### ISSUE TITLE
C++ code intelligence

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#10]
Support C++ on Sourcegraph

**Comment by chrismwendt** [comment]
Experimental C++ support has been shipped in Sourcegraph 2.8! Check out the blog post https://about.sourcegraph.com/blog/code-intelligence-for-more-languages-and-lsp-language-server-protocol-support

![image](https://user-images.githubusercontent.com/1387653/40390495-4a06a624-5dca-11e8-886b-bc0e1524f97c.png)

Thanks go to [LLVM](https://clang.llvm.org/extra/clangd.html) (and [Chilledheart/vim-clangd](https://github.com/Chilledheart/vim-clangd) for providing prebuilt binaries) for providing the language server.

**Comment by zhaojh329** [comment]
Support C ?

**Comment by mbautin** [comment]
How do current C++ indexing capabilities of Sourcegraph compare to those of Mozilla's DXR? ( https://github.com/mozilla/dxr )
Specifically, is there any support for C++ indexing using a clang plugin, and building an index in a system like Elasticsearch upfront?
As far as I know, clangd does not do any indexing upfront, it just does on-demand parsing of a given file, although this might change in Clang 8 and later.

**Comment by chrismwendt** [comment]
DXR appears much more advanced, using output from an instrumented C compiler. Except for indexed text search, Sourcegraph does not build an index up front. Many of the [programming language Sourcegraph extensions](https://sourcegraph.com/extensions?query=category%3A%22Programming+languages%22) use ctags + search on the fly. Go, TypeScript, and Python each have language server modes for more precise code intelligence.

**Comment by chrismwendt** [comment]
C/C++ code intelligence has been added in Sourcegraph 3.0 :tada:

https://about.sourcegraph.com/blog/sourcegraph-3.0#code-intelligence-for-all-languages

[Try it out](https://sourcegraph.com/github.com/torvalds/linux@aa0c38cf39de73bf7360a3da8f1707601261e518/-/blob/arch/arm/mach-footbridge/dc21285.c#L263:34) on Sourcegraph.com:

![image](https://user-images.githubusercontent.com/1387653/54005876-fb6c3b80-410f-11e9-8d93-2a8d73b7a175.png)
