### ISSUE TITLE
Indexer throws error in log for empty repos.

### ISSUE THREAD

**Issue by mrubinsk** [sourcegraph/sourcegraph#100]
- **Sourcegraph version:** 
Sourcegraph 2.9.1
- **Platform:** 
Ubuntu 16.04
Repositories hosted on VisualStudio Team Services git server.
#### Steps to reproduce:

1. Add configuration for repository that contains no files. Of note, this particular repository has commit history, it's just that at the moment, the latest commit left the repository empty.
2. Watch logs

#### Expected: 

Nothing - or at the minimum a warning/notice, not an error.

#### Actual:
 15:39:05        indexer | t=2018-06-25T15:39:05+0000 lvl=eror msg="Index failed" repo=AugmentedReality rev= isPrimary=false error="Repos.GetInventory failed: internal API response error code 404: \n (http://127.0.0.1:3090/.internal/repos/inventory-uncached)"

**Comment by keegancsmith** [comment]
Thank you for the report. We will tackle this in before the next minor release.

**Comment by sfllaw** [comment]
@keegancsmith This is still happening on Sourcegraph 2.10.0:

>20:43:40 indexer | t=2018-08-02T20:43:40+0000 lvl=eror msg="Index failed" repo=github.example.com/user/empty-repo rev= isPrimary=false error="Repos.GetInventory failed: internal API response error code 404: \n (http://127.0.0.1:3090/.internal/repos/inventory-uncached)"

**Comment by nicksnyder** [comment]
The fix is in master and will be released with 2.10.1

**Comment by mrubinsk** [comment]
Just a note that this is still happening in 2.10.2

**Comment by keegancsmith** [comment]
Damn! Ok will take a look.

**Comment by sqs** [comment]
This error appears to be harmless, just annoying. It occurs when the indexer is building the index of cross-repository references and encounters an empty repository. It should just suppress the error.

Indexer is being removed in 3.0 (next major release), and we do not plan to fix this issue before then, so I am going to close this.
