### ISSUE TITLE
Internal Server Error on badge request to unindexed domain

### ISSUE THREAD

**Issue by 6543** [sourcegraph/sourcegraph#10000]
request: `GET https://sourcegraph.com/code.gitea.io/sdk/gitea/-/badge.svg`

return: 500

expect: message witch tel this domain is not indexed or similar

**Comment by 6543** [comment]
pleace correct the title so it matches the bug desc more :) [I'm bad at this]

**Comment by unknwon** [comment]
The repository is in fact not exist on sourcegraph.com, so the error should be 404 not 500. The root cause _may_ be similar to https://github.com/sourcegraph/sourcegraph/issues/9274, cc @asdine in case you find anything useful while working on #9274.

**Comment by notjrbauer** [comment]
https://sourcegraph.com/code.gitea.io/sdk/gitea/-/badge.svg 404's now, but it assumes its searching a repo `repo:^code\.gitea\.io/sdk/gitea$`

**Comment by unknwon** [comment]
@asdine Please help verify if https://github.com/sourcegraph/sourcegraph/pull/10182 resolved this issue (claims so), if yes, we can then close this one.

**Comment by 6543** [comment]
I cant reproduce it anymore - think it fixed it :tada:

**Comment by 6543** [comment]
reopen If I missed something
