### ISSUE TITLE
Use net/http/httptrace to trace HTTP client requests

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#10007]
Problem: Some customers experience network connectivity issues between different services in Sourcegraph. In debugging issue where requests from service X to service Y fail, we don't have an easy way to determine if the request is at all making it to service Y (vs. the request makes it to service Y and some error occurs in service Y, or the request never leaves service X due to an error that happens in service X).

Proposed solution: Add https://golang.org/pkg/net/http/httptrace/ to our HTTP clients throughout the Sourcegraph backend. This will ensure there is a span corresponding to each HTTP client request in a trace, which can be used to determine if the issue is due to network connectivity or something else. (E.g., if a span exists for the HTTP client request, but not the corresponding HTTP handler in the receiving service, that implies that the error lies between the HTTP client and the HTTP server.)

More context in this [Slack thread](https://sourcegraph.slack.com/archives/CJX299FGE/p1585674985106700).

**Comment by uwedeportivo** [comment]
so it seems like we're mostly covered already and there is not much to do here.

i followed the code and all our http clients that do internal requests have roundtrippers that do the right thing: 

they use http://github.com/opentracing-contrib/go-stdlib/nethttp

for example:

https://github.com/sourcegraph/sourcegraph/blob/b1ddeff4a2b94ceccda7cdf7021d5f82aa4522ed/internal/gitserver/client.go#L869

this enables a trace to be marshalled over a rpc and spans from client and server be linked:

![trace](https://user-images.githubusercontent.com/534011/80748539-ec95d480-8ad9-11ea-8ee3-b4a57314b58d.png)

i looked at our architecture diagram (https://github.com/sourcegraph/sourcegraph/blob/master/doc/dev/architecture/index.md) to follow the arrows and looked at the client and server code and i think we're covered.

i'm going to close this issue but feel free to re-open if i missed a link and we have unconnected spans.
