### ISSUE TITLE
Docs: document that NFS storage should be avoided

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#10010]
NFS storage causes issues, especially when used for critical, performance-sensitive services like gitserver and indexed-search. We should strongly advise customers against it when spinning up Sourcegraph.

**Comment by dadlerj** [comment]
Issue that has been hit by:
* https://app.hubspot.com/contacts/2762526/company/1749029033
* https://app.hubspot.com/contacts/2762526/company/2931649618

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
