### ISSUE TITLE
Copy query button

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#10020]
#### Feature request description

Add a button in the search bar to copy the entire query. It's not currently possible to copy the entire raw query easily, since patternType and case filters are removed and put into toggles. We should add an easy way to do so.

Context: https://sourcegraph.slack.com/archives/C0W2E592M/p1582646381006600

Also needs to solve the problem for interactive mode, where filters are in separate inputs. 

See https://docs.google.com/document/d/1AtaJ8XvhDskcZOQtynuLKYq8thd727nI7baWNGGuEkU/edit?disco=AAAAGdpygKY for Garo's feedback on this.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
