### ISSUE TITLE
Reduce coupling in campaign store tests

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#10022]
The tests should be broken up into smaller units that can be run independently. There is currently too much shared state between tests which means they all need to be run in the correct order.

We should do more set up / teardown per test. This will be slower, but should allow us to run them in parallel so actual time to run them should stay about the same.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
