### ISSUE TITLE
Add puppeteer integration tests

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#10037]
We should have integration tests that allow us to test UI flows without needing a Sourcegraph backend. See https://github.com/sourcegraph/sourcegraph/pull/9591 for an example of what this might look like.

As part of these tests, we should expand our Percy screenshot test coverage.

Code coverage of these tests should be tracked.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by felixfbecker** [comment]
We now have an integration test suite running in CI! 🎉
 
I filed follow-up issues for the possible improvements.
