### ISSUE TITLE
No LSIF hovers on green part of the diff

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#10036]
I was reviewing https://github.com/sourcegraph/sourcegraph/pull/10035/files and noticed I could not get any hovers on green parts of the diff, but the red and white parts worked fine. The LSIF GitHub actions had completed already.

I verified in the background page network panel that the hovers came back as `null`:

![image](https://user-images.githubusercontent.com/10532611/79757551-8ad8ac00-831c-11ea-9434-25ecd4613c52.png)

and definitions empty:

![image](https://user-images.githubusercontent.com/10532611/79757646-aba10180-831c-11ea-9269-6307773eef02.png)

Request:

![image](https://user-images.githubusercontent.com/10532611/79757676-b22f7900-831c-11ea-9e2d-3a8851b4cc9c.png)

**Comment by efritz** [comment]
The DotCom LSIF queue is backed up at the moment and fixing the performance of the worker is already my current top priority. This working as expected, but may be an example of where some additional UX work needs to be done.
