### ISSUE TITLE
Don't parse filters in the main search bar in interactive mode

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#10030]
Currently, the main search input in interactive mode still accepts and parses filters. In the original RFC, we didn't want the input to parse filters

The `content` filter accepts any string, and matches it exactly. Using this, we can make the main search field interpret its input literally, and treat it only as the search match, forcing users to use the UI buttons to add filters to their queries.

Why is this better?
- It solves the problem of not being able to search for colons in the main search input when using literal search in interactive mode, and any other syntax bugs that may arise from any special characters that are added.
- The query becomes unambiguous: the main search field shows the pattern to be matched, and the UI buttons and fields show the filter conditions.

What needs to be considered?
- How do we communicate to users that filters aren't being parsed in the main input in interactive mode, while the same search bar _does_ parse filters in plain text mode? Should there be some visual indicator, if so, what does this look like?
- How does this impact AND/OR queries in the future? Currently, we could still support AND/OR filters in interactive mode with no additional work, since AND/OR would get parsed. If we did treat the input as just content, then we'd need an alternative UI (which we plan on doing anyways, but down the line).

- [ ] Write an RFC to propose a solution
- [ ] Rough designs of the correct solution
- [ ] Implementation

**Comment by attfarhan** [comment]
Bumping to 3.17 since I'll be focusing on version contexts.

**Comment by poojaj-tech** [comment]
Closing as we've decided to not support interactive mode moving forward.
