### ISSUE TITLE
Add monitoring for syntax highlighting vs. gitserver perf

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#10049]
As noted in https://github.com/sourcegraph/sourcegraph/issues/8433#issuecomment-611676781

**Comment by slimsag** [comment]
Note:

- For syntax highlighting perf, we'll want to add a prometheus metric around this code: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@9c12ed5f27b238abc071c7d2f83cfaac0f0af32f/-/blob/internal/highlight/highlight.go#L99
- For gitserver (i.e. file content fetching) we just need to measure the call to `Content` here: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@9c12ed5f27b238abc071c7d2f83cfaac0f0af32f/-/blob/cmd/frontend/graphqlbackend/virtual_file.go#L73-76

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
