### ISSUE TITLE
k8s: Deploy jaeger-agent as a Daemonset instead of sidecar container

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#10052]
From Yuri Shkuro (the main jaeger dev) on deploying jaeger-agent as a Daemonset vs sidecar container:

> It's certainly possible and even recommended. A sidecar deployment for jaeger-agent is only useful in multi-tenant scenarios. See this blog post for discussion on various deployment options: https://medium.com/jaegertracing/deployment-strategies-for-the-jaeger-agent-1d6f91796d09

Reasons:
* 1 daemonset per node is typically less than 1 sidecar per pod
* Jaeger OOMing will not cause the whole pod (including the actual service) to be evicted

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by daxmc99** [comment]
While investigating this, it looks like the Daemonset deployment depends on the usage of the Jaeger operator and they have deprecated the pure yaml deployment options https://github.com/jaegertracing/jaeger-kubernetes and now prefers the operator for all **Deployment** types except for manually adding the containers as sidecars. 

Are we fine with proceeding with the Operator based deployment? I think this is the obvious path forward if we are looking for using daemon sets. My only concern here is if we expect to deploy Sourcegraph into multi-tenant environments which may already have Jaeger deployed. There can be only 1 operator per cluster. In those cases, we would need to advise a potential user to add Sourcegraph to their Jaeger configuration.

**Comment by beyang** [comment]
If using the Daemonset requires using the operator, then let's abandon the change. Might be more resource intensive, but that's better than using a mechanism that would prevent including Jaeger by default.

**Comment by daxmc99** [comment]
Closing for now. If we decide this is a must-have then we can investigate the experimental option of using the [operator to generate YAML](https://github.com/jaegertracing/jaeger-operator#experimental-generate-kubernetes-manifest-file). I still believe the manually added jaeger sidecars provide more flexibility in supporting a wider variety of deployments.
