### ISSUE TITLE
RFC 142: Migrate backend e2e test with integration tests

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#10068]
This issue tracks the progress of migrating suitable e2e tests to integration tests after [auditing existing e2e tests](https://github.com/sourcegraph/sourcegraph/issues/9924).

**NOTE**: I have no idea how long integration tests would take, so hold 8 days for it for now.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
