### ISSUE TITLE
Get RFC 142 approved based on info from auditing

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#10066]
~~Blocked by https://github.com/sourcegraph/sourcegraph/issues/9924~~

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
