### ISSUE TITLE
RFC 142: Migrate backend e2e test with unit tests

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#10067]
This issue tracks the progress of migrating suitable e2e tests to unit tests after [auditing existing e2e tests](https://github.com/sourcegraph/sourcegraph/issues/9924).

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
