### ISSUE TITLE
Include "Campaign credits" in pings

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#10073]
We should include "Campaign credits" in pings to allow us to cost campaign usage.

For now, we'll track the number of PR's opened via campaigns but we're calling it "Campaign credits" to give us flexibility in future.

Note, updates to existing PR's should not cause double counting.

**Comment by ryanslade** [comment]
Instructions for adding data to pings:
https://about.sourcegraph.com/handbook/engineering/adding_ping_data

**Comment by mrnugget** [comment]
I think it also makes sense to include the "number of merged changesets" in here, since that's required for our [OKRs](https://docs.google.com/document/d/1fAB7HMD7rmcyI68f2WuMAvt3uf0UqIruFvKhJUHMCyY/edit?ts=5e991ac5):

> KR: ≥20 organizations have created campaigns, and at each of those organizations they have merged ≥20 campaign changesets

**Comment by ryanslade** [comment]
RFC ready: https://docs.google.com/document/d/1CfVoYNVphduuQmZOQAivmyCmFTYF_6-vBpugAgHLcAc
