### ISSUE TITLE
Extension area header is flush with sides of screens, needs padding

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1008]
![screenshot from 2018-11-14 23-38-28](https://user-images.githubusercontent.com/1976/48537426-6c889a00-e866-11e8-94f3-36d6f78f9fad.png)

**Comment by sqs** [comment]
@francisschmaltz 	ping on this

**Comment by francisschmaltz** [comment]
@sqs was this fixed in https://github.com/sourcegraph/sourcegraph/commit/0e9843236ef09bdb5a2d638fe0c948e827a0e382

**Comment by sqs** [comment]
Yes
