### ISSUE TITLE
Improve visual clarity and add CTAs re code intel

### ISSUE THREAD

**Issue by gbrik** [sourcegraph/sourcegraph#10083]
The current UI leaves a lot of room for confusion when using hovers, go-to-defs, and find-refs. I want  the status of code intelligence to be visually clear both passively and when doing code intel things. I also want there to be specific explanations/instructions to improve the status of code intel when relevant. Some of this already exists.

If I were purely optimizing for precise code intel usability and adoption, I would want the following specific things:
- Badge/indicator somewhere prominent on the page, with 3 states: basic code intel, loading precise code intel, precise code intel
  - The basic code intel badge shouldn't be angry, but the precise code intel badge should be very happy :)
  - On the website, this lives in the top right bar next to git blame. (Or somewhere better? I don't UI enough to know how to place buttons).
  - In the code host extensions, this lives in the sourcegraph badge.
  - When hovering the badge:
    - the basic code intel state contains an explanation + CTA to add LSIF data
    - the loading badge contains more information about indexing progress
    - the precise code intel badge says which commit the data is coming from
  - This information is only relevant for source files in languages we currently have good precise code intel support, so we should show it selectively
- When hovering symbols:
  - When code intel isn't yet available, there is an error/loading indicator with an explanation for why it's not available
  - Otherwise, the hover card + find-ref results both also have the above badge

But I'm open to pushback/alternatives on everything.

cc @sourcegraph/web, thoughts on all of this? and if you were to implement it, what would the timeline be?

assigned to me while in planning phase, will re-assign/re-assess milestone when we decide what implementation looks like.

**Comment by lguychard** [comment]
cc @imtommyroberts as well 🙂

**Comment by felixfbecker** [comment]
I like this proposal, this matches what I had in mind here in my [RFC 139 feedback](https://docs.google.com/document/d/1dl5u03dD63-RZB7S1p2IqFTiVcdx6On0aeIOXgsTehA/edit#bookmark=id.ls6jzuycy5kj)
The good news is that this is mostly already possible with only changes requires in the code intel extensions!

> Badge/indicator somewhere prominent on the page, with 3 states: basic code intel, loading precise code intel, precise code intel

This is possible by having the code intel extension(s) contribute an action item, just like the blame button itself is one. Here's an example:  https://github.com/sourcegraph/sourcegraph-git-extras/blob/4dad2605f4b6c36b71b129ab6516ec4a0bfb6be0/package.json#L12-L40

> When code intel isn't yet available, there is an error/loading indicator with an explanation for why it's not available

What the extension could do with the current extension API is throw an error from  the hover provider. We currently don't display that, but I think we should change that behavior (and it's easy to do). The hover provider could also return any markdown content as a result that contains this hint.

The important thing that needs to be considered here is that we don't want to show hovers on tokens inside comments, whitespace, punctuation etc. This is indicated by the hover provider returning `null` for the position. So the hover provider should ensure to not throw an error/return the hint on _every_ call, but also check what was hovered and use the knowledge about the language to determine whether this position should generally not have a hover (afaik this data is available for basic code intel).

> Otherwise, the hover card + find-ref results both also have the above badge

@efritz had added a badge API for individual hover contents, where badge means a little icon next to the hover content with a tooltip.

As @lguychard said, I think this would be good for @imtommyroberts to make a design for (he had some WIP stuff already I think)

**Comment by gbrik** [comment]
working on design here:
https://www.figma.com/file/QOCGTlcc8ZF5EqMl1jwfsk/Code-Intel-UI

**Comment by nicksnyder** [comment]
cc @rrhyne

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by gbrik** [comment]
Superseded by #10891
