### ISSUE TITLE
Write RFC for precise code intel mono repo support

### ISSUE THREAD

**Issue by gbrik** [sourcegraph/sourcegraph#10087]
Currently our tooling & docs are written assuming the user will be uploading LSIF indexes for the entire repo on each commit. This works for repos with a small number of projects, but would probably make precise code intel unusable on a large monorepo 10s or 100s of projects. This issue is to create an RFC drawing on [RFC 101](https://docs.google.com/document/d/15UxJMWUy40hnoA7Eb35BwMfEtOcWmHTSiC_5N-xD36U/edit) proposing tooling features to address this use case.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by gbrik** [comment]
done https://docs.google.com/document/d/1NPu0Vc7FpdoYwCrtpnu-8KB4OPbw7L0KBTqw96JVc8w/edit
