### ISSUE TITLE
Precise code intel mono repo support

### ISSUE THREAD

**Issue by gbrik** [sourcegraph/sourcegraph#10086]
Currently our tooling & docs are written assuming the user will be uploading LSIF indexes for the entire repo on each commit. This works for repos with a small number of projects, but would probably make precise code intel unusable on a large monorepo 10s or 100s of projects. This issue is to create an RFC drawing on [RFC 101](https://docs.google.com/document/d/15UxJMWUy40hnoA7Eb35BwMfEtOcWmHTSiC_5N-xD36U/edit) proposing tooling features to address this use case.

**Comment by unknwon** [comment]
Identical to https://github.com/sourcegraph/sourcegraph/issues/10087?

**Comment by gbrik** [comment]
Yes, double submitted cause of the GitHub outage earlier, ty!
