### ISSUE TITLE
"Open in editor" feature

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#10093]
A user at https://app.hubspot.com/contacts/2762526/company/464956351/ requested the ability to open a file in your editor directly from Sourcegraph's search results page or file page. Primarily for Jetbrains-based IDEs, which have an existing `localhost` server URL you can redirect to in order to complete the open action.

Full context: https://sourcegraph.slack.com/archives/CMB6K7SMN/p1587499846168800

**Comment by slimsag** [comment]
There doesn't appear to be an editor (or even OS) independent way of implementing this FYI. Some references:

- https://github.com/shengyou/vscode-handler
- https://github.com/rubysamurai/sublime-url-handler
- https://youtrack.jetbrains.com/issue/IDEA-65879
- https://intellij-support.jetbrains.com/hc/en-us/community/posts/360002618219-Open-file-in-phpstorm-via-phpstorm-link
- https://github.com/sshkarupa/url-handlers

Look to Phabricator for how this can be done: https://secure.phabricator.com/book/phabricator/article/external_editor/

**Comment by felixfbecker** [comment]
I just hacked something together for VS Code: https://sourcegraph.com/extensions/sourcegraph/vscode-extras

**Comment by AlicjaSuska** [comment]
This issue seems to be connected with the planned improvements in the ['Extensions Discoverability'](https://github.com/sourcegraph/sourcegraph/issues/11872) project. We would like to add extensions for:
<img width="775" alt="Screenshot 2020-08-07 at 14 23 22" src="https://user-images.githubusercontent.com/20326070/89645368-efaf1680-d8b9-11ea-9067-f50b4af228fe.png">

**Comment by limitedmage** [comment]
Created a customizable extension here: https://sourcegraph.com/extensions/sourcegraph/open-in-editor

Code here: https://github.com/sourcegraph/open-in-editor-extension

**Comment by limitedmage** [comment]
Closing issue as extension is published :) Please feel free to file follow up issues related to the extension.
