### ISSUE TITLE
Sourcegraph continues to attempt to index repo after removed from config.

### ISSUE THREAD

**Issue by mrubinsk** [sourcegraph/sourcegraph#101]
- **Sourcegraph version:** 
2.9.1
- **Platform:** 
Ubuntu 16.04
#### Steps to reproduce:

1. Remove an existing repository from configuration. Of note, this repository is the same repository from https://github.com/sourcegraph/issues/issues/100 that was causing indexer errors.
2. Watch log

#### Expected: 

Nothing - see no attempts at trying to index the repository.

#### Actual:

Log continues to show errors resulting from attempts at indexing the repository:

15:39:05 indexer | t=2018-06-25T15:39:05+0000 lvl=eror msg="Index failed" repo=AugmentedReality rev= isPrimary=false error="Repos.GetInventory failed: internal API response error code 404: \n (http://127.0.0.1:3090/.internal/repos/inventory-uncached)"

**Comment by keegancsmith** [comment]
Thank you for the report. Like the other report this shouldn't affect any functionality, its just annoying log spam. We will tackle this in before the next minor release.

**Comment by nicksnyder** [comment]
Indexer will be completely removed in 3.0, so I am going to close this now.
