### ISSUE TITLE
spike: investigate caddy issues in dev environment 

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#10103]
See https://sourcegraph.slack.com/archives/C07KZF47K/p1586860609310400

@ggilmore hasn't able to reproduce this issue, but this is causing pain for some on @sourcegraph/web 

Next steps: 

- Ask other team members if they're running into this 
- If no, hop on a call with @felixfbecker to try to reproduce this, options:
	- reproduce this on a clean laptop
	- reproduce this on a extremely minimal example

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by slimsag** [comment]
I believe this hasn't been an issue since, so I am going to close this. If I am wrong please re-open.

**Comment by felixfbecker** [comment]
I still have this issue, just tested again with latest master. Caddy just doesn't work without any errors or indication why. I am still depending on my nginx workaround to have a usable dev environment. I also heard from other web teammates who occasionally had issues with Caddy.

**Comment by daxmc99** [comment]
Closing since we haven't seen this in awhile. Please reopen if it reoccurs 

Should we consider deprecating this for local-dev?

**Comment by daxmc99** [comment]
Maybe fixed in https://github.com/sourcegraph/sourcegraph/pull/10021
