### ISSUE TITLE
git history should have more info

### ISSUE THREAD

**Issue by shawnma** [sourcegraph/sourcegraph#1010]
Currently when you look at the history of a file, it has only git change id and summary. It would be better if we can have author and date information. It would be even better if we can have diff support for two versions.

**Comment by sqs** [comment]
@shawnma 	Just moved this issue to the main repository (https://github.com/sourcegraph/sourcegraph). 

What version of Sourcegraph are you using? The latest release (Sourcegraph 2.13) and https://sourcegraph.com have a new Git history view. See it at https://sourcegraph.com/github.com/sourcegraph/sourcegraph-git-extras/-/blob/package.json#&tab=history.

It includes the author and date info, and when you click on a commit, it takes you to the commit diff. Is this what you want? If so, just upgrade!

![screenshot from 2018-11-15 00-29-33](https://user-images.githubusercontent.com/1976/48539943-88436e80-e86d-11e8-9c72-5ae8f04ffd85.png)

**Comment by shawnma** [comment]
Ah nice. I guess our company is using an old version. thanks!

(how do I know which version is running?)

**Comment by ryan-blunden** [comment]
The path is `/site-admin/updates`

**Comment by shawnma** [comment]
No. Not an admin. Got 403. Maybe should file a bug to show version number in the (?) menu.

**Comment by keegancsmith** [comment]
We have a sneaky URL at `/__version` which should work for you.
