### ISSUE TITLE
spike: investigate what it would take to export GCP billing information to BigQuery

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#10101]
Part of https://docs.google.com/document/d/1PUM_6xR_upvrMoHurU056QFfe8JK6HvCVEdTaZiFeYs

> Cost accounting (GCP billing): Investigate what it would take to export GCP billing information to BigQuery (https://cloud.google.com/billing/docs/how-to/export-data-bigquery) for further processing via `cost-category` labels. 
> 
> Time box to 1.5 day. 
> 
> Verify with @dadlerj  that this is an improvement.
>

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by slimsag** [comment]
We haven't done this yet and are moving to more isolated GCP projects, so this is less important I think. Closing, but feel free to reopen.
