### ISSUE TITLE
RFC 141: Prototype generating manifests, rather than directly editing deploy-sourcegraph

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#10100]
Implement generated manifests for Kubernetes as described in [RFC 141](https://docs.google.com/document/d/1tsksAlqe77NmdPLw7oyy2u0-1rYDQeVpPeDo1T0Xt50)

**Comment by ggilmore** [comment]
prerequisites:


- https://github.com/sourcegraph/sourcegraph/issues/10145
- https://github.com/sourcegraph/sourcegraph/issues/10143

**Comment by slimsag** [comment]
Question/challenge: If we generated a deploy-sourcegraph repository variant for each possible customization combination instead, would that not be better for customer's in terms of upgrading/managing?

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
