### ISSUE TITLE
Discuss/plan how we can improve scaling documentation of Sourcegraph

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#10102]
Part of RFC 131 https://docs.google.com/document/d/1PUM_6xR_upvrMoHurU056QFfe8JK6HvCVEdTaZiFeYs/edit#

> “Dot-com”: interview various team members (especially @slimsag ) for their context on the “I personally don’t have a good grasp on” questions. Their answers would be translated in to docs pages / resource recommendation guides for our customers. Such a guide helps both our users and our own team. Learnings from this guide can be used to identify concrete next steps to take with the sourcegraph.com infra

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by pecigonzalo** [comment]
Closing as this is not a priority at the moment and the context at the time this might be worked on will potentially make this stale.
