### ISSUE TITLE
spike: investigate supporting restricted or-expressions for repos

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#10113]
The end goal is to support `repo:foo or repo:bar`...

Our regexp support can possibly support the above by transforming such queries. Alternatively, it could be implemented natively. The challenge is to restrict to what extent or-expressions can apply in the interest of #9425 (i.e., validation), and perhaps not generally at first.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by rvantonder** [comment]
Closing: this will be supported as a result of #10623
