### ISSUE TITLE
Implement repo or-expressions for multi repo/multi rev

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#10114]
I'll adjust this estimate based on #10113. For now this is a thumbsuck.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by rvantonder** [comment]
Closing: this will be supported as a result of #10623
