### ISSUE TITLE
Script to flag GCP and AWS resources that are unexpected / wasteful

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#10116]
Is there a simple script we could write that does the following?
* query the GCP and AWS APIs for all compute resources tied to our billing account
* compare these against a git-vendored list of expected resources (e.g., resources associated with *.sgdev.org or sourcegraph.com)
* alert someone (or a Slack channel) when unexpected resources exist

**Comment by bobheadxi** [comment]
How I'm thinking of tackling this:

* implement `unknown-resources` as a `internal/cmd`, similar to `tracking-issues`
    * this tool will query the necessary APIs to list compute resources and report it to a Slack channel
* run via Actions, similar to `tracking-issues`:
    * on cron (once a day?)
    * via [repo dispatch](https://developer.github.com/v3/repos/#create-a-repository-dispatch-event)

I'll probably aim to put up a PR when I get this to simply report a complete (?) list of resources. How does that sound @ggilmore?

**Comment by ggilmore** [comment]
This sounds reasonable. The only thing that I don't know is if this script should live in sourcegraph/sourcegraph versus a separate repository. Can @sourcegraph/core-services weigh in on whether or not a tool should be added to `internal/cmd`?

Note that the answer to this this shouldn't block you @bobheadxi from progressing on the tool

**Comment by slimsag** [comment]
> my project planning doc suggests that this runs as a kube service, but I'm thinking it should run via Actions, similar to tracking-issues:

That sounds like a great idea to me! I was the one who originally wrote as a kube service -- but I agree a GitHub action is better for it!

**Comment by slimsag** [comment]
> With a v0 when I get this to simply report a complete (?) list of resources.

I think the ideal end state here would be "report daily the resources that have been added/changed since last week", so that if e.g. someone spins up something we would get notified daily about it for 7 days. Then, if nobody addresses it the script would stop reporting it to us and accept it as "something we want running constantly"

**Comment by slimsag** [comment]
(edited my last message)

**Comment by bobheadxi** [comment]
> in case your implementation (e.g. github actions) boxes you in, in some way (such as not having persistent storage)

Hm, in that case I'm thinking an Action-based implementation could just use whatever mechanism an alternative implementation would have leveraged in the same way (in Cloud Storage for example)

**Comment by unknwon** [comment]
> This sounds reasonable. The only thing that I don't know is if this script should live in sourcegraph/sourcegraph versus a separate repository. Can @sourcegraph/core-services weigh in on whether or not a tool should be added to `internal/cmd`?
> 
> Note that the answer to this this shouldn't block you @bobheadxi from progressing on the tool

Source code lives in `internal/cmd` SGTM, and 👍 for running it as GitHub Action (big fan of it now 😄) just double check that if we have any sensitive output, run the GitHub Action in a private repository.

**Comment by keegancsmith** [comment]
I think it living in its own repo also makes sense, especially if you go with github actions since you will need a repo for the action anyways. Then the repo for the action and the command can be the same repo.

**Comment by bobheadxi** [comment]
> since you will need a repo for the action anyways

You can run Dockerfiles directly as well (aside: maybe the issue tracker action should do this too?), so I don't think a separate repo is strictly needed

[reference](https://help.github.com/en/actions/building-actions/creating-a-docker-container-action#example-using-a-private-action)

```yml
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
```

**Comment by tsenart** [comment]
> maybe the issue tracker action should do this too?

That’s what it does :-) https://github.com/sourcegraph/sourcegraph/blob/81ef3584d8d0f2353968cd79c8a9e8d68c01710e/.github/workflows/tracking-issue.yml#L22

Sent via Superhuman iOS ( https://sprh.mn/?vip=tomas@sourcegraph.com )

**Comment by bobheadxi** [comment]
@tsenart from what I understand that uses a published docker image (`uses: docker://sourcegraph/tracking-issue:latest`), whereas I'm referring about running it from source (`users: path/to/my/dockerfile/dir`) which doesn't require the [additional publish step](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@59b278cd3378b7cfbfa37af1efc95f09dd17d414/-/blob/internal/cmd/tracking-issue/README.md#deployment)

**Comment by daxmc99** [comment]
https://github.com/cloud-custodian/cloud-custodian can be helpful here as well

**Comment by bobheadxi** [comment]
`cloud-custodian` seems like quite something to set up 🤔

**Comment by tsenart** [comment]
> @tsenart from what I understand that uses a published docker image (uses: docker://sourcegraph/tracking-issue:latest), whereas I'm referring about running it from source (users: path/to/my/dockerfile/dir) which doesn't require the additional publish step (though maybe this is intentional)

Ah, interesting. I didn't know about that option. I wonder whether that means we pay the cost of building the image at run-time, which if so, might make sense for this script, since there are not user latency considerations involved, in contrast to the tracking issue tool.

**Comment by slimsag** [comment]
@bobheadxi I gave this a rough estimate, feel free to alter if you think I'm off
