### ISSUE TITLE
Write RFC for syntax that supports multiple repos and revisions to support RFC 136

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#10111]
The RFC should cover the points that:

- It targets functionality of #9425 with a sustainable/maintainable syntax
-  Is valuable to incorporate into `repogroup` as per #9712 
   - E.g., create a repo group using query expressions like `repo:a@b or repo:c`, ....
   - Associated syntax that would go in config options (I'll probably need a couple of hours to look into how best this could work to inform the solution in the RFC, so tacking on ~0.5d conservatively)

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by rvantonder** [comment]
Closing. Multi-repo/multi-rev support will come naturally as part of #10623 at a later stage (not in the RFC 136 timeline)
