### ISSUE TITLE
Automated/transparent indexing

### ISSUE THREAD

**Issue by gbrik** [sourcegraph/sourcegraph#10130]
The biggest advantage of providing precise code intel via LSP is that people could navigate to a repo and it would 'just work'.

This issue is to brainstorm/investigate how possible this would be with LSIF-based indexing and what the limitations would be.

Brainstorming doc [here](https://docs.google.com/document/d/1_t7XjlWaahiQQv2VrsvMH0H63CZTZLamhzlxAT6HuJE/edit).

cc @sourcegraph/code-intel

**Comment by efritz** [comment]
We've launched an auto-indexer and are continuing to do improve that product. Closing this issue as it's now off the ground.
