### ISSUE TITLE
Sourcegraph Extension buttons don't appear on rendered markdown files

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#10135]
Repro: visit https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/CHANGELOG.md

![image](https://user-images.githubusercontent.com/5589410/80007813-a8705780-847b-11ea-890c-3e2517e827ce.png)

After clicking on "Raw", the buttons DO appear, even when you then subsequently switch back to "Formatted"

**Comment by felixfbecker** [comment]
I think this is because the `Blob` (not `BlobPage`) activates extensions, but is not rendered at all in "rendered markdown" mode

**Comment by tjkandala** [comment]
This was fixed by #17999
