### ISSUE TITLE
Filters/scopes overlap with search type tabs in Safari

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#10147]
Reported by a user at https://app.hubspot.com/contacts/2762526/company/768958891

![image](https://user-images.githubusercontent.com/5589410/80056281-b56f6400-84d8-11ea-9ff8-0cc43ab17c2b.png)

Browser is Safari, and potentially of note, the following banner has not yet been cleared from the top of the instance:

![image](https://user-images.githubusercontent.com/5589410/80056318-cae48e00-84d8-11ea-903e-de5c8688b306.png)

**Comment by felixfbecker** [comment]
@attfarhan it looks like you wrote the CSS for this, would you be able to take this on?
