### ISSUE TITLE
`src-expose serve` doesn't work with Git submodules (where .git is a file, rather than a dir)

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#10140]
Reported by https://app.hubspot.com/contacts/2762526/company/768958891

@keegancsmith provided a special src-expose build to the prospect at https://sourcegraph.slack.com/archives/CTJCMDCCS/p1587131251161000?thread_ts=1587086215.160000&cid=CTJCMDCCS where it would recurse into subdirectories to find child git repos

Unfortunately, after updating to this version and running `src-expose serve ./` from the parent directory, he saw a long list of errors back for each of the git submodules:

```
serve: 2020/04/22 14:32:39 configuring repo at <parent>/<submodule>/.git: updating server info: : fork/exec /home/<user>/git/bin/git: not a directory
```

The .git files in each git submodule (not directories) have the format:

```
gitdir: ../path/to/.git/<something>
```

(I didn't get the specific path format here ^^)

**Comment by keegancsmith** [comment]
Do they want us to export the submodules as well? Right now I will fix the bug, exporting the submodules is quite a bit more work and I am unsure if worth it. It would make more sense if they init the submodules / ensure they are checked out.

**Comment by keegancsmith** [comment]
So this only affects this customer, since we don't recurse into non-bare repos outside of the special case for the customer. I will update the branch for that customer and push a simple fix.

FYI the branch is here. Will update and close this issue once done. https://github.com/sourcegraph/sourcegraph/tree/core/src-expose-recurse

**Comment by dadlerj** [comment]
Thanks for the quick turnaround @keegancsmith!

Just to check — I think by default, we _don't_ serve the submodules inside of the parent repo at all (the parent repo shows _links_ to them, but you can't access the code, right?).

So the recommendation here is that they have to run git init in those submodules for them to be visible/available on Sourcegraph?

I think (?) we support sub-modules automatically through other/standard (i.e. non-src-expose) external services, so just want to clarify.

**Comment by keegancsmith** [comment]
> Just to check — I think by default, we _don't_ serve the submodules
> inside of the parent repo at all (the parent repo shows _links_ to
> them, but you can't access the code, right?).

Yes, the parent repo will show links to them but we won't expose
them. The more I think about it, the more this seems like the correct
approach. Since the path to the submodule shouldn't be the name of the
repo.

> So the recommendation here is that they have to run git init in those
> submodules for them to be visible/available on Sourcegraph?

If it isn't exported in any other way, then yes. Alternatively they
add those submodules to Sourcegraph in another external service (eg if
they are dependencies from GitHub), or they keep git clones in the
appropriate place under src-expose serve.

> I think (?) we support sub-modules automatically through
> other/standard (i.e. non-src-expose) external services, so just want
> to clarify.

Yes, when browsing a repo we understand submodule files. So we will
resolve them. We won't automatically start cloning them/etc. Rather they
need to be repos that are also on the instance.

**Comment by dadlerj** [comment]
@keegancsmith sorry for commenting on this after a while, but I was checking out https://github.com/sourcegraph/sourcegraph/commits/core/src-expose-recurse (when sending a link to the build that recurses into sub-dirs for https://app.hubspot.com/contacts/2762526/company/693777200) and I noticed that there don't seem to be any changes there related to that feature. It only contains the "ignore .git files" change, and merging in master. 

Just to check, is the branch that DOES make that update available? Or did I miss it there?

**Comment by keegancsmith** [comment]
@dadlerj "where .git is a file, rather than a dir" I fixed that by making a change in master which is included in that branch (the reason I did the merge) 1af15c3501915bd7adb15e4e1c9029889aad04bf

**Comment by dadlerj** [comment]
This has now been requested by https://app.hubspot.com/contacts/2762526/company/578600789 as well.

@keegancsmith in your message from April 24 you wrote:

>If it isn't exported in any other way, then yes. Alternatively they
>add those submodules to Sourcegraph in another external service (eg if
>they are dependencies from GitHub), or they keep git clones in the
>appropriate place under src-expose serve.

But given submodules don't have their own .git directory, if I run `git init` in them, then wouldn't all history be lost? 

Is there any better way to serve a repo that contains submodules that retains submodule-level history? What if there was a constraint that they wanted to use src-expose, since they want to create generated files/etc. before serving?

>Do they want us to export the submodules as well? Right now I will fix the bug, exporting the submodules is quite a bit more work and I am unsure if worth it. It would make more sense if they init the submodules / ensure they are checked out.

I think better support for .git _files_ (i.e., those that point to some external .git directory) in general makes a lot of sense here, and I think this pretty heavily overlaps with usage of src-expose. Curious to hear any input you may have on this.

**Comment by keegancsmith** [comment]
@dadlerj and I chatted over VC about this. Still unclear if we should directly support submodules as-is. The reason submodules are problematic is they are just a link to another remote repo. Two approaches I can think of are src-expose clones and manages them or tells Sourcegraph to. In both cases this increases complexity a bunch, and it isn't clear that either can clone the repo. Additionally questions like what name should they appear as / etc are not clear.

I suspect the solution is if a user wants submodule links to work, they configure an external service to clone them or they clone them into a directory that src-expose exports.

**Comment by keegancsmith** [comment]
Closing out, since there is a work-around and I think this will likely remain out of scope for src-expose.
