### ISSUE TITLE
Repogroup autocomplete

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#10141]
Reported by https://app.hubspot.com/contacts/2762526/company/768958891

Unlike most search filters, the `repogroup:` filter doesn't provide any autocomplete options. It would be nice to pull them from settings and make this possible!

This is _related_ to RFC-136 (which would solve the need for this user), but this would be beneficial on its own regardless, even if not a priority yet.

**Comment by unknwon** [comment]
FYI, I have `searchFilterSuggestion` that returns repo groups of a user, I think it's just not used: https://github.com/sourcegraph/sourcegraph/blob/master/cmd/frontend/graphqlbackend/search_filter_suggestions.go#L12

**Comment by dadlerj** [comment]
Yeah, interesting — looks like the frontend never calls this API https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24%40d371aba+SearchFilterSuggestions+lang:typescript+-file:%28test%7Cspec%29+&patternType=literal
