### ISSUE TITLE
spike: investigate cue for deploy-sourcegraph 

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#10143]
Related: 
- https://github.com/sourcegraph/sourcegraph/issues/10100
- https://github.com/sourcegraph/sourcegraph/issues/10063

In [RFC 141](https://docs.google.com/document/d/1tsksAlqe77NmdPLw7oyy2u0-1rYDQeVpPeDo1T0Xt50), we're exploring new configuration mechanisms for deploy-sourcegraph. As stated in the RFC, the main requirements for a solution are:

> - **[ Should not require customers to resolve git conflicts in the base Kubernetes manifests ]** 
> - Should not add friction to the initial installation process
> - Should not require customers to learn a substantial new domain of knowledge (e.g., a DSL)
> - Should not conflict with other tools customers use to deploy and manage Kubernetes clusters
> - Should be simple and easy to reason about
> - Should be extensible by customers if they want customizations we have not yet thought of

RFC 141's proposed solution involves using bash scripts (plus `yj` and `jq`) to manipulate the base manifests. This solution has a few pitfalls:

- Using bash isn't type-safe. As mentioned by @uwedeportivo, this approach is similar to just using something like `sed` - the tool has no knowledge of yaml or kubernetes schemas so it's possible for it to make syntactic and semantic errors 

- Running multiple customization bash scripts isn't guaranteed to be [commutative ](https://en.wikipedia.org/wiki/Commutative_property). Off the shelf ways I can think of to solve this would be very complex and hard to maintain (total ordering of bash scripts, making all bash scripts aware of each other's existence). 

---

[Cue](https://cuelang.org/) is a tool that I think can address some subset of these issues and a few more:

- **Main benefit relevant to this issue**: can be run as a validation layer on top of deploy-sourcegraph and our provided customization bash scripts. (can typecheck our definitions against offical kubernetes api defnitions, can write our own validations - example ensuring that the number of gitserver replicas is always in sync with the `SRC_GIT_SERVERS` env var 

- Extra benefits:
	- *relevant to our development*: Can use cue to import / generate our existing kubernetes manifests and can reduce boilerplate 
	- *relevant to our development*: Can share configuration between different environments and deployment targets (example: publish core definitions in sourcegraph/sourcegraph, import / tweak them in deploy-sourcegraph, deploy-sourcegraph-dot-com, deploy-sourcegraph-docker, etc.)
	- *relevant to our customers*: cue includes a scripting layer that lets you define custom commands -  users can drive cue with cli commands + bash scripts 

What I plan to do in the spike: 

- Run through https://github.com/cuelang/cue/blob/v0.1.0/doc/tutorial/kubernetes/README.md
- Use cue to render our existing deploy-sourcegraph yaml manifests
- Implement a basic customization to our manfiests (e.g. tuning gitserver's replica count)
- Try using cue as a validation layer on top of bash script transformations 

Questions I want to answer:

- Ease of picking up cue's language, syntax, and semantics
- What our development workflow of using cue would look like
- Is cue a viable option for generating deploy-sourcegraph manifests
- Is cue a viable option for applying a validation layer for manifests that both @sourcegraph and our users can run

**Comment by uwedeportivo** [comment]
👍

**Comment by ggilmore** [comment]
see https://github.com/sourcegraph/sourcegraph/issues/10937
