### ISSUE TITLE
Discussion: enforcing clone/update limit on repo-updater

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#1015]
The new repo-updater scheduler assumes that [update requests to gitserver](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@master/-/blob/cmd/repo-updater/repos/scheduler.go#L152) are synchronous, [as documented here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/gitserver/server/server.go#L441).

This assumption is violated in [the case where the repo needs to be cloned](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/gitserver/server/server.go#L466:15).

One reason I thought it would be nice to have repo-updater enforce this limit is because it seemed like it should be the source of truth for updates. Another reason is that it could apply this limit across multiple gitserver replicas.

Given that there are [other code paths on gitserver](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@master/-/blob/cmd/gitserver/server/server.go#L210:16) which can cause a clone (e.g. exec), and the additional complexity in making the clone case synchronous (do we really want a network request hanging for minutes for large repos?), I am inclined to remove the rate limiting in the new scheduler (which will even further simplify it) and leave the rate limiting in gitserver where it has always been.

Thoughts @keegancsmith ?

**Comment by keegancsmith** [comment]
Should we remove those other paths that can cause a clone in gitserver? That way we have one place only that is responsible for deciding this. It also removes the weird stuff we have around sometimes requiring a remote URL in gitserver, and move that responsibility just to repo-updater. We were working towards that goal a while ago, but I am not beholden to it. But it would be nice to remove that bit of complexity in gitserver.

**Comment by nicksnyder** [comment]
I didn’t look into it deeply, but it isn’t clear to me what current logic depends on exec implicitly cloning/updating and whether it makes sense to require any such existing logic to go through repo-updater instead of contacting gitserver directly.

I agree that the clone limiting logic in gitserver seems rather complicated.

**Comment by nicksnyder** [comment]
Closing this discussion and cc-ing @tsenart for context on repo-updater/gitserver interactions.
