### ISSUE TITLE
Add Cobol support (lang filters, codeintel)

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#10154]
Requested by https://app.hubspot.com/contacts/2762526/company/2428850551 (now a customer, but not urgent)

* Looks like we don't have a Cobol basic code intel extension: https://sourcegraph.com/extensions?query=cobol

* And just doing a search shows we don't provide a `lang:` filter option for them.

* And finally, I don't see syntax highlighting: https://sourcegraph.com/github.com/leachim6/hello-world@c46bbf3c38b3b98a78ee1bd38b89f4a888e271bb/-/blob/c/cobol.cbl

I believe the file extensions are .cbl or .cob or .cpy

@christinaforney Am I missing any steps here? it would be awesome if we had a checklist/process in the dev handbook for "how to add a language"! I have no idea who to file that issue on though :)

**Comment by slimsag** [comment]
Syntax highlighting for COBOL's extensions (cbl, cpy, cob, dds, ss, wks, pco) added in #10374 and will be in Sourcegraph 3.16. Unfortunately, this does not work for `.CBL` (uppercase) which appears to be somewhat common? I'm unsure how common, though.

Other code intelligence language support will still need to be added.

Example:

![image](https://user-images.githubusercontent.com/3173176/80898332-f6c0fa00-8cb6-11ea-8f76-af8df41e192b.png)

**Comment by efritz** [comment]
Initial support via extensions has been published in https://github.com/sourcegraph/code-intel-extensions/pull/383.

I'm not so familiar with cobol syntax/semantics, so if there are any additional improvements wrt ctags, please file a new issue and assign to me.
