### ISSUE TITLE
A script to replace Renovate usage for specifically updating Docker image tags

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#10165]
Precursor to https://github.com/sourcegraph/sourcegraph/issues/10011

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by slimsag** [comment]
This was done
