### ISSUE TITLE
Prototype a new LSIF indexer for C++ based on clangd-indexer

### ISSUE THREAD

**Issue by gbrik** [sourcegraph/sourcegraph#10175]
https://clangd.llvm.org/design/indexing.html

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by gbrik** [comment]
done: https://github.com/sourcegraph/lsif-clang
