### ISSUE TITLE
More granular code coverage reporting

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#10172]
Codecov reports coverage for our entire project by default. I would like to start measuring and reporting coverage on a more granular level so that we can write team OKRs around coverage and measure them.

We currently have two groups: unit and e2e.
https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+%22https://codecov.io/bash%22&patternType=regexp

The next step I would like to take would be to separate Go coverage from TypeScript coverage for unit tests. I think this would involve removing the final [addCodeCov](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+addCodeCov&patternType=literal) step from our pipeline and instead perform multiple uploads from multiple steps as they happen (and giving each step a unique tag).

If anyone knows about a reason why we don't upload incrementally already, please share that info here.

**Comment by felixfbecker** [comment]
I think there may have been a bug in Codecov that made that not work back when Richard set it up. @eseliger had also met these bugs in the past. But uploading seperate e2e and unit flags worked fine for me.

 👍 to this proposal, I think you can tag an upload with multiple flags. An alternative would be to look at the coverage of folders.

**Comment by felixfbecker** [comment]
One thought I have: Codecov flags seem mostly targeted to distinguish between different _kind_ of tests of the same file, but backend vs frontend are disjoint files/trees. Could you get the same information out of looking at the coverage of directories? I'd like to keep the ability to toggle between unit and our future integration test coverage on the same file (if that is still possible then I'm open to use flags for this too)

**Comment by nicksnyder** [comment]
> Codecov flags seem mostly targeted to distinguish between different kinds of tests of the same file

The docs say this:

> This is particularly helpful if you have multiple types of tests (e.g., unit, integration, frontend, backend, etc), or you're employing a monorepo setup where you'd like to encapsulate each project's test coverage independently.

unit/integration distinction is certainly one case, but they also explicitly mention frontend/backend and isolating projects within a mono-repo.

It seems like my PR would address both problems:
- We have an e2e flag for those tests (so you can measure that).
- We have split up the existing unit flag into more granular flags for more granular tracking.

If we had to choose between grouping codecov by kind of test vs area of product, I would choose the latter, because I want to incentivize/measure more unit tests, not e2e tests.

> Could you get the same information out of looking at the coverage of directories?

It depends on the directory structure. If all of a teams code is in a single directory, then yes. If not, then no. Generally the answer is no. For example, I would love to (eventually) have a tag for all code intel tests and the code intel team can own that number. Code intel has multiple services so codecov doesn't report a single number unless we create a step to run only codeintel related tests and give that a unique tag.
