### ISSUE TITLE
3.15 Docker container shuts down after 5min (consistently)

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#10187]
From https://twitter.com/skottk/status/1254468123618656256:

> Docker container for 3.15.0 shuts down five minutes after I launch it, 100% of the time.

![image](https://user-images.githubusercontent.com/1976/80315477-a4f70c00-87ac-11ea-91ef-bcc8d1efb51b.png)

**Comment by slimsag** [comment]
I suspect it is running out of memory, can you check what the memory available to it is?

**Comment by skottklebe** [comment]
Cleaned out .sourcegraph/* and reran with 3.14.0, per tweet recommendation. Clone ran through 2909 repos and died. These are the last lines of the logs:
Cleaned out .sourcegraph/* and reran with 3.14.0, per tweet recommendation. Clone ran through 2909 repos and died. These are the last lines of the logs:
19:27:35         gitserver | t=2020-04-26T19:27:35+0000 lvl=warn msg="Long exec request" repo=github.com/xxxxxxxxx args="[rev-parse HEAD]" duration=3.445s
19:29:26   zoekt-webserver | 2020/04/26 19:29:26 unloading: /var/opt/sourcegraph/zoekt/index/github.com%2Forg%2Fxxxxxxxxx_v16.00000.zoekt
19:30:26         gitserver | t=2020-04-26T19:30:26+0000 lvl=warn msg="Long exec request" repo=github.com/xxxxxxxxx args="[archive --worktree-attributes --format=tar 5f46361551e12d8053277451f311f50859742654 --]" duration=1m2.26s
19:33:59             nginx | 2020/04/26 19:22:44 [error] 172#172: *1935 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 172.17.0.1, server: , request: "POST /.api/graphql?StatusMessages HTTP/1.1", upstream: "http://127.0.0.1:8080/.api/graphql?StatusMessages", host: "localhost:7080", referrer: "http://localhost:7080/site-admin/repositories?filter=cloned"
19:34:03             nginx | 2020/04/26 19:33:59 [error] 172#172: *2134 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 172.17.0.1, server: , request: "POST /.api/graphql?StatusMessages HTTP/1.1", upstream: "http://127.0.0.1:8080/.api/graphql?StatusMessages", host: "localhost:7080", referrer: "http://localhost:7080/search?q=%5B0-9%5D%5C.%5B0-9%5D%5C.%5B0-9%5D%5C.%5B0-9%5D+repo:%5Egithub%5C.com/xxxxxxxxx%24+&patternType=regexp"
19:34:04             nginx | 2020/04/26 19:33:59 [error] 172#172: *2016 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 172.17.0.1, server: , request: "POST /.api/graphql?StatusMessages HTTP/1.1", upstream: "http://127.0.0.1:8080/.api/graphql?StatusMessages", host: "localhost:7080", referrer: "http://localhost:7080/site-admin/repositories?filter=cloned"
19:34:16      repo-updater | t=2020-04-26T19:34:10+0000 lvl=eror msg="Get \"http://127.0.0.1:3178/list?cloned\": context canceled"
19:34:23      repo-updater | t=2020-04-26T19:34:12+0000 lvl=eror msg=store.list-all-repo-names error="context canceled" count=0
19:34:26      repo-updater | t=2020-04-26T19:34:23+0000 lvl=eror msg="context canceled"
19:34:39         gitserver | 2020/04/26 19:34:39 http: superfluous response.WriteHeader call from github.com/opentracing-contrib/go-stdlib/nethttp.(*statusCodeTracker).WriteHeader (status-code-tracker.go:19)
19:34:41       lsif-worker | WARN Slow database query {
19:34:41       lsif-worker |   service: 'lsif-worker',
19:34:41       lsif-worker |   query: "\n            UPDATE lsif_uploads u SET state = 'processing', " +
19:34:41       lsif-worker |     'started_at = now() WHERE id = (\n                SELECT id FROM ' +
19:34:41       lsif-worker |     "lsif_uploads\n                WHERE state = 'queued'\n           " +
19:34:41       lsif-worker |     '     ORDER BY uploaded_at\n                FOR UPDATE SKIP ' +
19:34:41       lsif-worker |     'LOCKED LIMIT 1\n            )\n            RETURNING u.id\n       ' +
19:34:41       lsif-worker |     ' ',
19:34:41       lsif-worker |   parameters: undefined,
19:34:41       lsif-worker |   executionTime: 56501
19:34:41       lsif-worker | }
19:34:42       lsif-server | WARN Slow database query {
19:34:42       lsif-server |   service: 'lsif-server',
19:34:42       lsif-server |   query: 'SELECT COUNT(DISTINCT("LsifUpload"."id")) as "cnt" FROM ' +
19:34:42       lsif-server |     '"lsif_uploads" "LsifUpload" WHERE "LsifUpload"."state" = ' +
19:34:42       lsif-server |     '$1',
19:34:42       lsif-server |   parameters: [ 'queued' ],
19:34:42       lsif-server |   executionTime: 28445
19:34:42       lsif-server | }
19:34:47   zoekt-webserver | Terminating zoekt-webserver
zoekt-webserver died. Shutting down...
19:34:47      repo-updater | Terminating repo-updater
19:34:47 zoekt-indexserver | Terminating zoekt-indexserver
19:34:47      query-runner | Terminating query-runner
19:34:47      github-proxy | Terminating github-proxy
19:34:47          frontend | Terminating frontend
19:34:47          replacer | Terminating replacer
19:34:47    syntect_server | Terminating syntect_server
19:34:47 postgres_exporter | Terminating postgres_exporter
19:34:47           symbols | Terminating symbols
19:34:47          searcher | Terminating searcher
19:34:47       lsif-worker | Terminating lsif-worker
19:34:47       lsif-server | Terminating lsif-server
19:34:47       redis-store | Terminating redis-store
19:34:47           grafana | Terminating grafana
19:34:47             nginx | Terminating nginx
19:34:47        prometheus | Terminating prometheus
19:34:48         gitserver | 2020/04/26 19:34:48 http: superfluous response.WriteHeader call from github.com/opentracing-contrib/go-stdlib/nethttp.(*statusCodeTracker).WriteHeader (status-code-tracker.go:19)
19:34:48         gitserver | t=2020-04-26T19:34:48+0000 lvl=warn msg="error cloning repo" repo=github.com/xxxxxxxxx s err="failed to clone github.com/xxxxxxxxx: clone failed. Output: Cloning into bare repository '/var/opt/sourcegraph/repos/.tmp/clone-682276360/.git'...\nremote: Enumerating objects: 7, done.        \nremote: Counting objects: 100% (7/7), done.        \nremote: Compressing objects: 100% (7/7), done.        \nReceiving objects:  75% (1551/2053), 73.33 MiB | 1.17 MiB/s\r: signal: killed"
19:34:48         gitserver | t=2020-04-26T19:34:48+0000 lvl=warn msg="error cloning repo" repo=github.com/xxxxxxxxx err="failed to clone github.com/xxxxxxxxx: clone failed. Output: Cloning into bare repository '/var/opt/sourcegraph/repos/.tmp/clone-206831593/.git'...\nremote: Enumerating objects: 29, done.        \nremote: Counting objects: 100% (29/29), done.        \nremote: Compressing objects: 100% (17/17), done.        \nReceiving objects:  98% (2569/2621), 54.36 MiB | 991.00 KiB/s\r: signal: killed"
19:34:48         gitserver | t=2020-04-26T19:34:48+0000 lvl=warn msg="error cloning repo" repo=github.com/xxxxxxxxx err="failed to clone github.com/xxxxxxxxx: clone failed. Output: Cloning into bare repository '/var/opt/sourcegraph/repos/.tmp/clone-856594621/.git'...\nremote: Enumerating objects: 1, done.        \nremote: Counting objects: 100% (1/1), done.        \nremote: Total 335 (delta 0), reused 1 (delta 0), pack-reused 334\nReceiving objects: 100% (335/335), 183.63 KiB | 321.00 KiB/s, done.\nResolving deltas: 100% (140/140), done.\n: signal: killed"
19:34:48       redis-cache | Terminating redis-cache
19:34:49          postgres | Terminating postgres
19:34:57         gitserver | Terminating gitserver

After this, I re-ran the image, and it crashed again without managing to clone another repo.

**Comment by skottklebe** [comment]
It's running without resource limits on a 2019 MB Pro with 6 cores, 16gb RAM. 300 gb disk free, .sourcegraph/* amounts to <40gb so far.

**Comment by slimsag** [comment]
I suspect 2909 repos may be about the limit for that much RAM, unfortunately, since our search indexer is pretty RAM-intensive currently. Can you post the output of this:

```
$ docker inspect -f '{{json .State}}' $CONTAINER
```

Replace `$CONTAINER` with the actual Sourcegraph container name shown by `docker ps`.

This will tell us if it is indeed being OOM killed or not.

---

You may also try our [Docker Compose deployment here](https://github.com/sourcegraph/deploy-sourcegraph-docker/tree/master/docker-compose), because it has resource isolation between containers it may let you get further without needing extra RAM

**Comment by skottklebe** [comment]
It's up until it's dead, and when it's dead it's gone.

CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                                              NAMES
cac7b7a68aa9        sourcegraph/server:3.14.0   "/sbin/tini -- /usr/…"   46 seconds ago      Up 44 seconds       127.0.0.1:3370->3370/tcp, 0.0.0.0:7080->7080/tcp   awesome_tharp
sklebe@lp-C02XV1E7JGH7 projects % docker inspect -f '{{json .State}}' awesome_tharp
{"Status":"running","Running":true,"Paused":false,"Restarting":false,"OOMKilled":false,"Dead":false,"Pid":22400,"ExitCode":0,"Error":"","StartedAt":"2020-04-26T21:47:28.341251Z","FinishedAt":"0001-01-01T00:00:00Z"}
sklebe@lp-C02XV1E7JGH7 projects % docker inspect -f '{{json .State}}' awesome_tharp
{"Status":"running","Running":true,"Paused":false,"Restarting":false,"OOMKilled":false,"Dead":false,"Pid":22400,"ExitCode":0,"Error":"","StartedAt":"2020-04-26T21:47:28.341251Z","FinishedAt":"0001-01-01T00:00:00Z"}
sklebe@lp-C02XV1E7JGH7 projects % docker inspect -f '{{json .State}}' awesome_tharp
{"Status":"running","Running":true,"Paused":false,"Restarting":false,"OOMKilled":false,"Dead":false,"Pid":22400,"ExitCode":0,"Error":"","StartedAt":"2020-04-26T21:47:28.341251Z","FinishedAt":"0001-01-01T00:00:00Z"}
sklebe@lp-C02XV1E7JGH7 projects % docker inspect -f '{{json .State}}' awesome_tharp

Error: No such object: awesome_tharp

**Comment by slimsag** [comment]
Are you passing ‘—restart=always’ to the docker rum command? If you don’t, I think it’ll not show up as you showed above

**Comment by unknwon** [comment]
The "dead after 5 minutes" problem sounds very similar to what @mrnugget and @efritz had investigated IIRC, but I couldn't recall the cause and the solution.

**Comment by skottklebe** [comment]
Starting clean with a 1200-repo subset has resolved the issue. Is there a rule of thumb for estimating memory footprint for a source codebase of a particular size? Does it scale by repos, line count, character count...?

**Comment by dadlerj** [comment]
Great question @skottklebe — we provide a resource estimator at https://docs.sourcegraph.com/admin/install/resource_estimator, and as you can see there, it's not quite as simple as "resources scale with code or users" :). 

Each service has its own scaling profile (and even within them, there can be some variation depending on, e.g., whether the code is in a 10gb monorepo, or spread across 10k repos; the size of a checkout vs. the size of the full git history; etc.

At a high level, though, "Sourcegraph scales with the total size of the codebase" is a good rule of thumb.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by slimsag** [comment]
This was caused by resource exhaustion (lack of memory). If anyone else is experiencing this issue, please reach out to us support@sourcegraph.com or try increasing the available memory to Sourcegraph.

I'll close this issue now since it appears stale.
