### ISSUE TITLE
Implement RFC 150: Version contexts UI and frontend work

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#10196]
[RFC 150](https://docs.google.com/document/d/1G8vxRF5m8mrOvjmYxWSUW3yko0q-jKAMMD7Y-h2CWeY/edit#): Version contexts UI and frontend work

Part of [RFC 136](https://docs.google.com/document/d/1-Hn3bSVmwZ9iY0nfztXMoDfzWMdOHYTKrhK2F5ZJZI8/edit#): Navigating version contexts

See Version context configuration and graphql integration #10194

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
