### ISSUE TITLE
basic-code-intel uses version contexts

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#10195]
Part of [RFC 136](https://docs.google.com/document/d/1-Hn3bSVmwZ9iY0nfztXMoDfzWMdOHYTKrhK2F5ZJZI8/edit#): Navigating version contexts

basic-code-intel uses search to find definitions and references. When a version context is active it should use it to prioritize results from it. This requires adding a way to pass in version context to basic-code-intel. This then needs to be threaded through to search calls. A fallback to default context is probably also needed. How basic-code-intel currently uses search (thanks @efritz):

> For search-based definitions we do a symbol search at
`repo:current_repo@current_commit` and fallback to `repo:current_repo index:yes`
for local defs, then do a `repo:-current_repo index:yes` for remote definition
fallbacks.
>
> For search-based references we do a text search with the same basic shape
(except we do them concurrently).

**Comment by nicksnyder** [comment]
Who is best positioned to do this work?

Should someone on code intel take this? cc @efritz @gbrik

**Comment by efritz** [comment]
This should be a simple update to the extensions but is blocked until the extension host can supply the version context to providers, and until search respects context parameters in the GraphQL API.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by nicksnyder** [comment]
@efritz does this belong in 3.17 now?

**Comment by efritz** [comment]
Closed by https://github.com/sourcegraph/code-intel-extensions/pull/385.
