### ISSUE TITLE
Go: getting interface method implementations: " Error getting implementations: Unexpected EOF"

### ISSUE THREAD

**Issue by cpatulea** [sourcegraph/sourcegraph#102]
- **Sourcegraph version:** Sourcegraph.com
- **Platform:** Chrome

#### Steps to reproduce:

1. https://sourcegraph.com/github.com/prometheus/prometheus@2bd510a63e48ac6bf4971d62199bdb1045c93f1a/-/blob/storage/interface.go#L83:2$impl
2. Hover over AddFast, click FIND IMPLEMENTATIONS

#### Expected: 
list of implementations

#### Actual:
bottom panel error " Error getting implementations: Unexpected EOF"

https://i.imgur.com/r6KRYNW.jpg

**Comment by felixfbecker** [comment]
Hi @cpatulea, I cannot reproduce this issue:

<img width="868" alt="image" src="https://user-images.githubusercontent.com/10532611/41930575-47f0b3c6-7930-11e8-92e8-249a933a5089.png">

Does it still happen to you if you try again?

**Comment by keegancsmith** [comment]
@cpatulea How often do you see this happen? It was likely a transient issue, but if it isn't rare it will help us prioritise investigating and fixing this. For the sourcegraphers it happened at 2018-06-26 19:57:52.739 UTC (via [honeycomb](https://ui.honeycomb.io/sourcegraph/datasets/xlang/result/oUxEoPJNSxa))

**Comment by cpatulea** [comment]
I am not able to reproduce either now.
