### ISSUE TITLE
Error on the extensions page: pq: invalid input syntax for type json

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#1020]
- Visit https://sourcegraph.com/extensions
- Notice this error:

![image](https://user-images.githubusercontent.com/1387653/48587344-9df57a00-e8e7-11e8-846d-aeadab12a131.png)

**Comment by chrismwendt** [comment]
I think this is being caused by https://github.com/sourcegraph/sourcegraph/pull/1009 (merged 1 hour ago)

**Comment by sqs** [comment]
fixed in #1029  and deployed - you can see the WIP badge at (e.g.) https://sourcegraph.com/extensions?query=python
