### ISSUE TITLE
Render Jupyter Notebook files (.ipynb) like markdown

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#10203]
Requested by https://app.hubspot.com/contacts/2762526/company/554275594

>ipynb files are structured as JSON, but are not particularly useful to read in that format.

>Internally it was suggested that in rendered form, the python snippets should be appropriately highlighted as python, with code intel applied

**Comment by unknwon** [comment]
https://github.com/jsvine/notebookjs and https://github.com/markedjs/marked are what I used to render Jupyter Notebook, however be aware that

>Marked does not sanitize the output HTML. Please use a sanitize library, like DOMPurify (recommended), sanitize-html or insane on the output HTML! 🚨

_https://github.com/markedjs/marked#warning--marked-does-not-sanitize-the-output-html-please-use-a-sanitize-library-like-dompurify-recommended-sanitize-html-or-insane-on-the-output-html-_

**Comment by casassg** [comment]
Would be nice to have this in sourcegraph!

**Comment by pdubroy** [comment]
Here's an [example](https://github.com/barbagroup/AeroPython/blob/master/lessons/01_Lesson01_sourceSink.ipynb) on GitHub.

To me it looks like a significant chunk of work would be required to deliver a high-quality solution here. Given what @sourcegraph/frontend-platform has on the roadmap for Q3, I don't think we'd be able to work on this until Q4 at the earliest.

**Comment by sourcegraph-bot-2** [comment]
Heads up @taylorsperry @jasongornall - the "team/frontend-platform" label was applied to this issue.

**Comment by umpox** [comment]
Re-added our team label, I think this would still be our area of ownership as we [own](https://handbook.sourcegraph.com/departments/engineering/dev/process/engineering_ownership/#frontend-platform) Non-code file view.

Some additional information:

Here's an example file: https://sourcegraph.com/github.com/donnemartin/system-design-primer/-/blob/solutions/object_oriented_design/hash_table/hash_map.ipynb

Here's that same example on GitHub: https://github.com/donnemartin/system-design-primer/blob/master/solutions/object_oriented_design/hash_table/hash_map.ipynb

We would likely want to do this on the **backend**, not client side if possible. We handle this for markdown through the `richHTML` query returned from GQL.

**Comment by taylorsperry** [comment]
[Related request](https://sourcegraph.slack.com/archives/C0W2E592M/p1660318083027239)

**Comment by jdorfman** [comment]
@dadlerj done! https://sourcegraph.com/blog/code-search-now-supports-jupyter-notebook-rendering.md
