### ISSUE TITLE
repo-updater restart required for changes to repoListUpdateInterval to take effect

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#10213]
We are illegally not respecting changes in the the value of `conf.Get()` here by passing it as an argument:

https://sourcegraph.com/github.com/sourcegraph/sourcegraph@cb3b3cc0b1b1ce445e7a70d446a2265a451108a8/-/blob/cmd/repo-updater/shared/main.go#L190

A customer at https://app.hubspot.com/contacts/2762526/company/732945850/ reported this.

**Comment by tsenart** [comment]
This has been fixed.
