### ISSUE TITLE
Improve documentation on Phabricator development & debugging

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#10223]
There is currently a lot of undocumented context regarding usage & debugging of the Phabricator integration. This makes it hard to onboard new teammates on Phabricator, which means I end up being a SPOC/bottleneck for Phabricator issues. The docs should be improved so that ownership of Phabricator issues can be shared among the web team.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by pdubroy** [comment]
Closing this — last update was over a year ago, so I'm assuming it's obsolete. Please feel free to re-open if I'm wrong.
