### ISSUE TITLE
Handbook misleadingly states minor versions do not require manual migrations, confusing customers

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#10230]
Asked by https://app.hubspot.com/contacts/2762526/company/554275594

>Question: The releases page in the handbook mentions that monthly releases never require manual migration steps. Is this true for kubernetes clusters?
>https://github.com/sourcegraph/deploy-sourcegraph/blob/master/docs/migrate.md
>https://about.sourcegraph.com/handbook/engineering/releases

This should be updated, as k8s and docker compose deployments DO occasionally require updates on minor versions: https://docs.sourcegraph.com/admin/updates

**Comment by pecigonzalo** [comment]
Closing as releases now show when migration steps are required.
