### ISSUE TITLE
Go-to-def on GitHub appends absolute URL 

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#10287]
- **Browser extension version:** v20.4.21.1107, on Chrome

#### Steps to reproduce:

1. Go to https://github.com/sourcegraph/sourcegraph/pull/10286/files#diff-b8b9fb9fa11b884295cef9ca61b7eed4R124.
2. Hover over `suggestions`. Click go to definition.
3. Notice it takes you to https://github.com/sourcegraph/sourcegraph/compare/https:/github.com/sourcegraph/sourcegraph/blob/b5637591d3ca88cbbb8fc4192a3440875a78414a/shared/src/search/parser/completion.ts?expand=1#diff-b8b9fb9fa11b884295cef9ca61b7eed4R124

#### Expected behavior:

You get taken to https://github.com/sourcegraph/sourcegraph/blob/b5637591d3ca88cbbb8fc4192a3440875a78414a/shared/src/search/parser/completion.ts?expand=1#diff-b8b9fb9fa11b884295cef9ca61b7eed4R124

#### Actual behavior:

The absolute URL is appended to github.com/sourcegraph/sourcegraph/compare

**Comment by attfarhan** [comment]
What seems to be happening is: 
- if you click go-to-def before the definition is resolved, we will fetch the definition URL. Once it's fetched, the definition URL gets then appended to the current URL. 
- clicking go-to-def again will take you to the correct definition location.

**Comment by felixfbecker** [comment]
I think this caused (legit) e2e tests failures

**Comment by felixfbecker** [comment]
This seems to be the issue:
We use `history.push()` (from the `history` library) to do the programmatic navigation. But apparently `history.push()` does not support absolute URLs, only path-relative (the parameter is named `path`, not `url`). So the path of the URL gets set to this, not the whole URL.
