### ISSUE TITLE
Reduce usage of raw string for external service kind

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#10296]
We have raw strings (often with string.ToLower) all over the place.

We should introduce an enum type for this and have a common function for parsing / returning raw strings at the edges of our system.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
