### ISSUE TITLE
Feature request: Highlight references on hover

### ISSUE THREAD

**Issue by gbrik** [sourcegraph/sourcegraph#10306]
@sourcegraph/code-intel 

Lots of IDEs will highlight references to an identifier you're hovering over, which is especially helpful for grokking local variables in complicated functions. Screenshot below from my Emacs running an LSP extension.

![image](https://user-images.githubusercontent.com/3411715/80752209-20342700-8af9-11ea-9b58-5d977716e789.png)

It would be really slick to do this in our extensions and web UI when precise code intelligence is available.

cc @sourcegraph/web

**Comment by dadlerj** [comment]
Not exactly the same, but https://sourcegraph.com/extensions/chris/token-highlights is a much simpler proxy for this.

**Comment by gbrik** [comment]
Nifty, probably makes sense to extend & modify that. If the UI was less aggressive it could be on by default instead of an extension.

**Comment by efritz** [comment]
We have this in 3.18!
