### ISSUE TITLE
Display webhook URL in external service config view

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#10300]
Follow up work for #10292

**Comment by ryanslade** [comment]
Tag me on the PR please as I'd like to update our docs when merging the change.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
