### ISSUE TITLE
Feature request: handle broken LSIF index uploads more gracefully

### ISSUE THREAD

**Issue by shrouxm** [sourcegraph/sourcegraph#10307]
@sourcegraph/code-intel 

Right now, if a user uploads an LSIF index with a broken edge, we'll throw an error and refuse to process. This completely blocks precise code intelligence for that repo until the indexer gets fixed. It would be more graceful to instead ignore the broken edge, and provide a notice on files with broken edges potentially linking to details.

**Comment by macraig** [comment]
@scalabilitysolved is this something we'd plan to solve as part of our scaling effort?

**Comment by efritz** [comment]
@macraig This was originally Roux wanting to more leniently accept broken LSIF dump input. Something like this would (might) help us debug bad indexer output without requiring the full repository, though.
