### ISSUE TITLE
Repository does not show up in search results at all unless query *exactly* matches it

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#10313]
A user at https://app.hubspot.com/contacts/2762526/company/407948923/ reported an issue that is incredibly bizarre. there are two repositories:

- `github.com/foo/bar`
- `github.com/foo/bar-baz`

These queries do NOT return `foo/bar` but DO return `foo/bar-baz`:

```
repo:^github.com/foo/bar type:repo count:1000 timeout:60s
repo:github.com/foo/bar$ type:repo count:1000 timeout:60s
repo:foo/bar type:repo count:1000 timeout:60s
```

However, this query (and ONLY this query) DOES return `foo/bar`:

```
repo:^github.com/foo/bar$ type:repo count:1000 timeout:60s
```

All of these queries return almost instantly in under 1s, and all return <5 results total.

**Comment by dadlerj** [comment]
Just to check, did you try with `index:no`?

**Comment by slimsag** [comment]
Confirmed, `index:no` causes no change in behavior.

**Comment by slimsag** [comment]
A query for `type:repo . count:99999` returns `16,038` instead of `17,673` results, indicating that a large portion are for some reason being excluded from repository search.

**Comment by rvantonder** [comment]
Just to help eliminate possibilities: Is `github.com/foo/bar` a fork perhaps, which would then only show up if it matched exactly (if this Sourcegraph version runs the change that excludes forks)? Also `type:repo . count:99999` will also exclude forks depending on Sourcegraph version (I'm assuming the 16K numbers here correspond to the customer instance).

**Comment by rvantonder** [comment]
Aside: `type:repo` seems redundant in a query containing only `repo:` and some other filters that don't affect results. But, the behavior of `type:repo` with `repo:` is actually not well-defined to my mind. So, out of curiosity, what do the following queries do without `type:repo`:

```
repo:^github.com/foo/bar type:repo count:1000 timeout:60s
repo:github.com/foo/bar$ type:repo count:1000 timeout:60s
repo:foo/bar type:repo count:1000 timeout:60s
```

**Comment by slimsag** [comment]
🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦🤦

Oh my.. yes, `fork:yes` and `archived:yes` makes it no longer happen and all repositories show up.

Well, in light of this and:

- the fact that I myself couldn't figure out this was the cause
- Dan couldn't conclude this was the issue
- the user that reported this couldn't figure out this was the issue and reported it to their Sourcegraph admin
- Their Sourcegraph admin couldn't figure out this was the issue and reported it to me
- I concluded it MUST be at least an instability issue with the repository and was extremely worrying
- I then thought perhaps up to 1,000 repositories were being affected

Maybe the UI indicating forks/archived repos becomes ever more important? :) https://github.com/sourcegraph/sourcegraph/issues/9928

**Comment by slimsag** [comment]
I'll follow up with the affected users tomorrow and close in favor of #9928

**Comment by rvantonder** [comment]
We added the setting to restore the previous default (add forks). Are affected customers on a newer release? That would be an immediate solution.

**Comment by rvantonder** [comment]
To elaborate, another way to handle this, so that we don't have to immediately prioritize/implement the new alert thing, is:

- change the logic back to include forks by default (since this has now become a pernicious issue)
- make the site setting introduced in https://github.com/sourcegraph/sourcegraph/pull/9933 be opt-in (i.e., opt-in to exclude forks), rather than the current default to exclude forks
- In the interest of taking the opt-in to exclude forks, we should still raise an explicit alert

**Comment by slimsag** [comment]
> We added the setting to restore the previous default (add/include forks). Are affected customers on a newer release? That would be an immediate solution.

I think affected customers here generally DO want forks/archived repos excluded by default, and it's only a few users who do not want that behavior. But, with them excluded by default, the behavior in some cases (like this) is very surprising.

> - change the logic back to include forks by default (since this has now become a pernicious issue)

I suspect this would not be a good choice and would introduce more confusion for users ("Now forks ARE included by default?!")

As a temporary workaround, I have added the following to affected customers' global user settings:

```
  "search.scopes": [
    {
      "name": "Include forks",
      "description": "Includes forked repositories",
      "value": "fork:yes"
    },
    {
      "name": "Include archived",
      "description": "Includes archived repositories",
      "value": "archived:yes"
    },
    {
      "name": "Include all repositories",
      "description": "Includes all repositories (forked & archived)",
      "value": "fork:yes archived:yes",
    }
  ]
```

This way there is at least a semblance of "there are possibly more results omitted here"
