### ISSUE TITLE
Ensure that we are tracking Go test coverage correctly

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#10356]
From @keegancsmith [on Slack](https://sourcegraph.slack.com/archives/CHPC7UX16/p1588235602278900?thread_ts=1588193714.276400&cid=CHPC7UX16)

> FYI the current measurement is much lower than the reality. Everytime we have tried to use `-coverpkg` it broke something (I think because of how it interacts with race? I can't remember).
But right now we only collect coverage inside the package being tested, and miss out on coverage we get across packages. Fixing this might blow the OKR out of the water :slightly_smiling_face: So I'd investigate that first.

cc @unknwon since you are focusing on testing. I am going to tentatively place this in the next milestone because it isn't urgent.

**Comment by nicksnyder** [comment]
I looked for a quick win on this, but the builds did break in unexpected ways. I don't quite understand what is happening. https://github.com/sourcegraph/sourcegraph/pull/10439

**Comment by unknwon** [comment]
Cross-posting https://github.com/sourcegraph/sourcegraph/pull/10439#issuecomment-640062277:

> Fixed shellcheck and merged `master` in #11332 and passed CI, but it took over 16m for `go-test.sh` step (which [usually took <2m](https://buildkite.com/sourcegraph/sourcegraph/builds/65780)).
> 
> The coverage increase +3.17% for "go".

The cost is clearly not worth it as this point.

May come back later when there is more ideas about how to reduce the run time.
