### ISSUE TITLE
Enable selective logging of HTTP request headers

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#10359]
With `SRC_LOG_LEVEL`, we have a way to log metadata about HTTP response headers. However, sometimes site admins want to see metadata about HTTP requests received by Sourcegraph. For example, if a request from some other source to Sourcegraph fail, the admin may want to understand if the request is modified en route to Sourcegraph and observe which headers are actually set in the request when it arrives at Sourcegraph.

See [customer context](https://sourcegraph.slack.com/archives/CSKMGUJ58/p1588364066063500?thread_ts=1588105315.051500&cid=CSKMGUJ58).

**Comment by virginiaulrich** [comment]
In planning session, agreed to close at this time since this may not be directly relevant right now and we don't have record of additional needs beyond this request; we can reconsider later if needed.
