### ISSUE TITLE
VS Code extras extension error message isn't clear

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#10354]
![image](https://user-images.githubusercontent.com/5589410/80814483-d4c55b80-8b80-11ea-8367-b5b4a4c87cca.png)

~It'd be nice if this linked to the settings page and told me to add the required key (which doesn't exist there at all yet)~

Never mind! Apparently I did set the local path. This error message isn't clear to me then, since I see nothing in the JS console or the network requests tab in Chrome.

**Comment by felixfbecker** [comment]
This shouldn't happen... What did you set as `vscode.open.basePath`?

**Comment by felixfbecker** [comment]
And can you give me the link to the file this happened on?

**Comment by dadlerj** [comment]
Ah — it's because I was clicking it on a repo page 😄 . The same error happens on a tree page. E.g. https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/tree/schema or https://sourcegraph.com/github.com/sourcegraph/sourcegraph

**Comment by felixfbecker** [comment]
Made the extension also work on directory pages. The underlying issue here is context key expressions in directory contexts not being defined (which only happens with the `codeInsights` feature flag since that enables directory contexts)

**Comment by felixfbecker** [comment]
Tracking that in #10375
