### ISSUE TITLE
No "Go to definition" for Go symbol

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#10372]
At https://sourcegraph.com/github.com/sourcegraph/sourcegraph@7cee2b75321d1f2bd0f38b9ed143877f4a7e8fc5/-/blob/cmd/frontend/graphqlbackend/git_commit.go#L266:10 I see a hover for `type gitCommitConnectionResolver struct` but no "Go to definition" (or "Find references") buttons. I expect to see those buttons because it found the hover.

![image](https://user-images.githubusercontent.com/1976/80873415-34009a00-8c6d-11ea-94ff-606940a6a6a2.png)

**Comment by gbrik** [comment]
can't reproduce, could you confirm whether you're still seeing the error?

**Comment by efritz** [comment]
I also tried on mobile shortly after the issue was filed and it seemed like in the meantime an LSIF index was processed.

I haven't gotten around to looking at the issue in interpreting the search results, though.

**Comment by sqs** [comment]
I just saw this again at https://sourcegraph.com/github.com/sourcegraph/sourcegraph@42b1389a71b947a75f00c27bb463a3caca8d8a74/-/blob/enterprise/internal/campaigns/resolvers/patch_sets.go#L171:25 (hovering `ListRepos`). The hover info is there but no definition/references buttons.

**Comment by sqs** [comment]
Same at https://sourcegraph.com/github.com/sourcegraph/sourcegraph@53043edfa1c9c6adf76e61933fe401dc6720e2e3/-/blob/enterprise/internal/campaigns/service.go#L391:9 (`SyncChangesetsWithSources`).

**Comment by sqs** [comment]
I was able to fix by clearing my settings. Bisecting now to find out the culprit.

**Comment by sqs** [comment]
Unrelated to code intel. It's an extension problem. See https://github.com/sourcegraph/sourcegraph/issues/10600.

**Comment by efritz** [comment]
Thanks for updating us on this! Scratching my head on this for a while.
