### ISSUE TITLE
Make code insights user-resizable and reorderable

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#10376]
The user should have freedom to reorder and resize code insights to create a dashboard.
This should be persistable to user, org or global settings.
This also allows us to give fixed default width and height to views, which makes the UI stable (in combination with #10375).

First idea is to use CSS grid with native CSS `resize`, then a `ResizeObserver` to persist it. Could snap to grids with the CSS grid `span` keyword.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
