### ISSUE TITLE
Support context key conditions for view providers

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#10375]
This allows us to statically determine whether we should query an extension for a view without having to query it and see if it returns `null`, which creates an unstable UI.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by unclejustin** [comment]
Extension API is deprecated. Issue no longer relevant.
