### ISSUE TITLE
Ruby LSIF indexer

### ISSUE THREAD

**Issue by igor-drozdov** [sourcegraph/sourcegraph#10385]
@efritz First of all, great job on developing/maintaining the [existing indexers](https://lsif.dev/)!

Does your team have any plans for implementing Ruby LSIF indexer?

If not, considering your rich experience with LSIF, do you have any recommendations for someone who plans to implement one? In case you did any investigation, do you have any ideas on leveraging existing tools to create LSIF output for Ruby projects (like, as far as I understand, you did for https://github.com/sourcegraph/lsif-semanticdb)?

Thanks!

**Comment by efritz** [comment]
Hi Igor,

Our current plans are to aggressively prioritize Go, TypeScript, C/C++, and Java. Ruby is in the list of languages that comprises a pretty long tail, so we don't assume we'd get to it in the immediate future.

I **do** have recommendations to help others along with the engineering effort of writing an LSIF indexer themselves (and would love to see the community grow in this way). I'll publish my thoughts in a blog post that I've been meaning to do for some time now. Once it's published I'll update this issue with a link.

Out of curiosity, are there any popular tools for Ruby that would provide name resolution in the way SemanticDB/Metals does for Scala? Anything in use at GitLab? I know of Sorbet but I'm unsure of how widespread its use is outside of Stripe.

**Comment by igor-drozdov** [comment]
> Our current plans are to aggressively prioritize Go, TypeScript, C/C++, and Java. Ruby is in the list of languages that comprises a pretty long tail, so we don't assume we'd get to it in the immediate future.

That's a wise decision. Due to its dynamic nature, Ruby is not the easiest language for static analysis

> I'll publish my thoughts in a blog post that I've been meaning to do for some time now. Once it's published I'll update this issue with a link.

Yea, it would be cool, thanks!

> Out of curiosity, are there any popular tools for Ruby that would provide name resolution in the way SemanticDB/Metals does for Scala? Anything in use at GitLab? I know of Sorbet but I'm unsure of how widespread its use is outside of Stripe.

We don't use any custom tools at GitLab. I had a look at Sorbet, but haven't found a way yet to reuse its functionality. There are plenty of [LSP servers](https://microsoft.github.io/language-server-protocol/implementors/servers/) though, but I didn't find them useful to generate LSIF as well 🤔

**Comment by efritz** [comment]
It hasn't landed yet, but I wrote some documentation last week on how to write an indexer. It should be live on the user docs page pretty soon.

In the meantime, feel free to read the PR: https://github.com/sourcegraph/sourcegraph/pull/10422.

**Comment by abitrolly** [comment]
What is required to make LSIF indexer out of https://github.com/sourcegraph/lang-ruby ?

I am reading https://docs.sourcegraph.com/code_intelligence/explanations/writing_an_indexer but I am not proficient in JavaScript to see what could be the entrypoint.

**Comment by abitrolly** [comment]
`lang-ruby` is a simple client library for making requests to Sourcegraph server. I could not find what the server uses for indexing https://github.com/sourcegraph/sourcegraph/issues/4

**Comment by macraig** [comment]
Hi @abitrolly! The `lang-ruby` project is not being actively maintained so it wouldn’t be a good starting point for a custom indexer. We are however planning to do some work in the short term that should make the process of writing a custom indexer easier. If that's something that you're interested we can keep you posted!

**Comment by abitrolly** [comment]
@macraig I've started writing my own dumper for LSP symbols from Solargraph. It you have funds allocated for better support for Ruby and nobody to work on it, then I can try to get some prototype sooner.

**Comment by macraig** [comment]
@abitrolly that's awesome! We don't have any funds allocated to Ruby at the moment, but I'll let you know if that changes.
