### ISSUE TITLE
cmd/server: warn if arguments are unrecognized

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1038]
It is easy to make the mistake of running something like:

```
docker run \
  --publish 7080:7080 --rm \
  --volume ~/.sourcegraph/config:/etc/sourcegraph \
  --volume ~/.sourcegraph/data:/var/opt/sourcegraph \
  --volume /var/run/docker.sock:/var/run/docker.sock \
  sourcegraph/server:2.13.3 \
  --restart always
```

where `--restart always` is intended to be https://docs.docker.com/engine/reference/commandline/run/#restart-policies---restart. In reality, because the `--restart always` arg is AFTER the image name, `docker run` passes it through to `sourcegraph/server`'s entrypoint. So it does not take effect on Docker.

It would be nice if `sourcegraph/server` printed an error if it received unexpected command-line args. This would inform users of their mistake.

**Comment by saravanakumarangamuthu** [comment]
one more thing is --rm and --restart cannot be running together, if we specify as below: it works/bring back the source-graph server docker after host restart

 docker run \
  --publish 7080:7080 \
  --volume ~/.sourcegraph/config:/etc/sourcegraph \
  --volume ~/.sourcegraph/data:/var/opt/sourcegraph \
  --volume /var/run/docker.sock:/var/run/docker.sock \
  --restart always \
  sourcegraph/server:2.13.3

**Comment by sqs** [comment]
@saravanakumarangamuthu Great, thanks for mentioning that!
