### ISSUE TITLE
Large files not being returned for indexed filepath searches

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#10382]
In this specific context a 23mb ttf file is not being returned with the search `file:"arial" count:1000`, but is returned when `index:no` is appended. The root cause is likely `zoekt-archive-index` excluding it from what is passed into the zoekt indexing code, rather than letting the zoekt index code exclude it. 

Slack context: https://sourcegraph.slack.com/archives/CHEKCRWKV/p1588286811016700

**Comment by dadlerj** [comment]
Regarding prioritization: not urgent priority in this particular case, but obviously I don't know what I don't know. E.g., I have no idea if this is just the tip of an iceberg of zoekt missing certain files?

Happy to connect you to the customer if helpful.

Reported by https://app.hubspot.com/contacts/2762526/company/732945850

**Comment by keegancsmith** [comment]
@asdine I think this is quite easy to fix. I was working on another task and noticed the fix for this:

```diff
diff --git a/cmd/zoekt-archive-index/main.go b/cmd/zoekt-archive-index/main.go
index 4320a6c..6cb7e8b 100644
--- a/cmd/zoekt-archive-index/main.go
+++ b/cmd/zoekt-archive-index/main.go
@@ -165,11 +165,6 @@ func do(opts Options, bopts build.Options) error {
 	add := func(f *File) error {
 		defer f.Close()
 
-		// We do not index large files
-		if f.Size > int64(bopts.SizeMax) && !bopts.IgnoreSizeMax(f.Name) {
-			return nil
-		}
-
 		contents, err := ioutil.ReadAll(f)
 		if err != nil {
 			return err
```

We enforce sizes in the builder called below. The builder will store the filename for searching, but will skip indexing the contents. Which is the behaviour we want.
