### ISSUE TITLE
fix CI DB backcompat test

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1039]
I disabled the CI DB backcompat test in ed3e3c59bab74e9cb40a2bbba520ad5f4ed59770. It is failing at https://buildkite.com/sourcegraph/sourcegraph/builds/23729#dc59f7b2-1814-4058-ab04-57f1be7bb19f. I fixed 2 bugs here (116c0a1debcdd676aecce315ee60eec7b74297e9 and 31f14fd8db6720e34e902bf277a0186cd33b5ba5), but it would be great if you @beyang 	could look into this from here and see why it's failing now, on commits that don't introduce a DB migration. (Also the `go.sum` dirty issue that's also mentioned in the CI link above.)

We will not ship any more migrations until this test is reenabled. (This is not a big concern because master is 3.0-preview anyway.)

**Comment by nicksnyder** [comment]
@beyang are these tests still disabled?

**Comment by beyang** [comment]
Yes they are. I'll review this week.

**Comment by nicksnyder** [comment]
It would be nice to get this done before we tag 3.0

**Comment by beyang** [comment]
Fixed
