### ISSUE TITLE
add monitoring for registry API endpoints

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1040]

**Comment by nicksnyder** [comment]
If this is release blocking for 3.0, please add the release blocking label.

Otherwise, if this isn't going to get done in the next week, please remove it from the 3.0 milestone.

**Comment by sqs** [comment]
Should monitor /.api/registry/extensions URLs:

- the url used to query extensions
- the url used to get a single known extension like sourcegraph/lang-go

Note this uses a special simple rest api not GraphQL. The Go package registry is responsible for serving this.

**Comment by nicksnyder** [comment]
@lguychard do you think you can get this done this week? @keegancsmith or I can provide guidance on how we do monitoring.

Relevant locations:
https://github.com/sourcegraph/infrastructure/tree/master/site24x7
https://github.com/sourcegraph/deploy-sourcegraph-dot-com/blob/release/configure/prometheus/prometheus.ConfigMap.yaml

**Comment by lguychard** [comment]
@nicksnyder should be doable

**Comment by lguychard** [comment]
@sqs what did you have in mind specifically for this? AFAICT we currently log:
- All requests to the extension registry (list/get extension) & their URLs to Honeycomb
- Success & error counters for these requests to Prometheus

https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/internal/registry/http_api.go#L102

**Comment by nicksnyder** [comment]
@lguychard Logging and metrics are great, but I think this issue is specifically about getting alerted if these things are down. I would add a site 24x7 health check for the two endpoints Quinn mentioned.

**Comment by lguychard** [comment]
Added alerts registry_api_list and registry_api_lang_go in [be18d5a](https://github.com/sourcegraph/infrastructure/commit/be18d5a9528716fab83c131a1ca858eaf5bddda0)
