### ISSUE TITLE
UX: username is not mentioned in the verification email

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#10411]
Bob could add Alice's email address and send out a verification email to Alice, but Alice won't be able to verify with the link because the link knows it was generated for Bob. Then, it is super confusing for Alice what is going on.

If the email mentions the username "Bob", Alice could have known this email is a mistake and should not even try to click on the link.

![image](https://user-images.githubusercontent.com/2946214/81041132-99f45800-8edf-11ea-8b95-5ce4608530d1.png)

_Originally report and screenshot provided by **Ranjeet Kumar Singh**._

**Comment by unknwon** [comment]
Assigned @christinaforney for triaging.

**Comment by quinnkeast** [comment]
Based on the typical patterns for these emails, I don't think we need to expose the actual email address in the email body, just the username. We also include it in the footer, anyway. I suggest the following change to the copy to make it more in line with our content guidelines:

**Current:**

>Verify your email address "logan@smith.com" on Sourcegraph by following this link:
>[Verify email address]()

**Updated:**

>Hi {username},
>
>Please verify your email address on Sourcegraph by clicking this link:
>
>[Verify email address]()

Also, I see our current email has an unsubscribe link. As this is a system email sent in response to user action, I don't believe it requires the unsubscribe. Can we remove that?

**Comment by unknwon** [comment]
^ One nice addition would be also to include the instance URL (`externalURL`)

>Hi {username},
>
>Please verify your email address on Sourcegraph (https://sourcegraph.com) by clicking this link:
>
>[Verify email address]()

Just a suggestion though.

**Comment by arussellsaw** [comment]
☝️ this aligns with other emails we send so if there's no protests i'll add @unknwon's suggestion
