### ISSUE TITLE
`src config` commands fail

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#10419]
- **Sourcegraph version:** 3.15.1+

Reported by https://app.hubspot.com/contacts/2762526/company/557693052

Run `src config list` and `src config get` on against sourcegraph.com or a 3.15.1+ instance. I haven't tested against older versions.

```
GraphQL errors:
[
  {
    "locations": [
      {
        "column": 9,
        "line": 8
      }
    ],
    "message": "Fragment \"ConfigurationSubjectFields\" cannot be spread here as objects of type \"SettingsSubject\" can never be of type %!q(\u003cnil\u003e)."
  },
  {
    "locations": [
      {
        "column": 40,
        "line": 15
      }
    ],
    "message": "Unknown type \"ConfigurationSubject\"."
  },
  {
    "locations": [
      {
        "column": 13,
        "line": 20
      }
    ],
    "message": "Fragment \"ConfigurationFields\" cannot be spread here as objects of type %!q(\u003cnil\u003e) can never be of type \"Configuration\"."
  },
  {
    "locations": [
      {
        "column": 13,
        "line": 23
      }
    ],
    "message": "Fragment \"UserFields\" cannot be spread here as objects of type %!q(\u003cnil\u003e) can never be of type \"User\"."
  }
]
```

**Comment by mrnugget** [comment]
Seems like the query produced by `src config get` includes outdated GraphQL fields?

[Click here to try it on sourcegraph.com API console](https://sourcegraph.com/api/console#%7B%22query%22%3A%22query%20ViewerConfiguration%20%7B%5Cn%20%20viewerConfiguration%20%7B%5Cn%20%20%20%20...ConfigurationCascadeFields%5Cn%20%20%7D%5Cn%7D%5Cnfragment%20ConfigurationCascadeFields%20on%20ConfigurationCascade%20%7B%5Cn%20%20%20%20subjects%20%7B%5Cn%20%20%20%20%20%20%20%20...ConfigurationSubjectFields%5Cn%20%20%20%20%7D%5Cn%20%20%20%20merged%20%7B%5Cn%20%20%20%20%20%20%20%20...ConfigurationFields%5Cn%20%20%20%20%7D%5Cn%7D%5Cn%5Cnfragment%20ConfigurationSubjectFields%20on%20ConfigurationSubject%20%7B%5Cn%20%20%20%20id%5Cn%20%20%20%20latestSettings%20%7B%5Cn%20%20%20%20%20%20%20%20id%5Cn%20%20%20%20%20%20%20%20configuration%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20...ConfigurationFields%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20author%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20...UserFields%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20createdAt%5Cn%20%20%20%20%7D%5Cn%20%20%20%20settingsURL%5Cn%20%20%20%20viewerCanAdminister%5Cn%7D%5Cn%5Cnfragment%20ConfigurationFields%20on%20Configuration%20%7B%5Cn%20%20%20%20contents%5Cn%7D%5Cn%5Cnfragment%20UserFields%20on%20User%20%7B%5Cn%20%20%20%20id%5Cn%20%20%20%20username%5Cn%20%20%20%20displayName%5Cn%20%20%20%20siteAdmin%5Cn%20%20%20%20organizations%20%7B%5Cn%5Ct%5Ctnodes%20%7B%5Cn%20%20%20%20%20%20%20%20%5Ctid%5Cn%20%20%20%20%20%20%20%20%5Ctname%5Cn%20%20%20%20%20%20%20%20%5CtdisplayName%5Cn%5Ct%5Ct%7D%5Cn%20%20%20%20%7D%5Cn%20%20%20%20emails%20%7B%5Cn%20%20%20%20%20%20%20%20email%5Cn%20%20%20%20%20%20%20%20verified%5Cn%20%20%20%20%7D%5Cn%20%20%20%20url%5Cn%7D%5Cn%5Cn%22%2C%22operationName%22%3A%22ViewerConfiguration%22%2C%22variables%22%3A%22%22%7D)

**Comment by mrnugget** [comment]
cc @slimsag because I think you know a lot about our configuration system and might have an idea as to what changed.
