### ISSUE TITLE
Add ping JSONs back into admin dashboard

### ISSUE THREAD

**Issue by ebrodymoore** [sourcegraph/sourcegraph#10433]
#### Feature request description

A section/tab in the admin dashboard of the latest ping JSON sent back to Sourcegraph, and what the full ping would look like (in the case the admin has pings turned off). 

#### Is your feature request related to a problem? If so, please describe.

[$CUSTOMER](https://app.hubspot.com/contacts/2762526/company/554338610/) was wondering what the pings looked like because they were [thinking about re-enabling](https://sourcegraph.slack.com/archives/CMB6K7SMN/p1588352651210000). Dan had to do a lot of background work to get this. 

This also would make it easier for testing when adding a ping. 

#### Describe alternatives you've considered.

Adding an example ping JSON to the docs, but this is hard to maintain for all versions. 

#### Additional context

We had this at one point (according to Dan).

**Comment by ebrodymoore** [comment]
cc @dadlerj

**Comment by slimsag** [comment]
This could be easily added to the e.g. https://sourcegraph.com/site-admin/updates page since it already is fetching this information -- we would just need to pass it from the backend and have a little UI for it (e.g. Monaco).

Not trivial, but pretty straightforward

**Comment by ebrodymoore** [comment]
@slimsag good to know, thanks! Would this be in distribution's purview or another team?

**Comment by ebrodymoore** [comment]
Closed by [#14370](https://github.com/sourcegraph/sourcegraph/pull/14370)
