### ISSUE TITLE
release 2.13.5 cluster version

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1043]
I just released `sourcegraph/server:2.13.4` (see [changelog](https://about.sourcegraph.com/changelog/)). @ggilmore Could you please follow up and release 2.13.4 in deploy-sourcegraph, too?

**Comment by nicksnyder** [comment]
I am trying to cut 2.13.5 now so don't bother with 2.13.4 until 2.13.5 is cut (I am having issues with building our release branch since we upgraded node).

**Comment by nicksnyder** [comment]
Here is the build for 2.13.5:
https://buildkite.com/sourcegraph/sourcegraph/builds/23815
