### ISSUE TITLE
bad z-index in settings page

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#10431]
Repro: go to https://sourcegraph.com/users/sqs/settings (or some other user page) and open the search suggestions dropdown.

The "Settings" blue div is above the dropdown. Expected: below.

This might occur on other pages as well.

![image](https://user-images.githubusercontent.com/1976/81114883-ad032a00-8ed7-11ea-83ec-51d87b8de7d5.png)

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by Joelkw** [comment]
This was fixed https://github.com/sourcegraph/sourcegraph/commit/00fe2a031925c30343ebd96ae9d83694cb501d71
