### ISSUE TITLE
doc update: code intel CI guides instructions to pass workflow even if indexing fails

### ISSUE THREAD

**Issue by gbrik** [sourcegraph/sourcegraph#10452]
right now the default instructions for setting up a CI workflow will cause builds to fail if LSIF indexing fails. this could be annoying, so we should mention the potential issue and provide instructions to have the workflows emit a pass even if indexing/uploading fails.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by nicksnyder** [comment]
@gbrik Will these doc updates happen by the 20th? If not, please move this to 3.17 milestone and add planned/3.17 label

**Comment by gbrik** [comment]
yes, doing these today
