### ISSUE TITLE
Sourcegraph.com - add redis-store & precise-code-intel-bundle-manager snapshotting

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#10450]
- precise-code-intel-bundle-manager contains LSIF upload data we ideally do not want to lose. It's not critical if lost, but we should avoid losing it if we can. Backups of this are ideal.
- redis-store now contains user analytics/metrics data (from what I understand) so it is in a similar boat: not critical to keep, but ideal to keep.

We should add snapshotting for both on Sourcegraph.com.

**Comment by daxmc99** [comment]
We recently migrated Sourcegraph.com. This is an ideal time to ensure snapshot schedules for:


- precise-code-intel-bundle-manager
- redis-store
- redis-cache
- indexed-search (can be regenerated but the size makes this prohibitive) 
- repos-gitserver (can be regenerated but the size makes this prohibitive)
