### ISSUE TITLE
Basic code intel icon obscures type signature

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#10459]
Reported by https://app.hubspot.com/contacts/2762526/company/693777200

A user noted that the "i" icon obscures the type signature for them most of the time. Is it possible to make it appear to the side of that row, rather than as an overlay? Or perhaps only come up when you hover? Or etc.

![image](https://user-images.githubusercontent.com/5589410/81239975-0abc7280-8fbb-11ea-93a4-afbf8aa6e4d3.png)

**Comment by efritz** [comment]
This should probably be a change owned by @sourcegraph/web .

**Comment by gbrik** [comment]
I'll make sure to cover this during this redesign: #10083

**Comment by felixfbecker** [comment]
@gbrik if you don't mind, I'd like to solve this on the web team independently of redesign plans (the close button somewhat has the same problem)
