### ISSUE TITLE
add terraform configuration for sourcegraph.com's infrastructure 

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#10455]
See https://github.com/sourcegraph/sourcegraph/issues/10454#issuecomment-624884680

Using terraform to provision sourcegraph.com's infrastructure is a more maintainable / sustainable than just using the gcloud CLI.

**Comment by nicksnyder** [comment]
FWIW, I think https://github.com/sourcegraph/sourcegraph/issues/10465 is more important.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
