### ISSUE TITLE
Link to Perforce change list from whenever a `[git-p4: ...]` appears in a commit message

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#10460]
Reported by https://app.hubspot.com/contacts/2762526/company/693777200

This company is using src-expose and git-p4 to load Perforce repos into Sourcegraph.

A user noted that it's an annoying workflow to go from Sourcegraph's commit list, or commit diffs view, or from our diff/commit search results pages, etc. back to the corresponding change list on Perforce.

Thankfully, git-p4 annotates every commit message with info about the depot and change — it adds a line to the bottom that looks like:

`[git-p4: depot-paths = "//depot-mobile/project/": change = 1794239]`

(copied from the example at https://www.atlassian.com/git/tutorials/git-p4)

An extension that could turn this into a link in our UI (rather than code) would be great! Is that even possible using our extension API, though, @felixfbecker @twop ?

**Comment by unknwon** [comment]
Unlike Git code hosts which often have a web interface (that we can generate a URL for), all interactions with the Perforce Server are all through Perforce client GUI (P4V) or CLI (p4). How would we compose the "url" for the Perforce clients? 

Or is extracting the information ("depot-paths" and "change") then display them in the UI is good enough?

**Comment by dadlerj** [comment]
Ah interesting... Perhaps the URL could just be set in a setting or config value?

**Comment by unknwon** [comment]
That could work, but would like a confirm from users to make sure URL really make sense, importantly, ask them what do they expect to be convenient.

**Comment by oacnhpkqxjhufwumkkqnshvlmheokqv** [comment]
If the customer has Helix Swarm (a web UI for code reviews) installed, the link to a p4 changelist in Swarm would be https://<customer's Swarm FQDN>/changes/<CL number>

Swarm also has a basic file browser, so if there's interest in creating a link to a file in Swarm, the URL format would be https://<customer's Swarm FQDN>/files/<file path>/<file name>.<file extension>?v=<file version number>

**Comment by peterguy** [comment]
closing - handled by #48278, #46488, #40330
