### ISSUE TITLE
Download raw file fails on large repos

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#10466]
Reported by https://app.hubspot.com/contacts/2762526/company/693777200

>We’ve had users report that download raw file is failing.  I can reproduce it as well, we navigate to a file, click on the button and nothing seems to happen for 5-10 seconds.  Then I see the download start and immediately fail. (Error message in Chrome is just ‘Failed - Server problem’).  Any ideas?
>
> And by 5-10 seconds, I really mean closer to a few minutes as I tried to actually time it and gave up.

Discussion in Slack at: https://sourcegraph.slack.com/archives/CHPC7UX16/p1587695598217700

Suggestion by @unknwon:
>Are they having monorepo or huge repo? The way I see the current raw endpoint works is by first fetching an archive of the commit, then extract that single file from the archive. Pretty wasteful I would say… so could be timing out on fetch the ZIP archive.

Related: https://github.com/sourcegraph/sourcegraph/pull/9410, https://github.com/sourcegraph/sourcegraph/issues/9372, https://github.com/sourcegraph/sourcegraph/issues/1995

**Comment by tsenart** [comment]
@ryanslade: Do you have enough buffer this iteration to take a look at this?

**Comment by ryanslade** [comment]
Sure, I'll take a look. As it's a bug I'll prioritise it above my other work.

**Comment by tsenart** [comment]
@ryanslade: I saw no mention of this on this week's plan. Do you intend to work on it next week instead?

**Comment by ryanslade** [comment]
My bad, I'll take a look at it ASAP. I missed it because I was concentrating on tickets in the campaigns tracking issue

**Comment by ryanslade** [comment]
@keegancsmith I see there is quite a lot of history around this issue related to removing the need to keep archives on the frontend

Do you think we should add a special case for when a user requests a single raw file? In that case could we not run something like `git show revision:path` on gitserver and forward the result?

It looks like in the case of a directory our raw endpoint returns a list of the files, which is very close to the output of `git show` so I think it should work too.

WDYT?

**Comment by keegancsmith** [comment]
yes that is exactly what we need to do. Use git show instead. A decent approach is to see how we fetch file contents in our graphql layer. It really should be the same for this endpoint.

**Comment by ryanslade** [comment]
Do you mean this code?

https://github.com/sourcegraph/sourcegraph/blob/662ad6a70824059f39ae59fa5f7e1778bb4b0c33/cmd/frontend/graphqlbackend/git_tree_entry.go#L73

I notice that uses  `backend.CachedGitRepo` and I thought in this case we didn't want to perform caching?

**Comment by keegancsmith** [comment]
Thats the correct code. `CachedGitRepo` is misleading. This was from when we used to validate a repo still existed on a codehost when doing a request. `CachedGitRepo` avoided that request. So this will speak to gitserver.
