### ISSUE TITLE
Home/End key presses apply to search autocomplete dropdown, not the search bar text

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#10463]
Reported by https://app.hubspot.com/contacts/2762526/company/693777200

>go to the search bar and start typing something, let’s say “migration”. the popdown list appears. then let’s say you want to correct your typing. the arrow keys work, but pressing Home and End apply to the popdown list, not to the search bar. IOW, confusing when you are trying to make a correction and the keyboard doesn’t work as you’d expect.

**Comment by fkling** [comment]
I don't think that's an issue anymore with the new search input.
