### ISSUE TITLE
Git ops for CRUD operations all of our (Sourcegraph's) k8s clusters

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#10465]
This issue is complete when:
- [ ] Nobody has write access to GKE resources in our production GCP account from their @sourcegraph.com Google account.
- [ ] The only way to create, update, or delete GKE resources that we (Sourcegraph) owns is by merging a (code reviewed) PR to the master branch of a git repo (the change is then automatically applied in CI).

**Comment by slimsag** [comment]
To clarify this slightly, this is only for our k8s clusters. Not customers' (where we would not want to impose such a technology)

**Comment by slimsag** [comment]
@davejrt I've removed you from this issue to indicate @daxmc99 to be the sole owner here. Feel completely free to pair up on this, work together on it, etc. though. I've just removed to make it clear that most of your time will be spent on $CUSTOMER.

**Comment by daxmc99** [comment]
This appear to be devops issue
