### ISSUE TITLE
Non-smart search field indicates incorrect defaults for fork: and archive:

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#10479]
Reported by https://app.hubspot.com/contacts/2762526/company/407948923

![image](https://user-images.githubusercontent.com/5589410/81325574-68999a80-904d-11ea-9478-b3465c9a726d.png)

Repro:
* Visit .com
* Add the following to personal settings:
```  
  "experimentalFeatures": {
    "smartSearchField": false
  },
```
* Type in `fork:` or `archive:` to the search bar
* Note that it indicates "Yes" is the default

**Comment by rvantonder** [comment]
Thanks. The value from [this setting](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@d033866151b22827739b2c002e8fe06342d15045/-/blob/schema/settings.schema.json#L109-114) should be tracked. If I get a chance I'll look into this soon, unless someone on web beats me to it.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by rvantonder** [comment]
![Screen Shot 2020-08-13 at 9 00 34 PM](https://user-images.githubusercontent.com/888624/90212410-17b1e480-dda8-11ea-8a45-de13d2c7b98d.png)


The UI no longer displays the default, so I'm closing this. Not sure which PR changed that.
