### ISSUE TITLE
Docker Compose should be released on the 20th

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#10486]
Including https://github.com/sourcegraph/sourcegraph/pull/10467 and other docs updates.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by slimsag** [comment]
This was fixed via https://github.com/sourcegraph/about/pull/1223 and the docs I added in https://github.com/sourcegraph/deploy-sourcegraph-docker/blob/master/RELEASING.md as part of 3.17.
