### ISSUE TITLE
DB backcompat tests are flaky

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#10498]
I've seen multiple CI runs where the DB backcompat tests failed, the branch was up to date and no DB schema was changed.

Example: https://buildkite.com/sourcegraph/sourcegraph/builds/62971#e2e9fcbd-b76a-4ad1-a6a0-4bf284cca2a4/5214-5219

**Comment by unknwon** [comment]
Quick observation: all failed with same error `pq: column "tracing_context" of relation "lsif_uploads" does not exist`. cc @efritz in case you have anything in mind.
