### ISSUE TITLE
Search autocomplete for files doesn't specify repo

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#10509]
Reported by https://app.hubspot.com/contacts/2762526/company/693777200

> When you have the same file across multiple repos, you can’t tell which is which
> ...
> Not a major issue, but it would be nice if there was another way to present that information in the results

As a simple example :) 

![image](https://user-images.githubusercontent.com/5589410/81439800-cbf5fc00-9123-11ea-87f1-86261fbf15ae.png)

**Comment by malomarrec** [comment]
Tagging similar issue in #20158 to feed into prioritisation work.

**Comment by fkling** [comment]
I think we still don't add the repository when selecting a file, but we at least we show the complete file path now.
