### ISSUE TITLE
RFC 136: Version context design

### ISSUE THREAD

**Issue by christinaforney** [sourcegraph/sourcegraph#10518]
Initial designs: https://www.figma.com/file/Sax8ctk8GhvWd0vrzkHSDK/Version-Contexts?node-id=0%3A1

**Comment by rrhyne** [comment]
Design comps should be locked up and ready to go. Figma file:

https://www.figma.com/file/Sax8ctk8GhvWd0vrzkHSDK/Version-Contexts?node-id=0%3A1&viewport=151%2C441%2C0.125

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
