### ISSUE TITLE
Our usage of Caddy and Nginx is inconsistent

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#10569]
Today we use Caddy in Docker Compose setups, but not:

- [ ] Kubernetes (nginx currently, switching to caddy is important)
- [ ] server (nginx currently, switching to caddy is less important)

We should use one web server in all deployments. This reduces support burden and would mean we could e.g. use a single Prometheus metric exporter for Caddy instead of one for Nginx and one for Caddy.

cc @ggilmore for thoughts on when we can do this

**Comment by virginiaulrich** [comment]
No longer relevant given shift away from single image as supported production deployment; current single image for trials is working without issue for customers
