### ISSUE TITLE
campaigns: duplicate index in database

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#10563]
On `patches` `campaign_jobs_campaign_plan_id (patch_set_id)` is covered by `campaign_jobs_campaign_plan_repo_rev_unique (patch_set_id, repo_id, rev)`.

**Comment by mrnugget** [comment]
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/9580

**Comment by keegancsmith** [comment]
Thought I had filed this before, but a quick issue search I did didn't
turn it up. Another reason we need normal grep for github issues :)
