### ISSUE TITLE
repos: include deleted_at in repo db index

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#10565]
The suggested query to run is 

```
CREATE INDEX CONCURRENTLY ON repo (deleted_at, name)
```

we may instead want to extend an existing index or possibly just index null deleted_at.

![image](https://user-images.githubusercontent.com/187831/81587362-370b3100-93b7-11ea-8e55-cf1ef6b10b71.png)

cc @sourcegraph/core-services

**Comment by tsenart** [comment]
It's done.
