### ISSUE TITLE
perms: speed up queries on user_id

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#10564]
Will have a bigger impact for enterprises than what is being reported for sourcegraph.com

```
CREATE INDEX CONCURRENTLY ON user_external_accounts (user_id)
```

![image](https://user-images.githubusercontent.com/187831/81587197-fe6b5780-93b6-11ea-8296-963e41cc567a.png)

**Comment by unknwon** [comment]
What is this magic? It just tells us which column we should have index? 🤯

**Comment by keegancsmith** [comment]
pghero instance connected to production.
