### ISSUE TITLE
RFC 136: Version context design testing

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#10574]
Version context design prototype will allow us to test the version context designs for several tasks:

* Identifying which version context the user is in, in various states
* general usability of the version context selector dropdown
* The version context name
* Requirement of setting multiple contexts

Additionally, this prototype will serve as a trial of user testing services.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by keegancsmith** [comment]
@rrhyne This is tracked as done. Can we close?
