### ISSUE TITLE
docs: recommend disabling indexing on forks for public repos

### ISSUE THREAD

**Issue by gbrik** [sourcegraph/sourcegraph#10576]
The recommended precise code intel CI workflow right now will run the indexer on forks of the original repo. The supplied templates should make the opposite behaviour the default along with an explanation.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by nicksnyder** [comment]
@gbrik Will these doc updates happen by the 20th? If not, please move this to 3.17 milestone and add planned/3.17 label

**Comment by gbrik** [comment]
yes, doing these today
