### ISSUE TITLE
Missing monitoring for nginx/caddy

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#10570]
A customer https://app.hubspot.com/contacts/2762526/company/464956351/ requested we monitor for the case of "nginx returns 504 while the frontend returns 200" and this is a type of issue that has caused us issues in the past.

It may or may not make sense to complete our migration to Caddy first: https://github.com/sourcegraph/sourcegraph/issues/10569

**Comment by uwedeportivo** [comment]
https://github.com/nginxinc/nginx-prometheus-exporter

**Comment by uwedeportivo** [comment]
https://github.com/hairyhenderson/caddyprom
