### ISSUE TITLE
Explore inline install of the browser extension from Sourcegraph.com

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#10589]
Rather than linking to our browser extension docs, which themselves link to the web store, [inline installation](https://developer.chrome.com/webstore/inline_installation) of the browser extension directly from sourcegraph.com (for example, after clicking on the "install the browser extension" CTA) would be a much simpler flow.

**Comment by lguychard** [comment]
cc @marekweb we discussed this today. Things to think about:
- Would inline install be possible from customer instances (not just from sourcegraph.com?)
- If installing from customer instances, would it be possible to automatically configure the Sourcegraph URL and relevant permissions (to the instance URL, code hosts URL) during inline install?
- Other things that might improve onboarding post-install (eg. link to a public code host where we know users will see a hover, to demonstrate what the extension can do)

**Comment by lguychard** [comment]
@marekweb tentatively assigning this to you for 3.17, as I think it would be a nice improvement when paired with #10409

**Comment by marekweb** [comment]
The feature called "inline installation" has been deprecated in Chrome. The recommended alternative is to link directly to the Chrome Web Store page of the extension.

We can still explore the other improvements to make the installation flow smoother, and I'd like to see if automatic configuration is possible. and whether we can pass on some context from wherever the CTA interaction happens to the installation of the extension.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by felixfbecker** [comment]
Closing per @marekweb's comment above and the improvements we made
