### ISSUE TITLE
Scope all of our CSS in the browser extension

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#10595]
We currently import CSS in the browser extension from `shared/` that gets added to the global CSS, on Firefox even on all pages. Some of this CSS has high chance to conflict, like `.toggle`, and breaks other sites (e.g. #8489, #5889).

We experimented with solutions like shadow DOM in the past (#2358), but they don't work well with React and some libraries.

SCSS supports `@import` within a selector, which scopes all imported selectors to that selector. We can use this to scope all imports to a common base class we assign to all our mount points:

```scss
.sourcegraph-element {
  @import '../../shared/src/Toggle.scss';
  @import 'bootstrap';
  // ...
}
```

Action items:
- [ ] Assign a defined CSS class to all mount points
- [ ] Change all imports and definitions in the browser extension content script styles to be nested under that class

**Comment by twop** [comment]
Maybe this an opportunity to revisit how do we style browser extension's content overall?
Example: css-modules (which I personally dislike) or handful of other approaches. I recently did a reasearch on this subject, happy to share ideas/findings.

**Comment by felixfbecker** [comment]
Having watched the space too, my intuition is that way we handle CSS right now fits the constraints the best, but if you have a better proposal, please do not hesitate to write an RFC :)

I think this issue though is a quick win so we shouldn't block on such a discussion :)

**Comment by marekweb** [comment]
It's true that one of the so-called css-in-js solutions could solve the scoping problem out-of-the-box, but I agree that we could have that discussion elsewhere. Also it's a discussion that is typically a bikeshedding magnet :magnet:

**Comment by noonien** [comment]
Any update on this?

The Sourcegraph extension is unusable because of conflicting CSS with websites completely unrelated to SG.

I'm running FF 82.
