### ISSUE TITLE
Branches in branch switcher cannot be clicked anymore

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#10590]
![2020-05-12 10 41 52](https://user-images.githubusercontent.com/10532611/81662033-492fb280-943d-11ea-81ab-bd31956e775b.gif)

https://sourcegraph.com/github.com/npm/cli

**Comment by metamorfoso** [comment]
Hi there. I've been following sourcegraph with interest, and I've raised a quick PR to fix this issue.

**Comment by eseliger** [comment]
Closed in #10596
