### ISSUE TITLE
Use `git diff --stat` as possible optimization for changeset diff stats

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#10607]
To compute the diff stats for a campaign we currently:

1. make N requests to `gitserver` (N = number of changesets in a campaing) to get the full diff for each changset
2. parse each diff to get the diff stats
3. add up the diff stats

What we could do as an optimization is to ask gitserver for the diff stat directly.

---

This call to `DiffStat`

https://github.com/sourcegraph/sourcegraph/blob/938f0628eba30c9f29cc6376880caf0d4c384d32/enterprise/internal/campaigns/resolvers/campaigns.go#L307-L314

ends up making the request to `gitserver` here:

https://github.com/sourcegraph/sourcegraph/blob/938f0628eba30c9f29cc6376880caf0d4c384d32/cmd/frontend/graphqlbackend/repository_comparison.go#L183-L222

We could, for example, have a method on `fileDiffConnectionResolver`, called `ComputeDiffStatOnly`, that makes nearly the same request to `gitserver`, except that it adds the `--stat` flag to the `git diff` command and parses that output.

Or we can use `--numstat` or `--shortstat`.

**Comment by LawnGnome** [comment]
There's a complication here: the way [go-diff](https://github.com/sourcegraph/go-diff) calculates the diff stats is semantically different to how `git diff` calculates stats.

go-diff has a concept of a [changed line](https://sourcegraph.com/github.com/sourcegraph/go-diff/-/blob/diff/diff.pb.go#L89-90), which is [an added line immediately followed by a deleted line, or vice versa](https://sourcegraph.com/github.com/sourcegraph/go-diff/-/blob/diff/diff.go#L30-48). I think this is inspired by (although not _exactly_ the same as) [diffstat(1)'s `-m` option](https://linux.die.net/man/1/diffstat), which calculates the modified lines for mixed add/delete chunks. Although `git diff` reproduces the main functionality of `diffstat` via the various `stat` flags, the [modified line functionality isn't included](https://sourcegraph.com/github.com/git/git@b3d7a52fac39193503a0b6728771d1bf6a161464/-/blob/diff.c#L2527-2530).

Essentially, I think we have three choices:

1. Do nothing, and maintain the existing behaviour and implementation.
2. Move the stat calculation into `cmd/gitserver`. We'd still need the full set of patches, we'd just stream them into an internal go-diff [`MultiFileDiffReader`](https://sourcegraph.com/github.com/sourcegraph/go-diff/-/blob/diff/parse.go#L31) (which would be a new dependency for `cmd/gitserver`) or pipe them into `diffstat -mt` (which would then become a runtime dependency). This preserves the behaviour and saves some over-the-wire traffic between `gitserver` and `frontend`, at the cost of some build or runtime complexity.
3. Drop the changed semantics for campaign diff stats, and only show added/deleted, which we _can_ calculate entirely in `gitserver` by adding `--numstat`.

I'm going to prototype out the go-diff version of option 2 quickly, just to see how it feels, but I think all three options are probably on the table depending on the tradeoffs we want to make.

**Comment by mrnugget** [comment]
Thanks for diving into this and the thorough explanation here!

I think (3) is out-of-scope for this, since it would include changing how we cache and calculate the diff stats for `*campaign.Patch`, too. And there are other places in Sourcegraph where we display the diff stats as calculated by `go-diff`, I think. (@eseliger might know more about this, though.)

So, I'm torn between (1) and (2). If (2) is an actual performance improvement and not too much work, I think it'd be nice to have that diff-stat-calculation logic moved to `gitserver`.

But here's why I suspect it might not be a big performance improvement: I think in a lot of cases (not constrained to `campaigns`) in which we display the diff stats we also display the diff. Right now that means we only have to load the diff once from `gitserver`, then do our calculations in memory and render out the diff.

If we were to move the diff stat calculation to `gitserver` we do the parsing twice: once on our end, in `graphqlbackend`, and once on `gitserver`'s.

Again: if you think it'll be an actual runtime improvement and it's not too much work, go for it.

If you don't think it's worth it, then I suggest dropping the approach here, closing the ticket, and moving to https://github.com/sourcegraph/sourcegraph/issues/11075 which promises to yield a bigger performance improvement.

**Comment by eseliger** [comment]
One slight concern I would have with (2) is that frontend is horizontally scalable, while gitserver is not (at least not easily).

If it's not feasible, I agree with @mrnugget that only implementing #11075 should be fine.

**Comment by LawnGnome** [comment]
My sense is that this isn't worth it right now, and your points about scalability and needing the full diff in a lot of cases anyway are good ones.

Closing for now, and I'll go focus on #11075. Let's come back to this if we end up feeling like we're network constrained at some point.
