### ISSUE TITLE
Global abuse protection of all public endpoints

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#10629]
As we develop sourcegraph.com further according to RFC151, the need for protecting that deployment from Denial of Service attacks and other forms of abuse will increase.

Currently, we don't have any form of API rate limiting in place (i.e. GraphQL). We should follow prior art on other GraphQL APIs and use [cost based estimation on each query](https://developer.github.com/v4/guides/resource-limitations/).

Additionally, any other public endpoint that isn't the GraphQL API, also needs some form of rate limiting in place. We may be able to leverage Cloudflare for this, as well as DDoS protection.

Requested by:
* https://app.hubspot.com/contacts/2762526/company/464956351
* https://app.hubspot.com/contacts/2762526/company/557692805

From the latter:

>given that i can envision (over the long-term) teams wanting to build automation using the API, something we've noticed with GHE is that teams will create tooling without regard to load impact ... so having rate limiting will minimize our need to play "whack-a-mole" usage cops ... with GHE, we frequently see teams that put things in place that run on schedules ... often times they get unintentionally mis-configured and we end up having to chase down the bad actors in a reactive manner

Related: 
* https://github.com/sourcegraph/sourcegraph/issues/5705
* https://github.com/sourcegraph/sourcegraph/issues/5706

**Comment by unknwon** [comment]
cc @eseliger because we chatted very quickly about cost estimation yesterday.

**Comment by slimsag** [comment]
See existing issues for GraphQL:

- https://github.com/sourcegraph/sourcegraph/issues/5705
- https://github.com/sourcegraph/sourcegraph/issues/5715

**Comment by ElizabethStirling** [comment]
RE: conversation with @nicksnyder and @chayim, we think that abuse protection should be fully covered by the Cloudflare WAF + rate limiting. We don't want to worry about adding rate limiting to the product unless on-prem customers request it for their own instances. Unless anyone has any objections, I think we should close this issue. @tsenart, thoughts?

**Comment by eseliger** [comment]
I think GraphQL is not very well covered by Cloudflare, since they cannot tell how much effort single fields are to compute. I could request 1 repo at a time, 10k times an hour and it's combined compute time would be 35s (made up numbers), but I could also request 10k diff renders across 20 different branches each time and the combined compute time would be 1000*20*1.5s = 30000s = 500min. Not saying we need to act immediately, but I think we should keep it in mind.

**Comment by tsenart** [comment]
Perhaps an intermediate solution would be to restrict API access to paid customers?

**Comment by chayim** [comment]
> I think GraphQL is not very well covered by Cloudflare, since they cannot tell how much effort single fields are to compute. I could request 1 repo at a time, 10k times an hour and it's combined compute time would be 35s (made up numbers), but I could also request 10k diff renders across 20 different branches each time and the combined compute time would be 1000_20_1.5s = 30000s = 500min. Not saying we need to act immediately, but I think we should keep it in mind.

Part of the reason for rate limiting requests is to reduce socket exhaustion, not only lower compute usage. With today's usage, layer 3/4 rate limiting still helps on the DDOS attack side, even if it doesn't solve the issue permanently.
