### ISSUE TITLE
Add cookie for maintaining UTM parameters after navigating from landing page

### ISSUE THREAD

**Issue by ebrodymoore** [sourcegraph/sourcegraph#10639]
### Background

We can't report the effectiveness of digital campaigns unless UTM parameters are maintained once the browser navigates from a landing page. Results right now are showing close to 0 MQLs for all marketing campaigns through the `utm_source` parameter, which I don't think is true. 

More discussion here: https://sourcegraph.slack.com/archives/CNC4YAL1E/p1589302784090800

**Comment by aileenrose** [comment]
Let's move to about.sourcegraph.com issue.
