### ISSUE TITLE
zoekt error rate unit is wrong (5m fix)

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#10644]
in seconds not shorts as expected:

https://k8s.sgdev.org/-/debug/grafana/d/zoekt-webserver/zoekt-web-server?orgId=1&from=now-2d&to=now

![image](https://user-images.githubusercontent.com/3173176/81859341-f4ae3500-9519-11ea-873b-561125dc98a4.png)

**Comment by bobheadxi** [comment]
seems to have an appropriate percentage now (as of https://github.com/sourcegraph/sourcegraph/pull/12882):

https://sourcegraph.com/-/debug/grafana/d/zoekt-webserver/zoekt-web-server?viewPanel=4&orgId=1&from=now-2d&to=now
