### ISSUE TITLE
Feedback: smart search loading jitter

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#10649]
Just some personal feedback--one of the reasons I turned off smart search locally is because there was a lot of jitter on resizes/changes to the font in the query. This seems to have improved but it still exists. Example:

![smart-search-jitter](https://user-images.githubusercontent.com/888624/81867563-c0d90c80-9525-11ea-92b0-4657c2183ca8.gif)

The jitter on the keyboard icon next to the query is a separate issue (which I'm not a fan of either but it's OK I guess if there are reasons for this). But the part that compounds this issue is that on that part of the loading, the old query syntax font and size is shown briefly even while smartsearch is enabled:

<img width="912" alt="Screen Shot 2020-05-13 at 2 31 25 PM" src="https://user-images.githubusercontent.com/888624/81868043-8328b380-9526-11ea-9b97-0f4b69193f94.png">

 and then the other smart search font, and later, coloring kicks in. 

---

Compare to smart search turned off, where the font sizing stays consistent:

![no-jitter-smartsearch](https://user-images.githubusercontent.com/888624/81867571-c2a2d000-9525-11ea-8cf1-19d56083f504.gif)

Again, very much an issue coming from my personal taste. But just giving the feedback that this small jitter thing is enough for me prefer the old, undecorated syntax because it just feels smoother/more polished. I'd easily switch to smart search with highlighting and such if the visual loading was similar to the old style.

**Comment by rvantonder** [comment]
Just tagging you @lguychard for feedback, not saying this needs to be addressed.

**Comment by lguychard** [comment]
I think there's one more quick win here that would greatly reduce jitter, I'll look into getting that in tomorrow.

**Comment by lguychard** [comment]
@rvantonder the initial React state values controlling smart search & split search modes (the button to the left of the search field) have been changed to match the feature flag defaults. This means:
- The jitter on the keyboard icon next to the query will no longer be there
- The jitter of old font -> new font will no longer be there
