### ISSUE TITLE
Vast Docker image edge cases users rely on are not tested

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#10646]
We increasingly have constraints with our Docker images, such as:

1. Containers should run correctly both as root and non-root users.
2. The container UID/GID should be static and consistent with our other containers.
3. That the UID/GID be a specifically large value to avoid host conflicts: https://github.com/sourcegraph/sourcegraph/issues/10645
4. That images be published under the Sourcegraph docker hub organization
5. That images be versioned with Sourcegraph tags and we do not introduce dependencies on other versions (i.e. that we republish images).
6. That containers do NOT write outside of $HOME unless it is a mounted volume (e.g. writing to an ephemeral/unmounted path `/prometheus_config/promethues.yml` is forbidden in some k8s environments)

Trying to support and test all of these cases has caused us and customers much pain in the past. We should add better testing infrastructure to assert all of these conditions are true to avoid these pains and to avoid painful migrations.

**Comment by pecigonzalo** [comment]
Ill break this down into multiple issues

**Comment by pecigonzalo** [comment]
@slimsag could you clarify these 2?
> That images be published under the Sourcegraph docker hub organization

I believe this is already the case.

> That images be versioned with Sourcegraph tags and we do not introduce dependencies on other versions (i.e. that we republish images).

Isnt this the case as well? Or is this about not re-pushing an existing V tag?

**Comment by pecigonzalo** [comment]
> Containers should run correctly both as root and non-root users.
> The container UID/GID should be static and consistent with our other containers.
> That the UID/GID be a specifically large value to avoid host conflicts: #10645

I think this needs to be addressed when we migrate to non-root by default, which we have already been discussing.

**Comment by pecigonzalo** [comment]
>That containers do NOT write outside of $HOME unless it is a mounted volume (e.g. writing to an ephemeral/unmounted path /prometheus_config/promethues.yml is forbidden in some k8s environments)

Im not sure we can test for this, we could ensure that the user only has `write` permissions on the places it needs to write to, with something like https://github.com/aelsabbahy/goss and `dgoss`.
