### ISSUE TITLE
Make it possible to easily get slack/pager notifications for each defined alert in Sourcegraph

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#10640]
Today you can configure two alerts at the topmost level, one for critical alerts in Sourcegraph and one for warning alerts in Sourcegraph and then when you get notified via slack, pager, email, etc. go over to Sourcegraph's Grafana to identify the cause.

But, it would be nicer if there was an easy way to get the actual alert name / description / service name as part of the alert Grafana sends. This may be difficult to implement because Grafana alerting does not support templating in alert definitions, currently, so this issue may involve fixing that: https://github.com/grafana/grafana/issues/6557

**Comment by bobheadxi** [comment]
I'll cover this in https://github.com/sourcegraph/sourcegraph/issues/11452
