### ISSUE TITLE
observability: Alerting should be easily configured through a file or site configuration

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#10641]
Meta tracking issue to make alerting configuration nicer than a painful series of steps through the Grafana UI; I am pretty sure another exists for this already as we are working on this - I just couldn't find it.

**Comment by bobheadxi** [comment]
Is the main goal of this to:

> Make it possible to configure Grafana alerting via a file on disk (currently we use hacky UI editing which is tedious and easily gets undone)

(from https://github.com/sourcegraph/sourcegraph/issues/5370#issuecomment-629406540)

**Comment by slimsag** [comment]
@bobheadxi I'm adding you to this in hopes you can get around to it sooner because this is extremely important.

Here's the TL;DR of the problem:

Right now we tell people you must configure alerting for Grafana through the web UI by following [these instructions](https://docs.sourcegraph.com/admin/observability/alerting#set-up-alerts-in-grafana) but this has a few major problems:

- You must port-forward direct access to Grafana because of a CSRF bug https://github.com/sourcegraph/sourcegraph/issues/6075
- It involves a series of steps in the UI which is quite tedious / painful to follow
- I am not actually sure those steps/instructions really do work
- It is not possible in Grafana to configure alerts on provisioned dashboards (like the overview dashboard) because you cannot save changes to them (Grafana forbids it)
- It is constantly a worry that with each upgrade of Grafana, or change we make to our dashboards, that some customer out there is relying on it for alerting and it may get e.g. overridden when they upgrade. (e.g. if they *could* configure alerts on the overview dashboard, I would be worried that if the overview dashboard changes then when they upgrade they would lose configured alerting).
- Many customers have to duplicate the dashboards we provide in order to edit them to add alerts; which means they then don't get updated

In short, configuring alerting through the Grafana web UI feels very much like the wrong approach. Much more preferable would be being able to configure it through a file on disk because then we can treat Grafana as entirely ephemeral (and e.g. even remove its persistent volume so if it restarts all data comes 100% from disk).

We should try to make this as nice of a process as possible, because eventually we'd like to have it directly in the flow of setting up Sourcegraph (e.g. "install sourcegraph, configure your code host, set up alerting.") - so I am very open to ideas on how we can make this nice. Possible solutions that come to mind for me include:

- Instead of using Grafana's native config file format (which likely includes a lot more than just alerting), pass the configuration via env vars. Look at the existing grafana configs in our codebase and in deploy-sourcegraph, I think this is already supported possibly.
- Instead of using Grafana's native config file format, store the config as part of the Sourcegraph site config. This would be really nice because then you could do it entirely from the Sourcegraph web UI -- but this would involve adding a Go process into the Grafana docker container which pulls the site config from Postgres (we wouldn't want to get it from the frontend itself, because it might be down and we wouldn't want that to cause monitoring/alerting to go down too).

I would encourage you to explore the options above and see what makes sense to you and seems nicest.

More importantly, there is an immediate problem here that is urgent: How does someone running e.g. the latest Sourcegraph 3.16.1 release configure monitoring? Is it possible to do this from a file today? It would be ideal to investigate this first and then document it, if so, because right now most cannot configure alerting. If it's not possible, focusing on the longer term solutions above makes more sense (and becomes more urgent).

**Comment by bobheadxi** [comment]
For reference:

* [grafana alerting in config file](https://grafana.com/docs/grafana/latest/installation/configuration/#alerting)

**Comment by bobheadxi** [comment]
Had a chat with @davejrt and tentative direction I'll be exploring:

1. add configuration for `notificationChannels` and `alerts` under a new `observability` block in site config
   * `alerts` could either be entire dashboard jsons or just the condition, and we generate the dashboard for them... still looking at the config for this
2. add a sidecar to the grafana container to poll/subscribe for updates to site config. sidecar will then use the new `observability` fields to make the appropriate updates to grafana
   * I feel like it might be okay for this config to come from the frontend - if the sidecar fails to connect we can continue to use existing config, and in the event the frontend fails there's no trivial way to update the site config anyway (?) so it should be okay to expect that site admins will have to port-forward grafana to see what's going on anyway right?

**Comment by davejrt** [comment]
>    * I feel like it might be okay for this config to come from the frontend - if the sidecar fails to connect we can continue to use existing config, and in the event the frontend fails there's no trivial way to update the site config anyway (?) so it should be okay to expect that site admins will have to port-forward grafana to see what's going on anyway right?

is it any more difficult to query the DB directly rather than from the frontend? Site admins can udpate the siteconfig via the envvar and not only directly via the gui

https://sourcegraph.com/github.com/sourcegraph/sourcegraph@master/-/blob/cmd/frontend/internal/cli/config.go#L55:2

**Comment by bobheadxi** [comment]
> is it any more difficult to query the DB directly rather than from the frontend? Site admins can udpate the siteconfig via the envvar and not only directly via the gui

yeah I suppose it's probably not any easier/harder - suppose direct from DB is the neater solution :)

re: my thought:

> alternatively, it could be much more high level and simply allow site admins to subscribe to notifications through sourcegraph's alerts

quick sketch of what that might look like:

```json
    "observability.notificationChannels": {
      "type": "array",
      "items": {
        "type": "object",
        "description": "Grafana notification channels (https://grafana.com/docs/grafana/latest/http_api/alerting_notification_channels/#create-notification-channel)"
      }
    },
    "observability.alerts": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "ruleName": {
            "description": "Name of Sourcegraph alert rule (e.g. 99th_percentile_gitserver_duration)",
            "type": "string"
          },
          "serviceName": {
            "description": "Name of Sourcegraph service (e.g. frontend)",
            "type": "string"
          },
          "notificationChannelID": {
            "type": "string"
          }
        }
      }
    },
```

that said, the above won't work if allowing customers to describe custom metrics/dashboards through this is important, but I think just letting users set up notifications for our predefined alerts might be nice (since it doesn't seem trivial at the moment to do so, but I could be missing something here), and will allow us to handle migrations to new alerts etc pretty seamlessly 🤔

**Comment by slimsag** [comment]
Great to hear you're taking this approach in general! I'm very excited for this :)

> add a sidecar to the grafana container to poll/subscribe for updates to site config. sidecar will then use the new observability fields to make the appropriate updates to grafana

Instead of a sidecar container, I think you are better off doing this within the Grafana container itself. This would reduce the # of containers we must deploy (which, in some environments like pure-docker where customers effectively deploy the containers by hand is desirable but not a hard constraint).

You could for example create a Go binary that gets packaged into the same image and simply runs as the entrypoint before Grafana, and exits if anything is wrong with the Go binary or the Grafana entrypoint. https://github.com/sourcegraph/sourcegraph/blob/master/docker-images/grafana/Dockerfile#L54

This would also make it possible to "restart" Grafana when the configuration changes (I am not sure if Grafana can respond to config changes with live-reloading).

> I feel like it might be okay for this config to come from the frontend - if the sidecar fails to connect we can continue to use existing config, and in the event the frontend fails there's no trivial way to update the site config anyway (?) so it should be okay to expect that site admins will have to port-forward grafana to see what's going on anyway right?

This is a great point, I would be 100% okay with this as long as the config is persisted to disk in the Grafana container, so that if e.g. Grafana restarts and the frontend is down, the config is not lost.

This will likely be a lot easier, too, for two reasons:

1. If Grafana does need to connect to Postgres directly, customers will need to configure it to do so (since many customers run an external postgres DB). We would need to document this in multiple locations, so avoiding it is a nice property.
2. You could merely import the standard config package and respond to config changes the same way all our other services do, which means less code to maintain in the long run. It could be similar to the way repo-updater responds to changes in the frontend's postgres configuration here (only you'd just respond to `conf.Get().Observability` changes instead and restart after writing the updated Grafana config file to disk): https://sourcegraph.com/github.com/sourcegraph/sourcegraph@db715422d143fe21bb1d783b3dac4459ddb06d95/-/blob/cmd/repo-updater/shared/main.go#L59-69

> alternatively, it could be much more high level and simply allow site admins to subscribe to notifications through sourcegraph's alerts

I think this is the right approach. We should move in the direction of admins not being able to configure anything through Grafana itself and treat it as read-only. The more customizations we allow there, the more things we need to consider and it becomes a less nice out-of-the-box experience over time.

> quick sketch of what that might look like:

I think we shouldn't allow configuring specific alerts as you have under `observability.alerts`, instead let's only allow one to configure the notification channels. Then we get 100% control over how those are reported.

For now, it can be as simple as *only* alerting on the overview dashboard's two metrics: warning and critical. You can configure a notification channel for each. I would propose the following site config format:

```json
// Configures where Sourcegraph will send alerts.
"observability.alerting": [
    // Critical alerts are a definitive problem with Sourcegraph
    {
        "type": "slack",
        "level": "critical",
        ...
    },
    // Warning alerts may indicate a problem, but may also be a bit noisy. Send
    // them somewhere where you/others won't be bothered if they fire often.
    {
        "type": "email",
        "level": "warning",
        ...
    },
]
```

Each entry could effectively mirror the config options in https://grafana.com/docs/grafana/latest/administration/provisioning/#supported-settings which means you'd get nice autocomplete etc. in our site config editor, too.

**Comment by slimsag** [comment]
https://github.com/sourcegraph/sourcegraph/issues/10640

**Comment by slimsag** [comment]
https://github.com/sourcegraph/sourcegraph/issues/11210

**Comment by bobheadxi** [comment]
> You can configure a notification channel for each. I would propose the following site config format:

Do we want to allow multiple channels for each level? The array format seems to imply this should be possible 🤔

**Comment by slimsag** [comment]
> Do we want to allow multiple channels for each level? The array format seems to imply this should be possible 🤔 If not, should this config format be a map instead?

I think it would be good to allow this, but not required. Do whichever is easier.

> Also, just to clarify: only the new /monitoring dashboards have associated alerts right? (ie I can disregard the jsonnet ones here?)

This is 100% correct.

**Comment by bobheadxi** [comment]
Reopened by https://github.com/sourcegraph/sourcegraph/pull/11479 - see the PR for details of what's wrong still

**Comment by bobheadxi** [comment]
with https://github.com/sourcegraph/sourcegraph/pull/11483 this seems to be working :)
