### ISSUE TITLE
Code-Intel popup disappears without providing intel

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#10688]
- **Sourcegraph version:** 

3.15

- **Platform information:** 

Web version of sourcegraph.com I've observed in Chrome and Brave.

#### Steps to reproduce:

1. Find a function definition and hover it to make the code intel popup appear

#### Expected behavior:
If code intel is not available, present an info notice to users with information as to why, if available. If no information is available a general notice such as "Code Intelligence is not available for this function" would be an improvement.

#### Actual behavior:
1. A loading spinner briefly appears and the entire popover disappears with no code intel being shown and no explanation 
2. This is intermittent and I cannot pin down a reproducible pattern, but I feel it may be more likely on an unindexed repository.

**Comment by felixfbecker** [comment]
The challenge here is: How do you know the user hovered over a function that _should_ have a hover? As opposed to something that should not have any hover, like a word inside a string, a word inside a comment, a keyword, an operator, punctuation, whitespace...
Only the language indexer knows, but if we ask the indexer whether this position should have a hover and the language indexer tells us "this has no hover", how do we know the indexer is wrong?

**Comment by efritz** [comment]
cc @gbrik this is related to https://github.com/sourcegraph/sourcegraph/issues/10083 and [RFC 158](https://docs.google.com/document/d/1LkliTY4l-_S63hObBuiZ6g_izfF9IKrxnA9gEMK1FqA).

**Comment by efritz** [comment]
Also related: https://github.com/sourcegraph/sourcegraph/issues/10637.

**Comment by efritz** [comment]
Also related: https://github.com/sourcegraph/sourcegraph/issues/9346.

**Comment by rrhyne** [comment]
@felixfbecker I only experienced the issue when hovering over functions. I have not seen the popup appear and disappear in the other cases you mention. I'm probably just not following what you are saying correctly though.

That said, @ryan-blunden came up with a great idea about providing feedback through the popup which may be useful here. You can see it in the 'Feedback' section of [RFC 158](https://docs.google.com/document/d/1LkliTY4l-_S63hObBuiZ6g_izfF9IKrxnA9gEMK1FqA/edit)
