### ISSUE TITLE
mail package deprecated

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#10703]
We have an immediate need to fix these issues with the way Sourcegraph sends email:

- https://github.com/sourcegraph/sourcegraph/issues/10702
- https://github.com/sourcegraph/sourcegraph/issues/10700

But the upstream mail sending package we use https://github.com/jpoehls/gophermail has been archived and unmaintained for 4 years. Also, none of the mail sending code in Sourcegraph is tested so swapping it out is going to be risky.

https://github.com/go-gomail/gomail looks like a promising package to move to. Once implemented, we should manually test all email user flows work:

- saved search "subscribe" emails
- saved search notification emails
- saved search "unsubscribe" emails
- organization invite emails
- reset password emails
- emails on sourcegraph.com which use mandrill which I think we have some special code to disable click tracking
- Every other place we call txemail.send that might not work due to a difference in underlying mail package behavior

**Comment by unknwon** [comment]
A data point for using `go-gomail/gomail` (Gogs uses it). If the sender contains unicode, it breaks (could have workaround but never looked into it), e.g. `你好 <test@example.com>`.

https://github.com/jordan-wright/email is the one I might look into next.

**Comment by keegancsmith** [comment]
Noticed this issue and was interested how we use gophermail. It's super minimal and given how we use it I don't think we need to test every single email flow when replacing it. See https://github.com/sourcegraph/sourcegraph/pull/11285

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
