### ISSUE TITLE
Support AWS Simple Email Service (SES) for saved searches 

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#10700]
From @slimsag https://sourcegraph.slack.com/archives/CHPC7UX16/p1589491413374200?thread_ts=1589488108.373700&cid=CHPC7UX16

>We should file an issue for adding AWS Simple Email Service support, as well. I can imagine many companies use that and it shouldn't be hard for us to integrate.

Related to https://github.com/sourcegraph/sourcegraph/issues/10212

**Comment by benvenker** [comment]
Yeah I agree. For some reason I recall seeing this one and thought I added it to @camdencheek’s epic for code monitor improvements but I guess not. Thanks for resurfacing, I’ll add!

**Comment by camdencheek** [comment]
Closing as won't do. Saved searches don't exist anymore, and Code Monitors can use whatever email provider is set up with the instance. At worst, a user can create a webhook that can consume code monitor events and send it to SES
