### ISSUE TITLE
Ability to disable SMTP TLS verification

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#10702]
With two customers we have seen them only have SMTP servers with TLS verification disabled, meaning sending mail is not possible due to an error like:

```
internal API response error code 500: x509: certificate signed by unknown authority\n (http://127.0.0.1:3090/.internal/send-email)"
```

Currently, the only way to workaround this issue is by acquiring the CA certificate for the SMTP server (the customer has to know where to get this, usually from the team that manages the SMTP server) and then _appending_ that to the existing `/etc/ssl/certs/ca-certificates.crt` in the `frontend` containers (docker-compose: just frontend-internal container, single-container: just the single server container).

You can extract the CA certificates file from the running container like so:

```
docker exec -it $CONTAINER cat /etc/ssl/certs/ca-certificates.crt > ca-certificates.crt
```

Then, append your SMTP server's CA certificate to the `ca-certificates.crt` file it produces and then mount that into the container by altering the `docker run` command to add:

```
-v myconfig/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt
```

**Comment by dadlerj** [comment]
Requested by https://app.hubspot.com/contacts/2762526/company/554338610

@slimsag can you link to the other company that requested this?

**Comment by slimsag** [comment]
Apologies, I'm not sure how I forgot to link this one - I am confident that there was a second customer here aside from https://app.hubspot.com/contacts/2762526/company/554338610 but unfortunately cannot find the correspondence so I am no longer sure which it was.

**Comment by slimsag** [comment]
Related / pre-requisite: https://github.com/sourcegraph/sourcegraph/issues/10703

@sourcegraph/cloud can you consider this for 3.19? (we have a medium size customer requesting we fix this soon as it prevents them from using email notifications on Sourcegraph, have seen this at another customer, and seems like a bad debt area in our product - more context here: https://sourcegraph.atlassian.net/browse/SG-184 )

**Comment by bobheadxi** [comment]
FYI: #11832 adds a field in `email.smtp`, `disableTLS`, currently only used for `observability.alerts`

**Comment by unknwon** [comment]
Had a quick look, current gophermail has another function [`SendTLSMail`](https://github.com/jpoehls/gophermail/blob/62941eab772c480c968feea68faba37f941cc931/smtp.go#L37) which accepts a `tls.Config` (right now we use `SendMail`).

What we want here is to skip TLS verify but not necessarily disable TLS (though another valid option).

Seems the minimal change if it works out.

**Comment by unknwon** [comment]
I can commit one day for 3.19 to try out the approach I described above.

**Comment by tsenart** [comment]
@unknwon: I looked at your workload and you seemed quite overloaded already so didn't consider asking.

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by asdine** [comment]
[jordan-wright/email](https://github.com/jordan-wright/email) has a [SendWithTLS](https://godoc.org/github.com/jordan-wright/email#Email.SendWithTLS) function as well, so I'm gonna go with this library as you proposed in #10703 @unknwon
