### ISSUE TITLE
Hard reload required after enabling campaigns feature flag with no indication

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#10715]
When enabling campaigns, the user needs to do a hard reload after setting the campaigns feature flag. We should either

1. do the reload ourselves
2. add a notice that explains this to the user, similar to the "Server needs restart"

**Comment by eseliger** [comment]
@LawnGnome can I reassign this ticket to you so I can focus more on RFC 157?

**Comment by eseliger** [comment]
I think 2 is perfectly fine and much simpler. It really is just about the onboarding process, plus the feature flag is going to disappear at some point.

**Comment by LawnGnome** [comment]
> I think 2 is perfectly fine and much simpler. It really is just about the onboarding process, plus the feature flag is going to disappear at some point.

Makes sense. That's what I've implemented in #11118, then, which is now ready for review.
