### ISSUE TITLE
Migrate extensions activation to a new model described in RFC 155

### ISSUE THREAD

**Issue by twop** [sourcegraph/sourcegraph#10749]
See this WIP PR #10651 to overview API complexity
RFC: https://docs.google.com/document/d/1ikrUNVe3YVbR-JpegxhjrFdmRkTGzTLcOMkKHnOyjuE/edit#

```ts
type State {
     // ExtExtensions
     extensionDeactivate: Map<string, () => void | Promise<void>>
}

// Main -> Worker
 export interface FromMainThread {
     // ExtExtensions
     activateExtension: (extensionID: string, bundleURL: string) => Promise<void>
     deactivateExtension: (extensionID: string) => Promise<void>
 }
```

Challenges:
- Should we move activation logic to the worker too? We believe that the answer is yes but I don't have a good understanding yet what are the implications of doing this.
- it is probably going to be interconnected with settings area.
- how to test this? should we have any e2e/integrations tests as a part of this effort?

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by nicksnyder** [comment]
@felixfbecker please decide what to do with this
