### ISSUE TITLE
Infinitely processing malignant uploads

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#10755]
An upload file may be far too large for the current resources allocated to a worker. If a worker OOMs on a file and it resets, we should set a counter on that record so that we do not try to infinitely reprocess it on workers that will never actually process it successfully.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
