### ISSUE TITLE
Question mark button doesn't do anything on version context popup

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#10781]
This is on k8s.sgdev.org

![image](https://user-images.githubusercontent.com/5589410/82232099-f9d8fe80-98e2-11ea-9fed-4576b41e6e2a.png)

**Comment by rrhyne** [comment]
The issue is the ?help button should not display if the 'About version context' card is displayed. When the About card is hidden, the ? properly opens it again.
