### ISSUE TITLE
Trying to publish a failed changeset again is noop

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#10795]
- **Sourcegraph version:** master
- **Platform information:** macOS 10.15.4, Chrome 81

#### Steps to reproduce:

1. Have a draft campaign (publishing needs to fail to repro, try no privilege token or so)
2. Click publish on one single changeset
3. It should fail, check the error messages in the campaign status
4. Click publish on the changeset again
5. See the spinner indicate something would happen

#### Expected behavior:
6. It is tried again

#### Actual behavior:
7. It only spins, no actual retry attempt is made. This piece of code just returns when a job exists (even if failed) https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/campaigns/service.go#L428-431

**Comment by mrnugget** [comment]
@LawnGnome I assigned this one to you because it's part of your onboarding plan. But, as it says in the onboarding plan: that doesn't mean you're committed to finishing this.
