### ISSUE TITLE
Quotes hint with literal search on is off

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#10793]
- **Sourcegraph version:** master
- **Platform information:** k8s.sgdev.org

#### Steps to reproduce:

1. Go to https://k8s.sgdev.org/search?q=count:10+type:repo+after:%221+week+ago%22+asdf&patternType=literal
2. See no results, but the warning:

![image](https://user-images.githubusercontent.com/19534377/82270190-4a4c6c80-9974-11ea-9da8-2adc54453f09.png)

#### Expected behavior:
- It would not tell me I used quotes - because I didn't (did I? Just for the after filter)
- It would not suggest a query that is the original query with quotes added, although it tells it would _remove_ them
#### Actual behavior:
The opposite - or am I understanding this feature wrong?

**Comment by rvantonder** [comment]
This quotes suggestion logic is overall janky. It basically just looks for a quote if there are no results, and then throws this alert at you (it doesn't understand that quotes for params aren't part of a pattern, and we should only be throwing the alert if it is part of your pattern). I'm self-assigning to track it, but likely we can address this in a more principled way from scratch with the new query work.

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by rvantonder** [comment]
Original query correctly alerts that `after` can't be used without `type:commit`/`type:diff`. But the original issue still crops up with this query: [`count:10 type:commit after:"1 week ago" asdf`](https://k8s.sgdev.org/search?q=count:10+type:commit+after:%221+week+ago%22+asdf&patternType=literal)
