### ISSUE TITLE
Add the ability to disable Github projects if they've been archived on Github

### ISSUE THREAD

**Issue by voxxit** [sourcegraph/sourcegraph#108]
#### Describe the feature request.
In an effort to reduce/remove unnecessary projects from our Sourcegraph instance, it would be nice if we could remove them either automatically or with a bulk change tool if `{ "archived": true }` from the Github API.

#### Is your feature request related to a problem? Please describe.
Not presently, but if we can't remove repos soon, i feel there may be performance concerns.

#### Describe alternatives you've considered.
N/A

#### Additional context
N/A

**Comment by attfarhan** [comment]
Thanks for the feedback! We'll take a look into this and keep you updated here.

**Comment by attfarhan** [comment]
In the meantime, you can also enable/disable repos by using our [cli](https://github.com/sourcegraph/src-cli) (e.g. `src repos disable`) or hitting our [graphql API](https://about.sourcegraph.com/docs/features/api/#api-overview) directly.

**Comment by voxxit** [comment]
@attfarhan I didn't think of the CLI! Thanks. How can I ensure they stay disabled, while still allowing new repos to be cloned and enabled as they are created on our Github repo?

**Comment by attfarhan** [comment]
@voxxit under the `github` config option, if you set `initialRepositoryEnablement`  to `true`, new repos you add to GitHub will be auto-cloned and enabled, and any repos you disable will remain disabled. Docs: https://about.sourcegraph.com/docs/config/site/#initialrepositoryenablement-boolean

i.e. your config should look something like this: 
```
"github": [
    {
      "token": "your-token",
      "url": "https://github.com",
      "initialRepositoryEnablement": true
    }
  ]
```

**Comment by voxxit** [comment]
@attfarhan Thanks!

**Comment by nicksnyder** [comment]
And to clarify, regardless of how you configure `initialRepositoryEnablement` disabled repos will always stay disabled unless a site admin takes and explicit action to re-enable.

**Comment by keegancsmith** [comment]
@attfarhan you added support for finding archived repos in our search. Is there something to help this use case more directly now, or maybe a snippet using the src cli you can share?

**Comment by sqs** [comment]
We will try to address this problem (also related issues https://github.com/sourcegraph/sourcegraph/issues/383 https://github.com/sourcegraph/sourcegraph/issues/368) in the next month in the site admin UI or config.

**Comment by sqs** [comment]
We plan to address this pain with https://github.com/sourcegraph/sourcegraph/issues/914. I am closing this issue in favor of that one, because fixing that one will prevent Sourcegraph from getting into the bad state described in this issue.
