### ISSUE TITLE
Calculate true elapsed times when search alerts surface without results

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#10801]
The current fix causes the elapsed time to report effectively zero when we return alerts. This is better than "extremely-large-value" which results when nil-value of start time is taken is taken as the result (cf. https://github.com/sourcegraph/sourcegraph/issues/10701).

 To be accurate, we should calculate the elapsed time from the start of the request, but the current types and resolver structure make this tricky. See context in https://github.com/sourcegraph/sourcegraph/pull/10720#discussion_r426021614

**Comment by camdencheek** [comment]
I think this might no longer be an issue. At least since 7261b89246db73de0, every call to `resultsBatch()` adds the elapsed time to all `SearchResultResolver`s, even if they are just alerts

**Comment by rvantonder** [comment]
OK let's just close it, this seems stale anyway.
