### ISSUE TITLE
Sourcegraph graphQL invalid schema

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#10804]
#### Steps to reproduce:

1. Use the IntelliJ GraphQL plugin (or a sufficiently strict GraphQL schema parser)
2. Inspect schema

#### Expected behavior:
Valid Schema
#### Actual behavior:
Parser fails with: 
`graphql.schema.validation.InvalidSchemaException: invalid schema:
object type 'GitBlob' does not implement interface 'TreeEntry' because field 'isSingleChild' has a different number of arguments`

This appears to be a valid error: 

https://sourcegraph.com/github.com/sourcegraph/sourcegraph@40f4115a5025396eaec974c52dc52a4e254c8023/-/blob/cmd/frontend/graphqlbackend/schema.graphql#L2485:5&tab=references

https://sourcegraph.com/github.com/sourcegraph/sourcegraph@40f4115a5025396eaec974c52dc52a4e254c8023/-/blob/cmd/frontend/graphqlbackend/schema.graphql#L2692-2698

**Comment by slimsag** [comment]
cc @felixfbecker this may interest you?
