### ISSUE TITLE
TypeScript codeintel: WebSocket connection to 'ws://localhost:8080/' failed

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#1080]
- **Sourcegraph version:** latest master

#### Steps to reproduce:

Feel free to close if this isn't ready or isn't supposed to work yet

1. run enterprise dev server

2. run `docker run -p 80:8080 sourcegraph/lang-typescript` (from https://sourcegraph.com/extensions/felixfbecker/lang-typescript) and see:
```
dan$ docker run -p 80:8080 sourcegraph/lang-typescript
Using CACHE_DIR /tmp
WebSocket server listening on port 8080
Prometheus metrics on http://localhost:6060
```

3. update user settings:
```
{
  "extensions": {
    "felixfbecker/lang-typescript": true
  },
  "typescript.serverUrl": "ws://localhost:2088",
  "typescript.accessToken": "..."
}
```

4. visit .ts file, and see errors:

![image](https://user-images.githubusercontent.com/5589410/48806355-e4275080-ecce-11e8-8351-b7cdfce0b8eb.png)

**Comment by felixfbecker** [comment]
The settings are pointed to 2088 but the server is listening on 8080. Was 2088 mentioned in the docs?

**Comment by dadlerj** [comment]
Sorry, I had also tried with the old langserver image as well, but it doesn't work anymore. I get the same error when I point it at the correct port:

```
{
  "extensions": {
    "sourcegraph/basic-code-intel": true,
    "felixfbecker/lang-typescript": true
  },
  "basicCodeIntel.enabled": false,
  "typescript.serverUrl": "ws://localhost:8080",
  "typescript.accessToken": "..."
}
```

**Comment by felixfbecker** [comment]
The server logs say it's listening on port 8080, but you publish port `80` from Docker. It should be `-p 8080:8080`.

**Comment by dadlerj** [comment]
@felixfbecker will you update the readme for this then? https://sourcegraph.com/extensions/felixfbecker/lang-typescript

**Comment by felixfbecker** [comment]
Just did
