### ISSUE TITLE
Write an RFC on how to perform campaigns code host interactions with user accounts

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#10813]
RFC: [RFC 157 - Campaigns authorization model](https://docs.google.com/document/d/1-Ed6s3yiB-pmL7Up8H6nMlUhgmLn5BVu34Zpvf-_YNo/edit#heading=h.m2a6qvh96dy8)

**STATUS**: This ticket is not ready to be worked on. See open questions at the bottom.

#### Tasks

1. Collecting user tokens for code hosts
    - Either through authentication mechanism
    - Or user configuration
1. Use the token
    - when pushing a branch with the changes
    - creating a changeset
    - updating a changeset
    - closing a changeset
1. Validate that token has write access to repositories before attempting to push branch etc. so that error message is clearer
1. If no token is set:
    - Don't allow publishing campaign/changesets when no token is set
    - Show a warning when updating a campaign ("You cannot update this campaign since you have removed your token")

#### Questions

1. What does the user configuration look like?
1. How do we collect credentials through authentication mechanism?
    - Comment by @unknown in google doc:
        > We can make good use of `user_external_accounts` table. This is where we store all SSO metadata, including GitLab, GitHub OAuth tokens. However, we would have to make up one for Bitbucket Server (because it has no OAuth2 flow support).
1. Can these credentials be used to push/update branches (via `git`) AND open/update pull requests, or do we need two different credentials?
    - Comment by @unknwon in Google Doc:
        > As far as I know OAuth2 tokens are equally powerful as personal access token.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by eseliger** [comment]
Moving to 3.18.

**Comment by mrnugget** [comment]
@sourcegraph/campaigns We don't have a concept/design for how to do this, but I think we should definitely start working on this in 3.20

**Comment by LawnGnome** [comment]
This ticket is really now "write an RFC to perform code host interactions".

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by LawnGnome** [comment]
And [what an RFC it is](https://docs.google.com/document/d/1kDkIFQK9hiezEJrG5TfoGvsBKFKF6B6eUcKejYoX2XI/edit?usp=sharing).
