### ISSUE TITLE
Improve browser extension configuration experience for private instances

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#10814]
In the past, we didn't focus on the onboarding experience of the browser extension, as we wanted to focus on stability and reliability first.

We have now gotten to a point where the stability of code host integrations is good enough that we're considering:
- Pushing existing customers to activate the native integration
- [Improving in-app flows](https://github.com/sourcegraph/sourcegraph/issues/10225) so that new customers activate the native integration soon after adding repositories.
- [Surfacing the availability of the browser extension in a more persistent way](https://github.com/sourcegraph/sourcegraph/issues/10225)

For private instances, we should always favour native integrations, as they're the easiest way to make our code host integrations available to all users of an instance. However, when native integrations are not an option (for example for GitLab.com orgs, GitHub.com or GitHub Enterprise users), the activation flow of our browser extension for private instances is fairly error-prone:
- After installing the browser extension from our [docs page](https://docs.sourcegraph.com/integration/browser_extension), users will get no prompt of what they should configure.
- They'll need to discover from the docs, or by themselves, that they're expected to configure the Sourcegraph URL
- They will also need to grant permissions to the Sourcegraph URL:
![image](https://user-images.githubusercontent.com/1741180/82323502-6f72c680-99d8-11ea-86de-6904dbe84d79.png)
- Then they'll need to figure out that they need to grant permissions for their code host URL:
![image](https://user-images.githubusercontent.com/1741180/82323623-a052fb80-99d8-11ea-8852-acf7cbfd71ee.png)

All of this has to be discovered proactively, either by reading the docs, or by clicking the browser action when users realize something isn't working. As a result, it's not uncommon for users to miss one or more of these steps, and end up without code intelligence on their private code.

I believe there is the potential to do much better here, for instance:
- Allow the browser extension to be installed inline from customer instances (#10589), without having to go out-of-band to the docs, then to the Chrome web store.
- After installation, open the options page in a new tab (eg. chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/options.html), and:
    - Explain that the user should configure their Sourcegraph URL, and have them grant permissions right away.
    - Explain to the user that they should provide their code host URL(s), and also have them grant permissions right away.
- Maybe this could be streamlined further if there were a way to discover the Sourcegraph URL + code host URLs during inline install. The only step would be for the the user to grant permissions for these URLs (additional permissions will always have to be granted following an explicit user action, such as clicking a button).

Overall, I still think focusing on native integrations is the way to go for private instances. But if we decided to surface the browser extension in a more persistent way on private instances too, I think improving the configuration experience would have to be a prerequisite.

Cc @christinaforney @rrhyne, also @marekweb as you'd probably own this.

**Comment by felixfbecker** [comment]
Closing as implemented
