### ISSUE TITLE
CLA bot should periodically refetch org members to whitelist

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#10822]
CLA bot only fetches org members at startup. The causes new hires to have to whitelist themselves manually even though they shouldn't need to sign the CLA.

We should update CLA bot so that it fetches org members periodically (once an hour?) so new hires don't need to whitelist themselves.

**Comment by bobheadxi** [comment]
@eseliger https://github.com/sourcegraph/maintainerbot is the correct repo right? I can look at this :)

**Comment by nicksnyder** [comment]
@bobheadxi If you are going to work on this, please put it in the appropriate milestone (e.g. 3.17 and add the planned/3.17 tracking label)

**Comment by eseliger** [comment]
It’s in the bot implementation itself, passed from the outside :)

Init is here:
https://github.com/sourcegraph/infrastructure/blob/master/docker-images/sgbot/main.go#L98

And the check is performed here:
https://github.com/sourcegraph/infrastructure/blob/master/docker-images/sgbot/main.go#L125-L129

The init would need to be run periodically, and the maintainers array would need a mutex afaict.
