### ISSUE TITLE
Code intelligence integration tests

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#10832]
I have prototyped an integration test that was used to smoke test the behaviors between the TS and Go implementations of the precise code intel backends. This is not a very good tool to use as part of automated testing as it takes a long time to run and takes a good amount of manual setup.

We need to extend this tool so that it _could_ be ran in CI (easy to set up and efficient to run). Success criteria is that @uwedeportivo can run it as part of a release of 3.17+ to supplement or replace the old e2e code intelligence tests.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
