### ISSUE TITLE
Migrate all search query processing to new parser

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#10844]
The intent is to move away from all the `scanner.go` query processing code to the and/or-compatible parser code. This is largely a prerequisite to enable and/or queries globally without any special checks. Estimate is a thumbsuck.

Status update as of 06/17: I wanted this for 3.17 release but it didn't happen in time. I've migrated structural search, but not regexp and literal search yet. Onwards to 3.18!

This means:

- migrating literal search and other search tests
- removing the checks that gate the default #9836
- adding a lot of integration tests to check any regressions
- wish: fuzz against the `SearchImplementer` endpoint.

Migrating will enable/fix:

- A lot of search query errors documented in https://github.com/sourcegraph/sourcegraph/issues/8780
- and/or queries in literal search by default #9968
- Unified search input processing for webapp (also via #gqlsearch  #9979)
- additional user-configurable options https://github.com/sourcegraph/sourcegraph/issues/10429

Once migrated, I'll focus on extending support to other filters for hierarchical search #10623

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by rvantonder** [comment]
Implemented as an option in #12088. Will flick the switch after differential testing.
