### ISSUE TITLE
Display find-references inline on codehosts

### ISSUE THREAD

**Issue by gbrik** [sourcegraph/sourcegraph#10867]
on code hosts, viewing the references for a symbol (or search based definition candidates) requires jumping to Sourcegraph.com. we should provide this information inline by showing the relevant bottom panel on code hosts.

**Comment by felixfbecker** [comment]
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/3089?

**Comment by gbrik** [comment]
yup!
