### ISSUE TITLE
Run browser extension e2e tests before releasing

### ISSUE THREAD

**Issue by ijsnow** [sourcegraph/sourcegraph#1086]
Currently, the build step for e2e tests in the browser extension hangs indefinitely after all of them succeed. It seems like puppeteer is closing the browser properly but mocha won't exit even with the `--exit` flag. We need to figure out why this is happening and un-comment [these steps](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/dev/ci/gen-pipeline.go#L207-239)

**Comment by lguychard** [comment]
This is done now, see https://buildkite.com/sourcegraph/sourcegraph/builds/30218
