### ISSUE TITLE
Preload precise code intel data on the client

### ISSUE THREAD

**Issue by gbrik** [sourcegraph/sourcegraph#10869]
Currently, each code intel action sends a request to the server, which adds a delay to all code intel actions at best, and can make the feature extremely hard to use when network access is intermittent.

We should add a back-end endpoint which takes a file and range of lines, and returns all precise data available for those ranges, which will be cached by the code intel extensions. Those extensions will then answer queries via the cache whenever possible.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
