### ISSUE TITLE
Hovering a symbol should highlight visible references to that symbol

### ISSUE THREAD

**Issue by gbrik** [sourcegraph/sourcegraph#10868]
When hovering a symbol, we should perform a file scoped semantic find-references query, and highlight the results.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by felixfbecker** [comment]
Don't know if you've seen this but LSP even has an explicit feature to provide ranges in the document that should be _highlighted_ when a range is focused, with some interesting features to be able to distinguish read and write differences: https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_documentHighlight

It looks like it's not part of LSIF yet though, but sounds like something that could eventually be added or would be accepted in a PR. Then again simulating it through references and adding a filter by file to the API seems reasonable too

**Comment by efritz** [comment]
@felixfbecker Do you have any advice on how to approach this (assuming we can get the correct data in the extension)?

Not sure about (1) how to highlight ranges in the first place (I know we can't currently actually highlight by range but have to determine which spans intersect - is there any work to track this), and (2) trigger a highlight on hover (would this be a new provider type that the web side would handle?).

**Comment by felixfbecker** [comment]
I think we'd add an API for document highlights like VS Code has.

As for the implementation of that API, it would need to find the elements that most accurately represent the Range. E.g. find the start and end `span` and highlight everything in between those, inclusive of start and end. To find the start and end spans, you can use  [`getTokenElementAtPosition()`](https://sourcegraph.com/github.com/sourcegraph/codeintellify/-/blob/src/token_position.ts#L479:14). Then you just need to get all elements between the start and end element - e.g. by creating a DOM `Range` object with start and end pointing to the nodes, using `commonAncestorElement` to get the common ancestor, getting the index of start and end within its `children`, and calling `.slice(startIndex, endIndex)` on its `children`. Plus you need to handle the edge cases of the range being multi-line, in which case you'd need to select to the end/start of the line, and make sure to include all line wrapper elements of lines in between.

**Comment by efritz** [comment]
Is this all in the web code or does this live in codeintellify?

**Comment by felixfbecker** [comment]
I think this would all be in shared/, but you can use the functions exported by `codeintellify`.
