### ISSUE TITLE
New check CodeQL is taking a long time

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#10863]
In my PR at https://github.com/sourcegraph/sourcegraph/pull/10774, 2 of our new checks are slow:

- Code Scanning - Action / CodeQL-Build (push): 11min+ (https://github.com/sourcegraph/sourcegraph/pull/10774/checks?check_run_id=693134602)
- Code Inspector - Code Review: 11min+ - https://www.code-inspector.com/

Tagging @nicksnyder because I think he added CodeQL and @felixfbecker because I think he added Code Inspector.

I'm not blocked by these, but I wanted to mention it because some team members might feel that they are blocked.

**Comment by felixfbecker** [comment]
I really only wanted to try out the Code Inspector dashboard, I didn't know it also adds a status check. I looked if it can be disabled, but the app still tells me that the GitHub app was not approved yet in the org, and I don't have admin rights to do that.

**Comment by keegancsmith** [comment]
I just posted about Code Inspector in slack, didn't see this issue. Will continue discussion here. What I posted in slack: https://sourcegraph.slack.com/archives/C07KZF47K/p1589987798418700

"Code Inspector" CI check is slow. It seems to be really really slow. For example in #10864 it has been 20min and it is still in progress. A little annoying to have it signalling the CI is still running, when everything that is important is done. Is it worth keeping?

Oh, when I visit it it says

> Your project has too many lines of code! Upgrade your plan to increase your SLOC quota.

I'm thinking we just remove for now?

> I really only wanted to try out the Code Inspector dashboard, I didn't know it also adds a status check. I looked if it can be disabled, but the app still tells me that the GitHub app was not approved yet in the org, and I don't have admin rights to do that.

I have approved it for our org, specifically just for the sourcegraph/sourcegraph repo (I believe that is what was requested)

I'll see if I can disable CI check.

**Comment by felixfbecker** [comment]
I can configure it for a smaller repo to try it out. But I still don't seem to have any permissions to change anything, still says not configured 🤷

**Comment by keegancsmith** [comment]
> I really only wanted to try out the Code Inspector dashboard, I didn't know it also adds a status check.

FYI here is the dashboard: https://frontend.code-inspector.com/public/project/8273/sourcegraph/dashboard

> I can configure it for a smaller repo to try it out.

Go for it, for now I am removing from our main repo. The preferences for it allow us to ignore certain paths and disable some checks. But to experiment on our main repo we probably want a whitelist of paths.

> I'll see if I can disable CI check.

Can't work out how to disable it. I'm just gonna remove it.

**Comment by felixfbecker** [comment]
Sounds good

**Comment by felixfbecker** [comment]
![image](https://user-images.githubusercontent.com/10532611/82465091-29446280-9abf-11ea-8021-12f935c29b8f.png)
