### ISSUE TITLE
Constant stream of "Upserting BBS Webhook failed" errors

### ISSUE THREAD

**Issue by jjlin** [sourcegraph/sourcegraph#10876]
- **Sourcegraph version:** 3.16.0
- **Platform information:** Bitbucket Server 6.10.1, no server admin privileges

#### Steps to reproduce:

1. Upgrade to 3.16.0 on a Sourcegraph instance that indexes Bitbucket Server repos

#### Expected behavior:

No error messages, as with earlier versions.

#### Actual behavior:

Every minute, this message appears in the logs (some identifying info redacted as `{{ ... }}`):

    lvl=eror msg="Upserting BBS Webhook failed" err="deleting webhook: Bitbucket API HTTP error: code=405 url=\"{{bitbucket_server_url}}/rest/sourcegraph-admin/1.0/webhook?name=sourcegraph-{{uuid}}\" body=\"<!doctype html><html lang=\\\"en\\\"><head><title>HTTP Status 405 _ Method Not Allowed</title><style type=\\\"text/css\\\">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 405 _ Method Not Allowed</h1><hr class=\\\"line\\\" /><p><b>Type</b> Status Report</p><p><b>Description</b> The method received in the request-line is known by the origin server but not supported by the target resource.</p><hr class=\\\"line\\\" /></body></html>\""

It looks like this has something to do with tracking campaigns; I don't have any campaigns set up.

**Comment by mrnugget** [comment]
Thanks for filing this issue!

Just to be clear: you did not add the `"webhooks"` configuration to your Bitbucket Server configuration in Sourcegraph as described [here in the documentation](https://docs.sourcegraph.com/admin/external_service/bitbucket_server#webhooks)?

The current behavior is that if you do add the `"webhooks"` property, Sourcegraph will try to automatically setup a webhook on your Bitbucket Server instance. In this release we're adding a configuration that allows users to add the `"webhooks"` configuration, but disable the _automatic_ creation: https://github.com/sourcegraph/sourcegraph/issues/10217

**Comment by jjlin** [comment]
Nope, my Bitbucket config looks like this:
```
{
  "url": "{{url}}",
  "token": "{{token}}",
  "username": "{{username}}",
  "repositoryQuery": [
    "none"
  ],
  "repos": [
    // list of repos
  ]
}
```

**Comment by ryanslade** [comment]
We've decided that the feature to automatically configure webhooks in the background was not worth the complexity and confusion it added. 

To that end, we've decided to remove it. See: https://github.com/sourcegraph/sourcegraph/pull/10962

This change will be part of our 3.17 release

**Comment by jjlin** [comment]
Thanks for the update. Could you guys please lower the log level on this message in the next 3.16.x release, though? 3.17 is going to be a long wait with all this extra noise in the logs.

**Comment by ryanslade** [comment]
Sure, no problem
