### ISSUE TITLE
Hide 'Select context' placeholder label after first use

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#10877]
The Select context placeholder helps orient the user to the new feature, but it takes up valuable search bar real estate. 

Internal user feedback:
"I can't read my search query in most cases with my editor and sourcegraph open side-by-side.."
![Screen Shot 2020-05-20 at 11 04 30 AM](https://user-images.githubusercontent.com/539268/82481148-ba98e200-9a89-11ea-8a20-53df195f442c.png)

After the user has activated a context or closed the 'About version context' card, we should also hide the placeholder.

The label which displays a selected version context however, should still display.

**Comment by felixfbecker** [comment]
I think there's a Bootstrap helper class for this

**Comment by felixfbecker** [comment]
https://getbootstrap.com/docs/4.5/utilities/display/

e.g. you could give it `d-sm-none` or whatever breakpoint works well instead of `sm` and you can apply that only on the "Select context" element
