### ISSUE TITLE
Prevent admins from saving site config if it doesn't pass validation

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#10883]
A site admin clicked [`Add license key`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+%3Clicense+key%3E&patternType=literal), which inserted:

```json
"licenseKey": "<license key>"
```

They saved this, which worked fine, and then produces severe site config alerts everywhere.

It would be ideal if we prevented site config edits if they introduce validation problems.

@unknwon you've recently been working with the site config code, perhaps you'd be interested in this?

**Comment by unknwon** [comment]
> It would be ideal if we prevented site config edits if they introduce validation problems.

I think we thought about this, and I remember naively throwing hard errors for validation problems would prevent server from starting (if there is a validation problem for whatever reason) and the site admin has to fix the error by other means. But I have lost the context.

So for what we want here, we want to ignore the "save" from UI for site configuration if there is a validation problem, that's correct? And what is the reason we haven't done that?

**Comment by keegancsmith** [comment]
> So for what we want here, we want to ignore the "save" from UI for site configuration if there is a validation problem, that's correct? And what is the reason we haven't done that?

When we last discussed this I remember the ideal state we decided on was saving configuration we enforce validation, but for reading configuration we do not. I'm guessing we just didn't end up implementing that :P

**Comment by unknwon** [comment]
> > So for what we want here, we want to ignore the "save" from UI for site configuration if there is a validation problem, that's correct? And what is the reason we haven't done that?
> 
> When we last discussed this I remember the ideal state we decided on was saving configuration we enforce validation, but for reading configuration we do not. I'm guessing we just didn't end up implementing that :P

👍 Make senses, haha.

**Comment by bobheadxi** [comment]
Taking a peek at this and landed on https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/web/src/site-admin/SiteAdminConfigurationPage.tsx#L249:95, but it *seems* like any errors are raised correctly and do prevent saving the config

that said, on the resolver it doesn't seem like there's any validation code other than ensuring the content is JSON: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/site.go?utm_source=VSCode-1.1.0#L179

I'm thinking of adding a call to [`conf.ValidateSite`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/conf/validate.go?utm_source=VSCode-1.1.0#L172:6), would that be right function to use here?

**Comment by unknwon** [comment]
> I'm thinking of adding a call to [`conf.ValidateSite`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/conf/validate.go?utm_source=VSCode-1.1.0#L172:6), would that be right function to use here?

Can't say for sure without actually running the code, but from the docstring I would give it the first try.
