### ISSUE TITLE
Rare CI race condition sometimes breaks builds due to nodejs version

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#10881]
In https://buildkite.com/sourcegraph/sourcegraph/builds/64256#c9d134a0-887a-48eb-b01c-e405f264f468 for my PR https://github.com/sourcegraph/sourcegraph/pull/10880 that doesn't involve node, I got an `asdf`- or `node`-related error:

```

asdf: No preset version installed for command node
--
  | Please install the missing version by running one of the following:
  |  
  | asdf install nodejs 14.3.0
  |  
  | or add one of the following in your .tool-versions file:
  |  
  | nodejs 13.12.0
  | nodejs 14.2.0

```

**Comment by felixfbecker** [comment]
Had to revert the PR, but also seeing this in builds.
Assigning to you @ggilmore since I think you introduced `asdf`. It looks like `asdf` doesn't always pick up the `.nvmrc`

**Comment by felixfbecker** [comment]
I had to restart over 10 builds today because of this error (often the retry doesn't even fix it). @ggilmore how do we suggest we go about this? I think if `asdf` is buggy we should switch to `nvm` (but I have inherent preference, I just want the issue to be solved)

**Comment by felixfbecker** [comment]
I think I may have found the reason it happened for me in another repo

**Comment by slimsag** [comment]
`nvm` can't handle other tools, right? it doesn't sound ideal to me to use two different tools for this (one for node, one for others) unless we really can't fix this for some reason

It looks like the error message itself has been improved / fixed upstream and we just haven't updated the asdf version, how do we do that? https://github.com/asdf-vm/asdf/issues/662#issuecomment-594244237

It also looks like this may not be the fault of asdf itself but rather that `asdf install` is not being ran, perhaps this is just a CI race condition?

**Comment by slimsag** [comment]
Has anyone seen this since?

**Comment by pecigonzalo** [comment]
I believe this has been fixed by https://github.com/sourcegraph/sourcegraph/pull/15130
