### ISSUE TITLE
SiteFlags query returns an error for users 

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#10889]
#### Steps to reproduce:

1. Login to sourcegraph as a user (not site admin)
2. Open dev tools and observe an error in the console 

```
AggregateError: "must be site admin
must be site admin"
    createAggregateError errors.ts:46
    refreshSiteFlags backend.tsx:64
    _next tap.ts:120
    next Subscriber.ts:99
    notifyNext mergeMap.ts:168
```
This comes from this query 
https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/web/src/site/backend.tsx?utm_product_name=GoLand&utm_product_version=GoLand#L24:17-59:18

#### Expected behavior:

Portions of this query should work for users

#### Actual behavior:
The entire query fails

**Comment by daxmc99** [comment]
This issue was temporarily fixed in the backend but really should have a frontend fix to the query so that it doesn't request `needsRepostiryConfiguration` and `updateCheck` when the caller is not an admin. 

Reopening for tracking https://github.com/sourcegraph/sourcegraph/pull/10894#issuecomment-632329033

**Comment by daxmc99** [comment]
Sourcegraph should be refactored so that everywhere we do admin checks we return `errs` but these errors should be handled by the frontend, ie if part of query fails an admin check other parts of the query should still succeed.

https://github.com/sourcegraph/sourcegraph/pull/11113/commits/faf4b84fcc2d38b81bc8f6ba2d4b2ce710326221

**Comment by pdubroy** [comment]
Closing this — last update was over a year ago, so I'm assuming it's obsolete. Please feel free to re-open if I'm wrong.
