### ISSUE TITLE
Decompose and/or add more tests for CampaignDetails

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#10896]
When I have gone to make edits (for prototyping purposes) to [CampaignDetails.tsx](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@a540a1e3515403536ab0372db32828abb0f388b8/-/blob/web/src/enterprise/campaigns/detail/CampaignDetails.tsx), I am nervous because it is long/complex and lacks test coverage for actions (eg creation, editing, saving, etc.).

It would be nice if it were decomposed into more smaller and simpler components, and if there was more test coverage. Don't do this just on my account, but if you were already thinking of this, consider this a +1 for it.

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by mrnugget** [comment]
@eseliger Since I deleted large parts of `CampaignDetails`, should we close this? Or maybe it's better to keep this and check it off once we have more tests?

**Comment by eseliger** [comment]
Let's keep it, moved it over

**Comment by eseliger** [comment]
This component already got much smaller, I think it is at a maintainable point and will probably go away completely once we have the new workflow in place. Closing as I feel it's manageable now.
