### ISSUE TITLE
Feedback on marketing pages

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#10897]
My feedback on various pages on about.sourcegraph.com. Treat this feedback just like one person's opinion.

## Homepage

The homepage is very high level unless you actually watch the inline video, but I think that is too easy to scroll past (the thumbnail images doesn’t give me any information about what will be in the video or confidence that I will find it useful). I think if the thumbnail clearly showed that the video was a demo of our product it would be more effective (e.g., around second 4).

The gif on https://about.sourcegraph.com/product/code-discovery and the video thumbnail on https://about.sourcegraph.com/product/code-review would be more effective for me.

Do we have any data on how many homepage visitors start playing the video and how far they get through it?

## Universal code search

It feels weird to me that these pages are different:
- https://about.sourcegraph.com/universal-code-search
- https://about.sourcegraph.com/product

The click targets to the product page (purple) are not obvious, and it feels weird to me that UCS is both a top level target and nested under product.

![Screen Shot 2020-05-20 at 8 14 16 PM](https://user-images.githubusercontent.com/754768/82519503-b5ae4f80-9ad6-11ea-8850-63dbf80fd768.png)

## Code discovery

https://about.sourcegraph.com/product/code-discovery

LGTM!

## Code intelligence

https://about.sourcegraph.com/product/code-intelligence

- Better thumbnail on video and/or use animated GIF.
- Consider moving "Better code reviews with code intelligence" right below "Explore definitions & references, across all projects" and combining them (feels like there is duplicate content there).

## Code change management

https://about.sourcegraph.com/product/code-change-management

- Move "Leading dev teams invest heavily in code change management" below "Code change campaigns help teams move quickly and safely"
- Better thumbnail for video

## Code review

https://about.sourcegraph.com/product/code-review

LGTM!

**Comment by aileenrose** [comment]
no longer an issue
