### ISSUE TITLE
Add Repository / Update Repository actions unclear

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#10899]
- **Sourcegraph version:** 
3.16

- **Platform information:** 

MacOS, docker installed, latest chrome. 

#### Problem

When a user submits the form to add a new repository, the page is refreshed to display the same form with new header that reads ‘update’. No confirmation of success or failure is displayed and no note about the number of repositories added is displayed. The user is confused as to whether the action was successful. 

Additionally, when updating the repository setting, a green banner briefly displays under the form letting the user know the settings were updated.  It then disappears. If the user is not looking at the screen during the display time, they are unsure if the action was successful.

Both of these actions will result in changes to the repositories available in the user’s instance. Those repositories may take some time to clone and index, and therefore not be available to search immediately. This should also be conveyed to the user.

Lastly, a few users have tried to add forked repositories and were confused when they were not available to search. These repos should be labeled with a clear warning badge stating they are not indexed.

##### Video timeline
:05 - Add cost host form has Add Repository header.
:17 - User summits form, header is below scroll, form changes to 'update' code host, user is unsure if the action was successful
:26 - User hits hits update, sees flash message

The flow demonstrated above was observed several times in the installation study videos represented here:
[installation UX study](https://docs.google.com/document/d/1vx4veLKDM5p3VSzxIVnCKkt2fTHmwusfHYabCWWmbUU/edit#)

#### Expected behavior:

User is notified their addition or update of a repository was successful.
User and can view the status of each repository being added from the cost host.

#### Actual behavior:

The user is not notified of these actions or the pending state of the repositories, so they are unsure if they have been added properly and are available to search.

This video illustrates the issue and the page that would clearly show repository status to the user: [see video example](https://drive.google.com/open?id=106C9itxHIAvv_96ev81dME8WggTRIQmY)

This youtube video displays a user’s confusion as they navigate this issue:
https://youtu.be/1oJjfgK5Go8?t=399

#### Solution

* Redirect the user to the repository status page upon submission of both the create and update actions. 
* Display a green success banner at the top of the repository status page with the text:

>  Adding repositories. It may take a few moments to clone and index each repository. Repository statuses are displayed below.

  The banner should not be removed until the next page is loaded. 

* Sort repositories by update date descending so that the recently added or updated repos are visible to the user
* Move the 'cloning' status to the right side of the table/row
* Add a clear status message if a repository is not searchable due to being forked or other issue
* Link users to '/site-admin/external-services/new' from the "Almost there" accordion under "Add repositories" and the corresponding item under the Getting started dropdown. 

Figma compositions and prototype (click play in the top right):

https://www.figma.com/file/V67mcLX9OyR0Ru1KTssP3y/Add-Repositories?node-id=3%3A19&viewport=-1598%2C928%2C0.5

#### Benefit
Additional users will successfully connect a repository.

**Comment by felixfbecker** [comment]
@rrhyne I just merged Loic's 2 PRs above. Is this sufficiently addressed by them?

**Comment by rrhyne** [comment]
@felixfbecker I am not seeing the links that should be present from changes made in  #11784, even though my local env. has the commit. It may be that I am not restarting my dev environment correctly. Are you seeing those links?

**Comment by rrhyne** [comment]
I am seeing changes from #11782, 'Clarify add/update repository actions', though so this is a bit confusing.

**Comment by rrhyne** [comment]
@lguychard the links for 'add repository' do not seem to be displaying properly.

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by rrhyne** [comment]
@lguychard just pinging you to see if we can have a look at those links. Can you add a screenshot to show where the links are displayed? I cannot find them in my instance.

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by rrhyne** [comment]
I believe this bug may also be related to these changes:

https://github.com/sourcegraph/sourcegraph/issues/12985
