### ISSUE TITLE
Wrong API for github enterprise

### ISSUE THREAD

**Issue by cncook001** [sourcegraph/sourcegraph#109]
#### Steps to reproduce:

1. Install docker image 2.9.3
2. Click `Configuration`, then click `Add GitHub Enterprise`
Paste your token and git url as requested

#### Expected: 

Search to work

#### Actual:
14:21:54   repo-updater | t=2018-07-16T14:21:54+0000 lvl=eror msg="Error listing viewer's affiliated GitHub repositories" endCursor=<nil> error="invalid character '<' looking for beginning of value"
14:22:55   repo-updater | t=2018-07-16T14:22:55+0000 lvl=eror msg="Error listing public repositories" sinceRepoID=0 error="unexpected response from GitHub API (`https://github.<enterprisename>.com/<org>/<repo>/v3/repositories`): HTTP error status 406"

**Comment by nicksnyder** [comment]
Can you share the url (with any sensitive information replaced with `xxx`) and what GitHub enterprise version you are using?

You config should look something like this
```json
"github": [
    {
      "url": "http://github.example.com",
      "token": "xxx"
    }
  ],
```

And you should be able to see a JSON response if you paste this URL into your browser (replace example.com with your enterprise domain):
http://github.example.com/api/v3/repositories?access_token=xxx

**Comment by francisschmaltz** [comment]
I believe this issue was resolved by, if not before, commit 
https://github.com/sourcegraph/sourcegraph/commit/d3ca5fee72e9bdb8bccc528b276ed112ec53938e. @cncook001 If this is still an issue please reach back out.
