### ISSUE TITLE
No way to scroll search scopes/filters with a mouse

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#10910]
Reported by https://app.hubspot.com/contacts/2762526/company/693777200

A user reported they were unable to scroll repo filters and search scopes. Since we lack any visual indicator that the row is scrollable, or any buttons to scroll left and right, this only works if a user has a trackpad, or a mouse that has provides a scroll device that supports left-right scrolling.

**Comment by rrhyne** [comment]
Thanks @dadlerj. Do you have a priority/timeline in mind here?

**Comment by dadlerj** [comment]
Not urgent — but I imagine a quick/small improvement. I do feel like I have heard this from others before, but I can't find existing issues. The web team may have more context on this...

**Comment by slimsag** [comment]
FYI: In most OSs with a mouse you can scroll horizontally using shift + scroll wheel.

Not intuitive, I 100% agree, but it does work.

**Comment by dadlerj** [comment]
I've heard this several more times since filing this (including @christinelovett if I recall correctly!). Anecdotally, given this seems like it has a simple fix, I'd raise priority a bit.

**Comment by AlicjaSuska** [comment]
@rrhyne will you be taking care of this issue? (there is no designer assigned so far)

**Comment by christinelovett** [comment]
Fix requested by https://app.hubspot.com/contacts/2762526/company/464956351

**Comment by AlicjaSuska** [comment]
I'll be taking care of this issue from now on. @dadlerj it is added to 'to triage' - when does the design need to be ready?

**Comment by rrhyne** [comment]
Alicia, you’ll need to work with Loic to prioritize the issue on the search
team’s roadmap.

**Comment by dadlerj** [comment]
I feel like we could just put some spin buttons on the far right side of the bar (if it overflows) and that would be sufficient? I'm sure there's a nicer design you will be able to come up with :) but that was what I was referring to when I said it should have a "simple" fix above. Agreed that search is the right team to own this though!

**Comment by AlicjaSuska** [comment]
I've prepared a solution for filters not fitting in one line on search results pages. I would like to add a simple carousel that can be used to reveal the filters that are cut off now. All the details are added to [Figma](https://www.figma.com/file/Aa5qBTB9bLLEj5LElk6zGJ/Scroll-filters-and-repositories-14128?node-id=246%3A11)

As search scopes are no longer visible on the home page, I've skipped this part in the designs. 

<img width="661" alt="scroll" src="https://user-images.githubusercontent.com/20326070/103463139-74e40d80-4d2a-11eb-92c6-ef63c800693a.png">

@lguychard - as per our call before Christmas
@rrhyne could you please take a look and review the designs as well? Thank you!

**Comment by lguychard** [comment]
Thanks @AlicjaSuska! Designs LGTM.

**Comment by rrhyne** [comment]
Designs look great, I made one comment on the proposed interactivity and have laid out a proposal that addresses the comment.
