### ISSUE TITLE
Connection between bundle manager and worker is flaky

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#10913]
A customer has recently showed us that with LSIF uploads between 1-2G on a k8s deployment will see failures 50% of the time from the worker due to a connection reset when trying to fetch the raw upload data.

We need to investigate the connection between these two services to determine whether it's a timeout issue or something else. It may be necessary to split the payload into smaller chunks as we do for uploads.

**Comment by efritz** [comment]
Update: this behavior is currently visible in dotcom as well:

```
│ t=2020-05-21T20:19:43+0000 lvl=warn msg="Failed to process upload" id=59150 err="bundleManager.GetUpload: read tcp 10.52.12.36:56904->10.55.243.135:3187: read: connection reset by peer"         │
```

**Comment by efritz** [comment]
This is no longer an issue on dot-com.

**Comment by slimsag** [comment]
much more context in this thread: https://sourcegraph.slack.com/archives/CHXHX7XAS/p1590092732193100
