### ISSUE TITLE
Create a "code intelligence status" tooltip

### ISSUE THREAD

**Issue by shrouxm** [sourcegraph/sourcegraph#10926]
It should look like the [Code-intel-popup-branding frame](https://www.figma.com/file/QOCGTlcc8ZF5EqMl1jwfsk/Code-Intel-UI?node-id=37%3A126) on this Figma design (which is WIP).

It should show statuses for: index queued, index processing, index processing failed. Essentially, it should expose the 'state' column of the 'lsif_uploads' table when it is not 'completed'.

It should be on by default, but permanently dismissable via user-setting. The queued/processing and processing failed states should be dismissable separately.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by jjinnii** [comment]
@macraig Could we add more information about what this issue is trying to solve for and user feedback, if we have any? It's hard to discern what this issue is about, as it outlines just the solution.

**Comment by macraig** [comment]
@jjinnii can we close this one given we implemented the code intel badge?

**Comment by jjinnii** [comment]
@macraig  Yup I think so! The RFC you linked in the earlier comment covers much much more than the code intel badge, but I think this issue is specific to user problems we've tackled with the badge.
