### ISSUE TITLE
Create a "code intelligence source" tooltip

### ISSUE THREAD

**Issue by gbrik** [sourcegraph/sourcegraph#10925]
It should look like the [Code-intel-popup-branding frame](https://www.figma.com/file/QOCGTlcc8ZF5EqMl1jwfsk/Code-Intel-UI?node-id=37%3A126) on this Figma design (which is WIP).

It should be on by default, but permanently dismissable via user-setting.

**Comment by lguychard** [comment]
Rough implementation sketch:
- Extend [`HoverProvider`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@a054f46fd90a300bf09a49029af7bd63338fa88e/-/blob/packages/sourcegraph-extension-api/src/sourcegraph.d.ts#L1084-1086) in the extension API to be able to return the contents of the "code intelligence source" tooltip along with hover content, probably as an optional "alert", with contents, maybe an alert class (info, warning, error...) and a CTA.
- You'll have to handle this new content in [`fromHoverMerged()`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@a054f46/-/blob/shared/src/api/client/types/hover.ts#L12-34)
- Handle displaying this hover alert in `<HoverOverlay/>`, similarly to how we display [badges](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@a054f46/-/blob/shared/src/hover/HoverOverlay.tsx#L206-219). Add relevant tests to `HoverOverlay.test.tsx`
- Make sure the alert displays gracefully on all code hosts (GitHub, GitLab, Bitbucket Server, Phabricator). It may be necessary to style it using code host-specific classes. See as an example how we use [`infoAlertClassName`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24%40fc90be9+infoAlertClassName&patternType=literal).

Overall, this is not dissimilar to the work @efritz did to show [badge indicators](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/75e4cb28b99e2d17aa901a2be2ca7ca8ffa463b1).

**Comment by felixfbecker** [comment]
I have _some_ concerns with the design that I [just shared in Figma](https://www.figma.com/file/QOCGTlcc8ZF5EqMl1jwfsk?node-id=37:126#29572443).
Just wanted to mention here that depending on how you want to address those, the implementation may not even require an extension of the API. That shouldn't be the deciding factor though, just wanted to mention that here on the implementation notes.

What I would recommend is to start in the [`HoverOverlay` storybook](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/shared/src/hover/HoverOverlay.story.tsx), just implementing the UI first with static data, not touching the extension API at all. This should uncover any problems like interaction with the close button, multiple scrolling hover content, ...
Once the UI is implemented in `HoverOverlay` and has a storybook story, I'd go to extend the API (if needed at all).

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by efritz** [comment]
@gbrik Can you push your work so far up to a branch for visibility? If you're making good progress on the cpp indexer I can help with these UI/UX issues.

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
