### ISSUE TITLE
Create a 'stale code intelligence' tooltip 

### ISSUE THREAD

**Issue by shrouxm** [sourcegraph/sourcegraph#10927]
It should look like the [Code-intel-popup-branding frame](https://www.figma.com/file/QOCGTlcc8ZF5EqMl1jwfsk/Code-Intel-UI?node-id=37%3A126) on this Figma design (which is WIP).

It should be on by default, but permanently dismissable via user-setting.

It should appear when indexing activity occurred previously on the repository, but we're now serving search-based results again because it is too old to be used. It should not be shown if an index is queued or processing (#10926).

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by scalabilitysolved** [comment]
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/10926.
