### ISSUE TITLE
"How to create and publish your own Sourcegraph extension" link 404s

### ISSUE THREAD

**Issue by ijsnow** [sourcegraph/sourcegraph#1092]
The "How to create and publish your own Sourcegraph extension" link on [this page](https://docs.sourcegraph.com/extensions#authoring) is a 404.

**Comment by ryan-blunden** [comment]
Fixed with https://github.com/sourcegraph/sourcegraph/commit/b3e6585e87a8562496000abbd5d0fbbf132adaee
