### ISSUE TITLE
Error accessing gitlab.com repo

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#10930]
- Go to https://gitlab.com/sourcegraph/codeintellify/-/blob/master/src/hoverifier.ts
- See no code intel, error in console: 

`Could not resolve file info for code view Error: RepoLookup for {Repo:gitlab.com/sourcegraph/codeintellify} failed with http status 500: syncer.syncsubset.store.upsert-repos: insert: pq: could not serialize access due to concurrent update`

**Comment by eseliger** [comment]
Just tried and don't get that error, but hovers still won't work 🤔

**Comment by felixfbecker** [comment]
Interesting. Do you get a view on Sourcegraph button? Do you see the request with a successful response in devtools?

**Comment by eseliger** [comment]
successful response to resolve rev, and a 404 from codecov (expected)
and yes the button is there

**Comment by felixfbecker** [comment]
Confirmed
