### ISSUE TITLE
reduce k8s upgrade merge conflicts: RFC 141: Go investigation

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#10943]
Similar to:

- https://github.com/sourcegraph/sourcegraph/issues/10936
- https://github.com/sourcegraph/sourcegraph/issues/10937

I think it makes sense for us to consider something like what sourcegraph-server-gen was in the past, but in the form of:

> `src k8s config.yaml` -> generates `deploy-sourcegraph/base` but with modifications

I'm not saying we need to do this in 3.17, currently, just that I think considering this alongside Cue and Dhall makes sense. Thoughts @ggilmore?

**Comment by ggilmore** [comment]
@slimsag I think this is a valid alternative for us to explore. I won't have time in 3.17 to look into this however (unless we have some a-priori evidence that Cue or Dhall won't meet our needs)

**Comment by ggilmore** [comment]
This might also take longer than the three day estimate since we'd developing this system from scratch

**Comment by slimsag** [comment]
From what I understand we no longer plan on investigating this route, closing.
