### ISSUE TITLE
support $CUSTOMER

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#10942]
Time-tracking issue for https://github.com/sourcegraph/customer/issues/57

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by slimsag** [comment]
Closing in favor of https://github.com/sourcegraph/customer/issues/57
