### ISSUE TITLE
Backend: New campaign flow

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#10985]
Docs/Schema in PR #10921

**STATUS**: WIP pull request is https://github.com/sourcegraph/sourcegraph/pull/11675 and the tasks below as a WIP until we've done 3.19 planning.

#### Conceptual/Docs/GraphQL Schema

The PR in which these higher-level changes should be proposed/made/discussed is https://github.com/sourcegraph/sourcegraph/pull/10921

- [x] Schema for tracking existing changesets in `campaign-spec.yml`

#### Implementation Backend

The list below is _not complete_, but a rough overview of what has been done and needs to be done:

- [x] Pull in the GraphQL schema from https://github.com/sourcegraph/sourcegraph/pull/10921 as a skeleton (with only "TODOs" as implementation)
- [x] Remove GraphQL resolvers and majority of `campaigns.Service` methods that were only used in old workflow (I decided to keep the type definitions and database tables for `Patch`/`PatchSet`/`ChangesetJob` around, even though I anticipate that we will need to remove them)
- [x] Add `campaign_specs` & `changeset_specs` database tables, Go type definitions and methods in `campaigns.Store`
- [x] Add `CampaignSpecByID` query and `CampaignSpec` resolver (some methods still have TODOs)
- [x] Add `ChangesetSpecByID` query and `ChangesetSpec` resolver (some methods still have TODOs)
- [x] Implement `createChangesetSpec` mutation
- [x] Implement `createCampaignSpec` mutation
- [x] Implement `applyCampaignSpec` 
- [x] Implement `moveCampaign` mutation
- [x] Update the GraphQL API to reflect newest state in #10921
- [x] Move fields from `CampaignSpec.Spec` to `ChangesetSpec.Description` after newest updates to #10921 
- [x] Validate `CampaignSpec` in `(*Service).CreateCampaignSpec` (depends on schema, see above)
- [x] Validate `ChangesetSpec` in `(*Service).CreateChangesetSpec` (depends on schema, see above)
- [x] Allow `on:` (unquoted!) in YAML definition of `CampaignSpec`
- [x] Expire `{Campaign,Changeset}Specs`
  - [x] Return proper value in `{Campaign,Changeset} Spec.ExpiresAt`
- [x] Implement `ChangesetSpec`/`CampaignSpec` resolvers so that `CampaignSpec.PreviewURL` works
- [x] In `createCampaignSpec` check the user has access to the namespace it's creating the spec for.
- [x] In `moveCampaign` check the user has access to the new namespace.
- [x] Implement `Changeset.Status` API
  - [x] Add new `state` field to `Changeset`
  - [x] Create "pending"/"unpublished" changesets when applying a `CampaignSpec`
    - [x] Add internal `state` field to `changesets`
    - [x] Add `changeset_spec_id` to `changesets`
  - [x] ... many more things I have in a separate list
- [x] Implement the `Reconciler` that picks up unreconciled campaigns and creates the desired state
- [x] Implement tracking/importing of manual changesets

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by mrnugget** [comment]
I'm closing this after merging https://github.com/sourcegraph/sourcegraph/pull/12435. What's left to do in the backend has been extracted into separate tickets:

- Implement the changesetsConnectionStatsResolver #12642
- Implement the "processing?" checks in CloseCampaign/DeleteCampaign #12643
- Move CloseOpenChangesets to the reconciler #12644
- Move SyncChangesets to the background #12645
- Implement missing methods in changesetResolver #12646
- Change testChangesetResponse in permissions_test.go to include publication status, error and reconciler state #12647
- Replace commented-out portion of TestCampaigns in resolvers/resolver_test.go with more extensive test that tests ApplyCampaign #12648
- Check that retrying of changeset create/update works correctly in reconciler #12700
