### ISSUE TITLE
No Git file history for binary files

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#10999]
Requested by https://app.hubspot.com/contacts/2762526/company/578600789

Sourcegraph doesn't render binary files (https://github.com/sourcegraph/sourcegraph/issues/8387), but apparently it also isn't able to show Git history:

![image](https://user-images.githubusercontent.com/5589410/82936540-96cf1380-9f43-11ea-9430-c8d54fe9184c.png)

Related:

* https://github.com/sourcegraph/sourcegraph/issues/10998
* https://github.com/sourcegraph/sourcegraph/issues/8387

Not urgent, but if a quick fix, would be a nice customer win!

**Comment by tsenart** [comment]
@keegancsmith: Before I dive in, any clue where the root cause may be?

**Comment by keegancsmith** [comment]
No idea. Maybe our parsing of git log fails with binary files? Not sure why it would care about contents of files for log (except for detecting renames, but even then I don't see why log would change).

That would be my best guess. In fact @eseliger is adding support for binary files in our diff parser [1]. This may be a hint towards the issue.

[1]: https://github.com/sourcegraph/go-diff/pull/46

**Comment by tsenart** [comment]
@eseliger: Could you perhaps take a brief look at this as part of #10998? cc @mrnugget

**Comment by eseliger** [comment]
The cause is that the request fails with an error, because highlighting doesn't work. I think the proper fix is making `highlight` nullable in graphql and in the frontend don't fail if it's only that error. Want me to do a fix here or will someone else take it?

**Comment by eseliger** [comment]
Fix is here: https://github.com/sourcegraph/sourcegraph/pull/11034
