### ISSUE TITLE
Links to discussions from "Explore" page 404

### ISSUE THREAD

**Issue by ijsnow** [sourcegraph/sourcegraph#1100]
- **Sourcegraph version:** sourcegraph.com
- **Platform information:** Any browser, any system

#### Steps to reproduce:

1. Go to https://sourcegraph.com/explore
2. Scroll down to recent discussions and click one of them

#### Expected behavior:

Taken to the (file|repo|etc) and see the discussion

#### Actual behavior:

See "Repository not found".

Looks like the link href has some formating problem because the link goes to: https://sourcegraph.com/https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/xlang-go/internal/server/integration_test.go#tab=discussions&threadID=137

**Comment by sqs** [comment]
Fix is to use RouterLinkOrAnchor here, or just a href. It’s confusing because it works if you cmd-click (I think). I’ll fix this since I introduced it.

**Comment by slimsag** [comment]
Why is that explore page using a different component for displaying discussions...?

On the explore page:

![image](https://user-images.githubusercontent.com/3173176/48871964-38503480-eda4-11e8-9555-66884d2db422.png)

On the https://sourcegraph.com/discussions page:

![image](https://user-images.githubusercontent.com/3173176/48871977-4e5df500-eda4-11e8-862a-ee6cdbc89486.png)

I see that it matches the repositories list better, but it's kind of ugly in comparison and likely the cause of issues like this inherently. We could just reuse the same component and hide the filter + show more button?

**Comment by sqs** [comment]
^ @francisschmaltz can respond to that. He is aware of the need to unify the look.

**Comment by francisschmaltz** [comment]
@slimsag @sqs these should look the same. I’ll mock up a unified look this week. 
https://github.com/sourcegraph/sourcegraph/issues/1122
