### ISSUE TITLE
Provide a preview tab for HTML/CSS code

### ISSUE THREAD

**Issue by kaushikvapiwala** [sourcegraph/sourcegraph#1102]
#### Feature request description

It is easy to view the HTML page and edit it if there is an option provided to preview the changes.

#### Is your feature request related to a problem? If so, please describe.

It is quite frustrating to change tabs and preview code on other websites and update the repo or preview code on a local machine.

**Comment by sqs** [comment]
Would solving #49 solve your problem?

**Comment by kaushikvapiwala** [comment]
I be

> Would solving #49 solve your problem?

I believe that would do the job.

**Comment by sqs** [comment]
Great. Closing as duplicate of #49
