### ISSUE TITLE
Improve privacy messaging before requesting addition of repository

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#11044]
Sourcegraph version:3.16
Platform information:MacOS, docker installed, latest chrome.'

#### Steps to reproduce:

Begin the process of adding a cost host at /site-admin/external-services/new.

Note there is no message to users about how Sourcegraph protects a user's repositories. 

#### Expected behavior:

Users are properly informed of the actions the software will take on their repositories.

#### Actual behavior:

New users to the platform do not yet trust Sourcegraph with their data, therefore, some users are reluctant to add a code host to their configuration. 

#### Potential solution
Inform the user what the software will do with the access provided. Suggested copy:

>How this install accesses your code host:
> • Clones the repositories you specify to create a local cache
> • Periodically pulls cloned repositories to ensure search results are current
> • Collects usage metrics such as number of users, user activity and number of searched repositories 
>     • We collect this data to ensure usage does not exceed free software requirements
> 
>This installation will not:
> • Send your code, queries, or other personal data to any online service. Your code and information are private.
> 

The message should be dismiss-able.

See the screenshot:

![Privacy message](https://user-images.githubusercontent.com/539268/83072368-80988480-a023-11ea-9c64-923c6e7b0cc9.png)

**Comment by dadlerj** [comment]
My suggested changes to copy. The copy on top is focused on code host-specific privacy, rather than covering everything. I don't think this is the right place to get into details around [pings](https://docs.sourcegraph.com/admin/pings), which aren't specifically related to code host additions.

I also added a few more bullets. The core team should review to ensure this reflects reality (and we can cut these down if they're too long)!

>This Sourcegraph installation will never send your code, repository names, file names, or any other specific code data to Sourcegraph.com or any other destination. Your code is kept private on this installation. 
>
>This Sourcegraph installation will access your code host by:
>• Periodically fetching a list of repositories to ensure new, removed, and renamed repositories are accessible on Sourcegraph
>• Cloning the repositories you specify to create a local cache
>• Periodically pulling cloned repositories to ensure search results are current
>• Fetching [user repository access permissions](https://docs.sourcegraph.com/admin/repo/permissions), if you have enabled this feature
>• Sending pull requests as part of [code change campaigns](https://docs.sourcegraph.com/user/campaigns), if you have enabled this feature

**Comment by lguychard** [comment]
@sourcegraph/core-services could one of you review the accuracy of Dan's suggested copy above?

**Comment by keegancsmith** [comment]
LGTM.

> • Sending pull requests as part of code change campaigns, if you have enabled this feature

Technically we will then also periodically sync the PRs we created. But this wording should be sufficient. cc @ryanslade

**Comment by ryanslade** [comment]
> • Sending pull requests as part of [code change campaigns](https://docs.sourcegraph.com/user/campaigns), if you have enabled this feature

We could update it to make it a little more accurate:

• Opening pull requests and syncing their metadata as part of [code change campaigns](https://docs.sourcegraph.com/user/campaigns), if you have enabled this feature

**Comment by dadlerj** [comment]
Thanks @keegancsmith and @ryanslade ! And @rrhyne of course feel free to edit my wording, those are just suggestions.

**Comment by rrhyne** [comment]
@dadlerj looks great, thanks!

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
