### ISSUE TITLE
Add 'activity histogram' to admin usage stats + rearrange

### ISSUE THREAD

**Issue by ebrodymoore** [sourcegraph/sourcegraph#11063]
### Part 2 to RFC 145
[Figma](https://www.figma.com/file/B8c4C4FwQaigNw5QTOcgov/Admin-Panel?node-id=0%3A1) mockup

For context: [discussion on how to implement RFC 145 and who should own it](https://sourcegraph.slack.com/archives/CHPC7UX16/p1588726286311500)

Prioritization: this would be nice to have in 3.17 but not critical at all. We'll want to keep adding more insights for the admins over the next few releases.

**Comment by ebrodymoore** [comment]
@tsenart only assigning you because you were gracious enough to do part 1 and you may have the best view on who should do part 2 😄

**Comment by tsenart** [comment]
@ebrodymoore: The frontend skills required for this go beyond what I have unfortunately. I think someone from the web team would have to part own this. I can certainly take care of the backend bit. @lguychard thoughts?

**Comment by ebrodymoore** [comment]
[Web team conversation going on here](https://sourcegraph.slack.com/archives/CMT39K56Z/p1590751468160400). Let's hold off and involve this in 3.18 planning. We'll want to add more graphs soon so let's just wait and do it all at once

**Comment by ebrodymoore** [comment]
Updates are reflected in [Figma](https://www.figma.com/file/B8c4C4FwQaigNw5QTOcgov/Admin-Panel?node-id=0%3A1) and a [doc for the queries](https://docs.google.com/document/d/10eqBqXd2fBhSDmaFzfp4cjJ0p1zzJNxGFfPItrKBqw0/edit). I'm getting a final review on this because we've added more since this issue was opened. @lguychard @tsenart do you know who/when this will be worked on in 3.18?

**Comment by lguychard** [comment]
@tsenart I proposed GraphQL schema changes for this in https://github.com/sourcegraph/sourcegraph/pull/11850

Let's agree on the schema, then I'll do on the frontend part of this against stub data this week.

**Comment by lguychard** [comment]
@ebrodymoore backlogging this.

**Comment by pdubroy** [comment]
Closing this — last update was almost a year ago, so I'm assuming it's obsolete. Please feel free to re-open if I'm wrong.
