### ISSUE TITLE
Request: Link to Godocs

### ISSUE THREAD

**Issue by prestonvanloon** [sourcegraph/sourcegraph#111]
#### Describe the feature request.
When looking at a particular go source file, I would like a link to the godoc page for this package.
Some packages are spread across many files and the godoc is often helpful to understand how the whole package should be used. 

#### Is your feature request related to a problem? Please describe.
Nope

#### Describe alternatives you've considered.
I copy and paste the repository name to https://godocs.org/$REPO, but this is not as nice as a button click

#### Additional context
I'm happy to help add this feature, if anyone can point me in the right direction.

**Comment by sqs** [comment]
Thanks! :+1: 

Soon we will have an extension API for Sourcegraph (that lets you write an extension once and then use it on Sourcegraph, GitHub, your editor, etc.). One extension we plan to seed the platform with is a godoc extension that adds a godoc button for the current file's package and also next to each import path in the `import (...)` statement. I will post back here with updates.

**Comment by nicksnyder** [comment]
We have an extension API now so it should be possible to build an extension that adds a button like this. Check out the docs: https://github.com/sourcegraph/sourcegraph-extension-api

**Comment by prestonvanloon** [comment]
@nicksnyder Any idea how to add a button? There is very little documentation on that API and I can't figure out how to add an `ActionItem` or if that is even what I need to add.

**Comment by prestonvanloon** [comment]
I made a start on this: https://github.com/prestonvanloon/sourcegraph-godocs

I have a few issues:
- The iconURL doesn't seem to do anything. I thought it would put the svg next to the button label text?
- There is no way to issue updates to the context when navigating through directories. Right? Is this possible?
- There is no way to determine what type of project this is. i.e. Is there any API to let me see all of the file names in a given directory? My specific use case is that I only want to show my action item when go files are present in a directory or when we are looking at a specific go file.

**Comment by ryan-blunden** [comment]
@prestonvanloon, your extension is really cool. I'm working on documentation for this today and will come back to you once it's pushed as I'd love to get your feedback.

**Comment by prestonvanloon** [comment]
@sqs, Thanks for all of the responses. I'll be sure to track those issues. Am I right in my assumption that the icon appears next to the button label text?

@ryan-blunden Thanks a lot! I really struggled with package.json properties. I only discovered that this is how to configure things by looking at the codecov example. None of the tutorials mention it! The most mysterious thing so far is: What is `resource` in the codecov package.json? 

Thanks all!

**Comment by ryan-blunden** [comment]
I've sent you a PR to fix the button icon.

The Codecov example is a particularly complex one and yes I agree, the package.json has a lot going on. You'll see plenty of docs added to the sourcegraph/sourcegraph-extension-api this week and I'll post back here once they start coming through, beginning tomorrow.

I believe the `resource` in the Codecov package.json refers to the name of the file. Is that right @sqs?

**Comment by ryan-blunden** [comment]
Hi @prestonvanloon, is there anything else I can help you with in the meantime?

**Comment by prestonvanloon** [comment]
Hey Ryan, thanks so much for the PR and sorry for the delay here. I've just returned from vacation. 

The icon is working nicely now, but I'm still blocked by https://github.com/sourcegraph/sourcegraph-extension-api/issues/83

Thanks!!!

**Comment by sqs** [comment]
@prestonvanloon Got it, we will bump that up. Hope to add that next week or earlier. You are not the only one blocked on it!
