### ISSUE TITLE
Basic code intel hover/go to definition on PR even though LSIF checks passed and LSIF is enabled

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#11103]
![image](https://user-images.githubusercontent.com/10532611/83250347-45738e00-a1a8-11ea-829d-4ab7f3edb7de.png)

in https://github.com/sourcegraph/sourcegraph/pull/10779/files#diff-ef7108e038222546caed42d762faa0d9R101
and
https://sourcegraph.com/github.com/sourcegraph/sourcegraph@fb430d8fb79f7c64302317583f61037ab89490fd/-/blob/browser/src/shared/components/CodeViewToolbar.tsx#L101:83&tab=def
I get a (wrong) basic code intel hover. But all LSIF checks passed on the PR and LSIF is enabled in my settings. Other properties in the exact same line show LSIF hovers for me:

![image](https://user-images.githubusercontent.com/10532611/83250477-7653c300-a1a8-11ea-852f-3a95f8474dde.png)

**Issue/question A**: How can it be that that property gives a basic code intel hover? Is there some kind of fallback logic, because the parent property is `any`? If so, can I disable it? Because basic code intel is almost always wrong for TS.

**Issue B**: It seems like the LSIF indexer has the type of the prop as `any`, even though it seems it can resolve the type fine

![2020-05-29 12 35 22](https://user-images.githubusercontent.com/10532611/83250833-02fe8100-a1a9-11ea-8435-4bf890737a7d.gif)

**Comment by efritz** [comment]
We've added (and are [still adding](https://github.com/sourcegraph/code-intel-extensions/pull/432)) badges and tooltips to show the source of code intel, which should clarify this particular circumstance. Check passing may still mean that the processing failed to transient error.

**Comment by felixfbecker** [comment]
@efritz isn't the issue of `fileInfoOrError` being `any` still a bug that needs to be fixed?

Would also be interested in an answer to question A above (whether there could be a setting to disable the fallback).
