### ISSUE TITLE
Bitbucket Server native integration prevents file header text from wrapping

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#11110]
Reported by https://app.hubspot.com/contacts/2762526/company/407948923

See https://sourcegraph.slack.com/archives/CMT39K56Z/p1590772969161600 for details

**Comment by marekweb** [comment]
Looks like the issue might be with `display: flex` from this CSS: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@mz/firefox-inline-extensions/-/blob/browser/src/shared/code-hosts/bitbucket/style.scss?utm_source=VSCode-1.1.0#L47:9

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
