### ISSUE TITLE
tracking-issue bot not reliable

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#11122]
I've seen many instances where the tracking issue updating will not work: It will update time estimates and other things in the tracking issue, but the actual owner assignment changes are not picked up.

The first instance of this I reported over Slack here: https://sourcegraph.slack.com/archives/C07KZF47K/p1590188960450200

**Comment by slimsag** [comment]
We saw this happen again on Wed. 27th where the tracking issue showed it was updated just minutes ago, but the issue titles were not updated in the tracking issue to reflect what was shown on GitHub.

**Comment by slimsag** [comment]
I've just now seen it again: 10641 shows assignment to `@davejrt` and `@slimsag`:

![image](https://user-images.githubusercontent.com/3173176/83313257-4e755700-a1ca-11ea-95ea-1d387adc05b7.png)

But I have not been assigned for 7 days:

![image](https://user-images.githubusercontent.com/3173176/83313422-f7bc4d00-a1ca-11ea-97b4-4cb552cd480b.png)

And @bobheadxi` was assigned two hours ago:

![image](https://user-images.githubusercontent.com/3173176/83313447-0acf1d00-a1cb-11ea-89ac-4be9c2c329e4.png)

But it is not shown: 

![image](https://user-images.githubusercontent.com/3173176/83313463-1d495680-a1cb-11ea-9d5f-dcb498789064.png)

**Comment by tsenart** [comment]
@gbrik: Do you have an idea of where this bug may lie?

**Comment by bobheadxi** [comment]
I see a lot of inconsistencies with how multiple assignees are handled - e.g. https://github.com/sourcegraph/sourcegraph/issues/10641 doesn't show up under my name in https://github.com/sourcegraph/sourcegraph/issues/10788

**Comment by tsenart** [comment]
I don't understand what that bug is. We don't support multiple assignees because having multiple owners of an issue is a planning anti pattern, so only the first one is picked.

**Comment by gbrik** [comment]
I'll look into what I think might be the bug I introduced today (basically, a problem with parsing issues), but I think it's a wrong suspicion because it would happen every time not sometimes.

**Comment by slimsag** [comment]
> We don't support multiple assignees because having multiple owners of an issue is a planning anti pattern, so only the first one is picked.

Good to know, I didn't see this mentioned anywhere in the handbook docs, let's add a note for this there. I'll make sure we stop doing this + 'stretch' tasks on distribution.

**Comment by slimsag** [comment]
Update: It's like it is using some form of cached information about issue ownership? Now that I have removed all multiple-assignee issues, ones like #10641 show up under all previous assignees instead of just the current assignee.

Issue was updated by the bot after I updated the assignees:

![image](https://user-images.githubusercontent.com/3173176/83694807-adaddf80-a5ad-11ea-89bd-71f056b08479.png)

#10641 is assigned only to @bobheadxi :

![image](https://user-images.githubusercontent.com/3173176/83694846-c74f2700-a5ad-11ea-88f4-9d9b7e9f8085.png)

Tracking issue shows that issue assigned to @bobheadxi @davejrt and @slimsag :

![image](https://user-images.githubusercontent.com/3173176/83694892-e057d800-a5ad-11ea-9bbd-ca6bb5bcf889.png)

**Comment by slimsag** [comment]
FYI: It doesn't appear to be just sometimes, I think it is consistent behavior

**Comment by tsenart** [comment]
Built and pushed a new Docker image, so this should be fixed.
