### ISSUE TITLE
Sign-in broken on sourcegraph.com

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#1112]
1. Go to https://sourcegraph.com/search
2. Click "Sign in" and sign in
3. Redirects back to https://sourcegraph.com/search, but you're not signed in

**Comment by nicksnyder** [comment]
Works for me, although I am seeing this
![image](https://user-images.githubusercontent.com/754768/48921297-c0d9de00-ee53-11e8-9af9-6a5af59c052c.png)

**Comment by sqs** [comment]
I removed the `extension/Link` component that tried to communicate with the Chrome extension. That appears to be causing what you are seeing. Not sure why it would be showing up after I removed it though. I’ll check into it later tonight.

**Comment by nicksnyder** [comment]
@sqs I am still seeing the weird sidebar on sourcegraph.com

**Comment by sqs** [comment]
Hmm, I can't repro the weird sidebar (or the sign-in issue).

@nicksnyder 	I am using Firefox with the latest Firefox browser ext installed. I signed in and visited https://sourcegraph.com/search (and various other pages). Can you help me repro? Are you using the addons.mozilla.org-published version of the extension, by chance?

**Comment by sqs** [comment]
I repro'd the iframe and filed https://github.com/sourcegraph/sourcegraph/issues/1118 separately.

@beyang 	Can you repro the sign-in issue?

**Comment by beyang** [comment]
Weird, I can no longer repro now.
