### ISSUE TITLE
Add SQL search-based code intelligence

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#11132]
Requested by https://app.hubspot.com/contacts/2762526/company/1686989427

My summary from Slack:

>They have a lot of SQL code (mostly in .sql files, though some is embedded — I warned them that the former would be possible, but the latter would be harder). They’d love to see where a column is referenced in other SQL files, where a stored proc is used/defined, table names, etc.

And @efritz replied:

>I’d have to check ctag support for SQL

**Comment by dadlerj** [comment]
Looks like PL/SQL is supported: http://ctags.sourceforge.net/languages.html!

What's the process for adding these?

**Comment by efritz** [comment]
I will write a guide on adding language support for symbols-based code intel.

**Comment by aidaeology** [comment]
Update: adding request from Criteo for SQL code intel support as well.

**Comment by dadlerj** [comment]
@aidaeology just FYI I deleted the customer name as well as this history that included the customer name. Please use links to HubSpot (/company/ pages) when posting in our public issue tracker!

**Comment by macraig** [comment]
Guide to add languages to search-based was documented in [https://docs.sourcegraph.com/dev/how-to/add_support_for_a_language](https://docs.sourcegraph.com/dev/how-to/add_support_for_a_language).
