### ISSUE TITLE
Codecov "Coverage: %" not showing up for private repo

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1116]
@felker reported an issue with the [Codecov extension](https://github.com/sourcegraph/sourcegraph-codecov):

> I am able to get the "Inline code coverage" in a private repository after adding the Codecov API token, but the "Coverage: %" button never appears, unlike for public repositories. Is this normal?

https://twitter.com/kgfelker/status/1066369579893645313

**Comment by felker** [comment]
👋 
I just started using the Sourcegraph extension today. When I initially created the Codecov API token and added it to the extension by following https://github.com/sourcegraph/sourcegraph-codecov/blob/master/README.md, it worked right away with highlighting the GitHub source code as red/yellow/green:
<img width="798" alt="screen shot 2018-11-24 at 11 26 51 am" src="https://user-images.githubusercontent.com/1410981/48971185-088b7180-efdc-11e8-9bf2-b886c83b5e0c.png">
and the command palette gave a link the repository dashboard on Codecov, and summarized the recent coverage report and percentage. But, the "Coverage %" button was missing:
<img width="798" alt="screen shot 2018-11-24 at 11 27 10 am" src="https://user-images.githubusercontent.com/1410981/48971187-0de8bc00-efdc-11e8-9ac9-13aa78e20976.png">

And now, the behavior of the extension (at least on Chrome) is inconsistent. I will revisit the same file, and usually the API token is missing from the command palette, or I am unable to highlight the statement coverage, etc.

**Comment by sqs** [comment]
Thanks for posting more info. We have a number of fixes that should land by Monday. I’m pretty sure they will completely address the issues you’re seeing, but we’ll confirm.

**Comment by felker** [comment]
Did these fixes get pushed? The source code highlighting seems more consistent, but the button is still missing.

**Comment by felker** [comment]
- The button was missing even when coverage data was displayed
- I never noticed that "Show coverage %" option, but I am unable to check for it now, since:

And now, even worse, all of the Codecov related options have disappeared from the command palette...

Google Chrome Version 71.0.3578.80 (Official Build) (64-bit)
Sourcegraph extension 18.12.8.13

![image](https://user-images.githubusercontent.com/1410981/49823494-d012c400-fd4d-11e8-9ca4-1ac8e80a39a5.png)

**Comment by lguychard** [comment]
@felker if all codecov actions disappeared from the command palette, it looks like your codecov extension might be deactivated. Can you verify that it's activated in your settings (on sourcegraph.com, or on your private Sourcegraph instance if you use one)?

**Comment by felker** [comment]
Do you know if the Codecov +Sourcegraph instructions [here](https://github.com/codecov/sourcegraph-codecov) are still up-to-date? I didn't have a Souregraph account because I didn't think it was required for the Codecov functionality, and it worked without one until ~6 days ago. I've made one now, but haven't configured anything.

Now, viewing the example public repository file from those instructions exhibits the same issues with the browser extension for me:
https://github.com/theupdateframework/notary/blob/fb795b0bc868746ed2efa2cd7109346bc7ddf0a4/server/storage/tuf_store.go

**Comment by sqs** [comment]
Sorry, I will go update those docs. We made it so you need to enable the extension explicitly to use it (which currently requires you to have an account). We attempted to identify everyone who used it previously and enable it for them, but obviously the migration did not work in your case. Will investigate.

Anyway, @lguychard can continue troubleshooting the issue now that you have an account and enabled the extension.

**Comment by felker** [comment]
How do you enable it in the Sourcegraph account?

**Comment by lguychard** [comment]
Awesome!

No, you shouldn't enable the Codecov WIP extension.

Would you mind posting a screenshot of all codecov actions available to you from the command palette when browsing a private code view?

![image](https://user-images.githubusercontent.com/1741180/50222108-85212e00-0397-11e9-80ed-b8c04ab93008.png)

**Comment by felker** [comment]
Done. 

![screen shot 2018-12-19 at 11 28 45 am](https://user-images.githubusercontent.com/1410981/50233440-7596ea80-0381-11e9-871c-dc0ae35375b8.png)

**Comment by nicksnyder** [comment]
@lguychard what is the status of this issue?

If this is release blocking for 3.0, please add the release blocking label.

Otherwise, if this isn't going to get done in the next week, please remove it from the 3.0 milestone.

**Comment by lguychard** [comment]
Fixed by https://github.com/codecov/sourcegraph-codecov/pull/20

**Comment by Rush** [comment]
Sorry if this is a wrong ticket but I'm trying to configure codecov + sourcegraph on a private repo. The extension is working on the public source but not on my private one. I don't seem know where to add the Codecov token as the command palette is just not there:

![](https://rush.sh/6l5r9JNp+LWnScqAWudFNYVKWAQ/screenshot.png)

**Comment by sqs** [comment]
@Rush I filed the issue at https://github.com/sourcegraph/sourcegraph/issues/3281. It seems fixed but not yet released, and the fix should be released soon.

You can work around the problem right now by going to https://sourcegraph.com and signing in, and using the command palette there. If you are signed into Sourcegraph.com and your Sourcegraph browser extension's options URL is https://sourcegraph.com, it will use settings from Sourcegraph.com.
