### ISSUE TITLE
Inline blame shows up with no way to disable on GitHub if enabled on Sourcegraph

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1117]
Because the button to toggle inline blame is hidden on GitHub, there is no way to disable it if you had it enabled previously on Sourcegraph:

![screenshot from 2018-11-25 02-23-56](https://user-images.githubusercontent.com/1976/48977948-2a770980-f059-11e8-9451-16ae2e91fdc5.png)

**Comment by nicksnyder** [comment]
won't fix
