### ISSUE TITLE
Draft of marketing page for code insights

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#11181]
https://sourcegraph.slack.com/archives/C0C324C91/p1589481645150500

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by felixfbecker** [comment]
Closing this for now
