### ISSUE TITLE
Add support for code structure graph and code folding

### ISSUE THREAD

**Issue by Kimi-Arthur** [sourcegraph/sourcegraph#112]
#### Describe the feature request.
In-file structure is also very important besides the current feature set like symbol search and file search. To make that better, providing code structure/in-file symbol list would be very helpful.

Code folding is also helpful to make the code cleaner (but can be somewhat replaced by the code structure feature).

#### Is your feature request related to a problem? Please describe.
When reading a long source code file, especially an API or implementation, which typically contains many methods. It would be hard to get the whole picture of that file.

Also files like the central js/html file also contains many named/unnamed methods/functions, which are hard to read too.

#### Describe alternatives you've considered.
Either of the two suggestions in the first section would be great, but the code structure one is more preferred.

**Comment by sqs** [comment]
Thanks!

- In-file symbol outline view is a planned feature. Do you like how VS Code does it? https://code.visualstudio.com/updates/v1_25#_outline-view
- Code folding: this is the first external request we've gotten for this. Noted, and we hope that an improved and hierarchical symbol outline view will address the pain here.

**Comment by Kimi-Arthur** [comment]
Looks good! Thanks!

**Comment by sqs** [comment]
The symbol list is now scoped to the current file: #2877. We do not have any plans to work on code folding, so I am going to close this issue to keep our issue tracker representative of priorities. Please reply back if this is an especially important feature for you.
