### ISSUE TITLE
resources report: feedback

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#11207]
This is my feedback on the resources reporting bot; I'll defer to you to decide which of these sound like feedback you'd like to follow up on

Treat this as any other user's feedback and weigh the pros/cons of addressing each, this is not me saying you should fix all of these (especially if doing so would involve lots of work 😛)

Overall it solves my use case of finding unexpected resources pretty well and I'm very happy to continue trying it out over the coming weeks and narrow down my feedback to more critical things.

---

In the #distribution channel I saw this:

![image](https://user-images.githubusercontent.com/3173176/83443313-61706d00-a3fe-11ea-89f7-ce6bf45b7a4c.png)
![image](https://user-images.githubusercontent.com/3173176/83443329-659c8a80-a3fe-11ea-8921-0796bf8ccdb6.png)

It's Monday now and I'd like to review those to see if any unexpected resources show up. On another day, I might also prefer to do it a few days (or maybe even a week) later.

However, since it overwrites the `GeneratedReport` sheet in the Google Sheet, I'm not able to view these reports historically. For now, I am using the Google Sheets historical view to get this info but it'd be nice if the `Report` Slack button could work historically somehow (e.g. maybe by linking to a different sheet instead of replacing the old one). It also means I can't comment on the cells to tag other people (e.g. to ask questions about resources they created), which would be nice.

---

On `EC2::Volumes::gp2` entries, they sometimes don't have any tags:

![image](https://user-images.githubusercontent.com/3173176/83443980-84e7e780-a3ff-11ea-96c7-93c2bf9637f5.png)

This is obviously because we did a bad job and didn't tag them, but I wonder if there is any way we can get more info about who might've created that resource? For instances I see an owner ID but for volumes there doesn't appear to be one:

![image](https://user-images.githubusercontent.com/3173176/83445696-4acc1500-a402-11ea-847e-c7ff691bff9a.png)

---

AWS owners appear to indicate the entire Sourcegraph AWS team, not an individual user:

![image](https://user-images.githubusercontent.com/3173176/83445863-a0082680-a402-11ea-9933-cab5cc93da47.png)

![image](https://user-images.githubusercontent.com/3173176/83445884-a5fe0780-a402-11ea-9d87-6ac9abea0295.png)

I'm not sure if we can get more info than this, but if not it'd perhaps be useful to `-` that field to avoid confusion about the field being useful in the case of AWS.

--- 

It's hard to tell if resources were terminated or not. The best way I found of doing this in the case of EC2 is going to https://us-west-2.console.aws.amazon.com/cloudtrail/home?region=us-west-2#/events?ReadOnly=false and searching for the ID (e.g. i-0575189c678335dbc)

If there is a better way we can highlight resources that got deleted/terminated, that would be nice as it would mean I wouldn't need to go searching through Cloudtrail to see if it was shut down.

One option here might be to link to the resource (more on this below) so I could quickly see if it's still there. Of course, that info being in the sheet itself would be nicer if possible.

---

It would be nice if it could do a best-effort linking of common resources. In specific if it could try to link the following IDs to these pages:

- `aws` AND `us-west-2*` AND `i-0575189c678335dbc` -> https://us-west-2.console.aws.amazon.com/ec2/v2/home?region=us-west-2#Instances:search=i-0575189c678335dbc;sort=instanceId
- `aws` AND `us-west-1*` AND `vol-0f040e5129fd8669a` -> https://us-west-1.console.aws.amazon.com/ec2/v2/home?region=us-west-1#Instances:search=vol-023b2f1aec06d77d2;sort=instanceId

I confirmed the above searches work at least for volume and instance types. I think it would be OK to link there for any `EC2::Foobar` ID, effectively, though. Just handling linking to these five regions would be good enough:

![image](https://user-images.githubusercontent.com/3173176/83445518-f9bc2100-a401-11ea-8c54-ebb519be3d40.png)

If GCP has something similar, that would be nice, but it'd be OK to also just handle this for AWS for now.

This would allow me to more quickly find more details on a resource, or to see if the resource is gone (i.e. deleted already), which would make reviewing these reports much less tedious.

---

It'd be nice to be able to whitelist `gke-ci-*` IDs so they do not show up in the report at all. Our CI system spins up/down resources as needed, so this will always be noisy and not something we care about (expected resources). I think I saw you're already looking into this?

---

Extended timeframe?

Would it be easily possible to include all resources created in the past 7d (with each daily report, on the same schedule as now), but have a row on the left which indicates `1d`, `2d`, `3d`, `4d`, `5d`, `6d`, `7d`? I notice you do something similar for 48h/24h right now, so maybe it wouldn't be too hard?

If that was the case, I would have less of a need to go back and view each individual report and instead could rely on the report covering the last week.

**Comment by slimsag** [comment]
Once you've had a chance to read, go ahead and close this issue :) You can file others for specific things I brought up here, if you like, or just make changes as you see fit.

**Comment by bobheadxi** [comment]
Thanks for the detailed feedback @slimsag ! Here's my take on things potential followups:

### Better history

I think this depends on how important the following is:

> It also means I can't comment on the cells to tag other people (e.g. to ask questions about resources they created), which would be nice.

because I think it would essentially necessitate creating a new report (sheet page) for each run (which isn't bad), and maybe automatically deleting everything older than the last `n` pages.

### Identifying owners

I took another look and unfortunately I don't think there appears to be a way to get a better owner out of these... I'll remove the owner ID that actually represents teams though

Is the user arn screenshot just an example of a user ARN or something in the instance properties? I took a look and couldn't find something anything that granular :(

### Finding resources

Generate some best-effort links, as described - https://github.com/sourcegraph/sourcegraph/issues/11208

**Comment by slimsag** [comment]
> Is the user arn screenshot just an example of a user ARN or something in the instance properties? I took a look and couldn't find something anything that granular :(

The screenshot came from an IAM page on AWS, looking at instance properties I see the owner is identical to what you have above. BUT I do see the SSH keypair name appears to be a part of the instance properties and that is often named after the person who created it:

![image](https://user-images.githubusercontent.com/3173176/83692316-9b7d7280-a5a8-11ea-9c32-d234cec1d8c4.png)

Maybe it's possible to use that?

I found that info here: https://us-west-1.console.aws.amazon.com/ec2/home?region=us-west-1#Instances:sort=instanceId

**Comment by slimsag** [comment]
Thanks for responding to my feedback! I'll close this now :)

**Comment by bobheadxi** [comment]
Unfortunately I think that name is set by the user and could be anything, but might be a good starting point - I'll see if I can add it to `meta` to start with, and see how that goes.
