### ISSUE TITLE
Link to resources in Distribution resource reports

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#11208]
from https://github.com/sourcegraph/sourcegraph/issues/11207:

> It would be nice if it could do a best-effort linking of common resources. In specific if it could try to link the following IDs to these pages:
>    aws AND us-west-2* AND i-0575189c678335dbc -> https://us-west-2.console.aws.amazon.com/ec2/v2/home?region=us-west-2#Instances:search=i-0575189c678335dbc;sort=instanceId
>    aws AND us-west-1* AND vol-0f040e5129fd8669a -> https://us-west-1.console.aws.amazon.com/ec2/v2/home?region=us-west-1#Instances:search=vol-023b2f1aec06d77d2;sort=instanceId

**Comment by slimsag** [comment]
This is low priority generally, moving to backlog for now.
