### ISSUE TITLE
errors seen in indexed-search on bigdata cluster with 250k repos

### ISSUE THREAD

**Issue by uwedeportivo** [sourcegraph/sourcegraph#11200]
- **3.16 or master insiders** 
- **k8s GKE** 

these are error messages seen in the indexed-search pods on the pilot bigdata cluster
this cluster has 250k repos in about 1k+ orgs

this one shows up sporadically (13 times), not often:
```
2020/05/28 19:09:50 watcher error: fsnotify queue overflow
```

this type showed up many times
```
2020/05/31 21:44:43 error indexing ghe.sgdev.org/awesome-dubinsky-308/achintp-Leetcode_solutions@HEAD=7f4e5f9670108b934491bc82cb488cb9d373c398: GET http://sourcegraph-frontend-internal/.internal/search/configuration giving up after 5 attempts
```
maybe making frontend more responsive by giving it more mem helped with it

also seen is this type
```
ERR: 2020/06/01 10:44:35 main.go:237: archive/tar: invalid tar header
2020/06/01 10:45:31 error indexing ghe.sgdev.org/agitated-bouman-446/CloudMaster-Manoj-AC@HEAD=cfcc4223d2dfaa1516f1181880d689b2b5b2becc: command [zoekt-archive-index -name ghe.sgdev.org/agitated-bouman-446/CloudMaster-Manoj-AC -commit cfcc4223d2dfaa1516f1181880d689b2b5b2becc -incremental -branch HEAD -download-limit-mbps 1000 -file_limit 1048576 -parallelism 8 -index /data/index -require_ctags http://sourcegraph-frontend-internal/.internal/git/ghe.sgdev.org/agitated-bouman-446/CloudMaster-Manoj-AC/tar/cfcc4223d2dfaa1516f1181880d689b2b5b2becc] failed: exit status 1
OUT: 
```

this might be bum git repos (there are some in our collection of 111 million repos). worth checking here that the bum repos are not poison pills that prevent indexing of other repos (i don't think so, but worth double-checking).

there's also
```
er ERR: 2020/06/01 19:06:31 main.go:237: archive/tar: invalid tar header                                ││ zoekt-indexserver 2020/06/01 19:07:31 error indexing ghe.sgdev.org/agitated-bouman-446/CloudMaster-Manoj-AC@HEAD=cfcc4 ││ zoekt-indexserver OUT:                                                                                                 ││ zoekt-indexserver ERR: 2020/06/01 19:07:31 main.go:237: archive/tar: invalid tar header 

````

worth taking a look just to make sure.
many thanks :-)

**Comment by keegancsmith** [comment]
> this one shows up sporadically (13 times), not often:
> 
> ```
> 2020/05/28 19:09:50 watcher error: fsnotify queue overflow
> ```

This is benign. zoekt-webserver watches the directory with the index files. If anything changes it rescans the whole directory. So missing some events due to a full queue is benign. I'll update zoekt to skip logging this error as well as improve how it handles backlogged queues. From what I can tell we may lead in to situations where we are constantly scanning potentially affecting search performance.

> ```
> 2020/05/31 21:44:43 error indexing ghe.sgdev.org/awesome-dubinsky-308/achintp-Leetcode_solutions@HEAD=7f4e5f9670108b934491bc82cb488cb9d373c398: GET http://sourcegraph-frontend-internal/.internal/search/configuration giving up after 5 attempts
> ```
> 
> maybe making frontend more responsive by giving it more mem helped with it

Yes this would be an issue with frontend. We don't do concurrent requests against this endpoint. The endpoint only speaks to conf (so no external requests). This points to frontend being overloaded or networking issues.

> ```
> ERR: 2020/06/01 10:44:35 main.go:237: archive/tar: invalid tar header
> 2020/06/01 10:45:31 error indexing ghe.sgdev.org/agitated-bouman-446/CloudMaster-Manoj-AC@HEAD=cfcc4223d2dfaa1516f1181880d689b2b5b2becc: command [zoekt-archive-index -name ghe.sgdev.org/agitated-bouman-446/CloudMaster-Manoj-AC -commit cfcc4223d2dfaa1516f1181880d689b2b5b2becc -incremental -branch HEAD -download-limit-mbps 1000 -file_limit 1048576 -parallelism 8 -index /data/index -require_ctags http://sourcegraph-frontend-internal/.internal/git/ghe.sgdev.org/agitated-bouman-446/CloudMaster-Manoj-AC/tar/cfcc4223d2dfaa1516f1181880d689b2b5b2becc] failed: exit status 1
> OUT: 
> ```
> 
> this might be bum git repos (there are some in our collection of 111 million repos). worth checking here that the bum repos are not poison pills that prevent indexing of other repos (i don't think so, but worth double-checking).

Yeah it won't be a poison pill. We do need smarter behaviour around bad repos though to avoid constantly attempting them. Thanks for pointing this out though, I'll see what is up with this repo.

> ```
> er ERR: 2020/06/01 19:06:31 main.go:237: archive/tar: invalid tar header                                ││ zoekt-indexserver 2020/06/01 19:07:31 error indexing ghe.sgdev.org/agitated-bouman-446/CloudMaster-Manoj-AC@HEAD=cfcc4 ││ zoekt-indexserver OUT:                                                                                                 ││ zoekt-indexserver ERR: 2020/06/01 19:07:31 main.go:237: archive/tar: invalid tar header 
> ```

Yup will investigate this repo as well.

**Comment by keegancsmith** [comment]
> > this one shows up sporadically (13 times), not often:
> > ```
> > 2020/05/28 19:09:50 watcher error: fsnotify queue overflow
> > ```
> 
> This is benign. zoekt-webserver watches the directory with the index files. If anything changes it rescans the whole directory. So missing some events due to a full queue is benign. I'll update zoekt to skip logging this error as well as improve how it handles backlogged queues. From what I can tell we may lead in to situations where we are constantly scanning potentially affecting search performance.

Submitted zoekt fixes for this upstream:
- [Change 269795](https://gerrit-review.googlesource.com/c/zoekt/+/269795): shards: consolidate events before calling scan
- [Change 269796](https://gerrit-review.googlesource.com/c/zoekt/+/269796): shards: ignore fsnotify.ErrEventOverflow

**Comment by keegancsmith** [comment]
While looking at the cluster I did notice indexed-search-8 OOMing. This does look like a poison pill:

```
    Last State:    Terminated
      Reason:      OOMKilled
      Message:     ex/ghe.sgdev.org%2Finfallible-tereshkova-128%2Fjulianromera-jsdelivr_v16.00013.zoekt: 3358458 index bytes (overhead 3.0)
2020/06/01 17:18:11 main.go:237: read tcp 10.20.0.28:45418->10.20.2.25:3178: read: bad address
2020/06/01 17:21:26 error indexing ghe.sgdev.org/infallible-tereshkova-128/julianromera-jsdelivr@HEAD=741f20b92fd7bfa32e77c0fa483a3fc69cf62910: command [zoekt-archive-index -name ghe.sgdev.org/infallible-tereshkova-128/julianromera-jsdelivr -commit 741f20b92fd7bfa32e77c0fa483a3fc69cf62910 -incremental -branch HEAD -download-limit-mbps 1000 -file_limit 1048576 -parallelism 8 -index /data/index -require_ctags http://sourcegraph-frontend-internal/.internal/git/ghe.sgdev.org/infallible-tereshkova-128/julianromera-jsdelivr/tar/741f20b92fd7bfa32e77c0fa483a3fc69cf62910] failed: signal: killed
OUT: 
ERR: 2020/06/01 17:18:28 builder.go:620: finished /data/index/ghe.sgdev.org%2Finfallible-tereshkova-128%2Fjulianromera-jsdelivr_v16.00003.zoekt: 1104569 index bytes (overhead 3.0)
2020/06/01 17:18:30 builder.go:620: finished /data/index/ghe.sgdev.org%2Finfallible-tereshkova-128%2Fjulianromera-jsdelivr_v16.00004.zoekt: 1284092 index bytes (overhead 3.0)
2020/06/01 17:18:30 builder.go:620: finished /data/index/ghe.sgdev.org%2Finfallible-tereshkova-128%2Fjulianromera-jsdelivr_v16.00005.zoekt: 957177 index bytes (overhead 3.0)
2020/06/01 17:18:31 builder.go:620: finished /data/index/ghe.sgdev.org%2Finfallible-tereshkova-128%2Fjulianromera-jsdelivr_v16.00006.zoekt: 1252912 index bytes (overhead 2.9)
2020/06/01 17:18:58 builder.go:620: finished /data/index/ghe.sgdev.org%2Finfallible-tereshkova-128%2Fjulianromera-jsdelivr_v16.00000.zoekt: 166807173 index bytes (overhead 2.7)
2020/06/01 17:19:03 builder.go:620: finished /data/index/ghe.sgdev.org%2Finfallible-tereshkova-128%2Fjulianromera-jsdelivr_v16.00007.zoekt: 189279755 index bytes (overhead 2.8)
2020/06/01 17:20:37 builder.go:620: finished /data/index/ghe.sgdev.org%2Finfallible-tereshkova-128%2Fjulianromera-jsdelivr_v16.00013.zoekt: 3358458 index bytes (overhead 3.0)
```

Looks like very large repos can cause indexing to OOM.

**Comment by keegancsmith** [comment]
> > ```
> > ERR: 2020/06/01 10:44:35 main.go:237: archive/tar: invalid tar header
> > 2020/06/01 10:45:31 error indexing ghe.sgdev.org/agitated-bouman-446/CloudMaster-Manoj-AC@HEAD=cfcc4223d2dfaa1516f1181880d689b2b5b2becc: command [zoekt-archive-index -name ghe.sgdev.org/agitated-bouman-446/CloudMaster-Manoj-AC -commit cfcc4223d2dfaa1516f1181880d689b2b5b2becc -incremental -branch HEAD -download-limit-mbps 1000 -file_limit 1048576 -parallelism 8 -index /data/index -require_ctags http://sourcegraph-frontend-internal/.internal/git/ghe.sgdev.org/agitated-bouman-446/CloudMaster-Manoj-AC/tar/cfcc4223d2dfaa1516f1181880d689b2b5b2becc] failed: exit status 1
> > OUT: 
> > ```
> > 
> > 
> > this might be bum git repos (there are some in our collection of 111 million repos). worth checking here that the bum repos are not poison pills that prevent indexing of other repos (i don't think so, but worth double-checking).
> 
> Yeah it won't be a poison pill. We do need smarter behaviour around bad repos though to avoid constantly attempting them. Thanks for pointing this out though, I'll see what is up with this repo.

I took a quick look into this. Using tar directly does complain about an unknown header. So the next step is passing this tarball into zoekt-archive-index and working out why it is failing. More than likely we just need to skip some file (or maybe adjust flags we pass to git archive?). This is the sort of thing that may apply across our stack, and not be zoekt specific.

```
indexed-search-2:/data/index/.indexserver.tmp/tmpfriend-6-349160997# curl -L http://sourcegraph-frontend-internal/.internal/git/ghe.sgdev.org/agitated-bouman-446/CloudMaster-Manoj-AC/tar/cfcc4
223d2dfaa1516f1181880d689b2b5b2becc > foo.tar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 74.3M    0 74.3M    0     0   104M      0 --:--:-- --:--:-- --:--:--  114M
indexed-search-2:/data/index/.indexserver.tmp/tmpfriend-6-349160997# tar tf foo.tar > /dev/null
tar: warning: skipping header 'x'
```

**Comment by uwedeportivo** [comment]
for this last one: dave observed that the repo contains more binary files than normal. so it might be a contributing factor

**Comment by keegancsmith** [comment]
> > > ```
> > > ERR: 2020/06/01 10:44:35 main.go:237: archive/tar: invalid tar header
> > > 2020/06/01 10:45:31 error indexing ghe.sgdev.org/agitated-bouman-446/CloudMaster-Manoj-AC@HEAD=cfcc4223d2dfaa1516f1181880d689b2b5b2becc: command [zoekt-archive-index -name ghe.sgdev.org/agitated-bouman-446/CloudMaster-Manoj-AC -commit cfcc4223d2dfaa1516f1181880d689b2b5b2becc -incremental -branch HEAD -download-limit-mbps 1000 -file_limit 1048576 -parallelism 8 -index /data/index -require_ctags http://sourcegraph-frontend-internal/.internal/git/ghe.sgdev.org/agitated-bouman-446/CloudMaster-Manoj-AC/tar/cfcc4223d2dfaa1516f1181880d689b2b5b2becc] failed: exit status 1
> > > OUT: 
> > > ```
> > > 
> > > 
> > > this might be bum git repos (there are some in our collection of 111 million repos). worth checking here that the bum repos are not poison pills that prevent indexing of other repos (i don't think so, but worth double-checking).
> > 
> > 
> > Yeah it won't be a poison pill. We do need smarter behaviour around bad repos though to avoid constantly attempting them. Thanks for pointing this out though, I'll see what is up with this repo.
> 
> I took a quick look into this. Using tar directly does complain about an unknown header. So the next step is passing this tarball into zoekt-archive-index and working out why it is failing. More than likely we just need to skip some file (or maybe adjust flags we pass to git archive?). This is the sort of thing that may apply across our stack, and not be zoekt specific.
> 
> ```
> indexed-search-2:/data/index/.indexserver.tmp/tmpfriend-6-349160997# curl -L http://sourcegraph-frontend-internal/.internal/git/ghe.sgdev.org/agitated-bouman-446/CloudMaster-Manoj-AC/tar/cfcc4
> 223d2dfaa1516f1181880d689b2b5b2becc > foo.tar
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> 100 74.3M    0 74.3M    0     0   104M      0 --:--:-- --:--:-- --:--:--  114M
> indexed-search-2:/data/index/.indexserver.tmp/tmpfriend-6-349160997# tar tf foo.tar > /dev/null
> tar: warning: skipping header 'x'
> ```

So the tarball produced by git can't be parsed by go's tar or bsdtar. I think I will stop looking further into this one since we will be switching to git clones in the future.

I think that resolves all 3 issues reported:
1. fsnotify: fixed in zoekt upstream now.
2. configuration fail: issue in frontend, fixed via resources.
3. invalid tar header: won't fix. Will be resolved in next two iterations if/when we default indexing via git instead of tar.

**Comment by uwedeportivo** [comment]
👍

**Comment by uwedeportivo** [comment]
for the "tar invalid header" files. i tracked it down and reproduced it. it fails in parsePAXRecord in the archive/tar/strconv.go (it's a somewhat known issue with git archive tar)

in the meantime (until you convert to default indexing via git), could we try switching to zip instead.
it's a trivial code change. i was wondering if you tried zip before and it wasn't performant or something.
with zip we also have way more options in golang, not just the std library.

**Comment by uwedeportivo** [comment]
ok, i figured it out myself :-). i made the code changes and deployed to our replica and it poops out because we don't have streaming support with zip. nvm

**Comment by keegancsmith** [comment]
> ok, i figured it out myself :-). i made the code changes and deployed to our replica and it poops out because we don't have streaming support with zip. nvm

yup. It's non standard but we could technically stream in the zip since we can assume the zips from git are somewhat well formed. I experimented with it a long time ago https://github.com/sourcegraph/lazyzip
