### ISSUE TITLE
add Postgres scaling advice to resource estimator

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#11205]
We should:
1. [ ] Update our default postgresql.conf to match the default cpu/memory we specify in https://github.com/sourcegraph/deploy-sourcegraph/blob/master/base/pgsql/pgsql.Deployment.yaml#L62-L67
1. [ ] Add metrics to signal if Postgres performance is slow https://github.com/sourcegraph/sourcegraph/issues/11204
2. [ ] Rollout that change and, after a few months, determine what the average resources customers give to postgres is: https://github.com/sourcegraph/sourcegraph/issues/11204
3. [ ] Add more precise scaling advice to the resource estimator for Postgres

**Comment by tsenart** [comment]
@slimsag: This looks good to me, and I agree establishing a performance baseline is important, but I'm pretty sure can get quick wins by simply adjusting the Postgres configuration we ship to customers, based on the resources that are allocated to it (i.e. https://pgtune.leopard.in.ua/), so I'd put that first/.
