### ISSUE TITLE
Missing monitoring to signal if postgres performance is poor

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#11204]
Most customers today either use managed Postgres DBs (e.g. Amazon RDS) or our default deployment resource allocations:

- [Kubernetes](https://github.com/sourcegraph/deploy-sourcegraph/blob/master/base/pgsql/pgsql.Deployment.yaml#L53-L58)
- [docker-compose](https://github.com/sourcegraph/deploy-sourcegraph-docker/blob/master/docker-compose/docker-compose.yaml#L518-L519)
- [pure-docker](https://github.com/sourcegraph/deploy-sourcegraph-docker/blob/master/deploy-pgsql.sh#L18-L19)

Postgres's scaling behavior is all relative to its available memory. It will, e.g., run faster if given more memory, or run slower if there is not sufficient memory. This is in stark contrast to other Sourcegraph services which will not degrade gracefully like that and instead will have a hard OOM - making it clear they need more resources.

We do not know today if customer Postgres instances are slow or not, and we do not have a way to measure it. This also means we do not really have good baselines for giving advice in the resource estimator, aside from "the default deployment works well today", and thus this issue is a precursor to us adding scaling advice for postgres there.

We should identify a way to test postgres performance through e.g. measuring the performance of several of our postgres queries and defining alerts on them. When slow, that would signal Sourcegraph could benefit from more postgres resources and that the instance is in an abnormal state and we could notify site admins.

Likely the best way to measure this will be sourcegraph.com (but it does not run repo-updater today) and k8s.sgdev.org (but it is properly provisioned today?).

**Comment by bobheadxi** [comment]
@daxmc99 I believe you did some work on this?

**Comment by daxmc99** [comment]
We currently have some Postgres metrics here but they are disabled until we can find an upper bound for max transaction time 
See https://github.com/sourcegraph/deploy-sourcegraph-dot-com/pull/4218 for where we had to silence the alerts in cloud
