### ISSUE TITLE
resources-report: generate each report in a new page

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#11211]
from #11207:

> >    It also means I can't comment on the cells to tag other people (e.g. to ask questions about resources they created), which would be nice.
>
> because I think it would essentially necessitate creating a new report (sheet page) for each run (which isn't bad), and maybe automatically deleting everything older than the last n pages.

**Comment by slimsag** [comment]
I'd be perfectly fine with it never deleting old sheets FWIW
