### ISSUE TITLE
explore solutions for "impossible to silence monitoring alerts"

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#11210]
Sourcegraph.com has some alerts always firing (e.g. gitserver disk space) that we do not care about on Sourcegraph.com. Customers will likely have a few outliers like this, too, where silencing will be important.

We should have a mechanism for silencing these _somehow_.

**Comment by bobheadxi** [comment]
With #11832, this could be resolved by making API calls to the [Alertmanager API](https://github.com/prometheus/alertmanager/blob/master/api/v2/openapi.yaml#L65) or doing the same thing via configuration change

**Comment by slimsag** [comment]
Does Alertmanager have a web UI with silencing already that we could expose more easily, I wonder?

**Comment by bobheadxi** [comment]
> Does Alertmanager have a web UI with silencing already that we could expose more easily, I wonder?

Yep! https://github.com/sourcegraph/sourcegraph/pull/11832 reverse-proxies Alertmanager on `prometheus:port/alertmanager`. A user will be able to port-forward `svc/prometheus` to silence alerts.

**Comment by bobheadxi** [comment]
Whether more work needs to be done probably depends on whether or not we want alert silencing to live in site configuration as well, and whether or not we want to make it even more accessible (ie via `/-/debug/alertmanager` for example - though from what I understand, this might expose it to CSRF, which Grafana gets around by making it impossible to do anything. Not sure if Alertmanager has the same protection out of the box)

**Comment by bobheadxi** [comment]
https://prometheus.io/docs/operating/security/#api-security

> administrative and mutating endpoints are intended to be accessed via simple tools such as cURL, there is no built in CSRF protection as that would break such use cases. Accordingly when using a reverse proxy, you may wish to block such paths to prevent CSRF.

**Comment by slimsag** [comment]
Discussed live with Robert, TL;DR:

It is not possible to expose write-actions (POST) behind our debug auth proxy unless the underlying service does CORS properly. This means we have these options:

1. Implement CSRF in alertmanager
2. Do alert silencing via site config
3. Do alert silencing via our web UI itself
4. Require port-forwarding to silence alerts

Our conclusion is that #2 makes the most sense, is the best middle-ground solution, and is least-likely to lead to admins disabling alerting entirely.

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
