### ISSUE TITLE
Regex or globbing support for branch or revision names

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#11213]
Support something like `repo:^hyper/hyper-db$@release_.+` or `repo:^hyper/hyper-db$@release*`. This overlaps with some other search features and syntax we care about, namely:

- glob support for repos (not branches), in the form of `repo:foo*` https://github.com/sourcegraph/sourcegraph/issues/10094
- adding a `rev` field to queries, so that the above can rather be expressed as `rev:release*` rather than tacked onto repo (see https://github.com/sourcegraph/sourcegraph/issues/9712 and partial discussion in https://github.com/sourcegraph/sourcegraph/issues/10820)

**Comment by rvantonder** [comment]
Adding some additional context from [slack convo]( https://sourcegraph.slack.com/archives/CHEKCRWKV/p1587500488040500):

- This should probably apply to `file` and `repo` params
- One idea: add syntax to disambiguate intent, e.g., `field:substring` `field:=exactstring` `field:~regex` (or `field:/regex/`) and `field:%glob`
  - feedback: not sure users would intuitively know to use field:%glob , default assumption of users is field:glob when it's file or repo filter but substring otherwise
  - feedback: support Kleene-star * syntax for globbing and don't think it'll significantly impact existing regex filters. Supporting other syntax should be done carefully (it's great to support "everything"), but syntactically richer can also mean bogging things down
- feedback on a heuristic for implementing globbing versus just making it a consistent default, instead of extra syntax:

> I value consistency since it avoid surprises / makes the interface easier. I think for example a regular expression for content but glob for file can be quite surprising (especially when you look at things like the * ). However, the argument could be made that all non content fields make much more sense as globs

- There's a world where we can convert the query from regex to globs in the UI, and not the backend. Because the backend is currently the source of truth for parsing and validation, @rvantonder does not think this is where the logic should go right now.

Summary:

@stefanhengl you should feel free to propose a solution for the above and gather input. Revisiting the feedback I think we may actually have a strong case for treating `repo:` and `file:` filters as literal strings with glob support _by default_. The open question is how to support regular expressions if we change the default (maybe syntax, maybe a heuristic that detects regex metasyntax, maybe something else).

**Comment by camdencheek** [comment]
Closing as done since globbing can be used in the `repo:name@*refs/heads/*` position and with `rev:*refs/heads/*`
