### ISSUE TITLE
ability to run a search across all repos & branches

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#11224]
A user at https://app.hubspot.com/contacts/2762526/company/407948923/ wants to run a search query across all repos and branches to e.g. ensure every usage of an API (even on non-master branches) is eliminated.

I can imagine the same being useful for e.g. redacting tokens and other things like that.

Today, however, the closest you can get is:

- Search all branches/tags in a repo, if you turn on the experimental `searchMultipleRevisionsPerRepository` feature flag -- but it'd be very slow over several thousand repos and most likely the UI would time out (given it is unindexed) or the sourcegraph deployment would blow up (that's a lot of unindexed searches).
- Write some code around `src search 'type:repo .'` to list every repository, then slowly run a single search for each repository.

There is some orthogonality here to campaigns, but this is a clear use case where reaching for search makes sense -- not a campaign. Two ask:

1. Can we support this via the `src` CLI nicely? e.g. ability to run a long-running search, specifically across all repos and branches.
2. Can we support this via the web UI nicely? Same thing, but communicating progress in the web UI and not timing out (many people run an HTTP proxy in front of sourcegraph that times out after 60s).

Likely the best path to #1 would be via the search pagination API: adding support for it to the `src` CLI and somehow enabling `searchMultipleRevisionsPerRepository` by default (without allowing one to blow up instances with unindexed searches).

**Comment by slimsag** [comment]
Additional context here: https://sourcegraph.slack.com/archives/C0W2E592M/p1591061948305300

**Comment by rvantonder** [comment]
Search syntax related to #11213 and issues in there (cf. discussion supporting `rev:` as it's own field to support globbing/regex pattern support for a behavior to search "all" branches).

Backend work: in addition to pagination, repo/revision code is not pretty and needs attention.

**Comment by stefanhengl** [comment]
Done. To search all repos and all branches run a search like this `r:.* rev:*ref/heads/* <pattern>`.
