### ISSUE TITLE
Search results count now shows number of file matches, rather than number of text matches

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#11236]
Reported by https://app.hubspot.com/contacts/2762526/company/732945850

>For example, a user noticed that the count of results were different between the two instances. I did some investigating and it appears that in 3.12.6 the count was counting the number of instances of the search string. In 3.15.1 it appears the count is counting the number of files in which the search string occurred. So we'd see 27 in the older version and 23 in the newer version

I assumed that the former behavior was the "correct" one, but I'm not sure if that's the case. What is the desired behavior here?

**Comment by rvantonder** [comment]
I strongly believe nothing in the match count logic changed across these versions, except for structural search (given the 3.12 version, there is a low chance this is a structural search issue, but still possible).

I need more info to help with this:

- Are we sure that all results are being showed for these two results sets? (i.e., `count:1000` is set). If the results are partial, then the number of results can vary.
- If the complete results are shown, are we confident that the file contents are exactly the same? I.e., where there is a discrepancy in count for 3.12 <-> 3.15, are the missed/uncounted matches visible in the file contents of the 3.12 also visible in the 3.15.1 version?
- Was this literal search or regex search, or maybe structural?

**Comment by rvantonder** [comment]
Update: the correct number of lines are reported with `index:no`, so this is something to do with indexed matches. Cf.

1 result, index:yes https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24%409868cad+file:%5Ecmd/frontend/graphqlbackend/search%5C.go+repoRevs+index:yes&patternType=literal

26 results, index:no https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24%409868cad+file:%5Ecmd/frontend/graphqlbackend/search%5C.go+repoRevs+index:no&patternType=literal

Still digging...

**Comment by rvantonder** [comment]
A regression was introduced by https://github.com/sourcegraph/sourcegraph/pull/9541/files where `MatchCount` was introduced and updated for unindexed regex search and structural search, but not on the indexed (Zoekt) path. Indexed search counts are off (at most 1 match is counted per file, rather than line).

Besides the regression, while investigating I found _another_ bug that causes a discrepancy in indexed <-> unindexed search counts (irrespective of #9541 above). The problem with that bug is that the indexed search path would only previously count the number of matching _lines_ (i.e., if multiple search results show up on the same line like matching `foo` in `foo foo foo`, the number of matches would be 1, instead of 3. On the unindexed search path, it would count 3. This is due to how matches are added to a list in the unindexed search path (only one offset/length entry per match), whereas in the Zoekt path they are bundled together (but not counted separately).

**Comment by rvantonder** [comment]
Fixed by #11242. Might be worth doing a minor patch release that backports this.

**Comment by ssbarnea** [comment]
I tried to search the docs and also google for a way to count how many filenames with specific  name are on a repository. I am trying to find repositories which have more than on `package.json` in them, or something similar. Is that possible? I do not care about repos with one file occurrence, only about those with more than one.

**Comment by rvantonder** [comment]
@ssbarnea hey, sorry for the late reply. We have some new tooling that could help with that (it's not easily possible inside only the search window). What would help is knowing whether you are using Sourcegraph.com or a different instance?

To give you an example, here's an external site that uses the tooling:

[codestat.dev example counting `package.json` per repository](https://codestat.dev/explorer?q=repo%3Agithub%5C.com%2Fansible%2F*%20content%3Aoutput(.*%20-%3E%20%24repo)%20file%3Apackage.json%20count%3Aall%20type%3Apath&t=table&dp=100)

Example output:

<img width="883" alt="Screen Shot 2022-07-05 at 3 06 12 PM" src="https://user-images.githubusercontent.com/888624/177425048-45c7306b-af0d-4942-b7e9-002bc5fed54c.png">


The query says:

"In all repositories under `github.com/ansible`, find file paths with name `package.json`. For each match, output the `$repo`". The tool computes the count of `package.json` per repo for a query like this. Sorting by count, there are 3 repositories that contain 2 `package.json`. The rest all contain 1. It's not possible yet to filter out the `1` count repositories, but something we can easily add or postprocess.

**Comment by rvantonder** [comment]
@ssbarnea cool, well, [here's a similar query for `pyproject.toml`](https://codestat.dev/explorer?q=repo%3Agithub%5C.com%2F%20content%3Aoutput(.*%20-%3E%20%24repo)%20file%3Apyproject.toml%20count%3Aall%20type%3Apath&t=table&dp=10000). It will time out after 60 seconds (so it doesn't run forever, as a guard, though could be modified to run longer). And it does probably cover the vast majority of popular OSS GH repositories (it tends to search repositories by highest stars first). Is this helpful?

![Screen Shot 2022-07-06 at 12 43 22 PM](https://user-images.githubusercontent.com/888624/177630583-0d9e40aa-1718-4924-9672-15cb0da6ffcd.png)
