### ISSUE TITLE
dev: Grafana generated dashboards not loading on startup

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#11237]
when the server first starts up it will use the dashboards baked into the base container (it was previously built). Only when you save a file will it regenerate and actually pick up the changes. 

The generated dashboards are not mounted properly into the container (the deprecated jsonnet ones are, though): https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/grafana.sh#L23-38

**Comment by bobheadxi** [comment]
@slimsag I have a commit in #11082 for this: https://github.com/sourcegraph/sourcegraph/pull/11082/commits/2bffb317ac3e22ac109ab503faebfda91bc60146

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
