### ISSUE TITLE
Add tests for raw endpoint

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#11259]
I fixed a bug in this area recently and noticed there were no tests.

I didn't add any initially as I think it might require a bit of a refactor in order to mock out gitserver responses but adding a debt item here so we don't forget to go back to it.

https://github.com/sourcegraph/sourcegraph/blob/master/cmd/frontend/internal/app/ui/raw.go#L62

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
