### ISSUE TITLE
License report for syntect_server & its dependencies

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#11269]
See https://github.com/sourcegraph/sourcegraph/pull/11116#discussion_r433355048

**Comment by slimsag** [comment]
Additional context: https://sourcegraph.slack.com/archives/C0C324C91/p1591231461259700

**Comment by slimsag** [comment]
Assessment of all the syntax definitions we include is done and here: https://github.com/slimsag/Packages#license

I will be removing the four questionable ones included by accident there

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by slimsag** [comment]
@dadlerj what is the priority of this in your eyes?

**Comment by dadlerj** [comment]
Making it automated—very low

Simply having at least a current version—moderately important... Would be nice to have for the next release

Just so I know, how complex is this? I assume it's just copying syntect's own license along with the report for the definition files that you generated above, right?

**Comment by slimsag** [comment]
It's not super complex, just needs a few hours maybe. I already have the _hand-made_ version here: https://github.com/slimsag/Packages#license I would just need to combine that with the other dependencies we pull in.

The one major component here is removing the five languages mentioned at the top of that table which have questionable (read: GPL or untraceable) licenses, documenting those regressions in our product, and filing follow-up issues for us to prioritize writing syntaxes for those. Mostly communication/docs/explanation, but not trivial.

**Comment by dadlerj** [comment]
I don't think we actually have to remove those—Linux is GPL, and it's inside of a Docker container with Sourcegraph, and that's not a problem. 

Might be worth pulling the lawyers in on this front, but what if I told you that that work wasn't required?

**Comment by slimsag** [comment]
Three of those five _do not have licenses at all_, so legally - yes - we must remove them.

I agree that technically we could keep the two GPL ones, but I do not think that including them is a smart idea as they are linked into the final binary and GPLv2 dictates we would need to license `syntect_server` under GPL as well if we accept that. Sure, we could do that - but I'd much prefer we just remove them and dedicate some resources to writing some non-GPL ones in the future (I am sure there will be demand, and it wouldn't be a bad idea to have people at Sourcegraph knowledgable in how to add syntax highlighting for new languages from the ground up - not a super difficult feat..)

I could do these as separate tasks, technically, but it would just make it take longer to complete both as I would need to perform two independent updates (there are about a half a year of changes I need to pull in, and that changes which dependencies we consume.)

**Comment by dadlerj** [comment]
Thanks. Understood, yeah let's remove the unlicensed ones. 

Universal-ctags is GPL, and we bundle that with Sourcegraph. As long as there's an application-level wall between our product and the GPL code, we should be fine here.

Your fork of syntect might be a different story, but again I'd have to check with the lawyers. 

This problem doesn't just apply to us obviously, a lot of companies are being forced to make these decisions given the law hasn't kept up with concepts like Docker. My understanding is that packaging GPL code _alongside_ your application in a Docker image is considered safe, and I believe we should continue to operate under that assumption for now.

**Comment by slimsag** [comment]
`universal-ctags` is a binary we ship separately, `syntect_server` is also a binary shipped separately so in that respect you are correct.

However, we cannot claim `syntect_server` to be MIT-licensed as it is today if it includes GPL code as it does today. There are three options only:

1. Change the license of https://github.com/sourcegraph/syntect_server to GPLv2 - I am against this.
2. Remove the GPLv2-licensed syntaxes with intent of replacing them in the future.
3. _Link_ against the GPLv2 licensed syntaxes ("include them at runtime"), requires substantial engineering effort and not worth it IMO.

**Comment by slimsag** [comment]
To be totally clear: If I am working on syntect_server it's easier for me to tackle a few issues in a bundle than it is to do them one-by-one due to the way everything is set up.

**Comment by dadlerj** [comment]
Very well, I was only focused on our main sourcegraph/sourcegraph codebase, not the syntect_server fork. Totally leave the decision from here up to you!

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by slimsag** [comment]
I will do this after the branch cut so it goes out in 3.21 and we have as much time as possible to gauge reactions/feedback internally on this change, and if needed additional time to do mitigation work such as e.g. creating our own GraphQL syntax.
