### ISSUE TITLE
Auth: explicit session invalidation

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#1126]
Provide an explicit session invalidation mechanism for Sourcegraph.

Currently, sessions are invalidated after they expire (configurable via the `auth.sessionExpiry` option) or on user sign-out. Proposal is to also enable explicit session invalidation in the following scenarios:
* An admin manually invalidates all sessions for a given user.
* A user's existing sessions are invalidated after successful password reset or password change under built-in auth.
* Session is not cleaned up after user log out (added by @unkwon)

**Comment by tsenart** [comment]
Any customers asking for this?

**Comment by beyang** [comment]
No customers asking for this currently.

**Comment by tsenart** [comment]
Deprioritising this since there are no customers asking for this yet and there are more pressing issues to be addressed.

**Comment by ElizabethStirling** [comment]
Finished with PR #13647
