### ISSUE TITLE
FR: Show browser extension stats on site-admin page

### ISSUE THREAD

**Issue by francisschmaltz** [sourcegraph/sourcegraph#1128]
In the same way as https://github.com/sourcegraph/sourcegraph/pull/1018 we should show browser extension usage stats to the site admin.

There should be a single stat that we show and then the line can expand to show more information and any external links.

Here is a mock of how it should look:

![48584384-70f09980-e8de-11e8-8017-cf68fbba3f2c](https://user-images.githubusercontent.com/11583013/49036659-23412000-f16d-11e8-9e67-52b7df95bb3f.png)

**Comment by dadlerj** [comment]
@ijsnow are you using the browser extension usage data that admins have access to on the "Usage stats" page for this? I believe I linked you to this at some point earlier in the product planning process. I'd like to avoid implementing a new data source for this information. 

I.e., the last column on any /site-admin/usage-statistics page

**Comment by ijsnow** [comment]
Nope and I talked with @sqs yesterday and decided I'm not working on this project anymore as it morphed into https://github.com/sourcegraph/sourcegraph/issues/975.

**Comment by dadlerj** [comment]
Should this issue be closed then?
