### ISSUE TITLE
Search query syntax for archived repositories

### ISSUE THREAD

**Issue by sfllaw** [sourcegraph/sourcegraph#113]
#### Describe the feature request.
Now that you can [archive repositories in GitHub](https://help.github.com/articles/archiving-a-github-repository/), we should be able to search for:
* non-archived repositories only (maybe this is the default behavior?)
* archived repositories only
* all repositories

I propose an `archived` keyword that has the following options to match [GitHub's search syntax](https://help.github.com/articles/searching-repositories/#search-based-on-whether-a-repository-is-archived):
* non-archived repositories only: `archived:false`
* archived repositories only: `archived:true`
* all repositories `archived:any`

#### Is your feature request related to a problem? Please describe.
We would like to exclude archived repositories from the default search, to reduce the number of irrelevant search results.

#### Describe alternatives you've considered.
We currently move archived repositories to another organization, but that changes the URL of the repository so it is unsatisfying. It would be better to rely on the new archived repositories feature.

#### Additional context
* [Archiving Repositories | The GitHub Blog](https://blog.github.com/2017-11-08-archiving-repositories/)
* #108: Add the ability to disable Github projects if they've been archived on Github

**Comment by sqs** [comment]
We just added a `fork:` search keyword (will be in the release tomorrow), and we should add this too. 👍 

Adding @beyang (who worked on `fork:`) and @attfarhan (who worked on similar issues last release).

**Comment by attfarhan** [comment]
Yes, tackling this is part of my plan this month.

**Comment by attfarhan** [comment]
We've implemented this in master, and it will be available in the next release.

**Comment by attfarhan** [comment]
One thing to note: the syntax follows our existing syntax for filtering similar items (like forks) rather than GitHub's syntax. The syntax will be `archived:no` to filter out  results from archived repos, `archived:only` to search over archived repos only.

**Comment by nicksnyder** [comment]
This is fixed in 2.12.0

**Comment by allyn-psyonix** [comment]
Just wanted to point out that this search capability is not described on the advanced search page or the cheat sheet. I only found out about it by a google search that brought me to this ticket. Might be worth updating the advanced search page and cheat sheet.

**Comment by allyn-psyonix** [comment]
I'm sorry, I wasn't paying close enough attention and I thought this was a ticket for github's native search feature. The sourcegraph documentation for this looks great =)
