### ISSUE TITLE
Sourcegraph redirects to localhost:3081

### ISSUE THREAD

**Issue by francisschmaltz** [sourcegraph/sourcegraph#1130]
Sourcegraph redirects to port 3081.

To encounter this I did a fresh clone of Sourcegraph/sourcegraph and tried both on OSS and Enterprise.

The only reference is in `gulpfile.ts` lines 32-59 where it sets up a proxy

![screen shot 2018-11-26 at 11 36 09 am](https://user-images.githubusercontent.com/11583013/49037580-7ae08b00-f16f-11e8-99c1-16af68201d96.png)

![screen shot 2018-11-26 at 11 35 15 am](https://user-images.githubusercontent.com/11583013/49037543-597f9f00-f16f-11e8-9167-7469b55f5b12.png)

**Comment by sqs** [comment]
See https://sourcegraph.slack.com/archives/C07KZF47K/p1541900379295900?thread_ts=1541900379.295900. Does that help?

**Comment by francisschmaltz** [comment]
That solved my problem. I didn't have the updated config – I figured it was pulling automatically.
