### ISSUE TITLE
Background permission fetching causes repos from 2nd code host to be inaccessible

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#11318]
Reported by https://app.hubspot.com/contacts/2762526/company/557475933

Described in https://sourcegraph.slack.com/archives/CHPC7UX16/p1591375494489800

The customer has a workaround in the form of disabling background permission syncing.

**Comment by unknwon** [comment]
Making this as a release blocker so if not resolved before release, I need to revert https://github.com/sourcegraph/sourcegraph/pull/10972.
