### ISSUE TITLE
redis-exporter image is 32-bit and not open-source

### ISSUE THREAD

**Issue by terinjokes** [sourcegraph/sourcegraph#11323]
- **Sourcegraph version:** v3.16.1
- **Platform information:** Linux 5.4

#### Steps to reproduce:

1. Fetch redis-exporter image

```
$ skopeo copy docker://index.docker.io/sourcegraph/redis_exporter@sha256:282d59b2692cca68da128a4e28d368ced3d17945cd1d273d3ee7ba719d77b753 dir:image
Getting image source signatures
Copying blob a3dd6b185a5a done
Copying blob a3ed95caeb02 done
Copying blob 11dd4c90e5d0 done
Copying blob a3ed95caeb02 skipped: already exists
Copying blob a3ed95caeb02 skipped: already exists
Copying blob c5cbcf67ce48 [======================================] 22.3KiB / 22.3KiB
Copying config b8e9f0a71b done
Writing manifest to image destination
Storing signatures
```

2. Extract redis-exporter binary

```
$ tar xf image/11dd4c90e5d031e27c75024376729d1529c94ea46eba8a3ac1d7ad0d16461663 bin/redis_exporter

$ file bin/redis_exporter
bin/redis_exporter: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), statically linked, Go BuildID=6e51264daa7fea84d28d7c902cbf2e018bd8a55a, with debug_info, not stripped
```

#### Expected behavior:

Binary is 64-bit like the rest of the Sourcegraph images.

#### Actual behavior:

Binary is 32-bit, so it fails on distributions that have IA32 emulation disabled.

**Comment by sqs** [comment]
I’m guessing this is just a mistake that nobody else has reported.

**Comment by terinjokes** [comment]
@beyang I can't see sourcegraph/infrastructure repository, where this image seems to originate. Are you able to tell us if this is just the upstream redis_exporter image relabeled with no changes?

If so, we can fix this locally.

**Comment by slimsag** [comment]
Super sorry this is happening, we will make this open-source very soon in the `docker-images` folder of this repo. It's not meant to be private, it just ended up there by accident.

Here are the entire contents of the Dockerfile:

```
FROM oliver006/redis_exporter:v0.34.1@sha256:4f4420c643e83840753d57b8f7a5afd08b83f1645ca43c60278b75a3907a57a5
RUN addgroup -S redis && adduser -S -G redis -h /home/redis redis
USER redis
```

**Comment by terinjokes** [comment]
We migrated to a newer `redis_exporter` image without issue.

**Comment by slimsag** [comment]
Excellent, thank you for the information!

**Comment by ianseyer** [comment]
This is still causing issues without manual intervention from the `deploy_sourcegraph` repo.

**Comment by davejrt** [comment]
@terinjokes @ianseyer we've opensourced our redis_exporter build, and in the process updated our base so you shouldn't have any further issues

```
$ docker save sourcegraph/redis_exporter:84464_2021-01-15_c2e4c28 | undocker -i -o redis 
$ cd redis/
$ file redis_exporter 
redis_exporter: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped
```
