### ISSUE TITLE
Selecting an item in the search autocomplete list requires tooltip

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#11324]
- **Sourcegraph version:** 3.16 cloud, but should be on all instances
- **Platform information:** Chrome

#### Steps to reproduce:

1. Type `repo:` in the search bar. Wait for the autocomplete to appear and use the arrow keys to move to the second item. 
2. Press **return** to select the item as per Jetbrains IDEs, browser dropdowns, and other inputs.  

#### Expected behavior:

A tooltip helps me understand that TAB is the method of selection in this interface. "

#### Actual behavior:

The autocomplete window closes.

#### Notes:

See Quinn Keast's solution below.

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by rrhyne** [comment]
I love this solution.

**Comment by limitedmage** [comment]
@quinnkeast Love this! Do you have a Figma design/redlines for this? If not, I can come up with something based on the mockup screenshot you posted.
