### ISSUE TITLE
Display warning to users if repository is unavailable to search

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#11322]
#### Feature request description

When a repository being searched is a fork or it is currently being cloned or indexed, the user is not notified. Searches on that repository may not return results. 

For each search, review the current repository status of each repo in the search (resolving repogroups). If a repo is cloning or indexing, display a warning message to the user stating which repository is unavailable for search.

#### Is your feature request related to a problem? If so, please describe.

Customer feedback:

> is there a capability to display a warning or status message? it's not usual to have issues with a large codebase. for example, "we just started indexing a new branch" or "we had a perforce problem so we're reindexing everything from scratch"

https://app.hubspot.com/contacts/2762526/company/693777200

**Comment by rrhyne** [comment]
If this is difficult to do during a search, clearly showing the status of each repository in a code host as it's being added could alert the user to the issue as well:

https://github.com/sourcegraph/sourcegraph/issues/10899

**Comment by rvantonder** [comment]
Hey @rrhyne thanks--I think we missed this issue, please tag @sourcegraph/search or assign me or someone else on the search team, or link the issue in #search slack in future (this will send a notification and ensure we don't miss anything). Maybe also post #10899 in #web

**Comment by rrhyne** [comment]
Closed as it was addressed in: https://github.com/sourcegraph/sourcegraph/issues/10899
