### ISSUE TITLE
How can I use extensions on an OSS sourcegraph with no access to sourcegraph.com

### ISSUE THREAD

**Issue by philippe-granet** [sourcegraph/sourcegraph#11333]
#### Question description

I setup an OSS sourcegraph for test in our private network, with no internet access for security reasons.
I try to install extension from the UI , but I have this error:
` Unable to contact extension registry: Get "https://sourcegraph.com/.api/registry/extensions": dial tcp 172.67.75.219:443: i/o timeout`

I have also tried to install extension from source code, but I have this error:
```
SRC_ENDPOINT=https://sourcegraph.private.instance SRC_ACCESS_TOKEN="...."  src extensions publish
GraphQL errors:
[
  {
    "message": "The feature \"private-extension-registry\" is not activated because it requires a valid Sourcegraph license. Purchase a Sourcegraph subscription to activate this feature.",
    "path": [
      "extensionRegistry",
      "publishExtension"
    ]
  }
]
```

So, how can I use extensions on an OSS sourcegraph with no access to https://sourcegraph.com ?

**Comment by unknwon** [comment]
Hi!

I think the real problem is clear here:

>The feature \"private-extension-registry\" is not activated because it requires a valid Sourcegraph license. Purchase a Sourcegraph subscription to activate this feature.

It is not available for OSS version :)
