### ISSUE TITLE
Extension to add a custom feedback option

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#1134]
Original issue was: https://github.com/sourcegraph/enterprise/issues/12694.

Background: A customer has requested the ability to add a custom feedback option, so they can collect internal product feedback more efficiently.

Proposal: Implement an extension that provides this functionality.

![image](https://user-images.githubusercontent.com/1976/44364641-63ad4580-a47c-11e8-81fc-25501e4a7587.png)

Make adding stuff to the top of the menu possible, so the "Help" group in their menu would look like:

```
Help
-----
$CUSTOMER internal issue tracker
#sourcegraph on $CUSTOMER_CHAT
How to search
Sourcegraph documentation
Public support forum [StackOverflow]
Public issue tracker
Contact Sourcegraph
```

**Comment by sqs** [comment]
closing in favor of https://github.com/sourcegraph/sourcegraph/issues/3499
