### ISSUE TITLE
Go buildserver test failure

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#1135]
One of the Go buildserver integration tests is failing on master (but not failing CI because it's skipped in CI):

```
$ go test github.com/sourcegraph/sourcegraph/enterprise/cmd/xlang-go/internal/server -run 'TestIntegration'
--- FAIL: TestIntegration (31.66s)
    --- FAIL: TestIntegration/golang-go (0.11s)
        integration_test.go:243: initialize: jsonrpc2: code 0 message: unable to determine workspace's root Go import path: invalid canonical import path "go/constant" in file at path "/src/go/constant/value.go" (original rootPath is "git://github.com/golang/go?f75aafdf56dd90eab75cfeac8cf69358f73ba171") git://github.com/golang/go?f75aafdf56dd90eab75cfeac8cf69358f73ba171
```

Based on https://golang.org/doc/go1.4#canonicalimports, this doesn’t look invalid to me https://github.com/golang/go/blob/f75aafdf56dd90eab75cfeac8cf69358f73ba171/src/go/constant/value.go#L13

```
package constant // import "go/constant"
```

This could be due to GOROOT detection not working properly.

I'll move this issue to go-langserver once the tests have been migrated.

**Comment by tsenart** [comment]
FYI: Bumped into this while setting up my local dev env. @slimsag pointed me to this issue.

**Comment by chrismwendt** [comment]
This will be fixed by special casing the standard library in https://github.com/sourcegraph/go-langserver/pull/345 (specifically in https://github.com/sourcegraph/go-langserver/pull/345/commits/7a09a4af30a24585038a71e689b4464d6e78c2d4#diff-ac2051a40d61acd7db71e57c80b72459)
