### ISSUE TITLE
Add CLI option to update a campaign

### ISSUE THREAD

**Issue by smaifullerton-wk** [sourcegraph/sourcegraph#11350]
I'm writing a CI runner for creating and publishing Sourcegraph campaigns in our organization. It uses a service account with admin access.

Unfortunately, there doesn't seem to be a way to update campaigns that have been created this way because you can only update a campaign using the web UI, which won't work since only admin accounts can create or modify SG campaigns. Our users are using their personal non-admin accounts, not the service account. 

Even if it'd be possible to run and modify Sourcegraph campaigns without admin access, we still want to go the CI route to encourage a central place to store `action.json`s that are run in our org.

It'd be great if you added support for updating an existing campaign via command line if you have generated both the former patchset ID and the updated patchset ID. Something like:

```
src campaigns update -name='My campaign name' \
  -desc='My first CLI-created campaign, edited' \
  -update-patchset=aSdFaSdFaSdFaSdF \
  -new-patchset=Q2FtcGFpZ25QbGFuOjg= \
```

**Comment by sqs** [comment]
Thanks for posting this. We're already working on this, and your context is helpful. We intend to add `src campaigns update [-preview] [-name] [-description] [-{old,new}-patchset] -campaign=ID`.

**Comment by smaifullerton-wk** [comment]
Excellent, thanks for the quick update @sqs

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
