### ISSUE TITLE
document testing process for upgrading grafana

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#11358]
Robert notes that upgrading Grafana may involve changes to the underlying config format, which we will need to ensure we respect: https://github.com/sourcegraph/sourcegraph/issues/9983#issuecomment-640764575

Additionally, I note that upgrading Grafana could break generated dashboards if we don't e.g. upgrade the Go generator grafana dependency at the same time: https://github.com/sourcegraph/sourcegraph/issues/9983#issuecomment-640906607

We should put in place a process for testing Grafana upgrades (to start, just some manual documented smoke tests and testing on k8s.sgdev.org/sourcegraph.com would suffice).

**Comment by bobheadxi** [comment]
https://github.com/sourcegraph/about/pull/1053 covers a little, but probably isn't as robust as this issue describes

**Comment by slimsag** [comment]
https://github.com/sourcegraph/about/pull/1053 sufficiently covers this, we can file follow-up issues as needed or just improve the docs directly.
