### ISSUE TITLE
RFC: Actor-based authz checks instead of `🚨 SECURITY` comments

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#1136]
I'm seeing the proliferation of comments that state "The caller must ensure the request/actor is authorized to perform this action." For example:
* https://github.com/sourcegraph/sourcegraph/pull/1077/files#diff-e4690e26caa9d3d0aeee747eadcd526bR28
* https://github.com/sourcegraph/sourcegraph/pull/1089/files#diff-15c199c34e9c9af789ca286cd0955643R64

Ideally, authz checks are done as close to the data source as possible. This has several advantages:
* We have fewer authz checks (since checking them at a lower level precludes the need to do checking at higher levels, which may use the lower-level APIs in multiple different ways, requiring multiple checks)
* Authz checks can be guaranteed by unit tests within the package that serves as the data source / source of truth, rather than larger scope integration tests
* It's harder to forget to write an authz check where one is necessary
* It's nicer for clients of lower-level code, because you don't have to fret about ensuring you've called the required authz checks.

The downside / reason why the existing PRs do not do this, I believe, boils down to efficiency. An authz check typically incurs at least 1 DB access, which can add up over a request cycle.

Proposal: enhance the `actor` package so that the `Actor` struct also includes authz information.
* An authz check can be performed at any layer. Once the check has been verified, a flag (perhaps a map entry in the actor context item) is set.
* All low-level functions that return sensitive data should enforce authz checks via the actor context item. This would include, for instance, all exported functions in the `db` package. Instead of just adding a comment asking the client to verify the necessary permissions, the function would explicitly require the appropriate flag in the actor context item be set.

Additional notes:
* Care must be taken that the actor context item can only be settable by trusted code (i.e., we can't just call `req.Context()` in external handlers. This should already hold, but is worth verifying.

**Comment by beyang** [comment]
@nicksnyder @slimsag @keegancsmith what are your thoughts on the above? It inflates the amount of info we store in the context, but we're already storing the actor there anyway and we might as well use it for authz, as well as authn. I'd like to stop the proliferation of `🚨SECURITY` requirements as I think it's only a matter of time before someone slips up and forgets to check permissions before calling a critical function.

**Comment by nicksnyder** [comment]
The high level proposal seems find to me; I do thing the main problem to solve is efficiency (i.e. prevent duplicate authn lookups in a single request). The other key part is making the API to check (and cache) permissions nice and easy to use.

**Comment by slimsag** [comment]
Sounds good to me 👍

One thing to consider is whether or not this will be attempted in full or as a slow migration over time. Switching over to this approach full-hog will be tricky to do correctly and safely I think.
