### ISSUE TITLE
Campaigns file link in diff view should expand diff

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#11385]
I found myself naturally clicking on this link to expand the diff view, but this link actually takes me to the file on Sourcegraph, which is not what I want. I feel like clicking here should expand the diff (the 99% intended action imo), and if users want to open the full file there should be a separate button to click somewhere in the diff or line gutter.

![Screen Shot 2020-06-09 at 11 37 54 AM](https://user-images.githubusercontent.com/754768/84186718-c99a0100-aa45-11ea-83ab-a42c282f41ab.png)

**Comment by eseliger** [comment]
Invalid with the new designs, closing
