### ISSUE TITLE
Repo autocompletion does not work

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#11405]
- **Sourcegraph version:** 
- **Platform information:** 

#### Steps to reproduce:

1. Go to https://sourcegraph.com
2. Type a repo filter
3. Hit Ctrl+Space to invoke autocompletion

#### Expected behavior:

- Should display autocompletion values
  - both regexes and non-regexes should work
- Autocompletion should popup automatically

#### Actual behavior:

No autocompletion values, needs to be invoked manually

![image](https://user-images.githubusercontent.com/10532611/84258675-9fb10f00-ab17-11ea-8c62-af6655ab680c.png)

![image](https://user-images.githubusercontent.com/10532611/84258717-af305800-ab17-11ea-9488-a55ff17fd736.png)

**Comment by lguychard** [comment]
![image](https://user-images.githubusercontent.com/1741180/96120469-d7c5c580-0eee-11eb-943a-888a90805cd3.png)

Can't reproduce, completions appear for both regex and non-regex, automatically without having to hit ctrl+enter.
