### ISSUE TITLE
Use Postgres intarray to store permissions `object_ids`

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#11400]
### Context

@mrnugget [on Slack](https://sourcegraph.slack.com/archives/CMMTWQQ49/p1591711834080300)

> I have to say, I’m really not happy with the application-level joins we now have to do due to authz. Everytime we want to do something, we have to find the repo ID for a patch/changeset/changesetjob (which sometimes requires another DB query) and then we have to send the repo ID through the db.Repos.Get layer, which uses the authzFilter. Only then can we do what we previously did. A lot of things we could do with a single database query (“update … where campaign_id = foo”) now requires 1+ queries to the database (and potentially to the code hosts!).

To which @tsenart [replied](https://sourcegraph.slack.com/archives/CMMTWQQ49/p1591717396083300?thread_ts=1591711834.080300&cid=CMMTWQQ49)

> It might be interesting to look into https://www.postgresql.org/docs/9.6/intarray.html to store the object_ids, and convert that to a roaring bitmap on the application side, rather than storing the byte form of the roaring bitmap. It even supports set operations. Wondering about storage impact, but performance should be good by reading the docs, given the right index.

### Success criteria

1. Campaigns permissions queries can be done in pure SQL without application level joins.
1. `authzFilter` can be replaced with pure SQL joins.
1. Storage needs don't grow disproportionately on large instances (say, 1M repos, 10k users)
1. Performance impact of pure SQL permissions joins is sub 25 ms.

#### Migrations
We need to write a SQL migration to change the data type of `object_ids` in `user_permissions` and `user_ids` in `repo_permissions` to intarray, as well as enabling the intarray extension with `CREATE EXTENSION intarray`. This assumes we just drop existing permissions, instead of migrating them which would require a complex application level migration. Depending on when we do this (i.e. many customers adopt it), we might need the application level migration.

#### Indexing

From the docs:

> Two GiST index operator classes are provided: gist__int_ops (used by default) is suitable for small- to medium-size data sets, while gist__intbig_ops uses a larger signature and is more suitable for indexing large data sets (i.e., columns containing a large number of distinct array values). The implementation uses an RD-tree data structure with built-in lossy compression.

Since we expect object_ids to contain up to as many repo ids as there are repos in an instance (e.g. 400k), we should ensure we use the `gist_intbig_ops` index operator class.

**Comment by tsenart** [comment]
@unknwon: Updated the issue body with some more detail. I think it'd be worth doing a 2 day spike on this soon.

**Comment by unknwon** [comment]
@tsenart: Thanks! Yep we should do this sooner rather than later regardless of campaigns permissions.

Especially not many customers using permissions currently (1 for background permissions syncing and 0 for explicit permissions APIs, cc @dadlerj to confirm). If any customer is using explicit permissions APIs then we can't simply drop (at least need to communicate with the customers). 

I would like to do the spike ASAP so adding to 3.17.

**Comment by tsenart** [comment]
@unknwon: If it turns out that the storage requirements are too big with this, as I suspect, we could consider normalizing this data. 8 bytes * 1 million (repos) * 10 thousand (users) = 80 GB.

A schema that could work for normalizing this data:

```sql

CREATE TABLE repo_permissions (
    user_id int REFERENCES users (id) NOT NULL,
    repo_id int REFERENCES repo (id) NOT NULL,
    perm text NOT NULL
)

-- A compound index to answer queries like:
--   SELECT repo_id FROM repo_permissions WHERE user_id = 123 AND perm IN ('READ', 'WRITE');
--   SELECT * FROM repo WHERE name LIKE '%pattern%' AND EXISTS (SELECT 1 FROM repo_permissions WHERE repo_id = repo.id AND user_id = 123 AND perm = 'READ')

CREATE INDEX repo_permissions_user_repos ON repo_permissions USING btree (repo_id, user_id, perm);

-- A compound index to answer queries like:
--   SELECT user_id FROM repo_permissions WHERE repo_id IN (1, 2, 3) AND perm IN ('READ', 'WRITE');
CREATE INDEX repo_permissions_repo_users ON repo_permissions USING btree (user_id, repo_id, perm);
```

**Comment by tsenart** [comment]
And for visualizing the query plans of this experiment, highly recommend @felixge's https://flame-explain.com/visualize/input

**Comment by dadlerj** [comment]
>Especially not many customers using permissions currently (1 for background permissions syncing and 0 for explicit permissions APIs, cc @dadlerj to confirm). If any customer is using explicit permissions APIs then we can't simply drop (at least need to communicate with the customers).

We actually have a good number of customers and prospects using permissions, though as of now I'm not aware of any using the explicit API. Off the top of my head, our list includes:

* https://app.hubspot.com/contacts/2762526/company/557475933
* https://app.hubspot.com/contacts/2762526/company/623971957
* https://app.hubspot.com/contacts/2762526/company/1749284052
* https://app.hubspot.com/contacts/2762526/company/1749029033
* https://app.hubspot.com/contacts/2762526/company/557476528
* https://app.hubspot.com/contacts/2762526/company/2942642504
* and maybe https://app.hubspot.com/contacts/2762526/deal/1644515057

And likely several more that I'm sure I'm missing. We also have 3-4 I can think of now who plan to use them but haven't enabled them yet (for various reasons).

**Comment by unknwon** [comment]
> @unknwon: If it turns out that the storage requirements are too big with this, as I suspect, we could consider normalizing this data. 8 bytes * 1 million (repos) * 10 thousand (users) = 80 GB.
> 
> A schema that could work for normalizing this data:
> 
> ```sql
> CREATE TABLE repo_permissions (
>     user_id int REFERENCES users (id) NOT NULL,
>     repo_id int REFERENCES repo (id) NOT NULL,
>     perm text NOT NULL
> )
> 
> -- A compound index to answer queries like:
> --   SELECT repo_id FROM repo_permissions WHERE user_id = 123 AND perm IN ('READ', 'WRITE');
> --   SELECT * FROM repo WHERE name LIKE '%pattern%' AND EXISTS (SELECT 1 FROM repo_permissions WHERE repo_id = repo.id AND user_id = 123 AND perm = 'READ')
> 
> CREATE INDEX repo_permissions_user_repos ON repo_permissions USING btree (repo_id, user_id, perm);
> 
> -- A compound index to answer queries like:
> --   SELECT user_id FROM repo_permissions WHERE repo_id IN (1, 2, 3) AND perm IN ('READ', 'WRITE');
> CREATE INDEX repo_permissions_repo_users ON repo_permissions USING btree (user_id, repo_id, perm);
> ```
> 
> So we would need a single table for this, rather than also needing a `user_permissions` table.

@tsenart: Not sure if I'm doing the math correctly, but from my calculation two approaches would end up similar usage of storage.

Assuming 10k users have access to 1 million repos.

- Using intarray (total 160 GB)
	- `repo_permissions`: 8 bytes * 1 million (repos) * 10 thousand (users) = 80 GB
	- `user_permissions`: 8 bytes * 1 million (repos) * 10 thousand (users) = 80 GB
- Normalize `repo_permissions`:
	- (8 + 8) bytes * 1 million (repos) * 10 thousand (users) = 160 GB

**Comment by unknwon** [comment]
> * [app.hubspot.com/contacts/2762526/company/557475933](https://app.hubspot.com/contacts/2762526/company/557475933)
> * [app.hubspot.com/contacts/2762526/company/623971957](https://app.hubspot.com/contacts/2762526/company/623971957)
> * [app.hubspot.com/contacts/2762526/company/1749284052](https://app.hubspot.com/contacts/2762526/company/1749284052)Toast [📝](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+archived%3Afalse+1749284052)
> * [app.hubspot.com/contacts/2762526/company/1749029033](https://app.hubspot.com/contacts/2762526/company/1749029033)
> * [app.hubspot.com/contacts/2762526/company/557476528](https://app.hubspot.com/contacts/2762526/company/557476528)OUTREACH [📝](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+archived%3Afalse+557476528)
> * [app.hubspot.com/contacts/2762526/company/2942642504](https://app.hubspot.com/contacts/2762526/company/2942642504)
> * and maybe [app.hubspot.com/contacts/2762526/deal/1644515057](https://app.hubspot.com/contacts/2762526/deal/1644515057)

I checked these customers with our **Server update check ping details (realtime)** (https://sourcegraph.looker.com/looks/436) and all of them have <500 users, most of them <200. So doesn't seem like we should be concerned about wiping out existing permissions and let background permissions syncing start over.

Unfortunately we don't have _number of repos_ included in the ping data, so can't verify that.

**Comment by unknwon** [comment]
Regarding indexing: I don't think we actually need (at least for now)? Or does it by indexing the intarray we can have performance gain for the following query?

```sql
SELECT id, name FROM repo
WHERE (SELECT object_ids FROM user_permissions WHERE user_id = 1) @> ARRAY[id];
```

```
Seq Scan on repo  (cost=1.04..26.10 rows=1 width=45) (actual time=0.028..0.028 rows=0 loops=1)
  Filter: ($0 @> ARRAY[id])
  Rows Removed by Filter: 5
  InitPlan 1 (returns $0)
    ->  Seq Scan on user_permissions  (cost=0.00..1.04 rows=1 width=32) (actual time=0.003..0.004 rows=1 loops=1)
          Filter: (user_id = 1)
          Rows Removed by Filter: 2
Planning Time: 0.305 ms
Execution Time: 0.058 ms
```

Also another property of GiST index which concerns me is that (https://www.postgresql.org/docs/9.6/textsearch-indexes.html):
>A GiST index is lossy, meaning that the index **might produce false matches**, and it is necessary to check the actual table row to eliminate such false matches.

**Comment by tsenart** [comment]
@unknwon: I had a session with @felixge nerding about this (thanks ❤️). Here some notes and recommendations.

### Normalized single `repo_permissions` table with BTREE indexing

Pros:
- Referential integrity is can be maintained by Postgres.
- Easier to work with from the application side (compared to two tables).
- Btree indexes make performant pagination easy (for paginated repo and user listing permissions queries).

Cons:
- Number of rows can grow very fast, specially on Sourcegraph cloud when we're multi-tenant.
- Storage requirements.
- Unclear how fast writing and updating a table with potentially tens billions of rows would be. We'd need to setup more realistic testing.

### De-normalized single `repo_permissions` table with GIN indexing

Turns out GIST index was the wrong thing to use and that GIN indexing has comparable performance with the normalized BTree index approach.

Pros:
- Order of magnitude less rows than the normalized approach.
- Easier to maintain compared to two tables (`repo_permissions` AND `user_permissions`)

Cons:
- Pagination of `repo_ids` is going to be slow because Postgres needs to always sort a large list of integers before returning the results.

### De-normalized `repo_permissions` and `user_permissions` with GIN indexing 

Pros:
- Still order of magnitude less rows than the normalized approach.
- Pagination of users and repo permissions queries is fast as long as we maintain `user_ids` and `repo_ids` columns sorted in the order we want.
- Smaller incremental change to the code we have already today compared to the other approaches.

Cons:
- We have to maintain `user_ids` and `repo_ids` columns sorted if we want fast pagination.
- Less simplifaction of the application code.

Open questions:
- Can we include the `permission` column in the GIN index (i.e. compound index)? We need this for it to be fast, or find an alternative:
  - Collapse `permission` and `user_ids` into a single value (i.e. `read:123`, `write:123`) and index an array of those.
  - Split `user_ids` into two nullable columns: `read_user_ids` and `write_user_ids`, etc.

**Comment by tsenart** [comment]
@unknwon: I think we should go with `De-normalized repo_permissions and user_permissions`.

**Comment by unknwon** [comment]
> @unknwon: I think we should go with `De-normalized repo_permissions and user_permissions`.

@tsenart: Did you get this conclusion with some new findings or just based on https://github.com/sourcegraph/sourcegraph/issues/11400#issuecomment-643611882?

**Comment by mrnugget** [comment]
What's the schema underlying `De-normalized repo_permissions and user_permissions`?

**Comment by tsenart** [comment]
> @tsenart: Did you get this conclusion with some new findings or just based on #11400 (comment)?

Just thought about it more based on the pros and cons I wrote above.

@mrnugget: The schema is the same we have today (2 tables), but instead of storing the marshaled roaring bitmap, we store an intarray and index it with a compound GIN index over (permission, (repo|object)_ids).

**Comment by tsenart** [comment]
@unknwon: We might not even need the GIN index on `user_id` and `object_ids`, given the two table approach, all queries we do are always targeted at a single row, which the existing btree index on (repo_id, permission) or (user_id, permission) would make fast. Then the membership test in the (sorted) list of `user_ids` or `repo_ids` is just a fast binary search for Postgres.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by mrnugget** [comment]
I was just about to reply to @unknwon on Slack but then realised that it's probably best to document this here.

Joe asked me:

> I would like to know how would [campaigns make use of a] `user_permissions` table if you’re able to check permissions directly using SQL. (e.g. `SELECT * FROM repo WHERE ARRAY[id] <@ (SELECT object_ids FROM user_permissions WHERE user_id = $1 AND permission = 'READ' AND object_type = 'repo')`).

The example is spot on, that’s exactly what we want to do: JOIN on `repo_id` against a table with permission data, so we get only back the rows to which the user has access.

But there are more usecases, so let me document them:

1. The `JOIN` example from above. Right now, without `JOIN`, we do: load all X (changesets, patches, ...), then load authz-filtered repositories where ID in X.RepoIDs, then skip all X where we don’t have access. Example: https://github.com/sourcegraph/sourcegraph/blob/24c734e703f5cdb0057524940950147cbd7ff713/enterprise/internal/campaigns/service.go#L334-L350
1. Variation on the `JOIN` example: we want to modify `changeset_jobs`, but only those the user has access to. So we need to load all `patches` with `changeset_jobs.patch_id`, then load all repositories, authz-filtered, then skip the `changeset_jobs` the user doesn't have access to after looking at which repos were filted. Example: https://github.com/sourcegraph/sourcegraph/blob/24c734e703f5cdb0057524940950147cbd7ff713/enterprise/internal/campaigns/service.go#L513-L536
1. Another variation on the `JOIN` example: we want to get `changeset_jobs.*` but  filter out the `changeset_jobs.error` for the repositories the user doesn't have access to. Before repo permissions it was a single `SELECT`, now we need to first get all repository IDs for `changeset_jobs` (by joining against `patches`, which have the `repo_id`), then filter those repo IDs by loading the authz-filtered repositories, then do the `SELECT` with a `where repo_id NOT IN (<filtered repos>)`. Example: https://github.com/sourcegraph/sourcegraph/blob/24c734e703f5cdb0057524940950147cbd7ff713/enterprise/internal/campaigns/service.go#L723-L757
1. Return an error if user doesn't have access to one repository involved in the operation. Right now we load all repositories, authz-filtered, check whether one repository was filtered out, if so, return an error. Example: https://github.com/sourcegraph/sourcegraph/blob/24c734e703f5cdb0057524940950147cbd7ff713/enterprise/internal/campaigns/service.go#L403-L416
1. Show a "hidden" variation of patch/changeset if the user doesn't have access to the repository. This is a `LEFT JOIN` or a sub-select: `SELECT patches.*, (SELECT ... from repo_permissions...) AS has_access` We don't want to filter out on the database level, but _hide_ information in the application level if we don't have access. Example: https://github.com/sourcegraph/sourcegraph/blob/24c734e703f5cdb0057524940950147cbd7ff713/enterprise/internal/campaigns/resolvers/changesets.go#L131-L167

**Comment by unknwon** [comment]
After discussed with @mrnugget and thought about the pure SQL authz flow more, I think these 5 use cases of campaigns can be satisfied if we have the full picture in our permissions tables.

To completely replace `authzFilter` function with pure SQL approach, we need to address following problems:
1. User and repo creation process become more expansive in scale, we need to update all rows in `user_permissions` table for every new unrestricted repository.
	- Using the term "unrestricted" here because (one real) customer could choose to allow access to all repositories on Sourcegraph regardless of their visibilities on chosen code host.
	- The "more" needs to be defined in practice, depends on the performance of Postgres to do array insertion/deletion of an element.
	- Alternatively, we could have a `repo_permissions_unrestricted` table.
1. Anonymous user visits, it is not a concern for campaigns but a general problem for authz. We could use `0` to indicate what repositories an anonymous user can see but it is no longer an easy on/off site config switch but has to update many rows in `repo_permissions` table (depends on how many repositories are unrestricted).
	- Could also be solved by using a `repo_permissions_unrestricted` table.
1. Removal/addition of authz providers would no longer take effect immediately because the background process takes time to process all rows (depends on how many repositories are associated with given authz providers).
1. We need another background worker to check external accounts for users. Currently we check-and-fetch missing external accounts on the fly inside `authzFilter` (specifically, for Bitbucket Server users).

They're not impossible to address, 1-3 are all rare events. I would like to do a spike on addressing these problems this week.

**Comment by tsenart** [comment]
> User and repo creation process become more expansive in scale, we need to update all rows in user_permissions table for every new unrestricted repository.

Can you explain why it is more expensive than before? I don't follow.

**Comment by unknwon** [comment]
> > User and repo creation process become more expansive in scale, we need to update all rows in user_permissions table for every new unrestricted repository.
> 
> Can you explain why it is more expensive than before? I don't follow.

If we store `user_ids` the in the same way we do for restricted (private) repositories, that means:
- When a user signs up, we need to do:
	1. `UPDATE repo_permissions SET user_ids = SORT(user_ids + X) WHERE repo_id IN (<IDs of all unrestricted repositories>)`, and (remaining question: how do we quickly find out _IDs of all unrestricted repositories_)
	2. `INSERT INTO user_permissions (user_id, object_ids, ...) VALUES (X, SORT(<IDs of all unrestricted repositories>))`
- When a new unrestricted repository is added, we need to do:
	1. `UPDATE user_permissions SET object_ids = SORT(object_ids + X) AND ...`, and 
	2. `INSERT INTO repo_permissions (repo_id, user_ids) VALUES (X, SORT(<IDs of all users>))`

This is "more expensive" with the assumption that unrestricted (public) repositories are common.

**Comment by tsenart** [comment]
Why do we need to store permissions for "unrestricted" repositories? I'd treat the absence of a row in `repo_permissions` matching a given repo as it being visibile / accessible for all users. Is that not good enough?

**Comment by unknwon** [comment]
> Why do we need to store permissions for "unrestricted" repositories? I'd treat the absence of a row in `repo_permissions` matching a given repo as it being visibile / accessible for all users. Is that not good enough?

Is it safe to assume "absence" as "unrestricted"? I don't think so, it could just be background worker hasn't kept up and could leak repositories to unauthorized users when these repositories are first added.

**Comment by tsenart** [comment]
You're right!

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
