### ISSUE TITLE
Error fetching hover from C language server for sourcegraph.com

### ISSUE THREAD

**Issue by Warchant** [sourcegraph/sourcegraph#1140]
- **Sourcegraph version:** sourcegraph.com
- **Platform information:** chrome extention v18.11.21.421

#### Steps to reproduce:

1. Go to https://github.com/kanaka/wac/blob/master/wa.c#L1906
2. Hover `interpret(m)`
3. See 
![image](https://user-images.githubusercontent.com/1867551/49056221-6fec3000-f22d-11e8-8e45-a928a60d51d3.png)

#### Expected behavior:
No error printed

#### Actual behavior:
Language server error

**Comment by Warchant** [comment]
UPD: it happens for all symbols in that repository

**Comment by sqs** [comment]
As a workaround, does it work if you disable https://sourcegraph.com/extensions/langserver/typescript and enable https://sourcegraph.com/extensions/felixfbecker/lang-typescript? (Must be signed in.)

Assigned to @felixfbecker to fix, or if the workaround works, then just expedite switching to the new TypeScript extension.

**Comment by Warchant** [comment]
For some reason, toggle button does not work. For enabled extension when I click disable, it does not react anyhow, for disabled (the one which is WIP) I click enable, it shows prompt with "OK"/"cancel", I press "OK" and nothing happens.

Here is what js console shows me:
![image](https://user-images.githubusercontent.com/1867551/49060461-3375ff80-f240-11e8-8588-299bcca5daad.png)

**Comment by sqs** [comment]
We are now supporting C using our basic-code-intel extension. See https://streamable.com/t7v2q for a video.

To use it (as demo'd in the video above):

1. Go to https://sourcegraph.com/extensions/sourcegraph/basic-code-intel and ensure the extension is enabled for you (requires signup)
1. In the command palette (<kbd>≡</kbd> icon in top right nav) on either Sourcegraph or GitHub, select **Basic code intel: Enable fuzzy hovers**.
1. Hover over tokens in https://github.com/kanaka/wac/blob/master/wa.c#L1906.

Let me know how this works for you, and please reopen if this is not an acceptable solution.
