### ISSUE TITLE
React Dev Tools says that sourcegraph.com uses development react build

### ISSUE THREAD

**Issue by Warchant** [sourcegraph/sourcegraph#1141]
React Developer Tools says that sourcegraph.com uses development React build. 

![image](https://user-images.githubusercontent.com/1867551/49065545-e0587880-f250-11e8-9894-4bc4887f2f26.png)

Is this something intentional?

I believe there should be a production build.

**Comment by felixfbecker** [comment]
We're also shipping sourcemaps suddenly, no idea why...

**Comment by Warchant** [comment]
Fixed
