### ISSUE TITLE
Alert if available file descriptors is low

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#11420]
A common issue in docker compose deployments is file descriptors being configured incorrectly, e.g. see https://sourcegraph.atlassian.net/browse/SG-231

We should alert if available file descriptors are < 262144 and update docker compose installation docs to reflect this requirement.

**Comment by bobheadxi** [comment]
duplicate of https://github.com/sourcegraph/sourcegraph/issues/11420
