### ISSUE TITLE
Search with explicit repo: filter for not-cloned/cleaned-up repo returns neither "repo not found" nor triggers a clone, but just returns 0 results

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#11431]
In a local dev instance, I often get no results for commit searches that I know definitely should return a result. E.g. https://sourcegraph.test/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+type:commit+before:2020-03-18T00:00:00%2B01:00+count:1&patternType=literal

![image](https://user-images.githubusercontent.com/10532611/84381190-f3d7f400-abe8-11ea-9420-c9a3221925ee.png)

This is a problem because it breaks code insights:

![image](https://user-images.githubusercontent.com/10532611/84385455-e114ed80-abef-11ea-889e-b690e93d01dd.png)

**Comment by felixfbecker** [comment]
Ah, it seems like for some reason the repo got pruned from my Sourcegraph instance (no idea why) and had to be recloned, and a search even with an explicit repo filter doesn't seem to trigger a clone but will just return no results.

**Comment by felixfbecker** [comment]
This just happened again: I just `git pull`ed and suddenly the repo is gone and needs to be recloned

![image](https://user-images.githubusercontent.com/10532611/84393669-263f1c80-abfc-11ea-860f-b2cb69064b5f.png)

**Comment by felixfbecker** [comment]
Just happened again without any git pull, restart etc

**Comment by keegancsmith** [comment]
Is this due to 10% free logic? Only an issue in dev.

**Comment by felixfbecker** [comment]
Yeah I got help on Slack and that seems to be the root cause. The only thing left is: Shouldn't a search inside a specific repository (fully qualified `repo:` filter) trigger a repo clone? Or at least return the "No repos matched your filter" error? It seems the search considers the repo "there, but empty", which seems wrong

**Comment by tsenart** [comment]
@camdencheek: Assigning to you for triage since this is related to diff and commit search.

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by camdencheek** [comment]
Given that this is 2 years old, and it sounds like it only happened in dev, I think this should be closed. However, I don't this would be search product anyways. I've never touched any of the repo-cloning logic, which appears to be what was causing issues here.
