### ISSUE TITLE
Add browser argument to BrowserExtensionConnectedToServer event

### ISSUE THREAD

**Issue by ebrodymoore** [sourcegraph/sourcegraph#11447]
Now that we're sending browser extension data to Sourcegraph.com, could we add which browser it's coming from?

To me, the most logical path would be to add `browser: Chrome` (or similar) as an argument to the event [BrowserExtensionConnectedToServer](https://sourcegraph.sgdev.org/sourcegraph/sourcegraph@7f2ca81319b40d59c3634959f004461904e53a47/-/blob/web/src/tracking/eventLogger.tsx#L28). Does that seem like the best route for this?

I'm only interested in this data for Sourcegraph.com, but it would give us the option to add to pings at a later date. 

@lguychard tagging you on this because it'd be in the web team domain (pun intended)

**Comment by ebrodymoore** [comment]
@lguychard could we get this into 3.18 also to understand the breakdown of extension by browser?

**Comment by rrhyne** [comment]
Suggestion:

#chrome_ext and #firefox_ext

**Comment by lguychard** [comment]
This is now implemented.
