### ISSUE TITLE
Rename default branch to `main`

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#11464]
We are going to do this for reasons mentioned in this thread: https://twitter.com/mislav/status/1270388510684598272

More context in https://github.com/sourcegraph/sourcegraph/issues/11389#issuecomment-642877899

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by keegancsmith** [comment]
Aah sorry forgot to finish up my PR after I went on vacation. Will tackle early on in 3.19.
