### ISSUE TITLE
Nav links have bad iconography

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#11461]
Action items in the navbar should give a good idea of what awaits the user behind each item. As a user, I'm less likely to click on an item to explore what's behind it if I'm confused about what it means. We should encourage exploring what's behind nav bar items to drive adoption of features. 
Iconography can be an important part in this, stimulating curiosity and providing analogies for what the user can find behind an item. On the other hand, bad iconography can _cause_ confusion and _reduce_ the likelihood of exploratory clicks. This doesn't just affect the nav item with the unclear icon - if the nav bar overall is confusing/unclear, a user is less likely to touch something in that area.

Because I am adding another member (insights) to the nav bar, I would like to clean our nav links up and make sure they have meaningful icons.

Let's go through the items in our nav bar.

![image](https://user-images.githubusercontent.com/10532611/84499243-809ab480-acb2-11ea-8ba7-06045b437bdb.png)

- [x] **Explore**. Used to have no icon at all, which makes the nav bar overall confusing. I just fixed this yesterday by simply giving it a compass icon 🧭. Also considered binoculars, but compass seemed more appropriate for "exploration".
- [x] **Insights**. This is a new addition, I think anything with charts 📊  gives a pretty good idea of what the feature is mainly about, but always open for suggestions.
- [x] **Campaigns**. This one is extremely ambiguous. What I see is a square with sparkles, and I struggle to connect that with anything of what campaigns is about (large-scale code changes? tracking code changes?). Personally I would suggest some analogy to real-world tools/vehicles that help with "large-scale changes", like a crane 🏗  (or other construction site vehicle, but crane is arguably the vehicle of the _largest scale_). MDI has an icon for a crane.  Focusing on the tracking would also be possible (the first version used a burndown chart icon), but I'd be worried that anything chart-related would now not be clearly distinguished from code insights. @sourcegraph/campaigns @rrhyne WDYT?
- [x] **Command palette.** This is extremely generic, and we've gotten a lot of feedback that it is confusing. A hamburger menu is the most lazy icon ever. All it conveys is a "list", but that applies to almost everything (this would be just as applicable to the user menu). It should convey something about the _command_ part, that you can run extension _commands_ with this. I'd suggest one of the MDI terminal icons:
  ![image](https://user-images.githubusercontent.com/10532611/84502086-fce3c680-acb7-11ea-9414-9d551bc2592d.png) ![image](https://user-images.githubusercontent.com/10532611/84501631-19cbca00-acb7-11ea-8027-1aae7399e8ab.png)
  because that is the closest analogy to "running commands" I can think of. We already use this icon for the API console, but I think it should be fine because those are in clearly-distinguished different contexts.
  - In code host contexts, we may want to consider branding this instead to be a Sourcegraph icon, to make that connection clearer?
- [x] **User Menu.** Some things in here are not strictly user-related, but this seems fine as this is a common UI pattern. Only annoyance is that when the user has no avatar, this shows the user name without an icon instead, which is less clear of a pattern. I would suggest a generic MDI user icon in that case:
 
  ![image](https://user-images.githubusercontent.com/10532611/84501678-336d1180-acb7-11ea-9d92-7ed810949a97.png)

All icons of the icon library we use can be found here: https://materialdesignicons.com/

**Comment by rrhyne** [comment]
Campaigns: I agree chart is a bad signal. Any icon chosen here is going to only have meaning to the user if it appears with a label. Crane, File with star, etc. are very subjective. Personally, I recommend no changes here until we can attempt to address with a custom icon. 

Command palette: a custom form field icon with a command prompt would be best, but to move this along, I would choose the first of the two options you provided to avoid duplication with the API command icon.

User icon: I agree with the user icon, unless users often log in under multiple accounts, in which case some signal about which account they are logged into is important.

**Comment by felixfbecker** [comment]
Another thing to consider: When not signed in, there are completely different nav links.

![image](https://user-images.githubusercontent.com/10532611/84576746-6a2a5100-adb7-11ea-8985-6e4fca658142.png)

**Comment by chrispine** [comment]
Our ticket for the Campaigns icon is #14740, which should be finished soon.

**Comment by LawnGnome** [comment]
> Our ticket for the Campaigns icon is #14740, which should be finished soon.

The new campaigns icon has now been merged. :100:
