### ISSUE TITLE
Browser extension appears to be disabled on sourcegraph/sourcegraph

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#1146]
Repro: visit https://github.com/sourcegraph/sourcegraph/blob/15d2613d75c25d6d960458be3b9690953f3de17a/cmd/frontend/graphqlbackend/generic_search.go

**Comment by ijsnow** [comment]
The browser extension seems to be trying to resolve the revision at the exact commit from the link but is getting `null` back from the API (i.e. 404 for that specific revision). Is this commit a part of a PR that somehow isn't in history anymore but GH has saved for viewing purposes?

**Comment by ijsnow** [comment]
Seems to be the same issue as https://github.com/sourcegraph/sourcegraph/issues/1147 so closing this.
