### ISSUE TITLE
Repository language query not returning correct results in a timely fashion

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#11466]
Original Slack thread: https://sourcegraph.slack.com/archives/CTGBWCKM0/p1591986011002500

Customer is issuing the following GraphQL query:
```
query ListLanguages($repoName: String!) {
  repository(name: $repoName) {
    language
    commit(rev: "HEAD") {
      languages
    }
  }
}
```

Their security team relies on this endpoint to be notified which languages are represented in the repository. The customer has `USE_ENHANCED_LANGUAGE_DETECTION=false`. On a lot of repositories, the wrong languages are returned, including their large Go mono-repo. The endpoint returns this (note the ordering is alphabetical with caps first):
```
{
  "data": {
    "repository": {
      "language": "AGS Script",
      "commit": {
        "languages": [
          "AGS Script",
          "AMPL",
          "ANTLR",
          "Assembly",
          "Awk",
          "C",
          "C++",
          "CSS",
          "CSV",
          ...
          "TeX",
          "Text",
          "Thrift",
          "Unity3D Asset",
          "Unix Assembly",
          "XML",
          "YAML",
          "YANG",
          "reStructuredText"
        ]
      }
    }
  }
}
```

Invoking `enry` (which is the library/tool we use under the hood) on a local checkout yields this (note the order is most common language first):
```
./enry ./path/to/repo -mode=oneline
<redacted>%	Go
<redacted>%	Python
<redacted>%	Thrift
<redacted>%	JavaScript
<redacted>%	Shell
<redacted>%	HTML
<redacted>%	TSQL
<redacted>%	CSS
<redacted>%	Makefile
<redacted>%	C
....
<redacted>%	PLSQL
```

Setting `USE_ENHANCED_LANGUAGE_DETECTION=true` fixes the languages detected for other repositories, but causes the request to timeout for the Go mono repo.

I have repro'd this on a local dev server on the code from github.com/sourcegraph/sourcegraph.

Customer notes that this was working earlier, but it is possible this has been broken since they set `USE_ENHANCED_LANGUAGE_DETECTION=false` in March 2020.

**Comment by aisbaa** [comment]
Hei, is there a release I can test?
