### ISSUE TITLE
Code insights blog post content

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#11497]
Show off screenshots of code insights and ask for questions readers would like to answer about their code

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
