### ISSUE TITLE
Don't put campaigns marketing page on dotcom behind auth

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#11501]
Currently, the marketing content on dotcom is hidden behind authentication, but we'd like to link potential users to it and don't want them to sign up first.

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
