### ISSUE TITLE
Wireframes final review

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#11513]
Please review the final wireframes and accompanying prototype to ensure the designs met  the following [RFC 159](https://docs.google.com/document/d/16ANfXRaJmsiYCPZSPlyAc8Zu-sY6plO6_eRDZ09C_SY/edit#) objectives:

- Allows users to:
  - Select a repository group which contains code familiar to them
    - Search that repository group with highly relevant queries
  - See interesting example queries 
  - Search code in a specific language

There are two changes from the last requested preview to review and approve:
- Repository groups have been moved from /search to /repository-group/{groupname}. This is to clearly denote they are not a search, they are a webpage
- The search bar was removed from the top of the repository group page (where it sat as if it were a search result) to the centered homepage position. This keeps the search bar from jumping from top to middle and back during common flows through this content.

### Wireframes:
https://www.figma.com/file/QS14QhHzvKwY4lD2U2cOzG/RFC-159-Wireframes?node-id=319%3A1745

### Prototype:
https://www.figma.com/proto/QS14QhHzvKwY4lD2U2cOzG/RFC-159-Wireframes?node-id=338%3A963&viewport=68%2C533%2C0.125&scaling=min-zoom

Please leave comments in the figma if you find issues that require resolution before the project moves to the next phase.

**Comment by attfarhan** [comment]
LGTM

**Comment by aileenrose** [comment]
On the repository group page layout, besides the logomark by the search bar and the logo on the browser tab, could we have the logo on the upper left?

**Comment by rrhyne** [comment]
@aileenrose, great catch I've added it there as requested. 

Not having a logo here is a consequence of my removal of the search bar at the top of the page.  With that change, I am trying to keep the location of that bar from bouncing around between the top and the center and from being duplicated on the page, which I think is very confusing. 

A few options: 

1) remove the search bar from the centered position on all but the home page and add it back to the top
2) Leave the search bar centered on repository group pages and add the logo to the top left
3) Duplicate the search bar

I prefer option 2 as it meets @sqs 's request to center the search bar on the page and it brands the page strongly which will help orient users coming from search and social links.

**Comment by sqs** [comment]
I don't think we need a Sourcegraph logo. It would reduce the feeling of "this is a search tailored JUST FOR my project" and it would possibly increase the feeling of "thank you, Sourcegraph, for providing this" but that is vaguer. If the search is really good, they'll come back, and they will eventually realize it's Sourcegraph.

**Comment by christinaforney** [comment]
I don't want the Sourcegraph logo to over power the logo/image for the group. What about keeping it small in the top left where our logo usually is, this allows us to keep brand recognition without taking away from this page feeling tailored to JUST my project. 

Part of our goal is brand recognition as well, so keeping it small but lower in visual hierarchy seems like a good compromise.

Otherwise, discussed the designs with @rrhyne and @poojaj-tech and have agreement on what needs to happen for the MVP design to get out ASAP. Rob will be working on visual design for these.

**Comment by rrhyne** [comment]
I agree with @christinaforney and will add that if the logo was not present, a user inbound from a referral such as a search result or a social link would never see the company name. This is because search results only contain a small logo symbol.

I've updated the wireframes with a version that reduces the size of the logo as per Christina's comment.

**Comment by lguychard** [comment]
Wireframes and prototype look good to me!

**Comment by sqs** [comment]
LGTM
