### ISSUE TITLE
Direct admins to Grafana when critical alerts have fired recently

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#11517]
A banner alert, similar to the upgrade notifications, should appear if a critical alert is firing on the instance.

> 5 critical alerts firing in the past 30m [view alerts](url-to-grafana)

**Comment by bobheadxi** [comment]
We'll need SDK support for the Alerts API - I've opened a PR upstream: https://github.com/grafana-tools/sdk/pull/91

**Comment by bobheadxi** [comment]
Nevermind my previous comment - with #11832, we'll be able to use [Alertmanager's API](https://github.com/prometheus/alertmanager/blob/master/api/v2/openapi.yaml#L130) directly, or make a Prometheus query, and render that in the frontend

**Comment by bobheadxi** [comment]
@slimsag @pecigonzalo adding this back to 3.18 because all my other 3.18 issues are in-progress and awaiting review or pending some decision-making, and I had some time today :)
