### ISSUE TITLE
Puppet file syntax highlight

### ISSUE THREAD

**Issue by aisbaa** [sourcegraph/sourcegraph#11522]
#### Feature request description

It would be amazing to have puppet file syntax highlighting. 

#### Additional context

Here's an example: https://github.com/jordansissel/puppet-examples/blob/master/disks-and-directories/manifests/site.pp

**Comment by rvantonder** [comment]
And done: https://sourcegraph.com/github.com/jordansissel/puppet-examples@master/-/blob/disks-and-directories/manifests/site.pp
