### ISSUE TITLE
Build initial set of MVP repository group pages

### ISSUE THREAD

**Issue by christinaforney** [sourcegraph/sourcegraph#11538]
Build the content for repository group pages from #11539 using the template from #11537

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by poojaj-tech** [comment]
Closing with pages live on search homepage now.
