### ISSUE TITLE
cursor in Monaco has a blue box at the top

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#11556]
- **Sourcegraph version:** `master`/`3.17`
- **Platform information:** Safari

In Safari the cursor in every Monaco instance has a blue box at the top that doesn't disappear, even when the cursor is blinking:

![image](https://user-images.githubusercontent.com/1185253/84877522-e9a27380-b088-11ea-8596-f047c45cdc5e.png)
![image (1)](https://user-images.githubusercontent.com/1185253/84877534-eb6c3700-b088-11ea-9359-3e4a0e07c0e5.png)

**Comment by fkling** [comment]
Doesn't seem to be an issue anymore.
