### ISSUE TITLE
Update version contexts via API

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#11569]
Several of our early version context users are hoping to use automation to keep their contexts updated. Using our API to edit the site configuration, however, is not pleasant...

I'm honestly not sure what a better solution is 😕 . Migrating this state to Postgres and a web UI wouldn't be ideal either. I'm open to any suggestions for how (if?) we handle this elsewhere!

Requested by:
* https://app.hubspot.com/contacts/2762526/company/768958891 (more urgent)
* https://app.hubspot.com/contacts/2762526/company/693777200 (less urgent)

We have discussed this previously with them. When they asked me the following question (see https://sourcegraph.slack.com/archives/CTJCMDCCS/p1592413499290500):

>Also I am not sure but did you send us how to get the site config from the API? And how to make changes to the version context via API? Would be really helpful

I replied with:

>Yes, thanks for the patience!
>
>Because version contexts are stored in the configuration, you have two ways to do this. Unfortunately, in both instances, it does require modifying the configuration JSON document. I’ve filed a request for our team to find a way to make this easier.
>
>First, if you are [loading your site configuration from disk](https://docs.sourcegraph.com/admin/config/advanced_config_file), then you’d only need to change that file. Some customers check their configuration into version control, so issuing a pull request against it would be one option.
>
>If not, then it is possible to change the configuration via API. The query to fetch the config is the following (try running this at the /api/console page on your own instance to see what it looks like):

```
query Site {
  site {
    configuration {
      id
      effectiveContents
    }
  }
}
```

And the query to update it is:
```
mutation UpdateSiteConfiguration($lastID: Int!, $input: String!) {
                updateSiteConfiguration(lastID: $lastID, input: $input)
            }
```

>(where the `$lastID` variable is the id from the previous API call, and the `$input` variable is the new configuration).
>
>I know this is a bit messy — that’s why I started with editing a file on disk. I’m happy to help if you run into any trouble making these API calls — please just let me know!

**Comment by lguychard** [comment]
We no longer have version contexts, but search contexts can be updated via API!
