### ISSUE TITLE
campaigns: GitHub GraphQL API implicitly depends on a post-2020-01-01 version

### ISSUE THREAD

**Issue by LawnGnome** [sourcegraph/sourcegraph#11565]
Creating changesets can fail on GitHub when Sourcegraph is talking to a version of GitHub (presumably Enterprise) that pre-dates the [2020-01-01 changes to the GraphQL API](https://developer.github.com/v4/breaking_changes/#changes-scheduled-for-2020-01-01), specifically because the `assignee` field doesn't exist.

If we can detect this, we could likely use the old `user` field as a stopgap.

**Comment by dadlerj** [comment]
Reported by https://app.hubspot.com/contacts/2762526/company/557692805

**Comment by eseliger** [comment]
This is handled down to v2.20 and documented, so closing.
