### ISSUE TITLE
Show search scopes ASAP (before the search completes)

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#11564]
Given I use Sourcegraph.com for most of my searches, I often type a term I want to search into the URL bar, then immediately click on my "Sourcegraph" search scope to narrow my search to our repo. This saves me from having to type `repo:github.com/sourcegraph/sourcegraph` along with every query...

However, the list of search scopes doesn't appear until the search returns. So I generally have to wait a half-second or more for initial results to appear.

I'm aware that an extra second or two of of waiting isn't a huge problem :) but it also occurs to me that there's no reason for the scopes list to not be rendered sooner (and on slower searches, it actually can be a bit painful). 

If I'm running into this, I figured others may be as well.

**Comment by lguychard** [comment]
Closing as the results redesign fixed this!
