### ISSUE TITLE
github permissions regression test fails

### ISSUE THREAD

**Issue by uwedeportivo** [sourcegraph/sourcegraph#11561]
- **Sourcegraph version: 3.17 single server docker image** 
- **Platform information: Docker for Mac** 

#### Steps to reproduce:

1. Run the instance and set up environment for regression test
2. Run this test: 

```
yarn run test:regression:external-services -f 'External services permissions: GitHub'
```

https://github.com/sourcegraph/sourcegraph/blob/master/web/src/regression/external-services.test.ts#L263

(if you don't want to set up the regression test environment as described here: https://github.com/sourcegraph/sourcegraph/blob/master/web/src/regression/README.md#L1, you can do the test by hand. it's not that many steps)

#### Expected behavior:

test should pass

#### Actual behavior:

test fails, but if you turn off background permission sync, it passes

```
 "permissions.backgroundSync": {
    "enabled": false
  }
```

**Comment by unknwon** [comment]
@uwedeportivo and I paired on this and found the problem is that we store database ID (integer) for GitHub in `user_external_accounts` table but background permissions syncing uses GraphQL node ID (string).
