### ISSUE TITLE
gqltest: enable in CI on `main` branch

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#11579]
~~Wait until https://github.com/sourcegraph/sourcegraph/issues/11762 is closed.~~

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
