### ISSUE TITLE
Enforcing product tiers 

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#11577]
RFC 167: https://docs.google.com/document/d/1XozQ4JINJqirdaG-XqGtboT2-PlIXPyBn6EwV7Q3pWI/edit

TODOs:
- [x] What information we could extract from existing licenses, including tags, issue date.
- [x] What should we do to tolerate future product tiers changes.

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by unknwon** [comment]
Have created issues for each individual task thus closing this one.
