### ISSUE TITLE
Support GitLab in campaigns

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#11586]
Steps:

- [x] Update `src-cli` to extend [this check](https://github.com/sourcegraph/src-cli/blob/master/cmd/src/actions_exec.go#L588-L591)
- [x] Extend [`SupportedExternalServices`](https://github.com/sourcegraph/sourcegraph/blob/ac2d98d352e5f2c8c62b2439545c587e32b19a6e/internal/campaigns/types.go#L27-L30)
- [x] Implement the [`ChangesetSource`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@ac2d98d352e5f2c8c62b2439545c587e32b19a6e/-/blob/cmd/repo-updater/repos/sources.go#L101:6) interface on `repos.GitlabSource` (see `repos.GitHubSource` and `repos.BitbucketServerSource` as examples)
- [x] Add gitlab support to the [`workers.go`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@ac2d98d/-/blob/enterprise/internal/campaigns/workers.go#L233:4) so that changesets can be created by us.
- [x] Handle `gitlab.MergeRequests` in the [switch statements in `campaigns/types.go`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24%40ac2d98d+.*%5C%28type%5C%29%5Cs%7B%24+lang:go+f:campaigns/types.go&patternType=regexp&case=yes)

At this point, we should be able to create changesets and display them (but their `External*` fields should be empty).

Next step is to support `ChangesetEvents`:

- [x] Load the events in the `ChangesetSource`
- [x] Support `gitlab` in the [`ChangesetEvents`](https://github.com/sourcegraph/sourcegraph/blob/2f6716f0e9c4a1b48846ea3decfbb49cc3137313/internal/campaigns/types.go#L663-L1439)
- [x] Handle `gitlab` metadata in the [state computation switch statements](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24%40ac2d98d+.*%5C%28type%5C%29%5Cs%7B%24+lang:go+f:state.go&patternType=regexp&case=yes)
- [x] Handle `gitlab` events in the [`computeHistory` function](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@ac2d98d352e5f2c8c62b2439545c587e32b19a6e/-/blob/enterprise/internal/campaigns/changeset_history.go#L32) (which is used for the burndown chart and the state computation above)
- [ ] Last: [add webhook support](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24%40ac2d98d+switch+:%5B_%5D+:%3D+:%5B_%5D.%28type%29+lang:go+f:webhooks.go&patternType=structural&case=yes)

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by mrnugget** [comment]
@LawnGnome Do we want to create a separate ticket to track webhook support?

**Comment by LawnGnome** [comment]
> @LawnGnome Do we want to create a separate ticket to track webhook support?

#12171

**Comment by mrnugget** [comment]
@LawnGnome Something that came to my mind this morning: do we have any integration-y tests for GitLab? As far as I can tell in #11757 the GitLab client is mocked, so we don't record request/response in cassettes.

In our resolver tests we do have [this one here, `TestCampaigns`](https://github.com/sourcegraph/sourcegraph/blob/870221e07c86de5e67d3900a804ce6547b595fd3/enterprise/internal/campaigns/resolvers/resolver_test.go#L247-L338) that tracks a Bitbucket Server and a GitHub changeset and makes sure that the changeset resolvers work. But in #11675 I already ripped out that part, because the `createChangesets` mutation won't exist anymore.

I'm thinking that maybe we should extract that part of the test and create a `TestChangesetResolver` test that uses VCR-recorded and the rest of our stack to make sure that a fully-synced changeset from GH/GL/BBS works with the `ChangesetResolver`. What do you think?

The other test that I thought about it is this one: https://github.com/sourcegraph/sourcegraph/blob/870221e07c86de5e67d3900a804ce6547b595fd3/enterprise/internal/campaigns/resolvers/resolver_test.go#L651

That test currently only tests GitHub changesets on an integration-y level, but since `changesetCountsOverTime`, which is used for the burndown chart, has been tricky in the past, I wonder whether we shouldn't extend that.

And now to sum all of this up: I think we should have a test somewhere that makes sure that the flow of `actual-data-from-gitLab->Sourcegraph->Sourcegraph-GraphQL-API` works, but I leave it up to you to decide where/how/when to add this 😄
