### ISSUE TITLE
alerting for when external service connections are failing

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#11595]
The Repo Updater dashboard should alert when external service connections are failing (e.g. if the access token to github/gitlab is bad or expired).

Requested by https://app.hubspot.com/contacts/2762526/company/693777200/ https://sourcegraph.slack.com/archives/C011899KB6U/p1592509078273100

**Comment by pecigonzalo** [comment]
This is likely going to be caught by the repo-sync time. Closing for the time being.
