### ISSUE TITLE
Add structural search help message

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#11593]
- **Sourcegraph version: All versions
- **Platform information:** cloud
#### Steps to reproduce:

1. Search useState(:[arg]) or any structural search. 
2. Forget to click the structural search button.

#### Expected behavior:
See a help message under 'No search results' message that reads:

 "It looks like you are using structural search . You must enable structural search by clicking the [ ] button to use those language features."  

Alternatively, (depending on complexity and how accurate we could be), detect structural search in a query, and automatically apply the button. 

#### Actual behavior:

I see no search results and wonder if my syntax is wrong.

**Comment by rvantonder** [comment]
Sounds good to me, this is a backend alert I can add. I'm going to CC the others who might be interested in this UX comment. Potentially this could be surfaced alternatively or additionally as a squiggle underneath the query pattern with on-hover suggestion to turn on structural search later.

**Comment by rvantonder** [comment]
CC @lguychard @attfarhan @christinaforney

**Comment by attfarhan** [comment]
SGTM 👍
