### ISSUE TITLE
Cannot expand/collapse all results from a single file

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#11596]
Reported by https://app.hubspot.com/contacts/2762526/company/693777200

Reproducible on sourcegraph.com — run any search, you can still collapse any results, but the "expand all" and "collapse all" buttons don't work.

Notes from conversation below:
- The expand and collapse all buttons _do_ work. The customer may have been confused because they expected _all_ results to be collapsed or expanded. Rather, we only expand/collapse past 10 line matches. The customer may be requesting to collapse and expand all of the results.

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by attfarhan** [comment]
This seems to work fine for me, e.g. try on https://sourcegraph.com/search?q=test+repo:0i0/nonky&patternType=literal. @dadlerj do you have another repro that still causes issues? Otherwise will close.

**Comment by dadlerj** [comment]
Hmm not any more :/ I think it's fine to close. I'm having trouble remembering the specific convo, though, and wondering if this was just confusion about what can/can't be expanded (we _only_ allow expanding/hiding results once it's greater than some number, correct? Perhaps we rename this to be "can't hide/expand all results from a single file" and leave it as a product request.

**Comment by attfarhan** [comment]
> we only allow expanding/hiding results once it's greater than some number, correct  

Yes that's correct.

> Perhaps we rename this to be "can't hide/expand all results from a single file" and leave it as a product request.

👍

**Comment by dadlerj** [comment]
Requested by https://app.hubspot.com/contacts/2762526/company/2428850551

**Comment by malomarrec** [comment]
Tagging similar issue in #20158 to feed into prioritisation work.

**Comment by fkling** [comment]
Doesn't seem to be a problem anymore.
