### ISSUE TITLE
Add docs on backing up data/migrating to a new instance

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#11600]
Requested by: 
* https://app.hubspot.com/contacts/2762526/company/814799425
* https://app.hubspot.com/contacts/2762526/company/554275594

We don't have a single source of truth in our documentation on how to back up a Sourcegraph instance's data, and in a similar vein, to migrate data to a new deployment.

There are a giant number of factors/inputs that can complicate this — if a customer is using config files loaded from disk; if they're using external databases; etc. If they're on the single Docker image deployment vs. Kubernetes. If they're willing to re-clone/re-index all of their code and their LSIF data or not. 

When I respond to customers, it follows the following structure:

* What _types_ of data does Sourcegraph store, and where:
  * Configuration/global settings/external service config data (stored on disk or in Postgres)
  * Persistent data stored in Postgres (almost all of Sourcegraph's important state — users, repo lists, user settings, saved searches, access tokens, usage statistics, survey results, etc.)
  * Ephemeral data stored on disk, in SQLite, and in Redis (repo clones, indexes, LSIF dumps, sessions, etc.)
* Options for exporting/backing up Postgres, e.g.
  * Copy the ~/.sourcegraph/data/postgres directory on the host machine (single Docker image)
  * Copy/back up the entire volume (Kubernetes)
  * Use `sourcegraph-server-gen` (no longer available via documentation at https://docs.sourcegraph.com/admin/install/kubernetes/update#updating-blue-green-deployments... Instead, see https://sourcegraph.slack.com/archives/CTN0ZBETE/p1590106666323700?thread_ts=1590015918.321500&cid=CTN0ZBETE from @slimsag )
  * Manually run `pg_dump`?

Anything else to add here?

**Comment by daxmc99** [comment]
See also terraform migration [google doc](https://docs.google.com/document/d/1ATRCW9xUW6aEldpnm2QPCuJqRgdGxEgKU13c3KQv2mQ/edit?usp=sharing). 
Some surprises off the top of my head:

1. Redis
2. Minio
3. Depending on size, gitserver & index servers

**Comment by DaedalusG** [comment]
We should consider having independent docs covering each type of deployment migration:
single > single
single > compose ✅ 
single > k8s
compose > compose
compose > single (maybe not this one?)
compose > k8s
k8s > k8s (I believe @topebali created a nice [doc](https://handbook.sourcegraph.com/departments/support/process/enablement/k8-migration) on this for internal use) ✅ 
k8s > compose
k8s > single (again maybe not this one?) 

A general migrations theory doc, with links to procedural migration docs (noted above) would be awesome to have here. It may seem repetitious but I think our users would appreciate it. 

Note also that the old Sourcegraph Server Gen script automated some of the dumps including redis.
