### ISSUE TITLE
Current version shown as 0.0.0+dev after installing 3.17.0

### ISSUE THREAD

**Issue by lalau** [sourcegraph/sourcegraph#11618]
- **Sourcegraph version:** 3.17.0
- **Platform information:** 

#### Steps to reproduce:

1. Fresh install 3.17.0 using the docker image
> docker run -d --publish 80:7080 --publish 127.0.0.1:3370:3370 --restart unless-stopped --volume /home/ec2-user/.sourcegraph/config:/etc/sourcegraph --volume /home/ec2-user/.sourcegraph/data:/var/opt/sourcegraph --volume /var/run/docker.sock:/var/run/docker.sock sourcegraph/server:3.17.0

2. Navigate to the updates page

#### Expected behavior:

Shows version 3.17.0.
No "An update is available" banner shows.

#### Actual behavior:

Shows version 0.0.0+dev.
"An update is available" banner shows.

![Screen Shot 2020-06-22 at 2 08 18 AM](https://user-images.githubusercontent.com/236573/85269799-4311f600-b42d-11ea-89f0-3e6a0dda4823.png)

**Comment by unknwon** [comment]
@daxmc99 Do you still have context around this? I'm also experiencing this on my personal instance running `sourcegraph/server:insiders` Docker image.

**Comment by daxmc99** [comment]
This fixed it for https://github.com/sourcegraph/sourcegraph/pull/11633 the K8s version but it needs to be ported to the single container.
