### ISSUE TITLE
Write RFC to enable additional build steps in auto-indexer

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#11626]
Some repositories will not simply be able to run lsif-* alone in order to index their code. We need a way to configure some pre-build steps (code generation, dependency fetching, etc) in order to run the indexers.

Write an RFC to detail how to configure this, and what (performance, security) issues that will bring to the auto indexer process.

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by efritz** [comment]
First draft available in https://docs.google.com/document/d/1NPQs1s814LZjNXjPuavqC1N7hZR192DNtmSBmAeH9UY/edit#heading=h.trqab8y0kufp.
