### ISSUE TITLE
Write RFC to scale the bundle manager

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#11634]
This will need to happen sooner than later. Our bundle manager service is currently designed to scale horizontally, but for technical reasons we cannot shard it and is effectively a singleton service. This will undoubtedly become a bottleneck.

Write an RFC that identifies the problem points that prevent horizontal scaling today.

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by efritz** [comment]
First review draft if available at https://docs.google.com/document/d/1IfkY9a6odfQmkjGtgJBFtPOUFuTwWryawFfVGRi8hO4.
