### ISSUE TITLE
Write RFC to horizontally scale auto-indexer

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#11635]
Currently the auto indexer cannot auto-scale because the indexer and the scheduler are run in the same process.

Write an RFC that identifies the problem points that prevent horizontal scaling today.

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by efritz** [comment]
First draft of RFC is available at https://docs.google.com/document/d/1rCduWqaLAbMu2s43RwJTBbRlhL6qS3oqq4iawiGdoVE/edit#heading=h.drl0b86kshdg.
