### ISSUE TITLE
Code intel user research

### ISSUE THREAD

**Issue by shrouxm** [sourcegraph/sourcegraph#11647]
The core semantic indexing product is rapidly maturing, and as we approach Q3 and Q4 we're going to have to focus on product work that benefits smaller slices of our user-base. The data we currently have on feature interest is very informal and incomplete.

This issue is to figure out how to measure user interest in product features so we can ensure that we're building the right thing. We should try measure interest from both existing and potential users, via survey & analytics. This issue will likely become a tracking issue for several related efforts.

**Comment by tsenart** [comment]
The tracking label is reserved to be used with the [tracking issue tool](https://about.sourcegraph.com/handbook/engineering/tracking_issues#populating-and-maintaining-a-tracking-issue) and causes breakage when used with labels that have too many issues. Hope it's ok to remove!

**Comment by scalabilitysolved** [comment]
Closing this as I believe we're tracking this as part of @macraig work cc/ @shrouxm
