### ISSUE TITLE
Definitions and references tab links should have the anchor at end of URL

### ISSUE THREAD

**Issue by aileenrose** [sourcegraph/sourcegraph#11649]
- **Sourcegraph version:**  Latest on /search

#### Steps to reproduce:
 On any function name, hover and copy the link on 'Find references'
Example:
`https://sourcegraph.com/github.com/sourcegraph/about/-/blob/website/src/components/BlogPosts.tsx?subtree=true#L5:11&tab=references`

#### Expected behavior:
The anchor link should be at the end of the URL.  In the example above, it should be:
``https://sourcegraph.com/github.com/sourcegraph/about/-/blob/website/src/components/BlogPosts.tsx?subtree=true&tab=references#L5:11`

The issue is that Google Analytics will filter out the URL fragment starting with the hashtag anchor link and so we are unable to see if users are clicking on the definition or references tab.

#### Actual behavior:
![Screen Shot 2020-06-22 at 12 12 17 PM](https://user-images.githubusercontent.com/2164916/85327981-bbf06c80-b484-11ea-9ee4-4cbdaf8aa3fe.png)

cc: @rrhyne @ebrodymoore

**Comment by rrhyne** [comment]
GREAT FIND!
