### ISSUE TITLE
External services banner message is unclear

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#11640]
A banner when setting up the instance reads:

“Configure external services to connect repositories to Sourcegraph.”. 

It is unclear what external services the install is referring to. The banner links to the Add Repositories page. Update the banner to read:

“Connect a code host to add repositories to your Sourcegraph instance.”. 

The link text should be: "Connect a code host"

**Comment by lguychard** [comment]
@rrhyne was this addressed by https://github.com/sourcegraph/sourcegraph/pull/11645?

**Comment by felixfbecker** [comment]
Ping @rrhyne 🙂

**Comment by rrhyne** [comment]
It was addressed here, but I did not link the issue to the pull request correctly: 

https://github.com/sourcegraph/sourcegraph/pull/11645
