### ISSUE TITLE
Simplify certain equivalent expressions containing AND

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#11656]
Users might be tempted to query:

`repo:foo (file:bar AND foobar)` or variants, which are equivalent to omitting the `AND` expression. We should surface this somehow, likely as a suggestion.

**Comment by camdencheek** [comment]
Closing since failing to correct a user's verbosity isn't a bug, and now that patterns are AND-separated by default, I expect we'll hit this much less frequently.
