### ISSUE TITLE
Add anonymous user ID to HubSpot forms

### ISSUE THREAD

**Issue by ebrodymoore** [sourcegraph/sourcegraph#11658]
For [RFC 185](https://docs.google.com/document/d/185ZbBFP2NFrTpP3sbNnevE2KnoFdSj6gsmX9uYtEMh0/edit#), we need to start capturing `Sourcegraph cloud anonymous user ID` as a hidden field in all our HubSpot forms (demo, contact). 

I've added the `anonymous_user_id` as a hidden field to the contact and demo forms. This just needs to be filled with the anonymous user ID we embed in localStorage. [This HubSpot link](https://community.hubspot.com/t5/APIs-Integrations/Capture-cookie-info-with-hidden-form-fields/td-p/257670) is similar to what might need to be done. I struggle to add a lot more knowledge behind this so @dadlerj is probably the best resource to answer more technical questions about this.

**Comment by aileenrose** [comment]
Initial notes:
Local Storage cookie: sourcegraphAnonymousUid
I don't see it on Safari, only on Chrome and Firefox.
With Google Tag Manager, I should be able to write the value into the forms.

**Comment by dadlerj** [comment]
In case it's helpful, it's defined in the https://sourcegraph.com/github.com/sourcegraph/sourcegraph@f142c9ce4e8d9c7d36579cdc4dd9ce487a74cdcd/-/blob/web/src/tracking/eventLogger.tsx#L80:12

It should be on Safari 🤔  — there's no limitation that I'm aware of. Just to check @aileenrose are you checking on the about.sourcegraph.com domain, or on the sourcegraph.com domain? I am honestly not sure if this value is accessible across those! We might need to change how we store it if not...

That HubSpot link that @ebrodymoore linked to looks correct to me — the form creator function at https://sourcegraph.com/github.com/sourcegraph/about/-/blob/website/src/components/HubSpot.tsx#L8:17&tab=references accepts a `onFormSubmit` argument... We could make it add that value as a default?

**Comment by aileenrose** [comment]
This definitely makes a compelling reason to not use the about subdomain!  

If there is a cookie we could read from the about site or info.sourcegraph.com, we could also use `onFormReady` to set the value.

**Comment by ebrodymoore** [comment]
Could we use [a solution like this](https://stackoverflow.com/questions/18492576/share-cookie-between-subdomain-and-domain) to maintain the cookie across the subdomain?

**Comment by dadlerj** [comment]
Yes that sort of thing is definitely possible! Unfortunately, we are currently using localStorage for this info, not a cookie (similar, but slightly different concepts), and localStorage doesn't work across subdomains.

The easiest solution is probably to migrate this data to a cookie instead, which _can_ be accessed across subdomains. 

See this comment for more: https://stackoverflow.com/a/28095717

**Comment by aileenrose** [comment]
@christinaforney (not to ping-pong too much with this. ) :) 
We need assistance from the Cloud team to write the `AnonymousUserID` into a cookie instead of localStorage.

Once that is done, Marketing can read the cookie from the subdomain i.e. about.sourcegraph.com, and get it into Hubspot.

**Comment by felixfbecker** [comment]
If this is for RFC 185: Sourcegraph Cloud lead generation tracking, should this be owned by the cloud team instead of the web team?

**Comment by ebrodymoore** [comment]
@christinaforney ^^^ since it looks like you added the web label

**Comment by christinaforney** [comment]
@felixfbecker - This is for Sourcegraph.com, not necessarily for Sourcegraph Cloud private code, and is much more of a web infrastructure problem. The web team should own this. This helps us with efforts like tracking users that came in to use the CNCF search page, and will be helpful in understanding how Sourcegraph.com contributes to the sales pipeline.

**Comment by felixfbecker** [comment]
Does the proposed solution with cookies with Chrome's and Safari's restrictions on cross-origin cookies?

**Comment by felixfbecker** [comment]
Should not be, given that should still qualify as "SameSite": https://web.dev/samesite-cookies-explained/#explicitly-state-cookie-usage-with-the-samesite-attribute

**Comment by felixfbecker** [comment]
@dadlerj while investigating I also found that we set the same localStorage key for a user ID on native integrations: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/browser/src/shared/tracking/eventLogger.tsx#L97:40
But given that it's on the native integration, that user ID will actually be different and not shared with sourcegraph.com. Is that intentional? Or are we potentially over-counting unique users?

**Comment by ebrodymoore** [comment]
@aileenrose could we add the anonymous_user_id to HubSpot forms now that it's in the cookie?

**Comment by aileenrose** [comment]
accidentally closed - still pending with tracking project.

**Comment by dadlerj** [comment]
@felixfbecker Regarding your post above:

>But given that it's on the native integration, that user ID will actually be different and not shared with sourcegraph.com. Is that intentional? Or are we potentially over-counting unique users?

Because we don't support anonymous users on self-hosted instances, it shouldn't be a problem (I believe everyone has to auth to Sourcegraph before native integrations work). Does that make sense to you?
