### ISSUE TITLE
Go to definition tab link does not always include &tab=def 

### ISSUE THREAD

**Issue by aileenrose** [sourcegraph/sourcegraph#11652]
- **Sourcegraph version:** Latest on /search

#### Steps to reproduce:
On any function name, hover and copy the link on 'Go to definition'.
Example: 
https://sourcegraph.com/github.com/sourcegraph/about/-/blob/website/src/components/HubSpot.tsx?subtree=true#L8:17

#### Expected behavior:
https://sourcegraph.com/github.com/sourcegraph/about/-/blob/website/src/components/HubSpot.tsx?subtree=true&tab=def#L8:17

NOTE that this was discovered when looking into this issue: https://github.com/sourcegraph/sourcegraph/issues/11649

#### Actual behavior:
![Screen Shot 2020-06-22 at 1 18 28 PM](https://user-images.githubusercontent.com/2164916/85331455-ffe67000-b48a-11ea-8b40-51c9e0ab944f.png)

cc: @rrhyne @ebrodymoore

**Comment by attfarhan** [comment]
If there is a canonical definition (i.e. our code intel knows the exact definition location), it won't have `&tab=def`, and the link will take you to the definition directly.

**Comment by attfarhan** [comment]
@rrhyne why are these tagged RFC-159 and assigned to me btw? Issues like this seem more like code intel issues to me?

**Comment by rrhyne** [comment]
The end goal is to enable goal tracking to ensure we are helping users see code intel events. They were assigned to you because they affect this project's goal tracking, but I appreciate they should be assigned to code intel.

**Comment by rrhyne** [comment]
@aileenrose, what do you think about tracking these with Events? We already have to use events for other actions and we can get a more consistent behavior without requesting an alteration to code intel.

**Comment by aileenrose** [comment]
Yes, we can track the tab clicks with events.  I wanted to make sure this was not a bug.  I can close this if this not a bug.
