### ISSUE TITLE
Make store interfaces interoperable

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#11678]
This is part of https://github.com/sourcegraph/sourcegraph/issues/11676 (bullet point #4).

**Proposal**

Define a generic `store` interface in an internal package with a minimal set of functionality (basically defining things like Execer and other required interfaces). This will also add `Transact` and `Done` functionality seen in some implementations and standardize this pattern.

Rewrite each existing store to extend this store via composition so they do not have direct access to the underlying database.

Add a way for one store to "take" the handle of another store to allow multi-store transactions. For example:

```go
repoStore := ...
campaignsStore := ...

// ...

tx := campaignsStore.Transact(ctx)
tx.Something(...)

// ...

tx2 := repoStore.Use(tx) // replaces underlying db handle of repoStore
tx2.Something(...)

// ...

tx.Done() // also equivalent to tx2.Done()
```

Comments welcome on this issue.

**Comment by tsenart** [comment]
I like this proposal. I'd just rename `Use` to either `With` or `In` and have in mind that at least for now we don't support nested transactions. Would be cool to support them though since Postgres does with SAVEPOINT.

**Comment by ryanslade** [comment]
Nice.

One suggestion, instead of `Use` maybe `WithTransaction` or `WithTX`?

**Comment by efritz** [comment]
> I like this proposal. I'd just rename `Use` to either `With` or `In` and have in mind that at least for now we don't support nested transactions. Would be cool to support them though since Postgres does with SAVEPOINT.

The codeintel store supports savepoint already, so I’ll move this up a layer as well.

**Comment by tsenart** [comment]
For context I tried this before [here](https://github.com/sourcegraph/sourcegraph/pull/6499) but failed to support concurrency with nested transactions due to lib/pq#81

**Comment by mrnugget** [comment]
> Rewrite each existing store to extend this store via composition so they do not have direct access to the underlying database.

I think I know what you mean, but can you spell out what "direct access" refers to?

**Comment by efritz** [comment]
@mrnugget It should issue queries through a common interface (such as dbutil) rather than using a raw sql conn. We basically already do this.

**Comment by mrnugget** [comment]
Great! That, plus moving more helpers into `dbutil`, would be great. I like the proposal.

What do we do about the elephant in the `./cmd/frontend` called `db`?

**Comment by efritz** [comment]
See the parent issue

**Comment by efritz** [comment]
> One suggestion, instead of Use maybe WithTransaction or WithTX?

@ryanslade This method _might_ not be in a transaction, which seems a slight bit misleading (although that's generally why'd you use it - share a transaction _if_ one is started). I think @tsenart 's suggestion for `With` seems like a good middle-ground.

**Comment by efritz** [comment]
> Would be cool to support them though since Postgres does with SAVEPOINT.

@tsenart We already have code in the codeintel layer to do this - I'll move it to the base store implementation so that others can use it as well.
