### ISSUE TITLE
repo-updater organization synching takes forever

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#11684]
cc @sourcegraph/cloud Repo-updater is incredibly slow in the way it performs ListOrgRepositories requests. Our replica configuration has 2k orgs listed out like this:

```
{
  "url": "https://ghe.sgdev.org",
  "token": "<secret>",
  "orgs": [
    "cool-lichterman-353",
    "pensive-pare-463",
    "adoring-solomon-88",
    "awesome-faraday-105",
    "upbeat-buck-175",
    "tender-ride-438",
    "strange-easley-211",
    "determined-austin-59",
    "adoring-wilbur-103",
    "elated-ardinghelli-65",
    "naughty-jones-406",
    "hopeful-wilson-230",
    "objective-hodgkin-142",
    ...
  ]
}
```

Logs indicate that repo-updater starts at the bottom of the list of orgs, and slowly goes to the top (no repeats in the logs, so I know it hasn't completed the list once):

```
t=2020-06-23T20:56:25+0000 lvl=dbug msg="TRACE github" host=ghe.sgdev.org path=/api/v3/orgs/friendly-volhard-252/repos code=200 duration=1.863031112s
...
t=2020-06-23T22:11:19+0000 lvl=dbug msg="TRACE github" host=ghe.sgdev.org path=/api/v3/orgs/jolly-dubinsky-343/repos code=200 duration=4.710393588s
```

There are 289 orgs between `friendly-volhard-252` and `jolly-dubinsky-343` in our configuration - 291 in total, and repo-updater logs show it is going through them one-by-one.

**It is taking repo-updater 67 minutes for it to consume 291 orgs, despite not being rate limited at all**

This is a major problem because we need to consume all 2k orgs listed out in this configuration, **it is expected this will take a customer around ~8 hours just for it to discover the repos from the code host and only _then_ will it start cloning and indexing them** 

Here are the full logs from repo-updater while it is trying to do this: https://gist.github.com/slimsag/18cee5a81616eaedd34cb31c9c675b2d

**Comment by slimsag** [comment]
This is not a regression and was also present in 3.16 it seems, over the last 7d on our replica syncs reported by `src_repoupdater_syncer_sync_last_time` indicate they took around 6-8 hours on average:

![image](https://user-images.githubusercontent.com/3173176/85474335-5e821b80-b569-11ea-9263-d3221997c280.png)

**Comment by keegancsmith** [comment]
GitHub doesn't allow concurrent requests, could it just be that this is how long it takes?

Note: for new repos we add them to the db straight away, we don't wait until syncing is done. We wait until syncing is done only for modify repo metadata and detecting deletions. However, this feature may need to be updated to also enqueue those repos in the update scheduler. I'll look into that now.

**Comment by slimsag** [comment]
Ah I didn’t know GitHub doesn’t allow concurrent requests for this. In that case, I think the issue becomes “this can go on for 8 hours with substantial lack of visibility into what is happening”

**Comment by keegancsmith** [comment]
Note: this may not be true on a customized GitHub enterprise, we could add some concurrency for that if that helps the customer in question.

**Comment by keegancsmith** [comment]
I just realised another problem with slow syncing. If repo-updater restarts, we won't do any git fetches until the first sync. Fixing this problem as well :)

**Comment by keegancsmith** [comment]
> However, this feature may need to be updated to also enqueue those repos in the update scheduler.

Confirmed that they do get added to the queue as we discover them. So on initial setup we will start cloning repos straight away.

**Comment by keegancsmith** [comment]
@slimsag in master we now also fetch all existing repos. I think a follow-up issue focussing on what you would like to be reported to give you confidence everything is working would be great. I think now that we do start the scheduler, you may start noticing activity. As such I am gonna close this out.
