### ISSUE TITLE
failed to update recloneTimestamp

### ISSUE THREAD

**Issue by sfllaw** [sourcegraph/sourcegraph#117]
- **Sourcegraph version:** Sourcegraph Server 2.10.0 (2.10.0)

#### Steps to reproduce:

1. Clone a repo and manage to lock the repo's local config somehow
2. Restart Sourcegraph

#### Bug:

In the logs, I see:
>20:44:17 gitserver | t=2018-08-02T20:44:17+0000 lvl=eror msg="error recloning repo" repo=/var/opt/sourcegraph/repos/github.example.com/user/repo/.git error="failed to update recloneTimestamp: /usr/bin/git git config --add sourcegraph.recloneTimestamp 1533242657 failed with stderr: : exit status 255"

If we log into the Docker container and run the same command:
```console
/var/opt/sourcegraph/repos/github.example.com/user/repo/.git # GIT_TRACE=1 /usr/bin/git config --add sourcegraph.recloneTimestamp 15333242657
20:54:57.822096 git.c:415               trace: built-in: git config --add sourcegraph.recloneTimestamp 15333242657
error: could not lock config file config: File exists
```

This is because `config.lock` actually exists!

```console
/var/opt/sourcegraph/repos/github.example.com/user/repo/.git # ls
 -l config*
-rw-r--r--    1 root     root           223 May  4 16:45 config
-rw-r--r--    1 root     root             0 May  4 16:46 config.lock
```

These repos are all managed by Sourcegraph though, so perhaps you want to clear the locks every time you clone the repo?

#### Workaround:
```console
~ # find /var/opt/sourcegraph/repos -path '**/.git/config.lock' -print -delete
```

**Comment by keegancsmith** [comment]
Nice catch! We have janitor jobs that go around looking for "stuck" repos. We can clean up the lock file in those cases. I'd also add we should probably clean up other lock files git can leave behind. I believe they can also exist for packed-refs and under the `refs/` dir.

**Comment by keegancsmith** [comment]
The next release of Sourcegraph will include the above mentioned janitor job to clean up lock files.

**Comment by nicksnyder** [comment]
This fix has been released.
