### ISSUE TITLE
Add Google Analytics event tracking to cloud deployments

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#11700]
#### Feature request description

To help track goals related to measurement of onboarding efforts are working, we would like to add Google Analytics Event tracking of specific events to Cloud deployments. This is in addition to our Looker event logs.

@rrhyne @attfarhan @aileenrose discussed this live. We will add this via Google Tag Manager, which we already have a script for in Cloud. Steps to move forward:

- [ ] @attfarhan to add `ga-` specific classes for buttons triggering the events below 
- [ ] @aileenrose to add the events/build funnel in GTM

We will not use the same events as in Looker. We will track: 
- Go to definition
- Find references
- Search scope clicked
- Regexp toggled
- Structural search toggled
- Case sensitivity toggled

~Due to the volume of logged events, we would like to track only the following subset of the current events:~

~- codeintel.searchDefinitions~
~- codeintel.lspDefinitions~
~- codeintel.lsifDefinitions~
~- codeintel.searchReferences~
~- codeintel.lspReferences~
~- codeintel.lsifReferences~
~- SearchScopeClicked~

Additionally, the following new event log items should be created:

- *SearchResultFileClicked:* triggered when a user clicks a link in the search results to get to a page such as [this one](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@a1aba93fa33fe0d23ed60111afd49f06b5794509/-/blob/cmd/frontend/db/event_logs.go)
- The following search mode toggle events:
  - SearchModeRegexpToggled
  - SearchModeStructuralToggled
  - SearchModeCaseSensitivityToggled

```
ga('send', {
  hitType: 'event',
  eventCategory: {EVENT_LOG_NAME},
  eventAction: 'click',
});

```

- *ViewRepositoryGroup:* triggered when a repository group page is viewed. For these events, adding an event label will help us review page popularity:

```
ga('send', {
  hitType: 'event',
  eventCategory: 'ViewRepositoryGroup',
  eventAction: 'click',
  eventLabel: 'Python2 to 3 conversion'
});

```

#### Describe alternatives you've considered.

We attempted to add goal tracking via URLs, but the structure of our URLs is not compatible with the feature. 

#### Additional information
@aileenrose can you confirm this is the relevant documentation for implementation:
https://developers.google.com/analytics/devguides/collection/analyticsjs/events

**Comment by rrhyne** [comment]
@ebrodymoore

**Comment by ebrodymoore** [comment]
@rrhyne are you ok with the following changes (for syntax consistency):
SearchResultFileClicked
SearchModeRegexpToggled
SearchModeStructuralToggled
SearchModeCaseSensitivityToggled

**Comment by rrhyne** [comment]
Of course. I edited the ticket to represent those names. Does RepositoryGroupPageViewed match your convention?

**Comment by ebrodymoore** [comment]
Actually could we switch that to ViewRepositoryGroup____? Would it be accurate to call that page 'RepositoryGroupHome' instead of page?

**Comment by rrhyne** [comment]
@ebrodymoore I think that would be undesirable in Google analytics, we would want to add a value to the event log instead. See my updated request above. Can your system do that as well?

**Comment by attfarhan** [comment]
@ebrodymoore do we currently use google analytics in the web app? Based on what I've searched there's nothing in there. Would need to set this up properly + need our GA credentials, etc.

Also, can I ask why we need to have this separately in Google Analytics rather than events in Looker? These events seem similar to events we already log in the web app that go to Looker.

**Comment by rrhyne** [comment]
Yes, we are using Google Analytics via the Google Tag Manager for cloud deployments. 

The events are duplicative to Looker data but allow us to tie into other analytic efforts by the marketing team and view them with web-specific analytics tools.

**Comment by rrhyne** [comment]
@attfarhan @christinaforney while it is certainly possible to launch the MVP without this tracking, I would much prefer to launch with it so we can start measuring results as soon as possible.

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
