### ISSUE TITLE
Design enterpirse download CTAs for cloud 

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#11725]
Allow users to find the downloadable installation from sourcegraph.com cloud content. 

#### Figma

https://www.figma.com/file/X5WmkZmMv8wACPpxFDgKpX/Search-CTAs?node-id=0%3A1&viewport=234%2C1758%2C1

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
