### ISSUE TITLE
Consider warning if host resources are unused

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#11723]
A customer ([see slack thread](https://sourcegraph.slack.com/archives/CJX299FGE/p1593120405486000?thread_ts=1593119496.484500&cid=CJX299FGE)) had a docker-compose deployment with memory/CPU limits lower than their instance had - meaning they had spare, unused resources on the host machine.

Ideally we would surface this information at least in Docker Compose deployments - and perhaps in Kubernetes, optionally, too?

**Comment by dadlerj** [comment]
Requested by https://app.hubspot.com/contacts/2762526/company/693777200

**Comment by bobheadxi** [comment]
This was added in https://github.com/sourcegraph/sourcegraph/pull/11082, got various tweaks to try and make it more informative (e.g. https://github.com/sourcegraph/sourcegraph/issues/12692, https://github.com/sourcegraph/sourcegraph/issues/12032,  https://github.com/sourcegraph/sourcegraph/issues/14504), but was eventually removed in https://github.com/sourcegraph/sourcegraph/pull/16164

Semi-relevant, but (possibly) unused resources also came up recently from feedback about Sourcegraph being unexpectedly expensive to run ([thread](https://sourcegraph.slack.com/archives/C0C324C91/p1609277165138900))

cc @pecigonzalo

**Comment by pecigonzalo** [comment]
> I wonder if we can just provide documentation on scaling instances that suggests looking at the monitoring for long-term usage to decide if services need to be downscaled to try and resolve this?

I think adding docs on how to scale Sourcegraph, providing alerts when scaling is required and lowering the default deployment limit settings would greatly help alleviate this.
This is also in-line with what I have seen most other self-hosted software provide.

In the particular case of docker-compose, I would assume (or even require) the host is dedicated to running Sourcegraph and not shared, in this case, resource limits are only to prevent services to take down each other, so we could only limit some services and advice how to scale them.

**Comment by pecigonzalo** [comment]
I would consider doing something like in this draft https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/207
