### ISSUE TITLE
`src-expose` fails on unreadable non-tracked files in repo dir

### ISSUE THREAD

**Issue by abitrolly** [sourcegraph/sourcegraph#11720]
When there are unreadable files in repo dir, [`src-expose`](https://github.com/sourcegraph/sourcegraph/tree/master/dev/src-expose) fails.
```
...
sync: 2020/06/25 17:53:17 localrepo> git status --porcelain --no-renames
> ?? .sourcegraph/
sync: 2020/06/25 17:53:17 localrepo> git rm -r -q --cached --ignore-unmatch .
sync: 2020/06/25 17:53:17 localrepo> git add -A
! warning: could not open directory '.sourcegraph/data/postgresql/': Permission denied
! error: open(".sourcegraph/config/nginx.conf"): Permission denied
! error: unable to index file '.sourcegraph/config/nginx.conf'
! fatal: adding files failed

error: exit status 128
```
`.sourcegraph/data/postgresql` is present in repo working dir, but is owned by other user. Why it tries to `git add` it in the first place? Looks like a security issue to me.

#### Steps to reproduce:

```
podman pod create --name srcview -p 127.0.0.1:3434:34343 -p 127.0.0.1:7080:7080 -p 127.0.0.1:3370:3370
podman run --pod srcview --name src-expose --rm -v "${PWD}:/var/opt/localrepo":Z,ro sourcegraph/src-expose:latest /var/opt/localrepo
mkdir -p .sourcegraph/config
mkdir -p .sourcegraph/data
podman run --pod srcview --name sourcegraph --rm -v .sourcegraph/config:/etc/sourcegraph:Z -v .sourcegraph/data:/var/opt/sourcegraph:Z sourcegraph/server:3.17.1
```

**Comment by abitrolly** [comment]
@keegancsmith any ideas why this happens?

**Comment by keegancsmith** [comment]
You are making src-expose crawl "$PWD". But "$PWD" also contains your `.sourcegraph` dirs you created. Rather put the sourcegraph data in another directory, rather than the repository you are snapshotting.

**Comment by abitrolly** [comment]
@keegancsmith I do not track `,sourcegraph` in `git`. Why `src-expose` tries to add them?

**Comment by keegancsmith** [comment]
Add it to `.gitignore` then. I am assuming it is showing up with `git status`? If $PWD is a git repo, instead run `src-expose serve /var/opt/localrepo`. Note: src-expose snapshots directories, its original purpose was for integrating non-git repo data into sourcegraph. However, if you already have a git repo `src-expose serve` will avoid snapshotting and instead just serve up the `.git` data.

**Comment by abitrolly** [comment]
`serve` doesn't seem to work. The http://127.0.0.1:3434/v1/list-repos gives empty output.
```
{
  "Items": null
}
```

The log.
```
serve: 2020/06/26 10:24:40 listening on http://[::]:3434
serve: 2020/06/26 10:24:40 serving git repositories from /var/opt/localrepo
serve: 2020/06/26 10:24:40 configuring repo at /var/opt/localrepo/.git: updating server info: error: unable to update info/refs: Read-only file system
error: unable to update objects/info/packs: Read-only file system
warning: unable to unlink 'info/rev-cache': Read-only file system
: exit status 1
```

**Comment by abitrolly** [comment]
@keegancsmith I started with this problem in https://github.com/sourcegraph/sourcegraph/issues/11707

**Comment by keegancsmith** [comment]
aah ok, I am going to close this issue out and continue on the issue linked. You need to use serve, but we don't support read only yet. I'll update with information on the linked issue.

**Comment by abitrolly** [comment]
Why `src-expose` is not using `git clone --bare userrepo servedrepo`? That will solve the problem with read-only repo and won't touch user data.
