### ISSUE TITLE
Is it possible to request the addition of new open source repos to sourcegraph.com?

### ISSUE THREAD

**Issue by smcallis** [sourcegraph/sourcegraph#11730]
#### Question description

There's several repos hosted on googlesource.com that I think would be of general interest.
  https://chromium.googlesource.com/
  https://android.googlesource.com/

**Comment by unknwon** [comment]
@christinaforney @poojaj-tech what do you think?

**Comment by tsenart** [comment]
If these have mirrors on GitHub, it'd be easy.

**Comment by smcallis** [comment]
I know that chromium is mirrored at least:

https://github.com/chromium/chromium

I'll look into whether it'd be a simple matter to mirror the rest or not.

**Comment by tsenart** [comment]
@smcallis: Cool. If a repo is on GitHub, you can always open it on Sourcegraph like so: https://sourcegraph.com/github.com/chromium/chromium

**Comment by smcallis** [comment]
Sounds like the easiest way to me :)
