### ISSUE TITLE
Allow references to be marked as imprecise

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1174]
There are many useful things that are like "references" but that are not precise: our current basic-code-intel extension, #981, cross-repo references that may take shortcuts to be imprecise, etc.

To support these without violating users' reasonable expectation that "references" means precise, it would be valuable to have a way to display imprecise references and communicate the imprecision clearly to the user. 

Strawman ideas:

1. Extensions could mark individual reference results in a field on the result element that would cause the UI to display an "imprecise" or "best-effort" badge (possibly with an explanatory tooltip or label).
1. Extensions could contribute new panel tabs other than "References", such as "API matches (imprecise)" or "Text matches". Downside: the tab title would need to convey the imprecision, which could make it long and therefore weird-looking in the UI. (Related: #1172.)

cc @tsenart

**Comment by tsenart** [comment]
I like the first idea.

**Comment by sqs** [comment]
@francisschmaltz 	I'll just find a place to add a badge to these reference results (idea 1 above) unless you have any better ideas.

**Comment by francisschmaltz** [comment]
We should replace the repo badge with this icon if the match is from basic-code-intel: 
https://materialdesignicons.com/icon/blur

**Comment by sqs** [comment]
@francisschmaltz That solution alone doesn't work well, because we don't want to special-case a single extension (basic-code-intel).

**Comment by sqs** [comment]
PR at https://github.com/sourcegraph/sourcegraph/pull/1627

**Comment by nicksnyder** [comment]
Is this release blocking for 3.0?

**Comment by sqs** [comment]
No

**Comment by sqs** [comment]
I am postponing the fix for this issue (#1627) until 3.1. Because it is postponed, some users may be confused if all of the following are true:

- They have the basic-code-intel extension enabled
- They also have a precise code intel extension enabled

In this case, they will need to toggle the "Show/hide fuzzy refs" button if they want to see only precise refs. I will document this.

This is less of a problem for self-hosted instance users than Sourcegraph.com users because self-hosted instance users:

- need to explicitly enable the basic-code-intel extension (or their admin needs to) to experience this confusion, but explicitly enabling it means they are more likely to be aware of what's happening when they see fuzzy matches; it isn't enabled automatically as it is on Sourcegraph.com users
- are less likely (at least initially) to have a precise code intel extension enabled, so there is less likely to be confusion about which matches are precise and which are fuzzy

So overall it is still a big win to ship basic-code-intel even without this issue addressed.

**Comment by sqs** [comment]
@lguychard 	I saw you moved this from 3.1 to 3.0. I am assuming that was a mistake, and I moved it back to 3.1. I don't know if this will be a priority for 3.1, but we can triage it together soon and will have more feedback from users to help us decide.

**Comment by sqs** [comment]
Moving to backlog. Will monitor user feedback and bump this up in priority as needed.

**Comment by lguychard** [comment]
Discussed with @sqs:

- Fuzzy references could be differentiated through highlight color. For instance, in the below screenshot, the two fuzzy references would have a different highlight color, but we would still display all references:

![image](https://user-images.githubusercontent.com/1741180/51992477-57a6c480-24ad-11e9-9975-bcb9da344a2c.png)

- Hovering on a fuzzy reference could show a simple "fuzzy" badge

**Comment by lguychard** [comment]
@chrismwendt reassigning to you since you'll be working on this

**Comment by chrismwendt** [comment]
@lguychard Ah, thanks! I've been looking for this issue. Linking to https://github.com/sourcegraph/sourcegraph/issues/2452

**Comment by nicksnyder** [comment]
Should this be moved into the 3.2 milestone?

**Comment by chrismwendt** [comment]
@nicksnyder Yup, moved.

**Comment by chrismwendt** [comment]
Now that basic code intel has been split into N language extensions, showing the badge at the file header level is OK. You'll never see mixed fuzzy + precise results. That means https://github.com/sourcegraph/sourcegraph/pull/1627 will probably solve this issue.

I'll optimistically pick that up and work on it until someone chimes in.

**Comment by chrismwendt** [comment]
Resolved by adding an "Imprecise results" action item in the references panel https://github.com/sourcegraph/sourcegraph-basic-code-intel/pull/41
