### ISSUE TITLE
Programatically create regular data about code intel activity 

### ISSUE THREAD

**Issue by gbrik** [sourcegraph/sourcegraph#11746]
To help direct code intel work, we should create the following metrics:
- number of search-based code intel queries
- proportion of search-based code intel queries

split by the following dimensions:
- language
- project/repo
- project/repo size

**Comment by gbrik** [comment]
@dadlerj how much of this could we wrangle out of pings?

**Comment by gbrik** [comment]
@efritz how hard is this going to be to implement? project size is unnecessary for an mvp

**Comment by efritz** [comment]
We have these but not split by language or project/repo. I don't think we can get project/repo details back in pings (but we could possibly anonymize the repo into a generic "bucket" in which counts are distinct). cc @dadlerj for that, but it seems like a stretch for ping data.

I thought we were tracking languages in events, but it's not in the table. That would be trivial to add, but a bit more difficult to add to pings as we'd need the same code intel event payload for each language (we support 30+).

**Comment by gbrik** [comment]
ok, i'll focus on cloud for now, but specifically splitting this by lang in pings would be a huge +

**Comment by dadlerj** [comment]
CC @ebrodymoore

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by aidaeology** [comment]
Update: I was able to manually scrape customer information from hubspot/productboard, github issues and information provided by customer engineering team. It's proving difficult to programmatically get this information. Here are the results of this effort: https://docs.google.com/spreadsheets/d/1i3Edpz3NPqN1weTnr4pqEbKxxyNhgd96vMAq-R-5LII

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by efritz** [comment]
See https://about.sourcegraph.com/handbook/engineering/adding_ping_data.

**Comment by macraig** [comment]
@efritz is this issue relevant to the planned worked for this milestone? If so I can move it to the iteration board or just close it.

**Comment by gbrik** [comment]
This was the initial issue that eventually became your [RFC 241](https://docs.google.com/document/d/1Cs1FwtaCfcct90h_i__-4kFOtJ80PbOnd7jdz3BDsbQ/edit?ts=5f6c8022#heading=h.8nozctbmjyhv).
