### ISSUE TITLE
Improve clarity of the extensions registry

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#11743]
The default state of the extensions registry is very confusing. All of our language extensions are shown, and it's unclear to the user what their purpose is. A lot of `wip` extensions, or low-quality extensions, are shown. As a result, the few extensions that would be useful for users to enable (codecov, npm imports, git-extras, datadog-metrics) are not easily discoverable.

<details>
    <img src="https://user-images.githubusercontent.com/1741180/85864877-60481b00-b7c5-11ea-807f-cd08cb931df8.png">
</details>

We should improve this default state by only showing:
- `sourcegraph`-authored extensions that are _not_ language extensions and _not_ `wip`
- Any other activated extensions

Other extensions could be enabled from the "options" dropdown:

![image](https://user-images.githubusercontent.com/1741180/85867722-98e9f380-b7c9-11ea-8ad3-9fdd431f3653.png)

**Comment by lguychard** [comment]
I was hoping this would be easy to do 100% on the frontend, but unfortunately there's a bit more to it :(

Extension filtering on the extension list page is done partly on the frontend (for enabled/disabled filtering), and partly on the backend (for the rest). 

The biggest win here would have been hiding all the code intel extensions by default. The rest of the changes (hiding wip extensions, only showing `sourcegraph/` extensions) are very easy, but don't remove as much clutter upfront. This would have required filtering based on categories. Unfortunately, categories are [not currently exposed on `RegistryExtension`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@38d54337b92ac35c69472197779cbe029ae17610/-/blob/cmd/frontend/graphqlbackend/extension_registry.go?subtree=true#L103-121), the backend simply [filters on them at the DB layer](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@38d54337b92ac35c69472197779cbe029ae17610/-/blob/enterprise/cmd/frontend/internal/registry/extensions_db.go?subtree=true#L205-228) with `jsonb` operations on the raw manifest.

When viewing a _single_ extension on the frontend, we [parse and validate them out of the manifest](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@38d54337b92ac35c69472197779cbe029ae17610/-/blob/web/src/extensions/extension/RegistryExtensionOverviewPage.tsx?subtree=true#L46-56), but I don't want to do so on the extension list page, as that would require `JSON.parse()`ing 140+ extension manifests client-side...

I also think round-trips to the backend to filter on categories are needlessly slow, so I reckon the best way forward would be to parse & validate categories at extension release time, store them in `extension_releases` and expose them on `RegistryExtension`.

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by felixfbecker** [comment]
Closing this in favor of https://github.com/sourcegraph/sourcegraph/issues/13329
