### ISSUE TITLE
Create a code intel user survey

### ISSUE THREAD

**Issue by gbrik** [sourcegraph/sourcegraph#11747]
Rough draft:

# Code intelligence user survey

- Do you use Sourcegraph?
- Do you use Sourcegraph's code browser?
- Do you use Sourcegraph code host extensions?
- Are you aware of Sourcegraph's semantic code intelligence capabilities?
- For which languages are you interested in semantic code navigation?
  - multiselect including: go, ts/js, java, c++, python, ruby, more semi popular langs, and an other field
- What barriers prevent you from enabling semantic code intelligence on Sourcegraph?
  - unaware of option
  - not available for my languages
  - don't know how
  - too much effort to set up
  - maintenance is too hard
  - indexing takes too long
  - existing solutions don't work with my project structure
  - [freeform field]
- Which features of your IDE do you wish you could use when browsing code online?

**Comment by gbrik** [comment]
@efritz add stuffs you want to know!

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by macraig** [comment]
@gbrik can we close this issue as we have already created the survey? Or would you like to keep it and update it?

**Comment by gbrik** [comment]
Nope, this is done!
