### ISSUE TITLE
Burndown chart is off by one

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#11744]
![image](https://user-images.githubusercontent.com/19534377/85868223-48bf6100-b7ca-11ea-8bf0-c2bda93c163f.png)

Shows 1 open and changes requested but none appear in the list as open.

I checked the events in the DB and the problem seems to be that we query at most [250](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@bb060724ed5b825ea439da16fdec43132b9d93b5/-/blob/internal/extsvc/github/pulls.go#L840) events, which made us miss the "closed" event.
The PR: https://github.com/sourcegraph/sourcegraph/pull/596 has quite a few commits, so the event count should be much greater than 250. Perhaps pagination can help us here, but not sure how easily it can be combined with rate-limiting.

**Comment by chrispine** [comment]
@eseliger Is this fixed already?

**Comment by eseliger** [comment]
No, still a problem
