### ISSUE TITLE
Pure-SQL authz approach

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#11767]
Based on the effort of #11457, attempt to completely remove `authzFilter` function and store all permissions facts in Postgres tables.

See https://github.com/sourcegraph/sourcegraph/issues/11400#issuecomment-650838104 for problems to address.

**Comment by unknwon** [comment]
No bandwidth for this in 3.18, needs more time to work on pure SQL `PermsStore`.

**Comment by tsenart** [comment]
@unknwon: Removed from this cycle since you already had too much on your plate.

**Comment by unknwon** [comment]
Moved to the next cycle with reduced estimate.
