### ISSUE TITLE
e2e: remove tests covered by `dev/gqltest`

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#11762]
https://docs.google.com/spreadsheets/d/1lzKnWbI-zTlaqnHqzW5Ju1JF0dsov7s9RE6DyFeQmRk/edit#gid=0

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by felixfbecker** [comment]
Please coordinate with @sourcegraph/web on this so that we only remove e2e and regression tests that are also covered by our growing webapp integration test suite :)

**Comment by unknwon** [comment]
> Please coordinate with @sourcegraph/web on this so that we only remove e2e and regression tests that are also covered by our growing webapp integration test suite :)

@felixfbecker: Thanks, good point, will keep in mind!

**Comment by unknwon** [comment]
This issue turns out to be not something "do it and done", instead an effort with potentially multiple teams, so putting it in backlog and periodically checking back.

**Comment by unknwon** [comment]
Many e2e tests are removed during last week, I think this can be closed because no longer worth keeping as a dedicated task.
