### ISSUE TITLE
Stefan Hengl onboarding plan

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#11779]
### Week 1

- [x] General [onboarding](https://about.sourcegraph.com/handbook/people-ops/onboarding)
- [x] Engineering [onboarding](https://about.sourcegraph.com/handbook/people-ops/onboarding)
- [x] Get an introduction to the [architecture](https://docs.sourcegraph.com/dev/architecture) with @rvantonder or @tsenart.
- [x] Setup chats with everyone in your own team (Search) and get to know them.
- [x] Join each other team sync and understand what they own / do.
  - [x] [Cloud](https://about.sourcegraph.com/handbook/engineering/cloud)
  - [x] [Campaigns](https://about.sourcegraph.com/handbook/engineering/campaigns)
  - [x] [Web](https://about.sourcegraph.com/handbook/engineering/web)
  - [x] [Code Intelligence](https://about.sourcegraph.com/handbook/engineering/code-intelligence)
  - [x] [Distribution](https://about.sourcegraph.com/handbook/engineering/distribution)
  - [ ] Sales
  - [x] Marketing
  - [ ] Business Ops

- Stefan will own #10094 as a first feature improvement (solution proposal and implementation)

### Week 2 - 8

The below plan outlines a desirable path, but should not be seen as something that is absolutely fixed. Sometimes things like product requests can shift priorities quickly :-) It is rather to give structure that preempts situations like "ho hum, what should I work on now?" The intent is to convey the rough space of work that addresses gaps in our product and opportunities for impactful [1] additions and features that I'm very familiar with and can provide direct guidance on. 

[1] I say "impactful" to typically mean making progress on a bug or feature that affects customers/end-users. This can imply that we need to shape up various parts of our code base, so code quality and testing is crucial to shipping impactful changes and not isolated from it.

**Week 2.**

- Search query processing deep dive (schedule a call, allocate 1.5 hours). We’ll look at what I’m currently working on and direction for this functionality (query migration, supporting search expressions).

- Discuss work items to pick up and transfer ownership. Update: we picked #10094. Other options for later work includes:

  - Cover bite-sized opportunities for new search features and parameters and fixes (`rev:`, `time:`, globbing) (examples: #11213, #10820)
  - Candidate subtask: differential testing for prior and new query parser to facilitate query migration (example: #8780, #10844)
  - Candidate subtask: optimize and/or operators (examples: #11656, #11281)
  - Candidate subtask: `NOT` (example: #9976)
  - Candidate subtask: generating informative messages and query suggestions (example: #10013, #10793)
  - Candidate subtask: exclude dir from search https://github.com/sourcegraph/sourcegraph/issues/6870

Outcome: Pick one or more subtask and make progress over the next 1.5 weeks.

**Week 3.** Work on subtask(s) from previous week. Outcome: merge an impactful change and gain familiarity with the search code base.

**Week 4.**

- Reflect on progress for previous tasks, decide whether to continue on those additional subtasks.

- Interactive deep dive on search logic (schedule a call, allocate 1 hour). We’ll look at what the search code does in search.go and search_results.go and investigate together opportunities for refactoring and simplifying this code. Consider additional subtasks based on this deep dive: 

  - refactor logic and result handling in textsearch.go and search_results.go, identify and fix inconsistencies (example: #11364)
  - separate logic for different kinds of searches (commit/diff search, versus repo, etc) and add tests for these. We’re very aware that some of this is not sufficiently tested.

Outcome: Help make delivering impactful changes a sustainable habit by identifying key places to continue work.

**Week 5.** Continue Work on subtask(s) assigned in previous week. Start jointly brainstorming and propose RFC(s) that address next steps for search functionality re queries and customer validation: rules, return types, piping.

**Week 6-8.** Start iterating on proposed RFCs. Likely pick up additional prior subtasks or new requests. Possibilities: #9822, #8166.

Outcome: Identify and start work on next-level search features while having confidence in existing codebase (establish thorough testing, well-defined behavior).

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by tsenart** [comment]
Noticed we were using initials and this was still assigned to @rvantonder so made the change :)

**Comment by rvantonder** [comment]
@tsenart we can probably close this now yeah?
