### ISSUE TITLE
Extract codeintel's background job processing into an internal library

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#11786]
In order to make storing work records in postgres more generalizable, we should extract the current work done by the precise code intel backends so that it can used by other parts of the application.

**Comment by ryanslade** [comment]
FYI, we have similar code for campaigns too:
https://github.com/sourcegraph/sourcegraph/blob/f1fac0001ec84b0fab1a476c0655f835677979ee/enterprise/internal/campaigns/workers.go#L38

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
