### ISSUE TITLE
Chayim Kirshen On-boarding

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#11785]
### Week 1

- [x] General [onboarding](https://about.sourcegraph.com/handbook/people-ops/onboarding)
- [x] Engineering [onboarding](https://about.sourcegraph.com/handbook/people-ops/onboarding)
- [x] Read https://docs.sourcegraph.com/dev/architecture
- [x] Chat with everyone in your own team.
- [x] Chat with each team and understand what they own / do.
  - [x] Cloud: @keegancsmith
  - [x] Campaigns: @mrnugget 
  - [x] Web: @lguychard
  - [x] Code Intelligence: @efritz
  - [x] Distribution: @slimsag
  - [x] Sales: @juliasourceress 
  - [x] Marketing: @adamfrankl2015 
  - [x] Business Ops: @dadlerj 

### Week 2 - 4

- [x] Write an RFC for a sub-part of the [“Storing Secrets Securely”](https://docs.google.com/document/d/1qSSo83MJNcNbJhQOhDyHsGBCYPjyr7uhVQKGfZ8Vxfg/edit#heading=h.az00lc90wa5j) roadmap item and execute together with the Cloud and Distribution teams. Start small to get your feet wet, understand how things are put together but still make a meaningful contribution.
  - @slimsag [has written some additional context](https://docs.google.com/document/d/1q_OzpEgP6NJhWJLFGRS3MpG-A1UPZwYUe5d2FWTD0cc/edit) from his understanding of the problem space.
- [x] Review [RFC 52: State of security](https://docs.google.com/document/d/1r3YzpeoQMQ6MY1p1OpA-m2-_hDk_mLFeFUHlTx7PI7I/edit#heading=h.3ecdofvc7xo3)
- [x] Understand how our authorization and authentication systems work. @unknwon is the right person to get a brain dump from. Could we convert that into technical documentation?
- [x] Work with distribution and cloud teams on expanding / adjusting their 3 month roadmaps on security related work as appropriate.
- [x] Mentor [E. S.](#11605).

### Week 4 - 8

- Continue writing RFCs and delivering on “Storing Secrets Securely”
- ... TBD

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by chayim** [comment]
Onboarded and contributing. Closing accordingly.
