### ISSUE TITLE
Frontend memory leak

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#11790]
Some long term metrics show that we appear to have a slow memory leak on our frontend instances:

<img width="1262" alt="Screenshot 2020-06-29 at 15 50 10" src="https://user-images.githubusercontent.com/25610/86017367-40626280-ba24-11ea-8d50-5f7b91370d74.png">

**Comment by ryanslade** [comment]
Just to be clear, I'm not planning on looking into this in 3.18 unless it becomes a high priority

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by ryanslade** [comment]
We still seem to have slow growth in memory but it's not clear whether it's a leak or just cached data

**Comment by ryanslade** [comment]
This looks flat now:

<img width="2542" alt="Screenshot 2021-04-07 at 14 55 57" src="https://user-images.githubusercontent.com/25610/113869773-66861180-97b1-11eb-9d7c-9a33f11d5c8b.png">
