### ISSUE TITLE
Plan 3.19 work ahead of time

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#11818]
Depends on @slimsag completing Distribution product roadmap and giving Gonza enough context/info to do this

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by pecigonzalo** [comment]
Done in https://github.com/sourcegraph/sourcegraph/issues/11954
