### ISSUE TITLE
Add word wrap to code view

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#11823]
Word wrap would be nice when reading Markdown files with long paragraphs ([example](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@57fba3e8a4c47ec8c9e190fd4f9cf49bd90efa0b/-/blob/doc/admin/search.md?subtree=true#L9:217)).

This seems like a good issue for a new engineer (or an engineer who is new to the frontend code) to tackle.

**Comment by lguychard** [comment]
We do have word wrapping - or did I misunderstand what you mean here?

![image](https://user-images.githubusercontent.com/1741180/88387627-26ae0400-cdb3-11ea-8a2d-f7a1304ef1ab.png)
![image](https://user-images.githubusercontent.com/1741180/88387635-2a418b00-cdb3-11ea-8013-1f22a0201641.png)

**Comment by beyang** [comment]
TIL!

**Comment by NightMachinary** [comment]
@lguychard I can't find a wrap option for the search page? E.g., see [this](https://sourcegraph.com/search?q=context:global+file:indices/.*.org+repo:%5Egithub%5C.com/NightMachinary/r_rational%24+anime&patternType=regexp):
![image](https://user-images.githubusercontent.com/36224762/120240853-cf9c7980-c276-11eb-943a-aa07353c2f04.png)
