### ISSUE TITLE
Put plan forward: Push site admins to use Docker Compose or Kubernetes for production deployments

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#11828]
Many users of Sourcegraph today are still using a `sourcegraph/server` deployment in production.

We have seen that when this single-container deployment type begins to fall over, it falls over _hard_ and in ways that we (nor the customer) can effectively debug. It means that our only recourse is a painstakingly urgent migration to a better deployment type with resource isolation, like Docker Compose. In practice this has led to [angry and frustrated customers](https://sourcegraph.atlassian.net/jira/servicedesk/projects/SG/queues/custom/1/SG-187) and the appearance that we don't understand the cause of the issue.

This is all because services are running in the same exact container and competing for resources without any isolation between them. In contrast, Docker Compose and Kubernetes allows us to have resource isolation between services.

This issue is for tracking how we can get to a world where `sourcegraph/server` is treated purely as a non-production demo deployment type, with something like a banner at the top indicating exactly that.

It is worth noting that:

1. In our documentation we already explicitly state that single-container deployments are NOT for production deployments.
2. In server deployments we have a hard warning about performance being due to the deployment type [if searches time out and in other conditions](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@b084d7110dd495aca35d12e3e1c600308326db31/-/blob/web/src/search/results/SearchResultsList.tsx#L452-462).
3. Several customers are still running `server` deployments as we have not pushed them to migrate, and have explicitly used some hacks to disable the performance warning banners AND have faced performance issues.

In order to achieve this I believe we will need to:

1. Reduce the friction of upgrading from server -> Docker Compose and reduce the maintenance and resource burden of Docker Compose deployments compared to server ones (i.e. we need a "small scale docker compose deployment" setup).
1. Over time increasingly ramp-up pressure on site admins to upgrade to docker-compose or Kubernetes and explain why in clear terms.
1. Ultimately get to a point where there is a non-dismissible banner at the top of server deployments indicating "this is a demo deployment not for production use" - ramping up to this will need to be done carefully, after emailing and pushing admins, and after several versions of Sourcegraph with increasingly strong wording about the fact that we are going to do this.

**Comment by dadlerj** [comment]
A big part of the current problem can be tied back to our old pricing decisions — making non-single-server deployments part of a higher price tier. That was changed months ago, but we still have some customers on older contracts.

I think a non-dismissable banner at the top of single-server deployments is a great solution here. Obviously the more we can do to simplify the Docker Compose route the better, though, as most of the customers/users on a single server instance don't actually need any additional resources at all, so they might be confused by this change. 

Is there any way to put hardcoded limits on resource usage inside of a container?

**Comment by slimsag** [comment]
Moving https://github.com/sourcegraph/sourcegraph/issues/13304 here:

> For the past ~6 months or so [we have not recommend using `sourcegraph/server` in production deployments](https://docs.sourcegraph.com/admin/install) and instead suggested using at least Docker Compose which offers resource isolation and stability. However, a number of customers are still using `sourcegraph/server`.
>
> This is a tracking issue for me to put forward a plan for slowly reducing the number of sourcegraph/server usages in production deployments over time.
>
> This will be a slow and gradual process, I anticipate happening over the course of several months.
>
> More details to come.

**Comment by slimsag** [comment]
Recording of some customer, user, and internal pains we have faced due to the sourcegraph/server model:

- Usage numbers today and some discussion of why we need to do this to make customers successful / happy over the longer term: https://sourcegraph.slack.com/archives/CJX299FGE/p1594926820493600?thread_ts=1594926820.493600
- Instances of maintenance complexity:
    - Almost delayed the 3.19 release due to Redis segfault issues https://github.com/sourcegraph/sourcegraph/pull/13143
    - Major Alpine package dependency resolution/management issues for 3.19 release, taking multiple days of Distribution team's time, at least 24h of my time and 72h+ of Uwe's time.
    - Also taking up other team's time https://github.com/sourcegraph/sourcegraph/pull/13127
    - DNS issues https://github.com/sourcegraph/sourcegraph/pull/13107
    - Ongoing maintenance burden in development with monitoring/observability: https://github.com/sourcegraph/sourcegraph/pull/12424 https://github.com/sourcegraph/sourcegraph/pull/11950 
    - Lack of testing sometimes causes problems for users: https://github.com/sourcegraph/sourcegraph/pull/12312 
    - Version info regression: https://github.com/sourcegraph/sourcegraph/pull/11633
    - Annoying to build / test: https://github.com/sourcegraph/sourcegraph/pull/11536
    - Hard to handle/test every edge case: https://github.com/sourcegraph/sourcegraph/pull/10919
    - Security debt: https://github.com/sourcegraph/sourcegraph/issues/13238
    - Docs not clear on which deployment to use, leads to confusion: https://github.com/sourcegraph/sourcegraph/issues/13232
    - Another regression: https://github.com/sourcegraph/sourcegraph/issues/13079
    - Regressions in it not caught quickly enough, reduce user confidence in Sourcegraph: https://github.com/sourcegraph/sourcegraph/issues/12524#issuecomment-679332203
    - Disk utilization issues: https://github.com/sourcegraph/sourcegraph/issues/8453
    - Syntax highlighting issues: https://github.com/sourcegraph/sourcegraph/issues/5841
    - Search 504 issues: https://github.com/sourcegraph/sourcegraph/issues/12347

**Comment by slimsag** [comment]
> Obviously the more we can do to simplify the Docker Compose route the better, though, as most of the customers/users on a single server instance don't actually need any additional resources at all, so they might be confused by this change.

Yes, this is absolutely a problem that must be resolved (at least somewhat) _before_ we push more people to use Docker Compose.

**Comment by slimsag** [comment]
> Is there any way to put hardcoded limits on resource usage inside of a container?

No, this is what Docker Compose does and even if we could it wouldn't solve the other major problems here around maintenance burden.

**Comment by slimsag** [comment]
I have put forward a plan in the form of:

- [RFC 230: Deprecate single-container deployments](https://docs.google.com/document/d/1lyrQKBQZOKAfudykzDN95amUwkCpaM4YCf9j5YpRe-0/edit#heading=h.rg0uspwsxz5a)
- [RFC 232: A suitable replacement for non-production deployments](https://docs.google.com/document/d/17Jx1qi7LyImf0mpuzwmhrDmjq3Ed8sVNJWTM4PnDHQ4/edit#heading=h.kct20jix194c)

I will close this issue to record my work here; we can open new issues once we have decided on next steps.
