### ISSUE TITLE
deploy-sourcegraph-dhall: extend configuration layer for subset of services on k8s.sgdev.org

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#11830]
https://github.com/sourcegraph/deploy-sourcegraph-dogfood-k8s/blob/4669f10e139feccd1e8a68490faecd9c5b76437d/generated/params.sh#L11-L44

Right now, k8s.sgdev.org is configured via a bash-based configuration pipeline as a result RFC 141. This will be replaced by https://github.com/sourcegraph/deploy-sourcegraph-dhall as part of the Dhall dogfooding process. 

Part of this will be done by @ggilmore to lay the groundwork. The rest will be done by another member of the distribution team to spread knowledge and solicit feedback. This other team member will need to need to go through the dhall tutorial + pair with me in order to get up to speed about the Dhall language itself and https://github.com/sourcegraph/deploy-sourcegraph-dhall's architecture. 

@ggilmore proposes that he'll replicate `frontend`, `grafana`, and `redis` from https://github.com/sourcegraph/deploy-sourcegraph-dogfood-k8s/blob/release/generated/params.sh. The other distribution teammate will handle the other services

The work involved here includes:

- writing scripts to invoke dhall in the k8s.sgdev.org pipeline
- refactoring k8s.sgdev.org's bash-based configuration scripts to merge the output of the dhall-based-pipeline can be deployed alongside the legacy bash-based one
- Writing more dhall code in deploy-sourcegraph-dhall to handle new configuration needs (such as increasing the storage capacity of a persistent volume claim - needed for gitserver, etc.)
- Wiring up the configuration layer for all services in deploy-sourcegraph-dhall, not just the ones listed in https://github.com/sourcegraph/sourcegraph/issues/10936.

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by slimsag** [comment]
@ggilmore what is the status of this? closing but feel free to reopen.
