### ISSUE TITLE
Structural search bug for CPP only

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#11831]
Running a structural search for c:  lang:c = :[hole]; returns just fine, but running it for cpp: lang:cpp = :[hole];  returns the following:

<img width="1047" alt="Screen Shot 2020-06-30 at 5 48 43 PM" src="https://user-images.githubusercontent.com/539268/86191000-c81aa080-bafa-11ea-927c-2640d8663d6a.png">

**Comment by rvantonder** [comment]
I can no longer reproduce this, [the query returns results](https://sourcegraph.com/search?q=lang:cpp+%3D+:%5Bhole%5D%3B&patternType=structural), but I do think there's something not quite right here. I checked whether recent commits affected this but I don't think so. Will try a couple of things to pin it down.

**Comment by rvantonder** [comment]
Nevermind, I can see this behavior, sometimes it returns results, sometimes it doesn't. Will see what's going on.
