### ISSUE TITLE
Initial search tour

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#11833]
Introduce an optional tour to help new users get accustomed to the search syntax and place users in code they care about. 

Research

- [x] User test: https://drive.google.com/drive/folders/1joboprhSuHbJdllr4_exF1Wv19z_HJHxz
- [x] Review search data from sourcegraph.com

Wireframes
- [x] design

Figma Prototype
- [x] hallway testing
- [x] user testing - test prototype, then ask users to repeat what they learned on sourcegraph.com
- [x] review
- [x] approval

Visual design
- [x] design
- [x] review
- [x] approval

@attfarhan: __10.00d__

- [ ] Tour implementation [#12137](https://github.com/sourcegraph/sourcegraph/issues/12137) __10d__ 
- [ ] Search onboarding tour [#12972](https://github.com/sourcegraph/sourcegraph/pull/12972) :shipit:

**Comment by ebrodymoore** [comment]
For the analytics, the ideal scenario is adding these two events:
- `ViewOnboardingTour`
- `CloseOnboardingTourClicked` with the stage/step the user was at in the tour (e.g. `stage: 2`)

**Comment by tsenart** [comment]
The tracking label is reserved to be used with the [tracking issue tool](https://about.sourcegraph.com/handbook/engineering/tracking_issues#populating-and-maintaining-a-tracking-issue) and causes breakage when used with labels that have too many issues. Hope it's ok to remove!

**Comment by rrhyne** [comment]
@tsenart what is the limit for number of issues a tracking label can have? There were only three associated with this RFC-159.2.

**Comment by tsenart** [comment]
In your case the number of issues wasn't the problem, but rather that the issue body isn't being generated by the tracking issue tool. For that you need to create the issue with the right template (check the tags where the content would be inserted).

**Comment by ebrodymoore** [comment]
For getting onboarding tour metrics in pings, I'm thinking we create a funnel of sorts. 

So it'd be number of times each of these events is triggered per day: `ViewOnboardingTour`, `OnboardingTourLanguageOptionClicked`, `OnboardingTourRepositoryOptionClicked`, `ViewedOnboardingTourSubmitSearchStep`, `ViewedOnboardingTourAddQueryTermStep`, `ViewedOnboardingTourFilterRepoStep`, `ViewedOnboardingTourFilterLangStep`

@poojaj-tech @rrhyne @attfarhan would love your thoughts on this
