### ISSUE TITLE
Audit current e2e / regression tests, and identify which should be ported to integration tests

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#11869]

**Comment by twop** [comment]
My first pass of auditing regression tests for porting them as UI tests. I haven’t prioritized the list of UI tests yet, but it seems that signing in, searching and hovers are the most valuable.
https://docs.google.com/document/d/1BoEasLC_q1UKF_nAwPDidLt090GFPczRRjFMEHb1aao/edit#heading=h.hn3ibsuomih
I haven’t touched e2e tests yet, that is probably going to be todo on Monday

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
