### ISSUE TITLE
Selected search filter disappears

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#1186]
1. https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/gohugoio/hugo%24+i18n+file:%5C.go%24+
2. Click on `-file:_test\.go$` filter
3. Results page does not have `-file:_test\.go$` filter selected

Not a high priority.

cc @vanesa

**Comment by ijt** [comment]
This appears to be working. I did steps 1 and 2 and this is the result:

![Screen Shot 2019-05-08 at 4 10 48 PM](https://user-images.githubusercontent.com/15530/57414179-e82b2a00-71ab-11e9-8f22-f98dfa063197.png)

**Comment by nicksnyder** [comment]
@attfarhan assigning this to you since you will be working on search frontend. Solving this particular issue is not a priority, but you might incidentally make this issue obsolete.

@ijt this is an example of a bug in the two way binding between UI and search bar

**Comment by ijt** [comment]
Given that it's buggy and probably not worth the effort to fix all its issues, we could get rid of the two way binding and define a simple rule such as this: Fields from outside the main search bar get added to the query upon submission, not before. If there are conflicts, it would be up to the backend to either take the rightmost settings of conflicting fields or flag the conflicts as errors.

**Comment by malomarrec** [comment]
Tagging similar issue in #20158 to feed into prioritisation work.

**Comment by lguychard** [comment]
Closing: this will no longer be relevant with the new search results sidebar (cc @rrhyne @limitedmage)
