### ISSUE TITLE
search: multiple repohasfile inconsistency between repo search and text search

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#11865]
If you do the search `repohasfile:foo repohasfile:bar`, we do a repo search and return repos which contains `foo` OR `bar`. However, if you do `baz repohasfile:foo repohasfile:bar` we return baz only in repos which contains the file `foo` AND `bar`. :/

I believe AND is the correct behaviour here. The function that needs updating is `reposToAdd`. cc @sourcegraph/search

**Comment by keegancsmith** [comment]
Some extra context pointing towards just removing support for repohafile in reposearch https://github.com/sourcegraph/sourcegraph/pull/11864#issuecomment-652743242

**Comment by rvantonder** [comment]
Going through some search-labeled issues. Since this is a validation issue which we can deal with in the new parser  (and also support the `or` expression soon enough), I'm reassigning this to myself, unless you really want to deal with it :-)

**Comment by rvantonder** [comment]
Same issue with `message:` and `commit:` https://github.com/sourcegraph/sourcegraph/issues/13346

**Comment by rvantonder** [comment]
Related to `repo` and `repogroup` combinations: https://github.com/sourcegraph/sourcegraph/issues/14004
