### ISSUE TITLE
Z-index issue on extension registry

### ISSUE THREAD

**Issue by christinaforney** [sourcegraph/sourcegraph#11871]
![image (1)](https://user-images.githubusercontent.com/1559622/86258272-7d873b80-bb6f-11ea-80ee-04399a58ab25.png)

**Comment by tjkandala** [comment]
<img width="535" alt="Screen Shot 2020-10-12 at 2 21 06 PM" src="https://user-images.githubusercontent.com/37420160/95778473-2d536580-0c96-11eb-9141-064597db219a.png">

Fixed in RFC 209 implementation
