### ISSUE TITLE
Extensions discoverability

### ISSUE THREAD

**Issue by christinaforney** [sourcegraph/sourcegraph#11872]
The web team will be doing a first effort to improve the extension registry in the next week or so (first week of July): https://github.com/sourcegraph/sourcegraph/issues/11743

### Discoverability

- Add to main navigation?
- Improve extension search and discovery
  - Link to docs on how to create extension
  - Replace category dropdown with tags
  - Replace enabled/disabled drop down with checkbox
  - Add lead in for authoring extensions

**Comment by AlicjaSuska** [comment]
Notes from the kick-off meeting with @christinaforney. This is a summary of the most important problems for this project with possible solutions.

1. Discoverability - extensions should stand out more on the platform. 
- Add the 'Extensions' tab to the main navigation.

2. Extensions registry is overwhelming
- Group extensions in categories
- Add categories as filters
- Bring enabled/disabled filters to the front
- Hide extensions that are WIP
- Make sure that language extensions are on (for code intelligence)

3. Communicate the value
- add a description that explains what extensions are and why they are useful.

4. Encourage users and companies to create their own extensions
- add a link to the documentation
- make this possibility stand out more on the website

5. Explore the idea of 'approved' extensions
- help for users to understand which extensions are ready to use and recommended by Sourcegraph
- how would the approval process look like?
- beta and WIP extensions - distinction, which should be on the main page, etc.

6. Extensions behaviour and bar management
- extensions shouldn't disappear from the toolbar to not confuse the users. They can be inactive.
- how to manage extensions bar
- any other suggestions that would improve the experience

7. Command palette
- is placement correct?
- an empty state could 'advertise' the feature

**Comment by AlicjaSuska** [comment]
Connected to this issue: 'Add tags to Git-extras extension' [#12485](https://github.com/sourcegraph/sourcegraph/issues/12485)

**Comment by AlicjaSuska** [comment]
I've created an **[RFC](https://docs.google.com/document/d/1I5BMEGp3QuB81AjSzLCQwq_XJV1sXevlU0lpB4O1pj8/edit?usp=sharing)** for the project to gather all the information in one place. @christinaforney @rrhyne that would be great if you can review it, then I'll make changes and start the usability testing! 🎉

Current state:

**Ready to review**: All details regarding the discoverability, extensions registry change and adding more information about publishing extensions.

Still WIP: 'using extensions' - management of the bar and command line

**Comment by AlicjaSuska** [comment]
[RFC](https://docs.google.com/document/d/1I5BMEGp3QuB81AjSzLCQwq_XJV1sXevlU0lpB4O1pj8/edit?usp=sharing) is ready for the final review.

@tjkandala will be handling the implementation of the changes on the extensions registry page 🎉

**Comment by AlicjaSuska** [comment]
The issue regarding ['Open in editor' feature](https://github.com/sourcegraph/sourcegraph/issues/10093) is connected with the planned work for writing new extensions for this project.

**Comment by felixfbecker** [comment]
FYI RFC 209 is shipped now: https://sourcegraph.com/extensions

**Comment by ebrodymoore** [comment]
[Here's a Looker view](https://sourcegraph.looker.com/looks/748) that evaluates it on Cloud. If this issue should still be open, then someone can re-open it. But it seems done to me based on our current priorities!
