### ISSUE TITLE
bug: underscores not appearing in search bar

### ISSUE THREAD

**Issue by gbrik** [sourcegraph/sourcegraph#11880]
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:** Firefox 77.0.1

#### Steps to reproduce:

1. Navigate to sourcegraph.com/search
2. Type '_' in the search bar

#### Expected behavior:
An underscore appears.
#### Actual behavior:
An underscore does not appear (but if you copy paste the textbox contents, you can see that there is an underscore there).

cc @sourcegraph/web

**Comment by limitedmage** [comment]
I can't repro this in the latest version of Firefox, does it still happen to you @gbrik ?

**Comment by bduffany** [comment]
Try reproducing on Chrome + Linux.
