### ISSUE TITLE
keep e2e tests in functional state during iteration

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#11886]
painfully needed by release captain to not be overwhelmed when working on the release.

- [x] CI build to run e2e daily
- [ ] CI build to run e2e regression suite daily

reserve a couple of hours each week to fix issues and get both to green as ongoing effort during an iteration

**Comment by uwedeportivo** [comment]
https://buildkite.com/sourcegraph/e2e/builds/9990

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
https://github.com/sourcegraph/sourcegraph/pull/12126
