### ISSUE TITLE
TypeScript hover shows type any

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#11893]
![image](https://user-images.githubusercontent.com/10532611/86336546-48064f00-bc50-11ea-95df-0e8fdabe378f.png)

https://github.com/sourcegraph/sourcegraph/pull/11889/files#diff-e2379b776b881f35f2e78c43de1624c0R127

**Comment by efritz** [comment]
So looking at this file there was an unrelated issue with importing `.json` files causing a 500 error from the bundle manager. This is handled in https://github.com/sourcegraph/sourcegraph/pull/12497.

The type issue no longer seems reproducible. If you see something similar again please re-open or file another issue and tag me directly so I get a fresh bundle to diagnose.

<img width="566" alt="Screen Shot 2020-07-27 at 2 49 22 PM" src="https://user-images.githubusercontent.com/103087/88585198-6590c380-d018-11ea-9fef-3f75bc763530.png">

<img width="566" alt="Screen Shot 2020-07-27 at 2 50 54 PM" src="https://user-images.githubusercontent.com/103087/88585341-9b35ac80-d018-11ea-869f-efccc500e173.png">
