### ISSUE TITLE
sourcegraph.internal.sourcegraphURL is invalid value

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1189]
This breaks the lang-typescript extension. cc @felixfbecker 	

![screenshot from 2018-11-30 00-42-46](https://user-images.githubusercontent.com/1976/49278180-dc874a80-f438-11e8-8625-434af25e21e9.png)

**Comment by felixfbecker** [comment]
I think lang-go uses this too

**Comment by sqs** [comment]
Fixed, sorry!
