### ISSUE TITLE
Reduce the impact of unplanned work

### ISSUE THREAD

**Issue by pecigonzalo** [sourcegraph/sourcegraph#11904]
We should define a process to ensure incoming requests are handled while keeping Milestone objectives on track.

- [x] Requests priority should be easy to identify
- [x] ~Requests should be categorized to facilitate subsequent reporting~

**Comment by pecigonzalo** [comment]
Removing categorization requirement for now.

I had a conversion with @dadlerj and we will work on a way to prioritize incoming issues.

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by pecigonzalo** [comment]
Priorities draft: https://github.com/sourcegraph/about/pull/1521/files

Given that PR will remain open for some time as we iterate over it, I dont think there is a reason to keep this issue open for the same period.
