### ISSUE TITLE
Change PV reclaim policy from "delete" to something else; clarify that --prune can be dangerous

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#11913]
Our default PV reclaim policy is "delete" which means disks are deleted when no longer used.

Additionally, we had a customer modify `kubectl-apply-all.sh` to specify a single file and so `--prune` deleted all deployments not specified. This ultimately didn't result in data loss (luckily) but we should carefully make two changes here:

1. Add a note to https://github.com/sourcegraph/deploy-sourcegraph/blob/master/kubectl-apply-all.sh that `--prune` is destructive unless you specify the entire `base/` directory.
2. Change our default PV reclaim policy from "delete" to something less destructive.

Customer: https://sourcegraph.slack.com/archives/CJX299FGE/p1593211681018900 https://app.hubspot.com/contacts/2762526/company/578600789/

**Comment by davejrt** [comment]
> Our default PV reclaim policy is "delete" which means disks are deleted when no longer used.

This should be set as part of the storage class like so:
```
. You can't specify the reclaimPolicy as part of a volumeClaimTemplate in statefulsets and deployments. As we rely a lot of dynamic provisioning I think this makes the most sense in this case.
