### ISSUE TITLE
Syntax Highlighting for Nix

### ISSUE THREAD

**Issue by lf-** [sourcegraph/sourcegraph#11948]
#### Feature request description

(resurrection of #152)

I'd like to have syntax highlighting in `.nix` files so I can use Sourcegraph to browse them. GitHub has this feature already, which gives it a better user experience for reading nix package code.

#### Is your feature request related to a problem? If so, please describe.

Lack of syntax highlighting makes it hard for me to read code.

#### Describe alternatives you've considered.

I normally use GitHub to browse nix package code because this feature isn't available, even though their code search and browsing otherwise sucks 😒.

**Comment by rvantonder** [comment]
And done: https://sourcegraph.com/github.com/jbboehr/php-handlebars/-/blob/nix/ci.nix

https://github.com/sourcegraph/sourcegraph/pull/19282
