### ISSUE TITLE
Fancy quotes on repogroup pages

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#11953]
These will not work when copy pasted to search queries:

![image](https://user-images.githubusercontent.com/10532611/86593952-79578580-bf96-11ea-8aff-d4feca3135da.png)

![image](https://user-images.githubusercontent.com/10532611/86593963-7e1c3980-bf96-11ea-9353-664bc23b81b9.png)

![image](https://user-images.githubusercontent.com/10532611/86594066-aa37ba80-bf96-11ea-948c-a71522d13e38.png)

**Comment by poojaj-tech** [comment]
Closing, fixed in a past PR and #https://github.com/sourcegraph/sourcegraph/pull/12061
