### ISSUE TITLE
Kubernetes repogroup icon is not transparent, looks bad in dark theme

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#11956]
![image](https://user-images.githubusercontent.com/10532611/86594533-7ad57d80-bf97-11ea-8b89-7b5fb2586abc.png)

![image](https://user-images.githubusercontent.com/10532611/86594604-9b9dd300-bf97-11ea-9357-02d7df938102.png)

I think it would be best to use SVGs, which would also prevent this problem.

**Comment by poojaj-tech** [comment]
Fixed with URL for image in #11922
