### ISSUE TITLE
Border-radius wrong in repogroup page search query input groups

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#11955]
<img width="544" alt="Screen Shot 2020-07-06 at 12 57 40" src="https://user-images.githubusercontent.com/10532611/86594228-ed922900-bf96-11ea-8759-c54517cfb442.png">

These should use [input groups](https://getbootstrap.com/docs/4.5/components/input-group/#button-addons)

cc @poojaj-tech @christinaforney

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by attfarhan** [comment]
what page was this on @felixfbecker? I don't see this issue anymore on repogroup pages, perhaps fixed?

**Comment by poojaj-tech** [comment]
<img width="781" alt="Screen Shot 2020-07-19 at 9 36 04 PM" src="https://user-images.githubusercontent.com/57463526/87900036-f871a280-ca07-11ea-879e-1827fc24a301.png">
This was on the repogroup page. Verified that it doesn't repo anymore.
