### ISSUE TITLE
Update to the new Sourcegraph logo

### ISSUE THREAD

**Issue by christinaforney** [sourcegraph/sourcegraph#12008]
The new marketing site will be going live tomorrow 2020-07-08 and has a new Sourcegraph logo in use. Please update the product to use the new assets. Please be sure it updates in both the product and the docs.

@aileenrose - can you please share access to the new assets for the team to use?

**Comment by aileenrose** [comment]
New logo files can be found here:
https://drive.google.com/drive/folders/17HFjTFe4q8KLXsu7LoLS_lIgOT1OARiP?usp=sharing
