### ISSUE TITLE
feedback collection: k8s configurations

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#12000]
- https://sourcegraph.slack.com/archives/CJX299FGE/p1591127578463200
- https://docs.sourcegraph.com/admin/install/kubernetes/configure
- gitserver network changes / SSH keys
- using Sourcegraph with external Postgres/Redis
- nodeSelectors
- https://sourcegraph.slack.com/archives/CJX299FGE/p1583437361204200?thread_ts=1583437108.204100&cid=CJX299FGE
- RBAC
- Running users as root vs. non-root: https://github.com/sourcegraph/deploy-sourcegraph/tree/master/overlays/non-root
- Removing Prometheus due to k8s service discovery
- namespaced: https://github.com/sourcegraph/deploy-sourcegraph/tree/master/overlays/namespaced
- non-privileged deployment: https://github.com/sourcegraph/deploy-sourcegraph/tree/master/overlays/non-privileged

**Comment by uwedeportivo** [comment]
some customizations seen at customers:

- different image registry
- image name prefix
- image name suffix
- image names without the sha256 suffix
- minikube specific: no storageclassname
- different storageclassname
- remove our labels and add their labels
- have two sets of labels (one for devel, one for prod)

**Comment by uwedeportivo** [comment]
some more:
- make components optional
- make certain resources optional (like PVCs), since some customers create PVs directly with claimrefs tailored for the statefulsets

**Comment by daxmc99** [comment]
This blocked our ingress upgrade work since we were not sure how many customers used our bundled ingress
