### ISSUE TITLE
structural search doesn't work when @commit is an alias for HEAD

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#12012]
Probably broken by the recent Zoekt restructuring. Even though structural search can't work yet for searching at arbitrary indexed commits and it's fine to punt, it should still work at a commit that is auto-populated that resolves to HEAD.

<img width="1041" alt="Screen Shot 2020-07-07 at 11 34 40 AM" src="https://user-images.githubusercontent.com/888624/86868501-ab95df80-c089-11ea-8aab-f12bd979a4e2.png">

CC @keegancsmith

**Comment by keegancsmith** [comment]
Indeed, this was broken by https://github.com/sourcegraph/sourcegraph/pull/11931

It was too strict, it skipped the bit of logic which matched up revs to HEAD. The tricky part is its hard to tell if we are searching things other than HEAD. However, after the indexedRepoRevs change, it should be easier :) I'll fix this today!

**Comment by rvantonder** [comment]
No pressure, I'm just keeping note of it :-) Feel free to ignore and rush the index work. We can clean up after (I'm serious about attempting to tackle merging the Zoekt functions, just not while the parts are moving).

**Comment by keegancsmith** [comment]
Working again on dotcom
