### ISSUE TITLE
precise-code-intel on sourcegraph.com running out of disk space

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#12014]
@sourcegraph/code-intel we are trying to resolve some open alerts on sourcegraph.com as part of https://github.com/sourcegraph/sourcegraph/issues/12011

We are seeing that on sourcegraph.com precise-code-intel-bundle-manager is running out of disk space. It has < 15% remaining currently.

More specifically, I want to know:

1. At what % usage remaining would you like to get emails/slack notifications about disk space being low?
2. At what point would you like to get paged about disk usage being low via OpsGenie (in the future, [as part of RFC 189](https://docs.google.com/document/d/1noZf86g2QwTbFNt3XSSbMg36D-_HCptP1thMzZsgt2Q/edit))?

Currently it would be set to warn you at 25% remaining and page you at 15% remaining (but it won't actually page/notify you anywhere yet, just visible on https://sourcegraph.com/-/debug/grafana).

**Comment by efritz** [comment]
I think these are good starting points.

**Comment by bobheadxi** [comment]
This alert is also the one currently giving us a red banner on dot-com:

<img width="594" alt="image" src="https://user-images.githubusercontent.com/23356519/87018688-2daa1380-c204-11ea-8089-ea2ad724fccd.png">

I'm working on silencing which should be ready soon (https://github.com/sourcegraph/sourcegraph/issues/11210), would we be silencing this for dot-com or trying to resolve it through other means?

**Comment by bobheadxi** [comment]
At @keegancsmith 's [request](https://sourcegraph.slack.com/archives/CMBA8F926/p1594284636025000?thread_ts=1594282438.022900&cid=CMBA8F926), I've created a manual silence for now (72h) :)

**Comment by bobheadxi** [comment]
Link to discussion: https://sourcegraph.slack.com/archives/CMBA8F926/p1594221125015500

**Comment by slimsag** [comment]
@bobheadxi this looks resolved, closing - if I am wrong please reopen.
