### ISSUE TITLE
Error message overlays when writing code snippets in PR comments!

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [sourcegraph/sourcegraph#1201]
- **Sourcegraph version:** _N/A_
- **Platform information:** Chrome 70, Windows 10 with the Sourcegraph extension

#### Steps to reproduce:

1. Go to a PR to review on GitHub. I used https://github.com/Microsoft/tslint-microsoft-contrib/pull/651/
2. Start typing in the following text:

```markdown
Use `|| !tsutils.
```

#### Expected behavior:

Nothing Sourcegraph-related should happen. Why would it?

#### Actual behavior:

```
1 error occurred: * symbol search failed: Post http://10.188.11.72:3184/search: dial tcp 10.188.11.72:3184: connect: connection refused
```

![image](https://user-images.githubusercontent.com/3335181/49336389-33665e80-f5b6-11e8-98a7-cd355f7b82fc.png)

Amusingly, I got a similar popup writing up this issue:

![image](https://user-images.githubusercontent.com/3335181/49336400-53961d80-f5b6-11e8-9e57-e597f9cdc09e.png)

Edit: ooh, and more while typing! From this text:

```markdown
Use `|| !tsutils.isStringLiteral(expression
```

...I get this:

```
type error at character 65: error parsing regexp: missing closing ): `tsutils.isStringLiteral(expression`
```

![image](https://user-images.githubusercontent.com/3335181/49336409-8213f880-f5b6-11e8-96fc-d0271a4642c4.png)

**Comment by sqs** [comment]
This is triggering the symbol search autocomplete, which lets you autocomplete symbols in your code as you would for usernames and issues.

It should not be erroring and should not be triggering in this case. Sorry, we will fix this soon.
