### ISSUE TITLE
sourcegraph.com shows global warning banner "Unable to fetch alerts status: status 404"

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#12022]
![image](https://user-images.githubusercontent.com/10532611/86919861-24984400-c129-11ea-9607-60bad59e6d44.png)

This comes from the backend in the `SiteFlags` query:

![image](https://user-images.githubusercontent.com/10532611/86919896-2f52d900-c129-11ea-9d2d-9bec93955106.png)

**Comment by pecigonzalo** [comment]
Most likely related to https://github.com/sourcegraph/sourcegraph/pull/11957

**Comment by keegancsmith** [comment]
Note this only seems to be shown for admins. I tried in incognito and didn't get the banner.

**Comment by bobheadxi** [comment]
I believe this will be fixed by https://github.com/sourcegraph/deploy-sourcegraph-dot-com/pull/2929 - will report back in a few minutes. What seems to have happened:

* new feature is added involving both frontend and prometheus (https://github.com/sourcegraph/sourcegraph/pull/11957)
* frontend is automatically updated, prometheus is not
* woes

**Comment by bobheadxi** [comment]
The correct alert is now showing: 

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/23356519/86924396-fb47da00-c161-11ea-9f70-5bdf457ca708.png">

As @keegancsmith noted, this is only visible to admins

**Comment by bobheadxi** [comment]
Some follow-up items:

* [ ] prometheus not updated in lockstep with everything else might be problematic
* [ ] the banner is grammatically incorrect at the moment for singular alert/service

**Comment by bobheadxi** [comment]
I've opened up followup issues for the above items - since this specific problem is resolved, I'll close this now :) Thanks for reporting this @felixfbecker!
