### ISSUE TITLE
monitoring: alerting followups

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#12026]
This issue tracks follow-ups to the slew of alerting features recently added/in flight:

* https://github.com/sourcegraph/sourcegraph/issues/11452
* https://github.com/sourcegraph/sourcegraph/issues/11517
* https://github.com/sourcegraph/sourcegraph/issues/5370 (addressing incrementally)

Adding this to 3.18 because anything tracked here is probably something we need to fix before shipping all this stuff

### Items

* [x] critical alerts banner is grammatically incorrect at the moment for singular alert/service ("singular _are_ firing") => https://github.com/sourcegraph/sourcegraph/pull/12045
* [x] link to grafana is bust (goes to a search) - https://sourcegraph.slack.com/archives/CHPC7UX16/p1594216721153200?thread_ts=1594212174.150300&cid=CHPC7UX16 => https://github.com/sourcegraph/sourcegraph/pull/12045
* [x] `#alerts` is wicked noisy - determine what we can do to reduce this (ie prevent repeated alerts from firing too frequently) => https://github.com/sourcegraph/sourcegraph/pull/12046
* [x] opsgenie alert labels not very compatible with slack https://sourcegraph.slack.com/archives/C0J618TTM/p1594287803014000 => https://github.com/sourcegraph/deploy-sourcegraph/pull/786

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
