### ISSUE TITLE
Symbols service was unavailable, didn't alert

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1202]
The symbols service was unavailable, spewing logs like:

```
2018/12/02 12:21:03 received error during background config update, err: unable to fetch new configuration: internal API response error code 404: no route
 (http://sourcegraph-frontend-internal/.internal/configuration/raw-json)
2018/12/02 12:21:07 received error during background config update, err: unable to fetch new configuration: internal API response error code 404: no route
 (http://sourcegraph-frontend-internal/.internal/configuration/raw-json)
2018/12/02 12:21:09 received error during background config update, err: unable to fetch new configuration: internal API response error code 404: no route
 (http://sourcegraph-frontend-internal/.internal/configuration/raw-json)
2018/12/02 12:21:14 received error during background config update, err: unable to fetch new configuration: internal API response error code 404: no route
 (http://sourcegraph-frontend-internal/.internal/configuration/raw-json)
```

(This was caused by a long-time deployment issue that @ggilmore is working on fixing.)

Despite this unavailability, there was no OpsGenie alert for the downtime. I only noticed it when a user reported it at https://twitter.com/bweston92/status/1069199874393034753 (and in hindsight it turned out to be one of the causes of #1201 too).

We need to set up alerting so that we would have caught this issue. (A similar issue happened with lsp-proxy 2-3 days ago, too.)

Assigning to @nicksnyder 	to figure out who should own this.

**Comment by nicksnyder** [comment]
Agree that we need alerting for this. Will revisit alerting after we have our new deployment process ironed out.

**Comment by ggilmore** [comment]
Maybe the solution is to have proper k8s health check for the symbols service that fails if the config is unable to be read

**Comment by ggilmore** [comment]
Closed via https://github.com/sourcegraph/deploy-sourcegraph-dot-com/commit/fc1a14158c78e43cd5d760c60aa230835f86de76
