### ISSUE TITLE
Use Chromatic to host our Storybook

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#12054]
As we get more designers on the team, we need to make sure design and engineering is a two-way street, so we can discover any inconsistencies.

We have Storybook for our component library. It doesn't include all components yet, but improves developer experience a lot and can also be used for screenshot testing. Components in the storybook can easily be looked at by designers without having to reproduce a lot of backend state.

However, they currently still require cloning and building the repo, which is not a hurdle for engineers, but is one for designers. There is also no channel to discuss what is inside the storybook.

[Chromatic](https://www.chromatic.com/) by the storybook creators solves this. It can host our storybook and allows commenting on it (more granularly than in Percy). It supports versioning (tied to git) and can replace our use of Percy for Storybook screenshot tests.

cc @AlicjaSuska @rrhyne

**Comment by rrhyne** [comment]
Not apposed, but personally, I am referring to storybook quite a bit on various branches without issue (other than a node version mismatch between sourcegraph and storybook). 

My main issue is that it is a manual process to go between storybook and Figma to view inconsistencies. 

Does Chromatic tool support plugins such as this one?

https://www.figma.com/resources/extensions-and-apis/storybook-figma-addon/

**Comment by eseliger** [comment]
Just tried it, adding a Figma design using your suggested plugin works (locally and in the Chromatic hosted version):

![image](https://user-images.githubusercontent.com/19534377/87099153-556f9a80-c249-11ea-82a3-42c95301cf10.png)

**Comment by AlicjaSuska** [comment]
Thank you for bringing this up Felix! It seems like a good addition to the workflow. In particular, I like the ability to have discussions exclusively about the components!
