### ISSUE TITLE
Group search results by the repositories or files that contain matches

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#12055]
Aggregate/combine search results by repo or file

Discussed recently at https://sourcegraph.slack.com/archives/CHEKCRWKV/p1591740072200200

Requested by:

* https://app.hubspot.com/contacts/2762526/company/693777200

>I’m searching for a specific text and I just want to see the list of files where this text appears in and not the content of the files when you search them?

* https://app.hubspot.com/contacts/2762526/company/1737648116

>not every file that this appears in, but rather repo level. is that available?

* https://app.hubspot.com/contacts/2762526/company/557692805

>is there a way through the UI to simply return a repo or file list without pulling back the code? ... and is there a way to get the total repo / file count without having to attempt pulling back the code results ... for example, this search result without a count qualifier comes back quickly but i only get an indication of 65+ results when there are hundreds (maybe thousands) ...

* https://app.hubspot.com/contacts/2762526/company/407948923 (multiple times)

>btw, all I really want here is to find the number of repos for which a condition exists. It'd be great if there could be an instruction for that
>
>pretty common thing we have to do. Find the number of repos to establish how widespread something is

Comments from the team:

@sqs: Try out https://sourcegraph.com/extensions/sourcegraph/search-export and see if that would solve their problem

@slimsag:
You can also use the CLI for this:
`$ src search -json 'foobar count:99999999' | jq -r '.Results[].repository.name'`
It'll give you a plaintext list of all the repositories

**Comment by christinelovett** [comment]
Requested by: https://app.hubspot.com/contacts/2762526/company/4239202221

**Comment by dadlerj** [comment]
Requested by https://app.hubspot.com/contacts/2762526/company/557692737

>Also here is a user case get from teams and hope you can help to answer, user would like to know which repos contains the query condition but not the detail of code, for this case does sourcegrahp support?

>For below snapshot, with the query ”import org.REDACTED” user hope it can only list the repos show the REDACTED and REDACTED so he can quickly do action with these repo

>It could be only simply collapse all only leave the “result-container__header”? or show all result repo in Repositories tag? As Repositories tag only works for repo name search?

**Comment by rvantonder** [comment]
Closed by Closed by https://github.com/sourcegraph/sourcegraph/pull/19236
