### ISSUE TITLE
deploy-sourcegraph-dhall: indexed-search: implement generate reading from config

### ISSUE THREAD

**Issue by uwedeportivo** [sourcegraph/sourcegraph#12068]
right now the generate function in prometheus https://github.com/sourcegraph/deploy-sourcegraph-dhall/blob/master/src/base/github-proxy/generate.dhall doesn't read the configuration that is passed into it. 

we want to read enough configuration to support configuring these params:

https://github.com/sourcegraph/deploy-sourcegraph-dogfood-k8s/blob/ca1a4d1a7e678f6fa65abd2fdab5047fff31000e/generated/params.sh

- implement templating logic
- maybe add more fields in the global config
- if needed: implement transformations

provide an example pipeline config that declares the changes from dogfood for indexed-search.

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
support for this:

```
  'set_replicas indexed-search 2'
  'set_cpu_limit indexed-search zoekt-webserver 12'
  'set_memory_limit indexed-search zoekt-webserver 120Gi'
  'set_cpu_request indexed-search zoekt-webserver 12'
  'set_memory_request indexed-search zoekt-webserver 120Gi'
  'set_stateful_set_persistent_volume_claim_capacity indexed-search data 4Ti'
  'set_container_image indexed-search zoekt-webserver index.docker.io/sourcegraph/indexed-searcher:insiders@sha256:8324943e1b52466dc2052cf82bfd22b18ad045346d2b0ea403b4674f48214602'
  'set_container_image indexed-search zoekt-indexserver index.docker.io/sourcegraph/search-indexer:insiders@sha256:f31ec682b907bde2975acda88ee99ac268ef32a79309a6036ef5f26e8af0dcac'
  'set_ephemeral_resource_request indexed-search zoekt-webserver 1Gi'
  'set_ephemeral_resource_limit indexed-search zoekt-webserver 1Gi'
  'set_ephemeral_resource_request indexed-search zoekt-indexserver 1Gi'
  'set_ephemeral_resource_limit indexed-search zoekt-indexserver 1Gi'
```

**Comment by uwedeportivo** [comment]
https://github.com/sourcegraph/deploy-sourcegraph-dhall/pull/11 covers it
