### ISSUE TITLE
deploy-sourcegraph-dhall: prometheus: implement generate reading from config

### ISSUE THREAD

**Issue by uwedeportivo** [sourcegraph/sourcegraph#12063]
right now the generate function in prometheus https://github.com/sourcegraph/deploy-sourcegraph-dhall/blob/master/src/base/prometheus/generate.dhall doesn't read the configuration that is passed into it. 

we want to read enough configuration to support configuring these params:

https://github.com/sourcegraph/deploy-sourcegraph-dogfood-k8s/blob/ca1a4d1a7e678f6fa65abd2fdab5047fff31000e/generated/params.sh#L70-L74

- implement templating logic
- maybe add more fields in the global config
- if needed: implement transformations

provide an example pipeline config that declares the changes from dogfood for prometheus.

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
https://github.com/sourcegraph/sourcegraph/issues/12063

**Comment by uwedeportivo** [comment]
the equivalent of

```
  'set_memory_limit prometheus prometheus 2G'
  'set_memory_request prometheus prometheus 500M'
  'set_container_image prometheus prometheus index.docker.io/sourcegraph/prometheus:insiders@sha256:8906de7028ec7ecfcfecb63335dc47fe70dbf50d8741699eaaa17ea2ddfa857e'
  'set_ephemeral_resource_request prometheus prometheus 1Gi'
  'set_ephemeral_resource_limit prometheus prometheus 1Gi'
```

is something like this:

```
let c =
      Configuration/global::{=}
      with Prometheus.Deployment.Containers.Prometheus.resources.limits.memory = Some
          "2G"
      with Prometheus.Deployment.Containers.Prometheus.resources.requests.memory = Some
          "500M"
      with Prometheus.Deployment.Containers.Prometheus.image = Some
          "index.docker.io/sourcegraph/prometheus:insiders@sha256:8906de7028ec7ecfcfecb63335dc47fe70dbf50d8741699eaaa17ea2ddfa857e"
      with Prometheus.Deployment.Containers.Prometheus.resources.requests.ephemeralStorage = Some
          "1Gi"
      with Prometheus.Deployment.Containers.Prometheus.resources.limits.ephemeralStorage = Some
          "1Gi"
```

diff looks like this

<img width="1383" alt="Screen Shot 2020-07-13 at 2 49 22 PM" src="https://user-images.githubusercontent.com/534011/87357127-33f80280-c518-11ea-83cb-6c3f0f780efa.png">

**Comment by uwedeportivo** [comment]
https://github.com/sourcegraph/deploy-sourcegraph-dhall/pull/9

**Comment by uwedeportivo** [comment]
closing this even though PR hasn't landed yet (just to show progress :-) ). PR implements the desired customizations
