### ISSUE TITLE
deploy-sourcegraph-dhall: symbols: implement generate reading from config

### ISSUE THREAD

**Issue by uwedeportivo** [sourcegraph/sourcegraph#12076]
right now the generate function in prometheus https://github.com/sourcegraph/deploy-sourcegraph-dhall/blob/master/src/base/symbols/generate.dhall doesn't read the configuration that is passed into it. 

we want to read enough configuration to support configuring these params:

https://github.com/sourcegraph/deploy-sourcegraph-dogfood-k8s/blob/ca1a4d1a7e678f6fa65abd2fdab5047fff31000e/generated/params.sh

- implement templating logic
- maybe add more fields in the global config
- if needed: implement transformations

provide an example pipeline config that declares the changes from dogfood for symbols.

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
https://github.com/sourcegraph/deploy-sourcegraph-dhall/pull/13
