### ISSUE TITLE
saved searches run too frequently, scheduler is naive and results in search perf issues

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#12102]
We have had an ongoing performance investigation with https://app.hubspot.com/contacts/2762526/company/419771425/ in which it has been identified that the way we run saved searches is:

1. Too naive (based on time it takes to query)
2. Far too frequent (e.g. thousands of queries running per second)
3. Not accounting for repository updates (we only want "new" results so it's kinda silly that we rerun searches even on repositories that have not been updated since we last checked)

This goes with the general theme that saved searches is, frankly, a poor implementation and needs major overhauling / reconsideration.

As a workaround, `FORCE_RUN_INTERVAL=10m` can be set on the `query-runner` which reduces the frequency of the searches (but still runs them in large bursts, which is horrible).

**Comment by lguychard** [comment]
Cc @camdencheek -- we no longer have saved searches, but I don't think the code monitoring scheduler is much smarter yet.
