### ISSUE TITLE
deploy-sourcegraph-dhall: grafana: implement new configuration logic for k8s.sgdev.org

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#12109]
Right now the `generate` function in Grafana https://github.com/sourcegraph/deploy-sourcegraph-dhall/blob/master/src/base/grafana/generate.dhall doesn't actually read the configuration that's passed to it . 

https://github.com/sourcegraph/deploy-sourcegraph-dogfood-k8s/blob/ca1a4d1a7e678f6fa65abd2fdab5047fff31000e/generated/params.sh#L38-L44

This issue tracks the work that's needed to implement the k8s.sgdev.org transformations specified for Redis in the above file. 

- new configuration fields will need to be added to https://github.com/sourcegraph/deploy-sourcegraph-dhall/blob/master/src/base/grafana/configuration.dhall
- new logic will need to be written in https://github.com/sourcegraph/deploy-sourcegraph-dhall/blob/master/src/base/grafana/generate.dhall to support these new transformations. 

The PR implementing this functionality will include an example pipeline configuration in the description that declares the same transformations as the ones linked above.

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by daxmc99** [comment]
Not currently in progress
