### ISSUE TITLE
no authentication provider is set in site configuration.

### ISSUE THREAD

**Issue by adam-moss** [sourcegraph/sourcegraph#1210]
- **Sourcegraph version:** 2.13.5
- **Platform information:** CentOS 7, Docker-CE 12.12.1

#### Steps to reproduce:

1. Start docker container with volume mounts to config and data

#### Expected behaviour:
Container starts correctly, sourcegraph is accessible

#### Actual behavior:
Container starts but sourcegraph is not accessible, throwing error
>Access to Sourcegraph is forbidden because no authentication provider is set in site configuration.

Config is using the `builtin` auth provider.

**Comment by adam-moss** [comment]
Closing, reviewed the contents of https://github.com/sourcegraph/sourcegraph/commit/795c190823be0a74d404c508e64d72f5a5b32cac and have updated the config file to support the new properties.

**Comment by sqs** [comment]
We will be adding support for migrating config automatically in 3.0 or 3.1 to avoid this kind of issue. Sorry for the disruption and glad you found that.
