### ISSUE TITLE
Search result match count display different by 1

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#12106]
Oddly, the repo button shows 39 matches, while the results list shows 40 matches

Not a big deal, just noticed it during a demo.

Reproducible: https://sourcegraph.com/search?q=new+auth+provider+repo:%5Egithub.com/sourcegraph/sourcegraph%24+lang:go+-file:_test%5C.go%24&patternType=regexp

![image](https://user-images.githubusercontent.com/5589410/87207247-58f23880-c2c0-11ea-8bc0-b906bbae9479.png)

**Comment by rvantonder** [comment]
Nice find. There are 40 results indeed, so it's got to be something around where we generate the filter/chip data. Haven't touched that recently so no clue off the bat. Will investigate.

**Comment by dadlerj** [comment]
Thanks, but this isn't high priority from my perspective

**Comment by rvantonder** [comment]
Can't reproduce any more--looks fixed. There were some changes to suggestions/result count code since.
