### ISSUE TITLE
kubernetes cadvisor container_spec_memory_limit_bytes is zero

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#12114]
The [percentage memory usage metric we have and alert on](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@985c423d2de6eac234f2aabd6ad1b5ecfb2dbea3/-/blob/docker-images/prometheus/config/cadvisor_rules.yml#L16-18) is sometimes not functioning on sourcegraph.com because the native cadvisor `memory_limit_bytes` metric is just zero, oddly.

This shows it is happening for something like ~40 containers:

https://sourcegraph.com/-/debug/grafana/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Prometheus%22,%7B%22expr%22:%22container_spec_memory_limit_bytes%20%3D%3D%200%22%7D,%7B%22mode%22:%22Metrics%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D

**Comment by slimsag** [comment]
Thought: this could likely be due to cadvisor crashing in prod on some nodes due to lang-typescript.

**Comment by bobheadxi** [comment]
cadvisor seems to be fine in prod: https://console.cloud.google.com/kubernetes/daemonset/us-central1-f/dot-com/prod/cadvisor/details?authuser=2&folder=&organizationId=&project=sourcegraph-dev

**Comment by bobheadxi** [comment]
The `image` label on these seem to imply they aren't really Sourcegraph containers 🤔 

<img width="175" alt="image" src="https://user-images.githubusercontent.com/23356519/87260270-8c60dd00-c4e3-11ea-93cd-cc1189df1d59.png">

https://stackoverflow.com/questions/53258342/what-is-the-use-of-a-pause-image-in-kubernetes

**Comment by bobheadxi** [comment]
Removing `k8s` images leaves us with some containers that also don't seem sourcegraph-related:

https://sourcegraph.com/-/debug/grafana/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Prometheus%22,%7B%22expr%22:%22container_spec_memory_limit_bytes%7Bimage!~%5C%22k8s%5C%5C.gcr%5C%5C.io.*%5C%22%7D%20%3D%3D%200%22%7D,%7B%22mode%22:%22Metrics%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D

<img width="388" alt="image" src="https://user-images.githubusercontent.com/23356519/87260377-2cb70180-c4e4-11ea-8077-04b18c5e5f53.png">

**Comment by slimsag** [comment]
I was definitely seeing some like sourcegraph-frontend with NaN values, I considered grabbing a screenshot but I figured that wouldn’t help us reproduce it, I’ll see if I can reproduce it later

**Comment by bobheadxi** [comment]
> I was definitely seeing some like sourcegraph-frontend with NaN values

It seems some of the `k8s.grc.io` containers run in the same namespace as our stuff, so it looks relevant, but I don't think they're relevant - we create the % mem usage alert on `name`, and querying for relevant frontend metrics via:

```
container_spec_memory_limit_bytes{name=~".*frontend.*",name!~".*(_POD_|_jaeger-agent_).*"}
```

gives no non-zero metrics https://sourcegraph.com/-/debug/grafana/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Prometheus%22,%7B%22expr%22:%22container_spec_memory_limit_bytes%7Bname%3D~%5C%22.*frontend.*%5C%22,name!~%5C%22.*(_POD_%7C_jaeger-agent_).*%5C%22%7D%22%7D,%7B%22mode%22:%22Metrics%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D

**Comment by bobheadxi** [comment]
Closing, everything seems fine: https://sourcegraph.com/-/debug/grafana/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Prometheus%22,%7B%22expr%22:%22container_memory_working_set_bytes%7Bname%3D~%5C%22frontend.*%5C%22%7D%22,%22requestId%22:%22Q-bf59c785-e8ff-4fd6-85c0-1796599042a0-0A%22%7D%5D
