### ISSUE TITLE
deploy-sourcegraph-dhall: incrementally migrate sourcegraph.com services over to dhall

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#12113]
In order to gather more feedback from @sourcegraph/distribution about the following aspects of [deploy-sourcegraph-dhall](https://github.com/sourcegraph/deploy-sourcegraph-dhall):

- what it's like to make larger changes to [deploy-sourcegraph-dhall](https://github.com/sourcegraph/deploy-sourcegraph-dhall)'s components (adding new templating logic for more configuration options, adding new fields to the global configuration type)

- what the pure-yaml -> dhall migration experience is like

I propose the following: 

A member of @sourcegraph/distribution (other than @ggilmore  or @uwedeportivo) will migrate the following subset of sourcegraph.com services to [deploy-sourcegraph-dhall](https://github.com/sourcegraph/deploy-sourcegraph-dhall):

- [ ] [Precise Code Intel](https://github.com/sourcegraph/deploy-sourcegraph-dot-com/tree/release/base/precise-code-intel) (not as risky as frontend, but will still likely see a good amount of changes)
- [ ] [Redis](https://github.com/sourcegraph/deploy-sourcegraph-dot-com/tree/release/base/redis) 
- [ ] [Prometheus](https://github.com/sourcegraph/deploy-sourcegraph-dot-com/blob/release/base/prometheus/prometheus.Deployment.yaml) 

In the end state: 

- The above components will have their folders / K8s YAML files removed from 'base/' on [deploy-sourcegraph-dot-com](https://github.com/sourcegraph/deploy-sourcegraph-dot-com/)
- [deploy-sourcegraph-dot-com](https://github.com/sourcegraph/deploy-sourcegraph-dot-com/) will contain a dhall configuration pipeline that outputs a K8s YAML file that's semantically equivalent to what was in `base/` before. This YAML file will be checked into the repository. 
- [deploy-sourcegraph-dot-com](https://github.com/sourcegraph/deploy-sourcegraph-dot-com/)'s CI will kubectl apply this new K8s YAML from dhall in addition to the remaining K8s YAML from services that haven't been migrated

This change should be entirely transparent since the K8s YAML that [deploy-sourcegraph-dhall](https://github.com/sourcegraph/deploy-sourcegraph-dhall) generates  will be semantically identical to what was there before. 

--- 

Note: Unlike https://github.com/sourcegraph/sourcegraph/issues/11830, [deploy-sourcegraph-dot-com](https://github.com/sourcegraph/deploy-sourcegraph-dot-com/) doesn't have a clean diff that clearly shows the transformations that will need to be made to the base configuration. This is a known problem that will need to be solved (see https://github.com/sourcegraph/sourcegraph/issues/12110). 

To start off with, the implementer will rely on the `git diff` output between [deploy-sourcegraph-dot-com](https://github.com/sourcegraph/deploy-sourcegraph-dot-com/) and [deploy-sourcegraph](https://github.com/sourcegraph/deploy-sourcegraph-dot-com/). If this proves to be insufficient, then @ggilmore will use the implementer's feedback to figure which of the solutions from https://github.com/sourcegraph/sourcegraph/issues/12110 we should invest in.

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
