### ISSUE TITLE
A ResolveRev GraphQL request to the public Sourcegraph.com was blocked because the current repository is private.

### ISSUE THREAD

**Issue by ijsnow** [sourcegraph/sourcegraph#1212]
We should catch and handle the error we throw for requesting data for private repos from sourcegraph.com. 

```
A ResolveRev GraphQL request to the public Sourcegraph.com was blocked because the current repository is private.
```

https://sentry.io/sourcegraph/browser-extension/issues/787219392/?query=is:unresolved

**Comment by ijsnow** [comment]
Linked the wrong issue in that PR so reopening.

**Comment by lguychard** [comment]
We now handle this error correctly.
