### ISSUE TITLE
Sourcegraph.com status page

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#12138]
It'd be nice to have a sourcegraph.com status page, similar to e.g. https://www.githubstatus.com/

Thought: This could be a near 1:1 display of the Grafana homepage dashboard + a custom message from us?

Requested by [a user over Twitter](https://twitter.com/leftpaddotpy/status/1282861560226971649) (among many others in the past)

**Comment by bobheadxi** [comment]
FWIW, [GitLab has a public Grafana dashboard](https://dashboards.gitlab.com/) (and so does [Wikimedia](https://grafana.wikimedia.org/))

**Comment by tsenart** [comment]
https://www.atlassian.com/software/statuspage

**Comment by daxmc99** [comment]
Clarification: 
Limited to Sourcegraph.com, simple MVP 

Concerns: 
What is our definition of "down" for the MVP? 
Ensure the alert we use is not "flaky"
