### ISSUE TITLE
Query definition and hover provider so we can correctly badge results

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#12133]
In the code intel extensions, the definition may be imprecise but a hover may be precise (this occurs with go stdlib values where definitions aren't resolvable via LSIF the hovers are). We need to query the definition along with the hover in order to send back a properly badged value.

**Comment by hitzhangjie** [comment]
I don't know what happended, I came across a similar problem.

hover and click go to the definition...the UI says it keeps querying, but all failed.

It could find the references but go to definition fail.

![image](https://user-images.githubusercontent.com/3725760/89330272-9761f400-d6c2-11ea-8b15-7f80c3124d30.png)

**Comment by efritz** [comment]
Can you send a link to the repo where this is a problem? Is it consistent with this repository?

**Comment by efritz** [comment]
@hitzhangjie We had someone else report the same issue and this is fixed in https://github.com/sourcegraph/code-intel-extensions/pull/453. Sorry for the trouble!
