### ISSUE TITLE
Tour implementation

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#12137]
Implement the tour design to aid users in getting started with Sourcegraph search. 

* See [Wireframes](https://www.figma.com/file/MtDahkziU3Yrag00mn8LmG/RFC-159.2-Tour?node-id=31%3A372) page for copy and all screens
* See [Visual Design](https://www.figma.com/file/MtDahkziU3Yrag00mn8LmG/RFC-159.2-Tour?node-id=108%3A0) page for layout with redlines, colors, etc. 
* See [flowchart](https://www.figma.com/file/MtDahkziU3Yrag00mn8LmG/RFC-159.2-Tour?node-id=119%3A0) page for interaction steps. 

The workflow page should guide you on how each stage is triggered. Some general rules:

- The tour starts with a user (cloud or enterprise) who has not yet seen the tour clicks in the search bar. 
- If we can, we should not show the tour to users who have already performed a search.  
- Some stages are triggered on a delay when the user types, some when the user makes a selection. 
- Clicking outside the tour should not close the tour

**Comment by ebrodymoore** [comment]
From #11833 

For the analytics, the ideal scenario is adding these two events:
- `ViewOnboardingTour` (when the onboarding tour is shown)
- `CloseOnboardingTourClicked` with the stage/step the user was at in the tour (e.g. `stage: 2`)
