### ISSUE TITLE
gqltest: migrate internal/cmd/search-integration-tester

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#12143]
`internal/cmd/search-integration-tester` contains many search integration tests, some of them are taken from [Backend e2e and regression tests audit](https://docs.google.com/spreadsheets/d/1lzKnWbI-zTlaqnHqzW5Ju1JF0dsov7s9RE6DyFeQmRk/edit#gid=0) (marked as **HOLD**) by @rvantonder (initially in https://github.com/sourcegraph/sourcegraph/pull/10712).

**Comment by rvantonder** [comment]
LMK if/how I can help. Some of those tests check whether certain alerts are returned, I think, so when migrating the GQL query just needs to be updated to get the thing being tested (like alerts).

**Comment by unknwon** [comment]
> LMK if/how I can help. Some of those tests check whether certain alerts are returned, I think, so when migrating the GQL query just needs to be updated to get the thing being tested (like alerts).

Definitely, I'll also make sure you can easily do the tests you're interested easily. Most likely will be:

```
cd dev/gqltest && go test -tags gqltest -run TestSearch
```

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
