### ISSUE TITLE
No TypeScript hover from LSIF in our repo (but shows hover in VS Code)

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#12147]
https://sourcegraph.com/github.com/sourcegraph/sourcegraph@138e2f89a0136fab21d5f76a981c38e686f281d9/-/blob/web/src/search/input/MonacoQueryInput.tsx#L193:13

I wanted to learn what type that prop is (what options it accepts) but didn't get a hover content:

![image](https://user-images.githubusercontent.com/10532611/87414393-07052780-c5cc-11ea-97b1-97c5754445c6.png)

VS Code:

![image](https://user-images.githubusercontent.com/10532611/87414381-02407380-c5cc-11ea-91cb-6ef07fda07ee.png)

**Comment by felixfbecker** [comment]
I can see in the network tab though that the `Ranges` response did return hover content for this:

![image](https://user-images.githubusercontent.com/10532611/87415171-0d47d380-c5cd-11ea-972e-73c50b104402.png)

**Comment by efritz** [comment]
This should be fixed in https://github.com/sourcegraph/code-intel-extensions/pull/421

**Comment by efritz** [comment]
The issue was that lsif-tsc outputs multiple ranges overlapping that position - one for the symbol an done for the containing object literal. It just happens that the hover text for the outer range is empty and is returned first by Array.find.
