### ISSUE TITLE
RFC 196 Tracking Issue

### ISSUE THREAD

**Issue by chayim** [sourcegraph/sourcegraph#12166]
Tracks work on [RFC 196](https://docs.google.com/document/d/1e10UPwmI16VAQleBK81EQMMGTRBgihI1vwL5I6kicrA)
#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by tsenart** [comment]
@chayim: Here's what another RFC tracking issue looks like: https://github.com/sourcegraph/sourcegraph/issues/11526. You can still rely on the tracking-issue tool to keep this updated. You just have to create a label, say `RFC-196`, and then add that label to this tracking issue and to the issues it tracks. To read more about this: https://about.sourcegraph.com/handbook/engineering/tracking_issues#populating-and-maintaining-a-tracking-issue

**Comment by chayim** [comment]
Tracked elsewhere - closing.
