### ISSUE TITLE
Make bundle manager janitor more lenient during disaster recovery

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#12168]
In order to prevent the deletion of ... everything, we need to make the janitor have a small grace period between marking a record as deletable and actually deleting it. Forgetting to set a flag to disable the janitor during migrations, postgres failover, or persistent volume resizes can cause a cascading data deletion which is extremely undesirable.

Implementation details in [RFC 205](https://docs.google.com/document/d/1kwmhGIj9Vi_v9AQYEHjKd2Ok-Lk_e4FKc_cNs88CGK8/edit#heading=h.trqab8y0kufp)

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by efritz** [comment]
@aidaeology Note this will not be necessary anymore if https://github.com/sourcegraph/sourcegraph/issues/13070 is done and approved.

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
