### ISSUE TITLE
Make diff highlight colors (red/green) configurable

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#12173]
Requested by https://app.hubspot.com/contacts/2762526/company/814799452

Two pieces of input:

First, in dark mode, the red/green highlights are very hard to see. I agree with this, and have felt this for a while. Curious if other dark mode users feel. 

Second, this could be a nice accessibility improvement. Red/green color blindness is quite common, and it'd be nice to make this customizable.

**Comment by jasongornall** [comment]
this is being addressed by @umpox for contrast across the application
