### ISSUE TITLE
Sourcegraph OSS user settings not accessible

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#12191]
going to eg `http://localhost:3080/users/bobheadxi/settings` via `./dev/start.sh` lands me on this error:

![image](https://user-images.githubusercontent.com/23356519/87489944-e940cc80-c676-11ea-9385-39985dba69ce.png)

am able to access user settings as usual via `./enterprise/dev/start.sh`

**Comment by unknwon** [comment]
@bobheadxi This bug has been fixed, do you think it's worth adding a CHANGELOG entry?

**Comment by bobheadxi** [comment]
I'm sure it wouldn't hurt to highlight efforts to maintain the OSS versions :)

**Comment by unknwon** [comment]
PR sent: https://github.com/sourcegraph/sourcegraph/pull/12320
