### ISSUE TITLE
Sourcegraph Server home page

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#12192]
Goals:
- Grow usage among all personas in the enterprise by:
- Reducing onboarding time
- Providing content relevant to the user persona
- Surfacing key product features 

Definition of success:
Increase the number of users returning in the first 2 weeks.

Workshop
- [x] prepare
- [x] concepts
- [x] voting
- [x] consolidating

Wireframes ([Figma page](https://www.figma.com/file/sPRyyv3nt5h0284nqEuAXE/%2312192-Sourcegraph-server-page?node-id=158%3A0))
- [x] design

Visual design  ([Figma page](https://www.figma.com/file/sPRyyv3nt5h0284nqEuAXE/%2312192-Sourcegraph-server-page?node-id=255%3A3)
- [x] design
- [x] hallway testing
- [x] review
- [x] handoff preparation

- [ ] QA
- [ ] Testing

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
