### ISSUE TITLE
Cookiebot alert box is not responsive

### ISSUE THREAD

**Issue by aileenrose** [sourcegraph/sourcegraph#12196]
Reported by Julia.

![Image from iOS](https://user-images.githubusercontent.com/2164916/87203881-6b687400-c2b8-11ea-8208-1bfaaa0646be.png)

**Comment by felixfbecker** [comment]
Fixed:

![image](https://user-images.githubusercontent.com/10532611/87528485-dd143980-c68d-11ea-963c-4be1031bf293.png)

![image](https://user-images.githubusercontent.com/10532611/87528858-69266100-c68e-11ea-9c41-6dfbb24c66cb.png)
