### ISSUE TITLE
schema file missing

### ISSUE THREAD

**Issue by stackflow1234** [sourcegraph/sourcegraph#1220]
#### Question description

Does it suppose to have a `schema` file exist in this directory?

https://github.com/sourcegraph/sourcegraph/blob/240f3db60dc137e98c23c3e5af31b54ba0956c68/shared/src/graphql/graphql.ts#L2

**Comment by sqs** [comment]
This file is not committed. It is written in the `gulp graphQLTypes` action, which is run in the npm postinstall script (https://sourcegraph.com/github.com/sourcegraph/sourcegraph@d9a8ccb8ab2c12aa4fce24f72e0448e7190a8f10/-/blob/shared/gulpfile.ts#L50).
