### ISSUE TITLE
\s\S regex patterns fail to parse 

### ISSUE THREAD

**Issue by aisbaa** [sourcegraph/sourcegraph#1221]
#### Steps to reproduce:

1. https://sourcegraph.com/search?q=a%5B%5Cs%5CS%5D*b+repo:%5Egithub%5C.com/nf/goto%24

#### Expected behavior:

Expect sourcegraph to parse this pattern, here's how it should work https://regex101.com/r/AkzrYn/1/

#### Actual behavior:

<img width="990" alt="screenshot 2018-12-04 at 15 13 17" src="https://user-images.githubusercontent.com/82692/49444283-57ed5100-f7d7-11e8-8839-245ed80bd38d.png">

**Comment by keegancsmith** [comment]
Interesting, so `[\s\S]` is just another way of saying `.`. But yeah this is a problem in our query parser, which will soon be replaced by https://github.com/sourcegraph/sourcegraph/issues/1005

However, I'll leave this open and ensure it works in our new search engine.

**Comment by ijt** [comment]
This appears to be working. Closing the issue.

<img width="988" alt="Screen Shot 2019-04-24 at 5 05 23 PM" src="https://user-images.githubusercontent.com/15530/56701313-4a1b6800-66b3-11e9-8d8a-ba0503686d4d.png">

**Comment by aisbaa** [comment]
Is it in v3.3?

**Comment by ijt** [comment]
Turns out I spoke too soon. In fact this issue is present not only in v3.3 but also in HEAD. Here's a local repro at HEAD:

![Screen Shot 2019-04-30 at 9 40 49 PM](https://user-images.githubusercontent.com/15530/57005923-ca007100-6b90-11e9-87c8-3bf4dae796c5.png)

Reopening this.

**Comment by ijt** [comment]
@aisbaa, can you use `a.*b` instead for now? Is there some case it doesn't handle?

**Comment by ijt** [comment]
It's an issue in zoekt: https://github.com/google/zoekt/issues/82.

**Comment by ijt** [comment]
I'm taking this off the 3.4 milestone since it should be possible to work around by using `.` instead of `[\s\S]`.

**Comment by ijt** [comment]
This is due to a bug in the standard library `regexp` package: https://github.com/golang/go/issues/31807.

**Comment by ijt** [comment]
I'm unassigning myself because this should eventually correct itself once it's fixed in the Go stdlib.

**Comment by keegancsmith** [comment]
The fix I did to go is in master, so I expect it to be part of the next go release.

**Comment by keegancsmith** [comment]
Sourcegraph.com (and 3.8) is now compiled with 1.13, which contains the relevant fix.
