### ISSUE TITLE
Search returns results that shouldn't match

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#1222]
[repo:sourcegraph/website are-we-there-yet(.|\s)*version.*](https://sourcegraph.sgdev.org/search?q=repo:sourcegraph/website+are-we-there-yet%28.%7C%5Cs%29*version.*)

![image](https://user-images.githubusercontent.com/754768/41386368-fe9def9e-6f35-11e8-8e63-e1b0e7ee8614.png)

**Comment by keegancsmith** [comment]
Fixed by https://github.com/sourcegraph/sourcegraph/pull/519
