### ISSUE TITLE
Improve Sourcegraph quickstart guide

### ISSUE THREAD

**Issue by dertz** [sourcegraph/sourcegraph#12220]
IN deploy-sourcegraph-docker/docker-compose/docker-compose.yaml

on line 52, you have the following
          # - '/LOCAL/KEY/PATH.pem:/sourcegraph.key'
Should this be 
          # - '/LOCAL/KEY/PATH.key:/sourcegraph.key'

When I made this change it worked.

**Comment by davejrt** [comment]
@dertz thank for you picking this up and raising the issue
