### ISSUE TITLE
3.18 Failing regression tests

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#12230]
We currently have some release-blocking issues found during regression testing. 

The suites that are not passing are and we require assistance with are:

- Onboarding 

- External Services (needs the most work) 

#### Steps to reproduce:

1. Setup a regression testing environment: [README](https://github.com/sourcegraph/sourcegraph/blob/master/web/src/regression/README.md) 
Please ping me with any difficulties in setting up these tests. 

3. `SLOWMO=10 KEEP_BROWSER=true yarn run test:regression:onboarding` 
4. `SLOWMO=10 KEEP_BROWSER=true yarn run test:regression:external-services` 

#### Expected behavior:

These tests pass and we can release 3.18.0

#### Actual behavior:

The [onboarding tests](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@3.18/-/blob/web/src/regression/onboarding.test.ts?utm_product_name=GoLand&utm_product_version=GoLand#L187:44-187:60) has some strange behavior with being unable to select a `.e2e-query-input` selector. I was unable to find this selector in Chrome but it was present in Firefox. 

Could the @sourcegraph/web team take a look at this? 

For the external-services test, we are tracking down expired tokens as a likely culprit and would appreciate help updating [1password](https://team-sourcegraph.1password.com/vaults/dnrhbauihkhjs5ag6vszsme45a/allitems/gm5dfflq6sfclmotneuayfdj5q) of tokens. cc @unknwon @beyang 

Please see the PR https://github.com/sourcegraph/sourcegraph/pull/12228 here for the current steps we are taking to fix the other regression tests.

**Comment by unknwon** [comment]
> For the external-services test, we are tracking down expired tokens as a likely culprit and would appreciate help updating [1password](https://team-sourcegraph.1password.com/vaults/dnrhbauihkhjs5ag6vszsme45a/allitems/gm5dfflq6sfclmotneuayfdj5q) of tokens. cc @unknwon @beyang

Would you be able to list which tokens in specific that you think they might have expired?

**Comment by daxmc99** [comment]
These issues have been fixed! Thank you everyone for your help
