### ISSUE TITLE
remove jumpToDefOSSIndex experimental feature flag

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#1223]
This feature flag has existed for 4 months. We should kill it or default it to on.

https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+jumpToDefOSSIndex

**Comment by nicksnyder** [comment]
@keegancsmith Is this feature flag relevant with the new code intel architecture?

**Comment by keegancsmith** [comment]
no, given it relies on the db table we want to remove.

**Comment by nicksnyder** [comment]
this has been removed
