### ISSUE TITLE
Tooltips in search bar often don't disappear

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#12242]
- **Sourcegraph version:** sourcegraph.sgdev.org
- **Platform information:** macOS Catalina, Safari Version 13.1.1 (15609.2.9.1.2)

#### Steps to reproduce:

I don't have any. I tried to reproduce it and get reliable steps, but couldn't.

It seems like I randomly trigger this behavior by going with the mouse cursor to the back/forward buttons in the browser toolbar.

#### Expected behavior:

Tooltips disappear after a timeout when the mouse is not hovering over the thing that triggers the tooltip.

#### Actual behavior:

Tooltips often say around. See GIF:w

![screenshot_2020-07-16_13 41 06](https://user-images.githubusercontent.com/1185253/87667252-51240f80-c76a-11ea-828e-6848dac7e4dd.gif)

**Comment by felixfbecker** [comment]
Thanks for filing! I'm reassigning this to the search team, who owns the query input.

**Comment by malomarrec** [comment]
Tagging similar issue in #20158 to feed into prioritisation work.

**Comment by fkling** [comment]
We've since switched to CodeMirror and I've not seen reports for it about this issue.
