### ISSUE TITLE
sourcegraph.com - adding gitlab.com repos broken

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#12257]
> @slimsag : Correction: You CAN add gitlab.com repos by visiting them, like github.com. We had to introduce this when rolling out the native integration into gitlab.com (edited) 
> https://github.com/sourcegraph/sourcegraph/pull/6194

> @tsenart is it broken / not working then? or why doesn't the URL I linked above work? https://sourcegraph.com/gitlab.com/nvidia/container-images is a valid gitlab repo but returns a 500

> Must be a bug
> I'll investigate

**Comment by tomas** [comment]
Please stop mentioning me in these pull requests

**Comment by keegancsmith** [comment]
https://gitlab.com/nvidia/container-images is not a valid gitlab repo, it is a repo group. I just visited https://sourcegraph.com/gitlab.com/nvidia/container-images/video-codec-sdk which we didn't have cloned and it worked.
