### ISSUE TITLE
Update product documentation

### ISSUE THREAD

**Issue by chayim** [sourcegraph/sourcegraph#12266]

**Comment by chayim** [comment]
Need to update to support variables SOURCEGRAPH_CRYPT_KEY and SOURCEGRAPH_SECRET_FILE from #12409

**Comment by chayim** [comment]
Please see branch rfc196-docs

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by sqs** [comment]
@daxmc99 Do you intend to merge the rfc196-docs branch by Thu Aug 20 (when the 3.19 release will be published)?

**Comment by daxmc99** [comment]
@sqs After syncing with Chayim, it doesn't make sense to add these to the 3.19 docs since the feature will not be fully merged by then. I will move it out of this milestone for now.

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
