### ISSUE TITLE
Migrate secrets from JSON blobs to encrypted storage

### ISSUE THREAD

**Issue by chayim** [sourcegraph/sourcegraph#12263]
Change the json blobs being stored in the secrets table to hold placeholders, but call out to the new code for inserting back into the object at run time (as opposed to store time), in the original location.

This replaces the placeholder within the json, with the decrypted secret - which is never rewritten to the database.

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by daxmc99** [comment]
We no longer plan to use the secrets table and plan to implement the encryption and decryption at the db access layer. 
Currently plan to encrypt JSON blobs in `external_accounts` and `event_logs`. 

`external_services` will also be encrypted after Goal 1 Team finishes https://github.com/sourcegraph/sourcegraph/pull/12789

**Comment by daxmc99** [comment]
@andreeleuterio Can we close this? I think this is being tracked / worked-on elsewhere

**Comment by andreeleuterio** [comment]
This was handled in [RFC 310](https://docs.google.com/document/d/1ZlQzlTRtrQbx3yi2cqmSjyq3ddcp2eKnhqekLOvzm_w/edit#)
