### ISSUE TITLE
[draft] deploy-sourcegraph-dhall: implement migrate-to-non-root overlay

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#12283]
https://github.com/sourcegraph/deploy-sourcegraph/blob/master/overlays/migrate-to-nonroot/kustomization.yaml is an example of a non-trivial customization that a real customer uses. @ggilmore has full confidence that this kind of customization is possible to implement in dhall, but it's useful to see how the complexity of the templates evolve as we add more and more configuration logic.

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
