### ISSUE TITLE
Extensions connection frequently gets closed

### ISSUE THREAD

**Issue by ijsnow** [sourcegraph/sourcegraph#1228]
I frequently see a "Connection closed" error be thrown/displayed in the tooltip. We need to investigate why it keeps getting closed or implement a robust way of handling this (i.e. catch error and recreate connection when closed).

**Comment by sqs** [comment]
I thought https://github.com/sourcegraph/sourcegraph/pull/1207 would fix most cases of this but apparently not.

**Comment by ijsnow** [comment]
Ah, well I was opening based on past experience/Sentry errors from yesterday. Maybe it is fixed now. I'll close this and reopen if I see it again.

**Comment by ijsnow** [comment]
Still seeing this quite a bit

**Comment by felixfbecker** [comment]
lang-typescript has reconnection logic

**Comment by sqs** [comment]
I think this is an extension host to main thread disconnection problem, not a problem with individual extensions’ websocket disconnection. @ijsnow can you paste the stack trace and accompanying screenshot and/or logs?

**Comment by sqs** [comment]
We haven't seen this occur recently, and much has changed around it that could have fixed this. Please reopen if you still encounter this.

**Comment by felixfbecker** [comment]
I still see this sometimes in the console

**Comment by ijsnow** [comment]
This still happens sporadically. [Here are instances of this error caught by sentry.](https://sentry.io/sourcegraph/browser-extension/?query=is%3Aunresolved+connection+is+closed) This would definitely be nice to fix but this might not be the highest of priorities since it is seemingly random/rare and can be resolved by a page reload.

**Comment by ijsnow** [comment]
Didn't notice the assignee change on this issue and started debugging it today. I'm able to reproduce this by:

1. [Open any page with code on GitHub](https://github.com/sourcegraph/codeintellify/blob/master/src/positions.ts)
2. In a new tab navigate to [chrome://extensions](chrome://extensions) and refresh the extension
3. Hover over code in the GitHub tab that was already open

![screenshot 2019-01-30 13 40 29](https://user-images.githubusercontent.com/11557758/52015405-c0367700-2496-11e9-834e-d1d164e1e31d.png)

This tells me that this happens when the [port that is being used to communicate with content scripts](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/browser/src/extension/scripts/background.tsx#L378-388) from the background script is disconnected.

This may happen in more that one situation, but one situation that I and @chrismwendt can think of is when the browser extension gets auto-updated in the background. The resulting problem is that the old content script is trying to communicate with a background script that doesn't exist anymore.

The simplest code change I can think of would be to use the notifications API to tell the user to refresh the page when this happens. We don't want to manually refresh the page because that could be jarring to the user.
