### ISSUE TITLE
ad-hoc "updatecheck" dashboard violates one-dashboard-per-service principle

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#12280]
https://github.com/sourcegraph/sourcegraph/blob/master/monitoring/update_check.go

@daxmc99 I noticed that this was added as a separate `Container` / file in `monitoring/` - this should instead be added to the existing service which is publishing the metrics in use (frontend.go).

This is bad for multiple reasons outlined in the monitoring developer guide ["FAQ: Why can’t I create an ad-hoc dashboard (e.g. an “HTTP” dashboard)?"](https://about.sourcegraph.com/handbook/engineering/distribution/observability/monitoring_pillars#faq-why-can-t-i-create-an-ad-hoc-dashboard-e-g-an-http-dashboard)

Can you own removing this file and placing it into the appropriate frontend service file instead? I think it could go well under the `Internal service requests` group here: https://github.com/sourcegraph/sourcegraph/blob/master/monitoring/frontend.go#L301

(I think this is definitely useful to have in place, though, so thank you for adding monitoring for this!)

**Comment by daxmc99** [comment]
Thanks for catching this @slimsag! 
I have a PR up here https://github.com/sourcegraph/sourcegraph/pull/12281 to fix this
