### ISSUE TITLE
'About Sourcegraph' and 'Help' pages should be opened in the separate tab

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#12286]
Current state:
- Authorized users: 'Help' and 'About Sourcegraph' links, accessible from the 'Profile' dropdown, opens in the new tab
- Un-authorized users: 'Help' and 'About' links, accessible from the top navigation, opens in the same tab.

Proposed changes:
- **Open Help and About links in the separate tab for all users.** We would avoid taking them out of the context of the app.
- **Add 'open in the new tab' icon** in the dropdown menu visible for authorized users.

@rrhyne @felixfbecker please, review. Thank you!

See in [Figma](https://www.figma.com/file/iXNTQ4rsggVtH8ASe3Vnzg/About-Sourcegraph-and-Help-pages-should-be-opened-in-the-separate-tab?node-id=0%3A1)

![Menu-icon](https://user-images.githubusercontent.com/20326070/87757861-ae23d200-c80b-11ea-94cf-ea03752295b8.png)

**Comment by AlicjaSuska** [comment]
Friendly reminder @rrhyne @felixfbecker

**Comment by felixfbecker** [comment]
LGTM, @sourcegraph/web let's see if we can fit this in this iteration
