### ISSUE TITLE
Wrong file: scope when file path contains spaces or special characters

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#12296]
When navigating too a tree/blob, the search field will be scoped to the current repo/file:

![image](https://user-images.githubusercontent.com/1741180/87797131-928bec00-c84a-11ea-804b-3ad7cdc22430.png)

However, when the file path contains spaces or other special characters, the scoped query is build from the URL-encoded file path, which will return no search results:

![image](https://user-images.githubusercontent.com/1741180/87797408-eb5b8480-c84a-11ea-8a44-de862db5053d.png)

This is because the file path we use to build the scoped query is [parsed from the location](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@c8c34394d09aa73ac47465d250167f386004c1a4/-/blob/web/src/repo/RepoContainer.tsx?subtree=true#L228-232). 

However, simply fixing `parseBrowserRepoURL` to `decodeURIComponent(filePath)` is not enough: if the decoded file path contains spaces, we would need to quote it to insert it as a valid filter.

**Comment by felixfbecker** [comment]
Briefly looked into this and tried to decode and use `quoteIfNeeded()`, but that existing search helper uses `JSON.stringify()`, which obviously does more than just quoting. I don't know what other things may break if I change that function, so deferring to @sourcegraph/search. There is an integration test in https://github.com/sourcegraph/sourcegraph/pull/12297 you can comment out to test.
