### ISSUE TITLE
dotcom: gorilla/mux repo go to codehost button is phabricator

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#12294]
https://sourcegraph.com/github.com/gorilla/mux/-/commit/948bec34b5168796bf3fc4dbb09215baa970351a?visible=1

go to codehost button is phabricator and directs you to

https://phabricator.sgdev.org/rMUX948bec34b5168796bf3fc4dbb09215baa970351a

This is true for incognito mode as well. My guess someone was testing phabricator integration against sourcegraph.com, so there are likely other repos with this association? Not exactly sure the codepath taken to generate this link.

cc @sourcegraph/web @sourcegraph/cloud 

![image](https://user-images.githubusercontent.com/187831/87788925-81d57900-c83e-11ea-9255-d903153f4fc3.png)

**Comment by felixfbecker** [comment]
This is provided by the backend through the `externalURLs` GraphQL field:

![image](https://user-images.githubusercontent.com/10532611/87789191-eabcf100-c83e-11ea-9604-d1cb7f662335.png)

The webapp shows a button for the first one in the list as the primary source.
What I don't know is what influences the order on the backend, or why our sgdev phabricator instance is configured as an external service on dotcom. Maybe someone ran e2e/regression tests against dotcom and it changes external services?

**Comment by lguychard** [comment]
> there are likely other repos with this association

AFAICT the only other repository on phabricator.sgdev.org that could have this association is `sourcegraph/jsonrpc2` -- all other repositories are mirrored from Gitolite.

**Comment by keegancsmith** [comment]
Yeah I suspect someone was testing against prod and now the data is in the DB. Our phabricator integration is not that great, so I doubt we clean up once the external service config is removed. I'll manually remove from the DB.

**Comment by keegancsmith** [comment]
Manually cleaned up. See some interesting data we had there on slack: https://sourcegraph.slack.com/archives/CMT39K56Z/p1594992624474200?thread_ts=1594991017.473600&cid=CMT39K56Z
