### ISSUE TITLE
Create web content stylesheet

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#12303]
The addition of 'web' oriented styles have been added to the following components and their scss files and require consolidation once they are properly defined within the global styles:

SearchPage.tsx & SearchPage.scss
RepositoryGroupPage.tsx & RepositoryGroupPage.scss
PrivateCode.tsx & PrivateCode.scss

Additionally, on RepositoryGroupPage.tsx, several font-weight-normal overrides are occurring to meet the design specification with existing styles. The font weight should be incorporated into the web-styles elements.

**Comment by attfarhan** [comment]
I propose renaming this to "Create web content stylesheet" and I'll assign myself, and this will be the next thing I address. 

The stylesheet will include the web content styles already in the repogroup pages and private code CTA, and I'll remove any overrides in those respective stylesheets. The stylesheet won't be complete yet, but we can add to it as we define our web styles more clearly.
