### ISSUE TITLE
Determine state of LSIF-java

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#12306]
https://github.com/sourcegraph/lsif-java/

- [x] Check the current [issues](https://github.com/sourcegraph/lsif-java/issues) and see what is no longer reproducible with the latest version. Close the issues which are not reproducible. Comment on the ones that are.
- [x] Choose a set of three to six OSS repositories not listed there and ensure generation does not crash the indexer.
- [x] Upload the resulting indexes to a local Sourcegraph instance and get hover tooltips on the code. Catalog which language features are missing results or have incorrect results (e.g. enums, jump to def into inner classes, etc).

**Comment by aidaeology** [comment]
Update: Re-ran LSIF-java against repos with known issues and was able to still reproduce issues listed [here](https://github.com/sourcegraph/lsif-java/issues). 

On the upside I was able to generate LSIF dump for the following OSS repositories and successfully uploaded to sourcegraph.com:
- [google/turbine](https://github.com/google/turbine)
- [square/javapoet](https://github.com/square/javapoet)
- [twitter/whiskey](https://github.com/twitter/whiskey)
