### ISSUE TITLE
Activation confetti does not appear on find references action

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#12310]
- **Sourcegraph version:** 
- **Platform information:** 

#### Steps to reproduce:

1. Start a new Sourcegraph instance 
2. Using a fresh user account, run a search.
3. Do a find references action.

#### Expected behavior:

The confetti appears from activation dropdown both when doing a search and when doing find refs.

#### Actual behavior:

Find refs does not trigger confetti. The activation progress bar does advance, though.

**Comment by attfarhan** [comment]
I was able to reproduce once, but on subsequent attempts it seems to work fine. Perhaps this is an issue only for the first user.

**Comment by lguychard** [comment]
I'm not sure whether this is still relevant, but if it is it is not a search issue.

**Comment by macraig** [comment]
@attfarhan is this issue still relevant?
