### ISSUE TITLE
Make license check not fail when our node version is upgraded

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#12318]
See https://github.com/sourcegraph/sourcegraph/pull/11840

The license check seems to fail whenever the Node version is updated, preventing us from upgrading because it would poison the check on master and all branches afterwards. Could the GitHub action be made to use our .nvmrc (like Buildkite) instead of a baked-in version?

**Comment by bobheadxi** [comment]
Sorry for the delay! Just saw that the first comment was a couple of days ago :'(
