### ISSUE TITLE
Run e2e tests on bare-metal Buildkite agents on every commit to master (non-blocking)

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#12339]
Every commit to master should run e2e tests on the bare-metal buildkite agents once https://github.com/sourcegraph/sourcegraph/issues/12101 is closed.

It should not block the build at all (adds no time to CI runs, and if it fails should not show the build as failed).

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
