### ISSUE TITLE
🚚 LSIF-clang Delivery

### ISSUE THREAD

**Issue by aidaeology** [sourcegraph/sourcegraph#12349]
The goal of this task is to ship LSIF-clang v0.1 to customers:

1. Fix any [outstanding bugs and issues](https://github.com/sourcegraph/lsif-clang/issues) for LSIF-clang.
1. Benchmark and test LSIF-clang for performance, determine if there are any bottlenecks that need to be resolved.
1. Validate lsif-clang works as expected for C and Objective C by [indexing OSS projects](https://github.com/sourcegraph/sourcegraph/issues/12773).
1. Work with three existing customers below to deploy LSIF-java successfully and work out any potential technical blockers or usability issues so that LSIF-java can be used by all customers as part of a wide release.

- [ ] Customer 1: https://github.com/sourcegraph/customer/issues/86
- [ ] Customer 2: https://github.com/sourcegraph/customer/issues/87
- [ ] Customer 3: https://github.com/sourcegraph/customer/issues/88

Once this is complete for all three update status for LSIF-clang as appropriate (beta? ready?) and indicate its readiness for general availability.

**Comment by aidaeology** [comment]
@dadlerj tagging you here in response to your slack message.

**Comment by aidaeology** [comment]
@gbrik Please add the details of the known issues for lsif-clang in this issue or link to existing issues if they already exist somewhere else.

**Comment by aidaeology** [comment]
Update: We reviewed the state of lsif-clang indexer today and there are still some outstanding issues that need to be addressed and therefore we're not able to guarantee stability for a wide release right now. We are happy to work with any customers who are willing to try out a.k.a "dogfood" an unstable version and give us feedback and could help us identify any other bugs.

**Comment by aidaeology** [comment]
@gbrik Reminder to add the following details about the known bugs: 
OS version, error code/message and any other stack trace information that is helpful for debugging.

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by aidaeology** [comment]
Update: lsif-clang issues have been added to the [lsif-clang repos]( https://github.com/sourcegraph/lsif-clang/issues).

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by scalabilitysolved** [comment]
Do we need this still @macraig or are we tracking the delivery elsewhere?

**Comment by macraig** [comment]
@scalabilitysolved tracking elsewhere
