### ISSUE TITLE
Run QA tests on bare-metal Buildkite agents on every commit to master (non-blocking)

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#12340]
Every commit to master should run the e2e "regression" tests on the bare-metal buildkite agents once #12101 is closed.

It should not block the build at all (adds no time to CI runs, and if it fails should not show the build as failed).

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by slimsag** [comment]
@davejrt has beaten me quite a lot in looking into this and https://github.com/sourcegraph/sourcegraph/issues/12339 (which covers the needlessly-separate e2e test suite), but we still have a little ways to go. I am pulling into 3.21, I suspect only a few days of work remaining before we have this in place. cc @pecigonzalo

**Comment by davejrt** [comment]
Closing as this has been broken down into separate tickets in https://github.com/orgs/sourcegraph/projects/90
