### ISSUE TITLE
Cannot ignore warning alerts from within the Grafana UI

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#12341]
https://app.hubspot.com/contacts/2762526/company/693777200/ requests a way to be able to ignore warning alerts from within the Grafana UI, particularly in the list view on the overview dashboard because it makes it hard to see critical alerts and due to low usage when starting a Sourcegraph trial many provisioning indicator alerts will be firing initially.

Important note: Warning alerts are expected to be flappy in general - they may not be real issues - this is about having the ability to silence some of them in Grafana solely and not about silencing them in general etc.

**Comment by bobheadxi** [comment]
I think one pain point with this is that you have to look at every single red alert to find a critical alert - would multi-column sorting (https://github.com/grafana/grafana/issues/10541) or being able to filter by alert level on the overview dashboard help alleviate this problem?

<img width="225" alt="image" src="https://user-images.githubusercontent.com/23356519/87996860-fef63c00-cb25-11ea-812f-69bb0086e917.png">

**Comment by daxmc99** [comment]
I believe this is blocked by the fact we do not provide write-access within the Grafana UI.
