### ISSUE TITLE
Sourcegraph.com search returns "too many matching repositories", no results, and broken suggestions

### ISSUE THREAD

**Issue by ijt** [sourcegraph/sourcegraph#1234]
- **Sourcegraph version:** sourcegraph.com
- **Platform information:** n/a

#### Steps to reproduce:

1. Go to sourcegraph.com.
2. Enter "pubsub".

#### Expected behavior:

Search results come back with some relevant repos that mention pubsub.

#### Actual behavior:

It returns "Too many matching repositories", and four links to suggested refinements that all yield further empty search results.

**Comment by sqs** [comment]
I’ll plan a workaround that doesn’t require us to search all repositories to solve the confusion here.

**Comment by ijsnow** [comment]
We'll use the query builder (https://github.com/sourcegraph/sourcegraph/issues/652) in our solution for this. The benefit is users becoming educated on how to use our search syntax and not receive confusing error messages. We could either:

1. block search when a repo filter isn't specified on sourcegraph.com and open up the query builder.
2. remove the "Did you mean...?" search suggestions from the error page and replace it with the query builder.

With either solution above, we could emphasize the repository filter input in the UI so users know they need to update that field.

**Comment by christinaforney** [comment]
This now works with the solution from @ijt 's hackweek project! 🎉

**Comment by keegancsmith** [comment]
This is my comment!
