### ISSUE TITLE
Unindexed repositories for Structural Search

### ISSUE THREAD

**Issue by poojaj-tech** [sourcegraph/sourcegraph#12348]
Configuration: Multiple mono repos

#### Steps to reproduce:
For any structural search he tried (not language specific), he got this message: 
eg. “ITEM_ID_STRING count:1000" with structural search toggle on
![109431530_315982736225866_314350281374927002_n](https://user-images.githubusercontent.com/57463526/87996440-ff9bbd80-caa6-11ea-9267-731e3c0661b7.png)

#### Expected behavior:
Should all repos be indexed on an enterprise instance?

https://app.hubspot.com/contacts/2762526/company/732945930/

**Comment by rvantonder** [comment]
The message is expected behavior if not all repositories are indexed, and a global structural search is run across everything. We would need more information about which repositories are indexed/unindexed on this instance.

**Comment by rvantonder** [comment]
Follow up: you may try add `index:only` to guarantee that only indexed repos on the instance are considered. The site admin repo page will enumerate which repos are unindexed (and not searched by structural search). For example, at: https://instance.com/site-admin/repositories?filter=needs-index

**Comment by dadlerj** [comment]
>Should all repos be indexed on an enterprise instance?

I would assume so. @rvantonder what reason could we have for a repo or series of repos to _not_ be indexed? I can for more info from the customer.

**Comment by poojaj-tech** [comment]
Update: Searching in their `Go` monorepo showed the same message as well.

**Comment by rvantonder** [comment]
> what reason could we have for a repo or series of repos to not be indexed?

I really don't know--this sounds like a deployment question that @sourcegraph/distribution would have a good sense of, maybe. I'd think one step is to check whether, and how many, repos are unindexed at the site admin repo page I mentioned. The alert mentions index settings to our [current docs](https://docs.sourcegraph.com/admin/search#indexed-search), so it would be good to have an idea if those settings are set.

**Comment by poojaj-tech** [comment]
+1 also curious why an admin would choose to not index.  If we want to encourage all repos to be indexed, we could upsell that in our messaging here (eg. submit request to admin to index).

**Comment by dadlerj** [comment]
No need for anyone from distribution to get involved yet, I'll check with the customer

**Comment by dadlerj** [comment]
Update from the customer:

>> If you visit the Site-admin > Repository Status page, and click on the "Needs index" option, how many do you see show up?

>None show up under "Needs index".

>> did you ever disable search indexing (via setting the site-admin configuration option search.index.enabled to false)

>I don't think we did and I don't see that option under site-admin/configuration.

**Comment by rvantonder** [comment]
Thanks. Next step is on my side then, I'll dig into the index/commit logic to see why this could happen spontaneously/nondeterministically.

**Comment by rvantonder** [comment]
Done in #17967.
