### ISSUE TITLE
Investigate effort for a new LSIF-swift indexer

### ISSUE THREAD

**Issue by aidaeology** [sourcegraph/sourcegraph#12350]
Start work on Swift support by evaluating implementation effort for implementation - time box research to 2 hours.

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by scalabilitysolved** [comment]
Closing for now, Swift is on our radar as a team.
