### ISSUE TITLE
src-expose is first class

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#12363]
I am going to tackle a few quick wins in making src-expose feel first class. This issue will track them.

- [x] git protocol v2. For perf and solves #11707
- [x] better external service integration
- [x] integrate just serve into src-cli #9243
- [x] list option for interactive debugging
- [ ] test src-cli docker image
- [x] document and publish src git-serve

This should help a lot with the current pains listed in [PD 10: Support for non-Git VCS](https://docs.google.com/document/d/1Y2xYbckAz5jlBePER_BarypeDfP3mjjX9bBOZm3ALqY/edit#). However, solving non-Git VCS in general is likely a larger project.

cc @christinaforney @dadlerj

**Comment by keegancsmith** [comment]
Did some work on this today. src-cli now has `src serve-git` as a subcommand that is hidden. It is just `src-expose serve`, except a much simpler CLI UI since we don't have any of the snapshotting cruft. It is using git protocol v2, so is more efficient.

Tomorrow I'll focus on making the external service setup not seem hacky. Then testing and docs and I'm done with these improvements.

**Comment by keegancsmith** [comment]
I ended up spending only a little bit of time on external service before being sucked into other things today. But the little bit of time made me realise its a bit of work to add.

@dadlerj Do you think it is alright to have the external service configuration be the same we are using at the moment. Or do you think I should add a new external service type? To make src-expose feel polished maybe all we need to do is what I have done so far (fold into src-cli) and document it very well.

Additionally I renamed it to `src serve-git` to make it clear we are only serving git repos now. Do you think we should keep the name expose? Maybe `src expose`?

**Comment by dadlerj** [comment]
I'm fine with the name change. I don't think the external service piece is critical up-front...

Alternatively, would it be possible to simply add a button to the external services page that reflects src serve-git, and when you click it, it starts with that default config? Essentially, still use the "generic git host" service under the hood, but add a nice UI for it. 

Adding this to the `src` cli is actually an interesting topic... I can see lots of benefits (e.g., release versioning, etc.), but this functionality definitely has a different UX (running as a server, often deployed via Docker on a remote machine, etc.). I don't want to have to backtrack on that decision now, but I'm curious what your thoughts are on doing this vs putting it in /cmd and running it alongside Sourcegraph?

**Comment by keegancsmith** [comment]
> Alternatively, would it be possible to simply add a button to the external services page that says `src serve-git`, but when you click it, it takes you to the "generic git host" page with the `src serve-git` default config instead of an empty one? Essentially, still use the "generic git host" service under the hood, but add a nice entrypoint UI for it.

Great idea. Will do.

> Adding this to the `src` cli is actually an interesting topic... I can see lots of benefits (e.g., release versioning, etc.), but this functionality definitely has a different UX (running as a server, often deployed via Docker on a remote machine, etc.). I don't want to have to backtrack on that decision now, but I'm curious what your thoughts are on doing this vs putting it in /cmd and running it alongside Sourcegraph?

This is a nice idea. What I like about src-cli vs standalone binary:

- Release process is clear and tailored for a binary
- We don't do binary releases for different platforms in /cmd
- I want people to try it out interactively.
- In the future we have the option of it automatically configuring external services since src-cli "knows" how to edit external services.
- It "feels" right to me :P

If nearly everyone is going to do this via Docker then I suppose that would make sense to just support Docker. But I like the fact that anyone can fetch our src-cli binary and just play with it.

FYI I am adding `src serve-git -list` today which just lists all the repositories it finds. That should help customers debug stuff :)

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
