### ISSUE TITLE
Search was fast yesterday, now times out

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#12378]
Will add more...

yesterday this query was fast: https://sourcegraph.com/search?q=import+yaml+and+load%28+lang:python&patternType=structural

Now it is timing out. After a while:

> text search failed: failed to search github.com/bioconda/bioconda-recipes@: searcher request failed: Get "http://10.164.1.136:3181?CombyRule=&Commit=25ace29ac3cefec4dd726500f4fc0bab1ef7de26&Deadline=2020-07-21T22%3A00%3A09.769850718Z&ExcludePattern=&FetchTimeout=51.801355963s&FileMatchLimit=5000&IncludePatterns=scripts%2Fucsc%2Fcreate-ucsc-packages.py&IsStructuralPat=true&Languages=python&PathPatternsAreRegExps=true&Pattern=import+yaml&PatternMatchesContent=true&PatternMatchesPath=false&Repo=github.com%2Fbioconda%2Fbioconda-recipes&URL=": EOF

![image](https://user-images.githubusercontent.com/1976/88111522-ea846480-cb62-11ea-9182-9643c688387e.png)

**Comment by rvantonder** [comment]
Same thing is going on in #12347 for regexp search (seems to affect all search types for a collection of repos).
