### ISSUE TITLE
option for deploy-sourcegraph prometheus unbundling

### ISSUE THREAD

**Issue by uwedeportivo** [sourcegraph/sourcegraph#12370]
feedback from customer:

- already have a prometheus running in cluster
- already collect cadvisor metrics
- concern about metric duplication

wish for unbundling option that exposes prometheus rules and targets necessary for sourcegraph as prometheus operator ServiceMonitors and PrometheusRules

example of this approach:
https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/templates/argocd-server/servicemonitor.yaml

**Comment by bobheadxi** [comment]
to clarify: this just means not deploying prometheus/cadvisor, correct?

also would like to point out that `PROMETHEUS_URL` will need to be unset appropriately as well

**Comment by slimsag** [comment]
I am going to close this as I think in general we should avoid having any deployments without our monitoring/observability stack. Those that do mean we cannot debug them effectively and are somewhat on their own. We should move in this direction and push more folks to use our monitoring stack.
