### ISSUE TITLE
Indexing multiple branches timing out with git command `failed: exit status 128`

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#12376]
Reported by https://app.hubspot.com/contacts/2762526/company/768958891

See Slack thread at https://sourcegraph.slack.com/archives/CTJCMDCCS/p1595352999461200?thread_ts=1595350296.457900&cid=CTJCMDCCS

```
2020/07/21 17:35:51 error indexing <$REPO>@HEAD=<$SHA_BRANCH_LIST>: command [git -C /data/index/.indexserver.tmp/tmpfriend-6-554088670/<$REPO.git> -c protocol.version=2 fetch --depth=1 http://sourcegraph-frontend-internal/.internal/git/<$REPO> <$SHA LIST>] failed: exit status 128
OUT:
ERR: warning: redirecting to http://gitserver-0.gitserver:3178/git/<$REPO>/
error: RPC failed; HTTP 500 curl 22 The requested URL returned error: 500
fatal: the remote end hung up unexpectedly
```

When the user reduced the number of branches from double digits to just 1, it worked just fine. He then increased up to 5, and got the same error. 

* Kubernetes
* Fetching code from Gerritt

**Comment by keegancsmith** [comment]
Ouch this is a bit hard to debug. I'm surprised it failed at 5 branches. I will jump into the thread and ask this:

Hi, sorry you are experiencing this. It's a bit tricky to debug, the fastest way is to manually try how we fetch the code with git tracing enabled. Could you try going to the searcher-indexer container (possibly called zoekt-sourcegraph-indexserver) and manually run:

```
git init --bare /data/index/test.git
GIT_CURL_VERBOSE=1 git fetch -C /data/index/test.git -c protocol.version=2 fetch --depth=1 http://sourcegraph-frontend-internal/.internal/git/<$REPO> <$SHA LIST>
rm -rf /data/index/test.git
```

Other interesting git debug environment vars are `GIT_TRACE_PERFORMANCE=1` and `GIT_TRACE_PACKET=1`

Note: we do have a limit of 64 branches per repository currently.

**Comment by keegancsmith** [comment]
Haven't really heard back from the customer, nor have I heard this happen to others. I'm going to close this out. Feel free to re-open if we need to investigate more.
