### ISSUE TITLE
Rate limit requests to Sourcegraph API

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#12375]
Requested by:
* https://app.hubspot.com/contacts/2762526/company/464956351
* https://app.hubspot.com/contacts/2762526/company/557692805

From the latter:

>given that i can envision (over the long-term) teams wanting to build automation using the API, something we've noticed with GHE is that teams will create tooling without regard to load impact ... so having rate limiting will minimize our need to play "whack-a-mole" usage cops ... with GHE, we frequently see teams that put things in place that run on schedules ... often times they get unintentionally mis-configured and we end up having to chase down the bad actors in a reactive manner

Related: 
* https://github.com/sourcegraph/sourcegraph/issues/10629
* https://github.com/sourcegraph/sourcegraph/issues/5705
* https://github.com/sourcegraph/sourcegraph/issues/5706

@slimsag this issue feels slightly different from #10629 but feel free to merge if you'd like.

**Comment by tsenart** [comment]
I think this is a dup of #10629, so closing and moving customer links there.
