### ISSUE TITLE
gqltest: add tests for version context

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#12383]

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by unknwon** [comment]
Cleaning up old/stale/fixed issues, please feel free to reopen if you think it's worth keeping.
