### ISSUE TITLE
go to define not show

### ISSUE THREAD

**Issue by stewForAni** [sourcegraph/sourcegraph#1239]
it's ALL fine to read an android project when i first use it include hover to show go to define,but now ,go to define not show at all, help me , i like sourcegraph so much!

**Comment by sqs** [comment]
Sorry, we needed to take down Java temporarily as we move to a much better architecture that will result in improved Java support. @beyang 	is working on bringing Java back to Sourcegraph.com.

**BUT** you can get Java back right now by running a self-hosted Sourcegraph instance. See https://about.sourcegraph.com/blog/java-php-experimental-language-servers-temporarily-unavailable for more information and workarounds.
