### ISSUE TITLE
sourcegraph/server:3.18 provisioning indicators panel missing

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#12421]
![image](https://user-images.githubusercontent.com/3173176/88232278-6eedea80-cc2a-11ea-801d-fe94fb3845fd.png)

Provisioning indicators here in sourcegraph/server:3.18.0 are not showing up^ - this likely means that Grafana dashboards in sourcegraph/server were not updated for some reason(not sure how that's possible) before it was released, you can repro with the command on http://docs.sourcegraph.com/

**Comment by bobheadxi** [comment]
Seems this is because the grafana image we copy assets from is hardcoded, and thus never updated

Will send a PR to have this build on the fly, similar to prometheus

https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/server/Dockerfile#L71:38

**Comment by bobheadxi** [comment]
@slimsag note that while #12424 adds the panel and makes grafana consistent with the release, sourcegraph server does not support provisioning indicators

**Comment by slimsag** [comment]
Yep, acknowledged and that’s 100% ok / not something we need to solve.
