### ISSUE TITLE
Branch names not showing up on search results

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#12420]
Sourcegraph.com

Repro: https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24%40*refs/heads/:%5Erefs/heads/master+file:migrations/++type:diff&patternType=literal

This search is ONLY searching non-default/non-`master` branches, but the branch names don't seem to show up on search result lines.

![image](https://user-images.githubusercontent.com/5589410/88232002-f4bd6600-cc29-11ea-9860-84439a75cea2.png)

**Comment by dadlerj** [comment]
Could this also be related to the version context issue discussed in Slack? https://sourcegraph.slack.com/archives/CHEKCRWKV/p1595362401130000

**Comment by attfarhan** [comment]
Notes:

- We pass through the html to render from the backend, not sure why it's suddenly excluding branch names
- https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/search_commits.go#L365:1-377:2 this function doesn't seem to append branch name to the label, but quite sure it appeared before. Odd.

**Comment by attfarhan** [comment]
@dadlerj actually we have never shown this in the past. The issue here is that the `inputRevision` can be multiple things. You're diffing a head and a base, and the head/base could have a specified or unspecified input revision. So it's unclear what to show here.

But, this UX is not good and we should think about this more down the line. cc @poojaj-tech (to surface this to product/design)

**Comment by dadlerj** [comment]
Interesting! I didn't realize that. I know that _sometimes_ the branch name shows up (e.g. with version contexts, with specifically named branches in a search, etc.) so this was surprising. Thanks for raising it to product.

**Comment by poojaj-tech** [comment]
Thanks for filing @dadlerj. Revisions can specified as a branch, commit hash or a tag. Git refs can vary based on the configuration set up. This will be an interesting consideration to think through.
cc: @christinaforney

**Comment by camdencheek** [comment]
Closing since in the context of a commit/diff search, the input rev is used as the starting point of the search, so the results themselves are associated with commits that are contained in the history of those input revs. It would not make sense to have a rev on the search results.
