### ISSUE TITLE
Sourcegraph.com github-proxy is over provisioned

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#12447]
These are firing frequently:

"warning_github_proxy_provisioning_container_cpu_usage_7d_low",
"warning_github_proxy_provisioning_container_memory_usage_7d_low",

https://sourcegraph.com/-/debug/grafana/d/github-proxy/github-proxy

Please fix, confirm the alert is not firing anymore, and then unsilence it: https://github.com/sourcegraph/deploy-sourcegraph-dot-com/blob/e33d7cd48e9407aac88124eec89644dd4d51699c/base/frontend/sourcegraph-frontend.ConfigMap.yaml#L5271-L5275

**Comment by mrnugget** [comment]
Seems like this is not happening anymore.
