### ISSUE TITLE
Browser extension not working with Codecov Token

### ISSUE THREAD

**Issue by poojaj-tech** [sourcegraph/sourcegraph#12445]
Customer feedback through Extension Uninstall Feedback form

> Doesn't work with codecov token.

Company: https://app.hubspot.com/contacts/2762526/company/4188342284
Customer: https://app.hubspot.com/contacts/2762526/contact/24406751/

**Comment by lguychard** [comment]
This is fixed in v20.7.24.1507 of the browser extension.
