### ISSUE TITLE
Sourcegraph.com update checks slow

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#12448]
This is firing frequently:

"warning_frontend_90th_percentile_updatecheck_requests",

https://sourcegraph.com/-/debug/grafana/d/frontend/frontend

Please fix, confirm the alert is not firing anymore, and then unsilence it: https://github.com/sourcegraph/deploy-sourcegraph-dot-com/blob/e33d7cd48e9407aac88124eec89644dd4d51699c/base/frontend/sourcegraph-frontend.ConfigMap.yaml#L5271-L5275

**Comment by bobheadxi** [comment]
This is one of our most frequent alerts, according to [this query](https://sourcegraph.com/-/debug/grafana/explore?orgId=1&left=%5B%22now-7d%22,%22now%22,%22Prometheus%22,%7B%22expr%22:%22sum%20by(service_name,%20name)%20(increase(alert_count%5B$__range%5D))%22%7D,%7B%22ui%22:%5Bfalse,true,true,%22none%22%5D%7D%5D):

<img width="1712" alt="image" src="https://user-images.githubusercontent.com/23356519/89785492-1769dd00-db4d-11ea-8b49-629d4d6132de.png">

**Comment by bobheadxi** [comment]
@daxmc99 seems like you added this one, but I'm not entirely sure how it works - do you mind taking a look and seeing if these really are too slow, or if the threshold is too low?

**Comment by daxmc99** [comment]
Opened a PR here https://github.com/sourcegraph/sourcegraph/pull/12901 

The intention of this alert was to warn when the updatecheck body (telemetry) would become so large it would risk timing out. 

https://sourcegraph.com/-/debug/grafana/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Prometheus%22,%7B%22expr%22:%22sum(src_updatecheck_client_duration_seconds_sum)%5Cn%5Cn%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D

This might be what we should alert on. The timeout is 300 sec atm

**Comment by bobheadxi** [comment]
updated title because we didn't fix update checks being slow (or if they were slow at all) 🙃
