### ISSUE TITLE
Sourcegraph.com gitserver underprovisioned

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#12451]
The following alerts are now firing frequently again:

"warning_gitserver_provisioning_container_cpu_usage_7d_high",
"warning_gitserver_provisioning_container_memory_usage_5m",
"warning_gitserver_provisioning_container_memory_usage_7d_high",
~"warning_gitserver_running_git_commands",~

https://sourcegraph.com/-/debug/grafana/d/gitserver/git-server

Please fix, confirm the alerts are not firing anymore, and then unsilence them: https://github.com/sourcegraph/deploy-sourcegraph-dot-com/blob/e33d7cd48e9407aac88124eec89644dd4d51699c/base/frontend/sourcegraph-frontend.ConfigMap.yaml#L5271-L5275

**Comment by bobheadxi** [comment]
> warning_gitserver_running_git_commands

https://github.com/sourcegraph/sourcegraph/issues/9355
