### ISSUE TITLE
Sourcegraph.com: code intel running out of CPU/memory/etc regularly

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#12452]
The following alerts are firing frequently on Sourcegraph.com:

"warning_precise_code_intel_bundle_manager_provisioning_container_cpu_usage_7d_high",
"warning_precise_code_intel_indexer_index_queue_growth_rate",
"warning_precise_code_intel_indexer_provisioning_container_cpu_usage_7d_high",
"warning_precise_code_intel_indexer_provisioning_container_memory_usage_7d_high",
"warning_precise_code_intel_worker_provisioning_container_cpu_usage_7d_high",

From:

- https://sourcegraph.com/-/debug/grafana/d/precise-code-intel-bundle-manager/precise-code-intel-bundle-manager?orgId=1
- https://sourcegraph.com/-/debug/grafana/d/precise-code-intel-indexer/precise-code-intel-indexer?orgId=1
- https://sourcegraph.com/-/debug/grafana/d/precise-code-intel-worker/precise-code-intel-worker?orgId=1

I have silenced them - please fix, confirm the alerts are not firing anymore, and then unsilence them: https://github.com/sourcegraph/deploy-sourcegraph-dot-com/blob/e33d7cd48e9407aac88124eec89644dd4d51699c/base/frontend/sourcegraph-frontend.ConfigMap.yaml#L5271-L5275

**Comment by bobheadxi** [comment]
## indexer

Seems CPU usage can be high, but memory usage has more of a pattern of slowly building up to ~90% and stopping, which leaves our `max_over_time` query for the 7d provisioning high

<img width="1683" alt="image" src="https://user-images.githubusercontent.com/23356519/88476006-67e71500-cf67-11ea-9726-81bdf0d2254e.png">

**Comment by bobheadxi** [comment]
## bundle manager

I don't think adjustments are necessary - it seems `max_over_time` overly emphasizes brief usage peaks in this case:

<img width="1700" alt="image" src="https://user-images.githubusercontent.com/23356519/88476121-6cf89400-cf68-11ea-87a0-a12aeaa567ff.png">

**Comment by bobheadxi** [comment]
## worker

Seems CPU usage could use slight increase

<img width="1682" alt="image" src="https://user-images.githubusercontent.com/23356519/88476181-13dd3000-cf69-11ea-9922-4ecedc903c72.png">

**Comment by bobheadxi** [comment]
I don't see any of these alerts firing - this may have been a bug: https://github.com/sourcegraph/sourcegraph/pull/12489
