### ISSUE TITLE
Raw API returns 500 Internal Server Error when file does not exist

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#1245]
See http://sourcegraph.com/github.com/sourcegraph/codeintellify@14252839a623a04dd381e1980f6d7d49876fd3bb/-/raw/src/package.json

This is bad because the 404 is needed to find the closest package.json to a URI returned by the language server in the lang-typescript extension.

**Comment by slimsag** [comment]
Pushed d0e53f75cc4b23bc9a6aceca171d5319c9c8f077 just now which will likely fix this.

**Comment by slimsag** [comment]
Fixed
