### ISSUE TITLE
Feature request: Easily add terms from search results to the search query

### ISSUE THREAD

**Issue by vanesa** [sourcegraph/sourcegraph#1246]
#### Feature request description

When holding down a key, mouse pointer changes to an arrow with an add sign and clicking on a term in the search result preview will add that term to the search query.

![image](https://user-images.githubusercontent.com/9110008/49555483-e8e62a00-f8b4-11e8-9c15-0d4777f85037.png)

#### Is your feature request related to a problem? If so, please describe.
It would optimize search work flow when wanting to extend the search query with search patterns found in search results.

Currently when browsing code from search result to search result this means: click through a match, copy the next search pattern, paste it into the search bar, and execute. This is cumbersome and could be optimized with the feature mentioned above.

**Comment by camdencheek** [comment]
Closing since this is quite old, but cc @taiyab since we discussed something similar to this for narrowing/excluding repos/directories/etc. from search results and integrating that capability with the filters panel
