### ISSUE TITLE
Query parser migration

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#12477]
This task tracks query parser migration to the new parser. Checklist of items to do:

- [x] Differential testing of search inputs and internal representation (build a corpus of inputs and convert them using both parsers, check that the results are equivalent). Bugs fixed:
  - #12572 
  - #12733
- [x] Run search-integration-tester test cases https://github.com/sourcegraph/sourcegraph/pull/13004
- [x] Add `/.../` syntax or deprecate it. The new parser doesn't support it yet, but it may be a fair decision to just drop support.
- [ ] Document the configuration/settings that control parsing, esp. for fallback.
- [ ] fix `alertForOverRepoLimit` for queries containing and/or
![image](https://user-images.githubusercontent.com/26413131/89024658-bdd00a00-d325-11ea-9c5e-9e6c2b8af82a.png)

**Comment by rvantonder** [comment]
Ran into 

`repo:^github\.com/sourcegraph/sourcegraph$ \{[^ ]+` give san alert `Error parsing regexp: missing closing ]: [^`, because we don't recognize the space in our language (it becomes concat). This is true of new and old parser, but it means we should alert why this doesn't compile.

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by rvantonder** [comment]
Closing this--the main flag, `migrateParser`, is set in our config and will become default in 3.20. Will file follow up tasks for anything else.
