### ISSUE TITLE
Design a GraphQL API that allows us to filter changesets via the textbox

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#12471]
As discussed in our sync: we want to be able to filter changesets through a textbox (see [Figma mockup](https://www.figma.com/file/kRf5i7xf1p4zs3OyX0DUVp/Campaigns)).

The parsing of that query could happen client side, but we need a way to then filter the changesets based on the given filters.

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by eseliger** [comment]
This has been incorporated in this list of tickets: https://github.com/sourcegraph/sourcegraph/issues/14968#issuecomment-727665114, so I'm going to close this one. If someone disagrees, please reopen.
