### ISSUE TITLE
Experimental globbing support in the backend

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#12476]
This task tracks issues to address before enabling globbing for fields for all Sourcegraph org members. Add things here as you discover them. Checklist of items to do:

- [x] I noticed that globbing feels sluggish sometimes. For example, globbing has a bad performance if the code host is specified. For the screenshots below, regex is enabled, but we add `.*?` in front just like globbing would do. Look at the difference in performance.

**with**
![image](https://user-images.githubusercontent.com/26413131/89766849-19a24c00-daf9-11ea-89c3-273cc51f308d.png)

**without**
![image](https://user-images.githubusercontent.com/26413131/89766888-29219500-daf9-11ea-94eb-078f46e9be77.png)

- [x] When a repo part contains `@commit`, we can safely assume the user intent is to search only at that commit for a single repo. Currently we expand to `repo:..**@commit` (i.e., all repos matching the string and those commits). Adding this TODO item here only because the fix should be really easy #12892.

- [x] Repo revs: unexpected behavior here. For example, [`repo:github.com/sourcegraph/sourcegraph@qqq`](https://sourcegraph.com/search?q=repo:github.com/sourcegraph/sourcegraph%40qqq&patternType=literal) returns results for a query that is equivalent to `repo:github.com/sourcegraph/sourcegraph*@qqq`, rather than seeing the `github.com/sourcegraph/sourcegraph` part as an exact match with non-existent `@qqq` branch. I.e., for globbing syntax `repo:github.com/sourcegraph/sourcegraph@qqq` we should see this:

![Screen Shot 2020-07-24 at 3 18 13 PM](https://user-images.githubusercontent.com/888624/88439736-e8b7dc80-cdc0-11ea-8f55-2a79da9ae244.png)

but instead we see the equivalent of  `repo:github.com/sourcegraph/sourcegraph*@qqq`:

![Screen Shot 2020-07-24 at 3 19 23 PM](https://user-images.githubusercontent.com/888624/88439795-12710380-cdc1-11ea-8f02-1a8a609db798.png)

This is a good example to fix and test with the integration tester. I will give @stefanhengl a rundown of that next time we talk.

- [ ] The order of results varies with `count:` 

**@rvantonder's idea**: what if we just took a query like `repo:github.com/sourcegraph/sourcegraph` and converted it to: `repo:github\.com/sourcegraph/sourcegraph$ or repo:^github\.com/sourcegraph/sourcegraph/.*`. The `or` evaluation will mean it searches first for the exact string, and if there are enough results, it returns (shortcircuits). Otherwise, it will search 'the rest'. Only thing to be careful of is if the left side returns some results, and we search the right side too, and get results, we'd need to dedup for the left side. Basically, this expression approximates an ordered search that first tries an exact search and then a fuzzy search (instead of us having to write the code for performing an exact search, check results, and then perform fuzzy search).

https://sourcegraph.com/search?q=repo:github.com/sourcegraph/sourcegraph+file:README.md+%23+count:100&patternType=literal
![image](https://user-images.githubusercontent.com/26413131/89660587-d6b25f80-d8d1-11ea-91a0-4f595b935032.png)
![image](https://user-images.githubusercontent.com/26413131/89660639-e8940280-d8d1-11ea-8316-b0364ba4444d.png)

- [x] Alerts propose queries with regex syntax. This is coming from backend alerts and we should run the glob transformer on the proposed queries. Example:

![Screen Shot 2020-07-24 at 3 30 36 PM](https://user-images.githubusercontent.com/888624/88440415-bb6c2e00-cdc2-11ea-9cb8-441018261999.png)

- [x] Web query hovers describe regex-compatible patterns, not globbing

![Screen Shot 2020-07-24 at 3 35 24 PM](https://user-images.githubusercontent.com/888624/88440616-5fee7000-cdc3-11ea-91c1-fae49e304dca.png)

- [x] Currently, we ignore the special meaning of `^` (negation) in character classes `[a-zA-Z0-9]` when we translate a globbing pattern to regex. Hence `^` as the first character in a character class is translated to negation although in globbing it represents the literal character `^`. We should escape `^` or move it to the end of the character class to better reflect the user's intent.

- [x] investigate whether suggestions should append an implicit * to the current field's value. Glob is different from regex when it comes to capturing the user's intent while typing. For example: A substring of a filename 'foo.txt', say `fo`, will match `foo.txt` in regex, but not in glob. Suggestions are helpful because either the user doesn't know how to finish the query or does not want to type out a very long string. We should aim to mimic the behavior of pressing `Tab` in Terminal.

- [x] conflicting repos show alert with regex anchors
![image](https://user-images.githubusercontent.com/26413131/89552904-14998000-d80d-11ea-8be1-85e2f1f96a29.png)

- [x] Exact versus fuzzy file matching, especially for files. We need to make a decision here. With globbing, the query [repo:github.com/sourcegraph/sourcegraph file:search.go](https://sourcegraph.com/search?q=repo:github.com/sourcegraph/sourcegraph+file:search.go&patternType=literal) implies exact paths, and won't find results. With regex, it'll find all the files that have `search.go` (i.e., equivalent to the glob syntax `file:*search.go*`). We know that _it could be the case_ that we want to keep something like `search.go` to imply an exact path (e.g., we are in favor of this for [repos](https://docs.google.com/document/d/1OPyX4KbgUgdeRxvVkm1gRS0PiUtxfO9hAgaNUoMdd2Y/edit?disco=AAAAJ_F3n4w). But at the same time, I found myself being in the habit of typing out `file:search.go` and expecting a search, and then realizing I would need to add `file:*search.go`. Initially I felt like I should not have to add the glob star and would be happy for it to just search, but that may be an issue of habit. Or, it might be something that only applies to `file` and not `repo`. High level thought: if the exact path doesn't match, when run an alert for the fuzzy version, then return any of those results _and_ an alert that says "I interpreted your search as `file:*search.go`", all Google-style, since the other thing didn't return results. Anyway, something to think about. (We went with magic fuzzy matching, similar to what we do with regex, and also a smarter sort in #12766).

  - [ ] with magic fuzzy matching, the user cannot specify exact paths anymore, which is fine for files, because we put exact matches on top. However, for repos, this causes us to search unnecessarily in repos that share a common prefix. Sourcegraph's org is a good example: 
![image](https://user-images.githubusercontent.com/26413131/89660415-99e66880-d8d1-11ea-941b-21c4cac3d0a5.png)

- Not in scope for this issue, since we will do an internal-only trial first. But, if we do decide to turn this on for all of sourcegraph, the search landing page at https://sourcegraph.com/search and search pages syntax for things like `repo:^github\.com/golang/go$ type:diff after:"1 week ago"` need to be updated.

- [ ] ~Minor: a query like `repo:github.com/sourcegraph/sourcegraph` will kick off a search and show a repo result (e.g., it goes to the [search page](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24&patternType=literal)). Since it is a direct match, we could redirect to the [repo browser page](https://sourcegraph.com/github.com/sourcegraph/sourcegraph). _However_ because our existing functionality follows the same behavior (going to the search result rather than page) even if the regexp was exact like `repo:^github\.com/sourcegraph/sourcegraph$`, I consider this optional, and it would be a web change (though I think we can make the call--basically, if the search result page would return just 1 result, redirect to repo).~ Declaring this out of scope, since the same behavior is true outside of the globbing option

**Comment by poojaj-tech** [comment]
Linking an error @stefanhengl and I ran into: #12575

**Comment by rvantonder** [comment]
I don't think #12575 is related to the globbing we are adding here. Basically, we don't support any way to process glob patterns on revisions in a general way. This is true of the existing approach (the link and results that 404 in that issue happen without the globbing option), so the globbing support we are adding here won't resolve or address that (we need to actually implement matching revisions according to a glob-like pattern in the backend, which I don't see as a blocker for enabling globbing on the fields). 

Revisions and patterns on them behave inconsistently in general. See #10571. We support, for example, `blah$@*refs/heads/` according to the docs, which is passed through to git directly, and a general globbing syntax is not supported. I myself am confused about this syntax, and even though we tell customers about it and have examples, for all practical purposes I personally just assume we don't support any sort of patterns on branch/commit names until I can spend some dedicated time to investigate how we process these things in the backend, which is why I created #10571

**Comment by poojaj-tech** [comment]
thanks! this is really helpful context.

**Comment by rvantonder** [comment]
Following up on the above item:

> Exact versus fuzzy file matching, especially for files. We need to make a decision here. With globbing, the query repo:github.com/sourcegraph/sourcegraph file:search.go implies exact paths, and won't find results. With regex, it'll find all the files that have search.go (i.e., equivalent to the glob syntax file:*search.go*). We know that it could be the case that we want to keep something like search.go to imply an exact path (e.g., we are in favor of this for repos. But at the same time, I found myself being in the habit of typing out file:search.go and expecting a search, and then realizing I would need to add file:*search.go. Initially I felt like I should not have to add the glob star and would be happy for it to just search, but that may be an issue of habit. Or, it might be something that only applies to file and not repo. High level thought: if the exact path doesn't match, when run an alert for the fuzzy version, then return any of those results and an alert that says "I interpreted your search as file:*search.go", all Google-style, since the other thing didn't return results. Anyway, something to think about.

and @keegancsmith 's comment:

> I'm guessing this is a bit tricky around consistency and convenience. ie I like that I can just do -file:_test.go. But I suppose it needs to be **_test.go?

>  if we guide the user that makes a lot of sense. I agree that once you learn to include ** it becomes very natural and much more exact.

I think we are going to get flak if we enforce the `**` requirement, even if we teach users about this new ability. I believe we can preserve consistency and convenience with the following approach. The crux is that the user may search for an exact path, or a pattern, and they don't necessarily want to add extra syntax to communicate that intent. So, if the input is `file:foo.go` then:

- We check first for the existence of the `foo.go` as an exact filepath of the repo. I.e., match `^foo.go$`. If there's a hit, we return/search that file only.
  - Enhancement, if we can add it to the web changes: We communicate what happened with a _small_ banner saying "Exact file path foo.go matched. Search for more files with `file:**foo.go**`" or whatever the glob pattern would be.
- If there is no hit for `foo.go`, we expand it to what we do today for `foo.go` (i.e., the glob becomes, I think `**foo.go**`). We then return/search that result set
  - Enhancement: Small banner saying "No exact match for foo.go, searching for pattern **foo.go** instead". 

Any input containing glob syntax (`file:*foo.go`) is interpreted as normal. 

The reason I think the above "magic" is acceptable, is because we already do this magic for regex: on `file:foo.go`, we expand it to something equivalent to `file:(.*foo.go.*)`. It's also predictable and consistent, it's just that there's an additional behavior that we insert for convenience.

Other ideas? I've thought about an alternative where, given `file:foo.go` we jump right ahead and search for `file:**foo.go**`. Given a path like `file:a/b/path`, we would do the same (and if the path is exact, we would only match the exact path, so that works). The trouble with going straight ahead with `file:**foo.go**` is that there is then no way to refer to `foo.go` as the exact file path at the root directory: it will always be interpreted as a pattern, because we have no equivalent of regex anchors to communicate that it is exact. Because we now have a reasonable search behavior that is _inexpressible_ (i.e., it won't be possible to search only an exact path at the root of a directory) this is a big no no. So, to overcome that it would impose that we introduce a way to refer exactly to a file at the root of the repository, like `./foo.go`, which I'm not really feeling.

**Comment by poojaj-tech** [comment]
Since there can only be only one exact match, knowing we don't rank results in frontend today, would it still be possible just in this case to return the following:
search box: `file:foo.go`
--------------------------------------
Exact match
———
All other matches 
———
———
....
--------------------------------------
Return both results instead of a banner with syntax suggestions - the exact match first if one exists for foo.go (globbing _file:foo.go_), then the list of all other matches (globbing _file:**foo.go**_).
I might not even mention the syntax difference for each. If this is such a common search, we would want to offer them a more convenient syntax that gets them all the results by typing just _foo.go_.
Thoughts?

**Comment by rvantonder** [comment]
@poojaj-tech I think that's a great idea! We could probably do this fairly easily: currently we sort all result matches (by repo by file). To put that at the top, we would just look in that result set for an exact path match, and prepend it to the list of results. That operation is probably cheap enough that it won't have a big perf hit.

> I might not even mention the syntax difference for each. If this is such a common search, we would want to offer them a more convenient syntax (like you mention above) that gets them all the results by typing just foo.go.

Yes, agree. If we point out 'exact match' versus 'other matches' we don't even have to mention that we ran the equivalent of `**foo.go**`.

**Comment by keegancsmith** [comment]
I think the sort of magic which responds to the results makes things quite complicated to understand. Displaying different results differently makes a lot of sense to me and can be done purely in the code that collects results so that sounds much more reliable.

Another suggestion, which I think I have seen done before. If your glob doesn't contain a `/` or `**` there is an implicit transormation to `**G**` where `G` was the original glob. If we have a way to reference root files (`/` prefix?) this allows all the same power with the same convenience.

**Comment by poojaj-tech** [comment]
Was just testing IDE/other tools, they don't delineate "exact" versus "other matches" with section headers, so not completely sure if we need to do either. A good UX to test. 
@stefanhengl pulled data for `file:` filter usages on Sourcegraph cloud for June and July in [this doc](https://docs.google.com/spreadsheets/d/1nzomTcGm1NuY4ZzvteCAQu82H6H0Cc5asoOhcLhN8yg/edit#gid=813984086). There's a few more expressive regex use cases, will separate them out. Perhaps the new `and/or` syntax will help with expressing these.

**Comment by rvantonder** [comment]
> I think the sort of magic which responds to the results makes things quite complicated to understand. Displaying different results differently makes a lot of sense to me and can be done purely in the code that collects results so that sounds much more reliable.

Agree. What I meant to communicate is the order of best-effort assumptions we should make on the intent of a user's query (rather than explain it in terms of introspecting results). The assumption being what you mentioned: absence of glob syntax (like `file:G`) implies looking for results that match a substring (implicitly `file:**G**`), but exact matches should take precedence, since it has a higher likelihood of being the original intent. 

Like you mention, we would definitely need a reference to root files in the form of `/` or `./`, because if we always assume the intent of `file:G` is a pattern, then there is no way to disambiguate `file:G` from an exact match of `file:/G` versus `file:a/b/G`. For the sake of a simplifying assumption in the implementation, i.e., without introducing the `/` part, I feel like we can run a search for a query `repo:foo file:bar` as `repo:**foo** file:**bar**` and then decide to show either only exact matches, or exact matches first and fuzzy matches. Otherwise, we should spec out briefly the implementation of the extra work of adding `/`... and commit to that.

@poojaj-tech: 

> There's a few expressive regex use cases that globbing doesn't cover, will separate them out. Perhaps the new and/or syntax will help with expressing these.

This would be useful! Yeah, I fully expect that globbing should work in tandem with `or` operators (which is, I think the only real thing that regex gives that globbing doesn't). I'm aim to activate `or` operators on `file` and `repo` at around the same time, but it may lag by a week or so.

**Comment by keegancsmith** [comment]
> What if we sort exact matches by length (keeping alphabetical order for everything else)? This way exact matches on root level would always come first and we would not need to introduce a new identifier for root files.

I like this approach. In fact we implemented something like this a long time ago. IE we implemented some "ranking" on results based on input. So a match on a filename is ranked higher than matching on a dirname, etc. I think simple things here go a long way. I think our current approach of sorting is just naive, so as long as we are mostly deterministic then what we are doing is good.

**Comment by rvantonder** [comment]
Filed https://github.com/sourcegraph/sourcegraph/issues/12889 where we have some perf issue searching for repo paths, and which negatively affects globbing due to the way we convert these to a pattern. Mysterious, haven't dug into it deeper.

**Comment by lguychard** [comment]
We have dropped globbing for now.
