### ISSUE TITLE
Add tags to Git-extras extension

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#12485]
Git-extras extension has no tags assigned. It comes up when searching for keywords like 'GitHub' or 'GitLab' but other related terms are not searchable. In particular, it is impossible to search for 'blame': 

<img width="1170" alt="Screenshot 2020-07-26 at 14 38 32" src="https://user-images.githubusercontent.com/20326070/88479329-9f959300-cf4e-11ea-9c95-4d0cc425d702.png">

Proposition:
Add the following tags to improve search experience:
- 'blame'
- 'GitHub'
- 'GitLab'
- 'code host'
- 'author'

Tags are up for discussion - I would love to see your feedback and other ideas 🌟

This improvement came up when working on the 'Extensions discoverability' project [#11872](urlhttps://github.com/sourcegraph/sourcegraph/issues/11872)

Git-extras currently (no tags):
<img width="1156" alt="Screenshot 2020-07-26 at 14 42 52" src="https://user-images.githubusercontent.com/20326070/88479424-4aa64c80-cf4f-11ea-8019-1c9dd9f78c77.png">

@rrhyne - regarding our discussion from last week ☝️
@christinaforney @felixfbecker please, review. Thank you!

**Comment by rrhyne** [comment]
Good catch! Also, the extension search should leverage descriptions: https://github.com/sourcegraph/sourcegraph/issues/11264.

**Comment by limitedmage** [comment]
Pull request here: https://github.com/sourcegraph/sourcegraph-git-extras/pull/138

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by limitedmage** [comment]
Completed and published 👍

![Screen Shot 2020-08-13 at 10 04 00 AM](https://user-images.githubusercontent.com/206864/90164560-69c51c80-dd4c-11ea-9222-73b0812bd0f5.png)
