### ISSUE TITLE
Banner messaging is confusing, for example: "Unindexed repositories with structural search"

### ISSUE THREAD

**Issue by poojaj-tech** [sourcegraph/sourcegraph#12499]
Get customer insights on what's confusing, add logging to gauge which banners are shown the most
Audit all banner messaging 
Include search syntax examples in banners where possible?

#### Expected behavior:
Understand that they can reach out to admins to this is on for repositories 
#### Actual behavior:
Immediately thought search was broken for them

![109431530_315982736225866_314350281374927002_n](https://user-images.githubusercontent.com/57463526/88587577-fcef1a00-d00a-11ea-99af-bff2c5864ca0.png)

**Comment by LaureenH** [comment]
I'm a fan of messages that are human, relatable, and most important, easily and clearly actionable for the user. I'm not clear in this situation what the remedy is. Is it that this functionality (indexing repos) is not available in SG right now, or that the user needs to ask an admin to index the currently not-indexed repos? We want the error message to first surface the solution to the problem. "Your search includes non-indexed repositories. Please contact your company's Sourcegraph admin to index the repositories. Learn more about managing indexed repositories..."

**Comment by lguychard** [comment]
We now have unindexed structural search, and these alerts have been much improved.
