### ISSUE TITLE
Permission denied error updating repos from visual studio team services

### ISSUE THREAD

**Issue by mrubinsk** [sourcegraph/sourcegraph#125]
- **Sourcegraph version:** 
2.10.2 and 2.10.3

- **Platform:** 
Ubuntu 16.04.5 LTS
Repositories configured via "repos.list": []
example entry:
```
        {
            "url": "https:\/\/username:personal_access_token@organization_name.visualstudio.com\/\/ProjectName\/_git\/RepoName",
            "path": "RepoName",
            "links": {
                "commit": "https:\/\/organization_name.visualstudio.com\/ProjectName\/_git\/RepoName\/commit\/{commit}"
            }
        }
```

#### Steps to reproduce:

1. Upgrade functioning install from a version prior to 2.10.2 (I was on 2.10.0, but can verify that 2.10.1 also works as expected).

#### Expected: 
Repositories update normally.

#### Actual:
Log fills with permission denied errors like:

16:18:03      gitserver | t=2018-08-21T16:18:03+0000 lvl=eror msg="Failed to update" repo=RepoName error="exit status 128" output="fatal: Authentication failed for 'https://username:personal_access_token@organization_name.visualstudio.com//ProjectName/_git/RepoName/'\n"

Manually navigating to the repository copy in .sourcegraph/data/repos and doing a git fetch works as expected. Reverting install back to 2.10.1 also causes repositories to update as expected.

**Comment by dadlerj** [comment]
Sorry @mrubinsk, thanks for the report
