### ISSUE TITLE
update lsif.dev

### ISSUE THREAD

**Issue by shrouxm** [sourcegraph/sourcegraph#12501]

**Comment by aidaeology** [comment]
Todo: Review https://lsif.dev and update the LSIF Indexer table and make sure info is accurate.

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
