### ISSUE TITLE
Incorrect search-based definition highlighting

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#12500]
Highlighting is wrong in definitions panel: https://k8s.sgdev.org/ghe.sgdev.org/sourcegraph/DIYgod-RSSHub@638e418b093c4b93e783e26547642243ee413c7b/-/blob/lib/routes/douban/people/status.js#L37:11&tab=def

<img width="566" alt="Screen Shot 2020-07-27 at 3 16 08 PM" src="https://user-images.githubusercontent.com/103087/88587804-282e3500-d01c-11ea-82a8-78aa146de819.png">

**Comment by efritz** [comment]
This was previously an issue in references, which was fixed by increasing the number of characters per line when running ctags.

**Comment by efritz** [comment]
I did a small amount of digging and found that this only happens on indexed search. Related, it seems that we always fall back to a starting token of 0 for these results: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/search_symbols.go?subtree=true#L316. Relevant line in zoekt: https://github.com/sourcegraph/zoekt/blame/dae6fc7ecc8fcad0437bd8e50b534ce5d57fa7fc/ctags/json.go#L166

cc @keegancsmith

**Comment by keegancsmith** [comment]
Yeah indexed symbol search never supported this, so likely a regression from back when we introduced indexed symbol search. I don't really understand ctags that well. Why do we need pattern? If I'm not mistaken isn't this used to try help ctags still work when line numbers change. Can't we rely on name?

Additionally, can we modify ctags to return the data we care about? We already compile it ourself?

**Comment by efritz** [comment]
@keegancsmith Could this be fixed by https://github.com/sourcegraph/sourcegraph/pull/14073?

**Comment by keegancsmith** [comment]
we are not storing the pattern in the index, so unfortunately not. Maybe we can use the index, and then hydrate results by passing each file into ctags? ie something speaks to zoekt, which then speaks to symbols asking for tags in a specific file (rather than archive)

**Comment by efritz** [comment]
More context:

The `toSymbolResolver` method in the search code relies on having both a `Name` field and a `Pattern` field populated. In both Zoekt and the symbols service, they return a line number, but no offset on that line that should be highlighted. Before indexed search, we used the Name (the entire line) and the Pattern (the value `^{identifier}$`) that comes back from the symbols service ctags query to match the token in the line to find the offset. Zoket does not populate these fields in the same way, so every definitions pane result is wrong (as are the links from symbols search results).

What needs to happen:

@rvantonder Can you pass the symbols regex pattern down into the symbols resolver? I'm unfamiliar with the code around this area.

Next, we'll have to figure out how to get the matching line context from the symbol resolver code. @rvantonder may need to help me out again here.

After these are done, I can do a correct column offset and pass that back up.
