### ISSUE TITLE
Can no longer click Discussions tab

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#1251]
@sqs is it possible you recent changes may have caused this regression? Any clue what the problem may be?

1. Visit https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/xlang/proxy/server_proxy.go#&tab=history
2. Click the `Discussions` tab -> you cannot.

**Comment by sqs** [comment]
I can repro. Looking into it.
