### ISSUE TITLE
New symbol highlighting highlights unrelated tokens

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#12519]
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:** macOS, Chrome 84

#### Steps to reproduce:

1. Hover on the slash or any other segment from the string in the screenshot below here: internal/extsvc/gitlab/webhooks/merge_requests.go
2. See the result from the screenshot

#### Expected behavior:
It highlights nothing else, or gitlab maybe.

#### Actual behavior:
GitHub in a string and GitLab as a type are highlighted as well
![image](https://user-images.githubusercontent.com/19534377/88681164-90027f80-d0f1-11ea-8b90-f9f725636d4c.png)
(You could argue gitlab is correctly highlighted, as it's the import for that one). But the Github highlight definitely seems off (and the highlighting of the `/`)

**Comment by efritz** [comment]
I think related: https://github.com/sourcegraph/sourcegraph/issues/2341

**Comment by efritz** [comment]
I think all the remaining work might be just for import strings (as the UI shows): https://github.com/sourcegraph/lsif-go/issues/160. We can probably continue anything else relevant/actionable today there.
