### ISSUE TITLE
Evolution of line of code - where it originated or was derived from (prior git blames, similar code blocks)

### ISSUE THREAD

**Issue by poojaj-tech** [sourcegraph/sourcegraph#12526]
#### Feature request description
Customer feedback from NPS

> Feature request: more context on code evolution -- often when reviewing or reading code, I want to see how a particular line changed over time.

#### Is your feature request related to a problem? If so, please describe.
Thread
> would showing not just the most recent Git blame but all prior blames (author + commit message + date) be helpful?
> 
> Yeah, seeing prior blames would be great with the ability to jump back to them quickly.
> 
> Another far out idea: seeing other code blocks that are similar or the same across repositories if they exist. I see a lot of code that is more or less copied from one place to another when reviewing and it would be fantastic to see where the work originated or was derived from. 

#### Additional context
Company: https://app.hubspot.com/contacts/2762526/company/814799425
Customer: https://app.hubspot.com/contacts/2762526/contact/16031951/

**Comment by scalabilitysolved** [comment]
Is this something we want to keep/close or move to productboard @macraig ?

**Comment by macraig** [comment]
@scalabilitysolved I believe this is already possible by using the History button.
