### ISSUE TITLE
Author searches report 'no results', should hint to use type:commit or type:diff

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#12527]
Some filters result in 'No result' and do not help the user understand why. Example:

1. Search repo:sourcgraph/sourcegraph author:rob@sourcegraph.com
2. Note the user has not included type commit or diff 
3. Run search

#### Expected behavior:
A tip is provided that author searches require type:commit or type:diff.

#### Actual behavior:
3. Receive the "No Results" banner

Identify combinations of languages and types which are not compatible and add hints for the user as to how to produce a valid result.

**Comment by rvantonder** [comment]
Nice, yeah should do this. It'd be worth going through the language spec to see which filters correspond to certain types and always suggest those (I think all of those under [commit parameter](https://docs.sourcegraph.com/user/search/language#commit-parameter) qualify)

**Comment by rrhyne** [comment]
That's a much better approach than addressing these at a single time. Altering the ticket to reflect that. You might need to edit it to be more accurate.
