### ISSUE TITLE
To 'Explore repositories', you need to be a site admin?

### ISSUE THREAD

**Issue by pandravada** [sourcegraph/sourcegraph#1253]
#### Question description

Cannot 'Explore repositories' anymore. It complains saying, I need to be site admin. 
Is this something new. It used to work before...

**Comment by slimsag** [comment]
Hello, where are you experiencing this issue? On Sourcegraph.com or on a private instance? Which version?

This definitely sounds like a bug, and it does not happen on Sourcegraph.com currently (just checked).

**Comment by dadlerj** [comment]
I'm on dev (latest master), and just saw this while I was working on another issue. I'm shown a sign-in screen when I click on "explore" as an _unauthenticated_ user (i.e., with `"auth.public"` set to true). I haven't tested as a signed-in, but non-admin yet.

**Comment by beyang** [comment]
We're removing the special page for "Explore repositories" in newer versions of Sourcegraph. The new "Explore repositories" button will just link to a search for `repo:`, which will show all repository results in the search UI.

So the workaround (which will soon become the actual thing) is just to search for `repo:`.

**Comment by dadlerj** [comment]
@beyang my comment was in reference to the *Explore* page, not the old *Explore repositories* page. This same issue appears to affect that one, even if it's not what was originally reported.

**Comment by beyang** [comment]
@dadlerj that seems like a different bug that what OP was reporting (and not sure if a bug or intentional—a lot of the content on /explore doesn't seem actionable unless you are authenticated; i.e., it seems like a page you should visit immediately *after* signing up). If it is a bug, let's file another issue.
