### ISSUE TITLE
Firefox addon permissions issues?

### ISSUE THREAD

**Issue by leezu** [sourcegraph/sourcegraph#1254]
Thanks for distributing a pre-built version for Firefox again (https://github.com/sourcegraph/sourcegraph/issues/744). I noticed that upon installing the pre-built version, permission to access data on all websites is requested. When installing Sourcegraph for Chrome however, only access permission for `github.com` and `sourcegraph.com` is requested?

Is this intended? Or is there a bug in the `manifest.json`?

(Installing from https://storage.googleapis.com/sourcegraph-for-firefox/latest.xpi )

**Comment by leezu** [comment]
It seems in principle the optional permissions API should also be supported by Firefox https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/permissions/request

**Comment by sqs** [comment]
Unfortunately, there is a known issue in Firefox preventing us from using that API. See https://github.com/sourcegraph/sourcegraph/issues/760#issuecomment-440724347. (Closing as duplicate.)
