### ISSUE TITLE
Sourcegraph button on GitHub should go to the corresponding sourcegraph page instead of the repo root

### ISSUE THREAD

**Issue by tbodt** [sourcegraph/sourcegraph#12551]
Sometimes I do a github search and then decide the results aren't cutting it and I want to try sourcegraph. I'd like a sourcegraph button right there on the search page that takes me to sourcegraph. Also if I'm looking at a file or directory and I click the sourcegraph button, I'd like to see the file I was looking at, instead of the repository root.

**Comment by taras-yemets** [comment]
@tbodt 'Search on Sourgraph' buttons were added in [PR#30399](https://github.com/sourcegraph/sourcegraph/pull/30399)

**Comment by vdavid** [comment]
This is fixed.
E.g. if you're here: https://github.com/sourcegraph/sourcegraph/search?q=test
and click the Sourcefgraph button, it correctly goes to 
https://sourcegraph.com/search?q=test+repo:sourcegraph/sourcegraph$
