### ISSUE TITLE
Back/forward-compatibility for Sourcegraph extensions

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1255]
From @lguychard  (copied from https://github.com/sourcegraph/sourcegraph-basic-code-intel/pull/8#discussion_r239192158):

We should plan to handle the issue of extension API breakage differently - IMO there should be no backwards compatibility handling in extension code, it should be handled at the registry/extension host level.

eg.:

If the user has activated the Sourcegraph extension E, which is only compatible with extension API vN, and his browser extension packages extension API vN+1, he receives a notification that "Incompatible extension E could not be activated"
If the user's browser extension packages extension API vN, the extension registry will provide the latest version of E that was compatible with extension API vN, even if the very latest version of E on the registry was coded against vN+1

**Comment by lguychard** [comment]
Prerequisite: #2080

**Comment by felixfbecker** [comment]
> If the user's browser extension packages extension API vN, the extension registry will provide the latest version of E that was compatible with extension API vN, even if the very latest version of E on the registry was coded against vN+1

I doubt this will work in practice because the old version can be incompatible for many other reasons than just the extension API - GraphQL changes, langserver changes, raw API changes...

**Comment by chrismwendt** [comment]
One example of a new GraphQL change that [basic-code-intel depends on](https://github.com/sourcegraph/sourcegraph-basic-code-intel/pull/65) is the [`fileLocal` field](https://github.com/sourcegraph/sourcegraph/pull/2788).

Parsing the `buildVersion` would be difficult and fragile, so basic-code-intel just reads a global setting for now.

Could the Sourcegraph instance expose a set of features/capabilities that it supports (@felixfbecker's idea)? I see there are features for the product license and tags per user, but neither of those sound relevant.

**Comment by felixfbecker** [comment]
You could use GraphQL schema introspection, or try/catch the query with/without querying for fileLocal

**Comment by chrismwendt** [comment]
GraphQL schema introspection will work, thanks!

**Comment by lguychard** [comment]
Also consider:
- Private registries
- Code intel fixes that need to be deployed across all versions, without needing to backport fixes to older extension versions.

We've discussed this with @sourcegraph/web and determined that we should close this until a concrete use case comes up that would make this necessary. For now, the least complex solution is to maintain backwards compatibility in extension code.
