### ISSUE TITLE
Implement combined diff stat on changesetspec resolver

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#12564]
Implement the API change proposed in https://github.com/sourcegraph/sourcegraph/issues/12464.

And the already existing `Campaign.DiffStat` should use the cached `DiffStat` field on changesets.

**Comment by mrnugget** [comment]
Updated the ticket to say that it includes using the cached values on `Campaign.DiffStat` too if that's not the case already.
