### ISSUE TITLE
Hovering on a specific class sometimes takes a while to load all the references

### ISSUE THREAD

**Issue by poojaj-tech** [sourcegraph/sourcegraph#12569]
**Sourcegraph.com:** 
Customer feedback:
https://app.hubspot.com/contacts/2762526/contact/24612301/

> Hover my mouse on a specific class, sometimes it will take a while to load all the references.

**Comment by efritz** [comment]
![Kapture 2020-07-31 at 16 36 11](https://user-images.githubusercontent.com/103087/89079424-0d293100-d34c-11ea-9694-7bfd3a36e12f.gif)

Looking to confirm if the references refer to the identifiers that get highlighted on hover, or the results that appear in the bottom pane once you click the Find References button?

**Comment by ekss1121** [comment]
I am seeing this issue very intermittently. The repo I am checking is [ReactivX/rxjs](https://github.com/ReactiveX/rxjs). Sometimes when I hover on a symbol the definition in the popup menu will show a loading ring for up to 5 sec before getting the definition. There is one possible way to replicate this is to leave the web page inactive for a while.

**Comment by poojaj-tech** [comment]
thanks for the additional information @ekss1121!

**Comment by efritz** [comment]
@ekss1121 We've recently published some fixes to a similar issue we found in the code intel extensions as well as the sourcegraph.com release (and the 3.20 release if you're on a private instance).

Could you tell me if you see a noticeable difference? Are you still able to replicate it, or was it fixed by the recent changes?

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by ekss1121** [comment]
@efritz , I haven't seen any slow loading issue for the past 2 days. Thanks!

**Comment by efritz** [comment]
🎉 !
