### ISSUE TITLE
Implement GraphQL API that allows to fetch campaigns by namespace

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#12563]
See this ticket for the API design: https://github.com/sourcegraph/sourcegraph/issues/12470

**Comment by mrnugget** [comment]
Just a note for the implementation here: the connection between `user|org` and `campaign` is "namespace". So, `user.campaigns` returns the campaigns where the `campaign.namespace` points to the user. Whether the user created or applied the `campaignSpec` doesn't play into it.
