### ISSUE TITLE
Result link for revisions with globbing opens to 404

### ISSUE THREAD

**Issue by poojaj-tech** [sourcegraph/sourcegraph#12575]
Results look off and clicking on link from results page opens to 404
[repo:github.com/sourcegraph/sourcegraph@3.1*](https://sourcegraph.com/search?q=repo:github.com/sourcegraph/sourcegraph%403.1*&patternType=literal)

**Comment by rvantonder** [comment]
The revision syntax and search support is ill-defined and does not necessarily play well with other params. See #10571. I basically don't expect any rev syntax containing a `*` to return reasonable things except for the two things explicitly documented to work: `*refs/heads/` and `*refs/tags/` with potential names and negation.

**Comment by poojaj-tech** [comment]
Got it — will close this in favor of #10571 then.
(references these [docs](https://docs.sourcegraph.com/user/search/queries#repository-revisions) for revision syntax)

**Comment by rvantonder** [comment]
Added the example here to that issue, it's another case that highlights some issues.
