### ISSUE TITLE
Filter "content:" docs aren't clear

### ISSUE THREAD

**Issue by poojaj-tech** [sourcegraph/sourcegraph#12576]
**From docs**
https://docs.sourcegraph.com/user/search/queries#structural-search
content:“pattern” | Explicitly override the search pattern. Useful for explicitly delineating the pattern to search for if it clashes with other parts of the query.

**What's confusing**
- Parts of the query mean avoiding conflicts with existing syntax keywords field names, :, etc
- Use case isn't immediately obvious without examples

**Comment by leonore** [comment]
seems like this is outdated as this is the current state of the `content:""` documentation:

<img width="848" alt="image" src="https://user-images.githubusercontent.com/29406849/181789516-a1296899-194a-4279-8b21-54be1841b317.png">

closing this, if deemed not satisfactory enough it can be reopened! 😄
