### ISSUE TITLE
LSIF Diagnostics query fails with `exit status 128 (stderr: "fatal: bad object $COMMIT_HASH")`

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#12585]
Repro in [API Console](https://sourcegraph.com/api/console#%7B%22operationName%22%3A%22ESLintDiagnostics%22%2C%22query%22%3A%22query%20ESLintDiagnostics(%24repo%3A%20String!%2C%20%24path%3A%20String!)%20%7B%5Cn%20%20repository(name%3A%20%24repo)%20%7B%5Cn%20%20%20%20commit0%3A%20commit(rev%3A%20%5C%22646ebbb62f5ed21ab1feec1e4fab19a0bb39845e%5C%22)%20%7B%5Cn%20%20%20%20%20%20tree(path%3A%20%24path)%20%7B%5Cn%20%20%20%20%20%20%20%20lsif(toolName%3A%20%5C%22eslint-formatter-lsif%5C%22)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20diagnostics%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20totalCount%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%20%20commit1%3A%20commit(rev%3A%20%5C%221d5a67069d35c8840a075207aa77890ae61e7f89%5C%22)%20%7B%5Cn%20%20%20%20%20%20tree(path%3A%20%24path)%20%7B%5Cn%20%20%20%20%20%20%20%20lsif(toolName%3A%20%5C%22eslint-formatter-lsif%5C%22)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20diagnostics%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20totalCount%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%20%20commit2%3A%20commit(rev%3A%20%5C%223029f7449c0fb1198ffcbaee4ebdf25b8ee02ff7%5C%22)%20%7B%5Cn%20%20%20%20%20%20tree(path%3A%20%24path)%20%7B%5Cn%20%20%20%20%20%20%20%20lsif(toolName%3A%20%5C%22eslint-formatter-lsif%5C%22)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20diagnostics%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20totalCount%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%20%20commit3%3A%20commit(rev%3A%20%5C%22255cb618c755026d801b2d2fd5bc9d30197c19a5%5C%22)%20%7B%5Cn%20%20%20%20%20%20tree(path%3A%20%24path)%20%7B%5Cn%20%20%20%20%20%20%20%20lsif(toolName%3A%20%5C%22eslint-formatter-lsif%5C%22)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20diagnostics%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20totalCount%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%20%20commit4%3A%20commit(rev%3A%20%5C%22c6db6b232639b991eb5746a9b90daf12f6133c7d%5C%22)%20%7B%5Cn%20%20%20%20%20%20tree(path%3A%20%24path)%20%7B%5Cn%20%20%20%20%20%20%20%20lsif(toolName%3A%20%5C%22eslint-formatter-lsif%5C%22)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20diagnostics%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20totalCount%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%20%20commit5%3A%20commit(rev%3A%20%5C%22d07cd9909a5fb6f32925653432ac5b1e6858be00%5C%22)%20%7B%5Cn%20%20%20%20%20%20tree(path%3A%20%24path)%20%7B%5Cn%20%20%20%20%20%20%20%20lsif(toolName%3A%20%5C%22eslint-formatter-lsif%5C%22)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20diagnostics%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20totalCount%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%20%20commit6%3A%20commit(rev%3A%20%5C%22a8a890b684f33696c01644a3873a3192444b4944%5C%22)%20%7B%5Cn%20%20%20%20%20%20tree(path%3A%20%24path)%20%7B%5Cn%20%20%20%20%20%20%20%20lsif(toolName%3A%20%5C%22eslint-formatter-lsif%5C%22)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20diagnostics%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20totalCount%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22variables%22%3A%22%7B%5Cn%20%20%5C%22repo%5C%22%3A%20%5C%22github.com%2Fsourcegraph%2Fsourcegraph%5C%22%2C%5Cn%20%20%5C%22path%5C%22%3A%20%5C%22%5C%22%5Cn%7D%22%7D)

This queries LSIF data for various commits (which exist in the repo). All queries fail with
```
exit status 128 (stderr: \"fatal: bad object $COMMIT_HASH\")
```
where `$COMMIT_HASH` is some random commit hash (that does not match the input hash, and indeed does not exist in the repo).

This currently breaks the ESLint code insight.

cc @efritz

**Comment by efritz** [comment]
I was able to reproduce this and traced the request - it looks like we were finding 600+ "closest uploads" for this query due to a bug in the way we were selecting, some of which were commits that were force-pushed away on the code host. This particular error was trying to transform document paths from the upload's commit into paths in the target commit. Because the upload commit didn't exist, gitserver failed the request here.

After https://github.com/sourcegraph/sourcegraph/commit/3cd7ca975ba0c467fbbd2c0a8ea2603489c2d422 landed, this doesn't occur on the same query. I've filed https://github.com/sourcegraph/sourcegraph/issues/12588 to resolve the underlying issue in a more permanent way.
