### ISSUE TITLE
Error: Repository not found from code discussions extension

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#1260]
I always get this error on repos, e.g. https://sourcegraph.com/github.com/sourcegraph/react-loading-spinner/-/blob/src/LoadingSpinner.tsx#L7:14&tab=references
```
errors.ts:37 Uncaught (in promise) Error: repository not found
    at Object.exports.createAggregateError (errors.ts:37)
    at Object.<anonymous> (api.ts:167)
    at api.ts:252
    at Object.next (api.ts:252)
    at o (api.ts:252)
```

The stack trace points to `renderMarkdown()`.

**Comment by nicksnyder** [comment]
I am not able to reproduce this error. What are your user settings? https://sourcegraph.com/users/nick/settings

**Comment by felixfbecker** [comment]
I noticed this comes from the "Inline discussions" button (and is triggered again every time you click it). Reassigning to @slimsag
