### ISSUE TITLE
Protobuf code intelligence

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#1263]
For now, while gathering requirements and discovering specific setups users have, we're working under the assumption that the final result of the Thrift proposal in #669 will similarly work for Protobufs.

**Comment by kminehart** [comment]
There's a lot of plugins available for Protobuf / protoc  as well,. I would be interested to see if it's possible to locate the origin of stubs generated by `go-grpc` or [twirp](https://github.com/twitchtv/twirp) or if it would only be possible for interfaces generated by `protoc-gen-go`.

**Comment by aidaeology** [comment]
Closing this issue as we are consolidating conversation for support in #981
