### ISSUE TITLE
Create technical design diagrams for code intel systems

### ISSUE THREAD

**Issue by aidaeology** [sourcegraph/sourcegraph#12638]
As part of our new engineer onboarding effort we want to supplement our written documentation with visual diagrams + specs for the most critical or complex components and processes. Visual diagrams can boost async learning as well as provide a better understanding of the parts that make up the big picture. Completed diagrams will be stored in the code intel google drive. Code intel team has identified these initial diagrams as useful for us to create:

1. Bundle Manager sequence diagram
2. Inter-service request diagrams
3. LSIF indexers general flow diagram, show how they traverse repository files and parse their contents.

**Comment by efritz** [comment]
Finished.
