### ISSUE TITLE
Code intel stops working on local instance when sourcegraph can no longer phone home

### ISSUE THREAD

**Issue by PaulMooney56** [sourcegraph/sourcegraph#12633]
- **Version 3.18.0**
- **OS: Ubuntu Server 20.04 LTS**

#### Steps to reproduce:

1. Install Sourcegraph on a local instance
2. Add a repo, explore the repo and enjoy code intel and everything working
3. Sever the connection to the internet

#### Expected behavior:
I would expect everything to continue working

#### Actual behavior:
The code intelligence stops working

It is slightly concerning that sourcegraph needs to phone home to continue working. I consider this a privacy issue since I don't trust what data it's actually sending back to sourcegraph. Even so, most people don't want to expose their repos to the internet. This is basic "security in depth".

**Comment by efritz** [comment]
This is because code intel is provided by [Sourcegraph extension](https://github.com/sourcegraph/code-intel-extensions), which is served from our public extension registry. Enterprise versions of the product allow you to sync the extensions into a local registry so that it can be run in highly firewalled environments, but requires manual syncing of extensions with the upstream.

**Comment by slimsag** [comment]
Expanding on what @efritz said above: Sourcegraph, the application/deployment/Docker container can be 100% fire-walled off with no ill effects. The extension is downloaded by your _browser_ from sourcegraph.com, so you can completely fire-wall off Sourcegraph without a local registry so long as your browser itself can download the extension from sourcegraph.com.

**Comment by PaulMooney56** [comment]
@slimsag: I can tell you right now from testing... I have a web browser running on a computer that has internet and can get to google.com. Code intel still doesn't work if the sourcegraph server does not have an internet connection. The server has to have a connection back to sourcegraph to download the extension. As soon as I give the server internet back, everything works again in the browser.

@efritz: I'd like to try and demo this to my company, but to do that with our source repo, we have everything on the corporate network going through a HTTP/HTTPS proxy. I added the following to my docker invocation:

````
-e HTTP_PROXY="http://company-proxy:1234" -e HTTPS_PROXY="https://company-proxy:1234"
````

and I believe requests are being rejected by sourcegraph to pull the extensions because it's getting the corporate certificate (since its a proxy) instead of the sourcegraph.com one. Is there a way to add the corporate certificate authority to sourcegraph, or did I miss a step?

**Comment by slimsag** [comment]
I am genuinely not sure how that is possible - it should definitely be working - we have several customers running with _exactly_ that same configuration (server with no public internet access, browsers with access to sourcegraph.com) using it fine. There must be another problem / bug here.

Also if you take a look at the browser network tab you'll see we load the extension which provides code intel directly from sourcegraph.com in your browser only:

![image](https://user-images.githubusercontent.com/3173176/89739628-21012100-da37-11ea-957c-63a8792e46f4.png)

Which language are you testing code intel on? Can you try e.g. adding github.com/gorilla/mux to your Sourcegraph instance and testing the Go code intel

Is there any info in the browser console, or failed requests in the network tab? Can you see the extension download there?

**Comment by PaulMooney56** [comment]
@slimsag Thanks for responding.

I had been playing around with the C++ code intel but for testing purposes, I went ahead and cloned the mux repo as you suggested and went to the developer console in Chrome:

<img width="1579" alt="output" src="https://user-images.githubusercontent.com/69123296/89740740-6fbfb280-da59-11ea-92a9-a02c64db0c85.png">

What I witnessed was that the "graphql?Extensions" sits pending for 20 seconds, then gets a 200 back (as seen in the picture). 

Then there is a log line (that scrolled off) that states:
"DevTools failed to load SourceMap: Could not load content for http://sourcegraph-test:7080/43ad892....worker.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE"

Then the log is spammed with the "Extension X was not found".

As soon as I connect the server to the internet everything works and looks like the screenshot you posted where its able to pull the extensions.

**Comment by PaulMooney56** [comment]
@slimsag @efritz 

Here's an animation of this happening... Just to prove I have internet and code intel is not working, I open another tab and browse Google after hitting refresh on my Sourcegraph window:

![animation](https://user-images.githubusercontent.com/69123296/89741196-44d75d80-da5d-11ea-9304-3392af67dadb.gif)

**Comment by slimsag** [comment]
OK, got it - sorry for the trouble here I must be wrong and we must have some server-side dependency on sourcegraph.com for listing extensions. I thought for sure we did a fall-back to the browser directly reaching sourcegraph.com in this case assuming you had an extension in your site config - but I must be wrong here.

I would say this is not working as intended, because this is a pretty common configuration - but I'll chat with folks here and see what we can do about this.

In the meantime, I'll see if we can send an enterprise trial key your way which would let you download the extensions you want and upload them to your server [as described here](https://docs.sourcegraph.com/admin/extensions#publish-extensions-to-a-private-extension-registry) and then everything should work. If this sounds okay, shoot me an email to stephen@sourcegraph.com

**Comment by PaulMooney56** [comment]
@slimsag  I'm not sure I'd be able to convince management to purchase Enterprise... We'd probably want to start with Team first which doesn't support local extensions. Also, we have no issue with the sourcegraph server being able to hit the internet, the only constraint is that it has to go through a corporate http/https proxy.

After messing around with it a bit, I discovered that the options:

-e HTTP_PROXY="http://company-proxy:1234" -e HTTPS_PROXY="https://company-proxy:1234"

Will make Sourcegraph want to talk to a proxy. The next issue was that Sourcegraph didn't want to accept the corporate CA. I added the CA as a trusted CA to the Sourcegraph server through "update-ca-certificates". I then discovered @keegancsmith work here: https://github.com/sourcegraph/sourcegraph/pull/8092 and added "insecureSkipVerify" to the site config

Looking at the proxy logs, I can now see that the sourcegraph server is able to successfully talk to github (recall we were testing with mux). But the extensions are still not working. From the logs I can see that the sourcegraph server tries to reach out to https://sourcegraph.com but doesn't get anywhere because it's presented with our corporate certificate from the proxy server.

I was a little disappointed because I thought that tls.external / insecureSkipVerify would work on all communication between the sourcegraph server and external entities but it appears to only affect repo related tasks (e.g. Talking to github to check for updates).

All we really need is to just let sourcegraph send all its traffic through a proxy.

**Comment by keegancsmith** [comment]
> I was a little disappointed because I thought that tls.external / insecureSkipVerify would work on all communication between the sourcegraph server and external entities but it appears to only affect repo related tasks (e.g. Talking to github to check for updates).

You managed to find an area we hadn't tested properly! Another customer actually recently ran into this. We need to make our communication back to sourcegraph.com also respect the tls configuration. Previously I was focussed on git cloning/etc and missed this.

**Comment by PaulMooney56** [comment]
@keegancsmith 

Thanks! I look forward to seeing this fix!
