### ISSUE TITLE
Write a migration that deletes all existing campaigns/changesets when upgrading to 3.19

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#12641]
This depends on https://github.com/sourcegraph/sourcegraph/issues/12640 and whether we decide to do it or not.

If we decide we go with the "export & delete everything" option, we need a migration that deletes all campaigns and changesets that were created with the old campaigns workflow.

Something like this:

```sql
delete from campaigns where campaign_spec_id is null;
-- make campaigns.campaign_spec_id not nullable

delete from changesets where campaign_ids -- ... is empty
```

**Comment by LawnGnome** [comment]
We need to make some fields not null as part of the migration: `InitialApplier`, `LastApplier`, `LastAppliedAt`, `CampaignSpecID`, per #12875.

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
