### ISSUE TITLE
Duplicate search results

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#1264]
https://sourcegraph.com/search?q=%22conf.Get%28%29.Gitlab%22+repo:sourcegraph/sourcegraph

![image](https://user-images.githubusercontent.com/754768/49603113-33ac8400-f93f-11e8-87f9-6b1eea04b22c.png)

**Comment by sqs** [comment]
Fixed by https://github.com/sourcegraph/sourcegraph/pull/2186
