### ISSUE TITLE
campaigns: cancelled GitLab pipelines don't take check state out of pending

### ISSUE THREAD

**Issue by LawnGnome** [sourcegraph/sourcegraph#12667]
_Originally posted by @eseliger in https://github.com/sourcegraph/sourcegraph/pull/12139#issuecomment-667984395_

I won't reproduce the full comment here, but basically: a cancelled pipeline was synced and didn't change the check state from pending to whatever is appropriate (probably unknown). I need to investigate the [offending pipeline](https://gitlab.sgdev.org/sourcegraph/bitbucket-server-plugin/pipelines/55) and [merge request](https://gitlab.sgdev.org/sourcegraph/bitbucket-server-plugin/merge_requests/19) in the API to ensure we're doing the right thing.

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by LawnGnome** [comment]
Punting to 3.20, but I have some hope that the fix for this is clean enough that we might want to consider it after branch cut.
