### ISSUE TITLE
Disable low resource utilization alerts

### ISSUE THREAD

**Issue by pecigonzalo** [sourcegraph/sourcegraph#12669]
We currently have multiple `[WARNING] symbols: less than X` that notify about services or resources that are over-provisioned. As we are not periodically reviewing and actioning these alerts, we want to remove their notifications and re-asses how to implement these alerts in the future.

### Task
- [ ] Disable low resource utilization notifications via Slack
- [ ] Disable low resource utilization notifications via site-admin

**Comment by bobheadxi** [comment]
Is this for dot-com or the managed instances? (meeting notes imply the latter)

@slimsag already created a range of issues tracking other utilization alerts on dot-com: https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aopen+is%3Aissue+label%3Asilenced-alert+label%3Adot-com

**Comment by bobheadxi** [comment]
made a response in slack: https://sourcegraph.slack.com/archives/CJX299FGE/p1596505757462700

**Comment by pecigonzalo** [comment]
We have some changes already in 3.19 that might mitigate this, and we will re-review this issue after that release.

**Comment by bobheadxi** [comment]
@pecigonzalo no low-util alerts have fired in the past 7 days for Cloud:

https://sourcegraph.com/-/debug/grafana/explore?orgId=1&left=%5B%22now-7d%22,%22now%22,%22Prometheus%22,%7B%22expr%22:%22alert_count%7Bname%3D~%5C%22.*_low%5C%22%7D%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D

<img width="1703" alt="image" src="https://user-images.githubusercontent.com/23356519/90992907-28066280-e5e5-11ea-9f59-3e601e724e45.png">

**Comment by bobheadxi** [comment]
The low-util alerts were removed in https://github.com/sourcegraph/sourcegraph/pull/16164
