### ISSUE TITLE
Bitbucket Server permissions only supports <2500 repositories

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#12671]
Quoting [our documentation](https://docs.sourcegraph.com/admin/repo/permissions#bitbucket-server):

> You have **fewer than 2500 repositories** on your Bitbucket Server instance.

A customer would like to use Bitbucket Server permissions with 40-50k repositories. How can we make this possible?

https://app.hubspot.com/contacts/2762526/company/407948923/

**Comment by unknwon** [comment]
I believe we stated this because of performance concern while fetching permissions was on the search path cc @tsenart, but it is no longer a concern with background permissions syncing.
