### ISSUE TITLE
Docs are misleading about speed of repository permission synching

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#12679]
The [repository permission synching docs](https://docs.sourcegraph.com/admin/repo/permissions#background-permissions-syncing) state:

> Benefits of backround syncing:
> - ...
> - Users who sign up on the Sourcegraph instance can immediately get search results from the repositories they have access to on the code host.

This misleads me and potential site admins into thinking that somehow a new user who has signed in will immediately have all of their permissions synched magically without delay. I do not see any way that would be possible, and so I assume this sentence is actually meant to say something like:

> Users who sign up on the Sourcegraph instance can immediately get search results from _some_ repositories they have access to on the code host as we begin to incrementally sync their permissions.

https://app.hubspot.com/contacts/2762526/company/407948923/

**Comment by unknwon** [comment]
Imagine the following flow:
1. Site admin set up the Sourcegraph and added all external services.
2. Site admin enabled repository permissions and waiting for it to finish (before announce publicly). At the stage, we've cached "up-to-date" repository permissions with their code host ID if not yet signed up in Sourcegraph.
3. A user signs in via GitHub OAuth, we can immediately recognize what repositories the user has access to via its GitHub ID (or GitLab ID, Bitbucket Server username) from cached data we got in step 2.

Thus what you have suggested is not always true, but I agree it is better.
