### ISSUE TITLE
No alerts fire if repository permissions add substantial performance issues

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#12676]
From what I understand, authorization has some overhead added to requests. This means that if something is wrong when a site admin turns on repository permissions, request latency may go up substantially. There is a panel which shows authorization duration:

![image](https://user-images.githubusercontent.com/3173176/89222165-69c55f80-d589-11ea-9ec7-a40becd1cd7c.png)

But there is no e.g. warning alert which would indicate this being a problem to site admins.

https://app.hubspot.com/contacts/2762526/company/407948923/

**Comment by unknwon** [comment]
I think this will be resolved by https://github.com/sourcegraph/sourcegraph/issues/9923 which always requires an alert.

**Comment by unknwon** [comment]
🤔 I didn't assign myself? ....
