### ISSUE TITLE
It is not called out clearly enough in docs that initial permission synching may take several hours

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#12678]
In https://docs.sourcegraph.com/admin/repo/permissions#background-permissions-syncing there is a point that is very important but us not called out clearly enough at all (emphasis mine):

> Benefits of **backround** syncing:
> 
> 1. More predictable load on the code host API due to maintaining a schedule of permission updates.
> 1. Permissions are quickly synced for new repositories added to the Sourcegraph instance.
> 1. Users who sign up on the Sourcegraph instance can immediately get search results from the repositories they have access to on the code host.
> 
> Considerations when enabling for the first time:
> 
> 1. While the initial sync for all repositories and users is happening, users can gradually see more and more search results from repositories they have access to.
> 1. **It takes time to complete the first sync. Depending on how many private repositories and users you have on the Sourcegraph instance, it can take from a few minutes to several hours. This is generally not a problem for fresh installations, since admins should only make the instance available after it's ready, but for existing installations, active users may not see the repositories they expect in search results because the initial permissions syncing hasn't finished yet.**
> 1. More requests to the code host API need to be done during the first sync, but their pace is controlled with rate limiting.
> 
> Please contact [support@sourcegraph.com](mailto:support@sourcegraph.com) if you have any concerns/questions about enabling this feature for your Sourcegraph instance.

If a customer such as https://app.hubspot.com/contacts/2762526/company/407948923/ was to turn on repository permission synching with several thousand users and 20-50k repositories, this could result in most users being unable to use Sourcegraph for several hours unbeknownst to the site admin.

This point is worth calling out very explicitly as a warning so that site admins know to schedule a specific window during which this will occur.

https://app.hubspot.com/contacts/2762526/company/407948923/

**Comment by tsenart** [comment]
@slimsag: Please propose a change to those docs, it's not clear to me, at least, how you'd want to make this point number 2 stand out more. Can you clarify?

**Comment by slimsag** [comment]
Right now it's kind of hidden under a section of many bullet points and very easy to miss. One thought would be to add:

> **WARNING:** It takes time to complete the first sync. [...]

at the start of each code-host specific section, i.e. before the person starts going through the process of setting it up.

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
