### ISSUE TITLE
Is there any indication that search results may be missing due to permissions?

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#12680]
Users regularly rely on Sourcegraph to get a comprehensive set of results, but with repository permission synching enabled there may be no indication that Sourcegraph is aware of more repositories that may have results that the current user doesn't have access to. I see three problems:

1. The user does not have access at all on the code host, e.g. Bitbucket, and we will not tell them on the search page OR in the search docs currently that there may be more. This is quite bad because it means a user may believe they have a comprehensive list of results, when in reality they need to contact their site admin to get an admin account in order to perform comprehensive searches and get all results.
2. The user **does** have access on the code host, but permissions just haven't synched to Sourcegraph yet. This case is more worrying to me and cannot be fixed just by documentation, because it presents a "I see this result on Bitbucket directly, but Sourcegraph doesn't have it" scenario which is not at all communicate to the user.

https://app.hubspot.com/contacts/2762526/company/407948923/

**Comment by unknwon** [comment]
1. The more repositories on a Sourcegraph instance, the more likelihood that a non-site admin is almost always missing search results from some repositories that the user does not have access to on the code host. The indication we give the user in this scenario is actually leaking the existence of "there are other repositories for the keyword you are searching". I think we just need to ensure the user knows _we return the comprehensive set of results from repositories you have access to_.
2. We are able to give a warning when we detected that we have repositories aren't having permissions mirrored, which the current user may or may not have access to them. However, this warning does not help that if a user just being added to an existing repository on the code host. I think the similar problem exists on repository syncing, how do we ensure/warn a user if something the user searched exists in a new commit on the code host that hasn't fetched by gitserver?
