### ISSUE TITLE
Trailing parenthesis in search URL is erased sometimes

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#12690]
On Sourcegraph version: 3.18 and master

A URL containing `patternType=regexp` for a query like [`repo:(sourcegraph)`](https://sourcegraph.com/search?q=repo:%28sourcegraph%29&patternType=regexp) works as expected.

When The URL does not contain `patterntype=XXX`, a trailing parenthesis in the URL is erased. Here is an example of a URL containing the trailing `)` (encoded as `%29`), but when the value is populated in the search bar, the trailing `)` briefly appears and is then erased:

https://sourcegraph.com/search?q=repo:%28sourcegraph%29

This seems almost certainly related to https://github.com/sourcegraph/sourcegraph/issues/12506

Customer reported working previously, but broken as of 3.18.

**Comment by rvantonder** [comment]
Introduced by #12690. I didn't dig into why that change causes the query to be transformed (and strangely, it doesn't happen when patterntype=xxx is specified). @lguychard please take a look 🙏

**Comment by attfarhan** [comment]
[`followedBy` identifies whitespace or a closing paren as a delimiter](https://github.com/sourcegraph/sourcegraph/pull/11688/files#diff-a3aab87936ca3f27111203014e861b46R308), so all closing parens are actually parsed out. I think we'd need to check if there's whitespace after the closingParen when identifying it as a delimimetr.

**Comment by attfarhan** [comment]
Or, it actually may be because the closing paren is excluded from literal values in the parser: https://github.com/sourcegraph/sourcegraph/pull/11688/files#diff-a3aab87936ca3f27111203014e861b46R227. I have a PR open to fix this https://github.com/sourcegraph/sourcegraph/pull/12696.
