### ISSUE TITLE
Improve sign in/out UX

### ISSUE THREAD

**Issue by christinaforney** [sourcegraph/sourcegraph#12695]
The sign in page should align with the new design consistency work we've been doing around headers and information architecture. There are some confusing moments with the different sign in options, and the UI could be significantly improved. 

Additionally there are a few known issues:

- And the sign in page's nav bar: https://github.com/sourcegraph/sourcegraph/issues/12547
- The sign out page only has a dark theme: https://github.com/sourcegraph/sourcegraph/issues/9810
- Once you sign out, the user flow makes it difficult to sign back in.

Each instance will have different options for signing in depending on what is configured by the Sourcegraph admin. Additionally, Sourcegraph Cloud offers running searches without authentication, but this is not an option for Server deployments.

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by quinnkeast** [comment]
This is ready to move forward.

- [RFC 213: Improve Sign in / Sign out UX](https://docs.google.com/document/d/1HoGEL9tgi92ru2Gel681dNEfhM0zcqFIFcZauQQwdD4/edit#heading=h.trqab8y0kufp)
- [Annotated Figma reference](https://www.figma.com/file/L5ZdNBGAnHQQUGGmp6tdQS/12695-%E2%80%93-Sign-in-Out-UX-Review?node-id=17%3A1471)

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
