### ISSUE TITLE
Search for repos with multiple file conditions

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#127]
#### Describe the feature request.
A user has requested the ability to do a search for the following: "Find me repos that have file 'baz', which contain 'foo', and also contain file 'bar'." 

#### Describe alternatives you've considered.
`file:baz foo` works for "find me repos that have a file 'baz' with 'foo'", but doesn't cover the "also contains file 'bar'" clause.

#### Additional context
Source: https://stackoverflow.com/questions/51940465/more-advanced-search-with-sourcegraph

Post-fix TODO:
- [ ] Update the answer at https://stackoverflow.com/questions/51940465/more-advanced-search-with-sourcegraph

**Comment by schultz9999** [comment]
Or `exists:$FILE`

**Comment by keegancsmith** [comment]
> Find me repos that have file 'baz', which contain 'foo', and also contain file 'bar'."

@beyang this would be covered. The query should be

```
(type:repo file:baz foo) (type:repo file:bar)
```

I'll add this query to my list of requirements to ensure it works.

**Comment by albertocavalcante** [comment]
@beyang @keegancsmith 

It's not clear to me whether it's supported or not.
In case it is, do you have a working query search sample you can share? 

Thanks

**Comment by keegancsmith** [comment]
@albertocavalcante here is an example search [`select:repo (file:dockerfile AND file:package.json)`](https://sourcegraph.com/search?q=context:global+select:repo+%28file:dockerfile+AND+file:package.json%29&patternType=standard)

**Comment by jgodi** [comment]
@keegancsmith That works, but can it do something like `(file:package.json "react") AND (file:appconfig.js)`?

Basically, I am looking to search for repositories with two files and check for something within the `package.json`. Is that possible?

**Comment by keegancsmith** [comment]
@jgodi indeed it seems we have some limitations here in how we translate a query into a query plan. I know our backend implementation would support what you are trying to express, but I can't convince our frontend to do it. @camdencheek @stefanhengl Do you know how to express this / what we can do to improve the situation here?

**Comment by camdencheek** [comment]
Hey @jgodi!

You can accomplish what you're looking for with a query like `repo:has.file(path:package.json content:react) file:appconfig.js`. 

The reason your query didn't work is that query terms are `AND`-ed together by default, so `(file:package.json "react") AND (file:appconfig.js)` is interpreted as `file:package.json AND file:appconfig.js AND react`, which only matches files with both `package.json` and `appconfig.js` in the path.

**Comment by jgodi** [comment]
Awesome, thank you for the additional context.
