### ISSUE TITLE
RFC 199: Deploy new indexer service

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#12709]
Deploy the new indexer service introduced in https://github.com/sourcegraph/sourcegraph/issues/12707 onto a compute node so that it can interface with the Cloud instance.

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
