### ISSUE TITLE
RFC 199: Replace docker commands with firecracker commands

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#12708]
Modify the new indexer service introduced in https://github.com/sourcegraph/sourcegraph/issues/12707 to run code within VMs via weaveworks ignite instead of docker, as described in [RFC 199: User code execution in the auto-indexer](https://docs.google.com/document/d/1rCduWqaLAbMu2s43RwJTBbRlhL6qS3oqq4iawiGdoVE).

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
