### ISSUE TITLE
UI Tooltips for asymmetric precision of hover and definition results

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#12706]
Fill out tooltip text for the following conditions:

https://github.com/sourcegraph/code-intel-extensions/blob/master/shared/providers.ts#L328
https://github.com/sourcegraph/code-intel-extensions/blob/master/shared/providers.ts#L338

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
