### ISSUE TITLE
Update ExternalServicesStore.List to allow filtering by user

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#12704]
..., and site admins are able to list all.

Refs:
- https://sourcegraph.com/github.com/sourcegraph/sourcegraph@5d73f94a7ad9c8c5a5d30954f737e9dde5c2a8b5/-/blob/internal/db/external_services.go#L405

Part of #12699.

**Comment by ryanslade** [comment]
Are you going to add pagination as part of this?

**Comment by unknwon** [comment]
@ryanslade: No, that would be another issue (see tracking issue down the list of same section).
