### ISSUE TITLE
Should not show basic code intel actions on something that is obviously a comment

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#1271]
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:** Mac, Chrome

#### Steps to reproduce:

1. Visit https://sourcegraph.com/github.com/trifacta/sequelize/-/blob/lib/data-types.js#L734:42, hover on `attributes` in the comment
2. Notice that go to def appears and takes you to a var named `attributes`

#### Expected behavior:

The basic code intel extension should recognize that this is a comment, and not show the hover

#### Actual behavior:

![dec-06-2018 12-23-13](https://user-images.githubusercontent.com/5589410/49614581-944bb900-f95f-11e8-8f85-494b96a683a6.gif)

**Comment by sqs** [comment]
This behavior is useful in some cases when the comment refers to a token, like `// Calls myFunction to...`. So I don't want to completely disable basic-code-intel on comments. But it could use much stricter heuristics.

**Comment by chrismwendt** [comment]
@dadlerj Your GIF shows perhaps the most appropriate time to show code intelligence in hovers: when hovering over a token enclosed in backticks. Are there any cases where you'd like to get code intelligence in comments?

Some heuristics that come to mind are: backticks, quotes `"foo"`, and parentheses trailing a token `foo()`.

**Comment by chrismwendt** [comment]
I added some regex heuristics to detect code in comments. It's stricter than it was before.

https://github.com/sourcegraph/sourcegraph-basic-code-intel/blob/8d5ed5d56823fec7724185e9215adaddcdabe776/package/src/handler.ts#L144-L147

```TypeScript
            isComment(line) &&
            !new RegExp(`('|"|\`)${searchToken}('|"|\`)`).test(line) &&
            !new RegExp(`${searchToken}\\(`).test(line) &&
            !new RegExp(`\\.${searchToken}`).test(line),
```

The fact that the "Find references" button shows up regardless of the underlying token is a limitation that extensions can't get around right now, and I filed a separate issue for it https://github.com/sourcegraph/sourcegraph/issues/2159

**Comment by dadlerj** [comment]
Thanks! Your solution here seems like a good one, and I don't think we should stress this too much. Let's consider this a test — if we see anyone annoyed by the heuristics you put in place (e.g. if they cause any obscure languages to break?) then it's fine to remove them. 

Someday we can maybe build these regexes into each lang extension as args to basic code intel? (I'm picturing Rijnard's searcher here...)
