### ISSUE TITLE
codeintel: Alert on failure to open database

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#12712]
A customer has recently reported 500 errors due to permissions of certain SQLite files in the bundle manager. This happened due to a strange migration path that has now been documented.

We should add a metric for failure to open a database file and alert on any increase with a proposed resolution.

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
