### ISSUE TITLE
deploy-sourcegraph-dhall: Add CI job to generate diff between master and feature branch

### ISSUE THREAD

**Issue by davejrt** [sourcegraph/sourcegraph#12716]
Create a CI job that runs on commits to diff between the master and feature branch. 

This job should:

- [ ] use dhall to generate the git action itself
- [ ] be a shell script that invokes dhall to generate the diff

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
