### ISSUE TITLE
New external_service_repos table

### ISSUE THREAD

**Issue by asdine** [sourcegraph/sourcegraph#12711]
Create the `external_service_repos` table and migrate external_service sources column data to that table. Update stores to read sources data from that new table.

Part of #12699

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
