### ISSUE TITLE
add structural search showcase page

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#12767]
I'll add a search page dedicated to some structural searches that point out the contexts it is useful for.

**Comment by poojaj-tech** [comment]
@rvantonder i'm curious if this is the same as a repogroup on the Cloud homepage & if you think this would be a good resource to highlight in a structural search Tour-- for both Cloud & Enterprise Server users?

**Comment by rvantonder** [comment]
Blog post showcases part of the intent here using the multiline editor. It'd be nice to have a feature page that directs to queries like "Code checks for Go". This needs more planning, so I'm closing this issue until we can revisit that.
