### ISSUE TITLE
campaigns: allow users to specify the author details used when creating commits

### ISSUE THREAD

**Issue by LawnGnome** [sourcegraph/sourcegraph#12769]
Right now, we [hardcode the author name and e-mail](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/campaigns/reconciler.go#L298:18) used when creating campaign commits, but it would be better if those fields were customisable.

Initial thought: we could add optional fields to the `changesetTemplate.commit` object in the campaign spec that would allow overriding the defaults.

**Comment by chrispine** [comment]
[Relevant RFC](https://docs.google.com/document/d/1kDkIFQK9hiezEJrG5TfoGvsBKFKF6B6eUcKejYoX2XI/edit#)

**Comment by chrispine** [comment]
Fixed in https://github.com/sourcegraph/sourcegraph/pull/13574
