### ISSUE TITLE
redis-cache segfault in single server dogfood instance

### ISSUE THREAD

**Issue by uwedeportivo** [sourcegraph/sourcegraph#12772]
see https://github.com/sourcegraph/infrastructure/pull/2053

we experienced it today with sourcegraph.sgdev.org.

switching back to 3.18 fixes it.

things i tried:

- wiping /var/opt/sourcegraph/redis-cache (the data dir). that made it come up for a bit but ended up in the same segfault
- putting in a dummy endpoint and sh-ing into the container and launching redis-server redis-cache.conf. that works but the caveat here is that it didn't get exposed to traffic
- increased logging to debug level in the conf template https://github.com/sourcegraph/sourcegraph/blob/master/cmd/server/shared/assets/redis-cache.conf.tmpl#L16  and took out the tail -1 https://github.com/sourcegraph/sourcegraph/blob/master/cmd/server/shared/redis.go#L94
 but logging didn't reveal anything other than it passes beyong initialization and conf reading
- since https://pkgs.alpinelinux.org/packages?name=redis&branch=v3.10 recommends 5.0.5, i downgraded 5.0.9 to 5.0.5 with no effect, still segfaults
- @ggilmore set up  dogfood-redis-test cluster in sourcegraph-aux but couldn't reproduce it there
- @davejrt used his minikube vm and couldn't reproduce it there
- we all tried locally and it came up, no segfault
- read through https://github.com/sourcegraph/sourcegraph/issues/651
- there are core dumps in /var/opt/sourcegraph/redis-cache-backup. i pointed gdb to one core dump and the function name i got is

```
/* Returns an array of robj pointers, and populates *argc with the number
 * of items, by parsing the format specifier "fmt" as described for
 * the RM_Call(), RM_Replicate() and other module APIs.
 *
 * The integer pointed by 'flags' is populated with flags according
 * to special modifiers in "fmt". For now only one exists:
 *
 *     "!" -> REDISMODULE_ARGV_REPLICATE
 *     "A" -> REDISMODULE_ARGV_NO_AOF
 *     "R" -> REDISMODULE_ARGV_NO_REPLICAS
 *
 * On error (format specifier error) NULL is returned and nothing is
 * allocated. On success the argument vector is returned. */
robj **moduleCreateArgvFromUserFormat(const char *cmdname, const char *fmt, int *argcp, int *flags, va_list ap) {
    int argc = 0, argv_size, j;
    robj **argv = NULL;
    /* As a first guess to avoid useless reallocations, size argv to
     * hold one argument for each char specifier in 'fmt'. */
    argv_size = strlen(fmt)+1; /* +1 because of the command name. */
    argv = zrealloc(argv,sizeof(robj*)*argv_size);
    /* Build the arguments vector based on the format specifier. */
    argv[0] = createStringObject(cmdname,strlen(cmdname));
    argc++;
```

as far as i can tell it segfaults somewhere around createStringObject (i don't have debug symbols in the core dump so it's all disassembler). 

to reproduce just change back to the insiders image mentioned in https://github.com/sourcegraph/infrastructure/pull/2053

there's also a couple of uwe-dev-insiders-1,2,3,4 images with mods mentioned above. uwe-dev-insiders-4 has gdb in it

**Comment by uwedeportivo** [comment]
@tsenart  @keegancsmith if you have any ideas, any help appreciated

**Comment by tsenart** [comment]
I checked where `moduleCreateArgvFromUserFormat ` is called in the Redis source code, and out of the three places, I think this is the code path that is triggering the segfault: https://sourcegraph.com/github.com/redis/redis@24c539251f368fb597b660de179a10b2d1370ecb/-/blob/src/module.c?subtree=true#L4108

Why? Because of changes introduced in https://github.com/sourcegraph/sourcegraph/pull/8114 , we started issuing `BGREWRITEAOF` commands on Sourcegraph frontend startup so that the AOF file wouldn't grow out of bounds due to frequent container restarts, and thus, then take a long time to be read on startup.

So I'm pretty sure it's related to that.

**Comment by tsenart** [comment]
I've been debugging this locally after having copied with the redis-cache data directory to my local computer (with kubectl cp, after having created an archive of it in the container's data directory) and having mounted it in the right place (~/.sourcegraph). I can reproduce the segfault locally with:

```
docker run --publish 7080:7080 --publish 127.0.0.1:3370:3370 --rm --volume ~/.sourcegraph/config:/etc/sourcegraph --volume ~/.sourcegraph/data:/var/opt/sourcegraph sourcegraph/server:insiders
```

However, when I change the entrypoint to a bash shell and run `redis-server /etc/sourcegraph/redis-cache.conf` by hand, it doesn't segfault, so there's something else going on. Also, when issue a manual `BGREWRITEAOF` command with `redis-cli` it doesn't segfault.

**Comment by tsenart** [comment]
You know what, this segfault may be a red herring. I managed to reproduce it consistently by modifying the server binary to not start redis-cache, so that I'd start it manually alongside everything else that server starts, and nothing segfaults that way, but, it does, when I press CTRL+C. So this may mean that another process is actually failing and making everything else terminate, it's only that redis-cache isn't terminating gracefully for some reason.

**Comment by tsenart** [comment]
But that wouldn't explain why redis-cache is the first process to terminate in the logs. I'm stuck and don't have more time to put into this right now.

**Comment by uwedeportivo** [comment]
@tsenart thank you so much for looking into this (i feel bad actually, i only asked for ideas and you did so much more). i should have listened to @slimsag in one of the slack comments. i feel like this is goreman/procfile weirdness combined with OOM by some of the other subprocesses. by switching the whole server image to 3.18 where it doesn't crash, we switched out all the candidates. maybe one of the others increased in memory consumption. my main suspect is `symbols`. this is why i'm not the biggest fan of single-server :-)

**Comment by tsenart** [comment]
@uwedeportivo: I couldn't let this go, and tracked down a way to reproduce the segfault via a specific redis command that I traced is being sent to redis (with tcpdump). If you issue a `GET "v2:http:http://127.0.0.1:3180/orgs/sourcegraph-testing/repos?sort=created&page=1&per_page=100"` command, it makes the redis-server crash (tested locally with the copied redis-cache data directory). I have no idea why. Maybe that blob is too big and redis crashes?

**Comment by tsenart** [comment]
Getting other keys doesn't really crash the process, so far only this one has that effect. Maybe a bug in Redis?

**Comment by tsenart** [comment]
[redis-crash-report.zip](https://github.com/sourcegraph/sourcegraph/files/5035687/redis.zip)

**Comment by keegancsmith** [comment]
This problem also tickled me. I took a quick look after what Tomas found. I remember the on-disk formats for appendonly.aof was quite simple, and I hoped the same was true for RDB. So I looked at a hexdump in both files around the bad key. (in redis-cache-backup)

From reading [rdbSaveRawString](https://sourcegraph.com/github.com/redis/redis@5.0.5/-/blob/src/rdb.c?subtree=true#L405:9) strings are just encoded as len data. It has some heuristics, but it looks like it does the verbatim encoding since we can read the string. [rdbSaveLen](https://sourcegraph.com/github.com/redis/redis@5.0.5/-/blob/src/rdb.c?subtree=true#L140:5) is quite complicated, so we need to guess where the length starts but we can reverse engineer. The string has length 85 so it seems it will be encoded into `[2]byte` (2 bits for int type, 14 bits for length). Quoting redis src:

> 01|XXXXXX XXXXXXXX => 01, the len is 14 byes, 6 bits + 8 bits of next byte

So this little bit of python can decode lengths:

```python
f = lambda a, b: ((a&0x3F)<<8)|b
# >>> f(0x40, 0x55)
# 85
```

So the "@U" is the length of the string! It looks like the value is appearing after that, but I have just hit my wall and will go to sleep now. I'll leave checking out the length of the value (to see if we are doing overflows) as an exercise for the reader.

The key in dump.rdb

    # strings -t d dump.rdb    | grep orgs/sourcegraph 
      83514 @Uv2:http:http://127.0.0.1:3180/orgs/sourcegraph/repos?sort=created&page=3&per_page=100
    2572037 @Uv2:http:http://127.0.0.1:3180/orgs/sourcegraph/repos?sort=created&page=2&per_page=100
    2797503 @Uv2:http:http://127.0.0.1:3180/orgs/sourcegraph/repos?sort=created&page=5&per_page=100
    3406123 @Uv2:http:http://127.0.0.1:3180/orgs/sourcegraph/repos?sort=created&page=4&per_page=100
    4275305 @Uv2:http:http://127.0.0.1:3180/orgs/sourcegraph/repos?sort=created&page=1&per_page=100
    
    # hexdump -s 4275290 -n 200 -C dump.rdb 
    00413c5a  c6 0c ad cb 73 01 00 00  f8 80 00 05 02 57 00 40  |....s........W.@|
    00413c6a  55 76 32 3a 68 74 74 70  3a 68 74 74 70 3a 2f 2f  |Uv2:http:http://|
    00413c7a  31 32 37 2e 30 2e 30 2e  31 3a 33 31 38 30 2f 6f  |127.0.0.1:3180/o|
    00413c8a  72 67 73 2f 73 6f 75 72  63 65 67 72 61 70 68 2f  |rgs/sourcegraph/|
    00413c9a  72 65 70 6f 73 3f 73 6f  72 74 3d 63 72 65 61 74  |repos?sort=creat|
    00413caa  65 64 26 70 61 67 65 3d  31 26 70 65 72 5f 70 61  |ed&page=1&per_pa|
    00413cba  67 65 3d 31 30 30 c3 80  00 01 4c 56 80 00 08 59  |ge=100....LV...Y|
    00413cca  f5 1f 48 54 54 50 2f 31  2e 31 20 32 30 30 20 4f  |..HTTP/1.1 200 O|
    00413cda  4b 0d 0a 54 72 61 6e 73  66 65 72 2d 45 6e 63 6f  |K..Transfer-Enco|
    00413cea  64 69 1f 6e 67 3a 20 63  68 75 6e 6b 65 64 0d 0a  |di.ng: chunked..|
    00413cfa  41 63 63 65 73 73 2d 43  6f 6e 74 72 6f 6c 2d 41  |Access-Control-A|
    00413d0a  6c 6c 6f 0a 77 2d 4f 72  69 67 69 6e 3a 20 2a e0  |llo.w-Origin: *.|
    00413d1a  08 1f 19 45 78 70 6f 73                           |...Expos|
    00413d22

The key in appendonly.aof

    # strings -t d appendonly.aof     | grep orgs/sourcegraph 
     151149 @Uv2:http:http://127.0.0.1:3180/orgs/sourcegraph/repos?sort=created&page=5&per_page=100
     745433 @Uv2:http:http://127.0.0.1:3180/orgs/sourcegraph/repos?sort=created&page=4&per_page=100
     982409 @Uv2:http:http://127.0.0.1:3180/orgs/sourcegraph/repos?sort=created&page=2&per_page=100
    2756815 @Uv2:http:http://127.0.0.1:3180/orgs/sourcegraph/repos?sort=created&page=1&per_page=100
    3184082 @Uv2:http:http://127.0.0.1:3180/orgs/sourcegraph/repos?sort=created&page=3&per_page=100
    
    # hexdump -s 2756790 -n 200 -C appendonly.aof 
    002a10b6  73 22 3a 31 30 36 7d 5d  7d fc c6 0c ad cb 73 01  |s":106}]}.....s.|
    002a10c6  00 00 f8 80 00 05 02 59  00 40 55 76 32 3a 68 74  |.......Y.@Uv2:ht|
    002a10d6  74 70 3a 68 74 74 70 3a  2f 2f 31 32 37 2e 30 2e  |tp:http://127.0.|
    002a10e6  30 2e 31 3a 33 31 38 30  2f 6f 72 67 73 2f 73 6f  |0.1:3180/orgs/so|
    002a10f6  75 72 63 65 67 72 61 70  68 2f 72 65 70 6f 73 3f  |urcegraph/repos?|
    002a1106  73 6f 72 74 3d 63 72 65  61 74 65 64 26 70 61 67  |sort=created&pag|
    002a1116  65 3d 31 26 70 65 72 5f  70 61 67 65 3d 31 30 30  |e=1&per_page=100|
    002a1126  c3 80 00 01 4c 56 80 00  08 59 f5 1f 48 54 54 50  |....LV...Y..HTTP|
    002a1136  2f 31 2e 31 20 32 30 30  20 4f 4b 0d 0a 54 72 61  |/1.1 200 OK..Tra|
    002a1146  6e 73 66 65 72 2d 45 6e  63 6f 64 69 1f 6e 67 3a  |nsfer-Encodi.ng:|
    002a1156  20 63 68 75 6e 6b 65 64  0d 0a 41 63 63 65 73 73  | chunked..Access|
    002a1166  2d 43 6f 6e 74 72 6f 6c  2d 41 6c 6c 6f 0a 77 2d  |-Control-Allo.w-|
    002a1176  4f 72 69 67 69 6e 3a 20                           |Origin: |
    002a117e

**Comment by tsenart** [comment]
@uwedeportivo: Do you plan to submit a bug report to Redis with all of the above?

**Comment by uwedeportivo** [comment]
@tsenart yes, doing it this morning

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
i will add a link to a writeup about docker images to this issue, but closing this because it's fixed and a release blocker
