### ISSUE TITLE
xref count badge

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1277]
The badge was set to always report `?`. We should revive it. @chrismwendt 	to plan out how we do this.

**Comment by bradleyjkemp** [comment]
This has caused broken badges on many, many repositories. High visibility examples:
* https://github.com/labstack/echo
* https://github.com/gorilla/mux
* https://github.com/gin-gonic/gin
etc...

**Comment by sqs** [comment]
Yes, sorry. We will bring this back very soon.

**Comment by chrismwendt** [comment]
Two ideas:

1. Approximate the ref count with a search for the import path in Go files across a subset of repositories on Sourcegraph.com (almost certainly wildly inaccurate)
2. Call out to the godoc.org importers API

Any other ideas? I'll start working on 2 soon.

**Comment by bradleyjkemp** [comment]
Note that option 2 is also an underapproximation as it does not include imports from test files (and so testing libraries show up as near zero importers).

**Comment by sqs** [comment]
@chrismwendt For (2), it might make sense to build up our own dependency-dependent index for Go code (maybe even using gddo, but lifting the limitation that @bradleyjkemp described). It just uses Redis to store the data and can be seeded fairly quickly. (Or it would not be hard to write this from scratch, if gddo's existing code is not suited to it.)

**Comment by chrismwendt** [comment]
I have a PR for option (2) above https://github.com/sourcegraph/sourcegraph/pull/1377
