### ISSUE TITLE
Add comment parsing to lsif-go

### ISSUE THREAD

**Issue by stefanhengl** [sourcegraph/sourcegraph#12786]
We should support code-intel for references to symbols within go-comments.

**Comment by efritz** [comment]
Is there a standard for this in general? It should be fairly easy to say "this word matches the case of a package-level variable". Is there similarly a way to specify fields of structs or exports from another package? Javadoc, ruby, and other spec types have other conventions and I'm not sure/aware of what Go uses in this regard (`parent#child`, `parent.child`, etc).

**Comment by macraig** [comment]
@stefanhengl is this something you are still interested in having?

**Comment by scalabilitysolved** [comment]
@macraig ping

**Comment by macraig** [comment]
Closing for now, will reopen if needed
