### ISSUE TITLE
update settings version mismatch: last ID is 6321 (mutation wanted 4425)

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1278]
This is an annoying bug/limitation where if you make a settings change in one browser tab, it isn't reflected in other browser tabs, so settings changes in those fail with this error:

```
update settings version mismatch: last ID is 6321 (mutation wanted 4425)
```

One possible fix for this is to communicate with all other browser tabs (via the StorageEvent, `window.addEventListener('storage', ...)`) to tell them to reload user settings.

Repro:

1. Open 2 browser tabs to a Sourcegraph page, such as https://sourcegraph.com/github.com/ntilwalli/combineLatestStartUndefined@master/-/blob/index.js#L26:10&tab=references
2. In both browser tabs, click **Hide fuzzy references** (or any other action that calls updateConfiguration)

One of the tabs will have this error.

**Comment by slimsag** [comment]
Periodic reloading of contents from server makes more sense to me, as that
would account for setting changes by other users (in the case of org/global
settings). This could be as simple as refreshing every 10s.

**Comment by keegancsmith** [comment]
Until there is a tab reload, can't we just use the stale settings? If I have 15 github tabs open, does that mean we do a refresh every 10s 15 times?

**Comment by slimsag** [comment]
Only if you have 15 tabs on the settings edit page (Monaco editor), is that
what you meant?

**Comment by slimsag** [comment]
Whoops, I see, yeah you are right. I read this in my email before Quinn added the additional context to this issue, so I thought this was occurring on settings edit pages -- not generally. I agree my suggestion was wrong given this new info.
