### ISSUE TITLE
reduce JS/CSS bundle size

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1279]
Our JS/CSS bundle is large. It takes a long time to download. There must be opportunities to reduce this.

For example: https://slack-files.com/T02FSM7DL-FEMQWS90U-5c035bdff2 (video of @keegancsmith  loading the references page on south african coffee shop wifi)

**Comment by keegancsmith** [comment]
Note: I downloaded this without clearing the cache/etc. I had opened the exact same link, created a new window and opened the same link again for that video.

**Comment by felixfbecker** [comment]
Out JS bundle size is 519KB, CSS is 94KB.

**Comment by felixfbecker** [comment]
@keegancsmith could you take a look at your network tab and see if your slow load times are caused by download time or by latency?

**Comment by ijsnow** [comment]
Discussed with Quinn and Nick and this isn't a priority right now.
