### ISSUE TITLE
Not redirected to previous page after sign-in

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#12793]
Reported by https://app.hubspot.com/contacts/2762526/company/1686989427

A customer reported that after returning to Sourcegraph, taking some action (e.g. a search), and getting redirected to their SSO provider to sign in, they aren't returned back to that original search after completing the sign-in. 

Not an urgent issue, but a small annoyance. And they are uncertain as to whether it's due to a limitation on their side.

I haven't tried to reproduce yet.

**Comment by tsenart** [comment]
Fixed by #15439
