### ISSUE TITLE
Search recommendations to add quotes is misleading.

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#12802]
Just watched this happen during a demo with https://app.hubspot.com/contacts/2762526/company/2428850551. 

Repro:

1. https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/kubernetes/kubernetes%24+.+type:diff+timeout:1s&patternType=literal

2. Click on the suggested search
3. Note that quotes get added around the search term (`.` -> `"."`)

**Comment by rvantonder** [comment]
assigning to myself to investigate

**Comment by rvantonder** [comment]
@dadlerj this is a problem with the repo fetching/caching :'( If you go try either of the original search, or the one with quotes, it won't time out and show results. If it does time out, wait like, 1 minute, and search again, and you'll see the expected results.  We have existing issues related to this but not sure how intertwined they are with diff search. Will dig them up and cross ref.

**Comment by rvantonder** [comment]
@keegancsmith do we run diff searches on gitserver? I had a brief look at the code but not sure. Wondering whether there's fetching/eviction behavior for repos on the service that runs diff/commit searches that might affect this.

**Comment by dadlerj** [comment]
@rvantonder sorry to clarify the issue, the timeout is not the problem. Well, it is the problem on their instance, but theirs is severely underpowered/underprovisioned (which is a separate conversation). 

The timeouts are painful, but a separate thread. Quotes being added to the search by the recommendation (and thus changing the meaning of the search itself) was the only issue I wanted to raise here!

**Comment by rvantonder** [comment]
Got it! Thanks for clarifying. That's probably a relatively quick fix (let's just not show things that aren't helpful in this context).

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by rvantonder** [comment]
Rleated to #10793

**Comment by rvantonder** [comment]
Click the suggestion no longer quote the pattern. I think this got fixed when the new parser was activated.
