### ISSUE TITLE
Instead of loader, empty hover is shown

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#1281]
It used to be that a loader was shown while the hover request was still pending. Since recently, only an empty hover is shown, which is very ugly and a regression in terms of letting the user know what's going on.

![image](https://user-images.githubusercontent.com/10532611/49647545-27015c00-fa23-11e8-872e-6bc265e969b1.png)

**Comment by sqs** [comment]
@felixfbecker and @lguychard you two can pair on this next week

**Comment by nicksnyder** [comment]
Who owns this?

**Comment by sqs** [comment]
After more usage myself and discussion with @lguychard, I don't consider this a problem, so I am closing it to reflect the fact that we do not plan to prioritize this and consider it an issue. We can have discussion on the closed issue if anyone disagrees and wants to argue for reopening it.
