### ISSUE TITLE
Unable to enqueue changeset to be reconciled while it's being reconciled

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#12827]
### Status quo

In order to enqueue a `changeset` to be picked up by the reconciler, we set its `reconciler_state` column to `queued`.

The reconciler then dequeues the changeset by setting the `reconciler_state` to `processing`:

https://github.com/sourcegraph/sourcegraph/blob/74ad60c5b67a800804279e036f8c849e14fc02c9/internal/workerutil/dbworker/store/store.go#L298-L315

Once it's done, it sets the `state` to `completed` or `errored`.

### Problem

We want to move the closing of changesets into the background (https://github.com/sourcegraph/sourcegraph/issues/12644) by setting a "please close this" boolean on the `changeset` and enqueuing the changeset so that the reconciler picks it up and closes it.

We also want to allow this _while a `changeset` is being processed by the reconciler_, because the reconciler could — in the future — always be processing a changeset and that shouldn't stop the user from marking a changeset as "to be closed". See https://github.com/sourcegraph/sourcegraph/pull/12782#issue-463915652 for more context.

*But here is the problem*: if we enqueue a changeset while it's being processed by setting `reconciler_state = 'queued'` then that value will simply be overwritten by the reconciler once it's done with the current processing.

In other words: we can't enqueue a changeset to be processed again while it's being processed.

That's due to the architecture of the underlying `dbworker/store`, which assumes that every job is a one-off job that ends in a terminal state and is not re-enqueued again.

### Possible Solution 1

We split the `reconciler_state` up into two fields:

- `enqueued: bool`
- `processing_state: string`

In order to enqueue a changeset, we set `enqueued = TRUE`.

We then need to change the `dbworker/store` so that the `selectCandidateQuery` allows us to set these fields, like this (see the `selectCandidateQuery` above):

```sql

WITH candidate AS (
  SELECT {id} FROM %s
  WHERE
    -- This is new
    ({state} = 'queued' OR (enqueued IS TRUE)) AND
    ({process_after} IS NULL OR {process_after} <= NOW())
    %s
  ORDER BY %s
  FOR UPDATE SKIP LOCKED
  LIMIT 1
)
UPDATE %s
SET
  -- This is new
  enqueued = FALSE,
  {state} = 'processing',
  {started_at} = NOW()
WHERE {id} IN (SELECT {id} FROM candidate)
RETURNING {id}
```

We could then compute the `Changeset.ReconcilerState()` by looking at both fields.

And we could always set the `enqueued`, even while a changeset is being processed, because the field acts like a dirty bit that's only cleared when dequeued. If we set it to `true` again, while it's being processed, the reconciler will pick it up again after it's done processing.

### Possible Solution 2

We could switch away from using the `changesets` table as re-usable jobs that are re-executed again and again and instead create a new `reconciler_job` whenever we want the reconciler to look at the changeset.

That would require another table, of course, and that we need to fetch the jobs whenever we want to check the status of a changeset. We could make that easier with a database view, though, in which we always join the changesets against the `reconciler_jobs`.

But then we'd have the problem that we create a new job while the old one is being processed and both would try to modify the changeset, so we'd need to lock the changeset.

---

I'm leaning towards solution 1.

**Comment by mrnugget** [comment]
Another note: we also need to make sure that we don't overwrite  the `closing`, `unsynced`, `current_spec_id` and `previous_spec_id` fields from _inside the reconciler_.

**Comment by mrnugget** [comment]
We also need to make sure that the syncer doesn't overwrite all the worker/reconciler-related fields.

In other words, the following fields on `changesets` table should be "opt in" when using `UpdateChangesets`:

```
 reconciler_state
 failure_message
 started_at
 finished_at
 process_after
 num_resets
 unsynced
 closing
 enqueued
```

**Comment by efritz** [comment]
A couple thoughts:

- Looks like the reconciler is conflating two concepts that should probably be kept as two. By having only one record type with multiple attempts you can't easily keep track of historic attempts (not sure if this is important or not, but would be in many non-campaigns use cases). It seems like it would be better to have a one-to-many relation between changesets and changeset_jobs. If you keep the "dirty" bit on the changeset (which I think is a cleaner idea), then you can have a single goroutine (protected by an advisory lock) that will scan all of the changeset jobs with a dirty bit and enqueue a new job for it if there isn't one already queued. This is exactly how the precise code intel indexer works by scheduling index jobs for a repo and commit pair.

Additionally, say we want to have something in the future like a job_logs or a job_stats table for better introspection to historic job invocations. If we have only one reusable row we lose all of that data (which is valuable). If we have one row per action, we can keep it and prune it as necessary.

The package was never meant to make spaghetti, but the first solution seems like it's heading that way a bit.

**Comment by efritz** [comment]
> But then we'd have the problem that we create a new job while the old one is being processed and both would try to modify the changeset, so we'd need to lock the changeset.

Don't lock the changeset, just put a lock around the routine that enqueues dirty jobs. If this is the _only_ thing that enqueues jobs then you have no issues with concurrent enqueues.

https://sourcegraph.com/github.com/sourcegraph/sourcegraph@99dfc3f338c2f8d59711d82132e83fb8a00da37d/-/blob/enterprise/internal/codeintel/commits/updater.go#L69

**Comment by mrnugget** [comment]
(Just replicating some of my Slack comments here for the record, before we jump on our call)

> It seems like it would be better to have a one-to-many relation between changesets and changeset_jobs.

I do feel the friction in the API of the `dbworker` package by hacking the dirty-bit stuff into it, but I feel (!) that having this relationship between `changesets` and `changeset_jobs` wouldn't necessarily be simpler. Especially since we don't need a lot of the features you can get from a single-record-with-jobs:

- We don't need historical data
- We don't need `started_at`, `finished_at`, `num_resets`, etc.

All we need is something that re-processes changesets when something (user updated foreign-key references or flipped a boolean) has changed.

> If this is the _only_ thing that enqueues jobs then you have no issues with concurrent enqueues.

We do have two routines in the frontend that can enqueue something. Putting a lock around that is hard, since there can be multiple instances of `frontend`.

**Comment by efritz** [comment]
@mrnugget and I had a hack session where we (re-)discovered some things.

Most importantly, you can't modify a record of the workerutil package while it's being processed because there is a postgres lock held on it. This actually simplifies a _lot_ of the reconciler code (I'm told) and it seems like there's an alternate approach to being able to "stack" changes on a moving campaign/changeset.

**Comment by mrnugget** [comment]
Just adding some campaigns-related words on top of the previous comment:

- We can't `ApplyCampaign` while `changesets` are being processed. That would block because those changesets are locked.
- We can't `CloseCampaign` while `changesets` are being processed, for the same reason. *And* the "do we have processing changesets?" check is full of race conditions.

That means while the title of this ticket ("Unable to enqueue changeset to be reconciled while it's being reconciled") is technically correct, the original problem description is not: the reconciler does *not* overwrite the `changeset.reconciler_state = "enqueued"` set by `ApplyCampaign`/`CloseCampaign`, because those would block.

We decided that the best behaviour for `ApplyCampaign`/`CloseCampaign` is to do the following:

- Set all _currently enqueued_ changesets to "errored" with `failure_message = "Cancelled because of a new campaign spec is applied ... etc"` (or completed?)
- Wait for all _currently processing_ changesets to finish processing
- Then do `ApplyCampaign`/`CloseCampaign`

Eric typed up some draft-level SQL/Go in https://github.com/sourcegraph/sourcegraph/pull/13546 and I'll finish that PR tomorrow.
