### ISSUE TITLE
Split up ChangesetCountsOverTime integration test

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#12835]
The name suggests it only tests the `changesetCountsOverTime` resolver, but it actually also mocks the codehost, does a full sync and so on. This should be in a separate test.

**Comment by mrnugget** [comment]
Pretty sure this was fixed in https://github.com/sourcegraph/sourcegraph/pull/12813. Closing it. If you think this assessment is wrong, please reopen @eseliger.

**Comment by eseliger** [comment]
I should have linked to the conversation. See here https://github.com/sourcegraph/sourcegraph/pull/12813#discussion_r467015271 for more context. We thought the test is too broad and needs to many mocks for testing just the count logic.
