### ISSUE TITLE
campaigns: large changesets can result in 413 errors

### ISSUE THREAD

**Issue by LawnGnome** [sourcegraph/sourcegraph#12840]
We've addressed this to some extent with #9202, but this is still an issue: creating a large campaign (for example, with lots of noise in vendored packages or lockfiles) can result in 413s.

The work going on in #12333 will (significantly) improve this: each changeset spec will be uploaded individually, which means that we essentially move from the size of the campaign being the issue to the size of the changeset, but this doesn't completely remove the potential for 413s.

In the longer term, we should provide a GraphQL mutation that can accept partial changeset specs, and make `src-cli` smart enough to know when to chunk specs before transmission.

**Comment by chrispine** [comment]
consider combination of gzip, chunked uploads, smaller diffs

**Comment by mrnugget** [comment]
@chrispine Some rough notes and starting points on what needs to be done:

- Use `git diff (-D|--irreversible-delete) ` when creating the diffs for `changesetSpecs` in `src-cli`. ([See where that's done right now](https://sourcegraph.com/search?q=repo:src-cli%24+diff%22%2C+%22--cached%22&patternType=literal), but with Adam's work in `src-cli` it'll be [here](https://github.com/sourcegraph/src-cli/pull/260/files#diff-b24071a94c5639d715fffc30db1456dbR140))
- Make sure the new diff format can be parsed when we ingest it in `sourcegraph/sourcegraph` [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/campaigns/types.go#L1756)
- Make sure the new diff format can be applied and pushed in the reconciler [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/campaigns/reconciler.go#L251:22)
- And now, the trickiest part, is to get [`previewRepositoryComparisonResolver `](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/preview_repository_comparison.go#L13) to work with a diff where the "right side of the diff" is missing. @eseliger can give more pointers here, I assume.
