### ISSUE TITLE
Icon for "Open in editor" extension

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#12843]
For #10093, we need a generic "Open in editor" icon. The icon would show both in the extension gallery and as a button in the extension toolbar in SourceGraph and code hosts like GitHub when viewing files.

We need a generic icon instead of an editor-specific icon because the extension will be customizable: the user can select between a set of built in editors or, if the extension doesn't support their editor, can set a custom one.

**Comment by AlicjaSuska** [comment]
Icon for open-in-editor extensions is ready for review in [Figma](https://www.figma.com/file/vr6vyV5Vs55wq2DocyRZ9m/12843-Icon-for-Open-in-editor-extension-Review?node-id=0%3A1)

<img width="751" alt="Screenshot 2020-08-24 at 08 57 25" src="https://user-images.githubusercontent.com/20326070/91013352-da3f2980-e5e7-11ea-9843-eb5dcbc2f36a.png">

I've created an issue for the general approach regarding extensions for opening in editors [#13270](https://github.com/sourcegraph/sourcegraph/issues/13270). The overall need and function of this icon depend on the outcome of this issue.

**Comment by felixfbecker** [comment]
Done
