### ISSUE TITLE
Campaigns new flow design

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#12885]
Goals:

* Avoid major changes to in-flight designs/architecture 
* Quickly address small UX issues with the existing components
* Improve the layout's visual appeal
* Assess and address the overall flow of creating and editing campaigns

Visual design

- [x] address visual design of components and pages
- [ ] review
- [ ] hallway testing
- [ ] external user testing

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
