### ISSUE TITLE
Documentation for configuring campaigns (scope for tokens)

### ISSUE THREAD

**Issue by poojaj-tech** [sourcegraph/sourcegraph#12888]
Customer feedback
> better documentation on setting up/ configuring campaigns. For example I'd like to know what scope I need for tokens before I try to create/ import them. In secure environments where I don't have ownership of the organization it means that I have to request token form the owner, wait, try, get error, wait try....

Company: https://app.hubspot.com/contacts/2762526/company/2155791964
Customer: https://app.hubspot.com/contacts/2762526/contact/16469101/

**Comment by poojaj-tech** [comment]
(another issue filed by the customer: [#259](https://github.com/sourcegraph/src-cli/issues/259)

**Comment by mrnugget** [comment]
This depends on https://github.com/sourcegraph/sourcegraph/issues/10813
