### ISSUE TITLE
Globbing: don't search fuzzy repos when @commit is present

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#12892]
For something like: `repo:github.com/sourcegraph/sourcegraph@master`, I think it's fair to assume we don't need to fuzzify to `repo:github.com/sourcegraph/sourcegraph**@master`. I noticed some results for multiple repos even when `@commit` was specified, and we probably don't need [this behavior](https://sourcegraph.com/search?q=repo:github.com/sourcegraph/sourcegraph%40master&patternType=literal):

![Screen Shot 2020-08-10 at 2 59 57 PM](https://user-images.githubusercontent.com/888624/89835756-356a1a00-db1a-11ea-8bfd-dd3dd3f096ba.png)

This is minor, but I think it's an easy fix (I think you just add a `$` anchor when `@commit` is present?), so just thought I'd file if @stefanhengl wants to look into it.

**Comment by rvantonder** [comment]
Actually this is probably a bigger usability deal than I thought, because if a specific commit is used then we'll throw an ugly warning about how some repo doesn't contain a commit:

![Screen Shot 2020-08-10 at 3 01 57 PM](https://user-images.githubusercontent.com/888624/89835922-8aa62b80-db1a-11ea-8342-0c7666159a05.png)

**Comment by bobheadxi** [comment]
thought: what if I want to search across all `v2` branches in a set of repositories that use this convention?

**Comment by stefanhengl** [comment]
@bobheadxi If you add wildcards we won't remove them. Taking your example, if you want to search across all v2 branches across many repositories in your org you could do something like this

```
repo:github.com/sourcegraph**@v2
```

which will translate to the regex pattern

```
repo:^github.com/sourcegraph.*?$@v2
```

**Comment by keegancsmith** [comment]
Alternative: If we are in "fuzzy" mode, do an exact search if the string is an exact match on a repo. This would work the same way we handle deciding if we should automatically include archived or not. IE I don't think we should special case this to `@`
