### ISSUE TITLE
Precise code intel API server error during background config update

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#12895]
Reported by https://app.hubspot.com/contacts/2762526/company/768958891

The precise-code-intel-api-server was rescheduled onto a new node by K8s, and started spamming the following logs. The customer does not currently use precise code intelligence at all. 

`2020/08/10 21:24:31 received error during background config update, err: unable to update new configuration: invalid critical configuration (empty string)`

**Comment by dadlerj** [comment]
Discussed at https://sourcegraph.slack.com/archives/CHXHX7XAS/p1597099443342200

**Comment by pecigonzalo** [comment]
We asked the customer to verify if this is a cluster connectivity issue by trying to reach the service from other pods in the cluster running in the same node.

**Comment by slimsag** [comment]
Resolved: https://github.com/sourcegraph/customer/issues/85

**Comment by ianseyer** [comment]
Can we get some public information on what happened here? I am now seeing this issue on 3.22.1
