### ISSUE TITLE
Slow loading of Go external refs

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#129]
@nictuku reported that external refs were slow to load for a specific definition linked from a godoc.org page (i.e., the "Uses" link at https://godoc.org/github.com/dgrijalva/jwt-go#Parser.ParseWithClaims).

Any rarely used function will be slow to fetch xrefs for. The worst case would be the least frequently used function in the most commonly used repository (other than golang/go, which we index specially). We have not optimized this operation much.

@nictuku: If you recall the specific definition that was slow, let us know.

**Comment by nictuku** [comment]
`https://sourcegraph.com/github.com/src-d/go-git/-/blob/options.go#L322:6=&tab=references:external`

Click on LogOptions and External References. It took 40+ seconds to load here. I recorded a video, let me know if that can be helpful.

**Comment by sqs** [comment]
Assigning to @chrismwendt 	to use this as a test case for the new Go external references implementation.

**Comment by christinaforney** [comment]
Hey @nictuku, I just tested your example and everything I tested was snappy for me (but I might not have been looking at the right things). Can you confirm if this is working for you now?
