### ISSUE TITLE
Long load time of Extensions registry page

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#12909]
Extensions registry page load time feels long. Spinner is being shown usually for 2-3 seconds, sometimes longer.

<img width="1536" alt="Screenshot 2020-08-11 at 13 58 59" src="https://user-images.githubusercontent.com/20326070/89895016-63fbf980-dbdb-11ea-93ab-3f1f315212d7.png">

**Comment by AlicjaSuska** [comment]
@tjkandala we've discussed this issue last week. Will it be possible to solve this problem when working on the extensions project?

**Comment by tjkandala** [comment]
Are you noticing this long load time when you navigate from other pages, or when you reload the page. If it's the latter, that's a symptom of the app's general load time/bundle size. Regarding the former, I [made some changes](https://github.com/sourcegraph/sourcegraph/pull/12810) last week that should take about a good chunk off the load time. We were previously creating a URL object for every extension in the registry, which took ~30ms on average for each of them.

**Comment by AlicjaSuska** [comment]
@tjkandala as we've discussed - it was happening on Cloud both when I reload the page and navigate to extensions from other pages (in this case, it took longer). Changes that you've made on your branch solved the problem 🎉

**Comment by AlicjaSuska** [comment]
Connected to: https://github.com/sourcegraph/sourcegraph/issues/11872
