### ISSUE TITLE
Produce a source code zip of Firefox add-on to faciliate compliance review

### ISSUE THREAD

**Issue by marekweb** [sourcegraph/sourcegraph#12918]
The Mozilla add-on team needs access to the source code of our Firefox add-on in order to be able review it for compliance with their policy. We need to submit this source code with every new version of the add-on.

This issue is to track the requirements for this source code.

The source code zip:

- **must** contain the exact snapshot that was used to produce the submitted add-on (XPI file)
- **must** contain all scripts required to reproduce the build (although it can pull/build dependencies with `yarn install` etc)
- **should** reproduce the build exactly, so that a diff of the result shows no difference (before zipping; because after zipping the XPI will actually be non-identical due to file timestamps being included inside the zip metadata).
- **should** only include source code that pertains to the add-on, and not the entirety of `sourcegraph/sourcegraph`. This means the solution is not to simply zip the entire repository.
- **should**, for our convenience, be something that can be done automatically by a script
- **could** if possible, in addition to producing the source code zip, upload it automatically with the submitted XPI.

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
