### ISSUE TITLE
504 Gateway Timeouts when mousing over after the page has loaded for a while

### ISSUE THREAD

**Issue by lawrence-tan** [sourcegraph/sourcegraph#12930]
- **Sourcegraph version:** 3.18.0
- **Platform information:** Firefox 79.0 on macOS 10.15.5

#### Steps to reproduce:

1. Load a source file in Sourcegraph, and mouse over an element to get a code intelligence popup.
2. Move your mouse away to dismiss the popup.
3. Leave the page alone for 5 minutes.
4. Go back to the page and mouse over another element.

#### Expected behavior:
A code intelligence popup appears.
#### Actual behavior:
Nothing happens. Errors show up in the console, and I've attached a screenshot of one set of errors.
<img width="1011" alt="Screen Shot 2020-08-11 at 8 54 50 PM" src="https://user-images.githubusercontent.com/15042336/89963449-a510ff80-dc15-11ea-8919-1d915384a6c4.png">

**Comment by efritz** [comment]
Do you see this behavior consistently? Does it affect one repo over others, or all repos uniformly?

**Comment by lawrence-tan** [comment]
Hi - thanks for the response. This behavior is consistent in our largest C++ repo. I spot-checked a smaller repo (which is mainly Python), and this issue didn't seem to happen.

**Comment by efritz** [comment]
Sorry for the issue. The repo size is good to know. Can you give me some rough indication about the size of your LSIF index (the one that's uploaded to the instance from your CI) so I can see if I can replicate this locally? Do you happen to see any suspicious activity (crash, restart, logs) in either the frontend or the bundle manager pods that service this request?

Feel free to at me (@eric) on the Sourcegraph slack channel if you'd rather transmit log messages or code sizes that way instead.

**Comment by efritz** [comment]
This was caused by websocket timeout values on an nginx proxy in front of the Sourcegraph instance.

```
    # Don't timeout websockets quickly. Default is 60s. This is the timeout
    # between reads/writes, not the full session timeout.
    proxy_send_timeout 1h;
    proxy_read_timeout 1h;
```
