### ISSUE TITLE
frontend: blob load latency

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#12942]
[`blob_load_latency` seems to spike frequently, which sets off a critical-level alert](https://opsg.in/a/i/sourcegraph/fadf2220-62b8-4043-9896-1a5387e55565-1597243379134).

[panel](https://sourcegraph.com/-/debug/grafana/d/frontend/frontend?viewPanel=12&orgId=1&from=now-2d&to=now)

<img width="1756" alt="image" src="https://user-images.githubusercontent.com/23356519/90031104-6ea7b300-dcef-11ea-999a-6478f38ae466.png">

The big one in the middle is some downtime we had recently. This alert was migrated from our custom dot-com alerts - the variant there no longer works due to referencing a nonexistent record, so this alert is pretty much new. Some questions:

* Is this expected behaviour?
* Is this actionable? Should it be a warning instead? Does this panel even need to exist?

The threshold for this was already recently relaxed in https://github.com/sourcegraph/sourcegraph/pull/12936

Assigning to @sourcegraph/search since the alert is currently tagged as owned by search (let me know if this isn't right!)

**Comment by bobheadxi** [comment]
the old alert for reference: https://github.com/sourcegraph/deploy-sourcegraph-dot-com/blob/release/base/prometheus/prometheus.ConfigMap.yaml#L478-L486

**Comment by bobheadxi** [comment]
@sourcegraph/search this alert still comes up frequently - do you want to silence this and follow up in this issue instead? Instructions: https://docs.sourcegraph.com/admin/observability/alert_solutions#frontend-blob-load-latency

**Comment by keegancsmith** [comment]
We have prometheus counters for when this limit is enforced already (via the search alert metrics)

**Comment by bobheadxi** [comment]
Just realized I've mistakenly tagged this on the wrong team 😅 sorry! cc @sourcegraph/cloud 

https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/monitoring/frontend.go#L112-124

**Comment by unknwon** [comment]
Cross posting here:

Can these two be correlated? Because syntect failed and unable to response, somewhere in the backend retried multiple times? “blob” page to my understanding, is viewing a file (with syntax highlighting)

![image](https://user-images.githubusercontent.com/2946214/91642065-e4837c80-ea5a-11ea-9c99-898fb2d1d87c.png)

**Comment by bobheadxi** [comment]
Seems [sometimes correlated](https://sourcegraph.com/-/debug/grafana/explore?orgId=1&left=%5B%22now-2d%22,%22now%22,%22Prometheus%22,%7B%22expr%22:%22alert_count%7Bname%3D~%5C%22blob_load_latency%7Csyntax_highlighting_worker_deaths%5C%22%7D%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D), but the worker deaths is so frequent it is hard to tell

<img width="1697" alt="image" src="https://user-images.githubusercontent.com/23356519/91649678-ee33d100-eaa8-11ea-9204-6bba0a3620a9.png">

Comparison with various other measures of syntect_server problems: https://sourcegraph.com/-/debug/grafana/explore?orgId=1&left=%5B%22now-2d%22,%22now%22,%22Prometheus%22,%7B%22expr%22:%22sum(increase(src_syntax_highlighting_requests%7Bstatus%3D%5C%22hss_worker_timeout%5C%22%7D%5B5m%5D))%22%7D,%7B%22expr%22:%22sum(increase(src_syntax_highlighting_requests%7Bstatus%3D%5C%22panic%5C%22%7D%5B5m%5D))%22%7D,%7B%22expr%22:%22sum(increase(src_syntax_highlighting_requests%7Bstatus%3D%5C%22error%5C%22%7D%5B5m%5D))%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D&right=%5B%22now-2d%22,%22now%22,%22Prometheus%22,%7B%22expr%22:%22alert_count%7Bname%3D%5C%22blob_load_latency%5C%22%7D%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D

<img width="1709" alt="image" src="https://user-images.githubusercontent.com/23356519/91649740-92b61300-eaa9-11ea-85ee-176f36e92ee9.png">
