### ISSUE TITLE
Make every line of code as link following to usages (references)

### ISSUE THREAD

**Issue by poojaj-tech** [sourcegraph/sourcegraph#12955]
#### Feature request description

> Make every line as link following to usages

#### Is your feature request related to a problem? If so, please describe.

Customer feedback:
1. Primary issue with Find references window is it can't provide a reference most of the time
2. Find references windows appears every time and when I want to copy a statement for searching, that window prevents me from doing so.
3. Search bar was folding, it was a very frustrating experience. It might be fixed now.

Customer: https://app.hubspot.com/contacts/2762526/contact/16241401/
Company: https://app.hubspot.com/contacts/2762526/company/732945850/

**Comment by poojaj-tech** [comment]
Could you confirm that "Find references" is the popup and not the References pane below?
<img width="706" alt="Screen Shot 2020-08-12 at 1 40 22 PM" src="https://user-images.githubusercontent.com/57463526/90065784-a25bec00-dca1-11ea-9b2b-ae82576db6dd.png">

**Comment by macraig** [comment]
@scalabilitysolved is there a reason you moved this into the Backlog?
