### ISSUE TITLE
fix proposed queries in alertForTimeout 

### ISSUE THREAD

**Issue by stefanhengl** [sourcegraph/sourcegraph#12963]
[alertForTimeout](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@c4160cf/-/blob/cmd/frontend/graphqlbackend/search_alert.go?subtree=true#L93:6) ignores AND patterns when proposing queries

![image](https://user-images.githubusercontent.com/26413131/90103115-48f7c980-dd42-11ea-831e-f903be42653d.png)

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by stefanhengl** [comment]
This has been fixed. As of today, I cannot reproduce it on Sourcegraph.com
