### ISSUE TITLE
dev/ci: codecov test coverage unstable

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#12986]
Something seems to be not right about our configuration.

In Elizabeth’s PR it showed +12% TS coverage and then after a few other commits it shows exactly 0% change in test coverage:

https://github.com/sourcegraph/sourcegraph/pull/12803#issuecomment-673011797
![Screen Shot 2020-08-13 at 10 24 06 AM](https://user-images.githubusercontent.com/754768/90166642-68492380-dd4f-11ea-805d-ae778a1bf43c.png)

cc @keegancsmith @eseliger

**Comment by nicksnyder** [comment]
When I look at the codecov upload step in buildkite, it tells me the report is at https://codecov.io/github/sourcegraph/sourcegraph/commit/b973f000839da45c4d6cb0a381e846b26b688bbf

This commit hash is the head commit after Elizabeth merged main into her development branch, so I am wondering if this is why codecov is reporting 0% change in coverage

**Comment by nicksnyder** [comment]
Something is definitely broken or misconfigured. If you look at coverage on the main branch, it thrashes:

![Screen Shot 2020-08-13 at 10 44 49 AM](https://user-images.githubusercontent.com/754768/90168535-10f88280-dd52-11ea-9740-7a084c05ce7b.png)

**Comment by eseliger** [comment]
Good find, that could be a problem!

Other reasons why it failed in the past: 

Single reports aren't uploaded reliably, sometimes just nothing happens and no report is uploaded, causing coverage to change.
This build has 5 reports attached, but we should have uploaded 6: https://codecov.io/gh/sourcegraph/sourcegraph/commit/440881116efe1473da7164972babffea9e2f4bfc/builds. Hence, the commit is reported as reducing coverage by ~4%. The missing report is the go coverage and the logs here: https://buildkite.com/sourcegraph/sourcegraph/builds/70714#58a251e4-b4de-453f-944e-6ea888eaff44 show no codecov logs, but exit code 0. That happened quite a few times.

Codecov says [they detect CI status from GitHub/Buildkite](https://docs.codecov.io/docs/github-checks-beta) and defer posts to comments, but sometimes I've seen comments being posted while CI was still going, those were obviously wrong as well because not all reports were uploaded by that point in time.

And for some reason, we've seen that message for a while now after we switched to `main` as our default branch:
![image](https://user-images.githubusercontent.com/19534377/90168618-a2411680-dd9d-11ea-999c-aa02189cc8fe.png)
Not sure that indicates a problem but it won't go away.

I just found GitHub checks in their docs, they're still in beta but maybe still more reliable than the posted report(?) https://docs.codecov.io/docs/github-checks-beta

**Comment by nicksnyder** [comment]
Another example of a PR where codecov info is wonky:
https://github.com/sourcegraph/sourcegraph/pull/13838#issuecomment-693177625

![Screen Shot 2020-09-15 at 10 29 37 PM](https://user-images.githubusercontent.com/754768/93295900-f1b2a200-f7a2-11ea-89f7-850818aa60c3.png)


cc @jerrode

**Comment by nicksnyder** [comment]
Another example:

https://github.com/sourcegraph/sourcegraph/pull/14241

**Comment by jerrode** [comment]
cc: @thomasrockhu

Hey @nicksnyder, to confirm, there are many more files changing than you would expect, correct? Most often this will happen if Codecov is selecting the incorrect Head PR and/or not all uploads are making it Codecov. 

https://codecov.freshdesk.com/support/solutions/articles/43000593940-unexpected-coverage-changes

We'll take a look on our side as well.

**Comment by nicksnyder** [comment]
> there are many more files changing than you would expect, correct?

yep!

**Comment by jerrode** [comment]
@nicksnyder ok, so some things to confirm:

1.)  Codecov is picking this as the Pull Request Base Commit: 
![image](https://user-images.githubusercontent.com/8398772/94613062-db9fe980-0258-11eb-9d60-20458e3fe962.png)

Which you can see here: https://codecov.io/gh/sourcegraph/sourcegraph/pull/13838/commits

Is this the correct base? 

2.) That base commit has 10 total session uploads / builds from Build Kite: https://codecov.io/gh/sourcegraph/sourcegraph/commit/465d7e7bfe424ff969e6e0f2864cc398fc27a5c5/build

3.) The Head commit on this PR only has 6 builds / session uploads from Build Kite: 
https://codecov.io/gh/sourcegraph/sourcegraph/commit/36a3bd27a29f1b4ef0c1a00a12ba1fa0cdc252d8/build


Do you know why there would be a difference in # of sessions / builds from Build Kite? This can cause the "diff" run by Codecov to be wonky.


A way to work around this would be to stop notifications to come to your Github PR until Codecov received N builds: https://docs.codecov.io/docs/pull-request-comments#after_n_builds

(Of course, this would need comments to be working as well, are you seeing multiple comments issue anymore? cc: @felixfbecker )

**Comment by nicksnyder** [comment]
> Is this the correct base?

That is not the correct base commit. The base commit should have been: b872f78d5f68a70a76f861c4c1aa4da1b7af045c. I can tell because this is the base commit that codenotify used:
<img width="552" alt="Screen Shot 2020-09-29 at 3 19 35 PM" src="https://user-images.githubusercontent.com/754768/94622519-393b3280-0267-11eb-98ae-4d664205dd80.png">

> Do you know why there would be a difference in # of sessions / builds from Build Kite?

We don't run every build step for every commit, but we do configure codecov to carryforward data: https://github.com/sourcegraph/sourcegraph/blob/main/dev/codecov.yml

> A way to work around this would be to stop notifications to come to your Github PR until Codecov received N builds

This wouldn't solve this particular problem.

**Comment by thomasrockhu** [comment]
@nicksnyder, apologies, we clearly dropped the ball on our side here. I've looked at the most recent set of PRs, and I haven't noticed any significant changes in coverage (no large swings in coverage). I wanted to get back to you and see if you were still experiencing an issue, or if we had fixed it in our general bug-fixing, as I think that's the root issue.

**Comment by nicksnyder** [comment]
I quickly browsed a few open PRs and found a PR that touches no tsx files but has a delta in test coverage:

https://github.com/sourcegraph/sourcegraph/pull/15622
![Screen Shot 2020-11-10 at 11 18 03 AM](https://user-images.githubusercontent.com/754768/98722846-6b4fb200-2346-11eb-8887-f708e67fc226.png)

**Comment by nicksnyder** [comment]
Here is another change that didn't touch any code files, but Codecov reported a change in Go coverage: https://github.com/sourcegraph/sourcegraph/pull/15711

![Screen Shot 2020-11-12 at 10 09 16 AM](https://user-images.githubusercontent.com/754768/98978688-3327ab00-24cf-11eb-8283-d75fbdc6dc40.png)

**Comment by thomasrockhu** [comment]
@nicksnyder, I dug into the more recent comment you made.

The first things to note is the location of the [changes](https://codecov.io/gh/sourcegraph/sourcegraph/pull/15711/changes). Specifically `enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/locations.go` lines 98 and 99. Before they were covered, and now they are not.

There are only two [commits](https://codecov.io/gh/sourcegraph/sourcegraph/pull/15711/commits) to deal with here, the BASE and the HEAD.

Looking at the [raw upload](https://codecov.io/gh/sourcegraph/sourcegraph/commit/f6b69abb1d70953ca37c4f0fcbd406c966cb053b/build) for the BASE commit, I see this line

```
github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/locations.go:98.40,100.3 1 1
```

For the HEAD commit, the [upload](https://codecov.io/gh/sourcegraph/sourcegraph/commit/8848bb57fa0b1b475d1bcb3a3cc64d22d5595778/build) shows

```
github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/locations.go:98.40,100.3 1 0
```

According to the [Golang documentation](https://github.com/golang/go/blob/0104a31b8fbcbe52728a08867b26415d282c35d2/src/cmd/cover/profile.go#L56), the last number represents the count. This means that now, this line is no longer covered. In other words, Codecov is showing coverage as uploaded to it.

We have seen this sort of issue before, but not necessarily with Go. The most common reason is that tests are unexpectedly idempotent, or that not all tests are being run. I'm not too familiar with the Sourcegraph codebase so I can't say for sure this is the case, but I would check this path first. Is there any way to isolate tests run?
