### ISSUE TITLE
Commit search result fails on empty repos

### ISSUE THREAD

**Issue by aisbaa** [sourcegraph/sourcegraph#12990]
- **Sourcegraph version:** 3.17.3
- **Platform information:** all versions

#### Steps to reproduce:

1. create completely empty repo with no commits
2. wait for sourcegraph to try to clone it
3. run this query:

```
{
  search(query: "type:commit count:10000 archived:no language:go after:\"August 1, 2020\"") {
    results {
      resultCount
      limitHit
      results {
        ... on CommitSearchResult {
          commit {
            repository {
              name
            }
          }
        }
      }
    }
  }
}
```

#### Expected behavior:

Do not include that repo in result set.

#### Actual behavior:

Error is returned:

```
{
  "errors": [
    {
      "message": "1 error occurred:\n\t* commit search failed: failed to search commit log REPO_NAME@: git command [git show --no-patch --no-merges -z --decorate=full --format=format:%H%x00%D%x00%aN%x00%aE%x00%at%x00%cN%x00%cE%x00%ct%x00%B%x00%P%x00 --no-prefix --max-count=10001 --extended-regexp --regexp-ignore-case --since=August 1, 2020 --patch --extended-regexp -- :(icase)*.go] failed (output: \"\"): exit status 128 (stderr: \"fatal: your current branch 'master' does not have any commits yet\")\n\n",
      "path": [
        "search",
        "results"
      ]
    }
  ],
  "data": {
    "search": null
  }
}
```

#### Ref

Might be related to this issue https://github.com/sourcegraph/sourcegraph/issues/78

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by poojaj-tech** [comment]
@stefanhengl would this be good to close now? Asking because if it can be closed I won't include it in the search team issue backlog.

**Comment by PaulMcMillan** [comment]
I can't do bulk data export while this issue exists. I really don't want to have to go prune empty repos from bitbucket any time someone creates one and doesn't immediately commit something to it.

**Comment by malomarrec** [comment]
Tagging similar issue in #20158 to feed into prioritisation work.

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by tsenart** [comment]
@camdencheek: Closing, but feel free to check if this is still an issue.

**Comment by camdencheek** [comment]
This was fixed as part of the commit/diff search rewrite 👍
