### ISSUE TITLE
Haskell code intelligence

### ISSUE THREAD

**Issue by jhigdon** [sourcegraph/sourcegraph#13]
Support Haskell on Sourcegraph

**Comment by chrismwendt** [comment]
Haskell code intelligence has been added in Sourcegraph 3.0 :tada:

https://about.sourcegraph.com/blog/sourcegraph-3.0#code-intelligence-for-all-languages

[Try it out](https://sourcegraph.com/github.com/pcapriotti/optparse-applicative@72b6e4a52cb0d7e13f390f836ebfe493ff37906c/-/blob/Options/Applicative/Builder.hs#L120:8) on Sourcegraph.com:

![image](https://user-images.githubusercontent.com/1387653/54005959-3ff7d700-4110-11e9-9dd7-7d9cc839d863.png)
