### ISSUE TITLE
Syntax highlighting is broken on file extensions that don't match case

### ISSUE THREAD

**Issue by RichardBelzer** [sourcegraph/sourcegraph#13007]
- **Sourcegraph version: 3.18.0** 
- **Platform information: Fedora Server** 

#### Steps to reproduce:

Have a file in the repo that is all caps

#### Expected behavior:

The syntax highlighting works:

<img width="427" alt="works" src="https://user-images.githubusercontent.com/69686380/90264814-a877d700-de1f-11ea-99b7-bf0d7ee5b1da.png">

#### Actual behavior:

Everything is all grey. It doesn't think it's a source file.

<img width="386" alt="doesntwork" src="https://user-images.githubusercontent.com/69686380/90264900-d1986780-de1f-11ea-9d70-3720fb2dbd9f.png">

This is probably a case where .lower() is **not** being called on the filename to match against supported source file types

**Comment by slimsag** [comment]
Thank you for filing this! Should be an easy fix, will take a look

**Comment by slimsag** [comment]
Sorry this has fallen behind, I will plan on taking a look at this soon.

I think we just need to update `p.Filepath` before we send it to the syntax highlighting service here: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@98abec31146bf652f03dedd8917ec76d5baa1d80/-/blob/internal/highlight/highlight.go#L170

It will be important to have some test cases which shows we *only* lowercase `p.Filepath`'s extension, and not on other filepaths like `FOO.txt`, `Makefile`, `Makefile.am`, etc.

**Comment by slimsag** [comment]
@RichardBelzer Just wanted to let you know, this has been fixed in the latest `insiders` build, on Sourcegraph.com, and will be in our next release Sourcegraph v3.23 on Dec 20th. Sorry for the delay again!
