### ISSUE TITLE
Search suggestion box keeps popping open on page changes (on non-smart search bar)

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#13000]
I suddenly started seeing this again recently, after not noticing it for months (I recall this was an issue at one point in the past). I laid out a very specific set of repro steps below that I know works, but it also happens quite often in other various situations, so I assume I'm missing the common thread here.

Repro:

- visit https://sourcegraph.com/github.com/sourcegraph/sourcegraph
- click into the search bar (at the end) and type any character (or any string). Wait for the full autocomplete menu to appear.
- click anywhere on the page to make it go away
- click on any file in the file tree sidebar
- see the autocomplete menu pop back up

![2020-08-13 17 23 45](https://user-images.githubusercontent.com/5589410/90209939-88a1ce00-dda1-11ea-97b3-6a8a876c4002.gif)

**Comment by attfarhan** [comment]
Since we have had the smart search field on by default for a while now, this older query input is not actively maintained. It seems that we have stability on the smart search field, so can we remove the feature flag for the smart search field, and remove this old query input completely? cc @christinaforney @lguychard

**Comment by dadlerj** [comment]
As I posted in Slack: 

>OMG I completely forgot I had the old search field toggled on… I think I did it at one point last week to help a customer debug a similar issue (who was still using the old one). I totally agree, let’s just remove the old one

:)
