### ISSUE TITLE
When adding auth provider for the first time, it's easy to delete `builtin` auth and get locked out

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#13012]
Reported by:

- https://app.hubspot.com/contacts/2762526/company/1748986560
- https://app.hubspot.com/contacts/2762526/company/2942642504

Both of these companies followed our docs for adding an auth provider (e.g. https://docs.sourcegraph.com/admin/auth#github) and copy-pasted the JSON from there. In the process, they deleted their `builtin` auth provider as well.

However, the connection to the external auth provider wasn't working correctly, and they got completely locked out.

Ideas for how to improve this:
- Big red warning in our docs on each auth provider section about this?
- Alert on config save whenever someone deletes `builtin` auth?
- Some sort of site admin sign-in escape hatch (seems like a bad idea)
- Document the commands to run to re-add builtin auth if the admins can get SSH access to the PG database?

**Comment by dadlerj** [comment]
Note from @slimsag:

https://docs.sourcegraph.com/admin/config/site_config#editing-your-site-configuration-if-you-cannot-access-the-web-ui

**Comment by daxmc99** [comment]
Closing with slimslag's comment being the workaround. 
Happy to reopen if we see again
