### ISSUE TITLE
🚚 LSIF-Java Delivery 

### ISSUE THREAD

**Issue by aidaeology** [sourcegraph/sourcegraph#13017]
The goal of this task is to ship LSIF-java v1.0 to customers:

1. Fix any [outstanding bugs and issues](https://github.com/sourcegraph/lsif-java/issues?q=is%3Aopen+is%3Aissue+label%3Abug) for LSIF-java.
1. Benchmark and test LSIF-java for performance, determine if there are any bottlenecks that need to be resolved.
1. Work with three existing customers below to deploy LSIF-java successfully and work out any potential technical blockers or usability issues so that LSIF-java can be used by all customers as part of a wide release.

- [ ] Customer 1: https://github.com/sourcegraph/customer/issues/79
- [ ] Customer 2: https://github.com/sourcegraph/customer/issues/80
- [ ] Customer 3: https://github.com/sourcegraph/customer/issues/81

Once this is complete for all three we will mark LSIF-java as stable and ready for general availability.

**Comment by aidaeology** [comment]
@Strum355 Don't worry about starting work on this in your first week or two.

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by macraig** [comment]
Tracking elsewhere
