### ISSUE TITLE
Log metric for requests to the code host by reads vs. writes

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#13026]
requested by https://app.hubspot.com/contacts/2762526/company/1748986560

This prospect is using GitHub for authn and authz, and as part of setting up a GitHub OAuth app, we require access to private repos. It sounds like (per @unknwon ) that read/write can't be separated due to a limitation on GitHub's side, so while we never actually write through this OAuth app, we have to request it.

Request from the customer:

> Since the write permissions are required, is there any logging/auditing we can do on sourcegraph's side to review accesses?

And my response:

> Perhaps we could log something to Prometheus/Grafana so you can get a metric for the # of read vs. write requests in a period of or something similar.

Not sure if this is possible (?), but consider this a feature request :)

**Comment by unknwon** [comment]
read vs. write requests in terms of authN/authZ or everything?

If you look at our GitHub client package (methods of `*Client`): https://godoc.org/github.com/sourcegraph/sourcegraph/internal/extsvc/github, there are only three methods about _create, update and close pull requests_ (which currently only used by campaigns I believe, and not using OAuth token).

So the metric would be confusing that "there are write requests" but not via OAuth token.
