### ISSUE TITLE
SAML: Expected Enveloped and C14N transforms

### ISSUE THREAD

**Issue by swsnider** [sourcegraph/sourcegraph#13032]
- **Sourcegraph version:** 3.18.0
- **Platform information:** Docker

#### Steps to reproduce:

1. Enable SAML auth with all the parameters necessary
2. Click 'Login via SAML'

#### Expected behavior:

Redirected to auth provider, then returned and logged into the instance

#### Actual behavior:

Error is returned to the user, and the logs indicate I'm triggering the bug: https://github.com/russellhaering/goxmldsig/issues/43

In particular, the only transform present in my SAML provider AuthnResponse (from the INSECURE tracing) is `<Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/></Transforms>`

**Comment by unknwon** [comment]
Thanks for the feedback!

Can you post the error message you found? Also, which SAML provider you were connecting to?

**Comment by swsnider** [comment]
`19:35:05                          frontend | t=2020-08-17T19:35:05+0000 lvl=eror msg="Error validating SAML assertions. Set the env var INSECURE_SAML_LOG_TRACES=1 to log all SAML requests and responses." err="reading AuthnResponse assertions: error validating response: Expected Enveloped and C14N transforms"`

I'm not allowed to disclose the SAML provider we use (and I don't actually know which one it is myself). I do know that Monday.com, Splunk, and several other third party offerings do not have issues integrating.

**Comment by unknwon** [comment]
Thanks for grabbing the log! 

> I'm not allowed to disclose the SAML provider we use (and I don't actually know which one it is myself).

It would be very inconvenient to reproduce the error if we don't know what to test against and propose a fix.

**Comment by swsnider** [comment]
Looks like Chris Toshok has the same issue at a different company (based on who filed the upstream issue) perhaps he could help with a test case?

**Comment by tsenart** [comment]
Fixed by https://github.com/sourcegraph/sourcegraph/pull/17765
