### ISSUE TITLE
Add create/edit page for campaigns

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#13058]
Minimal in-app documentation on how to get started with a campaign

**Comment by rrhyne** [comment]
This issue would be blocked by: 

https://github.com/sourcegraph/sourcegraph/issues/13115

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
