### ISSUE TITLE
Use campaign name in URL instead of ID for better readability

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#13086]
- [x] Change URL methods in graphql backend
- [x] Change routing in the app
- [x] Add API to resolve campaign by namespace + name
- [x] Adjust frontend to use that API

**Comment by unknwon** [comment]
Any examples?

The way medium.com does seem a good middle ground: `/the-science-of-setting-up-a-healthier-home-325f10c46c1d`.

**Comment by eseliger** [comment]
`https://sourcegraph.acme.corp/users/eseliger/campaigns/awesome-campaign`

Campaign names are now limited to `^[\\w.-]+$`, so they're sluggable :)

**Comment by eseliger** [comment]
Proposed API schema change:

```diff
diff --git a/cmd/frontend/graphqlbackend/schema.graphql b/cmd/frontend/graphqlbackend/schema.graphql
index f18955d2f1..dcb3eb7961 100755
--- a/cmd/frontend/graphqlbackend/schema.graphql
+++ b/cmd/frontend/graphqlbackend/schema.graphql
@@ -1259,6 +1259,13 @@ type Query {
         # Only include campaigns that the viewer can administer.
         viewerCanAdminister: Boolean
     ): CampaignConnection!
+    # Looks up a campaign by namespace name and campaign name.
+    campaign(
+        # The namespace name where the campaign lives.
+        namespace: String!
+        # The campaigns name.
+        campaign: String!
+    ): Campaign
 
     # Looks up a repository by either name or cloneURL.
     repository(
```

This is aligned with how we resolve users by email/username.

**Comment by mrnugget** [comment]
Why `campaign: String!` and not `name: String!`? For users we also call the fields `email` and `username`: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/schema.graphql#L1328-1333

**Comment by unknwon** [comment]
> `https://sourcegraph.acme.corp/users/eseliger/campaigns/awesome-campaign`
> 
> Campaign names are now limited to `^[\\w.-]+$`, so they're sluggable :)

Without random hash, one can't use multiple campaigns with same name?

**Comment by eseliger** [comment]
Correct but campaign names are unique identifiers :) If you apply to a campaign that exists, you're updating it

**Comment by eseliger** [comment]
> Why campaign: String! and not name: String!? For users we also call the fields email and username: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/schema.graphql#L1328-1333

Because the other fields is called `namespace` and I thought of it as the two resources, `namespace/campaign`, where `name` could have been ambiguous if it's the name of the namespace, campaign or both 🤔 
Did you find it confusing @mrnugget?

**Comment by unknwon** [comment]
> Correct but campaign names are unique identifiers :) If you apply to a campaign that exists, you're updating it

Cool... but surprising! In that case, sounds good :)

**Comment by mrnugget** [comment]
> Cool... but surprising! In that case, sounds good :)

Think of the campaign name like the repository name on GitHub: you can only have a single repository/campaign with name A in the same namespace (org/user).

---

> Because the other fields is called `namespace` and I thought of it as the two resources, `namespace/campaign`, where `name` could have been ambiguous if it's the name of the namespace, campaign or both 🤔
> Did you find it confusing @mrnugget?

Yeah. `campaign(namespace: ID, campaign: String)` is more confusing and ambiguous to me than `campaign(namespace: ID, name: String), since the latter are just the names of properties on a campaign.

**Comment by eseliger** [comment]
Okay, I'll change it to `name` then, but note that `namespace` is not `ID`, but `string` as well.
Since I just realized `namespaceName` is not ensured to be unique (or is it?), I guess we have to make it `username: String` and`orgName: String` instead.
