### ISSUE TITLE
Confusion about editing personal vs global search scopes

### ISSUE THREAD

**Issue by poojaj-tech** [sourcegraph/sourcegraph#13081]
- **Sourcegraph Cloud** 

<img width="860" alt="Screen Shot 2020-08-17 at 3 52 09 PM" src="https://user-images.githubusercontent.com/57463526/90452385-d882dc80-e0a2-11ea-9c14-b77eb0378eb5.png">

#### Steps to reproduce:
1. Clicking the Edit button took me to User Settings. I was temporarily confused about where all the other search scopes came from as as I didn't many personal scopes defined.

#### Expected behavior:
1. Hover or tooltip on "Edit" link explaining how to edit user search scopes, and where global search scopes live
2. Visual difference b/w global and personal search scopes

#### Actual behavior:
1. Dropped into User settings without guidance on editing
2. No visual cue for global versus personal search scopes

**Comment by lguychard** [comment]
This is no longer relevant with snippets.
