### ISSUE TITLE
Link to "uploading LSIF data" docs is dead

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#13096]
On the repository settings page, this link is dead:

![screenshot_2020-08-18_11 02 35@2x](https://user-images.githubusercontent.com/1185253/90493280-78dc0e00-e142-11ea-8be5-32436f26457a.png)

It leads to `https://docs.sourcegraph.com/user/code_intelligence/lsif` which gives me a [not found](https://docs.sourcegraph.com/user/code_intelligence/lsif) message.

It should link to https://docs.sourcegraph.com/user/code_intelligence/precise_code_intelligence I guess, but I'm not sure, so I didn't open a PR.

**Comment by Strum355** [comment]
Think youre right, https://docs.sourcegraph.com/user/code_intelligence/precise_code_intelligence has a data retention section which seems in-line with what a search for the old url shows 
![image](https://user-images.githubusercontent.com/18282288/90501488-5945e500-e144-11ea-89fd-450229a293ee.png)

Theres 12 places that I could find pointing to that link 
https://sourcegraph.com/search?q=repo:sourcegraph/sourcegraph+user/code_intelligence/lsif%5Cb&patternType=regexp

**Comment by Strum355** [comment]
https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/web/src/enterprise/codeintel/CodeIntelUploadsPage.tsx#L209:27 shows it to be pointing to the right url :thinking:

**Comment by efritz** [comment]
@mrnugget What instance are you seeing this on? Links look fine on dotcom.

**Comment by mrnugget** [comment]
That was on `main`, my local instance.

**Comment by efritz** [comment]
I can't reproduce on main locally. Can you hard refresh and see if it still is outdated?

**Comment by efritz** [comment]
@Strum355 Looks like there's only one actual outdated link (one is a fixture, the other results were form forked repos): https://sourcegraph.com/search?q=repo:%5Egithub.com/sourcegraph/sourcegraph%24+code_intelligence/lsif%5Cb&patternType=regexp

Fixed here: https://github.com/sourcegraph/sourcegraph/pull/13103.

**Comment by mrnugget** [comment]
Cannot reproduce after hard-reloading 🤦‍♂️
