### ISSUE TITLE
Add rev: filter support

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#13091]
This issue tracks syntax, implementation and usage concerns for a `rev:` filter. 

What this would look like:

- `rev` supports regex syntax. Patterns containing the `|` operator can thus match multiple revisions 
- we will maintain backwards compatibility with `repo:foo@bar` syntax
- `rev` can compose with `or` operators and work with search expressions. So these are all equivalent:
  - `repo:foo (rev:bar or rev:baz)` 
  - `(repo:foo rev:bar) or (repo:foo rev:baz)`
  - `repo:foo@bar or repo:foo@baz` 
  - `repo:foo rev:bar|baz`
    - **Note:** this work item shouldn't require anything special to work with `or`-operators, it should just work generally based on @rvantonder's search expression work.

The implementation should take care of the backend part that matches a pattern according to branches. When processing the query, it should check for invalid syntax like `repo:foo@bar rev:baz`. 

Existing context:
 - #9712 It is a customer pain that multiple revisions for a repo cannot be specified.
  - Search expressions help with the above issue as a workaround, e.g., `repo:foo@bar or repo:foo@baz`, but the `repo:` part is shared, and it makes a lot of sense to pull out a separate `rev:` specifier
- Partial discussion of adding `rev:` in https://github.com/sourcegraph/sourcegraph/issues/10820#issuecomment-637154705

**Comment by stefanhengl** [comment]
More context:
- Regex or globbing support for branch or revision names (https://github.com/sourcegraph/sourcegraph/issues/11213)

**Comment by stefanhengl** [comment]
> rev supports regex syntax. Patterns containing the | operator can thus match multiple revisions

For `type:commit` and `type:diff`, we use the `@` to set options for `git-log`. The way it is implemented now, our revision-syntax is a shorthand for `git-log <revision range> --exclude=<glob-pattern> --glob=<glob-pattern>`, where <revision range> is a powerful, git-specific syntax to describe a set of commits in the commit-tree.  I suggest to use the same syntax for rev: and @ and extend the supported git-log options if required.

**Comment by stefanhengl** [comment]
We still need to document `rev:` in the user docs to close this ticket
