### ISSUE TITLE
Design create/edit page for campaigns

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#13115]
Design a create/edit page which acts as a useful product workflow page. The page should contain:

* Hello world
* Other Example campaigns
* Blank campaign

Additionally, explore documentation examples and commonly referenced items. 

![image](https://user-images.githubusercontent.com/539268/92508762-ff25c600-f1bd-11ea-942f-6f899f52d893.png)

Figma frame:
https://www.figma.com/file/5Ap3Iqjv81Dh0Hc6cLtSqN/Create-page-13115?node-id=290%3A3622

**Comment by rrhyne** [comment]
Blocks: [#13058 Add create/edit page for campaigns](https://github.com/sourcegraph/sourcegraph/issues/13058)

**Comment by rrhyne** [comment]
@sqs can you review? This is my interpretation of your idea for an improved create page that acts as a "product workflow page". 

cc @chrispine @eseliger

**Comment by chrispine** [comment]
Nice! The commands are not quite right, as there is no `-preview` flag anymore, and both preview and apply require a namespace, like `-namespace rrhyne` or something.

**Comment by rrhyne** [comment]
Commands are fixed.

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
