### ISSUE TITLE
Proposed queries in search alerts do not preserve operators

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#13125]
For example following suggestion doesn't contain the `foo and bar` part, may be only `alertForOverRepoLimit`.

<img src=https://user-images.githubusercontent.com/26413131/89024658-bdd00a00-d325-11ea-9c5e-9e6c2b8af82a.png>

**Comment by stefanhengl** [comment]
@rvantonder I could not replicate the error. Maybe this has resolved itself?

**Comment by rvantonder** [comment]
cannot repro
