### ISSUE TITLE
deploy-sourcegraph: have Renovate apply image updates as soon as they are built

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#13122]
We want deploy-sourcegraph's `master` branch to reflect the latest insiders builds from Sourcegraph's `main` branch. Renovate should automatically open and merge pull requests to update images ASAP. Ideally, each Renovate PR for image tags in deploy-sourcegraph can be tied back to a specific Sourcegraph commit

We need to update the release process to accommodate this. One possibility might be to branch at the relevant deploy-sourcegraph commit and add a commit that pins to a release image, for example

**Comment by bobheadxi** [comment]
Update - this is turning out a bit more frustrating than I expected on the `deploy-sourcegraph` end:

* https://github.com/renovatebot/config-help/issues/440#issuecomment-557779301
* similar to above, unable to get renovate to accept semver -> nonsemver

Still investigating

**Comment by slimsag** [comment]
It is my intention that GitHub.com/slimsag/update-docker-tags could be used for exactly this type of situation - worth considering now maybe?

**Comment by bobheadxi** [comment]
It looks like the tool supports a similar upgrade scheme to Renovate, ie `insiders` -> `insiders` and `semver` -> `semver`, but I just want it to see "new semver" -> forcibly update everything - is that currently possible?

**Comment by slimsag** [comment]
You are right it is not currently possible, but it should be relatively easy to add and I have plans to do so in the near future. Something like:

```
update-docker-tags -replace 'latest=<semver>' # replace all "latest" tags with semver tags
update-docker-tags -replace '<semver>=latest' # replace all semver tags with 'latest'
```

(and obviously you could swap `latest` with `insiders`, or target it to a more specific set of images like those with a `sourcegraph/` prefix.)

If that was in place, would that help? I imagine the difficulty at that point being "can it open PRs automatically" which it unfortunately cannot yet

**Comment by bobheadxi** [comment]
@slimsag I've made a pass at what I have in mind in https://github.com/slimsag/update-docker-tags/pull/7 - I'll be able to use this to automate the creation of release PRs on desired branches, which I think will be a marked improvement on the current wait-for-Renovate step of the release process!

**Comment by bobheadxi** [comment]
This is currently broken until my Renovate fix at https://github.com/renovatebot/renovate/pull/7274 is merged, due to being unable to override `schedule` set in `deploy-sourcegraph` (which allows us to make our manual triggers take precedence over the Renovate app)

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by bobheadxi** [comment]
Marking as closed - this seems to be working, and I am working on a handbook update.
