### ISSUE TITLE
Allow users to publish only a subset of changesets

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#13139]
With the switch to the new workflow publishing changesets is an all-or-nothing operation.

Right now, to publish the changesets in a campaign the user has to switch the `published: false` in the campaign spec

```yaml
# ...
changesetTemplate:
  # ...
  published: false
```

from `false` to `true`.

We should allow users to publish only a subset of changesets.

---

**More generally**: we should allow users to set all of the attributes in the `changesetTemplate` (commit message, title, body, ...) for only a subset of repositories.

**Comment by LawnGnome** [comment]
Here is [a draft RFC](https://docs.google.com/document/d/1A-5cbYGz1p1UB1eAFsIgpK5XDkvS7ZNAVKMdtBm_WY0/edit?usp=sharing) containing some (but probably not all) of the available options.

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
