### ISSUE TITLE
codeintel/design: Go to definition of unindexed/uncloned code

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#13137]
Code navigation currently fails if both the source and target of a go to definition operation are not cloned in the Sourcegraph instance.

In situations where RepoA depends on RepoB:

- if RepoA and RepoB both have LSIF indexes, we get precise go to definition;
- if RepoA has an LSIF index but RepoB does not, we fall back to search-based code intelligence, which _may_ find the definition in RepoB;
- if RepoB is not cloned in the instance, we have nothing to target.

We should be able to match the behavior of VSCode by implementing a [TextDocumentContentProvider](https://code.visualstudio.com/api/extension-guides/virtual-documents#textdocumentcontentprovider) in these circumstances, which will be able to render the text of a non-local dependency. This may require that we index the text documents of dependencies while indexing RepoA. Alternatively, we could federate code intelligence requests to a public Sourcegraph instance (https://sourcegraph.com) which is likely to contain these third-party dependencies.

This ticket is tracking an RFC effort to propose a solution to this problem.

**Comment by felixfbecker** [comment]
Cross-posting the proposal from #9952 for the case where the target repo is cloned but has no LSIF index itself (specifically for TypeScript, but may be applicable or even easier for other languages):

> Could the LSIF indexer use the information from node_modules to determine the target repo, commit, file and position like the language server does it? I wrote an overview of the algorithm back then here: https://github.com/sourcegraph/sourcegraph-typescript/issues/8#issue-379063436
> 
> The "resolve clone URL to repo URL using raw API" step would probably not be done by the indexer, but by the LSIF server or JIT by the code intel extension (not sure how it currently works for LSIF-to-LSIF xrepo j2d). The indexer would just do the steps of the algorithm necessary to produce the information necessary for LSIF's xrepo information encoding mechanism (package monikers etc).

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by efritz** [comment]
I'm currently drafting an RFC for this feature at https://docs.google.com/document/d/1QigoTPGbc5ztGRzeqBBFVM5sD_uLfT4yOO3qxch2kGE. Feel free to leave comments if you have input while we discuss some possible implementation avenues.

**Comment by efritz** [comment]
I'm going to close this issue as we will track discussion and later implementation progress in the RFC.
