### ISSUE TITLE
campaigns: review docs for completeness and accuracy

### ISSUE THREAD

**Issue by LawnGnome** [sourcegraph/sourcegraph#13153]
We've made lots of changes to campaigns in 3.18 and 3.19, so we should do a full review of the campaign docs to make sure they reflect reality in total.

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by mrnugget** [comment]
While we can always improve our docs (and should!) I think completeness and accuracy are covered by these:

- https://github.com/sourcegraph/sourcegraph/pull/13638
- https://github.com/sourcegraph/sourcegraph/pull/13812
- https://github.com/sourcegraph/sourcegraph/pull/13848

I did multiple passes over the docs and they're not outdated/wrong anymore.

So I'm going to close this, *but*, again, it doesn't mean we shouldn't update/improve our docs further. I just want to check off this really specific thing (docs became outdated with new workflow) here.
