### ISSUE TITLE
user testing for campaigns

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#13151]
(Previous user testing [here](https://github.com/sourcegraph/sourcegraph/issues/9912).)

Proposed testing script:
```
Hi $NAME,

We're excited about the new Campaigns workflow, and we're happy to have you
help us with testing and polishing it!

Here's what we'd like you to do:

1. Set up your Sourcegraph instance (using `main`, not 3.19) to have one code
   host configuration syncing the sourcegraph-testing GitHub org
   (https://github.com/sourcegraph-testing)
2. Create a campaign that does the following in at least 5 repositories:
   a. Run Comby (https://comby.dev/) to replace `fmt.Sprintf("%d", :[v])` with
      `strconv.Itoa(:[v])` in Go files (`*.go`)
   b. Run `go fmt ./...` in the repository
3. Write up everything you bump into, document whenever you get stuck.
   Ideally you include screenshots. (Take a look at Joe's report for inspiration:
   https://gist.github.com/unknwon/b7c80d23e6b2a624e50e4073454959e0)
4. Send us your report. Thanks!

To get started, you'll need the docs: https://docs.sourcegraph.com/@main/user/campaigns

We don't want to give you more detailed instructions, the idea being that you
use the docs to find answers. (We're testing the docs, too.)

Thanks in advance!

~your friendly neighborhood campaigns team
```

TODO
- [x] Confirm above script with Rob and the Campaigns team.
- [x] One of us runs through it ourselves to make sure everything works as expected.
- [x] Find people interested in trying out Campaigns. (Ask for internal folks who might be interested.)
- [x] Send the script to all of the testers (sent 2020-09-09 at noon PST)
- [ ] Collect feedback from
  - [x] tion
  - [ ] aida
  - [ ] christina
  - [ ] loic

**Comment by eseliger** [comment]
> The biggest question I have is around whether we are using UserTesting, or just asking folks internally to try it out. Because the first step requires setting up a Sourcegraph instance, it's not easy for just anyone to try out.

Since the setup flow for campaigns didn’t change, we could not probe on that and tell people to use the dogfood instance, then no set up would be required other than having src cli (and that’s mentioned in the in-app documentation)

**Comment by mrnugget** [comment]
> * or just ask for internal folks?

I would just ask internal folks for now. Easiest to do and will probably yield a bunch of improvements that we want to have before we ask externally.



> tell people to use the dogfood instance,

Then we need to make sure that:

1. Configured token is correct
2. Correct repositories are cloned

**Comment by chrispine** [comment]
Yes, agreed with you both: let's go with internal folks for now, but I do like the idea of using the dogfood instance later as a way to open up our testing to a larger audience. (My concerns there were around how to set it up, as Thorsten said, but also if it would mean that we couldn't have multiple tests going at the same time, and do we need to do cleanup after each test, etc.)

**Comment by mrnugget** [comment]
Update on previous comment: ticket is filed here https://github.com/sourcegraph/sourcegraph/issues/13620 and fixed here https://github.com/sourcegraph/src-cli/pull/300

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by chrispine** [comment]
We got some feedback, so I'm going to close this issue. (I'm going to collate and report on what we found, but that was never part of this issue.)
