### ISSUE TITLE
Create campaigns demo video

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#13150]
We need to create a new marketing demo video for campaigns

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by sqs** [comment]
https://www.youtube.com/watch?v=EfKwKFzOs3E done! Nice job, @mrnugget.
