### ISSUE TITLE
"Manage repos" is not a good title for the external services page

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#13160]
![image](https://user-images.githubusercontent.com/5589410/90697967-7659e100-e234-11ea-9706-c649a01c0155.png)

I find that I often forget which of these two titles takes me to which page. Both sound like they should take you to the "Repository status" page.

A prospect (https://app.hubspot.com/contacts/2762526/company/1748986560) recently had an issue where they tried to add each repo they wanted as a distinct external service connection: https://sourcegraph.slack.com/archives/C07KZF47K/p1597874785447000

**Comment by rrhyne** [comment]
I agree this is very confusing. The menu item and title of the page should be 'Manage code hosts'. It can be addressed as part of @AlicjaSuska's information architecture project.

**Comment by AlicjaSuska** [comment]
Thank you for bringing this up @dadlerj. As per @rrhyne suggestion - I've changed it to 'Manage code hosts' in the documentation for [Information Architecture project](https://docs.google.com/document/d/1bU-tq1yM4cechfAnHXEibkebWzACeFVfaFFXoqGk0mA/edit?usp=sharing).

I've linked this issue to the issue #[11775](https://github.com/sourcegraph/sourcegraph/issues/11775)

**Comment by tistru** [comment]
I would add here that within the Mange Repositories tab, there is a button labeled "add repositories". That is really meant to add a code host and I've encountered a customer who added a few dozen individual repositories on that page from that misinterpretation. I would suggest that button is relabeled "add code host" or something similar

**Comment by AlicjaSuska** [comment]
Thank you @tistru I've added this change to the document as well.

**Comment by quinnkeast** [comment]
Addressing in #13765.
