### ISSUE TITLE
Survey page has no option for a "10" score—only 0–9

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#13162]
Repro: https://sourcegraph.com/survey/

![image](https://user-images.githubusercontent.com/5589410/90707038-7fa27800-e24b-11ea-8073-ed08a3f8876f.png)

**Comment by dadlerj** [comment]
Looks like this was broken in https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/f425fda6e0ad1ef8ba5fdedbf0e755a8c12feec6?visible=465#diff-65a8ca33d45e9864c72af4496b2f06e1

Renovate replaced `new Array(11)` with `_.range(0,10)` which has a different meaning

![image](https://user-images.githubusercontent.com/5589410/90711968-d792ac00-e256-11ea-8904-31c9892a126c.png)

**Comment by felixfbecker** [comment]
As much as I would like to blame the robot, I'm afraid it was me who made the mistake 😅 
A Jest snapshot test would have helped!
