### ISSUE TITLE
Search button doesn't perform new search, loads https://sourcegraph.com/search? instead

### ISSUE THREAD

**Issue by Strum355** [sourcegraph/sourcegraph#13179]
- **Sourcegraph version:** Sourcegraph.com, `Version: 71303_2020-08-20_f3e640d` from https://sourcegraph.com/users/Strum355/settings
- **Platform information:** chromium Version 84.0.4147.125

#### Steps to reproduce:

1. Navigate to sourcegraph.com
2. type `repo:sourcegraph/sourcegraph code intel` (arbitrary) in the search bar and hit enter/click search button
3. In the new view, click the blue search icon (having changed search bar content or not)

#### Expected behavior:
New search with search bar content is performed

#### Actual behavior:
https://sourcegraph.com/search? loads instead. Hitting enter in the search bar behaves as expected

@mrnugget has a recording from when we discovered it in a zoom call

**Comment by mrnugget** [comment]
cc @sourcegraph/search and @sourcegraph/web since I'm not sure who owns this

**Comment by felixfbecker** [comment]
@sourcegraph/search :)

**Comment by limitedmage** [comment]
Looks like this was introduced with #12972, I'll investigate and try to find a fix.
