### ISSUE TITLE
Do not re-execute campaign spec steps when the diff is still valid

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#13172]
Something I noticed while playing around with the new `src campaigns apply` command (https://github.com/sourcegraph/src-cli/pull/260).

The src-cli internal cache is busted and the campaign spec steps are re-executed every time something in the `changesetTemplate` changed. I think we should only re-execute the steps when the `steps:` or the `on:` fields change.

That's frustrating when one wants to quickly change something in the campaign (description, changeset template title, etc.).

**Comment by LawnGnome** [comment]
I was deliberately conservative on this, but I agree: we should try to do less work. I'd love it if someone else (with fresher eyes than I) took this on!
