### ISSUE TITLE
codeintel: Investigate lsif-go memory issues

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#13184]
A [customer](https://sourcegraph.atlassian.net/jira/servicedesk/projects/SG/queues/custom/1/SG-327) has reported that the lsif-go v1.0.0 release is using more memory than previous version and is crashing on an index machine with 12GB.

This should be investigated to see where the increase came from and determine if we can dump some of the excess. This seems like a regression that should be addressed before shipping lsif-go more widely (see https://github.com/sourcegraph/sourcegraph/issues/13015).

**Comment by efritz** [comment]
## A bit of investigation

I added the following to the main function of previous versions to get the maximum in-use allocations during the indexing run. This should be _good enough_ to show if there are major differences in heap usage between versions.

```
var M uint64
var wg sync.WaitGroup
q := make(chan struct{})
wg.Add(1)
go func() {
	defer wg.Done()
	defer func() {
		fmt.Printf("Peak heap: %d MB\n", M)
	}()

	for {
		var m runtime.MemStats
		runtime.ReadMemStats(&m)
		x := m.Alloc / 1024 / 1024
		if x > M {
			M = x
		}

		select {
		case <-q:
			return
		case <-time.After(time.Second / 4):
		}
	}
}()

defer func() {
	close(q)
	wg.Wait()
}()
```

The following results are from running over aws-sdk-go. This repo has 2.7 million lines of code; for contrast, the code for which the 12GB indexer machine was insufficient was only 2.2 million lines.

### v0.10.0:

```
747 package(s), 1759 file(s), 787399 def(s), 14267010 element(s)
Processed in 2m17.565110213s
Peak heap: 4866 MB
```

### v1.0.0:

```
747 package(s), 1759 file(s), 787399 def(s), 14263096 element(s)
Processed in 24.406575579s
Peak heap: 5324 MB
```

There is an increase in memory allocations between v0.10.0 and v1.0.0, but I'm not sure why there's a 7GB discrepancy between these results and the error report. Will need to look into it a bit more deeply.

**Comment by pyaesone1933** [comment]
#!/bin/bash
set -o errexit -o nounset -o pipefail
command -v shellcheck > /dev/null && shellcheck "$0"

function print_usage() {
  echo "Usage: $0 NEW_VERSION"
  echo ""
  echo "e.g. $0 0.8.0"
}

if [ "$#" -ne 1 ]; then
    print_usage
    exit 1
fi

# Check repo
SCRIPT_DIR="$(realpath "$(dirname "$0")")"
if [[ "$(realpath "$SCRIPT_DIR/..")" != "$(pwd)" ]]; then
  echo "Script must be called from the repo root"
  exit 2
fi

# Ensure repo is not dirty
CHANGES_IN_REPO=$(git status --porcelain)
if [[ -n "$CHANGES_IN_REPO" ]]; then
    echo "Repository is dirty. Showing 'git status' and 'git --no-pager diff' for debugging now:"
    git status && git --no-pager diff
    exit 3
fi

NEW="$1"
OLD=$(sed -n -e 's/^version[[:space:]]*=[[:space:]]*"\(.*\)"/\1/p' packages/std/Cargo.toml)
echo "Updating old version $OLD to new version $NEW ..."

FILES_MODIFIED=()

for package_dir in packages/*/; do
  CARGO_TOML="$package_dir/Cargo.toml"
  sed -i '' -e "s/version[[:space:]]*=[[:space:]]*\"$OLD\"/version = \"$NEW\"/" "$CARGO_TOML"
  FILES_MODIFIED+=("$CARGO_TOML")
done

cargo +nightly build
FILES_MODIFIED+=("Cargo.lock")

for contract_dir in contracts/*/; do
  CARGO_TOML="$contract_dir/Cargo.toml"
  CARGO_LOCK="$contract_dir/Cargo.lock"

  sed -i '' -e "s/version[[:space:]]*=[[:space:]]*\"$OLD\"/version = \"$NEW\"/" "$CARGO_TOML"
  (cd "$contract_dir" && cargo build)

  FILES_MODIFIED+=("$CARGO_TOML" "$CARGO_LOCK")
done

echo "Staging ${FILES_MODIFIED[*]} ..."
git add "${FILES_MODIFIED[@]}"
git commit -m "Set version: $NEW"

**Comment by efritz** [comment]
Resolved https://sourcegraph.atlassian.net/jira/servicedesk/projects/SG/queues/custom/1/SG-327 by release of lsif-go v1.1.1-v1.1.4.
