### ISSUE TITLE
Design campaign empty states

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#13187]
Empty states need to be designed for the following pages/states:

* Campaigns / no campaigns exist
* Campaign preview / no change sets exist
* Campaign close / no change sets will be altered

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
