### ISSUE TITLE
"Go to definition" goes to parallel function

### ISSUE THREAD

**Issue by kidsil** [sourcegraph/sourcegraph#1319]
- **Sourcegraph version:** v18.12.8.13
- **Platform information:** Ubuntu 16.04

#### Steps to reproduce:

1. Go to https://github.com/ethereum/go-ethereum/blob/master/eth/api.go#L171
2. Hover over "ExportChain"
3. Click on "Go to definition" 

#### Expected behavior:
Either no "Go to definition" link, or different text, such as Go to Struct definition.

#### Actual behavior:
Goes to another function with the same name:
https://github.com/ethereum/go-ethereum/blob/master/cmd/utils/cmd.go#L191:6

**Comment by sqs** [comment]
This is fixed because Go precise code intel now takes precedence over basic code intel
