### ISSUE TITLE
Repo-updater component always outputs debug logs

### ISSUE THREAD

**Issue by christinelovett** [sourcegraph/sourcegraph#13191]
https://app.hubspot.com/contacts/2762526/company/1712883009
https://sourcegraph.atlassian.net/jira/servicedesk/projects/SG/queues/custom/1/SG-313

We deploy sourcegraph to kubernetes, similar to https://github.com/sourcegraph/deploy-sourcegraph
One component of this deployment, is repo-updater https://github.com/sourcegraph/sourcegraph/tree/master/cmd/repo-updater

This depends on a log library log15 https://github.com/inconshreveable/log15 which:

1. Logs all levels by default
2. Logs non-info levels to stderr

This means that repo-updater always writes its debug-level logs to stderr
A side effect of this is that when sending logs from our k8s deployment to stackdriver, all the debug messages are logged with 'ERROR' severity, since they appear on stderr and stackdriver has no other way to get insight into the severity.
This causes our logging dashboards to show 100,000s of errors each day.

There are two solutions that would work really well for us either seperately or together, with the first being the easiest to implement:

1. Allow configuring log level for repo-updater via a flag (so we can suppress debug output in our deployment, and generally save on logging expenses)
2. Use structured (json) logging, with a valid severity field (which stackdriver and other logging systems can parse) (https://cloud.google.com/run/docs/logging#special-fields)

**Comment by slimsag** [comment]
@uwedeportivo this also happens on `frontend` for some reason in pure docker deployment where we do not explicitly set `SRC_LOG_LVL` it seems to default to `dbug` and it is a BIG problem for some customers, see e.g. https://github.com/sourcegraph/customer/issues/49

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
ok, so i have a test cluster up and i have been modifying the repo-updater log level, and it respects it

```
      containers:
      - env:
          - name: SRC_LOG_LEVEL
            value: info
        image: index.docker.io/sourcegraph/repo-updater:insiders@sha256:b262571482910fe0a3b2f85d551d10bbe96b38b30cab908e01a4aa7b1d794acd
```

it's true: the default level if nothing is set explicitly is debug, which is super verbose for repo-updater.

i'm reluctant to change the default at this point but setting the env var works. i'll see if i can add the standard severity field to the structured logging to let the customer filter by it as they suggested. i'll also look at frontend and the other processes. they all go to our shared log.Init() (which is super nice).

i'll look at the other deployment types.

**Comment by uwedeportivo** [comment]
here's documentation on how they can change it: https://docs.sourcegraph.com/admin/observability#logs

**Comment by uwedeportivo** [comment]
i'm going to consult with the eng team to see if it makes sense to change the default: https://github.com/sourcegraph/sourcegraph/blob/main/internal/env/env.go#L31

**Comment by uwedeportivo** [comment]
we can also maybe land https://github.com/sourcegraph/sourcegraph/pull/14259 and give the customer option number 2

**Comment by uwedeportivo** [comment]
i tested frontend and the log level is respected there as well. i will check why pure docker doesn't pass that along

**Comment by uwedeportivo** [comment]
@christinelovett please re-open if you feel these changes don't address it and ping me. i'm going to close it for now (the only other thing we could do is not make dbug the default log level).

**Comment by christinelovett** [comment]
@uwedeportivo awesome I'll let them know, thank you :-)
