### ISSUE TITLE
Identifier popup is finicky

### ISSUE THREAD

**Issue by nictuku** [sourcegraph/sourcegraph#132]
- sourcegraph.com
- Chrome Version 68.0.3440.106 (Official Build) (64-bit), OSX 10.13.6

#### Steps to reproduce:

1. Go here: https://sourcegraph.com/github.com/src-d/go-git/-/blob/options.go#L325
2. Hover the mouse over an identifier (e.g: `All` attribute inside `CommitOptions`)
3. Quickly move the mouse towards the "Find references" button

#### Expected: 
- Popup should remain in place and let me click on find references

#### Actual:
- Sometimes the popup disappear, probably because it thinks the mouse isn't hovering over the identifier anymore

I'll post a link to a video with the repro in a follow-up update.

**Comment by felixfbecker** [comment]
Filed this in our library that adds the hovers: https://github.com/sourcegraph/codeintellify/issues/48

We currently show the hover while the mouse is either over the token, or the hover itself. So if you don't "leave" the token while moving the mouse to the button, or first move it on the hover, it should work reliably. Alternatively clicking the token will pin the hover.

We should add a small delay here before hiding the tooltip.

**Comment by nictuku** [comment]
Here's a video: https://photos.app.goo.gl/TnmuYnd5Henjrk3e8.

Hope it helps.

**Comment by sqs** [comment]
Closing in favor of https://github.com/sourcegraph/codeintellify/issues/48, which is an issue on the more relevant repo
