### ISSUE TITLE
What is the purpose of quickGitserverRepo?

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#1320]
What do these lines accomplish? Does calling IsRepoCloneable have a side effect?

https://github.com/sourcegraph/sourcegraph/blob/07054656c7662374534cf8a2b83b36aad97e0a6d/cmd/frontend/backend/repos.go#L98-L105

Despite the documentation, RepoLookup is always called.

cc @tsenart

**Comment by keegancsmith** [comment]
https://github.com/sourcegraph/enterprise/commit/6311657bdd90e14c0fc5d0dd65c603a9fb954e21

Looks like we do this to avoid depleting our Github API rate limit (isRepoCloneable just does a git ls-remote which is not subject to the same API limits).

**Comment by tsenart** [comment]
But `RepoLookup`, at least in the code path @nicksnyder shared, is always called.

**Comment by keegancsmith** [comment]
The benefit is to fail early for non-cloneable URLs. The commit message:

> frontend: do not incur GitHub API call for repos that are not cloneable
> Most of our rate limit is used looking up nonexistent repos (like
> github.com/settings/profile) or private repos from browser ext users.

**Comment by nicksnyder** [comment]
Ah, that makes sense. Just a fail fast case.
