### ISSUE TITLE
Navigation to definition unavailable from occurrence/usage of symbol in source 

### ISSUE THREAD

**Issue by poojaj-tech** [sourcegraph/sourcegraph#13200]
#### Steps to reproduce:
Customer feedback:
> I'm not finding navigation from an occurrence/usage of a symbol in the source to its definition. It may be something that either we didn't set up or I just haven't figured out, but either way it would be awesome if in my casual usage I experienced it.

Company: https://app.hubspot.com/contacts/2762526/company/693777177/
Customer: https://app.hubspot.com/contacts/2762526/contact/15781901/

**Comment by efritz** [comment]
Can you try to get additional information here? Do they _never_ see definitions of usages? What languages? Are they seeing this behavior only on things defined by third-party libraries, or their own code as well?

**Comment by macraig** [comment]
Reached out to user, waiting for their feedback

**Comment by macraig** [comment]
Closing for lack of feedback from user. Will re-open if we can get more context.
