### ISSUE TITLE
Investigate effort for Bazel integration

### ISSUE THREAD

**Issue by aidaeology** [sourcegraph/sourcegraph#13202]
Many prospects and customers (such as ....) rely on Bazel broadly across their organization to build and manage their projects, and we need to build an integration that can support the more complex monorepos structures and workflows. Bazel support also opens the door to two other important features: remote development and automated refactoring. 

This spike is for researching the development effort required for building integration with code intelligence tools.  To start we will limit the scope of this work to basic code intelligence. Specifically we need to know how Bazel transitive dependencies/dependents info can be used to provide cross-repository/package references in basic code intel.

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by christinelovett** [comment]
Requested by:

- https://app.hubspot.com/contacts/2762526/company/1249201106

- https://app.hubspot.com/contacts/2762526/company/1832711947
