### ISSUE TITLE
Multiple hover and definition requests sent for the same position and blocked on the last result

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#1321]
Go to any pinned position, e.g. https://sourcegraph.com/github.com/angular/angular/-/blob/packages/http/src/http.ts#L116:3

This should only sent a _single_ hover and a _single_ definition request to the extension. However, it sends multiple. lang-typescript just forwards these to the server without deduplication, and sometimes the server is busy and takes long to answer the second request. The UI does not show the hover the _second_ hover and definition requests have returned:

![image](https://user-images.githubusercontent.com/10532611/49750654-ca64a200-fcab-11e8-8c09-e38f695641eb.png)

Note how in this scenario, the first request came in at 18:18:58, and the hover could have been shown at 18:19:08, instead it didn't appear until 18:19:43 (ideally the server would be super responsive always but this is simply not always the reality - we should not overload it from our side).

I suspect this is a bug in codeintellify that wasn't noticed before because we used to cache all requests. Extensions can't really do this anymore if they want to work in editors too, and they shouldn't have to add code for this.

cc @sqs @lguychard 	@ijsnow

**Comment by chrismwendt** [comment]
Fixing in https://github.com/sourcegraph/codeintellify/pull/92

**Comment by chrismwendt** [comment]
This bug seems to have reappeared (see https://github.com/sourcegraph/sourcegraph-typescript/pull/246)

**Comment by felixfbecker** [comment]
@sourcegraph/code-intel it would be nice if this bug was fixed so that PRs like https://github.com/sourcegraph/sourcegraph-basic-code-intel/pull/198/files don't take extra effort to maintain all the workarounds 🙂

**Comment by aidaeology** [comment]
Closing as we no longer support LSP
