### ISSUE TITLE
lguychard/string-references extensions breaks all hovers with "You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable."

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#13223]
1. Enable https://sourcegraph.com/extensions/lguychard/string-references
2. Hover anywhere, e.g. https://sourcegraph.com/github.com/sourcegraph/codeintellify/-/blob/src/helpers.ts

Error:

`You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.`

![image](https://user-images.githubusercontent.com/10532611/90897059-ea2af380-e3c4-11ea-84f3-3b340204d098.png)

The problem in the extension host here is that a single extension's error can prevent any other hover from being shown (the TypeScript extension's hover specifically).

**Comment by y120** [comment]
Similarly, this is broken for lguychard/configurable-references.

This also manifests when hovering over code on Github when using the browser extension.
