### ISSUE TITLE
Rendering of Directory Children With Single Folder Is Confusing

### ISSUE THREAD

**Issue by tistru** [sourcegraph/sourcegraph#13231]
- **Sourcegraph version:** 3.18
- **Platform information:**

We got a complaint this AM that the way Sourcegraph 3.18 renders directories with only directory children is confusing.

For example:
https://sourcegraph.com/github.com/vanadium/core/-/tree/x

Looks like it contains lots of files / directories.

Which is an empty dir with only a ref folder.
https://github.com/vanadium/core/tree/master/x

This issue was first presented in a JIRA: https://sourcegraph.atlassian.net/jira/servicedesk/projects/SG/queues/custom/1/SG-328

#### Steps to reproduce:

1. Examine directory with single folder containing around 10 files and sub folders
2. Observe that at the single folder level when viewed within the Sourcegraph web UI, the contents of the folder are displayed along with the top level folder (see links above).

**Comment by dadlerj** [comment]
@tistru you should let the customer know that the fix has been merged and will be available in the next monthly release (version 3.20)

**Comment by tistru** [comment]
Sure I'm inform the customer. Thanks for the update and for resolving this isuse.
