### ISSUE TITLE
Consolidate site configuration for individual repo listing and blacklisting

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#1324]
### Background

Today there are multiple scattered ways to list or blacklist specific individual repos across all site configuration:

#### Listing

1. `repos.list`: https://docs.sourcegraph.com/admin/site_config/all#repos-list-array
1. `github.repos`: https://docs.sourcegraph.com/admin/site_config/all#repos-array
1. `github.repositorySearch` with `repo: XXX` search term: https://docs.sourcegraph.com/admin/site_config/all#repositoryquery-array
1. `gitlab.projectQuery`: https://docs.sourcegraph.com/admin/site_config/all#projectquery-array
1. `phabricator.repos`: https://docs.sourcegraph.com/admin/site_config/all#phabricator-array

#### Blacklisting

1. `gitolite.blacklist`: https://docs.sourcegraph.com/admin/site_config/all#blacklist-string

### Proposal

As part of #914, this issue proposes to consolidate the site configuration for listing and blacklisting individual repositories across all code hosts. These would be the changes involved:

1. Introduce new top-level `repos.blacklist`
1. Deprecate `phabricator.repos` in favour of `repos.list`
1. Deprecate `github.repos` in favour of `repos.list`
1. Deprecate `gitolite.blacklist` in favour of `repos.blacklist`

### Compatibility

Each of these changes requires documentation of the deprecated configuration to be marked appropriately and for it to point to the supported configuration options `repos.list` and `repos.blacklist`.

In order to reduce friction for administrators that upgrade their instances, a straight-forward CLI migration tool (e.g `sourcegraph config upgrade "gitolite.repos"`), or an in-app `Upgrade config` button can be developed.

**Comment by tsenart** [comment]
PTAL @nicksnyder @sqs

**Comment by slimsag** [comment]
SGTM at first glance; what are the semantics of `repos.blacklist`? Can we specify a query of repos to ignore with that? What syntax would it use?

About compatibility -> after #965 we can develop automatic config migrations since all config will be stored in the DB. i.e. read config from DB on startup -> apply some migration -> write config back to DB

**Comment by tsenart** [comment]
> what are the semantics of repos.blacklist? Can we specify a query of repos to ignore with that?

Symmetrically with `repos.list`, we can specify a list of repos that should be blacklisted from whatever selection of repos resulted from the aggregate code host's configuration via things like `github.repositoryQuery`.

If a repo is in both `repos.list` and `repos.blacklist`, `repos.blacklist` takes precedence, and it won't be active.

> What syntax would it use?

```json
{
    "repos.list": ["https://github.com/sourcegraph/sourcegraph"],
    "repos.blacklist: ["https://github.com/sourcegraph/sourcegraph"]
}
```

> About compatibility -> after #965 we can develop automatic config migrations since all config will be stored in the DB. i.e. read config from DB on startup -> apply some migration -> write config back to DB

Awesome!

**Comment by tsenart** [comment]
Addendum: I thought about adding support for regex based blacklist with a `repos.blacklist_regex`, but perhaps we leave that to another time.

**Comment by slimsag** [comment]
It's actually not clear to me, but what I was trying to get at is that it seemed to me like the old API supported some sort of fuzzy blacklisting based on a repo query or something, whereas this new API you are proposing (without regex) would not. Any clue if the existing API does support fuzzy blacklisting? (API == config option)

**Comment by tsenart** [comment]
@slimsag: I linked to all relevant configuration options I could find. Which one of those are you referring to?

**Comment by slimsag** [comment]
I am thinking of the ones you have already listed (though there is one for BitBucket you missed: [`excludePersonalRepositories`](https://docs.sourcegraph.com/admin/site_config/all#excludepersonalrepositories-boolean))

For example, users may be relying on `gitolite.blacklist`'s regexp ability to filter out repositories, which could not translate into a pure list-only approach ``repos.blacklist` which you are proposing here. Does that make sense?

**Comment by tsenart** [comment]
Ah! Yes, that makes total sense. I hadn’t noticed that `gitolite.blacklist` was a regular expression.

So then, what do you think of adding `repos.blacklist_regex` as well?

**Comment by slimsag** [comment]
SGTM, but I would suggest finding an all-in-one approach that could satisfy both requirements using the same top-level field, something like:

```json
"repos.blacklist": [
    "github.com/exact/match",
    "regexp:github.com/.*/match",
]
```

**Comment by nicksnyder** [comment]
Each code host config is stored separately in the database, so global inclusions and exclusions would not be a good user experience because users would need to configure this in two different places in the UI.

As a general principal, we want a single external service configuration to completely specify what repos that connection owns (which is also convenient for the syncing logic in repo-updater).  I don't think we want to add `repos.blacklist` and I think we should remove `repos.list`.

In an ideal world, `github.repositorySearch` and `gitlab.projectQuery` probably should have the same name (`repositorySearch` seems the better of the two).

**Comment by tsenart** [comment]
> Each code host config is stored separately in the database, so global inclusions and exclusions would not be a good user experience because users would need to configure this in two different places in the UI.

That's news to me. Can you please point me to these two different places in the UI? I agree this proposal isn't great under those conditions.

> As a general principal, we want a single external service configuration to completely specify what repos that connection owns (which is also convenient for the syncing logic in repo-updater). I don't think we want to add repos.blacklist and I think we should remove repos.list.

Then instead of top-level configuration, we ought to make these consistent within each connection: `{github|gitlab|bitbucket|phabricator|gitolite}.{repos|blacklist}`.

Since not every code host supports search queries, what do you think of this @nicksnyder?

**Comment by slimsag** [comment]
> I think that's a better user experience but I'd like to know why you think it's better. Do you also find it's better UX? Is this a pattern we use elsewhere? Other reasons?

1. I think it is a better UX.
2. I strongly prefer less top-level fields, because they pollute our configuration (which is rapidly growing). Another option is:

```
repos.blacklist: {
    values: ["repo/a", "repo/b"],
    regex: "foo/.*",
}
```

**Comment by sqs** [comment]
@nicksnyder the reason for GitLab config having projectQuery vs repositorySearch is that they’re called projects in GitLab, and we prefer to use the names from the external service. As for query vs search, those should be standardized ideally.

**Comment by nicksnyder** [comment]
> Can you please point me to these two different places in the UI?

This is the external services UI that I have been working on as part of https://github.com/sourcegraph/sourcegraph/issues/914 (e.g. https://github.com/sourcegraph/sourcegraph/pull/1103) that is currently hidden behind a feature flag. You can test list locally by enabling the feature flag in your site config

```
"experimentalFeatures": {
    "externalServices": "enabled"
  },
```

> we ought to make these consistent within each connection

All else equal, consistency is good, but code hosts may have material differences in their capabilities that motivates the configuration to be different. Each code host should have a configuration that makes sense to users of that code host and uses terms that the users of that code host would be familiar with. When we have shareable concepts between code hosts we should try to be consistent and reuse terms when appropriate.

It isn't a priority to backfill features to other code hosts (e.g. it isn't a problem if certain code hosts don't support blacklists or a repos list).




There is also code host specific terminology that we wish to maintain as @sqs mentioned above.

**Comment by tsenart** [comment]
> This is the external services UI that I have been working on as part of #914 (e.g. #1103) that is currently hidden behind a feature flag. You can test list locally by enabling the feature flag in your site config

Thanks, that helps.

> Each code host should have a configuration that makes sense to users of that code host and uses terms that the users of that code host would be familiar with. When we have shareable concepts between code hosts we should try to be consistent and reuse terms when appropriate.

From our sync the other day, I was under the impression that selecting and, to a lesser degree, blacklisting individual repos was something we cared to support. Today, only `github` has `.repos` and only `.gitolite` has `.blacklist`.

> There is also code host specific terminology that we wish to maintain as @sqs mentioned above.

What I proposed is that we make this capability consistent across code hosts with `.repos` and `.blacklist`. We wouldn't touch `gitlab.projectQuery` nor `github.repositorySearch`.

But we can defer doing this to after #914, and simply remove the top-level `repos.list` for now.

How does that sound?

**Comment by nicksnyder** [comment]
Sounds good.

Random docs that I stumbled across that will need to be updated/deleted:
- https://docs.sourcegraph.com/integration/bitbucket_server
- https://docs.sourcegraph.com/admin/repo/add_from_git_repository

**Comment by sqs** [comment]
Closing this because we want each external service's configuration to use the terms and concepts specific to that external service (e.g., GitHub) and not ALSO have "external service-independent" concepts (which add complexity for users). I don't know of any use cases that need an external service-independent repo enumeration or blacklist.

**Comment by sqs** [comment]
Note that I specifically think it is not important to **consolidate/unify** the repo enumeration and blacklist concept **among all external service configs**. It is still potentially valuable to have fields like these in the config for specific external services (although not for any urgent customer needs; I see #2649 is adding it for GitHub, which is not necessary for any product/customer priorities I am aware of, but perhaps it solves problems you're facing), such as:

- `github.repos` (I wish it were named `github.repositories` btw, but that's not worth changing)
- `github.excludeRepositories`
- `gitlab.projects`
- `gitlab.excludeProjects`

Not all of these exist and I'm not saying we need to add them right now, but when the need comes to have  enumeration and blacklists, they should be done independently in the way that makes most sense for each external service config (eg calling them "projects" not "repositories" for GitLab).
