### ISSUE TITLE
VimL highlighting

### ISSUE THREAD

**Issue by lf-** [sourcegraph/sourcegraph#13258]
#### Feature request description

Highlighting for VimL (`.vim`) files

#### Is your feature request related to a problem? If so, please describe.

It's fatiguing to browse codebases for Vim plugins while having (learning disability I have) because syntax highlighting is not available.

#### Describe alternatives you've considered.

Browse it on GitHub? Their search is no good though!

#### Additional context

Sample file that is unpleasant to read:

https://sourcegraph.com/github.com/neoclide/coc.nvim@702ae48/-/blob/autoload/coc/util.vim

**Comment by rvantonder** [comment]
Aaand done #19282
