### ISSUE TITLE
TypeScript code intel gives only `any` type on some things

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#1325]
Not sure if I should file this here or somewhere else.

This only happens on specific symbols, but they appear to have concrete types in the code. Likely _not_ a regression.

1. Visit https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/shared/src/actions/SearchFiltersContainer.tsx#L43
2. Hover over `getContributions`, wait until it loads, it displays `any` type.
3. Walk up the field accessors `contribution`, `services`, `extensionsController`, `this.props` are all `any` types for some reason?
4. If you go to the actual definition of `this.props.extensionsController`, it has a concrete type.

Expected: TS langserver picks up the type since it is concrete.

**Comment by felixfbecker** [comment]
Seems like tsserver is not considering the files in node_modules, as if it didn't notice they were added through the dependency installation.

**Comment by felixfbecker** [comment]
This should not happen anymore, I made it so we restart tsserver after dependency installation. It can be configured with a setting. Please reopen if you still see it!
