### ISSUE TITLE
TypeScript code intel takes a long time to load (e.g. 32s); must wait again after page refresh

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#1326]
Not sure if I should file this here or somewhere else.

1. Visit https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/shared/src/actions/SearchFiltersContainer.tsx#L43
2. Hover over `getContributions`
3. Wait 32s for it to load.
4. Refresh the page -> you must wait 32s again.

My main complaint here is that after page refresh I have to wait this time again. What this means for me as a user is that whenever I navigate to a repo I feel like I can't rely on TS code intel to quickly respond (I very often use new tabs / don't just use a single Sourcegraph browser tab). I suspect I will not be the only user in this boat.

---

The lightstep trace indicates almost all of that time is spent during `yarn install`:

https://app.lightstep.com/sourcegraph-prod/trace?span_guid=067b24994b223d1b&at_micros=1544479949698948

![image](https://user-images.githubusercontent.com/3173176/49765041-0e44b080-fc86-11e8-98bd-7fc149f78149.png)

Is there anything we can do caching wise so that if I myself or someone else has already viewed the repo the `yarn install` results are reused?

**Comment by felixfbecker** [comment]
I am open for suggestions but I can't think of a way beyond the caching we already do

**Comment by gbrik** [comment]
@slimsag I'm closing this as it seems resolved, please let me know otherwise.
