### ISSUE TITLE
Create extensions for opening in additional editors - Atom, IntelliJ and Sublime Text

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#13270]
Let's agree on the next steps regarding extensions for opening the file in the editor.

### Currently

Right now we enable opening in the editor by:
- using **vs-code** extension
<img width="373" alt="Screenshot 2020-08-24 at 08 26 09" src="https://user-images.githubusercontent.com/20326070/91011070-ede89100-e5e3-11ea-92b8-4386f523e524.png">

- using **open-in-editor** extension developed recently by @limitedmage as the onboarding task. User can configure their preferred editor in settings.
<img width="375" alt="Screenshot 2020-08-24 at 08 26 19" src="https://user-images.githubusercontent.com/20326070/91011083-f2ad4500-e5e3-11ea-8fef-761e57ee725e.png">
 
### Proposition
1. **Develop separate extensions for each supported editor**
In Sourcegraph we list VS Code, Atom, IntelliJ, and Sublime Text.

<img width="194" alt="Screenshot 2020-08-24 at 08 46 46" src="https://user-images.githubusercontent.com/20326070/91012432-63556100-e5e6-11ea-8781-c183f4b6ee62.png">

**Reasoning**
- It is easier to enable the extension then configure settings for open-in-editor extension
- Better visibility of those extensions in the extensions registry page
- in open-in-editor extension, the user chooses only one preferred editor. Many developers use more than one editor and we should accommodate their needs.

2. **Present open-in-editor extension as an option for adding an editor that is not supported yet**

Users who use the editor from outside the supported editors' list can configure it in the open-in-editor extension. For now, I think that configuring one additional editor is enough, let's see how many people use this option. If it turns out to be necessary in the future, maybe we can develop this extension further to let users add more than one additional editor.

@christinaforney @felixfbecker @tjkandala

**Comment by felixfbecker** [comment]
I propose we make it four extensions:
- `open-in-sublime`
- `open-in-intellij`
- `open-in-atom`
- ~`vscode-extras`~ rename to `open-in-vscode`

Each would only work for one editor (we can adapt the code from the `open-in-editor` extension).
Repos should be the name of the extension prefixed with `sourcegraph-` (convention for our extensions).

**Comment by AlicjaSuska** [comment]
Sounds good @felixfbecker! When do you think it can be done?

**Comment by AlicjaSuska** [comment]
@tjkandala @felixfbecker I've added new editors to [extensions list design](https://www.figma.com/file/7Ek89vyDoqlGhCn3wyS40J/11872-Extensions-discoverability-Final-review?node-id=86%3A648). Also, logos are available for export.

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by felixfbecker** [comment]
@tjkandala implemented and released these 🚀
