### ISSUE TITLE
ci: build and pin tool apks in CI for release

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#13297]
Some of our docker images (`sourcegraph/server`, `gitserver`), etc. rely on external tools provided alpine APKs. Examples include `git`, `postgres`, and `redis`. We've recently experienced severe issues cutting release when the versions of these tools are updated in the alpine repositories. 

We can solve this by building the APKs for eaceh of the external tools at the exact version that we want. We can create `sourcegraph/alpine-builder-*` docker images that compile these APKs and store them under a known directory (like `/target`). People can trigger builds by pushing to `docker-image-build/[IMAGE]/`[VERSION]` branches on sourcegraph/sourcegraph. This will build and push a `sourcegraph/[IMAGE]:[VERSION]` docker image. 

Docker images that need these APKs can use `COPY --from=sourcegraph/alpine-builder-*:VERSION` statements in their dockerfile to fetch these APKS. 

https://github.com/sourcegraph/sourcegraph/pull/13158 (WIP) is an implementation of this PR.

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
