### ISSUE TITLE
Update all deployments to use Postgres 13

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#13300]
`sourcegraph/server` currently uses Postgres 11.5, which is not available in Alpine 3.12. To workaround this we have compiled Postgres 11.5 for Alpine 3.12: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/server/Dockerfile#L44-51

This will in the future cause ongoing maintenance pain and we should update `sourcegraph/server` to use Postgres 13. Someone will need to look at how to perform that migration (I believe we did this in the past for postgres 10 -> 11?)

Additionally, there are security and performance improvements in Postgres 13.

@sourcegraph/cloud is this something you would be interested in performing?

**Comment by tsenart** [comment]
@daxmc99: I think this is too much for this cycle so moving to Backlog (based on the estimates of the remaining security work).

**Comment by tsenart** [comment]
Update title from 12 to 13. I'm filing a separate issue to start collecting Postgres and Redis versions in pings so that we can change our minimum supported versions without fear.

**Comment by daxmc99** [comment]
I would like to amend this to upgrading all shipped versions of Postgres to 13. 

I will need to modify our shipped `postgresql.conf` to support `pg_stat_statements` as part of #15029 .  This typically involves a database restart and it would be easiest to ship an image with this enabled by default.

**Comment by keegancsmith** [comment]
FYI just because it isn't clear here part of making this happen is making our database automatically upgrade. @tsenart did a lot of work around this 2 years ago, and likely has the most context on pointing the owner in the right direction. Alternatively, we don't treat sourcegraph/server the same as we did before, so it may not be as involved.

**Comment by efritz** [comment]
We now require 12 as a minimum version.

**Comment by keegancsmith** [comment]
How are upgrades being handled by customer installations?

**Comment by efritz** [comment]
If they're using our `sourcegraph/postgres` image it will go 11.4->12.6 automatically. There are release notices, upgrade instructions for external databases, an explanatory blog post, and CSE teams have been in contact with enterprise customers.

If using RDS, Aurora, CloudSQL, etc, and are still on < 12, they will have to migrate it themselves.

**Comment by keegancsmith** [comment]
> If they're using our `sourcegraph/postgres` image it will go 11.4->12.6 automatically

Cool. So the image will automatically migrate/pgupgrade the data from 11.4 to 12.6?

**Comment by efritz** [comment]
Yep, same way we did from 9.6 to 11.4 in the old image: https://github.com/sourcegraph/infrastructure/blob/main/docker-images/postgres-12.6/Dockerfile#L43

**Comment by tsenart** [comment]
@efritz: Glad you were able to reuse that — it took a loooot of effort back then :D

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/cloud-devops - the "team/devops" label was applied to this issue.

**Comment by kalanchan** [comment]
@daxmc99 @rafax do you have any updates to this? Also, can we remove the @sourcegraph/dev-experience label as this is an org wide issue?
