### ISSUE TITLE
Update Kubernetes, Docker Compose deployments to use Postgres 12

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#13301]
We currently are shipping Postgres 11 with our Kubernetes and Docker Compose deployments.

There are security and performance improvements in Postgres 12, we should ship that out of the box.

This will require figuring out the appropriate migration path. Note that in the past for Postgres 9 -> 11 we used a set of automatic migration scripts, which we could probably repurpose for this: https://github.com/sourcegraph/infrastructure/tree/master/docker-images/postgres-11.4/rootfs

NOTE: This does **not** change our minimum supported Postgres version, many customers still use e.g. RDS with older Postgres versions like 9.6. It only changes the version we ship alongside Sourcegraph by default.

**Comment by daxmc99** [comment]
Superseded by https://github.com/sourcegraph/sourcegraph/issues/13300
