### ISSUE TITLE
Highlight usages of variable name under cursor

### ISSUE THREAD

**Issue by lf-** [sourcegraph/sourcegraph#13308]
#### Feature request description

Something similar to what nvim-coc is doing here (and many other IDEs do), where it is putting a subtle highlight on the occurrences of the keyword under the cursor:
![image](https://user-images.githubusercontent.com/6652840/91108427-eb5e5980-e62c-11ea-9170-6a2735d1573c.png)

In Sourcegraph this could be implemented on mouse over, since locals typically do not result in popups.

#### Is your feature request related to a problem? If so, please describe.

I have a learning disability/brain quirk that makes it hard to find usages of keywords without editor assistance, and this feature is necessary to make Sourcegraph accessible for people like me.

#### Describe alternatives you've considered.

Double clicking the keyword and hitting ctrl-f. This works but sometimes causes the page to jump around and is not ideal.

**Comment by eseliger** [comment]
@sourcegraph/code-intel I think this is done, please confirm :)

**Comment by efritz** [comment]
This does already exist, but only for commits with LSIF data.

**Comment by scalabilitysolved** [comment]
If this exists for precise code intel do we consider this resolved @macraig ?

**Comment by Strum355** [comment]
My personal 2c on the topic would be to not have it for the _current_ search-based code intel impl at the least.

 I already get some weird highlighting sometimes that are wrong (I think notably from lsif-tsc and lsif-clang), which are quite off-putting when trying to review code. Making it a _feature_ would be less desirable than it being a bug. Especially for locals.

**Comment by lf-** [comment]
> @lf- FYI, as described, this would also highlight the state in the comment above the line, and the string content in the line above that. Do you still feel that would be enough signal over the additional noise?

I often do # or * in vim with highlight search on to do this, which has the same issue. Equally the workaround of ctrl-f has this as well. It's still very useful to be able to see it, and if it gets distracting, the cursor can be moved off the word.

**Comment by christinelovett** [comment]
Customer request: https://app.hubspot.com/contacts/2762526/company/557692623

**Comment by macraig** [comment]
This feature request is now tracked in [Productboard](https://sourcegraph.productboard.com/feature-board/1825051-code-intel/features/8233846/detail).
