### ISSUE TITLE
Break up very large or complex functions in search code

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#13311]
The following large functions are candidates for refactors that break them up into smaller pieces. Please edit this issue if you come across functions that seem like good candidates. Comment if you have an opinion on the items.

- [ ] [resolveRepositories](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/search.go#L730-942). About 200 lines of code, but complex. One way could be to break up the  `Repos.List`, version context setup, and resolving revs separately.

**Comment by camdencheek** [comment]
Closing as done. I spent a while refactoring `ResolveRepositories` a while ago, and it's still complex, but more approachable.

**Comment by keegancsmith** [comment]
I also spent time refactoring it for search jobs. Its mostly split up these days :)
