### ISSUE TITLE
Single Repo Not Cloning On Docker Compose (50+ other repos on same server clone fine) 

### ISSUE THREAD

**Issue by tistru** [sourcegraph/sourcegraph#13332]
- **Sourcegraph version:** 3.18
- **Deployment:** Docker Compose

A user reports that he could connect to all 50+ repos but one on his gitlab server. He tried to remove and re-add the project to the Sourcegraph instance but the project was stuck on "cloning queued" for >60 mins. He also confirmed that he can clone the repo in question locally using a personal access token and a "git clone" command. 

When attempting the clone, the `docker-compose logs --tail=100 | grep <REPO NAME>` output mentions the repo as:
 "not cloneable: exit status 128 (output follows)\n\nremote: HTTP Basic: Access denied\nfatal: Authentication failed for '<redacted>/'

This error occurs with the same access token mentioned above that worked for the local cloning test.

Full details can be found in the JIRA: https://sourcegraph.atlassian.net/jira/servicedesk/projects/SG/queues/custom/1/SG-320

**Comment by tsenart** [comment]
@tistru, @dadlerj: Going forward, please assign me directly, otherwise I won't receive notifications.

I don't have access to this JIRA project. Can you include the customer's Hubspot link in the GitHub issue?

**Comment by tistru** [comment]
Hey @tsenart. Sorry for not updating but this issue has been resolved. Full update below:

Hubspot link for customer: https://app.hubspot.com/contacts/2762526/company/1783614661

From the customer:

> I finally found the root cause and I can now also sync the final repo.  The problem was indeed that repository access level setting. The matching property in Gitlab GUI is 
> 
> Goto Project -> Settings -> General
> 
> Expand "Visibility, project features, permissions"
> 
> Change “Repository Access” from "Only Project Members" to “Everyone with Access”
> 
> Would be good to document that somewhere in e.g. a FAQ or as a note in the Gitlab-specific documentation.
> 
> For the record: this is still using the access token and not the alternative SSH approach.

Later @dadlerj updated our docs to incorporate this feedback: 

> I just added this to our docs at https://github.com/sourcegraph/sourcegraph/pull/13771/files to help future users.

**Comment by tsenart** [comment]
Thanks!

**Comment by ryanslade** [comment]
I'm going to remove the milestone as it doesn't make sense for this to show up in the tracking issue anymore
