### ISSUE TITLE
dhall: generate separate yaml files for each "component" instead of one large one

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#13338]
need a wrapper and dhall expressions

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
