### ISSUE TITLE
dhall: create "base" version of records and explicitly import into templating logic

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#13336]
see https://github.com/sourcegraph/sourcegraph/issues/13335

this enables us to protect base and maybe re-use in other deployment targets.

v1: use k8s dhall types
v2: 
  - distill core stuff with a simpler representation (similar to docker compose) that can be specialized for specific deployment
  - define more general types for resources that don't have counterparts in other deployments

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by pecigonzalo** [comment]
Closed as part of the architecture discussion.
