### ISSUE TITLE
Tracking issue: Use CI on sourcegraph.com with Dhall

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#13340]
### Tracked issues

@uwedeportivo: __1.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/14133 

Completed: __1.00d__
- [x] (🏁 380 days ago) https://github.com/sourcegraph/sourcegraph/issues/14132  __1.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by slimsag** [comment]
Update: I won't have time to look into this in 3.21, running behind where I expected to be. Given this I am un-assigning myself.
