### ISSUE TITLE
Prioritize exact filename matches when file extension isn't included

### ISSUE THREAD

**Issue by poojaj-tech** [sourcegraph/sourcegraph#13348]
#### Steps to reproduce:
Customer Feedback

> 
Prioritizes exact filename matches when the extension isn't include more highly, they're frequently at the bottom of results. Including the extension makes them immediately the top result, but should not be necessary.

Company: https://app.hubspot.com/contacts/2762526/company/464956351/
Customer: https://app.hubspot.com/contacts/2762526/contact/25490501/

**Comment by keegancsmith** [comment]
@sourcegraph/search-core Do we have good examples from sourcegraph.com where we could do better here? This issue is a bit light on the details, and since then we have started using ranking more from zoekt.

**Comment by keegancsmith** [comment]
@stefanhengl and I were accidently very mean to @jac and stole his onboarding task by accident last friday. Sorry! https://github.com/sourcegraph/zoekt/pull/349
