### ISSUE TITLE
Hover loads indefinitely

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1334]
With the basic-code-intel extension enabled, hover over `a.position` or `b.position`'s `position` token at https://github.com/sourcegraph/codeintellify/pull/77#discussion_r240263029. The hover loads indefinitely. Here is the devtools console error:

![screenshot from 2018-12-10 20-52-54](https://user-images.githubusercontent.com/1976/49779214-9abe9580-fcbd-11e8-9205-1ec86b24c5d4.png)

**Comment by nicksnyder** [comment]
Update here? Are you still the correct owner for this?

**Comment by sqs** [comment]
Yes, I own basic-code-intel (for now). I just saw this occur again today. I will fix it.

**Comment by sqs** [comment]
This is actually caused by https://github.com/sourcegraph/sourcegraph/issues/1801, which can wait until 3.1. The infinite loading is no longer present now that the codeintellify behavior has changed to not show the loader unless at least one of the actions or hover has returned, so this is not immediately noticeable/annoying.
