### ISSUE TITLE
Multiple message: or author: query fields are implicitly treated as "or"

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#13346]
Although sort of understandable from a usability perspective, this is not the desired semantics for treating whitespace consistently as `and` and will create confusion. We need to be consistent if we treat whitespace as `and`. This behavior is almost certainly a result of the fact that we pass multiple options off to `git` for commits, which treat the options as `or`. 

[example](https://sourcegraph.test:3443/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+type:commit+author:rijnard+author:ryan&patternType=literal)

Relates to https://github.com/sourcegraph/sourcegraph/issues/11865

**Comment by fkling** [comment]
This seems to have been fixed.
