### ISSUE TITLE
TypeScript hover provider never returns

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1335]
At https://sourcegraph.com/github.com/sourcegraph/codeintellify@ce472adbfc6ac8ccf1bf7afbe71f18505ca994ec/-/blob/src/hoverifier.ts#L516, hover over `position` in `b.position`. The hover provider never returns any data (see the lack of a response from the `languageFeatures/$observeHover` call in the devtools console). There are no other errors.

![screenshot from 2018-12-10 20-56-41](https://user-images.githubusercontent.com/1976/49779294-220c0900-fcbe-11e8-8354-805e9009df31.png)

**Comment by sqs** [comment]
It finally started returning, but all types are `any` typed

**Comment by slimsag** [comment]
Sounds related to #1325 and #1326

**Comment by sqs** [comment]
dupe of #1325 and #1326
