### ISSUE TITLE
Implement changes to nav bar

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#13372]
Specification: [Navigation section in Information Architecture document](https://docs.google.com/document/d/1bU-tq1yM4cechfAnHXEibkebWzACeFVfaFFXoqGk0mA/edit#heading=h.9abnbtvc0vh1)
Product issue: #11775
Design: [Figma](https://www.figma.com/file/cT23UcGqbdjdV4H2yxweIu/11775-Map-the-current-information-architecture-Approved?node-id=888%3A1782)
Design owner: @AlicjaSuska 

- [x] Move extensions item from user menu to navbar, add icon
- [x] Always show an avatar, never the username. If we don't have an avatar image URL, show a circle avatar with the initials.
- [x] Change icon of command palette
- [x] Remove explore page (completely)
- [ ] Add 'Sign up' primary button for un-authenticated users
- [ ] Change 'Sign in' button label to 'Log in'. Change button style to secondary.

**Comment by AlicjaSuska** [comment]
Removal of the explore page approved in [#7363](https://github.com/sourcegraph/sourcegraph/pull/7363). This issue also closes #7363.

**Comment by AlicjaSuska** [comment]
Visuals:

<img width="1398" alt="Screenshot 2020-09-14 at 09 34 18" src="https://user-images.githubusercontent.com/20326070/93056995-81eecb00-f66d-11ea-82c1-910d1c451816.png">

[See in Figma](https://www.figma.com/file/cT23UcGqbdjdV4H2yxweIu/11775-Map-the-current-information-architecture-Approved?node-id=98%3A31)

**Comment by Joelkw** [comment]
This issue is on hold because of some ongoing navigation brainstorming work in #14892 .

**Comment by AlicjaSuska** [comment]
@valerybugakov I've updated [designs](https://www.figma.com/file/cT23UcGqbdjdV4H2yxweIu/11775-Map-the-current-information-architecture-Approved?node-id=888%3A1782) based on yesterday's [discussion](https://sourcegraph.slack.com/archives/C01LTKUHRL3/p1614009674002700)
