### ISSUE TITLE
Scroll bar jitter for diff views

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#13393]
Page load triggers jitter:

![scroll-jitter](https://user-images.githubusercontent.com/888624/91371710-96eee180-e7c6-11ea-896a-db4366c0a7ad.gif)

This on Chrome browser. Been like this for a while and now, anyone in a good position to fix this? CC @eseliger @limitedmage @felixfbecker

**Comment by fkling** [comment]
The styles for this page have since changed. I don't think that's an issue anymore.
