### ISSUE TITLE
Slow page loads on Sourcegraph.com sometimes in the middle of the day (US - West coast)

### ISSUE THREAD

**Issue by poojaj-tech** [sourcegraph/sourcegraph#13398]
Sourcegraph.com

#### Steps to reproduce:
 NPS survey feedback from customer:
"The page loads can be slow sometimes in the middle of the day (West coast of the United States). "

Customer: https://app.hubspot.com/contacts/2762526/contact/25498651/

**Comment by tsenart** [comment]
This issue is non-actionable without being able to reproduce it or measure how fast exactly the customer expects it to be. Closing.
