### ISSUE TITLE
Dotcom suggests index on external_id

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#13406]
pg hero suggests adding an index on `external_id` on the repos table.

> CREATE INDEX CONCURRENTLY ON repo (external_id)

**Comment by tsenart** [comment]
@eseliger: Are there specific queries that would be made faster with this index?

**Comment by eseliger** [comment]
Sorry, I haven't looked further. It just was suggested by pgHero when @keegancsmith and I looked into something during a hack session.

**Comment by tsenart** [comment]
Closing for now.
