### ISSUE TITLE
Constant error message popup showing when I hover on any line of code (sourcegraph.com)

### ISSUE THREAD

**Issue by poojaj-tech** [sourcegraph/sourcegraph#13400]
Logged in with my account on Sourcegraph.com

#### Steps to reproduce:
1. Hover on line of code, see error message in popup 
"You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable."
2. Try different files, repos and languages: Java, C, etc.

#### Expected behavior:
Code-intel hover for find references and go to definition

#### Actual behavior:
<img width="805" alt="Screen Shot 2020-08-26 at 9 32 47 PM" src="https://user-images.githubusercontent.com/57463526/91384890-877e9100-e7e4-11ea-917b-1b26cc7d60e0.png">

**Comment by efritz** [comment]
I can't replicate. Is this on a codehost? If so what browser and what version of the sourcegraph extension do you have installed?

**Comment by felixfbecker** [comment]
@AlicjaSuska had this bug too. Do you have this extension enabled? That was the cause for her https://sourcegraph.com/extensions/lguychard/string-references

**Comment by poojaj-tech** [comment]
@felixfbecker thank you, disabling that extension fixed it for me! One note - after disabling it I was still seeing a popup ('Hello world from my first extension!") above the code-intelligence popup that felt like a bug. Disabling the [hello world extension](https://sourcegraph.com/extensions/yevbar/hello-world) fixed it completely.
Context: I randomly enabled a ton of Sourcegraph extensions just for testing recently, that's probably when both these extensions got enabled.
<img width="1648" alt="Screen Shot 2020-08-27 at 12 56 35 PM (2)" src="https://user-images.githubusercontent.com/57463526/91489857-5777d200-e866-11ea-9b67-15aa97857136.png">

**Comment by poojaj-tech** [comment]
@efritz this is on sourcegraph.com for the Google Chrome browser. Closing this issue since disabling the extension Felix mentioned fixed this for me!
