### ISSUE TITLE
Side by side diff view

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#13410]
Requested by: 
- https://app.hubspot.com/contacts/2762526/company/1686989427
- https://app.hubspot.com/contacts/2762526/company/2428850551

We don't currently support this view for diffs, only inline. Generally, with the browser extension, it's easy to use the code host native side by side diff view, but both of these customers use unsupported code hosts (e.g. the first one uses Gerrit).

**Comment by tsenart** [comment]
Needs product / design input.

**Comment by Joelkw** [comment]
Just curious, @dadlerj, if you had to choose between us supporting Gerrit (something eventually the web team might build) so this request was less necessary, or us supporting the diff views so these customers used sourcegraph natively, which would you prefer? I see advantages to having them stay on sourcegraph, I'm just wondering if you think that behavior is easy to change, or if folks are more likely to want to continuing use their code hosts?

**Comment by dadlerj** [comment]
Hm, good question. I don't see these two as perfect tradeoffs—if we support Gerrit, that would make some of the customers who want this capability happy, but not all. If we support this feature, that would be nice for some companies that want the Gerrit browser extension, but not all.

Simply comparing the two projects on their own distinct merits, I definitely see Gerrit support as a higher priority though.

**Comment by Joelkw** [comment]
Perfect, thanks for that info!

**Comment by AlicjaSuska** [comment]
[Design is ready for review](https://www.figma.com/file/VLSswnLheMURkjIVw9uOMS/Side-by-side-diff-view-13410-Review?node-id=246%3A11)

I've prepared two possible scopes of work:
- Minimal: implement split diffs and button to control the mode
- Even better diffs: add line wrapping control, information about the number of files and changes and ability to expand

**Comment by 5h1rU** [comment]
> @5h1rU, can you confirm that you have what you need to start implementing here?

Confirmed
