### ISSUE TITLE
Scala syntax highlighting is really bad

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#1341]
![image](https://user-images.githubusercontent.com/10532611/49819931-e2edbe80-fd76-11e8-939a-ab61d772ba4d.png)

https://sourcegraph.com/github.com/scalameta/metals/-/blob/metals/src/main/scala/scala/meta/metals/Main.scala

**Comment by ggilmore** [comment]
It looks fine with the light theme:

![screen shot 2018-12-11 at 10 02 14 am](https://user-images.githubusercontent.com/9022011/49820107-e019ac00-fd2b-11e8-8b2b-19a9971077e6.png)

**Comment by slimsag** [comment]
yeah our dark theme is less precise than the light theme (which is actually an existing light theme, `Solarized (light)`). The proper fix here would probably be taking the light theme + applying our dark theme colors on top using https://tmtheme-editor.herokuapp.com

**Comment by slimsag** [comment]
Offerring a theme switcher would also help significantly

**Comment by slimsag** [comment]
If anyone strongly wants a fix for this, let me know and I'll prioritize it. Otherwise I will defer it for a while.

**Comment by felixfbecker** [comment]
Ah, so this is a duplicate of https://github.com/sourcegraph/sourcegraph/issues/925.
Personally I am a dark theme user, and I would assume that many of our users are too. This is a really bad instance, the code is almost like plain text, which we should not have in our app. Reading code is at the core of our product and the theme is part of our brand.

@slimsag are there docs how these themes are configured? Maybe if it is just configuration @francisschmaltz could own this.

The colors for our VS Code dark theme (which is perfect) are here: https://github.com/sourcegraph/themes/blob/master/themes/sourcegraph-dark.json
It's all based on our OpenColor color palette.

**Comment by felixfbecker** [comment]
Dark theme has always been something developers expect from any developer tool and is becoming mainstream now with both Mojave and Windows supporting native dark themes.

**Comment by slimsag** [comment]
No docs atm, but you can just take the theme files from https://github.com/slimsag/syntect/tree/master/testdata/Sourcegraph load them into your editor or https://tmTheme-editor.herokuapp.com and then send me a PR and I'll make sure it lands upstream.

**Comment by slimsag** [comment]
Me and Francis chatted and sounds like a theme switcher / override in the user settings is a good idea (albeit probably a separate solution).

**Comment by felixfbecker** [comment]
Just to be clear, I don't want to load a random dark theme from the internet, I want a dark theme that matches our product color palette. Everything else feels out of place.
