### ISSUE TITLE
Single file diff views

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#13411]
Related to #13410 

Requested by:

- https://app.hubspot.com/contacts/2762526/company/1686989427
- https://app.hubspot.com/contacts/2762526/company/2428850551

Both customers are interested in seeing arbitrary diffs (which we already provide), but for a single file at a time (which we do not). We don't have any way to fetch this from the backend or to display it today.

**Comment by tsenart** [comment]
Needs product / design input.

**Comment by christinelovett** [comment]
Customer request: https://app.hubspot.com/contacts/2762526/company/557692623

**Comment by christinelovett** [comment]
@valerybugakov @umpox this is still a large pain point for [customer](https://github.com/sourcegraph/accounts/issues/558) is it possible to prioritize in the near term?

**Comment by pdubroy** [comment]
@christinelovett Do you know whether it's still the case that there is no backend support? And do you know which team would be building that?

**Comment by christinelovett** [comment]
@pdubroy the customer added this note: 

> The developers mentioned to me that they needed an explicit list of commits with the exact commit time when comparing the files.

**Comment by umpox** [comment]
@justdueck My initial thought is that comparing file diff _across_ repositories could be quite a significant piece of work and would require a lot of backend changes. I think it's worth creating a separate issue for that if it's something we want to implement!

**Comment by justdueck** [comment]
Thanks @umpox !

I have a Product Gap filed with the Product team here: https://sourcegraph2020.lightning.force.com/lightning/r/Product_Gap_Submission__c/a1C5b00000AEkFhEAL/view

**Comment by AlicjaSuska** [comment]
[Design](https://www.figma.com/file/u4vJIUP8qfVyfWPyOwF1D5/Single-file-diff-view-%5BREADY-FOR-DEV%5D?node-id=260%3A11) is ready for dev. @umpox

**Comment by benvenker** [comment]
@lguychard there is some thought that this may have some search backend work. Thoughts?

**Comment by umpox** [comment]
Adding additional context so we know the current state of this issue:

Currently the backend can return a diff between _all_ files changed between two commits. We need the backend to support returning a diff on a _single_  file changed between two commits.

I posted this in #dev-chat ([link](https://sourcegraph.slack.com/archives/C07KZF47K/p1638872214482900))

> Do we have any way of fetching a diff for a single file? I was playing around with [this query](https://sourcegraph.com/api/console#%7B%22query%22%3A%22%7B%20%20%5Cn%20%20repository(name%3A%20%5C%22github.com%2Fsourcegraph%2Fsourcegraph%5C%22)%20%7B%5Cn%20%20%20%20comparison(base%3A%20%5C%224832bf49d0a93f39a26cef5eb108735e26818c28%5C%22%2C%20head%3A%20%5C%22b96c3562814ef9aec74fecbbf73d240bf30a1f94%5C%22)%20%7B%5Cn%20%20%20%20%20%20fileDiffs(first%3A%2010)%20%7B%5Cn%20%20%20%20%20%20%20%20nodes%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20oldPath%5Cn%20%20%5Ct%5Ct%5Ct%5CtnewPath%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20totalCount%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22operationName%22%3A%22RepositoryComparisonDiff%22%7D), but didn’t see anything that would support this.

@eseliger Replied:

> I think the current backend can only do all files in a commit. It won't be super hard to build though if we needed it, I think. The file diffs are already implemented so we just need to feed it with git diff data

@dan-mckean Investigated if this would be something that @sourcegraph/repo-management should do, but thinks it is more aligned with the search team ([link](https://sourcegraph.slack.com/archives/C02EDAQAJQZ/p1638957774314900?thread_ts=1638892142.313400&cid=C02EDAQAJQZ)).

It would be helpful if @sourcegraph/search-core could investigate if this backend work would be possible and how much effort it work take.

**Comment by tsenart** [comment]
> It would be helpful if https://github.com/orgs/sourcegraph/teams/search-core could investigate if this backend work would be possible and how much effort it work take.

I don't expect this to be a lot of work, maybe 1 or 2 days including reviews and deployment. Can you file an issue? Maybe I can slot this in next week.

**Comment by tsenart** [comment]
I ended up not being able to look into this. Sorry it fell through the cracks. I don't think we'll be able to prioritise it now though unfortunately. I'm putting @varungandhi-src in CC since he worked on diff related things recently (I can't remember the details).

**Comment by taylorsperry** [comment]
Hey, @macraig I [asked about this in #search](https://sourcegraph.slack.com/archives/CHEKCRWKV/p1654279433647509) and it sounds like Code Intel is the right team to address Tom's backend questions. Could you please take a look? Thanks!

**Comment by macraig** [comment]
Hi @taylorsperry, this is currently owned by Frontend Platform afaik

**Comment by camdencheek** [comment]
@benvenker, that product gap was specifically for cross-repo diffs. This is definitely doable, and it should be fairly straightforward to update the [fileDiffs](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@25d676d7413d503d59699c4db84d15dd4d933245/-/blob/cmd/frontend/graphqlbackend/schema.graphql?L3005-3005) GraphQL endpoint to filter the diff to a specific path.

However, as @macraig said, this page is owned by Frontend Platform, not Search 🙂

**Comment by taylorsperry** [comment]
Thanks, @camdencheek. Totally agree that this is an issue for FPT, just trying to understand the level of backend work and whether or we need some support to address it. I'll bring it back to FPT to discuss.

**Comment by camdencheek** [comment]
@taylorsperry No need to keep shuffling this around. Turns out the backend work was super easy and makes our GraphQL API generally better, so I just went ahead and [did it](https://github.com/sourcegraph/sourcegraph/pull/36866).

**Comment by lrhacker** [comment]
Split this issue into #41891, #41892, and #41896 so the work is easier to estimate and progress is easier to track.

**Comment by philipp-spiess** [comment]
I’m going to reopen this umbrella ticket so we have a tracking issue for the feature.
