### ISSUE TITLE
Raw API does not set Content-Type to properly for archives

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#1343]
When requesting a tar archive with `Accept: application/x-tar`, I would expect the response `Content-Type` to be `application/x-tar`. Instead, it is `application/octet-stream`.
Currently checking the content type is my only option to detect auth errors.

**Comment by keegancsmith** [comment]
@slimsag I can take this issue and the other raw api issue off your hands for 3.0 if you like https://github.com/sourcegraph/sourcegraph/issues/1248

**Comment by slimsag** [comment]
Awesome, all yours! :)
