### ISSUE TITLE
Repo-updater gets stuck when an invalid token is added

### ISSUE THREAD

**Issue by asdine** [sourcegraph/sourcegraph#13447]
When a new external service is added with a bad access token, repo-updater gets stuck trying to sync external services using that token.
Fixing this requires deleting the external service and restarting repo-updater.
Context: https://sourcegraph.slack.com/archives/CMBA8F926/p1598615920060100

**Comment by unknwon** [comment]
Possible solution: Once detected 401 from code host, should just halt the process (valid for current all-at-once syncer and per-external-service syncer).

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by tsenart** [comment]
Fixed by #13742.
