### ISSUE TITLE
Show error messages from third-party auth on sign-in page instead of on a plain text, white background plain HTML page

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#13442]
Part of [RFC 213](https://docs.google.com/document/d/1HoGEL9tgi92ru2Gel681dNEfhM0zcqFIFcZauQQwdD4/edit#heading=h.a4g02kh1btiz)
Product issue: #12695
Design owner: @quinnkeast 

Handle error messages related to third party auth (e.g. failed authentication) on sign in page, instead of plain text error response.

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
