### ISSUE TITLE
Implement UI changes on sign-in/sign-up form

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#13443]
Part of [RFC 213](https://docs.google.com/document/d/1HoGEL9tgi92ru2Gel681dNEfhM0zcqFIFcZauQQwdD4/edit#heading=h.a4g02kh1btiz)
Product issue: #12695
Design: [Figma](https://www.figma.com/file/L5ZdNBGAnHQQUGGmp6tdQS/%2312695-%E2%80%93-Sign-in-%2F-Out-UX-%5BReview%5D?node-id=1%3A101)
Design owner: @quinnkeast 

- [x] Remove the navbar altogether from the sign in and sign up flows.
- [ ] Always autofocus on the first input field on sign in and sign up pages.
- [ ] Reorganize elements to improve hierarchy of actions (e.g. “New to Sourcegraph? Sign up” relocated to end of sign in form).
- [ ] Rewrite error messages for stronger UX copy.
- [ ] Replace “Sign in” button label with spinner while submitting.
- [ ] Add labels to form elements.
- [ ] Expose password requirements on signup form.
- [ ] Show all errors inline on signup form.
- [ ] Adjust subtitle copy on Cloud to articulate value proposition / suggest what action will come next after signing up.
- [x] Change “Sourcegraph.com” to “Sourcegraph Cloud” to align language.
- [ ] Refine the overall visual appearance of the sign in / sign up flow.

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by tjkandala** [comment]
Notes:
- logo should only link back to search in sourcegraphdotcommode
