### ISSUE TITLE
Remove sign out page

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#13440]
Part of [RFC 213](https://docs.google.com/document/d/1HoGEL9tgi92ru2Gel681dNEfhM0zcqFIFcZauQQwdD4/edit#heading=h.6tqw1u2wi1b0)
Product issue: #12695
Design owner: @quinnkeast 

After signing out, the user should be redirected to the home page or the login page (if the home page is not accessible for signed-out users).

**Comment by felixfbecker** [comment]
@quinnkeast I just realized that whether we should remove the sign out page or not may depend on the outcome of whether/how we sign out users out of auth proxies ([this discussion](https://docs.google.com/document/d/1HoGEL9tgi92ru2Gel681dNEfhM0zcqFIFcZauQQwdD4/edit?disco=AAAAKLRAwM8)), since that is currently how we allow users to do that. Could you find a solution with @unknwon and @chayim and report back once a decision has been made? I'll wait with this task until then and focus on the other UI changes

**Comment by quinnkeast** [comment]
For visibility, this discussion is underway!

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by quinnkeast** [comment]
Decision was [recorded in the RFC](https://docs.google.com/document/d/1HoGEL9tgi92ru2Gel681dNEfhM0zcqFIFcZauQQwdD4/edit?disco=AAAAKJ98EMo), but realized it wasn't also recorded here. 

>... the resolution is to
>a) remove the sign-out page (redirect to home page instead)
>b) not sign users out of auth proxies

@christinaforney for visibility.

**Comment by felixfbecker** [comment]
This was done
