### ISSUE TITLE
Docker Compose install docs still refer to 3.18.0-1

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#13464]
https://docs.sourcegraph.com/admin/install/docker-compose

![image](https://user-images.githubusercontent.com/5589410/91616453-91b2a380-e93a-11ea-83ef-6f4e11dea3ec.png)

**Comment by dadlerj** [comment]
Tagging folks who might be involved :). Feel free to reassign if appropriate!

**Comment by slimsag** [comment]
Thanks, it actually is updated/fixed just not on the 3.19 branch. https://docs.sourcegraph.com/@main/

I have a feeling we're going to see a lot more of this now that we're versioning our docs.
