### ISSUE TITLE
GitHub OAuth certificate signed by unknown authority

### ISSUE THREAD

**Issue by brightgong** [sourcegraph/sourcegraph#13461]
#### Question description
src: https://github.com/sourcegraph/deploy-sourcegraph-docker
version: 3.19.1

when login sourcegraph with github sso it return error as below:
Post "https://github.xxx.corp/login/oauth/access_token": x509: certificate signed by unknown authority

and when login to sourcegraph-frontend-0 and sourcegraph-frontend-internal as root, add the ca.pem file into /usr/local/share/ca-certificates and run update-ca-certificates, still not work

and this way once worked with single docker image run but faild when run with docker compose, so pls hlep to let me know how to fix this and thanks so much

**Comment by unknwon** [comment]
Related: https://github.com/sourcegraph/sourcegraph/issues/4652

**Comment by brightgong** [comment]
Hi, thanks for helping resloveing this issue
and i realize the real problom is not from tech side but in doc side, hope teams can update the doc @https://docs.sourcegraph.com/admin/config/site_config#reference to let user know all feature under #schema/site.schema.json# so it will big help to solve most of issues and save your times

**Comment by unknwon** [comment]
> Hi, thanks for helping resloveing this issue
> and i realize the real problom is not from tech side but in doc side, hope teams can update the doc @[docs.sourcegraph.com/admin/config/site_config#reference](https://docs.sourcegraph.com/admin/config/site_config#reference) to let user know all feature under #schema/site.schema.json# so it will big help to solve most of issues and save your times

Ah cool. Thanks for pointing out! It does seem missing many options we have in that page 🤔 Need to investigate.

**Comment by unknwon** [comment]
OK, I see the config option `certificate` is actually mentioned in https://docs.sourcegraph.com/admin/external_service/github, which is not part of site config.
