### ISSUE TITLE
k8s upgrade docs don't list anything for 3.19

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#13468]
https://docs.sourcegraph.com/admin/updates/kubernetes

**Comment by slimsag** [comment]
They do on `main`: https://docs.sourcegraph.com/@main/admin/updates/kubernetes

**Comment by davejrt** [comment]
Docs seem to be complete here

https://docs.sourcegraph.com/admin/updates/kubernetes#3-19
