### ISSUE TITLE
Improve the open-in-editor extension

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#13474]
Here are some changes to improve the UX of the open-in-editor extension developed by @limitedmage 🎉

---

1. 👨‍💻 **Change copy in the alert and add a link to the extension details page**

<img width="475" alt="Screenshot 2020-08-11 at 14 06 13" src="https://user-images.githubusercontent.com/20326070/91643502-0cabb500-ea34-11ea-9a94-8fed794c4368.png">

- Text in the alert could be written in the more human-friendly language. New proposition: 'Add openineditor.basePath to your user settings [keep the existing link] to open files in the editor. Learn more'
- Add 'Learn more' text that links to the [open-in-editor extension details page](https://sourcegraph.com/extensions/sourcegraph/open-in-editor)

<img width="430" alt="New-alert" src="https://user-images.githubusercontent.com/20326070/91643760-6a410100-ea36-11ea-8b56-f805b899232e.png">

[See this design in Figma](https://www.figma.com/file/WpFZczSBx9daMhEW7DYDfz/Untitled?node-id=0%3A1)

----

2. 👨‍💻 **Change the content of the 'Settings' section in the extension description**

To make it easier for the user, let's add ready to copy-paste settings for each editor:

**Settings**

Add openineditor.basePath to your user settings to open files in the editor. Copy one of the following lines depending on the editor you would like to use.

Supported editors:
- vscode (Visual Studio Code): "openineditor.editor": "vscode"
- idea (JetBrains IntelliJ IDEA): "openineditor.editor": "idea"
- sublime Sublime Text, requires a URL handler installed such as this one for macOS)
- custom (requires also setting openineditor.customUrlPattern - see details below)

openineditor.basePath(....) - the rest of the text says the same

--

🤔 **To discuss**: 
- taking into consideration that we are planning to develop separate extensions for supported editors, should we remove them from this extension? @felixfbecker @tjkandala 
- for the standard editors, can we display the editor's icon instead of the extension icon once it is set? @felixfbecker @tjkandala 

----

3. 👨‍💻 **Add Atom to supported editors**

Atom is listed in our [Docs](https://docs.sourcegraph.com/integration/editor) as a supported editor. Can we add it to the extension?

<img width="768" alt="Screenshot 2020-08-29 at 20 25 54" src="https://user-images.githubusercontent.com/20326070/91643710-e1c26080-ea35-11ea-8db5-cce8f646056a.png">

**Comment by AlicjaSuska** [comment]
@quinnkeast @rrhyne do you have any thoughts about the proposed improvements?

**Comment by quinnkeast** [comment]
I'm a big fan of both improvements. Copy/paste lines go a long way to making it simple to do. 

I was originally thinking it'd be good to keep the link to the user settings in the error message, but I **think** the docs are more useful in this case.

**Comment by tjkandala** [comment]
> * taking into consideration that we are planning to develop separate extensions for supported editors, should we remove them from this extension? @felixfbecker @tjkandala

Sounds good to me! 

> * for the standard editors, can we display the editor's icon instead of the extension icon once it is set? @felixfbecker @tjkandala

What would the icon be before it is set? I was under the impression that the extension icon would be the editor icon.

**Comment by AlicjaSuska** [comment]
@tjkandala before the prefered editor is set, we need a generic icon. Currently, we're using the temporary icon:

<img width="62" alt="Screenshot 2020-09-10 at 14 14 14" src="https://user-images.githubusercontent.com/20326070/92727804-0096f000-f370-11ea-93a7-2241d7d56a15.png">

It would be great if we can change it to:
<img width="200" alt="Screenshot 2020-09-10 at 14 13 28" src="https://user-images.githubusercontent.com/20326070/92727824-07256780-f370-11ea-89b5-bd9a8f8f37bf.png">

[Figma](https://www.figma.com/file/vr6vyV5Vs55wq2DocyRZ9m/12843-Icon-for-Open-in-editor-extension-Review?node-id=0%3A1)

@tjkandala if user adds an editor from outside of our list (not Atom, vs-code, IntelliJ and Sublime), can we still access the logo or the extension will be using the generic icon?

**Comment by tjkandala** [comment]
@AlicjaSuska Right now, icons are specified in the extension manifest (in the `package.json` file). I'm adding the ability to specify dark-theme-friendly icons in 13703. Should we add the ability for extensions to change their icon in application code/at runtime?

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
