### ISSUE TITLE
Investigate creation of Safari browser extension

### ISSUE THREAD

**Issue by marekweb** [sourcegraph/sourcegraph#13499]
Questions that we want to answer:

- What is the level of support in Safari of the WebExtension APIs? Is any WebExtension API support missing for us to implement existing features?
- What work is involved to build and publish a Safari extension?

Resources:

- https://developer.apple.com/news/?id=kuswih5l
- [Safari Web Extensions](https://developer.apple.com/documentation/safariservices/safari_web_extensions)
- [Browser support for WebExtension APIs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs)

Previous discussion:

- #766

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by felixfbecker** [comment]
Closing this in favor of https://github.com/sourcegraph/sourcegraph/issues/766 and https://github.com/sourcegraph/customer/issues/138 assuming the "investigation" is done :)
