### ISSUE TITLE
Vulnerability scans of all insiders containers

### ISSUE THREAD

**Issue by chayim** [sourcegraph/sourcegraph#13551]
This involves setting up vulnerability scans of containers we publish against using insiders tag in dockerhub. One possibility is to deploy sysdig image scanning we quickly enable docker vulnerability scans based on anchore and falco.

**Comment by ElizabethStirling** [comment]
RE: conversation with Chayim, it sounds like we're just going to use sysdig. This should be relatively rapid to deploy, and so shouldn't make this take too long.

**Comment by ElizabethStirling** [comment]
@chayim, moved this to 3.22. Please close it out if it's already finished with PR #14767

**Comment by chayim** [comment]
Marking as complete. The manually run scans have their vulnerabilities shared [here](https://github.com/sourcegraph/security-issues/issues/120) so that I can triage them as part of #14089
