### ISSUE TITLE
Cannot install the Firefox extension at all with Firefox v80

### ISSUE THREAD

**Issue by woopla** [sourcegraph/sourcegraph#13578]
- **Sourcegraph version:** 3.19.1
- **Platform information:** Firefox 80.0

#### Steps to reproduce:

1. Go to https://docs.sourcegraph.com/integration/browser_extension using Firefox v80
2. Click on the [Install Sourcegraph for Firefox](https://storage.googleapis.com/sourcegraph-for-firefox/latest.xpi) link
3. Click on 'Continue to Installation' in the tab that pops up

#### Expected behavior:

The plugin should show up as disabled in the [Firefox extensions config page](about:addons), per the documentation. There it can be enabled.

#### Actual behavior:

Firefox displays an alert box with the message 'Sourcegraph could not be installed because it has a high risk of causing stability or security problems'.

While I could probably work around the problem with setting `extensions.blocklist.enabled` to `false` in `about:config`, I do not want to because it's a larger security risk. It looks like (but I haven't found how to fish that info out) the extension got caught in the Firefox 'hard blocklist'.

**Comment by unknwon** [comment]
Thanks for the feedback!

FYI this is known issue, read more about it here: https://docs.sourcegraph.com/integration/firefox_security

**Comment by woopla** [comment]
@unknwon the reason I filed this ticket is that the documentation is not accurate anymore. The extension _won't_ install, period 😿  I have no 'I know what I'm doing, leave me alone' option. Which I why I believe the extension has been 'hard blocklisted' by Mozilla.

**Comment by seh** [comment]
Yes, I came here for the same reason. I can't find any way so far to skirt Firefox's refusal to enable the plugin. There is no longer a slider switch there that allows me to accept the risk and proceed.

Perhaps we're blocked on #12918.

**Comment by marekweb** [comment]
We've been working on getting this resolved with the help of the add-ons team at Mozilla.

We've addressed the original security concerns, and the add-on is now undergoing a review to get it unblocked.

Thank you for your patience on this issue. I'll share an update here as soon as we have a resolution.

**Comment by felixfbecker** [comment]
The Firefox extension is now unblocked 🎉  
The instructions in our docs should work: https://docs.sourcegraph.com/integration/browser_extension

**Comment by seh** [comment]
See https://github.com/sourcegraph/sourcegraph/issues/13813#issuecomment-724024492.
