### ISSUE TITLE
No code intelligence in browser extension (no errors, no loader) when there is rendered markdown somewhere on the page

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#1359]
![2018-12-12 21 40 11](https://user-images.githubusercontent.com/10532611/49897488-9a0d3700-fe56-11e8-9f4f-d85ae4f2518d.gif)

Sourcegraph URL: https://sourcegraph.com

Background page log:

[dgjhfomjieaadpoljlnidmbgkdffpack-1544647351744.log](https://github.com/sourcegraph/sourcegraph/files/2673454/dgjhfomjieaadpoljlnidmbgkdffpack-1544647351744.log)

Active extensions:

![image](https://user-images.githubusercontent.com/10532611/49897605-f708ed00-fe56-11e8-82e2-eafb766c840e.png)

Version 18.12.12.1816
Chrome

Settings:
```jsonc
{
  // "sourcegraph.url": "http://localhost:3080",
  // "typescript.serverUrl": "ws://localhost:8080",
  // "typescript.langserver.log": "log",
  // "typescript.tsserver.log": "verbose",
  // "typescript.tsserver.env": {
  //   "TSC_WATCHFILE": "UseFsEvents",
  //   "TSC_NONPOLLING_WATCHER": "true",
  // },
  "typescript.npmrc": {
    "//registry.npmjs.org/:_authToken": "redacted"
  },
  "codecov.decorations.lineCoverage": false,
  "extensions": {
    "sourcegraph/logdna": false,
    "sourcegraph/codecov": false,
    "sourcegraph/code-discussions": true,
    "sourcegraph/git-extras": true,
    "sourcegraph/lang-typescript": false,
    "felixfbecker/lang-typescript": true,
    "sqs/sourcegraph-python": false,
  },
  "typescript.accessToken": "redacted",
  "go.accessToken": "redacted",
  "panel.locations.groupByFile": true,
  "basicCodeIntel.enabled": false,
  "discussions.decorations.inline": true,
  "git.blame.lineDecorations": false
  // add settings here (Cmd/Ctrl+Space to see hints)
}
```

https://github.com/sourcegraph/codeintellify/pull/70/files#diff-4a91ad3f5a7ed49f91943e184440a5dd

**Comment by felixfbecker** [comment]
It looks like the extension doesn't activate

**Comment by ijsnow** [comment]
Works for me

**Comment by lguychard** [comment]
Reproduced - .tsx diff view is never detected

![image](https://user-images.githubusercontent.com/1741180/49932529-8a7b0600-fec9-11e8-8764-3a15b6ed2883.png)

**Comment by lguychard** [comment]
Broken by https://github.com/sourcegraph/sourcegraph/pull/1322 - this also matches rendered markdowns in PR comments
