### ISSUE TITLE
Slow git blame performance

### ISSUE THREAD

**Issue by alanhamlett** [sourcegraph/sourcegraph#136]
- **Sourcegraph version:** 2.11.0
- **Platform:** Search

#### Steps to reproduce:

1. view large file in Sourcegraph. For ex: a 597K Ruby file with 16653 lines
2. select a line, and notice the blame annotation takes a long time to load

#### Expected: 
Blame should load in under a second

#### Actual:
Blame takes multiple seconds to load

![sg-slow-git-blame](https://user-images.githubusercontent.com/522344/44929903-77289e00-ad11-11e8-8481-2f9d6aaa9e4d.gif)

**Comment by ijsnow** [comment]
Hi Alan, thanks for reporting and sorry you are experiencing this.

That is certainly slow and that is certainly a large file. Is this inside of a mono repo? For large teams and teams with a lot of or large repositories, we suggest using a [Data Center](https://github.com/sourcegraph/deploy-sourcegraph) deployment. Data center deployments are k8s clusters that can scale as needed and have a lot more nobs to tune for performance. That means the `gitserver` won't have to share computing power with the rest of the Sourcegraph services.

Are you on a Data Center deployment already?

**Comment by alanhamlett** [comment]
> Are you on a Data Center deployment already?

Not using Data Center deployment currently.

When using GitHub website to blame that file it times out, so a few seconds seems understandable now.

![screen shot 2018-08-31 at 11 18 04 am](https://user-images.githubusercontent.com/522344/45052245-224f9500-b03b-11e8-98ae-7e8cb2daa4a7.png)

**Comment by sqs** [comment]
@alanhamlett To establish a baseline for perf: how long does the file take to `git blame` on your local machine?

**Comment by sqs** [comment]
@alanhamlett Friendly followup on the question above. I think you are on vacation right now, so no rush. :smile:

**Comment by eseliger** [comment]
We since implemented streaming blame which addresses most of these cases.
