### ISSUE TITLE
managed-instances: deploy a demo instance

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#13604]
after https://github.com/sourcegraph/sourcegraph/issues/13120 and [related changes](https://github.com/orgs/sourcegraph/projects/83) dogfood will likely become a rather unstable deployment. it might be valuable to add a more stable deployment that actually tracks releases for demo purposes (probably useful for @sourcegraph/customer-engineering)

This could be a good chance to take @slimsag 's extensive [managed instances documentation](https://about.sourcegraph.com/handbook/engineering/distribution/managed) for a spin too, and hopefully won't be too much overhead. I imagine it might work as a mini-testbed to try out changes before changing customer deployments too.

cc @pecigonzalo

**Comment by dadlerj** [comment]
This has actually come up in several recent CE syncs internally—definitely of interest for everyone in CE and sales!

One critical thing is to ensure that it's set up to perform in an ideal way—e.g. no banners warning about alerts, no upgrade notifications, precise code intel, default extensions turned on, etc. The same way we treat Sourcegraph.com, but with fewer repos (to make demo searches less random).

**Comment by slimsag** [comment]
What we use for demos and testing should be separate.

CE and Sales need a proper isolated managed instance treated the same way we treat customer managed instances, while distribution and the rest of engineering need a testbed deployment that can be broken/played around with regularly.

Should be trivial to set these two up. Thoughts on domains?

- demo.sourcegraph.com
- test.sourcegraph.com

**Comment by juliasourceress** [comment]
demo.sourcegraph.com sounds great!

Julia Gilinets
VP Strategic Accounts
323.445.6877
Sourcegraph <https://sourcegraph.com> | @srcgraph
<https://twitter.com/srcgraph>

*"With more code, languages, and systems to integrate than ever before, the
job of the developer is exponentially more difficult than 5-10-15 years
ago. Universal Code Search is the only solution that lets developers stay
on top of this ever-growing complexity by giving them the ability to
search, understand and fix problems across the entire codebase.”*
– Quinn Slack <https://twitter.com/sqs>, CEO and co-founder of Sourcegraph

**Comment by bobheadxi** [comment]
> test.sourcegraph.com

Would this replace k8s.sgdev.org?

**Comment by pecigonzalo** [comment]
I would start with the demo instance, which is required right now by CE and will be a workflow that we will "break" with the new dogfood

**Comment by slimsag** [comment]
> Would this replace k8s.sgdev.org?

No, maybe "managed-dev.sourcegraph.com" would be a better name for the test one - the aim would be to have a "test" deployment we can freely muck around with.

**Comment by bobheadxi** [comment]
This is just waiting on @sourcegraph/customer-engineering followup on a few items ([slack message](https://sourcegraph.slack.com/archives/CU93UDUBV/p1601455070038200)):

1. license for the instance (managed-instances docs indicates that CE will provide)
2. repositories setup (just some public repos on there right now)
3. accounts setup (gsuite auth?)

**Comment by bobheadxi** [comment]
With @slimsag's setup of google auth and license I think we're good to go here!
