### ISSUE TITLE
Cross-repo go-to-definition in browser extension goes to invalid 404 URL with "undefined" in it

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#1360]
Go to https://github.com/sourcegraph/codeintellify/pull/70/files#diff-e60ccdd8766832cee90d293fc00ba7d4R1 and invoke go-to-definition on `Position`.
You get taken to a URL with `undefined` in it that 404s.

The same action on Sourcegraph https://sourcegraph.com/github.com/sourcegraph/codeintellify@636e5b2070bb1eb66feda1d5319d5e9e59f371a9/-/blob/src/hoverifier.test.ts?diff=636e5b2070bb1eb66feda1d5319d5e9e59f371a9&utm_source=chrome-extension#L1:10 navigates to the target correctly.

**Comment by ijsnow** [comment]
Assigning @lguychard as well in case you have time to get to it first. It's likely because someone introduced a breaking change and didn't update this block https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/browser/src/libs/github/code_intelligence.ts#L158-184

**Comment by lguychard** [comment]
Fixed in #1390
