### ISSUE TITLE
The sources json column returned by `listReposQueryFmtstr` should not include tokens

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#13614]
The `listReposQueryFmtstr` https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/repo-updater/repos/store.go#L597 should not contain secret tokens. 

Note: the Sources column has been made read-only and will be removed in https://github.com/sourcegraph/sourcegraph/issues/13401

Other portions of this query such as `metadata` should also be encrypted 

Part of: #12699

**Comment by tsenart** [comment]
Will be done as part of #13851.
