### ISSUE TITLE
Campaign mutations (ApplyCampaign, CloseCampaign) block if there are processing changesets

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#13617]
This ticket serves as a reminder that "this" is a thing that we might or might not need to fix and revisit in the future.

To summarise:
- https://github.com/sourcegraph/sourcegraph/pull/13600 and https://github.com/sourcegraph/sourcegraph/pull/13588 fixed race conditions in `ApplyCampaign` and `CloseCampaign` by cancelling all currently enqueued changesets and waiting for the currently processing ones to finish
- They are a result of https://github.com/sourcegraph/sourcegraph/issues/12827
- But that last ticket is not what it seemed to be, which we found out while I was working on it. I described the findings/decisions here: https://github.com/sourcegraph/sourcegraph/issues/12827#issuecomment-684936536

Result: we fixed existing race conditions by making those calls blocking _if there are currently processing changesets_.

Blocking API calls are not the best thing from a UX perspective, since they can make the product seem unresponsive, especially when it takes longer than, say, 5 seconds?

What are the alternatives? I tried to write some of those down in this comment https://github.com/sourcegraph/sourcegraph/pull/13600#discussion_r482132236 which I'm going to copy here:

> the alternatives [to blocking] would be
> 
> 1. Fail if there are _any_ processing changeset. That doesn't allow you to cancel, for example, an accidental publishing of 200 changesets. You'd need to time your `src campaign apply` call to slip right in between the reconciler working on two changesets.
> 2. Cancel currently processing reconciler processes. I don't think that's possible without adding a direct connection to repo-updater worker processes and leaving behind some weird state when something is canceled. [Addition: Eric Fritz suggested in [this comment](https://github.com/sourcegraph/sourcegraph/pull/13588#issuecomment-685784847) that `LISTEN/INOTIFY` might be a way to cancel currently running workers/reconcilers]
> 3. Cancel all currently enqueued changesets and ignore the processing ones. That leads to the problem described above where we work with inconsistent state in `ApplyCampaign`
> 4. Combination of (3) and (1): Cancel all currently enqueued changesets and fail if there are processing ones (instead of blocking). That seems to be the next-most-feasible solution, but it's also a bit weird, IMHO.
> 
> The analogy I made to @efritz was that of a file transfer: when I hit cancel I want all the files that are currently in memory to be written and then stop. I don't want to get a "can't cancel because some files are in memory" message and I don't want a "cancelled transfer and left files in memory in half-written state". I want to say "stop transfering more files but wait until you wrote all currently in memory files so I have consistent state"

**Comment by malomarrec** [comment]
This ticket has been inactive for a while, and after checking in internally it appears to be outdated. Closing.
If you come across this and think this ticket shouldn't have been close, please reopen and leave a comment so that we can reconsider it!
