### ISSUE TITLE
Race condition due to latency in accessing active window through extensions.

### ISSUE THREAD

**Issue by vanesa** [sourcegraph/sourcegraph#1363]
#### Steps to reproduce:

1. Activate WIP:datadog-metrics extension
2. open: https://sourcegraph.com/github.com/bbc/cops-dd-backup-lambda/-/blob/libs/datadog/dogstatsd/base.py#L151
3. See the following console error:
![image](https://user-images.githubusercontent.com/9110008/49899401-7921f300-fe10-11e8-9781-25f4aebb5117.png)

This issue is also reproduced in localhost if we set a network latency of e.g. 500ms
![image](https://user-images.githubusercontent.com/9110008/49899387-70312180-fe10-11e8-9e1b-f86e845f86a0.png)

#### Expected behavior:
No console error, racy behavior.

#### Actual behavior:
Console error and sometimes the extension decorators disappear.

**Comment by lguychard** [comment]
It looks like the latest version of your extension doesn't have this problem anymore, did you add this check recently? `e.app.activeWindow && t(e.app.activeWindow.visibleViewComponents)` (quoting the minified code here as I don't have access to your extensions' source)

`activeWindow` is typed as `Window | undefined`, so you should always have been checking for its existence anyway, as it may have been legitimately `undefined`. For instance, the configuration observer may emit before any viewComponent is registered (I suspect this was the case here).

Any reason why you're always decorating all `visibleViewComponents`, and not just the textDocument emitted by `onDidOpenTextDocument`?

**Comment by vanesa** [comment]
You should be able to see the extension's code here: https://github.com/sourcegraph/sourcegraph-datadog-metrics
I had published a version of the extension with a workaround so that it wouldn't show the issue, but I republished it without it now, so you should be able to see the error again.

**Comment by lguychard** [comment]
Closing as there's no racy behaviour here: sourcegraph-datadog should explicitly check for possible undefined value of `activeWindow` rather than using non-null assertions (https://github.com/sourcegraph/sourcegraph-datadog-metrics/blob/master/src/datadog-metrics.ts#L36)

**Comment by vanesa** [comment]
This is still happening. Currently working around it by adding a timeout to the decorations:
```setTimeout(() => editor.setDecorations(decorationType, decorations), 200)```

**Comment by sqs** [comment]
I think there is a better workaround now thanks to @lguychard's recent #2071, which added things like [activeWindowChanges](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@b423e8380eedb5b104bda16136569bc74f77eaf3/-/blob/packages/sourcegraph-extension-api/src/sourcegraph.d.ts#L656).

```
combineLatest(
  from(sourcegraph.app.activeWindowChanges),
  new Observable(subscriber => sourcegraph.configuration.subscribe(() => subscriber.next())),
).subscribe(([activeWindow]) => {
  if (activeWindow) {
    // Do something with activeWindow.
  }
})
```

instead of

```
sourcegraph.configuration.subscribe(() => {
    if (sourcegraph.app.activeWindow) {
        decorateEditors(sourcegraph.app.activeWindow.visibleViewComponents)
    }
})
```

**Comment by felixfbecker** [comment]
@vanesa I think you missed @lguychard’s question earlier:

> Any reason why you're always decorating all visibleViewComponents, and not just the textDocument emitted by onDidOpenTextDocument?

As long as the code contains the ! operator it is acessing a property of something that is possibly undefined and it is expected that the code may fail. @vanesa does this issue still happen if you get rid of all ! casts?

**Comment by lguychard** [comment]
The casts were an issue, but regardless the extension used to rely on `onDidOpenTextDocument`, and should be refactored to use `activeWindowChanges` / `activeEditorChanges` to reliably react to changes in the active editor & decorate it.

**Comment by felixfbecker** [comment]
I believe there is no bug in the extension host here - if this issue still happens without any `!` cast, please reopen.
