### ISSUE TITLE
Add Search Relevance/Usefulness Measurement

### ISSUE THREAD

**Issue by tistru** [sourcegraph/sourcegraph#13635]
Request by Customer: https://app.hubspot.com/contacts/2762526/company/554275594

#### Feature request description

- Can sourcegraph incorporate some notion of tracking how long a user spent looking for a particular thing?
- Really like the idea of measuring view time for usefulness or relevance (Search ranking/relevance)

#### Use Case 
- We're trying to come up with a measurable key result for improving developer productivity.
- While surveys are nice, they don't give a great picture as to how something like time-to-ship improves due to codesearch

#### Additional context

- Would equate this to something like "what if google returned all the results but had zero relevance?"
- Would be nice to have some sort of correctness vs usefulness measurement

**Comment by camdencheek** [comment]
Closing since this is no longer relevant. We use the "search success" metric to measure this indirectly now, and use "average distance from top" to measure ranking metrics.
