### ISSUE TITLE
Add custom confirmation popup when enabling the extension

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#13664]
Currently, we use system popups to give permissions when enabling the extension. It may look like a system error message and potentially discourage users from enabling extensions.

Example - Chrome:

<img width="1536" alt="Screenshot 2020-09-07 at 09 45 22" src="https://user-images.githubusercontent.com/20326070/92362841-e13e5f80-f0f0-11ea-9deb-7d323d54debc.png">

Example - Firefox:

<img width="1536" alt="Screenshot 2020-09-07 at 09 46 05" src="https://user-images.githubusercontent.com/20326070/92362829-dd124200-f0f0-11ea-8061-b644e379574b.png">

**Proposition**
Create a custom popup the follows the styles of our app. It would look less suspicious for the user.

<img width="1441" alt="Extensions - Poopup - Light" src="https://user-images.githubusercontent.com/20326070/92363006-1cd92980-f0f1-11ea-9c70-d9d8520ceb4a.png">

[See in Figma](https://www.figma.com/file/7Ek89vyDoqlGhCn3wyS40J/11872-Extensions-discoverability-Final-review?node-id=1124%3A31185)

@christinaforney @sourcegraph/design @tjkandala @felixfbecker

**Comment by quinnkeast** [comment]
I strongly back this: not only are @AlicjaSuska's comments about user perception bang on, but we're almost certain to need to use a dialogue like this more often in the future, and it'd be great to make it a standard pattern now.

**Comment by AlicjaSuska** [comment]
@tjkandala I've created both light and dark themes for the popup. Also, I've added the redlines to make it easier for you :) [See in Figma](https://www.figma.com/file/7Ek89vyDoqlGhCn3wyS40J/11872-Extensions-discoverability-Final-review?node-id=1124%3A31185)

<img width="892" alt="Screenshot 2020-09-11 at 09 46 35" src="https://user-images.githubusercontent.com/20326070/92886307-d6970980-f413-11ea-8f5e-f9f97896496f.png">

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
