### ISSUE TITLE
Generic commit/diff search results should have improved titles

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#1366]
https://sourcegraph.com/search?q=type:commit+abc+r:sourcegraph/sourcegraph

Actual title:

![image](https://user-images.githubusercontent.com/3173176/49901419-fc921300-fe15-11e8-9206-0a7c497e79ce.png)

Expected title (unicode `›` arrow, quotes around commit title):

![image](https://user-images.githubusercontent.com/3173176/49901596-73c7a700-fe16-11e8-9a20-c38189bc5b65.png)

**Comment by nicksnyder** [comment]
@slimsag Is this a design request or is there another reason why you are expecting that output?

**Comment by slimsag** [comment]
It is a regression in the `src` CLI from after @attfarhan merged https://github.com/sourcegraph/src-cli/pull/33#issuecomment-446702533 and also an ugly part of our web UX.
