### ISSUE TITLE
Some extensions need a dark mode variant

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#13666]
Datadog, Sentry, and Erlang extensions need a separate variant for the dark mode to improve their visibility.

**Currently**:
<img width="375" alt="Screenshot 2020-09-07 at 11 19 12" src="https://user-images.githubusercontent.com/20326070/92371566-0c7a7c00-f0fc-11ea-8b1f-2505fd5a0f3d.png">
<img width="372" alt="Screenshot 2020-09-07 at 11 18 58" src="https://user-images.githubusercontent.com/20326070/92371577-0daba900-f0fc-11ea-8f77-e1575526f3c2.png">
<img width="376" alt="Screenshot 2020-09-07 at 11 18 49" src="https://user-images.githubusercontent.com/20326070/92371580-0edcd600-f0fc-11ea-81da-f18d9fdfac2f.png">

**Updated**:
<img width="367" alt="Screenshot 2020-09-07 at 11 21 06" src="https://user-images.githubusercontent.com/20326070/92371706-3f247480-f0fc-11ea-8534-7413dac6ed59.png">
<img width="369" alt="Screenshot 2020-09-07 at 11 21 02" src="https://user-images.githubusercontent.com/20326070/92371709-3fbd0b00-f0fc-11ea-8933-6d7d7443eb84.png">
<img width="371" alt="Screenshot 2020-09-07 at 11 20 53" src="https://user-images.githubusercontent.com/20326070/92371712-40ee3800-f0fc-11ea-9ed3-a99b87bfefb1.png">

Assets available to download from [Figma](https://www.figma.com/file/7Ek89vyDoqlGhCn3wyS40J/11872-Extensions-discoverability-Final-review?node-id=241%3A3794)

@tjkandala can we add it to the extensions registry work?

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
