### ISSUE TITLE
Fuzzy hovers don't work for C#

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#1367]
![image](https://user-images.githubusercontent.com/10532611/49902387-165a4700-fe64-11e8-985d-452d881c9a10.png)

I suspect this is because the heuristics don't recognize the `///` comments. We removed the experimental language server so this would be nice to support through basic codeintel.

https://sourcegraph.com/github.com/nunit/nunit@master/-/blob/src/NUnitFramework/framework/Internal/TestExecutionContext.cs#L51:18

Related https://github.com/sourcegraph/sourcegraph/issues/255

**Comment by sqs** [comment]
This is what I see when clicking on your link, which appears to be correct:

![screenshot from 2019-01-10 20-46-17](https://user-images.githubusercontent.com/1976/51013690-c92bcc80-1518-11e9-88f0-66ece7c10dd6.png)

@felixfbecker 	Can you run the `Basic code intel: Enable fuzzy hovers` action (if you haven't already)?

**Comment by sqs** [comment]
I made it so that hovers are on by default.

**Comment by felixfbecker** [comment]
I am on sourcegraph.com and have the basic code intel extension enabled, and no basic code intel setting in my user settings. That means it should be on, right? But it doesn't appear to be. This is what my command palette shows:

![image](https://user-images.githubusercontent.com/10532611/51076555-4df22400-169a-11e9-8a32-1da33ffa9a98.png)

Ideally fuzzy hovers should not be on for languages with a high-quality language extension, but otherwise on by default.

**Comment by felixfbecker** [comment]
It works when I run the enable command.

**Comment by sqs** [comment]
Fuzzy hovers are hidden automatically if a language extension has a hover
