### ISSUE TITLE
Add link to user research signup to saved search notification emails

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#13673]
To build our pool of user research participants who can help us with research around code monitoring, we'd like to add a simple link to the [end of saved search notification emails](https://github.com/sourcegraph/sourcegraph/blob/main/cmd/query-runner/email.go#L73-L91), like:

>We’re doing research around the future of saved searches. [Sign up to get a sneak preview and share your feedback](https://airtable.com/shrqVVodqnNUGlbHj?prefill_Source=Saved+search+notification)!

The link directs to the Airtable-based signup form.

While we wouldn't see the results for 2-3 months (until folks upgrade), it'd give us a touchpoint to reach users who actually use saved search notifications today and hopefully give us a chance to get them involved.

I can submit a PR for this, but I wanted to put it out for discussion in case there are any thoughts or concerns.

@poojaj-tech for visibility!

**Comment by slimsag** [comment]
Thanks for filing!
