### ISSUE TITLE
Codecov coverage checks taking a long time

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#13695]
On my PR #13680, there are several Codecov checks that seem to be never-ending:

![image](https://user-images.githubusercontent.com/1976/92491876-992e4400-f1a7-11ea-9bff-c620ba8e9ca5.png)

![image](https://user-images.githubusercontent.com/1976/92491902-9f242500-f1a7-11ea-9477-1ec51eb42db4.png)

For example: https://github.com/sourcegraph/sourcegraph/pull/13680/checks?check_run_id=1086125937

**Comment by nicksnyder** [comment]
@pecigonzalo Can you take a look? I don't see any information that is useful to figure out what is failing here. I see multiple commits that are hanging here. These failures don't block anything but they are annoying. If this is flaky now, we can disable for now.

**Comment by jerrode** [comment]
👋 hey y'all. Jerrod from Codecov here. I know this has been quite an annoying one for you. Getting this working for Sourcegraph is definitely a priority for us and we are discussing in our weekly support stand up today. 

We will keep you updated ASAP.

**Comment by pecigonzalo** [comment]
There seems to be a duplicate valid run.
![image](https://user-images.githubusercontent.com/9908105/92504133-82690b00-f202-11ea-81f6-31fa69cbfbaa.png)

**Comment by jerrode** [comment]
Hey @sqs and Sourcegraph team, these multiple comments / hanging status checks seem to be stemming from same underlying problem, which is a timeout in between the Github API and our own web nodes. We are digging in ASAP and making a few changes to timeout behavior to see if we can address underlying issue.

I would note that we still have some other Sourcegraph-specific questions we are trying to answer that are likely disconnected from this timeouts issue (see here: https://github.com/sourcegraph/sourcegraph/issues/12986).

**Comment by pecigonzalo** [comment]
Thanks for the update @jerrode

**Comment by jerrode** [comment]
Moving this to a full incident on our status page: https://status.codecov.io/

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by jerrode** [comment]
Hey Sourcegraph team / @sqs -- just confirming that your Codecov statuses are no longer hanging?

Separately, we are discussing with Github PMs around multiple comments next week.

**Comment by nicksnyder** [comment]
I don't see any recent builds on PRs or on our main branch that are hung, so going to close this. Thanks!
