### ISSUE TITLE
Clicking View Repository button on a GitHub repository root page produces a 404

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#1369]
- **Sourcegraph version:** 25366_2018-12-12_18d9b8a (25366_2018-12-12_18d9b8a)
- **Platform information:** macOS Mojave, Chrome 71.0.3578.80
- **Browser extension:** v18.12.12.1816
#### Steps to reproduce:

1. Go to https://github.com/sourcegraph/docsite
2. Click on the **View Repository** button.

#### Expected behavior:

To be taken to the root repository page

#### Actual behavior:

Taken to Sourcegraph 404 page

**Comment by ijsnow** [comment]
Works for me. Could you try agian? This makes me think that maybe this repo wasn't on Sourcegraph previously.

**Comment by ijsnow** [comment]
What Sourcegraph URL is your browser extension pointed to?

**Comment by ryan-blunden** [comment]
sourcegraph.com. Browser extension version is v18.12.12.1816

**Comment by ijsnow** [comment]
Haven't debugged yet but this seems fishy https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/browser/src/shared/components/OpenOnSourcegraph.tsx#L25

**Comment by beyang** [comment]
This is probably affecting all Chrome ext users, making "View repository" 404 for them. I've reverted #1352 to see if that was the root cause.

**Comment by sqs** [comment]
Thanks. I have a PR to fix it. #1352 was indeed the cause.

**Comment by sqs** [comment]
Fix released and confirmed
