### ISSUE TITLE
Make the browser extension version string deterministic

### ISSUE THREAD

**Issue by marekweb** [sourcegraph/sourcegraph#13716]
When we release a new version of the browser extensions, the release process is:

- push to the `bext/release` branch
- CI runs the build script
- The build script uses the [utc-version](https://www.npmjs.com/package/utc-version) function to generate a version with a timestamp, and puts this version string in the browser-extension manifest.
- CI finishes the build by zipping and publishing the extensions

Because the version string is determined at build time, as a timestamp, this makes the build process non-deterministic (it depends on when the CI runs and it won't produce the exact same output from the same git revision).

By making the version string deterministic, we get some benefits:
- Guarantee that re-building the browser-extensions from the same source code will always result in the same output (relevant #12918)
- Uniquely identify each published version as corresponding to a particular revision in the repository

**Possible issues**

- Whatever the format of the version string, it should not cause confusion with the Sourcegraph instance version number a a user may be running.
- If we need to update a browser-extension's metadata (such as the marketing copy on the directory page), do we need to bump the version number for the directory to accept an update? If so then multiple version strings would refer to the same source code revision (but I don't see a problem with this.)

**Notes**

- The other remaining part of making builds reproducible is covered in #12099 which only affects Firefox
- The final output of the build process (the packaged extension as a zip/xpi file) will not byte-for-byte identical anyway, but this is because the zip format saves filesystem timestamps for the contents. The build is considered deterministic if individually all the files that get zipped are identical.

**Comment by muratsu** [comment]
Reprioritization discussion (retrospective Mar-12) - timestamp version numbers are not ideal but it's not contributing significantly to increasing sourcegraph extension usage

**Comment by ryankscott** [comment]
@muratsu  is this relevant? Have we heard any complaints about this? Otherwise I'd suggest we close.
