### ISSUE TITLE
campaigns: increment minimum src-cli version before 3.20 cut

### ISSUE THREAD

**Issue by LawnGnome** [sourcegraph/sourcegraph#13724]
We need to do this on Monday (2020-09-14).

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by LawnGnome** [comment]
Done in #13815.
