### ISSUE TITLE
Expose raw API to internal services

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#1372]
Fetching an archive from the public endpoint takes multiple seconds. It could be faster if language servers could talk to an internal API endpoint within the node.

This is also needed if the Sourcegraph instance is behind an auth proxy.

- [ ] Expose raw file/archive API (ie mount the raw API http.Handler) (see https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/app/ui/router.go#L294)
- [ ] Update docs for all lang extensions and possibly cluster deploy to mention this and when it is necessary for things to be configured to access the raw API internally vs externally

**Comment by nicksnyder** [comment]
Is this merely a performance optimization?

**Comment by felixfbecker** [comment]
No, as said in the description, this is also needed if the Sourcegraph instance is behind an auth proxy.

**Comment by nicksnyder** [comment]
If this is release blocking for 3.0, please add the release blocking label.

Otherwise, if this isn't going to get done in the next week, please remove it from the 3.0 milestone.

**Comment by felixfbecker** [comment]
@slimsag how much time would this take?

**Comment by nicksnyder** [comment]
Relevant conversation
https://sourcegraph.slack.com/archives/C07KZF47K/p1546899085052100

**Comment by nicksnyder** [comment]
This is a release-blocker for 3.1 (not 3.0).

**Comment by felixfbecker** [comment]
Correction: This *is* a release-blocker for 3.0 because it blocks basically every single customer from using codeintel in 3.0.

**Comment by sqs** [comment]
See https://sourcegraph.slack.com/archives/C07KZF47K/p1547106853121300?thread_ts=1546899085.052100&cid=C07KZF47K.

**Comment by beyang** [comment]
This has been addressed by the documentation sub-headed by "Authentication proxies and firewalls" here:
* https://sourcegraph.com/extensions/sourcegraph/lang-typescript
* https://sourcegraph.com/extensions/sourcegraph/lang-go
* https://sourcegraph.com/extensions/sourcegraph/python

**Comment by felixfbecker** [comment]
How can we test it? Did you manage to set it up on dogfood?

**Comment by beyang** [comment]
Not on dogfood, but with a server instance
