### ISSUE TITLE
Refactor and simplify parser code

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#13754]
Merge the `parser.go` and`literal_parser.go` files. Then there's some duplication of these scanner/parser functions to simplify.

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
