### ISSUE TITLE
Repository permissions from multiple code hosts

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#13750]
Reported by https://app.hubspot.com/contacts/2762526/company/693777200 

This customer is using an external SSO provider for authn (SAML I believe).

They use two GitLab instances, each of which also uses the same SSO provider. Each of these has its own permissions.

They are using the [sudo access token](https://docs.sourcegraph.com/admin/repo/permissions#sudo-access-token) method to enable repo permissions in Sourcegraph for the first of the GitLab instances.

Now, they are wondering if it's possible to add the second instance.

Just so I know, is this possible? Would Sourcegraph accept permissions from both code hosts that apply only to the repos that come from them? Since all three systems (Sourcegraph, GitLab1 and GitLab2) use the same identity provider, theoretically it SEEMS like this should work! We haven't tried to replicate this yet though.

CC @tistru

**Comment by unknwon** [comment]
Repository permissions from multiple code hosts is definitely supported, but not sure about the part "use two GitLab instances, each of which also uses the same SSO provider" (it should work from auditing the code).

Will try to simulate this setup next week.

**Comment by dadlerj** [comment]
Thank you! 

> Repository permissions from multiple code hosts is definitely supported...(it should work from auditing the code).

Just so I know, this would NOT be possible with any other code hosts, right? E.g. with GitLab and GitHub, because GitHub ACLs _only_ work when GitHub is used for authn as well?

**Comment by unknwon** [comment]
> > Repository permissions from multiple code hosts is definitely supported...(it should work from auditing the code).
> 
> Just so I know, this would NOT be possible with any other code hosts, right? E.g. with GitLab and GitHub, because GitHub ACLs _only_ work when GitHub is used for authn as well?

That is correct, the authN provider must provide the "account link" between the code host and the Sourcegraph. Unless they also use the same SSO for the additional GitHub (for your example).

**Comment by unknwon** [comment]
@dadlerj I've set up two GitLab and Keycloak (as the SSO) ([ops log](https://unknwon.io/posts/200915_setup-sourcegraph-gitlab-keycloak/)), and I realize repo permissions are actually not going to work (because the mismatch of the SAML NameID). I start to wondering what's the Sourcegraph version and the SSO software the customer is using?

**Comment by unknwon** [comment]
OK! I found what's missing in my set up, the NameID should be `email`! Otherwise, Keycloak would always generate a different UUID for each client.

Now I can confirm it is working for two GitLab using one SSO, and can correctly sync repo permissions in Sourcegraph.

**Comment by dadlerj** [comment]
Amazing—thank you! This is super useful to know for sure :).

CC @tistru
