### ISSUE TITLE
Design support for user-added public code

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#13765]
For the **Soft launch of indexed search over user added public code** #12699, we're replicating the existing pages for "Manage repositories" and "Repository status" from the site admin into user settings. This is the best way for us to get users started using Sourcegraph with their own code base, which will hopefully lead to more "ah-ha" moments for new users.

However, these existing pages have a fair bit of usability debt. Simply replicating them won't create a great experience for Cloud users adding their own repositories, but we also want to keep a tight scope at this stage. 

The challenge is: how might we improve the baseline experience of adding their public repos without significantly impacting front-end scope for the soft launch?

This means:

- Tightening up the language and terminology.
- Clearly communicating that users can only add public repositories.
- Making the most of the current configuration UI for connecting code hosts.
- Improving content to be clear and actionable.
- Making it predictable what will happen when users remove code host connections.

~I've created annotated [fat-marker-style wireframes](https://basecamp.com/shapeup/1.3-chapter-04#fat-marker-sketches) on Figma that walk through recommendations from a design perspective: ~

~[View on Figma →](https://www.figma.com/file/8cU3v6RWB8kZpJvBglcuMa/Public-repositories-on-Cloud-WIP?node-id=260%3A11)~

~Before I create higher fidelity design artifacts, please share any questions or feedback as comments in Figma! I~

Following review and feedback (thanks!), high fidelity design artifacts are now available on Figma.

[View on Figma →](https://www.figma.com/file/8cU3v6RWB8kZpJvBglcuMa/Public-repositories-on-Cloud-WIP?node-id=364%3A320)

**Thinking ahead:**

User-added public code is a big opportunity space, and there's some great paths we can explore for creating an integrated onboarding flow, better exposing code host connections and repositories in the UI, and groundwork for adding private repos. I suggest we approach this generally like:

1. MVP soft launch in the short term.
2. Explore information architecture and language for code host connections and repositories.
3. Explore adding repos in signup flow.

**Comment by tsenart** [comment]
Reviewed current Figma, thanks for the great work! @ryanslade and @asdine PTAL as well.

**Comment by ryanslade** [comment]
Looks great! I really like all the changes 👍

**Comment by asdine** [comment]
That looks really nice! I can't wait to see this in motion :clap:

**Comment by quinnkeast** [comment]
Based on discussions earlier this week, we're changing our plan a bit. Instead of implementing these changes for the soft launch for the internal team, we're going to instead launch the duplicated interface without making changes. Then, we're going to invest more time in a bigger set of changes that will be more purposeful and sustainable with an eye on users outside of the Sourcegraph team.
