### ISSUE TITLE
Toggles on the extensions registry are higher on the z-axis than the command palette

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#13781]
- **Sourcegraph version:**  Sourcegraph.com
- **Platform information:**  Latest Chrome, Firefox, Safari on Mac OS

#### Steps to reproduce:

1. Log in, go to [extensions registry](https://sourcegraph.com/extensions) 
2. Open command palette
3. Scroll

#### Expected behavior:
The command palette is higher on the z-axis than the extensions registry, covers everything that's below it.

#### Actual behavior: 
Toggles are 'higher' than the command palette. They are visible over it when scrolling. See [Loom recording](https://www.loom.com/share/9d17698f5d374c31b264039cfa86d786) for details.

**Comment by AlicjaSuska** [comment]
@tjkandala would you be able to fix it when working on the command palette?

**Comment by tjkandala** [comment]
Good catch. I had noticed this while working on the command palette, but it seems that the z-index was added due to the link being stretched across the whole card. This can be removed due to the changes to the extension card in RFC 209, so it will be closed by #13699

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
