### ISSUE TITLE
Check state is reported as failed even though all the checks passed

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#13789]
I imported https://github.com/sourcegraph/sourcegraph/pull/13768 into a campaign and am seeing this:

<img width="1306" alt="screenshot_2020-09-14_15 46 39@2x" src="https://user-images.githubusercontent.com/1185253/93093942-90ef7080-f6a1-11ea-87e9-3f24968ff919.png">

But all the checks are passing:

![image](https://user-images.githubusercontent.com/1185253/93093999-a4024080-f6a1-11ea-86ef-9b8025410948.png)

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by mrnugget** [comment]
Looking at the JSON that's dumped into my database, I could find this in the `CheckSuites` of the PR:

![screenshot_2020-09-15_17 28 14@2x](https://user-images.githubusercontent.com/1185253/93231371-f95d5100-f778-11ea-8095-f7bcc33b8be0.png)

Not sure how that makes any sense, though.

**Comment by mrnugget** [comment]
I'm closing this, because I'm reasonably sure that it's a GitHub bug.

The check suite's `conclusion` is `"failure"`:

```
curl -s \
  -H "Accept: application/vnd.github.antiope-preview+json" \
  -H "Authorization: token $GITHUB_TOKEN" \
  https://api.github.com/repos/sourcegraph/sourcegraph/check-suites/1178688272 | jq '{status,conclusion}'
```
```json
{
  "status": "completed",
  "conclusion": "failure"
}
```

But every `check-run` in it is successful:

```
curl -s \
  -H "Accept: application/vnd.github.antiope-preview+json" \
  -H "Authorization: token $GITHUB_TOKEN" \
  https://api.github.com/repos/sourcegraph/sourcegraph/check-suites/1178688272/check-runs | jq '.check_runs[] | {status,conclusion}'
```
```json
{
  "status": "completed",
  "conclusion": "success"
}
```
