### ISSUE TITLE
Enterprise home: Stabilize visual tests due to timestamps

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#13797]
Timestamps are causing instability in the Enterprise Home recent searches panel visual tests, this should be stabilized.

![image](https://user-images.githubusercontent.com/206864/93117494-d006cd00-f673-11ea-89e0-b91bc5ad2d72.png)

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
