### ISSUE TITLE
dogfood-k8s: finalize migration over to new cluster

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#13792]
Move all configuration, licenses, etc from the current k8s.sgdev.org to the new cluster we've set up at https://github.com/sourcegraph/deploy-sourcegraph-dogfood-k8s-2 in `sourcegraph-dogfood`'s `dogfood` cluster.

- [x] Move configuration, license => https://github.com/sourcegraph/sourcegraph/issues/13792#issuecomment-693140150
- [x] Move DNS => https://github.com/sourcegraph/infrastructure/pull/2131
- [x] Update handbook entry => https://github.com/sourcegraph/about/pull/1579
- [x] Tear down old cluster

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by bobheadxi** [comment]
Moved config by hand:

* site config
* repo connections

**Comment by bobheadxi** [comment]
Switch to new deployment is live: https://sourcegraph.slack.com/archives/C0EPTDE9L/p1600531167006800

**Comment by bobheadxi** [comment]
@pecigonzalo the old deployment is gone, and we should be able to close this out right?
