### ISSUE TITLE
Search bar doesn't populate with repo filter

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#13805]
![Screen Recording 2020-09-14 at 07 07 41 PM](https://user-images.githubusercontent.com/754768/93156827-c73ae900-f6bd-11ea-8a91-9f1ee13859ed.gif)

Reproduce:
1. Go here: https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/actions/toolkit%24%40main+startGroup&patternType=literal
2. Click on `export function startGroup` result
3. See filter flash in search bar and then disappear.

Expected repo filter to remain in search bar.

@lguychard can you triage to web or search team?

**Comment by lguychard** [comment]
This would be on search, but I cannot reproduce. Can you still reliably reproduce this?

**Comment by nicksnyder** [comment]
Yes I can reproduce still in an incognito window.

**Comment by lguychard** [comment]
Ha! I have a local repro.

**Comment by lguychard** [comment]
This was introduced by https://github.com/sourcegraph/sourcegraph/commit/09965489e0a8fec0035f8f8352bf7ad0f213f0d0
