### ISSUE TITLE
Slow blank search performance

### ISSUE THREAD

**Issue by krishicks** [sourcegraph/sourcegraph#1381]
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:** macOS 10.14, Firefox 63

#### Steps to reproduce:
1. Go to any repository on sourcegraph.com, e.g. https://sourcegraph.com/github.com/krishicks/yaml-patch
2. Click on the downward-facing triangle button next to the repository name

#### Expected behavior:
Since nothing is typed, nothing (no spinner, or results) is shown.
_or_
Since nothing is typed, 10 random repositories are shown as quickly as results are returned
_or_
Since nothing is typed, the first 10 repositories in alphabetical order are shown as quickly as results are returned when performing a search with a non-empty query (for me, ~175ms).

#### Actual behavior:
The spinner spins for about 9-10 seconds before showing anything, delivering a poor user experience. I wasn't sure if I was supposed to just start typing or not, then 10 seconds later I saw some random results.

Notably, the results are not cached, so each click of the button causes another 9-second request to be made.

It's not clear to me if this is a route towards a DOS; I did not hammer the button enough to find out.

In any event, I think it could be improved to not be a slow (and potentially service-disrupting) query, and also give the user a better experience.

**Comment by sqs** [comment]
Thanks for the report. Yes, this is bad UX on Sourcegraph.com (it is fine on self-hosted instances). We should be able to optimize the queries so that it is very fast. It may be using the more complex regexp matching code path, which is slow in some cases. It should be able to use the fast `LIKE '%foo%'` code path.

**Comment by keegancsmith** [comment]
```
sg=# explain analyze SELECT id, name, description, language, enabled, created_at, updated_at, external_id, external_service_type, external_service_id FROM repo WHERE TRUE AND enabled ORDER BY uri LIMIT 11 OFFSET 0;                                                           QUERY PLAN                                                           
--------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=241091.77..241091.80 rows=11 width=200) (actual time=9742.536..9742.537 rows=11 loops=1)
   ->  Sort  (cost=241091.77..247704.95 rows=2645272 width=200) (actual time=9742.534..9742.535 rows=11 loops=1)
         Sort Key: uri
         Sort Method: top-N heapsort  Memory: 27kB
         ->  Seq Scan on repo  (cost=0.00..182109.72 rows=2645272 width=200) (actual time=0.029..4571.352 rows=2796976 loops=1)
               Filter: enabled
               Rows Removed by Filter: 31
 Planning time: 0.123 ms
 Execution time: 9742.568 ms
(9 rows)
```

The problem here is we are ordering by uri, which is a field we don't even use anymore? I think this was a mistake from when we refactored from uri to name, and this was a condition we missed.

**Comment by keegancsmith** [comment]
@krishicks this fix isn't deployed yet, but will be in the next 24 hours.
