### ISSUE TITLE
Instructions on how to bypass Firefox block don't work anymore

### ISSUE THREAD

**Issue by br3no** [sourcegraph/sourcegraph#13813]
#### Describe the issue
The documentation in https://docs.sourcegraph.com/integration/firefox_security states, that the block can be bypassed by explicitly "re-enabling" the extension in `about:addons`. On Firefox 80.0.1 this is not possible. Tying to install the extension leads to the following message:
![image](https://user-images.githubusercontent.com/30877433/93197689-3c54ff80-f74c-11ea-84e3-942814f272dd.png) 

The extension does not appear in `about:addons`.

It would be nice if you could document how to get the addon to work on Firefox despite the issue with Mozilla.

#### Where is the issue located?
At least on Firefox 80.0.1. Haven't checked older versions.

**Comment by unknwon** [comment]
I think this is essentially the same to https://github.com/sourcegraph/sourcegraph/issues/13578.

**Comment by felixfbecker** [comment]
The Firefox extension is now unblocked 🎉  
The instructions in our docs should work: https://docs.sourcegraph.com/integration/browser_extension

**Comment by seh** [comment]
I'm still unable to install the extension located [here](https://storage.googleapis.com/sourcegraph-for-firefox/latest.xpi). Firefox reports:
> Sourcegraph could not be installed because it has a high risk of causing stability or security problems.

<img width="481" alt="Sourcegraph extension prompt" src="https://user-images.githubusercontent.com/175841/98549067-500e7500-2268-11eb-84b4-89924ec49d7a.png">_

Firefox won't install it, so I can't enable it manually afterward. I tried downloading the XPI file too, and directing Firefox to install it from that file, but the outcome was the same.

**Comment by dbgrigsby** [comment]
I'm still experiencing the same issue as @seh , on the latest version of Firefox (73.0b10 (64-bit))

**Comment by felixfbecker** [comment]
@marekweb did I prematurely close this issue? Is this expected?

**Comment by Syfaro** [comment]
I am now able to install the extension in Firefox 83 and was unable to install it in previous 82.0.x versions.

**Comment by dbgrigsby** [comment]
I am as well!

**Comment by seh** [comment]
It is _so nice_ to have Sourcegraph working again with GitHub. I had years of muscle memory learned that kept leading me to confusion disappointment several times per day. Now my vision returns.
