### ISSUE TITLE
Private registry extension page is broken

### ISSUE THREAD

**Issue by tjkandala** [sourcegraph/sourcegraph#13829]
**Steps to reproduce**

- Copy an extension to a private registry using [src-cli](https://docs.sourcegraph.com/admin/extensions#publish-extensions-to-a-private-extension-registry)
- Search for it in the extension registry 
- Click on the extension name

![Screenshot from 2020-09-15 17-53-50](https://user-images.githubusercontent.com/37420160/93269153-74743680-f77c-11ea-9be1-b680c7bd6cf9.png)

**Comment by tjkandala** [comment]
This happens because [`ExtensionCard`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/web/src/extensions/ExtensionCard.tsx#L73) links to the extension ID _without_ the registry. @sourcegraph/web is there any reason we should keep it this way? It seems like just using the full extension id works for both local and remote extensions.

**Comment by felixfbecker** [comment]
I can't see a reason, this looks like a bug (feel free to go ahead with fixing something like this in the future, no need to first get permission 🙂 )
