### ISSUE TITLE
release blocking e2e test failure: Interactive search mode filter buttons

### ISSUE THREAD

**Issue by davejrt** [sourcegraph/sourcegraph#13830]
When running e2e tests in buildkite the following test results in failure, however when run locally this intermittently passes:

Link to buildkite [here](https://buildkite.com/sourcegraph/e2e/builds/10157#1b1a5565-012c-403f-8184-54b09eb4c739/2737-3133)

**Buildkite**
![image](https://user-images.githubusercontent.com/2067825/93269715-2f003b00-f775-11ea-85df-0e634553acd4.png)

**Local**
![image](https://user-images.githubusercontent.com/2067825/93269683-1bed6b00-f775-11ea-819f-b9a4725a23d4.png)

**Comment by davejrt** [comment]
See https://github.com/sourcegraph/sourcegraph/pull/13831

**Comment by uwedeportivo** [comment]
feel free to assign back to me if necessary. e2e passing is on the required path to an RC build, so i will look at it closely tomorrow
