### ISSUE TITLE
release blocking e2e test failure: Interactive search mode filter dropdown and finite-option filter inputs

### ISSUE THREAD

**Issue by davejrt** [sourcegraph/sourcegraph#13832]
When running e2e tests in buildkite the following test results in intermittent failure

![image](https://user-images.githubusercontent.com/2067825/93270075-edbc5b00-f775-11ea-8155-4d017ee0d8d6.png)

Link to failed run [here](https://buildkite.com/sourcegraph/e2e/builds/10157#1b1a5565-012c-403f-8184-54b09eb4c739/2737-3145)

Link to run without this failure [here](https://buildkite.com/sourcegraph/e2e/builds/10156#a9988587-d03b-453f-9983-a7abcf9d7706)

**Comment by davejrt** [comment]
See https://github.com/sourcegraph/sourcegraph/pull/13831

**Comment by uwedeportivo** [comment]
@attfarhan @limitedmage if one of you could please take a look. something must have moved around a little in the search UI. we are getting 6 more in that area now: https://buildkite.com/sourcegraph/e2e/builds/10160#5edda473-7fb7-4d40-8b97-9e325b2496c6
