### ISSUE TITLE
User documentation: data security policy

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#13855]

**Comment by chayim** [comment]
For anyone wanting to track the policies.  I've taken the approach of creating the document needed with boiler plate, and starting the policy set from where we are today.  

https://docs.google.com/document/d/1sVBHaGLXojcq7zAxJo8D4Fonh4kxA3grtWgzbKoAn-0/

**Comment by unknwon** [comment]
@chayim Has it been live as a handbook page or somewhere in our site (other than the gdoc link)? I would like to take a look!

**Comment by chayim** [comment]
It will be - in fact all policies will be.  For now, they live in here
<https://docs.google.com/document/d/1sVBHaGLXojcq7zAxJo8D4Fonh4kxA3grtWgzbKoAn-0>
- but this is temporary, it's just easier to edit in a word processor.
