### ISSUE TITLE
RFC-214: Repository Settings > Mirroring should not display token in the UI

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#13852]
We currently display the full clone URL (including the token) in the repository **Settings > Mirroring** page, we should stop doing that.

I didn't verify, but it feels like we need to:
1. Find where the backend returns the value of this field in GraphQL.
2. Use `url.Parse` and wipe out the _username_ and _password_ portion, which effectively makes it a normal-looking URL (in a browser address bar).

**Comment by tsenart** [comment]
@unknwon: Took this off your plate (you still have too much).
