### ISSUE TITLE
RFC-214: Transparent encryption and decryption for all tables that contain secrets or tokens

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#13851]
This is a placeholder issue for tracking implementing transparent encryption and decryption for all tables.

TODO:
- [x] secrets: add scanners for transparent encryption and decryption #14191
- [x] Package rename #14213
- [ ] ~~DB migration~~ (@unknwon: Not worth it because extra ephemeral changes need to be made just for DB migration to work)
- [ ] Transparent encryption and decryption for all tables that contain secrets or tokens #14214

**Comment by tsenart** [comment]
How does this issue relate to ##13853?

**Comment by daxmc99** [comment]
This issue tracks the transparent encryption portion and does not involve bootstrapping. When this issue is finished, all secret types will utilize the [secret.StringValue](https://github.com/sourcegraph/sourcegraph/pull/13759/files#diff-e145e71eae067c257a62b871b928ffdeR16) type but there will be no process for existing data to be encrypted.

**Comment by tsenart** [comment]
@daxmc99 and @unknwon: Now that you have agreed on the approach, is there a way to parallelise the remaining work?

**Comment by tsenart** [comment]
@unknwon doesn't have the availability for all the work on his plate. Could @asdine take this on instead?

**Comment by daxmc99** [comment]
This work is expected to be done in #13759. The remaining work is to perform the db migration and validate the `JSONB` to `TEXT` conversions work as expected & to add test to `scanner.go`. I think @unknwon & I have about 1 day left of work here. 

@asdine could also be brought on if that would help. I'm not as experienced with the db migration portion and we have had to work around some triggers.

**Comment by tsenart** [comment]
If there's only 1d of work left, can you adjust the estimate please?
