### ISSUE TITLE
RFC-214: Encrypt secrets in user_external_accounts, external_services, saved_searches and external_service_repos

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#13853]
We need to encrypt existing data in `user_exernal_accounts.{auth_data, account_data}`, `external_services.{config}`, `saved_searches.query` and `external_service_repos.clone_url`.

Prior art: https://github.com/sourcegraph/sourcegraph/pull/13093/files#diff-0d2a8ca7d4bdc94a4127a855a8a814b4R323

TODO:
- [ ] Come up a helper that accepts a table name, and list of columns to encrypt. #14231
- [ ] Have a background worker in repo-updater to identify rows that are not encrypted by the current `primaryKey` (i.e. search rows that do not have expected `keyHash` prefix). This would cover both cases of encryption bootstrap and future key rotation.
- [ ] Have a Prometheus metric to track how many rows are encrypted/unencrypted until we have good UI on this.
- [ ] Decide if `ConfiguredToRotate` is worth keeping given the `Decrypt`/`RotateEncryption` method now does no-op if the ciphertext does not look like being encrypted.

**Comment by tsenart** [comment]
@unknwon and @daxmc99: How can you parallelise the work here, now that you have agreed on the approach?

**Comment by daxmc99** [comment]
Once the code is written to encrypt one table the logic should be generally applicable to several tables.

**Comment by daxmc99** [comment]
For the todo, I'm not sure why the background process should live inside repo-updater? I see we have quite a few "syncer" style processes in there but it is not clear to me why the background table encryption should be there. 

One reason to not put it there is to avoid needing to determine how to transmit keys securely and avoiding any discrepancies due to different keys between present on multiple services.

**Comment by unknwon** [comment]
> For the todo, I'm not sure why the background process should live inside repo-updater? I see we have quite a few "syncer" style processes in there but it is not clear to me why the background table encryption should be there.
> 
> One reason to not put it there is to avoid needing to determine how to transmit keys securely and avoiding any discrepancies due to different keys between present on multiple services.

For context, repo-updater is the only singleton service in our architecture right now, otherwise you would have to deal with leader election or work split.

**Comment by daxmc99** [comment]
### Handoff instructions

Opened a [PR](https://github.com/sourcegraph/sourcegraph/pull/14430) on top of https://github.com/sourcegraph/sourcegraph/pull/14231 to add tests and add code to demonstrate how we could add this to repo-updater. It also contains the full set of tables that need encryption. 

The majority of the remaining work remains in the todo's above. 
Some additional work items: 

- [ ] repo-updater encryption should run in the background ( I looked into the `dbworker` package but I'm not sure if its a good fit here, the store.Store is confusing with the repo-updater Store)
- [ ] Queries should be paginated and not lock the entire tables

**Comment by ryanslade** [comment]
We may also need to encrypt or at least hash the `verification_code` column in the `user_emails` database so that someone who gains read access to our database can't impersonate another user.

**Comment by unknwon** [comment]
We're gonna use Vault.
