### ISSUE TITLE
campaigns: allow users to use their own code host tokens when applying campaigns

### ISSUE THREAD

**Issue by LawnGnome** [sourcegraph/sourcegraph#13862]
Per [RFC 229](https://docs.google.com/document/d/1kDkIFQK9hiezEJrG5TfoGvsBKFKF6B6eUcKejYoX2XI/edit?usp=sharing) (at least until it's split into multiple RFCs), we need to add the ability for users to use their own code host tokens when creating and updating changesets.

This may take the form of using auth tokens as a default if they exist, and/or allowing users to add a token to a setting.

**Comment by unknwon** [comment]
Worth subscribing to https://github.com/sourcegraph/sourcegraph/pull/13759 if user token needs to be stored in database.

**Comment by LawnGnome** [comment]
This is now #14989, #14990, #14991, #14992, #14993, #14994, and #14995. (And probably other issues yet to be dreamed up.)

Closing in favour of those more broken down issues.
