### ISSUE TITLE
Automate Kubernetes cluster QA tests

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#13878]
Today our release process https://github.com/sourcegraph/sourcegraph/issues/13374 indicates you should create a Kubernetes cluster, deploy Sourcegraph on it, run the e2e test initializer on it, and run the regression test suite on it:

>   - [ ] New Sourcegraph Kubernetes cluster:
>     - Run the initializer on a new Sourcegraph Kubernetes cluster.
>     - Run the regression test suite.

There has to be a better way we can reduce the number of manual steps here, maybe using Pulumni or some other form of scripting for this. Let's investigate and find possible opportunities, even if we don't get around to actually implementing them in 3.21.

**Comment by pecigonzalo** [comment]
Isnt this already done by https://github.com/sourcegraph/deploy-sourcegraph/blob/master/.buildkite/integration-test.sh? While its not part of our main pipeline, I believe that does smoke testing.
This is not to say we cant improve that process.

**Comment by slimsag** [comment]
@pecigonzalo No, that doesn't run the e2e regression (QA) tests as the release checklist currently mandates. But that could be a sufficient replacement perhaps, given we run the QA tests against server. https://sourcegraph.slack.com/archives/CJX299FGE/p1603129425002100?thread_ts=1603129247.499700&cid=CJX299FGE

**Comment by pecigonzalo** [comment]
I was misled by the title as it said "smoke tests" which is what I though that repo was running as it just pings endpoints

**Comment by slimsag** [comment]
You're right, the title is misleading. Updating.

**Comment by daxmc99** [comment]
I synced with Uwe and came out with some takeaways:

- Adding additional automation to the release process is likely somewhat self defeating. These tests break often and require human intervention.
- If it can be automated, then it should be run as part of CI (like the docker e2e tests are). Or a subset of the tests could be run to require the break-fix work come release time.
