### ISSUE TITLE
qa: automated sourcegraph/server upgrade test

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#13877]
Today our release process https://github.com/sourcegraph/sourcegraph/issues/13374 indicates we should do a manual test of upgrading Sourcegraph using the server image:

>   - [ ] Upgrade from previous release:
>     - Run the initializer on a Docker container running the last patch version of the previous major/minor release.
>     - Upgrade and run the regression test suite.

We should effectively copy what we did for https://github.com/sourcegraph/deploy-sourcegraph-docker/tree/master/test and have a Vagrant-based test for this that runs in CI.

One challenge here will be figuring out how to denote the "old" and "new" version - will probably have to fetch that info from Git tags?

**Comment by bobheadxi** [comment]
References for self:

* https://github.com/sourcegraph/sourcegraph/blob/main/client/web/src/regression/README.md

**Comment by bobheadxi** [comment]
I've been keeping an eye out for @davejrt 's progress, and I think work on this is pretty closely coupled with the outcomes of his work - see the draft PR at https://github.com/sourcegraph/sourcegraph/pull/14974 . I think it's close-ish, but probably won't make it this sprint, so moving it to the next.

FYI @pecigonzalo
