### ISSUE TITLE
Identify further ways to reduce number of steps needed to complete a release

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#13879]
Our release process is a quite long checklist, e.g.: https://github.com/sourcegraph/sourcegraph/issues/13374

I have filed a number of issues with the lowest-hanging fruit I see to remediate the situation: https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+is%3Aopen+label%3Ateam%2Fdistribution+project%3Asourcegraph%2F90

Once the above has been mostly addressed, we should re-evaluate and identify further ways we can reduce the number of steps needed to complete a release. The outcome of this issue should be more issues detailing those opportunities.

**Comment by bobheadxi** [comment]
https://github.com/sourcegraph/sourcegraph/issues/14242 is one of these
