### ISSUE TITLE
RFC 235: Add code intel postgres container

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#13883]
This is part of [RFC 235: Move LSIF data to Postgres](https://docs.google.com/document/d/1Y9p29hK8xrPUTvBdWqP9uAHDg3JLV-HCaxsbCo9-YHQ).

Update the following environments to configure a new database container, and ensure that the frontend has credentials to the new database. This needs to be done before we change code to read the new variables.

- [x] server environment
- [x] pure docker
- [x] docker-compose environment
- [x] k8s template environment
- [x] configure postgres in cloud environment

This issue must follow https://github.com/sourcegraph/sourcegraph/issues/13912.

**Comment by slimsag** [comment]
pure-docker also needs to be done
