### ISSUE TITLE
RFC 201: Write a JSONC index configuration format parser

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#13892]
This is part of [RFC 201: Auto-indexer build configuration](https://docs.google.com/document/d/1NPQs1s814LZjNXjPuavqC1N7hZR192DNtmSBmAeH9UY).

Write the datatypes for the index configuration as well as unmarshalling routines to convert from JSONC to these types.

**Comment by sqs** [comment]
(In case you missed it: https://sourcegraph.com/github.com/sourcegraph/jsonx is the VS Code JSONC parser ported to Go.)
