### ISSUE TITLE
"Go to definition" mangles repository name

### ISSUE THREAD

**Issue by enisoc** [sourcegraph/sourcegraph#139]
- **Sourcegraph version:** Sourcegraph.com
- **Platform:** Chrome 68

#### Steps to reproduce:

1. Select the symbol `APIResource` on [this line](https://sourcegraph.com/github.com/GoogleCloudPlatform/metacontroller@a55bf371a8090f3abf2abc91d645984152db051a/-/blob/dynamic/discovery/discovery.go#L33) and click "Go to definition".

#### Expected: 

Should link to the file `pkg/apis/meta/v1/types.go` in repository `github.com/kubernetes/apimachinery`.

#### Actual:

Links to the non-existent file `machinery/pkg/apis/meta/v1/types.go` in repository `github.com/kubernetes/api`.

Note that the repo name `apimachinery` appears to have been chopped up into two parts and split between the repo name `api` and the non-existent path `machinery/`. Both `kubernetes/api` and `kubernetes/apimachinery` are valid repos, which may have contributed to the confusion.

**Comment by sqs** [comment]
In Nov 2018 we will give Go cross-references (and same for all languages, in fact) some more attention (see roadmap at https://docs.sourcegraph.com/dev/roadmap). I expect that we will fix this issue then.

**Comment by sqs** [comment]
Assigning @chrismwendt 	to use this issue as a test case for the new Go external references implementation.

**Comment by chrismwendt** [comment]
I confirmed this is an issue in go-langserver. Specifically in the URL rewrite code, it checks for dependencies by prefix:

https://github.com/sourcegraph/go-langserver/blob/d032df118c7de2909eb86c6af922865548cea598/buildserver/build_server.go#L499-L503

I'm working on a fix now.
