### ISSUE TITLE
lsif-java Error When Uploading

### ISSUE THREAD

**Issue by tistru** [sourcegraph/sourcegraph#13914]
Reported by: https://app.hubspot.com/contacts/2762526/company/1783614661

Deployment type: docker-compose

User reported following error when attempting to upload dump.lsif to java repo:

`failed to enqueue payload: pq: new row for relation "lsif_uploads" violates check constraint "lsif_uploads_commit_valid_chars"`

#### Setup

> 1 self-hosted gitlab server
> 
> 2 “managed repos” pointing to that gitlab server, one containing 2 named projects and the other containing 46 named projects
> 
> a lsif.dump for a subdirectory of one of the projects named "{project name}".  When I go to the settings of that repo via Site Admin → Repository Status → Settings I only see Uploads under Code intelligence but that is empty

#### Steps To Reproduce
Upload command used:

*"{value}" is intended as a placeholder 
```
~/Projects/lsif-java(master)% ./scli -endpoint 'http://localhost' lsif upload -repo {value} -commit {value} -file {value} -root {value}

Inferred arguments:
  -repo={value}
  -commit={value}
  -root={value}
  -file={value}/dump.lsif
  -indexer=lsif-java

unexpected status code: 500

failed to enqueue payload: pq: new row for relation "lsif_uploads" violates check constraint "lsif_uploads
```

#### Additional Information:

Repository settings > Code intelligence > Activity for this repository docker-compose logs pgsql shows:

pgsql                                |  DETAIL:  Failing row contains (1, {Commit Num}, {projectName}, 2020-09-15 23:36:31.686289+00, uploading, null, null, null, 17, lsif-java, 1, {0}, null, 0, null).
pgsql                                | STATEMENT:  
pgsql                                | 				INSERT INTO lsif_uploads (
pgsql                                | 					commit,
pgsql                                | 					root,
pgsql                                | 					repository_id,
pgsql                                | 					indexer,
pgsql                                | 					state,
pgsql                                | 					num_parts,
pgsql                                | 					uploaded_parts,
pgsql                                | 					upload_size
pgsql                                | 				) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
pgsql                                | 				RETURNING id
pgsql                                | 			
pgsql                                |  ERROR:  new row for relation "lsif_uploads" violates check constraint "lsif_uploads_commit_valid_chars"
pgsql                                | DETAIL:  Failing row contains (2, {Commit Num}, {projectName}, 2020-09-15 23:36:31.971162+00, uploading, null, null, null, 17, lsif-java, 1, {0}, null, 0, null).
pgsql                                |  STATEMENT:  
pgsql                                | 				INSERT INTO lsif_uploads (
pgsql                                | 					commit,
pgsql                                | 					root,
pgsql                                | 					repository_id,
pgsql                                | 					indexer,
pgsql                                | 					state,
pgsql                                | 					num_parts,
pgsql                                | 					uploaded_parts,
pgsql                                | 					upload_size
pgsql                                | 				) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
pgsql                                | 				RETURNING id
pgsql                                |

**Comment by efritz** [comment]
Can I get an example of an actual `{Commit Num}` that is being inferred by the src utility here?

**Comment by tistru** [comment]
Sure. An example would be: `d21806b`

**Comment by efritz** [comment]
Only 7 characters, not 40? We assume a full revhash.

**Comment by efritz** [comment]
Followed-up with @tistru and looked at the associated JIRA issue. This error is occurring because we need a full 40-character OID supplied as the `-commit` argument. This is an expected error condition, but not an expected error message (see https://github.com/sourcegraph/sourcegraph/issues/13957 for improvement in this area).
