### ISSUE TITLE
Search/index generated code (that is not checked in)

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#13921]
Requested by:

* https://app.hubspot.com/contacts/2762526/company/578600789
* https://app.hubspot.com/contacts/2762526/company/732945850

>One question that came up from a user: Is there any way to get Sourcegraph to index generated code?  This user has generated code overriding methods, and thus people who remove those methods don't know when they search in Sourcegraph.

If it’s not checked in, we can’t currently support it.

There are workarounds to accomplish this, such as maintaining a branch or fork that includes the generated code, or using [`src serve-git`](https://github.com/sourcegraph/src-cli) [docs](https://docs.sourcegraph.com/admin/external_service/src_serve_git) we provide to serve up a repo on disk to Sourcegraph, but they do involve some custom work on the user's end.

Related to https://github.com/sourcegraph/sourcegraph/issues/577

**Comment by efritz** [comment]
There's a bit of overlap here and https://docs.google.com/document/d/1QigoTPGbc5ztGRzeqBBFVM5sD_uLfT4yOO3qxch2kGE (though not a whole lot).

**Comment by tsenart** [comment]
This needs product input, thinking and prioritisation, so assigning to @christinaforney.

**Comment by efritz** [comment]
See [RFC 236](https://docs.google.com/document/u/1/d/1QigoTPGbc5ztGRzeqBBFVM5sD_uLfT4yOO3qxch2kGE).

**Comment by tsenart** [comment]
@efritz: Does the code intelligence team own this then?

**Comment by efritz** [comment]
We only own the proposal in RFC 236 which _may_ overlap with this request and do not plan to implement it in the near-term. Agreed we should figure out the priority of this. cc @macraig

**Comment by poojaj-tech** [comment]
cc: @christinelovett since we chatted about a customer request for this recently.

**Comment by macraig** [comment]
Added this issue to our backlog to prioritize, @christinelovett @poojaj-tech have you talked about the priority level this has for CE and the search team? As @efritz said RFC 236 is not currently on our near term list, but we can change that if it becomes relevant.

**Comment by christinelovett** [comment]
@macraig I've tagged it as P1 - I don't think its super urgent but definitely something we want to support for them soon. We have a very large expansion opportunity here.

**Comment by macraig** [comment]
This feature request is now being tracked in [Productboard](https://sourcegraph.productboard.com/feature-board/1825051-code-intel/features/8233815/detail)
