### ISSUE TITLE
Remove `auth.providers` site configuration

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#1392]
Once we have fully migrated to external services, it is clunky that authorization configuration is split between site config and individual services. For example, GitHub authorization configuration should be completely contained inside of the GitHub external service config.

**Comment by nicksnyder** [comment]
I don't think we can remove this.

**Comment by sqs** [comment]
This should be moved into the critical site config, no?

**Comment by slimsag** [comment]
it already is

**Comment by slimsag** [comment]
err, by it I mean `auth.providers`
