### ISSUE TITLE
Add syntax highlighting for INI files (develop an open-source grammar for it)

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#13936]
The syntax definition we used for highlighting INI files before was found to have no license and not be open-source so we had to remove it. See #13933

We should develop and open-source grammar for it following what was said in #13933 - please see that issue if you are interested in taking a shot at this. We are looking for volunteers :)

**Comment by rvantonder** [comment]
It works https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/docker-images/grafana/config/grafana.ini
