### ISSUE TITLE
Search tour updates

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#13944]
* Remove structural search examples temporarily
* Add next and previous buttons to each step of the tour except the 'run search' and 'view search guide' steps
  * Previous buttons will not clear any input created in the previous step

**Comment by attfarhan** [comment]
> Remove structural search examples temporarily
What are we replacing these with?

**Comment by rrhyne** [comment]
I think we should just remove them for now along with the text for that step that reads "Or try an example:". The tour will prompt the user as so:

"Type the name of a function, variable or other code."

That should help the user enter something that means a bit more to them.
