### ISSUE TITLE
Sourcegraph Chrome extension page layout broken

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#1394]
I'm guessing the content we have entered is causing this. I've also viewed the page in incognito mode and get the same results.

1. Go to https://chrome.google.com/webstore/detail/sourcegraph/dgjhfomjieaadpoljlnidmbgkdffpack?hl=en
2. Scroll to the left to see the broken UI

<img width="1368" alt="screen shot 2018-12-13 at 12 47 02 pm" src="https://user-images.githubusercontent.com/133014/49966712-a389b400-fed5-11e8-838e-51d60886ec18.png">

In comparison to Last Pass' page

<img width="975" alt="screen shot 2018-12-13 at 12 40 27 pm" src="https://user-images.githubusercontent.com/133014/49966737-b308fd00-fed5-11e8-8e33-24a8d57b8777.png">

**Comment by sqs** [comment]
Yes, the long URLs were not wrapping. I abbreviated the SHAs. Will close this when I confirm the description has been updated.
