### ISSUE TITLE
Resolving repo groups is really slow

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#13947]
I semi-frequently run queries against [`repogroup:go-gh-100`](https://sourcegraph.com/search?q=repogroup:go-gh-100&patternType=literal), which is 100 Go GitHub repos. Previously it took less than a second (even less than 300ms I want to say?) It currently takes 13 seconds to just list the repos (i.e., repo lookup is very slow). Similar for other repogroups I've created like `repogroup:java-gh-100`, `repogroup:c-gh-100`.

I haven't confirm but: https://github.com/sourcegraph/sourcegraph/pull/13730 is a recent change, so it has a good chance of affecting things?

**Comment by beyang** [comment]
Initial investigation seems to suggest the [computeExcludedRepositories](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/search.go#L417-468) function is the bottleneck, based on the logs in this span (note the large gap between `Repos.List - done` and `excluded repos: ... `):
![Selection_299](https://user-images.githubusercontent.com/1646931/93834461-db886400-fc30-11ea-856c-38c312587603.png)

**Comment by rvantonder** [comment]
Ah ha. So this makes me wonder about some caching behavior--I refactored the excludedRepos behavior and there was one possibly semantics-altering change that I called out here: https://github.com/sourcegraph/sourcegraph/pull/13352/files#diff-d270aecf1b7e3730429f967a1dad8114L504. But there didn't seem to be any concerns about an impact in the PR. Based on this behavior and it possibly being due to that PR, I'm wondering if there's some recomputation going on. Just another guess based on recent changes, will have to dig into it, but should be able to reproduce the issue locally.

**Comment by beyang** [comment]
Ah interesting, that might explain things. I made a PR with some additional tracing (feel free to approve/merge or abandon): https://github.com/sourcegraph/sourcegraph/pull/14020. If you have an inkling as to the root cause, can I let you take over investigation from here (feel free to loop me back in at any point)?

**Comment by rvantonder** [comment]
Yep I'll own this.

**Comment by rvantonder** [comment]
@beyang strongly believe this is the issue, repogroup labels are ignored: https://github.com/sourcegraph/sourcegraph/commit/a82e2b088dce6f2ea20ebfe3ac61c61e2e36548d#r42707333, so repogroups are currently broken. I also confirmed by doing `repogroup:<choose anything>` and then do `count:1000` you'll see a lot more repos are included than what should be (any use of `repogroup` includes all repos specified for all repogroups). Will try come up with a test and fix, but going to cap that effort to an hour or two. It's a pretty bad regression so if I don't get a fix for it soon I'll put up a PR to revert it, and we can figure out who owns reintroducing/fixing this functionality (I'm OK with owning this, but I don't want it to block the repogroup functionality/blog post content I'm working on, would rather revert and come back to it).
