### ISSUE TITLE
GraphQL syntax highlighting chooses poor colors for comments+field names

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#13959]
Now that we're using `"""` (triple-quote) comment syntax in our GraphQL schema file (https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/schema.graphql#L573:5), I see that there is poor visual distinction between comments and field names. For example, the "Set the permissions of a repository..." comment and the `setRepositoryPermissionsForUsers` field name are the same color. Note that the `(` after the field name is a different color, so this does not *appear* to be incorrect tokenization, just poor color choices.

![image](https://user-images.githubusercontent.com/1976/93643258-83452e00-f9b4-11ea-8e7e-c54f39549ad0.png)

**Comment by rvantonder** [comment]
![Screen Shot 2021-05-19 at 1 13 00 PM](https://user-images.githubusercontent.com/888624/118878253-351a5e80-b8a4-11eb-8eb2-3b9e7f9adebc.png)


This was likely fixed in https://github.com/sourcegraph/sourcegraph/pull/14814 when we updated the GQL highlighting definition.
