### ISSUE TITLE
Show last ping data to admins on the Site-admin > Pings page

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#13956]
https://app.hubspot.com/contacts/2762526/company/557692623 requires offline support for Sourcegraph, and we have agreed that they will simply email us a copy of the standard telemetry, but once per month (or on some other schedule). 

This dovetails nicely with the desire to be more transparent about our ping telemetry. We have discussed in the past displaying the actual telemetry payloads to admins for full transparency, and that could solve this problem.

Proposal
* On the Site-admin > Pings page, add a box at the top (or bottom? or on another tab?) that illustrates the payload generated for the "last" ping (or if not exactly the last, some ping in the last 24 hours) that was sent.
* Add a button to the top to download that payload (similar to the download button on https://sourcegraph.com/site-admin/usage-statistics).
* Ensure that this whole flow works, even if the instance is not connected to the internet (so pings aren't actually going out). In this case, I believe we still generate the payload, but the post to sourcegraph.com fails, so just make sure everything is sequenced correctly...

**Comment by tsenart** [comment]
@flying-robot: Assigned this to you as well. We could pair on some of this on Thursdays and Fridays (when I have less meetings scheduled usually).

**Comment by dadlerj** [comment]
Awesome!

One alternative to using events (since this isn't _really_ a user event, and I have a slight preference to keep things clean conceptually there...) would be to just chuck the last ping into a random Redis key, and if the data is lost, that's totally fine. I don't have a strong opinion and if this is significantly faster to implement then I'm fine with it

**Comment by tsenart** [comment]
> (since this isn't really a user event, and I have a slight preference to keep things clean conceptually there...)

We have a few other system level events in that table (where there's no user associated with it) so I think conceptually it'd be fine. It also easily allows us to show the last few pings, if we so wished. I think we should go with it.
