### ISSUE TITLE
Detect and delete public repository added-on-visit when it become private

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#13978]
Currently, we automatically add public repositories from GitHub.com and GitLab.com when a user visits it (either by directly viewing it on Sourcegraph.com or via browser extension). However, we don't have a mechanism to delete such repositories when they become private on the code host as they may not associate with any external service.

Related: https://github.com/sourcegraph/security-issues/issues/96

**Comment by tsenart** [comment]
@unknwon: Assigned @asdine since you had too much on your plate.
