### ISSUE TITLE
C++ code intelligence does not work on nanocurrency/raiblocks

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#140]
- **Sourcegraph version:** Sourcegraph.com

#### Steps to reproduce:

1. Go to https://sourcegraph.com/github.com/nanocurrency/raiblocks@fbeddd4c00dc816233919b45dce3b7eb7d8e14de/-/blob/rai/lib/work.cpp#L29:17
2. Hover over any token

Extracted from #138 

#### Expected: 

Hover information

#### Actual:

No hover information

**Comment by chrismwendt** [comment]
The language server is up and running (e.g. [hover works on the redis repo](https://sourcegraph.com/github.com/antirez/redis@2e0ab4a80708d96f4107ff75686be5582e314f0f/-/blob/src/expire.c#L223:28)), but is not providing code intelligence on this repository.

The only relevant difference in logs between this and the redis example is:

```
[17:34:01.296] Ignored diagnostic. too many errors emitted, stopping now
```

I don't know if "stopping now" means "stopping all code intelligence" or "stopping looking for more diagnostics to report".

The next steps would be to try to whittle this down to a minimal repro and/or dig into the language server itself.

**Comment by sqs** [comment]
We removed the C++ lang server that caused this (see https://about.sourcegraph.com/blog/java-php-experimental_language_servers-temporarily-unavailable).

The preferred way to get C++ code intelligence is (for now) to use the basic-code-intel extension; see https://about.sourcegraph.com/blog/sourcegraph-3.0-beta-is-now-available#basic-code-intelligence-for-all-languages for info. (On Feb 4, 5 days from when I'm currently writing this, Sourcegraph 3.0 will be released, at which point there will be a **C++** extension that is enabled by default on all instances; see #2035. Then this will just work out of the box.)
