### ISSUE TITLE
Update RFC 236

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#14007]
Update thoughts for [RFC 236: Code intel federation](https://docs.google.com/document/u/1/d/1QigoTPGbc5ztGRzeqBBFVM5sD_uLfT4yOO3qxch2kGE). Will likely involve a meeting including @gbrik and @Strum355 to bash our ideas until they look pretty much the same.

Note: Title of RFC is subject to change as federation is an implementation detail (and one we might not even choose).

**Comment by macraig** [comment]
Not prioritizing in the near term, can reopen if we revisit.
