### ISSUE TITLE
Enhanced Python code intelligence

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#1401]
Pre-requisite:
- [x] https://github.com/sourcegraph/sourcegraph/issues/959

Milestones:
- [ ] Single repository code intelligence with dependency fetching
- [ ] Cross repository code intelligence

**Comment by aidaeology** [comment]
@nicksnyder It looks like this issue is for Python LSP support? If yes, can we close it or do we still need to work on it?

**Comment by efritz** [comment]
LSIF support for Python would provide the same outcome.

**Comment by nicksnyder** [comment]
We will eventually want to support Python code intelligence regardless of implementation details (LSIF vs LSP). Given this isn't a current priority, I think it would be fine to close this issue, but I will leave that decision up to you and the team.

**Comment by scalabilitysolved** [comment]
Given the prior convo shall we close this @macraig ?
