### ISSUE TITLE
Implement TypeScript query parser in webapp

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#14016]
Without a frontend/typescript query parser, we cannot do any of these really important things:

- manipulate/change queries correctly when any UI element state affects a query (e.g., adding `case:yes` when the user toggles the button) https://github.com/sourcegraph/sourcegraph/issues/13958
- properly highlight search queries, or special syntax found in regex like `\s` or `+`, and structural search like `...` or `:[hole]`. Without highlighting, our language is bland, and we lose the ability to provide helpful visual cues for users. A search query UI/UX without these basics is a second-rate experience/solution.
- provide helpful hints to users when there's a syntax error (unbalanced `)` or invalid filter
- hover information for all of the above (e.g., explain what does `\s+` match?)
- extend our query language with new syntax or features

I will just be (mostly) mechanically translating the backend parser to TypeScript, and porting the tests too.

**Comment by felixfbecker** [comment]
I thought we had one? A nice functional one even :)

**Comment by rvantonder** [comment]
@felixfbecker the language is/has changed, see implications: https://github.com/sourcegraph/sourcegraph/issues/13958

Query transformation current assumes the input is some linear sequence of filters/patterns, so just uses regex to change things. This assumption doesn't hold any more, the query is a proper tree now.

> A nice functional one even :)

It's great to have the framework and Monaco. Loic wrote the parser in a couple of weeks, it's pretty barebones. E.g., we don't have regex syntax highlighting yet, feel like it's time to we have (a way) to do this sort of thing easily.

**Comment by tsenart** [comment]
Excited for this. I like parsers :)

**Comment by rvantonder** [comment]
Closed by #15560
