### ISSUE TITLE
Go to definition takes me to wrong line; wrong tokens highlighted on hover

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#14015]
Filing on web, even though this has to do with codeintel, because it seems like it's affecting non-codeintel extensions as well (e.g. token highlights)

Repro:

- Hover over this token: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@599f414/-/blob/enterprise/cmd/frontend/internal/licensing/licensing.go#L69:18
- Note that the `Lock` token in `mu.Lock()` on line 88 is highlighted
- Click go to definition
- Land on the `Lock` token on line 88

**Comment by dadlerj** [comment]
Seems to happen on main as well in TS code. E.g. try hovering on the token `productSubscription` on line 56 and see that a bunch of random tokens are highlighted: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/web/src/global/GlobalAlerts.tsx#L56:58

![image](https://user-images.githubusercontent.com/5589410/93832428-982af700-fc2a-11ea-8f80-d139e9513755.png)

**Comment by felixfbecker** [comment]
Reassigning to @sourcegraph/code-intel, this data comes this way from the LSIF backend:

![image](https://user-images.githubusercontent.com/10532611/95793021-f5bfda00-0ce4-11eb-8372-dd6b9075b818.png)

**Comment by efritz** [comment]
I can't reproduce. If you found any other examples could you post a fresh one that I could look into? I don't know if this is a bug in the API, indexer, or just happenstance of weird state.

**Comment by dadlerj** [comment]
Perhaps related to the other issue you fixed this week. Seems like a whole category of "codeintel flakiness" could be wiped away by that one!

**Comment by efritz** [comment]
It could be fixed (but probably not that bug if the LSIF data is wrong here). If you see anything else weird feel free to file and issue or ping me on slack with a _living_ problematic hover and I can track it down pretty quick.
