### ISSUE TITLE
Clicking on search result clears search bar; have to refresh to get it back

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#14014]
Sourcegraph.com

repro:
- visit sourcegraph.com/search
- search for anything
- click on any result

**Comment by dadlerj** [comment]
Seems like clicking on any line in any file does this too

**Comment by slimsag** [comment]
Just came here to file exactly this. It is infuriating for me as it breaks my most common workflow:

1. Visit https://sourcegraph.com/github.com/sourcegraph/sourcegraph and search for something like `Your license will expire` trying to track down where it comes from.
2. Find [the relevant file](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/web/src/site/LicenseExpirationAlert.tsx), and want to now search for its usages by searching in the repo for `LicenseExpirationAlert` - but wait - now my search bar is empty. How the heck do I come up with the right `repo:` concoction? Now I am out of context

Was this a regression? Is this also a regression in 3.20 or only Sourcegraph.com?

**Comment by slimsag** [comment]
Looks like this has been fixed and is in 3.20.1 but not yet on sourcegraph.com for some reason.

![image](https://user-images.githubusercontent.com/3173176/93833759-69168480-fc2e-11ea-988c-e2436760283c.png)

https://github.com/sourcegraph/sourcegraph/pull/13954

**Comment by slimsag** [comment]
fixed https://sourcegraph.slack.com/archives/CMBA8F926/p1600734032009700
