### ISSUE TITLE
RFC 167: Enforce site-admin roles

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#14023]
The actual form of enforcement hasn't been decided yet, see discussions in the [RFC](https://docs.google.com/document/d/1XozQ4JINJqirdaG-XqGtboT2-PlIXPyBn6EwV7Q3pWI/edit?disco=AAAAJ_b2hIg).

Part of [RFC 167](https://docs.google.com/document/d/1XozQ4JINJqirdaG-XqGtboT2-PlIXPyBn6EwV7Q3pWI/edit).

TODO

- [x] All new users are prompted to be side admins in Free tier
- [x] Prevent user creation with a malformed/expired license
- [x] Dotcom: no new users can be prompted to site admin automatically
- [x] Prevent revoking site admins

**Comment by unknwon** [comment]
We don't have bandwidth in the 2020-10-07 cycle.

**Comment by tsenart** [comment]
@unknwon: Does this still need to be done?

**Comment by unknwon** [comment]
@tsenart Ah missed it :) Adding to the current cycle.
