### ISSUE TITLE
RFC 211: We should apply a per user and total limit to user added repos

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#14043]
We should limit the number of repos that can be added by users

- [x] Limit the number of repos per user
- [x] Limit the total number of user added repos
- [ ] Fire an alert when we are approaching the total limit

The above limits will need to be enforced during sync and should be included both during streaming insertion of repos and batch syncing.

It should be configurable but include sane defaults. The point of this is to protect an instance against abuse so the number should be high enough that they are not hit based on normal usage.

User repos from code hosts should be ordered deterministically so that once they are over the limit we don't randomly add and remove repos on each sync.

The discussion around how we notify end users can begin here but we will not implement it as part of this issue.

**Comment by tsenart** [comment]
> The discussion around how we notify end users can begin here but we will not implement it as part of this issue.

@quinnkeast @christinaforney: We'd like input on this. I can think of few ways to leverage existing UI patterns to surface this information to the users. Syncing repos, and thus, discovering how many the given code host connection "yields", is an asynchronous process, like cloning and indexing.

In the past we have used the progress status indicator for this, but we also have the banner "alerts" infrastructure. We could tie in to any of these for normal users to receive notifications for now, before you have the time to re-work the design of this use-case.

What do you think?

**Comment by ryanslade** [comment]
Some WIP notes on this as I looked at implementing it today and it not that simple:

We need to make it work while the streaming inserter is adding repos
What do we do once we are part way through fetching from the code host and we hit the limit as we stream new repos in. We need to stop inserting but continue to fetch repos so that we know which ones we can delete. 
Once we delete we are freeing up quota again...

One quick win could that if we keep the limit for user added repos quite small, say around 2k then we actually skip the streaming insert completely for user added repos as it won't take long to fetch all repos. Then we can do everything in one batch which makes the task significantly simpler.
