### ISSUE TITLE
File breadcrumbs can expand to more than one line

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#14059]
Repro:
* Go to https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/tree/browser/src/shared/code-hosts/shared
* Observe the file breadcrumb renders awkwardly into 2 lines (because "code-hosts" is split into 2 lines).

![image](https://user-images.githubusercontent.com/1646931/93910403-e5a07600-fcb5-11ea-8fee-4d5cf5c554ac.png)

cc @sourcegraph/web

**Comment by tjkandala** [comment]
Closing in favor of #13535
