### ISSUE TITLE
site-admin status unclear for user coming from openid google auth provider

### ISSUE THREAD

**Issue by uwedeportivo** [sourcegraph/sourcegraph#14068]
- **3.20 k8s.sgdev.org** 
- **k8s cluster, chrome browser** 

#### Steps to reproduce:

1. log into k8s.sgdev.org with google openid (stephen or tomas or a couple of others)
2. observe: not site-admin
3. go to postgres pod for k8s.sgdev and select site-admin from users where username="stephen";
4. observe it says "t"

#### Expected behavior:

expect to be a site-admin

#### Actual behavior:

not a site-admin

this might be a misunderstanding on my part, but it happened for me, dave and geoffrey. once promoted to site-admin in the UI by the original admin (i logged in as admin with builtin auth provider and password from 1passw), it works and i, dave and geoffrey are site-admins now.

**Comment by uwedeportivo** [comment]
@unknwon feel free to re-assign or close if this is expected behavior

**Comment by unknwon** [comment]
@uwedeportivo Hmm, no I'm not a site admin right now using my Sourcegraph email to sign in via OpenID (am I supposed to? Have we replicate the database in the exact same state?).

**Comment by unknwon** [comment]
Cleaning up old/stale/fixed issues, please feel free to reopen if you think it's worth keeping.
