### ISSUE TITLE
webapp search query validation incorrectly indicates '-author' is not supported

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#14083]
![image](https://user-images.githubusercontent.com/23356519/93963628-41d7c880-fd90-11ea-93ea-e3893eadcd7c.png)

This filter seems to work - [example](https://k8s.sgdev.org/search?q=repo:%5Egithub.com/sourcegraph/.*+type:commit+after:%223+days+ago%22+-author:%28sourcegraph-bot%7Crenovate%5C%5Bbot%5C%5D%29&patternType=literal)

**Comment by rvantonder** [comment]
Looks like this applies to [author, committer, and message](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/search/query/validate.go#L303-305). 

Just going to assign myself and @stefanhengl and see who gets to it first, we've all touched this part of the code before.
