### ISSUE TITLE
Send GCE logs to logging infrastructure

### ISSUE THREAD

**Issue by chayim** [sourcegraph/sourcegraph#14091]
In theory we can connect Stackdriver and Elasticsearch.

https://cloud.google.com/solutions/exporting-stackdriver-logging-elasticsearch

**Comment by ElizabethStirling** [comment]
Estimating 1 day for this, since [this tutorial](https://cloud.google.com/community/tutorials/exporting-stackdriver-elasticcloud) I found seems relatively straightforward. I would expect to need some time to test and verify that this works as intended, so I want to assign an entire day to this.

**Comment by chayim** [comment]
Closed by 14092.
