### ISSUE TITLE
Gather docker logs into centralized logging

### ISSUE THREAD

**Issue by chayim** [sourcegraph/sourcegraph#14090]
For all running containers in Sourcegraph cloud, gather the associated logs and send them to the infrastructure enabled in #13552

**Comment by ElizabethStirling** [comment]
Estimating as 4 days. I assume we'll need to do work for each container to configure infrastructure logging, and to configure them to only do this on our cloud deployments. Could be more time consuming, depending on how obtuse the tooling around this is.

**Comment by ElizabethStirling** [comment]
Moving out of 3.22 since scanning and RFC 249 come before this in the roadmap.
