### ISSUE TITLE
Broken doc link to management_console page

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1410]
https://sourcegraph.com/github.com/sourcegraph/sourcegraph@6439a23db9e1174fb56e2bbb66205e2b65132543/-/blob/web/src/site-admin/SiteAdminManagementConsolePassword.tsx#L92:73 links to https://docs.sourcegraph.com/admin/management_console, which doesn't refer to any existing doc page.

**Comment by slimsag** [comment]
Yep, FWIW I know this is a broken link + have plans to add it.

**Comment by slimsag** [comment]
Fixed
