### ISSUE TITLE
navbar overflowing

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#14110]
https://sourcegraph.com/github.com/sourcegraph/zoekt/-/blob/cmd/zoekt-sourcegraph-indexserver/main.go#L58:10

![image](https://user-images.githubusercontent.com/3173176/94054000-e1488b80-fd8f-11ea-86b0-d5f3c2fe7a6e.png)

**Comment by tjkandala** [comment]
Fixed by #14097
