### ISSUE TITLE
Update saved search pings to include number of org/individual

### ISSUE THREAD

**Issue by ebrodymoore** [sourcegraph/sourcegraph#14113]
[#12956](https://github.com/sourcegraph/sourcegraph/pull/12956) introduced saved search metrics to pings. Need to update to separate out organization and individual-level saved searches for adoption data cc @poojaj-tech

**Comment by poojaj-tech** [comment]
Raising the importance for tracking number of organization users for saved searches. This helps us answer an important open question for planning ([link to doc)](https://docs.google.com/document/d/1EG42dM1old49uPXpGAqL7b9k95bWpM0Zcu0JM5gXtOQ/edit) around adding support and/or migration for organization saved searches.
