### ISSUE TITLE
release: update the version in about.sourcegraph.com GetStarted

### ISSUE THREAD

**Issue by aileenrose** [sourcegraph/sourcegraph#14111]
This new file in the website repo needs to be updated with the version number for any new releases:

https://github.com/sourcegraph/about/blob/main/website/src/components/GetStarted.tsx 

note from @slimsag 
> We will need to add an equivalent edit command here that automates updating that line as part of the release: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/release/src/release.ts#L319-327

**Comment by slimsag** [comment]
Updated description/etc to make this a little more clear. @bobheadxi maybe something you could quickly take on?

**Comment by bobheadxi** [comment]
Reference: basically this diff https://github.com/sourcegraph/about/pull/2053/files
