### ISSUE TITLE
Log cross repo code intel events

### ISSUE THREAD

**Issue by ebrodymoore** [sourcegraph/sourcegraph#14120]
We've had conversations about this being an 'aha' moment during the sales cycle and beyond, and this could be something really valuable we surface to admins.

@efritz to add notes about what implementation would look like to add this to code intel events.

**Comment by efritz** [comment]
This should be doable, just want to know how to count it:

- Do we want each _result_ that's from a different repo to be counted
- Or do we want each result _set_ that contains _at least one_ result in a different repo to be counted as one unit

**Comment by ebrodymoore** [comment]
Each time a result set contains at least one in a different repo to be counted as one would be best. So just to make this crystal clear, if a hover produces [same repo, diff repo, diff repo] we would want to count this as one, not two.
