### ISSUE TITLE
Debugging Sourcegraph Extension with `console.log`

### ISSUE THREAD

**Issue by yevbar** [sourcegraph/sourcegraph#1413]
- **Sourcegraph version:** sourcegraph.com
- **Platform information:** chrome extension with extensions and extension-debugging (where RPC trace logging is visible)

#### Steps to reproduce:

1. Install my [hello-world extension](https://sourcegraph.com/extensions/yevbar/hello-world) (and [here](https://github.com/yevbar/Sourcegraph-HelloWorld) is the source)
2. Hover over some code

#### Expected behavior:

When hovering over a token, the user should see a hello world message above the token and see a hello world message in the console as well.

#### Actual behavior:

There is a hover message but there is no output in the console.

**Comment by yevbar** [comment]
For people that come across this issue, the reason I ran into this was that I assumed that the extension would run the script in the same environment as the page you're on however that's incorrect. To see your `console.log` statements, you'll need to open the Sourcegraph environment via `chrome://extensions` (if you're on Chrome)

**Comment by yevbar** [comment]
To see the `background page`, you must toggle developer mode when on chrome://extensions

**Comment by ryan-blunden** [comment]
Sorry you ran into this @yevbar. It's unintuitive and we're working on a solution to propagate logs to the content page from the background page
