### ISSUE TITLE
add deploy-sourcegraph-dhall pipeline to deploy-sourcegraph-dot-com

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#14132]
Part of: https://github.com/sourcegraph/sourcegraph/issues/13340

Depends on: https://github.com/sourcegraph/sourcegraph/issues/14131, https://github.com/sourcegraph/sourcegraph/issues/14130, https://github.com/sourcegraph/sourcegraph/issues/13338, https://github.com/sourcegraph/sourcegraph/issues/14133, #17631, #17290 

**MVP** for this work is a pipeline that deploys symbols

- [x] `deploy-sourcegraph-dot-com-pipeline.dhall` generates a Dhall record containing only symbols component 
- [x] `ds-to-dhall dhall2ds` used to convert to K8s compatible yaml
- [ ] Open source Dhall repo to allow us to add a `generate.dhall` file into `deploy-sourcegraph-dot-com` 
- [ ] Add pipeline.dhall file that imports https://github.com/sourcegraph/deploy-sourcegraph-dhall with the necessary customizations
- [ ] Remove existing https://github.com/sourcegraph/deploy-sourcegraph-dot-com YAML files for symbols, gitserver
- [ ] YAML is committed back to branch automatically via pipeline tool (in the correct place) 
- [ ] Renovate should not modify the symbol's k8s yaml. It should operate on the `deploy-sourcegraph-dot-com-pipeline.dhall`  https://github.com/sourcegraph/sourcegraph/issues/14133
- [ ] Add CI check to verify that dhall and generated kubernetes YAML are synchronized (runs every commit)

**Comment by daxmc99** [comment]
TODO:

- [ ] `dhall diff '(./src/k8s/pipeline-dot-com.dhall).repo-updater' '(./deploy-sourcegraph-dot-com.dhall).repo-updater'`

**Comment by daxmc99** [comment]
**MVP** for this work is a pipeline that deploys symbols

- [ ] Open source Dhall repo to allow us to add a `generate.dhall` file into `deploy-sourcegraph-dot-com` 
- [ ] `deploy-sourcegraph-dot-com-pipeline.dhall` generates a Dhall record containing only symbols component 
- [ ] `ds-to-dhall dhall2ds` used to convert to K8s compatible yaml
- [ ] YAML is committed back to branch automatically via pipeline tool (in the correct place) 
- [ ] Renovate should not modify the symbol's k8s yaml. It should operate on the `deploy-sourcegraph-dot-com-pipeline.dhall` 

Deep dive into a renovate PR:

- When Renovate creates a PR to update an image it should
1. Choose the correct file to use, update a renovate-compatible file `renovateHERE.yaml` representation of all images
1. Workflow triggers to dhall-to-yaml | yaml-to-k8s  & commit back to branch
1. After CI passes, merge

**Comment by pecigonzalo** [comment]
Removing from the current iteration as we shift priorities.

**Comment by daxmc99** [comment]
Not currently pursing
