### ISSUE TITLE
Unable to log in via GitLab OAuth

### ISSUE THREAD

**Issue by plinss** [sourcegraph/sourcegraph#14144]
- **Sourcegraph version:** 3.20.1
- **Platform information:** CentOS 7.8.2003, Docker V19.03.8

#### Steps to reproduce:

1. Connect Sourcegraph to on-premise GitLab via instructions at: https://docs.sourcegraph.com/admin/auth#gitlab
2. Attempt to login to Sourcegraph via GitLab

Note that the GitLab instance is using an https certificate signed by an internal CA.
Sourcegraph site config contains:

    ...
    "auth.providers": [
        {
            "type": "builtin",
            "allowSignup": false
        },
        {
            "type": "gitlab",
            "displayName": "GitLab",
            "url": "https://gitlab.<our-domain>",
            "clientID": "<gitlab OAuth ID>",
            "clientSecret": "<gitlab OAuth secret>"
        }
    ],
    ...
    experimentalFeatures: {
        "tls.external": {
            "certificates": ["<internal CA root certificate pem data>"]
        }
    }

#### Expected behavior:

Successful login.

#### Actual behavior:

After redirecting to GitLab (and successfully logging in if necessary), Sourcegraph responds with "github: unable to get GitLab user".

GitLab logs appear to show successful login and OAuth response.

**Comment by plinss** [comment]
FWIW, Sourcegraph is otherwise connecting to the GitLab instance and fetching repositories. Local user accounts work, but we're unable to use GitLab accounts.

**Comment by unknwon** [comment]
Thanks for filing this issue!

The error message itself is an easy fix:

https://github.com/sourcegraph/sourcegraph/blob/7932d2c48f296e99476d38ed93e184fc8ac5118b/enterprise/cmd/frontend/auth/gitlaboauth/login.go#L17

And it's so bad that we swallow the error here:

https://github.com/sourcegraph/sourcegraph/blob/main/enterprise/cmd/frontend/auth/gitlaboauth/login.go#L62-L64

**Comment by tsenart** [comment]
@unknwon: Can add an estimate to this issue?

**Comment by unknwon** [comment]
> @unknwon: Can you add an estimate to this issue?

@tsenart: Added.

**Comment by unknwon** [comment]
Found the possible root cause while fixing the error message:

https://github.com/sourcegraph/sourcegraph/blob/decd7defbffb0d65b48420240faec3ed8362d714/internal/extsvc/gitlab/client.go#L81

We should have been using `httpcli.ExternalDoer` since #13814

**Comment by unknwon** [comment]
@plinss The patch to address this issue was merged but unfortunately will only land on 3.22.

**Comment by plinss** [comment]
Thanks @unknwon! Verified with 3.22, I can now sign in to Sourcegraph via GitLab.
