### ISSUE TITLE
Change wording of "No action will be taken on apply" in preview

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#14155]
I don't think it makes sense to say "No action will be taken on apply" when it clearly mentions an action on the left: "Will import"

![image](https://user-images.githubusercontent.com/1185253/94140814-1c1ff180-fe6c-11ea-9519-c6a0ffb3a7a4.png)

How about changing it into something wordier but maybe clearer, like

> The changeset won't be modified on apply. It will only be imported and tracked.

Maybe that can be generalised to other "explanatory" texts for each action?

**Comment by eseliger** [comment]
I think this needs some further spec work, once we allow non-admins to create/apply campaigns.

Currently, the rewirer will bail out with an error if any of the changeset specs target a repo that the user has no access to. Given that, no actions will be taken at all.

**Comment by mrnugget** [comment]
@eseliger But wouldn't those changeset specs show up as `HiddenChangesetSpecs` on the preview page?

**Comment by eseliger** [comment]
Yes but when you click apply it would fail.

**Comment by mrnugget** [comment]
Exactly, which means that it might make sense to grey out the `Apply spec` button if we know it would fail and tell the user that they need to create a new campaign spec.

FYI, there's a reason why it's an error and doesn't skip repositories:

https://github.com/sourcegraph/sourcegraph/blob/e37786d049dde9f65af642c9ee9e1e7c80578959/enterprise/internal/campaigns/service_apply_campaign.go#L236-L243

**Comment by eseliger** [comment]
I think the task here then is: 

Add a `viewerCanApply` field to the campaign spec resolver and use that to 
- Disable the apply spec button
- Add some explanatory text why it can't be applied
- Set all reconciler actions to `NO_ACTION`
