### ISSUE TITLE
Decorating changeset body fails with "Namespace not found"

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#14159]
I just ran into this when trying to create three changesets:

<img width="916" alt="screenshot_2020-09-24_15 21 29@2x" src="https://user-images.githubusercontent.com/1185253/94150659-b9cded80-fe79-11ea-99fb-6bd0deac7268.png">

**Comment by mrnugget** [comment]
Invalid. Realised it's because my local environment didn't have entries in the `names` table, because I re-setup my env my importing a database dump (which didn't include `names`).

**Comment by twof** [comment]
@mrnugget Hi! I'm running into the same issue when I try and run a campaign. I'm running it against an enterprise github instance if that changes anything. What were the steps you took to resolve this issue?

**Comment by mrnugget** [comment]
> I'm running it against an enterprise github instance if that changes anything. What were the steps you took to resolve this issue?

Hey! See my last comment: the problem was not the code host, but how I setup my local dev environment to work on campaigns.

Are you running into the _exact same_ error message? If so it sounds like the namespace (a Sourcegraph user or a Sourcegraph org) you're creating a campaign in might be wrong/deleted/outdated.

**Comment by twof** [comment]
<img width="1096" alt="Screen Shot 2021-07-07 at 12 31 31 PM" src="https://user-images.githubusercontent.com/5561501/124817986-56501080-df1f-11eb-9006-b9096a72b5ab.png">


Yeah it looks like I'm getting the exact same error. Where's the table located that you said was misconfigured?

**Comment by mrnugget** [comment]
> Yeah it looks like I'm getting the exact same error. Where's the table located that you said was misconfigured?

It's an internal database table.

In which namespace did you create that batch change (campaign)? And does that namespace still exist?

**Comment by malomarrec** [comment]
Hey @twof - what version are you on? 
Unrelated but this looks like an older version, you might be missing out on some [improvements / new batch changes features](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/CHANGELOG.md#3-29-0) :)

**Comment by twof** [comment]
@malomarrec Our enterprise deployment is on 3.23.0 and my command line tool (`src`) is
```
$ src version
Current version: 3.29.1
Recommended version: 3.23.3 or later
```

I'm not the admin for my org's deployment so I'm not going to be able to upgrade it unfortunately.
