### ISSUE TITLE
Implement Polly recording/replaying of requests

### ISSUE THREAD

**Issue by marekweb** [sourcegraph/sourcegraph#14174]
Currently the Polly adapter implemented in #13870 is able to intercept and fulfill requests.

It currently doesn't fully implement another Polly feature: recording and replaying requests which are persisted as HAR files.

Support for recording/replaying is partial:

- With the adapter, Polly is able to record and persist requests in HAR files
- But adapter doesn't succeed in fulfilling requests when they are being replayed from the persisted HAR files

**Comment by felixfbecker** [comment]
@marekweb it would help if you could put an estimate for this so we know how much we need to plan for next iteration, could you do that?
