### ISSUE TITLE
Hover syntax highlighting is not working, produces error

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1418]
```
Error syntax-highlighting hover markdown code block Error: Unknown language: "python"
```

**Comment by sqs** [comment]
This occurs for all languages. The problem does not exist on dev builds.

**Comment by felixfbecker** [comment]
Was about to file this. Is this from your changes to how highlight.js is imported?

![image](https://user-images.githubusercontent.com/10532611/49991488-890d1480-ff81-11e8-8b46-92028f0989f4.png)
