### ISSUE TITLE
Configure GitHub code scanning via CodeQL and OSSAR

### ISSUE THREAD

**Issue by ElizabethStirling** [sourcegraph/sourcegraph#14187]
In order to accomplish our goals of increasing visibility, we want to set up some static analysis tools. 

It looks as though we already have CodeQL partially configured, but it was configured with master, not main.
https://github.com/sourcegraph/sourcegraph/pull/14186

**Comment by chayim** [comment]
@ElizabethStirling I think this would be a worthy first start, especially if it's a true first order integration. https://github.blog/2020-09-30-code-scanning-is-now-available/

**Comment by ElizabethStirling** [comment]
This doesn't seem to actually have any additional use. After fixing CodeQL, I looked into [OSSAR](https://github.com/github/ossar-action), but it only supports scanning windows binaries, python code, and running eslint, which we already have configured. Doesn't seem like there's anything more to do here, so I'll close it out.
