### ISSUE TITLE
Add 'Install the browser extension' alert, remove the popup

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#14196]
Part of [RFC 221](https://docs.google.com/document/d/19f4xleYBU1zZZdqMmXlLmFxeR-fwEpOwTOgViOFOnyo/edit?usp=sharing): Improve discoverability/awareness of the browser extension

**Description**

- remove the 'install browser extension popup'
- add info alert to the file view pages

**Design documentation**

1. The alert:
[View in Figma](https://www.figma.com/file/V5t7KOzC6PIX75L4dz8IFc/RFC-221-Browser-extension-improve-discoverability-and-awareness-Final-review?node-id=366%3A1)
- Use the info alert styles. Limit number of characters to 66 per line.
- Display the alert for the first time after the user saw at least 2 hovers (code intel tooltips)
- Display only on the file view, until user dismissed it (x button). Don't show again.
- Use the code host logo and name in the popup. The code host name will be taken from the currently viewed file (ex. for the file from GitHub, we will show the GitHub logo and copy)
- Add [subtle flashing background](https://www.figma.com/file/V5t7KOzC6PIX75L4dz8IFc/RFC-221-Browser-extension-improve-discoverability-and-awareness-Final-review?node-id=366%3A59) animation behind the code host logo to draw more attention to the alert. See the [video](https://www.loom.com/share/84c8ff00408c40f9a9168e7f6f8ee974) showing the animation or open the [prototype](https://www.figma.com/proto/V5t7KOzC6PIX75L4dz8IFc/RFC-221-Browser-extension-improve-discoverability-and-awareness-Final-review?node-id=366%3A59&viewport=460%2C-1263%2C0.31671735644340515&scaling=min-zoom). Animation specs: ease in and out 800ms, delay 800ms.

2. Alert variants
- Content of the alert changes depending on the code host of the currently viewed file for Chrome and Firefox users (once the Firefox extension is fixed)
- For users of other browsers, content of the alert changes as well
[See all the alert content variants](https://www.figma.com/file/V5t7KOzC6PIX75L4dz8IFc/RFC-221-Browser-extension-improve-discoverability-and-awareness-Final-review?node-id=366%3A237) 

3. Dismissing the alert + tooltip
- When the user dismisses the alert, inform about the link in the user dropdown menu by showing a contextual tooltip
[View in Figma](https://www.figma.com/file/V5t7KOzC6PIX75L4dz8IFc/RFC-221-Browser-extension-improve-discoverability-and-awareness-Final-review?node-id=366%3A141)
- See the [video](https://www.loom.com/share/6e1d5d8b167f4d75a0efd1740c38da95) showcasing the animation or go to the [prototype](https://www.figma.com/proto/V5t7KOzC6PIX75L4dz8IFc/RFC-221-Browser-extension-improve-discoverability-and-awareness-Final-review?node-id=366%3A1&viewport=460%2C-1263%2C0.31671735644340515&scaling=min-zoom)
- Animation specs: click on the X button -> 100ms delay -> tooltip eases out (400ms) -> delay 50ms -> background behind the profile icon eases out (800ms) -> delay 3s -> both tooltip and background ease out (800ms)

As per @felixfbecker [comment](https://www.figma.com/file/V5t7KOzC6PIX75L4dz8IFc?node-id=366:237#42409520) this point was moved to the separate [issue](https://github.com/sourcegraph/sourcegraph/issues/14267) 
3. ~~Display [different alert content](https://www.figma.com/file/V5t7KOzC6PIX75L4dz8IFc/RFC-221-Browser-extension-improve-discoverability-and-awareness-Approved?node-id=558%3A17) if the admin turned on Sourcegraph on the code host level~~
- ~~‘Sourcegraph's code intelligence will follow you to your code host. Your site admin set up the Sourcegraph native integration for [code host]. Learn more or just try it out’~~
- ~~possible for GitLab, Bitbucket Server, and Phabricator~~

**Stats**
- Track the ‘Install...’ link clicks. Right now, the 'Install' button from the ‘Install extension’ popup clicks are tracked here:
https://sourcegraph.looker.com/looks/667
@ebrodymoore FYI

**Comment by AlicjaSuska** [comment]
As @felixfbecker suggested, I moved point 3 to issue #14267 @tjkandala

**Comment by AlicjaSuska** [comment]
@tjkandala please, see the updated copy for alerts:
- 'MRs' instead of 'PRs' for GitLab
- 'while browsing and reviewing code' for Phabricator

**Comment by tjkandala** [comment]
Closed by #14256
