### ISSUE TITLE
Ability to exclude personal repositories from being imported by Bitbucket by default

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#142]
Today, if you add a Bitbucket Server connection to Sourcegraph using an access token that has access to all repositories on Bitbucket (including personal repositories), the personal repositories will be imported.

An easy way to workaround this is by creating a "bot" account which just doesn't have access to those personal repositories.

But since this is not always ideal, it would be nice to have an option that explicitly excludes importing personal repositories from Bitbucket (even if the personal access token does have the ability to read them).

**Comment by nicksnyder** [comment]
Fixed in 2.12.0
