### ISSUE TITLE
Communicate the extension state by changing the icon

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#14203]
Part of [RFC 221](https://docs.google.com/document/d/19f4xleYBU1zZZdqMmXlLmFxeR-fwEpOwTOgViOFOnyo/edit?usp=sharing): Improve discoverability/awareness of the browser extension

**Description**

The browser extension icon should change its state to communicate that extension is on, off or that extension is not working properly.

**Design documentation**

Variants:
1. colorful logo - extension on, working properly or extension is not working but there is no action to be taken:
- when on sourcegraph.com
- for any domain except the code hosts
Note: it doesn't make sense to display the alert in those cases as the error cannot be resolved.
2. colorful logo + alert dot - extension on, not working properly, there is an issue to solve:
- disconnected from the URL (no green dot next to the URL)
- viewing the private repository that is not connected to Soucegraph
- additional permissions for the code host needed
3. gray logo - extension off
- when the toggle is set to 'off'

[View in Figma](https://www.figma.com/file/V5t7KOzC6PIX75L4dz8IFc/RFC-221-Browser-extension-improve-discoverability-and-awareness-Final-review?node-id=507%3A1402)

**Comment by marekweb** [comment]
We can use [`setIcon`](https://developer.chrome.com/extensions/browserAction#method-setIcon) to switch the icon.

We can also take a quick look at whether we can implement the alert icon using the badge feature. The badge is an indicator that is show on top of the icon, and it can contain a number or short string inside as well. That would be an alternative implementation compared to having the indicator icon contained in the icon image itself.

Reference: [`setBadgeText`](https://developer.chrome.com/extensions/browserAction#method-setBadgeText)
