### ISSUE TITLE
New extension page spacing is wrong

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#14216]
![image](https://user-images.githubusercontent.com/1976/94349661-81eeb380-fffb-11ea-918b-0ab529effd81.png)

https://sourcegraph.com/extensions/registry/new

Needs top spacing. Also should not show scrollbar. (It doesn't show it on macOS, but even on systems that do display scrollbars, it shouldn't show it.)

**Comment by tjkandala** [comment]
Fixed by #13699 and #14227

![Screenshot from 2020-09-28 02-59-00](https://user-images.githubusercontent.com/37420160/94400277-cf237000-0136-11eb-8ac9-a3118295d3be.png)
