### ISSUE TITLE
How can i enable guest user for my private instance?

### ISSUE THREAD

**Issue by undefined-moe** [sourcegraph/sourcegraph#14219]
I didn't find any description about this in the documentation.

It would be annoying when you send a link to others, and they have to register/login to see what is it.

**Comment by unknwon** [comment]
Sourcegraph does not support anonymous visits for private instances.  

I think this is a product question, cc @sourcegraph/product-team

**Comment by undefined-moe** [comment]
I solved it with creating a user names Guest and provide default cookie in nginx. thanks.
