### ISSUE TITLE
Record new Youtube video(s) that promote the browser extension

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#14234]
Part of [RFC 221](https://docs.google.com/document/d/19f4xleYBU1zZZdqMmXlLmFxeR-fwEpOwTOgViOFOnyo/edit?usp=sharing): Improve discoverability/awareness of the browser extension

**Description**

Showcase the improved flow in new video(s). It would be great to keep them in the loose format (as this [Campaigns walkthrough](https://zoom.us/rec/play/EoNNbAhN3MRNUhdtRGRpmZam3O-fjdURed11Z5JdytfEZrNDEi1gOjcGTDbg-sr-00kdragxTerD7mwu.XW2R9FPicHYJtlyV?continueMode=true&_x_zm_rtaid=xra366H4R5Gdu92soYzijA.1600247109357.c372d4c9bc8050e5d9c995b7f00c425d&_x_zm_rhtaid=885) - password available in the [Slack thread](https://sourcegraph.slack.com/archives/C02FSM7DU/p1599069723029500)

@sqs mentioning you to keep you in the loop on this one

**Comment by felixfbecker** [comment]
What are the videos for/where will they go? I.e. are they for the blog post, for the marketing homepage, for the docs, or for the browser extension post-installation page?

**Comment by kghopson** [comment]
If the video would be showcasing the improved flow, I think marketing or blog sounds like an ideal home. No reason why we could put it one place and reference it from others, though.

**Comment by AlicjaSuska** [comment]
I was initially thinking about just putting the video on our yt channel but I think it makes sense to add it to the blog post as well.

**Comment by felixfbecker** [comment]
Do we still want to do this? Who is the owner of this, you or me @AlicjaSuska ?
