### ISSUE TITLE
Update the ‘browser extension’ section in Sourcegraph Docs

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#14230]
Part of [RFC 221](https://docs.google.com/document/d/19f4xleYBU1zZZdqMmXlLmFxeR-fwEpOwTOgViOFOnyo/edit?usp=sharing): Improve discoverability/awareness of the browser extension

**Description**

Update the ‘browser extension’ section in Sourcegraph Docs

**Design documentation**

1. ‘Configuring the browser extension to use a Sourcegraph private instance’ section
- Add the information about the necessity to install Sourcegraph
- Make the title more general, for ex.  ‘Make it work on private code’
2. ‘Enabling the browser extension on your code host’
- Align this section with the ‘Make it work on your code host’ section from the installation page
- Use the code hosts logos for easier recognition
- Make it even more clear that extension is working on GitHub by default (users were skipping this information in the usability tests)
- Add flow of using ‘Grant permissions’ button in the extension settings window. As right-clicking on the extension and choosing ‘enable on this domain’ is more confusing, it should be presented as a secondary way to achieve this goal.
- Add a link to the [installation page](https://www.figma.com/file/V5t7KOzC6PIX75L4dz8IFc/RFC-221-Browser-extension-improve-discoverability-and-awareness-Approved?node-id=381%3A299) (labeled as ‘Starting guide’) so that users can come back to the page they’ve already seen
- Update videos after making changes to the UI in this project

**Questions to answer**
- To discuss: explain the difference between the native integration and browser extension (more detailed instructions on how to turn on the permissions in settings on GitLab)
- @AlicjaSuska TODO: Confirm the content with @kghopson

**Comment by kghopson** [comment]
Thanks for the heads up on this @AlicjaSuska! What is the estimated due date? Also, not sure if you intended this but the description is the same as #14229 

I'd like to put some time on your calendar to plan the content for the page. I'm assuming I'd also need to interview @felixfbecker for this as well.

**Comment by AlicjaSuska** [comment]
Fixed it, thank you @kghopson.

Browser extension improvements are the main focus for the Web Team for the next 2 weeks. I would like to have the Docs changes ready in 2 weeks as well to be able to release all changes connected to the topic at once. @kghopson I can prepare the proposition of changes to Docs and we can go from there. Is it ok with you?

**Comment by AlicjaSuska** [comment]
PR https://github.com/sourcegraph/sourcegraph/pull/14513

**Comment by AlicjaSuska** [comment]
Closed with #14513
