### ISSUE TITLE
js error: branch and path is

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#1425]
1. Go to https://github.com/rails/rails/blob/HEAD/activerecord/lib/active_record/connection_adapters/abstract/schema_definitions.rb#L446-L446
2. See error `branch and path is HEAD/activerecord/lib/active_record/connection_adapters/abstract/schema_definitions.rb, and branch is adb0c7bc51`

**Comment by felixfbecker** [comment]
No longer happens
