### ISSUE TITLE
Display different alert content if the admin turned on Sourcegraph on the code host level

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#14267]
Part of [RFC 221](https://docs.google.com/document/d/19f4xleYBU1zZZdqMmXlLmFxeR-fwEpOwTOgViOFOnyo/edit?usp=sharing): Improve discoverability/awareness of the browser extension

**Description**

Display [different alert content](https://www.figma.com/file/V5t7KOzC6PIX75L4dz8IFc/RFC-221-Browser-extension-improve-discoverability-and-awareness-Approved?node-id=558%3A17) if the admin turned on Sourcegraph on the code host level

**Design documentation**

- ‘Sourcegraph's code intelligence will follow you to your code host. Your site admin set up the Sourcegraph native integration for [code host]. Learn more or just try it out’
- possible for GitLab, Bitbucket Server, and Phabricator

**Comment by felixfbecker** [comment]
Note: There are multiple levels to this
- Have a setting to disable all alerts (easy)
- Decide dynamically based on events we received from the native integration (from the analytics DB etc), may require backend change to expose from the API (more involved)
