### ISSUE TITLE
Incognito mode: loading blob URL w/line number does not jump there

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#14260]
Repro:

1. Chrome: New incognito window
1. Go to https://sourcegraph.com/github.com/sourcegraph/sourcegraph@60f37656f10bfec49cc662aab09837e2b7b231a4/-/blob/.eslintrc.js#L53-62 (note that the URL has a line range)

Expected: browser window scrolls down to that line range
Actual: the browser window does not scroll down. If I visit the URL again, it does.

(I noticed this when I tweeted https://twitter.com/sqs/status/1310715558527074304 and tried that URL in incognito mode.)

It seems that the things that happen when a clean, incognito state browser visits a URL also cause the browser to not scroll down. There is a cookie warning and a browser extension notification that show up; either one could be the culprit.

**Comment by fkling** [comment]
Is this still an issue? Opening a new incognito window in Chromium and pasting this URL does scroll the lines into view for me.

**Comment by fkling** [comment]
Doesn't seem to still be an issue.
