### ISSUE TITLE
Create a guide for upgrading from 2.x to 3.0

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#1426]
3.0 includes many breaking changes:

- @slimsag Configuration moved to management console (mostly automatic, but requires the user to be informed about it existing)
- @tsenart `repos.list` being removed: https://github.com/sourcegraph/sourcegraph/pull/1391 users will need to manually add their repos back via the external services UI
- @nicksnyder How to add repositories via external services UI.
- @chrismwendt @felixfbecker Go and TS code intelligence being moved to extensions, needing to be spun up as separate Kubernetes services

What this immediately tells me is that users will need a guide for how to upgrade from 2.x to 3.0. I will compose this guide, but it would be great if each of you above could add notes, screenshots, etc. on what exactly users need to perform to migrate. Simply doing so as a comment in this thread is fine.

**Comment by tsenart** [comment]
Good call.

**Comment by tsenart** [comment]
## Removal of `repos.list` from site configuration

The top-level `repos.list` site configuration was removed in favour of each code-host's equivalent options, now configured via the new _External Services UI_ available at `/site-admin/external-services`. Equivalent options in code hosts configuration:
  - Github via [`github.repos`](https://docs.sourcegraph.com/admin/site_config/all#repos-array)
  - Gitlab via [`gitlab.projectQuery`](https://docs.sourcegraph.com/admin/site_config/all#projectquery-array)
  - Phabricator via [`phabricator.repos`](https://docs.sourcegraph.com/admin/site_config/all#phabricator-array)
  - [Other code hosts](https://github.com/sourcegraph/sourcegraph/issues/1324)

**Comment by ryan-blunden** [comment]
@slimsag Let me know if I can help.

**Comment by slimsag** [comment]
Sure, I'll tag you for review on what I send out. Also, if you are aware of any breaking changes I didn't mention in the description let me know.

**Comment by nicksnyder** [comment]
How to add repositories with external services.

**Comment by chrismwendt** [comment]
# Go code intelligence

- Remove the old `langservers` entry for Go from https://sourcegraph.com/site-admin/configuration
- Follow https://github.com/sourcegraph/lang-go#usage-on-sourcegraph-3x-instances which walks you through deploying the Go language server locally in Docker or on Kubernetes and adding the appropriate Sourcegraph settings

**Comment by slimsag** [comment]
Not having any docs here would be very bad for existing users, so I am tagging as a release blocker.

**Comment by nicksnyder** [comment]
My proposal is to add a migration section to the CHANGELOG

**Comment by slimsag** [comment]
I think linking to a separate markdown file in our docs from the changelog
would be better, this is too much information to cram into our changelog I
feel
