### ISSUE TITLE
TypeScript go to definition just goes to import

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#14272]
https://github.com/sourcegraph/sourcegraph/pull/14256/files#diff-389012daf6ffbfb95a148bde9e6800bbL145

![image](https://user-images.githubusercontent.com/10532611/94541302-b656af80-0247-11eb-9458-b7759f877b8b.png)

Go to definition on `LinkOrButton`, it just jumps to the import in the same file, instead of to https://sourcegraph.com/github.com/sourcegraph/sourcegraph@b2cd5ddf5a013b12df9691c670d8644dcf26a936/-/blob/shared/src/components/LinkOrButton.tsx#L46

**Comment by macraig** [comment]
Moving to https://github.com/sourcegraph/lsif-node/issues/149
