### ISSUE TITLE
Codecov extension not showing "Coverage: N%"

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#14283]
https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/cli/config.go

![image](https://user-images.githubusercontent.com/1976/94568061-eb9bd700-0220-11eb-864b-3115c4d0a9be.png)

Likely caused by #14088, which I just merged. Will investigate in a few hours.

**Comment by dadlerj** [comment]
Interestingly, it is still visible on GitHub, even while it's not on Sourcegraph.com

![image](https://user-images.githubusercontent.com/5589410/95505675-99b32980-0963-11eb-8431-665ce1032725.png)

**Comment by sqs** [comment]
It would be great for someone else to look into it if this fix is needed before the weekend. If so, unassign me.

**Comment by dadlerj** [comment]
Not urgent for me
