### ISSUE TITLE
Update documentation to reflect management console

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#1428]
- [x] Update all docs to reference the management console.
    - [x] https://github.com/sourcegraph/deploy-sourcegraph/blob/master/docs/configure.md#update-site-configuration That section should now link to documentation on docs.sourcegraph.com about the site admin config page + the management console; That section should probably be updated with information about how to access the management console (port-forwarding, changing the password in a k8s context, etc.)
    - [x] All references to the site configuation file in the rest of https://github.com/sourcegraph/deploy-sourcegraph/blob/master/docs/configure.md need to be updated to stop refering to the config-map
    - [x] The migration path from the old https://github.com/sourcegraph/deploy-sourcegraph/blob/181c382d7d737cc0178bb94c6eb98da5b492a0de/base/config-file.ConfigMap.yaml to the management console needs to be documented
    - [x] https://github.com/sourcegraph/deploy-sourcegraph/blob/master/docs/configure.md#add-license-key
    - [x] Make any necessary updates to deploy-sourcegraph and documentation there (e.g. migration steps if any).
- [x] Clearly document that some properties (e.g. `externalURL`) require the frontend server to be restarted. This is a known bug: https://github.com/sourcegraph/sourcegraph/issues/517
- [x] Clearly document how migration occurs:
    - [x] Add management console section to https://github.com/sourcegraph/deploy-sourcegraph/blob/master/docs/sourcegraph-3.0.migrate.md
    - Users should expect to now visit the management console for certain things
- [x] Update CHANGELOG to reflect management console change.
- [x] Clearly document how the management console works
    - The password is auto-generated, accessible via site admin area.
    - The SSL cert is self-signed, must accept in browser.
- [x] ~Is a blog post desirable? cc @sqs~ 
- [x] Document how to access dogfood management console. https://sourcegraph.slack.com/archives/C0EPTDE9L/p1547161784030100

Note to self: See also notes about documentation under https://github.com/sourcegraph/sourcegraph/pull/966

**Comment by sqs** [comment]
>  Is a blog post desirable? cc @sqs

We will include it in the 3.0 blog post, so no separate blog post is necessary.

**Comment by slimsag** [comment]
I will finish this before EOD, but it is actually mostly independent from 3.1 since it is all in deploy-sourcegraph aside from that one note about the `externalURL` known bug.

**Comment by slimsag** [comment]
https://github.com/sourcegraph/deploy-sourcegraph/commit/8f6153c712d2ea93e871633441c3bbfe146fd7cc#diff-91cd69df8ac1d751bbe7c7b38b6cab1a

**Comment by slimsag** [comment]
https://github.com/sourcegraph/deploy-sourcegraph/commit/f689a6c5f8088641322de12bbf12696dfa75a2a9#diff-91cd69df8ac1d751bbe7c7b38b6cab1a

**Comment by slimsag** [comment]
https://github.com/sourcegraph/deploy-sourcegraph/commit/c347552c949bf1f2fbedf48a6a8b9ee88998b935

**Comment by slimsag** [comment]
https://github.com/sourcegraph/deploy-sourcegraph/commit/337e7c5c4673bbcf58843ebde42e130df7ef5bb5#diff-dbd0ee70a73f79c75df3569281ec56bb

**Comment by slimsag** [comment]
https://github.com/sourcegraph/sourcegraph/pull/2775
