### ISSUE TITLE
Collapsible Tree view for Symbols 

### ISSUE THREAD

**Issue by poojaj-tech** [sourcegraph/sourcegraph#14290]
#### Feature request description
Customer Feature Request

> It would be great if the list of symbols is more like a tree, i.e. class node can expand to list class variables and methods, with private / public/ protected access indication, and can be collapsed to declutter the view.
> would be great to list the function / method arguments instead of the "path" of the symbol; I already know that the symbol is in this file most of the time
> personal preference is to have this on the right side to match how IDEs usually display this (i.e. sublime and VS Code usually display this on the right). There's usually a ton of white space on the right side of the screen that can be used to provide extra info

#### Additional context

> here's a file that has 2 classes, the symbols view is long enough to fill up the entire screen & then some, so I have to scroll on it to get to the bottom of that list. If classes were nodes, I can then collapse long classes to save space to view other classes
> 
> https://sourcegraph.com/github.com/ray-project/ray/-/blob/python/ray/tune/trial.py

**Comment by poojaj-tech** [comment]
Related to #4544

**Comment by poojaj-tech** [comment]
Note: The customer didn't notice the existing "Symbols" tab until I shared a screenshot with the tab open. Perhaps our UI is a bit hidden or the naming _Symbols_ isn't immediately clear for users.

**Comment by poojaj-tech** [comment]
Update: The Symbols view is just a little hard to find and but the "Symbols" view does exactly what they think it would do. The naming isn't confusing for them which is the possibility I mention above.
In this case, they rarely hop repos so that's one reason their attention might not be drawn to the left side of the view where the Symbols tab lies.

**Comment by macraig** [comment]
Also requested by SourcegraphWeb user

**Tree view of classes and methods**
My use case here is when I'm exploring a file with multiple classes, I'd like to collapse the classes in the symbol sidebar that I'm not viewing, so I can just look at the classes that I care about and what methods they have. For example, in [this file](https://sourcegraph.com/github.com/drofp/RoadRun/-/blob/include/game.h#L17:7-17:11) for one of my classes, I'd like to have a collapsable section in the sidebar for the "Game" symbol that can hide all the variables and member functions within it. It would be even more impressive and useful if this could be done in [the equivalent source file](https://sourcegraph.com/github.com/drofp/RoadRun/-/blob/src/game.cc#L96:12-96:27), so I could quickly view which functions have been defined in the source file, and which class they belong to.

**Comment by macraig** [comment]
Feature request is now being tracked in [Productboard](https://sourcegraph.productboard.com/feature-board/1825051-code-intel/features/5789964/detail).

**Comment by FranklinYu** [comment]
Hi, the product board seems a private tracking platform. Would highly appreciate if we have some public tracking for the feature.

**Comment by macraig** [comment]
Hi @FranklinYu, thanks for your feedback! We're currently tracking feature requests that have no estimated delivery date in Productboard, but we'll re-open this issue once the feature is prioritized and we have a better idea of when we'll be able to start working on it. 

We are very interested in adding features like this one to our product but have been making some tough roadmap prioritization decisions based on our team's bandwidth. This will change soon (Sourcegraph is growing fast!) and we'll likely revisit implementation in the near future.
