### ISSUE TITLE
Sourcegraph should log and email important encryption events

### ISSUE THREAD

**Issue by chayim** [sourcegraph/sourcegraph#14303]
Part of security audit requirements involves process tracking.  These practices require at a minimum the following emails should be sent out as part of these operations - indicating events of interest.

**Job submission** - Once an encryption (including key rotation) job has been submitted, an email will be sent to the site admin, confirming this operation has been scheduled.  The email would include a link to the administration page allowing cancelling this job. The reason for this need, is to solve the security concern whereby a bad actor might gain authentication to Sourcegraph. This event should also be logged as an event_log.

**Job start** - At the beginning of the encryption process itself, an email is sent to the site-admin. This event should also be logged as an event_log.

**Job completion** - Upon the completion of the encryption operation, an email would similarly be sent to the site-admin.  The added advantage of this element, is that it supports site-admins opting to re-encrypt data immediately in the rare need where this is occurring. This event should also be logged as an event_log.

**Comment by unknwon** [comment]
Closing as we're no longer pursuing RFC 214
