### ISSUE TITLE
A bad externalURL can kill the frontend, inherently killing the management console

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#1431]
- This issue only affects single container deployments.
- Per config usage guidelines (see #1430), bad config should NEVER take down a process of ours. It should just 'do nothing'.

**Comment by slimsag** [comment]
Yes, it is -- it would crash the container and prevent you from accessing the management console to correct the issue.

I will commit to fixing this before we cut the release (over the weekend if necessary)

**Comment by nicksnyder** [comment]
What happens, and what is the resolution in 2.x if there is a bad externalURL?

**Comment by nicksnyder** [comment]
Can you define what you mean by "bad externalURL"? Does this mean `https://notavaliddomain.com` would be a problem or only if the url is misformatted like `oops://not? actually a&& url`?

It is unclear to me if we should actually delay cutting the release if this is not fixed by tomorrow.
