### ISSUE TITLE
Management console should indicate license status

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#1432]
Today, the license status is indicated via the site config area, but it is configured through the management console. This is a bad UX but not too bad.

Customers:

- https://app.hubspot.com/contacts/2762526/company/419771425

**Comment by slimsag** [comment]
I think we should defer this until 3.1 to ensure it meets our quality bar, see my comment here https://github.com/sourcegraph/sourcegraph/pull/2097#issuecomment-459642742 cc @nicksnyder

**Comment by nicksnyder** [comment]
@slimsag @attfarhan Given that this is moved to 3.1, can you work out whether you think it makes sense for Farhan to continue working on this or whether @slimsag should own finishing this for 3.1?

**Comment by slimsag** [comment]
I think it makes sense for Farhan to continue owning the frontend portion, and for me to own the backend portion. We'll work together to land it.
