### ISSUE TITLE
search: err from searchFilesInRepos ignored for structural search

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#14338]
I think this was a mistake from the refactoring done around how we call each search type.

https://github.com/sourcegraph/sourcegraph/blob/3e960ea1437d3c0e5beb9a6d22f400896d8f48ab/cmd/frontend/graphqlbackend/search_results.go#L1577

**Comment by stefanhengl** [comment]
This has been fixed through various refactors.
