### ISSUE TITLE
repo-updater: Factor out common code between SyncExternalService and syncRepo

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#14346]
They have large chunks of code that are very similar. Ideally, we should be able to call syncRepo from within SyncExternalService.

**Comment by ryanslade** [comment]
The functions have now diverged enough that I don't think it makes sense to try and factor out common code. There are only a few lines of code in common now and it'll probably just end up being harder to manage.

Since this work isn't actually going to be done, shall I close and remove it from the milestone @tsenart?

**Comment by tsenart** [comment]
> Since this work isn't actually going to be done, shall I close and remove it from the milestone @tsenart?

It makes sense to me to invest the time in https://github.com/sourcegraph/sourcegraph/issues/14369 instead, and I think the code simplifications shall follow.

**Comment by ryanslade** [comment]
I was planning to work through the DB interface debt work with @asdine as we can divide those up quite easily and hopefully make some good progress there. 

Specifically for this issue, does it make sense to remove it from the milestone?

**Comment by ryanslade** [comment]
Closing and removing from milestone as we no longer need to do this
