### ISSUE TITLE
Validation errors for critical config are only displayed in the site config area

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#1435]
When there are validation errors in the critical config, the management console should show them. In general there is some question about how to present validation errors (does the mgmt console show BOTH site and critical validation errors? Only one? What about the site config area? etc.)

**Comment by keegancsmith** [comment]
I was confused by this since the site-admin config area for sourcegraph.com was showing 3 config errors, but for keys only in management console.

**Comment by slimsag** [comment]
This is bad, but something that can be fixed in 3.1 rather than 3.0.

**Comment by sqs** [comment]
This is less important than the other work planned for 3.2, so I am backlogging this.
