### ISSUE TITLE
Add alert when we hit the site wide limit on user added repos

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#14377]
The limit is configurable and we should surface it to site admins. 

We need to decide whether we report the status back to frontend during sync or we have a periodic check in frontend. Either way, we need to perform a DB request.

This was originally meant to be added as part of https://github.com/sourcegraph/sourcegraph/issues/14043 but pulling out into its own issue so that the main PR to add limits is not blocked.

**Comment by tsenart** [comment]
Superseded by #14442
