### ISSUE TITLE
Tooltips are lost in dark mode and need a color in light mode

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#14384]
![image](https://user-images.githubusercontent.com/539268/94955118-f368af00-049e-11eb-8d50-ba5d14858677.png)

Can we set these tooltips to $grey-19 in both light and dark modes?

Intended color:

![image](https://user-images.githubusercontent.com/539268/94956400-f2388180-04a0-11eb-9359-c602d5d6da26.png)

**Comment by limitedmage** [comment]
This is the default Bootstrap tooltip styling and I'm not sure what is the best way to modify Bootstrap's default styles. Maybe @sourcegraph/web team can help with this instead.

**Comment by felixfbecker** [comment]
@limitedmage like most things in Bootstrap looks like this is configurable with a Sass variable: https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/twbs/bootstrap%24+-f:dist+%24tooltip-bg&patternType=literal :)
