### ISSUE TITLE
Include database versions in ping data

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#14405]
In order to confidently increase our [Minimum Supported Version](https://docs.sourcegraph.com/dev/postgresql#version-requirements) of Redis and Postgres, we need to know what our customers are actually relying on. Instead of sending them a survey, we can just gather this information automatically and include them in pings.

@flying-robot: Tentatively assigning to you for next cycle (starting this Wednesday), since you touched this area of the system recently and I think you could get this done easily. You can ready about the [Life of a Ping](https://docs.sourcegraph.com/dev/architecture/life-of-a-ping) for the full picture.

@ebrodymoore: Do we need to do anything beyond the code changes? (i.e. Looker, Dataflow schema, doc updates) I thought I saw a dev guide somewhere on how to add new data to pings, but can't find it.

**Comment by ebrodymoore** [comment]
I think [this hb page](https://about.sourcegraph.com/handbook/engineering/adding_ping_data) on adding pings is what you were looking for.

We do need to update the BigQuery schema before the PR is merged, and then I'll need to update Looker. @flying-robot please let me know when you're ready to merge so I can make the change!

**Comment by arussellsaw** [comment]
there are two different pools in the redispool package, should we be reporting the versions of both these pools separately? https://sourcegraph.com/github.com/sourcegraph/sourcegraph@2d9f87e/-/blob/internal/redispool/redispool.go#L77-L103

**Comment by tsenart** [comment]
> should we be reporting the versions of both these pools separately?

In practice, I don't believe there will be customers using different Redis versions for each of these, but to be double sure, yeah, we should, if it's not  too much extra work.
