### ISSUE TITLE
Editor extensions fail to generate correct URLs when jumping to Sourcegraph

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#14423]
Reported by https://app.hubspot.com/contacts/2762526/company/555146901

JIRA ticket: https://sourcegraph.atlassian.net/jira/servicedesk/projects/SG/queues/custom/1/SG-364

>Hi,I am trying to use sourcegraph plugin for vs-code. When I try to use Command Palette, Open in sourcegraph it adds a $HOSTNAME/$LOCAL-ORG-NAME/ to the URL and I get a 404 not found. This is my setting:
>
>$REDACTED

After clarifying the URL that opened, we found:

>Correct url: https://sourcegraph.example.com/$SG-ORG-NAME/$REPONAME/-/blob/README.md
>
>When opened through VS code plugin: https://sourcegraph.example.com/$HOSTNAME/$LOCAL-ORG-NAME/$REPONAME@master/-/blob/README.md

(obviously I've redacted a lot here... Perhaps easier to check the JIRA thread above)

My takeaway from the above: the site admin has set `repositoryPathPattern` to convert URLs from $HOSTNAME/$LOCAL-ORG-NAME/$REPONAME to $SG-ORG-NAME/$REPONAME instead.

After digging in to our [editor link handler](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/app/editor.go), my hunch is that the lookup breaks because the repo names are different (?). 

It looks like at some point in the past we anticipated that this would happen, and added support for the editor to pass in the pattern for replacing links: [commit that added it](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/dc9b5d7ea0642060ddffa764514ce066c48928c4?visible=2), and [where it is used](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@13b8964f6f38b516e72937aa572844ce842cb4af/-/blob/cmd/frontend/internal/app/editor.go#L304:5). 

Unfortunately it seems that this is not used anywhere in our VS Code plugin: https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/+repo:vscode+hostname_patterns&patternType=literal

As a potential workaround, I'm going to ask the user to use the `sourcegraph.remoteUrlReplacements` property (https://marketplace.visualstudio.com/items?itemName=sourcegraph.sourcegraph) to replace `$HOSTNAME/$LOCAL-ORG-NAME/$REPONAME` with `$SG-ORG-NAME/$REPONAME` and see if that helps.

**Comment by dadlerj** [comment]
Similar report from https://app.hubspot.com/contacts/2762526/company/693777200

This user is using the IntelliJ/JetBrains plugin.

This company is using `src serve-git` to convert Perforce repos _and branches_ to git repositories in the Sourcegraph backend, so repo and branch naming is very different on the app than locally… We’d need some advanced repo/rev rename field (along the lines of how the `repositoryPathPattern` config option works in the webapp) to map from local git remote name to Sourcegraph URL. 

E.g. some field like (totally made up, and not actually what they need): `repoNameMapping: "{host}/hardcodedRepoName/{rev}@main"` or something, where literal strings can be mixed with variable interpolation, where _revisions_ can be used in interpolations, etc.


Details from the user:

>Perhaps I need more in the URL?  The net effect is that I have copy link to file and open file enabled but not search selection or search in repository.  Neither option that is enabled seems to do anything.

>Update:  Based on documentation, I tried selecting text and both search selection and search in repository worked.  Neither of the other options seems to do anything.  My searches are not focused on the branch I care about - I don't know if that's something I adjust via a project setting or if I need to set something on the site.  My top hits are all on the REDACTED branch and I really just care about REDACTED.

>The documentation says `By default, the plugin will use the origin git remote to determine which repository on Sourcegraph corresponds to your local repository. If your origin remote doesn't match Sourcegraph, you may instead configure a sourcegraph Git remote which will take priority.` but I don't know how to do that and this isn't git, it's perforce.

See more in the thread: https://sourcegraph.slack.com/archives/C011899KB6U/p1602270142030200

**Comment by dadlerj** [comment]
Similar report from https://app.hubspot.com/contacts/2762526/company/557475882

>Hi folks, was attempting to use option+A to open the file on sourcegraph with the sourcegraph extention, but it's routing very strangly. option+S correctly does the search with the URL http://sourcegraph.REDACTED.com/ but if I try to auto-open a file it's routing to https://sourcegraph.com/github.com/ORG/REPO@BRANCH/-/FILE with a 404 error.

**Comment by felixfbecker** [comment]
If what @dadlerj says above was the issue, this should have been fixed in https://github.com/sourcegraph/sourcegraph-vscode/pull/122 (version 1.2.0 of the extension). We also made some improvements in the backend handling in Sourcegraph. @dadlerj could you ask the customer if they are still experiencing this issue with the latest extension version 1.2.0? Closing for now.
