### ISSUE TITLE
unexpected panic error in sourcegraph/lang-go extension

### ISSUE THREAD

**Issue by yevbar** [sourcegraph/sourcegraph#1442]
- **Sourcegraph version:** 
- **Platform information:** 

#### Steps to reproduce:

1. [https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/migrate-vanity.go#L37](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/migrate-vanity.go#L37)

#### Expected behavior:

No errors, hovers and console don't let out any error messages

#### Actual behavior:

The following message comes after a hover event

```
unexpected panic: runtime error: invalid memory address or nil pointer dereference
```

**Comment by yevbar** [comment]
For people that run into a similar situation, here was the reason for my error:

In my access tokens page, there wasn't a token labeled `go`. To view this on your account, go to `https://sourcegraph.com/users/USERNAME/account/tokens` and you should see a list of existing tokens on your Sourcegraph account.

If this is your issue, then here are the steps to resolve it:

1) Go to `https://sourcegraph.com/users/USERNAME/settings`
2) Delete the entry with the key `go.accessToken`
3) Go to a `Go` file (or reload the page with one if you're coming from seeing the issue in your console)
4) An access token labeled `go` should be in your account and there should also be a value with the key `go.accessToken` in your settings
5) You should no longer see the error message in your console

**Comment by chrismwendt** [comment]
I confirmed this is caused by revoking the access token that sourcegraph/lang-go creates for the language server. Tracking the fix in https://github.com/sourcegraph/lang-go/issues/8
