### ISSUE TITLE
Firefox Sourcegraph Extension Does Not Work

### ISSUE THREAD

**Issue by postables** [sourcegraph/sourcegraph#1443]
Sourcegraph extension version: v18.12.13.848

OS: Pop!_OS 18.04 LTS (ubuntu fork)

Browser: Firefox 64.0 (Quantum) 64bit

Browser Extensions: NoScript (disabled it for this), HTTPSEverywhere (disabled it for this), UBlockOrigin (disabled it for this)

#### Steps to reproduce:

1. Install firefox extension
2. Enable extension on github domain
3. Browse to any github repo (such as https://github.com/RTradeLtd/Temporal)

#### Expected behavior:

1. Code insights, etc..

#### Actual behavior:

Nothing happens whenever I browse to pages, and it doesn't appear that the extension actually loads

Of note, the browser console log displays `Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).`

**Comment by ijsnow** [comment]
Could you uninstall the extension and reinstall it and try again without clicking "enable on this domain"? [We have access to run on all domains because of a bug in Firefox](https://github.com/sourcegraph/sourcegraph/issues/760) so you don't need to click that button. We shouldn't show it in FF.

**Comment by postables** [comment]
:cry:  tried, and got the same issue.

**Comment by AlexNPavel** [comment]
I'm also having this problem with the latest extension and Firefox 64 on Fedora. Occassionally I will get a small box with "Go to Definition" and "Find References", but the usual code insights/documentation don't appear, and most functions don't have any hover action

**Comment by AlexNPavel** [comment]
This same issue happens on the sourcegraph page (without the content security policy error in the console). I'll attach a sceenshot as an example:
![screenshot from 2018-12-19 12-00-20](https://user-images.githubusercontent.com/3813031/50244794-af69f000-0385-11e9-93c1-2b8d6a04b7a7.png)

**Comment by AlexNPavel** [comment]
I was able to get it working by going to the extension's settings and enabling "Use extensions" in the "Experimental configuration" section. It is now working as expected and showing the function signatures and documentation when I hover over a function.

**Comment by AlexNPavel** [comment]
It actually works even without the Use extensions config enabled now... I don't know why but it just works now. However, it does not work in PRs if I am logged in. It works in PRs if I am logged out though. Should I open a separate issue for that? One of my coworkers was experiencing that as well, in both Chrome and Firefox

**Comment by postables** [comment]
Update: It seems installing sourcegraph firefox sort of works. whenever I view a repo on github the `view on sourcegraph` button pops up, but there is no in-github code intelligence.

**Comment by ijsnow** [comment]
@postables, what language are you trying to use? Could you go to https://sourcegraph.com/extensions and make sure that that language's extension is enabled? We recently switched to using Sourcegraph extensions rather than built in language support. [Read more on extensions here.](https://docs.sourcegraph.com/extensions)

@AlexNPavel, it seems like your problem is actually with the go extension. Could you make sure [the correct extension is enabled?](https://sourcegraph.com/extensions/sourcegraph/lang-go) cc @chrismwendt

**Comment by ijsnow** [comment]
Moved to backlog because this seems like configuration errors.

**Comment by chrismwendt** [comment]
I installed the latest XPI and was able to get code intelligence on https://github.com/RTradeLtd/Temporal/blob/V2/mail/mail.go while signed in or out of either GitHub or Sourcegraph (all 4 combinations). My Sourcegraph URL is https://sourcegraph.com

![image](https://user-images.githubusercontent.com/1387653/50615328-ed443980-0e98-11e9-9375-6f98de1e8138.png)

@postables can you try completely uninstalling the Firefox extension and reinstalling it? Post a screenshot like I did and provide a link to the file in which you're expecting to see code intelligence.

**Comment by postables** [comment]
Sorry for the delay, here is the configuration ![](https://gateway.temporal.cloud/ipfs/QmTpoZyWPFgg8nM9LCdoeFH99nhTFNF6qX8zHVJjjmFXxK). I also tried https://github.com/RTradeLtd/Temporal/blob/V2/mail/mail.go and this didn't work.

For reference, on google chrome it works whether or not im signed into, or signed out of github.

**Comment by chrismwendt** [comment]
v19.1.7.543 works for me. I did not see that error `Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).`, but I don't know what the relevant difference between our setups is. I'm also Firefox 64 but on macOS 1.14.2. I wonder if Firefox on Linux has stricter CSP by default, and whether or not that could be relaxed.

**Comment by iMouath** [comment]
I ran into this issue as well. Only workaround I found is by setting ```network.websocket.allowInsecureFromHTTPS``` in ```about:config``` to ```true```

source: https://stackoverflow.com/questions/11768221/firefox-websocket-security-issue/12042843#12042843

note: I've a self hosted instance installed behind a traefik proxy

**Comment by sqs** [comment]
@iMouath Is your Sourcegraph URL `http://` or `https://`?

**Comment by iMouath** [comment]
@sqs `https://` I set it through the console "externalURL" option

It's a valid letsencrypt SSL, I used traefik as proxy.

Looking at the logs all the requests are going through https (to sourcegraph.com)

**Comment by sqs** [comment]
@iMouath Thank you for the followup. So it is working for you now that you're using `wss://` for the Go language server? (Indeed, this sounds like a different issue.)

**Comment by sqs** [comment]
@postables Are you still unable to use the Firefox extension? We have not been able to repro your issue. Do you see any errors? Can you try it with all other Firefox extensions disabled (in case you didn't already)?

**Comment by aravindhp** [comment]
I am running into similar issues with the extension v19.5.16.1439 i.e. I am unable to configure it and have the code insights working. If I try to make it connect to https://sourcegraph.com I get an error as show below:
![image](https://user-images.githubusercontent.com/11638995/58203615-8fc65300-7ca8-11e9-8822-e5f1d31f56b8.png)

Not sure where I can get more details about the error. I have tried uninstalling and reinstalling extension and running it in isolation with all other extensions disabled but I have not been able to resolve the issues. I am on FireFox 66.0.5 on Fedora 30. LMK if you need more info.

**Comment by AlexNPavel** [comment]
@aravindhp Yeah, I had that same issue (on the same version of firefox and fedora). I was able to fix it by building the extension manually from the current git and that worked, so there is a bug in the version currently being distributed for firefox (v19.5.16.1439) that is fixed on master.

**Comment by chrismwendt** [comment]
@AlexNPavel @aravindhp Version v19.5.22.2203 has been released with the fix https://github.com/sourcegraph/sourcegraph/pull/4117 My apologies for not publishing this sooner.

**Comment by slimsag** [comment]
Closing since this appears fixed. Re-open or comment if I am wrong.
