### ISSUE TITLE
Allow all Sourcegraph teammates to add their own public repos in the Cloud env

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#14441]
This involves manually updating user tags in the database.

**Comment by ryanslade** [comment]
I've just run a query to allow all current site admins to add their own user owned code hosts. The original plan was to select users have verified sourcegraph.com e-mail addresses but I noticed a lot of us haven't done that, myself included.

The current list of site admins seems to cover most people and anyone we've left out can reach out to be added.
