### ISSUE TITLE
Add ability to syntax highlight read-only search requests displayed in the app

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#14443]
raised by @limitedmage 

Some of the search requests displayed on the repogroup homepage or on the new enterprise homepage are partially highlighted, but this highlighting is hardcoded. Other search requests (like in the "Recent searches" panel) have no highlighting:

![image](https://user-images.githubusercontent.com/1741180/95218236-5dad8680-07f4-11eb-97f9-54b930fb5ddb.png)

https://sourcegraph.com/github.com/sourcegraph/sourcegraph@089083a29336eaacdf7206a91bbd7b5e26b96d32/-/blob/web/src/search/panels/RepositoriesPanel.tsx?subtree=true#L95-98

We should probably have a `<HighlightedSearchQuery/>` (or similar) component that, given a query string, will rely on the frontend query parser to display it as a fully syntax-highlighted search query, consistent with what is shown in the query input.

**Comment by lguychard** [comment]
This is not an immediate priority, but we should do it eventually (possibly after @rvantonder has ported the full query parser to the frontend: https://github.com/sourcegraph/sourcegraph/issues/14016)

**Comment by limitedmage** [comment]
Required for #14393

**Comment by limitedmage** [comment]
Required for #14383
