### ISSUE TITLE
Combine existing panels on repo page, code insights and views into one customizable grid

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#14459]
The repo page could be more useful. One way to do that is to display repo info using the code insights API. 

We could display it in widget-like boxes  (like the branches or tags box show). This has the further benefit of making users familiar with these "customizable" boxes if part of code insights eventually lives here. 

![image](https://user-images.githubusercontent.com/11967660/95269907-4ae48300-07ef-11eb-843a-74fd7c5e89ac.png)

#### Additional context

Originally prototyped by @sqs on `sqs/exp/search` branch in files like `treeDependencies.tsx`

#### Next Steps in order to Prioritize

- Synthesize the existing problems with the repo page, as well as what it does well, so we don't impact the successful interactions the page enables. 
- Commit to a wider use of this box/widget UI model

**Comment by felixfbecker** [comment]
Just noticed this is largely a duplicate of https://github.com/sourcegraph/sourcegraph/issues/15057
