### ISSUE TITLE
Extension manifest should be validated before upload and not affect other extensions.

### ISSUE THREAD

**Issue by francisschmaltz** [sourcegraph/sourcegraph#1445]
If an extensions has a bad manifest it affects Sourcegraph instances using extensions from sourcegraph.com. 

We should:
1. Validate manifests
2. Prevent incorrect manifests from affecting other extensions.

**Comment by sqs** [comment]
1 is not ideal because we still need it to be robust in case we forget validation cases or ever change the schema. #1447 does 2.

**Comment by sqs** [comment]
As Francis pointed out, we do need to do 1 before we return the JSON data to other instances. So I added that to #1447
