### ISSUE TITLE
Campaigns beta message box has a white background in dark mode

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#14450]
#### Steps to reproduce:

1. Make sure your theme is in dark mode
2. Visit [your private sourcegraph domain]/campaigns, like https://sourcegraph.test:3443/campaigns

#### Expected behavior:

You would see a dark-background box, like the "create your own extensions" box on the extensions page in dark mode.  

#### Actual behavior:

We see a white-background box regardless of theme.

**Comment by chrispine** [comment]
This looks fixed to me, so I'm closing it.
