### ISSUE TITLE
New dark mode on docs flashes white background when switching pages

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#14492]
![2020-10-07 22 49 07](https://user-images.githubusercontent.com/10532611/95386313-65058a80-08ef-11eb-90ac-b842f95928f5.gif)

**Comment by sqs** [comment]
I think I need to move the script tag to the head so it doesn't render the first frame pre-styling. Thanks for filing.

**Comment by felixfbecker** [comment]
We could also remove the theme switcher and make it CSS-only :)
Would allow us to send a `<meta>` tag too to have the browser pick better default colors and to easily include screenshots for both themes using `<picture>`.

**Comment by sqs** [comment]
I like the switcher, personally. People get confused without it in my experience - thinking they are on a different site when they visit on another device, for example. I wish browsers had a native control for this.

Re: screenshot, would that be for opengraph?

**Comment by felixfbecker** [comment]
> People get confused without it in my experience - thinking they are on a different site when they visit on another device, for example.

Interesting, I've never felt this way myself or heard that from anyone. As a data point, Twitter adapts to the system light/dark theme, but the manual override toggle is burried deep in the account settings (i.e. not visible on the home page). Obviously Twitter is more recognizable but the general website behavior is present on popular sites too.

> I wish browsers had a native control for this.

Same, I wish the browser would allow to "override" the system theme through it's UI and remember the choice per-site, the same way it remembers zoom levels per site. That way we wouldn't ever have to implement toggles and could use CSS directly for everything.

> Re: screenshot, would that be for opengraph?

No, to have screenshots of the product that match the doc's theme. I was referring to this technique:

https://github.com/sourcegraph/sourcegraph-code-stats-insights/blob/9d128789fb363a08c21a7a35f8dd94af671da496/README.md#L6-L10

Check it out on https://sourcegraph.com/extensions/sourcegraph/code-stats-insights when switching the OS theme.

Would be possible with some CSS classes too of course.

**Comment by sqs** [comment]
I didn't know about the color-scheme meta tag - neat. And yeah, it would be great if our screenshots adapted to the theme. I fixed the immediate issue in #14586, and we can do the other things later.
