### ISSUE TITLE
 Why is viewing a list of repositories that refer to another repository disabled?

### ISSUE THREAD

**Issue by hsluoyz** [sourcegraph/sourcegraph#145]
- **Sourcegraph version:** Sourcegraph.com
- **Platform:** Google Chrome Version 68.0.3440.106 (Official Build) (64-bit)

In [this blog](https://about.sourcegraph.com/blog/see-how-many-people-use-your-library-with-sourcegraph-badges/), it said that:

``
Update (September 20, 2017): Viewing a list of repositories that refer to another repository is currently disabled. It will be added back soon. Viewing function call sites across repositories is still supported.
``

This is the feature I like most. Because my project is a library. It's very important for me to know how many developers are using my project. And SourceGraph is the only tool that can achieve it very well.

So can you add this feature back to ``Sourcegraph.com``? Thanks.

**Comment by beyang** [comment]
Thank you for the feedback. Yes, we are still planning on adding this back.

@chrismwendt any plans to support repo-level stats as an extension point? This could be something that the cross-repo code intelligence extensions provide (in addition to the cross-repo j2d/find-refs functionality).

**Comment by sqs** [comment]
This will become possible again for public code when @chrismwendt 	adds external references support to the Go extension. The Go extension work is in progress, and he'll begin external references support soon. I will post an update then. I will do the final work of updating the blog post mentioned above and other relevant places.

**Comment by hsluoyz** [comment]
Thanks for the update :) Look forward to this feature.

**Comment by nicksnyder** [comment]
@sqs Can you post an update here?

**Comment by sqs** [comment]
Sorry, this is taking longer. I am moving to backlog to reflect that we have not been able to prioritize this yet.
