### ISSUE TITLE
GitHub GraphQL ratelimit is not respected

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#14526]
The calls to the GitHub GraphQL API in our GitHub client code don't respect the rate limit imposed on us by them.

Problems this causes:
- The reconciler can run into rate limiting issues
- Listing repos can fail
- Syncing changesets in the background can fail (but we do have a self-imposed rate limit here AFAIK)

What we observed so far:
- We do have two rate limiters in the client, one self imposed `rateLimiter`, one based on GitHubs rate limit `rateLimitMonitor`
- The `rateLimiter` tracks GraphQL and REST calls in the same bucket, although they likely have separate rate limits (**to be confirmed**)
- The `rateLimitMonitor` is updated by passing in the response headers, but GraphQL doesn't return those, but exposes the fields through the response
- Querying the `rateLimit` property through `GraphQL` seems to be cost neutral, against the docs which state it always at least costs 1 token
- The `rateLimiter` is [global to repo-updater](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/extsvc/github/client.go#L148) and hence being used in the reconciler
- `rateLimitMonitor` is not shared globally
- Reconciler fails with rate limit errors, making the changeset end up in the errored state, but it will be retried eventually.

Ideas for a solution:
- Make the `rateLimitMonitor` also update from GraphQL results
- Use the `rateLimitMonitor` in the `requestGraphQL` method on the client, not only explicitly at certain places
- Add a function on the monitor to take the suggested rate limit out of the values reported by the monitor PLUS the one of our internal rate limiter
- Make the `rateLimitMonitor` globally shared, so new clients still know about the previous requests limits

Future improvements:
- Merge the monitor and internal rate limiter into a single structure that can account for the combined limitation of both (and split across GraphQL and REST rate limits)
- Do proper timeouts and timeout error handling on the reconciler so these become enqueued back without erroring

cc @mrnugget @ryanslade

**Comment by eseliger** [comment]
## Current findings
- The rate limit monitor _is_ properly updated from the headers, the github api explorer just doesn't set them. Using the actual API works.
- The v3 and v4 APIs DO have separate rate limits

## Open question
What is the desired behavior for the syncer and reconciler? Currently both try as many as they can and eventually fail some of their tasks, which is undesirable.

For the syncer: I tried creating one syncer per token that we have, and it works. That means that only the rate limited token's syncer will need to sleep (unlike now where all github.com would need to sleep). That requires some wonky logic to determine the repos to include for that syncer though, which currently works by picking the first (lowest ID) external service that is associated to the repo the changeset lives in. This seems to work fine but it means we don't make use of other tokens although they might have rate limit tokens left. I think, besides the waste of some tokens, this is fine and works well. Question is how many external services there might be - if it's many once user external services are enabled, it'll spawn a lot of syncers in the background.
Another question is also: What token would we actually want to use? For GitHub, the token needs some specific scopes, so it might be that the configured global token doesn't work and it might make sense to use another token, perhaps one the user specified. If we do that, though, how will we determine which token to use? Imported changesets don't even have a proper owner. 

For the reconciler: I did no change to it but since it also uses the GithubSource, it will also sleep once rate limits become exhausted. This does work, but could mean that once we approach the limit and wait for longer, that rows in the DB are locked for a pretty long time. Also, since the reconciler works off one item at a time, one token being stalled can cause all actions to come to a sleep, which also isn't ideal. I think we would want to somehow incorporate that in the ordering of the reconciler worker pulling jobs, but it's hard since rate limiting is not a DB state.

For the meantime, my current approach should work and it would fix the rate limit issue in the shorter term (especially not keeping to hit Githubs apis once exhausted, which can cause a permanent ban), but I don't think it's done.

**Comment by eseliger** [comment]
Questions from a Zoom call:

What's the next steps?
1. Do what we have in the prototype: sleep until we can sync again
2. Back-off in reconciler, instead of retrying immediately. Use `process_after` set to `time.Now() + err.RecommendedSleepTime`
3. Take recommended sleep duration into account in `NextSync`
4. Make `NextSyncAt` request the time from repo-updater so it can take the recommended sleep time into account
5. Have a shared rate limiter between repo-updater and changeset syncer

**Comment by ryanslade** [comment]
repo syncing happens per external service, each of which we expect to have their own token. Currently we run up to 3 concurrently but this is easily configurable. 

This proposal might also be of interest when it comes to picking a token for a repo: https://github.com/sourcegraph/sourcegraph/issues/14910
