### ISSUE TITLE
Add better description and resolution steps for zoekt-webserver: fs_io_operations alert

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#14548]
Reported by https://app.hubspot.com/contacts/2762526/company/693777200

https://docs.sourcegraph.com/admin/observability/alert_solutions#zoekt-webserver-fs-io-operations has no possible solutions

Diff search points me to this commit: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/e8e86b961b28f769facf1489d2b101ada99f41f7?visible=4

Assigning @bobheadxi but feel free to redirect if someone else should be involved

**Comment by bobheadxi** [comment]
background: this was created on request as part of https://github.com/sourcegraph/sourcegraph/issues/12163

unfortunately I'm not sure what next steps should be if IO usage is high - @keegancsmith do you have any advice on this?

**Comment by dadlerj** [comment]
This is not urgent by the way—just an example of something that came up while the customer was reviewing our default alerts.

**Comment by keegancsmith** [comment]
> background: this was created on request as part of #12163
> 
> unfortunately I'm not sure what next steps should be if IO usage is high - @keegancsmith do you have any advice on this?

I think in the original PR I said setting a limit on IO is a bit weird to alert on, since its depends on the machine. My advice is remove the alert / try and make it  on sustained IO.

**Comment by stefanhengl** [comment]
There is currently no alert associated with fs_io_operations. I will close this ticket. @keegancsmith please reopen if needed.
