### ISSUE TITLE
Update code intelligence ping data

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#14574]
We need to:

- Send data broken down by language instead of in a single bucket
- Count of cross-repository code intel actions (see https://github.com/sourcegraph/sourcegraph/issues/14120)

Discussed, but out of scope:
- Determine number of code-intel-indexed repositories and the number of total repositories (or the ratio)
- Count and usage data of auto-indexed code intelligence

**Comment by ebrodymoore** [comment]
Would like to add [#14673](https://github.com/sourcegraph/sourcegraph/issues/14673) in here too. We get the number of unique users for LSIF | LSP | search but don't get an overall number of unique users who used code intelligence
