### ISSUE TITLE
Add total number of unique searchers to pings

### ISSUE THREAD

**Issue by ebrodymoore** [sourcegraph/sourcegraph#14575]
Right now we only split out active users by a condition (such as literal and regexp), but a user can be active in both categories so we don't actually get the number of unique users who searched over a time period

**Comment by attfarhan** [comment]
What time horizons do we want this for?

**Comment by attfarhan** [comment]
What seems to be missing is total uniques that have _ever_ searched, since we have uniques for day/month/year. Is that what we want? It doesn't seem that we'd be able to then chunk by specific time horizons though.

**Comment by ebrodymoore** [comment]
Wow you're absolutely right. No, we're good. That was easy 😄
