### ISSUE TITLE
RFC 201: Do not auto-index things being manually indexed

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#14572]
Auto-indexing should not be enabled for a repository that is getting _consistently_ uploads from a CI process as badly inferred data can interrupt actually good data that exists out-of-band.

**Comment by gbrik** [comment]
Implementation: Once #17386 is done, check whether the most recent upload (if exists) was manual or automatic. If manual, don't run the auto indexer on this thing. If automatic or non-existent, run the auto indexer on this thing. End result will be that you can stop auto-indexing for a repository by manually uploading something, and you can restart it by requesting an auto-index run through the UI.
