### ISSUE TITLE
Browser Extension Install Page Design Polish

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#14577]
We built the install page for the browser extension and have some additional tweaks to make it friendlier. 

Exploration: https://www.figma.com/file/V5t7KOzC6PIX75L4dz8IFc/RFC-221-Browser-extension-improve-discoverability-and-awareness-Approved?node-id=914%3A2364

(TODO @rrhyne to attach a figma link and/or context when ready.)

**Comment by AlicjaSuska** [comment]
I've made some changes to the installation page design:
- added a bigger SG logo that links to the home page
- added a link to the Docs in the top bar
[Figma](https://www.figma.com/file/V5t7KOzC6PIX75L4dz8IFc/RFC-221-Browser-extension-improve-discoverability-and-awareness-Approved?node-id=381%3A299)

For more context, here is the discussion about the changes and Rob's design in [this thread](https://www.figma.com/file/V5t7KOzC6PIX75L4dz8IFc?node-id=381:299#44000244)

@Joelkw @felixfbecker can we move forward with those changes?
