### ISSUE TITLE
Cancelled jobs in buildkite leave vagrant boxes running

### ISSUE THREAD

**Issue by davejrt** [sourcegraph/sourcegraph#14582]
If a job is cancelled, either by a user or a new push to a feature branch a pipeline exits without running any pre-exit commands which we use to destroy any infra created. 

This can lead to hanging vagrant boxes which need to be cleaned up in order to reduce infra costs.

**Comment by pecigonzalo** [comment]
@davejrt The linked PR did not fix it?

**Comment by davejrt** [comment]
WTH, I drafted a comment explaining and then mustn't have submitted it. 

The issue I ran into, was BUILDKITE_AGENT_NAME is set on the first agent that picks up the job which is then persisted through each step of the pipeline, regardless of it runs on another agent. 

In [this](https://github.com/sourcegraph/sourcegraph/pull/14961/files#diff-24562b302d432c760a2572378a156511d72947133ee6b97e5047b7658532fd42R11) line if the agent has changed between loading the pipeline and step 2. So agent1 cannot write to a directory owned by agent2. 

Next idea, generate the pipeline and use the nametag for each agent. I found [this](https://gist.github.com/toolmantim/1337952c8b5b1e5b0b5ea10c40e9efe4) gist explaining that you can do this by targetting an agent with name. However, meta-data has been deprecated in favor of tags, and there is no way to interpolate the "name" of agent in the tags field in a buildkite config file like you can do with name: see [here](https://buildkite.com/docs/agent/v3/configuration). 

I hope that's a complete enough explanation, feel free to tag me on slack and we can discuss further if not.

**Comment by pecigonzalo** [comment]
Fixed by sourcegraph/infrastructure#2223 and #15115
