### ISSUE TITLE
Commit message with ${foo.bar} causes Buildkite to fail

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#14591]
See https://github.com/sourcegraph/sourcegraph/pull/14590.

Not blocking (workaround is mentioned in that PR), but caused me ~15-20min of confusion and will probably bite someone again in the future.

**Comment by danishprakash** [comment]
@sqs is the idea here to somehow document this? Or have a hook that warns the committer beforehand?

**Comment by sqs** [comment]
I don’t know what the best solution is 🤷🏼‍♂️
