### ISSUE TITLE
Missing external_service_repos rows

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#14613]
We're seeing rows in our `repos` table without corresponding entries in `external_service_repos` on sourcegraph.com. This should not be possible. 

```sql
SELECT COUNT(*) FROM repo
LEFT JOIN external_service_repos esr ON repo.id = esr.repo_id
WHERE esr.repo_id IS NULL AND repo.deleted_at IS NULL;

=> 31179
```

**Comment by ryanslade** [comment]
We can assign a size estimate after some investigation

**Comment by ryanslade** [comment]
We've taken a look into this and it appears to be caused by old repos from 2018 as well as a few from the day of our migration that added the `external_service_repos` table. 

We decided that the best option is to run a once off query to fix the issue on Cloud and @asdine is happy to do this.

**Comment by asdine** [comment]
I have inserted rows in the `external_service_repos` table for these repos.
Github repos have been associated with the global Github external service and Gitlab repos with the Gitlab one.

```sql
SELECT COUNT(*) FROM repo
LEFT JOIN external_service_repos esr ON repo.id = esr.repo_id
WHERE esr.repo_id IS NULL AND repo.deleted_at IS NULL;

=> 0
```
