### ISSUE TITLE
release: command naming and behaviour is inconsistent

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#14623]

**Comment by bobheadxi** [comment]
Closed in #14621

**Comment by pecigonzalo** [comment]
@bobheadxi was the handbook updated? I see a reference to doing it in the PR but no linked PR.

**Comment by bobheadxi** [comment]
This is the one: https://github.com/sourcegraph/about/pull/1749

(looks like the GitHub "linked pull request" links don't work cross-repo :( )
