### ISSUE TITLE
Document QA test commands

### ISSUE THREAD

**Issue by pecigonzalo** [sourcegraph/sourcegraph#14632]
The commands required to run the QA tests broke after the re-organization of the web components and the existing documentation does not work.

- [ ] Document in the handbook
- [ ] Automate the steps if possible

**Comment by pecigonzalo** [comment]
@slimsag I believe you were working on this, otherwise please re-assign.

**Comment by slimsag** [comment]
Merged https://github.com/sourcegraph/sourcegraph/pull/14553 ~6 days ago to help with this. I think there are still some aspects that can be improved, like https://github.com/sourcegraph/sourcegraph/issues/14875 but that is being tracked separately.

I won't lie, the docs are still quite rough IMO - but we can improve these going forward - the general steps are there. Feel free to reopen if you disagree.
