### ISSUE TITLE
proposal: less verbose patternType from URLs 

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#14668]
I find patternType makes our URLs quite ugly. We seem to always specify it because users can have different default pattern types. Can we try make our URLs less verbose?

### Proposal: shortened key and value

| verbose | succinct |
| ------------- | ---------- |
| `patternType=literal`    | `t=l`                 |
| `patternType=regexp`     | `t=r`                 |
| `patternType=structural` | `t=s`                 |
| `patternType=unknown`    | `patternType=unknown` |

Alternatively, `t=lit`, `t=re` and `t=struct`. 

So we special case a few values and support reading them. If we are constructing a URL, we use our special cases if we can.

### Proposal Next: Remove search.defaultPatternType

Who is using this? Can we just not support it, it seems like a strange thing to support and I believe we added it because we were scared of interrupting existing workflows / links. However, I suspect most are using literal. If we don't support it, then in the default case (literal) we can just not include pattern type at all, which will be very great.

cc @sourcegraph/search @poojaj-tech @rrhyne

**Comment by stefanhengl** [comment]
@keegancsmith Please reopen if you want to reignite this proposal :-)

**Comment by limitedmage** [comment]
FYI @rvantonder since you're working on augmenting `search.defaultPatternType`

**Comment by rvantonder** [comment]
Noted, thanks @limitedmage! Won't get into details of changes in this old issue, but noted for future!
