### ISSUE TITLE
Basic code intel on Markdown code blocks

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#1468]
#### Feature request description

The `basic-code-intel` extension could be used on Markdown code blocks in any comment, issue or PR description.

#### Is your feature request related to a problem? If so, please describe.

No.

#### Describe alternatives you've considered.

No alternatives.

**Comment by scalabilitysolved** [comment]
Is this still something we plan on doing @macraig ?

**Comment by macraig** [comment]
Added feature request to Productboard, closing for now and will reopen if we decide to prioritize it
