### ISSUE TITLE
Home panels: saved searches appear in "recent searches" panel

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#14717]
I noticed that queries from my personal saved searches show up in the recent searches panel

![image](https://user-images.githubusercontent.com/1741180/95983642-44bf5980-0e22-11eb-9c6e-110b92a3c10e.png)
![image](https://user-images.githubusercontent.com/1741180/95983650-4721b380-0e22-11eb-8206-267c760b5a85.png)

This was unexpected to me. I'm not sure of how big an issue it is -- I imagine that for a user with a lot of saved searches it might effectively render the panel irrelevant. I have no idea whether filtering out saved searches is easy.

cc @rrhyne @limitedmage @poojaj-tech

**Comment by rrhyne** [comment]
As the saved searches are run by the system, they show in this panel? If so that is un-intended.

**Comment by lguychard** [comment]
> As the saved searches are run by the system, they show in this panel?

Yes, exactly.

**Comment by limitedmage** [comment]
@lguychard  Do you have repro steps for this? I haven't been able to do this yet. I wonder if what happened is that you clicked on the search results link in the email?

**Comment by lguychard** [comment]
@limitedmage I think you are right, I must've clicked on the email link 🤦‍♂️

**Comment by limitedmage** [comment]
Closing this issue, we can reopen if we see this happen again. (Or we decide that certain types of search interactions should not show in the recent searches)
