### ISSUE TITLE
Remove (unintended) deprecation of extension API showNotification

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#1471]
Extensions currently have no way of showing an error message, the other option being `showNotification` which is deprecated.

Looking at https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L6291, maybe it's worth adding a `showWarningMessage` too.

**Comment by sqs** [comment]
Ideally we could extend showNotification to allow multiple levels (info, error, warn, etc.) instead of adding 1 new method per level

**Comment by felixfbecker** [comment]
So just undeprecate `showNotification()`?

**Comment by lguychard** [comment]
Discussed with @sqs 
- `showNotification()` was likely `@deprecated` because it was due to change, and there was no way to flag it as experimental
- So, yes, we want to undeprecate it, and extend it to allow multiple levels
