### ISSUE TITLE
Empty sourcegraph URL shows "Looks good!"

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#14729]
When all the characters are deleted from the URL input, we should display 'Checking...' state. Now, it shows 'Looks good!' (probably because it is linking to the sourcegraph.com address).

<img width="420" alt="Screenshot 2020-10-14 at 16 29 46" src="https://user-images.githubusercontent.com/20326070/96004138-4d705980-0e3b-11eb-98cc-71644592f9df.png">

**Comment by felixfbecker** [comment]
@AlicjaSuska current behavior is clearly wrong, thanks.
Why should it display "Checking..." though? What would it check if there is no URL? I would think we should make the field invalid.

**Comment by AlicjaSuska** [comment]
You're right @felixfbecker thank you for making the changes
