### ISSUE TITLE
Can't add public GitHub repository

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#1472]
#### Steps to reproduce:

1. Pull latest master
2. Generate an access token
3. Add an external service config:
```json
{
    "repos": [
        "gorilla/mux"
    ],
    "token": "$YOUR_TOKEN"
}
```
4. Go to http://localhost:3080/github.com/gorilla/mux. See this message:
![image](https://user-images.githubusercontent.com/1646931/50104858-f1593180-01df-11e9-8ac5-e4bb8d53bb52.png)

**Comment by beyang** [comment]
I think this issue was caused by the old code host site config (from `dev-private`), which resulted in seeing the following errors:
![image](https://user-images.githubusercontent.com/1646931/50114908-b6182c00-01fa-11e9-8148-e21e2542c889.png)

Removing those fields from the config seemed to fix the issue. @nicksnyder assuming this is just due to the particular way we bootstrap the config in dev and that we have a migration path for code hosts site config to the new external site DB tables?

**Comment by nicksnyder** [comment]
I left those fields in the dev site config because it was a working way to leverage the automatic migration to external services in a dev environment. I didn't realize the existence of those errors would break other things though.

> My next step will be to replace the old dev-private code host config with a bootstrapping script similar to what we use for initial site/critical config in dev. @nicksnyder let me know if you disagree with this.

This is the correct next step, thanks! This is also a checkbox in https://github.com/sourcegraph/sourcegraph/issues/914#issuecomment-440067022
"need solution for fixture external services in dev environment "

**Comment by nicksnyder** [comment]
> FYI, no auto-migration from site config to external services appeared to take place for me (my external_services table was empty in local dev until I added an entry manually).

Hmm, I tested that code path last week and it was working so I will test it again.

**Comment by nicksnyder** [comment]
Ok, what I actually tested last week was the code path that customers will go through (which is slightly different than what happens in dev). I confirmed again that the customer code path does work.
