### ISSUE TITLE
Permissions from multiple code hosts at once

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#14736]
Requested by:

* https://app.hubspot.com/contacts/2762526/company/1799582875

>Hi folks. I've been finalising our deployment and had a question about how repository permissions worked.
>
>It's my understanding that they rely upon the information provided by the code host authentication, thus it's preferred that one use your code host for user authentication instead of going to an external SSO provider (e.g. Okta).
>
>Is it possible to apply repository permissions from multiple code hosts, or is it only from the code host that authentication is configured with.

* https://app.hubspot.com/contacts/2762526/company/1749032193 (see https://sourcegraph.slack.com/archives/C0B2RU51Q/p1602706736156600)

* https://app.hubspot.com/contacts/2762526/company/693777200

#thanks to @unknwon for earlier confirming that we CAN support multiple code host permissions (e..g multiple GitLabs) at once! 

Interestingly, we can support this for GitLab (using sudo access tokens or username equivalency: https://docs.sourcegraph.com/admin/repo/permissions#gitlab) and for Bitbucket Server (see https://docs.sourcegraph.com/admin/repo/permissions#bitbucket-server). But not for GitHub. 

So two specific requests here:

* Support username or email-based permission for GitHub (versus ONLY supporting it when GItHub is also the authn provider)
* Simply confirm that Sourcegraph can handle supporting permissions from multiple code hosts with distinct permissions all connected in different ways (has this already been confirmed by you @unknwon ?)
* Confirm whether it's possible to have code host-synced permissions AND explicit permissions for another code host. E.g. for https://app.hubspot.com/contacts/2762526/company/1749032193

**Comment by unknwon** [comment]
> * Support username or email-based permission for GitHub (versus ONLY supporting it when GItHub is also the authn provider)

It is possible, the hard part is to get a personal access token that has WRITE permissions to ALL repositories being synced from GitHub.com. (For GitHub Enterperise Server it is easier by just getting an admin access token).

> * Simply confirm that Sourcegraph can handle supporting permissions from multiple code hosts with distinct permissions all connected in different ways (has this already been confirmed by you @unknwon ?)

Technically we do support, but have to know the full picture of their set up to be sure, to suggest best solution and to cover possible edge cases.

Ideally, we want all code hosts _and_ Sourcegraph to use the same SSO (as [the experiment I did with two GitLabs](https://unknwon.io/posts/200915_setup-sourcegraph-gitlab-keycloak/)).

> * Confirm whether it's possible to have code host-synced permissions AND explicit permissions for another code host. E.g. for [app.hubspot.com/contacts/2762526/company/1749032193](https://app.hubspot.com/contacts/2762526/company/1749032193)

They do not play nice currently as the site admin has to choose one between code host-synced permissions OR explicit permissions, otherwise will be very confusing to debug/inspect when anything goes wrong. I would suggest not open this possibility to customer.

**Comment by dadlerj** [comment]
>It is possible, the hard part is to get a personal access token that has WRITE permissions to ALL repositories being synced from GitHub.com. (For GitHub Enterperise Server it is easier by just getting an admin access token).

Thanks, this is helpful. It's similar to the "sudo access token" option for GitLab, if I understand correctly? We should document this if it's already possible, but if it's not, then I can update this issue to focus on adding this.

**Comment by unknwon** [comment]
@dadlerj:

> > It is possible, the hard part is to get a personal access token that has WRITE permissions to ALL repositories being synced from GitHub.com. (For GitHub Enterperise Server it is easier by just getting an admin access token).
> 
> Thanks, this is helpful. It's similar to the "sudo access token" option for GitLab, if I understand correctly?

That is correct.


> We should document this if it's already possible, but if it's not, then I can update this issue to focus on adding this.

Hmm, I should have said it is possible via a unified external SSO (e.g. Okta with SAML), not directly via GitHub OAuth, plus a "sudo access token".

**Comment by dadlerj** [comment]
>Hmm, I should have said it is possible via a unified external SSO (e.g. Okta with SAML), not directly via GitHub OAuth, plus a "sudo access token".

Yeah, this is what I assumed (that it would work the same as the GitLab equivalent option). Being able to use a unified external SSO for both GitHub and GitLab (and etc.) is exactly the goal here (requested by https://app.hubspot.com/contacts/2762526/company/1799582875, but not urgent). This is ONLY documented for GitLab today, though.

Does this option already exist for GitHub, or would it have to be added?

**Comment by unknwon** [comment]
>Does this option already exist for GitHub, or would it have to be added?

I believe this would have to be added, and only work with GitHub Enterprise Server because we want a sudo-access-token (same that we assume it is GitLab on-perm not GitLab.com).

**Comment by unknwon** [comment]
Cleaning up old/stale/fixed issues, please feel free to reopen if you think it's worth keeping.
