### ISSUE TITLE
Account update email should mention the instance URL

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#14751]
I reset my test account password on my dev instance, and it has email configured. Then I received the following notification:

>Somebody (likely you) reset the password for the user * on Sourcegraph.
>
>If this was not you please change your password immediately.

My email client shows it is coming from "notifications@sourcegraph.com" (which is not really true).

I think the email body should mention which Sourcegraph instance (the `externalURL`) sent out the email, otherwise it is pretty confusing and could cause false alarm.

**Comment by tsenart** [comment]
@ElizabethStirling: Have you worked in this area recently? Would this be a quick fix?

**Comment by ElizabethStirling** [comment]
Not immediately certain that it'd be a quick fix, since I'd assume the local machine was configured to use that email account. I think this might be a broader thing about how we handle emails in local development environments.

**Comment by unknwon** [comment]
@ElizabethStirling It happened this time on my local dev instance, but can also happen when I use more than one Sourcegraph instances, for example:
- Sourcegraph.com
- Sourcegraph for my school
- Sourcegraph for my personal use

Most likely I'll use the same username for all instances whenever possible, thus giving the information of which exactly the instance is would be very helpful.

**Comment by arussellsaw** [comment]
Hey, i don't know if we have standards around copy or how we format emails, but here's a first stab at this! 
![Screenshot 2020-11-02 at 15 36 25](https://user-images.githubusercontent.com/5236823/97886961-2d88d300-1d21-11eb-94f7-de0613d337d7.png)

**Comment by tsenart** [comment]
This looks good to me!

**Comment by unknwon** [comment]
@arussellsaw Looking great!
