### ISSUE TITLE
Find a reliable way to inspect the current value of the Monaco editor in integration tests

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#14756]
To get the current value of the Monaco editor, we use `document.querySelector('#monaco-query-input .view-lines')?.textContent`.

Unfortunately, Monaco will render all spaces as non-breaking spaces in the DOM, preventing us from distinguishing spaces from non-breaking spaces in the actual query.

**Comment by fkling** [comment]
I think we can close this now. Besides phasing out Monaco, the editor API that I introduced in https://github.com/sourcegraph/sourcegraph/pull/36044 reads Monaco's value from the `<textarea>` element contained within it, which seems reliable so far.
