### ISSUE TITLE
Exclude the "repo" search option from the search bar after I've found the repo I want to explore

### ISSUE THREAD

**Issue by macraig** [sourcegraph/sourcegraph#14762]
#### Feature request description

SourcegraphWeb user request

> I'd like the "repo" section to behave similarly to Chrome's "search engine search" or "restricted omni bar search" feature (see screenshot below for example with searching using Youtube as the search engine) when I navigate to the repo of interest I am exploring. 

#### Is your feature request related to a problem? If so, please describe.

> This would allow me to more easily search within a repo without accidentally searching all of Sourcegraph.

**Comment by camdencheek** [comment]
Closing since this is not something that I think we'll prioritize independently, but cc @taiyab for design inspiration
