### ISSUE TITLE
Sourcegraph extension hover card not complete markdown

### ISSUE THREAD

**Issue by yevbar** [sourcegraph/sourcegraph#1477]
#### Feature request description

To be able to use simple Markdown functionality in a hover card including links, dropdowns

#### Is your feature request related to a problem? If so, please describe.

The markdown renderer seems to sanitize a lot out of the given source. Doing the following:

```
[some text](some url)
```

Will give you an `a` tag but it won't point to a URL. And doing

```
<details>
<summary>Here's a dropdown</summary>
Here is dropdown content
</details>
```

Will render the summary and content text without a dropdown

#### Describe alternatives you've considered.

Putting in HTML elements did not bypass the sanitizer/filter so hover cards in the Sourcegraph browser extension are limited in what they can provide to a user

#### Additional context

I originally wanted to use formatted markdown in a hover card for displaying information about a feature flag (see point 2 [here](https://github.com/sourcegraph/sourcegraph/issues/1249#issuecomment-444765619))

**Comment by yevbar** [comment]
@chrismwendt do you know if it'd be possible to remove some of the filtering with the markdown renderer?

**Comment by yevbar** [comment]
XSS and other attack vectors are irrelevant since they're already using a Sourcegraph extension which runs remote JavaScript in the user's browser :slightly_smiling_face:

**Comment by chrismwendt** [comment]
Hmm, that sounds overly strict to me. I don't know off the top of my head, but @lguychard are you familiar with how the renderer is configured?

**Comment by sqs** [comment]
The markdown rendering still occurs in codeintellify. That hasn’t changed yet.

**Comment by yevbar** [comment]
@felixfbecker thanks for the link! I'll be making a PR soon :slightly_smiling_face:

**Comment by yevbar** [comment]
@felixfbecker @sqs I put in the needed tags and created a PR:
[https://github.com/sourcegraph/codeintellify/pull/83](https://github.com/sourcegraph/codeintellify/pull/83)

**Comment by sqs** [comment]
Fixed upstream
