### ISSUE TITLE
Site init page changed with redesign of sign up form

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#14773]
We didn't consider this when we redesigned the sign up form. @quinnkeast how should this look like?

![image](https://user-images.githubusercontent.com/10532611/96141068-eddc8180-0f00-11eb-914e-89bd63fcadce.png)

**Comment by quinnkeast** [comment]
Surprised we missed this!

I've created a design for this based on the existing work, with a couple of quick tweaks for visibility.

[https://www.figma.com/file/L5ZdNBGAnHQQUGGmp6tdQS/12695-%E2%80%93-Sign-in-Out-UX-Done?node-id=1%3A101](View on Figma)

Let me know if this will do the trick in the short term.

**Comment by pdubroy** [comment]
Is there still any work required here, or can we close this issue?

**Comment by felixfbecker** [comment]
@pdubroy I'd suggest running a [fresh Docker instance](https://about.sourcegraph.com/get-started/) and comparing the init screen to the Figma design (either the one @quinnkeast linked above, or what was in the redesign designs, if this page was included)

**Comment by pdubroy** [comment]
Sorry, I should have been clearer in my comment about what my question was.

@quinnkeast AFAIK we didn't touch the site init page in the redesign (please correct me if I'm wrong). Assuming that's correct, are the designs from 2020-10-20 that you linked above something that we want to implement, or do they need to be updated based on the changes made in the design refresh?

**Comment by quinnkeast** [comment]
The content/structure in the linked design (date is correct) is still good to go. If this can be implemented with the redesign's changes applied, that's perfect. If the team would prefer to have a high-fidelity design reference with the design refresh applied, I can also provide that but it'll be a bit lower on my list of priorities.

**Comment by quinnkeast** [comment]
Took a look, and yes, it's still an issue. If it can be completed in the short term and isn't too much investment, it's worth the update.

**Comment by taylorsperry** [comment]
Thanks, @quinnkeast. I think this belongs with IAM since it's related to sign-up. cc @ryphil
