### ISSUE TITLE
Add onboarding tour metrics in pings

### ISSUE THREAD

**Issue by ebrodymoore** [sourcegraph/sourcegraph#14781]
The directions to add pings can be found [here](https://about.sourcegraph.com/handbook/engineering/adding_ping_data)

**Comment by ebrodymoore** [comment]
@rrhyne did we ever scope out metrics for this (like we did for panels)? I couldn't find a doc anywhere. 

If not, that's obviously step one here (as a group, I mean. Not just Rob and me 😄)

**Comment by rrhyne** [comment]
@ebrodymoore https://github.com/sourcegraph/sourcegraph/issues/11833

**Comment by attfarhan** [comment]
we ended up adding way more stats than what was specified in https://github.com/sourcegraph/sourcegraph/issues/11833#issuecomment-656961717. Do we want to include all that data? See https://sourcegraph.com/search?q=r:github.com/sourcegraph/sourcegraph+f:client/web/src/search/input/+eventlogger&patternType=literal#2 for what we track.

**Comment by ebrodymoore** [comment]
For getting onboarding tour metrics in pings, I'm thinking we create a funnel of sorts. 

So it'd be number of times each of these events is triggered per day: `ViewOnboardingTour`, `OnboardingTourLanguageOptionClicked`, `OnboardingTourRepositoryOptionClicked`, `ViewedOnboardingTourSubmitSearchStep`, `ViewedOnboardingTourAddQueryTermStep`, `ViewedOnboardingTourFilterRepoStep`, `ViewedOnboardingTourFilterLangStep`

@poojaj-tech @rrhyne @attfarhan would love your thoughts on this

**Comment by attfarhan** [comment]
I have a draft PR up that captures total views off the onboarding tour, and then percentages of each step (similar to homepage panels). Happy to change to raw counts if that's better. https://github.com/sourcegraph/sourcegraph/pull/15113/files

**Comment by rrhyne** [comment]
I defer to Eric on how the metrics are reported, but I wonder if we should also collect search reference seen? I imagine that being important to the matrix Eric... 'users who have seen the search reference are more likely to use structural search'.

**Comment by attfarhan** [comment]
There isn't any content related to structural search in the search reference currently, though.

**Comment by rrhyne** [comment]
Poor reference, but after, before, any other commands we call out are
applicable.

**Comment by attfarhan** [comment]
Got it. Curious, though, are we able to actually map data like this? Since we don't track events corresponding to individual users, and just aggregates, we wouldn't actually know the rate of filter usage for a given user, let alone whether a particular user actually clicked the search reference in the past, right? @ebrodymoore

**Comment by rrhyne** [comment]
Eric and I have something cooking that would allow us to see the percentage of users who conducted one action correlated to every other action we track. For instance:  users who have seen the search reference are more likely to return the second week.
