### ISSUE TITLE
remove search code clutter

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#14788]
move this validation function: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/search_results.go#L2114-2120

move out validation checks like this: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/textsearch.go#L341

fix/remove this validation: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/search/text_pattern_info.go#L8

**Comment by camdencheek** [comment]
@rvantonder is this still relevant? I have no idea what those links were pointing to since they weren't pinned at a commit, and we've seriously reorganized since this was created 😄

**Comment by rvantonder** [comment]
IDK this is old, it go bye bye
