### ISSUE TITLE
Do not autofocus search input for users who will see the tour

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#14783]
Starting the application with the tour popup open and visible leads to many items competing for attention. 

To reduce this complexity, we should only show the search tour when the user registers their intent to make their first search, i.e., when the user focuses the search input. 

To make this possible, if the user should see the tour, the application should not focus the search input. When the user clicks the search input, the tour should then display. 

On every subsequent visit,  the search input should be focused.

See the following slack thread for background:
https://sourcegraph.slack.com/archives/C0W2E592M/p1602623755088100

**Comment by attfarhan** [comment]
I think this solution would help us solve the problem of competing attention, but I don't like the idea of not focusing the input on first view. For new users especially, we want the default action to be typing a query. Before running into any other concept, first and foremost, we want users to figure out our search. 

Therefore, I think the tour _should_ be the first thing they see, as it'll guide them to making their first search. My preference is the solution Juliana proposed: to dim the background while the tour is shown. This solves the problem of competing attention, but doesn't take users away from Sourcegraph's main functionality on initial visit.

**Comment by attfarhan** [comment]
@rrhyne what are your thoughts on the above?

**Comment by rrhyne** [comment]
I feel strongly we should remove autofocus for the first visit.

**Comment by attfarhan** [comment]
Can you elaborate on why? I am very worried that it distracts users from the main value proposition and distracts them from making a successful search on the first visit.
