### ISSUE TITLE
Frontend needs to handle asynchronous repository deletion

### ISSUE THREAD

**Issue by asdine** [sourcegraph/sourcegraph#14799]
The backend sometimes deletes repositories asynchronously for various reasons (repository becomes private and must be deleted, changes in external service configuration, etc.). It means that any GraphQL query on the Repository API might fail at any given point and thus must handle that error correctly.

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.

**Comment by jasongornall** [comment]
Adding repo management for awareness / priority (pruning backlog)

**Comment by eseliger** [comment]
Errors are returned correctly, if anything is missing here it's UI bugs specific to the use-cases the APIs are called, so closing from a source perspective.
