### ISSUE TITLE
Expired/invalid GitHub OAuth token is not visible to user

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#1479]
Simple repro:
- Enable GitHub authz and add a repository that your user has access to, but a generic user does not (e.g., a private repo with no collaborators)
- Sign-in via GitHub
- Check that you can access the repo on Sourcegraph
- Invalidate the OAuth token by removing the OAuth app authorization in the GitHub UI
- Try to navigate to the repo. You should not be able to access it anymore, which is expected. What's unexpected, however, is that you receive no error or warning that your GitHub creds have expired.

Proposed fix: Show a UI banner indicating a user should re-sign-in via GitHub (and also check GitLab) if the creds in the DB are rejected.

**Note:** In implementing the fix, it's important that we avoid leaking repository existence/info. The error should trigger anytime we detect the GitHub OAuth creds are invalid, **not** based on the existence/properties of specific repositories.

**Comment by francisschmaltz** [comment]
@beyang is this related to #1710
