### ISSUE TITLE
Pasting Code From Sourcegraph To Some External Text Editors Results In Difficult To Read Table Format

### ISSUE THREAD

**Issue by tistru** [sourcegraph/sourcegraph#14810]
Reported by: https://app.hubspot.com/contacts/2762526/company/693777200

Customer reported that when copying code from Sourcegraph into certain text editors (e.g.[ Azure boards](https://azure.microsoft.com/en-us/services/devops/boards/)), the format is off and difficult to read. This is evident when copying Sourcegraph formatted code directly into an editor such as MS Word or Google Docs. The root of this seems to be that the code is formatted as a table when pasted into an editor that supports tables. See example below in MS Word where it is evident how the code block is distributed across

![image](https://user-images.githubusercontent.com/25908288/96298626-c51bc100-0fc0-11eb-941f-6233da0a8433.png)

#### Steps to reproduce:

1. Copy a block of code from a file while viewing in the Sourcegraph web interface.
2. Paste the code to an external editor such as MS Word, Google Docs, or [ Azure boards](https://azure.microsoft.com/en-us/services/devops/boards/))

#### Expected behavior:
Original function block direct from Sourcegraph:

![image](https://user-images.githubusercontent.com/25908288/96297943-a963eb00-0fbf-11eb-9d1a-bab1abf1f4f9.png)

#### Actual behavior:
MS Word Example (note that the function name is not spaced properly across the line and the code black is not lined up with the function name):

![image](https://user-images.githubusercontent.com/25908288/96297431-d794fb00-0fbe-11eb-8374-c4e2095d8ed5.png)

#### Exceptions:
_**Note that pasting into some text editors (that do not support tables) seem to look as expected. For example, notepad and notepad++.**_

**Comment by pdubroy** [comment]
Closing this out as I believe the original issue is fixed. Please feel free to re-open if I'm wrong.

**Comment by felixfbecker** [comment]
@pdubroy I think this is still an issue, I can still repro. The root is that we use a table (we still do that), don't override copy behavior, and that table gets copied into editors as a table.

**Comment by pdubroy** [comment]
@felixfbecker Thanks. I wasn't seeing the `|` characters in the tool that I was pasting into (Bear) but I do see them when I paste into the Github compose UI.

**Comment by jasongornall** [comment]
We can reopen if a client specifically complains but as mentioned in https://github.com/sourcegraph/sourcegraph/issues/15788 `Notepad / slack / vscode` seem fine. I don't think this is a common usecase.
