### ISSUE TITLE
Capitalization problems in search homepage copy

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#14819]
- "api" should be capitalized ("API")
- "Explore and Extend" should be sentence-case, not title case (https://about.sourcegraph.com/handbook/communication/content_guidelines/style_and_mechanics#capitalization), so "Explore and extend"

![image](https://user-images.githubusercontent.com/1976/96373622-961d6080-1122-11eb-8fc4-b74784830c5d.png)

**Comment by poojaj-tech** [comment]
thanks for filing @sqs! assigning to @limitedmage who owns these panels to address in the ongoing iteration once she's back from time-off next week.
