### ISSUE TITLE
zoekt: improve grafana dashboard

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#14858]
Introduce some key metrics we would be interested in correlating when things go wrong. Some ideas:

1. Request durations
2. Request rates
3. Shard counts
4. Process Restarts

cc @pecigonzalo for other things distribution team may want.

**Comment by slimsag** [comment]
Directly related to Zoekt dashboard:

* Add better description and resolution steps for zoekt-webserver: fs_io_operations alert #14548 
* Metrics or indicator for search readiness (for massive scale instances) #14316
* monitoring: add metric for open file descriptors and alert when approaching fd limit #10009
* Alert when search indexing is failing #9783 
* observability: Add monitoring for when zoekt indexing fails on repos #8309
* monitoring for how many repos are indexed/nonindexed missing #4197

Orthogonal, but arguably worth calling out as some here may be more important:

* Missing monitoring to signal if requests are not hitting search index #9838
* Alert if the number of repositories not cloned is high #9837
* Alert if containers are entirely down/missing #9792
* Missing monitoring to notify admins of mass recloning events #9789
* Alert when repository updates are failing #9782
Open
* Frontend dashboard: "non-200 indexed search responses every 5m" should be by (category,code) #9744
* Alerts for code host rate limiting, time spent waiting on rate limiting, etc. #8100

**Comment by pecigonzalo** [comment]
@keegancsmith I shared this with the distribution team directly for them to add comments.

I think the most important thing is to define for each "service" that zoekt provides some key metrics, aside from the "context" metrics.
I think for those Rate, Errors, Duration (RED) would be the basic requirements for most services. Duration, might not be duration of a query, given queries could have a varying length depending on the size of the dataset, but there might be other duration 
sensitive metrics. In the context of Zoekt, I could think of something like "index delay" or similar.

Maybe this is already included in the metrics you named, but I would just think about what would be useful to you or other engineers to understand if Zoekt is working correctly or not, given you could only look at the metrics.
Other information like log, traces, etc could be required to pin what is the cause, but metrics should be able to highlight in most cases if the service is healthy or not, as said before, some are for context, some are direct indicators.

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket,  please tell use how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
