### ISSUE TITLE
Mount file on batch change steps containers

### ISSUE THREAD

**Issue by jensim** [sourcegraph/sourcegraph#14851]
#### User outcome and current workflow

It's frequent for users to run complex scripts or internal tools in batch changes. To do so today, they gave two choices:
- bake the script/ or binary inside the step container. This is painful and slows down iteration as it requires to rebuild the container.
- Use [steps.file](https://docs.sourcegraph.com/batch_changes/references/batch_spec_yaml_reference#steps-files), which is also painful and slows down iteration. To convince yourself, paste a python script of a 100 line in a batch spec and fix the indentation :). 

#### Proposal

Allow users to mount a file (a script, a binary of an internal tool) on the batch spec container. This means the user can iterate on the file easily, without needing to copy-paste it inside the spec, or rebuild a container.

One thing we need to figure out is caching. If the spec does not change, but the file changes, we should invalidate the cache.

This is discussed in [RFC 560 REVIEW: Mount file on Batch Changes container](https://docs.google.com/document/d/146zr_cD2a6TEf2UJdmlq4_sOD_KzvZL-Le9eJUWMSZU/edit#heading=h.trqab8y0kufp)

#### Impacted customers (details in thread)

- https://github.com/sourcegraph/accounts/issues/8202
- https://github.com/sourcegraph/accounts/issues/1
- https://github.com/sourcegraph/accounts/issues/537
- https://github.com/sourcegraph/accounts/issues/544
- https://github.com/sourcegraph/accounts/issues/278 (Use case: to replace all docker files by a specific docker file, `files:` is not convenient)
- https://github.com/sourcegraph/accounts/issues/6859 because they need to run custom tooling, and it's currently brittle

### Delivery plan

- [x] #31790
- [x] #37216
- [x] #31791
- [x] #31792
- [ ] #31793
- [ ] #37751
- [ ] #41549
- [ ] #45278
- Make sure template UI supports template with mounted files

**Comment by eseliger** [comment]
Hey, thanks for filing this! 🎉 
We recently opened https://github.com/sourcegraph/sourcegraph/issues/15821 which tracks progress on this. If you have additional feedback / wishes around this topic, please add them there!

**Comment by malomarrec** [comment]
+1

**Comment by malomarrec** [comment]
Another +1 from 2 customers ([A](https://docs.google.com/spreadsheets/d/1OEhzdMSlkGOaWyGKwdiAGlirsKKj9EN45Izn7kdKNTg/edit#gid=0&range=A94), [B](https://docs.google.com/spreadsheets/d/1OEhzdMSlkGOaWyGKwdiAGlirsKKj9EN45Izn7kdKNTg/edit#gid=0&range=A94))

**Comment by chrispine** [comment]
Let's start with an experimental feature (on src-cli only) to get this done sooner.

**Comment by malomarrec** [comment]
We decided to do this as an `experimental` feature, with the following trade-off:
- not available on serve side batch changes
- can be removed at any time
- add disclaimers about reproducibility in the docs

For future versions, we'd need to discuss
- The idea of pulling specs (and files) from a github repository to create a fully reprodcbility flow on server side batch changes
- Reproducibility in general
- Viewing files from the GUI if they are mounted.

**Comment by malomarrec** [comment]
+1 from [customer](https://sourcegraph2020.lightning.force.com/lightning/r/Account/0013t00001dBddGAAS/view)

**Comment by malomarrec** [comment]
+1 from https://github.com/sourcegraph/customers/issues/1

**Comment by malomarrec** [comment]
Requested by: https://github.com/sourcegraph/accounts/issues/8202 (see details in the customer's ticket)

**Comment by malomarrec** [comment]
+1 from https://github.com/sourcegraph/accounts/issues/544

**Comment by malomarrec** [comment]
From https://github.com/sourcegraph/accounts/issues/6859
>I think the need lines up with the need in that FR — namely, the need to do things that are more complex than you would want to do interactively in a shell.  Shell scripts, complex comby replaces, compiled binaries, etc all fall into this.

Mounting files into the container is definitely a step in the right direction if it checksums the files and knows to re-run the steps whose’ mounted files change.  I think that would satisfy our local need well.  It would mean that we don’t have to build a docker image environment for our steps to run.

(Having this break server side applies would be a bit rough though… it would mean that we would develop using this feature and then build a docker environment, which then means it’s going to be easy to make a mistake.  So I feel like we’d want some way to include the files that would be mounted in, maybe a src batch preview --execute-remotely?)

I think this exposes another aspect of this which is the question about the docker images changing and not expiring the steps: I think the cache should include, as part of its key / invalidation, the image/layer checksum of the base image that is used for the step.  That would give us a lever for only re-running the steps we are iterating on by having per-step docker images.

**Comment by malomarrec** [comment]
For those following this issue, we've gotten started on this (step 1 of the plan above), and will be updating as me move forward.

**Comment by malomarrec** [comment]
Chris's idea: you could add a mounted file from the batch spec directly, drag&drop into the UI. This potentially breaks down the 5th step into 2 smaller steps.

**Comment by Piszmog** [comment]
I agree. Supporting both would be great. There is a possibility that #31791 will add the support needed to do #31793 in one shot. But maybe two issues will help break down the issue where they can be worked in parallel/make it into different releases.

**Comment by Piszmog** [comment]
I had another idea/thought on mounting files. So far we have mounting files that are uploaded from a user's machine (uploaded via a batch spec or the UI). But I was thinking that I would be nice to be able to mount files from a remote server/code host. This way I could source control these files/scripts and share them more easily with others.

**Comment by chrispine** [comment]
Cool idea! Make a ticket for it and stick in Triage (unless you think it's small enough that it could be part of the above-mentioned tickets)

**Comment by malomarrec** [comment]
We're making progress on this issue: released in 4.1: mounting files when running server-side.
Up next: displaying mounted files in the UI (read-only)
