### ISSUE TITLE
FilteredConnection hides new entries in a list by setting visible parameter

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#14871]
#### Steps to reproduce:

1. Go to the campaigns list page, having, for example, 4 campaigns in the instance
2. See the query getting a `visible=4` parameter
3. Reload the page to see your new campaign in the list
4. It only shows the first 4 campaigns now, with a show more button, although the default pageLimit is 15.

#### Expected behavior:
It shows up to 15 (or the default configured page limit, really) entries, without respecting the minimum page limit.

#### Actual behavior:
It uses pagination, starting with fetching just 4 entries.

I am not sure what we use that parameter for, especially given that it also sets the `first` parameter when using pagination, for example `first=30`, when the show more button was clicked. It feels like the visible parameter is not needed? Task is to verify what it's for and possibly use something like `if (defaultFirst > visible) { dontAppendVisibleParam() }`.

**Comment by jasongornall** [comment]
Closing as can no longer reproduce see https://k8s.sgdev.org/batch-changes?visible=30. On reload it respects the visible query param
