### ISSUE TITLE
secret: only turn on encryption when the env var is explicitly specified

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#14898]
As of now, the database secrets encryption will be turned on when one of the following happens:
1. The default secret key file exists (`/etc/sourcegraph/token`).
2. The admin specifies the secret key file via env var `SOURCEGRAPH_SECRET_FILE` _and_ it exists.

The proposal [inspired by my reply to @pecigonzalo](https://github.com/sourcegraph/sourcegraph/pull/14705#issuecomment-709162350) is to remove 1. and only keep 2. In addition, when the admin  specifies the secret key file via env var `SOURCEGRAPH_SECRET_FILE`, we throw a hard error when the file does not exist instead of ignoring it.

Would love inputs from @sourcegraph/security about this new proposal before preceding.

**Comment by chayim** [comment]
Throwing a hard error if the file does not exist makes perfect sense! Can we also check file contents - if we have a zero length file, or an invalid key we should similarly throw a hard error. 

Why do you want to eliminate the secret key file and rely solely on the environment variable?

**Comment by unknwon** [comment]
> What is the desire for eliminating the secret key file and relying solely on the environment variable?

@chayim My intent is to make security-related things as simple/explicit as possible here, but if you think keep 1. is valuable, I'm also OK with it.

**Comment by chayim** [comment]
I believe its both valuable, and expected behaviour for secrets. Having secrets written to disk is a concern when permissions and ownership aren't set properly.  I'd rather we keep it.

**Comment by unknwon** [comment]
> Having secrets written to disk is a concern when permissions and ownership aren't set properly

Hmm, I'm a bit confused by this. 

The env var `SOURCEGRAPH_SECRET_FILE` is used to indicate which file Sourcegraph should read the secret key from. The env var itself does not contain any form of the secret key(s). Therefore, the "permissions and ownership" must be set properly without 1. By removing 1., we don't have a default secret key file path, and the admin must tell us which file it is (that contains the secret key) for secrets encryption.

**Comment by chayim** [comment]
I don't know where my head was, my apologies. Maintaining two paths has no value. Removing it, and relying solely on the environment variable is a good idea!
