### ISSUE TITLE
Provide a debug endpoint to list current authz providers

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#14891]
Along with their corresponding external service ID.

Likely adding a route here:

https://github.com/sourcegraph/sourcegraph/blob/a2cdfe9f60cbaf994c488921834d2e007372a25d/cmd/repo-updater/shared/main.go#L238

**Comment by tsenart** [comment]
If this is for debugging, should we implement it in the public API? I'd say an internal debugging endpoint is best.

**Comment by unknwon** [comment]
@tsenart Good point, updated issue.
