### ISSUE TITLE
Remove long-running transactions from dbworker

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#14920]
We discussed, that it will probably beneficial to remove the dependency on long-running dependencies in the worker, by using some kind of additional column for example to "lock" the row, outside of a TX. 
Not sure what this will look like exactly, but this issue shall remind us of that.

**Comment by tsenart** [comment]
@efritz: Any update on this?

**Comment by efritz** [comment]
https://sourcegraph.slack.com/archives/C01AS4GCA90/p1611250001000800?thread_ts=1610961203.000200&channel=C01AS4GCA90&message_ts=1611250001.000800

Will prioritize for next sprint (starting Monday).

**Comment by tsenart** [comment]
Thanks!
