### ISSUE TITLE
Search Performance Data

### ISSUE THREAD

**Issue by poojaj-tech** [sourcegraph/sourcegraph#14927]
Measure additional data for search queries for internal search performance dashboards to quantify indicators of poor search performance. This helps us monitor baseline performance for customers and dig into specifics for slow searches.
--We should analyze this on Sourcegraph Server first because we have latencies for every query.
--I've bolded the data points that have surfaced as most important to measure so far based on customer insights and conversations.

For common search types (all/aggregated view, literal, regexp, symbol, file, repo)
1. Default search experience is slow
- [ ] **# searches resulting in errors**
2. Comprehensive (expensive) search query is run
- [ ] **# system-thrown and user-specified timeouts**
- [ ] **# system-thrown and user-specified high counts** (count:9999999 [#14316](https://github.com/sourcegraph/sourcegraph/issues/14316))
3. Known sources of relatively slower search queries
- [ ]  **API**
- [ ] **Unindexed** 
- [ ] Saved Searches (automated)
- [ ] src-cli
4. Where time is spent in the system
 - [ ] # of repos we attempted to search

To understand the impact of this data, we will additionally need to connect it to search latency. One way to do this is to tie it back to P99, P90, P50 daily/weekly/monthly data but it is _more actionable_ to see this breakdown by % of slow searches that respond in between 0-1 sec, 1-10 sec and 10+ sec. 
Sample solution:
-customer name -> 1 - 10 seconds -> Literal -> Dimensions (e.g. # of errors) outlined above

**Note on Tools for exploration**
[Honeycomb](https://ui.honeycomb.io/sourcegraph/datasets/search) - Useful for running SQL-like queries to dive deeper 
Looker - Better for building dashboards and analyzing customer data

**Comment by poojaj-tech** [comment]
@ebrodymoore created this issue based on our discussion and [RFC for collecting data](https://docs.google.com/document/d/1kwZ0Ilm6Y-9XbKcB5xTwWKYCQgOsOJCr8opUeNxIROY/edit#).

**Comment by poojaj-tech** [comment]
@ericbm I believe we don't know where data lives for these- (from the bolded items)
1. errors
2. system-thrown timeouts
3. API
4. Unindexed
does this sound correct?

**Comment by ebrodymoore** [comment]
Step 1: [This chart](https://lucid.app/lucidchart/ef48fffe-c310-4dcb-99dd-849b37674f3d/edit?shared=true&existing=1&token=76655ee42f149233916ccafab681c6dfad985aa9-eml%3Dericbm%2540sourcegraph.com%26ts%3D1603818376985%26uid%3D135820542&docId=ef48fffe-c310-4dcb-99dd-849b37674f3d&page=0_0#?folder_id=home&browser=icon) (will add more in this comment later)

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket, please let us how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
