### ISSUE TITLE
Hover shows on GitHub but not GitLab for Dockerfile lint extension

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#1493]
- **Sourcegraph version:** 25726_2018-12-18_8277ea5 (25726_2018-12-18_8277ea5)
- **Sourcegraph browser extension version:** v18.12.13.848
- **Platform information:** macOS Majova, Chrome 71.0.3578.98

#### Steps to reproduce:

1. Enable the extension Dockerfile lint extension: https://sourcegraph.com/extensions/ryan-blunden/dockerfile-lint
2. Go to https://github.com/ryan-blunden/learn-kubernetes/blob/master/cats/Dockerfile
3. Go to https://gitlab.com/injenia/ansible-core/blob/master/Dockerfile

![hoversnotworkingsourcegraphextension](https://user-images.githubusercontent.com/133014/50181856-64d36f80-02c2-11e9-8faa-17c3ba5e5609.gif)

#### Expected behavior:

Hovers work on both

#### Actual behavior:

Hovers only work on GitHub

**Comment by lguychard** [comment]
@ryan-blunden could not reproduce this:

![image](https://user-images.githubusercontent.com/1741180/51531197-21c66800-1e3d-11e9-8135-f23a7beb40b8.png)

Is it still an issue on your side?

**Comment by ryan-blunden** [comment]
Confirmed it's now working.
