### ISSUE TITLE
Blob viewer integration test is flaky because browser extension alert sometimes shows

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#14939]
https://percy.io/Sourcegraph/Sourcegraph/builds/7384713?utm_campaign=Sourcegraph&utm_content=Sourcegraph&utm_source=github_status_public

Perhaps we're not clearing localStorage before every test?

**Comment by tjkandala** [comment]
#14694 will likely fix it, I'll merge that now

**Comment by felixfbecker** [comment]
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/15126
