### ISSUE TITLE
Extension search matches only extension ID, not title

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#1494]
Sourcegraph version: 25726_2018-12-18_8277ea5 (25726_2018-12-18_8277ea5)
Sourcegraph browser extension version: v18.12.13.848
Platform information: macOS Majova, Chrome 71.0.3578.98

![extensionsearchissue](https://user-images.githubusercontent.com/133014/50181991-f04d0080-02c2-11e9-843d-7ea61702d8de.gif)

**Comment by sqs** [comment]
It searches the extension id only. This is a bug. It needs to also look in the manifest JSON to search the title and description.
