### ISSUE TITLE
Add (better) filtering/searching capabilities to campaign and changeset(spec) lists

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#14968]
These three lists currently don't feature any extensive filtering and no searching. While this usually doesn't matter in dev where we have like 5 changesets, I started feeling the pain immediately when I created a campaign of a 10k changesets locally. It is just unfeasible to find a specific changeset in the list of all changesets, without paginating through them for a really long time.

I think this task should include some nice UX to do quick filtering actions, but also have a good fuzzy search, that searches titles, bodies and repository names. This could potentially be tricky, given that repository permissions are still on app-level, which probably means we can only do repo name filters in the app level as well. Hence, I'm giving a rather high estimate.

**Comment by rrhyne** [comment]
Sorting will be important too. For instance:

I would like to view changesets by create date descending with a status of open so I can see which items are blocked or stale.

**Comment by chrispine** [comment]
This is awesome, thanks for creating this, Erik!

**Comment by rrhyne** [comment]
@eseliger can you split the filtering and searching features into two separate tickets? We want to try and break this into smaller pieces.

**Comment by eseliger** [comment]
Sure thing:

- Searching: https://github.com/sourcegraph/sourcegraph/issues/15781
- Filtering: https://github.com/sourcegraph/sourcegraph/issues/15783
- Ordering: https://github.com/sourcegraph/sourcegraph/issues/15784

**Comment by LawnGnome** [comment]
This is now several tickets. Closing.
