### ISSUE TITLE
Streaming Search Progress API Proposal

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#14977]
Our progress API (previously called stats) is the biggest change in our move to streaming. We are wanting to tackle some debt as well as plan for the future. This is a proposal for the API.

[Figma Design](https://www.figma.com/file/IyiXZIbPHK447NCXov0AvK/%2313928--Streaming-search?node-id=0%3A1)

This is what we currently request from GraphQL in the webapp:

```graphql
limitHit
matchCount
approximateResultCount
missing {
    name
}
cloning {
    name
}
repositoriesCount
timedout {
    name
}
indexUnavailable
elapsedMilliseconds
```

This is our proposal for a progress event in the streaming API. We have tried to match up with the Figma designs with what makes sense from the backend. See below for commentary.

```typescript
// Aggregate type. Replace when new ones come in.
interface Progress {

    /**
     * Every repository is broken down into 1 or more shards. This is an
     * increasing number of the number of shards searched so far. We don't
     * give a statistics on number of repositories for two reasons:
     *
     * 1. Does not represent progress in a monorepo.
     * 2. Expensive to give an accurate count over time.
     */
    shardsSearched: number

    /**
     * The total number we will search. This will increase over time.
     */
    shardsTotal: number

    // The number of repositories matching the repo: filter. Is set once they
    // are resolved.
    repositoriesCount: number

    // The number of non-overlapping matches. If skipped is non-empty, then
    // this is a lower bound.
    matchCount: number

    // Wall clock time in milliseconds for this search.
    durationMS: number

    // A description of shards or documents that were skipped. This has a
    // deterministic ordering.
    skipped: Skipped[]
}

interface Skipped {
    /**
     * Why a document/shard/repository was skipped. We group counts by reason.
     * 
     * - document-match-limit :: we found too many matches in a document, so we stopped searching it.
     * - shard-match-limit :: we found too many matches in a shard/repository, so we stopped searching it.
     * - shard-timeout :: we ran out of time before searching a shard/repository.
     * - repository-cloning :: we could not search a repository because it is not cloned.
     * - repository-missing :: we could not search a repository because it is not cloned and we failed to find it on the remote code host.
     * - excluded-fork :: we did not search a repository because it is a fork.
     * - excluded-archive :: we did not search a repository because it is archived.
     * - repository-limit :: we did not search a repository because the set of repositories to search was too large.
     */
    reason: "document-match-limit" | "shard-match-limit" | "shard-timedout" | "repository-cloning" | "repository-missing" | "excluded-fork" | "excluded-archive" | "repository-limit"
    // The number of documents or shards that match this reason.
    count: number
    // A message to show the user. Usually includes information explaining the reason, count as well as a sample.
    message: string
    // sample is a subset of the shards or document@shards that where not searched or not fully searched.
    sample: string[]
    severity: "info" | "warn"
    // a suggested query expression to remedy the skip. eg "archived:yes" or "timeout:2m".
    queryExpression?: string
}
```

<a id="org7ac659b"></a>

# Shards vs repositories

We want to show progress made. Above we propose `shardsSearched` and `shardsTotal`, both increasing over time. A repository is one or more shard(s). The reason we want to use the language "shard" instead of "repository" is it more accurately represents progress. For example in a mono-repo case, the repo may represented by 30 shards. In the Figma design there was this comment:

> If 1 repository was searched, should we switch to docs based stats?

By relying on shard, we can always use the shard number to represent progress.

Additionally shard is generic enough to work in future search directions (eg searching over google docs?). Moving to a more generic language of document and shard is more accurate as well as more flexible for the future.

An example where shard is better. The search `repo:foo@*refs/heads/*` searches all the branches in a repository. Right now we report that as 1 repository. However, the progress we make will be per branch. Each branch will be its own shard.

What do you think of this language change? How do we explain to users?

Note: We still have `repositoriesCount`. This is the total number of repositories matching a the filter, a number still generally useful as users narrow down a search query.

<a id="org8c1101b"></a>

# What is result count?

It's worth narrowing down, because this has been a source of no confidence/non-determinism.

Here are the possible interpretations:

-   Number of file matches. Generically the number of documents which contain a match.
-   Number of line matches. Generically the number of lines in a document which contain a match. This is what we currently document as the value of `matchCount`. However, we don't strictly stick to that definition across search types and have some other heuristics at play.
-   Number of non-overlapping ranges? This is what zoekt reports as match count. To me this is the most useful number. If I search `foo`, I'd expect the match number to be the number of times the word `foo` appears.

All of these make sense, we should try and clarify it. I propose switching the number to "Number of file matches". This number is useful, and is the most likely to stay stable over time. However, is it useful enough?

<a id="org87f51fc"></a>

# "1.3k repositories not searched"

In the Figma designs we use the copy "1.3k repositories not searched". Here are some comments on that copy with respect to the above API:

-   We want to use the word "skipped".
-   We can also return documents that were skipped.
-   We want to use the word "shards" and/or "documents".

<a id="orgf323185"></a>

# Dropdown and interface Skipped

Right now there is an example of the drop down for things that where not searched. It has the layout:

    ! A timeout occurred
    370K repositories could not be searched. Try
    reducing scope of your query with repo:
    repogroup: or other filters.
    
    Continue this search with the excluded
    repositories and a larger timeout:
    
    [ ] 1,200 forked (forked:yes)
    [ ] 1,200 archived (archived:yes)
    
    Timeout: [60s]
    
    [Continue searching]

We have tried to capture this information in `interface Skipped`. Notice that `skipped: Skipped[]` is an ordered list of skipped notifications to show the user. We imagine the above example would look like the following:

```typescript
[{
    reason: "shard-timeout",
    count: 370000,
    message: "370K repositories could not be searched. Try reducing scope of your query with repo: repogroup: or other filters.",
    sample: ["github.com/foo/bar", "github.com/foo/baz", ...],
    severity: "warn",
}, {
    reason: "excluded-fork",
    count: 1200,
    message: "By default we exclude forked repositories. Include them with \"fork:yes\" in your query.",
    sample: ["github.com/foo/fork"],
    severity: "info",
    queryExpression: "forked:yes",
}, {
    reason: "excluded-archive",
    count: 1200,
    message: "By default we exclude archived repositories. Include them with \"archived:yes\" in your query.",
    sample: ["github.com/foo/archived"],
    severity: "info",
    queryExpression: "archived:yes",
}]
```

Whats missing is the copy "Continue this search with the excluded repositories and a larger timeout:". This could be generated in the webapp from the list of reasons.

Do we need info bubbles so we can show the "message"?

How would you change the design with this API?

<a id="org0c6c5ad"></a>

# Addendum :: Potential fields

We also considered including the below progress indicators. These also indicate progress like our shard numbers. They are also very useful numbers to try and help us understand performance issues. We are excluding them now for keeping the API minimal, but would be interested in introducing them in the future.

`message` seems useful for the backend summarising what its currently doing. I am leaving it out of the proposal for now since it isn't clear to me what those messages will be yet. But I'd be interested to know how this could affect the design.

```typescript
interface Progress {

    // Amount of I/O for reading contents. Note: Only indexed text search
    // reports this number.
    contentBytesLoaded: number

    // Amount of I/O for reading from an index. Note: Only indexed text
    // search reports this number.
    indexBytesLoaded: number

    // a generic message the backend wants to communicate about progress.
    message: string
}
```

Part of #13067 

cc @sourcegraph/search

**Comment by keegancsmith** [comment]
@rrhyne @limitedmage @lguychard I've assigned you all to take a look and respond. Please un-assign yourself once you have responded :)

Also if you have a penchant for the old school, here is the above proposal as a txt file. Might be easier to manipulate for replying: [progress-api-proposal.txt](https://github.com/sourcegraph/sourcegraph/files/5421550/progress-api-proposal.txt)

**Comment by rvantonder** [comment]
Following sync: I can see the usefulness of shards metric (so, in general, in favor of communicating this, or a progress metric derived from it). It also feels entirely Zoekt-specific, so how would that fit into progress for, say, unindexed search. You might say "we don't care" about unindexed search but I mean more generally, e.g., if we decide to use other search-like backends where shards is not part of the terminology/quantity of progress (let's say there's some backend that could be dedicated to searching commits, etc. which may or may not use Zoekt). So maybe we can generalize this metric, along the lines of the other fields in the Addendum.

---

result count:

> I suspect that for code results, most users would instinctively expect "result count" to mean "non-overlapping ranges". It would be nice to validate that assumption though.

Agree

> I could maybe see "number of file matches" as an unintuitive when a user is expecting an exhaustive result?

> Ultimately, we should surface both non-overlapping ranges and file matches in result stats ("X results across Y documents, Z shards").

Fully agree. It is important to report the number of matches subject to search kind (file contents, files, etc) and we should strive to provide the full breakdown. It is extremely useful to have match counts from an API perspective (e.g., to measure number of calls matched in commit X versus commit Y). Only reporting file matches is limiting. 

More past discussion about this: https://github.com/sourcegraph/sourcegraph/issues/9426#issuecomment-607396894

> because this has been a source of no confidence/non-determinism.

Even though it's a source of no confidence/non-determinism, we should still collect/report it IMO. Limiting our own visibility into number of matches will just make things harder, and if we do use a solution that improves on this, we'd want to report it.

---

While we're discussing match count:

> Number of line matches. ... This is what we currently document as the value of `matchCount`

Where is that documented? Related, in https://github.com/sourcegraph/sourcegraph/pull/11242 I pointed out my discovery that Zoekt seems to report line matches and not non-overlapping ranges, and I think that's still the case. In that PR I took the Zoekt result and calculate the non-overlapping ranges, which is what we now report in text search results.

**Comment by rrhyne** [comment]
> We want to use the word "skipped".

Works for me. 

**Progress bar:**

> By relying on shard, we can always use the shard number to represent progress.

For progress, a text label does not matter, we can simply show percentages or graphics depicting percentage of completeness. 

I initially designed a progress bar that is akin to the spinning loop, in that it doesn't try to display a percentage value or reach 100%. I am updating to a design that does display percentage complete. @keegancsmith will that also work for indexed search, or will we need both? 

**Result count:**
Seconding Rijnard's statements and adding that I believe this affects code insights (@Joelkw @felixfbecker ) heavily. If I'm looking for the number of uses of a function, file matches is certainly the wrong metric. Lines is also potentially inacurrate to some degree. I think this should be as consistent as possible across all search types. 

**Shard/doc/repo label in relation to what is being searched**

I would very much not like to communicate with the word 'shards'. Consider an instance where I have specified a set of repositories like r:^github.com/sourcegraph/* and I know there are roughly 50 repositories that match that query. Returning that Sourcegraph searched 400 of 500 shards, means little to me. 

I'm also not sure that documents searched is a meaningful metirc. I know how many repositories I have. I may know roughly how many there are in my team. I have no clue how many are in my company and keeping track of how many files the company has doesn't seem valuable or knowable. 

Due to the above, I've removed all attempts to place a number on what was searched from the update set of comps. I'm ok with this if everyone else is. 

**Shard/doc/repo label in warning / error messages / complete messages**

In the section "1.3k repositories not searched" you suggest we change messaging to documents or shards.  The result of that dropdown is the interface that shows the user the number of forked, archived and possibly cloning repositories that were skipped. I am having a difficult time reconciling this difference in messaging. We current have that number, so I'm confused as to why we would need to do this. Monorepo use case? Archived, forked or cloned won't be a factor there. We can display documents skipped for those with more than 1000 matches. What other messages are likely to appear here for monorepos?

_Is there a difference in the available data of complete searches vs. in progress searches?_ If so, and we have repositories skipped for timeouts in addition to the forked, archive and cloned numbers, I think we should display that number here.

*Use case example:*
My search must be exhaustive for something critical like a token. It times out and some repositories were not cloned, some were archive and some were forked. I would like to try and limit my search to only the repositories which were not previously searched. In this use case, I need to know how much of my code wasn't searched and I need a way to search it. Shards and documents doesn't help as there are no search filters I can use to act on this knowledge. 

Due to the above, is there a way we can maintain repositories skipped for this display?

**Comment by lguychard** [comment]
> For progress, a text label does not matter

👍

> I've removed all attempts to place a number on what was searched from the update set of comps. 

That direction looks good. Maybe we could also do the same for the "skipped" indicator, and have it simply read "partial result set"? In the monorepo use case you might still have a partial result set even though no repository was technically skipped. The copy I suggest always accurate.

![image](https://user-images.githubusercontent.com/1741180/97322378-05f0c100-1870-11eb-81d7-910ad4a94c47.png)

> We currently have [the number of skipped forked/archived repositories], so I'm confused as to why we would need to [change messaging to documents or shards]
> is there a way we can maintain repositories skipped for this display?

I will let @keegancsmith chime in here for Correct Information™️ , but my understanding is that coming up with a precise number for skipped repositories is not trivial for all skipped reasons.

Closing remarks:

> I would very much not like to communicate with the word 'shards'.

While we may not want to have "shards" prominently featured in the UI, I wouldn't see that much of a problem in exposing it to users in a location where more verbose copy is acceptable if we feel like that term (or any other terminology) is the most accurate description of what our search is doing. We'd of course have to back that up with high-quality supporting documentation explaining what the term covers. I would greatly prefer that to exposing a less accurate metric for the sake of user-friendliness -- if execution is right, full transparency would go a long way towards improving confidence in "what Sourcegraph search is doing".

**Comment by rrhyne** [comment]
>  Maybe we could also do the same for the "skipped" indicator

> I would greatly prefer that to exposing a less accurate metric for the sake of user-friendliness

I look at this more as solving core use cases, than friendliness. For example:

As a user I need to find repositories where a critical API I'm about to change is called.
* If forks and archives were skipped, I need to see those repositories so I can contact owners
* If some of the repositories were not cloned, I need to wait and search again to find usages (or fix the problem)
* If a timeout occurs I need to understand how many repositories were missed and how to find the rest of them

Can we communicate to the lack of precision, but provide some level of useful information about the repositories not searched? Does streaming provide the number of forked, archived, cloned, not found and timed out repositories as per current?

Apologies for my lack of knowledge here, I don't mean to ask for the impossible, just trying to find a balance between use cases and capabilities!

**Comment by limitedmage** [comment]
I think that "shards" should not be featured prominently, but I'm OK with them being featured in verbose detail (such as the dropdown dialog when clicking on the progress button) for users that really want to know how much they have searched for. I agree with Keegan that this will be very valuable for monorepo use cases or when searching multiple branches in the same repo.

For the progress API, my only concern is that in `Skipped`, the `count` will be ambiguous depending on the `reason`. Could we add a `countType` or similar with type `'document' | 'shard' | 'repository'` to make this clear?

**Comment by rrhyne** [comment]
I think any time a single repository is searched (to cover the mono repo use case), we should use the documents count:

![image](https://user-images.githubusercontent.com/539268/97345786-c1512f80-1847-11eb-8b7f-06cb26a1f89a.png)

Can I get some examples of the use of 'shards' that would be useful to customers? How would you alter your searches or act on the information return? I'm having a hard time visualising this.

**Comment by Joelkw** [comment]
Just echoing @rrhyne's callout that knowing a deterministic count of non-overlapping ranges for a specific search is likely necessary for many of the insights we're chatting with customers about and that we have heard excitement around in the past (like tracking a code smell or migration over time, library usage, which functions from which dependencies are used and how often, the number of times code that a team or individual wrote gets used, and so on). Nothing else to contribute, sneaking back into the shadows...

**Comment by felixfbecker** [comment]
I'm a bit confused by the rename from "stats" to "progress". Does this imply that this data is now some evolving value? How would we get the definite, final counts for the code insights use cases described above by @Joelkw?

Only other suggestion I have on the API is to make sure the types are prefixed with `Search`, just "Progress" is a bit ambiguous (could be a "campaign progress" too).

**Comment by keegancsmith** [comment]
Thanks for all the feedback. I realised I haven't actually responded on this issue, apologies. An updated API is proposed in a PR https://github.com/sourcegraph/sourcegraph/pull/15430 Copying the description here for convenience which will be a reply to the above discussion.

The following changes have been made after feedback:

### Removing counts

Lots of feedback over if shards is a good word to communicate. The
progress API is instead updated to just communicate "copy" for
implementing the UI. The only places we will now expose counts is total
number of repositories, in the messages for skipped items and match
counts.

### Done

The boolean field Done is added to indicate the progress update is the
final/last one. This is useful for affecting how we communicate
numbers. Until we have a final progress update all communication must
assume result sets can change.

### Skipped

Skipped now has a title and a message. This matches the mocks in
Figma. Additionally suggested query now has a title and what should be
added to the query.

---

@Joelkw @felixfbecker we still expose the same counts we previously did. Designing this API exposed that our match count was ill-defined in the existing GraphQL API. As part of our work we will make it exact and match other intuitions (number of non-overlapping results)

@felixfbecker none of the interfaces are currently exported for streaming search. Once they are, I see it is convention to have a globally unique name in our codebase. We will update them when exported to have a consistent prefix.

**Comment by Joelkw** [comment]
@keegancsmith appreciate the update, thank you!
