### ISSUE TITLE
External service list should indicate which services are user owned

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#14976]
We list all external service here:
https://sourcegraph.com/site-admin/external-services

We should include a UI element that shows which services are user owned and which are admin owned.

Ideally we also want to be able to filter by All / Admin/ User

**Comment by ryanslade** [comment]
@tsenart Maybe this could be a good initial task for AR when he joins?

**Comment by tsenart** [comment]
@ryanslade: Yep!

**Comment by ryanslade** [comment]
Removed milestone 3 label as this doesn't block it.
