### ISSUE TITLE
cors-anywhere secure deployment notes

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#15025]
Below are my notes on important things to consider for deploying a cors-anywhere service in a secure way.

Important readings:

- https://github.com/sourcegraph/infrastructure/pull/2209#pullrequestreview-510790952
- https://medium.com/certik/cors-anywhere-the-dangers-of-misconfigured-third-party-software-df232aae144c
- https://github.com/Rob--W/cors-anywhere/issues/152#issuecomment-462486081
- https://github.com/Rob--W/cors-anywhere/issues/79#issuecomment-322583203
- https://github.com/Rob--W/cors-anywhere/issues/79#issuecomment-482802428

Some random thoughts on deploying this in a secure way:

1. Definitely need this to be in a completely isolated k8s cluster, so it cannot reach any other service we have. I am not sure an isolated k8s cluster alone is enough, probably an isolated bare metal GCP instance is better.
1. Ideally we allowlist only specific origins, I think, but if not then we need to verify it cannot hit any local DNS or IPs such as to access k8s, GCP, or EC2 metadata via a metadata URL that those expose. See [my comment above](https://github.com/sourcegraph/infrastructure/pull/2209#pullrequestreview-510790952).
1. Definitely need to avoid having this deployed under the same sourcegraph.com domain - we should purchase a seperate domain here.
1. We should use an existing implementation for this I imagine? it seems we use our own hand-rolled one right now, but there are probably some things we're not properly handling like how to handle auth cookies in a secure way. e.g. cors-anywhere.herokuapp.com says:

> **Cookies are disabled and stripped from requests.**
>
> Redirects are automatically followed. For debugging purposes, each followed redirect results
> in the addition of a X-CORS-Redirect-n header, where n starts at 1. **These headers are not
> accessible by the XMLHttpRequest API.**
> **After 5 redirects, redirects are not followed any more.** The redirect response is sent back
> to the browser, which can choose to follow the redirect (handled automatically by the browser).
>
> **The requested URL is available in the X-Request-URL response header.**
> The final URL, after following all redirects, is available in the X-Final-URL response header.
>
> **To prevent the use of the proxy for casual browsing, the API requires either the Origin
or the X-Requested-With header to be set. To avoid unnecessary preflight (OPTIONS) requests,
it's recommended to not manually set these headers in your code.**

These are all likely related to abuse prevention and/or security. As a starting point I'd suggest we deploy https://github.com/Rob--W/cors-anywhere with modifications.

**Comment by daxmc99** [comment]
[Kubernetes Network Policies](https://kubernetes.io/docs/concepts/services-networking/network-policies/) would provide a option to run a service like this

**Comment by slimsag** [comment]
@daxmc99 interesting, I hadn't seen those before - but are you sure those can prevent in-cluster traffic (malicious container -> in-cluster pod), and traffic from the container -> host machine (AWS/GCP node metadata endpoints)? I didn't read the docs in-depth, but saw these two points at the end which make me think it does not:

> What you CAN'T do with network policies (at least, not yet)
>
> * Forcing internal cluster traffic to go through a common gateway (this might be best served with a service mesh or other proxy).
> * The ability to prevent loopback or incoming host traffic (Pods cannot currently block localhost access, nor do they have the ability to block access from their resident node).

**Comment by daxmc99** [comment]
@slimsag 

- Can they prevent in-cluster traffic (evil pod -> friendly pod)?
Yup, this is their primary use case. 

This sample network policy would only allow pods labelled `foo` to talk to pods labelled `hello`
<details>
<summary>Details</summary>

```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: foo-allow-to-hello
spec:
  policyTypes:
  - Egress
  podSelector:
    matchLabels:
      app: foo
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: hello
  - ports:
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP
```

</details>

- Traffic from the container -> host machine (AWS/GCP node metadata endpoints)

This outgoing traffic could be stopped by a `DENY EGRESS` rule as long as its not using `127.0.0.1` with a network policy. Also could be mitigated via GCP metadata protection settings. 

My bigger concern is that network policies aren't supported by default outside of GKE. They typically require installing a separate CNI.

**Comment by slimsag** [comment]
> This outgoing traffic could be stopped by a DENY EGRESS rule as long as its not using 127.0.0.1 with a network policy. Also could be mitigated via GCP metadata protection settings.

I'm not familiar with GCP metadata protection settings, but that sounds like what we'd need - I am worried what other info is accessible via `127.0.0.1` or on the host node.

> My bigger concern is that network policies aren't supported by default outside of GKE. They typically require installing a separate CNI.

We don't need to run this outside GKE, it's for Sourcegraph.com only and would not be run on-prem.

**Comment by slimsag** [comment]
Important to call out here, even if network policies solve this, I think we should deploy this in an isolated cluster still to mitigate us messing anything up and shooting ourselves in the foot - AND we still have to address:

- [ ] "Ideally we allowlist only specific origins" - Web team needs to answer this I think
- [ ] Definitely need to avoid having this deployed under the same sourcegraph.com domain - we should purchase a seperate domain here.
- [ ] "there are probably some things we're not properly handling like how to handle auth cookies in a secure way. e.g. cors-anywhere.herokuapp.com says:" - I think this is a big risk.

**Comment by felixfbecker** [comment]
>  "Ideally we allowlist only specific origins" - Web team needs to answer this I think

The link preview extension by nature needs to be able to request any URL.

>  Definitely need to avoid having this deployed under the same sourcegraph.com domain - we should purchase a seperate domain here.

👍 sounds good.

>  "there are probably some things we're not properly handling like how to handle auth cookies in a secure way. e.g. cors-anywhere.herokuapp.com says:" - I think this is a big risk.

👍  I'd be in favor of replacing the hand-grown service with the open source one. I don't remember why we wrote one ourselves. This should be as simple as changing the image name in the deployment.

**Comment by conwnet** [comment]
The sourcegraph API is powerful, is there any plan for supporting call it anywhere?
Just without cors check, of course just for anonymous calling, no cookie will be taked.
