### ISSUE TITLE
Add Postgres dashboards with alerting

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#15029]
Continuation of https://github.com/sourcegraph/sourcegraph/issues/14451 

We have access to Postgres metrics in a Sourcegraph installation but we currently have no alerts around this. 

We should have 2 seperate dashboards for each Postgres database. The LSIF database likely has different concerns than the general database. 

This complements our existing, cloud-only `PgHero` deployment 

cc @efritz , cc @tsenart

**Comment by daxmc99** [comment]
Plans to add additional alerts to allow for checking if database schemas are dirty

**Comment by tsenart** [comment]
We need also alerts for slow queries in the user request path (say, more than 500ms) and in the background (say, more than 5m).

**Comment by tsenart** [comment]
cc @ryanslade
