### ISSUE TITLE
No TypeScript code intel on GitHub.com

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#1502]
Go to https://github.com/sourcegraph/sourcegraph/blob/master/web/src/backend/graphql.tsx and see no code intelligence.

Error in the console:

```
Error activating extension "sourcegraph/lang-typescript": i: error thrown while executing extension "sourcegraph/lang-typescript" bundle (in importScripts of blob:chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/3ea115ca-e36a-4dc5-9db9-7b15da14523b): Error: Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' blob:".
```

We noticed this after we deployed the new prod cluster. I unfortunately don't know if this was an issue pre-deploy.

**Comment by felixfbecker** [comment]
If this does not happen on Sourcegraph then it looks like a browser extension issue to me, specifically a permissions issue, and I assume it happens for all extensions not just typescript. What browser are you using?

**Comment by lguychard** [comment]
This does not happen for all extensions, happens only for lang-typescript (eg no issue for lang-go)

**Comment by felixfbecker** [comment]
Filed https://github.com/lightstep/lightstep-tracer-javascript/issues/141

**Comment by felixfbecker** [comment]
Fixed by removing Protobuf support in our fork
Also released new bext version
