### ISSUE TITLE
if no namespace is given, default to username

### ISSUE THREAD

**Issue by chrispine** [sourcegraph/sourcegraph#15058]
- [x] If no `-namespace` is passed in to src-cli, use the username as a default.
- [x] Update [all references to the `-namespace` parameter in docs](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+-namespace+f:doc/campaigns&patternType=regexp)
- [x] Create a section in "Create a campaign"-how-to that explains how to choose a different namespace

**Comment by mrnugget** [comment]
FYI I updated the ticket description to mention that docs also need to be updated.
