### ISSUE TITLE
Repository page design and discovery

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#15057]
Repository pages could be vastly improved by including commits, the project readme, branches, tags, and other key content. 

Additionally, adding an 'index' of repository pages that focuses on browsing and discovering repositories would enable 'code discovery' within an organization. This index page would be promoted as a top-level destination within the application. 

See:

* [Render READMEs by default on repo/tree pages (#9561) ](https://github.com/sourcegraph/sourcegraph/issues/9561)
* [SQS's repository page hack project](https://sourcegraph.slack.com/archives/C014ZCKMCAV/p1601195775005600): 

![image](https://user-images.githubusercontent.com/539268/97201928-394c2680-1770-11eb-861e-19855e6bc819.png)

#### Estimated amount of work
- M - up to a month

#### Impact
Makes individual repository pages more valuable to users. Also promotes repositories as a first-class citizens in the UI, which could enable code discovery.

#### Urgency
1st quarter 2021?

**Comment by jasongornall** [comment]
@plibither8 / @umpox should we keep this one around? Seems like we are rethinking an attack on this page

**Comment by rrhyne** [comment]
I suggest closing as this is VERY old. Since this was written, @jjinnii  has done some design work that was featured in a hackathon project. It may be a more appropriate ticket.
