### ISSUE TITLE
Extension registry animation box shadow color now has full opacity

### ISSUE THREAD

**Issue by tjkandala** [sourcegraph/sourcegraph#15064]
![extanimreg](https://user-images.githubusercontent.com/37420160/97219583-95c73a00-17a0-11eb-8b22-ba44c830a398.gif)

The new color is harsher than the original color. What was the source of this regression?

cc @AlicjaSuska what do you think about this color?

**Comment by AlicjaSuska** [comment]
Thank you for bringing this up @tjkandala. This color is too intense, let's come back to the previous version. The same thing is happening in the dark mode FYI

**Comment by felixfbecker** [comment]
This is likely a regression from Quinn's PRs to use color variables everywhere and should be a quick fix.

**Comment by muratsu** [comment]
@AlicjaSuska this seems to be fixed with the redesign. If you agree I'll close the issue

**Comment by AlicjaSuska** [comment]
Yes, it's fixed. Let's close. Thank you @muratsu
