### ISSUE TITLE
Sourcegraph GraphQL API is undiscoverable in the extension API

### ISSUE THREAD

**Issue by tjkandala** [sourcegraph/sourcegraph#15069]
Extensions can execute Sourcegraph GraphQL API queries and mutations through `commands.executeCommand`. This is a powerful feature, but is undiscoverable and clunky to use in its current state. 

We should implement a dedicated API to provide type definitions and hover documentation.

**Comment by Joelkw** [comment]
@tjkandala does this belong in our current iteration? If not, could you add it to the backlog board in "to Triage"?

**Comment by tjkandala** [comment]
@Joelkw  It's part of our plan for this iteration ([bookmarked in extension improvements doc](https://docs.google.com/document/d/1l0grJVcTLdKGhRZD2LUMjB2e95xhnhBIE-oX5D_LAZQ/edit#bookmark=id.fvtwgyckri77))

**Comment by Joelkw** [comment]
@tjkandala thought so! Sorry, to be explicit – I meant "current iteration board." I've added it there; feel free to move around.
