### ISSUE TITLE
extension-api-stubs package isn't mentioned in the docs and not included by the extension generator

### ISSUE THREAD

**Issue by tjkandala** [sourcegraph/sourcegraph#15060]
The Sourcegraph extension API package doesn't implement any methods; its purpose is to provide type definitions to extension authors and a "hook" (call to `global.require`) by which the extension host can provide extensions the concrete extension API. This adds complexity to testing Sourcegraph extensions, since users must stub the API. We can't reasonably expect authors to go through this effort to write unit tests, but we want our extension registry to be populated with well-tested extensions

**Action items**

- Add a section on testing to extension authoring docs
- Add a section to extension authoring docs that explains how the Sourcegraph extension API package works
- Add [`extension-api-stubs`](https://github.com/sourcegraph/extension-api-stubs) to the [`create-extension`](https://github.com/sourcegraph/create-extension) Sourcegraph extension generator so that users don't have to set up the test harness themselves

**Comment by marekweb** [comment]
Closed by #15516 and sourcegraph/create-extension#153
