### ISSUE TITLE
Server side execution of campaign specs

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#15083]
Currently, the only well supported workflow for campaigns is to run src-cli which evaluates the campaign spec and creates changeset specs from it, which then get uploaded to the Sourcegraph instance, which opens the changesets on the code hosts.

Ultimately, we should want to have more ways of running campaigns than just the src-cli one, namely server side execution.

In the past, there have been a few efforts in this direction, tracked by https://github.com/sourcegraph/sourcegraph/issues/7723 and [spec'd here](https://docs.google.com/document/d/1z3kzSFA6OApx_6kvAB7j40I1WxHdf3exD8EtEbfPd7I/edit#heading=h.trqab8y0kufp). 

These efforts require the resolution of several questions surrounding worker healthchecks, block storage, and deployment/security concerns.

Codeintel has made big steps in this direction since then and many of the previous points have been addressed. When this ticket is picked up again, we should revisit requirements based on their work on the issue.

**Comment by mrnugget** [comment]
Another bag of thoughts:

Codeintel implemented a worker queue that allows the `frontend` process to schedule jobs to be run inside a firecracker VM. The implementation is fairly generic and allow running `src-cli` and Docker containers in firecracker VMs.

Eric Fritz created a draft-spike-hack PR that shows how we could run `src campaigns apply` in that VM: https://github.com/sourcegraph/sourcegraph/pull/14915

A possible path forward would be to do just that: implement the GraphQL API for server-side execution but simply start by shelling out to `src campaign apply` in the Firecracker VM. That, plus a UI and logging, would get us to a minimal-minimal-viable-product that we could dogfood ourselves. Then we could optimize this solution, step-by-step, having a running version with each step:
  1. Run `src campaign apply` in Firecracker VM, outputting progress as JSON-lines
  2. Modify `src campaign apply` to have a hidden `ENABLE_SERVER_MODE` var that we can use to toggle functionality on/off
  3. Modify `src campaign apply` in server mode to not send changeset specs up via API, but output them. Output is then used to save them in the database directly. Create the campaign spec entirely in the backend.
  4. Evaluate the `on.repositoriesMatchingQuery` queries not in `src-cli`, but in our backend, then run `src campaign apply` in server mode, _once per repository_ yielded by the evaluation of the search
  5. ... more...

Steps 2, 3, 4, 5 don't have to be done in that order — I don't know what the order would be.

But then, somewhere around step 20: remove `src campaign apply` altogether and execute the `steps` directly in the VM — this requires the templating/evaluation of `steps.run`, `steps.files`, `steps.env` to be done in the firecracker VM.

**Comment by malomarrec** [comment]
#21018 duplicates this, and is linked to Productboard
