### ISSUE TITLE
repo store: Stop using the global dbconn

### ISSUE THREAD

**Issue by asdine** [sourcegraph/sourcegraph#15092]
The shared RepoStore type uses the global `dbconn` connection. In an effort of [cleaning up the database package](https://github.com/sourcegraph/sourcegraph/issues/11676), we must stop using that global handle and instead instantiate the store in the main function of each service using that store, using [NewRepoStore](https://github.com/sourcegraph/sourcegraph/blob/d9ad15cabb5eba2fc36d31133601facb7b84b540/internal/db/repos.go#L60-L60), and pass that store to any function/type that needs it.

**Comment by tsenart** [comment]
Superseded by #16586
