### ISSUE TITLE
Bullet points in hover markdown not rendered on GitHub

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#1510]
Sourcegraph version: 25726_2018-12-18_8277ea5 (25726_2018-12-18_8277ea5)
Sourcegraph browser extension version: v18.12.19.1240
Platform information: macOS Majova, Chrome 71.0.3578.98

#### Steps to reproduce:

1. View [Dockerfile on Sourcegraph](https://sourcegraph.com/github.com/ryan-blunden/learn-docker@master/-/blob/mkdocs/Dockerfile) to see expected styling.

<img width="973" alt="screen shot 2018-12-19 at 5 17 52 pm" src="https://user-images.githubusercontent.com/133014/50257989-8a3fa680-03b2-11e9-9789-df012d2a1c15.png">

Then view on GitHub, there are no bullets visible.

<img width="1028" alt="screen shot 2018-12-19 at 5 17 41 pm" src="https://user-images.githubusercontent.com/133014/50258026-b22f0a00-03b2-11e9-858b-21b9a920c392.png">

**Comment by sqs** [comment]
Guessing this is a CSS issue, not an extensions rendering issue, so relabeled to `browser-extension`.

**Comment by felixfbecker** [comment]
@ryan-blunden what extension do I need to reproduce this?

**Comment by ryan-blunden** [comment]
The docker lint server had gone down which is why you weren't seeing any highlighted lines. It's back up and running now.

To reproduce:

1. Enable the [docker lint extension](https://sourcegraph.com/extensions?query=category%3ALinters)
2. [View a Dockerfile on sourcegraph.com] and mouse over the red line to see styles.
3. Do the same on GitHub.

**Comment by ryan-blunden** [comment]
Can probably fix #1950 with this change as well.

**Comment by felixfbecker** [comment]
@ryan-blunden the extension doesn't work for me unfortunately:

![image](https://user-images.githubusercontent.com/10532611/78047916-3d9a9780-7379-11ea-949e-d56db0006a95.png)

**Comment by ryan-blunden** [comment]
This could be reproduced with an extension that produces hover content with a h2 then a bulleted list. Nothing really specific to the Dockerfile lint extension itself.
