### ISSUE TITLE
campaigns: let this base branch be created from the default branch if it does not yet exist

### ISSUE THREAD

**Issue by LawnGnome** [sourcegraph/sourcegraph#15110]
Feature request: [let this base branch be created from the default branch if it does not yet exist](https://github.com/sourcegraph/src-cli/pull/361#issuecomment-716901424)

_Originally posted by @bobheadxi in https://github.com/sourcegraph/sourcegraph/issues/15070#issuecomment-716903172_

**Comment by chrispine** [comment]
I'm 90% sure that "base branch" means "target branch", yes?

**Comment by LawnGnome** [comment]
> I'm 90% sure that "base branch" means "target branch", yes?

Yep.
