### ISSUE TITLE
campaigns: #15101 caused repo-updater startup to block

### ISSUE THREAD

**Issue by LawnGnome** [sourcegraph/sourcegraph#15128]
This [caused an issue](https://sourcegraph.slack.com/archives/CMMTWQQ49/p1603922480483500) when deployed. I think this is because this function blocks until a signal is received and the workers stop, so it's [normally used as the last call in a process's `main()`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@42e1af75fa4a04a3d24f8fcf92314075388a8484/-/blob/internal/goroutine/background.go#L33:6&tab=references).

I think the fix here would be to propagate the started workers back up to `main()`, then call this function there for monitoring.

_Originally posted by @LawnGnome in https://github.com/sourcegraph/sourcegraph/pull/15101#r513794082_

**Comment by LawnGnome** [comment]
@eseliger I've assigned this to you for now because you know this code better than I do, but feel free to kick it back if you don't have time to look into it and I'll pick it up.

**Comment by eseliger** [comment]
Thanks! I'll fix it 🤦
