### ISSUE TITLE
Sharing of Sourcegraph searches breaks when using GitHub auth

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#15132]
At the 3 minute mark [in this research video](https://drive.google.com/file/d/1ruxK2I-x-VvQ-_TY8YQDCict5ZRIEI3J/view) a customer states:

"I'll often go to the Github page and share that. Sharing links with Sourcegraph is often less useful than linking directly... this could be something you could configure: when you are given a link, click it, prompt for login. When you log in with github it goes back to the main page."

The sharee must know they can hit back in the browser to see the actual search. 

This is an inhibitor to growth and should be corrected sooner rather than later.

**Comment by felixfbecker** [comment]
Ugh this is unfortunate. This could likely be more of a backend issue though, I'm not entirely sure how these OAuth flows work. @sourcegraph/cloud anybody familiar with auth?

**Comment by ryanslade** [comment]
@unknwon Any ideas?

**Comment by unknwon** [comment]
Thanks for tagging!

If I understand correctly, we don't redirect back to the last URL the user was trying to visit after 
 went over GitHub auth?

**Comment by quinnkeast** [comment]
> Thanks for tagging!
> 
> If I understand correctly, we don't redirect back to the last URL the user was trying to visit after
> went over GitHub auth?

Yes, this is what it sounded like to me.

**Comment by unknwon** [comment]
Put into cloud's next cycle for investigation.

**Comment by tsenart** [comment]
@unknwon: @flying-robot thinks this could be a good discovery task for on-boarding A. R. S., so I'm putting this in his on-boarding plan.
