### ISSUE TITLE
Better search expression alerts

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#15142]
A query like:

```
(repo:^github\.com/sgtest/sourcegraph-typescript$ yarn-deduplicate or repo:^github\.com/sgtest/go-diff$) package diff provides
```

cannot be evaluated right now because the inner group contains `(repo:foo a-pattern or repo:b) different-pattern` which expands to:
`(repo:foo (concat a-pattern different-pattern)) or (repo:bo different-pattern)`, and the concat isn't evaluated after expansion. The issue is that this query alert isn't helpful, and should be more helpful:

> I'm having trouble understanding that query. The combination of parentheses is the problem. Try using the content: filter to quote patterns that contain parentheses

**Comment by camdencheek** [comment]
Closing since I believe this will no longer be relevant now that we default to AND-separating patterns
