### ISSUE TITLE
Add translation layer for optimizing backend search engine work

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#15145]
We parse and evaluate a query like `foo and not foobar` using a general `and` intersection operation that works across all search engines (Zoekt, unindexed text search, structural search). This can be slow when searching over "everything" because it collects two result sets. For example, the query `foo and not foobar` 502s for me on Sourcegraph.com

Zoekt, being one of our search backends, has a native notion of `and` and `not` that will likely compute much faster than the general operation, because it will build one result set as it evaluates. All we need to do to gain Zoekt's native speed for "not" queries is:

- add a translation layer from our search query to a zoekt query (easy)
- detect when we _can_ translate our search query to a zoekt query (a bit of extra logic). This means, e.g., making sure that we use the translated zoekt query on an indexed search path for valid text searches
 - case out and collect results when we are good to evaluate with Zoekt

CC @stefanhengl who had the intuition/inclination to look into this. 

In general, this idea applies to any backend search engine: where something can use a representation of our input query (or subpart of it) directly and optimize evaluation, we should add a translation for it.

Relates to #636

**Comment by rvantonder** [comment]
Reasons for doing: [this query is slow](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/llvm/llvm-project%24+namespace+cfg+and+dump&patternType=regexp), and the reported time is not accurate (need to aggregate time for subexpressions).

**Comment by rvantonder** [comment]
Another example where this could matter:

A search like:

[`repo:^github\.com/sourcegraph/sourcegraph$ file:client/shared/src/api/protocol/contribution\.ts ((Search case:yes) or (Filter case:no))`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24%C2%A0file:client/shared/src/api/protocol/contribution%5C.ts%C2%A0%28%28Search+case:yes%29+or+%28Filter+case:no%29%29&patternType=literal)

will highlight both the `Search` and `Filter` parts in the line:

`export interface SearchFilters`

but, if we take out the `file:` filter, then the first `Search case:yes` could shortcircuit, and will highlight only the `Search` in `SearchFilters`, even though the `or` operator would also highlight `Filter` if we did an exhaustive search. [Example](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24%C2%A0%28%28Search+case:yes%29+or+%28Filter+case:no%29%29&patternType=literal).

As expected, if we add something like count:10000 (exhaustive), then everything is highlighted. [Example, scroll down](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24%C2%A0%28%28Search+case:yes%29+or+%28Filter+case:no%29%29+count:10000&patternType=literal).

Short circuit behavior is a nice property if we want results fast, but not if we want all the possible hits to be highlighted. There are a couple of directions here: re-search matching files that were short circuited to get complete highlighting (more work, kind of undermines shortcircuiting), or make it more obvious that exhaustive/`count` could pick up all highlightable line matches.

If, however, we translate the above to a Zoekt query, Zoekt probably takes care of merging at the file level, and not at the search query level for search expressions. Basically, it could figure out some of this for us, but not in all cases (e.g., if we mix in different pattern types).

**Comment by rvantonder** [comment]
Related to #9824.

**Comment by rvantonder** [comment]
Refactor things in line with comment: https://github.com/sourcegraph/sourcegraph/pull/18017#discussion_r571183337

> Nice. I feel like this is exactly the sort of conditional check that we should replace with a type to case out on. I.e.,we have a query of type T at this point, and when we check here, we test if it is a ZoektQuery and then run this logic. At some point prior to doResults, we would use the values of isGlobalSearch(), isIndexedSearch, isFileOrPath values to translate to a ZoektQuery type. Barring version contexts, all of the values of isGlobalSearch()/isIndexedSearch/isFileOrPath can be statically determined from the initial query. Which means we shouldn't (have to) do any query translation here in search_results.go, but rather right after parsing a query, in internal/search/query :-)

> Just sketching out some of this while I'm looking. I'll start moving on this this once I've landed all the query parsing changes.

**Comment by camdencheek** [comment]
@rvantonder Can this be closed now that we do send optimized and/or/not queries to Zoekt?

**Comment by rvantonder** [comment]
yeah
