### ISSUE TITLE
Explicitly annotated variable type degrades to Observable<any>

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#15150]
![image](https://user-images.githubusercontent.com/10532611/97561597-b7aeff80-19e0-11eb-8241-8445127b9610.png)

VS Code:

![image](https://user-images.githubusercontent.com/10532611/97561943-3146ed80-19e1-11eb-8e1f-24825832760a.png)

https://github.com/sourcegraph/sourcegraph/pull/15131/files#diff-d0f2ec764d1c50118c2c5465271cb246c8d06830456e42eab5db0936476cf089L293

**Comment by felixfbecker** [comment]
@efritz

**Comment by macraig** [comment]
@efritz should this be moved to `lsif-node`?

**Comment by efritz** [comment]
That'd be fine.

**Comment by macraig** [comment]
Moved to [#144](https://github.com/sourcegraph/lsif-node/issues/144) track against `lsif-node` repo when polishing indexer into production state.
