### ISSUE TITLE
qa: extensions test fails in CI

### ISSUE THREAD

**Issue by davejrt** [sourcegraph/sourcegraph#15168]
When running `yarn test:regression:extensions` in CI, the test fails with the following error:

```
    sourcegraph-qa-test:   2 passing (30s)
    sourcegraph-qa-test:   1 failing
    sourcegraph-qa-test:   1) Sourcegraph extensions regression test suite
    sourcegraph-qa-test:        Codecov extension:
    sourcegraph-qa-test:      Error: expect(received).toHaveLength(expected)
    sourcegraph-qa-test:
    sourcegraph-qa-test: Expected length: 264
    sourcegraph-qa-test: Received length: 0
    sourcegraph-qa-test: Received array:  []
    sourcegraph-qa-test:       at /sourcegraph/client/web/src/regression/extensions.test.ts:77:93
    sourcegraph-qa-test:       at processTicksAndRejections (internal/process/task_queues.js:93:5)
    sourcegraph-qa-test:       at RetryOperation._fn (/sourcegraph/node_modules/p-retry/index.js:41:12)
    sourcegraph-qa-test:

```

Full run with artifacts here:
https://buildkite.com/sourcegraph/qa/builds/92#4e123c29-eb1e-4626-a210-b56e028d2545

**Comment by felixfbecker** [comment]
Am I crazy? This comment says "Wait for Codecov button to appear and click it". But where does it do that? How is this test supposed to work?

https://github.com/sourcegraph/sourcegraph/blob/aaa6fea13a7817beda81aa6ce63ee5d6850a0478/client/web/src/regression/extensions.test.ts#L114-L125

**Comment by felixfbecker** [comment]
The click was removed in 964d97bd4d5817949a5cf596e415c454525313fb

**Comment by felixfbecker** [comment]
Note from the PR https://github.com/sourcegraph/sourcegraph/pull/12439:

> extensions code cov test doesn't find the codecov button to hit, once you hit manually the test continues.

So... is it _expected_ that this test fails and you need to click the button manually? Which obviously doesn't work in CI

**Comment by davejrt** [comment]
@uwedeportivo do you recall how this worked when you tested it locally?

**Comment by davejrt** [comment]
Uwe was running these manually for each release so whatever manual steps existed then were valid. If this test is still valid, and needs to find an element on the page we just need to target that....or find another way to test this functionality.
