### ISSUE TITLE
upgrade devmanaged.sourcegraph.com to v3.20, v3.21, v3.22

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#15173]
devmanaged.sourcegraph.com (the development managed instance) is on 3.19.2, so two upgrades are needed (3.20, 3.21).

**Comment by bobheadxi** [comment]
Side task: reminder to self to check alerts name on all the instances

**Comment by bobheadxi** [comment]
alert user name for devmanaged: 
![image](https://user-images.githubusercontent.com/23356519/100375553-f15b4080-3048-11eb-8a9c-d925a9d1f45a.png)

**Comment by bobheadxi** [comment]
did all 3, see attached PRs:

* https://github.com/sourcegraph/deploy-sourcegraph-managed/pull/14
* https://github.com/sourcegraph/deploy-sourcegraph-managed/pull/15
* https://github.com/sourcegraph/deploy-sourcegraph-managed/pull/16
