### ISSUE TITLE
create upgrade schedule

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#15174]
Historically done by me, create a schedule for shipping pure-docker to customers and upgrades of managed instances.

**Comment by bobheadxi** [comment]
Could the release tool create issues with dates for these? e.g. at open an issue with a checklist of which instances to upgrade at RELEASE + X days

**Comment by slimsag** [comment]
@bobheadxi that sounds really great! I won't have bandwidth to get to that anytime soon, so I plan to go for a low-effort calendar reminder which just acts as a date for a human on the distribution team to create a GitHub issue for these.

**Comment by slimsag** [comment]
I think the concrete list is:

Create issue on release day 20th + 3 days of buffer space (in case of e.g. bad / faulty release) describing to:

>
> - [ ] (Robert, Dax) [Upgrade internal managed instances](https://about.sourcegraph.com/handbook/engineering/distribution/managed/upgrade_process) first
> - [ ] (Robert, Dax) [Upgrade customer managed instances](https://about.sourcegraph.com/handbook/engineering/distribution/managed/upgrade_process)
> - [ ] (Uwe, Dave) [Release pure-docker](https://github.com/sourcegraph/deploy-sourcegraph-docker/blob/master/RELEASING.md#releasing-pure-docker) and inform https://app.hubspot.com/contacts/2762526/company/407948923/
>
> The above should be completed sometime within the following ~3 weeks.

**Comment by pecigonzalo** [comment]
If its possible, lets `@sourcegraph/distribution` on the body as well, as I know we cant assign issues to individual, but the task themselves should not need to be performed by a fixed set of engineers. I would also add this to the Distribution calendar.

**Comment by slimsag** [comment]
I do think automating this is a good idea, but as mentioned earlier I have gone for the lower-bandwidth option and created a calendar reminder which indicates to file these issues manually:

<img width="464" alt="image" src="https://user-images.githubusercontent.com/3173176/98165297-df9bd880-1ea2-11eb-93ab-e68f8ddac5b3.png">

I have given all guests the ability to edit, and started it 3 days after the 20th repeating every 4 weeks on Mon - so it should always coincide with "a few days after the release, on Monday"
