### ISSUE TITLE
qa: onboarding tests require manual validation

### ISSUE THREAD

**Issue by davejrt** [sourcegraph/sourcegraph#15179]
The onboarding QA tests reqiuire manual validation, which is not conducive to them running in CI. We should write automated tests, or remove them if they're no longer valid. 

Log here:
https://buildkite.com/sourcegraph/regression/builds/94#9a7dc591-1d77-4fc3-9dff-d1fda9df7a14/64-2589

**Comment by Joelkw** [comment]
@jeanduplessis we can discuss prioritizing it in an iteration planning wherever you see fit for this one, if it looks like something we can solve.

**Comment by davejrt** [comment]
The manual part of these steps has been removed, so they now pass however are not verified. @Joelkw I'm going to remove the distribution team assignment from this as it's now in web triage. Feel free to close this and open a new ticket that reflects better what the web team wants to do here with these particular tests.
