### ISSUE TITLE
Revoking Sourcegraph authorization from a code-host should log the user out of Sourcegraph

### ISSUE THREAD

**Issue by christinaforney** [sourcegraph/sourcegraph#15176]
If a user's last login to Sourcegraph was via code host OAuth and their access is revoked, we should log them out.

**Comment by christinaforney** [comment]
Link to subfeature: https://sourcegraph.productboard.com/feature-board/planning/features/5982134

**Comment by ryanslade** [comment]
I'm wondering how this would work if they are connected with more than one code host?

We also need to investigate how we can be notified of this or is it something we occasionally poll their API for?

**Comment by chayim** [comment]
Can we track how the user last logged in? For instance if they're logged in via GitHub, and they revoke GitHub authorization, the user would then log out.

**Comment by ryanslade** [comment]
SGTM

**Comment by ryanslade** [comment]
I've looked into this a bit and it doesn't appear there is a clear way to react to someone revoking their token. 

Also, tokens received from GitHub never expire, they can only be revoked.

I think our only option is to poll the codehost occasionally and check whether their token is still valid. The question is, how frequently is acceptable here? Too often and we potentially start running into rate limit issues. Not often enough and we leave access open to the user after their token has been revoked. @chayim, what would be an acceptable time here?

**Comment by chayim** [comment]
There are two possibilities that are fair to me:

1. Calling real-time within 5 minutes. If that avoids rate-limiting, I
think it's completely reasonable.

2. Notifying the user when they link their code host that we may require up
to 30 minutes (again, purely to avoid rate limiting) to synchronize these
items.

Assuming we communicate these things to the user up front, I don't see this
as an issue. However, I have a clear preference for #1.

**Comment by unknwon** [comment]
I now feel like there is some overlap in this issue and https://github.com/sourcegraph/sourcegraph/issues/14899, where the latter tends to periodically scan through the entire `user_external_accounts` table with a "whoami" API request to test if the OAuth token is still valid (what I planned to do).

**Comment by unknwon** [comment]
@christinaforney, @chayim:

During my 1:1 with @tsenart, we were wondering what is the intention of "log the user out of Sourcegraph". Because revoking Sourcegraph application on GitHub.com means revoking the OAuth token, and "sign-in via GitHub.com" just happens to be the way of obtaining the OAuth token.

Now, what really means for a user to revoke OAuth token. Is it to remove repositories been added to Sourcegraph Cloud? If so, why can't the user just go to Sourcegraph.com and remove the external service?

Also from user experience, I haven't seen any SaaS service does this for me, but some of them do have short-lived user sessions (few days) which would often asks me to perform sign-in again (and by that time, the service wouldn't need to know/care if the OAuth has been revoked because I need to authorize again anyway).

**Comment by ryanslade** [comment]
As we don't have clarity on this yet and probably won't work on it next cycle I'm moving it to the backlog

**Comment by chayim** [comment]
> During my 1:1 with @tsenart, we were wondering what is the intention of "log the user out of Sourcegraph". Because revoking Sourcegraph application on GitHub.com means revoking the OAuth token, and "sign-in via GitHub.com" just happens to be the way of obtaining the OAuth token.

It would be nice (ideal) if users remembers what their tokens were for, but not everyone remembers what was authorized. As GitHub is the arbiter of permissions, I think we should remove repositories that are in Sourcegraph if the token is revoked. @christinaforney WDYT?

**Comment by ryanslade** [comment]
We'll be removing repos for code hosts connection that have revoked tokens here: https://github.com/sourcegraph/sourcegraph/issues/15739

Logging the user out when a token is revoked is not a common flow so we don't plan on implementing this. We'll rely on the session timeout.
