### ISSUE TITLE
User authentication and authorization flow to connect code

### ISSUE THREAD

**Issue by christinaforney** [sourcegraph/sourcegraph#15175]
description goes here

**Comment by christinaforney** [comment]
Link to feature: https://sourcegraph.productboard.com/feature-board/planning/features/5981900

**Comment by ryanslade** [comment]
More details please :)

**Comment by tsenart** [comment]
@quinnkeast: What does this refer to in Productboard? Is it redundant with other tasks?

**Comment by quinnkeast** [comment]
I'm not sure actually – @christinaforney can you help?
