### ISSUE TITLE
Go to definition doesn't work on same-repo TypeScript import

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#15185]
Jump to definition doesn't work in many cases, e.g.

![image](https://user-images.githubusercontent.com/10532611/97679443-8e03e000-1a95-11eb-95c3-247bf99d149a.png)

https://sourcegraph.com/github.com/sourcegraph/sourcegraph@2f5873684d268d60d2d4c46e0961918a526262a2/-/blob/client/browser/src/shared/platform/settings.ts#L16:10

This could be related to the destination being under a different TypeScript project (tsconfig.json), we use project references.

**Comment by beyang** [comment]
Encountered this today. Also, `Find references` seems to return nonsense results:

[![image](https://user-images.githubusercontent.com/1646931/105202866-479fa980-5af7-11eb-8355-5d91347fdbb0.png)](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@410bbd207914dde9eb7ed0b4361623b11eef33d5/-/blob/client/web/src/repo/blob/Blob.tsx#L11:10&tab=references)

**Comment by macraig** [comment]
Moving to https://github.com/sourcegraph/lsif-node/issues/148

**Comment by deepseawhale** [comment]
> 

Hi there, may I know if "nonsense results" when doing get references still there in lsif-node? Thanks

**Comment by macraig** [comment]
Hi @deepseawhale, I've responded in https://github.com/sourcegraph/lsif-node/issues/148
