### ISSUE TITLE
Send new users (added by site admin) the password reset URL over email

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1519]
As a site admin, I want new users (added by me in the site admin area) to receive an email with a URL they visit to create a password, instead of me (the site admin) getting the URL to copy-paste to them. This would make it faster to add many users (because I wouldn't need to open a private chat with each user and paste them a link). It would also reduce the likelihood of me making a mistake and sending a URL to the wrong user.  (This would only occur if the site config `email.smtp` property is set. If not, copy-pasting the URL is OK.)

This is low priority because site admins who need to add many users should use an external auth provider (SSO), or they can use the GraphQL API if SSO is not an option.

Requested by @P3GLEG

**Comment by beyang** [comment]
@christinaforney @sourcegraph/web We should add "setting up SMTP" and "sending out email invites to additional users" to the site admin onboarding experience.

**Comment by christinaforney** [comment]
Adding to team sync notes to discuss.

**Comment by ElizabethStirling** [comment]
If a user is created and the password reset email is sent, do we still want to display the reset link for the site admin?

**Comment by ElizabethStirling** [comment]
> instead of me (the site admin) getting the URL to copy-paste to them.

Assuming this means we want to explicitly not display the result if the user has been emailed, but will wait for comment

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
