### ISSUE TITLE
go binary to create sudo token should be more generic

### ISSUE THREAD

**Issue by davejrt** [sourcegraph/sourcegraph#15197]
The go code I wrote to create the sudo token, which was forked from Joe's previous work should be more generic to be used in other project without hard coding paths or URL's as it currently the case. 

This uses the graphql api

Code [here](https://github.com/sourcegraph/sourcegraph/blob/main/test/qa/main.go)

forked from Joe's code [here](https://github.com/sourcegraph/sourcegraph/tree/cfdb8d8b38664418ca3815c6cad65a905fe83e57/dev/gqltest)

**Comment by bobheadxi** [comment]
FYI https://github.com/sourcegraph/sourcegraph/pull/14974 made this a shared tool amongst the QA tests (`init-server.go`)

**Comment by davejrt** [comment]
The tool has been moved to https://github.com/sourcegraph/sourcegraph/tree/main/internal/cmd/init-sg

You can now load your external svc configs with a json file, as seen [here](https://github.com/sourcegraph/sourcegraph/blob/main/dev/ci/test/code-intel/repos.json)
