### ISSUE TITLE
Syntax highlighting on NixOS config files

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#152]
#### Describe the feature request.

Request from a user who filled out a survey:

>The file I was just looking at was a NixOS configuration file (/etc/nixos/configuration.nix), and it didn't have any syntax highlighting, so perhaps that? <3

(looks like this is available, e.g. https://github.com/NixOS/nixpkgs/blob/master/nixos/default.nix)

**Comment by lf-** [comment]
Hi! I am not the original requester, but I also want this.
