### ISSUE TITLE
Make it clear to Enterprise trial license key holders that the single-Docker container deploy is OK

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1520]
From a user (paraphrased):

> As a user who received an Enterprise trial license key, I want it to be clear that it is OK for me to use the single-Docker container deployment scheme with Enterprise. When I got an Enterprise trial license, it took me straight to the Kubernetes installation, so I assumed I needed to deploy to a Kubernetes cluster to use Enterprise.

**Comment by sqs** [comment]
@KattMingMing 	Can you check the emails and other links you are sending to see how to avoid this confusion? Reported by @P3GLEG.

**Comment by KattMingMing** [comment]
This has been resolved. The confusion happened after submitting a trial request the confirmation page only displayed a link to cluster deployment. That page was updated to include both deployment options.
