### ISSUE TITLE
index.docker.io/sourcegraph/codeintel-db has no tag in deploy-sourcegraph-* releases

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#15206]
https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/deploy-sourcegraph%28.*%29+rev:3.21+index.docker.io/sourcegraph/codeintel-db&patternType=literal

**Comment by bobheadxi** [comment]
cc @sourcegraph/code-intel

**Comment by efritz** [comment]
Will add an insiders tag.
