### ISSUE TITLE
Help k8s installers avoid/detect underprovisioned clusters

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1521]
As someone deploying Sourcegraph to a Kubernetes cluster using https://github.com/sourcegraph/deploy-sourcegraph, I want the documentation to help me avoid the problem of underprovisioning my k8s cluster. This leads to a confusing state; in this case, I saw that the redis-store pod was "Pending" and not being scheduled. I want the troubleshooting steps to include this problem, and I want the docs written in such a way that I know how many nodes and how much CPU/memory to provision so that I don't encounter this issue.

Note: We recommend that everyone starts with the single-Docker-container deployment at https://docs.sourcegraph.com/#quickstart and only deploy to a Kubernetes cluster when the single-container deployment no longer scales to their usage patterns (number of users, frequency of usage, amount of code, API access patterns, etc.).

Requested by @P3GLEG

**Comment by christinaforney** [comment]
Some additional information has been added here: https://github.com/sourcegraph/deploy-sourcegraph/blob/master/docs/k8s.md

Updated gap in the docs: https://github.com/sourcegraph/deploy-sourcegraph/pull/246

**Comment by slimsag** [comment]
This was fixed for node underprovisioned in the docs update above, and Sourcegraph now alerts you to over/under-provisioning both in a site banner and in grafana thanks to work by @bobheadxi 🎉
