### ISSUE TITLE
Validate repository names and allow deleting repositories with invalid names

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1522]
As a site admin, I want to be able to delete repositories with invalid repository names that were inadvertently added. For example, if a repository name has a trailing slash (`foo/bar/`), it is not possible to delete it. This is because you need to navigate to a repository's settings page to delete it `https://sourcegraph.example.com/foo/bar/`, but the trailing slash will be elided by the URL router used by Sourcegraph and you will be redirected to `https://sourcegraph.example.com/foo/bar` (note lack of trailing slash).

- [ ] Define the set of allowable repository names and document this in `doc/` (rough attempt: a repository name is a series of one or more `/`-joined path components with no leading or trailing `/`, with each path component containing characters in `[some-chars]`.
- [ ] Disallow creation of repositories with invalid repository names (per the definition above)
- [ ] On the site admin repositories page, add a gear-icon dropdown menu to each repository row with a single item "Delete repository". When clicked, it shows the same confirmation prompt as the one shown when a site admin deletes a repository from its repository settings page. (This action is nested in the gear dropdown menu because that helps communicate that it is a rarely used action and helps avoid confusion between the concept of enable/disable and delete for repositories.)

Requested by @P3GLEG

**Comment by tsenart** [comment]
Closing since it doesn't seem relevant anymore.
