### ISSUE TITLE
Export search results to CSV

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1525]
As an engineer who needs to take/assign specific actions for lines matching a particular pattern, I want to be able to export search results to CSV from the search results page. I would then open this CSV in a spreadsheet application and work down the list, checking off rows as I handle them. I can't do this on Sourcegraph because the search results page is not persistent; the results might change and/or be reordered if I perform the search again, and this would make it hard to know I've addressed everything at a point in time.

I prefer "Export to CSV" over other solutions:
- Using the GraphQL API is not a good solution because I always perform this workflow on the web app and don't want to need to write a script and switch to it to get the CSV.
- Using the `src` CLI is not a good solution for the same reasons as above.

Requested by

- @P3GLEG (who said he might look into building this himself as a Sourcegraph extension or as a script)
- https://app.hubspot.com/contacts/2762526/company/557475593 (https://sourcegraph.slack.com/archives/C0C324C91/p1571777058036700)

**Comment by felixfbecker** [comment]
If anyone needs this right now, this is trivial to do with PSSourcegraph:
```powershell
Search-Sourcegraph 'r:sourcegraph/sourcegraph HoverOverlay type:file' |
  Select-Object -Property RepositoryName,FilePath,LineNumber |
  ConvertTo-Csv
```

**Comment by christinaforney** [comment]
We are working on a feature to let you pin locations in code, this may make this issue irrelevant, but we will keep this open until @P3GLEG has a chance to weigh in. We will reach out to schedule a call with you soon!

**Comment by lguychard** [comment]
We have a [search export](https://sourcegraph.com/extensions/sourcegraph/search-export) extension. In the future, we may support this and other transformations natively (cc @rvantonder)

**Comment by limitedmage** [comment]
This is implemented natively into the product now.
