### ISSUE TITLE
RFC 266: Production testing of all authorization models

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#15273]
https://docs.google.com/document/d/1BO5RNnSrNWybUt79e7wmt2KKqCweV9G4kM8-UkdvK08/edit#

### Next steps

- [ ] Make an implementation plan and create GitHub project to track task items
- [ ] Split work with @indradhanush 
- [ ] Deploy to Buildkite

**Comment by unknwon** [comment]
Moved to the next cycle with reduced estimate.

**Comment by unknwon** [comment]
RFC approved

**Comment by indradhanush** [comment]
Github project created here: https://github.com/orgs/sourcegraph/projects/164

**Comment by unknwon** [comment]
We have created issues to split the work, and this one can be closed.
