### ISSUE TITLE
All accounts always have a confirmed primary email address

### ISSUE THREAD

**Issue by christinaforney** [sourcegraph/sourcegraph#15274]

**Comment by christinaforney** [comment]
Link to subfeature: https://sourcegraph.productboard.com/feature-board/planning/features/5982138

**Comment by ryanslade** [comment]
@christinaforney How do we want to enforce this? What should the UX be for a user who hasn't verified yet?

**Comment by chayim** [comment]
Steps to reproduce:

1. Create a Sourcgraph account
2. Add a second email address (but not verify)
3. Delete the primary email address
4. Go through the forgot password flow, with the second e-mail address.

The user should not be unable to delete their primary e-mail address if the secondary address has not been verified.

**Comment by ryanslade** [comment]
FYI, about 20% of our users on sourcegraph.com haven't verified their email address

**Comment by ryanslade** [comment]
Depends on: https://github.com/sourcegraph/sourcegraph/issues/15393

**Comment by ryanslade** [comment]
This is solved by https://github.com/sourcegraph/sourcegraph/pull/15683 as you can't delete your primary email address
