### ISSUE TITLE
Make it easier to add repositories that exist on my disk

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1527]
As a site admin who *X* (see below for the multiple values of *X*), I want to be able to quickly and easily add repositories that I have on disk. The current way of adding repositories from disk (https://docs.sourcegraph.com/admin/repo/add_from_local_disk#add-repositories-already-cloned-to-disk) is too cumbersome because:

- It requires complex-sounding Git features that I distrust
- It requires me to substitute and map paths in multiple places, which is complex and error prone
- It does not automatically add/remove repositories to Sourcegraph when I add/remove repositories from disk (i.e., it also requires me to add it to `repos.list`)
-  I am not confident that Sourcegraph will fetch changes from a repository after it is updated on disk

The values of *X* (i.e., the use cases for which this need arises):
- I just want to try Sourcegraph with a single repository and don't want the (perceived) hassle of connecting it to my code host and/or of working with multiple repositories.
- I don't trust Sourcegraph enough to give it access to my code host, but I do trust it enough to give it access to a single repository.
- The repositories do not exist on any code host or at any remote Git URL. (I.e., they are static dumps of repositories.)

We have had a few issues/requests related to this:

- #226: direct user request for this
- #151: confusion caused by this process being tricky
- @P3GLEG: requested this to be easier (he said it's not a high priority, but it still caused friction) https://app.hubspot.com/contacts/2762526/company/550460939 

Priority is low (please add a comment in this thread if you want us to reconsider this priority). Historically we haven't prioritized this feature because we want users to connect their code host, which lets them use Sourcegraph across all of their repositories and see more value. If there are reasons why users aren't comfortable connecting their code host, we've tried to address those directly instead of adding this workaround.

**Comment by mrtnlrsn** [comment]
For me X='The repositories do not exist on any code host or at any remote Git URL. '

They exist on a local server. On the server I have tried to make a single copy of all my files and add to a git repo. This repo is imported into the docker instance, where it is mounted in `/src/SRC/.git`

Inside docker I can do `git clone /src/SRC`.


From https://docs.sourcegraph.com/@v3.2.0/admin/repo/add_from_local_disk I get the understanding I should be able to add this as an external service somehow, but I don't get the details.

I tried to add a single git repository with the following config:
```
  "url": "git:///src/",
  "repos": [ "SRC" ]
```

Output from sourcegraph is
08:01:45          gitserver | t=2019-03-21T08:01:45+0000 lvl=warn msg="error cloning repo" repo=/src/SRC err="error cloning repo: repo /src/SRC (git:///src/SRC) not cloneable: exit status 128 (output follows)\n\nfatal: unable to look up  (port 9418) (Name does not resolve)\n"

**Comment by neerajbadlani** [comment]
+1 . I am trying to setup sourcegraph to code search from repo already cloned to local disk , but its not working and instructions are difficult to follow . Please help . 

my repo is on my local laptop : /Users/nebadlan/.sourcegraph/data/repos/github/libuv.git . 
and docker instance is also running locally . 
None of the configs in setting up external service seems to work . 
Any idea ?

**Comment by P3GLEG** [comment]
I was able to do this with a kinda hacky way. I have a single docker repo, so not sure how to do it for a cluster deployment. 
```
sudo mkdir -p ~/.sourcegraph/data/repos/myhostname/myorgname/
sudo mv ~/mylocalrepo/.git ~/.sourcegraph/data/repos/myhostname/myorgname/mylocalrepo/
```

Now go to the external configuration service and add a single git repo do

```
{
  "url": "https://myhostname", // this doesn't matter
  "repos": [
    "myorgname/mylocalrepo",
  ]
}
```

My team really needs a better feature to do this. We don't always have access to source code hosts but we get source code.

**Comment by sqs** [comment]
@P3GLEG Thank you for posting this workaround and bringing this up. We will post back here soon with how we are prioritizing this.

**Comment by aesyondu** [comment]
> I was able to do this with a kinda hacky way. I have a single docker repo, so not sure how to do it for a cluster deployment.
> 
> ```
> sudo mkdir -p ~/.sourcegraph/data/repos/myhostname/myorgname/
> sudo mv ~/mylocalrepo/.git ~/.sourcegraph/data/repos/myhostname/myorgname/mylocalrepo/
> ```
> 
> Now go to the external configuration service and add a single git repo do
> 
> ```
> {
>   "url": "https://myhostname", 
>   "repos": [
>     "myorgname/mylocalrepo",
>   ]
> }
> ```
> 
> My team really needs a better feature to do this. We don't always have access to source code hosts but we get source code.

Hi, I tried to do this but I'm getting an error message in the `docker run` foreground process:
```shell
02:10:06                         gitserver | t=2020-04-22T02:10:06+0000 lvl=warn msg="error cloning repo" repo=myhostname/myname/myrepo err="error cloning repo: repo myhostname/myname/myrepo not cloneable: exit status 128 (output follows)\n\nfatal: unable to access '<redacted>/': Could not resolve host: myhostname\n"
```

It seems it tries to look for a server `myhostname`, but I don't have one since the git repo is only saved on disk.

**Comment by tsenart** [comment]
@keegancsmith: Any clue what's going on above?

**Comment by keegancsmith** [comment]
That comment is out of date. The git repo has to be bare and it must exist at a `~/.sourcegraph/data/repos/myhostname/myorgname/mylocalrepo/.git`. Note the instructions above put it at `~/.sourcegraph/data/repos/myhostname/myorgname/mylocalrepo`.

Additionally the documentation was recently updated (although this issue still stands about it not being straightforward). So please also read https://docs.sourcegraph.com/admin/repo/add_from_local_disk#add-repositories-already-cloned-to-disk

**Comment by mastercoms** [comment]
The repo I created using the steps in the docs keeps getting deleted from data.

**Comment by mastercoms** [comment]
Due to #8453, the local repository could be removed from disk, and then fail to reclone, which requires manual intervention.

**Comment by hitzhangjie** [comment]
> I was able to do this with a kinda hacky way. I have a single docker repo, so not sure how to do it for a cluster deployment.
> 
> ```
> sudo mkdir -p ~/.sourcegraph/data/repos/myhostname/myorgname/
> sudo mv ~/mylocalrepo/.git ~/.sourcegraph/data/repos/myhostname/myorgname/mylocalrepo/
> ```
> 
> Now go to the external configuration service and add a single git repo do
> 
> ```
> {
>   "url": "https://myhostname", 
>   "repos": [
>     "myorgname/mylocalrepo",
>   ]
> }
> ```
> 
> My team really needs a better feature to do this. We don't always have access to source code hosts but we get source code.

Thanks. I use this method to search my team's source code.
