### ISSUE TITLE
release(patch): investigate better process for tracking commits that must go in a patch

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#15294]
3.21.x seems to have had some difficulty tracking patches that had to go in a release

Related: https://github.com/sourcegraph/sourcegraph/issues/15293

**Comment by davejrt** [comment]
My comments are the patch release were: different teams were typically contacting me via different means...some via slack private, or in a thread in #web or #distribution. 

Combined with the lack of testing meant PR's were being merged or cherry-picked but not necessarily being tested before that and then I had to chase up dev's to get things fixed. 

I think there needs to be one way of getting a PR into a release, and everyone adhering to that. Making sure it's really obvious, and harder to miss or forget. This might be a new tracking issue with a list of the PR's to tick off tagged with the patch release number, which should be on the developers to own tagging and documenting.

**Comment by bobheadxi** [comment]
> This might be a new tracking issue with a list of the PR's to tick off tagged with the patch release number, which should be on the developers to own tagging and documenting.

IIRC the patch tracking issue has a template section where people should edit the issue as a requirement for getting their change into the patch, example: https://github.com/sourcegraph/sourcegraph/issues/13992 - is still insufficient? we can make it a bit more emphasized in the release tooling (more aggressive slack messaging, timelines / cutoffs?)

that said, I can't find the patch trackers for the 3.21 patches ([query](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+patch+release+is%3Aclosed)), were any created?

**Comment by bobheadxi** [comment]
@davejrt https://github.com/sourcegraph/sourcegraph/pull/15548 and https://github.com/sourcegraph/about/pull/1881 includes wording changes to try and make the patch checklist more prominent - do you think that's sufficient to resolve this?
