### ISSUE TITLE
Support front matter in markdown files on Sourcegraph.

### ISSUE THREAD

**Issue by francisschmaltz** [sourcegraph/sourcegraph#153]
#### Describe the feature request.
Support front matter on markdown files.

#### Is your feature request related to a problem? Please describe.
Front matter displays poorly on markdown files.

#### Additional context
We will use front matter in our repositories and we should display it correctly in Sourcegraph.
![screen shot 2018-09-27 at 2 58 24 pm](https://user-images.githubusercontent.com/11583013/46176908-c9ec6b80-c265-11e8-8df7-ffbd82d22f46.png)

**Comment by slimsag** [comment]
I may look into fixing this. We can reuse the parser that Hugo uses: https://github.com/gogs/gogs/pull/4643
