### ISSUE TITLE
Potential nil panic in hard_delete.go

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#15302]
Seeing a nil panic in my dev env when things restart. Probably something that is dodged in prod but @efritz you may want to look into it?

> 22:52:54             frontend | runtime/debug.Stack(0xc00082db38, 0x59c2960, 0x78fc3a0)
22:52:54             frontend | 	/usr/local/Cellar/go/1.14.3/libexec/src/runtime/debug/stack.go:24 +0x9d
22:52:54             frontend | github.com/sourcegraph/sourcegraph/internal/goroutine.Go.func1.1()
22:52:54             frontend | 	/Users/rvt/sourcegraph/internal/goroutine/goroutine.go:19 +0x57
22:52:54             frontend | panic(0x59c2960, 0x78fc3a0)
22:52:54             frontend | 	/usr/local/Cellar/go/1.14.3/libexec/src/runtime/panic.go:969 +0x166
22:52:54             frontend | github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/codeintel/background.(*HardDeleter).deleteBatch(0xc00195eaa0, 0x64d7b20, 0xc001962b40, 0x7958998, 0x0, 0x0, 0x0, 0x0)
22:52:54             frontend | 	/Users/rvt/sourcegraph/enterprise/cmd/frontend/internal/codeintel/background/hard_delete.go:86 +0xe3
22:52:54             frontend | github.com/sourcegraph/sourcegraph/enterprise/cmd/frontend/internal/codeintel/background.(*HardDeleter).Handle(0xc00195eaa0, 0x64d7b20, 0xc001962b40, 0x0, 0x0)
22:52:54             frontend | 	/Users/rvt/sourcegraph/enterprise/cmd/frontend/internal/codeintel/background/hard_delete.go:58 +0x17a
22:52:54             frontend | github.com/sourcegraph/sourcegraph/internal/goroutine.(*PeriodicGoroutine).Start(0xc001a82690)
22:52:54             frontend | 	/Users/rvt/sourcegraph/internal/goroutine/periodic.go:95 +0x2c2
22:52:54             frontend | github.com/sourcegraph/sourcegraph/internal/goroutine.startAll.func1()
22:52:54             frontend | 	/Users/rvt/sourcegraph/internal/goroutine/background.go:55 +0x56
22:52:54             frontend | github.com/sourcegraph/sourcegraph/internal/goroutine.Go.func1(0xc0003735c0)
22:52:54             frontend | 	/Users/rvt/sourcegraph/internal/goroutine/goroutine.go:24 +0x49
22:52:54             frontend | created by github.com/sourcegraph/sourcegraph/internal/goroutine.Go
22:52:54             frontend | 	/Users/rvt/sourcegraph/internal/goroutine/goroutine.go:16 +0x3f

This line, probably the `d` could be nil? https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/internal/codeintel/background/hard_delete.go#L58

**Comment by Strum355** [comment]
It appears that (*HardDeleter).lsifStore is never assigned, hence the nil pointer at L86 
https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/internal/codeintel/services.go#L27:2&tab=references
