### ISSUE TITLE
Spike: Prototype account merging between GitLab and GitHub

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#15332]
Check how easy it'll be to use OAuth signup with either GitHub or GitLab. If the user signs in with a second code host and an existing verified email address is matches then merge them.

This is a spike since we want to test the feasability while exploring the code host API's before committing to a "proper" solution that can handle more than the above two mentioned hosts.

**Comment by unknwon** [comment]
For some reasons, I think we already have this ability to associate accounts from different code hosts as long as the email returned by the code host is verified?

**Comment by ryanslade** [comment]
I know we already merge email based login and GitHub if there are matching verified email addresses but I haven't confirmed whether it works with the GitHub / GitLab combination yet.

**Comment by unknwon** [comment]
I have verified both in code and end-to-end that sign in with GitHub (e.g. GitHub.com) and GitLab (e.g. GitLab.com) will associate to the same user, as long as the user has one of the verified emails matches the code host primary email.

Setup:

1. I added two emails "github@example.com" and "gitlab@example.com" (redacted) and marked them as verified. Each email is the primary email of each code host respectively. 
1. Then I sign in with each code host account, both times I'm logged in as the same Sourcegraph user.

One minor problem:

We _always_ update **Display name** and **Avatar URL** with the _last_ sign in method. That means if I sign in with GitHub and GitLab in turn, my name and avatar also changes in turn 😂  cc @quinnkeast for a UX suggestion.

**Comment by quinnkeast** [comment]
>We always update Display name and Avatar URL with the last sign in method. That means if I sign in with GitHub and GitLab in turn, my name and avatar also changes in turn 😂 cc @quinnkeast for a UX suggestion.

Quick thoughts: once something "exists," it shouldn't change without deliberate action by the user. So, if the display name and avatar originally come from GitHub, the new name and avatar from GitLab should be ignored by default.

The display name and avatar should also be "owned" by Sourcegraph, not by the code host. We can originally fetch these from the code host (magically saving time for the user), but then future changes should be the user's responsibility on Sourcegraph itself. We can eventually update the user profile section to let people grab the current avatar from [code host], but it shouldn't change without their action.

So:

1. First-time code host connection – fetch display name and avatar from code host if they haven't already been set on Sourcegraph.
2. Future new code host connections or sign-ins – no action.

Wdyt?

**Comment by unknwon** [comment]
> So:
> 
> 1. First-time code host connection – fetch display name and avatar from code host if they haven't already been set on Sourcegraph.
> 2. Future new code host connections or sign-ins – no action.

@quinnkeast Sounds prefect! Filed: https://github.com/sourcegraph/sourcegraph/issues/17086
