### ISSUE TITLE
Browser ext doesn't work w/o "Enable on this domain", but this isn't obvious to users

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#1535]
After a long discussion with an Engineer at Codecov trying to debug why they couldn't see anything from Sourcegraph on GitLab, we finally discovered they hadn't yet "enabled" it on that domain (by default, it only works on github.com I believe).

Can we either:
1) make it work by default on gitlab.com and other major code hosts
2) add a badge/alert to the ext icon if it's not enabled (like how other browser extensions do this)

![image](https://user-images.githubusercontent.com/5589410/50304872-07682b80-0446-11e9-9a52-0e8f476c9c0b.png)

3) simply add a button for this in the actual extension menu?

@francisschmaltz you might have design ideas

**Comment by dadlerj** [comment]
"enable on this domain" is only visible when you right-click on the browser extension icon:

![image](https://user-images.githubusercontent.com/5589410/50304918-2c5c9e80-0446-11e9-9804-722feec33834.png)

**Comment by francisschmaltz** [comment]
@dadlerj @ijsnow There should be a button in the extension that allows to add the domain. zpl.io/blZNDrz

**Comment by ryan-blunden** [comment]
Re Dan's suggestion in https://github.com/sourcegraph/sourcegraph/issues/1535#issue-393171362, is it possible to add an indicator to the icon to show that Sourcegraph needs to be enabled for this domain?

![sg](https://user-images.githubusercontent.com/133014/51000642-91099700-14e2-11e9-938c-468e8bf9bb58.jpg)

**Comment by felixfbecker** [comment]
This is now mentioned in the options page. Is that sufficient?

![image](https://user-images.githubusercontent.com/10532611/55296709-927d9800-541d-11e9-9c2b-4aa3f02062e8.png)

**Comment by sqs** [comment]
This should suffice for now. We will reopen this issue if we hear more user feedback that it is not enough.
