### ISSUE TITLE
Design campaigns licensing flow and messaging 

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#15351]
* create copy for the messaging
* banner on the preview screen 

Update, basic Figma:
https://www.figma.com/file/rkxG6h3WzW0rzmPBE0CSbM/Licensing?node-id=0%3A1&viewport=-658%2C-185%2C0.5

**Comment by chrispine** [comment]
restrictions: Error on publish, only display 5 imported changesets in the UI (with explanation of why)

**Comment by chrispine** [comment]
alternate restriction idea: error in CLI if more than 5 changesets "reduce number of changesets or INSERT COINS"
