### ISSUE TITLE
Only a subset of GitLab repositories appearing in Sourcegraph

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#1537]
A user reported "setting it up with Gitlab or Gerrit repos has been torturous" — this is a tracking issue for these problems (will be updated as more information is available).

Potentially related: 
* https://github.com/sourcegraph/sourcegraph/pull/1103 (slated for 3.0)
* https://github.com/sourcegraph/sourcegraph/issues/1467

Reported by https://app.hubspot.com/contacts/2762526/company/981045254

**Comment by dadlerj** [comment]
The user reported that the curl command above successfully returned all of their repos (thousands), but that Sourcegraph still only displayed a subset of them (several hundred).

**Comment by beyang** [comment]
Prioritizing this for next week.

**Comment by beyang** [comment]
@dadlerj Can the customer provide the following pieces of information?
1. Run `curl --head -H 'PRIVATE-TOKEN: $ACCESS_TOKEN' -XGET https://$GITLAB_HOSTNAME/api/v4/projects`, replacing `$ACCESS_TOKEN` and `$GITLAB_HOSTNAME` with their values. Report the values printed for `X-Per-Page`, `X-Total`, and `X-Total-Pages`.
1. Report the total number of repositories in the Sourcegraph repo table: `docker exec $(docker ps --filter 'ancestor=sourcegraph/server:insiders' --format '{{.ID}}') psql -U postgres -d sourcegraph -c 'select count(*) from repo'`
1. How long did they let Sourcegraph run (minutes, hours, days, weeks?) when they initially examined the repositories and found some were missing?

**Comment by replicatesas** [comment]
1. 
x-per-page: 20
x-total: 17416
x-total-pages: 871
2. 419
3. days

**Comment by beyang** [comment]
@replicatesas do you have any logs you can share from the Sourcegraph instance (specifically looking for lines with `repo-updater`)?

**Comment by replicatesas** [comment]
Not from our current instance - when we fire up 3.0 will be sure to pass along logs with repo-updater (will need to re-configure our instance to use gitlab) thanks.

**Comment by beyang** [comment]
Great, thanks! There were a few fixes / changes to repo-updater in 3.0, so there's a chance that upgrading will resolve this issue.

**Comment by varaamo** [comment]
> Great, thanks! There were a few fixes / changes to repo-updater in 3.0, so there's a chance that upgrading will resolve this issue.

Do you know what version is this fixed in? I'm running 3.0 and seeing a slightly different kind of  issue. When using a PAT (Personal access token) associated with my gitlab account, i can see all the repos to which I have been granted permissions in SourceGraph 

But when I add the Gitlab external service to use the Sourcegraph “bot” user, which is just a normal user account with no explicit access to any GitLab repositories, Sourcegraph is not displaying them. Running curl command however is able to retrieve all the repos.

**Comment by sqs** [comment]
Marked @varaamo's issue in the comment directly above as resolved (they opened it at https://github.com/sourcegraph/sourcegraph/issues/2164#issuecomment-460676618 and it was addressed there).

**Comment by keegancsmith** [comment]
We have done a lot of work for GitLab in for the 3.x series. @replicatesas is this issue still occurring?

**Comment by keegancsmith** [comment]
ping @replicatesas is this still an issue?
