### ISSUE TITLE
Remove config-file.ConfigMap.yaml from deploy-sourcegraph, prod, dogfood, deploy-sourcegraph-docker

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#1538]
```
# TODO(slimsag): After 3.0 (NOT 3.0-preview), we can remove this. It is
# left here now so that users upgrading to 3.0 will leave it here so
# that the DB will be populated with their old site config file
# (i.e. for migration). This means that for now we have two sources of
# truth for the 'default' cluster configuration: The config-map in this
# repository and the confdefaults.Cluster variable in our main repo.
```

**Comment by nicksnyder** [comment]
Nevermind, I just saw this comment

```
# TODO(slimsag): After 3.0 (NOT 3.0-preview), we can remove this. It is
# left here now so that users upgrading to 3.0 will leave it here so
# that the DB will be populated with their old site config file
# (i.e. for migration). This means that for now we have two sources of
# truth for the 'default' cluster configuration: The config-map in this
# repository and the confdefaults.Cluster variable in our main repo.
```

**Comment by sqs** [comment]
@ggilmore @slimsag Is this still relevant?

**Comment by slimsag** [comment]
@sqs I am the correct owner here and will follow up when appropriate, refer to the comment in the issue description for more info.

**Comment by ggilmore** [comment]
All the [references to site-configuation.ConfigMap.yaml](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/deploy-sourcegraph%24+%22config-file.ConfigMap.yaml%22) and [configuration](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/deploy-sourcegraph%24+%22site+configuration%22) in https://github.com/sourcegraph/deploy-sourcegraph/blob/master/docs/configure.md also need to be updated.

**Comment by nicksnyder** [comment]
To be clear, the original issue description was written before we renamed the releases, so I think no action is needed here until after 3.1

**Comment by slimsag** [comment]
@ggilmore That is a separate issue, https://github.com/sourcegraph/sourcegraph/issues/1428, which I will solve this week.
@nicksnyder Correct.

**Comment by slimsag** [comment]
I will do this early in 3.2, because it is safer to do so + I am short on time.

**Comment by slimsag** [comment]
We may want to wait to remove this until all customers have migrated to a 3.x version. If we don't and a customer skips a version which contains this, then automatic migration won't occur for them. Not sure if there is a better way to handle this?

I'll update the comment to mention "wait for all customers to upgrade to 3.x" instead of the current version it mentions.

**Comment by sqs** [comment]
Moving to backlog due to @slimsag's above comment https://github.com/sourcegraph/sourcegraph/issues/1538#issuecomment-465839845 about waiting longer to make this change.
