### ISSUE TITLE
Users can create and manage code host connections

### ISSUE THREAD

**Issue by christinaforney** [sourcegraph/sourcegraph#15399]
Code host connections are how users connect their Sourcegraph account to third-party code hosts.

<p></p>

**Action items for first iteration:**

<p></p>

- Replace "Manage repositories" view with new "Code host connections" view.

  - List supported code hosts—GitHub.com and GitLab.com in first iteration.

  - Indicate if a code host connection exists for a given code host. Otherwise, present connect action.

  - Code host connections will use manually-entered access tokens.

  - Connect action triggers modal overlay with personal access token input.

  - After entering the personal access token, user returns to the list of code host connections with the connection status updated.

  - User can edit access token, which triggers the same entry modal. Access token is never revealed after entry—editing the token replaces it altogether.

  - User can remove a code host connection. A confirmation modal is shown in response to the action.

  - If for some reason a code host connection is nonfunctional, an inline error message is shown with an in-message action.

  - Note: only one code host connection is allowed for any given code host.

  - Subheading text links to "Add repositories" view.

<p></p>

**View on Figma:**

<https://www.figma.com/file/zXvqCASHDzmvKbrAl1EVsd/Public-and-Private-Repos-for-Users-on-Cloud?node-id=563%3A21272>

<p></p>

**On the radar in case it affects implementation decisions:**

<p></p>

- Organizations on Sourcegraph Cloud will use the same code host connections UI in the organization's settings.

- We don't want diverge Sourcegraph Cloud from Server. That means that this UI will need to also support self-hosted and managed instances, if not immediately, then in the very near future.

- This UI will support creating the connection via OAuth instead of manually in a very near iteration.

**Comment by christinaforney** [comment]
Link to feature: https://sourcegraph.productboard.com/feature-board/planning/features/6031069

**Comment by tsenart** [comment]
Do we need Figma link / assets / etc?

**Comment by tsenart** [comment]
cc @ryanslade @artemruts
