### ISSUE TITLE
Links to open GitHub issues are broken

### ISSUE THREAD

**Issue by clintharrison** [sourcegraph/sourcegraph#154]
- **Sourcegraph version:** Sourcegraph.com
- **Platform:** Chrome 70

#### Steps to reproduce:

1. Go to https://sourcegraph.com/search
2. Click help button
3. Click a link under "File a public issue"

#### Expected:
Browser navigates to GitHub 

#### Actual:
Browser navigates to https://sourcegraph.com/https:/github.com/sourcegraph/issues/issues/new?template=bug_report.md

`<a href="/https://github.com/sourcegraph/issues/issues/new?template=bug_report.md">` has an unwanted `/` at the beginning.

**Comment by nicksnyder** [comment]
Thanks for reporting!

@vanesa I think this just needs to be changed from `<Link>` to `<a>`
