### ISSUE TITLE
JSONC in external services config causes 500

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#1540]
- Open http://localhost:3080/site-admin/external-services
- Create a new service
- Save the default text (make sure it includes a comment `// ...`):

```
{
    // Configure your external service here (Ctrl+Space to see hints)
}
```

- Open http://localhost:3080/github.com/gorilla/mux/-/blob/mux.go
- Notice a 500:

![image](https://user-images.githubusercontent.com/1387653/50320253-5b900180-0480-11e9-8506-0230a25247f7.png)

**Comment by slimsag** [comment]
I have a fix for this incoming.
