### ISSUE TITLE
Make repo name and file name (the last breadcrumb) bold

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#15437]
Part of the Breaders Tracking Issue #15431 

Overlaps with issue #14258 - I think it should close this issue by achieving the desired effect of the repo being more prominent.

**Description**
Make repo name and file name (the last breadcrumb) bold. It will make them more distinguishable from the other breadcrumbs and improve the hierarchy of the page.

**Design details**
- Currently, both repo and file names are semi-bold (600).

- **Change to bold (~~900~~ 700)**

[Figma](https://www.figma.com/file/A4gGoseJDz8iPeHP515MfQ/%F0%9F%A5%96Breaders-breadcrumbs-headers-Final-review?node-id=567%3A206)

**Comment by felixfbecker** [comment]
@AlicjaSuska are you sure it should be `900` and not `700`? Our classes for `bold` and the style for `strong` is `700`. `900` looks _very_ bold:

![Uploading image.png…]()

**Comment by AlicjaSuska** [comment]
@felixfbecker You're right - let's go with 700
