### ISSUE TITLE
Remove breadcrumbs from web-oriented pages

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#15432]
Part of the Breaders Tracking Issue #15431 

**Description**
Because we're adding linked parent elements directly to the [headers](https://www.figma.com/file/A4gGoseJDz8iPeHP515MfQ/%F0%9F%A5%96Breaders-breadcrumbs-headers-Final-review?node-id=343%3A175), breadcrumbs used so far need to be removed from all web-oriented pages.

List of pages that are currently using breadcrumbs:

- [ ] Insights

- [ ] Extensions registry and all extension details pages

- [x] Campaigns and all campaign details pages

**Design details**
Removing the breadcrumbs will push the whole page up. For Insights, please add 0.5rem of additional padding above the header to keep all the layouts consistent.

**Comment by felixfbecker** [comment]
@sourcegraph/campaigns maybe you could do this for campaign pages whenever you get to it, and we can do it for the others?

**Comment by eseliger** [comment]
Yup will do https://github.com/sourcegraph/sourcegraph/issues/15471

**Comment by eseliger** [comment]
Sorry, not done, just campaigns.
