### ISSUE TITLE
Centralize OS logs in centralized logging

### ISSUE THREAD

**Issue by chayim** [sourcegraph/sourcegraph#15447]

**Comment by ElizabethStirling** [comment]
Investigate if we already get this from google cloud from our workloads

If not, get into stackdriver or direct to elastic if that sucks

Actual workloads responsible for inserting into stackdriver
If not possible, deploy filebeat per workload, read logs, put them into elastic

**Comment by ElizabethStirling** [comment]
Update: GKE does not appear to natively do this out of the box. However, Google has some prebuilt yaml for this. Hopefully, this will only require me to verify that this code does in fact work [x](https://github.com/GoogleCloudPlatform/k8s-node-tools/blob/master/os-audit/cos-auditd-logging.yaml)

**Comment by ElizabethStirling** [comment]
Closing now that this work has been completed and Elastic has been re-stabilized. Time estimate was way off because I didn't expect the scope to expand to debugging and re-configuring Elastic, pubsubbeats, and our logging cluster.
