### ISSUE TITLE
Update the infrastructure repository to consume secrets from our secret manager

### ISSUE THREAD

**Issue by chayim** [sourcegraph/sourcegraph#15457]
Update our infrastructure repo to consume secrets from Vault, rather than storing them in plaintext. This will likely require multiple PRs, since there are both terraform and k8s secrets, each of which need to be handled and tested differently.

**Comment by ElizabethStirling** [comment]
Bumping estimate since this also contains secrets in yaml, rather than pure terraform like I initially expected.

**Comment by ElizabethStirling** [comment]
Replacing with more well defined subtasks.
