### ISSUE TITLE
Buildkite secrets are located and enumerated

### ISSUE THREAD

**Issue by chayim** [sourcegraph/sourcegraph#15453]
Locate and enumerate secrets used by buildkite, so that we know exactly what to load into Vault. This will also let us determine how the secrets are currently consumed, which will assist in more accurately estimating the work required to get Vault up and running.

**Comment by ElizabethStirling** [comment]
Note - this should also encompass enabling the secret manager's audit logs. https://cloud.google.com/secret-manager/docs/audit-logging

**Comment by ElizabethStirling** [comment]
Secret manager audit logs enabled
