### ISSUE TITLE
Update deploy-sourcegraph-dot-com to consume secrets from our secret manager

### ISSUE THREAD

**Issue by chayim** [sourcegraph/sourcegraph#15456]
Update our dotcom deployment repo to consume secrets from Vault, rather than storing them in plaintext. This will likely require multiple PRs, since there are both terraform and k8s secrets, each of which need to be handled and tested differently. 

>Elizabeth

**Comment by ElizabethStirling** [comment]
Bumped estimate significantly since there are a large number of secret values, and not all are ingested as environment variables. It will at the very least require some reconfiguration of our configmaps and secrets.

**Comment by ElizabethStirling** [comment]
Replacing with more well defined subtasks.
