### ISSUE TITLE
Fix the Sourcegraph.com license expiration bot

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#15467]
I built a bot that only functions on Sourcegraph.com that posts a note to our sales team whenever a customer license is about to expire. It _mostly_ doesn't work, but once in a while something will randomly appear (see the #licenses channel).

The bot is defined in https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/internal/dotcom/productsubscription/license_expiration.go.

I've tested locally and it always seems to work just fine. Perhaps something is broken on dotcom due to having multiple frontends? Perhaps my date/time logic is off somehow? Perhaps the webhook env var sometimes isn't set? I'm quite lost.

**Comment by tsenart** [comment]
Looking at production logs to see what errors might be happening.

**Comment by dadlerj** [comment]
Thanks! Not an urgent issue, of course (we've been surviving without it for months now :) ).

**Comment by tsenart** [comment]
@dadlerj: Got some time for hacking :D
