### ISSUE TITLE
Collect metrics for campaigns funnel 

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#15482]
To derive a campaigns funnel from ping data we need to collect the following metrics. @ebrodymoore suggested how to store and collect this information. Those suggestions are in (). 
 
- Created page viewed (eventLog)
- Spec created (either)
- Preview page viewed (eventLog)
- Spec applied (creates the campaign)
  - Number of changesets unpublished (db Eric thinks it is less reliable to get this data from an event log for viewing)
  - If we want the number of changesets for spec we don’t want to process multiple event logs and risk out of date or dupe entries. 
  - Also affects number of changesets overall
- Number of changesets open (same as above)
- Number of changesets merged (same as above)
- Campaign closed (db)

**Comment by mrnugget** [comment]
Just discussed this on Slack with @rrhyne and @ebrodymoore:

- Most of these are covered in https://github.com/sourcegraph/sourcegraph/pull/15279
- What's missing is: `Created page viewed (eventLog)`, `Preview page viewed (eventLog)`, `Campaign closed (db)`
- I'll take this ticket on.
- Tracking `Campaign closed (db)` can be done in database.
- The other two I can track in the frontend.
