### ISSUE TITLE
Support filtering repos by owner in API

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#15488]
We need to add the ability to filter repositories by a single namespace here:

https://github.com/sourcegraph/sourcegraph/blob/48625df9c1af26ea3ae9dfa0d9d899bd2bf13df9/cmd/frontend/graphqlbackend/schema.graphql#L2096

Initially we'll only support users but after https://github.com/sourcegraph/sourcegraph/issues/15324 is implemented should support orgs too.

Part of: https://github.com/sourcegraph/sourcegraph/issues/15401

**Comment by ryanslade** [comment]
@asdine I assigned this to you since we're waiting on the search context stuff

**Comment by asdine** [comment]
@arussellsaw It seems that you are already working on a frontend task that needs this, did you already work on this on your side?

**Comment by arussellsaw** [comment]
yep! there's now a Repositories connection on the User object in the graphql schema https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/schema.graphql#L6324-6358
