### ISSUE TITLE
Regression: Scrolling broken on configuration page on dev servers

### ISSUE THREAD

**Issue by francisschmaltz** [sourcegraph/sourcegraph#155]
Regression of https://github.com/sourcegraph/enterprise/issues/13354

![crap](https://user-images.githubusercontent.com/11583013/46266675-ccf58f00-c4e5-11e8-8a97-314e272ac7cc.gif)

@slimsag This seem like it should block release, but that's up to you.

**Comment by slimsag** [comment]
Yes, so tag with `release-blocker` but not `open-source`.

**Comment by attfarhan** [comment]
Just investigated this and appears this only occurs on development builds. Running ./dev/run-server-image.sh does not have this issue, and this also doesn't occur on dogfood. So this does not block release.

**Comment by sqs** [comment]
This was fixed
