### ISSUE TITLE
Replacement for repos.list

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#1550]
https://github.com/sourcegraph/sourcegraph/pull/1391 removed support for repos.list because that configuration option didn't fit in with how we wanted to model code host connections with external services.

repos.list served as an escape hatch for code hosts that we don't have explicit API integrations for (e.g. bitbucket.com). It is incredibly valuable to be able to say "we support any Git code host", even if we don't have a direct integration with that code host.

To support any code host in the new external services model, the proposal is to create a new external service type called "Other". The JSON config will look roughly like this:

```json
{
    "url": "https://bitbucket.com",
    "repos": [
        "a/b",
        "c/d"
    ]
}
```

This will cause repo-updater/gitserver to clone the following repos:
```
git clone https://bitbucket.com/a/b
git clone https://bitbucket.com/c/d
```

When inserting into the `repo` table in the database, `external_*` columns will be populated as follows
- `external_service_type` will be set to `other`
- `external_service_id` will be set to the url of the external service (e.g. "https://bitbucket.com").
- `external_id` will be the fully qualified clone uri (e.g. "https://bitbucket.com/a/b")

Note that repositories synchronized in this way will not support renames, but that is the state of the current system today ([which is why we moved toward the external services model](https://github.com/sourcegraph/sourcegraph/issues/914)).

Checklist
- [x] Add "OtherExternalServiceConnection" type to site.schema.json
- [ ] Add code to https://github.com/sourcegraph/sourcegraph/tree/master/cmd/repo-updater/repos to fetch repos for these other connections.
- [ ] Write a test plan

**Comment by dadlerj** [comment]
What code hosts would be initially supported with a built-in service? 
* GitHub.com
* GitHub Enterprise
* GitLab
* Bitbucket Server
* Bitbucket.com (?)
* Phabricator (?)
* Gitolite (?)

**Comment by nicksnyder** [comment]
Relevant conversation: https://sourcegraph.slack.com/archives/C0B2RU51Q/p1546898265072400

**Comment by nicksnyder** [comment]
After further discussion with @sqs, this is a priority to fix for 3.0 because it is very valuable to maintain the invariant "we support any Git code host". @tsenart can you please make this your main priority this week (instead of https://github.com/sourcegraph/sourcegraph/issues/914)?

I updated the original issue description with a proposal.

**Comment by slimsag** [comment]
What is the motivation for separating the host portion of the URL (`url`) and the path portion (`repos`)? I ask this because:

1. Just a list of clone URLs seems easier to describe / fill out the details of when writing the actual JSON, instead of having to explain / learn that "these `repos` are relative to this `url`".
2. My guess would be that most users creating this JSON list would generally be doing so in some scripted fashion. I suspect they may be more likely to have a list of absolute clone URLs and having to split them up to be relative would be more annoying.

**Comment by nicksnyder** [comment]
> What is the motivation for separating the host portion of the URL (url) and the path portion (repos)

My thought was that it mirrors how other configs work and it enforces that you can't mix repos from two difference sources in the same list (i.e. you should create two "Other" external services, one for each code host, in this case).

> 1. Just a list of clone URLs seems easier to describe / fill out the details of when writing the actual JSON, instead of having to explain / learn that "these `repos` are relative to this `url`".
> 2. My guess would be that most users creating this JSON list would generally be doing so in some scripted fashion. I suspect they may be more likely to have a list of absolute clone URLs and having to split them up to be relative would be more annoying.

What if we keep my proposed schema and just not require "url"? For example, both of these could be valid configs

```json
{
    "url": "https://bitbucket.com",
    "repos": [
        "a/b",
        "c/d"
    ]
}
```

```json
{
    "url": "", // or unset completely
    "repos": [
        "https://bitbucket.com/a/b",
        "https://bitbucket.com/c/d"
    ]
}
```

At the end of the day, url is just concatenated with "repos" so it is fine if "url" is empty/unset.

**Comment by slimsag** [comment]
Your second proposal above sounds good to me 👍

**Comment by keegancsmith** [comment]
Out of interest, how do we know when to use ssh vs https in this proposal?

**Comment by tsenart** [comment]
> Note that repositories synchronized in this way will not support renames, but that is the state of the current system today (which is why we moved toward the external services model).

The reason we don't support renames without external services is that we'll be relying on a stable external identifier provided by a code host's API to detect renames.

An alternative approach that we can consider in the future is to do content based deduplication via `git merge-base` to the best common ancestor between two repos.

**Comment by nicksnyder** [comment]
> What is the motivation for separating the host portion of the URL (url) and the path portion (repos)

There is a third reason I remembered: we need a value to put for `external_service_id` in the repo table, and for GitHub/GitLab it is the url. I am not sure if it would cause a problem for that to be empty (if it does cause a problem then we should prevent an empty url in the config).

> Out of interest, how do we know when to use ssh vs https in this proposal?

How did we know with the old repos.list?

> Content based deduplication

I predict content based filtering to be tricky to do well (e.g. how do you distinguish between a legitimate fork and its parent repo).

The approach proposed here is merely a catch all so customers aren’t blocked from using Sourcegraph if we lack a first class API integration with their code host.

I would prefer adding more first class api integrations to making the catch all more complicated.
