### ISSUE TITLE
Improving language support in 2019

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#1551]
See the proposal: https://github.com/sourcegraph/sourcegraph/pull/1541

- [ ] By ?, publish a blog post with modified version of this proposal that communicates our high level plan and states what Sourcegraph wants in terms of language support. Briefly summarize and link to the master plan. Mention that we'll help with sponsorship, technical advice, getting feedback, etc.
- [ ] By ?, update langserver.org and our careers repo to link to this blog post and have @sqs to tweet this to Future of Coding
- [ ] By ?, after doing an initial triage, publish one blog post per language similar to the above blog post but with more details about the particular language.
- [ ] By Jan 16, add an Implementation section to the README of sourcegraph/{go,typescript,python}
- [ ] By Jan 16, prepare a doc outlining how to build language extensions building off of https://github.com/sourcegraph/sourcegraph/pull/628 but avoid recommending certain approaches (leave it up to the language server author), link to the Implementation sections above
- [ ] By Jan 18, update langserver.org entries with check boxes for any new and relevant pieces of functionality based on the Implementation sections above
- [ ] By Jan 14, basic Python support is deployed to Sourcegraph.com (@sqs has already implemented most of this)
- [ ] By ?, same-file Ruby hovers work on GitHub.com
- [ ] By ?, Ruby hovers work for full projects
- [ ] By Jan 25, Python has cross-repo support
- [x] Jan 10, determine quality of Swift language server
- [ ] By Jan 18, find a Swift contractor
- [ ] By Jan 25, basic Swift support is deployed on Sourcegraph.com
- [ ] By Feb 1, Swift has cross-repo support

**Comment by felixfbecker** [comment]
This looks very outdated. Should we close it?
