### ISSUE TITLE
Unable to run SourceGraph with Istio

### ISSUE THREAD

**Issue by ethankhall** [sourcegraph/sourcegraph#15517]
- **Sourcegraph version:** 3.20.1
- **Platform information:** Kubernetes, EKS, Istio 1.7

#### Steps to reproduce:

1. Deploy Istio into cluster
2. Create namespace with istio-inject=enabled
3. Deploy Sourcegraph
4. Errors when searching

#### Expected behavior:

Everything to work normally

#### Actual behavior:

Error message with no search results.

```
=2020-11-06T06:26:48+0000 lvl=eror msg="API HTTP handler error response" method=GET request_uri="/.internal/search/configuration?repo=github.com%2F<org>%2F<repo>" status_code=500 error="git command [git rev-parse HEAD] failed (stderr: \"\"): strconv.Atoi: parsing \"\": invalid syntax" trace=
```

It looks like if I disable istio injection on `gitserver-0` with all of the other pods having istio enabled everything works. I don't know what's special about gitserver

**Comment by unknwon** [comment]
@sourcegraph/distribution is this something we aim to support?

**Comment by daxmc99** [comment]
First thought would be that gitserver uses raw TCP sockets and I believe istio works at gRPC / HTTP(S) protocol level by default.

**Comment by daxmc99** [comment]
Part of https://github.com/sourcegraph/sourcegraph/issues/23560

**Comment by virginiaulrich** [comment]
2022-03-28 Delivery planning session note: This is tracked as a product gap now so closing this issue to remove duplicative efforts
