### ISSUE TITLE
Disable Gitlab's nameTransformations setting for user-added external services

### ISSUE THREAD

**Issue by asdine** [sourcegraph/sourcegraph#15529]
Setting:
https://github.com/sourcegraph/sourcegraph/blob/c8c970746592fc2efefa0c7edf7fdd946bec8cc9/schema/gitlab.schema.json#L129-L129

**Comment by ryanslade** [comment]
I *think* it might be as simple as adding `nameTransformations` to this slice:
https://github.com/sourcegraph/sourcegraph/blob/3309f7ef7a214541f8921a3a81a7bd45c9e67242/internal/db/external_services.go#L171
