### ISSUE TITLE
Revert to using upstream reactstrap when new release is published

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1553]
When a release of `reactstrap` that incorporates https://github.com/reactstrap/reactstrap/pull/1254#issuecomment-434401397 is published, we should use it instead of this self-published package (from our `package.json`):

```
"reactstrap": "https://registry.npmjs.org/@sqs/reactstrap/-/reactstrap-6.5.0-tmp1.tgz",
```

(I self-published that to incorporate the fix to https://github.com/reactstrap/reactstrap/issues/1201, which was preventing any child components of CommandList in the web app from seeing the React 16.3 context set in SourcegraphWebApp.)

**Comment by felixfbecker** [comment]
Looks like it was published with v7?

**Comment by sqs** [comment]
Yep
