### ISSUE TITLE
Send Content-Length from archive raw API

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#1554]
Without a `Content-Length` header, we cannot show a deterministic progress indicator from language servers. We currently show MB downloaded, which actually caused some users to think it is downloading a repo to the user's disk and to uninstall the browser extension.

@slimsag mentioned we serve most archives from a cache so we could get a Content-Length from a stat in almost all cases.

**Comment by slimsag** [comment]
I am putting in backlog, let me know if you think this should be in the next release.

**Comment by felixfbecker** [comment]
@slimsag how much time would this take?

**Comment by felixfbecker** [comment]
@keegancsmith in case you also wanna look at this

**Comment by felixfbecker** [comment]
Could this be prioritised? We are seeing browser extension uninstalls because people think it is downloading repos to their local disk, because we can't show them anything but a number of MB already downloaded. I would really like to show just a progress bar but I can't atm.

**Comment by felixfbecker** [comment]
Assigning to 3.2.

**Comment by sqs** [comment]
This is less important than the other things @slimsag 	and @keegancsmith 	are working on. Moving to backlog.

@felixfbecker 	I will propose a solution for the uninstalls that doesn't involve this code change at https://github.com/sourcegraph/sourcegraph/issues/2451.
