### ISSUE TITLE
Safari Extension

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#15553]
Source of truth [customer issue #138](https://github.com/sourcegraph/customer/issues/138)

- [x] Spec / roadmap document by EOD 2020-11-10
- [x] Safari extension progress update by EOD 2020-11-13

**Comment by felixfbecker** [comment]
@Joelkw do we need this issue in addition to https://github.com/sourcegraph/customer/issues/138 and  https://github.com/sourcegraph/sourcegraph/issues/766?

**Comment by Joelkw** [comment]
@felixfbecker I was using this to track the progress update and roadmap documentation, which were our two initial goals for this iteration (which now also include finishing safari – thanks for moving that one in). Given that both those are done, I think we should close this!
