### ISSUE TITLE
Move extension thumbnail to the details column on extension details page

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#15567]
Part of the Breaders Tracking Issue #15431 

**Description**
To accommodate the new header, we need to move the extension thumbnail to the details column.

**Design details**
[Figma](https://www.figma.com/file/A4gGoseJDz8iPeHP515MfQ/%F0%9F%A5%96Breaders-breadcrumbs-headers-Final-review?node-id=701%3A497)

**Comment by AlicjaSuska** [comment]
<img width="382" alt="Screenshot 2020-11-25 at 12 46 52" src="https://user-images.githubusercontent.com/20326070/100224042-93313f00-2f1c-11eb-833e-7c626a47d68b.png">

@felixfbecker currently we use a default puzzle icon on the registry page for extensions authored by Sourcegraph that don't have the icon. Please, remember to add it to the right column as well. Currently, it is not shown in the header (it should be, by design).

For the extensions not authored by Sourcegraph that don't have the icon, no default icon should be added to the column.

**Comment by felixfbecker** [comment]
This task makes most sense to do together with 
 https://github.com/sourcegraph/sourcegraph/issues/15563

**Comment by umpox** [comment]
@felixfbecker Picking this up as I'm starting work on https://github.com/sourcegraph/sourcegraph/issues/15565 which touches this page

**Comment by umpox** [comment]
Closed by https://github.com/sourcegraph/sourcegraph/pull/17831
