### ISSUE TITLE
Add updated header to the pages (list in the description)

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#15565]
Part of the Breaders Tracking Issue #15431 

**Description**
Currently, only extensions use the header component. It needs to be added to the remaining pages.

(*Campaigns header looks similar but it is not a header component)

**Design details**
- [Campaigns](https://www.figma.com/file/A4gGoseJDz8iPeHP515MfQ/%F0%9F%A5%96Breaders-breadcrumbs-headers-Final-review?node-id=343%3A717). Please note that Campaigns are no longer in beta, there is no need for the beta label.
- [Campaign details page](https://www.figma.com/file/A4gGoseJDz8iPeHP515MfQ/%F0%9F%A5%96Breaders-breadcrumbs-headers-Final-review?node-id=343%3A475)
- [Extensions registry](https://www.figma.com/file/A4gGoseJDz8iPeHP515MfQ/%F0%9F%A5%96Breaders-breadcrumbs-headers-Final-review?node-id=563%3A1822)
- [Extension details page](https://www.figma.com/file/A4gGoseJDz8iPeHP515MfQ/%F0%9F%A5%96Breaders-breadcrumbs-headers-Final-review?node-id=701%3A498) - to accommodate the new header, the extension thumbnail needs to be moved to the details column (described in #15567). Also, on this page, it makes sense to align the toggle button with the left side of the details column for visual consistency (not to the right side of the column grid as in all other cases).
- [Profile settings](https://www.figma.com/file/A4gGoseJDz8iPeHP515MfQ/%F0%9F%A5%96Breaders-breadcrumbs-headers-Final-review?node-id=345%3A9995)
- [Organisation settings](https://www.figma.com/file/A4gGoseJDz8iPeHP515MfQ/%F0%9F%A5%96Breaders-breadcrumbs-headers-Final-review?node-id=345%3A10679)
- [Insights](https://www.figma.com/file/A4gGoseJDz8iPeHP515MfQ/%F0%9F%A5%96Breaders-breadcrumbs-headers-Final-review?node-id=345%3A9027). 'Share feedback' should be a mailto:support@sourcegraph.com
@Joelkw do you think it would make sense for us to link your or my email directly here for the time being?
- [Query builder](https://www.figma.com/file/A4gGoseJDz8iPeHP515MfQ/%F0%9F%A5%96Breaders-breadcrumbs-headers-Final-review?node-id=563%3A2336)

**Comment by umpox** [comment]
Closed by https://github.com/sourcegraph/sourcegraph/pull/17831
