### ISSUE TITLE
Update the header component

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#15563]
Part of the Breaders Tracking Issue #15431 

**Description**
Add breadcrumbs, header byline and buttons to the header component, update the horizontal spacing, align with the column grid.

**Design details**
[Figma](https://www.figma.com/file/A4gGoseJDz8iPeHP515MfQ/%F0%9F%A5%96Breaders-breadcrumbs-headers-Final-review?node-id=343%3A175)

1. The header can contain the following elements:
- breadcrumbs
- header byline
- button(s)
- label + 'share feedback' button (for beta or prototype pages). The button will link will be determined case-by-case.
- avatar (for user and org settings)

2. Headers should be flexible and let us create different variations, for ex. (but not limited to):
- [the simplest header](https://www.figma.com/file/A4gGoseJDz8iPeHP515MfQ/%F0%9F%A5%96Breaders-breadcrumbs-headers-Final-review?node-id=558%3A10738) (only page title)
- [page name + icon + optional button(s)](https://www.figma.com/file/A4gGoseJDz8iPeHP515MfQ/%F0%9F%A5%96Breaders-breadcrumbs-headers-Final-review?node-id=343%3A176)
- [page name + avatar](https://www.figma.com/file/A4gGoseJDz8iPeHP515MfQ/%F0%9F%A5%96Breaders-breadcrumbs-headers-Final-review?node-id=690%3A13651) - for settings pages. Avatar has different dimensions than the page icon (1)
- [header with breadcrumbs + byline + button(s)](https://www.figma.com/file/A4gGoseJDz8iPeHP515MfQ/%F0%9F%A5%96Breaders-breadcrumbs-headers-Final-review?node-id=343%3A175) - for ex. Campaigns header
- [beta feature header with label and 'share feedback' button](https://www.figma.com/file/A4gGoseJDz8iPeHP515MfQ/%F0%9F%A5%96Breaders-breadcrumbs-headers-Final-review?node-id=690%3A13588)

3. Comparing to the current components, the **spacing** between elements and overall height of the header has changed.

4. **The page icon** is enclosed in the 32x32px bounding box. It follows the same rules as all the other icons in our app when it comes to sizing and spacing. We no longer need a separate export for the headers.

5. Please, pay attention to the page icon colors:
- [when it is used as a breadcrumb](https://www.figma.com/file/A4gGoseJDz8iPeHP515MfQ/%F0%9F%A5%96Breaders-breadcrumbs-headers-Final-review?node-id=343%3A175) - it should have a link color
- [when it is used as a regular page icon](https://www.figma.com/file/A4gGoseJDz8iPeHP515MfQ/%F0%9F%A5%96Breaders-breadcrumbs-headers-Final-review?node-id=343%3A176) - it should have a regular text color

6. From now on, we will only use icons for the key pages on our platform (all available for export in Figma):
- [Campaigns](https://www.figma.com/file/A4gGoseJDz8iPeHP515MfQ/%F0%9F%A5%96Breaders-breadcrumbs-headers-Final-review?node-id=558%3A10790)
- [Extensions](https://www.figma.com/file/A4gGoseJDz8iPeHP515MfQ/%F0%9F%A5%96Breaders-breadcrumbs-headers-Final-review?node-id=558%3A10792)
- [Code Insights](https://www.figma.com/file/A4gGoseJDz8iPeHP515MfQ/%F0%9F%A5%96Breaders-breadcrumbs-headers-Final-review?node-id=558%3A10791)
- Code monitoring (TBD)

7. Design for the [light](https://www.figma.com/file/A4gGoseJDz8iPeHP515MfQ/%F0%9F%A5%96Breaders-breadcrumbs-headers-Final-review?node-id=690%3A13588) and [dark theme](https://www.figma.com/file/A4gGoseJDz8iPeHP515MfQ/%F0%9F%A5%96Breaders-breadcrumbs-headers-Final-review?node-id=690%3A13648)

**Comment by umpox** [comment]
@AlicjaSuska 

> Please, pay attention to the page icon colors:
> - when it is used as a breadcrumb - it should have a link color

Does this mean that the icon should also be clickable as a link?

If so, where would clicking the icon take you [in this example](https://www.figma.com/file/A4gGoseJDz8iPeHP515MfQ/%F0%9F%A5%96Breaders-(breadcrumbs-%2B-headers)-%2315431-%5BApproved%5D?node-id=343%3A175)

**Comment by AlicjaSuska** [comment]
@umpox yes, [when icon is used as breadcrumb](https://www.figma.com/file/A4gGoseJDz8iPeHP515MfQ/%F0%9F%A5%96Breaders-breadcrumbs-headers-15431-Approved?node-id=343%3A474) it is a link and takes user to the first page from the path (Campaigns in this example, the same location as if they clicked on 'Campaigns' in the top nav bar). 

If icon is displayed in the header on one of those 'main' pages - it has the same color as the page name and doesn't work as a link ([on the Campaigns example](https://www.figma.com/file/A4gGoseJDz8iPeHP515MfQ/%F0%9F%A5%96Breaders-breadcrumbs-headers-15431-Approved?node-id=343%3A718))
