### ISSUE TITLE
searching binary matches "not indexed reason" from zoekt

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#15581]
![image](https://user-images.githubusercontent.com/187831/98545990-f6756d00-229e-11eb-9336-1721fba0c529.png)

When skipping a file, we include the skip reason in the file contents: https://github.com/sourcegraph/zoekt/blob/48642cac2d971e23f6102e54d42957786c779f22/indexbuilder.go#L392

Binary files have the SkipReason: `binary content at byte offset %d`.

**Comment by stefanhengl** [comment]
This has been implemented.
