### ISSUE TITLE
Code monitoring: add documentation pages, and populate links in the creation page.

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#15612]
- [ ] https://github.com/sourcegraph/sourcegraph/pull/15575#discussion_r520040585
- [ ] https://github.com/sourcegraph/sourcegraph/pull/15575#discussion_r520045810
- [ ] https://github.com/sourcegraph/sourcegraph/pull/15575#discussion_r520046773
- [ ] https://github.com/sourcegraph/sourcegraph/pull/15575#discussion_r520057099

**Comment by quinnkeast** [comment]
I'm beginning to stub out documentation in #16173.

**Comment by lguychard** [comment]
We have code monitoring docs now.
