### ISSUE TITLE
If `experimentalFeatures.splitSearchModes` is disabled while interactive search is on, webapp goes into odd state

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#15632]
#### Steps to reproduce:

1. Enable `experimentalFeatures.splitSearchModes`
2. Enable interactive search via the dropdown next to search bar
3. Disable `experimentalFeatures.splitSearchModes`

#### Expected behavior:

Interactive search is completely disabled

#### Actual behavior:

Webapp goes into a weird state where it thinks it's in interactive search mode (so no filter pills enabled) but doesn't render the interactive search UI.

**Comment by lguychard** [comment]
We no longer have this flag.
