### ISSUE TITLE
Refactor uses of FileMatchLimit which corresponds to count

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#15640]
After processing a query, we persist the value of `count:` in `FileMatchLimit`, and use it in other kinds of searches like `commit`. We should refactor the internal data types to reflect these values.

Example https://github.com/sourcegraph/sourcegraph/pull/15619/files#r521127896

**Comment by camdencheek** [comment]
Closing since there is no longer such thing as `FileMatchLimit`
