### ISSUE TITLE
Error when updating display name and avatar URL

### ISSUE THREAD

**Issue by justdueck** [sourcegraph/sourcegraph#15663]
- **Sourcegraph version:** 
- **Platform information:** 

#### Steps to reproduce:

1. Update Display Name and Avatar URL in user settings
2. Hit 'Save'

#### Expected behavior:
Saves successfully and updates display name and avatar 

#### Actual behavior:
Receives `Error: unable to change username because auth.enableUsernameChanges is false in site configuration`

Customer support ticket: https://sourcegraph.atlassian.net/jira/servicedesk/projects/SG/queues/custom/2/SG-420

**Comment by unknwon** [comment]
>A site admin then proceeds as expected,...

I don't think so? Both site admins and regular users are blocked by this config check. (but this is not important, just a minor detail)
