### ISSUE TITLE
Validate campaigns tokens before storing them

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#15692]
As the title suggests, I think we should try to catch user errors (missing scope, copy-past error,..) as early as possible.

**Comment by chrispine** [comment]
Is this something that would be done solely on the src-cli side?

**Comment by eseliger** [comment]
Ah, this was about the campaigns credentials UI, so solely `sg/sg`. When we ask users for credentials we just store them away and don't validate they're actually valid tokens.
