### ISSUE TITLE
LSIF Indexers to include references to implementations and uses of such for abstract interfaces/other

### ISSUE THREAD

**Issue by Strum355** [sourcegraph/sourcegraph#15699]
### Plan

LSIF 0.5.0 spec dictates that the response for the references request should also include eg implementations of a hovered abstract method as well as invocations of any of that method on types of the concrete classes

Excerpt from spec:
![image](https://user-images.githubusercontent.com/18282288/98956605-266b7d00-24f8-11eb-8c8b-ad062cd60e86.png)

Searching for `I#foo()` finds 4 references, searching for `II#foo()` finds 3 reference, and searching on `B#foo()` finds 5 results. The interesting part here is when the declaration of class B gets processed which implements `I` and `II`, neither the reference result bound to `I#foo()` nor the one bound to `II#foo()` can be reused. So we need to create a new one. To still be able to profit from the results generated for `I#foo` and `II#foo`, the LSIF supports nested references results. This way the one referenced from `B#foo` will reuse the one from `I#foo` and `II#foo`. Depending on how these declarations are parsed, the two reference results might contain the same references. When a language server interprets reference results consisting of other reference results, the server is responsible to de-duplicate the final ranges.

In the above example, there will be three reference results

![image](https://user-images.githubusercontent.com/18282288/98956628-2c615e00-24f8-11eb-8ad9-44fef35892f6.png)

### Tracked issues

- [ ] Support in lsif-go
- [x] Support in lsif-java
- [ ] Support in lsif-clang (if possible)

**Comment by macraig** [comment]
@Strum355 is this something we plan working on or worth archiving for now?

**Comment by Strum355** [comment]
@macraig Java has support for this. I shouldve ticked this. Given current priorities, we wont be addressing this in lsif-clang for a good while yet, and its a bit of a trickier issue with lsif-go, at best being locally based rather than cross repo. So we could close this for now
