### ISSUE TITLE
Search results page ugly wrapping

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#15700]
![image](https://user-images.githubusercontent.com/5589410/98957267-d7045d00-24b5-11eb-8973-49b09ef141f0.png)

Anyone else experiencing this? I assume it's not intentional, given the tabs become "floating" when they wrap.

Tagging @poojaj-tech as PM for triage!

**Comment by poojaj-tech** [comment]
Thanks for filing @dadlerj. It seems like a bug, and I'm seeing it too. Adding this to the search team's [prioritized backlog](https://github.com/orgs/sourcegraph/projects/99) to track (bugs we want prioritize fixing based on bandwidth).

@attfarhan  / @limitedmage any idea if this is a recent bug? If yes, we should fix this before the upcoming release goes out.

**Comment by limitedmage** [comment]
Introduced by #15549, I'll take a look

**Comment by poojaj-tech** [comment]
thanks @limitedmage!

**Comment by limitedmage** [comment]
@dadlerj Should be fixed now (when .com redeploys) :) [See video here](https://drive.google.com/file/d/1hmTJxcdtspQ0yNYmseqlCdpxy3qOFxSY/view?usp=sharing)

**Comment by dadlerj** [comment]
Thanks!
