### ISSUE TITLE
Notifications popping up on github.com PRs

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [sourcegraph/sourcegraph#1572]
- **Sourcegraph version:** 
- **Platform information:** 

#### Steps to reproduce:

1. Install your Chrome extension
2. Visit a PR on GitHub

#### Expected behavior:

No in-page notifications

#### Actual behavior:

`<div class="sourcegraph-notifications">...</div>` on the page:

![image](https://user-images.githubusercontent.com/3335181/50402624-dd747900-0765-11e9-9cbc-74ec3c269403.png)

wat

**Comment by sqs** [comment]
Now that notifications are used for passive progress indicators (instead of just in response to Sourcegraph-specific actions taken by the user), we need to find a way to make them either not show up on GitHub or be much less distracting.

**Comment by ijsnow** [comment]
Should this be up to the discretion of extension developers? For example, the image in this issue is about the typescript extension's diagnostics. Should that extension just provide a setting for whether or not a user would like to see this information? cc @felixfbecker

**Comment by felixfbecker** [comment]
Imo these progress indicators are universially useful because it is useful to know for the user what the language server is doing (and why e.g. hovers are not showing yet). But they look a lot more distracting on GitHub than on sourcegraph.com. I think the browser extension should find a better way to integrate these into GitHub that feels less distracting:

- Less out-of-place colors, e.g. white background instead of grey
- Positioning that does not overlay major UI elements and is properly anchored in some frame
- GitHub design: rounded corners

@francisschmaltz could you design this?

**Comment by francisschmaltz** [comment]
Will get designs this week. I had a similar problem where I was unsure if the extension was loading data locally in browser or to the SG instance.

**Comment by slimsag** [comment]
This is **really** intrusive / annoying. Is there any mitigation we can do for 3.0?

**Comment by sqs** [comment]
We should immediately update the TS ext to not show this loading indicator, until we have a better UI.

I think @felixfbecker is on a long flight right now. I will go make this change and publish the update.

Then moving this to 3.1 because it isn't important for 3.0 given this mitigation.

**Comment by JoshuaKGoldberg** [comment]
@felixfbecker I was seeing them on GH.com, where I didn't want to know about them. 

Either way they get in front of the on screen code. I don't like having anything overlaid on top of that portion of the screen.

If these were changed to something less intrusive that would be nice? But as long as they don't interrupt GH.com sessions, 👍

**Comment by felixfbecker** [comment]
What about the case where the language server is taking a long time to initialize and no hover appears? Would you prefer seeing some indication of progress (like reporting dependency installation as above) or just wait without any indicators?

**Comment by JoshuaKGoldberg** [comment]
Most of the time I don't use SG language service features on GH.com or even SG.com. When I _do_ use them it's nice to know - is there a way to only show the notification if I've demonstrated intent to use its services?

**Comment by felixfbecker** [comment]
Oh, that's a great insight! What if the server only shows the current progress once you hovered over something?
Alternatively, would you want a button that toggles hovers, notifications etc?

**Comment by JoshuaKGoldberg** [comment]
SGTM 😊

**Comment by sqs** [comment]
Now it only shows progress after you hover something. That satisfies our valued user @JoshuaKGoldberg 	(and me). :smile:

**Comment by felixfbecker** [comment]
@JoshuaKGoldberg we also now have a button to toggle TypeScript code intelligence on demand :)

![2019-03-07 21 44 36](https://user-images.githubusercontent.com/10532611/53987853-6de61700-4122-11e9-8c06-8cbbd812e942.gif)

**Comment by JoshuaKGoldberg** [comment]
Love it, thanks!
