### ISSUE TITLE
github-proxy: Limit concurrent requests per token

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#15751]
Our GitHub proxy is in place to limit the number of concurrent API requests we make, currently set at 1. However, it appears that this concurrency limit is only really valid when all calls are made on behalf of the same token, see here: https://developer.github.com/v3/guides/best-practices-for-integrators/#dealing-with-abuse-rate-limits

**Specifically**: Make requests for a single user or client ID serially. Do not make requests for a single user or client ID concurrently.

We should alter the proxy so that it never sends concurrent requests for the same token, but does allow concurrent requests if they are for different tokens. This concurrency level should be configurable.

We'll need to update our `src_github_rate_limit_remaining` metric, but we probably don't want to increase the cardinality based on tokens.

**Comment by ryanslade** [comment]
I believe we can use a map of semaphores like this, using the token as the key:

```go
type keyedSemaphore struct {
	concurrency int

	mu    sync.Mutex
	chans map[string]chan struct{}
}

func newKeyedSemaphore(concurrency int) *keyedSemaphore {
	return &keyedSemaphore{
		concurrency: concurrency,
		chans:       make(map[string]chan struct{}),
	}
}

// Take blocks until we can proceed.
// The caller is expected to always call Put when done.
func (k *keyedSemaphore) Take(key string) {
	k.mu.Lock()
	c := k.chans[key]
	if c == nil {
		c = make(chan struct{}, k.concurrency)
		c <- struct{}{}
		k.chans[key] = c
	}
	k.mu.Unlock()
	<-c
}

func (k *keyedSemaphore) Put(key string) {
	k.mu.Lock()
	c := k.chans[key]
	if c == nil {
		panic("Put called before Take")
	}
	k.mu.Unlock()
	c <- struct{}{}
}
```

**Comment by tsenart** [comment]
This could be useful here: https://pkg.go.dev/golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/semaphore

**Comment by ryanslade** [comment]
Related project:  https://github.com/kubernetes/test-infra/tree/master/ghproxy 

(Thanks @daxmc99)

**Comment by ryanslade** [comment]
I'm not convinced we need this until we start seeing contention on the mutex, at the moment it's not an issue:

https://sourcegraph.com/-/debug/grafana/d/github-proxy/github-proxy?viewPanel=100000&orgId=1&from=now-6h&to=now
