### ISSUE TITLE
campaigns: use a custom User-Agent for src-cli requests

### ISSUE THREAD

**Issue by LawnGnome** [sourcegraph/sourcegraph#15769]
Currently, the default `Go-http-client/2.0` is used, but it would be nice if src-cli could identify itself for usage tracking purposes.

**Comment by aisbaa** [comment]
I'd love to see this implemented. I'd suggest using `src-cli/3.21.9` or `sourcegraph-cli/3.21.9`. This would help us to differentiate human and bot users.

**Comment by christinelovett** [comment]
https://app.hubspot.com/contacts/2762526/company/464956351
