### ISSUE TITLE
campaigns: src-cli cannot handle mount mismatches in Docker-in-Docker setups

### ISSUE THREAD

**Issue by LawnGnome** [sourcegraph/sourcegraph#15772]
The scenario:

* `src-cli` is run within a Docker container (container `a`) that has the Docker socket bind mounted in so it can run Docker commands.
* A shared volume is mounted into the `src-cli` container from the host, with the intention being that this can then also be mounted into whatever containers `src-cli` spawns to run campaign steps.
* The volume is in a _different_ filesystem path on the host and in container `a`: for example, on the host the volume is at `/var/lib/docker/volumes/foo`, but within container `a` it's mounted at `/bar`.
* `src-cli` is run with  `-cache` and `-tmp` pointing at `/bar` (or a subdirectory of `/bar`).

When `src-cli` tries to invoke `docker run`, it sets up the bind mount with something like `--mount type=bind,source=/bar/repo/workspace,target=/tmp/tmp.XYZ`, but the command fails because the Docker daemon on the host only has that source at `/var/lib/docker/volumes/foo`.

We'll need to either figure out a way to detect this, or provide a flag for the user to specify the mapping, or _insert idea here_.

**Comment by eseliger** [comment]
What if we didn't bind-mount the script, but instead create a volume and cp the file onto the volume using a small utility container?

```bash
VOL_ID=$(docker volume create -d local)
CONTAINER_ID=$(docker run -d --rm --mount 'type=volume,src=$VOL_ID,dst=/script-vol alpine:3.10)
docker cp path_to_script $CONTAINER_ID:/script-vol/script.sh
docker stop $CONTAINER_ID
docker rm $CONTAINER_ID
```

That way, it would work the same across all systems. Also, small benefit: it doesn't store the script directly in the tmp dir of the host system, which we might need to encrypt at some point when we would decide to run on a shared runner (?)

**Comment by mrnugget** [comment]
Is it possible to specify the host paths as `-tmp` and `-cache`? So instead of running

> src-cli is run with `-cache` and `-tmp` pointing at `/bar` (or a subdirectory of `/bar`)

you run src-cli with `-cache` and `-tmp` pointing at `/var/lib/docker/volumes/foo`.

**Comment by malomarrec** [comment]
We agreed that we are not going to do it this year, most likely.
Closing for now, will re-open if this is less infrequent than we thought.
