### ISSUE TITLE
Support pattern quantifiers for AND operation

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#15777]
More of a note-to-self, this is not high priority right now. I added `and` for patterns, but we don't support qualifying these subexpressions with `case` or `patterntype`. It would be nice if we did. We currently treat `and` synonymous with space-separated values (atoms), but in this case, `and` is an operation on two subexpressions, so the semantics (and transformation/reduction of `and` operations on subexpressions) would need to come into play.

<img width="741" alt="Screen Shot 2020-11-13 at 8 55 55 PM" src="https://user-images.githubusercontent.com/888624/99139061-b8f04700-25f2-11eb-8ce0-d36f48868d31.png">

/cc @sourcegraph/search-platform

**Comment by camdencheek** [comment]
@rvantonder it looks like this [works fine now](https://sourcegraph.com/search?q=context:global+%28case:no+abd%29+or+%28case:yes+ABC%29&patternType=literal). Is it safe to close this?

**Comment by jtibshirani** [comment]
We don't plan to implement this -- it hasn't come up as a use case, and it'd add complexity to parsing. Closing it out.
