### ISSUE TITLE
Changeset filtering

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#15783]
We are not going to implement a full search DSL for now; instead we're going to reconcile the dropdowns with [the design](https://www.figma.com/file/MxlqIj1eHeLrqr1BWGIXlL/Changeset-filter-design-%2316780?node-id=0%3A1&viewport=2732%2C1046%2C1) and add the new KPI icons above the changeset list.

**Comment by LawnGnome** [comment]
This ticket accidentally morphed, and is now a duplicate of #16960.
