### ISSUE TITLE
Changeset text search

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#15781]
Allow to search through changesets based on
- title
- repo name

Therefor, we should implement the search bar we talked about this summer that will eventually also allow for a search syntax that unifies filtering and searching.

Tasks:

- [x] Extend `campaigns.Store` to allow `ListChangesets` with a `TextSearch: "foobar"` option that creates a query that searches through the changeset title, the name of the repository
- [x] Extend the GraphQL schema to allow filtering changesets based on text search, e.g.: `changesets(search: "foobar"): ChangesetConnection!`
- [x] Extend UI to have a text box that allows to search for changesets using this API

**Comment by chrispine** [comment]
Needs some design @rrhyne
