### ISSUE TITLE
Update extensions to use Sourcegraph proxy for CORS requests

### ISSUE THREAD

**Issue by jeanduplessis** [sourcegraph/sourcegraph#15794]
## Overview
The CORS proxy has been redeployed at https://cors-anywhere.sgdev.org - It has the features described in https://github.com/sourcegraph/sourcegraph/issues/15582.

Namely, added x-forwarded headers and a simplistic rate-limiter.
The ALLOW_LIST is unchanged: `https://registry.npmjs.com,https://skimdb.npmjs.com,https://api.npmjs.org,https://api.godoc.org,https://sentry.io/api`

## Requirement
We should update the extensions configuration to no longer point to the Heroku proxy we used, but to our own proxy URL: https://cors-anywhere.sgdev.org

**Comment by felixfbecker** [comment]
I just realized that the ALLOW_LIST needs to be expanded before we can switch to this proxy - as long as it's not including Sonarcloud and Snyk in the ALLOW_LIST it wouldn't help those extensions.

**Comment by felixfbecker** [comment]
https://github.com/sourcegraph/deploy-sourcegraph-dot-com/pull/3956
