### ISSUE TITLE
Code search hangs until I restart sourcegraph

### ISSUE THREAD

**Issue by sabyasachi** [sourcegraph/sourcegraph#1579]
- **Sourcegraph version:** 2.13.5 
- **Platform information:** 
- OS version: 
`$ cat /etc/centos-release`
CentOS Linux release 7.5.1804 (Core)
`$ uname -a`
Linux localhost.localdomain 3.10.0-123.el7.x86_64 #1 SMP Mon Jun 30 12:09:22 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
- Cloud provider: NA
- Web browser version: Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)
- Docker version: 
`$ docer version`
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-75.git8633870.el7.centos.x86_64
 Go version:      go1.9.4
 Git commit:      8633870/1.13.1
 Built:           Fri Sep 28 19:45:08 2018
 OS/Arch:         linux/amd64
Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-75.git8633870.el7.centos.x86_64
 Go version:      go1.9.4
 Git commit:      8633870/1.13.1
 Built:           Fri Sep 28 19:45:08 2018
 OS/Arch:         linux/amd64
 Experimental:    false

Reproducible in both OS:  OS X and CentOS.

#### Steps to reproduce:

1. I have around around 8 repositories added in SourceGraph.
2. After starting the SourceGraph server, it works fine for couple of hours. Then search requests starts taking forever (basically hangs). Then if I go to any other page, they also just show "Loading". 
3. I kill and restart SourceGraph docker after waiting for 30 mins. 
4. Works again for a while.

#### Expected behavior:
Should not have to restart once in a while.

#### Actual behavior:
See above.

**Comment by sqs** [comment]
Thanks for reporting this and sorry you are experiencing it. We haven’t received reports of this happening before, but I have a couple ideas for further investigation. 

1. What does `docker top` on the Sourcegraph container report? (Any long-running git processes would be likely culprits.)
1. Does the container have any other log messages during the time it is unresponsive?
1. When it is unresponsive, can you still visit non-repo pages such as your user profile?

**Comment by sabyasachi** [comment]
1. You mean output of docker top [contain-id]? These are few long running jobs. Otherw were under 1 minute.
```
root                26314               26287               0                   Jan02               ?                   00:03:08            lsp-proxy
root                26316               26287               0                   Jan02               ?                   00:06:09            frontend
root                26319               26287               0                   Jan02               ?                   00:00:00            /bin/sh -c exec redis-server /etc/sourcegraph/redis.conf | tail -n 1
root                26320               26319               0                   Jan02               ?                   00:04:30            redis-server /etc/sourcegraph/redis.conf
root                26321               26287               0                   Jan02               ?                   00:00:22            github-proxy
root                26323               26287               0                   Jan02               ?                   00:00:32            zoekt-sourcegraph-indexserver -sourcegraph_url http://127.0.0.1:3090 -index /var/opt/sourcegraph/zoekt/index -interval 1m -listen 127.0.0.1:6072
root                26325               26287               0                   Jan02               ?                   00:01:45            repo-updater
```

2. I could see logs containing:
`11:56:50         lsp-proxy | DEBUG window/logMessage Parsing <filepath> {<...>}`

3. The situation is random. Sometimes after a while it starts working, sometimes it doesn't. When it is unresponsive, I can not visit non-repo pages.

**Comment by christinaforney** [comment]
Hey @sabyasachi - I'm going to close this out assuming that upgrading to 3.0+ solved this issue for you. If you are still having trouble don't hesitate to let us know and we can reopen.
