### ISSUE TITLE
User-added repos do not stay indexed on Sourcegraph.com

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#15820]
I added a user repo on Sourcegraph.com, and it gets indexed:

![Screen Shot 2020-11-16 at 2 38 29 PM](https://user-images.githubusercontent.com/888624/99311313-a441c800-2819-11eb-85cf-478f96f59d4b.png)

Shortly after (like 1 minute), it gets unindexed/the index disappears:

![Screen Shot 2020-11-16 at 2 38 39 PM](https://user-images.githubusercontent.com/888624/99311334-ac016c80-2819-11eb-8666-49c993448a52.png)

If I go to my repos and add it again, and update, it indexes again and then disappears again. I don't know if this is the case for all repos (some of the others I added stay indexed).

**Comment by rvantonder** [comment]
cycled again after 10 mins:

![Screen Shot 2020-11-16 at 2 47 43 PM](https://user-images.githubusercontent.com/888624/99312082-bf610780-281a-11eb-94f9-dfe3f5196a1a.png)

![Screen Shot 2020-11-16 at 2 47 49 PM](https://user-images.githubusercontent.com/888624/99312094-c2f48e80-281a-11eb-85d9-53877688647f.png)

**Comment by rvantonder** [comment]
Final update about behavior I'm seeing: when I update my manage repositories for repos, it seems it retriggers an index. When it's indexed, it says the last update was 5 hours ago (i.e., the time it was first indexed). Then after a couple of minutes it gets unindexed again. So somehow after it reindexes, it knows about the old update. You can probably replicate this by adding

`Workiva/w_flux` to your repos, see it gets indexed, wait 5 or 10 minutes, refresh the repo page, and see that it is no longer indexed. I don't know if the reindexing is because of a particular repo trait, because my other repos seem to not be unindexed/reinduxed.

**Comment by tsenart** [comment]
@ryanslade: Just a gut feeling: This might have something to do with #15797, since the SQL query that lists repos to index relies on that table.

**Comment by ryanslade** [comment]
I've managed to reproduce another strange case a couple of times:

1. Go to a random `workiva` repo, check that it's indexed, it is. 
2. Find something in the repo to search for.
3. Search for it from the main search page, it finds it.
4. Try again, not found
5. Look at index status, now says `
master — initial indexing in progress`

**Comment by ryanslade** [comment]
When checking a repo owned by both a user external service and our public external service I can confirm that there are two rows in `external_service_repos`

When I browse to the repo and check `external_service_repos` again, we now only have one row pointing at the public external service in `external_service_repos`.

If I force a sync of the user external service again the second row is added back.

So, visiting a repo removes the relationship with user added external services, most likely due to lazy syncing.
