### ISSUE TITLE
Command palette ≡ icon is injected with no spacing on GitHub when unauthed

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1584]
When you are not logged into GitHub, the command palette's <kbd>≡</kbd> icon has no right margin between it and **Why GitHub?**. When you hover over it, its border is flush with the W in **Why GitHub?** There should be spacing.

(BTW, it is desirable for the icon to be here rather than on the right-hand side, to avoid jitter after the page loads and the icon is rendered.)

![screenshot from 2018-12-30 05-32-42](https://user-images.githubusercontent.com/1976/50546858-63744200-0bf4-11e9-8732-8d33cf0ab48c.png)

**Comment by felixfbecker** [comment]
Fixed
