### ISSUE TITLE
Browser extension: clipped content in popover when the "you're on Sourcegraph Cloud" alert is displayed

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#15878]
- **Sourcegraph version:** Browser extension v20.11.17.1425

#### Steps to reproduce:

1. Navigate to sourcegraph.com
2. Open the popover

#### Expected behavior:

Popover content is not clipped.

#### Actual behavior:

Bottom links ("Sourcegraph Cloud", "Documentation") are clipped.

![image](https://user-images.githubusercontent.com/1741180/99420611-b4cb6e80-28fd-11eb-9414-2bcca4c6d116.png)

**Comment by Joelkw** [comment]
@lguychard this is a problem either way, but wanted to confirm the behavior you are seeing – are the contents just clipped for you and you can't scroll to reveal them, or are you able to scroll? (I can scroll in this [loom](https://www.loom.com/share/eb605510c13f414cb8a2dcd0355b68f1)).

**Comment by marekweb** [comment]
I assume that this is because the pop-up viewport itself has a max height and I don't know if we can control it.

Does scrolling work? When I reproduce this, I'm able to scroll the contents.

If so, would you agree that from a UX point of view, the problem can be stated as:

- "The popover contents get clipped and it's not apparent that it can be scrolled."
- Or: "The popover contents get clipped and regardless of ability to scroll, the clipping behavior is non-intuitive / bad usability"

**Comment by felixfbecker** [comment]
Yeah I think I remember looking at this and finding that the popup cannot be larger. It just happens to be that with other content it's below the max size. So the only "fix" would be to redesign the popup to stay within the max-height.

**Comment by AlicjaSuska** [comment]
**Solution**

[Figma](https://www.figma.com/file/V5t7KOzC6PIX75L4dz8IFc/RFC-221-Browser-extension-improve-discoverability-and-awareness-Approved?node-id=1316%3A1440)

In this particular case, the bottom margin of the 'You're on Sourcegraph' banner is 32px, which should be 16px. Please, fix this detail.

When it comes to clipping content we have even longer states (ex. '[Private repository](https://www.figma.com/file/V5t7KOzC6PIX75L4dz8IFc/RFC-221-Browser-extension-improve-discoverability-and-awareness-Approved?node-id=397%3A524)' banner) so we cannot avoid it 100%. My proposition is to:
- add a scroll bar to indicate that there is more content. See the [design](https://www.figma.com/file/V5t7KOzC6PIX75L4dz8IFc/RFC-221-Browser-extension-improve-discoverability-and-awareness-Approved?node-id=1316%3A1440) for more details.
- Fix the header and the footer of this window so they do not scroll with the content

@Joelkw Please, review :) thank you!

![browser-extension-issue](https://user-images.githubusercontent.com/20326070/102888590-64de4b00-4459-11eb-9eac-614c4509a59c.png)

**Comment by Joelkw** [comment]
@AlicjaSuska I think this is a good solution! Left some minor comments on the figma but reviewing this as "done."

**Comment by ryankscott** [comment]
We looked into this and cannot reproduce this. If this issue comes up again, please create an new issue.
