### ISSUE TITLE
Display user analytics according to instance server date/time 

### ISSUE THREAD

**Issue by chrislovett03** [sourcegraph/sourcegraph#15876]
Currently our analytics displays to the user against our timetable, this creates confusion over user statistics of those sourcegraph instances hosted in different timezones. 

Admins are seeing activity on days when there are no active users. 

https://app.hubspot.com/contacts/2762526/company/1749054227 would like their usage statistics to display according to their server date/time

**Comment by tsenart** [comment]
@sourcegraph/cloud: Any takers?

**Comment by asdine** [comment]
The GraphQL API seems to be sending the right time, but the frontend code adds 24 hours to that date: https://github.com/sourcegraph/sourcegraph/blob/45f9839011ac5df56d1cb07dfa09c7749dd26084/client/web/src/site-admin/SiteAdminUsageStatisticsPage.tsx#L51-L51 but I lack some context, perhaps @dadlerj or @felixfbecker would know?

**Comment by felixfbecker** [comment]
I have no idea. It blaims to @dadlerj: https://github.com/sourcegraph/sourcegraph/commit/c0c9831aa4979cc95e15a72d6eac03598ea5c825#diff-01453ff38ffb903c16c1679717a948b1f5515b8670c4bad202003ab3eba9c303R54
(who's on vacation atm)
