### ISSUE TITLE
monitoring: remove JSONNET, internal dashboards from Grafana image

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#15875]
From https://github.com/sourcegraph/about/pull/2000#discussion_r524803355:

> Remove the current custom dashboards shipped with the Grafana image to drive eventually "promoting" experimental dashboards to generator dashboards in order to get them shipped out-of-the-box, and to have more impetus to improve the generator to enable this if required (to avoid becoming increasingly dependent on raw dashboards)

To make sure we do not break anyone's workflows, the existing internal dashboards should be migrated during https://github.com/sourcegraph/sourcegraph/issues/15873 (so this is kind of blocked until that is done)

I feel like we should drop the JSONNET dashboards as part of this too - they contribute significantly to Grafana image build times, I'm not sure they see much use, and we should standardize on the #15873 approach for creating dashboards. Maybe those could be migrated to ConfigMap'ed dashboards

**Comment by bobheadxi** [comment]
Reopening because https://github.com/sourcegraph/deploy-sourcegraph-dot-com/pull/4107 was reverted in due to an oversized generated ConfigMap in https://github.com/sourcegraph/deploy-sourcegraph-dot-com/pull/4120 - we will need to reapply those changes before closing this out

cc @pecigonzalo

**Comment by pecigonzalo** [comment]
I possible workaround, although Im not in love with it, would be to use something like https://github.com/kiwigrid/k8s-sidecar/blob/master/example.yaml as init to pull all the dashboards and we can then specify the dashboards in multiple files and group them by label.

**Comment by bobheadxi** [comment]
I think that might be complicated, due to deploy-sourcegraph-dot-com being a private repo 🤔

**Comment by pecigonzalo** [comment]
It does not grab the dashboards from GH, it grabs them from configMaps.

**Comment by bobheadxi** [comment]
Doesn't this part work by grabbing things from GitHub? https://github.com/kiwigrid/k8s-sidecar/blob/master/example.yaml#L62

**Comment by pecigonzalo** [comment]
I think it can do both, the ConfigMap itself containing the config is discovered dynamically and it could contain a raw dashboard as well.

**Comment by bobheadxi** [comment]
Closed by https://github.com/sourcegraph/sourcegraph/issues/15875
