### ISSUE TITLE
Move aggregated repository statistics to critical telemetry

### ISSUE THREAD

**Issue by ebrodymoore** [sourcegraph/sourcegraph#15883]
Aggregated repository statistics (lines of code and size of git repositories stored) should be in the [critical telemetry bucket](https://docs.sourcegraph.com/admin/pings#critical-telemetry) of pings as we need this for billing purposes. [Slack conversation here](https://sourcegraph.slack.com/archives/CU93UDUBV/p1605543777498400).

@keegancsmith assigned this to you since you had the original repo stats pings, but I know you've been floating so please push this onto another team if this isn't you! 😄

**Comment by keegancsmith** [comment]
@tsenart any scope for cloud team to tackle this?

**Comment by ebrodymoore** [comment]
Thanks @unknwon!! 🙏
