### ISSUE TITLE
Display source or source library on hover

### ISSUE THREAD

**Issue by hillba** [sourcegraph/sourcegraph#1589]
#### Feature request description. 
It would be great if Sourcegraph could display the source library in the hover tooltip when users are hovering over a particular function. 

#### Is your feature request related to a problem? If so, please describe.
When reviewing team members' code, or exploring a new codebase, it can sometimes be onerous to find the initial definition/declaration of a function and/or determine whether or not a function is being imported or is defined somewhere else in the current file I'm reading. 

#### Describe alternatives you've considered.
Users can scroll to the top of a file, and check a function against a list of imports to determine whether or not the function was defined in the current file, or do a browser search. Displaying the source library in the tooltip could increase developer efficiency and reduce friction when developers are exploring a new codebase or doing code review on a piece of functionality they are less familiar with.

#### Additional context
This isn't a great example, since the file is relatively small. However, Sourcegraph could simply display the source library in the tooltip and prevent developers from scrolling through files or browser searching.

![image](https://user-images.githubusercontent.com/45243796/50551380-841cb600-0c4d-11e9-9368-7419443e745e.png)

**Comment by sqs** [comment]
Thanks, this is a great feature request. It would be fairly easy to show this whenever Sourcegraph knows the definition location (which it does if the "Go to definition" button is showing).

Can you add a comment here when you encounter other specific situations where this would be helpful? (Anyone else reading this is also welcome to do so.) This would help us better understand the use case and come up with the best solution.

Also, I have a question about the screenshot you posted. It shows the definition of `callAPIMiddleware`. You want to see source/library info in the hovers in your own code when it calls `callAPIMiddleware`, right? (Not add'l info in the hover shown in the screenshot.)

**Comment by hillba** [comment]
Here's a specific example encountered today, 

I'm examining an area of my company's codebase, so that I can understand the architecture of a particular service and subsequently build a new feature. I encounter a function `request_tiles`, to which `tile_ids` is being passed in. This could be an internal function, or one that we import from another Python library. It would be helpful to know immediately what the source library is for this function (without necessarily needing to 'go to definition'), because our internal structure for `tile_ids` is specific to our organization. If there could be a way for me to very rapidly assess whether or not this function is internal, it could help me to more rapidly understand how data is being passed through this service.
