### ISSUE TITLE
Changeset events for gitlab merge and close events not inferrable from notes

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#15899]
For GitLab, we don't get a "timeline" via the API like we do for github, so we rely on gitlab system notes to sanitize the events we care about. While for the webhooks we do have sanitization of merged/closed events in place, we don't do so for the notes. That is, because GitLab doesn't return those in the list of notes, albeit they exist in the rendered UI. The only two options I see at this point are:

The simple, quick, dirty and ugly one:
- Sanitize the merged event based on the merged_at and merged_by fields from the MergeRequest API response (since merge is a one-way road, no "un-merge" can happen and this is safe)
- Sanitize the closed event based on closed_at and closed_by (this is not ideal, because we would overwrite historic state on reopen/close again and would not be able to reconstruct the whole timeline of the MR, especially for imported ones)

The hard, slow, clean and ugly one:
Parse the HTML rendered by gitlab directly, and use those events. It works somewhat well and might be somewhat easy to detect breakage using a nightly run script test (in case of DOM changes). P o c:
![image](https://user-images.githubusercontent.com/19534377/99475129-31863900-294e-11eb-98ec-b6bd672bb715.png)
(But that could mean that API tokens aren't enough anymore (probably can't access rendered HTML with an API token?))

I checked the GraphQL API as well and it seems like that one also doesn't reveal the information we need.

**Comment by chrispine** [comment]
Have we reached out to Gitlab to ask them how they would like us to accomplish this? If not, we should do this.

**Comment by eseliger** [comment]
On a boring Saturday I looked through the api docs and discovered they added an API in 13.2 4 months ago which we can use. The attached draft PR implements this and works as expected.
