### ISSUE TITLE
Clone progress screen doesn't refetch anymore

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#15903]
The clone view on a repository page used to refetch constantly to display the latest state of gitserver. This doesn't seem to be the case anymore. I've seen this two times now in the past weeks, but both times I didn't have a browser console open, so not sure if there are any errors thrown.

![image](https://user-images.githubusercontent.com/19534377/99486048-dbbc8b80-2963-11eb-884b-6ffeaac9701e.png)

**Comment by jasongornall** [comment]
closing feel free to reopen if this is still happening
