### ISSUE TITLE
Advertise webhook support more prominently

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#15900]
Webhooks are ought to make campaigns a lot faster and responsive, while taking off load from the API because we don't need to constantly resync changesets. It was hard for me to find a section on how to set them up when I wanted to link a customer to it and I didn't see it anywhere in the campaigns section of the docs. After a search I almost gave up on because it seemed to not find what I was looking for, I went to look at a result I suspected might also talk about that (and that is from my perspective as a Sourcegraph person). We should probably advertise it more prominently
- In the docs, like a "How to make your instance ready for campaigns" section for site-admins
- In the app, for site-admins? But not sure where.

**Comment by mrnugget** [comment]
Just so it's collected in this ticket, here are the code-host-specific webhook guides:

- https://docs.sourcegraph.com/admin/external_service/github#webhooks
- https://docs.sourcegraph.com/admin/external_service/gitlab#webhooks
- https://docs.sourcegraph.com/admin/external_service/bitbucket_server#webhooks

**Comment by malomarrec** [comment]
Closing in favor of #21890
