### ISSUE TITLE
gqltest: add a test to cover repository with space in its name

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#15905]
Example "Other" external service config:

```json
{
  "url": "https://<username>:<password>@sourcegraph.visualstudio.com/sourcegraph/_git/",
  "repositoryPathPattern": "sourcegraph.visualstudio.com/{repo}",
  "repos": [
    "Test%20Repo"
  ]
}
```

Follow up of #15745

**Comment by unknwon** [comment]
@felixfbecker do we have a team account on sourcegraph.visualstudio.com/sourcegraph or it's on your personal namespace? I'm trying to avoid using personal accounts for testing credentials.

**Comment by felixfbecker** [comment]
It's like a GitHub org. I don't have permissions to add users, only @sqs has. He can add you under https://sourcegraph.visualstudio.com/_settings/users
