### ISSUE TITLE
Changes to search query may be overridden by GlobalNavbar query update logic (racy)

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#15921]
The `search suggestions` regression test [is failing](https://github.com/sourcegraph/sourcegraph/issues/15178#issuecomment-729609488), with the search suggestions widget failing to show at [this step](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/regression/search.test.ts#L534:1).

Running the tests locally, I noticed that while the suggestions widget was initially shown, shortly after the [`jwtmi ` keyboard input](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@00c88f2e486dc5a9bb3aa4c42c85f399e9feac9c/-/blob/client/web/src/regression/search.test.ts#L531:1) was erased, and the suggestions widget was hidden.

I tracked this down to the [query update logic in `<GlobalNavbar/>`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@00c88f2e486dc5a9bb3aa4c42c85f399e9feac9c/-/blob/client/web/src/nav/GlobalNavbar.tsx#L118-141), which was added to fix another critical issue in #13954. Any query changes from user input occurring between a location change and the execution of this `useEffect` block would be erased.

**Comment by eseliger** [comment]
@pecigonzalo this broke the global search bar and seems to be in the release.

**Comment by pecigonzalo** [comment]
@lguychard could you review?
