### ISSUE TITLE
Make repo update schedule configurable

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#15926]
Currently we backoff based on a simple heuristic:

https://github.com/sourcegraph/sourcegraph/blob/320870aca21f1194446e0e9c034a8843c553ed22/cmd/repo-updater/repos/scheduler.go#L197-L202

Some customers would prefer if we could specify a fixed backoff, perhaps we can add optional site config to allow this?

**Comment by christinelovett** [comment]
https://app.hubspot.com/contacts/2762526/company/578600789

https://app.hubspot.com/contacts/2762526/company/1686989427

**Comment by christinelovett** [comment]
Customer requested option to target repogroups in addition to individual repos in the coming refresh update settings.

**Comment by christinelovett** [comment]
Hey @ryanslade is there any update on this work? It's a hard requirement for customer to configure the update schedule per repo group. With a large number of repos (12K) it's essential to the functionality. Is it possible for this to be made available in the API before work makes it to the UI?

**Comment by tsenart** [comment]
@christinelovett: @ryanslade is on vacation until next week. Can you share why the customer needs different refresh intervals per repo group? What's the underlying thinking?

**Comment by christinelovett** [comment]
Hey @tsenart - for that particular set of 12k repos, they want to ensure that the index is always up to date in Sourcegraph. All of these repos represent their monorepo. It's ideal for them to use heuristics by default for most repos, but state intervals via webhook for all repos in a given group (specifically, the repogroup representing the monorepo).

**Comment by tsenart** [comment]
> Hey @tsenart - for that particular set of 12k repos, they want to ensure that the index is always up to date in Sourcegraph.

Do you mean they want to ensure the repo clone in Sourcegraph is always up to date? The search index is a separate thing.

> but state intervals via webhook for all repos in a given group

What do webhooks have to do with this? Can you clarify?

>  (specifically, the repogroup representing the monorepo).

We don't have a concept of repo groups in code host connection configuration. What does this refer to? Can they share their code host connection config? Also, if it's a monorepo, isn't that single repo in Sourcegraph?

**Comment by christinelovett** [comment]
Yes - they want to ensure it is always up to date. They have an irregular repo structure so the "monorepo" is not actually a single repo on Sourcegraph. 

The thought was to set disableAutoGitUpdates to true and configure up a webhook that calls at their desired interval: `curl -XPOST -H 'Authorization: token $ACCESS_TOKEN' $SOURCEGRAPH_ORIGIN/.api/repos/$REPO_NAME/-/refresh`

If this webhook could be extended to support $REPO_GROUP - that would simplify the task. If this work made it to the UI that would be great, but it feels like the quickest win is to make the webhook available.

**Comment by tsenart** [comment]
@christinelovett: Repo groups have nothing to do with code host connections unfortunately — they are only used in the UI, for search.

> They have an irregular repo structure so the "monorepo" is not actually a single repo on Sourcegraph.

How is this represented in the code host connection configuration? Can you share that (anonymized, or via Slack in the #cloud channel).

> If this work made it to the UI that would be great

It shouldn't be much work after we understand the requirements more precisely. We need to understand how the different monorepo subtrees are converted into different repos in Sourcegraph, so sharing the above info would go a long way.

**Comment by tsenart** [comment]
Talked with @christinelovett over Slack. Adding another configuration field to the external service config should do the trick. Something like:

```json
"gitUpdateInterval": {"foo/.*": "1h", "bar/.*": "1d", "default": "8h"}
```

**Comment by ryanslade** [comment]
We should be able to add this to the external service config and fall back to the site config value instead of defining a new default.

**Comment by ryanslade** [comment]
@christinelovett Please see the description here for what we've implemented: https://github.com/sourcegraph/sourcegraph/pull/16765

This will go out at part of our next release.

**Comment by christinelovett** [comment]
Awesome! Thanks @Ryan Slade <rslade@sourcegraph.com> :-)
