### ISSUE TITLE
Improve getting started with campaigns documentation

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#15931]
Improve campaigns introduction page to provide the high-level view of system architecture and relevant items from the product marketing document.

**Comment by malomarrec** [comment]
@rrhyne do you think we should close this? Seems that it's been tackled by the high level [overview](https://docs.sourcegraph.com/batch_changes/explanations/how_src_executes_a_batch_spec).

**Comment by malomarrec** [comment]
Is this really a 2 day estimate? For now, given the priorities for this team, 2 days is a lot of investment but I'm also surprised this is so big @rrhyne what would this involve?
