### ISSUE TITLE
TypeScript syntax highlighting bug

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#15930]
https://sourcegraph.com/github.com/felixfbecker/dom-to-svg@4cb4bb3d6b23ccb1a6458ffb59037d848535330b/-/blob/src/element.ts#L158

Nothing special really going on in that statement but after that syntax highlighting is broken:

![image](https://user-images.githubusercontent.com/10532611/99569014-676c0180-29d0-11eb-8ad3-0a254c891471.png)

**Comment by felixfbecker** [comment]
Note also the `const` is wrong in L152. Maybe this has to do with the `??` syntax, which is fairly new.

**Comment by rvantonder** [comment]
<img width="1137" alt="Screen Shot 2021-03-18 at 3 22 24 PM" src="https://user-images.githubusercontent.com/888624/111705360-cb2afd80-87fd-11eb-83be-776f71673971.png">

It is the fixed after updating to more recent syntax definition. https://github.com/sourcegraph/sourcegraph/pull/19282
