### ISSUE TITLE
executor: Use expiring tokens

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#15942]
The executor, frontend, and executor-queue share an auth token to communicate with each other from different networks. In order to reduce the risk of this token leaking, we should auto-generate one to be sent back to the executor with a one-use lifetime and a TTL. In the case that we fail to scrub the token from the log contents (see https://github.com/sourcegraph/sourcegraph/issues/15940), it will have no use for a malicious actor, as they will only see it by the time it has already been consumed.

**Comment by efritz** [comment]
Thanks @eseliger for the suggestion!

**Comment by Piszmog** [comment]
Closing in favor of #46171 (Job specific tokens)
