### ISSUE TITLE
Update the Find References toolbar UI ("Hide references from other repositories," "Ungroup by file")

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#15951]
![image](https://user-images.githubusercontent.com/11967660/99605895-7b5a3800-29bd-11eb-85b8-03ced27ce764.png)

The link buttons for "Hide references from other repositories," "Ungroup by file" feel like they're in a bad, non-obvious place. It seems like an easy solution could be to just move them to the left, since all the other UI for this feature is on the left, rather than keeping them far away on the right. 

Split out of #15630, where @slimsag noted "The placement of "Show references from other repositories" and "Ungroup by file" seems really weird to me as well, it takes up a lot of space in what is already a very small viewport."

**Comment by felixfbecker** [comment]
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/9740

**Comment by Joelkw** [comment]
Closing; copied relevant feedback to the duplicate ticket.
