### ISSUE TITLE
authz: change the way to get/set providers without global state

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#15962]
Authz privders are now stored in a global state list, it is very easy to forget to initialize them in a new service and "mysteriously" blocking the database access (we enforce authz in DB layer).

**Comment by tsenart** [comment]
Cough cough, dependency injection.

**Comment by unknwon** [comment]
Cleaning up old/stale/fixed issues, please feel free to reopen if you think it's worth keeping.
