### ISSUE TITLE
Can't see search filters in UI

### ISSUE THREAD

**Issue by evanweible-wf** [sourcegraph/sourcegraph#15988]
- **Sourcegraph version:** 3.21.2
- **Platform information:** Chrome 86, Mac

#### Steps to reproduce:

1. Search for something include some filters like `repo:foo` and `lang:dart`

#### Expected behavior:

Previously, the filters would be taken out of the search field and shown as controls just below so that you can edit/remove each one.

#### Actual behavior:

I no longer see these filters anywhere except the URL after I've searched. For example, searching for `/search?q=.canUserAccess+repo:wdesk_sdk+lang:dart+&patternType=literal` gives me the following UI:
![Screen Shot 2020-11-19 at 9 03 25 AM](https://user-images.githubusercontent.com/1738457/99699611-fe73a080-2a46-11eb-96a5-8a9ee4f38ef4.png)

Other users at my org do see the filters in the UI, as expected, so I'm not sure what the difference is.

**Comment by evanweible-wf** [comment]
Clearing site data fixed this issue. If I'm able to reproduce again, I'll try clearing localStorage entries one-by-one to see if I can find out which one, if any, caused it.

**Comment by Qmando** [comment]
I seem to have hit this issue too. I was able to fix it after removing the local storage entry `sg-search-mode: interactive`

**Comment by lguychard** [comment]
The flag that caused this issue no longer exists.
