### ISSUE TITLE
Recent search query text not always preserved (some characters can get erased)

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#15995]
- Enter a query like `repo:sourcegraph\.com/[a-z]+`
- Search
- Go to search page with recent searches and see `repo:sourcegraph\.com/[a-z]+`
- Click it, erases the trailing `+` in search.

![erase+1](https://user-images.githubusercontent.com/888624/99735239-7e1e6100-2a81-11eb-9592-3ba7d5778f62.gif)

Probably some encoding issue, should take care of any special syntax (not sure how else this can crop up).

**Comment by fkling** [comment]
We don't have recent searches atm.
