### ISSUE TITLE
Repo stuck in indexing state 

### ISSUE THREAD

**Issue by christinelovett** [sourcegraph/sourcegraph#15992]
3.21.2- Kubernetes 
Gitolite repository

After recently upgrading from 3.17 to 3.21.2, a 7.66 gb heavily-trafficked monorepo is stuck in "indexing" state 

Logs from indexed-search pod:

2020/11/19 18:14:30 error indexing code.$customername.internal/mobile/ios@HEAD=157b2666cc9f8b2108f1623cf626ca43d2c67238: command [zoekt-git-index -submodules=false -incremental -branches
HEAD -file_limit 1048576 -parallelism 8 -index /data/index -require_ctags /data/index/.indexserver.tmp/tmpfriend-6-974167242/code.$customername.internal%2Fmobile%2Fios.git] failed: signal: killed
OUT:

They're only at 25% cpu so it doesn't appear to be resource related. Error persisted in indexed-search pod after restarting

https://app.hubspot.com/contacts/2762526/company/464956351

**Comment by aisbaa** [comment]
It is clearly a timeout issue:

```
2020/11/20 16:40:45 no output for 5m0s, killing [zoekt-git-index -submodules=false -incremental -branches HEAD -file_limit 1048576 -parallelism 42 -index /data/index -require_ctags /data/index/.indexserver.tmp/tmpfriend-6-846637191/REPO.git]
2020/11/20 16:40:45 error indexing REPO@HEAD=GIT_SHA: command [zoekt-git-index -submodules=false -incremental -branches HEAD -file_limit 1048576 -parallelism 42 -index /data/index -require_ctags /data/index/.indexserver.tmp/tmpfriend-6-846637191/REPO.git] failed: signal: killed
```

**Comment by keegancsmith** [comment]
`no output for 5m0s`. I think this is likely too harsh of a check at this scale. We intentionally added this check to avoid unexpected deadlocks (originally with ctags, but that has been fixed now). I think we need to increase the timeout much higher as a short term fix we can ship asap. Alternatively we need to improve how the binary communicates it is making progress. As long as it is making progress life is good, even if it may be slow/stalled.

@lguychard I can tackle this on Monday. Alternatively someone else can tackle it on the team and I can guide them.

**Comment by keegancsmith** [comment]
@christinelovett the customer can switch the `zoekt-indexserver` to this container `index.docker.io/sourcegraph/search-indexer:80740_2020-11-24_ccd94fe@sha256:89fa7d5eac6f9f3e8893a482650dffcea4d22be993328427679af7e3ddd08e10`

**Comment by aisbaa** [comment]
I've managed to find image hash `index.docker.io/sourcegraph/search-indexer:insiders@sha256:89fa7d5eac6f9f3e8893a482650dffcea4d22be993328427679af7e3ddd08e10` and it works! It did take 8min to index, which means 1G per minute.
