### ISSUE TITLE
campaigns frontend: number of entries in changeset list doesn't match numbers at top of view

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#16029]
When a changeset is "processing" or "errored" it is counted towards the unpublished count at the top:

![screenshot_2020-11-20_15 17 32@2x](https://user-images.githubusercontent.com/1185253/99810105-8939c580-2b43-11eb-9a96-2d68d93de65e.png)

But when it is `processing` or `errored` it doesn't show up in the list at the bottom:
![screenshot_2020-11-20_15 18 03@2x](https://user-images.githubusercontent.com/1185253/99810157-99ea3b80-2b43-11eb-8921-957f2967c975.png)

**Comment by rrhyne** [comment]
I think we just need to add and the status "error" at the top. Possibly processing as well?

**Comment by eseliger** [comment]
I think that would work. Can you update the responsive designs because I don't know how to stuff 8 things in 3 rows without it looking weird 😁 

Then the tasks here are:

- [ ] Introduce campaigns UI state in the backend (or an equivalent, at least, so we can fetch them)
- [ ] Add those two new types of stats to the gql API
- [ ] Add those types to the UI stats card

**Comment by rrhyne** [comment]
I believe this covers the requirements:

https://www.figma.com/file/S0608OCnkzSWmvK7Sy5kZ8/?node-id=0%3A1

**Comment by eseliger** [comment]
Ah, smart! I like that. 

We need one more for 'processing' though :)

**Comment by rrhyne** [comment]
The first image shows an added processing status and error status. Two options here: 

1) always show processing which will usually be 0
2) remove the processing status counter if we aren't processing anything


![image](https://user-images.githubusercontent.com/539268/100296773-f5e90180-2f41-11eb-892f-6fbb023d7982.png)

**Comment by eseliger** [comment]
I think I like hiding it, maybe same for error?
