### ISSUE TITLE
Document a compatibility matrix of campaigns

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#16034]
We currently don't explicitly state what versions of external code hosts are supported. Sometimes, customer run into issues because their code host is very outdated and we should have a source where we point them to.

**Comment by eseliger** [comment]
I think this ticket can actually only be closed after we conducted the testing. We should add some docs in this iteration, but the actual matrix is probably not possible before the codehost version QA is done.

**Comment by chrispine** [comment]
This is good enough for now; post QA testing, we will have more information for this
