### ISSUE TITLE
Deleting and "nuking" users as a site admin has scary usability

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#16035]
## The problem

In the user management section of site admin (`/site-admin-users`), we have two actions available:

- Delete user (soft delete)
- Nuke user (hard delete)

These are presented with almost-equal button styling:

<img width="273" alt="Screenshot 2020-11-20 at 17 22 28" src="https://user-images.githubusercontent.com/6304497/99823694-f7d34f00-2b54-11eb-843e-1353d8c494ef.png">

The tooltip for nuking a user is **terrifying** usability-wise:

<img width="318" alt="Screenshot 2020-11-20 at 17 19 52" src="https://user-images.githubusercontent.com/6304497/99823385-9ca15c80-2b54-11eb-93d0-ed5f94f3c1ad.png">

When the user clicks the either the "Delete user" or "Nuke user" button, they're presented with a browser alert to confirm:

<img width="400" src="https://user-images.githubusercontent.com/6304497/99823469-b93d9480-2b54-11eb-93d9-23e28caa0385.png">

We should improve this flow so it's less terrifying and more clear, and honestly, more sensitive.

## Proposed changes

First, I strongly recommend changing the name of these actions for clarity and sensitivity.

- ~Delete~ **Deactivate**
- ~Nuke~ **Delete**

_(Note: I understand that the implementation for soft delete almost certainly relies on a field like `deleted_at` or a `deleted_users` table, so renaming it to "Deactivate" can introduce incongruity, but this copy is user-facing while our database terminology is internal, so user-facing clarity wins out.)_

Second, we should update the buttons to communicate these actions more clearly. Since the rows in the UI are already quite packed, there's two options here, one quick and one a bit more involved. 

**The quick approach**: We replace the "Delete" button with a secondary button style with red text and a text label, and we replace the "nuke" icon with the trash can icon.

<img width="356" alt="Screenshot 2020-11-20 at 17 25 43" src="https://user-images.githubusercontent.com/6304497/99824263-ca3ad580-2b55-11eb-92e1-a6fd3458e963.png">

**The more involved approach**: We redesign the rows to better accommodate the content without using buttons for everything.

Third, we should replace the browser alert with our own modal with more purposeful copy that follows our [actionable language guidelines](https://about.sourcegraph.com/handbook/communication/content_guidelines/actionable_language#confirmation-messages), like so:

<img width="1200" alt="Screenshot 2020-11-20 at 17 54 29" src="https://user-images.githubusercontent.com/6304497/99827047-716d3c00-2b59-11eb-9076-5675ec065769.png">

Finally, I'd also submit a PR to update language on the docs page for [user data deletion](https://github.com/sourcegraph/sourcegraph/blob/main/doc/admin/user_data_deletion.md) to align all content.

Thanks @flying-robot for flagging this issue and talking through it!

**Comment by Joelkw** [comment]
@quinnkeast cc @flying-robot  thanks for calling this out proactively! This could fit into our web team's webapp goal, so I have some clarifying questions. 

First, re: priority – do we have any existing feedback on this, or have you come across any? I understand that this UI may be bad, but it may also be that this is a rarely-enough taken path (admin users only, and delete-desiring admins only) that we've been able to get away with it for now (so it might be lower priority than something that fixes a problem we have clear feedback that affects every single user). 

Second, do either of you know the history behind these names? I wonder if "delete" has some sort of legal implication re GDPR? I also wonder if there's a usability/use case history here, where people go through this process to avoid being billed for extra users they aren't using (I know some of our customers keep a close eye on this, as is totally fair they should), and would "deactivate" cause any problems or questions around billing? Would we need to update our billing / license agreements or docs to discuss deactivated users so it was clear?

**Comment by felixfbecker** [comment]
cc @slimsag who added this I think?

**Comment by unknwon** [comment]
Thanks for calling this out!

Just my feedback regarding terms:

I think "Deactivate" is not an appropriate term because that to me implies the user can later be "re-activated", which is not true (and it's hard because someone else could take the same username after the user has been marked as "deactivate"/soft-deleted).

**Comment by quinnkeast** [comment]
@Joelkw As @flying-robot says, it's less about having received feedback and more identifying a bad practice we should address when we have the chance. Like you say, we've gotten by up until now.

@unknwon Great feedback, and this is something @flying-robot and I were discussing. When users can take the same username after soft delete occurs, deactive doesn't describe the action properly. Is there another common pattern for distinguishing between "soft" and "hard" deletes?

**Comment by unknwon** [comment]
> @Joelkw As @flying-robot says, it's less about having received feedback and more identifying a bad practice we should address when we have the chance. Like you say, we've gotten by up until now.
> 
> @unknwon Great feedback, and this is something @flying-robot and I were discussing. When users can take the same username after soft delete occurs, deactive doesn't describe the action properly. Is there another common pattern for distinguishing between "soft" and "hard" deletes?

When I take one step back and think about this again, the real difference between "soft" and "hard" is that latter we _actually_ removed data from our database. So what about instead of providing two buttons, we provide the "nuke" option as a check box ("remove associated data permanently") when the site admin tries to "delete a user"?

**Comment by quinnkeast** [comment]
I love this thought.

My only concern is if users might check it automatically without reading, which would be our fault. I think we can solve this: we could potentially introduce a second confirmation once the user checks the "hard delete" option, where we ask users to type the username to confirm. In addition to the positive extra friction, it'd serve as an affordance that checking the box changed something. (It feels a bit over-designed so I'd love feedback.)

<img width="1115" alt="Screenshot 2020-11-23 at 10 32 04" src="https://user-images.githubusercontent.com/6304497/99946831-50823200-2d77-11eb-995d-056f51859c87.png">

**Comment by Joelkw** [comment]
@unknwon thank you for the context. @quinnkeast I like your take – I actually think the checkbox is potentially easy to miss and perhaps should be set off a little more (it comes at the end of a bulleted list and it almost looks like another bullet on quick glance). But the design can be refined if we prioritize this –

Before we make any changes, I want to be clear on why this system is the way it is. Why do we offer these soft and hard deletes to begin with instead of just a hard delete? Someone internal to Sourcegraph should know this, maybe @unknwon, or @slimsag I see you [added some lines](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/doc/admin/user_data_deletion.md?view=code) if you know? (I could take some educated guesses on this but would rather be certain.) 

Which one do users primarily use (ideally we know but best guess from someone who worked on this is also good)?

**Comment by quinnkeast** [comment]
>I actually think the checkbox is potentially easy to miss and perhaps should be set off a little more (it comes at the end of a bulleted list and it almost looks like another bullet on quick glance). But the design can be refined if we prioritize this –

I agree—this is meant to be a functional example rather than the ultimate design outcome.

**Comment by unknwon** [comment]
@Joelkw:

>Before we make any changes, I want to be clear on why this system is the way it is. Why do we offer these soft and hard deletes to begin with instead of just a hard delete? Someone internal to Sourcegraph should know this, maybe @unknwon, or @slimsag I see you added some lines if you know? (I could take some educated guesses on this but would rather be certain.)

I have no context why we originally decided to support soft-deleting for users, after all it's a feature we can provide. In general, database records are evidence, some customers may want to keep them for auditing purpose, and regulations (e.g. GDPR if I understood correctly) also require us to be able to completely remove someone's data upon request.

This is not a good answer that I'm 100% happy myself, but hope you get the idea 😅

**Comment by Joelkw** [comment]
Yeah -- I assume this is something to do with records/regulation/customer request, but it'd help to know what! @slimsag if you know (since you wrote the docs) the reason behind this, awesome; if not just react and I'll see if I can get the answer in #any-question or elsewhere.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam-and-admin-experience - the "team/iam-admin-experience" label was applied to this issue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.

**Comment by thenamankumar** [comment]
@quinnkeast do you think this is still an issue with the new user management?

cc: @rrhyne 

![Image](https://user-images.githubusercontent.com/22571395/192931980-297ba366-ffbe-4f41-88e0-7302b44636f6.png)

**Comment by quinnkeast** [comment]
I don't think it's still an issue: "Delete forever" is effective language that resolves the original concern.

**Comment by thenamankumar** [comment]
Closing the issue.
