### ISSUE TITLE
Spike: Investigate gqlgen as the framework for our GraphQL backend

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#16071]
https://github.com/99designs/gqlgen

It is based on code generation and also has rate-limiting related features like "Query complexity".

### Questions to answer after the spike

- By replacing the current framework (graphql-go), what are the pros and cons?
- Should we fully switch to it?
- If we decide to fully switch to it, what's the transition plan? (i.e. can we make two frameworks co-exist for a period of time so we can migrate piece by piece).

**Comment by ryanslade** [comment]
@unknwon Did you look into this at all? I'm looking into rate limiting and wondering if you have an idea about whether it would be feasible to switch?

**Comment by unknwon** [comment]
@ryanslade No I didn't 😓 But happy to look together for sure.
