### ISSUE TITLE
Add support for action items bar and static info bar menu items

### ISSUE THREAD

**Issue by tjkandala** [sourcegraph/sourcegraph#16089]
`editor/actionItemsBar`: New action items bar. Existing `editor/title`actions will likely be displayed here in the web app.

`editor/staticInfoBar`: Tentative bottom bar to which extensions can contribute plain text/hypertext menu items.

**Comment by AlicjaSuska** [comment]
@tjkandala is it within the scope of this issue to define the character limit for static info for the extensions? I think we should keep the existing one (150 characters if I remember correctly).

**Comment by felixfbecker** [comment]
Closing due to extensions deprecation.
