### ISSUE TITLE
Update deploy-sourcegraph to include an ingress-nginx deployment

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1609]
Followup to #929:

- [x] Update deploy-sourcegraph to include an ingress-nginx deployment
- [ ] Update the nginx doc page (https://docs.sourcegraph.com/admin/nginx) with k8s cluster nginx config info

**Comment by ggilmore** [comment]
I took a stab at using ingress-nginx in https://github.com/sourcegraph/infrastructure/tree/master/kubernetes/dogfood, but:

- I haven't tried it with our microservice-based deployment 
- I haven't tried it with manually provisioned certs
- I don't know whether my implementation above is super-robust

**Comment by nicksnyder** [comment]
@keegancsmith is going to own merging and testing https://github.com/sourcegraph/sourcegraph/pull/929 and then can help with this
