### ISSUE TITLE
e2e: external code host links timesout

### ISSUE THREAD

**Issue by davejrt** [sourcegraph/sourcegraph#16135]
e2e tests are failing with the following error:

```
sourcegraph-e2e:   1) e2e test suite
--
  | sourcegraph-e2e:        Repository component
  | sourcegraph-e2e:          external code host links
  | sourcegraph-e2e:            on repo navbar ("View on GitHub"):
  | sourcegraph-e2e:      Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/sourcegraph/client/web/src/end-to-end/end-to-end.test.ts)
  | sourcegraph-e2e:       at listOnTimeout (internal/timers.js:551:17)
  | sourcegraph-e2e:       at processTimers (internal/timers.js:494:7)

```

![image](https://user-images.githubusercontent.com/2067825/100145170-ebf1d080-2e65-11eb-9d7c-537ca9407ce2.png)

https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/end-to-end/end-to-end.test.ts#L1096:19

**Comment by felixfbecker** [comment]
Do we have an integration test for this? If yes, imo we should delete this test.

**Comment by felixfbecker** [comment]
@unknwon could you tell us if there is a backend integration test that verifies `externalURLs` are correctly returned in GraphQL?

**Comment by unknwon** [comment]
> @unknwon could you tell us if there is a backend integration test that verifies `externalURLs` are correctly returned in GraphQL?

I don't think so, but seems easy to add once we know what's the GraphQL query.

**Comment by felixfbecker** [comment]
This query: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@e996e6a4d0351f25289900680dbc63e7e6c77dfd/-/blob/client/web/src/repo/backend.ts#L229-241

**Comment by felixfbecker** [comment]
Could you add one? Then we can just delete this test.

**Comment by unknwon** [comment]
Filed https://github.com/sourcegraph/sourcegraph/issues/16206 for adding backend integration test for this.

**Comment by unknwon** [comment]
Update: #16206 is closed.

**Comment by pecigonzalo** [comment]
@tjkandala FYI: https://buildkite.com/sourcegraph/qa/builds/756#0facdb1d-dd42-43fb-ad17-c36e57468e86 I dont know if that was introduced by #16200 or if its a different problem.

**Comment by tjkandala** [comment]
It looks like the [Datadog extension test](https://buildkite.com/sourcegraph/qa/builds/756#0facdb1d-dd42-43fb-ad17-c36e57468e86/33-1271) failed. It might be a flake, since I can't think of a connection between this and the removed test cc: @felixfbecker

**Comment by felixfbecker** [comment]
Deleting that test is blocked by https://github.com/sourcegraph/sourcegraph/issues/15976. Maybe we can priotitize that?
cc @Joelkw @jeanduplessis
