### ISSUE TITLE
"Review the search reference" tour won't go away

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#16142]
Every time I reload the search results page this re-appears:

<img width="428" alt="image" src="https://user-images.githubusercontent.com/3173176/100161472-bb626480-2e6e-11eb-9cf3-116702960301.png">

It happens even if I click the search reference button, and even if I click `Close tour`. The URL never seems to change, `onboardingtour=true` is always in it:

http://localhost:3080/search?q=error&patternType=literal&onboardingTour=true

**Comment by limitedmage** [comment]
@attfarhan Can you take a look?

**Comment by attfarhan** [comment]
@slimsag I am not able to repro on Sourcegraph.com or my dev server on both Chrome and Firefox. Can you provide more details?

**Comment by attfarhan** [comment]
Ah sorry I see what you mean now. The query param should be stripped. Will fix.
