### ISSUE TITLE
Sourcegraph browser extension action icon is blurry

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#16218]
![image](https://user-images.githubusercontent.com/10532611/100447953-ce18ab80-30b1-11eb-90fd-58147cdb7323.png)

![image](https://user-images.githubusercontent.com/10532611/100448005-e38dd580-30b1-11eb-8e2b-8a77b36368a2.png)

This is on a MacBook 15" display. The low quality is very noticable and irretating to the eye, especially between other high resolution icons.

cc @marekweb @AlicjaSuska

**Comment by AlicjaSuska** [comment]
@marekweb maybe something went wrong during the export from Figma? I've [prepared presets](https://www.figma.com/file/V5t7KOzC6PIX75L4dz8IFc/RFC-221-Browser-extension-improve-discoverability-and-awareness-Approved?node-id=776%3A1303) for 3x png and the svg formats. Maybe you can try to re-upload the icons?
