### ISSUE TITLE
Add a dedicated method to fetch only a subset of repository columns

### ISSUE THREAD

**Issue by asdine** [sourcegraph/sourcegraph#16219]
Currently, search code sometimes needs to fetch only a subset of repository information: the local id, name, the external id, and if the repo is private or not. https://github.com/sourcegraph/sourcegraph/blob/6b282f9176d54018402af43eb1d9e291364be2a2/internal/types/types.go#L88-L101

Since this need is very specific to the search code, add a dedicated method to the [db.RepoStore](https://github.com/sourcegraph/sourcegraph/blob/67a926c4563945d5a3a5599110cbbfafdd18a628/internal/db/repos.go#L53-L53) type to only fetch these types, so that instead of returning a list of "standard" repos, it would return a dedicated struct containing only the information listed above.

This will prevent us from having to use the current structure in the whole codebase, and instead use the [one defined in repo-updater](https://github.com/sourcegraph/sourcegraph/blob/a61ded3b729ce8921c44622ac93cf36adec6f677/cmd/repo-updater/repos/types.go#L69-L69), which is much simpler to use.

**Comment by keegancsmith** [comment]
FYI search only needs name and id, externalrepo fields are fetched for auth. But if auth is purely done in the db layer now you can probably skip returning that.
