### ISSUE TITLE
dhall: implement github-proxy service in deploy-sourcegraph-dhall

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#16259]
- [x] implement github-proxy with support for shared + sourcegraph.com customization 
- [x] write documentation for the implemented customization
- [x] ~~write tests for each customization~~

**Comment by davejrt** [comment]
Given the way testing needs to be done, and the difficulty of testing containers themselves. I believe the rest of these tasks will be handled in a different issue.
