### ISSUE TITLE
Unable to find definition in Linux kernel source

### ISSUE THREAD

**Issue by njbull4** [sourcegraph/sourcegraph#1625]
- **Sourcegraph version:** 18.12.24.2208
- **Platform information:** Firefox Quantum 64 bit running on Arch LSB 1.4

#### Steps to reproduce:

1. Navigate to github.com/torvalds/linux/arch/x86/boot/cpucheck.c
2. View file with Sourcegraph browser extension
2. On line 132 select get_cpuflags() then "Go to definition"

#### Expected behavior:
Should redirect to github.com/torvalds/linux/arch/x86/boot/cpuflags.c line 87

#### Actual behavior:
No redirect. Upon hover, new modal appears stating "Error: no definition found"

**Comment by sqs** [comment]
The Sourcegraph link (equivalent) is https://sourcegraph.com/github.com/torvalds/linux@8834f5600cf3c8db365e18a3d5cac2c2780c81e5/-/blob/arch/x86/boot/cpucheck.c#L122:2.

I believe this is because ctags on the linux repo is very slow due to its size.

**Comment by chrismwendt** [comment]
@njbull4 I deployed performance improvements to Sourcegraph.com, so jump-to-definition is super fast now: https://sourcegraph.com/github.com/torvalds/linux@aa0c38cf39de73bf7360a3da8f1707601261e518/-/blob/arch/arm/mach-footbridge/dc21285.c#L263:34 If you hop to a different commit, it takes ~3 minutes to index, but hover tooltips and jump-to-definition should be fast after that.

Try it out and let us know how it goes!

**Comment by njbull4** [comment]
Thanks for the followup, I'll be sure to check it out
