### ISSUE TITLE
dhall: implement searcher service in deploy-sourcegraph-dhall

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#16267]
- [x] implement searcher with support for shared + sourcegraph.com customization
- [x] write documentation for the implemented customization
- [ ] write tests for each customization

**Comment by uwedeportivo** [comment]
https://github.com/sourcegraph/deploy-sourcegraph-dhall/pull/37

**Comment by uwedeportivo** [comment]
https://github.com/sourcegraph/sourcegraph/issues/16801 covers the test
