### ISSUE TITLE
Repositories/revisions popover inputs are too narrow

### ISSUE THREAD

**Issue by tjkandala** [sourcegraph/sourcegraph#16268]
![Screenshot from 2020-11-30 14-00-39](https://user-images.githubusercontent.com/37420160/100666900-d0843b00-3327-11eb-8bce-b71aed146c50.png)
![Screenshot from 2020-11-30 16-09-13](https://user-images.githubusercontent.com/37420160/100666903-d11cd180-3327-11eb-92b1-a7d322aba462.png)

**Comment by Joelkw** [comment]
(Adding more detail just because the contrast of the images took me a second to get -- this refers to the fact that where you type Is not full width on its element). Thanks for filing!
