### ISSUE TITLE
 dhall: implement query-runner service in deploy-sourcegraph-dhall 

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#16266]
- [x] implement query-runner with support for shared + sourcegraph.com customization
- [x] write documentation for the implemented customization
- [x] ~~write tests for each customization~~

**Comment by pecigonzalo** [comment]
@ggilmore AFAIR from our pairing, we are not writing tests for each customization. Is that correct? If that is the case I will close this.

**Comment by pecigonzalo** [comment]
Tests will be written later on in a separate task. This is done now.
