### ISSUE TITLE
Temporary file size error when upserting sources

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#16318]
Currently we are getting an error whenever upserting sources: 

```
syncer.sync.store.upsert-sources: pq: temporary file size exceeds temp_file_limit (1025563kB)
```

This is likely caused by a db cleanup where we moved about 400k repos from one external service to another.

**Comment by tsenart** [comment]
See `SetClonedRepos`, we likely will be able to use `unnest` for this too.

**Comment by ryanslade** [comment]
This appears to be caused by our orphaned repo trigger. It runs after our upsert sources function, even if no rows are deleted.

The trigger is very slow and appears to perform a full scan on both our `repo` and `external_service_repo` tables:

```
Update on repo  (cost=304634.44..1295175.33 rows=2661 width=544)
  ->  Hash Anti Join  (cost=304634.44..1295175.33 rows=2661 width=544)
        Hash Cond: (repo.id = external_service_repos.repo_id)
        ->  Seq Scan on repo  (cost=0.00..399754.15 rows=3957759 width=529)
              Filter: (deleted_at IS NULL)
        ->  Hash  (cost=235864.53..235864.53 rows=3956153 width=10)
              ->  Seq Scan on external_service_repos  (cost=0.00..235864.53 rows=3956153 width=10)
```

I disabled the trigger temporarily and external services are syncing as expected. 

As a quick fix I'm going to remove this trigger and perform the orphaned repo query in a background job.
