### ISSUE TITLE
Surface sync errors to users

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#16321]
We need to surface code host sync errors to users.

Initially we can display this in the repo list page.

**Comment by ryanslade** [comment]
We are returning the most recent error in the API now so we are ready to display it somewhere in the UI

**Comment by quinnkeast** [comment]
@ryanslade will this be addressed by #16510?

**Comment by ryanslade** [comment]
Yes, I believe this what would be included when there is a "code host connection" error as shown [here](https://www.figma.com/file/0567AnXEpQTzQXkgs7AzEh/%2316510-%E2%80%93-WIP-%E2%80%93-Status-notification-system?node-id=466%3A279)

**Comment by quinnkeast** [comment]
Perfect. We also have an error message surface here in the code host connections view here:

<img width="853" alt="image" src="https://user-images.githubusercontent.com/6304497/104440399-964ac200-5592-11eb-9480-9e600d929dfb.png">

**Comment by quinnkeast** [comment]
Addressed in #16510.
