### ISSUE TITLE
Write documentation for deploy-sourcegraph-dot-com

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#1634]
Part of #976 

This is a stub issue for now - I'll flesh it out later

Write dev READMEs for https://github.com/sourcegraph/deploy-sourcegraph-dot-com/

- How to update deployment
- How to troubleshoot
- Document unique aspects/services associated with sourcegraph.com

**Comment by ggilmore** [comment]
https://github.com/sourcegraph/deploy-sourcegraph-dot-com/blob/release/README.info.md has been written, but it still needs to be fleshed out.

**Comment by nicksnyder** [comment]
closing stale issue
