### ISSUE TITLE
Implement a "copy query" button in the query input

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#16365]
Figma design: https://www.figma.com/file/4Fy9rURbfF2bsl4BvYunUO/RFC-261-Search-Contexts?node-id=581%3A4754

Implement a copy query button in the search input (may reuse the existing, feature-flagged copy query button). Clicking the button will copy to the clipboard a string including:
- The contents of the search input
- The search context
- The pattern type
- If applicable, the `case:` filter

**Comment by limitedmage** [comment]
@lguychard  @novoselrok  This seems to already exist under `experimentalFeatures.copyQueryButton`, is something still missing or do we want to turn the feature flag on? We can convert this issue to track that the copy button still works when we add contexts.
