### ISSUE TITLE
Support context: keyword in the search frontend

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#16363]
Includes:
- Highlighting
- Autocompletion
- Hovers

**Comment by limitedmage** [comment]
I'm adding basic highlighting to support #18086 but will need to expand this further with autocomplete.

**Comment by limitedmage** [comment]
#18013 addresses highlighting and hovers, but we probably still want to add autocomplete based on the user's contexts.

**Comment by novoselrok** [comment]
> #18013 addresses highlighting and hovers, but we probably still want to add autocomplete based on the user's contexts.

Yep, I'll add that in a separate PR.
