### ISSUE TITLE
Incorrect line-break in file path

### ISSUE THREAD

**Issue by vogelsgesang** [sourcegraph/sourcegraph#16373]
- **Sourcegraph version:** Unsure. Whatever my company deployed... If I click on "Help", I get the error message "The version v73828_2020-09-18_5a9b2db was not found.", so I guess `v73828_2020-09-18_5a9b2db` is my version?
- **Platform information:** Chrome 87.0.4280.67 on a macBook pro running Catalina 10.15.7

#### Steps to reproduce:

1. Create a folder with a `-` in its name
2. Navigate to a file within that folder in the SourceGraph UI

#### Expected behavior:

The file path should be displayed in a single line

#### Actual behavior:

Parts of the file path are wrapped into multiple lines.
See screenshot for an example

![Screenshot 2020-12-02 at 21 24 28](https://user-images.githubusercontent.com/6820896/100928011-f5261180-34e5-11eb-9710-c847f1a32889.png)

This is a purely aesthetic issue, functionality works as expected

**Comment by vogelsgesang** [comment]
Quickly opened the Chrome dev console...

It seems this can be easily fixed by adding
```
whitespace: no-wrap
```
to the CSS selector `.file-path-breadcrumbs .part-directory`

**Comment by Joelkw** [comment]
Thanks for filing this, @vogelsgesang!
