### ISSUE TITLE
Investigate why some Prometheus metrics are broken for sourcegraph.com

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#1638]
See:

- https://github.com/sourcegraph/deploy-sourcegraph-dot-com/pull/31#issuecomment-448834572 
- https://sourcegraph.slack.com/archives/C08JA8Q1H/p1545224476154300

cc @beyang @felixfbecker @chrismwendt

**Comment by keegancsmith** [comment]
View https://prometheus.sgdev.org/targets and notice that we are not scraping lang-go and lang-typescript. `kubectl -n prod get svc` indicates we have load balancers for the debug port on both of those services. Maybe prometheus only does discovery on clusterip services. Additionally, we shouldn't have load balancers spun up for the debug port.

**Comment by keegancsmith** [comment]
> Additionally, we shouldn't have load balancers spun up for the debug port.

@ggilmore what do you think about that point?
