### ISSUE TITLE
Enable different user added repo limits per user

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#16394]
We need internal users to be able to ingest large numbers of repos that normal users shouldn't.

Follow up from https://docs.google.com/document/d/1dtrOHs5STJYKvyjigL1kMm6u-W0mlyRSyVxPfKIOfEw/edit#heading=h.r7tahw4ry14v

**Comment by beyang** [comment]
This would be a rather large external service, as my intention is to increase the size of `default_repos` to 400k and then beyond. I also don't think it was the direct DB access that enabled this to exhaust the GitHub rate limit. The ghdump script first makes an API request for each repository; this triggers a fetch from the GitHub API if the repo doesn't exist yet. This is the behavior for *every* user, so in theory any users could cause us to exhaust our GitHub rate limit by requesting repositories that don't yet exist in Sourcegraph.

So I'd propose closing this issue in favor of fixing https://github.com/sourcegraph/sourcegraph/issues/16392. I will also actively monitor the rate limit moving forward.

**Comment by tsenart** [comment]
> This is the behavior for every user, so in theory any users could cause us to exhaust our GitHub rate limit by requesting repositories that don't yet exist in Sourcegraph.

Yes, this is a problem we will need to solve with our own API rate limiting.

> This would be a rather large external service, as my intention is to increase the size of default_repos to 400k and then beyond.

That should be OK and you could also break it up into multiple ones, say, one per language community. Do you think you can use `repositoryQuery` to this effect, instead of a raw list of repos?

**Comment by ryanslade** [comment]
@tsenart Something to be aware of is that once we switch to the new UI it's assumed that a user will only have one code host connection per code host.

**Comment by tsenart** [comment]
>  Something to be aware of is that once we switch to the new UI it's assumed that a user will only have one code host connection per code host.

We could make this a site level external service that is synced in the background.

**Comment by ryanslade** [comment]
I think instead of altering the user limits we should add the ability to sync some of our site level services in the background.

**Comment by ryanslade** [comment]
I don't think this is a priority at the moment since we can continue to use our existing tooling to add new default repos.

**Comment by tsenart** [comment]
Let's close this then.
