### ISSUE TITLE
monitoring: Graph each of the different API rate limits separately (rest, graphql, search)

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#16391]
`sum by (app, resource) (src_github_rate_limit_remaining)` in  https://sourcegraph.com/-/debug/grafana/d/github-proxy/github-proxy?viewPanel=5&orgId=1

Follow up from today's incident https://docs.google.com/document/d/1dtrOHs5STJYKvyjigL1kMm6u-W0mlyRSyVxPfKIOfEw/edit#heading=h.r7tahw4ry14v

**Comment by tsenart** [comment]
@ryanslade: Is this solved?

**Comment by ryanslade** [comment]
Yes, see the third row here in the "External services" section here: 
https://sourcegraph.com/-/debug/grafana/d/repo-updater/repo-updater?orgId=1

However, note that we only seem to use the rest API on Cloud currently. at least from `repo-updater` which is where we monitor the rate limits.
