### ISSUE TITLE
Migrate our external public repos from Travis to GitHub actions

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#16395]
Travis has become increasingly unreliable since they switched to credit-based pricing, blocking teammates from merging PRs. We should migrate those repos to GitHub actions.

This is fairly easy - I did it here as an example: https://github.com/sourcegraph/extension-api-stubs/commit/41b1837ac882fd39f7eb6e33181de9a9037fdc03

- Add GitHub actions workflow file that matches travis.yml
- Delete travis.yml
- Login to NPM with the `sourcegraph-bot` user using credentials in 1Password, create a token with the "Publish" scope and add it as a secret `NPM_TOKEN` under GitHub repo settings > Secrets

**Comment by pdubroy** [comment]
Closing this since I believe it's done. Please feel free to re-open if I'm wrong.

**Comment by felixfbecker** [comment]
There are still [quite a lot of repos](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/+f:travis%5C.yml%24&patternType=literal) in our org. A number of them are [Sourcegraph extensions](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph-+f:travis%5C.yml%24&patternType=literal)

**Comment by pdubroy** [comment]
@felixfbecker Do you know if we have any kind of defined ownership for these repos? I'm assuming that answer is no, but thought I'd check.

**Comment by jasongornall** [comment]
I'm going to suggest we close this issue and we can reopen as needed in a per repo basis. I think the migration in the main repo alleviated 90% of the issues.
