### ISSUE TITLE
Don’t delete repos when GitHub tokens are exhausted

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#16393]
When the number of GitHub tokens are exhausted and we attempt to perform a sync the repo is soft deleted.

We should instead treat this as a soft failure and try again later. 

Related incident:
https://docs.google.com/document/d/1dtrOHs5STJYKvyjigL1kMm6u-W0mlyRSyVxPfKIOfEw/edit#bookmark=kix.ria6dd5pj5wp

**Comment by ryanslade** [comment]
This appears to be related to this code, but in theory should not trigger for token exhaustion:

https://github.com/sourcegraph/sourcegraph/blob/b3d304f70306971adbc5065436e0cc3c36e2c0ee/cmd/repo-updater/repoupdater/server.go#L487-L493

**Comment by tsenart** [comment]
What error does GitHub return when we exhausted a token?

**Comment by ryanslade** [comment]
We check for a temporary error here:
https://github.com/sourcegraph/sourcegraph/blob/main/cmd/repo-updater/repoupdater/server.go#L776:6

So in theory it should work unless there is a bug in the github client

**Comment by ryanslade** [comment]
> This appears to be related to this code, but in theory should not trigger for token exhaustion:
> 
> https://github.com/sourcegraph/sourcegraph/blob/b3d304f70306971adbc5065436e0cc3c36e2c0ee/cmd/repo-updater/repoupdater/server.go#L487-L493

As @tsenart just pointed out this entire block of code is outdated now since private repos should not be deleted if a user tries to access them who does't have access. It will appear as if the repo doesn't exist, but in fact it just isn't visible to some users.

**Comment by ryanslade** [comment]
> We check for a temporary error here:
> https://github.com/sourcegraph/sourcegraph/blob/main/cmd/repo-updater/repoupdater/server.go#L776:6
> 
> So in theory it should work unless there is a bug in the github client

I've confirmed that when rate limit is exceeded in either the GraphQL or rest api we detect it correctly
