### ISSUE TITLE
User added private repos are visible to all

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#16405]
When adding a user added private repo, other users are able to access it.

This is most likely because we do not enforce that user added repos have the `authorization` setting.

**Comment by tsenart** [comment]
I went tested this. The first time I opened the repo in a normal authenticated tab, it showed, the second time, it didn't. Something is off.

**Comment by ryanslade** [comment]
I'll deal with that as part of https://github.com/sourcegraph/sourcegraph/issues/16393
