### ISSUE TITLE
Add clarity to MinIO credential settings

### ISSUE THREAD

**Issue by macraig** [sourcegraph/sourcegraph#16412]
Customer was confused about MinIO credential setting in the following doc:

https://docs.sourcegraph.com/admin/external_services/object_storage

Add clarity to when users should modify (or not) the default credentials.

**Comment by ianseyer** [comment]
Why would one _not_ change the default credentials? This should be highlighted clearly.

**Comment by macraig** [comment]
Hi @ianseyer, MinIO shouldn’t be accessible outside of the cluster/docker-compose network so it shouldn’t need anything other than the default credentials. We'll make sure to make this clearer in our docs moving forward.
