### ISSUE TITLE
lang-typescript references disappear immediately

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#1641]
- Visit https://sourcegraph.com/github.com/sourcegraph/sourcegraph@4e5f8f71ea056f651203c369236ce8dc20357ea5/-/blob/client/browser/src/libs/github/dom_functions.ts#L38:7&tab=references
- Notice the references appear then disappear right away

![2019-01-06 15 58 51](https://user-images.githubusercontent.com/1387653/50743381-06682580-11cc-11e9-8e2b-c802e92ef4ab.gif)

I saw this in the console:

![image](https://user-images.githubusercontent.com/1387653/50743435-ca819000-11cc-11e9-8cd7-e99cbc04a4f2.png)

```
"Error: package.json at https://sourcegraph.com/github.com/sourcegraph/sourcegraph@4e5f8f71ea056f651203c369236ce8dc20357ea5/-/raw/client/browser/package.json does not contain a name
    at g (https://sourcegraph.com/-/static/extension/2038-sourcegraph-lang-typescript.js?bqz5chlq47s8--sourcegraph-lang-typescript:1210:4922)"
```

I don't see this behavior with lang-go, for example in [mux.go](https://sourcegraph.com/github.com/gorilla/mux@master/-/blob/mux.go#L25:47&tab=references).

**Comment by felixfbecker** [comment]
I still hate that we don't show errors anymore in the references panel.

**Comment by sqs** [comment]
@felixfbecker References panel has no good place to show a partial error right now, but feel free to make a PR that adds support for that and then we’ll merge that

**Comment by felixfbecker** [comment]
And if no error is shown, at least the references that were already emitted should be shown

**Comment by felixfbecker** [comment]
Fixed in https://github.com/sourcegraph/lang-typescript/commit/f4ea0b77d9d614a03f38aeb0cfed19f179ff4cc3
