### ISSUE TITLE
Streaming search doesn't respect query operators (and/or/not)

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#16423]
`and`, `or`, `not` operators don't work in streaming search, [example search](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+filters+and+type&patternType=literal) (only shows results for files containing `filters` and not `type`). Search expressions won't work either. I can be convinced this is "incomplete feature" rather than a bug, but if we release in the current state it's a bug. This limitation means these operators are also broken for current Sourcegraph org users (so I have turned it off personally because I need this functionality). Questions:

- What are the assumptions about a query for streaming currently?

- Since we're not abstracting streaming over the current [`Results` endpoint](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/search_results.go#L1098), what's the plan for bringing streaming search in line with the current query language to make it semantics compatible? 

  I'm not saying all our endpoints like unindexed search/structural search need to support streaming right away (I'm not sure what natively supports streaming and what doesn't yet). At this stage I mean mostly: How are we planning to orchestrate things? For example, can we (a) fallback if the query is not compatible with streaming architecture? (b) support streaming interfaces for all our kinds of searches, even if the thing that evaluates a query is batched based? 

  The code exists for merging results, so I assume something like that can be reused/ported for the streaming endpoint--just wondering what the thinking is here.

**Comment by limitedmage** [comment]
@keegancsmith Can you take a look? Is this expected?

**Comment by keegancsmith** [comment]
This is a known issue on my side. Completely backend related, and I was intending on punting on this until later. I did want to ensure the experience wasn't broken before releasing streaming. For everything we don't support, we just fallback to the batching behaviour (ie old experience). Fully supporting and/or is a bit tricky, but not so bad given how merging works (ie we can merge at the repo granularity relatively easy)

**Comment by rvantonder** [comment]
Great, makes sense. Might not be worth putting in guardrails (error/alert for unsupported queries) if this resolves soonish before release.

**Comment by keegancsmith** [comment]
Part of https://github.com/sourcegraph/sourcegraph/issues/13067
