### ISSUE TITLE
Deleting User Settings leads to Error Page

### ISSUE THREAD

**Issue by vanesa** [sourcegraph/sourcegraph#1645]
Accidentally deleted my user settings. Would have expected an empty user settings box, instead I get this error page.

![pasted_image_at_2018-09-17__11_15_am](https://user-images.githubusercontent.com/9110008/45642001-dd305780-ba6b-11e8-924c-f24e3e829b7a.png)

**Comment by chrismwendt** [comment]
I have some free cycles, so I'll look into this.
