### ISSUE TITLE
Clicking "show more" with search expressions can sometimes not go away

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#16472]
Query keeps saying show more, issue with updating limit hit in the merge code [`repo:^github\.com/sourcegraph/sourcegraph$ (Github case:yes) or (organisation case:no) count:1000`](https://sourcegraph.com/search?q=repo%3A%5Egithub%5C.com%2Fsourcegraph%2Fsourcegraph%24+%28Github+case%3Ayes%29+or+%28organisation+case%3Ano%29+count%3A1000&patternType=literal)

Update: it seems to be because "case" is in there. This is fine: [`repo:^github\.com/sourcegraph/sourcegraph$ (Github or organisation) count:1000`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+%28Github+or+organisation%29+count:1000&patternType=literal)

**Comment by rvantonder** [comment]
Clarification: It's actually because the original query in the description does not parenthesize the expression well enough, and ends up being interpreted as:

`(repo:foo (Github case:yes)) or (organisation case:no)` -> reports show more (for repos that are not `foo`). I'm guessing the second subexpression returns limit hit, but I don't see the results for it (?).

**Comment by camdencheek** [comment]
Closing as stale since we no longer have a "show more" button
