### ISSUE TITLE
Mismatched fonts on landing page for Chrome on Windows machine

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#16499]
I was on Sourcegraph.com on Chrome on a Windows box and noticed that the recent searches/repos font doesn't match the search box query font. What can we do to make this consistent? CC @rrhyne 

Click to zoom
![Screenshot 2020-12-06 222657](https://user-images.githubusercontent.com/888624/101312955-4ef24880-3812-11eb-9eff-44408e82ef80.png)

The span class for recent searches/repos is `text-monospace search-query-link`. The span class for query box is `mtk14` (probably related to monaco?)

**Comment by limitedmage** [comment]
@rvantonder  are you still seeing this? A little while ago I made some changes to standardize the fonts in the `MonacoQueryInput` to match our monospace font.

**Comment by rvantonder** [comment]
Yeah looks OK now, thanks!

![Screenshot 2021-02-22 192738](https://user-images.githubusercontent.com/888624/108795666-1e35cb80-7544-11eb-8821-57a3825cd904.png)

**Comment by rvantonder** [comment]
(The dark scrollbars turn light when I hover over them, apparently the refresh doesn't happen when I toggle the theme in Windows/Chrome)

**Comment by limitedmage** [comment]
Scrollbars are managed by the browser and we can't really control them. We try to tell the browser the right thing (CSS `theme`) but it's up to the browser to react accordingly.

**Comment by rvantonder** [comment]
Yep, orthogonal to the fonts issue. Just didn't want someone passing by to think something's broken there.
