### ISSUE TITLE
Write an RFC for First-class Perforce integration

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#16508]
Based on the investigation in https://github.com/sourcegraph/customer/issues/148.

RFC: https://docs.google.com/document/d/1r6ngZNOENVikcEzMU4v8b3TNT2TQydzILVDRqmJuzqY/edit#heading=h.trqab8y0kufp

**Comment by tsenart** [comment]
cc @christinaforney, this seems to be much much smaller than what we first thought!

**Comment by unknwon** [comment]
Will break up to separate issues and create a project so closing this one.
