### ISSUE TITLE
"Some repositories excluded" for queries targeting a single repository

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#16523]
Run this search, targeting solely sourcegraph/sourcegraph: https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+fmt.Println&patternType=structural

Notice the skipped alert + popup show up because a result limit was hit:

![image](https://user-images.githubusercontent.com/1741180/101380182-7cdc9900-38b5-11eb-9e26-b52b60d52573.png)

The alert title is misleading here, as no _repository_ was excluded from the search. It should probably read "some results excluded" or "some matches excluded"?

**Comment by limitedmage** [comment]
@rrhyne I'm thinking of going with "Some results excluded", what do you think?

**Comment by rrhyne** [comment]
Sounds great.
