### ISSUE TITLE
prometheus: job label for frontend is different in different deployments

### ISSUE THREAD

**Issue by uwedeportivo** [sourcegraph/sourcegraph#16552]
k8s: sourcegraph-frontend
dev: frontend

check the other deployments, make sure all job labels are consistent

**Comment by bobheadxi** [comment]
Related: we currently have a hack workaround for this in the monitoring definitions that we can remove with this change https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+lang:go+%28frontend%7Csourcegraph-frontend%29&patternType=literal

**Comment by uwedeportivo** [comment]
the PR closed this automatically, re-opening until all PRs land

single server is good too now (same PR takes care of it)

![image](https://user-images.githubusercontent.com/534011/107582967-19b9fc00-6baf-11eb-8eed-6c80e7162091.png)

**Comment by uwedeportivo** [comment]
doing docker compose next
