### ISSUE TITLE
Codecov line decorations are not readable in GitHub dark mode

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#16555]
![image](https://user-images.githubusercontent.com/10532611/101528800-095b8a00-3990-11eb-9d43-4016a1c73f7e.png)

This is tricky because extensions can specify `dark` and `light` styles, but the browser extension currently assumes GitHub is always in light mode. We need to detect the theme.

**Comment by eseliger** [comment]
The `<html>` node has a `data-color-mode="dark"`
