### ISSUE TITLE
Migrate to pgx library for Postgres access

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#16575]
The package we use, https://github.com/lib/pq, states the following:

> This package is effectively in maintenance mode and is not actively developed. Small patches and features are only rarely reviewed and merged. We recommend using pgx which is actively maintained.

**Comment by asdine** [comment]
Some observations so far:

- pgx doesn't support the `fallback_application_name` setting and other driver only settings https://github.com/jackc/pgx/issues/893. The workaround is very simple though.
- pgx and pgtypes don't provide easy to use [driver.Valuer](https://golang.org/pkg/database/sql/driver/#Valuer) implementations https://github.com/jackc/pgtype/issues/83. Most Go types are automatically converted if we use the pgx API, however the database/sql API requires a conversion prior to calling Exec or Query. The workaround is to keep using pq types like [pq.Int64Array](https://pkg.go.dev/github.com/lib/pq#Int64Array) for example.
- It seems like using the database/sql API won't bring any [significant](https://github.com/jackc/pgx#choosing-between-the-pgx-and-databasesql-interfaces) [performance](https://github.com/jackc/pgx#performance) gain, as most of the cool stuff is brought by using the pgx API.

**Comment by tsenart** [comment]
@asdine: Any clue what level of effort it would be to later migrate to use pgx native APIs instead of database/sql?
