### ISSUE TITLE
Experiment with PGAnalyze

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#16579]
PGHero, which we have deployed, doesn't go as far as https://app.pganalyze.com/organizations/sourcegraph/, which has features like auto explaining, and historical views of query performance. For 250 USD per month, it seems worth it.

**Comment by unknwon** [comment]
We have had tried this, just asking here, has the experiment considered done?

**Comment by tsenart** [comment]
It's on-going since we haven't paid enough attention to it recently and there were a few bugs on their side that they were fixing.
