### ISSUE TITLE
Underscores are rendering as spaces

### ISSUE THREAD

**Issue by bduffany** [sourcegraph/sourcegraph#16595]
- **Sourcegraph version:** sourcegraph.com
- **Platform information:** Ubuntu 20.04, Google Chrome 86

#### Steps to reproduce:

1. Type in a search term containing an underscore

#### Expected behavior:

Underscores should render as underscores.

#### Actual behavior:

Underscores render as spaces (in this screenshot, `http_response_size` is rendering as `http response size`. Please ignore the highlighted "http"). The issue happens in both Dark Mode and Light Mode.

![image](https://user-images.githubusercontent.com/2414826/101667799-c47e3480-3a1d-11eb-9089-9092ad345eb7.png)

IMO this is a huge usability issue since there's a lot of code out there that contains underscores

**Comment by bduffany** [comment]
For anyone else who ran into this, you can add this user stylesheet using the Stylish Chrome extension, and it should fix the issue:

```css
#monaco-query-input {
    height: 17px !important;
}
```

**Comment by Icantjuddle** [comment]
Having this issue on firefox 84 as well on linux.
