### ISSUE TITLE
Upgrade to Postgres 13 on dot-com

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#16611]
Postgres 13 is available for Cloud-SQL, let's migrate to it

**Comment by pecigonzalo** [comment]
Pushing this after NY as there is no rush to migrate and we faced a number of issues which meant this is not a trivial process.

**Comment by daxmc99** [comment]
The reason for the longer time estimate is that the default import/export does not work. I'm not sure why but I believe it has something to with our use of extensions. 

This means we will need to run a job _somewhere_ with `pg_dump`. There is some advantage in this model since extensions would be copied. 

Lastly, it might be worthwhile to contact GCP to determine why our import/export is failing.

**Comment by kalanchan** [comment]
@daxmc99 can you add this back to the Cloud team's board? Or close it and recreate? :)
