### ISSUE TITLE
monitoring: Add container restart alerts for repo-updater

### ISSUE THREAD

**Issue by asdine** [sourcegraph/sourcegraph#16653]
We currently have no way of knowing when repo-updater containers restart, usually due to repo-updater running OOM.

**Comment by daxmc99** [comment]
This is typically done with by adding `kube-state` metrics but we that is currently not part of `deploy-sourcegraph`

**Comment by tsenart** [comment]
@daxmc99: How can we make it part of it? Also @pecigonzalo, other ideas?

**Comment by daxmc99** [comment]
https://github.com/google/cadvisor/issues/1312#issuecomment-613654333 
I am hoping @slimsag's hack could work here. Otherwise, we could add kube-state deployment.

**Comment by tsenart** [comment]
What about the `up` metric?

**Comment by asdine** [comment]
Fixed by #16664

**Comment by pecigonzalo** [comment]
Does https://github.com/sourcegraph/sourcegraph/pull/16664 fix this? That one does memory, this one requires alerts.

> This is typically done by adding kube-state metrics but that is currently not part of deploy-sourcegraph

This is my preferred option, but it does not work with Docker Compose. 

> @daxmc99: How can we make it part of it? Also @pecigonzalo, other ideas?

@tsenart I dont know really, for Cloud something like this could work, but for customers it might not, or we have to create an alert for Docker Compose and Kubernetes. This could also overall replace #bots-production with something metrics based and a bit smarter, but I cant cook up a full solution right now. I would reference the public Kubernetes mixins as this a solved problem I believe.


- https://github.com/kubernetes-monitoring/kubernetes-mixin
- https://gitlab.com/gitlab-com/runbooks/-/tree/master/rules

I believe there are a few more.
