### ISSUE TITLE
Search alerts returned from the backend should use Markdown

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#16677]
See this example search alerts returned from the server: 

![image](https://user-images.githubusercontent.com/206864/101813424-90fce200-3ad1-11eb-8438-edbbe48431b7.png)

From https://github.com/sourcegraph/sourcegraph/pull/16624#issuecomment-743074770:
> What do you think about rendering the alert as markdown? Currently the link is not a real link, and the filters would look better as code I think than with double quotes

**Comment by lguychard** [comment]
Duplicate of #16576
