### ISSUE TITLE
gitserver: Maintain repo state in Postgres (WIP)

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#16670]
### Context

We need to be able to query repo state that currently only exists on gitserver.

#### Clone status

Is the repo cloned, cloning or not cloned? 

We currently poll git-server for the full list of clone repos each shard has in its disk. repo-updater then takes that list of repos and updates the repo table `cloned` column accordingly.

https://github.com/sourcegraph/sourcegraph/blob/1a76bd75d079cfb0f3c2c26fc7a90a84590fd38a/cmd/repo-updater/shared/main.go#L399-L440

This is done so that we can efficiently filter repos by cloned state in SQL.

#### Sync failures

Currently when syncing repos we pick a random clone url from one external service based on random map iteration (not great): https://github.com/sourcegraph/sourcegraph/blob/1a76bd75d079cfb0f3c2c26fc7a90a84590fd38a/cmd/gitserver/main.go#L81-L83

We attempt to sync once and fail on error. Instead we should probably round robin all external services to give us the best change of eventually syncing.

Perhaps we can keep an in memory LRU cache of bad clone urls that are low priority? Or, we could flag it in `external_service_repo` but I'd prefer not to we don't want more than one service writing to that table.

### Proposal

Instead of shuffling huge lists of repo names across service boundaries, gitserver would maintain a table called `gitserver_repos` with the appropriate cloning state of each repo and whether we failed to sync. Then in any service that needs to filter repos based on cloning state, it's a simple join.

A secondary use case that we want to solve is for zoekt-indexserver to be able to efficiently ask git-server for all repos that have had commits after X. It's possible we could leverage this table for the same purpose, but I think it'd be fine for us to split this work out.

Proposed schema:

```sql
CREATE TABLE IF NOT EXISTS gitserver_repos
(
    repo_id int REFERENCES repo(id) PRIMARY KEY,
    clone_status text NOT NULL default 'not_cloned',
    last_external_service bigint,
    shard_id text NOT NULL,
    last_error text,
    updated_at timestamp WITH TIME ZONE default now() not null
);
```

`last_error` allows us to determine repos that are failing to sync
`last_external_service` allows us to round robin syncing across all external_services

Gitserver will be responsible for keeping the state up to date. Each gitserver will run the following "reconciler" in a background goroutine:

1. Get the current list of repos it is responsible for. We use the same method currently used in frontend here: https://github.com/sourcegraph/sourcegraph/blob/fdc8858ebfe10e50d5640aa4785d91c3755eb4fd/internal/gitserver/client.go#L91-L111 to decide. 
2. For each repo, check whether the current state as returned from the db aligns with what is on disk, if different update it.

Additionally we can also make reactive updates to the database when we know the state is changing, ie:

1. We starting cloning a new repo
2. We finish cloning a repo
3. We purge a repo

A missing row can be treated as `not_cloned`

We have an open PR with an initial schema and some code: https://github.com/sourcegraph/sourcegraph/pull/15434

**Comment by tsenart** [comment]
cc @keegancsmith @flying-robot

**Comment by ryanslade** [comment]
Just had a hack session with @asdine where we thought of another possible way to solve this so just noting it down here so w don't forget it as an option.

We can perform the same consistent hashing we do here, but in SQL:
https://github.com/sourcegraph/sourcegraph/blob/fdc8858ebfe10e50d5640aa4785d91c3755eb4fd/internal/gitserver/client.go#L107-L111

The janitor job on Gitserver would select all repos that it owns by using the same hashing functions above, but in SQL, looking at the new 'gitserver_repos` table.

Then, we just need to iterate over that result and set the sate based on what's on disk. There are potential race conditions where other go routines are cloning repos which we would need to be aware of though.
