### ISSUE TITLE
Include additional unique user information in session

### ISSUE THREAD

**Issue by ElizabethStirling** [sourcegraph/sourcegraph#16680]
Due to potential security concerns raised in [this ops incident](https://sourcegraph.slack.com/archives/CMBA8F926/p1607633730290500?thread_ts=1607620479.283500&cid=CMBA8F926), we want to store the creation date of the user in as part of the session stored in Redis. To do this, we would update `cmd/frontend/internal/session/session.go:sessionInfo` to contain a field `UserCreatedAt` that would be compared with the user's creation date whenever the session was used to authenticate. Since this would only be out of sync due to a serious issue, we should alert if this check fails, since it indicates that either sessions are users are being improperly generated or used.

Relates to the incident in #16629

**Comment by unknwon** [comment]
@ElizabethStirling Could you elaborate more about why having the extra "creation date" would help prevent impersonation (for example, the latest incident)?

**Comment by ElizabethStirling** [comment]
> @ElizabethStirling Could you elaborate more about why having the extra "creation date" would help prevent impersonation (for example, the latest incident)?

This would have prevented this issue because the user ID collisions would have been resolved by noting that the creation date of the user was different. More generally, if we ever have any user ID collision cases, the novel colliding user will not be created at the same time as the victim user, and I would also not expect the attacker to have a way of determining or spoofing the user's creation date. If the attacker can spoof their creation date as well, this likely indicates a more serious vulnerability.

**Comment by unknwon** [comment]
@ElizabethStirling Thanks! I understand now, the creation date would help prevent the particular incident we had (user is recreated with same identifier).

**Comment by unknwon** [comment]
@flying-robot Feel free to reassign to you 🙂

**Comment by ryanslade** [comment]
@flying-robot I've moved this to the current milestone so that we can close the old one
