### ISSUE TITLE
After install page looks broken on Safari

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#16717]
![Screen Shot 2020-12-14 at 12 32 46](https://user-images.githubusercontent.com/10532611/102076794-91b2b280-3e08-11eb-9a39-fd0968cb772e.png)

Looks like some flex property is not supported or not rendering the same as in Chrome/Firefox.

**Comment by felixfbecker** [comment]
cc @marekweb

**Comment by marekweb** [comment]
Fixed by #18005
