### ISSUE TITLE
Add number of synced repos to externalServices GraphQL resolver 

### ISSUE THREAD

**Issue by artemruts** [sourcegraph/sourcegraph#16729]
### Proposed changes

For the new code host page designs, we'll need to make a few tweaks to `externalServices` GraphQL API.

1. provide a number of synced repos for given code host connection:
This could be just a `number` or an array of `namespace/repository-name` strings.
2. surface sync warnings and errors for code hosts:
We already have a `warning` optional field on the `ExternalService` node - we just need to verify it's used.

```json
{
  "data": {
    "externalServices": {
      "nodes": [
        {
          "id": "<id>",
          "kind": "GITHUB",
          "displayName": "My GitHub connection",
          "config": "{\n  \"url\": \"https://github.com\",\n  \"token\": \"<access token>\",\n  \"orgs\": [],\n  \"authorization\": {}\n}",
          "synced": "[\"foo/bar\", \"foo/baz\", \"foo/42\"]",
          "warning": "<warning/error message>"
        }
      ]
    }
  }
}
```

If we can get this data in a single request - that's preferred.

**Comment by ryanslade** [comment]
If we only need the count of synced repos I think we should only return a number to reduce the amount of data we send.

Happy to reuse the `warning` field assuming it's not already used for something else. 

```json
{
  "data": {
    "externalServices": {
      "nodes": [
        {
          "id": "<id>",
          "kind": "GITHUB",
          "displayName": "My GitHub connection",
          "config": "{\n  \"url\": \"https://github.com\",\n  \"token\": \"<access token>\",\n  \"orgs\": [],\n  \"authorization\": {}\n}",
          "repoCount": 42,
          "warning": "<warning/error message>"
        }
      ]
    }
  }
}
```

**Comment by ryanslade** [comment]
We added a new field to surface sync errors here: 
https://github.com/sourcegraph/sourcegraph/pull/16880

I'll add the sync count next
