### ISSUE TITLE
Space bar scroll down doesn't work as expected in Firefox

### ISSUE THREAD

**Issue by macraig** [sourcegraph/sourcegraph#16728]
Issue reported by a user from customer https://app.hubspot.com/contacts/2762526/company/768958891 

#### Steps to reproduce:

1. Open any file on Sourcegraph Web with Firefox, example: https://sourcegraph.com/gitlab.com/sourcegraph/sourcegraph/-/blob/monitoring/definitions/frontend.go
2. Click on a blank line and space bar to scroll down. 

#### Expected behavior: 
Pressing space bar should trigger scroll down in file.

#### Actual behavior:
Pressing space bar doesn't do anything.

**Comment by jasongornall** [comment]
@lmelende20 mind taking a look at this? seems like a nested scrollbar issue
