### ISSUE TITLE
No unique constraint on {changeset,campaign}_specs.rand_id column

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#16721]
I think after this comment https://github.com/sourcegraph/sourcegraph/pull/11711#discussion_r445470902 I missed adding a separate unique constraint on the `rand_id` columns.

And @tsenart just reminded me of that: https://github.com/sourcegraph/sourcegraph/issues/16629#issuecomment-744423160

So we should add a unique constraint *and* make sure that we retry application-side when the creation fails (if that's even possible, since the transaction might be rolled back if that fails)

**Comment by mrnugget** [comment]
#22719 adds another `rand_id`.

**Comment by eseliger** [comment]
I think we could get away with failing, instead of a complicated retry algorithm, since this ought to happen _never_. It's still a good change to add the index because it'll ensure we never fall into an invalid state.
