### ISSUE TITLE
deploy-sourcegraph: secrets in config-file.ConfigMap.yaml should be read a secret, not a config file

### ISSUE THREAD

**Issue by marccampbell** [sourcegraph/sourcegraph#1677]
https://github.com/sourcegraph/deploy-sourcegraph/blob/master/base/config-file.ConfigMap.yaml contains secrets such as github tokens and auth provider secrets. If this config map was changed to be a secret, and loaded from a secret in every deployment that uses it, then it can take advantage of commonly available tools to encrypt and load secrets separately. In the current form, this is hard to use in a GitOps workflow (weave flux in my case) because the secrets would have to be unencrypted in the git repo.

I'm currently doing this with a kustomize overlay after running helm template, but it feels slightly fragile because if you introduce a new deployment that uses this config map, my deployment will break.

Would you be open to a PR to change this config map to a secret?

**Comment by ggilmore** [comment]
@slimsag Is this still relevant?

**Comment by slimsag** [comment]
We are moving to a new model in 3.0 where secrets are stored in the DB entirely and only accessible via the management console. More information on this will be in the blog post coming soon sometime next week.
