### ISSUE TITLE
campaigns: fix changeset count calculation

### ISSUE THREAD

**Issue by LawnGnome** [sourcegraph/sourcegraph#16781]
Historically this was a UI ticket, which was addressed in a different issue, but there is an issue that was originally somewhat hidden with this that we need to handle. To quote @eseliger:

> I think this ticket is about making [this query](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/enterprise/internal/campaigns/store/changesets.go#L829) use the same conditions as the [State resolver](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/enterprise/internal/campaigns/resolvers/changeset.go#L291), so the numbers always match up with the table filters.
> IF that's what we meant here, I am not doing this as part of #17110 😁

**Comment by LawnGnome** [comment]
@eseliger I think this is your "Stats bar, with stats about total diffStat, all changeset operations and added/removed/modified counts" entry in #17110, if I'm not mistaken? I feel like you're already doing this; is there anything in #17110 you want to give me in return?

**Comment by eseliger** [comment]
I think this ticket is about making [this query](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/enterprise/internal/campaigns/store/changesets.go#L829) use the same conditions as the [State resolver](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/enterprise/internal/campaigns/resolvers/changeset.go#L291), so the numbers always match up with the table filters.
IF that's what we meant here, I am not doing this as part of #17110 😁
