### ISSUE TITLE
[deploy-sourcegraph] update documentation about the site configuration 

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#1679]
_See https://github.com/sourcegraph/deploy-sourcegraph_

Since #966 was merged, the documentation in https://github.com/sourcegraph/deploy-sourcegraph/blob/master/docs/configure.md#update-site-configuration is now outdated since https://github.com/sourcegraph/deploy-sourcegraph/blob/181c382d7d737cc0178bb94c6eb98da5b492a0de/base/config-file.ConfigMap.yaml is going to be removed.

1. That section should now link to documentation on docs.sourcegraph.com about the site admin config page + the management console
1. That section should probably be updated with information about how to access the management console (port-forwarding, changing the password in a k8s context, etc.)
1. All references to the site configuation file in the rest of https://github.com/sourcegraph/deploy-sourcegraph/blob/master/docs/configure.md need to be updated to stop refering to the config-map 
1. The migration path from the old https://github.com/sourcegraph/deploy-sourcegraph/blob/181c382d7d737cc0178bb94c6eb98da5b492a0de/base/config-file.ConfigMap.yaml to the management console needs to be documented
1. All the doc changes above should be tested on fresh clusters using the steps in https://github.com/sourcegraph/deploy-sourcegraph/blob/master/README.dev.md

**Comment by ggilmore** [comment]
The license key section also needs to be updated https://github.com/sourcegraph/deploy-sourcegraph/blob/master/docs/configure.md#add-license-key

**Comment by slimsag** [comment]
Dup of #1428 which is a more broad issue for this. I've copied your notes there.
