### ISSUE TITLE
Heavy GraphQL API queries causing brief, definitive outages of deployment

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#16807]
A user ran this GraphQL API query multiple times and it is suspected to have caused a brief outage on their instance https://app.hubspot.com/contacts/2762526/company/407948923/:

```
query {
  search(query: "something count:9999") {
    results {
      __typename
      limitHit
      resultCount
      approximateResultCount
      indexUnavailable
      results {
        ... on FileMatch {
          lineMatches {
            lineNumber
            preview
            limitHit
          }
          repository {
            name
            commit(rev:"HEAD") {
              committer {
                date
              }
            }
          }
          file {
            path
          }
        }
      }
    }
  }
}
```

It seems that `results.repository.commit` in this query would resolve directly to [this implementation code](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/repository.go#L148-163) which would then ask gitserver to execute `git rev-parse HEAD` for the repository on every single search result that is returned. This is obviously far more work than needs to be done, as many results will come from the same repository.

It is suspected that the massive fan-out here from the frontend -> gitservers caused a temporary network outage on the machine, causing the frontend to be inaccessible. Their deployment is a single-beefy-machine, so more prone to this type of issue - but could happen on any deployment given only a slightly broader search query due to the fact that network traffic is from frontend.

**Urgency / priority:** unclear / normal.

Related to #5715 #5705 and #10629

**Comment by ryanslade** [comment]
This look like something we can tackle on our next iteration. I'm happy to take it if nobody else wants it.

**Comment by tsenart** [comment]
I suppose an underlying unmet need we have here is to cache responses from git-server — this would reduce a lot of load on git-server. But it's unclear if having a cache across the network (e.g. in Redis), would prevent this from happening again since there'd still be lots of network traffic.

This will be hard to reproduce I believe. Thoughts @slimsag? Could there be some Linux kernel tunables we could tweak to make this go away perhaps?

**Comment by ryanslade** [comment]
Can we not at least cache the result of backend.Repos.ResolveRev per request?

**Comment by tsenart** [comment]
Yeah, that's totally doable and good in itself. But it's going to be hard to validate if it has any impact on this situation.

**Comment by slimsag** [comment]
FYI, customer suffered a serious outage due to this just today. https://github.com/sourcegraph/customer/issues/175#issuecomment-790970050

Suspicion is that it is due to a heavy GraphQL query (or multiple) and GraphQL rate limiting would be one way to help prevent this.

> This will be hard to reproduce I believe. Thoughts @slimsag? Could there be some Linux kernel tunables we could tweak to make this go away perhaps?

Yeah, reproducing the outage itself will be hard. I think the quicker thing to focus on here is just GraphQL rate limiting.

**Comment by slimsag** [comment]
Customer suffered another serious 30m outage affecting 25% of all requests (and several users): https://github.com/sourcegraph/customer/issues/269
