### ISSUE TITLE
Upgrade to networking.k8s.io/v1 Ingress

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#16808]
```
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, 
unavailable in v1.22+; 
use networking.k8s.io/v1 Ingress
```

Our Ingress API type is slightly outdated. As part of this, we should also update our Ingress to use a more recent version of `Nginx-ingress`

**Comment by pecigonzalo** [comment]
FYI, I run into some issues with this and Traefik v2 in my `k3d` cluster, we should verify NGINX ingress works with this, but also it could affect customers  using Traefik.

**Comment by daxmc99** [comment]
Agreed, this should work with Trafik as well

**Comment by daxmc99** [comment]
As part of this, we will need to upgrade our supported Kubernetes version to 1.14. 

I'm hesitant to do this because we are currently on **1.9** per our [docs](https://docs.sourcegraph.com/admin/install/kubernetes#requirements). 

A common solution to this problem is to use your deployment management tool to detect the k8s version you are deploying into. https://sourcegraph.com/github.com/rancher/rancher/-/blob/chart/templates/ingress.yaml?subtree=true#L2

I'm still planning on upgrading our ingress nginx-deployment as part of this but I'm not sure if we should update the ingress object at this moment.

**Comment by davejrt** [comment]
I think we should only support whatever version of kubernetes are supported, and those which we actively test  on, otherwise we leave ourselves open to maintaing code for bugs/issues/components that are well and truly out of date.

**Comment by daxmc99** [comment]
In that case we should make the minimum  `1.15` per https://github.com/sourcegraph/deploy-sourcegraph/blob/master/tests/integration/fresh/fresh_test.go#L24

**Comment by pecigonzalo** [comment]
@daxmc99 Removing from the sprints.

**Comment by davejrt** [comment]
We should update any scripts we use to deploy an ingress controller and have them reference the upstream yaml files and documentation so we don't lag behind. 

https://sourcegraph.com/github.com/sourcegraph/deploy-sourcegraph/-/tree/configure/ingress-nginx
