### ISSUE TITLE
Change sourcegraph.com to use ingress-nginx 

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#1682]
Once #1609 is completed, sourcegraph.com should also use ingress-nginx. 

I don't think this is necessary for 3.0, but feel free to change the milestone if you think otherwise @keegancsmith

**Comment by chrismwendt** [comment]
The Python language server does not support TLS, so it needs an ingress controller for SSL termination (doesn't seem release blocking to me).

**Comment by ggilmore** [comment]
@keegancsmith Has this been done? I see both an `sourcegraph-frontend` ingress and a `sourcegraph-frontend-loadbalancer-https` in the dot-com cluster.

**Comment by keegancsmith** [comment]
This has been done. However,  I still need to cleanup the old LB so will leave this open. This now also opens the possibility of using the ingress for other things like extensions and the gddo-proxy. But lets leave that for another time.

**Comment by keegancsmith** [comment]
LB removed and removed from create cluster script in https://github.com/sourcegraph/deploy-sourcegraph-dot-com/commit/b411b0c07b048284324575603469680690f05e4d
