### ISSUE TITLE
search: remove done field from progress API

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#16833]
> I think instead the typescript consumer API should listen for the observable being complete, then update progress to be done. So we additionally remove the "done" field from progress. cc @limitedmage 

Context: https://github.com/sourcegraph/sourcegraph/pull/16298#issuecomment-737039691

**Comment by limitedmage** [comment]
I was just talking about this with @lguychard yesterday. I agree we should do this. I might actually do this as part of #16734.
