### ISSUE TITLE
fix `src version` recommended version

### ISSUE THREAD

**Issue by chrispine** [sourcegraph/sourcegraph#16850]
Currently, `src version` will reply with current version and recommended version. The problem is that if a user is on the latest version of src-cli (which is good), the "recommended" version could actually be a downgrade.

Instead, it should say something like:

```
Current version: 3.23.0
Recommended version: 3.22.4 or later
```

(Also, let's make sure the capitalization is consistent; currently, one of the "version"s is capitalized, and the other isn't.)

**Comment by jonti09** [comment]
HI @chrispine 

I would like to contribute to the project, but as this is the first time I am contributing to OSS, would you mind guiding me for the same?
