### ISSUE TITLE
Horizontal hover scrolling in browser extension scrolls entire hover content

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#1686]
![2019-01-07 13 28 45](https://user-images.githubusercontent.com/10532611/50794531-3e30a500-1280-11e9-82d6-f28d109129f6.gif)

**Comment by amandascchan** [comment]
Just noticed that if the content only has one line it is still covered by search bar. 

Chrome: Version 73.0.3683.103 (Official Build) (64-bit)
Platform information: v19.4.16.929, on MacOS Sierra 10.12.6


<img width="817" alt="Screen Shot 2019-04-23 at 7 05 42 PM" src="https://user-images.githubusercontent.com/5076860/56621544-e03f8780-65fa-11e9-9dd4-11de24f40c5c.png">
