### ISSUE TITLE
Code Monitoring: Replace placeholder icon with feature icon

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#16871]

**Comment by AlicjaSuska** [comment]
The icon is ready to download from [here](https://drive.google.com/file/d/1FcrBQ3BFI0hdQ5YHAsc-bNWfbuZCFMxd/view?usp=sharing).

[Figma file](https://www.figma.com/file/Zzefa8PPpBLozovls2uRu8/Code-monitoring-icon-16871-Review?node-id=246%3A11)

![Icon](https://user-images.githubusercontent.com/20326070/102486194-f4a28480-4068-11eb-8bf2-818f551fa4b4.jpg)
