### ISSUE TITLE
Limit non-admin user to a single external service per code host

### ISSUE THREAD

**Issue by artemruts** [sourcegraph/sourcegraph#16885]
### Description

Limit non-admin user to a code host per supported code host kind (`Mutation.AddExternalService`)
This would prevent users creating multiple services with API and allow us to simplify UIs knowing there's a backend constraint.

### Acceptance criteria

When non-admin user makes a GraphQL API request to add a new service of already used code host kind, we should send back an error and prevent mutation.

Something descriptive:
```js
{
  "errors": [
    {
      "message": "Non-admin users can't have more than one external service per code host (GitHub)"
    }
  ]
}
```

**Comment by ryanslade** [comment]
@artemruts I've added this check in the backend, see https://github.com/sourcegraph/sourcegraph/pull/17104

Maybe we should update the UI too so that once an external service has been added for one kind we don't show that as an option anymore?

**Comment by artemruts** [comment]
> @artemruts I've added this check in the backend, see #17104
> 
> Maybe we should update the UI too so that once an external service has been added for one kind we don't show that as an option anymore?

@ryanslade I think the new tokens UI takes care of that, but we can hide the service kind because we need to show that it's active. With your change we _should_ be all set since the users won't be able to get around UI by creating services with GraphQL calls.
