### ISSUE TITLE
settings: design the user flow when an SSH key needs to be provisioned

### ISSUE THREAD

**Issue by LawnGnome** [sourcegraph/sourcegraph#16892]
When a user is adding a user credential to use with campaigns, they also need to configure SSH when the code host uses SSH to clone and push repositories. This will likely take the form of prompting the user during or after the modal where they enter their personal access token to copy the given public key and paste it into their code host settings as an authorised key.

Part of #16888.

**Comment by LawnGnome** [comment]
I don't know if we want to do this as a single modal any more, but here's how we might extend the existing modal:

![image](https://user-images.githubusercontent.com/229984/102563487-3f82c300-408e-11eb-8212-1285f237d64f.png)

**Comment by eseliger** [comment]
This is done
