### ISSUE TITLE
Test plan for management console

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#1689]
Test plan:

1. Start an older Sourcegraph version (anything before 3.0).
2. Ensure you can see repositories and search.
3. Edit your site config, set `"maxReposToSearch": 1337`.
4. Edit your site config, set `"auth.sessionExpiry": "1337h"`.
5. Stop the old Sourcegraph version. Start the latest 3.0 version (see #dev-announce for instructions).
6. Ensure you can still see repositories and search as expected.
7. Visit the site config area, check that `maxReposToSearch` is still `1337` and that `auth.sessionExpiry` is no longer there.
8. Edit and save the `maxReposToSearch` value. Refresh and ensure it persists.
9. Following [the management console docs](https://docs.sourcegraph.com/admin/management_console), gain access to your management console.
10. In the management console, check that `auth.sessionExpiry` is set to `1337h` as expected, and that `maxReposToSearch` is NOT there.
11. In the management console, make a change and refresh the page to ensure it persists.
12. In the management console, change `licenseKey` to an invalid value.
13. Confirm you are locked out of your instance.
14. Go back to the management console, change `licenseKey` back to a valid value, confirm you are no longer locked out of your instance.

@sourcegraph team, please reply to this issue with answers to:

1. Which test plan step you ultimately got to.
2. Did you encounter any issues? (**link to separate issues, do not put them here**)
3. Did you test a Server or Cluster deployment?

**Comment by slimsag** [comment]
@nicksnyder @ggilmore @francisschmaltz Could you please be my testers? :)

**Comment by nicksnyder** [comment]
I tested server deployment and looks good!

I ran into one issue but wasn't able to reproduce the second time I tried: https://github.com/sourcegraph/sourcegraph/issues/1729 so not sure if it is a real issue (probably not).

One open question: https://github.com/sourcegraph/sourcegraph/issues/1731

**Comment by ggilmore** [comment]
I wasn't able to complete this test plan today. I'll test it first thing tomorrow morning.

**Comment by ggilmore** [comment]
I tested the management console on https://github.com/sourcegraph/deploy-sourcegraph/tree/26a7c6bd16dd5e113d7964e7a53625020dd16c5c. Besides the other UX issues that @slimsag will file, https://github.com/sourcegraph/sourcegraph/issues/1820 is the only other thing that I found.

**Comment by slimsag** [comment]
Filed https://github.com/sourcegraph/sourcegraph/issues/1821 for the primary issue you encountered, and https://github.com/sourcegraph/sourcegraph/issues/1822 for the minor UX issue. I'll address these in 3.0 but neither of these are show-stoppers. :)

**Comment by nicksnyder** [comment]
Can we close this test plan as complete then?

**Comment by francisschmaltz** [comment]
Tested on fresh instance and looks good!

**Comment by slimsag** [comment]
Thanks! Looks like we're good to close this now.
