### ISSUE TITLE
Support merging different commit data for type:diff and type:commit

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#16899]
We merge commit data for queries like `type:commit (author:foo or author:bar)`. But for a query like `(type:commit or type:diff) author:foo` we merge matching commits by URL (so only a commit message or a diff content is shown, not both). A better experience would be to show both the union of commit message and diff content.

**Comment by camdencheek** [comment]
Query with an example commit that demonstrates this: [repo:github.com/sourcegraph/sourcegraph$ (type:commit or type:diff) IsRevisionNotFound](https://k8s.sgdev.org/search?q=repo:github.com/sourcegraph/sourcegraph%24+%28type:commit+or+type:diff%29+IsRevisionNotFound&patternType=literal)
