### ISSUE TITLE
Proposal: Move SQL migration management out of application code

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#16909]
### Context

We currently manage all migrations from the application side (i.e. frontend) — on startup, migrations are applied by the first frontend instance acquiring the Postgres advisory lock. This has the benefit that it works across all our deployment types without additional infrastructure.

### Problem

However, there are a few issues with this approach, that have been coming to surface:

1. Running migrations on service start-up makes it easy for engineers to write code that isn't backwards compatible with a previous version of the schema. Assuming that the code and schema change are updated atomically is a mistake that leads to downtime, since deployments are not atomic, and there are many services that read from the database.
2. We have a need of managing non-application migrations that don't relate to application code directly (e.g. pganalyze schema changes, functions, etc, which have been applied by hand).

### Proposal

I propose we completely decouple SQL migrations from application code by introducing a separate `migrator` service which runs migrations on container startup. This requires the following changes:

1. Create `migrator` service under `cmd/migrator` for running SQL migrations under its tree (i.e. `frontend`, `code-intel`, `pg-analyze`). We could also just use the `migrate` binary directly instead of wrapping it in our own code.
1. Introduce `migrator` service in each of our deployment types (K8S, docker-compose, single docker image).
1. Change application code to not run migrations, and simply connect to the database.
1. Document requirement for changing code and schemas in a backwards compatible way and provide a robust CI check for that.
1. Encode pg-analyze migrations in it.

### Open questions

- What's the best way to encode this sort of container in each of our deployment types? This is sort of a one shot job that runs on startup and exits, not a long living service.
- Do you foresee any customer pains in moving to this?

**Comment by efritz** [comment]
> Change application code to not run migrations, and simply connect to the database.

Would we still ensure the expected minimum migration number on startup?

**Comment by tsenart** [comment]
> Would we still ensure the expected minimum migration number on startup?

Would that defeat the purpose of enforcing writing backwards compatible code?

**Comment by efritz** [comment]
> Would that defeat the purpose of enforcing writing backwards compatible code?

That would be forwards compatibility, which is ... useless.

Say we're running version N and we deploy N+1 with a new table. We need to ensure the frontends for version N+1 don't start accepting traffic until the N+1 migration is there, but that migration should not affect currently executing frontends on version N (backwards compatibility).

What you suggested is having N+1 frontends being able to operate on previous migrations, which doesn't buy anything.

**Comment by efritz** [comment]
Also note that this will change the way we think about deployments. See the [slack thread](https://sourcegraph.slack.com/archives/CSCFMFXS5/p1608214953063400?thread_ts=1608209518.058800&cid=CSCFMFXS5) for some discussion between @tsenart and myself.

Namely, the following idea

> we should not think of deployements as coordinated lock step operations of every service

will no longer hold in general as we require a pre-step to run before deploying new code that depends on a migration having previously run.

**Comment by tsenart** [comment]
> What you suggested is having N+1 frontends being able to operate on previous migrations, which doesn't buy anything.

It buys them being able to be rolled out without introducing errors. Deploys are not atomic.

**Comment by efritz** [comment]
@tsenart How do you suggest that the following deployment scenario looks like: _Campaigns needs to track new data in for a changeset_. Currently this process looks like:

1. Add a nullable column to the changeset
2. Update code to read and write new column
3. Ensure a deployment occurs
4. Backfill default values and set non-nullable (optional)
5. Ensure another deployment occurs

We can't perform step 2 if we need to be able to work properly against the existing schema.

**Comment by pecigonzalo** [comment]
@efritz Is that process per version?  Otherwise that only happens in sourcegraph.com in customer environments they follow releases and we should keep that loop across an entire release version IMO.

**Comment by efritz** [comment]
@pecigonzalo Yes the "ensure deployment occurs" is basically "wait a month" to do it properly. This should be less of an issue if we reduce the release cadence.

**Comment by efritz** [comment]
But even just the first two steps don't match (what I understand to be) @tsenart's description.

**Comment by tsenart** [comment]
> 1. Add a nullable column to the changeset
> 2. Update code to read and write new column
> 3. Ensure a deployment occurs
> 4. Backfill default values and set non-nullable (optional)
> 5. Ensure another deployment occurs

> We can't perform step 2 if we need to be able to work properly against the existing schema.

@efritz: Sorry for the late response here. Back from holidays now. You're right, we can't 100% decouple migrations from new code. We need a way for N+1 $SERVICE to ensure the schema changes they depend on have been applied, so, yes, I think asserting an expected minimum schema version at startup makes sense, in combination with migrations always running before code deployments.

**Comment by efritz** [comment]
See https://github.com/sourcegraph/sourcegraph/issues/25247 for implementation.
