### ISSUE TITLE
auto-indexing: Add docker/src-cli command wall clock limits

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#16915]
There are currently no time limits for index jobs. We should have a default maximum time and override-able time that can be put into configuration, up to a certain system hard limit. This will stop people from effectively blocking the index queue with slow (un-finish-able) jobs as well as people trying to run bitcoin miners on our compute infra.

**Comment by andreeleuterio** [comment]
just commenting here because I don't know another way of getting notifications for a specific issue 🤷‍♂️

**Comment by efritz** [comment]
Fixed in https://github.com/sourcegraph/sourcegraph/pull/20465.
