### ISSUE TITLE
External Services -> GitHub requires a "url" field but doesn't tell you

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#1694]
Start a clean instance. Add a `GitHub` external service connection like so:

![image](https://user-images.githubusercontent.com/3173176/50806439-de53f180-12b3-11e9-9d99-f93fdca39249.png)

No repositories will show up when you visit /site-admin/repositories; if you modify the entry to be:

![image](https://user-images.githubusercontent.com/3173176/50806475-03e0fb00-12b4-11e9-8bb7-6770a83a9de8.png)

Then it suddenly works.

Issues:

1. You are not informed that this is a required field anywhere.
2. The default when you ctrl+space select the `url` field appears to be `https://github.com`, but why is that default not actually applied when the field is omitted?

@nicksnyder I am assigning you because I don't know who should own this.

**Comment by francisschmaltz** [comment]
@nicksnyder We should assume GitHub.com (and the titular host for other options) without requiring a URL.

**Comment by nicksnyder** [comment]
The previous behavior in 2.x was to auto fill with the correct url when the (now removed) "Add GitHub.com repository" button was clicked. It reported an error if you saved a config that did not have an explicit url: 
![image](https://user-images.githubusercontent.com/754768/50814083-482cc500-12cd-11e9-91ab-d8ab9fd801d9.png)

The current external services implementation does neither, and I think it should:
- [ ] Pre-populate relevant config per code host type
- [ ] Validate json on the backend

**Comment by nicksnyder** [comment]
The PR I merged solves the immediate issue of populating default values in the config. More specific schema validation still doesn't happen on the backend (but I don't think it happened before either) so I created a followup issue for that (backlog): https://github.com/sourcegraph/sourcegraph/issues/1721
