### ISSUE TITLE
Handling async repo list fetching

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#16948]
## Problem

When the user finishes selecting repositories from the "Add/manage repositories" view, the current behaviour is to immediately redirect them to the "Repositories" view with the list of all repositories. When the user chooses to "Sync all repositories" the request is made asynchronously by our backend, because it may take a long time to fetch a list of all the repositories from the code hosts. The problem with this immediate redirect to the "Repositories" view is we may not have finished fetching the list of repositories yet, so they just get a blank screen.

In this scenario, we're just fetching the repository listing—not cloning the repos.

A "loading" state on the "Repositories" view isn't the right timing/context for this fetching activity. We fetch those repositories in response to the user's save action—which is when something might go wrong. By the time the user is redirected to the "Repositories" view, they should see the **outcome** of their action, not the action in progress. This is even more important when there may be **some** repositories ready to list, but not all.

## Proposal

(This is tentative depending on our worst-case scenarios.)

Instead, I propose we communicate what's going on in the context of the "Add/manage repositories" view. This way, we surface the status in the context of the user's immediate action. When the user clicks save, we'll disable the save button and display a loading state in the button that will update periodically. This gives us way more leeway time-wise and also gives us a microcopy opportunity to turn a potential delay into a positive emotional moment.

### A relatively quick async process would look like this:

![CleanShot 2020-12-21 at 15 00 47](https://user-images.githubusercontent.com/6304497/102784972-72ce9600-439d-11eb-831b-757c98a375c3.gif)

### A longer process would look like this:

![CleanShot 2020-12-21 at 15 02 22](https://user-images.githubusercontent.com/6304497/102785081-ac070600-439d-11eb-88cd-977bec17f2ca.gif)

### And a really long process would look like this:

![CleanShot 2020-12-21 at 15 03 01](https://user-images.githubusercontent.com/6304497/102785101-b4f7d780-439d-11eb-85c9-8cd063d9ddaa.gif)

That was a full 15 seconds of async delay!

### Handling the user navigating away:

If the user leaves the view while the async fetch is underway, it won't interrupt the fetch (since it's being handled in the backend). If they visit the "Repositories" view before fetching is complete, we will show a message to make sure they know it's incomplete.

<img width="1294" alt="image" src="https://user-images.githubusercontent.com/6304497/102785573-81697d00-439e-11eb-83c7-8723f48a59a0.png">

### Try it for yourself!

- [Interactive prototype available on Figma](https://www.figma.com/proto/zXvqCASHDzmvKbrAl1EVsd/Public-and-Private-Repos-for-Users-on-Cloud?node-id=1483%3A1157&viewport=477%2C441%2C0.20413458347320557&scaling=scale-down)

**Comment by artemruts** [comment]
@quinnkeast, I think this is great! User's definitely will get confused by a blank page and may try to re-select repos again 👍 
My only questions are:

1. Do we support partial results from repositories API, displaying some while the rest of the repos is still fetching?
2. If the user leaves the view and sees "Some repositories are still..." message, do we expect the page to refresh once all of the repos are fetched/repos list update dynamically/user to refresh manually?

**Comment by quinnkeast** [comment]
Great questions!

>1. Do we support partial results from repositories API, displaying some while the rest of the repos is still fetching?

This I'm not sure about, and will affect the proposal for sure—but it looks like we'll have to wait til the team's back from holidays for a firm answer!

>2. If the user leaves the view and sees "Some repositories are still..." message, do we expect the page to refresh once all of the repos are fetched/repos list update dynamically/user to refresh manually?

If the page shows partial results, it shouldn't refresh, since the user might be viewing the content and should maintain total control. In that case, we can update the message itself and provide a "Reload page" action in the message.

If the page doesn't show partial results, then we can refresh it when it's ready.

**Comment by quinnkeast** [comment]
Related, if the user:

1. Goes to "Manage repos" view and selects "all repos."
2. Returns to the "Repos" view.
3. Returns to the "Manage repos" view and changes to a single selected repository, instead of all.

When they next return to the "Repos" view, they should already see the updated selection, rather than the previous selection. I understand this is tied to when the repo-updater job runs.

**Ideally,** the exact same loading process would be used so that when the user hits "Save changes" on the "Manage repos" view and then returns to the "Repos" view, it accurately reflects their selections. Is there a way we can immediately remove the no-longer-selected repos from the "Repos" view, even if the repos haven't actually been removed by the repo-updater job yet?
