### ISSUE TITLE
[deploy-sourcegraph] language servers migration steps should be more concrete 

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#1695]
_See https://github.com/sourcegraph/deploy-sourcegraph_

https://github.com/sourcegraph/deploy-sourcegraph/blob/d75ebf89c269a0fe70400559ca7741c7a38ac23a/docs/migrate.md#language-server-deployment provides a nice overview of the changes, but this document should be written with concrete steps/commands whenever possible for people to run. 

Examples: 
- What happened to the Python language server? Why is it labeled "WIP"? Where is the java language support?
- Am I expected to deploy https://sourcegraph.com/extensions/sourcegraph/lang-typescript separately? Does it need to be in a separate cluster? Does it need a static IP? How do I set up so that the deployment is managed by kubectl-apply-all.sh? 
- It seems like there is no parent git repository for https://sourcegraph.com/extensions/sourcegraph/lang-typescript's K8s deployment. How will I be notified about any upgrades?

**Comment by chrismwendt** [comment]
Jotting down notes:

- I plan to wrap up the Python language server on Wednesday to remove the WIP status. AFAIK Java will not ship in 3.0
- The site admin will deploy language servers, likely in the same k8s cluster. They will need a static IP each. I've been manually reserving+copying a static IP address into the lang-go deployment YAML.
- I'm not sure about upgrades, they'll probably be rare and might not be worth figuring out a way to automate notifications right now.

**Comment by nicksnyder** [comment]
> The site admin will deploy language servers, likely in the same k8s cluster. They will need a static IP each. I've been manually reserving+copying a static IP address into the lang-go deployment YAML.

Where is this going to be documented?

**Comment by nicksnyder** [comment]
My notes:
- [ ] @ggilmore create a new 3.0 migration readme in deploy-sourcegraph for https://github.com/sourcegraph/deploy-sourcegraph/blob/d75ebf89c269a0fe70400559ca7741c7a38ac23a/docs/migrate.md#language-server-deployment. I think we need the bare minimum documentation here, just link to https://docs.sourcegraph.com/user/code_intelligence
- [ ] @chrismwendt make language support more discoverable on https://docs.sourcegraph.com/. "Code intelligence" is the only hint right now, but other words like "language support" and specific languages (e.g. Go, TypeScript/JavaScript, Python) would aid discoverability
- [ ] @chrismwendt Add general documentation to https://docs.sourcegraph.com/user/code_intelligence about how customers should manage code intel deployments (and any other recommendations that would apply across language servers, either for docker image or k8s).

**Comment by chrismwendt** [comment]
I added some top level documentation and a section about deployment, and edited the comment above with links to the commits.
