### ISSUE TITLE
Clicking on README.md link for an internal markdown link throws error

### ISSUE THREAD

**Issue by jbelmont** [sourcegraph/sourcegraph#17]
![screen shot 2017-07-12 at 11 26 12 am](https://user-images.githubusercontent.com/2974744/28125672-46d98952-66f5-11e7-83ec-9a62d1f5e58e.png)

User Scenario:

I was traversing the following repository:

https://github.com/legastero/stanza.io

Action:

I was reading the `README.MD` file and tried to click on the link `API Reference` and immediately saw the error above. I tried this on github and the link seems to work fine.

**Comment by jbelmont** [comment]
I tried adding the label `BUG` but I don't have authorization to set `LABEL` although we you create an issue it prompts you to do so.

**Comment by beyang** [comment]
Thanks for filing. It's on our todo list and we'll post back here when it's fixed!

**Comment by keegancsmith** [comment]
This seems to be working now.
