### ISSUE TITLE
Update label for code monitor active toggle

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#17039]
In the original design, I used the phrase "**We will watch for the trigger and run actions in response**" in the active toggle for the code monitor.

<img width="590" alt="image" src="https://user-images.githubusercontent.com/6304497/103644033-f966a400-4f55-11eb-9ac9-4ecc8544437f.png">

Based on feedback (thanks @rrhyne), we should update this to: "**Code monitor will watch for the trigger and run actions in response**," which better reflects what's happening ("we" aren't doing anything, the code monitor is).

As well, when the code monitor is inactive, we should change the helper copy to: "**Code monitor will not respond to trigger events**".

**Comment by quinnkeast** [comment]
Just realized that #17795 doesn't address this in full:

>As well, when the code monitor is inactive, we should change the helper copy to: "Code monitor will not respond to trigger events".

Related, the label "Active" should probably switch to "Inactive." The toggle in the email notification action should probably behave similarly, because when they're both toggled "off," the label implies they're both "on."

<img width="229" alt="CleanShot 2021-02-08 at 11 49 26@2x" src="https://user-images.githubusercontent.com/6304497/107209911-bd66a900-6a03-11eb-9b3a-3d8e79fef28f.png">

@AlicjaSuska @limitedmage wdyt?

**Comment by AlicjaSuska** [comment]
@quinnkeast +1 - label should change to describe the state of the toggle
