### ISSUE TITLE
Remove testbed vault

### ISSUE THREAD

**Issue by ElizabethStirling** [sourcegraph/sourcegraph#17046]
Work to be done in our infrastructure repo.

Current state: Testbed vault is in `infrastructure/vault`  in project `sourcegraph-vault-stage`

~Better state: Vault is in `infrastructure/security/vault`  in project `sourcegraph-security-vault-testbed` , and the `sourcegraph-vault-stage` project is deleted along with `infrastructure/vault`. The data in the current testbed vault can safely be deleted.~

Updated better state:
Testbed vault and `sourcegraph-vault-stage` are deleted

Note that this also requires creating the project `sourcegraph-security-vault-testbed`.

**Comment by daxmc99** [comment]
Completed
