### ISSUE TITLE
Test plan for code intelligence

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#1705]
While testing code intelligence, imagine you’re a site admin setting up language support for the first time because they are the people who will get their company from 1 to 20 users.

For each language (Go, TypeScript, Python):

* Deploy the language server in a Docker container by following: https://docs.sourcegraph.com
* Find a random repository (e.g. from https://github.com/search?o=desc&q=language%3Ago&s=stars&type=Repositories) and make sure hovers/defs/refs work
* Go-specific
   * Cross-repository defs/refs
   * Private repositories
   * Private dependencies via SSH or netrc
      * https://github.com/sourcegraph/sample-private-go-repo (private repository)
      * https://github.com/sourcegraph/sample-public-go-repo (public with a dependency on the private repository above)
      * SSH instructions: https://github.com/sourcegraph/lang-go#private-dependencies-via-ssh-keys
      * Netrc instructions: https://github.com/sourcegraph/lang-go#private-dependencies-via-netrc
   * Revoke your access token and restart the language server, then make sure the access token gets recreated upon refreshing the page
* TypeScript-specific **do not test TypeScript until this plan has been filled out** TODO(felix)
   * Cross-repo defs/refs
   * Dependency fetching
   * Private repositories
   * Private dependencies
   * Progress
* Python-specific

Testers should comment on this issue when they have tested.
This issue should be closed after a sufficient number of people have tested.

**Comment by chrismwendt** [comment]
I split this into these issues:

- https://github.com/sourcegraph/sourcegraph/issues/1717
- https://github.com/sourcegraph/sourcegraph/issues/1718
- https://github.com/sourcegraph/sourcegraph/issues/1719
