### ISSUE TITLE
monitoring: Define configuration types for new monitoring API

### ISSUE THREAD

**Issue by davejrt** [sourcegraph/sourcegraph#17060]
Identify new configurations we want to support  and determine the best way to implement those, by either using the full SDK or creating options to specify from a predefined list:

eg: by looking at the Cloud dashboards, such as "Git Server - Cloud",

**Comment by bobheadxi** [comment]
We confirmed with Cloud that the Git Server dashboard is the only thing they use, and will use replicating that as a starting point for customization demo (https://github.com/sourcegraph/sourcegraph/issues/17062).

As part of that, we also settled on just providing:

* Observable
* sdk.GraphPanel

As options when building custom options, which we will implement in https://github.com/sourcegraph/sourcegraph/issues/17061
