### ISSUE TITLE
Ensure all sourcegraph images have a registry specified

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#17066]
Some images do not currently have registry specified, they all should. 

Example: https://github.com/sourcegraph/deploy-sourcegraph/blob/master/base/pgsql/pgsql.Deployment.yaml#L29

This was found during our Dhall work. This cannot be finished until https://github.com/sourcegraph/sourcegraph/issues/14132 is done.

**Comment by pecigonzalo** [comment]
@daxmc99 Removing from the sprints.

**Comment by daxmc99** [comment]
Per https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/deploy-sourcegraph%24%40master+image:.*&patternType=regexp 
This is fixed
