### ISSUE TITLE
Link to previous version docs

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1706]
The docs.sourcegraph.com site should have a prominent link either in the header or on the index and other relevant pages to pages under https://docs.sourcegraph.com/@v2.13.5, so that people on 2.13 or 2.x can find the relevant docs.

**Comment by beyang** [comment]
The revspec-based option actually seems better to me, because that way the docs are kept up-to-date for *each* version automatically.

**Comment by sqs** [comment]
Fixed in https://github.com/sourcegraph/docs.sourcegraph.com/commit/aca93f1b23e981e6b03cfd3f4656fea3d833c432. Modeled on how PostgreSQL does it, like at https://www.postgresql.org/docs/9.3/sql-update.html.

![screenshot from 2019-01-09 23-05-18](https://user-images.githubusercontent.com/1976/50951826-6a584b80-1463-11e9-9855-73cb63f5b1e4.png)
![screenshot from 2019-01-09 23-05-12](https://user-images.githubusercontent.com/1976/50951827-6a584b80-1463-11e9-9eec-bc4c29b4f200.png)

Try it (look for the "Version:" line on each of these pages):

- https://docs.sourcegraph.com/admin (next release version)
- https://docs.sourcegraph.com/@v2.13.5/admin (current release)
- https://docs.sourcegraph.com/@v2.13.2/admin (neither next nor current)

**Comment by nicksnyder** [comment]
Should the current release be the default?

**Comment by sqs** [comment]
Overall no. Half of docs changes are improvements that apply to all versions, half are actual breaking-ish changes. If users need version-specific docs, they need to choose their specific version and not rely on current being close enough. Most doc sites do it the way I’ve described. It would be an improvement to offer a version selector but right now it doesn’t matter since we only have these docs for 3.0 and 2.13 (2.12 docs were in a different format).
