### ISSUE TITLE
Mark same email as verified the second time displays an ugly raw DB error

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#17073]
When two users alice and bob both added the same email "user@example.com", and bob tries to verify the email after alice has verified we got the following ugly raw DB error:

>Pq: conflicting key value violates exclusion constraint "user_emails_unique_verified_email"

<img width="659" alt="CleanShot 2021-01-06 at 17 11 17@2x" src="https://user-images.githubusercontent.com/2946214/103750742-3314d900-5042-11eb-8ff0-3f2ea37556e9.png">

We should detect and display a user-friendly message, something like:

"Someone else has already verified this email address, please contact site-admin for support if you believe this is a problem."

**Comment by tharun208** [comment]
I like to work on this issue.

**Comment by unknwon** [comment]
@tharun208 Thanks, please go ahead :)

**Comment by ryanslade** [comment]
@tharun208 Are you still planning to work on this?
