### ISSUE TITLE
Test plan for deployment

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#1708]
Get everyone on the engineering team to test the deployment process.

- [x] @nicksnyder 
- [x] @KattMingMing 
- [x] @sqs 
- [x] @beyang 
- [x] @slimsag 
- [x] @attfarhan 
- [x] @vanesa 
- [x] @keegancsmith 
- [x] @lguychard 
- [x] @tsenart 
- [x] @felixfbecker 
- [ ] @ijsnow 
- [x] @chrismwendt

**Comment by nicksnyder** [comment]
Given that this has been tested a lot, it is no longer a release blocker. @ggilmore you should still follow up with the remaining people when they are available.

**Comment by sqs** [comment]
Checked myself off because I deployed (https://github.com/sourcegraph/deploy-sourcegraph-dot-com/commit/7e1fecea2120a18b021acf7f2a4bd1493a763a5a and then ran kubectl-apply-all.sh).

**Comment by nicksnyder** [comment]
@beyang @ijsnow can you please deploy sourcegraph.com (even if it is a no-op deploy) and check your name off this list.

**Comment by nicksnyder** [comment]
Going to close this. @ijsnow you should still deploy sourcegraph.com so you know how to do it.
