### ISSUE TITLE
Loading/pending state for repository syncs after adding repos.

### ISSUE THREAD

**Issue by arussellsaw** [sourcegraph/sourcegraph#17107]
Repo syncing is async, so when a user goes through the manage repositories page (https://github.com/sourcegraph/sourcegraph/pull/17022) and hits save, they'll be dropped back to an empty or unchanged list of repositories. we should implement some kind of indication that there's a background sync going on.

There are two possible approaches:

### A static message (quick to implement, worse UX)
We can drop the user back to the page with a message parameter indicating that a background job is running. This wouldn't respond to the sync finishing, just lets the user know to check back later. This is the quickest/easiest option at the cost of UX.

### Infer loading state by querying repo-updater job status (will take longer to implement, better UX)
Add a new graphql endpoint to query the state of repo-updater background jobs, we'd need to somehow identify who the repo-updater jobs belong to in order to only show the loading state to the user who initiated the job. i don't know how complicated that would be. as i'm not familiar with the schema of our background jobs.

Considering we're constrained on frontend work and aiming to hit a release milestone soon i'd recommend option 1, but happy to be overruled.

**Comment by arussellsaw** [comment]
just saw this issue https://github.com/sourcegraph/sourcegraph/issues/16948

**Comment by quinnkeast** [comment]
My mistake for not referencing that issue here!

**Comment by ryanslade** [comment]
We could get the most recent job per external service based on the owner with a something like this:

```sql
select distinct on (es.id) job.state, job.finished_at from
external_service_sync_jobs job
join external_services es ON job.external_service_id = es.id
where es.namespace_user_id = 1
order by es.id, job.id desc;
```

There's a delay between saving an external service for the first time and the initial job being created though. So we probably want to show a message if either the user has an external service with zero jobs or they have at least one job in the `queued` or `processing` state.

Not saying we need to implement this option now, your call, but it shouldn't be a huge amount of work.

**Comment by quinnkeast** [comment]
@ryanslade let's move this conversation to #16948.
