### ISSUE TITLE
Code monitoring event logging

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#17124]
RFC: https://docs.google.com/document/d/1-Uj3Gl0-WrJsz_XH3QtHYl8jIf-cybeWE2ScZNCwWTY/edit#heading=h.trqab8y0kufp

This is a list of events that need to be logged in the code monitoring frontend, using EventLogger. 

- [ ] ViewCodeMonitorPage. This can be achieved by using `logViewEvent`. Example: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductSubscriptionPage.tsx#L62:32
- [ ] CodeMonitorCreated. This should include a `location` parameter, which specifies whether the code monitor is being created via the search results page or code monitoring form. Example: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/search/input/QueryInput.tsx
- [ ] CodeMonitorEmailLinkClicked. We can track this by adding a query parameter to URLs in our notification emails. We can parse for that query parameter when a user lands on a page, and if the query param exists, we'll log this event.

**Comment by ebrodymoore** [comment]
For logistics on this, it sounds like code monitoring will be available in 3.26 (without the feature flag). If so, we need to get these events in and then switch the pings over from saved search events to these code monitoring events within the next 4 weeks. Does that sound right on timing?

And a side note for whoever ends up doing this work, I'd love to watch over your shoulder if possible. I'm curious how you determine where the right place to add the line of eventLogger code is.
