### ISSUE TITLE
Add "intent" delay to search helpers on hover

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#17126]
## Problem

We have helpers that appear when the user hovers over a segment of a search query. However, these begin to appear even when the user is actively moving their cursor without intent to hover over any particular element. This creates a visual distraction that can quickly become annoying or irritating, which would be a disappointing outcome given the educational value the helpers provide.

https://user-images.githubusercontent.com/6304497/103988850-0e7a4780-518f-11eb-9fb4-73a5fc008591.mp4

## Proposal

Add a small delay to check for **intent** before displaying the helper. As long as the cursor is in motion, it shouldn't appear. When the cursor is no longer in motion and a very short delay has passed, show the hover. 

This behaviour was captured in the [old hoverIntent jQuery plugin](https://briancherne.github.io/jquery-hoverIntent/)—it's a good reference for the behaviour.

**Comment by lguychard** [comment]
We should be able to tweak this using Monaco's [`IEditorHoverOptions`](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ieditorhoveroptions.html)
