### ISSUE TITLE
Proposed change: remove toggle from code monitor list view

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#17129]
Based on our testing with Nutanix and our own internal use, I think the toggle to enable/disable a code monitor from the list view is overkill. The action is simple enough from within the code monitor itself, and there isn't a clear use case for enabling/disabling many at once.

We can improve this UI by removing the toggle from this location, and making the entire code monitor item clickable to view the config. The "Edit" label can remain, because it provides a good target and suggests the action that will take place when the user clicks it.

![image](https://user-images.githubusercontent.com/6304497/104010968-a5ee9300-51ad-11eb-9b70-a9dcf05a3b61.png)

Love to hear your thoughts!

**Comment by lguychard** [comment]
@novoselrok can you take this?

**Comment by novoselrok** [comment]
@lguychard Sure 👍

**Comment by quinnkeast** [comment]
Based on discussion with @novoselrok, with this change, it makes sense to unify the "cards" throughout the code monitoring UI and their handling of hover states.

This means trigger and action cards in the create/manage view will have the blue border hover state after configuration, as will the code monitor cards in the code monitoring list view.

This is a pretty minimal change that can be done in styles alone. The "Edit" label can remain, because it communicates the action nicely. Note that this should probably be done on top of #17132, which fixes a content jump related to the hover border.

<img width="788" alt="image" src="https://user-images.githubusercontent.com/6304497/104026041-b6ab0300-51c5-11eb-8336-92974a772e6a.png">

<img width="886" alt="image" src="https://user-images.githubusercontent.com/6304497/104026088-c75b7900-51c5-11eb-8216-df8b9007c84f.png">
