### ISSUE TITLE
Experimental config for GitHub auth provider should be in management console not site-admin

### ISSUE THREAD

**Issue by francisschmaltz** [sourcegraph/sourcegraph#1713]
Currently you can enable and disable the GitHub auth provider in the site-admin. As auth has moved to the management console so should experimental settings for auth.

<img width="333" alt="screen shot 2019-01-08 at 11 52 15 am" src="https://user-images.githubusercontent.com/11583013/50855276-3c2c1c00-133c-11e9-9b43-23066e163ee7.png">

**Comment by francisschmaltz** [comment]
@beyang can we target this for 3.0 or no?

**Comment by slimsag** [comment]
Experimental features should remain under the site config area unless there is something about them that could inherently break Sourcegraph, I think.

Requiring them to be set in the management console also increases the barrier to getting users to test them for us.

**Comment by francisschmaltz** [comment]
> unless there is something about them that could inherently break Sourcegraph

@slimsag turning this off could disable auth for all users. I don't know if this could count as *breaking* but it does feel like a mild concern that a user without access to the management console could essentially disable auth for the instance.

**Comment by slimsag** [comment]
By breaking, I mean "If the option was changed, could it prevent the same site admin who changed it from going back to the site admin area and unchanging it?"

i.e., could it also prevent the site admin themselves from authenticating and fixing the issue?

- If yes, I agree this has to be moved into the management console.
- If no, it should stay in the site config area I think.

**Comment by beyang** [comment]
I'll remove the experimental feature flags. They are unnecessary given that these features will undergo standard QA for 3.0 release.
