### ISSUE TITLE
Implement pagination component

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#17136]
## Problem

For the current Cloud efforts around helping our users add their own code to Sourcegraph Cloud, we have a few places where we will need to be able to show a paginated list of many items, such as a long list of repositories. Infinite loading isn't appropriate for this particular interface element.

<img width="893" alt="image" src="https://user-images.githubusercontent.com/6304497/104032085-f2e26180-51cd-11eb-9108-c64a52144a53.png">

While we have a simple pagination element in place in the short term, it's not complete or sustainable.

## Proposal

We should implement a new pagination component for both the Wildcard design system and in code.

In general, our needs are for a pagination component that can handle a large set of pages gracefully, based on client data or with backend pagination. In the moment, we're only paginating data on the client.

I've created an experimental design for this pagination that also discusses logic (heavily influenced by GitHub's own pagination, which gracefully and familiarly handles huge page counts). **However, as pagination is its own hairy mess, I'd love the team's feedback on the best approach to this, whether that's doing it ourselves or using an existing library.**

**Design experiment:**

<a href="https://www.figma.com/file/IFZmcl5QoFT1KQHo6SMm4f/Pagination-Component-Proposal?node-id=627%3A0">
<img width="870" alt="CleanShot 2021-03-03 at 15 59 24@2x" src="https://user-images.githubusercontent.com/6304497/109824832-7bfb9f00-7c39-11eb-9d36-fa41e31ae478.png"></a>

- [View on Figma](https://www.figma.com/file/IFZmcl5QoFT1KQHo6SMm4f/Pagination-Component-Proposal?node-id=627%3A0)

**Comment by quinnkeast** [comment]
@rrhyne mentioned we might be better using an existing pagination component/library that takes care of the logic for us. I'm happy to do this as well!

**Comment by umpox** [comment]
I think this is great. Do we have an example right now where we're using this pattern, or is this completely new? My only concern is how we receive data from the backend. It's important that we get `totalPages` back from the API, although we could still build this component in isolation.

I think we can build this out ourselves, it'll give us a lot more control over future changes. I'd say this should be the case for most scoped out components, unless we have a particularly good reason. Otherwise we might find ourselves fighting against component code to achieve a UX variation 😃 

Design thought:
- When we hit the maximum items (referred in the design as many) we should keep the page selector at a fixed width. In the current designs it expands as a user clicks more pages, this would be a bad UX I think. Example: https://material-ui.com/components/pagination/
- Showing 8 items seems quite a lot on mobile. I feel like we could specify a `maxItems` prop and we work how many we are able to show based on the users screen width. I imagine it'll be best to use a little bit of JS for this but I think it'll greatly improve a users mobile experience.

**Comment by quinnkeast** [comment]
>Do we have an example right now where we're using this pattern, or is this completely new?

I believe the only place we're using this right now is the "Manage repos" view for the new Cloud work.

>My only concern is how we receive data from the backend. It's important that we get totalPages back from the API, although we could still build this component in isolation.

For the "Manage repos" view, we have a weird bit of complexity: we don't paginate on the server, as we're taking and combining data from multiple code hosts (e.g. 210 repos from GitHub, 18 from GitLab). For this view, we're paginating on the client.

>When we hit the maximum items (referred in the design as many) we should still keep the page selector at a fixed width. In the current designs it expands as a user clicks more pages, this would be a bad UX I think. Example: https://material-ui.com/components/pagination/

I'm game to make this work! I don't think we need a design spec for this, as it'll be an implementation detail—but let me know if I'm wrong about this.

>Showing 8 items seems quite a lot on mobile. I feel like we could specify a maxItems prop and we work how many we are able to show based on the users screen width. I imagine it'll be best to use a little bit of JS for this but I think it'll greatly improve a users mobile experience.

Works for me. The "Manage repos" view this is being used on is not optimizing for mobile use, but I can see future cases where this would become a need.

**Comment by umpox** [comment]
Hey @quinnkeast

Do you think we can trial our [proposed process for implementing design system components](https://docs.google.com/document/d/1m4BxPJe39IpgWDz3UrSX6IEF1hs-UoB1CFMOS8M_vQU/edit#bookmark=id.iwsdm5eqgk7u) here?

I think this component would be a good use case, and we could have a feature retro to discuss how this process went.

**Comment by umpox** [comment]
The main thing would be building out a Figma spec for this component. Ideally something which we can use copy and configure across to different Figma files (I believe this is possible). Then just going through our typical design review process before starting implementation. I'm happy to work with you on this!

**Comment by quinnkeast** [comment]
I would love to say yes, however my time is tight right now—I'm happy to take the [initial Figma design](https://www.figma.com/file/IFZmcl5QoFT1KQHo6SMm4f/Pagination-Component-Proposal?node-id=514%3A345) and create the Figma components in the future (next week or the week following), but I wouldn't want to block implementation right now.

**Comment by quinnkeast** [comment]
@umpox [Please review!](https://www.figma.com/file/IFZmcl5QoFT1KQHo6SMm4f/Pagination-Component-Proposal?node-id=627%3A0)
