### ISSUE TITLE
GitHub internal repositories are not synced when specifying "orgs"

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#17153]
Private repositories are synced correctly (according to the customer), but [internal repositories](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-repository-visibility#about-internal-repositories) are not showing up in the search result.

Customer confirmed that the "token" in the code host connection is able to see the internal repository when curling the GitHub API directly by sending us the output of the following command:

```
curl -v -H "Authorization: token {GitHub token}" https://api.github.com/repos/{name of the organization}/{name of an internal repository}
```

Example config:

```json
{
  "url": "https://github.com",
  "token": "<REDACTED>",
  "authorization": {
    "ttl": "3h"
  },
  "orgs": [
    "<REDACTED>"
  ]
}
```

### Notes

- Internal repositories may not be synced/worked in any case, it's just that the customer is using "orgs" in the code host connection.
- ~~According to [GitHub docs](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-repository-visibility#about-internal-repositories), GHE 2.20+ should have the "internal" visibility option, but our GHE test instance (2.20.8) doesn't have it.~~
- Looking at the [GitHub API docs for listing organization repositories](https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#list-organization-repositories), I do not see a reason why we would not sync for internal repositories (we don't specify any so default):
	>Specifies the types of repositories you want returned. Can be one of all, public, private, forks, sources, member, internal. Default: all.

### TODO

- [x] Confirm if internal repositories show up in the site admin panel: [they can't](https://github.com/sourcegraph/sourcegraph/issues/17153#issuecomment-758052051)
- [x] Make our GHE test instance have the "internal" visibility option (or ~~have a GitHub Enterprise Cloud test org that has this option~~)
	![CleanShot 2021-01-10 at 16 53 32@2x](https://user-images.githubusercontent.com/2946214/104118477-72a23480-5364-11eb-96d1-df9480ef0695.png)

**Comment by christinelovett** [comment]
Sourcegraph Version 3.22

**Comment by tsenart** [comment]
@christinelovett: What resolution timeline is associated with the `ce/p1` label?

**Comment by christinelovett** [comment]
@tsenart we don't have a documented resolution timeline (will raise with CE team) - in this case, the prospect is expected to sign by EOM. https://app.hubspot.com/contacts/2762526/company/1749284052

**Comment by tsenart** [comment]
@unknwon: Can you have the above into consideration as you plan your work?

**Comment by christinelovett** [comment]
The site admin is not able to see the internal repository in the site admin page /site-admin/repositories

**Comment by unknwon** [comment]
Thanks @christinelovett! I added to my current cycle so I can take a look, and I expect majority of time is to set up a test instance/org that has internal visibility option.

**Comment by tsenart** [comment]
> I expect majority of time will be spent on setting up a test instance/org that has internal visibility option.

Can we just upgrade our Github Enteprise instance? cc @pecigonzalo

**Comment by pecigonzalo** [comment]
Created https://github.com/sourcegraph/sourcegraph/issues/17202 to track the upgrade

**Comment by pecigonzalo** [comment]
@unknwon The upgrade has finished, you should be able to test now.

**Comment by unknwon** [comment]
@christinelovett I created an internal repository on the GHE test instance, and used the following code host connection config:

```json
{
  "url": "https://ghe.sgdev.org",
  "token": "<REDACTED>",
  "authorization": {
    "ttl": "3h"
  },
  "orgs": [
    "sourcegraph"
  ]
}
```

I'm able to both search and find the internal repository ("sourcegraph/internal"), and see it in the site-admin panel.

**Comment by christinelovett** [comment]
Ah thank you @unknwon ! I will check in with the customer on the token and report back.

**Comment by christinelovett** [comment]
The token used is the same as the code host connection token. 

- User can manually add internal repos to be searched, they just don't show up automatically
- The sourcegraph extension says “repository not found” for these repos on GitHub
- If internal repos are added like this, they show up but not before adding in the "repos" field:
```
{
 "url": "https://github.com",
 "token": "",
 "authorization": {
   "ttl": "3h"
 },
 "orgs": [
   "toasttab"
 ],
 "repos": [
   "toasttab/toast-employee-app-ios"
 ]
}
```
- Because they are part of toasttab org, the expectation is they should sync - but currently they must be explicitly set in the repos field. 
- This is only true for "internal" repos, private repos are automatically synced

**Comment by unknwon** [comment]
Based on the same symptom of another issue reported: https://sourcegraph.slack.com/archives/CHPC7UX16/p1610752085013800

I'm wondering/correlating if there is something else failing on the way of showing up these missing repos.

**Comment by unknwon** [comment]
> Based on the same symptom of another issue reported: [sourcegraph.slack.com/archives/CHPC7UX16/p1610752085013800](https://sourcegraph.slack.com/archives/CHPC7UX16/p1610752085013800)
> 
> I'm wondering/correlating if there is something else failing on the way of showing up these missing repos.

According to https://github.com/sourcegraph/sourcegraph/issues/17424, these two issues are not related. So I'm going to continue looking into this and think about how we can improve debugging in this area.

**Comment by unknwon** [comment]
Simply having an organization with "GitHub Enterprise Plan" on GitHub.com does not have the option to create "internal" repository, one has to have an [Enterprise account](https://help.github.com/articles/about-enterprise-accounts) (https://github.blog/changelog/2019-10-09-updates-to-internal-repository-visibility-beta/), which then mentioned nowhere how to get one. I'm stepping back until further info to come.

@christinelovett: One last thing the I would suggest the customer to try out to help gather a bit more debugging info:

1. Start "repo-updater" with environment variable `SRC_LOG_LEVEL=DBUG` set.
2. Go to "/site-admin/external-services" and find the external service
3. Go straight to the bottom and click on "Update repositories" (which effectively triggers a sync to list org repositories)
4. In the logs, search for string "github sync: ListOrgRepositories", around that should have a value named "repos", which is the number of repositories Sourcegraph found.
5. Compare this number with number of repos the customer's organization has, is there a difference? If so what's the difference? (Assuming the GitHub token they use has access to all repos under the given organization for this validation to be useful)

**Comment by christinelovett** [comment]
Thank you @unknwon I will share with customer

**Comment by mike-r-mclaughlin** [comment]
We have 2 other deployments that have seen this or a similar issue.  For these deployments, when we call the [GitHub `/org/{org}/repos` API](https://docs.github.com/en/rest/reference/repos) directly, it also does **not** return the `internal` repositories.  For example, if we run:

`curl -u username:token  -v https://github.example.com/api/v3/orgs/sourcegraph/repos?type=all&per_page=1000`

we do not see the `internal` repos.  But, if you pass the `type=internal` parameter, it **does** return them.

Interestingly, other users' tokens work fine (i.e., the default API returns all repositories including `internal`).  We've tried creating new tokens and seen the same behavior.

**Comment by unknwon** [comment]
@mike-r-mclaughlin 

>But, if you pass the type=internal parameter, it does return them.

Nice find! (though sounds like a bug in GitHub.com 😞 )

The mitigation we could have is to always make an additional API call that explicitly wants internal repos.

>Interestingly, other users' tokens work fine

What is the traits of "other users"? It makes me wonder if this is about user roles in an org to be able to include "internal" repos by default.

**Comment by mike-r-mclaughlin** [comment]
> What are the traits of "other users"? It makes me wonder if this is about user roles in an org to be able to include "internal" repos by default.

Customer commented: "from some more testing that I did yesterday it looks like if the API caller/token owner is an owner/member of the org where the internal repos reside, then the API call will return those repos by default"
^ checking with other customer about this too

**Comment by kkom** [comment]
FYI, you're most likely running into a bug in GitHub's API.

Namely, when you have an internal repo it will not be listed in https://docs.github.com/en/rest/reference/repos#list-organization-repositories results if you use a token of a user that doesn't have an explicit role on this repo, **unless** you provide an explicit filter of `type=internal`. This applies equally to the REST and GraphQL APIs, so the bug's deeper in GitHub's stack than just the API frontend layer.

I reported this to GitHub, they acknowledged the problem but said that there is no ETA on fix and closed the ticket. `¯\_(ツ)_/¯`

The workaround is to filter the repos based on their type.

Instead of making one call to `/orgs/{org}/repos`, you can make 3 calls providing `"public"`, `"private"` and `"internal"` as values of the `type` argument. And add up the results (you can get duplicates there because of race conditions those, so better union them instead).

You can also issue one unfiltered call, and then another one to just just the internal repositories, and union the results. That will be a more magic and will include some assumptions about exactly GitHub's API is broken – you may or may not want to include that detail in your code.

PS: I believe this is a separate issue from https://github.com/sourcegraph/sourcegraph/issues/21591 – which is more about how Sourcegraph interprets read permissions to org-internal repos.

**Comment by kkom** [comment]
Oups, sorry, I just quickly scanned the messages and didn't see that @mike-r-mclaughlin already gave this context in https://github.com/sourcegraph/sourcegraph/issues/17153#issuecomment-804364180 and @unknwon suggested the workaround in https://github.com/sourcegraph/sourcegraph/issues/17153#issuecomment-805534274

I hope it was at least helpful to confirm that GitHub acknowledges this as a bug!

**Comment by kkom** [comment]
I was just talking to our Sourcegraph customer engineer about various internal repo issues, wasn't this one fixed in https://github.com/sourcegraph/sourcegraph/pull/22339 ?

**Comment by indradhanush** [comment]
I haven't looked at the work in #22339 yet, so I will need to do manually verify if this bug indeed still exists. I'll update the issue when I find it and then find out more.

**Comment by mrnugget** [comment]
I think this is closed by https://github.com/sourcegraph/sourcegraph/pull/22339
