### ISSUE TITLE
Multiple "View file" buttons on GitLab

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#1716]
- Visit https://gitlab.com/coldnight/ci-test/blob/master/.gitlab-ci.yml
- Right click the Sourcegraph extension -> Enable on this page
- Click OK
- Notice another "View file" button appears

You can actually repeat this process and get more buttons.

![2019-01-08 12 07 44](https://user-images.githubusercontent.com/1387653/50855933-24ee2e00-133e-11e9-9bb9-20297af6262c.gif)

**Comment by lguychard** [comment]
Not a release blocker & likely preexisting 3.0 work, let's treat this in 3.1

**Comment by chrismwendt** [comment]
Thinking out loud here: #1904 fixes this, but it seems like there's some other problem causing this. Multiple buttons appear upon initial page load, and increase in count each time you click "Enable Sourcegraph on this domain", which makes me think this is related to permissions, though I'm not sure how.

**Comment by lguychard** [comment]
Two questions I asked myself while fixing this:
- Why is gitlab not in our default permissions (@ijsnow do you know? Seems like it was removed in f1f5846, but the commit doesn't mention the reason, and the link to the related issue is dead)
- Why is it possible at all to click "Enable Sourcegraph on this domain" *several times*?
