### ISSUE TITLE
Test plan for Go code intelligence

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#1717]
While testing code intelligence, imagine you’re a site admin setting up language support for the first time because they are the people who will get their company from 1 to 20 users.

Copy this plan into new comment and update the comment as you complete the tasks:

```
I'm starting to test Go code intelligence, and here is my status:

- [ ] Spin up a brand new Sourcegraph 3.0 instance `env IMAGE='sourcegraph/server:3.0.0-alpha.9' ./dev/run-server-image.sh`
- [ ] Enable both a popular Go repository from [GitHub](https://github.com/search?o=desc&q=language%3Ago&s=stars&type=Repositories) AND one of its dependencies on your Sourcegraph 3.0 instance
- [ ] Deploy the language server in a Docker container by following: https://docs.sourcegraph.com (if any of this is unclear, report it in a comment below)
- [ ] Test a few hover tooltips, jump-to-definitions, and find-references
- [ ] Test cross-repository jump-to-def from the popular repository to the dependency
- [ ] Test cross-repository find-references from the dependency to the popular repository
- [ ] Set up support for private dependencies by following https://github.com/sourcegraph/lang-go#private-dependencies
- [ ] Enable https://github.com/sourcegraph/sample-private-go-repo
- [ ] Enable https://github.com/sourcegraph/sample-public-go-repo
- [ ] Test jump-to-definition and find-references between the public/private repositories (one depends on the other)
- [ ] Unassign yourself from this issue
```

This issue should be closed after a sufficient number of people have tested.

**Comment by chrismwendt** [comment]
I'm starting to test Go code intelligence, and here is my status:

- [ ] Spin up a brand new Sourcegraph 3.0 instance `env IMAGE='sourcegraph/server:3.0.0-alpha.9' ./dev/run-server-image.sh`
- [ ] Enable both a popular Go repository from [GitHub](https://github.com/search?o=desc&q=language%3Ago&s=stars&type=Repositories) AND one of its dependencies on your Sourcegraph 3.0 instance
- [ ] Deploy the language server in a Docker container by following: https://docs.sourcegraph.com (if any of this is unclear, report it in a comment below)
- [ ] Test a few hover tooltips, jump-to-definitions, and find-references
- [ ] Test cross-repository jump-to-def from the popular repository to the dependency
- [ ] Test cross-repository find-references from the dependency to the popular repository
- [ ] Set up support for private dependencies by following https://github.com/sourcegraph/lang-go#private-dependencies
- [ ] Enable https://github.com/sourcegraph/sample-private-go-repo
- [ ] Enable https://github.com/sourcegraph/sample-public-go-repo
- [ ] Test jump-to-definition and find-references between the public/private repositories (one depends on the other)
- [ ] Unassign yourself from this issue

**Comment by dadlerj** [comment]
I'm starting to test Go code intelligence, and here is my status:

- [ ] Spin up a brand new Sourcegraph 3.0 instance `env IMAGE='sourcegraph/server:3.0.0-alpha.9' ./dev/run-server-image.sh`
- [ ] Enable both a popular Go repository from [GitHub](https://github.com/search?o=desc&q=language%3Ago&s=stars&type=Repositories) AND one of its dependencies on your Sourcegraph 3.0 instance
- [ ] Deploy the language server in a Docker container by following: https://docs.sourcegraph.com (if any of this is unclear, report it in a comment below)
- [ ] Test a few hover tooltips, jump-to-definitions, and find-references
- [ ] Test cross-repository jump-to-def from the popular repository to the dependency
- [ ] Test cross-repository find-references from the dependency to the popular repository
- [ ] Set up support for private dependencies by following https://github.com/sourcegraph/lang-go#private-dependencies
- [ ] Enable https://github.com/sourcegraph/sample-private-go-repo
- [ ] Enable https://github.com/sourcegraph/sample-public-go-repo
- [ ] Test jump-to-definition and find-references between the public/private repositories (one depends on the other)
- [ ] Unassign yourself from this issue

**Comment by chrismwendt** [comment]
@dadlerj Thanks for the feedback on the docs, I took your suggestion and moved the Docker deployment to the top.

**Comment by KattMingMing** [comment]
I'm starting to test Go code intelligence, and here is my status:

- [x] Spin up a brand new Sourcegraph 3.0 instance `env IMAGE='sourcegraph/server:3.0.0-alpha.9' ./dev/run-server-image.sh`
- [x] Enable both a popular Go repository from [GitHub](https://github.com/search?o=desc&q=language%3Ago&s=stars&type=Repositories) AND one of its dependencies on your Sourcegraph 3.0 instance
- [x] Deploy the language server in a Docker container by following: https://docs.sourcegraph.com (if any of this is unclear, report it in a comment below)
- [x] Test a few hover tooltips, jump-to-definitions, and find-references
- [x] Test cross-repository jump-to-def from the popular repository to the dependency
- [x] Test cross-repository find-references from the dependency to the popular repository
- [x] Set up support for private dependencies by following https://github.com/sourcegraph/lang-go#private-dependencies
- [x] Enable https://github.com/sourcegraph/sample-private-go-repo
- [x] Enable https://github.com/sourcegraph/sample-public-go-repo
- [x] Test jump-to-definition and find-references between the public/private repositories (one depends on the other)
- [x] Unassign yourself from this issue

**Comment by nicksnyder** [comment]
@ryan-blunden please still test this as I think it is important. I am going to remove release-blocking since we have 2 independent testers who ran through this.
