### ISSUE TITLE
Test plan for Python code intelligence

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#1719]
While testing code intelligence, imagine you’re a site admin setting up language support for the first time because they are the people who will get their company from 1 to 20 users.

Copy this plan into new comment and update the comment as you complete the tasks:

```
I'm starting to test Python code intelligence, and here is my status:

- [ ] Spin up a brand new Sourcegraph 3.0 instance `env IMAGE='sourcegraph/server:3.0.0-alpha.9' ./dev/run-server-image.sh`
- [ ] Enable a popular Go repository from [GitHub](https://github.com/search?o=desc&q=language%3Apython&s=stars&type=Repositories)
- [ ] Deploy the language server in a Docker container by following: https://docs.sourcegraph.com (if any of this is unclear, report it in a comment below)
- [ ] Test a few hover tooltips, jump-to-definitions, and find-references
- [ ] Unassign yourself from this issue
```

You won't get code intelligence on variables from dependencies.

This issue should be closed after a sufficient number of people have tested.

**Comment by chrismwendt** [comment]
Ready for testing (I pushed the docker image).

**Comment by chrismwendt** [comment]
I'm starting to test Python code intelligence, and here is my status:

- [ ] Spin up a brand new Sourcegraph 3.0 instance `env IMAGE='sourcegraph/server:3.0.0-alpha.9' ./dev/run-server-image.sh`
- [ ] Enable a popular Go repository from [GitHub](https://github.com/search?o=desc&q=language%3Apython&s=stars&type=Repositories)
- [ ] Deploy the language server in a Docker container by following: https://docs.sourcegraph.com (if any of this is unclear, report it in a comment below)
- [ ] Test a few hover tooltips, jump-to-definitions, and find-references
- [ ] Unassign yourself from this issue

**Comment by nicksnyder** [comment]
Chris is satisfied with the amount of testing that has been done.
