### ISSUE TITLE
Cloud cost budgeting

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#17203]
We currently instruct devs to create their own projects to provide resource isolation and easy cleanup. 

However, these projects lack fine-grained budgeting. 

At first glance, this would require an automated solution since only a role with "Billing Manager" can add budgets which we would not want to give to everyone capable of creating a project

**Comment by pecigonzalo** [comment]
This ties into https://github.com/orgs/sourcegraph/projects/92 and the goal [#split-cloud-infrastructure-into-separate-gcp-projects](https://about.sourcegraph.com/handbook/engineering/distribution/goals#split-cloud-infrastructure-into-separate-gcp-projects),

It was descoped, but it would be great to have this feature.

**Comment by pecigonzalo** [comment]
Reference: https://cloud.google.com/billing/docs/how-to/notify#cap_disable_billing_to_stop_usage
