### ISSUE TITLE
Docs "note" style should have stronger highlighting

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#1720]
Currently, `aside.node` elements in the docs (which correspond to `> Markdown blockquotes`) are not highlighted in any way. They are indistinguishable from paragraph text. However, they often have important information that a user should notice on the page. For instance:

![image](https://user-images.githubusercontent.com/1646931/50857180-b7dc9780-1341-11e9-81b2-af5e9545735d.png)

@francisschmaltz Can we highlight these things by placing them in a yellow rounded-corner box or whatever you think is best as design chief?

**Comment by sqs** [comment]
Note that these are displayed right on docs.sourcegraph.com but not in /help.

**Comment by beyang** [comment]
Why do we have different styling on docs.sourcegraph.com vs. /help?

**Comment by francisschmaltz** [comment]
@sqs @beyang lets dive into this for 3.1. But we should have unified styles across both docs and /help
