### ISSUE TITLE
Require valid external service config json before creating/updating external services.

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#1721]
Right now, external service config json is validated on the frontend (which yields green squiggles in the frontend). The existence of validation errors doesn't prevent the form from being submitted however; ideally it would.

Either we need to do validation on the backend (e.g. https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/pkg/conf/validate.go#L76:11), or, if possible and easier, piggy back on the validation already being done in the client by the monaco editor and prevent form submission there (e.g. does this help? https://github.com/Microsoft/vscode/pull/31045).

cc @tsenart since this relates to external services and @slimsag since this relates to backend validation which is already being done for site config.

**Comment by tsenart** [comment]
Isn't validation being done [here](https://github.com/sourcegraph/sourcegraph/pull/1700/files#diff-e4690e26caa9d3d0aeee747eadcd526bR48)?

On a similar note, I was wondering why we don't use JSON schema on the backend to do the validation too.

**Comment by nicksnyder** [comment]
> Isn't validation being done here?

Yes, but it is all manual, not automated based on the site.schema.json.

For example, we have this check for GitLab but not for GitHub (although it really could be used in both places)
```
if strings.Contains(cfg.Url, "example.com") {
	return fmt.Errorf(`invalid GitLab URL detected: %s (did you forget to remove "example.com"?)`, cfg.Url)
}
```

> I was wondering why we don't use JSON schema on the backend to do the validation too.

Yes, that is what I meant by "we need to do validation on the backend (e.g. https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/pkg/conf/validate.go#L76:11)"
