### ISSUE TITLE
Mirroring stats are inconsistent on Cloud

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#17238]
The position in the queue seems to stay the same but the next scheduled update shifts around and often appears in the past yet the `last refreshed` value doesn't seem to change:

<img width="1144" alt="Screenshot 2021-01-13 at 12 42 17" src="https://user-images.githubusercontent.com/25610/104442080-3d345b80-559d-11eb-8c2f-cd9bd7253c89.png">

**Comment by tsenart** [comment]
Will you look into this during this cycle?

**Comment by ryanslade** [comment]
I'll try 😄

**Comment by ryanslade** [comment]
This was fixed by https://github.com/sourcegraph/sourcegraph/pull/17318
