### ISSUE TITLE
fastResultLoading sometimes showing unrelated results, missing real ones

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#17231]
So I _thought_ I was seeing weird highlighting issues before when using search, like, odd things being highlighted that shouldn't be, but this only happened once or twice and when I refreshed the issue disappeared. Turns out I am not crazy and can reproduce this reliably. This issue disappears when I put ` "enableFastResultLoading": false` in my user settings so it is probably a regression in the changes there. Basically, stale/previously highlighted things show up, try this:

- Run this on Sourcegraph.com: [`repo:^github\.com/ethereum/solidity$`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/ethereum/solidity%24&patternType=literal)
- Search for `HAVE_z` in this repository. You will see expected results, there's are hits for `HAVE_Z3`
- Now change the pattern to `HAVE_c` and search. This will very likely show you a highlighted result for `HAVE_Z` which is not what we searched for, and no result for `HAVE_C` in that file (but there is a `HAVE_C` match in that file `libsmtutil/SMTPortfolio.cpp`). 
- Refresh, and you will see the expected, but previously missing `HAVE_C` highlighted and the `HAVE_Z` disappear. 

In [that particular file](https://github.com/sourcegraph/sourcegraph/issues/17231#issue-784780946), there is a HAVE_Z and a HAVE_C close to each other, within a couple of lines of each other, so I suspect some calculation is messing up, but not sure why it fixes on refresh.

Trying to reproduce this issue, I also had very wacky stuff happening like entire file contents for results (again, some calculation issue going on) but I can't reproduce it reliably. Basically, I guarantee if you go to the above repo and alternate searching for `HAVE_z` and `HAVE_c` a couple of times you will see weird things. It disappears if I disable the fast loading flag.

Example: (Edit: the video does `HAVE_c` first then `HAVE_z`, I don't think this matters, just try alternate searches for these)

https://user-images.githubusercontent.com/888624/104407171-3e727380-551e-11eb-926a-32bfd3f4f56d.mp4

**Comment by rvantonder** [comment]
Here's another side-by-side of a first search that had weird highlighting compared to the results after refresh

# 1. first result
![Screen Shot 2021-01-18 at 11 12 39 AM](https://user-images.githubusercontent.com/888624/104950690-60d11a80-597e-11eb-87bf-472952c58040.png)

# 2. after refresh
![Screen Shot 2021-01-18 at 11 13 16 AM](https://user-images.githubusercontent.com/888624/104950705-6595ce80-597e-11eb-963d-b8fe75c805b6.png)

**Comment by rvantonder** [comment]
Confirming this issue affects references highlighting. You can reproduce by clicking between two `value` locations in the file at the [following query](https://sourcegraph.com/github.com/rust-analyzer/rust-analyzer@188db89/-/blob/editors/code/src/persistent_state.ts#L39:56&tab=references), like you see in the video below. Do this two or three times so you see the issue. When fast reloading is false, I'm unable to reproduce, even after doing this back and forth 20+ times (`      "enableFastResultLoading": false`).


https://user-images.githubusercontent.com/888624/106964800-ec2d0880-66ff-11eb-9730-34a187ec0945.mp4

**Comment by slimsag** [comment]
Turned off the feature flag on Sourcegraph.com just now, should rollout in a bit: https://github.com/sourcegraph/deploy-sourcegraph-dot-com/commit/5c61f138db5e034c9e3cec422ea28ddb2bcefafb

Additional context for myself: https://sourcegraph.slack.com/archives/CHXHX7XAS/p1611756846077100

I will investigate/fix the actual cause later on.

**Comment by limitedmage** [comment]
@slimsag  @efritz  is this fixed? Should we turn the feature flag back on in Sourcegraph.com?

**Comment by efritz** [comment]
@limitedmage Sorry for the delay, if it's not on currently on we should be able to re-enable it.

**Comment by limitedmage** [comment]
@camdencheek  can you check if the new syntax highlighting works with `experimentalFeatures.enableFastResultLoading` enabled?

**Comment by camdencheek** [comment]
Looks good to me 👍

**Comment by limitedmage** [comment]
@slimsag / @camdencheek  can one of you turn the feature flag back on on sourcegraph.com and also make it enabled by default in dev environment?
