### ISSUE TITLE
Improve style of links, especially for dark theme

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#1724]
In the following screenshots, "connecting an external service" [is a link](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/web/src/repo/RepositoryErrorPage.tsx#L202:45-208:48).

The link is not visible in dark theme:
![image](https://user-images.githubusercontent.com/10532611/50388610-2273bd80-071c-11e9-80a5-e805b8b0374a.png)

and barely visible in light theme
![image](https://user-images.githubusercontent.com/754768/50808987-093f4500-12b6-11e9-9ec4-d52b29147cb2.png)

@francisschmaltz can you figure out what style this should be and then assign to @vanesa ?

This issue was extracted from https://github.com/sourcegraph/sourcegraph/issues/1570

**Comment by felixfbecker** [comment]
I updated the text color so this should now be visible.
