### ISSUE TITLE
New signup page

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#17273]
## Context

The Cloud team is working on making Sourcegraph Cloud support private and public repos for individual users.

We know that users signing up for the first time often struggle with their first search, because they're simultaneously learning how the search works while searching code in hundreds of thousands of repos on Cloud that they're not familiar with. By creating code host connections and adding their own repos, users will be able to target a subset of these hundreds of thousands of repos they care about.

For new users, we're working on a signup flow where they can add code host connections and their own repositories during signup, so that by the time they make their first search, they're able to search that code. Our hypothesis is this will improve the initial experience and help users get to that "ahha" moment faster.

As part of this, we want to encourage users on Cloud to sign up via continuing with GitHub or GitLab. Our current signup page prioritizes email signup, and is overall very functional without any persuasive or compelling reasons to sign up.

With this in mind, we want to create a new signup page specifically for Cloud (not for Enterprise). This will give us the chance to meet this unique goal, while also doing more to convey the value of Sourcegraph for individual users. In the future, this page will also help us with our goal of driving signups for SMBs.

## Feedback

I've done a really rough pass on an approach to content for this signup page, and an even rougher pass on the visual design.

<a href="https://www.figma.com/file/zXvqCASHDzmvKbrAl1EVsd/Public-and-Private-Repos-for-Users-on-Cloud?node-id=1935%3A368"><img width="1439" alt="image" src="https://user-images.githubusercontent.com/6304497/104599698-670e8080-5678-11eb-9619-2342b0f6c97e.png"></a>

[View on Figma](https://www.figma.com/file/zXvqCASHDzmvKbrAl1EVsd/Public-and-Private-Repos-for-Users-on-Cloud?node-id=1935%3A368)

@sourcegraph/marketing, I'd like to get your feedback on:

- The content and messaging
- Thoughts on brand identity: what brand character and personality are we currently working with?
  - In terms of visual and brand design, how far do we want to go visually? Our brand identity is relatively limited right now, and I don't want to go too far into "defining" a particular identity when it's likely to change in the near future.
- Customer logo choices: which logos are best to use in this context?
- Emails: we send a verify-your-email email immediately after signup, and a simple welcome email after a delay. Both of these ought be considered as part of the overall signup experience.

I'm using this issue as the place for discussion and review.

**Comment by abschu** [comment]
@quinnkeast - looking forward to discussing this when we meet on Tuesday. Is this for when we launch Cloud for private code or is this the page you want to start using now (for public code)?

**Comment by kaciewj** [comment]
@quinnkeast Cloud signup is one of the only ways we can currently collect data about our users. If users continue with GitHub/GitLab do we lose the ability to collect their info?

**Comment by quinnkeast** [comment]
>@quinnkeast - looking forward to discussing this when we meet on Tuesday. Is this for when we launch Cloud for private code or is this the page you want to start using now (for public code)?

This would be for Cloud with private code, when we're ready for GA.

>@quinnkeast Cloud signup is one of the only ways we can currently collect data about our users. If users continue with GitHub/GitLab do we lose the ability to collect their info?

No, we should have all the same info we have today. We use continue with GitHub today for Cloud, and I think we'll continue to use that same implementation.

**Comment by lorihey** [comment]
@quinnkeast When someone signs up for a Cloud Account now, their email address is submitted via API from the Cloud server to Hubspot, which identifies it as a Cloud Sign-up and creates a record for it in Hubspot (which then syncs over to Salesforce) with the Original Source field populated with "API" (since it was processed by the Cloud server and not the About website, so Hubspot sees the record as having come from something "off site") and the First Touchpoint field populated with "Sourcegraph.com Account." So are you saying that if someone starts using the Cloud Server via their GitHub or GitLab login, that the Cloud Server will grab that email address from their logins on those systems and process those email addresses the same way in our lead capture systems as if they had submitted their email address directly to us?

**Comment by quinnkeast** [comment]
I'm going to defer to @unknwon and @ryanslade to discuss the specifics around how the flow works, particularly as it relates to the lead capture needs.

(To be sure—these details are exactly what we're looking to uncover and be sure we address as part of implementation!)

**Comment by unknwon** [comment]
> So are you saying that if someone starts using the Cloud Server via their GitHub or GitLab login, that the Cloud Server will grab that email address from their logins on those systems and process those email addresses the same way in our lead capture systems as if they had submitted their email address directly to us?

I have no idea where/when we submit email address to HubSpot, but we will have a verified email (get from GitHub or GitLab API) as the user's primary email address on Sourcegraph instance.

**Comment by aileenrose** [comment]
@unknwon  In the signup process, it will create a Hubspot contact record with SyncUser.
https://sourcegraph.com/github.com/sourcegraph/sourcegraph@667c6698bf576daa57bf0b4a6f462651c62871c6/-/blob/cmd/frontend/internal/auth/userpasswd/handlers.go#L190
https://sourcegraph.com/github.com/sourcegraph/sourcegraph@667c6698bf576daa57bf0b4a6f462651c62871c6/-/blob/cmd/frontend/internal/app/tracking/tracking.go

**Comment by unknwon** [comment]
@aileenrose Thanks for the links! 

If we agree that the leads quality do not differ enough between "sign in with email" and "sign in with code hsot" (that has an email), then we just need to make sure calling the `SyncUser` function.

If we don't agree, hmm, then that's not an engineering problem and I could not answer :D

**Comment by quinnkeast** [comment]
Based on current planning, this won't be implemented as part of the Core Application team's work for the marketing launch. @tommypez and @sqs are taking this initiative as part of a separate project.
