### ISSUE TITLE
Error: Cannot query field "pendingContents" on type "SiteConfiguration"

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#1729]
I got to step 7 of the test plan (I actually skipped step 6) and saw this error when trying to view the site config.

```
Error: Cannot query field "pendingContents" on type "SiteConfiguration". Did you mean "effectiveContents"? Cannot query field "canUpdate" on type "SiteConfiguration". Cannot query field "source" on type "SiteConfiguration".
```

What I did:
1. Run 2.13.5
    ```
    rm -rf /tmp/sourcegraph
    docker run --publish 7080:7080 --rm --name sourcegraph --volume /tmp/sourcegraph/config:/etc/sourcegraph --volume /tmp/sourcegraph/data:/var/opt/sourcegraph sourcegraph/server:2.13.5
    ```
2. Configured access to github.com with token and added sourcegraph/infrastructure, nicksnyder/go-i18n
3. Edited the site config according to steps 3 and 4 in the test plan (it prompted me to restart to apply the config, but I just shut it down instead).
4. Shut down 2.13.5 server
5. Run latest insiders
    ```
    docker pull sourcegraph/server:insiders
    docker run --publish 7080:7080 --rm --name sourcegraph --volume /tmp/sourcegraph/config:/etc/sourcegraph --volume /tmp/sourcegraph/data:/var/opt/sourcegraph sourcegraph/server:insiders
    ```
6. Go to `http://localhost:7080/site-admin/configuration` and see error

**Comment by nicksnyder** [comment]
Hmm, I just ran through this again and was not able to reproduce. I am not sure what happened.

**Comment by slimsag** [comment]
It sounds like you may not have refreshed the page and hence been running an old version of the frontend code.
