### ISSUE TITLE
Support searching "files that you own" through CODEOWNERS

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#17311]
See comments: https://github.com/sourcegraph/sourcegraph/pull/17298#issuecomment-760673473, https://github.com/sourcegraph/sourcegraph/pull/17298#issuecomment-760718760

> Side-note: How easy would it be to extend our query language to search codeowners now? I can imagine a simple backend which contributes FileMatch with just paths for codeowners. You could then and against that and just search files you own :O

> That's a really nice idea. I'm collecting search ideas like that to drive how we would extend things and support certain "builtins", and that'll definitely be on the list! More soon. For this use case we'd essentially need a primitive to substitute the content of a match for a search pattern.

**Comment by jensim** [comment]
# I would also like to see a feature like this.

Maybe a less specific description would be "Filter files/repos based on ownership"

It would require search indexing to parse CODEOWNERS and other file types that it would choose to support

To a user it might look like this: `owner:jensim repo:sourcegraph/sourceghraph file:\.go$ oldFunc(`

# This would  be a great enabler when running batch changes.

Often when I get requests for generating batch changes, I ask what teams are interested in receiving them, and not all are.. Some want to opt out so it does not create noise at that specific time. Some want it right away, and some want it later.

But as we work with hundreds of repos, and some really big mono-repos, it would enable us greatly if there was a way to search with a owner-filter.

**Comment by camdencheek** [comment]
Closing since this this is now possible with the `file:has.owner()` predicate as part of the Sourcegraph Own feature set. It's still pretty slow, but we do not plan to make further improvements right now.
