### ISSUE TITLE
Give immediate feedback in mgmt console for invalid license key

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#1731]
For step 12 of the [test plan](https://github.com/sourcegraph/sourcegraph/issues/1689) it is a bit unclear to me why putting in an invalid value for the licenseKey would cause the instance to display a roadblock page when a missing license key doesn't behave that way.

![image](https://user-images.githubusercontent.com/754768/50877823-8cc96680-1388-11e9-8061-0be70c4870a0.png)

**Comment by slimsag** [comment]
I think the only reason this occurs is to surface the error. For example, if you typo your license key and the app continued to work you would think you entered it correctly and that you now have access to paid features -- but you don't and that would be surprising.

We could raise this error through other means (a site banner) but I presume this was just an easy method of raising this information. cc @sqs who implemented this

Not a release blocker.

**Comment by sqs** [comment]
Yes, my intent with this behavior was to be explicit, because this almost always indicates an error that the user would want to immediately rectify if they knew about it.

**Comment by nicksnyder** [comment]
A more explicit and immediate error would be to make this a validation error in the  management console at the time the bad config is saved.
