### ISSUE TITLE
Multiple containers try to bind to `6060` in 3.21

### ISSUE THREAD

**Issue by nmattia** [sourcegraph/sourcegraph#17349]
- **Sourcegraph version:** 3.22

#### Steps to reproduce:

Run all containers on the same machine with `--network=host`.

#### Expected behavior:

Everything works fine as in `3.21`.

#### Actual behavior:

Most containers fail to start because the port `6060` is already bound

---

Up to 3.21 everything worked fine, but from 3.22 onward it looks like all containers try to bind to port `6060`. After some investigation it looks like sourcegraph is exposing profiling data on `6060`. This however should only occur in k8s setup (see the [debug ports](https://docs.sourcegraph.com/admin/pprof#debug-ports) section), how can I either disable the profiling data, or tell sourcegraph to use a different port for each container?

Thanks in advance!

**Comment by slimsag** [comment]
How are you running the containers?

**Comment by nmattia** [comment]
I'm running them through [NixOS' oci container support](https://github.com/NixOS/nixpkgs/blob/e80cbcfb93aaf274f362aebbde83edf84e1c79b3/nixos/modules/virtualisation/oci-containers.nix). In practice it means that each container is run by a command like this:

```
$ docker run --rm --name=<name> ... --network=host
```

where I'm setting various env variables for each container:

### github-proxy

``` nix
        environment = {
          GOMAXPROCS = "1";
          SRC_FRONTEND_INTERNAL = "localhost:3090";
          JAEGER_AGENT_HOST = "jaeger";
        };
```

### gitserver

``` nix
        environment = {
          GOMAXPROCS = "4";
          SRC_FRONTEND_INTERNAL = "localhost:3090";
          JAEGER_AGENT_HOST = "jaeger";
        };
```

### repo-updater

``` nix
        environment = {
          GOMAXPROCS = "1";
          SRC_FRONTEND_INTERNAL = "localhost:3090";
          JAEGER_AGENT_HOST = "jaeger";
          GITHUB_BASE_URL = "http://localhost:3180";
        };
```

### searcher

``` nix
        environment = {
          GOMAXPROCS = "2";
          SRC_FRONTEND_INTERNAL = "localhost:3090";
          JAEGER_AGENT_HOST = "jaeger";
        };
```

### symbols

``` nix
        environment = {
          GOMAXPROCS = "2";
          SRC_FRONTEND_INTERNAL = "localhost:3090";
          JAEGER_AGENT_HOST = "jaeger";
        };
```

### search-indexer

``` nix
        environment = {
          GOMAXPROCS = "8";
          HOSTNAME = "localhost:6070";
          SRC_FRONTEND_INTERNAL = "http://localhost:3090";
        };
```

### indexed-searcher

``` nix
        environment = {
          GOMAXPROCS = "16";
          HOSTNAME = "localhost:6070";
        };
```

### frontend

``` nix
        environment = {
          SITE_CONFIG_FILE = "/tmp/site-config.json";
          EXTSVC_CONFIG_FILE = "/tmp/extsvc.json";
          SITE_CONFIG_ESCAPE_HATCH_PATH = "/tmp/site-config-escape-hatch.json";
          GOMAXPROCS = "12";
          GITHUB_BASE_URL = "http://localhost:3180";
          GRAFANA_SERVER_URL = "http://localhost:3370";
          INDEXED_SEARCH_SERVERS = "localhost:6070";
          JAEGER_AGENT_HOST = "jaeger";
          REDIS_ENDPOINT = "localhost:6379";
          REPLACER_URL = "http://localhost:3185";
          REPO_UPDATER_URL = "http://localhost:3182";
          SEARCHER_URL = "http://localhost:3181";
          SRC_FRONTEND_INTERNAL = "localhost:3090";
          SRC_GIT_SERVERS = "localhost:3178";
          SRC_SYNTECT_SERVER = "http://localhost:9238";
          SYMBOLS_URL = "http://localhost:3184";
        };
```

### precise-code-intel-worker

``` nix
        environment = {
          GOMAXPROCS = "2";
          NUM_WORKERS = "1";
          SRC_FRONTEND_INTERNAL = "localhost:3090";
          PROMETHEUS_STORAGE_DIR = "/prom";
          PROMETHEUS_CONFIGURATION_DIR = "/prom_config";
        };
```

### query-runner

``` nix
        environment = {
          GOMAXPROCS = "1";
          SRC_FRONTEND_INTERNAL = "localhost:3090";
          JAEGER_AGENT_HOST = "jaeger";
        };
```

---

Are there heuristics in place for figuring out if the containers are running as pods? Did those change in 3.22?

**Comment by slimsag** [comment]
I am not familiar with NixOS OCI support in general (and we do not support it officially), but Sourcegraph very much assumes its containers can bind the same ports as other containers. This does not just apply to Kubernetes deployments, but in any deployment where the containers are deployed individually. In other words, you will run into this again even if binding on another port is possible. Is there no way in NixOS's OCI support to not use host binding for the network? [this](https://github.com/NixOS/nixpkgs/blob/e80cbcfb93aaf274f362aebbde83edf84e1c79b3/nixos/modules/virtualisation/oci-containers.nix#L80-L132) seems to imply that `--net=host` is not the effective default in their OCI runtime.

The "docker" section [in the docs](https://docs.sourcegraph.com/admin/pprof#debug-ports) you referenced refers to the `sourcegraph/server` image, which bundles all container images in one for small demo deployments and inherently must bind to different ports.

As a quick workaround you can set [this environment variable](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/debugserver/debug.go#L22) on each container - but as I noted above you will run into this issue again in the future.

You can find an example of how to deploy the containers on Docker Compose here - which I imagine should be a straightforward translation to NixOS: https://github.com/sourcegraph/deploy-sourcegraph-docker/blob/master/docker-compose/docker-compose.yaml

Hope this helps!

**Comment by nmattia** [comment]
I see, thanks a lot. Setting `SRC_PROF_HTTP` did work for now. I'll try to find a way to set up a user bridge in NixOS. Thanks a lot for your help here @slimsag !
