### ISSUE TITLE
non-existent repogroups return "Too many repositories"

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#17343]
We should check that a repogroup exists (could be user defined).

![Screen Shot 2021-01-15 at 4 20 28 PM](https://user-images.githubusercontent.com/888624/104787762-a4910d80-574d-11eb-8ff2-6dc7d62bfbfb.png)

CC @sourcegraph/cloud

**Comment by tsenart** [comment]
@rvantonder: Thanks! What makes this a Cloud team thing?

**Comment by rvantonder** [comment]
I wasn't super sure about that to be honest, but I remember Ryan adding the "my" repogroup. It could be a search thing (or... something else? I don't know what else). That seems tenuous, if only because it's not clear to me who owns this code in general, seems to have gotten lost in the core / search / cloud transition. I'll add a search label too 🤷

**Comment by malomarrec** [comment]
Tagging similar issue in #20138 to feed into prioritisation work.

**Comment by malomarrec** [comment]
Are repogroups going to be deprecated in favor of contexts?

**Comment by lguychard** [comment]
@novoselrok let's close this once the code backing repogroups has been removed.
