### ISSUE TITLE
Manage repositories view question

### ISSUE THREAD

**Issue by artemruts** [sourcegraph/sourcegraph#17354]
### Question

If the user has both GitHub and GitLab code host connections setup but one of them fails, for example GitLab due to bad credentials. Users won't be able to see GitHub repositories in "manage" repositories view.

@quinnkeast  I don't propose we fix this right away, just documenting as part of QA. In the ideal world would we still want to show GitHub repos, right?

### Video

https://user-images.githubusercontent.com/1319181/104871563-62b4c280-5919-11eb-8094-b081abdd89f6.mov

**Comment by quinnkeast** [comment]
Great callout. Yes, we should still show the GitHub repos and show an error message for the GitLab code host connection, with a link to the code host connections page where they can resolve the issue.

**Comment by tsenart** [comment]
If it's an easy fix @artemruts, then I'd say pull this in to the iteration. Also fine if we postpone to next one.
