### ISSUE TITLE
For milestone 5 list the build tools/project info for each customer we intend to deliver lsif-clang to.

### ISSUE THREAD

**Issue by scalabilitysolved** [sourcegraph/sourcegraph#17368]
For milestone 5 of our goals as listed here https://about.sourcegraph.com/handbook/engineering/code-intelligence/goals we plan to deliver lsif-clang to 3 customers initially. 

It'd be good to have as much information available per company set up to ensure we've at least tried a happy path on their build tool/set up of choice.

**Comment by macraig** [comment]
Confirm with C++ customers what LLVM version they are compatible with.

**Comment by scalabilitysolved** [comment]
Where are we tracking this list @macraig ?

**Comment by macraig** [comment]
Tracking in [LSIF delivery status](https://docs.google.com/spreadsheets/d/1wV-ymvENWvi92zN6NQpvPj4Kqxyy-bsGqm0gMSrq4bs/edit#gid=0)
