### ISSUE TITLE
Only 1 popover or dropdown should be visible at a time

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1736]
Repro:

1. Visit any page with a repo header, such as https://sourcegraph.com/github.com/sourcegraph/docsite
1. Click the rev name (`master`) to open the rev popover
1. Click the down caret next to the repo name to open the repo popover

Expected: at most 1 popover should be able to be displayed at a given time. Clicking the repo name caret should close the rev popover.

Actual: both popovers are shown

![screenshot from 2019-01-08 22-44-28](https://user-images.githubusercontent.com/1976/50881596-f6e90800-1396-11e9-9cf2-ad2f683bc310.png)

**Comment by attfarhan** [comment]
(Reassigned to @lguychard since it looks like he has a PR open already)
