### ISSUE TITLE
codeintel: Auto-configure 5 cmake repositories

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#17376]
1. https://github.com/microsoft/vcpkg
~~- https://github.com/dolphin-emu/dolphin~~
~~- https://github.com/google/flatbuffers~~
2. https://github.com/ethereum/solidity
3. https://github.com/qbittorrent/qBittorrent
~~- https://github.com/Genymobile/scrcpy~~
4. https://github.com/apache/arrow
5. https://github.com/edenhill/librdkafka

**Comment by scalabilitysolved** [comment]
Is this done @Strum355 or do we still have 2 more repos to do considering some of the repos counted towards milestone 1?

**Comment by Strum355** [comment]
Ill wanna do 2 more repos for that reason yea @scalabilitysolved will have em done by EOW

**Comment by Strum355** [comment]
Mission successful :tada:
