### ISSUE TITLE
blog: Write about the code intelligence commit graph optimization effort

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#17379]
The [previous](https://about.sourcegraph.com/blog/optimizing-a-code-intel-indexer/) two [articles](https://about.sourcegraph.com/blog/optimizing-a-code-intel-backend/) can be supplemented with a third about the recent commit graph optimizations. Write a draft of this.

**Comment by efritz** [comment]
Completed first draft in https://github.com/sourcegraph/about/pull/2431. I will respond to comments as they come in, hopefully will get polished and published sometime in this or the next sprint.

**Comment by efritz** [comment]
Reopening to track progress on the [blog posts board](https://github.com/orgs/sourcegraph/projects/128).

**Comment by content-hacker** [comment]
@efritz it doesn't look like the pull request is attached to this? Am I just missing it?

**Comment by efritz** [comment]
> @efritz it doesn't look like the pull request is attached to this? Am I just missing it? 

https://github.com/sourcegraph/about/pull/2431

**Comment by content-hacker** [comment]
Thank you! Didn't realize this blog post issue was opened in the sourcegraph repo so I can't link it to the PR
