### ISSUE TITLE
codeintel: Research adding cmake project configuration inference

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#17375]
Determine if cmake configurations have a common generic structure that can be inferred correctly for some non-trivial percentage of repositories.

This issue should be aggressively time-boxed. There may be a step that is non-inteferable, in which case the result of this issue should be a plan to break apart what can be inferred and what needs to be supplied by the user (without requiring full user configuration). (e.g. Can we show the user the inference and have them fill out particular sections that we get wrong?)

**Comment by Strum355** [comment]
After testing preliminary code on ~10 repositories, we found it not possible to get cmake to give us a compdb without having certain project-dependent dependencies installed. Effort will be redirected towards being able to notify users of a partial config that needs final tweaking, teaming with @gbrik
