### ISSUE TITLE
code intel: link completed index jobs to their successful lsif_uploads

### ISSUE THREAD

**Issue by gbrik** [sourcegraph/sourcegraph#17386]
Right now the code intel auto indexer won't leave any record of which index runs correspond to which lsif uploads, so the backend has no way to know which uploads were submitted by the auto indexer and which were submitted manually/through CI. We should persist this info in the database.

This will be useful for #14572.

**Comment by gbrik** [comment]
@efritz

**Comment by efritz** [comment]
Some things to help you out:

- `src lsif upload` has a `-json` flag
- Any code-intelligence specific code in the executor path (modifying lsif_index job records) will need to be done somewhere in https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/tree/enterprise/cmd/executor-queue/internal/queues/codeintel. The executor-queue coordinates the jobs ran by the executor. The executor cannot be code-intel specific, so anything that needs to modify the job pre/post execution has to go in the executor-queue adapters for a specific queue.

You may need to find an appropriate place in the executor-queue to run hooks for pre-complete (where we may want to parse the log output of the job), and then register that hook in the codeintel queue.

**Comment by efritz** [comment]
Additional ideas in https://github.com/sourcegraph/sourcegraph/issues/17392 and https://github.com/sourcegraph/sourcegraph/issues/17393.
