### ISSUE TITLE
Write README for Datadog extension and republish

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1739]
The Datadog extension should have a README.md file in its repository like the one in https://github.com/sourcegraph/sourcegraph-basic-code-intel. After adding the README.md, republish the extension to Sourcegraph.com.

Then we can link interested folks to https://sourcegraph.com/extensions/sourcegraph/datadog-metrics and they can see the description, screenshots, etc. (like https://sourcegraph.com/extensions/sourcegraph/basic-code-intel).

**Comment by sqs** [comment]
Also remove WIP

**Comment by vanesa** [comment]
Updated README.md: https://github.com/sourcegraph/sourcegraph-datadog-metrics

**Comment by sqs** [comment]
This is done
