### ISSUE TITLE
Code monitor title colour wrong on dark mode

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#17408]
## Problem

On the code monitor list view in dark theme, the colour of the title of the code monitor doesn't respond to the theme.

<img width="951" alt="image" src="https://user-images.githubusercontent.com/6304497/105034013-2f794d00-5a59-11eb-9dbc-14a3b6dd949b.png">

## Expected behaviour

Code monitor title should follow theme conventions.

(Thought: I see the title doesn't have any semantic tag, like h4 or similar. Should it?)

**Comment by limitedmage** [comment]
Doesn't repro in Chrome for me but does repro in Safari
