### ISSUE TITLE
Private mode requires authentication" error message is not discoverable

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#1741]
- **Sourcegraph version:** "Sourcegraph.com
- **Platform information:** MacOS, Chrome

#### Steps to reproduce:

1. Point your browser extension to sgdev.
2. Sign out of sgdev.  Sign in with OpenIDConnect.
2. On GitHub or GitLab, go to a file in a repository not on sgdev (e.g. if you're pointing your repo to sgdev, go to https://github.com/tsenart/vegeta/blob/master/internal/cmd/echosrv/main.go) 
3. Hover over a token, and see that a line appears above the token. Open the browser console and see 401 errors that say "private mode requires authentication". I was not sure of what to do, but remembered we had a GitHub sign-in option, which I used, and solved the problem.

![2019-01-09 21 48 53](https://user-images.githubusercontent.com/16265452/50904057-480e0000-145a-11e9-9bdc-564ed93f7f8e.gif)

#### Expected behavior:

The line above the token when hovering should not appear, or a hover should appear showing the error message "private mode requires GitHub/GitLab/CodeHost authentication" or something more specific.

#### Actual behavior:

The line above tokens appear when hovering and the ambiguous "private mode requires authentication" message appears in the console.

**Comment by attfarhan** [comment]
This seems like it could be an edge case, since we have multiple sign-in options (I don't think most instances will have multiple), so not sure if it should be release blocking.

**Comment by sqs** [comment]
@ijsnow is not working between now and the release, this is not a new issue, this is a browser extenson issue (so can be fixed without requiring customer redeploy) -- so pushing to 3.1

**Comment by ijsnow** [comment]
Reassigning to you to triage/prioritize @lguychard
