### ISSUE TITLE
Git blame toggle button should indicate 3-states

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#17429]
The git blame extension button has the below on/off states, but it actually has three states: off, blame selected lines, blame all lines. 

The button should tell me which option I have; right now, blame all lines and blame selected lines show the same "on" state. 

Ideally, the button also implies that there are more than two states, so I don't just turn it on and assume that's all I can do. (For example, in UIs where I can see 3 states in a row and toggle between them. I think that's overkill here, but if there are ways to bring in that concept, that's a bonus.) That said, this is a secondary concern to "capture 3 states." 

![image](https://user-images.githubusercontent.com/11967660/105084885-d656ec80-5a4b-11eb-984d-266d6c386f60.png)
![image](https://user-images.githubusercontent.com/11967660/105084912-dfe05480-5a4b-11eb-8d83-54f948e4c5a7.png)

**Comment by felixfbecker** [comment]
The question is how? Generally the 3-state toggle is tricky from a UX and accessibility perspective. In ARIA terms, there is `aria-pressed`, which is either `true` or `false`, which these toggles use depending on the `pressed` expression in the extension API. The current 3-state Git blame toggle actually already violates the ARIA spec:

> Toggle buttons require a full press-and-release cycle to change their value. Activating it once changes the value to true, and activating it another time changes the value back to false.

**Comment by Joelkw** [comment]
Thanks for the thoughts, @felixfbecker. Can we adapt the [ARIA tri-state checkbox](https://w3c.github.io/aria-practices/examples/checkbox/checkbox-2/checkbox-2.html) standard here? (I realize it isn't a "summary" metric of individual metrics, but in some ways the 'mixed' pattern does apply -- some lines on / some off in the blame selected lines state.)

**Comment by ryankscott** [comment]
@jjinnii this is no longer required with our new designs correct?

**Comment by jjinnii** [comment]
@ryankscott  Yup! Based on assumptions that the new row highlighting (if a user has a specific line selected) will solve this use case. If we get additional user feedback on this, can always revisit but I'm assuming it's solved with our new implementation.
