### ISSUE TITLE
Sourcegraph.com not indexing repos added by org

### ISSUE THREAD

**Issue by emchap** [sourcegraph/sourcegraph#17424]
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:** N/A (but found while working in Firefox)

#### Steps to reproduce:

1. Add a Github org to the site from https://sourcegraph.com/site-admin/external-services
2. Select "add repositories in an organization"; add url/token/org
3. It appears that only a subset of public repos will be cloned over or recognized; if additional repos are viewed in Github with the browser extension, they are added as well.
4. In tests, behavior did not mirror what happened in other deployments (where the full set of repos was added)

#### Expected behavior:
All repos that the token returns are recognized, listed, and cloned as time/rate limits permit.

#### Actual behavior:
Only some are listed and cloned until visited in Github directly.

**Comment by ryanslade** [comment]
@tsenart I believe the issue is that we don't actively sync any site admin owned external services on Cloud so the only repos that have been synced are ones that have been accessed on demand.

I'm a little confused as to how we've ended up with repos that exist in our repos table but are not cloned though.

I think what we could do is sync sync all external services in the background apart from our "global" ones on Cloud. This would be a fairly minimal change actually.

**Comment by tsenart** [comment]
@ryanslade: Shouldn't @emchap be using user added code host connections instead though?

**Comment by ryanslade** [comment]
I wasn't sure about that since they're not really "her" repos. It would be the quickest way to make things work though and wouldn't required the code change I proposed.

**Comment by ryanslade** [comment]
Also, it doesn't look like we allow adding repos for a single org from our new UI yet

**Comment by emchap** [comment]
@tsenart They exist outside of me—these were students we were going to give free on-site licenses to until we realized they just wanted unauthenticated search for public repos in their org, so this seemed like the best approach. If I should be doing something else let me know, of course, but this seemed to best match what we were doing.

**Comment by ryanslade** [comment]
@emchap This should be fixed now.

See: https://sourcegraph.com/site-admin/repositories?query=github.com%2Focf%2F

We've changed it so that even site admin external services are now synced in the background on sourcegraph.com

Feel free to close the issue once you've confirmed 😄

**Comment by emchap** [comment]
@ryanslade Works perfectly—thank you!
