### ISSUE TITLE
No feedback after adding/updating external service 

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#1742]
- **Sourcegraph version:** Insiders

#### Steps to reproduce:

1. Go to the external services page and click **Add external service**
2. Fill out the form, and click **Add external service**

OR 

1. Click **Settings** for an existing external service
2. Update the form, (or don't update the form, even)
3. Click **Update external service**

![2019-01-09 23 48 53](https://user-images.githubusercontent.com/16265452/50911123-29b00080-146a-11e9-91fe-1a7326123631.gif)

#### Expected behavior:

I would expect that after adding or updating an external service, you get taken back to the main external services page with a list of the added external services. 

I also expect that when you're editing an external service, if you have not edited anything, the **Update external service button** is not clickable.

#### Actual behavior:

Once adding or updating an external service, you are kept on the same page. When adding, the button text changes from "Add" to "Update", which is minimal feedback. When updating, nothing changes and you're kept on the same page, so it's difficult to tell if your update went through.

**Comment by nicksnyder** [comment]
> I would expect that after adding or updating an external service, you get taken back to the main external services page with a list of the added external services.

Fixed.

> I also expect that when you're editing an external service, if you have not edited anything, the Update external service button is not clickable.

This is a bit tricky to do given how the config area works, and it is also not consistent with what we do with other forms (for better or for worse).

**Comment by nicksnyder** [comment]
This got rolled in to https://github.com/sourcegraph/sourcegraph/issues/1756

**Comment by vanesa** [comment]
The first time I add the public repos to external services and saved, I was redirected to the main page. However, when I updated some repos and then clicked on "update external services", I was not redirected to the main external services page nor did I see any message confirming my changes were saved.

Here is a gif.
https://cl.ly/9f1d9bae0dc5

I'm using the newest docker image.
