### ISSUE TITLE
Configure external services banner does not disappear after services are added.

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#1743]
- **Sourcegraph version:** Insiders

#### Steps to reproduce:

1. Start a clean Sourcegraph instance
2. Sign up as an admin and add an external service.
3. Once adding the service, notice that the banner is still there, and still asks you to configure a service.

![image](https://user-images.githubusercontent.com/16265452/50911147-36345900-146a-11e9-8346-78aef2013cc1.png)

#### Expected behavior:

I expect the banner to either disappear, or update to name the next step once a service is added.

#### Actual behavior:

The banner remains

**Comment by nicksnyder** [comment]
It looks like it disappears if you do a hard refresh. I just need to reload site flags when external services are added/deleted.
