### ISSUE TITLE
Should references to the site config overview page be deleted?

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#1745]
Should references to this page: https://docs.sourcegraph.com/admin/site_config/ be deleted or updated now that the management console exists? For example, we still link to it from https://docs.sourcegraph.com/admin/site_config/all, but I believe many of the options listed there would be configured in the management console now.

**Comment by sqs** [comment]
I will update this doc page.

**Comment by slimsag** [comment]
FYI I started a WIP generator to generate the `site_config/all.md` and separate `management_console.md` or something, but didn't get too far.

**Comment by slimsag** [comment]
Is that the approach you are taking?

**Comment by slimsag** [comment]
Here is what I had if it is useful to you: [`schema/docgen.go`](https://gist.github.com/slimsag/9b346f3ad6a3030c978374aa67415690)

**Comment by sqs** [comment]
Thanks! My intent was to lighten your load here since I am updating other doc pages anyway.

 I haven’t started and don’t plan to immediately (maybe 12-24h from now). When I do start, I will prioritize updating the content over adding automation, but I would probably use your tool to at least do a one-time update.

**Comment by slimsag** [comment]
Awesome! Yeah, I started here with the same motivation (update content over adding automation) but it quickly became apparent to me a lot on that page was out of date and automation felt easier to me. I definitely agree do whatever is quickest here first!

**Comment by sqs** [comment]
closing in favor of #2067
