### ISSUE TITLE
Change 'Create new extension' button label  to 'Create extension'

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#17454]
**Description**

On the [extensions registry page](https://sourcegraph.com/extensions) button used for creating a new extension is labeled 'Create new extension'. After discussing it with @quinnkeast in the context of the Code Monitoring project, we came to the conclusion that 'new' is conversational and makes button labels too long (ex. 'Create new code monitor'). Let's follow the 'Create X' pattern for our buttons on all pages.

**Scope**

Change button label to 'Create extension'

@Joelkw @felixfbecker what do you think about this change?
Also, it could be a quick onboarding task.

**Comment by Joelkw** [comment]
@AlicjaSuska It was too quick, so I made this change last week and just [put up the PR](https://github.com/sourcegraph/sourcegraph/pull/17734).

**Comment by AlicjaSuska** [comment]
Thanks @Joelkw I'm closing the issue
