### ISSUE TITLE
https://sourcegraph.com/sign-up - No user exists matching any of the verified emails

### ISSUE THREAD

**Issue by markfirmware** [sourcegraph/sourcegraph#17476]
I sign in using github for a lot of apps without any trouble, but here sourcegraph is presenting an error.

**Comment by unknwon** [comment]
@markfirmware Thanks for filing the issue!

Is there any chance you've been able to record the additional error message returned on the same page starts with "First error was:"?

I took a quick look at the code and our configuration and doesn't see anything from a new user signs up directly with GitHub. 🤔

**Comment by markfirmware** [comment]
Thank you for the quick response!

I replaced my actual email with xxxxxx:


    No user exists matching any of the verified emails: xxxxxx, markfirmware@users.noreply.github.com.

    First error was: Username "markfirmware" already exists, but no verified email matched "xxxxxx"


My gh admin page says that your app has been granted permission to access my emails, so you should be able to see what xxxxxx is:

Sourcegraph.com
Last used within the last week Developed by sourcegraph
https://sourcegraph.com

Permissions
Access user email addresses (read-only)

**Comment by markfirmware** [comment]
Continue with GitHub

is the button I used.

**Comment by unknwon** [comment]
Thanks for the follow up!

The error indicates a user with the username "markfirmware" already exists on sourcergaph.com, is that you?

**Comment by markfirmware** [comment]
I think when I was unable to login with github I then tried to register with email/username/password. That did not work too well (I cannot remember the details) and that is when I decided to open an issue for the github login. I want to use a github login.

If the exisitng markfirmware login was created in the last day then I presume that it was I who did it.

**Comment by markfirmware** [comment]
I tried the forgot password link but did not receive an email.

It is possible that I signed up for sourcegraph some time ago. I do not know.

**Comment by unknwon** [comment]
Hmm, I checked our database and the user "markfirmware" was created on `2020-06-01 08:56:08.375369+00` 🤔 

I think this is the point that should bring @sourcegraph/product-team in: how we should help users in the case that they want to sign in with GitHub but the same username (in both Sourcegraph and GitHub) has been taken.

Ideally I would want a better UX that allows me to choose a different username and bind that Sourcegraph user with my GitHub.

**Comment by markfirmware** [comment]
I have another github account mark2011 and that is working. I can use that for the time being if you want to keep markfirmware in its current state to help with your resolution.

**Comment by oacnhpkqxjhufwumkkqnshvlmheokqv** [comment]
I'm seeing this too on sourcegraph/server:3.30.3

**Comment by unknwon** [comment]
This is kinda addressed by https://github.com/sourcegraph/sourcegraph/pull/59843
