### ISSUE TITLE
Error while adding public repos to external services

### ISSUE THREAD

**Issue by vanesa** [sourcegraph/sourcegraph#1747]
When trying to add public repos to my external services, I get this error:

![image](https://user-images.githubusercontent.com/9110008/50913037-113de700-1466-11e9-9aa0-6d353f8a1f34.png)

`Json: cannot unmarshal string into Go struct field GitHubConnection.repos of type []string`

I typed in the markdown instead of tabbing to auto-complete and the token had my private GitHub access token which I only removed for the screenshot.

**Comment by nicksnyder** [comment]
Hmm, I am not able to reproduce. I realized that my test instructions did not include `docker pull sourcegraph/server:insiders` so it is possible you were using an old build (if you were testing on insiders). Can you test this again after running `docker pull sourcegraph/server:insiders`?

**Comment by vanesa** [comment]
I was running an uptodate build:

```macbook-pro-10 sourcegraph (master) $ docker run --publish 7080:7080 --publish 2633:2633 --rm \
>     --volume /tmp/sourcegraph/config:/etc/sourcegraph \
>     --volume /tmp/sourcegraph/data:/var/opt/sourcegraph \
>     sourcegraph/server:insiders
Unable to find image 'sourcegraph/server:insiders' locally
insiders: Pulling from sourcegraph/server```

But I'll run it again to be sure.

**Comment by vanesa** [comment]
I couldn't reproduce it, so maybe it was just a glitch.

**Comment by nicksnyder** [comment]
Oh, I was able to trigger this error message by just putting invalid input.

![image](https://user-images.githubusercontent.com/754768/50984142-ef6c5080-14b5-11e9-9604-b818ea5f23d8.png)

Is this error message not clear to you?

**Comment by nicksnyder** [comment]
Oh, I think the problem is that once an error happens, updates don't succeed

**Comment by vanesa** [comment]
Closed as not able to reproduce.
