### ISSUE TITLE
Sync and index all non global external services on Cloud

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#17472]
Currently we only sync and index repos owned by user external services in the background on Cloud.

This makes it difficult for site admins to add new special case external services, for example: https://github.com/sourcegraph/sourcegraph/issues/17424

Instead we should sync and index all external services except for our special "Cloud Global" services that we use as the default external services for GitHub and GitLab. We want to exclude these as they can own a very large number of repos.

We'll need to make the following changes:

- [x] Introduce a new `cloud_global` column on `external_services` which defaults to false
- [x] Add a DB constraint that only one cloud global service can exist per kind. Currently this is checked in code when we save an external service.
- [x] Deploy this change and manually set the flag for our global services.
- [x] Deprecate the `CloudGlobal` setting in our GitHub and GitLab external service configuration and use the value from the db instead
- [x] For background syncing, only exclude external services with the `cloud_global` flag set.
- [x] Update `ListDefaultRepos` to include repos in `default_repos` and any repos owned by external services where `cloud_global` is false.

**Comment by ryanslade** [comment]
@asdine @tsenart How does this sound?

**Comment by tsenart** [comment]
SGTM, but perhaps `cloud` instead of `cloud_global`?

**Comment by ryanslade** [comment]
Well, we'll have other external services on cloud. I agree it's not the best name but at least it's explicit.

**Comment by tsenart** [comment]
Would `public` make more sense perhaps?

**Comment by ryanslade** [comment]
I went with `cloud_default` since it's a cloud specific feature and I think points at the fact these are where repos end up by default due to on demand syncing.
