### ISSUE TITLE
Add button to retry failed changeset

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#17479]
An errored changeset should have a button that re-requeues it for processing, so the user can retry without re-applying the campaign, which sometimes can be slow if caches are invalidated.

**Comment by rrhyne** [comment]
We should move the retry button outside of the error message to conform to alert guidelines as so:

![image](https://user-images.githubusercontent.com/539268/106217456-1e7fb880-618a-11eb-9a2b-0d470ad0f5c4.png)

Figma: https://www.figma.com/file/eRPXxaseMmYmIPpCpxeJmg/(%2317479)-Download-and-Retry-buttons?node-id=0%3A1&viewport=-512%2C282%2C0.8454133868217468
