### ISSUE TITLE
Commit search returns duplicates of the same commit

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#17483]
- **Sourcegraph version:** 
- **Platform information:** 

#### Steps to reproduce:

The query [`repo:^github\.com/sourcegraph/sourcegraph$ type:commit author:rijnard highlight`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+type:commit+author:rijnard+highlight&patternType=literal) returns the following results:
<img width="1275" alt="Screen Shot 2021-01-20 at 12 03 21" src="https://user-images.githubusercontent.com/12631702/105222284-89d8e300-5b17-11eb-8328-f3cb9f8becf7.png">

#### Expected behavior:

The commits should be unique, or deduplicated when multiple sets of results are merged

**Comment by rvantonder** [comment]
Can reproduce. Not a recent regression it turns out, I went back as far as 63c87676a5 and still see the duplicate commits (last four result rows in that screen shot). There's also a chance this isn't a regression.

**Comment by rvantonder** [comment]
OK went to 7152e4dea24f245db61776db7bad15ddc09ffe7a and still there. I think this is not a regression, but some newly discovered bug. It is coming from the backend, not a webapp issue.

**Comment by camdencheek** [comment]
I made a little progress on debugging this. 

Looks like [`nextCommits()`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/vcs/git/diff_search.go#L265:19) occasionally returns partial results due to a timeout, but will then return the remaining results on the next call in the loop as expected. On the example query, I'll occasionally see 7, 8, or 9 results in the first call, with 9 being the actual number of matches.

However, a couple of lines later, when we call [`rawShowSearch()`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/vcs/git/diff_search.go#L272), it always returns 9 results, even if there were only 7 results returned from `nextCommits()`. These extra two results seem to be the duplicated commits.

So now, next time through that loop, `nextCommits()` returns the remaining two results, passes them to `rawShowSearch()`, and we get the results that shouldn't have been returned last time again. 

I don't have a great grasp on why `rawShowSearch` exists, but I've verified that the `git show` arguments produced do, in fact, produce 9 results and it's not just a parsing error.

**Comment by rvantonder** [comment]
Now that you mentioned those calls, I went back and tried a couple of things. This is a regression introduced by https://github.com/sourcegraph/sourcegraph/pull/15386 in 9bf0a80a937c0679a6255f95ca1ada62ec7ebf53 (earlier than where I was looking before). I can confirm the duplicates do not show up in the commit right before this one, but do after. 

I'm not sure about the interaction of `nextCommits` and `rawShowSearch` without reading the code more deeply, maybe @keegancsmith has a more immediate idea.

**Comment by keegancsmith** [comment]
What are the commits passed to `rawShowSearch`? `nextCommits` returns a list of SHAs matching the query. However, it includes false positives. The purpose of `rawShowSearch` is to then fetch the full commit data and filter it down to the true search results. So I would only expect each SHA from nextCommits to appear at most once in the result set. So there is likely a subtle bug going on somewhere. To debug I would try find somewhere a duplicate SHA. Failing that I would try understand by running the git commands manually (this is what I laboured through a few months ago lol).

While are you touching this code I actually have some tech debt/polish that I wanted to do when I cleaned this up a few months ago if you are so inclined :) See details below

<details>

``` org
*** TODO onelineCommit only returns sha1 and sourceRef

We need to make sure we only ask for those values. Reading the parser it does
more than that. We shouldn't be doing =--oneline=, rather we should be using a format like

: git log --pretty='format:%H %S' -z --source --no-patch

instead of

: git log --oneline -z --source --no-patch

Requires Git 2.21 (Q1 2019), which added =%S=.

*** TODO refResolveCache doesn't need to exist
We only resolve HEAD [[file:~/go/src/github.com/sourcegraph/sourcegraph/internal/vcs/git/diff_search.go::type refResolveCache struct {][refResolveCache]]
   
*** TODO remove [[file:~/go/src/github.com/sourcegraph/sourcegraph/internal/vcs/git/exec.go::func readUntilTimeout(][readUntilTimeout]]

We can adjust the implementation of =DividedOutput= to include partial output.
```

</details>

**Comment by rvantonder** [comment]
Getting severely duplicated commits for this query [`repo:^github\.com/sourcegraph/sourcegraph$ type:commit author:rijnard count:1000`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+type:commit+author:rijnard+count:1000&patternType=literal). Adding here because fixing this will likely resolve it.

Also `select:commit` removes duplicates and is a great workaround.

**Comment by christinelovett** [comment]
https://app.hubspot.com/contacts/2762526/company/464956351 has reported this issue

**Comment by aisbaa** [comment]
We noticed this issue with `count:10000` limiting query to one repo.
