### ISSUE TITLE
Directly request structural searches along zoekt-searcher code path

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#17496]
We need a way to execute the new code path for structural search independently from the current code path. This means changing frontend code to signal where and how to structure requests for searcher depending on which one we execute. Currently, there's no way to execute the new path without also (redundantly) executing the old path.

**Comment by lguychard** [comment]
Is this still relevant following https://github.com/sourcegraph/sourcegraph/issues/17616 ?

**Comment by camdencheek** [comment]
Closing as no longer relevant
