### ISSUE TITLE
Pass down 'timeout:' values for UseFullDeadline in searcher-zoekt client

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#17492]
In v1 of the searcher-zoekt client #17495, we currently hardcode a value of "false" for UseFullDeadline. `UseFullDeadline` relies on:

> // If the user manually specified a timeout, allow zoekt to use all of the remaining timeout.

We need to retrieve and honor this timeout value (either pass it to searcher in a request, or get it from the full query, which we can pass to searcher in a request). However, we can't use this timeout value purely for the searcher-zoekt client, we need to compute the remainder that comby can use after zoekt is done.

**Comment by camdencheek** [comment]
Zoekt now streams its results back, so UseFullTimeout is no longer relevant
