### ISSUE TITLE
Doc improvements for deploy-sourcegraph-dot-com

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#1750]
I don't understand the semantic difference between
https://github.com/sourcegraph/deploy-sourcegraph-dot-com/blob/release/README.info.md
https://github.com/sourcegraph/deploy-sourcegraph-dot-com/blob/release/README.dev.md

It also seems like a waste that the root README.md is basically empty.

Can you consolidate all the relevant information into https://github.com/sourcegraph/deploy-sourcegraph-dot-com/blob/release/README.md?

**Comment by peterguy** [comment]
The referenced files no longer exist. The root `README.md` does have some info in it now.
