### ISSUE TITLE
Private repository on sourcegraph.com shows "Empty repository" instead of 404

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#1751]
https://sourcegraph.com/github.com/sourcegraph/test-private-package

Reported by @felixfbecker in https://github.com/sourcegraph/sourcegraph/issues/1744#issuecomment-452759151

**Comment by nicksnyder** [comment]
@felixfbecker ehm, that repo is private and we don't show private code on sourcegraph.com. I am going to close this, but feel free to re-open if I am missing something or if I misunderstood.

**Comment by felixfbecker** [comment]
If it is private, it should show a 404, but it shows “Empty repository”.

**Comment by nicksnyder** [comment]
filed https://github.com/sourcegraph/sourcegraph/issues/1762
