### ISSUE TITLE
Panic in search code stopping tests and deploys

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#17542]
This line panics with [`send on closed channel`](https://buildkite.com/sourcegraph/sourcegraph/builds/85105#74c318d6-af2c-443c-ab20-b26e02aa02de/2626-5032) introduced by #17470.

https://github.com/sourcegraph/sourcegraph/blob/c2d1d37ecd8419ce6480c31fbbc32ebc0a2719b5/cmd/frontend/graphqlbackend/textsearch.go#L470

---

Strangely, the PR that introduced this issue did panic in our CI environment, but everything still passed, here's the panic in the green build on main: https://buildkite.com/sourcegraph/sourcegraph/builds/84989#c75a2e6a-329a-42af-a635-6f8dfe65006f/2209-4966. Wondering what we can do about that, any one have ideas? @unknwon maybe?

We didn't see red builds on `main` until later in 3510702de66e48acf52d58a6f5872aa3de2c5a29

**Comment by keegancsmith** [comment]
I will fix ASAP. Just a note that this isn't causing any user noticeable issues thankfully.

**Comment by keegancsmith** [comment]
@rvantonder thanks so much for finding the commit where this panic started. It made debugging this much easier!
