### ISSUE TITLE
Update error message for already-existing usernames to convey useful information

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#17552]
## Problem

When a user attempts to updates their username and the username already exists, they receive the following error message:

![image](https://user-images.githubusercontent.com/6304497/105484878-57142380-5cac-11eb-9436-37416167e783.png)

## Proposal

With a minimal, quick-fix in mind, we should replace this with an error message that follows our [content guidelines](https://about.sourcegraph.com/handbook/communication/content_guidelines/actionable_language#error-messages).

I suggest:

>Username is already in use.

With a larger scope, we could also re-use the async validation in our signup form to provide feedback before the user submits the form.

![CleanShot 2021-01-22 at 12 23 43](https://user-images.githubusercontent.com/6304497/105485172-c4c04f80-5cac-11eb-802c-23ef0dbf67cf.gif)

**Comment by felixfbecker** [comment]
This error message comes from the backend, it needs to return us a better error message here (or an error code). I think a better error message would suffice (error code is not needed), as Quinn's suggestion is a valid error message to be returned by the backend and the backend should ideally not leak Postgres internals. The webapp doesn't need to handle this in any special way compared to other errors.
