### ISSUE TITLE
Streaming: jittery results display on long-running searches

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#17560]
On a long-running streaming search like [`RouteHandler timeout:20s count:1000`](https://sourcegraph.com/search?q=RouteHandler+timeout:20s+count:1000&patternType=literal), notice that the results are pushed down three times:

1. When the filters row is rendered
2. When the "skipped" toolbar item is rendered
3. When the repositories row is rendered

Item 2. would not happen on wider viewports, but I find the unstable UI with the actual results being pushed further and further below the fold frustrating (especially if I start reading the code of a result while the search is still running, and it suddenly skips down). Maybe something we only want to tackle with the results page refactor, though?

cc @rrhyne @limitedmage 

https://user-images.githubusercontent.com/1741180/105499822-4ff81000-5cc2-11eb-9a0a-5cfecb5fbbb6.mp4

**Comment by lguychard** [comment]
Notes from discussion with @rrhyne @limitedmage:
- Round the number (eg. instead of `34623 repos`, `34.6k repos`)

**Comment by limitedmage** [comment]
@rrhyne  I'll start with abbreviating numbers and if you have further ideas that we can add for the current design, please add them here.

**Comment by rrhyne** [comment]
One of the pops is the filter and repository bars rendering after not being present. To fix, we can start with these areas present but empty, then populate the actual repositories and filter chips when we have that data. 

It would be nice touch to have a very, very fast CSS fade in event when that occurs. 

What do you think?

**Comment by limitedmage** [comment]
> Two of the pops are the filter and repository bars rendering after not being present. To fix, we can start with these areas present but empty, then populate the actual repositories and filter chips when we have that data.
> 
> It would be nice touch to have a very, very fast CSS fade in event when that occurs.
> 
> What do you think?

I like this solution. I'll work to implement it once I have bandwidth.

> On the totals poping, it looks like we are breaking when it gets over col-6 or similar, but we have much more room available. If that is accurate, could we reduce the width of the tab area or perhaps use a different positioning technique?

We used to have the counts/stats bar below the tabs but this was redesigned when we started working on Streaming Search. We can go back to this if desired.

**Comment by rrhyne** [comment]
No, I don't think we should go back to under the tabs. It introduces another 30 or more pixels of vertical space before the code is displayed. Additionally, the stats and loader would either scroll off the screen when results are scrolled, or we would need to introduce another level of fixed UI, which would reduce the legible lines of code on the screen. 

The original problem has been improved with the friendly display of long numbers.

I believe it will get better when we take on https://github.com/sourcegraph/sourcegraph/issues/17573

**Comment by limitedmage** [comment]
@rrhyne  Can you create a quick design mockup of how the page would look with visibly empty filter bars? Note that we won't necessarily have *any* filters once the results are fully loaded, so we need to design with the mindset that the filter bards would be empty permanently.

**Comment by rrhyne** [comment]
I don't think we should spend much time on this before our search results redesign. Simply showing all the bars and label without the filter chips and rendering the label as placeholder text color would be fine.

![image](https://user-images.githubusercontent.com/539268/109528679-cc240700-7a69-11eb-987d-7943193f93fe.png)
