### ISSUE TITLE
search: Not all results are returned under new structural search path

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#17569]
#### Steps to reproduce:
Compare the results of `repo:^github\.com/kubernetes/kubernetes$ Eventf(cj, :[1]) rule:'where "zoekt" == "zoekt"'` to `repo:^github\.com/kubernetes/kubernetes$ Eventf(cj, :[1])`. The first triggers the new code path, and returns fewer results.

This appears to be because the `Matcher` arg is not set, so comby must use the generic matcher. Setting `lang:go` in the query fixes the issue, but it's unclear yet how the current structural code path is getting the lang.

**Comment by rvantonder** [comment]
Nice catch. So in either path, it's currently going to be the case that if the user doesn't specify a language, we fall back to a generic matching (i.e., adding `lang:go` is always the best thing to do). I think part of solving this is doing better in the UI/UX and frontend (and we can hint at which `lang:` to add, etc.). Any case, I suspect the fewer results on the new path is maybe a case of nondeterminism, I can't find any code that does something more special than that.

We can do better here in general with a more proper fix, and then there's the "quick" improvement using the way you have in the PR, which I think works for now :-) More comments there.

**Comment by rvantonder** [comment]
> Any case, I suspect the fewer results on the new path is maybe a case of nondeterminism, I can't find any code that does something more special than that.

Gah, I missed something here. Yes, populating `includeFilePattterns` will influence the matcher, because on comby will look at command line flags for file filters and detect an extension. It will pick the first file it sees as an extension. Since on the new path we send no file filters at all, it falls back to the generic matcher.

**Comment by camdencheek** [comment]
For context: Leaving this issue open because, though the linked PR is fixed, it does much more work than necessary, especially when there are a large number of files. See https://github.com/sourcegraph/sourcegraph/pull/17572#discussion_r562836148
