### ISSUE TITLE
Add "members" section to code insights handbook page, or remove it from the org chart

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#17576]
The code insights team doesn't appear in [our org chart](https://about.sourcegraph.com/company/team/org_chart), because there is no code insights team!

![image](https://user-images.githubusercontent.com/5589410/105535393-b1f54d00-5ca3-11eb-94b9-1acb3fc14806.png)

Can we just add a "members" section to that page with a note about how we will be hiring for it in the future, so this error is fixed?

**Comment by felixfbecker** [comment]
There is a @sourcegraph/code-insights team, it's me and @Joelkw :)
Will add the formal "Members" section.

**Comment by Joelkw** [comment]
@dadlerj @felixfbecker haha whoops, I noticed and fixed this error before I'd caught up on notifications for the day and saw this. But I didn't indicate we were hiring explicitly – [PR for that update](https://github.com/sourcegraph/about/pull/2395) is here now.
