### ISSUE TITLE
Code intelligence result types in hovers shouldn't be dismissible 

### ISSUE THREAD

**Issue by macraig** [sourcegraph/sourcegraph#17582]
At the moment we display the type of results a user is getting (whether it's search-based or semantic) in a dismissible alert in the hover. This often results in users dismissing the alert and later being confused about what type of results they are getting. This information is valuable and important and it shouldn't be subject to being dismissed by mistake.

Proposal: Change the way we present result types from alerts to a more persistent component.

**Comment by olafurpg** [comment]
Thank you for opening this issue! One possible way to indicate that a file has precise code intel would be to underline all references, similar to the chromium code search.


https://user-images.githubusercontent.com/1408093/105860310-b6946b00-5fed-11eb-8d30-3f54000e2360.mp4

I don't think we need a toggle to enable/disable underlines, I would enable them by default when LSIF is available. The benefit of underlines is that they also provide a visual hint about what identifiers have precise intel.

For now, I don't think it's necessary to display a tooltip or message when precise code intel is missing. We can use other ways to advertise LSIF, for example in the Sourcegraph settings or admin panel. Down the road, we can add tooltips on how to enable precise code intel for languages that are known to have mature LSIF support (Go, TypeScript, ..).

**Comment by efritz** [comment]
For context, here is where we define all of our tooltips. They can be trivially enabled/disabled on all instances (without a deploy step) by modifying this file and publishing new extensions to the registry.

**Comment by olafurpg** [comment]
Findings after some investigation on this issue:

* you can re-enable the LSIF tooltips by executing this command in the JS console `localStorage["WebHoverOverlay.dismissedAlerts"] = "[]"`. This workaround will re-enable all Sourcegraph tooltips that have been dismissed, not only LSIF ones.
* there doesn't appear to be a UI to view dismissed tooltips or a UI button to re-enable tooltips.
* the state is local to the browser, so you can change to another browser to see the tooltip again.
* for LSIF, I think it would make sense to remove the tooltip and use another visual indicator when LSIF is available that can't be dismissed.

**Comment by felixfbecker** [comment]
FYI I think the extension can also control whether the alert is dismissable or not

**Comment by AlicjaSuska** [comment]
[Design](https://www.figma.com/file/nm32rgS1n4j6SA9Tk7cz30/Code-intelligence-result-types-in-hovers-shouldn-t-be-dismissible-17582-Review?node-id=275%3A1628) is ready for your review @olafurpg @macraig - please, review by Monday :) Thank you!

Summary:
- added a permanent label to the tooltip that shows the result type and links to docs
- we can keep the alert for new users. I've changed its color and structure
- added a label to each item in the references panel to indicate the result type. Those labels also link to docs.
- we need to remove the 'i' icon from the results list

**Comment by felixfbecker** [comment]
@sourcegraph/extensibility should also review since this goes through the extension API.

**Comment by scalabilitysolved** [comment]
Should we move this back to the planning board for Monday @macraig ?

**Comment by AlicjaSuska** [comment]
@macraig [design](https://www.figma.com/file/nm32rgS1n4j6SA9Tk7cz30/Code-intelligence-result-types-in-hovers-shouldn-t-be-dismissible-17582-Approved?node-id=246%3A11) is ready and approved - we can move forward to implementation :)
