### ISSUE TITLE
LSIF indexer for every language

### ISSUE THREAD

**Issue by alidn** [sourcegraph/sourcegraph#17591]
Hi, I'm sure what the best way is to reach out to everyone in the code-intel team, so I'm writing it here.

#### Idea description
An indexer that can generate LSIF data for every language using an LSP server. A working implementation of the idea: https://github.com/alidn/universal-lsif.

#### Is your feature request related to a problem? If so, please describe.
Can't use Sourcegraph with precise code intelligence for a language unless there is an LSIF indexer for it. Sourcegraph supports more than 20 languages but only 9 of them have an indexer. On the other hand, there is an LSP server for almost every language. This can be an alternative until Sourcegraph implements fast indexers for all the major languages.

#### Describe alternatives you've considered.
Another language-agnostic tool for generating LSIF data using tree-sitter (https://github.com/alidn/lsif-os). It is extremely fast and precise enough, but not as precise as a language-specific indexer.

**Comment by alidn** [comment]
Closed in favour of #17378

**Comment by efritz** [comment]
@alidn For future reference we have a `team/code-intelligence` tag if you want particular attention from us :)

**Comment by alidn** [comment]
Thank you!
