### ISSUE TITLE
Search query "checklist" for code monitor trigger queries

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#17603]
## Problem

In our user testing for code monitoring, we’ve observed developers using the search query error messages to iteratively reach a valid search query for a trigger, which forces them to go against error messages to get it right—ultimately turning a positive process of iteration into a negative experience. If we improve this, it will improve the process of writing a query for a code monitor's trigger while improving in-context product education.

## Proposal

I propose we implement a "checklist" of requirements for a valid search query for a code monitor, which specifically lists each required element. This is in place of "defaults" in the search query, which I believe users will typically replace without consideration, making them less effective as a solution for this problem.

This approach follows patterns used for new password validation, where the requirements for a valid password are clearly listed ahead of time.

As well, we can use inline tooltips to provide extra context and education about why these filters are required, and what they do.

Finally, I suggest we make `repo:` a required element for these search queries. Right now, the value of code monitors is already limited in that `type:diff` and `type:commit` have a "hidden" 50 repo limit, which we've already seen can create serious problems for users who don't realise this limitation is in place.

**Validation checklist** / Empty
<img width="687" alt="CleanShot 2021-01-25 at 11 09 09@2x" src="https://user-images.githubusercontent.com/6304497/105692094-4bb83680-5efe-11eb-9db8-b8d90bea481f.png">

**Validation checklist** / Tooltip
<img width="682" alt="CleanShot 2021-01-25 at 11 13 23@2x" src="https://user-images.githubusercontent.com/6304497/105692206-6ab6c880-5efe-11eb-9645-af16a1596c50.png">

**Validation checklist** / One filter present
<img width="686" alt="CleanShot 2021-01-25 at 11 13 15@2x" src="https://user-images.githubusercontent.com/6304497/105692238-74403080-5efe-11eb-98fb-1ff7f750104a.png">

**Validation checklist** / Fully valid query
<img width="687" alt="CleanShot 2021-01-25 at 11 14 34@2x" src="https://user-images.githubusercontent.com/6304497/105692290-84f0a680-5efe-11eb-86e9-b4d66e114218.png">

- [View and share feedback on Figma](https://www.figma.com/file/Krh7HoQi0GFxtO2k399ZQ6/RFC-227-%E2%80%93-Code-monitoring-actions-and-notifications?node-id=3855%3A2039)

**Comment by limitedmage** [comment]
Really like this design and it makes creating a code monitoring a lot clearer. I think the hover hints need to be very clear and useful though, to make sure users understand **why** they need to add these filters.

**Comment by quinnkeast** [comment]
Update: here's a [high-fidelity design proposal in Figma](https://www.figma.com/file/Krh7HoQi0GFxtO2k399ZQ6/RFC-227-%E2%80%93-Code-monitoring-actions-and-notifications?node-id=3891%3A41568).

<a href="https://www.figma.com/file/Krh7HoQi0GFxtO2k399ZQ6/RFC-227-%E2%80%93-Code-monitoring-actions-and-notifications?node-id=3891%3A41568 "><img width="849" alt="CleanShot 2021-01-27 at 11 30 19@2x" src="https://user-images.githubusercontent.com/6304497/105978637-0e38e200-6093-11eb-9b71-a3354acedf3c.png"></a>

**Comment by limitedmage** [comment]
@quinnkeast  @AlicjaSuska  is the design complete and ready for dev implementation?

**Comment by quinnkeast** [comment]
Yes, I believe so! The [high-fidelity is available on Figma](https://www.figma.com/file/Krh7HoQi0GFxtO2k399ZQ6/RFC-227-%E2%80%93-Code-monitoring-actions-and-notifications?node-id=3891%3A41568). Let me know if there's anything else that's needed or unclear.
