### ISSUE TITLE
Show "Search for symbol" instead of "Go to definition" and "Find references" when they are imprecise

### ISSUE THREAD

**Issue by macraig** [sourcegraph/sourcegraph#17617]
Show a "Search for symbol" button instead of "Go to def" or "Find references" if code intel is search-based. This would replace the alert disclaimer in the case below:

![Screenshot 2020-11-05 at 18 07 20](https://user-images.githubusercontent.com/1657213/98398523-65fe1900-2061-11eb-82f2-890d9b73e68e.png)

Note: Moved from [#1966](https://github.com/sourcegraph/about/issues/1966)

**Comment by scalabilitysolved** [comment]
@macraig with our recent naming discussions and hover changes, I think this perhaps isn't as relevant anymore? Going to close but please re-open if needed!
