### ISSUE TITLE
Show transitive dependencies for modules

### ISSUE THREAD

**Issue by macraig** [sourcegraph/sourcegraph#17623]
From customer https://app.hubspot.com/contacts/2762526/company/814799425 

Feature request: dependency graphs — Find References but for modules. Our team would love to see transitive dependencies for applications to determine whether it’s ok to archive repositories.

Steps
1. Expose dependency graphs to GraphQL.
2. Explore design options and decide where is the right place for this information to live in the UI

High-level proposals:
- Repository level: for each repository find out every project on the instance that uses it
- When viewing a package manifest (eg. go.mod package.json) provide versioned links to dependencies from that manifest.

**Comment by stiti75** [comment]
sxsx

**Comment by stiti75** [comment]
dffgdfg

**Comment by stiti75** [comment]
fdgdfg

**Comment by stiti75** [comment]
fdfg

**Comment by stiti75** [comment]
fsfsdf

**Comment by macraig** [comment]
This feature request is now being tracked in [Productboard](https://sourcegraph.productboard.com/feature-board/1825051-code-intel/features/8233720/detail)
