### ISSUE TITLE
Private repository on sourcegraph.com shows "Empty repository" instead of 404

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#1762]
Load https://sourcegraph.com/github.com/sourcegraph/test-private-package

**Expected**

![image](https://user-images.githubusercontent.com/754768/50945864-936ce200-144b-11e9-9b7f-4547c372b1a6.png)

**Actual** 
![image](https://user-images.githubusercontent.com/754768/50945850-864ff300-144b-11e9-8386-2a39ca97e0c1.png)

If you try to load a repo that actually doesn't exist, the correct behavior happens.
https://sourcegraph.com/github.com/sourcegraph/test-private-package2 (doesn't exist)

Honestly I am a bit confused how test-private-package was cloned in production in the first place (cc @keegancsmith ?)

reported by @felixfbecker 

---

I debugged this a bit and here are my notes.

The relevant graphql call is this
```
"
                query Repository($repoName: String!) {
                    repository(name: $repoName) {
                        id
                        name
                        url
                        externalURLs {
                            url
                            serviceType
                        }
                        description
                        enabled
                        viewerCanAdminister
                        redirectURL
                        defaultBranch {
                            displayName
                        }
                    }
                }
            "
```

The expected response (or at least what is returned when the repo actually doesn't exist) is:
```json
{"data":{"repository":null}}
```

But the actual response is
```json
{
  "data": {
    "repository": {
      "id": "UmVwb3NpdG9yeTozNzQ0ODk4OA==",
      "name": "github.com/sourcegraph/test-private-package",
      "url": "/github.com/sourcegraph/test-private-package",
      "externalURLs": [],
      "description": "Test private npm package",
      "enabled": true,
      "viewerCanAdminister": true,
      "redirectURL": null,
      "defaultBranch": null
    }
  },
  "errors": [
    {
      "message": "repository does not exist: github.com/sourcegraph/test-private-package",
      "path": [
        "repository",
        "defaultBranch"
      ]
    }
  ]
}
```

So it is returning both a repo and an error. 

Given that the defaultBranch field is null, my guess is [that field resolver](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/repository.go#L136) is returning an error (correctly it seems). The real question is why is this private repo in our db in the first place?

**Comment by tsenart** [comment]
@keegancsmith: I'll be working on #914 even before beginning on the larger `repos-service` work, so we should have that going right after the 3.0 release.

**Comment by felixfbecker** [comment]
Maybe it was public before and then was switched to private.
This seems to be a security issue because we are leaking the existence of a private repo.

**Comment by nicksnyder** [comment]
@felixfbecker was this repo ever public?

**Comment by felixfbecker** [comment]
I don't know. You can probably check in the GitHub audit log. I don't have access

**Comment by nicksnyder** [comment]
We should fix, but I don’t think I would go so far as to quality this as a security issue. We aren’t leaking information that wasn’t already public (and probably cached/archived by many other services on the internet).

**Comment by keegancsmith** [comment]
According to the audit log it never had its visibility changed. I'm not sure how else we could of gotten the repo description unless that happened, so pretty weird. Maybe the audit log is missing some info, or a repo with the same name used to exist?

![image](https://user-images.githubusercontent.com/187831/50973907-ba322380-14f2-11e9-9bd7-7b146189a7ef.png)

**Comment by felixfbecker** [comment]
I took no actions about this repo yesterday.

**Comment by nicksnyder** [comment]
I can't explain or reproduce why this happened, but this is exactly the issue that should be addressed categorically by https://github.com/sourcegraph/sourcegraph/issues/914. I manually deleted this repo from the db in production so I am going to close this as a duplicate of https://github.com/sourcegraph/sourcegraph/issues/914
