### ISSUE TITLE
upgrade deploy-sourcegraph-dhall implementation to latest deploy-sourcegraph commits 

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#17632]
Requires changing https://github.com/sourcegraph/deploy-sourcegraph-dhall/blob/main/.env and upgrading the implementation as appropriate (for example - the diff should be non-existent when diffing ds-dhall and deploy-sourcegraph `just diff-ds`)

**Comment by uwedeportivo** [comment]
https://github.com/sourcegraph/deploy-sourcegraph-dhall/pull/60
