### ISSUE TITLE
no alert if literal search contains "..." and 0 results

### ISSUE THREAD

**Issue by stefanhengl** [sourcegraph/sourcegraph#17630]
I believe this query should return an alert asking to enable structural search, but it doesn't

https://sourcegraph.com/search?q=select+%7B+...+default:+%7D&patternType=literal

<img width="808" alt="image" src="https://user-images.githubusercontent.com/26413131/105814993-8aa7c400-5fb2-11eb-8311-96c3f1cddcb5.png">

**Comment by rvantonder** [comment]
The suggestion trick doesn't trigger for `...` syntax, only `:[...]` syntax. I would feel comfortable raising that alert only if there are no results. Reasonable to do in the backend, but I actually prefer putting that sort of alerting logic in the web app now.

**Comment by rvantonder** [comment]
Eh, since the logic [already exists](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/cmd/frontend/graphqlbackend/search_results.go#L2057), this is an easy fix in the backend, so I'll do it there for now. Thanks.
