### ISSUE TITLE
Swift language Code intelligence Support using SourceKit-LSP

### ISSUE THREAD

**Issue by satishbabariya** [sourcegraph/sourcegraph#1763]
#### Feature request description
[experimental]
Swift language Code intelligence Support  Using [https://github.com/apple/sourcekit-lsp](https://github.com/apple/sourcekit-lsp)

**SourceKit-LSP:**
SourceKit-LSP is an implementation of the Language Server Protocol (LSP) for Swift and C-based languages. It provides features like code-completion and jump-to-definition to editors that support LSP. SourceKit-LSP is built on top of sourcekitd and clangd for high-fidelity language support, and provides a powerful source code index as well as cross-language support. SourceKit-LSP supports projects that use the Swift Package Manager.

**Comment by chrismwendt** [comment]
We'd love to get Swift support implemented! Closing in favor of the existing issue, also using sourcekite-lsp https://github.com/sourcegraph/sourcegraph/issues/1557
