### ISSUE TITLE
Frontend: Implement omnipresent feedback widget

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#17645]
Part of implementing [RFC 215: Improving User Feedback](https://docs.google.com/document/d/1mn3AxOMLM_ivu-mfWa3VAXyJnmX4WFInREdB2kI_g6o/edit#).

**Description**

Implement the omnipresent feedback widget.

<a href="https://www.figma.com/file/9FprSCL6roIZotcWMvJZuE/Improving-user-feedback-channels?node-id=300%3A3110"><img width="698" alt="CleanShot 2021-01-26 at 10 31 54@2x" src="https://user-images.githubusercontent.com/6304497/105827003-baaa9380-5fc1-11eb-9263-98f52d5a61b0.png"></a>

Interaction details can be found in the Figma docs.

Emojis should use [Twimoji](https://twemoji.twitter.com/content/twemoji-twitter/en.html). Please reference [@dadlerj's comment in Slack regarding how to handle licensing](https://sourcegraph.slack.com/archives/C01GJFE26BX/p1611678214005300?thread_ts=1611677489.004800&cid=C01GJFE26BX).

The submitted response will include:

- The open-ended feedback
- The “happiness” response
- The current URL
- The user’s email/username (when available, e.g. on Cloud)
- The user’s organization (when available)
- (Other data? @attfarhan @ebrodymoore)

In the submission confirmation, link to the user settings page for Product feedback and research (#17646). Note that confirmation content may be affected by site admins choosing to disable the product feedback page (#17647).

**Design documentation:**

- [View in Figma](https://www.figma.com/file/9FprSCL6roIZotcWMvJZuE/Improving-user-feedback-channels?node-id=300%3A3110)
- [Simple prototype in Figma](https://www.figma.com/proto/9FprSCL6roIZotcWMvJZuE/Improving-user-feedback-channels?node-id=262%3A11&viewport=483%2C450%2C0.21965965628623962&scaling=min-zoom)
- [Emoji-selection animation on CodePen](https://codepen.io/quinnkeast/pen/bGpazQo)

**Comment by umpox** [comment]
@quinnkeast @attfarhan @ebrodymoore It doesn't seem clear where we will actually send the data once a user clicks 'Send'. Is this still undecided? We can work on the UI in the meantime.

**Comment by quinnkeast** [comment]
Yes, @ebrodymoore is working with us to finalize our plan for this. It's safe assumption that we'll submit responses via an API to a service like HubSpot. I'll keep you updated as soon as we have this locked in.

**Comment by ebrodymoore** [comment]
@quinnkeast or @umpox - what should the field type be for the happiness response? If the emoji will be converted to a number I can make it only take integers, otherwise I'll make it text.

**Comment by quinnkeast** [comment]
@ebrodymoore I'm going to defer to you on the best field type for this data, as ultimately it will be used to calculate a happiness score. (Another option is to use the emoji itself, which could be useful for differentiating data in the future if we change an emoji (e.g. instead of 4 → 4, it'd be 😄 → 🤩 ... whether or not that's valuable, I don't know.)

**Comment by ebrodymoore** [comment]
Let's do an integer then. Emojis in the database would not be pretty 😆 

@umpox here's how the widget should map into HubSpot. I gathered my understanding from this example, but let me know if I'm off on my understanding or you need more information!

Here's [the form itself](https://app.hubspot.com/forms/2762526/417ec50b-39b4-41fa-a267-75da6f56a7cf/performance). We won't use the HubSpot form itself obviously, but the submissions should go to this object. NPS is the same way; we can view all the submissions [here](https://app.hubspot.com/forms/2762526/a86bbac5-576d-4ca0-86c1-0c60837c3eab/submissions). I couldn't find this in the code how it knows it's an NPS survey being submitted, but hopefully I'm just missing something that's obvious to you, or we can dig into more otherwise!

Mapping (and HubSpot field type):
The open-ended feedback → `happiness_feedback` (text)
The “happiness” response → `happiness_score` (int) 
The current URL → `happiness_current_url` (text)
The user’s email/username (when available, e.g. on Cloud) → `happiness_username` (text)
The user’s organization (when available) → `site_id` (text)

**Comment by quinnkeast** [comment]
Thanks, Eric! While we're at it, do let us know if there's any other data points we should be capturing here that we might not be thinking of.

**Comment by ebrodymoore** [comment]
I don't think so! The timestamp is captured automatically by HubSpot when the form is submitted (screenshot). Apart from that, the NPS responses have a `Submitting user is authenticated` field but we never use that, and can assume it's a no if there's no username and the site ID is from Sourcegraph Cloud anyway. 
<img width="423" alt="Screen Shot 2021-02-03 at 9 02 18 AM" src="https://user-images.githubusercontent.com/25422491/106773642-860c8c80-65fe-11eb-8b43-1702ccead69c.png">

**Comment by quinnkeast** [comment]
Perfect!

**Comment by umpox** [comment]
@ebrodymoore 

> The user’s email/username (when available, e.g. on Cloud) → happiness_username (text)

Could I clarify exactly what we want here? Do we ever want a users email? It feels potentially confusing to be sending an email for `happiness_username`.

**Comment by ebrodymoore** [comment]
Good point. How about if the user is submitting from Sourcegraph Cloud we capture their email, and if they're submitting from any other instances we don't? And by capturing their email, we can follow the logic in the NPS surveys and map it to `email` and ignore the `happiness_username` field.  

How does that sound? (@quinnkeast too)

**Comment by umpox** [comment]
@ebrodymoore @quinnkeast Quick thought:

We're capturing the current URL for all submissions, when this eventually reaches private instances it will mean that we could capture some private repository data e.g. 

`Page submitted on: https://sourcegraph.com/github.com/someorg/privaterepo`

Should we only send `happiness_current_url` to HubSpot when submitting from Sourcegraph Cloud?

**Comment by quinnkeast** [comment]
Oh, nice catch. If that's protected information then we definitely don't want to be capturing it. Is there a way to redact private info while still providing location context ("viewing a repo" for example)?

**Comment by umpox** [comment]
Reopening with two amendments:

- Only show the prompt for authenticated users
- Adjust location tracking for non-cloud customers
