### ISSUE TITLE
dhall: implement searcher

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#17642]
- [x] create implementation that mimics default deploy-sourcegraph's YAML with defaults 
- [x] write customizations that match ones implemented for other components (see documentation.md files - for example all components should support customizing resource requirements even if this container specifically doesn't do it) and souregraph.com's unique customizations
- [x] write documentation.md file
- [x] write tests

**Comment by pecigonzalo** [comment]
@ggilmore isnt this done in https://github.com/sourcegraph/sourcegraph/issues/16267? https://github.com/sourcegraph/deploy-sourcegraph-dhall/tree/main/src/k8s/components/searcher

**Comment by uwedeportivo** [comment]
it's done, sorry
