### ISSUE TITLE
dhall: implement prometheus

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#17640]
- [ ] create implementation that mimics default deploy-sourcegraph's YAML with defaults 
   - [ ] https://github.com/sourcegraph/sourcegraph/issues/17640#issuecomment-768110304
- [ ] write customizations that match ones implemented for other components (see documentation.md files - for example all components should support customizing resource requirements even if this container specifically doesn't do it) and souregraph.com's unique customizations
- [ ] write documentation.md file
- [ ] write tests

**Comment by bobheadxi** [comment]
Note: this should ideally support namespace-based generation of the configmap, see https://github.com/sourcegraph/sourcegraph/issues/17365 and https://github.com/sourcegraph/deploy-sourcegraph/pull/1644
