### ISSUE TITLE
Frontend: Create reusable text-based in-context feedback component

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#17648]
Part of implementing [RFC 215: Improving User Feedback](https://docs.google.com/document/d/1mn3AxOMLM_ivu-mfWa3VAXyJnmX4WFInREdB2kI_g6o/edit#).

**Description**

Create a reusable, flexible text-based component for prompting users for feedback in context.

<img width="978" alt="CleanShot 2021-01-26 at 11 02 23@2x" src="https://user-images.githubusercontent.com/6304497/105830604-fc3d3d80-5fc5-11eb-83e7-2ad78b13827f.png">

This component should allow for:

- An optional "leading" text element
- A required "call to action" text element that will be linked
- A required link, which will change, and may be a URL link or a `mailto:` link

This element is already being used in the [Code monitoring](https://sourcegraph.com/code-monitoring) feature, and should be formalized as a re-usable component.

**Design documentation:**
- [View in Figma](https://www.figma.com/file/9FprSCL6roIZotcWMvJZuE/Improving-user-feedback-channels?node-id=630%3A3833)

**Comment by umpox** [comment]
For this should be able to rework `<StatusBadge />` a little from https://github.com/sourcegraph/sourcegraph/pull/17521

**Comment by umpox** [comment]
Closing as I think the work for this is already done (in https://github.com/sourcegraph/sourcegraph/pull/17521). Feel free to reopen if you disagree!

Our StatusBadge component supports all of this except specifically the optional leading text. The component can currently be configured with a styled 'status' (e.g. prototype, WIP) badge. It should be trivial to update this to support standard plaintext if we have an implementation need (I don't currently see any design that uses the leading text element instead of the status)

**Comment by quinnkeast** [comment]
Would this component also cover the use case of appearing without the badge, within other content?

Here's an example:

<img width="1054" alt="CleanShot 2021-02-03 at 12 15 16@2x" src="https://user-images.githubusercontent.com/6304497/106739514-88c8ab00-6619-11eb-93f4-18bca7800277.png">

[Link to Figma](https://www.figma.com/file/Krh7HoQi0GFxtO2k399ZQ6?node-id=3512:30543#60950302)

**Comment by umpox** [comment]
Ah okay I see. Unfortunately it wouldn't, `StatusBadge` is primarily just a styled badge (of a certain type, e.g. WIP) with an optional feedback link. I'm a little wary that reworking this to support plaintext + link could be an over abstraction. We can already achieve this with the standard `<small>` and `<a>` HTML elements. Unless we have some specific logic (e.g. generating the link from a users details?) I don't personally feel this would be worth extracting into a component.

Thoughts @sourcegraph/frontend-platform ?

**Comment by felixfbecker** [comment]
Agree, I don't really see the benefit of abstracting this as a component. Even if it existed, I think engineers would not intuitively find and use it over just `<small>`+`<a>`. @quinnkeast could you explain more the benefits of having it as a component?

I would say though that regardless of whether we should do it or not that is what the issue asked for so we should reopen it imo.

**Comment by quinnkeast** [comment]
Ultimately, the request for a reusable component was a thought that came up a few times, but implementation-wise, I defer to the @sourcegraph/frontend-platform team on the best approach. I'm happy to consider this issue closed.
