### ISSUE TITLE
Ext debug menu has bullet in browser extension

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1765]
![screenshot from 2019-01-09 23-50-01](https://user-images.githubusercontent.com/1976/50953783-4e57a880-1469-11e9-8669-c3006db9217f.png)

In the browser extension, when you run `localStorage.debug=true;location.reload()`, the Ext debug menu has a bullet. There should be no bullet. (Be careful to not override the code host's own CSS.)

**Comment by vanesa** [comment]
I can no longer reproduce the issue.
