### ISSUE TITLE
Private code made public not accessible on Cloud

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#17672]
A repo that was originally private has been made public on Cloud but is not accessible and we see a 500 error:
https://sourcegraph.com/github.com/uccnetsoc/shortener

**Comment by unknwon** [comment]
I did a quick try but no luck, there is no error of the log in GCP logs or the trace: https://sourcegraph.com/-/debug/jaeger/trace/ef9da231ed10e8c

**Comment by ryanslade** [comment]
I think it could be the new `GetVCSyncer` code. If the repo doesn't exist, this code path will fail:
https://github.com/sourcegraph/sourcegraph/blob/main/cmd/gitserver/main.go#L89

I'll prepare a fix.. I think we may need use a heuristic to guess the code host type if we can't find it in the db
