### ISSUE TITLE
RFC 277: Simulate and test a large Perforce depot end-to-end

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#17682]
Set up a Perforce depot that has ~~6 months of history (if it's possible like Git to fake "commit time"), and with~~ ~~10k~~ 1000 changes.

- [Creating and Initializing a New Perforce Depot](https://www.youtube.com/watch?v=pv4tvwghGCQ)

**Comment by unknwon** [comment]
I didn't find a way to fake commit time but the time actually doesn't matter much, the number of commits matters.

By using my poor-man's version of script to generate p4 changes, it takes ~10s for each change, and import 100 changes is already slow, so I'm gonna aim for 1000 changes instead of 10k changes (which otherwise could take my life to import such depot and do any useful test). 

![](https://media0.giphy.com/media/7wVFzrFY35eNd6wAPu/giphy.gif)

**Comment by tsenart** [comment]
@unknwon: I think we need to translate the results of this test into a) user documentation and b) next steps for trialing customers (i.e. what does this mean for them?)

**Comment by unknwon** [comment]
Test is done, and adding some docs in https://github.com/sourcegraph/sourcegraph/pull/19981.
