### ISSUE TITLE
Fix inconsistencies in page padding

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#17702]
Pages across the Sourcegraph web application are not using consistent padding/margins.

Example:
![image](https://user-images.githubusercontent.com/9516420/105968962-9e6d2c00-607f-11eb-8c53-0bf9e5c7572c.png)

We should align this, and ensure that these pages stay aligned (e.g. maybe we might want a `<Page></Page>` component that wraps and applies a set of styles)

**Comment by umpox** [comment]
1. We want to apply a top padding of 24px to pages, as referenced here: https://github.com/sourcegraph/sourcegraph/pull/17521#pullrequestreview-575508041. This seems better to apply to a global `Page` style rather than specifically to the Header component.
2. It seems most pages are currently wrapped with the following classes: `container web-content mt-3`. This applies the following spacing: `padding-right: .75rem; padding-left: .75rem;`.

@AlicjaSuska Just adding this to the design priorities just to confirm. To summarise the above, it seems we will want to essentially wrap pages across the Sourcegraph web app in these styles:
```
 margin-top: 1.5rem;
 margin-bottom: 1.5rem;
 padding-right: .75rem;
 padding-left: .75rem;
```

**Comment by felixfbecker** [comment]
We don't currently have a global "Page" style, but we have the `container` class that web-content pages use, which defines left and right spacing.
Is there a benefit to adding a `Page` component over adding the margin to the page header? Do we have any pages not using page headers that should have the same padding regardless? That would be an argument in favor of a `Page` component. A disadvantage would be that people can easily forget to use the `Page` component for new pages (while forgetting to use `PageHeader` is less likely).

**Comment by umpox** [comment]
@felixfbecker Giving `PageHeader` a `24px/1.5rem` top margin feels wrong imo, that component should not be concerned with how it is externally positioned. For example, we'd run into issues if we ever actually want something above that component like a banner. We do also currently have quite a few pages not using page headers, for right or wrong reasons (e.g. site admin pages).

**Comment by felixfbecker** [comment]
Good argument.

**Comment by AlicjaSuska** [comment]
All correct @umpox

**Comment by AlicjaSuska** [comment]
The paddings you've listed are correct @umpox 👍
