### ISSUE TITLE
Streaming search: "unable to process query" errors aren't properly surfaced

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#17703]
**Steps to reproduce**

Attempt to run [`file:*.ts`](https://sourcegraph.com/search?q=file:*.ts&patternType=regexp) (invalid use of globbing) with streaming search.

**Expected**

"Unable to process query" alert is shown.

![image](https://user-images.githubusercontent.com/1741180/105969121-2f480580-6088-11eb-8fce-f756cb93f82a.png)

**Actual**

"Connection was closed before your search was completed" error.

![image](https://user-images.githubusercontent.com/1741180/105969034-15a6be00-6088-11eb-9b06-72caaf2da5b8.png)

**Comment by keegancsmith** [comment]
The response from the backend is a single event:
```
error: "SearchImplementer does not support streaming"
```

So three problems here:
- Backend: need to handle alerts that occur before streaming starts.
- Backend: send done event after error.
- Webapp: Prefer showing error over connection not shutting down cleanly. Does webapp handle error event?

For the second point we could make it such that error events are final events in a stream. But I think its cleaner to always send a done event.

**Comment by keegancsmith** [comment]
> Webapp: Prefer showing error over connection not shutting down cleanly. Does webapp handle error event?

I don't think this is actually needed. It is now fully solved in the backend.
