### ISSUE TITLE
ci: restore e2e tests

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#1772]
Originally disabled as part of https://github.com/sourcegraph/sourcegraph/issues/976

**Comment by ggilmore** [comment]
The other issues that I am working on the milestone are low-hanging fruit compared to this one. I think it's the next-most-important thing for me to tackle, but I'm not sure that it'll land in 3.0. This issue is complex enough that it warrants its own proposal.

**Comment by ggilmore** [comment]
I'll need to write a longer but a few quick notes:

- we want to maintain the property that the manifests checked into the dot
com repository are always safe to deploy

- our previous relied on synchronous kubernetes rollouts so that test
failures can be tied to a commit

- since renovate is an asynchronous tool, the above is not possible with
that workflow

So, there a few options to resolve this:

1. Ditch the safety property above and go back to what we have before. I
think this is undesirable

2. Ditch renovate and replace it with a synchronous tool. This has some
complexities: maintaining yaml formatting, what happens if there are merge
conflicts, etc.

3. Have a new "e2e" cluster that people normally don't deploy to and are
only used for e2e tests. This cluster wouldn't need up to date manfiest
files. We could really use a lot our existing deployment code. However, it
seems wasteful to have a separate cluster and this introduces the
possibility test failures that have to do with the cluster's out of band
configuration and nothing to do with the commit being tested

4. Make it possible to run the e2e tests entirely within CI. To me this
means that CI will need to be capable of spinning up a docker container (or
a k8s cluster) and "driving it" so that it can attach language servers to
it and interact with the web UI. I don't know of an existing tool that can
do this and writing one will be an undertaking

**Comment by nicksnyder** [comment]
I would pursue (4) first. Seems like it should be possible to docker run sourcegraph/server in the background, run a language server, configure sourcergraph to point to the language server (this might be a non-zero amount of work to expose an API to do this), then point the current e2e tests at this instance (headless browser?). @felixfbecker and @ijsnow can probably provide good advice here.

**Comment by nicksnyder** [comment]
Seems like these are enabled now.
