### ISSUE TITLE
[Cloud] Add GraphQL mutation to create passwords for users signed-up with OAuth

### ISSUE THREAD

**Issue by artemruts** [sourcegraph/sourcegraph#17729]
### Description

Sourcegraph Cloud has a sign-up with GitHub/GitLab option.  At the same time, users can remove their connected GitHub/GitLab accounts. This can create a situation where users who signed-up with OAuth and removed their external accounts will be left without a password. 

We will take care of that in redesigned UI ([Figma](https://www.figma.com/file/zXvqCASHDzmvKbrAl1EVsd/Public-and-Private-Repos-for-Users-on-Cloud?node-id=1695%3A0)). For that, we'll need a new API to create a password for existing users when they don't have one.

### Acceptance criteria

Add new GraphQL API:  `Mutation.createPassword(userID!: ID, newPassword!: String)` that will successfully execute when users don't have a password.

### Notes

I synced on this with @quinnkeast to confirm if we should do this.
@unknwon / @ryanslade - WDYT?

**Comment by ryanslade** [comment]
I think this is ok but I'm worried about the security implications. I can't think of a specific issue right now but it makes me feel uneasy 😄 

Will this option always appear as long as they don't have a password set and they have zero sign in connections?

If they are logged out in some way we plan to use the reset password flow right?

**Comment by quinnkeast** [comment]
>Will this option always appear as long as they don't have a password set and they have zero sign in connections?

Yes, but it'll only be shown during the period of time while they're still authenticated for current session, and after removing all sign in connections. Otherwise, they'll have to use the reset password flow.

**Comment by unknwon** [comment]
Sounds OK... but we have to be 100% that the user _didn't have a password_. We can't just arbitrarily allow setting a password without knowing the previous one. Bob could just go to alice's computer and set a new password...

**Comment by artemruts** [comment]
Not an expert, so I defer to backend engineers on this.
I thought it can be done with: 

check that for given user ID
- `passwd`, `passwd_reset_time`, `passwd_reset_code` fields are `NULL` in `users` table
- every account in `user_external_accounts` is deleted or expired
