### ISSUE TITLE
ci: restore automatic k8s deployments

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#1773]
Originally disabled as part of https://github.com/sourcegraph/sourcegraph/issues/976

**Comment by ggilmore** [comment]
This has been implemented for dogfood and sourcegraph.com with the following caveats:

1. It can take ~1.5 hours or more for an update to an image tag to be deployed to sourcegraph.com since Renovate is asynchronous

1. Buildkite doesn't deploy RBAC resources automatically since updates to those resources require elevated GCP permissions

1. There are no e2e tests blocking bad deployments from reaching production

1. There isn't a clear linkage between a sourcegraph/sourcegraph commit and the docker image tag that it corresponds to

**Comment by tsenart** [comment]
This is great! Thanks :-) Some follow up questions on the caveats.

> It can take ~1.5 hours or more for an update to an image tag to be deployed to sourcegraph.com since Renovate is asynchronous

It might not be the best approach for us to rely on Renovate to update our own images, given the much higher rate of change. What other options do we have?

> Buildkite doesn't deploy RBAC resources automatically since updates to those resources require elevated GCP permissions.

Would a service account with the right permissions not allow this to happen from Buildkite?

> There are no e2e tests blocking bad deployments from reaching production.

Do we have a tracking issue to re-enable these?

> There isn't a clear linkage between a sourcegraph/sourcegraph commit and the docker image tag that it corresponds to.

Do we have a tracking issue for this?
