### ISSUE TITLE
Make non-actionable errors to be warnings and stop sending to Sentry

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#17743]
Many errors in Sentry are in fact, warnings, especially when they're not actionable.

For example, we have 13k "connection reset by peer" over last 24 hours. These errors are not 100% useless but we would be better looking at our service health from monitoring instead of try to derive value out of individual error when by itself not actionable.

The principle I think we should follow is: If the error is not worth filing a GitHub issue, it should not be reported to Sentry.

**Comment by jhchabran** [comment]
Update: we have been using `warn` level as a way to signify that an error is transient, which enables to auto-close those errors. If that error is truly useless, the error reporting should be done at the info level in that case, so it remains within the logs. 

We're experimenting with sampling along the way, and could potentially throttle `warn` level errors further down to reduce the noise and avoid blowing away our quota.

**Comment by bobheadxi** [comment]
@jhchabran I think warn level errors are no longer sent to Sentry, right? We also have sampling in place for these events. We should formalize the sampling (move it into log config + site config) perhaps
