### ISSUE TITLE
Streaming search: unclear how to load more results

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#17773]
#### Steps to reproduce:

1. Run a search with many results, like [`config`](https://sourcegraph.com/search?q=config&patternType=literal)
2. Witness not all results are shown:

![image](https://user-images.githubusercontent.com/1741180/106153940-5f260480-617f-11eb-9b15-6a43025c57a4.png)

#### Expected behavior:

It is easy to understand how to get more results to display (eg. batched search had "show more", which re-ran the search with a higher `count`)

#### Actual behavior:

The UI gives not hint as to how to load more results (no "show more", "load more", if you don't know about the `count:` filter you are stuck.

**Comment by lguychard** [comment]
@rrhyne to think about whether a proposed query is sufficient, or whether we should show something at the bottom of the results list.

**Comment by rrhyne** [comment]
I think we need the message at the bottom. The tabs do not stay on the screen when scrolling to the bottom and the user would be left with no information about what has occurred. 

Here's the suggested correction:

![image](https://user-images.githubusercontent.com/539268/106206900-b7580900-6175-11eb-85cd-a6f17db38e3d.png)

Figma frame with redlines:

https://www.figma.com/file/IyiXZIbPHK447NCXov0AvK/13928-Streaming-search?node-id=1006%3A31

**Comment by keegancsmith** [comment]
I'm re-opening and I've reassigned to @limitedmage to implement your figma design. For now I think https://github.com/sourcegraph/sourcegraph/pull/17781 is good enough to enable for sourcegraph org. However, the bottom suggestion is needed general availability of streaming search.
