### ISSUE TITLE
Streaming: repositories count is misleading 

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#17780]
![image](https://user-images.githubusercontent.com/1741180/106166165-2b9da700-618c-11eb-8829-333474faa0eb.png)

This number is misleadingly displayed as the number of repositories that _were_ searched, but it is the total number of repositories that _can_ be searched.

It should probably only be sent up in the final progress update.

**Comment by lguychard** [comment]
cc @limitedmage @keegancsmith @stefanhengl

**Comment by limitedmage** [comment]
Does #17782 fix this or do we want to explore more on this UI?

**Comment by keegancsmith** [comment]
I think it fixes it for now. Marked the PR as fixing this issue.
