### ISSUE TITLE
WIP: Security 2021-01-25 Tracking issue

### ISSUE THREAD

**Issue by ElizabethStirling** [sourcegraph/sourcegraph#17786]
### Plan

The main goal of this iteration is to ensure a smooth transition of responsibilities as @chayim offboards. For the most part, we'll be tackling administrative, documentation, and planning work, rather than GitHub issues.
@ElizabethStirling is getting onboarded to hiring, and is working with the team to update our [security team goals](https://about.sourcegraph.com/handbook/engineering/security/goals). She is also working on handbook documentation for security processes and responsibilities, as well as grooming our upcoming work.
@andreeleuterio is working to get onboarded on #15452 so that he can hammer out secret management during @ElizabethStirling's upcoming medical leave. We're also working to redefine and rescope how we want to manage infrastructure secrets, since managing Vault isn't feasible within the time and team constraints.
@chayim is currently offboarding and working to help ensure a smooth transition period. 

### Availability

Duration: 2021-01-25 to 2021-02-05

If you have planned unavailability this iteration (e.g., vacation), you can note that here.

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- :shipit: Pull Request

**Comment by andreeleuterio** [comment]
**This week**
I worked mostly in setting up the secret mgmt work I'm tackling after my vacation. Paired with Elizabeth, Dax and Gonza in discussing the tradeoffs while considering our difficulties atm.  Also triaged a vulnerability and a WAF false positive.

**Next week**
I'll be on vacay 🎉🎉🎉💤💤💤

**Comment by ElizabethStirling** [comment]
**Last Week**
Last week was mainly spent giving @andreeleuterio context for secret management and working on hiring. Also resolved Elastic data retention issues, and got our updated goals merged in.

**This Week**
This week, I'll be resolving outstanding security asks and getting hiring to a point where we can move some candidates forward while I'm on leave.
