### ISSUE TITLE
Add GSM Terraform module to dogfood

### ISSUE THREAD

**Issue by ElizabethStirling** [sourcegraph/sourcegraph#17797]
We need to enable / configure GSM for our `sourcegraph-dogfood` project and deploy Berglas infrastructure to the GKE cluster. Note that this should undergo a lot of testing, since mutating webhooks are problematic if misconfigured.

**Dependencies:**
#17793 

**Useful Links:**
[Example Terraform module](https://github.com/sourcegraph/infrastructure/pull/2316)
[Using Terraform modules](https://www.terraform.io/docs/language/modules/syntax.html)

**Repository:**
[Infrastructure](https://github.com/sourcegraph/infrastructure/)

**Comment by andreeleuterio** [comment]
Closed with https://github.com/sourcegraph/infrastructure/pull/2395
