### ISSUE TITLE
No basic code intel

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#1779]
This is on a fresh Sourcegraph instance running latest `insiders` through Docker.
There's no basic code intel, no button either, despite the extension being active.

![image](https://user-images.githubusercontent.com/10532611/50997009-ca162b80-1523-11e9-9c19-88d1b2379b5b.png)

![image](https://user-images.githubusercontent.com/10532611/50997046-dbf7ce80-1523-11e9-96ed-849b1b5f2e81.png)

**Comment by sqs** [comment]
Ah...this is because all settings to enable it default to off.

![screenshot from 2019-01-10 23-09-23](https://user-images.githubusercontent.com/1976/51018538-d05cd580-152c-11e9-876c-8462d3e681bc.png)


Will fix.

**Comment by sqs** [comment]
Reopened for @felixfbecker 	to verify the fix.

**Comment by felixfbecker** [comment]
Confirmed on a fresh Docker instance
