### ISSUE TITLE
Update dogfood deployment configuration to consume GSM secrets

### ISSUE THREAD

**Issue by ElizabethStirling** [sourcegraph/sourcegraph#17802]
Consume the secrets we just added to the secret manager. We should inject the secrets into the k8s deployment as k8s secrets through a CD step, or through GitHub Actions. K8s env vars should be pulled from these secrets.

**Dependencies**
#17801

**Useful Links:**
[GitHub action GSM](https://github.com/google-github-actions/get-secretmanager-secrets)
[k8s env var from secret](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables)

**Repository:**
[deploy-sourcegraph-dogfood-k8s-2](https://github.com/sourcegraph/deploy-sourcegraph-dogfood-k8s-2)

**Comment by andreeleuterio** [comment]
Closed with https://github.com/sourcegraph/deploy-sourcegraph-dogfood-k8s-2/pull/1036
