### ISSUE TITLE
Add GSM & Berglas Terraform modules to dotcom

### ISSUE THREAD

**Issue by ElizabethStirling** [sourcegraph/sourcegraph#17803]
We need to enable / configure GSM for our `sourcegraph-dev` project (this is cloud).

**Dependencies:**
#17802

**Useful Links:**
[Example Terraform module](https://github.com/sourcegraph/infrastructure/pull/2316)
[Using Terraform modules](https://www.terraform.io/docs/language/modules/syntax.html)

**Repository:**
[Infrastructure](https://github.com/sourcegraph/infrastructure/)

**Comment by andreeleuterio** [comment]
Closed with https://github.com/sourcegraph/infrastructure/pull/2401. We're removing secrets per service so more PRs like 2401 are incoming.
