### ISSUE TITLE
Test plan for "Other" external services

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#1782]
This test plan is meant to cover the new functionality introduced in #1700.

Imagine you're completely new to Sourcegraph and you want to connect it with your Git repositories that live in your own personal Git server. As with #1702, this test plan is goal oriented so that we make sure the documentation is good.

1. Run a fresh Sourcegraph instance.
    ```
    rm -rf /tmp/sourcegraph
    docker pull sourcegraph/server:insiders
    docker run --publish 7080:7080 --publish 2633:2633 --rm \
        --volume /tmp/sourcegraph/config:/etc/sourcegraph \
        --volume /tmp/sourcegraph/data:/var/opt/sourcegraph \
        sourcegraph/server:insiders
    ```
2. Pretend like you are a new user setting up Sourcegraph for the first time.
    - Your goal is to add a repository to your Sourcegraph instance for which there's no direct external service integration. Start at https://docs.sourcegraph.com.
    - Here's a repo for you to try: https://try.gitea.io/gitea/git.git

**Comment by felixfbecker** [comment]
@tsenart I won't have time to go through this unfortunately.

**Comment by tsenart** [comment]
@felixfbecker: No problem!

**Comment by lguychard** [comment]
Filed & fixed #1808, LGTM otherwise

**Comment by dadlerj** [comment]
Filed https://github.com/sourcegraph/sourcegraph/issues/1837 (not urgent), worked great otherwise

**Comment by nicksnyder** [comment]
Works for me too! Closing since we have 3 testers.
