### ISSUE TITLE
https://docs.sourcegraph.com/ should default to the current version

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#1788]
- Visit https://docs.sourcegraph.com/
- Notice it automatically selects `3.0 (next)`, which is not desirable as that version is not yet released.
- Expected: We should redirect to the current version by default.

![image](https://user-images.githubusercontent.com/3173176/51006003-688f9600-14fe-11e9-87f4-ebefff723e14.png)

**Comment by sqs** [comment]
I think the right fix is to make version selection more apparent to users, and even more prominent on the homepage specifically. See https://github.com/sourcegraph/sourcegraph/issues/1706#issuecomment-453321304 for reasoning. This is especially acute on the homepage because of the docker run command. 

I will handle this and come up with a fix that is (hopefully) globally ideal.

**Comment by slimsag** [comment]
Sounds good

**Comment by sqs** [comment]
Reassigning to @ryan-blunden 	and to 3.2. @ryan-blunden 	and I think the right fix is NOT to default to the released version but instead just to make version selection more prominent.

**Comment by ryan-blunden** [comment]
This will be addressed once we merge @francisschmaltz PR #2564.

**Comment by ryan-blunden** [comment]
The above UI docs have now been delayed until 3.3 so the proposed change is below (using the existing template):

![Screen Shot 2019-03-19 at 12 30 45 PM](https://user-images.githubusercontent.com/133014/54636189-1d848880-4a43-11e9-9e26-e439caf230fb.png)

**Comment by slimsag** [comment]
We chatted over Slack and the above SGTM 👍 

There are some questions here like "When do we call out changes that occur in a certain version, and when do we remove those from our docs?" but I am 100% on board with trying this out and it's already a huge improvement over our current state I think.

**Comment by ryan-blunden** [comment]
Fixed by #2841

**Comment by ryan-blunden** [comment]
Visiting htdocs://docs.sourcegraph.com will default to showing the master branch
