### ISSUE TITLE
Repogroup page looks bad on mobile

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#17897]
- **Sourcegraph version:** Sourcegraph.com

Sides are cut off for repogroup page (eg https://sourcegraph.com/kubernetes) on small screens. Tested on iOS Safari.

![image](https://user-images.githubusercontent.com/206864/106523491-0cf22580-6496-11eb-96eb-4d671ae17882.png)

**Comment by camdencheek** [comment]
Closing as done. Repo groups no longer exist.

**Comment by fkling** [comment]
@camdencheek These pages still seem to exist though, only that they use `context:` now. And it still looks bad on mobile 😅 
Do we know what the plan for these kind of pages is?

**Comment by camdencheek** [comment]
Oh geez. I had no idea these were still a thing. Thanks for checking me!

cc @jdorfman do you happen to know anything about these community landing pages?

**Comment by jdorfman** [comment]
@kukicado can we check with Justin (the consultant) if these are worth keeping or not.

**Comment by camdencheek** [comment]
I mean, they're not really costing much in terms of ongoing effort. Mostly just to figure out whether we should spend any time fixing them.

**Comment by jdorfman** [comment]
@camdencheek will let you know as soon as I hear back
