### ISSUE TITLE
Docs search for docs.sourcegraph.com does not respect selected version

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#1789]
![screenflow](https://user-images.githubusercontent.com/133014/51006242-20b94080-14f7-11e9-816e-8cc400c7d047.gif)

## To re-produce

 - Go to  https://docs.sourcegraph.com
- Click on 3.0 (next)
- Search for TypeScript

## Expected result

 - Search results are for the 3.0 version.

## Actual result

- Search results are for the 2.13 version

**Comment by sqs** [comment]
Good catch.  Very strange, those pages should have meta noindex. Will investigate and fix.

**Comment by sqs** [comment]
Blocked on https://github.com/algolia/docsearch-configs/pull/699

**Comment by sqs** [comment]
I hope they merge that soon. Algolia is based in France, so they should be waking up soon.

**Comment by sqs** [comment]
I commented and just emailed them again.

**Comment by sqs** [comment]
I will temporarily replace this with a custom Google site search widget or link until  they merge https://github.com/algolia/docsearch-configs/pull/699.

**Comment by sqs** [comment]
My Algolia update didn't fix this problem. I am going to replace the search with a Google `site:docs.sourcegraph.com` search.

**Comment by sqs** [comment]
Reopen to verify fix
