### ISSUE TITLE
We don't higlight Julia files

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#17906]
Am embarrassed. Going to try do this soon.

**Comment by DaedalusG** [comment]
Hey @rvantonder I've just recently received an email to support from an open source developer that I think is related to this feature development:

As I code mostly in JuliaLang the thing I'm missing the most is an extension for it mostly for syntax highlighting but also for better search features.

Seems like the Julia sublime syntax highlighting file exists already but I'm not really understanding the other steps in [](https://github.com/sourcegraph/syntect_server#adding-languages)

Wondering if I should let them know this is a feature we're working on?

**Comment by slimsag** [comment]
Assuming no unexpected issues come up, this will go out in the 3.26 release in 2 days. It will land on Sourcegraph.com later today / tomorrow morning and you should see it working here (https://sourcegraph.com/github.com/JuliaLang/Example.jl/-/blob/src/Example.jl)

Associated PR: https://github.com/sourcegraph/sourcegraph/pull/19282

**Comment by rvantonder** [comment]
It works https://sourcegraph.com/github.com/JuliaLang/Example.jl/-/blob/src/Example.jl
