### ISSUE TITLE
Don't search files that don't exist on certain branches/commits on structural search path

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#17907]
Seeing the `git ls-tree ... file does not exist` first seen in https://github.com/sourcegraph/sourcegraph/pull/17726#issue-562835104, but now in the wild, with this query example [`repo:^github\.com/sourcegraph/sourcegraph$ Search(...)`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+Search%28...%29&patternType=structural).

Key thing to realize: when I add `@HEAD` to the repo, it disappears. This means some combination of the repo + branch/commit args that we send in searcher causes us to search a file we get from Zoekt and return results, but that result/file does not actually exist at that path for the branch/commit. So we should debug what we're sending/receiving when `@HEAD` added vs omitted.

**Comment by camdencheek** [comment]
I have a feeling this is because if the rev is unspecified, we pass Zoekt an empty string rather than "HEAD". Trying to construct a case that reproduces it locally
