### ISSUE TITLE
increasing limit twice leads to broken query with 2 count filters

### ISSUE THREAD

**Issue by stefanhengl** [sourcegraph/sourcegraph#17909]
I ran a query and increased the limit twice. It seems as if we don't respect existing count filters?
<img width="828" alt="image" src="https://user-images.githubusercontent.com/26413131/106568018-fb129000-6532-11eb-9d30-632663b7e646.png">

**Comment by lguychard** [comment]
I think this is a duplicate of https://github.com/sourcegraph/sourcegraph/issues/17789

**Comment by limitedmage** [comment]
Yes, dupe of #17789.
