### ISSUE TITLE
Extension detail page syntax highlighting for type diff are unreadable in light mode

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#1791]
![screen shot 2019-01-10 at 4 56 27 pm](https://user-images.githubusercontent.com/133014/51006567-b6a19b00-14f8-11e9-8438-f368c3445aa0.png)

**Comment by felixfbecker** [comment]
@vanesa can you take this?

**Comment by felixfbecker** [comment]
Ping @vanesa

**Comment by felixfbecker** [comment]
Fixed in 1c73e76fdc227c9caddedfc6cf0b22483d88e5d4
