### ISSUE TITLE
performance: Reduce the number of times we request a user from the database

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#17911]
Landing on `/search` hits the database 13 times simply to fetch the current user. 

Ideally we can fetch it early on and cache the result in the context.

**Comment by tsenart** [comment]
Would be good to see in a graph how much latency we'd shave off. Sounds like a good win.

**Comment by unknwon** [comment]
>Would be good to see in a graph how much latency we'd shave off

☝️

**Comment by ryanslade** [comment]
This is an ancient ticket and a lot of frontend work has happened since so closing it.
