### ISSUE TITLE
Fix pings for lsif WAUs

### ISSUE THREAD

**Issue by macraig** [sourcegraph/sourcegraph#17923]
We currently aren't getting code intelligence WAUs. 

<img width="1482" alt="Screenshot 2021-02-02 at 16 38 10" src="https://user-images.githubusercontent.com/1657213/106653045-99840d00-6596-11eb-97a7-8562c1feb4ab.png">

**Comment by efritz** [comment]
#17959 adds additional WAU values based on certain classes of events.
