### ISSUE TITLE
Markdown highlighting of diffs is dark and unreadable

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#1794]
- Visit https://sourcegraph.com/extensions/sourcegraph/lang-typescript

![image](https://user-images.githubusercontent.com/1387653/51010987-7e578800-150b-11e9-8a7c-09db1274d1cf.png)

This looks like an odd color to choose:

![image](https://user-images.githubusercontent.com/1387653/51011060-d1c9d600-150b-11e9-9578-c7897ce25982.png)

Is this a dark theme vs light theme problem?

**Comment by slimsag** [comment]
Looks like dup of #1791
