### ISSUE TITLE
Migrate other user-defined secrets to new encryption tooling.

### ISSUE THREAD

**Issue by arussellsaw** [sourcegraph/sourcegraph#17957]
in [RFC 310](https://docs.google.com/document/d/1ZlQzlTRtrQbx3yi2cqmSjyq3ddcp2eKnhqekLOvzm_w/edit#) we're tackling the highest priority user secrets to encrypt before GA, but we want to encrypt all zero-visibility data in the long run, this issue is to track the remaining secrets we'd like to redact:

*  TBD

**Comment by tsenart** [comment]
Things to consider in [our schema](https://github.com/sourcegraph/sourcegraph/blob/main/internal/database/schema.md).

- `external_service_repos.clone_url` — Ideally we would actually not have this column, and construct the clone URL in gitserver as needed?
- `user_credentials` — Relatively new table, used by campaigns. Definitely needs encrypting.
- `user_emails.verification_code` — Not sure if it's worth encrypting.
- `campaigns_XXX` — `spec` columns and `diff` columns? Maybe these would contain secrets. 
- `event_logs.argument` —  Worth looking if the `argument` column on sourcegraph.com would contain sensitive data, for instance, the ping event contains a license key. Does this need to be encrypted? We should discuss.
- `cm_queries.query` and `cm_trigger_jobs.query_string` — I suppose a common use case could be to setup code monitors for secrets. But would users search for specific secrets like this? Or for patterns instead?
- `critical_and_site_config` — Contains lots of secrets, as you can see here: https://sourcegraph.com/site-admin/configuration
- `global_state.mgmt_password_plaintext` — Looks funny, definitely worth investigating.
- `orgs.slack_webhook_url` — Would you consider this a secret?
- `product_licenses.license_key` — What do you think? An attacker could just impersonate a customer in pings and / or use the product for free?

**Comment by mrnugget** [comment]
(Ignore me, just leaving a comment so I get notified about this issue and the notifications make it through my email filters. Also: hi, good morning!)

**Comment by tsenart** [comment]
@mrnugget: You know there's a subscribe button?

**Comment by mrnugget** [comment]
I do know that, yes, but I'm subscribed to _all_ Sourcegraph issues by default and then filter out the relevant ones (mention me, I'm assigned, etc.) in email filters.
