### ISSUE TITLE
Symbols MVP design and testing

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#17966]
The symbols project improves the browsing of code from the perspective of API level documentation. 

This project will need light design work and testing to improve cohesion within the existing UI.

Notes:

https://docs.google.com/document/d/1YRxTxUJ-fLe6Dl8AipxBN52YDE27uJeLyczIZN3Kc7s/edit#

**Comment by AlicjaSuska** [comment]
@rrhyne could you provide more context on who from the design team should be assigned to this issue?

**Comment by rrhyne** [comment]
Closing as this has become a larger effort.
