### ISSUE TITLE
Fix the legend/graph division so large graph keys don't hide the graph

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#17969]
If you have a lot of things you're tracking on one graph, the key gets larger than the graph and it looks like there's no graph ([example](https://sourcegraph.slack.com/archives/C012V43N8E7/p1611785612023300?thread_ts=1611705216.016900&cid=C012V43N8E7) – in slack because private info). We should constrain/make scrollable the key -- whatever's functional and fast suffices for this fix at this stage.

**Comment by felixfbecker** [comment]
I'm not sure how we would solve this from a design perspective, with that many series in such a small chart. I'm thinking that for that many series you probably want to increase the size of the chart (#11713)

**Comment by Joelkw** [comment]
Sure, I'm okay tabling this if we're changing chart libraries anyway, but would note that we should test for many (10-15, perhaps) series on a single chart to see how we're handling things.

**Comment by felixfbecker** [comment]
(Note: This is still the case with the new chart library)

![image](https://user-images.githubusercontent.com/10532611/120024186-1c6e1f00-bfef-11eb-90b1-be8139d1633c.png)

**Comment by Joelkw** [comment]
I am closing this as it is now fixed via changes like https://github.com/sourcegraph/sourcegraph/pull/28270
