### ISSUE TITLE
Sort files by modification date

### ISSUE THREAD

**Issue by hellodword** [sourcegraph/sourcegraph#17970]
For example, 

the result of [`repo:^github\.com/torvalds/linux$ file:^Documentation/ABI/removed type:path .*`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/torvalds/linux%24+file:%5EDocumentation/ABI/removed+type:path+.*&patternType=regexp) ,

![image](https://user-images.githubusercontent.com/46193371/106838713-be33ce00-66d7-11eb-9367-3f06fcc6a47d.png)

is same as (or less than) github.

![image](https://user-images.githubusercontent.com/46193371/106838649-ac522b00-66d7-11eb-99da-b2b18fb74e75.png)

I found [`after` and `before` in the doc](https://docs.sourcegraph.com/code_search/reference/queries#keywords-diff-and-commit-searches-only), but I believe an option to sort the files by modification date and other rules would be nice :)

**Comment by Mattwmaster58** [comment]
Was this really completed? I can't find anything in the docs about sorting search results by file date. For my use case, I would like to see the first occurrence of a term in a list of commits. 

For a large search result, I guess I could do a binary search with the before and after filters to find the oldest commit :)
