### ISSUE TITLE
Handle repository redirects on GitHub

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#17978]
For example:
`https://sourcegraph.com/github.com/google/kythe`

`github.com/google/kythe` redirects to `github.com/kythe/kythe`

Since we don't have a repo named `github.com/google/kythe` we attempt to clone it on demand
but the name comes back as `github.com/kythe/kythe` which we **do** have cloned. This causes
us to abandon the clone process.

**Comment by tsenart** [comment]
For additional context, the syncer is supposed to handle repository renames, and we have lots of tests to make sure of that.
