### ISSUE TITLE
Update precise code intelligence documentation

### ISSUE THREAD

**Issue by macraig** [sourcegraph/sourcegraph#17988]
Doc link: https://docs.sourcegraph.com/code_intelligence/explanations/precise_code_intelligence

To dos:

- Update "Why are my results incorrect?" section  
- Update "Size of upload data" table
- Clarify version handling [#17621](https://github.com/sourcegraph/sourcegraph/issues/17621)

**Comment by scalabilitysolved** [comment]
This is now available and answered in our docs.
