### ISSUE TITLE
Elixir code intelligence

### ISSUE THREAD

**Issue by StephaneRob** [sourcegraph/sourcegraph#18]
Support Elixir on Sourcegraph

**Comment by chrismwendt** [comment]
Experimental Elixir support has been shipped in Sourcegraph 2.8! Check out the blog post https://about.sourcegraph.com/blog/code-intelligence-for-more-languages-and-lsp-language-server-protocol-support

![elixir](https://user-images.githubusercontent.com/1387653/40394853-2e53177c-5dda-11e8-8ad0-07788e02c966.gif)

Thanks go to [JakeBecker/elixir-ls](https://github.com/JakeBecker/elixir-ls) for providing prebuilt binaries) for providing the language server.

**Comment by chrismwendt** [comment]
Elixir code intelligence has been added in Sourcegraph 3.0 :tada:

https://about.sourcegraph.com/blog/sourcegraph-3.0#code-intelligence-for-all-languages

[Try it out](https://sourcegraph.com/github.com/phoenixframework/phoenix@e0be71759d83c15f6d1a852d9872d6de1ea0db24/-/blob/lib/mix/tasks/phx.gen.context.ex#L89:5) on Sourcegraph.com:

![image](https://user-images.githubusercontent.com/1387653/54006040-9c5af680-4110-11e9-81a1-271e4e8f0f1f.png)
