### ISSUE TITLE
Hover tooltips in browser extension are always empty

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#18018]
Something must have regressed - when I browse a PR like https://github.com/sourcegraph/sourcegraph/pull/17805, this is all the tooltip content I am seeing on any token:

![image](https://user-images.githubusercontent.com/10532611/107032189-b0ec1180-67b3-11eb-98e4-cf4bf9fab899.png)

But the same file@revision in Sourcegraph works fine:

![image](https://user-images.githubusercontent.com/10532611/107032311-e690fa80-67b3-11eb-854b-d778bca8f45b.png)

Given that, I would assume this is in the browser extension. But I am using latest version v20.11.17.1425, which as the version number shows wasn't updated since November 2020. From my memory this must be a recent regression though. Maybe something was changed in the codeintel extensions?

@sourcegraph/extensibility cc @sourcegraph/code-intel

**Comment by felixfbecker** [comment]
Okay a reload fixed it. Thisi s not the first time this has happened though, and apparently @eseliger has seen it too. It is persistent for every hover until the reload. Wondering what can cause this?

**Comment by efritz** [comment]
Is this consistently reproducible?

**Comment by eseliger** [comment]
It didn't happen to me again yet

**Comment by chrismwendt** [comment]
Can't repro and this hasn't reoccurred in a long time, reopen if it does.
