### ISSUE TITLE
Results "from 0 repositories" - erroneous label

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#18019]
When I just ran this search: https://sourcegraph.com/search?q=repo%3A^github\.com%2Fsourcegraph%2Fsourcegraph%24+foo

I saw "...from 0 repositories". I expect it to be "...from 1 repository".

![image](https://user-images.githubusercontent.com/1976/107055200-e37f1580-6785-11eb-9731-86ec715eb4f4.png)

cc @mike-r-mclaughlin

**Comment by lguychard** [comment]
I am seeing this as well. cc @keegancsmith @stefanhengl @limitedmage, not sure whether the problem is on the frontend or backend here.

**Comment by keegancsmith** [comment]
Seems to be a backend issue. Will tackle it asap.
