### ISSUE TITLE
Close icon is over text on hover when only "Find references" button is shown

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#1802]
- **Sourcegraph version:** sourcegraph.com and 3.0
- **Platform information:** Chrome

<img width="841" alt="screen shot 2019-01-10 at 10 40 08 pm" src="https://user-images.githubusercontent.com/133014/51017488-14e67200-1529-11e9-81ca-8d1a42ae05ce.png">

#### Steps to reproduce:

1. Enable basic code intel extension
2. Got to http://localhost:7080/github.com/sinatra/sinatra/-/blob/examples/chat.rb#L9:8&tab=references
3. Hover over the `Find references` button.

**Comment by sqs** [comment]
No good fix in the current UI. Cc @francisschmaltz

**Comment by sqs** [comment]
![ab274d79-1a54-4c90-b994-cdfc442b4bc3](https://user-images.githubusercontent.com/1976/51023633-33a23400-153c-11e9-9378-45e013e3500e.png)

**Comment by sqs** [comment]
Extra context ^^
