### ISSUE TITLE
Confusing result count on search results page

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#18028]
- **Sourcegraph version:** 86355_2021-02-05_95bce6c (86355_2021-02-05_95bce6c) [shown on [sourcegraph.com/site-admin/updates](https://sourcegraph.com/site-admin/updates)]

#### Description
The count shown on the results page is confusing especially when doing demos.  For example, if you search for a broad search term across all repositories, you will typically see a count that is smaller than a filtered search.

I understand that this is likely caused by counting the results until a page is ready to be returned to the user.  But, it creates some confusion when demonstrating in front of new prospects.

See a concrete example below:

#### Steps to reproduce:

1. Go to sourcegraph.com/search and search for ["auth provider"](https://sourcegraph.com/search?q=auth+provider&patternType=literal).  
    When I run this, it shows "76 results in 1.90s".  This number changes each time I run the search; but, I think that is fine.

![image](https://user-images.githubusercontent.com/23640224/107074308-2ce35b00-67ae-11eb-8051-5a472beedf36.png)

2. Next, [add a repo: parameter](https://sourcegraph.com/search?q=auth+provider+repo:github.com/sourcegraph/sourcegraph&patternType=literal) like `repo:github.com/sourcegraph/sourcegraph`
   This almost always results is a number larger than what is shown in the previous step.  For example, when I run this now, I see "103 results in 0.01s".  

![image](https://user-images.githubusercontent.com/23640224/107074277-1fc66c00-67ae-11eb-94ee-eeec6bcc9e76.png)

#### Expected behavior:

In an _ideal_ world, you'd see the exact count.  But, I don't think that's realistic (or fast :) ).  I guess I would at least expect the broader search to show a larger count (or maybe there's a better way to indicate this entirely?).

You can use Google as an example (though I recognize it's not entirely the same concept).  If you search on Google for "foo" it shows "About 101,000,000 results":

![image](https://user-images.githubusercontent.com/23640224/107076084-9d8b7700-67b0-11eb-9f22-d0b32f0f5b5c.png)

And, if you search on a specific site (say, sourcegraph.com) you see a smaller number:

![image](https://user-images.githubusercontent.com/23640224/107076184-b300a100-67b0-11eb-91d8-7e0be0f94a89.png)

#### Actual behavior:

When you execute a query for a broad search term, you see a count that is smaller than a more narrow search result.

**Comment by mike-r-mclaughlin** [comment]
Another example of this (not sure if this belongs in a new ticket but it seems related to this so going to add it here for now):
In the broad example shown above, you see "some results excluded".  If you expand that, it says "result limit hit".  If I choose to increase the limit to 1000 and search again, I now see "1.8k+ results in 2.80s".  
This is confusing because it said a specific number on the previous result ("76 results") and now suddenly there are 1.8k+ results.  

![image](https://user-images.githubusercontent.com/23640224/107076871-b0eb1200-67b1-11eb-80af-99d246afdc0a.png)

**Comment by keegancsmith** [comment]
@mike-r-mclaughlin thanks for this great feedback. If you try streaming on sourcegraph.com now, how is the experience? We have done several tweaks to how we display result counts / etc. Not perfect yet, but would love to hear how you think it can be better / things that are still confusing / etc.

**Comment by malomarrec** [comment]
This is something that has shown up in UX interviews of .com users. @mike-r-mclaughlin would love to get your thoughts on this after @keegancsmith 's update!

**Comment by camdencheek** [comment]
Closing since, with streaming search and many changes in how we do result counts, this seems to be no longer relevant. Feel free to re-open if I'm off base.
