### ISSUE TITLE
Filter Site-admin > Users list by whether they are admins or not

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#18025]
We recently had a teammate depart, and when I went to disable their admin access on Sourcegraph.com, I faced an interesting challenge. [Our user search only works for usernames (not emails)](https://github.com/sourcegraph/sourcegraph/issues/15461), but even if it did, I'd have to guess whether the user in question's account was on their company email or a personal one. 

It'd be great, for administrative security reasons, to be able to filter and see only admins on this page so they can be cleaned up if necessary.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam-and-admin-experience - the "team/iam-admin-experience" label was applied to this issue.

**Comment by jasongornall** [comment]
oops sorry this gibberish is from me ^ can ignore

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.

**Comment by kopancek** [comment]
Closing, as this has been magically done by someone else already 🙇
