### ISSUE TITLE
Upgrade to Go 1.15

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#18026]
Related: https://github.com/sourcegraph/sourcegraph/pull/13433
Current PR: https://github.com/sourcegraph/sourcegraph/pull/18024

**Comment by daxmc99** [comment]
TODO (from https://github.com/sourcegraph/sourcegraph/pull/13433#issuecomment-684082487):

- [ ] A warning at the top of the CHANGELOG section
- [ ] A warning in our blog post
- [ ] A note in the marketing email that gets sent out
- [ ] An entry on docs.sourcegraph.com/admin/install/kubernetes/update
- [ ] An entry on docs.sourcegraph.com/admin/updates/docker_compose
- [ ] An entry on docs.sourcegraph.com/admin/updates/pure_docker
- [ ] Ask in #marketing or #product for how to handle points 2 and 3 above.

**Comment by tsenart** [comment]
> Go 1.16 is not yet released. These are work-in-progress release notes. Go 1.16 is expected to be released in February 2021.

I guess upgrading to 1.16 would then be an easier process so we can get to 1.15 in between?

**Comment by daxmc99** [comment]
Upgrading to 1.16 should be easier after this. I haven't seen a similar issue to the TLS cert issue in Go 1.16
