### ISSUE TITLE
Integrate a site-admin feedback form/widget.

### ISSUE THREAD

**Issue by pecigonzalo** [sourcegraph/sourcegraph#18031]
We could integrate a widget or clickable form in the site-admin page, only seen by site-admins.

The current feedback collection targets a lot more users of Sourcegraph, but contextually it does not reference providing feedback about the site-admin, deployment, monitoring, upgrading, etc experience of thoses tasked with supporting the deployment.

https://github.com/sourcegraph/sourcegraph/issues/17645

**Comment by ggilmore** [comment]
@pecigonzalo I am worried that we won't get timely feedback on this if it's in app. The admins won't see this until they upgrade, so it might be months until we get responses. What do you think about creating an email campaign for this instead? We already have all the emails we need from their initial signups.

**Comment by pecigonzalo** [comment]
@ggilmore I would check with CE. I worry we end up spamming them with email, so this was a "passive" way of collecting feedback. 

My initial thoughts were to show it like the one in the linked PR but only for site-admins when in the site-admin panel, do you think that would not work?
Maybe periodic email campains are OK, but I think its a CE call as they can ensure we are not bombarding them with email or might have some "policies" around doing this or not.

**Comment by ggilmore** [comment]
@pecigonzalo 

I'll check with CE. 

If possible, I think email is a faster way to get initial feedback. 

If CE is okay with the initial email but not follow ups, then I think it makes sense to revisit an in-app solution. We will still have the initial round of feedback from the emails.  I think it makes sense to wait for https://github.com/sourcegraph/sourcegraph/issues/17645 to be implemented (it's already scheduled) so that we can borrow its implementation instead of duplicating it (I also wonder if having the toast look similar to the existing normal user feedback toast is actually something we want - a design question).

**Comment by pecigonzalo** [comment]
@ggilmore Yeah, the idea was to reuse the implementation of that and work with that team to implement or reuse. My bad for not putting that in the body.

Regarding the email, keep in mind we have sent one already in [slack](https://sourcegraph.slack.com/archives/CU93UDUBV/p1612802748157300?thread_ts=1612391214.116800&cid=CU93UDUBV) - [doc](https://docs.google.com/document/d/1jHbIRV_F-wdlbL5RhT_BXppe5IeFT8IKvEFhu7J6wGk/edit#).

**Comment by ggilmore** [comment]
@pecigonzalo 

I guess that I misunderstood that this was for passive feedback and not specific questions like our survey idea. If that's the case, then I am not sure that an email asking for general feedback is the best medium for that. 

If that's the case, it seems like we should wait for #17645 to be implemented. What do you think about dropping a note on that issue that we're interested in re-using their implementation for this new use case once it's done, and that we're happy to chat if they have any questions. 

Once that's done, I don't think there are new things we can do for this issue in particular until #17645 lands. Do you agree?

**Comment by pecigonzalo** [comment]
> I guess that I misunderstood that this was for passive feedback and not specific questions like our survey idea. If that's the case, then I am not sure that an email asking for general feedback is the best medium for that.

Sorry for the confusion. 
- This issue was to gather passive feedback (customers randomly provide feedback through a form like NPM). 
- My link to the slack thread and doc was just to highlight that we were already in the process of actively reaching out to them via email.

> If that's the case, it seems like we should wait for #17645 to be implemented. What do you think about dropping a note on that issue saying that we're interested in re-using their implementation for this new use-case once it's done, and that we're happy to chat if they have any questions.

SGTM.

> Once that's done, I don't think there are new things we can do for this issue in particular until #17645 lands. Do you agree?

I would draft the general idea and check with Product (maybe Quinn Keast can help there) how does this sound to them. Maybe there are concerns with the approach and we have to figure out another way or reconsider this task.

WDYT?

**Comment by ebrodymoore** [comment]
(Background: Gonza and I were chatting about this earlier) 

You could definitely reuse their widget, we'd just need to make sure there was an identifier that distinguished a user's feedback from an admin's. My initial take is the URL that's passed through would suffice if the survey was only visible on `https://sourcegraph.com/site-admin/remaining_path`, but not sure if this will be the case. Let me know if not and we can explore options.

I also told @quinnkeast that distribution was planning on doing this and he made the good point that depending on what information you want to get, it could be helpful to show the form at certain times (such as in the workflow of upgrading if you're looking for upgrade feedback). Eventually may be worth a quick brainstorm with him if you want to get more targeted since he drove this whole feedback effort from the product side!

**Comment by ggilmore** [comment]
Thanks for following up @ebrodymoore! That all sounds workable - Tomorrow I'll make plans to sync with @quinnkeast

**Comment by ggilmore** [comment]
Notes on meeting with @quinnkeast 👍 

---

- Quinn asked about for more information about when we were imagining that the feedback form would appear
    - I responded (as a first stab it), that the following are the "contextually relevant" places that I could think of to show that form :
        - `/site-admin` subpages: the admin is doing maintenance related tasks
        - perhaps when we have detected like they have done an action related to maintenance (like upgrades - we can detect that the `site-version` field has changed in the DB recently)
- Quinn quickly demo'd the initial designs for context:
    - as opposed to NPS surveys that prompt the user randomly (every 30 days), the proposed user feedback form is designed to be always present so that the user can trigger feedback themselves and capture user sentiment within the moment
        - I asked (not to be provocative, but just for context), is there a thought that trigging the flow themselves might lead to only capturing the "extremes" of their experience?
            - Yes, but this is better / would provide more feedback than capturing every 30 days through NPS surveys
- Quinn asked, if there was a "flow" for site-admin tasks (similar to a sign up / sign in flow)?
    - I said: not one that's in app. Often, the site-admin would have just run a shell script or something to upgrade the versions. However, there isn't an in-app "flow" that the admin enters after this process is completed (e.g. a "What's New" flow akin to a sign-up flow that provides a natural feedback touch point for upgrades)
    - The design of this existing feedback form might be not be contextual for the user
- Next steps
    - For right now, we would recommend just telling the site admins to also provide maintenance feedback in the same "user" feedback form. We will not be adding special handling / highlight the feedback form for site admins until we know what the most effective way of doing that would be.
    - Within the next day or so, ask CE if there is a customer that Quinn Keast could shadow during the upgrade process
        - We should also try to see if we can get customers across various deployment methods (I suspect the sentiment gets a lot more negative as you go from single-server→docker-compose→Kubernetes)
        - This is will give us a better understanding of when it might be relevant to bring up the feedback form.

**Comment by ebrodymoore** [comment]
[Here's the form](https://share.hsforms.com/1aGeG7ALQQEGO6zyfauIiCA1n7ku)! @quinnkeast should we get marketing involved in this? I think they came in at the later stage to do some branding and host it on our domain, but I wasn't involved in that. You can [edit the form here](https://app.hubspot.com/forms/2762526/editor/686786ec-02d0-4041-8eeb-3c9f6ae22208/edit/form).
