### ISSUE TITLE
Create reports on usage of our admin docs from the static site

### ISSUE THREAD

**Issue by pecigonzalo** [sourcegraph/sourcegraph#18032]
Are there metrics we can use from our static site?
- Admins using alert docs
- Resource estimator usage
- etc

**Comment by ebrodymoore** [comment]
FYI @uwedeportivo I talked to Gonza this morning and can look into Google Analytics on our docs page and come up with a report. It should be straightforward

**Comment by aileenrose** [comment]
Google Analytics is tracking docs in the same profile as our other sites.  See this report:
https://analytics.google.com/analytics/web/#/report/content-pages/a40540747w150533180p15550805[…]22analytics.hostname%22,%22PT%22,%22docs%22,0%5D%5D

**Comment by ebrodymoore** [comment]
Thanks Aileen! @pecigonzalo @uwedeportivo could you send me the docs pages you're curious about tracking? I'll set up a report. There are a few different alerting pages

**Comment by uwedeportivo** [comment]
Could we start with these if it's not too much trouble:

Alerting:

- https://docs.sourcegraph.com/admin/observability/alerting
- https://docs.sourcegraph.com/admin/observability/alerting_custom_consumption
- https://docs.sourcegraph.com/admin/observability/dashboards
- https://docs.sourcegraph.com/admin/observability/alert_solutions

Sizing an initial cluster:

- https://docs.sourcegraph.com/admin/install/resource_estimator
- https://docs.sourcegraph.com/admin/install/kubernetes/scale

We might ask for more :-).

**Comment by pecigonzalo** [comment]
I was just updating some docs and thought it would be good to get a sense for the `docker-compose/aws.md` and the likes.

**Comment by ebrodymoore** [comment]
[Here's the report](https://analytics.google.com/analytics/web/#/savedreport/0Oe7pXCaSO6YpwsSJyprww/a40540747w150533180p155508056/_u.dateOption=last30days&_r.dsa=1&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.hostname&explorer-table.advFilter=%5B%5B0,%22analytics.hostname%22,%22BW%22,%22docs%22,0%5D,%5B0,%22analytics.pagePath%22,%22RE%22,%22(admin~2Fobservability~2Falerting%7Cadmin~2Fobservability~2Falerting_custom_consumption%7Cadmin~2Fobservability~2Fdashboards%7Cadmin~2Fobservability~2Falert_solutions%7Cinstall~2Fresource_estimator%7Cinstall~2Fkubernetes~2Fscale)%22,0%5D%5D&explorer-segmentExplorer.segmentId=analytics.pagePath&_.advseg=&_.useg=&_.sectionId=&explorer-table-dataTable.sortColumnName=analytics.uniquePageviews&explorer-table-dataTable.sortDescending=true/) (and I added you both to Google Analytics). Let me know any changes you'd like, hope this is helpful!

**Comment by pecigonzalo** [comment]
I got a "Thre  request page

**Comment by pecigonzalo** [comment]
🤔 I got: 

> Failed to load the shortcut.
> The requested page was not found on this server.

Any ideas? I've disabled all my ad-blocking stuff.

**Comment by ebrodymoore** [comment]
Report is [here](https://drive.google.com/file/d/1NLfbrJ3wq7ISj0UjltT8tiohrkYqV-3U/view?usp=sharing), and it's also set up to be emailed to @pecigonzalo weekly for 4 weeks. We'll re-evaluate how useful it is soon.
