### ISSUE TITLE
Update gitserver to stop passing the token in clone_url.

### ISSUE THREAD

**Issue by arussellsaw** [sourcegraph/sourcegraph#18057]
ref [RFC 310](https://docs.google.com/document/d/1ZlQzlTRtrQbx3yi2cqmSjyq3ddcp2eKnhqekLOvzm_w/edit#)

Once we've finished #18054 we want to stop passing the auth token to gisterver in the clone url, this will mean that gitserver will start hitting the credential helper, and no longer store the token on disk.

**Comment by tsenart** [comment]
We should make sure that it actually update the remotes in the `.git` directory and they no longer have the tokens there.
