### ISSUE TITLE
Create a git credential helper implementation for gitserver clone credentials

### ISSUE THREAD

**Issue by arussellsaw** [sourcegraph/sourcegraph#18054]
ref [RFC 310](https://docs.google.com/document/d/1ZlQzlTRtrQbx3yi2cqmSjyq3ddcp2eKnhqekLOvzm_w/edit#)

from the rfc:
>## 🤖  Gitserver credentials
>Another place where external service tokens live in plaintext is on disk in the git repos managed by gitserver, this is because we pass a clone url containing the token in order to authorise the clone, the problem is that git will store this token on disk for future clones. In order to mitigate this we will plug into git’s credential helper tooling, providing a binary that git will call to authenticate the repo, you can read more [here](https://git-scm.com/docs/gitcredentials). This binary will read the encrypted access token from metadata we store in the git config of the repo and decrypt it using the KMS api, but via the abstracted Key interface described below. 

This will involve building a binary we can ship with gitserver and add to git config, being called by git commands to retrieve credentials when cloning. We will likely also need to embed the encrypted token inside git config, as we do this already with other values. This value can then be read by the helper & decrypted via the Key interface.

💡 it might prove difficult to provide config to this binary easily, so it might be better to have the binary be a client that RPCs back to the local gitserver to do the actual decryption, as we'll need to configure the Key for each deployment

@unknwon has the most context on this problem

**Comment by tsenart** [comment]
>  it might prove difficult to provide config to this binary easily, so it might be better to have the binary be a client that RPCs back to the local gitserver to do the actual decryption, as we'll need to configure the Key for each deployment

Or add a subcommand to gitserver like `gitserver credentials ...`

**Comment by arussellsaw** [comment]
testing

**Comment by tsenart** [comment]
While we removed credentials from disk, we learned new information that some customers forward the output of `ps` to security monitoring infrastructure, and they don't want secrets to be included in these command lines. Context: https://sourcegraph.slack.com/archives/C1JH2BEHZ/p1616694530064500

So implementing a git credential helper makes sense, given this additional feedback.

**Comment by eseliger** [comment]
We fixed this another way by passing the credentials to Gitserver via env vars that solved this.
