### ISSUE TITLE
[Cloud] user notifications UI

### ISSUE THREAD

**Issue by artemruts** [sourcegraph/sourcegraph#18066]
### Description

Part of #16510

Implement required UI changes to support _user only_ (org will be in a separate issue ) notifications.
[Figma designs](https://www.figma.com/file/0567AnXEpQTzQXkgs7AzEh/%2316510-%E2%80%93-WIP-%E2%80%93-Status-notification-system?node-id=466%3A279).

### Acceptance criteria

- [ ] add new UI elements/components
- [ ] integrate with the new notifications GraphQL endpoint (TODO: link issue from @ryanslade)
- [ ] QA
- [ ] deploy under the [Cloud GA user tag](https://github.com/sourcegraph/sourcegraph/blob/main/client/web/src/user/settings/cloud-ga.ts#L9-L13)

**Comment by ryanslade** [comment]
@artemruts I added https://github.com/sourcegraph/sourcegraph/issues/18543

Still need to decide on the implementation
