### ISSUE TITLE
search: streaming webapp freezes up often

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#18060]
This is more than likely related to the fact I have increased the default limits from 30 to 500 (see #17777). It seems the larger number of results streaming in can often freeze up the webapp. I am finding this pretty easy to reproduce on sourcegraph.com and have to close my browser tab in safari. This feels like a "release blocker". IE I wouldn't be comfortable turning this on for cloud until we have an idea what is going on here.

**Comment by rvantonder** [comment]
The 500 limit on `type:diff` gives a time to first result of 5 seconds (long) and takes longer to finish (11 seconds). Time to first result of `count:30` is very fast. Is this a bug?

[Query](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+Search+++type:diff&patternType=literal)

**Comment by keegancsmith** [comment]
> The 500 limit on `type:diff` gives a time to first result of 5 seconds (long) and takes longer to finish (11 seconds). Time to first result of `count:30` is very fast. Is this a bug?
> 
> [Query](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+Search+++type:diff&patternType=literal)

@rvantonder no that is unexpected. Filed in a separate issue to follow up on. https://github.com/sourcegraph/sourcegraph/issues/18142

**Comment by limitedmage** [comment]
Still experiencing freezing after the first round of perf improvements.

**Comment by limitedmage** [comment]
@keegancsmith @rvantonder Can you verify that this is fixes after the frontend perf fixes and #18517?

**Comment by keegancsmith** [comment]
@limitedmage from some quick tests this is perfect! The interface seems snappier than I remember it ever being, let alone just with streaming :D Great work.
