### ISSUE TITLE
search: count strictly limits ResultCount

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#18076]
Fluctuating result counts reduce confidence in our search system. It also leads to user confusion. Currently we have limiting per backend. Once a backend has found count results, it will stop. So if text search backend finds 500 results, we cancel it. However, we still run other backends (repository and path) and wait for them. We then return all those results to user leading to higher ResultCounts shown.

ResultCount is a little different between search types, but usually represents the number of "highlights" we would show (ie number of line fragments, offset/ranges, etc). However, the limit is applied to the number of documents with matches, no the ResultCount. So additionally we should make count: based on ResultCount instead.

This is "breaking change" even though it is an improvement. So we will mostly limit this change to only happen with streaming mode.

This issue came out after discussions with @rrhyne. See context in [Search result counts user study](https://docs.google.com/document/d/195ndinssIvxpTvangN1blGalN-0etnOap32vtP3YTRc/edit)

**Comment by keegancsmith** [comment]
@rrhyne I'm gonna send out a bunch of PRs that implement the below screenshots. We need to improve how it is displayed in the UI, but this is a clear improvement so I am keen to land them. Here I am doing a search which has more than 500 results (the default limit):

![image](https://user-images.githubusercontent.com/187831/107279295-86be7c00-6a5f-11eb-858e-8652976730d4.png)

Notice our result count stops at 500 and we have "some results excluded":

![image](https://user-images.githubusercontent.com/187831/107279355-9d64d300-6a5f-11eb-84ff-6c4bae9a1cb1.png)

Now when I do the search I find all of the results:

![image](https://user-images.githubusercontent.com/187831/107279400-ab1a5880-6a5f-11eb-868c-aa4d2bc0d16e.png)

Tell me what you think, but things that need improvement:
- We should probably display the `500` as `500+` since we hit the limit.
- The `1.1k+` is confusing since we found all the results. We have the `+` there as part of the code which summarizes the number. Maybe we should show an exact number here?
- Relatedly the absence of "some results excluded" isn't that clear for me to know we have found everything.

cc @limitedmage

**Comment by rrhyne** [comment]
I don't think we should display the + next to 500. Now that we are returning exactly 500 results, that number is more accurate. The 'some results excluded' notice says 'there are more results to be found' much more clearly IMO.

Showing only 1.1k would be fine with me. I believe the user would understand that number as simplified (from say 1,112) for display. Once we have the result count dropdown we can show exact numbers there.

**Comment by stefanhengl** [comment]
> I don't think we should display the + next to 500. Now that we are returning exactly 500 results

Currently, we might return more than 500 but we stop counting at 500. IMO the reported numbers should match what the user sees. Sure, the numbers fluctuate, but maybe a tooltip would go a long way in explaining to the user why they fluctuate.

**Comment by keegancsmith** [comment]
> > I don't think we should display the + next to 500. Now that we are returning exactly 500 results
> 
> Currently, we might return more than 500 but we stop counting at 500. IMO the reported numbers should match what the user sees. Sure, the numbers fluctuate, but maybe a tooltip would go a long way in explaining to the user why they fluctuate.

We can update the limiting code to limit the results sent down. Right now the `+` is always added as a suffix by the UI. See https://github.com/sourcegraph/sourcegraph/pull/18093

**Comment by lguychard** [comment]
Related: https://github.com/sourcegraph/sourcegraph/issues/18028#issuecomment-774224963

**Comment by keegancsmith** [comment]
Two things left in this experiment after playing with it on sourcegraph.com:

- If the query doesn't contain `count:` we should send down as many results as we find within the default limit. In fact, we should probably have much higher time limits in the default case.
- If we say we found 500 results, we should only send down 500 results. Right now the count is different to the results actually sent (which can be more).

From playing with streaming search on sourcegraph.com, what do others think?

**Comment by rrhyne** [comment]
Currently, the results reads '500 results', indicating this is the total number of results for all queries. 

If we found 501 results, can we add a plus symbol to the results count in the UI? Should we also signify that in the API?

**Comment by keegancsmith** [comment]
@rrhyne we have the "some results excluded" dialog. But I agree, it doesn't seem very clear. I agree adding the `+` makes sense here. Will do that.

**Comment by keegancsmith** [comment]
> If the query doesn't contain count: we should send down as many results as we find within the default limit. In fact, we should probably have much higher time limits in the default case.

I'm not sure what we should do here. Should we have the fluctuating result count numbers? IE if there is no count is it alright that each time you run the search you will get a different number (with limit hit)?

**Comment by rrhyne** [comment]
Setting a limit of 500 results is a more consistent way of limiting broad queries. That said, constantly returning only 500 results without count explicitly in the query feels incorrect to me. 

Users start to lose trust and get confused when counts fluctuate upward after they apply filters to narrow results. Eg: 'auth provider' returns 1.1k results in 60s, then 'auth provider lang:go' returns 1.5k results. Do you feel that the new match limits will reduce occurrences of this behavior?

If it does not significantly, then I believe the proposed match limit dialog would be required to revert back to time-bound queries. With that in place, we can explain that the search was broad to return more results and how to narrow it to return more exact results. 

WDYT? 

I'll speak with @ebrodymoore about logging result counts on .com so we can determine how often this happens.

**Comment by keegancsmith** [comment]
Yes, without putting in a hard limit and sticking to it result counts will fluctuate exactly as much as it did before (for large result sets). That is why I am thinking it is better to stick to a hard limit. Maybe instead of 500 we should use a different number for a default?

**Comment by rrhyne** [comment]
Ok, let's stick with the hard limit for now. I would very much like to collect data on result counts to understand how often this occurs.

**Comment by rrhyne** [comment]
Sorry meant to add that with data on result counts we can determine how often the 500 result limit is reached.
