### ISSUE TITLE
[Bug] Repos failing to index 

### ISSUE THREAD

**Issue by justdueck** [sourcegraph/sourcegraph#18072]
**Filing issue on behalf of prospect**

Sourcegraph Version: 3.24.1
Deployment: Docker-compose 

#### Steps to reproduce:

1. Use src-cli to expose 331 local repos to Sourcegraph

#### Expected behavior:
All repos clone and index properly 

#### Actual behavior:
Most repos (291) cloned and indexed properly however 40 failed with `fatal: The remote end hung up unexpectedly` in the server logs

The user notes that in their testing that if they removed the original .git folder and initialized a fresh git repo, then Sourcegraph would then successfully clone the repo. 

From the user: 

> My hypothesis is that it has something to do with large objects in the repo’s git history. It would explain the “fatal: The remote end hung up unexpectedly” error as the common solution I found is to increase the `http.postBuffer`. 
> 
> I tried setting that parameter for sourcegraph/server and "sourcegraph/src-cli" docker containers in various manners, though it did not seem to help the issue. Additionally, I increased the logging level for Git on those docker containers and did not see anything noteworthy.

They have also created a GitLab repo with additional info and steps they tried here: https://gitlab.com/jbeckman/sourcegraph-debug

Jira [issue](https://sourcegraph.atlassian.net/browse/SG-536)
Looker [instance](https://sourcegraph.looker.com/dashboards/94?Unique%20Server%20ID=rajonbeckman@gmail.com&Site%20ID=&Salesforce%20Unique%20ID=&filter_config=%7B%22Unique%20Server%20ID%22:%5B%7B%22type%22:%22%3D%22,%22values%22:%5B%7B%22constant%22:%22rajonbeckman@gmail.com%22%7D,%7B%7D%5D,%22id%22:6%7D%5D,%22Site%20ID%22:%5B%7B%22type%22:%22%3D%22,%22values%22:%5B%7B%22constant%22:%22%22%7D,%7B%7D%5D,%22id%22:7%7D%5D,%22Salesforce%20Unique%20ID%22:%5B%7B%22type%22:%22%3D%22,%22values%22:%5B%7B%22constant%22:%22%22%7D,%7B%7D%5D,%22id%22:8%7D%5D%7D)

**Comment by slimsag** [comment]
Adding two relevant teams, feel free to remove whichever is not related.

**Comment by tsenart** [comment]
@justdueck: Since this seems to be a customer issue, please close and re-open in our customers repo so we are free to discuss details specific to the customer. Once you that, please share a message in #core-application.

**Comment by justdueck** [comment]
Created new customer issue here https://github.com/sourcegraph/customer/issues/201

Closing this one
