### ISSUE TITLE
When creating an external service with kind="other", JSON comments refer to phabricatorconnectionobject

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#1808]
- go to https://YOUR-INSTANCE/site-admin/external-services/add?kind=other
- witness JSON comments point to #phabricatorconnection-object

![image](https://user-images.githubusercontent.com/1741180/51043582-50338000-15bf-11e9-985b-115e225b3c33.png)

_expected_: JSON comments point to #otherexternalserviceconnection-object

**Comment by tsenart** [comment]
Thanks!
