### ISSUE TITLE
Add syntax highlighting and autocomplete for `context:` filter in MonacoQueryEditor

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#18085]
I'll be adding very basic syntax highlighting to work on #18086 but we probably want better syntax highlighting and autocomplete.

**Comment by limitedmage** [comment]
@novoselrok  are you planning on adding this? If not, @rvantonder do you have bandwidth to help with this?

**Comment by rvantonder** [comment]
Syntax highlighting done in https://github.com/sourcegraph/sourcegraph/issues/16362, https://github.com/sourcegraph/sourcegraph/pull/17947 no? Autocomplete is probably on @novoselrok's radar, it's tracked in https://github.com/sourcegraph/sourcegraph/issues/16363, no? (I don't personally have any intention to context switch to `context` work).

**Comment by limitedmage** [comment]
Thanks @rvantonder ! I'll close this in favor of #16363 :)

**Comment by rvantonder** [comment]
Sorry, I linked the wrong PR for the highlighting, it's not merged yet: https://github.com/sourcegraph/sourcegraph/pull/18013. The highlighting is not behind a feature flag for now, and to be honest, it's fine this way, it's not leaving a big footprint that we need to feature flag IMO.

**Comment by limitedmage** [comment]
Oh that's even better, thanks! I agree it doesn't have to be behind the feature flag.
