### ISSUE TITLE
What are the semantics of AUTHORS.txt?

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#181]
When are new contributors supposed to get added to AUTHORS.txt?

Does our CI check require that each new author add themselves on their first contribution?

**Comment by sqs** [comment]
Yeah, git shortlog -ns and a mailmap seems sufficient

**Comment by slimsag** [comment]
Go has this file for copyright/legal purposes. It is worth noting that in Go 1.11 onwards they do not require anyone be in the file, they just let anyone add themselves _if they desire to_. I think that is the right approach. https://go-review.googlesource.com/c/go/+/128877

**Comment by nicksnyder** [comment]
I guess if Go is moving in the direction of "it doesn't matter" then I think we should start that way and not bother.

Anyone can see contributors by looking at the source of true for contributions directly (commits, PRs, issues, etc)

**Comment by slimsag** [comment]
Agree

**Comment by felixfbecker** [comment]
I don't see a point in the file if it can be inferred from version control and needs to be kept in sync manually.
