### ISSUE TITLE
Investigate indexed repos that are not cloned

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#18102]
On Cloud we have ~1k repos that are in our `default_repos` table but are not cloned:

```
select count(*) from default_repos
JOIN repo r ON r.id = default_repos.repo_id
where not r.cloned;
```

We need to investigate why they are never cloned.

**Comment by tsenart** [comment]
I checked a few of those, and they all 404 on the code host.

**Comment by ryanslade** [comment]
Cool, so maybe we just need to do some cleanup in that table

**Comment by ryanslade** [comment]
Total uncloned: 970

I intend to delete the following from our `default_repos` table:
* Marked as deleted in our repo table: 61
* 404 from code host: 875
* 415 from code host (unavailable for legal reasons): 31

That only leaves 3 "valid" repos:

* https://github.com/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    * Appears to be a repo simply full of programs that output `e`. I think we can safely delete it
* https://github.com/jjqqkk/chromium
    * Disabled by GitHub due to trademark policy. Safe to delete
* https://github.com/jlippold/tweakCompatible
   * Looks ok, need to investigate further.

**Comment by ryanslade** [comment]
https://github.com/jlippold/tweakCompatible looks like a very big repo, 2.3GB. @keegancsmith do we have a size limit?

**Comment by keegancsmith** [comment]
> https://github.com/jlippold/tweakCompatible looks like a very big repo, 2.3GB. @keegancsmith do we have a size limit?

We don't have a size limit, this should clone. What might be kicking in is a timeout on clone (1 hour?). There are larger repos in our corpus. Generally these large repos on github are hosting very large assets that aren't _that_ interesting to sourcegraph. So I wouldn't bend over backwards to get it to clone.
