### ISSUE TITLE
Clean up code intels grafana dashboards

### ISSUE THREAD

**Issue by macraig** [sourcegraph/sourcegraph#18124]
We have some unused panels that could be removed and metrics that seem to be deprecated.

**Comment by macraig** [comment]
@Strum355 can you add links to the dashboards you were mentioning?

**Comment by Strum355** [comment]
**Precise Code Intel Worker**
[Job errors every 5m](https://sourcegraph.com/-/debug/grafana/d/precise-code-intel-worker/precise-code-intel-worker?orgId=1&from=1613003485847&to=1613046685847&var-alert_level=$__all&viewPanel=100002)
[Database store errors every 5m](https://sourcegraph.com/-/debug/grafana/d/precise-code-intel-worker/precise-code-intel-worker?orgId=1&from=1613003503077&to=1613046703078&var-alert_level=$__all&viewPanel=100201)
[LSIF store errors every 5m](https://sourcegraph.com/-/debug/grafana/d/precise-code-intel-worker/precise-code-intel-worker?orgId=1&from=1613025127459&to=1613046727459&var-alert_level=$__all&viewPanel=100221)
[Upload store error every 5m](https://sourcegraph.com/-/debug/grafana/d/precise-code-intel-worker/precise-code-intel-worker?orgId=1&from=1613025141100&to=1613046741100&var-alert_level=$__all&viewPanel=100231)
[Gitserver client errors every 5m](https://sourcegraph.com/-/debug/grafana/d/precise-code-intel-worker/precise-code-intel-worker?orgId=1&from=1613025151722&to=1613046751722&var-alert_level=$__all&viewPanel=100241)

**Executor Queue**
[Queue growth rate over 30m](https://sourcegraph.com/-/debug/grafana/d/executor-queue/executor-queue?orgId=1&from=1613003612822&to=1613046812822&var-alert_level=$__all&viewPanel=100001)
[Job errors every 5m](https://sourcegraph.com/-/debug/grafana/d/executor-queue/executor-queue?orgId=1&from=1613003633118&to=1613046833118&var-alert_level=$__all&viewPanel=100002)

**Precise Code Intel Indexer**
The entire dashboard? :thinking: cc @efritz 

**LSIF**
The entire dashboard also

This is a start, theres some in the Frontend dashboard that seem to be phased  out too
