### ISSUE TITLE
GitLab repo permissions shouldn't require SSO with GitLab authentication

### ISSUE THREAD

**Issue by KattMingMing** [sourcegraph/sourcegraph#1813]
When using GitLab authentication, it's unnecessary to require SSO to use repository permissions. However, in the case where only GitLab permissions we will still require Sourcegraph to be configured with the same SSO provided as is used to sign into GitLab.

**Comment by KattMingMing** [comment]
The GitLab external service requires SSO to be enabled on both the sourcegraph instance and GitLab if you want to enable repository permissions, which was only necessary when we didn’t support GitLab authentication. Now when an instance supports logging in with GitLab, we can enable repo permissions for each user without requiring SSO to be responsible for mapping users on sourcegraph to users on GitLab. 

Does that help? @beyang can add additional context here if I’m missing anything.

**Comment by sqs** [comment]
Ah, I was thinking that GitLab auth is a form of SSO, thus the confusion.
