### ISSUE TITLE
[deploy-sourcegraph] Test code intelligence migration steps

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#1814]
_See https://github.com/sourcegraph/deploy-sourcegraph_

Migrated from https://github.com/sourcegraph/sourcegraph/issues/1692

Test update code intelligence migration steps using instructions in https://github.com/sourcegraph/deploy-sourcegraph/blob/master/README.dev.md

**Comment by chrismwendt** [comment]
I feel that setting up code intelligence for 3.0 is being sufficiently covered by other test plans, and I can't think of anything related to code intelligence that would need to be migrated.
