### ISSUE TITLE
[deploy-sourcegraph] Add ingress-nginx migration steps 

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#1815]
_See https://github.com/sourcegraph/deploy-sourcegraph_

Migrated from https://github.com/sourcegraph/sourcegraph/issues/1692

Update https://github.com/sourcegraph/deploy-sourcegraph/blob/master/docs/sourcegraph-3.0.migrate.md with changes related to ingress-nginx

**Comment by nicksnyder** [comment]
Migration steps are not a blocker for 3.0-beta so moving to 3.0
