### ISSUE TITLE
[deploy-sourcegraph] Test ingress-nginx migration steps 

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#1816]
_See https://github.com/sourcegraph/deploy-sourcegraph_

Migrated from https://github.com/sourcegraph/sourcegraph/issues/1692

Depends on https://github.com/sourcegraph/sourcegraph/issues/1815

Test ingress-nginx migration steps using instructions in https://github.com/sourcegraph/deploy-sourcegraph/blob/master/README.dev.md

**Comment by nicksnyder** [comment]
Migration steps are not a blocker for 3.0-beta, so moving to 3.0

**Comment by keegancsmith** [comment]
@ggilmore is currently doing this.

**Comment by keegancsmith** [comment]
I believe this is done? @ggilmore?

**Comment by ggilmore** [comment]
I tested this from scratch, but I did not test the `2.x -> 3.0` migration path yet.

**Comment by keegancsmith** [comment]
I personally did it for prod. Everything you do is additive (and then cleanup of the LB). So your testing covers the same path. Do you think we need more intensive testing?

**Comment by ggilmore** [comment]
No, I trust you 👍
