### ISSUE TITLE
Repository name in search results disappears in a weird way when scrolling

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#18167]
- **Sourcegraph version:** sourcegraph.com
- **Platform information:** macOS, Chrome

#### Steps to reproduce:

1. Search for something that yields results in multiple repositories
2. Scroll through results

See:

https://user-images.githubusercontent.com/1185253/107625318-71fb0780-6c5c-11eb-9c36-6987eff59843.mp4

#### Expected behavior:

I think the repository name should stay visible as long as search results from that repository are still visible.

#### Actual behavior:

The repository name is "behind" the search results.

**Comment by mrnugget** [comment]
(I'm not sure who to assign this to, there's no `frontend-platform` team I can assign it to, so feel free to reassign)

**Comment by felixfbecker** [comment]
Thanks for filing @mrnugget! The search results page is owned by the search team, so reassigning.

**Comment by malomarrec** [comment]
Tagging similar issue in https://github.com/sourcegraph/sourcegraph/issues/20158 so as to come up with a prioritised lists of paper cuts fixes.

**Comment by camdencheek** [comment]
Closing as done. We've since redesigned search results at least 3 times.
