### ISSUE TITLE
Write a cleaner/more general version of grailbio/bazel-compilation-database

### ISSUE THREAD

**Issue by shrouxm** [sourcegraph/sourcegraph#18186]
Ideally users should just be able to input:
- which bazel outputs need to actually be built to compile the code (headers, generated code)
- a bazel expression for which targets we need to analyze the dependency graph of
and get a compile_commands.json.

We should also provide good general defaults for these values. grailbio/bazel-compilation-database for example uses a hardcoded and very short list of possible C++ file extensions to figure out which targets to analyze.

**Comment by perezd** [comment]
Would this support other languages like Java? Or still only C++

**Comment by macraig** [comment]
Hi @perezd, this refers particularly to C++. Bazel is not supported for Java yet, we're planning on supporting it eventually but we don't have an estimated completion date for the time being. If you're interested in Java support you can check https://sourcegraph.github.io/lsif-java/docs/getting-started.html#supported-build-tools to see where we're at.

**Comment by varungandhi-src** [comment]
The `grailbio/bazel-compilation-database` tool works fine enough for now, and there is another alternate tool which we recommend in the scip-clang repo: https://github.com/hedronvision/bazel-compile-commands-extractor
