### ISSUE TITLE
Streaming search dropdown is not keyboard navigable

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#18195]
Users can tab to the dropdown and open it, but not navigate to sub-items within it to open notices or interact with the form.

**Comment by limitedmage** [comment]
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/18170

**Comment by limitedmage** [comment]
Sorry not a dupe, this is streaming search skipped items popup, not search contexts :)

**Comment by limitedmage** [comment]
@rrhyne  can you still repro this? I just tried it and tabbing through the dropdown menu works fine for me.

**Comment by limitedmage** [comment]
Tabbing works but using enter/space to expand/collapse isn't working (see https://github.com/reactstrap/reactstrap/issues/2099) I'm sending out a fix for this.
