### ISSUE TITLE
ci: deploy-sourcegraph ci pipeline fails to delete some test clusters

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#18201]
See https://sourcegraph.slack.com/archives/CJX299FGE/p1612988997206500

The integration tests in https://github.com/sourcegraph/deploy-sourcegraph seem to leave behind k8s test clusters under some unknown circumstances. This occurs both in the pulumi integration tests and the bash "restricted" integration tests: 

- pulumi example: https://buildkite.com/sourcegraph/deploy-sourcegraph/builds/8157#79ebc4db-efc9-48f2-bf5b-f91bec337b3c
- bash "restricted" example: https://buildkite.com/sourcegraph/deploy-sourcegraph/builds/8330#fedcae09-f281-4969-9e0d-d6fba5c16e18

The error message is always the same: `All cluster resources were brought up, but: component "kube-apiserver" from endpoint "gke-..." is unhealthy.`

This error occurs across a variety of K8s cluster versions -  I was not able to find any commonality there. Since the k8s api server is down, I am also unable to inspect the cluster. 

---

For future reference, here is the hacky script that I wrote to pull all the logs from buildkite and search for strings containing the abandoned clusters: https://gist.github.com/ggilmore/a1077634254c05160cfb4ee409bf9bbf (please ignore the code quality - I was writing this quickly). 

Here are all the builds corresponding to the abandoned clusters that the program was able to find:

```
2021/02/11 18:19:34 GOT FAILED BUILDS
2021/02/11 18:19:34 -----------------
2021/02/11 18:19:34 {8330 fedcae09-f281-4969-9e0d-d6fba5c16e18 300a9bfc https://buildkite.com/sourcegraph/deploy-sourcegraph/builds/8330#fedcae09-f281-4969-9e0d-d6fba5c16e18}
2021/02/11 18:19:34 {8292 23dd070b-6f60-4fdf-a9eb-30aa29174945 af8c0f4 https://buildkite.com/sourcegraph/deploy-sourcegraph/builds/8292#23dd070b-6f60-4fdf-a9eb-30aa29174945}
2021/02/11 18:19:34 {8157 79ebc4db-efc9-48f2-bf5b-f91bec337b3c ada4a94 https://buildkite.com/sourcegraph/deploy-sourcegraph/builds/8157#79ebc4db-efc9-48f2-bf5b-f91bec337b3c}
2021/02/11 18:19:34 {8156 804a3363-cb4c-4141-9bee-bafcf1515d39 8233fb8 https://buildkite.com/sourcegraph/deploy-sourcegraph/builds/8156#804a3363-cb4c-4141-9bee-bafcf1515d39}
2021/02/11 18:19:34 {8235 42be306c-f055-42fd-8000-3c9b831c39e4 f51ca8d https://buildkite.com/sourcegraph/deploy-sourcegraph/builds/8235#42be306c-f055-42fd-8000-3c9b831c39e4}
2021/02/11 18:19:34 {8131 43c21868-0460-49b3-9c66-cc723478c428 62b75baf https://buildkite.com/sourcegraph/deploy-sourcegraph/builds/8131#43c21868-0460-49b3-9c66-cc723478c428}
2021/02/11 18:19:34 {8130 21ede05e-b298-4364-a69e-dcabaa34ae20 f4c64dc3 https://buildkite.com/sourcegraph/deploy-sourcegraph/builds/8130#21ede05e-b298-4364-a69e-dcabaa34ae20}
2021/02/11 18:19:34 {8128 ac4b83a8-dcc3-4063-8e37-550fceace172 e30cec23 https://buildkite.com/sourcegraph/deploy-sourcegraph/builds/8128#ac4b83a8-dcc3-4063-8e37-550fceace172}
2021/02/11 18:19:34 {8098 c4dc9a31-d956-455a-9354-fd4c9a57b4b8 d445c37c https://buildkite.com/sourcegraph/deploy-sourcegraph/builds/8098#c4dc9a31-d956-455a-9354-fd4c9a57b4b8}
```

I was unable to find the root cause of this, so I'm going to proceed with simply deleting the clusters for now. https://github.com/sourcegraph/sourcegraph/issues/18200 has been opened to track creating a background job that will reap these abandoned clusters.

**Comment by ggilmore** [comment]
Actually, I am unable to delete a fair amount of the failed clusters because the API server is failing. GKE is reporting that a lot of these clusters are stuck in a "stopping" state - and I can't delete the cluster itself until that completes. I don't see a way to "force delete" them in the GKE UI. I'll investigate finding a workaround for this tomorrow.

**Comment by pecigonzalo** [comment]
@ggilmore maybe that is why it failed for CI as well. Maybe we can open a support case for it and let GCP troubleshoot this, its possible that it got hit by some of their recent outages.

You can open cases in our main Sourcegraph project.

**Comment by ggilmore** [comment]
I checked on this earlier - and the "stuck" clusters seem to have been deleted already (I hadn't opened a support ticket for this yet). https://github.com/sourcegraph/sourcegraph/issues/18200 remains as the path forward

**Comment by pecigonzalo** [comment]
This could be related to these events as well https://status.cloud.google.com/incident/container-engine/21004 seems like GKE is having some issues.
