### ISSUE TITLE
management console: chrome doesn't tell you that the username is irrelevant when signing in

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#1820]
When visiting the management console page via Firefox, the authentication box tells me that the username doesn't matter:

![screen shot 2019-01-11 at 4 06 04 pm](https://user-images.githubusercontent.com/9022011/51065642-d4373900-15ba-11e9-943c-c19b8d1c31aa.png)

However, in Chrome that message is missing:

![screen shot 2019-01-11 at 4 07 38 pm](https://user-images.githubusercontent.com/9022011/51065702-1c565b80-15bb-11e9-9d06-19de16cccf13.png)

I see in the [management console's docs](https://docs.sourcegraph.com/admin/management_console#what-is-the-password-to-my-management-console) that it mentions that you can enter any username, but this is still confusing behavior. Could we at least bold that section in the documentation as a quick fix?

**Comment by slimsag** [comment]
yeah, only Firefox supports these messages. Other browsers do not render them as an anti-phishing security measure.

I will close this as a dup of https://github.com/sourcegraph/sourcegraph/issues/1685 and did the quick fix you suggested: https://github.com/sourcegraph/sourcegraph/commit/f29a7ae98da97fb3d2da284c41ba653ca2b86884#diff-17c8075fe125ab9e7c211a64aff40412
