### ISSUE TITLE
Streaming duplicates `or` expression results

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#18203]
I didn't investigate deeply, but I was pretty dang surprised when 

[`repo:^github\.com/sourcegraph/sourcegraph$ search or tokens file:parserFuzz.ts count:1000`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+search+or+tokens+file:parserFuzz.ts+count:1000&patternType=literal)

duplicated the matches on the file separately (line matches not merging), note that these two file results are both `parseFuzz.ts`:

![Screen Shot 2021-02-12 at 12 00 05 AM](https://user-images.githubusercontent.com/888624/107739087-5415bd00-6cc5-11eb-9dc3-fef89386b60a.png)

I initially didn't suspect streaming, because I saw PRs about it being turned off for these (maybe it was just `and` operators?).  But then after sitting back being baffled, I was 100% sure that I tested this sort of things for months, and so, when I turned off streaming, things were normal again:

![Screen Shot 2021-02-12 at 12 02 27 AM](https://user-images.githubusercontent.com/888624/107739219-9ccd7600-6cc5-11eb-8bd2-4711fb64203e.png)

I'm going to withhold labeling this as "Bug" so we can clarify what the expected behavior is here, and complexities around making subexpressions compatible/amenable to streaming. Like "technically" you could argue that these are two different result sets at the file level, and "correct" (match counts are same), but whatever behavior was introduced is skipping over the merging part of the code (`unionMerge)`. I feel like the original pre-streaming result is more desirable (?) but don't know if this complicates streaming. When we decide on this, I'll write integration tests to pin this behavior.

**Comment by rvantonder** [comment]
Actually I feel like this is a bug with the reasoning that `foo or foo` will show both matches in the same file, when there's only one.

**Comment by keegancsmith** [comment]
The problem here is we can't dedup results with streaming from the backend. We require the client to dedup. This is a tension between streaming out results as soon as they are found vs waiting until we have searched across all "terms" and then dedupping.

I think the correct fix is for the webapp to dedup. It only needs to dedup on what it displays. We may need to design some UX to prevent "popping" as new results in a file stream in. Or make it less surprising that we don't dedup. Note: we already have some dedupping logic within a file on the frontend. This would need to be extended to looking up in a dict which file to add to. cc @limitedmage @rrhyne 

Longer term Zoekt is able to directly execute and/or queries in a single go. This will be both a performance improvement and not require dedupping. WDYT?

**Comment by limitedmage** [comment]
@keegancsmith  What is the right way to de-dupe on the client side? Based on file URL? If we find a duplicate filename, is it simple enough to remove one, or do we have to dedupe the line matches inside?

**Comment by rrhyne** [comment]
Let me see if I have this correct:

*  Results for 'search' is returned on line 1 of a file. 
* A separate search for 'token' returns results for line 2 at a later time (do 'or' queries run a separate search?)
* Any user who has scrolled down below the files being altered would have the code they are reading pushed down by the additional line.

If that's all correct, one way to prevent shifting of results due to the addition of lines is to not alter files that come before the current scroll top. Items below would be updated as required. When a code display with changes is scrolled onto the screen, the new lines would need to fade/slide in with some animation to gradually introduce them to the screen. 

Another way might be to offset the scrollTop by the height of the added items, but I can't imagine that would be smooth. 

A UX based approach might be to pause updates and require the user to display the new updates as they require, but that would seem to require quite a bit of work on the part of the user.

**Comment by limitedmage** [comment]
> * Results for 'search' is returned on line 1 of a file.
> * A separate search for 'token' returns results for line 2 at a later time (do 'or' queries run a separate search?)
> * Any user who has scrolled down below the files being altered would have the code they are reading pushed down by the additional line.

This is what I understand.

I think the best course of action is to prototype a naïve de-duping without UX considerations and after we see how bad it actually is we can see which approach we want to take. None of them are cheap (smooth CSS animations and scrolling with lots of potential state changes can be very time consuming to achieve).

My 2-cents: Streaming search was never designed with the approach of "going back" and changing already-returned results.

**Comment by keegancsmith** [comment]
### @limitedmage

> More than de-duping, this looks like combining line matches for the same file if the same file is returned twice.

We already do some of this. For example do a query like `foobar or foobar` and inspect the API response from graphql and streaming. GraphQL API will return 2 line matches per `foobar`. Streaming will return two file matches per foobar. ie graphql essentially has an algorithm like `results[filematch.url].linematches.append(new_linematches)`, while streaming doesn't attempt to merge.

> I agree with @keegancsmith that this may cause pop in/unexpected UI behavior because we would be modifying **already displayed** results instead of appending results to the end of the page.

Alternatively we could communicate this better? For example we have a little scroll down button saying "show 10 more results" when a filematch has lots of results. Maybe we could just add that in (with a fade?) when we stream in a file again?

### @rvantonder 

> Converting the input query to a set of queries that call out to our backends has been on my mind for a while.

Great. It has been on my mind as well. EG a more general `plan` phase that happens earlier makes a lot of sense to me.

> I firmly believe we should have a general routine that can merge results of expression that's agnostic to our backends.

I don't think we can do that without falling back to batch mode. I'll comment more on your other response below.

> we need a fallback routine for a backend that doesn't--otherwise, we fragment everything and nobody can guess how we end up evaluating a query or whether it is supported.

Maybe we need to make every backend support and/or "within" a repo? That seems doable given the union/intersect logic is relatively straightforward? This does become a bit difficult with commit search though :)

> > The problem here is we can't dedup results with streaming from the backend.
> 
> Would it really be so bad to dedupe stream results in the backend? We'd keep a data structure of "seen" results.

This of course is possible. But at what point can we stream out a result? IE once a filematch has been streamed out... what do we then send when we find another filematch for the same file? Alternatively, when do we know we have found everything for a file?

> It'd add memory pressure, but the thinking is that this merge operation would be a fallback routine, if Zoekt or other backends can natively evaluate the original query.

For the worst case we may be allocating a map the size of every file in our corpus. So we would need a less naive approach, such as every backend understanding simple and/or queries (which I *think* should be doable).

> The other reason I'm in favor of backend deduping is that CLI uses benefit from this behavior (we've already see this with `select:repo` helping campaigns because it dedupes things natively, and we can optimize for that use case).

Agreed that is useful for CLI, and that was our main concern about thinking this needs to be done in the client. But its a tradeoff that I'm not sure about yet.

### @rrhyne 

> Let me see if I have this correct:
> 
> * Results for 'search' is returned on line 1 of a file.
> * A separate search for 'token' returns results for line 2 at a later time (do 'or' queries run a separate search?)
> * Any user who has scrolled down below the files being altered would have the code they are reading pushed down by the additional line.

Yup.

> If that's all correct, one way to prevent shifting of results due to the addition of lines is to not alter files that come before the current scroll top. Items below would be updated as required. When a code display with changes is scrolled onto the screen, the new lines would need to fade/slide in with some animation to gradually introduce them to the screen.

This might actually be fine? IE I think even though we would be "popping". Although I'd prefer scroll positions not to be messed with. Additionally once a search is complete, any result that has been shown to the user needs to have all linematches included. This is so a user can have confidence that once a search is done, they are looking at all matches for a file. This would require backend changes to track that as well.

### @limitedmage 

> I think the best course of action is to prototype a naïve de-duping without UX considerations and after we see how bad it actually is we can see which approach we want to take.

I like this idea. Rather be correct first, then make it smooth :)

> My other concern is that a user will scroll past files returned in the first go and never see the new results.

Exactly. But I think the expectation that until a search is done that results may change is an acceptable one.

> My 2-cents: Streaming search was never designed with the approach of "going back" and changing already-returned results.

Yup. Ideally our backend didn't exhibit this behaviour. However, changing the backend is a much larger change (which we do intend on doing!). It just will take a while.

**Comment by rrhyne** [comment]
> > My other concern is that a user will scroll past files returned in the first go and never see the new results.

> Exactly. But I think the expectation that until a search is done that results may change is an acceptable one.

I disagree! 

 I didn't catch this as early as I should have (thanks @limitedmage!), but this is actually a huge, huge concern. My workflow for finding something is to review each result and keep scrolling. If my work reviewing that returned result may be invalidated, and I have to scroll through results a few times on long searches, then I cannot trust the results and my work is wasted. 
 
This behavior probably couldn't be made acceptable without very complicated and unwieldy UX and I'm not sure it would ever be 'pleasant'.

**Comment by keegancsmith** [comment]
> This behavior probably couldn't be made acceptable without very complicated and unwieldy UX and I'm not sure it would ever be 'pleasant'.

Currently we append the new found matches at the bottom. Is this the better behaviour for now? (eg try the search in the issue description)

**Comment by rvantonder** [comment]
> Maybe we need to make every backend support and/or "within" a repo? That seems doable given the union/intersect logic is relatively straightforward? This does become a bit difficult with commit search though :) This does become a bit difficult with commit search though :)

This assumption is, unfortunately, a can of worms from my point of view. The main prompt that convinced me to introduced search expressions on all terms is that there was a use case precisely for searching over multiple repositories at multiple revisions (e.g., we can have `repo:foo (rev:bar or rev:qux) or repo:stuff`). Even if we declared today "that's not a common use case we can throw that out" it massively complicates consistent query processing. It also becomes problematic with commit search or anything else, basically it blocks a composition operation over backends. I want to emphasize, _we can absolutely enforce that that every backend support and/or within a repo and support streaming and optimize that use case in query processing_ but we shouldn't bake that assumption into our queries. So below is my "generic" fallback solution outline for streaming, in the cases where a search query is expressible, but not optimizeable to a particular backend.

> > I firmly believe we should have a general routine that can merge results of expression that's agnostic to our backends. [...]

>> Would it really be so bad to dedupe stream results in the backend? We'd keep a data structure of "seen" results.

> This of course is possible. But at what point can we stream out a result? IE once a filematch has been streamed out... what do we then send when we find another filematch for the same file? Alternatively, when do we know we have found everything for a file?

Got it, I take your point. This is why in the original post above I basically questioned "is this a bug or do I need to just accept this". Given the complexity of getting this "ideally, absolutely right", for file matches it's clear things are very complex because of this nested result property. It would be cool to stream out just line matches associated with a file, and not file matches, IMO. Then you could dedupe on that and stream out immediately. In lieu of that happening any time soon, I'll backtrack and say: I think this behavior is OK in the backend (and even if the frontend just consumes it as such). This behavior only crops up for explicit `or` operations, and anything that can reduce to a regular expression (like `foo or bar` -> `foo|bar` will at some point be optimized, so we will reduce the chances of file matches duplicating things). 

Other than that my proposal for a "generic" fallback solution is one that I would implement on the basis of assuming, e.g., a blackbox on our streaming API. For example, suppose I had some client that requests streams of results for multiple expressions against our streaming API (one expression could be commit results, another text results, etc.). In my client I would define some policy for merging results over streams (and for `FileMatch`, I would just do the naive thing here and just accept that I'll show both files potentially). That policy control, e.g., the size of buffer of results to collect that I can dedupe on, and after I've seen enough, I would clear the buffer and continue with remaining results. I suspect this would get rid of a couple of artifacts like the one I saw above. And since I feel like I can actually implement such a solution while treating our streaming API as a blackbox, I'm confident we can have something similar inside our backend. Again, emphasis here on "this is the generic fallback solution"--we would try optimize queries so that this wouldn't be needed except when we really can't reduce things down to single text search/backend queries (e.g., multiple repo/rev, combinations of commit and other searches, etc.). take on that?

**Comment by rvantonder** [comment]
I suppose the thing I'm describing is similar to what @stefanhengl did in https://github.com/sourcegraph/sourcegraph/pull/17276. I think this is fine as a fallback `or`-expressions too, and would probably get rid of the artifact in the original post. It'd be nice to define a policy for something like a fixed result set size size instead of waiting for all results to complete (i.e., abstract over the streams instead of abstracting over batch queries).

**Comment by rrhyne** [comment]
> Currently we append the new found matches at the bottom. Is this the better behaviour for now? (eg try the search in the issue description)

The current behavior keeps the workflow intact so that the user's work reviewing results isn't wasted. That said, it will call into question the quality of the results when users see that 'token' is not highlighted in the first example. I believe that would only last until the user discovered the second file where token is highlighted though. 

If a backend solution can be found at some point soon, I think the current behavior is preferable to introducing the levels of both ux design and technical debt required to try and correct this in the front end.

Question: do we know how many searches this affects? Is it all 'or' searches?

**Comment by rvantonder** [comment]
@stefanhengl (CC @lguychard) instead of "living with this state" if we release, I think the easiest would be to just add `evaluateOrStream` that falls back to batch search, just like `evaluateAndStream` does. That would be a simple and effective stopgap, no?

**Comment by keegancsmith** [comment]
> @stefanhengl (CC @lguychard) instead of "living with this state" if we release, I think the easiest would be to just add `evaluateOrStream` that falls back to batch search, just like `evaluateAndStream` does. That would be a simple and effective stopgap, no?

It looks like this bug is still present and we didn't do this fallback. I am guessing we should fallback to batch behaviour? Here I believe the solutions to this solution in order of simplicity, but in reverse order of optimality:

1. fallback to batch behaviour
2. deduplicate in backend in OR queries (negative due to memory usage)
3. deduplicate in backend in OR queries with heuristics (eg sometimes return duplicates, but bound memory usage)
4. deduplicate in webapp
5. convert OR query into Zoekt query.

fallback seems dead simple, but regresses time to first result. backend deduplicate isn't hard to implement, we already have it implemented for batch. deduplicate in webapp allows us to better deal with results in the same file coming later. The best is the final point about zoekt directly executing or queries. In general we can't always do this due to us not always supporting all features in both backend and zoekt, but seems like it scales best.

We should make a decision here. I propose the core search support taking on one of these as a polish task (this or next week). That will make this issue closed out. I believe the Zoekt stuff is somewhere on the roadmap @rvantonder? @lguychard WDYT?

**Comment by rvantonder** [comment]
Ideal way this plays out:

(1) _Compatible_ queries are converted to Zoekt queries. 
(2) As we know, not all `or`-expressions are compatible Zoekt queries, they may not even concern text search. Compatible expressions should convert to an appropriate backend query that supports `or`-expressions natively (whether through regex, e.g., for commit message `message:a or message:b` implies `message:a|b`, or some native capability, e.g., let's say comby starts supporting `or`-expressions), _but should otherwise fallback to the generic expression evaluator_. I want to reemphasize that we should _always have a generic expression evaluator_. 

These solutions are not mutually exclusive, and they correspond to your (1) and (5). 

> I propose the core search support taking on one of these as a polish task (this or next week).

(1) is feasible now. In my opinion, (5) is not feasible in the current state of query processing, this is why I've been tackling it in refactors like #19698--this is exactly what's needed to implement (5). In fact, the most important thing to me right now isn't the `or`-expression, but efficient `not` and `and` evaluation for text search. (5) can and should not be done without a code structure that can support that translation. I've described what this needs to look like in  [RFC 254](https://docs.google.com/document/d/1_m63fsBMAtqaq3GA_aMzKUPxD3yxTy8d12lJE6qN6PU/edit#heading=h.s25eb1cluqod) and [this comment](https://github.com/sourcegraph/sourcegraph/pull/19698#issuecomment-815126347).

>  I propose the core search support taking on one of these as a polish task (this or next week). That will make this issue closed out. I believe the Zoekt stuff is somewhere on the roadmap @rvantonder? @lguychard WDYT?

In my opinion for (5) it will take me one dedicated month to restructure our code to support an evaluation model that deals gracefully with optimized backends. It is not a light task. I don't think this restructure is a good fit for core-search to take on, I've now built up >1 year of context and actively working on restructures where I can, and I know what this needs to look like. If the desire is to close this issue ASAP, feel free to tackle (1)/batch behavior, it will be a short PR I think. I can't make any promises about when the Zoekt optimization work will be done, since I need to negotiate my time around restructuring this part of the code. Don't get me wrong, I'm eager to get it done, but "performance scaling queries" or such is not a roadmap item right now.

**Comment by keegancsmith** [comment]
> (2) As we know, not all `or`-expressions are compatible Zoekt 
> queries, they may not even concern text search. Compatible 
> expressions should convert to an appropriate backend query that 
> supports `or`-expressions natively (whether through regex, e.g., 
> for commit message `message:a or message:b` implies 
> `message:a|b`, or some native capability, e.g., let's say comby 
> starts supporting `or`-expressions), _but should otherwise 
> fallback to the generic expression evaluator_. I want to 
> reemphasize that we should _always have a generic expression 
> evaluator_.  

Agreed, we always need a generic version. Is there an example of a 
non-compatible `or` query on indexed code? IE I assume for a 
candidate result, it needs to satisfy the `or`-expression and 
doesn't rely on other state.

> If the desire is to close this issue ASAP, feel free to tackle 
> (1)/batch behavior, it will be a short PR I think.

Yeah I think this is the correct approach since it does fix this 
issue. The broader work we want to do can be tracked by something 
else than this bug report.

**Comment by rvantonder** [comment]
> Is there an example of a non-compatible `or` query on indexed code? 

There are a couple of cases where a query shape is not a pure Zoekt expression, which may cause an evaluation of the generic `or`-expression if I understand the question. 

- `(repo:foo or repo:bar) <something that converts to Zoekt query>`

- generalization of above: `<something that converts to Zoekt query> or <any expression that is not text search>`

Wherever a subexpression of a Sourcegraph query can be converted to a Zoekt query, we would do so, and use the result it generates and use it during further evaluation. There is no scenario where the result of a Zoekt query (`FileMatch`) would be incompatible with general evaluation, since general evaluation operates on all search result types.

Anyway sounds like we're agreed on the immediate way to resolve this and the long term one will pan out over time!

**Comment by rvantonder** [comment]
To investigate: this likely affects `select:file` functionality (and anything that relies on file match). I've repro'd an issue where `select:file` duplicates, likely because the underlying result set are duplicated file matches, that we do not deduplicate properly on assumption that the file matches are unique (?).

[`repo:^github\.com/sourcegraph/sourcegraph$ TODO or SEARCH or TODO or Search select:file file:batches\.go`](https://sourcegraph.test:3443/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+TODO+or+SEARCH+or+TODO+or+Search+select:file+file:batches%5C.go&patternType=literal)

<img width="830" alt="Screen Shot 2021-04-26 at 2 52 29 PM" src="https://user-images.githubusercontent.com/888624/116155527-0b07bf00-a69f-11eb-85f5-df302e644bb8.png">

**Comment by rvantonder** [comment]
Owning this--have started working on a solution.
