### ISSUE TITLE
Same reference appears twice (with commit specified and unspecified)

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#1823]
- **Sourcegraph version:** alpha9

#### Steps to reproduce:

Haven't tried to repro on another repo yet.

1. Follow the instructions here: https://github.com/sourcegraph/sourcegraph/issues/1717
2. Go to http://localhost:7080/github.com/sourcegraph/sample-public-go-repo/-/blob/main.go#L5:25&tab=references
3. Ensure that:
  * Fuzzy matches are turned OFF
  * Show references from other repositories is turned ON

![image](https://user-images.githubusercontent.com/5589410/51066968-ae159700-15c2-11e9-9b47-0855053ebf93.png)

Note that you see two references to the same line. If I "Hide references from other repositories", the 2nd one goes away.

If I click, the two URLs I get taken to are:
* http://localhost:7080/github.com/sourcegraph/sample-public-go-repo@1d29938eca9afab8e8a26479d78e60b5978c0f57/-/blob/main.go#L5:25
* http://localhost:7080/github.com/sourcegraph/sample-public-go-repo/-/blob/main.go#L5:25

The extension seems to think the specified commit is a different repo.

**Comment by chrismwendt** [comment]
Thanks for reporting! Fixed in https://github.com/sourcegraph/lang-go/commit/773a90c040d0730eb3607be7e2b9f27fa6e41c39
