### ISSUE TITLE
GitHub CSP blocking browser extension requests to local instance

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#1825]
![screenflow](https://user-images.githubusercontent.com/133014/51067842-d1dcdb00-15ca-11e9-81eb-d1080733877a.gif)

To reproduce, launch a local Sourcegraph and lang server, point the browser extension at your local instance, then try getting code intelligence to work. This seems to have happened to @KattMingMing today and I was able to reproduce the issue on @dadlerj's local instance.

When browsing GitHub with the browser extension installed, after an indeterminate amount of time, requests from the browser extension from the contents script start failing due to CSP issues.

It's triggered when the CSP has a different `frame-src` value.

![pasted_image_at_2019-01-11__6_05_pm](https://user-images.githubusercontent.com/133014/51067928-b32b1400-15cb-11e9-97df-3f585ac17d1c.png)

**Comment by ryan-blunden** [comment]
We tried at one point to use an ngrok https url, thinking that perhaps, it was because of localhost or the fact requests were sent via http.

This worked for a while (less than an hour), the stopped working. I tried a different ngrok URL which worked for less time, then eventually no ngrok URLs worked.

**Comment by lguychard** [comment]
Closed by #1954
