### ISSUE TITLE
search: count limit is enforced as number of matching fragments

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#18298]
Depending on the backend we enforce limits differently. We want to make it such that it is always based on the number of "highlighted" results we send back (ie fragments/offsetAndLengths). We still need a hardcoded limit to prevent OOMing, but it should be much higher. Here is the current state of limits:

So I went and investigated how exactly limits work within a file. My memory was slightly incorrect, we do not limit within a line. Rather we have limits on the number of fragments we find in a file. We also have limits on the number of documents we find with matches, and this is normally what a backend interprets `count:` to mean.

Investigating fragment limits:

-   Zoekt has no limits in a document! Surprising, this is an avenue to denial of service zoekt. See [regexp](https://github.com/sourcegraph/zoekt/blob/41147eccb798a61e2ed11a737456c5b41cdb1caf/matchtree.go#L635) and [substring](https://github.com/sourcegraph/zoekt/blob/41147eccb798a61e2ed11a737456c5b41cdb1caf/matchiter.go#L179), additionally no limiting is done elsewhere in eval.go.
-   Searcher's limit is hardcoded as 100 in a document. See [maxLineMatches](https://github.com/sourcegraph/sourcegraph/blob/v3.24.1/cmd/searcher/search/search.go#L44)
-   I am unsure what comby does (structural search).
-   unindexed symbol search caps at 500 fragments over the whole repo but otherwise uses the user's count. See [maxFirst](https://github.com/sourcegraph/sourcegraph/blob/v3.24.1/cmd/symbols/internal/symbols/search.go#L146) and how we set [First](https://github.com/sourcegraph/sourcegraph/blob/v3.24.1/cmd/frontend/graphqlbackend/search_symbols.go#L260).

Outside of fragments we have limits as well:

-   zoekt interprets user's count as the number of line matches (not matches on line) to stop at. See [MatchCount write](https://github.com/sourcegraph/zoekt/blob/41147eccb798a61e2ed11a737456c5b41cdb1caf/eval.go#L262) an [MatchCount read](https://github.com/sourcegraph/zoekt/blob/41147eccb798a61e2ed11a737456c5b41cdb1caf/eval.go#L160).
-   searcher caps at 1000 documents with matches. See [maxFileMatches](https://github.com/sourcegraph/sourcegraph/blob/v3.24.1/cmd/searcher/search/search.go#L40)
-   unsure about comby (structural).
-   unindexed symbol search only limits on fragments (which is better).

Part of https://github.com/sourcegraph/sourcegraph/issues/18297

**Comment by keegancsmith** [comment]
Some extra notes around the concept of counting fragments.

Commit search doesn't always have something to highlight. For example when you just search based on metadata like timestamp or author. Here are two example queries:

```
repo:^github\.com/sourcegraph/sourcegraph$ type:commit author:keegan after:"1 day ago"

repo:^github\.com/sourcegraph/sourcegraph$ type:commit after:"1 day ago"
```

Multiline results contribute a count per line. Here is an example: https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+:%5B%5Bf%5D%5D%28...context.Context...%29+%28...%29+%7B:%5Bbody%5D%7D+rule:%27where+match+:%5Bbody%5D+%7B+%7C+%22:%5B~context.Background%5D%22+-%3E+true+%7D%27+lang:go&patternType=structural

**Comment by lguychard** [comment]
@keegancsmith is this still relevant?

**Comment by keegancsmith** [comment]
I've assigned myself and added to backlog to investigate the current state of the world. I think it might still be relevant, but things have def changed here. Including lots of good work by @camdencheek for insights, so it is possible things are much more equal now.

**Comment by camdencheek** [comment]
Things are definitely a bit better, both for commit/diff search and for unindexed text search. Both are fully streaming and respect the limit based on fragments matched.

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket,  please tell use how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
