### ISSUE TITLE
Explore on site admin overview is wrong color on dark theme

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1829]
![screenshot from 2019-01-12 03-33-47](https://user-images.githubusercontent.com/1976/51072762-e8ab1e00-161a-11e9-8f8b-50d3c1a432e8.png)

**Comment by francisschmaltz** [comment]
Fixed in 
https://github.com/sourcegraph/sourcegraph/commit/e49b702c938abda67bf38ca27e2237fd0a0380d6
