### ISSUE TITLE
`select:` on streamed results

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#18291]
`select` currently doesn't work on streamed results. E.g., with `streaming` on, we see content results with `select:file`

<img width="1436" alt="Screen Shot 2021-02-15 at 10 21 12 AM" src="https://user-images.githubusercontent.com/888624/107976968-99f9ac00-6f77-11eb-9c12-9a0ed111c8c9.png">

 Some context:

![Screen Shot 2021-02-15 at 10 19 17 AM](https://user-images.githubusercontent.com/888624/107976754-49824e80-6f77-11eb-9f45-5eaf95c44df9.png)

**Comment by rvantonder** [comment]
Note: our integration tests were fine because we're not testing against streaming. Side question is how we can add integration tests for streaming.

**Comment by camdencheek** [comment]
Do we do any deduplicating for streaming? It seems like we wouldn't be able to actually stream any results until we've got the full set so that we can merge FileMatches

**Comment by rvantonder** [comment]
We'd do the deduplicating. We can still deduplicate on a stream as we get results--for `FileMatch`, it's a bit of a toss up, my take is we are fine to navigate around it, because:

- `FileMatch` merges matters more for `or`-expressions, such that _if_ a result set contains multiple content matches for a file, then we merge them. But if a result set does not contain multiple content matches (let's say we short-circuit because we found enough results for a subexpression) then we currently wouldn't merge them anyway--we don't wait for the full set/exhaustive search. Note that as we mentioned, we're not deduping line matches for this right now, neither for streaming nor batch search.

- The `FileMatch` merges is important in that context ^ because it's nice to highlight disjoint results once we have a result set, and not duplicate the UI Result Component. For streaming, this UI rendering not so important because we show results as they come in (like, as a cosmetic thing, maybe the frontend can reorder the Result Components if we see a new result of a file match), but from the backend perspective we would just deduplicate on the stream as we would before--we don't need the complete result set before deduping, even for `FileMatch`.

**Comment by camdencheek** [comment]
Makes sense to me. After talking with Keegan, it seems like we can pretty easily wrap the streamer to select/deduplicate results. Like you mentioned, `FileMatch` results already behave a little weird, so I'll leave deduplicating line results to a future me.
