### ISSUE TITLE
search: clearly state when limits are hit

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#18300]
We need to more clearly state when limits are hit. Currently we have a single `LimitHit` field. We should differentiate between limits being hit within a repository, document, line, commit, etc. Additionally we should clearly indicate if we hit the limit due to `count:` or a hard cap on the number of matches in a document.

This will probably involve extending the `Skipped` API in the streaming `Progress` API and populating it.

Part of https://github.com/sourcegraph/sourcegraph/issues/18297

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket,  please tell use how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
