### ISSUE TITLE
insights: better scheduler implementation for executing searches

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#18308]
Right now the Code Insights background workers will enqueue search queries to be executed at a given interval, and we enforce that the timeout on searches is below that interval to promise the queue does not grow unbounded (e.g. if a search takes longer than the interval we enqueue at).

https://github.com/sourcegraph/sourcegraph/pull/18267#discussion_r576237553

This could be improved by adding backpressure such as through only enqueuing _new_ insights from the enqueuer, and having the worker itself enqueue the next job.

**Comment by coury-clark** [comment]
No longer necessary, insights maintain state in a database and will schedule recordings based on a timestamp.
