### ISSUE TITLE
Exhaustive search UX MVP in the webapp

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#18306]
This iteration we are focussing on the backend for exhaustive search. However, we don't want to forget what the user experience will be like. From a backend perspective we won't add any extra "marker" that we have an exhaustive search. Rather we want to make the experience of running a high `count:` query reliable.

High level questions to answer so we can close this issue (can design later/etc):

1. Do we want to do anything to the UX to make it clearer how to run an exhaustive search?
2. Do we want to change anything in our streaming UX for long running queries?
3. Do we want to introduce Display Limits vs Match limits? IE only send down Display Limit results to browser, but continue to compute aggregate statistics. How will we introduce this? (eg query token `display:10 count:999999`).

cc @stefanhengl

**Comment by keegancsmith** [comment]
@lguychard @stefanhengl and I chatted a bit about this now. We have some ideas around the UX that we will put into an RFC that will be published this week. So will take over assignment on this now.

**Comment by lguychard** [comment]
The plan:
- We stream N results max (handled on the backend with `display`)
- The frontend sets `display:`
- If scrolled through all results, the frontend shows an alert telling the user to use src-cli
