### ISSUE TITLE
streaming: detailed counts in API response

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#18302]
Currently we return a single count: the number of results. We plan on making it consistent what that means. However, we might as well return more information such as:

- number of "highlights" (current).
- number of lines with matches.
- number of documents with matches.
- number of commits with matches (in commit/diff search).
- number of repositories with matches.

Part of https://github.com/sourcegraph/sourcegraph/issues/18297

**Comment by rrhyne** [comment]
Potential duplicate ticket: https://github.com/sourcegraph/sourcegraph/issues/17573. Happy to move Figma designs here if that's the case.

**Comment by keegancsmith** [comment]
Lets keep this as the backend part of the task.

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket,  please tell use how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
