### ISSUE TITLE
Commit view shows highlighted diff on wrong version of the file

### ISSUE THREAD

**Issue by JohnAZoidberg** [sourcegraph/sourcegraph#18315]
- **Sourcegraph version:** "Sourcegraph.com"
- **Platform information:** Firefox 84.02 on Linux

#### Steps to reproduce:

- https://github.com/tianocore/edk2/commit/bd9da7b1da2639fcea8a156fa92a32bbc4209367 shows the correct diff.
- https://sourcegraph.com/github.com/tianocore/edk2/-/commit/bd9da7b1da2639fcea8a156fa92a32bbc4209367?visible=2 shows a different diff, which is incorrect.

Hmm, the line number is shown as the same in both. So I think Sourcegraph wants to highlight the correct line but the source that's displayed is not from the given revision.

**Comment by camdencheek** [comment]
Hi @JohnAZoidberg -- I just tried to reproduce this with the links you gave, and the diffs both look the same to me now. I think this might have been fixed since you reported this. Could you check that this is still an issue?
