### ISSUE TITLE
Structural search with index:no is not propagating limitHit

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#18311]
[`repo:^github\.com/tianocore/edk2$ ESAL index:no`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/tianocore/edk2%24+ESAL+index:no&patternType=structural)

Shows 18 results, and no `show more`. This would normally mean things are exhaustively searched. But, there are definitely more matches, 31, with `count:1000`

[`repo:^github\.com/tianocore/edk2$ ESAL index:no count:1000`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/tianocore/edk2%24+ESAL+index:no+count:1000&patternType=structural)

Ran into this while debugging a highlight issue for a result in that repo.

/cc @sourcegraph/search-platform

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket,  please tell use how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
