### ISSUE TITLE
inserter.Flush: ERROR: duplicate key value violates unique constraint "lsif_data_metadata_pkey" (SQLSTATE 23505)

### ISSUE THREAD

**Issue by Strum355** [sourcegraph/sourcegraph#18356]
[Link to failed upload](https://sourcegraph.com/site-admin/code-intelligence/uploads/TFNJRlVwbG9hZDoyNjQxNTY=)

![image](https://user-images.githubusercontent.com/18282288/108138841-b4866f00-70b6-11eb-8c0b-1438936c2d19.png)

![image](https://user-images.githubusercontent.com/18282288/108138818-acc6ca80-70b6-11eb-8426-2d80fcc3273a.png)

**Comment by efritz** [comment]
Fixed by https://github.com/sourcegraph/sourcegraph/pull/21530.
