### ISSUE TITLE
Update sass framework

### ISSUE THREAD

**Issue by francisschmaltz** [sourcegraph/sourcegraph#1836]
Update sass framework to reduce pain points for design and engineering.

Goals:
- [ ] Use mixins for theme, viewport, components to make reuse easier. @francisschmaltz 
- [x] Use long hex codes for all colors (outside of rgba)
- [ ] Create proposal for design framework @francisschmaltz

**Comment by francisschmaltz** [comment]
Using our currently code style for sass slows down development significantly as I spend most of my time trying to figure out what something controls as searching for css becomes impossible as everything is segmented into `&__name` which always returns more results than needed. As I have become increasingly responsible for CSS I see a huge improvement we can make to our product.

**Comment by francisschmaltz** [comment]
@felixfbecker and I discussed over a (long) video chat. Updated description with goals.

**Comment by nicksnyder** [comment]
@francisschmaltz the remaining checklist items are assigned to you. Is this work that you are going to do this week? If not, let's backlog.

**Comment by francisschmaltz** [comment]
@nicksnyder moving to backlog
