### ISSUE TITLE
Remove 'X' icon from 'enable extension' toggle

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#18364]
**Description**

We received signals that current visuals of the disabled toggle on the [extension details page](https://sourcegraph.com/extensions/sourcegraph/open-in-editor) are misleading - toggle doesn't look like a clickable element. The hypothesis was that the 'x' icon was making the whole element look less like a traditional toggle. I've tested it with both internal and external users during [action item bar tests](https://docs.google.com/spreadsheets/d/1hRBPzEA7ogvip4zD4aopvCa8i1J-htjp4vZcp6tlahE/edit?usp=sharing). Results were positive for the no-x-icon approach.

Currently:
<img width="742" alt="Screenshot 2021-02-17 at 10 02 22" src="https://user-images.githubusercontent.com/20326070/108180628-4cac4480-7107-11eb-97dd-4b8563ada459.png">

**Design spec**

Remove the 'x' icon from the toggle:
<img width="959" alt="Screenshot 2021-02-17 at 10 02 45" src="https://user-images.githubusercontent.com/20326070/108180657-559d1600-7107-11eb-98c6-d2a3de92a191.png">

Important: enabled toggle remains without changes (with the tick icon).

**Comment by AlicjaSuska** [comment]
@Joelkw @jeanduplessis can we add it to the next iteration?

**Comment by Joelkw** [comment]
Yes! Thank you for thoroughly testing this.
