### ISSUE TITLE
Highlight symbol, path, repository, and description matches

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#18374]
Currently, only matches within code are highlighted. We do not highlight symbol, path, or repository matches in search results.  

To help users visually locate occurrences and align result counts with matches, we should highlight occurrences in symbols, paths, and repositories.

![image](https://user-images.githubusercontent.com/539268/108217176-24f9b400-70e8-11eb-8162-5e7433a79938.png)

![image](https://user-images.githubusercontent.com/539268/108216959-e2d07280-70e7-11eb-90d4-ede65064bed0.png)

Figma:

https://www.figma.com/file/Y8FtteYjdKPCtyx3DZyNbl/%2318374-Proposal-to-highlight-all-results?node-id=15%3A0&viewport=759%2C521%2C0.25

**Comment by keegancsmith** [comment]
This is something that is webapp related. I could attempt to do it, but I would be much slower than @limitedmage :)

**Comment by limitedmage** [comment]
@rrhyne This is not streaming search related, right? It also happens for non-streaming search results. Depending on how we decide to implement this, it might also require backend work.

**Comment by limitedmage** [comment]
To elaborate, it might be trivial to find `sourcegraph/sourcegraph` in `github.com/sourcegraph/sourcegraph-vscode`, but what if the query is something like `repo:sourcegraph vscode`, or even a complex regex or globbing syntax? What would we highlight there? We may need a mechanism from the backend to return the matching part similar to how we do it for line matches.

**Comment by rrhyne** [comment]
> @rrhyne This is not streaming search-related, right? It also happens for non-streaming search results. Depending on how we decide to implement this, it might also require backend work.

This is correct, apologies! I've moved to the exhaustive project.

**Comment by rrhyne** [comment]
Moving to search UX redesign. This is an important consistency item for search results and I think we should include it as part of those efforts.

**Comment by limitedmage** [comment]
This is nice-to-have but unfortunately will require a lot of work to make this happen as part of the redesign. It will require a lot of heavy backend modifications.

**Comment by keegancsmith** [comment]
> This is nice-to-have but unfortunately will require a lot of work to make this happen as part of the redesign. This needs a lot of heavy backend modifications.

What is the backend work? To include highlight ranges for all result types?

**Comment by limitedmage** [comment]
> > This is nice-to-have but unfortunately will require a lot of work to make this happen as part of the redesign. This needs a lot of heavy backend modifications.
> 
> What is the backend work? To include highlight ranges for all result types?

Yes, and also possibly changing the way the data rendered in result titles is returned. Right now, for example, repos and files return the right data split up, but commit/diff results return two markdown strings that combine repo, author, message in one and hash, date in another. If we want result match highlighting on, for example, commit message, this might have to change.

**Comment by lguychard** [comment]
@tbliu98 should this be closed?

**Comment by tbliu98** [comment]
@lguychard Symbol highlighting hasn't been implemented yet but is still on my radar, so I would say this can be left open for now
