### ISSUE TITLE
Other ext services docs: change https://YOUR-INSTANCE --> https://sourcegraph.example.com

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#1837]
On https://docs.sourcegraph.com/admin/repo/add_from_other_external_services

We use example.com domains instead! E.g. https://sourcegraph.com/search?q=r:sourcegraph/sourcegraph+f:doc+example.com+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+

See the style guide for things like this: https://github.com/sourcegraph/about/blob/master/STYLEGUIDE.md

**Comment by tsenart** [comment]
Thanks!
