### ISSUE TITLE
insights: frontend startup should not block on codeinsights-db

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#18388]
https://github.com/sourcegraph/sourcegraph/pull/18359

There are a lot of good reasons that the frontend should not wait/block to start up on initializing the codeinsights DB. Instead, the GraphQL API should merely be unavailable until it has initialized.

One great reason for this would be any DB migration we run taking a potentially long time. Another great reason is that if something happens which prevents codeinsights-db from starting up, a user's only recourse currently is to completely disable the code insights backend and we have to later convince them to turn it on (vs. them seeing errors in the web UI.)

**Comment by coury-clark** [comment]
No longer relevant based on modern Sourcegraph architecture, closing.
