### ISSUE TITLE
Unclear empty state for extension command palette

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#1841]
If I install the browser extension and then discover the command palette on GitHub.com, it is unclear what I should do to make this useful. How do I add commands here? Do I need to sign in to sourcegraph.com? There is no hint that this is related to extensions.

![image](https://user-images.githubusercontent.com/754768/51082025-01671280-16b3-11e9-951d-6b7e865758e9.png)

This was on the root page of a repo; once I went to a code page there were things populated there, but it isn't clear that commands might change depending on what page I am on.

**Comment by christinaforney** [comment]
This is duplicated in #3644 which references the empty state on Sourcegraph.

**Comment by felixfbecker** [comment]
If the user has no extensions installed, this could show an alert "You don't have any Sourcegraph extensions installed. Find extensions in the [Sourcegraph extension registry](), or learn [how to write your own]() in just a few minutes."

If the user has extensions that are not activated, it could slightly modify above message to say "Commands from your installed extensions will be shown here when you navigate to certain pages. Find more extensions in the [Sourcegraph extension registry](), or learn [how to write your own]() in just a few minutes."

**Comment by dadlerj** [comment]
Also reported by a user at https://app.hubspot.com/contacts/2762526/company/407948923

**Comment by rrhyne** [comment]
Will be addressed in https://github.com/sourcegraph/sourcegraph/issues/11872

**Comment by AlicjaSuska** [comment]
Addressed in PR #[13305](https://github.com/sourcegraph/sourcegraph/pull/13305)
