### ISSUE TITLE
Chrome extension fails to connect to private instance due to CORS in background page

### ISSUE THREAD

**Issue by marekweb** [sourcegraph/sourcegraph#18412]
I've started observing this behavior in the Chrome extension where the background page is unable to make requests to a private Sourcegraph instance.

When setting the Sourcegraph URL to `https://k8s.sgdev.org`, the options page is unable to validate the URL:

![Screen Shot 2021-02-17 at 23 44 27](https://user-images.githubusercontent.com/602886/108306569-72befc80-717a-11eb-933e-0a83af512ab5.png)

This is caused by the background page's request to validate the URL failing, due to a CORS failure.

> Access to fetch at 'https://k8s.sgdev.org/.api/graphql?SiteProductVersion' from origin 'chrome-extension://lhhkipppenfkelpnnhoehndpejholohb' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by felixfbecker** [comment]
Potential causes:
- `corsOrigin` misconfigured on k8s.sgdev.org site config?
- Not signed in and auth proxy doesn't send CORS headers?
- Browser extension doesn't have permissions for k8s.sgdev.org (which would disable CORS I believe in the background page for that site)

**Comment by Joelkw** [comment]
I'm not able to reproduce this and am logged in. @marekweb do you notice any patterns? (This is low-priority at the moment unless we hear it from a customer.)

**Comment by goddenrich** [comment]
we are a customer and I am seeing it 
`[internal sourcegraph url] from origin 'chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by Joelkw** [comment]
@goddenrich Thanks for letting us know. What is your current configuration; do you have your Sourcegraph instance on a network with any access controls? (I will also sync up with our customer engineering team, since they're more familiar with our individual customers' configurations.)

**Comment by abeatrix** [comment]
@goddenrich  Hi there! Since we do not encourage our customers to share any private information in the public tracker, a follow-up email has been sent to your email with Thought Machine. These emails sometimes end up in the spam filter, so here is the subject I used for your reference: _Chrome extension fails to connect to private instance due to CORS in background page_
Please let me know here if you didn’t get it. Otherwise, I look forward to hearing from you via email!

**Comment by abeatrix** [comment]
Hi Team! I am also getting the same error in the console with `https://k8s.sgdev.org/`
Here are my network logs:
![image](https://user-images.githubusercontent.com/68532117/111383640-ba478400-8665-11eb-9c9c-cf0883ac3a86.png)
![image](https://user-images.githubusercontent.com/68532117/111384213-7b65fe00-8666-11eb-9a02-43cb36811d4d.png)
![image](https://user-images.githubusercontent.com/68532117/111384028-448fe800-8666-11eb-9169-4e0eecb40b1f.png)

**Comment by erzhtor** [comment]
Hey, everyone! I'm not being able to reproduce it for both (not) logged-in self-hosted sourcegraph instance. I would assume it was already fixed already.
<details>

![image](https://user-images.githubusercontent.com/6717049/144588508-bf7325fd-b339-4932-93d9-5e48c63d6078.png)

</details>
Let me know, if you still experience it, we will re-open and continue the investigation.

**Comment by abeatrix** [comment]
@erzhtor I also cannot reproduce it anymore 👍
