### ISSUE TITLE
Let's see if I can mention the team

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#18424]
If the body of the issue contains the word campaigns then we should all be mentioned. Let's hope it works this time.

**Comment by mrnugget** [comment]
Works! I'll leave it like this. Means we need to add/remove people manually from the list. Let me know if you want to get added @rrhyne or if someone wants to be removed.

**Comment by rrhyne** [comment]
I'm fine without, for now, thanks for asking.

**Comment by chrispine** [comment]
Cool, thanks for doing this!
