### ISSUE TITLE
Why aren't we using the standard discussion list component on the explore page?

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#1848]
I have reported this before on Slack and IIRC @sqs said that @francisschmaltz was looking into unifying these. Compare the two discussion list UXs:

- https://sourcegraph.com/discussions
- https://sourcegraph.com/explore

The problem: The explore page is for some reason using its entirely own component to render a list of code discussions. This has multiple issues:

- The logic and styling is non-trivial, it is a lot of duplicate code and the implementations are not similar at all.
- The explore page version has multiple UX bugs:
    - (recent regression) Missing space between words: https://github.com/sourcegraph/sourcegraph/issues/1846
    - You cannot click the author name as one would expect.
    - Hovering over the timestamp does not properly indicate the exact time the comment was created.
    - There is no indication to me as a user wtf those numbers on the right are. Most of them just say one or two, what are they? They have no icon or tooltip indicating what they are.
    - The spacing, font size, etc. are inconsistent with the entire rest of our UX

Solution:

The explore page should be using the existing code discussions list component, i.e. the one that https://sourcegraph.com/discussions is using. It is understandable that the explore page will not want a search bar, in which case we should add a property to the component to hide it.

Thoughts @francisschmaltz @sqs ? Why was this not implemented this way in the first place?

**Comment by francisschmaltz** [comment]
@sqs I'm not sure the reason for this but I'd love to unify these.

**Comment by slimsag** [comment]
Just to be sure we're on the same page, 'unify' really just means: figure out how to use the existing DiscussionsList component on the explore page, which likely just involves adding a property to hide the search bar.

**Comment by francisschmaltz** [comment]
Yep! Exactly!

**Comment by sqs** [comment]
There’s no good reason. I agree we should unify them too.

**Comment by sqs** [comment]
Code discussions are not shown here anymore
