### ISSUE TITLE
Investigate improving link previews/unwraps for pasting Sourcegraph links to lines of code

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#18499]
If you paste a GitHub link in slack, it looks like: 

The Sourcegraph link looks like: 

Let's make our link previews rich and reveal the lines of code you select. 

If you select a larger block of code than you can view in the link preview, we should start the preview at the first line of code.

**Comment by Joelkw** [comment]
Tangentially related to #16528

**Comment by vdavid** [comment]
@novoselrok worked on this recently, and what we figured was that the only info we can show while respecting customer privacy was stuff that was already in the URL. He's already implemented it (as far as @philipp-spiess and I remember), so we should be good. Closing this. @novoselrok if I'm mistaken, let me know and I can reopen this.

**Comment by novoselrok** [comment]
Yes, an improvement was implemented here: https://github.com/sourcegraph/sourcegraph/pull/41843

Site-admins can enable it by creating the `enable-link-previews` feature flag.

**Comment by felixfbecker** [comment]
I think to achieve the features in the issue description, we would need to write a Slack app, that can handle authentication and unfurling. Otherwise we can only show info from the URL. That's how the GitHub Slack integration does it. Maybe it should be kept open?
