### ISSUE TITLE
Support profile images for organizations

### ISSUE THREAD

**Issue by francisschmaltz** [sourcegraph/sourcegraph#185]
Sourcegraph should support profile images for organizations the same way it supports them for users.

**Comment by francisschmaltz** [comment]
Can we take a look at implementing this feature. Shouldn’t be too big of an issue.

**Comment by nicksnyder** [comment]
No, we aren't going to prioritize this right now as there are many other high value things we are working on. We can prioritize this when there is concrete customer feedback or a use case.
