### ISSUE TITLE
Add Perforce Streams support

### ISSUE THREAD

**Issue by christinaforney** [sourcegraph/sourcegraph#18557]
Some organizations use Perforce to store assets and video files. This means depots can be multiple TBs. To mitigate the size of the depot, some organizations use  [Perforce Streams](https://www.perforce.com/perforce/r13.1/manuals/p4v/streams_overview.html).  the cloned stream with a limited set of directories is only 25GB.  Unfortunately, streams aren’t compatible with git-p4 (see this [SO question](https://stackoverflow.com/questions/52044658/git-p4-on-a-perforce-stream)).  However, there are a few extensions to make it work.  The workaround is to clone the entire depot and configure SG to ignore those directories.   Unfortunately, this puts extra strain on the Perforce server to sync files that are not needed.   It would be great to add support for streams to our Perforce integration at some point in the future.

**Comment by regner** [comment]
Just to add some more info: We don't use streams just because they allow us to limit what gets synced. You can do that with workspace views on a normal depot.

They make it easier to move between branches and do integrations between branches. Basically allowing you to work in a git flow style development more easily.

**Comment by oacnhpkqxjhufwumkkqnshvlmheokqv** [comment]
#23845 should meet the need of filtering out large files from syncing from Perforce, the customer just needs to create a Perforce client spec that filters out these file types or directories (as Perforce client spec views do not yet have an exclusion for file size), then configure the client spec name in the code host config.

See [Exclude files and directories](https://www.perforce.com/manuals/p4guide/Content/P4Guide/configuration.workspace_view.exclude.html).

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.

**Comment by peterguy** [comment]
closing - moving to #50141
