### ISSUE TITLE
Update link for product research signup

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#18567]
On the current product research page, the button to `Sign up now` links to a default Hubspot link. @aileenrose has created a new URL that better conveys our ownership and includes the Sourcegraph logo. 

We need to update the link to instead direct users to: [https://info.sourcegraph.com/product-research](https://info.sourcegraph.com/product-research)

**Comment by umpox** [comment]
This is done: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/user/settings/research/ProductResearch.tsx#L11
