### ISSUE TITLE
Invalid contexts causes weird error message with streaming

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#18576]
Without streaming, I see the "This isn't a valid thing" when using an invalid `context`, but on streaming search:

<img width="1235" alt="Screen Shot 2021-02-23 at 11 18 15 AM" src="https://user-images.githubusercontent.com/888624/108888978-0c4a3c00-75c9-11eb-83d2-8d704b2fda85.png">

[`repo:^github\.com/sourcegraph/sourcegraph$ foo context:asdf`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+foo+context:asdf&patternType=literal&context=global)

**Comment by novoselrok** [comment]
Relevant line: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/search/stream.ts#L454:132

@keegancsmith @limitedmage It seems that this is how we handle all server errors with streaming? Do I need to add anything to properly handle these context errors (either on the frontend or backend)?

**Comment by limitedmage** [comment]
Looks like the backend is returning a string instead of an error-like object:

![image](https://user-images.githubusercontent.com/206864/108892747-1b2eef80-75c5-11eb-96c5-651bce6ad617.png)

I'll modify the backend to return the correctly formatted object.
