### ISSUE TITLE
Investigate k8s errors in logs

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#18583]
From [ops-incident](https://docs.google.com/document/d/1dtrOHs5STJYKvyjigL1kMm6u-W0mlyRSyVxPfKIOfEw/edit?disco=AAAALhj6LVg) 

There are logs in our frontend about k8s watches failing.

**Comment by daxmc99** [comment]
```
{ "error": "k8s client.Watch error: unknown (get endpoints)", "t": "2021-02-21T03:36:09.953025567Z", "endpoint": "/-/debug", "lvl": "warn", "msg": "failed to connect to kubernetes endpoint watcher. Will retry in 5s." }  in cloud logging
```

**Comment by keegancsmith** [comment]
FYI this happened again.

**Comment by daxmc99** [comment]
This has likely been the cause of frequent ops incidents related to `Hard error search responses every 5m`. 
We watch the indexed-search endpoints using `k8s watches`. This is done as a websocket underneath which makes it prone to network instability. We should try to move towards `informers` which utilize cacheing to smooth out brief periods of API inaccessibility (ie cluster upgrades).

**Comment by keegancsmith** [comment]
We didn't rely on informers before. If its an easy change we should switch to them, but maybe there is a more minimal change to do first where we don't hard fail on TCP errors??

**Comment by daxmc99** [comment]
Agreed, this issue should only focus on fixing the nil pointer panics in
prod. I will file another issue to investigate a possible switch to
informers

**Comment by daxmc99** [comment]
The panics in the endpoints package are going to be tracked in this issue https://github.com/sourcegraph/sourcegraph/issues/18913 
I'm considering this issue closed based on this PR 
https://github.com/sourcegraph/sourcegraph/pull/18761
