### ISSUE TITLE
Default context is always set to the user and potentially breaks all existing search URLs

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#18580]
It can be a nice thing to set the default context to the current user, but this also breaks existing search URLs. I believe this behavior is a breaking change. For example, if I previously linked a query somewhere (embedded in a website, like our search docs, saved it in a note, whatever) like:

[`repo:gorilla/mux testroute `](https://sourcegraph.com/search?q=repo:gorilla/mux+testroute)

Then search contexts will automatically apply me as the user, and if I don't have the `gorilla/mux` repo in my context, then it breaks and there are no results (I have to set search to `global`, whereas previously it worked before). Problematically, if I set search to global, the webapp doesn't preserve this setting, so I have to do this each time for the linked URL). 

I am not necessarily proposing that we default to to `global` (although if we don't, then the above is going to potentially break for any existing search query URLs saved somewhere or embedded in a website). I would propose that the app at least remembers that I set `global` if there is no context specified, because otherwise I have to set this each time. If we remember the previous setting in the absence of a context, then the breaking change will only require users to meddle with this once per saved URL, and not for every previously saved URL.

**Comment by rvantonder** [comment]
Via @novoselrok 

> At least for now, search contexts are active only if you have added repositories through code host connections. Otherwise the dropdown is hidden.
We do save the last selected search context (through the dropdown) in the local storage and use it if it is available.

I'm pretty sure the local storage is not kicking in, I'm not able to see that behavior in action.

**Comment by novoselrok** [comment]
> Via @novoselrok
> 
> > At least for now, search contexts are active only if you have added repositories through code host connections. Otherwise the dropdown is hidden.
> > We do save the last selected search context (through the dropdown) in the local storage and use it if it is available.
> 
> I'm pretty sure the local storage is not kicking in, I'm not able to see that behavior in action.

Really weird, do you see any related errors in the console? (And which browser are you using?)

**Comment by rvantonder** [comment]
Here's the reproduction, I change context to global, and it doesn't persist when the URL doesn't contain anything about context.

https://user-images.githubusercontent.com/888624/108904433-b59a2d80-75db-11eb-963e-4283a4ef43cb.mp4

**Comment by rvantonder** [comment]
Nothing in console. On Chrome.

**Comment by novoselrok** [comment]
Fixed via https://github.com/sourcegraph/sourcegraph/pull/20054
