### ISSUE TITLE
Auth docs issues

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#1859]
1. https://docs.sourcegraph.com/admin/site_config/all#gitlabconnection-object mentions `sudo` as a permission type on access tokens on GitLab (no such permission exists), maybe this needs to get removed because the configuration for GitLab is now done in external services, not in the site config
2. https://docs.sourcegraph.com/admin/repo/permissions#gitlab also mentions `sudo`
3. UI alignment looks off: https://docs.sourcegraph.com/admin/repo/permissions

![image](https://user-images.githubusercontent.com/1387653/51092352-14c5bc80-174b-11e9-95f5-946d098ff740.png)

4. Bullet points are not rendering: https://docs.sourcegraph.com/admin/repo/permissions

![image](https://user-images.githubusercontent.com/1387653/51092492-d4673e00-174c-11e9-8580-0d8b19ffe753.png)

5. In https://github.com/sourcegraph/sourcegraph/issues/1861 it wasn't clear to me that the reason why I couldn't access a private repository on the Sourcegraph org was because the Sourcegraph org denies third party oauth apps access to its private repositories.

6. (Copied from https://github.com/sourcegraph/sourcegraph/issues/1864): The page at https://docs.sourcegraph.com/admin/auth, specifically the GitHub and GitLab sections, should link to https://docs.sourcegraph.com/integration/github and https://docs.sourcegraph.com/integration/gitlab, respectively.

**Comment by beyang** [comment]
Fixed by https://github.com/sourcegraph/sourcegraph/pull/1974
