### ISSUE TITLE
structural search returns inconsistent results

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#18594]
[`repo:^github\.com/torvalds/linux$ copy_from_user(:[dst], :[_], sizeof(:[_]) - :[_]) count:30`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/torvalds/linux%24+copy_from_user%28:%5Bdst%5D%2C+:%5B_%5D%2C+sizeof%28:%5B_%5D%29+-+:%5B_%5D%29+count:30&patternType=structural) => 4 results

![Screen Shot 2021-02-23 at 9 12 10 PM](https://user-images.githubusercontent.com/888624/108946602-003b9a00-761c-11eb-9f3f-d473c6e07971.png)

`count:100` or `count:500`: one result.

![Screen Shot 2021-02-23 at 9 13 20 PM](https://user-images.githubusercontent.com/888624/108946593-fd40a980-761b-11eb-867d-0b847f0d44ea.png)

`count:31`: no results.

What gives?

Confirmed with both streaming on and off.

/cc @sourcegraph/search-platform

**Comment by rvantonder** [comment]
Likely cause: `count` affects files returned which affects matcher language. Note how `lang:c` is absent in these.

**Comment by jtibshirani** [comment]
Closing this out since we are not actively investing in structural search.
