### ISSUE TITLE
ExploreRepositories count does not respect repository permissions

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#1860]
- Image `sourcegraph/server@sha256:fc7c6d14bbfe3632ce27bca5b16c2099ea473ede4d03faf246ee22be64e87839` (Jan 13)
- Add a GitHub external service
- Add a GitHub authentication provider https://docs.sourcegraph.com/admin/repo/permissions#github
- Enable a private repository
- Create a new user (this user does not have access to the private repository)
- Visit http://localhost:7080/explore
- Notice that the repository count is actually 1 when I expect it to be 0:

![image](https://user-images.githubusercontent.com/1387653/51092827-d3d0a680-1750-11e9-9a6a-0704ec4ca229.png)

**Comment by chrismwendt** [comment]
Prior to seeing the discrepancy in the count, I get this error:

![image](https://user-images.githubusercontent.com/1387653/51093913-11d3c780-175d-11e9-9ec3-af706d73e8b2.png)

It goes away upon 1 refresh.

When I have 2 repositories that the current user does not have access to, it takes 2 refreshes to disappear.

**Comment by beyang** [comment]
I think the quickest solution here would be to remove the count
