### ISSUE TITLE
Cannot view org private repo when authenticated via GitHub

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#1861]
- Image `sourcegraph/server@sha256:fc7c6d14bbfe3632ce27bca5b16c2099ea473ede4d03faf246ee22be64e87839` (Jan 13)
- Add a GitHub external service
- Add a GitHub authentication provider https://docs.sourcegraph.com/admin/repo/permissions#github
- Enable https://github.com/sourcegraph/dev-private
- Sign in via GitHub as yourself, who has access to the repository
- Visit http://localhost:7080/github.com/sourcegraph/dev-private
- Notice a 404 when I expect to see the repository:

![image](https://user-images.githubusercontent.com/1387653/51092948-881efc80-1752-11e9-817d-9ec5bd7213d7.png)

**Comment by chrismwendt** [comment]
It turns out that GitHub organizations can deny third party oauth apps access to private repositories https://help.github.com/articles/about-oauth-app-access-restrictions/

This is working as expected. I'm adding a note about this to https://github.com/sourcegraph/sourcegraph/issues/1859

**Comment by beyang** [comment]
Closing in favor of item in #1859
