### ISSUE TITLE
Scroll bars are flashing for code insights panels

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#18649]
![cleanshot_2021-02-25_at_00 30 51](https://user-images.githubusercontent.com/2946214/109154264-04e18900-77a9-11eb-9dcc-25b6549d0ebc.gif)

https://sourcegraph.com/github.com/sourcegraph/sourcegraph

I'm on Chrome Version 88.0.4324.192 (Official Build) (x86_64), macOS Big Sur.

It is reproducible for me consistently.

**Comment by Joelkw** [comment]
@unknwon thanks for logging this!

**Comment by vovakulikov** [comment]
Hi @unknwon it seems like this problem has been fixed by PR https://github.com/sourcegraph/sourcegraph/pull/19556 

I can't reproduce this right now, when you got a moment check code insights, just to double-check we don't have this problem anymore and we can close this issue, thanks.

**Comment by unknwon** [comment]
@vovakulikov Thanks, looking really nice now! Confirmed fixed.
