### ISSUE TITLE
srcimage: Create a tool for updating docker images

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#18651]
As part of the Deployment UX project, we need a tool that can handle updating a docker image given a git SHA1 commit. 

Repo for tool: https://github.com/sourcegraph/distribution-tools
Design doc: https://docs.google.com/document/d/1IohtPWJicyg-0sydCblO-25JHm3LwP0yIxopI4x-AqQ/edit#heading=h.7ozmgygojgzt 

Basic specification:
- This tool should take an image as input `registry/image:tag` (or similar) and an old image to replace in some files
- Given a `registry/image:tag`, it should find the most up-to-date image and digest.
- Given some collateral YAML files, it should update the docker images in those YAML files.
- Stretch: `--dryRun` mode that outputs the replaces

Outcome:
- A composable tool that allows us to replace the image updating functionality of renovate 
- This issue is only for the creation of this tool, integration will be tackled in a separate issue. 

## Notes:
- We have already used the docker-cli image digest parsing libraries in https://sourcegraph.com/github.com/sourcegraph/ds-to-dhall@main/-/tree/dockerimg.
- We should leverage https://github.com/slimsag/update-docker-tags

**Comment by daxmc99** [comment]
Overall workflow:

1. Given some image (index.gcr.io/demo:243add_0102_123) 
2. This uses the tag format from ${SHORT_SHA}_${DATE}_${BUILD_NUMBER}
3. Find this image in the given YAML
4. Update this image to the new tag in the given YAML

**Comment by pecigonzalo** [comment]
I reckon `${SHORT_SHA}${DATE}${BUILD_NUMBER}`'s format will end not mattering as given either:
- `index.gcr.io/demo:243add_0102_123` is the "image to be replaced" and you already have its full name minus the SHA
- `index.gcr.io/demo:243add_0102_123` is the "image to replace with" and you can replace all images that are `index.gcr.io/demo:.+` (pseudo regex) for the most part.
