### ISSUE TITLE
Changing theme resets line decorations

### ISSUE THREAD

**Issue by muratsu** [sourcegraph/sourcegraph#18673]
- **Sourcegraph version:** 3.25
- **Platform information:** Linux, Chrome

#### Steps to reproduce:

1. Enable git blame plugin
2. Navigate to a file
3. From drop down change the theme a bunch of times

#### Expected behavior:
1. The line decorations to persist

#### Actual behavior:
1. The line decorations dissapear

A visual repro: 
![bug](https://user-images.githubusercontent.com/1308560/109240201-ede06e00-778b-11eb-88d5-28c4b6dc15d7.gif)

**Comment by tjkandala** [comment]
Fixed by #18898
