### ISSUE TITLE
Hover tooltip shows up seemingly randomly

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#18681]
I recorded the following video **after** the hover for `ioutil.TempFile` showed up and then disappeared. I opened the console's network tab to see if I can debug this (not remembering that the extension doesn't log in there).

If you watch the video you'll see me trying to get the hover over `ioutil.TempFile` to show up again. It doesn't until 24s in the video when it shows up again:

https://user-images.githubusercontent.com/1185253/109282674-216bd880-781e-11eb-842e-e08ca4bbb69f.mp4

I've ran into variations of this a lot in the past and it's really frustrating because it gives me the feeling that I can't rely on hover tooltips to show up.

@scalabilitysolved assigning this to you, feel free to reassign.

**Comment by scalabilitysolved** [comment]
Hey @macraig I was also able to recreate this issue, seems like something we should look to fix in the next iteration if possible.  Do you have any additional context or reports of this in the past?

**Comment by macraig** [comment]
@scalabilitysolved we had similar "Hovers sometimes don't show up" last year. This closed [issue](https://github.com/sourcegraph/sourcegraph/issues/13802) might be related, we did a short debugging session and closed it but I think given the context at that time we should revisit it. 

Something to keep in mind is that we need to identify if this is actually on the code intel or the extensibility side, but I'd prioritize digging into what's causing this either way.

**Comment by efritz** [comment]
Could this just be a stuck/very slow request finishing after several others are fired off and return?

**Comment by mrnugget** [comment]
Not sure. What's the easiest way to see if that's the cause when it's happening?

**Comment by efritz** [comment]
@mrnugget Did we find the source of this (is it related to the extension host issue with folded documents on GitHub)?

**Comment by mrnugget** [comment]
Reasonably sure by now that it's https://github.com/sourcegraph/sourcegraph/issues/18337 but not 100%.

**Comment by scalabilitysolved** [comment]
It seems this was resolved in [#18337](https://github.com/sourcegraph/sourcegraph/issues/18337)
