### ISSUE TITLE
Code search tour jumps from step 2 to 5

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#18683]
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:** macOS, Safari

#### Steps to reproduce:

1. Open sourcegraph.com with empty local storage
2. Click in search field
3. See tooltip to search for a language
4. type in `lang:rust` and **hit return** (because this is what I assumed I should do)

#### Expected behavior:

I continue the code search tour

#### Actual behavior:

Code search tour jumped from step 2 to 5.

---

See the video

https://user-images.githubusercontent.com/1185253/109284627-5c6f0b80-7820-11eb-9f5f-b67629e81d56.mp4

**Comment by lguychard** [comment]
@novoselrok the search tour has changed quite a bit since this was opened. Is it still relevant?

**Comment by novoselrok** [comment]
I don't think so, since the search does not appear on the search results page anymore.
