### ISSUE TITLE
Subrepositories in file tree are right-aligned

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#18684]
- **Platform information:** 

#### Steps to reproduce:

1. Go to https://sourcegraph.com/github.com/rust-lang/rust/-/tree/library
2. Expand the `library` folder

![screenshot_2021-02-26_12 17 12@2x](https://user-images.githubusercontent.com/1185253/109293989-e02ef500-782c-11eb-9903-787d8653a87f.png)

It looks weird. Not sure if this is intended or not. It definitely looks like a bug though.

**Comment by umpox** [comment]
I think this is a regression from https://github.com/sourcegraph/sourcegraph/pull/15833

**Comment by felixfbecker** [comment]
cc @tjkandala

**Comment by umpox** [comment]
This seems to be fixed! 

<img width="379" alt="image" src="https://user-images.githubusercontent.com/9516420/177189880-ae4b9cae-8098-429f-88de-83e8a8937959.png">
