### ISSUE TITLE
insights: frontend: need indicator if backend is populating historical data or not

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#18708]
As the backend walks slowly back in time and looks for data, there are a few states that the frontend could render better:

1. Directly after adding an insight, there may be no data points. Currently the display for this is quite ugly (empty chart, looks broken:

<img width="1170" alt="image" src="https://user-images.githubusercontent.com/3173176/109358075-69035c00-7840-11eb-8845-dbf0a390eded.png">

2. We may also have only a single data point for an extended period of time. For example, if the data backfiller is hard at work on other series, it may not get to yours for a few hours or so. In this case, you'd be stuck looking at the singular data point that the regular worker records every 12h:

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/3173176/109358678-605f5580-7841-11eb-9720-b09b823c8b83.png">

3. As historical data is being found, it does so repository-by-repository. This means that the oldest data point returned may be _incomplete_. For example, if looking at this global view, the 10/13 data point is incomplete - one option is for the backend to not return this, another option is for the frontend to warn the user that it is an incomplete data point (always the oldest iff historical data is being built still):

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/3173176/109358947-d8c61680-7841-11eb-921d-9c37f6b2473f.png">

TODO:

* Decide exactly what we want to display here on the frontend.
* Expose this type of "loading" / "progress" information from the backend.

**Comment by Joelkw** [comment]
@AlicjaSuska given Stephen's [comment here](https://github.com/sourcegraph/sourcegraph/issues/19537#issuecomment-812261524) and the fact that I know you're extra busy with the refresh + create code insight UI, would you be okay if we wanted to put up a temporary version that just exposed some information and we can otherwise fix/redo it if we need to later?

**Comment by coury-clark** [comment]
Related #22931

**Comment by unclejustin** [comment]
@AlicjaSuska I'm going to need some design support here, but I'm unsure what to even ask for yet. We need some way to indicate to the user that some of the data is still pending. I'm thinking maybe an icon with a tooltip? But where? And I'm not sure how obvious we need to make it.

Off the top of my head maybe an hourglass next to the card title? 🤷
