### ISSUE TITLE
GraphQL DeleteExternalService query takes ~20 seconds or returns 5XX errors

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#18730]
### Problem

Hallway testing for Cloud revealed that when removing code host connections, it hangs badly. `DeleteExternalService` requests take ~20 seconds or 502.

### Steps to reproduce

In Admin API:

0. Make sure your user has `allowUserExternalServicePublic` tag set

1. Get an ID for existing external service
```js
// Query
query ExternalServices($first: Int, $after: String, $namespace: ID) {
  externalServices(first: $first, after: $after, namespace: $namespace) {
    nodes {
      ...ListExternalServiceFields
    }
  }
}
fragment ListExternalServiceFields on ExternalService {
  id
  kind
  displayName
  warning
  lastSyncError
}

// Variables
{"user": "<your user id>", "first": 1}
```
2. ⚠️  Delete external service 🐢 
```js
// Query
mutation DeleteExternalService($externalService: ID!) {
  deleteExternalService(externalService: $externalService) {
    alwaysNil
  }
}

// Variables
{"externalService": "<your external service id>"}
```

### Screenshots

**Admin API**
<img width="1792" alt="Admin API" src="https://user-images.githubusercontent.com/1319181/109255750-9d383780-77c2-11eb-9828-89e84303cc57.png">

**Request from React component**
![dotcom page](https://user-images.githubusercontent.com/1319181/109255855-c789f500-77c2-11eb-92c4-c796dae30be1.png)

**502**
![Screen Shot 2021-02-26 at 12 28 43 AM](https://user-images.githubusercontent.com/1319181/109259148-9eb92e00-77c9-11eb-897c-42ed1f5ae73a.png)

**Comment by ryanslade** [comment]
Fixed 😄 

<img width="999" alt="Screenshot 2021-03-30 at 14 58 50" src="https://user-images.githubusercontent.com/25610/112992517-86418800-9168-11eb-85b1-7c51c438555c.png">

Basically all of that 300ms is the latency from South Africa 😄 

cc @asdine
