### ISSUE TITLE
GitHub code host doesn't report problems when adding invalid tokens 

### ISSUE THREAD

**Issue by artemruts** [sourcegraph/sourcegraph#18740]
### Problem

When adding invalid tokens (think `bla-bla-42`) for GitHub code host, backend reports code host as successfully added.
GraphQL mutation is `AddExternalService`.
____
Based on the architecture, I'd guess this happens due to indirection and throttling @ [github-proxy](https://github.com/sourcegraph/sourcegraph/tree/main/cmd/github-proxy) and the errors will be eventually reported when code hosts starts to sync. 

### Steps to reproduce

0. Make sure your user has `allowUserExternalServicePublic` tag set
1. Navigate to code host connections page `https://sourcegraph.com/users/<your user>/settings/code-hosts`
2. Open Browser DevTools and monitor network
2. Add `bad-token` personal access token to GitHub code host connection
3. Examine `200` response from https://sourcegraph.com/.api/graphql?AddExternalService, it will have `warning` and `lastSyncError ` set as `null`
4. ⚠️   Instead we should have `warning` or `lastSyncError` have an error message. 

### Screenshots

<img width="1790" alt="Screen Shot 2021-03-01 at 11 33 32 AM" src="https://user-images.githubusercontent.com/1319181/109528038-4b253980-7a82-11eb-9c3e-14735bbef7d4.png">

**Comment by indradhanush** [comment]
### Issue related discoveries and questions

@artemruts , I paired with @asdine on this today and in an effort to reproduce the issue we found that the `warning` field is populated for a request with an invalid token:
![s_2021-03-24_182356](https://user-images.githubusercontent.com/2682729/112338864-2882eb00-8ce5-11eb-87a4-36ed0bc5b999.png)

This seems to be the point where the frontend monolith code injects the warning into the response: https://github.com/sourcegraph/sourcegraph/blob/f7ee6671e2d9f4aaf544bb9b3a94347e284dd4b7/cmd/frontend/graphqlbackend/external_services.go#L90-L93

Having said that, there is indeed an edge case where the response silently ignores the error and doesn't set any value to either `warning` or `lastSyncError`. Let us go deeper down the call stack, the definition of `syncExternalService`:

https://github.com/sourcegraph/sourcegraph/blob/f7ee6671e2d9f4aaf544bb9b3a94347e284dd4b7/cmd/frontend/graphqlbackend/external_services.go#L161-L184

In this function we set a 5 second deadline for the function to complete on line 164.

Now, the error handling for `repoupdater.DefaultClient.SyncExternalService` in line 179 is partially incomplete that is `syncExternalService` only returns an error if the `repoupdater.DefaultClient.SyncExternalService` returns an error. But if ignore the case when the `repoupdater.DefaultClient.SyncExternalService` does not return an error but `ctx.Err()` does. That is either the function exceeding the deadline limit or someone calling `cancel` on the context.

@artemruts When you encountered the issue, could it have been that the code took the path of this edge case? We took a closer look at your screenshot and is the big green chunk under `10000ms` an indicator of the time this request took to be completed? :thinking: 

Additionally, if you are also able to reproduce our findings where `warning` is already populated for invalid tokens, do you still require `lastSyncError`? (Personally I think populating `warning` and hiding the error is not ideal but there is a good chance I do not have the complete context on this.) 

### API redesign proposal

This might warrant a new issue altogether, but we felt it would be easier to continue the discussion here with the above context in mind.

At the moment, the lowest level API responsible for returning a success / failure response is the `/sync-external-service` handler:
https://github.com/sourcegraph/sourcegraph/blob/f7ee6671e2d9f4aaf544bb9b3a94347e284dd4b7/cmd/repo-updater/repoupdater/server.go#L334-L346

And a quick peek inside the `externalServiceValidate` function which is called from the above handler reveals that we make an API call to "list repos" based on the code host's configurations:
https://github.com/sourcegraph/sourcegraph/blob/f7ee6671e2d9f4aaf544bb9b3a94347e284dd4b7/cmd/repo-updater/repoupdater/server.go#L401-L404

This has the potential to be a rather "heavy" API call based on the code host's config and what's at the end of the API call for each code host. Additionally, we also end up ignoring the API results here: https://github.com/sourcegraph/sourcegraph/blob/f7ee6671e2d9f4aaf544bb9b3a94347e284dd4b7/cmd/repo-updater/repoupdater/server.go#L406-L416

We propose a modification to this by adding a new interface: `SourceValidator` that has a `Validate` method. Each source can implement this and add its own logic to make a light API call to verify if the API keys are valid or not. Additionally we can add a small `if-else` check to make this change as smooth as possible:

```
if _, ok := src.(SourceValidator); ok {
    if _, err := src.Validate(); err != nil {
        return err
    }
} else {
    // Existing code to list repos in a goroutine and then handle the success / response accordingly
    ...
    src.ListRepos()
    ...
}
```

We could ship this without implementing the `SourceValidator` interface in any of the code host implementations and eventually implement them one at a time over small iterations. And finally when all the code host's have implemented the `SourceValidator` interface we can remove the code for `ListRepos`.

What do you think? 

cc: @arussellsaw, @ryanslade, @tsenart

**Comment by ryanslade** [comment]
Nice, I like the sound of this. 

@arussellsaw and I are going to be pairing on this endpoint in a couple of hours and we'll keep this change in mind as we dig in. We're specifically looking at it from the angle of https://github.com/sourcegraph/sourcegraph/issues/19235 to see if changing the API could lead to a better long term fix than we we did [here](https://github.com/sourcegraph/sourcegraph/pull/19417)

**Comment by unknwon** [comment]
Nice writeup!! @indradhanush
