### ISSUE TITLE
Add UI option to enable an extension for all users

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#1874]
Reading through https://sourcegraph.com/extensions/sourcegraph/basic-code-intel#usage, it struck me that there was no toggle to enable this for all users (even as an admin on my own instance).

There's also no explanation for HOW to enable it for all users/the whole instance in the readme or the UI. 

If a user is an admin, there should be a 2nd toggle beneath the first one for whether to enable for all users on the instance (along with a link to docs for how to enable for orgs). The 2nd toggle would be disabled entirely if the first wasn't selected.

E.g.

![image](https://user-images.githubusercontent.com/5589410/51131248-0d9ebd00-17e4-11e9-89eb-c3e1b8da8b88.png)

**Comment by francisschmaltz** [comment]
@lguychard can we hit 3.0 with this?

**Comment by sqs** [comment]
No, 3.0 will not add new features beyond 3.0 beta. This is important to ensure 3.0 is stable. I would love to add this feature, but it's not worth the risk to stability of 3.0.

I did document adding it to global settings at https://docs.sourcegraph.com/extensions#for-organizations (enabling an extension for all members of an org was already documented here). It is also documented on the extension registry doc page. And this makes me feel comfortable that this would not be a blocker for a user:

![screenshot from 2019-01-14 15-56-56](https://user-images.githubusercontent.com/1976/51148996-1360c680-1815-11e9-94d6-9fa5dffdb7f3.png)

**Comment by sqs** [comment]
Basic proposal: add a gear icon (next to the enable/disable slider) that shows the following dropdown menu:

- Enable/disable for all users
- (divider)
- Enable/disable for org1
- Enable/disable for org2
- Enable/disable for orgN

Notes:

- The "Enable/disable" would be the correct word based on the current enabled state for the subject.
- Only authenticated users would see the gear icon.
- If the user is not in any orgs, the bottom section of the dropdown would say "No organizations to enable for" (better copy is welcomed)
- If the user is not a site admin, then the top section (the divider and above) would not be shown

**Comment by dadlerj** [comment]
Reported by https://app.hubspot.com/contacts/2762526/company/2243289985

**Comment by Joelkw** [comment]
@lguychard was there a reason this never got started or did it just get deprioritized? (Assuming the latter but wanted to make sure.) If just deprioritized, please feel free to untag yourself and the web team can take it forward (at some point) from here!

**Comment by felixfbecker** [comment]
@Joelkw I think this needs a design. @AlicjaSuska did you ever think about this as part of your design for the extension activation toggle?

**Comment by Joelkw** [comment]
(Yep, it's tagged need-design and left that on there intentionally.)
