### ISSUE TITLE
Consider moving to informers from watchers

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#18753]
We currently use k8s watchers
https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/internal/endpoint/endpoint.go#L180 

We should consider replacing these with informers

**Comment by daxmc99** [comment]
@sourcegraph/core-application or @sourcegraph/search, any appetite to take this on? 
Happy to pair to help out on this

**Comment by unknwon** [comment]
Any docs for differences between a k8s watcher vs informer? Seems like a nice chance for pairing.

**Comment by daxmc99** [comment]
https://stackoverflow.com/questions/59544139/kubernetes-client-go-watch-interface-vs-cache-newinformer-vs-cache-newsharedi#:~:text=Informers%20is%20a%20higher%20level,and%20an%20in%2Dmemory%20cache.

This provides a high-level overview. While I believe the actual method may have changed this is a general idea. An informer would bundle a lister, a watcher and an in-memory cache. 

Happy to pair on this!
