### ISSUE TITLE
Rename campaigns to batch changes

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#18771]
Context: [RFC 320](https://docs.google.com/document/d/1GiirRL99dHkoNMU0m3_-jiyrGU0c62ANbJcsgBasAUA/edit)
Timeline: [Name change timeline](https://docs.google.com/document/d/1iFVhpC8d9eMkLkV7ME5a3oB43q-EurKt4Eof2uvol_c/edit)

### Plan

Start with user-visible things (API, content, docs, URLs) and end with implementation "details" (Go package name, directory names, database table names).

**Why**? Avoids rebasing problems as long as possible and gets the critical must-be-done stuff done first.

### Open Questions

- [ ] Do we do this in one PR? Or multiple?

#### `sourcegraph/sourcegraph`

- [x] Deprecate old GraphQL entities (`Campaign` and `CampaignSpec`, `CampaignsCodeHosts`) and their queries & mutations. Add `BatchChange` and `BatchSpec` entities, mutations, queries. **PR: https://github.com/sourcegraph/sourcegraph/pull/18734**
    - [x] In Go `graphqlbackend` package: rename GraphQL resolvers from `CampaignsResolver` to `BatchChanges` resolver
    - [x] In Go `enterprise/internal/campaigns/resolvers` package: rename `campaignsResolver` to `batchChangesResolver` and same for `BatchSpec`.
- [x] Rename Go package `campaigns` to `batchchanges` **PR:** https://github.com/sourcegraph/sourcegraph/pull/18855
- [x] Change URL generation **PR**: https://github.com/sourcegraph/sourcegraph/pull/18859
    - [x] In [reconciler here](https://github.com/sourcegraph/sourcegraph/blob/bb2fcfe81d79b815c395b413691283aca4f56164/enterprise/internal/campaigns/reconciler/executor.go#L687-L706)
    - [x] In [resolvers here](https://github.com/sourcegraph/sourcegraph/blob/bb2fcfe81d79b815c395b413691283aca4f56164/enterprise/internal/campaigns/resolvers/urls.go#L7-L14) 
- [x] **WIP** Rename Go types `Campaign` and `CampaignSpec` https://github.com/sourcegraph/sourcegraph/pull/18864
- [x] Use new GraphQL names in `web` code
- [x] Change `web` **views** to use "batch change" and "batch spec" wording
- [x] Change `web` **views** to use new src-cli commands
- [x] Change `Batch changes` to `Batch Changes` in web
- [ ] Fix in-app docs links
- [x] Redirect `/<org-or-username>/campaigns` to `/<org-or-username>/batch-changes`
- [x] **WIP @malomarrec** Move `doc/campaigns` to `doc/batch-changes` **PR** https://github.com/sourcegraph/sourcegraph/pull/18854
    - [x] Redirect `docs.sourcegraph.com/campaigns` to `docs.sourcegraph.com/batch-changes` (see `doc/_resources/assets/redirects)
    - [x] Add redirect for the pages that have "campaigns" in their name: `campaign_spec_yaml_reference`
    - [x] Move `doc/dev/background-information/campaigns` to `doc/dev/background-information/batch-changes`
    - [x] Redirect `docs.sourcegraph.com/dev/background-information/campaigns` to `docs.sourcegraph.com/dev/background-information/batch-changes` (see `doc/_resources/assets/redirects)
    - [x] Change the content
- [x] site config options: [see here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@f134e4efb416733415765b4fb31a64402a70da74/-/blob/schema/schema.go?subtree=true#L1306-1310)
    - [x] `campaigns.enabled`
    - [x] `campaigns.restrictToAdmins`
    - [x] `campaigns.readAccess.enabled` (since it's deprecated anyway: remove?)
    - [x] Wrapper function [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@f134e4efb416733415765b4fb31a64402a70da74/-/blob/internal/conf/computed.go?subtree=true#L222-227)
    - [x] Usage here: [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@f134e4efb416733415765b4fb31a64402a70da74/-/blob/enterprise/internal/batches/resolvers/resolver.go?subtree=true#L43-56)
    - [x] Also, see [these validators here](https://github.com/sourcegraph/sourcegraph/blob/fd38b9c508759b9de4d0fa71e7639f0e9117a64a/internal/batches/config.go#L8-L20)
- [x] errors: ErrCampaignsDisabled etc. in the resolvers: [see this file](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@f134e4efb416733415765b4fb31a64402a70da74/-/blob/enterprise/internal/batches/resolvers/errors.go?subtree=true#L7)
    - [x] we need to wrap those and return the Campaigns version when a campaigns mutation was used and a batchchange version when not
    - **UPDATE**: @mrnugget and @eseliger discussed this and didn't think this was worth it, since the only place where these errors could show up is in the src-cli where `campaign` commands have been deprecated anyway.
- [x] Licensing PR: https://github.com/sourcegraph/sourcegraph/pull/18983
    - [x] [`FeatureCampaigns`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@f134e4efb416733415765b4fb31a64402a70da74/-/blob/enterprise/internal/licensing/data.go?subtree=true#L43-44) needs to be an alias
    - [x] Introduce `FeatureBatchChanges`
- [x] Rename database table and foreign keys
    - [x] UserCredentials "domain" is currently `"campaigns"`
- [x] Add changelog entry 
- [x] Regenerate docs for src-cli in `doc/cli/references` #18799
- [x] Rebase and update `usagestats` PR https://github.com/sourcegraph/sourcegraph/pull/18604
- [x] Rebase and update `analytics` PR https://github.com/sourcegraph/analytics/pull/109

#### `sourcegraph/src-cli`

- [x] Introduce aliases for `src batch apply` #18940

#### Misc

- [x] Not sure: rename repos https://k8s.sgdev.org/search?q=campaign+type:repo&patternType=literal

**Comment by mrnugget** [comment]
Playbook for how to migrate GraphQL that I've used:

1. Open `./cmd/frontend/graphqlbackend/campaigns.go`
2. Look at `CampaignsResolver` to see which mutations/queries are marked as "to-be-deprecated"
3. Pick a mutation/query to rename/duplicate. Example: `CloseCampaign`
    - Create a copy, call it `CloseBatchChange`
    - See if you can reuse the args struct, `*CloseCampaignArgs`, or whether it has
      campaigns-specific arguments in it. In this case it has: `Campaign
      graphql.ID`.
    - Create a copy of the arg, rename `Campaign` in the args to `BatchChange`
    - Mark the old args struct as deprecated by adding `// TODO(campaigns-deprecation)`
    - Use the new args in the new mutation/query
    - Make sure that the old query/mutation also returns the new types (`BatchChangeResolver`) to reuse the same resolvers/interfaces to act as `Campaign` and `BatchChange`
4. Add the new mutation/query to the `defaultCampaignsResolver`
    - Mark the old one as deprecated too
5. Open `./enterprise/internal/campaigns/resolvers/resolver.go` to add the new mutation/query (or any other file in the `resolvers` folder)
    - Copy the old one and give it the new name
    - Use the new args in the new mutation/query
    - Change the old one to call the new one under the hood, rewriting the args, like so:
      ```go
      // OLD:
      func (r *Resolver) CloseCampaign(ctx context.Context, args *graphqlbackend.CloseCampaignArgs) (_ graphqlbackend.BatchChangeResolver, err error) {
        return r.CloseBatchChange(ctx, &graphqlbackend.CloseBatchChangeArgs{
          BatchChange:     args.Campaign,
          CloseChangesets: args.CloseChangesets,
        })
      }

      // NEW:                 new name                                       new args
      func (r *Resolver) CloseBatchChange(ctx context.Context, args *graphqlbackend.CloseBatchChangeArgs) (_ graphqlbackend.BatchChangeResolver, err error) {
        tr, ctx := trace.New(ctx, "Resolver.CloseBatchChange", fmt.Sprintf("BatchChange: %q", args.BatchChange))
        // [...] use new args
      }
      ```
6. Run the tests for the resolvers: `go test ./enterprise/internal/campaigns/resolvers`
    - Fix compilation errors & fix tests
    - **IMPORTANT**:
        - Tests might still work, because we are backwards incompatible. But it's important that our tests use the new API. We manually test the backwards-compatibility with src-cli.
        - Tests might break because the mutations/queries use the old names and then the JSON unmarshalling of the GraphQL response "silently" fails. Make sure to rename the variables/query/mutation names *in the strings*.
        - Especially check the `permissions_test.go` file

**Comment by LawnGnome** [comment]
_whistling, going through GitHub notifications_

![image](https://user-images.githubusercontent.com/229984/110389832-ef2a5a00-8019-11eb-8f8c-73d62d502a3b.png)

Bah. Sorry.
