### ISSUE TITLE
I see searches that aren't mine.

### ISSUE THREAD

**Issue by Andoryuuta** [sourcegraph/sourcegraph#188]
![image](https://user-images.githubusercontent.com/8594162/46325566-b74b9c80-c5ad-11e8-8922-4b0f992753e4.png)

Brand new test account.

**Comment by sqs** [comment]
It was showing saved searches that accidentally got added to global settings. I just removed those.

Assigning to @beyang to verify fixed.

**Comment by beyang** [comment]
Fixed for me.
