### ISSUE TITLE
Improvements around issue-management for frontend-plaform team

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#18831]
We use Github projects combined with Google docs to manage our backlog and plan our iterations.

🚀 [Current iteration board](https://github.com/orgs/sourcegraph/projects/144)
🪲 [Issue backlog board](https://github.com/orgs/sourcegraph/projects/117)
📝 [Iteration planning Google Doc](https://docs.google.com/spreadsheets/d/1CfOE7BpDgvnxtIJxw4g8DOwCBz8KKYmuDl8920vOsAk/edit#gid=1603557743)

# Issues

### Description:
It's not possible to comment on cards in Github projects. That's why we use Google Docs for iteration planning where we can easily discuss issues. It's frustrating because we don't have one source of truth, and we need to switch between different tools.

The ideal workflow would be:

1. Have prioritized, discussed backlog before the beginning of each iteration.
2. If not enough items in the backlog -> add them in an async manner or schedule a grooming call.
2. Pick items from the backlog to the current iteration.
3. At the end of the iteration, archive all `Done` cards and start over.

### Solution
@5h1rU: Convert each card into Github issue and keep communication there instead of planning in Google docs.

--------------------------

Note:
@sourcegraph/frontend-platform add more discussion points here 👆

**Comment by umpox** [comment]
@valerybugakov Are you happy to close this issue now we have updated our team process in [this PR](https://github.com/sourcegraph/about/pull/2784/files#diff-bf4678ed7b4c337f62c6b2a44d0d04df160f06784279bdd6a2069493b08f3ad7R70)?

**Comment by valerybugakov** [comment]
Yes, we can open it later if we find new topics to discuss.
