### ISSUE TITLE
Ensure containers (specifically gitserver) have consistent sourcegraph uid/gid by allocating specific ones

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#1884]
When using gitserver as a non-root user, you often need to provide .ssh credentials in `/home/sourcegraph/.ssh` -- but if your host volume mounted is owned by root, the `sourcegraph` user in the container cannot access it. The solution is to change the owner to the UID/GID of the `sourcegraph` user by running this on the host:

```bash
$ sudo chown -R 100:101 ~/my-sourcegraph-ssh-config/.ssh
```

But this means relying on stable UID/GIDs in our container. Currently, they are stable just due to the nature of addgroup/adduser execution order in our Dockerfile. However, we could improve this by ensuring we always allocate UID/GID 100/101 to be more explicit about it and ensure we don't regress on this.

**Comment by ggilmore** [comment]
cc @ggilmore

**Comment by slimsag** [comment]
@ggilmore did you mean to mention someone else or assign yourself?

**Comment by ggilmore** [comment]
No, I just wanted to have this issue in my email notifications for reference

**Comment by slimsag** [comment]
Since the implicit user creation order does ensure this is stable, it is OK if this doesn't land in 3.0 BUT it would be really good to have it land in 3.0. This is about as close as you can get to a release-blocker issue without it being one.

I'll try to implement this soon.
