### ISSUE TITLE
"nginx: [alert] could not open error log file: open() "./logs/error.log" failed" on Server instance

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#1886]
When I run the command from our docs to run Sourcegraph Server, I see at the top of the output logs:

```
23:25:47              nginx | nginx: [alert] could not open error log file: open() "./logs/error.log" failed (2: No such file or directory)
```

Full logs: https://gist.github.com/slimsag/bfc295bac77d136208be33883813b1f8

**Comment by chrismwendt** [comment]
Other people say this can be ignored https://stackoverflow.com/a/39124579/2061958

**Comment by slimsag** [comment]
It looks like an error, so at the very least we should suppress it. Otherwise I would complain about it via support.
