### ISSUE TITLE
Investigate improving build times with esbuild

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#18863]
#### Feature request description
[Esbuild](https://github.com/evanw/esbuild)

We should investigate if this can help us improve our build times for the webapp.

[Related webpack loader](https://github.com/privatenumber/esbuild-loader)

**Comment by umpox** [comment]
Note: As we're likely not going to work on this in the immediate future, I'm just attaching a branch where I did a quick investigation into using [esbuild-loader](https://github.com/privatenumber/esbuild-loader).

Branch is here: https://github.com/sourcegraph/sourcegraph/compare/main...esbuild-loader

With webpack/terser/babel the build takes around **2 minutes**. Using `esbuild-loader` we can cut this down to around **30 seconds**.

We would be able to get even better performance entirely by fully moving to `esbuild` but this could be a good step if we rely on certain Webpack plugins.

**Comment by fkling** [comment]
We are now using esbuild and are experimenting with vite ;)
