### ISSUE TITLE
Onboarding R.H.

### ISSUE THREAD

**Issue by stefanhengl** [sourcegraph/sourcegraph#18899]
### Week 1

Go through [General Onboarding](https://about.sourcegraph.com/handbook/people-ops/onboarding#for-all-new-teammates) and [Engineering Onboarding](https://about.sourcegraph.com/handbook/engineering/onboarding#engineering-onboarding).

- [ ] Schedule a backend development introduction session with your on-boarding buddy (or someone else on your team).
- [ ] Schedule 1:1s with everyone else on your team to get to know them and what they're working on.
- [ ] Setup a (potentially recurring) pairing session with your on-boarding buddy or someone else on your team. This will help you get up to speed faster on your first tasks.

### Week 2 - 3

Get started with one of the task below. The tasks are in no particular order. You should pick one or more that pique your interest.

##### Small
- [ ] Support recursive matching for `search.LargeFiles` (see [#224](https://github.com/sourcegraph/customer/issues/224))
- [ ] Minimal HTML/JS frontend to search for Sourcegraphers to use. (lots of debug output included/etc, no flourishes).

##### Medium
- [ ] Star ranking in Zoekt: The idea is to teach Zoekt about external ranking signals. Github stars are a simple proxy for importance and we could let Zoekt loop over shards in the order of their importance. This would immediately improve user experience.
- [ ] Zoekt's regex engine uses substring positions to start search at: This is an interesting follow-up to [this performance optimization we did last year](https://github.com/google/zoekt/commit/9b867fb6188e91f3b2cd04921acc919f648a4152): The idea is to tell the regex engine which lines to search in those documents we didn't skip. It would be a nice side-project to add reproducible benchmarks to zoekt so that we can better evaulate the impact of our changes.

##### Large
- [ ] Make Zoekt's trigram map live on disk: This is part of our effort to increase the number of repositories we index, see [this discussion](https://sourcegraph.slack.com/archives/CHPC7UX16/p1611183485070100) for more context.
- [ ] Green field work on fast diff/commit search: Our [diff/commit search is currently limited to 50 repos](https://sourcegraph.com/search?q=panic+type:diff+&patternType=literal) and doesn't scale well. On our long term roadmap is the idea to find/integrate/build an indexed diff/commit backend that is performant at a scale of 5 mil repos. The point of this task is not necesarily to build such a backend from scratch, but rather to prototype/evaluate several ideas and identify the best way forward.

**Comment by tsenart** [comment]
@stefanhengl: I think that latest version of our architecture docs do a pretty good job of explaining the high level so I don't think it's as useful for me to keep doing these intro sessions. I do recommend, however, that someone else on the search team does a deep dive into the search architecture in specific. Also, a few more recommended week 1 items:

- [ ] Schedule a backend development introduction session with your on-boarding buddy (or someone else on your team).
- [ ] Schedule 1:1s with everyone else on your team to get to know them and what they're working on.
- [ ] Setup a (potentially recurring) pairing session with your on-boarding buddy or someone else on your team. This will help you get up to speed faster on your first tasks.

**Comment by stefanhengl** [comment]
@tsenart thanks for the input, much appreciated!

**Comment by stefanhengl** [comment]
cc @lguychard
