### ISSUE TITLE
Unable to load symbols for brave/brave-core

### ISSUE THREAD

**Issue by pdubroy** [sourcegraph/sourcegraph#18901]
- **Sourcegraph version:** "Sourcegraph.com"
- **Platform information:** N/A

#### Steps to reproduce:

1. Go to code.brave.com (redirects to https://sourcegraph.com/github.com/brave/brave-core)
2. Click on "Symbols"

#### Expected behavior:

I see the list of symbols, or an error message that is uses language that I understand.

#### Actual behavior:

<img width="494" alt="Screenshot 2021-03-05 at 09 54 08" src="https://user-images.githubusercontent.com/17293/110092808-49b58300-7d9a-11eb-97b7-273923992eb7.png">

#### Other notes:

I can't reproduce the issue anymore, so it may have been a transient connectivity issue.

**Comment by mrnugget** [comment]
cc @sourcegraph/distribution @sourcegraph/core-application This seems to be due to a gitserver deployment.

I know that `gitserver` is stateful and zero-downtime deploys are hard with that, but wrapping the error message would at least be better.

**Comment by tsenart** [comment]
@asdine: I think we can make the error message friendlier before we tackle https://github.com/sourcegraph/sourcegraph/issues/16577. @quinnkeast: Any tips on what a good user friendly error message would be?

**Comment by quinnkeast** [comment]
The title of this issue does a really good job of capturing the issue, so we can probably work off of that. What's the possible action users can take? Refreshing? If so, something like this would work:

>Unable to load symbols
>[Refresh](#) to try loading symbols again

**Comment by unknwon** [comment]
So... since it is assigned to be, and I have a little thinking already. In such cases, I think the backend should return 503, and the frontend should prompt user to refresh.

**Comment by beyang** [comment]
This works for me now, okay to close?

**Comment by daxmc99** [comment]
Feature work is tracked in https://github.com/sourcegraph/sourcegraph/issues/16577 
From @sourcegraph/distribution we deploy our [statefulsets](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/deploy-sourcegraph%24+Statefulset+file:base/&patternType=literal) only once per day to account for the induced downtime

**Comment by unknwon** [comment]
Originally, we wanted to do some fancy retry... but that's not the real fix. Since we track the root issue in #16577, I'm closing this.
