### ISSUE TITLE
Panics in endpoints pkg

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#18913]
https://console.cloud.google.com/errors/CIKi3d-NgILyDw?time=PT6H&refresh=auto&project=sourcegraph-dev&authuser=0&organizationId=1006954638239 

I spend a little bit of time trying to replicate these issues. I believe the root cause is the API server going down temporarily (as that happens during k8s upgrades when the API server is unavailable).

**Comment by daxmc99** [comment]
Not sure who owns this code (sorry @keegancsmith ) but I'm happy to pair to get to the bottom of this. 
Happy to help setup a test cluster env as well

**Comment by keegancsmith** [comment]
Fairly certain this didn't happen until we switch the k8s clients :) Lets pair on it soon. I'm up late tonight, so we can pair today if that suits you?
