### ISSUE TITLE
[deploy-sourcegraph] ingress-nginx: document that you can pull the controller's logs to troubleshoot 

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#1892]
_See https://github.com/sourcegraph/deploy-sourcegraph_

When following https://github.com/sourcegraph/deploy-sourcegraph/blob/master/docs/configure.md#configure-tlsssl, if there is an issue with your provided cert / key pair, the only thing that obviously visiblyy wrong is the following when you visit your Sourcegraph instance: 

![screen shot 2019-01-14 at 4 53 58 pm](https://user-images.githubusercontent.com/9022011/51150901-5888f680-181d-11e9-8885-90daf478f2d7.png)

This doesn't tell you anything about what actually went wrong (your named secret doesn't exist, your cert-key pair is mismatched, doesn't apply to this domain, etc.). 

`kubectl describe ingress sourcegraph-frontend` also makes it seems like nothing is wrong: 

```shell
Name:             sourcegraph-frontend
Namespace:        default
Address:          35.238.7.214
Default backend:  default-http-backend:80 (10.8.0.9:8080)
TLS:
  sgdev-tls-lol terminates ingresstest.sgdev.org
Rules:
  Host                   Path  Backends
  ----                   ----  --------
  ingresstest.sgdev.org
                         /   sourcegraph-frontend:30080 (<none>)
Annotations:
  kubernetes.io/ingress.class:                       nginx
  nginx.ingress.kubernetes.io/proxy-body-size:       150m
  kubectl.kubernetes.io/last-applied-configuration:  {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{"kubernetes.io/ingress.class":"nginx","nginx.ingress.kubernetes.io/proxy-body-size":"150m"},"labels":{"app":"sourcegraph-frontend","deploy":"sourcegraph"},"name":"sourcegraph-frontend","namespace":"default"},"spec":{"rules":[{"host":"ingresstest.sgdev.org","http":{"paths":[{"backend":{"serviceName":"sourcegraph-frontend","servicePort":30080},"path":"/"}]}}],"tls":[{"hosts":["ingresstest.sgdev.org"],"secretName":"sgdev-tls-lol"}]}}

Events:
  Type    Reason  Age   From                      Message
  ----    ------  ----  ----                      -------
  Normal  CREATE  11m   nginx-ingress-controller  Ingress default/sourcegraph-frontend
  Normal  UPDATE  11m   nginx-ingress-controller  Ingress default/sourcegraph-frontend
```

It was only after a while that I realized that you can actually pull the logs of the ingress controller pod, which will tell you things like: 

`kubectl logs nginx-ingress-controller-87554c57b-95dmr --namespace=ingress-nginx`: 

```shell
W0115 00:11:18.271795      10 controller.go:1080] Validating certificate against DNS names. This will be deprecated in a future version.
W0115 00:11:18.271803      10 controller.go:1085] SSL certificate "default/sgdev-tls-lol" does not contain a Common Name or Subject Alternative Name for server "ingresstest.sgdev.org": x509: certificate is valid for sgdev.org, not ingresstest.sgdev.org
W0115 00:11:18.271810      10 controller.go:1087] Using default certificate
```

This really needs to be documented somewheere in https://github.com/sourcegraph/deploy-sourcegraph/blob/master/docs/configure.md, I spent a lot of time (2+ hours) trying to figure out what was going on until I realized this.

**Comment by nicksnyder** [comment]
Since this is a docs change, it is not a blocker for tagging 3.0-beta (but is still important to do by 3.0).
