### ISSUE TITLE
Reload server action needs a longer timeout

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#1895]
- **Sourcegraph version:** 3.0 beta

Seems it needs a longer timeout?

![screenflow](https://user-images.githubusercontent.com/133014/51155235-b7ee0300-182b-11e9-9b9c-0a83b139787a.gif)

**Comment by sqs** [comment]
Adding to 3.1 because this sounds like it'll be addressed by https://github.com/sourcegraph/sourcegraph/issues/517. @slimsag 	If not, please move to backlog (or handle separately).
