### ISSUE TITLE
dbtesting.GetDB is not parallel-safe, making it impossible to run insights integration tests in parallel

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#18956]
Insights regression tests (which rely on testing things mostly end-to-end, including the DB) are pretty slow right now because of a single reason: `dbtesting.GetDB` returns a _global_ database handle - making it impossible to `t.Parallel()` the tests so they all run side-by-side.

This is not true of our interactions with e.g. TimescaleDB, only the interactions we have with Postgres (e.g. to fetch user settings.) If we address this, tests will run much faster.

https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+lang:go+file:insights+yuck&patternType=literal

**Comment by leonore** [comment]
closing as I believe we migrated away from `dbtesting.GetDB`: https://sourcegraph.sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+dbtesting.GetDB&patternType=standard
