### ISSUE TITLE
insights: use search query parser instead of string manipulation in some places

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#18959]
In the backend we do string manipulation of queries a bit. Nothing crazy, but there could be some false-positives which cause us to consider a search query for an insight to be invalid and thus produce no data for it:

* https://sourcegraph.com/github.com/sourcegraph/sourcegraph@2ad492d82b016f60975019beb689af1f4eac4a4c/-/blob/enterprise/internal/insights/background/historical_enqueuer.go#L380-390
* https://sourcegraph.com/github.com/sourcegraph/sourcegraph@2ad492d82b016f60975019beb689af1f4eac4a4c/-/blob/enterprise/internal/insights/background/historical_enqueuer.go#L446-448
* https://sourcegraph.com/github.com/sourcegraph/sourcegraph@2ad492d82b016f60975019beb689af1f4eac4a4c/-/blob/enterprise/internal/insights/background/insight_enqueuer.go#L109-120

**Comment by coury-clark** [comment]
Closing in favor of https://github.com/sourcegraph/sourcegraph/issues/24432
