### ISSUE TITLE
Restart server button unresponsive if request times out

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#1896]
- **Sourcegraph version:** 3.0 beta

The Restart server button gets repeatedly pressed after a timeout but nothing happens. Only way to 
fix it is to refresh.

![screenflow](https://user-images.githubusercontent.com/133014/51155346-0ac7ba80-182c-11e9-9a6b-0660cc059a3e.gif)

**Comment by sqs** [comment]
Adding to 3.1 because this sounds like it'll be addressed by https://github.com/sourcegraph/sourcegraph/issues/517. @slimsag 	If not, please move to backlog (or handle separately).

**Comment by slimsag** [comment]
This is a dup of https://github.com/sourcegraph/sourcegraph/issues/517 effectively, closing.
