### ISSUE TITLE
insights: make the experience of data backfilling more interactive

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#18968]
Closely related to https://github.com/sourcegraph/sourcegraph/issues/18708

Quoting https://sourcegraph.slack.com/archives/C014ZCKMCAV/p1614910618100400 (which may now be a broken link due to Slack retention)

Stephen says:

> Historical data generation has landed and is live on k8s.sgdev.org (not yet on sourcegraph.com, because deployment rolls out there slowly.) It's already working, albeit a bit slow (as expected) - it records about 100,000 data points (that is, 100,000 unique searches!) per hour. Since k8s.sgdev.org has ~40k repos, it thus takes about 30m to build out data for each 1 week timeframe it generates data for.
>
> It generates 1 data point per week (per repo) for the past 52 weeks, which with 40k repos should take about 26 hours at current pace.
> If you add more than one search insight, it does work linearly so the time it takes would double. It builds out data from most-recent to oldest, so each insight would have its data slowly built back into history (rather than one insight, then the next, etc.)
> My time here is obviously more limited now, but there are things we can tune over the coming weeks to make this nicer:
> * If we record 1 data point per 2 weeks, that's 2x faster. 1 point per month is 4x faster.
> * We can enqueue work faster - I've made it intentionally slow so as to not impact real user's searches, etc. Just requires adjusting a time parameter in the code and keeping an eye on system load to make sure it's okay.
>
> **(THIS ISSUE)** In the future, there are also some other curious opportunities to make the experience even more interactive. The new hire would have to do this, and I'll write a github issue, but basically we could immediately record data points for 1 year ago (so you'd have "one point a year ago, one point today"), then add a point 6 months ago, then 3 and 9 months ago, and incrementally get more and more fine-grained. This would be a challenge to implement, but could be interesting.

Joel says:

> This is great! 1 data point/repo/week seems like a good max level of detail based on our customer conversations, but I imagine that most customers (at the moment) won’t have 40k repos. One quick thing is that the UI to create an insight can let a user set the level of detail and we can note it affects the speed (and note it right there on that input, at least in the prototype and beta).
> Agree with you that there are some interesting things we can do with the UX given these constraints! Thanks for the initial suggestions. I’ll also do some background research on how other tools handle >10 minute delays; at the moment I’m mostly familiar with the interfaces of the lookers/periscopes/leanplums of the world.
>
>
> I am assuming that there’s nothing special here about the linear queue (it’s not just per-graph or per-user, but across all insights) — that if six users create 2 insights each, that’s a 12-query queue?
>
>
> (Note to self, we need to define “an insight” vs “a query” to avoid confusion here.)

Stephen says:

> That is correct. “Series” is the word to describe a query or other (webhook) series of data. An “insight” is said to be a chart, made up of one or more series.

Felix says:

> Thanks @stephen, that's great! Please do record this in a GitHub issue as I'm afraid it would get lost in Slack :slightly_smiling_face:
> I like the binary-search-like fill approach.

**Comment by slimsag** [comment]
One drawback I thought of w.r.t. the binary-search-like approach of data backfilling: it makes communicating "wtf is going on" to the user a lot harder. e.g. progress on backfilling currently is "I don't see old data, and after a few hours I start to, and after a day I do" - with the binary-search-like approach some of the problems in https://github.com/sourcegraph/sourcegraph/issues/18708 are a lot harder to communicate (e.g. "incomplete data points" described in there)

**Comment by Joelkw** [comment]
@slimsag Thanks for documenting this! (Noting for anyone coming across this that we have _**not**_ aligned on a team that the binary search approach is the direction we want to go.)

**Comment by coury-clark** [comment]
Closing this issue since it has gotten crusty and very out of date.

To summarize:
1. Some metadata is now exposed to allow the frontend to display loading states to users.
2. The backend uses a compression mechanism to reduce the number of points required to query, and fills from the most recent point backwards as possible.
