### ISSUE TITLE
search: avoid copying stats.Repos

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#18984]
We removed an important perf optimization in https://github.com/sourcegraph/sourcegraph/pull/18982

We can likely get back the performance by using a copy-on-write map. This way we can share the map unless we really do end up mutating it.

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket,  please let us how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
