### ISSUE TITLE
Document steps migrate from src-expose to new Perforce integration

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#18994]
#### Describe the issue
Please add documentation for customers that are currently using src-expose to integrate with Perforce to migrate to the newer version of Perforce integration

**Comment by unknwon** [comment]
@mike-r-mclaughlin is it feasible to provide >3 real-world customer configs of `src-expose` (through private DM) to me so at least I will not come up the migration docs out of nothing? 😁

**Comment by mike-r-mclaughlin** [comment]
Ah. Sure @unknwon .  I didn't realize the original steps weren't documented.  I'll get those to you in next day or two.  :)

**Comment by mike-r-mclaughlin** [comment]
Rough outline of steps:
1. Delete src-expose containers
2. Upgrade cluster
3. Follow steps [outlined in the docs](https://docs.sourcegraph.com/admin/repo/perforce#sourcegraph-3-25-1-configuration-instructions)
    3a. Add a new repository configuration for all depots listed in `repo-list.sh` configuration file

NOTE: all of the repositories will need to re-index after this step

**Comment by mike-r-mclaughlin** [comment]
@unknwon is there a way to do this one repo at a time?  Could we configure a repo in the new UI, let it index, and then delete the "old" one?

**Comment by unknwon** [comment]
> @unknwon is there a way to do this one repo at a time? Could we configure a repo in the new UI, let it index, and then delete the "old" one?

I don't see a reason why we technically can't

**Comment by unknwon** [comment]
Cleaning up old/stale/fixed issues, please feel free to reopen if you think it's worth keeping.
