### ISSUE TITLE
Sourcegraph extensions on a code host: extensions should fail gracefully rather than break all hovers/extensions

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#19009]
A teammate reported an instance where a broken Sourcegraph extension then broke the whole browser extension functionality (hovers and other extensions). Example logs attached from one such case in Safari. 
<img width="1316" alt="Screen Shot 2021-03-08 at 12 56 58" src="https://user-images.githubusercontent.com/11967660/110557278-24f04100-80f5-11eb-9ade-6ab0345506e3.png">

**Comment by erzhtor** [comment]
I think this is not the case anymore and was fixed https://github.com/sourcegraph/sourcegraph/pull/24675.
@tjkandala do you think we can close this as duplicate or so?
cc @muratsu
