### ISSUE TITLE
As a non admin, it's unclear why I can't close campaigns

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#19029]
## User story
I am not a site admin. I start viewing campaigns created by others (that I don't own).
I can click on the "Close" campaign button. 
When I click on that button, I view  a page with all buttons disabled, and I'm lost

https://www.loom.com/share/b0d8e83ce7a344fa93d483c75723d90a

## Desired behaviour
Users that are not site admin cannot close campaigns they don't own (~ that they did not create).
The page should make it clear why closing campaigns is not possible.

## Proposed solution
![image](https://user-images.githubusercontent.com/25070988/110629342-596f0600-81a4-11eb-86e3-c184c2136aa6.png)

**Comment by rrhyne** [comment]
This would be fine with me, but another solution would be to grey out the close button on the campaign page and change the tooltip to read something like:

"Only campaign owners or admins can close a campaign."
