### ISSUE TITLE
General keyboard shortcuts

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#19021]
This is the implementation issue for [RFC 345: Keyboard navigation in Sourcegraph](https://docs.google.com/document/d/1_r8aikiE-zwn0ZkWmOilynNVA3HfmF9Mglgg6ZEkkls/edit#).

[Figma – Keyboard navigation underpinnings audit](https://www.figma.com/file/SFxkUErsZNYDPQZMG8nBK6/%2319021-%E2%80%93%C2%A0Keyboard-navigation-underpinnings-audit?node-id=246%3A12&t=75OjC6q2EJL38cUn-0)

Next steps from @felixfbecker:

- [ ] Resolve open comments in the RFC, in particular:
   - [x] Alignment with established accessibility concepts (landmark areas and widgets, vs "navigation areas" and "application areas")
- [ ] Audit the main screens of the app (blob view, search results). I suggest creating a Figma for this with screenshots we can overlay with rectangles and annotations.
   - [ ] Highlight the landmark areas and which keyboard shortcuts we want to use for jumping to them.
   - [ ] Highlight widgets that currently do not have standard keyboard controls (e.g. file tree, revision selector) and what ARIA widget we want to implement (which has standardized corresponding keyboard controls)
   - [ ] Highlight special areas that are not widgets, but where we want to implement additional keyboard controls regardless (e.g. jumping between search results)
- [ ] Implement shortcuts, including user settings to override them and events to track whether they are used
- [ ] Think about how to educate users of these shortcuts. It would probably be useful to have a similar visual for the different areas as the one from the above step that we can include in the app/docs for the user for education.
   - Keyboard shortcut quick-help
   - Docs page

**Comment by pdubroy** [comment]
Based on https://docs.google.com/document/d/1_r8aikiE-zwn0ZkWmOilynNVA3HfmF9Mglgg6ZEkkls/edit?disco=AAAAH93ixxE I don't know if we have everything we need to write this RFC yet.

**Comment by umpox** [comment]
Just for further context:

We've prioritised accessibility a lot lately, and I think it would be wise to re-review this RFC once we have finished our efforts in https://github.com/sourcegraph/sourcegraph/issues/31476.

Reasoning: We've made our application accessible with basic, built-in, keyboard shortcuts. This RFC focuses more on "power users". That is good, but there is also a lot of additional nuance that we need to account for the ensure these shortcuts are still accessible.

Some aspects, like changing how <kbd>tab</kbd> or arrow keys behave, might not be complaint with our accessibility standards

**Comment by felixfbecker** [comment]
@quinnkeast Here's what I think are the next steps:

- Resolve open comments in the RFC, in particular:
  - Alignment with established accessibility concepts (landmark areas and widgets, vs "navigation areas" and "application areas")
- Audit the main screens of the app (blob view, search results). I suggest creating a Figma for this with screenshots we can overlay with rectangles and annotations.
  - Highlight the landmark areas and which keyboard shortcuts we want to use for jumping to them.
  - Highlight widgets that currently do not have standard keyboard controls (e.g. file tree, revision selector) and what ARIA widget we want to implement (which has standardized corresponding keyboard controls)
  - Highlight special areas that are not widgets, but where we want to implement additional keyboard controls regardless (e.g. jumping between search results)
- Implement shortcuts, including user settings to override them and events to track whether they are used
- Think about how to educate users of these shortcuts. It would probably be useful to have a similar visual for the different areas as the one from the above step that we can include in the app/docs for the user for education.
  - Keyboard shortcut quick-help
  - Docs page

**Comment by quinnkeast** [comment]
I agree with all of these steps. I'll self-assign this issue and review \#1 on your list, then follow up on \#2 soon.

**Comment by quinnkeast** [comment]
Updates:
- I've [revised the RFC](https://docs.google.com/document/d/1_r8aikiE-zwn0ZkWmOilynNVA3HfmF9Mglgg6ZEkkls/edit#) based on comments and further thinking.
- I'm going to use [this Figma file](https://www.figma.com/file/SFxkUErsZNYDPQZMG8nBK6/%2319021-%E2%80%93%C2%A0Keyboard-navigation-underpinnings?node-id=246%3A12&t=brVxH4k8BhakP2sq-1) to audit the main screens of the app based on the latest revision of the proposal.
