### ISSUE TITLE
Hover tooltips show up on page load without any user interaction and then disappear

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#19034]
I could reproduce this and recorded a video:

1. Open https://sourcegraph.com/github.com/sourcegraph/sourcegraph@a6056c2414e37be9ea3db18ddc0ba32d206ddb51/-/blob/internal/database/external_services.go?L1201-1203#L1000:1-1002:3
2. See hover tooltip show up, show spinner, then disappear

Video:

https://user-images.githubusercontent.com/1185253/110656465-436f3e80-81c0-11eb-9e3a-8998c1424cfd.mp4

I'm not sure what's going on, but it does feel flaky that selected lines and no user input could cause the hover to show up.

It's not captured in the video but when I first noticed this I think (not sure though) that the tooltip showed up and disappeared _twice_ in a row.

**Comment by mrnugget** [comment]
cc @tjkandala because we discussed this on Slack just now

**Comment by efritz** [comment]
You do have user input here: the URL query string. That's the same as hovering over that range as far as the extension is concerned (not claiming this isn't bad UX).

**Comment by chrismwendt** [comment]
I'm guessing [token-click j2d](https://github.com/sourcegraph/sourcegraph/pull/28520) eliminated this problem.
