### ISSUE TITLE
Sourcegraph doesn't start on Apple M1 machines

### ISSUE THREAD

**Issue by mherna** [sourcegraph/sourcegraph#19041]
- **Sourcegraph version:** 3.25.2
- **Platform information:** macOS Big Sur (M1)

#### Steps to reproduce:

1. run ```docker run --publish 7080:7080 --publish 127.0.0.1:3370:3370 --rm --volume ~/.sourcegraph/config:/etc/sourcegraph --volume ~/.sourcegraph/data:/var/opt/sourcegraph sourcegraph/server:3.25.2```

#### Expected behavior:
Sourcegraph start normally
#### Actual behavior:
```
21:02:24 precise-code-intel-worker | qemu: uncaught target signal 11 (Segmentation fault) - core dumped
21:02:24 precise-code-intel-worker | Terminating precise-code-intel-worker
precise-code-intel-worker died. Shutting down...
21:02:24              github-proxy | Terminating github-proxy
21:02:24               redis-store | Terminating redis-store
21:02:24                 gitserver | Terminating gitserver
21:02:24                     nginx | Terminating nginx
21:02:24                prometheus | Terminating prometheus
21:02:24                  frontend | Terminating frontend
21:02:24                    jaeger | Terminating jaeger
21:02:24              query-runner | Terminating query-runner
21:02:24           zoekt-webserver | Terminating zoekt-webserver
21:02:24            syntect_server | Terminating syntect_server
21:02:24         zoekt-indexserver | Terminating zoekt-indexserver
21:02:24                   grafana | Terminating grafana
21:02:24         postgres_exporter | Terminating postgres_exporter
21:02:24                     minio | Terminating minio
21:02:24               redis-cache | Terminating redis-cache
21:02:24                  searcher | Terminating searcher
21:02:24              repo-updater | Terminating repo-updater
21:02:24                   symbols | Terminating symbols
21:02:24                  postgres | Terminating postgres
```

**Comment by camdencheek** [comment]
Maybe related to https://github.com/docker/for-mac/issues/5123?

**Comment by eneroth** [comment]
I get this problem as well. It fails at creating the account.

```
06:41:55                  frontend | ✱ Sourcegraph is ready at: http://127.0.0.1:7080
06:42:57                    worker | qemu: uncaught target signal 11 (Segmentation fault) - core dumped
06:42:57                    worker | Terminating worker
worker died. Shutting down...
06:42:57           zoekt-webserver | 2021/07/16 06:42:57 shutting down
06:42:57         postgres_exporter | Terminating postgres_exporter
06:42:57           zoekt-webserver | Terminating zoekt-webserver
06:42:57         zoekt-indexserver | Terminating zoekt-indexserver
06:42:57              github-proxy | Terminating github-proxy
06:42:57               redis-cache | Terminating redis-cache
06:42:57                   symbols | Terminating symbols
06:42:57                 gitserver | Terminating gitserver
06:42:57              query-runner | Terminating query-runner
06:42:57                prometheus | Terminating prometheus
06:42:57                  frontend | t=2021-07-16T06:42:57+0000 lvl=eror msg="Error in user signup." email=[redacted] username=[redacted] error="2 errors occurred:\n\t* read tcp 127.0.0.1:34896->127.0.0.1:5432: i/o timeout\n\t* sql: transaction has already been committed or rolled back\n\n"
06:42:57               redis-store | Terminating redis-store
06:42:57 precise-code-intel-worker | Terminating precise-code-intel-worker
06:42:57                     nginx | Terminating nginx
06:42:57              repo-updater | Terminating repo-updater
06:42:57                   grafana | Terminating grafana
06:42:57                  searcher | Terminating searcher
06:42:58            syntect_server | Terminating syntect_server
06:42:58                    jaeger | Terminating jaeger
06:42:58                  frontend | t=2021-07-16T06:42:58+0000 lvl=eror msg="Repository authz config was invalid (errors are visible in the UI as an admin user, you should fix ASAP). Restricting access to repositories by default for now to be safe." seriousProblems="[Could not list external services: failed to connect to `host=127.0.0.1 user=postgres database=sourcegraph`: server error (FATAL: the database system is shutting down (SQLSTATE 57P03))]"
06:42:58                     minio | Terminating minio
06:43:03                  frontend | t=2021-07-16T06:43:03+0000 lvl=eror msg="Repository authz config was invalid (errors are visible in the UI as an admin user, you should fix ASAP). Restricting access to repositories by default for now to be safe." seriousProblems="[Could not list external services: failed to connect to `host=127.0.0.1 user=postgres database=sourcegraph`: server error (FATAL: the database system is shutting down (SQLSTATE 57P03))]"
06:43:07                  postgres | Terminating postgres
06:43:07                  frontend | Terminating frontend
```

**Comment by rafax** [comment]
I tried running Docker version of Sourcegraph on M1 Macbook Pro today ([same command as Chris](https://github.com/sourcegraph/sourcegraph/issues/19041#issuecomment-951354425)), and was able to get Sourcegraph to start, created an admin and user account / added some repos / searched without issues.
Is there a specific action that triggers the crash?

Environment:
Computer: MacBook Pro (14-inch, 2021)
OS: MacOS 12.0 (21A344) Monterey
Docker: Desktop 4.2.0 (70708), Engine: 20.10.10
Command:  `docker run --publish 7080:7080 --publish 127.0.0.1:3370:3370 --rm --volume ~/.sourcegraph/config:/etc/sourcegraph --volume ~/.sourcegraph/data:/var/opt/sourcegraph sourcegraph/server:3.33.0`

**Comment by ggilmore** [comment]
There are two issues that I can see so far:

1. Docker uses [QEMU](https://www.qemu.org/) to emulate foreign architectures when you are running a non-native container (e.g. running an `amd64` container on an `arm64` machine like we're doing with `sourcegraph/server`). QEMU currently doesn't implement a syscall (`io_setup`) that [`nginx` relies on](https://sourcegraph.com/github.com/nginx/nginx@3334585539168947650a37d74dd32973ab451d70/-/blob/src/event/modules/ngx_epoll_module.c?L278:9#tab=references). See https://gitlab.com/qemu-project/qemu/-/issues/210. This doesn't cause an immediate crash, but I think it's safe to say that we can expect some issues if some aspect of nginx's async io functionality is broken. 
2. When I run the server container, I have seen the `frontend` binary get killed repeatedly. It's getting a `kill 9` signal, but there is no log output explaining anything that's gone wrong. I am currently trying to read through `QEMU_STRACE`'s output, but I haven't found anything illuminating so far.

**Comment by ggilmore** [comment]
> When I run the server container, I have seen the frontend binary get killed repeatedly. It's getting a kill 9 signal, but there is no log output explaining anything that's gone wrong. I am currently trying to read through QEMU_STRACE's output, but I haven't found anything illuminating so far.

After doing some more investigation about this, I think the answer is simply that the process is getting OOM killed. 

You can pull this from the `dmesg` output:

```
[15256.187810] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=docker,mems_allowed=0,global_oom,task_memcg=/docker/22559687cb4d15c846d590053598efc6432fcd82a4e8f96aa4c69fac43c10d65,task=frontend,pid=67689,uid=0
[15256.190006] Out of memory: Killed process 67689 (frontend) total-vm:1021056kB, anon-rss:109376kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:508kB oom_score_adj:0
[15256.244763] oom_reaper: reaped process 67689 (frontend), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

It's [documented that using `qemu`  for emulation requires more memory than the native architecture]( https://docs.docker.com/desktop/mac/apple-silicon/#known-issues). 

Compare the output of `free -h` on a fresh container (spawned via `env TAG=3.33.0 ./dev/run-server-image.sh`) on both architectures: 

- `arm64` (notice that this is already using all of its swap space):
```
/ # free -h 
              total        used        free      shared  buff/cache   available
Mem:          1.9Gi       1.7Gi        31Mi        30Mi       228Mi       153Mi
Swap:         1.0Gi       1.0Gi       3.0Mi
```

- `amd64`
```
/ # free -h
              total        used        free      shared  buff/cache   available
Mem:          1.9Gi       1.1Gi        94Mi        89Mi       749Mi       612Mi
Swap:         1.0Gi       646Mi       377Mi
```

Once the "host" OS (the linux VM that docker for mac uses) starts running out of memory, it'll start killing processes to get rid of space. [`goreman` will then kill all of the other processes](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@72a1932648a6787309a54d8c79f8c64c4ad03e3c/-/blob/cmd/server/shared/shared.go?L189) and shutdown the container. 

---

If we want to work around this problem, we'll need to adjust our docs to tell that they need to [bump the amount of memory that's assigned to the linux VM](https://docs.docker.com/desktop/mac/#resources) to 4 or even 6 gigabytes before they can use our quickstart command. 

**Note**: The unimplemented syscall for `nginx` (mentioned my earlier comment) is still an entirely separate problem that's not addressed by this. We'll need to come to a descision (ripping out Nginx entirely, moving to [ARM native containers](https://docs.google.com/document/d/1kZUEV9SIIv_wuxD_l1Buw9zNV9X_PtR-IJxGxm3Guvc/edit), etc.).

**Comment by ggilmore** [comment]
Posting a response to a Slack comment here: 

> Can we pass the memory demands in via the quickstart command? ...

Unfortunately no. Passing the memory flag with a higher amount than what's assigned to the Linux VM (configured via [that docker for Mac setting](https://docs.docker.com/desktop/mac/#resources)) won't have any effect.

**Comment by ggilmore** [comment]
(And even if that were possible, the unimplemented syscall for `nginx` is still an issue).

**Comment by dan-mckean** [comment]
Geoffrey's write up [Sourcegraph Single Container image (sourcegraph/server) on Apple m1
](https://docs.google.com/document/d/113D_xE7KHk3vskNZxytR_Vaau43TkiZ2aITlrLg5qFg/edit#heading=h.a7shr7kpo90g)

**Comment by virginiaulrich** [comment]
From 2022-03-28 Delivery planning session: closing from Delivery backlog; work to be done will be from within Enablement org and those teams can share more details about their plans as needed.
