### ISSUE TITLE
Robust, simple and easy to reason about authz service / domain

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#19065]
## Context

- Specially important given the advent of private code in sourcegraph.com
- The direct SQL integration is easy to skip and produces hard to debug queries.
- We need robust, but still performant service with a clear public API that's easy to audit and test for correctness.
- We need to make it very hard for new developers to skip authorization when writing new code.
- Needed for [Sophisticated Role Based Permissions](https://sourcegraph.productboard.com/feature-board/2119755-core-application/features/7275624/detail).
- Model code structure based on [RFC 348 - Backend Code Structure](https://docs.google.com/document/d/1WyMlVtrwe2qqOGhPYgnvFxUYqllz2t-CVH3sD4qMKTE/edit#)

**Comment by unknwon** [comment]
>The direct SQL integration is easy to skip and produces hard to debug queries.

I was thinking about it today, what about we utilize Postgres roles that only "the authz service" (e.g. `authz` role) can read/write the full "repo" table, and other roles have to access it via "filtered_repos" function (which caller has to pass a user ID). Broadly speaking, each service of the domain may have its own PG role.

**Comment by tsenart** [comment]
Yeah, that could work as a first step! Still a bit worried about the query complexity as it currently stands, but we could improve that with some SQL function too?

**Comment by unknwon** [comment]
>but we could improve that with some SQL function too?

This reminds me of https://github.com/sourcegraph/sourcegraph/issues/16024

A query can be as simple as:

```sql
SELECT * FROM filtered_repos(true, false, 0, 'read');
```

Migration path: replace every `FROM repo` to be `FROM filtered_repos(...)`.

It wasn't appealing to me because I didn't think of utilizing PG roles.

**Comment by unknwon** [comment]
Looks like yes! https://www.postgresql.org/message-id/CAA-aLv7cw8cZ_SGGKJyu2Rd14FYAr4zhH=q1Us66zLZsra1gCw@mail.gmail.com
