### ISSUE TITLE
Context missing from SearchSubmitted event

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#19068]
When a user is using the context selector on Cloud (and hasn't added it to the search query manually), it won't be included in `SearchSubmitted` events. For example, a user with the context `@logansmith` would report the event: 

`EVENT SearchSubmitted {query: “console.log lang:js”, source: “nav”}`

### Steps to address

Include context parameter in SearchSubmitted events.

**Comment by ebrodymoore** [comment]
Unassigning myself as this should be the search team to execute!
