### ISSUE TITLE
search: Generalize parsing of predicate values

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#19075]
To support parameter values like `contains(file:test)`, we had to add an exception to the parsing rules to continue parsing through parantheses in the case that we are parsing one of the reserved predicate keywords. This should be generalized to allow for multiple predicate names, and also re-thought to make sure this is the correct place to do this check.

Related to #18584

**Comment by camdencheek** [comment]
Things that still don't work: `repo:contains(file:package.json content:prettier)`

**Comment by rvantonder** [comment]
Related: We need to also cover the case for `file:(a (regex(with parens)))`, I think our regex to that "parses" this will fail currently. Probably a good way to do this would be to extract the parser code to a separate scanner that we can reuse for simpler cases.
