### ISSUE TITLE
Failure to load page with SyntaxError: invalid regexp group

### ISSUE THREAD

**Issue by rina-indeed** [sourcegraph/sourcegraph#19074]
When I go to https://sourcegraph.com/search using Firefox, I get an entirely blank page. Checking the console, the only message I see is `SyntaxError: invalid regexp group`.

Previously I had been able to use SourceGraph without any issues. I have only been able to replicate this bug on my Ubuntu 16.04 desktop using Firefox. SourceGraph works normally on the same device using Chrome, and on my Mac laptop using either Chrome or Firefox.

**Comment by malomarrec** [comment]
Hi @rina-indeed !
I am so sorry you did not get an answer on this. Sounds like it was left unassigned, I'm investigating why and will try to get something in place so that this does not happen.

I was unable to reproduce, can could you confirm that this is still happening?

**Comment by rina-indeed** [comment]
Hi @malomarrec! Thanks for following up. This is still happening (with the same error message) whenever I use Firefox on my Ubuntu desktop. I still have been unable to reproduce with different browsers and with different computers, so I'm not sure what additional context would be helpful in reproducing the issue.

**Comment by DaedalusG** [comment]
@rina-indeed I'd love to look into this for you, would you be able to email support@sourcegraph.com so we can do so in a manner that protects your data?

**Comment by rina-indeed** [comment]
@DaedalusG Thanks, just sent the email!

**Comment by DaedalusG** [comment]
Moved to private issue tracking
