### ISSUE TITLE
VS Code uses VS Code's extension schema in Sourcegraph ext package.json files

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1908]
When editing a package.json file in VS Code that is for a Sourcegraph extension, VS Code shows the JSON Schema (hovers, completions, validations) for VS Code extensions, not Sourcegraph extensions.

They are slightly different: https://docs.sourcegraph.com/extensions/authoring/manifest#fields vs https://code.visualstudio.com/api/references/extension-manifest:

- Categories are sentence case in Sourcegraph ("Programming languages" vs "Programming Languages")
- `contributions` is slightly different (but similar enough to be confusing)

**Comment by felixfbecker** [comment]
Can we make the extension generator add a `$schema` field that points to our schema (which should reference the URL for the plain npm package.json schema)?

**Comment by sqs** [comment]
[It does](https://sourcegraph.com/github.com/sourcegraph/create-extension@47f5c09f7c24c19a0ca0c4aa5454798a5b6073d9/-/blob/src/cli.ts#L164), but I believe that VS Code unions the schemas. There may not be a way to tell VS Code "do not use the builtin schema for package.json, *only* use this one".

**Comment by felixfbecker** [comment]
It doesn't union the schema. The error went away for me after adding `$schema`.
