### ISSUE TITLE
Closing backticks in diff view are highlighted in red for a line that has been added

### ISSUE THREAD

**Issue by indradhanush** [sourcegraph/sourcegraph#19084]
- **Sourcegraph version:** 89916_2021-03-12_4dae89d
- **Platform information:**

  - Firefox 86.0
  - Chromium 89.0.4389.82
  - Google Chrome 89.0.4389.82 

#### Steps to reproduce:

1. Visit the link: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/compare/2fa31403177b4e4d1cef75d4dcc17b185b45517e...726710bb9cea37f690ddcd423118449f5397947d?utm_source=firefox-extension&visible=1#diff-640e590d4fb6e0c3c7a2fda6ff3d0810
2. Ensure that the light theme is enabled on the browser for sourcegraph.com

#### Expected behavior:

In the light theme, backticks should not be highlighted in red for a diff where the line has been added. In dark theme this is not an issue.

#### Actual behavior:

Closing backticks are highlighted in red.

![image](https://user-images.githubusercontent.com/2682729/110897030-b2fd3f00-8322-11eb-9c65-1cc739a2351c.png)

**Comment by lrhacker** [comment]
This appears to be working now:
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/10523985/180285435-4600d3a7-c32c-4d5a-934e-ae564a5a5d6a.png">
