### ISSUE TITLE
Search input should have border radius on left corners

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#19090]
### Problem

With the introduction of the contexts selector, I think we lost a small design detail: the left corners of the search input have no radius, while the right corners of the whole (the search button) have a `2px` radius.

<img width="758" alt="CleanShot 2021-03-12 at 10 44 18@2x" src="https://user-images.githubusercontent.com/6304497/110922380-e8ecf400-831f-11eb-90d4-80e12f5c8692.png">

### Solution

The top left and bottom left corners of the search input should have `2px` radius on both the home page and the top nav bar.

**Comment by novoselrok** [comment]
Fixed with the redesign:
<img width="189" alt="Screenshot 2021-05-28 at 10 06 41" src="https://user-images.githubusercontent.com/6417322/119951598-6843a880-bf9c-11eb-98e3-0907be34dfcc.png">
