### ISSUE TITLE
Reduce coupling of raw endpoint with repo-updater

### ISSUE THREAD

**Issue by indradhanush** [sourcegraph/sourcegraph#19096]
### Problem description

If the `raw` endpoint for a particular repo receives a request and the repo is not cloned already, the [serveRaw](https://github.com/sourcegraph/sourcegraph/blob/main/cmd/frontend/internal/app/ui/raw.go#L62-L85) handler keeps checking indefinitely waiting for the repo to be cloned. This has the following down sides:

1. The client waits while the request is completed. 
1. If the `repo-updater` component is not available for any reason, the request will stay alive indefinitely until the max TTL of the web server is hit.
1. The service serving the `raw` endpoint is heavily coupled with the `repo-updater` and makes the service implicitly trust that the availability of `repo-updater`. Services should be fault tolerant and expect other services to fail and handle the failure scenarios appropriately.
1. This potentially opens up a DoS attack vector.

### Proposed solution

Instead of waiting for the repo to be cloned, we should return a 404 with a [useful error message](https://tools.ietf.org/html/draft-ietf-httpbis-p2-semantics-12#section-8.4) that indicates to the client that they may try again in some time and maybe the repo will be available then.

The scope of this issue should also include tests for the new behavior. 

### Dependencies with other areas of the product

- https://sourcegraph.com/github.com/sourcegraph/src-cli/-/blob/internal/batches/repo_fetcher.go#L291-338 - Owned by @sourcegraph/batchers

**Comment by ryanslade** [comment]
@indradhanush Are you working on this? No problem if not, but then can you unassign yourself so that it goes back into the unowned pool in our debt tracking issue 😄

**Comment by cbart** [comment]
I think the link for the CLI usage is now https://sourcegraph.com/github.com/sourcegraph/src-cli/-/blob/internal/batches/repozip/fetcher.go?L315

**Comment by eseliger** [comment]
Correct!
