### ISSUE TITLE
Support multi-line searches

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#191]
#### Feature request description

Find matches for a search query that occur across multiple lines. Right now, Sourcegraph only finds a match when it occurs on a single line.

#### Additional context

Reported by @lhorie (and others, before this repo was open-sourced) at https://news.ycombinator.com/item?id=18117755

**Comment by hho** [comment]
Possible duplicate of #35

**Comment by keegancsmith** [comment]
Duplicate of #35
