### ISSUE TITLE
Fix race condition in TestRunMigratorMigrationChangesDirection

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#19127]
We've talked about this before (and I already took a stab at it but it went nowhere), so let's create a ticket for this since it failed again [here](https://buildkite.com/sourcegraph/sourcegraph/builds/90068#0bd6517b-2e4e-445f-ac26-71779ffa4436):

```

FAIL: TestRunMigratorMigrationChangesDirection (0.00s) | 0s
-- | --
  | runner_test.go:248: unexpected number of calls to Up. want=5 have=4
```

**Comment by keegancsmith** [comment]
> race condition is due to cancelling the ctx in migrator before it has had a chance to read everything from the channel.
