### ISSUE TITLE
Help docs home page displays docker run command on a single line

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#1912]
![screen shot 2019-01-15 at 9 40 50 am](https://user-images.githubusercontent.com/133014/51200818-66875780-18af-11e9-8728-59bd594ca84b.png)

**Comment by felixfbecker** [comment]
The `virtual-br` class is missing in the main webapp styles.

**Comment by sqs** [comment]
#2337 will fix this. Therefore not assigning this to anyone.
