### ISSUE TITLE
dev/launch.sh breaks if you haven't run "yarn" yet 

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#1914]
https://sourcegraph.slack.com/archives/C07KZF47K/p1547578053302000?thread_ts=1547577858.301500&cid=C07KZF47K

**Comment by keegancsmith** [comment]
https://github.com/sourcegraph/sourcegraph/pull/1496#issuecomment-452663654

Alternatively we can revert that PR and do "go run" where minversion checks that output of `runtime.Version()`

**Comment by nicksnyder** [comment]
I like the go run idea.

**Comment by attfarhan** [comment]
Do we expect that some of our contributors (or teammates) use development builds of Go? It seems like there are a lot of complaints about `runtime.Version()`'s output being unhelpful for this kind of use (https://github.com/golang/go/issues/21207, https://github.com/golang/go/issues/11972, https://github.com/golang/go/issues/11972). I think it's possible to parse release tags well enough, but development builds might be tricky

**Comment by nicksnyder** [comment]
I don't think anyone uses a development build of go so I wouldn't worry about that.
