### ISSUE TITLE
Focus and padding on streaming search indicators

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#19143]
The focus state shows as grey and extends to the borders of the dialog. 

We need to use the blue focus style and add p2 to the entire button area to ensure there is space between the border of the dropdown and the focused element. 

Current:
![image](https://user-images.githubusercontent.com/539268/111201618-2cde3400-8580-11eb-98ae-31dcbb3e844e.png)

Corrections:
![image](https://user-images.githubusercontent.com/539268/111201664-38c9f600-8580-11eb-8344-0611114e6517.png)

**Comment by limitedmage** [comment]
@benvenker Moving this into "Next" in case we have the bandwidth to look into it in the next iteration.
