### ISSUE TITLE
Repo page loads correctly for a moment, then breaks with gating error

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#19157]
This was [brought up by a user](https://sourcegraph.slack.com/archives/C0W2E592M/p1615844757032900) who thought this was an issue with the chrome extension URL bar, but I think it's actually an issue with something happening on Sourcegraph (or both, still digging in with them) – https://www.loom.com/share/6daae4a61a744a6aae9adf97388d6a20

This also seems to happen on other repository pages, like sourcegraph/about: 
![image](https://user-images.githubusercontent.com/11967660/111269645-1f5e9380-85ec-11eb-887b-48ab72b37fee.png)

**Comment by tjkandala** [comment]
@Joelkw this seems to happen to me only when the code-stats-insights extension is enabled. I believe it has to do with the recent extension host refactor
