### ISSUE TITLE
Publisher links on extension page doesn't work as expected

### ISSUE THREAD

**Issue by muratsu** [sourcegraph/sourcegraph#19150]
The publisher links on extension pages will navigate to a 404 page

![image](https://user-images.githubusercontent.com/1308560/111226758-cddbe780-859e-11eb-936d-8fd0c8bdacd7.png)

#### Steps to reproduce:

1. Navigate to an extension page (https://sourcegraph.com/extensions/sourcegraph/code-ownership) or (https://sourcegraph.com/extensions/chris/token-highlights)
2. Click on the hyperlink below the publisher

#### Expected behavior:
1. Navigate to a user page with info about the user

#### Actual behavior:
1. Navigates to a user/org page (see header) but there's also a 404 message on the page

**Comment by Joelkw** [comment]
I'm not quite sure what the intended behavior of this is -- we don't seem to give much love/maintenance to the user and org pages as is, and it's not clear to me that's the best place to take people. CC @felixfbecker do you have any relevant historical knowledge of our hopes for linking to a publisher's "user" page?

**Comment by muratsu** [comment]
A quick solution is to disable the hyperlink. Navigating to a 404 page is a bad experience.

**Comment by felixfbecker** [comment]
There was probably a thought that at one point we'd have more of a social profile for users like GitHub. I think we had an empty page for that this linked to, and that must have been removed in the navigation cleanup process, hence now there's a 404. We can just remove the link.
