### ISSUE TITLE
No entrypoint for managing repos if the user hasn't added a code host

### ISSUE THREAD

**Issue by arussellsaw** [sourcegraph/sourcegraph#19161]
Now that we have the 'public repos' box, we want users to be able to add those repos without connecting a code host, however right now there's no way to access the manage repos page without adding a code host. we should also probably make sure the manage repos page understands the current state when loaded without a code host, as it will show options that don't make any sense at the moment, eg 'selected repos'. we should probably get rid of the entire top box.

this is a blocker for #19139

**Comment by quinnkeast** [comment]
We have a state in the design for the manage repos view for when the user can add other public repos, but hasn't connected a code host:

<img width="875" alt="CleanShot 2021-03-16 at 10 10 33@2x" src="https://user-images.githubusercontent.com/6304497/111283953-ef40e000-863f-11eb-84b8-fc6b949468a0.png">

[Link to comment in Figma for reference](https://www.figma.com/file/zXvqCASHDzmvKbrAl1EVsd?node-id=700:26794#68522674).
