### ISSUE TITLE
search: settings page always reports 1 shard

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#19163]
See this customer issue for an example where we had 600Mb of content on one shard. https://github.com/sourcegraph/customer/issues/246

Or alternatively, see https://sourcegraph.com/github.com/kubernetes/kubernetes/-/settings/index. I would suspect that kubernetes repo is big enough to have more than one shard.

We need to correctly report shard count, since it is useful information for debugging issues. This will likely involve following the call path from our GraphQL backend all the way down into zoekt's List implementation.

We could also possibly be only indexing onto 1 shard, which would be a bad bug. Confirming by checking shards comparing shard counts on the zoekt-webserver filesystems vs what sourcegraph.com reports would help here.

**Comment by stefanhengl** [comment]
This seems to be a reporting issue. I compared shard count for https://sourcegraph.com/github.com/WireGuard/wireguard-linux/-/settings/index v. shards on zoekt-webserver. We report 1 shard but zoekt-webserver actually has 9 shards, which fits to the size of 842mb. I will track down where we loose the correct shard count next.
