### ISSUE TITLE
Create a yq script to update images in-place

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#19189]
The `yq` command should take 

`srcimage --image frontend` will return `gcr.io/frontend:123@sha256:asddfbvc` 

yq should replace image in-place
`| yq base/appName/appName_deployment.yaml '{.spec.frontend.deployment.image.}'`

```bash


for i in $images; do 

srcimage --image $i | yq base/$i/$i_deployment.yaml '{.spec.image.$i}' 

done

```

**Comment by davejrt** [comment]
closed by https://github.com/sourcegraph/deploy-sourcegraph-updater-test/pull/262
