### ISSUE TITLE
Docs - Migrating from Docker-Compose to Kubernetes

### ISSUE THREAD

**Issue by airamare01** [sourcegraph/sourcegraph#19194]
From a customer:
`We currently deploy sourcegraph via docker-compose, but should probably upgrade to a Kubernetes based deployment based off our server size. Is there documentation on migrating a server from docker-compose to Kubernetes while keeping user config, repos etc?`

Current documentation covers migration from a single docker image to docker compose and can be found [here](https://docs.sourcegraph.com/admin/install/docker-compose/migrate) 

Solution:
Doc creation on how to use a db-dump from docker-compose into a Kubernetes deployment.

**Comment by virginiaulrich** [comment]
@dan-mckean another one for the product backlog (does such a think exist) that is more about do we want to provide avenues for this or not?
