### ISSUE TITLE
insights: support querying per-repository insights

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#19204]
The code insights backend:

1. Already stores all insights data points per-repository (we record 1 data point per repo on Sourcegraph.)
2. Stores all the info we need to filter by repository, including the `repo_name` per data point and a Postgres trigram index over that field so that we can allow filtering by a regexp like `github\.com/myorg.*` or similar.
3. Stores the `repo_id` field along with every data point, so that we can determine whether or not the person querying the data has access to that repository (otherwise we might be giving away the fact that repo exists, or exposing similar low-risk private info.)

The only thing the backend _doesn't_ do right now is actually expose that granularity of information over GraphQL. We currently only support querying an aggregated count (i.e. sum all the per-repo data points) and [we implement this query here](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:insights+file:store+SUM&patternType=literal).

The following DB query would give us the data we want per-repository:

```sql
SELECT sub.time_bucket,
	SUM(sub.max),
	sub.repo_id,
	sub.metadata
FROM (
	SELECT time_bucket(INTERVAL '15 days', time) AS time_bucket,
		MAX(value),
		m.metadata,
		series_id,
		repo_id
	FROM series_points p
	LEFT JOIN metadata m ON p.metadata_id = m.id
	WHERE %s
	GROUP BY time_bucket, metadata, series_id, repo_id
	ORDER BY time_bucket DESC
) sub
GROUP BY time_bucket, repo_id, metadata
ORDER BY time_bucket DESC
```

There are only two challenges here:

1. Integrate the above SQL query into our codebase, particularly the DB store and GraphQL layer. Likely by introducing a new `SeriesPointsPerRepo` method, accepting e.g. a regex search query to filter based on.
2. Ensuring we handle the security aspects:
    * The obvious thing to do is to only return data points if `repo_id` is the ID of a repo that the requester has access to. There are existing ways to check this easily, and we would do it in the GraphQL layer most likely. Ask in #dev-chat for how to do this ("I have repository IDs I need to confirm the user has access to view, how would I do that?")
    * The alternative thing to consider would be: do we *want* to allude to the fact that some results exist, you just can't see what they are? For example, it might even make sense to _not_ check if the user has access to those repos (being very careful to ensure we only expose the repo name) and allow this on enterprise instances where it would not be a security concern and perhaps even desirable but NOT sourcegraph.com (where we expect to have private repositories and exposing "a repo by the name of github.com/microsoft exists" would be considered a security issue.

**Comment by rounakdatta** [comment]
Hi @slimsag is this issue open/available for working upon? If so, can I start designing the implementation?

**Comment by coury-clark** [comment]
This issue is out of date, closing with context:
1. Repo permissions are now resolved at query time for each request
2. Repo name regex matching / exclusion is implemented as part of the `insights` GraphQL node
