### ISSUE TITLE
Sourcegraph should run on ARM64 (aarch64) 

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#19208]
#### Feature request description

Sourcegraph should run on arm64 (aarch64) machines natively 

#### Is your feature request related to a problem? If so, please describe.

More software is being compiled for the arm64 architecture. 
Efforts such as the [Docker M1 Tech Preview](https://docs.docker.com/docker-for-mac/apple-m1/) are enabling more software for this architecture. 
Some team members also would like to use M1 Macbooks and we should support them in being able to run Sourcegraph on those machines. 

#### Describe alternatives you've considered.

While it may be possible to run Sourcegraph on arm64 via emulators such as QEMU, users would suffer worse performance. 

#### Additional context

GCP currently does not provide arm64 VMs. We would need to use [buildx](https://docs.docker.com/buildx/working-with-buildx/#build-multi-platform-images) or modify our build pipeline to support cross-compiling.

**Comment by techknowlogick** [comment]
Equinix Metal, Oracle Cloud, and AWS all have arm64 offerings.

cc: @vielmetti (who is/was? affiliated with the WorksOnArm program)
