### ISSUE TITLE
Stats button disappears momentarily when typing in the search bar

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#19230]
Chrome browser. Reproduced on Mac and Windows

https://user-images.githubusercontent.com/888624/111533410-f93c0f00-8723-11eb-81d4-0390497de841.mp4

CC @sourcegraph/frontend-platform @sourcegraph/search, don't know who the right team is for this.

**Comment by limitedmage** [comment]
It's the stats button flashing while typing. This happens with or without streaming search turned on. Local repro requires `experimentalFeatures.searchStats` enabled.

**Comment by limitedmage** [comment]
@tjkandala @sourcegraph/extensibility I *think* this might be a regression from #18898 which refactored `ActionsNavItems`
