### ISSUE TITLE
References tab jitters while typing

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#19243]
Chrome browser on Mac.

Go here and type: [url](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/search/input/toggles/Toggles.tsx#L49:14&tab=references)

https://user-images.githubusercontent.com/888624/111557886-cbb68c00-874a-11eb-94ce-9ba27b7f6f91.mp4

Don't know who the clear owner is for this.

**Comment by tjkandala** [comment]
This was fixed in #19245
