### ISSUE TITLE
Remove unused IP addresses

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#1925]
Removed unused static IP addresses: https://console.cloud.google.com/networking/addresses/list?project=sourcegraph-dev&authuser=1&organizationId=1006954638239

We currently have 13 unused IP addresses. I would just go delete them, but filing this issue for visibility. cc @sqs @beyang just want to confirm if we need to hold onto any of these ip addresses.

**Comment by beyang** [comment]
Sounds good, delete away

**Comment by keegancsmith** [comment]
Done
