### ISSUE TITLE
Insights charts sometimes have dots, sometimes don't

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#19284]
![image](https://user-images.githubusercontent.com/10532611/111693495-fbd85a80-8830-11eb-960b-af72b759f157.png)

Seems to be some kind of race condition in the charting lib (recharts)

**Comment by vovakulikov** [comment]
@felixfbecker close this since this has been fixed by https://github.com/sourcegraph/sourcegraph/pull/19556
