### ISSUE TITLE
Sometimes fails to display language breakdown labels until you click in

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#19285]
![image](https://user-images.githubusercontent.com/11967660/109369562-9efd0c00-7851-11eb-99f2-2320ed9432d8.png)
I can reliably reproduce this just by visiting /insights on .com and refreshing until I get a load with the label missing. A customer also ran into this recently and was wondering why there were no labels.

**Comment by vovakulikov** [comment]
@Joelkw @felixfbecker Close this since that problem has been fixed by this PR https://github.com/sourcegraph/sourcegraph/pull/19556
