### ISSUE TITLE
Typescript Link broken in Chrome Web Store

### ISSUE THREAD

**Issue by Hocdoc** [sourcegraph/sourcegraph#193]
In the Chrome Web Store of Sourcegraph https://chrome.google.com/webstore/detail/sourcegraph/dgjhfomjieaadpoljlnidmbgkdffpack the link to the Typescript example is broken (Http Error 404): 

```
* TypeScript: https://github.com/angular/angular/blob/master/modules/%40angular/benchpress/src/reporter/console_reporter.ts
```

**Comment by chrismwendt** [comment]
Thanks for reporting! I permalink'ed all of the examples.
