### ISSUE TITLE
Unused disks in gcloud

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#1930]
Are these safe to delete?

https://console.cloud.google.com/compute/disks?organizationId=1006954638239&project=sourcegraph-dev&diskssize=50&disksquery=%255B%257B_22k_22_3A_22userNames_22_2C_22t_22_3A10_2C_22v_22_3A_22_5C_22_5C_5C_5C_22_5C_5C_5C_22_5C_22_22%257D%255D

**Comment by ggilmore** [comment]
Deleted.
