### ISSUE TITLE
File tree trigger icon colors are inconsistent

### ISSUE THREAD

**Issue by tjkandala** [sourcegraph/sourcegraph#19317]
Icon colors should be the same for both "open" and "close" file tree buttons, in both idle and hover states. Refer to [Figma](https://www.figma.com/file/p7g56TD2qFbqxRJ4ODrbo7/RFC-250-Action-items-bar-%5BFinal-review%5D?node-id=1186%3A43057)

**Comment by muratsu** [comment]
The hover on "Collapse Panel" doesn't seem to be working right now
![image](https://user-images.githubusercontent.com/1308560/117192784-f9a56d80-ad96-11eb-8a10-80be5980f2f4.png)

**Comment by Joelkw** [comment]
Closing since not part of design anymore.
