### ISSUE TITLE
Hover not showing find definition on github

### ISSUE THREAD

**Issue by milind-shakya-sp** [sourcegraph/sourcegraph#1931]
- **Sourcegraph version:**  2.13.5
- **Platform information:**  mac osx high sierra

#### Steps to reproduce:

1. run docker containers
2. install chrome extension

#### Expected behavior:

Hover should show, Find definition, find references, find implementations

#### Actual behavior:
Hover shows only `references`
<img width="693" alt="screen shot 2019-01-16 at 6 24 19 pm" src="https://user-images.githubusercontent.com/43146933/51285275-501af200-19bc-11e9-81ab-66db338c49d0.png">

**Comment by ryan-blunden** [comment]
Hi @milind-shakya-sp, could you provide a link to the file this is happening on?

**Comment by milind-shakya-sp** [comment]
hi, here you go.

https://github.com/django/django/blob/master/django/apps/registry.py


<img width="1075" alt="screen shot 2019-01-23 at 2 39 30 pm" src="https://user-images.githubusercontent.com/43146933/51632220-c1a6f300-1f1c-11e9-9233-7935eaf45c21.png">

**Comment by sqs** [comment]
@milind-shakya-sp 	This is due to the limitations of Sourcegraph's Python support as deployed to Sourcegraph.com right now. See https://sourcegraph.com/extensions/sourcegraph/basic-code-intel under the "Limitations" section at the end.

We are working on an extension that uses the Python language server to provide precise, cross-repository code intelligence. It's at  https://sourcegraph.com/extensions/sourcegraph/python, but it is not currently enabled or deployed on Sourcegraph.com yet. (You would need to follow the deployment instructions there to use it.)

**Comment by milind-shakya-sp** [comment]
Hi @chrismwendt and @sqs. Thanks for the info and updates! 

I am actually running the sourcegraph server locally on docker. is there a particular revision of the image i should pull to get the updates?

**Comment by milind-shakya-sp** [comment]
Another thing to note is that the hover works fine on sourcegraph's UI, just not on github with the extension.

![screen shot 2019-01-25 at 4 19 50 pm](https://user-images.githubusercontent.com/43146933/51773547-2b5e0300-20bd-11e9-9fd6-df7388feb753.png)

**Comment by chrismwendt** [comment]
@milind-shakya-sp Oh, my apologies. For local deployment and browser extension integration, you'll need to:

- Enable the `sourcegraph/python` extension at http://localhost:7080/extensions
- Follow the instructions in https://sourcegraph.com/extensions/sourcegraph/python to deploy the Python language server
- Change the Sourcegraph URL in your browser extension to http://localhost:7080 (mine is on 3080 in this screenshot):

![image](https://user-images.githubusercontent.com/1387653/51776939-e2538200-20af-11e9-8400-89083e2acc01.png)

If you don't want to set up the Python language server, you can enable `sourcegraph/basic-code-intel` at http://localhost:7080/extensions to get zero-configuration but less precise code intelligence (check out the [README](http://localhost:7080/extensions)).

**Comment by milind-shakya-sp** [comment]
Is this something that was changed recently? The code intelligence for python was working fine few days back for me when I was using the local deployment.

**Comment by chrismwendt** [comment]
For 2.x instances there's a built-in `langserver/python` extension at http://localhost:7080/extensions/langserver/python that uses the Python language server that is enabled on http://localhost:7080/site-admin/code-intelligence:

![image](https://user-images.githubusercontent.com/1387653/51780128-eb008400-20c0-11e9-9a35-1c62dff32609.png)

**Comment by milind-shakya-sp** [comment]
![screen shot 2019-01-25 at 7 48 37 pm](https://user-images.githubusercontent.com/43146933/51780155-455a0e80-20da-11e9-8a9c-4a3929a7df2e.png)

Yeah I do have that turned on. Unfortunately, the hover issue still exists when when its turned on.
