### ISSUE TITLE
Remove use of gitserver.DefaultClient

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#19356]
Instead we should create one in `main` and pass it around.

One reason we want this is that currently the UserAgent is computed based on the binary name which is a little brittle and means we need to write code like:

https://github.com/sourcegraph/sourcegraph/blob/e5d768576083ee500445b7fcada2a77b658204ea/cmd/gitserver/server/server.go#L361-L366

**Comment by susantoscott** [comment]
This has been done by https://github.com/sourcegraph/sourcegraph/pull/32880
