### ISSUE TITLE
Isolate Storybook configuration inside of the `wildcard` package

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#19350]
**Description**

FE-related configs and scripts are spread across the repo. To simplify codebase exploration, we need to encapsulate this logic into self-contained documented packages. The first step is to encapsulate the Storybook inside of the `wildcard` package.

**Definition of success**
- Storybook config and commands are isolated in the `wildcard` package.
- Stories defined in other packages continue working without any additional change.

**Notes**

Part of the [FE SDK Isolation RFC](https://docs.google.com/document/d/1MpcUDvtBMg2IcYOGGAGNwBZCUljlDMyvqm5UdzMqoOg/edit#).

**Comment by valerybugakov** [comment]
> Stories defined in other packages continue working without any additional change.

Right, this is just about moving the config and some NPM scripts to a `wildcard` package.

**Comment by felixfbecker** [comment]
Is there any benefit to that? If the Storybook contains stories from all the `client` folders, and the config applies to all those stories, it seems a bit confusing that it would live in `wildcard`. E.g. the `.eslintrc.json` config files that live in each `client` subfolder only apply to each  subfolder respectively, but that wouldn't be true for the Storybook config in `wildcard`.

It would also be good to retain the ability to run `yarn storybook` in the root without having to `cd` into a subfolder, since this is a common command used by all teams in their workflow.

**Comment by valerybugakov** [comment]
The main benefit I see here is the front-end code's encapsulation inside of the `client` folder. It's easier to track interdependencies and expose functionality when you're inside of the workspaces. 

For example, to use TS project-references import in Storybook configuration, we need to make it aware of the workspaces. It seems more natural to do it inside the `wildcard` package than outside of the `client` folder. In the future, we might add additional logic to `preview.js`, which will use modules/patterns defined in the `wildcard` package.

My mental model for Storybook configuration is closer to Webpack config. Webpack bundles modules from different packages, but the `web` package owns it. It's colocated with the application that is the primary consumer of this functionality. In the bright future, all the reusable components will live under `wildcard`, that's why I think it a good place for Storybook.

Let me know it still doesn't make sense. Maybe I'm biassed in some way.
cc @pdubroy

**Comment by pdubroy** [comment]
It sounds like there are potentially two separate decisions here:

1. Putting our Storybook config into one of the Yarn-workspace-managed packages, and
2. Whether `wildcard` is the right package.

Does that sound right?

I'm agnostic on (1). Regarding (2), I think I agree with @felixfbecker. The `wildcard` package feels like it should be a "foundational" package — higher-level packages should depend on `wildcard` but not vice-versa. So if there are benefits of putting the storybook config in a separate package, I'd consider adding a new package for that purpose.

**Comment by valerybugakov** [comment]
@pdubroy, that's even better; I agree with this approach. 
I wanted to keep things simple from the start — avoid creating new packages until we understand all functional parts that we want to extract into standalone packages. This is mentioned in the [RFC](https://docs.google.com/document/d/1MpcUDvtBMg2IcYOGGAGNwBZCUljlDMyvqm5UdzMqoOg/edit#) `next steps #9`  that in the bright future, we will have multiple packages for configs, etc.

I see that it's clear already that the `Storybook` config needs to be extracted into a separate package -> so I can look into how much work it would be to implement a solution for this issue with new a package right away.
