### ISSUE TITLE
Close button on hover needs padding

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#1935]
![screenflow](https://user-images.githubusercontent.com/133014/51292046-45f9f300-19be-11e9-9334-667525f3e1ef.gif)

**Comment by felixfbecker** [comment]
@ryan-blunden I'm not clear what exactly you were imagining here, do you remember?

**Comment by ryan-blunden** [comment]
It looks a bit janky when the `x` overlaps the symbol text on hover. Not a big deal though, so I'll close this.
