### ISSUE TITLE
Upgrade to Postgres 12

### ISSUE THREAD

**Issue by pecigonzalo** [sourcegraph/sourcegraph#19364]
In order to support a number of features in our product, we need to upgrade all databases to `min > 12`. This requires updating all containers and systems to support this.

A non-exhaustive list of containers:
- https://github.com/sourcegraph/infrastructure/blob/main/docker-images/postgres-11.4/Dockerfile
- https://github.com/sourcegraph/sourcegraph/blob/main/docker-images/codeinsights-db/build.sh (seems to use 12 already, but this is also timescale)
- https://github.com/sourcegraph/sourcegraph/blob/main/docker-images/codeintel-db/build.sh
- https://github.com/sourcegraph/sourcegraph/blob/main/docker-images/postgres-11.4/build.sh

I believe the first step is creating a new container in `infrastructure/docker-images/postgres-12` similar to the one in `/postgres-11.4` and building that container, then porting all databases to use that version and test.

Our Cloud environment is already running 12, so we know the version is compatible, but we need to ensure our helper scripts in the container still work.

Additionally, I would rename `sourcegraph/docker-images/postgres-11.4/` to `sourcegraph/blob/main/docker-images/pgsql/` or similar, as we do for `codeintel-db`. Using a generic name as the version itself is pinned in `infrastructure/` and the docker image itself.

**Comment by pecigonzalo** [comment]
Something missing here is some guidance on how to upgrade (or a script for doing it) for customers that use the included pgsql.

**Comment by pecigonzalo** [comment]
Also `single-docker`

**Comment by daxmc99** [comment]
Completed
