### ISSUE TITLE
Request developer feedback on dogfood pipeline

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#19377]
Developers should give us feedback on argocd in dogfood.

Created this [form](https://docs.google.com/forms/d/1XEc3ZME50aWWV3BNg8h4E22rwX4aXpRRV7KEpl8J26U/edit)

TODO:

- [ ] Share video on how to use in handbook & #dev-announce
- [ ] Update handbook with how to use ArgoCD

**Comment by ggilmore** [comment]
@daxmc99 Could you update this description with creating argo cd documentation (creating a video suitable for dev-announce)?

**Comment by daxmc99** [comment]
Updated the issue description
