### ISSUE TITLE
Product comparison chart

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1937]
We should make a chart comparing Sourcegraph to all the potential alternatives, including:

• git GUI clients like gitkraken and sourcetree
• code search engines like Oracle OG and hound
• repository hosts like GitHub and GitLab
• IDEs like IntelliJ, VSCode

Some of these tools are overlapping. Some aren't overlapping but people might think they are (or just wonder how they would fit in together in the dev workflow). Should be a visual chart.

HT @beyang

**Comment by christinaforney** [comment]
We should definitely still do this!

**Comment by ryan-blunden** [comment]
Grouping comparisons by type e.g *Sourcegraph vs. IDE, then Sourcegraph vs. code search* would work well, as the columns/features to compare are specific for that kind of thing.

**Comment by sqs** [comment]
This is live at https://about.sourcegraph.com/workflow#other-tools
