### ISSUE TITLE
Multiple definitions when using basic-code-intel

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1939]
The intent is that the basic-code-intel extension's definition provider is very strict: it tries to never return false positive definition locations. If it detects ambiguity, then it should return no definitions instead of returning all possible definitions. (References are different; false positive references are much less bad because the common case for references is that the user scans them all; for definitions they usually expect to go to the single definition.)

@felixfbecker 	reported that this was not working as intended in a particular case where the var's name started with `$`. The likely reason for this is that basic-code-intel strips `$` from names when it searches for symbols, and so it finds the wrong symbol definition (`var schema` not `var $schema`).

**Comment by felixfbecker** [comment]
Another example:

![image](https://user-images.githubusercontent.com/10532611/51861376-55712880-233c-11e9-967c-dd737eba3f0f.png)

![image](https://user-images.githubusercontent.com/10532611/51861412-6ae65280-233c-11e9-8ade-ea2baf4059ac.png)

**Comment by sqs** [comment]
This will now be solved by @chrismwendt’s work. However the fix is quick so I will do it tonight to avoid this bug lasting for longer (I meant to fix it earlier).

**Comment by sqs** [comment]
This is covered by #2035 and does not require any extra work beyond that. Closing.
