### ISSUE TITLE
`contains(...)` interaction with `select` doesn't reveal partial/exhaustive results

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#19401]
This is an impressive query:

[`repo:^github\.com/sourcegraph/ repo:contains(file:README\.md) type:symbol Search select:repo`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/+repo:contains%28file:README%5C.md%29+type:symbol+Search+select:repo&patternType=literal)

It says "search in repos in the sourcegraph org containing README files for a symbol `Search` and then give me the repos". We handle the logic correctly. The issue is that we don't propagate information that indicates we get partial results (traditionally, `limitHit`). What happens is that we sometimes get back 4 repos, 6, or 7, or whatever, but we don't say it's incomplete. There are 39 repos that satisfy this query, adding 10000 shows the exhaustive result [`repo:^github\.com/sourcegraph/ repo:contains(file:README\.md) type:symbol Search select:repo count:10000`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/+repo:contains%28file:README%5C.md%29+type:symbol+Search+select:repo+count:10000&patternType=literal). _Warning_: sometimes I see that the result says there are 39 but streaming search appears not to show them all--I can't confirm and dig into this right now. 

Either way, we should propagate the `limitHit` signal that not all results are show in the case where `count` is absent. I think what's happening here is that we short circuit search after `contains` expands. In which case, we need to propagate `limitHit`.

**Comment by camdencheek** [comment]
Can no longer reproduce. I am correctly getting a "Result limit hit" message now.
