### ISSUE TITLE
Changing primary email from user settings does not work

### ISSUE THREAD

**Issue by indradhanush** [sourcegraph/sourcegraph#19410]
- **Sourcegraph version:** 90888_2021-03-24_27450a0
- **Platform information:** Linux. i3wm. Firefox 86.0.1

#### Steps to reproduce:

1. Visit https://sourcegraph.com/users/<your-username>/settings/emails
2. (Optional) Add a secondary email if you don't have one already and verify it.
3. Try to change primary emails

#### Expected behavior:

Primary email should change from the dropdown.

#### Actual behavior:

https://user-images.githubusercontent.com/2682729/112275319-80016680-8ca5-11eb-8411-2b7adaedc9aa.mp4

**Comment by pdubroy** [comment]
I was able to reproduce. This indeed looks like a bug. Thanks!

**Comment by umpox** [comment]
I think I've seen a similar issue elsewhere, should be a quick fix, going to assign myself
