### ISSUE TITLE
Remove credentials from external_service_repos.clone_url

### ISSUE THREAD

**Issue by arussellsaw** [sourcegraph/sourcegraph#19420]
Now that we're encrypting external service config in the external_services table we want to prevent ourselves from leaking that info anywhere else, right now we store the plaintext token in clone_url of external_service_repos. We should refactor this to construct the clone url at runtime from the external service config.

originally this work was plannned as part of refactoring gitserver to use a credential helper, but we forgot to re-spec it when we found an alternate approach.

more context here: https://sourcegraph.slack.com/archives/CMBA8F926/p1616596856052900

**Comment by eseliger** [comment]
This might affect https://github.com/sourcegraph/sourcegraph/issues/19419, so maybe that ticket is a pre-requisite.

**Comment by arussellsaw** [comment]
closed by https://github.com/sourcegraph/sourcegraph/pull/20021
