### ISSUE TITLE
Empty search results display both "No results" and "Result limit hit."

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#19432]
- **Sourcegraph version:** 3.26

#### Steps to reproduce:

1. Go to demo.sourcegraph.com
2. Search for `lang:xml`

#### Expected behavior:
There are no XML hits. I should see a "No results" info.

#### Actual behavior:
I see both:
- a "No results" info
- an extraneous and confusing "Result limit hit. Modify your search with count: to return additional items"
![image](https://user-images.githubusercontent.com/25070988/112383878-fcb83300-8ced-11eb-8ebd-2904cdddf467.png)

**Comment by malomarrec** [comment]
Tagging similar issue in #20138 to feed into prioritisation work.

**Comment by lguychard** [comment]
Fixed by https://github.com/sourcegraph/sourcegraph/pull/19438
