### ISSUE TITLE
Monaco editor on user settings is really small

### ISSUE THREAD

**Issue by ijsnow** [sourcegraph/sourcegraph#1943]
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:** Mac, Firefox
#### Steps to reproduce:

1. Got to sourcegraph.com, log in and navigate to your user settings

#### Expected behavior:

The editor is not really small

#### Actual behavior:

The editor is really small

**Comment by nicksnyder** [comment]
Screenshot?

**Comment by vanesa** [comment]
Screenshot Chrome 
![image](https://user-images.githubusercontent.com/9110008/51366797-1fe96580-1b1a-11e9-867d-00ba2bd88cba.png)
VS
Screenshot Firefox:
![image](https://user-images.githubusercontent.com/9110008/51366807-2c6dbe00-1b1a-11e9-96ed-41cc972d04ae.png)

**Comment by ijsnow** [comment]
Thanks Vanesa! Seems like its a Firefox vs Chrome problem

**Comment by vanesa** [comment]
Yes, it seems like while Chrome is able to receive the height setting of `400px` when `this.props.height` is undefined, but Firefox changes it to `5px`.
Chrome `clientHeight` vs. Firefox:
![image](https://user-images.githubusercontent.com/9110008/51979448-84b89e80-24d0-11e9-83f1-d6bdb8114e06.png)

![image](https://user-images.githubusercontent.com/9110008/51979425-736f9200-24d0-11e9-9184-4b29995b4c11.png)
