### ISSUE TITLE
Markdown headings in hovers are too large

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#1950]
**Sourcegraph version:** 3.0 beta

Code that produces the Markdown is at - https://github.com/sourcegraph/sourcegraph-extension-samples/blob/master/dockerfile-lint-extension/extension/src/ui.ts#L38

<img width="859" alt="screen shot 2019-01-17 at 3 22 00 pm" src="https://user-images.githubusercontent.com/133014/51355402-f114b600-1a6b-11e9-95c0-4965d6907f4a.png">

<img width="867" alt="screen shot 2019-01-17 at 3 21 42 pm" src="https://user-images.githubusercontent.com/133014/51355403-f1ad4c80-1a6b-11e9-8009-01599b636668.png">

**Comment by sourcegraph-demo** [comment]
Also affects definition hovers who's content contains markdown.

<img width="907" alt="screen shot 2019-01-18 at 11 55 22 am" src="https://user-images.githubusercontent.com/46826578/51410009-3bec0780-1b18-11e9-8f9a-1197b3e632a7.png">

**Comment by vanesa** [comment]
I'm not able to reproduce this:
@felixfbecker do you still have the issue?

![image](https://user-images.githubusercontent.com/9110008/52534186-a7c13900-2d81-11e9-83f5-9d748d145c36.png)

**Comment by felixfbecker** [comment]
The screenshot you posted doesn't include a markdown heading. Note @ryan-blunden posted this issue, not me

**Comment by vanesa** [comment]
I haven't been able to get the Docker lint extension to work and am verifying with Ryan that the issue isn't on my end. 

Isn't this the hover you posted?
![image](https://user-images.githubusercontent.com/9110008/52534353-f079f180-2d83-11e9-8ade-a5cc6b6f8461.png)

I posted the same hover just at a different area that was also showing a markdown title: `# the rest of your classic application...`. 
Is that not a markdown title?

**Comment by felixfbecker** [comment]
That looks like a python comment within a code block.

**Comment by vanesa** [comment]
Ah yes, it might have been rendered wrongly as markdown back when @sourcegraph-demo posted the screenshot.

**Comment by ryan-blunden** [comment]
Still occuring.

<img width="862" alt="screen shot 2019-02-10 at 10 09 48 am" src="https://user-images.githubusercontent.com/133014/52537487-5d59a100-2d1c-11e9-9735-a532be0e5920.png">
<img width="874" alt="screen shot 2019-02-10 at 10 09 34 am" src="https://user-images.githubusercontent.com/133014/52537488-5d59a100-2d1c-11e9-97f6-1dadd6a65b59.png">

**Comment by vanesa** [comment]
@francisschmaltz what do you think about this styling?

![image](https://user-images.githubusercontent.com/9110008/52547859-ad646080-2e0d-11e9-93a7-456977de6689.png)

**Comment by francisschmaltz** [comment]
They should be Medium font weight.

**Comment by vanesa** [comment]
@francisschmaltz Do we have a style guide that includes the hover overlays that I can use?

**Comment by francisschmaltz** [comment]
@vanesa I'll work on adding that to zeppelin style guide this week!

**Comment by vanesa** [comment]
@francisschmaltz any update on the style guide?
