### ISSUE TITLE
Feature request: Add the ability to search or filter by GitHub topics

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#19507]
#### Feature request description

Add a new operator that allows users to search or filter searches by GitHub topics to the Sourcegraph search query.

#### Is your feature request related to a problem? If so, please describe.

Repos for different teams are listed under different GitHub topics, and currently, there is no easy way to sort/filter them without making changes in the backend

#### Describe alternatives you've considered.

Setting up repogroups, but that involves input the lists of repos manually.

**Comment by camdencheek** [comment]
Oh, this is done. Github and GitLab topics are now automatically ingested and can be searched with `repo:has.topic(your-topic)`.
