### ISSUE TITLE
Review and add visual regression tests for design refresh

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#19520]
We should review the effectiveness of our current visual regression tests and their coverage of areas defined in the [design refresh scope](https://docs.google.com/document/d/16lCKUwbbqbZ03TdesGMHyBpqPzhdCaoLm0oBSpNb-Xw/edit#heading=h.esslulm1pi4r).

**For example:**
We have a GlobalNavBar story [defined in Storybook](https://5f0f381c0e50750022dc6bf7-hotdlwhehx.chromatic.com/?path=/story/web-nav-globalnav--anonymous-viewer). We run visual snapshots against this component on every frontend build. This will be useful for developers and designers to determine the scope of engineering changes when implementing changes for the design refresh.

These regression tests should cover both the redesign view and the 'current' view.

If we see any areas effected in the design scope that are not covered by visual snapshots, we should add them!

Notes:
- Key areas:
    - [x] File Tree. Currently partially supported through Percy. Would be useful to have in Storybook but not essential
    - [X] NavBar. Covered in Storybook: https://5f0f381c0e50750022dc6bf7-kbvryslswx.chromatic.com/?path=/story/web-nav-globalnav--anonymous-viewer
    - [x] Symbol tree/search. Not captured in either Percy or Storybook. Needs to be done. TICKET: https://github.com/sourcegraph/sourcegraph/issues/19736
    - [x] Code view. Not captured in either Percy or Storybook. I think it would be quickest to capture this through Percy, as we have some integration tests that cover this area. 
    - [x] Reference Panel - PR to add branded component to Storybook: https://github.com/sourcegraph/sourcegraph/pull/19647. Should also be tested through Percy as this component can become quite involved, as that's difficult to replicate through Storybook 
    - [X] Hover Overlay. Covered in Storybook https://5f0f381c0e50750022dc6bf7-kbvryslswx.chromatic.com/?path=/story/shared-hoveroverlay--loading
    - [x] Branch/Tag/Commits selector. Not captured in either Percy or Storybook. Needs to be done. As this is more of a self container component than a typical page, it would make sense to add to Storybook if possible. TICKET: https://github.com/sourcegraph/sourcegraph/issues/19735
    - [X] Search Results. Covered in Storybook https://5f0f381c0e50750022dc6bf7-kbvryslswx.chromatic.com/?path=/story/web-search-results-streaming-streamingsearchresults--standard-render
    - [X] Diff View. I believe this is also covered in Storybook: https://5f0f381c0e50750022dc6bf7-kbvryslswx.chromatic.com/?path=/story/web-diffs-filediffnode--all-file-node-states-overview

Update:
- Large parts of these areas are now covered through https://github.com/sourcegraph/sourcegraph/pull/19648
- For symbol search and the branch/tag/commits work, we have created two tickets to add Storybook tests:
  - https://github.com/sourcegraph/sourcegraph/issues/19735
  - https://github.com/sourcegraph/sourcegraph/issues/19736

**Comment by felixfbecker** [comment]
There are also app-wide screenshots taken from integration tests for Percy, which would help too for screens like the file viewer with the file tree, the search results page, etc.

**Comment by umpox** [comment]
Note: Closing this old issue as now the remaining tasks have been coverage in Storybook/Percy
