### ISSUE TITLE
Request for patch release on 3.26

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#19529]
@sourcegraph/distribution I am requesting the following commits be included in a patch release. They are already merged into `main`:

The intent of the questions below is to ensure we keep Sourcegraph high quality and [only create patch releases based on a strict criteria.](https://about.sourcegraph.com/handbook/engineering/releases#when-are-patch-releases-performed) If you can answer yes to many or most of these questions, we will be happy to create the patch release.

- https://github.com/sourcegraph/sourcegraph/commit/842077b78d5d115315263b5ca0e559a33aca8603
- https://github.com/sourcegraph/sourcegraph/commit/c534e172f9fd12c5fdb4ec21811642e1226956d4
- https://github.com/sourcegraph/sourcegraph/commit/ff7e667d7bb4b4aaddd6f1fc05094f219ab818a6
- https://github.com/sourcegraph/sourcegraph/commit/b97a052236d24abeca623648012ff87ad860d2c0
- https://github.com/sourcegraph/sourcegraph/commit/99b6c2f39c650550462bdc523fe79af84b1de84e
- https://github.com/sourcegraph/sourcegraph/commit/3ada0927878fdc7362a6ba1f44a4d0ffc382a7dd

I have read [when and why we perform patch releases](https://about.sourcegraph.com/handbook/engineering/releases#when-are-patch-releases-performed) and answer the questions as follows:

> Are users/customers actively asking us for these changes and cannot wait until the next full release?

- P0 customer issue, details here: https://github.com/sourcegraph/customer/issues/263

> Are the changes extremely minimal, well-tested, and low risk such that not testing as we do in a full release is OK?

- Yes, relatively minor and changes have been tested on sourcegraph.com

> Is there some functionality completely broken that warrants redacting the prior release of Sourcegraph and advising users wait for the patch release?

No

> This will interrupt our regular planned work and release cycle, taking 3-6 hours of our time, and will take up all of our site admin's valuable time by asking them to upgrade or producing noise for them if they don't need to upgrade.
>
> Do you believe the changes are important enough to warrant this?

Yes, it is a priority for the customer linked above.

> Patch releases are a signal we can do something better to improve the quality of Sourcegraph. Have you already scheduled a call (or created a google doc) to perform a [retrospective](https://about.sourcegraph.com/retrospectives) and identify ways we can improve?

Not yet.

---

**For the [release captain](https://about.sourcegraph.com/handbook/engineering/releases#release-captain)** - after reviewing and approving this request:

- If there is [already an upcoming patch release](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+), add the listed commits alongside a link to this issue
- If there is no upcoming patch release, create a new one:
  - Update [`dev/release/release-config.jsonc`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/release/release-config.jsonc) with the patch release in `upcomingRelease` and `releaseDate` (and open a PR to `main` to update it)
  - `yarn release tracking:issues`
  - Add the listed commits alongside a link to this issue to the generated [release tracking issue](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+)

Comment and close this issue once the relevant commit(s) have been cherry-picked into the release branch.

**Comment by lguychard** [comment]
Added https://github.com/sourcegraph/sourcegraph/commit/842077b78d5d115315263b5ca0e559a33aca8603 to this patch release request. It's a very minor change, but without it several UI elements appear completely broken on 3.26 (link to non-existent repo instead of the code monitoring pages)

**Comment by ryanslade** [comment]
In order to test this I've done the cherry picking locally however I needed to resolve some conflicts when applying ff7e667.

Also, 99b6c2f includes a migration which causes us to jump ahead 3 migrations. Does this mean we need to include the commits that introduce the the other migrations steps too?

**Comment by daxmc99** [comment]
Due to concerns around the database migrations, we decided to cut this patch release directly from the main branch (at 0ee5f2560eef687f5e75b5be576af131e2c907bc ).

**Comment by pecigonzalo** [comment]
@daxmc99 I re-opened as the closing PR was the release captain update, feel free to close again if the release is done.

**Comment by daxmc99** [comment]
The release is done now, 
images have been updated https://hub.docker.com/layers/sourcegraph/server/3.26.1/images/sha256-879859fc317827d53d99f2f348a6cceebec6760103616500d866ecb2e820bc6f?context=explore 

deploy-sourcegraph repos have also been updated https://github.com/sourcegraph/deploy-sourcegraph/tree/v3.26.1/base
