### ISSUE TITLE
Add CNAME for storybook `main` branch deployment

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#19522]
#### Expected behavior:
I can go to https://storybook.sgdev.org to view our latest components

#### Actual behavior:
I have to navigate to: https://main--5f0f381c0e50750022dc6bf7.chromatic.com/ to view this. This URL isn't memorable or suitable for keyboard input so my only real solution is to bookmark it and pass it on to others

**Comment by felixfbecker** [comment]
This would be amazing. Maybe @sourcegraph/distribution can help or advise how to do this?

**Comment by pecigonzalo** [comment]
Is that url `--*` a reference to the commit it was created from? If its static, we can add it to https://github.com/sourcegraph/infrastructure/blob/main/dns/sgdev.tf

**Comment by umpox** [comment]
@pecigonzalo `5f0f381c0e50750022dc6bf7` is our `appid` and Storybook offers this pattern as a permalink to the latest `main` deployment, so I think it's safe to use 👍

**Comment by pecigonzalo** [comment]
Added in https://github.com/sourcegraph/infrastructure/pull/2446, please review.
