### ISSUE TITLE
View specs from preview link

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#19534]
**Use case**
When I create a batch change, I can share the preview link with a team mate and they can view the specs as well as the proposed impact.

**Feature**
Add batch spec in the preview view

**Customers**
https://sourcegraph.productboard.com/insights/all-notes/organizations/227910

**Comment by LawnGnome** [comment]
In terms of scope, this is what we need to do here:

1. Convert the existing Preview heading on the preview page into a tab bar similar to the one we have on the actual batch change page:

    ![image](https://user-images.githubusercontent.com/229984/116744940-a8b90200-a9af-11eb-8d46-cceef09adac3.png)

    ![image](https://user-images.githubusercontent.com/229984/116745357-cedea200-a9af-11eb-9466-c96a8847cf2d.png)

2. Add a Spec tab like the one on the batch change page.
3. Add the `originalInput` field to the existing batch change GraphQL query, and use that to retrieve the spec.
4. Render the spec on the Spec tab. (We should be able to reuse at least some of the components from the existing batch change spec tab here.)
