### ISSUE TITLE
Search web app does not consume or render file search suggestions

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#19551]
Pretty sure this is a bug, but the expected search suggestion functionality is ill-defined so not sure if this ever mattered. In either case, it's clutter while I'm cleaning up some code.

Basically we have logic that sends file path results for suggestions when a query is of the form:

`repo:thing cmd/searcher`

Note, this is without the `file:` part. Then, for example, and we would receive suggestions for a file paths like `cmd/searcher/README.md` form the backend. I went through the backend code and see that the suggestions show up in the webapp console. And we don't do anything with it in the frontend, it never renders or shows the suggestions. Seems way off 🤷‍♂️

**Comment by rvantonder** [comment]
For some reason I'm struggling to reproduce this on Sourcegraph.com. I can reproduce locally and on k8s.sgdev.org by typing `drivers/` in this [query](https://k8s.sgdev.org/ghe.sgdev.org/sourcegraph/torvalds-linux/-/blob/drivers/input/tablet/gtco.c#L934)

**Comment by lguychard** [comment]
@novoselrok would this still be relevant after your recent work on suggestions?

**Comment by novoselrok** [comment]
Probably not, since this seems specific to the GQL suggestions. Also we would now use the `cmd/searcher` part to look for matching symbols, not file paths.
