### ISSUE TITLE
Refactor relative cross-package imports to absolute ones via package name.

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#19562]
Cross-package imports should rely on package-name instead of the relative path: `../../shared/src/util/strings` -> `@sourcegraph/shared/src/util/strings`.

**Comment by pdubroy** [comment]
I wonder if it would be possible to do this via an ESLint rule that supports `--fix`. From the ESLint's [Working with rules](https://eslint.org/docs/developer-guide/working-with-rules) documentation, it seems that it should be possible to determine the "correct" way to import based on the the file being linted.

**Comment by valerybugakov** [comment]
Found a couple of open-source solutions for this issue. I will try them locally and post an update here. 
If they don't work for our codebase, let's pair on this. 👍
