### ISSUE TITLE
Test that we better communicate the error state of removing codehost HTTP auth and switching to just SSH auth for repo cloning

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#1957]
1. Add an external service connection with Bitbucket Server or any other codehost by adding a `token` or `username` and `password` entry, etc.
2. Sourcegraph will discover repositories from this code host.
3. In the external service, change the `gitURLType` to `ssh` and remove the `token` or `username`/`password` that was previously set. I.e., setup SSH repo cloning authentication instead.
4. Sourcegraph is now aware of the repositories, but it cannot clone them. No indication as to why is given anywhere, except that when visiting the repo mirroring page "Check connection" indicates a 401.

We need this authentication for updating repositories to handle e.g. repository renames, but it is a VERY bad UX that you can end up in a state where:

1. Sourcegraph is aware of repositories, you can see them at /site-admin/repositories
2. Gitserver can clone them (confirmed via `git clone` in a gitserver shell)
3. Sourcegraph cannot clone them (401 error)

I have observed customers running into this.

**Comment by slimsag** [comment]
@nicksnyder I think we should prioritize working on this at least for 3.1, but maybe we can mitigate the issue in 3.0 if someone has a good idea of how to solve this, would @tsenart or @keegancsmith be the right person to work on this?

**Comment by slimsag** [comment]
I've updated description to better explain everything, apologies for the ambiguity.

I agree this is an intersection of #914 and #1811. Let's consider this a specific case in which we should test once we fix those two issues then.

**Comment by keegancsmith** [comment]
In the new syncer, this would break syncing and would be reported to the user when they clicked update on the external service. I think that is good enough to consider this issue solved?

**Comment by nicksnyder** [comment]
> this would break syncing and would be reported to the user when they clicked update on the external service

So the new (broken) external service config would not get saved to the DB in this case due to the invalid config?

If that is the case, then I think it is safe to close this issue.

**Comment by keegancsmith** [comment]
Schema validation is done before saving. Username is a required field since 3.3, so the DB won't be updated and we will fail.

Note: I mentioned the syncer would break. In the case the Schema is correct but something else goes wrong (say invalid token), the DB update will still happen. We will just report back the error to the user. The UI can probably be improved in that case.
