### ISSUE TITLE
Address VPA's recommendations for sourcegraph.com

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#1958]
In https://github.com/sourcegraph/deploy-sourcegraph-dot-com/pull/164, I added a [vertical pod autoscaler](https://cloud.google.com/kubernetes-engine/docs/how-to/vertical-pod-autoscaling) to sourcegraph.com, which can give us more accurate recommendations for what our deployment's resource requests should be set to. 

Here is what it recommends after about a day's worth of monitoring (this output is from a script that I added in https://github.com/sourcegraph/deploy-sourcegraph-dot-com/pull/169:

("cpu"'s units are in fractional cores, and "memory"'s units are in gigabytes)

```json
{
  "cors-anywhere": {
    "cpu": 0.011,
    "memory": 0.021955927833914757
  },
  "frontend": {
    "cpu": 0.379,
    "memory": 5.415829627774656
  },
  "gddo-proxy": {
    "cpu": 0.011,
    "memory": 0.021955927833914757
  },
  "github-proxy": {
    "cpu": 0.011,
    "memory": 0.021955927833914757
  },
  "gitserver": {
    "cpu": 0.977,
    "memory": 5.147732779383659
  },
  "lang-go": {
    "cpu": 4.991,
    "memory": 10.402064252644777
  },
  "lang-typescript": {
    "cpu": 3.666,
    "memory": 4.892402446828783
  },
  "management-console": {
    "cpu": 0.011,
    "memory": 0.021955927833914757
  },
  "npm-proxy": {
    "cpu": 0.224,
    "memory": 0.911084963940084
  },
  "pgsql": {
    "cpu": 0.271,
    "memory": 2.3649791702628136
  },
  "pgsql-exporter": {
    "cpu": 0.011,
    "memory": 0.021955927833914757
  },
  "query-runner": {
    "cpu": 0.011,
    "memory": 0.021955927833914757
  },
  "redis": {
    "cpu": 0.203,
    "memory": 2.0137913692742586
  },
  "redis-exporter": {
    "cpu": 0.011,
    "memory": 0.021955927833914757
  },
  "repo-updater": {
    "cpu": 0.078,
    "memory": 1.1535918107256293
  },
  "search-badger": {
    "cpu": 0.011,
    "memory": 0.04616234079003334
  },
  "searcher": {
    "cpu": 0.011,
    "memory": 1.2937909020110965
  },
  "symbols": {
    "cpu": 0.476,
    "memory": 4.417638565413654
  },
  "syntect-server": {
    "cpu": 0.078,
    "memory": 0.806466244161129
  }
}
```

You can see the guidelines for [how the VPA gives its recommendations here](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/autoscaling/vertical-pod-autoscaler.md#recommendation-model). 

Interesting things:

## frontend

The VPA recommends ~5.4 gigs of memory, but we have a limit of 5 set here: https://github.com/sourcegraph/deploy-sourcegraph-dot-com/blob/release/base/frontend/sourcegraph-frontend.Deployment.yaml#L214 (is it expected for frontend to use this much memory?)

The dashboards [here](https://console.cloud.google.com/kubernetes/deployment/us-central1-f/dot-com/prod/sourcegraph-frontend?project=sourcegraph-dev&organizationId=1006954638239&tab=overview&deployment_overview_active_revisions_tablesize=50&duration=P7D&pod_summary_list_tablesize=20) say that frontend has been close to full memory utilization for at least the past 7 days:

![screen shot 2019-01-18 at 11 33 23 am](https://user-images.githubusercontent.com/9022011/51408870-ef52fd00-1b14-11e9-8298-4b012d139ac7.png)

_We currently have 3 frontend replicas, so 15 gigs is the collective memory limit for the deployment_. 

## gitserver

The VPA recommends > 5 gigs of memory, but we have a limit of 5 set here: https://github.com/sourcegraph/deploy-sourcegraph-dot-com/blob/release/base/gitserver/gitserver.StatefulSet.yaml#L55. 

The dashboards [here](https://console.cloud.google.com/kubernetes/statefulset/us-central1-f/dot-com/prod/gitserver?project=sourcegraph-dev&organizationId=1006954638239&tab=details&duration=P7D&pod_summary_list_tablesize=20) say that gitserver has been close to full memory utilization for at least the past 7 days:

![screen shot 2019-01-18 at 11 38 14 am](https://user-images.githubusercontent.com/9022011/51409062-93d53f00-1b15-11e9-876a-7025291b76bc.png)

_We currently have 3 gitserver shards, so 15 gigs is the collective memory limit for the stateful set._ 

Also, it seems like gitserver barely uses more than 1 cpu core per-shard, but we have a request of "6" set here: https://github.com/sourcegraph/deploy-sourcegraph-dot-com/blob/release/base/gitserver/gitserver.StatefulSet.yaml#L55 

cc @tsenart 

## lang-go

The VPA recommends > 10.4 gigs of memory, but we have a limit of 10 set here: https://github.com/sourcegraph/deploy-sourcegraph-dot-com/blob/release/configure/lang/go/lang-go.Deployment.yaml#L79. 

The dashboards [here](https://console.cloud.google.com/kubernetes/deployment/us-central1-f/dot-com/prod/lang-go?project=sourcegraph-dev&organizationId=1006954638239&tab=overview&deployment_overview_active_revisions_tablesize=50&duration=P7D&pod_summary_list_tablesize=20) say that lang-go has been under 80% resource utilization over the past 7 days:

![screen shot 2019-01-18 at 11 57 35 am](https://user-images.githubusercontent.com/9022011/51410238-dc422c00-1b18-11e9-82e2-bc01431a00ca.png)

_We currently have 4 gitserver shards, so 40 gigs is the collective memory limit for the stateful set._ 

However, I also noticed that the pods have been OOM kiled 3 days within the last 24 hours. I wonder if there are certain workloads that cause memory usage in lang-go to balloon (and these aren't able to be captured in the chart above)?

## pgsql

The VPA recommends ~2.4 gigs of memory, but we have a limit of 2 set here: https://github.com/sourcegraph/deploy-sourcegraph-dot-com/blob/release/base/pgsql/pgsql.Deployment.yaml#L52. 

The dashboards [here](https://console.cloud.google.com/kubernetes/deployment/us-central1-f/dot-com/prod/pgsql?project=sourcegraph-dev&organizationId=1006954638239&tab=overview&deployment_overview_active_revisions_tablesize=50&duration=P7D&pod_summary_list_tablesize=20) say that pgsql hovers awfully close to full memory utilization over the last 7 days.

![screen shot 2019-01-18 at 12 10 13 pm](https://user-images.githubusercontent.com/9022011/51410684-3f808e00-1b1a-11e9-87f3-89dab154fcae.png)

Also, it seems like pgsql barely uses more than 1/3 of a cpu core, but we have a request of "7" set here: https://github.com/sourcegraph/deploy-sourcegraph-dot-com/blob/release/base/pgsql/pgsql.Deployment.yaml#L54 

## symbols 

The VPA recommends ~4.4 gigs of ram, but our limit is set at 4 here: https://github.com/sourcegraph/deploy-sourcegraph-dot-com/blob/release/base/symbols/symbols.Deployment.yaml#L58. 4.4 is probably an underestimate, since they symbol pods were killed before the VPA could get an accurate read on what the "true" resource usage is. This service has been falling over in prod for a while now.

**Comment by nicksnyder** [comment]
I don't see a reason to delay increasing resource allocations to services that appear to be starved. Whether we can make those resources more efficient is another matter (and would benefit from the knowledge of how many resource they actually want).

If you are worried about reducing resources for certain services (e.g. pgsql), then we can just wait to collect more data.

**Comment by chrismwendt** [comment]
For lang-go, loading and parsing files eats up the most memory:

![image](https://user-images.githubusercontent.com/1387653/51411746-d69b1500-1b1d-11e9-9b68-84dd779fc63a.png)

I'm guessing large repositories could cause spikes in memory usage that take down the process. I tested locally, and **kubernetes/kubernetes takes 580MiB** of memory.

**Comment by beyang** [comment]
@ggilmore I think you should make the call for what the allocations should be. Feel free to err on the safe side—unless it is going to make $1000s of difference in monthly spend, not worth an extended discussion (let's focus instead on what gets customers from 1 to 20).

**Comment by keegancsmith** [comment]
Frontend is heavy on memory. I'd say go with all the recommendations.

**Comment by tsenart** [comment]
I recommend that we adjust up liberally and quickly for resources that are starved and down cautiously for what is currently over-provisioned.

One question: Do we have any Prometheus alerts setup for K8S resource starvation?

**Comment by ggilmore** [comment]
1. I adjusted the resource usage in the following commits:

- https://github.com/sourcegraph/deploy-sourcegraph-dot-com/commit/55eacb43f60830def7a8aa8c6e24f733ba993950
- https://github.com/sourcegraph/deploy-sourcegraph-dot-com/commit/67085d7fa5ecec8d34619c7fe043e93b3666839b
- https://github.com/sourcegraph/deploy-sourcegraph-dot-com/commit/9c48b78271539d4c6e1e7abd77eeaccc64544990
- https://github.com/sourcegraph/deploy-sourcegraph-dot-com/commit/2324e8d0b053b650cd2f1556fd74699ee8d52166
- https://github.com/sourcegraph/deploy-sourcegraph-dot-com/commit/1b7462364a3e0668d248be6475a6f6f34f1bf6fd

1. I filed https://github.com/sourcegraph/sourcegraph/issues/1986 to track adding a new prometheus metric cc @tsenart 

1. I'll be collecting anecodes like the following in https://github.com/sourcegraph/sourcegraph/blob/master/doc/dev/architecture.md so that we keep a written record of recommendations, etc: 

> Frontend is heavy on memory. I'd say go with all the recommendations.
