### ISSUE TITLE
Match highlighting is broken for type:commit

### ISSUE THREAD

**Issue by stefanhengl** [sourcegraph/sourcegraph#19599]
Possible regression. Not all matches are highlighted, see screenshot.

Query:
https://sourcegraph.com/search?q=r:%5Egithub%5C.com/sourcegraph/sourcegraph%24+type:commit+author:stefan+related&patternType=literal

![Screenshot 2021-03-31 at 13 02 18](https://user-images.githubusercontent.com/26413131/113134802-936e7d80-9221-11eb-9f04-ed1ac34a467d.png)

Looking at the payload, we send the correct highlights from the backend to the frontend.
![Screenshot 2021-03-31 at 13 12 30](https://user-images.githubusercontent.com/26413131/113135757-cc5b2200-9222-11eb-8ae1-16e4b46fa1c8.png)

**Comment by limitedmage** [comment]
These search highlighting issues feel like
![whack-a-mole](https://media1.tenor.com/images/4361bf1ccba5cf586c9cb600e12f66b0/tenor.gif?itemid=11145541)
