### ISSUE TITLE
Published changesets are not linking to codehost on preview page

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#19607]
If a changeset has already been published and exists on the code host we should link to it.

Because this is not helpful:

![image](https://user-images.githubusercontent.com/1185253/113156484-5498f180-923a-11eb-82b8-aba7ab4a64c5.png)

**Comment by LawnGnome** [comment]
We already retrieve the existing changeset (if any), so this likely involves adding something like this to the `changeset` requested in `VisibleChangesetApplyPreviewFields`:

```gql
        externalURL {
          url
        }
```

If it comes back as non-null, then we should make the rendered title a link rather than plain text.
