### ISSUE TITLE
Tweet announcement for 3.0

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1960]
To announce 3.0:

- [x] Update tweet below for 3.0
- [x] Add emojis
- [x] Tweet announcement from `@srcgraph`
- [x] Pin the announced tweet on the `@srcgraph` profile

Tweet (:white_check_mark: ready to go when 3.0 is out):

<blockquote>
Sourcegraph 3.0 is out! Code search and nav tool (OSS/self-hosted) now with:

🌐 Go-to-definition and find-references for ~all languages
🔍 Easier search filters
🔐 GitHub repository permissions support
🚀 Better+more cluster deploy options

Get it at: https://about.sourcegraph.com/blog/sourcegraph-3.0
</blockquote>

(Note: For comparison, see the [3.0 beta tweet](https://twitter.com/srcgraph/status/1085201580213878784).)

**Comment by sqs** [comment]
@ryan-blunden Ideas on a gif/image to attach to the tweet?

**Comment by ryan-blunden** [comment]
A 30 second video showing code intelligence in Go, Java, Python and
TypeScript on GitHub?

Bringing code intel to many more languages is my favorite 3.0 feature.
