### ISSUE TITLE
Finalize diff designs

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#19628]
Produce designs for diff views that incorporate design ideas from our initial explorations with the in-progress work on updated diff views.

**Comment by AlicjaSuska** [comment]
@rrhyne @quinnkeast Please, review the [designs](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/?node-id=3250%3A44100). Thank you!

**Comment by rrhyne** [comment]
@AlicjaSuska we've made a few changes based on our review. I've tried to leave notes explaining them. We are happy to discuss the logic on any of them and alter as you require.
