### ISSUE TITLE
MVP search results design

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#19629]
Search results will need a full round of UX study and exploration, but some portion of this design should ship with the design refresh. 

Design an MVP solution that fits the search team's engineering constraints and the new styles.

Consider:
* Repository
* File
* Symbol
* Commit
* Diff
* responsive breakpoints and sidebar design
* ...

Current state (figma: https://www.figma.com/file/J8MduuIBmHAdMFsohckpsi/Search-results-design?node-id=0%3A1&viewport=-2100%2C168%2C0.5082005858421326):

![Search results](https://user-images.githubusercontent.com/539268/117521233-93207b00-af61-11eb-8a6c-c05f1af044b5.png)

**Comment by limitedmage** [comment]
@rrhyne I think we can close this as completed?

**Comment by rrhyne** [comment]
Yes, thanks for all your effort on this.
