### ISSUE TITLE
File page design lockups

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#19627]
The file page requires several additional design decisions beyond the initial creative direction. 

- Active file indicator color is distracting
- Complete designs for all page states
- Padding impact on the extension bar

### Active file indicator color is distracting
The active file indicator requires exploration as the current blue background is too active on the page. 
* Full-width background?
* Bold?
* Vertical purple bar?

### Complete designs for all page states
Additionally, the creative direction did not address several functional elements of the file page. These items will need to be addressed before that page can be built. 

- Close button
- Closed state 
- Symbol panel
- Symbol search
  - empty results 
- Alerts in file panel due to directory length

### Padding impact on extension bar
Correct issues with right side page on the extension bar

**Comment by rrhyne** [comment]
Action bar hover, active, etc states should be addressed as well.

**Comment by AlicjaSuska** [comment]
- Close left pannel button is addressed in the separate issue #21081 
- Symbol panel [mockup](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Design-Refresh-Systemization-source-of-truth?node-id=3173%3A0) and [stickersheet](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Design-Refresh-Systemization-source-of-truth?node-id=954%3A9710)
- [Symbol panel empty state](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Design-Refresh-Systemization-source-of-truth?node-id=3173%3A1549)
- [Closed state](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Design-Refresh-Systemization-source-of-truth?node-id=2965%3A1752)
- [Inline alert in the file panel](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Design-Refresh-Systemization-source-of-truth?node-id=3173%3A1641)
- Action items ([stickersheet](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Design-Refresh-Systemization-source-of-truth?node-id=3181%3A45820))

**Comment by quinnkeast** [comment]
LGTM!
