### ISSUE TITLE
Notice and Alert redesign

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#19662]
Explore alert design, with the Alert RFC in mind. Search results alerts should factor heavily in these decisions. 

Decision: 3px border radius ✅
Decision: No shadow ✅
Unmade decision: Color ✅

![image](https://user-images.githubusercontent.com/539268/115785198-0330dd80-a374-11eb-84f6-eab87a63b787.png)

![image](https://user-images.githubusercontent.com/539268/115785225-0af08200-a374-11eb-909f-70c9daa57a64.png)

Figma:

https://www.figma.com/file/rOhSZskqbqzAnT0meBgvgx/Alerts?node-id=0%3A1&viewport=755%2C966%2C0.22484339773654938

**Comment by rrhyne** [comment]
Requires additional colors specified here:

https://github.com/sourcegraph/sourcegraph/issues/20233

**Comment by rrhyne** [comment]
Valery, one item that was pointed out to me is the colored background had square borders where the surrounding border is round. 

Can we get that corrected?

**Comment by valerybugakov** [comment]
@rrhyne I've double-checked border radius, and it matches mockups from Figma. For some reason, snapshots in Chromatic don't convey it. Check out stories here: http://storybook.sgdev.org. Let me know if you still see the issue.

**Comment by AlicjaSuska** [comment]
@rrhyne when you'll be reviewing this issue, I found the problem with alerts on the extension page
- Icon covers the text
<img width="176" alt="Screenshot 2021-05-18 at 21 06 35" src="https://user-images.githubusercontent.com/20326070/118710097-225d4680-b81e-11eb-8a53-0d6c1c364586.png">

- alert overlaps with the card. Anyways, @tjkandala is working on the redesign and it is not an issue with the new design. @tjkandala do you think there is a need to fix it?
<img width="422" alt="Screenshot 2021-05-18 at 21 06 31" src="https://user-images.githubusercontent.com/20326070/118710099-22f5dd00-b81e-11eb-82f2-a9c6f92b003d.png">

**Comment by tjkandala** [comment]
@AlicjaSuska neither of those should be problems in the new design:
1) [We've removed the disabled alert](https://github.com/sourcegraph/sourcegraph/pull/20822#discussion_r632035140)
2) We don't use the `.alert` class for the extension card anymore

The icon doesn't cover the text in case of an error:
![Screenshot from 2021-05-18 16-34-11](https://user-images.githubusercontent.com/37420160/118719951-0c885b00-b7f7-11eb-9790-c15e48a4eeba.png)

**Comment by rrhyne** [comment]
@tjkandala that makes sense to me, @AlicjaSuska LMK if there is anything for me to do here.

**Comment by valerybugakov** [comment]
@rrhyne, should we close this issue since it's `Done`?

**Comment by rrhyne** [comment]
Yes, hopefully, nothing else opens it! Thanks for your hard work on this!!!!
