### ISSUE TITLE
Give GCP scratch space access to CS rotating engineer for distribution rotation 

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#19679]
For experimenting with https://github.com/sourcegraph/sourcegraph/issues/19428

**Comment by virginiaulrich** [comment]
If it's easier to grant all of CS access now in advance of the rest of the rotations, I am good with that! I don't need access, but the actual CSEs, I mean (Adeola, Beatrix, Giselle, Stompy, Warren)

**Comment by pecigonzalo** [comment]
We should add their group to https://about.sourcegraph.com/handbook/engineering/environments#engineering-projects
