### ISSUE TITLE
Search alert is unreadable/broken when many revisions cannot be  searched

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#19671]
- **Sourcegraph version:** latest Cloud

#### Steps to reproduce:

1. Run [`repo:^github\.com/google/*@master print count:2000`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/google/*%40master+print+count:2000&patternType=literal), which searches for a specific branch across multiple repositories or a repogroup.

#### Expected behavior:

If some revisions cannot be searched, I get a readable, actionable alert explaining the problem. It does not prevent me from viewing results.

#### Actual behavior:

A gigantic alert is displayed, giving me the impression that something is badly broken:

![image](https://user-images.githubusercontent.com/1741180/113405075-7fee1e80-93a9-11eb-9f5b-3718e1f333b9.png)

**Comment by lguychard** [comment]
@rrhyne tagging this as "needs design" because we'd need to decide what to do here, but cc also @limitedmage re: display considerations, and @keegancsmith @stefanhengl re: alert content returned by the backend.

**Comment by rrhyne** [comment]
We already handle this case with the streaming search notice, so I think the action here is to remove this alert. See the screenshot below:

![image](https://user-images.githubusercontent.com/539268/113441326-eae82700-93a2-11eb-9bd9-dc416adeccb4.png)

**Comment by limitedmage** [comment]
This alert is coming from the server. @keegancsmith / @stefanhengl  can you remove it?

**Comment by keegancsmith** [comment]
> This alert is coming from the server. @keegancsmith / @stefanhengl can you remove it?

This should be easy to do. We need to only remove it for streaming. For graphql search we still want it. I think we should just conditionally disable it, and not "improve" it for graphql since existing use cases will be "machines" querying the API.

**Comment by stefanhengl** [comment]
@rrhyne The "missing" notice doesn't cover the revisions which could not be searched. If we remove the alert for streaming we won't show anything. Maybe we need a separate section in the streaming search notice?

![Screenshot 2021-04-06 at 12 14 52](https://user-images.githubusercontent.com/26413131/113697331-57309680-96d3-11eb-85a9-e7d57ac89fd3.png)

**Comment by keegancsmith** [comment]
Looks like we accidently dropped this issue. @lguychard minor issues like this, does it make sense for our support oncall to tackle as low-prio? Might be a nice way to tackle polish issues.

**Comment by lguychard** [comment]
@keegancsmith I think that would make sense here!

**Comment by stefanhengl** [comment]
Here are 3 suggestions of what we could do 
1. Handle missing revisions and missing repos in the same notification "missing".
2. Give missing revs a separate dropdown, EG "missing revisions".
3. Display a shortened form of the alert for streaming IE cut the list to a maximum of 10.

@rrhyne WDYT? Do we have any guidelines as to what to display as alert and what to display as notification?

I recommend going with option 2. Are there more options we should consider?

**Comment by rrhyne** [comment]
Sorry all, this is my fault for missing @stefanhengl's mention. 

Stefan, I think by #2 you mean to create a new streaming alert for missing revisions. If that's the case, I agree, that's the best path. Also note that repositories in those alerts are truncated as per your number 3.
