### ISSUE TITLE
Scope symbols sidebar to current folder/file

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1967]
The symbols sidebar currently shows ALL symbols in the repo. That is useful sometimes, but it's more often useful to see only "relevant" symbols (which usually means only symbols for the current file or project).

From a user:

> My only current complaint is that the "Symbols" tab appears to contain ALL symbols in the Repo, not just the ones in the file being viewed. Either IN the symbols pane, or perhaps in a new pane, it would be awesome to be able to see all the functions that are defined in the file being viewed, possibly even in a hirearchy/tree structure. (e.g. class "blah" has methods underneath it, show them as nodes underneath "blah")

**Comment by felixfbecker** [comment]
Same issue as https://github.com/sourcegraph/enterprise/issues/9769

**Comment by sqs** [comment]
Closed by https://github.com/sourcegraph/sourcegraph/pull/2877
