### ISSUE TITLE
Repository syncing errors are not surfaced in the UI

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#19685]
### Context

I was investigating why a wrong password of Perforce code host connection does not surface an error in the UI when trying to clone a depot. I was able to get the following log grab from gitserver ([code](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/gitserver/server/server.go?utm_product_name=GoLand&utm_product_version=GoLand#L638:24)):

```
│ gitserver t=2021-04-05T07:18:14+0000 lvl=warn msg="error cloning repo" repo=perforce/test-large-depot err="error cloning repo: repo perforce/test-large-depot not cloneable: exit s │
│ tatus 1 (output follows)\n\nPerforce password (P4PASSWD) invalid or unset.\n"
```

### Problem

The actual error is responded to the "client" of the gitserver.Server (see "code" referenced in context) but we swallowed error (possibly only being recorded in `gitserver_repos.last_error`), and not seeing any error/warn logs from repo-updater.

**Comment by mrnugget** [comment]
This ticket's no longer valid. Syncing errors are shown in UI now.
