### ISSUE TITLE
Feature request: Copy file path instead of link to current file

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#19703]
#### Feature request description
It has been mentioned that it would be useful if the 'copy file' functionality would copy the actual file path instead of a link to the current page.

For example:
1. Go to https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/README.md
2. Click copy icon:
![image](https://user-images.githubusercontent.com/9516420/113684013-b9ca6800-96bc-11eb-800b-5c621d5a3312.png)
3. This currently will copy the URL, should it instead copy the file path?

#### Additional context
https://sourcegraph.slack.com/archives/C0W2E592M/p1617397296117600

**Comment by olafurpg** [comment]
This issue appears to be fixed now! I just tried to the "Copy to clipboard" button on https://sourcegraph.com and it copied the filepath instead of the URL.
