### ISSUE TITLE
Add a high level architecture doc on authorization data model

### ISSUE THREAD

**Issue by arussellsaw** [sourcegraph/sourcegraph#19712]
Raised in our retro:

a high level architecture doc would be very useful when working with authz code, i don't think having detailed specific docs on implementations are necessary here, just a guide to help understand the data model & intention. ideally in here: https://docs.sourcegraph.com/dev/background-information/architecture as all engineers read this as part of onboarding

**Comment by unknwon** [comment]
Cleaning up old/stale/fixed issues, please feel free to reopen if you think it's worth keeping.
