### ISSUE TITLE
non-root overlays do not deploy successfully

### ISSUE THREAD

**Issue by davejrt** [sourcegraph/sourcegraph#19724]
When deploying the non-root overlay, there are errors in frontend logs. The non-root, and downstream overlays (inc non-privileged) should include rbac permissions so out of the box these overlays deploy without errors. 

``` frontend
│ t=2021-04-06T19:30:44+0000 lvl=eror msg="k8s failed to list services" error="services is forbidden: User \"system:serviceaccount:ns-sourcegraph:sourcegraph-frontend\" cannot list resource \"services\" in AP 
```

**Comment by daxmc99** [comment]
This appears to be a good opportunity to merge both `non-root` and `non-privileged. We should try to have a least permission deployment.
