### ISSUE TITLE
Complete k8s onboarding chapters

### ISSUE THREAD

**Issue by davejrt** [sourcegraph/sourcegraph#19725]
An issue to capture any pre-requisite learning for your distribution rotation. This can be [kubernetes in action](https://www.manning.com/books/kubernetes-in-action-second-edition), a udemy course, or which you feel is most appropriate for you. 

You should reach a point where you understand how to deploy a basic app to kubernetes when completed. For example, [chapter 3: deploying your first application](https://livebook.manning.com/book/kubernetes-in-action-second-edition/chapter-3/v-6/) would be a good point to aim for.

**Comment by abeatrix** [comment]
Finished Chapter 1-3
