### ISSUE TITLE
gitserver: no timeout on waiting for rate limiter in `doBackgroundRepoUpdate`

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#19720]
When setting `gitMaxCodehostRequestsPerSecond` to 0, we effectively blocks all git operations, but also leaking goroutines if the site admin never sets another value.

We should have a timeout for waiting rate limiter inside `doBackgroundRepoUpdate` and do a proper logging.

**Comment by ryanslade** [comment]
Ah, so when rate and burst are zero does it wait forever?

**Comment by ryanslade** [comment]
I think this isn't a problem once https://github.com/sourcegraph/sourcegraph/pull/19716 lands since once `burst` is zero `Wait()` will immediately fail with this error: 

```
Wait(n=1) exceeds limiter's burst 0
```

**Comment by unknwon** [comment]
> I think this isn't a problem once #19716 lands since once `burst` is zero `Wait()` will immediately fail with this error:
> 
> ```
> Wait(n=1) exceeds limiter's burst 0
> ```

Making total sense ... 🤔 But that's not what I'm observed...

So when I initially set the value to 0 before booting up the local instance, my instrumentation shows it is blocking on `Wait`.

```diff
// cmd/gitserver/server/server.go:L1618
+	fmt.Println("s.rpsLimiter.Wait")
	if err = s.rpsLimiter.Wait(ctx); err != nil {
		return err
	}
+	fmt.Println("s.rpsLimiter.Wait OK")
```

```
23:36:33    gitserver | s.rpsLimiter.Wait
23:36:33    gitserver | s.rpsLimiter.Wait
23:36:33    gitserver | s.rpsLimiter.Wait
23:36:33    gitserver | s.rpsLimiter.Wait
23:36:33    gitserver | s.rpsLimiter.Wait
23:36:33    gitserver | s.rpsLimiter.Wait
```

**Comment by ryanslade** [comment]
Was that the value of the limit or burst or both? I think that error is only raised when burst is zero.

**Comment by unknwon** [comment]
I have set `gitMaxCodehostRequestsPerSecond` to 0, so both limit and burst are 0, after the change made in https://github.com/sourcegraph/sourcegraph/pull/19716.

**Comment by ryanslade** [comment]
Did you set it in your `dev-private`? I'll try to reproduce

**Comment by ryanslade** [comment]
I set it to zero and added similar logging to you and it looks ok. Your code doesn't reach `fmt.Println("s.rpsLimiter.Wait OK")` because it fails with an error. Here's what I did, note that I also print the error:

```go
fmt.Println("Waiting", s.rpsLimiter.Limit(), s.rpsLimiter.Burst())
	if err = s.rpsLimiter.Wait(ctx); err != nil {
		fmt.Println(err)
		return err
	}
	fmt.Println("Done waiting", s.rpsLimiter.Limit(), s.rpsLimiter.Burst())
```

and I see this in my logs:

```
12:10:49                 gitserver | Waiting 0 0
12:10:49                 gitserver | rate: Wait(n=1) exceeds limiter's burst 0
```

**Comment by unknwon** [comment]
Gotcha 🤔 so the error somehow got swallowed that we don't print it anywhere else?

**Comment by ryanslade** [comment]
> Gotcha 🤔 so the error somehow got swallowed that we don't print it anywhere else?

I submitted a PR to log the error when doing a background rep update
