### ISSUE TITLE
provision GKE cluster for k8s testing

### ISSUE THREAD

**Issue by davejrt** [sourcegraph/sourcegraph#19726]
Provision a cluster in GKE to test kubernetes. You can use [these docs](https://cloud.google.com/kubernetes-engine/docs/how-to/creating-a-zonal-cluster) and pair with @davejrt to help complete this task.

**Comment by abeatrix** [comment]
Set up a GKE cluster with @daxmc99 on 4/7. Will revisit again later today.

**Comment by abeatrix** [comment]
Completed following Dax's walkthrough video.
