### ISSUE TITLE
Request for patch release on 3.26

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#19750]
@sourcegraph/distribution I am requesting the following commits be included in a patch release. They are already merged into `main`:

The intent of the questions below is to ensure we keep Sourcegraph high quality and [only create patch releases based on a strict criteria.](https://about.sourcegraph.com/handbook/engineering/releases#when-are-patch-releases-performed) If you can answer yes to many or most of these questions, we will be happy to create the patch release.

- https://github.com/sourcegraph/sourcegraph/commit/096fc3c91ed14da330eaed2883f1934420158a2a

I have read [when and why we perform patch releases](https://about.sourcegraph.com/handbook/engineering/releases#when-are-patch-releases-performed) and answer the questions as follows:

> Are users/customers actively asking us for these changes and cannot wait until the next full release?

No explicit requests. One customer downgraded to 3.25: https://github.com/sourcegraph/customer/issues/283.

> Are the changes extremely minimal, well-tested, and low risk such that not testing as we do in a full release is OK?

Yes. See commit. We tested manually, it has fixed the bug on sourcegraph.com and it includes unit tests.

> Is there some functionality completely broken that warrants redacting the prior release of Sourcegraph and advising users wait for the patch release?

I think this *might* be a yes. Note this is only broken for the patch releases where we merged in main. It included a commit which breaks search on all large repos. The breakage causes large repos to always return partial results. (will only search 1 shard of many for indexed search).

> This will interrupt our regular planned work and release cycle, taking 3-6 hours of our time, and will take up all of our site admin's valuable time by asking them to upgrade or producing noise for them if they don't need to upgrade.
>
> Do you believe the changes are important enough to warrant this?

Yes.

> Patch releases are a signal we can do something better to improve the quality of Sourcegraph. Have you already scheduled a call (or created a google doc) to perform a [retrospective](https://about.sourcegraph.com/retrospectives) and identify ways we can improve?

No I haven't. I  believe this  is due to merging in main, when we didn't expect a branch cut. We were operating under the assumption there wouldn't be a release with this commit for another month.

---

**For the [release captain](https://about.sourcegraph.com/handbook/engineering/releases#release-captain)** - after reviewing and approving this request:

- If there is [already an upcoming patch release](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+), add the listed commits alongside a link to this issue
- If there is no upcoming patch release, create a new one:
  - Update [`dev/release/release-config.jsonc`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/release/release-config.jsonc) with the patch release in `upcomingRelease` and `releaseDate` (and open a PR to `main` to update it)
  - `yarn release tracking:issues`
  - Add the listed commits alongside a link to this issue to the generated [release tracking issue](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+)

Comment and close this issue once the relevant commit(s) have been cherry-picked into the release branch.

**Comment by keegancsmith** [comment]
FYI I had already cherry-picked the commit onto the 3.26 branch and pushed it. I hadn't realised we introduced this process at that time.

**Comment by unknwon** [comment]
@ggilmore Is it too late to ask for including https://github.com/sourcegraph/sourcegraph/commit/98aa730b2ba775d6f96b63dc0bcc54aad8d1c0f2 from the core app team? Our customer champion will leave the company in 2-3 weeks and want to get this roll out before leaving.
