### ISSUE TITLE
Searching for repositories after adding code host reloads the page

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#19754]
When searching for some term on `/users/NAME/settings/repositories/manage`, after pressing enter in the search input box the page reloads and the search term is lost again, so searching doesn't seem possible to me at this point. With 11 pages of repos returned for my GitHub account this is a bit tedious 😬

**Comment by ryanslade** [comment]
> so searching doesn't seem possible to me at this point

It should automatically filter as you type, does that not work?

I agree that pressing enter shouldn't refresh the page though

**Comment by eseliger** [comment]
Ah yes seems to work just typing in my search term. The URL `query` param isn't set unless pressing enter though, that's why I thought it doesn't do anything 😬 
Then the problem is probably just that it reloads on enter, and maybe that the search query param isn't set, but I don't think that's super important.

**Comment by artemruts** [comment]
I can probably see if we can handle that enter event and prevent it, or why the query params are not updated.

**Comment by ryanslade** [comment]
Thanks @artemruts
