### ISSUE TITLE
We should provide docs on how to recover from PV's becoming unbound

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#19766]
If a StatefulSet is deleted the PVs can become `Unbound`, this is preferred with our `sourcegraph` StorageClass since it has the `reclaimationPolicy` of `Retain` set instead of `Delete`. 

However, the PVCs and PVs will still need to be manually reassociated. We should document how to do this.

Long term, we should investigate tooling like [Verlo](https://velero.io/) to see if we can provide an easier way to perform diaster recovery.

**Comment by virginiaulrich** [comment]
Decided in planning today to close this since it's been ~12 months and is currently outside of scope of intention of official docs at this time
