### ISSUE TITLE
[Discovery] Support permissions sync from Bitbucket Cloud

### ISSUE THREAD

**Issue by emchap** [sourcegraph/sourcegraph#19782]
#### Feature request description

Bring Bitbucket Cloud permissions sync in to the app.

#### Is your feature request related to a problem? If so, please describe.

See https://github.com/sourcegraph/customer/issues/288

#### Describe alternatives you've considered.

Manual permissions syncing, which becomes unwieldy if there's a Server code host connection in the same instance.

#### Additional context

See linked /customers issue.

**Comment by emchap** [comment]
Sourcegraph employees see also: https://docs.google.com/document/d/1TKtt3iJPRiuuaVxw4ioOCRrEnhH4q7kIi6meEXUDue0/edit?usp=sharing

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.

**Comment by pjlast** [comment]
Implmented by https://github.com/sourcegraph/sourcegraph/pull/46312
