### ISSUE TITLE
Browser extension install CTA looks squished on small windows

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#19794]
Screenshot: 
![Screenshot 2021-03-14 at 13 01 43](https://user-images.githubusercontent.com/11967660/113958539-21280b00-97d6-11eb-8711-11bbccbaa146.png)

**Comment by erzhtor** [comment]
Hey, @Joelkw! 
I think we've updated/migrated these CTAs to a new design and I checked that it renders properly on different viewports. Closing this issue as it is not a case anymore. Let me know if I misunderstood and we should still tackle it.
cc @vdavid @rrhyne 
![image](https://user-images.githubusercontent.com/6717049/163804344-9bb0e563-c0f7-431d-bc19-8f5f01319ec2.png)
