### ISSUE TITLE
RFC 266: Create a test for a user attempting to access code intel resources

### ISSUE THREAD

**Issue by indradhanush** [sourcegraph/sourcegraph#19817]
1. A user attempting to request code intel definitions/references/hovers/diagnostics of a repository the user does not have access to.
1. A user requesting code intel definitions/references/hovers/diagnostics of a repository but some of dependencies the user does not have access to.

**Comment by unknwon** [comment]
I verified [all of current LSIF endpoints are sub-nodes of Repository node](https://github.com/sourcegraph/sourcegraph/blob/main/cmd/frontend/graphqlbackend/codeintel.graphql), which basically rely on the permissions enforcing at the repository-level, and that is already covered in other tests, thus closing.
