### ISSUE TITLE
Contexts selector is not removed when code host connections are removed

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#19831]
## Problem

When a user has at least one code host connections—which makes the context selector visible—and then removes all code host connections, the contexts selector remains visible until the next reload. The select is fully interactive and the user can attempt to do a search, even though there's nothing to search.

![CleanShot 2021-04-08 at 19 27 19](https://user-images.githubusercontent.com/6304497/114070773-a5df5b80-98a0-11eb-8552-8ef03208d7a4.gif)

## Expected behaviour

Removing all code host connections removes the context selector without a reload.

**Comment by artemruts** [comment]
@quinnkeast I'm not sure this should be addressed by the core team. WDYT?

**Comment by quinnkeast** [comment]
To be honest, I'm not 100% sure. I've added team/search so we can figure it out.
