### ISSUE TITLE
Intermittent Terraform failures on k8s provider

### ISSUE THREAD

**Issue by ElizabethStirling** [sourcegraph/sourcegraph#19857]
On occasion, Terraform's kubernetes provider will fail to initialize properly, and will use the default provider config. This will result in Terraform attempting to apply to `localhost`, which results in the error `Error: Get "http://localhost/api/v1/namespaces/[OBJECT_TO_MODIFY_PATH]": dial tcp [::1]:80: connect: connection refused`.

[Provider initialization failure](https://buildkite.com/sourcegraph/infrastructure/builds/70077#96cb1ff7-3a10-41c1-b97d-b947ceb2a846/291-10264)

[Provider default host](https://buildkite.com/sourcegraph/infrastructure/builds/70077#96cb1ff7-3a10-41c1-b97d-b947ceb2a846/291-10280)

[Connection refused](https://buildkite.com/sourcegraph/infrastructure/builds/70077#96cb1ff7-3a10-41c1-b97d-b947ceb2a846/291-10339)

This is somewhat intermittent, but once triggered is consistent so long as the underlying Terraform isn't updated. This can result in things that don't solve the underlying problem appearing to solve the underlying problem.

This is a known Terraform issue, with many proposed workarounds.
https://github.com/hashicorp/terraform-provider-kubernetes/issues/1028
https://github.com/hashicorp/terraform-provider-kubernetes/issues/821
https://github.com/hashicorp/terraform-provider-kubernetes/issues/1152
The core terraform issue appears to be https://github.com/hashicorp/terraform/issues/4149, however, it's not currently being worked on by the team https://github.com/hashicorp/terraform/issues/4149#issuecomment-805307448

[Relevant Slack Thread](https://sourcegraph.slack.com/archives/CJX299FGE/p1617905337383900)

**Comment by daxmc99** [comment]
Fix has been applied for:

- [ ] buildkite
- [ ] Cloud
- [ ] dogfood

**Comment by daxmc99** [comment]
If we see this again, please reopen
