### ISSUE TITLE
Add prometheus metric that tracks deployment's resource usage 

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#1986]
See https://github.com/sourcegraph/sourcegraph/issues/1958#issuecomment-456027014

**Comment by tsenart** [comment]
@ggilmore: Some useful resources:

- https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus
- https://github.com/grafana/kubernetes-app
- https://cloud.google.com/monitoring/kubernetes-engine/prometheus

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by slimsag** [comment]
Robert fixed this via https://github.com/sourcegraph/sourcegraph/issues/7529
