### ISSUE TITLE
Search code snippet does not display errors when requests have failed

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#1987]
1. Start a Sourcegraph server of any kind with an invalid `SRC_SYNTECT_SERVER` value, such as `http://bad`.
2. Enter any search query into Sourcegraph and notice no errors, but just blank results:

![image](https://user-images.githubusercontent.com/3173176/51562178-728e8e80-1e46-11e9-8212-112249e824bf.png)

The console shows:

![image](https://user-images.githubusercontent.com/3173176/51562213-8934e580-1e46-11e9-812a-76a813ee8f2e.png)

This error shoudl be surfaced in our UI somewhere.

**Comment by felixfbecker** [comment]
Have seen this before too. Always in favor of in-place error displays!
