### ISSUE TITLE
Alert when user exceeds repo limit

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#19881]
If we know at the time a user attempts to save code host repos that they would exceed our repo limit we should alert immediately instead of kicking off a sync and finding out later. 

We can do this in cases where they've selected individual repos. In case where they've selected by org or affiliated repos we can't tell until later but in that case it will at least be picked up eventually by the syncer  and they'll be alerted in the notifications area.

**Comment by artemruts** [comment]
@quinnkeast do you know how this should look?
@ryanslade what's our repo limit?

**Comment by ryanslade** [comment]
@artemruts It's configurable, but currently set at 2k per user. 

We also have a limit of 100 "other" public repos per user.

**Comment by ryanslade** [comment]
I don't mind taking this on Monday. I imagine we could use our normal error alert, similar to:

![Uploading Screenshot 2021-04-09 at 17.37.38.png…]()

**Comment by quinnkeast** [comment]
Agreed, let's use the normal alert for now. A message could be:

>*Too many repositories*. Sourcegraph supports adding a maximum of 2000 repositories.
