### ISSUE TITLE
Server-side batch changes pre-read

### ISSUE THREAD

**Issue by chrispine** [sourcegraph/sourcegraph#19887]
Create a pre-read document to describe the issues and context around server-side batch changes before we have our summit.

- [x] Create 1-2 page "RFC light" describing the idea
- [x] Batch Changes internal review/sync on this doc
- [x] Meeting with code-intel/distribution/etc.

**Comment by LawnGnome** [comment]
Pre-read has gone out; we have early feedback; calling this done.

**Comment by malomarrec** [comment]
[Batch Changes server side execution: runners](https://docs.google.com/document/d/1ioKOJbXML-Oee4BPql_lCak8W4YCjR7HHO621eAVNvU/edit)
