### ISSUE TITLE
sg: codeinsights database migration fails

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#19883]
When trying to use `sg run-set enterprise` on latest main (`7bfcf61`), `enterprise-frontend` fails to do the codeinsights database migration. 

```
[enterprise-frontend] failed to initialize insights: Failed to perform codeinsights database migration: Failed to migrate the DB. Please contact support@sourcegraph.com for further assistance: Dirty database version 1000000001. Fix and force version.
```

I think I saw some more useful debugging information printed the first time I ran the command, but I didn't save it at the time, and I haven't been able to get it to show up again. I'll add more info if I find out more.

**Comment by slimsag** [comment]
> sg run-set enterprise

What is this command? I've never seen this before

It looks likely that your dev server terminated, killing the codeinsights DB while it was running the very first migration and thus it got marked "dirty"

So this is mostly a dev environment issue.

**Comment by camdencheek** [comment]
> What is this command? I've never seen this before

It's listed in the README with the comment "Run the enterprise environment". 

I figured `./dev/start.sh` : `sg start` :: `./enterprise/dev/start` : `sg run-set enterprise`

**Comment by camdencheek** [comment]
I'm not working on any enterprise-only features, so this certainly isn't stopping me from using `sg` right now, but I figured it was worth writing up an issue in case I was missing something silly or someone else runs into it. I'm happy to dig into it more once my plate clears a bit.

**Comment by camdencheek** [comment]
Still not sure what caused this, but it's stopped happening, so I'm closing it
