### ISSUE TITLE
Minimal search panel design

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#19903]
Search would like to start iterating on features that improve the learning curve and retention as quickly as possible. This requires UI space provided by the side panel concept. 

To support those requirements we will design a MVP of the panel using only existing styles and supporting only those elements that are currently available in the search UI. 

The following panels will be supported:

### Result types:
Tabs will be replaced with a panel containing 'result types' in the sidebar. When each type is clicked the type is added to their search and their search is re-run as per current tab behavior. The list will consist of the following types:
* file
* symbol
* repo
* path
* diff
* commit

Users must clear a type added to their query manually. No interactive components will be designed as part of this effort.

### Search.scopes
This search scope is actually a query fragment with a name parameter. These are useful for storing items like regexes or common filter values you don't want to have to type again and again. Scopes can be set for an organization or a user. We will maintain this functionality but rename it.

### Quicklinks
We will review usage statistics and potentially recommend removing this feature.

https://www.figma.com/file/QqFYlk9Jez1d3DNpZXVf7l/Minimal-search-panel-%2319903?node-id=0%3A1&viewport=-41%2C497%2C1

![image](https://user-images.githubusercontent.com/539268/114251156-e1d3f880-9954-11eb-9e47-6ad861e52212.png)

**Comment by quinnkeast** [comment]
`Search scopes` → `Search snippets` is a great change. Huge jump forward conceptually.

**Comment by benvenker** [comment]
@rrhyne has this been superseded by the current search reference pane, or is this still an additional direction we want to head?

**Comment by rrhyne** [comment]
Yes, this is complete. Looks like it was moved to done but not closed.

**Comment by benvenker** [comment]
Got it, thanks.
