### ISSUE TITLE
Handbook is slow

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#19901]
The handbook server itself is becoming slow

Directly port-forwarding the pod 
`k port-forward svc/about-sourcegraph-com-loadbalancer-https 9090:` and we are still seeing requests take ~3 seconds or  more on average for TTFB (time to first byte). 

Should we consider not using [docsite](https://github.com/sourcegraph/docsite) for our handbook?

**Comment by nicksnyder** [comment]
> Should we consider not using this for our handbook?

Not using what?

**Comment by daxmc99** [comment]
I updated the initial comment.  I meant to say the docsite program. I'm not sure what benefits it has over something that creates a static site.

**Comment by daxmc99** [comment]
Partly fixed in linked issue
