### ISSUE TITLE
Search input with context selector is initially visually broken when loading on search home

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#19917]
- **Sourcegraph version:** Sourcegraph Cloud
- Safari, Chrome, Firefox

#### Steps to reproduce:

1. Visit sourcegraph.com/search with contexts enabled
2. A visual gap/flicker is momentarily present between the input and the contexts selector

<img width="260" alt="CleanShot 2021-04-12 at 10 48 59@2x" src="https://user-images.githubusercontent.com/6304497/114367402-b29fd000-9b7c-11eb-9f98-f2b663b76131.png">

Video: https://cln.sh/8CpAi1

**Comment by camdencheek** [comment]
Closing since the context selector has since been redesigned
