### ISSUE TITLE
Tabs lockup

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#19928]
Define all states for the tab component from the initial designs:

* Active
* Hover
* Disabled

Boostrap specs:
https://getbootstrap.com/docs/4.6/components/navs/#tabs-with-dropdowns

**Comment by quinnkeast** [comment]
I believe this is what we've called a "subnav," but please correct me if I'm wrong.

<a href="https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Design-Refresh-Systemization-source-of-truth?node-id=1107%3A23176 "><img width="542" alt="CleanShot 2021-05-21 at 16 16 40@2x" src="https://user-images.githubusercontent.com/6304497/119151704-ef9a9480-ba4f-11eb-954e-fca681f1e9d4.png"></a>

- Sticker sheet: 
[https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Design-Refresh-Systemization-source-of-truth?node-id=1107%3A23176](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Design-Refresh-Systemization-source-of-truth?node-id=1107%3A23176)

Not present right now is the disabled state. Do we have the need for disabled items here? If so, we will likely need to switch the default colour (not current) to the link blue.

**Comment by pdubroy** [comment]
Can we close this issue?

**Comment by AlicjaSuska** [comment]
I think so, @quinnkeast do you have anything against?
