### ISSUE TITLE
Breaders / Page headers

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#19932]
The new page headers for code monitoring and batch changes will need to be implemented in other pages as well. 
Define those pages and provide header designs for them.

Figma:
https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/?node-id=998%3A0

In the product, top and bottom margin may be different from the Figma files.

![image](https://user-images.githubusercontent.com/539268/115765182-49c60e00-a35b-11eb-9079-abf193e5ce51.png)

![image](https://user-images.githubusercontent.com/539268/115765206-5480a300-a35b-11eb-91b3-4397e233bfc0.png)

**Comment by rrhyne** [comment]
@eseliger this ticket originally mentioned campaigns which is why you were notified. I wonder if that's been updated to also alert on batch changes?

**Comment by eseliger** [comment]
Yes! Thanks for checking :)

**Comment by umpox** [comment]
Reopening for implementation review, @sourcegraph/design please review, raise any changes as new tickets and close this issue!

**Comment by rrhyne** [comment]
I went through it last week, LGTM!
