### ISSUE TITLE
Bitbucket server permissions docs out of date

### ISSUE THREAD

**Issue by emchap** [sourcegraph/sourcegraph#19937]
#### Describe the issue
Bitbucket server docs (https://docs.sourcegraph.com/admin/repo/permissions#bitbucket-server) are out of date; they include a reference to a button that no longer exists in-app and don't clarify that to configure the connection in Bitbucket you need to be a superadmin.

#### Where is the issue located?
https://docs.sourcegraph.com/admin/repo/permissions#bitbucket-server

#### Suggested resolution
Change `As an admin user, go to the “Application Links” page.` to `As a superadmin user, go to the “Application Links” page.`. Clarify that you have to set up the connection, save it, and then edit it to get the 2-legged OAuth button to appear. 

Change `Click on the Enforce permissions quick action on top of the configuration editor.` to include the actual JSON the customer needs to include, as the button is no longer in the app. (Alternatively, I guess, add the button back—it was removed in 3.11 I think, I'm not sure why.)

Config they need appears to be:

```
{
// Other config goes here
	"authorization": {
		"identityProvider": {
			"type": "username"
		},
		"oauth": {
			"consumerKey": "KEY GOES HERE",
			"signingKey": "KEY GOES HERE"
		}
	}
}
```

I thought another issue had been filed for this but I'm not seeing it, so filing this here! Sorry if it's duplicative.

**Comment by macraig** [comment]
@unknwon I tagged you based on our conversation, but feel free to reassign within the team
