### ISSUE TITLE
Add events for add public code flow

### ISSUE THREAD

**Issue by ebrodymoore** [sourcegraph/sourcegraph#19945]
Add events for the following actions so we can measure the flow from Sourcegraph.com -> adding public code (and eventually private code)
- [x] Manage Repositories 
- [x] Save (on the manage repositories page)
- [x] Attempt to connect with code host
- [ ] There may be others that would be good to add that aren't directly in this flow but we'll want data on cc @quinnkeast for any other events you're interested in @kelsey-brown

**Comment by ryanslade** [comment]
It looks like we already have:

`ViewUserSettingsRepositories` and `ViewUserSettingsCodeHostConnections ` when a user visits those new pages.

**Comment by ryanslade** [comment]
I've addressed the ticked items above in the linked PR

**Comment by ebrodymoore** [comment]
Ah got it. I think we should add events when these buttons are clicked then. Otherwise it just reloads as `ViewUserSettingsRepositories` and we aren't actually knowing what they're doing on that page. 

**Manage**
<img width="1182" alt="Screen Shot 2021-04-14 at 8 28 00 AM" src="https://user-images.githubusercontent.com/25422491/114718198-6333de00-9cfb-11eb-82cf-8196d02e0137.png">

**Save**
<img width="1149" alt="Screen Shot 2021-04-14 at 8 28 09 AM" src="https://user-images.githubusercontent.com/25422491/114718209-65963800-9cfb-11eb-8fb6-ce66ee09f5ad.png">

**Comment by ryanslade** [comment]
Cool, we already fire an event when save is clicked, `UserManageRepositoriesSave`

Looking into how to do it for `Manage Repositories` since it's actually a link, not a button.

**Comment by ebrodymoore** [comment]
Ok great thank you!!
