### ISSUE TITLE
design-refresh: Deprecate unused colors after design refresh

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#19973]
As part of the design refresh we have deprecated certain semantic color variables.

Once we no longer rely on these color variables, we should find and replace all usage with the correct value.

Designs: https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Design-Refresh-Systemization?node-id=771%3A1315

| Deprecated variable  | Replacement variable |
| ------------- | ------------- |
| `--link-hover-bg-color` | `--color-bg-2`  |
| `--link-hover-bg-color-2`  | `--color-bg-3`  |
| `--disabled-action-bg-color`  | `--color-bg-3`  |
| `--disabled-action-text-color`  | `--text-muted`  |

**Comment by felixfbecker** [comment]
I never understood `--link-hover-bg-color` because links don't have backgrounds 😄
