### ISSUE TITLE
Support username (123)@example.com email formats 

### ISSUE THREAD

**Issue by chrislovett03** [sourcegraph/sourcegraph#19987]
#### Feature request description

Support email address format: username (123)@example.com

#### Is your feature request related to a problem? If so, please describe.

This isn't supported by our normalization standards so users are unable to access their Sourcegraph instance

#### Additional context

https://github.com/sourcegraph/customer/issues/282

**Comment by christinelovett** [comment]
Hey @unknwon will this make it into 3.28?

**Comment by unknwon** [comment]
> Hey @unknwon will this make it into 3.28?

I cannot commit a date but I do not think it's possible to work on this before June 4th.

**Comment by christinelovett** [comment]
thanks for the update 👍

**Comment by christinelovett** [comment]
Hey @unknwon is it possible to take another look at this?

**Comment by unknwon** [comment]
@ryphil - Please triage

**Comment by Sean-Oh** [comment]
@christinelovett 

Some additional context from us:
* We have a SAML based auth system
* We have users with the same first/last name and differentiate based on name + location. Here's an example:
  * Name: Bob Traeger (NY)
  * Username: bobtraeger
  * Email: bob.l.traeger@foo.com

Sourcegraph will automatically sign up this user as `Bob-L-Traeger`. However, when Bob tries to use Sourcegraph, they will see the following error message:
```Error normalizing the username "Bob Traeger (NY)". See https://docs.sourcegraph.com/admin/auth/#username-normalization.```
