### ISSUE TITLE
Token cursor highlighting stretches backwards on in-line file fragraments

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#19996]
Token highlighting seems to get tripped up by an added extra space in front of code snippets – it doesn't happen on full blob pages. See [here](https://github.com/golang/go/issues/45494) for an example. 

![image (22)](https://user-images.githubusercontent.com/11967660/114660977-0f99a400-9cab-11eb-856f-594b66b1d561.png)

**Comment by ryankscott** [comment]
Can no longer reproduce.
