### ISSUE TITLE
constantly getting signed out of k8s.sgdev.org

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#19995]
@sourcegraph/distribution noticed this on Friday, but we seemed to be getting signed out of k8s.sgdev.org on a regular basis. 

There might be a redis misconfigration issue...Perhaps the session storage isn't permanelty mounted. If that's the case, then the constant stream of deployments from the image updater pipeline might be exacerbating this.

It remains to be seen if there is a bug in the updater pipeline, or in the underlying redis configuration (maybe this was constantly broken, it's just that redis didn't get updated nearly as often before...)

We should run this down before proceeding with rolling out the image updater pipeline on sourcegraph.com

**Comment by davejrt** [comment]
Confirmed after bouncing the redis-store pod on k8s.sgdev.org that I get signed out. I put a temp file on the pvc and that volume is persisting
