### ISSUE TITLE
Kotlin code intelligence

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#2]
Support the Kotlin language on Sourcegraph.

**Comment by keegancsmith** [comment]
Link to a tweet of another user asking for Kotlin https://twitter.com/erluxman/status/910790116091740160

**Comment by slimsag** [comment]
Another user here asking for Kotlin support :) https://github.com/sourcegraph/java-langserver-docs/issues/1

**Comment by keegancsmith** [comment]
In another thread talking about popularity of Kotlin, there was this response which I think is food for thought w.r.t. trying to quantify the popularity:

> I'm not sure we have great data on that, actually. Most server-side JVM work is closed-source so GitHub isn't a good indicator. I suspect there are lots of companies like mine that introduced Kotlin to a Java code base but if forced to choose a single option in a "which language is your server written in?" survey would still pick Java.

**Comment by nicksnyder** [comment]
Sourcegraph is happy to sponsor someone working on a Kotlin (or any other) language server. Please let us know if you are interested!

The best measure of “is there enough demand for a language server” is “is the community or a company in the community already working on one”. We are happy to help and lend our expertise about building language servers when that time comes.

**Comment by joaoqalves** [comment]
@nicksnyder Is it possible to plug in [this](https://github.com/fwcd/KotlinLanguageServer) LSP?

**Comment by nicksnyder** [comment]
Any LSP server can be plugged in to Sourcegraph using [lsp-adapter](https://github.com/sourcegraph/lsp-adapter). Feel free to open a pull request there!

We have plans to make it even easier to add language support via Sourcegraph extensions in the future.

@sqs @felixfbecker @chrismwendt can you post a plan to https://github.com/sourcegraph/about ?

**Comment by sqs** [comment]
We are releasing a big improvement to how lang support is added to Sourcegraph in under 2 weeks (see "Language support via Sourcegraph extensions", more info coming soon, at https://docs.sourcegraph.com/dev/roadmap#october-2018). After that, we will post back here with guidance on using the lang server you linked (https://github.com/fwcd/KotlinLanguageServer) with Sourcegraph.

**Comment by hzsweers** [comment]
Would it be possible to start with just basic syntax highlighting?

**Comment by chrismwendt** [comment]
Code intelligence on Sourcegraph is now provided through [Sourcegraph extensions](https://docs.sourcegraph.com/extensions). We've built extensions for [Go](https://sourcegraph.com/extensions/sourcegraph/lang-go), [TypeScript](https://sourcegraph.com/extensions/sourcegraph/lang-typescript), and [Python](https://sourcegraph.com/extensions/sourcegraph/lang-python).

Anyone can create a new Sourcegraph extension for Kotlin support, and Sourcegraph is happy to help out with funding and technical guidance!

**Comment by ZacSweers** [comment]
@chrismwendt can extensions provide syntax highlighting? Looked at the linked docs page + the examples, and I don’t see any of them controlling the grammar for highlighting.

**Comment by chrismwendt** [comment]
No, syntax highlighting is provided by https://github.com/sourcegraph/syntect_server cc @slimsag Could Kotlin be added?

**Comment by ZacSweers** [comment]
Looks simple enough if it’s just proxying to codemirror, I’ll take a shot at a PR

**Comment by ZacSweers** [comment]
It looks like the sublime folks' recommendation is to basically take a public kotlin package, such as https://github.com/vkostyukov/kotlin-sublime-package, and then a PR to maybe add that to https://github.com/slimsag/Packages (which appears to be the source for https://github.com/sourcegraph/syntect_server ? it's not entirely obvious how this is all wired)

**Comment by chrismwendt** [comment]
Kotlin code intelligence has been added in Sourcegraph 3.0 :tada:

https://about.sourcegraph.com/blog/sourcegraph-3.0#code-intelligence-for-all-languages

[Try it out](https://sourcegraph.com/github.com/shadowsocks/shadowsocks-android@44c5180d5d55189b66178dfaf9d3273a4d487352/-/blob/core/src/main/java/com/github/shadowsocks/net/LocalDnsServer.kt#L74:27) on Sourcegraph.com:

![image](https://user-images.githubusercontent.com/1387653/52600352-2cf32f00-2e10-11e9-890e-eb709e56db26.png)

**Comment by slimsag** [comment]
I've added syntax highlighting (in code files) for Kotlin (thanks @KattMingMing for his help!). It will be in the next v3.1 shipping soon. Example on Sourcegraph.com:

https://sourcegraph.com/github.com/JetBrains/kotlin-examples/-/blob/tutorials/mpp-iOS-Android/app/src/main/java/com/jetbrains/jonnyzzz/myapplication/MainActivity.kt

**Comment by ZacSweers** [comment]
I've tried both linked samples but `Find References` never shows any results in either example for the classes and functions I tried. Only go to definition seemed to work

**Comment by slimsag** [comment]
@chris is that expected?

**Comment by chrismwendt** [comment]
@ZacSweers Sorry about that! You probably ran into a bug that was introduced yesterday and I fixed a minute ago 🐛 It should work now.
