### ISSUE TITLE
Slow page render on GitHub with browser extension enabled

### ISSUE THREAD

**Issue by eatonphil** [sourcegraph/sourcegraph#2000]
- Chrome browser integration

#### Steps to reproduce:

1. Visit this Standard ML file while the browser integration is enabled and try to scroll down https://github.com/eatonphil/ponyo/blob/master/examples/performance-testing.sml
2. It takes seconds to render the content
3. Visit the same file without the browser integration enabled and it renders about as quickly as you scrol

#### Expected behavior:

If the language is not supported (by looking at file extensions?) don't render it through Sourcegraph.

#### Actual behavior:

A non-supported language is re-rendered through Sourcegraph and causes unnecessarily slow page renders.

**Comment by sqs** [comment]
We received another report of this from a customer on GitHub PR pages. Bumping this up in priority unless it is determined they are separate issues.

**Comment by matevarga** [comment]
Hi, fyi -- I'm happy to provide e.g. Chrome profiling info if that helps (I'm that other customer who reported the slowness).

**Comment by ijsnow** [comment]
@matevarga @eatonphil I merged and released a change that greatly improved performance on page load (was released in `v19.1.29.2106`). Please don't hesitate to reopen this if you continue to see problems!

And just a side note @eatonphil: any language can be a supported language with [Sourcegraph extensions!](https://docs.sourcegraph.com/extensions) If you have spare time and would like to see ML support in Sourcegraph, we'd be happy to help you get going on building an extension for it!
