### ISSUE TITLE
design-refresh - update navigation menu

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#20023]
### Update our navigation menu to match the design refresh

Designs: https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Design-Refresh---Systemization-(source-of-truth)?node-id=988%3A0

We should ensure these updates are scoped under `theme-redesign`.

**Comment by AlicjaSuska** [comment]
@5h1rU update on the syn icon: @quinnkeast prepared the outlined version of sync icons (the cloud-shaped icon visible in the nav bar). Could you please swap the icons as the part of nav bar redesign implementation? Thank you :) [Figma](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Design-Refresh-Systemization-source-of-truth?node-id=1366%3A168)
