### ISSUE TITLE
Add metrics on code host versions

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#20033]
We would like to be able to track what versions of code hosts are being used with Sourcegraph to make decisions about API versions used, features we can leverage, ...
We need to
- [ ] Write code to fetch the versions of all connected code hosts
- [ ] Add it to the pings data
- [ ] Get the pings change approved and the BigQuery schema adjusted

**Comment by ebrodymoore** [comment]
Getting the change approved should come first! Just in case those checkboxes are listed in what comes first, second, third

**Comment by eseliger** [comment]
Haha there was no particular order, no worries :)

**Comment by mrnugget** [comment]
RFC is here: https://docs.google.com/document/d/1Z68vV1SvCmRW5Hz5v4SkI8oUW4pgLmq5199RmLYToeU/edit#
