### ISSUE TITLE
Enable access to license info from database layer 

### ISSUE THREAD

**Issue by kelsey-brown** [sourcegraph/sourcegraph#20037]
BizOps would like to be able to pull[ license data](https://sourcegraph.com/site-admin/dotcom/product/subscriptions) (ex. expiration date, tags) into BigQuery and eventually Salesforce to consolidate information about customer licenses so it is easily accessible to AEs/CEs. Right now that data is [not accessible on the db layer](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/internal/dotcom/productsubscription/licenses_graphql.go#L83:1) (more details in [slack](https://sourcegraph.slack.com/archives/CHPC7UX16/p1618431275345600)). 

This is relatively low priority but will become increasingly important as we gain new customers and release more features. [This](https://github.com/sourcegraph/analytics/issues/140) is blocked until we can access this info. 

cc @ebrodymoore

**Comment by ebrodymoore** [comment]
Is this the @sourcegraph/core-application team that would handle this? If so, I just want to make sure you all are aware of it - this is fairly low priority in relation to the private code push but if we could get it prioritized in the next few months it would be a huge help to the sales and CE teams!

**Comment by tsenart** [comment]
Hi @ebrodymoore! If the objective is to import this data into Salesforce, could the BizOps team not use the GraphQL API to import that data?

**Comment by ebrodymoore** [comment]
Yeah, I'd need to get ramped up creating a script using the API but I have an [initial query](https://sourcegraph.com/api/console#%7B%22query%22%3A%22query()%7B%5Cn%20%20dotcom%7B%5Cn%20%20%20%20productSubscriptions%7B%5Cn%20%20%20%20%20%20nodes%7B%5Cn%20%20%20%20%20%20%20%20activeLicense%7B%5Cn%20%20%20%20%20%20%20%20%20%20subscription%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20account%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20username%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20info%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20productNameWithBrand%5Cn%20%20%20%20%20%20%20%20%20%20%20%20tags%5Cn%20%20%20%20%20%20%20%20%20%20%20%20userCount%5Cn%20%20%20%20%20%20%20%20%20%20%20%20expiresAt%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%7D) so this can definitely be done. I'll remove the core-app tag but may ask you and your team some questions around the API!
