### ISSUE TITLE
Migrate from our custom site24x7 plugin

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#20038]
Our terraform site 24x7 custom provider no longer works https://github.com/sourcegraph/terraform-provider-site24x7 

We should consider migrating to a working provider (there is no official one) or fixing ours. 

Effects:
- We cannot change the site24x7 config via terraform 

We should leverage GCP alerts for this

**Comment by daxmc99** [comment]
Planning to completely deprecate site24x7 as part pf DevOps team work

**Comment by JenRed777** [comment]
Need to announce that this is no longer a thing

**Comment by daxmc99** [comment]
Announced here: https://sourcegraph.slack.com/archives/C0EPTDE9L/p1646691895852269
