### ISSUE TITLE
User External Account encryption: handle null authdata correctly

### ISSUE THREAD

**Issue by arussellsaw** [sourcegraph/sourcegraph#20030]
Right now we will set authdata to an empty string instead of null if we try to encrypt a null authdata, we should fix this to set it to be actually null, and update the OOB migration to recognise null values when checking progress.

**Comment by arussellsaw** [comment]
also fix NewMigrator to not use dbconn.Global

**Comment by tsenart** [comment]
And encrypt account_data too!

**Comment by arussellsaw** [comment]
gosh i should really write things down when we speak about them. thanks!
