### ISSUE TITLE
symbols | fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by 5h1rU** [sourcegraph/sourcegraph#20042]
- **Platform information:** 
- Local environment

#### Steps to reproduce:

1. Run the local env with `enterprise/dev/start.sh`
2. Go to any commit or file which use symbols, e.g. [link](https://sourcegraph.test:3443/github.com/sourcegraph/sourcegraph/-/commit/bfb6d7847115ac8d6422df42c34f5796ca6a1f4e?visible=1&toast=integrations)
3. Hover any token

#### Expected behavior:
It shows the tooltip with the go definition and finds references on the UI.

#### Actual behavior:
The build stops all the services and is not able to recover. It needs to rerun step 1.
[Logfile](https://gist.github.com/5h1rU/7f54323af88702440b89a2e18ce75862)

**Comment by eseliger** [comment]
This is working for me:

![image](https://user-images.githubusercontent.com/19534377/114795823-cb340400-9d8f-11eb-8398-67470ca8c9b1.png)

But I saw "_Cfunc_sqlite3_load_extension" in the stack trace in your logfile, so perhaps building the libsqlite failed.

Can you try running `./dev/libsqlite3-pcre/build.sh` please?

**Comment by 5h1rU** [comment]
Thanks for your answer, @eseliger Unfortunately, this is not working.

Also I ran 
`rm -rf libsqlite3-pcre.dylib`
`./dev/libsqlite3-pcre/build.sh`

**Comment by keegancsmith** [comment]
Is this still an issue?
