### ISSUE TITLE
Code insight charts may have weird negative y-labels

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#20046]
#### Steps to reproduce:

1. Go to code insight charts
2. Notice that some charts have strange negative y-labels. (see image below)

![image](https://user-images.githubusercontent.com/18492575/114825460-ec681500-9dce-11eb-8188-40a2434d95ce.png)
 

#### Expected behaviour:
For some charts we have to clamp first lowest y value by some number (In the case in the picture above, we should limit the lower Y bound to zero)

#### Actual behavior:
Having a negative value in charts where it doesn't make any sense.

**Comment by Joelkw** [comment]
@vovakulikov is there a PR that closes this? Didn't see one in either the extensions codebase or sourcegraph/sourcegraph

**Comment by vovakulikov** [comment]
@Joelkw I thought I was fixed that ticket unintentionally by non-related to this issue directly PR but it turned out that problem still can be found in our charts with some specific chart hights.  

I prepared a small fix for this problem https://github.com/sourcegraph/sourcegraph/pull/22018
