### ISSUE TITLE
No data on grafana graphs

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#20041]
Some grafana dashboards on cloud and dogfood report no data:

- https://k8s.sgdev.org/-/debug/grafana/d/repo-updater/repo-updater?viewPanel=100102&orgId=1&from=now-24h&to=now 

We should ensure these metrics are still reporting correct values

**Comment by bobheadxi** [comment]
This looks like one of those graphs that intentionally don't show anything if there are no errors: https://docs.sourcegraph.com/admin/observability/dashboards#repo-updater-src-repoupdater-syncer-sync-errors-total

The panel is owned by core app, so we might want to check with them instead

**Comment by ryanslade** [comment]
> This looks like one of those graphs that maybe intentionally won't show anything if there are no errors: https://docs.sourcegraph.com/admin/observability/dashboards#repo-updater-src-repoupdater-syncer-sync-errors-total
> 
> The panel linked in the issue description is owned by @sourcegraph/core-application so we might want to check with them instead

That's correct, an empty panel here indicates we're *not* seeing any sync errors, so that's a good thing :)

**Comment by bobheadxi** [comment]
What do you think about https://github.com/sourcegraph/sourcegraph/pull/22836?
