### ISSUE TITLE
Page loads can hang on gitlab.com and other repositories with large numbers of repositories

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#2007]
Due to the way we fetch permissions for GitLab instances, page loads can hang if an instance has a very large number of GitLab repositories (e.g., gitlab.com).

Repro:
* Add a gitlab.com GitLab external service with authz enabled
* Add a private repo to Sourcegraph
* Log in as a user that does NOT have access to the private repo
* Visit the private repo page on Sourcegraph. Observe it hang. Logs will show it is slowly fetching all repositories, page by page, for a given user (including public ones).

**Comment by beyang** [comment]
WIP branch: bl/faster-gl-authz

**Comment by nicksnyder** [comment]
This is only if auth is enabled for GitLab, right? Can you explain why this should block cutting a release?
