### ISSUE TITLE
symbol select kind via `symbols` GQL endpoint

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#20075]
We support selecting symbol kind via search queries, but not via `symbols(...)` endpoint in GQL. This is something we could look into supporting, though it's unclear to me what the general constraints and documentation concerns are around query strings for specific result endpoints like `symbols`. Worth discussing at some point.

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket,  please tell use how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
