### ISSUE TITLE
Network errors when requesting list of contexts should degrade gracefully

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#20073]
I was doing a simple search: https://sourcegraph.com/search?q=context:global+console.log&patternType=literal

One of the XHR requests failed with a 502 (I assume maybe a deploy was happening) and I got an error for the whole page.

![Screen Shot 2021-04-15 at 4 46 23 PM](https://user-images.githubusercontent.com/754768/114951918-2b678c00-9e0a-11eb-9591-f87c5c60748f.png)

Is it not possible to degrade more gracefully?

**Comment by limitedmage** [comment]
@novoselrok Can you take a look? This is context related.

**Comment by novoselrok** [comment]
I tried running the query in the link and it works with global and personal context, and all contexts are loaded properly. I think this is most likely deploy related as mentioned and not context specific.

**Comment by limitedmage** [comment]
> I tried running the query in the link and it works with global and personal context, and all contexts are loaded properly. I think this is most likely deploy related as mentioned and not context specific.

We should be more graceful in handling error requests, eg. fall back to contexts disabled with global as the default if we can't get the user's autodefined list. Let me know

**Comment by nicksnyder** [comment]
Yeah, the problem is not that the error happened, instead the problem is that we didn't handle the error gracefully.

**Comment by lguychard** [comment]
@novoselrok tentatively added this to the project board for this iteration -- this seems like something we'd need to fix.
