### ISSUE TITLE
Code insights error: relation "series_points" does not exist (SQLSTATE 42P01)

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#20072]
I went to sourcegraph.com and saw this:

![Screen Shot 2021-04-15 at 4 35 10 PM](https://user-images.githubusercontent.com/754768/114950757-9748f500-9e08-11eb-983b-4befb4e65ccd.png)

**Comment by slimsag** [comment]
I was doing some ops & wiped the DB to fix an issue, this is fixed.
