### ISSUE TITLE
E2E test failures

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#20100]
The e2e tests are currently failing https://buildkite.com/sourcegraph/e2e 

@sourcegraph/distribution has been investigating these issues and come to the conclusion that these test failures are likely within the tests themselves and not related to the infrastructure. 

Could the @sourcegraph/frontend-platform team help to resolve these issues by running these tests locally and confirming that these tests pass locally?

**Comment by 5h1rU** [comment]
Thanks for the report, @daxmc99. Can we update the **BittBucket** token there? It seems like this is the problem.

**Comment by 5h1rU** [comment]
e2e tests are working as expected. Feel free to open it again in case the error comes back.
