### ISSUE TITLE
Search erroneously reports no results found

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#20117]
In [this search](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+type:diff+aws-sdk-go&patternType=literal), I get a timeout warning banner that says that **no** results were found and I should increase the timeout, but in fact there were results found. Maybe not all, so that's why this message shows up, but I found the error message a bit misleading.

![image](https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/4ac50c40-8ccb-4b47-bbb1-c44768eb8901/b42148b2-009c-4a6f-b0f4-ec774dea35fe?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy80YWM1MGM0MC04Y2NiLTRiNDctYmJiMS1jNDQ3NjhlYjg5MDEvYjQyMTQ4YjItMDA5Yy00YTZmLWIwZjQtZWM3NzRkZWEzNWZlIiwiaWF0IjoxNzE4MzY0Mzk0LCJleHAiOjMzMjg4OTI0Mzk0fQ.akhFIFylbtbYMgnUWXYA6iIp54Pl6BJlqKQ5FeMbfIk)

**Comment by malomarrec** [comment]
Collecting similar feedback in https://github.com/sourcegraph/sourcegraph/issues/20117

**Comment by eseliger** [comment]
#20117 is this ticket, I guess you meant another one?

**Comment by malomarrec** [comment]
Try again!
https://github.com/sourcegraph/sourcegraph/issues/20138

**Comment by fkling** [comment]
Don't know if this is still an issue. If it comes again we can reopen or create a new issue.
