### ISSUE TITLE
Dart code intelligence

### ISSUE THREAD

**Issue by bunopus** [sourcegraph/sourcegraph#2011]
Hello. I would really happy to see [Dart](https://www.dartlang.org/) language support in sourcegraph. This can be very useful for many users because of the big popularity of [Flutter](https://github.com/flutter/flutter) and also Dart is a cool language.
Looks like we have all the tools for that: 
- [Language server](https://github.com/natebosch/dart_language_server)
- [Syntax highlight](https://github.com/guillermooo/dart-sublime-bundle)  

I tried to combine everything together, but it's not so obvious. 

### Code highlight
According to #2, to add code highlight it must be done in https://github.com/sourcegraph/syntect_server. But how to debug it, and connect with sourcegraph local instance? Looks like this part is missing in docs. I want to be sure it's working before sending PR

### Code intelligence  
I tried to add code intelligence for Dart in my local environment, but failed. Steps:
1. Run local sourcegraph instance via Docker
2. Download and run [lsp-adapter](https://github.com/sourcegraph/lsp-adapter) with [dart_language_server](https://github.com/natebosch/dart_language_server)
```bash
> ./lsp-adapter_darwin_amd64 --trace --didOpenLanguage="dart" --glob=*.dart dart_language_server
2019/01/24 15:51:22 proxy.go:104: CloneProxy: accepting connections at 127.0.0.1:8080
```
3. Added following to the _Global Settings_:
```json
{
   "langservers": [
      {
         "language": "dart",
         "address": "tcp://127.0.0.1:8080"
      }
   ],
   "extensions": {
      "langserver/dart": true,
   }
}
```
4. Unfortunately Dart intelligence isn't working for me  

Maybe i did something wrong? How can i debug that sourcegraph instance connecting to lsp-adapter and then to dart_language_server?

Thanks for your help

**Comment by chrismwendt** [comment]
I'm glad you're interested in adding Dart!

The only way to get code intelligence working is by creating a [Sourcegraph extension](https://docs.sourcegraph.com/extensions) that runs in the browser. The way that we've gotten the language server to communicate with the Sourcegraph extension for [other languages](https://docs.sourcegraph.com/user/code_intelligence#language-support) is by:

- adding WebSocket support so that the Sourcegraph extension running in the browser can communicate with the language server
- passing to the language server an HTTP URL that points to a zip archive of the current repository so that the language server can fetch it, unzip it, and begin analysis

Let me know if that's something you'd like to work on, I'm happy to go into more detail 😄 

How did you find out about lsp-adapter and that `langservers` field?

**Comment by bunopus** [comment]
Thanks for the answer, @chrismwendt. I will start digging the docs about extensions. One question: is code highlighting should be added via extension too? I'm asking because right now many languages supported via syntect server. 
>How did you find out about lsp-adapter and that langservers field?

Google 😄

Oh, i get it. I tried to search docs about this field (because there was a mention somewhere) and founded this: https://docs.sourcegraph.com/@v2.13.5/admin/site_config/all#langservers-array
Forgot to look at url, it's about old version. Sorry, my bad. It's not really clear that this documentation is obsolete.

**Comment by chrismwendt** [comment]
You're welcome! Nope, syntax highlighting is provided by syntect server. @slimsag would be able to help more that I on that front.

Ah, I think that issue about the search directing you to 2.13.5 will be resolved once we release 3.0 (in about a week).

**Comment by bunopus** [comment]
Hi, @slimsag! Could you please help with code highlighting for Dart language? What should i do to add it?

**Comment by chrismwendt** [comment]
Dart code intelligence has been added in Sourcegraph 3.0 :tada:

https://about.sourcegraph.com/blog/sourcegraph-3.0#code-intelligence-for-all-languages

[Try it out](https://sourcegraph.com/github.com/flutter/flutter@1e5d2e55fc29f6187877124e0cfffeb585960f8e/-/blob/packages/flutter/lib/src/widgets/scroll_simulation.dart#L52:29) on Sourcegraph.com:

![image](https://user-images.githubusercontent.com/1387653/52603751-fec81c00-2e1c-11e9-86d4-e82c8b6c0399.png)

**Comment by slimsag** [comment]
I've added syntax highlighting (in code files) for Dart. It will be in the next v3.1 shipping soon. Example on Sourcegraph.com:

https://sourcegraph.com/github.com/dart-lang/dart-tutorials-samples/-/blob/its_all_about_you/web/main.dart
