### ISSUE TITLE
Load SCSS helpers into CSS modules automatically

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#20137]
To use global SCSS mixins or variables in CSS modules, we need to `@import` them before that. 
Using [sass-resources-loader](https://github.com/shakacode/sass-resources-loader) should allow us to do it automatically. 

Slack [thread](https://sourcegraph.slack.com/archives/C89KCDK5J/p1618835211274900?thread_ts=1618465323.223700&cid=C89KCDK5J) for context.

**Comment by felixfbecker** [comment]
That's an awesome solution, I didn't know about that!
