### ISSUE TITLE
Sourcegraph logo is broken in Percy tests

### ISSUE THREAD

**Issue by LawnGnome** [sourcegraph/sourcegraph#20154]
For example, [in this build](https://percy.io/Sourcegraph/Sourcegraph/builds/9958977/changed/560451754?browser=chrome&browser_ids=16&subcategories=approved&viewLayout=overlay&viewMode=original&width=1920&widths=960%2C1920), the Sourcegraph logo is replaced by a broken image.

[From Felix in Slack:](https://sourcegraph.slack.com/archives/C01C3NCGD40/p1618857494068400?thread_ts=1618856923.068300&cid=C01C3NCGD40)

> The logo being broken has to do with the integration tests not serving static assets properly I think.

**Comment by valerybugakov** [comment]
@gitstart-sourcegraph, fixing this issue should address [the problem](https://percy.io/Sourcegraph/Sourcegraph/builds/14315071/changed/808532103?browser=chrome&browser_ids=20&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1920&widths=1920) with the Sourcegraph logo on the home page, which we [just added](https://github.com/sourcegraph/sourcegraph/pull/28350) to Percy.

<img width="1281" alt="Screenshot 2021-12-02 at 17 34 23" src="https://user-images.githubusercontent.com/3846380/144453265-58ab158e-7dca-44f0-9437-bf8ba8847dca.png">
