### ISSUE TITLE
Code monitoring navbar entry appears in OSS build

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#20166]
The code monitoring navbar item is currently displayed in the OSS version of sourcegraph, but it leads to a 404-ing page. I think we should remove the link in non-enterprise.

**Comment by benvenker** [comment]
@lguychard I think the decision was made to move Code monitors to paid plans so we might need to do this. I'm going to move it back to our triage column so I remember to check in on the pricing strategy.

**Comment by camdencheek** [comment]
Closing since the OSS version no longer exists.
