### ISSUE TITLE
Inaccurate alert for repo:`contains` expressions

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#20193]
`repo:contains(file:README.md) and repo:contains(file:CHANGELOG)` evaluates successfully, but because our backend alerts make simple assumptions about queries and repository results, it surfaces an inaccurate alert:

<img width="1434" alt="Screen Shot 2021-04-20 at 12 47 26 AM" src="https://user-images.githubusercontent.com/888624/115357932-ffce0400-a171-11eb-9520-152a0ecc7e88.png">

**Comment by camdencheek** [comment]
Closed as fixed
