### ISSUE TITLE
Improve scaling documentation

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#2019]
https://github.com/sourcegraph/deploy-sourcegraph/blob/master/docs/scale.md

- [ ] There is no mention of how to scale the `symbols` service. For ~12k repos we currently advise 4 symbols service replicas.
- [ ] The number of searcher replicas suggested are too high: For ~12k repos we currently advise using 20 searchers, and the suggested amount for that would appear to be more than 20 because for `5k` repos we suggest 20.
- [ ] The number of gitserver replicas suggested are too high. For ~12k repos we currently advise using 6 gitservers, and the suggested amount for that would appear to be around  ~15 because for `5k` repos we suggest 8.

For sourcegraph/server:

- [ ] Here’s another question. We have over 1000 projects. How well can Sourcegraph scale with a single instance? How long until my hardware no longer makes a difference? I currently have Sourcegraph running on an 8-core machine with 16 GB of RAM.

**Comment by keegancsmith** [comment]
For things like gitserver, scaling has more to do with traffic than number of repos. For searcher and symbols, we need to scale out by number of repositories for it to be able to handle large unindexed searches.

**Comment by nicksnyder** [comment]
Perhaps more relevant info to share would be guidance on how to detect if an instance is under or over scaled instead of a concrete number of replicas.

**Comment by beyang** [comment]
@ggilmore I wrote up a rough outline of a new scaling guide here: https://docs.google.com/document/d/1dBvc_hpovih0fNjb9vHDh3jMPDyfn6Tm_VZ-k1QK6lQ/edit, informed by my experience helping 2 relatively large customers answer scaling questions. Can we discuss in person before you start on this?

**Comment by ggilmore** [comment]
Due to some higher priority issues that came up, I am worried that this is at-risk of not shipping in 3.2. I plan to discuss this with Beyang tomorrow.

**Comment by ryan-blunden** [comment]
@ggilmore, @beyang: Is this still on track for for 3.3?

**Comment by beyang** [comment]
Nope, looks like it never made it to the [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/2809), so backlogging it for now. If it should be prioritized, let us know.

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.11 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by beyang** [comment]
Closing this in favor of https://github.com/sourcegraph/sourcegraph/issues/6274 (that issue links back to this one).
