### ISSUE TITLE
Add autosuggestions to repository field in code insight create form

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#20198]
To create code insight user should fill _repositories_ input as a code insight setting. With plain input without any suggestions it might be a bit inconvenient. You can find low-fi designs [here ](https://www.figma.com/file/QfeID0EEYMEPdEv8pbGULB/Code-Insights-WIP?node-id=260%3A11)

To improve user experience on this field we may add something like suggest component to code insights create form.

Simple demo: https://codesandbox.io/s/261pd

**Comment by Joelkw** [comment]
(About to share larger updates in slack but noting explicitly here – let's reframe this as "autosuggest" for v1)
