### ISSUE TITLE
Align search query input of code insight creation form

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#20201]
According to our [low-fi designs ](https://www.figma.com/file/QfeID0EEYMEPdEv8pbGULB/Code-Insights-WIP?node-id=262%3A11)of code-insights creation UI we have query Input to fill query setting of code insight. It seems a bit similar to what we have in code monitor creation form.

_Code insight_
<img width="641" alt="image" src="https://user-images.githubusercontent.com/18492575/115371180-6c78eb00-a1d2-11eb-936b-6777e5c3c0a5.png">

_Code monitoring_
<img width="703" alt="image" src="https://user-images.githubusercontent.com/18492575/115371419-a0eca700-a1d2-11eb-8983-eb51d531b0ec.png">

It might be useful to avoid duplication of these two components and make this part of UI shared between code insights and code monitoring.

**Comment by felixfbecker** [comment]
@AlicjaSuska is it intentional that these look slightly different? Code monitoring looks like a [input group with button addon](https://getbootstrap.com/docs/4.6/components/input-group/#button-addons), but code insights looks like a link absolutely positioned over the input.

**Comment by vovakulikov** [comment]
I'm closing this issue in favor of https://github.com/sourcegraph/sourcegraph/issues/21339
