### ISSUE TITLE
h4 update to 14pt medium from 16pt regular

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#20219]
To even out our type scale we need to modify the previously specified h4 value of 16pt regular to 14pt medium. 

Example:

![image](https://user-images.githubusercontent.com/539268/115435027-43e6f600-a1be-11eb-9566-398ded823580.png)

**Comment by felixfbecker** [comment]
@rrhyne FYI I think you mean `14px` (`0.875rem`), `14pt` would be `18.6667px`. It's also a unit in CSS 😄

**Comment by rrhyne** [comment]
Yes, thank you!
