### ISSUE TITLE
"private repositories" OAuth scope for the users enrolled in the private code test

### ISSUE THREAD

**Issue by artemruts** [sourcegraph/sourcegraph#20229]
### Description

Currently requests to add external code hosts with OAuth are missing `private repositories` scope.   
That would be `repo` for GitHub and `read_repository` for GitLab  providers.

This results in private repositories not fetched and not displayed on the "Manage repositories" page. 

### Acceptance criteria

- `private repository` scopes are added for all of the GitHub/Gitlab OAuth requests where users have the `AllowUserExternalServicePrivate` tag (or another way to limit this rollout only to the Sourcegraph team, _for now_).

### Notes

I believe, relevant changes will need to be added to:
- [GitHub OAuth provider](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/internal/auth/githuboauth/provider.go#L74)
- [GitLab OAuth provider](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/internal/auth/gitlaboauth/provider.go#L33)

**Comment by artemruts** [comment]
@unknwon Joe, can you please confirm I'm not mistaken here? TY!

**Comment by unknwon** [comment]
Yep, thanks for looking into this, the conclusion look right (also double checked). 👍

**Comment by ryanslade** [comment]
Thanks for looking into this.

How shall we "re-auth" users that have already gone through the OAuth flow for public code? I'll check if we have the metadata on our side to detect they don't have the correct scope.

**Comment by ryanslade** [comment]
So it looks like when you connect to a code host all that happens is we place the token in the external service config. I think we're going to need to detect when a user has the private code flag enabled and they're unable to list private code because they lack the scope on their token and prompt them to re-auth.

OAuth does support requesting additional scopes from what I can tell but we should probably communicate this to the user somehow as it'll require a redirect to the auth provider.

Not the greatest user experience though, @quinnkeast, any ideas?

**Comment by quinnkeast** [comment]
Are we able to detect on the frontend that they have code host connections, but they're only valid for public repos?

**Comment by unknwon** [comment]
I thought there was an API to list current granted scope for a GitHub access token but couldn't find it at the moment.

Based on our current situation, if we don't see any private repos listed, we could lazily prompt users to go through OAuth flow again in the UI, and if succeed, we will get a new OAuth token to overwrite whatever we have before. It is also safe if the user decides to drop out in the middle, we still have the old OAuth authorization with access to only public repositories.

**Comment by artemruts** [comment]
I believe this was addressed by https://github.com/sourcegraph/sourcegraph/pull/20487. @ryan @asdine is that correct or do we need to do anything else?

**Comment by ryanslade** [comment]
I think we've covered the specific case where the user has been opted in by tagging them. 

We don't currently support the case where we enable it site wide which is something we need to figure out by June 4th but I think is a separate issue.

**Comment by ryanslade** [comment]
I've pushed a PR to ensure that we also check site wide config.

What's still missing is the UX of how we re-auth a user who has previously authed with only public repo scope and we then enable private code support.

**Comment by quinnkeast** [comment]
In that case, it would seem the only way to surface this would be to invalidate existing connections and force a re-connect, which doesn't feel great. I'll think on this—do you have any other possibilities in mind?

**Comment by ryanslade** [comment]
Ah, I just found a way to check existing scopes, it comes back in a header 😄 

```
curl -H "Authorization: token REDACTED" https://api.github.com/user -I
HTTP/2 200
server: GitHub.com
date: Fri, 07 May 2021 13:41:55 GMT
content-type: application/json; charset=utf-8
content-length: 1318
---SNIP
x-oauth-scopes: repo
---SNIP
```

**Comment by ryanslade** [comment]
Designs here:
https://www.figma.com/file/zR0nDDrcbRSQaPry5o5Jyq/Update-OAuth-scope?node-id=246%3A11
