### ISSUE TITLE
New info, warning, danger colors

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#20233]
To implement notices and alerts, we needed to add a 4th color value to each of the semantic colors:
```
primary-04 / Light - #E1F0FF
success-04 / Light - #EBFAEE
info-04 / Light - #EAFAFC
warning-04 / Light  - #FFF7E1
danger-04 / Light - #FBEAEA
secondary-04 / Light - #F1F4F9
merged-04 / Light - #EEE9FD

primary-04 / Dark - #03284F
success-04 / Dark - #054410
info-04 / Dark- #025762
warning-04 / Dark   - #3D2904
danger-04 / Dark  - #3D0A0A
secondary-04 / Dark  - #545967
merged-04 / Dark  - #1F0A5C
```

Additionally a 2nd link color was required to ensure the blue links have accessible contrast on notices:

```
link-color-2 / Light - #0766CC
link-color-2 / Dark - #70B0F3
```
![image](https://user-images.githubusercontent.com/539268/115486513-aadecc00-a20b-11eb-8ecc-43d7a5471223.png)

**Comment by rrhyne** [comment]
Updated with new link color required for notices.

**Comment by umpox** [comment]
Closing this issue as it has been moved to 'Done' on the [design refresh board](https://github.com/orgs/sourcegraph/projects/160#card-59482976)
