### ISSUE TITLE
Include activation status in pings

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#2024]
#2069 defines an **activation** metric for new Sourcegraph instances. We need to include simple scalar values (such as `has performed code search with >1 results? TRUE/FALSE`) in the pings to measure this.

Proposals for pings: https://docs.google.com/document/d/1jxhzlRG-5jpbcdEXCXKXaSKLURF_HAjo6A3BgTFIb8c/edit

**Comment by dadlerj** [comment]
This is largely complete with #2104 , but leaving it open for:

- [ ] Differentiating between go-to-def and find-refs (https://sourcegraph.com/search?q=todo.*%5C%28dan%5C%29+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+)
- [ ] Sourcegraph extension status metrics

**Comment by nicksnyder** [comment]
I am moving this out of 3.1

**Comment by dadlerj** [comment]
Thanks, closing this, I'll break the second checkbox out into a separate issue
