### ISSUE TITLE
search: dashboard to help debug search backend issues

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#20245]
We need a general dashboard to help diagnose why things are going wrong in search. This isn't a dashboard for alerting, but rather once alerts are going off we can investigate what component is the issue.

Ideas:
- [ ] zoekt scheduler
- [x] indexing state
- [x] git resolve revision latency
- [ ] blob fetch latency
- [ ] db.Repos.List latency
- [ ] archive fetching in searcher/symbols

**Comment by keegancsmith** [comment]
cc @lguychard @camdencheek @sourcegraph/search-core

**Comment by camdencheek** [comment]
I've also been feeling the need for something like this. However, it seems to be at odds with our [monitoring pillars](https://about.sourcegraph.com/handbook/engineering/observability/monitoring_pillars#dashboards-should-only-be-created-with-the-monitoring-generator) in that it would necessarily require grouping metrics from more than one service together.

**Comment by keegancsmith** [comment]
> I've also been feeling the need for something like 
> this. However, it seems to be at odds with our [monitoring 
> pillars](https://about.sourcegraph.com/handbook/engineering/observability/monitoring_pillars#dashboards-should-only-be-created-with-the-monitoring-generator) 
> in that it would necessarily require grouping metrics from more 
> than one service together.

We can create a PR against that repo as well then :P This is all up to
debate to be fair. Pretending that search doesn't depend on how the
frontend or gitserver is behaving is naive, so I think there is
certainly a place for holistic dashboards that help debug real issues
that customers see.

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket, please let us know how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
