### ISSUE TITLE
Sourcegraph fails to fetch/update gitolite repos that have @ in their name 

### ISSUE THREAD

**Issue by aisbaa** [sourcegraph/sourcegraph#20257]
- **Sourcegraph version:** 3.26

#### Steps to reproduce:

For repos that contain `@` symbol in their name Sourcegraph adds `?` before `@` symbol when fetching. 

0. Suspected code https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/vcs/url.go#L80-107
1. Go playground example https://play.golang.org/p/f5fn4p64LLn
2. Regex playground https://regex101.com/r/DAuCaS/1

#### Expected behavior:

Sourcegraph should no add `?` before `@` to repo name when fetching from gitolite.

**Comment by rvantonder** [comment]
Additional concern where `@` in repo names likely conflict with backend logic for some query syntax. Filed https://github.com/sourcegraph/sourcegraph/issues/20333.

> We can't have a repo pattern containing `@` in a query like repo:foo@something because it conflicts with `@` being interpreted as a separator for revision syntax, e.g.,  `repo:foo@revision`. *Interim solution is that users should use a `.` (regex for any character) instead of @ if the repo is known to contain an @. *

**Comment by aisbaa** [comment]
I know, sourcegraph replaces `@` with `-` after cloning, but for git fetch you still need to used name with `@` symbol.
