### ISSUE TITLE
Search finds private repo results, but does not display them

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#20254]
This only seems to be an issue when running with `SOURCEGRAPHDOTCOM_MODE=true`

This makes me think it's related to the defaultrepos query not performing any authz filtering.

Searches that hit private repos appear to return results that are then not visible:

The screenshots below show results from an *unauthenticated* user matching against results in a private repo.

<img width="2542" alt="Screenshot 2021-04-21 at 16 27 52" src="https://user-images.githubusercontent.com/25610/115570651-9576aa00-a2be-11eb-8631-76bfd10e1db6.png">

Searching for only repos also returns private repos the user does not have access to:

<img width="2542" alt="Screenshot 2021-04-21 at 16 29 01" src="https://user-images.githubusercontent.com/25610/115570802-b50dd280-a2be-11eb-81b6-cdb08ed39f13.png">

Navigating to the repo gives a repo not found error, as we could expect. 

The repo is clearly marked as `private` in the database yet amending the search to only include `public` repos still finds it.

**Comment by ryanslade** [comment]
@keegancsmith Am I correct in assuming that this method is responsible for returning the list of repos we want to pass to Zoekt and it is responsible for filtering out repos the user should not have permission to see? 

https://github.com/sourcegraph/sourcegraph/blob/1e88f2d36cc1cc0a8fdabf7e22c4015c9d7565cd/cmd/frontend/internal/search/repos/repos.go#L50

If that's the case then I think we have an issue on Cloud as we usually fall back to fetching default repos which will include all user added repos, even private ones.

I guess we'll need to modify the default repos query to only include public repos and then also append any private repos the user has added via their own external services.

**Comment by keegancsmith** [comment]
> @keegancsmith Am I correct in assuming that this method is 
> responsible for returning the list of repos we want to pass to 
> Zoekt and it is responsible for filtering out repos the user 
> should not have permission to see?

Yes
 
> If that's the case then I think we have an issue on Cloud as we 
> usually fall back to fetching default repos which will include 
> all user added repos, even private ones.

Are the repos part of the default_repos table? Then yes that is an 
issue.
 
> I guess we'll need to modify the default repos query to only 
> include public repos and then also append any private repos the 
> user has added via their own external services.

Agreed if the above is true. Think of default repos as the global list
of repos to search. Also remember that the Default Repos store has a in
process cache. So anything extra we will have to "mux" in.

**Comment by ryanslade** [comment]
> Are the repos part of the default_repos table? Then yes that is an
issue.

No, they're not directly in the `default_repos` table but they're included in the query which joins against a few other sources: 

https://github.com/sourcegraph/sourcegraph/blob/1e88f2d36cc1cc0a8fdabf7e22c4015c9d7565cd/internal/database/repos.go#L842-L872

We use the default repos queries for two things:

* Default list of repos to search, this we should change to only include public repos on Cloud
* The list of repos we want Zoekt to index. This should still include user added private repos as we want them to be indexed.

I'll keep looking into this as it's my priority today.
