### ISSUE TITLE
References panel errors in percy

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#20261]
This is a screenshot from percy 
![image](https://user-images.githubusercontent.com/19534377/115575242-aa553c80-a2c2-11eb-90d3-5f81b7398090.png)

Not sure if this is just something that's mocked in a weird way, or if we actually have a regression here. We should definitely look into it, at least.

**Comment by Joelkw** [comment]
@muratsu can you triage this and add to the appropriate column? I don't know what this affects or if this means we might miss something important if this is broken.

**Comment by vdavid** [comment]
We're deprecating this version of the references panel, and the new one doesn't have to do anything with Integrations, so we're closing this.
