### ISSUE TITLE
3.27.1 patch release

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#20307]
@sourcegraph/distribution I am requesting the following commits be included in a patch release. They are already merged into `main`:
- bb9d23ccd799967c2cbf6dcd5f8502d651c8b19b
- 689d4044631abf6755e43c0ac231c728c0a19e96
- b08476ff34bf244655138fc52ba3aee00ef55c99

However, I'm **unsure of the dependencies of those commits with previous commits done after we cut 3.27.0**. Could we just cut from main?

> Are users/customers actively asking us for these changes and cannot wait until the next full release?

The 3.27 release is borked. Customers that upgrade will have issues.

> Are the changes extremely minimal, well-tested, and low risk such that not testing as we do in a full release is OK?

Can we approach this as a re-release? What tests do we need to run?

> Is there some functionality completely broken that warrants redacting the prior release of Sourcegraph and advising users wait for the patch release?

Yes.

> This will interrupt our regular planned work and release cycle, taking 3-6 hours of our time, and will take up all of our site admin's valuable time by asking them to upgrade or producing noise for them if they don't need to upgrade.
>
> Do you believe the changes are important enough to warrant this?

Yes.

> Patch releases are a signal we can do something better to improve the quality of Sourcegraph. Have you already scheduled a call (or created a google doc) to perform a [retrospective](https://about.sourcegraph.com/retrospectives) and identify ways we can improve?

No. I don't think we have enough data points to consider this a trend.

---

**For the [release captain](https://about.sourcegraph.com/handbook/engineering/releases#release-captain)** - after reviewing and approving this request:

- If there is [already an upcoming patch release](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+), add the listed commits alongside a link to this issue
- If there is no upcoming patch release, create a new one:
  - Update [`dev/release/release-config.jsonc`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/release/release-config.jsonc) with the patch release in `upcomingRelease` and `releaseDate` (and open a PR to `main` to update it)
  - `yarn release tracking:issues`
  - Add the listed commits alongside a link to this issue to the generated [release tracking issue](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+)

Comment and close this issue once the relevant commit(s) have been cherry-picked into the release branch.

**Comment by daxmc99** [comment]
This has been released, closing
