### ISSUE TITLE
New endpoint to determine affiliated repo sync status

### ISSUE THREAD

**Issue by artemruts** [sourcegraph/sourcegraph#20318]
### Description

Closes #19826

Currently in the "Manage repositories" view when repositories selection is saved - we wait for the code hosts to sync, that guarantees the changes have propagated and were picked up.

This creates a latency problem, users have to wait for ~3-7 seconds until the code hosts sync.

**Example:**

https://user-images.githubusercontent.com/1319181/115759581-64ee4900-a36e-11eb-89ee-f6f2e44369b6.mov

### Proposal

We need a new endpoint.

> We can detect that we've started a background process and just indicate to the user that something is happening, then prompt them to refresh once we know we have new data. We'll need a new API for this, but it should be fairly straightforward as we can tap into the external_service_sync_jobs table. Clicking save currently adds a row to that table already.
— @ryanslade

I agree with Ryan that the easiest way is:

For the sake of this example let's call the new endpoint - `AffiliatedReposSyncStatus`

1. instead of querying `ExternalServices` endpoint while the repositories are "saving", we take users to the repositories list view
2. while the repositories list view is loading we send requests to the following endpoints:
   1. `UserRepositories` - to determine a list of repositories we should display
   2. `AffiliatedReposSyncStatus` - to determine if we should show the "Repositories are syncing" banner
   
If the `AffiliatedReposSyncStatus` endpoint replies with `all synced` (TBD) status:
  1. hide the "Repositories are syncing" banner
  2. show the "Repositories are synced. Please refresh at will" banner
  3. stop querying `AffiliatedReposSyncStatus` endpoint

If the `AffiliatedReposSyncStatus` endpoint replies with `not synced` (TBD) status:
  1. show the "Repositories are syncing" banner
  2. query `AffiliatedReposSyncStatus` endpoint every 2 seconds to check if the status has changed

### Constrains

When the `AffiliatedReposSyncStatus` endpoint replies with `all synced` status - `UserRepositories` endpoint when queried should already have all of the repositories the user had previously selected.

### TODO

- [ ] copy for banner messages
- [ ] new endpoint name and how the statuses will look like

### Notes

These changes will also solve current intermittent bug when the "Some repositories are still being updated." banner is shown.

**Comment by artemruts** [comment]
@quinnkeast WDYT? Does this sound OK from the UX perspective?

**Comment by ryanslade** [comment]
Bear in mind that we periodically sync external services in the background and a user could have more than one (either GitHub or GitLab or both) 

The current state of each external service sync can be one of: 

- Queued (will run soon)
- Processing (running now)
- Completed or Errored (finished)

It's also possible that we don't have a row since it is a new service that has never run.

I think for this process we actually don't care when we're next scheduled. All we care about is:

* Are we running now or soon?

So a simple `bool` return may be all we need. 

Is there anything else? 

Bear in mind we can already find out about failed sync jobs from the StatusMessages endpoint

**Comment by quinnkeast** [comment]
Sounds like a plan to me!

**Comment by ryanslade** [comment]
1d estimate is for backend work only.

I propose we add a new query that takes an external service ID and a time duration argument. We return true if the external service is currently syncing or is due to sync in less than "duration" from now.

**Comment by ryanslade** [comment]
I'm going to work on this tomorrow. @artemruts this is what I'm proposing as the API, WDYT?:

```graphql
"""
Returns true if any of the code hosts supplied are syncing now or within "seconds" from now.
"""
codehostSyncDue(ids: [ID!]!, seconds: Int!): Boolean!
```

**Comment by artemruts** [comment]
> I'm going to work on this tomorrow. @artemruts this is what I'm proposing as the API, WDYT?:
> 
> ```graphql
> """
> Returns true if any of the code hosts supplied are syncing now or within "seconds" from now.
> """
> codehostSyncDue(ids: [ID!]!, seconds: Int!): Boolean!
> ```

@ryanslade this looks good, thank you!
