### ISSUE TITLE
Request for 3.27 patch release

### ISSUE THREAD

**Issue by LawnGnome** [sourcegraph/sourcegraph#20329]
@sourcegraph/distribution I am requesting the following commits be included in a patch release. They are already merged into `main`:

The intent of the questions below is to ensure we keep Sourcegraph high quality and [only create patch releases based on a strict criteria.](https://about.sourcegraph.com/handbook/engineering/releases#when-are-patch-releases-performed) If you can answer yes to many or most of these questions, we will be happy to create the patch release.

- https://github.com/sourcegraph/sourcegraph/commit/060cef795c2ccaca653e22b06891d06ca1f6391a

I have read [when and why we perform patch releases](https://about.sourcegraph.com/handbook/engineering/releases#when-are-patch-releases-performed) and answer the questions as follows:

> Are users/customers actively asking us for these changes and cannot wait until the next full release?

Yes; see https://github.com/sourcegraph/customer/issues/311 for more detail.

> Are the changes extremely minimal, well-tested, and low risk such that not testing as we do in a full release is OK?

Yes; the actual diff is a very obvious -4+4 lines of Go, and I've added an explicit check to the relevant unit test that covers this.

> Is there some functionality completely broken that warrants redacting the prior release of Sourcegraph and advising users wait for the patch release?

No; the specific configuration required is reasonably specific (Batch Changes + Bitbucket Server + SSH push). I believe we're already in communication with all affected users, so a redaction and/or deployment freeze is unnecessary.

> This will interrupt our regular planned work and release cycle, taking 3-6 hours of our time, and will take up all of our site admin's valuable time by asking them to upgrade or producing noise for them if they don't need to upgrade.
>
> Do you believe the changes are important enough to warrant this?

Discussing this with @malomarrec and @justdueck, we believe so. The only possible workaround for affected users would be to downgrade to 3.26, so although the configuration is (as mentioned above) quite specific, it's a serious regression for users of that configuration.

> Patch releases are a signal we can do something better to improve the quality of Sourcegraph. Have you already scheduled a call (or created a google doc) to perform a [retrospective](https://about.sourcegraph.com/retrospectives) and identify ways we can improve?

We'll discuss this at our next team retro, which is on Tuesday.

---

**For the [release captain](https://about.sourcegraph.com/handbook/engineering/releases#release-captain)** - after reviewing and approving this request:

- If there is [already an upcoming patch release](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+), add the listed commits alongside a link to this issue
- If there is no upcoming patch release, create a new one:
  - Update [`dev/release/release-config.jsonc`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/release/release-config.jsonc) with the patch release in `upcomingRelease` and `releaseDate` (and open a PR to `main` to update it)
  - `yarn release tracking:issues`
  - Add the listed commits alongside a link to this issue to the generated [release tracking issue](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+)

Comment and close this issue once the relevant commit(s) have been cherry-picked into the release branch.

**Comment by daxmc99** [comment]
Have we cut this patch release?

**Comment by daxmc99** [comment]
Closing, I believe this went into the 3.30.1
