### ISSUE TITLE
Code insights error handling breaks badly on FF relative to Chrome

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#20336]
In firefox, an unfound repo or other insights error just causes all the insights to load infinitely with errors logged to the console – which means if you have one error-producing insight, it blocks the others. 

![image (24)](https://user-images.githubusercontent.com/11967660/115796044-eef5dc00-a385-11eb-9bd7-d0d311b0054a.png)

In chrome, the page loads and the error messages apply to the individual insights – which means if you have one error-producing insight, it doesn't block the others. 

![image (23)](https://user-images.githubusercontent.com/11967660/115796034-ebfaeb80-a385-11eb-93cf-ad2c94d15afa.png)

(Further examples in [this thread](https://sourcegraph.slack.com/archives/C014ZCKMCAV/p1619130307209800).) 

As of now, steps to reproduce:

1. Use firefox
2. Sign into demo.sourcegraph.com with your Google account
3. Paste this into your user settings: https://gist.github.com/slimsag/3f5be43ac1b29743322e99c006a6a209
4. Visit the insights page.

**Comment by felixfbecker** [comment]
I think the `DataCloneError` is the culprit here, which probably "crashes" the entire extension host resulting in the infinite loading (as nothing is updated anymore, lost communication). This is likely an `Error` instance that is trying to be sent over the worker boundary, but `Error`s are not clonable. There is code for this case in some places, e.g. in `proxySubscribable()`: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@b37ecfe6737e0c34896ff622ce6a2a02b8ff459a/-/blob/client/shared/src/api/extension/api/common.ts#L37
But apparently that is not hit/circumvented, at least in this case.

@vovakulikov do you think you're able to debug this?

**Comment by vovakulikov** [comment]
@felixfbecker 
> but Errors are not clonable

It seems like this is clonable for Chrome and Safari (but not for Firefox). If be honest I'm not sure how to fix that problem since we use errors in extension widely. @tjkandala @muratsu can you have a look at this?

**Comment by felixfbecker** [comment]
The extension host (not the extension) should make sure that no "real" `Error` instances cross the worker boundary. E.g. like in the code I linked above, everywhere an Error could be passed (specifically where this particular error is passed, if you were to trace it with a debugger/logs) it should be ensured it's converted like `{ message: error.message, name: error.name, stack: error.stack }` and converted back on the other side. Ideally of course in unified places, like that function linked above, not duplicated X times for every API.

**Comment by muratsu** [comment]
Can you walk me through a repro? The demo website is now working and I can't repo it on my local server. Not sure how do I create and nuke an insight to get to the broken state

**Comment by felixfbecker** [comment]
I can repro on any instance in Firefox if the insight provider is throwing any kind of error, which for example can be triggered through a non-existing repo (JSON settings):
```json
"searchInsights.insight.testRepro": {
    "title": "Test repro",
    "repositories": ["asdasdasd"],
    "series": [
      {
        "name": "Test",
        "query": "bla",
        "stroke": "blue"
      }
    ]
  },
"experimentalFeatures": {
  "codeInsights": true
},
"extensions": {
  "sourcegraph/search-insights": true,
}
```
