### ISSUE TITLE
Regression: Code tour box is grey in light mode

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#20345]
This seems to be a recurring regression. The background color should be white:

![image](https://user-images.githubusercontent.com/539268/115811987-8880b600-a3a5-11eb-8eb4-508f1ebd2143.png)

**Comment by limitedmage** [comment]
@rrhyne I think they have always been this color in light mode? We use `var(--color-bg-3)` for these. What color should I use instead that also works in dark mode? Black background doesn't work, it blends in too much since there is no (visible) drop shadow.

**Comment by limitedmage** [comment]
|   | Current `var(--color-bg-3)` | New `var(--body-bg)` |
| --- | --- | --- |
| Light mode | ![image](https://user-images.githubusercontent.com/206864/115933954-dac4e400-a444-11eb-82d1-9fd7d6c57930.png) | ![image](https://user-images.githubusercontent.com/206864/115934085-1a8bcb80-a445-11eb-9e69-10a803d714bd.png) |
| Dark mode | ![image](https://user-images.githubusercontent.com/206864/115933986-e9130000-a444-11eb-8ca7-0bf23f128c0a.png) | ![image](https://user-images.githubusercontent.com/206864/115934063-0cd64600-a445-11eb-9478-73df3f488264.png) |

**Comment by rrhyne** [comment]
Body-bg please!

**Comment by limitedmage** [comment]
> Body-bg please!

I don’t think this looks good in dark mode, it blends in too much. It looks like you have floating text. The arrow color will also be changed and you won’t see what it’s pointing at.

**Comment by rrhyne** [comment]
Ah, sorry, I missed dark mode on my mobile. As this is a regression, can you simply set it back to the previous value?

**Comment by limitedmage** [comment]
> Ah, sorry, I missed dark mode on my mobile. As this is a regression, can you simply set it back to the previous value?

As far as I can tell from the code history, it has always been this color.

**Comment by limitedmage** [comment]
Will create a new variable `--tour-bg` for the bubble background color, use colors white in light mode and $gray-19 in dark mode. Redesign colors TBD.
