### ISSUE TITLE
Intermittent test failure in `TestTickerRateLimited`

### ISSUE THREAD

**Issue by indradhanush** [sourcegraph/sourcegraph#20350]
The following test failure was seen [here](https://buildkite.com/sourcegraph/sourcegraph/builds/94042#6a2db5d8-a37e-442f-83ed-e003f41e2616/213) which was fixed on a retry. 

```
FAIL: TestTickerRateLimited (0.02s)
    ticker_test.go:82: unexpected non-nil channel: 0xc000356300
```

**Comment by mrnugget** [comment]
@LawnGnome Assigning you because you might know what's causing this. But I'm also looking at this right now.
