### ISSUE TITLE
Design refresh: Dropdown nav

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#20366]
Components
https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Design-Refresh-Systemization-source-of-truth?node-id=954%3A1200

Sticker sheet
https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Design-Refresh-Systemization-source-of-truth?node-id=1955%3A33720

<img width="400" alt="Screenshot 2021-05-04 at 18 02 11" src="https://user-images.githubusercontent.com/20326070/117033700-e943b300-ad02-11eb-8998-4a376d8e1095.png">

**Comment by AlicjaSuska** [comment]
Moving to 'Done' as there are no blockers. I've created issue #21070 with the visual fixes. @5h1rU
