### ISSUE TITLE
Design refresh: Subnav

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#20365]
https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Design-Refresh-Systemization-source-of-truth?node-id=1172%3A652

**Comment by AlicjaSuska** [comment]
@quinnkeast could you please work with @5h1rU to review this issue? Thank you!

**Comment by rrhyne** [comment]
@quinnkeast @AlicjaSuska can one of you track down the status of this? I believe it's complete, but it's been in review for quite some time.
