### ISSUE TITLE
Design refresh: command palette

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#20373]
Sticker sheet:
 https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Design-Refresh-Systemization-source-of-truth?node-id=1506%3A653

**Comment by umpox** [comment]
Moving this to ready for development, after discussions in relation to navigation work

cc: @AlicjaSuska

**Comment by umpox** [comment]
Reopening for implementation review, @sourcegraph/design please review, raise any changes as new tickets and close this issue!

**Comment by AlicjaSuska** [comment]
Styles look good, thank you @5h1rU 

I've submitted #21072 - illustration contrast is too low (also in the current implementation). Would be great to fix before releasing the refresh @5h1rU
