### ISSUE TITLE
Diff highlighting renders differently

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#20387]
Introduced by https://github.com/sourcegraph/sourcegraph/pull/19986 as far as I can tell, after bisecting. 

# Previously:

<img width="1427" alt="Screen Shot 2021-04-23 at 5 34 24 PM" src="https://user-images.githubusercontent.com/888624/115941471-51b8a780-a45a-11eb-8342-1648328dcc03.png">

# Now:

<img width="721" alt="Screen Shot 2021-04-23 at 5 34 52 PM" src="https://user-images.githubusercontent.com/888624/115941477-554c2e80-a45a-11eb-9688-66bbce23636b.png">

The "Now" part still renders, but it's quite different. Is this intended? Or is it a regression? I think the previous rendering looked better (green for `+`, red for `-`).

**Comment by camdencheek** [comment]
Not intentional -- definitely a regression. I'll get it fixed ASAP.

**Comment by camdencheek** [comment]
Appears to be limited to the dark theme, so should just be a CSS fix

**Comment by camdencheek** [comment]
Thought this would've been closed with the linked PR. This is fixed now 👍

**Comment by rvantonder** [comment]
Sweeet
