### ISSUE TITLE
Browser extension: Freezing and lag when scrolling on Github PR diffs

### ISSUE THREAD

**Issue by jimbo1qaz** [sourcegraph/sourcegraph#2038]
- **Sourcegraph version:** ??? 
- **Platform information:** Ubuntu 18.04, Github + Sourcegraph extension 19.1.23.1746, Firefox 65.0b12 (64-bit)

#### Steps to reproduce:

1. Install https://storage.googleapis.com/sourcegraph-for-firefox/latest.xpi .
1. Go to https://github.com/jimbo1qaz/corrscope/pull/154/files (very long Github diff)
2. Hold Page Down or Page Up to scroll through page.

#### Expected behavior:
Smooth scrolling without page freezing.

#### Actual behavior:
Page freezes repeatedly. I assume it blocks on HTTP requests, whenever a file's header (and SourceGraph button) comes into view.

**Comment by sqs** [comment]
We are working on this in #2000. Thanks for the report and sorry for the issue.
