### ISSUE TITLE
Regression: after-line decorations add extra line breaks to code

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#20397]
![image](https://user-images.githubusercontent.com/10532611/116082077-486a4d80-a69b-11eb-8194-5163965eeccf.png)

Taken from https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/platform/context.ts#L32

The hit counts should be displayed at the end of each line, not on their own lines.

This must either be something with extensibility code or caused by the recent changes to syntax highlighting (since that returns the HTML table from the backend). cc @camdencheek

**Comment by camdencheek** [comment]
This seems likely related to the highlighting changes. I'll take a look after my meetings this morning
