### ISSUE TITLE
Revoking access to the Sourcegraph OAuth app doesn't trigger an error with code host connection

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#20391]
#### Steps to reproduce:

1. Create a code host connection with Cloud <> GitHub.
2. Go into your personal settings in GitHub and revoke access for the Sourcegaph OAuth app.
3. Return to Sourcegraph > Settings > Code host connections.

#### Expected behavior:

An error is shown related to the revoked code host.

#### Actual behavior:

It appears that nothing's wrong with the connection.

**Comment by artemruts** [comment]
I'll remove the `UX` label on this one. Once the backend knows how to handle expired/revoked tokens and doesn't report errors back to the client - this won't be a problem. We try to display all code host warnings/errors coming from the backend.

**Comment by ryanslade** [comment]
In theory we'll get an error in the notifications area the next time we attempt to sync. We don't have a way of being notified that the token was revoked so all we can do is wait until we next try to use it.
