### ISSUE TITLE
code-intel postgres_exporter image pulls from wrouesnel rather than sourcegraph organization

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#20415]
- **Sourcegraph version:** 3.27.2
- **Platform information:** 

#### Expected behavior:

codeintel-db `postgres_exporter` images is sourced from `sourcegraph` organization just like the [`pgsql` `postgres_exporter` deployment](https://github.com/sourcegraph/deploy-sourcegraph/blob/v3.27.2/base/pgsql/pgsql.Deployment.yaml#L70)

#### Actual behavior:

codeintel-db `postgres_exporter` image pulls from `wrouesnel` namespace ([details](https://github.com/sourcegraph/deploy-sourcegraph/blob/v3.27.2/base/codeintel-db/codeintel-db.Deployment.yaml#L68))

**Comment by daxmc99** [comment]
Fixed by https://github.com/sourcegraph/deploy-sourcegraph/pull/2798
