### ISSUE TITLE
k8s: pgsql deployment: pgsql pod crashes if permissions on /data/pgdata-11 is not 750 or 700

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#20425]
- **Sourcegraph version:** 3.27.2
- **Platform information:** AWS EKS, EBS volumes for /data

#### Steps to reproduce:

1. `/data/pgdata-11` has 770 permissions
2. Perform upgrade to 3.27.2
    ASSUMPTION: pgsql pod is in `CrashLoopBackOff` state
3. Check `/var/lib/postgresql/pg_ctl_old.log`.  There should be an error indicating that `/data/pgdata-11` must have 750 or 700 permissions.

#### Expected behavior:

Pod fixes the permissions or produces a log message in the stderr of the pod so it's accessible

#### Actual behavior:

Pod crashes with error `pg_ctl: could not start server` and no additional information.  In order to find the problem, you must change the entrypoint of the image and get a shell into the image to see the `/var/lib/postgresql/pg_ctl_old.log` file.

#### Workaround

1. Change [this line](https://github.com/sourcegraph/deploy-sourcegraph/blob/v3.27.2/base/pgsql/pgsql.Deployment.yaml#L30) to `command: ["sh", "-c", "if [ -d /data/pgdata-12 ] || [ -d /data/pgdata-11 ]; then chmod 750 /data/pgdata-*; fi"]`
2. Re-run upgrade
    ASSUMPTION: pod will start

**Comment by daxmc99** [comment]
PR here https://github.com/sourcegraph/deploy-sourcegraph/pull/2902

**Comment by daxmc99** [comment]
Fixed in https://github.com/sourcegraph/deploy-sourcegraph/pull/3124
