### ISSUE TITLE
3.27.4 patch release

### ISSUE THREAD

**Issue by indradhanush** [sourcegraph/sourcegraph#20440]
@sourcegraph/distribution I am requesting the following commits be included in a patch release. They are already merged into `main`:
* https://github.com/sourcegraph/sourcegraph/commit/ddadaee80ed28cd4fc543f662e52951366cf1e5d

I have read [when and why we perform patch releases](https://about.sourcegraph.com/handbook/engineering/releases#when-are-patch-releases-performed) and answer the questions as follows:

> Are users/customers actively asking us for these changes and cannot wait until the next full release?

The customer has requested an urgent patch release. 
* Customer tracking issue: https://github.com/sourcegraph/customer/issues/307

> Are the changes extremely minimal, well-tested, and low risk such that not testing as we do in a full release is OK?

Yes. The change allows us to clone repos with `@` in their names. I have tested this by using `src serve-git` and then adding `src-serve` as a code host while serving a repo with the following name: `test@domain`. The repo was successfully cloned to disk. 

However, since our UI relies on `@` to differentiate between a repo name and a revision, the repo won't be searchable from the UI and visiting the repo's URL on the UI will return a 404 (since the UI tried to `GET` a repo with the name `test` instead of `test@domain`. The customer _is _ aware of this limitation and we have a tracking issue for this: https://github.com/sourcegraph/sourcegraph/issues/20333

> Is there some functionality completely broken that warrants redacting the prior release of Sourcegraph and advising users wait for the patch release?

No. This includes only a fix for a very specific edge case for the customer.

> This will interrupt our regular planned work and release cycle, taking one full working day of our time, and will take up all of our site admin's valuable time by asking them to upgrade or producing noise for them if they don't need to upgrade.
>
> Do you believe the changes are important enough to warrant this?

Yes.

> Patch releases are a signal we can do something better to improve the quality of Sourcegraph. Have you already scheduled a call (or created a google doc) to perform a [retrospective](https://about.sourcegraph.com/retrospectives) and identify ways we can improve?

No. This was an unexpected edge case. 

---

**For the [release captain](https://about.sourcegraph.com/handbook/engineering/releases#release-captain)** - after reviewing and approving this request:

- If there is [already an upcoming patch release](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+), add the listed commits alongside a link to this issue
- If there is no upcoming patch release, create a new one:
  - Update [`dev/release/release-config.jsonc`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/release/release-config.jsonc) with the patch release in `upcomingRelease` and `releaseDate` (and open a PR to `main` to update it)
  - `yarn release tracking:issues`
  - Add the listed commits alongside a link to this issue to the generated [release tracking issue](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+)

Comment and close this issue once the relevant commit(s) have been cherry-picked into the release branch.

**Comment by indradhanush** [comment]
There is some uncertainty about this regarding if this is the right approach and if we should be supporting repo names with `@` in their name at all. As a result, this patch release is no longer required at the moment and we might revert the commit in question.

**Comment by ggilmore** [comment]
> There is some uncertainty about this regarding if this is the right
approach and if we should be supporting repo names with @ in their name at
all. As a result, this patch release is no longer required at the moment
and we might revert the commit in question.

We are about to finalize the 3.27.4 release, do we need to abort this
process?

**Comment by daxmc99** [comment]
I believe we have released this, can we close this issue?

**Comment by indradhanush** [comment]
For historical context, it was reverted here: https://github.com/sourcegraph/sourcegraph/commit/a8327dc1157d0839ed20b0151c521e376de93026
