### ISSUE TITLE
Double number of extension views in Code Insights page.

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#20442]
#### Steps to reproduce:

1. Open Sourcegraph.com and go to the settings page.
2. Change any settings in settings file.
3. Go back to `/insights` page.
4. Open dev tool and see that we have double numbers of code insight views. (See screenshot below)

![image](https://user-images.githubusercontent.com/18492575/116205238-35608780-a746-11eb-8a3a-efc9898c34d7.png)

Original handler where we fetch/get code insights views - https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/insights/pages/InsightsPage.tsx#L22-27

#### Expected behavior:
After changing user or organisation config/settings we **don't have** double number of code insights.

#### Actual behavior:
After changing user or organisation config/settings we **have** double number of code insights.

**Comment by Joelkw** [comment]
@vovakulikov thanks for catching this!
