### ISSUE TITLE
Error "<commit> is tree, not commit"

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#20464]
When trying to view a commit page for root commits, it fails with the following message in the UI: 

`Git command [git merge-base -- 4b825dc642cb6eb9a060e54bf8d69288fbee4904 391c5d218cba0d1d03b5c8c7988ab6c5f589f5f6] failed (output: "error: object 4b825dc642cb6eb9a060e54bf8d69288fbee4904 is a tree, not a commit fatal: Not a valid commit name 4b825dc642cb6eb9a060e54bf8d69288fbee4904"): exit status 128`

<img width="1285" alt="Screen Shot 2021-04-27 at 12 37 17" src="https://user-images.githubusercontent.com/12631702/116294525-4fee2d00-a755-11eb-8324-e99f5de22a61.png">

Reproducible [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph-c9/-/commit/391c5d218cba0d1d03b5c8c7988ab6c5f589f5f6)

**Comment by stefanhengl** [comment]
I cannot reproduce this anymore. @camdencheek please reopen if you think the issue still exists.

**Comment by camdencheek** [comment]
Looks fixed to me 👍
