### ISSUE TITLE
CLI produces an incorrect link to troubleshooting page

### ISSUE THREAD

**Issue by rfulwell** [sourcegraph/sourcegraph#20470]
- **Sourcegraph version:**
- src version
Current version: 3.27.0

#### Steps to reproduce:

1. Run a batch preview which fails for some reason (I was trying to run the command in a Docker container which seems to be unsupported).

#### Expected behavior:
Link to the troubleshooting page:
https://docs.sourcegraph.com/batch_changes/references/troubleshooting

#### Actual behavior:
The CLI incorrectly links to a URL with a dash in place of the underscore:
https://docs.sourcegraph.com/batch-changes/references/troubleshooting

![image](https://user-images.githubusercontent.com/470472/116307434-2d5f1280-a75b-11eb-94b3-0df4ef430f73.png)

**Comment by mrnugget** [comment]
Thanks for reporting @rfulwell!

We should not only fix this but also add a redirect so that the current link works.
