### ISSUE TITLE
Search repo autocomplete exploration

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#20499]
On cloud, the repo: filter has several UX issues that could be resolved with an improved dropdown menu:

* new users are unware the value can take regex
* users who do understand regex, lack a mental model of how to leverage it
* autocomplete is slow
* lack of ranking hundreds of thousands of repositories makes finding the correct repository difficult

Explore using the existing dropdown menu, pre-populated with 3 use cases:
* searching GitHub for an exact repository
* 'fuzzy' searching an org
* searching repo names

![image](https://user-images.githubusercontent.com/539268/116469564-2998c200-a827-11eb-966a-a7d03bcc578f.png)

* The exploration will be enabled as a feature flag
* A URL parameter will enable the feature flat so that the feature can be tested  via tasks and unmoderated sessions

**Comment by rvantonder** [comment]
The V1 is merged in #20606 so closing this. We can open more issues for other iterations as needed.
