### ISSUE TITLE
Search input design

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#20496]
Search bar has been modified for the redesign. 

Note that at XS sizes, slightly different behavior occurs. 

# Figma
https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Design-Refresh-Systemization-source-of-truth?node-id=1285%3A25746

**Comment by limitedmage** [comment]
I'll initially only implement the full-size design and will do the responsive design as part of https://github.com/sourcegraph/sourcegraph/issues/20685

**Comment by umpox** [comment]
Reopening for implementation review, @sourcegraph/design please review, raise any changes as new tickets and close this issue!

**Comment by rrhyne** [comment]
I'll leave this one open, pending:

https://github.com/sourcegraph/sourcegraph/issues/20685

**Comment by limitedmage** [comment]
@rrhyne  @AlicjaSuska  work on the redesigned search box has been completed, including QA items. Can this issue be closed?

**Comment by rrhyne** [comment]
Yes, thanks!
