### ISSUE TITLE
Event tracking for search success

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#20502]
To measure search success we need to be able to see sessions with search errors, especially common errors such as "No results" and "Too many repositories". 

Additionally, two other events are required to capture the success of queries:
* Copy permalink (with hash) (this needs an event)
* Raw download (needs an event)

Add tracking for these events.

**Comment by ebrodymoore** [comment]
Ideal scenario: we attach search errors to individual events (probably SearchResultsFetched) so we can associate the errors with specific search sessions in our event logs. 

I'll rely on those who have better judgement for implementation but an idea is adding `search_error: true, error: timeout` to the argument

**Comment by novoselrok** [comment]
Some notes:

We already track true search errors with the `SearchResultsFetchFailed` event. We include the error message in the argument as `code_search.error_message`. `SearchResultsFetchFailed` is mutually exclusive with the `SearchResultsFetched` event, so both can be used to delimit search sessions.

What we don't track are search alerts. I'll include the alert title within the `SearchResultsFetched` event. It will have the following path: `code_search.results.alert` and it will be `null` if no alert is present. You can view the full list of alert titles here: https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:%5Ecmd/frontend/graphqlbackend/search_alert%5C.go+title:+count:all&patternType=literal

I'm not sure what falls under the copy permalink event. I assume this is the button next to the "Raw download" link in the Blob page. We can track whether the user clicked on the permalink, but we cannot track if the user then copied the URL from the browser address bar. This is a hard browser limitation, we can only detect copy events within the page.

**Comment by rrhyne** [comment]
@ebrodymoore, one of the major errors are are looking to track is "No result". I see "No result" with a structural search description in that search you linked but not simply "No results".  Can you make sure that event is fired when this search is run?

https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:%5Ecmd/frontend/graphqlbackend/search_alert%5C.go+No+resultz&patternType=literal

**Comment by novoselrok** [comment]
The `No results` error/alert can be computed from the `SearchResultsFetched` event by checking if `results.result_count == 0` and `results.alert == null`, so I don't think we need to fire a separate event for that. 

The `No results` structural search alert is when a user is trying to run a structural search, but he does not have the structural search toggle enabled. It will be tracked as a `SearchResultsFetched` event with `results.alert='No results'`.
