### ISSUE TITLE
search result has incomplete highlighting

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#20510]
[`lang:ocaml module Type`](https://sourcegraph.com/search?q=lang:ocaml+module+Type&patternType=literal&case=yes)

<img width="806" alt="Screen Shot 2021-04-29 at 1 56 45 AM" src="https://user-images.githubusercontent.com/888624/116526182-2be23700-a88e-11eb-8c3e-146e78ae2e3f.png">

**Comment by rvantonder** [comment]
CC @camdencheek for recent changes. I haven't bisected to confirm it's from recent commit.

**Comment by camdencheek** [comment]
Unlikely from the highlighting changes I'm making, but I'll take a peek this morning to confirm

**Comment by rvantonder** [comment]
Yeah see that, this isn't a file highlighting issue. Still feels like a regression, having a hard time thinking it's always been like this. I might bisect later.

**Comment by rvantonder** [comment]
This needs escalating, it is a major regression and not in b50a1fe27f6354fae936b247043376309861c1a0 (Mar 22), so introduced some time after that. I can reproduce with a regex query and it borks structural search highlighting big time.

Regex query:

[`repo:^github\.com/sourcegraph/sourcegraph$ Search\(.* file:client/web/src/search/backend.tsx lang:typescript`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+Search%5C%28.*+file:client/web/src/search/backend.tsx+lang:typescript&patternType=regexp)

<img width="964" alt="Screen Shot 2021-04-30 at 11 42 19 AM" src="https://user-images.githubusercontent.com/888624/116739986-380ee700-a9a9-11eb-99e3-8b73fd7d4f14.png">

**Comment by rvantonder** [comment]
@camdencheek Sorry to say I think this is due to the syntax highlighting changes. Those changes are somehow affecting our highlight overlays. I confirmed that c85ab07c2129b7eb1255bba28aeb5595d4d9b1f6 does _not_ have this issue, so it is fairly recent, and appears to be re-introduced in the un-revert commit, and master.

**Comment by camdencheek** [comment]
On it 👍
