### ISSUE TITLE
Datadog extension docs missing screenshot

### ISSUE THREAD

**Issue by emchap** [sourcegraph/sourcegraph#20521]
#### Describe the issue
Go to https://sourcegraph.com/extensions/sourcegraph/datadog-metrics . You'll see `Datadog extension screenshot` and `Datadog metric` on the page, but not the actual screenshot or metric.

#### Where is the issue located?
Datadog landing page in Sourcegraph extensions.

#### Suggested resolution
Add the screenshot and metric image back.

**Comment by muratsu** [comment]
Fixed!
