### ISSUE TITLE
Make docs pages more visually appealing

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#2052]
Reading our docs is currently the opposite of a delightful experience. There is almost no color on the page, everything is in a monochrome grey tone. There are zero visually engaging elements, like icons or variations in backgrounds and borders. The search box doesn't match the design of the rest.

Here are some good examples of visually engaging docs:
https://scalameta.org/metals/docs/editors/overview.html
https://www.prisma.io/docs/

Also good to look at because it's similar in content:
https://code.visualstudio.com/docs

Also good to look because it's the same style:
https://getbootstrap.com/docs/4.2/getting-started/introduction/

**Comment by ryan-blunden** [comment]
Theme improvements tracked at https://github.com/sourcegraph/docs.sourcegraph.com/pull/11

**Comment by felixfbecker** [comment]
New design looks great and I had added syntax highlighting
