### ISSUE TITLE
Enable code host "sync all" mode for Sourcegraph cloud

### ISSUE THREAD

**Issue by artemruts** [sourcegraph/sourcegraph#20530]
### Description

Currently code host's "sync all" functionality is behind a `AllowUserExternalServiceSyncAll` user tag on the client.
To enable it we need to investigate the following issue:

* https://github.com/sourcegraph/sourcegraph/issues/20478 — `ExternalService` endpoint doesn't return repos in `allRepos:true` mode

After the issues are resolved there _might be_ a few straightforward code changes (https://github.com/sourcegraph/sourcegraph/issues/20570) on the client to make "sync all" work.

**Comment by RafLeszczynski** [comment]
@artemruts just for bookkeeping could you also create an issue for this part `straightforward code change`?
