### ISSUE TITLE
Background of close icon clashes with action item when no hover contents are displayed

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#2053]
Previously, when only the action buttons were displayed (when a def was loading for example), and you hovered the pinned hover, the close icon was shown but its background did not clash with the hover:

![image](https://user-images.githubusercontent.com/1741180/51917819-aaff1100-23e0-11e9-87a9-6ed1b67cc078.png)

Now, its background clashes with the hover:

![image](https://user-images.githubusercontent.com/1741180/51917709-6d9a8380-23e0-11e9-9da3-a6231b216e3e.png)

I don't think this was particularly graceful before either, but the clashing background makes it look pretty buggy now IMO. Maybe there's a better solution?

**Comment by francisschmaltz** [comment]
I think a good stop gap would set a min-height for the box that prevents the x from overlapping.

**Comment by attfarhan** [comment]
Reverted https://github.com/sourcegraph/sourcegraph/commit/cac576ae749b04dce921fc883a6ba338efd45c11, so closing this. Reopened https://github.com/sourcegraph/sourcegraph/issues/1935 and added to backlog.

**Comment by francisschmaltz** [comment]
@sqs this should be a higher priority since basic code intel might have hovers that are only buttons. 

@attfarhan can we have the close button only visible if there is more content than just the buttons?

**Comment by vanesa** [comment]
@francisschmaltz could we move the close button outside of the hover, like this:
![image](https://user-images.githubusercontent.com/9110008/52552660-5d44c880-2e24-11e9-9ae2-531fe3e3aa7f.png)

**Comment by sqs** [comment]
Backlogging. This is not a high priority. It is a relatively minor visual glitch. The bigger improvements we are making in #2380 are more important.

**Comment by felixfbecker** [comment]
We are only showing it on hover now and it doesn't have a background, so closing
