### ISSUE TITLE
Buttons contributed to the extensions toolbar should allow to specify "toggled" state

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#2055]
Many buttons contributed to the toolbar are to toggle something on or off, e.g. Coverage colors, soon code intel, ...
The on/off state can currently only be communicated through the label "Enable"/"Disable". This makes it impossible to omit the lable to save space, and looks very weird on GitHub where the buttons look like actual 3D buttons, that don't change into a "pressed" state when the setting is enabled.

There should be a field `"toggled"` in package.json for the button that is a boolean expression (and can read a setting for example) that makes the button toggled or not. On the Sourcegraph webapp, the state could be indicated by a background color change (something like `rgba(0, 0, 0, 0.5)` in light theme, `rgba(255, 255, 255, 0.5)` in dark theme).

I see this as a prerequisite to add an enable/disable for TypeScript because otherwise the experience is very weird.

Rel #1572

**Comment by sqs** [comment]
The motivation for this is that sometimes users DON'T want code intel on a code block, and this lets them quickly disable it (without completely uninstalling Sourcegraph). The reasons why they might not want code intel usually are bugs themselves (such as interfering with text selection, showing annoying loading indicators, showing useless/incorrect fuzzy results or `any` TS hovers, etc.) but this is a nice escape hatch for users who get value 98% of the time and who want a way to disable it the other 2%.

**Comment by felixfbecker** [comment]
Why was this moved to 3.2?

**Comment by lguychard** [comment]
@felixfbecker I could not get to this last week. Is the question "why was it moved to 3.2 rather than backlog" or "why was it not done in 3.1"?

**Comment by felixfbecker** [comment]
@lguychard could you take a look at this this week?

**Comment by lguychard** [comment]
Yes
