### ISSUE TITLE
Status bar tutorial/docs

### ISSUE THREAD

**Issue by muratsu** [sourcegraph/sourcegraph#20579]
We've shipped status bar capability but we currently don't have any documentation for extension developers. We should have some minimal documentation with preferably a sample.

**Comment by Joelkw** [comment]
Would be sweet to have! Do you think we could do 2 passes at this – a 30-minute or less pass to just add something to our docs/point you at codecov or something using it, and a 1/2 day pass (sometime further in the future, maybe when the team is full size 3 again) for better documentation?

**Comment by muratsu** [comment]
Agreed on having 2 passes
