### ISSUE TITLE
Code insights charts breaks with unhelpful "no results" if I enter a not found repository

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#20603]
A customer [reported this issue](https://sourcegraph.slack.com/archives/C01S5DM6NG7/p1620049197098000) and thought it was a problem with their repo not returning any results, because that's what the error says and they fixed it by removing a repo. 

After playing with it a while, I wasn't able to reproduce this with a 0-results string (any arbitrary gibberish) and that correctly calculates 0 results onto the chart. _But_ if I type in a gibberish repo (so the repo isn't found), I do get this error (rather than a more descriptive and correct error like "repo not found") – example for a fake repo called Sourcegraph "aboutlk" 

![image](https://user-images.githubusercontent.com/11967660/116941225-22592600-ac24-11eb-8df5-16de0e1a88d7.png)

@felixfbecker (for when you return) or @vovakulikov – I think this error will resolve itself (so there is no work to do here) when we ship the new setup flow because the repo field should handle validation/catch these, right? Tagging you to confirm that indexing won't be an issue – is it possible for the repo filter to allow a repo that's connected but not yet indexed?

**Comment by vovakulikov** [comment]
@Joelkw Thanks for filling it out. Now we don't have a validation step for checking can we reach some repo in the repositories field for search or stats insights creation UI. I believe we need to add this but not sure we can add this validation by the next release 22 May, just because we already full of others tickets.

**Comment by felixfbecker** [comment]
I think we can close this now since we have validation on the Repositories field in the creation UI.
