### ISSUE TITLE
Focusing backward on contexts selector broken after completing a search

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#20629]
#### Steps to reproduce:

1. Click into the search input.
2. Shift-tab to change focus to the contexts selector (works).
3. Select a context from the selector. Use either keyboard or mouse to do this.
4. The search will immediately run, and change focus to the search input (correct behaviour).
5. Try using shift-tab to change focus to the contexts selector again.

#### Expected behavior:

Contexts selector is focused.

#### Actual behavior:

Sometimes, nothing happens. Other times, it works as expected.

Video: https://cln.sh/gzXNjq

**Comment by camdencheek** [comment]
Closing since the context selector has since been redesigned
