### ISSUE TITLE
tech debt: two search implementations

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#2062]
There may already be an issue for this open.

search2.go and search.go both exist, and it is hard to know which one is the in-use search implementation. We should have only one.

https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/search2.go

https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/search.go

**Comment by keegancsmith** [comment]
We haven't shipped search2, it is behind a feature flag. When we have time to focus on search again it will be cleaned up. I don't think this issue is worth tracking right now. Maybe some source code comments would help? I can follow up if you think so.

**Comment by slimsag** [comment]
Yes, that would help. A short statement like that at the top of both files would do.
