### ISSUE TITLE
Playground search button needs design

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#20639]
![playground-search-button-needs-design](https://user-images.githubusercontent.com/25070988/117020459-c14e5280-acf6-11eb-88de-326a43d43711.png)

It's nice that the button indicates shortcuts, but it looks a bit big / clumsy / non Sourcegraph-themed.

**Comment by camdencheek** [comment]
Closing since the search playground is not an advertised part of the product and we don't have plans to improve it.
