### ISSUE TITLE
tech debt: two repo-updater implementations

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#2063]
There may already be an issue for this open.

There are two repo-updater scheduler implementations but only one is in use AFAIK, we should get rid of the other one.

https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+Scheduler2Enabled#3

**Comment by nicksnyder** [comment]
Thanks for filing an issue. We have not yet had a non-beta release where the new implementation is on by default so the current state is intentional. We should be able to remove the old implementation and feature flag in 3.1 unless some issues arise.

**Comment by nicksnyder** [comment]
This is good to complete before starting on https://github.com/sourcegraph/sourcegraph/issues/2025

**Comment by tsenart** [comment]
> This is good to complete before starting on #2025

👍

**Comment by keegancsmith** [comment]
We will remove this if it makes #2025 easier. Otherwise, I think we should hold off removing the older implementation since we have some large customers who have not updated to 3.x yet, and may find issues with the new implementation.
