### ISSUE TITLE
Playground: Use new design for result types navigation

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#20635]
Autocomplete or hover do not work on multiple lines.

**Steps to reproduce**
Go to the [playground](https://sourcegraph.com/search/console?q=%2F%2F%20Search%20in%20teh%20facebook%20%2Freact%20repo%0Arepo%3A%5Egithub.com%2Ffacebook%2Freact%24%0A%0A%2F%2F%20Don%27t%20search%20in%20test%20files%0A-file%3Atest%0A%0A%2F%2F%20Search%20for%20useState%0AuseState%0A%0A%2F%2F%20Try%20using%20the%20repo%20selecter%20here)
Try adding a repo selector on a new line, no autocomplete will appear.

**Comment by camdencheek** [comment]
Closing since the playground is not a priority, nor is it advertised anywhere in the product
