### ISSUE TITLE
Design refresh: User nav

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#20646]
Components
https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Design-Refresh-Systemization-source-of-truth?node-id=954%3A1200

Sticker sheet
https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Design-Refresh-Systemization-source-of-truth?node-id=954%3A7769

<img width="280" alt="Screenshot 2021-05-04 at 18 02 17" src="https://user-images.githubusercontent.com/20326070/117034037-34f65c80-ad03-11eb-934a-6e2ae4d2919e.png">

**Comment by pdubroy** [comment]
Re-opening since it still needs review from design.
