### ISSUE TITLE
Listing default repos can cause search queries to fail

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#20651]
With the default search timeout of 20s, the [`ListDefaultRepos`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/database/repos.go#L833) query often times out (currently takes around 15-25s). Its result is cached and it is updated in the background once it passed once and queries come in regularly, but especially after frontend startup, queries will take a while and can time out. I think the cache should be initialized on frontend startup and be updated as part of a background job that runs every minute, instead of on the request path.
Also, maybe there's potential to make the query faster, @mrnugget and I gave it a quick stab but we weren't lucky. After all, our tables are not particularly small, so maybe that is something we have to accept to be rather slow.

**Comment by keegancsmith** [comment]
cc @stefanhengl @rmmh

**Comment by stefanhengl** [comment]
This has been resolved with https://github.com/sourcegraph/sourcegraph/pull/21835
