### ISSUE TITLE
`archived:yes`/`fork:yes` is returned in the repos filter chips

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#20655]
The forked:yes and archived:yes filter appears in the repo filter chips:

![image](https://user-images.githubusercontent.com/539268/117071671-3cf2d400-ace4-11eb-9a5f-f2f70895cd71.png)

Now that we are handling archived repo selection in the search results dropdown, we would like to remove them from the repos list so that they do not appear in the repositories panel of the new sidebar:

![image](https://user-images.githubusercontent.com/539268/117070267-57c44900-ace2-11eb-84ff-712fdb389e77.png)

**Comment by rrhyne** [comment]
@limitedmage tagging you for visibility!

**Comment by limitedmage** [comment]
This is because the `kind` of this filter is `'repo'`. @sourcegraph/search-core can we create a new `kind` for this type of filter what is distinct from specific repo suggestions?

**Comment by stefanhengl** [comment]
@limitedmage Do we really want to keep the filter chips for archived:yes and forked:yes under a different `kind` or wouldn't it be better to just remove them entirely?

**Comment by stefanhengl** [comment]
EDIT: If we pick a different `kind` (EG "generic"), the chips would show up in the "Filter" carousel as well as in the dropdown. Do we want to keep both?
<img width="2560" alt="Screenshot 2021-05-05 at 09 37 23" src="https://user-images.githubusercontent.com/26413131/117109998-ca3a3500-ad85-11eb-99f2-921d5ba5ddd2.png">

**Comment by rrhyne** [comment]
Having them in filter carousel, which is to be labeled “dynamic filters” in
the redesign would be fine with me.
