### ISSUE TITLE
start anchor for file regex doesn't match for `type:diff` searches

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#20664]
[`repo:^github\.com/sourcegraph/sourcegraph$ file:^README\.md type:diff fix`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:%5EREADME%5C.md+type:diff+fix&patternType=literal) should find matches. The issue is the start anchor `^` is not being honored. Removing the `^` finds results (but over matches all file paths).

**Comment by rvantonder** [comment]
Bisect progress:

Working as of c91d72ed50e7f99296f2cdd7cdabeae7db96580e


Broken as of 6d86c041d3939afb312182916a0fdf998dedd622

**Comment by rvantonder** [comment]
Regression introduced in https://github.com/sourcegraph/sourcegraph/pull/19460. Please self-assign if you feel comfortable picking this up @camdencheek, maybe something to tackle in next iteration?

**Comment by camdencheek** [comment]
Thanks for tracking it down. On it 👍

**Comment by camdencheek** [comment]
Actually, never mind answering that question. I can bisect myself :) 

Looks like the issue has to do with how we parse the diff chunks. Unclear if it actually has to do with #19460. Before we were returning `internal/cmd/search-blitz/README.md`, now we are returning `b/internal/cmd/search-blitz/README.md`, which is the format that a normal `git log --patch` returns it in. Working on cause now.

**Comment by rvantonder** [comment]
Cool. My exact steps were to go through the [compare view](https://github.com/sourcegraph/sourcegraph/compare/1167b9e...6e55404) and manually bisect until I landed on that commit, so I wasn't looking at releases. I manually killed my local instance, ran `yarn generate`, and started it up again for every commit I tried. If you don't do a full restart, it might look like an instance is running for a certain commit, but the build is just failing and it's running a different state.

**Comment by camdencheek** [comment]
@rvantonder are we sure that query _should_ return matches? When did README.md contain the literal `fix`?

**Comment by rvantonder** [comment]
Oh, ha, I didn't use that query to bisect. I used `repo:^github\.com/sourcegraph/sourcegraph$ file:^README\.md type:diff`. Sorry! I think I meant to use the query with `file:^CHANGELOG\.md` for the query in the issue description.

**Comment by camdencheek** [comment]
Okay cool! I thought I found the issue, but then wasn't seeing any results still 😂
