### ISSUE TITLE
Current filter designation

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#20662]
Many users do not understand some basic rules of working with filters:

* Filter input ends when a space is entered
* Filters must not have a space after the colon

These alterations to the UX of filter editing should correct those issues:

https://www.figma.com/file/UObwwQGIspZDNhuvwNvKIa/Filter-ux-explorations?node-id=0%3A1&viewport=41%2C431%2C0.25

![image.png](https://images.zenhubusercontent.com/5467e9ba7c6ccc6277a5f103/dfc419de-a83a-4a55-98e5-9c155348a91f)

**Comment by camdencheek** [comment]
Closing since I think this is largely solved by the improved completions menu. Feel free to reopen.
