### ISSUE TITLE
Implement XS responsive design for search input

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#20685]
![image](https://user-images.githubusercontent.com/206864/118736130-a6033d00-b7f6-11eb-964e-55e5c67d3611.png)

Note that this does NOT include multi-line support. That will be done separately with #21215.

### Figma

Normal: https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Design-Refresh---Systemization-(source-of-truth)?node-id=908%3A0

With Version Contexts: https://www.figma.com/file/QQYKGTl5MufkNIu9D9mOgN/temp-version-context-ui?node-id=1%3A812&viewport=351%2C542%2C0.25

**Comment by limitedmage** [comment]
@rrhyne @AlicjaSuska  Where does the version contexts dropdown fit into this design? We still need to support this (at least for a while) for enterprise customers.

**Comment by AlicjaSuska** [comment]
@limitedmage we've discussed it during today's design meeting. We should put the version context dropdown above the search input. @rrhyne FYI

**Comment by rrhyne** [comment]
@AlicjaSuska you can see the ticket I created earlier for design and the direction I took here:

https://github.com/sourcegraph/sourcegraph/issues/21066
