### ISSUE TITLE
Instance activation flow for site admins

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#2069]
We want to help users on new Sourcegraph instances see value. This includes both changes to the actual setup process and improving our documentation content.

Let's define [**activation**](https://500.co/activate-or-die-3-keys-to-user-activation-for-saas-part-1/) for a Sourcegraph instance as:

> On the instance, at least 1 of the following actions has been performed (by any user):
>
> - Find references
> - Code search that has 1 or more text or diff results

- This implies that they have added repositories. 
- "Any user" will usually be the site admin.
- This is a necessary but not sufficient condition for seeing value from Sourcegraph. It is OK that it's not sufficient; using a simple-to-understand/measure activation metric means we can start making improvements and measuring results more quickly.
- In the future, we'll probably change this definition as we get more data about how it correlates to 20+ DAU, likely by adding the following additional steps:
  - The instance has a non-localhost `externalURL`.
  - The instance has 2 or more users.

## Plan

[**Issues labeled <kbd>activation-flow</kbd>**](https://github.com/sourcegraph/sourcegraph/issues?q=is:issue+is:open+sort:updated-desc+label:activation-flow+milestone:3.1)

#2258 

Also see [**Proposed step-by-step activation flow**](https://docs.google.com/document/d/1P7uMHtOeYK1IwMj-1WtKspo16v8C_Mevj3qe1cX_kGY/edit#heading=h.vh7b6txgdnec).

## Test/review plan

- Code reviewer: @felixfbecker (TODO?)
- Tester: @ryan-blunden

**Comment by slimsag** [comment]
I know this is a tracking issue, but since I have no action items around activation flow I am unassigning myself to reflect that. Add me back if there is clear work I need to do here.
