### ISSUE TITLE
Code navigation UX and robustness

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#2070]
Code navigation includes code intelligence, Git blame, Codecov/Datadog extensions, Chrome/Firefox extensions, and anything else that helps a user navigate their code.
 Code navigation is one of the 2 main features of Sourcegraph for users (along with code search).

We've made big changes to code navigation the last few months, such as moving language/git-blame functionality to extensions and enabling code intel by default (in 3.0). We want to reserve time to be responsive to feedback on these new features introduced in 3.0 and proactively fix the biggest issues and known tech debt.

## Plan

[**Issues labeled <kbd>code-nav</kbd>**](https://github.com/sourcegraph/sourcegraph/issues?q=is:issue+is:open+sort:updated-desc+label:code-nav+milestone:3.1)

## Scope

- Issues labeled <kbd>release-blocker</kbd> *must get done*.
- Issues labeled <kbd>priority</kbd> are the next thing to work on *after all release-blockers are done*.
- Issues without <kbd>release-blocker</kbd> or <kbd>priority</kbd> label will get tackled if time.

## Test/review plan

- Code reviewer: assignees of this issue
- Tester: assignees of this issue

**Comment by nicksnyder** [comment]
I am going to close this umbrella issue for 3.1. We will kickoff 3.2 tomorrow.
