### ISSUE TITLE
Add event on 'Create code monitor' button

### ISSUE THREAD

**Issue by ebrodymoore** [sourcegraph/sourcegraph#20713]
There's no event on this 'Create code monitor' button 

<img width="509" alt="Screen Shot 2021-05-06 at 3 02 11 PM" src="https://user-images.githubusercontent.com/25422491/117358666-0a7bdf00-ae7c-11eb-95a1-b99ce178c27b.png">

**Comment by camdencheek** [comment]
Closing as done since [we now have an event](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@0fe9b522098a36b06c6ff6c25ac475373471393d/-/blob/client/web/src/enterprise/code-monitoring/CreateCodeMonitorPage.tsx?L54-54) `CreateCodeMonitorFormSubmitted`
