### ISSUE TITLE
Codecov "Coverage: %" not showing up for some public repo

### ISSUE THREAD

**Issue by takuyahara** [sourcegraph/sourcegraph#2073]
Unlike [Codecov "Coverage: %" not showing up for private repo #1116](https://github.com/sourcegraph/sourcegraph/issues/1116), I see some of the public repo don't show `Coverage %` button nor `Codecov: Show coverage % button` item, like [tuf_store.go](https://github.com/theupdateframework/notary/blob/master/server/storage/tuf_store.go) does but [one of my code](https://github.com/TakuyaHara/test/blob/master/src/Tempo/TempoSelector.tsx) doesn't. Both of them show code lines hilighted though.

In my understanding what should I do to show lines hilighted and `Coverage %` button is same and as lines are hilighted button should be present as well. Is this an issue or do I lack any step?

**Comment by EvanHong1** [comment]
I have a same issue.
Coverage % button is not appearing for public repo.
https://github.com/EvanHong1/evan_coveralls_test/blob/master/app/src/main/java/com/evan/coverallstest/CampaignSettings.java

**Comment by takuyahara** [comment]
My impatience, looking @lguychard's PR I chose to change my username to all lower case to prevent future issue and it solved. Thanks for your investigation and I hope the merged code helps who uses upper case.

**Comment by lguychard** [comment]
Thanks for reporting @takuyahara ! I've just published a new version of the codecov extension including the fix.

**Comment by lguychard** [comment]
@EvanHong1 in your case, on the linked file, the codecov API request returns the following:

`{"meta": {"status": 404}, "error": {"reason": "No reports found for this commit.", "context": null}}`
