### ISSUE TITLE
[deploy-sourcegraph] Use rollout strategy Recreate for stateful singleton deployments.

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#2076]
Any of our deployments which only have one replica and a volume should use the recreate strategy. This will likely involve a migration guide or a move to a new deployment since the rollout strategy field is immutable. In the case of moving to a new deployment, care must be taken so the admin is aware that they need to port modifications from the old deployment to the new one.

See https://kubernetes.io/docs/tasks/run-application/run-single-instance-stateful-application/#updating

**Comment by nicksnyder** [comment]
Can you clarify what are the negative effects of our current state?

My main concern with scoping this for 3.1 is that this cannot be done incrementally (i.e. the whole thing, including documentation, needs to land by Friday). You have more context though about how much effort this is.

**Comment by keegancsmith** [comment]
We have been using this wrong strategy since the creation of Deployments in k8s. There is a possibility of having two pods writing to the same volume leading to corruption. In practice this hasn't happened to us (or that we know of to a customer). The reason this hasn't happened to us is the google cloud disks can only be attached to one node. Given the above this is low-priority to fix, but important debt since one day it could lead to very bad and hard to debug failures.

**Comment by keegancsmith** [comment]
@ggilmore @nicksnyder this change will require a migration guide, but is important to do at some point. Do we have a reasonable release to include these sort of migrations?

**Comment by nicksnyder** [comment]
I don’t think any particular release is going to be better then another. All else equal, sooner rather than later so fewer customers need to deal with this pain. It would be nice if we had the capability to script these upgrades in some way (e.g. Pulumi?) so they are automated (I.e. we don’t rely on users needing to read the change log).

**Comment by keegancsmith** [comment]
We may be able to tackle this with a normal shell script. I believe by just using `kubectl replace --force` we get the behaviour we want. We don't want to use replace everytime, so this needs to be a once off thing to run.

Do we have any plans for introducing automated migrations that admins would know to run when they upgrade?

For now I am going to let this issue stay in the backlog.

**Comment by keegancsmith** [comment]
@sourcegraph/distribution this is some old tech debt which is in your purview. If you are on a kubernetes cluster which supports mounting your postgres volume into multiple pods, we can have data corruption on rollouts. This has never been an issue for us since gke doesn't support that (atleast for the volume types we use).

Fixing it requires customers to migrate. The better fix is likely using a statefulset for postgres. Given the above I'm unsure on when we should fix it. WDYT?

**Comment by beyang** [comment]
> Fixing it requires customers to migrate. The better fix is likely using a statefulset for postgres. Given the above I'm unsure on when we should fix it. WDYT?

I think we should opt using a StatefulSet. However, this is low-priority, since it's unlikely to affect customers (unless they bump the replica count of Postgres to something greater than 1).

**Comment by keegancsmith** [comment]
While we are deploying it is possible to have two instances of postgres running.

https://github.com/sourcegraph/deploy-sourcegraph/blob/v3.11.4/base/pgsql/pgsql.Deployment.yaml#L16-L20
