### ISSUE TITLE
Multiple icon sizes 

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#20771]
Icon use in the application is currently generally specified at:

* 14px icons Inline in buttons and other text 
* 16px icons in the navigation

If we would like to stick to bootstrap size conversions, we could use btn-sm, btn-md, btn-lg, and btn-xl classes. 
LG and XL could be specified at 20px and 32px respectively.

**Comment by AlicjaSuska** [comment]
Sorry for the late response @rrhyne Makes sense to me, I've been using 16px for icons. For extensions action items, I'm using 20px as an exception.

Also, let's specify: those sizes are still bounding boxes' sizes, not the icons themsleves.
