### ISSUE TITLE
Search homepage iterations

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#20773]
Produce several iterations of the search homepage that can be user and A/B tested. 

Figma: 
https://www.figma.com/file/F6xqBsBLJSUx3xY5zBOFg6/Homepage-concept?node-id=0%3A1&viewport=455%2C403%2C0.5302419066429138

**Comment by limitedmage** [comment]
@rrhyne  is this complete with #20773? Or is there still work to be done here?

**Comment by rrhyne** [comment]
This is to track the need to iteration on the homepage. It's partially designed, but will need to bump to next iteration or the next to finalize various designs and build them. I've changed the title to reflect this.

It is dependant on the A/B testing framework.

**Comment by rrhyne** [comment]
Closing in favor of: https://github.com/sourcegraph/sourcegraph/issues/21648
