### ISSUE TITLE
Card redesign: add default icon for extensions not authored by Sourcegraph

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#20785]
### Description

This issue adds a default icon for the extensions not authored by Sourcegraph that don't have the logo/icon provided by the author.

### Specification

So far, the default icon was only used for extensions authored by Sourcegraph. Now, all the extensions should have the default icon.

Icons for Sourcegraph and non-Sourcegraph extensions are slightly different to distinguish them visually:
- [Sourcegraph](https://www.figma.com/file/hciWKNbllHeHWoYcpfGQp2/RFC-305-Next-Up-Extensions-Registry-Marketplace-Concepts-Review?node-id=758%3A5) (with Sourcegraph logo overlay) - the same as the son used currently. 
- [non-Sourcegraph](https://www.figma.com/file/hciWKNbllHeHWoYcpfGQp2/RFC-305-Next-Up-Extensions-Registry-Marketplace-Concepts-Review?node-id=758%3A88) (no logo overlay. The same for light and dark mode: 95A5C6 32%) - SVG for this one is ready to download from Figma from this link

**Comment by tjkandala** [comment]
Implemented in #20822
