### ISSUE TITLE
commit search does not work for "before" and "after"

### ISSUE THREAD

**Issue by sslavian812** [sourcegraph/sourcegraph#2078]
- **2.13.6** 
- **docker image sourcegraph/server:2.13.6** 

#### Steps to reproduce:

1. search for:  before:"june 25 2019"
or
2. search for after:"june 25 2000"

#### Expected behavior:
some search results
#### Actual behavior:
no search results

used example from here:
https://docs.sourcegraph.com/user/search/queries

**Comment by sqs** [comment]
What is the full query you are using? It must include type:diff or type:commit.

**Comment by ijt** [comment]
Closing this for lack of repro information. Feel free to reopen if you can provide it.
