### ISSUE TITLE
Bug: open dropdown color changes to dark theme variant

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#20791]
###Description

After the opening the 'Show all' dropdown on the extension registry page and hovering out, button color changes to the dark mode variant.

[Loom video](https://www.loom.com/share/44bff4d380234fe09be0cff6308cfb48) shows the behavior.

*no problems in the dark mode.

**Comment by AlicjaSuska** [comment]
@tjkandala I've assigned this issue to you as it's connected to the registry redesign.

**Comment by tjkandala** [comment]
![Screenshot from 2021-05-14 09-28-38](https://user-images.githubusercontent.com/37420160/118277434-c9e11e80-b496-11eb-8e9f-3df8f6b81cfe.png)

This doesn't happen for me when the redesign is enabled. Should we still invest in fixing this?

**Comment by muratsu** [comment]
Closing this because it's fixed by the redesign
