### ISSUE TITLE
File tab content is right-aligned

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#20798]
- **Sourcegraph version:** 
- **Platform information:** 

#### Steps to reproduce:

1. Go to https://sourcegraph.com/github.com/sourcegraph/sourcegraph@40c5c3d665983f879465daa32f7d0154db024791/-/blob/enterprise/internal/batches/resolvers/resolver.go#L99-114
2. Look at the files tab:

![screenshot_2021-05-10_10 57 05@2x](https://user-images.githubusercontent.com/1185253/117633720-9b093680-b17e-11eb-9fdb-4d62bf8a2aad.png)

#### Expected behavior:

The scrollbar on the bottom of the files tab either is not there (perfect) or scrolled to the left.

#### Actual behavior:

The content of the tab is horizontally scrollable and it's scrolled to the middle, hiding the beginning of some file names and the end of others.

**Comment by malomarrec** [comment]
@rrhyne is this something that will be tackled by a redesign item?

**Comment by pdubroy** [comment]
@malomarrec I think this is a regression. May be related to https://github.com/sourcegraph/sourcegraph/issues/20743

**Comment by mrnugget** [comment]
Or might be related to https://github.com/sourcegraph/sourcegraph/issues/18684
