### ISSUE TITLE
"new: search contexts" popup should only appear if users have completed the search tour

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#20801]
![image](https://user-images.githubusercontent.com/1741180/117638740-73689d00-b183-11eb-96c2-e3f78bcd5404.png)

**Comment by lguychard** [comment]
@novoselrok is this still relevant with the rework of the Tour?

**Comment by novoselrok** [comment]
> @novoselrok is this still relevant with the rework of the Tour?

Yep, this will actually be fixed with the Tour rework. I'll link the PR.
