### ISSUE TITLE
A/B testing infrastructure MVP

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#20803]
Build an MVP A/B testing infrastructure, likely based on RFC 258. We need this on the Search Product team to enable metrics-driven iteration on search UX, Core Application has a similar need.

- [x] Make final decision on in-house vs. 3rd party:
    - We decided to implement RFC 258 
- [ ] Implement feature flags system:
    - [x] DB and Golang API
    - [x] GraphQL API (https://github.com/sourcegraph/sourcegraph/pull/21749)
    - [ ] Basic site admin UI for feature flags

**Comment by lguychard** [comment]
@camdencheek created this based on what we had in the planning document so that we could represent it in the iteration project board. Feel free to edit as you see fit!

**Comment by lguychard** [comment]
@camdencheek edited the description a bit to represent the state of things!

**Comment by benvenker** [comment]
@lguychard is this still something that's we want to do or have things all migrated to Amplitude/Looker or something else?

**Comment by lguychard** [comment]
@benvenker we do have this infrastructure in place now. The only thing we do not have is an in-app UI for site admins to interact directly with feature flags, but it has not proven necessary so far. Let's close.

**Comment by benvenker** [comment]
got it, thanks
