### ISSUE TITLE
Site admin should not see other user's saved searches

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#20800]
Site admins can currently see any other user's saves searches. This could reveal private repositories in future so we should not allow it.

We should not be able to view
- [x] User saved searches
- [x] Organisation saved searches

**Comment by ryanslade** [comment]
So this already works, but by accident.

When user A browses to user B's saved search page we actually return user A's saved searches.

It doesn't appear to take into account the URL at all but instead looks at the current logged in user's ID.

The question is whether we want to fix the bug and perform the proper checks. It might not be worth the effort right now as saved searches are going to be deprecated soon anyway in favour of code monitoring AFAIK.

**Comment by ryanslade** [comment]
@limitedmage has confirmed that saved searches are *not* being deprecated, only the notifications side of it is. 

This means that we should probably use the username in the URL and if the current user isn't the currently logged in user, show an error.

The reason I'd be hesitant to just leave it as it is now is that at some point someone my fix the issue but not think of the security implications.

I'll own this.

**Comment by ryanslade** [comment]
After looking a bit more into the issue above I think we're safe to leave it as is.

We currently always request the current user's searches, even if we're on an org page for example.

Since we do it that way, there's no way to leak someone elses searches since we don't even have the option to ask for another user's saved searches.

**Comment by limitedmage** [comment]
> We currently always request the current user's searches, even if we're on an org page for example.

This seems broken. Users should be able to see their orgs' saved searches.

> Since we do it that way, there's no way to leak someone elses searches since we don't even have the option to ask for another user's saved searches.

Could site admin still query other users' saved searches via GraphQL console?

**Comment by ryanslade** [comment]
> This seems broken. Users should be able to see their orgs' saved searches. Part of the appeal of saved searches is that you can share them with others.

The API is really basic right now:
https://github.com/sourcegraph/sourcegraph/blob/26029e2d70b30841cb98db3ae35a805886ae8def/cmd/frontend/graphqlbackend/schema.graphql#L1168-L1171

It just implicitly fetches saved searches for the currently logged in user.

It looks like on the org page all repos are requested and then filtered on the frontend if they happen to match the org that's currently being viewed.

I totally agree it's not a great approach but it doesn't appear to be a security risk which is what we're currently focused on addressing.
