### ISSUE TITLE
Reinstate search query syntax usage tracking

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#20813]
From @rvantonder :

> Apparently the code was refactored because pings impacted instance stability. In the process previous metrics were removed, and no one owns this.

**Comment by rvantonder** [comment]
Part of https://github.com/sourcegraph/sourcegraph/issues/20528

Previous backend code removed in this PR: https://github.com/sourcegraph/sourcegraph/pull/11307. Apparently the code was already dead by this point (?)

Relevant refactor, not sure where this fits into the picture yet: https://k8s.sgdev.org/github.com/sourcegraph/sourcegraph/-/commit/69553e0e63e047db36b965b10b1c2aafcebdcf1e?visible=8

**Comment by rvantonder** [comment]
Implemented RFC 384
