### ISSUE TITLE
Site-wide search scopes not appearing in Safari

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#20821]
Repro: visit this page on Safari: https://sourcegraph.com/search?q=repo:sourcegraph/about%24+f:handbook/+type:commit&patternType=regexp

![image](https://user-images.githubusercontent.com/5589410/117692419-db15ec80-b171-11eb-901b-fbba38a73d0a.png)

**Comment by benvenker** [comment]
@dadlerj I could be missing something since I'm still new, but when I compared Chrome to Safari on that link just now they appeared identical to me. Perhaps this was fixed pre-cloud launch?

**Comment by dadlerj** [comment]
Hah, yeah, this is way outdated, it applied to the old UI. Closing now, thanks

**Comment by benvenker** [comment]
great, thanks!
