### ISSUE TITLE
codeintel: implement an autoindexing recognizer for Java packages

### ISSUE THREAD

**Issue by shrouxm** [sourcegraph/sourcegraph#20835]
The recognizer should: recognize LSIF packageInformation vertices which represent Maven repositories, request the repositories to be pulled down into gitserver, and submit an autoindex job to the queue which will index those repos if they haven't already been indexed.

**Comment by shrouxm** [comment]
cc @efritz links here

**Comment by efritz** [comment]
1. Add a [Java recognizer](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/lib/codeintel/autoindex/inference/recognizers.go#L28) to create index jobs from a repository (not necessarily Java).

Use Go/TypeScript as a sample of how to do this. Basically you need to fill out the functions:

- `Patterns` returns regex patterns matching files interesting to the other two functions. You may want to just look for things like a gradle conf in the root and other simple indicators to start out.
- `CanIndexRepo` takes the paths in the repo matching the patterns above and returns true if there is likely an index job inferable from the file contents. Paths here may include more than the given patterns (they may also match patterns from other recognizers).
- `InferIndexJobs` takes the paths in the repo matching the patterns above and returns a set of index jobs that are likely to succeed on a particular commit of the repository.

2. Update [QueueIndexesForPackage](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/codeintel/autoindex/enqueuer/enqueuer.go#L81:25) to recognize Java repositories from maven monikers. Right now this function special-cases Go, but should be fairly easy to extract into a function that can be called over multiple moniker schemes (try to parse Go, try to parse TypeScript, try to parse Java, etc).

**Comment by olafurpg** [comment]
Here's a PR that got started with this change, but it never got merged because it was incomplete
https://github.com/sourcegraph/sourcegraph/pull/20448
