### ISSUE TITLE
follow up on enabling docker multi-stage builds in CI

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#2083]
See https://github.com/sourcegraph/infrastructure/pull/1095#issue-249001644

**Comment by ggilmore** [comment]
Perhaps https://cloud.google.com/blog/products/gcp/introducing-kaniko-build-container-images-in-kubernetes-and-google-container-builder-even-without-root-access is an option

**Comment by ggilmore** [comment]
@tsenart 

Re: https://github.com/sourcegraph/infrastructure/pull/1095#issuecomment-459124027

I upgraded our nodes to the latest available GKE version, but they're still using docker `17.03`. I assume they haven't changed the COS version for GKE yet.

**Comment by keegancsmith** [comment]
This solution failed. It seems wondering if the blessed GKE path is a recipe for disaster. The kubelet fails to start. I am rolling back.

**Comment by keegancsmith** [comment]
We now use docker-in-docker to build images, instead of the node's docker. There is a PR out which adds the resources to our cluster. But it has been deployed so I am regarding this issue as fixed.
