### ISSUE TITLE
Misaligned bottom border width in panel tabs

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#20857]
I noticed this at https://sourcegraph.com/github.com/sourcegraph/sourcegraph@8ef8adbfcdf956504867cf46415a9205077c1e59/-/blob/client/shared/src/util/hashCode.test.ts#L23:20&tab=references

![image](https://user-images.githubusercontent.com/10532611/117803270-bba4bf80-b256-11eb-85a3-f4a9894ad0f1.png)

See how
1. the grey border width does not extend (have the same width) with the border right of the tabs.
2. there is a small grey border shining through where the blue (active) border is, i.e. the widths there don't match.

**Comment by 5h1rU** [comment]
Sure, I'll take a look
