### ISSUE TITLE
Add step-wise caching to src-cli

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#20850]
This is a sub-ticket of https://github.com/sourcegraph/sourcegraph/issues/19476.

The idea is described in https://hungry-yonath-3c673a.netlify.app/, but the short version:

1. Instead of caching only the result of executing _all_ steps in a repository, we cache the results per step
2. We invalidate the cache for a step only if the step or one of the previous steps definitions changed

**Comment by chrispine** [comment]
This was moved to Done, but but closed, so I'm closing it.
