### ISSUE TITLE
Design refresh: extensions action items bar

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#20853]
Design for vertical action items bar.

- [Sticker sheet](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Design-Refresh-Systemization-source-of-truth?node-id=2528%3A107)
- [Mockups](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Design-Refresh-Systemization-source-of-truth?node-id=3173%3A0)

**Comment by AlicjaSuska** [comment]
@quinnkeast please, review once @tjkandala is ready. Thank you!

**Comment by rrhyne** [comment]
@tjkandala can you update us when you start this?

**Comment by tjkandala** [comment]
@rrhyne @quinnkeast This is ready for review at #21004 (I also merged #21299 into this branch, which updated the status bar)
