### ISSUE TITLE
Override search keyword default values

### ISSUE THREAD

**Issue by KattMingMing** [sourcegraph/sourcegraph#2085]
**Request**
Allow users to set preferred default values for search keywords.

- [ ] Add `search.keywordDefaults` to user configuration.
`search.keywordDefaults` lets users override the default keyword values such as `case:no` to `case:smartcase`.

- [ ] On search append the query with overwritten operators if the keyword was not present in the query and exists in `search.keywordDefaults`.

All keywords can be found here: https://docs.sourcegraph.com/user/search/queries

**Example**

Set default "case" keyword value to "smartcase" instead of "no".

```
// user settings
...
search.keywordDefaults: {
    "case": "smartcase",
}
...
```

**Example queries with overwritten keyword values**
1. Search input field: `repo:github.com/gorilla/mux mux`
On search: `repo:github.com/gorilla/mux mux case:smartcase`

2. Search input field: `repo:github.com/gorilla/mux case:no mux`
On search: `repo:github.com/gorilla/mux case:no mux`

Related issues: https://github.com/sourcegraph/sourcegraph/issues/2084 and https://github.com/sourcegraph/sourcegraph/issues/1817

/cc @sourcegraph/search-platform

**Comment by keegancsmith** [comment]
pretty cool idea. Only issue is this makes it hard to share search URLs and complicates our dynamic search filters. Could we not instead by default prepend / append keywords?

**Comment by sqs** [comment]
Deferring because I think we can enable smartcase by default without implementing this issue and the other use cases are not as important, plus I am worried about it meaning that search queries mean different things for different users (unexpectedly).

**Comment by dadlerj** [comment]
Just got a request from https://app.hubspot.com/contacts/2762526/company/2211073777 for this (or something like https://github.com/sourcegraph/sourcegraph/issues/1817):

>- Is it possible to exclude certain repostiroy paths (path inside a repository) from the search index? For example in some repositories our dependencies are vendored and it would be nice to exclude this easily from the search results by default. We could create global search scopes but users would need to select these everytime they do a search

**Comment by dadlerj** [comment]
Tagging @christinaforney for potential prioritization and @attfarhan as (potential?) owner

Not urgent, but something I've heard several times before in several different contexts (see https://github.com/sourcegraph/sourcegraph/issues/1817 for another example)
