### ISSUE TITLE
Redesign: floating bottom extension static info bar

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#20854]
- [Sticker sheet](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Design-Refresh-Systemization-source-of-truth?node-id=2537%3A73)
- [Mockups](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Design-Refresh-Systemization-source-of-truth?node-id=825%3A127121)
- [with code intel panel open](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Design-Refresh-Systemization-source-of-truth?node-id=3173%3A4620)

Details:
- bottom bar should be floating
- it should resize to content
- it should keep current scrolling behavior

Important: add extra 56px bottom padding to the code container to prevent the floating bar from covering the last lines of code.

**Comment by AlicjaSuska** [comment]
@quinnkeast please, review once @tjkandala is ready. Thank you!

**Comment by rrhyne** [comment]
@AlicjaSuska moving this to closed as it looks like the PR closed this.
