### ISSUE TITLE
Hovering over repo name in search results should display tooltip with full repo name

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#20874]
Nice to have but not required for the redesign. Unfortunately requires a lot of refactoring on the backend, so it might have to wait until graphql search is removed.

**Comment by rrhyne** [comment]
I think this can be closed?

**Comment by limitedmage** [comment]
> I think this can be closed?

Not really. This is for the search results list, for repos that don't show the icon. Unfortunately it's not straight forward and requires backend changes to implement.

**Comment by camdencheek** [comment]
Closing this as done since we no longer render the repo name with markdown on the backend
