### ISSUE TITLE
file: search operator could be better optimized to reduce gitserver IO load

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#2089]
Steps to reproduce:

1. Be on a Sourcegraph instance with a large number of repositories.
2. Ensure the Sourcegraph instance has a high `maxReposToSearch` value (i.e. any large Sourcegraph instance).
3. In the search field, type just `file:a`, then quickly in succession hit backspace to erase `a` and type `b`, then `c`, and so on.
4. You will notice the search suggestions rapidly getting slower. Press enter after a while (e.g. after reaching `file:h` in the alphabet).
5. Enter a search query like `file:h error` which will turn up results. The results will quickly appear, but the code inside of them will take a LONG time to load:

![image](https://user-images.githubusercontent.com/3173176/52083484-ca22ad80-255c-11e9-9f78-8e707a7ebe65.png)

Gitserver logs will indicate:

```
WARN Long exec request [...]
```

**Comment by keegancsmith** [comment]
This would be an optimization in searcher. Right now when you do the file name only request we still request a full `git archive` in searcher. Instead it is likely worth making searcher smarter and have it issue (and cache) a `git ls-tree` request if the archive is not present.

**Comment by keegancsmith** [comment]
Oh I assumed we spoke to searcher since it supports just file queries. By cache do you mean pre-emptive or just caching the output of ls-tree.

Not searcher would also cause high io on git server, due to git archive

**Comment by slimsag** [comment]
Me and Keegan chatted via Slack, I have some additional investigation to do here since ls-tree output appears to have a cache already.

**Comment by slimsag** [comment]
Update: I've done some further investigation into the cause of this issue. There are in fact four distinct problematic places in our code which all together contribute significantly to the slowness. Primarily this leads to:

1. gitserver: A high number of `git` commands being executed, which sometimes affects CPU load.
2. gitserver: The `git` commands being executed consume more disk IO than is optimal.
3. repo-updater: A high request rate to this service puts pressure on it, backlogging some requests and putting pressure on Redis as well.

_Only once **all four** of the following issues are addressed fully does the issue in the description no longer occur_ (i.e. resolving 3 of 4 does not get the performance within reasonable levels on a dev machine with ~1200 repositories).

1. `searchTreeForRepo` [calls into the graphql `(*repositoryResolver).Commit` method](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@5ad5349157106f7b6126354799f359e07a268290/-/blob/cmd/frontend/graphqlbackend/search.go#L674) which [calls `backend.Repos.ResolveRev`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@5ad5349157106f7b6126354799f359e07a268290/-/blob/cmd/frontend/graphqlbackend/repository.go#L114) which [implicitly uses a non-cached `GitRepo`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@5ad5349157106f7b6126354799f359e07a268290/-/blob/cmd/frontend/backend/repos_vcs.go#L162), thus almost every search leads us to asking repo-updater to ensure the URI of every repository found by the search is up to date, which is _S.L.O.W._. It should be using a `CachedGitRepo` instead, but the abstractions here make that hard.
2. Identical to #1, except with [the call to `backend.Repos.GitCommit`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@5ad5349157106f7b6126354799f359e07a268290/-/blob/cmd/frontend/graphqlbackend/repository.go#L122).
3. Calling [`backend.Repos.GitCommit`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@5ad5349157106f7b6126354799f359e07a268290/-/blob/cmd/frontend/graphqlbackend/repository.go#L122) for every repository just to ultimately discard the result is too slow. Ideally, `(*repositoryResolver).Commit` would make this call lazily only if one of the fields this value is used for was requested.
4. The cache sitting in front of `git ls-tree` is [too small](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/pkg/vcs/git/tree.go#L125), does not persist across restarts (should be stored in Redis), and uses [a non-aggressive heuristic](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/pkg/vcs/git/tree.go#L152-154) which leads to us wasting a ton of time spawning thousands of short-lived `git ls-tree` commands when we could just quickly consult Redis for the result. Ideally we would also pre-emptively build this cache when indexing repositories initially, instead of waiting on the first search that touches the repository.

I currently estimate this will take a few days to resolve, as this essentially boils down to "we should be indexing file: search" which is tough to get right due to the number of abstraction layers in place here.

**Comment by keegancsmith** [comment]
Should we not just get rid of this code, and rely on searcher which is much smarter about all of this? The only downside is to answer a `file:` request it dumps a full repo. However, once it has done that it should be fast. TBH I'm surprised this specialized file listing search exists.

**Comment by slimsag** [comment]
@keegancsmith Can you elaborate a bit more on how we would rely on searcher for this? Do you mean to re-implement `file:` searches inside of searcher? Or do you have something else in mind?

**Comment by keegancsmith** [comment]
Searcher already supports `file:` only searches.
