### ISSUE TITLE
cloud: manage repositories page no longer includes repos from orgs

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#20904]
On sourcegraph.com I setup repositories. I selected via a checkbox a repository from my github, as well as repos from the sourcegraph org (which I am part of). I then additionally added a few more repos via the manual input text box. I just went back to the page to add some more repos from the sourcegraph org, but the sourcegraph org is no longer included in the selected list. However, it is still part of my user search context. Screenshots for context:

The list of repos in my personal search context:
![image](https://user-images.githubusercontent.com/187831/117994350-c3409300-b340-11eb-8639-84444942b580.png)

The configuration I have synced. Notice the 1 repository selected and that sourcegraph repos are not mentioned anywhere anymore. I only have keegancsmith repos (and one gchaincl repo which is a user, not an org):
![image](https://user-images.githubusercontent.com/187831/117994640-fa16a900-b340-11eb-857d-b62774c850bd.png)

![image](https://user-images.githubusercontent.com/187831/117994797-14508700-b341-11eb-9476-c5d5134e82e1.png)

**Comment by ryanslade** [comment]
I know it's probably not the answer you want, but removing your GitHub connection and adding it again should fix this.

We've been making changes around the scopes we request and I think your current OAuth token doesn't have org access. 

I've confirmed this fixed the same issue with my token on .com

**Comment by keegancsmith** [comment]
I think this is fine as a workaround, assuming not too many people outside of the sourcegraph org are affected. Will close out, re-open if you think you need to do a better fix :)
