### ISSUE TITLE
Refresh: extensions registry & extension details page (QA)

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#20903]
- Design QA after applying global styles to the extensions registry and extension details page
- Create issues for improvements

**Comment by AlicjaSuska** [comment]
Reviewed refresh redesign with the refresh toggle on (as of May 19)

**Comment by rrhyne** [comment]
@AlicjaSuska What needs to be done here? Are we expecting it to ship with the redesign?

**Comment by AlicjaSuska** [comment]
Yes, we did the QA with @tjkandala yesterday/today. It's ready to go, no bugs were found.
