### ISSUE TITLE
Unable to root cause repos that are failing to sync on dogfood

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#20927]
- **Sourcegraph version:**  "Sourcegraph.com" (version: `95869_2021-05-12_379977d`) 
- **Platform information:** Chrome

#### Steps to reproduce:

1. Unknown, possibly add a bad code host
2. Go to https://k8s.sgdev.org/site-admin, click on the cloud icon on upper right hand corner. 
See this error `3 repositories could not be synced`

#### Expected behavior:
I can see what repos are failing to sync and what code-host to inspect for issues

#### Actual behavior:
<img width="438" alt="Screen Shot 2021-05-12 at 4 45 35 PM" src="https://user-images.githubusercontent.com/31839142/118057791-81641c80-b341-11eb-9210-6607b5f7953e.png">

I did not see any failing sync jobs in the repo-updater debug UI

**Comment by pdubroy** [comment]
@daxmc99 Is it possible to make me a site-admin so I can reproduce the problem? I just see the following:

![CleanShot 2021-05-21 at 11 56 07](https://user-images.githubusercontent.com/17293/119119532-90c32400-ba2b-11eb-9ed2-e70fe6f174a8.png)

**Comment by pdubroy** [comment]
Actually, this message appears to be coming from the backend: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@7859892520dd3e1ce59bd980dc0236d245b2b40c/-/blob/internal/repos/status_messages_test.go?subtree=true#L196, so I don't think this is a frontend issue.

@ryanslade, can you help?

**Comment by ryanslade** [comment]
We'll need access to the database which I don't think I have. 

We need to run the following:

```sql
select * from gitserver_repos where last_error is not null;
```

@dax Can you run this?

**Comment by eseliger** [comment]
this data is exposed in the ui now.
