### ISSUE TITLE
Batch changes container / layouts

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#20935]
Batch changes pages needs updating to the new container layout system. This involves changing the following pages:

Index - A white content container will wrap all batch changes. ([See layouts](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Design-Refresh-Systemization-source-of-truth?node-id=2588%3A1))
Getting started - the two main cards will adopt a white bg ([see code monitors getting started design](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Design-Refresh-Systemization-source-of-truth?node-id=2584%3A36266))
Batch change page - a white content container will wrap the changesets. KPIs and alerts will appear outside of the container on the page background ([See layouts](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Design-Refresh-Systemization-source-of-truth?node-id=2588%3A1))

**Comment by eseliger** [comment]
This is done.
