### ISSUE TITLE
Update Monaco theme colors to match redesign color palette

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#20946]
Our [root color palette](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Design-Refresh-Systemization-source-of-truth?node-id=908%3A7961) is updated under the redesign theme. We need to sync it with [the colors](https://github.com/sourcegraph/sourcegraph/blob/main/client/web/src/components/MonacoEditor.tsx#L138) used by the Monaco editor.

Known updates:

- [ ] `--search-keyword-color`
  - light theme: from `--oc-grape-7: #ae3ec` to `--purple: #a305e1'`
  - dark theme: from `--oc-grape-4: #da77f2` to `--pink: #d68cf3'`

**Comment by fkling** [comment]
You linked to [the Monaco colors](https://github.com/sourcegraph/sourcegraph/blob/main/client/web/src/components/MonacoEditor.tsx#L138), but it doesn't look like any of them are specific to *search*.

Should all references to `#ae3ec` and `#da77f2` in that file be replaced with the new colors? That would include things like `keyword`, `openingParen`, `closingParen`, ...

Or is this the wrong file to look at?

**Comment by valerybugakov** [comment]
The `--search-keyword-color` CSS variable is just one of the known updates. This issue is not specific to the _search_ functionality. 

We need to go through the Monaco theme and ensure that it uses new colors if they were updated during the redesign. Colors should be added to variants of the redesign Monaco theme: `SOURCEGRAPH_DARK_REDESIGN` and `SOURCEGRAPH_LIGHT_REDESIGN`. Previous color values should be in place until the redesign release. @limitedmage, please correct me if I'm wrong. 

@fkling let me know if it's still confusing 🙂

**Comment by limitedmage** [comment]
What @valerybugakov  says is correct. We need to go through both `colors.scss` and `colors-redesign.scss`, figure out what colors were changed there that are also used in the Monaco themes, and add those colors to the Monaco redesign variants. Kind of a chore and unfortunate that Monaco does not support CSS variables in themes :(

**Comment by fkling** [comment]
Got it, thank you @valerybugakov , @limitedmage !

**Comment by fkling** [comment]
I assume that colors used by Monaco but not used in `colors.scss` should just stay as they are?

**Comment by valerybugakov** [comment]
@fkling, I think so too 👍
