### ISSUE TITLE
management-console doesn't pick up settings from dev-private

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#2095]
- **Sourcegraph version:** https://github.com/sourcegraph/sourcegraph/commit/36dbe5794521f612ea77ffb33b32f0ab53febb69
- **Platform information:**

```
Hardware Overview:
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro13,2
  Processor Name:	Intel Core i7
  Processor Speed:	3.3 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	4 MB
  Memory:	16 GB
```

#### Steps to reproduce:

1. Clone https://github.com/sourcegraph/sourcegraph/ to `$GOPATH/src/github.com/sourcegraph/sourcegraph`
1. Clone https://github.com/sourcegraph/dev-private/ to `$GOPATH/src/github.com/sourcegraph/dev-private`
1. Visit management console at `https://localhost:2633`

#### Expected behavior:

Management console has settings copied over from https://github.com/sourcegraph/dev-private/blob/master/enterprise/dev/critical-config.json

#### Actual behavior:

The management console only has the default config:

```js
// The Sourcegraph critical configuration for development servers.
{
  "externalURL": "http://localhost:3080",
  "update.channel": "release",
  "auth.providers": [
    {
      "type": "builtin",
      "allowSignup": true
    }
  ]
}
```

I can still see that the `frontend` binary is picking up `lightstep` settings (from `dev-private`?) due to this log line:

```
13:59:02               frontend | INFO Distributed tracing enabled, tracer: Lightstep
```

But the `lighstepProject` field in my traces are incorrect (see https://sourcegraph.slack.com/archives/C07KZF47K/p1548971461561900?thread_ts=1548969611.558900&cid=C07KZF47K). 

Maybe there is a race condition happening somewhere?

---

Also (related), the management console seems to throw away any edits I make to the critical configuration between restarts (all I see is the default config).

**Comment by sqs** [comment]
Moving to backlog because @ggilmore 	has not found this important enough to reply in 25 days, and this doesn't affect customers, so it does not seem high priority.
