### ISSUE TITLE
`patterntype:structural` should not be valid for code monitors

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#20970]
One proposed way to do this previously:

> (Honestly I think the best answer for this is to add one more validation check: Contains patternType:literal or patternType:regexp. This way we avoid issues with users changing their defaultPatternType and also with patternType:structural not being supported in type:diff/type:commit searches. I’ve told Quinn and hopefully he agrees)

Via https://sourcegraph.slack.com/archives/D018MSGBH9B/p1617059981012400

Affects customer trial https://sourcegraph.slack.com/archives/C01NDS6BVBQ/p1619805792267300

@limitedmage please reassign as appropriate, I'm just assigning you because you're closest to code.

**Comment by quinnkeast** [comment]
> @sourcegraph/design or @quinnkeast Can you help out with how this should look? Would adding another item to the checklist be OK, and if so, what should the copy for that be?

Yes, I think so. Probably best as the first item in the list. Copy can be:

>Contains a patternType:literal or patternType:regexp filter

What would you suggest for helper tooltip copy?

**Comment by limitedmage** [comment]
> Contains a patternType:literal or patternType:regexp filter

Actually I don't think this is accurate, because users don't *need* to add a `patternType` filter. If they don't add one, we will automatically add `patternType:literal` behind the scenes.

**Comment by fkling** [comment]
Thank you all, this was exactly what I had problems with figuring out. Using the same wording as the current ones didn't seem to work for this case because we have default behavior. I like 

> Is patternType:literal or patternType:regexp
