### ISSUE TITLE
Allow authenticated user get `user_external_accounts.accountData` for GitHub and GitLab

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#20978]
This is needed for our web app to display useful information in the security page under user settings.

https://github.com/sourcegraph/sourcegraph/pull/20288#issuecomment-840053990

**Comment by ryanslade** [comment]
Do we want to disallow site admins?

**Comment by unknwon** [comment]
@ryanslade Technically I would say no. As for Cloud, site admins see what's already public by hitting GitLab.com and GitHub.com's APIs.

@artemruts and I came up this issue was because we fear some on-prem Sourcegraph SSO setups may contain unexpected sensitive information to users (as was stated in the code comment).

**Comment by ryanslade** [comment]
@unknwon What if a user has a private token in `AccountData`, we don't want site admins to be able to read that

**Comment by unknwon** [comment]
> @unknwon What if a user has a private token in `AccountData`, we don't want site admins to be able to read that

That would be stored in `AuthData` not `AccountData` (by design).
