### ISSUE TITLE
Validate site admins cannot view changes to private repos on dotcom

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#20986]
This will need to be validated before we enable Batch Changes on the dotcom instance. Site admins should not be able to view private code there at all. I think it should be working already because we just rely on authz filters in the DB layer, but we should check regardless. Maybe there are some exceptions in the app logic layer(?)

**Comment by malomarrec** [comment]
Sounds like this could be closed now that we don't have plans on .com?

**Comment by eseliger** [comment]
yeah.
