### ISSUE TITLE
Confirm behaviour of ScopeSiteAdminSudo on Cloud

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#20991]
This relates to scope allowed on access tokens.

We should confirm how to handle this on our Cloud instance. 

We should most likely not allow it as it would allow a site admin to create a token that allows them to impersonate any user which in turn gives them access to any private code added by that user.

**Comment by unknwon** [comment]
I'm taking this on assuming no one has started working on this (no assignee).

**Comment by unknwon** [comment]
Sudo tokens would allow me as a site admin to impersonate any user at the API-level, including access to private resources (if any).

Therefore, before we have a RBAC, **we should disable creating sudo tokens and delete all existing sudo tokens on dotcom for site admins**.

**Comment by ryanslade** [comment]
@unknwon Should we delete the token anyway just for completeness?

**Comment by unknwon** [comment]
Code-intel is actually relying on the sudo scope for uploading LSIF indexes to dotcom... see discussions here: https://sourcegraph.slack.com/archives/CHXHX7XAS/p1621871416113500

Reopen since there maybe some additional work to do.
