### ISSUE TITLE
repo-updater: Integrate OtherReposSyncer with Scheduler.updateSource

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#2100]
Currently, OTHER synced repos are passed to the scheduler with [UpdateOnce](https://github.com/sourcegraph/sourcegraph/blob/42ea41244572f895abb48cd5011ca1eff3916b07/cmd/repo-updater/main.go#L118) which bypasses the scheduler entirely.

**Comment by keegancsmith** [comment]
I believe @tsenart has fixed this.
