### ISSUE TITLE
Unable to login to sourcegraph with OIDC

### ISSUE THREAD

**Issue by techknowlogick** [sourcegraph/sourcegraph#21003]
- **Sourcegraph version:** 3.27.5 - installed via one-line docker run command to test sourcegraph
- **Platform information:** Docker version 20.10.6 (Host: macOS 10.15 Catalina)

#### Steps to reproduce:

1. Set OIDC provider using following config:
```
{
      "type": "openidconnect",
      "displayName": "Provider Name",
      "issuer": "https://example.com/",
      "clientID": "ID_GOES_HERE",
      "clientSecret": "SECRET_GOES_HERE"
    }
```
and the well-known endpoint from oidc provider returns:
```
{
    "issuer": "https://example.com/",
    "authorization_endpoint": "https://example.com/login/oauth/authorize",
    "token_endpoint": "https://example.com/login/oauth/access_token",
    "response_types_supported": [
        "code",
        "id_token"
    ]
}
```
2. Open sourcegraph install, and attempt to login via OIDC provider.

Note: I am able to use this OIDC provider to login into non-sourcegraph applications.

#### Expected behavior:
Successful user login via oidc

#### Actual behavior:
Browser returns error: `Authentication failed. Try signing in again. The error was: OpenID Connect ID token could not be verified.`
Docker logs show: `lvl=eror msg="OpenID Connect auth failed: the ID token verification failed." error="oidc: id token signed with unsupported algorithm, expected [\"RS256\"] got \"HS256\""`

**Comment by abeatrix** [comment]
Hi @techknowlogick ! 

> error="oidc: id token signed with unsupported algorithm, expected [\"RS256\"] got \"HS256\""

Is the setting for your JsonWebToken in OAuth sets to `HS256` (which is the default for clients)? If yes, the solution for this would be changing it to `RS256`. 
See the auth0 docs for more related information: https://auth0.com/blog/navigating-rs256-and-jwks/
I hope this helps!

**Comment by techknowlogick** [comment]
Thanks for response @abeatrix, sadly the ODIC provider I use only supports`HS256`.

**Comment by abeatrix** [comment]
@techknowlogick Sorry to hear that, I will let the team knows and see if this is something we can support in the future.

For now, here is [a list of auth provider](https://docs.sourcegraph.com/admin/auth#openid-connect) that Sourcegraph currently supports:
- Google Workspace (Google accounts)
- Okta
- Ping Identity
- Auth0
- Salesforce Identity
- Microsoft Azure Active Directory
- Google Identity Platform

**Comment by abeatrix** [comment]
@techknowlogick It looks like this will require code change to be supported unfortunately 😞 
However, please feel free to create a feature request for this and provide us with more context that would help us to prioritize the requests. Thanks!

**Comment by techknowlogick** [comment]
Thanks for letting me know :)
