### ISSUE TITLE
Creation UI URL hierarchy

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#21012]
Currently the code insights creation UI has the following hierarchy:

- `/insights`
- `/insights/create-intro`
- `/insights/create-search-insight`
- `/insights/create-lang-stats-insight`

Note how there is redundancy in multiple ways, e.g. `insight` is repeated and `create-` is a prefix for multiple adjacent URLs.

I think a hierarchy like this would make more sense:

- `/insights`
- `/insights/create` (intro)
- `/insights/create/search` (i.e. `/insights/create/:type`)
- `/insights/create/lang-stats` (dito)

**Comment by Joelkw** [comment]
I agree! Hadn't gotten to this until now and just went looking for something like this. Thanks for suggesting.

**Comment by vovakulikov** [comment]
Thanks for suggesting. I agree existing routes were not chosen in the best way
