### ISSUE TITLE
Remove 'show all extensions' button from the registry

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#21011]
### Description

This issue removed the 'show all extensions' button from the registry.

### Reasoning
@muratsu raised an interesting concern: do we need the 'show more extensions' button at all? 

What it does: it shows the language extensions
Why it's there: we've hidden language extensions as we don't want users to turn them on and off. Also those are not really the 'extensions' in traditional users' understanding. They are more of 'code intel must-haves'

Decision: Remove the button
Why: It's taking up space and causes [problems in the interface](https://github.com/sourcegraph/sourcegraph/pull/20822#issuecomment-842013172) when there is a button for 'show all category' in the category above. 'Languages' is accessible as a category in the left menu, if users need it.
Please note: we should show 'Other' as the last category in the registry. Only 'Languages' should be hidden.

@Joelkw FYI since you're on vacation

**Comment by Joelkw** [comment]
@AlicjaSuska thanks for the FYI! I am fine hiding them since everything should be otherwise in a category (including other) and as long as the sidebar link to it preserves the ability to link to/show all the language extensions for CE and docs use cases.
