### ISSUE TITLE
Remove SetRepositoryEnabled

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#21013]
As seen here:
https://github.com/sourcegraph/sourcegraph/blob/f5823d7018bebddd72a6d97dab6276500dfe1b0d/cmd/frontend/graphqlbackend/repositories.go#L276-L278

It has been deprecated for a while and we believe no customers are using it anymore and is therefore safe to remove.

**Comment by slimsag** [comment]
We're good to remove this, details here: https://sourcegraph.slack.com/archives/CHPC7UX16/p1621274748368000?thread_ts=1621245199.320000&cid=CHPC7UX16
