### ISSUE TITLE
Indexed search doesn't honor multiline RE2 syntax with `(?s:regex)` modifier.

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#21034]
I believe this is something in the backend/Zoekt flags causing this to happen. We recognize the modifier syntax on the unindexed code path. 

- no results bug `index:only` 

[`repo:^github\.com/sourcegraph/sourcegraph$ file:^client/branded/src/components/Toggle\.story\.tsx (?s:example.*class) index:only`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:%5Eclient/branded/src/components/Toggle%5C.story%5C.tsx+%28%3Fs:example.*class%29+index:only&patternType=regexp)

- identical query, multiline result with `index:no` 

[`repo:^github\.com/sourcegraph/sourcegraph$ file:^client/branded/src/components/Toggle\.story\.tsx (?s:example.*class) index:no`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:%5Eclient/branded/src/components/Toggle%5C.story%5C.tsx+%28%3Fs:example.*class%29+index:no&patternType=regexp)

Related to https://github.com/sourcegraph/sourcegraph/issues/11364. Run into by customer https://sourcegraph.slack.com/archives/C01MX8ATDNY/p1621284415048600

**Comment by rvantonder** [comment]
Why this matters: we support multiline matching with a simple workaround like `.|\n`. But that's not quite equivalent to to `(?s:.)`. Turns out, that `(?s:.)` will also take care of matching `\r\n`, but the workaround would not (this could trip users up, and we have one data point where it has). The workaround would need to be modified to `.|\n|\r\n`.

Open question:

(1) Do we support this regex modifier on indexed search (I believe Zoekt does understand it). 

OR

(2) Do we keep our current backend flags and just say we don't support this?

My sense is, if it's easy, we should go with (1), because we "already" support it on the unindexed code path. But, I suspect that it might be tricky to validate (1) using, say, the Go regex package (maybe there's an easy way to configure which regex flags to check in the syntax?).

**Comment by keegancsmith** [comment]
@jjeffwarner this issue and https://github.com/sourcegraph/sourcegraph/issues/33656 are related. They may be appropriate onboarding tasks for the zoekt codebase. I wouldn't say good first issue, but good early issue.

**Comment by stefanhengl** [comment]
This seems to have been fixed. I tried the example in the description and both return the same results. Please reopen if there is still an issue and don't forget to add examples to the ticket.
