### ISSUE TITLE
Don't use light theme colors in dark mode alerts.

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#21041]
In [the alerts redesign](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Design-Refresh-Systemization-source-of-truth?node-id=1398%3A32330), we use light mode colors in the dark mode variants. 

In the implementation, when the dark theme is enabled, we don't have access to the light theme colors. Values are switched to alternative dark values, and the intended behavior is to use these alternative values.

To avoid hacky solutions in the implementation, we need to _use only dark theme colors for dark mode variants_.

**Comment by rrhyne** [comment]
Speaking with Valery, we will use 01/Dark colors in the alert icons to solve this issue.

**Comment by pdubroy** [comment]
Closed as it appears this has been approved by @rrhyne. Rob, please re-open if we're wrong about that.
