### ISSUE TITLE
Code monitoring: show "new" tooltip the first time a user runs a search that can be monitored

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#21049]
From @quinnkeast (see #18281): we should show a "new" tooltip under the "monitor" button on search results the first time a user runs a search that can be monitored.

![image](https://user-images.githubusercontent.com/1741180/118659429-97645800-b7ed-11eb-961f-c8528887f9c9.png)

[Full design documentation in Figma](https://www.figma.com/file/Krh7HoQi0GFxtO2k399ZQ6/RFC-227-%E2%80%93-Code-monitoring-actions-and-notifications?node-id=3921%3A37186)

**Comment by malomarrec** [comment]
Right now, it sounds like approximately 2% of relevant sessions have type:commit or type:diff. This sounds like a significant opportunity, tagging as retention/p2.

**Comment by malomarrec** [comment]
I this lands, we'll A/B test under the `w0-signup-optimisation` flag
