### ISSUE TITLE
Diff highlighting panics if base file ends with an empty new line

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#21054]
I added a test case reproducing that in https://github.com/sourcegraph/sourcegraph/pull/21053. When the base file diff ends with an empty new line ` `(just a space, to indicate no change in this line) the highlighting panics. I think that is because the highlightedBase doesn't contain the final new line, which is required for what's shown in the test case in the PR.

**Comment by camdencheek** [comment]
Looks like we're paying for the complexity described in https://github.com/sourcegraph/sourcegraph/issues/20704. I'll get a fix out today, and try to prioritize simplifying that logic.
