### ISSUE TITLE
Refresh: file path / breadcrumbs

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#21051]
Lockup file path design:
<img width="853" alt="Screenshot 2021-05-18 at 15 38 08" src="https://user-images.githubusercontent.com/20326070/118661096-1b6b0f80-b7ef-11eb-8dbc-210f496852c7.png">

**Comment by AlicjaSuska** [comment]
Current component: https://5f0f381c0e50750022dc6bf7-tntipscpgc.chromatic.com/?path=/story/web-breadcrumbs--example

**Comment by umpox** [comment]
FYI: Have updated this design from this issue: https://github.com/sourcegraph/sourcegraph/issues/21418.

I am closing that one and leaving this one in 'Implementation review' for any further changes
