### ISSUE TITLE
Temp version context ui

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#21066]
![image](https://user-images.githubusercontent.com/539268/118692822-4fc6d780-b7bf-11eb-8333-3f3b5706929c.png)

Figma
https://www.figma.com/file/QQYKGTl5MufkNIu9D9mOgN/temp-version-context-ui?node-id=1%3A812&viewport=351%2C542%2C0.25

**Comment by limitedmage** [comment]
Thanks Rob, this looks great! Do you have a design for this in the bigger size (all inline)?

**Comment by rrhyne** [comment]
I added a sm + size and changed the background color of the button in the
small size for continuity.

**Comment by limitedmage** [comment]
Closing this as completed design. Dev implementation will be done in #20685
