### ISSUE TITLE
Double-clicking extensions is not a great experience

### ISSUE THREAD

**Issue by muratsu** [sourcegraph/sourcegraph#21062]
About standalone web server credentials: we have k8s.sgdev.org admin user in 1Password that can be used to log in to the web server.

I was able to reproduce this behavior locally with our frontend server. The issue is visible if you set network throttling to "Slow 3G":
![image](https://user-images.githubusercontent.com/1308560/118685872-5140d180-b7b8-11eb-8c39-b7d885f16e1b.png)

This issue is noticeable with the standalone web server because it has native latency to reach the deployed API instance. To reproduce it:

1. Enable network throttling.
2. Enable and disable the extension.
3. See how changes will be reflected in the UI

https://user-images.githubusercontent.com/3846380/118614662-9550c800-b7f2-11eb-8b3b-c488e8938916.gif

**Comment by tjkandala** [comment]
We cannot reproduce this issue after #21197 (the extension toggle is optimistic, doesn't sync with server state intermittently anymore).
