### ISSUE TITLE
RFC 427: Store user momentary state/invisible settings

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#21084]
[RFC link](https://docs.google.com/document/d/1PCG1BhagmALYBEUe9PF7I_0W573Fodw4lOEbhYZCyuI/edit#)

There should be a way to store user momentary state or invisible settings. 

Currently, we are using localStorage, which causes a number of issues:
- State will not be saved between sessions. Users will see things again (eg. onboarding tour) if they log in to another computer/browser.
- State will be saved in the same browser even if the user logs out.
- Each of the settings we save has a different key with no clear naming convention.

Examples of things we currently save:
- Onboarding tour state
- Which popups have been dismissed
- Some theme settings

Example of things we want to save:
- Collapse/expand and order state of search sidebar
- More tutorial/modal dismiss states
- Last typed file fuzzy search query per repo (see #20921)

We should have a way to save these sort of momentary states or invisible settings in the backend. Maybe as part of user settings. User's settings should carry over through sessions. Continuing to use localStorage for logged out users is OK, but we might want to organize/standardize those settings to match those stored for logged in users.

**Comment by rrhyne** [comment]
Users may want to alter some of these settings as well. A settings page to list the key / values and edit or remove them would be helpful.

**Comment by limitedmage** [comment]
[Notes](https://docs.google.com/document/d/1el48U_HejMzoUjQ_l2glyPSFkuqTCr_IvIvkfu2zNNY/edit#bookmark=id.chmldfkm9cyj) from Frontend Crew meeting about this topic:

> - Erik Seliger: Seems like a good idea. Have needed this for dismissed notifications.
> - Juliana Peña: Maybe a new key in the user settings?
>   - Might be spammy, but users would be able to reset all of these things
> - Felix Becker: we already store code insights in settings without user manually editing
> - Vova Kulikov: how to reconcile settings when multiple tabs are open? local storage can do this
>   - Felipe Janer: some libraries have revalidate on focus, maybe this is helpful.
>   - Juliana Peña: we already have this problem anyway
> - Juliana Peña (or someone else in search product team) will write up an RFC

**Comment by rvantonder** [comment]
To add to this: would recent searches fit into the scope of this of 'momentary state'? It's worrying that we query the event logs table to get the recent query in the `combined` member _along with_ aaalllll the data we stored for query metrics. Lotta cruft for no good reason https://sourcegraph.com/github.com/sourcegraph/sourcegraph@9f7c75e60e80efae1cb539497cdd0dc68f403784/-/blob/client/web/src/search/queryTelemetry.tsx#L34

**Comment by limitedmage** [comment]
@rvantonder  I definitely think recent searches/repos/file would be a good fit for this.

**Comment by rrhyne** [comment]
I think these user preferences should adopt a dotfiles-like approach. Imagine you point Sourcegraph to a repository you own that has a .sourcegraph file in it. You define what side your search bar panel is on, your syntax theme, your preferences for order of the search sidebar panels, font size, dark mode, etc.

To gain this level of customization you need to connect a repository. That sounds a bit 'markety', but it gets users started down the path of the most important action they can make toward experiencing how powerful code search can be on their own code.

**Comment by pdubroy** [comment]
@limitedmage Are you going to drive this?

**Comment by limitedmage** [comment]
@pdubroy Yes, I was planning to drive this unless Frontend Platform wants to take it on. It makes sense for Frontend Platform to own this, but Search team is in more urgent need of this feature.

**Comment by pdubroy** [comment]
@limitedmage Sounds good. I agree that this is something that should ultimately be owned by Frontend Platform, but we don't have the capacity to drive this right now, so it would be great if Search can drive it and keep us in the loop.

**Comment by lguychard** [comment]
@limitedmage the RFC is out and implementation is tracked in #23425. Should we close this?

**Comment by limitedmage** [comment]
@lguychard  Yes, I'll close this.
