### ISSUE TITLE
"Series is Empty" Validation error when I have completed all fields but not clicked "done" 

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#21094]
If I create an insight but skip clicking "done" then the live preview works fine but I get a validation error on trying to click "create insight."  This is not expected – a user assumes that because they've provided all the information and can see a live preview, they shouldn't need to click "done" essentially twice (in the series, and at the bottom of the form). 

Proposals: 

* Best UX – can we just accept "done" for you/not require you to click done as long as the fields are valid, and let you just click 'create"? 
* Simple + clarity – is it really a "done" or more like an "add another series" button if we implement the "Simple" solution of not requiring it? What if we change "Done" to "Add another series" and it either: a) adds a new series and collapses this one (so it skips two clicks in the current version, the "done" and the "add another series") or b) (if we don't have time for (a) right now) can it just collapse this so you can at least see the "add another series button"
* Acceptable if necessary/if simple we don't have time for by the next release – make the error not be a red "series is empty" error on the validation form, but instead just a red box around "done" (and ideally a message like "you must finish the series"). 
![Data series](https://user-images.githubusercontent.com/11967660/118762896-d5806c80-b82b-11eb-9fd5-45ac5dcc767b.png)

**Comment by Joelkw** [comment]
Update – this is also a "buggy" UX if I "edit" an insight, add another series, then click "edit insight." It validates/lets me exit the page and as a user I think I've edited, but since I never explicitly clicked "done" on a new series, it doesn't save my edits *even though the live preview showed them.* 

A shortened version of the problem is essentially "If I hit create or edit, whatever I see in the live preview should be saved"

**Comment by felixfbecker** [comment]
Agree with all your points (including what is acceptable if we don't have time).

@vovakulikov maybe you remember our convo about treating the series inputs not as a "sub-form" but more like 1..n sets of additional input fields that are inlined into the root form. Clicking the series card basically just shows/hides those inputs visually. Therefor pressing submit if the series is filled out, but not confirmed with "Done", should work and respect the values entered. How this is implemented of course doesn't matter, that's just how I would think about it conceptually (and how the UX should be for the user).
