### ISSUE TITLE
Code insights creation forms should save my progress if I navigate away from the page

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#21098]
If I enter some form fields but then navigate to another page or click away/close the tab accidentally, when I hit the back button it would be very nice if the user saw their in-progress work from the last non-complete extension. This doesn't need to persist across browsers // using localstorage would be fine with me. 

This was a case that a user hit when we still had our original prototype flow (navigated away from settings accidentally) and it frustrated them so much that they gave up on trying to re-create the insight.

**Comment by Joelkw** [comment]
@felixfbecker @vovakulikov do you think there's a lightweight version of this that can be in scope for our next bunch of days of creation UI polish?

**Comment by vovakulikov** [comment]
@Joelkw I agree that this would be useful. It seems like there are no super big changes required to implement this autosave logic. I added this ticket to our next 3.29 release tracking issue

**Comment by felixfbecker** [comment]
I'd just raise that as a user I'd also like a way to start fresh and "discard" an insight. My normal intuition to do this would be to just reload the page, so if we persist all inputs, we should have some kind of "Discard" button so a user doesn't have to manually clear out every input field (which will also still make the red/invalid etc so it's not really "starting fresh").

**Comment by Joelkw** [comment]
@felixfbecker yep, @coury-clark brought that up in sync as well. We may want to have Alicja take a glance at that input/ability.

**Comment by vovakulikov** [comment]
@felixfbecker 
>some kind of "Discard" button which will also still make the red/invalid etc so it's not really "starting fresh"

This is not necessary our case with the discard button. We can initiate discarding and not initiate an input validation. In my vision of that only blur and submit button can trigger re-validation state (show/hide visual validation state)

**Comment by felixfbecker** [comment]
@AlicjaSuska That design looks great to me. The button is less visually standing out and separated well to avoid the general danger of users accidentally clicking it noted on [`<button type="reset">`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/reset) (which, btw @vovakulikov, I think would fit perfectly for this button 🙂 ). 💯

**Comment by vovakulikov** [comment]
@felixfbecker we can't use here button reset, just because we use controlled inputs for the creation UI forms. I mean I have nothing against adding `type='reset'  but logic about resetting fields - we have to add it ourselves.

**Comment by vovakulikov** [comment]
@AlicjaSuska Cool design!

One question What is the reason for disabling this button if a user doesn't have any values? Also, I think it would be the right thing to focus first input if a user clicks `clear all field` button

**Comment by felixfbecker** [comment]
@vovakulikov 

> @felixfbecker we can't use here button reset, just because we use controlled inputs for the creation UI forms. I mean I have nothing against adding `type='reset' but logic about resetting fields - we have to add it ourselves.

Yeah you could add an `onReset` handler on the `<form>` with `event.preventDefault()` if necessary – that would be a neat solution as then any dev could add `<button type="reset">` buttons without having to write any custom logic/event handlers, as long as a shared Form component is used.
