### ISSUE TITLE
Design refresh: keep file tree and code intel references panels width in sync

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#21109]
This ticket should be done after [the code intel references panel redesign](https://github.com/sourcegraph/sourcegraph/issues/21045).
The screenshot shows panels that should be in sync.

<img width="1097" alt="Screenshot 2021-05-19 at 10 34 54" src="https://user-images.githubusercontent.com/3846380/118782731-fc3cb280-b8c0-11eb-99b4-fb63fe6552d2.png">

**Comment by lrhacker** [comment]
<img width="621" alt="image" src="https://user-images.githubusercontent.com/10523985/181062271-ca6832a9-f606-4973-b0d8-bff274a2e0d5.png">
<img width="623" alt="image" src="https://user-images.githubusercontent.com/10523985/181062302-3e29e0f3-b075-478b-972f-d1cc30bddc6f.png">

The resizable panel is no longer used on the lefthand portion of the "References" tab in the current or upcoming UI, so this is no longer relevant.
