### ISSUE TITLE
Copy – modify live preview text

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#21103]
Current: 
![image](https://user-images.githubusercontent.com/11967660/118772357-812fb980-b838-11eb-926c-d400f640cf09.png)

Proposed/change: 
To see a preview, you need to fill in the repositories and series fields.

**Comment by felixfbecker** [comment]
Alternative proposal: "The chart preview will be shown here once you filled out the repositories and series fields"

(avoiding the phrase "you need to" because it sounds a bit aggressive/accusative, the above sounds more neutral I think)
