### ISSUE TITLE
Copy – unify the button text. 

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#21102]
Make them both use the verb "create" rather than "set up" versus "create." 

![image](https://user-images.githubusercontent.com/11967660/118771852-de773b00-b837-11eb-826f-4c9e7a0b9ecf.png)

@AlicjaSuska @felixfbecker @vovakulikov if you have a reason why we're using different verbs here (and think we should continue doing so), please do leave a comment on this issue.

**Comment by felixfbecker** [comment]
Also the "custom" feels wrong because the other button talks about "language usage", therefor this would be "search" (or "search-powered" or whatever we want to use). They could both be argued to be "custom".
