### ISSUE TITLE
Docker image tagging

### ISSUE THREAD

**Issue by dan-mckean** [sourcegraph/sourcegraph#21114]
Users experience problems with deployments and upgrades when images are expected to be in a known state, and are not (tagged).  If an image is not tagged correctly, this can cause the upgrade to fail. We will add release tests to ensure all the images are “the ones we expect” for the release.  These tests currently exist for in the k8s repo and will be added to docker-compose repo.

**Comment by davejrt** [comment]
Fixed in https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/363
