### ISSUE TITLE
First time deployment experience for kustomize

### ISSUE THREAD

**Issue by dan-mckean** [sourcegraph/sourcegraph#21120]
First time deployment documentation for kustomize

Make it super easy (as easy as possible) to understand the value of Kustomize (when and why to use it) and how to use it with Sourcegraph – how to get started.

Dan-proof guide to how Kustomize works. 
(Beatrix or another CS might have started this)

**Comment by dan-mckean** [comment]
Along the lines of the other [issue about Kustomize overlays](https://github.com/sourcegraph/sourcegraph/issues/21119), is this guidance on how to then use the overlays to actually apply all the right default Kubernetes config?

**Comment by bobheadxi** [comment]
I'd like to expand this to include seeing what improvements can be made to the overall Kustomize experience to hopefully make it more attractive as an option
