### ISSUE TITLE
Increase the default postgres requirements in our deployment configs

### ISSUE THREAD

**Issue by dan-mckean** [sourcegraph/sourcegraph#21129]
Increase the default postgres requirements in our deployment configs
  * Modifying the resource management tool for DB/Postgres specific tuning 
  * @dan-mckean's understanding: Reconcile what PostGres says with what Kubernetes says to reduce customer visible issues

**Comment by daxmc99** [comment]
Closing this issue for one https://github.com/sourcegraph/sourcegraph/issues/20519
Also adding that issue to the sprint
