### ISSUE TITLE
Audit the liveness and readiness checks for Postgres

### ISSUE THREAD

**Issue by dan-mckean** [sourcegraph/sourcegraph#21131]
Audit the liveness and readiness checks for Postgres.  If Postgres doesn’t have the correct permissions to the mounted data file storage, then liveness check will pass, but Sourcegraph services will fail to start because the DB does not exist.

**Comment by davejrt** [comment]
Resolved by cherry-picking a commit onto the 3.27.5 tag which addresses the issue of having two pgdata directories and ensures both have the correct permissions to run the migration for pgsql 11  to 12
