### ISSUE TITLE
Proactive database monitoring on dotcom

### ISSUE THREAD

**Issue by indradhanush** [sourcegraph/sourcegraph#21142]
Our production DB on dotcom was at ~100% CPU usage for the last 30 days. 

![s_2021-05-19_155344](https://user-images.githubusercontent.com/2682729/118816080-78d68d80-b8cf-11eb-92b0-fb70ef1f08df.png)

### The Good

- We got lucky that dotcom was available even though database CPU usage has been ~100% for so long. 
- We were able to upgrade the DB instance from 16vCPUs to 32vCPUs with a minimal amount of downtime - ~10 minutes. 

### The Bad

We have some top offending queries. This screenshot was taken after the instance was upgraded. I don't have a screenshot of the queries before the upgrade, but I distinctly remember the average running time of the top offending query here being ~60 seconds and the average rows returned being in the order of ~2 million.

![s_2021-05-19_174912](https://user-images.githubusercontent.com/2682729/118816088-7aa05100-b8cf-11eb-80c1-958d99cb0987.png)

### The Ugly

We have an alerts channel on Slack but because of it's spammy nature no one monitors it actively (including me) and almost everyone (again including me) has that channel muted. It should not have taken us ~30 days to realize our DB CPU has been near 100%. 

Before initiating the [database upgrade](https://github.com/sourcegraph/infrastructure/pull/2584) we had [set a warning banner](https://github.com/sourcegraph/deploy-sourcegraph-dot-com/commit/75878924d93b0d45ae437dc8430562dc75f8ebee) on dotcom. Once the database upgrade was underway, the site was not reachable. Thus setting the banner turned out to be not so useful for our user experience after all.

![image](https://user-images.githubusercontent.com/2682729/118828369-d7553900-b8da-11eb-8aa9-f14c4cee4acf.png)

### What has been done so far?

As a temporary solution to avoid us running into this problem again, we've [routed](https://github.com/sourcegraph/infrastructure/commit/4d0c3c983c6ec32e4c208f841291ab66bbbe0782) database CPU utilization alerts to the #dev-ops channel on Slack.

### What more can we do about it?

We should be actively monitoring the following (at least) database instance metrics:

- CPU utilization
- Memory usage
- Disk storage
- Active database connection count
- Read / Write IOPS

We need to figure out what are sane thresholds to set for alerts and also the communication medium. The on-call person should be mentioned in the alerts. Alternatively if Slack alerts don't work we will need to setup PagerDuty to do this instead.

Increasing the database vCPUs has bought us additional time and we should use this to hunt down the top queries in the screenshot above and find out ways of improving it.

Additionally, we need to have a load testing infrastructure that has a similar scale as dotcom so that we could use this to get a better insight into how our queries are performing before we ship them into production that eventually causes a downtime.

**Comment by daxmc99** [comment]
There are two possible ways I think we could proceed with monitoring and alerting here. 
One option would be to ingest these cloud SQL metrics back into Prometheus/Grafana and use our existing alerting infrastructure. 
```
GCP alerting -> Prometheus/Alertmanager -> Grafana
							(if over threshold) -> Opsgenie
```

Or, we could use terraform with the Opsgenie provider. 

```
GCP Alerting -> (if over threshold) Opsgenie
``` 

Finding sane values for these are likely the first steps. I would prefer the first option since the alerts we decide on could prove useful to customers as well.

**Comment by ryphil** [comment]
@daxmc99 - Was there any movement on either suggestion? This is hanging out in our core-app support but we havent had any movement on it yet so wanted to check-in before moving it anywhere.

**Comment by daxmc99** [comment]
We have a GCP alert for this CPU usage here: https://console.cloud.google.com/monitoring/alerting/policies/11677834676306408736?project=sourcegraph-dev
