### ISSUE TITLE
Display batch changes getting started page to un-authed users / redesign getting started

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#21158]
Unauthed users of the cloud product should see the batch changes getting started page. These users should be prompted to install a local version of the application so they can get started with the solution. 

Additionally, the getting started page requires some modifications such as tabs and body-bg color applied to panels. 

![image](https://user-images.githubusercontent.com/539268/118883914-a9f09700-b8aa-11eb-80c0-0c1aa8c3dc8a.png)

**Comment by rrhyne** [comment]
This page has been reviewed and is ready for dev. Figma:

https://www.figma.com/file/Ad4ewsTTB6oi6BuhwNjQZd/Un-authed-getting-started?node-id=0%3A1&viewport=715%2C1342%2C0.125

**Comment by malomarrec** [comment]
Needs to be included in an A/B test starting on the 28th, with the feature flag w1-signup-optimisation
