### ISSUE TITLE
See if we can fix Firefox update trigger paths

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#21154]
Since we've changed distribution paths, it actually seems like the addons store/firefox doesn't encourage you to upgrade to the latest version. 

Reproduce:

Grab an old version of the extension from our docs page. Visit the add-ons page. Note the version in your current extension is older than the add-on page version, yet there's no "upgrade" button and the CTA is just "remove." 

(Current path – remove it, then install from this page to get the new version.) 

https://user-images.githubusercontent.com/11967660/118865975-5f651f80-b896-11eb-8659-0c0cb5a8ff4c.mp4

I would be surprised if we're the first extension to hit this problem, but a quick google didn't return great results / may have been googling the wrong terms.

**Comment by Joelkw** [comment]
This should block #14233 since sending users to an addon page that says "remove" rather than "upgrade" is not a good use of interrupting their sourcegraph session.

**Comment by muratsu** [comment]
We need to release a small patch for self-hosted to auto update: https://discourse.mozilla.org/t/migrate-from-self-hosted-to-add-ons-store/5403

**Comment by Joelkw** [comment]
@muratsu is this issue complete?

**Comment by muratsu** [comment]
Closing this issue as we've decided to have a migration page instead. See: https://docs.sourcegraph.com/integration/migrating_firefox_extension
