### ISSUE TITLE
slow structural search query on single file

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#21169]
Extraordinarily slow query that shouldn't be: [`repo:github\.com/apache/spark file:common/kvstore/src/main/java/org/apache/spark/util/kvstore/InMemoryStore\.java ...(...) lang:java`](https://sourcegraph.com/search?q=repo:github%5C.com/apache/spark+file:common/kvstore/src/main/java/org/apache/spark/util/kvstore/InMemoryStore%5C.java+...%28...%29+lang:java&patternType=structural)

Likely some issue with searcher<->Zoekt architecture or Zoekt matching, because locally structural search is fine with this pattern.

/cc @sourcegraph/search-platform

**Comment by jtibshirani** [comment]
I'm closing this out since we're not actively investing in structural search.
