### ISSUE TITLE
Notify users of rename from lang-typescript to typescript extension ID

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#2116]
To avoid confusion like at https://sourcegraph.slack.com/archives/C07KZF47K/p1549016057572100, we should hardcode migrations or just console.logs for users who have sourcegraph/lang-typescript enabled to tell them to enable sourcegraph/typescript instead. Same for Go/Python.

**Comment by felixfbecker** [comment]
Can we do this with a DB migration? Could use Postgres' `json_set()` https://www.postgresql.org/docs/9.5/functions-json.html

**Comment by sqs** [comment]
No because settings are JSONC

**Comment by chrismwendt** [comment]
Same for basic-code-intel (from https://github.com/sourcegraph/sourcegraph/issues/2123).

Where might this hard-coded migration live? In Go code in some init or main func?

**Comment by chrismwendt** [comment]
None of the `sourcegraph/lang-$LANG` extensions exist anymore. I don't recall, but I probably deleted them a couple weeks ago. Should I republish them and add a console message, or not even bother?

**Comment by sqs** [comment]
Add a hard coded check for them in the main web code and print a helpful error message pointing people to the new name. That’s the simplest. Don’t republish because that would be confusing.

**Comment by chrismwendt** [comment]
How does this look? Too distracting?

![image](https://user-images.githubusercontent.com/1387653/52307975-f66d6e00-2950-11e9-9b42-ac303d3df73e.png)

**Comment by felixfbecker** [comment]
Also, can't we update the settings programmatically? Why force the user to do this manually?
