### ISSUE TITLE
search: timeouts not respected properly

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#21181]
Example search: [`timeout:500ms [a-z]{100}[a-z]{100}[a-z]{100}[a-b]{100}`](https://sourcegraph.com/search?q=context:global+timeout:500ms+%5Ba-z%5D%7B100%7D%5Ba-z%5D%7B100%7D%5Ba-z%5D%7B100%7D%5Ba-b%5D%7B100%7D&patternType=regexp). This should timeout after 500ms, instead we get no results after 15s and an error saying we couldn't query the DB.

![image](https://user-images.githubusercontent.com/187831/118940419-fc848e80-b950-11eb-9de1-5908f383f9b5.png)

**Comment by keegancsmith** [comment]
Looking at traces, zoekt is not respecting MaxWallTime properly. In an example trace above we have MaxWallTime of 499ms, but the stats report back `stats.wait_ms = 1424`

**Comment by stefanhengl** [comment]
More insights from the traces
- It appears that this issue is always related to `indexed-search-0`.
- The issue is not related to `	shards := ss.getShards()`, because the traces show log entries before and after the call to `getShards` almost at the same time.

**Comment by keegancsmith** [comment]
Stefan and I investigated this this morning. The root cause is a shard containing genomic data. It seems the go regex engine is just very slow here. We don't interrupt the go regex engine while searching a file, so only check for timeouts between files. This leads to us taking 1s to search 1 file -> not respecting timeout. This is expected behaviour and is not that bad. It seems the correct tradeoff here is accepting we can be a few seconds slow to respect timeouts on bad regexes. In the future we will look into faster regex engines.
