### ISSUE TITLE
Batch changes nav item links to about page, but doesn't open in new tab

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#21183]
When clicking through these tabs in exploration, I'd expect all of them to stay in the product so that the navbar stays visible and it's easy to switch back or to the next tab.
The Batch Changes item on dotcom though navigates to the about page, which means the tabs are suddenly gone, which is a bit disruptive. This would be less of a problem if it opened a new tab, as it would be easy to close.

![image](https://user-images.githubusercontent.com/10532611/118975468-55195300-b974-11eb-84ec-f58af70b97fd.png)

**Comment by chrispine** [comment]
closing in favor of #21158
