### ISSUE TITLE
Hover content rendered backwards

### ISSUE THREAD

**Issue by vanesa** [sourcegraph/sourcegraph#2120]
#### Steps to reproduce:

1. Open http://localhost:3080/github.com/sourcegraph/sourcegraph/-/blob/client/browser/src/libs/gitlab/file_info.ts#L13:5 and hover over `getFilePathsFromCodeView`
2. Open https://sourcegraph.com/github.com/sourcegraph/sourcegraph@master/-/blob/client/browser/src/libs/gitlab/file_info.ts#L13:5 and hover over `getFilePathsFromCodeView`
3. Notice how on the local hover the hover content title is shown after the info, while on Sourcegraph.com it shows it reverse.

Local:
![image](https://user-images.githubusercontent.com/9110008/52132931-98f0cd00-2683-11e9-983d-c77078c81cfc.png)

Sourcegraph.com:
![image](https://user-images.githubusercontent.com/9110008/52133084-000e8180-2684-11e9-958d-25345e936358.png)

#### Expected behavior:
Have the content elements of the hover cards render in the same order.

#### Actual behavior:
Locally, the hover content signature is rendered underneath the docstring.

**Comment by sqs** [comment]
I think this is due to one being from basic-code-intel and the other from the sourcegraph/typescript extension. They should be consistent, and I think it makes most sense for the signature to be above the docstring.

**Comment by vanesa** [comment]
Closing since basic-code-intel is deprecated and we are now only using the typescript language extension.

**Comment by vanesa** [comment]
Still happens locally.

**Comment by felixfbecker** [comment]
Hey @chrismwendt, as a user I notice this every day as an irritating inconsistency in our UI, and it has been open for over 2 months. This sounds like a quick fix. Given our focus on polish, would this be possible to prioritise this?

**Comment by chrismwendt** [comment]
Fixed in https://github.com/sourcegraph/sourcegraph-typescript/pull/130

![image](https://user-images.githubusercontent.com/1387653/55657887-9b20f600-57b0-11e9-9820-e6e57c79633c.png)
