### ISSUE TITLE
CSV Export fails if there are too many results

### ISSUE THREAD

**Issue by muratsu** [sourcegraph/sourcegraph#21217]
Our current implementation works fine for small CSV files but doesn't work for large search results. It will create the CSV but download will fail error : Failed -Network Error. 

![image](https://user-images.githubusercontent.com/1308560/119060236-a6cad900-b986-11eb-85b1-15f4d400eb4d.png)

**Comment by ryankscott** [comment]
@abeatrix  looks like this issue can be closed?

**Comment by abeatrix** [comment]
@ryankscott Yup, thanks for checking!
