### ISSUE TITLE
Editing a code language stats insight that was created before the creation flow was built breaks with an error message OR at least fix message

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#21214]
If I edit an insight that existed before the creation flow I get: 

![image](https://user-images.githubusercontent.com/11967660/119052750-ea6b1600-b979-11eb-8282-e2aa114c52ba.png)

I'm actually not sure this is worth fixing unless it's a super easy fix – no more than 6-7 customers have a legacy language insight, and of those that do, I doubt they'll all try to edit it this way. But I wanted to log/track it anyway. 

If we don't want to fix this, let's at least make the message in line [with our copy guidelines](https://about.sourcegraph.com/handbook/communication/content_guidelines/actionable_language#error-messages), something like "We couldn't find that insight" and "Try to find the insight with ID: [ID] in your user or org settings"

**Comment by Joelkw** [comment]
(This would be a worse bug if it broke entirely, so thank you @vovakulikov for handling this case as you did!)

**Comment by vovakulikov** [comment]
@Joelkw Thanks for catching this. I left this message with a grammar error and completely forgot about this. Supporting legacy code stats insight seems like something which I want to avoid because this insight has a bit different settings body compared to the new one insight (query vs repo field and etc). So let's fix the error message now and if our customers tell us this is the important thing we will fix edit properly for old insights.

**Comment by felixfbecker** [comment]
One option would be to write a "migration" in the extension that updates the settins from the old format to the new format on extension activation

**Comment by vovakulikov** [comment]
@felixfbecker can we write a classic DB migration for that? I mean we store user/org settings in our DB right?

**Comment by felixfbecker** [comment]
Not sure because the settings are a JSONC string (with comments and formatting) which Postgres can't edit natively. You could run something on startup of the app, but at that point you might as well just do it on startup of the extension (easier to implement for us)

**Comment by Joelkw** [comment]
@felixfbecker @vovakulikov I leave it up to you on migration, but I'm personally very satisfied with just updating the error strings here and that's probably much easier and faster – I don't think we'll see so much usage (I can think of 1-2 individuals at the moment at just a few customers) it's a major pain point and it's easy to re-set-up on the new extension.

**Comment by vovakulikov** [comment]
@felixfbecker @Joelkw For now I've created a PR  for just changing the redirect message for this case. I will create a ticket for the migration thing but I consider we can close this ticket since this [PR](https://github.com/sourcegraph/sourcegraph/pull/21226) will be merged

**Comment by Joelkw** [comment]
@vovakulikov thanks!
