### ISSUE TITLE
Declarative site config with support for secrets

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#21220]
#### Feature request description

A way to declaratively create our site-config.json & global-settings.json such that is safe to commit to a VCS. 

#### Is your feature request related to a problem? If so, please describe.

Today we support mounting the site-config.json directly as a file (disallowing user edits in the process). However, this cannot be stored in VCS since it contains secrets, negating the advantage of using the site config file

#### Solution

We should support interpolation within the site-config file. Other tools allow for using `$templateKey` in their configuration and then fetching that value either from a separate file, an env var, or even a K8s secret.

**Comment by keegancsmith** [comment]
Please can we fix this. I just wanted to silence an alert, I can't believe the number of roadblocks. I ended up just removing the alert. https://github.com/sourcegraph/sourcegraph/pull/24403

**Comment by daxmc99** [comment]
I have a pretty good idea of how to solve this. Going to try and take this on this week.

**Comment by keegancsmith** [comment]
@daxmc99 Aah sorry I didn't finish up some other work I did. See https://github.com/sourcegraph/sourcegraph/pull/24422 I made it possible to have one config for secrets and another for public.

**Comment by daxmc99** [comment]
Fixed!
