### ISSUE TITLE
Re-enable LSIF uploads to Dogfood instance

### ISSUE THREAD

**Issue by pdubroy** [sourcegraph/sourcegraph#21232]
All LSIF uploads to Dogfood are failing. Context/discussion: https://sourcegraph.slack.com/archives/CMBA8F926/p1621546597012300

#20927 is a related issue that's making it harder to root cause the issue.

**Comment by pdubroy** [comment]
@daxmc99, assigning to you for now. Please feel free to re-assign if you're not the right person.

**Comment by daxmc99** [comment]
Uploads re-enabled here https://github.com/sourcegraph/sourcegraph/pull/21903

Still seeing other errors in LSIF uploads around `yarn install` 
https://github.com/sourcegraph/sourcegraph/runs/2788242490#step:5:8

**Comment by daxmc99** [comment]
Dogfood uploads have been re-enabled. If these steps begin to fail at the dogfood step, feel free to reopen. 
I believe the root cause was resource issues with dogfood.
