### ISSUE TITLE
Add Percy snapshots for code insights chart

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#21247]
Add Percy snapshot in order to catch visual problems with SVG chart rendering in different browsers (Chrome, Firefox, Safari)

**Comment by felixfbecker** [comment]
@vovakulikov is there a difference between this issue and https://github.com/sourcegraph/sourcegraph/issues/20443, or is this a duplicate?

**Comment by vovakulikov** [comment]
@felixfbecker thanks for noticing this. You're right, This issue is just a duplicate.
