### ISSUE TITLE
Auto-escape/fixup queries that resemble common literal queries but are invalid regexps

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#2125]
As a user, if I perform certain common kinds of search queries (listed below), Sourcegraph tries parsing the queries as regexps, which fails. My intent is clear, and Sourcegraph should handle these cases better, as described  below.

- `myfuncname(` to `myfuncname\(`
- `myarray[` to `myarray\[`

Note that these fixups ONLY occur in unambiguous cases, where the query would fail to be parsed as a regexp and therefore return no results (just an error). We do not (in this issue) plan to do any auto-fixup of *valid* queries.

In case we missed any common cases, inspect the Sourcegraph.com search logs for regexp parse errors and add other cases to handle to this issue.

This is a partial and simpler fix for the problem described in #633.

**Comment by keegancsmith** [comment]
> I noticed there is a new searcher implimentation. Is that on or off by default now?

Off by default at the moment.

> I imagined that I’d implement my solution by handling “ParseError”s. When I get a parse error, I’d do some basic heuristics to see if we should auto escape/fixup the query. Would you do this in the graphql handler code or in the query parsing package?

query parsing package. In particular `github.com/sourcegraph/sourcegraph/cmd/frontend/internal/pkg/search/query`. That package has the knowledge of each field and if it represents a regexp. Technically I suppose it is the subpackage `types` that has that knowledge. So the fix here would be some sort of transformation it does in conjunction with the types pkg.

> If in the package, should I do this work in the copy of zoekt’s package you made?

Ideally you would, that package represents the future of our syntax and also should be easier to add support for this feature. But that can be out of scope. If thats the case I'd suggest porting the tests you write to that package, but skip them. That should drastically help someone get back into the context of porting that feature when the time comes.

**Comment by nicksnyder** [comment]
Reopening since the fix was reverted.

**Comment by nicksnyder** [comment]
This is not going to be done in time for the 3.2 release as there are open concerns and product questions. I have moved it to 3.3.

**Comment by ijt** [comment]
I'd like to try a different approach.

Here's why. Auto-fixing broken regexes commits us to an inconsistent query
experience.  If users start by saying "foo(" and that gets fixed, why doesn't
"foo(bar)" get converted to "foo\(bar\)"?  But if "foo(bar)" does get converted
to "foo\(bar\)" then it's not clear how to get the regex behavior again.

Here's something we could do instead that would be more consistent. There can
be a global setting `regex:(on|off)` that defaults to "on". That means existing
users who are used to Sourcegraph searches with regexes will see no change. If a user tries
to submit a query with an invalid regex, we can tell them it's not valid and
give them a fix-up link saying "did you mean: fixed-up-regex" and also ask if
they want to turn off regexes for future searches.

In the search UI, there can be a toggle button to enable regex searches, like
in VS Code, Intellij, Sublime, Textmate. Then users can see at a glance how
it will work if they know about regexes.

**Comment by ijt** [comment]
In offline discussion, @sqs pointed out the problem that global state for regex support causes friction around sharing queries for users with different settings. Luckily, that global state isn't necessary. Just having a "did you mean" link for invalid regexes would be helpful without introducing any inconsistency in how we treat queries.

**Comment by ijsnow** [comment]
> Just having a "did you mean" link for invalid regexes would be helpful

I agree that just displaying something like this would be very helpful and reduce concerns around consistency. However, that means we'd actually be fixing the query. With that, I want to point out that when you actually start fixing the queries there are a lot of deep dark rabbit holes to fall down. Simple string manipulation is incomplete and will often be wrong. If we reuse the `regexp/syntax` packages parser to operate on the query, the queries will get changed by the parser. To prevent this, we'd essentially have to rewrite the regexp type's `String()` method which comes with a lot of complexity.

**Comment by ijt** [comment]
@ijsnow, we could suggest putting quotes around the query to make it literal. Would that address your concern?

**Comment by ijsnow** [comment]
Yea, if the "did you mean" link was just casting it to a literal, that would address my concern

**Comment by ijt** [comment]
We're planning to do #2772 instead for 3.3. Closing this.

**Comment by sqs** [comment]
After thinking about it some more, I do think the **automatic** nature of the fixup is important (vs. #2772 and #2774, which would add an extra step for user). 

- Let's only handle the **unambiguous** cases in the issue description. If one of those cases turns out to be hard to detect/handle, then we can make a decision to omit that case.
- For these simple fixups, we do not need (and should not add) a UI notice to communicate "ORIGINAL_QUERY had a regexp error. Searching instead for FIXEDUP_QUERY." I believe this would just be extra noise for users and complexity for impl.
- I understand that this creates the possibility for user confusion, e.g. with `foo(` working but `foo(a)` not working. I believe the risk is worth it because `foo(` queries are MUCH more common than `foo(a)` queries.

So I reopened this issue and am closing #2772 and #2774.

**Comment by ijsnow** [comment]
Actually fixing queries (e.g. changing `foo(` to `foo\(`) becomes very complicated very quickly. I think this is a good solution if by "fixing", we mean just treating the query as a string literal (e.g. changing `foo(` to `"foo("`).

> For these simple fixups, we do not need (and should not add) a UI notice to communicate [the fix]

While there are likely many users who know the correct syntax but do not care to be explicit, there are probably more who just don't know the syntax is regular expression by default (particularly new users).  We should default to helping new users learn how to use our product rather especially when it doesn't add require extra steps from users who don't need the education. I don't think adding a message to the UI would be noisy or get in the way of anything. Education is important.

As for implementation, I _shouldn't_ complicate things too much. We could just add a field to the [query type](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/pkg/search/query/types/query.go#L10:5) that tells us if it was modified. [This is accessible from the graphql api.](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@c843c8414fef917cc025947e7273494fe9faa6dd/-/blob/cmd/frontend/graphqlbackend/search.go#L74) We could easily expose this and the web app change would be a few lines of code in the [SearchResults component.](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@c843c84/-/blob/web/src/search/results/SearchResults.tsx) It is a non-zero amount of work and would require a little back and forth with @francisschmaltz on UI but I believe education is worth it.

**Comment by sqs** [comment]
Maybe fixup is confusing as a word. I don’t mean to modify the value of the user’s query. I just mean to interpret foo( as foo\( in the regexp parser. This is similar to if you run `ls foo*` in the shell and no files begin with foo; it treats it as a literal. 

My proposed change is very simple. While I agree it would be nice to do a lot more here, those attempts haven’t succeeded yet, so I want to keep it simple first.

**Comment by ijt** [comment]
I agree with ijsnow@ that we should communicate what we are doing if we do this. It doesn't have to include an error message, but we can show that the query has been modified. This sort of thing helps to understand what's going on in some Google searches ([example](https://www.google.com/search?q=recies&oq=recies&aqs=chrome.0.69i59j69i57.1454j0j7&sourceid=chrome&ie=UTF-8)), and it's not a big leap to think it would help our users too.

About the change to be made, why would we want to do special cases rather than trying double quotes around the whole pattern when a regex fails to parse? Quoting is simpler to implement and would handle more cases.

About where the change happens, I'm worried that putting this logic into the query parser permanently commits us to inconsistent guesswork because then saved queries will be treated the same way. Couldn't we do it in the UI for interactive queries only, clearly showing the correction, and not do it for saved queries?

**Comment by ijt** [comment]
To be clear, what I'm proposing would mean that when the search results come back, the query would appear fixed up (double quoted) in the search bar, so that clicking the "Save this search query" link would save the fixed query rather than the one the user entered.

**Comment by sqs** [comment]
All of those other changes sound good (and strictly better than what I proposed), but those are not necessary to solve the user's problem (and it has been harder to implement them than necessary). The user believes that we should be able to interpret `foo(` as `foo\\(` because there is no ambiguity. I have sat with such users and they have badgered me along these lines. :smile:

Knowing that is the minimum problem we need to solve for the user, can you refine your proposal to be simpler to implement? Or do you think it's the simplest to implement that would not cause other big problems?

**Comment by ijt** [comment]
How about this: If the search results come back with a regex error, the server can include a quoted version of the query to try. The typescript code can replace the contents of the search box with that and try again automatically. This is the simplest thing I've thought of that doesn't add the risk of a confusing search experience.

**Comment by sqs** [comment]
Hmm, that sounds difficult because we can’t parse and rewrite the query syntax on the client side (the parser is only in Go). Can you help me understand what the confusing search experience would be if we make the replacements in the issue description at a low level (ie when parsing regexps on the backend)? I am not seeing where it would create confusion in enough common use cases that outweigh the value, so I may be missing something.

**Comment by ijt** [comment]
The server side can return a suggested fix up when it returns an error.
Have to go. More later.

**Comment by ijt** [comment]
Thinking about it a bit more, it's probably possible to try what you're suggesting without being locked in by saved searches. If we decided to change or remove the auto-fixing rules later we could add something to detect saved searches that relied on the old rules and either fix the saved searches or notify the user that they need to be updated.

**Comment by sqs** [comment]
I simplified the list of fixups to make in the issue description to be only the most important ones, to make this easier and quicker to address.

**Comment by sqs** [comment]
@ijt I see you edited the issue description to **add back** the more complex cases I mentioned I removed in https://github.com/sourcegraph/sourcegraph/issues/2125#issuecomment-476472136. Did you intend to do that?

**Comment by ijt** [comment]
@sqs, yes. These cases are fine to include since they would either be invalid (*foo) or not useful (foo()) as regexes. The complexity of the code needed to support them is low and I believe it's a reversible change if we later decide to remove this. That's because we can use the same regexes to detect these patterns in saved searches as we use to do the fixing.

**Comment by ijt** [comment]
Correction: it turns out that making auto-fix idempotent (not escaping things that are already escaped) on all the cases you originally listed makes it complex enough for us to probably want to release a more limited version. For future reference, here's a change that supports those cases: https://github.com/sourcegraph/sourcegraph/pull/2991/files/d2b10821e1b7f9a6367aef0c3a10752d78ef58df.
