### ISSUE TITLE
Add a dismissible alert with basic search help

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#2126]
The dismissible alert would be to help new users perform their first few searches. It would show up on the `/search` page and contain something like (very rough, will update with better text):

> Search all your code from here. Punctuation and regexps are supported. Use keywords like `repo:my/repo`, `file:my/file.txt`, and `lang:javascript` to filter your query (or just type a term and let Sourcegraph suggest ways to narrow your search). Click `(?)` for more help.

**Comment by poojaj-tech** [comment]
Closing since we're launching this functionality with "Search Tours" which helps users with their first few searches :)
