### ISSUE TITLE
Search suggestion loading indicator obscures search query

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#2127]
This loader (for search suggestions) appears on top of the search query. This is annoying because it shows up at the end of what you're typing, which is often where your cursor is, so you can't see the letter you just typed appear.

The simplest (and acceptable) fix is just to remove the search suggestions loading spinner entirely.

![image](https://user-images.githubusercontent.com/1976/52150035-fcbccb00-266e-11e9-87d5-b2dbe1ba0bbe.png)

**Comment by felixfbecker** [comment]
Doesn’t the spinner only show up after you stopped typing?

**Comment by nicksnyder** [comment]
google.com doesn't have a loading spinner for search suggestions.

github.com has a loading spinner in the area that search suggestions would appear (not in the bar itself).

Overall this is a very minor issue that only impacts narrow screens so I think we should either backlog as not important or just delete the spinner for now. Any effort spent discussing/implementing beyond that isn't worth it.

**Comment by sqs** [comment]
We should just remove the spinner as in #2226.
