### ISSUE TITLE
Suggest lang: not file:\.ext$ dynamic search filters

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#2128]
Sourcegraph has supported `lang:` search filters for a while, but our dynamic search filters still suggest things like `file:\.ts$`. In most cases it should instead suggest `lang:`. This promotes learnability.

**Comment by nicksnyder** [comment]
Relevant user feedback: https://sourcegraph.slack.com/archives/C0C324C91/p1553753927002600

**Comment by sqs** [comment]
@attfarhan is prioritizing this for 3.3
