### ISSUE TITLE
Promote features available to authenticated users in search results for unauthed users

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#21295]
Users find value while searching and would experience more value if they were signed up. 

Promote these value propositions tastefully to unauthenticated users in search results.

**Comment by malomarrec** [comment]
[Figma](https://www.figma.com/file/LfQUGTLvfYWxyuFoyQsptB/Expose-features?node-id=0%3A1&viewport=-81%2C-640%2C0.5)

**Comment by malomarrec** [comment]
@ebrodymoore new metrics coming up!
What should we do from a design/product/eng standpoint to get those into amplitude?

**Comment by malomarrec** [comment]
Duplicates #21093 and #21161
