### ISSUE TITLE
Add creating from search-query result functionality for code-insights

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#21323]
Problem: users want to – but can't – turn a search query from search view right into an insight, since they're used to the Search UI. 
﻿
Why this fits in our goals: making it easier to create search-based code insights would directly help achieve our adoption and usage goals. 
﻿
Solution: TBD (probably a simple button on the search results page, similar to the monitor button, that leads to the insights configuration flow).

**Comment by AlicjaSuska** [comment]
Here is how the [design](https://www.figma.com/file/R6oOtAvmfq7ZhRoiJ67pT1/Create-insight-from-search-results-21323?node-id=0%3A1) for the button that you've mentioned @vovakulikov
- It should lead to the creation UI of the search-based insight with the query and repositories copied to it. We should focus and scroll to the query input.

TBD (ongoing slack [thread](https://sourcegraph.slack.com/archives/C01RVEVPWLC/p1623155990013200)):
- tooltips for disabled state
- what if there are no repos in the query
