### ISSUE TITLE
Subscription page: in dark mode, credit card field has white bg

### ISSUE THREAD

**Issue by pdubroy** [sourcegraph/sourcegraph#21338]
- **Sourcegraph version:** Sourcegraph.com

#### Steps to reproduce:

1. Ensure that the Dark theme is enabled
2. Go to https://sourcegraph.com/users/pdubroy/settings/subscriptions/new.

#### Expected

Credit card field has a dark background

### Actual

Credit card field has a white background

![image](https://user-images.githubusercontent.com/17293/119493527-92a92200-bd60-11eb-9de5-42cbe32b4221.png)

**Comment by 5h1rU** [comment]
@pdubroy Is this still an issue? I wasn't able to replicate it.

**Comment by pdubroy** [comment]
I can't reproduce it either.
