### ISSUE TITLE
File tree decorations are low-contrast for selected file in redesign

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#21330]
![image](https://user-images.githubusercontent.com/10532611/119469796-fd019880-bd47-11eb-99bb-8a4e3cb1613f.png)

E.g. https://sourcegraph.com/github.com/sourcegraph/sourcegraph@861ca53785e41c286f0b7add1999af7ce7579d82/-/blob/client/web/src/repo/blob/Blob.tsx

**Comment by tjkandala** [comment]
I've had a [quick fix up](https://github.com/sourcegraph/sourcegraph/pull/21292) for this, but it doesn't address the grey-on-grey issue

**Comment by rrhyne** [comment]
@pdubroy I've taken this and made a few comments on the PR.

**Comment by quinnkeast** [comment]
Posting here so it's all in one place!

I had a quick experiment before seeing @rrhyne or @tjkandala's comments/suggestions in the PR.

<img width="591" alt="CleanShot 2021-05-26 at 10 32 09@2x" src="https://user-images.githubusercontent.com/6304497/119628881-caba6e80-be0d-11eb-8167-900c96f59bc6.png">

Percentage label is always `text-muted`, while the bar background is `$grey-5` / `text-disabled` on hover/focus and current states.
