### ISSUE TITLE
Test 3.0.0 image tag on kubernetes cluster

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#2133]
- [ ] Update image tags to v3.0.0 in deploy-sourcegraph
- [ ] Test on k8s cluster.
- [ ] Tag v3.0.0 in deploy-sourcegraph

**Comment by ggilmore** [comment]
I tested a fresh 3.0.0 cluster and the 2.12.x -> 3.0.0 upgrade and it seems to work. I will wait until 3.0.1 is released to test:

- fresh 3.0.1
- 2.12.x -> 3.0.1
- 3.0.0-beta.3 -> 3.0.1

**Comment by nicksnyder** [comment]
This issue is superseded by https://github.com/sourcegraph/sourcegraph/issues/2179
