### ISSUE TITLE
Unintuitive sign up experience due to (un)verified email address

### ISSUE THREAD

**Issue by fkling** [sourcegraph/sourcegraph#21344]
- **Sourcegraph version:** 97031_2021-05-25_5802320

This issue is related to https://github.com/sourcegraph/sourcegraph/issues/20710 but I wanted to create a separate one to elaborate on my experience.

## Actual behavior

- I signed up on https://sourcegraph.com/sign-up and got an email to verify my email address.
- I clicked the link, but it opened in another Firefox container, so Sourcegraph asked me to sign in again.
- I provided my email address and password (via password manager) but the got the error message "User or password was incorrect".
- I couldn't imagine that my password is incorrect  but I clicked on the "Forgot password" link just to make sure. I never received an email, making me wonder whether there is an issue with the email address.

As it turned out, signing in with my *username* worked, and once I was logged in I could verify the email address. Afterwards I was able to login with my email address and also receive the password reset emails.

## Expected behavior

I see a couple of ways that could have helped me

- signing in with an unverified email address should be possible (not sure about the security implications though)
- inform the user one way or the other that signing in only works via username unless an email address was verified (maybe that was the case and I missed it?)
- either getting some information that it's not possible to reset passwords with unverified email addresses (which would still require further information about how to resolve the issue) or allowing password reset emails to unverified addresses. Anything seems to be better than silently not sending the email.

Overall it wasn't clear what steps I needed to take to resolve this situation. I wouldn't have thought signing in with my username would work if signing in with my email address didn't.

**Comment by quinnkeast** [comment]
I'm half-wondering if this is a regression related to our changes to the account primary email addresses a while back.

I think the choices here are:

1. Allow unverified emails to sign in.
2. Require verified primary email, and catch that the email is unverified when the user signs in, and show a "verify your email / resend verification email" view.

The former reduces friction and I believe is what we previously had working, and lets us prompt for verification only when we require it. The latter is more explicit about requiring the verified email, and doesn't introduce copy that has to be interpreted and understood.

@unknwon @sourcegraph/security any thoughts here?

**Comment by unknwon** [comment]
> 2\. Require verified primary email, and catch that the email is unverified when the user signs in, and show a "verify your email / resend verification email" view.

I think this option is better and more common.

**Comment by fkling** [comment]
> 2. Require verified primary email, and catch that the email is unverified when the user signs in, and show a "verify your email / resend verification email" view.

Wouldn't that possibly leak information about which email addresses exist and doesn't exist in our database (which is generally avoided)? Someone more knowledgeable about security concerns like this should chime in :)

**Comment by fkling** [comment]
Ah ok, that makes more sense!

**Comment by eseliger** [comment]
Seems to be resolved.
