### ISSUE TITLE
executor: Launch cache-warming VM at application boot

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#21377]
Instead of locking all `ignite run` commands to prevent concurrent dependency requests, we should do a canned sequence of commands at startup to pull down any dependencies (docker images, etc) that could lead to concurrency issues.

**Comment by efritz** [comment]
@eseliger Is this still an issue/

**Comment by eseliger** [comment]
No I don't think the described thing is still necessary. But we still have the lock around ignite run, right? I think that is still problematic, especially on larger hosts.

**Comment by efritz** [comment]
@eseliger Do we have an issue for that already? If so can we close this one? If not can we close it in favor of a more accurate issue?

**Comment by eseliger** [comment]
I don't remember but quick searches haven't returned a ticket for that. Yes, we can close it and create a more detailed one.

**Comment by eseliger** [comment]
https://github.com/sourcegraph/sourcegraph/issues/29524
