### ISSUE TITLE
Cross-repo references are not showing up from TypeScript basic code intel

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#2137]
At https://sourcegraph.sgdev.org/github.com/sourcegraph/sourcegraph/-/blob/cmd/management-console/web/src/MonacoEditor.tsx#L90:21&tab=references I am not seeing any cross-repo references to this token:

![image](https://user-images.githubusercontent.com/1976/52176371-174b8d00-27b2-11e9-8ad9-78c829714809.png)

I expect to see references from ReactiveX/rxjs to this token because they show up in search:

![image](https://user-images.githubusercontent.com/1976/52176378-334f2e80-27b2-11e9-99ad-23f2b687b2dd.png)

**Comment by chrismwendt** [comment]
I accidentally broke this during refactoring a few days ago 😞 

Fixed in https://github.com/sourcegraph/sourcegraph-typescript/commit/a3cd559a75155b0128c8d06458a07eac728841e3 and https://github.com/sourcegraph/sourcegraph-basic-code-intel/commit/a236e8083a03b8a02f5573477710684f875570b6
