### ISSUE TITLE
Add FOSSA for OSS license checks

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#214]
Tracking issue for adding FOSSA to our CI and a badge

**Comment by kevinburke** [comment]
FOSSA does not currently support Go modules. 

https://github.com/fossas/fossa-cli/issues/234

@mitchellh suggested a workaround in the linked Github issue:

https://gist.github.com/mitchellh/72ccd9174897aeb65c46a6d6859919d6

**Comment by kevinburke** [comment]
@sqs what do you think - should I try to go ahead with the gist approach, or wait for Go module support?

**Comment by sqs** [comment]
Let’s wait for Go modules support

**Comment by francisschmaltz** [comment]
@beyang It looks like support was added https://github.com/fossas/fossa-cli/issues/234#issuecomment-436016038 Can we prioritize or fix this?

**Comment by sqs** [comment]
@francisschmaltz 	We can, but I don't see it as a priority right now.
