### ISSUE TITLE
Flake: `TestIntegration/Server/RepoLookup/found_-_gitlab.com_on_Sourcegraph.com` disabled

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#21408]
- **Name of test:** `TestIntegration/Server/RepoLookup/found_-_gitlab.com_on_Sourcegraph.com`
- **Example failure:** https://buildkite.com/sourcegraph/sourcegraph/builds/97243#08afde54-be7f-4b01-a442-329905a59b97
- **PR**: https://github.com/sourcegraph/sourcegraph/pull/21409

**Comment by eseliger** [comment]
Seems to be not disabled anymore.
