### ISSUE TITLE
Breadcrumb adjustments

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#21418]
This ticket collects two issues of feedback related to breadcrumbs:

* @ symbol as a divider
  * Discussion: https://sourcegraph.slack.com/archives/C01TFNBHYCV/p1621951411057600 
* Font size used in file path
  *  Discussion: https://sourcegraph.slack.com/archives/C01TFNBHYCV/p1621951440058200

Designs:
https://www.figma.com/file/pbQ58ocQ6xmKLeO9C17nE7/Breadcrumb-adjustments?node-id=0%3A1&viewport=727%2C521%2C0.775943398475647

**Comment by umpox** [comment]
@rrhyne This has been merged now!

**Comment by umpox** [comment]
Closing this in favor of https://github.com/sourcegraph/sourcegraph/issues/21051 (for implementation review)
