### ISSUE TITLE
Update G Suite browser ext install steps

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#2141]
https://docs.sourcegraph.com/integration/google_gsuite#automatically-install-with-g-suite says to use configuration including `serverUrls`. This is incorrect now that the extension supports only a single server URL.

**Comment by chrismwendt** [comment]
Fixed in 515f7d61ac2ac45ccd3666e7319abac1625dc961 (I committed that before I saw https://github.com/sourcegraph/sourcegraph/pull/2142, which also updates the docs).
