### ISSUE TITLE
matches report lines instead of highlights

### ISSUE THREAD

**Issue by stefanhengl** [sourcegraph/sourcegraph#21443]
Looking at the screenshot, on the right side it says "275 matches, 265 more" which 
implies we see 10 matches, however counting the highlights I see 12 matches for the first file.
We seem to be reporting lines and not highlights.

https://sourcegraph.com/search?q=context:global+repo:github.com/sourcegraph/sourcegraph+resolver+lang:go&patternType=literal

<img width="2544" alt="Screenshot 2021-05-27 at 13 02 40" src="https://user-images.githubusercontent.com/26413131/119815501-e5fbab80-beeb-11eb-8dda-21cfda82dc50.png">

**Comment by stefanhengl** [comment]
I took a look at the code. Things are getting a bit more complicated because of `context` IE lines of code we show around matches. We compute the collapsed label before we know how many highlights will actually be visible: If a highlight is on a context line, we show the highlight but don't account for it in the label.

**Comment by rvantonder** [comment]
Could you give an example query? I would confirm if this happens on the indexed search path only or not. Possibly a regression. I'm reminded of gremlins when I fixed things in this PR https://github.com/sourcegraph/sourcegraph/pull/11242

**Comment by rvantonder** [comment]
Hmmm, hard to say, there is a discrepancy between `index:no` and `index:only` for the first file in that screenie, but even the `index:no` results look very wrong (100 matches, even if I set count:10000).

- [index:only](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:enterprise/cmd/frontend/internal/codeintel/resolvers/mocks/mock_resolver.go+resolver+index:only&patternType=literal)

- [index:no](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:enterprise/cmd/frontend/internal/codeintel/resolvers/mocks/mock_resolver.go+resolver+index:no&patternType=literal)

- [index:no count:10000](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:enterprise/cmd/frontend/internal/codeintel/resolvers/mocks/mock_resolver.go+resolver+index:no+count:10000&patternType=literal) <- this one's weird

**Comment by keegancsmith** [comment]
@rvantonder: Stefan is referring to the count numbers for each file. IE that number seems to be reporting the number of line matches rather than fragments. This number isn't returned by the backend, but is computed in the webapp when displaying a file. In the API/backend we consistently count matches as the number of fragments.

The discrepencies you are reporting are indeed weird. But we still have some hardcoded limits in searcher. For zoekt there are no hardcoded limits.

**Comment by rvantonder** [comment]
Gotcha, thanks @keegancsmith

**Comment by stefanhengl** [comment]
I added a query to the description. As Keegan mentioned, the issue is just in the UI. We should display highlight counts, not line counts.
