### ISSUE TITLE
Placeholder in search bar

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#21465]
![image](https://user-images.githubusercontent.com/206864/119875930-2eab6880-bedc-11eb-8af1-27de22556124.png)

The redesign specified a placeholder in the search bar to help users identify the input, especially in the XS responsive designs. This is not possible in monaco currently and would need a workaround. See:

https://github.com/microsoft/monaco-editor/issues/1228

**Comment by limitedmage** [comment]
@rrhyne  Should the placeholder show in only the XS size or in all sizes?

**Comment by rrhyne** [comment]
No, I don't beleive so, but it is doubly important there because of design makes in a bit unclear that the item is an input.

**Comment by limitedmage** [comment]
This is complete with the migration to CodeMirror and will be enabled for everyone soon.
