### ISSUE TITLE
search: `patternType:structural` does not work with `type:` filter

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#21485]
In both streaming search and batch (graphql) search, `patternType:structural` will always return only file line matches and will not take into account `type:` filters in the query.

If this is expected behavior, we should return a warning alert telling users that structural search will only return file matches.

**Comment by rvantonder** [comment]
> Hey, @sourcegraph/batchers (@eseliger @mrnugget @LawnGnome @malomarrec @chrispine @courier-new) - we have been mentioned. Let's take a look.

??? 😄

**Comment by rvantonder** [comment]
These shouldn't work together. I think the surprising thing is that it returned results. I'm pretty sure we previously did not return results. That regression might have been because of https://github.com/sourcegraph/sourcegraph/pull/19698.

**Comment by LawnGnome** [comment]
> ??? smile

One of the triggers is the word "batch" — we were worried it would be too sensitive, but I think this is the first misfire I can remember since we added it. Sorry for the noise! :see_no_evil:
