### ISSUE TITLE
Large margin between search bar and repo nav

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#21512]
Actual:

![image](https://user-images.githubusercontent.com/10532611/120013672-4fa9b180-bfe1-11eb-8cd2-c2e93282f53d.png)

Design:

![image](https://user-images.githubusercontent.com/10532611/120013696-59331980-bfe1-11eb-9abc-ae737c956dea.png)

**Comment by limitedmage** [comment]
@sourcegraph/design  what is the right padding to use here? The Figma is inconsistent that there is different padding in the search results page vs the file page.

![image](https://user-images.githubusercontent.com/206864/120017876-3ed64d00-bf9b-11eb-8edb-83d603b5893f.png)

https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Design-Refresh---Systemization-(source-of-truth)?node-id=1018%3A13883

**Comment by limitedmage** [comment]
Syncing offline with @rrhyne, we'll go with 8px (0.5rem) and make in consistent across pages.
