### ISSUE TITLE
Edit context menu only appears on insights page, not on directory page and homepage

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#21524]
To reproduce:
1. Go to https://sourcegraph.com/github.com/sourcegraph/sourcegraph
2. See insights have no three-dot menu

**Comment by vovakulikov** [comment]
@felixfbecker @AlicjaSuska this was disabled intentionally by me on the homepage and directory pages in the first version of the creation UI. For the directory page, we should switch the repo field from repositories values to the 'current' (directory) repo. This is kind of related to https://github.com/sourcegraph/sourcegraph-search-insights/issues/6#issuecomment-850740541

For me, as a user, this is not clear what it would be if I clicked edit of some insight on the directory page. Should we open an edit page with directory URL repo in repositories filed in creation UI form or something else? About delete button the same story. Should we delete this insight entirely or just delete this insight from a particular directory view?

**Comment by felixfbecker** [comment]
The user problem I see here is:
As a user, who is not familiar with code insights and is browsing a repo, I may see code insights that others configured in org settings and I have no way to know how these are configured and take a look at the configuration.
That is at best a missed opportunity, and at worst frustrating.
I've personally wanted to edit an insight I saw on the repo page, and had to navigate to the Insights page instead, wait for them to load again, just to click edit.

Your points are good points though, they are valid concerns I hadn't considered.

> Should we open an edit page with directory URL repo in repositories filed in creation UI form or something else?

With the clarified behavior in https://github.com/sourcegraph/sourcegraph-search-insights/issues/6, I think it makes sense that the repositories field is always the list of repositories in a _global_ context (insights page/homepage), but on repos and directory pages it's always overridden with the current one. We should communicate that in the help text of the input.

> About delete button the same story. Should we delete this insight entirely or just delete this insight from a particular directory view?

I think it makes sense to delete it for all places here too, but we should communicate it in the confirm message (https://github.com/sourcegraph/sourcegraph/issues/21515), like "This will delete the insight from the insights page, the homepage and all repository/directory pages. Are you sure you want to delete the insight?"
