### ISSUE TITLE
Search sidebar reference panel

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#21539]
A reference panel will help new users learn the query syntax while they use the product. The panel will be searchable and clicking an item in the panel will add it to the search input with placeholder text selected and ready for the user to type the proper value.

![image](https://user-images.githubusercontent.com/539268/120053748-ddd16800-bfe0-11eb-98f7-f1659e05f014.png)

Figma file:
https://www.figma.com/file/as1QusTZKQlUakfC90ANwb/Search-reference-panel?node-id=0%3A1&viewport=919%2C239%2C1.1955307722091675

**Comment by fkling** [comment]
I guess we can close this now?
