### ISSUE TITLE
Version context menu redesign

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#21534]
Adjust the colors of the version context menu to ensure it continues to demo well with the redesign enabled. This should be a very quick effort though, as version contexts will be depreciated soon.

![image](https://user-images.githubusercontent.com/539268/120041820-ce8cf300-bfbd-11eb-93c1-bbdc32424b69.png)

Figma:

https://www.figma.com/file/eZ5uFeofqZpkbPogvAazvu/Version-contexts-redesign?node-id=0%3A1&viewport=-1082%2C569%2C1.0046948194503784

![image](https://user-images.githubusercontent.com/539268/120042905-d483d380-bfbf-11eb-8d5a-1f2568c71765.png)

**Comment by rrhyne** [comment]
@lguychard will contexts complete replace version contexts this release? If not, version contexts design needs a quick touch-up.

**Comment by lguychard** [comment]
@rrhyne the plan is for customers using version contexts to migrate off of them immediately following the 3.29 upgrade, we've synced with CE to prepare this. So, version contexts will still be _present_ in 3.29 (the feature won't have been removed), but my take is we should spend our effort supporting the migration, not touching up version contexts at this stage.
