### ISSUE TITLE
Entering a repo that is not found in the Repositories field will show HTML code to the user in the error message

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#21547]
## Problem statement
Bad HTML code error message below the repositories search field at the code insights creation UI.

## Success criteria
Improve repositories search field error message in a way that this message could be a real HTML (with working links and other HTML content that backend validation returns) 

To reproduce:
- Go to https://sourcegraph.com/insights/create-search-insight
- Type in "github.com" into the input field and wait for validation.

![image](https://user-images.githubusercontent.com/10532611/120071769-fdc06480-c090-11eb-9885-9eb8dab28b63.png)

Note how there are `<p>` and `<a>` tags in the error message visible to the user. Instead, these should not be visible but rendered instead (actual links).

I'm pretty sure this is the bug I pointed out in https://github.com/sourcegraph/sourcegraph/pull/20995#discussion_r635124507, see the thread for my suggested solution (https://github.com/sourcegraph/sourcegraph/pull/20995#discussion_r634612955, let me know if you need help).

**Comment by gssandhu143** [comment]
@felixfbecker @vovakulikov  kindly assign this to me and update me about the prerequisites to running this on local machine.

**Comment by vanesa** [comment]
FYI, this issue is still available to solve!
