### ISSUE TITLE
Background of meters feels a bit too dark now

### ISSUE THREAD

**Issue by pdubroy** [sourcegraph/sourcegraph#21558]
Context: https://sourcegraph.slack.com/archives/C01TFNBHYCV/p1622223695112300

Change to the following:

**Light theme:**
- `gray-04` by default (same as before the refresh)
- `gray-05` for selected, active, hover states

    <img width="312" alt="CleanShot 2021-06-01 at 09 58 26@2x" src="https://user-images.githubusercontent.com/17293/120287855-ee732e00-c2bf-11eb-9f4d-c666b47d4f40.png">

**Dark theme:**
- `gray-07` by default; unchanged in selected, active, hover states

    <img width="308" alt="CleanShot 2021-06-01 at 09 58 09@2x" src="https://user-images.githubusercontent.com/17293/120287865-f03cf180-c2bf-11eb-9b2a-06d26dccf75e.png">

**Comment by quinnkeast** [comment]
Looks great!
