### ISSUE TITLE
Outline badges

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#21562]
Design would like to add an outline badge to support the old keyboard component style:

![image](https://user-images.githubusercontent.com/539268/120220548-c0271d00-c1f1-11eb-9e6c-806eac51c386.png)

This would be useful in the new file fuzzy finder and other areas of the product:
![image](https://user-images.githubusercontent.com/539268/120220648-efd62500-c1f1-11eb-8d9d-ceec1c746d84.png)

Figma design here:
https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Design-Refresh-Systemization-source-of-truth?node-id=947%3A7095

**Comment by rrhyne** [comment]
@umpox where is the PR for this?

**Comment by umpox** [comment]
For future readers: https://github.com/sourcegraph/sourcegraph/pull/21588

@rrhyne Thanks for finding and reviewing this. I'm going to close this and move to 'done' as the PR got your approval. Let me know if there are any problems!
