### ISSUE TITLE
Private/public code settings pages need containers

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#21567]
...and other changes such as removal of borders around list items, full width for consistency and other tweeks.

The pages requiring updating are:

https://sourcegraph.com/users/eseliger/settings/security
https://sourcegraph.com/users/eseliger/settings/code-hosts
https://sourcegraph.com/users/eseliger/settings/repositories

Figma designs of requested changes:

https://www.figma.com/file/PGorahH15wPOQ6WgYlzmBY/Remaining-settings-pages?node-id=0%3A1&viewport=472%2C321%2C0.2701502740383148

**Comment by umpox** [comment]
PR: https://github.com/sourcegraph/sourcegraph/pull/21692

**Comment by rrhyne** [comment]
QA: https://www.figma.com/file/PGorahH15wPOQ6WgYlzmBY/?node-id=15%3A19

@quinnkeast, you might want to have a look at the above!
