### ISSUE TITLE
Code insights creation UI typo: "Seperate repositories with comas"

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#21564]
I just read over this in review and testing without noticing it 😬 

![image](https://user-images.githubusercontent.com/10532611/120228626-cb0e9b80-c24b-11eb-97b9-b7cf15e27d65.png)

Should be "commas", not "comas"

**Comment by vovakulikov** [comment]
I was in a coma, probably when I added this 🤦 thanks for catching

**Comment by Joelkw** [comment]
closed by #21603
