### ISSUE TITLE
Jumping-to-line in a file sometimes appears to hang for several seconds

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#21578]
See [this Slack thread for more details](https://sourcegraph.slack.com/archives/C0W2E592M/p1622540659099900), but I'll try to reproduce here.

I wrote:

> I'm often confused when I get a sourcegraph link to a specific line in a file, I click on it, and I don't jump to the line.
> I then realise it's because the jump-to-line functionality waits for the extensions to load, which can take 3-5 seconds in my experience.

Example links:

* https://sourcegraph.com/github.com/golang/go/-/blob/src/os/exec/exec.go#L664
* https://sourcegraph.com/github.com/rust-lang/rust/-/blob/compiler/rustc_middle/src/mir/mod.rs#L1870

Video:

https://user-images.githubusercontent.com/1185253/120309080-1751ee00-c2d5-11eb-8d85-7878a49206ad.mp4

But I **can't reliably reproduce this**: when clicking the same links again now I can't reproduce the behaviour.

@felixfbecker dug into this and managed to capture a profile. Reconstructing his Slack message here:

> I just took a quick profile and the majority of time is actually spent on **painting**! Each of the green "Composite Layers" blocks is almost half a second long (and is blocking the main thread). It's hard to figure out what exactly makes it take that long, but at its core these are responses of the browser to React rerendering something and needing to paint it, and with the many DOM nodes from syntax highlighting, the table layout and potentially even changes introduced from the redesign there could be many reasons why the browser takes this long to apply an update.

![image](https://user-images.githubusercontent.com/1185253/120309183-3ea8bb00-c2d5-11eb-864a-5ad3588fe621.png)

**Comment by pdubroy** [comment]
Weird. I can reproduce this, but my profile doesn't look anything like what @felixfbecker is seeing. It looks like it is mostly idle, not painting.

![CleanShot 2021-06-01 at 15 26 46](https://user-images.githubusercontent.com/17293/120331169-c8fd1900-c2ed-11eb-8d95-85ee81856c3e.png)

**Comment by felixfbecker** [comment]
Did you have "Advanced paint instrumentation" on? (If not, it may actually be that the overhead of the paint instrumentation makes it so slow in the profile, and the real bug is something much simpler like a React component not reacting to a prop change)

**Comment by umpox** [comment]
Is anyone able to replicate this locally? It would be useful to run this through the React Profiler too

**Comment by tjkandala** [comment]
I have a strong hunch that this is related to the extension loading issue. 

Scrolling to position is handled by codeintellify's [`hoverifier`](https://sourcegraph.com/github.com/sourcegraph/codeintellify/-/blob/src/hoverifier.ts?L1054-1069), which we don't initialize until the text document is acknowledged by the extension host. Unfortunately, the extension host is busy synchronously loading the initial set of extensions.

This functionality shouldn't block on extension loading. We should implement some sort of cooperative multitasking in the extension host worker so the extension loader can yield control to events from the main thread, keeping extensions-related UI responsive.

**Comment by mrnugget** [comment]
> I have a strong hunch that this is related to the extension loading issue.

I thought the same, but there's a lag between when the extension loading indicator stops and when it jumps. That made me doubt that it's related.

**Comment by fkling** [comment]
This is likely not an issue anymore since we removed extensions and switched to CodeMirror.
