### ISSUE TITLE
Extensions registry order is not deterministic

### ISSUE THREAD

**Issue by muratsu** [sourcegraph/sourcegraph#21572]
The extensions on the extension registry don't show up deterministically. Enabling/disabling & refreshing changes the orders and it's confusing. 

https://sourcegraph.com/extensions?category=All

Extensions registry order of extensions should be deterministic such that: 
- Anything I have enabled should show up first
- Then the remaining extensions in alphabetical order

**Comment by muratsu** [comment]
Yeah, currently it looks really confusing when we disable extensions:

![order-bug](https://user-images.githubusercontent.com/1308560/120349254-cd581080-c2b2-11eb-8f33-78f86f6be38b.jpg)

Also tagging @Joelkw who found this issue

**Comment by Joelkw** [comment]
Yep, I think we should alphabetize extensions and then within that if some are enabled/disabled make that the split, so if I have extensions A B C D E F and I've enabled extensions C and E, I would see an order like: CEABDF
