### ISSUE TITLE
Committer initials aren't constrained to circles

### ISSUE THREAD

**Issue by pdubroy** [sourcegraph/sourcegraph#21583]
From @eseliger:

![image](https://user-images.githubusercontent.com/17293/120332339-f1394780-c2ee-11eb-9044-066d9f51953c.png)

The `Bm` initials cause the element to be wider than it is tall, and therefore no longer a circle.

**Comment by umpox** [comment]
@5h1rU I have pushed up a fix for this, and branched from your diff view branch as I see you have modified this structure slightly. PR is here: https://github.com/sourcegraph/sourcegraph/pull/21685
