### ISSUE TITLE
The Find references button shows up on whitespace

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#2159]
- Enable sourcegraph/go
- Visit https://sourcegraph.com/github.com/gorilla/mux/-/blob/mux.go
- Hover over whitespace
- Notice "Find references" pops up

![2019-02-05 03 09 41](https://user-images.githubusercontent.com/1387653/52269700-a4e2c600-28f3-11e9-904b-40368989a548.gif)

Potential solutions:

- Special-case whitespace as a no-op in the extension host
- Add an optional callback argument `shouldDisplayButton` to `registerReferencesProvider` so that an extension could perform some custom check to see if there are likely to be any references (not sure what the name would be)
- Execute the provider immediately (just like we do with hovers and defs) and only show the button once results come back (will have perf implications, since refs are usually slower)

@lguychard I'm curious how you think we could solve this.

**Comment by lguychard** [comment]
Instinctively I'd say we should not call reference providers over whitespace.

**Comment by felixfbecker** [comment]
We could only hide the button on whitespace at the start and end of lines

**Comment by chrismwendt** [comment]
Resolved by https://github.com/sourcegraph/sourcegraph/pull/3188
