### ISSUE TITLE
Remove search help button and re-add search box shadow once sidebar reference panel is added

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#21592]
Once #21539 (Search sidebar reference panel) is complete, we can remove the search help button and re-add the shadow that was removed to fix #21554.

![image](https://user-images.githubusercontent.com/206864/120359992-2331b600-c2bd-11eb-961f-8099df4c325d.png)

**Comment by rrhyne** [comment]
This is fixed by #22917
