### ISSUE TITLE
GCP access control audit

### ISSUE THREAD

**Issue by dan-mckean** [sourcegraph/sourcegraph#21599]
GCP access control audit

From [security cloud plans doc](https://docs.google.com/document/d/1rZsHOr0CH1RP5ahsG_YFVJLF_7uhtgK93Fuh77SD2gE/edit#bookmark=id.m41m9gd2dtjk)

Waiting on @bcreager to find a good example to ~shamelessly imitate~ base ours off.

**Comment by davejrt** [comment]
@dan-mckean Is there more information related to this that I can read related to this?

**Comment by dan-mckean** [comment]
@bcreager reminder that we're waiting on:
>Waiting on @bcreager to find a good example to shamelessly imitate base ours off.

**Comment by dan-mckean** [comment]
@bcreager still waiting on something to copy

**Comment by dan-mckean** [comment]
@bcreager I kinda feel like we did this - we cut a load of people with access.

But I also know we envisaged the output being some sort of (largely plaugerised) document... so I'm not sure. 

What're your thoughts on closing this?

**Comment by dan-mckean** [comment]
We partially did this. It'll come back up for a more formal revisit with SOC2 work.
