### ISSUE TITLE
codeintel: Replace hard coded list of repositories to dependency index

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#21607]
Following up from action items listed in https://github.com/sourcegraph/sourcegraph/pull/21476.

Current solution:

```
var dependencyIndexingRepositoryIDs = []int{
	36809250, // sg/sg on cloud
}
```

This should instead be a database table that won't require an instance restart to take effect.

**Comment by tjdevries** [comment]
I think we can close now @efritz ?
