### ISSUE TITLE
Document `DISABLE_CODE_INSIGHTS`

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#21605]
We have several customers running with 
`DISABLE_CODE_INSIGHTS=true` 

Currently, this is an undocumented feature but since it is in our codebase, we should either remove it or fully support it. 

Documentation of this feature will include _where_ to place this env var as our current tribal knowledge says to place it on frontend and gitserver. 

What are the effects of this env var being set?

**Comment by northyg** [comment]
Hello! 👋 Spoke with @daxmc99 and here are some recent examples of customer's using this. Understanding the full ramifications of setting would be helpful!

https://sourcegraph.slack.com/archives/C01E3PX9E3Z/p1622440538000900
https://sourcegraph.slack.com/archives/CTN0ZBETE/p1622151169061000
https://sourcegraph.slack.com/archives/C014ZCKMCAV/p1621887575071100
https://sourcegraph.slack.com/archives/C014ZCKMCAV/p1614718017058900
