### ISSUE TITLE
Add help tooltip over search types

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#21615]
### User problem
New users don't understand what search types are, and get confused about `select` vs `type`.

### Proposed solution
Add help tooltip over the search types items.
![image](https://user-images.githubusercontent.com/25070988/120437885-ef1fc900-c380-11eb-9200-d64966297724.png)

**Comment by fkling** [comment]
Since we have removed/revisited the search types section completely, this is probably no longer relevant.

**Comment by lguychard** [comment]
We no longer have a search types section.
