### ISSUE TITLE
Padding between tabs and file tree

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#21612]
On the latest sourcegraph.com when visiting [this file page](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/schema/settings.schema.json), the Files / Symbols tab starts out slightly scrolled which makes the margin between the tabs and file tree look incorrect:

![image](https://user-images.githubusercontent.com/539268/120408113-37000b00-c303-11eb-8d55-78ab39e658e0.png)

**Comment by pdubroy** [comment]
Seems to be fixed. Please re-open if I'm wrong.

![CleanShot 2021-06-25 at 17 13 14](https://user-images.githubusercontent.com/17293/123445902-a43c4e80-d5d8-11eb-92cf-17678baa0ab9.png)
