### ISSUE TITLE
src-cli: Upload changeset specs one by one, not all at once, and give users a way to preview them before the batch spec is fully executed

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#21618]
As a user it's not great that I have to wait for _all_ changesets to finish execution before I can see one of the diffs.

Ideally I can look at the diffs that have been produced so I know that the rest of the execution will also produce meaningful results.

---

What happens right now, on the GraphQL layer, in rough pseudo code:

1. `createChangesetSpec(...)` -> get back id `cs1`
2. `createChangesetSpec(...)` -> get back id `cs2`
3. ...
4. `createChangesetSpec(...)` -> get back id `csN`
5. `createBatchSpec(rawSpec, [cs1, cs2, ...csN])` -> get back `bs1`
6. then: `applyBatchSpec(bs1)`

The historical reason for why we do it like that is that we want the batch spec that's created in step 5 here to be immutable: once a user previews it nobody should be able to add changeset specs to it. Otherwise someone else could add another changeset spec between the "preview" time and when someone applies it.

But we could also achieve the same by adding an explicit "seal" step. Rough sketch:

1. `createOpenBatchSpec(rawSpec)` -> get back id `bs1`
2.  Click URL to preview `bs1`, UI shows that it's still being processes
3. `createChangesetSpec(...)` -> get back id `cs1`
4. `addChangesetSpec(bs1, cs1)`
5. `createChangesetSpec(...)` -> get back id `cs2`
6. `addChangesetSpec(bs1, cs2)`
7. ...
8. `createChangesetSpec(...)` -> get back id `csN`
9. `addChangesetSpec(bs1, csN)`
5. `sealBatchSpec(bs1)` -> now nobody can add another changeset spec, UI shows that it's done executing
6. then: `applyBatchSpec(bs1)`

**Comment by eseliger** [comment]
I think this has been solved by SSBC in a more elegant way. Please reopen if you think this should still happen.
