### ISSUE TITLE
'View Repository' button with Chrome(ium) extension disappearing.

### ISSUE THREAD

**Issue by c-edw** [sourcegraph/sourcegraph#2162]
- **Sourcegraph version:** N/A (Extension 19.1.29.2106)
- **Platform information:** Chromium 71.0.3578.98

#### Steps to reproduce:

1. Install the Sourcegraph extension 
2. Navigate around various pages on GitHub
3. Observe that the `View Repository` button usually next to `Watch` is missing
![130535-2019-02-05](https://user-images.githubusercontent.com/38229097/52275208-c28d4b00-2946-11e9-9ac4-8e1bdde82872.png)

4. Refresh the page
5. Observe that the `View Repository` button is now visible
![130559-2019-02-05](https://user-images.githubusercontent.com/38229097/52275219-cfaa3a00-2946-11e9-8551-b1fb1f2534a2.png)

6. Continue to navigate around GitHub
7. Observe that the `View Repository` button disappears again

#### Expected behavior:
The `View Repository` button should remain visible and not only be visible after a page refresh.

#### Actual behavior:
The `View Repository` button disappears unless the page is refreshed, but later disappears again after continuing to browse GitHub.

**Comment by ryan-blunden** [comment]
Hi @c-edw, thanks for reporting this.

When you're navigating around GitHub and the `View Repository` button was not visible, did you observe that the `View File` button was not visible also?

If you could supply the URL for the page where you observed this, that would be a big help too.

**Comment by felixfbecker** [comment]
I have this issue all the time too

**Comment by nicksnyder** [comment]
@felixfbecker I am going to assign to you since you are able to repro (neither Isaac nor myself can repro consistently).
