### ISSUE TITLE
File explorer show button looks obstrusive/inconsistent in the redesign

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#21637]
(Reported by myself and Coury [in Slack](https://sourcegraph.slack.com/archives/C01TFNBHYCV/p1622029529079800))

This button doesn't feel like it fits into the design very well:

![image](https://user-images.githubusercontent.com/10532611/120487447-455b2f00-c3b6-11eb-98ad-4f789ea4acc8.png)

Compared to the "hide" button:

![image](https://user-images.githubusercontent.com/10532611/120487544-599f2c00-c3b6-11eb-8c07-3c4be91c9d7e.png)

I hacked together a quick alternative proposal that got the [designer Seal of Approval ™️](https://sourcegraph.slack.com/archives/C01TFNBHYCV/p1622639092170600?thread_ts=1622029529.079800&cid=C01TFNBHYCV):

![image](https://user-images.githubusercontent.com/10532611/120487701-79ceeb00-c3b6-11eb-81c3-056edd8ebe3f.png)

Thoughts behind it:
- Consistent with the collapse button in terms of icon, color and size, also consistent with the extension bar collapse button
- Neat little _tab_ that indicates the explorer is _hidden off-screen_ and you can _pull it out_ (also afforded by using the same background as the file explorer)
- Neat alignment with the repo title and not obstructing the rounded corner shape of the content container, instead of sitting square in the top-right corner

Specs:
- 2x2rem
- `--icon-color` color
- `--body-bg` background
- 1rem top margin to the top of the content container
- `--border-radius` border-radius top-right and bottom-right, 0 on the other corners
- Important: Added .5rem padding to the content container on the left, so it neatly aligns with the rev switcher and has padding on both sides and is not flush with the window frame on one side but not the other.

**Comment by AlicjaSuska** [comment]
Nicely done @felixfbecker Thank you!
