### ISSUE TITLE
Add metadata to search results

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#21636]
In the first iteration of the design refresh we’ve built an MVP for search results. The intent is to eventually display other data next to search results (eg. repo description, star count, last synced time for repos, last edited time for files, …). This requires backend changes (to expose the data).

The precise scope of the metadata we will display is still TBD.

![image](https://user-images.githubusercontent.com/539268/121432680-d3dc2d00-c92f-11eb-8812-53de03e067b8.png)

[Figma link](https://www.figma.com/file/J8MduuIBmHAdMFsohckpsi/Search-results-design?node-id=1%3A2270)

**Comment by rrhyne** [comment]
Closing in favor of this one. 

From that ticket: https://github.com/sourcegraph/sourcegraph/issues/21590

User testing reveals users experience confusion when encountering file and repo results.

Additionally, displaying additional data would help users resolve several use cases, such as selecting the most recently updated repository or determining when a file was last updated.

**Comment by camdencheek** [comment]
Repository metadata we currently have available:
- Description
- Language
- Created at
- Last updated at
- Fork
- Archived
- File count

Repository metadata we can add cheaply (we already have the data, we just need to expose it):
- Star count

Repository metadata we would need to fetch more information about (significantly higher effort):
- Fork count
- Open issues

File metadata we currently have available:
- Line count
- Content size

**Comment by rrhyne** [comment]
We can definitely move forward without fork and open issue data. They are certainly signals users may need, but I have no direct evidence, unlike some of the other data points.

**Comment by malomarrec** [comment]
This should not be A/B tested, it should be in both versions of the PLG A/B test.

**Comment by camdencheek** [comment]
@rrhyne Do you have a definitive list from the comment above that you want to add? I'm working on adding stars to the streaming API right now, and there are at least a few others it would be trivial to add while I'm at it. But I don't want to add things that won't be used because there are some performance implications to some of them.

**Comment by camdencheek** [comment]
As of #22032, all the repo metadata is added to streaming search results. In #22200, that metadata is added to the UI.

Next steps on this is getting file metadata (lines, bytes) and adding it to the UI

**Comment by lguychard** [comment]
Closing this in favour of more specific follow-up: https://github.com/sourcegraph/sourcegraph/issues/22255
