### ISSUE TITLE
order repository matches by star counts

### ISSUE THREAD

**Issue by rmmh** [sourcegraph/sourcegraph#21642]
#### Feature request description

Repository matched should be ordered by ranking instead of at random.   
#### Is your feature request related to a problem? If so, please describe.

For example, `r:kubernetes` should probably return `kubernetes/kubernetes` first, instead of the current results: 
![image](https://user-images.githubusercontent.com/211868/120496670-fcd25000-c37a-11eb-8fb6-a08c40502c4d.png)

#### Additional context

The repos table metadata has star counts for github repositories that could be used for ordering these results.

**Comment by tsenart** [comment]
This is done.
