### ISSUE TITLE
codeintel: Auto-index based on repo groups

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#21645]
We currently auto-index based on:

- repositories having an auto-index configuration in the database, and
- repositories with a specific pattern of code intelligence events

We should instead be ensuring that we index (and dependency index) the repositories which are part of repo groups. On Cloud, this provides a very good set of repositories that are likely to be actively used (in place of a stargazer count, which we don't have a concrete timeline for).

We should remove the indexability updater (and related concepts in the database layer) and simply iterate through the repo group repositories inside of the index scheduler.

**Comment by tjdevries** [comment]
Also probably can be closed? Do we need follow up issues or are the ones I made from the PR enough?

**Comment by tjdevries** [comment]
Closed by #21982
