### ISSUE TITLE
Gitserver pub/sub

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#21641]
Most of the CPU on frontend is dealing with trying to keep our systems up-to-date. This issue is about fixing that by replacing polling with pub/sub. instead of having to ask every repository what’s your latest revision constantly, you get told when it changes, and can keep local state on Sourcegraph.

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket,  please tell use how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
