### ISSUE TITLE
Home page iterations

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#21648]
The home page can be improved with more relevant examples which speak to common objections we've heard from users and with video content that could give users a better ramp in to search. 

Figma:
https://www.figma.com/file/5CRqR5RVgv0HJ5A06YQ1uT/Homepage-updates.-New-examples-%2B-video?node-id=8%3A3665&viewport=429%2C406%2C0.3843750059604645

**Comment by lguychard** [comment]
@rrhyne having merged a new iteration of the homepage, should we close this and track future iterations in separate issues?

**Comment by lguychard** [comment]
@rrhyne closing this for now. Let's track future work on the homepage in follow-up issues.
