### ISSUE TITLE
Search snippets with user input

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#21653]
@lguychard proposed evolving the behaviour of snippets so as to allow for users to discover the search syntax. I can click a snippet, which fills the search bar with `filter:PLACEHOLDER` and when I start typing it modifies the placeholder. 

I think there should be a visual indication that users can start typing to replace the placeholder, we should brainstorm design options here.

Examples:
- "search diff content" -> `type:diff PATTERN_TO_SEARCH_IN_DIFF_CONTENT`, where `PATTERN_TO_SEARCH_IN_DIFF_CONTENT` is preselected and I just have to start typing to replace it.
- "find repository by name" -> `repo:REPO_NAME_REGEX`

This is a follow up to #21545.

**Comment by malomarrec** [comment]
Blocked on autocomplete functionalities, that will be built for the to #21539

**Comment by fkling** [comment]
Just for completeness, the way it works with search references is exactly as described in the first example (the placeholder text is pre-selected). For filters with suggestions though we use an empty value and trigger the autocompletion logic.
