### ISSUE TITLE
Improve how users interact with search types

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#21656]
#### Problem

Search types are hard to use. Many users stumble on [`type:repo errors`](https://github.com/sourcegraph/sourcegraph/issues/19239). Understanding how your interpreted search pattern changes with a `type:` added to your query is non-intuitive. As such, exposing search types prominently in the sidebar risks causing confusion from users who misunderstand how they work.

![image](https://user-images.githubusercontent.com/1741180/120517923-451c5d00-c3d1-11eb-8cd8-7621b39d0665.png)

Additionally, the phrase "search types" cover two very different use cases that are essentially impossible to discover for users:

(A) As a user, I would like to map the results of my query to a given type, aka "only show me repository results". This is best solved by `select:`, which is not discoverable except through filter autocomplete at present.
(B) As a user, I would like to _filter on data specific to a result type_, aka "I want to search a repo by name". The recommended way to solve this can be very different depending on the result type: `repo:PATTERN` for repos,  but `type:diff PATTERN` for diffs.

#### Proposed solution

1. Remove the current "search types" sidebar section.
2. Feature `select:` prominently in the search reference panel, and don't feature `type:`, to promote the recommended way to solve (A)
2. Introduce search snippets with pre-selected placeholders (#21652) to solve use case (B):
    - "Search a repository by name", inserts `r:REPOSITORY_REGEX_PATTERN`
    - "Search a file by path or name", inserts `f:FILE_REGEX_PATTERN`
    - "Search diff contents", inserts `type:diff PATTERN_TO_SEARCH_IN_DIFF_CONTENT`
    - "Search commit messages", inserts `type:diff PATTERN_TO_SEARCH_IN_COMMIT_MESSAGES`
3. Bonus: show these snippets on the home page, to help users successfully get what they want out of their first search.

Additional thoughts: should the snippets mentioned in 2. be "built-in snippets", existing outside of the settings cascade? They might be useful on Enterprise as well, but it would be strange to have them pre-baked into Global Settings, and potentially overrideable there.

**Comment by malomarrec** [comment]
@lguychard I see very well how this works for `select:repo, but how does it work for other types?
Eg.
[auth type:symbol](https://sourcegraph.com/search?q=context:global+auth+type:symbol&patternType=literal) works well, [auth select:symbol](https://sourcegraph.com/search?q=context:global+auth+select:symbol&patternType=literal)

Besides there is no select for `diff`, `commit`
Shall we promote `select` for `repo` and `file`, and keep type for `path`, `diff`, `commit`?
Or to remove the cognitive burden on users, have `select:diff, commit` be an alias for `type:diff, commit`?

**Comment by lguychard** [comment]
> I see very well how this works for `select:repo`, but how does it work for other types?
> - auth type:symbol works well, auth select:symbol does not.

Again, this boils down to `type:` and `select:` functioning in a fundamentally different way.
- `type:`: changes the INPUT kind of a search (but also influences the OUTPUT kind)
- `select:`: changes the OUTPUT kind of a search

Thus:
- `auth type:symbol`: match the pattern `auth` against symbol names. Return symbol results.
- `auth select:symbol`: match the pattern `auth` against code, repo names, symbol names, path names. Filter to return only symbol results. This search doesn't work well because we hit an internal limit while searching _all of these different input types_, before having found symbol results to return (eg. we probably found 1000+ code results for "auth"). There is admittedly a nasty interaction between `select:` and internal limits there.

A more useful query:
- `auth type:symbol select:symbol.class`: match the pattern `auth` against symbol names. Filter to return only _a specific type of symbol_

Suggested fix:
- We don't promote all values of `select:` in the reference (just the existence of `select:`, and its purpose: mapping results to a specific type)
- We promote "search symbols" (inserts `type:SYMBOL SYMBOL_NAME`) in snippets if we want to surface symbol search

> There is no select for diff, commit

There is no value of `select:` that performs similarly to `type:diff` (because their purpose is different), but there are in fact values of `select:` that are extremely useful in conjunction with `type:diff`. For example, surfacing only changes in _added_ lines, or _removed_ lines:

[`repo:github\.com/sourcegraph/sourcegraph$ type:diff select:commit.diff.added HACK case:yes`](https://sourcegraph.com/search?q=context:global+repo:github%5C.com/sourcegraph/sourcegraph%24+type:diff+select:commit.diff.added+HACK+&patternType=literal&case=yes) (only surfaces diffs that _added_ "HACK")

Suggested fix:
- We make the search reference to be aware of the query
- We suggest `select:commit.diff.added`, `select:commit.diff.removed` when running a `type:diff` query
- We suggest  `select:symbol.class`, `select:symbol.function` when running a `type:symbol` search.

> remove the cognitive burden on users, have select:diff, commit be an alias for type:diff, commit?

We should not do this. As exposed above, the semantics of `select:` are very different to those of `type:`, and we should preserve that. You can [read more here](https://docs.google.com/document/d/1_m63fsBMAtqaq3GA_aMzKUPxD3yxTy8d12lJE6qN6PU/edit#bookmark=id.dg8mylyfyn0g).

**Comment by rrhyne** [comment]
I think this is a good start to the proposed solution:

https://www.figma.com/file/i2W27agZb7dlKJkRXQmCNd/Improve-how-users-interact-with-search-types-(%2321656)?node-id=0%3A1&viewport=756%2C521%2C1

One note: if we surface snippets at this level (I'm a big fan of this approach, it's one of the first things I proposed when I got here), we should also probably work on their usability a bit. Mostly by making it more clear how to add and remove them.

**Comment by rrhyne** [comment]
![image](https://user-images.githubusercontent.com/539268/126164594-a9dc8c5a-753c-4caf-9fa8-3fa8cc5894a6.png)

**Comment by lguychard** [comment]
Update: this content does not have to be backed by snippets, we can re-introduce the old types panel, with new content. If later we want to roll this into snippets, we can. This allows us to decouple this from fixing snippets to our liking.

**Comment by rrhyne** [comment]
[Figma](https://www.figma.com/file/i2W27agZb7dlKJkRXQmCNd/Improve-how-users-interact-with-search-types-(%2321656)?node-id=0%3A1&viewport=1253%2C3355%2C1.1458420753479004) has been updated to present the old types panel with new content:

![image](https://user-images.githubusercontent.com/539268/126419323-759eb3d0-1132-4d54-bca9-512a9399b003.png)

@lguychard can you all sign off on the searches and labels. I reduced your symbol search to simply type:symbol to make the feature more useful. 

@fkling this is ready as soon as Loic oks it.

**Comment by lguychard** [comment]
Looks good to me!

**Comment by fkling** [comment]
Should clicking on the entries that add/change `type:` trigger the search immediately, like the old panel did, or should it also work like search references does, i.e. updating the query but not running it?

**Comment by rvantonder** [comment]
> Should clicking on the entries that add/change type: trigger the search immediately, like the old panel did, or should it also work like search references does, i.e. updating the query but not running it?

I think your second point leads to the same answer that came to my mind: right away, if a pattern exists. But if a pattern doesn't exist yet...

> If the query is empty, wait and allow the user to provide the search term, otherwise trigger the search immediately.

Then yeah, agree with this ^. I actually think the chances are high that the query is empty when someone clicks these.

**Comment by fkling** [comment]
@rvantonder 

> I actually think the chances are high that the query is empty when someone clicks these.

How? The search sidebar is only shown on the search results page, so a query must already exist... or am I missing something? (that doesn't mean that I expect this to always be the case, I want to understand what the current situation is)

**Comment by rvantonder** [comment]
I was unclear, sorry. To clarify:

~that the query is empty~ that the query exists without a pattern

For example, let's say, someone navigates to a repo for the first time, like [for sourcegraph](https://sourcegraph.com/github.com/sourcegraph/sourcegraph), or ends up there after searching, or navigates to a repo/file, then a query might be something like:

`repo:foo` or `repo:foo file:bar`

Now they see these options on the left presented. They click any one of those (find a symbol, ...). What happens if we just append `type:symbol`?

- [no results](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+type:symbol&patternType=literal)

Not ideal. We can change this (either have our backend assume this is any symbol, so regex `.*`) or deal with this on the UI side.

I what happens for `type:commit` and `type:diff` without a pattern, and here we'll just show everything, so this is actually OK.

**Comment by fkling** [comment]
Draft PR: #23170 . I still have to work on the repo button, that requires some refactoring of the code I built for search references (so that I can reuse the placeholder logic stuff).

**Comment by rrhyne** [comment]
> Should clicking on the entries that add/change type: trigger the search immediately, like the old panel did, or should it also work like search references does, i.e. updating the query but not running it?
> 
> I think given that people can only go to that page after they searched something (i.e. the query input isn't empty), triggering the search right away makes sense.
> 
> In the long term, and if we expose those links elsewhere, it would make sense to be intelligent about this: If the query is empty, wait and allow the user to provide the search term, otherwise trigger the search immediately.

This generally sounds right, but I think a click on a value that does not have a replacement should run the query, even if it isn't a good query.  Here's why: when clicking repo there is a replacement highlighted. There is a clear expectation on the user and a visual indication they should do something. If the query is empty, there is no indication. The user may be confused as to why nothing happened. I'm guessing a bit here, so trying it out may convince me otherwise.

**Comment by fkling** [comment]
https://github.com/sourcegraph/sourcegraph/pull/23170 is ready for review.

**Comment by lguychard** [comment]
@fkling linked PR has been merged. Should we close this, and track future improvements in follow-up issues?

**Comment by benvenker** [comment]
Following up on this. @fkling or @lguychard, can/should we close this and track in a subsequent issue?

**Comment by lguychard** [comment]
We should close this.
