### ISSUE TITLE
Unclear and hard to discover indexed search documentation

### ISSUE THREAD

**Issue by KattMingMing** [sourcegraph/sourcegraph#2165]
Our documentation about indexed search isn't easily found and doesn't clearly communicate to our users what branches are indexed and why they are indexed.

Current documentation to indexed search:
- https://docs.sourcegraph.com/user/search
    - Only discoverable from blog posts and footer and searching for "index search.
- https://docs.sourcegraph.com/admin/search
    - Only discoverable by searching for "index search"

Possible improvements to documentation:
- Add more detail about differentiating Sourcegraph search features to https://docs.sourcegraph.com/ or link to search documentation. 
- Top level section that explains how Sourcegraph search is different which emphasizes: **with no indexing required** 
- Add a section on "user/search" and "admin/search" for when indexed search should be used and provide recommendations for when indexing should be enabled (X number of repositories or repositories over a certain size?)

**Comment by sqs** [comment]
Reassigning to a member of the search team (@attfarhan) because this involves purely technical documentation. Also assigning to me for the product marketing parts (I plan to revise the search help page; right now https://docs.sourcegraph.com/user/search is a weird mix of marketing and technical).

**Comment by KattMingMing** [comment]
Adding to milestone based on convo here: https://sourcegraph.slack.com/archives/C0W2E592M/p1553205756018900

**Comment by ryan-blunden** [comment]
@attfarhan Is this still on track for 3.3?

**Comment by ijt** [comment]
Closing this as obsolete because indexed search is now enabled by default for all deployment styles.
