### ISSUE TITLE
Introduce a way to add search fragments to the Monaco search field with pre-selected placeholders

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#21652]
For the search reference (#21539) and search snippets (#21545), a useful pattern would be the ability to add a query fragment to the search field, with a pre-selected range, for instance:
- Clicking a UI element adds `repo:REPO_REGEX_PATTERN` to the search field
- The placeholder value, `REPO_REGEX_PATTERN` is pre-selected (and it is obvious that it is pre-selected)
- Starting to type immediately overrides the placeholder

**Comment by fkling** [comment]
I have a very rudimentary version of this working in my search reference PR (#22236). It consists of adding a Monaco selection to `QueryState`. That might be good enough as a start, but I might also implement a more complete API as part of that PR.

**Comment by malomarrec** [comment]
Assigning to @fkling as this is already part of search reference work. Feel free to close if needed.

**Comment by lguychard** [comment]
@fkling I'll close since a basic version of this was merged as part of search reference, and we can iterate on it as needed.
