### ISSUE TITLE
Insights button/page is "broken" in open source and sourcegraph.com

### ISSUE THREAD

**Issue by fkling** [sourcegraph/sourcegraph#21654]
From my understanding, Code Insights is an experimental enterprise-only feature.

If I run the open source version (`dev/start.sh`) locally, I can see the Insights nav item but going to that page shows me a GraphQL error:

![2021-06-02_14-00](https://user-images.githubusercontent.com/179026/120498251-5fe5d600-c3bf-11eb-9ef4-4d4787e87538.png)

This happens in the current design and in the redesign.

It works as expected when I start `enterprise/dev/start.sh`.

---

Related to that (but I'm happy to create a separate issue): Even though I don't have Insights enabled, I can see the navigation entry on  https://sourcegraph.com/. Navigating to it shows this though:

![2021-06-02_16-27](https://user-images.githubusercontent.com/179026/120517511-d50dd700-c3d0-11eb-81a1-1e7a60e0c969.png)

The button is only visible in the redesign, but going to https://sourcegraph.com/insights directly triggers the same issue in the current design.

**Comment by pdubroy** [comment]
Closing since this appears to be fixed now.
