### ISSUE TITLE
Open batch changes marketing page in a new window on sourcegraph.com

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#21660]
Currently, for users of sourcegraph.com/search, the batch changes marketing page opens in the same window as the application.

As the marketing page is not connected to the application it is unaware the user is signed in or out, which can be confusing. It is also difficult to get back to the application from the marketing site. 

Until the [getting started ticket](https://github.com/sourcegraph/sourcegraph/issues/21158) is done, open the marketing site in a blank window.

**Comment by umpox** [comment]
I believe this should now be fixed through https://github.com/sourcegraph/sourcegraph/pull/21708 and https://github.com/sourcegraph/sourcegraph/pull/21729

**Comment by umpox** [comment]
Closing, let me know if this still needs work
