### ISSUE TITLE
fix postgres deployment in dogfood 

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#2166]
See https://github.com/sourcegraph/infrastructure/pull/1139

sourcegraph.sgdev.org can't be updated past https://github.com/sourcegraph/sourcegraph/commit/e19f9d1b8ef6103d1bd6d5d4192a6975aecdd2f1 until this issue is fixed.

**Comment by tsenart** [comment]
This is done.

**Comment by ggilmore** [comment]
Closed in https://github.com/sourcegraph/infrastructure/commit/51d3982f1bf7143d8480efb6e65f4860a22ca3cc
