### ISSUE TITLE
jaeger broken in docker compose - trace id not found

### ISSUE THREAD

**Issue by adeola-ak** [sourcegraph/sourcegraph#21677]
- **Sourcegraph version:** compose 3.27.4
- **Platform information:**  

#### Steps to reproduce:

1. run a search
2. look for trace ID in dev tools, run trace in jaeger 

#### Expected behavior:
see traces in jaeger UI

#### Actual behavior:
jaeger returns a 404 of trace id not found for several traces

**Comment by adeola-ak** [comment]
@daxmc99

**Comment by adeola-ak** [comment]
customer slack thread https://sourcegraph.slack.com/archives/C015JREMBTR/p1620752207002600 
he finds the trace id and is told in jaeger that it is not found

**Comment by daxmc99** [comment]
Root cause issue: Not setting ENV var similiar to https://github.com/jaegertracing/jaeger/blob/e7d7eb76a5e44c6bb47a6c03191a566b62a3a33e/cmd/all-in-one/Dockerfile#L65

**Comment by abeatrix** [comment]
Confirmed that adding `SAMPLING_STRATEGIES_FILE=/etc/jaeger/sampling_strategies.json` to the docker compose yaml file resolved the issue for me.
![image](https://user-images.githubusercontent.com/68532117/127560548-a07841f0-70e1-40f6-9670-2c344dbc88b9.png)
![image](https://user-images.githubusercontent.com/68532117/127560598-599bafc2-864f-42b6-9e4a-aaaf922c6cad.png)
