### ISSUE TITLE
Search snippets metric

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#21682]
### Problem
We are going to be iterating on several versions of snippets, but we don't have a way to validate our changes.

### Proposal
We should track usage of snippets as a proxy for user value.
Add a "addedSnippet" metric that is sent every time a user clicks on a snippet.

This will be useful for 
#21545 
#21653 

![image](https://user-images.githubusercontent.com/25070988/120829840-28f9f680-c55e-11eb-95ad-f2bee18480c7.png)

**Comment by malomarrec** [comment]
@ebrodymoore I didn't find anything like this in Amplitude, so I' proposing to add it. Let me know if there are existing metrics, that don't show up in Amplitude.

**Comment by ebrodymoore** [comment]
@sourcegraph/search-product who would be responsible for adding logging to search snippet clicks? I don't think there's any logging on there currently

**Comment by limitedmage** [comment]
> @sourcegraph/search-product who would be responsible for adding logging to search snippet clicks? I don't think there's any logging on there currently

I can help out with this, what should the name of the event be?

Note that we already track the event `DynamicFilterClicked` for clicks on the sidebar and this includes search scopes/snippets (but there is no way to differentiate between scopes/snippets and *real* dynamic filters that come from the server). I think we should remove `DynamicFilterClicked` for snippet clicks and replace with the new event instead.

**Comment by ebrodymoore** [comment]
Thanks and agreed, we should get more descriptive with these. SearchSnippetClicked and SearchScopeClicked would be good ones!

**Comment by limitedmage** [comment]
@ebrodymoore to clarify, "search scopes" and "search snippets" are the same thing. "Scopes" is the old name used in the settings and "snippets" is the new names used in the sidebar UI.

**Comment by ebrodymoore** [comment]
@limitedmage ohhh got it haha. well as long as we can distinguish a click in one section of the sidebar from the other I think it's fine
