### ISSUE TITLE
DismissibleAlert close icon is off center for one-line alerts

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#21693]
On a multi-line DismissibleAlert, this looks good and is not weirdly centered.
![image](https://user-images.githubusercontent.com/19534377/120658964-32b02b00-c486-11eb-9784-b89b29ae7a9e.png)
On a single-line alert, however, this looks a bit odd, because it is just so slightly off-center. 
![image](https://user-images.githubusercontent.com/19534377/120659253-786cf380-c486-11eb-924e-8819f62870b2.png)

**Comment by rrhyne** [comment]
The dismissable should be centered when used as a single line.

**Comment by rrhyne** [comment]
@valerybugakov could you have a look at this issue?
