### ISSUE TITLE
Commit view displaying "Unexpected HTTP error: 500"

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#2169]
![screen shot 2019-02-05 at 12 20 14 pm](https://user-images.githubusercontent.com/133014/52301884-6b847780-2940-11e9-9667-373f3c14fb61.png)

- **Sourcegraph version:** Sourcegraph.com
- **Platform information:** Chrome 72.0

#### Steps to reproduce:

Go to https://sourcegraph.com/github.com/cruise-automation/webviz/-/commit/ab168d049b975098a550c312bd2494f6b90ad51c

If not a bug, then handling the error and displaying a user relevant message would be better.

**Comment by sqs** [comment]
Trace:  https://app.lightstep.com/sourcegraph-prod/trace?span_guid=32492911a647505a&at_micros=1550120839654440#span-59be948523dce271

Error: 

```
graphql: graphql: panic occurred: graphql: got nil for non-null "File2"
```
