### ISSUE TITLE
Extension buttons on diffs need redesign work

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#21716]
Full height extension buttons in the diff views (and other areas where these elements exist) should be redesigned. 

For example, the buttons in the panel at the top of diff views should be links instead. Figma:

https://www.figma.com/file/30vUPTo5zeoQXdj5c6478w/Extension-buttons-in-diffs?node-id=0%3A1&viewport=485%2C404%2C0.31086957454681396

**Comment by AlicjaSuska** [comment]
The [design](https://www.figma.com/file/30vUPTo5zeoQXdj5c6478w/Extension-buttons-on-diffs-need-redesign-work-21716?node-id=0%3A1) is ready for review. On top of the changes described above, I've added badges 'base' and 'head' (we've discussed it with the extensibility team some time ago as an improvement for the static bar). I've also changed the clickable content style to link.

**Comment by rrhyne** [comment]
That's a big improvement. Love the base/head badges.
