### ISSUE TITLE
Bug Report: UI autorefreshes caused incorrect search-results 

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#21721]
- **Sourcegraph version:** 3.25
- **Platform information:** K8s
- **Internal Slack:** [Thread](https://sourcegraph.slack.com/archives/CHEKCRWKV/p1622755246204300)

#### Steps to reproduce:

A user has located a bug in our UI where results from a frontend pod got replaced by results from another frontend pod as their kubernetes configuration does not support session affinity (_This means that every request from the sourcegraph UI could potentially hit a different front-end server_).

> The user hits frontend A, which gets one result within the query timeout. This is displayed to the user. Then Sourcegraph autorefreshes. The refresh hits frontend B, which has never heard of this query before. But this time it's a little slower than A, so it gets zero results within the timeout.

#### Expected behavior:
 it should either merge the results, or refuse to replace a longer list of results with a shorter list.

#### Actual behavior:
 The Sourcegraph UI javascript decides to show zero results, replacing the one result.

#### Suggestions from the user:

>  one possible fix is to change the UI code to avoid displaying the issue to the user. The other possible fix is to add a caching layer in between the front end and the back end, which would mean that front end servers can share results; this would also be better for perf in our (admittedly janky) configuration.

**Comment by limitedmage** [comment]
I'm more concerned about the report that the UI is autorefreshing, I'd like to learn more about how/why that is happening.

**Comment by keegancsmith** [comment]
Clarification on incorrect:
1. Wrong results
2. Different result ordering (ie the match counts remain the same)
3. Less/more results

(1) Wrong results I would find very surprising and would likely be a sign of a big bug.

(2) different result ordering is what I expect to happen. We have work on our short term roadmap to add "semi-deterministic" ordering of results. This would more than likely solve this problem for the majority of queries.

(3) less/more results is possible, especially if the frontend you have changed to has just started up and has some cold application caches. These application caches are shared between users, so this would be surprising. What scale is this customer at (how many repos)?

Background: We do some stuff in the frontend, but most of the heavy lifting is done by Zoekt and in that case we aggregate across the cluster so affinitiy is not an issue. So in practice affinity shouldn't be an issue (unless I am missing something around auth/user syncing/etc)

**Comment by abeatrix** [comment]
@keegancsmith Thank you for looking into this!
> What scale is this customer at (how many repos)?
20k repos

**Comment by keegancsmith** [comment]
> 20k repos

20k repos isn't much, so I wouldn't suspect it is due to cold application caches in the frontend. My suspicion is this is (2) listed above.

**Comment by abeatrix** [comment]
@keegancsmith (2) doesn't seem to explain why they are getting zero results when one result is expected (or I might not be understanding this correctly). 
Could this be related to https://github.com/sourcegraph/customer/issues/353?

**Comment by keegancsmith** [comment]
It could be related and is surprising. It would be _amazing_ if we had a trace of 1 result vs 0 results. But I realise that may be hard to collect. Even a trace of either may help point us in the right direction. Right now it is hard to do more without more information.

**Comment by stefanhengl** [comment]
Closing this since @abeatrix closed the linked issue.
