### ISSUE TITLE
Search input tooltips are broken in Firefox

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#21751]
Note the tooltip arrow:
![image](https://user-images.githubusercontent.com/539268/120844399-29759b80-c524-11eb-91d9-5f968f2fe225.png)

See converation here:
https://sourcegraph.slack.com/archives/C01TFNBHYCV/p1622827634220100

**Comment by rrhyne** [comment]
Editing to separate the icon size issue as it is present in Safari, but the tooltip issue is not.

**Comment by limitedmage** [comment]
This issue is not related to the design refresh and has been present for some time I think.
