### ISSUE TITLE
Log site ID on extensions request to dotcom registry

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#21776]
For analytics cross-checking, we want to log the Site ID on request for an extension. We **shouldn't** log IP address, just the extension ID (the way we do for pings) and the site ID. 

We should send this to bigquery.

**Comment by Joelkw** [comment]
It might also be worth it to send whether the instance has a valid license or not (and its plan type) so we can easily separate OSS from Free/Enterprise. 

[From Joe](https://sourcegraph.slack.com/archives/C022SPMNR0W/p1623041185092900?thread_ts=1622842325.091400&cid=C022SPMNR0W):

> I do not think we can tell if a build is unmodified reliably, but if you want to know if an instance has a valid license (don't know if we send back through pings today), we may able to send the license key along with the ping data?
Of course, sending the entire license key with every ping is a waste of bandwidth, we can instead just send the hash of the license key and compare it with what we have in dotcom DB (to do server-side verification).

**Comment by dadlerj** [comment]
Thanks for posting! Regarding the suggestion above, I'm not sure if that will work here. the "OSS vs. non-OSS" question is different from "does this instance have a valid license key". There are plenty of "free" (but non OSS) instances out there that have no license key, but _do_ still have an official build. 

Would it be possible to, like, hash the Docker image binary itself and send that back? Or if it's not being run via Docker, to return some environment variable that we can set to `false` in ./dev/start and `true` in ./enterprise/dev/start or something? Obviously someone could get around the latter, but if that's the best we can do, so be it.

**Comment by Joelkw** [comment]
@dadlerj Thanks for the thoughts! 

I imagine this could be done a few ways – am aware that non-OSS free instances might not have a license key; my understanding is that an instance is 1 of OSS | Free | Teams/Enterprise . We won't get to this until after the 3.29 release this month, so I'll let the team consider other technical solutions here, but confirming that the need is: "is this instance a known build of Sourcegraph?" where "Known build" = OSS OR [Sourcegraph Free/Teams/Enterprise] of each version.

**Comment by dadlerj** [comment]
Exactly, yes—OSS vs. non-OSS is the key question here. 

I think it is technically correct to say that an instance can be 1 of OSS | Free | Teams | Enterprise, but the right way of looking at it is probably that there are two distinct axes here (the product tier is one of them, and OSS vs non-OSS is the other... Though technically you can't have all of the combinations, it's probably still correct to think about it in these terms).
