### ISSUE TITLE
worker: migrate Batch Changes background jobs

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#21782]

**Comment by mrnugget** [comment]
Isn't this done, @eseliger?

**Comment by eseliger** [comment]
No, we're still running in repo-updater.

**Comment by eseliger** [comment]
Mostly done, with the exception of the changeset syncer which is pretty legacy and not so easy to move around.

**Comment by eseliger** [comment]
The syncer has it's own ticket so I am going to close this one.
