### ISSUE TITLE
Test plan for automatic Postgres upgrades in the server image

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#2179]
We'd like to test both the documentation and the automated upgrades.

Go to  https://github.com/sourcegraph/sourcegraph/blob/master/doc/admin/migration/3_0.md#bundled-postgres-upgrade and test automated and manual upgrades to `3.0.1-rc.3` coming from `2.13.6`, `3.0.0` and  ~`3.0.0-beta5`~ `3.0.0-beta.4`.

You can create a fresh install of each of these versions by running the correspondent Docker container. Ensure you clean-up your data directory between each test (e.g. `rm -rf ~/.sourcegraph`)

Here's a check-list for you to copy into a comment in this issue and tick as you go:

```
- [ ] Test manual upgrade from `2.13.6` to `3.0.1-rc.3`.
- [ ] Test manual upgrade from `3.0.0` to `3.0.1-rc.3`.
- [ ] Test automatic upgrade from `2.13.6` to `3.0.1-rc.3`.
- [ ] Test automatic upgrade from `3.0.0-beta.4` to `3.0.1-rc.3`.
- [ ] Test automatic upgrade from `3.0.0` to `3.0.1-rc.3`.
```

Part of #1404

**Comment by ggilmore** [comment]
I assume this includes checking for the k8s case as well?

**Comment by nicksnyder** [comment]
@ggilmore yes, can you please test k8s? You can tag `v3.0.1-rc.1` to make it easy to update the image tags.

**Comment by ggilmore** [comment]
@tsenart Are there manual upgrade steps for deploy-sourcegraph?

**Comment by nicksnyder** [comment]
@ggilmore Don't ask @tsenart, just read the documentation like a user and do what a user would do. If you end up doing the wrong thing and it doesn't work, then that is a bug in the documentation!

**Comment by ggilmore** [comment]
There is no section on the page for deploy-sourcegraph manual upgrades, which is why I asked.

**Comment by nicksnyder** [comment]
Then as a user I would conclude that no special steps are necessary for postgres upgrade. Test that!

**Comment by nicksnyder** [comment]
Food for thought:
Should we keep migration information separated by deployment type (sourcegraph/sourcegraph, sourcegraph/deploy-sourcegraph) or should we consolidate upgrade information in a single place in sourcegraph/sourcegraph

**Comment by ggilmore** [comment]
- ~[ ] Test manual upgrade from `2.13.6` to `3.0.1-rc.1` on K8s.~ N/A
- ~[ ] Test manual upgrade from `3.0.0-beta.5` to `3.0.1-rc.1` on K8s.~ N/A
- ~[ ] Test manual upgrade from `3.0.0` to `3.0.1-rc.1` on K8s.~ N/A
- [ ] Test automatic upgrade from `2.13.6` to `3.0.1-rc.1` on K8s.
- [ ] Test automatic upgrade from `3.0.0-beta.5` to `3.0.1-rc.1` on K8s.
- [ ] Test automatic upgrade from `3.0.0` to `3.0.1-rc.1` on K8s.

**Comment by nicksnyder** [comment]
- [ ] Test manual upgrade from `2.13.6` to latest insiders.
- [ ] Test manual upgrade from `3.0.0-beta.5` to latest insiders.
- [ ] Test manual upgrade from `3.0.0` to latest insiders.
- [ ] Test automatic upgrade from `2.13.6` to latest insiders.
- [ ] Test automatic upgrade from `3.0.0-beta.5` to latest insiders.
- [ ] Test automatic upgrade from `3.0.0` to latest insiders.

**Comment by ryan-blunden** [comment]
- [ ] Test manual upgrade from `2.13.6` to latest insiders.
- [ ] Test manual upgrade from `3.0.0-beta.5` to latest insiders.
- [ ] Test manual upgrade from `3.0.0` to latest insiders.
- [ ] Test automatic upgrade from `2.13.6` to latest insiders.
- [ ] Test automatic upgrade from `3.0.0-beta.5` to latest insiders.
- [ ] Test automatic upgrade from `3.0.0` to latest insiders.

**Comment by tsenart** [comment]
I just realized that since 3.0.0-beta.5 already runs Postgres 11.1, we don’t need to test the manual upgrade, only the automated one (which should be a no-op)

**Comment by nicksnyder** [comment]
@ryan-blunden The problem is that you didn't add `-v /var/run/docker.sock:/var/run/docker.sock:ro` as documented here:
https://docs.sourcegraph.com/admin/postgres#automatic-upgrades

@tsenart I am not surprised that Ryan missed this documentation just from reading https://github.com/sourcegraph/sourcegraph/blob/master/doc/admin/migration/3_0.md#bundled-postgres-upgrade. It isn't clear that it is required to click through the link.

There either needs to be an explicit call to action to read that link or that content needs to be inlined into the migration guide (I think I would prefer the latter).

**Comment by ryan-blunden** [comment]
Could the script/code check if the docker socket exists and if not, print an informative message with a link to the docs and exit nicely? 

I didn't see the link because of the noise from the Docker error.

**Comment by ryan-blunden** [comment]
Tried mounting the Docker socket (code from https://docs.sourcegraph.com/admin/postgres#automatic-upgrades) but that didn't succeed either. I've updated my comment with more info and a link to a pastebin to see the output.

I think it would be better if the script captured the stdout/stderr from the postgres upgrade process as it looks kinda scary seeing that amount of output.

Also, another thing which worried me was that the image came from a non-Sourcegraph dockerhub user - `=tianon/postgres-upgrade:9.6-to-11`.

**Comment by ggilmore** [comment]
I ran into https://github.com/sourcegraph/sourcegraph/issues/2192. I didn't realize until just now that this issue happens on a cluster, not just the upgrade process.

**Comment by tsenart** [comment]
> or should we consolidate upgrade information in a single place in sourcegraph/sourcegraph

@nicksnyder: This is the approach taken in this document. I feel it's easier to manage if it's all in one place.

**Comment by tsenart** [comment]
@sourcegraph/team: I had mistakenly asked you to test `3.0.0-beta.5`. That tag doesn't exist. Please use `3.0.0-beta.4`.

**Comment by tsenart** [comment]
> I'm not clear on how to test manual vs. automatic upgrades so I've put my results under the manual tests.

@ryan-blunden: I made the CTA [slightly more prominent](https://github.com/sourcegraph/sourcegraph/pull/2195/files#diff-db45bfa8d797d0c1697d11ff1a61bf50).

**Comment by tsenart** [comment]
All your feedback is addressed. Please test again with latest insiders image.

**Comment by nicksnyder** [comment]
I tagged `v3.0.1-rc.3` so please use that for testing moving forward.

**Comment by nicksnyder** [comment]
I finished testing automated and manual upgrade paths for the Docker image.

Only a few minor followup items, but none that block release.
- https://github.com/sourcegraph/sourcegraph/pull/2205
- https://github.com/sourcegraph/sourcegraph/issues/2203
- https://github.com/sourcegraph/sourcegraph/commit/91ca210595e4adcd978dcf0006fb37c8eab874ed (already cherry-picked into 3.0 branch)

**Comment by nicksnyder** [comment]
@ggilmore Found an issue that would prevent us from tagging the release for Kubernetes

https://github.com/sourcegraph/sourcegraph/issues/2206

**Comment by francisschmaltz** [comment]
Testing Details:
1. Create new instance on fresh ubuntu 18.04 VM.
1. Install Docker-CE
1. Start Sourcegraph in docker
1. Create admin account
1. Clone `gorrila/mux` `Sourcegraph/Sourcegraph`
1. Tried to upgrade

- [X] Test automatic upgrade from `2.13.6` to latest insiders.
- [X] Test automatic upgrade from `3.0.0-beta.4` to latest insiders.
- [X] Test automatic upgrade from `3.0.0` to latest insiders.

Ran into https://github.com/sourcegraph/sourcegraph/issues/2208 but images deployed and instance was usable.

**Comment by nicksnyder** [comment]
Tomas and I fixed the last remaining issue related to kubernetes, so I am going to tag 3.0.1

**Comment by slimsag** [comment]
I tested automatic upgrades from 2.13.6 and 3.0.0-beta.2.

I also tested in a deploy-sourcegraph-docker deployment, which hasn't yet been upgraded to postgres 11 -- and everything works fine there.
