### ISSUE TITLE
Connecting a code host results in two progress buttons being shown

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#21805]
#### Steps to reproduce:

1. Go to /settings/code-hosts
2. Connect with a code host with OAuth

#### Expected behavior:

The "disabled/loading" button state is shown for the "Connect" button.

#### Actual behavior:

The "Updating" progress button is also shown.

https://user-images.githubusercontent.com/6304497/121004121-942a0f80-c78e-11eb-96b9-4436f39c7cd4.mp4

**Comment by pdubroy** [comment]
Is this still an issue? I wasn't able to reproduce it.

Also, I suspect this is unrelated to the design refresh, so probably not a Frontend Platform issue. Please let me know if I'm wrong.

**Comment by artemruts** [comment]
Closing this one, I fixed this about a month ago. It was a Core App regression.
