### ISSUE TITLE
Remove corsOrigin (because it is likely not necessary anymore)

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#2182]
@ijsnow 	thinks corsOrigin is no longer necessary (see https://github.com/sourcegraph/sourcegraph/pull/1954#issuecomment-455713204). Removing corsOrigin (and the need for site admins to configure it) would nicely simplify the site admin setup process. It would also be a great removal of code and tech debt.

To be specific, corsOrigin is the ONLY remaining thing in site config that site admins would need to set up in the site activation flow planned for 3.1. If we can remove corsOrigin, it would mean *site admins do not need to modify site config to get activated*, which would be awesome. :tada:

So if possible, please remove it ASAP so we don't need to waste time incorporating it into site admin activation flow designs.

cc @beyang	for activation flow

**Comment by ijsnow** [comment]
It is indeed not required for browser extension use anymore, but we should confirm it is not required for the in page Phabricator script.

**Comment by lguychard** [comment]
I verified that `corsOrigin` is unfortunately still necessary for the in-page Phabricator script.

**Comment by beyang** [comment]
If it's only necessary for the in-page Phabricator script, it seems unnecessary to incorporate into the activation flow.

**Comment by sqs** [comment]
Correct. I will submit a PR tonight to remove it from all docs (and other things) where it is no longer necessary.

**Comment by sqs** [comment]
Submitted that PR: https://github.com/sourcegraph/sourcegraph/pull/2689
