### ISSUE TITLE
Bug Report: Extra line's added when there is no match when using ruplacer in Batch Changes

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#21840]
- **Sourcegraph version:** 3.28
- **Platform information:** All versions

#### Steps to reproduce:

1. Create a batch spec following the example listed in our docs using `ruplacer`: https://docs.sourcegraph.com/batch_changes/tutorials/search_and_replace_specific_terms#using-ruplacer-to-replace-terms-in-multiple-case-styles
2. Check the file changes

#### Expected behavior:
Terms in files are replaced accordingly.

#### Actual behavior:
The last line of code was removed and re-added despite there is no matches / changes
![image](https://user-images.githubusercontent.com/68532117/121098431-af0a7d00-c7aa-11eb-9944-747395c6b018.png)

Note: Running the job without ruplacer worked as expected.
![image](https://user-images.githubusercontent.com/68532117/121098619-1b857c00-c7ab-11eb-8e9a-8b8c3b90bd2b.png)

Link to Internal Issue: https://github.com/sourcegraph/customer/issues/382

**Comment by LawnGnome** [comment]
This turned out to be an issue in ruplacer itself; I've opened https://github.com/dmerejkowsky/ruplacer/pull/67 to (hopefully) fix this.
