### ISSUE TITLE
Breader slash improved with lighter font-weight

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#21866]
The slash we use to separate sections of the breader is currently the same weight as the header text. In Figma this is mostly okay, but it renders a little bit heavier in the browser, which makes the slash look a bit clunky.

<img width="508" alt="CleanShot 2021-06-08 at 14 30 48@2x" src="https://user-images.githubusercontent.com/6304497/121185523-7039fd00-c866-11eb-8702-51f00f2d0afd.png">

Changing the slash to `font-weight: 400;`makes the breader more refined.

<img width="287" alt="CleanShot 2021-06-08 at 14 33 33@2x" src="https://user-images.githubusercontent.com/6304497/121185599-834ccd00-c866-11eb-886f-2046f37ad986.png">

CC @AlicjaSuska @rrhyne

**Comment by AlicjaSuska** [comment]
I agree, let's do it :)
