### ISSUE TITLE
PackageHub: automatically add repositories on LSIF upload

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#21884]
Currently, the JVM packages external service type only supports adding dependencies manually through the site-admin JSON config UI. We should add support to add dependencies during LSIF uploading from the `packageInformation` vertexes.

**Comment by olafurpg** [comment]
Notes from an offline chat with @Strum355 

- we probably need to add a postgres table to list the `PackageInformation` vertexes that should have a corresponding git repo. Tentative schema:
    ```
    CREATE TABLE package_information_repos (
        manager text NOT NULL,
        name text NOT NULL,
        version text NOT NULL,
    );
    ```
- we should write to this table when processing LSIF `packageInformation` vertexes with the correct manager (maven, npm, jvm).
- we should read from this table when listing repos for JVM dependencies.

**Comment by efritz** [comment]
We [queue a dependency indexing job](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@ae1fda8da6d0fc7a7c0d955ad2e25b7dcb7db41b/-/blob/enterprise/cmd/precise-code-intel-worker/internal/worker/handler.go?L154) on LSIF uploads which are [handled](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@ae1fda8da6d0fc7a7c0d955ad2e25b7dcb7db41b/-/blob/enterprise/cmd/worker/internal/codeintel/indexing/dependency_indexing_scheduler.go?L54).

You can implement this behavior for JVM packages more easily by altering the [QueueIndexesForPackage](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@ae1fda8/-/blob/enterprise/internal/codeintel/autoindex/enqueuer/enqueuer.go?L91) method in the index enqueuer that also maps a package identifier to a repo name (right now we only [implement the logic for Go](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@ae1fda8/-/blob/enterprise/internal/codeintel/autoindex/enqueuer/enqueuer.go?L91)).

**Comment by efritz** [comment]
Related issues:

- https://github.com/sourcegraph/sourcegraph/issues/20835
- https://github.com/sourcegraph/sourcegraph/issues/20836
