### ISSUE TITLE
Add back 3.0-preview GitLab authz provider

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#2188]
This was removed in e9cd0086517d6fd2d069cf6239fdbebd37e21531 in favor of a pure-OAuth-based implementation, but it turns out the old version is needed to satisfy a customer's requirements. Add back the old impl, alongside the OAuth-based impl. The `authorization` field config object should specify which type ("oauth" or "auth-provider").

**Comment by sqs** [comment]
This is important for the customer https://app.hubspot.com/contacts/2762526/company/578600789.

@tsenart 	@keegancsmith 	@beyang 	Please figure out among yourselves how to handle this issue amid handing off ownership of repo perms from @beyang 	to @tsenart 	and @keegancsmith. cc @nicksnyder

**Comment by beyang** [comment]
This was fixed in https://github.com/sourcegraph/sourcegraph/pull/2236
