### ISSUE TITLE
[deploy-sourcegrah] psgql pod never becomes ready 

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#2192]
- **Sourcegraph version:** 
- **Platform information:** 

#### Steps to reproduce:

1. Deploy [3.0.1-rc.1](https://github.com/sourcegraph/deploy-sourcegraph/commit/073d2117bee03f39765249186dabbb42eb4bff10) to a cluster

#### Expected behavior:

The cluster is healthy.

#### Actual behavior:

The pgsql pod never becomes ready. `kubectl describe pod pgsql` says that it's failing the readiness check: 

```shell
$ kubectl describe pod pgsql-7fd9d6b8f5-cfn2c

  Warning  Unhealthy               17m (x6 over 18m)     kubelet, gke-geoffrey-cluster-tes-default-pool-727d0b15-r36p  Liveness probe failed: ./ready.sh: line 12: POSTGRES_PASSWORD: unbound variable
  Warning  BackOff                 9m23s (x23 over 15m)  kubelet, gke-geoffrey-cluster-tes-default-pool-727d0b15-r36p  Back-off restarting failed container
  Warning  Unhealthy               4m18s (x37 over 18m)  kubelet, gke-geoffrey-cluster-tes-default-pool-727d0b15-r36p  Readiness probe failed: /ready.sh: line 12: POSTGRES_PASSWORD: unbound variable
```

**Comment by tsenart** [comment]
@ggilmore: Seems to me that the default for new clusters is to not set a Postgres password for the created user at all. Is this intended?

**Comment by ggilmore** [comment]
@tsenart https://github.com/sourcegraph/sourcegraph/issues/2197
