### ISSUE TITLE
Scrolling on search filter sidebar, scrolls results content when initial bounds are reached

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#21941]
### Problem

When scrolling on a filter section in the sidebar, when the user reaches the bounds of that section's scrollable area, the scroll switches to the search results.

https://user-images.githubusercontent.com/6304497/121393592-ca16f180-c950-11eb-8559-681b277c2848.mp4

This feels like an undesirable interaction outcome, because an action that at one point affected a targeted area inexplicably begins to affect a different area. (I had to do this a few times to understand what was happening and that it wasn't simply a weird bug causing double-scrolling.) 

This isn't "uncommon" behaviour—for example, it happens on GitHub itself:

https://user-images.githubusercontent.com/6304497/121394146-56c1af80-c951-11eb-9bea-f2e940a2ebb1.mp4

However, since the scrolling areas in the search sidebar are so relatively short, it's easier to encounter the scrolling behaviour here more frequently.

### Potential solutions

Two possible solutions that come to mind:

1. Search results should only scroll when the cursor is over the results section. No
2. Sidebar shouldn't (initially) have scrollable areas and should instead use sticky scrolling, much like Twitter. If the user clicks to show more for a section, then use a scrollable area. At that point, there's enough content for it to feel more purposeful, like in the GitHub example above.

https://user-images.githubusercontent.com/6304497/121394520-b5872900-c951-11eb-98f1-f5fc6d198207.mp4

CC: @rrhyne

**Comment by camdencheek** [comment]
The filters sidebar has been redesigned twice since this was opened, and it no longer has individually-scrollable elements. Closing as no longer relevant
