### ISSUE TITLE
Remove stats button from search results

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#21944]
The stats experimental feature is underdeveloped. Crafting a query to get a successful result can be difficult. This is proven to be frustrating in usertesting. Now that the stats button is much more prominent in the UI, this issue is likely to get worse. 

Remove the stats button from search results until the feature can be further developed. 

NOTE: Insights relies on the stats page in some of its links, so do not remove the entire feature. 

![image](https://user-images.githubusercontent.com/539268/121409061-e8133080-c915-11eb-83dd-419635ef070f.png)

**Comment by limitedmage** [comment]
@sourcegraph/code-insights or @sourcegraph/extensibility  do any of you have the bandwidth for this? Looks like this gets populated by some sort of extension, not by the search results page.

**Comment by felixfbecker** [comment]
It's registered with this function from within the web app (not an extension): https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/search/stats/contributions.ts#L29:41 (found with [this code search](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+%5CbStats%5Cb+lang:TypeScript+&patternType=regexp&case=yes))

Also looks like there is a feature flag for it that is off by default, and it's enabled only on sourcegraph.com in Global settings. I just disabled that so we don't need to make a code change.

**Comment by felixfbecker** [comment]
Actually didn't disable it because our Global settings are in a file in our deployment repos, can't edit through the web UI. I can do this tomorrow or if you want feel free to do it today @limitedmage

**Comment by muratsu** [comment]
Once disabled, should we migrate this to an experimental extension like [search exports](https://github.com/sourcegraph/sourcegraph-search-export)?

**Comment by limitedmage** [comment]
> Once disabled, should we migrate this to an experimental extension like [search exports](https://github.com/sourcegraph/sourcegraph-search-export)?

I don't understand, these sound like unrelated extensions/features?

**Comment by muratsu** [comment]
I missed that it's a dependency for insights. My suggestion was to remove this feature from sg and to make a separate extension out of it. I shared the search exports one because I thought they are somewhat similar (from user perspective).

**Comment by felixfbecker** [comment]
@muratsu there are two parts here, the button, and the stats page it links to: https://sourcegraph.com/stats?q=context:global%20repo:^github\.com/sourcegraph/sourcegraph$%20test
The stats page is built in React in the web app, meaning it can't be moved into an extension. The button could be, but the benefit doesn't seem clear given 95% of the stats-related code cannot be moved to the extension 🙂

**Comment by rrhyne** [comment]
Can we address only the button as part of this PR? I was hoping this would be a very small issue we could correct now that the redesign is out.

**Comment by felixfbecker** [comment]
@rrhyne please see the two PRs above in the timeline, they do what you want :)

**Comment by rrhyne** [comment]
Ah, 'Disable "searchStats" feature' sounds like the entire feature goes away. Your team needs this though, so you would know! :D
