### ISSUE TITLE
"Manage repositories" row items don't have hover or focus states

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#21961]
#### Steps to reproduce:

1. Visit /settings/repositories/manage with a connected code host
2. Hover over a repository row item, and use keyboard to focus on a line item

<img width="961" alt="CleanShot 2021-06-10 at 09 05 21@2x" src="https://user-images.githubusercontent.com/6304497/121480108-02f3ac80-c9cb-11eb-8d0b-b7bd20ac4bdb.png">

#### Expected behavior:

I don't know if this was a change due to the redesign or an oversight earlier in the process, but these rows should have a background change on hover and focus.

Background color on hover should be equivalent to `--body-bg`.

Checkboxes should have visible outline when focused with the keyboard.

#### Actual behavior:

No indication of hover or focus state.

@AlicjaSuska is this frontend platform or core application?

**Comment by AlicjaSuska** [comment]
Core app implemented this layout, I think it'd be the easiest for them to fix :)

**Comment by RafLeszczynski** [comment]
fixed
