### ISSUE TITLE
Configurable Git clone timeout

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#21984]
#### Feature request description

Make the timeout on git clones configurable.

#### Is your feature request related to a problem? If so, please describe.

The timeout on the clone operation is limited to [1 hour](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/gitserver/server/server.go#L224:5).  This is a problem for large repositories (especially large Perforce depots).  The clone operation is killed.  Example:

```
t=2021-04-28T23:43:04+0000 lvl=warn msg="error cloning repo" repo=depot/tmos/tier2 err="failed to clone depot/tmos/tier2: clone failed. Output: Importing from //depot/tmos/tier2/@all into /data/repos/.tmp/clone-201466160/.git\nInitialized empty Git repository in /data/repos/.tmp/clone-201466160/.git/\nImport destination: refs/remotes/p4/master\nImporting revision 3481472 (100%)\n: signal: killed"
```

**Comment by unknwon** [comment]
Link to JIRA ticket: https://sourcegraph.atlassian.net/browse/COREAPP-107

**Comment by ryanslade** [comment]
@flying-robot I think you can close this right?
