### ISSUE TITLE
Sourcegraph.com going down prevents me from using code intelligence

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#2199]
I spun up an instance and couldn't use code intelligence. The extensions were enabled and everything, but there wasn't any code intelligence. As it turns out, this was because sourcegraph.com had intermittent issues serving extension bundles.

As a user I expect to be able to use my installed extensions regardless of Sourcegraph.com going down. @felixfbecker informed me that I should have used a private extension registry to ensure I was not dependent on sourcegraph.com, but:

1. There is no documentation anywhere telling me that I am relying on Sourcegraph.com unless I use a private extension registry
2. [The documentation](https://docs.sourcegraph.com/admin/extensions#publish-extensions-to-a-private-extension-registry) says I have to run `src extensions publish` for every extension I want. I do not feel like I should have to do this in order to ensure my instance is not reliant on Sourcegraph.com. Further, having Sourcegraph.com downtime also correlate into user extension downtime seems very bad to me.

I propose:

1. All Sourcegraph instances (enterprise or not) should have their own local cache of extensions which they serve from. i.e., the extensions still come from sourcegraph.com when not using a private registry -- but after being fetched the first time from sourcegraph.com that version of the extension is forever served from my sourcegraph.example.com instance.

**Comment by keegancsmith** [comment]
So rather make the private instance have a caching proxy to sourcegraph.com, rather than everyone speaking to sourcegraph.com?

**Comment by nicksnyder** [comment]
Assigning to @lguychard to triage. Backlogging for now since this isn't going to be fixed with 3.1

**Comment by ryan-blunden** [comment]
Removing the `docs` label until a solution is agreed upon.

**Comment by felixfbecker** [comment]
@ryan-blunden shouldn't we document the status quo before implementing any complex technical solution like a cache?

**Comment by sqs** [comment]
In 4.0, we deprecated the extension registry, so instances no longer have this dependency on Sourcegraph.com. This problem is not 100% resolved because the extension registry is not fully removed, only deprecated, and many customers will remain on older versions, but the solution is clear, so I'm going to close this.
