### ISSUE TITLE
Groovy code intelligence

### ISSUE THREAD

**Issue by joemccall86** [sourcegraph/sourcegraph#22]
Support Groovy on Sourcegraph

**Comment by beyang** [comment]
We could potentially use the Groovy language server here: https://github.com/palantir/language-servers.

**Comment by mredding10** [comment]
This would be really useful for debugging & searching through Gradle config.

**Comment by beyang** [comment]
This should be very doable now via the basic code intel extensions. Someone familiar with Groovy syntax would simply have to add an entry to this array: https://github.com/sourcegraph/sourcegraph-basic-code-intel/blob/ab57b346e4c85fff20afcc2fb187268fffe04dab/languages.ts#L46-L77.

**Comment by ryan-blunden** [comment]
@joemccall86 @mredding10 [Groovy code intelligence](https://sourcegraph.com/extensions/sourcegraph/groovy) is now supported.
