### ISSUE TITLE
Sourcegraph docker image list polluted with builds from CI

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#220]
https://hub.docker.com/r/sourcegraph/server/tags/

This makes it harder for end-users to see tagged releases.

**Comment by keegancsmith** [comment]
So CI and our CD pipelines should push elsewhere for the individually tagged. This is what we did before when we used gcr. cc @beyang

**Comment by beyang** [comment]
Yeah I agree. How about `sourcegraph/server-dev` for non-release images?

**Comment by slimsag** [comment]
I think it is also reasonable that some user might want to use a more recent tag than our latest `insiders` version but ALSO remain pinned to a version _they_ deem stable. So I think ideally they could still find these.

What if instead we made `sourcegraph/server` the location for release images, and `sourcegraph/insiders` the location for the insiders version and all of these untagged release images?
