### ISSUE TITLE
Change "Remove" button to text link instead of button in settings

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#22015]
On the following pages, we use buttons with a mix of `btn-link` and `btn-link px-0` for the "Remove" action:

- Code host connections
- Sign in connections
- Batch changes settings

<img width="909" alt="CleanShot 2021-06-11 at 15 50 29@2x" src="https://user-images.githubusercontent.com/6304497/121696904-d3c56400-cacc-11eb-9aa1-03f5cc2e2aa9.png">

<img width="1001" alt="CleanShot 2021-06-11 at 15 50 35@2x" src="https://user-images.githubusercontent.com/6304497/121696911-d4f69100-cacc-11eb-8fe9-e969597c9677.png">

This results in inconsistent spacing on the right edge of the rows, where there's extra space on the right side of the `Remove` label.

**Expected outcome:**

Ideally, there's no space on the right side of the the `Remove` label when that action is on its own.

**Thoughts on solving this:**

- Since removing padding only on the right side of these buttons would result in a strange shape for the focus outline, that's not a good solution on its own.
- Regular text links are an option (@eseliger notes that'd be done with an `<a>` tag and would need `event.preventDefault()`)
- Buttons with `btn-link` and `p-0`, which we use on the `/settings/emails` page, are another option (@felixfbecker notes : "From a semantics and accessibility point of view this should probably still remain a `<button>`, assuming this triggers an action and doesn't navigate anywhere. If it was an `<a>` it would need `role="button"` added and so on. So I would naturally go with `<button>` + `px-0`  class. But if this is something you just wanna do for all these text-like buttons, we may just wanna set `padding-left/right: 0` globally for them.")

I'm not thrilled about globally removing the padding on `btn-link`, because it serves a role when adjacent to normal buttons. For example, the `Remove` button on the third row of the batch changes needs the padding to maintain proper spacing with the actual `View public key` button:

<img width="1175" alt="CleanShot 2021-06-11 at 16 26 10@2x" src="https://user-images.githubusercontent.com/6304497/121702054-d24a6a80-cad1-11eb-8b0b-64a0bd1faccf.png">

**Comment by pdubroy** [comment]
@quinnkeast Can you clarify what the desired final state is here? It's not clear to me from what you've written.

**Comment by quinnkeast** [comment]
> @quinnkeast Can you clarify what the desired final state is here? It's not clear to me from what you've written.

Sorry, @pdubroy! I've re-written the description for clarity. Does it make more sense now?

**Comment by 5h1rU** [comment]
@quinnkeast I'm checking the behavior of the remove button in the cloud instance, and remove is already a "link" button.
