### ISSUE TITLE
Monaco theme should use CSS variables

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#22016]
Even though [Monaco itself doesn’t support CSS variables](https://github.com/microsoft/monaco-editor/issues/2427), we can try to use `getComputedStyle` to get the value of CSS variables at runtime when creating the Monaco themes. See https://github.com/sourcegraph/sourcegraph/pull/21988#discussion_r649778421

**Comment by benvenker** [comment]
@limitedmage is there still work here? I see two related PRs merged...

**Comment by limitedmage** [comment]
@benvenker Yes, there's still potential to improve this. But the priority is very low. This was top-of-min when doing redesign since we changed all the colors and changing the Monaco colors ended up being very painful. See https://github.com/sourcegraph/sourcegraph/pull/21988#discussion_r649778421 for a suggested avenue of exploration.

**Comment by benvenker** [comment]
Got it, thanks.

**Comment by camdencheek** [comment]
With the planned migration to CodeMirror, is this still relevant?

**Comment by limitedmage** [comment]
@camdencheek No, we should close this issue if we never plan to address this and permanently move to CodeMirror.
@fkling Can you confirm CodeMirror lets us use CSS variables directly?

**Comment by fkling** [comment]
@limitedmage I haven't tested it for themes that are declared in JavaScript, but the CodeMirror DOM can easily be styled with stylesheets (and thus CSS vars), which is what I've done in the current experiment.

**Comment by limitedmage** [comment]
This is awesome; in that case, we can close this issue once we definitively decide to disable Monaco.

**Comment by limitedmage** [comment]
Actually, I'm closing it now and we can reopen it if we ever decide (hopefully not) to keep Monaco
