### ISSUE TITLE
Search for different token types

### ISSUE THREAD

**Issue by aisbaa** [sourcegraph/sourcegraph#2201]
I really like there is a way to do symbol search (variable, function, class etc.). 
- Would it be possible to extend it with more types like comment, doc-comment, keyword, identifier?
- Would it be possible to allow users to specify symbol type?

For example: I want to see how often `sourcegraph` is mentioned in the code base. Here's what I've tried and how that went:

- `-repo:sourcegraph sourcegraph` really fast, but returns a lot of comments.
- `-repo:sourcegraph sourcegraph count:10 -type:symbol` not supported.
- `-repo:sourcegraph sourcegraph count:10 type:symbol` timed out with 504 status from frontend, also tried to search for `add type:symbol` and it was fine.

**Comment by beyang** [comment]
Waited 40 minutes for this to transfer, giving up. Going to transfer manually.
