### ISSUE TITLE
insights: reduce commit indexer load on gitserver

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#22035]
The insights commit indexer currently retrieves all of the commits for a specific repository at once. This may cause gitserver to sit at 100% CPU for long periods of time, and could have an impact on the rest of Sourcegraph.

Possible options:
1. Paginate history requests
2. Rate limit history requests

**Comment by chwarwick** [comment]
Implementing approach defined in https://github.com/sourcegraph/sourcegraph/issues/33294
