### ISSUE TITLE
Search for different token types

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#2204]
This is from @aisbaa:

I really like there is a way to do symbol search (variable, function, class etc.). 
- Would it be possible to extend it with more types like comment, doc-comment, keyword, identifier?
- Would it be possible to allow users to specify symbol type?

For example: I want to see how often `sourcegraph` is mentioned in the code base. Here's what I've tried and how that went:

- `-repo:sourcegraph sourcegraph` really fast, but returns a lot of comments.
- `-repo:sourcegraph sourcegraph count:10 -type:symbol` not supported.
- `-repo:sourcegraph sourcegraph count:10 type:symbol` timed out with 504 status from frontend, also tried to search for `add type:symbol` and it was fine.

**Comment by beyang** [comment]
From @sqs:

This is a great feature request.

> comment, doc-comment, keyword, identifier

Would you agree the right name for this is "syntax-aware search"? It seems to me slightly different from our current symbol search (which deals with *definitions*).

One sketch is to implement this as follows:

- Add new search keywords `in:` and `is:` that let you specify things like `in:comment`, `in:doc` (doc comments), `in:string` (string literal), `is:ident` to restrict text matches. (Both `in:` and `is:` would do the same thing, but `in:` makes more sense English-wise for things like comments and string literals, and `is:` makes more sense English-wise for finding identifiers.)
- Add dynamic search filter suggestions for common cases here, such as suggesting to add `-in:comment` if a lot of (but not all) results occur within comments.

Other than the Sourcegraph use case you mentioned above, do you have any Uber use cases that would help us better understand how people inside Uber would use this?

Thank you!!

**Comment by beyang** [comment]
From @chrismwendt:

Syntax highlighters or tools like [tree-sitter](http://tree-sitter.github.io/tree-sitter/) could be used to extract syntax information (either on the fly or indexed).

**Comment by beyang** [comment]
From @aisbaa:

> Would you agree the right name for this is "syntax-aware search"? It seems to me slightly different from our current symbol search (which deals with _definitions_).

syntax-aware search sounds great! `in`and `is` sound like a right fit.

> Other than the Sourcegraph use case you mentioned above, do you have any Uber use cases that would help us better understand how people inside Uber would use this?

Unfortunately I don't, but I'm planning to integrate ubers feedback tool, that might give us more insights. I can forward survey responses if you'd like to.

> Syntax highlighters or tools like [tree-sitter](http://tree-sitter.github.io/tree-sitter/) could be used to extract syntax information (either on the fly or indexed).

Just a naive question, since I'm not familiar with LSP and sourcegraph internals. Theoretically LSP server should perform parsing internally (at least lexer/parser stages). It should construct AST from source code. If that is the case, would it be possible to ask lang server to provide that info and put it into the index?

> @aisbaa mind if we move this to the public issue tracker? (might be others out there who have a similar request)

Go ahead!

**Comment by keegancsmith** [comment]
LSP symbol search can return these results. However, two issues:
- The spec under specifies the input to a symbol search. It is just a string, so is upto the LSP server to decide what to return. Most seem to just do substring search. The results of a symbol search includes all your examples (except maybe comments?)
- Doing it cross-repo implies having a LSP server running per repo which doesn't scale well. This is likely solvable with LSIF. However, I am not 100% familiar with the LSIF spec so unsure if it supports this use case.

I think our symbol service is a more appropriate place to implement an efficient service for this that is consistent across languages. If cross-repo search is not required, LSP seems very appropriate (assuming the individual LSP server can understand this sort of symbol request).

**Comment by lguychard** [comment]
`select:symbol.$KIND` now allows doing this.
