### ISSUE TITLE
Add wildcard combobox component

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#22053]
#### Component description

Some limited versions of the Combobox components now are used by insight creation UI. 
You can find the suggestion (Combobox) component [here ](RepositoriesField)

**_Where will this component be used?_**
I believe we already have a few places to use this component (insight creation UI, or we have a suggestion in the extension dropdown panel)

 _Extension dropdown panel_
 
<img width="430" alt="Screenshot 2021-06-14 at 14 58 04" src="https://user-images.githubusercontent.com/18492575/121888724-fe0f5f80-cd20-11eb-9e7d-c37a849e51af.png">

_Branch picker in directory view_
<img width="580" alt="Screenshot 2021-06-14 at 14 59 23" src="https://user-images.githubusercontent.com/18492575/121888918-3b73ed00-cd21-11eb-8b8e-7a190bf1e9e1.png">

Now all those implementations don't have a common way to implement async suggestion or don't think about styling suggestion and a bunch of states (user typing, loading, user picking suggestion, ...etc)

#### Have designs already been created? If so, please link them here.
No

**Comment by pdubroy** [comment]
@vovakulikov Thanks for filing this. This week we're prioritizing our Wildcard work, so we should be able to let you know soon how we can help here.

**Comment by umpox** [comment]
Closing in favor of https://github.com/sourcegraph/sourcegraph/issues/27705
