### ISSUE TITLE
Diff searches with non-ASCII characters have incorrect highlight ranges

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#22066]
When a `type:diff` search contains a line with non-ASCII characters, the highlight ranges seem to be returned incorrectly.

Two examples:

- https://sourcegraph.com/search?q=context:global+type:diff+repo:sourcegraph/sourcegraph%24+camden+count:1+author:juliana+message:%22update+diff%22&patternType=literal
  - Highlight range is returned as `[4,90,6]`, should be `[4,88,6]`
  - ![image](https://user-images.githubusercontent.com/206864/121934760-8fb8a600-ccfc-11eb-838d-f398e42fac4f.png)
- https://sourcegraph.com/search?q=context:global+type:diff+repo:sourcegraph/sourcegraph%24+%E2%80%BA+%5C%5BCamden+count:1&patternType=regexp
   - Highlight range is returned as `[4,85,11]`, should be `[4,85,9]`
   - ![image](https://user-images.githubusercontent.com/206864/121934710-829bb700-ccfc-11eb-8fcd-3ad2223abbc8.png)

In this case, the character `›` is causing the issue. This character is 3 bytes in Unicode so the off-by-two error might be caused by the backend treating every byte as a character.

**Comment by camdencheek** [comment]
I'll take this one since I've recently touched this code.
