### ISSUE TITLE
Design: View batch change execution progress

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#22099]
Design for the first iteration of server side Batch Changes. 
Users can launch executors run from the CLI, then track progress in the GUI.

- Users run a batch change using `src batch run --file my.batch.yaml`
- The CLI returns a link to the batch change page to track execution
- Users can track execution in the GUI: track progress, and view logs.

[Draft Figma](https://www.figma.com/file/Kiy3qu0YvJcGsYfP2Nm8r6/execution-sketch?node-id=0%3A1&viewport=1428%2C571%2C1)  / Discussion in [PD 26 REVIEW: server side batch changes](https://docs.google.com/document/d/1MnfaA9P7mtur7aQbMvy2x96_zy_IrOhY-MbGUo5I5wk/edit#)

**Comment by chrispine** [comment]
Closing because this is outdated; we can create a better ticket if needed.
