### ISSUE TITLE
remove unused `lsif_indexable_repositories` table and references

### ISSUE THREAD

**Issue by tjdevries** [sourcegraph/sourcegraph#22127]
In https://github.com/sourcegraph/sourcegraph/pull/21982 we removed the usage of `lsif_indexable_repositories`, but because of our migration strategy we could not remove all references, drop the tables, etc.

We should do that and clean up any associated ops.

**Comment by scalabilitysolved** [comment]
Is this issue still valid @tjdevries , should it be something we tackle in the next iteration?

**Comment by tjdevries** [comment]
I'll work on this!
