### ISSUE TITLE
Messages on search homepage lost padding

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#22120]
![image](https://user-images.githubusercontent.com/10532611/122201914-d0e7bc00-ce9c-11eb-94cd-a3a8ed924a1a.png)

Notice how there is no padding for the boxes with the messages

**Comment by franco-ortega** [comment]
Hello. I am participating in Hacktoberfest and would like to work on this issue. Is there any particular amount of padding to add? Will a single value apply to all screen sizes?

Also, I am very familiar with using GitHub to work on team projects, but this is my first time working on an issue. How do I find the particular repo for this issue?

**Comment by franco-ortega** [comment]
@limitedmage Thank you so much for the info! I'll get started on this today and let you know how it goes.

**Comment by franco-ortega** [comment]
@limitedmage I have gotten to Step 5 of the Getting Started guide, but when I run this command:

`sg run redis-postgres`

I receive this error:

```
Running redis-postgres...
[redis-postgres] Network dev_default  Creating
[redis-postgres] Network dev_default  Created
[redis-postgres] Container dev-redis-1  Creating
[redis-postgres] Container dev-postgresql-1  Creating
[redis-postgres] Container dev-postgresql-1  Created
[redis-postgres] Container dev-redis-1  Created
[redis-postgres] Attaching to dev-postgresql-1, dev-redis-1
[redis-postgres] dev-redis-1       | 7:C 11 Oct 2021 22:44:02.198 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
[redis-postgres] dev-redis-1       | 7:C 11 Oct 2021 22:44:02.198 # Redis version=5.0.13, bits=64, commit=00000000, modified=0, pid=7, just started
[redis-postgres] dev-redis-1       | 7:C 11 Oct 2021 22:44:02.198 # Configuration loaded
[redis-postgres] Error response from daemon: Ports are not available: listen tcp 0.0.0.0:5432: bind: address already in use
--------------------------------------------------------------------------------
Failed to run redis-postgres:
Exit code: 1

Standard out:
        Attaching to dev-postgresql-1, dev-redis-1
        dev-redis-1       | 7:C 11 Oct 2021 22:44:02.198 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
        dev-redis-1       | 7:C 11 Oct 2021 22:44:02.198 # Redis version=5.0.13, bits=64, commit=00000000, modified=0, pid=7, just started
        dev-redis-1       | 7:C 11 Oct 2021 22:44:02.198 # Configuration loaded

Standard err:
        Network dev_default  Creating
        Network dev_default  Created
        Container dev-redis-1  Creating
        Container dev-postgresql-1  Creating
        Container dev-postgresql-1  Created
        Container dev-redis-1  Created
        Error response from daemon: Ports are not available: listen tcp 0.0.0.0:5432: bind: address already in use

--------------------------------------------------------------------------------
error: failed to run redis-postgres
```

When I run that command, two new items show up in Docker. One says:

```
dev-postgresql-1
CREATED PORT: 5432
```

```
dev-redis-1
RUNNING PORT: 6379
```

Any help would be most appreciated. Thank you.

**Comment by limitedmage** [comment]
Can you try running this command instead? 
```
export PGUSER=sourcegraph PGPASSWORD=sourcegraph PGDATABASE=sourcegraph 
createdb --user=sourcegraph --owner=sourcegraph --encoding=UTF8 --template=template0 sourcegraph
```

Alternatively, try setting up the database [without Docker](https://docs.sourcegraph.com/dev/getting-started/quickstart_5_initialize_database#without-docker)

**Comment by franco-ortega** [comment]
Running `pg_isready` results in the same "command not found" type of response.

If I clear Docker, the `docker ps` command responds with this:

`CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES`

Then, if I run the `sg run redis-postgres` command, it responds with the same error as above, the `docker ps` command responds with this:

```
CONTAINER ID   IMAGE                              COMMAND                  CREATED          STATUS          PORTS                    NAMES
0d0e67d4b89c   sourcegraph/redis-cache:insiders   "/sbin/tini -- redis…"   12 seconds ago   Up 11 seconds   0.0.0.0:6379->6379/tcp   dev-redis-1
```

**Comment by bobheadxi** [comment]
It's probably already in use - I'd check to see what other services you might have running locally that bind to that port

**Comment by franco-ortega** [comment]
Thank you, everyone. I will try to work on this for 30 min each day this week, and I'll keep you updated.

**Comment by vanesa** [comment]
This issue is still available for solving!
