### ISSUE TITLE
Remove site-admins after audit

### ISSUE THREAD

**Issue by bcreager** [sourcegraph/sourcegraph#22125]
Remove users that are marked as not needed site-admin access: https://docs.google.com/spreadsheets/d/1iqpktlUB0fi5XAafFvTqbLZyNRNgBAIdRoniqjyJcCA/edit#gid=539739516

**Comment by daxmc99** [comment]
@sourcegraph/security are we OK with having personal emails with site admin access?

**Comment by daxmc99** [comment]
Users that were removed were marked in red in the spreadsheet
