### ISSUE TITLE
obstructed views in search on dotcom when sidebar is collapsed

### ISSUE THREAD

**Issue by adeola-ak** [sourcegraph/sourcegraph#22136]
#### Feedback

The icon that the side panel displays when it is collapsed can obstruct some of the content on the page and continue to obstruct as the behavior continues as you scroll.

The customer believes the icon is poorly placed as it blocks page contents and persists as you scroll down the page

The symbol covering text is depicted below in a screenshot 

<img width="808" alt="Screen Shot 2021-06-16 at 2 49 55 PM" src="https://user-images.githubusercontent.com/67931373/122276278-a1dc4500-ceb2-11eb-9672-713d50f66aec.png">

#### Customer

https://sourcegraph2020.lightning.force.com/lightning/r/Account/0013t00001XicWuAAJ/view

**Comment by felixfbecker** [comment]
The solution I proposed in https://github.com/sourcegraph/sourcegraph/issues/21637 would fix this issue too (note how there is no overlap with the content):

![image](https://user-images.githubusercontent.com/10532611/122286534-3fa23500-cef0-11eb-8f7a-ab5bab0e9ab3.png)

![image](https://user-images.githubusercontent.com/10532611/122286633-5ea0c700-cef0-11eb-95f7-0a1bc51ffe6b.png)
