### ISSUE TITLE
Remove notifications functionality from saved searches

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#22154]
### Context

We decided in planning code monitoring that notifications functionality for saved searches would be removed once we were confident in code monitoring's performance. I believe we've validated code monitoring as a replacement for these notifications, and now we need to remove the notifications functionality from saved searches.

_Note that saved searches themselves will continue to exist in Sourcegraph in the form of "easy re-usable search queries," but without notifications._

### Proposal 

Existing saved searches with notifications should continue to work for now. We should:

1. Remove the ability to add notifications to saved searches that aren't already using them, and update content to reflect functionality:

<img width="602" alt="CleanShot 2021-06-17 at 12 11 53@2x" src="https://user-images.githubusercontent.com/6304497/122377293-3e5f1f80-cf65-11eb-9f6d-ac3eac76aab9.png">

Note that the button label has changed and there's now a "Cancel" button as well.

2. Disable interactivity with saved search notifications that already have them configured, and prompt users to create a code monitor instead.

There's a couple of approaches to this: the slightly-more-scope approach, and the minimal scope approach.

In the minimal scope approach, we show the "Email notifications" checkbox, and show an info message telling the user to go to code monitoring. When the user unchecks the checkbox and saves the view, the checkbox and notifications are no longer shown.

<img width="620" alt="CleanShot 2021-06-17 at 12 12 53@2x" src="https://user-images.githubusercontent.com/6304497/122377746-9eee5c80-cf65-11eb-9c8e-4e1034d2dee4.png">

With a bit more scope, we could offer the ability to "convert" a saved search notification into a code monitor on the spot. This would take whatever's in the saved search query and would take the user to the "Create new code monitor" view with the saved search notification pre-filled. Then, we could "uncheck/remove" the notification from the saved search while preserving the search as a "useful bookmark."

<img width="609" alt="CleanShot 2021-06-17 at 12 14 56@2x" src="https://user-images.githubusercontent.com/6304497/122377946-d0672800-cf65-11eb-8aab-71b2b6d45b2e.png">

In this approach, I would rather take the user to the create code monitor view than keep them in place (and create the code monitor behind the scenes), because there's a risk that not all saved search queries might be valid by default, and if something goes wrong it won't be surfaced well. As well, when more actions are available (like webhooks), taking the user to the create view will help surface more options.

Once the user has hit "Convert to code monitor," we'd "uncheck" it and subsequently only show the description and query fields.

Note that the button label has changed and there's now a "Cancel" button as well.

Flow diagram and basic wireframes on Excalidraw: [https://plus.excalidraw.com/l/4Dr1S6qmmY7/9coop4HogrC](https://plus.excalidraw.com/l/4Dr1S6qmmY7/9coop4HogrC)

### Next steps

We need to agree on which approach (or another approach!) we'd like to take. Then, we can finalize our plan.

**Comment by limitedmage** [comment]
> the tradeoff is there's no way to "uncheck" the notification

What if we keep the checkbox enabled? Once disabled and the saved search is saved, we don't show it again.

**Comment by limitedmage** [comment]
Another suggestion: adding a box under the form in the vein of "Want to get notified about changes to your code? Create a code monitor". This could be shown for every saved search.

**Comment by quinnkeast** [comment]
> > the tradeoff is there's no way to "uncheck" the notification
> 
> What if we keep the checkbox enabled? Once unchecked and the saved search is saved, we don't show it again.

Obvious in hindsight. Let's do that!

>Another suggestion: adding a box under the form in the vein of "Want to get notified about changes to your code? Create a code monitor". This could be shown for every saved search.

I'm just a bit hesitant here because for new users, it creates a conceptual connection between saved searches (as bookmarks) and notifications related to saved searches. It'll be a lot easier to evolve saved searches if we keep them conceptually separate now.

**Comment by limitedmage** [comment]
I like this. I'd vote for option 2 since it's the cheaper one, since I'm concerned about user expectations of the term "convert". (Will the saved search be deleted? Also, not all saved searches are valid for code monitors.) We could even do option 1 what pre-populates the query with the saved search's query.

**Comment by quinnkeast** [comment]
I've [updated the Excalidraw](https://plus.excalidraw.com/l/4Dr1S6qmmY7/9coop4HogrC) to reflect the decision here.

The only tradeoff is that saved search notifications will always be in the UI until the user de-selects "send notifications" themselves and saves. In the future, when we're ready to totally shut off saved search notifications, we can address this as needed.

**Comment by limitedmage** [comment]
@quinnkeast Regarding this part:
> + notifications *removed* from original saved search

I'm not sure if this is a good idea. When users are taken to the new code monitor form, the values are pre-populated, but the user may end up cancelling the creation or changing the query to something different from the original saved search. Also, not all valid saved search queries may be valid for code monitoring, because we added more strict validation for code monitoring, so the user might have to modify it anyway.  I'm leaning towards skipping/punting this. WDYT?

**Comment by quinnkeast** [comment]
To be totally sure we're thinking of the same thing: I'm envisioning notifications becoming unchecked on the original saved search, to prevent duplication of notifications and creating the need to go back to the original saved search. Is that the part you're thinking about as well?

**Comment by limitedmage** [comment]
Yes, correct.

**Comment by limitedmage** [comment]
@quinnkeast  Should we also add the notice/warning to emails being sent out by saved searches notifications?
