### ISSUE TITLE
Weird black gap at top of homepage

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#2215]
![image](https://user-images.githubusercontent.com/754768/52498077-906d2a80-2b8c-11e9-9f40-1979476ef857.png)

**Comment by francisschmaltz** [comment]
@nicksnyder this is from the 3.0 announcement. I think it's the z-index that causes the content to shift but not be visible.

**Comment by francisschmaltz** [comment]
Ahh. It's the position. It needs to be changed to sticky on the homepage to display correctly.
