### ISSUE TITLE
Extensibility: use DismissibleAlert for browser extension discoverability alerts

### ISSUE THREAD

**Issue by tjkandala** [sourcegraph/sourcegraph#22169]
Before the redesign, we had reasons to re-implement `DismissbleAlert` ([context](https://github.com/sourcegraph/sourcegraph/pull/22126#discussion_r653619585)). Now, `DismissibleAlert` completely suits our needs.  

#### Potential benefits

Decrease our bundle size slightly, less code to read + maintain.

#### Cost of not refactoring immediately

More code to maintain, but not too risky since these components aren't modified often and aren't critical to our code browsing UI.

**Comment by ryankscott** [comment]
These alerts are no longer used.
