### ISSUE TITLE
Extensibility: search within "other" category doesn't match user expectations

### ISSUE THREAD

**Issue by tjkandala** [sourcegraph/sourcegraph#22171]
On the main registry page (category = "All"), we display uncategorized extensions under the "Other" category. However, when users search for "Other" extensions, we only display extensions explictly categorized as "Other." 

Example of negative UX consequences (user clicks on "show full category" and _loses_ hits):

![Screenshot from 2021-06-17 11-01-07](https://user-images.githubusercontent.com/37420160/122424446-ba089e80-cf5c-11eb-865f-d45d0b98ef46.png)

![Screenshot from 2021-06-17 11-01-18](https://user-images.githubusercontent.com/37420160/122424459-bbd26200-cf5c-11eb-9f02-20e248603b7c.png)

**Comment by tjkandala** [comment]
Update: I checked the `wolfychu/test` and it doesn't have explicit categories either. We should look into why my local registry extensions with `"test"` in their extension IDs don't show up in the second search.

**Comment by muratsu** [comment]
This is an interesting one, I've checked the manifests and am not sure what the logic is here. Curious to know the reason
