### ISSUE TITLE
Update logo and brand colors to the new versions

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#22184]
Brand design has updated our logo and brand colors. We need to update them within the product and design system as well. 

| Color  | Current | New |
| ------------- | ------------- | ------------- |
| Blue: | `#00B4F2` |      `#00CBEC`
| Red/orange: | `#F96216` |      `#FF5543`
| Purple: | `#A305E1` |      `#A112FF`

New logo attached:
[Sourcegraph_Logo_FullColor_light.svg.zip](https://github.com/sourcegraph/sourcegraph/files/6954564/Sourcegraph_Logo_FullColor_light.svg.zip)

**Comment by valerybugakov** [comment]
@rrhyne, do we have Sourcegraph logo source in Figma or Google drive?

**Comment by felixfbecker** [comment]
The source of truth is in our handbook :) https://about.sourcegraph.com/handbook/marketing/brand/brand_guidelines

One note for frontend changes: You'll likely need to change the `?v2` cache bust parameter to `?v3` in addition to updating the logo (or just start inlining the logo into JSX, which would also fix our Percy snapshots showing a broken logo...).
https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+%3Fv2&patternType=literal
