### ISSUE TITLE
Extension card status for unsigned users

### ISSUE THREAD

**Issue by muratsu** [sourcegraph/sourcegraph#22191]
If you visit the [extension registry](https://sourcegraph.com/extensions?category=All) without signing in the extension cards will have a label `disabled` or ✅ icon indicating if they are enabled/disabled. This seems to be an artifact from before redesign. 

![image](https://user-images.githubusercontent.com/1308560/122437739-d7cf0700-cf4e-11eb-97c0-854bb416e9aa.png)

**Comment by AlicjaSuska** [comment]
@muratsu Thank you for surfacing this issue. I've put together a [design](https://www.figma.com/file/W5CUf6Ar7ipVf0Q858Vv8C/Extension-card-status-for-unsigned-users-22191?node-id=1%3A59):

- for extensions enabled by default: toggle (on, disabled) + 'enabled by default' label
- for extensions not enabled by default: toggle (off, disabled) + 'log in to enable'

I'd like to add a tooltip for both cases that says: 'Log in to manage extensions'. I'm wondering if 'log in' is a good message here though, maybe we should focus on 'sign up' as well. @Joelkw what do you think?

**Comment by Joelkw** [comment]
@AlicjaSuska I like making this a touchpoint to sign up (via the toggle and a nice rather than hijack-y redirect)! Perhaps "sign in" is enough to cover all cases but we take them to the sign up/sign in screen that handles it regardless?
