### ISSUE TITLE
API docs for streaming search endpoint

### ISSUE THREAD

**Issue by DaedalusG** [sourcegraph/sourcegraph#22206]
#### Feature request description

For customers building tools off of Sourcegraph, it may be helpful to have some documentation about what makes the streaming search endpoint in the UI different than the graphQL endpoint typically utilized for building off of Sourcegraph. Information should be available about the nature of streaming search endpoint and its differences to graphQl endpoint. 

#### Is your feature request related to a problem? If so, please describe.

In some use cases, graphQL paginated search may not be well suited to developing tools, additionally, it is flagged as experimental. In these same cases streaming search may present a valuable alternative. While full API support may not be necessary, some information would be appreciated by adventurous developers.

**Comment by rvantonder** [comment]
I think we need to look revisit the points in this issue holistically, some parts here are outdated, like 

> graphQL paginated search may not be well suited to developing tools, additionally, it is flagged as experimental.

refers to something that's removed

> some information would be appreciated by adventurous developers.

> seems silly to have no user-facing docs around how to use our preferred search API

There are many many things we can do to support adventurous developers, and public documentation for our streaming search API is one item on that list. Like many teams, we tend to prioritize what's coming through via customer requests, some more detail about our audience and "adventurous developers" here is going to be useful context.

To give more context on the current state, I would also say, that our preferred search API is not in a mature enough state that we are eager to put out documentation for general API use. Around 2 months ago I was still changing data type definitions https://github.com/sourcegraph/src-cli/pull/610. And, some customers have asked about using it, and we've said 'you can use it in this state but we are still fleshing it out'. I'm just defending a bit that, this is not so silly/some obvious oversight. It is in flux, and we evaluate things like pushing out a GA streaming API docs on an on-demand basis like many other requests. We are also adding on to it still  with highlighted streaming (in progress https://github.com/sourcegraph/sourcegraph/issues/24097). And, as you know, we also have the CORS issue, which is going to be way more likely to stop adventurous/outside developers. I'm going to take a guess, that maybe you wanted to do something specific here to use the streaming API, but couldn't find docs on it (and given commentary on the CORS issue), so maybe helping with your specific case is going to be more productive than trying to address the overarching "why doesn't this exist for all users already, and that way I can use it too?"

**Comment by rvantonder** [comment]
The client URL params here give an idea of what the endpoint supports:

https://github.com/sourcegraph/sourcegraph/blob/a248eae68cee442546b68f025c99fb554fbb5d15/client/shared/src/search/stream.ts#L423-L431

The `dl`, `dk`, `dc` params are part of highlighting/decoration work that's still in progress and should be considered experimental. The rest correspond to GQL search types, except for `display` which is the cap on the number of results the client wants.

**Comment by stefanhengl** [comment]
For visibility, here is the ticket relating to the CORS issue https://github.com/sourcegraph/sourcegraph/issues/23140

**Comment by daxmc99** [comment]
👍 On docs for this. There is a lot of confusion here on this new API endpoint

**Comment by lguychard** [comment]
Seems like the time has come to add some docs for this: https://sourcegraph.slack.com/archives/CHEKCRWKV/p1636571039132900?thread_ts=1636570636.131500&cid=CHEKCRWKV

@sourcegraph/search-core would you like to take a first pass at documenting what's currently supported in the API?

**Comment by david-sandy** [comment]
We are also working on documenting our API (/.api) and NON-API (other than /.api) security.  At this point we are working on making a number of changes to comments in our code, changes to the actual code and creating an actual diagram for these.  

Hopefully. reading some of the code comments would be helpful:

https://github.com/sourcegraph/sourcegraph/pull/27313
https://github.com/sourcegraph/sourcegraph/pull/27303
https://github.com/sourcegraph/sourcegraph/pull/27298
https://github.com/sourcegraph/sourcegraph/pull/27297
https://github.com/sourcegraph/sourcegraph/pull/27295

There are additional changes coming.  This is sort of piece meal at the moment, so, my apologizes, but, I wanted to let you folks know what is being worked on as @daxmc99 thought it would be useful.

**Comment by stefanhengl** [comment]
I have added a doc page for our Stream API (https://github.com/sourcegraph/sourcegraph/pull/28173). We still need to fix the CORS issue (link above) before customers can really do something useful with the API though.
