### ISSUE TITLE
Fuzzy finder: too little visual hint when clicking on "show more" button

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#22219]
Currently, the fuzzy finder displays maximum 100 results. When there are more than 100 results, the "show more" button becomes visible. Every time the user clicks on "Show more", the maximum number of results increases by 100.

We got feedback that there are limited visual hints when clicking on "Show more".

> 2. Click the Show more button doesn't seem to do anything? Or maybe it does, but there's no visual cue.
> <img width="1576" alt="Screen Shot 2021-06-16 at 10 47 29" src="https://user-images.githubusercontent.com/67471/122188659-75afcc80-ce90-11eb-8b80-36b6f336ead8.png">
> _Originally posted by @tsenart in https://github.com/sourcegraph/sourcegraph/issues/21201#issuecomment-862179845_

This problem seems to originate from the fact that the "Show more" button is visible even if you haven't scrolled to the bottom of the list. I propose that we move the button to the bottom of the results list to fix this UI quirk.

What do you think @rrhyne?

/cc @felixfbecker

**Comment by rrhyne** [comment]
Show more should be at the bottom of the list to match what occurs in other areas of the product, so this is a good fix.

**Comment by fkling** [comment]
Looks like we don't show a "show more" button anymore? Closing this for now, feel free to reopen.
