### ISSUE TITLE
Fuzzy finder: UI looks too dark in dark theme

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#22222]
Currently, the fuzzy finder currently looks like this in the dark theme:

![image](https://user-images.githubusercontent.com/1408093/122553937-9a46a880-d038-11eb-89ce-e467aa9299d7.png)

I personally find it difficult to view because it's too dark. In particular, the highlighted text uses `<mark>` nodes that set the text color to black, which has too little contrast from the dark-ish yellow/orange `--mark-bg` background color.

/cc @felixfbecker

**Comment by felixfbecker** [comment]
This was fixed



![Image](https://user-images.githubusercontent.com/10532611/202808861-37028e82-9a0c-47e0-bc74-cea69a39c0d4.png)
