### ISSUE TITLE
Fuzzy finder: trigger on keyboard shortcut `Cmd/Ctrl + P`

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#22229]
Currently, we use the keyboard shortcut `t` to activate the fuzzy finder. This shortcut was chosen because it's consistent with the equivalent feature on GitHub. However, this shortcut has the downside that it's not active while the search bar is focused (and it's focused by default when opening a page). It would be nice if we support an additional shortcut that can also be active while the search bar is focused. Proposals:

- `Cmd/Ctrl + P`: consistent with default shortcut in VS Code and Sublime.
- `Cmd/Ctrl + Shift + O`: consistent with default shortcut in IntelliJ

Tagging @quinnkeast because this is related to RFC 345 (https://docs.google.com/document/d/1_r8aikiE-zwn0ZkWmOilynNVA3HfmF9Mglgg6ZEkkls/edit#).

My vote would be to use `Cmd/Ctrl + P`. Down the road, I think we should consider making this configurable via extensions (similar to VS Code) so that users can optionally install an extension that override the default keybindings (for example, to support IntelliJ/Emacs keybindings).

**Comment by quinnkeast** [comment]
We should generally avoid overriding existing browser shortcuts where possible, as we exist within the browser context.

I'd propose `alt`+`p` instead, which would be close to a [shortcut available anywhere](https://docs.google.com/document/d/1_r8aikiE-zwn0ZkWmOilynNVA3HfmF9Mglgg6ZEkkls/edit#bookmark=id.3cv1ir92mt9y).

**Comment by olafurpg** [comment]
@quinnkeast I agree with this in principle but it looks like several other online code editors override `Cmd/Ctrl + P` for the same feature:

- GitHub Codespaces
- Gitpod
- Replit

I think it would be natural for Sourcegraph to stay consistent with those.

**Comment by quinnkeast** [comment]
I see your perspective! It's a compelling argument.

 It's interesting to think how this will ultimately shape how we approach a lot of keyboard shortcut patterns. I know we can change it any time, so it's a relatively low-risk decision, but I like thinking systematically. @umpox @felixfbecker @limitedmage – each of you had quite a few contributions to the original RFC around keyboard navigation in Sourcegraph. Do you have any thoughts on this to share?

**Comment by felixfbecker** [comment]
I absolutely hate when the print dialog pops up because my muscle memory made me press cmd+P on Sourcegraph or GitHub. Like no Chrome I do not want to print the code thank you 😄  So I would love it if we override it.

**Comment by limitedmage** [comment]
I also wouldn't mind overriding Ctrl+P, I also get the "print" dialog to pop up way too much. If users *really* want to print from Sourcegraph, there's always the File > Print menu.

**Comment by olafurpg** [comment]
Sounds good. Looks like there's consensus to try overriding Cmd/Ctrl+P! I'll try to prepare a PR this week. I already got it working for most cases but the shortcut is not activated while the search bar is focused.

**Comment by olafurpg** [comment]
Do other people agree that this issue should block GA for the fuzzy file finder? I personally find it frustrating that I can't activate the fuzzy finder while the search bar is focused. Using a different keyboard shortcut like Cmd/Ctrl+P would fix this issue but I haven't been able to implement this change myself when I've looked into it. I'd love to make the fuzzy file finder enabled for all users by default but I also want to avoid changing the keyboard shortcut after the feature reaches GA.
