### ISSUE TITLE
Replace visibility settings insight creation UI by dashboards scope setting

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#22235]
### Background
Now in insight creation UI, we have visibility settings to choose what kind of settings in the setting cascade will be used. A personal or an organization level. With the dashboard system, we should change this in order to be able to choose a dashboard instead of a particular level of setting cascade.

**Now** 
° Personal
° Sourcegraph (let's say in this example user was included in Sourcegraph org)

**WIth dashboards**
° Personal dashboard - since we always have this dashboard this works exactly like personal visibility options now
° Sourcegraph org dashboard (see https://github.com/sourcegraph/sourcegraph/issues/22218)
° User personal custom dashboard 
° Some dashboard from Sourcegraph org

For the first version of dashboards and according to our tech limitation (you can find them in this doc https://docs.google.com/document/d/1qHFFS53Ca3gmbi8jODUaPnkpu05CyqPi_VuAXKbmtsk/edit#) we should have here radio group instead of combobox 

<img width="501" alt="image" src="https://user-images.githubusercontent.com/18492575/122567359-409ea800-d051-11eb-9721-3e4af82d4889.png">

**Comment by felixfbecker** [comment]
@vovakulikov what's your estimate on this?

**Comment by vovakulikov** [comment]
According to this PR, this issue is no longer relevant since we use separate UI for adding/removing insights to/from the dashboard. https://github.com/sourcegraph/sourcegraph/pull/22748
