### ISSUE TITLE
Implement "Add insight to dashboard"

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#22233]
### Background
With an insight dashboard, there are two ways how to add insight to some dashboards.
- Set dashboard in insight creation UI (dashboard, prior visibility setting)
- This ticket case - via `assign insight to` UI

Note that for the first version we can use just a list of checkboxes instead of Combobox control (see the second sketch)

<div style="display:flex">
<img width="45%" alt="image" src="https://user-images.githubusercontent.com/18492575/122559795-75f2c800-d048-11eb-8075-b21e6efec037.png">

<img  width="45%"  alt="image" src="https://user-images.githubusercontent.com/18492575/122560058-cbc77000-d048-11eb-8f69-368a4b80ff62.png">

</div>

**Comment by felixfbecker** [comment]
FYI the copy verb for this was changed from "add" to "assign"
