### ISSUE TITLE
Export to CSV extension produces blank CSV on some exports

### ISSUE THREAD

**Issue by emchap** [sourcegraph/sourcegraph#22247]
- **Sourcegraph version:** Demo
- **Platform information:** FF, OSX

#### Steps to reproduce:

1. Go to https://demo.sourcegraph.com/search?q=lang:Python+class...:+count:all&patternType=structural
2. Export to CSV
3. Open CSV

#### Expected behavior:

Has content.

#### Actual behavior:

![image](https://user-images.githubusercontent.com/9934079/122614559-bd268c00-d03b-11eb-86c6-d137935e518f.png)

**Comment by emchap** [comment]
https://demo.sourcegraph.com/search?q=test+repo:sourcegraph%24+-file:_test%5C.go%24+&patternType=structural Populated correctly. I'm uncertain what causes the consistent but different behavior.

**Comment by muratsu** [comment]
The demo instance currently runs SG version: 3.28.0. The bug you're running into here is fixed in [3.29](https://github.com/sourcegraph/sourcegraph/issues/21569).
