### ISSUE TITLE
Config errors in external services no longer appear to show up in admin UI

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#2227]
~~Configuration errors in external services no longer appear in admin UI.~~

Repro:
* Add an external service with the following config:
```
{
  "authorization": {
    "ttl": "1s",
    "identityProvider": {
      "type": "oauth"
    }
  },
  "token": "$TOKEN",
  "url": "https://gitlab2.sgdev.org"
}
```
* View site admin UI (http://localhost:3080/site-admin). No error shows up, but logs show "Repository authz config was invalid (errors are visible in the UI as an admin user, you should fix ASAP). Restricting access to repositories by default for now to be safe.". If you add a `log.Printf("%+v", seriousProblems)` to [this line](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/internal/authz/init.go#L103:0), you can see the actual error (the GitLab URL doesn't exist in the `auth.providers` list in the critical site config).

This is a high-priority bug fix, because without the error, the code host configuration will fail silently, leading to unexpected behavior.

**Comment by slimsag** [comment]
I think tsenert/Nick would be the best person to work on this, I haven't
interacted with this code yet

**Comment by tsenart** [comment]
Hey @beyang,

Would you please provide more detailed repro steps? The specific flow and config you're inputing would be great. Also, which page exactly are you referring to by "Site Admin UI"?

**Comment by beyang** [comment]
@tsenart Updated the repro steps. Ping me on Slack if that's still insufficient :)

**Comment by tsenart** [comment]
Thanks @beyang.

**Comment by nicksnyder** [comment]
@beyang please discuss this with @tsenart @keegancsmith so you can handoff knowledge about how auth works

**Comment by tsenart** [comment]
Hey @beyang,

What is the error in the above config?

**Comment by beyang** [comment]
The error is the following:
* The `authorization` field is set with `authorization.identityProvider.type` set to "oauth", which means "enforce permissions using a user's GitLab OAuth identity".
* There is no corresponding item in `auth.providers` (in the critical site config) that matches the GitLab URL, which means there is no way Sourcegraph has the user's GitLab OAuth identity.

**Comment by tsenart** [comment]
@attfarhan: I suspect that this is a frontend issue introduced here https://github.com/sourcegraph/sourcegraph/pull/2033

I'm seeing weird behaviour where the frontend returns an error like this, as logged in the `asError` function:

```
{message: "external service updated, but sync request failed:…rt/vegeta returned status 401: Bad credentials↵↵↵", path: Array(1)}
```

But the UI either just ignores the error and shows "Updated", or some other times it keeps spinning the in an "updating" state.

**Comment by tsenart** [comment]
Also, cc @felixfbecker for visibility, since you were involved in that PR.

**Comment by felixfbecker** [comment]
This needs to be followed up upon by keeping the refactor and making real fix

**Comment by nicksnyder** [comment]
@felixfbecker or @attfarhan please file a new issue to track the work that needs to be (re)-done.

**Comment by attfarhan** [comment]
Reverting my commit, which @tsenart did in https://github.com/sourcegraph/sourcegraph/commit/1ba5cf684eaeffa14d29ea36ddaf1c6f168949d1, fixed the problem where errors for invalid configuration did not appear. 

However, following Beyang's repro steps above, the log message `Repository authz config was invalid (errors are visible in the UI as an admin user, you should fix ASAP). Restricting access to repositories by default for now to be safe.` still appears, and there is indeed nowhere that this error appears in the UI.

@tsenart I am reopening this since most of the issue is still unfixed
