### ISSUE TITLE
Add ability to overwrite env variables for the `sg` command from the terminal

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#22322]
In the current `sg` implementation `VAR=foo sg run bar` will still use `VAR` value from the  `sg.config.yaml.`
It would be great to allow overwrites.

[Slack thread](https://sourcegraph.slack.com/archives/C01N83PS4TU/p1623840700149300) for context.

**Comment by mrnugget** [comment]
That's a tough one, because from `sg`'s perspective `VAR=foo sg run bar` are the same as 

```
VAR=foo
[30 days later]
sg run bar
```

How would you feel about `sg run bar -e VAR=foo`?

**Comment by mrnugget** [comment]
This is implemented by not overwriting env vars set in the environment.
