### ISSUE TITLE
insights: historical backfiller unnecessarily repeats many queries

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#22324]
The historical backfiller for code insights analyzes data frames to determine which frames need to be [sampled.](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/insights/background/historical_enqueuer.go?utm_product_name=GoLand&utm_product_version=GoLand&utm_source=JetBrains-v1.2.0#L231:34)

Once the analyzer finds frames that need to be queried, tasks are [queued](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/insights/background/historical_enqueuer.go?L481&utm_product_name=GoLand&utm_product_version=GoLand&utm_source=JetBrains-v1.2.0#L231:34) up. These tasks can take significantly longer than the frame analyzer, and many of them will end up duplicated in the queue. Currently on dogfood-k8s there are approximately 112 million queued jobs for only 3 defined insights.

The analyzer does perform a [check](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/insights/background/historical_enqueuer.go?L331&utm_product_name=GoLand&utm_product_version=GoLand&utm_source=JetBrains-v1.2.0#L231:34) if there is already a point in the time frame, but this is ineffective:
1. The frame could be queued but not yet executed
2. The frame could have been skipped as part of an optimization pass, in which case the value at that frame should be the most recent observation, which may exist

This is problematic because any newly defined insight would have to wait for all of those records to clear before it will start filling, as well as the unnecessary work performed on the cluster.

Ideally we should only need to perform one search per frame per insight series.

**Comment by coury-clark** [comment]
This is loosely related to #21483, as it has to do with this historical analyzer and query mechanism being largely stateless.

**Comment by coury-clark** [comment]
As a temporary measure, we could consider running the historical analyzer at a much slower interval. Currently it [runs](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/insights/background/historical_enqueuer.go?L149&utm_product_name=GoLand&utm_product_version=GoLand&utm_source=JetBrains-v1.2.0#L231:34) every 15 minutes to pick up new insights. We could consider running this every 12 hours (or some other long interval), to allow any newly defined insights to finish populating in that interval. It won't solve the problem overall, as any insight that takes longer than 12 hours would still grow without bound until completely backfilled. 

The tradeoff of something like this is that it would take up to this interval of time before any newly defined insights start populating. This tradeoff may be unavoidable, as other performance concerns #22304 will likely manifest solutions with a similar downside (such as materializing views on an interval).

Do you have any thoughts / opinions on this @slimsag?

**Comment by slimsag** [comment]
Completely 100% agree with the problem statement here.

The reason I didn't address this was because, due to the number of repositories and how often the historical analyzer already had to yield (sleep) to ensure it did no harm, it was in practice running much slower than the jobs themselves (when I was testing.)

I think that's no longer true today, though. Especially with the awesome improvements you made.

What if we ran the historical enqueuer goroutine at a much faster interval (say, every minute) but it just immediately returns (does no work) if the job queue has a lot of work in it? that way you can be guaranteed that if the job queue is empty, it's going to start adding more work.

**Comment by coury-clark** [comment]
Current thinking for a light solution:

1. When we create a new insight data series, store some state for which intervals we need to backfill.
2. While queueing up queries for backfilling, we can join insight series to this table of historical intervals filtered by incomplete intervals.
3. After we queue up the query, we mark the interval record as completed.

This would require a small refactor of the [historical recorder](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/insights/background/historical_enqueuer.go) to analyze based on individual insights intervals, rather than a global set of intervals.

**Comment by coury-clark** [comment]
> It pretty much becomes a boolean "has this insight seen a full repository iteration yet" flag.

Maybe this is the lightest solution of them all? Instead of storing intervals we just take the creation metadata, build the dataframes in memory. If we successfully complete a full repository walk we just flag the data series as backfilled?
