### ISSUE TITLE
Slide toggle in ext debug menu looks glitchy

### ISSUE THREAD

**Issue by vanesa** [sourcegraph/sourcegraph#2234]
#### Steps to reproduce:

1. Have the browser extension for Chrome active. On GitHub, run `localStorage.debug=true;location.reload()` in your console if the extension debug menu isn't visible already. 
2. Click on the extension debug menu and activate `Log to devtools console`. 
3. Notice on the slider is missing the toggle button when activated.

![image](https://user-images.githubusercontent.com/9110008/52533804-9164ae80-2d7c-11e9-8a2f-3c73e0d14c7b.png)

#### Expected behavior:
Look like a normal slide toggle.

#### Actual behavior:
Looks like a glitchy slide toggle.

**Comment by felixfbecker** [comment]
#2344 removes this toggle
