### ISSUE TITLE
insights: support backend insights over a subset of all repos

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#22349]
Currently backend insights run against all repos, and will aggregate across all repos. The creation UI allows users to specify a subset of repos, and likely search contexts will be another way that we can select repo groupings.

We should do one of the following:
1. Continue to run an insight over all repos, and only aggregate over the user specified subset at query time
2. Only run the insight over the subset of repos, possibly having to duplicate data
3. Run the insight over the subset of repos without duplicating data, but having to handle the cases where different users have different (and possibly intersecting) subsets

**Comment by felixfbecker** [comment]
Summary from the [team sync](https://docs.google.com/document/d/1cftSl8GMuw4uUv91wpgpMCPB8BFJ28dd3FojBYDB4rI/edit#heading=h.c7vqlxfhgx83): 
- @coury-clark would like to delay this until post-Beta when backend is in a better place to do this
- Implication of this for Beta is that insights, under the hood, still always run over all repos and are going to take time to backfill (and add pressure on the scheduler queue)
  - However, drilldown (repo filtering at view time) is going to be very fast.
- @Joelkw says that is acceptable for Beta, given we can essentially say insights are spending more time upfront to support fast drill-down afterwards

**Comment by Joelkw** [comment]
@felixfbecker thanks for documenting. Noting explicitly (and for my future reference) as well that my understanding is filtering is not _required_ to actually filter your insight view to a subset of repos. This means if you want to run it over repos A,B,C,D, then you can still define that in the insight setup (not waiting until the filter stage) and, while the backend may actually run over repos A,B,C,D,E,F,G, it ultimately only displays your insight values only over ABCD repos, without requiring additional filtering.

**Comment by coury-clark** [comment]
One of the problems to solve here is that there is value in being able to translate insight metadata (query text, repositories, possibly interval) into a unique series ID such that we can reuse data if it has already been calculated. For very small insights (say, less than 5 repos) we wouldn't necessarily mind duplicating data (5 repos * 12 data points = 60 points) since they would execute very fast anyway and require minimal storage. However, for anything in the realm of hundreds or thousands of repos it takes enough time that reusing previously calculated values is important.

Here is some text from a recent random brain dump on the topic:

1. Is there something we can associate with a set of repos so that code insights can deterministically associate a subset of the underlying data with a repo set
    1. This will allow us to continue to re-use pre-generated data. The problem right now is that we have to run over all repositories. Ideally we would allow users to provide subsets, and let the system determine which subsets need to be populated for.
        1. It gets tricky handling changing underlying data, because repos already selected would be receiving real-time recordings of indexed search (at an interval), but to catch up the new repos you’d have to go back and do historical searches for each (repo, time). 
       2. Or maybe we only include the data from each subset at the time it was included in a particular data series? This would show the “growth” as the series are added in the chart, rather than “modifying” history.
    2. Even if we couldn’t reuse the data, it would still be useful to have a simple association without thousands of repos. For example insight A -> global context
    3. Search contexts don’t quite seem to fit
        1. Limit revision - maybe if we had a wildcard for revision?
        2. Searches that don’t match a context query will result in an error https://github.com/sourcegraph/sourcegraph/issues/24149

**Comment by coury-clark** [comment]
Closing as this is long out of date. We now support static lists of repos, and upcoming work to support dynamic repo queries.
