### ISSUE TITLE
Code intelligence breaks because there is no HEAD for an empty Git repository.

### ISSUE THREAD

**Issue by sfllaw** [sourcegraph/sourcegraph#22357]
- **Sourcegraph version:** 3.29.0

#### Steps to reproduce:

1. Create an empty GitHub Enterprise repository.
2. Ask Sourcegraph to index it.
3. Wait for the worker to start its code intelligence pass.

#### Actual behavior:
Code intelligence breaks because there is no HEAD for an empty Git repository.

The worker process will emit the following error logs:
> worker | lvl=eror msg=codeintel.autoindex-enqueuer.QueueIndex error="gitserver.FileExists: git.ResolveRevision: revision not found: github.example.com/org/empty-repo@HEAD" count=1.000 elapsed=0.004
> worker | lvl=eror msg=codeintel.autoindex-enqueuer.QueueIndex error="gitserver.FileExists: git.ResolveRevision: revision not found: github.example.com/org/empty-repo@HEAD" count=1.000 elapsed=0.004
> worker | lvl=eror msg="Failed to update indexable repositories" err="gitserver.FileExists: git.ResolveRevision: revision not found: github.example.com/org/empty-repo@HEAD"

Grafana will complain with the following critical alerts:
> - worker: less than 1 number of worker instances running the codeintel-auto-indexing job for 5m0s
> - worker: less than 1 number of worker instances running the codeintel-commitgraph job for 5m0s
> - worker: less than 1 number of worker instances running the codeintel-janitor job for 5m0s

**Comment by sfllaw** [comment]
Since the auto-indexing is not being done by the worker, its queue is now getting bigger and bigger:
![Screenshot from 2021-06-30 02-37-35](https://user-images.githubusercontent.com/155692/123938799-4eef9c80-d94c-11eb-9716-eb2a4c5e00a6.png)

**Comment by sfllaw** [comment]
Does it make sense for the worker to get stuck on repositories missing a revision?

If I were in its shoes, I would emit a warning and then send the invalid repository to the back of the queue to be retried. Possibly, I would add the error message to the queue itself, so an admin could try to resolve the problem?

Perhaps if the error were persistent, I'd give a way to remove the repository from the queue.

**Comment by abeatrix** [comment]
Hi @sfllaw. I am able to reproduce the issue on my end and agree that this should not be the expected behavior. I will look more into this with the team and you should be able to follow our process here. Thank you so much for bringing this to our attention!

**Comment by efritz** [comment]
@sfllaw Are you also running an instance of the Sourcegraph executor image? Currently auto-indexing is not advertised to be enabled on non-Sourcegraph hosted instances and requires some special (undocumented but not secret) setup to get running.

**Comment by sfllaw** [comment]
@efritz I'm not running sourcegraph/executor, since I'm running the single sourcegraph/server image. Is  `codeIntelAutoIndexing.enabled` incompatible with this configuration?

**Comment by efritz** [comment]
Today, yes you are correct. We currently don't advertise use of the executors outside of our Cloud environment. We are currently working on ways to bring this to enterprise/private instances (it currently requires baremetal instances for firecracker virt).

We should be more clear about the usability of the feature where it's publicly faced (fixed in https://github.com/sourcegraph/sourcegraph/pull/22626).
