### ISSUE TITLE
spike: Run src-cli in executor

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#22355]

**Comment by malomarrec** [comment]
See [scratchpad](https://docs.google.com/document/d/1hXklrrAerQwpFcOQZELgZoqyxmFOxI7DVEDGJV7sxxg/edit)

**Comment by eseliger** [comment]
Spike is done. Resulting tracking issue is here: https://github.com/sourcegraph/sourcegraph/issues/22550 and log entries are in the scratch pad document.
