### ISSUE TITLE
Long org names get squished on user settings sidebar

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#22370]
On Sourcegraph.com on my user settings page, the `sourcegraph-sentry-testing` org is squished. The circle icon is squished and the text is clipped.

![image](https://user-images.githubusercontent.com/1976/123342739-307d4180-d505-11eb-923c-e41c465061c1.png)

**Comment by fkling** [comment]
This doesn't appear to be an issue anymore.
![2024-02-08_22-21](https://github.com/sourcegraph/sourcegraph/assets/179026/7f1a067e-342e-417e-9af8-acebe9f0f08a)
