### ISSUE TITLE
Clicking Blame when logged out of sourcegraph produces divs that cannot be dismissed 

### ISSUE THREAD

**Issue by nikhildahake** [sourcegraph/sourcegraph#2239]
1) Open Chrome browser
2) Install Sourcegraph extension for chrome (Not necessary. Problem is with the site not the plugin)
3) Navigate to: https://sourcegraph.com/github.com/google/guava/-/blob/guava/src/com/google/common/annotations/VisibleForTesting.java#L7

4) Click 'Blame'. See attached image.
5) Dialog boxes show up which cannot be dismissed. They get dismissed when the page is reloaded.

![source_graph_bug](https://user-images.githubusercontent.com/2182360/52557145-9bd28700-2e14-11e9-8abf-acab17e24f86.png)

**Possible Solution**

Solution 1:
Auto dismiss after few seconds. 

window.onload = (function(){
  document.getElementsByClassName("sourcegraph-notifications")[0].innerHTML='';
}, 5000);

Solution 2:
Add a 'X' (close button) to the top of the box. Attach a handler to 'X' to close the div on 'onClick' event.

**Comment by felixfbecker** [comment]
Our notifications are dismissable now :)

![image](https://user-images.githubusercontent.com/10532611/78048557-2dcf8300-737a-11ea-96da-c67f7f488718.png)
