### ISSUE TITLE
insights: indexed data points in backend insight seem to be larger than unindexed

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#22401]
<img width="390" alt="CleanShot 2021-06-25 at 13 21 19@2x" src="https://user-images.githubusercontent.com/5090588/123481405-87901e80-d5b8-11eb-9f2a-eafab4af8673.png">

(ignore the scale on these images, it is truncated from the left, so they are less drastic changes that it seems)

In both of these insights there is a unusual uptick at the end. Each of these upticks would be points recorded by the indexed search recorder, and all of the previous points would be compressed historical results.

Possibilities:
1. Coincidence
2. Something about the historical compression is causing a discrepancy. We could test this by modifying the historical recorder to record the same latest point, and see if there is a difference from indexed results.
3. ~~This could be a manifestation of some limits in the unindexed path that don't exist in the indexed path (#21998 possibly related)~~

**Comment by coury-clark** [comment]
My assumption was that this was an artifact of 3) above, where searches were hitting the very low limits. Search team just recently refactored these limits to be much larger, so I re-ran these insights, and am still observing strange results. I haven't verified yet if these insights are completely backfilled, but it has been nearly 24 hours (which should be sufficient).

<img width="399" alt="CleanShot 2021-07-09 at 09 59 45@2x" src="https://user-images.githubusercontent.com/5090588/125112903-af917e80-e09c-11eb-8c62-7b5baa2fb82e.png">

**Comment by coury-clark** [comment]
Taking a look today after this running for a few days, something is very off.

<img width="1139" alt="CleanShot 2021-07-12 at 15 14 12@2x" src="https://user-images.githubusercontent.com/5090588/125362534-ea591800-e323-11eb-81c7-229e290a6760.png">

**Comment by coury-clark** [comment]
The giant drop in results is caused by #22777 and unrelated to insights. If we ignore that point we see the same results as above, where the value jumps from 86,161 to 102,846 on the first indexed search.

**Comment by coury-clark** [comment]
Digging into the results between the last historical point and the first indexed point. Let `H` be the set of historical repos at the last historical point, let `I` be the set of repos in the first indexed point.

`I / H = 245 repos`
`H / I = 22 repos`
`∑ I / H = 15578`
`∑ H / I = 820`

A few hypotheses come to mind
1. The query to resolve the chart is carrying forward the most recent observation for each distinct repository on the table. If a value were to trend to zero in the historical search, it would be forcefully queried because the historical backfiller queries for each repository; however, the indexed search recorder just takes the search result and stores it. If a repository were to go missing from the result between the historical backfill and the indexed recordings, it would be carried forward until a value is recorded for that repository. This may explain why some repositories in `H` are not in `I` but still get reported on the chart.
    * Having said that, in this case that may not be entirely responsible. Just picking an example, `github.com/sourcegraph/grafana` reports 550 results on both the last historical recording and the current indexed search.

2. For some reason there are repositories that are indexed in Zoekt that are not in the `repo` table. This could possibly explain the 245 repositories that exist in the indexed recordings, but not in the historical recordings. However, picking some sample repos and spot-checking the `repo` table shows that they exist (`repo_id: 12020,
12062,
12078,
12232,
12497,
12502,
12646,
12659,
12767,
12786,
12823,
12863`).
    * This raises the question - why weren't these repositories included in the historical recordings? They appear to be cloned both as a status in the `repo` table, and by virtue of returning indexed results in search.
    * Possibly the [logic](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/insights/discovery/all_repos_iterator.go?L28:6) for pulling repositories is flawed? This has supporting evidence that the `commit_index` table also is missing results for these repositories, which is populated by the same logic.

Both of these issues point towards a discrepancy caused by different recording mechanisms. Perhaps there is some way to unify the set of repositories that we are recording between historical and indexed search (in other words, between Code Insights and regular Search).

**Comment by slimsag** [comment]
Do I understand correctly that we always see an _increase_ with indexed search, never the other way around? (I see _a drop in results_ mentioned once above, but your message implies it turned out to be a separate issue?)

**Comment by slimsag** [comment]
> Let ∑ be the sum of the recorded values over a given set.

Is this describing the sum number of results found by search queries, or the sum number of values recorded (e.g. the number of repositories)?

**Comment by coury-clark** [comment]
> Do I understand correctly that we always see an increase with indexed search, never the other way around? (I see a drop in results mentioned once above, but your message implies it turned out to be a separate issue?)

I don't think I have any evidence at the moment to definitively say one way or the other. Based on the data above and similar insights I've looked in to, there is a larger set of repos that are in indexed set that aren't in the historical set which likely contributes to the significant growth.

I strongly suspect queries erroring out is partially to blame here, but at the time I looked into this there wasn't very good visibility. This is something I'm going to have to change before I can get more of an idea.

> Is this describing the sum number of results found by search queries, or the sum number of values recorded (e.g. the number of repositories)?

The sum of the search result values - the aggregated delta.

**Comment by slimsag** [comment]
Best explanation I would have after reading all of this would be the following hypothesis:

* We are specifying `OnlyCloned: true` in `RepoStore.List`, which seems sensible (i.e the insights code here seems sane to me.)
* The `RepoStore.List` implementation looks.. spotty.
  * These TODOs around `OnlyCloned` flag have not been addressed: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/database/repos.go?L762-773
  * There seem to be indicators of a separate `gitserver_repos` table; I didn't know this existed - but it certainly makes me question our design here a little bit more (why would the two not be the same table? seems odd): https://sourcegraph.com/github.com/sourcegraph/sourcegraph@61148fb0761d2b74badd3886d3221e817b4f1eb8/-/blob/internal/database/repos.go?L820

What we could do is perhaps reconsider this code from the POV of "what does zoekt do to discover repos to index?" to ensure what we do for unindexed searches remains in sync with zoekt generally.

* Zoekt fetches the list of repos to clone here: https://sourcegraph.com/github.com/sourcegraph/zoekt/-/blob/cmd/zoekt-sourcegraph-indexserver/main.go?L580
* That endpoint is defined [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/httpapi/router/router.go?L123:13), registered [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/httpapi/httpapi.go?L122:18) and implemented [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/httpapi/internal.go?L270:27).
* It does call the very same `RepoStore.List` API [right here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/httpapi/internal.go?L293-296), but it specifies `Index: true` instead of our `OnlyCloned: true` - it also doesn't appear to set pagination params(?) nor an `OrderBy` clause.
 
Hypothesis being: Maybe `OnlyCloned: true` is giving us a subset of the indexable repos (that'd be crazy, but the code doesn't look super reliable at first glance - so possible) or `Index: true` gives a larger set of repos for some reason. Maybe keep our pagination/order-by params, but swap `OnlyCloned: true` with `Index: &true`?

**Comment by slimsag** [comment]
Another possible variance would be this:

https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/searcher/search/search.go?L40-44

Searcher limits the # of results it can return to 20,000 matches for a single repository. It's possible we have a particularly large result set which, in indexed mode is returning e.g. 50k results but in unindexed is returning 20k only. Unfortunately there are probably a few more subtle ways in which unindexed search may differ from indexed that have not surfaced yet.

**Comment by coury-clark** [comment]
One contributing issue is found #23386, however this likely only accounts for a small and inconsistent part of this

**Comment by coury-clark** [comment]
Attemping to run an insight with the same repo fetching strategy as Zoekt to see what happens.
https://github.com/sourcegraph/sourcegraph/pull/23422

**Comment by coury-clark** [comment]
Something else occurred to me that may be contributing. If the commit index is dirty and only has a partial index (meaning it is up to date but missing historical commits) the compression algorithm may skip time intervals that should otherwise be queried. #23268 The compression algorithm should always try and query for the first and last interval for each repo, so this should only impact the interval in which values change.

**Comment by coury-clark** [comment]
Some initial analysis after re-running the insight with `Index: true` versus `Cloned: true` configuration for the `RepoStore`:
I - H = 5 repos
H - I = 159 repos

k8s dogfood is currently reporting a very large number (2132) of `missing` repositories. Not sure if this is relevant, and I don't have any idea of what that was reporting before the k8s refresh.

**Comment by coury-clark** [comment]
Re-ran the insight again with queue purging disabled, here's the chart before any indexed recordings. Less than 15 errors, so that likely doesn't explain the full gap. After the indexed recording we should see a jump; however, that may be expected.

At this point, I think that #22799 needs to be resolved to narrow down contributing factors.

<img width="394" alt="CleanShot 2021-08-02 at 16 42 46@2x" src="https://user-images.githubusercontent.com/5090588/127936657-f6c9bcae-3c87-4fdc-b64e-1993e67ff5a2.png">

**Comment by coury-clark** [comment]
One more observation:

The intervals are not consistent as they approach the `created_at` time of a data series, which is also the first indexed recording. For an underlying data value that grows rapidly, that could make it look like a significantly larger gap than at the older points. Here is a comparison of an "all repository insight" versus `sourcegraph/sourcegraph` for the same query over roughly the same time interval.

<img width="788" alt="CleanShot 2021-08-03 at 13 02 15@2x" src="https://user-images.githubusercontent.com/5090588/128078574-40429696-7d9b-41ea-a381-9be434e3e150.png">

If we look at the raw datapoints inside the "all repos" version but scoped specifically to `sourcegraph/sourcegraph`, we can see the last historical recording was `2021-06-18`.
| time | value |
| :--- | :--- |
| 2021-08-02 | 2524 |
| 2021-08-01 | 2524 |
| 2021-07-30 | 2524 |
| 2021-06-18 | 1568 |
| 2021-05-19 | 1143 |
| 2021-04-19 | 987 |
| 2021-03-20 | 865 |
| 2021-02-15 | 602 |

The logic behind the skipped last interval was to accommodate a potentially stale commit index, with the assumption that the indexed interval would occur near enough to the end of the last interval that it would be consistent all the way through. [Code](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/enterprise/internal/insights/compression/compression.go?L77-79=&utm_product_name=GoLand&utm_product_version=GoLand#L68:6)

There are a few reasons this behaves strangely.
1. The time intervals that would be built for a backfill starting on `2021-07-30` would have been queried close to the midpoint of each interval. #23515 presents a small bug in this behavior.
2. Choosing the midpoint may already be an incorrect choice for a time. The intervals are constructed such that the starting time is the time at which we want to record, and we are building a frame for what that value remains valid. This means we should also likely query for the most recent commit before a time, rather than the [nearest](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/enterprise/internal/insights/background/historical_enqueuer.go?L462) commit.

I suspect we should do the following:
1. Fix #23515
2. Modify the behavior of both the compressor and the backfiller to use the starting point of each frame as the recording time, and look for the most recent commit <= that time.

**Comment by coury-clark** [comment]
Closing - addressed by https://github.com/sourcegraph/sourcegraph/issues/23690
