### ISSUE TITLE
`src batch` fails on windows

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#22402]
See [thread](https://sourcegraph.slack.com/archives/CMMTWQQ49/p1624467371288100)

**Comment by LawnGnome** [comment]
Fixed by #22374.

**Comment by malomarrec** [comment]
@LawnGnome there was a [customer](https://docs.google.com/spreadsheets/d/1OEhzdMSlkGOaWyGKwdiAGlirsKKj9EN45Izn7kdKNTg/edit#gid=0&range=A94) that has an issue on windows. I think you were asking about their environment. 
Does this resolve their issue? Should someone investigate some more?

**Comment by LawnGnome** [comment]
@malomarrec Yep, the issue I linked above was spawned from the same Slack thread, and the customer has confirmed it resolves their issue. I closed this issue because it's a duplicate.
