### ISSUE TITLE
Code intel badges missing in references/definitions panel

### ISSUE THREAD

**Issue by Strum355** [sourcegraph/sourcegraph#22411]
- **Sourcegraph version:** Sourcegraph.com and local dev

#### Steps to reproduce:

1. Click 'find references' on a code intel hover 

#### Expected behavior:
Results would be badged with either Semantic or Search-based as per Figure 1

#### Actual behavior:

No badges are displayed, unable to tell apart search based results from semantic results as per Figure 2. 

---

I'm pre-emptively assigning frontend team, but feel free to reassign to e.g. extensions team if this is unrelated to the frontend team. 

As with https://github.com/sourcegraph/sourcegraph/issues/22316, full ownership does not yet lie with code-intel team (but hopefully soon 🤞)

**Figure 1** (screenshot from https://github.com/sourcegraph/sourcegraph/pull/18843)
![image](https://user-images.githubusercontent.com/18282288/123637299-c2db5900-d815-11eb-9b0f-2d922312c80f.png)

**Figure 2**
![image](https://user-images.githubusercontent.com/18282288/123637417-e7cfcc00-d815-11eb-8ba7-01e3e50d91c0.png)

**Comment by valerybugakov** [comment]
@limitedmage, it seems that `aggregableBadges` [were included](https://github.com/sourcegraph/sourcegraph/pull/22024/files#diff-090c6c469b59d788b9e111ec434ae3a33f060d670194223fcae7b97a0db4e92cL95-L100) into the `MatchItem` type in the [FileMatch](https://github.com/sourcegraph/sourcegraph/blob/main/client/shared/src/components/FileMatch.tsx) component. In [this PR](https://github.com/sourcegraph/sourcegraph/pull/22024) this logic was [changed](https://github.com/sourcegraph/sourcegraph/pull/22024/files#diff-090c6c469b59d788b9e111ec434ae3a33f060d670194223fcae7b97a0db4e92cR86-R96). I've looked into fixing this issue, but found out that [LineMatch](https://github.com/sourcegraph/sourcegraph/blob/main/client/shared/src/search/stream.ts#L31) type doesn't have `aggregableBadges` property. But this property is set in [referencesToFileLineMatch()](https://github.com/sourcegraph/sourcegraph/pull/22024/files#diff-77f61a0fb016c366a922fc35c3fd6b0b3640a5565e1de4d6787cad4ee8011e62R207) despite the return type being [FileLineMatch](https://github.com/sourcegraph/sourcegraph/blob/main/client/branded/src/components/panel/views/FileLocations.tsx#L194).

It looks like to fix the reported issue, we should either update streaming types or create an extended one to include `aggregableBadges` as it was in the previous implementation. Let me know what do you think about it.

**Comment by limitedmage** [comment]
@valerybugakov  Thanks for fixing this!
