### ISSUE TITLE
Docs: Deploying on docker-compose

### ISSUE THREAD

**Issue by dan-mckean** [sourcegraph/sourcegraph#22427]
Update the documentation for Deploying on docker-compose

[RFC 414 REVIEW: Distribution Docs – An Epic Crusade](https://docs.google.com/document/d/1oF4MhFdLbCNd_f1NfgqVaxk9lIFePp5XaJrGPshEIkA/edit#)

**Comment by bobheadxi** [comment]
> Would it be possible to give a sense of what small, medium, and large mean here?

_Originally posted by @emchap in https://github.com/sourcegraph/sourcegraph/pull/22965#discussion_r672415211_

**Comment by bobheadxi** [comment]
- [ ] Initial reorganization https://github.com/sourcegraph/sourcegraph/pull/23029
- [ ] Deploy-sourcegraph-docker clarity improvements https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/454
- [ ] Small, medium, large https://github.com/sourcegraph/sourcegraph/issues/22427#issuecomment-882926677
