### ISSUE TITLE
Docs: Upgrading kubernetes

### ISSUE THREAD

**Issue by dan-mckean** [sourcegraph/sourcegraph#22424]
Update the documentation for Upgrading Kubernetes

[RFC 414 REVIEW: Distribution Docs – An Epic Crusade](https://docs.google.com/document/d/1oF4MhFdLbCNd_f1NfgqVaxk9lIFePp5XaJrGPshEIkA/edit#)

**Comment by virginiaulrich** [comment]
Agreed we can close this since work we do here will be informed by prod ed team and done in collaboration and Q1 work needs to be finished first
