### ISSUE TITLE
Docs: Deploying Kubernetes

### ISSUE THREAD

**Issue by dan-mckean** [sourcegraph/sourcegraph#22425]
Update the documentation for Deploying Kubernetes

[RFC 414 REVIEW: Distribution Docs – An Epic Crusade](https://docs.google.com/document/d/1oF4MhFdLbCNd_f1NfgqVaxk9lIFePp5XaJrGPshEIkA/edit#)

**Comment by ryancurrah** [comment]
We are looking at purchasing sourcegraph and the bloat in the Kubernetes deployment is unreal. Minio, Jaeger, Prometheus, Grafana, cAdvisor daemonset, etc. We have a meeting with Will Camp today, we are going to want to talk about this.

**Comment by bobheadxi** [comment]
@davejrt for reference, might be good to align the structure of the kubernetes docs with the docker-compose ones:

- https://github.com/sourcegraph/sourcegraph/pull/23029
- https://docs.sourcegraph.com/admin/install/docker-compose

Let me know if you have any thoughts on the format!
