### ISSUE TITLE
API docs: "This repository does not have LSIF data" during LSIF uploads

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#22453]
@efritz I've noticed that, very briefly during LSIF uploads, a query for this:

```graphql
            query DocumentationPage($repo: ID!, $revspec: String!, $pathID: String!) {
                node(id: $repo) {
                    ... on Repository {
                        commit(rev: $revspec) {
                            tree(path: "/") {
                                lsif {
                                    documentationPage(pathID: $pathID) {
                                        tree
                                    }
                                }
                            }
                        }
                    }
                }
            }
```

The response `data.node.repo.commit.tree.lsif` field (not actually related to API docs at all, just the LSIF GraphQL API) returns `null`.

I'm surprised by this because I would think that during an LSIF upload for a repo, the old bundles would still be available. Any idea what might cause that? Happy to do some digging if you point me in the right direction

**Comment by efritz** [comment]
I think what happens is the upload of the new upload marks the old one as DELETED and the new one as COMPLETED (there's a unique constraint on repository_id, commit, path, indexer for all completed uploads). This does not yet update the commit graph for the repository.

This means that when asking for completed uploads for that particular commit (before the commit graph updater runs), you'll only get the DELETED upload, which are filtered out at the SQL level (as the new one isn't in the commit graph data in Postgres).

There may be a few paths forward:

- force run the commit graph update on uploads
- introduced a new state REPLACED that is like DELETED but can still answer queries until the commit graph is refreshed
- introduce a new state PROCESSED that is like COMPLETED but doesn't have the same unique constraint; the commit graph updater can then replace uploads shadowed by PROCESSED one and promote PROCESSED uploads to COMPLETED

Happy to chat live about this as well.

**Comment by slimsag** [comment]
thanks for the response, I actually think this will become a critical issue for API docs. I've noticed on several occasions the golang/go API docs are completely unavailable due to pending uploads, yuck.

Your explanation / paths forward mostly make sense to me, thank you for detailing that. Do you have a preferred path forward, or one that you think would be easier than the others to implement? Could you maybe give me more pointers / a mini roadmap of what implementing that change might look like (where would I start looking around in the code?) - I'll probably try to work on this sometime this week

**Comment by efritz** [comment]
Can you throw a meeting on my calendar to discuss/pair a solution here? In the meantime here are the relevant places in code that would need to change (I'm not sure which of my _very incomplete_ list of suggestions would be best here, if any):

- Commit graph updater routine (in worker, runs periodically): https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/worker/internal/codeintel/commitgraph/updater.go?L49
- Repository marked as dirty after upload: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/precise-code-intel-worker/internal/worker/handler.go?L164
- Finding candidate index files to query: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@c9b52fc09645549ec6d5cefd62b8d401a4a51053/-/blob/enterprise/cmd/frontend/internal/codeintel/resolvers/exists.go?L40

The process currently works as:

- after an upload (or after a request for a commit we don't have any reachable data for), we mark the entire repository commit graph as dirty by bumping a dirty counter up by one
- a periodic routine will look for repositories where updated_token != dirty_token (the counter) and will refresh the commit graph and set updated_token=dirty_token at the time of the read
- the periodic routine takes an advisory lock for that repository during processing, ensuring the commit graph is updated only once concurrently

This has the property that if there are multiple uploads or multiple requests for an unknown commit, they will all be batched into a "last update wins" update, saving a bunch of expensive calculation and db writes.

We'd need to move in one of two directions:

- stop avoiding work aggressively here and update the commit graph more frequently (caution: the workload caused issues in enterprise instances in the past)
- stop immediately making stuff in the cached commit graph invisible before the commit graph is refreshed (i.e., defer work to the commit graph update to be finalized)
