### ISSUE TITLE
Code Insights: Get rid of `QueryInputInViewContent` component in insights view component and by this simplify prop interfaces

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#22462]
### Background
Historically Code Insights pages with insights are built on top of `ViewContent` component from the` /views` product area. `ViewContent` uses `QueryInputInViewContent` which uses a lot of infrastructure props from the top level of the app. That means that if we want to render code insights on some page we have to specify all these infrastructure props. That requires a lot of information from top-level components and usually inconvenient from a development point of view, plus that increases the complexity of using code insights as independent components. 

We can't just delete `QueryInputInViewContent` from `ViewContent`  because this component is used by `/views` area components.

### Proposal
In order to preserve all view area-specific logic and simplify code insights components only, we can create our own view similar to `ViewContent` but without `QueryInputInViewContent` and all these infra props.

**Comment by felixfbecker** [comment]
> We can't just delete QueryInputInViewContent from ViewContent because this component is used by /views area components.

I'd argue that we _can_ just delete the entire `/views` area if it's a hassle – we don't need to break a leg to continue to support it.
