### ISSUE TITLE
Unexpected behavior/confusing UX when clicking "Enable and clone all" button

### ISSUE THREAD

**Issue by KattMingMing** [sourcegraph/sourcegraph#2247]
The `site-admin/repositories` page has an _Enable and clone all_ button that is located at the bottom of the list of repositories.

**Current behavior**

Clicking the button enables all repositories and clones all repositories even if they are not found in the currently filtered list.

**Expected behavior**

Users expect that the button's action would correspond to the repositories found in the filtered list and that the button _Enable and clone all_ would only enable and clone all repositories found in the filtered list.

Possible solutions:

1. The _Enable and clone all_ button should respect the state of the radio button filter and only enable and clone all repositories found by that filter, not all possible repositories.
2. Enable and clone all should show the number of repositories to be cloned so users can quickly see that the repositories are incorrect.

This issue might be resolved via https://github.com/sourcegraph/sourcegraph/issues/2057

**Comment by sqs** [comment]
Yeah, part of #2057 and #2025 will be removing the concept of enable/disable for repositories, so this button would be removed. I’ll keep this open until that is done.

**Comment by keegancsmith** [comment]
Fixed by #2025
