### ISSUE TITLE
Creating a search insight shows a toggle to use the backend if the flag is enabled

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#22489]
If you have enabled the backend flag #22488 then when you create a search insight you should see a toggle/radio option that lets you use the backend to run your insight. 

It's up to Vova/Coury/Alicja to make some best-guess ad-hoc decisions if we move faster than I can contribute to here, but I imagine if you're using the backend we need to: 
- communicate what's happening
- make it easy to run over all your repos 
- disable the custom colors + granularity options, I think 
- might even need to disable the permissions?

**Comment by coury-clark** [comment]
> disable the custom colors + granularity options, I think

I think we can keep custom colors since that's just rendered client side. @vovakulikov can confirm

> might even need to disable the permissions?

I'm not sure I understand what this means. Do you mean personal / org specific insight?

**Comment by vovakulikov** [comment]
@coury-clark about colors. 
It would be more convenient for the FE client not to store insight information except backend id (id is needed for the FE dashboards and BE insights migration). Currently, we have a fallback color for a backend insight just because we don't have a series color field in our gql API but eventually, I would prefer to have them in gql API rather in the client settings.

**Comment by coury-clark** [comment]
@vovakulikov I agree eventually all of the metadata (including ids) will live in the database, but keeping in mind that we are temporarily keeping the settings model - there shouldn't be any reason we can't keep color selection, since there is no change to the schema, right?

**Comment by vovakulikov** [comment]
Hmm. By keeping the settings model you mean that in the creation UI for all repositories mode (backend insight case) we still will write insight configuration in user/org settings, right? I just thought that we will use some gql handler that saves backend insights in DB and returns id as a result and then we can save this id in `insightIds` of some dashboard.

**Comment by vovakulikov** [comment]
If it is the case then I don't see any reason why we can't keep color and other insight settings.

**Comment by coury-clark** [comment]
@vovakulikov just for clarity, [here](https://docs.google.com/document/d/1BCZ1v95NACk9f32Iq0aWVgv2j_vxKYLSkPDZlcM_c68/edit?ts=60ddb357#heading=h.fl8youkd7uwp) is where this is specified. The point is that we don't gain very much right now by moving them, and we are squeezed as is on roadmap for beta. This is definitely a priority in the medium term though, and I've opened #22524 to track this.

**Comment by Joelkw** [comment]
@felixfbecker @vovakulikov I think this Issue can be closed now?

**Comment by Joelkw** [comment]
bias to action and closing it
