### ISSUE TITLE
Ability to drag to select lines of code to share

### ISSUE THREAD

**Issue by pdubroy** [sourcegraph/sourcegraph#22491]
#### Feature request description

Requested by https://docs.google.com/spreadsheets/d/1OEhzdMSlkGOaWyGKwdiAGlirsKKj9EN45Izn7kdKNTg/edit#gid=0&range=A1902 

The request was:
> Ability to drag to select lines of code to share. Right now I don't see a way to select more than one line to add it to the shareable

#### Additional context

Currently, it's possible to link to an individual line by clicking on the line number or in the margin to the left of the line number. As described by the customer here, one possible implementation for linking to multiple lines would be support a click-and-drag operation in the same area.

**Comment by fkling** [comment]
This was implemented when we moved to CodeMirror.
