### ISSUE TITLE
Diff view: commit title can overlap with commit sha/parent

### ISSUE THREAD

**Issue by pdubroy** [sourcegraph/sourcegraph#22497]
## Details

- **Sourcegraph version:** Sourcegraph.com
- **Platform information:** Chrome Version 91.0.4472.114 (Official Build) (x86_64) on macOS

#### Steps to reproduce:

1. Go to https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/4a6ca65e1d8c3154dac83e5b067513f575f6cb09?visible=6
2. Shrink window width — at about 1250px, the commit title starts to overlap with the element that shows the SHAs of the commit and its parent:
    
    ![CleanShot 2021-07-01 at 10 05 46](https://user-images.githubusercontent.com/17293/124093497-379dd580-da58-11eb-9bb1-cf36edf9e403.png)

#### Expected behavior:

Text does not overlap.

#### Actual behavior:

Text is overlapping.

## Comments

The simplest fix is probably to allow the commit title to wrap. A more sophisticated solution (not necessarily required) is to do something like GitHub does, and limit the title text to 69 characters and put the remainder on the next line:

![CleanShot 2021-07-01 at 10 47 05](https://user-images.githubusercontent.com/17293/124095242-c5c68b80-da59-11eb-8fc0-9f184e28836d.png)

**Comment by fkling** [comment]
It seems we hide the overflow now and show ellipsis.
