### ISSUE TITLE
Browser extension: bitbucket.org support

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#2250]
Support Bitbucket.org in the browser extension.

cc @sqs for prioritization

Related: 
* https://github.com/sourcegraph/sourcegraph/issues/244
* https://twitter.com/heyyoni/status/1095096741140021248

**Comment by christinaforney** [comment]
@muratsu - does https://github.com/sourcegraph/sourcegraph/pull/25084 mean we can close this?

**Comment by muratsu** [comment]
Yes @christinaforney ~ we can close this issue.
