### ISSUE TITLE
search docs examples throw ugly commit error

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#22531]
Changing some things in the docs and noticed one of our examples just borks with a weird error

<img width="1408" alt="Screen Shot 2021-07-01 at 1 29 49 PM" src="https://user-images.githubusercontent.com/888624/124185995-85bed300-da70-11eb-9824-ec89b9bcb4d0.png">

> Strconv.ParseUint: parsing "0\nwarning: refname '2a80128c8601a387809434efb23d09ac2d31d025' is ambiguous. Git normally never creates a ref that ends with 40 hex characters because it will be ignored when you just specify 40-hex. These refs may be created by mistake. For example, git switch -c $br $(git rev-parse ...) where "$br" is somehow empty and a 40-hex ref is created. Please examine these refs and maybe delete them. Turn this message off by running "git config advice.objectNameWarning false"": invalid syntax (and 413758 more)

**Comment by stefanhengl** [comment]
I cannot reproduce this anymore. @rvantonder please reopen if you think the issue still exsists.

![image](https://user-images.githubusercontent.com/26413131/171870642-9fa2d23c-6459-4c98-b5f0-c18ca6ac7e7b.png)
