### ISSUE TITLE
"Repositories" user menu items gives 404 on k8s.sgdev.org

### ISSUE THREAD

**Issue by pdubroy** [sourcegraph/sourcegraph#22539]
- **Sourcegraph version:** k8s.sgdev.org
- **Platform information:** Chrome Version 91.0.4472.114 (Official Build) (x86_64) on macOS

#### Steps to reproduce:

1. Go to k8s.sgdev.org
2. Make sure you are signed in.
3. Click on your profile picture in the top right.
4. Click on "Repositories" in the menu.

#### Expected behavior:

Either "Repositories" is not visible (is it only supposed to be there on Cloud?), or clicking on it takes me to the repository settings.

#### Actual behavior:

I see a 404 message in the settings area:

![CleanShot 2021-07-02 at 09 58 41](https://user-images.githubusercontent.com/17293/124242416-05a27700-db1d-11eb-9707-385009061ce6.png)

**Comment by emchap** [comment]
@sourcegraph/core-application This is also broken on Demo and was reported by a customer: https://sourcegraph.slack.com/archives/C01PFK3CS49/p1626459861000700

**Comment by gabtorre** [comment]
A customer reported this on their K8s instance.
https://sourcegraph.slack.com/archives/C027S6MLPT8/p1629317171000500

I can see this on the support Docker Compose 3.30.3 instance as well.

**Comment by topebali** [comment]
A customer reported this also, on their k8s instance
https://sourcegraph.slack.com/archives/CT9P97S6L/p1629445565020400
