### ISSUE TITLE
Github dark mode hovers look wrong

### ISSUE THREAD

**Issue by muratsu** [sourcegraph/sourcegraph#22536]
@Joelkw to add detail

**Comment by erzhtor** [comment]
Hey, @muratsu, @Joelkw! Is this still an issue? If so, can you, please add a description of what should be updated. Otherwise, may we close this?
<details>

![image](https://user-images.githubusercontent.com/6717049/144599856-0d1d0d85-2ef0-43fd-b7b2-0a3fcc4720ca.png)

</details>
