### ISSUE TITLE
Symbol search is too slow to provide jump-to-definition on torvalds/linux

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#2257]
## Problem

Jump-to-definition doesn't work on torvalds/linux (e.g. [dc21285.c#L252:13](https://sourcegraph.com/github.com/torvalds/linux@aa0c38cf39de73bf7360a3da8f1707601261e518/-/blob/arch/arm/mach-footbridge/dc21285.c#L252:13)). This was reported by a user in https://github.com/sourcegraph/sourcegraph/issues/1625 and will likely be a showstopper for companies with monorepos. I expect a "Go to definition" button next to "Find references", but it actually isn't there:

![image](https://user-images.githubusercontent.com/1387653/52597841-e64e0680-2e08-11e9-9669-3f48c5c864b0.png)

## Finding the bottlenecks

From the browser's perspective, the request took 10.15s:

![image](https://user-images.githubusercontent.com/1387653/52597809-cd455580-2e08-11e9-9a67-3956313aa788.png)

The query was: `\bfootbridge_cfn_mode\b case:yes file:.(c|cc|cpp|hh|h)$ type:symbol repo:^github.com/torvalds/linux$@aa0c38cf39de73bf7360a3da8f1707601261e518`

The [LightStep trace](https://app.lightstep.com/sourcegraph-prod/trace?span_guid=4a19e26d56caa52f&at_micros=1549923788112034#span-4a19e26d56caa52f) from the `x-trace` header in the HTTP response shows that 99% of the time was spent blocked on a `symbols.Client.httpPost`:

![image](https://user-images.githubusercontent.com/1387653/52598136-c9fe9980-2e09-11e9-8741-d3640593c59e.png)

I later found the [rest of the trace](https://app.lightstep.com/sourcegraph-prod/trace?span_guid=1a290c80f10c5a14&trace_id=70d402b5b6437a76&tracer_id=424df437e6c0b0ba&operation_name=search&at_micros=1549924585495011#span-1a290c80f10c5a14) through LightStep's UI (and filed https://github.com/sourcegraph/sourcegraph/issues/2248), and this trace shows 30% of time spent in `decodeSymbols` and 70% of time spent in `filterSymbols`:

![image](https://user-images.githubusercontent.com/1387653/52598694-755c1e00-2e0b-11e9-829a-51bf2cd7d309.png)

## Understanding how the symbols service works

**Parsing tags out of files**

Parsing is triggered by a HTTP `/search` request.

The symbols service main process fetches a tar from gitserver and passes file contents over stdio to [N child ctags processes](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/symbols/internal/symbols/parse.go#L24-37) running in [interactive mode](http://docs.ctags.io/en/latest/interactive-mode.html) in parallel.

The ctags processes pass tags back to the main process over stdout, and the main process collects all the tags in a [giant slice of symbols](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@318feaba8e6909c739c1ad172a02078f1f3c039f/-/blob/cmd/symbols/internal/symbols/parse.go#L81-121) in Go then [gzips it and writes it to the disk cache](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@318feaba8e6909c739c1ad172a02078f1f3c039f/-/blob/cmd/symbols/internal/symbols/index.go#L78) at `/mnt/cache/symbols-$POD/$REPO_HASH.zip`.

**Querying tags**

Queries are served on the HTTP `/search` endpoint.

The main process reads and decodes (`decodeSymbols`) the giant slice of symbols from the [disk cache](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@318feaba8e6909c739c1ad172a02078f1f3c039f/-/blob/cmd/symbols/internal/symbols/index.go#L44) then filters (`filterSymbols`) them [by looping over each symbol and matching against the given regexes](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@318feaba8e6909c739c1ad172a02078f1f3c039f/-/blob/cmd/symbols/internal/symbols/search.go#L102). The main problem is that to find even a single symbol, it has to load the **entire** cache archive into memory at once and loop over each symbol. The symbols are neither sharded nor indexed.

## Ideas for improvements

There 2 primary use cases to support:

- Find an exact symbol (needed by basic code intel)
- List all the symbols in a file (needed by the symbols view in the future, once it's scoped to the current file)

**Sharding by symbol name and/or file path**

The symbols service could hash symbol names into N buckets and write N tars to disk (with the same slice-of-symbols format). It could also do the same for file paths (using 2x disk space). That way, the symbols service would only need to read 1 of those N tars to find an exact symbol or for symbols in an exact file.

**Indexing by symbol name and/or file path**

Instead of only a slice-of-symbols format, the symbols service could also write an index into the file:

```go
type NewFormat struct {
  Symbols []protocol.Symbol // same as current format
  SymbolNameIndex map[string][]int // symbol name to list of indexes into .Symbols of symbols that have that name
  FilePathIndex map[string][]int // file path to list of indexes into .Symbols
}
```

That would slow down `decodeSymbols` a little bit (have to also decode the 2 indexes), but would make `filterSymbols` nearly constant-time.

**Separate index files**

The same as the previous section, but put each `map[string][]int` in a separate file and make the `int` refer to a byte offset in the slice-of-symbols file (rather than an index) so that the symbols service can seek + read a tiny part of the file.

**Micro-optimizations**

From @slimsag:

> I think just from implementing exact string matching, or even substring matching, you would skip the cost of regex matching 200k+ symbol paths/names and would see gains of 50-65% in terms of time to result

> also note `symbols []protocol.Symbol` is used everywhere, which means e.g. looping over `symbols` with a for loop causes every `protocol.Symbol` to be copied, and each one contains several fields, so 8+8+8+8+8+8+8+8+8+1 bytes being copied around for every one. It may be worth testing perf if you change those to pointers

> Other nasty stuff here includes every symbol having its own `Language` and `Path` strings, despite the high odds they will all have close to the same ones, etc

From @keegancsmith 

> Yeah this line in particular is bad https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/symbols/internal/symbols/search.go#L134
> Stop starting a regex engine is slow, and we do it for lots of small strings (symbol name). I would suspect if we were to adjust the symbols search to just re-use searcher it would be much faster.

**Zoekt supports ctags**

From @keegancsmith:

> zoekt already has support to take the output of ctags

**Postgres**

TODO @slimsag to fill in

## Refs

- https://github.com/sourcegraph/sourcegraph/issues/1625
- https://github.com/sourcegraph/sourcegraph/issues/1738
- https://github.com/sourcegraph/sourcegraph/issues/1964
- https://sourcegraph.slack.com/archives/C07KZF47K/p1549409281707800 (research by @slimsag)
- https://sourcegraph.slack.com/archives/C0C324C91/p1549917863003300 (lots of ideas for improving symbol search)

**Comment by tsenart** [comment]
Is this going to be done in time for the 3.1 release?

**Comment by chrismwendt** [comment]
Just chatted with @slimsag in person and decided to go with sharding by symbol name + special-casing queries like `^foo$` to do exact matches.

@keegancsmith Do you know if zoekt can do ctags searches directly? It sounds like it uses ctags for ranking, but I'm not sure if it can return ctags results alone. Is there some kind of API for this?

**Comment by chrismwendt** [comment]
@tsenart Yes, this will probably be done in time for 3.1.

**Comment by keegancsmith** [comment]
> @keegancsmith Do you know if zoekt can do ctags searches directly? It sounds like it uses ctags for ranking, but I'm not sure if it can return ctags results alone. Is there some kind of API for this?

I thought you could use the `symbol:` token but that doesn't seem to work when I experimented on https://cs.bazel.build

I'm not sure if sharding by symbol name/path will give you much performance benefit. I think there is a _lot_ of room for just optimizing the engine as it is. How about this for an idea:

A zip file where each file contains all its symbol text, new line seperated. Additionally you store as metadata line number => symbol metadata. You can then re-use searcher's fast searching logic to find linematches, and hydrate those results into proper symbol results.

Another alternative which may suit symbol search very well, especially in the case of JIT / caching indexes. Just use sqlite. I have no idea if the perf is good, but the model of how sqlite works suits this use case.

**Comment by keegancsmith** [comment]
Also I am unsure if symbols service has this, but we used benchmarks very effectively in searcher to find the low hanging fruit. The benchmark would happen against actual upstream repos. https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+f:cmd/search+Benchmark

**Comment by chrismwendt** [comment]
**Update**

Locally, adding `^...$` to the symbol name in a symbol search makes `filterSymbols` ~6x faster:

- 0.346s [`repo:^github\.com/kubernetes/kubernetes$ test-setup type:symbol`](http://localhost:3080/search?q=repo:%5Egithub%5C.com/kubernetes/kubernetes%24+test-setup+type:symbol)
- 0.056s [`repo:^github\.com/kubernetes/kubernetes$ ^test-setup$ type:symbol`](http://localhost:3080/search?q=repo:%5Egithub%5C.com/kubernetes/kubernetes%24+%5Etest-setup%24+type:symbol)

In the context of code intel, however, adding `^...$` had almost no effect because the search time is dominated by the `file:(c,h,cpp,hpp)$` filter, which is executed first. The `language:` doesn't help because it also turns into a regex like `(c,h,cpp,hpp)$`.

I'm going to run regexes that start with `^...` first to get that speed boost.

**Comment by chrismwendt** [comment]
Oops, I didn't see your comments before posting that :point_up:

Regarding using searcher: how would that metadata (line number -> symbol) be stored? If it's the same gob format on disk, it'll still take ~3s to load it into memory, regardless of how fast the search is.

Interesting, I'd like to try sqlite. Would you recommend exactly one DB file, or one per repository@commit?

**Comment by slimsag** [comment]
sqlite sounds like an interesting approach 👍I think that would give you the benefits of postgres, basically, but without having to wire up things through the frontend etc. and it acting as persistent data (instead it is just a 'cache'). I assume you would want to use a single DB file, or else you would end up with many small files due to some repos being small in size.

**Comment by felixfbecker** [comment]
Btw you might wanna investigate why the trace was lost between the frontend and symbols service - either the symbols client doesn't inject trace data, or the symbols server doesn't extract it.

**Comment by slimsag** [comment]
#2248

**Comment by keegancsmith** [comment]
I would go for a sqlite db per repo@commit, since that is how we shard and will make cache eviction much easier. Lots of files isn't a problem for sqlite if I am not mistaken.

> , adding `^...$` to the symbol name in a symbol search makes `filterSymbols` ~6x faster:

This isn't surprising. The regex engine should optimize that to a string equality check. Without the `^` it should optimize it to a string index check (although might not, we may be passing weird options around treating new lines).

> In the context of code intel, however, adding `^...$` had almost no effect because the search time is dominated by the `file:(c,h,cpp,hpp)$` filter, which is executed first. The `language:` doesn't help because it also turns into a regex like `(c,h,cpp,hpp)$`.

Thats the funny thing about how we have implemented symbol service. The file path is actually longer than the symbol text we are trying to match against and we don't layout the data so we only need to do one file path check for all the symbols in a file. Additionally the regex engine may not optimize regexs like the above. However, creating a O(n) matcher for those sort of patterns is something you may have learnt in undergrad ;)

> Regarding using searcher: how would that metadata (line number -> symbol) be stored? If it's the same gob format on disk, it'll still take ~3s to load it into memory, regardless of how fast the search is.

I wouldn't use the same format. I'm unsure what I would do, maybe use some sort of embedded db like bolt? Just something which won't require us to deserialize all the data.



BTW this is a fun thing to fix, and doing it properly will be very much worth it.

**Comment by chrismwendt** [comment]
WIP branch for sqlite https://github.com/sourcegraph/sourcegraph/compare/symbols-sqlite (one sqlite db per repo@commit, and an index on the `name` column)

The results look promising:

- kubernetes/kubernetes: regex search for current implementation is 1.02s, WIP branch is 0.45s (and 0.02s for exact name search!)
- torvalds/linux: regex search for current implementation is 4.5s, WIP branch is 2.1s (and 0.02s for exact name search, too!)

**Comment by sqs** [comment]
Moving to 3.2 because it's past the release branch cut date

**Comment by chrismwendt** [comment]
Now that sqlite has been deployed to production, we can review the impact this has had on our metrics.

From the browser's perspective, the request took ~~10s~~ 200ms:

![image](https://user-images.githubusercontent.com/1387653/53282525-8b13f200-36ed-11e9-99ef-28b437925fcb.png)

The first part of the LightStep trace shows again that most time is spent blocked on a call to the symbols service:

![image](https://user-images.githubusercontent.com/1387653/53282538-c1517180-36ed-11e9-80e6-768bca310726.png)

sqlite responded in **1ms**!

![image](https://user-images.githubusercontent.com/1387653/53282543-e514b780-36ed-11e9-9da8-7d3004310d14.png)

Oh, and the memory usage dropped a LOT:

![image](https://user-images.githubusercontent.com/1387653/53282560-1c836400-36ee-11e9-914d-07f5e209a3c4.png)
