### ISSUE TITLE
Odd "start typing" state appearance in code insights creation ui repositories field 

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#22609]
### Background
Currently, we're showing the start typing state immediately as soon as user focused field with autosuggestions.

Feedback from @pdubroy 
>As soon as I focused the field, the autocomplete dropdown appears with the text “start typing”. I found this a bit odd, as it’s not how most autocomplete interfaces work. Usually, the dropdown only appears once there are suggestions.

![image](https://user-images.githubusercontent.com/18492575/124571231-474e5d00-de50-11eb-9ee7-c1e227cdf45d.png)

https://user-images.githubusercontent.com/18492575/124571769-c479d200-de50-11eb-9998-d29864af8aba.mp4

**Comment by AlicjaSuska** [comment]
I agree with the feedback. We can eliminate the 'start typing' state and show the suggestions once they are available. @vovakulikov do you need any additional design input for this issue?

**Comment by vovakulikov** [comment]
Nope, @AlicjaSuska seems like a simple and straightforward change.
