### ISSUE TITLE
Exact match field value is excluded from suggestions in the code insight creation UI 

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#22610]
### Background
We exclude already typed valid repo names from the suggestions system to avoid duplications in a field with autosuggestions but some users found this behavior odd and stange 

Feedback from @pdubroy 
>I was a bit confused by the behavior of the suggestions, that when my query is an exact match, it disappears from the suggestions. I would expect it to still be visible and to be the first suggestion. Again, this is similar to how other autocomplete dropdowns work (e.g., Google)

**Comment by unclejustin** [comment]
Example of problem:


https://user-images.githubusercontent.com/1855233/128102540-5719ab14-525d-466b-a548-d84e1594bd14.mov
