### ISSUE TITLE
Search info bar provides incorrect message when using quotes in the after: filter

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#22628]
![image](https://user-images.githubusercontent.com/539268/124687813-a4bfc980-dea3-11eb-9c31-f2f4828a190e.png)

The Searching literally (including quotes) message above is not required or accurate here as the quotes in the after filter are part of the filter, not the search terms.

**Comment by rvantonder** [comment]
cropped up again:
<img width="1160" alt="Screen Shot 2022-07-20 at 7 40 34 AM" src="https://user-images.githubusercontent.com/888624/180010561-1102d0dc-9c65-460d-91c1-71572f120e9c.png">
