### ISSUE TITLE
GitLab oauth returns oauth2: Context missing state value

### ISSUE THREAD

**Issue by VeselaHouba** [sourcegraph/sourcegraph#2263]
- **Sourcegraph version:** 3.0.0 , 3.0.1
- **Platform information:** Docker version 18.09.1, build 4c52b90
#### Steps to reproduce:

1. Set up GitLab application according to https://docs.sourcegraph.com/admin/auth/#gitlab
![screenshot 2019-02-12 at 13 37 00](https://user-images.githubusercontent.com/6410423/52636016-b9165c80-2ecb-11e9-8484-317695cb5836.png)

2. Set up authorization in management console
```
  "externalURL": "http://192.168.11.90",
  "auth.providers": [
    {
      "type": "builtin",
      "allowSignup": true
    },
    {
      "type": "gitlab",
      "displayName": "GitLab",
      "clientID": "5b8b22c5e....<removed>",
      "clientSecret": "e6c112314.......<removed>",
      "url": "https://<url_to_my_gitlab_homepage>"
    }
  ]
```

#### Expected behavior:
- Hitting "Sign in with GitLab" button
- GitLab Sign-in page shows
- Logging in GitLab
- Logged in Sourcegraph

#### Actual behavior:
- Hitting "Sign in with GitLab" button
- GitLab Sign-in page shows
- Logging in GitLab
- Redirected to 
```
http://192.168.11.90/.auth/gitlab/callback?code=c77cd52f08471a2c8cca55b8a35455e26f9f0fae5047f8313d1f2d8be582918c&state=eyJSZWRpcmVjdCI6IiIsIlByb3ZpZGVySUQiOiJodHRwczovL2dpdGxhYi5iZXRzeXMuY29tLyIsIkNTUkYiOiJCWDc4cWxrUzFVWEJ2cVRoVXRxUXo1WmJfMUpHb0RTcUZFRzRmS19Cd25rIn0
```
and page contains only
```
oauth2: Context missing state value
```

**Comment by VeselaHouba** [comment]
Seems to be working with no problem in 3.1.1

**Comment by beyang** [comment]
Closing in favor of https://github.com/sourcegraph/sourcegraph/issues/3917
