### ISSUE TITLE
`select:` for simple query doesn't stream

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#22649]
I think this should stream, but it doesn't. To investigate....

[`(parse(.|\n)*parameters)|(parameters(.|\n)*parse) file:\.go select:repo`](https://sourcegraph.com/search?q=%28parse%28.%7C%5Cn%29*parameters%29%7C%28parameters%28.%7C%5Cn%29*parse%29+file:%5C.go+select:repo&patternType=regexp)

The code this kind of query runs through out to be sending results as soon as it's deduped: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/search/streaming/stream.go?L70&subtree=true

Locally it takes longer with `select:repo`, and streams results without it, so there's definitely something up with the postprocessing. 

I think it's because of this `select:repo` optimization for zoekt, which doesn't stream: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/search/zoekt/indexed_search.go?L401:22&subtree=true IT appears that way, because `select:file` works just fine 

Yeah it's because of this optimization, it's blocking and not sending results asap.

[`(parse(.|\n)*parameters)|(parameters(.|\n)*parse) file:\.go select:file`](https://sourcegraph.test:3443/search?q=%28parse%28.%7C%5Cn%29*parameters%29%7C%28parameters%28.%7C%5Cn%29*parse%29+file:%5C.go+select:file&patternType=regexp)

Branch

https://github.com/sourcegraph/sourcegraph/tree/rvt/debug-and-select

**Comment by rvantonder** [comment]
@sourcegraph/search-core thoughts on how we can make `select:repo` results stream? In the two cases where `select:repo` applies we call `zoekt.list` that seems to batch the request and takes a long time to time-to-first-result (like 13s+ on Sourcegraph.com). Ideas to stream `select:repo` results incrementally (can we page? we can't page along the global search path, but we can page concurrently on the non-global path)

https://sourcegraph.com/github.com/sourcegraph/sourcegraph@c0a4d591d4d28ea94b4e26258a95f62bf36dcf01/-/blob/internal/search/zoekt/indexed_search.go?L625&subtree=true

https://sourcegraph.com/github.com/sourcegraph/sourcegraph@c0a4d591d4d28ea94b4e26258a95f62bf36dcf01/-/blob/internal/search/zoekt/indexed_search.go?L467&subtree=true

**Comment by keegancsmith** [comment]
Yeah I think we should not use zoekt.List, and instead just do a streaming search where we transform the results into repo results. If you specify in the zoekt options max 1 result repo shard this should work? cc @stefanhengl since that may interact badly with merged shards / I remember us adding workarounds in list around this.

**Comment by rvantonder** [comment]
Ooo yeah the max 1 result repo shard option would probably be a good way enable this. Was worried that just doing it on FileMatches would force us to set some high match count to collect enough repo results.
