### ISSUE TITLE
Sourcegraph trying to clone repos from a git mirroring system that aren't mirrored

### ISSUE THREAD

**Issue by ijsnow** [sourcegraph/sourcegraph#2265]
- **Sourcegraph version:** 3.0.x
- **Platform information:** Docker, GitHub Enterprise WITH a git mirroring system in front of GHE

A customer has a git mirroring system in front of their GitHub Enterprise. They have a number of git organizations that are not mirrored on their mirroring system. On Sourcegraph 2.X, these organizations were ignored. This is the desired behavior for this setup. However, in 3.0, Sourcegraph attempts to clone these repos, increasing load on the mirroring system. 

#### Steps to reproduce:

1. Run Sourcegraph 3.0.x, GitHub Enterprise, and a git mirroring system
2. Configure Sourcegraph to clone from the git mirroring system

#### Expected behavior:

Sourcegraph doesn't try to clone repositories that aren't in the mirroring system even though they are on GitHub Enterprise.

#### Actual behavior:

Sourcegraph tries to clone repositories that aren't in the mirroring system.

**Comment by dadlerj** [comment]
FYI, reported by a customer at https://app.hubspot.com/contacts/2762526/company/561806411

**Comment by nicksnyder** [comment]
To add context here that I shared with @ijsnow in person:

1. External services were added in 3.0, but that shouldn't change what gets cloned, just where the configuration is stored (unless the configuration was somehow changed in that migration).
2. The default repo-updater scheduler was updated in 3.0, but that shouldn't change what gets cloned

**Comment by tsenart** [comment]
Hey @ijsnow, thanks for reporting! Would you be able to get us the exact site configuration and external service configuration being used? That'd help troubleshooting dearly.

Also, is this customer using SSH or HTTPS for cloning?

**Comment by ijsnow** [comment]
This is actually intended behavior. Sourcegraph should attempt to clone enabled repositories enabled it has access to based on the token that it was given.
