### ISSUE TITLE
Set proxy for code hosts

### ISSUE THREAD

**Issue by Ryanznoco** [sourcegraph/sourcegraph#22669]
#### Feature request description

I need set a proxy for code host, but I can't find any documents about it.

#### Describe alternatives you've considered.

I've tried add `http_proxy` to the environment, but it doesn't work.

**Comment by camdencheek** [comment]
Thanks for the request! Looks like a team member just opened a feature request for this same thing, so I'm closing this in favor of https://github.com/sourcegraph/sourcegraph/issues/22730 -- feel free to add any additional info or follow that issue.
