### ISSUE TITLE
Search sidebar scrolls a bit when not necessary

### ISSUE THREAD

**Issue by pdubroy** [sourcegraph/sourcegraph#22671]
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:** Version 91.0.4472.114 (Official Build) (x86_64) on macOS

#### Steps to reproduce:

1. Go to https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+foobar&patternType=literal
2. Make the window tall enough to show the full contents of the search sidebar on the left:
    ![CleanShot 2021-07-08 at 12 06 09](https://user-images.githubusercontent.com/17293/124904170-020f6400-dfe5-11eb-86ae-87f3450cc984.png)
3. Scoll the search results.

#### Expected behavior:

The sidebar remains static. I expect the sidebar to scroll with the content when it's not fully visible, but when the window is tall enough to show all the content, it should remain static.

#### Actual behavior:

The sidebar scrolls a few pixels before stopping.

https://user-images.githubusercontent.com/17293/124904337-308d3f00-dfe5-11eb-8dd2-c7d4b2bbefb4.mp4

**Comment by camdencheek** [comment]
Closing since this sidebar has since been redesigned twice.
