### ISSUE TITLE
using rev: filter without repo: filter should return error

### ISSUE THREAD

**Issue by stefanhengl** [sourcegraph/sourcegraph#22693]
I stumbled across this while I was refactoring the global search path.

https://sourcegraph.com/search?q=context:global+rev:b6dd338737c090fdab31d324542bfdaa7ce9f766+doResults&patternType=literal

This search, which ends up in the global search path, returns a lot of results. Instead it should return
an error asking the user to add a repo: filter.

**Comment by stefanhengl** [comment]
@rvantonder should make the parser check this during validation?

**Comment by rvantonder** [comment]
huh, the interesting part is that the backend "does something" and returns results even when there isn't a `repo:` filter. Sure, this should be easy to guard. Curious what how the backend ends up computing these results though, that's not the parsers fault--likely repo value is empty and then this happens for some reason.

**Comment by rvantonder** [comment]
To wit 😏 

![Screen Shot 2021-07-08 at 5 39 18 PM](https://user-images.githubusercontent.com/888624/125006639-73660b80-e013-11eb-9033-e8acf757f31c.png)

**Comment by rvantonder** [comment]
So validation is technically not strong enough for `repo` either. I'm going to punt on that one for now, it's tricker to validate and you have to know our conventions really well to surface that.

**Comment by stefanhengl** [comment]
The backend qualifies it as global search, because there is no repo: filter, and then ignores the rev: filter completely.
