### ISSUE TITLE
Docs: Add coverage for all deployments to some of our docs

### ISSUE THREAD

**Issue by dan-mckean** [sourcegraph/sourcegraph#22720]
The following docs lack explanations for one or more of our deployment types:
- https://docs.sourcegraph.com/admin/config/site_config#editing-your-site-configuration-if-you-cannot-access-the-web-ui - missing Docker-Compose
- https://docs.sourcegraph.com/admin/repo/pre_load_from_local_disk - missing Docker-Compose and Kubernetes

**Comment by bobheadxi** [comment]
I think this was covered by https://github.com/sourcegraph/sourcegraph/issues/23145 - both those links have mentions of Docker Compose now :)
