### ISSUE TITLE
Allow setting proxy parameters for HTTP and git requests to code hosts

### ISSUE THREAD

**Issue by emchap** [sourcegraph/sourcegraph#22730]
#### Feature request description

The ability to set proxy parameters for HTTP and git requests to code hosts, and documentation on how to do that.

#### Is your feature request related to a problem? If so, please describe.

SG employees see https://sourcegraph.slack.com/archives/C0W2E592M/p1625683121455400. Discussed this with Joe, who asked me to raise an issue.

#### Describe alternatives you've considered.

N/A

#### Additional context

Discussed with @unknwon, he asked me to make an issue.

**Comment by camdencheek** [comment]
May be related to #22607
