### ISSUE TITLE
Error: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by sfllaw** [sourcegraph/sourcegraph#22740]
- **Sourcegraph version:** 3.29.0
- **Platform information:** N/A

#### Steps to reproduce:

We don't know exactly how to reproduce the problem. A small subset of our users encounter this when they:
1. Go to https://sourcegraph.example.com
2. Get redirected to https://sourcegraph.example.com/search
2. Get unlucky.

#### Expected behavior:
The user should see the home page with a search box.

#### Actual behavior:
The user sees the following React error:
```
Cannot read property '0' of undefined
```

Here is a screenshot:
![image-2021-07-09-08-26-21-161](https://user-images.githubusercontent.com/155692/125138241-2477af00-e0c3-11eb-8bc7-bf3c5c14cca8.png)

And here is the stack trace from the Developer Console on Chrome:
```
TypeError: Cannot read property '0' of undefined
    at scanner.ts:72
    at T (scanner.ts:494)
    at SyntaxHighlightedSearchQuery.tsx:8
    at Object.useMemo (react-dom.production.min.js:165)
    at t.useMemo (react.production.min.js:25)
    at a (SyntaxHighlightedSearchQuery.tsx:7)
    at Qo (react-dom.production.min.js:153)
    at ws (react-dom.production.min.js:261)
    at bc (react-dom.production.min.js:246)
    at hc (react-dom.production.min.js:246)
rs @ react-dom.production.min.js:209
n.payload @ react-dom.production.min.js:227
ho @ react-dom.production.min.js:129
Ua @ react-dom.production.min.js:179
ws @ react-dom.production.min.js:263
bc @ react-dom.production.min.js:246
hc @ react-dom.production.min.js:246
ac @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
$i @ react-dom.production.min.js:122
Ji @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
_c @ react-dom.production.min.js:257
t.unstable_runWithPriority @ scheduler.production.min.js:19
$i @ react-dom.production.min.js:122
Ec @ react-dom.production.min.js:257
R @ react-dom.production.min.js:287
Jt @ react-dom.production.min.js:68
selectionchange (async)
setSelectionRange @ textAreaInput.js:599
writeToTextArea @ textAreaState.js:32
_setAndWriteTextAreaState @ textAreaInput.js:433
writeScreenReaderContent @ textAreaInput.js:441
_setHasFocus @ textAreaInput.js:420
focusTextArea @ textAreaInput.js:387
focusTextArea @ textAreaHandler.js:383
focus @ viewImpl.js:355
focus @ codeEditorWidget.js:897
(anonymous) @ MonacoQueryInput.tsx:284
ss @ react-dom.production.min.js:211
_c @ react-dom.production.min.js:257
t.unstable_runWithPriority @ scheduler.production.min.js:19
$i @ react-dom.production.min.js:122
Ec @ react-dom.production.min.js:257
(anonymous) @ react-dom.production.min.js:256
F @ scheduler.production.min.js:17
_.port1.onmessage @ scheduler.production.min.js:14
```

#### Workaround
Users can workaround this problem by providing a non-empty query, _e.g._ https://sourcegraph.example.com/search?q=foo. We think this is a bug in the syntax highlighter for the input field.

**Comment by camdencheek** [comment]
Thanks for the report! It looks like we're creating a `SyntaxHighlightedSearchQuery` with an undefined `query` somewhere. I took a quick peek, and it seems the most likely place this could happen is in the [recent searches panel](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@0dd845823a85873954d3bd2e5dbe8d791a9a5b9b/-/blob/client/web/src/search/panels/RecentSearchesPanel.tsx#L154). 

cc @rvantonder because I think you are more familiar with recent searches?

**Comment by rvantonder** [comment]
Didn't get a chance to look at this today. Maybe I'll have a chance in the next day or two. CC @limitedmage for visibility, but not sure what the root cause is yet, may very well be a query scanning issue. Would make sense to reproduce with an empty account I'm guessing.

**Comment by sfllaw** [comment]
Looking at the database, it looks like old versions didn't populate `node.argument` which might cause [`processRecentSearches`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@0dd845823a85873954d3bd2e5dbe8d791a9a5b9b/-/blob/client/web/src/search/panels/RecentSearchesPanel.tsx?L192-193) to fail in this way?

```
sourcegraph=# SELECT id, name, url, argument FROM event_logs WHERE name = 'SearchResultsQueried' AND argument = '{}' LIMIT 1;
-[ RECORD 1 ]---------------------------------------------------------------------------------------
id       | 295165
name     | SearchResultsQueried
url      | https://sourcegraph.quantcast.com/search?q=test&patternType=regexp
argument | {}
```

**Comment by rvantonder** [comment]
@sfllaw thanks--we'll look into this ASAP. When we do find a fix, it'll likely be in our next release (roughly one week away).

In the mean time, I want to mention that its possible to disable the components that are likely causing this, via

```
experimentalFeatures: {      
   "showEnterpriseHomePanels": false,
}
```

in User Settings for individual users, or in settings elsewhere for orgs/globally.

**Comment by sfllaw** [comment]
:tada:
