### ISSUE TITLE
Run on clouds other than Google Cloud and Digital Ocean

### ISSUE THREAD

**Issue by ijt** [sourcegraph/sourcegraph#2274]
Some users may have reasons to run Sourcegraph on clouds other than Google Cloud or Digital Ocean. For example, there are startups that have credits on AWS (https://aws.amazon.com/startups/) and may want to use them to run Sourcegraph on their code.

One possible way to gain this portability would be to take advantage of the new Go CDK: https://gocloud.dev. Some areas where it could help are its API for portable pubsub (runs on AWS, Azure, GCP, plus has RabbitMQ support), and its packages for connecting to managed Postgres databases.

**Comment by nicksnyder** [comment]
Sourcegraph works on any cloud provider (we bundle our own database by default for example, but customers can also configure Sourcegraph to point to an external database), including running on your local machine :)

What gave you the impression that we only support those two hosts?

@ggilmore is specifically working on better AWS documentation right now.

**Comment by ijt** [comment]
Wow. I don't know how I missed that. Shot from the hip. Closing this out.
