### ISSUE TITLE
Add BE version of insight to the creation UI of search based insight

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#22759]
Since we have some version of BE insight that still works via user settings we can adopt search-based insight creation UI for it.

We have to 

- Add some UI (probably checkbox) about turning on `over all repos` mode (BE insight)
- Change the setting update handler in the creation UI page. 
- Adopt the edit page setting handler.

**Comment by felixfbecker** [comment]
Closing as it appears this was implemented, probably as part of https://github.com/sourcegraph/sourcegraph/pull/22868 (screenshot from k8s):

![image](https://user-images.githubusercontent.com/10532611/125996347-2c6aa39b-302d-4ae2-ab3f-e1af856368ad.png)
