### ISSUE TITLE
Invalid tooltip appears if moving vertically through whitespace in JavaScript

### ISSUE THREAD

**Issue by wukkuan** [sourcegraph/sourcegraph#2275]
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:** macOS High Sierra, Sourcegraph.com, Firefox 65.0 and Chrome 72.0.3626.96

#### Steps to reproduce:

1. Go to https://github.com/wukkuan/url-shortener/blob/master/lib/shortened-urls.js#L24 with the Sourcegraph extension installed
or
https://sourcegraph.com/github.com/wukkuan/url-shortener@master/-/blob/lib/shortened-urls.js#L24 directly
2. Place mouse cursor on line 26, directly below `shortUrlKeyLength`
3. Move cursor straight up, slowly, to hover over `shortUrlKeyLength`.
4. Hover and wait for the Sourcegraph tooltip to appear.
5. Click "Go to definition"

#### Expected behavior:
In step 4: `shortUrlKeyLength` is highlighted orange. A preview of the definition of `shortUrlKeyLength` is displayed.
In step 5: The `shortUrlKeyLength` definition (function parameter) is highlighted.

#### Actual behavior:
This is intermittent, but ~75% of the time this happens:
In step 4: Nothing is highlighted. No preview appears.
In step 5: A spinner appears on the Go to Definition button, but never goes away.

If I approach horizontally from the right/left, it works normally.

#### Screencast:
Invalid behavior:
![screencast 2019-02-12 20-11-39](https://user-images.githubusercontent.com/4724/52679289-a53a1d00-2f02-11e9-939b-5583ab13800e.gif)

Valid and then invalid behavior:
![screencast 2019-02-12 20-16-17](https://user-images.githubusercontent.com/4724/52679477-36a98f00-2f03-11e9-8db1-288a1c378dfe.gif)

**Comment by sqs** [comment]
Thank you for the detailed bug report.

**Comment by felixfbecker** [comment]
Hi @wukkuan, I am unable to reproduce this:

![2019-04-03 13 29 33](https://user-images.githubusercontent.com/10532611/55475598-aa6b3c80-5614-11e9-9e0a-2f87cd2327f9.gif)

![2019-04-03 13 30 15](https://user-images.githubusercontent.com/10532611/55475602-accd9680-5614-11e9-8aeb-1ec777239ad2.gif)

Am I doing anything different?

**Comment by wukkuan** [comment]
Strange... It's not doing it anymore for me either. It persisted across reboots and across different browsers before... So I don't think I was imagining. :) Thanks for looking into it!
