### ISSUE TITLE
search regression: global queries return fewer results than expected

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#22777]
Introduced by https://github.com/sourcegraph/sourcegraph/pull/22689, bisected by @coury-clark. I tried to revert but we have conflicts on top so am filing a report for @sourcegraph/search-core to triage instead.

Reproducing:

![Screen Shot 2021-07-12 at 6 05 48 PM](https://user-images.githubusercontent.com/888624/125374408-ce617080-e33b-11eb-8376-2f46bde2c52c.png)

**Comment by stefanhengl** [comment]
Looking into it, thanks for bisecting already!
