### ISSUE TITLE
Show function dependency graph

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#2278]
From a user (@ritazh):
>  I wish there was an easy way to show the dependency graph for a large codebase, specifically at the function level

@ritazh features similar to this have been requested before. A few clarifying questions:
* What's the specific use case? Is it for diving into the details (in which case I'd imagine wanting to jump back and forth between file view and graph view) or more for high-level structure?
* How much of the graph would you like to see at once? Just the edges/nodes X hops out from a single symbol? Or the entire codebase (which is more comprehensive but also noisier)
* Do you want to see just edges within a repository or also edges between repositories (function calls to external dependencies)? Which is more common / useful?

**Comment by sqs** [comment]
I split this into 3 separate feature requests, because there is a lot of product development we can do here:

- Call hierarchy #2881 
- Call graph #2882 
- Function dependency graph #2883

**Comment by aisbaa** [comment]
Awesome, thank you!
