### ISSUE TITLE
Create content for notebook/playground

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#22790]
Users are missing use cases to evaluate the capabilities of Sourcegraph search. Provide these use cases in a notebook format where each segment of the query is commented and easily digestable. 

Sample content ideas:
* Searching diff and commits + all head branches
* Various methods of searching repositories
  * An org's repositories
  * Content within a repository

**Comment by lguychard** [comment]
@rrhyne closing as the initial version of this is now live. Let's track future progress in follow-up issues.
