### ISSUE TITLE
Bug Report: disable access to certain code host requires users to reinstall browser extension

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#22798]
- **Sourcegraph version:** 3.29.0
- **Platform information:** Any

#### Steps to reproduce:

1. Add repo from Phabricator to Sourcegraph
2. Remove repo from Phabricator to Sourcegraph and add the same repo from GitHub
3. The `View on Phabricator` icon remains even though the repo has been removed. This should be replaced by `View on GitHub` instead.
![image](https://user-images.githubusercontent.com/68532117/125499933-d2891316-cc84-4718-8fa0-06cdeacbb669.png)
4. A user reported that reinstalling the extension and disable access to Phabricator would stop the `View on GitHub` button from changing to `View on Phabricator` . 

#### Expected behavior:
1. `View on Phabricator` should be removed and replaced by `View on GitHub` if Phabricator is no longer listed as the code host.
2. Users should be able to disable access to Phabricator on the Sourcegraph extension setting page, under Site access.

#### Actual behavior:
1. Users can only see `View on Phabricator` even though Phabricator is no longer listed in the code host config.
2. Users need to reinstall the extension to restore the access permissions because they cannot disable access to a specific site from the extension setting page.
![image](https://user-images.githubusercontent.com/68532117/125500869-58d398cf-421e-4d9f-ba13-1ee2b1039658.png)

**Comment by tjkandala** [comment]
Hey @abeatrix, I believe you should be able to select individual site permissions if you disable "Automatically allow access on the following sites." Does that work for you?
