### ISSUE TITLE
Instance for IOActive PenTest

### ISSUE THREAD

**Issue by bcreager** [sourcegraph/sourcegraph#22796]
IOActive will start conducting a pen test this week. They will use dogfood for some of that activity, but we also wanted to give them a sandbox for more destructive testing

**Comment by bobheadxi** [comment]
Slack discussion: https://sourcegraph.slack.com/archives/C01DQNSHXCM/p1626194598034100

**Comment by ggilmore** [comment]
see https://sourcegraph.slack.com/archives/C01DQNSHXCM/p1626465566018400?thread_ts=1626375672.007100&cid=C01DQNSHXCM
