### ISSUE TITLE
Docs: open source documentation

### ISSUE THREAD

**Issue by marshall007** [sourcegraph/sourcegraph#228]
#### Feature request description

Now that the core is open source, it probably makes sense to open source the [documentation](https://about.sourcegraph.com/docs/) as well. I wasn't able to find it anywhere in order to submit a fix.

It also might make more sense to move the [browser extension](https://about.sourcegraph.com/docs/features/browser-extension/) documentation to [`sourcegraph/browser-extensions`](https://github.com/sourcegraph/browser-extensions), so that it can be maintained alongside changes to source code.

#### Additional context

It appears that GitLab support was recently added in [`sourcegraph/browser-extensions#197`](https://github.com/sourcegraph/browser-extensions/pull/197/files), but the [documentation](https://about.sourcegraph.com/docs/features/browser-extension/configuration#supported-code-hosts) has not been updated to reflect that yet. GitLab/Enterprise <-> GitHub/Enterprise would be our primary use case, so it's good to note support is there.

**Comment by sqs** [comment]
Thank you for reporting this. @attfarhan is currently doing this and it will be live soon. 

As for the GitLab support, that will be announced shortly in our upcoming 2.12 release (this week) and we will then update the docs. We tweeted about it but only because it may have caused some people to have their extension disabled.

**Comment by sqs** [comment]
A PR to publish our docs and website sources is open at https://github.com/sourcegraph/about/pull/1.

**Comment by attfarhan** [comment]
Hey @marshall007, thanks for opening this. We've merged the PR to open source our docs, blog, website, and product roadmap in https://github.com/sourcegraph/about. Contributions are welcome and appreciated!
