### ISSUE TITLE
Updates based on hallway testing

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#22801]
## Interaction related:
- [x] Improve the left caret to include an 'i' character to further denote additional information is contained in the reference. [Figma](https://www.figma.com/file/as1QusTZKQlUakfC90ANwb/Search-reference-panel?node-id=437%3A7612)
- [x] Animate the i < button into screen from right (our animation from when the caret was on the left will be appropriate)  
- [ ] link @rev in repo: filter replaces search. Open this in a new tab or remove the link
- [x] Make examples clickable and additive to the user's search

## Content related
- [x] before: fitler is missing
- [x] after and before descriptions should include a statement "To use this filter, the search query must contain type:diff or type:commit."
- [x] In the after examples description, and likely elsewhere, filters are missing quotes. The filter `after:last week` is then presented to users incorrectly. Add quotes: `after:"last week"` so the filter is presented correctly 
  * This should be made on the documentation page as well
 - [x] file.contains() is missing from the list of items
 - [x] Negation entry is missing the phrase (opt + click filter in reference list) ([figma](https://www.figma.com/file/as1QusTZKQlUakfC90ANwb/Search-reference-panel?node-id=210%3A1376))
 - [x] visibility filter does not contain the additional items private and public as forks and archived do. It should display as `visibility:any/private/public`
 - [x] repo:contains.file/content/commit should be split into:
   * repo:contains.file(path)
   * repo:contains.content(content)
   * repo:contains.commit.after(date)
   * Descriptions are available for these items in the documentation
- [x] Author is missing. Description should contain: "To use this filter, the search query must contain type:diff or type:commit."
- [x] Message is missing. Description should contain: "To use this filter, the search query must contain type:diff or type:commit."
 

# metrics related
Metrics defined here: https://www.figma.com/file/as1QusTZKQlUakfC90ANwb/?node-id=199%3A645

- [x] SearchReferenceSearchedAndClicked
- [x] SearchReferenceFilterClicked
- [x] SearchReferenceClosed
- [x] SearchReferenceOpened

**Comment by fkling** [comment]
>  link @Rev in repo: filter replaces search. Open this in a new tab or remove the link

Looks like I cannot make those links be opened in another tab. That would mean removing all links descriptions, including useful ones like

> The value of the parameter is a string that can be parsed by the [Go time package’s `ParseDuration`](https://golang.org/pkg/time/#ParseDuration)

Are not links better than the current behavior? Or can we expect that people will CTRL click a link to open it in a new tab?

**Comment by rrhyne** [comment]
If we cannot open in a new tab, let's leave it as is. I think it was a bit shocking to the user, but I think you are correct, the information is valuable to have and the user will learn to control click.
