### ISSUE TITLE
Bug Report: Extension does not function against privately scoped repos on some code host 

### ISSUE THREAD

**Issue by hicksca** [sourcegraph/sourcegraph#22803]
- **Sourcegraph version: 3.29.0** 
- **Platform information: Any** 

#### Steps to reproduce:
(Tested against Github.com and Bitbucket Server)

1. Create a private repository
2. Synced with Sourcegraph  
3. Verified that extension was authenticated with Sourcegraph instance

#### Expected behavior:
Once synced with Sourcegraph from the code host (bitbucket server). I should be able to reload the page for the repo and have the extension add a sourcegraph button in the UI and have code intel hover capabilities:
![image](https://user-images.githubusercontent.com/3722310/125520541-8ee66c2c-1ef4-4a52-8b21-f2c71229b5f9.png)

#### Actual behavior:
I reload the page once I have verified that the repo has been cloned indexed to Sourcegraph instance and I do not get the Sourcegraph UI or hover capabilities for my repository.
![image](https://user-images.githubusercontent.com/3722310/125521822-21a4d854-736d-4d9b-bd7e-06d6ec725896.png)

**Comment by muratsu** [comment]
Hey @hicksca, we've recently updated our browser extensions. Can you try the latest version and let us know if you're still able to repro this issue?

**Comment by hicksca** [comment]
Verified that in testing that I am now getting the expected UI changes (SG button added for private repos) on Bitbucket server (an internal test instance).
