### ISSUE TITLE
Use `production` build for frontend integration tests

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#22831]
## Problem statement

Currently, we use a development build to run our integration tests. It's beneficial for performance, but the way the application is loaded is different from what we have in the production environment: CSS is not extracted in a separate file, and many third-party library production optimizations are not applied. 

Without code minimization, the build time won't change significantly, but we will be able to test our UI in an environment consistent with our production deployments.

## Success criteria

It's possible to run integration tests on top of the production build of the web application.

## Implementation details

1. The place where we create the integration tests context and mock the index.html file:
 
 
 
 https://github.com/sourcegraph/sourcegraph/blob/573a8bb047b1ff09812823a13cbe6f08a73b062f/client/web/src/integration/context.ts#L66

2. [Integration tests documentation](https://docs.sourcegraph.com/dev/how-to/testing#browser-based-tests)
3. Let's use the `NODE_ENV` env variables to determine the type of build we want to use to run the integration tests

## Time estimate

- Pull requests with ~450 lines changed should take **8 hours** at maximum. Ping the reviewer in the spec pull request if time-consuming changes are required.
- Let's discuss the solution ideas early in the spec PR.

**Comment by felixfbecker** [comment]
One big thing to consider is debuggability: E.g. when an error happens, can we get a stack trace that doesn't just point to a position in a minified bundle. Ideally, we can respect source maps. But there can be some errors and warnings e.g. by React that are not emitted in production mode, and potentially certain debug information (e.g. component names?).

The other aspect is CI build time, I think production builds took a lot longer to build. Maybe that has changed.

**Comment by valerybugakov** [comment]
Because we recently bumped multiple times into issues with the unstable CSS order, we need to look into this issue to catch CSS bugs during our CI builds.
