### ISSUE TITLE
Python go-to-def performance regression

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#2288]
From a user: https://twitter.com/regexmachina/status/1095646961758220288

Link: https://sourcegraph.com/github.com/clhchtcjj/BiNE@c9cb51b43ce0201aebf32fea44980b1f4ae8ebcb/-/blob/model/train.py#L283:5

cc @chrismwendt @lguychard @ijsnow @sqs 

Workaround for now: Use the basic code intelligence for faster code intel https://sourcegraph.com/extensions/sourcegraph/basic-code-intel. It's accurate enough and much faster for many use cases.

**Comment by chrismwendt** [comment]
Changed the title to Python (I think that's the language the user was reporting). Added a link to the repository to the description.

After refreshing the page a few times, I've seen it take anywhere from 5 to 20+ seconds to show the definition. This is a 16 MB repository archive that decompresses to 41 MB (most of which is a single `.dat` file), so I doubt size is the issue.

**Comment by sqs** [comment]
@chrismwendt 	For now, I think just making Sourcegraph.com drop down to basic code intel for Python is the best fix. Therefore adding this to 3.1.

**Comment by chrismwendt** [comment]
Sounds good, I updated global settings on Sourcegraph.com.

**Comment by aidaeology** [comment]
Closing this issue since its now obsolete.
