### ISSUE TITLE
managed: upgrade to terraform v1

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#22905]
The recently released [Terraform v1 has some nice compatibility promises](https://www.terraform.io/docs/language/v1-compatibility-promises.html). We should upgrade managed instances tooling to use it:

- [ ] update [`template`](https://github.com/sourcegraph/deploy-sourcegraph-managed/tree/main/template)
- [ ] update [`devmanaged`](https://github.com/sourcegraph/deploy-sourcegraph-managed/tree/main/dev)
- [ ] update `demo`
- [ ] update all customer instances

[Upgrade guide](https://www.terraform.io/upgrade-guides/1-0.html)

**Comment by daxmc99** [comment]
Thanks! This has high importance as we leverage managed instances more
