### ISSUE TITLE
Don't show a ghost "insight" chart that loads and then disappears

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#22958]
We shouldn't show you a ghost chart that seems to appear and load. I imagine this has something to do with our empty state or something? 

It otherwise made me think one of my insights was loading and then getting bumped/deleted/reordered – it wasn't clear that it was a "fake" chart to me until I tried it on a single-insight dashboard. 

Loom: https://www.loom.com/share/b8ad18893872417d94f7800e37a99f76

**Comment by felixfbecker** [comment]
To clarify, the "ghost" insight is the "Backend insight" that shows up loading, then disappears.

![image](https://user-images.githubusercontent.com/10532611/126154074-edec4617-3f84-4d80-b229-12d2efc44cf7.png)

![image](https://user-images.githubusercontent.com/10532611/126154131-6614fe08-0e24-487c-adf1-26107449eedd.png)
