### ISSUE TITLE
Redirect /insights to dashboards page?

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#22959]
Although I think this was just a caching issue, a couple times I seemed to end up on /insights (which displays no dashboard behavior) rather than /insights/dashboards/all. 

I'm wondering if there's any reason to leave /insights a separate page right now? I don't feel like we need to remove it fully for speed of fix/technical reasons, but should we just **redirect** it to /insighs/dashboards/all?

**Comment by vovakulikov** [comment]
@Joelkw thanks for noticing this. At the moment we still use this page in our integration tests to make screenshots of our charts in different browsers. That page will be removed when we implement proper integration tests over dashboard features. 

For now, I'll check any route redirects and transitions to be sure that we don't have old /insights page routes in our new dashboard flow.

**Comment by felixfbecker** [comment]
Is there any reason the integration tests wouldn't work on the `/insighs/dashboards/all` (without changing the test body)? Does the test still add value if users are no longer expected to go to this page?
I feel like "we have a test for it" should not be the reason to not remove/redirect a page because then we could never remove/redirect any page ever assuming good test coverage 😄

**Comment by vovakulikov** [comment]
@felixfbecker There are no reasons or tech limitations except that we didn't have time for it. I think it should be a quick fix but I would prefer to do that after release cause we still have a package with small tickets/problems that we want to fix before the 3.30 release cut. But I totally with you about the insights page and test coverage 😄

**Comment by vovakulikov** [comment]
@Joelkw I checked dashboard routes and it seems already without /insights page redirections. Can you please check this again or maybe you remember what kind of page it was with bad navigation

**Comment by Joelkw** [comment]
@vovakulikov I think it may just a pre-loaded tab that hadn't updated yet. But I'm concerned/assuming a lot of folks may be use to hitting /insights to get to the insights page, either via typing it in manually or the browser's omnibar history that takes them there after they start typing "insights". I also don't know if anyone may have bookmarked the old url. So it might be worth a redirect anyway? But I understand the time and integration test tradeoff, so it's okay if we can't get this in until the next release.
