### ISSUE TITLE
Redirect user back to the original page when they sign in

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#22977]
From @JoshuaKGoldberg:

> User login flow: I ran a basic search anonymously, clicked Log In, logged in with Github, and was redirected to the Sourcegraph homepage. The query was lost. The Github integration did have to ask for new permissions on my account. Maybe that's relevant?

I've also experienced this myself. We should redirect the user back to the page they were on (with security guidelines in place to forbid open redirects, etc.) when they sign in.

**Comment by limitedmage** [comment]
We have the `returnTo` param so I think this should be trivial to implement.

**Comment by 5h1rU** [comment]
I think this would be owned by @sourcegraph/core-application.
