### ISSUE TITLE
Basic code intel: ideas for improvements

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#2298]
## Jump-to-definition can't disambiguate between symbols with the same name

Say you have 2 files that both define:

```
// a.go
type Foo int
// b.go
type Foo int
```

Jump-to-definition on a reference to `Foo` would show 2 results.

**Ideas for improvements**

- Filter by imported packages
- Use scope information from ctags and some rudimentary type inference (or even just look at the token to the left of the `.`, such as `cli` in `cli.Main`) to determine the enclosing class

See https://github.com/sourcegraph/sourcegraph/issues/3234

## Find-references is inaccurate

**User report**

> The most important thing IMHO is "Find references" should consider scopes of the objects, i.e. when using it on a local variable or a member, it shouldn't give results for all variables with the same name. Or at least order the results based on some heuristic, e.g. file path distance.

> It includes references that appear in comments, but shouldn't. `@KattMingMing`

**Ideas for improvements**

- [x] Boosting results by file path distance (from the user above). Done in https://github.com/sourcegraph/sourcegraph-basic-code-intel/commit/27d3b8906d564d0c2559685245b244fe5678914a
- Filter out results from packages that do not import the package where the symbol is defined
- Filter out references if they appear in comments or strings

More discussion https://github.com/sourcegraph/sourcegraph/issues/3418

**Elaborating on filtering by imports**

We could do more computation in basic-code-intel in the browser. Here's a sketch:

- User clicks "Find references" on token `Foo`
- Internally, basic code intel does a j2d on `Foo` and discovers it is defined in `pkg1/Foo.java`
- Internally, basic code intel does a text search for `Foo` and finds lots of results
- For each search result, do another j2d and check if that is the same as the original

The main problem is "lots of results", which could be in the tens or hundreds. We could limit it to the top N, or prompt users to click a button to make basic code intel try harder.

We could do more indexing up front. Here's a sketch:

- Sourcegraph analyzes all of the files in all repositories and stores metadata about each identifier (name + definition location)
- User clicks "Find references" ... (same as above)
- Instead of doing a text search, it does a symbol search for references to that definition location

The main problem is compute and storage resources for all of these references.

## Doesn't work well for dependencies

**User report**

> Tooltips and jump-to-definition (and even basic type inference) don't seem to work for any symbols that are imported from other libraries (even Prelude).

**Ideas for improvements**

- Use `import` statements, `package.json`s, and the respective package registry to find relevant repositories to search in for dependency symbols

## Jump-to-definition and find-references don't work on local variables

Currently, basic-code-intel cannot provide jump-to-definition for anything but top-level variables/functions, and there are lots of false-positives because it's not scope-aware.

**Proposal: use tree-sitter**

Use [tree-sitter](http://tree-sitter.github.io/tree-sitter/) to build a syntax tree with scope information for a given file in order to reduce false positives for references provide jump-to-definition within the given scope.

## Domain-specific code intelligence

- Database table creation <-> column referenced in SELECT/INSERT/etc.
- HTTP router/handler <-> GET/POST requests to that endpoint

## Custom hover docs

> What I was asking for is structured documentation like [this one](https://sourcegraph.com/github.com/jneen/rouge@v3.3.0/-/blob/lib/rouge/regex_lexer.rb#L32:11) (note the special syntax `@see`). It should be rendered like [this](https://www.rubydoc.info/gems/rouge/3.3.0/Rouge/RegexLexer/State) (note the subsection “See Also” under section “Overview”).

From https://github.com/sourcegraph/sourcegraph/issues/4#issuecomment-471056540

Currently, Sourcegraph `RegexLexer.state` is not a link:

![image](https://user-images.githubusercontent.com/1387653/54057731-9b75a380-41a8-11e9-9d28-8e72b769d978.png)

**Comment by chrismwendt** [comment]
Basic code intel now ranks references by file path similarity https://github.com/sourcegraph/sourcegraph-basic-code-intel/commit/27d3b8906d564d0c2559685245b244fe5678914a

![image](https://user-images.githubusercontent.com/1387653/53193215-586eda00-35c5-11e9-8e1f-466d00cf16c7.png)

![image](https://user-images.githubusercontent.com/1387653/53193224-5c9af780-35c5-11e9-8951-f75735fd0438.png)

**Comment by FranklinYu** [comment]
For section “Custom hover docs”, actually `@see` isn’t the only tag I was looking for. A full list is available [here](https://www.rubydoc.info/gems/yard/file/docs/Tags.md); if full support is too complicated, I would expect at least:

* `@param`
* `@return`
* `@raise`

As they are very often useful as tooltip.

**Comment by aidaeology** [comment]
Closing this issue as it stands it is not actionable for us, team will discuss outstanding ideas and if still applicable we will create new separate scoped issues to track development.
