### ISSUE TITLE
Our public derivative Docker images should be OSS

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#2299]
Lots of these should be open-source, but are currently locked behind our private infrastructure repo (not intentionally):

- `sourcegraph/postgres`
- `sourcegraph/postgres-11.1`
- `sourcegraph/redis-cache`
- `sourcegraph/redis-store`
- `sourcegraph/redis_exporter`
- `sourcegraph/zoekt-indexserver`
- `sourcegraph/zoekt-webserver`
- `sourcegraph/pgsql-exporter`
- `sourcegraph/pod-tmp-gc`

And perhaps many more. Of course, we should do some cleanup at the same time:

- `pgsql-exporter` vs `redis_exporter` vs `redis-cache` naming inconsistency.
- why is `postgres-11.1` a different name and not just a tag?

**Comment by valsor** [comment]
Could you please make those images open-source. Especially postgres and redis. Thank you

**Comment by bobheadxi** [comment]
I belive pretty much all of the above (and more) are available now in https://github.com/sourcegraph/sourcegraph/tree/main/docker-images - others are included in https://github.com/sourcegraph/sourcegraph/tree/main/cmd
