### ISSUE TITLE
Support images

### ISSUE THREAD

**Issue by ammar1x** [sourcegraph/sourcegraph#23]
If I open an image it opens as a binary file. It would be nice if I could see an actual image instead.

**Comment by francisschmaltz** [comment]
@sqs Where did we land with https://github.com/sourcegraph/enterprise/issues/10316#issuecomment-375221191 ?

**Comment by francisschmaltz** [comment]
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/23

**Comment by sqs** [comment]
@francisschmaltz: We are all set with respect to DMCA Safe Harbor, so there are no copyright concerns with serving raw files.
