### ISSUE TITLE
How can I transfer the User Interface into Japanese

### ISSUE THREAD

**Issue by KashingLiu** [sourcegraph/sourcegraph#23007]
#### Question description

I want to localize my Sourcegraph site, for example, I want to transfer the "Go to Defination" button or the button and context in the website into Japanese. How can I finish this? Can I find the source code and change words? or Can I use other extension?

**Comment by camdencheek** [comment]
Looks like this is related to #10847

**Comment by Joelkw** [comment]
@jeanduplessis tagging you as "general catchall PM" for frontend platform team – don't think extensibility would own this.

**Comment by umpox** [comment]
Thank you for raising this @KashingLiu 

We do not currently support localization, you would need to manually change the source code to achieve what you want.

This is definitely something we want to support and is on our long-term roadmap. We have an [issue to track this ](https://github.com/sourcegraph/sourcegraph/issues/10847), I'll close this issue in favor of that one!
