### ISSUE TITLE
Upgrade to Go 1.12: Management Console shouldn't show broken ASCII characters on non-https

### ISSUE THREAD

**Issue by StevenH1901** [sourcegraph/sourcegraph#2300]
- **Sourcegraph version:** 3.0.1
- **Platform information:**  Ubuntu 18.04, Digital Ocean, Firefox Developers Edition 66.0b6 (64-bit), Docker 18.09.2 

#### Steps to reproduce:

1. Visit http://<Your_IP>:2633

#### Expected behavior:
I would expect there to be an error message saying that the management console must be accessed via https.

#### Actual behavior:
Currently there are just some broken ASCII characters visible.
See image attached.
![mgmt console non https](https://user-images.githubusercontent.com/26209272/52820718-5ad7ae00-3072-11e9-89c9-39e737af24a6.png)

**Comment by slimsag** [comment]
I've looked into fixing this just now, I agree this is a common mistake which is bad. Chrome handles this better, but unfortunately Firefox does not.

Go 1.12, when released, [will contain this fix](https://github.com/golang/go/commit/fc4f2e5692ab800a450e07c3d983eda02dfd4711#diff-bf538ad0b0c9263061db13ca6d8f324e) which would then show:

> HTTP/1.0 400 Bad Request
> Client sent an HTTP request to an HTTPS server.

So I think the only thing to do here is wait and verify that works when Go 1.12 is released. It doesn't appear like we can do anything (easily) in the meantime.

**Comment by slimsag** [comment]
We've upgraded to Go 1.12 some ~13 days ago, so the next release of Sourcegraph this issue should automatically be resolved.
