### ISSUE TITLE
Apply CSS Modules codemod to areas where automatic migration is possible

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#23015]
## Problem statement

We're in the process of migration from global CSS to [CSS modules](https://docs.sourcegraph.com/dev/background-information/web/styling#css-modules). To automate part of the process, [the codemod](https://github.com/sourcegraph/codemod/tree/main/src/transforms/globalCssToCssModule) has been created that can do most of the changes required automatically. It was [partially applied](https://github.com/sourcegraph/sourcegraph/pulls?q=is%3Apr+codemod+css+modules+label%3Ateam%2Ffrontend-platform+label%3A%22CSS+Modules+migration%22) to the codebase. As part of this issue, we need to apply the codemod to the rest of the codebase where significant manual work (similar to https://github.com/sourcegraph/sourcegraph/issues/21368) is not required.

## Implementation details

1. Check out two pull requests to see the instructions on how to apply the codemod:
    - https://github.com/sourcegraph/sourcegraph/pull/25430
    - https://github.com/sourcegraph/sourcegraph/pull/25429 
2. Apply the codemod to small parts of the codebase to keep pull request diff around [450 lines](https://about.sourcegraph.com/handbook/engineering/developer-insights#prefer-small-prs-lines).
3. Mention this issue in the pull request to keep track of the work here: "Part of the https://github.com/sourcegraph/sourcegraph/issues/23015"
3. Skip components where significant refactoring is required to complete migration to CSS modules. Create a separate Github issue similar to https://github.com/sourcegraph/sourcegraph/issues/21368 to return to this task later. Add the following labels to these issues: `CSS Modules migration`, `dx`, `team/frontend-platform` to include them in [the tracking issue](https://github.com/sourcegraph/sourcegraph/issues/23010).

### Priorities

1. `web` package
2. `branded` package
3. `shared` package
4. `browser` package

## Success criteria

1. Small revertable pull requests are created with the help of the codemod to convert parts of the codebase to CSS modules.
2. This issue can be closed once the whole codebase is migrated to CSS modules, excluding components where significant refactoring is required.

**Comment by gitstart-sourcegraph** [comment]
Hello @valerybugakov 
After creating a number of codemod sub-issues, which are mostly completed at the moment, we are currently unable to find any more global `scss` files to be converted to `module.scss`. Assumption is that all needed conversions has been covered in created sub issues. kindly help confirm this.

**Comment by valerybugakov** [comment]
@gitstart-sourcegraph, could you check if we did we cover?
1. `client/browser/src/browser-extension/after-install-page/AfterInstallPageContent.scss`
2. `client/browser/src/browser-extension/options-menu/OptionsPage.scss`
3. `client/browser/src/shared/code-hosts/*/style.scss` — not used in React components, but still can be converted to CSS modules.
4. `client/web/src/SourcegraphWebApp.scss` — `app__error` and `app__error-text` classes. 

Let's address all items from the list above and double-check leftovers again after merging all the PRs. 
I used this type of search in the VSCode to find not transformed styles:

<img width="597" alt="Screenshot 2021-11-29 at 11 41 45" src="https://user-images.githubusercontent.com/3846380/143844212-4686cf4b-d5f4-4e81-8a3e-a8457b59146e.png">

**Comment by gitstart-sourcegraph** [comment]
Hi @valerybugakov here are a list of all remaining `.scss` files on project could you help give a tip on how to proceed on some of the listed files

- [ ]  HoverOverlay.scss `client/browser/src/shared/code-hosts/shared/HoverOverlay.scss`

⇒ Has no corresponding `.tsx` file

- [ ]  ActionsNavItems.scss `client/shared/src/actions/ActionsNavItems.scss`

⇒ Already converted to scss: might need to delete `scss` file

- [ ]  SourcegraphWebApp.scss `client/web/src/SourcegraphWebApp.scss`

⇒ Already converted to `.module.scss` might need to delete `.scss`  file

- [ ]  ApiConsole. `client/web/src/api/ApiConsole.scss` 

⇒ Already converted to `.module.scss` might need to delete `.scss` file

- [ ]  cm-sourcegraph-theme.scss `client/web/src/api/cm-sourcegraph-theme.scss`

⇒ not sure how to proceed on theme file

- [ ]  graphql-theme.scss `client/web/src/api/graphiql-theme.scss` 

⇒ not sure how to proceed on theme file

- [ ]  Dialog.scss `client/web/src/components/Dialog.scss` 

⇒ Contains no corresponding `.scss` file

- [ ]  DocumentationIcon.scss `client/web/src/repo/docs/DocumentationIcon.scss` 

⇒ Can be converted to `.module.scss`

- [ ]  RepositoryReleasesArea.scss `client/web/src/repo/releases/RepositoryReleasesArea.scss`

⇒ Can be converted to `.module.scss`

- [ ]  RepositoryStatsPage.scss `client/web/src/repo/stats/RepositoryStatsPage.scss` 

⇒ Does not contain corresponding `.tsx`  file

- [ ]  ShephrdTour.scss `client/web/src/search/ShepherdTour.scss` 

⇒ Does not contain corresponding `.tsx` file

- [ ]  homepage.scss `client/web/src/search/home/homepage.scss` 

⇒ Does not contain corresponding `.tsx` file

**Comment by valerybugakov** [comment]
@gitstart-sourcegraph

1. `client/shared/src/actions/ActionsNavItems.scss` — let's move these styles to `client/shared/src/actions/ActionsNavItems.module.scss` into `.action-item`.
2. `client/web/src/SourcegraphWebApp.scss` — no changes required.
3. `client/web/src/api/ApiConsole.scss` — no changes required.
4. `client/web/src/components/Dialog.scss` — no changes required.
5. `client/web/src/repo/docs/DocumentationIcon.scss` — let's convert it to CSS module.
6. `client/web/src/repo/releases/RepositoryReleasesArea.scss` — let's delete it. It seems that it's not used anywhere.
7. `client/web/src/repo/stats/RepositoryStatsPage.scss` — classes from here are used in `client/web/src/repo/stats/RepositoryStatsContributorsPage.tsx`. Let's move them to the corresponding CSS module and delete redundant rules if there're any.
8. `client/web/src/search/ShepherdTour.scss` — no changes required.
9. `client/web/src/search/home/homepage.scss`— let's the CSS variables defined here to `client/web/src/SourcegraphWebApp.scss`.

**Comment by gitstart-sourcegraph** [comment]
Hi @valerybugakov 
Migrations has been completed on highlighted files. Any more changes require changes before marking this Issue as `finished`?

**Comment by valerybugakov** [comment]
@gitstart-sourcegraph, closing this issue since all global styles are migrated to CSS modules.
