### ISSUE TITLE
Site admin global batch spec executions list page

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#23032]
Add new page from site admin area for featuring a full list of all pending and completed batch spec executions.

**Comment by courier-new** [comment]
After design session today, it is unclear how useful this would be for anyone except admins. Currently shifting to the backlog and removing from #23496.

**Comment by courier-new** [comment]
Re-pulling this one into EM 1.3 as accessible from the admin settings for site admin/developer purposes.
