### ISSUE TITLE
Search results rendering not synced with file blobs -- highlighting off

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#23056]
I searched for [`IsEmpty`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+IsEmpty+lang:go+&patternType=regexp&case=yes) in our repo. I see:

<img width="1420" alt="Screen Shot 2021-07-20 at 6 51 45 PM" src="https://user-images.githubusercontent.com/888624/126418315-224ce3d3-3cbe-4bf4-842c-71015ac199e9.png">

Note the highlights that don't highlight `IsEmpty`. Then I realized, that it's highlighting where `IsEmpty` is supposed to be. clicking on the result takes me to a `IsEmpty` match. I don't know what's causing this regression, whether backend or frontend. Video:

https://user-images.githubusercontent.com/888624/126418473-c9a39d8c-4fb6-474d-8d02-54f0e6f85cb6.mp4

**Comment by rvantonder** [comment]
Here's a simpler link with the issue: https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+PatternInfo.IsEmpty&patternType=regexp&case=yes

Note that these changes were recently merged, in the last 24 hours, so maybe some kind of syncing issue.

**Comment by lguychard** [comment]
The `version` returned in streaming matches appears to be out of sync with the revision actually being searched.

With an [even simpler query](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+f:search.go%24+PatternInfo.IsEmpty&patternType=regexp&case=yes), here are the streamed matches:

```json
[
    {
        "type":"file","name":"cmd/frontend/graphqlbackend/search.go",
        "repository":"github.com/sourcegraph/sourcegraph",
        "repoStars":4892,
        "branches":[""],
        "version":"8f1310d028f70637a8e4ec69c3b2d89c2cf19ebf",
        "lineMatches":[{
            "line":"\tif args.PatternInfo.IsEmpty() {",
            "lineNumber":335,
            "offsetAndLengths":[[9,19]]
        }]
    }
]
```

The frontend correctly requests the highlighted blob for `8f1310d028f70637a8e4ec69c3b2d89c2cf19ebf`, but [`isEmpty` does not exist on line 335 at `8f1310d028f70637a8e4ec69c3b2d89c2cf19ebf`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@8f1310d028f70637a8e4ec69c3b2d89c2cf19ebf/-/blob/cmd/frontend/graphqlbackend/search.go?L336:10&subtree=true).

When clicking through to the blob view, the revision is resolved to `03e3becb90148dcb2bcad26d7f528b1cdc6b6d71`, where [`isEmpty` does exist on line 335](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@03e3becb90148dcb2bcad26d7f528b1cdc6b6d71/-/blob/cmd/frontend/graphqlbackend/search.go?L336:10&subtree=true).

```json
// ResolveRev response
{
    "data": {
        "repositoryRedirect": {
            "__typename": "Repository",
            "mirrorInfo": {"cloneInProgress":false,"cloneProgress":"","cloned":true},
            "commit": {
                "oid": "03e3becb90148dcb2bcad26d7f528b1cdc6b6d71",
                "tree": {
                    "url":"/github.com/sourcegraph/sourcegraph"
                }
            },
            "defaultBranch": {
                "abbrevName": "main"
            }
        }
    }
}
```

**Comment by lguychard** [comment]
Tagging as `release-blocker` pending further investigation.

**Comment by stefanhengl** [comment]
Indexing of sourcegraph seems stuck at 8f13 according to the repo-settings in site admin view
https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/settings/index

**Comment by stefanhengl** [comment]
Zoekt logs
```
2021/07/21 08:22:43 updating index github.com/sourcegraph/sourcegraph@HEAD=03e3becb90148dcb2bcad26d7f528b1cdc6b6d71,3.17=e756e24b3725a525a7fb187f0c0ef441b4cfc835,main=03e3becb90148dcb2bcad26d7f528b1cdc6b6d71,v3.0.0=5ad5349157106f7b6126354799f359e07a268290
2021/07/21 08:23:24 updated index github.com/sourcegraph/sourcegraph@HEAD=03e3becb90148dcb2bcad26d7f528b1cdc6b6d71,3.17=e756e24b3725a525a7fb187f0c0ef441b4cfc835,main=03e3becb90148dcb2bcad26d7f528b1cdc6b6d71,v3.0.0=5ad5349157106f7b6126354799f359e07a268290 in 41.624296041s
```

**Comment by stefanhengl** [comment]
@tsenart and I found the issue. The metadata file is not updated if we reindex a new revision. The effect is that, although we reindex, we don't report the correct sha back to sourcegraph. We worked on a fix, but it requires more testing. I recommend to revert to unbreak production.

**Comment by keegancsmith** [comment]
Sorry about this :) This is now fixed, confirmed that prod is happy. Here is a journal entry about fixing https://github.com/sourcegraph/search-scratch/blob/master/2021/journal.org#meta-file-production-issue-2021-07-21-wed-1438
