### ISSUE TITLE
Code Insights: "Remove from dashboard" feature

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#23065]
### Background 
Currently, there is only one way to remove/unassing insight from the dashboard. You have to do that via the dashboard context menu.

It seems like we can easily add the _Remove from dashboard_ action item to the insight context menu.  

![](https://user-images.githubusercontent.com/18492575/125780047-371c2e53-0dec-4727-9a3d-bb426dc6713b.png)

### Technical details 
We should reuse jsonc setting cascade files logic from the dashboard add or remove insight modal. 
https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/insights/core/settings-action/dashboards.ts?subtree=true

**Comment by Joelkw** [comment]
@vovakulikov just curious, do you feel like this issue is appropriately pointed at a "5"? (It strikes me as perhaps a simpler change, but I'm probably missing some details – just wanted to make sure this was intentional, don't feel like you need to otherwise justify your decision or write up a justification).

**Comment by vovakulikov** [comment]
Also if we could implement a special gql mutation for removing insight I would like to have a special gql mutation for adding insights as well. In my perspective it seems like this 

```
mutation UpdatingDashboardInsights {
   removeInsightsFromDashboard(ids: [<insight ID 1>, <insights ID 2> ...]) {}
   raddInsightsToDashboard(ids: [<insight ID 1>, <insights ID 2> ...]) {}
}
```

**Comment by CristinaBirkel** [comment]
@vovakulikov For this issue it looks like you would just need to send one at a time? I'm curious the use case for wanting to remove several at a time. We can definitely do it, but just wondering the priority on that.

Off the top of my head, the current way that we add/remove insights from a dashboard can add/remove multiple at a time. Looks like right now it's just sending one request per insight. Would this change be an optimization for that?

**Comment by CristinaBirkel** [comment]
@vovakulikov Sounds good; if you ever feel it will be important (for performance reasons maybe,) feel free to create an issue and we can add that in!
