### ISSUE TITLE
Code Insights: Move insights with dashboard throughout visibility levels

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#23070]
### Context
At the moment if you change dashboard visibility from the personal to an org sharing level this operation doesn't make insights within this dashboard public (doesn't change their visibility settings)
 
https://www.figma.com/file/5ahYGyPdTGS9NVdMdRXe4m/Making-a-private-dashboard-with-private-insights...%2323003?node-id=246%3A11

**Comment by coury-clark** [comment]
I'm not sure why this is open or got tagged? This predates our entire permissions system and is not accurate. Closing unless someone else has a better idea. cc @Joelkw

**Comment by Joelkw** [comment]
No idea why still open, I found this in our backlog looking for something else related to dashboard perms and it looked bad. Thanks for closing!
