### ISSUE TITLE
Separate Sourcegraph instance for the penetration test

### ISSUE THREAD

**Issue by andreeleuterio** [sourcegraph/sourcegraph#23089]
We are currently undergoing a penetration test to simulate sourcegraph.com. The testing is happening in the dogfood instance. That has proven to be problematic since dogfood can be unstable and the testing can be blocking for our developers. Some points:

- We are more concerned on the application behaving like dotcom than the underlying infrastructure or deployment type. It is important for us to know those differences though. 
- Having GitHub/Gitlab authentication in the instance would also be great. That testing will happen in production atm.
- We don't need continuous deployment to this instance. It's our understanding that what needs testing is already shipped.

Happy to discuss the needs and understand the effort around this custom instance.

**Comment by andreeleuterio** [comment]
cc @bcreager @dan-mckean

**Comment by ggilmore** [comment]
Update here https://sourcegraph.slack.com/archives/C1JH2BEHZ/p1627408866014300
