### ISSUE TITLE
Request for 3.30.1 patch release

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#23139]
@sourcegraph/distribution I am requesting the following commits be included in a patch release. They are already merged into `main`:

- 2b1c33d5dc60e4f7f4e4fa5455eeaded78f05d2e

I have read [when and why we perform patch releases](https://about.sourcegraph.com/handbook/engineering/releases#when-are-patch-releases-performed) and answer the questions as follows:

> Are users/customers actively asking us for these changes and cannot wait until the next full release?

No, but they definitely will be.

> Are the changes extremely minimal, well-tested, and low risk such that not testing as we do in a full release is OK?

Yes, they affect ONLY (1) API docs (which is clearly marked experimental) and (2) the code intelligence hovers (to fix the regression, this is a few lines changed only)

> Is there some functionality completely broken that warrants redacting the prior release of Sourcegraph and advising users wait for the patch release?

Yes, the web UI is currently showing errors when viewing code files - due to a table name having been typo'd in an SQL query:

```
lsifStore.Ranges: ERROR: relation \"lsif_documentation_mappings\" does not exist (SQLSTATE 42P01)
```

> This will interrupt our regular planned work and release cycle, taking one full working day of our time, and will take up all of our site admin's valuable time by asking them to upgrade or producing noise for them if they don't need to upgrade.
>
> Do you believe the changes are important enough to warrant this?

Yes.

> Patch releases are a signal we can do something better to improve the quality of Sourcegraph. Have you already scheduled a call (or created a google doc) to perform a [retrospective](https://about.sourcegraph.com/retrospectives) and identify ways we can improve?

We will be improving testing on API docs very soon (which was the root cause of this issue.) It is unlikely to occur again, it was just poor timing with the release branch cut.

---

**For the [release captain](https://about.sourcegraph.com/handbook/engineering/releases#release-captain)** - after reviewing and approving this request:

- If there is [already an upcoming patch release](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+), add the listed commits alongside a link to this issue
- If there is no upcoming patch release, create a new one:
  - Update [`dev/release/release-config.jsonc`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/release/release-config.jsonc) with the patch release in `upcomingRelease` and `releaseDate` (and open a PR to `main` to update it)
  - `yarn release tracking:issues`
  - Add the listed commits alongside a link to this issue to the generated [release tracking issue](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+)

Comment and close this issue once the relevant commit(s) have been cherry-picked into the release branch.

**Comment by slimsag** [comment]
I have already created the CHANGELOG entry: https://github.com/sourcegraph/sourcegraph/blob/main/CHANGELOG.md#3301

**Comment by daxmc99** [comment]
Approved, starting the patch release process now.

**Comment by daxmc99** [comment]
Closed in https://github.com/sourcegraph/sourcegraph/issues/23143
