### ISSUE TITLE
symbols: Indexed symbols sidebar query returns incorrect column

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#23134]
#### Steps to reproduce:

1. Click on a symbol in the symbols sidebar within an _indexed_ revision of a tree

#### Expected behavior:

The indexed search path should behave the same as the unindexed search path, which returns the correct column offsets for symbol ranges.

![Kapture 2021-07-22 at 14 09 21](https://user-images.githubusercontent.com/103087/126695818-28e0b3af-1de0-40f8-a842-59e8378f7255.gif)

#### Actual behavior:

All symbols from the indexed search path return a column of zero. (Note the URL after navigating from a symbol).

![Kapture 2021-07-22 at 13 57 03](https://user-images.githubusercontent.com/103087/126695438-415b4ed1-e875-4d0a-88f3-4cbf97914d3d.gif)

This is an issue with how the frontend deals with symbol results from Zoekt. Note that the same problem was previously [fixed on a different code path](https://github.com/sourcegraph/sourcegraph/pull/17258). That issue may link to useful context about this code path.

**Comment by rvantonder** [comment]
To clarify: in the second screenshot, the clicked symbols should be highlighting and it is not, right? (and the reason for this is some index/offset shenanigans).

> This is an issue with how the frontend deals with symbol results from Zoekt. 

Hmm, the previous issue wasn't a frontend one though. Will see if I can find anything looking into this, but no promises.

**Comment by efritz** [comment]
Try the query at [`HEAD`](https://sourcegraph.com/api/console#%7B%22query%22%3A%22query%20Symbols(%24repo%3A%20ID!%2C%20%24revision%3A%20String!%2C%20%24first%3A%20Int%2C%20%24query%3A%20String%2C%20%24includePatterns%3A%20%5BString!%5D)%20%7B%5Cn%20%20node(id%3A%20%24repo)%20%7B%5Cn%20%20%20%20__typename%5Cn%20%20%20%20...%20on%20Repository%20%7B%5Cn%20%20%20%20%20%20commit(rev%3A%20%24revision)%20%7B%5Cn%20%20%20%20%20%20%20%20symbols(first%3A%20%24first%2C%20query%3A%20%24query%2C%20includePatterns%3A%20%24includePatterns)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20...SymbolConnectionFields%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%5Cn%5Cnfragment%20SymbolConnectionFields%20on%20SymbolConnection%20%7B%5Cn%20%20pageInfo%20%7B%5Cn%20%20%20%20hasNextPage%5Cn%20%20%7D%5Cn%20%20nodes%20%7B%5Cn%20%20%20%20...SymbolNodeFields%5Cn%20%20%7D%5Cn%7D%5Cn%5Cnfragment%20SymbolNodeFields%20on%20Symbol%20%7B%5Cn%20%20name%5Cn%20%20containerName%5Cn%20%20kind%5Cn%20%20language%5Cn%20%20location%20%7B%5Cn%20%20%20%20resource%20%7B%5Cn%20%20%20%20%20%20path%5Cn%20%20%20%20%7D%5Cn%20%20%20%20range%20%7B%5Cn%20%20%20%20%20%20start%20%7B%5Cn%20%20%20%20%20%20%20%20line%5Cn%20%20%20%20%20%20%20%20character%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20end%20%7B%5Cn%20%20%20%20%20%20%20%20line%5Cn%20%20%20%20%20%20%20%20character%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%20%20url%5Cn%7D%5Cn%22%2C%22variables%22%3A%22%7B%5Cn%20%20%5C%22repo%5C%22%3A%20%5C%22UmVwb3NpdG9yeTozNjgwOTI1MA%3D%3D%5C%22%2C%5Cn%20%20%5C%22revision%5C%22%3A%20%5C%22HEAD%5C%22%2C%5Cn%20%20%5C%22first%5C%22%3A%201%2C%5Cn%20%20%5C%22query%5C%22%3A%20%5C%22%5C%22%2C%5Cn%20%20%5C%22includePatterns%5C%22%3A%20%5B%5D%5Cn%7D%22%2C%22operationName%22%3A%22Symbols%22%7D) vs the query at [`HEAD~1`](https://sourcegraph.com/api/console#%7B%22query%22%3A%22query%20Symbols(%24repo%3A%20ID!%2C%20%24revision%3A%20String!%2C%20%24first%3A%20Int%2C%20%24query%3A%20String%2C%20%24includePatterns%3A%20%5BString!%5D)%20%7B%5Cn%20%20node(id%3A%20%24repo)%20%7B%5Cn%20%20%20%20__typename%5Cn%20%20%20%20...%20on%20Repository%20%7B%5Cn%20%20%20%20%20%20commit(rev%3A%20%24revision)%20%7B%5Cn%20%20%20%20%20%20%20%20symbols(first%3A%20%24first%2C%20query%3A%20%24query%2C%20includePatterns%3A%20%24includePatterns)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20...SymbolConnectionFields%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%5Cn%5Cnfragment%20SymbolConnectionFields%20on%20SymbolConnection%20%7B%5Cn%20%20pageInfo%20%7B%5Cn%20%20%20%20hasNextPage%5Cn%20%20%7D%5Cn%20%20nodes%20%7B%5Cn%20%20%20%20...SymbolNodeFields%5Cn%20%20%7D%5Cn%7D%5Cn%5Cnfragment%20SymbolNodeFields%20on%20Symbol%20%7B%5Cn%20%20name%5Cn%20%20containerName%5Cn%20%20kind%5Cn%20%20language%5Cn%20%20location%20%7B%5Cn%20%20%20%20resource%20%7B%5Cn%20%20%20%20%20%20path%5Cn%20%20%20%20%7D%5Cn%20%20%20%20range%20%7B%5Cn%20%20%20%20%20%20start%20%7B%5Cn%20%20%20%20%20%20%20%20line%5Cn%20%20%20%20%20%20%20%20character%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20end%20%7B%5Cn%20%20%20%20%20%20%20%20line%5Cn%20%20%20%20%20%20%20%20character%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%20%20url%5Cn%7D%5Cn%22%2C%22variables%22%3A%22%7B%5Cn%20%20%5C%22repo%5C%22%3A%20%5C%22UmVwb3NpdG9yeTozNjgwOTI1MA%3D%3D%5C%22%2C%5Cn%20%20%5C%22revision%5C%22%3A%20%5C%22HEAD~1%5C%22%2C%5Cn%20%20%5C%22first%5C%22%3A%201%2C%5Cn%20%20%5C%22query%5C%22%3A%20%5C%22%5C%22%2C%5Cn%20%20%5C%22includePatterns%5C%22%3A%20%5B%5D%5Cn%7D%22%2C%22operationName%22%3A%22Symbols%22%7D). The former query will always give you a range offset starting at col zero on the correct line (as that's what Zoekt makes available). The latter query will give you the correct range offset, because the symbols service makes the additional information available.

**Comment by rvantonder** [comment]
@efritz I wanted to tackle this today but I can no longer reproduce 😮 . Also your link to the query of `HEAD` vs `HEAD~1` produce the same (non-zero) offsets 😮 . I did check before and did see that they gave 0 offset for the first, so I remember that not being the case before. Vidya:


https://user-images.githubusercontent.com/888624/128276059-914c4815-7911-4d79-b804-f22b5cabe4bc.mp4


[query example for video](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/api/api.go?L11:6-11:12)


Can you confirm it's not cropping up? I may bisect to see if I can identify a bug fixing commit if you confirm it's fixed. Other than that, any chance that there may not have been a successful precise/semantic upload for the latest HEAD commit, so that we're dealing with a state/precise issue here (which causes a fallback to a different symbol search or something?) Just putting out ideas because honestly its a bit weird--I'm not sure that any code was touched to fix this and there may not be a bug fixing commit.

**Comment by efritz** [comment]
@rvantonder You can't reproduce it because `main` is still indexing; you only hit the unindexed path. Wait until main has an index (or use a branch that's currently indexed for the sg/sg repo).

**Comment by efritz** [comment]
For example: [v3.0.0 - indexed](https://sourcegraph.com/api/console#%7B%22query%22%3A%22query%20Symbols(%24repo%3A%20ID!%2C%20%24revision%3A%20String!%2C%20%24first%3A%20Int%2C%20%24query%3A%20String%2C%20%24includePatterns%3A%20%5BString!%5D)%20%7B%5Cn%20%20node(id%3A%20%24repo)%20%7B%5Cn%20%20%20%20__typename%5Cn%20%20%20%20...%20on%20Repository%20%7B%5Cn%20%20%20%20%20%20commit(rev%3A%20%24revision)%20%7B%5Cn%20%20%20%20%20%20%20%20symbols(first%3A%20%24first%2C%20query%3A%20%24query%2C%20includePatterns%3A%20%24includePatterns)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20...SymbolConnectionFields%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%5Cn%5Cnfragment%20SymbolConnectionFields%20on%20SymbolConnection%20%7B%5Cn%20%20pageInfo%20%7B%5Cn%20%20%20%20hasNextPage%5Cn%20%20%7D%5Cn%20%20nodes%20%7B%5Cn%20%20%20%20...SymbolNodeFields%5Cn%20%20%7D%5Cn%7D%5Cn%5Cnfragment%20SymbolNodeFields%20on%20Symbol%20%7B%5Cn%20%20name%5Cn%20%20containerName%5Cn%20%20kind%5Cn%20%20language%5Cn%20%20location%20%7B%5Cn%20%20%20%20resource%20%7B%5Cn%20%20%20%20%20%20path%5Cn%20%20%20%20%7D%5Cn%20%20%20%20range%20%7B%5Cn%20%20%20%20%20%20start%20%7B%5Cn%20%20%20%20%20%20%20%20line%5Cn%20%20%20%20%20%20%20%20character%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20end%20%7B%5Cn%20%20%20%20%20%20%20%20line%5Cn%20%20%20%20%20%20%20%20character%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%20%20url%5Cn%7D%5Cn%22%2C%22variables%22%3A%22%7B%5Cn%20%20%5C%22repo%5C%22%3A%20%5C%22UmVwb3NpdG9yeTozNjgwOTI1MA%3D%3D%5C%22%2C%5Cn%20%20%5C%22revision%5C%22%3A%20%5C%22v3.0.0%5C%22%2C%5Cn%20%20%5C%22first%5C%22%3A%201%2C%5Cn%20%20%5C%22query%5C%22%3A%20%5C%22%5C%22%2C%5Cn%20%20%5C%22includePatterns%5C%22%3A%20%5B%5D%5Cn%7D%22%2C%22operationName%22%3A%22Symbols%22%7D) vs [v3.0.1 - unindexed](https://sourcegraph.com/api/console#%7B%22query%22%3A%22query%20Symbols(%24repo%3A%20ID!%2C%20%24revision%3A%20String!%2C%20%24first%3A%20Int%2C%20%24query%3A%20String%2C%20%24includePatterns%3A%20%5BString!%5D)%20%7B%5Cn%20%20node(id%3A%20%24repo)%20%7B%5Cn%20%20%20%20__typename%5Cn%20%20%20%20...%20on%20Repository%20%7B%5Cn%20%20%20%20%20%20commit(rev%3A%20%24revision)%20%7B%5Cn%20%20%20%20%20%20%20%20symbols(first%3A%20%24first%2C%20query%3A%20%24query%2C%20includePatterns%3A%20%24includePatterns)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20...SymbolConnectionFields%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%5Cn%5Cnfragment%20SymbolConnectionFields%20on%20SymbolConnection%20%7B%5Cn%20%20pageInfo%20%7B%5Cn%20%20%20%20hasNextPage%5Cn%20%20%7D%5Cn%20%20nodes%20%7B%5Cn%20%20%20%20...SymbolNodeFields%5Cn%20%20%7D%5Cn%7D%5Cn%5Cnfragment%20SymbolNodeFields%20on%20Symbol%20%7B%5Cn%20%20name%5Cn%20%20containerName%5Cn%20%20kind%5Cn%20%20language%5Cn%20%20location%20%7B%5Cn%20%20%20%20resource%20%7B%5Cn%20%20%20%20%20%20path%5Cn%20%20%20%20%7D%5Cn%20%20%20%20range%20%7B%5Cn%20%20%20%20%20%20start%20%7B%5Cn%20%20%20%20%20%20%20%20line%5Cn%20%20%20%20%20%20%20%20character%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20end%20%7B%5Cn%20%20%20%20%20%20%20%20line%5Cn%20%20%20%20%20%20%20%20character%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%20%20url%5Cn%7D%5Cn%22%2C%22variables%22%3A%22%7B%5Cn%20%20%5C%22repo%5C%22%3A%20%5C%22UmVwb3NpdG9yeTozNjgwOTI1MA%3D%3D%5C%22%2C%5Cn%20%20%5C%22revision%5C%22%3A%20%5C%22v3.0.1%5C%22%2C%5Cn%20%20%5C%22first%5C%22%3A%201%2C%5Cn%20%20%5C%22query%5C%22%3A%20%5C%22%5C%22%2C%5Cn%20%20%5C%22includePatterns%5C%22%3A%20%5B%5D%5Cn%7D%22%2C%22operationName%22%3A%22Symbols%22%7D).

**Comment by rvantonder** [comment]
... OK thanks for clarifying (I don't like that indexed vs unindexed for symbols so opaque, like, there's no obvious way to know from the UI, but OK, I know the answer why this is. There's also this drawback of  previous links not persisting the reproducible issue. sigh.)

**Comment by efritz** [comment]
@rvantonder Is zoekt vs symbols sent back in any way from the graphql layer today?

**Comment by rvantonder** [comment]
You mean is it indicated in the GQL response? Unsure :-)
