### ISSUE TITLE
idea: PR bot that blocks build if PR lacks tests and lacks justification

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#2313]
Related https://github.com/sourcegraph/sourcegraph/issues/2312

**Comment by felixfbecker** [comment]
> PR bot that blocks build if PR lacks tests

That's what codecov does. Imo if a reason needs to be provided that reason needs to be reviewed by humans, so that part cannot be automated. A reviewer can look at the codecov status/report and if it lacks tests approve/reject depending based on if the justification is reasonable.

**Comment by slimsag** [comment]
Yes, I agree. This is something I did not think much about, I just filed because Quinn explicitly mentioned it and I wanted to ensure I gave it proper thought. The only beneficial thing here I can imagine would be ensuring people do not ignore a PR checklist, but that is honestly not worth automating IMO.
