### ISSUE TITLE
Docker Compose all the things

### ISSUE THREAD

**Issue by emchap** [sourcegraph/sourcegraph#23145]
#### Describe the issue

Trying to limit the number of places where we reference single-node Docker and k8s but not Docker Compose. Came out of https://sourcegraph.slack.com/archives/CJX299FGE/p1625766854015100 . Dunno if this is a Distro or CSE project. 

#### Where is the issue located?
* [x] https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/doc/admin/auth/index.md - Troubleshooting section
* [x] https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/doc/admin/auth/saml/azure_ad.md - "Add the SAML auth provider" section about troubleshooting
* [x] https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/doc/admin/auth/saml/generic.md - Same as above
* [x] https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/doc/admin/auth/saml/index.md - SAML troubleshooting section
* [x] https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/doc/admin/auth/saml/jump_cloud.md - Configure SAML authentication provider section
* [x] https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/doc/admin/auth/saml/microsoft_adfs.md - Add the SAML auth provider section
* [x] https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/doc/admin/auth/saml/okta.md - Same as above
* [x] https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/doc/admin/auth/saml/one_login.md - Same as above
* [x] https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/doc/admin/config/advanced_config_file.md - Site configuration section, Code host configuration section, Global settings config section. (I'm assuming cluster deployment = k8s?)
* [x] https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/doc/admin/config/site_config.md - Editing your site config... section
* [x] https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/doc/admin/faq.md - We list single-node and k8s and that's it
* [x] https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/doc/admin/migration/opengrok.md - Deploying sourcegraph section
* [x] https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/doc/admin/postgres.md - Single container and k8s instructions but no compose
* [x] https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/doc/admin/pprof.md - Exposing the debug... section
* [x] https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/doc/admin/repo/add.md - Troubleshooting section
* [x] https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/doc/admin/repo/custom_git_or_ssh_config.md - Missing compose section
* [x] https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/doc/admin/repo/pre_load_from_local_disk.md - "The steps documented above..." may be missing a clarification if this applies to the compose deployments

#### Suggested resolution

Add Compose info.

**Comment by bobheadxi** [comment]
Wow thanks for compiling this list together!

**Comment by emchap** [comment]
@bobheadxi Not to be all "not just the president, I'm a member" but getting this info out of Sourcegraph was super quick!
