### ISSUE TITLE
Require codecov does not regress as PR status check

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#2314]
(and don't report erroneous change in various Go tests)

Then, afterwards, require codecov does not regress as a PR status check?

**Comment by keegancsmith** [comment]
I fixed a few of these at the end of last year since it used to annoy me so much. If you see any, please paste it to this issue so we can track them.

**Comment by sqs** [comment]
Related: #319

**Comment by slimsag** [comment]
Fixed by @nicksnyder
