### ISSUE TITLE
Add code host filter 

### ISSUE THREAD

**Issue by chrislovett03** [sourcegraph/sourcegraph#23141]
#### Feature request description

Add a filter to include results by the selected code host:
ex: `host:gitlab`, `host:github`,  `host:bitbucket`

#### Is your feature request related to a problem? If so, please describe.

This would help users narrow results by code host

#### Describe alternatives you've considered.

The current workaround is to use a generic repo filter like: `repo:github.com/*`

#### Additional context

[Customer Request](https://app.hubspot.com/contacts/2762526/company/578600789)

**Comment by benvenker** [comment]
@camdencheek or @lguychard any initial thoughts on complexity of this?

**Comment by benvenker** [comment]
@rvantonder pinging you just for thoughts on this

**Comment by camdencheek** [comment]
I think this would be a great use case for @fkling's query aliases. I'm not sure it's worth polluting the query language with more keywords for something that's fairly elegantly solved just with `repo:^github.com`, but if a user wants this, a custom alias would be perfect for it.

**Comment by christinelovett** [comment]
@alexfogg

**Comment by benvenker** [comment]
@camdencheek yeah Loïc had similar thoughts re: the query language. I don't know much about the query aliases, but maybe I'm forgetting something I've seen...is there a ticket or example I can can check out?

**Comment by camdencheek** [comment]
I don't know if there are any open tickets for it right now (I don't think the work has been prioritized), but you can find Felix's original presentation for aliases from our offset [here](https://docs.google.com/presentation/d/1gDT38uxrmgjlWH3ylRPPGHUv4x8gIEIHOM4gqgCwh44/edit?usp=sharing)

**Comment by benvenker** [comment]
Yeah that's an interesting idea. For the code host case, I wonder if that's a little confusing vis a vis Search Contexts though, given that they will tend to be associated with larger buckets of repos. I know that's not related to the code host, per se, but they're conceptually similar enough that I could see users wondering why they have to do something different for a code host "context".
