### ISSUE TITLE
Search notebook diagnostics are not multiline

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#23152]
Diagnostics are not multiline, they probably need a similar fix to the hover code.

Also we're not using the same CSS for notebooks that suppresses some hover ugliness in our standard search query bar. We probably want to add that.

![Screen Shot 2021-07-22 at 6 02 06 PM](https://user-images.githubusercontent.com/888624/126726662-084d0c2f-02fb-4edd-a65a-d5a555620c15.png)

Just assigning myself and Rok for visibility

**Comment by lguychard** [comment]
Fixed when we migrated to CodeMirror

![image.png](https://images.zenhubusercontent.com/61434ea43ff890091f5e83f9/b9c07706-46ed-442b-98fc-954cea5562e9)
