### ISSUE TITLE
When clicking through entries in "Symbols" sidebar, hover tooltips seem to randomly show up or not

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#23166]
See this video:

https://user-images.githubusercontent.com/1185253/126781900-31d02109-74c0-4e62-ab1a-2d8193e50f23.mp4

I can reproduce this pretty reliably by clicking through the symbols here: https://sourcegraph.com/github.com/golang/go/-/blob/src/os/exec/exec.go?L189:1-189:15

Sometimes a tooltip shows up, sometimes it doesn't, sometimes it flickers.

It feels really bad and unreliable.

Not sure whether this is @sourcegraph/code-intel or @sourcegraph/extensibility or @sourcegraph/frontend-platform though.

**Comment by Strum355** [comment]
Is this the same issue as https://github.com/sourcegraph/sourcegraph/issues/23134 ?

**Comment by mrnugget** [comment]
Closing because it's a duplicate of #23134

**Comment by rvantonder** [comment]
Fixed on Sourcegraph.com :-) https://github.com/sourcegraph/sourcegraph/pull/23664
