### ISSUE TITLE
CLA bot is stuck?

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#2317]
My PR https://github.com/sourcegraph/sourcegraph/pull/2304 has been stuck on the CLA bot for ~30 minutes.

I am unable to merge my change due to this, so I am temporarily disabling the CLA bot as a required status check. We will need to investigate and re-enable. cc @tsenart

**Comment by nicksnyder** [comment]
I restarted the pod to see if that helps

**Comment by nicksnyder** [comment]
seems to have passed [here](https://github.com/sourcegraph/sourcegraph/pull/2323) so I re-enabled it as a required check
