### ISSUE TITLE
Search CTA should be dismissable

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#23180]
Search CTA for unauthenticated users should be permanently dismissable. We should also measure how many users dismiss it.

![image](https://user-images.githubusercontent.com/206864/126821807-45c26667-85dc-41d9-9a09-fcbcbd3b24ff.png)

**Comment by limitedmage** [comment]
@rrhyne  Do we have a design for this?

**Comment by rrhyne** [comment]
Closed by https://github.com/sourcegraph/sourcegraph/pull/30169
