### ISSUE TITLE
Change extension based insights fetch approach to load insights independently to avoid double(re)-fetching problem

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#23187]
### Context

At the moment our search-based and code-stats insights are working via extension-based API.
And that means that we load all extension-based insights via extension API and BE-based insight in the main thread together

To visualize this approach we're getting something like this 

<img width="649" alt="Screenshot 2021-08-02 at 18 32 29" src="https://user-images.githubusercontent.com/18492575/127886663-beffc74f-7044-4e30-b162-56c627e0b49f.png">

This system was very convenient at the beginning but currently, we're struggling with that approach. For example, if we want to reload some particular insight that triggers re-fetching all other insights on the page. You can read about this problem in [this doc](https://docs.google.com/document/d/14j63ngu5OUE2wfczQU80j1o6YGYScRNtMO87oG3hWXM/edit#)

### Proposal

In order to solve this problem we have to separate insights loading system and have something similar to the system below 

<img width="746" alt="Screenshot 2021-08-02 at 18 36 28" src="https://user-images.githubusercontent.com/18492575/127887152-6dae8ae6-caf8-4e35-99ac-40056b5b9b00.png">

With that system, we can avoid the re-fetching problem but we still have to take into account that we have other places for insights like the directory page and homepage. At these views, all data is loaded by consumer's views (that means that the directory page is in charge to load data for the insight grid component) In this case we have to provide some composable stateless components to render insight data instead of providing smart insight component with fetching (in theory we can adopt the new approach of loading insights that is described above but for this ticket, we should avoid refactoring of loading other consumer views)

**Comment by Joelkw** [comment]
@vovakulikov just want to confirm, since I see this issue will be a big lift – is this necessary for the drilldown implementation? (I trust your answer so a simple yes/no is fine, just double checking!)

**Comment by vovakulikov** [comment]
@Joelkw **Yes** to avoid double fetching and other insight re-fetching if one drill-down filter of one particular insight has been changed. 

Yeah, we have to change our loading system. **BUT** I'm almost sure that I've figured out how to do that without moving all extensions code-bases to the app codebase (eventually I still want to do that but taking into account that we don't have a lot of time I'm considering if doing this after our beta release)

**Comment by Joelkw** [comment]
@vovakulikov thanks! Understand, and we will make time in the roadmap for anything you want to push out of the beta release to make sure we're running on time for that otehrwise.

**Comment by felixfbecker** [comment]
@vovakulikov since https://github.com/sourcegraph/sourcegraph/pull/23244 says it closes "part of" this issue, and you said above that you only want to do part of this issue for the Beta, and the issue overall is part of the tracking issue and rated at 5d – could you split this issue into the two parts that you want to get done before Beta, and the other you want to get done after? 🙂
