### ISSUE TITLE
Implement UI for the drill down insight filters

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#23189]
### Context

This ticket implies UI-only implementation (only visible components) for the drill-down project. You can find designs for this [here](https://www.figma.com/file/1zvF8Owrh1ndVH29lvyrXn/RFC-419%3A-Code-Insights-“Drilldown”?node-id=260%3A11).

### Screenshots
![Frame 5108](https://user-images.githubusercontent.com/18492575/127826263-77eb8169-1947-4c71-a599-fe2fc685dd70.png)

For the first version of drill-down, we are gonna implement only the regexp tab but in the future, we will other ways to setup drill-down filters (like an explicit list of all repos)

**Comment by felixfbecker** [comment]
We're only doing regex for now, right (no list tab)?

**Comment by AlicjaSuska** [comment]
That's correct @felixfbecker Here is the [design](https://www.figma.com/file/1zvF8Owrh1ndVH29lvyrXn/RFC-419-Code-Insights-%E2%80%9CDrilldown%E2%80%9D?node-id=1109%3A12703) for this part of the project only @vovakulikov

**Comment by vovakulikov** [comment]
Thanks, @felixfbecker, and @AlicjaSuska for pointing out this. I changed estimation and description of this issue and creates another one for the repo list UI https://github.com/sourcegraph/sourcegraph/issues/23441
