### ISSUE TITLE
Regular expression behavior for `file:` with `type:diff` 

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#23191]
This is a crazy bug. With `type:diff` active, for some reason, whether a `file:` value is parenthesized changes the result:

[`repo:^github\.com/sourcegraph/sourcegraph$ file:internal/gitserver type:diff after:"2021-05-17T00:49:10Z"`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:internal/gitserver+type:diff+after:%222021-05-17T00:49:10Z%22&patternType=literal) - 5 results

[`repo:^github\.com/sourcegraph/sourcegraph$ file:(internal/gitserver) type:diff after:"2021-05-17T00:49:10Z"`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:%28internal/gitserver%29+type:diff+after:%222021-05-17T00:49:10Z%22&patternType=literal) - 3 results

The only difference is `file:internal/gitserver` versus `file:(internal/gitserver)`. Since `(...)` is just a grouping, this shouldn't matter at all. 

I believe this is something to do with how we interpret file patterns when we call out to git. I don't believe this problem manifests for content/file search for example.

I discovered this after I asked about the change made in https://github.com/sourcegraph/sourcegraph/pull/22209, and @DaedalusG pointed out this example of incorrect results. This actually started with a customer who attempted to use `file:(foo)|(bar)` and didn't get expected results, but did get expected results for `(file:foo or file:bar)`!

**Comment by camdencheek** [comment]
I tracked the issue down to [these lines](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/vcs/git/diff_search.go?L504-521&subtree=true). Essentially, we attempt to create a git glob that is a superset of what the regex would match. If we can't make one that is exactly equivalent, we add a limit of 500 commits and run the regex pattern against them as a post-processing step.

In this cas, the capture group syntax causes creating an equivalent glob to fail, so we limit to 500 commits to post-process, and the 500 latest commits aren't nearly all the commits that could've touched that file. 

Now that we stream commit results, can we just get rid of that limit?

**Comment by rvantonder** [comment]
Wow, interesting! I can see the limit fix being a stopgap. The problem for this particular issue though I feel like is the `regex -> glob` conversion. A naively parenthesized regex, like the original input `(thing)`, should have a valid conversion. I don't know where we can draw the line--like, `(foo)|(bar)` is not naively parenthesized. This is brittle and a new discovery for me :-) 

Two other solution spacese:

- `+1` for the fact that a generic `or` routine is more well-behaved.
- if/when we _default_ to `file:glob(...)` semantics then this will help. We can keep the current behavior for `file:regexp(...)`.

I'll see if I can PR the `glob` branch I have some time. In the meantime, probably the stopgap is most reasonable...

**Comment by camdencheek** [comment]
Closing since this was fixed with the commit/diff search rewrite. We now use go's regex engine to filter files and do not convert to glob patterns.
