### ISSUE TITLE
Need to be logged in to view code discussions

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#232]
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:** MacOS Mojave, Chrome 69.0.3497.100

#### Steps to reproduce:

1. Not logged into Sourcegraph.com
2. https://sourcegraph.com/github.com/sourcegraph/sourcegraph-extension-api/-/blob/src/sourcegraph.d.ts#L1-2&tab=discussions&threadID=28

#### Expected behavior:

See code discussions.

#### Actual behavior:

Cannot see code discussions.

**Comment by slimsag** [comment]
@sqs any chance you could update the blog post to include a footnote about requiring login until I get around to fixing this?

**Comment by sqs** [comment]
(Updated blog post on about.sourcegraph.com (will be live soon) and in the about repo in https://github.com/sourcegraph/about/commit/e765119b2188a84b841c55df1cb7c8d1b7eb6079)

**Comment by sqs** [comment]
This is fixed now

![screenshot from 2018-10-25 01-52-03](https://user-images.githubusercontent.com/1976/47488123-936c2700-d7f8-11e8-9e56-c6311539b07a.png)
