### ISSUE TITLE
Add back the ability to set color options per series to a backend insight

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#23205]
We should let users set color per series to a graph since it makes the insight easier to track two different series of and also naturally more visually attractive.

**Comment by vovakulikov** [comment]
@coury-clark it may also require some effort on the BE as well cause currently gql handle doesn't return any info about these settings.

**Comment by coury-clark** [comment]
Is this a regression? I'm not entirely clear on why this would break - the options are still stored and kept in user settings by design so that we can use this functionality without fully migrating to the backend yet.

**Comment by felixfbecker** [comment]
Yeah I would think the same, @vovakulikov can you match the series returned by the backend to the config in settings through the index or the label?

**Comment by vovakulikov** [comment]
@felixfbecker Technically I can match settings and data and I think this is the optimal option for the next release but I'm usually trying to avoid gathering and combining information from the different sources on FE to make it as simple as possible and not having a bunch of data sources.
