### ISSUE TITLE
How to add a code host and add a repository by API?

### ISSUE THREAD

**Issue by KashingLiu** [sourcegraph/sourcegraph#23219]
#### Question description

I have a repository list which is refreshed everyday, and it may delete some repo or add some repo. I don't want to add or delete the repo in my Sourcegraph manually. I hope there is a API to **add** a repo. HOW can I use some API or automatic workflow to update my repository? 

I try to analyze the request and I find when I click the Update Repository button, there is a POST request like this: 
{"query":"\n            mutation UpdateExternalService($input: UpdateExternalServiceInput!) {\n                updateExternalService(input: $input) {\n                    ...ExternalServiceFields\n                }\n            }\n            \n    fragment ExternalServiceFields on ExternalService {\n        id\n        kind\n        displayName\n        config\n        warning\n        lastSyncError\n        repoCount\n        webhookURL\n        lastSyncAt\n        nextSyncAt\n        updatedAt\n        createdAt\n        namespace {\n            id\n            namespaceName\n            url\n        }\n    }\n\n        ","variables":{"input":{"__typename":"ExternalService","id":"RXh0ZXJuYWxTZXJ2aWNlOjI=","kind":"OTHER","displayName":"codehub-repositories","config":"{\n  \"url\": \"REDACTED\",\n  \"repos\": [\n    \"ABC/DEF.git\",\n    \"ABC/DEF.git\",\n    \"ABC/DEF.git\",\n    \"ABC/DEF.git\"\n  ]\n}","warning":null,"lastSyncError":null,"repoCount":3,"webhookURL":null,"lastSyncAt":"2021-07-26T07:59:26Z","nextSyncAt":"2021-07-26T08:00:26Z","updatedAt":"2021-07-26T07:59:17Z","createdAt":"2021-07-08T08:19:27Z","namespace":null}}}
and the url is *http://mysourcegraphsite.com:7080/.api/graphql?UpdateExternalService*, so I make a POST request by curl which include these parameters, but there is nothing shows on the console.

**Comment by KashingLiu** [comment]
I don't know the relationship between UpdateExternalServiceInput ID fields and the code host which I want to update
![image](https://user-images.githubusercontent.com/22939122/127113265-e49c33fc-1baf-4715-9aee-4ad161c77852.png)

I decode the id and it means ExternalService:10. What does the number 10 mean? Does it mean a function id, like 1 means update, 2 means delete, 3 means update? Or 1 means the first repository, 2 means the second repository? 
![image](https://user-images.githubusercontent.com/22939122/127113439-a0bc67bb-1157-4e8d-993f-64a1c0dbd6d1.png)

**Comment by unknwon** [comment]
Hey! 10 is the internal database ID, and you can find base64 encoded ID of an external service by browsing to the UI:

![CleanShot 2021-09-07 at 11 59 50@2x](https://user-images.githubusercontent.com/2946214/132282252-b2c7ec2f-c1d1-4ede-8876-eb779a968088.png)
