### ISSUE TITLE
Code Insights: Implement save this as new insight feature

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#23233]
### Context

With filled drill-down filters, the user can save their insight with settings as a new insight with prefilled settings. [Figma design link](https://www.figma.com/file/1zvF8Owrh1ndVH29lvyrXn/RFC-419%3A-Code-Insights-“Drilldown”?node-id=935%3A4643)

<table>
<tr><th>Filter panel button</th><th>Creation Insight flow from filtered insight</th></tr>
<tr>
  <td>
    <img width="192" alt="image" src="https://user-images.githubusercontent.com/18492575/127016101-059808ff-acf7-4549-a8bb-db93f1ecb03b.png">
  </td>
  <td>
  <img width="317" alt="image" src="https://user-images.githubusercontent.com/18492575/127016392-bc01fbad-0293-4d46-bebe-ec85eebf2d23.png">
  </td>
</tr>
<table>

### Tech notes
Right after gql creation request, we have to write returned from the gql request insight (view) id to the setting cascade BE insight section.

**Comment by Joelkw** [comment]
I believe cc @AlicjaSuska that this isn't quite done/resolved yet? (There's a way both to "save as new insight" and "save filters on this insight" in the versions we discussed towards the end of last week.) So moving to in-design.
