### ISSUE TITLE
Add options to select documentation in search reference

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#23249]
Update the select documentation to add all additional values as so:
```

Shows only query results for a given type. For example, select:repo displays only distinct repository paths from search results. The following values are available:

* select:repo
* select:commit.diff.added
* select:commit.diff.removed
* select:file
* select:file.directory
* select:file.path
* select:content
* select:symbol.symboltype

See the language definition for more information on possible values.
```

And the following examples:

`select:commit.diff.added //TODO`
`select:file.directory`

**Comment by rrhyne** [comment]
Content should follow the results of this PR:

https://github.com/sourcegraph/sourcegraph/blob/ff1b62b0d056cbfba328fe73054f06936ca83d38/doc/code_search/reference/queries.md

**Comment by fkling** [comment]
Do you mean to just update the documentation? Because that only mentions `select:commit.diff.added`. Or do you want to have multiple entries of `select:`? At the moment we only have a single entry, `select:result-type`.

**Comment by rrhyne** [comment]
I updated the issue to be more clear.
