### ISSUE TITLE
insights: commit index is generating an incomplete history

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#23268]
On k8s-dogfood it seems the commit index for some repositories has a fraction of the commits I'd expect to see. Below is the results for the sourcegraph/about repository. When I noticed this problem yesterday I assumed it was related to the recent k8s wipe / rebuild, so I purged all of the dirty indices and let them repopulate. Below is the result after the first index. We should expect to see the past year of commits for this repository.

This index is designed to be atomically created, and if it exists in this partial historical state (with missing historical commits) the compression mechanism will not function properly for insights.

`select * from commit_index where repo_id = 276 order by committed_at;`

| committed\_at | repo\_id | commit\_bytea |
| :--- | :--- | :--- |
| 2021-07-27 03:25:47.000000 | 276 | E'\\\\x31F1494D591FE0A9E5C8FB82755CA36BE91BA8A9' |
| 2021-07-27 04:45:36.000000 | 276 | E'\\\\xEF350999CBD5415D9C520E27D4D67DC2DEF25990' |
| 2021-07-27 05:43:24.000000 | 276 | E'\\\\xACAD2A57C2A7FCB6E88854CE4F1D00B371F051F8' |
| 2021-07-27 08:50:48.000000 | 276 | E'\\\\x95853752DE29C350D1F85065617B1077DD0F2ED8' |

The fact that we have commits at all implies the command from gitserver is returning results. The [code](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/insights/compression/worker.go) for the worker just uses a max historical time (default 1 year) and requests commits after it. It's possible we are getting a bad result from gitserver.

It's also not clear why this index was out of date at all. I didn't expect the codeinsights database to be purged and recreated with the k8s rebuild, but if so that could explain how we arrived at this state.

**Comment by felixfbecker** [comment]
@coury-clark do you have an estimate how long this will take you to fix?

**Comment by coury-clark** [comment]
@felixfbecker not really at the moment, I'll have to look into this after the current issues. It isn't clear if this is actually an issue, a manifestation of the database problems on k8s, or some upstream change in gitserver that has changed behavior.

**Comment by coury-clark** [comment]
After k8s was refreshed many repository IDs were conflicting with old data in the codeinsights DB. Rather than waste time debugging stale data, I truncated the commit index and will let it completely refresh to see if we are still experiencing a problem.

**Comment by coury-clark** [comment]
`select count(*) from commit_index where repo_id = 276;`
3486

That seems much more appropriate after refreshing.

**Comment by coury-clark** [comment]
This issue seems to have been caused by the corruption of the primary k8s database, causing a desync between the repository ids of the freshly generated postgres and the codeinsights database.
