### ISSUE TITLE
Change message on the "live preview" section for backend insights

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#23260]
If using the checkbox to run over all repos, the live preview shows the default "Chart preview will be shown here once you filled out the fields..." message, but that's wrong, since we don't yet have "live preview" for all repos. 

We should instead make this message say "Previews are not currently available for insights over all repos. Previews are only available if you list individual repos, up to 50 repos." 
![image](https://user-images.githubusercontent.com/11967660/127113269-83a639d9-4267-42f9-b3d3-1d54dd94b921.png)

**Comment by Joelkw** [comment]
cc @vovakulikov @AlicjaSuska just making this as followup from our mention in the sync on Monday. Open to tweaks of the message if you'd like @AlicjaSuska otherwise please feel free to move it out of "needs design."

**Comment by AlicjaSuska** [comment]
I've tweaked the message a little and separated into the main and secondary message. @Joelkw @vovakulikov wdyt? (full mockup in [Figma](https://www.figma.com/file/wXKTspDmgTrPPumahHQTXQ/Caution-suggest-to-keep-insights-500-repos-23655?node-id=1%3A2352))?

<img width="563" alt="Screenshot 2021-08-10 at 15 57 43" src="https://user-images.githubusercontent.com/20326070/128880145-6a344c1c-c85b-487e-9d8b-7ac0aab3a0ba.png">
