### ISSUE TITLE
Diff results not matched

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#23277]
Here are results for this query:

[`repo:^github\.com/sourcegraph/about after:"June 1 2021" type:diff file:^handbook/engineering/developer-insights/extensibility/index\.md`](https://k8s.sgdev.org/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/about+after:%22June+1+2021%22+type:diff+file:%5Ehandbook/engineering/developer-insights/extensibility/index%5C.md&patternType=literal)

![Screen Shot 2021-07-27 at 1 46 42 PM](https://user-images.githubusercontent.com/888624/127225081-76fea574-f4dd-45a9-ba05-9a88e753910d.png)

Note that the 3rd block partially renders the diff. The fully rendered diff contains text for word `Joelkw`. If we search for those that in the query, there are no results:

[`repo:^github\.com/sourcegraph/about after:"June 1 2021" type:diff file:^handbook/engineering/developer-insights/extensibility/index\.md Joelkw`](https://k8s.sgdev.org/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/about+after:%22June+1+2021%22+type:diff+file:%5Ehandbook/engineering/developer-insights/extensibility/index%5C.md+Joelkw&patternType=literal)

But if we search for `visual` we do get results

[`repo:^github\.com/sourcegraph/about after:"June 1 2021" type:diff file:^handbook/engineering/developer-insights/extensibility/index\.md visual`](https://k8s.sgdev.org/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/about+after:%22June+1+2021%22+type:diff+file:%5Ehandbook/engineering/developer-insights/extensibility/index%5C.md+visual&patternType=literal)

After playing around with this, it seems that we simply just don't match past a particular point `sure to request`, and the rest of the content is cut for some mysterious reason.

E.g., this query works:

[`repo:^github\.com/sourcegraph/about after:"June 1 2021" type:diff file:^handbook/engineering/developer-insights/extensibility/index\.md to request`](https://k8s.sgdev.org/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/about+after:%22June+1+2021%22+type:diff+file:%5Ehandbook/engineering/developer-insights/extensibility/index%5C.md+to+request&patternType=literal)

But then searching for `the PR` which comes right after this text, on this very same line, returns no results:

[`repo:^github\.com/sourcegraph/about after:"June 1 2021" type:diff file:^handbook/engineering/developer-insights/extensibility/index\.md to request the PR`](https://k8s.sgdev.org/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/about+after:%22June+1+2021%22+type:diff+file:%5Ehandbook/engineering/developer-insights/extensibility/index%5C.md+to+request+the+PR&patternType=literal)

 The full diff looks like this:

![Screen Shot 2021-07-27 at 1 50 22 PM](https://user-images.githubusercontent.com/888624/127225448-217a9214-2614-410d-b142-fff1fab49147.png)

**Comment by rvantonder** [comment]
Making a GQL query to the backend reveals that the full result value is cut off in the `html`/`text` portions. 

<img width="1244" alt="Screen Shot 2021-07-27 at 2 01 21 PM" src="https://user-images.githubusercontent.com/888624/127226961-690cd9cd-1196-4cc9-9fee-0d0a1ab38e2e.png">

This is a backend problem.

Reference: [Example GQL query](https://k8s.sgdev.org/api/console#%7B%22operationName%22%3A%22Search%22%2C%22query%22%3A%22%23%20Type%20queries%20here%2C%20with%20completion%2C%20validation%2C%20and%20hovers.%5Cn%23%5Cn%23%20Here's%20an%20example%20query%20to%20get%20you%20started%3A%5Cn%5Cnquery%20Search(%24query%3A%20String!)%20%7B%5Cn%20%20search(query%3A%20%24query)%20%7B%5Cn%20%20%20%20results%20%7B%5Cn%20%20%20%20%20%20__typename%5Cn%20%20%20%20%20%20limitHit%5Cn%20%20%20%20%20%20resultCount%5Cn%20%20%20%20%20%20approximateResultCount%5Cn%20%20%20%20%20%20missing%20%7B%5Cn%20%20%20%20%20%20%20%20name%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20cloning%20%7B%5Cn%20%20%20%20%20%20%20%20name%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20timedout%20%7B%5Cn%20%20%20%20%20%20%20%20name%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20indexUnavailable%5Cn%20%20%20%20%20%20dynamicFilters%20%7B%5Cn%20%20%20%20%20%20%20%20value%5Cn%20%20%20%20%20%20%20%20label%5Cn%20%20%20%20%20%20%20%20count%5Cn%20%20%20%20%20%20%20%20limitHit%5Cn%20%20%20%20%20%20%20%20kind%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20results%20%7B%5Cn%20%20%20%20%20%20%20%20...%20on%20Repository%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20id%5Cn%20%20%20%20%20%20%20%20%20%20name%5Cn%20%20%20%20%20%20%20%20%20%20__typename%5Cn%20%20%20%20%20%20%20%20%20%20label%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20html%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20url%5Cn%20%20%20%20%20%20%20%20%20%20detail%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20html%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20matches%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20url%5Cn%20%20%20%20%20%20%20%20%20%20%20%20body%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20text%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20html%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20highlights%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20line%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20character%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20length%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20...%20on%20FileMatch%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20file%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20path%5Cn%20%20%20%20%20%20%20%20%20%20%20%20url%5Cn%20%20%20%20%20%20%20%20%20%20%20%20commit%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20oid%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20repository%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20id%5Cn%20%20%20%20%20%20%20%20%20%20%20%20name%5Cn%20%20%20%20%20%20%20%20%20%20%20%20url%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20limitHit%5Cn%20%20%20%20%20%20%20%20%20%20symbols%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20name%5Cn%20%20%20%20%20%20%20%20%20%20%20%20containerName%5Cn%20%20%20%20%20%20%20%20%20%20%20%20url%5Cn%20%20%20%20%20%20%20%20%20%20%20%20kind%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20lineMatches%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20preview%5Cn%20%20%20%20%20%20%20%20%20%20%20%20lineNumber%5Cn%20%20%20%20%20%20%20%20%20%20%20%20offsetAndLengths%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20...%20on%20CommitSearchResult%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20__typename%5Cn%20%20%20%20%20%20%20%20%20%20label%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20html%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20url%5Cn%20%20%20%20%20%20%20%20%20%20detail%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20html%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20matches%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20url%5Cn%20%20%20%20%20%20%20%20%20%20%20%20body%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20text%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20html%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20highlights%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20line%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20character%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20length%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20alert%20%7B%5Cn%20%20%20%20%20%20%20%20title%5Cn%20%20%20%20%20%20%20%20description%5Cn%20%20%20%20%20%20%20%20proposedQueries%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20description%5Cn%20%20%20%20%20%20%20%20%20%20query%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20elapsedMilliseconds%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22variables%22%3A%22%7B%20%5C%22query%5C%22%3A%5Cn%20%20%5C%22repo%3A%5Egithub%5C%5C%5C%5C.com%2Fsourcegraph%2Fabout%20after%3A%5C%5C%5C%22June%201%202021%5C%5C%5C%22%20type%3Adiff%20file%3A%5Ehandbook%2Fengineering%2Fdeveloper-insights%2Fextensibility%2Findex%5C%5C%5C%5C.md%20to%20request%5C%22%5Cn%7D%22%7D)

**Comment by rvantonder** [comment]
I tested a commit 80c863a038cd9032e6713b06e1e3f2f7362d0e1d two weeks ago and it has the same issue. Don't know that this is a recent regression or something that's always been a problem.

**Comment by rvantonder** [comment]
Potentially related to this method, but I don't find any uses of it: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@95d4c5be4750edeaca01bd3c87b95f0f3673a3b2/-/blob/internal/search/result/commit.go?L42&subtree=true

**Comment by camdencheek** [comment]
I have a hunch that this has to do with [`maxCharsPerLine`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@e6cc91f2bd49f7a8d261337e75d0a1fe7e744d3f/-/blob/internal/vcs/git/diff_filter.go?L46:3&subtree=true). 

Haven't take the time to validate this, but I stumbled across those (pretty conservative) limits just now, and had no idea they exist, and `189 (offset) + 10 (length)` is suspiciously close to `200 (maxCharsPerLine)`

**Comment by coury-clark** [comment]
Bumping this issue, just ran into this again today trying to find where we made a regression. This bug makes diff search pretty much unusable knowing many results are not showing up in the search.

**Comment by rvantonder** [comment]
added label, think lack of label meant this slipped (cc @benvenker for visibility)

**Comment by benvenker** [comment]
Oh, thanks @rvantonder, I had definitely missed this. @camdencheek does this belong in your epic? Is this urgent enough to pull into this iteration?

**Comment by camdencheek** [comment]
@coury-clark Diffs are formatted using the match ranges. We do this so the diff that the user sees is a pared down version of the diff that is relevant to their search. 

Before my changes roll out, there is also a `maxCharsPerLine` limit for the formatting that would chop off all text after column 200. I think the intent was that we would only show highlights that would be in view without scrolling. However, this sometimes caused us to drop all the highlights in a diff because they all occured after column 200. This would cause the diff to be filtered out because it appeared to contain zero matches after formatting.

Following my changes, there will still be [limits on formatted diff size](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/gitserver/search/diff_format.go?L12-18), but those limits will not ever generate a diff that contains no matches because we choose hunks based on whether they contain matching ranges. So the count of matches will be incorrect, but count of "number of diffs matched" should always be correct.

**Comment by lguychard** [comment]
@camdencheek should this be closed now?

**Comment by camdencheek** [comment]
Yes! This should be fixed now
