### ISSUE TITLE
Query builder should show query in search box

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#2329]
The query builder does currently not show the built query in the search box. This is a missed opportunity for teaching people how to achieve the query with direct search syntax. It is also confusing, because the query builder does not have a Submit button, but the "Search" submit button is implied to submit what is in the search box, not the query builder.

![2019-02-16 11 08 03](https://user-images.githubusercontent.com/10532611/52898202-42cf6e00-31db-11e9-8187-2d416509d72a.gif)

I propose it makes the search box readonly and updates its contents.

**Comment by sqs** [comment]
Let's get more user feedback on the query builder before prioritizing/making this change. There is one other direction (that I consider fairly likely) that would preclude this specific change:

- Making the query builder always visible like https://cs.chromium.org/. Then we could not have this simple behavior of "if query builder is visible, make main search bar readonly"

Adding @francisschmaltz 	for user research on this.

**Comment by felixfbecker** [comment]
Personally I am -1 on that because it makes the UI less clean/tidy.

But I think it would be good idea to remember the open state in localStorage for people who always prefer the query builder

**Comment by francisschmaltz** [comment]
I agree with Felix that it shouldn't be always visible. The 1 way binding we previous discussed would be the right thing to do here.

**Comment by attfarhan** [comment]
Query builder is feature flagged off by default and will be removed, so closing.
