### ISSUE TITLE
Support GSSAPI auth between frontend services and external DB

### ISSUE THREAD

**Issue by christinelovett** [sourcegraph/sourcegraph#23300]
#### Feature request description

Support GSSAPI/Kerberos authentication to external DBs from the frontend service. 

[Customer](https://app.hubspot.com/contacts/2762526/company/578600789) is hitting PGaaS startup failure due to environmental restrictions around authentication:

`ERROR: failed to connect to frontend database: DB not available: database did not start up within 10s (failed to connect to `host=<redacted> user=<redacted> database=sg`: failed to receive message (unknown authentication type: 7))`

#### Additional context

[Related customer issue](https://github.com/sourcegraph/customer/issues/403)

**Comment by christinelovett** [comment]
I'm not sure if it's still blocking, @alexfogg has taken over as CE for customer (OOO returning tomorrow)

**Comment by dan-mckean** [comment]
Will track this via the product gap.
