### ISSUE TITLE
Gradient shadow on query builder looks out of place

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#2330]
![image](https://user-images.githubusercontent.com/10532611/52898220-8f1aae00-31db-11e9-9ba8-bf01c546c1e2.png)

We don't use gradients anywhere else in our app and it feels out of place with our flat/minimal design.

**Comment by attfarhan** [comment]
Assigning to @francisschmaltz since this was in the designs. Should be easy enough for you to remove @francisschmaltz.

**Comment by francisschmaltz** [comment]
@felixfbecker the design for the query builder was *too* flat without something to break it up. It also isn't a gradient but a single colored shadow. Closing for now but we can continue this offline if you'd like.

**Comment by sqs** [comment]
Felix, Farhan, and I all had negative reactions to the gradients, and we are squarely in the target demographic, so what can you do to address our concerns? Also, Felix is in Germany, so taking it offline won’t work too well. :)
