### ISSUE TITLE
OOB migrations use an unadorned background context

### ISSUE THREAD

**Issue by LawnGnome** [sourcegraph/sourcegraph#23340]
OOB migrations are currently implemented to use a [straight up `context.Background()`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@10921291b3d50ecd450d94d285f3d2e8fccebb3c/-/blob/internal/oobmigration/runner.go?L46:36) as their base context when running migrations. As we add more authz checks to lower levels of our codebase, this is likely to cause issues where background processes that we expect to have access to things do not.

I suggest that we add the appropriate bypass and/or internal actor, just as soon as we figure out what the right thing to do is.

cc: @efritz in case you have input, although I'm happy for us to own this for now.

**Comment by efritz** [comment]
I think it's proper to put the authz bypass on that context as migrations are meant to be infra-level tasks. Of course, feel free to own this 😄!

**Comment by LawnGnome** [comment]
Done in #23392.
