### ISSUE TITLE
"Formatted" toggle entirely broken on all Markdown files in Firefox and Chrome

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#23342]
1. Go to a markdown file.
2. Click "Show formatted" button - nothing happens.

<img width="425" alt="image" src="https://user-images.githubusercontent.com/3173176/127420784-52f910a0-c27a-465f-a7c5-db4e4e539e88.png">

https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/database/schema.codeintel.md?L14=

Tested in Firefox and Chrome

**Comment by novoselrok** [comment]
That seems to be the expected behaviour if a line number is present: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/repo/blob/BlobPage.tsx?L228:79
