### ISSUE TITLE
A block when yarn build fresh packages

### ISSUE THREAD

**Issue by KashingLiu** [sourcegraph/sourcegraph#23346]
- **Sourcegraph version:**   Version: 0.0.0+dev
- **Platform information:** 
- 5.11.0-16-generic 17-Ubuntu SMP Wed Apr 14 20:12:43 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Docker version 20.10.2, build 20.10.2-0ubuntu2

#### Steps to reproduce:

1. git clone https://github.com/sourcegraph/sourcegraph.git
2. cd sourcegraph
3. ./dev/start.sh

#### Expected behavior:

I think there should not be a block or stop at running yarn build

#### Actual behavior:
After I run the shell scripts, the yarn report that there is some warning like `warning "react-spring > @react-spring/zdog@9.0.0" has unmet peer dependency "react-zdog@>=1.0".` , then there is a block and the program stop at `yarn | [5/5] Building fresh packages...`. I tried to terminate the program by enter `Ctrl + C`. But the program run as normal. I found `✱ Sourcegraph is ready at: http://localhost:3080/` and the program stop at `web | webpack compiled successfully in 8009 ms`. I can visit the sourcegraph website

**Comment by daxmc99** [comment]
`sg` tooling should be used for this now
