### ISSUE TITLE
Error occurred while proxying request. [ECONNRESET]

### ISSUE THREAD

**Issue by KashingLiu** [sourcegraph/sourcegraph#23347]
- **Sourcegraph version:** Version: 0.0.0+dev
- **Platform information:** 
- 5.11.0-16-generic 17-Ubuntu SMP Wed Apr 14 20:12:43 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Docker version 20.10.2, build 20.10.2-0ubuntu2

#### Steps to reproduce:

1. set 127.0.0.1 soucegraph.test in /etc/hosts
2. cd sourcegraph && ./dev/start.sh
3. visit extension page on sourcegraph site

#### Expected behavior:

There is serveral extensions which I can choose to enable or not

#### Actual behavior:

When I visit `http://localhost:3080/extensions?category=All`, it shows `No extension registry is available (use Sourcegraph Free or Sourcegraph Enterprise to access the Sourcegraph extension registry and/or to host a private internal extension registry)`, and I found the log on my terminal. It seems that the proxy has something went wrong. If I build the sourcegraph by the source code, can I access extension registry which is public? The problem is caused by wrong proxy or is caused by building the website by myself?

`web | <e> [webpack-dev-server] [HPM] Error occurred while proxying request 192.168.176.227:3080/.api/graphql?RegistryExtensions to http://localhost:3081/ [ECONNRESET] `

`web | <e> [webpack-dev-server] [HPM] Error occurred while proxying request 192.168.176.227:3080/.api/graphql?CheckMirrorRepositoryConnection to http://localhost:3081/ [ECONNRESET] `

**Comment by muratsu** [comment]
Hey @KashingLiu, 👋. As mentioned in the error message the extension registry is available only for Sourcegraph Free (via www.sourcegraph.com) and Sourcegraph Enterprise.
