### ISSUE TITLE
For methods that start with $ (dollar sign), only the $ is highlighted on hover

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#2341]
![image](https://user-images.githubusercontent.com/10532611/52971591-52f07480-33b8-11e9-8b33-7e4f8921df4a.png)

https://sourcegraph.com/github.com/sourcegraph/sourcegraph@0f7c5b69f332ff81d6895343005cddb4a0862048/-/blob/shared/src/api/extension/api/search.ts#L20

**Comment by scalabilitysolved** [comment]
![image](https://user-images.githubusercontent.com/1309599/110462883-8b636800-80d1-11eb-830d-cd16b30fe3ec.png)

@felixfbecker this looks resolved to me now, is this working as you'd expect?

cc/ @macraig

**Comment by felixfbecker** [comment]
Yeah that looks much better. Ideally the `$` would be included but that is lower priority

**Comment by macraig** [comment]
Closing for now, will reopen if prioritized
