### ISSUE TITLE
Option the use of simple=true when querying GitLab API

### ISSUE THREAD

**Issue by chrislovett03** [sourcegraph/sourcegraph#23424]
#### Feature request description

A customer is hitting 500s from the `https://gitlab.example.com/api/v4/projects?membership=false&per_page=100
` repo list query, which they believe is due to their GitLab server being overloaded. They are working with GitLab on this, but believe Sourcegraph can also help.

This API also takes a `simple=true` parameter, which retrieves much less data.  Unfortunately, `simple=true` loses the visibility field, which Sourcegraph reads.  But they are OK assuming that all of their repos that Sourcegraph is allowed to see are public.  

Proposed solution:
Include the option to add  `?simple=true` when querying GitLab instance's for lists of repositories, and assume all repos are public 

#### Additional context

[Customer](https://github.com/sourcegraph/accounts/issues/8205)

**Comment by dan-mckean** [comment]
Hey @christinelovett 
Has any progress been made working with Gitlab?
>A customer is hitting 500s from the https://gitlab.example.com/api/v4/projects?membership=false&per_page=100 repo list query, which they believe is due to their GitLab server being overloaded. They are working with GitLab on this, but believe Sourcegraph can also help.

Just trying to assess the priority of this :)

**Comment by christinelovett** [comment]
cc @alexfogg who has taken over as CE for the customer; slacking for context
