### ISSUE TITLE
Error when searching across Sourcegraph-org repos on Sourcegraph.com

### ISSUE THREAD

**Issue by francisschmaltz** [sourcegraph/sourcegraph#2342]
When searching across all sourcegraph org repos (example https://sourcegraph.com/search?q=repo:github.com/sourcegraph+%22data+center%22 ) I get the error

```
1 error occurred: * text search failed: failed to search github.com/sourcegraph/sourcegraph-erlang@: failed to fetch missing archive cache item: Post http://gitserver-0.gitserver:3178/exec: dial tcp: lookup gitserver-0.gitserver on 10.55.240.10:53: no such host

**Comment by attfarhan** [comment]
I tried this search too, and it shows a different repo in the error message each time. Each of the repos mentioned show a 500 error when trying to go directly to the repo. E.g. https://sourcegraph.com/github.com/sourcegraph/sourcegraph-erlang. 

Other repos: 
https://sourcegraph.com/github.com/sourcegraph/node-idast
https://sourcegraph.com/github.com/sourcegraph/surf

**Comment by sqs** [comment]
This is caused (I believe) by old repos that have been deleted on the code host still existing on Sourcegraph. It will be fixed by #2025 and #914, planned for 3.2. 

The reason the error differs each time is that it shows the first errors to be received, which is dependent on the speed of various distributed operations.

**Comment by attfarhan** [comment]
Interestingly those 3 repos I linked above no longer return 500s.

**Comment by sqs** [comment]
@francisschmaltz 	When you performed that search, did you see any results or just an error? I am not seeing the error when I try to repro it (but it does indicate that some repos were not found).

**Comment by tsenart** [comment]
> This is caused (I believe) by old repos that have been deleted on the code host still existing on Sourcegraph. It will be fixed by #2025 and #914, planned for 3.2.

@sqs: What led you to this conclusion? The error that @francisschmaltz reported looks like the cluster's DNS server is down: `dial tcp: lookup gitserver-0.gitserver on 10.55.240.10:53: no such host`

**Comment by sqs** [comment]
I didn’t read the whole error message apparently. You are right.

**Comment by keegancsmith** [comment]
This sounds like a transient issue that happened in our cluster. I am closing.
