### ISSUE TITLE
google-api-go-client only has top-level package API docs

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#23434]
The repo at https://sourcegraph.com/github.com/googleapis/google-api-go-client/-/docs only has API docs for the root package, not for the many subpackages:

![image](https://user-images.githubusercontent.com/1976/127732189-60c78c5a-e053-4e89-9c5c-afb1f6d388b0.png)

Clicking `...` does not do anything.

**Comment by slimsag** [comment]
Fixed
