### ISSUE TITLE
Add document for backup and restore on Kubernetes

### ISSUE THREAD

**Issue by northyg** [sourcegraph/sourcegraph#23468]
#### Describe the issue
 
[We have documents for backup and restore on docker compose.](https://docs.sourcegraph.com/admin/install/docker-compose/operations#back-up-sourcegraph-databases) We need such a doc for Kubernetes.

#### Suggested resolution

@abeatrix and myself will work on the doc using internal notes as reference. Then submit for review to Distribution.

**Comment by abeatrix** [comment]
Link to draft: https://docs.google.com/document/d/1ks9DHQ03W0vwbri1UIGbgu9O_nkG840ck5SZiZ9MLDA/edit
