### ISSUE TITLE
Zoekt / Indexed search not honoring regex range quantifier

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#23467]
A query like:

- [`(foo){2,}`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+%28foo%29%7B2%2C%7D+&patternType=regexp) returns results where `foo` is only matched once, which seems wrong. The range quantifier means it should only be a result of `foo` is matched consecutively. [Example on regexr](https://regexr.com/630pd)

- This problem does not exist with `index:no`, so it is Zoekt-specific.

- RE2 syntax does say it supports range quantifiers, and a query like [`(aa){2,}`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+%28aa%29%7B2%2C%7D+&patternType=regexp) does appear to do the right thing. Note that the RE2 behavior is "prefer longer", so, my guess is that this `(aa){2,}` only works because there are legitimate matches and we see those first. In the first pattern, `foofoo` doesn't exist, and I think we for some reason return results that don't honor the range quantifier.

Context:

https://sourcegraph.slack.com/archives/C022SPMNR0W/p1627930318021600

**Comment by rvantonder** [comment]
Labeling as bug until I learn otherwise.

**Comment by rmmh** [comment]
This is a zoekt bug. regexpToMatchTreeRecursive converts the input `(foo){2,}` into a simpler search of `substr("foo", [], wrapper(not("freq=0")))`, dropping the repeat count modifier and bypassing regex evaluation altogether.

**Comment by rvantonder** [comment]
this is fixed
