### ISSUE TITLE
Include Sourcegraph extension usage status in pings

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#2348]
Related: https://github.com/sourcegraph/sourcegraph/issues/2024

Include aggregate metrics on which Sourcegraph extensions are in use (with anonymized counts of users) in [server pings](https://docs.sourcegraph.com/admin/pings).

**Comment by vanesa** [comment]
Active extensions on Sourcegraph.com are now included in the pings: https://github.com/sourcegraph/sourcegraph/pull/5177

**Comment by dadlerj** [comment]
Actually, important terminology note @vanesa — they are logged on Sourcegraph.com, but NOT included in pings (which come from self-hosted instances). So this issue can remain open for now.
