### ISSUE TITLE
3.1 release notifications

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#2349]
## ToDo

- [x] Blog post - https://about.sourcegraph.com/blog/sourcegraph-3.1
- [x] Tweet - https://twitter.com/srcgraph/status/1098325294480470017
- [x] Email

**Comment by ryan-blunden** [comment]
- [ ] Blog post
- [ ] Tweet
- [ ] Email

**Comment by ryan-blunden** [comment]
@nicksnyder What previous versions can be upgraded to 3.1?

**Comment by nicksnyder** [comment]
3.1 is no different than 3.0.1 with respect to upgrades

**Comment by sqs** [comment]
Tweet:

<blockquote>

Sourcegraph 3.1 is out! OSS/self-hosted code search/nav tool, now with:

🔍 Query builder (search code like a pro)
🌐 Better definitions & hovers for all langs
⚙️ For admins: easier config, new user auth options/APIs
⌚ Now releasing monthly on the 20th

https://about.sourcegraph.com/blog/sourcegraph-3.1

</blockquote>
