### ISSUE TITLE
Popover doesn't goes away

### ISSUE THREAD

**Issue by victorjavierss** [sourcegraph/sourcegraph#235]
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:**  
Google Chrome  69.0.3497.100
Mac OS High Sierra 10.13.6 (17G65)

#### Steps to reproduce:
1. Open a source file in github.com
2. Select a code that is at the bottom
3. Exit the popup near the top left corner

#### Expected behavior:
Popover should disappear 

#### Actual behavior:
Popover stays open trough navigation in GitHub

[video](https://drive.google.com/open?id=1d6D8xBhHzJE8sQEwYPcDdktMXJl4MWCe)

**Comment by felixfbecker** [comment]
This issue was moved to sourcegraph/browser-extensions#226
