### ISSUE TITLE
Removing user from Github organization does not remove repositories from list

### ISSUE THREAD

**Issue by neekolas** [sourcegraph/sourcegraph#2351]
- **Sourcegraph version:*3.0.1*
- **Platform information:*Mac OS 10.14.3*

#### Steps to reproduce:

1. Add Github Repository from an organization user is a member of
2. Remove user from organization
3. View list of repositories (http://127.0.0.1:7080/site-admin/repositories)

#### Expected behavior:
Repositories from organization should disappear from list after user has been removed from the organization.

#### Actual behavior:
Repositories from organization are still present in list, but cloning will always fail and errors will be logged on startup.

**Comment by sqs** [comment]
This is a high priority issue currently being worked on for Sourcegraph 3.2 (release on March 20) in #2025 and #914.

In the meantime, you need to (unfortunately, manually) delete repositories from Sourcegraph as a site admin when you no longer want them to be on Sourcegraph. You can do this on the Site admin > Repositories page.

**Comment by sqs** [comment]
Closing as duplicate of #2025 and #914

**Comment by neekolas** [comment]
Thanks
