### ISSUE TITLE
JVM Dependencies: disable cloud_default, use background syncing instead of lazy syncing 

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#23543]
- **Sourcegraph version:** 🚀 528adc31c7 (63 minutes ago, Felipe Janer): welcome-feature: add backend integration logic (#23319)
- **Platform information:** Firefox

#### Steps to reproduce:

1. Visit a non-existing JVM dependencies repo URL like https://sourcegraph.com/maven/com.sourcegraph/semanticdb-javac

#### Expected behavior:

The page returns a 404 because the dependency is not configured in the external service type.

#### Actual behavior:

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/1408093/128139596-933c1606-deb6-4712-80f7-f7d7d98b6e2f.png">

## Steps to resolve the problem

We should remove the code paths that support lazy syncing.

**Comment by olafurpg** [comment]
I'm no longer able to reproduce this error after removing and adding the same dependency again. However, I can reproduce it by visiting a non-existing package repo like https://sourcegraph.com/maven/org.scala-lang

**Comment by olafurpg** [comment]
@tsenart can you confirm that it's sufficient to disable `cloud_default` for the JVM external service type if we want to turn off lazy syncing? Besides removing the line [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@ca109dbe34ffc3661b1caceb8d96c9c5f1df539f/-/blob/internal/extsvc/codehost.go?L30), what other changes should we make to entirely get rid of lazy syncing?

**Comment by Strum355** [comment]
Combing through the changes (really like the direction its going, good stuff @tsenart :tada:) we should be fine with toggling `cloud_default` :+1:
