### ISSUE TITLE
How can I configure the search result display limit

### ISSUE THREAD

**Issue by KashingLiu** [sourcegraph/sourcegraph#23541]
#### Question description

I found that when I search something and there is more than 500 results, the result page tells me `We only display 500 results even if your search returned more results. To see all results and configure the display limit, use our CLI.`  But I don't know how to configure the display limit more than 500 in the site configuration. I don't want to search something in the CLI, I just want to search something in the webapp.

**Comment by KashingLiu** [comment]
#19714
@stefanhengl 
Hello, I want to display all result sets. Is there a configuration which I can set display limits? Or will you add a previous and next buttons or something like this to show all results?

**Comment by keegancsmith** [comment]
We are increasing the default limit. 500 was too conservative. We can consider a user setting for display limit, for now it is hardcoded. cc @stefanhengl @lguychard 

However, if you want to see all results I recommend using `src-cli` to do the search. Sourcegraph is not a traditional IR system, we make different trade-offs which make knowing how many pages have results not possible without wasting computation. Pagination is possible, but very tricky to get right. Instead we rely on a streaming system.

**Comment by keegancsmith** [comment]
The rationale between display vs match limits is display limits are for avoiding sending large amounts of data the the browser that we don't expect a human to parse. The counts and statistics you see will still be acurrate with respect match limits. IE have you tried `count:all`.

**Comment by KashingLiu** [comment]
Will you increase the default limit soon? Can I know how long does it take to add this function (or setting)? Or in which version this feature can release. And can I set the display limit to `all`  rather than a exact number after I can set it?

**Comment by keegancsmith** [comment]
It is increased and available on sourcegraph.com and in the next release for other installations. I haven't added the ability to override it. PRs welcome, see https://github.com/sourcegraph/sourcegraph/pull/23545 for where the hardcoding is.

**Comment by KashingLiu** [comment]
@keegancsmith  Thanks a lot again. After modifying my code, is there a way to build a docker image and use ` docker run my-own-image ` to start a server rather than execute `./dev/start.sh` ? It seems that I need a Dockerfile, is it in ` cmd/server/build.sh ` or somewhere?

**Comment by KashingLiu** [comment]
@keegancsmith Hello, I update the version to 3.30.4, but it still has a 500 display limit.
![image](https://user-images.githubusercontent.com/22939122/129825491-7621ff4d-d58c-4b2f-b76e-cbd9a6c0cbc2.png)
![image](https://user-images.githubusercontent.com/22939122/129825527-9c2af507-db58-46e2-b261-65061b1f4dd9.png)
How can I set the limit exactly? Did you mean it will appear in 3.31 or later release?

**Comment by keegancsmith** [comment]
3.31 will have it. We continuously update the `sourcegraph/server:latest` docker image with what is in main. Building your own docker image is not that straightforward, we offload it to CI so I'd recommend using that.

**Comment by keegancsmith** [comment]
@michaelkebe can you document your use case here with examples of why you often need more than 1500? What limit would you like to use in your browser?

**Comment by michaelkebe** [comment]
We have a large C/C++ codebase with many custom datastructures named with three characters like `abc`. The fields of the datastructure are named like `abc123`.
So to access a specific field of a datastructure, you have write this: `abc.abc123` or `abc->abc123`

If you want to search for the usage of a specific datastructure (e.g. `abc`), you will have many hits. A datastructure has about 200-300 fields (`abc001`, `abc011`, `abc216`, ...).

The UI says:
![image](https://user-images.githubusercontent.com/74952/170233648-b14a903e-6d45-4f80-ba9a-607e19b76219.png)

I can open the "Some results excluded" menu and increase the `count` limit:
![image](https://user-images.githubusercontent.com/74952/170234087-4c94ba79-d745-46fc-b8b7-51236745dad5.png)

But then I see the `display limit hit` notice:
![image](https://user-images.githubusercontent.com/74952/170234861-a4afe833-3297-4b14-be0d-fb50587fbc3d.png)

If understand correctly I should either configure the display limit (which is not possible right now, because it is hardcoded) or I should use the CLI.

I think we are happy with a limit like 10000. But it really should be configurable. A bonus would be to be configurable for each user.

**Comment by keegancsmith** [comment]
that copy is indeed wrong, it isn't possible to configure via the web ui.

Are you visually looking at all 1500 results? This seems like a lot of things for a human to be looking at.

**Comment by michaelkebe** [comment]
At least scrolling through them.

**Comment by stefanhengl** [comment]
> If understand correctly I should either configure the display limit (which is not possible right now, because it is hardcoded) or I should use the CLI.

No, you cannot configure the display limit in the UI. However you can configure the display limit in src-cli. To run an exhaustive search over all repositories without limits, you have to use the src-cli there is currently no other way.

**Comment by michaelkebe** [comment]
Okay, the sentence confused me. After reading it a few times I understand it.

Anyway, a configuration of the display limit would be awesome. I know that there might be performance or stability issues, but for a local installation it should configurable.

**Comment by stefanhengl** [comment]
> Anyway, a configuration of the display limit would be awesome. I know that there might be performance or stability issues, but for a local installation it should configurable.
> 
> Using the cli is not very intuitive and using sourcegraph as an easy accessible web app should help exactly with these kind of problems.

Yes, that is a fair point. I will bring it up with my team to see how soon we can implement it.

**Comment by stefanhengl** [comment]
I will close this ticket as it just about the "how" right now. I have opened a new ticket to keep track of the proposed change.

https://github.com/sourcegraph/sourcegraph/issues/36691
