### ISSUE TITLE
Support service mesh for Sourcegraph on K8s

### ISSUE THREAD

**Issue by christinelovett** [sourcegraph/sourcegraph#23560]
#### Feature request description

Provide a service mesh integration in order to meet the following requirements:

- Data encryption in transit between pods 
- Authz/Authn between pods 
- Introduce network controls between Sourcegraph services
- Limit/block API calls to administrator only 

#### Is your feature request related to a problem? If so, please describe.

Highly regulated customers have security requirements on interservice connectivity that are best addressed by a service mesh like Istio. In order to meet these requirements, providing a tested and stable service mesh would ensure we can meet these reqs efficiently and reliably. 

#### Additional context

This was prompted by the tech risk eval completed by [customer](https://docs.google.com/spreadsheets/d/1OEhzdMSlkGOaWyGKwdiAGlirsKKj9EN45Izn7kdKNTg/edit#gid=0&range=A17)

Other customers who would benefit:  

- https://docs.google.com/spreadsheets/d/1OEhzdMSlkGOaWyGKwdiAGlirsKKj9EN45Izn7kdKNTg/edit#gid=0&range=A4615
- https://docs.google.com/spreadsheets/d/1OEhzdMSlkGOaWyGKwdiAGlirsKKj9EN45Izn7kdKNTg/edit#gid=0&range=A1008
- https://docs.google.com/spreadsheets/d/1OEhzdMSlkGOaWyGKwdiAGlirsKKj9EN45Izn7kdKNTg/edit#gid=0&range=A104

**Comment by daxmc99** [comment]
I have run Sourcegraph with Linkerd in the past. I would expect this to work but more testing would be needed to use it with a customer.
