### ISSUE TITLE
Cannot update configuration files when related jobs are running

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#23585]
- **Sourcegraph version:** 3.29.1
- **Platform information:** Docker Compose (but should be reproducible on other platforms) 

Users have reported a reproducible issue where configuration files cannot be updated when there are related jobs running in the background.

#### Steps to reproduce:

1. Add 20k repos with a code host configuration
2. Make changes to the code host configuration/site admin configuration file

#### Expected behavior:
Warnings about configuration files are being used so no updates can be made to the files.

#### Actual behavior:
Users can make changes to the configuration files in UI with no warning when saving the files, but the files will be reverted to the initial state.

**Comment by ryanslade** [comment]
@abeatrix Were you able to reproduce this in a local environment? What jobs are you referring to?

AFAICT from the code when we save code host configuration we do some simple validation and then save it immediately here:
https://github.com/sourcegraph/sourcegraph/blob/a1075bf6b8604c2b671d36e9e00224e13148232b/cmd/frontend/graphqlbackend/external_services.go#L145

We do kick off an external service sync a few lines later, but with a short timeout of 5 seconds and even if that does fail we'd still have saved the config:
https://github.com/sourcegraph/sourcegraph/blob/a1075bf6b8604c2b671d36e9e00224e13148232b/cmd/frontend/graphqlbackend/external_services.go#L156

**Comment by abeatrix** [comment]
@benjaminwgordon is this still an issue for the customer?

**Comment by benjaminwgordon** [comment]
It is, but they don't currently have an instance running.

They are in a period between ending their trial and generating a production instance.  When they start up the production instance I suspect this will continue to be a problem.

**Comment by eseliger** [comment]
we stop running jobs now when changing config - so this should be fixed.
