### ISSUE TITLE
Adopt shared LSP client library for extensions

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#2359]
We currently have a lot of duplicate code in codeintel extensions. A shared library should make it just a few lines of code to wire up a WebSocket language server to the Sourcegraph API.

## Features:

- Registering providers based on server capabilities
- Converting LSP types <-> Sourcegraph types
- Multi-root workspace translation to multi-connection with rootUri for language servers that don’t support it
- Reconnection logic when connection gets lost
- OpenTracing support (starting on client)

Repo: https://github.com/sourcegraph/lsp-client

**Comment by mpickering** [comment]
What's the status of this? Is the `lsp-client` library finished and usable?

**Comment by felixfbecker** [comment]
Hi @mpickering, lsp-client is ready to be used. If you have any questions or meet any problems let me know! https://github.com/sourcegraph/lsp-client

**Comment by lguychard** [comment]
lsp-client is now inlined in code-intel extensions.
