### ISSUE TITLE
RFC: Create a `BatchChange` with an empty batch spec, before being applied

### ISSUE THREAD

**Issue by courier-new** [sourcegraph/sourcegraph#23599]
[RFC 505 REVIEW: Batch Changes “empty” batch change model](https://docs.google.com/document/d/1In0aivqY0CJA4FFvnnp47R8RaWDWKQkUYa9LlvR83FE/edit#)
---

**The result of this issue is an RFC and a decision about what we should do.** The implementation of that RFC is captured as SSBC EM2.4 #26796.

To reduce confusion around what gets created when you run a batch spec, reduce complexity when it comes to surfacing pending executions or previews in the UI, and move a step closer to collapsing the batch change model for users, we propose creating a batch change from the earliest moment we are able to do so and use this as the primary "thing" for users to interact with.

Currently the flow is

execute -> preview -> apply -> batch change

With this change, we are suggesting the new flow of

execute -> **"shallow" batch change** -> preview -> apply -> batch change

The "shallow" batch change will just be a normal batch change with a shallow/empty spec file (empty except for the `name`). Applying the batch change then becomes closely analogous to how updating one currently works. This change will not have any affect on the DB column constraints for `batch_changes`, nor will it change how the life cycle of batch specs work.

Using this shallow model will enable us to reduce complexity and top-level entities in the UI and enable permanent views that the user can easily get back to for pending/errored executions and preview (unapplied) batch specs.

As Erik points out in the comment below, a concern that will need to be addressed around this time is hiding sensitive "shallow" batch changes like security fixes.

**Comment by eseliger** [comment]
> Allow creating a BatchChange DB entry without a batch spec, before being applied

This is a change for SSBC and we still don't know exactly where the journey is headed, so I'd rather not change the whole database model for now. We should instead:
- On submit parse the batch spec input, extract name and description field, run `createBatchSpec` and `createBatchChange` to create it with an _empty spec_, and go from there. To make it easier to understand, in the update UI I think we should disallow changing the `name` field on the batch spec input, so the target is always clear :) (But that part doesn't need to happen today!! Just a thought I had I want to write down somewhere)

> This will enable us to have a single list things produced from batch changes and collapse the name to just "batch changes" in the UI, no matter what state it's formally in on the server.

We need to make sure that adding them to the list does not expose anything sensitive. We currently run by the principle that batch specs are "private unless you share them explicitly via a link". For that reason, the IDs of those are also not guessable.

**Comment by chrispine** [comment]
For this sprint, let's figure out what the scope of this work should be and how it ties into EM3
