### ISSUE TITLE
insights: insights graphql resolvers lack instrumentation

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#23590]
The insights graphql [resolvers](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/enterprise/internal/insights/resolvers/resolver.go?utm_product_name=GoLand&utm_product_version=GoLand#L41:24) do not have instrumentation. At a minimum, we should drill traces through to the store calls and instrument each store call.

**Comment by coury-clark** [comment]
It is possible to get a trace that hits all of the SQL interactions by adding `?trace=1` to the API console request that executes the GraphQL query for fetching an insight. It will [generate something like this](https://sourcegraph.grafana.net/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22grafanacloud-sourcegraph-traces%22,%7B%22query%22:%22304f99b1aed5696b%22,%22queryType%22:%22traceId%22%7D%5D)

The goal of this ticket is to add context to the traces for each of the `store` operations

**Comment by leonore** [comment]
closing as this is no longer correct
