### ISSUE TITLE
Code intelligence status indicator is inaccurate

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#236]
- **Sourcegraph version:** sourcegraph/server:insiders
- **Platform information:** MacOS
#### Steps to reproduce:

1. Spin up a fresh Sourcegraph instance and add a Go repository.
2. View a Go file in the repository. Notice that the status indicator on the top right is green and hovering over it says "Connected to the Go language server". However, code intelligence won't work.
3. Go to extensions, and add the Go extension. Only now does code intelligence work.

#### Expected behavior:

Either the status indicator is red and tells the user that they need to enable to the Go extension, or the Go extension is automatically added upon viewing a Go file. Basically, the indicator should accurately reflect the status of code intelligence on the file.

#### Actual behavior:

The status indicator is green regardless of whether code intelligence is enabled or not.

**Comment by chrismwendt** [comment]
@sqs Do you plan to tackle this one? If not, I'll probably hop on this soon with @attfarhan

**Comment by sqs** [comment]
Go for it

**Comment by chrismwendt** [comment]
PR created https://github.com/sourcegraph/sourcegraph/pull/358
