### ISSUE TITLE
site24x7 flapping on alerts

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#2361]
@tsenart and I investigated an opsgenie alert from site24x7. There was no restarts in sourcegraph-frontend or ingress-nginx, so we went to the site24x7 console to see what information it had.

It presented this screenshot: 
![image](https://user-images.githubusercontent.com/187831/53018169-53414c00-345a-11e9-8576-f8e64237cddb.png)

With this log
<img width="1098" alt="image" src="https://user-images.githubusercontent.com/187831/53018194-648a5880-345a-11e9-9e57-ba686769cab5.png">

This seems to indicate that it got a 500 response without even resolving an IP. This leads us to believe this may be an infrastructure problem with site24x7. Further investigation is required. I would suggest implementing some of our checks in pingdom or a competitor and comparing the reports.

Assigning @nicksnyder to triage.

**Comment by nicksnyder** [comment]
> I would suggest implementing some of our checks in pingdom or a competitor and comparing the reports.

Acknowledged and I agree.

**Comment by nicksnyder** [comment]
I am assigning this to @beyang to triage and plan (as part of the distribution team).

Another option is https://apex.sh/ping/

Apparently we migrated away from pingdom to site 24x7 at some point in the past (this decision predates me).

**Comment by nicksnyder** [comment]
It would be ideal if our e2e alerts automatically updated a status page like https://www.statuspage.io/

**Comment by tsenart** [comment]
> It would be ideal if our e2e alerts automatically updated a status page like https://www.statuspage.io/

Good idea!
