### ISSUE TITLE
Can I search within all branches?

### ISSUE THREAD

**Issue by techman84** [sourcegraph/sourcegraph#2362]
#### Question description

I'm testing Sourcegraph attached to my GitLab account. When I perform a search, it seems to look only in master branches, not in all repository branches. Is it a normal behavior?
Is there an option to search in all repositories and branches?
Thank you.

**Comment by slimsag** [comment]
Hi @techman84 !

By default, Sourcegraph searches over the default branches (e.g. `master`) in repositories. If you have a specific branch you wish to search over, you can specify it like by adding `@mybranch` to the end of your `repo:` filter (example: [`repo:^github\.com/gopherjs/vecty$@old error`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/gopherjs/vecty%24%40old+error)). This is currently limited to a single branch at a time.

It sounds like you may want to use `type:diff` search, though, which _does_ allow you to search over all/multiple branches for matching diffs (see `repo:regexp-pattern@refs` in the [query syntax docs](https://docs.sourcegraph.com/user/search/queries#keywords-diff-and-commit-searches-only)).

Examples:

* [unmerged commits with `task` in their diff](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/Microsoft/vscode%24%40*refs/heads/:%5Erefs/heads/master+type:diff+after:%221+month+ago%22+task#1)
* ["Who's been adding init functions?"](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24%40*refs/heads/+type:diff+after:%222+weeks+ago%22+lang:go+%22func+init%28%29%22) (Go static init functions, which can sometimes be undesirable)
* [Who's using old-style JS require (not import)?](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24%40*refs/heads/+type:diff+after:%222+weeks+ago%22+file:%5C.%28js%7Cts%29x%3F%24+%22require%28%22)

Please let me know if this helps!

**Comment by techman84** [comment]
Thank you @slimsag, now it's clear.
