### ISSUE TITLE
Prometheus cannot send email notifications without TLS encryption 

### ISSUE THREAD

**Issue by alexAtSourcegraph** [sourcegraph/sourcegraph#23636]
- **Sourcegraph version:** 3.29.1
- **Platform information:** Kubernetes Deployment

#### Steps to reproduce:

1. Update site configuration to include `email.address, email.smtp` properties. 
2. Add `"noVerifyTLS": true` to `email.smtp` property.
3. Attempt a test email notification using the Sourcegraph API console.

#### Expected behavior:
With properly configured properties in the site configuration, a test email notification would be received in the configured email inbox.

#### Actual behavior:
When `"noVerifyTLS":true` is added to the `email.smtp` property of site configuration, Prometheus throws the following error and fails to deliver the email notification:
`msg="Notify attempt failed, will retry later" attempts=1 err="'require_tls' is true (default) but \"smtp.server.com:port\" does not advertise the STARTTLS extension"`

**Comment by daxmc99** [comment]
As a temporary workaround before this is released in 3.31, the user can set both `"noVerifyTLS":true` & `disableTLS:true`

**Comment by alexAtSourcegraph** [comment]
Thanks, @daxmc99 !
