### ISSUE TITLE
Sales & Marketing

### ISSUE THREAD

**Issue by whichsteveyp** [sourcegraph/sourcegraph#23640]
Hello, today I was contacted on my personal cell by a rep from your company. I've never given y'all that info nor consented to being contacted for sales - so I'm assuming you purchased it or found it online and then dug up my github + association with my employer.

Not only am I not the person to talk to for this, I'm not the person to contact to try to learn who to talk to about potentially using your product. And I _definitely_ am never that person on my _personal cell that I did not provide you_.

Would love to be added to your DNC list if possible. Thanks.

**Comment by ebrodymoore** [comment]
Hi @whichsteveyp - We're sorry for that, I've confirmed you're now on our DNC list.
