### ISSUE TITLE
Caution/suggest to users in the creation form that they still try to keep their insights <500 repos

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#23655]
We should advise users via some quick copy changes/a phrase near the “all repos” checkbox that, though they can run insights over “all repos,” we currently best support a strongly suggested limit of 500 repos.

The reason for this is to give ourselves a “soft limit” of confidence and support levels as we scale this system up, because we aren’t 100% sure the current system can always handle >500 repos and we don’t want to over-commit. Much better to tell the user “go ahead, try it over 7k repos, but if it breaks we noted already it might do that” than “try it over 7k repos! Oh, it broke? Yeah well we didn’t want to tell you but…” 

**Proposal: change the below text to just: "run your insight over all repositories – with soft [beta limitations](linkurl)"** 

- This has no functional limit in the code
- There will be no form validation of any kind related to this
- This can just be a phrase near the “all repos” checkbox that should link to the limitations docs page (https://docs.sourcegraph.com/code_insights/explanations/current_limitations_of_code_insights) 
- This won't change the fact that you can't add repo lists in any format on creation
- So then how can a user honor this limit? Well, we only save things for matching repos, so even though they can’t yet pass in a pre-filter of repos for the insight, if you attach a filter like “lang:go” and only 350 repos have go files, then that conforms to this limit. 
- What will be on the docs page: The way to test this for the user, if they are curious, will be manual – take their search query, copy to a search bar, add `select:repo` and see how many repos they have
- Doing this automatically for a user would be a cool stretch item that I don’t expect we’ll fit into the beta  

![image](https://user-images.githubusercontent.com/11967660/128433295-c2400112-16c3-430d-88b8-681d6d147555.png)

**Comment by AlicjaSuska** [comment]
Design is ready to review in [Figma](https://www.figma.com/file/wXKTspDmgTrPPumahHQTXQ/Caution-suggest-to-keep-insights-500-repos-23655?node-id=0%3A1):
- added the checkbox with explanation and link to Docs
- showed the disabled state for the repositories field when the checkbox is selected (please review the behavior described in the pink note)
- added 'repositories' label to the field, changed the section title to 'Targeted repositories'

@Joelkw @vovakulikov could you please review the design? Thank you!
