### ISSUE TITLE
search notebooks: add File block

### ISSUE THREAD

**Issue by novoselrok** [sourcegraph/sourcegraph#23668]
Add a new File block with the following inputs: repository, revision, file path, and line ranges. The output should be syntax highlighted lines, or the entire file if no line ranges were provided.

**Comment by rvantonder** [comment]
Please add me to reviewers for this PR :-)

Question/comment for my curiosity: looks like embedded notebook queries use the streaming search API right? To implement this highlighting I think it's only possible via GQL API currently. Note there is a call in the GQL API to limit line highlighting to a specific range.

Possibly relevant: @camdencheek and I have been working on streaming highlighted _search_ results for ranges too. Down the line it _might_ (?) make sense to expose file highlighting on an independent stream endpoint for this use case (`compute` decoration). But for one-shot highlighting GQL is the best (only) option right now.

**Comment by benvenker** [comment]
@novoselrok is this the equivalent in your mind of the code snippets Beyang was wanting, but in Notebooks land? If so, I'm wondering if we want an option to disable the highlighting as well. If we're able to restrict the ranges to just what the user wants to see, the highlighting seems unnecessary/overkill from a UX perspective.

Additionally, if file block === code snippets, should we be thinking about a way to infer the necessary query from a selection in a file result so it's easy to add just a selection/"snippet" to a notebook?

**Comment by benvenker** [comment]
Clarified the above with @novoselrok. We were talking about different things. There will be syntax highlighting in the displayed snippet but not line highlighting.
