### ISSUE TITLE
Embed search code blocks in an external site

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#23666]
#### Feature request description

Embed search notebook type search blocks into external sites.

#### Is your feature request related to a problem? If so, please describe.

Search notebooks are great to tell a story about a codebase or explain the search query language. However, it _has_ to be in a notebook. Blog post or content creators would want the search blocks to be embedded in their own website.

Internal customer:
- Community team: embed search blocks into the sourcegraph learn website vs copying it over to a notebook ([Sourcegraph learn](https://learn.sourcegraph.com/literal-search-patterns) | [notebook](https://github.com/sourcegraph/notebooks/blob/main/learn-literal-patterns.snb.md))

#### Describe alternatives you've considered.

Using notebooks directly is a good quickfix. It will only work for users that are OK putting the content on our own domain.

**Comment by csbailey5t** [comment]
This would also be useful internally for the Content team, with effectively the same use case. We imagine using search notebooks in the Sourcegraph blog as a way to take a guided tour through code examples following Dev Tool Time episodes where it makes sense, such as recently re: CUE lang.

**Comment by sqs** [comment]
https://docs.sourcegraph.com/notebooks/notebook-embedding
