### ISSUE TITLE
File extension => file type mapping configuration

### ISSUE THREAD

**Issue by jacks0n** [sourcegraph/sourcegraph#237]
It would be very useful to be able to specify file types for specific file extensions.

As a Drupal developer, often PHP files have custom file extensions (e.g. `.module`, `.inc`) that Sourcegraph doesn't understand. This is the main barrier for me being able to use Sourcegraph fully.

I haven't been able to find any workarounds.

**Comment by sqs** [comment]
Yes, big feature gap here. Thanks for filing.

@chrismwendt, @felixfbecker, and I will chat about how to solve this in the next 48h and will put up a plan at https://github.com/sourcegraph/about/tree/master/projects. This touches many parts of Sourcegraph, so we'll see how we can get a shorter term workaround.

We'll fix it throughout, but to help us prioritize the quicker fix, in which areas are you specifically experiencing issues?

- Syntax highlighting
- Code intelligence
- `lang:` filters in search
- Anywhere else?

**Comment by jacks0n** [comment]
@sqs thanks for the quick response. At the moment `.inc` and `.module` files are treated as plain text files, so syntax highlighting and code intelligence doesn't work at all.

**Comment by aidaeology** [comment]
Removed code-intel tag for now, please add us back if you determine we need to do work to support this feature.

**Comment by tjdevries** [comment]
This can now be configured via `syntaxHighlighting` in the site configuration.

More information can be found here: https://docs.sourcegraph.com/dev/how-to/add_support_for_a_language#customizing-syntax-highlight-language

I'm happy to answer any questions about the feature!
