### ISSUE TITLE
Results could not be searched in time.

### ISSUE THREAD

**Issue by KashingLiu** [sourcegraph/sourcegraph#23710]
#### Question description

When I search `type:commit repo:content after:"1 month ago" `, there is an alert shows `6 repositories could not be searched in time. Try searching again or reducing the scope of your query with repo:, repogroup: or other filters.`. Is it caused by the repository updating? So I cannot get the real search result from the git repo. But when I search one of these 6 repositories, it can show the result correctly, and there is not an alert. Why does it behave like this?
![image](https://user-images.githubusercontent.com/22939122/128677218-a5610770-f5d8-42aa-8a97-6d0a52d3fc9d.png)

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket,  please let us how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
