### ISSUE TITLE
Symbols service: spammy unknown ctags kind gets logged

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#2372]
Seeing a lot of logspam of the following form in latest `master`:

```
16:57:19               frontend | Unknown ctags kind: "packageName"
16:57:19               frontend | Unknown ctags kind: "packageName"
16:57:19               frontend | Unknown ctags kind: "packageName"
16:57:19               frontend | Unknown ctags kind: "packageName"
16:57:19               frontend | Unknown ctags kind: "packageName"
16:57:19               frontend | Unknown ctags kind: "packageName"
16:57:19               frontend | Unknown ctags kind: "packageName"
16:57:19               frontend | Unknown ctags kind: "packageName"
```

From https://sourcegraph.slack.com/archives/C07KZF47K/p1550624287099000

We should suppress this in customer deployments.

**Comment by felixfbecker** [comment]
> We should suppress this.

That would be like putting tape over your engine-needs-maintenance LED. We should handle the kind.

**Comment by chrismwendt** [comment]
Yup, and most of our customers aren't mechanics, so I added the qualification "... in customer deployments" just now.

**Comment by felixfbecker** [comment]
Most car drivers aren't car mechanics and that LED is still shown in their dashboard, so they can contact a mechanic if it lights up. And we don't even show this in the dashboard, we show it if you open hood...
