### ISSUE TITLE
Filtering on narrow screens overlaps graphs

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#23765]
If you use a filter on a narrow screen, it overlaps the graphs. 

I expect we may want to do another larger pass over our filter UI at some point in Sep-Dec 2021, with some of the following future concepts in mind: 

- Can I apply a filter to a whole dashboard? 
- Should filters persist on the screen? Should they be something other than a popup? 
- If a popup, can we make it translucent when not actively focused so you can see the graph values? 

Etc. 

This is mostly a placeholder ticket at this moment to collect future thoughts/problems.

**Comment by Joelkw** [comment]
Example on a narrow screen:
![CleanShot 2021-08-10 at 15 51 44](https://user-images.githubusercontent.com/11967660/128945871-f4175872-7e35-428a-a777-5ecb69d56c9c.gif)
<img width="748" alt="CleanShot 2021-08-10 at 15 55 20@2x" src="https://user-images.githubusercontent.com/11967660/128945899-3c65c3b4-5693-4966-8a7a-800fa3253aac.png">

**Comment by Joelkw** [comment]
Two more issues 
![image](https://user-images.githubusercontent.com/11967660/129671144-738a83b7-0ce0-41f7-aa0c-5b8202969372.png)
![image](https://user-images.githubusercontent.com/11967660/129671563-de53e6d8-79f7-45b0-84e7-1c180ccc80e4.png)

**Comment by unclejustin** [comment]
This has been fixed.
