### ISSUE TITLE
Flake: TestSyncRegistry, TestNextSync and TestSyncerRun

### ISSUE THREAD

**Issue by indradhanush** [sourcegraph/sourcegraph#23772]
- **Name of tests:**  TestSyncRegistry, TestNextSync, TestSyncerRun
- **Example failure:** https://buildkite.com/sourcegraph/sourcegraph/builds/104488#0ffd8d62-3a23-4fb3-873e-659ab4fa6e72/341

**Comment by mrnugget** [comment]
Hopefully fixed in https://github.com/sourcegraph/sourcegraph/pull/24462. Please reopen if this comes up again.
