### ISSUE TITLE
Flake: TestSyncRegistry

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#23796]
- **Name of test:** enterprise/internal/batches/syncer:TestSyncRegistry
- **Example failure:** https://buildkite.com/sourcegraph/sourcegraph/builds/104547#93906ad5-c2de-4510-834e-d52b073a8703

cc @sourcegraph/batchers

**Comment by mrnugget** [comment]
Hopefully fixed in https://github.com/sourcegraph/sourcegraph/pull/24462. Please reopen if this comes up again.
