### ISSUE TITLE
Flake: percy batch changes flake

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#23795]
- **Name of test:** Batch changes list - light theme 
- **Example failure:**  https://percy.io/Sourcegraph/Sourcegraph/builds/12033382/changed/677543692?browser=chrome&browser_ids=16&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1920&widths=1920

**Comment by mrnugget** [comment]
I dug into this but give up now and close this ticket. If this happens again, please reopen and I'll investigate.

I just can't make sense of this failure. In the screenshot the whole page is blank, 0 elements to see. But in our test we only call the `percySnapshot` function after all the other assertions (do the elements exist?) were true.

I suspect that something between browser <-> snapshot <-> percy went wrong here, or that there's some underlying integration-test-utilities failure. But it _seems_ unrelated to our tests.
