### ISSUE TITLE
Integrations quality

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#2380]
The desired outcome of this project is to increase the product quality, stability and code quality of our integrations, and more specifically of the browser extension.

## Goals
- **Error handling**: no more `console.error(err); return null`
- **Reactive to the DOM**: no more one-time `inject()` calls
- **Tested**: prevent regressions

## Metrics
- Number of errors on [Sentry](https://sentry.io/sourcegraph/browser-extension/)
- Uninstalls tracked by [Chrome webstore](https://chrome.google.com/webstore/developer/stats/dgjhfomjieaadpoljlnidmbgkdffpack)
- Unhandled errors: [![search matches](https://sourcegraph.com/search/badge?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:%5Eclient/browser/+%22console.error%28%22&label=search+matches)](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:%5Eclient/browser/+%22console.error%28%22)

## Plan

[Issues labeled <kbd>code-nav</kbd> <kbd>browser-extension</kbd>](https://github.com/sourcegraph/sourcegraph/issues?q=is:issue+is:open+sort:updated-desc+label:code-nav+label:browser-extension+milestone:3.2)

## Test/review plan

- Code reviewer: 
- Tester:

**Comment by nicksnyder** [comment]
The metrics section doesn't clearly define what success looks like (or even what the current baseline is).

Recording the current baseline would be incredibly valuable and then you can set a goal relative to that baseline (e.g. 50% fewer sentry alerts, 50% browser extension installs)

**Comment by nicksnyder** [comment]
Tracking issues are supposed to reflect what a given team is going to get done in a given release cycle. 

Here are two examples of good tracking issues:
- https://github.com/sourcegraph/sourcegraph/issues/2809
- https://github.com/sourcegraph/sourcegraph/issues/2452

Please close this issue with an explanation about what you accomplished in 3.2 and create a new one for 3.3 that reflects what you plan to do in that release cycle.

**Comment by lguychard** [comment]
Issues closed in 3.2:
- https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+archived%3Afalse+assignee%3Alguychard+is%3Aclosed+milestone%3A3.2+
- https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+archived%3Afalse+assignee%3Afelixfbecker+is%3Aclosed+milestone%3A3.2+
