### ISSUE TITLE
Add Azure Devops as one of the code hosts

### ISSUE THREAD

**Issue by zyh41** [sourcegraph/sourcegraph#23828]
#### Feature request description

As an Azure Devops site admin, I'd like to have "Azure Devops" as a dedicated host "kind" for adding all repositories I have access to on UI

This is beneficial for org/people who uses ADO.

The APIs are available here:
https://docs.microsoft.com/en-us/rest/api/azure/devops/git/?view=azure-devops-rest-6.0

similar to bitbucket, the input config could be:

```json
{
  "url": "https://example.com/org/_git",
  "token": "<access token>",
  "username": "<username that created access token>", <- optional_if_token_is_PAT
  "repositoryQuery": [
    "all"
  ]
}
```

#### Is your feature request related to a problem? If so, please describe.

https://github.com/sourcegraph/sourcegraph/issues/8647#issuecomment-800499622

#### Describe alternatives you've considered.

Using "Generic Git host" allows me to add repos, it works using https and PAT with config, however, it takes time if user wants to add lots of repos. As this is generic git host config, and different hosting platforms have different list APIs, I'd image it does not make sense to extend this config to have a key that takes regex for repo names matching/filtering

```json
{
"url": "https://PAT@example.com/org/_git",
"repos": ["r1"]
}
```

**Comment by eseliger** [comment]
Azure DevOps support has been added to Sourcegraph a while ago: https://docs.sourcegraph.com/admin/external_service/azuredevops!

Thanks for requesting :)
