### ISSUE TITLE
"Active" state of buttons should not share the same style as "focused"

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#23849]
The "active" state for the button group on the search homepage looks like a focus state and always confuses me when I land on the search homepage because it looks like that button is keyboard-focused, but clicking elsewhere doesn't unfocus it.

![image](https://user-images.githubusercontent.com/10532611/129232997-0d810b84-cd3f-4ef2-bc7f-006f28a596d2.png)

Looking at the CSS class, it uses `active`, and `active` is part of the same selector that applies `:focus` styles. However, I think that is semantically wrong: The "active" state of a button is a different state than focus, it's a "pressed" state. See for example the [active state in Bootstrap button groups](https://getbootstrap.com/docs/5.1/components/button-group/#basic-example) and how it is "pressed" (darker) but not the same as "focused" (with an outline).

There is also a clear reason for this: It must still be possible to focus an "active" button with the keyboard as you tab through a button group, which would not be visually detectable if the states were the same.

**Comment by 5h1rU** [comment]
I'm taking a look at the [figma](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Design-Refresh-Systemization-source-of-truth?node-id=908%3A2514) implementation, and we don't have any active status designed. 

Do we need to include this new status in our systematization file? @AlicjaSuska

**Comment by felixfbecker** [comment]
As a quick fix, reusing the hover state would be better than reusing the focus state.

**Comment by valerybugakov** [comment]
Let's wait for at least a comment from @sourcegraph/design and move forward after that because it's not a critical bug. 
It would be great to incorporate a solution for this issue into the Wildcard Sticker Sheet.

**Comment by pdubroy** [comment]
@AlicjaSuska Any comment from the design side?

**Comment by AlicjaSuska** [comment]
Thank you for raising this. Let's differentiate the active and focus states:
- focus: as is
- active: the same visually as hover state
@taylorsperry @lrhacker FYI

**Comment by umpox** [comment]
Noticed this is a duplicate of another issue. Closed in favour of https://github.com/sourcegraph/sourcegraph/issues/35354 to avoid duplicating work
