### ISSUE TITLE
Stats button in search results bar is too big

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#23872]
![image](https://user-images.githubusercontent.com/19534377/129284553-7589d1a9-9512-4866-9e3d-fe437f7e1d8a.png)

The `Stats` button is slightly bigger than the other ones.

**Comment by valerybugakov** [comment]
The `Stats` button seems to be coming from `SearchResultsInfoBar` owned by @sourcegraph/search-product: 

https://github.com/sourcegraph/sourcegraph/blob/24e2b4e9262b350d02de5db903c20fa97f822255/client/web/src/search/results/SearchResultsInfoBar.tsx#L314-L321

The markup is defined by the `ActionsNavItems` component probably owned by @sourcegraph/extensibility: 

https://github.com/sourcegraph/sourcegraph/blob/24e2b4e9262b350d02de5db903c20fa97f822255/client/shared/src/actions/ActionsNavItems.tsx#L90-L103

Could one of the teams take over this issue? Let me know if I'm wrong about who is responsible for this part of the UI.

**Comment by Joelkw** [comment]
Thanks @valerybugakov ! Probably any team tagged could own this but we're happy to make this quick fix.

**Comment by limitedmage** [comment]
Yes, this is owned by @sourcegraph/extensibility and will also affect buttons coming from extensions (eg. the "Export to CSV" extension).
