### ISSUE TITLE
Bulk actions pings and update monthly contributor definition

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#23882]
We recently added bulk to allow users to manage a large number of changesets in just a few clicks. We don't have metrics for them yet.
- We want to track usage of bulk actions.
- We now consider that users that perform some bulk operations (comment, merge, close, publish) are actively managing batch changes and should be counted as monthly contributors.

[RFC 424 APPROVED: Add server side and bulk actions to Batch Changes pings](https://docs.google.com/document/d/1JlGMgk51LGONIQi9Zsaeo1eqxSg5Msp1--j2g4fLq6k/edit)

- [ ] add count of the number of bulk [`comment`, `detach`, `re-enqueue`, `merge`, `close`, `publish`] by week
- [ ] update monthly contributor definition to add any user that performed a bulk `comment`, `merge`, `publish`, `close` in a given month

**Comment by BolajiOlajide** [comment]
@malomarrec I'm having trouble understanding one of the requirements for this issue:

```Update monthly contributor definition to add any user that performed a bulk comment, merge, publish, close in a given month```

Does this refer to the number of bulk operations in a single month or the amount of unique users who have carried out a bulk operation in a single month?

**Comment by malomarrec** [comment]
We should:
- track the number of bulk operations of each type per month
- AND update the MAU (called monthly_contributor in pings) definition to
count as active anyone who performed a bulk operation.

**Comment by BolajiOlajide** [comment]
Got it. Thanks

**Comment by BolajiOlajide** [comment]
Fixed by [#34308](https://github.com/sourcegraph/sourcegraph/pull/34308)
