### ISSUE TITLE
Browser extension causing backend errors

### ISSUE THREAD

**Issue by muratsu** [sourcegraph/sourcegraph#23914]
When someone forgets to point their bext to the private instance and we make calls to dotcom instead it causes errors on the backend (repo can't be cloned!) This is causing problems with logging.

[Slack convo](https://sourcegraph.slack.com/archives/CMBA8F926/p1628599402084000)

**Comment by Joelkw** [comment]
From @muratsu – we could set this to only fetch relevant repos / repos that might be fetchable. Public+private on the same extension might also be considered relevant to this work. Could fix with quick changes to browser extension.
