### ISSUE TITLE
Smarter search query analysis -> No results page

### ISSUE THREAD

**Issue by fkling** [sourcegraph/sourcegraph#23928]
Now that https://github.com/sourcegraph/sourcegraph/pull/23726 is merged, we have a good foundation to improve the UX around query input and diagnostics. This issues serves as a collection of next steps and open questions/issues around that.

## Possible next steps

- Validating `type:diff` and `type:commit` related filters, including quick fixes (that's new)
- Validating `select:` predicates
- Ranked auto-completion suggestions based on existing query
- Similarly, show relevant filters in the search reference or in search types

## Open questions

So far I can identify two use cases: Diagnostics for Monaco and general contextual information for other parts of the app (e.g. the sidebar). I originally thought that we would only define a single set of rules that covers both cases (and evaluate those rules in a single place) but maybe it's OK to have separate rule sets.

Either way, `QueryState` should probably be extended with a parsed/tokenized version of the query to avoid parsing it in multiple places and to possible contain the contextual query information.

Eventually we would want to abstract from the query being processed as tokens, and provide a higher level API/DSL to define rules and quickfixes ( @lguychard provided `lang:$1 $2` as an example for how to specify quickfix patterns).

## Subtasks

- [x] https://github.com/sourcegraph/sourcegraph/issues/24689
- [ ] https://github.com/sourcegraph/sourcegraph/issues/24691

**Comment by lguychard** [comment]
Initial version of the no results page was released.

**Comment by fkling** [comment]
Just for posterity and completeness: The initial version of the no results page doesn't include any query analysis. It's "just" a static page.
