### ISSUE TITLE
Typing a "[" or a "(" breaks adding insights to dashboards

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#23934]
If I type a "[" in the "add insights to dashboard search bar" then it totally breaks: 
[Loom Video](https://www.loom.com/share/9e6e82295b614dd38c26eccf343cbdd9)

Probably we just need to escape the input or something.

**Comment by unclejustin** [comment]
@Joelkw I gotchoo fam

**Comment by Joelkw** [comment]
Nice @unclejustin !
