### ISSUE TITLE
Consider fixing y-axis labels to remove sometimes-unnecessary padding

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#23951]
We might want to remove unnecessary padding when the y-axis labels are small (see #23950 for context)

**Comment by vovakulikov** [comment]
@Joelkw Whenever you have a moment can you confirm that this one has been closed by the fix for the https://github.com/sourcegraph/sourcegraph/issues/23950

**Comment by vovakulikov** [comment]
Close it since it has been fixed by https://github.com/sourcegraph/sourcegraph/pull/24091
