### ISSUE TITLE
Filtering to a repo pattern that's not a repo breaks the graph display

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#23952]
Example: 
![image](https://user-images.githubusercontent.com/11967660/129429989-27099db0-f389-4693-a380-eb08a2415960.png)

 versus the correct example

![image](https://user-images.githubusercontent.com/11967660/129429999-15988d97-cbfd-4565-a423-0a948ce56fe0.png)

Can we just show 0 values but preserve the points? **OR** if we do have two different signals (no repos matched vs 0 values) then it would be awesome if we could display a message like "no repos match that filter" cc @AlicjaSuska on that?

**Comment by Joelkw** [comment]
(@vovakulikov this can bump any stretch issues as well)

**Comment by vovakulikov** [comment]
@Joelkw This might be a problem to fix. Since we render everything that we got from BE response. In this case, I think insight BE returns zero points and zero series cause this non-repo filter has been applied. So to be able to fix that we have to change the BE logic and always send a chart series even if the filter cut off all repos from the search area. 

cc @coury-clark

**Comment by vovakulikov** [comment]
@Joelkw But it is possible to add some empty chart states. In general we need this anyway. Cause at the moment there are cases when we get insight data with zero series (even without a bad filter) and I think it would be cool if we have some visual state for it. (cc @AlicjaSuska)

**Comment by Joelkw** [comment]
@vovakulikov thanks, I understand. Don't expect the perfect fix to land for beta then given the backend dependency, but do you think we could get a quick "no data points found" message for this case so it seems like the system at least knows what's going on?

**Comment by coury-clark** [comment]
@vovakulikov @Joelkw I'm trying to catch up on this conversation, but as I understand it I don't think the conclusions above are exactly correct. Below is an example of the graphQL query where it won't match any repositories, but returns the series metadata still. The expectation should be if the underlying series has zero points, we return zero points - but I don't see any issue with the metadata resolving currently.

```
query Insights {
  insights {
    nodes {
      title
      series {
        points (includeRepoRegex:"asdfasdfasdfasdf") {
          dateTime
          value
        }
        label
      }
    }
    totalCount
  }
}

**Comment by vovakulikov** [comment]
@coury-clark can you can with id filter as well, at the moment I'm checking this query at k8s and with weird filter value backend returns empty point array

<img width="682" alt="Screenshot 2021-08-18 at 21 31 59" src="https://user-images.githubusercontent.com/18492575/129952877-801a8edf-110a-4223-857e-ec35d04c0edd.png">

**Comment by coury-clark** [comment]
@vovakulikov right - the array is empty because there are no results. What else could possibly go there? I thought you were talking only about the metadata (label, title, etc)

**Comment by vovakulikov** [comment]
Yeah Sorry for that, For some reason I was thinking about points array and not about metadata. Ignore my comment above. 🤦

**Comment by unclejustin** [comment]
@Joelkw I _think_ https://github.com/sourcegraph/sourcegraph/pull/24055 covers (ha pun!) this use case. If we get back 0 data then the new error overlays will explain what is happening.

**Comment by Joelkw** [comment]
Awesome, thank you!

**Comment by unclejustin** [comment]
https://github.com/sourcegraph/sourcegraph/pull/24055 merged. Given @coury-clark's comments above, I'm closing this issue.
