### ISSUE TITLE
We lost "Start Y" from "Start Y Axis at 0" – just add it back

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#23958]
I think it got removed in [this change](https://github.com/sourcegraph/sourcegraph/commit/4deb23d3d2a0bb015807cbcc67de1a125ca7ba19#diff-98d9f8b5f59dcfd26ea7b58974723dd5f5e0a7a220490014c4b2c3c24b0b53c1L63) (but I wasn't sure what was up with the `{' '}` so I'll let someone smarter than me fix this!). Not a big deal, and easy to fix!

Should appear as it did before: `Start Y Axis at 0`

![image](https://user-images.githubusercontent.com/11967660/129439460-3bc902e2-f050-4454-bdf0-e2cbb1ccacab.png)

**Comment by felixfbecker** [comment]
Agree, this irritated me too, gtk how it happened :)

**Comment by felixfbecker** [comment]
FYI `{' '}` is just a regular space at the end of the line (if it was a literal, unquoted space ` `, it would get trimmed by autoformatting)
