### ISSUE TITLE
How to set the NGINX config to run sourcegraph under a non-root URL

### ISSUE THREAD

**Issue by KashingLiu** [sourcegraph/sourcegraph#23970]
#### Question description

I know that the sourcegraph is not supported under a non-root URL. But is there a way to support it by using a nginx server which is different from the nginx owned by Sourcegraph itself?
It seems that we can redirect the request which is sent to root URL, to a non-root URL or set a proxy_pass. 
For example, if I have a non-root URL like http://nonrootexample.sourcegraph.com/test.
`http://rootexample.sourcegraph.com:7080/search` --> `http://nonrootexample.sourcegraph.com/test/search`
`http://rootexample.sourcegraph.com:7080/.assets/scripts/*` --> `http://nonrootexample.sourcegraph.com/test/.assets/scripts/*`
`http://rootexample.sourcegraph.com:7080/sign-in` --> `http://nonrootexample.sourcegraph.com/test/sign-in`
What I need is to add a prefix. Do you know how to set the nginx.conf? Is it possible?

**Comment by KashingLiu** [comment]
See also #2180 #7876 #119 #103

**Comment by dan-mckean** [comment]
It's not currently in our plans to offer support or guidance for this.
