### ISSUE TITLE
Golang: files with a build tag are ignored

### ISSUE THREAD

**Issue by xvello** [sourcegraph/sourcegraph#2399]
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:** Firefox 65.0.1 on Linux

#### Steps to reproduce:

Our Go monorepo ships several agents that we compile with different build tags. Searching for references and definitions do not work on files under a build tag. Three examples in one file:

* Reference search for [NewHandler](https://sourcegraph.com/github.com/DataDog/datadog-agent@6.10.0-rc.3/-/blob/pkg/clusteragent/clusterchecks/handler.go#L62:6) fail. I expected to find [this use](https://sourcegraph.com/github.com/DataDog/datadog-agent@6.10.0-rc.3/-/blob/cmd/cluster-agent/app/app.go#L245:14)
* Definition search for the [dispatcher](https://sourcegraph.com/github.com/DataDog/datadog-agent@6.10.0-rc.3/-/blob/pkg/clusteragent/clusterchecks/handler.go#L49:24) type does not return [the expected definition](https://sourcegraph.com/github.com/DataDog/datadog-agent@6.10.0-rc.3/-/blob/pkg/clusteragent/clusterchecks/dispatcher_main.go#L22-23)
* Definition search for the stdlib's [sync.RWMutex](https://sourcegraph.com/github.com/DataDog/datadog-agent@6.10.0-rc.3/-/blob/pkg/clusteragent/clusterchecks/handler.go#L54:1) type does not return either, while it works fine [on this file with no build tag](https://sourcegraph.com/github.com/DataDog/datadog-agent@6.10.0-rc.3/-/blob/pkg/tagger/tagstore.go#L33:2)

#### Expected behavior:

Code intelligence works, and returns all uses and definitions in the code base. If two definitions are found (because there is a [placeholder definition under the `!clusterchecks` tag](https://sourcegraph.com/github.com/DataDog/datadog-agent@6.10.0-rc.3/-/blob/pkg/clusteragent/clusterchecks/api_nocompile.go#L33:6), both should be presented to the user).

Ideally, a user could browse the source with custom build tags (are you investigating the windows or the linux code path today?), but that'd probably a chunk of its own.

#### Actual behavior:

Golang code intelligence does not work if either the declaration or the reference is under a build tag.

**Comment by nicksnyder** [comment]
@chrismwendt this might be something we want to bring up with the upstream language server. Can basic code intel provide help here?

**Comment by chrismwendt** [comment]
Basic code intel shows the reference:

![image](https://user-images.githubusercontent.com/1387653/53206560-1e620000-35e6-11e9-8d35-9513936a3ae6.png)

It won't be that accurate for functions with more common names (e.g. `Get` will return tons of results). I have a plan for improving the accuracy in https://github.com/sourcegraph/sourcegraph/issues/2298

Alternatively, we could add a command palette item that lets you enter the build tags you want to browse the code using, and those build tags would be sent to the language server in the initialize request. I'm not 100% if that would work, but that's how I would approach it.

**Comment by keegancsmith** [comment]
> Alternatively, we could add a command palette item that lets you enter the build tags you want to browse the code using, and those build tags would be sent to the language server in the initialize request. I'm not 100% if that would work, but that's how I would approach it.

That would work. In theory the upstream language server could find these other locations and present all of them. But it would be quite hairy to do + would only work for j2d/hover not find references (which would be much more complicated to do)

**Comment by xvello** [comment]
Thanks for your replies! Having a build tag selection control would indeed help a lot, provided it is persisted by code repository.

After re-reading the issue, I think there are two distinct user stories here:

- `As contributor to a "build-tagged" package, I want code intelligence to work on my code in order to efficiently use Sourcegraph`. This would be solved by browsing with custom build tags
- `As a contributor, I want to look for all usages of the method I'm modifying, including "build-tagged" code, to ensure I'm not introducing side-effects`. We currently resort to grep'ing the whole repository for this.

**Comment by aidaeology** [comment]
Obselete as its an LSP related issue.
