### ISSUE TITLE
Cross-repo jump to def to file removed in master fails (kubernetes)

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#24]
Jump to def on `[s.Create]`https://sourcegraph.com/github.com/kubernetes/kubernetes@6430b1002c2900a1761cbd07cb77a1e4cf82b64e/-/blob/pkg/registry/extensions/deployment/registry.go#L69:16-69:22 breaks with `Unable to open 'rest.go': open server/pkg/registry/rest/rest.go: file does not exist.` error.

~The file that we're attempting to jump to was removed in https://github.com/kubernetes/api/commit/ab8ef47cb141bc2c8fef662a179c948d53956ec4, and currently we don't take into the version information when performing a cross-repository jump-to-def.~

The reason this isn't taking into account version information is that we need to support symbolic links in our VFS. k8s.io/apiserver/pkg/registry/rest is vendored in, but in a weird way via a symbolic link https://sourcegraph.com/github.com/kubernetes/kubernetes@6430b1002c2900a1761cbd07cb77a1e4cf82b64e/-/blob/vendor/k8s.io/apiserver (via @keegancsmith)

(HT @ahmetb)

**Comment by keegancsmith** [comment]
j2d on `Create` works for me.

**Comment by keegancsmith** [comment]
> currently we don't take into the version information when performing a cross-repository jump-to-def

We do for golang.

**Comment by keegancsmith** [comment]
The reason this isn't taking into account version information is that we need to support symbolic links in our VFS. `k8s.io/apiserver/pkg/registry/rest` is vendored in, but in a weird way via a symbolic link https://sourcegraph.com/github.com/kubernetes/kubernetes@6430b1002c2900a1761cbd07cb77a1e4cf82b64e/-/blob/vendor/k8s.io/apiserver
