### ISSUE TITLE
Prune undesirable git tags

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#2401]
Our repo has a bunch of git tags that we inherited when we merged in one of the other repos (e.g. extensions npm api, or browser extension, or something). This makes it annoying to tag new Sourcegraph releases because these tags must first be deleted on the origin before tagging the "real" release for the main Sourcegraph images.

@chrismwendt did a one time purge, but it looks like the tags got re-pushed incidentally. I can't think of a good way to delete these on the origin and prevent others from inadvertently pushing them again.

My best idea is to make a script that will delete these tags from your local checkout and have everyone run that script, then delete them from the remote.

Any other creative ideas? cc @slimsag @keegancsmith @tsenart

**Comment by slimsag** [comment]
add a pre-push hook to prevent `git push --tags` and tell the user the git command to push a specific single tag

https://stackoverflow.com/a/20551984

**Comment by keegancsmith** [comment]
- get everyone to run a query which deletes the tags locally. Interested to know how this is happening, since one has to do git push --tags to recreate.
- Maybe github's branch protection rules could apply to the tags as well?

**Comment by felixfbecker** [comment]
Does `git pull --prune` not delete tags deleted on the remote?

**Comment by nicksnyder** [comment]
> Does `git pull --prune` not delete tags deleted on the remote?

No, but `git fetch --prune origin "+refs/tags/*:refs/tags/*"` does the trick.

**Comment by nicksnyder** [comment]
I cleaned up our origin and requested that everyone run the above command.

https://sourcegraph.slack.com/archives/C0EPTDE9L/p1551288111011100
