### ISSUE TITLE
extension: inaccurate jump to definition in pull request

### ISSUE THREAD

**Issue by ijt** [sourcegraph/sourcegraph#2407]
- **Sourcegraph version:** sourcegraph.com
- **Platform information:** Chrome 72.0.3626.109 on Mac

browser extension v19.2.13.1951

#### Steps to reproduce:

1. Go to line 172 of nats.go in https://github.com/google/go-cloud/pull/1381/files.
2. Hover the mouse over NextMsg and click Go to Definition.

#### Expected behavior:

It should go to the definition of NextMsg.

#### Actual behavior:

It goes to https://github.com/nats-io/go-nats/blob/HEAD/nats.go#L3015:24, which at the moment is somewhere inside a method called `unsubscribe`.

**Comment by chrismwendt** [comment]
@ijt Can you share a link to where you expect Go to Definition to take you? As far as I can tell, https://github.com/nats-io/go-nats/blob/HEAD/nats.go#L3015:24 is the correct definition.

**Comment by ijt** [comment]
Sure, it should be
https://github.com/nats-io/go-nats/blob/3ca0505d233111f6b95a2888f6536340a10a8aeb/nats.go#L3025
.

Now that I look again, I can see that the line it jumps to puts the
definition in view, it's just that the line it highlights isn't the right
one.

I suspect the sourcegraph server cached something that got a bit stale.

**Comment by chrismwendt** [comment]
It looks like go-cloud uses Go modules, which are not supported by go-langserver. go-langserver appears to assume HEAD for dependencies, which is why it took you to L3015. Yeah, visiting the repository probably triggered a `git fetch`, which then updated the HEAD to the latest commit.
