### ISSUE TITLE
Code Insights Backend: Carrying Over Datapoints from "left to right" if a repo/result goes missing causes unintended behavior, results, and confusion

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#24070]
As far as we understand it now, if a repo goes "missing" (unclear to me if that included "0" or truly null somehow) from sooner-in-time search results, we carry over a "more left" (earlier in time) data point and fill the value in our database with that match count. 

### **Example:** 

Some repo _R_ has 45 matches for some string _S_ five months ago. 
1. Three months ago, say:
   1. that file with the 45 matches for _S_ gets so large it is no longer searched (we have file size limits on searches and they're the [same for indexed/unindexed](https://github.com/sourcegraph/sourcegraph/pull/23840))
   1.  also say all matches for _S_ also get removed from the file and repo _R_.* 
1. Now _R_ returns 0 match count (at least in sourcegraph GUI search) but the insight carries "45" forward. This means the ultimate insight is wrong – there are truly 0 results for _S_ in _R_ now (and for the past three months). 

*_I think the only thing needed to trigger this example is 1.ii, and not 1.i, – I think you can ignore the "file gets too big to be searched" aspect. But since this is a real example and I'm not 100% sure, including it for the sake of accuracy._

I don't have full context on the benefits of doing this, so instead I'm just including the problems it causes and why I think we need to change that, and noting some benefits we've stumbled across we might need to think about "maintaining" in a solution.

### Problems seen: 
- It means that values "don't go back down" if a repo goes from having results to not having results / not existing:
  - we saw this come into play with a sourcegraph/ghdump repo, [here was that catch/writeup](https://sourcegraph.slack.com/archives/C02BQB5CCFK/p1629257134242400?thread_ts=1629190254.171200&cid=C02BQB5CCFK) (and this was affecting pretty much every insight we tested)
  - This is very "incorrect" from a user POV, especially if I am caring about a migration/deprecation – if everything gets deleted, then I do really care about seeing 0 values and seeing "carried over" values is unhelpful.
- It is nearly impossible for a user to debug (aka "know this is happening to their insight") in the current form of code insights, so they don't know if it affects their insights or not
  - This is because the search GUI won't show these repos as having "matches" if the issue is they no longer have matches now but the insight is carrying over old match counts forward (this was seen in the same writeup linked above). And since we don't return (now, or possibly ever) a list of "repos + match counts" the only way to figure out "what repo is contributing all these extra unintended results?" is to dig into the series_points db table, which most users won't have access to. 

### Benefits, maybe? 
- It seems like we're "flattening" the jumps around the historical-vs-indexed search this way when indexed search doesn't have results for archived + forked repos? [Link to thread](https://sourcegraph.slack.com/archives/C02BQB5CCFK/p1629140085054200?thread_ts=1629139713.050900&cid=C02BQB5CCFK)
  - possible solution: it turns out fork/archive default to "no" for indexed but "yes" for historical searches _because_ historical searches are run with a `repo` filter and that defaults these to "yes." So maybe we could just make them "yes" on indexed searches and that could help? 

Here were @slimsag 's [quick thoughts when asked](https://sourcegraph.slack.com/archives/C02BQB5CCFK/p1629257969243700?thread_ts=1629190254.171200&cid=C02BQB5CCFK) on what to do next on this, but we both obviously defer to @coury-clark here!

**Comment by Joelkw** [comment]
(@coury-clark it sounded like this wasn't actually an issue after we looked into it – feel free to close this if that's the case!)

**Comment by coury-clark** [comment]
To summarize the issue:
1. Last observations carried forward (carry to the right) was disabled when we moved to storing full vectors at each time.
2. This issue was the result of a bug in the compression logic, that associates unchanged time frames with an exemplar query
3. The problem was that the compression logic was using the wrong timeframe

Closed by https://github.com/sourcegraph/sourcegraph/pull/24101
