### ISSUE TITLE
Move main navigation item "docs" to the expanding menu on mobile screens

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#24088]
#### Problem statement
For narrow devices, we are greatly limited in the amount of space we have for items in the navigation bar:

![image](https://user-images.githubusercontent.com/9516420/134359165-0ee4a22a-1d3a-4e13-96ee-3468b47444ef.png)

These links and buttons are squashed together and are difficult to tap.

#### Success criteria

We should move the 'Docs' link to the expanding navigation menu **on mobile** to further optimise for small screens.

**Please note: The only required change here is moving the 'Docs' link and adding the divider, only on mobile breakpoints. Other changes from the design to the screenshot above aren't necessary.**
![image](https://user-images.githubusercontent.com/9516420/134359395-3d1bc0b4-b5e2-41c6-808a-14fb2cafc9a4.png)

Figma: https://www.figma.com/file/MgCovj1EGTApBkYVrfzlMw/Improve-navigation-on-mobile?node-id=2%3A6059&viewport=490%2C48%2C0.25

#### Things to learn/practice during the implementation
- Responsive styling

#### Estimated amount of work
T-shirt size estimate: S

**Comment by AlicjaSuska** [comment]
Hello @redhoyasa ! Yes, that's correct - Docs link is available only for unauthenticated users now :) Thank you!

**Comment by vanesa** [comment]
Hi @redhoyasa are you still tackling this issue? Thank you!

**Comment by redhoyasa** [comment]
Hi, I still didn't manage to run SG webapp on my local env (using M1) and I don't think I have enough bandwidth to work on this currently.

Feel free for others to take this on.

**Comment by natikgadzhi** [comment]
@valerybugakov looks like the website UI has changed since, and the menu is nice and clean now. I _think_ this is safe to close?

**Comment by valerybugakov** [comment]
Looks like you're right, @natikgadzhi. Thanks for looking into it!
