### ISSUE TITLE
Progress notification stuck

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#2409]
![image](https://user-images.githubusercontent.com/1741180/53240893-401fbd80-36a0-11e9-88d1-fd3be04849a3.png)

In the above screenshot, the "Fetching packages" notification is stuck and impossible to dismiss. This is with a pre-comlink extension, and I'm still seeing some `$updateProgress` emissions in the console.

**Comment by felixfbecker** [comment]
Let's revisit this after merging comlink #2344

**Comment by lguychard** [comment]
I haven't been able to reproduce this with the latest version of the browser extension.
