### ISSUE TITLE
TypeScript language extension downloading source twice?

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#2412]
Saw this on a PR just now:
![selection_042](https://user-images.githubusercontent.com/1646931/53262063-810cd780-368a-11e9-897d-9487bb778f94.png)

@felixfbecker does this indicate a bug?

**Comment by felixfbecker** [comment]
No, it's just one server for the head rev and one server for the base rev.

**Comment by beyang** [comment]
@felixfbecker could the loading message be different? "Downloading head revision to TypeScript server" and "Downloading base revision to TypeScript server"?
