### ISSUE TITLE
insights: a repo scoped insight doesn't match expected results

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#24148]
Slack [thread](https://sourcegraph.slack.com/archives/C014ZCKMCAV/p1629337847399000?thread_ts=1629313216.381200&cid=C014ZCKMCAV) for context

From @Joelkw 
> I ran this chart after the fixes from earlier today and even though it has a context, it seems to me like at least some of the queries (all 12, perhaps) ran to populate.
But the issue is that it’s showing a flatline, and we can actually compare it to the frontend insight (since it’s just 1 repo in the context, we can use the frontend to test!). This shows the flatline value is the “current”/“most recent” value. So if this Isn’t related to the database, there might be an issue here otherwise.

https://sourcegraph.slack.com/files/U01ADU7BKML/F02BKHH1BM3/image.png
https://sourcegraph.slack.com/files/U01ADU7BKML/F02CC7784KA/image.png
https://sourcegraph.slack.com/files/U01ADU7BKML/F02CC77G664/image.png

**Comment by coury-clark** [comment]
After digging in and recreating / retrying the backend insight, we found the following:
1. Search contexts change the underlying series in unexpected ways. It seems that the context is either restricting the revision, or otherwise manipulating the returned results. This is what is causing the unexpected number.
2. The backend and extension insight matched values exactly if they both had the context in the query.

**Comment by felixfbecker** [comment]
@coury-clark great find. So what is the resolution here? Do we need to tell users to not use search contexts? Should we file a bug on the search team as unexpected behavior?
