### ISSUE TITLE
Red symbol highlights on github

### ISSUE THREAD

**Issue by muratsu** [sourcegraph/sourcegraph#24157]
Currently, we highlight the symbol at the point with a yellow-ish color and other references to that symbol in red. The expected color is gray. Turns out, enabling the latest preview feature (dark high contrast) messes up our css colors.

Only Github is affected. It's happening on all browsers.

![image](https://user-images.githubusercontent.com/1308560/130117255-425e4229-42e4-4366-9a11-a6aa43ef1ab0.png)
![image](https://user-images.githubusercontent.com/1308560/130117281-07523741-7f8d-4e06-a8a6-0e177a690022.png)
![image](https://user-images.githubusercontent.com/1308560/130117272-aa5bd705-212a-43b4-89f2-0e4fa784a3b1.png)

**Comment by felixfbecker** [comment]
I would guess that GitHub used `red` everywhere here to surface which colors they haven't updated yet before releasing the feature as stable. So before that they would probably update these again, I'd guess.

**Comment by felixfbecker** [comment]
Okay, I'm now seeing the red highlights even without the Feature Preview. Looks like the feature preview was removed / released to everyone, it doesn't show up under "Feature Preview" anymore. Which also invalidates my theory above unfortunately.

**Comment by muratsu** [comment]
Thanks for the heads up @felixfbecker! We have this on our priority list for next week

cc: @tjkandala
