### ISSUE TITLE
Extension API: doc.text can be undefined

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#2416]
In the callback to `registerHoverProvider`, the given `TextDocument.text` field is `undefined` on private repositories, but the type is `string`. To handle this, I made a change to basic-code-intel:

https://github.com/sourcegraph/sourcegraph-basic-code-intel/commit/d291aaa733e6882dadbda5906dcaaaa946ed57cd

The type of `text` could be changed to `string | undefined`, forcing this case to be handled.

Another idea is to make the entire `doc` parameter `TextDocument | undefined`, but that would break the Codecov extension, which needs only the file path.

Any other ideas?

**Comment by sqs** [comment]
(For context, this was introduced by https://github.com/sourcegraph/sourcegraph/pull/2051.)
