### ISSUE TITLE
Support GitHub ACLs without GitHub configured as auth provider

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#2419]
$CUSTOMER would like to enable GitHub ACLs without using GitHub as the authentication mechanism to Sourcegraph. They are using a separate SSO provider.

The reason Sourcegraph currently requires GitHub to be configured for authn in order to turn on GitHub authz is we need to:
1. Reliably map Sourcegraph user IDs to GitHub user IDs
2. Compute GitHub user permissions.

For (1), the way we currently construct this mapping is by having the user authenticate through GitHub (which will also force the user to authenticate through whatever authentication provider GitHub requires) and then recording the user's GitHub OAuth credentials. Possible alternatives are:
* Assume username equivalency. Note: this might not be safe, because usernames are mutable on both GitHub and Sourcegraph. We could add an option to make them immutable on Sourcegraph if SSO is configured, but I'm still not sure about enforcing this on GitHub.
* Find some way via the GitHub API to look up a user by email or SSO ID. This doesn't appear to be possible via the REST API, but there might be something we overlooked here in the GraphQL API. We are ultimately constrained by what the GitHub API allows in terms of looking up users. (Note to $CUSTOMER: if you have a support line with GitHub folks, you can note that GitLab supports looking up users by *both* email and SSO ID, so this is not an issue for our GitLab integration.)

For (2), we use the OAuth credentials to see which repos a user can access. Due to limitations in the GitHub permissions API, this appears to be the only way to precisely compute a user's permissions (other code hosts like GitLab have a notion of `sudo` token which can be used to impersonate users, but GitHub doesn't have this feature). As an alternative, we could do the following:
* Implement permission computation by looking at what organizations a user belongs to on GitHub. Then we reverse-engineer GitHub permissions from org/team membership. We would err on the side of conservatism here, preventing access to some repositories a user might see on GitHub rather than risk leaking repo content to a user not authorized to see them.

The above changes would take 1-2 months to implement and fully test.

**Comment by bwitt** [comment]
@beyang was this issue closed due to it being implemented?  or WONTFIX?  or something else?  thanks!
