### ISSUE TITLE
Code Insights: Revisit accessibility on the dashboard page

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#24233]
### Background 
Usually, we care about accessibility in terms of voice-over and keyboard navigation and focus management but due to the fast evolution of code insight functionality last month we haven’t covered all things like voice-over support for drill-down filters, or live area for the dashboard page dashboard change. 

### Accessibility revisit things 

- Dashboard live area for the loading state of the dashboard page content
- Insights card component context menu (voice-over support with right aria labels)
- Drill-down button and filter panel element with [right aria labels for tooltip/popover element](https://www.w3.org/TR/wai-aria-practices/#tooltip)
- Dashboard insight card aria-labels (how many insights on the current dashboard, voice-over number of insight card among other cards on the page)

**Comment by unclejustin** [comment]
Duplicate now that we have dedicated accessibility issues.
