### ISSUE TITLE
Code Insights: Extract no opener link to a react component

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#24238]
## Context
At the moment we have enough places where we use a native link with no opener attr to redirect users to our doc site or any other external resource. 

```tsx
<a 
 href="https://css-tricks.com/snippets/css/a-guide-to-flexbox/" 
 target="_blank"
 rel="noopener noreferrer">

    Flexbox
</a>
```

To simplify all consumers that have this link consider extracting a no opener link in the separate component

**Comment by felixfbecker** [comment]
Is this issue really specific to code insights?

Btw we have linting in place that ensures the `rel` attributes are added for security :)

**Comment by felixfbecker** [comment]
@sourcegraph/frontend-devs I would suggest this is not worth doing given the number of tasks we already have this iteration and the small value we would gain from doing this (we have linting for `rel`, and with an external component devs would still need to remember to use that component, and it's not code-insights-specific). Taking a bias to action and moving it out of the iteration, but please feel free to challenge.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by thenamankumar** [comment]
@felixfbecker I feel adding the component for the no opener link won't do much good. Having a lint rule is enough.

Should we close this issue or do we need to add the required component?

**Comment by felixfbecker** [comment]
That's my viewpoint, but @vovakulikov filed this issue originally – @vovakulikov what do you think?

**Comment by limitedmage** [comment]
I agree that the linter rule is enough.

**Comment by limitedmage** [comment]
I thought we already have an eslint rule that does this? You can't set `target="_blank"` without also setting `rel="noopener noreferrer"` or something like that.

**Comment by vovakulikov** [comment]
@limitedmage I was thinking more about having eslint rule that enforces rel and target any time when we use the `Link` with a global `https://....` type of URL

**Comment by limitedmage** [comment]
Oh yeah, that would also be great!

**Comment by thenamankumar** [comment]
@vovakulikov can you create a separate issue for adding ESlint rule for the Link component?

Closing this issue.
