### ISSUE TITLE
Code Insights: Re-use form wildcard components 

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#24235]
## Context

Since some PRs from the frontend-platform team, we have some components in wildcard components that were copied from the code-insights code-base. To avoid different implementations of the same things we have to consider avoiding our own implementation of some logic or visual components and use our shared components. 

### List of re-useable components 

- Input: I couldn't find any refs to these. Just the exotic components below. - @unclejustin 
- [Button](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:insights+%3Cbutton&patternType=literal&case=yes) 
- [Checkbox](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:insights+%3Cinput+AND+type%3D%22checkbox%22&patternType=literal&case=yes)
- [Radio](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:insights+%3Cinput+AND+type%3D%22radio%22&patternType=literal&case=yes)
- [ForwardRefExoticComponent](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:insights+ForwardRefExoticComponent&patternType=literal&case=yes) types

**Comment by felixfbecker** [comment]
@sourcegraph/code-insights-frontend this issue is still in the last iteration milestone, what is the status of it? Do you want to make a case to include it in the next iteration, or to backlog it?

**Comment by unclejustin** [comment]
I would backlog it. When I started in on these it became apparent that the current state of the Wildcard components did not properly suit our use cases. This means that we need to update them, which is a larger task than just implementing them.
