### ISSUE TITLE
Code Insights: Improve charts with big number of lines

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#24240]
At the moment our chart doesn't look good or usable in case if this chart has a lot of data series 

<img width="396" alt="Screenshot 2021-08-23 at 17 23 00" src="https://user-images.githubusercontent.com/18492575/130463936-37031558-ee7b-4e8c-a532-ade8fd1bfca2.png">

We have to somehow change the insight card layout to fit content in a proper way to be able still to interact with the chart

**Comment by felixfbecker** [comment]
@AlicjaSuska are you actively working on this rn? Do you plan to work on it next iteration?
