### ISSUE TITLE
search contexts: iterate on single page design

### ISSUE THREAD

**Issue by novoselrok** [sourcegraph/sourcegraph#24272]
We want to bring search contexts pages closer to the current repogroup community pages (example: https://sourcegraph.com/stanford). This includes search examples (potentially an opportunity for search notebooks) and a search box.

**Comment by benvenker** [comment]
Leaving the context pages as they are for now, so that repogroups will just transition to contexts under the hood. Will open a new one with clearer set of steps for this.
