### ISSUE TITLE
cloud: syncing of personal repositories times out

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#24281]
![image](https://user-images.githubusercontent.com/187831/130611977-21be2045-33d1-42cb-a75b-16993a58f274.png)

The repositories are still added, but we are presented with this error. When trying to click away it says are changes are not saved.

I assume the root cause here is attempting to sync in a blocking fashion and timing out. This is a pretty bad user experience.

Myself and @stefanhengl can reproduce everytime.

@flying-robot assigning to you since you are on support for core app.

**Comment by indradhanush** [comment]
FYI, saw a similar error on dotcom for updating external service config. It looks related.
![image](https://user-images.githubusercontent.com/2682729/130808557-5c7e84c0-4071-42c9-808c-42848e4f8266.png)
