### ISSUE TITLE
Note that Beta is "free for now" [modal]

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#24298]
When we enable code insights by default in the product (planned for 3.32) we need to note to customers that it's not "Free forever" but that we can charge separately for the product (given the value it provides and the complexity to build!) 

Tracking ticket – PM, design, and marketing will need to work together on this, but the eng work itself will be minimal – a message somewhere on the insights pages/near the beta label, or a modal/overlay when you first view the insights pages.

**Comment by Joelkw** [comment]
From sales/gregg stone: 

> So long as we are super clear that it is in Beta and that they may lose access and/or be asked to pay for it, then it's OK on our end. The issues arise when these points are not clear or buried somewhere that nobody looks at.

**Comment by Joelkw** [comment]
Part of this is probably also a possible "education" moment, since some people will be landing on insights net-new. We might also want to encourage them in that message/screen to send us additional feedback.

**Comment by Joelkw** [comment]
[RFC is here now](https://docs.google.com/document/d/1FHwif1GU_3_-N69LLHo3N3OZKmQebdDy_zzHjJAXpQo/edit#heading=h.kct20jix194c)

**Comment by Joelkw** [comment]
@AlicjaSuska do you need anything more from me? Just know that if we want to put this in 3.32 we may need to start working on designs (or you may have already, in which case I apologize for the ping)!

**Comment by Joelkw** [comment]
Some quick test cases for this issue: 

- Do I see the modal if I am a new user who signs up after insights is "visible by default?"
- Do I see the modal if I am an old user who wasn't signed in when this is turned on? 
- Do I see the modal if I visit an insights page for the first time from the "1-click create insight from search" path (right to the creation form) rather than the "insights" nav bar item? 
- Do I see the modal if I am linked directly to a non-default dashboard? (not an "all [entity]'s insights" board)

**Comment by AlicjaSuska** [comment]
[Design](https://www.figma.com/file/TJ7utTjy5lythks77GrF9f/Beta-release-communication?node-id=1%3A1934) is ready for review @Joelkw @vovakulikov @felixfbecker
