### ISSUE TITLE
"Inline discussions" toggle doesn't indicate current state

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#243]
"Inline discussions" doesn't indicate current state. It is also unclear what it does at all. Perhaps a more descriptive tooltip would help with the latter.

![image](https://user-images.githubusercontent.com/754768/46421579-41e3e700-c6e7-11e8-96b3-5d5e69aee43d.png)

**Comment by nicksnyder** [comment]
Oh, I figured out what it does. You need to have a code discussion on the file (and visible) to know what it does. 

I did find a bug where it overlaps blame:
![image](https://user-images.githubusercontent.com/754768/46422109-799f5e80-c6e8-11e8-8b99-9f73f58ebbe0.png)

I don't think this visual treatment adds much since you really have to click to see the whole message anyway. I think it would be better if "inline discussions" were removed and there was just a persistent gutter icon (ideally on by default) for existing discussions on the file. Would greatly help discoverability of existing discussions.

**Comment by sqs** [comment]
Please file at https://github.com/sourcegraph/sourcegraph-code-discussions and close this :smile:

**Comment by nicksnyder** [comment]
https://github.com/sourcegraph/sourcegraph-code-discussions/issues/3
https://github.com/sourcegraph/sourcegraph-code-discussions/issues/4
https://github.com/sourcegraph/sourcegraph-code-discussions/issues/5
