### ISSUE TITLE
Extension registry: not finding extensions when searching by name

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#24301]
Repro: Go to https://sourcegraph.com/extensions?category=All&query=typescript.

Expected: there should be results, one of which is the `sourcegraph/typescript` extension.

Actual: no results (see screenshot).

This seems to be related to https://github.com/sourcegraph/sourcegraph/issues/22171 because I see the extension if I am in the `Programming languages` category (https://sourcegraph.com/extensions?category=Programming+languages&query=typescript). Recommended priority of fixing:

1. Make it so that searches in the `All` category work (it should search across all extensions; currently it is perhaps only searching extensions whose category is `All`, which means no extensions).
2. Address UX feedback in #22171 so that the behavior is clear when you have a non-`All` category selected and run a search. (I think it should probably not default to just searching within a single category, as that can be confusing.)

**Comment by sqs** [comment]
This bug is still around, and it seems fairly serious (most searches on the extension registry UI will incorrectly show no results). @tjkandala @Joelkw

**Comment by muratsu** [comment]
We're currently working on fixing [this](https://github.com/sourcegraph/sourcegraph/issues/24157) issue. Once it's fixed this issue is next in line.
