### ISSUE TITLE
Code intel not working on private TypeScript repo

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#24302]
On my private repo https://sourcegraph.com/github.com/sqs/aviation (I am fine "leaking" this repo name in this public issue, this is just a fun hack project):

1. With `"codeIntel.lsif": true` in my user settings, I see no hovers on tokens. I do not have LSIF data uploaded, but I expect it to fall back to search-based code intel. It does not. The GraphQL LSIF response just has a null value.
2. With `"codeIntel.lsif": false` in my user settings, only a few tokens have hovers. Most do not. For example, at https://sourcegraph.com/github.com/sqs/aviation@3228c0988f27850e846585e09bebd9c03f95ff3c/-/blob/web/src/serve.tsx?L7 the `const entrypointHTML` symbol has no hover, even though a [similar symbol in another (public) file](https://sourcegraph.com/github.com/cypress-io/cypress@2a80c137d9e086193200d4497b7a04ce81ecf1e7/-/blob/packages/extension/gulpfile.ts?L11:7) has a hover.

I am happy to grant anyone access to this private repo to debug it. (Again, the repo is not sensitive in any way, so I don't mind leaking its name or filenames in the URLs linked above.)

**Comment by varungandhi-src** [comment]
We no longer support private repos on Sourcegraph.com, and we generally do have auto-indexing working for popular TypeScript repos on Sourcegraph.com, so closing this for now.
