### ISSUE TITLE
Webhook not setup banner

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#24310]
### User problem
Nearly every new customer contacts support, reporting that their changesets are not syncing. In the vast majority of cases, their site admin has not setup webhooks. Even some older customers still have not setup webhooks, resulting in [degraded performance](https://docs.sourcegraph.com/batch_changes/references/requirements#batch-changes-effect-on-code-host-rate-limits), and changesets taking up to 8 hours to update versus updating nearly immediately with webhooks.

Users report not knowing about webhooks, or forgetting to set them up. Once instructed to do so, customers successfully setup notebooks. The webhook setup flow is not great, and we have a proposal to fix it, but the primary root cause is that site admins _don't know_ about webhooks.

### Proposed change

[Figma](https://www.figma.com/file/w8O8L0I0k2I5J2qHtqBz0d/webhooks-warning?node-id=0%3A1) | Draft docs page https://github.com/sourcegraph/sourcegraph/pull/25558

If webhooks are not setup for any given codehost connected to the instance:
- non site admin users see a banner on batch changes pages, informing them that changesets are likely not up to date because webhooks are not setup. This banner points to the webhooks docs page, which explains to users they need to ask a site-admin to setup webhooks.
- site admin get a banner, with a link to the docs, and a list of codehosts to configure linking to the codehost config page
- site admins can explicitly opt-out of the webhooks warning for a codehost (in case some organisations have policies against webhooks), by setting a site admin flag. In that case, the banner doesn't show anymore for any user.

- regardless of site admin settings, users see additional [hints](https://www.figma.com/file/w8O8L0I0k2I5J2qHtqBz0d/webhooks-warning?node-id=32%3A2204) if webhooks are not setup

**Comment by malomarrec** [comment]
What about customers with multiple codehosts? Do we pop a banner as long as only one connected codehost doesn't have webhook? It could be a very rarely used codehost, or a codehost that is not used with batch changes. @rrhyne WDYT?

**Comment by malomarrec** [comment]
Possible simplification to not blow scope: if an instance has 0 codehost setup, we show the banner. If an instance has at least one webhook setup, we don't.

**Comment by rrhyne** [comment]
I think that could lead to a lack of trust. Some changesets won't be up to date and it'd be difficult trying to figure out why, especially if I saw the warning once, but I'm not getting it now.

**Comment by malomarrec** [comment]
https://github.com/sourcegraph/accounts/issues/8194

**Comment by rrhyne** [comment]
First take:

https://www.figma.com/file/w8O8L0I0k2I5J2qHtqBz0d/webhooks-warning?node-id=0%3A1

**Comment by malomarrec** [comment]
Draft docs page:
https://github.com/sourcegraph/sourcegraph/pull/25558

**Comment by malomarrec** [comment]
The current design implies that the warning will show as long as there's _at least one_ codehost without webhooks.
In that case, if an instance has GitHub and GitLab, and webhooks are only setup for GitLab, users will still see the warning.
The site-admin can go and opt-out of the warning (for example: GitHub is not used with Batch Changes, don't want to setup webhooks)

Should the "opt out of warning" be a global setting, or a codehost specific setting? I see two conflicting user stories:

1) An instance has 3 codehosts setup, the site admin wants to opt-out of webhooks, it's less work if the opt-out is global.
2) An instances has GitHub and GitLab setup, site-admin adds webhook for GitHub, then disables the warning because they don't care about GitLab. They add a second GitHub#2 instance. In that scenario, it's better if the warning pops-up again.

So overall, given we want to optimize for making sure users _know_ they should setup webooks, sounds like `disableWebhooksWarning` should be a property of the external_services pages, and not a global setting.
Thoughts @sourcegraph/batchers ?

**Comment by eseliger** [comment]
I think we could make it a per-codehost thing, and add it to the batch changes settings page. That way, admins can explicitly opt-out per detected code host. If we find that too much work for now, the global flag could work.

One thing with GitHub.com (and perhaps other public code hosts, too - need to figure this out) is that you cannot have a _global_ webhook set up, so if you want to use webhooks with your personal account, I think you'd need to configure webhooks multiple times(?). Given that, we can never really tell for sure if _all_ cloned repos are covered by webhooks, if there is at least one webhook configured for the code host. Difficult 🥴

**Comment by malomarrec** [comment]
Got it. 
So when we deprecate the codehost token, and sync only with the PAT, each user will have to add a webhook? If that's the case, I think we may need to revisit that because that'll be a lot of config in the hand of each individual user ...

**Comment by eseliger** [comment]
No, it's not that bad, they don't _need_ to do that; we can have global webhooks _without_ global service accounts.
