### ISSUE TITLE
Codehost webhooks setup wizard

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#24312]
### User problem
Setting up webhooks is hard. There are many steps and failure points and the docs are confusing. The site-admin json input form does not help.

This is not urgent, as the main root cause for users not setting up webhooks is that they don't know about it #24310. Once aware, they manage to get through the process. In the long run though we'd like to make it really easy for site-admin to setup webhooks.

### Proposal

- A webhook wizard helps users setup and validate codehost webhooks
- When webhooks are not setup for a codehost, visual cues alert admins

<img width="1134" alt="webhooks-wizard" src="https://user-images.githubusercontent.com/25070988/130800624-fdae8d46-3caa-4d96-a8d6-7280656ed1ef.png">

**Comment by malomarrec** [comment]
Related: https://github.com/sourcegraph/sourcegraph/issues/25400

**Comment by courier-new** [comment]
Related: https://github.com/sourcegraph/sourcegraph/issues/41096

**Comment by courier-new** [comment]
Related: https://github.com/sourcegraph/sourcegraph/issues/42028.
