### ISSUE TITLE
Code Insights: Tooltips overlaying other elements when you scroll down on pages

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#24340]
## Background
I think at the moment we don’t have any system behind tooltips and popover layers at all. This leads us to the visual bugs below and similar overlapping for other elements like this.
The culprit here is that all tooltips and popovers which are built by reach UI use portals and there is no way to set some targeted element for rendering tooltips or boundary elements to avoid overlapping. I’ve been thinking about this for a while and I think we should come up with our own version of tooltips or make a PR to the reach ui popover package to solve this problem

![image](https://user-images.githubusercontent.com/18492575/130926717-6c6a3e20-790c-4048-b009-b5288c3c5326.png)

![image](https://user-images.githubusercontent.com/18492575/130926701-a28171ad-d52a-4f1a-b2ab-d4e0d9e104a3.png)

---

Edited: @unclejustin 

The issues described above are two separate issues. The tooltips are using [ReachUI](https://reach.tech/menu-button/#menupopover) but the graphs are using [XYChart](https://airbnb.io/visx/docs/xychart). So the solutions will be similar, but different.

**Comment by unclejustin** [comment]
@felixfbecker I estimated this one at 3 days, but I have little confidence in that estimate. The issue is somewhere in the VisX library. I am unsure that we can work around it.

**Comment by unclejustin** [comment]
Tooltips have been rebuilt and original case has been fixed.
