### ISSUE TITLE
10 second delay between clicking "Edit" on an insight and the edit UI appearing

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#24348]
I'm seeing a 10 second delay between clicking "Edit" on an insight and the edit UI appearing, on any insight. The URL already has the new value, but the UI is frozen. I didn't see this last time I tested.

https://user-images.githubusercontent.com/10532611/130974719-43265248-434e-4a29-a097-725aa452d9ee.mov

Looking at the Performance tab, I see a lot of Forced Reflows/Recalculate layout.

Browser: Chrome 92.0.4515.159

**Comment by vovakulikov** [comment]
I think we can close it since nobody hasn't seen this problem in the past 5 months. @unclejustin wdyt?

**Comment by unclejustin** [comment]
@vovakulikov agreed. Especially since we've changed so much under the hood in that time.
