### ISSUE TITLE
insights: flag query as dirty if it is terminally 'failed'

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#24358]
To generate an insight data series, search queries are queued for (repository, time) tuples. The queries are processed asynchronously in the background from a table that serves as the queue. The states that the records can move in is as follows:

`queued -> processing -> completed`
`queued -> processing -> errored`
**`queued -> processing -> failed`**
`errored -> processing -> errored`
**`errored -> processing -> failed`**

There are two paths that result in a terminal state of `failed` which has the semantic that the record has exceeded the retry policy and is considered unprocessable.

It will be useful to inform users that their insight has potentially misleading values. A table exists called `insight_dirty_queries` that is used to record queries that were not wholly successful. We should [mark](https://sourcegraph.com/-/editor?remote_url=git%40github.com%3Asourcegraph%2Fsourcegraph.git&branch=main&file=enterprise%2Finternal%2Finsights%2Fstore%2Finsight_store.go&editor=JetBrains&version=v1.2.1&utm_product_name=GoLand&utm_product_version=2021.1.3&start_row=98&start_col=34&end_row=98&end_col=34) any queries that [enter](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/workerutil/worker.go?utm_product_name=GoLand&utm_product_version=GoLand&utm_source=JetBrains-v1.2.1#L308:41) the `failed` state as dirty and expose `reason` metadata describing as much of the problem as possible.

**Comment by leonore** [comment]
closing this until we get user feedback on whether they actually need better surfacing of these errors
