### ISSUE TITLE
Diff and commit message search type examples are effectively broken on cloud

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#24393]
When clicking either example, the search fails because too many repos are being searched.

We should modify the examples to include more filters so that results are returned, or we should simply add `type:diff` or `type:commit` to the search box and not run the search

**Comment by rrhyne** [comment]
Which example is this?

**Comment by benvenker** [comment]
@rrhyne the diff and commit examples here:
![image](https://user-images.githubusercontent.com/4605817/131889984-53fc4d19-18da-4f49-9729-656ffe336973.png)

For clarification, this is when searching in the global context. If I'm in my personal context they work.

**Comment by rrhyne** [comment]
Ah... this is not an example, but a search 'helper' if you will. An example would be what is shown on the search homepage for unauthenticated users. 

What you are actually saying is that diff and commit search at **scale** does not work as well as it could, but the limits we have set and speak to in the message will get you a performant diff or commit search. 

That said, this is known and is the focus of @camdencheek's efforts to improve perf. He has an interesting RFC you should read on improving. One other note, this impacts code monitors, thus the efforts to improve performance.

**Comment by benvenker** [comment]
Got it, thanks for the context.
