### ISSUE TITLE
Should I see the repo panel in search results when I didn't use exact match on repo?

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#24394]
When I [this](https://sourcegraph.com/search?q=context:global+type:commit+dang+repo:facebook/react&patternType=literal) search, I don't see the repo pane even though there are multiple repos that appear in the search results.

**Comment by rrhyne** [comment]
Yes, you should have.

**Comment by fkling** [comment]
Confirmed that there are no `repo:` filters returned from the server. This is the payload of the `filters` event:

```
[{"value":"archived:yes","label":"archived:yes","count":1,"limitHit":false,"kind":"dynamic"}]
```

Passing over to @sourcegraph/search-core

**Comment by tsenart** [comment]
@stefanhengl: Added to the support board.
