### ISSUE TITLE
Customizing Sourcegraph appearance

### ISSUE THREAD

**Issue by KattMingMing** [sourcegraph/sourcegraph#2439]
### Feature request description

Enterprise customers would like the ability to customize the appearance of the authentication page and search homepage.

User's have expressed that this will:
- Help site admins feel more comfortable sharing Sourcegraph because the unauthenticated page can communicate value / purpose of Sourcegraph prior to authenticating.
    - End users will feel more comfortable authenticating on company branded login pages. Specifically when authenticating via code host.
- For instances that allow unauthenticated users, customizing the search page will help communicate the purpose of Sourcegraph by emphasizing it's for internal code search.

Additionally, Sourcegraph instances should have their own `/welcome` page that can be customized by site admins. (TODO link issue)

#### Implementation (WIP)

It's already possible for users to inject a custom stylesheet via `htmlHeadTop` (https://docs.sourcegraph.com/admin/config/critical_config). Customizing the appearance could be done through additional site config properties.

### Documentation updates
Below are the necessary changes to documentation

#### Changing the appearance of the login page and homepage

Sourcegraph offers a way to put your company’s identity on the login page and homepage of your Sourcegraph instance.

By default, the page shows the Sourcegraph logo.

<img width="1792" alt="screenshot 2019-02-25 12 02 32" src="https://user-images.githubusercontent.com/4897310/53366605-d8b07a80-38f8-11e9-99ae-d33bea80d328.png">

#### Changing the appearance
Navigate to the *site-admin/configuration* page to customize the appearance by updating your site configuration.

```
branding: {
	light: {
		logo: "<url_to_logo>",
		favicon: "<url_to_favicon>",
	},
	dark: {
		logo: "<url_to_logo>",
		favicon: "<url_to_favicon>",
	},
	auth: {
		header: "The header text used on the authentication page"
		subtitle: "This message appears on the authentication page of your Sourcegraph instance."
	}
}
```

**Comment by sqs** [comment]
Tentatively prioritizing for 3.3

**Comment by felixfbecker** [comment]
> It's already possible for users to inject a custom stylesheet

This would not work anymore when we start using shadow roots. Is that an issue? What exactly do customers want to customize?

**Comment by KattMingMing** [comment]
Resolved in https://github.com/sourcegraph/sourcegraph/pull/2876 – This change does not include allowing for CSS customizations. As @felixfbecker pointed out that is more complicated and so the scope of this was to allow branding customizations.
