### ISSUE TITLE
Search "times out" but results are returned

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#24392]
Some searches are timing out on Sourcegraph Cloud when there are, in fact, plenty of results returned. See [this search](https://sourcegraph.com/search?q=context:global+type:commit+repo:%5Egithub%5C.com/facebook/react&patternType=literal).

![image](https://user-images.githubusercontent.com/4605817/131228786-62d064ad-f7ec-4791-a7a8-ec3c3b0163ed.png)

**Comment by camdencheek** [comment]
This should be fixed now that https://github.com/sourcegraph/sourcegraph/pull/24376 is merged (<24hr ago). I think it's safe to close this

**Comment by benvenker** [comment]
OK, closing.
