### ISSUE TITLE
Too many matching repositories for commit search to handle

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#24391]
This message is frustrating and it would be nice to do better here. If we're limited to only 50 repositories at a time, would it be possible to use our star ranking to pluck the top 50 repositories by star ranking, run the search, and then provide the user with a similar message to what we have now, but indicating how we got the result set?

![image](https://user-images.githubusercontent.com/4605817/131228717-a17bcc20-6275-4152-b528-abbc2bd18e68.png)

**Comment by camdencheek** [comment]
Commit search now has no limit to the number of repositories it can search. The only limit is the timeout, which can still be hit because commit/diff search is slow.
