### ISSUE TITLE
Native bitbucket.org integration (instead of adding repos one-by-one)

### ISSUE THREAD

**Issue by linknum23** [sourcegraph/sourcegraph#244]
What are your plans to support cloud access to bitbucket.org? Does it already work but is undocumented?
I naively attempted to setup bitbucket,org as a Bitbucket Server and this failed. If this is already supported do you have any documentation on how to configure it. 

In case it is relevant, below is the error that happens when attempting to connect to bitbucket.org:
repo-updater | t=2018-10-03T16:00:18+0000 lvl=eror msg="failed when listing Bitbucket Server repos" url=https://bitbucket.org/ error="Get /account/signin/?next=/account/signin/%3Fnext%3D/account/signin/%253Fnext%253D/account/signin/%25253Fnext%25253D/account/signin/%2525253Fnext%2525253D/account/signin/%252525253Fnext%252525253D/account/signin/%25252525253Fnext%25252525253D/account/signin/%2525252525253Fnext%2525252525253D/account/signin/%252525252525253Fnext%252525252525253D/account/signin/%25252525252525253Fnext%25252525252525253D/rest/api/1.0/repos%2525252525252525253Flimit%2525252525252525253D100: stopped after 10 redirects"

**Comment by sqs** [comment]
Thanks for filing. Sourcegraph only has first-class support for Atlassian's Bitbucket Server (formerly known as Stash).

To use Sourcegraph with Bitbucket Cloud (bitbucket.org) repositories, just follow the [docs for adding Git repositories from other code host](https://about.sourcegraph.com/docs/config/repositories/#sync-repositories-from-any-code-host).

(This is less convenient since you need to add repos individually, but it still works. We would like to improve the experience for Bitbucket Cloud in the future, and we'll track progress on this issue.)

**Comment by heyoni** [comment]
HI @sqs, do you know setting it up this way allows will work with the chrome extension?

And any tips for setting up authentication? Can I use the other auth headers for oauth2 and use my sourcegraph instance as my app callback address?

Thanks!

**Comment by nicksnyder** [comment]
@Unknwon The task here is to create a [Source](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/repo-updater/repos/sources.go#L80) for Bitbucket Cloud. You can look at examples for how this interface is implemented for other code hosts (e.g. [GitHub](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/repo-updater/repos/github.go?#L25)). If you have any questions, don't hesitate to ask here or in Slack/Zulip.

**Comment by Unknwon** [comment]
Progress:
- [x] Initial version: List all user repositories found
- [ ] List all team repositories found
- [ ] Make all parameters work
- [ ] Add test cases

**Comment by tsenart** [comment]
@Unknwon: Great to have you help us out. We'd love to give you in depth feedback so smaller, more incremental PRs are greatly appreciated!

**Comment by Unknwon** [comment]
Update: It is not 100% completed according to implementation plan, but initial support for Bitbucket Cloud has been merged to `master` branch and should cut with next 3.6 release branch.

Currently, this initial version supports lists all personal and selected teams' repositories. Filtering-related parameters will be added soon.

**Comment by nicksnyder** [comment]
> It is not 100% completed according to implementation plan

What implementation plan are you referring to?

> Are you planning to do this work?

Filtering-related parameters will be added soon.

**Comment by Unknwon** [comment]
@nicksnyder 

> What implementation plan are you referring to?

I'm referring to https://github.com/sourcegraph/sourcegraph/issues/244#issuecomment-508893569, basically add more parameters to match other external services, e.g. `repositoryQuery`, `repos`, `exclude`, etc.

> Are you planning to do this work?

Yes, but my main focus this week should be the LSIF Go exporter related work.

**Comment by unknwon** [comment]
Hi @linknum23, thanks again for the feedback!

I'm going to close this issue in favor of https://github.com/sourcegraph/sourcegraph/issues/5151. Please comment on that issue if you have further feedbacks.
