### ISSUE TITLE
Customize appearance of /welcome page

### ISSUE THREAD

**Issue by KattMingMing** [sourcegraph/sourcegraph#2443]
#### Feature request description

Sourcegraph instances should have their own /welcome page that can be customized by site admins. Customizations should include adding company logo, header text, and site admin contact information. 

To successfully onboard new teammates site admins should only need to send one link to their team. https://sourcegraph.mycompany.com/welcome

Right now, site admins lack one URL to send to their team that:
- Communicates the value of Sourcegraph
- Demos and describes product features
- Provides links to documentation.
- Includes their instance URL

Educating new users typically requires 3 types of links to be sent:
1. Base URL to their instance (https://sourcegraph.mycompany.com).
    - The search homepage and unauthenticated page lacks critical product education so additional resources are necessary to share. (Related: https://github.com/sourcegraph/sourcegraph/issues/2439)
2. docs.sourcegraph.com
3. sourcegraph.com/welcome

(Reference image for /welcome on Sourcegraph.com)
<img width="1792" alt="screenshot 2019-02-25 13 26 00" src="https://user-images.githubusercontent.com/4897310/53370211-03530100-3902-11e9-842f-fa3c47c4aaf6.png">

**Necessary changes for Sourcegraph instances (not Sourcegraph.com) include:**

- Remove customer logos
- Replace deploy self-hosted Sourcegraph button with a "Sign in" button (this page should be accessible to authenticated and unauthenticated users)
- Add company favicon to header next to Sourcegraph logo (Sourcegraph logo + My Company logo)
- Let site admin's customize content
    - Either by adding an additional section or overwriting our copy.
    - #2959  does this for the homepage, not yet the welcome page
- Show site admin contact information if specified in config (https://github.com/sourcegraph/sourcegraph/issues/2442)
- Keep demo gifs

**Comment by sqs** [comment]
Added mention of #2959, which does some of this for the homepage (not yet the welcome page)

**Comment by francisschmaltz** [comment]
This should be a part of a designed /welcome page - not an add-on to the current page.
