### ISSUE TITLE
Think about GitOps for SSBC

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#24453]
I think some customers currently do a GitOps based approach for Batch Changes. I think this is a perfectly valid model, and we should make sure we thought about how we can support it ideally until beta so we can at least have a paragraph in the docs about it.

**Comment by malomarrec** [comment]
+1, also see [PD 26 APPROVED: server side batch changes](https://docs.google.com/document/d/1MnfaA9P7mtur7aQbMvy2x96_zy_IrOhY-MbGUo5I5wk/edit#bookmark=id.n96hjtyfqvdz)
