### ISSUE TITLE
Code Insights: Add dashboard flow integration tests

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#24455]
## Context
We have already implemented some of our missing integration and unit tests for the Code Insights pages. In this ticket, we should add another part of the needed tests in order to increase code coverage and therefore our confidence for regression testing. 

## Missing integration tests 

- [ ] Backend insight card loading layout test
- [ ] Dashboards flow (create, delete, update dashboard visibility)

**Comment by felixfbecker** [comment]
@sourcegraph/code-insights-frontend  what is the estimate of this?

**Comment by felixfbecker** [comment]
@unclejustin what's your size estimate of this for this iteration?

**Comment by unclejustin** [comment]
1 already in review, thanks for the ping!
