### ISSUE TITLE
URL shortening for the public instance

### ISSUE THREAD

**Issue by strumlovesgorm** [sourcegraph/sourcegraph#24452]
#### Feature request description

- A shortened URL for the public instance to make sharing URLs easier.
- Example : https://sourcegraph.com/github.com/golang/go/-/blob/src/net/http/httptest/httptest.go#L41:6&tab=references being shortened to something like https://src.gr/GxOyRzM

#### Is your feature request related to a problem? If so, please describe.

- Nah

#### Describe alternatives you've considered.

- Using third party URL shorteners?

#### Additional context

- I notice srcgra.ph being owned by Sourcegraph. Something shorter than that would be even better. Also, GORM <3

**Comment by unknwon** [comment]
@sqs IIRC you once tweeted about a URL shorten domain/service that would expands to sourcegraph.com URLs?

**Comment by sqs** [comment]
@unknwon We own https://cs.dev and other similar domains, but they aren't general-purpose URL shorteners. `https://cs.dev/foo` redirects to a Sourcegraph.com query for `foo`.
