### ISSUE TITLE
Find implementations for Go

### ISSUE THREAD

**Issue by scalabilitysolved** [sourcegraph/sourcegraph#24479]
- [x] Merge https://github.com/sourcegraph/lsif-go/pull/199
- [x] Merge https://github.com/sourcegraph/sourcegraph/pull/24854
- [x] Publish a new `sourcegraph` npm package
- [x] Merge https://github.com/sourcegraph/code-intel-extensions/pull/683
- [x] Update GH action Docker image to lsif-go@1.7.0
- [x] Fix browser extension https://github.com/sourcegraph/sourcegraph/issues/27239 (need to wait until the next release on Nov 22)
- [x] Post in `#code-intel`
- [ ] Tweet

**Comment by jyavorska** [comment]
@macraig can you please add a (conservative) estimate for when this will be delivered? Doesn't need to be exact, and it can change, but it's for the roadmap view at https://github.com/orgs/sourcegraph/projects/214/views/11.

**Comment by macraig** [comment]
@jyavorska the feature shipped in 3.34. The pending items aren't blocking usage so I've updated the roadmap view and marked it as Done. If you think it should remain In Progress until all the items are done and this issue is closed let me know and I'll be happy to switch it back.

**Comment by jyavorska** [comment]
I think it's fine @macraig it's most important that it makes sense to you and the team.

**Comment by nicksnyder** [comment]
Since this is marked as done, can this issue be closed?
