### ISSUE TITLE
Use Apollo client for GraphQL queries in data retention UI.

### ISSUE THREAD

**Issue by scalabilitysolved** [sourcegraph/sourcegraph#24478]
Given the context here -> https://github.com/sourcegraph/sourcegraph/pull/24095#discussion_r695522113

Frontend platform are moving to use Apollo client for all GraphQL queries.  With the recent work in our data retention UI (see link above for additional context) we should also conform to this.

**Comment by Numbers88s** [comment]
@efritz That is all of them. Last one was https://github.com/sourcegraph/sourcegraph/pull/25709
