### ISSUE TITLE
insights: migrate code insights backend pings

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#24481]
Some code insights pings [currently interact with the insight definitions](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/usagestats/code_insights.go?L137-195) stored in user settings directly. As we migrate away from settings to an API, we need to ensure we migrate these pings.

**Comment by CristinaBirkel** [comment]
This is covered by https://github.com/sourcegraph/sourcegraph/issues/27214
