### ISSUE TITLE
User report: tapping search bar on iPad doesn’t bring up keyboard 

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#24493]
On Sourcegraph.com. Seeking additional repro steps. Via https://twitter.com/lachlanjc/status/1432964734932766720

**Comment by malomarrec** [comment]
Unclear which team this belongs to, tentatively assigning to frontend-platform. If it's not the right move, let me know!

**Comment by valerybugakov** [comment]
@malomarrec, IIRC the search input is owned by the @sourcegraph/search-product. Correct me if I'm wrong here.

**Comment by limitedmage** [comment]
I was able to repro this on my iPad. It seems this has something to do with autofocus. Here's a workaround that worked for me: tapping anywhere outside the search box to unfocus, and then tapping inside the search box to focus again.

**Comment by camdencheek** [comment]
Failed to reproduce on the latest sourcegraph.com. We've made various changes to autofocus, so I think it's safe to say this was likely fixed along the way.
