### ISSUE TITLE
Use /data volume for Coursier cache for JVM dependencies

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#24502]
Currently, gitserver and repo-updater use the default Coursier cache directory in `$HOME/.cache/coursier`. We should put the cache under the /data volume instead. It's possible to customize the cache directory through the environment variable `COURSIER_CACHE`.

cc/ @tsenart what exact directory should we use for the cache?

**Comment by tsenart** [comment]
`/data`, check our gitserver.StatefulSet.yaml manifests in prod (and dogfood, and deploy-sourcegraph)
