### ISSUE TITLE
Cache search results so clicking the back button after clicking on a search result does not execute the search again

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#24523]
Flow:

1. Execute a search and wait for results
3. Click a result.
4. Read the result, realize it's not what you're looking for. Click back button to back to results.

Current behavior:

Search runs again and you have to wait for results again, which depending on the search may take a long time (eg. unindexed searches). Because we don't have consistent sorting, results may not be in the same order as before.

Suggested behavior:

Results for the last query are cached so going back to the results page shows the same results. This should only happen if the search completed successfully.

**Comment by limitedmage** [comment]
@benvenker  We've discussed this in the past but not sure if an issue already exists for this, if so, please close this as duplicate. I'm putting this in "Next" in case we have the bandwidth for it next iteration.

**Comment by benvenker** [comment]
@limitedmage I don't see a duplicate so this one is good to go.
