### ISSUE TITLE
Remove the code insights experimental feature flag (turn code insights on by default)

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#24538]
We are in beta!! If no major issues arise in 3.31 with customers we should be confident to turn insights on by default. 

Like other prior "remove the flag" tickets, this is a tracking ticket and can be started – but should not be merged – without explicit approval at time of merge from @joelkw .

**Comment by Joelkw** [comment]
@felixfbecker @vovakulikov @unclejustin when we make this change, I want to further specify that we should **reverse this flag** rather than remove it. @abschu brought up the good point there are cases when we might still want an "off switch," either because the customer for some reason doesn't want to try the beta or the CE/AE thinks it's not a good moment (eg, close to a renewal, or the customer is super sensitive to bugs and using a beta will frustrate them). 

Could we also change the name/placement of the flag, in that case? It's not an "experimental feature" anymore, though if it makes sense to leave it in the experimental features section, that's okay (ideally, perhaps we have a "betaFeatures" : {}" object and can move the flag there?)

**Comment by Joelkw** [comment]
One more note: we should also make sure that "Insights" only shows up in the navbar if you're logged in (otherwise you get a 404 page). I think that'd be the case anyway but just wanted to confirm. This isn't really an issue for customers but might be an issue for dotcom, for example.

**Comment by Joelkw** [comment]
@vovakulikov can we close this issue given [this PR](https://github.com/sourcegraph/sourcegraph/pull/24970)?

**Comment by vovakulikov** [comment]
@Joelkw Yes. Not sure why merging this PR didn't close this issue as well.

**Comment by felixfbecker** [comment]
@vovakulikov I think it's because you listed them with commas and didn't repeat the "Closes" prefix :)
