### ISSUE TITLE
Account removed from dogfood

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#2454]
Something weird happened and my account disappeared from dogfood. Tomas checked if I existed in the admin interface and I had gone. Not sure if this was a weird ops mistake, or some changes to the github auth code which you did recently.

```
No user exists matching any of the verified emails: keegan.csmith@gmail.com, keegan@sourcegraph.com.

First error was: User account with verified email "keegan.csmith@gmail.com" does not exist. Ask a site admin to create your account and then verify your email.
```

**Comment by ggilmore** [comment]
We dropped the postgres database when we were testing the postgres upgrade process iirc. Did you create a new user account after that?

**Comment by keegancsmith** [comment]
I thought I had used it recently, but I had not. My last visit was which wasn't a sign-in page was January 21st! I've obviously been relying on sourcegraph.com since our code is now public.
