### ISSUE TITLE
Performance comparison of git2go and git-rs

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#24596]

**Comment by camdencheek** [comment]
For the purpose of diff search, which is the primary thing we're optimizing for here, the difference between the two is negligible. The runtime is dominated by generating the diff, so until we've come up with a fix for that, optimizing away cgo overhead doesn't gain us much. I'd love to get to the point where that matters 😄

**Comment by unknwon** [comment]
@camdencheek I'm curious which direction are we going forward? git-rs or stick with what we have currently?

**Comment by camdencheek** [comment]
"What we have currently" is shelling out to git CLI. I'm currently working on using git2go (go bindings to libgit2) for diff and commit search. There were some questions about the performance overhead of cgo, and whether the rust bindings would be considerably faster than the go bindings because of that, so I wrote diff search in go and rust to test performance differences. I'll be continuing to move in the direction of using git2go instead of adding a new Rust service.
