### ISSUE TITLE
Add in product CTAs to the Cloud app

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#24591]
## Problem statement

The cloud application is not yet suitable for enterprise use. Where there are deficiencies, we should promote the private installation. Along with this, we should include links to where users can learn more and get help installing.

## Success criteria

1. Design is updated [accordingly](https://www.figma.com/file/IgD7ZzmNt4Un2nqkk1u1X4/Self-hosted-CTAs-in-the-Cloud-product?node-id=214%3A657) in three primary locations where CTAs could be useful to users looking for more functionality:
    - Repositories page
    - Code hosts page
    - Organizations
2. ["Need help getting started"](https://www.figma.com/file/IgD7ZzmNt4Un2nqkk1u1X4/Self-hosted-CTAs-in-the-Cloud-product?node-id=212%3A466) block is implemented as a reusable React component.
    -  Note, that we already have a similar block with gradient border here: `client/web/src/search/home/SelfHostInstructions.tsx`. It should be extracted into a reusable component and placed under `client/web/src/components`.
    - `--marketing-gradient` CSS variable declaration should be moved to `client/branded/src/global-styles/colors.scss`
    - As a result, we will have two reusable components: `<MarkeringBlock />` with gradient border and spacing and `<SelfHostedCTA />` with a "Need help getting started" message that uses `MarkeringBlock` internally.
3. All metrics specified in mockups are captured using `telemetryService.log(eventName: string, eventProperties?: any)` method.
4. The [Wildcard component library](https://docs.sourcegraph.com/dev/background-information/web/wildcard) is used in combination with [global styles](https://github.com/sourcegraph/sourcegraph/blob/main/client/branded/src/global-styles/GlobalStylesStory/GlobalStyles.story.tsx) to implement UI.

### Implementation details

- Repositories page
    - URL: `users/:username/settings/code-hosts`
- Code hosts page
    - URL: `users/:username/settings/repositories`
- Organizations
    - Create a new React-router route: `/organizations/about` with the corresponding component.
    - Implement design specified [here](https://www.figma.com/file/IgD7ZzmNt4Un2nqkk1u1X4/Self-hosted-CTAs-in-the-Cloud-product?node-id=214%3A657) for the new route.
    - Use new route to change a link from "+ New organization" to "About organizations" in `client/web/src/user/settings/UserSettingsSidebar.tsx` if `window.context.sourcegraphDotComMode` is true.
    - `window.context.sourcegraphDotComMode` stands for "Cloud" mode of the Sourcegraph web application.

## Figma file with designs and metrics capture:
https://www.figma.com/file/IgD7ZzmNt4Un2nqkk1u1X4/Self-hosted-CTAs-in-the-Cloud-product?node-id=0%3A1

### Example:
![image](https://user-images.githubusercontent.com/539268/132011336-54114e97-e912-4d66-985c-392ca1b470d3.png)

**Comment by gitstart-sourcegraph** [comment]
@valerybugakov  

1. Could you describe in detail the requirement: "This panel should fill the remaining space in the container"?
2. For new route "/organizations/about",  we are going to keep `UserSettingsSidebar` on new page, is the right thing?

<img width="1436" alt="Screenshot at Sep 22 23-31-02" src="https://user-images.githubusercontent.com/89894075/134384468-ed7a22f1-e3ff-4dc3-82f6-78ecd3f4b152.png">

**Comment by rrhyne** [comment]
I updated the card in question. The note is saying, "Need help getting started" should be the width of the content
and the other text should expand horizontally to fill the remaining space in the container.
