### ISSUE TITLE
Use ESLint

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#2461]
ESLint has TypeScript support and is the future of TypeScript linting (TSLint will eventually be deprecated). It has a bunch of rules (like not referencing `this.state` in `setState()`) that I would like to enable because they keep coming up in code review.

**Comment by sqs** [comment]
More info: https://github.com/palantir/tslint/issues/4534 and https://medium.com/@oliver.grack/using-eslint-with-typescript-and-react-hooks-and-vscode-c583a18f0c75

**Comment by JoshuaKGoldberg** [comment]
You mentioned in #4486 that you rely on some TSLint rules that haven't been migrated over yet. Are there any ones in particular? I'd love to help target those first in typescript-eslint to assist in the move. 😊

**Comment by christinaforney** [comment]
Thanks for the offer to help @JoshuaKGoldberg ! @felixfbecker or @sqs can you help out with this info?

**Comment by sqs** [comment]
- Our standard tslint config is at https://sourcegraph.com/github.com/sourcegraph/tslint-config/-/blob/tslint.json
- We have a custom [`banImportsRule`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/shared/dev/tslint/banImportsRule.ts)
- Our other main tslint.json files are at https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+f:tslint.json

Maybe eslint already has all these things. If so, great! It probably won't be too much work to switch regardless.

**Comment by felixfbecker** [comment]
@JoshuaKGoldberg I think what would help us the most is an automatic, idempotent migration tool like what I described in this highly-upvoted comment: https://github.com/palantir/tslint/issues/4534#issuecomment-466710036
I thought this as I just went through all of our rules to find the most helpful ones to migrate, it's just a lot of work right now to check which ones already exist :)

**Comment by JoshuaKGoldberg** [comment]
Cool, I'll have something for you folks soon. 😉 

In the meantime - what'd be helpful for me to know is some kind of relevancy for rules. Are there things you really do or don't care about? If that's a lot to ask, just a gut feeling check of which rules are _absolutely blocking_ your move to ESLint would be great. If we converted which {X} rules to ESLint, could you migrate immediately?

I'm also up for sending a pull request that partially migrates you using [eslint-plugin-tslint](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin-tslint) for any blocking rules in the interim.

**Comment by felixfbecker** [comment]
Here's a rough list of rules I think are the most important (in order):
- `no-floating-promises`
- `ban`
- `rxjs-no-async-subscribe`
- `rxjs-no-ignored-observable`
- `rxjs-no-ignored-subscription`
- `rxjs-no-nested-subscribe`
- `rxjs-throw-error`
- `deprecation`
- `await-promise`
- `jsx-ban-props`
- `no-object-literal-type-assertion`
- `no-unnecessary-type-assertion`
- `no-tautology-expression`
- `strict-type-predicates`
- `no-string-throw`
- `prefer-const`
- `prefer-for-of`
- `no-for-in-array`
- `no-require-imports`
- `unnecessary-else`
- `no-submodule-imports`
- `no-unbound-method`
- `no-angle-bracket-type-assertion`
- `no-console`
- `no-duplicate-imports`
- `no-inferrable-types`
- `no-var-keyword`
- `only-arrow-functions`

It's not that easy to actually come up with these cause we had them for a long time and it's hard to say which absence would cause problems (again), but I hope this helps!

**Comment by JoshuaKGoldberg** [comment]
Super. I just released [tslint-to-eslint-config](https://github.com/JoshuaKGoldberg/tslint-to-eslint-config), which can auto-generate the ESLint config for you. There's actually nothing feature-gap-wise stopping you from switching to ESLint right now: any TSLint rule without an ESLint equivalent can be run by [eslint-plugin-tslint](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin-tslint).

Out of those rules, ones that don't yet have a converter to the ESlint equivalent _(at least in tslint-to-eslint-config, which is probably slightly out of date already)_ are:

* `ban`
* `deprecation`
* `jsx-ban-props`
* `no-duplicate-imports`
* `no-floating-promises`
* `no-submodule-imports`
* `no-tautology-expression`
* `only-arrow-functions`
* `rxjs-no-async-subscribe`
* `rxjs-no-ignored-observable`
* `rxjs-no-ignored-subscription`
* `rxjs-no-nested-subscribe`
* `rxjs-throw-error`
* `strict-type-predicates`
* `unnecessary-else`

> @JoshuaKGoldberg I think what would help us the most is an automatic, idempotent migration tool like what I described in this highly-upvoted comment: [palantir/tslint#4534 (comment)](https://github.com/palantir/tslint/issues/4534#issuecomment-466710036)

Indeed, that'd be great. Tracking at https://github.com/JoshuaKGoldberg/tslint-to-eslint-config/issues/57.

**Comment by felixfbecker** [comment]
Tried it out, but got an error: https://github.com/JoshuaKGoldberg/tslint-to-eslint-config/issues/69
