### ISSUE TITLE
Monorepo never finishes indexing

### ISSUE THREAD

**Issue by sheesania** [sourcegraph/sourcegraph#24610]
Let me know if this question should be asked elsewhere - I wasn't sure exactly where to ask for help on a general support issue!

I've been experimenting with Sourcegraph, hoping to set it up for my team, and currently have a Docker Compose installation of Sourcegraph 3.31.1 on my dev machine for testing with two repositories. They are both small monorepos - one is 3.3 GB, the other is 140 MB - with mostly Java code. The issue is that Sourcegraph is taking forever to index them - I left it going for ~8 hours yesterday and the repository settings still report "initial indexing in process". Code intelligence features like jump to definition seem to be timing out (which is a bummer since this would be the killer feature for my team!).

I set up my CPU and memory limits in docker-compose.yaml per the resource estimator, with 8 cpus and 16g memory for zoekt-indexserver. My machine has a Ryzen 7 processor with 8 cores, 32 GB of RAM, and a 512 GB m.2 SSD. I'm not seeing high CPU/RAM/disk usage on my machine in general or reported for zoekt-indexserver in Grafana (the container seems to peak at 20% CPU usage and 30% memory usage). More oddly, zoekt-indexserver reports that it's indexed 2 repos in Grafana, even though on the Sourcegraph side it continues to say "initial indexing in progress".

Any leads on how to debug/fix this? Sourcegraph.com was an absolute godsend on my previous, open-source project (an ancient C monolith), and so I would love to be able to get a private instance working for my new team's private repos.

eta: I just checked the indexing progress again after opening this and the 140 MB repo had successfully finished indexing. So something at least is happening?

**Comment by sheesania** [comment]
I poked around some logs and found that the indexer appears to keep failing with this message:
```
2021/09/03 22:04:20 no output for 30m0s, quitting [zoekt-git-index -submodules=false -incremental -branches HEAD -file_limit 1048576 -parallelism 8 -index /data/index -require_ctags /data/index/.indexserver.tmp/tmpfriend-7-297814841/[repo].git]

zoekt-indexserver-0 | 2021/09/03 22:04:20 error indexing [repo]@HEAD=b081795d9e83770451e6eba9ffb6ea793334a59e: command [zoekt-git-index -submodules=false -incremental -branches HEAD -file_limit 1048576 -parallelism 8 -index /data/index -require_ctags /data/index/.indexserver.tmp/tmpfriend-7-297814841/[repo].git] failed: exit status 2

zoekt-indexserver-0 | OUT: SIGQUIT: quit
```

Perhaps related to #15992? But then in my case, the indexer doesn't think it's making progress even with a generous 30 minute timeout.

I also tried lowering and raising the number of cores allocated to zoekt-indexserver, and didn't see any difference.

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. We have made a lot of improvements to the performance of our indexed backend since 2021, so this issue is likely solved. To reopen the ticket,  please let us how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
