### ISSUE TITLE
Star result ranking order being enabled by default with repo results

### ISSUE THREAD

**Issue by donavonelli** [sourcegraph/sourcegraph#24650]
- **Sourcegraph version:** 3.30.0

#### Steps to reproduce:

1. Do a general search

#### Expected behavior:
The results to show most relevant results first

#### Actual behavior:
The results show in order of highest rated stars (i.e. 3.2k > 1.7k> 500) with no experimental ranking feature added to site config/ global settings

This affects customers with few or no starred repos being shown repos with more stars than their own
Relevant Zendesk Ticket: https://sourcegraph.zendesk.com/agent/tickets/3095

**Comment by lguychard** [comment]
@rmmh I know we have an escape hatch for ranking, but I can't find a reference to it in our docs or in the changelog. Could you help document this? Thanks!

**Comment by shuyangfang** [comment]
From https://sourcegraph.com/github.com/sourcegraph/sourcegraph@v3.31.0/-/blob/internal/search/repos/repos.go?L171-179#tab=references, it looks like that https://sourcegraph.com/github.com/sourcegraph/sourcegraph@42ff402d38f5e2951188c02fb4b6e3a21483ea57/-/blob/cmd/frontend/graphqlbackend/search_results.go?L530 is default `true`, so no escape hatch would apply / override? 

https://sourcegraph.com/github.com/sourcegraph/sourcegraph@v3.31.0/-/blob/cmd/frontend/internal/httpapi/internal.go?L165#tab=references looks overridable by not having `experimentalFeatures.Ranking` set but then stars end up dominating the priority anyway https://sourcegraph.com/github.com/sourcegraph/sourcegraph@v3.31.0/-/blob/cmd/frontend/internal/httpapi/internal.go?L215

I can't find any other escape hatch, but hopefully I'm missing something

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/search-core - the "team/search-core" label was applied to this issue.

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket, please let us know how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
