### ISSUE TITLE
Better nginx documentation for TLS

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#2466]
> We’ve had a few people have issues with SSL and the nginx docs. I think the sample nginx conf file needs to be updated to the latest generated version
It would be awesome if you could update the docs with what the nginx file should be
I’m working with Geoffrey on an AWS Terraform plan and this is the nginx file I’m using - https://github.com/sourcegraph/deploy-sourcegraph-aws/blob/master/terraform/ec2/resources/user-data.sh#L63
```# TODO (ryan): update generated nginx.conf file```
As an aside, that TODO is there because I want to use the nginx file generated, but just insert the required SSL configuration lines into the existing file.

**Comment by KattMingMing** [comment]
Related issue with some steps I went through to set up nginx and let's encrypt - https://github.com/sourcegraph/sourcegraph/issues/2475

**Comment by keegancsmith** [comment]
Your issue is much better, gonna track that instead.

Duplicate of #2475

**Comment by ryan-blunden** [comment]
Updated documentation is at https://docs.sourcegraph.com/admin/nginx#nginx-ssl-https-configuration and https://docs.sourcegraph.com/admin/ssl_https_self_signed_cert_nginx
