### ISSUE TITLE
search: Port server side query validation to client side

### ISSUE THREAD

**Issue by fkling** [sourcegraph/sourcegraph#24689]
[`validate.go`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@bac67ad723752a6cc5c3c6a25c5f31ce75a9f20f/-/blob/internal/search/query/validate.go) contains various server side query validations, some of which we can perform in the browser for a better UX. Potential candidates (still need to determine what is feasible):

- [x] `validateRepoRevPair`
- [x]  `validateCommitParameters`
- [x] `validateTypeStructural`
- ~[ ] `validateRepoHasFile` (waiting for clarification https://github.com/sourcegraph/sourcegraph/issues/4610#issuecomment-921745222)~
- ~[ ] `validatePureLiteralPattern` (don't quite know what this does exactly. might not be possible to evaluate this with tokens alone)~
- ~[ ] `lang:` filter contains a known language (caveat: Our client side list might not be up-to-date with the list used on the server) (skipping this one for now)~

**Comment by rvantonder** [comment]
> validateRepoHasFile

yeah skip this.

> validate `contains`

we already have some validation for this, not sure how much extra we need to be here

> validatePureLiteralPattern 

when do you think it will be useful to have this in the frontend? what comes to mind is just to suggest/warn the user to parenthesize an expression (which is useful). but if that's the case, we need to do more than just do what the Go counterpart does--we need to check it's not already parenthesized, etc. So, my intuition on porting this is that it's not immediately useful?

> lang:

what you said :-)

**Comment by fkling** [comment]
> when do you think it will be useful to have this in the frontend?
I was really only looking and what's technically possible to do on the frontend (i.e. which doesn't need any information from the server). I think the more validation we have in the frontend, the better. If some checks require "more" to be useful then we can track those in a separate issue (if we decide that it would eventually be useful).
