### ISSUE TITLE
`can't access property "key", t is null` on basic navigation

### ISSUE THREAD

**Issue by 5h1rU** [sourcegraph/sourcegraph#24694]
Copying from a slack thread made by @slimsag 

still running into this frequently, it seems to happen on about 1/3rd of all page loads for me in Firefox. It's not consistent. In Chrome, it seems like maybe the same issue surfaces as a long like 3s "delay" on page load but does not result in the error you see here.

Best way I have to repro is in Firefox by:
- Opening a new tab
- Pasting [https://sourcegraph.com/github.com/sourcegraph/sourcegraph](https://sourcegraph.com/github.com/sourcegraph/sourcegraph) into the URL bar and pressing enter

**Note:** in Chrome I get Sentry errors in the console, I wonder if it's related.

**Comment by eseliger** [comment]
This bug is caused by `react-grid-layout` used by code insights.
