### ISSUE TITLE
CLA bot posts message after CLA is already signed

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#2474]
See how CLA bot commented on https://github.com/sourcegraph/sourcegraph/pull/2135 multiple times. Chris signed the CLA Feb 2, 2019 13:44:10.

I wondered if this had to do with the pod restarting.

The [most recent comment was](https://github.com/sourcegraph/sourcegraph/pull/2135#issuecomment-467901229) Feb 27, 7:16 AM PT.

Describing the pod shows that it started 1.5 hours earlier:
```
State:          Running
      Started:      Wed, 27 Feb 2019 05:41:12 -0800
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Thu, 21 Feb 2019 14:07:26 -0800
      Finished:     Wed, 27 Feb 2019 05:40:51 -0800
Restart Count:  1
```

So restarting is a plausible theory if it takes 1.5 hours to resync everything.

@kevinburke would you expect the bot to re-post after being restarted?

**Comment by dadlerj** [comment]
@nicksnyder have you seen this reoccur since then?

**Comment by nicksnyder** [comment]
The last occurrence that I observed was March 18 on that same PR:
https://github.com/sourcegraph/sourcegraph/pull/2135#issuecomment-474114820

**Comment by dadlerj** [comment]
Okay if I close for now until we see it again then?

**Comment by nicksnyder** [comment]
Sure

**Comment by nicksnyder** [comment]
We just fixed CLA bot and saw it post a duplicate message on https://github.com/sourcegraph/sourcegraph/pull/3835#issuecomment-579450752. The pod restarted between the messages so that might be the cause (i.e. we don't persist any state between restarts)

**Comment by eseliger** [comment]
Possibly fixed in https://github.com/sourcegraph/maintainerbot/pull/1 
awaiting result here: https://github.com/sourcegraph/sourcegraph/pull/8271
I realized that cla-bot has a super long warmup phase of ~5h (around 2s per issue * ~8300 issues/prs). So revisiting in a while...

**Comment by eseliger** [comment]
It looks like it's working. Closing for now

**Comment by eseliger** [comment]
Found a proof PR: https://github.com/sourcegraph/sourcegraph/pull/3835
