### ISSUE TITLE
[DEPRECATED] Make the code insights landing page land you on "creation" screen if no visible insights

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#24751]
Right now, a new user sees: 
![image](https://user-images.githubusercontent.com/11967660/132548624-288dc58f-b69d-4ff1-ac03-33bb3671830d.png)

But we have a screen that does a better job of comparing insights one click away, at: 
![image](https://user-images.githubusercontent.com/11967660/132548674-30ffa203-ba2d-449a-9726-d3993ee4063a.png)

Could we just make the empty dashboard landing screen (eg, the first/any user who has no org-visible insights that display so "all insights is empty) automatically take you to the latter screen instead (so new users land there first)? 

Not a *major* issue because all the CTAs lead there, but it'd be a more polished first user experience with the feature.

**Comment by felixfbecker** [comment]
We should either do this **or** implement the [welcome page](https://www.figma.com/file/QfeID0EEYMEPdEv8pbGULB/Creation-UI-and-Welcome-page?node-id=9325%3A14960). I'd advocate to actually do the latter, if we can fit that in.
