### ISSUE TITLE
Scroll position not restored when clicking back/forward

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#24758]
### Flow:

1. Make browser window small enough to have vertical scrolling
2. Navigate to a page that has scrolling without requiring any data to be loaded (eg. https://sourcegraph.com/user/settings/profile )
3. Scroll all the way down
4. Click any link that will navigate to a different page (eg. a link in the top navbar)
5. Click the back button in the browser

### Expected:

Previous scroll position is restored

### Actual:

Previous page is shown scrolled all the way to the top

**Comment by valerybugakov** [comment]
@limitedmage, please clarify if we had this feature that stopped working, or is it an improvement request?
I see the `bug` label, but I never encountered this functionality in our web app.

**Comment by limitedmage** [comment]
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/28845

**Comment by limitedmage** [comment]
Actually not exactly a duplicate, as #28845 only addresses search results and not every page.

**Comment by limitedmage** [comment]
This is fixed by #41561
