### ISSUE TITLE
Consider a "formal" landing page for first-time code insights visitors

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#24768]
See [code monitoring](https://sourcegraph.com/code-monitoring/getting-started) and [batch changes](https://sourcegraph.com/batch-changes) pages. 

Couple of key differences I believe we should take advantage of: 

- We could show you an on-page insight (what if we just had a "TODOs" insight that was actually live, ready to go on the page when you visited it? or what if we selected a simple repo and search query and didn't let you change ANYTHING else but the repo and query in a quick live-edit preview for single-repo insights as an on-page demo?) 

- Batch changes and code monitoring are "later value" features: code monitoring "monitors over time" and batch changes takes some time to learn + set up (and if you want to run changes, you have to be willing to change your code at that moment). Code insights (at least for frontend insights) returns value fast. If not the above concept, how can we funnel you into creating your first insight fast?

**Comment by Joelkw** [comment]
Go away @sourcegraph/batchers this doesn't concern the likes of you!

**Comment by unclejustin** [comment]
![Nothing to see here](https://user-images.githubusercontent.com/1855233/132600676-e6944e77-d250-4b03-940e-4fe17e301cb0.gif)

**Comment by Joelkw** [comment]
(Noting we have older in-progress designs here: https://www.figma.com/file/QfeID0EEYMEPdEv8pbGULB/Creation-UI-and-Welcome-page?node-id=275%3A1628 )

**Comment by felixfbecker** [comment]
@AlicjaSuska do you think we could have a revised design for this before the start of the next iteration (i.e. by EOW), so that we could include implementation of this issue in the next iteration?

**Comment by Joelkw** [comment]
Yay, we did this! (For GA.)
