### ISSUE TITLE
Web: Hovering over line number in diff view breaks hovers

### ISSUE THREAD

**Issue by tjkandala** [sourcegraph/sourcegraph#24762]
Steps to reproduce:
- go to a diff view on the Sourcegraph web app
- hover over a line number
- observe that hovers no longer work, whether you're in unified or split mode 

### Console

![Screenshot from 2021-09-08 17-01-20](https://user-images.githubusercontent.com/37420160/132585034-48067ed6-d00e-480b-8572-4fcdfc01aa6f.png)

**Comment by muratsu** [comment]
Interesting to know what has changed to break the old behavior

**Comment by tjkandala** [comment]
@muratsu Explanation in [PR description](https://github.com/sourcegraph/sourcegraph/pull/24763#issue-991530890)

**Comment by muratsu** [comment]
Yeah just saw the explanation. Can we add a test to make sure we don't break this in the future?

**Comment by tjkandala** [comment]
@muratsu I would like to protect this, but not sure how many "negative tests" we should have. I guess if something _has_ broken before, that's how we determine that something is worth writing a negative test case for. cc @erzhtor wdyt?

We don't have diff integration tests yet, but that's definitely worth adding so we might as well cover this case! I'll create an issue for it
