### ISSUE TITLE
Change VS Code Sourcegraph extension categories

### ISSUE THREAD

**Issue by tjkandala** [sourcegraph/sourcegraph#24766]
We are in the process of deprecating `sourcegraph/vscode-extras` in favor of `sourcegraph/open-in-vscode`. We should add the `Code editors` category to `sourcegraph/open-in-vscode`s manifest to put it higher in the extension registry, and remove all categories from `sourcegraph/vscode-extras`s manifest to push it down the extension registry.

**Comment by erzhtor** [comment]
Done!

<details>

![image](https://user-images.githubusercontent.com/6717049/133256206-e61ef34e-7419-4165-b06a-dff0a5cdf90b.png)
</details>
