### ISSUE TITLE
Unclear how to expose access to management console (GCP)

### ISSUE THREAD

**Issue by KattMingMing** [sourcegraph/sourcegraph#2478]
After following the [Install Sourcegraph with Docker on Google Cloud](https://docs.sourcegraph.com/admin/install/docker/google_cloud) documentation and setting up SSL/TLS - https://github.com/sourcegraph/sourcegraph/issues/2475 it's not obvious to users how to access the management console.

By default, `2633` is not exposed and users need to expose the port so that it can be accessible.

You can do so by running:
```
gcloud compute firewall-rules create management-console --allow tcp:2633,icmp
```

@slimsag is this how users should expose access to the management console?

Also should users update their certificate to a signed certificate when going through the SSL/TLS configuration?

**Comment by slimsag** [comment]
Apologies for delay in answering this. The answer is Yes, exposing that port to the public internet is a good (and safe) thing to do here.

In Kubernetes/cluster deployments, it is marginally safer (more for peace of mind) to not expose the port to the internet and instead use port forwarding. For Server deployments where that is not easily possible, exposing it to the public internet is the right thing to do. See https://docs.sourcegraph.com/admin/management_console#when-running-sourcegraph-in-a-single-docker-container for how I talk about this currently.

> Also should users update their certificate to a signed certificate when going through the SSL/TLS configuration?

Users can do so if they want to. It is marginally safer to do so (for example, your connection initially could be MITM'd as an attacker could send you their own self-signed certificate). However, the operating assumption is that in general users who are worried about this and security conscious will know to do this anyway. This is to say: I do not think we need to provide instructions for doing so, but merely mention it as a possibility in passing. See https://docs.sourcegraph.com/admin/management_console#i-am-seeing-tls-ssl-warnings-in-my-browser-why for how I talk about this.
