### ISSUE TITLE
Update "What we support" spreadsheet

### ISSUE THREAD

**Issue by dan-mckean** [sourcegraph/sourcegraph#24799]
We're putting together a relatively high-level "What we support" spreadsheet. This task is to add things that we do support, as well as things we don't but that we can think we might be asked about.

[The spreadsheet](https://docs.google.com/spreadsheets/d/101JXaau2EPvi322AOFmNeoeuXSJqlruD8gBBsHl1fmI/edit#gid=0)

**Comment by davejrt** [comment]
having reviewed this...at a high level nothing further comes to mind.
