### ISSUE TITLE
"must be site admin" when accessing account settings on sourcegraph.com 

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#2480]
- **Sourcegraph version:** "Sourcegraph.com"
- **Platform information:** google chrome
#### Steps to reproduce:

1. log in to sourcegraph.com
2. go to `users/${user}/settings` or `users/${user}/account`

#### Expected behavior:

account setting page

#### Actual behavior:

![image](https://user-images.githubusercontent.com/23356519/53535315-41455600-3ab7-11e9-9a4a-a90939f54188.png)

**Comment by sqs** [comment]
Confirmed broken on Sourcegraph.com. It works on self-hosted instances.

**Comment by sqs** [comment]
Merged and deployed fix, confirmed working on Sourcegraph.com now. Thank you, @bobheadxi!
