### ISSUE TITLE
Document how to update docs.sourcegraph.com for a new release version

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#2481]
Document the docs update release process and update (Sourcegraph) release checklist for 3.2.

Extracted from #2465 so that issue can just be about the underlying code changes (which are good on their own).

**Comment by ryan-blunden** [comment]
See https://github.com/sourcegraph/sourcegraph/blob/master/doc/dev/patch_release_issue_template.md#update-the-docs
