### ISSUE TITLE
Browser extension not working for private repo

### ISSUE THREAD

**Issue by indradhanush** [sourcegraph/sourcegraph#24842]
- **Sourcegraph extension version:** v21.9.9.1541
- **Platform information:** Firefox, Chromium

#### Steps to reproduce:

1. Add a private GitHub repo to sourcegraph.com
2. Visit the repo on GitHub

#### Expected behavior:

Sourcegraph extension to work

#### Actual behavior:

Sourcegraph extension doesn't work and show a red dot

Private repo on github.com
![image](https://user-images.githubusercontent.com/2682729/132868851-c99d0bfa-3ac6-44c4-8131-5e345c9b8484.png)

Same private repo added on sourcegraph.com
![image](https://user-images.githubusercontent.com/2682729/132869009-b8705a1e-a1f4-4220-a646-75c0abdc05cc.png)

Extension not working on repo (notice the red dot on the extension icon in the top right)
![image](https://user-images.githubusercontent.com/2682729/132869498-bb3d1f51-f87d-4d33-92f3-ce76d93d34b6.png)

**Comment by taras-yemets** [comment]
Personal repositories are no longer supported on sourcegraph.com ([blog post](https://about.sourcegraph.com/blog/single-tenant-cloud)). 

I can confirm that the Sourcegraph browser extension v22.9.27.1330 works for private repositories on private Sourcegraph instances.
<img width="2554" alt="Screenshot 2022-09-30 at 12 34 00" src="https://user-images.githubusercontent.com/25318659/193240959-a35c2f67-140b-4dba-bc1d-6086df38853e.png">
<img width="2554" alt="Screenshot 2022-09-30 at 12 33 47" src="https://user-images.githubusercontent.com/25318659/193240978-4eb41621-d7bc-40a7-b7ee-e9656a05f129.png">
