### ISSUE TITLE
Change the default search contexts

### ISSUE THREAD

**Issue by KashingLiu** [sourcegraph/sourcegraph#24860]
#### Feature request description

I notice that the default search contexts is `global`, it means that Sourcegraph will search all repos on each repo's default branch, it doesn't mean it will search all repos on each repo's all branch. So I use search context, but by default, it only searches the default branch. I want to change the default context, but I can't find any information.
Before: 
![image](https://user-images.githubusercontent.com/22939122/132940236-9cb9c047-987e-4778-b841-b814b1bb5ac0.png)
After:
![image](https://user-images.githubusercontent.com/22939122/132940276-d4a90598-c237-4d32-9227-5222ab3dcc53.png)
@keegancsmith

**Comment by KashingLiu** [comment]
Or the word `context` will make the user confuse, I think `version` is better

**Comment by KashingLiu** [comment]
https://github.com/sourcegraph/sourcegraph/issues/10621#issuecomment-665820457

**Comment by keegancsmith** [comment]
cc @novoselrok

**Comment by benvenker** [comment]
Contexts now remember your last used context via temporary settings.
