### ISSUE TITLE
Provide single command to download and install sg binary

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#24897]
What I want is a single shell command that a new colleague can paste into their terminal and they end up with `sg` installed.

Example: [`rustup.rs`](https://rustup.rs/)

It should

1. check whether they're on macOS or Linux
2. download the binary
3. move it into a correct folder
4. propose to update the shell config to include the folder in the `$PATH`

See this screenshot of `rustup` in action:

![rustup](https://user-images.githubusercontent.com/1185253/133054901-dafd1c28-0518-4315-bb8a-58805c34d75e.png)

**Comment by jhchabran** [comment]
@mrnugget I think we can safely close this.

**Comment by bobheadxi** [comment]
Would be nice to have the relevant PRs linked here!
