### ISSUE TITLE
`lang:Dockerfile` not working as expected (does not find `Dockerfile`s)

### ISSUE THREAD

**Issue by NiclasvanEyk** [sourcegraph/sourcegraph#24890]
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:** MacOS Big Sur 11.4, Firefox 91.0.2 (but I don't think this is platform dependant) 

#### Steps to reproduce:

1. Execute a search using the `lang:Dockerfile` filter, e.g. [for the sourcegraph/sourcegraph repository on Github](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+lang:Dockerfile+&patternType=literal)
2. Use the same search, but exchange the `lang:Dockerfile` filter for `file:Dockerfile`, e.g. [the same example as in search 1 with exchanged filters](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:Dockerfile&patternType=literal)

#### Expected behavior:

Search (1) and (2) should yield similar results, especially for files called `Dockerfile`.

#### Actual behavior:

Search (1) does not yield any results, while search (2) correctly finds all Dockerfiles. 

It seems like the `lang:Dockerfile` filter only takes the file extension into account. For example, when I do not limit the search to a particular repository and apply `lang:Dockerfile` ([link](https://sourcegraph.com/search?q=context:global+lang:Dockerfile&patternType=literal)), only files like `something.Dockerfile`, so ones containing the `.Dockerfile` suffix are returned. This is even more obvious when _also_ applying `file:^Dockerfile$` ([link](https://sourcegraph.com/search?q=context:global+lang:Dockerfile+file:%5EDockerfile%24&patternType=literal)), which yields no results. 

#### Additional notes

The _syntax highlighting_ seems to have similar issues, just the other way around: A file called `Dockerfile` [is highlighted correctly](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/cmd/tracking-issue/Dockerfile), while a file with a `.Dockerfile` suffix [does not get highlighted](https://sourcegraph.com/github.com/microsoft/vscode/-/blob/.devcontainer/cache/cache.Dockerfile) at all.

Also other languages with similar naming conventions suffer from such issues. A search containing `lang:Makefile` [only yields files with a `.mk` extension](https://sourcegraph.com/search?q=context:global+lang:Makefile+&patternType=literal), but most makefiles will be just named `Makefile`, which [are found when using `file:^Makefile$`](https://sourcegraph.com/search?q=context:global+file:%5EMakefile%24&patternType=literal), but applying both `lang:Makefile` and `file:^Makefile$` [yields no results](https://sourcegraph.com/search?q=context:global+file:%5EMakefile%24+lang:Makefile+&patternType=literal).

Given that `Dockerfile` is the convention/default filename used by the `docker` cli, I think that a search containing `lang:Dockerfile` should also return those files as a result.

**Comment by camdencheek** [comment]
Thanks for the detailed report! This should be fixed by #25320
