### ISSUE TITLE
Code Intel in a Monorepo not working as expected

### ISSUE THREAD

**Issue by topebali** [sourcegraph/sourcegraph#24911]
- **Sourcegraph version:**  v3.31.1 and "Sourcegraph.com" 
- **Platform information:** 

#### Steps to reproduce:

1.  Build a Monorepo from scratch or create a fork of a public repo. In my case, I used [this](https://github.com/vladotesanovic/hospital-sdk)
2. Clone to your local system.
3. Add the repo to SG and make sure it's indexed.

#### Expected behavior:
search-based intel should work for JS files and when the LSIF data is uploaded I should get precise code intel on JS files without affecting the precise code intel already generated for TS files.

#### Actual behavior:
I did a search-based intel on some JS files, no code intel(hover tips) popped up. I did the same search for TypeScript I got search-based intel. I decided to manually generate index data in LSIF for JS and TS. I followed the manual indexing instructions in the [docs ](https://docs.sourcegraph.com/code_intelligence/how-to/index_a_typescript_and_javascript_repository). I ran the` lsif-tsc -p .` command for typescript. I uploaded the data to my SG instance and I was able to get precise code intel and interestingly, I was able to get search-based code intel for JS files. Now I decided to follow the instructions in the guide I shared for the JS files I have and I observed that no code intel worked for JS files while the TS files switched to search-based intel meaning the earlier precise code intel I was getting disappeared. now I re-ran the commands for TS as per the doc and I was getting my previous precise code intel back while JS was returning search-based intel.

It's important that I also mention the issue with JS files isn't just in a monorepo, a normal JS file search on sourcegraph.com doesn't return any code intel.

**Comment by macraig** [comment]
@tjkandala @Joelkw we suspect this might be related to https://sourcegraph.slack.com/archives/C01LZKLRF0C/p1631282442116300?thread_ts=1631281063.115900&cid=C01LZKLRF0C
