### ISSUE TITLE
If I run an empty search, the repository filter results don't make any sense

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#24939]
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:** Chrome Version 93.0.4577.63 (arm64)

#### Steps to reproduce:

1. Run an empty search from the homepage
2. See that the your are returned a list of repositories by GitHub star rank
3. Look at the repositories filter and see that the list is not the list of repositories but a list of (possibly?) numerically ordered repository names
![CleanShot 2021-09-13 at 22.08.23.png](https://images.zenhubusercontent.com/5467e9ba7c6ccc6277a5f103/f0205ead-b88a-46da-8d3e-b0cf605c4c09)

#### Expected behavior:
I would expect to see the list of repos in the results duplicated in the repositories filter.

#### Actual behavior:
See screenshot above.

**Comment by camdencheek** [comment]
Filters have since been redesigned twice. Closing as stale.
