### ISSUE TITLE
Notepad

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#24932]
Store users Sourcegraph browsing history in a "stack" UI element so they can quickly jump back to previous searches or files. Some things that would be nice:
- Store search results for some nontrivial length of time
- Retain scroll position of a file view
- Retain scroll position of a search results view
- Differentiate in the UI component between searches and files

Something likely not dissimilar from the VS Code outline feature in appearance an placement:
![image.png](https://images.zenhubusercontent.com/5467e9ba7c6ccc6277a5f103/1b818ba1-87d5-4324-841a-9954e7582076)

## Previous Context
[RFC 278](https://docs.google.com/document/d/1zoLxppX0XmwQsD7u2m5yZA9E3EQdzMlAYkdsqpNa8sQ/edit#heading=h.trqab8y0kufp)

**Comment by fkling** [comment]
Can we close this? @benvenker
