### ISSUE TITLE
Add link to root directory in file path breadcrumbs UI

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#24946]
#### Feature request description

When browsing a file, you click on a **button** to open the root directory of the repository and you click on a **link** to open a subdirectory.

![CleanShot 2021-09-14 at 09 37 27@2x](https://user-images.githubusercontent.com/1408093/133216336-a53d88d5-c6dc-4d3b-96c6-e72e5d3b060c.png)

It would be nice if there was a **link** to the root directory that was consistent with the links to the subdirectories.

#### Is your feature request related to a problem? If so, please describe.
It may be difficult for users to discover the button to the root directory. For example, https://twitter.com/willnorris/status/1435649914814418944

#### Additional context

For inspiration, GitHub file breadcrumbs include a link to the root directory

<img width="986" alt="image" src="https://user-images.githubusercontent.com/1408093/133216920-cc5d3451-6ade-4b21-b8c2-dee5b435bb33.png">

**Comment by olafurpg** [comment]
One design challenge is that the current root directory button is visible in other pages like "branches" and "tags"

![image](https://user-images.githubusercontent.com/1408093/133222105-b2506989-a17c-4406-87b7-70e00a4a7829.png)

If we keep this button and add a link in the file breadcrumbs, then we end up with one button and one link in the same row that do the same thing. In GitHub you also have two links to the root directory but they're not on the same row.

**Comment by jjinnii** [comment]
@olafurpg @macraig Is it possible for us to track how often users are utilizing the root directory button to change root directories while in a search? We debated for awhile during our planning what use cases there were for users to **change** roots when already performing a search.

**Comment by efritz** [comment]
@Numbers88s We decided the easiest solution is to add a leading `/` that points to the root directory of the repository. Then we can break links up as 

`/ (dir1/) (dir2/) (dir3/) ...`
