### ISSUE TITLE
Add file icons in tree views and directory overview

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#24947]
#### Feature request description

Currently, the directory page looks like this on Sourcegraph

![CleanShot 2021-09-14 at 10 09 09](https://user-images.githubusercontent.com/1408093/133220866-88cbfbf2-f7e4-4e0f-8d5f-85fd38c289d3.png)

The tree view looks like this.

![CleanShot 2021-09-14 at 10 11 17](https://user-images.githubusercontent.com/1408093/133220834-72a6fc8f-f815-4092-bf66-3fa18d87a881.png)

It would be nice if the files has icons to make it easier to distinguish the what file types are there (CSS, JSON, TypeScript, Java, Go, ...).

#### Is your feature request related to a problem? If so, please describe.

Without icons, it's difficult to quickly find the files I'm looking for.

#### Additional context

VS Code displays file icons in the tree view

![CleanShot 2021-09-14 at 10 09 54](https://user-images.githubusercontent.com/1408093/133220954-d7552cc2-bd66-47c0-b833-d92f51d34295.png)

The icons in VS Code from the theme set here https://github.com/jesseweed/seti-ui

IntelliJ has its own custom icons that are Apache 2 licensed and available here https://github.com/JetBrains/intellij-community/tree/32ff29dd848947bf1e6a4a82cc71926d4e8b9b71/platform/icons/src/fileTypes

![CleanShot 2021-09-14 at 10 33 56](https://user-images.githubusercontent.com/1408093/133224912-6da1459a-6bc6-44e4-b429-412cd3577d01.png)

**Comment by fkling** [comment]
We have icons now.
