### ISSUE TITLE
Make search contexts code enterprise-licensed

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#24955]
Search contexts should not be available in the OSS version of Sourcegraph. Code related to search contexts should be moved to `/enterprise` folders.

**Comment by malomarrec** [comment]
@lguychard @benvenker do you think we can aim doing this before the end of Q3?

**Comment by lguychard** [comment]
@malomarrec we need to confirm the effort required with the team, but we've tentatively planned this for next iteration (starting 2021-09-20).

**Comment by benvenker** [comment]
@camdencheek or @novoselrok, not sure if you're the right people to comment, but any idea on the complexity and feasibility of this? Would like to throw it in this iteration if we can.

**Comment by novoselrok** [comment]
> @camdencheek or @novoselrok, not sure if you're the right people to comment, but any idea on the complexity and feasibility of this? Would like to throw it in this iteration if we can.

I'll investigate today. Moving the client should be fairly straightforward. I expect the backend to be more complicated because the code is spread across multiple modules.

**Comment by benvenker** [comment]
Got it, thanks.

**Comment by malomarrec** [comment]
@novoselrok is there a separate issue for moving the GraphQL API to enterprise?

**Comment by novoselrok** [comment]
> @novoselrok is there a separate issue for moving the GraphQL API to enterprise?

It was already done as a part of this ticket. Here is the PR: https://github.com/sourcegraph/sourcegraph/pull/25281 The PR was reviewed separately, but merged together with the client PR.
