### ISSUE TITLE
Blur browser omnibox after searching

### ISSUE THREAD

**Issue by erzhtor** [sourcegraph/sourcegraph#25000]
**1.Description**

The browser extension adds Omnibox (quick search) with the `src` key. However, when you search and the Sourcegraph search results are loaded browser Omnibox is still in focus which confuses users (at least me) because Sourcegraph search input is also focused. 

Also, usually, you want to add/edit Sourcegraph search input by adding more filters or so, and when you type, you end up editing browser Omnibox instead.

**2. Steps to reproduce**

1. Search using `src` + Tab -> Write query -> Enter
![image](https://user-images.githubusercontent.com/6717049/133469663-b3bdc183-042a-4c92-b054-a1a496d70dd8.png)

2. Both browser omnibox and Sourcegraph input seems to be focus. However, Omnibox takes precedence.
![image](https://user-images.githubusercontent.com/6717049/133469784-8614ef3d-cb11-4918-97f1-34cf6fa100e0.png)

**3. Expected behavior**
Browser Omnibox to blur, and focus only Sourcegraph search input.

**Comment by erzhtor** [comment]
@muratsu, @tjkandala, I often quickly jump to SG search using the **`src`+ Tab** shortcut added by a browser extension. And it always confuses me that I want to update the SG input field but end up updating the browser Omnibox/input. So, I decided to make a quick fix. 

Also, to clarify for the future, do we want to create "Issue with labels + PR" or for such cases, or just creating "PR with labels" would be enough?

**Comment by muratsu** [comment]
I like it! I would make sure it works x-browser. Safari & FF might have unexpected behavior.

I think PR with labels work for quick fixes like this but we should still add the PR to the tracxking board so that we can see work that's delivered

**Comment by erzhtor** [comment]
@muratsu, thanks for the feedback! I've checked firefox, works correctly! Regarding safari, I could not find a way to trigger Omnibox keyword searching (even with a published SG extension). It doesn't seem to support it at all, does it?
