### ISSUE TITLE
Let users select "don't show me again" to the NPS survey popup

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#25010]
We should let users select a "don't show me this again" on the survey. 

TBD whether you can only click this option if it's been submitted/selected at least once, or whether we want to just let users not respond at all and then disable it permanently for themselves. Not sure what the impact to the feedback pipeline would be (you can already close it, but at least it comes up again later if you do now). 

We've had users who dislike the NPS prompt strongly [see it multiple times and complain each time](https://sourcegraph.slack.com/archives/C0W2E592M/p1631658753143300?thread_ts=1631656895.142300&cid=C0W2E592M). 

h/t to @mike-r-mclaughlin

**Comment by benvenker** [comment]
Hey @AlicjaSuska and @Joelkw, search product team thinks we have a way to solve this on our end pretty easily using some work @limitedmage has done recently on temporary settings. Sounds like it might actually be the ideal solution, so we're happy to take it on if you'd like.

**Comment by benvenker** [comment]
If you're good with that, please just comment here and add the "team/search-product" label to the issue so it gets in our backlog. Thanks!

**Comment by AlicjaSuska** [comment]
I've put together the [design](https://www.figma.com/file/WsGbJHkx7usyZpwa02RdQK/Basic-Project-Template-Copy?node-id=246%3A11) for the checkbox. I've also updated some styles:
- removed the emoji
- adjusted padding and spacing
- separated the buttons
- added the scale (likely / not likely) for better communication

@Joelkw @umpox could you please review? Thank you!

<img width="790" alt="Screenshot 2021-09-22 at 17 53 05" src="https://user-images.githubusercontent.com/20326070/134378384-49ab4617-dac3-4973-9be6-ede05d5e4967.png">

Also, should we add the cancel option and the 'don't show again' checkbox also to the next step? @jjinnii @rrhyne wdyt?

<img width="559" alt="Screenshot 2021-09-22 at 17 48 20" src="https://user-images.githubusercontent.com/20326070/134378197-84321dce-d0cb-40dd-a7c7-e0694f1fcd27.png">

**Comment by Joelkw** [comment]
Looks good to me generally. What happens if I check "don't show this again" on the box before I select a number – does it automatically go away? A checkbox feels like "I still have to submit" – I'm wondering if we should make it a "link/button" that just closes this if you don't want to submit or see this again? (There are some slight tradeoffs on "we'd ideally like people to give us feedback rather than close this immediately" but seems like folks who are angry / don't want to submit will submit a 0 anyway and check the box, so that feedback won't be valuable?)

**Comment by jjinnii** [comment]
On the question about adding the 'don't show again', when a user has selected a rating. I would say yes, (and an exit if the "x" close icon is not present) as well. 

We don't have any indication from the original survey that there's more to the form once you select a number (@Joelkw worth exploring in the future). But due to that, I think we should allow users the option to exit and decide not to see the popup again if they're irked that there's more to the form than they expected.

**Comment by Joelkw** [comment]
(I am not really a stakeholder here, just a PM helping move this forward @benvenker ! The folks who'd implement this could either be frontend platform or search)

**Comment by benvenker** [comment]
Yeah I'm definitely fine with frontend platform implementing. It does sound like it makes sense to use @limitedmage's temporary settings work to keep track of the user preference though.

**Comment by AlicjaSuska** [comment]
@Joelkw answering your question: after selecting 'don't show this again', user still needs to close the popup with X. To avoid skewed results (for ex. of the 'angry 0'), I would not condition the ability to check the checkbox on selecting the rating. It should be available. Also, selecting the rating automatically moves the user to the next page with details so the situation of selected rating & 'don't show it again' does not exist.

**Comment by AlicjaSuska** [comment]
@pdubroy I move it to backlog as design is ready

**Comment by umpox** [comment]
Moved to 'On deck'. I think we can bring this in next week given the importance
