### ISSUE TITLE
insights: investigate query timeouts

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#25062]
Sourcegraph syntax has an option `timeout` to specify how long the query should execute before stopping. The default value is currently 45.

We perform a [search](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/insights/background/queryrunner/graphql.go?utm_product_name=GoLand&utm_product_version=GoLand#L100:6) against Sourcegraph to generate code insights. We need to understand if this `timeout` field will impact insights search results, and if there is any way to override without having to manipulate the syntax. If we do have to manipulate the syntax, will we encounter similar problems to https://github.com/sourcegraph/sourcegraph/issues/24432.

**Comment by slimsag** [comment]
If count:all or count:99999999 are in the query, the timeout field is
irrelevant and disregarded entirely FWIW.
-- 
Follow me on twitter @slimsag <https://twitter.com/slimsag>.

**Comment by coury-clark** [comment]
@slimsag thanks for that context! It seems I was misled by something else then. This issue may just be scoped to understand why some code insights queries are consistently timing out / 503 bad gateway.

**Comment by coury-clark** [comment]
It certainly seems possible to run a search for longer: 
<img width="458" alt="image" src="https://user-images.githubusercontent.com/5090588/163599529-06b63cb7-3c5f-4037-9545-8d09174776c8.png">

Maybe the old timeout is an artifact of pre-stream search. The remaining question is probably what should the default from Code Insights be? 45 seconds is probably reasonable for most searches - maybe we need a way to override this.

**Comment by Joelkw** [comment]
Notes from sync: 
- @chwarwick - we need a way to reliably trigger this to test it, maybe the new Gigarepo will help? 
- @Joelkw we can check on that with this issue first – we should stop and re-evaluate at this point. 
- @Joelkw is this a default or should it be configurable? 
- @chwarwick  - this is actually a search default, or at least it was.

**Comment by coury-clark** [comment]
Is there anything left here to answer? It seems the original question is answered in the context of a stream, we can exceed the 2 minute limit.

**Comment by coury-clark** [comment]
While looking into the compute streaming endpoint, I noticed this as well: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/internal/compute/streaming/stream.go?L22

We may need to introduce some changes here if we need to exceed 1 minute on the compute stream.

**Comment by Joelkw** [comment]
@coury-clark if we've answered this question, feel free to close! Was just writing down what we discussed in team sync.
