### ISSUE TITLE
migrations: dirty flag can linger even after a successful migration

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#25089]
It's possible for a migration to complete successfully but leave the dirty flag set to true.

This requires unnecessary manual intervention to fix, and the fix is always `UPDATE schema_migrations SET dirty = 'f'`.

Here's how it can happen:

- The frontend starts up and begins a [golang-migrate](https://github.com/golang-migrate/migrate) migration
- golang-migrate sets the dirty flag to true
- golang-migrate sends the SQL commands to Postgres
- The migration happens to be slow, and the frontend pod gets restarted by Kubernetes after [5 minutes](https://github.com/sourcegraph/deploy-sourcegraph-dot-com/blob/180850cbcdc71f99b7926182151aa0354b41850b/base/frontend/sourcegraph-frontend.Deployment.yaml#L80)
- The SQL commands complete successfully
- The dirty flag is left set to true (if the SQL commands completed fast enough, the frontend would still be around and golang-migrate would set the dirty flag to false)
- The frontend pod starts back up and sees a dirty database and prints the dreaded "Failed to migrate the DB. Please contact support@sourcegraph.com for further assistance: Dirty database version 1528395882. Fix and force version."

## Solutions

- **Hardcode**: modify all migration files by appending `SET dirty = 'f'` and `git commit` those changes https://github.com/sourcegraph/sourcegraph/pull/25090
- **FS injection**: inject `SET dirty = 'f'` into each migration file on the fly when [reading the migration files](https://github.com/sourcegraph/sourcegraph/blob/7ce0484274d7382f4b9b2898d77c3987e51fffa6/internal/database/dbconn/migration.go#L83)
- **golang-migrate injection**: add an option to golang-migrate to inject `SET dirty = 'f'`

## Previous work

We intended to fix this in the past, but I accidentally merged the PR into the wrong branch and it never got into master 🤦‍♂️ https://github.com/sourcegraph/sourcegraph/pull/7909

**Comment by efritz** [comment]
Another solution is to rewrite the entire freaking thing.
