### ISSUE TITLE
Diff & commit search improvements: speed and correctness

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#25114]
This epic tracks the refactor effort to make git search more performant and wrap it in a better API so we can do more complex queries. This came out of exploring migrating from git CLI to libgit2, but for reasons outlined in #24595, we chose to stick with git CLI. 

Expected outcomes:

**Improved diff and commit performance**
  - Avoid many followup requests to fetch diffs
  - Reduced network bandwidth
  - Optimized case-insensitive regex search
  - Parallel searching
  - Save matches during search to avoid re-searching for highlights
  - And/or/not queries are supported natively on the backend, which avoids running many DNF-ed queries
  - No false positives need to be post-filtered due to query semantics/git CLI feature mismatch
  - TODO: add some numbers here
  
**Increase 50-repo search limit**
- Actual max will be determined by the performance improvement (TODO expect 2-3x, still in evaluation though)
- Commit search can probably be raised higher than diff search (diff search is _much_ more expensive than commit)
- The limit will still necessarily exist until we have indexed commit/diff search

**Improved query correctness**
- And/or queries currently do not highlight all terms
- Because we highlight after generating the diff, context lines are sometimes highlighted
- Correctly highlight file names
- Correctly highlight message when the `message:` field is used
- Avoids bad regex-to-glob conversions like the case of `file:(internal/commit)`

**Improved maintainability**
- No dynamically-generated git args
- No translating regex to globs
- Our query structure maps directly to supported git search types
- Added boundary between git CLI and the calling search service
- More possible to add alternative commit/diff backends

**Comment by lguychard** [comment]
@benvenker @camdencheek it might make sense to close this?

**Comment by camdencheek** [comment]
Yes, I think we can close this. The only followup task is to remove the old diff/commit search code, which I plan to do after the 3.34 release cut.
