### ISSUE TITLE
Frontend always sends Cache-Control: no-cache

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#2512]
Every URL under a Sourcegraph instance is responded to with the HTTP header
```http
Cache-Control: no-cache, max-age=0
```
This is especially bad for the raw API, and it causes Cloudflare to never cache (even with a page rule), which in turn causes it to use chunked encoding and swallow the `Content-Length` header (#2467).
Also especially in the raw API when giving a commit hash the archive is not only cacheable, but immutable.

It looks like this line is responsible: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@c56753b88ecacf5b4fbadbc618fd6790d73daec6/-/blob/cmd/frontend/internal/cli/http.go#L134

**Comment by felixfbecker** [comment]
@keegancsmith @slimsag 	thoughts?

**Comment by nicksnyder** [comment]
No-cache sounds like a good default policy for api endpoints in general so it seems like we would just want a way to override this on the raw endpoint.

**Comment by slimsag** [comment]
I agree, we just need to override this in places where we do want caching. In all other locations, no-cache is the sane default. i.e. just add:

```Go
w.Header().Set("Cache-Control", "some caching rule")
```

To the HTTP handler where we want caching.

We need to be careful about auth though, there are some confusing factors at play here. e.g. the raw endpoint accepts cookie auth, so it also goes through the CSRF middleware, which means it sometimes(?) sends a cookie back which would disable caching and/or break things when it doesn't send a cookie back and we do cache the response. I'm not 100% positive on the details here, someone will need to investigate end-to-end whether or not it is safe (both security and bug-wise) to enable caching on the raw endpoint.

**Comment by beyang** [comment]
stale, please re-open if still an issue
