### ISSUE TITLE
Can't scroll down on search results, page bounces weirdly

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#25148]
Seen on https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/about%24+type:commit+update&patternType=literal using a trackpad.

I'm trying to scroll down, but instead the page just bounces weirdly. I can then also not scroll up anymore. It seems that there are somehow two scrollbars stacked where one only moves a few pixels but scrolling with the trackpad triggers scrolling that scrollbar. It also seems related to streaming more results, as eventually when "breaking through", it works again, but also it seems more items are not rendered until you're at the bottom, so it's a chicken-and-egg problem?

https://user-images.githubusercontent.com/10532611/134134410-42484bcc-ffc5-4566-b677-5a6f3062eb1d.mov

**Comment by benvenker** [comment]
Seems ok now, can't repro
