### ISSUE TITLE
Investigate root cause of alert "repo-updater: 0.1s+ mean blocked seconds per conn request for 15m0s"

### ISSUE THREAD

**Issue by indradhanush** [sourcegraph/sourcegraph#25153]

**Comment by indradhanush** [comment]
https://github.com/sourcegraph/infrastructure/pull/2783

**Comment by indradhanush** [comment]
@tsenart has updated the max PG connections for repo-updater to 60. We've disabled the alert tonight and are going to look at this tomorrow as a P0 for @sourcegraph/repo-management team.

This issue 
https://github.com/sourcegraph/deploy-sourcegraph-dot-com/commit/f38d761845bd9da0d65900a0b0c9aff540870823

**Comment by ryanslade** [comment]
Updating the connections did not seem to help.

There seems to be a clear correlation between deployments or pod restarts as can be seen here:

<img width="1766" alt="Screenshot 2021-09-23 at 12 22 29" src="https://user-images.githubusercontent.com/25610/134491435-6759ce71-9dfd-439c-82f6-baf0366fb1c1.png">

It's not clear *which* services are deployed above but our assumption is that it's mostly frontend.

So we have two things that we need to investigate further: 

1. Why are we seeing so many restarts
2. Why do restarts block connection in repo-updater

One other avenue we went down was looking into these blocked queries:

<img width="1765" alt="Screenshot 2021-09-23 at 12 26 43" src="https://user-images.githubusercontent.com/25610/134492058-230c9dde-f82a-4d8a-9252-b8db822999d6.png">

Both repoo-updater and frontend run them but we couldn't draw any conclusions yet.

**Comment by indradhanush** [comment]
We have a strong conviction of the potential root cause of this issue thanks to @flying-robot! `syncRepo` acuiqres an advisory lock [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/repos/syncer.go?L295:15).

A fix is WIP here: https://github.com/sourcegraph/sourcegraph/pull/25341

We will monitor the changes once this is deployed to dotcom and come back to update the issue.

**Comment by indradhanush** [comment]
@ryanslade Assigned to you and removed my assignment as you're leading the effort on the fix now. :smile:

**Comment by ryanslade** [comment]
It looks like the merged PR above has solved the issue!

Once I've re-enabled the alert I'll close this.
