### ISSUE TITLE
dev/ci: make changedFiles calculation smarter in PRs

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#25164]
When preparing changedFiles we perform a diff against `main`. Right now, if you push the following commits to a PR separately:

1. A bunch of Go changes
2. A bunch of web app changes
3. A bunch of docs changes

In commit 1, Go tests run, then in commit 2 Go _and_ web tests run (well, actually _all_ tests run but assuming we improve that too) and in commit 3 everything is in the pipeline. Maybe we could find a way to perform the diff against previous runs of the same branch?

Related: https://github.com/sourcegraph/sourcegraph/pull/25229

**Comment by bobheadxi** [comment]
Thought: this depends on the previous commit having a build. If, e.g., 2 commits are pushed at once the diff might be misleading. Probably not too hard to query the Buildkite API here

**Comment by jhchabran** [comment]
Let's just use curl to get the build status of the previous commit
