### ISSUE TITLE
[Settings migration] Track total insights on an instance, by type if possible. 

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#25196]
Track total insights on an instance, by type if possible. 

We don't seem to have this and it's hard to do via settings files. 

We have long ago gotten RFC/bizops approval for this. 

Something of the form: 

```json
{
"codeStatsInsights":3,
"searchBasedInsights":81,
"searchBasedExtensionInsights":26,
"searchBasedBackendInsights":55
}
```

is perfect. It can just reflect total of all time (we can subtract to get differences week to week).

**Comment by Joelkw** [comment]
(cc @coury-clark )

**Comment by coury-clark** [comment]
@Joelkw 
A follow up question:

We have deprecated in the monikers "search based" and "lang stats" in the API and instead refer to presentation and data generation scheme. Would we get more value from the pings by reconstructing that pairing, or would we get equal value knowing:
1. search insights + line chart
2. search insights + pie chart
3. future other insight (webhook) + line chart
4. future other insight (webhook) + piechart

**Comment by Joelkw** [comment]
@coury-clark thanks for the heads up!

I think it makes sense to separate presentation and data generation scheme – in the future, perhaps search insights (of any kind/creation) could have either pie or line chart. My question for you and @CristinaBirkel would just be if there's a way to perhaps encode the "data generation" portion a bit more specifically? 

Both lang stats + search use 'search' but my understanding is they use different search endpoints? Similarly, for regex capture groups: would that be "search insights" (not ideal, lost info) or something like "capture group insights"? Basically, I agree with you about separating presentation + generation but to me (and users) lang stats and search based do different things and they are (I thought) generated a bit differently.

**Comment by coury-clark** [comment]
@Joelkw I think the problem is that they exist at different cardinalities

There is nothing about the data that prevents me from having a line chart with both capture groups series and regular search series. So we would really be counting insight-view-series in order to group by both chart type and generation scheme. Does that work for you?

**Comment by Joelkw** [comment]
@coury-clark ah, got it. Good point. Yeah, if we could do insightType-viewType-seriesType that would be great (using "Type" just to make it clear to my future self and others that this doesn't collect any information about the series like title or anything, it's purely "search insight – line chart – capture group" or similar). 

Does this mean, however, we need a separate set that is just insightType-viewType? How would we otherwise count # of insights (rather than # of data series)?

**Comment by coury-clark** [comment]
Let me back up a second and clarify what exactly we are interested in knowing. For example:

1. Plain search insight series
2. Capture group series
3. Global (backend) series (what about after we are doing repository scopes for backend series?)
4. Language stats series?

I think maybe I'm slightly trying to jam a square peg in a round hole, because some of these aren't exactly categories but more like implementation details of how we generate the data, whereas others are really different sources (capture group vs not, for example, or future webhook)

**Comment by Joelkw** [comment]
@coury-clark I see, thanks. 

I am interested in using this to generally understand "how much and what features of insights are a customer using?" which, when we have only 1-2 chart types, is basically "how many insights of each type". 

View count by chart type is nice but if we're saying that "lang stats + regex group + basic search" are all the same chart type, then I'd like to separate it out as well so we can understand how many of each "feature" is in use. 

**So your proposal of just counting "view count by chart type" (total insights) and then also counting – my proposal here – "display type + data series" would work, right?** 

This tells us how many different insight charts they have (view count) but the second part of this, the "display type + data series", also tells us if they're using a lot of regex capture group charts (which could be pie charts some day), a lot of language stats pie charts, etc. Would that work?

**Comment by Joelkw** [comment]
(Actually, reading it again, that may just be your proposal but stated in the reverse order of the two counts :) )

**Comment by Joelkw** [comment]
Notes from sync discussion where we left off: 

- Do 1 count of InsightType-Viewtyp pairs, like "line: 3, pie: 2" is 5 insights, 3 with line(s) and 2 pie charts
- Do 1 count of Viewtype-seriesType paris, like "line, capture group: 4" "line, search: 2", "pie, language: 2" is 4 capture group insights, 2 lines (could be 1 graph with 2 lines) of search insight data, and 2 language pie charts 
- Do 1 count of just data series by generation type, so "capture group: 2" is "2 unique capture group series" (which, combined with the above line, tells you at least 1 if not both series are repeated on line display graphs).
