### ISSUE TITLE
Improve sign-up message for smaller screens

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#25216]
#### Problem statement

The sign-up message is not good in using available space on small screens:

<img width="387" alt="Screenshot 2021-09-22 at 12 12 34" src="https://user-images.githubusercontent.com/3846380/134316408-31778700-ab98-4c31-8ea5-3b6bb55e3ece.png">

This could be fixed by splitting the content into two rows:
1. Search icon + text.
2. Create a free account" button.

To reproduce the issue visit the following [link](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:highlight.scss+type:diff&patternType=literal&case=yes) as a non-authorized user. 
The source code for the sign-up message is located [here](https://github.com/sourcegraph/sourcegraph/blob/3194d48bb5363d80f6ba057f9710726dcabff31f/client/web/src/search/results/StreamingSearchResults.tsx#L294-L318).

#### Success criteria

The message changes the layout on smaller screens to show content in two rows.

#### Things to learn/practice during the implementation

1. Apply CSS to build responsive UI. 
2. Learn more about how Sourcegraph repo uses CSS modules to build UI's faster.

#### Estimated amount of work

T-shirt size estimate: **S**.

**Comment by rosiegamgee718** [comment]
I'd like to work on this one, please? Thanks!!

**Comment by OlushesiToheeb** [comment]
I'll love @vanesa but I'm having problem with running the app locally on my pc
