### ISSUE TITLE
Why did Cloudflare caching suddenly break sign-ins to sourcegraph.com?

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#2521]
Figure out what caused https://github.com/sourcegraph/sourcegraph/issues/2520 to happen.

Situation:
- We have had Cloudflare caching enabled for while with no problems and we also rely on Cloudflare SSL proxying.
- This morning sign-ins (and sign outs) stopped working reliably. See https://github.com/sourcegraph/sourcegraph/issues/2520.
- We could not identify any Sourcegraph code, configuration, or deployments that could have caused this issue.
    - Auth code paths have not changed recently.
    - We rolled back sourcegraph.com to a time when sign-ins were known to be working, and sign-ins were still broken.
- We discovered that if we disabled Cloudflare proxying, sign-ins started working.
    - Since we had been relying on Cloudflare SSL proxying, we needed to generate a new SSL cert to get sourcegraph.com into a useable state without Cloudflare.
    - After the fact, we also realized that we could have just disabled Cloudflare caching while enabling SSL proxing (which is the state we are in currently).

Observations:

- Before we make a POST sign in request, we must have a valid CSRF cookie.
- Requests made without a CSRF cookie have one set by the middleware.
- Our `/sign-in` page (and all pages) have `cache-control: no-cache, max-age=0`
- It looks like we have configured Cloudflare to cache all pages
    ![image](https://user-images.githubusercontent.com/754768/53673185-f3f1f180-3c3a-11e9-8297-1847062c9478.png)
    > Cache-Control headers sending "private","no-cache", or "max-age=0" or Expires header with a date in the past will override the rule and cause Cloudflare to NOT cache the resource. To override these you'd need to add another setting called "Edge Cache TTL" and set it to however long you'd like Cloudflare to cache that resource on our servers.
    https://support.cloudflare.com/hc/en-us/articles/115000150272-How-do-I-use-Cache-Everything-with-Cloudflare-
    
    This could be a problem under the following scenario:
    1. On GET /sign-in, we only sometimes send a cookie. i.e., only if you haven't visited a different Sourcegraph page and already gotten a CSRF cookie.
    2. This means that some GET /sign-in requests do not have any cookies sent with them.
    3. This means CloudFlare observes no cookie in the response, and (possibly) decides it is OK to cache the response:
        > if there is a cookie in the response, then Cloudflare will not cache the resource.
    4. Someone else requests GET /sign-in, recieves the cached cloudflare version without the CSRF cookie they need and BOOM, failed sign in.

**Comment by nicksnyder** [comment]
I have deleted the "Cache Everything" rule above and re-enabled caching for sourcegraph.com. The site seems to be behaving as expected so I am going to close this for now. It is still unclear why this suddenly stopped working this morning because there are no changes to this setting in the Cloudflare audit log (until I deleted it).

**Comment by felixfbecker** [comment]
I think I am responsible for this - adding the rule was suggested to me by the Cloudflare support staff to fix #2467. I didn't realise when I added it that this would cause a problem with CSRF tokens and didn't see any issues in my own testing. Later in the evening when I read about the sign in fails I didn't think about my change. Sorry for the trouble.

**Comment by nicksnyder** [comment]
Thanks for the additional context. @ggilmore is working to move our Cloudflare config into Terraform so we will have more visibility into these changes in the future.
