### ISSUE TITLE
Move navbar from `wildcard/components` folder to `client/web/src/nav`

### ISSUE THREAD

**Issue by 5h1rU** [sourcegraph/sourcegraph#25241]
## Problem statement

Navbar is not considered a Wildcard library component anymore. Moving to a place outside wildcard is ideal for avoiding confusion about which elements belong to WCL.

## Success criteria

1. The `client/wildcard/src/components/NavBar` is moved to `client/web/src/nav/NavBar`
2. `NavBar` exports are removed from `client/wildcard/src/components/index.ts`
3. Imports in consumers are changed to use the new `NavBar` location — `client/web/src/nav/NavBar`.

**Comment by PuneetDabral** [comment]
please also assign this issue to me so i can learn more from you

**Comment by 5h1rU** [comment]
<html><head><meta content="text/html; charset=UTF-8" http-equiv="content-type"></head><body class="c10"><p class="c9"><span class="c14"></span></p><p class="c13"><span class="c14">Hi, @PuneetDabral thanks for helping us to improve our codebase. I want to point you in the right direction, please read the points below, and in case you have any questions don&rsquo;t hesitate to ask.</span></p><p class="c9"><span class="c14"></span></p><p class="c13"><span class="c5">If you want to run a local environment, you need to:</span></p><p class="c9"><span class="c5"></span></p><ol class="c4 lst-kix_7zbd0siveeiv-0 start" start="1"><li class="c2 li-bullet-0"><span class="c8">Clone the repo: git clone </span><span class="c17"><a class="c6" href="https://www.google.com/url?q=https://github.com/sourcegraph/sourcegraph/tree/main/client/web&amp;sa=D&amp;source=editors&amp;ust=1633119657843000&amp;usg=AOvVaw3lPjFYfvU74RgKKG1ggh5O">https://github.com/sourcegraph/sourcegraph/</a></span><span class="c5">&nbsp;</span></li><li class="c2 li-bullet-0"><span class="c5">Make sure your node environment is running version 16.x.x.</span></li><li class="c2 li-bullet-0"><span class="c8">In case you want to contribute, please sign our </span><span class="c17"><a class="c6" href="https://www.google.com/url?q=https://docs.google.com/forms/d/1Z8zQHZs1ycfOCaR8N43S2lalgsmTTeKoUizrc93xk6M/edit?usp%3Ddrive_web&amp;sa=D&amp;source=editors&amp;ust=1633119657844000&amp;usg=AOvVaw0gNMOKXd1tePmvw6u0ueQA">contributor license agreement</a></span><span class="c5">. Once you have already signed it, you will have permission to merge your contributions after an appropriate review and approval. </span></li><li class="c2 li-bullet-0"><span class="c5">If one or more people ask for the same issue, the first person asking for it will have the priority for the assignation.</span></li><li class="c2 li-bullet-0"><span class="c8">If you have any questions, please </span><span class="c17"><a class="c6" href="https://www.google.com/url?q=https://docs.sourcegraph.com/&amp;sa=D&amp;source=editors&amp;ust=1633119657844000&amp;usg=AOvVaw1_c2c5YxzOXFrNO7u5EUld">refer to the docs first</a></span><span class="c5">. If you don&rsquo;t find any relevant information, mention the issue author.</span></li><li class="c2 li-bullet-0"><span class="c8">Issue author will try to provide guidance. Sourcegraph always works in async mode. We will try to answer as soon as possible, but please take in mind time zones differences.</span></li></ol><p class="c9"><span class="c16"></span></p><p class="c9"><span class="c16"></span></p><p class="c13"><span class="c12 c19">Relevant development docs</span></p><ul class="c4 lst-kix_eyalsfe0q0yg-0 start"><li class="c1 li-bullet-0"><h2 class="c3">Getting applications up and running</h2></li></ul><ul class="c4 lst-kix_pjb5qkani51j-0 start"><li class="c11 li-bullet-0"><span class="c7"><a class="c6" href="https://www.google.com/url?q=https://docs.sourcegraph.com/dev/background-information/web/web_app%23commands&amp;sa=D&amp;source=editors&amp;ust=1633119657845000&amp;usg=AOvVaw3GGV94VxDGouYyOj5paPkA">Developing the Sourcegraph web app</a></span></li><li class="c11 li-bullet-0"><span class="c7"><a class="c6" href="https://www.google.com/url?q=https://docs.sourcegraph.com/dev/background-information/web&amp;sa=D&amp;source=editors&amp;ust=1633119657845000&amp;usg=AOvVaw1MhZJAAeO5VRLPjOkGzk8e">Table of contents</a></span></li><li class="c11 li-bullet-0"><span class="c12">Configuring backend services locally is not required for most frontend issues. However, a guide on how to do this can be found </span><span class="c7"><a class="c6" href="https://www.google.com/url?q=https://docs.sourcegraph.com/dev/getting-started&amp;sa=D&amp;source=editors&amp;ust=1633119657845000&amp;usg=AOvVaw1Gmft_Zs6dt-3N-Q0bwMHE">here</a></span><span class="c3">.</span></li></ul><ul class="c4 lst-kix_3zas2a5i95nk-0 start"><li class="c1 li-bullet-0"><span class="c3">How to style UI</span></li></ul><ul class="c4 lst-kix_rf4n86t5uo4-0 start"><li class="c11 li-bullet-0"><span class="c7"><a class="c6" href="https://www.google.com/url?q=https://docs.sourcegraph.com/dev/background-information/web/styling&amp;sa=D&amp;source=editors&amp;ust=1633119657846000&amp;usg=AOvVaw3uURly8kwLeCLcV69bQsPt">Guidelines</a></span></li><li class="c11 li-bullet-0"><span class="c7"><a class="c6" href="https://www.google.com/url?q=https://docs.sourcegraph.com/dev/background-information/web/wildcard&amp;sa=D&amp;source=editors&amp;ust=1633119657846000&amp;usg=AOvVaw3Mkjb1OX11H3Cgm4bRkrsy">Wildcard Component Library</a></span><span class="c3">.</span></li></ul><ul class="c4 lst-kix_3n1is42dcpeq-0 start"><li class="c1 li-bullet-0"><span class="c12">Client packages </span><span class="c7"><a class="c6" href="https://www.google.com/url?q=https://github.com/sourcegraph/sourcegraph/blob/main/client/README.md&amp;sa=D&amp;source=editors&amp;ust=1633119657846000&amp;usg=AOvVaw29M002ShQdkkPISe1ZMxt8">overview</a></span></li><li class="c1 li-bullet-0"><span class="c3">How to write tests</span></li></ul><ul class="c4 lst-kix_bm7arep89ur-0 start"><li class="c11 li-bullet-0"><span class="c7"><a class="c6" href="https://www.google.com/url?q=https://docs.sourcegraph.com/dev/background-information/testing_web_code&amp;sa=D&amp;source=editors&amp;ust=1633119657847000&amp;usg=AOvVaw0IlFDIlPQuHefqYTaB1w2y">https://docs.sourcegraph.com/dev/background-information/testing_web_code</a></span></li><li class="c11 li-bullet-0"><span class="c7"><a class="c6" href="https://www.google.com/url?q=https://docs.sourcegraph.com/dev/background-information/testing_principles&amp;sa=D&amp;source=editors&amp;ust=1633119657847000&amp;usg=AOvVaw0IEtqRTsshMVFCd4-7kH4E">https://docs.sourcegraph.com/dev/background-information/testing_principles</a></span></li><li class="c11 li-bullet-0"><span class="c7"><a class="c6" href="https://www.google.com/url?q=https://docs.sourcegraph.com/dev/how-to/testing&amp;sa=D&amp;source=editors&amp;ust=1633119657848000&amp;usg=AOvVaw3kKBIvXD4AxG-ojW8o5DM9">https://docs.sourcegraph.com/dev/how-to/testing</a></span></li></ul><ul class="c4 lst-kix_wo5d6il553z-0 start"><li class="c1 li-bullet-0"><span class="c3">Continuous integration pipeline</span></li></ul><ul class="c4 lst-kix_yevn1p7zn7mn-0 start"><li class="c11 li-bullet-0"><span class="c7"><a class="c6" href="https://www.google.com/url?q=https://github.com/sourcegraph/sourcegraph/actions&amp;sa=D&amp;source=editors&amp;ust=1633119657848000&amp;usg=AOvVaw0dn2doYKesZDI454paxgXT">Github actions</a></span></li><li class="c11 li-bullet-0"><span class="c7"><a class="c6" href="https://www.google.com/url?q=https://docs.sourcegraph.com/dev/background-information/testing_principles%23visual-testing&amp;sa=D&amp;source=editors&amp;ust=1633119657849000&amp;usg=AOvVaw3UzTscpRj-qjy-cAUEKDM5">Visual testing</a></span></li></ul><ul class="c4 lst-kix_fq4ix68xgtcj-0 start"><li class="c13 c15 li-bullet-0"><span class="c12">We use </span><span class="c7"><a class="c6" href="https://www.google.com/url?q=http://percy.io/&amp;sa=D&amp;source=editors&amp;ust=1633119657849000&amp;usg=AOvVaw2Nk09ZkXRfaCCQ_Ghrf_AS">percy.io</a></span><span class="c12">&nbsp;and </span><span class="c7"><a class="c6" href="https://www.google.com/url?q=http://chromatic.com/&amp;sa=D&amp;source=editors&amp;ust=1633119657849000&amp;usg=AOvVaw1VAN-DgkTMIUbAYAsunOfP">chromatic.com</a></span><span class="c3">&nbsp;for visual testing.</span></li></ul><ul class="c4 lst-kix_vuykz2trjmjz-0 start"><li class="c11 li-bullet-0"><span class="c7"><a class="c6" href="https://www.google.com/url?q=https://buildkite.com/sourcegraph/sourcegraph&amp;sa=D&amp;source=editors&amp;ust=1633119657850000&amp;usg=AOvVaw3Wx1F_E290Df2gjEw0xFid">Buildkite </a></span><span class="c3">is used to run most of our tests.</span></li></ul><ul class="c4 lst-kix_ywo4yhapf0h0-0 start"><li class="c1 li-bullet-0"><span class="c3">Pull Requests</span></li></ul><ul class="c4 lst-kix_ael2mfxr66az-0 start"><li class="c11 li-bullet-0"><span class="c7"><a class="c6" href="https://www.google.com/url?q=https://docs.sourcegraph.com/dev/background-information/code_reviews%23what-makes-an-effective-pull-request-pr&amp;sa=D&amp;source=editors&amp;ust=1633119657851000&amp;usg=AOvVaw3FceWH375qjxiP59W6_m8H">How to structure</a></span></li><li class="c11 li-bullet-0"><span class="c12">Pull Request </span><span class="c7"><a class="c6" href="https://www.google.com/url?q=https://about.sourcegraph.com/handbook/engineering/developer-insights%23prefer-small-prs-lines&amp;sa=D&amp;source=editors&amp;ust=1633119657851000&amp;usg=AOvVaw0Lvt99sn9UKJBGPoEXHkF6">size guidelines</a></span></li><li class="c11 li-bullet-0"><span class="c12">Git branch name convention: </span><span class="c20">[developer-initials]/short-feature-description</span></li><li class="c11 li-bullet-0"><span class="c12">See examples </span><span class="c7"><a class="c6" href="https://www.google.com/url?q=https://github.com/sourcegraph/sourcegraph/pulls?q%3Dis%253Apr%2Blabel%253Ateam%252Ffrontend-platform&amp;sa=D&amp;source=editors&amp;ust=1633119657852000&amp;usg=AOvVaw378oAuk6dJMiB2oPTmJ94k">on Github</a></span><span class="c3">.</span></li></ul><p class="c9"><span class="c3"></span></p><p class="c9"><span class="c14"></span></p><div><p class="c9"><span class="c14"></span></p></div></body></html>

**Comment by OlushesiToheeb** [comment]
I'll love to solve this issue @5h1rU

**Comment by OlushesiToheeb** [comment]
and also have been able to clone the repo but for me to `run` it locally am too follow [client/web](https://github.com/sourcegraph/sourcegraph/tree/main/client/web) doc right?

**Comment by OlushesiToheeb** [comment]
@valerybugakov did you get my previous comments

**Comment by pidoxy** [comment]
I'd love to work on this @valerybugakov @mrnugget @vanesa @5h1rU  pls How do I find the consumers file or folder? The third instruction on the issue's description

**Comment by vanesa** [comment]
@umpox might be able to help too :). Thank you for taking this on @pidoxy !
