### ISSUE TITLE
navbar: SCSS replace margin spacing for gap property.

### ISSUE THREAD

**Issue by 5h1rU** [sourcegraph/sourcegraph#25243]
Change all the margins for list elements and use gap property on the parent instead

Currently, we are using margin to add horizontal spacing between navbar elements. Replace this margin with the `gap` will simplify our code.

For example, [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/wildcard/src/components/NavBar/NavItem.module.scss?L6). We can remove the margin property and add a `gap` in the [parent element](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/wildcard/src/components/NavBar/NavBar.module.scss?L49).

<img width="543" alt="Screen Shot 2021-10-13 at 9 23 36 AM" src="https://user-images.githubusercontent.com/989826/137152543-18551a1b-cd59-4063-b554-49569ed112e1.png">

**Comment by deepto98** [comment]
@5h1rU I'd like to work on this, can you assign this to me? Also, can you point me to the stylesheet file referred to here?

**Comment by valerybugakov** [comment]
@5h1rU, could you add additional details to this issue?

**Comment by anthonygedeon** [comment]
hey @vanesa, it seems the link to the community space is broken, which link should I go to for help?
