### ISSUE TITLE
Decouple migrations: Update deployment of managed environments

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#25255]
Partially implements Step 3 in [RFC 469](https://docs.google.com/document/d/1_wqvNbEGhMzu45CHZNrLQYys7gl0AtVpLluGp4cbQKk).

Update Dogfood and Cloud environments to invoke the migration runner before deployments (in a blocking manner), and fail deployments if the migration runner does not succeed.

For Dogfood, we can run a container as a pre-step in ArgoCD. For Cloud, we should either wait for ArgoCD to become available, or add a few extra steps in the deployment pipeline to ensure the migration runner occurs first. This may cause issues in deployment with buildkite job timeouts (just shifting the problem to CI instead of deployment). Discuss possibilities with @sourcegraph/distribution.

Note that Demo and managed instances are running the most recent minor version and do not need to be CD'd (these are updated manually today).

**Comment by danieldides** [comment]
Sub issues:
- [ ] https://github.com/sourcegraph/sourcegraph/issues/31433
- [x] https://github.com/sourcegraph/sourcegraph/issues/31434
- [ ] https://github.com/sourcegraph/sourcegraph/issues/31435
