### ISSUE TITLE
Decouple migrations: Improve docker-compose upgrade process

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#25258]
Partially implements Step 4 in [RFC 469](https://docs.google.com/document/d/1_wqvNbEGhMzu45CHZNrLQYys7gl0AtVpLluGp4cbQKk).

Explore ways to improve the ergonomics of the docker-compose upgrade process. See if we can invoke the required command as part of the existing upgrade process.

**Comment by danieldides** [comment]
I think this one is covered by https://github.com/sourcegraph/sourcegraph/issues/25256

**Comment by efritz** [comment]
@danieldides You're right, will close. #25256 was originally meant to just update instructions on the manual process, but looks like both got rolled into the same effort.

Thanks!
