### ISSUE TITLE
`lang:Apex` search includes Progress, LaTeX, VB, and other languages

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#25262]
- **Sourcegraph version:** 
- **Platform information:** Sourcegraph.com

#### Steps to reproduce:

1. Search for [`lang:Apex`](https://sourcegraph.com/search?q=context:global+lang:Apex+&patternType=literal) (use [`lang:Apex -file:/force -file:/apex`](https://sourcegraph.com/search?q=context:global+lang:Apex+-file:/force+-file:/apex&patternType=literal) to remove most of the real apex code)

Examples of non-Apex code found with `lang:Apex` search:
* https://sourcegraph.com/github.com/sourcerer-io/sourcerer-app/-/blob/src/test/resources/samples/langs/TeX/problemset.cls
* https://sourcegraph.com/github.com/aquynh/capstone/-/blob/bindings/vb6/CX86Operand.cls
* https://sourcegraph.com/github.com/github/linguist/-/blob/samples/VBA/cApplication.cls

#### Expected behavior:
Only return Apex code when using `lang:Apex`

#### Actual behavior:
Returns LaTex, Visual Basic, some Progress, other misc languages

**Comment by benvenker** [comment]
@mike-r-mclaughlin we've had this come up with a couple other languages as well. @camdencheek I think you were the one I talked to about this last (though then it was with Smalltalk). Should I create an epic for these issues because they're part of a larger problem or are there one-off fixes that can be done per-language?

**Comment by camdencheek** [comment]
I'm not sure there is much we can do about this. `.cls` is a valid file extension for [many languages](https://sourcegraph.com/github.com/go-enry/go-enry/-/blob/data/extension.go?L172:49) (including Apex), and we determine the language of a file purely by the file extension. 

It's maybe theoretically possible to inspect the file contents to get slightly better accuracy, but that would be computationally expensive and still quite error-prone.

The only other option I can think of is to enable some sort of user-overridable setting for these extensions.

**Comment by camdencheek** [comment]
On a more general note, grouping similar issues like this under an epic would be useful since, if it's fixable, it's much easier to do all at once

**Comment by camdencheek** [comment]
Related issue, but for the issues it causes with highlighting: https://github.com/sourcegraph/sourcegraph/issues/20227

**Comment by benvenker** [comment]
Ok, that makes sense. Thanks for the context.

**Comment by keegancsmith** [comment]
@lguychard my holiday made me page out what was next for this issue and I can't remember what was said in team meeting (was't in our notes). I think we wanted to spend a day on this soon?

**Comment by lguychard** [comment]
The intent was for @rmmh to take this on, but I think last week ended up being too busy on support for him to get to it. We'd want to land this in the next release (cutting Nov 20th).

**Comment by keegancsmith** [comment]
@rmmh do you have bandwidth for this? Please say soon if not so someone else can pick it up.

**Comment by jjeffwarner** [comment]
From our sync this week:

1. Making frontend generate new zoekt search syntax for using ctags language detection
2. Adding flags to make the language detection more configurable

**Comment by jyavorska** [comment]
@lguychard can you please add a (conservative) estimate for when this will be delivered? Doesn't need to be exact, and it can change, but it's for the roadmap view at https://github.com/orgs/sourcegraph/projects/214/views/11.

**Comment by lguychard** [comment]
@jyavorska done.

**Comment by jjeffwarner** [comment]
Revised estimated delivery to Dec 3 to support additional complexity and unplanned PTO.

**Comment by rmmh** [comment]
Fixed in #28370

**Comment by keegancsmith** [comment]
@rmmh nice work. Don't forget a changelog entry :)

**Comment by rmmh** [comment]
https://github.com/sourcegraph/sourcegraph/blob/main/CHANGELOG.md

> Indexed queries with language filters now use file contents to recognize languages. For example, `lang:matlab` will no longer return an Objective-C `main.m`. [#28370](https://github.com/sourcegraph/sourcegraph/pull/28370)

**Comment by jjeffwarner** [comment]
Address some issues so the feature flag can be default on rather than off.

**Comment by jyavorska** [comment]
In the product engineering project, this item has a delivery date of FY22 Q4 which is in the past. @lguychard can you please take a look?

**Comment by jjeffwarner** [comment]
@jyavorska @lguychard I re-opened this ticket because we found an issue that needs to be addressed. I should have just created a new issue. I'll close this one and create a defect issue.
