### ISSUE TITLE
Search contexts CTA should be dismissable so users can access org/site-wide contexts without adding repos

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#25270]
If you have not added any repositories, you can't access the search contexts dropdown, instead getting the CTA:

![image](https://user-images.githubusercontent.com/206864/134418501-500e26ab-351d-417e-b683-d7c34e9a4253.png)

This blocks users from accessing org or site-wide contexts until they add repositories, which is not necessary.

The CTA should be dismissable so users can change contexts without needing to set up their own.

**Comment by marisak** [comment]
In-progress designs can be found on Figma: [25270: context-cta-popover](https://www.figma.com/file/5YVNZx1oXKbBpsam5OfBKf/25270%3A-context-cta-popover?node-id=22%3A30)

**Comment by benvenker** [comment]
@limitedmage looks like we're good to go with the "alt" designs in the figma.

ccc @marisak
