### ISSUE TITLE
code insights tests failing on CI because DB is not started

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#25285]
Example failure here: https://buildkite.com/sourcegraph/sourcegraph/builds/109199#fc0fde2d-0ab5-4012-88ed-c049a5163150

It looks like the DB is not started when the tests are run. Is this a race condition somewhere? We run the tests before we start the DB?

**Comment by mrnugget** [comment]
Debugging PR here: https://github.com/sourcegraph/sourcegraph/pull/25283

**Comment by mrnugget** [comment]
I think it might be a race condition between the codeinsights-db starting up **in the background, non-blocking** here

https://github.com/sourcegraph/sourcegraph/blob/dc9b64df64e9d6b7089a631950ea44097e26b659/dev/ci/go-test.sh#L13-L16

and the tests for the Go projects being started here: 

https://github.com/sourcegraph/sourcegraph/blob/dc9b64df64e9d6b7089a631950ea44097e26b659/dev/ci/go-test.sh#L18-L19

On CI it looks like the codeinsights tests pass when tests for other packages/projects started first, but when our main Go tests start first, then that is not enough time for the DB to start up in the background.

**Comment by mrnugget** [comment]
I think I have a fix:

1. We do set `export DB_STARTUP_TIMEOUT=120s` in `go-test.sh`
2. But in `dbtesting.TimescaleDB` we used `pgx` to connect to the DB, which does **not** take `DB_STARTUP_TIMEOUT` into account.

In my PR I switched to using `dbconn.NewRaw`, which retries for the time set in `DB_STARTUP_TIMEOUT`

**Comment by coury-clark** [comment]
Thanks for taking this!

I don't understand why this is happening *now*. My guess is something about the other troubles in CI brought this race condition to light, otherwise, it is really strange that something that has been running for 7 months suddenly starts failing consistently.

If I get some more time I'd like to dig in more to this entire codeinsights initialization, but I suspect I won't have time before we migrate to `pgsql` and away from Timescale.

If this happens again please let me know!

**Comment by mrnugget** [comment]
> I don't understand why this is happening _now_. My guess is something about the other troubles in CI brought this race condition to light, otherwise, it is really strange that something that has been running for 7 months suddenly starts failing consistently.

Or another Go project was added and the order changed? Or starting the Docker container got slower because of... whatever?

**Comment by coury-clark** [comment]
> Or another Go project was added and the order changed? Or starting the Docker container got slower because of... whatever?

Also possible, and maybe likely. Unless I'm thinking wrong I think any material changes to our repos that caused this would have meant somebody merged a red build which would be a problem for a different reason (unless the ci config is in a different repo? not sure). So I suspect that something about the build infrastructure changed (like you said, docker container startup time, etc.)

**Comment by mrnugget** [comment]
At this point I'm quite certain that ghosts are haunting our infrastructure, so anything's possible really.
