### ISSUE TITLE
codeintel-qa: pipeline failures

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#25304]
https://buildkite.com/sourcegraph/code-intel-qa/builds/4778#fe1c8927-490a-4791-97a9-c0dad886940e/60-1179

https://sourcegraph.slack.com/archives/C02F6E9JS2J/p1632411164089500

**Comment by bobheadxi** [comment]
appears to be fixed with revert of https://github.com/sourcegraph/sourcegraph/pull/25315 - cc @efritz ?

**Comment by eseliger** [comment]
at least it passed now :)

**Comment by efritz** [comment]
:(
