### ISSUE TITLE
sourcegraph-qa: pipeline failures

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#25305]
https://buildkite.com/sourcegraph/qa/builds/5629#e18ca3ec-6087-444f-88c6-6a34c0328c5f/41-1060

https://sourcegraph.slack.com/archives/C02F6E9JS2J/p1632412314094900?thread_ts=1632411952.092300&cid=C02F6E9JS2J

**Comment by bobheadxi** [comment]
Looks like this was fixed with https://github.com/sourcegraph/sourcegraph/pull/25329 and friends, though I see https://github.com/sourcegraph/sourcegraph/pull/25307 is still open?

**Comment by valerybugakov** [comment]
Fixes from https://github.com/sourcegraph/sourcegraph/pull/25307 were cherry-picked into other PRs. I think we can close this issue now since it's been fixed.
