### ISSUE TITLE
Ruby Find references returns no results for methods ending in !

### ISSUE THREAD

**Issue by DaedalusG** [sourcegraph/sourcegraph#25322]
# Ruby Find references returns no results for methods ending in !
- **Sourcegraph version:** Sourcegraph.com, Sourcegraph-Server v3.30.4
- **Platform information:** N/A

#### Steps to reproduce:
1. Find a file containing a ruby method ending in `!` [Example](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/rubocop/rubocop%24+foo%21&patternType=literal)

![Screen Shot 2021-09-23 at 5 30 06 PM](https://user-images.githubusercontent.com/13024338/134601095-90bf92dc-f92e-47fc-b623-02b94f30b990.png)

2. Hover over the method and select the `Find references` tooltip button [Example](https://sourcegraph.com/github.com/rubocop/rubocop/-/blob/spec/rubocop/cop/naming/memoized_instance_variable_name_spec.rb?L83:17&subtree=true#tab=references)

![Screen Shot 2021-09-23 at 5 29 48 PM](https://user-images.githubusercontent.com/13024338/134601142-90d07050-ace8-46b6-a212-4f4135f87f73.png)

Examples from Sourcegraph.com

#### Expected behavior:
The references panel should return results that can be found searching for the method name within the repo.

#### Actual behavior:
The references panel displays no results  From the above examples this can be seen not to be the case.

**Comment by chrismwendt** [comment]
Deployed a fix https://github.com/sourcegraph/code-intel-extensions/pull/687

<img width="929" alt="CleanShot 2021-09-23 at 19 23 23@2x" src="https://user-images.githubusercontent.com/1387653/134604185-25975db8-57b0-48aa-a229-e7e3838d3ef6.png">
