### ISSUE TITLE
Enterprise features show up and are enabled in free version and it is not clear if I am allowed to use them or not

### ISSUE THREAD

**Issue by DavidZidar** [sourcegraph/sourcegraph#25335]
#### Describe the issue
I am using the free OSS version of Sourcegraph via a single docker container and I see the following features in the UI and on the surface they seem to work too:
* Batch Changes
* Code Monitoring
* Code Insights

#### Where is the issue located?
The [pricing change](https://about.sourcegraph.com/pricing/) makes no mention of the last two features but the first one is clearly listed under Enterprise. There seems to be nothing stopping me from using this feature, I find this confusing.

#### Suggested resolution
List every major feature in a table and clearly indicate if they are available or not in the different editions.

Also, the landing pages of the features in Sourcegraph application itself should probably reflect if they are Enterprise only feature or not even show up at all in the free version.

**Comment by malomarrec** [comment]
@DavidZidar thanks for reporting this!
Can you describe how you installed Sourcegraph? Did you build from source, or follow the [quick-install guide](https://docs.sourcegraph.com/#quick-install)?

**Comment by DavidZidar** [comment]
@malomarrec I have been running it in a single Docker container since the start of 2019 using the official Docker images from DockerHub, I have not built anything myself.

**Comment by malomarrec** [comment]
@DavidZidar I just took a look at our README and docs page, and I see how it can be confusing, sorry about that. I'll submit a PR to clarify what is what.

- When you run our docker images, you are running the Free plan, of Sourcegraph Enterprise. This is written in the README is:
> Prebuilt Docker images are the fastest way to use Sourcegraph Enterprise. See the quickstart installation guide.
- To run Sourcegraph OSS, you can clone the repository and follow those [instructions](https://github.com/sourcegraph/sourcegraph#installation).

On top of that, the various plans of Sourcegraph Enterprise are sometimes not clearly enforced, which means you might see Batch Changes available in the Free plan of Sourcegraph Enterprise. We are working on a plan to roll out a clear separation.

I hope this helps, sorry about how confusing this all is, thanks for surfacing this.

**Comment by DavidZidar** [comment]
@malomarrec If I understand you right you are saying that the only way to run the free version is by building the source myself and not use the Docker container? That is quite surprising, the Licensing page in Site admin is saying I'm using Sourcegraph Free right now.

If I would be forced to build it myself I'm not sure I would keep using Sourcegraph. I'm guessing I wouldn't be able to afford the enterprise version. Maybe I misunderstood, but please consider allowing the container (or a separate container) be used for the free version.

**Comment by malomarrec** [comment]
@DavidZidar "Sourcegraph Free" means "the Free plan of Sourcegraph Enterprise", which allows up to 10 users, for free. This is what the Docker container runs.
Here is an explanation page from our (public) company handbook: https://about.sourcegraph.com/handbook/product/licensing#licensing

**Comment by DavidZidar** [comment]
@malomarrec I see, that just makes the pricing page even more confusing. Since I am a single user, does that mean I am in fact allowed to use the features mentioned above for free?

**Comment by DavidZidar** [comment]
@malomarrec If I understand you correctly then here's what I would suggest. Clearly brand Sourcegraph OSS and Sourcegraph Enterprise and list Sourcegraph OSS, Sourcegraph Enterprise Free and Sourcegraph Enterprise Paid as three separate entries on your pricing page. That would make it more obvious what to run and what features are available.

**Comment by malomarrec** [comment]
@DavidZidar you can run Sourcegraph for Free! Batch Changes and Code Monitoring should be on paying tiers, we are making sure that future releases make the distinction clearer :)

**Comment by malomarrec** [comment]
Thanks for the suggestion above 👆

**Comment by malomarrec** [comment]
As a first step, I clarified the readme:
https://github.com/sourcegraph/sourcegraph/pull/25336
