### ISSUE TITLE
I want Sourcegraph to delete old branches when a batch change execution is complete

### ISSUE THREAD

**Issue by ajaynz** [sourcegraph/sourcegraph#25340]
Raising feature on behalf of https://github.com/sourcegraph/accounts/issues/6312

Add an option to changesetTemplate like `deletesourcebranchonmerge` which will instruct Sourcegraph to create a PR with option to delete souce branch when a merge is complete and batch campaign is executed successfully.

Ability to delete source branch on merge is available on most code hosts.

**Comment by malomarrec** [comment]
Duplicates: https://github.com/orgs/sourcegraph/projects/119?card_filter_query=delete
