### ISSUE TITLE
project-automation: The property 'number' cannot be found

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#25347]
There was a failure in https://github.com/sourcegraph/sourcegraph/actions/runs/1270600336

Looks like the issue `number` was missing, not sure how/why that could happen. This workflow was triggered by closing an issue.

**Comment by felixfbecker** [comment]
Thanks for filing! This should already have been fixed by https://github.com/sourcegraph/sourcegraph/commit/21f3c911c8572aa3ef0c99cadc6581e54419f506 but let me know if you still see it.
The action linked above ran a few hours before that commit :)
