### ISSUE TITLE
dev/ci/cluster-ci: fix failing tests and re-enable tests

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#25346]
from https://github.com/sourcegraph/sourcegraph/pull/25338: https://buildkite.com/sourcegraph/qa/builds/5660#fcb9eba8-1546-4cb4-a4d6-38f96764aed0 cluster-ci tests fail after deployment

these are currently marked as allow-fail: https://github.com/sourcegraph/sourcegraph/pull/15678/files#r715748236

we should fix these tests and allow them to fail builds again

**Comment by bobheadxi** [comment]
Some weird stuff going on as well with some pods _sometimes_: https://sourcegraph.slack.com/archives/C02FLQDD3TQ/p1632940141086500

```
2021-09-29 18:17:34 UTC	codeintel-db-78b679b45f-48pzt                0/2     Init:0/1      0          96s
2021-09-29 18:17:34 UTC	codeintel-db-78b679b45f-v5v9p                2/2     Terminating   0          3m23s
```

We should do something like grep for non-`Running` pods at the end of a test run and fail if anything is not in a healthy state

**Comment by daxmc99** [comment]
I have noticed these typically occur with stateful data. I'm working to use hostPath for all of these services to reduce the need to spin-up PDs
