### ISSUE TITLE
Support wildcarding in search contexts

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#25352]
Context in [this](https://sourcegraph.slack.com/archives/C022SPMNR0W/p1632506289161600) Slack thread.

Basically, users want to be able to set a context for, in this case, a GitLab group, which would contain several repos, but they don't want to have to list them individually, they'd like to be able to do "repo:^gitlab.example.com/groupname/.*" and capture all the repos in that group.

**Comment by benvenker** [comment]
@novoselrok does this work actually fall with search product first, or do we blocked on other work?

**Comment by novoselrok** [comment]
I don't think we are blocked on this, and we could start designing this. This will require some backend restructuring to fit include/exclude patterns into search contexts, but nothing too drastic hopefully.

**Comment by benvenker** [comment]
Ok great, thanks!

**Comment by benvenker** [comment]
This feature is now available via query-based search contexts!
