### ISSUE TITLE
Better/more syntax highlighting in search bar

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#25377]
I find it difficult sometimes to find and differentiate between the string I'm searching and the text associated with a given filter or type. Would like to consider enhancing our highlighting in the search bar to make it easier to parse visually.

**Comment by benvenker** [comment]
@rrhyne our work on the "no results" page and going out of our way to explain literal search made me think of this. I think it would be a nice affordance to make it very clear what text is being searched, as opposed to the current state, in which it can be hard to differentiate filter params (not the filters themselves) from the search query. For example in some "normal" queries like the below.
![image.png](https://images.zenhubusercontent.com/5467e9ba7c6ccc6277a5f103/500d6a53-ca7e-40a7-be3c-123fcb96b579)

**Comment by camdencheek** [comment]
Closing since we've since improved syntax highlighting dramatically and also added "chip"-like UI elements to make the tokenization more visual.
