### ISSUE TITLE
Flake: code-intel-qa disabled

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#25387]
- **Name of test:** code-intel-qa
- **Example failure:**
https://buildkite.com/sourcegraph/code-intel-qa/builds/4847#296f3dc7-34cf-46f4-acb9-3b1f24a2fce7
https://buildkite.com/sourcegraph/code-intel-qa/builds/4845#ecff50fc-a139-482a-89ca-e6fb8839d0dd

<img width="809" alt="Screenshot 2021-09-27 at 12 17 12" src="https://user-images.githubusercontent.com/1408093/134899811-3cabe272-59c9-4e84-922e-ec96801bccb7.png">

- **PR**: https://github.com/sourcegraph/sourcegraph/pull/25386/files

#### Additional details

https://sourcegraph.slack.com/archives/CMBA8F926/p1632733591338100

**Comment by bobheadxi** [comment]
Duplicate: https://github.com/sourcegraph/sourcegraph/issues/25389
