### ISSUE TITLE
Upgrade canary test instances for docker-compose

### ISSUE THREAD

**Issue by dan-mckean** [sourcegraph/sourcegraph#25391]
Creating canary instances is an action item from the 3.30 retrospective. 

This issue proposes the following workflow to run `amcheck` tests (run once-daily):

1. Clone https://github.com/sourcegraph/deploy-sourcegraph-docker at the commit of the previous release
3. Create a VM base image that has two versions of https://github.com/sourcegraph/deploy-sourcegraph-docker:
- One at the version of the last release commit
- One at the latest version of the manifests with the latest docker images
4. Use vagrant to deploy the above base image 
5. Run `docker-compose up -d` to deploy the last release version
5. Run basic tests (add a user, add some repos, run a search) + amcheck at the last release version
6. If those pass, run `docker-compose up -d` with the latest docker image version of the manifest (in place upgrade)
7. Run basic + amcheck tests again 

We can expand on this template to rope in more extensive tests (e.g. our e2e tests into this workflow). However, the amcheck tests are sufficient to validate database integrity (which was the primiary motivation for these canary instances)

Notes:
- We choose to only run docker-compose instances for now. They're easier to deploy and customize, and the amcheck tests would run identically across both docker compose and kubernetes. 
- It's important to emphasize that the errors from the 3.30 database issue most likely wouldn't have been caught by e2e tests (since the way these issues manifest is non-deterministic). The amcheck tests

**Comment by virginiaulrich** [comment]
Closing this since we are doing this as part of managed instance upgrades/release process; would be ideal to automate, but that will be a new ticket as an output of team planning talks (if the team decides to do that work)
