### ISSUE TITLE
diff search: timeout not visible after scrolling down

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#25396]
When you scroll down a diff search and **then** it times out, you might miss the timeout message and think you hit the end of the results.

For example, this search times out after 20s: https://sourcegraph.com/search?q=context:global+repo:github.com/sourcegraph/sourcegraph%24+musl-tools+type:diff&patternType=literal

![](https://user-images.githubusercontent.com/1387653/134939977-2dfc47a7-479d-4f32-b095-5bf6680c0b90.png)

(originally from https://github.com/sourcegraph/sourcegraph/issues/25380)

cc @camdencheek

**Comment by camdencheek** [comment]
Yes! This is something that's [bothered me for a while](https://sourcegraph.slack.com/archives/CHEKCRWKV/p1628522890075200). 

I personally think the best solution here is to duplicate the "Some results excluded" component at the bottom of the page so users can actually see that when they are at the bottom of the page. 

Another option is to pin the bar that contains the "Some results excluded" box, and just scroll the results. 

Adding this to search priorities for next sprint

cc @rrhyne for design thoughts

**Comment by benvenker** [comment]
@camdencheek is this a bug or just something we want to improve?

**Comment by rrhyne** [comment]
This requires design because the current implementation uses a dropdown that is not suited for the bottom of the page.

**Comment by camdencheek** [comment]
Closing since the timeout message is now at the top of the page
