### ISSUE TITLE
monitoring: Grafana Cloud parity with /-/debug/grafana

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#25407]
With the restriction of site-admin access to dot-com, we need to provide another way for devs to access dashboards. Right now port-forwarding is an option for non-site admins, but it's not the most ergonomic solution.

We have a Grafana Cloud account set up at sourcegraph.grafana.net that is connected to logs and traces - we should bring it to parity with `/-/debug/grafana` and encourage its use.

- Set up external access for Grafana Cloud to get to our Prometheus instance (preferred), or [enable metrics collection in `grafana-agent`](https://github.com/sourcegraph/sourcegraph/issues/25407#issuecomment-928188517)
- Continuously upload the generator-output dashboards to Grafana Cloud (https://sourcegraph.grafana.net) that was set up so that we can avoid requiring privileged access just to access dashboards on https://sourcegraph.com/-/debug/grafana .

**Comment by bobheadxi** [comment]
cc @tsenart

**Comment by tsenart** [comment]
We need to configure `grafana-agent` for metrics as well. It's only configured for logs and traces right now.

**Comment by bobheadxi** [comment]
https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/docker-images/grafana/home.json#L1:1 we need to embed this into the generator as well (doesn't have to be integrated)

**Comment by bobheadxi** [comment]
cc @asdine @jhchabran I think I've got https://github.com/sourcegraph/sourcegraph/issues/25696 working and I've made both of you admins as well, so this should be unblocked now in case either of you want s to take a stab at this!

**Comment by bobheadxi** [comment]
I think we can close this now, appears there is ongoing work to leverage Datadog in Cloud instead
