### ISSUE TITLE
Support code host username search

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#25423]
See [this](https://sourcegraph.slack.com/archives/C0C324C91/p1632789532354100) Slack thread for context.

Basically, several people's first interaction with Sourcegraph search at a conference began with them searching their GitHub username. It would be nice to support this in a way similar to repo, where it's one of the first, fast matches suggested to a user when they type into the search box.

An interesting thing to think about here is what the typeahead should return. For example, I could see users wanting a GitHub-esque profile page, by default, that showed repos, commits, etc., similar to our repo pages and GitHub's actual profile page. But there are many other useful options we could show, so more research is needed here.

**Comment by camdencheek** [comment]
Closing since we have no plans to do this right now.
