### ISSUE TITLE
File tree loading indicator has poor spacing

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#2544]
When the file tree is loading, the "Loading" text and indicator does not have any (or enough) spacing.

**Comment by pdubroy** [comment]
Looks like this is still an issue:

![CleanShot 2021-06-25 at 16 58 02](https://user-images.githubusercontent.com/17293/123443892-98e82380-d5d6-11eb-997a-ebbaa68c7bc6.png)

**Comment by yowayb** [comment]
I'd like to take a stab at this.  Is there any guidance on what the spacing should be like?

**Comment by yowayb** [comment]
How's this?

![image](https://user-images.githubusercontent.com/603829/152855603-307816d6-24aa-4af1-9c7d-9331c6b47f32.png)
