### ISSUE TITLE
Executors pipeline can clog and fail main CI pipeline

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#25487]
We suspect that multiple main builds at the same time can cause delays in AMIs being created, hence leading to timeouts in the executor image builds. This breaks the CI build on main. We need to find a way to 
- Either only run this when something actually changed
- Reduce the pressure on AWS by using concurrency groups or similar
- Something entirely different

Also see [this conversation](https://sourcegraph.slack.com/archives/C02FLQDD3TQ/p1632862533041000) for more in-depth discussions.

**Comment by bobheadxi** [comment]
Example failure: https://buildkite.com/sourcegraph/sourcegraph/builds/109873#e5c6f353-334d-4fad-a639-991ba2566a52

**Comment by bobheadxi** [comment]
> Snapshot creation is a shared bandwidth operation. This means that Amazon EBS uses a shared bandwidth to send data to S3. Therefore, you might encounter delays if there are multiple volumes queued for snapshot creation. This typically happens if several snapshots are created at the top of the hour. For example, if you have automated processes to create snapshots exactly at midnight, then the snapshot creation might be delayed.

https://aws.amazon.com/premiumsupport/knowledge-center/ebs-snapshot-ec2-ami-creation-slow/

**Comment by bobheadxi** [comment]
I am going to build a mechanism for image build scripts to provide an identifier to determine whether an image build needs to happen at all. I think we can key the based on contents of the executor build dir + the binary itself:

```
~/Projects/sourcegraph/sourcegraph main*
❯ go build github.com/sourcegraph/sourcegraph/enterprise/cmd/executor   

~/Projects/sourcegraph/sourcegraph main*
❯ shasum executor
1f54e480d015e2a5b22f200a491aed6818ee073f  executor

~/Projects/sourcegraph/sourcegraph main*
❯ rm -rf executor && go build github.com/sourcegraph/sourcegraph/enterprise/cmd/executor

~/Projects/sourcegraph/sourcegraph main*
❯ shasum executor                                                                       
1f54e480d015e2a5b22f200a491aed6818ee073f  executor
```
