### ISSUE TITLE
"Invalid hover response" when browsing GitHub OSS project

### ISSUE THREAD

**Issue by jnm2** [sourcegraph/sourcegraph#255]
- **Sourcegraph version:** Sourcegraph Firefox extension 1.16.2
- **Platform information:** Firefox 62.0.3 64-bit

#### Steps to reproduce:

1. Install addin for the first time

2. Go to https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Internal/TestExecutionContext.cs (or any .cs file)

3. Hover over anything

#### Expected behavior:

No error.

#### Actual behavior:

![image](https://user-images.githubusercontent.com/8040367/46445355-6e7a1c00-c744-11e8-8424-00536d71b6e2.png)

**Comment by sqs** [comment]
This looks like a regression when we moved the hover normalization code to extensions

**Comment by arpitchauhan** [comment]
I get the same issue with the Chrome extension.

**Comment by nicksnyder** [comment]
@sqs Can you please post an update here about C# support?

**Comment by sqs** [comment]
We are removing experimental C# support for now. See https://about.sourcegraph.com/blog/java-php-experimental_language_servers-temporarily-unavailable. We hope to bring it back soon.
