### ISSUE TITLE
File tree should be closed by default on mobile

### ISSUE THREAD

**Issue by pdubroy** [sourcegraph/sourcegraph#25500]
From @sqs on [Slack](https://sourcegraph.slack.com/archives/C0W2E592M/p1632878500295800):

> Feedback from a friend - on mobile the file tree should be closed by default

![Image from iOS](https://user-images.githubusercontent.com/17293/135226279-c4ffed33-260f-43f3-b247-703faf07268b.jpg)

**Comment by KShivendu** [comment]
Hi @valerybugakov, I've faced this issue in the past and would love to fix it. Please assign it to me :)

**Comment by valerybugakov** [comment]
@KShivendu, feel free to send a PR!
