### ISSUE TITLE
5.5M Repos Indexed on Cloud

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#25516]
Tracking issue for the scaling work to grow the Sourcegraph Cloud global index to 5.5M repositories.

**Comment by lguychard** [comment]
## 2021-09-29 update

We’ve grown the Sourcegraph cloud global index to 2.1M repositories.

However, We’re still seeing significant site instability caused by the 2.1M scale (notably, frequent OOMs of the frontend service). While we’ve fairly confident we’ve identified the root cause, and have a fix brewing, stabilizing sourcegraph.com at this new scale has proven slower and trickier than we expected.

With this in mind, we are no longer confident in our ability to grow the sourcegraph.com global index to 5.5M without affecting site stability before the end of the month; we’d like to provide a revised timeline for hitting 5.5M, as well as clarification on the path forward.

Full update with proposed revised timeline [here](https://docs.google.com/document/d/1Tf-k6Nf_I6GDYyimohCil3v2uvjVNgSc_SulK_CK5Wc/edit#heading=h.ak7rp5zfj7a2).

**Comment by lguychard** [comment]
## 2021-10-05

OOMs are now fully resolved. We are switching our focus to making Zoekt index polling more efficient, another blocker for 5.5M.

**Comment by stefanhengl** [comment]
Closing this because we have decided not to pursue the 5.5m in favor of more relevant work.
