### ISSUE TITLE
Spike: gitserver "GetObject" move to KV store

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#25522]
This is a spike to trial our approach detailed here: 
https://docs.google.com/document/d/1U5KmrVRezD1wjs1g2dBkeCJIfGTJ4dzZ8zXudJaDNNU/edit#heading=h.9jg2bv44wmmu

We'll use it as both a test bed for our hexagonal architecture as well as a way to test the feasibility of having a non gitserver read path for some requests.

Initially we'll use redis as the backend since it already exists in our infrastructure and is well suited for simple KV data that is returned by `rev-parse`.

**Comment by eseliger** [comment]
experiment stopped.
