### ISSUE TITLE
quotes not interpreted correctly inside `(...)` in regexp mode

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#25532]
Results incorrectly _includes_ quotes for a query like: 

[`(file:node_modules/@angular/core/package.json "version")`](https://sourcegraph.com/search?q=%28file:node_modules/%40angular/core/package.json+%22version%22%29&patternType=regexp)

Explicitly adding `patterntype:regex` fixes it. So likely we're just missing code to add annotation for regexp interpretation, inside code that deals with `(...)` groups.

Results correctly do not include quotes, when the parens are removed: 

[`file:node_modules/@angular/core/package.json "version"`](https://sourcegraph.com/search?q=file:node_modules/%40angular/core/package.json+%22version%22&patternType=regexp)

---

Likely unrelated, but bundling here:

[`(file:node_modules/@angular/core/package.json content:"\"version\"") OR (import { Version } from '@angular/core';)`](https://sourcegraph.test:3443/search?q=%28file:node_modules/%40angular/core/package.json+content:%22%5C%22version%5C%22%22%29+OR+%28import+%7B+Version+%7D+from+%27%40angular/core%27%3B%29&patternType=regexp)

causing client disconnect. could not reproduce locally so may be a transient issue, not a query parser bug.

**Comment by camdencheek** [comment]
Can no longer reproduce. This has since been fixed, possibly by https://github.com/sourcegraph/sourcegraph/pull/60157
