### ISSUE TITLE
multiple `repo:contains` sometimes returns "no repo matches" and also matches

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#25580]
This doesn't always happen. It's weird.

<img width="1116" alt="Screen Shot 2021-09-30 at 5 06 28 PM" src="https://user-images.githubusercontent.com/888624/135546474-5dba8492-7c6d-4d58-ba89-156c14bfb9fb.png">

Seems similar to https://github.com/sourcegraph/sourcegraph/pull/25536 but probably issue is in predicate logic where we propagate results and not match count?

[local query](https://sourcegraph.test:3443/search?q=repo:contains%28file:changelog+content:fix%29+AND+repo:contains%28file:test+content:test%29+count:1000&patternType=literal)

**Comment by camdencheek** [comment]
`repo:contains` logic has since been rewritten and this query runs fine
