### ISSUE TITLE
Ideas for simplifying Sourcegraph extension settings/configuration

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#256]
## Problems and confusion related to settings

- "Add/remove" have no semantics. Users only enable/disable extensions, and sometimes that overrides settings of lower precedence.
- "Remove" is so rarely used that spending any UI on it is a waste.
- It's easy to forget your browser extension is pointed at a different Sourcegraph URL when you're on the extension registry
- The state of each extension is hidden behind a gear icon:

![image](https://user-images.githubusercontent.com/1387653/46446118-459b5c00-c72f-11e8-8ec8-7c470429da20.png)

The change in https://github.com/sourcegraph/extensions-client-common/pull/50 helped simplify the UI and I'd like to go a bit further.

## Constraints and goals

- **Anonymous** users must be able to toggle settings and enable/disable extensions
- Users must be able to enable/disable an extension in **1 click** from the extension registry
- Users must be able to see **why** an extension is enabled/disabled directly on the registry page (not needing to open up 3 different settings pages to find out)
- It's obvious when a user is enabling/disabling extensions on a Sourcegraph instance that's different from what their browser extension is pointing to

## Proposed changes

- [x] Eliminate "add/remove", keep "enable/disable". Removal is so rare that it can be relegated to manual updates of settings. https://github.com/sourcegraph/extensions-client-common/pull/56 https://github.com/sourcegraph/sourcegraph/pull/286
- [x] Convert the gear into a toggle for enabling/disabling, and add a little `i` info icon with a tooltip that says where the extension is enabled/disabled. https://github.com/sourcegraph/extensions-client-common/pull/56 https://github.com/sourcegraph/sourcegraph/pull/286
- [ ] Eliminate client settings and instead cache user settings (see https://github.com/sourcegraph/enterprise/issues/13242). When an unauthenticated user toggles Codecov, the cache will be updated even though there are no user settings backing it. Then when that user signs up, either the cache gets written to user settings or wiped out entirely (I haven't decided which).
- [ ] Add a browser extension status indicator (could be a yellow warning ⚠️  near the top of the registry page that says "Hey, your browser extension is pointing to a different Sourcegraph URL, so any changes here will not take effect on code hosts"
- [x] "Ext" debug menu in the bottom right - https://github.com/sourcegraph/browser-extensions/pull/228

## Comments

- @sqs Do you foresee any fundamental problems with these ideas?
- @slimsag Would these changes simplify the UI and mental model?

**Comment by slimsag** [comment]
These changes seem good, and we should do them, but I am still extremely disappointed that we still have not added back the default of add/remove extension being "global" via the UI. I think that is _the biggest_ flaw with the extensions configuration today in on-prem deployments.

In other words, yes, on Sourcegraph.com we probably want users to individually add extensions. But in a company setting, I don't want you and me to have different extensions in general. And this really sucks for code discussions.

-- 

> Eliminate "add/remove", keep "enable/disable". Removal is so rare that it can be relegated to manual updates of settings.

Agree.

 > Hey, your browser extension is pointing to a different Sourcegraph URL, so any changes here will not take effect on code hosts

As a user and developer @ Sourcegraph I don't know what this means or what I should do differently based on it. I would file an issue and ask for help.

**Comment by slimsag** [comment]
Me and Chris chatted synchronously about the add/remove UI default being global or user based.

The conclusion we came to is that having the default be user makes sense, but admins should have the same UI effectively for doing it globally as well.

**Comment by sqs** [comment]
This sounds great and is much better! Thanks!

@francisschmaltz Please make sure you understand this and the reasoning why, so designs take it into account and you can communicate this to other folks on the team. And if you have any better ideas, now is the time. 😃

**Comment by sqs** [comment]
@chrismwendt When do you plan to make these changes? I am free to pair on this if it’d help

**Comment by chrismwendt** [comment]
@sqs I started working on removing client settings yesterday. Specifically, I'm working on tweaking the configuration cascade subject so that when user settings don't exist, they're replaced by the cached settings from the browser extension (if the browser extension is connected). Still more to think about here.

I might hop on switching to toggles and adding the browser extension status indicator since those are easier to accomplish.

I'd like to get it in the release, so I plan to work on these today. Let me know if you want to take some of these tasks or pair on thinking through how to remove client settings (I'm free anytime until 10pm Pacific).

**Comment by chrismwendt** [comment]
I completed bullets 1 and 2. Now I'm going to continue with bullet 3 (eliminate client settings).

**Comment by chrismwendt** [comment]
Eliminating client settings is more involved than I thought, so I'm tabling this for now. If/when I come back to this, I need to:

- Implement client-side prediction
- Store user settings per Sourcegraph instance
- Figure out a clean way to cache user settings
- Change the communication between the browser extension and the Sourcegraph instance (if both can edit user settings, how do updates get propagated? Need to avoid cycles)
