### ISSUE TITLE
Browser extension breaks styles on GitLab v10.8.7

### ISSUE THREAD

**Issue by KattMingMing** [sourcegraph/sourcegraph#2560]
The Sourcegraph browser extension breaks the GitLab header on v10.8.7. See screenshot below:
![gitlabsourcegraphextissue](https://user-images.githubusercontent.com/4897310/53753765-e4ef8700-3e66-11e9-9681-e9ee0c20ea34.png)

**Comment by sqs** [comment]
@lguychard If this occurs on GitLab.com, it’s a high priority (3.2). Otherwise it can wait.

**Comment by lguychard** [comment]
This does not happen on gitlab.com

![image](https://user-images.githubusercontent.com/1741180/53800283-ab894b00-3f3c-11e9-930b-75ccfe15185c.png)

Gitlab 10.8.7 is a security release from July 2018, the current version of gitlab is 11.8.

Backlogging, to be prioritised after 3.2.

**Comment by felixfbecker** [comment]
I'd say this is safe to close because that release is over a year old now
