### ISSUE TITLE
Raw API: 500 when fetching kubernetes/kubernetes

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#2569]
- Visit https://sourcegraph.com/github.com/kubernetes/kubernetes@4b1282d9258e13791970a20395df4a6ec2613856/-/blob/cmd/kube-proxy/app/server.go#L236:24 to trigger the language server to fetch `curl -H 'accept: application/zip' https://a2e77a474d18f55f7971f024a2e25c38ef55af09@sourcegraph.com/github.com/kubernetes/kubernetes@4b1282d9258e13791970a20395df4a6ec2613856/-/raw`
- Notice an error in the browser console

![image](https://user-images.githubusercontent.com/1387653/53786129-8a3e4580-3ecf-11e9-8ade-5550cb1cc301.png)

Here's [the 500 in stackdriver](https://console.cloud.google.com/logs/viewer?interval=NO_LIMIT&project=sourcegraph-dev&minLogLevel=0&expandAll=false&timestamp=2019-03-05T06%3A44%3A46.941000000Z&customFacets&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22container%22%0Aresource.labels.pod_id%3D%22sourcegraph-frontend-56564b86fc-rw8mc%22%0Aresource.labels.zone%3D%22us-central1-f%22%0Aresource.labels.project_id%3D%22sourcegraph-dev%22%0Aresource.labels.cluster_name%3D%22dot-com%22%0Aresource.labels.container_name%3D%22frontend%22%0Aresource.labels.namespace_id%3D%22prod%22%0Aresource.labels.instance_id%3D%221691855115502292775%22%0Atimestamp%3D%222019-03-05T06%3A44%3A33.229020587Z%22%0AinsertId%3D%221o7ph7cfpjmjjo%22&scrollTimestamp=2019-03-05T06%3A44%3A33.230609582Z&dateRangeUnbound=forwardInTime):

`... msg="ui HTTP handler error response" ... error="failed to fetch missing archive cache item: failed to copy and close missing archive cache item: exit status 128 (stderr: \"error: object file .git/objects/74/b1201277c0a87e8b2d9cc4747d62c691168c18 is empty error: object fil... (truncated)\")" ...`

cc @slimsag for raw API knowledge
cc @keegancsmith for gitserver knowledge

**Comment by keegancsmith** [comment]
This now works. If you see this again I will investigate, but given how low we would prioritize investigating it (unless it happens again) I'll just close it
