### ISSUE TITLE
Fall back to basic code intel if hover/def takes too long

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#2571]
Sometimes it takes 10+ seconds for a hover to appear on moderately-sized repos (especially immediately after opening a file). A couple of examples:

- 8s to initial hover for TypeScript https://sourcegraph.com/github.com/sourcegraph/codeintellify@1936b9668f7f622f71d21670e224d1c2b9b84449/-/blob/src/hoverifier.ts#L455:82
- 11s to initial hover for Go https://sourcegraph.com/github.com/sourcegraph/sourcegraph@f5b050d5295224c8fd7bdff3b7cc2a2062de590e/-/blob/cmd/symbols/internal/symbols/parse.go#L66:35

This can be mitigated by falling back to basic code intel after a threshold amount of time elapses (e.g. 500ms).

**Comment by nicksnyder** [comment]
Please move this to an appropriate milestone since 3.2 is about to close.

**Comment by chrismwendt** [comment]
Closing because falling back reduces users' confidence in code intelligence https://github.com/sourcegraph/sourcegraph-go/pull/57#issuecomment-478829153
