### ISSUE TITLE
Do not drop search indexes and repo clones as soon as repo is deleted

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#2572]
Give some time before removing in case the admin makes a mistake. This is to prevent unnecessarily recomputing indexes.

Additionally we should do the same logic for gitserver clones.

Proposed solutions: Do not delete until repo has been removed from the repos table for 1 hour.

**Comment by keegancsmith** [comment]
cc @sourcegraph/distribution

**Comment by keegancsmith** [comment]
### Proposal for gitserver

Removing repository:
- mv to `.morgue/$path`
- modify timestamp of something reliable to now

Bury job:
- use atomic removal on stuff older than 1 hour based on above timestamp.
- If a timestamp is in the future, adjust timestamp to now (account for weird
  fs stuff).

Free diskspace job:
- Clear out `.morgue` first

Cloning:
- Try revive from `.morgue`

Morgue should only be used by repo-updater rm job. Other janitor jobs should
directly remove to prevent us reviving bad repos.

**Comment by slimsag** [comment]
Makes sense to me and sounds reasonable.

Is 1h long enough? If an admin makes a mistake and all repos disappear, they'll contact us and if we don't get back to them and identify the cause soon enough.. then it sounds like the bury job would run and we'd lose the data and have to reclone.

**Comment by mrnugget** [comment]
Sounds good to me!

> Cloning:
> 
> Try revive from .morgue

Then we need to remember that we also need to fetch again so we don't restore an outdated state and forget to update it

Regarding the timeframe: no opinion really. If you know what you're doing you want the repos to be gone immediately, and if you made a mistake you want them around as long as needed to restore. Hard to pick a value here that satisfies both needs, I guess.

Slight suggestion regarding naming: I do like `.morgue`, but maybe we should call it `.trash`? Everybody understands the concept of a trash: move things into the trash, empty trash, move things out of trash. And having that would possibly make explaining the behavior easier to site-admins:

"I deleted 1000s of repos but Sourcegraph is still taking up disk space!"
"Yes, we're moving them to the trash first and if they haven't been touched in ~x hours, we delete the trash. You can empty the trash manually by doing foobar"
"Ah, I see"

**Comment by keegancsmith** [comment]
Its a trade-off between admins recovering from mistakes and freeing up disk space. Given we have a disk space freeing job, we can actually be more conservative for time to recover. How about 6 or 12 hours?

**Comment by keegancsmith** [comment]
### Proposal for zoekt

All changes are to zoekt-sourcegraph-indexserver since it is currently
responsible for both indexing and removal.

Removing shard:
- mv to `.morgue/`
- touch index
- store in memory that the index is for a repo@commit

Bury job:
- remove all shards older than 1 hour.
- If a timestamp is in the future, adjust timestamp to now (account for weird
  fs stuff).

Indexing:
- If we have shards for repo@commit, move back into `./`.
  - Bail out if any shards in morgue are missing (avoid incomplete indexes)
  - Bail out if any target shards exist (avoid inconsistent indexes)
  - If bailing out, remove shards from morgue.
- continue indexing as usual after

We move to =.morgue= so zoekt-webserver unloads the shard from
memory. zoekt-sourcegraph-indexserver doesn't have any disk freespace jobs. We
should consider adding one which deletes from morgue and exports prometheus
metrics.

**Comment by keegancsmith** [comment]
Ok will use `.trash` instead. I was enjoying my morbid naming, but that is far more practical :P

**Comment by tsenart** [comment]
@keegancsmith: As for git-server, what prevents us from just increasing the interval of the purger go-routine to something like 24h?

**Comment by keegancsmith** [comment]
> @keegancsmith: As for git-server, what prevents us from just increasing the interval of the purger go-routine to something like 24h?

Do we want to rely on luck? As it stands an admin would likely update their cluster during their office hours => purger runs at some point in the office hours. Additionally if a service restarts within 24 hours we lose the cleanup that day. However, our services shouldn't restart unexpectedly.

This solution does seem somewhat acceptable if we don't run purger straight away + randomize it a bit. WDYT?

**Comment by tsenart** [comment]
> This solution does seem somewhat acceptable if we don't run purger straight away + randomize it a bit. WDYT?

Either that or we run it at a specific time of day. Seems simpler than the above proposal. We could even increase 24h to something bigger, like weekly cleanup.

**Comment by keegancsmith** [comment]
It is simpler, but I worry that it still leads to bad behaviour. However, the weekly cleanup seems like a good idea to avoid the fact that midnight is timezone aware, but our app runs in UTC. I have memories of an admin complaining that we didn't clean up repositories quick enough, which is why we introduced our cleanup job in the first place (before we had a bi-monthly cleaner).

But given the simplicity of the solution, I'm very keen to do this and see what our admins say. If we get complaints, then we may need to implement the more complicated solution. 1am UTC on a Sunday? 

Others that have commented on this issue, thoughts? @slimsag @mrnugget 

Note: We still need the more complicated solution for zoekt, since reclaiming RAM quickly is very important. Alternatively we could introduce some coupling between the indexserver and webserver, but I'm not at all keen for that and appreciate the current design of zoekts components.

**Comment by mrnugget** [comment]
> I'm very keen to do this and see what our admins say. If we get complaints, then we may need to implement the more complicated solution. 1am UTC on a Sunday?

Agree with this! Let's use the simplest version, ship it, gather feedback and iterate on it.


> I have memories of an admin complaining that we didn't clean up repositories quick enough, which is why we introduced our cleanup job in the first place (before we had a bi-monthly cleaner).

Do you think a weekly clean-up would be enough for that admin?

**Comment by keegancsmith** [comment]
No idea! I think it was asked for due to other issues we had. So should be fine.

**Comment by keegancsmith** [comment]
An interesting side-effect is we would likely never have the repos cleaned up on our dev instances, since most of us likely aren't running our dev environments at that time.

**Comment by tsenart** [comment]
@keegancsmith: A new feature that would perhaps pair well with this simpler approach would be to provider a button somewhere in the admin area to explicitly trigger a clean-up of deleted repos in git-server, as a way to fast-track this process if necessary.

**Comment by keegancsmith** [comment]
yup if we hear feedback about that. For now though, I prefer avoiding more UX/API surface area which can just be automated.

**Comment by slimsag** [comment]
SGTM but please update docs somewhere to mention when we do cleanup exactly
so admins / others can be aware of it

**Comment by keegancsmith** [comment]
Done. Gitserver: https://github.com/sourcegraph/sourcegraph/pull/4417 Zoekt: https://github.com/sourcegraph/zoekt/pull/7
