### ISSUE TITLE
Removing enabled/disabled for synced repositories

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#2574]
In the new repository syncer (#2025) we no longer will have an enabled/disabled state. Additionally, only the syncer will control deletion of repositories. As such we need to update the UI to:

- Remove enable/disable/deletion actions for Github repositories.
- Educate admins to update external service configuration.

For the short-term proposals below we would like to ship these changes in 3.2 since they block the release of the new syncer.

### Repo Listing Page

Short-term Proposal: Grey out the enable/disable button. Update tooltip to educate user about updating external services.
Long-term Proposal: Button jumps to external service configuration for that repository's external service.

Additionally Github repositories do not indicate enabled/disabled. (If not deleted, they are always enabled). As such github repositories always show in the enabled filter, and never in the disabled filter.

![image](https://user-images.githubusercontent.com/187831/53803923-ce245f80-3f4e-11e9-8288-0d065296cf00.png)

### Repository option page

Short-term Proposal: Replace this page with text explaining external services.
Long-term Proposal: Link to external service configuration for the repository.

![image](https://user-images.githubusercontent.com/187831/53804113-49861100-3f4f-11e9-94f9-a51c67338ec1.png)

The text can probably match what we use for visiting repositories that exist but are not enabled:

![image](https://user-images.githubusercontent.com/187831/53804210-94078d80-3f4f-11e9-9b17-c64bcf268c14.png)

**Comment by keegancsmith** [comment]
@sqs assigned to you to make product decisions / re-assign.

**Comment by nicksnyder** [comment]
My proposal:
- Repo Listing Page: remove the "enable/disable" button.
- Repository option page
  - short term: replace this page with an explanation of external services (remove delete/disable buttons)
  - longer term: add button to jump to configuration of external service that provides this repo

**Comment by sqs** [comment]
For SiteAdminRepositoriesPage repository items, RepositoryErrorPage, and RepoSettingsOptionsPage, I was thinking that there would be 2 variants:

- One variant for repositories synced by the "new repository syncer", which is kept up-to-date with config and has no enable/disable concept (i.e., GitHub repositories in 3.2): similar to what was said above, removing the enable/disable button, adding a link to the external services page (ideally the specific external service, if that's too hard then just the list of external services) with a tooltip like "To remove this repository, update this repository's code host configuration to omit it".
- One variant for repositories synced by the old repository syncer (i.e., non-GitHub repositories): same as today

If a site has both variants of repos shown in the SiteAdminRepositoriesPage list, some list items would have different buttons than others.

The benefit of this is that it is an all-or-nothing change for users: either their repos are new-variant or old-variant. There is no intermediate state or confusing transition. Most sites have repositories  from only a single code host, so it is rare that the 2 variants would be in use at the same time (which could cause some confusion, but it'd be the rare case).

If it would be confusing to implement this (e.g., you hope to entirely remove the old repository syncer), let me know and I will think about how to create the transition state for non-GitHub repos in 3.2.

**Comment by keegancsmith** [comment]
@sqs this is implementable. Our change supports having only github on the new syncer and all others the old style. Next milestone we will have all codehosts on the new syncer.

**Comment by sqs** [comment]
Moving to 3.3 and assigning to @keegancsmith 	and @tsenart because this is related to #2025

**Comment by tsenart** [comment]
Thanks for the linking these issue @sqs.

**Comment by keegancsmith** [comment]
Forgot this issue existed. This work has been done in https://github.com/sourcegraph/sourcegraph/pull/3380 and https://github.com/sourcegraph/sourcegraph/pull/3341. The earlier PR hasn't been merged yet, but we are tracking it in #2025 so gonna close this issue out.
