### ISSUE TITLE
Search tour popup can be distracting when scrolling

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#25776]
Source: [slack](https://sourcegraph.slack.com/archives/C0W2E592M/p1633548648392800)

> In all browsers, the "Get started" onboarding widget really irritates me, it doesn't stay in place and instead "lags behind" as I scroll which makes the whole experience feel even more laggy and draws my attention to it - instead of the marketing content - as I scroll up/down.

**Comment by camdencheek** [comment]
Closing since the widget has since been redesigned.
