### ISSUE TITLE
codeintel: Apply policies to groups of repositories

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#25788]
We have a way to attach policies to _all_ repositories or _one_ repository. We should be able to attach policies to _groups_ of repositories matching some types of conditions.

What those conditions look like are up for discussion (please weigh-in in comments here).

**Comment by eseliger** [comment]
Another possibility might be to utilize search contexts.
In their simplest form, we could convert the current repo groups on dotcom into search contexts (Actually, I think that is what search product is currently doing anyways). So if we added support for hooking a search context up with a policy, this could **cover the repogroups case**.
I am not sure (and could not find any info on that in some issue searches, so we need to confirm with them) what the future plans for search contexts are, but they **support all of _my_ repos with auto generated search contexts already**.
I assume the same would be implemented for orgs soonish, which makes sense once orgs can import repositories (SaaS effort), and there might be more things that are useful, like globbing. Maybe these workstreams can be combined and you would not need to implement something new here at all. Perhaps worth some chat.

**Comment by efritz** [comment]
Proto usage of search contexts (although it's doing it in a stupid way directly through the db): https://github.com/sourcegraph/sourcegraph/pull/26067
