### ISSUE TITLE
insights chore: Fix error message when trying to run unit tests without the db running

### ISSUE THREAD

**Issue by CristinaBirkel** [sourcegraph/sourcegraph#25799]
[This didn't alert me](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/insights/dbtesting/insights.go?L32)  when I tried running `go test` without the codeinsights-db running. (My test hung for at least several minutes and it took me a while to understand why.)

First thought: maybe they should be `fmt.Println` statements instead, because `t.Log` only prints out when the test completes?

Note from Coury: Maybe that is a side effect of the recent changes to the dbconn? It used to skip immediately if the database wasn't running.

**Comment by leonore** [comment]
@CristinaBirkel the link to this file is broken. I'm going to close this issue since this hasn't been raised since, is probably no longer relevant.

**Comment by CristinaBirkel** [comment]
Yeah, it used to be that the db needed to be specifically started and running. Now it's always running (I think? It is the way I have it set up anyway,) so yes fair to close this issue.
