### ISSUE TITLE
Sign sourcegraph/server docker images

### ISSUE THREAD

**Issue by KattMingMing** [sourcegraph/sourcegraph#2579]
Users / companies may only want/have permission to run signed docker images. Our images are currently unsigned which isn't a major issue for most users since content trust is disabled by default. Users can enable it via `DOCKER_CONTENT_TRUST=1`.

Signing images could be done in a similar way to Mongo. `latest` is unsigned, but tagged releases are signed.

See Docker documentation for more details on content trust: https://docs.docker.com/engine/security/trust/content_trust/

**Comment by ggilmore** [comment]
sourcegraph/server:3.1.1 has been signed and a pushed to a separate docker repository https://hub.docker.com/r/sourcegraph/server-signed. 

This doc contains basic/scant instructions for how to sign a new image for sourcegraph/server-signed: https://docs.google.com/document/d/1x5WIu-1XgQMhHUZPIs955dVoZ65JVzp9roJSyORjMzE/edit.

More investment will be put into this if more users request signed images.
