### ISSUE TITLE
Remove requirement for `repo:` filter on code monitors

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#25803]

**Comment by camdencheek** [comment]
We are considering doing this because the effective current limit is 10000 repos right now, which is large enough that most customers don't need to add a `repo:` filter in order to successfully run a code monitor. 

However, on sourcegraph.com, and with very large customers (I think Capitol One has a scale of like 100k), they will exceed this limit. Since this may be dynamic (more repos may be added after the code monitor is created), I think the best path forward is to notify on searches that return errors. This way, if they configure a monitor with 12k repos, they will get an email that says "too many repos searched. consider adding a repo: filter" or something of the sort. 

cc @benvenker

**Comment by benvenker** [comment]
Noted. It's come up that customers with large amounts of repos can take a "federated" approach to their org and so aren't necessarily going to monitor all repos, but rather different team will have distinct monitors/approaches to monitoring so we may be in better shape than we think, even for bigger clients.

**Comment by camdencheek** [comment]
Closing as done. There is no limit to the number of repos monitored anymore.
