### ISSUE TITLE
Unable to search on Sourcegraph.com using repo keyword

### ISSUE THREAD

**Issue by KattMingMing** [sourcegraph/sourcegraph#2580]
Currently seeing this frontend error when trying to search on Sourcegraph.com with a `repo` keyword.

<img width="1792" alt="screenshot 2019-03-05 08 19 01" src="https://user-images.githubusercontent.com/4897310/53819750-60147400-3f1f-11e9-9bb6-d900130c13e1.png">

**Comment by ijsnow** [comment]
Rolled back to a new version and reverted the guilty commit
