### ISSUE TITLE
Add feedback capabilities to SG 

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#25839]
As an engineer, I can immediately provide feedback on any command of command group of `sg`. 

It could look like: 

```
sg ci --feedback
sg run redis-postgres --feedback
sg ... --feedback
``` 

And it would take you to https://github.com/sourcegraph/sourcegraph/discussions/categories/developer-experience to create a new thread or possibly point you to an existing one. 

Another possibility is to have 

```
sg feedback anything you want here 
``` 

and send you to that exact place. 

In any of those scenario, we could package along the way a bunch of metadata (`sg doctor` output? `sg version` ... ?)

**Comment by jhchabran** [comment]
cc @mrnugget 🧑‍🍳

**Comment by vrto** [comment]
Awesome idea :)

I and JH chatted about possibly expanding this with happy/unhappy DX tracking, so anything you feel like something is going smoothly, you can just:

`sg happy`

or

`sg happy something worked well, and I felt productive.`

and we can do it from the other perspective, such as unhappy/sad;

`sg unhappy`

or

`sg unhappy I am stuck on trying to install yarn or whatever.`

Potentially happy/unhappy can be the same thing as feedback, but they'd carry a positive/negative 'mood value' so we know how well we're doing (or not), and what are some hot spots to look at. It could be a helpful data point.
