### ISSUE TITLE
Repository language is not updated anymore

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#2586]
In https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/0a137981f3628128a3952cb1ea79681ac3e5f7bf we removed the code that updated the `repo.language` DB column, so GraphQL-querying `Repository.language` will return empty for newly added repositories (and the previous, possibly stale language for repositories that existed before that commit).

**Comment by tsenart** [comment]
Looking at history, it seems it never was set in that query. It was set with `repos.UpdateLanguage`, which I think stopped being called in [this PR](https://github.com/sourcegraph/sourcegraph/pull/584/files#diff-1167f49285cd564ecdab1a422ff7ffc3L91)

**Comment by tsenart** [comment]
@sqs: Did you add this to the 3.2 milestone purposefully or is this meant to be in the backlog?

**Comment by sqs** [comment]
I added it to 3.2 and assigned to myself as I planned to find someone to work on it in 3.2. When you guys assigned it to yourself I assumed you planned to fix it in 3.2. Since it sounds like you don’t, I will reassign it to myself to figure out how to get it fixed in 3.2.

**Comment by beyang** [comment]
@keegancsmith @tsenart We can compute this on the fly. Is there still a reason to write it to the database in the background (e.g., `SELECT`ing by language)?

**Comment by keegancsmith** [comment]
@beyang I believe this is done? Can you close if so.

**Comment by keegancsmith** [comment]
Fairly certain this is fixed by https://github.com/sourcegraph/sourcegraph/pull/4775
