### ISSUE TITLE
Expose full repository languages/file types inventory via GraphQL

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#2587]
##  Backend
Each repository has a full "inventory", which is the result of processing all of its files, determinining their languages, and counting bytes of each language/file type. This is not exposed in  GraphQL; only the top language is exposed (via `Repository.language`). We should expose the full inventory so that API consumers can see all of the languages in use in the repository.

Also, it should include line counts, not just byte counts.

Details: For every Git tree and blob, there should be a GraphQL field `inventory` that exposes:

- All languages found in the tree/file (files obviously only have one language right now), in an array of the following for each detected language:
  - Language names and other metadata (eg "is this markup or code?") that the `inventory` package already produces
  - ~Number of bytes of this language~ (have not actually heard this from a customer)
  - Number of lines of code of this language (can be naive lines, no need to use SLOC or anything)

The most common use case is to get this info for a repository at its HEAD commit, so there should be a `Repository.inventory` field that returns this info for the HEAD commit's root Git tree.

The language determination from the existing `inventory` package is sufficient. No need to make it more advanced.

The expected usage patterns are mainly:

- Querying across many/all repositories (eg up to 30k repositories)
  - This should be possible, but it is OK if it takes minutes or hours and requires repeated calls until the data is computed and cached for every repository. Basically, there should be a way to get this info for that many repositories, but it doesn't need to be instant or even very fast.

## UI
- Show this on the directory page
- Seeing this in the UI (eg on a tree page) like the GitHub languages breakdown on the repo page
  - So caching this computation is probably a good idea. It doesn't need to be precomputed; it can be computed on-the-fly if not cached.

## Related Info
Related: #2586

Customers:

- https://app.hubspot.com/contacts/2762526/company/464956351 
- https://app.hubspot.com/contacts/2762526/company/732945850 
- https://app.hubspot.com/contacts/2762526/company/557476190 
- https://app.hubspot.com/contacts/2762526/company/419771425 
- https://app.hubspot.com/contacts/2762526/company/407948923
- https://github.com/sourcegraph/issues-uber/issues/188

**Comment by keegancsmith** [comment]
> Querying across many/all repositories (eg up to 30k repositories)

Is there more specific information on why a customer wants to do this and how important it is?

**Comment by sqs** [comment]
@keegancsmith:

> Is there more specific information on why a customer wants to do this and how important it is?

https://app.hubspot.com/contacts/2762526/company/464956351 specifically asked for this, and they have that scale. They would like to be able to compute these stats over all repositories to know how their usage of languages is changing over time (eg "are we using more or less of $LANG?").

Based on demos and conversations with the other companies mentioned in the top comment (where the decision maker for deploying Sourcegraph would have seen immediate product value if Sourcegraph were able to give stats about language usage), it would also be an effective element of the initial demo. It would be something that directly gives the decision maker value, instead of just giving value to their team. For example, in the demo, we would ask "Do you even have a way to know which languages are in use?" "No." "Sourcegraph can tell you - here's a Python script [and in the future, a UI screen] that hits our API and tells you. Run it!" "Wow, this is a new capability that lets me plan hiring/training better...and there were these other questions I wanted answered: ..." (which leads to more good high-level product value conversations).

**Comment by christinaforney** [comment]
While working on repo stats, make sure to include lines of code via API: [related issue](https://github.com/sourcegraph/issues-uber/issues/188)

**Comment by christinaforney** [comment]
More information about lines of code requirement can be found about API needs (#1235) and UI request (#1517).

**Comment by keegancsmith** [comment]
Similar to https://github.com/sourcegraph/sourcegraph/issues/1235#issuecomment-510911635 I didn't notice this being added to 3.6 milestone. For adding tasks like this, do you mind commenting on our tracking issue so we can discuss / plan appropriately.

**Comment by christinaforney** [comment]
> Similar to [#1235 (comment)](https://github.com/sourcegraph/sourcegraph/issues/1235#issuecomment-510911635) I didn't notice this being added to 3.6 milestone. For adding tasks like this, do you mind commenting on our tracking issue so we can discuss / plan appropriately.

Yes, will do - my fault for not making sure it was on the radar!

**Comment by tsenart** [comment]
I don't recall us including this in our last planning meeting. Perhaps this was assigned the 3.6 milestone tentatively, prior to that.

**Comment by christinaforney** [comment]
> I don't recall us including this in our last planning meeting. Perhaps this was assigned the 3.6 milestone tentatively, prior to that.

Yes, I had put it into 3.6 tentatively for you to decide if you wanted to include it - I had included it in my planning Google doc that I shared with all of the teams letting everyone know what priorities I was thinking about for them to consider in their planning: https://docs.google.com/document/d/1c_4QOUjXL0vRMNyttm79MpaUc_je7EpKMZ8m1TQcUJc/edit# 

It sounds like using the tracking issue for that communication with the core services team would be better?

**Comment by slimsag** [comment]
A user at https://app.hubspot.com/contacts/2762526/company/407948923 has requested this, in particular this aspect would be beneficial to them:

> Number of lines of code of this language

**Comment by keegancsmith** [comment]
I believe this is done? @sqs is there anything left to do (I know you were experimenting with the API recently). If not can we reach out to customers who requested this?

**Comment by sqs** [comment]
It’s still feature-flagged off by default. With @ryanslade on parental leave 😀 someone else needs to test it at scale and assess whether we can just enable it for all (or if we need to have certain customers enable it and collect perf feedback from them first). @beyang @slimsag can then tell the customers they work with that they can start using it. 

#7137 lowercases field names, but that’s a quick change for customers when they next upgrade and needn’t block customers using it (although it is annoying).
