### ISSUE TITLE
search-core high level monorepos discussion

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#25899]
This is capturing some thoughts around work for search-core to tackle monorepos soon. It is _very_ light on details. The intention is to have discussion and flesh out a bit. This isn't a tracking issue/etc, but more an "email thread".

Once we have some consensus from the team, we can edit this line and add some details. Ideally our plans will end up in some artifact which can be shared (maybe this issue?)

cc @sourcegraph/search-core

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket, please let us how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
