### ISSUE TITLE
Warn admins of potential issues with non-https 

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#259]
Several things might break unexpectedly if the server is not accessed via https, such as 
https://twitter.com/joaoqalves/status/1047808163381227520?s=2. Need to find a way to help the admin avoid these problems.

**Comment by ryan-blunden** [comment]
This will be addressed by a screencast that shows how to add SSL with a browser trusted certificate before the 3.2 release.

**Comment by ryan-blunden** [comment]
Also [replied to the tweet ](https://twitter.com/joaoqalves/status/1047808163381227520) that prompted the creation of this issue.
