### ISSUE TITLE
Allow repo-centric and user-centric permissions sync to be enabled/disabled independently

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#25903]
#### Feature request description

Allow a site admin to enable/disable either repo-centric or user-centric permissions syncing.

#### Is your feature request related to a problem? If so, please describe.

See Slack discussion starting [here](https://sourcegraph.slack.com/archives/C022SPMNR0W/p1633663221282900?thread_ts=1632866395.192500&cid=C022SPMNR0W).

From the above thread:
> If we want to only rely on either user- or repo-centric syncing, we need to disable the other, because if they run simultaneously and yield inconsistent results (i.e. different list of repos due to token permissions), they'll keep overwriting each other (i.e. a user sometimes could see repos because user-centric syncing just finished, but sometime can't because repo-centric syncing just finished).

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.

**Comment by pjlast** [comment]
See this RFC: https://docs.google.com/document/d/1ZjTRgfk2fWqK7_dRs92h0kCGxY8lgKQ7rL09C453E8k/edit#

I'm thinking the minimal effort we can do that adds value is what is described here: allow the site-admin or config or so to disable a sync mechanism if they want.

**Comment by unknwon** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IAM-627aebcc9f8b7c00128a8ab6/issues/sourcegraph/sourcegraph/25903?planning-poker) with ZenHub @kopancek @miveronese @pjlast

**Comment by kopancek** [comment]
This has now been done.
