### ISSUE TITLE
Repository listing page has too much indentation.

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#2591]
![image](https://user-images.githubusercontent.com/67471/53834431-3b55e600-3f8b-11e9-9b63-6cca4e9228df.png)

**Comment by nicksnyder** [comment]
This is a regression since 3.1. I am going to git bisect to see if I can identify the commit.

**Comment by nicksnyder** [comment]
This regressed in https://github.com/sourcegraph/sourcegraph/commit/d42ed0fc19e22603abb2a4358d257dcb2e8b77fb

Assigning to @chrismwendt .

**Comment by chrismwendt** [comment]
Ah, looks like I missed a CSS selector somewhere. Looking now.
