### ISSUE TITLE
Diff results are not syntax highlighted

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#2592]
Go to https://sourcegraph.com/search?q=r:sourcegraph/+type:diff+author:nick

I don't see diff or syntax highlighting on results:
![image](https://user-images.githubusercontent.com/754768/53840280-91586880-3f4e-11e9-982a-00c7274c37dd.png)

I could have sword that this was working last week so it feels like a recent regression.

**Comment by sqs** [comment]
My markdown changes to remove our docsite markdown may have broken this. I thought I tested it but it may have been before another change of mine that broke it again. @attfarhan I think it’s best for you to fix it now though.
