### ISSUE TITLE
some search unit tests behave differently in CI vs local dev

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#25936]
In https://github.com/sourcegraph/sourcegraph/pull/25721 I refactored the way in which search functions are called:

Previously, roughly:

```
doResults 
-> FileAndPathSearch 
-> SearchFilesInRepos
-> IndexedSearchRequest (Zoekt) to partition index/unindex repos
````

Now, roughly:

```
doResults
-> FileAndPathSearch 
-> IndexedSearchRequest 
-> SearchFilesInRepos
```

Basically, the IndexedSearchRequest thing happens before `RunSearchOverRepos`. It turns out that we have a bunch of tests (search for this issue number in our code) that mocked out various functionality at the `SearchFilesInRepos` call, which is mocked in our tests. By moving the `IndexedSearchRequest` code before it, something happened where code is getting called that passes in local testing of `go test ./...` but hangs (times out after 10 mins) in CI. 

[example job](https://buildkite.com/sourcegraph/sourcegraph/builds/110869#effe32f2-381e-4830-837f-fd791a3b7cf5)

I couldn't pin down the root cause of this, and likely some functionality in `IndexedSearchRequest` cannot just be called in some environments like CI, and needs to also be mocked (since this has been previously prevented from being called, by the mocking code). In https://github.com/sourcegraph/sourcegraph/pull/25721 I decided to disable the affected tests from running in CI for the following reasons:

- these tests and the gymnastics of working with the mocks have always been meddlesome
- to "properly fix", i.e., in order to keep the tests working in CI would probably mean mocking an additional function along this path. i'm actively working on this code and don't want it to incur more mocking costs, it's a productivity killer
- the code that these unit tests cover are functionally covered by integration tests (and indeed, backend search tests pass in CI, which rely on a live instance, even though the unit tests become borked)
- some tests are very low value (looking at search suggestions) which will hopefully be superseded by search suggestions being powered by clients via the search stream interface (Rok is currently working on this)
- i would actually prefer we find a way to remove and/or better mock out these tests, but that's a potentially big undertaking. i can't justify just removing them right now, in case someone works on things locally and only runs local unit tests without the delay of CI catching it later

**Comment by camdencheek** [comment]
Closing since this code has changed dramatically since this was opened.
