### ISSUE TITLE
Explicit email consent

### ISSUE THREAD

**Issue by dan-mckean** [sourcegraph/sourcegraph#25942]
### Timeline for release: 3.34 (approx 2021-11-20)
---
As per [RFC 453](https://docs.google.com/document/d/1kcUqV5G2y_w72a6qZm4rl-e2QknncsHSnglHn_I5il0/edit#bookmark=id.t2j6o0wq8zmk), we need to add explicit T&Cs acceptance to the account creation flow.

This ticket is limited to the non-cloud instances of Sourcegraph (namely managed instances and self-hosted).

I’d hoped we could do it without redirects, but that will trip us up later as just having a checkbox on the signup page doesn’t solve the need for future T&Cs updates (and requiring users to re-accept). Plus it’s a bad UX.

Instead, I think the logic needs to be something like:
1. Post-authentication (regardless of method), during sign-up OR sign-in, check for T&Cs acceptance date set for that user
2. If date >= date of latest T&Cs update THEN END
3. If no date or date < latest T&Cs update THEN redirect the user to the T&Cs page
4. If date is already set, show extra explanation text that the T&Cs have changed since last accepted
5. Require user to accept to proceed
6. If user bounces, sign them out (or some other method to prevent them getting to anything else til accepted)

Designs (courtesy of @quinnkeast): https://www.figma.com/file/FrsayNrNEiyYBwi4og3KZy/25942-%E2%80%93-Explicit-T%26C-Consent?node-id=1114%3A4018

Notes:
- No need to automatically check for changes to the T&Cs - only substantial changes are worthy of requiring reacceptance we'd not want to trigger that if someone changes formatting or a typo.
- Currently trying to find out if there's a requirement for keeping track of previous (not just latest) acceptances - [Slack question](https://sourcegraph.slack.com/archives/C02GLLN94DT/p1634219319000700?thread_ts=1633434849.002700&cid=C02GLLN94DT) - answer: no.
- We should add something to the page to explain to the user seeing the interrupt _why_ they're seeing it (one of a couple of reasons)

**Comment by jplahn** [comment]
Closing this as search product is doing this work: https://github.com/sourcegraph/sourcegraph/issues/28716
