### ISSUE TITLE
Support Github Wiki

### ISSUE THREAD

**Issue by OliverCardoza** [sourcegraph/sourcegraph#25955]
#### Feature request description

Github provides the ability to have a Wiki per repository: [About wikis](https://docs.github.com/en/communities/documenting-your-project-with-wikis/about-wikis). These Wiki's are effectively a git repo with a flat list of markdown files. For a repo of the form:

```bash
https://github.com/USER_OR_ORG/REPO_NAME
```

The wiki git repo is hosted at:

```
https://github.com/USER_OR_ORG/REPO_NAME/wiki
```

The presence of this Wiki is indicated by the `has_wiki` parameter of the Github API repository response: [Repository parameters](https://docs.github.com/en/rest/reference/repos#create-an-organization-repository--parameters).

#### Is your feature request related to a problem? If so, please describe.

Github searches includes results from wiki content, however, Sourcegraph does not. See Github documentation here: [Types of searches on Github](https://docs.github.com/en/search-github/getting-started-with-searching-on-github/about-searching-on-github#types-of-searches-on-github). When evaluating sourcegraph vs Github search this lack of support means that sourcegraph queries may miss expected results.

#### Describe alternatives you've considered.

Use Github pages instead for hosting documentation. These repos are included in Github API calls which list all repos (wiki's are not included there it seems? makes them slightly more hidden).

#### Additional context

If you could please provide some technical pointers on how to navigate adding this feature I'll take a look.

**Comment by micimize** [comment]
Related: GitLab Wiki support #2837

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket, please let us how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
