### ISSUE TITLE
External services form UI shows wrong copy when invalid external svc is created

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#2599]
From https://github.com/sourcegraph/sourcegraph/pull/2570#issuecomment-469646852

1. Create an external service with a failing config. So valid from a JSON schema perspective, but invalid from the repo-updater syncing perspective. Example: bad token.
1. Add it.
1. The UI responds with an error message prefix: warning: external service created, but sync request failed.
1. The UI still doesn't believe the service was created. I would expect the buttons to say "update" rather than "create".

**Comment by keegancsmith** [comment]
Its not just wrong copy, you can continue to press create and it will keep creating a new copy of the service each time.

**Comment by mrnugget** [comment]
Fixed by https://github.com/sourcegraph/sourcegraph/pull/4148
