### ISSUE TITLE
Transition on file tree navigation drawer

### ISSUE THREAD

**Issue by RamV13** [sourcegraph/sourcegraph#26]
It would be nice if there was a CSS transition or something upon opening the file tree navigation drawer.

**Comment by beyang** [comment]
Thanks for using the product and filing this feedback. Unfortunately, this feature request is underspecified (which CSS transition?), so it's not really actionable for the team. I'm going to close it for now, but feel free to re-open if there's a specific request.

**Comment by beyang** [comment]
Thanks for using the product and filing this feedback! Could you shed some more light on what kind of CSS transition you'd like to see?

**Comment by RamV13** [comment]
A transition on the `width` such that the drawer doesn't suddenly appear and translate all page content over to the right would be nice.

**Comment by sqs** [comment]
This has been changed significantly, and the original issue is no longer a problem.
