### ISSUE TITLE
Show yellow banner for external service warnings

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#2600]
From https://github.com/sourcegraph/sourcegraph/pull/2570#issuecomment-469646852:

Perhaps it makes more sense to show a yellow banner when an external service is created, but the sync step fails.

**Comment by sqs** [comment]
It sounds like @keegancsmith 	intended to do this for 3.2, so I am adding it to 3.2.

**Comment by keegancsmith** [comment]
@sqs this is part of the frontend UI changes we depend on for repo updater work. Who is the most appropriate person to own it?

**Comment by keegancsmith** [comment]
This does not block the 3.2 milestone, so moving to 3.3

**Comment by mrnugget** [comment]
Fixed by https://github.com/sourcegraph/sourcegraph/pull/4148
