### ISSUE TITLE
Code intelligence is slow

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#26015]
I observed this on https://github.com/sourcegraph/sourcegraph/pull/25993/files

https://user-images.githubusercontent.com/10532611/137129438-c65b1060-d9aa-4c12-a886-51b5d2ded0a1.mov

- At ~1s, the cursor touches the token.
- At ~8s, the hover tooltip code intel content appears.

This makes it ~7s to get code intelligence for a hover, which makes it slow enough that it doesn't provide value (making code review faster: Cmd+F would be faster) or that I even cancel it after a few seconds because I might assume it's broken.

On the right you see the requests the code intel extension is making during the waiting time, with the first request appearing at ~2s, indicating that the slowness/bottleneck is within the code intel extension or backend (not the browser extension or extension host, although they may be contributing ~1s).

**Comment by chrismwendt** [comment]
It's faster now:

https://user-images.githubusercontent.com/1387653/162336979-7a16bd27-f15f-4fa8-a93a-31dba0de0546.mp4
