### ISSUE TITLE
UI papercut: search sidebar has different hover state animations

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#26022]
On the search sidebar, different items have different animations for showing the hover state. This makes it feel inconsistent.

Quick Loom recording as a demo: [https://cln.sh/xO7bua](https://cln.sh/xO7bua)

I previously talked in Slack about [removing css transitions everywhere](https://sourcegraph.slack.com/archives/C01TFNBHYCV/p1628689768001400), but haven't made an explicit issue for it yet. Would it be better to address this as a standalone issue, or make the unifying issue to address it everywhere?

**Comment by camdencheek** [comment]
Closing since the sidebar has since been redesigned
