### ISSUE TITLE
commit search before a time returns different results for the same repository in two installs

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#26033]
The following query `repo:^github\.com/sourcegraph/sourcegraph$ type:commit before:2021-06-30T00:00:00-07:00 count:1` returns different results depending on the installation.

## On dot-com:
returns revision `0991e4f34061072cc33aba785863511aec9c345b`

```
Author:     Ryan Hitchman <hitchman@sourcegraph.com>
AuthorDate: Tue Jun 15 23:46:50 2021 -0600
Commit:     Ryan Hitchman <hitchmanr@gmail.com>
CommitDate: Mon Jul 19 10:38:40 2021 -0600
```

## Running Sourcegraph locally 
running on `57c491594b39b6114198d969b18db806421538b7` (current HEAD)
returns revision `450e8700f57eb7bb3ff45b4957ac0aaa8a9b96d3`
```
Author:     Stephen Gutekanst <stephen@sourcegraph.com>
AuthorDate: Tue Jun 29 23:11:33 2021 -0700
Commit:     GitHub <noreply@github.com>
CommitDate: Wed Jun 30 06:11:33 2021 +0000
```

Despite the discrepancy, it is not accurate that the last commit prior to `2021-06-30T00:00:00-07:00` was on `June 15` on `sourcegraph/sourcegraph`.

**Comment by camdencheek** [comment]
Reopening because this is definitely not fixed
