### ISSUE TITLE
Root slash in file path should preserve current rev

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#26068]
At https://sourcegraph.com/github.com/sourcegraph/careers@21da628a87bb37543aa779122bf1d36fee0ee7b3/-/tree/events, I expect clicking the `/` in the file path (see screenshot below) to take me to the root at the current rev (`21da628...`). This is how the other components in the file path breadcrumb work. Instead, it takes me to the root at the default branch.

![image](https://user-images.githubusercontent.com/1976/137223991-91680f3e-e886-41ca-a132-fe5b04ec61c5.png)

(BTW, the addition of the root slash is great! #25489 #24946)

**Comment by pdubroy** [comment]
@AlicjaSuska - does the proposal make sense to you?

**Comment by AlicjaSuska** [comment]
Yes, I agree with @sqs

**Comment by oleggromov** [comment]
This is now fixed in production, please check the original link.
<img width="1279" alt="Screenshot 2021-12-16 at 15 30 51" src="https://user-images.githubusercontent.com/2196347/146372485-8f0a0788-ed0e-4859-9a87-4417031e4d51.png">
