### ISSUE TITLE
canonical search

### ISSUE THREAD

**Issue by b-j-p** [sourcegraph/sourcegraph#2607]
#### Feature request description

I wish I could make something like the following search from the primary search page:

```componentDidMount |* js```

Think of this search as piping a very basic query into a "javascript canon," as defined by Sourcegraph. I am piping an exact match query in this case, but it might be a type:symbol or a regex query as well.

Such canons might be compiled for each language: a living representation of repositories containing code that is found to be exemplary in that language or ecosystem -- on the basis of the number of github stars on the project, sure, but probably on the basis of some more sophisticated curation process. I don't know how many repositories you would need represented in a canon. But let us say 50, arbitrarily, and then let that have ramifications on the kind of results I get back from my search. 

If all goes perfectly well -- imagine for a second that every project in the `js-canon` is a react project -- instead of getting this response as I do currently when I search for `componentDidMount`:
<img width="982" alt="Image 2019-03-05 at 11 12 06 PM" src="https://user-images.githubusercontent.com/29590320/55355572-8e816280-547d-11e9-9d18-c0ba881ef561.png">
I now see a list of 50 results -- familiar looking results, pretty much just as you are used to seeing when searching across a single repository or repo-group. BUT! these results are substantive references to locations in files across the `js-canon`.

In this idealized case, each item in the list of results would be a substantive reference to a single location in a single file from a different one of the fifty repositories represented in the `js-canon`. 

In principle, each result from the list would serve me as a model, or exemplar, of how this particular lifecycle method looks when it is used by the best teams, in the standard way. But not only that, each result would also serve me as a hook, if and when i click through, into one of the projects in the `js-canon`, which is full of interesting and exemplary code. 

#### Is your feature request related to a problem? If so, please describe.

Nope. No problems to report.

#### Describe alternatives you've considered.

Obviously, repo-groups exist! And I am very glad they do. The user is today free to put together a personally curated canonical group of repos for each language. But I am thinking of something quicker and more dynamic. Something built into the guts of Sourcegraph search and immediately at the finger tips of a new Sourcegraph user. Something smarter and more vigilant than we are, tuned to give us this type of result back.

I have considered a little how canons might be constructed, and structured, the benefits of different sizes of canons, etc. The interesting thing is that I believe this feature request is asking for one implementation of a more general kind of code search. If you conceive of canons as a sort of virtual super-repo compiled strategically behind the scenes by Sourcegraph for Sourcegraph to range over, you can begin to imagine compiling other canons for different, more specific aims. Ultimately, I wish I could come to Sourcegraph and surf the Sourcegraph canons, in addition to being able to interface in detail with this rich data as it is found "in the wild", which is what I think Sourcegraph is doing so well for me already.

#### Additional context

None

**Comment by attfarhan** [comment]
Hey @b-j-p, sorry for the very late reply here! Thanks for suggesting this feature and for the detailed writeup. We're thinking about how to improve the default search experience on Sourcegraph.com, so this is very useful.

A couple questions come to mind:
- Did you notice the "Popular npm packages" repogroup? This was an attempt to curate a group of JS repositories that are high quality, almost as you describe above. If you did notice and try it, what about that repogroup falls short for your purposes? If not, how could we make it more obvious for you? (if you have the chance to try it, I'd still love to hear your answer for how it may fall short) 
- Are you requesting the syntax for searching over curated canons/repogroups be slightly simpler (as in your `componentDidMount |* js` example)?
- Do you have any suggestions for curating these canons? We've found that it can be challenging to create repogroups that are relevant to everyone, even people within the same community. A difficulty we've seen in the past, is that when we provide a JS canon, a user could search for something 100% valid, but a bit obscure, and that may not show up in the canon. This makes the user think "well, Sourcegraph doesn't work at all" and is still a bad experience.

**Comment by b-j-p** [comment]
Hello @attfahran. Thanks for getting back to me about this. No apologies, please! I'm just glad to be able to help out.

Yes. To your last point: I admit that a canonical search feature would be difficult to get right and also that, as part of the default search experience, it would have to be gotten right. So there are some risks involved with it from a product perspective. I'll get to your other points too, but i want to go on the record as saying that I am very happy with sourcegraph, even if canonical search dies here. I opened the issue knowing it was an impractical, extracurricular kind of thing. No matter what, I'll plan on adding value to sourcegraph in the regular way, too, that is with a PR!

I would appreciate some advice from you about the best `good first issue` for me to work on. But that's a different conversation 😅.

**Comment by attfarhan** [comment]
Thanks for the follow-up @b-j-p! I think we're on the same page as to what the difficulties here are, and it's something that we'll continue to think about and see how we can get right. Glad to hear that you're happy with Sourcegraph.

As for good first issues, we have a label that you can look through and see what interests you:  https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22 All contributions are valued and appreciated! 😄

**Comment by b-j-p** [comment]
Now to your first point, @attfarhan, about `popular npm packages`. I updated the image included with my feature request 👆 to give more context about how it looks when sourcegraph makes this suggestion to the user. In short, yes, I tried it, and the user gets results back from a very basic js query, which is pretty great. I remember this list of results being an especially cool one and looking a little bit like the one I'd want from a sourcegraph canonical search feature. In particular, it was fun to see what some of the projects included in this repogroup are. 

However:
- When I queried `popular npm packages`, I remember being swamped by the richness of the results. Where I'd like to have gotten from querying your `js-canon` one result from each project represented in the canon containing a match, I got multiple matches accross an indefinitely large percentage of the projects in the repogroup. I was hoping to examine one species of little toad in the javascript ecosystem. I was querying a broad and eclectic repogroup for it. `componentDidMount` isn't the kind of function that is used just once in a repository. So I found it all over the place and got lost. That's not too suprising. The data that we are talking about (in the land of opensource code) is so rich that it is easy to get lost in it. "swamped" isn't quite the right word, either. It's more like a jungle out there! And I don't even know if there are toads in the jungle! Ach, I'm getting lost in my imagery. Forget about toads, what counts is that there are going to be some fundamental functions in the js ecosystem, and I was trying with sourcegraph to look into one of them.
- Related to the feeling of being bejungled by sourcegraph, my experience when querying this repogroup was, I remember, that I was too quickly separated from my search results. I was just being a little curious and suddenly I find myself deep inside one of the projects in `popular npm packages`, but which???, sniffing around, getting bitten by all kinds of cool looking misquitos. I would very much have prefered, in this case, to be able to do some more surfing around the results, in and between projects in `popular npm packages`. I wished for a cleaner and steadier surface provided me by a series of unique matches, one per project, which stay put when I click around in them. I never got the opportunity to ask and answer the questions: Which one of these popular npm packages employing this particular lifecycle method is my personal favorite? Which project has the nicest looking `componentDidMount` for purposes of my own projects?
- So I ended up doing the bare exact match search a number of times, and it seemed from the perspective of the user to be a matter of luck if sourcegraph made the `popular npm packages` suggestion. sourcegraph will not make this suggestion to me every time I make an overly basic, unfiltered query that smells like javascript. The suggestion will be somewhere in the suggested filters area, or not. But wouldn't it be cool (forgetting about the query syntax that I am suggesting for a second) if sourcegraph just detected an unfiltered, basic, javascript query in the main searchbox and piped it into the `js-canon`. That, in place of returning the "Whoops, the jungle is too jungle-y for this query" response? Actually, if you have a `js canon`, I think you have the ability to do that. Because in order to *represent* a bunch of awesome javascript projects in a canon, by which I mean a kind of virtual super-repo, I think you would need to have a grip on a good number of the basic building blocks in the js ecosystem. But I will go into this some more when I address your last point about curating canons.
- Indeed, however interesting and well curated it may be, a repogroup is not a canon. And no matter how well `popular npm packages` worked with just a quick click to get me some fascinating results back, I never was querying the type of thing I wished I could be querying.

**Comment by b-j-p** [comment]
About the syntax, @attfarhan , your second point. I don't feel strongly about my proposal at all. The concept should come from a product expert. As a matter of fact, I  wish canonical search were the default "fast path" for Sourcegraph code search -- exact match, unfiltered, no more specific default context specified. In which case, no new syntax is required. 

My suggestion ` [exact match pattern] |* js-canon` was added mainly to try to mark the fact that, there is a kind of break happening. In this search the user would not be querying a repo or a repogroup but some *third kind of thing*, that is admittedly not code as it appears in the wild.  

I want to call this kind of thing a canon, for two good reasons and one bad one: 
1. This "tertium quid" , whatever you want to call this type Sourcegraph queryable, is going to be the product of a process of canonical representation or "curation" which I will try to describe in my next comment (this is by far the hardest thing you asked of me  as I know neither Sourcegraph nor the mathematics of canonical representation 😅) 2. It would also serve Sourcegraph users as a source of code results that are representative or exemplary of a particular open source ecosystem  3. The bad reason is that for fun I wanted the query to look sort of like a canon firing a projectile.

Really ashamed to have to admit that...

**Comment by b-j-p** [comment]
Ok @attfarhan, just getting back from a vacation with the fam. My plan was to respond to your question about canon curation from the beach, but I never got around to taking out my laptop. I am  feeling more dull-witted than I was before I left, to say the least, so you will have to forgive the job I do on this. Hopefully, you come away with an understanding of the general direction I would go with curation/construction of canons.

**Comment by b-j-p** [comment]
**Richness**
Here is a sense of what I mean by "richness". This is kind of an important part of canonical representation of an ecosystem, if we can't do this I don't know if canonical search is possible.
So we have `seed` which is a repogroup, and with a repogroup comes a complete list of all symbols appearing in the repogroup. We iterate through the list of symbols in `seed` and for each symbol we query `seed` for that symbol. We next analyze  the results of that query in a basic way and record the results of the analysis. It's very basic stuff, we are looking for things like number and distribution of matches. We will identify in this way some basic or core symbols in the ecosystem and this does not have to be a complete list of the core building blocks it just has to be a decent collection -- `componentDidMount` would be among them, presumably, because when we query `seed-js` (the seed used for the canonical representation of the javascript ecosystem) we will get way too many matches, and we will remember that.

**Comment by b-j-p** [comment]
**THE OUTPUT**
Finally we arrive at the point in the curation process where we can construct a  `canon`! Or, because it is so novel for Sourcegraph to be not only ranging over naturally occurring projects,  but also generating highly artificial projects for itself to range over, I'm going to talk as if Sourcegraph is doing all of this, not "us".

- Here, Sourcegraph does a `mkdir canon`.
- Inside of `canon`, for each project in `seed`, Sourcegraph makes a `representation` folder.
- Sourcegraph scans the richness numbers it has generated for `seed` 👆.
- Sourcegraph extracts the _n_ richest files (a small fraction) that it needs from each project in `seed`.
- And for each of these files, Sourcegraph deposits a copy of the whole file into the correct project's `representation` folder inside of `canon`. 
- For each file we retain its jungle address, all its metadata from its place in the wild. Maybe we record this data in a sort of `canon-package` file that sits at the root level of `canon`. Or maybe we have a top level `canon-package` that deals with data about the projects, and in each `representation` folder,  a project level `project-package`, with data about the particular files we are using to represent the project. 

When we are ready, we expose `canon` to the user's query, not `seed`!! 
And `canon` is not a naturally occurring repo, nor is and it a repogroup. It's something else. It's a third kind of thing. It is another kind of search that we are enabling with it. If I can steal more time I would like to talk  about what is essentially different about this search experience.

But we are not ready with `canon` yet. At this point we need to: test `canon`, by querying it a bunch. So we have a terribly long list of exact match queries relevant to `canon` that we hit `canon` with. We know what we want to be able to respond to these queries with: in the ideal case it would be  one match in one file from each one of the `representation` folders in `canon`. But it will never be that good, and it doesn't have to be! Maybe we end up with 100 projects represented in `canon`. If we could return 10-15 results, each one from a different `representation` folder, hence a different project in the OSS jungle, a prime specimen from a dynamic open source project, I think we'd be happy. Results that you could click through -- >first, into the whole file, and then, if you are curious about this project --> into other matches from that `representation` folder if there were any, and ultimately into the jungle where the code lives, --> into the actual project being represented in `canon`.  Yeah I, for one, would be really happy with that.  Right now, suppose `canon` is not capable of responding to enough exact match queries in this satisfactory manner. Well, we just augment `seed` with more projects from `canon-candidates`. This is when we make `seed` really great. We increase the size of `canon` thereby, and we run the spec again, and repeat. We do this until `canon` gets over the bar that we set on the canonical search experience. Then `canon` is exposed to the Sourcegraph user's queries. 

The commitment to the user in a canonical search feature is not to the freshness of the results -- that they reflect the latest commits, and so on. We want exemplary results. Sourcegraph could construct `canon` at 2 am  PST each night. Do this, and overtime canonical search would get better because, for example, knowledge of what symbols belong in `core-js` improves. Knowledge of the relative weights of those symbols for purposes of canonical representation of the javascript ecosystem improves, etc.

**Comment by limitedmage** [comment]
Closing this issue as we now have Search Contexts, where you can create your on lists of repositories to search through and share with others. More info here: https://about.sourcegraph.com/blog/introducing-search-contexts/
