### ISSUE TITLE
dev/sg: 'sg ci' integration with annotations and artifacts

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#26072]
Annotations could be a useful way to surface high-signal output from CI jobs (https://github.com/sourcegraph/sourcegraph/issues/26071), and artifacts can contain useful log entries and reports - we should figure out the appropriate places for `sg ci` to surface this information

Part of https://github.com/sourcegraph/sourcegraph/issues/25768

**Comment by bobheadxi** [comment]
`sg ci` commands today: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/sg/sg_ci.go

**Comment by burmudar** [comment]
Hey @bobheadxi. What do envision the integration with `sg ci logs` should look like 🤔 ? At the moment I don't have a clear view how it should look.

**Comment by burmudar** [comment]
Closing this issue as I think the current integration with annotations is enough for this issue.
