### ISSUE TITLE
dev/sg: `sg ci status --commit`

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#26098]
For querying a specific commit, useful on main where the latest build is not necessarily the one you care about. Might need to do some handling between --branch and --commit - should the latter override the former?

**Comment by jhchabran** [comment]
> Might need to do some handling between --branch and --commit - should the latter override the former? 

If we were to, we'd need to return an error or a big warning if they are used in conjunction rather than simply overriding, that would be confusing otherwise I believe!

**Comment by jhchabran** [comment]
As we went for the alternative, I think we can close this.
