### ISSUE TITLE
Inaccessible references to sgdev.org in documentation

### ISSUE THREAD

**Issue by ianlopshire** [sourcegraph/sourcegraph#261]
There are many references to `sgdev.org` in the documentation contained in this repo that are not accessible to people outside of Sourcegraph. The [architecture.md](https://github.com/sourcegraph/sourcegraph/blob/master/docs/architecture.md) page is particularly bad.

I believe all of `sourcegraph.sgdev.org/github.com` links could be replaced with their `github.com` equivalents. I'd be happy to submit a PR if that is the case.

**Comment by attfarhan** [comment]
Hey @ianlopshire, thanks for filing this. You can replace `sourcegraph.sgdev.org` with `sourcegraph.com` in those links. A PR would be great!
