### ISSUE TITLE
resources-report: recreate Slack app integration, point to #dev-ops

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#26105]
https://sourcegraph.slack.com/archives/CJX299FGE/p1634029545376800

https://sourcegraph.slack.com/archives/C01CSS3TC75/p1634127357178900

https://handbook.sourcegraph.com/engineering/distribution/tools/resources_report

https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/cmd/resources-report/README.md#slack

It seems I'm locked out of the old Slack app and nobody else seems to be able to access it, so I think it needs to be recreated

**Comment by david-sandy** [comment]
We have a security issue that will need a fix.  For this resource:

```
resource "aws_iam_user_policy_attachment" "rr" {
  user       = aws_iam_user.rr.name
  policy_arn = "arn:aws:iam::aws:policy/ReadOnlyAccess"
}
```
We need to create a role/group and then attach the aws_iam_user to that role/group and then attach the policy to that role/group. Policies really shouldn't have users attached directly to them.

Please see: https://docs.bridgecrew.io/docs/iam_16-iam-policy-privileges-1 for more information.

**Comment by david-sandy** [comment]
When this is completed, can we ensure that the AWS instance used is properly encrypted and that the security team is notified?

Thank you!

**Comment by bobheadxi** [comment]
@david-sandy this doesn't run on an AWS instance - it runs in GitHub actions, and only requires the AWS IAM defined in https://github.com/sourcegraph/infrastructure/pull/2986

**Comment by david-sandy** [comment]
I am confused.  Why does this use AWS Terraform if it doesn't run in AWS?

**Comment by bobheadxi** [comment]
There has been no real demand for this, so am closing this for now
