### ISSUE TITLE
dev/ci: Grafana dashboard for pipeline and job metrics

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#26118]
Tracking issue for:

> Build an overview to report on metrics such as number of builds per day/week/month, ratio of successful to failed builds, build run time over day/week/month (maybe broken down by step or command, e.g. with tracing)

See #25768: https://docs.google.com/document/d/1fknr3NQGmwbKCfnF3Bcr-tYzV-TeuAGq-_Tm2-z_09M/edit#heading=h.4lpcsjmzh2db

**Comment by bobheadxi** [comment]
https://sourcegraph.grafana.net/d/iBBWbxFnk/ci?orgId=1 is a dashboard currently based on the logs entries exported by https://github.com/sourcegraph/sourcegraph/issues/25562

![image](https://user-images.githubusercontent.com/23356519/142258232-dc0fbdcb-7aab-49df-b7ae-6a72ccb2580e.png)

It's fairly rudimentary for now, and I'm not sure if we can generate all the metrics originally scoped out in this task purely from logs

**Comment by bobheadxi** [comment]
Idea to enable runtime metrics + success ratios: https://github.com/sourcegraph/sourcegraph/issues/27982

**Comment by bobheadxi** [comment]
Marking this as closed now that we have https://sourcegraph.grafana.net/d/iBBWbxFnk/ci?orgId=1

**Comment by Elyx0** [comment]
@bobheadxi How did you go around with it, trying to solve https://twitter.com/0xngmi/status/1525544425866289153 ?

**Comment by bobheadxi** [comment]
@Elyx0 we developed some tooling to ingest logs uploaded from CI in Loki:

- https://github.com/sourcegraph/sourcegraph/issues/27982
- https://sourcegraph.com/github.com/sourcegraph/sourcegraph@4233a1ca3fa8c9e718b75b3b9eae471a296c28b7/-/blob/enterprise/dev/ci/scripts/upload-build-logs.sh?L41:49
- https://sourcegraph.com/github.com/sourcegraph/sourcegraph@4233a1ca3fa8c9e718b75b3b9eae471a296c28b7/-/blob/dev/sg/sg_ci.go?L451-517

Then, we wrote some dashboards based on queries over the logs, for example:

- Failed builds

```logql
count by (build, name) (count_over_time({app="buildkite",branch="main",state="failed"}[5m]))
```

- Failed steps over 3h

```logql
count by (name) (count_over_time({app="buildkite",state="failed",branch="main"}[3h]))
```

- Failed steps over 1d

```logql
count(
topk(1, count_over_time({app="buildkite",state="failed",branch="main"}[1d])) by (build)
)
```

- Most frequently failed steps over 7d

```logql
count by (name) (count_over_time({app="buildkite",branch="main",state="failed"}[7d]))
```

We also mention this briefly in our newsletter: https://handbook.sourcegraph.com/departments/product-engineering/engineering/enablement/dev-experience/newsletter/#nov-23-2021

What it looks like today:

<img width="1671" alt="image" src="https://user-images.githubusercontent.com/23356519/169669957-8466b0b1-848e-430d-84f9-3dd0f3faf9eb.png">

<img width="1667" alt="image" src="https://user-images.githubusercontent.com/23356519/169669961-0931b59e-e924-4756-b91b-6a2d30703239.png">
