### ISSUE TITLE
When system theme isn’t supported we should default to light theme instead of showing an error

### ISSUE THREAD

**Issue by francisschmaltz** [sourcegraph/sourcegraph#2613]
When the system theme isn’t an option we should default to light theme and then only show the error if the user tries to manually select it. It shouldn’t be possible to select it on browsers that don’t support this feature. 

![img_0108](https://user-images.githubusercontent.com/11583013/53902761-c7e9be00-3ff6-11e9-9497-446921f9b8e4.jpeg)

**Comment by felixfbecker** [comment]
Please see #2490. Closing for now.
