### ISSUE TITLE
sg: fails with unclear errors when running sg on old (unsupported) go versions

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#26155]
Context: https://sourcegraph-community.slack.com/archives/C02BG0M0ZJ7/p1634296034018800 

The person is running an old go version, 1.10, and was facing odd errors related to Go modules when trying to compile the code. 

Should we check the Go version in sg doctor or before running commands?

**Comment by bobheadxi** [comment]
This will be closed by https://github.com/sourcegraph/sourcegraph/pull/37628 which now pulls the desired go version from `.tool-versions`
