### ISSUE TITLE
Validate base manifests for all supported Kubernetes versions

### ISSUE THREAD

**Issue by caugustus-sourcegraph** [sourcegraph/sourcegraph#26162]
CI should run validation tests for all supported Kubernetes versions against the base manifests provided in https://github.com/sourcegraph/deploy-sourcegraph. Currently they are only validated using a dry-run or apply's against live clusters.

**Comment by virginiaulrich** [comment]
Closing for now and will revisit as part of a larger conversation for CI testing for Helm
