### ISSUE TITLE
Diff result not syntax highlighted

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#2617]
I suspect it is related to the diff being markdown.

https://sourcegraph.sgdev.org/search?q=r:sourcegraph/+type:diff+author:nick+count:1000+after:%224+months+ago%22#5

![image](https://user-images.githubusercontent.com/754768/53915142-3a1ccb80-4014-11e9-985e-a4380009661b.png)

**Comment by attfarhan** [comment]
Dupe of https://github.com/sourcegraph/sourcegraph/issues/2615
