### ISSUE TITLE
ci: document run types directly rather than sending people toward the sources

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#26179]
https://docs.sourcegraph.com/dev/background-information/continuous_integration#run-types points to the source code, which is acceptable but with some friction. 

I believe we should have a proper list of those with explanations, as that's easily addressed and it's our responsibility to keep the doc up to date.

**Comment by bobheadxi** [comment]
It could be cool if these docs could be generated directly from the source somehow 😁

**Comment by bobheadxi** [comment]
superseded by https://github.com/sourcegraph/sourcegraph/issues/30203 , I forgot about this issue!
