### ISSUE TITLE
Make unified hover popup UI for all code hosts in browser extension & native integrations

### ISSUE THREAD

**Issue by erzhtor** [sourcegraph/sourcegraph#26191]
[Figma Designs](https://www.figma.com/file/VMkv14J80ibVCVzFUczKDe/23738-Add-branding-to-extension-popovers?node-id=275%3A1628).  Related to https://github.com/sourcegraph/sourcegraph/issues/23738

**Comment by muratsu** [comment]
Closing as per items discussed above
