### ISSUE TITLE
Diff search doesn't show full diffs

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#2620]
I want to use diff search, but I have found that I can't rely on its result in the way that I want.

**Expected**

I want to perform a search and then see every single line in all matching diffs.

**Actual**

For some results, it only shows a small portion of the whole diff.

For example:
https://sourcegraph.sgdev.org/search?q=r:sourcegraph/+type:diff+author:vanesa+count:1000+after:%224+months+ago%22#16

(scroll down or find-in-page until you see this result)
![image](https://user-images.githubusercontent.com/754768/53916535-38a0d280-4017-11e9-8b83-b62de8a2ea22.png)

Doesn't show the full diff:
https://sourcegraph.sgdev.org/github.com/sourcegraph/sourcegraph/-/commit/23a5556c7e25aaab1f1529cee4efb90fe6fe3a30

And worse, it is impossible for me as a user to know a priori if there are more results to see by clicking through to the diff.

**Proposals**

These options are not mutually exclusive:
- Increase the default display limit beyond what it is today (easy).
- Add an indication to the result if the full diff is not included (click through required to view full diff)
- Only display part of the diff by default but allow it to be expanded to the full diff inline

**Comment by attfarhan** [comment]
Can you attach the query that you ran?

**Comment by nicksnyder** [comment]
I updated the original description with the link to the search.
