### ISSUE TITLE
Compute prototype: general-purpose search result processing

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#26210]
Timeline:

In the current 11/22/21 sprint I will:

- Demo capabilities with a front facing client to the search team.

- Work with team to characterize and demo this tooling broadly and discuss next steps for prioritizing/growth

- Continue attempt to incorporate LSIF

- Add incremental improvements to client (hyperlinks, maybe callgraphs)

- Set up and document the client side work for other engineers to play with. Also make time for giving walkthroughs.

In the prior 11/9/21 2-week sprint I added:

- [x] Metadata substitution integration (allow substituting values of repositories,commits,filepaths,author in outputs)

- [x] structural search output support

- [x] frontend client to prototype capabilities. I have in mind a solution that graphs all kinds of cool and customizable properties/insights on code.

- [x] streaming computing results (only available in a branch right now, because we are rearchitecting our streaming API endpoints for CORS). We want to stream results (a) because operations are cheap and (b) time-to-first-result is attractive. We want to keep a GQL endpoint for Code Insight's purposes, but perhaps over the long term the streaming endpoint can become the mainstay API.

- [ ] LSIF query integration (query/case out on LSIF values based on matched ranges)--only partial, didn't get to this.

In the prior, and first 2-weeks print, I implemented in-place replacement and outputting captured values (basically output template/printer) for search results on files. The initial implementation supports in-place regex and structural search replace, and regex outputs for captured values (no structural search support yet)

**Comment by rvantonder** [comment]
FYI lots of PRs to  this sprint towards prototype functionality in backend work. I can update the description for work for the next two weeks.

https://github.com/sourcegraph/sourcegraph/pull/26827
https://github.com/sourcegraph/sourcegraph/pull/26813
https://github.com/sourcegraph/sourcegraph/pull/26766
https://github.com/sourcegraph/sourcegraph/pull/26754
https://github.com/sourcegraph/sourcegraph/pull/26698
https://github.com/sourcegraph/sourcegraph/pull/26697
https://github.com/sourcegraph/sourcegraph/pull/26695
https://github.com/sourcegraph/sourcegraph/pull/26694
https://github.com/sourcegraph/sourcegraph/pull/26693
https://github.com/sourcegraph/sourcegraph/pull/26692
https://github.com/sourcegraph/sourcegraph/pull/26624
https://github.com/sourcegraph/sourcegraph/pull/26553
https://github.com/sourcegraph/sourcegraph/pull/26552
https://github.com/sourcegraph/sourcegraph/pull/26551
https://github.com/sourcegraph/sourcegraph/pull/26550
https://github.com/sourcegraph/sourcegraph/pull/26549
https://github.com/sourcegraph/sourcegraph/pull/26548
https://github.com/sourcegraph/sourcegraph/pull/26547
https://github.com/sourcegraph/sourcegraph/pull/26546
https://github.com/sourcegraph/sourcegraph/pull/26545
https://github.com/sourcegraph/sourcegraph/pull/26544
https://github.com/sourcegraph/sourcegraph/pull/26543
https://github.com/sourcegraph/sourcegraph/pull/26542
https://github.com/sourcegraph/sourcegraph/pull/26538
https://github.com/sourcegraph/sourcegraph/pull/26528
https://github.com/sourcegraph/sourcegraph/pull/26527
https://github.com/sourcegraph/sourcegraph/pull/26523
https://github.com/sourcegraph/sourcegraph/pull/26479
https://github.com/sourcegraph/sourcegraph/pull/26478
https://github.com/sourcegraph/sourcegraph/pull/26474
https://github.com/sourcegraph/sourcegraph/pull/26467
https://github.com/sourcegraph/sourcegraph/pull/26404
https://github.com/sourcegraph/sourcegraph/pull/26341
https://github.com/sourcegraph/sourcegraph/pull/26323

**Comment by lguychard** [comment]
@rvantonder could you add a short description to this issue to represent the intent of this work? Thanks!

**Comment by rvantonder** [comment]
updated

**Comment by nicksnyder** [comment]
(Stumbled across this from the product/eng tracker) Is there a more descriptive title we could have for this issue? What is the problem we are solving here?

**Comment by rvantonder** [comment]
@nicksnyder I've updated the title to something more descriptive. Details to follow, it's too early to elaborate without a prototype. @lguychard @benvenker if the maturity of this work doesn't fit in the current tracker then I suggest we move or remove it until we have more to say. I think it does fit, but I still need/want room to work on things, it's only been about 4 weeks where I've spent maybe 30% of my time on this, so I don't know how we can communicate that more effectively.

**Comment by jyavorska** [comment]
@benvenker can you please add a (conservative) estimate for when this will be delivered? Doesn't need to be exact, and it can change, but it's for the roadmap view at https://github.com/orgs/sourcegraph/projects/214/views/11.

**Comment by rvantonder** [comment]
Updated description.

**Comment by benvenker** [comment]
@jyavorska updated the the date in the dashbaord

**Comment by rvantonder** [comment]
Closing this, I think the prototyped served its purpose and we don't need immediate follow up work for it. We can create a new issue if we want to track work to get this onto a Demo instance.
