### ISSUE TITLE
Support Phabricator as a repository source

### ISSUE THREAD

**Issue by KattMingMing** [sourcegraph/sourcegraph#2623]
**Expected behavior**
Phabricator external service should successfully fetch Phabricator hosted repositories and mirrored repositories

**Current behavior**
Phabricator repositories are not fetched. Only mirrored repositories are supported.

Right now, it's not possible to clone repositories hosted by Phabricator (diffusion) with the **Phabricator** external service.

The Phabricator external service seems to only support cloning repositories that are mirrored to Phabricator such as from Gitolite, AWS Code Commit, GitHub, etc. It does not work when cloning directly from Phabricator URLs.

NOTE: It is possible to clone Phabricator repositories via SSH or HTTP(s) by using **Other** as the external service type. This would look like:

```
{
  "url": "https://secure.phabricator.com",
  "repos": [
    "https://secure.phabricator.com/diffusion/ARC/arcanist.git"
  ]
}
```
(The example above also works when using `SSH`, username + password, or tokens)

**Comment by keegancsmith** [comment]
I don't think we ever supported this. Does our documentation / feature list mislead in this regard? How important is supporting this. We have been focused on foundational work in our repo management so I can't imagine having bandwidth for this in the next milestone. But it may be a possibility if motivated properly.

**Comment by KattMingMing** [comment]
We support it in some capacity since it's possible to add them manually by using the "other" external service (since they are Git repositories).

I'll review the documentation, but there's no explicit mention that this would not work.

https://docs.sourcegraph.com/admin/external_service/phabricator#repository-linking-and-syncing

Possibly need to update documentation to start with:
> **Only** if you mirror your source repositories on Phabricator,

**Comment by tsenart** [comment]
Related to #3490

**Comment by keegancsmith** [comment]
@christinaforney do any customers want this? If so, should we add to the roadmap? If not, can we close?

**Comment by tsenart** [comment]
Closing until there's new demand for this.
