### ISSUE TITLE
make search suggestions more precise

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#26239]
- The [new additions](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/shared/src/search/query/providers.ts?L43-70&subtree=true) only pull out `file` and `repo`, but we can easily support other filters that make sense (like `lang`) which filters down to files. Currently, `lang` is ignored, so when I type `lang:go parse`, I still get typescript suggestions for a function `parse`

<img width="1345" alt="Screen Shot 2021-10-18 at 2 31 11 PM" src="https://user-images.githubusercontent.com/888624/137810284-ee3eb0a9-4b65-4bca-91f5-1d26ebe30681.png">

I suggest we go over the filters comprehensively and support all the ones that make sense (otherwise we might run into more of the above kinds of issues). if we run into filters that pose issues for some reason, it's better to show no suggestions than entirely irrelevant ones (IMO).

- As seen in screenshot above, there are a lot of hits for `parse`. Turns out they are all different, but it's difficult to see because the path gets cut off. Can we investigate appending the file path of matches to that dropdown directly (and right align it, so that the last part of the path always shows, in case it's too long?)

**Comment by benvenker** [comment]
Sorry, lost track of this. @rvantonder do you feel that #26256 covers the engineering portion of your concern?

**Comment by benvenker** [comment]
@novoselrok blast from the past: did you merged PR address this to our satisfaction, at least for now?

**Comment by novoselrok** [comment]
Yep, I think it did.

**Comment by camdencheek** [comment]
Closing since suggestions have changed dramatically since this was opened.
