### ISSUE TITLE
ci: add pull-through caches for dependencies to mitigate transient errors 

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#26257]
Context: https://sourcegraph.slack.com/archives/C07KZF47K/p1634591872474600

A common source of CI flakes are failed downloads of mandatory dependencies, which have various causes: transient network errors, rate-limiting from Github, etc ... Those can be addressed individually, but on the long run, a more general solution would definitely be best. 

Possible solutions: 
- introduce HTTP caching through a proxy, to avoid cluttering the build scripts with caching logic
- cache various build artefacts (node modules, binaries, etc..)
- .. 

⚠️  There are many ways we can address this, let's make sure the problem is properly scoped before looking for a solution.

**Comment by bobheadxi** [comment]
Do we have statistics indicating this is a frequent issue? Anecdotally I have not seen one of these in a while

**Comment by jhchabran** [comment]
No, we don't and it's hard to diagnose, because the errors depend on what resources we're fetching is failing. The caching mechanism addresses this issue directly. 

@bobheadxi I'm inclined to close this in favour of a ticket listing what remains to be cached once we move onto the stateless agents.

**Comment by jhchabran** [comment]
closing, now irrelevant
