### ISSUE TITLE
Sentry extension

### ISSUE THREAD

**Issue by vanesa** [sourcegraph/sourcegraph#2628]
Sentry helps devs track, organize and break down errors more efficiently, facilitating their debug process. We want to make it more convenient for developers to access Sentry's error tracking tools directly from the code that is doing the error handling, code such as `throw new Error(QUERY)`, `console.log(QUERY)`, `console.error(QUERY)` etc.. 

In the first version, the Sentry extension will render a `View logs in Sentry` link on each line it detects such error handling code, leading the devs directly to the corresponding Sentry issues stream page.

**WIP**: https://github.com/sourcegraph/sourcegraph-sentry

#### PLAN

- [x] Build extension skeleton
- [x] Develop the regex to detect error handling code. For the first version it should detect: 
	- [x] `throw new Error(QUERY)`
	- [x] `console.log(QUERY)`
	- [x] `console.error(QUERY)`
	- [x] `console.warn(QUERY)`
	- [x] `console.info(QUERY)`
	- [x] `console.debug(QUERY)`
	- [x] `log.Printf(QUERY)`
	- [x] `log.Print(QUERY)`
	- [x] `log.Println(QUERY)`
	- [x] It detects any error handling code specified in the Sentry extension settings
- [x] Create a test plan
- [x] Render a link next to lines that contain error handling code
- [x] Match document repo with Sentry organization
- [x] Check if document format matches the Sentry extension configuration for file matching
- [x] Match the document with the corresponding Sentry project that's receiving the logs
- [x] Generate the correct link to the issues stream page with the org and project information

#### EXAMPLE USE CASE FOR V0

Error handling code like [this one](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/browser/src/libs/github/file_info.ts#L29):

```
throw new Error('cannot determine delta info')
```

should generate a link that leads to the Sentry issues stream page:
```
https://sentry.io/organizations/[organization-name]/issues/?project=[project-name]&query=is%3Aunresolved+cannot+determine+delta+info&statsPeriod=14d
```
![image](https://user-images.githubusercontent.com/9110008/54014672-d7b4fe00-41c0-11e9-9b92-66d851401fa0.png)

**Comment by felixfbecker** [comment]
I don't think `console.log()` is tracked by Sentry (probably `info()` and `Println()` too)

**Comment by nicksnyder** [comment]
Is this issue ready to close? I don't see any more checkboxes. I know there is more work to be done with the sentry extension but I assume that that work is captured in https://github.com/sourcegraph/sourcegraph/issues/3177

**Comment by vanesa** [comment]
Yes all these issues have been closed.
