### ISSUE TITLE
Define what's officially supported

### ISSUE THREAD

**Issue by dan-mckean** [sourcegraph/sourcegraph#26299]
In order to work well with CE and set expectations for what works, we want to make sure the "[Deployment best practices](https://docs.sourcegraph.com/admin/deployment_best_practices)" guide is up to date and fully reflect what we do and don't recommend. 

This will change when we iterate on the options we support for deployment. But getting it up to date for now will help us in the short term.

**Comment by kevinwojo** [comment]
A couple of notes after working with some recent deployment stuff:

 * Docker Compose version
 * Docker version
 * Installation methods

**Comment by virginiaulrich** [comment]
Delivery me is going to ask support me to follow through on this and collab with Delivery team as needed; first steps are a leadership level conversation about company customer-first philosophy and whether clear boundaries for support are truly in conflict with that
