### ISSUE TITLE
ci: annotate pipeline generation failures

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#26304]
<img width="917" alt="CleanShot 2021-10-19 at 18 18 34@2x" src="https://user-images.githubusercontent.com/10151/137951435-104d4931-e688-4ded-b2e9-de60b3f00e1a.png">

The red text saying that the pipeline is empty distracts from the real problem.

**Comment by jhchabran** [comment]
@burmudar where do we stand on this? We have added a bunch of annotation already. Should we consider this done? How do you consider it through the bet standpoint?

**Comment by burmudar** [comment]
Once https://github.com/sourcegraph/sourcegraph/pull/39289/files is merged this can be closed. There isn't much actions a person not familiar with the pipeline can do and with sentry we get notified, and we can actually engage and take action with this :)
