### ISSUE TITLE
insights: add code insights to the architecture diagram

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#26317]
Add code insights to the diagram on [this page](https://docs.sourcegraph.com/dev/background-information/architecture#diagram)

**Comment by felixfbecker** [comment]
@coury-clark @CristinaBirkel am I assuming correctly this is a quick task (size 1)?

**Comment by coury-clark** [comment]
@felixfbecker yes, see https://github.com/sourcegraph/sourcegraph/pull/29893
