### ISSUE TITLE
Add metric to track the display of the install browser extension popover

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#26319]
The browser extension promotes users returning to the product frequently, [thus it improves retention](https://analytics.amplitude.com/sourcegraph/chart/d9iuw6g). As retention is a primary goal, we should attempt to increase the number of users who install the extension. 

The first step in this goal is to fully understand the metrics behind the feature, including its [acquisition funnel](https://analytics.amplitude.com/sourcegraph/chart/k9xzbih):

- [ ] Add metric to track the display of the "Install browser extension popover"

**Comment by muratsu** [comment]
We currently log platform but not the browser extension version. We should log the browser extension version.

**Comment by rrhyne** [comment]
This issue formerly contained the following issue as well: https://github.com/sourcegraph/sourcegraph/issues/27082. I've split them because they can be separate efforts.

**Comment by muratsu** [comment]
https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/repo/actions/InstallBrowserExtensionPopover.tsx?L27
