### ISSUE TITLE
Why does the GraphQL console give different (no) results?

### ISSUE THREAD

**Issue by hho** [sourcegraph/sourcegraph#2632]
#### Question description

I entered a query (like `repo:^ourgitlab/somenamespace count:100`) in the search field and got the expected list of repos in that namespace.

However, when I copy **_the exact same GraphQL query and variables_** from the request payload (via Chrome Devtools) and insert them into the API console, I get no results:

```
{
  "data": {
    "search": {
      "results": {
        "__typename": "SearchResults",
        "limitHit": false,
        "resultCount": 0,
        "approximateResultCount": "0",
        "missing": [],
        "cloning": [],
        "timedout": [],
        "indexUnavailable": false,
        "dynamicFilters": [],
        "results": [],
        "alert": {
          "title": "No repositories satisfied your repo: filter",
          "description": "Change your repo: filter to see results",
          "proposedQueries": [
            {
              "description": "remove repo: filter",
              "query": "count:100"
            }
          ]
        },
        "elapsedMilliseconds": 158
      }
    }
  }
}
```

Why the difference? What do I need to change?

#### Additional context

Sourcegraph 3.1, locally installed via Docker

**Comment by attfarhan** [comment]
Hey @hho, sorry for the very late reply here! I'd love to help, but I can't reproduce this myself. 

It's been a while so this is a long-shot, but if you still remember the variables and query you used and you could share it here (with private repo names redacted) , it'd be super helpful to help debug. 

Thanks and apologies again for the late reply.

**Comment by hho** [comment]
Sorry, but I have since upgraded to Sourcegraph 3.2 and reconfigured the `repositoryPathPattern` of the configured provider.

And now I can't reproduce it anymore, either. :man_shrugging:
