### ISSUE TITLE
Collecting feedback on our qa/e2e tests 

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#26368]
This is a tracking issue for our effort with @valerybugakov to refresh our view on the QA/E2E test suites. We want to gather feedback on how each product team estimates the relevancy of each of those tests within their product domain.

> Why focus on that particular question and not open up an RFC about dropping those tests? 

Asking if we should remove the e2e/QA tests often leads to emotional answers as it evocates losing confidence when shipping to production. By focusing on the relevancy of each test performed by these test suites in the context of each specific domain, we can make the question fact-based instead.

Actions (google form maybe?) 
- List all individual tests performed by those test suites 
- Ask each product team, in the context of their domain, 
  - How does this test helps you to be confident that what you're shipping is working as intended? 
  - Are you getting coverage of that feature/sub-feature with other tests? 
  - When was the last time that adding a test in those test suites was considered? 
  - When was the last time you caught an error in those test suites that did not surface in any other test suite?
  - Would it be okay to remove this? If not why? 
- If we see tests that are about a single domain/team, extract those in a different file named after that domain. 
- Drop anything that is not deemed confidence building by anyone.

cc @pdubroy

**Comment by jhchabran** [comment]
@valerybugakov and @taylorsperry I have built this spreadsheet that we can use to collect feedback on the relevancy of those tests: https://docs.google.com/spreadsheets/d/1QjQJ9eysVhDzfXlmomS93ow91D9NR_Jskz7HKMKoKg8/edit?usp=sharing

Thoughts?

**Comment by jhchabran** [comment]
See Discussion here https://github.com/sourcegraph/sourcegraph/discussions/26983

**Comment by valerybugakov** [comment]
Joined the discussion mentioned above ^
