### ISSUE TITLE
insights: insight view GraphQL should provide sharing information

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#26384]
Insights can be added to dashboards via reference or copy. An insight can be called a reference if its total reference count is > 1. The GraphQL response view should return some basic information such that the UI can determine if the insight is referenced elsewhere or not.

Long term we would like to display the actual dashboards or locations that the view is visible, but this comes with user access problems that we are going to defer until a later time.

**Comment by CristinaBirkel** [comment]
This was covered by https://github.com/sourcegraph/sourcegraph/issues/30031
