### ISSUE TITLE
Activation flow issues for existing users

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#2638]
- [ ] For users who have already completed the actions before upgrading to a version that has the activation flow, don't show confetti the next time they visit
- [ ] Progress does not advance until a full page reload (e.g. after adding an external service)
- [ ] The "Setup" button and the circle icon appear slightly misaligned with each other
- [ ] The "Setup" button and icon disappear after clicking "Find references". It should stay around and show fully completed until the next page reload.

**Comment by chrismwendt** [comment]
A few more problems I noticed:

- Progress does not advance until a full page reload (e.g. after adding an external service)
- The "Setup" button and the circle icon appear slightly misaligned with each other:

![image](https://user-images.githubusercontent.com/1387653/54152607-d838d900-43fa-11e9-95c0-1b063d218a0a.png)

- The confetti that appeared after clicking "Find references" was quite distracting. I was expecting a more subtle change (e.g. the "Setup" button turns green)
- The "Setup" button and icon disappear after clicking "Find references". I was expecting that I would explicitly dismiss the progress indicator.

**Comment by sqs** [comment]
@beyang I added a checklist of the issues and solutions that we should fix for 3.2

For this one:

>  For users who have already completed the actions before upgrading to a version that has the activation flow, don't show confetti the next time they visit

Is it possible for us to know this? Or is the necessary tracking not even in until 3.2? Err on the side of not showing unexpected confetti if needed, so perhaps assume all current steps are completed for all users that existed as of pre-3.2 (instead of assuming they have NOT completed any).

**Comment by beyang** [comment]
>  Progress does not advance until a full page reload (e.g. after adding an external service)

This is a nice-to-have/wont-fix. We said this was acceptable for the non-find-references/search actions for now. I will best-effort fix.
