### ISSUE TITLE
Recommended Sourcegraph Extensions

### ISSUE THREAD

**Issue by muratsu** [sourcegraph/sourcegraph#26407]
The idea originated on [bext brain storming session](https://miro.com/app/board/o9J_lqCV2Uo=/).

We want to show users recommended extensions to increase usage & add more value.

Similar to VS Code recommendations:
![image](https://user-images.githubusercontent.com/1308560/138219738-fb7bca66-d5f7-4856-85f9-501d61838762.png)

**Comment by ryankscott** [comment]
@muratsu sounds like we should close this ticket?

**Comment by ryankscott** [comment]
Closing this. @muratsu  re-open if you see fit.
