### ISSUE TITLE
Deprecate the existing VS Code extension

### ISSUE THREAD

**Issue by tjkandala** [sourcegraph/sourcegraph#26439]
Once we release the new VS Code extension, we should deprecate the [existing VS Code extension](https://github.com/sourcegraph/sourcegraph-vscode).

**Comment by jjinnii** [comment]
[Thread](https://sourcegraph.slack.com/archives/C02E3HHDZ98/p1645090342453759) for context. 

Decision: deprecate old repo for vs code extension. User feedback will be directed to the discussion section in our monorepo discussions and other channels. (social media, issues, projectboard)
