### ISSUE TITLE
References in docstrings incorrect

### ISSUE THREAD

**Issue by adnanhemani** [sourcegraph/sourcegraph#2651]
- **Sourcegraph version:** "Sourcegraph.com"
- **Platform information:** MacOS 10.14.3, Chrome v72.0.3626.121

#### Steps to reproduce:
Results shown in pictures attached
1. Go to https://sourcegraph.com/github.com/data-8/datascience@4cee38266903ca169cea4a53b8cc39502d85c464/-/blob/datascience/tables.py#L1130 and hover over "``bins``". Notice that it automatically pops up the docstring for this function that the argument is part of (pivot_bins)
<img width="755" alt="screen shot 2019-03-08 at 4 24 02 am" src="https://user-images.githubusercontent.com/10746770/54029174-604d8300-415c-11e9-8787-efaafe984232.png">
2. Click "Find references" on the hover pop up and scroll down and click on the reference to "bins" on line 2389.
3. Hover over the "bins" arg in the doctring (note that this is a different function now: hist).
4. Note that the information that pops up on hover is referencing the first function that we hovered over the docstring for.
<img width="1181" alt="screen shot 2019-03-08 at 4 34 47 am" src="https://user-images.githubusercontent.com/10746770/54029166-5af03880-415c-11e9-8732-1185d232c7aa.png">

#### Expected behavior:
I'm not completely sure what is the intended behavior for this feature when hovering over docstrings, to be honest. I could understand if the hover popup only displays information if there's another function, module, etc. that's in the docstring, but a regular argument from a function I'm not so sure is necessary. Or at the very least, if displaying the function's docstring is still a good idea in this situation, make sure the right functions' information is being shown.

#### Actual behavior:
I'm guessing that it's referring to the first instance of the argument that it's seeing in a function signature and returning that function's docstring.

**Comment by chrismwendt** [comment]
Thanks for the feedback, @adnanhemani. Because this is so confusing, I'm tweaking the logic to be a bit stricter on what is considered a definition. PR incoming.
