### ISSUE TITLE
Revisit fallback URL logic/decision

### ISSUE THREAD

**Issue by erzhtor** [sourcegraph/sourcegraph#26515]
### Context
After fallback URL changes:

- Released PRs
  - https://github.com/sourcegraph/sourcegraph/pull/25185
  - https://github.com/sourcegraph/sourcegraph/pull/26007
- Not released PRs
  - https://github.com/sourcegraph/sourcegraph/pull/26163
  - https://github.com/sourcegraph/sourcegraph/pull/26258
  - https://github.com/sourcegraph/sourcegraph/pull/26352
  - https://github.com/sourcegraph/sourcegraph/pull/26489
  
We have a bug that browser extension accidentally uses cloud URL for private repos, breaking code-intel for private repos. We were planning to address this issue, but this brought up a discussion that some enterprise users on self-hosted instances might not want automatic fallback to the cloud at all.

### Next steps
- [x] Revert merged changes to main to unblock the main branch from future releases. Close not merged PRs. https://github.com/sourcegraph/sourcegraph/pull/26516
- [x] Lessons learned
  - Why did it happen?
  - What are the consequences?
  - How to prevent it in the future? Lessons
- [ ] Revisit decision on the fallback URL logic & design

**Comment by erzhtor** [comment]
Review/discussion docs https://docs.google.com/document/u/4/d/1NAa4xYcVRNnRxV9-TDLKSrlgLgq_YF_10KkBwoWYSkQ/edit#

**Comment by erzhtor** [comment]
Also, this old issue might be also related I think https://github.com/sourcegraph/sourcegraph/issues/5484

**Comment by jjinnii** [comment]
Closing issue as we have landed on a decision to implement dropdown solution through [RFC 524: Evaluating the decision to implement fallback logic](https://docs.google.com/document/d/1EXzvhZNBDsqU8s2IauYe6oyDo7qeTdg55dnDA8A2KuQ/edit#)
