### ISSUE TITLE
Elixir syntax highlighting broken

### ISSUE THREAD

**Issue by gerbal** [sourcegraph/sourcegraph#2653]
Navigate to any Elixir file, for instance: 

https://sourcegraph.com/github.com/elixir-lang/elixir/-/blob/lib/elixir/lib/gen_server.ex

Note the absence of syntax highlighting. I'm pretty sure syntax highlighting used to work for Elixir. Syntax highlighting still works in tooltips though. 

![screenshot_2019-03-08 sourcegraph](https://user-images.githubusercontent.com/5278092/54045369-6fa1f000-419f-11e9-8517-97744051b784.png)

**Comment by gerbal** [comment]
What's the status of this issue?

**Comment by gerbal** [comment]
@slimsag is there any plan to fix elixir syntax highlighting?

**Comment by rvantonder** [comment]
Aaand done: https://sourcegraph.com/github.com/elixir-lang/elixir/-/blob/lib/elixir/lib/gen_server.ex

#19282
