### ISSUE TITLE
sg: add a command to reset secrets for a given key

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#26555]
As we are adding commands, it can happen that a secret was assigned when less scope than needed to perform the new commands. Presently there is no way to get rid of those. 

Similarly, if a token were to be expired, there is no path to destroy those without manually editing the underlying file used for storage. 

➡️ Create a way to reset secrets for a given key without having to toy with the secrets file itself.

**Comment by chtnnh** [comment]
@ltagliaferri can we check now?

**Comment by chtnnh** [comment]
@valerybugakov could you please add the `hacktoberfest-accepted` label? Thanks :D

**Comment by ltagliaferri** [comment]
Looks like we are all set with the #hacktoberfest-accepted label, thanks team!
