### ISSUE TITLE
Enable source maps for client-side errors reported by Sentry

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#26578]
## Problem statement

For [some](https://sentry.io/organizations/sourcegraph/issues/?project=1391511&query=is%3Aunresolved&sort=freq&statsPeriod=14d) client-side errors, the source map is not available, making it challenging to identify the root cause of the issue.

## Success criteria

Every client-side error reported by Sentry has a source map available.
See more information on how to configure source maps for Sentry [here](https://docs.sentry.io/platforms/javascript/sourcemaps/#source-map-integration-setup).

**Comment by sourcegraph-bot-2** [comment]
Heads up @taylorsperry @jasongornall - the "team/frontend-platform" label was applied to this issue.
