### ISSUE TITLE
Improve backend Sentry configuration

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#26577]
Update [the Sentry package](https://github.com/sourcegraph/sourcegraph/blob/main/internal/sentry/sentry.go) used to report backend issues:
- [ ] Ensure that [the third-party Sentry package](https://github.com/getsentry/sentry-go/) is up to date.
- [ ] Investigate if it's possible [to improve stack traces](https://docs.sentry.io/platforms/go/troubleshooting/) for errors reported by Sentry.

**Comment by taylorsperry** [comment]
@valerybugakov is this still within the scope of work?
