### ISSUE TITLE
Investigate how to infer what backend service failed in Sentry errors

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#26584]
We can probably use different projects or at least labels depending on the app that failed to minimize the need to triage at the top level.

Based on [the RFC 501: Runtime error monitoring](https://docs.google.com/document/d/1d18e_YFJsw5cgDId8Iz1MT8A_GsHZTOGHMuem1JMzuM/edit?usp=sharing).

**Comment by taylorsperry** [comment]
@valerybugakov is this still within the scope of work?
