### ISSUE TITLE
Search UI: very deeply nested DOM

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#2661]
- Visit https://sourcegraph.com/github.com/linkedin/LayoutKit@c77e9bc8f31742adf56b05cda34cb91489b41181/-/blob/LayoutKit.playground/Pages/Inset.xcplaygroundpage/Contents.swift#L27:7&tab=def
- Scroll down in the references
- Scroll back up
- Inspect this element:

![image](https://user-images.githubusercontent.com/1387653/54066887-ea452c80-41ec-11e9-82c8-07c841f63c09.png)

- Notice the DOM for this highlight is very deep, I would expect it to only be 1 level deep

@attfarhan to triage in case this is related to recent search UI changes

**Comment by chrismwendt** [comment]
Hmm, I can't even repro this myself anymore. I'll reopen if I see this again.

**Comment by chrismwendt** [comment]
I can repro by **scrolling down and back up**.

I suspect that the matches are getting re-highlighted over and over when scrolling.

**Comment by chrismwendt** [comment]
I can't seem repro anymore.

**Comment by chrismwendt** [comment]
I'm able to repro at https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+import+as+lang:typescript+count:1000

![2019-03-24 01 37 56](https://user-images.githubusercontent.com/1387653/54876951-879b8580-4dd5-11e9-81d7-e6f7723da55f.gif)

**Comment by fkling** [comment]
Probably not an issue anymore because we render this information completely differently now.
