### ISSUE TITLE
Add autoscaling for PCI worker in kubernetes

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#26621]
We would like to automatically scale some services (PCI worker in this instance) based on some custom metrics like a queue size. These are currently captured in prometheus.

- [x] Make sure metrics-server is available in our kube clusters 
- [x] Deploy [prometheus-adapter](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-adapter)
- [ ] Define rules for prometheus-adapter to configure queue size metrics
- [ ] Create HPA resource to control PCI worker pod count based on the custom metric

**Comment by eseliger** [comment]
Should we tag the cloud team here for the prometheus-adapter part?

**Comment by daxmc99** [comment]
@eseliger Do you know what the rules are going to look like for this service? I would like to include them in the deployment instead of using the defaults to start.

**Comment by efritz** [comment]
I think we're both basing knowledge off of what we've done to [auto-scale executors](https://github.com/sourcegraph/terraform-google-executors/blob/master/modules/executors/main.tf#L121), which is basically a dumb heuristic of `ceil(queue size / n) = number of instances`, for some chosen `n` (i.e., 20 for executors).

Our current Prometheus query for our queue size panel is `max(src_codeintel_upload_total{job=~"^precise-code-intel-worker.*"})`.

**Comment by daxmc99** [comment]
Next steps on this:

Encode the above rule into a [PrometheusAdaptor Rule](https://github.com/kubernetes-sigs/prometheus-adapter/blob/master/docs/config-walkthrough.md#configuring-the-adapter) 

Basically, correctly fill out the `rules` section with the above. 

After that, we need to configure the HPA to scale based on that metric.

**Comment by eseliger** [comment]
Hey @daxmc99, we settled on `ceil(max(src_codeintel_upload_total{job=~"^precise-code-intel-worker.*"}) / 4)` as our initial attempt for a rule, can you point me where this would need to go?

**Comment by eseliger** [comment]
Not to myself and @efritz, we should later configure the PCI worker to have an execution deadline of 25m or something like that.

**Comment by daxmc99** [comment]
@eseliger Sorry for the delay on this. You need to put the rule here: https://github.com/sourcegraph/deploy-sourcegraph-cloud/pull/14945#discussion_r818153003

Ignore the argoCD portion for now just focus on filling out the `values.yaml` file for Helm
