### ISSUE TITLE
ci: add an annotation that tells which repo, pr and other informations at the end of every build. 

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#26638]
Presently, it's not very convenient to identify which repo was cloned and which PR is running. While it's rather obvious on the main repo, it's not at all the case on other pipelines. 

Buildkite UI should provide this, but it's a few clicks away, which is adding some unnecessary friction when you're resolving an incident and jumping around pipelines. 

A possible solution would be to create a BK plugin that does this automatically.

**Comment by jhchabran** [comment]
💡 Could be nice to annotate along the way when this was deployed.

**Comment by burmudar** [comment]
We should look at using agent hooks for this so that all pipelines benefit from this @jhchabran
