### ISSUE TITLE
Update enterprise-imports ESLint rule

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#26639]
#### Problem statement

The [enterprise-imports ESLint rule](https://github.com/sourcegraph/sourcegraph/blob/08ae21266b63fe7c3a18ac4c9f12082999da2d68/.eslintrc.js#L53-L62) would give false positives with absolute imports in files under the `enterprise` foder.

```ts
// src/enterprise/main.ts
import { test } from '@sourcegraph/web/enterprise/test.ts' // should not trigger ESLint error
```

#### Success criteria

1. The [enterprise-imports ESLint rule](https://github.com/sourcegraph/sourcegraph/blob/08ae21266b63fe7c3a18ac4c9f12082999da2d68/.eslintrc.js#L53-L62) is updated to work with absolute imports in files under the `enterprise` foder.
2. `dev/check/ts-enterprise-import.sh` in `dev/check/all.sh` is removed.

#### Things to learn/practice during the implementation

ESLint configuration in monorepos.

#### Implementation details

Relevant PR that introduced the ESLint rule: https://github.com/sourcegraph/sourcegraph/pull/23044

#### Estimated amount of work

T-shirt size estimate: **M**.

**Comment by chrishalbert** [comment]
This looks resolved at this point I think.

**Comment by valerybugakov** [comment]
Yep 👍
