### ISSUE TITLE
RFC 503: Limit sub repo access in gitserver using smart client

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#26646]
Use the smart sub repo permissions client to limit access to data via gitserver

Requires https://github.com/sourcegraph/sourcegraph/issues/26645

**Comment by ryanslade** [comment]
Superseded by https://github.com/sourcegraph/sourcegraph/issues/27138

**Comment by bobheadxi** [comment]
See the [November 5th update in RFC 503](https://docs.google.com/document/d/1d8j-6VC_nk8HXEDT6U2_s-_9uSzgzHWZzrJjII9pKEE/edit#heading=h.jongwze3bb71)
