### ISSUE TITLE
RFC 503: Create smart sub repo permissions client

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#26645]
The client is responsible for checking whether a given user can access a specific piece of content inside of a repo.

Details here:
https://docs.google.com/document/d/1d8j-6VC_nk8HXEDT6U2_s-_9uSzgzHWZzrJjII9pKEE/edit#heading=h.4w9htz1j4hqp

**Comment by bobheadxi** [comment]
Testing notes

```sql
select id, name, permission, user_ids_ints
from repo_permissions, repo
where repo_id = id;
```

```sql
update repo_permissions set user_ids_ints = '{1}' where repo_id = ID;

insert into sub_repo_permissions values(ID, 1, 1, '{"**.md"}', '{}', now());
```

```sql
select * from sub_repo_permissions where repo_id = 2
```

**Comment by bobheadxi** [comment]
Closing this for now - we've done many iterations on this API already. Some remaining work is in https://github.com/sourcegraph/sourcegraph/issues/26663 https://github.com/sourcegraph/sourcegraph/issues/27448 etc.
