### ISSUE TITLE
RFC 503: Limit sub repo access for indexed search using smart client

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#26647]
Use the smart sub repo permissions client to limit access to data in indexed search 

Requires https://github.com/sourcegraph/sourcegraph/issues/26645

**Comment by bobheadxi** [comment]
Adjusted to `searcher` in line with #27012

**Comment by bobheadxi** [comment]
I had some confusion here - see https://github.com/sourcegraph/sourcegraph/pull/27012#issuecomment-961190817 , and conflated searcher with zoekt + indexed search. Looks like they are indeed entirely separate. I'm going to just go ahead with searcher for now since I've already got a start on it

**Comment by bobheadxi** [comment]
Superseded by #27139 - see the [November 5th update in RFC 503](https://docs.google.com/document/d/1d8j-6VC_nk8HXEDT6U2_s-_9uSzgzHWZzrJjII9pKEE/edit#heading=h.jongwze3bb71)
