### ISSUE TITLE
Global state management: Update existing Zustand code to use a global store

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#26656]
As part of https://github.com/sourcegraph/sourcegraph/issues/26655 we should update the existing Zustand implementation to use a global store.  This means moving part of [this code](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@tr/webpack-manifest-local/-/blob/client/web/src/search/navbarSearchQueryState.ts#L69:3) to be a generic store, [similar to how we create the Apollo cache.](https://sourcegraph.com/-/editor?remote_url=git%40github.com%3Asourcegraph%2Fsourcegraph.git&branch=tr%2Fwebpack-manifest-local&file=client%2Fshared%2Fsrc%2Fgraphql%2Fapollo%2Fcache.ts&editor=VSCode&version=1.4.0&start_row=0&start_col=0&end_row=0&end_col=0).

**Comment by fkling** [comment]
Sorry for the late response (OOO, catching up), but yes, I'll take this on.
