### ISSUE TITLE
RFC 503: implement caching for smart client

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#26663]
extend https://github.com/sourcegraph/sourcegraph/issues/26645 with caching as described in [RFC 503](https://docs.google.com/document/d/1d8j-6VC_nk8HXEDT6U2_s-_9uSzgzHWZzrJjII9pKEE/edit#heading=h.ko15domw9plt)

**Comment by ryanslade** [comment]
I'm going to add some basic short lived caching for perm lookup and rule generation
