### ISSUE TITLE
insights: migrate lang-stats insights to the DB

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#26676]
We need to migrate any currently created lang-stats insights to the DB.

**Comment by CristinaBirkel** [comment]
@coury-clark Did you have anything in mind for how to store these?

Right now I'm thinking that we just add a couple of new columns to `insight_view`. Maybe called `repository` and `other_threshold`, or we could use a prefix and do `lang_stats_repository` and `lang_stats_other_threshold`.

Thinking ahead to supporting other chart types, will this table get sort of unwieldy? That's my concern, but I'm not sure if there's a better alternative? Just want to check in and make sure we're on the same page here before I go too far down the path of implementing it.

**Comment by coury-clark** [comment]
@CristinaBirkel 

It's important to consider that "lang stats" is just a time series just like any other:
1. It captures language stats information (similar to how we may capture regex groups in the near future)
2. It groups by language (similar to above)
3. It only needs a single data point from the timeseries (which I think we already have, but these will be executed on the frontend for now so it should be fine)
4. Displays on a pie chart. This implies we need to differentiate chart type at the `insight_view` level, so probably a new column there.
4. Has new `view` options, notably `other_threshold` that are not relevant for other chart types. This can live on the `insight_view` table, and we can use the application to "decode" these into appropriate types.

We can handle repository scopes in the same way we do for line charts, with a column on the associated `insight_series`

I wouldn't worry about the bloat on the table - we can address that problem if / when it becomes one. As long as we are keeping the tables focused (with view options / data going in the view table, etc), we should be fine.

**Comment by CristinaBirkel** [comment]
@coury-clark Ah I hadn't considered attaching a series to store the repository. Hmm, I think it might actually be the case that an insight won't even return via the API if it doesn't have at least one series attached. (Maybe that's a bug, but I'm not sure it's a real use case either.) This seems different than capture groups though, where we will auto-generate multiple series. This will be a single series that's only acting as a storage for the repository scope. It has to go somewhere though. Hmm. If the eventual plan is to use capture groups to do the lang stats insights on the backend I guess it will be a temporary thing anyway, and if we use a series there will be nothing to rip out (unlike adding another column.) I'm just thinking out loud at this point. Okay; I'm good with that. 👍 

So a new column on `insight_view` for the `type` (or maybe the `presentation_type`), and a new column for `other_threshold`. And `repositories` will be on the single attached series. And the front end can just read it from there, and write the update to there. That sounds like it will work. Thanks for clarifying!

**Comment by coury-clark** [comment]
@CristinaBirkel just to clarify one point here - an insight without a time series is by definition a blank chart. The model is that an `insight_series` relates with at least one time series. In the case of capture groups, we are considering expanding the time series based on grouped values (similar to group by in a SQL query), but we still need to have that base time series.

It's the same thing here - we need a time series to generate the pie chart. It just so happens that the time series also needs to collect language information such that we can group on it. It's not exactly the same as capture groups (we aren't planning on using a capture group specifically), it's the mechanism of grouping that is the same.

> This will be a single series that's only acting as a storage for the repository scope
It also acts as the driver for calculating the data - which we need to do. It's not an arbitrary association, the `insight_series` corresponds to actual data.

One thing that comes to mind here is that we will want to store with the `insight_series` what kind of metadata we are storing alongside it (capture groups, language stats, etc). I don't think we necessarily need to address for this issue since we are still going to execute these on the frontend, but we would need to address this so that we can collect the information on the backend.
