### ISSUE TITLE
Double forward slash in Find references link in the Browser Extensions

### ISSUE THREAD

**Issue by ducher** [sourcegraph/sourcegraph#2673]
#### Steps to reproduce:

1. Hover a function with the browser extension activated
2. The link generated contains 2 forward slashes after the domain name ( https://sourcegraph.com//github.com/sourcegraph/sourcegraph@5b9362940c84ca79c2ca277b9b1d5bbbccb47d3b/-/blob/shared/src/util/url.ts#L455:17&tab=references )

It works on the sourcegraph server but not on my own as the official sourcegraph server probably rewrites the URL to ignore the duplicate slash.

The issue is that we concatenate two '/' in the toAbsoluteBlobURL function, as the toPrettyBlobURL always returns a string begining with a '/' : https://github.com/sourcegraph/sourcegraph/blob/5b9362940c84ca79c2ca277b9b1d5bbbccb47d3b/client/browser/src/shared/util/url.tsx#L18
and 
https://github.com/sourcegraph/sourcegraph/blob/5b9362940c84ca79c2ca277b9b1d5bbbccb47d3b/shared/src/util/url.ts#L458

#### Expected behavior:
Have a valid URL (https://sourcegraph.com/github.com/sourcegraph/sourcegraph@5b9362940c84ca79c2ca277b9b1d5bbbccb47d3b/-/blob/shared/src/util/url.ts#L455:17&tab=references)

#### Actual behavior:
The link is invalid and sourcegraph doesnt find the file.

**Comment by ducher** [comment]
FYI I fixed the issue with a workaround in my apache config:
```
        RewriteEngine On
        RewriteCond %{REQUEST_URI} ^//(.*)$
        RewriteRule ^/(.*)$ https:/yourserver.com/$1 [R=301,L]
```

**Comment by AHassanSOS** [comment]
I have the same issue with the browser extension. It adds an extra slash at the end.

**Comment by sqs** [comment]
@lguychard @felixfbecker Reprioritizing because 2 different users have reported it and 1 went through the trouble of adding web server config to fix it. This is less important than Bitbucket Server issues and other critical customer issues, but otherwise it seems like a straightforward and important fix.
