### ISSUE TITLE
Add support for regex lookaround expressions

### ISSUE THREAD

**Issue by LinqLover** [sourcegraph/sourcegraph#26733]
#### Feature request description

It would be nice to use the full lookaround expression syntax (positive lookahead, positive lookbehind, negative lookahead, negative lookbehind) for regexes in Sourcegraph queries.

#### Is your feature request related to a problem? If so, please describe.

I stumbled upon this "missing feature" when performing [this query](
https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/dalehenrich/filetree%24+%5E%5C*%5B%5E%5Cr%5Cn%5D%2B%24%28%3F%3C%21-override%29&patternType=regexp):

```sourcegraph
repo:^github\.com/dalehenrich/filetree$ ^\*[^\r\n]+$(?<!-override)
```

#### Describe alternatives you've considered.

Theoretically, I could post-filter the results by grepping the CLI output ...

**Comment by benvenker** [comment]
@rvantonder and @camdencheek I assume given the recent issue for lookahead/lookbehind that we said we won't support that this is also effectively a wontfix, at least for now? The recommended solution from @camdencheek was in fact post-processing results on the user's local machine.

**Comment by camdencheek** [comment]
Yes, that's right. There are no plans to support lookahead/lookbehind. More details about why can be found [here](https://github.com/sourcegraph/sourcegraph/issues/636) and more details about workarounds (including a sample using CLI post-filtering) can be found [here](https://github.com/sourcegraph/sourcegraph/issues/31454#issuecomment-1043859744).
