### ISSUE TITLE
Make GitHub client package obey the same conventions as the GitLab client package

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#2676]
The GitLab client package, `extsvc/gitlab`, has two types, `ClientProvider` and `Client`. The former produces the latter, and the latter is associated with a specific user identity. The `authz/gitlab` package relies on the latter to compute permissions for a given user.

Meanwhile, the GitHub client package, `extsvc/github`, has only a `Client` type, which has a "base" token. Certain methods of `Client` allow specifying an override access token. These methods are used by the `authz/github` package to compute permissions for a given user. There are two issues with the GitHub client package:
* Not all `Client` methods support the override user token, meaning inconsistency in the API.
* The override token is bug-prone and there are caching constraints that might be easily broken in the future (i.e., cache entries should not be shared across different user identities).

We should update `extsvc/github` to use the `ClientProvider` + `Client` pattern used in `extsvc/gitlab`.

**Comment by keegancsmith** [comment]
Additionally we should probably look into using https://github.com/google/go-github again.

**Comment by beyang** [comment]
Does anyone recall the rational for not using `go-github`?

**Comment by sqs** [comment]
It didn’t support GraphQL at the time and it was overkill for the 1 API request we needed. I have no opinion or knowledge about whether it’s a good choice now.

**Comment by tsenart** [comment]
I don't think this is super relevant anymore, so closing.
