### ISSUE TITLE
GitHub link disappears intermittently in 3.x

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#2677]
From customer:

> Since the 3.x upgrade we've been seeing the :github:  link disappear intermittently. Sometimes reloading the page fixes it.
>
> It's almost always happening, I don't see a discernable pattern in the times that it does show up
> 
> I first noticed this when testing 3.x out on our test instance, and at the same time it worked properly on our production instance (running 2.x), so it seems to be related to the upgrade

More info (possibly separate issue):
> More info: we are seeing the following under the "Mirroring" details for the repos where the link isn't showing up. In some cases they are being refreshed properly, in some cases they are showing as very out of date

https://sourcegraph.slack.com/archives/GDS3PJ8GK/p1551726810000500

Reported by https://app.hubspot.com/contacts/2762526/company/561806411

**Comment by keegancsmith** [comment]
I am unsure why this is occurring. As such I have created two PRs which include more debug information around these code paths:

- https://github.com/sourcegraph/sourcegraph/pull/2679
- https://github.com/sourcegraph/sourcegraph/pull/2627

The intention is to cherry-pick/backport it to the version the customer is on, and create a new minor release.

**Comment by slimsag** [comment]
I will cherry-pick / back-port these since I am cutting a patch release as well: https://github.com/sourcegraph/sourcegraph/issues/2682

**Comment by slimsag** [comment]
Your changes are on the 3.1 branch, and in a `3.1.2-rc.1` I am doing some final testing on. I did omit one very minor log line in one of your changes, because it would require back-porting a larger change. More details here: https://github.com/sourcegraph/sourcegraph/commit/1a3509dab9198036ea5fca8a7142036f7d6d6e60 Feel free to backport that log line if you want, though.

I will finish the process of cutting the release (the stuff in https://github.com/sourcegraph/sourcegraph/issues/2682) tomorrow

**Comment by keegancsmith** [comment]
Thanks @slimsag. We can leave that log line out.

**Comment by keegancsmith** [comment]
Customer: Once `3.1.2` is out I encourage you to set `SRC_DEBUG_LEVEL=dbug` and try reproduce the problem. The logs from `repo-updater` will be the most interesting. Additionally you can check the Go trace page for repo-updater for other clues. For more troubleshooting information I just started an initial guide in https://github.com/sourcegraph/sourcegraph/pull/2692

**Comment by keegancsmith** [comment]
This is still an issue for the customer. I believe the cause is `repositoryPathPattern: "{nameWithOwner}"` in there config, which we haven't properly tested for a GHE instance. There are parts of our codebase which may result in us not using the external ID when doing repoLookup => failing to get links for a repository.

**Comment by keegancsmith** [comment]
This was actually fixed in 3.3 when we shipped the new syncer for GitHub (enabled by default).
