### ISSUE TITLE
Add support for npm package repositories

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#26772]
Currently, it's complicated to configure cross-repo navigation for JavaScript/TypeScript projects. Ideally, users should be able to follow the instructions here https://docs.sourcegraph.com/code_intelligence/how-to/index_a_typescript_and_javascript_repository once per repo and then be able to navigate to their npm module dependencies. Today, you need to setup LSIF indexing for your own repositories AND the repositories of your npm dependencies (at the exact correct git commits corresponding to the released npm artifacts).

We have solved this problem for Java with the new "JVM Dependencies" external service type (example repo https://sourcegraph.com/maven/org.scala-lang/scala-library). We should use the same approach for JS/TS by adding support to automatically create repositories that proxy the sources of npm modules.

Sub-tasks:
- [X] (Base functionality; needed for Cloud) Add a new external service type dealing with NPM dependencies. https://github.com/sourcegraph/sourcegraph/pull/28057
- [x] (Base functionality; needed for Cloud) Automatically fetch and index LSIF-referenced dependencies
  - [X] Automatically fetch dependencies and store them in the database. https://github.com/sourcegraph/sourcegraph/pull/29247
  - [x] 🚧 Automatically index dependencies. This does work for the basic cases, but it doesn't seem to be handling the full dependency graph. We should check whether we are inferring the right auto-indexing configuration; we should be creating a minimal `tsconfig.json` with something like `{"compilerOptions":{"allowJs":true}}`.
    - [X] 1/3 Add stub for new `--inferTSConfig` flag in `lsif-node`. https://github.com/sourcegraph/lsif-node/pull/183
    - [X] 2/3 Use `--inferTSConfig` in `sourcegraph/sourcegraph`. https://github.com/sourcegraph/sourcegraph/pull/30099
    - [X] 3/3 Implement logic for `--inferTSConfig` in `lsif-node`. https://github.com/sourcegraph/lsif-node/pull/184  [Need to fix some bugs in this patch.]
- [X] (Quality of Implementation/Security) We can replace the current usages of the `npm` CLI with calls to the NPM Registry API. https://github.com/sourcegraph/sourcegraph/pull/29799
- [X] (Needed for Enterprise) We need to add support for custom credentials. This should be relatively easy to add once we start using the NPM Registry API. https://github.com/sourcegraph/sourcegraph/pull/30232
- [x] Debug production issues. For example, this [LSIF upload](https://sourcegraph.com/github.com/hannahcode/word-guessing-game/-/code-intelligence/uploads/TFNJRlVwbG9hZDoxMTQwNzc5) should've triggered auto-indexing for the dependencies but it doesn't seem to be working.
  - [x] One of the issues we ran into is an out-of-bounds indexing bug. https://github.com/sourcegraph/sourcegraph/issues/30554
  - [x] The other issue we ran into is that repo-updater in prod is old (Jan 26), so it didn't have a bug-fix that was part of my credentials patch.
  - [x] https://github.com/sourcegraph/sourcegraph/issues/31061
  - [x] https://github.com/sourcegraph/sourcegraph/issues/31062
  - [x] https://github.com/sourcegraph/sourcegraph/issues/31063

**Comment by jyavorska** [comment]
In the product engineering project, this item has a delivery date of FY22 Q4 which is in the past. @macraig can you please take a look?

**Comment by macraig** [comment]
@jyavorska this project is nearing completion. Should move it over to FY23 Q1?

**Comment by jyavorska** [comment]
Yeah, I went ahead and did it based off your info @macraig. Can you please set the launch tier and month, if you know it?
