### ISSUE TITLE
Migrate Zoekt to Sourcegraph repo

### ISSUE THREAD

**Issue by jjeffwarner** [sourcegraph/sourcegraph#26801]
Expected work required from [Slack discussion](https://sourcegraph.slack.com/archives/C023ELQLV7F/p1635347436024500)

Expected completion date is 2021-11-12 so it can be coordinated with Content team.

1. We’ll rename sourcegraph/zoekt and create a new repository with that name that isn’t a GitHub fork of google/zoekt. We’ll also migrate PRs and issues from both our fork and google/zoekt.
2. We’ll open up a PR on google/zoekt updating the README to announce end of maintenance of that particular repository and redirecting  folks to sourcegraph/zoekt.
3. I’ll write a blog post, subject to your approval, announcing the switch. If you prefer, we won’t even mention Google and instead focus on  highlighting your contributions, our commitments to the user community, and our plan forward for the project.

**Comment by keegancsmith** [comment]
- We are no longer a fork!
- google/zoekt CR https://gerrit-review.googlesource.com/c/zoekt/+/323055
- sourcegraph/zoekt PR https://github.com/sourcegraph/zoekt/pull/198

**Comment by keegancsmith** [comment]
All the technical stuff has been done, so gonna close this issue out.
