### ISSUE TITLE
Open batch change changesets are not updated if the repo is archived while they're open

### ISSUE THREAD

**Issue by LawnGnome** [sourcegraph/sourcegraph#26820]
Original source: https://sourcegraph.slack.com/archives/C02BJ8T258D/p1635458039067400

### Steps to reproduce

1. Create a batch change that publishes a changeset to repo `X` (the report is on GitHub, but I'd assume this is going to be true for all code hosts).
2. Archive `X` on the code host, making it read only. All PRs are locked at this point.
3. Observe that Batch Changes still thinks the PR is open, and the PR cannot be closed within the batch change.

### Planned solution

Add a new terminal state that behaves like `closed` but is displayed differently to avoid confusion. (Name TBC, since we already have a concept of "archiving" that's different in Batch Changes.)

We need to be able to migrate both into and out of that state as repositories are archived and unarchived.

For now, we'll only do this on changeset sync or reconciler error, but an obvious future enhancement would be to also update changeset state when `repo-updater` becomes aware of a repo being archived or unarchived. (Indeed, Batch Changes could also update the repo once if it becomes aware before `repo-updater`.) The main technical challenge here is that it crosses the open source/enterprise boundary, and would probably need some new plumbing. (Maybe a notification queue via Redis on `repo-updater` events?)

### Reconciler errors to handle

We want to detect useful errors in both the `push` and `update` operations. We'll probably have to do this the old fashioned way with string comparisons in most cases.

<table>
<thead>
<tr><th>Code host</th><th>On push</th><th>On update</th>
</thead>
<tbody>
<tr>
<td>GitHub</td>
<td>
<pre><code>ERROR: This repository was archived so it is read-only.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.</code></pre>
</td>
<td><pre lang="json"><code>{
  "data": {
    "updatePullRequest": null
  },
  "errors": [
    {
      "type": "UNPROCESSABLE",
      "path": [
        "updatePullRequest"
      ],
      "locations": [
        {
          "line": 314,
          "column": 3
        }
      ],
      "message": "Repository was archived so is read-only"
    }
  ]
}
</code></pre></td>
</tr>
<tr>
<td>GitLab</td>
<td><pre><code>remote:
remote: ========================================================================
remote:
remote: ERROR: You are not allowed to push code to this project.

remote:
remote: ========================================================================
remote:
fatal: Could not read from remote repository.</code></pre></td>
<td>403 Forbidden (no other useful message to disambiguate)</td>
</tr>
<tr>
<td>Bitbucket Server</td>
<td rowspan="2" colspan="2">No concept of archiving a repo, or making it completely read only</td>
</tr>
<tr>
<td>Bitbucket Cloud</td>
</tr>
</tbody>
</table>

**Comment by eseliger** [comment]
Does archiving a repo also mark all PRs as closed? If not, I think this is expected behavior.

**Comment by sfllaw** [comment]
Please remember that a repository can be unarchived, so the changeset must be able to leave whatever state you’ve parked it in.
