### ISSUE TITLE
The Line Number Problem

### ISSUE THREAD

**Issue by KashingLiu** [sourcegraph/sourcegraph#26858]
- **Sourcegraph version:** Version: 3.31.1

#### Steps to reproduce:
1. search something using graphql api, focus on the `lineNumber` field
```
query ($query: String!) {
  search(query: $query, version: V2) {
    results {
      results {
        ... on FileMatch {
          ...FileMatchFields
        }
      }
      matchCount
      elapsedMilliseconds
    }
  }
}

fragment FileMatchFields on FileMatch {
  file {
    path
    url
  }
  repository {
    name
  }
  lineMatches {
    preview
    lineNumber
    offsetAndLengths
  }
}
```
2. see the file displayed in the result
3. the line number in the api result doesn't match the real line number in the file

#### Expected behavior and actual behavior:
For example, the api tells me that the keyword appears at line 17, but I open the file and find the keyword appears at line 18.
I know that on the result page, if there is just one match line, the program will show the previous row and the next row. But I may think the API is not accurate enough. I think the API should return the correct line, something should be process on the frontend

**Comment by camdencheek** [comment]
@KashingLiu The line number as returned by the API is zero-based. Most editors (and the Sourcegraph UI) use 1-based line numbering. You should just need to add 1 to get the line number you're expecting.
