### ISSUE TITLE
Status of gologin

### ISSUE THREAD

**Issue by asdine** [sourcegraph/sourcegraph#26867]
The [sourcegraph/gologin](https://github.com/sourcegraph/sourcegraph/blob/main/go.mod#L351-L355) fork causes [some issues](https://buildkite.com/sourcegraph/sourcegraph/builds/114518#bee5ae97-2a0e-4ebb-ae09-5993f4d5f574) with go mod when using sourcegraph/sourcegraph as a dependency for our command line tools.

It seems that the changes have been merged but [comparing with the main repo](https://github.com/dghubble/gologin/compare/master...sourcegraph:master) is a bit ambiguous and we are not sure if we can update the repo or not.
@beyang Before investigating further we're trying to get as much context as possible. If I understand correctly, this fork seems to have been pushed upstream a while ago, do you remember if it still contains some unmerged changes or if we kept the fork for a specific reason?

**Comment by eseliger** [comment]
@pjlast I think you resolved this today? 😁

**Comment by pjlast** [comment]
@eseliger haha yeah seems like unintentional issue solving :D

**Comment by pjlast** [comment]
Closed by https://github.com/sourcegraph/sourcegraph/pull/57391
