### ISSUE TITLE
User Journey analytics gaps

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#26872]
- [ ] (#26968)
- [ ] Onboarding emails
  * impact on retention
  * improvements to key stages

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @a-bergevin - the "team/growth" label was applied to this issue.

**Comment by a-bergevin** [comment]
Not enough details on this one so we'll just close and open a new one on anything related that comes up
