### ISSUE TITLE
Investigate adding PgBouncer to our infrastructure

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#26908]
Came up after [#inc-2021-10-26-sourcegraphcom-is-completely-down](https://sourcegraph.slack.com/archives/C02K45WQU90) 

PgBouncer was suggested as an approach to improve db connection usage. This card represents the spike task to confirm that.

**Comment by daxmc99** [comment]
Also should consider https://github.com/yandex/odyssey

**Comment by JenRed777** [comment]
Jennifer and Dax to look at to determine best path to use this.

**Comment by JenRed777** [comment]
Looked at this one with @daxmc99 and we should be able to add PgBlocker. Setting this to Up Next until we are ready to do the work

**Comment by danieldides** [comment]
Strong resource: https://medium.com/google-cloud/increasing-cloud-sql-postgresql-max-connections-w-pgbouncer-kubernetes-engine-49b0b2894820

**Comment by daxmc99** [comment]
Also consider https://github.com/levkk/pgcat

**Comment by jhchabran** [comment]
Tangential, `pgbouncer` (or anything similar) could be useful to not have to deal with deal with connections explictly within the tests (see https://github.com/sourcegraph/sourcegraph/issues/37743).

**Comment by daxmc99** [comment]
Closed for staleness
