### ISSUE TITLE
Appropriately scale cloud

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#26911]
We scaled cloud heavily for the dot-com launch. We are now in a stable state and can start to ensure we have not overprovisioned our resources. 

TODOs to be done **in-order**:

- [x] Ensure QoS `Guaranteed` for all stateful services
[PR](https://github.com/sourcegraph/deploy-sourcegraph-cloud/pull/15199)
- [ ] Ensure all services have resource limits
[PR](https://github.com/sourcegraph/deploy-sourcegraph-cloud/pull/15200)
- [x] Enable K8s autoscaling (allow scale down)
[Vertical node autoscaling enabled](https://github.com/sourcegraph/infrastructure/blob/main/cloud/main.tf#L101)
[Horizontal node autoscaling enabled](https://github.com/sourcegraph/infrastructure/blob/main/cloud/main.tf#L122)
Horizontal Pod Autoscaling (HPA) only enabled for `sourcegraph-docsite`
- [x] Setup default logging containers for all services
[PR](https://github.com/sourcegraph/deploy-sourcegraph-cloud/pull/15201)
- [ ] Setup requested resources/limits based on the usage (cost savings)
[PR](https://github.com/sourcegraph/deploy-sourcegraph-cloud/pull/15202)

**Comment by daxmc99** [comment]
Next steps here:
It is hard to find codeowners at Sourcegraph. @pdubroy has created https://handbook.sourcegraph.com/departments/product-engineering/engineering/process/engineering_ownership to help address this. 

Maybe we could collaborate with him to identify codeowners for some services (`gitserver` & `symbols` come up as good examples) 

Colloquially, I believe that search-core owns `gitserver` & `symbols` is owned by the code intel team but there should be a table that all teams can reference. 

We should also add an annotation or label to these services so that someone looking at the YAML can tell. 

Lastly, there are also services like `frontend` which are widely shared. DevOps can be the default owners of these if not Cloud SaaS

**Comment by JenRed777** [comment]
waiting on feedback
