### ISSUE TITLE
SSBC-EM2.3-CACHE1: Implement caching of full changeset specs

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#26929]
Part of https://github.com/sourcegraph/sourcegraph/issues/26142

- [x] Extract [`createChangesetSpecs`](https://github.com/sourcegraph/src-cli/blob/240d3b6f6fdb6eafdf0aa0775e74da57198136a7/internal/batches/executor/changeset_specs.go#L18) from `src-cli` into `sourcegraph/lib` and use in src-cli - **`1d`**
  - https://github.com/sourcegraph/sourcegraph/pull/26997
  - https://github.com/sourcegraph/src-cli/pull/648
- [x] Add implementation of [`ExecutionCache`](https://github.com/sourcegraph/src-cli/blob/240d3b6f6fdb6eafdf0aa0775e74da57198136a7/internal/batches/executor/execution_cache.go#L143-L151) that writes JSON LogLines on write-events **`0.5d`**
  - [x] https://github.com/sourcegraph/sourcegraph/pull/27061
  - [x] https://github.com/sourcegraph/src-cli/pull/649
- [x] Make `src batch exec` use this cache **`0.5d`**
- [x] Server-side: extract cache-write events from log entries and save to new `batch_spec_execution_cache_entries` table with K/V layout **`2d`**
  - `key` is cache key
  - `value` is text/jsonb/binary/whatever
  - `version` is a number that signifies format used in cached value
  - `last_used_at`
  - `created_at`
  - https://github.com/sourcegraph/sourcegraph/pull/27125
  - https://github.com/sourcegraph/sourcegraph/pull/27212
- [x] Extract implementation of [`TaskCacheKey`](https://github.com/sourcegraph/src-cli/blob/240d3b6f6fdb6eafdf0aa0775e74da57198136a7/internal/batches/executor/execution_cache.go#L110-L141) from src-cli to `sourcegraph/lib` **`2d`**
- [x] In workspace resolution: build cache key, check against database, set boolean `cached_result_found` on `batch_spec_workspace`, if cache hit: build changeset specs, persist, wire up correctly **`1d`**
- [x] In workspace resolver: if cached result found, return `CachedResultFound: true` and `State: completed` **`0.5d`**
- [x] When creating batch spec workspace execution jobs: skip workspaces with where `cached_result_found` boolean is set to true **`0.5d`**
- [x] UI: Show `workspace.CachedResultFound` **`0.5d`**
- [x] UI: All `workspace.Steps` are shown as `skipped` **`0.5d`**
- [x] Ensure that `steps.env` forwarding isn't usable in SSBC because it would break caching. **`0.5d`**
- [x] Periodic background job that cleans up old cache entries **`1d`**
  - If possible: use table size (max X gigabyte) and evict LRU entries first
  - https://github.com/pulls?q=is%3Apr+author%3Amrnugget+archived%3Afalse+user%3Asourcegraph+is%3Aclosed
- [x] In `src batch exec`: disable full-spec-caching in coordinator **`0.5d`**
  - https://github.com/sourcegraph/src-cli/pull/653
  - Remove `-clear-cache` flag https://github.com/sourcegraph/sourcegraph/pull/27338
- [x] Ensure that recreated-from-cache changeset specs are also cleaned up in `replaceBatchSpecInput` **`0.5d`**

**Comment by eseliger** [comment]
DONE!
