### ISSUE TITLE
Include p4-fusion in gitserver image

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#26926]
Now that [p4-fusion](https://github.com/salesforce/p4-fusion) is open source we should add a step in our gitserver [Dockerfile](https://github.com/sourcegraph/sourcegraph/blob/main/cmd/gitserver/Dockerfile) that pulls down a release, builds it and ensures that it is in the path.

We should use the latest release here: 
https://github.com/salesforce/p4-fusion/releases

(The latest good known release at time of writing is [1.2](https://github.com/salesforce/p4-fusion/releases/tag/v1.2))
UPDATE: currently (22 Dec 2021) the [v1.4](https://github.com/salesforce/p4-fusion/releases/tag/v1.4) is latest

We have an example Dockerfile [here](https://github.com/sourcegraph/p4-cpp-client/pull/2) which shows how to build it

- [ ] Delete our current private fork: https://github.com/sourcegraph/p4-cpp-client

**Comment by sashaostrikov** [comment]
How to build an image locally:
1) You can try to put a one-line script near /cmd/gitserver/build.sh with following contents:
```bash
IMAGE=sourcegraph/server:0.0.0-DEVELOPMENT VERSION=0.0.0-DEVELOPMENT time ./cmd/gitserver/build.sh
````
2) You can just remove `ENTRYPOINT` statement from Dockerfile, so it will not complain about go executive which is not built. Then the entry point will default to bash shell, and the container can be easily accessed
