### ISSUE TITLE
Add an alert for CPU throttling of gitserver container

### ISSUE THREAD

**Issue by indradhanush** [sourcegraph/sourcegraph#26925]
Blocked by #27122. 

The metric to be used can be seen here: https://sourcegraph.com/-/debug/grafana/d/gitserver/git-server?viewPanel=100010&orgId=1&var-alert_level=All&var-shard=All&from=now-7d&to=now

**Comment by DaivikDave** [comment]
Hi @indradhanush,
I'm new to sourcegraph can you help me with this issue. If the issue is still open, the changes required would be [here](https://github.com/sourcegraph/sourcegraph/blob/main/monitoring/definitions/git_server.go#L78). Should the alert level be warning and threshold be 70%.
