### ISSUE TITLE
Cannot close "get started" hovercard on homepage

### ISSUE THREAD

**Issue by LinqLover** [sourcegraph/sourcegraph#26959]
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:** Google Chrome 94.0.4606.81

#### Steps to reproduce:

1. Go to <sourcegraph.com/search> (do not log in)
2. Press the X on this hovercard:
   ![image](https://user-images.githubusercontent.com/38782922/139922960-ff8f7ec3-d2d2-4e78-89eb-016bc1c64d6d.png)

#### Expected behavior:

The hovercard is closed.

#### Actual behavior:

It remains open.

**Comment by rrhyne** [comment]
Thanks for submitting this issue @LinqLover!
