### ISSUE TITLE
Design work for Search Notebooks file block

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#26976]
Add a new File block with the following inputs: repository, revision, file path, and line ranges. The output should be syntax highlighted lines, or the entire file if no line ranges were provided.

**Comment by marisak** [comment]
I have some preliminary questions, see the following: 
- [Figma](https://www.figma.com/file/32wyz09t6u2bSBvsJwmDEA/Search-Notebooks-GA?node-id=1166%3A542) (Search notebooks GA > Sketches) 
- [Loom](https://www.loom.com/share/9f380fcce8aa4ccfb4e0858fd765a84f)

**Comment by marisak** [comment]
Met with Rok today to discuss further! Working on wireframes, will be done by the end of the week. [Figma: Search notebooks GA > Wireframes](https://www.figma.com/file/32wyz09t6u2bSBvsJwmDEA/Search-Notebooks-GA?node-id=1254%3A3129)
