### ISSUE TITLE
Support Apex file detection with Zoekt:

### ISSUE THREAD

**Issue by jjeffwarner** [sourcegraph/sourcegraph#26974]

**Comment by stefanhengl** [comment]
@keegancsmith I believe you were the last one working on this. Please reopen if there is still work to do.

**Comment by keegancsmith** [comment]
So the feature flag to use content based language detection is still off. I'll continue the discussion on the other issue linked here since it contains a much more general and rich description. https://github.com/sourcegraph/sourcegraph/issues/7841
