### ISSUE TITLE
Do not list BatchSpecs that were already applied

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#26987]
This ticket is an extraction from this comment chain: https://github.com/sourcegraph/sourcegraph/pull/26937/files#r741811497

Problem we need to address (or think about) when listing batch specs/batch changes/drafts/etc.: what do we do with the batch specs that were already applied but were superseeded by another batch spec? Nothing in our system says that you can't re-apply the old one again. In fact that might be a feature?

**Comment by rrhyne** [comment]
I believe this aligns with the executions log of a batch change where we would store the spec on the change. 

![image](https://user-images.githubusercontent.com/539268/140061554-21b022a2-bf88-4f93-b01d-9cf9526fed66.png)

We simply store the execution (even if it wasn't executed) with the change in the order it was created/applied.
