### ISSUE TITLE
sentry: provide server-side passthrough for web app Sentry events

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#26981]
Ad-blocking or script-blocking extensions may [prevent](https://github.com/easylist/easylist/issues/6963) Sentry SDK from being fetched and initialized correctly. The solution here would be to use [a server-side pass-through for event reporting](https://docs.sentry.io/platforms/javascript/troubleshooting/#dealing-with-ad-blockers) and our CDN for serving the init script.

**Comment by bobheadxi** [comment]
Tagging this in https://github.com/sourcegraph/sourcegraph/issues/37778 as I think it could be relevant, in the grand scheme of improving this sort of data

**Comment by jhchabran** [comment]
@valerybugakov the last version of the PR should work transparently for dotcom, assuming the client doesn't block getting the sentry pkg from the CDN in the first place.
