### ISSUE TITLE
Increase click target region for file tree navigation drawer

### ISSUE THREAD

**Issue by RamV13** [sourcegraph/sourcegraph#27]
Currently, the click target is isolated to the icon but it would be nice if the clickable region was composed of the entire bounding box. This is especially apparent upon scrolling when the bounding box is more clearly defined by the color boundary.

**Comment by beyang** [comment]
Can you post a screenshot?

**Comment by RamV13** [comment]
Currently, the click target is restricted to within the blue region below. It might be easier to expand the drawer if the entire black region was the click target.

<img width="45" alt="screen shot 2017-08-28 at 4 04 35 pm" src="https://user-images.githubusercontent.com/6133192/29791395-c2a2d0ae-8c0a-11e7-9f28-dfa84d97b6be.png">

**Comment by sqs** [comment]
This has been changed significantly, and the original issue is no longer a problem.
