### ISSUE TITLE
Add "Programming languages" category to extensions

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#2700]
https://sourcegraph.com/extensions?query=category%3A%22Programming+languages%22 should show all code intel extensions. Their package.jsons need the category "Programming languages".

**Comment by chrismwendt** [comment]
I think I had a capital `L` in `Programming Languages` because I saw this warning message in VS Code on the `categories` field:

![image](https://user-images.githubusercontent.com/1387653/54243385-743f0f00-44e5-11e9-9226-c3f3c981a154.png)
