### ISSUE TITLE
Replace Renovate with an hourly & daily cron job

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#27036]
Renovate's non-determinism causes some issues when performing rollouts. 
We should use a cron job for this task

TODO:

- [ ] Modify `./tools/update-all-images.sh` to support new versioning scheme

**Comment by unknwon** [comment]
GitHub Actions are can be configured as CRON jobs...

**Comment by JenRed777** [comment]
Still need code reviews and finding owner of SG Tool.
