### ISSUE TITLE
SPIKE: Search monitoring improvements

### ISSUE THREAD

**Issue by jjeffwarner** [sourcegraph/sourcegraph#27043]
For Q4 OKR for large mono-repos. [From Jamboard](https://jamboard.google.com/d/1-rNnz6v1MmXPV5wcVbT24S7FDcrBAIize6wkDSvqEJs/viewer?f=0)

### Investigate the following avenues:

Overhaul search monitoring to be consistent with some best practices (i.e. RED, 4 Golden Signals, etc) and use that to monitor our progress towards the latency KRs

### Timebox
5 days?

**Comment by ggilmore** [comment]
Is there any additional context about the kinds of gaps that we think we have in our monitoring? An issue or a slack link as an example? (The Jamboard doesn't seem to have additional context around this note)

**Comment by jjeffwarner** [comment]
From [our diagram](https://miro.com/app/board/o9J_lk_GP34=/?invite_link_id=374611483102).

1. Capture time to index in dashboard
2. Unindexed searches require better measurements. Perhaps some new sentinel queries to exercise this in the mega repo? Or other?

**Comment by keegancsmith** [comment]
@ggilmore any more work to do here that is worth capturing in this issue? I think you did most of the improvements we wanted?

**Comment by ggilmore** [comment]
No, this issue can be closed.
