### ISSUE TITLE
Fix unindexed symbols/popup window timing out

### ISSUE THREAD

**Issue by jjeffwarner** [sourcegraph/sourcegraph#27045]
From brainstorming session and client conversations:

1. Low hanging fruit: unindexed symbols constantly causes issues in monorepos due to symbol sidebar and bad handling of timeouts.
2. Fix symbols search/popup window timing out on monorepo.

**Comment by DaedalusG** [comment]
I believe @keegancsmith had an idea for a quick improvement on this issue.
https://github.com/sourcegraph/sourcegraph/issues/13053

Context from a customer instance in [this thread](https://sourcegraph.slack.com/archives/C011899KB6U/p1597454992360300).

**Comment by keegancsmith** [comment]
@stefanhengl @DaedalusG reproduces this all the time on the chromium repo. I got a trace from him of it timing out https://sourcegraph.grafana.net/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22grafanacloud-sourcegraph-traces%22,%7B%22query%22:%2201d911d0084f3507%22,%22queryType%22:%22traceId%22,%22refId%22:%22A%22%7D%5D

He was visiting a specific commit. If he visits an indexed branch (eg master), it works.

**Comment by ShaneDelmore** [comment]
For files unchanged since the last lsif upload, it would be wonderful if we could just populate the symbols from the lsif indexes.  In a large monorepo 99% of the files will be unchanged daily.
