### ISSUE TITLE
SPIKE: Explore git maintenance and diff commit search for performance gains

### ISSUE THREAD

**Issue by jjeffwarner** [sourcegraph/sourcegraph#27041]
For Q4 OKR for large mono-repos. [From Jamboard](https://jamboard.google.com/d/1-rNnz6v1MmXPV5wcVbT24S7FDcrBAIize6wkDSvqEJs/viewer?f=0)

### Investigate the following avenues:

1. How well does diff commit search work on 1 repo with 1m commits with git maintenance?
2. Run "git maintenance" alongside gitserver or integrated in its janitor jobs infrastructure in order to speed up git operations
3. Enable gitserver commit-graph building for sufficiently large repos (for blame / file history on monorepos)

### Timebox
5 days?

### Related issues

- [Search timeout on diff search with 230k+ commits](https://github.com/sourcegraph/customer/issues/552)

**Comment by camdencheek** [comment]
FYI, I explored git maintenance a bit when doing the commit/diff search rewrite, and found it made no observable difference for diff search. Generating the diffs is still far and away the most expensive part.

**Comment by keegancsmith** [comment]
@stefanhengl I think this is done?

**Comment by keegancsmith** [comment]
I'm closing this out. @stefanhengl explored and implemented this ages ago. He has had some follow-up work which he has been tracking in https://github.com/sourcegraph/sourcegraph/issues/33353
