### ISSUE TITLE
Percy failing on changes that do not make any visual changes

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#2704]
I have noticed on three PRs now that Percy fails on various PRs that do not make any visual changes.

- In one case, it told me the screenshot was new and there was no baseline. I hit accept. The change was only a backend change, with no visual changes.
- In another, I edited our docs and Percy failed showing this corrupt image: https://github.com/sourcegraph/sourcegraph/pull/2701

![image](https://user-images.githubusercontent.com/3173176/54234880-45b53a00-44cd-11e9-9140-423ca88ea9c3.png)

Same thing in:

- (docs only change, corrupt image again) https://github.com/sourcegraph/sourcegraph/pull/2702

It will also probably happen in https://github.com/sourcegraph/sourcegraph/pull/2703

**Comment by chrismwendt** [comment]
- There **is a diff**: the suggested filters changed (not sure why)
- The search response time will change, so we need to pin that somehow
- That's not a corrupt image, that's Percy showing you the diff highlighted in red. You can click on the image to toggle between the actual image and diff mode.

**Comment by francisschmaltz** [comment]
Seems like we just need to change the threshold for requiring approval, or areas that are ignored

**Comment by slimsag** [comment]
Ah, my bad about thinking the image was corrupt. Still, given I didn't modify anything that could affect this, it should be treated the same as a flaky test then most likely.

**Comment by chrismwendt** [comment]
@francisschmaltz How do you change the threshold? Is that in the Percy docs somewhere? And wouldn't increasing the threshold allow some legitimate regressions through?

@slimsag Yes, this is a flaky test. I'll disable it for now.
