### ISSUE TITLE
SPIKE: Monorepo sharding

### ISSUE THREAD

**Issue by jjeffwarner** [sourcegraph/sourcegraph#27049]
For Q4 OKR for large mono-repos. [From Jamboard](https://jamboard.google.com/d/1-rNnz6v1MmXPV5wcVbT24S7FDcrBAIize6wkDSvqEJs/viewer?f=0)

### Investigate the following avenues:

1. Monorepo sharding: split monorepos into shards to allow parallelization of git operations / searches
2. Sharding for unindexed search
3. Shard by file path inside of mono repo

Potentially linked to #21855

### Timebox
5 days?

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket,  please let us how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
