### ISSUE TITLE
SPIKE: Ranking and context in monorepos

### ISSUE THREAD

**Issue by jjeffwarner** [sourcegraph/sourcegraph#27046]
For Q4 OKR for large mono-repos. [From Jamboard](https://jamboard.google.com/d/1-rNnz6v1MmXPV5wcVbT24S7FDcrBAIize6wkDSvqEJs/viewer?f=0)

### Investigate the following avenues:

1. Ranking in monorepos
2. Search contexts can specify file paths
3. Do we need to think about search contexts within monorepos?

### Timebox
5 days?

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket,  please let us how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
