### ISSUE TITLE
Exclude repo filter doesn't exclude private repos

### ISSUE THREAD

**Issue by gabtorre** [sourcegraph/sourcegraph#27044]
- **Sourcegraph version:** 3.33.0 
- **Platform information:** Kubernetes, Docker Compose

#### Steps to reproduce:

1. Run a query with the `-repo:` filter to exclude a private repo

#### Expected behavior:
The private repo is excluded from the results.

#### Actual behavior:
The private repo is included in the results. 
__

The `-repo:` filter seems to exclude public repos as intended on 3.33.0.

**Comment by lguychard** [comment]
@keegancsmith coudl this be a regression introduced by https://github.com/sourcegraph/sourcegraph/pull/25556?
