### ISSUE TITLE
Adding additional code hosting sites

### ISSUE THREAD

**Issue by jjeffwarner** [sourcegraph/sourcegraph#27050]
For Q4 stretch OKR for additional hosting sites. [From Jamboard](https://jamboard.google.com/d/1-rNnz6v1MmXPV5wcVbT24S7FDcrBAIize6wkDSvqEJs/viewer?f=0)

### Investigate the following avenues:

1. Determine which hosting sites would provide the best bang for the buck
2. https://github.com/sourcegraph/sourcegraph/issues/28936
3. Ubuntu - https://code.launchpad.net/ubuntu
5. Launchpad.net - https://launchpad.net/+apidoc/

[Link to Q4 document OKR Document](https://docs.google.com/document/d/1y1KVBMiVP5hZgEelF2iHM4AYVujq2tlU_bXDDTa8GdU/edit)

[Link to proposed sites](https://docs.google.com/spreadsheets/d/1jM7qpMbGCVDF79pTYmpU1kDEZDmbmhC88Y4nNWi3k3Q/edit#gid=0)

### For consideration
1. https://github.com/sourcegraph/sourcegraph/issues/28291 - will have to contribute to their code base.

### Completed
1. Fedora has been completed with #28028 and #27961
2. https://github.com/sourcegraph/sourcegraph/issues/28683 - This does not include all NPM repos, only repos that have been indexed by Code Intel. Zoekt will automatically include any additional repos that are indexed by Code Intel.
3. Maven - in the same way that NPM is handled, any repo indexed by Code Intel will be included in Zoekt. 
4. Tooling is in place so as additional repos are indexed by Code Intel, a one line change will include the new repos in Zoekt indexing. Proposed libraries include PyPi, RubyGems, Crates and NuGet.

**Comment by keegancsmith** [comment]
I think we decided on a different approach here, mainly motivated by the work @tsenart is doing on dependency search. @jjeffwarner I think we should close this out?

**Comment by jjeffwarner** [comment]
Yep, thanks.
