### ISSUE TITLE
Making docs changes is a pain

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#2706]
When I noticed that something in our `doc/` folder is out of date, has a typo, etc. I am hesitant to update it because the process is now very tedious:

1. Click `Edit this file` button
2. Make the edit
3. Specify commit title
    - At this point, I used to be able to _commit to master_. (We acknowledged that this would change in our sync and that updating docs would be harder when we decided to do this.)
5. Choose a branch name (I am OCD and want all of my branches to start with `sg/` so I can list them easier in the future).
6. Be uncertain if I need to have this change reviewed or not. I guess I am not required to, but should I? I am forbidden from committing it directly, after all.
7. Wait several minutes for required checks to pass: CL bot, buildkite (~10 minutes), Percy
8. Finally merge my change

Random ideas:

- Allow committing directly to master, but develop a strong culture against it unless it is a docs change.
- Come up with a system to auto merge PRs once checks pass (time consuming).
- Reduce the time it takes for CI to run (helps, but even if CI takes 30s steps 5-8 still suck).
- Move docs to a different repository (bad for other reasons).

**Comment by sqs** [comment]
I know this is not documented, and I’m not sure how to document it, but you don’t need approval on all docs changes.

**Comment by sqs** [comment]
If you trim the steps run in CI for doc changes, be sure to preserve running `docsite check` (not just prettier).

**Comment by chrismwendt** [comment]
I'm skipping non-doc checks for docs-only changes (for PRs only) in https://github.com/sourcegraph/sourcegraph/pull/2721, which will make CI take 2min (see sample build https://buildkite.com/sourcegraph/sourcegraph/builds/29318#5bad3b32-59a4-4f03-91e7-93ad70eb8caa).

**Comment by ryan-blunden** [comment]
Fixed by #2721
