### ISSUE TITLE
ci: report pipeline generation failures on Sentry so we are immediately notified

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#27088]
As we are providing the CI as a service for the engineers, we should monitor errors in our service like in any other product. 

Typically those errors involve pipeline generation failures or logs uploading failures. By opening a Sentry ticket and having the notifications in `#dev-experience` we could react faster to such issues. 

1. Create a Sentry project for the CI
2. Wrap error reporting so we can use it in our shell scripts
3. Plug it on the parts of the scripts that we directly are responsible for.

**Comment by burmudar** [comment]
This is almost done - just need to implement some lib/log library changes
