### ISSUE TITLE
User invitations

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#27101]
User invitations will allow users who have signed up for Sourcegraph to invite their friends and colleagues to the service. This feature can be placed in multiple locations within the application to maximize the chance of users inviting others to the application. 

There are two types of invitation features:

* A form that allows users to manually add email addresses, then send invitations via email
* A feature that extracts collaborators email addresses from a user's repositories and allows the user to invite those users to Sourcegraph

More information [in this RFC](https://docs.google.com/document/d/1Nsg6wneYlOQWzVXeQjS93zdd-MewGyv4gARB6_PHQOo/edit?usp=drive_web&ouid=107037782400977645523).

## Acquisition
These features can be included in multiple flows within the application: 

* After (or on) the post sign-up repositories saved stage
* On the homepage
* After the repositories selection process in the repositories settings page
* In the team creation form

Note:
_These features should be considered independent from teams functionality because we need to allow individual users to invite collaborators outside of a team context. That said, they should be developed in such a way as to also empower the team functionality 

## What metrics will signal this effort is successful?
* The experiment produces a viral coefficient greater than 1.

**Comment by slimsag** [comment]
> A feature that extracts collaborators email addresses from a user's repositories and allows the user to invite those users to Sourcegraph

FYI this is fairly involved, we do not have any really good way to do processing on repositories in the background nor do we store this information in a quick-to-retrieve format so this really involves building a system which runs in the background, scans repositories, and stores that data someone (e.g. a new DB table)

**Comment by slimsag** [comment]
> A form that allows users to manually add email addresses, then send invitations via email

For Sourcegraph.com, note there are a fair number of security implications here.

* We probably shouldn't allow the user to type an arbitrary message in the invitation email.
* We should probably limit the number of invitations that can be sent in a given timeframe (how many, though?)
* We should require the user's own email address be verified prior to allowing them to send invitations.

Any other thoughts around this @sourcegraph/security?

For on-prem instances, I should also call out that most customers do not have email sending set up - so this feature will likely not work there in practice in most cases. We don't really have any good UX that explains to admins they should set this up, either.

**Comment by andreeleuterio** [comment]
➕ on @slimsag's points. For the form option my suggestion is to rate limit it like we do for account sign-ups in dotcom: max of 5 requests/min. These situations are similar since we are trying to reduce spamming emails.

We should also provide an anti-abuse mechanism for people to "unsubscribe" from being invited.

**Comment by bcreager** [comment]
could we break this into two tickets, one for each workflow?

**Comment by rrhyne** [comment]
Probably. Off the top of my head, there is the core invite sending code, an
invite user UI element, and the recommended invites functionality.

**Comment by rrhyne** [comment]
> FYI this is fairly involved, we do not have any really good way to do processing on repositories in the background nor do we store this information in a quick-to-retrieve format so this really involves building a system which runs in the background, scans repositories, and stores that data someone (e.g. a new DB table)

@slimsag I was hoping we could leverage this on a repo by repo basis for the repositories a user has added to Sourcegraph:

https://docs.github.com/en/rest/reference/repos#collaborators

Is that feasible, and would it reduce workload?

**Comment by slimsag** [comment]
(we chatted over a call and sorted most details out)
