### ISSUE TITLE
Specific Search Example working on Cloud but not in CLI

### ISSUE THREAD

**Issue by jasonhawkharris** [sourcegraph/sourcegraph#27103]
- **Sourcegraph version:**   ​113937_2021-10-27_672a57a 
- **Platform information:**  Sourcegraph Cloud

#### Steps to reproduce:

1. Open terminal window
2. `src search 'file:^LICENSE$ content:"MIT License" count:all'` - note timeout
3. `src search 'file:^LICENSE$ content:"MIT License" count:210000'` - note timeout
4. Open sourcegraph.com
5. search `file:^LICENSE$ content:"MIT License" count:all` - note NO timeout
6. search `file:^LICENSE$ content:"MIT License" count:210000' - note NO timeout

#### Expected behavior:
The expected behavior is that this would work in the CLI as it does on sourcegraph.com

#### Actual behavior:
sourcegraph.com pulls the results correctly while CLI times out

If would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are not [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

**Comment by lguychard** [comment]
Hi @jasonhawkharris,

You should [pass the `-stream` flag](https://docs.sourcegraph.com/code_search/how-to/exhaustive#large-result-sets) when running exhaustive searches with the src cli. Otherwise, the CLI hits the GraphQL API, which cannot efficiently service exhaustive searches.
