### ISSUE TITLE
Investigate intermittent gitserver CPU throttling

### ISSUE THREAD

**Issue by indradhanush** [sourcegraph/sourcegraph#27122]
We recently [doubled](https://github.com/sourcegraph/deploy-sourcegraph-dot-com/pull/14833) gitserver CPU on dotcom. While this has led to an overall reduction in CPU throttling to <1%, we still see occasional peaks of 15-20%. We should investigate what is causing this.

https://sourcegraph.com/-/debug/grafana/d/gitserver/git-server?viewPanel=100010&orgId=1&var-alert_level=All&var-shard=All&from=1635843223000&to=1636188823000

When the investigation is complete and a fix is rolled out, we should verify the fix and then proceed to merge #29317 after making necessary changes to the PR which will consequently fix #26925.

![image](https://user-images.githubusercontent.com/2682729/140484366-beeddc0f-1d8b-4fc5-9454-2cb782bafd81.png)

**Comment by indradhanush** [comment]
@mollylogue and I have started brainstorming on this on the side. We're going to continue looking into this but since this isn't high on the list of priorities, progress is expected to be slow.

**Comment by indradhanush** [comment]
Started noting down thoughts here: https://github.com/sourcegraph/repo-management-scratchpad/blob/main/2022.md#2022-01-25-tuesday

**Comment by eseliger** [comment]
We have very spiky load and occasionally run maintenance on gigantic repos, I think load spikes are expected. Let's close this for now.
