### ISSUE TITLE
User settings textbox unusable on firefox

### ISSUE THREAD

**Issue by drolando** [sourcegraph/sourcegraph#2713]
- **Sourcegraph version:** 3.1.1
- **Platform information:** macos 10.14.3, firefox  65.0.1
#### Steps to reproduce:
On firefox I'm unable to edit (or view) my user settings since the textbox under `users/drolando/settings` is too small. See screenshot in "actual behavior".
Opening the page in an incognito window didn't help.

I don't see any error in the JS console.

#### Expected behavior:
I can see a reasonably sized testbox and my current settings.
#### Actual behavior:
https://www.dropbox.com/s/vh5zzmnr1ajk6sj/Screenshot%202019-03-12%2017.33.13.png?dl=0

**Comment by nicksnyder** [comment]
Thanks for filing! This is a duplicate of https://github.com/sourcegraph/sourcegraph/issues/1943
