### ISSUE TITLE
Explicitly specified repository permissions

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#2715]
A customer wants to use 2 sets of repositories on Sourcegraph:

- Some repositories that all users can view
- Some repositories ("restricted repositories") that only a specific, rarely changing set of users can view
  - The restricted repositories all share the same repository name prefix, which is guaranteed to never be a prefix of any non-restricted repository

The restricted repositories are on Gitolite, which has its own simple ACL config, but there is no easy way to transmit Gitolite ACL info to Sourcegraph.

Customer context: See the ["Want to enable Gitolite ACLs" bullet point on Slack](https://sourcegraph.slack.com/archives/C0B2RU51Q/p1552408309135700) cc @beyang 	@aisbaa

Other people interested: @P3GLEG

---

The (initial) proposal is to support explicitly specified repository permissions in site config or external service config, such as:

```
"permissions": {
  // Pattern for non-restricted repos:
  "^code\\.acmecorp\\.internal/": [
    "allow": "all"
  },
  // Pattern for restricted repos:
  "^topsecretproject\\.acmecorp.internal/': {
    "allow": [ "alice", "bob" ] // users or orgs who can view restricted repos
  },
}
```

This proposal is tentative, and @tsenart 	and @keegancsmith 	own deciding this (as it gets closer to being prioritized). We can get more customer context as needed.

Customers (not exhaustive):

- https://app.hubspot.com/contacts/2762526/company/464956351 (said they actually didn't need this initially)
- https://app.hubspot.com/contacts/2762526/company/693777200

**Comment by tsenart** [comment]
Is this in the 3.4 milestone intentionally or should it be in Backlog?

**Comment by sqs** [comment]
This was in 3.4 intentionally to ensure we discussed prioritizing it then, but 4 hours ago I just heard from one customer that this is actually unnecessary. I’m going to move it out of 3.4 as a result.

**Comment by keegancsmith** [comment]
@sqs given RFC 45 is this proposal still relevant?

**Comment by tsenart** [comment]
Ping @sqs ^

**Comment by sqs** [comment]
[RFC 40](https://docs.google.com/document/d/167WV_rhBg3oj0yw9fHwUMlB-8BR3ktk2FSsKiUQo55Y/edit) solves this. Closing.
