### ISSUE TITLE
Question on git push options when applying batch change spec

### ISSUE THREAD

**Issue by amberfurbush0317** [sourcegraph/sourcegraph#27150]
#### Question description###

Is it possible to somehow specify git push options when applying batch change spec? 

Specifically in spec yaml itself, using src cli or in web UI? 

#####Question####

Looking to see if options like `merge_request.remove_source_branch` or `merge_request.merge_when_pipeline_succeeds`. are support or can be used via the spec yaml itself, using src cli or in web UI?
 
I wasn’t able to find anything leading me to believe we support that functionality. I would imagine something like that living in the spec file as a **property/key.**

#### Additional context

I know GitLab supports similar git cli  push option such as git cli `git push -o merge_request.create -o merge_request.merge_when_pipeline_succeeds -o merge_request.remove_source_branch` as abstracted option in the spec.

**Comment by chrispine** [comment]
Hello @amberfurbush0317! Was it intentional that this ticket was moved to our Done column, but is still open?
