### ISSUE TITLE
Sign-up flow alterations

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#27156]
Marketing is altering the sign-up flow to better support self-hosted installations alongside cloud sign-ups based on user requirements.

The ask from us will be:
* Change the sign-up button to "Get started"
* Change the route to the new https://about.sourcegraph.com/get-started link (with a UTM parameter to aid tracking)
* Change other locations in the product (tour, etc) that link to sign-up to read "Get started" and the proper route

The timeframe for this will be after marketing makes these updates. It will happen either in a few days, or after the 27th of January, depending on the content platform team's development timeline.

**Comment by muratsu** [comment]
@rrhyne to update the details

**Comment by rrhyne** [comment]
Updated!

**Comment by philipp-spiess** [comment]
It seems like instead of altering the sign up flow the plan is to fork it:

- https://sourcegraph.slack.com/archives/C02HL0RNTGV/p1642098053063700
- https://sourcegraph.slack.com/archives/C02HL0RNTGV/p1642112686080400

@rrhyne I think this task can be closed?

**Comment by rrhyne** [comment]
No, there are two sites at work here. Fabiana's comment is regarding about.sourcegraph.com. We will need to make the changes above to sourcegraph.com.

**Comment by philipp-spiess** [comment]
@rrhyne Here are all the in-product links to `/sign-up` that I could find with various search queries:

| Code pointer | Screenshot  |
|---|---|
|[ExtensionRegistry.tsx](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/extensions/ExtensionRegistry.tsx?L361:52&subtree=true)|![Extensions](https://user-images.githubusercontent.com/458591/150560750-3c56fe56-cbb8-4bd5-88ea-3e41572becc6.png)|
|[OnboardingTour.tsx](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/onboarding-tour/OnboardingTour.tsx?L181:29&subtree=true)||
|[ExtensionAreaHeader.tsx](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/extensions/extension/ExtensionAreaHeader.tsx?L117:60&subtree=true)|![Screenshot 2022-01-21 at 16 52 29](https://user-images.githubusercontent.com/458591/150560950-5e6b141d-678b-4b68-b99a-01a3faabffb9.png)|
|[GlobalNavbar.tsx](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/nav/GlobalNavbar.tsx?L310:75&subtree=true)|![Screenshot 2022-01-21 at 16 53 34](https://user-images.githubusercontent.com/458591/150561053-5dfffc19-6977-453a-9ae2-61362b679297.png)|
|[SearchNotebooksListPage.tsx](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/search/notebook/listPage/SearchNotebooksListPage.tsx?L261:22&subtree=true)|![Notebooks](https://user-images.githubusercontent.com/458591/150561121-7614b768-593f-4634-8796-e529380cd0e5.png)|
|[ProductSubscriptionForm.tsx](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/enterprise/user/productSubscriptions/ProductSubscriptionForm.tsx?L222:42&subtree=true)|![New subscription](https://user-images.githubusercontent.com/458591/150561182-b54c9797-176f-4635-8401-7b62f7e9c7e5.png)|
|[StreamingSearchResults.tsx](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/search/results/StreamingSearchResults.tsx?L22)|![Screenshot 2022-01-21 at 16 58 14](https://user-images.githubusercontent.com/458591/150561297-b4d702b5-9454-4efd-827f-1a70492e2cdb.png)|
|[ButtonDropdownCta.tsx](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/search/results/ButtonDropdownCta.tsx?L81:26&subtree=true)|![Screenshot 2022-01-21 at 17 00 40](https://user-images.githubusercontent.com/458591/150561362-ab09fa36-3c69-4bad-b10f-557474d88080.png)|
|[SearchContextCtaPrompt.tsx](https://github.com/sourcegraph/sourcegraph/blob/main/client/search-ui/src/input/SearchContextCtaPrompt.tsx#L43)|![Choose search context](https://user-images.githubusercontent.com/458591/150561438-5789a71e-3ce2-4f4b-b985-27333aff7543.png)|
|[SignInPage.tsx](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/auth/SignInPage.tsx?L94:56&subtree=true)|![Sign in to Sourcegraph Cloud](https://user-images.githubusercontent.com/458591/150561504-09c4fe6c-ad11-4ab8-b7c8-ebb8a6e78672.png)|
|[CodeMonitoringSignUpLink.tsx](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/enterprise/code-monitoring/CodeMonitoringSignUpLink.tsx?L18:18)|![Proactively monitor changes to your codebase](https://user-images.githubusercontent.com/458591/150561551-d78b31ea-0d6d-4730-9b50-13f173eaf91a.png)|

Expect maybe the link on the Sign In page, I'd suggest we replace all of them with the new deployment-agnostic getting started context. WDYT?

**Comment by rrhyne** [comment]
Thanks @philipp-spiess... I love the formatting above and thanks for the screenshots!!!!

Code pointer | Note
-- | --
ExtensionRegistry.tsx |  Change link text to: "Get started", route to https://about.sourcegraph.com/get-started
OnboardingTour.tsx |  This is from the recent work with the getting started widget.  The current button text is "Sign up for Cloud". It should be "Get started". This also requires removing the button below this one which has the text "Install Sourcegraph locally". 
ExtensionAreaHeader.tsx |   _Same as ExtensionRegistry.tsx_
GlobalNavbar.tsx |   _Same as ExtensionRegistry.tsx_
SearchNotebooksListPage.tsx |   Change link text to: "Get started creating notebooks", route to https://about.sourcegraph.com/get-started
ProductSubscriptionForm.tsx |  No action, I'm not sure how an unauthed user could access this page, so we'll leave it.
StreamingSearchResults.tsx |  Change banner text to: "Get started searching your public and private repositories", route to  to https://about.sourcegraph.com/get-started. NOTE: David is currently working on this, so his PR and your's might conflict.
ButtonDropdownCta.tsx |  _Same as ExtensionRegistry.tsx_
SearchContextCtaPrompt.tsx |  _Same as ExtensionRegistry.tsx_
SignInPage.tsx |  No action
CodeMonitoringSignUpLink.tsx |  Change button text to: "Get started with code monitors", route to https://about.sourcegraph.com/get-started

**Comment by philipp-spiess** [comment]
Put up a draft PR (since we don't want to merge this until the new `/get-started` is ready here: https://github.com/sourcegraph/sourcegraph/pull/30098

I have some ideas on how to further improve the experience:

- Right now, we add a `returnTo` link to a lot of the sign up flows I noticed. This way, after signing up, a user is supposedly returned to where they left off. Looking at https://github.com/sourcegraph/about/pull/5083 I don't think we do forward that yet in case the sign up flow results in a cloud sign up.
- I’m a bit concerned about the case where a sign up flow starts from a non-`sourcegraph.com` domain and is linked to `sourcegraph.com`. This is definitely unhandy if you're testing things locally (where the domain to link back should be `https://sourcegraph.test:3443/`)  but what if on-premise installations also show some of these sign up buttons and some customers set it up in a way that their users need to sign up on their on premise instance? Is this a valid concern? If so, should we gate the changes and only make them for our dot com deployment?

**Comment by rrhyne** [comment]
Should on-prem installations display sign-up buttons? I thought those users were invited by the admin? I could be wrong though!

How would the returnTo link work with the sign-up flow? See this PR to view the workflow a user must go through after signing up. https://github.com/sourcegraph/sourcegraph/pull/29996#issuecomment-1019892346

We use UTM parameters to track actions on our sites that use Google Analytics like docs.sourcegraph.com and about.sourcegraph.com. With all the links here, we can use Amplitude to create event funnels for flows like Extensions to Signup to see how effective these items are.

**Comment by philipp-spiess** [comment]
> Should on-prem installations display sign-up buttons? I thought those users were invited by the admin? I could be wrong though!

I checked and you are right. On-prem instances show _nothing_ if a user is not logged in _except_ the sign in page. Since that still links to the previous sign up page I don't foresee any issues. 

> How would the returnTo link work with the sign-up flow? See this PR to view the workflow a user must go through after signing up. [#29996 (comment)](https://github.com/sourcegraph/sourcegraph/pull/29996#issuecomment-1019892346)

I guess with the welcome page this is irrelevant, yeah. Maybe just an artifact from an ancient time 😛  Should I remove existing `returnTo` props then?

> We use UTM parameters to track actions on our sites that use Google Analytics like docs.sourcegraph.com and about.sourcegraph.com. With all the links here, we can use Amplitude to create event funnels for flows like Extensions to Signup to see how effective these items are.

Okay so with our Amplitude setup we can already join events from `sourcegraph.com` and `about.sourcegraph.com`? Great!

**Comment by rrhyne** [comment]
Philipp
> Right now, we add a returnTo link to a lot of the sign up flows I noticed. This way, after signing up, a user is supposedly returned to where they left off. Looking at add cloud section v1.1 about#5083 I don't think we do forward that yet in case the sign up flow results in a cloud sign up.

Rob
> How would the returnTo link work with the sign-up flow? See this PR to view the workflow a user must go through after signing up. #29996 (comment)

Philipp
I guess with the welcome page this is irrelevant, yeah. Maybe just an artifact from an ancient time 😛 Should I remove existing returnTo props then?

@quinnkeast could you have a look at the reconstructed thread above and provide some advice?

**Comment by quinnkeast** [comment]
Returning to a path makes a lot of sense when the user's signing up in response to a prompted related to a moment in time (e.g. signing up to comment on a thread—returning to that thread to comment continues that flow). I don't believe we really have any of those moments in place in the product right now, where a user will be interrupting their flow to sign up, rather than signing up as the start of a new flow. @rrhyne please correct me if I'm forgetting a moment that we should preserve.

I think in most cases, we'll want Cloud users to proceed to a team-specific post-signup flow or first user experience to learn how to use the product.

**Comment by philipp-spiess** [comment]
> on-prem users may in fact be asked to signup when doing things like viewing a link to code.

This flow should be untouched by our changes though, as on-prem instances show the `/sign-in` view if no user is signed in. This _may_ contain a link to `/sign-up` but we're not changing links from the sign in page anyway.

**Comment by rrhyne** [comment]
Great!
