### ISSUE TITLE
Too many matching repositories error should display information about how to filter repos only

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#27152]
I recently received the following error for [this search](https://sourcegraph.com/search?q=context:global+type:commit+//todo+javascript&patternType=literal):

```
Too many matching repositories for commit search to handle
Commit search can currently only handle searching across 50 repositories at a time. Try using the "repo:" filter to narrow down which repositories to search, or using 'after:"1 week ago"'.
```

The content on the no results page that would have helped me resolve it was burried. As this is a very common error, I think we should cater to it specially. 

Limit the content shown to the section of the common problems describing how to filter to repos or groups of repos. 

[Figma](https://www.figma.com/file/E8fcpTxwiqVf1fLxNR6jQJ/No-results%3A-Improving-search-messages?node-id=296%3A9488)

![image](https://user-images.githubusercontent.com/539268/140576999-d39f55ce-132a-4c43-9378-a7d39b05718a.png)

**Comment by lguychard** [comment]
[diff/commit search no longer have repositories limits](https://sourcegraph.com/search?q=context:global+type:commit&patternType=lucky) :tada:
