### ISSUE TITLE
Create a JSON schema for generic webhooks

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#27155]
This is the schema for the JSON that is sent when calling generic webhooks. 

It probably should contain:
- Name of the monitor
- Link to the monitor
- Type of trigger (We currently only have one trigger, new search results, but more triggers may come eventually)
- Details from the trigger (For new search results, the details could be the number of search results and the link to the search results.)

@limitedmage putting our Code monitor payload doc [here](https://docs.google.com/document/d/1iqpCma3Em6fj4Mkv6PRo-4lszIMMxKTW45PzXqRBDEo/edit?usp=sharing) just for reference. Let me know if more discussion is required, the doc isn't finalized so we may need to revive the conversation.  cc @camdencheek.

**Comment by camdencheek** [comment]
> is there some overlap between this and https://github.com/sourcegraph/sourcegraph/issues/31579?

Yes. I think we should close the other one as a dupe.
