### ISSUE TITLE
Design for code monitoring history/events pages

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#27167]

**Comment by marisak** [comment]
Very preliminary thinking [here](https://www.figma.com/file/FlsqgXqE2TPmrGDEw9uFtZ/Code-monitors-improvements?node-id=1128%3A212), will update when there's more to comment on, along with what questions I have/feedback I'm requesting! (You can still comment, it just might not be very fulfilling :) )

**Comment by marisak** [comment]
Updated designs in [Figma: Code monitors improvements](https://www.figma.com/file/FlsqgXqE2TPmrGDEw9uFtZ/Code-monitors-improvements?node-id=1155%3A771). I'd appreciate some responses to the feedback cards!

**Comment by marisak** [comment]
Additional design updates in the [wireframes page](https://www.figma.com/file/FlsqgXqE2TPmrGDEw9uFtZ/Code-monitors-improvements?node-id=1298%3A5520) of the code monitors improvements Figma.

**Comment by marisak** [comment]
Designs can be found [here](https://www.figma.com/file/FlsqgXqE2TPmrGDEw9uFtZ/Code-monitors-improvements?node-id=1637%3A9685), closing this issue.
