### ISSUE TITLE
Design for code monitor library/samples

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#27169]

**Comment by marisak** [comment]
Very preliminary thinking [here](https://www.figma.com/file/FlsqgXqE2TPmrGDEw9uFtZ/Code-monitors-improvements?node-id=1128%3A212), will update when there's more to comment on, along with what questions I have/feedback I'm requesting! (You can still comment, it just might not be very fulfilling :) )

**Comment by marisak** [comment]
Additional in-progress work in [Figma: Code monitors improvements](https://www.figma.com/file/FlsqgXqE2TPmrGDEw9uFtZ/Code-monitors-improvements?node-id=1128%3A220)!

**Comment by limitedmage** [comment]
Closing as complete!
