### ISSUE TITLE
Getting started checklist for visitors

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#27177]
A getting started checklist for new visitors would help users experience the most unique and compelling features of Sourcegraph:

* Code search use cases
  * Commit search
  * Diff search
  * Symbol search
* Code intel
  * Find references
  * Go to definitions
* Extensions and tools that help users get more out of Sourcegraph
  * The browser extension
  * IDE Extensions
  
  
### Working Figma file here:
  https://www.figma.com/file/uq7yt5ETrrXiHjcb6dfHSi/Getting-started-checklist?node-id=0%3A1
  
### Product document:
https://docs.google.com/document/d/1aD9mEoqaYyIjMTdykNlv6OwCoEBeGwKd7dQ4Gtldg_c/edit#heading=h.g0gjwch98szj

Related https://github.com/sourcegraph/sourcegraph/issues/30258

**Comment by bcreager** [comment]
@rrhyne do we have a design for this page yet?

**Comment by rrhyne** [comment]
Bill, I've updated the issue with a link to a Figma file. That said, we need to work with an engineer to determine what is feasible. I don't want to get into a situation where I'm designing a lot of work that engineers aren't involved in from the outset.

**Comment by rrhyne** [comment]
Product document for this feature:

https://docs.google.com/document/d/1aD9mEoqaYyIjMTdykNlv6OwCoEBeGwKd7dQ4Gtldg_c/edit#heading=h.g0gjwch98szj
