### ISSUE TITLE
Cannot access locolhot web server

### ISSUE THREAD

**Issue by darzok0914** [sourcegraph/sourcegraph#27183]
- **Sourcegraph version:** 
I followed the instructions from 

https://docs.sourcegraph.com/#quick-install

And run

docker run -d --publish 7080:7080 --publish 127.0.0.1:3370:3370 --rm --volume ~/.sourcegraph/config:/etc/sourcegraph --volume ~/.sourcegraph/data:/var/opt/sourcegraph sourcegraph/server:3.33.0

- **Platform information:** 
Ubuntu 18.04 and 20.04

#### Steps to reproduce:

1.run the docker image 
2.once docker container is running, open web browser and try to access the webpage on local host ip address

#### Expected behavior:
I would expect to reach sourcegraph web page
#### Actual behavior:
Web page unreachable

**Comment by kevinwojo** [comment]
I was not able to reproduce this issue. Navigating to http://localhost:7080 should work. 

<img width="1721" alt="image" src="https://user-images.githubusercontent.com/9081680/153407617-bfd848cb-0f0e-465b-855c-d97d3807470c.png">

Another troubleshooting step would be to remove data in your `~/.sourcegraph/data` volume as it may have become corrupted.

**Comment by kevinwojo** [comment]
I believe this issue can be closed. Feel free to reopen if you are still experiencing difficulties.
