### ISSUE TITLE
Find implementation doesn't work on BExt

### ISSUE THREAD

**Issue by muratsu** [sourcegraph/sourcegraph#27239]
#### Steps to reproduce:

1. Go to a random code page on github
2. Hover on a variable and click on "Find Implementations"

#### Expected behavior:
Behave similarly to find references & open sourcegraph.com

#### Actual behavior:
Navigates to an invalid github url

![image](https://user-images.githubusercontent.com/1308560/140816010-8c00afea-b18d-42c2-ad4e-71c53372c631.png)

**Comment by chrismwendt** [comment]
Thanks for filing, this is definitely a bug. I'm looking into how to use an absolute URL to the Sourcegraph instance for find-implementations if you're on a code host.

**Comment by chrismwendt** [comment]
I haven't figured out a way to enable the "Find implementations" button on Sourcegraph and not in the browser extension, so I'm disabling implementations altogether until the next browser extension release on Nov 22.

**Comment by chrismwendt** [comment]
I reenabled find-implementations when you're on Sourcegraph instances (not on the browser extension) in https://github.com/sourcegraph/code-intel-extensions/pull/721

I'm still leaving this issue open until the next browser extension release on Nov 22.
