### ISSUE TITLE
Replace global classes with `data-testid` in web end-to-end tests

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#27265]
## Problem

We use global CSS classes in selectors in end-to-end tests. It is not robust because tests are tied to the class names that might change. This fact limits our detracts our refactoring speed and often causes bugs.

## Success criteria

Global CSS classes **except for `.test-*`** used in end-to-end tests are replaced with `data-testid` attributes.
Relevant file: `client/web/src/end-to-end/end-to-end.test.ts`.

## Estimate

- Pull requests with ~450 lines changed should take 1 hour at maximum. Ping the reviewer in the spec pull request if time-consuming changes are required.
- Split the work into multiple pull requests if the total diff is bigger than 450 lines of code.

**Comment by gitstart-sourcegraph** [comment]
Hello @valerybugakov ,
After going through the we end-to-end test file `client/web/src/end-to-end/end-to-end.test.ts`, we were unable to find any global className usage within the file, that could be converted to `data-testid`. Could you please help confirm this,

**Comment by valerybugakov** [comment]
@gitstart-sourcegraph, I cannot find any global classNames either. Closing the issue.
