### ISSUE TITLE
search: re-introduce "searchable" repositories counts and GraphQL fields

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#27274]
#26995 introduced paginated repository resolution, which was necessary to address some scalability challenges. That changes the semantics of the UI's repository count as well as related GraphQL fields from "searchable" to "searched" repositories.

On sourcegraph.com, counting the full repo table takes about 3s, and adds a lot of load on the database. Implementing this efficiently will require some form of caching, potentially split between public repos and private.

https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+repositoriesCount&patternType=literal

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket,  please let us how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
