### ISSUE TITLE
Migrate remaining `react-test-renderer` tests to `@testing-library/react`

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#27280]
### Motivation
We want to use a single React testing library, we have a tracking issue to address this https://github.com/sourcegraph/sourcegraph/issues/24986

### Implementation

1. Find all remaining usage of `react-test-renderer`, here's a [Sourcegraph search result](https://sourcegraph.com/search?q=context:global+repo:github.com/sourcegraph/sourcegraph+%27react-test-renderer%27&patternType=literal)
2. Convert these test files to use `@testing-library/react`.
2.1. Feel free to use [this migration PR](https://github.com/sourcegraph/sourcegraph/pull/27273) as an example.
2.2. To keep this migration light, we should aim to replicate the tests like-for-like. That means converting any `react-test-renderer` snapshots to `@testing-library/react` snapshots, and converting any behavior that tests specific elements or props to an equivalent test in `@testing-library/react`. For the latter example, some of the old tests might call props directly (e.g. `props().onClick()`), in testing-library, we have to do this through the DOM (e.g. find the element and call `fireEvent` to trigger a click).
3. Remove `react-test-renderer` as a dependency!

Note: The remaining tests are not as trivial as in the reference PR, this is mainly because they access the DOM directly to test individual elements, we just need to convert these to `@testing-library/react` queries

**Estimate:** After the migration PR (#27273), there should be 7 test files remaining. These are all relatively small test files so we would expect this task to take around 2-3 hours in total

**Comment by umpox** [comment]
After the migration PR (https://github.com/sourcegraph/sourcegraph/pull/27273), there should be 7 test files remaining. These are all relatively small test files so we would expect this task to take around 2-3 hours in total

**Comment by gitstart-sourcegraph** [comment]
@umpox Could we use  [@testing-library/user-event](https://testing-library.com/docs/ecosystem-user-event/) to simulate browser interactions?

**Comment by umpox** [comment]
@gitstart-sourcegraph Yeah this would be a good approach. I believe we're using `fireEvent` in many places but `@testing-library/user-event` would be preferred!
