### ISSUE TITLE
Great Tool and Chrome Extension!

### ISSUE THREAD

**Issue by njohnson7** [sourcegraph/sourcegraph#2729]
I just wanted to let you know how much I appreciate your work on Sourcegraph! Being able to find references and look up function signatures almost directly from GitHub repos is very convenient and helpful.

**Comment by sqs** [comment]
Thank you! This means a lot to our team. ❤️

**Comment by ryan-blunden** [comment]
Thanks @njohnson7, that's awesome and good to hear! 

Curious as to what languages and projects you use Sourcegraph for? Private code, open source or both?

**Comment by njohnson7** [comment]
So far I've mainly been using Sourcegraph with projects I've done in Ruby and JavaScript. Do you have an extension for bash or any type of shell scripting? I'm a big fan of explainshell.com, which I believe uses the Language Server Protocol to parse various lines of shell code and display the relevant docs. I think it's even more helpful with shell code, since the syntax is harder to parse without being familiar with the specific commands being run and their flags.

**Comment by chrismwendt** [comment]
@njohnson7 explainshell is sweeet 😃 Last year, I integrated explainshell into the bash language server:

- Docker image https://hub.docker.com/r/sourcegraph/codeintel-bash
- Dockerfile https://github.com/sourcegraph/lsp-adapter/blob/8c9f26cef0978ba96cf1fdca7e24546a3cd5384a/dockerfiles/bash/Dockerfile#L33

As of [Sourcegraph 3.0](https://about.sourcegraph.com/blog/sourcegraph-3.0), new code navigation functionality comes from Sourcegraph extensions, and the [sourcegraph/shell](https://sourcegraph.com/extensions/sourcegraph/shell) extension doesn't have explainshell yet, but it would be great if it did!

**Comment by nicksnyder** [comment]
Thanks again for the feedback! I am going to go ahead and close this issue since there is no action to take here.
