### ISSUE TITLE
insights: disable constant settings file sync jobs if API is enabled

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#27306]
Using a feature flag to enable the new GraphQL API, disable any settings from being synced if the flag is enabled. To keep it simple, we can still execute the jobs and just exit early (do nothing) if the flag is set.

**Comment by CristinaBirkel** [comment]
Note: for the sake of time we can use an environment variable or something and handle this separately from how the front end is doing it. The only downside there will be that it's another step for customers if they want to turn this feature on/off.

**Comment by coury-clark** [comment]
The background sync job will now be disabled by default and will be enabled if the `ENABLE_CODE_INSIGHTS_SETTINGS_STORAGE` is set on the `worker` instance (and restarted).

**Comment by vovakulikov** [comment]
@coury-clark can you show me where is this (`ENABLE_CODE_INSIGHTS_SETTINGS_STORAGE `) flag/env-var defined?

**Comment by Joelkw** [comment]
This was merged into a feature branch and then merged
