### ISSUE TITLE
Search works well for large-scale monorepos

### ISSUE THREAD

**Issue by jjeffwarner** [sourcegraph/sourcegraph#27320]
This is our OKR for Q4, more complete it is: **Make Sourcegraph Search work well with large-scale monorepos (time to first result for unindexed search on monorepos larger than 200GB is < 10s and <2s for indexed, and time to indexing is always <30 minutes)**

We have broken this down into a group of stories so we can explore the various aspects of this problem. They are as follows:

- [ ] https://github.com/sourcegraph/sourcegraph/issues/27043
- [ ] https://github.com/sourcegraph/sourcegraph/issues/27041
- [ ] https://github.com/sourcegraph/sourcegraph/issues/27042
- [ ] https://github.com/sourcegraph/sourcegraph/issues/27049
- [ ] https://github.com/sourcegraph/sourcegraph/issues/27046

### Establish Baseline
- [x] https://github.com/sourcegraph/sourcegraph/issues/27492
- [x] https://github.com/sourcegraph/sourcegraph/issues/27493
- [x] https://github.com/sourcegraph/sourcegraph/issues/27045

### Fixes/Changes
- [x] https://github.com/sourcegraph/sourcegraph/issues/27045

**Comment by jjeffwarner** [comment]
Actual work for this OKR will commence next week with a focus on establishing a baseline metric and repo.

**Comment by jjeffwarner** [comment]
The [mono repo](https://sourcegraph.com/github.com/sgtest/megarepo) has been socialized with other teams so it can be included in their testing as well.

**Comment by jyavorska** [comment]
@jjeffwarner @lguychard what ended up being the final status of this OKR for Q4?

**Comment by jyavorska** [comment]
Closing since the quarter is over, but please be sure to add the final update.

**Comment by jjeffwarner** [comment]
Against a 6GB synthetic repo and a goal of 
> At a P75 level, a synthetic repo of 6GB will index in less than 30 minutes, index searches complete in < 2s and unindexed searches complete in < 10s

1. Time to index at P75 level ~16 minutes
2. Index search at P75 level ~
3. Unindexed search at P75 level ~
