### ISSUE TITLE
Cloud indexes public repositories globally from 4 non-GitHub code hosts

### ISSUE THREAD

**Issue by jjeffwarner** [sourcegraph/sourcegraph#27322]
This is a stretch goal for the squad. 

- [ ] [SPIKE: Adding additional code hosting sites #27050](https://github.com/sourcegraph/sourcegraph/issues/27050)

Currently at 1 of 4 additional repos.

**Comment by yinquanteo** [comment]
@jjeffwarner I renamed the title to be consistent with our OKRs and linked this row to the board https://github.com/orgs/sourcegraph/projects/214/views/11

**Comment by jyavorska** [comment]
@jjeffwarner @lguychard what ended up being the final status of this OKR for Q4?

**Comment by jjeffwarner** [comment]
@jyavorska It was considered a success. 
1. Fedora is fully supported. 
2. Maven and NPM are supported via integration with Code Intel. As additional packages are added via Code Intel, it will automatically be indexed by Zoekt.
3. Support for additional packages is available as they become available via Code Intel.
4. Query-based search context was added to the product.
