### ISSUE TITLE
git: Apply sub-repo filtering for ArchiveReader

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#27332]
We should apply sub-repo filtering for calls to the [git.ArchiveReader](https://github.com/sourcegraph/sourcegraph/blob/ed3096ddcc725ce7cc89411c108a2f5210f49763/internal/vcs/git/archive.go#L23)

Since we don't have a valid use case for an end-user to request an entire archive of a repo we should simply return an error here if the context indicates this is a user request and the repo support sub-repo permissions.

**Comment by bobheadxi** [comment]
@ryanslade also see https://github.com/sourcegraph/sourcegraph/issues/28243

**Comment by ryanslade** [comment]
Batch changes need access to a full archive, as a user. 

So we'll need to update this code to check whether batch changes are enforced on a per-repo basis.

**Comment by sashaostrikov** [comment]
The issue was discovered and discussed in this [Slack thread](https://sourcegraph.slack.com/archives/C02EDAQAJQZ/p1644410935431569)
