### ISSUE TITLE
Measure and increase % of customer active weekly users (saturation) by 15%

### ISSUE THREAD

**Issue by jyavorska** [sourcegraph/sourcegraph#27342]
I've added an (internal only) tracker at https://docs.google.com/spreadsheets/d/11H4z6Hz1sJvsE27kignYBi6JjEEt571ROwnVKnpnarM/edit#gid=0 for the values here, since Looker at the moment does not support viewing values over time. I'll update that every Monday morning.

This is a public issue in `sourcegraph` so do not list absolute metrics, customer names, or other topics listed as exclusions to transparency at https://handbook.sourcegraph.com/company/values#open-and-transparent. If this issue needs to include confidential topics, please move it to the private `product-engineering-planning` project.

**Comment by jyavorska** [comment]
@ebrodymoore do we have any dashboard or place where I could find or make something that would show WAU for the code graph product areas?

**Comment by jyavorska** [comment]
Asked about possibility of metric at https://sourcegraph.slack.com/archives/CN4FC7XT4/p1637057998095600.

**Comment by nicksnyder** [comment]
It feels weird to have so many assignees to a single issue. If you really expect something from each team, should we create a single KR/issue per team?

**Comment by jyavorska** [comment]
@nicksnyder would you like us to retroactively adjust the KR for Q4 or is this more feedback for next time? Both are possible, just wanted to confirm.

**Comment by jyavorska** [comment]
Added data tracker at https://docs.google.com/spreadsheets/d/11H4z6Hz1sJvsE27kignYBi6JjEEt571ROwnVKnpnarM/edit#gid=0

**Comment by nicksnyder** [comment]
Up to you, I guess my question is more: how are you going to track/report progress on this this quarter

**Comment by jyavorska** [comment]
@nicksnyder we're using https://docs.google.com/spreadsheets/d/11H4z6Hz1sJvsE27kignYBi6JjEEt571ROwnVKnpnarM/edit#gid=0 for now, which is ugly but gives us the week over week visibility that looker isn't able to provide yet.

**Comment by jyavorska** [comment]
Tracker updated: https://docs.google.com/spreadsheets/d/11H4z6Hz1sJvsE27kignYBi6JjEEt571ROwnVKnpnarM/edit#gid=0

**Comment by jyavorska** [comment]
Updated title to match source data

**Comment by jyavorska** [comment]
Moved to at risk since 50% of teams appear to be on track.

**Comment by jyavorska** [comment]
Final result: Both Code Insights and Code Intel exceeded their goals, Batch Changes met it, and Search missed by 12%.
