### ISSUE TITLE
FY22-Q4 OKR: Search works well for large-scale monorepos

### ISSUE THREAD

**Issue by jyavorska** [sourcegraph/sourcegraph#27346]
This is a public issue in `sourcegraph` so do not list absolute metrics, customer names, or other topics listed as exclusions to transparency at https://handbook.sourcegraph.com/company/values#open-and-transparent. If this issue needs to include confidential topics, please move it to the private `product-engineering-planning` project.

**Comment by yinquanteo** [comment]
Closing this out to replace with https://github.com/sourcegraph/sourcegraph/issues/27320
