### ISSUE TITLE
Precise code intel support for TS/JS

### ISSUE THREAD

**Issue by jyavorska** [sourcegraph/sourcegraph#27345]
This is a public issue in `sourcegraph` so do not list absolute metrics, customer names, or other topics listed as exclusions to transparency at https://handbook.sourcegraph.com/company/values#open-and-transparent. If this issue needs to include confidential topics, please move it to the private `product-engineering-planning` project.

**Comment by yinquanteo** [comment]
@scalabilitysolved could you (or someone on the team) update this to a tracking issue? And also update the note section on the board? https://github.com/orgs/sourcegraph/projects/214/views/11 
Thanks!

**Comment by jyavorska** [comment]
@scalabilitysolved @macraig what ended up being the final status of this OKR for Q4?

**Comment by macraig** [comment]
@jyavorska off track, extends to Q1 FY23
