### ISSUE TITLE
[duplicate] FY22-Q4 OKR: Precise code intel support for Kotlin

### ISSUE THREAD

**Issue by jyavorska** [sourcegraph/sourcegraph#27344]
This is a public issue in `sourcegraph` so do not list absolute metrics, customer names, or other topics listed as exclusions to transparency at https://handbook.sourcegraph.com/company/values#open-and-transparent. If this issue needs to include confidential topics, please move it to the private `product-engineering-planning` project.

**Comment by yinquanteo** [comment]
closing in favor of this https://github.com/sourcegraph/lsif-java/issues/304
