### ISSUE TITLE
1 customer issue solved with the help of `src debug`

### ISSUE THREAD

**Issue by jyavorska** [sourcegraph/sourcegraph#27347]

**Comment by yinquanteo** [comment]
@jjeffwarner  could you (or someone on the team) update this to a tracking issue? And also update the note section on the board? https://github.com/orgs/sourcegraph/projects/214/views/11 
Thanks!

**Comment by jjeffwarner** [comment]
Happy to take a look at it. @yinquanteo @jyavorska where is the original story for this one?

**Comment by yinquanteo** [comment]
[This](https://docs.google.com/document/d/1y1KVBMiVP5hZgEelF2iHM4AYVujq2tlU_bXDDTa8GdU/edit) is the Q4 planning doc that Loic and team put together. Not sure if there's an existing GitHub issue yet

**Comment by jjeffwarner** [comment]
@yinquanteo This was a potential Q4 OKR but it fell to the wayside and is not active work. I am going to close it.

**Comment by jyavorska** [comment]
@jjeffwarner this one did become an OKR (Q4 started back on the 1st). Can you add a note here and on the dashboard https://github.com/orgs/sourcegraph/projects/214/views/11 with a little more detail indicating why it was canceled? Is the plan to replace it with something else?

**Comment by jjeffwarner** [comment]
The 5.5m repo meeting on Oct 25 ended with a consensus to focus on monorepo and as an aspirational OKR, additional repo hosting sites for Q4. [These were documented in the handbook](https://handbook.sourcegraph.com/company/strategy/code-graph/search/core). As I understand it, this was a potential objective but it was not part of the squad's Q4 plan once the the priority on the monorepo work was established.

**Comment by jyavorska** [comment]
All OKRs are aspirational, I'm not sure I follow the distinction @jjeffwarner. It's fine to cancel one though if you like, can you add the reasons why that was done? Is there a plan to replace it with something else, or not in this case?
