### ISSUE TITLE
[duplicate] FY22-Q4 OKR: 3 customers adopt on-prem auto-indexing

### ISSUE THREAD

**Issue by jyavorska** [sourcegraph/sourcegraph#27351]
This is a public issue in `sourcegraph` so do not list absolute metrics, customer names, or other topics listed as exclusions to transparency at https://handbook.sourcegraph.com/company/values#open-and-transparent. If this issue needs to include confidential topics, please move it to the private `product-engineering-planning` project.

**Comment by yinquanteo** [comment]
Closing out in favor of https://github.com/sourcegraph/sourcegraph/issues/24961
