### ISSUE TITLE
Code Monitors has three customers committed to use the feature

### ISSUE THREAD

**Issue by jyavorska** [sourcegraph/sourcegraph#27350]
This is a public issue in `sourcegraph` so do not list absolute metrics, customer names, or other topics listed as exclusions to transparency at https://handbook.sourcegraph.com/company/values#open-and-transparent. If this issue needs to include confidential topics, please move it to the private `product-engineering-planning` project.

Major areas of work below:
- [ ] https://github.com/sourcegraph/sourcegraph/issues/25699

**Comment by yinquanteo** [comment]
@lguychard @benvenker I updated the description above to include reference to [Code monitors improvements #25699](https://github.com/sourcegraph/sourcegraph/issues/25699). Does that work? Feel free to link any other tracking issues. 

@lguychard I lifted your update in the Code Graph board "We've discovered an issue affecting the reliability of code monitoring, which might put our planned improvements at risk (https://sourcegraph.slack.com/archives/CU93UDUBV/p1636497223167500)" and put it in the tracking board
https://github.com/orgs/sourcegraph/projects/214/views/11

**Comment by benvenker** [comment]
@yinquanteo makes sense. After hearing back from engineering this afternoon, I'm comfortable (for now) moving this issue back to "On Track" status. They've agreed upon an approach that gets us the functionality we want and should allow us to hit our Q4 target. Will need to keep an eye on this one, but I'm going to move out of "At risk" for now.

cc @jyavorska

**Comment by christinaforney** [comment]
I think we should decouple the delivery of the functionality from the KR. There is already a roadmap item to deliver webhooks + slack (https://github.com/sourcegraph/sourcegraph/issues/10212), so this can now orient around the outcome of customer engagement with the feature (and perhaps we should orient around what we can measure in Q4?)

**Comment by jyavorska** [comment]
That's fine with me @christinaforney. This is one that has gone back and forth a few times. What do you think @benvenker? I think the new title would be `Code Monitors has three customers committed to use the feature`.

**Comment by benvenker** [comment]
Works for me. I'll update it now.

**Comment by jyavorska** [comment]
FYI I updated the dashboard note to `INC-52 and reliability improvements slowed our progress so we are flagging as “at risk”, though risk is relatively low at this point`. Previously it said something like we're on track but flagging as at risk, which was slightly less clear.

**Comment by jyavorska** [comment]
@benvenker @lguychard what ended up being the final status of this OKR for Q4?

**Comment by jyavorska** [comment]
Closing since the quarter is over, but please be sure to add the final update.
