### ISSUE TITLE
1 customer committed to paying for code insights at launch

### ISSUE THREAD

**Issue by jyavorska** [sourcegraph/sourcegraph#27352]
STRETCH goal: 3 customers

This is a public issue in `sourcegraph` so do not list absolute metrics, customer names, or other topics listed as exclusions to transparency at https://handbook.sourcegraph.com/company/values#open-and-transparent. If this issue needs to include confidential topics, please move it to the private `product-engineering-planning` project.

Tracking the major areas of work below:
- [ ] #22524
- [ ] #25972

**Comment by yinquanteo** [comment]
@felixfbecker I lifted your status for [the settings migration issue](https://github.com/sourcegraph/sourcegraph/issues/22524) over to this issue (i.e. marking this as "at risk" on [the board](https://github.com/orgs/sourcegraph/projects/214/views/11)). Feel free to update the status on the board if you feel like it doesn't quite reflect the status of this KR

**Comment by benvenker** [comment]
@malomarrec just happened to notice that the title of this issue changed to "x`", maybe by accident?

**Comment by jyavorska** [comment]
It's definitely a mistake @benvenker, I've corrected it.

**Comment by malomarrec** [comment]
Oops, sorry.

**Comment by felixfbecker** [comment]
Closing as **ACHIEVED** as of https://sourcegraph.slack.com/archives/C89KCDK5J/p1638390664256600 🚀

**Comment by Joelkw** [comment]
^ I've added a stretch goal issue as its own issue so we can have an open, separate top-level row on the OKR board. Additional logic behind the stretch goal versus "picking a new goal" in that issue.
