### ISSUE TITLE
Wildcard V2 migration prep: Codemod `<button>` usage to instead use the Wildcard `<Button />` component

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#27355]
## Description
We should automatically convert `<button>` usage to the Wildcard [Button component](https://storybook.sgdev.org/?path=/story/wildcard-button--all-buttons).

## Acceptance criteria
1. We have a codemod that migrates the vast majority of `<button>` elements to `<Button />`
2. We have documentation explaining how to run this codemod
3. We have documentation explaining how to create similar codemods. This will be the first Wildcard V2 codemod so we should ensure we have a good foundation to create future ones

**Comment by umpox** [comment]
@valerybugakov Feel free to modify the issue as you see fit!

**Comment by valerybugakov** [comment]
Oh, thanks! We already have [the issue](https://github.com/sourcegraph/codemod/issues/31) for this task, and I linked a prep PR to it. I'll continue tracking there.
