### ISSUE TITLE
Negative repo search is not applied

### ISSUE THREAD

**Issue by jensim** [sourcegraph/sourcegraph#27360]
- **Sourcegraph version:** 3.33.0 oss & enterprise
- **Platform information:** rhel7

#### Steps to reproduce:

1. search for `file:pom.xml -repo:/JENSIM/`

#### Expected behavior:

Give me all file hits that are not in a repo name that contains /JENSIM/

#### Actual behavior:

No repos are excluded.

But if I add `repo:.` to the search, the negative search is applied as well.

**Comment by benvenker** [comment]
This appears to work as expected now: https://sourcegraph.com/search?q=context:global+file:pom.xml+-repo:/JENSIM/&patternType=literal (3.37 is the latest currently)
