### ISSUE TITLE
internal/trace: enable export of OpenTelemetry tracing

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#27386]
We currently have both jaeger client-go and Opentracing API's in our codebase. 
https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+github.com/uber/jaeger-client-go+OR+github.com/opentracing/opentracing-go&patternType=literal 

Both of these projects are deprecated and superseded by OpenTelemetry

We should replace this usage with https://pkg.go.dev/go.opentelemetry.io/otel

OpenTelemetry also contains several other standards around metrics and logging we should also adopt. 

See the channel #wg-observability for how we are thinking about accomplishing this

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/cloud-devops - the "team/devops" label was applied to this issue.

**Comment by bobheadxi** [comment]
Part of this work could probably be to remove as much vendor-specific tracing code as possible from the tracing package, notably Datadog, especially if we move ahead with dropping Datadog.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/delivery - the "team/delivery" label was applied to this issue.

**Comment by bobheadxi** [comment]
Re-assigning _again_ for now because of note in https://docs.google.com/document/d/1EPamUDc1O-OpFrv8rq3wS8Tf__icT8ijewGrSaSTKDw/edit#bookmark=id.282sqs68i2gv:

> Enable customers to connect and ingest Sourcegraph’s OpenTelemetry-compliant data into their monitoring solutions (e.g. Datadog, NewRelic, Honeycomb, and others). - Delivery team

Note that we're happy to help out still, let us know!

**Comment by briemcnally** [comment]
@bobheadxi this has not been prioritized or committed to by the Delivery team at this time. I believe the linked document is out of date. What is the urgency on delivering this? What is the impact if we do not do this in Q3?

**Comment by briemcnally** [comment]
We are in the process of defining the product roadmap, but the roadmap for Delivery for Q3+ is not complete yet. This was shared with me recently and is up to date on committed work: https://docs.google.com/document/d/1ICtf7Hpt5opOngS9fe1T0ETX_MTMBiuPwVeKG9cAQX0/edit

**Comment by bobheadxi** [comment]
This is definitely DevX ownership now, sorry for the confusion! Reassigning.

**Comment by bobheadxi** [comment]
Initial exploration: https://github.com/sourcegraph/devx-scratch/blob/main/2022/observability/log.snb.md#2022-06-23-opentelemetry-trace-export-exploration

**Comment by bobheadxi** [comment]
There's a bridge tracing package we can use: https://pkg.go.dev/go.opentelemetry.io/otel/bridge/opentracing#NewTracerPair

**Comment by michaellzc** [comment]
> There's a bridge tracing package we can use: [pkg.go.dev/go.opentelemetry.io/otel/bridge/opentracing#NewTracerPair](https://pkg.go.dev/go.opentelemetry.io/otel/bridge/opentracing#NewTracerPair)

there's a project that uses the bridge extensively, maybe we can borrow some codes from them.

https://sourcegraph.com/github.com/thanos-io/thanos/-/blob/pkg/tracing/migration/bridge.go
