### ISSUE TITLE
Impossible to change repositoryPathPattern after adding repositories

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#2741]
1. Add thousands of repositories to your Sourcegraph instance, wait for them to clone, etc.
2. Realize that since the browser extension repo name and Sourcegraph repo name must align, you actually needed to change `repositoryPathPattern` or else the browser extension won't work.
3. Edit the external service, set `repositoryPathPattern`... nothing happens! All repositories at `/site-admin/repositories` do not update, the new pattern is not respected!
4. At this point, your only resolution appears to be (a) write a script to delete all repositories or something then (b) add them all back again and wait for them to clone(!)

**Comment by keegancsmith** [comment]
This will partially be solved by #2025.

**Comment by tsenart** [comment]
Another very similar issue is when an admin changes the URL of an external service. This results in a similar phenomena as the described above. I suspect that handling these two cases goes hand in hand with our ideas for the "aliases" work. Note that supporting this sort of renames on Sourcegraph's config side is distinct from handling upstream repo name changes (which is covered by the work in #2025).

**Comment by keegancsmith** [comment]
The solution we have for 3.4 doesn't solve the recloning and reindexing issue. However, we no longer leave the old names around (this is properly cleaned up). I believe that is a major improvement. Updating our indexed search and gitserver to not be name based is a bit more work (especially for indexed search). If customers complain about this deficiency please open another issue :)
