### ISSUE TITLE
search: fix repository stats for GraphQL search

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#27421]
With the introduction of [repo pagination](#27359), repository counts changed meaning from the universe of repos to the repositories with matches. While streaming search was straightforward to adjust these statistics to the new semantics, GraphQL wasn't since there are a few different places where we currently cut matches which now need to update or re-compute statistics.

As part of this work, we should introduce a thorough set of integration tests in `dev/gqltest/search_test.go` for these statistics, both for streaming and GraphQL.

https://github.com/sourcegraph/sourcegraph/blob/3a7a0535ea7bf430c7e0b2c77f4720a80d55b5ca/cmd/frontend/graphqlbackend/search_results.go#L128-L135

https://github.com/sourcegraph/sourcegraph/blob/3a7a0535ea7bf430c7e0b2c77f4720a80d55b5ca/cmd/frontend/graphqlbackend/search_results.go#L910-L918

https://github.com/sourcegraph/sourcegraph/blob/3a7a0535ea7bf430c7e0b2c77f4720a80d55b5ca/cmd/frontend/graphqlbackend/search_results.go#L1182-L1189

**Comment by tsenart** [comment]
cc @rvantonder

**Comment by tsenart** [comment]
Caught up with @keegancsmith which will take this over from me. We found a few related things that need to be bundled together before branch cut.

1. Streaming `Repo` stats need to be computed before display limit is enforced.
2. `RepoStatusMap` needs to look things up from the DB rather than the `Repo` map because that second map now doesn't contain the full universe of searchable repos.

**Comment by keegancsmith** [comment]
Another issue:  5.9k repo results while only 1.5k repos have been searched
![image](https://user-images.githubusercontent.com/187831/142408590-8297f751-3d74-4508-bd1e-8441969587c9.png)

**Comment by jjeffwarner** [comment]
@keegancsmith did this work also include "set of integration tests in `dev/gqltest/search_test.go` for these statistics, both for streaming and GraphQL?" If not, please a new story for our backlog so we don't lose it.

**Comment by keegancsmith** [comment]
No I didn't work on that. To be completely honest I'm not sure it is worth tracking, I doubt anyone will pick it up.

**Comment by jjeffwarner** [comment]
Fair enough. We have plenty of opportunities :)
