### ISSUE TITLE
Remove gitserver_repos.last_external_service column

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#27422]
The column is not used anywhere.

We should write a migration to remove it and remove all references to it in https://github.com/sourcegraph/sourcegraph/blob/main/internal/database/gitserver_repos.go

**Comment by mollylogue** [comment]
I'm not sure what we do with these GH issues when we're working on them/up for review/done/etc. I have a PR open for this here: https://github.com/sourcegraph/sourcegraph/pull/28108

**Comment by ryanslade** [comment]
We would usually move them to "In Progress" and then "In Review" here: https://github.com/orgs/sourcegraph/projects/209

**Comment by ryanslade** [comment]
@mollylogue You can close this issue now 🎉
