### ISSUE TITLE
insights: graphql - update insights attached to a dashboard in a single operation

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#27449]
Provide a mutation (something like `modifyInsightsDashboardsViews` that allows a single operation to perform transactional mutation of:
1. Adding insight views to a dashboard
2. Removing views from a dashboard

Partial failures should fail the entire transaction.

**Comment by unclejustin** [comment]
If/when this issue is resolved, the frontend will need to update to use this.
