### ISSUE TITLE
sub-repo perms: Integration tests

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#27448]
We plan to add integration level tests using our existing [dev/gqltest]() package.

We plan to cover the following:

- [x] Accessing file data is not allowed
- [x] File lists are filtered
- [x] Indexed search matches are hidden
- [x] Non-indexed search matches are hidden
- [x] Structural search matches are hidden
- [x] Symbol search matches are hidden
- [x] Diff search results are hidden
- [x] Commits lists are filtered
- [x] Direct access to a commit is blocked
- [ ] Find references results are hidden
  - [x] Search based
  - [ ] Precise (Confirmed after uploading an LSIF dump)
- [x] File contents search (`type:file`)
- [x] File name search (`type:path`)
- [x] Archive requests are blocked for repos with sub-repo permissions

**Comment by bobheadxi** [comment]
Some initial thoughts: https://github.com/sourcegraph/sourcegraph/pull/27189#issuecomment-966444237

**Comment by bobheadxi** [comment]
docs on perforce dogfood: https://handbook.sourcegraph.com/support/p4-enablement

This might look like this in `dev/gqltest/search_test.go`:

```go
	perforceID, err := client.AddExternalService(gqltestutil.AddExternalServiceInput{
		Kind:        extsvc.KindPerforce,
		DisplayName: "gqltest-p4-search",
		Config: mustMarshalJSONString(struct {
			Port                  string      `json:"p4.port"`
			User                  string      `json:"p4.user"`
			Password              string      `json:"p4.passwd"`
			RepositoryPathPattern string      `json:"repositoryPathPattern"`
			Depots                []string    `json:"depots"`
			Authorization         interface{} `json:"authorization"`
		}{
			Port:                  "perforce.sgdev.org:1666",
			User:                  "buildkite",
			Password:              "TODO",
			RepositoryPathPattern: "perforce/{depot}",
			Depots: []string{
				"//test-perms/",
			},
			Authorization: struct {
				SubRepoPermissions bool `json:"subRepoPermissions"`
			}{ SubRepoPermissions: true },
		}),
	})
	if err != nil {
		t.Fatal(err)
	}
	defer func() {
		err := client.DeleteExternalService(perforceID)
		if err != nil {
			t.Fatal(err)
		}
	}()
```

**Comment by bobheadxi** [comment]
https://github.com/sourcegraph/sourcegraph/issues/27496 is a dependency for this work

**Comment by bobheadxi** [comment]
My notes on manual e2e testing: https://github.com/sourcegraph/sourcegraph/issues/26645#issuecomment-963576534

**Comment by bobheadxi** [comment]
#27567 opens the door to potentially writing arbitrary sub-repo-perms rules to the table in tests, though unsure how feasible this is yet.

**Comment by bobheadxi** [comment]
Good home for this I think: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/authtest/repository_test.go?L129-139&utm_source=VSCode-1.4.0#L139:4

**Comment by ryanslade** [comment]
We've got a good set of integration tests now as well as unit tests so I'm going to close this.
