### ISSUE TITLE
insights: update migrations documentation for code insights

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#27454]
Improve the migration documentation pages to clarify that code insights is a different database, and the migration tables is different than the primary postgres.

Additionally, add some more context for customers to be able to self-troubleshoot more migration problems (such as resolving down migrations after reverting an image).

Slack thread for context
https://sourcegraph.slack.com/archives/C014ZCKMCAV/p1636652682291000?thread_ts=1636651573.285400&cid=C014ZCKMCAV

**Comment by leonore** [comment]
@coury-clark closing this as it seems no longer relevant as we've retired timescaleDB
