### ISSUE TITLE
Sourcegraph chrome extension not working when pointing at local instance

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#2747]
Sourcegraph version: insiders - 29412_2019-03-14_38950e1 (29412_2019-03-14_38950e1)
Chrome: 73.0.3683.75 

![ScreenFlow](https://user-images.githubusercontent.com/133014/54396824-95346b00-4671-11e9-8dbe-d0aa82a993ac.gif)

**Comment by sqs** [comment]
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/2725
