### ISSUE TITLE
Detect slowness when running local instance

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#2748]
If a user runs a Sourcegraph instance on (especially) a laptop with a lot of other things running, the initial setup can fail. We should detect if it takes longer than 15-20s and print a message and/or handle the case.

Repro: Run a lot of apps with high CPU and memory usage, then run the Docker quickstart command. (Be sure you're running enough stuff that it takes ~40-60s to initialize, not the 15-20s stated.) It will print a DB error about being unable to acquire the lock, and a bunch of other error messages, too.

The fix was to have them re-run the `docker run` command, but they might not have realized to do that if we weren't on the demo with them.

Happened on a demo just now cc @KattMingMing

**Comment by beyang** [comment]
stale, please re-open if still an issue
