### ISSUE TITLE
sub-repo perms: configure dogfood perforce with sample permissions

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#27496]
We need to set up out dogfood perforce instance with a sample repo that has sub-repo permissions configured. 

I suggest we use the `//dax-golang` depot, which is a copy of the Go sourcecode as it's relativley large and should give us some early performance signal.

**Comment by ryanslade** [comment]
@bobheadxi I tried a few things but was unable to get this to work. 

Have you been able to test sub-repo permissions syncing from Perforce? I tried adding a user locally with one of the e-mails of the test users on our perforce.sgdev.org but that didn't seem to help. 

I can see that we have a Perforce auth provider running locally. Are there any other steps needed? I'm trying to get a minimal setup that proves everything is hooked up end to end. Once we have that working manually it should allow us to more easily add some automated tests.

**Comment by bobheadxi** [comment]
I noted this in https://github.com/sourcegraph/sourcegraph/issues/27448#issuecomment-966932534:

- handbook: https://handbook.sourcegraph.com/support/p4-enablement
- dogfood: https://k8s.sgdev.org/perforce/test-perms

I have yet to try it myself and am unsure what is available in this depot, but the name implies this was used to test permissions before, and is successfully cloned in dogfood. cc @DaedalusG , could you help us get up to speed on these depots?

**Comment by DaedalusG** [comment]
Hey @bobheadxi these depots were created by @unknwon (I believe) during the early days of perforce setup. The doc linked there was written primarily as an enablement doc for our AER's (new title = Application Engineer).

The document follows is mostly a digest of [this doc](https://docs.google.com/document/d/1nRKdDxfw6Y0PDLpf4ukTPStqJLKf53aSKE0dEH8ciaY/edit) written by Joe. I'm not totally sure about the nature of those depots or how they relate to the perforce permissions stuff Joe set up for that server.. Hope that helps to point you in the right direction, @unknwon probably knows more?

**Comment by unknwon** [comment]
If you use Perforce GUI tools to open the access list of test-perms (or equivalent p4 comment), you'll need ACL comment explaining which rule means for what. I can't recall all the details exactly ...

**Comment by ryanslade** [comment]
This is working, details of how to configure this locally can be seen here:
https://docs.google.com/document/d/1FEa-6wbyMTROSQF70ClQNpfdDMMBF9fgJ627ruWVj1U/edit#heading=h.ao1qf83jhcgf

**Comment by bobheadxi** [comment]
@ryanslade that document is not available to me (not trying to use it so non-urgent, but was curious) - it would be good to have instructions documented in-tree (or in the handbook)!

**Comment by ryanslade** [comment]
I've replicated it in the handbook:
https://github.com/sourcegraph/handbook/pull/2043
