### ISSUE TITLE
Theme picker doesn't show warning when "System" option selected in Chrome 73

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#2749]
On macOS Mojave, I have the dark theme set, but when I choose **System** from the theme selector, it changes to light mode?

![ScreenFlow](https://user-images.githubusercontent.com/133014/54397453-bf872800-4673-11e9-85e7-93c87e907067.gif)

**Comment by felixfbecker** [comment]
Chrome still doesn't support system theme. But the latest update made the feature detection return a false positive.

**Comment by felixfbecker** [comment]
System theme is now supported in stable Chrome, Firefox, Safari and Edgium.
