### ISSUE TITLE
sub-repo perms: filter commits shown

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#27498]
The simplest option here is to not allow access to commits via the API if any modified files in the commit would be disallowed by permissions. 

This is required when listing commits and also viewing commits directly.

**Comment by mollylogue** [comment]
@ryanslade would this be a decent thing for me to start looking at?

**Comment by ryanslade** [comment]
Yep. My thinking here is that the safest thing to do is just hide the entire commit rather than trying to just hide changes to files that the user can't see. 

Let me know if you need any more context.

**Comment by mollylogue** [comment]
Question: @ryanslade do we want to add filtering in [git.ResolveRevision](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/vcs/git/revisions.go?L66:6) as part of this?

**Comment by ryanslade** [comment]
> Question: @ryanslade do we want to add filtering in [git.ResolveRevision](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/vcs/git/revisions.go?L66:6) as part of this?

No, I think we should leave that function as is. It's quite a fundamental method and I'm a bit worried about performance if we need to dig into the commit to get file lists too. 

I also think that resolving to a commit doesn't leak anything private except the existence of a revision which is acceptable.
