### ISSUE TITLE
insights: disable background insights over repos with sub-repo perms

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#27490]
See [RFC 503](https://docs.google.com/document/d/1d8j-6VC_nk8HXEDT6U2_s-_9uSzgzHWZzrJjII9pKEE/edit#)

Background: Code Insights iterates over all repositories and records data points per repository. Permissions are enforced when code insights are queried by removing repositories the user cannot see from that recorded set of data, and resolving them into a time series. Code Insights cannot support sub-repo permissions at this time due to cardinality constraints that have not been addressed, and addressing these constraints is neither a requirement nor on the short-term roadmap for Insights.

Goal: Skip code insights recordings of repositories entirely that have these sub-repo permissions enabled, both when iterating over repositories for a non-global search, and when iterating over results from a global search.

Tasks:

-   (5d) Implement filtering in the code-insights worker for now - when [jobs are dequeued, an unauthenticated search is run](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@9fd01729ebabd3072578d6049dd94e2e192226de/-/blob/enterprise/internal/insights/background/queryrunner/work_handler.go?L155-179) and all data is recorded as one data point per repository, so we can just drop data points here from all results on repositories that have any sub-repo permissions.

-   The [web-app-generated code insights](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@c3011a30a0b9d21bc22ce7862c58d5f5bd62e12d/-/blob/client/web/src/enterprise/insights/core/backend/core/api/get-search-insight-content/get-search-insight-content.ts?L93-107) (for repo-specific insights) are [covered by work on search filtering](https://docs.google.com/document/d/1d8j-6VC_nk8HXEDT6U2_s-_9uSzgzHWZzrJjII9pKEE/edit#bookmark=kix.o4l3l76pq76b), since it [just performs a regular search](https://sourcegraph.slack.com/archives/C014ZCKMCAV/p1637788563446400?thread_ts=1637713681.443100&cid=C014ZCKMCAV).

**Comment by ryanslade** [comment]
@sashaostrikov Un-assigning for now as you're going to be on support and someone else may want to pick it up next week.
