### ISSUE TITLE
Add or revise thresholds for alerting on latency

### ISSUE THREAD

**Issue by jjeffwarner** [sourcegraph/sourcegraph#27545]
From the [2021-11-10 retro](https://docs.google.com/document/d/1s80YLFQ6-K4bCeXw85LHgtqrWSH5lsARrfv5O7YI6Yo/edit#heading=h.rnu2lkbnaf1v)

Product latency issue went unnoticed. 
Rethink how we monitor for this, consider start of operational documentation for system.

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket,  please let us how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
