### ISSUE TITLE
Automated testing for ranking system

### ISSUE THREAD

**Issue by jjeffwarner** [sourcegraph/sourcegraph#27544]
From [retro for 2021-11-10](https://docs.google.com/document/d/1s80YLFQ6-K4bCeXw85LHgtqrWSH5lsARrfv5O7YI6Yo/edit#heading=h.rnu2lkbnaf1v).

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket,  please let us how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
