### ISSUE TITLE
Select code on search page

### ISSUE THREAD

**Issue by thuan1412** [sourcegraph/sourcegraph#27558]
#### Feature request description
Currently, when I search for code and want to copy that code snippet, I have to open the code file to be able to copy the code. 
So, I think it's would be convenient if we can copy the code snippet directly on the search page.

#### Is your feature request related to a problem? If so, please describe.
As the description said, I always have to make one more action (open file) to copy the code.

#### Describe alternatives you've considered.
None

#### Additional context
None

**Comment by umpox** [comment]
Thanks for the request @thuan1412!

We have recently enabled this through this PR: https://github.com/sourcegraph/sourcegraph/pull/30033
