### ISSUE TITLE
Fuzzy finder shortcut should only display in Keyboard shortcuts if feature is enabled

### ISSUE THREAD

**Issue by chdsbd** [sourcegraph/sourcegraph#27553]
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:** Edge 95

#### Steps to reproduce:

1. Visit your user settings page and verify the `fuzzyFinder` experimental feature is not enabled
2. Navigate to a repository in Sourcegraph: https://sourcegraph.com/github.com/sourcegraph/sourcegraph
3. Open the keyboard shortcut panel with <kbd>shift</kbd> + <kbd>/</kbd>
4. See that the "Fuzzy search files" shortcut is displayed, but the shortcut doesn't work

#### Expected behavior:

The "Fuzzy search files" shortcut should only be visible if the fuzzyFinder feature is enabled.

#### Actual behavior:

The "Fuzzy search files" shortcut is visible when the shortcut doesn't work.

**Comment by umpox** [comment]
Thanks for raising! The fuzzy finder is now enabled by default so I think we can close this

**Comment by jdorfman** [comment]
@chdsbd would love to hook you up with some swag. Drop me an email if interested community@sourcegraph.com
