### ISSUE TITLE
Create functionality for `type:diff select:file` searches 

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#27550]
From @camdencheek 
> IIRC, we skipped implementing type:diff select:file because it was ambiguous and we’d need to make a followup network request for each result in order to implement it.
Ambiguous because type:diff select:file test could mean:
> 1) For diffs that matched test, return all the files the diff modified
> 2) For diffs that matched test, return all the files the diff modified where the modifications match test
Most likely number 2 is what we want, but currently, we return a pre-formatted diff from diff search, which is pre-limited in size, so it might not contain all the files modified by the diff.
With the new commit/diff search I recently made default, we’re actually much closer to being able to implement this because we could now stream the full diff contents, and format them closer to the API boundary.
I didn’t think anyone really wanted this, so I haven’t prioritized it (or even made a ticket for it), but if this is something that would be useful for making insights behave more intuitively, let’s certainly track it

My comments: 

Assume the primary use case (potentially) comes from Code insights, I agree that case 2) is the user expectation. 

For an explanation: 

Right now, if you have Insight A tracking occurrences of "library XYZ", when you click into the graph by clicking on a data point we take you to a diff search showing you all places this was added/removed between that datapoint and the preceding datapoint (so a diff search with a before: and after: ). The idea is "show me where all the changes came that contributed to this datapoint and were new since the last datapoint." 

Now assume Insight B might be something like "how many files use at least one occurrence of some indicator of library XYZ," because you don't really care how many times each file uses it, you just want the general "spread" of it in your code. Now, when you click a diff, you probably expect "okay, show me all the files that had this added/removed since the prior datapoint, so I understand what contributed to the increase/decrease of this datapoint." That's the case 2) – you want to see the files that are "newly counted" in this insight. 

/cc @sourcegraph/search-platform

**Comment by Joelkw** [comment]
Priority – this is not urgent. 

It would be nice to have by Code Insights GA (Feb 2022) but we can work around it other ways (remove this functionality) by: 
- We figure out how to disable this special case (only) in the product
- We update the search no results page with an error message instruction all diff searchers who use `select:file` to remove that?

**Comment by benvenker** [comment]
@Joelkw this _may_ be resolved by some sub-repo permissions work, but we still have some decisions to make. Per @camdencheek this may be possible in the very near future.

**Comment by camdencheek** [comment]
So, getting my head back into this, after https://github.com/sourcegraph/sourcegraph/pull/30109, we'll have the ability to (more) cheaply list files that the commit touches. This makes things like `type:commit author:camden select:file` would mean "return any files modified by commits created by camden". This is option 1 above.

This is not quite what we want, but I also think option 2 above is also possible right now just by pulling the file names out of the diff hunks that matched. It's not _super_ cheap right now, but that can be improved in the future. 

That said, I'd like to think a little bit about whether we can represent both of these options in a consistent manner with `select:`. I'm struggling a bit to come up `select:` nouns that communicate the intent. 

cc @rijnard for your take on the below: 

- `type:commit query select:commit.diff.files` means "return the files that were modified by commits whose message matches `query`"
- `type:diff query select:commit.diff.files` means "return the files whose diffs matched `query`"

The construction of the above is somewhat parallel with the existing `select:commit.diff.added`

**Comment by Joelkw** [comment]
Thanks @benvenker @camdencheek ! 

If it helps, the conceptual model of code insights right now is that adding `type:diff` the difference between two datapoints in time, i.e., what changed, so it would be cool if `type:diff` didn't require `select:` to do files.  

When you click an insight querying on `TODO` you get something like `TODO type:diff before:[second datapoint time] after:[first datapoint time]` and this shows you why the data increased/decreased. This breaks currently on `select:file` for reasons noted above. 

If you had an insight like `lang:TypeScript select:file` that was counting how many TS files you have (an approx of language that many customers use to see growth/comparison), then it'd be nice if adding `type:diff before:[datapoint 2] after:[datapoint 1]` would show you all the new files created. 

We can probably do some janky frontend logic (or eventually build a full resolver or something) to realize we need to add `type:diff select:commit.diff.files` to your query if you want to "see the diff" and strip the `select:file`, rather than just adding `type:diff` to `select:file`, but it'd be cool if it "just worked." (Or maybe the intention was that this is the default but `select:` lets you specify both?)

**Comment by rvantonder** [comment]
Belated reply -- I haven't digested these proposals yet. I think it's something that needs more thought (language design wise). I will say the part about `modified` files (and friends `added` and `removed`) encourage a distinct treatment and expressivity that we do want to unlock (and I remember some faint requests about this in the past), which prompts new syntax, and the idea proposal about `type:commit ...` seems a bit coarse.

The part about `type:diff` and just selecting files from a diff format seems on the surface reasonable with something `type:diff query select:commit.diff.files` but I do think this needs more thought/design: we should go over the internal type for `diffs` (or its intended end state), and whether it maps cleanly to this syntax (can't remember off the top of my head).

The ask here is a search extension/product extension for greater expressivity and I think we should weigh it that way--there's quite a bit of complexity here and the cost of getting it wrong will outweigh the immediate benefit (a couple of varied) use cases @Joelkw describes. For example, this idea sounds clear and easy, but it also introduces the notion of _newly created files_ (not just modified ones):

> If you had an insight like `lang:TypeScript select:file` ... then it'd be nice if adding `type:diff before:[datapoint 2] after:[datapoint 1]` would show you all the new files created.

And we don't currently parse or capture any of that data for a diff result type. Unfortunately without more thought and design (re: result types and how syntax maps to it) I am hesitant that a single example "just works" generally. It might work in that one case, and then you realize you want something slightly different, and the assumptions you made along the way now effectively lead to a dead end--that's the pitfalls at play. I think this is a multi-week to multi-month effort, depending on who is available (I am personally not able to devote any sort of full time to this particular problem right now, but can be involved in the process of someone else driving it).

My question (or suggestion), until we can give this real treatment as an extension of search, is whether it is possible for Code Insights to use the search primitives available today (diff search and `before`/`after`, etc) and consume the (larger-than-desired) result set, and, for example, parse the diff results (get some JS diff parser), and extract things like file paths, and detect create/removal/deletion of files.

**Comment by Joelkw** [comment]
@rvantonder thanks for the reply! It may be possible for code insights to get closer as we examine new UI/UX for digging into charts, and we'll keep this in mind. More likely, we'll start by just showing you per-repo breakdown of the total count of changes (subtract one datapoint from another, per-repo) and then let you look at the diffs within that repo.
