### ISSUE TITLE
code search doesn't load on Safari 13.1.1

### ISSUE THREAD

**Issue by chdsbd** [sourcegraph/sourcegraph#27551]
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:** macOS 10.15.5, Safari 13.1.1

#### Steps to reproduce:

1. Navigate to https://sourcegraph.com/search on Safari 13.1.1
2. Verify page fails to render and error exists in console

```
SyntaxError: No identifiers allowed directly after numeric literal
```

#### Expected behavior:

Code search should load on older versions of Safari

#### Actual behavior:

Code search fails to render.

**Comment by chdsbd** [comment]
It looks like this BigInt literal (`1n`) is the issue with Safari:

https://github.com/sourcegraph/sourcegraph/blob/607b1c51a56110dd03be9f37a12bb126a48d56aa/client/shared/src/util/strings.ts#L24-L26

**Comment by umpox** [comment]
Safari is no longer a supported browser as it does not fall into [our usage targets](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/.browserslistrc?L1%3A3=). Closing this!
