### ISSUE TITLE
executors: Warn when outdated

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#27570]
We currently rely on the executors being in version sync with the backend, so we should either not allow starting up when the version doesn't match a specific version constraint or at least warn site-admins that the instances are outdated.

**Comment by eseliger** [comment]
I think we shouldn't do this in this sustaining sprint as we might solve this automatically with some refactors that are upcoming.

**Comment by BolajiOlajide** [comment]
Getting the Sourcegraph version is tricky as it's not always in `Semver`. Also, it's possible that in some environment (e.g k8s) both `buildVersion` and `productVersion` are sometimes the same and are [both derived from `version.Version` as shown here](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/site.go?L107-109).

![CleanShot 2022-08-10 at 17 48 49@2x](https://user-images.githubusercontent.com/25608335/183969376-bdd154ab-2d1b-41f0-9a7b-f255c849435f.png)

Right now when a new build is released, the version will switch from being `3.42.2` to something like `NNNNNN_YYYY_MM_DD_NNNNN` which will be tricky to figure which Sourcegraph version is running.

cc @eseliger

**Comment by eseliger** [comment]
src-cli has some logic built-in that can handle this quite okay, by trying to look at the build date instead when it doesn't follow semver.
