### ISSUE TITLE
Create a patch release to fix regression in SSH-based Batch Changes auth that blocks customer

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#27572]
@sourcegraph/delivery I am requesting the following commits be included in a patch release. They are already merged into `main`:

- https://github.com/sourcegraph/sourcegraph/commit/0cf82e5ae12063d9cd540193e3051145ecf69522

---

I have read [when and why we perform patch releases](https://handbook.sourcegraph.com/engineering/releases#patch-releases) and answer the questions as follows:

> Are users/customers actively asking us for these changes and cannot wait until the next full release?

Yes: https://github.com/sourcegraph/customer/issues/558#issuecomment-968791974

> Are the changes extremely minimal, well-tested, and low risk such that not testing as we do in a full release is OK?

Yes. It's a a 1-line, 10-character change that I tested locally. I also know exactly when and how it was introduced and why it broke and why the fix fixes it.

> Is there some functionality completely broken that warrants redacting the prior release of Sourcegraph and advising users wait for the patch release?

No, the regression was introduced on another end of the system in 3.27.

> This will interrupt our regular planned work and release cycle, taking one full working day of our time, and will take up all of our site admin's valuable time by asking them to upgrade or producing noise for them if they don't need to upgrade.
>
> Do you believe the changes are important enough to warrant this?

I _think_ so, since it's a small change and the customer is asking for it.

> Patch releases are a signal we can do something better to improve the quality of Sourcegraph. Have you already scheduled a call (or created a google doc) to perform a [retrospective](https://about.sourcegraph.com/retrospectives) and identify ways we can improve?

We've already talked about this internally in Batch Changes and will do so again in our retrospective.

---

**For the [release captain](https://handbook.sourcegraph.com/engineering/releases#release-captain)** - after reviewing this request:

- [x] **Comment on this issue** with a decision regarding the request.
- [ ] If approved, **add it to a patch release**:
  - If there is [already an upcoming patch release](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+), add the listed commits alongside a link to this issue
  - If there is no upcoming patch release, create a new one:
    - Update [`dev/release/release-config.jsonc`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/release/release-config.jsonc) with the patch release in `upcomingRelease` and `releaseDate` (and open a PR to `main` to update it)
    - `yarn release tracking:issues`
    - Add the listed commits alongside a link to this issue to the generated [release tracking issue](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+)
- [ ] **Comment and close this issue once the relevant commit(s) have been cherry-picked into the release branch**.

**Comment by caugustus-sourcegraph** [comment]
@mrnugget - do you think a patch release is necessary back to 3.27, or would it be limited to 1 or 2 versions back? (2 versions would allow the customer to do a patch upgrade instead of a minor).

**Comment by airamare01** [comment]
If I can chime in here please, I think that it would make sense to patch back to 3.27 since this is where it was initially "broken". 
I'd defer, of course to @mrnugget though for his thoughts

**Comment by mrnugget** [comment]
I don't think it's necessary to patch back to 3.27. At some point we have to draw a line and patching 6 releases is, I think, beyond any line :)

The customer in question is on `Sourcegraph Version: 3.32.0` and we haven't heard from other customers on this topic.

So I'd love to get input here on how hard it is for the customer to upgrade to 3.33 before deciding to backport the fix to 3.32 even.

**Comment by airamare01** [comment]
It wouldn't be hard for the customer to perform the upgrade to 3.33 and they do have a preference to patch on their current version(3.32)

**Comment by airamare01** [comment]
@caugustus-sourcegraph , sorry to ask but would like to check in with you please on whether the patch could be released today by any chance?

**Comment by caugustus-sourcegraph** [comment]
@mrnugget @airamare01 - creating two patch releases (3.33 and 3.32) sounds like a good balance here between effort and impact. We'll get started on the patch releases - I can't guarantee it'll be complete today but we'll do our best!

We'll also revisit the larger issue ("how far back do we patch in general?") in the near future.

**Comment by airamare01** [comment]
Thanks @caugustus-sourcegraph ! Really appreciate you're help on this.

**Comment by caugustus-sourcegraph** [comment]
@airamare01 - sad news: it's unlikely the patch release will be ready today. We've been trying to get the builds to work all afternoon and keep running into problems (all unrelated to the actual change included in the patch). At this point, everything is building successfully but failing tests.

**Comment by airamare01** [comment]
@caugustus-sourcegraph - thanks for the update. Sorry to hear about the failing tests. I hope today we can probably overcome the failing tests :)

**Comment by caugustus-sourcegraph** [comment]
@airamare01 - the patch release 3.32.1 is available now. I'll be working on a 3.33.1 release soon as well.

**Comment by caugustus-sourcegraph** [comment]
3.33.1 has been published as well.

**Comment by mrnugget** [comment]
Thanks so much, @caugustus-sourcegraph!

**Comment by airamare01** [comment]
Thanks a ton @caugustus-sourcegraph and @mrnugget!
