### ISSUE TITLE
Unable to contact extension registry: Get https://sourcegraph.com/.api/registry/extensions: remote error: tls: access denied

### ISSUE THREAD

**Issue by cainzhong** [sourcegraph/sourcegraph#2758]
#### Question description

I deployed a 'sourcegraph/server:3.1.2', and it is started successfully. But the registry extensions can not be used. There is an error, 'Unable to contact extension registry: Get https://sourcegraph.com/.api/registry/extensions: remote error: tls: access denied'

**Comment by sqs** [comment]
Is this still occurring? Can you load that URL 
https://sourcegraph.com/.api/registry/extensions with curl or in your web browser? (It will give an error about content type when loaded without the right headers, which is expected.)

**Comment by fridayhoho** [comment]
invalid Accept header: expected "application/vnd.sourcegraph.api+json;version=20180621"

**Comment by cainzhong** [comment]
> Is this still occurring? Can you load that URL
> https://sourcegraph.com/.api/registry/extensions with curl or in your web browser? (It will give an error about content type when loaded without the right headers, which is expected.)

curl: (35) Peer received a valid certificate, but access was denied.
Do you have any idea how to fix it? I am using centos.

**Comment by cainzhong** [comment]
I fixed the problem. It is a proxy issue.
`docker run -e HTTP_PROXY=.... -e HTTPS_PROXY=...`

**Comment by cainzhong** [comment]
Refer to https://github.com/sourcegraph/sourcegraph/issues/69

**Comment by sqs** [comment]
Thanks for finding the fix!

**Comment by ganouar** [comment]
> I fixed the problem. It is a proxy issue. `docker run -e HTTP_PROXY=.... -e HTTPS_PROXY=...`

Can this fix be adapted to docker compose?
