### ISSUE TITLE
Design polish on SSBC execution screens

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#27587]
The wireframes for the specification execution screens have the required content, but details such as margins, padding, typography need attention before they are ready for development. 

![image](https://user-images.githubusercontent.com/539268/141812439-d692311f-f702-4444-ae62-57b4cd4b4b27.png)

**Comment by eseliger** [comment]
I think this is ok as-is and we can close this? @danielmarquespt @rrhyne

**Comment by danielmarquespt** [comment]
This has been covered in [#32345](https://github.com/sourcegraph/sourcegraph/issues/32345). Yes we can close it :)
