### ISSUE TITLE
query interprets repo revision "@" even after it's space separated

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#27594]
A query like `repo:foo @thing` now interprets the `@thing` part as a repo revision even though it's space separated. This means that some logic after query processing is making incorrect assumptions about whether a part of the query can be used as a revision. Likely a violation on the use of pattern in a repo rev context.

![Screen Shot 2021-11-15 at 10 03 58 AM](https://user-images.githubusercontent.com/888624/141831920-8f62ae75-699a-40ea-acc9-280544d8d1e1.png)

We should only be interpreting `@rev` if it is part of the repo value, not if it's space-separated.

If a user searches for any pattern starting with `@`, then they are likely to get the ugly message above (I ran into this searching for terms starting with `@`).

**Comment by rvantonder** [comment]
OK this is pretty bad, this happens even with `content:@...` so we've made searching any term starting with `@` inexpressible. Pretty sure this is a regression.

**Comment by rvantonder** [comment]
OK it's not that it's inexpressible, it's that we will do a repo search when we shouldn't (we still return results for text matches).

**Comment by benvenker** [comment]
Added to our backlog. @rvantonder any idea on the difficulty of the fix?

**Comment by rvantonder** [comment]
This is a regression introduced by https://github.com/sourcegraph/sourcegraph/pull/27359, so could you have a look @tsenart? I can't obviously tell what went wrong there. Somewhere pattern info data is being passed and used incorrectly I think.

**Comment by rvantonder** [comment]
@benvenker passing this off to @tsenart to have a look first since he's most familiar with the changes in that PR.

**Comment by tsenart** [comment]
@rvantonder: Will take a look tomorrow. Can't really think of the top of my head how this might have changed at all.

**Comment by tsenart** [comment]
Also, our of curiosity, how did you determine that this was a regression introduced by that PR?

**Comment by rvantonder** [comment]
I'm sort of surprised too. But only sort of because this is the search code we're talking about after all 😏 

 I bisected on commits starting at 5559ae0 which didn't have the issue.

**Comment by tsenart** [comment]
@rvantonder: This is because we treat the pattern as a repo filter on repo search.

https://github.com/sourcegraph/sourcegraph/blob/5c54597ea600e3f368f5edffdc5617a0f061a72d/internal/search/run/repository.go#L65-L69

I guess we'd want to do some extra validation there. Thoughts on the proper way to handle this?

**Comment by rvantonder** [comment]
This was fixed in https://github.com/sourcegraph/sourcegraph/pull/27881. The issue didn't autoclose because I had to reopen a PR.
