### ISSUE TITLE
CTA for logged in Cloud users to add code host

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#27604]
Logged-in users without a code host connection should be prompted to add a code host and repositories.

This CTA could replace the in results CTA that converts users to sign-up.

**Comment by vdavid** [comment]
@rrhyne, this one would also make sense as a follow-up project to #27100. But I'll need some specifics and design work first. Can you provide these?

**Comment by rrhyne** [comment]
I think if we used banner type CTAs for too many things, it will lead to banner blindness. 

As such, this will probably be part of https://github.com/sourcegraph/sourcegraph/issues/28322.
