### ISSUE TITLE
Unexpected behavior when clicking: "Options -> Show disabled extensions" 

### ISSUE THREAD

**Issue by KattMingMing** [sourcegraph/sourcegraph#2760]
"Options -> Show disabled extensions" does not show the full list of all disabled extensions instead it shows a "random" subset of extensions.

Below is a screenshot of a large portion of disabled extensions without the `#disabled` filter.

<img width="1792" alt="Screenshot 2019-03-15 09 12 58" src="https://user-images.githubusercontent.com/4897310/54445714-95307b80-4702-11e9-941d-ba42c1df0335.png">

Here's what I see when I click **Show disabled extensions**

<img width="1792" alt="Screenshot 2019-03-15 09 14 05" src="https://user-images.githubusercontent.com/4897310/54445766-b1341d00-4702-11e9-83e6-85483bf7ce71.png">

**Comment by sqs** [comment]
There are 3 states:

- Enabled
- Disabled
- Not set

Disabled does not mean "not enabled". It means "you explicitly disabled it".

This is how VS Code works. We could probably clarify this, but it's not high priority.
