### ISSUE TITLE
VS Code extension opens to incorrect remote

### ISSUE THREAD

**Issue by KattMingMing** [sourcegraph/sourcegraph#2761]
Open on Sourcegraph action of the VS Code extension picks the wrong remote.

It picks the first remote alphabetically instead of "origin"

**Comment by potterbm** [comment]
I ran into this today so I'm going to take a stab at a PR for it if you want to assign me for a bit. [Here's a draft](https://github.com/sourcegraph/sourcegraph/pull/48369)
