### ISSUE TITLE
Revised Sourcegraph deployment and configuration solution

### ISSUE THREAD

**Issue by dan-mckean** [sourcegraph/sourcegraph#27617]
### Plan

Tracking ticket for the work involved in creating and validating a revised deployment solution.

### Goals

- Minimize the chance a customer will need to fork and modify the deployment by using good defaults and adding configurability
- Configuration should be in an isolated area, potentially one file, to reduce merge conflicts
- Allow customers to easily add their own modifications when it does become necessary
- Standardize structure for all resources for easier maintenance

### Tracked issues
- https://github.com/sourcegraph/sourcegraph/issues/27758
- https://github.com/sourcegraph/sourcegraph/issues/27755
- https://github.com/sourcegraph/sourcegraph/issues/27756
- https://github.com/sourcegraph/sourcegraph/issues/27759
- https://github.com/sourcegraph/sourcegraph/issues/27760
- https://github.com/sourcegraph/sourcegraph/issues/27757

**Comment by dan-mckean** [comment]
@caugustus-sourcegraph - taken this off https://github.com/orgs/sourcegraph/projects/214/views/21?filterQuery=owning-team%3ADelivery+, we already have a Helm specific one on there https://github.com/sourcegraph/product-engineering-tracker/issues/88 and this one seems to serve no value.

Just flagging to you in case there's anything useful on here. Or anything else to tidy up?

Or do you think I can close this out?

**Comment by caugustus-sourcegraph** [comment]
@dan-mckean - good to close I think! Everything is covered by https://github.com/sourcegraph/sourcegraph/issues/31821
