### ISSUE TITLE
LogDNA is empty

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#2764]
LogDNA does not show any logs anymore (noticed by @ijsnow and me when we wanted to look at logs): https://app.logdna.com/e63dd10814/logs/view

**Comment by ggilmore** [comment]
https://sourcegraph.slack.com/archives/C07KZF47K/p1549405023705100?thread_ts=1549404662.704900&cid=C07KZF47K

> I am not aware of anyone using logdna. I would not be surprised if we stopped using it by accident (e.g. due to config changes) and nobody fixed it

If you need LogDNA specifically, the file another issue.
