### ISSUE TITLE
Wildcard V2: `<Icon />` Codemod

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#27669]
## Manual migration required to update our code to use the `<Icon />` Wildcard component.

See [Wildcard V2 - Planned work](https://docs.google.com/document/d/1NisbJPiadtt5jQw4vUUYJOr8dD6Urwn5V0mVq2wt6bE/edit#heading=h.g4cw92w3ouhw) for more context

Note: Before doing this, we should check if there is scope for a codemod to automate this migration. If so, the codemod should be implemented and ran before starting work on this issue.

## Acceptance criteria
- [ ] All incorrect usage of the previous pattern has been updated to use the Wildcard component

**Comment by valerybugakov** [comment]
@gitstart-sourcegraph

1. Create a codemod for `<Icon />` migration. It should be pretty similar to the `<Button />` codemod available [here](https://github.com/sourcegraph/codemod/tree/main/packages/transforms/src/buttonElementToComponent).
    - Copy-paste the `<Button />` codemod folder and rename it to the icon codemod.
    - Update it accordingly (import the `Icon` component from the `wildcard` package and remove `icon-inline` classes).
2. Run it over the Sourcegraph codebase. 

The issue should not take more than 8 hours of work to implement. Let us know if you encounter problems early.

**Comment by gitstart-sourcegraph** [comment]
@umpox @valerybugakov  there are some remaining usages of `icon-inline` class (new usages or missed updated on merge), we are going to run the final one but what do you think if we add eslint rule to ban `icon-class` class

**Comment by valerybugakov** [comment]
@gitstart-sourcegraph, good call, let's ban this class
