### ISSUE TITLE
Wildcard V2: `<Link />` Implementation

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#27660]
## Wildcard implementation of the `<Link />` component.

See [Wildcard V2 - Planned work](https://docs.google.com/document/d/1NisbJPiadtt5jQw4vUUYJOr8dD6Urwn5V0mVq2wt6bE/edit#heading=h.g4cw92w3ouhw) for more context

## Acceptance criteria
- [ ] Component is implemented within Wildcard
- [ ] Component has tests
- [ ] Component is accessible
- [ ] Component matches [Figma designs](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Wildcard-Design-System?node-id=908%3A1)

## Implementation details

1. Move [the existing implementation](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/shared/src/components/Link.tsx#L1:1) to [the Wildcard package](https://github.com/sourcegraph/sourcegraph/tree/main/client/wildcard).
2. Extract styles required for the component from Bootstrap to a CSS module:
    - Extract classes from `node_modules/bootstrap/scss/_reboot.scss` related to `Link` to a component CSS module.
    - Merge our [link SCSS variables](https://github.com/sourcegraph/sourcegraph/blob/b1d4bfaa0a580f2c74c643a428c92e7c4893bac6/client/branded/src/global-styles/index.scss#L24-L27) with the newly created CSS module.
2. Create new `Link` story. Render the `Link` component with a regular text like we do [here](https://github.com/sourcegraph/sourcegraph/blob/b1d4bfaa0a580f2c74c643a428c92e7c4893bac6/client/branded/src/global-styles/GlobalStylesStory/TextStory.tsx#L47-L49). 
3. Use [the `<Button />` component](https://github.com/sourcegraph/sourcegraph/tree/main/client/wildcard/src/components/Button) as a blueprint for the new component.

**Comment by umpox** [comment]
@gitstart-sourcegraph Is this still in spec review? It looks like the `<Link />` PR is ready to review: https://github.com/sourcegraph/sourcegraph/pull/28837

Can you confirm if that is the case and move it if so

**Comment by gitstart-sourcegraph** [comment]
@umpox Thanks for checking, it's ready to review now
