### ISSUE TITLE
Wildcard V2: `<ButtonLink />` Tracking issue

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#27670]
### Plan

Tracking Issue for individual `<ButtonLink />` component

### Tracked issues

@unassigned: __3.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/27606  __3.00d__
  - [x] (🏁 57 days ago) https://github.com/sourcegraph/sourcegraph/issues/27671  __1.00d__
  - [x] (🏁 43 days ago) https://github.com/sourcegraph/sourcegraph/issues/27672  __2.00d__

Completed: __3.00d__
- [x] (🏁 57 days ago) https://github.com/sourcegraph/sourcegraph/issues/27671  __1.00d__
- [x] (🏁 43 days ago) https://github.com/sourcegraph/sourcegraph/issues/27672  __2.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
- :shipit: Pull Request

**Comment by taylorsperry** [comment]
This is just one `<ButtonLink />` component, correct?
