### ISSUE TITLE
Wildcard V2: `<Typography />` Manual migration

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#27677]
## Manual migration required to update our code to use the `<Typography />` Wildcard component.

See [Wildcard V2 - Planned work](https://docs.google.com/document/d/1NisbJPiadtt5jQw4vUUYJOr8dD6Urwn5V0mVq2wt6bE/edit#heading=h.g4cw92w3ouhw) for more context

Note: Before doing this, we should check if there is scope for a codemod to automate this migration. If so, the codemod should be implemented and ran before starting work on this issue.

## Acceptance criteria
- [ ] All incorrect usage of the previous pattern has been updated to use the Wildcard component

**Comment by valerybugakov** [comment]
Hey @gitstart-sourcegraph, let's start tackling this issue. We can split PRs required to close this issue by Typography components — one PR per Typography component migration. Let's with `H1-H6` tags:

```tsx
<h1>Hello</h1>
```

Should be migrated to

```tsx
import { Typography } from '@sourcegraph/wildcard'

<Typography.H1>Hello</Typography.H1>
```

**Comment by gitstart-sourcegraph** [comment]
## Related Iissues
https://github.com/sourcegraph/sourcegraph/issues/35039
