### ISSUE TITLE
Wildcard V2: `<Card />` Implementation

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#27679]
## Wildcard implementation of the `<Card />` component.

See [Wildcard V2 - Planned work](https://docs.google.com/document/d/1NisbJPiadtt5jQw4vUUYJOr8dD6Urwn5V0mVq2wt6bE/edit#heading=h.g4cw92w3ouhw) for more context

## Acceptance criteria
- [ ] Component is implemented within Wildcard
- [ ] Component has tests
- [ ] Component is accessible
- [ ] Component matches [Figma designs](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Wildcard-Design-System?node-id=908%3A1)

## Implementation details

1. Extract styles required for the component from Bootstrap to a CSS module:
    - Figure out what classes do we use from `node_modules/bootstrap/scss/_card.scss`.
    - Create a CSS module with classes that we need from `node_modules/bootstrap/scss/_card.scss` and variables from `client/branded/src/global-styles/card.scss`.
    - For top-level classes create small components that incorporate required styles, e.g., `CardTitle` for `.card-title`.
2. Move `client/branded/src/global-styles/GlobalStylesStory/CardsStory.tsx` ([link](https://storybook.sgdev.org/?path=/story/branded-global-styles--cards)) to the new component folder and update it to match other stories in the Wildcard package. 
3. Use [the `<Button />` component](https://github.com/sourcegraph/sourcegraph/tree/main/client/wildcard/src/components/Button) as a blueprint for the new component.
4. Component API:

```tsx
<Card>
  <CardHeader>Featured</CardHeader>
  <CardBody>
     <CardTitle>My cool title</CardTitle>
     <CardSubtitle>Subtitle</CardSubtitle>
     <CardText>Body goes here</CardText>
  </CardBody>
</Card>
```

**Comment by raph941** [comment]
@valerybugakov 
1. Based on the [Figma design here](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Wildcard-Design-System?node-id=1172%3A285), it shows how we are to render the `title` and `subtitle` properties. however, the component API as shown in description specifies that user can provide a `cardHeader` property.
**Qusestion**: How should the header prop be rendered, perhaps should be rendered [like this](https://getbootstrap.com/docs/4.3/components/card/#header-and-footer)?
2. The switch buttons as shown in design, are they to be passed in as a property of the card or are they built in parts of the card component.

**Comment by gitstart-sourcegraph** [comment]
@valerybugakov

Based on the [Figma design here](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Wildcard-Design-System?node-id=1172%3A285), it shows how we are to render the title and subtitle properties. however, the component API as shown in description specifies that user can provide a cardHeader property.
**Qusestion**: How should the header prop be rendered, perhaps should be rendered as default [like this](https://getbootstrap.com/docs/4.3/components/card/#header-and-footer)?
The switch buttons as shown in design, are they to be passed in as a property of the card or are they built in parts of the card component.

**Comment by gitstart-sourcegraph** [comment]
Hello @valerybugakov point to note about the flow for interactive cards.
 Default State => border-width: 1px
 Hover State => border-width: 2px
 Focus State => border-width: 1px;
 
 This would generally cause a slight jump / shink effect when user hovers / focus on (generally transitioning between these states). kindly confirm if this is the expected behaviour.

**Comment by valerybugakov** [comment]
@gitstart-sourcegraph, let's stick with the current behavior if the solution is not apparent. We can revisit such improvements after the initial implementation. It would be helpful to have a note about it in the PR description or the source code (if possible), so we can follow up later.
