### ISSUE TITLE
Wildcard V2: `<Typography />` Lint rule

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#27676]
## Eslint rule to enforce the `<Typography />` Wildcard component.

See [Wildcard V2 - Planned work](https://docs.google.com/document/d/1NisbJPiadtt5jQw4vUUYJOr8dD6Urwn5V0mVq2wt6bE/edit#heading=h.g4cw92w3ouhw) for more context

## Acceptance criteria
- [ ] Eslint rule is added to enforce usage
- [ ] Eslint rule is implemented in the Sourcegraph repository

**Comment by valerybugakov** [comment]
Will be closed as a part of https://github.com/sourcegraph/sourcegraph/issues/27677
