### ISSUE TITLE
Wildcard V2: `<ButtonLink />` Implementation

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#27671]
## Wildcard implementation of the `<ButtonLink />` component.

See [Wildcard V2 - Planned work](https://docs.google.com/document/d/1NisbJPiadtt5jQw4vUUYJOr8dD6Urwn5V0mVq2wt6bE/edit#heading=h.g4cw92w3ouhw) for more context

## Acceptance criteria

- [ ] Component is implemented within Wildcard
- [ ] Component has tests
- [ ] Component is accessible
- [ ] Component matches [Figma designs](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Wildcard-Design-System?node-id=908%3A1)

## Implementation details

1. Add new `<ButtonLink />` to the Wildcard package.
    - See existing implementation [here](https://github.com/sourcegraph/sourcegraph/blob/main/client/shared/src/components/LinkOrButton.tsx)
    - Example of usage [here](https://github.com/sourcegraph/sourcegraph/blob/63757cf2584e584873a02cb8ad6e69b21ad6f5a2/client/web/src/repo/actions/GoToPermalinkAction.tsx#L82-L90).
2. Create a basic Storybook story that shows component usage.
3. Use [the `<Button />` component](https://github.com/sourcegraph/sourcegraph/tree/main/client/wildcard/src/components/Button) as a blueprint for the new component.

**Comment by gitstart-sourcegraph** [comment]
@umpox Could you take a look at this question?
