### ISSUE TITLE
Wildcard V2: Implementation of typography components: `Text`, `Label`, `Code`, and `H1`-`H6`

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#27674]
## Wildcard implementation of typography components: `Text`, `Label`, `Code`, and `H1`-`H6`

See [Wildcard V2 - Planned work](https://docs.google.com/document/d/1NisbJPiadtt5jQw4vUUYJOr8dD6Urwn5V0mVq2wt6bE/edit#heading=h.g4cw92w3ouhw) for more context

## Why

> **Unlimited component variations because of the globally styled HTML elements**. Because we rely more on HTML structure than on components in some places (e.g., typography), developers need to keep in mind relative rules applied to certain elements in global styles. With a strict design system, we explicitly defined the limited number of component variations. Now we can move away from the globally styled HTML elements and rely more on strictly styled React components.

See [the Styling UI guidelines RFC](https://docs.google.com/document/d/15PyMY7cZ-8_UpLFMA66L4DkB2d3Ve37gia2SxLVnE7c/edit#) for more details.

## Acceptance criteria

- [ ] Component is implemented within Wildcard
- [ ] Component is added to Storybook
- [ ] Component has tests
- [ ] Component is accessible
- [ ] Component matches [text mockups in Figma](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Wildcard-Design-System?node-id=5601%3A65477)

## Implementation details

Suggestions for every component:

1. Use styles defined in `client/branded/src/global-styles/typography.scss` and merge them with Bootstrap styles `node_modules/bootstrap/scss/_type.scss` required for these elements.  
2. Feel free to drop unused CSS rules based on our [text mockups](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Wildcard-Design-System?node-id=5601%3A65477).
3. Consider extracting and extending base interfaces such as `TypographyProps`.

### 1. Headings

Create components for each HTML heading from `h1` to `h6`: e.g., `<H1 />`.

Each should have `props` typed as follows:

```tsx
interface H1Props extends React.HTMLAttributes<HTMLHeadingElement> {
    as?: React.ElementType;
    alignment?: 'left' | 'center' | 'right';
    mode?: 'default' | 'single-line' | 'break-word';
}
```

Check out the discussion in comments to learn about `alignment` and `mode`.

### 2. Text

Create `<Text />` component with the following API:
```tsx
interface TextProps extends React.HTMLAttributes<HTMLParagraphElement> {
    size?: 'small' | 'base';
    weight?: 'regular' | 'medium' | 'bold';
    as?: React.ElementType;
    alignment?: 'left' | 'center' | 'right';
    mode?: 'default' | 'single-line' | 'break-word';
}
```

- The `<p />` element tag should be used internally by default. 
- Small styles should use only `rem` value in `font-size` rule instead of the current `calc(min(...))` logic.
- `<strong /> ` element tag should be used in case of `weight="bold"`.

Check out the discussion in comments to learn about `alignment` and `mode`.

### 3. Label

Create `<Label />` component with the following API:
```tsx
interface LabelProps extends React.HTMLAttributes<HTMLLabelElement> {
    size?: 'small' | 'base';
    weight?: 'regular' | 'medium' | 'bold';
    alignment?: 'left' | 'center' | 'right';
    mode?: 'default' | 'single-line' | 'break-word';
    isUnderline?: boolean;
    isUppercase?: boolean;
}
```

- The `<label />` element tag should be used internally. 

### 4. Code

Create `<Code />` component with the following API:
```tsx
interface CodeProps extends React.HTMLAttributes<HTMLElement> {
    size?: 'small' | 'base';
    weight?: 'regular' | 'medium' | 'bold';
}
```

**Comment by oleggromov** [comment]
A few questions and thoughts about the API:
1. what is the difference in usage between `<Label />` and `<Text />`
2. `alignment` to adjust `text-align` 
2. based on previous experience with UI kits I'd suggest adding "single line" and "break-word" modes. Maybe as a `mode` prop that would take:
    - `'default`' - no additional styles
    - `'single-line'` - `overflow: hidden; text-overflow: ellipsis; white-space: nowrap` so that text becomes a single line that takes 100% width
    - `'break-word'` or `'break-all'` to make breaking long words in the middle possible so that they don't cause overflow

Let me know what you think @umpox and @valerybugakov.

**Comment by valerybugakov** [comment]
@oleggromov,

1. `<Label />` uses `<label />` and a different set of variants defined by [our design system](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Wildcard-Design-System?node-id=5601%3A65477). 
2. Sounds good to me. 
3. Agree that we can add it because it's a common use case. 👍

**Comment by oleggromov** [comment]
@valerybugakov updated description. Should be ready for pick-up now.
