### ISSUE TITLE
Tech debt: address follow-ups from PR #2644

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#2768]
~- [ ] Replace size prop with CSS classes https://github.com/sourcegraph/sourcegraph/pull/2644#discussion_r265865424~
  - Reviewing this further, this seems like it'd be more annoying than helpful. All the existing mdi-icons accept a size property. If we wanted to be consistent with those, I suppose we could wrap all of the icon components in another component that translates from size classes into actual size numbers, but that seems of limited value for now.
- [x] Add e2e test for external services (or unit test if you can) (https://github.com/sourcegraph/sourcegraph/pull/2644#pullrequestreview-214953547)
- [x] Add snapshot test for `SiteAdminExternalServiceForm` (https://github.com/sourcegraph/sourcegraph/pull/2644#pullrequestreview-214953547)
- [x] The /site-admin/external-services/add page should be /new not /add for consistency with http://localhost:3080/organizations/new (which is called /new in the URL). Add redirects for this.
- [x] For newly initialized instances with no repos and no external services, the global alert (in NeedsRepositoryConfigurationAlert) should link to the /site-admin/external-services/new page now that it exists (not just /site-admin/external-services).

**Comment by felixfbecker** [comment]
>  All the existing mdi-icons accept a size property.

Yeah but all elements also accept a `style` prop and we're not using those either. Sizing is a CSS concern, just like all other styles.
