### ISSUE TITLE
Wildcard V2: `<Menu />, <MenuItem />` Manual migration

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#27701]
## Manual migration required to update our code to use the `<Menu />, <MenuItem />` Wildcard component.

See [Wildcard V2 - Planned work](https://docs.google.com/document/d/1NisbJPiadtt5jQw4vUUYJOr8dD6Urwn5V0mVq2wt6bE/edit#heading=h.g4cw92w3ouhw) for more context

Note: Before doing this, we should check if there is scope for a codemod to automate this migration. If so, the codemod should be implemented and ran before starting work on this issue.

## Implementation
1. Migrate all usage of the `@reach/menu-button` components to use these styled wrapper components.
2. Migrate all usage of the `Dropdown` | `DropdownMenu` | `DropdownItem` | `DropdownToggle` Reactstrap components from this list:
- SearchContextOwnerDropdown.tsx
- ExtensionRegistrySidenav.tsx
- MenuNavItem.tsx
- UserNavItem.tsx
- NavDropdown.tsx
- RepoHeader.tsx
- SearchNotebookPageHeaderActions.tsx
- ButtonDropdownCta

See this PR: https://github.com/sourcegraph/sourcegraph/pull/28979 for the implementation of these components

## Acceptance criteria
- [ ] All incorrect usage of the previous pattern has been updated to use the Wildcard component

**Comment by valerybugakov** [comment]
`SearchContextOwnerDropdown` should be migrated to a new component built on top of [the Listbox component](https://reach.tech/listbox/). The menu component [is not the right tool for the job](https://github.com/reach/reach-ui/issues/350#issuecomment-555866822).

A similar statement applies to the `SearchUserAutocomplete.tsx`, which should be migrated to the `Compobox` component that we do not have in the Wildcard at the moment.

These two remaining `reactstrap` `Dropdown` usages will be migrated in follow-up PRs.
