### ISSUE TITLE
Wildcard V2: `<Panel />` Implementation

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#27709]
## Wildcard implementation of the `<Panel />` component.

See [Wildcard V2 - Planned work](https://docs.google.com/document/d/1NisbJPiadtt5jQw4vUUYJOr8dD6Urwn5V0mVq2wt6bE/edit#heading=h.g4cw92w3ouhw) for more context

## Implementation details

This component should function similarly to the panel we use in Sourcegraph for file references ([link](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/wildcard/.eslintrc.js?L5:8#tab=references)) ([storybook](https://storybook.sgdev.org/?path=/story/branded-panel--simple)):

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/9516420/144616277-30244443-addf-425a-b211-1ae342d0ebfc.png)

</details>

However, it should be abstract. The component shouldn't assume any content that is provided, it should just be concerned with creating a fixed panel with resize functionality. For example, here's how the component might look on its own:

Note: The panel should be fixed to the bottom of the screen

<details>
<summary>Example</summary>

![image](https://user-images.githubusercontent.com/9516420/145840270-3062d601-50cb-4ccc-b870-167e6fbb726a.png)

</details>

An example of how this might look from a code point of view would be:
```
<Panel>
   {children}
</Panel>
```

## Acceptance criteria
- [ ] Component is implemented within Wildcard
- [ ] Component is tested
- [ ] Component is accessible
- [ ] Component matches [Figma designs](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Wildcard-Design-System?node-id=908%3A1)
- [ ] Component has relevant Storybook story

**Comment by gitstart-sourcegraph** [comment]
@umpox We have some questions for `wildcard/Panel` component, could you help to clear

1. Should we make it resizable (up/down for `bottom` position and left/right for `side` position)?
2. The `side` position option means to left side only or both left and right sides?
3. The `close` button position should be fixed .i.e it would overlap UI of children, children have to adjust their UI to not render UI under that close button, is that right?

**Comment by umpox** [comment]
@gitstart-sourcegraph

After further thinking, we only need the `bottom` position right now. Let's avoid complicating this until we need other variations. I've updated the ticket.

1. Panel should only be fixed to the `bottom` position and it should be resizable.
2. No longer using `side` position
3. I think this could cause problems in the current solution. For now, let's just allow the consumer to provide just the `children`. They can provide their own close button to toggle the panel themselves. If needed, we can iterate on this later to make the close button integrated to this component

**Comment by umpox** [comment]
@gitstart-sourcegraph

After further thinking, we only need the `bottom` position right now. Let's avoid complicating this until we need other variations. I've updated the ticket.

1. Panel should only be fixed to the `bottom` position and it should be resizable.
2. No longer using `side` position
3. I think this could cause problems in the current solution. For now, let's just allow the consumer to provide just the `children`. They can provide their own close button to toggle the panel themselves. If needed, we can iterate on this later to make the close button integrated to this component

**Comment by umpox** [comment]
@gitstart-sourcegraph I've just noticed that we also have the [`Resizable`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@contractors/SG-27709/-/blob/client/shared/src/components/Resizable.tsx?utm_source=VSCode-1.4.0#L1:36) component in the codebase. Do you think we could (in a follow-up PR) implement the same logic? It is quite similar to this implementation, but it is an old class component so it would be good to move logic into this hook.

The additional features I see from a quick look:
- [Size changes are debounced for improved performance](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@contractors/SG-27709/-/blob/client/shared/src/components/Resizable.tsx?utm_source=VSCode-1.4.0#L91:49)
- [Holding down the shift key will let you resize in increments](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@contractors/SG-27709/-/blob/client/shared/src/components/Resizable.tsx#L143:25)
- [It supports `right` and `left` alignment too](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@contractors/SG-27709/-/blob/client/shared/src/components/Resizable.tsx#L16:14). Apologies I said I didn't think we needed this before, but it looks like it'll be worthwhile to add now.

If we can implement the same features for this `Panel` component we can remove `Resizable` when we do the migration for this work.
