### ISSUE TITLE
Having to "Enable Sourcegraph on this site" is very non-obvious, makes it hard to rollout to multiple users

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#2770]
When installing the Sourcegraph Chrome extension, you have to right click and `Enable Sourcegraph on this site`. This has multiple problems which are a major hurdle to making use of and rolling out the Chrome extension:

1. It is not a part of our on-boarding flow for the Chrome extension, which makes it extremely non-obvious. For example, clicking the Sourcegraph toolbar icon shows `Connected` -- "but the extension doesn't work on my code host!"
2. We can roll out the Chrome extension to an entire organization via Google Apps, but users will still have to `Enable Sourcegraph on this site`. Our onboarding flow should take this into consideration as well.

**Comment by slimsag** [comment]
@lguychard Can we prioritize this in 3.3?

**Comment by lguychard** [comment]
Yes.

**Comment by lguychard** [comment]
After discussing this with @sqs yesterday:
- We actually used to display permissions notifications in the options page of the extension, but we stopped doing it when we simplified the options page.
- We should prioritize improving the quality on github over onboarding work for other code hosts.
- In any case, this should be made more discoverable in the docs, and outdated docs should be fixed: #2835

**Comment by lguychard** [comment]
Closing this, docs change will be all we do for this in 3.3. Potential future work on the browser extension onboarding flow to be tracked in #2799
