### ISSUE TITLE
Wildcard V2: `<Checkbox />` migration

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#27719]
## Problem statement

Migration is required to update our code to use the `<Checkbox />` Wildcard component. See [Wildcard V2 - Planned work](https://docs.google.com/document/d/1NisbJPiadtt5jQw4vUUYJOr8dD6Urwn5V0mVq2wt6bE/edit#heading=h.g4cw92w3ouhw) for more context.

## Success criteria

All occurrences of the `<input type="checkbox" />` or `<Input type="checkbox" />` element are replaced with the `<Checkbox />` Wildcard component.

## Time estimate

- The migration should take **8 hours** at maximum. Ping the reviewer in the spec pull request if time-consuming changes are required.

**Comment by gitstart-sourcegraph** [comment]
Issue paused. due to blocker on dependency. To be continued once [comment here](https://github.com/sourcegraph/sourcegraph/issues/33267#issuecomment-1088532501) is resolved

**Comment by umpox** [comment]
@valerybugakov I think now that https://github.com/sourcegraph/sourcegraph/pull/33414 has been merged, we should be able to continue this migration. LMK if you disagree.

It means we can now render a `<Checkbox />` and link it to an external label using `aria-labelledby`. This should solve some edge cases where we require a specific order of elements.

@gitstart-sourcegraph I think there might still be _some_ UI changes, so it's worth double checking that the UI is still the same after the migration. I don't expect that any UI changes will be too significant, so we should be able to solve them ourselves with a small amount of CSS
