### ISSUE TITLE
Wildcard V2: `<FeedbackPrompt />` Tracking issue

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#27711]
### Plan

Tracking Issue for individual `<FeedbackWidget />` component

### Tracked issues

@gitstart-sourcegraph: __2.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/27606  __2.00d__
  - [x] (🏁 31 days ago) https://github.com/sourcegraph/sourcegraph/issues/27712  __1.00d__
  - [x] (🏁 37 days ago) https://github.com/sourcegraph/sourcegraph/issues/27713  __1.00d__

Completed: __2.00d__
- [x] (🏁 37 days ago) https://github.com/sourcegraph/sourcegraph/issues/27713  __1.00d__
- [x] (🏁 31 days ago) https://github.com/sourcegraph/sourcegraph/issues/27712  __1.00d__

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.5nwl5fv52ess)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal
- :shipit: Pull Request

**Comment by taylorsperry** [comment]
`<FeedbackWidget />` is now `<FeedbackPrompt />`, correct?

**Comment by umpox** [comment]
@taylorsperry That's correct! I'll update these issues
