### ISSUE TITLE
Wildcard V2: `<Tabs />` Manual migration

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#27734]
## Manual migration required to update our code to use the `<Tabs />` Wildcard component.

See [Wildcard V2 - Planned work](https://docs.google.com/document/d/1NisbJPiadtt5jQw4vUUYJOr8dD6Urwn5V0mVq2wt6bE/edit#heading=h.g4cw92w3ouhw) for more context

Note: Before doing this, we should check if there is scope for a codemod to automate this migration. If so, the codemod should be implemented and ran before starting work on this issue.

## Context
1. We have the tabs component: [Storybook](https://storybook.sgdev.org/?path=/story/wildcard-tabs--tabs-story) and [Code](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/wildcard/src/components/Tabs/Tabs.tsx?utm_source=VSCode-1.4.0#L15:1). This is mainly a wrapper around `@reach/tabs`
2. We have [quite a bit of usage](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+%40reach/tabs&patternType=literal) of the `@reach/tabs` component.

## Implementation
1. Migrate all usage of `@reach/tabs` imports to use the Wildcard `Tabs` components
2. Remove the global `@reach/tabs` style import [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/branded/src/global-styles/index.scss?utm_source=VSCode-1.4.0#L116:5), move it to the Wildcard `Tabs` module.scss file

## Acceptance criteria
- [ ] All incorrect usage of the previous pattern has been updated to use the Wildcard component

**Comment by oleggromov** [comment]
Completed with https://github.com/sourcegraph/sourcegraph/pull/29920
