### ISSUE TITLE
Observability

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#27761]

**Comment by kstretch9** [comment]
@taylorsperry is there a description floating around we can add to this issue?

**Comment by taylorsperry** [comment]
[RFC 496: Continuous integration observability](https://github.com/sourcegraph/sourcegraph/pull/27964) and the associated [Tracking Issue](https://github.com/sourcegraph/sourcegraph/issues/25768) describe our efforts around Observability and the progress we've made over the quarter. 

We'll continue much of this work (with more specific definitions of success) in FY2023.
