### ISSUE TITLE
Autoprefixer does not add prefixes for background-image in all situations

### ISSUE THREAD

**Issue by francisschmaltz** [sourcegraph/sourcegraph#2776]
Autoprefixer does not add prefixes for gradients when using both a gradient and a URL image on the same `background-image:` rule.

See https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/shared/src/components/activation/ActivationDropdown.scss#L12:27

**Comment by felixfbecker** [comment]
Autoprefixer is capable of adding them:

![image](https://user-images.githubusercontent.com/10532611/54466423-f117f600-473c-11e9-973d-52ee27e82d56.png)

If they are not added, that means they are supported in all the browsers we target and they should be removed, or our browserlist config should be corrected (in the future, please follow these steps).

![image](https://user-images.githubusercontent.com/10532611/54466492-376d5500-473d-11e9-90a1-a6b16fe1cbc1.png)

https://caniuse.com/#feat=css-gradients

**Comment by felixfbecker** [comment]
Closing unless there's evidence Autoprefixer doesn't add them despite our browserslist saying it should
