### ISSUE TITLE
Install and upgrade testing using rendered helm manifests

### ISSUE THREAD

**Issue by caugustus-sourcegraph** [sourcegraph/sourcegraph#27760]
Using the helm prototype, evaluate the user experience when using rendered helm manifests to manage the installation and upgrade of Sourcegraph. This should be similar to the current experience for https://github.com/sourcegraph/deploy-sourcegraph base manifests but determine if there are new limitations or changes in maintainability.

Evaluation should consider the [documented use cases](https://github.com/sourcegraph/sourcegraph/issues/27758).

**Comment by michaellzc** [comment]
## Test plan

WIP

**Comment by michaellzc** [comment]
The experience is quite good or indifferent comparing to the `./kubectl-apply-all.sh` we have in `deploy-sourcegraph`.
