### ISSUE TITLE
Alter code monitors pages to correct create button in header

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#27776]
The code monitor create code monitor button should:

1. Be labeled "Create code monitor"
2. Should appear on both the create code monitor page and getting started page at all times
3. In the case of an empty code monitor page, the empty state button should be removed. 

Figma of problem areas and corrections:
https://www.figma.com/file/ZzWVJSMGKYDMLbfIAqWCvX/Consistency-of-primary-actions?node-id=14%3A951

**Comment by rrhyne** [comment]
@benvenker this is a fairly small issue, any chance we can get it done in the next sprint or two?

**Comment by benvenker** [comment]
I think we can have @limitedmage add it the frontend work she'll be starting soon for the new Code monitor updates.

**Comment by lguychard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Search-Product-61302e38f801dc0012e2e050/issues/sourcegraph/sourcegraph/27776?planning-poker) with ZenHub @benvenker @camdencheek @limitedmage
