### ISSUE TITLE
Simplify the `AuthzQueryConds` policy if at all possible

### ISSUE THREAD

**Issue by jplahn** [sourcegraph/sourcegraph#27796]
The AuthzQueryConds is fairly complex and subtle. Joe Chen and I spent quite a bit of time double-checking our work today, making sure all the parentheses were in the right spots and so on. It’s tricky and super easy to make a mistake when tweaking the logic.

Substantially simplifying what we have may be difficult (or impossible) given the dynamic needs of the query, but it’s worth investigating.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam-and-admin-experience - the "team/iam-admin-experience" label was applied to this issue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.
