### ISSUE TITLE
Improve test coverage of repo-updater

### ISSUE THREAD

**Issue by jplahn** [sourcegraph/sourcegraph#27803]
**This is a discovery issue.**

Functions like Sync and NewDiff in the repo-updater seem to have no unit tests. These seem like critical functions to ensure the stability of repo-updater. 

As a starting point for this issue, we should spend some time finding out more about the test coverage of repo-updater and create sub tasks based on different areas that need testing.

The testing strategy, that is unit tests vs end-to-end (or both) is left as an exercise for the discovery phase.

**Comment by ryanslade** [comment]
I'm going to close this as it's going to be covered by planned work to improve testing in general.

cc @varsanojidan
