### ISSUE TITLE
GitHub rate limit remaining dropping quickly

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#2781]
See https://sourcegraph.slack.com/archives/C0J618TTM/p1552693706001000

![image](https://user-images.githubusercontent.com/1387653/54467716-24aa4e80-4744-11e9-976f-6203cf542c08.png)

From https://prometheus.sgdev.org/graph?g0.range_input=2h&g0.expr=src_github_rate_limit_remaining%7Bresource%3D%22core%22%7D&g0.tab=0

Red box shows where the rate limit dropped precipitously.

Alert https://app.opsgenie.com/alert/detail/3c84f66a-ef83-4be2-b559-4e95d4f5e57a-1552693551936/details

- Image updated in https://github.com/sourcegraph/deploy-sourcegraph-dot-com/commit/3e0eae5932ca037d172c4e0b8fd2181c0da0d4b3
- Rolled back in https://github.com/sourcegraph/deploy-sourcegraph-dot-com/commit/625c313939845508f30c3c799c76601d024643a4

**Comment by tsenart** [comment]
Is there a way to find out which Git commit a given Docker image sha256 maps to?

**Comment by chrismwendt** [comment]
@tsenart Here's a Ruby script that'll do the trick:

<details><pre>
require 'buildkit'
require 'json'

client = Buildkit.new(token: ENV['BUILDKITE_TOKEN'])
needle = '31b3e1a9decc3ad5019b8716b2544948cae0429b64537f4b0bdbcfffc449de13'
cache_file = 'cache.jsonl'
cache = {}
if File.file?(cache_file)
  cache = File.read(cache_file).split("\n").map{|e| [JSON.parse(e)['commit'], JSON.parse(e)['line']]}.to_h
end
page = 1
while true
  client.pipeline_builds('sourcegraph', 'sourcegraph', { state: 'passed', branch: 'master', page: page }).each { |b|
    if !cache.key?(b.commit)
      j = b.jobs.select{ |j| j.command && j.command.include?('cmd/gitserver/build.sh') }[0]
      line = client.job_log('sourcegraph', 'sourcegraph', b.number, j.id).content.split(/(\r\n|\r|\n)/).select{|line|line.include?('sha256')}[0]
      cache[b.commit] = line
      File.write(cache_file, cache.map{ |commit, line| {'commit' => commit, 'line'=> line}.to_json }.join("\n"))
    else
      line = cache[b.commit]
    end
    puts("Commit: https://github.com/sourcegraph/sourcegraph/commit/#{b.commit}")
    puts("Build: https://buildkite.com/sourcegraph/sourcegraph/builds/#{b.number}")
    puts("gitserver image: #{line}")
    puts
    if line.include?(needle)
      puts('Found it!')
      exit 0
    end
  }
  page = page + 1
end
</pre></details>

- Commit: https://github.com/sourcegraph/sourcegraph/commit/cc71f6fc1e2ccbcc4d750d2febe4e1f1c2aea014
- Build: https://buildkite.com/sourcegraph/sourcegraph/builds/28666
- gitserver image: 28666_2019-03-01_cc71f6f: digest: sha256:31b3e1a9decc3ad5019b8716b2544948cae0429b64537f4b0bdbcfffc449de13 size: 1994

...

- Commit: https://github.com/sourcegraph/sourcegraph/commit/a234998c1a230438c63b5b2c3354d7ba7613c5dc
- Build: https://buildkite.com/sourcegraph/sourcegraph/builds/29494
- gitserver image: 29494_2019-03-15_a234998: digest: sha256:8d434226ef04b1aec770b742171608d38a8a22de596cfddc2cca6afb707be538 size: 1994

**Comment by tsenart** [comment]
Well, it seems like it was included in the name of the image all along. :-)

**Comment by tsenart** [comment]
Did that drop correlate with a deploy? Do we have a way to graph deploy events in Prometheus?

**Comment by tsenart** [comment]
Another question: How did we came to the conclusion that git-server is the culprit?

**Comment by chrismwendt** [comment]
> Did that drop correlate with a deploy?

The rate limit remaining started dropping ~1h after the newer gitserver image was deployed

- 3:49 PM Pacific, deployed https://buildkite.com/sourcegraph/deploy-sourcegraph-dot-com/builds/2376#1d225349-0d6d-46de-a870-fc5ce02570f7
- 4:45 PM Pacific, alerted https://app.opsgenie.com/alert/detail/3c84f66a-ef83-4be2-b559-4e95d4f5e57a-1552693551936/details

> Do we have a way to graph deploy events in Prometheus?

I looked a bit, but couldn't find a way to do it directly in Prometheus. I'm not sure if it's even possible considering that Prometheus is pull-based https://prometheus.io/blog/2016/07/23/pull-does-not-scale-or-does-it/#prometheus-is-not-an-event-based-system

Grafana supports [annotations](http://docs.grafana.org/reference/annotations/).

> How did we come to the conclusion that git-server is the culprit?

`@nicksnyder` [asked about it in Slack](https://sourcegraph.slack.com/archives/C0J618TTM/p1552693965001400?thread_ts=1552693706.001000&cid=C0J618TTM) and I remembered that I had recently bumped the version.

**Comment by tsenart** [comment]
> The rate limit remaining started dropping ~1h after the newer gitserver image was deployed

Was git-server the only new image that got deployed? Are we sure git-server is what's consuming the rate-limit?

**Comment by chrismwendt** [comment]
I'm not 100% sure. A few other images got deployed a bit earlier, but gitserver was the closest to the incident https://github.com/sourcegraph/deploy-sourcegraph-dot-com/commits/release

**Comment by tsenart** [comment]
To the extent of my knowledge, git-server doesn't talk to github.com, either directly or through github-proxy. Is my understanding wrong here?

**Comment by chrismwendt** [comment]
Determining the commit associated with an image should be much easier now that https://github.com/sourcegraph/sourcegraph/pull/2806 is merged.

**Comment by nicksnyder** [comment]
@ggilmore proposed re-deploying the latest gitserver to confirm/deny if it is the source of the observed issue.

**Comment by ggilmore** [comment]
#2806 will not help with this situation since these images pre-date that

**Comment by chrismwendt** [comment]
The alert [fired again](https://app.opsgenie.com/alert/detail/de72dcb5-16e8-4579-9b48-a33c938315bb-1552945854251/details) without any changes to gitserver today, so it must not be gitserver after all. My apologies for the confusion. I'm going to change the title of this issue.

**Comment by nicksnyder** [comment]
Let's re-deploy the latest gitserver then.

**Comment by chrismwendt** [comment]
The graph looks nearly identical to last time:

![image](https://user-images.githubusercontent.com/1387653/54566520-4eef4c80-498e-11e9-85fe-24232076b9fd.png)

**Comment by chrismwendt** [comment]
Re-deploying the latest gitserver in https://github.com/sourcegraph/deploy-sourcegraph-dot-com/commit/ca9169429ee2524445644fc9ef8ba1189eb7134b

**Comment by nicksnyder** [comment]
> To the extent of my knowledge, git-server doesn't talk to the github.com API, either directly or through github-proxy. 

This is my mental model too, but given the evidence that we had at the time rolling back the most recent deployment prior to the issue was a reasonable course of action.

> It only does raw git fetches. Do those count towards the rate limit?

No.

@tsenart My mental model would be to investigate repo-updater, github-proxy, and which codepaths cause GitHub api requests.

**Comment by attfarhan** [comment]
We switched the GitHub Public external service's access token on Sourcegraph.com to eliminate the possibility that something else was using that token.

But, we also figured out that rate limit is associated with the user, not token, so it's possible that usage of another token associated with the bot account is eating up our rate limit rapidly. 

There are 3 tokens on that account that have been used in the last week:
- the sourcegraph.com access token (public repo access)
- "sgbot - prod - default namespace" (repo access)
- "sourcegraph-vscode semantic-release" (repo access)

**Comment by chrismwendt** [comment]
sgbot also [hits the GitHub API](https://github.com/sourcegraph/infrastructure/blob/39395138cffba65176cafe8ab9d5473b42a1f30b/docker-images/sgbot/main.go#L90), but it's [throttled to 1 request every 3s](https://github.com/sourcegraph/deploy-sourcegraph-dot-com/blob/ca9169429ee2524445644fc9ef8ba1189eb7134b/configure/sgbot/sgbot.Deployment.yaml#L33) permitting [bursts of 20](https://github.com/sourcegraph/infrastructure/blob/39395138cffba65176cafe8ab9d5473b42a1f30b/docker-images/sgbot/vendor/github.com/sourcegraph/maintainerbot/sgbot.go#L126), so that doesn't explain the drop. I don't see increased [log output](https://console.cloud.google.com/logs/viewer?interval=CUSTOM&project=sourcegraph-dev&minLogLevel=0&expandAll=false&timestamp=2019-03-19T01:15:23.040000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22container%22%0Aresource.labels.cluster_name%3D%22dot-com%22%0Aresource.labels.namespace_id%3D%22default%22%0Aresource.labels.project_id%3D%22sourcegraph-dev%22%0Aresource.labels.zone:%22us-central1-f%22%0Aresource.labels.container_name%3D%22sgbot%22%0Aresource.labels.pod_id:%22sgbot-%22&scrollTimestamp=2019-03-18T20:40:21.433805560Z&dateRangeStart=2019-03-18T20:30:23.292Z&dateRangeEnd=2019-03-18T20:40:23.292Z) during the time of the drop, either.

**Comment by chrismwendt** [comment]
sgbot appears to be the culprit (see my updated comment above). The rate limit is shared among all access tokens for the given user, so usage by sgbot was eating into the rate limit remaining for Sourcegraph.com.

@beyang created a separate https://github.com/sourcegraph-dotcom-bot user (credentials in 1Password) and I generated a new access token "Sourcegraph.com" and put it in the Sourcegraph.com external service for GitHub.

**Comment by tsenart** [comment]
Thanks for the detective work everyone! 🥇
