### ISSUE TITLE
Code Insights: [BE] Add filters field in `createLineChartSearchInsight` mutation

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#27836]
At the moment we can't create insight with a predefined filters value.  But we have a case when this creation is needed. You can create insight from the drill-down filter panel. Because of this issue FE at the moment doesn't support this functionality. 

A possible workaround for FE in case if BE couldn't support this: call `createInsight` mutation first and then call updateLineChart mutation where we have filters field in input type. @unclejustin FYI.

Current state of Input type for `createLineChartSearchInsight` mutation.

```gql
"""
Input for a line chart search insight.
"""
input LineChartSearchInsightInput {
    """
    The list of data series to create (or add) to this insight.
    """
    dataSeries: [LineChartSearchInsightDataSeriesInput!]!

    """
    The options for this line chart.
    """
    options: LineChartOptionsInput!

    """
    The dashboard IDs to associate this insight with once created.
    """
    dashboards: [ID!]
}
```

**Comment by coury-clark** [comment]
Flagging this is as nice-to-have since we have a work around with create + update.
