### ISSUE TITLE
Image review and Topic search

### ISSUE THREAD

**Issue by devin3970285** [sourcegraph/sourcegraph#2786]
#### Feature request description

It would be great if we can review the image and soundtrack on it.
Also, it would be more convenient if we could search the code by topic.

**Comment by sqs** [comment]
For the image and soundtrack request, you would like to be able to view images and play audio files that are committed to repositories, right?

Could you please give some more info about your use case to help us understand, such as what higher-level problems this would solve? I understand the specific capability, but more of the story always helps us come up with the best impl and helps us prioritize. 

Thanks for the feature request!
