### ISSUE TITLE
docs: Update example versions

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#27869]
And ensure that when we publish versions the examples use that version in particular.

**Comment by efritz** [comment]
@chrismwendt Do you think there's a low-effort way to automate this?

**Comment by chrismwendt** [comment]
- Bash script that checks `git tag` and runs `sed` (only automates the file edits)
- CI check (only reminds us)
- Bot that runs `sed` and auto-commits when a tag is pushed

Any preference?

**Comment by efritz** [comment]
So the weird thing is the examples in the Terraform registry are tied to the tagged version, I think: https://registry.terraform.io/modules/sourcegraph/executors/google/latest

At least making sure we don't fall too far behind via a CI Check would be a fabulous start.
