### ISSUE TITLE
insights: insights aren't filterable with graphql API enabled

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#27863]
Steps to reproduce:
1. Create a backend insight
2. Open the filter tab
3. Type in a filter
4. There is no change on the chart (and no network requests emitted)

Demo
![CleanShot 2021-11-17 at 15 53 58](https://user-images.githubusercontent.com/5090588/142295549-3b9b0aea-1f64-457c-a4e4-5971418ca70a.gif)
:

**Comment by Joelkw** [comment]
@coury-clark do you want a "triage" from me, or is this for you and Cristina to use? I would consider this blocking, at least in its current state.

**Comment by coury-clark** [comment]
@Joelkw yeah this one is pretty clear :) Added the milestone

**Comment by vovakulikov** [comment]
I'm closing this one since this issue has been closed in this PR https://github.com/sourcegraph/sourcegraph/pull/27835
