### ISSUE TITLE
Series labels/data is swapped 

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#27879]
View [2:35-6:00 in this chorus call ](https://chorus.ai/meeting/576EC39ECD44447CB38428BD04F23464?). 

[Also trying to find out](https://sourcegraph.slack.com/archives/C02EYG34D5X/p1637105851009900?thread_ts=1637026109.008600&cid=C02EYG34D5X) if the issue is (my hypothesis) that these strings are either too long before the comparator/difference kicks in, or it's handling special characters (the `[` vs a `3`) differently on the backend and frontend. 

This otherwise appears to be a form of this bug #24352.

**Comment by vovakulikov** [comment]
@unclejustin We probably should change our logic in the new gql API. At the moment even with gql API where we have series id, we do a sorting over data series by query field `a.query.localeCompare(b.query)`. 

I think it makes sense to delete this logic for a new API to avoid bugs like this one in the future.

**Comment by felixfbecker** [comment]
Note from @vovakulikov: Should be closed with new migration, verify at end of iteration 7
