### ISSUE TITLE
docs: Note enable IAM permissions pre-terraform apply

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#27878]
Make sure you enable IAM permission (otherwise `terraform apply` will fail) https://console.cloud.google.com/apis/api/iam.googleapis.com/overview?project=SOME_PROJECT

**Comment by efritz** [comment]
@mrnugget I believe you were the one that mentioned this (could be wrong)?

**Comment by mrnugget** [comment]
Hmm, no, not sure what that refers to. I can't find something like that in my notes either:

* executors on GCP with Terraform: https://github.com/sourcegraph/sourcegraph/issues/26931#issuecomment-976715944
* executors on GCP bare-metal: https://github.com/sourcegraph/sourcegraph/issues/26781#issuecomment-978042559

Does it refer to the virtualization bit?

**Comment by eseliger** [comment]
@efritz do you happen to remember?
