### ISSUE TITLE
docs: How to auth to Cloud providers

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#27877]
From Chris: Must set `project` in google-beta and google and/or `gcloud config set project some-project`

**Comment by efritz** [comment]
@mrnugget I believe you were the one that mentioned this (could be wrong)?

**Comment by eseliger** [comment]
Is this still a problem?

**Comment by mrnugget** [comment]
I don't think so. `gcloud auth` etc. is covered in the deploy docs ([here](https://docs.sourcegraph.com/admin/deploy_executors#example-installation) for example).
