### ISSUE TITLE
Some `graphql?LogEvents` queries time out

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#27908]
[Some](https://console.cloud.google.com/logs/query;query=%22slow%20http%20request%22%20AND%20%22url%3D%2F.api%2Fgraphql%3FLogEvents%22;cursorTimestamp=2021-11-18T11:09:46.915041952Z?referrer=search&authuser=1&project=sourcegraph-dev&query=%0A) `graphql?LogEvents` queries timeout, which causes errors on the client-side. It happens only with `graphql?LogEvents`. It's not clear if we're losing some client events because of the API unavailability or the response time of the endpoint handler causes timeout.

**Comment by eseliger** [comment]
Has this been fixed by the linked PR?
