### ISSUE TITLE
insights: pings are reporting insight ID as insight type

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#27911]
For transparency here is the PR about fixing pings names https://github.com/sourcegraph/sourcegraph/pull/27891

I checked https://k8s.sgdev.org/site-admin/pings page and I couldn't manage to see increasing of `WeeklyInsightCreators` but I saw increasing of `Additional` for `"InsightType": "searchInsights"` and `"InsightType": "codeStatsInsights"`. 

```
{
                "Edits": 0,
                "Hovers": 1,
                "Removals": 0,
                "Additions": 2,
                "InsightType": "codeStatsInsights",
                "DataPointClicks": 0,
                "UICustomizations": 0
            },
            {
                "Edits": 0,
                "Hovers": 92,
                "Removals": 1,
                "Additions": 2,
                "InsightType": "searchInsights",
                "DataPointClicks": 0,
                "UICustomizations": 63
            }
```
@coury-clark other insights look like have a wrong type? not sure

Like, this is insight in the pings section. I suspect that we use insight id here as InsightType
```
  {
                "Edits": 0,
                "Hovers": 1,
                "Removals": 0,
                "Additions": 0,
                "InsightType": "aW5zaWdodF92aWV3OiJzZWFyY2hJbnNpZ2h0cy5pbnNpZ2h0LndpbGRjYXJkR3Jvd3RoIg==",
                "DataPointClicks": 0,
                "UICustomizations": 0
            },
```

_Originally posted by @vovakulikov in https://github.com/sourcegraph/sourcegraph/pull/27741#discussion_r751992503_

**Comment by coury-clark** [comment]
@vovakulikov The `insightType` is read directly from values populated by the web app [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/insights/analytics.ts?L29:5). My guess is that because previously it was parsing the ID prefix such as `insights.searchInsight.` to determine the type, it fails when we are using pure GraphQL IDs that do not have such a format. This is something we will need to fix before we release the API with flag enabled.

cc @Joelkw

**Comment by vovakulikov** [comment]
@coury-clark was right about FE but I think real culprit here this block https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/views/components/content/view-content/ViewContent.tsx?subtree=true

It's used for Hover and DataPointClick events tracking over insight views.
