### ISSUE TITLE
insights: series that are updated through the GraphQL api are incorrectly queued for processing

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#27917]
So it seems we have two issues:
1. This response is returning nil (for some reason the permissions are not resolving when it fetches after the update)
2. Series are getting queued for historical processing globally that shouldn't be

Based on that, I'm splitting this into another issue for 2.

_Originally posted by @coury-clark in https://github.com/sourcegraph/sourcegraph/issues/27837#issuecomment-973034958_

**Comment by coury-clark** [comment]
<img width="855" alt="CleanShot 2021-11-18 at 09 36 54@2x" src="https://user-images.githubusercontent.com/5090588/142457444-090fa0ac-68e9-468b-86e2-4b439fdb172d.png">

**Comment by coury-clark** [comment]
So for some reason, we have global series with randomly generated series_id as seen by the image above. This may be unrelated, but these series should hash from the query text since they are global.

**Comment by coury-clark** [comment]
Here is the `insight_series` after running the update mutation - clearly it's getting reset in some capacity.
<img width="734" alt="CleanShot 2021-11-18 at 09 47 55@2x" src="https://user-images.githubusercontent.com/5090588/142459517-e55d7a3f-d77c-491a-baca-0dbd295a32a9.png">

**Comment by coury-clark** [comment]
So it seems if the `seriesId` is not supplied on the mutation, the correct series (the global one) will get marked `deleted`, and a new series will be created. Each of the replacement series is interpreted as a new series because the `seriesId` is randomly generated.
<img width="799" alt="CleanShot 2021-11-18 at 10 06 45@2x" src="https://user-images.githubusercontent.com/5090588/142462739-661e69f0-531c-42ce-af11-f7fadacea652.png">

**Comment by CristinaBirkel** [comment]
> This may be unrelated, but these series should hash from the query text since they are global.
I think the hashing is only for series migrated over from settings?
https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/insights/resolvers/insight_view_resolvers.go?L664

No it shouldn't be creating new series for all of those. Hmm, first thought: could it be a race condition?

**Comment by coury-clark** [comment]
@CristinaBirkel Ah - I see the problem. It's because of the 10 minute sync jobs. When I re-run the update mutation after it updates from the hashed `seriesId`, it deterministically returns the same randomly generated series.

1. `seriesFound` [returns false](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/insights/resolvers/insight_view_resolvers.go?utm_product_name=GoLand&utm_product_version=GoLand&utm_source=JetBrains-v1.2.1#L288:21) since `seriesId` is null
2. `FindMatchingSeries` will 'reset' once the sync job runs and the series is replaced by the one with has the hashed `seriesId` and return no match

**Comment by coury-clark** [comment]
Closing since this is only an issue if running both the 10 minute sync jobs and the GraphQL API - which is an unsupported behavior.
