### ISSUE TITLE
insights: identical backend series are generated with different time periods

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#27956]
1. I created a new insight with two series
    1. `type:commit fix`
    2. `type:commit revert`
2. After fully generating the series, I see the following distinct dates for series 1:
```
'2020-12-01', '2021-01-01', '2021-02-01', '2021-03-01', '2021-04-01', '2021-05-01', '2021-06-01', '2021-07-01', '2021-08-01', '2021-09-01', '2021-10-01', '2021-11-01'
```
For series 2:
```
'2020-10-01', '2020-11-01', '2020-12-01', '2021-01-01', '2021-02-01', '2021-03-01', '2021-04-01', '2021-05-01', '2021-06-01', '2021-07-01', '2021-08-01', '2021-09-01'
```

So in other words, the second series is for some reason 2 months offset the first. Both series were created on the same date (but not at the same time?):
| query | created\_at |
| :--- | :--- |
| type:commit revert | 2021-11-18 17:38:10.748128 |
| type:commit fix | 2021-11-18 19:44:01.829547 |

<img width="387" alt="CleanShot 2021-11-19 at 08 39 05@2x" src="https://user-images.githubusercontent.com/5090588/142649716-6c2c3268-d365-4da8-98c1-ea53f03835f6.png">

**Comment by Joelkw** [comment]
Not a problem on demo: 
![image](https://user-images.githubusercontent.com/11967660/142658216-67d8dbfa-9afd-435a-b9f3-632f35408be1.png)

**Comment by coury-clark** [comment]
Unable to reproduce. [Looking at the code](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@insights/commit-search-result-test/-/blob/enterprise/internal/insights/background/historical_enqueuer.go?utm_product_name=GoLand&utm_product_version=GoLand&utm_source=JetBrains-v1.2.1#L331:29), it clearly generates points starting at the `created_at` time for the series, which is `2021-11-18`

I really don't have many ideas at this point what caused this. Maybe:
1. I manually edited this series yesterday (because it failed for unrelated reasons) and somehow I made a mistake manually. I don't think this is the case, because the query I ran was:
``` SQL
update insights_query_runner_jobs
set state = 'queued', last_heartbeat_at = null
where series_id = 's:10DD84C8E638D0AFC97B00BF4880D65E6F6C546ACA9C41C424ACA873F03A9284';
```
2. There is some bug that modifies the dates after they are constructed?

**Comment by coury-clark** [comment]
<img width="475" alt="CleanShot 2021-11-19 at 12 46 17@2x" src="https://user-images.githubusercontent.com/5090588/142682736-3b7370f9-ab94-411c-80df-ab1642bbf81a.png">
