### ISSUE TITLE
sg: export CI metrics to Loki

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#27982]
Idea: we can export CI metrics via a JSON-formatted log line we append to the end of each log stream before uploading the log stream, e.g. crudely:

```go
stream.Values = append(stream.Values, [2]string{"<ts>", `{"log": "build-summary-log", "duration":12}`})
```

Then we can do a query like this:

```logql
{app="buildkite",branch="main"} |=  "build-summary-log" # get summary lines
	| json # format summary lines as json
	| duration # do things to duration, e.g. chart or something
```

We can export this single "summary log line" for build successes as well, since this `sg ci logs` is now run after every job. This will enable additional metrics for https://github.com/sourcegraph/sourcegraph/issues/26118

**Comment by jhchabran** [comment]
This is a great idea! And much lower effort than adapting the tracing (open tracing VS open telemetry) as we already have those timings.

**Comment by bobheadxi** [comment]
After just getting build timing we could do another pass that does some analysis on the parsed log lines to generate our own "trace" timings for each _command_ in each step as well 😁 (maybe with a special delimiter syntax for ease of implementation and opt-in)

**Comment by bobheadxi** [comment]
@davejrt I would add any additional post-processing of streams, like that indicated by this issue, here: https://github.com/sourcegraph/sourcegraph/blob/main/dev/sg/sg_ci.go#L338-L341

**Comment by bobheadxi** [comment]
Another request: add metadata to this log line about the agent the job ran on

**Comment by bobheadxi** [comment]
Superseded by @jhchabran 's work on https://github.com/sourcegraph/sourcegraph/issues/29411 , which gives us a much better avenue for checking detailed step performance!

**Comment by jhchabran** [comment]
@bobheadxi Btw, I have updated the top 10 slowest things to be commands rather than steps, as we already have that on grafana :)
