### ISSUE TITLE
Failed to deploy on Centos 7

### ISSUE THREAD

**Issue by martin-o-sw** [sourcegraph/sourcegraph#2798]
- **Sourcegraph version: 3.1.2** 
- **Platform information: CentOS 7.6.1810, Docker 1.13.1 ** 

#### Steps to reproduce:

1. Run docker container with deployment command from website

#### Expected behavior:
Working container image as on other systems.

#### Actual behavior:
Container fails to deploy and prints permission error even when running as root:
Failed to setup nginx:failed to generate nginx configuration to /etc/sourcegraph: open /etc/sourcegraph/nginx.conf: permission denied

**Comment by nicksnyder** [comment]
cc distribution team @beyang @slimsag @ggilmore

**Comment by beyang** [comment]
@martin-o-sw assuming you ran the `docker run` command unmodified, the root user inside the container would need write access to the `$HOME/.sourcegraph/config` directory on the Docker host. Can you try the following?

1. `cd` into a temporary directory that your host user has read/write access to. Create a new directory and let `$DIR` be the absolute path to that directory. Then run
  ```
  docker run --publish 7080:7080 --publish 2633:2633 --rm --volume $DIR/config:/etc/sourcegraph --volume $DIR/data:/var/opt/sourcegraph sourcegraph/server:3.2.0
  ```

2. If that yields the same error, kill the `docker run` command and run the following:
  ```
  docker run -it --publish 7080:7080 --publish 2633:2633 --rm --volume $DIR/config:/etc/sourcegraph --volume $DIR/data:/var/opt/sourcegraph  --entrypoint bash sourcegraph/server:3.2.0
  ```
  
  This will give you an interactive shell inside the container. In that shell, `cd` into `/etc/sourcegraph`, do a `ls -h` and try to create a file `touch foo`. Report back any errors here.

**Comment by martin-o-sw** [comment]
I've set $DIR to /tmp/SourceGraph and just to be sure I ran chmod -R 0777 on that, but I still get same permissions error.
When I run touch inside the container in /etc/sourcegraph it gives me permission error again "touch: foo: Permission denied". But when I run this command inside container in /etc/ssh, where I should have same permissions, it runs just fine.

**Comment by beyang** [comment]
What does `ls -lh` return inside `/etc/sourcegraph` and `/etc/ssh` inside the container?

**Comment by martin-o-sw** [comment]
![dockerCentos](https://user-images.githubusercontent.com/48679493/54805583-ad127d00-4c77-11e9-86a6-7df8c1a8d457.JPG)

**Comment by beyang** [comment]
I believe this may be related to an issue using Docker volumes on CentOS:
* https://stackoverflow.com/questions/24288616/permission-denied-on-accessing-host-directory-in-docker
* https://github.com/moby/moby/issues/14175
* https://www.projectatomic.io/blog/2015/06/using-volumes-with-docker-can-cause-problems-with-selinux/

Can you try the instructions in the above links?

**Comment by martin-o-sw** [comment]
This was the issue and now it's working fine.
I think this is something that could be included even in SourceGraph manual as this is known issue.

Thank you for your help.

**Comment by sqs** [comment]
@beyang do you plan to include this in our docs?

**Comment by beyang** [comment]
@sqs I looked into it, but made the determination that there isn't a good place for this in our current docs. We could have a "Troubleshooting" page, but at the end of the day, that seems like it would just be a manual curation of certain issue responses—is that better than simply directing users to search through the issue tracker?
