### ISSUE TITLE
patch release request: backport fix for monitor notifications

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#27999]
@sourcegraph/delivery I am requesting the following commits be included in a patch release.

I've [merged the changes](https://github.com/sourcegraph/sourcegraph/pull/28019) into the 3.33 branch. The effect of the changes is the same as what is on main, but we couldn't cherry pick changes from main because it the commits that did this were not cleanly separated. 

---

The intent of the questions below is to ensure we keep Sourcegraph high quality and [only create patch releases based on a strict criteria.](https://handbook.sourcegraph.com/engineering/releases#patch-releases) If you can answer yes to many or most of these questions, we will be happy to create the patch release.

I have read [when and why we perform patch releases](https://handbook.sourcegraph.com/engineering/releases#patch-releases) and answer the questions as follows:

> Are users/customers actively asking us for these changes and cannot wait until the next full release?

See https://github.com/sourcegraph/security-issues/issues/18

> Are the changes extremely minimal, well-tested, and low risk such that not testing as we do in a full release is OK?

This change is as minimal as possible, and making it minimal was part of the reason I re-made these changes on top of v3.33.0 rather than pulling in the commits as they exist on main. I've tested the changes as well as upgrading from the resulting patch to v3.34.0 to make sure the weird migrations don't break anything. 

> Is there some functionality completely broken that warrants redacting the prior release of Sourcegraph and advising users wait for the patch release?

No. This issue has existed for more than a year, and version 3.34.0 will also fix this issue, so upgrading is preferable to patching.

> This will interrupt our regular planned work and release cycle, taking one full working day of our time, and will take up all of our site admin's valuable time by asking them to upgrade or producing noise for them if they don't need to upgrade.
>
> Do you believe the changes are important enough to warrant this?

Yes.

> Patch releases are a signal we can do something better to improve the quality of Sourcegraph. Have you already scheduled a call (or created a google doc) to perform a [retrospective](https://about.sourcegraph.com/retrospectives) and identify ways we can improve?

Retrospective will be performed as part of https://github.com/sourcegraph/security-issues/issues/18

---

**For the [release captain](https://handbook.sourcegraph.com/engineering/releases#release-captain)** - after reviewing this request:

- [x] **Comment on this issue** with a decision regarding the request.
- [ ] If approved, **add it to a patch release**:
  - If there is [already an upcoming patch release](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+), add the listed commits alongside a link to this issue
  - If there is no upcoming patch release, create a new one:
    - Update [`dev/release/release-config.jsonc`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/release/release-config.jsonc) with the patch release in `upcomingRelease` and `releaseDate` (and open a PR to `main` to update it)
    - `yarn release tracking:issues`
    - Add the listed commits alongside a link to this issue to the generated [release tracking issue](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+)
- [ ] **Comment and close this issue once the relevant commit(s) have been cherry-picked into the release branch**.

**Comment by kevinwojo** [comment]
Approving this patch. Moving forward with pushing out.

**Comment by kevinwojo** [comment]
This has been released: https://github.com/sourcegraph/sourcegraph/issues/28044

**Comment by kevinwojo** [comment]
This was released
