### ISSUE TITLE
Inform users they need to grant extension permissions to their code host and Sourcegraph URL

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#2799]
Having an onboarding flow in the browser extension that ensures necessary permissions are granted would be really helpful in making enterprise deployments successful.

The issue of permissions is twofold:
1. If the extension doesn't have permissions to the Sourcegraph URL, it may fail to connect to the instance (#2228).
2. If the extension doesn't have permissions to the code host's URL, it will fail to provide any features on the code host. This is true for any code host that isn't https://github.com.

We have to work with the following limitations:
- Permissions cannot be pre-set by the admin through GSuite deployment.
- Permissions requests must stem from a user gesture.

The status quo is:
- For 1., the options page now gives the user the option to [grant the extension permissions to the Sourcegraph URL if the connection fails](https://github.com/sourcegraph/sourcegraph/pull/2554).
![image](https://user-images.githubusercontent.com/1741180/54537367-a7c0e400-4992-11e9-9ff5-10b798412904.png)
- For 2., the only fix is to right-click the browser action and click "enable on this domain", which is [not very discoverable](https://github.com/sourcegraph/sourcegraph/issues/2770).
![image](https://user-images.githubusercontent.com/1741180/54537283-8bbd4280-4992-11e9-980b-d96a43b8b25a.png)

We could benefit from an onboarding, in the form of a web_accessible page (like the options page) opened when the extension is installed (using the [`runtime.onOninstalled`](https://developer.chrome.com/apps/runtime#event-onInstalled) callback). It could go like this:

- After extension installation, the onboarding page is opened.
- The user is asked to specify his sourcegraph URL, if applicable.
- If the user changes his Sourcegraph URL to something !== sourcegraph.com, we ask for permissions for that URL.
- We make sure the user is logged in to his Sourcegraph instance.
- The user is asked to specify his code hosts' URL (eg. https://ghe.private.org/).
- We ask for permissions for that URL if not already granted.

For people using the extension with sourcegraph.com (eg. just as a tool to see codecov decorations), the onboarding would be as simple as "Are you happy with the URL being sourcegraph.com? OK, looks good!".

That being said, there are ways to make this less intrusive:

- Instead of systematically opening an onboarding page when the extension is install, we add a badge to the browser action until the onboarding has been completed, and do the onboarding directly from the popup:
![image](https://user-images.githubusercontent.com/1741180/54537117-3ed96c00-4992-11e9-81e4-787f5c1005a2.png)
- Once the extension is connected to the Sourcegraph instance, we could fetch the code host URL from org settings, so that the user doesn't have to type it himself / can't mistype it.

**Comment by lguychard** [comment]
@sqs would love to get your thoughts on this. After working on #2228 in 3.2, and @slimsag bringing up #2770, I think this could be quite impactful.

Down the line, when we're happy with the quality of the browser extension, an onboarding flow would also be a way to encourage feature discovery.

Of course, the case could also be made that it it is more important to work towards having great native integrations with code hosts, because:
- It's easier to convince enterprise customers to deploy them.
- They require less (or no) configuration by the enterprise user.

**Comment by slimsag** [comment]
I think this could be the most impactful thing to get customers to see the value of the Sourcegraph extension more immediately.

**Comment by sqs** [comment]
This would absolutely be HUGE.

As we discussed that led to https://github.com/sourcegraph/sourcegraph/issues/2770#issuecomment-474413769, I think the proper order of operations is:

1. Make it work really well and document it
2. Add onboarding

Doing (2) before (1) is putting lipstick on a pig. :pig: :lipstick: I think we all agree here (as @lguychard said in "when we're happy with the quality of the browser extension, ...").

The question to answer before we start working on this is: is (1) done? @slimsag for the customers you work with, do you think (1) is done?

**Comment by slimsag** [comment]
The solution in #2770 means that when a customer/user tells me "it doesn't work" I can say:

> Yeah, we're aware this is annoying/confusing, here are docs explaining what you have to do: ...

It's kind of a "RTFM" solution, but doesn't really pass the test of basic human behavior 😜

At the end of the day, the UX is _extremely_ confusing as it stands. Here's why:

1. Install Sourcegraph and add Bitbucket repositories.
2. Install browser extension.
3. Visit your Bitbucket and click Sourcegraph icon, see this:

![image](https://user-images.githubusercontent.com/3173176/54969822-fc3d0400-4f3c-11e9-9963-839f270acf32.png)

4. Doesn't work yet, so assume "I probably need to change the URL." Set it:

![image](https://user-images.githubusercontent.com/3173176/54969857-21ca0d80-4f3d-11e9-8718-a2c113c05025.png)

It says `Connected` and shows me a green icon as if everything is working. I'm on my Bitbucket instance. But it's not working? Is it broken?

I estimate 100% of users who don't know about the right click trick would assume so.

**Comment by slimsag** [comment]
The bare minimum change we can do to achieve (1) is to add below the Connected field:

> Extension not working on your private code host? [You may need to grant it access](https://some.docs)

**Comment by sqs** [comment]
Good idea. Even easier immediate fix that doesn't require a docs link:

> Extension not working on your private/enterprise code host? Right-click on the extension's toolbar icon to allow access on the domain.

Want to just send up a PR with that now?

**Comment by lguychard** [comment]
@sqs @slimsag done in https://github.com/sourcegraph/sourcegraph/pull/2980

![image](https://user-images.githubusercontent.com/1741180/55000835-a8c9c500-4fd3-11e9-8fa1-7bd705a532c3.png)

**Comment by slimsag** [comment]
@lguychard @sqs I just got even more signal that the above is not sufficient / obvious enough. See my message at https://sourcegraph.slack.com/archives/C0W2E592M/p1554839219020100

I think it's just too easy to miss and it's such a critical thing, it leads to a very bad experience. What can we do to improve this further? One obvious step is making the `Extension not working on your private code host?` text bold.

**Comment by slimsag** [comment]
Removed milestone so we reprioritize this appropriately

**Comment by sqs** [comment]
How about:

- Fast improvement: if the url is other than Sourcegraph.com, show an info alert (Bootstrap blue background). 
- Near-ideal improvement: If it’s fairly easy to detect this precisely, then show a red alert if the url’s domain is not permitted yet (and don’t show anything if all is good)

@lguychard @felixfbecker This is important and we should prioritize this most highly (other than P0s).

**Comment by felixfbecker** [comment]
@sqs on which page should the alert be shown?

**Comment by sqs** [comment]
In the options menu for the browser extension

![image](https://user-images.githubusercontent.com/1976/55832874-5c01e600-5acb-11e9-839b-8f0eda584947.png)

**Comment by lguychard** [comment]
@sqs @slimsag done in #3342 

![image](https://user-images.githubusercontent.com/1741180/55871811-c5e1c480-5b8b-11e9-920b-47da6226664e.png)

**Comment by sqs** [comment]
@lguychard After https://github.com/sourcegraph/sourcegraph/pull/3342 is merged, we can close this issue, right? Because the other problem mentioned in this issue description is them needing to grant perms to a non-sourcegraph.com Sourcegraph URL, but that's fixed by special-casing the chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack origin on the server (and Firefox never had issues with it?), right?

(It's not worth keeping this issue open for general browser extension onboarding improvements, because that'll be a perennial project.)

**Comment by lguychard** [comment]
> needing to grant perms to a non-sourcegraph.com 

This can still be useful in some cases (#2228) but #2554 made it possible to grant permissions directly from the options page:

![image](https://user-images.githubusercontent.com/1741180/55948053-00ad3080-5c50-11e9-94c1-120224f0c0d1.png)

I agree that after #3342 is merged, we should close this, and track future improvements we may want to make in separate issues.
