### ISSUE TITLE
Code Insights: [FE] Implement check list logic for capture groups search query field

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#28022]
Blocked by https://github.com/sourcegraph/sourcegraph/issues/21339

## Context 

For capture groups query we have a list of requirements. Based on the latest design spec they are following.

<img width="509" alt="Screenshot 2021-11-22 at 19 16 44" src="https://user-images.githubusercontent.com/18492575/142896679-ec2e12a1-dae7-4acd-bd4f-2c8b1df1bcd8.png">

**Tech details:** This list of rules could be implemented with our custom pattern matching for queries https://sourcegraph.com/github.com/sourcegraph/sourcegraph@d3f3d5e2a394a933337301fb16eb83e6f59a6b27/-/blob/client/shared/src/search/query/diagnostics.ts?L84-178

**Comment by Joelkw** [comment]
(Updated image)
![image](https://user-images.githubusercontent.com/11967660/142905310-2f6aa7b0-eaa2-4fa4-8a21-403b5e80786e.png)
