### ISSUE TITLE
SSBC: View the position of my batch change in the queue

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#28031]
### User problem

When I submit a new batch change, all executors might be busy for a while running other batch changes.
Fair scheduling will be addressed by #26895, but regardless of what scheduling principle is used, as a user I want to know where my batch change is in the queue.

The ideal answer to "when will my batch change run" is, in order of usefulness:
- a timeline (sounds hard, frustrating, not worth it)
- the number of workspaces that need to be processed before mine
- the number of batch changes before mine 

### Proposal
Needs design.

**Comment by eseliger** [comment]
It is available in the UI :) 
![image](https://user-images.githubusercontent.com/19534377/143068978-179889e9-1e35-4482-8f2b-ff821e90e370.png)

**Comment by malomarrec** [comment]
Moving so fast my tickets are outdated before I can open them. 👏 
This sounds resolve, closing.
cc @rrhyne feel free to reopen if you feel otherwise

**Comment by rrhyne** [comment]
I have some revisions to make visually, reopening and assigning to me.

**Comment by rrhyne** [comment]
Figma available here: https://www.figma.com/file/cTKjwbvWqU6xAykZmCTTqy/?node-id=2013%3A70650

**Comment by courier-new** [comment]
For this ticket specifically, the scope is limited to this frame: https://www.figma.com/file/cTKjwbvWqU6xAykZmCTTqy/SSBC?node-id=2013%3A72171
The overview and no executors configured frames are separate tickets.

**Comment by courier-new** [comment]
Converted this back to an engineering ticket.
