### ISSUE TITLE
Should inlineSymbolSearch code be removed?

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#2804]
Inline symbol search currently seems to be [enabled by default](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/browser/src/browser/types.ts#L37:5) by a feature flag, but neither myself nor @felixfbecker can get it to work. Yet nobody has complained about it breaking.

In addition, it represents quite a lot of code that:
- We'd need to overhaul to bring up to our targeted quality standards
- Might interfere with some planned rewrites around better handling DOM mutation.

Should we just kill the feature and remove all associated code?

cc @sqs

**Comment by nicksnyder** [comment]
This was a hack project by @ggilmore last year. I am able to get it to work by typing `@!he` into the text box for this issue.

If there is any chance this non-critical feature would slow down stabilizing our more important features (which seems to be the case), then I would be in favor of deleting it.

![Screen Recording 2019-03-18 at 03 18 PM](https://user-images.githubusercontent.com/754768/54567452-19982e00-4991-11e9-81a4-e8146b4e0a34.gif)

**Comment by sqs** [comment]
Yes, you can remove this feature. We probably will bring it back *eventually*.
