### ISSUE TITLE
Fuzzy file finder shortcut opens print screen on Linux

### ISSUE THREAD

**Issue by scalabilitysolved** [sourcegraph/sourcegraph#28094]
**Problem**

Opening the fuzzy file finder on Linux in Chrome and Firefox 94.0 using the `ctrl+p` shortcut will result in the print dialog opening when any part of an opened file is clicked upon.

**Specific versions**
* Ubuntu - 20.04.3 LTS
* Chrome - Version 96.0.4664.45 (Official Build) (64-bit)
* Firefox 94.0
* Sourcegraph extension - v21.11.8.1804

**Loom video**
https://www.loom.com/share/5f16ff7028154fa69216d08ba72179b3?sharedAppSource=personal_library

**Steps to recreate**

1. Navigate to the [Hystrix](https://sourcegraph.com/github.com/Netflix/Hystrix/-/blob/hystrix-core/src/main/java/com/netflix/hystrix/HystrixThreadPool.java?L47:18) repository, open the fuzzy finder modal with `ctrl+p`.

![Screenshot from 2021-11-23 21-20-21](https://user-images.githubusercontent.com/1309599/143098184-c4dbcd2d-4478-421d-aed5-123894cc612e.png)

2. Close the modal and click on the class name (or anywhere within the file)
![Screenshot from 2021-11-23 21-21-28](https://user-images.githubusercontent.com/1309599/143098180-be65967a-302e-4460-98bc-93a7beaa2b83.png)

3. Re-open the modal with `ctrl+p` and the print dialog will appear.
![Screenshot from 2021-11-23 21-20-37](https://user-images.githubusercontent.com/1309599/143098182-53a5ff2d-0757-4b12-b9d8-8b96c335eb3c.png)

4. Upon closing the print dialog, the command palette will be open in the top right hand corner.
![Screenshot from 2021-11-23 21-27-44](https://user-images.githubusercontent.com/1309599/143098952-fffde095-6d56-49ea-96f6-181cb4fa6caf.png)

**Comment by scalabilitysolved** [comment]
Hey @Numbers88s :wave: 

Locally the problem doesn't occur if I alter the shortcuts in this file so that the command palette binds instead to any other letter except `p`. 

If I do this, then `ctrl+p` works for opening the fuzzy file finder on Linux/Chrome and clicking into any file doesn't stop it working.

I'm guessing you weren't able to recreate this on mac because fuzzy finder is `cmd+p` and control panel is `control+p` on osx.  If you change those to both be `cmd+p` I imagine you'll see the issue?

**Comment by olafurpg** [comment]
I propose that we use Cmd+K (and Ctrl+K) for the fuzzy file finder to fix this issue. It avoids the conflict with the action bar and the browser's Print command. In the future, we may support fuzzy searching more types (repos, symbols, actions) and it's unlikely we want to have a custom shortcut for every one of those. Also, GitHub's command pallette (which includes a fuzzy file finder) uses Cmd+K.
