### ISSUE TITLE
Improve Percy test coverage

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#28129]
## Problem

We have _some_ web application pages [covered](https://percy.io/Sourcegraph/Sourcegraph/builds/14121239/unchanged/798203119?activeBrowserFamilySlug=chrome&activeViewMode=new&activeWidth=1920&subcategories=approved&viewLayout=side-by-side) with visual tests via Percy. But a lot of core functionality is not covered, and it reduces our confidence in shipping visual changes.

## Success criteria

1. Important parts of the web application not covered with visual tests are identified. 
    - 4h estimate.
    - use https://k8s.sgdev.org/ to explore pages that are not covered.
    - use this [Percy report](https://percy.io/Sourcegraph/Sourcegraph/builds/14121239/unchanged/798203119?activeBrowserFamilySlug=chrome&activeViewMode=new&activeWidth=1920&subcategories=approved&viewLayout=side-by-side) to see which pages are already covered.
2. Integration tests rendering these parts of the app are identified.
    - 4h estimate.
    - find integration tests here `client/web/src/integration/**.test.ts`.
    - see documentation on how to run integration tests locally [here](https://docs.sourcegraph.com/dev/how-to/testing#client-integration-tests).
3. Percy screenshots are added to the integration tests identified in the previous step.
    - 2h estimate.
    - use `percySnapshotWithVariants` to make a Percy snapshot for a selected page in the integration test.

**Comment by gitstart-sourcegraph** [comment]
Hello @valerybugakov, with respect to first stage of issue completion, a number of pages has been identified. that we believe meets your description of `core functionality`. kindly review list below, to confirm pages.

```
1. Home / Search page: [https://k8s.sgdev.org/search](https://k8s.sgdev.org/search)
2. Search Notebook: [https://k8s.sgdev.org/search/notebook](https://k8s.sgdev.org/search/notebook)
3. User batch chages: [https://k8s.sgdev.org/users/gitstart/settings/batch-changes](https://k8s.sgdev.org/users/gitstart/settings/batch-changes)
4. Create Context page: [https://k8s.sgdev.org/contexts/new](https://k8s.sgdev.org/contexts/new)
5. Contexts list: [https://k8s.sgdev.org/contexts](https://k8s.sgdev.org/contexts)
6. Create batch change: [https://k8s.sgdev.org/batch-changes/create](https://k8s.sgdev.org/batch-changes/create)
7. SignIn Page: [https://k8s.sgdev.org/sign-in](https://k8s.sgdev.org/sign-in)
8. Add Dashboad Page [https://k8s.sgdev.org/insights/add-dashboard](https://k8s.sgdev.org/insights/add-dashboard)
9. Add Saved Search Form [https://k8s.sgdev.org/users/gitstart/searches/add](https://k8s.sgdev.org/users/gitstart/searches/add) 
10. API Console: [https://k8s.sgdev.org/api/console](https://k8s.sgdev.org/api/console)
11. Set up new language usage insight: [https://k8s.sgdev.org/insights/create/lang-stats](https://k8s.sgdev.org/insights/create/lang-stats)
12. Create new code insight: [https://k8s.sgdev.org/insights/create/search](https://k8s.sgdev.org/insights/create/search)
13. Organization setting: [https://k8s.sgdev.org/organizations/sourcegraph/settings](https://k8s.sgdev.org/organizations/sourcegraph/settings)
```

**Comment by valerybugakov** [comment]
@gitstart-sourcegraph, 
`Create new code insight` — is very similar to the `Edit code insight` page that is already covered.
Let's proceed with adding `percySnapshotWithVariants` for the other pages you mentioned.

**Comment by limitedmage** [comment]
Hi @gitstart-sourcegraph, can you also add tests to the following pages, if they don't already exist?

- Code monitoring homepage: [Link](https://k8s.sgdev.org/code-monitoring)
- User settings page: [Link](https://k8s.sgdev.org/user/settings)
- Saved searches list: [Link](https://k8s.sgdev.org/user/searches)
- Create saved search: [Link](https://k8s.sgdev.org/user/searches/add)

Thanks!

**Comment by vovakulikov** [comment]
Hello @gitstart-sourcegraph it seems like in code insights pages we already have some Percy snapshots.

A few pages that might be missed 
- Create insight Intro page- [Link](https://k8s.sgdev.org/insights/create?dashboardId=all)
- Create lang stats Insight - [Link](https://k8s.sgdev.org/insights/create/lang-stats?dashboardId=all)
- Create search based insight - [Link](https://k8s.sgdev.org/insights/create/search?dashboardId=all)
- Edit pages for search-based and lang stats are similar to creating UI pages so unsure about these screenshots but the flow here is 
  - Open dashboard page
  - Click on the context menu of any insight (three dots menu)
  - Click edit
  - you should be redirected to edit page for search-based/lang-stats insight 

Here is the existing integration test for it https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/integration/insights/edit-search-insights.test.ts

**Comment by courier-new** [comment]
Hi @gitstart-sourcegraph! Thanks for taking a look at this. In addition to the two Batch Changes pages you already flagged:

- User batch changes settings: [Link](https://k8s.sgdev.org/users/gitstart/settings/batch-changes)
- Create batch change: [Link](https://k8s.sgdev.org/batch-changes/create)

I'd also love to see coverage introduced for these pages:

- Batch changes "getting started" page: [Link](https://k8s.sgdev.org/batch-changes), then click on the tab "Getting started"
- Batch change details page: For example, [Link](https://k8s.sgdev.org/users/malo/batch-changes/hello-world)
- Batch change preview page: For example, [Link](https://k8s.sgdev.org/users/kelli/batch-changes/apply/QmF0Y2hTcGVjOiI4cVVtV1ZYcUE1MiI)
