### ISSUE TITLE
Docs: k8s deployment behavior during node upgrades, best practices 

### ISSUE THREAD

**Issue by DaedalusG** [sourcegraph/sourcegraph#28160]
#### Describe the issue
Some users utilize their cloud provider's kubernetes version [auto-update](https://cloud.google.com/kubernetes-engine/docs/concepts/cluster-upgrades#node_pool_upgrades) option. For the kubernetes control plane or the nodes themselves. Currently, our best [practices docs](https://docs.sourcegraph.com/admin/deployment_best_practices#kubernetes) don't have any advisement around auto-upgrades. Additionally our [kubernetes deployment docs](https://docs.sourcegraph.com/admin/install/kubernetes#about) don't set expectations about the stability or behavior of Sourcegraph during a node pool Kubernetes version upgrade.

From some initial testing, I found that a Kubernetes instance with 4 nodes saw the frontend go down during a node pool upgrade. While in another test deployment with 6 nodes was able to maintain service throughout the upgrade. 

There's anecdotal evidence that in some cases PVC may be temporarily detached during a node upgrade which could have unexpected results (it hasn't been reproduced but a user has suggested that after a node upgrade zoekt needed to reindex repos)  

#### Where is the issue located?
This issue is located within the k8s deployment docs and info, as well as the best practices advisements.

#### Suggested resolution
Suggesting documents to live in:
- [k8s operations or about](https://docs.sourcegraph.com/admin/install/kubernetes#about) (for general expected behavior or node pool resource advisement) 
- [best practices](https://docs.sourcegraph.com/admin/deployment_best_practices#kubernetes) (for advisement about stable release channel and auto-updates, note this choice may be out of some admins control)
- If a best practice exists around the best way to do a manual node pool update and maintain Sourcegraph availability that could get a how-to, for automatic updates this makes a little less sense.

**Comment by virginiaulrich** [comment]
@DaedalusG in delivery team planning, we are opting to close this because we need to have a larger philosophical conversation about whether we want our docs to cover this kind of education -- since we don't know if we want to sign ourselves up for being on the hook for such guidance. If you have any questions, let me know!
