### ISSUE TITLE
zoekt: make matchtree regex search use window around trigram locations instead of entire file

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#28178]

**Comment by keegancsmith** [comment]
@eseliger and I started hacking on this https://github.com/sourcegraph/zoekt/pull/216

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket, please let us know how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
