### ISSUE TITLE
CI still runs full suite on docs-only changes despite onlyDocsChange logic

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#2823]
My PR https://github.com/sourcegraph/sourcegraph/pull/2820 is a docs-only change, but it still ran all of CI. The onlyDocsChange logic in https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/df71399161451b0342249beeeb16208720638e07 does not seem to be working.

**Comment by chrismwendt** [comment]
The logic is correct, but `origin/master` was not always up-to-date upon execution. Fixing in https://github.com/sourcegraph/sourcegraph/pull/2826
