### ISSUE TITLE
store: implement sub-repo perms filtering on ZipCache return values

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#28243]
Regex search (and possibly more) happens on zip archives, fetched by  [Store](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@afdd23d41ba904d575d07012bdd8e8c30c111476/-/blob/internal/store/store.go) but appears to be provided by [ZipCache.Get](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@afdd23d41ba904d575d07012bdd8e8c30c111476/-/blob/internal/store/zipcache.go), so implement sub-repo perms filtering on the latter before the zip is returned from ZipCache from [Get()](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@afdd23d41ba904d575d07012bdd8e8c30c111476/-/blob/internal/store/zipcache.go?L45:39), i.e. when zip contents are requested from the cache it comes already filtered

We cannot filter the initial Git archive request because the cache is shared - multiple users with different permissions may need to search the same cached archive. This might supersede #27332

**Comment by mollylogue** [comment]
I've been tracing the usage of this ZipCache through the codebase and from what I can tell it's used exclusively in the `search` package. 

Here are some key Sourcegraph searches I ran to prove this out:
[places where the store package is imported](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph++%22github.com/sourcegraph/sourcegraph/internal/store%22&patternType=literal)
[uses of ZipCache.Get](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@b08fc8d9bb7ac722c258d3785247dc5f4542f76b/-/blob/internal/store/zipcache.go?L47:20#tab=references)
[all references to the ZipFile struct](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@b08fc8d9bb7ac722c258d3785247dc5f4542f76b/-/blob/internal/store/zipcache.go?L98:6#tab=references)

From all my searching/digging I'm not seeing these zip files referenced outside of the `search` package (or where the definitions themselves are in the `store` package). Within searcher, I'm seeing these zip files referenced in [search_regex.go](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@b08fc8d9bb7ac722c258d3785247dc5f4542f76b/-/blob/cmd/searcher/search/search_regex.go) , [search_structural.go](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@b08fc8d9bb7ac722c258d3785247dc5f4542f76b/-/blob/cmd/searcher/search/search_structural.go) and [search.go](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@b08fc8d9bb7ac722c258d3785247dc5f4542f76b/-/blob/cmd/searcher/search/search.go) (outside of these files are just references within the `store` package or test file references.) I dug into the usages in each of these files and it appears to me that the usages are all within the main "search" functions which will have sub-repo permissions applied at the top level. 

If it is the case that we are only accessing this code via searcher, we are handling sub-repo permissions filtering for all search backends at the top level (graphql layer) in this issue: https://github.com/sourcegraph/sourcegraph/issues/28242 

I'm not sure if there is another way to access any of these zip files that could be problematic, so I'll look a bit more into that.

**Comment by ryanslade** [comment]
Thanks for looking into this, it sounds like we're safe from the search side of things. 

I took another look and something that seems to have slipped through the net is our raw endpoint. 

It uses a few functions from our git package which luckily do apply filtering, but we did miss one, `git.ArchiveReader`. I'm going to create a new issue for that.

**Comment by mollylogue** [comment]
@ryanslade Should I look into the raw endpoint as a part of this? Or just leave it to that other ticket to deal with that?

**Comment by ryanslade** [comment]
I'm hoping that by adding a check in `git.ArchiveReader` we can leave the raw endpoint as is.

**Comment by mollylogue** [comment]
@ryanslade Should I just close this out with no code changes since the `git.ArchiveReader` task should cover the work needed?

**Comment by ryanslade** [comment]
Yep, I think that use case will be covered by https://github.com/sourcegraph/sourcegraph/issues/27332
