### ISSUE TITLE
search: Implement sub-repo filtering for search backends

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#28242]
Our search code has a natural place to apply sub-repo filtering which covers all search backends, with an entry point [here](https://github.com/sourcegraph/sourcegraph/blob/main/cmd/frontend/graphqlbackend/search_results.go#L599)

Each job `Run` method includes a `Sender`. We can modify `toSearchInputsso` so that we return jobs with a slightly different `Sender` that wraps the original one and does sub-repo filtering.  It would modify the `SearchEvent` being passed to the original sender by applying filtering to it.

By doing it in this place we can handle all search backends by filtering in only one place. 

We should add add some form of end-end or integration test so ensure that there are no regressions in the future.

**Comment by bobheadxi** [comment]
From Keegan:

> have you ruled out implementing this in Zoekt server? ie skipping searching a file at all if a user can't see it? For example something which skips over documents here would be quite efficient: https://github.com/sourcegraph/zoekt/blob/master/eval.go#L199-L202



> [the client-based approach] runs into issues when a user can't see much, since you start running into limits stopping searches on private results before a user has hit a result it can actually see.
>
> Zoekt does handle some concept of permissions for performance reasons. It currently stores repo visibility to make it possible to efficiently search over all public repos, we then pass in the set of private repos to zoekt to search those. I imagine the ideal situation with respect to performance is having the search engine aware of permissions of the request. However, this is the most complicated/coupled approach. Given this is for one customer I imagine the approach we are going with will be sufficient.

**Comment by ryanslade** [comment]
After chatting with @tsenart in Slack, this looks like a good place to hook into sub-repo filtering: 
https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/search_results.go?L598:26
