### ISSUE TITLE
git: Apply sub-repo filtering on git.Stat

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#28267]
This called in [a number of places](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+git.Stat&patternType=literal) so we'll need to ensure that the sub-repo client is initialised in the following services too:

* frontend 
* worker, perhaps [here]( https://github.com/sourcegraph/sourcegraph/blob/5360eb750aa3ded4d97c12226c820388a4953a62/cmd/worker/workerdb/db.go#L16)

I would *not* suggest this as an initial task, as it is used in quite a few places.

**Comment by sashaostrikov** [comment]
Sorry, @mollylogue, stealing this one from you as it naturally became a part of https://github.com/sourcegraph/sourcegraph/issues/28265 :)
