### ISSUE TITLE
git: Apply sub-repo filtering on git.ReadDir

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#28265]
Used [here](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+git.ReadDir&patternType=literal)

It looks like this is only used from frontend so this can be done once [this pr](https://github.com/sourcegraph/sourcegraph/pull/28859) is merged.

It looks like the underlying method used is `git.lsTree` so we should add filtering there that uses our SubRepo client to filter the returned `fs.FileInfo` structs.

**Comment by ryanslade** [comment]
@sashaostrikov This looks like one you might be able to pick up so I'm assigning it to you. Please reach our for help if you need any help or more context.

**Comment by sashaostrikov** [comment]
Refactoring signature of `git.lsTree` function which is used in `lStat` function which is eventually used in `git.Stat` leads to that this implementing this issue will also close https://github.com/sourcegraph/sourcegraph/issues/28267 as I don't see a reason to complicate life with dividing these two tightly coupled issues in two separate PRs
