### ISSUE TITLE
git: Apply sub-repo filtering on git.NewFileReader

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#28264]
For now, I think for now the check should only happen in the exported method. If we make the change in the helper method, `newBlobReader` then it touches a larger surface area and is a bit harder to get correct. 

We can tackle that later when we get to `git.ReadFile`

**Comment by mollylogue** [comment]
@ryanslade would this be a good next issue to pick up?

**Comment by ryanslade** [comment]
Yep, this is a good option 👍

**Comment by mollylogue** [comment]
https://github.com/sourcegraph/sourcegraph/pull/29213
