### ISSUE TITLE
ci: annotate the build on soft failures (and if possible cancellations) 

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#28283]
See [RFC 497](https://docs.google.com/document/d/1QqOb0ZDuUDSB57RM_YLzqAPFaFnDGq-8AES5yppWiqg/edit#).

Soft failures are confusing as they appear red like a normal failure, the only distinction being a small warning sign. 
This led on many occasions teammates to think that the problem with their build was originating from that specific failure. 

By adding annotation on soft fails, we could make sure there is no ambiguity.

**Comment by bobheadxi** [comment]
Note - related to #26071

**Comment by bobheadxi** [comment]
I think this is superseded by https://github.com/sourcegraph/sourcegraph/issues/26083 , which aims to generate a wholistic summary of the steps that have failed/soft-failed/been cancelled
