### ISSUE TITLE
sg/ci: generate commands for reproducing steps locally

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#28286]
See [RFC 497](https://docs.google.com/document/d/1QqOb0ZDuUDSB57RM_YLzqAPFaFnDGq-8AES5yppWiqg/edit#)

Introduce an `sg` command to output commands ran in failed steps. Something like `sg ci showFailed $buildId`. If implementation of the previous point takes a significant amount of time having a list of commands to run locally to repro failed CI step would be a good temporary compromise

**Comment by bobheadxi** [comment]
@jhchabran I've adjusted this to be more explicit that what we're trying to do here is to generate an easy way to reproduce steps locally

**Comment by burmudar** [comment]
`sg lint` currently adds a hint to on how to fix it a failing lint. This can probably extended to provide additional information into other parts of the pipeline.
