### ISSUE TITLE
ci: feedback annotations

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#28292]
**Status**: Idea to be explored. 

Presently, there is no way to provide feedback (it's flaky, output is hard to read, etc ...) on a given step in the CI, other than reaching out on the #dev-experience channel. 

The annotation API allows to insert HTML statement, so we can insert a way to submit that feedback directly from there.

**Comment by bobheadxi** [comment]
Note: we should direct feedback to discussions
