### ISSUE TITLE
Flake:  TestRepository/access_repositories/private_repository and TestRepository/search_repositories disabled

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#28294]
- **Name of test:** `TestRepository/access_repositories/private_repository` and `TestRepository/search_repositories disabled`
- **Example failure:**: 
  - https://sourcegraph.grafana.net/explore?orgId=1&left=%5B%22now-7d%22,%22now%22,%22grafanacloud-sourcegraph-logs%22,%7B%22refId%22:%22A%22,%22expr%22:%22%7Bapp%3D%5C%22buildkite%5C%22%7D%20%7C%3D%20%5C%22TestRepository%2Faccess_repositories%5C%22%22%7D%5D
  - https://buildkite.com/sourcegraph/sourcegraph/builds/118040#6ae68de7-36f7-4942-b380-8fc3d33eb416
- **PR**: https://github.com/sourcegraph/sourcegraph/pull/28295

#### Additional details

This test failed 8 times over the past seven days.

**Comment by kopancek** [comment]
Copied over to our Jira: https://sourcegraph.atlassian.net/browse/CLOUD-200

Please track progress there.
