### ISSUE TITLE
VSCE: Ensure resources from previous instance are disposed on instance change 

### ISSUE THREAD

**Issue by tjkandala** [sourcegraph/sourcegraph#28306]
When a VS Code extension user changes their Sourcegraph instance URL, dispose all resources associated with that instance to prevent sending repository information to the wrong instance. This is an extra precaution on top of URL validation (e.g. is host in file URI same as current instance)

**Comment by abeatrix** [comment]
Updated behavior: VSCE will be reloaded automatically if changes in instance URL / access token has been detected

**Comment by jjinnii** [comment]
@abeatrix to look into whether it's possible to hide the file path or override with like null/not found info?

**Comment by tjkandala** [comment]
Addressed in v1.

> @abeatrix to look into whether it's possible to hide the file path or override with like null/not found info?

Can you please elaborate on this issue?
