### ISSUE TITLE
Rename deployment repo to cloud

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#28319]
As part of https://github.com/sourcegraph/sourcegraph/pull/28220 & https://github.com/sourcegraph/sourcegraph/pull/28219 we should renaming our deployment repo to `deploy-sourcegraph-cloud` vs `dot-com`

**Comment by daxmc99** [comment]
Also walkthrough buildkite UI

**Comment by danieldides** [comment]
As far as this ticket is concerned, there are 32 references to [`deploy-sourcegraph-dot-com`](https://sourcegraph.com/search?q=context:%40sourcegraph+deploy-sourcegraph-dot-com&patternType=literal) across various repos within Sourcegraph. Most are just links but I think they should still be updated. Github will [automatically redirect](https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository) any references to the previous URL. This might be a good candidate for a batch change.

I have not found any other references to the `deploy-sourcegraph-dot-com` repository in other buildkite pipelines. I think the buildkite jobs configured for that repository will need to be manually updated, however.

To-do:
1. [ ] Batch change to broadly update references to the repository across the org
2. [ ] Update the Buildkite pipelines and verify they still work

**Comment by danieldides** [comment]
After a few false starts I think I've finally figured out the Batch Change required to update references to the repository: https://k8s.sgdev.org/users/daniel.dides/batch-changes/apply/QmF0Y2hTcGVjOiI4bWdGNEpvOXFiWSI=?visible=5

This should be applied (and accepted) after the repository is renamed and any BuildKite pipelines repaired. We should also probably sync with Cloud SaaS to schedule this either before / after the go-live this Thursday.

cc @JenRed777  @daxmc99

**Comment by daxmc99** [comment]
I think we are good to proceed with this. We can keep an eye on buildkite to see if any issues come up and post in #dev-ops

**Comment by danieldides** [comment]
Awesome. I'll submit the batch and then this afternoon (3:30PM CT) I'll rename the repository and begin merging in the batch documentation changes.
