### ISSUE TITLE
LDAP authentication

### ISSUE THREAD

**Issue by martin-o-sw** [sourcegraph/sourcegraph#2832]
#### Feature request description

It would be great to add LDAP authentication to Enterprise pack.

#### Additional context

Most companies are using LDAP to manage bigger number of users so it would be great to have this authentication implemented. For example our company is using on-prem Bitbucket with LDAP authentication. At the moment we are looking for some capable search engine like SourceGraph, but we really miss this feature here.

**Comment by sqs** [comment]
Thanks for posting! We have this filed at 
https://github.com/sourcegraph/sourcegraph/issues/618#issuecomment-438778854. Could you please help us understand your needs by answering the questions in the bullet list and replying to that issue?
