### ISSUE TITLE
Ruby code intel doesn't properly identify method name composed of non-ASCII unicode characters.

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#28375]
#### Steps to reproduce:

1. Go to https://sourcegraph.com/github.com/mperham/sidekiq@main/-/blob/test/test_sidekiq.rb?L26:7
2. Note the method invocation `Sidekiq.❨╯°□°❩╯︵┻━┻`. Sourcegraph doesn't properly tag the `.❨╯°□°❩╯︵┻━┻` as a method that is hoverable / clickable.

![image](https://user-images.githubusercontent.com/1646931/144139593-c4e3ecd7-5dfc-44a1-aa33-868720117c96.png)

**Comment by chrismwendt** [comment]
[`createIdentCharPattern`](https://github.com/sourcegraph/code-intel-extensions/blob/7b119f8fe7607f795c94650bc3b976a6a4deb688/template/src/language-specs/identifiers.ts#L8-L13) is about to get very interesting...

<img width="518" alt="CleanShot 2021-11-30 at 16 09 17@2x" src="https://user-images.githubusercontent.com/1387653/144142730-6b2437fc-e7bb-4746-aa22-6dc45ae886e2.png">

**Comment by varungandhi-src** [comment]
This does work today because we use highlighting data for determining hoverability, and the token gets correctly marked as an identifier.

![](https://github.com/sourcegraph/sourcegraph/assets/93103176/845e8eda-1be0-4d8f-b35f-8c29431e047a)
