### ISSUE TITLE
Unhelpful error popover on select filter

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#28401]
This is an incorrect usage of the filter, but the popover doesn't provide a helpful suggestion of what would be an acceptable usage:
![image.png](https://images.zenhubusercontent.com/5467e9ba7c6ccc6277a5f103/d0f0e506-646e-4b4f-8ead-6754588e7bdf)

@rvantonder or @camdencheek, any suggestions on what content should go here?

**Comment by rvantonder** [comment]
can no longer repro

![Screen Shot 2022-10-25 at 12 54 39 PM](https://user-images.githubusercontent.com/888624/197869257-6fe2614a-63d8-4cc0-94bd-ccfe7337f19c.png)

**Comment by rvantonder** [comment]
oh, actually this is specific to `diff.`, still a bug:

![Screen Shot 2022-10-25 at 12 55 26 PM](https://user-images.githubusercontent.com/888624/197869422-7a6c214a-caad-435a-983e-2a0bd09170bc.png)

**Comment by camdencheek** [comment]
Just checked, still relevant.
