### ISSUE TITLE
Remove banner message for pure-docker deployments

### ISSUE THREAD

**Issue by jasonhawkharris** [sourcegraph/sourcegraph#28405]
#### Feature request description

There is currently a message that is triggered for single container docker for mac deployments. It should not show up for custom, multi-container, pure-docker deployments, but it does.

The message reads:

```
It looks like you're using Docker for Mac. Due to known issues related to 
Docker for Mac's file system access, search performance, and cloning 
repositories on Sourcegraph will be much slower.

Run Sourcegraph on a different platform or deploy it to a server for much
faster performance.
```

#### Is your feature request related to a problem? If so, please describe.

This has created confusion for customers running custom pure-docker deployments. The spirit of the message is to encourage customers to switch to a docker-compose deployment from a single-container, docker for mac deployment. This simply doesn't apply to customers using a pure-docker deployment.

#### Describe alternatives you've considered.

No alternatives have been considered. This is simply a confusing UI message for certain customers. A condition should be added to check if the instance utilizes a pure-docker deployment before serving the message to site-admins, and it should only be served to site-admins.

#### Additional context

This can also cause distress for the site-admin because it isn't clear whether this message is going out to their entire userbase, or site-admin only.

EDIT: As of now, the message is served to the entire user base, not just site-admin.

**Comment by pdubroy** [comment]
I think @sourcegraph/delivery is probably the right team to handle this. The [logic for detecting it](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/bcb74c87785d995fff6c1adb2b8f97609056728f?visible=3) is in the backend.

**Comment by jasonhawkharris** [comment]
Looks like [this is the function](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/bcb74c87785d995fff6c1adb2b8f97609056728f?visible=3) that should be adjusted.

**Comment by justdueck** [comment]
Hey team, are you able to provide an initial estimate on where this could fall in the roadmap/when a fix could be put in place? This is a fairly significant pain point for our admin at Netflix as it is causing a lot of concern and confusion amongst Sourcegraph users

**Comment by dan-mckean** [comment]
@justdueck we're looking to get this done in time for the next release out on the 20th Dec 🙂

**Comment by justdueck** [comment]
Perfect! Thanks for the update @dan-mckean

**Comment by kevinwojo** [comment]
@justdueck @jasonhawkharris this was merged in. Should be going out with the next release.
