### ISSUE TITLE
insights: spike issue for migrating away from TimescaleDB

### ISSUE THREAD

**Issue by CristinaBirkel** [sourcegraph/sourcegraph#28423]
One of the large remaining items on our roadmap for GA is: https://github.com/sourcegraph/sourcegraph/issues/24430

This spike issue is to front-load the investigation such that we are confident in what the work involves and if there are any big gotchas. After completing this spike issue we should be able to estimate the work and create any sub-tasks that will be needed for it.

**Comment by felixfbecker** [comment]
Do we consider this spike done or is there more work on the "spike" in iteration 10?

**Comment by leonore** [comment]
I think we've handled all the migrating away from TimescaleDB now: this should have been closed by #24430
