### ISSUE TITLE
K8S: Read-only filesystem support

### ISSUE THREAD

**Issue by kevinwojo** [sourcegraph/sourcegraph#28424]
Tracking requests to support read-only filesystem k8s deployments.

**Comment by donavonelli** [comment]
Ran into two separate issues with customers that have file restrictions making them run in a read-only file system.
One was solved by adjusting their security restrictions and allowing sourcegraph to operate with root privileges. The other they are unable to get security exemptions and we are dealing with that currently

**Comment by kevinwojo** [comment]
Tracking in #21839
