### ISSUE TITLE
Sourcegraph Pull Request Guidelines Checklist

### ISSUE THREAD

**Issue by adeola-ak** [sourcegraph/sourcegraph#28438]
This particular page is to serve as a guideline checklist one can refer to when creating their first couple PR's until it becomes a habit. This may result in a series of handook pages that I think will be helpful in supporting early career engineers at Sourcegraph

[Scratch document](https://docs.google.com/document/d/1wThhjiKwSgSh8LK9qri80urDSVVyvzNUOIc8jxmqySs/edit?usp=sharing)

In summary the page will detail

- suggested branch naming convention
- PR naming convention
- labeling and assigning in PRs
- Automation between PRs and closing existing related issues
- tips about when to merge
- tips on how to make PRs as descriptive as possible

**Comment by courier-new** [comment]
Suggestions on where this should live/prior art from Thorsten:
https://docs.sourcegraph.com/dev

For example, background information on code reviews:
https://docs.sourcegraph.com/dev/background-information/code_reviews

**Comment by adeola-ak** [comment]
- file add is pending review
- would like to link file [here](https://handbook.sourcegraph.com/departments/product-engineering/engineering/hiring/early-career-engineers) in handbook at the bottom in a new section titled: 'Tools to help them get started' 
- as more early career engineer files are thought of, I think a directory and lone handbook section can be made
- after approved i want to add this [link](https://www.atlassian.com/blog/git/written-unwritten-guide-pull-requests) to the checklist for further reading as seen in our docs at this [page](https://docs.sourcegraph.com/dev/background-information/code_reviews)
- i think in addition to the handbook, this will be nice to have [here](https://docs.sourcegraph.com/dev) in our docs, as thorsten suggested
