### ISSUE TITLE
Better observability into zoekt indexserver queue

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#28456]
We recently had sourcegraph/sourcegraph an hour out of date with nothing in the logs indicating why. The only thing we could see is that the server wasn't doing anything. This points to a problem likely occuring in the queue and/or the new option fetching code. Lets add some more observability to try and diagnose this issue.

https://sourcegraph.slack.com/archives/C023ELQLV7F/p1638370600136900

**Comment by ggilmore** [comment]
For instrumenting the queue, do you mean [queue.go](https://github.com/sourcegraph/zoekt/blob/master/cmd/zoekt-sourcegraph-indexserver/queue.go) itself?

**Comment by keegancsmith** [comment]
I think we already have some instrumentation there? I didn't actually check :) But that would be helpful to see queue sizes/etc. The thinking behind this issue is some deeper information (like logs/etc) that actually help us diagnose the state of the system if/when this happens again.

**Comment by keegancsmith** [comment]
@stefanhengl this would probably help you understand why the queue is being slow to reindex everything in #29746

**Comment by keegancsmith** [comment]
@ggilmore has made some great progress on this by adding a way to get a dump of the queue: https://github.com/sourcegraph/zoekt/pull/317

**Comment by ggilmore** [comment]
We now have Grafana dashboards for this metric: https://sourcegraph.com/-/debug/grafana/d/zoekt/zoekt?orgId=1 ( see the indexing queue statistics section. 

However, this has revealed that our  queueing delay tail (how long a job sits in the queue before it's processed) is quite long (approaching ~2 days)! 

We'll do a deeper investigation on this in the coming weeks.

**Comment by stefanhengl** [comment]
implemented in https://github.com/sourcegraph/zoekt/pull/317
