### ISSUE TITLE
search: re-enable monitoring of unindexed symbol search on monorepo

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#28457]
This query was failing on every request (1min), causing many failures in symbols. I believe it was failing since symbols never finished processing the monorepo. My best guess is this caused some queues to form and never unblock => unavailability of symbols => symbol queries fail => search alerts go off.

```
repo:^github\.com/sgtest/megarepo$ type:symbol IndexFormatVersion rev:main
```

It would be great to re-enable the perf monitoring for this again so we can see proof that we have improved symbol searches once we have. So we can likely just tackle the low hanging fixes here, then re-enable.

@chrismwendt I assigned you since I know you are investigating this stuff. If you don't have bandwidth to do more work on symbols service our team is happy to pick up this problem.

**Comment by chrismwendt** [comment]
I'm guessing the channel of search requests is completely backed up waiting on parsing the megarepo. Ideas:

- Make a goroutine for each repo so that each repo gets some CPU time
- [Try implementing Rockskip](https://github.com/sourcegraph/sourcegraph/issues/28498) (I might start working on this next week)

**Comment by keegancsmith** [comment]
FYI @sourcegraph/search-core I just tried this query out again, and we still timeout with no results.

```
repo:^github\.com/sgtest/megarepo$ type:symbol IndexFormatVersion rev:main
```

<details>
<summary>0001-search-blitz-renable-mono_rev_symbol_small.patch</summary>

```patch
From cde09af3cb120098ba9edb9dc21c479f83713444 Mon Sep 17 00:00:00 2001
From: Keegan Carruthers-Smith <keegan.csmith@gmail.com>
Date: Thu, 10 Feb 2022 09:19:56 +0200
Subject: [PATCH] search-blitz: renable mono_rev_symbol_small

This reverts commit 5929cb6887733af4df3161223899e46447837c8c. We
disabled this since it was causing the symbols service to be
unresponsive.

Test Plan: manually run query on sourcegraph.com and get results.
---
 internal/cmd/search-blitz/queries.txt | 8 ++------
 1 file changed, 2 insertions(+), 6 deletions(-)

diff --git a/internal/cmd/search-blitz/queries.txt b/internal/cmd/search-blitz/queries.txt
index 3b221d5174..c438585290 100644
--- a/internal/cmd/search-blitz/queries.txt
+++ b/internal/cmd/search-blitz/queries.txt
@@ -72,12 +72,8 @@ repo:^github\.com/sgtest/megarepo$ patterntype:structural strings.ToUpper(...) r
 # mono_symbol_small
 repo:^github\.com/sgtest/megarepo$ type:symbol IndexFormatVersion
 
-## This query has been disabled due to it causing the symbols service to
-## degrade. We want to enable it again, tracked at
-## https://github.com/sourcegraph/sourcegraph/issues/28457
-##
-## # mono_rev_symbol_small
-## repo:^github\.com/sgtest/megarepo$ type:symbol IndexFormatVersion rev:main
+# mono_rev_symbol_small
+repo:^github\.com/sgtest/megarepo$ type:symbol IndexFormatVersion rev:main
 
 # mono_diff_small
 repo:^github\.com/sgtest/megarepo$ type:diff   author:camden before:"february 1 2021"
-- 
2.34.1

```

</details>

**Comment by keegancsmith** [comment]
> I added the megarepo to my local Sourcegraph instance and the symbols service successfully processed it in 15 minutes

The problem may be that the commit velocity outpaces the indexing time. However, I would expect after the first successful index we can then start doing incremental indexing and start succeeding. I'm not familiar enough with the logic around which previous index to use to know if that should work under high commit velocity.

Note: I just tested manually, I didn't re-enable search-blitz. I did not give enough time more than likely between attempts to see if it started working.

**Comment by chrismwendt** [comment]
> The problem may be that the commit velocity outpaces the indexing time.

I believe that's the main problem. It's like a tsunami of cold starts 🌊 

Theoretically, it should eventually finish one cold start and then subsequent requests can reuse that SQLite DB. Other cold starts that already started will blindly continue, though. The logic for selecting the previous index to use is quite simple: pick the newest file that ends in `.zip`, meaning indexing has completed. The file extension `.zip` is mostly a historical artifact, but it's actually a SQLite DB.

https://github.com/sourcegraph/sourcegraph/blob/main/cmd/symbols/internal/database/writer/fs.go#L11

**Comment by keegancsmith** [comment]
Great. I'm happy to re-enable this and see what happens. I'll do it tomorrow morning so I can monitor the impact over time while working.

**Comment by chrismwendt** [comment]
Indexing the megarepo might repeatedly fail until https://github.com/sourcegraph/sourcegraph/pull/31110 is merged (I'm waiting a bit in case @efritz wants to 👀 it).
