### ISSUE TITLE
ci: migrator changes do not trigger building the migrator image 

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#28462]
On this [build](https://buildkite.com/sourcegraph/sourcegraph/builds/118500#dff4fdcf-38dc-4f7e-a454-281dc3ccead7) @ryanslade ~changed the service `migrator`~ created a new service. His build succeeded but later failed on the main branch. 

Failing build on main: https://buildkite.com/sourcegraph/sourcegraph/builds/118500
PR: https://buildkite.com/sourcegraph/sourcegraph/builds/118375

EDIT: this service was totally new, but the problem remains. We do not have any documentation either on how to do that. 

**Problem**: This happened because the step building the migrator image wasn't run on the PR build, whereas it's obviously built on the main branch. This led to a failure that would have easily been avoided. Presently we have no way to tie those changes to a docker build step. 

This could have been avoided if the build type had been `main-dry-run`, but that's not obvious at all for the CI users and they should not have to keep in mind what is tested and what it isn't, it's too much cognitive weight. 

**Possible solutions** (non-exhaustive): 
- 🩹 The bandage solution would probably be to detect those changes and trigger the associated build by writing a specific check. 
- A more robust solution would be to be able to link the image building steps to the changed code, to fix this entire class of problem at once.
- (something else?) ...

**Comment by efritz** [comment]
@jhchabran Can you link to the failed build? It looks all green after I fixed the build.sh permissions.

**Comment by jhchabran** [comment]
@efritz I'm sorry, I mistook you for the PR author, it was Ryan and you were the reviewer. 

There are no action required from you here, it was a notice ping and incorrectly targeted at you 🙇

**Comment by bobheadxi** [comment]
Isn't this scope broader? No image changes trigger any image builds today on PRs, the only way to do it is `main-dry-run` and friends. That said, it's hard to detect what a service change is - we'd need to do something elaborate a la what we do for executors here: https://github.com/sourcegraph/sourcegraph/blob/main/enterprise/dev/ci/internal/ci/operations.go#L650

That said, a potentially easy fix would be to check the respective build directories and if _any_ of the directories change there trigger a full build of candidate images.

More granularly, we can build specific images if their respective build directories have changed
