### ISSUE TITLE
ci: export the JS tests output in JUnit format 

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#28471]
[Buildkite analytics](https://buildkite.com/test-analytics) is just around the corner and presently only parse JUnit xml format. Beta Release is expected to be this week. 

This means we need to convert the output of our tests in JUnit xml outputs to enable the test results to be parsed. 

Please not that for now we don't know yet how we will have to submit that to Buildkite. See #28472.

Prior work: https://github.com/sourcegraph/sourcegraph/pull/28262

**Comment by taylorsperry** [comment]
@jhchabran This is blocked along with https://github.com/sourcegraph/sourcegraph/issues/28469, correct?

**Comment by umpox** [comment]
@taylorsperry That's my assumption, we can generate the XML reports fine through https://github.com/sourcegraph/sourcegraph/pull/28262 but until we know how to actually submit them there's not any value in doing son

**Comment by jhchabran** [comment]
https://github.com/sourcegraph/sourcegraph/pull/28262 has been merged, closing this.
