### ISSUE TITLE
search: Support global mode with `repo:` filters

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#28475]
### Context

Our global search mode code path was initially designed for sourcegraph.com as a way to make searching over millions of repos efficient. This mode skips repository resolution altogether for file/content searches, hitting Zoekt directly, and later hydrating results with repo metadata in the streaming API handler.

This approach, however, isn't taken when there are any `repo:` filters in the query. We're missing out on performance, since a repo filter can match a large amount of repos (or even all repos, with `.*`), and the ideal query plan there wouldn't be paginating repos and searching bit by bit, but instead sending the repo and rev filters along to Zoekt at once.

This would require us to store in Postgres which revisions at which repos are indexed by Zoekt, so that we can pass to searcher all those that are not, concurrently with Zoekt searching those that are.

Fedora, having 34k repos in sourcegraph.com, would benefit immensely from this, potentially bringing search times down to sub-second. Any large customer that often searches over a large sub-set of repos would also benefit from this.

**Comment by tsenart** [comment]
FYI @rvantonder @camdencheek

**Comment by keegancsmith** [comment]
@tsenart this is in our TODO column. Is it work we intend on doing in the next month or two? If not, we should probably put it under "no status" in our backlog?

**Comment by tsenart** [comment]
I'll move it to No status. Thanks for spotting.

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket, please let us how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
