### ISSUE TITLE
ci: wrap submission of test reports to Buildkite test analytics

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#28472]
Submitting data to Buildkite Analytics has to be streamlined, to avoid having to deal with a complicated bash script (see https://github.com/sourcegraph/sourcegraph/blob/main/dev/ci/go-test.sh). Buildkite analytics works by uploading to their API, with a specific `Suite Key` a JUnit XML report of the tests that were run. 

Basically, what we want is to make it easy for any engineer writing a test step to submit the results, as long as they are in a compatible format.

A word of caution about the existing scripts: often a failure when running tests will interrupt the process due to the `set -e` flag at the top of these scripts. This has the side effect of preventing the upload to happen.

**Comment by jhchabran** [comment]
We heard back from buildkite that they will bundle the submission in `buildkite-agent` like the annotations. We can close this.

**Comment by bobheadxi** [comment]
Revisiting this with https://github.com/sourcegraph/sourcegraph/pull/31969
