### ISSUE TITLE
Add delay for processing if commit doesn’t exist

### ISSUE THREAD

**Issue by macraig** [sourcegraph/sourcegraph#28494]
Some Sourcegraph instances (likely using a custom Git infrastructure to support monorepos) may receive a precise code intelligence upload before the remote known by Sourcegraph has been updated to include it.

We should support this case by allowing the uploader to specify a window in which the commit should become visible. Within this period, failure to resolve the target commit during processing should cause the processing job to be requeued.

**Comment by efritz** [comment]
#28501 contains a draft solution.

**Comment by alexfogg** [comment]
Adding more customer context here that was getting buried in the Slack thread:

> Just wanted to report back that we found an example where our LSIF upload failed (and only succeeded after a busy/wait loop).  In this particular example a commit landed at 9:53AM -- it was available in gitlab from the day before (because it had already been pushed to a user remote) but it wasn't on the main branch of the repository until 10:07AM, which is when the upload finally succeeded.  Is there some config option to specify that sourcegraph should not only fetch commits from the main branch when checking an LSIF upload?  Or is this a bug of some kind?

**Comment by efritz** [comment]
They can set `PRECISE_CODE_INTEL_COMMIT_RESOLVER_MAXIMUM_COMMIT_LAG` on the `worker` service to a value like `24h`.
