### ISSUE TITLE
Web page crashes on very long, single-line JSON file

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#28515]
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:** Chrome 95.0.4638.69 and Firefox 94.0.2  on MacOS

#### Steps to reproduce:

1. Open a browser to https://sourcegraph.com/github.com/salesforce/ctrl/-/blob/ctrl-vocab.json?subtree=true
2. If it loads, click on the code and/or scroll to the right 
3. Web page will eventually crash (Firefox sometimes crashes and sometimes just does not load the page)

![image](https://user-images.githubusercontent.com/23640224/144493777-3ddd8c52-92c3-4698-869d-70a527a6bf93.png)

Also the JSON is not syntax highlighted

#### Expected behavior:

JSON is highlighted and scrolling or clicking doesn't crash the browser when loading

#### Actual behavior:

JSON is not highlighted and scrolling and/or clicking crashes the web browser

**Comment by umpox** [comment]
Confirmed fixed when CodeMirror is enabled. Closing this issue!
