### ISSUE TITLE
support searching for "before:<commit-ish>" and "after:<commit-ish>"

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#2851]
When interested in finding results that occur after or before a specific commit, it would be nice to not have to determine the exact timestamp of the commit myself. For example, one use-case would be searching over a range of known bad commits and good commits based on their timestamp:

```
type:diff before:<good commit> after:<bad commit>
```

Reported by https://app.hubspot.com/contacts/2762526/company/407948923

**Comment by camdencheek** [comment]
This has existed since before I started at Sourcegraph, so I think we can close this 😄
