### ISSUE TITLE
ci: Buildkite doesn’t notify when flakes have been fixed by retrying

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#28580]
Backported from https://docs.google.com/document/d/1N9QoZ9K2VFUMQtxXWp9DWIyDrof1GcddN8XMLUUGOes/edit#heading=h.pndwnyunkjix 

TODO: check again after Buildkite tests analytics is released.

**Comment by bobheadxi** [comment]
can be done with `sg ci status`, could potentially document
