### ISSUE TITLE
Delete user permissions in the background when a user is deleted

### ISSUE THREAD

**Issue by asdine** [sourcegraph/sourcegraph#28591]
When a user is (hard/soft) deleted, we need to delete all repository permissions related to that user.
Because the number of repositories can be very large, this action cannot be performed synchronously.

Instead, whenever a user is deleted, add a line to a dedicated job table and use a background job to cleanup the user permissions.

**Comment by indradhanush** [comment]
Commenting to keep track of: 

We might need to expose an API for the status of the background job related to the deleted user.

**Comment by asdine** [comment]
Closing this in favor of https://github.com/sourcegraph/sourcegraph/issues/36355
