### ISSUE TITLE
Visiting GitHub repo on Sourcegraph.com doesn't auto-add it

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#2860]
https://sourcegraph.com/github.com/01org/ciao 404s, despite http://github.com/01org/ciao being a valid repo. Expected behavior is for the repository to be auto-added to Sourcegraph when I visit it.

**Comment by tsenart** [comment]
Looking into this now.

**Comment by tsenart** [comment]
This seems to be the known issue with us not handling renamed repos.

http://github.com/01org/ciao has been renamed to https://github.com/ciao-project/ciao.

https://sourcegraph.com/github.com/ciao-project/ciao works.

**Comment by sqs** [comment]
Got it, thanks. Closing this because it's a known issue and this extra issue adds no value.

**Comment by chrismwendt** [comment]
Is https://github.com/sourcegraph/sourcegraph/issues/1966 the tracking issue for repository renaming? Did https://github.com/sourcegraph/sourcegraph/issues/914 not fix it?

**Comment by tsenart** [comment]
We're working on repository handling improvements in #2025, which should make us handle upstream codehost repository renames.

**Comment by tsenart** [comment]
(#2025 is the successor of #914)
