### ISSUE TITLE
insights: [frontend] randomly select color for capture group generated series

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#28628]
Insight series generated by capture groups will need randomly generated colors.

Currently, there is a problem in the relationships exposed by the API such that the time series returned by `dataSeries` will not match the cardinality in the `presentation` or `dataSeriesDefinitions` when generated by capture groups. We cannot trivially add fake series to the `presentation` or `dataSeriesDefinitions` without clients being unable to decipher "real" from "fake" series, and being able to populate edit forms for example.

In the short term, it may be easiest to do the following:
* On the frontend perform some kind of hacky substitution for capture group generated insights. Something like `data?.view.content.forEach(content => content.series.forEach( (series, i) => series.stroke = series.stroke || DEFAULT_COLOURS[Math.floor(Math.random() * DEFAULT_COLOURS.length)].color))
` when we load the series.

Long term, we would like to evolve the API to be able to provide `presentationDefinition` as well as `presentation` options that expose different cardinality for different purposes, the first being the "truth" of how the series was defined, and the second being the reality "which series are returning".

**Comment by coury-clark** [comment]
As a follow up from the sync:

We don't actually want to randomly generate colors. Ideally, we would have deterministic colors based on the series match, regardless of the order in which they match.

**Comment by coury-clark** [comment]
Scope for v1:
1. Minimum we need random colors generated at page load. There doesn't need to be any persistence or determinism.
2. As a stretch goal (time allowing), consistently hash the label text to the color set so that we will get deterministic colors given a deterministic input set of labels. In other words, the colors would only change when the set of labels change.

**Comment by vovakulikov** [comment]
It has been closes by https://github.com/sourcegraph/sourcegraph/pull/28855
