### ISSUE TITLE
Make it easy for users to figure out which version of sourcegraph they're using

### ISSUE THREAD

**Issue by analogue** [sourcegraph/sourcegraph#2862]
#### Feature request description

A user should be able to figure out which version of sourcegraph they're currently using via the web interface w/o having to dig into the source code of a given page.

#### Is your feature request related to a problem? If so, please describe.

Issues on github are tagged with the version of sourcegraph the bug fix or feature request will be available in. In order for a user to be able to request their installation of sourcegraph be upgraded by sourcegraph admins, it must first be determined what the current version of sourcegraph is.  The version of sourcegraph is not clearly identified on any pages that I could find served up by the web interface. I've checked settings, profile, account, page footers, etc.  

#### Describe alternatives you've considered.

Looking at the page source code in a browser looks like it has the version of sourcegraph embedded (in this case, 3.1.2), but that requires users to "View page source" which doesn't seem too obvious.
```
<script ignore-csp>
		window.context = {"externalURL":"https://sourcegraph.yelpcorp.com","xhrHeaders":{"X-Csrf-Token":"redacted","X-Requested-With":"Sourcegraph","x-sourcegraph-client":"https://sourcegraph.yelpcorp.com"},"csrfToken":"redacted","userAgentIsBot":false,"assetsRoot":"/.assets","version":"3.1.2","isAuthenticatedUser":true,"sentryDSN":null,"siteID":"redacted","siteGQLID":"redacted","debug":false,"showOnboarding":false,"emailEnabled":false,"critical":{"update.channel":"release"},"likelyDockerOnMac":false,"needServerRestart":false,"isClusterDeployment":false,"sourcegraphDotComMode":false,"accessTokensAllow":"all-users-create","allowSignup":false,"resetPasswordEnabled":false,"authProviders":[{"isBuiltin":false,"displayName":"OpenID Connect","authenticationURL":"/.auth/openidconnect/login?pc=redacted"}],"updateScheduler2Enabled":true}
		window.pageError =  null 
	</script>
```

#### Additional context

Just make it easy to find 😃

**Comment by sqs** [comment]
Yes, we need to make it possible for non-site admin users to determine the version. Thank you for the report.

My proposal is to add it on the user profile sidebar in the red scribbled area:

![image](https://user-images.githubusercontent.com/1976/54698619-f9d64680-4b05-11e9-8f5e-af799a9ed951.png)
