### ISSUE TITLE
Experimental search pagination / incremental search API

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#2865]
Today, it is only possible to retrieve whether or not your search query has more results via e.g. `limitHit`. You must then retry your query and request a higher number of results via the `count:` search query filter.

It would be nice if we had proper pagination via an offset + count.

## Why

Running Sourcegraph with thousands of repositories and executing a heavy/large query on all of those is expensive, and can take several minutes depending on the query (for example, symbol searches). This results in timeouts due to (1) a 1-minute-max hard-coded search timeout and (2) it is desirable to have the HTTP proxy that in front of Sourcegraph have sane timeouts like e.g. 2 minutes. Thus, this is beneficial because:

1. Allows scripts to workaround search timeouts.
2. Allows scripts to consume search results incrementally.
3. For users who care, allows searching for results in a specified order via adding e.g. `offset:0` to your query.

## Implementation

The implementation would be something like passing a pagination parameter down through the search pipeline which controls whether or not we construct search results in a stable order or not. By doing this, we can make smart choices to enable both paginated search to be fast AND still have fast time-to-result unstable ordering for the webapp UI.

Reported by https://app.hubspot.com/contacts/2762526/company/407948923

**Comment by nicksnyder** [comment]
Can you explain the benefit of this more?

Would the implementation be to run the full search on the backed for each page, sort, and then slice off the desired results?

**Comment by nicksnyder** [comment]
Is this supposed to be in the 3.3 milestone?

**Comment by slimsag** [comment]
@nicksnyder I've updated description with more details. No, it is not a part of the 3.3 milestone yet (but could be), as I have not yet had time to investigate how hard this will be so I cannot commit to a timeline yet.

I estimate either 3.3 or 3.4 is realistic, currently, but more investigation is needed to have a more concrete timeline.

**Comment by nicksnyder** [comment]
Thanks for adding more details. If the goal is to actually transform our search pipeline to be stable such that we can do actual pagination, that seems like it could be a decent amount of work.

We would have to think about how to accomplish this in both the indexed call path and the non-indexed call path (or if we can't do both, decide if that is an ok limitation).

**Comment by slimsag** [comment]
Yeah I am well aware of the challenges here. The question is just: How much work is that _actually_? Search result generation is an inherently orderly thing, the only question is at home many independent locations do we parallel join results and how hard would refactoring those locations to support parallel joining and consecutive joining be?

This is something that I am investigating as this is a priority for us. My result may very well be a few PRs that do it with an explanation of how/why, or it may be me taking a step back and saying it may be a serious undertaking and we should reconvene with relevant customers to figure out alternatives that may be suitable.

**Comment by slimsag** [comment]
The open question here is whether or not (1) search perf improvements in general and (2) search result streaming would be good enough to remove the need for pagination. Once I address (1) I will ask around to uncover the answer to this question, until then, this is backlogged.

**Comment by slimsag** [comment]
(Incremental search as me and @ijt discussed would effectively be the same as what I was proposing here, if done it would closed this issue.)

**Comment by ijt** [comment]
> (Incremental search as me and @ijt discussed would effectively be the same as what I was proposing here, if done it would closed this issue.)

It would at least be similar. I'm proposing to make the backend API very simple, in the sense that the GraphQL `Search` query would have an integer `batch` parameter that would determine which repos to search. Each batch would cover at most a fixed number of repositories. That would greatly reduce the variance of GraphQL `Search` queries, so we would have fewer issues with timeouts.

It would be the front-end's responsibility to keep on asking for more batches until it has a full page of results to display or it runs out of batches to request. The front end could continuously report progress in terms of percent done or number of repos searched out of the total.

**Comment by nicksnyder** [comment]
> it is desirable to have the HTTP proxy that in front of Sourcegraph have sane timeouts like e.g. 2 minutes

@slimsag Can you clarify what kind of timeout? For example, does this requirement exclude the possibility of HTTP request that streams results in the response? Even if it doesn't preclude streaming, do you think that users will find a pagination API easier to consume?

**Comment by felixfbecker** [comment]
Is this 3.6 or 3.8?

**Comment by slimsag** [comment]
3.8, as noted by the assigned milestone.

It is my goal to get an experimental version of _the API_ in 3.6, but it is a very close deadline so we will see. For more info on that, follow https://github.com/sourcegraph/sourcegraph/pull/4230

**Comment by slimsag** [comment]
> Can you clarify what kind of timeout? For example, does this requirement exclude the possibility of HTTP request that streams results in the response?

This part is flexible and it seems reasonable to assume that if data is being transferred the request will not be killed for a _longer_ period of time, within reason.

> Even if it doesn't preclude streaming, do you think that users will find a pagination API easier to consume?

Yes, I do believe a pagination API would be easier to consume in general.

Secondly, I looked into the feasibility previously of doing non-GraphQL streaming and it would be quite complex to actually implement due to the way the code is structured: https://sourcegraph.slack.com/archives/CHEKCRWKV/p1558473812028100

The above two points make GraphQL pagination API a clear win in my view.

**Comment by zsimic** [comment]
FWIW, I find the elasticsearch scroll idea to be pretty good for this kind of thing: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html#request-body-search-scroll

Rather than requesting a page, and then iterating on `page + 1` until `pageCount` is hit, client basically does an initial query which yields an optional `scroll_id`, and then client can choose to continue and get next "page" that way (until there's no more `scroll_id`).

**Comment by slimsag** [comment]
@zsimic You'll be happy to know that pattern is effectively the same pattern we plan to use! :) Basically, you'd request N results and we'd give you them + a cursor ID (same as your `scroll_id`) and by passing us that same cursor ID in the future you can get the next "page" of results until there are no more to consume.

**Comment by tsenart** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.9 release is scheduled for tomorrow** at 10:00 CEST.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by tsenart** [comment]
I believe this was resolved by https://github.com/sourcegraph/sourcegraph/pull/4796 in time for the 3.9 release so closing this issue. If not, please re-open and adjust the milestone accordingly.

**Comment by slimsag** [comment]
This will be in v3.9, with some caveats & known limitations. See the documentation for further details: https://docs.sourcegraph.com/api/graphql/search#sourcegraph-3-9-experimental-paginated-search
