### ISSUE TITLE
Cannot access Azure DevOps git repo with space in project name

### ISSUE THREAD

**Issue by abeyerpath** [sourcegraph/sourcegraph#2867]
- **Sourcegraph version:** 3.2.0
- **Platform information:** Ubunutu 18.04 Docker 18.06.1-ce

#### Steps to reproduce:

1. Use "Single Git repositories" external service to configure access to Azure DevOps git repos via ssh
2. Add project/repo path containing a space
```
{
  "url": "ssh://MyOrg@vs-ssh.visualstudio.com/v3/MyOrg/",

  "repos": [
    "Project1/RepoName",
    "Project 2/AnotherRepo"
  ]
}
```

#### Expected behavior:

Both repos available in sourcegraph

#### Actual behavior:

Both repos clone and index, become available for search and will generate search results. 

"Project1/RepoName" works correctly. However for "Project 2/AnotherRepo", with a space in project name, all links to blob paths for individual files/folders as well as the repo settings page give "Repository not found" errors.

**Comment by keegancsmith** [comment]
> Both repos clone and index, become available for search and will generate search results.

Given that, I don't think this is an error in gitserver / repo-updater. More than likely it is something wrong in the frontend or possibly the graphqlbackend. @attfarhan I think you are the best to investigate since you are modifying the frontend search code as is.

**Comment by Jamesits** [comment]
I can confirm this bug with a similar config. Tried space character in project name or use `%20`, the result is the same.

**Comment by sqs** [comment]
Thank you for reporting. To help us understand priority, is using spaces in repo names a common thing in Azure DevOps? @jamesits Are you also using Azure DevOps?

**Comment by abeyerpath** [comment]
As a educated guess...I'd suspect that "human friendly" naming is probably _more_ common on AzDO than other environments simply because it's sort of the hosted next-gen version of TFS, which was traditionally very UI driven and thus probably tended to give less thought to making naming schemes URL/machine friendly. There also isn't any immediate feedback when naming a project to discourage doing so.
That said, I have limited experience with either TFS or AzDO outside my current organization, so not sure how prevalent this actually is.

**Comment by Jamesits** [comment]
Yes I’m using Azure DevOps

**Comment by Jamesits** [comment]
I did some experiments with space in either project name or repo name, in both cases, sourcegraph will return 404 when trying to view files. Search is not impacted by this. I guess there are some double/iterative URL decode issues happening somewhere.

Note that Azure DevOps git URL looks like `https://dev.azure.com/{org}/{project}/_git/{repo}`, and you can have spaces in both project name and repo name.

**Comment by keegancsmith** [comment]
We need to triage this and determine where this is breaking down in our product. @attfarhan can you own reproducing this and finding the exact requests which are failing? And then look at the trace to see what is passed to the DB for the lookup. I took a quick look since I thought it may be a problem in our URL routing, but the regexes don't seem to care: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@a1962efd66971aa9a26161e7469e58e7c82a8889/-/blob/pkg/routevar/repo.go#L29:2

I think the guess that we may be passing URL escaped strings to the DB is likely the best bet.

**Comment by Jamesits** [comment]
Any updates on this?

**Comment by keegancsmith** [comment]
ping @attfarhan

**Comment by attfarhan** [comment]
Haven't had a chance to take a look but I'll add this to my work plan for this milestone

**Comment by christinaforney** [comment]
Hi @Poltergeisen - what organization are you with? How many users do you have on your instance? I want to make sure I have this associated and prioritized correctly. We have a lot of big improvements we are working on right now, so we need to be pretty rigorous about how we prioritize, making sure we are working on things with the biggest impact for our users.

If you prefer, you can email me privately at christina@sourcegraph.com

**Comment by ageisen2000** [comment]
I am currently the only person using sourcegraph. 
I was evaluating it before I suggest it to my boss. 

Not sure if that helps at all. I work for a fairly large multinational Corp.

**Comment by StevenTCramer** [comment]
I just started with a new organization and guess what they have spaces in their repo names.  Azure Dev Ops makes that easy to do.

**Comment by nareshkbohra** [comment]
Is there any update on this? I have a space in project name due to which I get a 404 everytime I try to access a file. Search works fine though.

**Comment by christinelovett** [comment]
https://app.hubspot.com/contacts/2762526/company/1085513342

**Comment by felixfbecker** [comment]
Related search issue: https://github.com/sourcegraph/sourcegraph/issues/12296
I added a failing integration test for this a while back that is partly commented out (because of the issue linked). It only tests for spaces in the file name, not in the repo name. It should be easy to duplicate that test for a repo name with spaces too.

**Comment by Ollie-Armitage** [comment]
Hi, Any updates on this as far as the Project Name goes? Seems to be working for the repo, and will initially load when searching: (Where the project name is Ascenti%20Digital)
![image](https://user-images.githubusercontent.com/26070111/146532322-746b3b43-c6a7-47cb-a134-961b5455b9d3.png)

When clicking on the search item however, It reevaluates the repo string to "Ascenti\ Digital":
![image](https://user-images.githubusercontent.com/26070111/146532620-b265361e-a1c6-4245-9071-9e821d650d73.png)

Thereby failing to find the file.

**Comment by keegancsmith** [comment]
cc @sourcegraph/search-product ^^

**Comment by rvantonder** [comment]
We'll track https://github.com/sourcegraph/sourcegraph/issues/29177 and follow up
