### ISSUE TITLE
Create CodeWing in GCP

### ISSUE THREAD

**Issue by JenRed777** [sourcegraph/sourcegraph#28678]
We now own CodeWing and need to migrate from their GCP Org to ours. In order to do this we need to just start up the server and have the DNS point to it. 

- [x] Create new GCP Project
- [x] Follow install instructions in https://github.com/sourcegraph/codewing#readme
- [x] Transfer over DNS to our Origination

**Comment by danieldides** [comment]
> Create new GCP Project
https://github.com/sourcegraph/infrastructure/pull/2988

**Comment by danieldides** [comment]
> Follow install instructions in https://github.com/sourcegraph/codewing#readme

I think this is deployed and working. I'll need to confirm with @chrismwendt that the functionality is as expected. I'll also need his assistance in transferring the DNS under Sourcegraph.

```
http 35.226.233.23 Host:api.codewing.dev --follow
HTTP/1.1 404 Not Found
Access-Control-Allow-Origin: *
Cache-Control: no-transform
Content-Length: 35
Content-Type: application/json; charset=utf-8
Date: Wed, 29 Dec 2021 23:16:09 GMT
Server: Caddy
Strict-Transport-Security: max-age=31536000;
X-Content-Type-Options: nosniff
X-Frame-Options: DENY

{
    "error": "the API route is POST /"
}
```

I had to make [some changes](https://github.com/sourcegraph/codewing/pull/2) to the Codewing deployment source code to get it working. I've tried to make them minimal and comment where I can.

@sourcegraph/cloud-devops  -- Currently, this service is being deployed on a GCP instance running Ubuntu, using it's own Caddy instance to reverse proxy the application. Do we want to pull this into the main Cloud Kubernetes cluster and run it there in a namespace? The current deployment is very non-standard compared to our other services. We also don't have any CICD process set up for it.

As it is, I think I'm blocked on this one now until the new year and people are back.

**Comment by JenRed777** [comment]
This needs a review from @chrismwendt

**Comment by chrismwendt** [comment]
@danieldides has the auth code for the DNS transfer, which can take 5-7 days to complete.

The API service itself might not need to live much longer because some of the tech is getting integrated into Sourcegraph, which will make CodeWing obsolete. That might influence whether or not it's worth pulling this into the main Cloud Kubernetes cluster.

**Comment by danieldides** [comment]
DNS transfer has been initiated. Once it's complete, we can configure the Cloudflare NS entries and then create the A-records in Cloudflare.

**Comment by danieldides** [comment]
Waiting on a small snafu related to associating the dns entry with the landing page on Firebase. The API is fully deployed the configured with the server, however.

**Comment by danieldides** [comment]
This PR should close out this issue: https://github.com/sourcegraph/infrastructure/pull/3028

**Comment by danieldides** [comment]
DNS transferred and website deployed.
