### ISSUE TITLE
Ensure batch spec hasn't been applied yet in "ReplaceBatchSpecInput"

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#28685]
In `ReplaceBatchSpecInput` we don't check whether the batch spec has been applied yet:

https://github.com/sourcegraph/sourcegraph/blob/ff7872c994325624839d42acaa66c73d4e56e669/enterprise/internal/batches/service/service.go#L465-L475

But we **should**, because otherwise the `DeleteBatchSpec` will fail due foreign keys.

We should do the same thing that we do in `RetryBatchSpecWorkspaces`:

https://github.com/sourcegraph/sourcegraph/blob/ff7872c994325624839d42acaa66c73d4e56e669/enterprise/internal/batches/service/service.go#L1146-L1153

**Comment by chrispine** [comment]
fixed

**Comment by mrnugget** [comment]
Fixed in https://github.com/sourcegraph/sourcegraph/pull/28840
