### ISSUE TITLE
Explore using Caddy in front of Sourcegraph for easier TLS configuration

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#2868]
Explore the option of adding docs for putting Caddy in front of the Sourcegraph front-end to make setting up TLS easier. Prompted by [this tweet](https://twitter.com/mholt6/status/1108437236456939520) from @mholt

**Comment by beyang** [comment]
@ggilmore to investigate this as part of https://github.com/sourcegraph/sourcegraph/issues/2285 and https://github.com/sourcegraph/sourcegraph/issues/2475 and compare to Nginx experience.

**Comment by keegancsmith** [comment]
To add another vote for this, originally I  suggested this but nginx was believed to be the better option due to it having more resources/popularity. However, I have setup caddy as a reverse proxy in our internal infra due to the great letsencrypt support. So look for how we do tls for bitbucket server.

**Comment by beyang** [comment]
If we do this, we should also move authN completely out of sourcegraph-frontend and into Caddy. Both Caddy and nginx have OAuth2 and SAML plugins. We should rely on the reverse proxy for authentication. Then the frontend auth model becomes very simple (HTTP header driven). Then it will also be easy to put other services (e.g., language servers) behind the same authN model we use for frontend.

**Comment by mholt** [comment]
On that note, we are currently designing authentication modules for Caddy 2, and we'd like to unify and simplify them if possible. The oauth/saml plugins for Caddy 1 should be fine for now, but at some point (in the next few weeks) I'd love to start a discussion with your team about how to best meet your authentication/authorization needs.

**Comment by sqs** [comment]
we are doing this

**Comment by mholt** [comment]
🥹 This makes me so happy ☺️
