### ISSUE TITLE
Indexing NPM repos

### ISSUE THREAD

**Issue by jjeffwarner** [sourcegraph/sourcegraph#28683]
Code intel is working on making NPM available. We could leverage this work and index the NPM repos as well. There are issues around ranking and potential value on these repos.

**Comment by jjeffwarner** [comment]
@tsenart I believe this changes are in place so any additional repo by Code Intel will be picked up automagically? If that is the case I think we can close this.

**Comment by tsenart** [comment]
Yep, closed by #29250.
