### ISSUE TITLE
Private code message overlaps code tour

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#28696]
There is a site config option that a fair number of customers set, we also have it set on k8s.sgdev.org, which adds a message to the homepage. It overlaps oddly with the search onboarding widget:
![image.png](https://images.zenhubusercontent.com/5467e9ba7c6ccc6277a5f103/e49d2f1e-59f6-4f29-b66f-85e4b68d90d4)

**Comment by camdencheek** [comment]
Closing as fixed
