### ISSUE TITLE
Update Cloud Resources

### ISSUE THREAD

**Issue by JenRed777** [sourcegraph/sourcegraph#28690]
Using the document created by Rafal go through and appropriately update our resources.

https://docs.google.com/document/d/1qEnD-1RQ0tD_C-kKiLngKnWA1-kUStOu4xU0YGlKQrM/edit#heading=h.m2y4u5mmwaiw

**Comment by filiphaftek** [comment]
@JenRed777 first step to reduce cpu and optimise VM processors is in this PR: https://github.com/sourcegraph/infrastructure/pull/2951. 
The proposal is although to go first with this kind of VMs to pre-prod environment, which is being created already, and if the VMs prove to be good enough and gitserver/indexer can work with less cpu request (but on faster n2 cores), we could apply this change also on production. This way should be safer, as we do not risk any issues on actual production. What do you think?

**Comment by JenRed777** [comment]
Want to wait until Pre-prd is complete
