### ISSUE TITLE
Error while migrating K8 DB dumps using Postgres Backup and Restore

### ISSUE THREAD

**Issue by topebali** [sourcegraph/sourcegraph#28729]
- **Sourcegraph version:** 
- **Platform information:** 

#### Steps to reproduce:

1. Generate Postgres dumps from the old instance
2. Restore the dumps in the new instance deployed in a different cluster

#### Expected behavior:
I should be able to backup and restore the dumps as stated in the docs
#### Actual behavior:
I was trying to migrate dumps from our CSE sourcegraph k8 test [instance](https://cse-k8s.sgdev.org/) to a freshly deployed sourcegraph instance on minikube. I was able to generate the dumps using this [documentation](https://docs.sourcegraph.com/admin/install/kubernetes/operations#restore-sourcegraph-databases). However, I ran into issues while trying to restore the dumps on the new sourcegraph instance.

@daxmc99 asked me to create this issue. Please I need help on this. Is there a script I could run to perform the migration seamlessly?

If would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are not [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

**Comment by topebali** [comment]
I get this error every time I try to restore.

`psql:/tmp/sourcegraph_db.out:133: ERROR:  type "batch_changes_changeset_ui_publication_state" already exists
ALTER TYPE
psql:/tmp/sourcegraph_db.out:145: ERROR:  type "cm_email_priority" already exists
ALTER TYPE
psql:/tmp/sourcegraph_db.out:157: ERROR:  type "critical_or_site" already exists
ALTER TYPE
psql:/tmp/sourcegraph_db.out:169: ERROR:  type "feature_flag_type" already exists
ALTER TYPE
psql:/tmp/sourcegraph_db.out:184: ERROR:  type "lsif_index_state" already exists
ALTER TYPE
psql:/tmp/sourcegraph_db.out:201: ERROR:  type "lsif_upload_state" already exists
ALTER TYPE
psql:/tmp/sourcegraph_db.out:213: ERROR:  type "persistmode" already exists
ALTER TYPE
psql:/tmp/sourcegraph_db.out:235: ERROR:  function "delete_batch_change_reference_on_changesets" already exists with same argument types
ALTER FUNCTION
psql:/tmp/sourcegraph_db.out:258: ERROR:  function "delete_repo_ref_on_external_service_repos" already exists with same argument types
ALTER FUNCTION
psql:/tmp/sourcegraph_db.out:277: ERROR:  function "invalidate_session_for_userid_on_password_change" already exists with same argument types
ALTER FUNCTION
psql:/tmp/sourcegraph_db.out:293: ERROR:  function "repo_block" already exists with same argument types
ALTER FUNCTION
psql:/tmp/sourcegraph_db.out:319: ERROR:  function "soft_delete_orphan_repo_by_external_service_repos" already exists with same argument types
ALTER FUNCTION
psql:/tmp/sourcegraph_db.out:341: ERROR:  function "soft_delete_user_reference_on_external_service" already exists with same argument types
ALTER FUNCTION
psql:/tmp/sourcegraph_db.out:356: ERROR:  function "soft_deleted_repository_name" already exists with same argument types
ALTER FUNCTION
psql:/tmp/sourcegraph_db.out:371: ERROR:  function "versions_insert_row_trigger" already exists with same argument types
ALTER FUNCTION
SET
SET
psql:/tmp/sourcegraph_db.out:395: ERROR:  relation "access_tokens" already exists
ALTER TABLE
psql:/tmp/sourcegraph_db.out:409: ERROR:  relation "access_tokens_id_seq" already exists
ALTER TABLE
ALTER SEQUENCE
psql:/tmp/sourcegraph_db.out:440: ERROR:  relation "batch_changes" already exists
ALTER TABLE
psql:/tmp/sourcegraph_db.out:454: ERROR:  relation "batch_changes_id_seq" already exists
ALTER TABLE
ALTER SEQUENCE
psql:/tmp/sourcegraph_db.out:478: ERROR:  relation "batch_changes_site_credentials" already exists
ALTER TABLE
psql:/tmp/sourcegraph_db.out:492: ERROR:  relation "batch_changes_site_credentials_id_seq" already exists
ALTER TABLE
ALTER SEQUENCE
psql:/tmp/sourcegraph_db.out:523: ERROR:  relation "batch_spec_resolution_jobs" already exists
ALTER TABLE
psql:/tmp/sourcegraph_db.out:537: ERROR:  relation "batch_spec_resolution_jobs_id_seq" already exists
ALTER TABLE
ALTER SEQUENCE
psql:/tmp/sourcegraph_db.out:570: ERROR:  relation "batch_spec_workspace_execution_jobs" already exists
ALTER TABLE
psql:/tmp/sourcegraph_db.out:584: ERROR:  relation "batch_spec_workspace_execution_jobs_id_seq" already exists
ALTER TABLE
ALTER SEQUENCE
psql:/tmp/sourcegraph_db.out:617: ERROR:  relation "batch_spec_workspaces" already exists
ALTER TABLE
psql:/tmp/sourcegraph_db.out:631: ERROR:  relation "batch_spec_workspaces_id_seq" already exists
ALTER TABLE
ALTER SEQUENCE
psql:/tmp/sourcegraph_db.out:661: ERROR:  relation "batch_specs" already exists
ALTER TABLE
psql:/tmp/sourcegraph_db.out:675: ERROR:  relation "batch_specs_id_seq" already exists
ALTER TABLE
ALTER SEQUENCE
psql:/tmp/sourcegraph_db.out:706: ERROR:  relation "changeset_specs" already exists
ALTER TABLE
psql:/tmp/sourcegraph_db.out:758: ERROR:  relation "changesets" already exists
ALTER TABLE
COMMENT
psql:/tmp/sourcegraph_db.out:793: ERROR:  relation "repo" already exists
ALTER TABLE
psql:/tmp/sourcegraph_db.out:818: ERROR:  relation "branch_changeset_specs_and_changesets" already exists
ALTER TABLE
psql:/tmp/sourcegraph_db.out:838: ERROR:  relation "changeset_events" already exists
ALTER TABLE
psql:/tmp/sourcegraph_db.out:852: ERROR:  relation "changeset_events_id_seq" already exists
ALTER TABLE
ALTER SEQUENCE
psql:/tmp/sourcegraph_db.out:889: ERROR:  relation "changeset_jobs" already exists
ALTER TABLE
psql:/tmp/sourcegraph_db.out:903: ERROR:  relation "changeset_jobs_id_seq" already exists
ALTER TABLE
ALTER SEQUENCE
psql:/tmp/sourcegraph_db.out:924: ERROR:  relation "changeset_specs_id_seq" already exists
ALTER TABLE
ALTER SEQUENCE
psql:/tmp/sourcegraph_db.out:945: ERROR:  relation "changesets_id_seq" already exists
ALTER TABLE
ALTER SEQUENCE
psql:/tmp/sourcegraph_db.out:976: ERROR:  relation "cm_action_jobs" already exists
ALTER TABLE
psql:/tmp/sourcegraph_db.out:991: ERROR:  relation "cm_action_jobs_id_seq" already exists
ALTER TABLE
ALTER SEQUENCE
psql:/tmp/sourcegraph_db.out:1017: ERROR:  relation "cm_emails" already exists
ALTER TABLE
psql:/tmp/sourcegraph_db.out:1031: ERROR:  relation "cm_emails_id_seq" already exists
ALTER TABLE
ALTER SEQUENCE
psql:/tmp/sourcegraph_db.out:1057: ERROR:  relation "cm_monitors" already exists
ALTER TABLE
psql:/tmp/sourcegraph_db.out:1071: ERROR:  relation "cm_monitors_id_seq" already exists
ALTER TABLE
ALTER SEQUENCE
psql:/tmp/sourcegraph_db.out:1097: ERROR:  relation "cm_queries" already exists
ALTER TABLE
psql:/tmp/sourcegraph_db.out:1111: ERROR:  relation "cm_queries_id_seq" already exists
ALTER TABLE
ALTER SEQUENCE
psql:/tmp/sourcegraph_db.out:1132: ERROR:  relation "cm_recipients" already exists
ALTER TABLE
psql:/tmp/sourcegraph_db.out:1146: ERROR:  relation "cm_recipients_id_seq" already exists
ALTER TABLE
ALTER SEQUENCE
psql:/tmp/sourcegraph_db.out:1179: ERROR:  relation "cm_trigger_jobs" already exists
ALTER TABLE
psql:/tmp/sourcegraph_db.out:1194: ERROR:  relation "cm_trigger_jobs_id_seq" already exists
ALTER TABLE
ALTER SEQUENCE
psql:/tmp/sourcegraph_db.out:1216: ERROR:  relation "critical_and_site_config" already exists
ALTER TABLE
psql:/tmp/sourcegraph_db.out:1230: ERROR:  relation "critical_and_site_config_id_seq" already exists
ALTER TABLE
ALTER SEQUENCE
psql:/tmp/sourcegraph_db.out:1255: ERROR:  relation "discussion_comments" already exists
ALTER TABLE
psql:/tmp/sourcegraph_db.out:1269: ERROR:  relation "discussion_comments_id_seq" already exists
ALTER TABLE
ALTER SEQUENCE
psql:/tmp/sourcegraph_db.out:1290: ERROR:  relation "discussion_mail_reply_tokens" already exists
ALTER TABLE
psql:/tmp/sourcegraph_db.out:1308: ERROR:  relation "discussion_threads" already exists
ALTER TABLE
psql:/tmp/sourcegraph_db.out:1322: ERROR:  relation "discussion_threads_id_seq" already exists
ALTER TABLE
ALTER SEQUENCE
psql:/tmp/sourcegraph_db.out:1352: ERROR:  relation "discussion_threads_target_repo" already exists
ALTER TABLE
psql:/tmp/sourcegraph_db.out:1366: ERROR:  relation "discussion_threads_target_repo_id_seq" already exists
ALTER TABLE
ALTER SEQUENCE
psql:/tmp/sourcegraph_db.out:1399: ERROR:  relation "event_logs" already exists
ALTER TABLE
psql:/tmp/sourcegraph_db.out:1413: ERROR:  relation "event_logs_id_seq" already exists
ALTER TABLE
ALTER SEQUENCE
psql:/tmp/sourcegraph_db.out:1435: ERROR:  relation "external_service_repos" already exists
ALTER TABLE
psql:/tmp/sourcegraph_db.out:1449: ERROR:  relation "external_service_sync_jobs_id_seq" already exists
ALTER TABLE
psql:/tmp/sourcegraph_db.out:1472: ERROR:  relation "external_service_sync_jobs" already exists
ALTER TABLE
psql:/tmp/sourcegraph_db.out:1498: ERROR:  relation "external_services" already exists
ALTER TABLE
psql:/tmp/sourcegraph_db.out:1520: ERROR:  relation "external_service_sync_jobs_with_next_sync_at" already exists
ALTER TABLE
psql:/tmp/sourcegraph_db.out:1534: ERROR:  relation "external_services_id_seq" already exists
ALTER TABLE
ALTER SEQUENCE
psql:/tmp/sourcegraph_db.out:1559: ERROR:  relation "feature_flag_overrides" already exists
ALTER TABLE
psql:/tmp/sourcegraph_db.out:1589: ERROR:  relation "feature_flags" already exists`

**Comment by JenRed777** [comment]
@daxmc99 is there anymore context you can give to this ticket?

**Comment by virginiaulrich** [comment]
@topebali Guessing based on timestamps this is resolved; if not have support me talk to delivery me 🙃

**Comment by daxmc99** [comment]
We also have updated our handbook to include steps for how to do this
