### ISSUE TITLE
Verify renovate is processing all images correctly for cloud

### ISSUE THREAD

**Issue by danieldides** [sourcegraph/sourcegraph#28742]
Renovate configuration is specific about which tags will be processed correctly and deployed. Quickly audit all base images in `deploy-sourcegraph-dot-com` and verify they're correct for renovate.

Wanted to get this one in and done before the go-live on Thursday to make sure we're prepared to iterate quickly on Cloud.

**Comment by danieldides** [comment]
Quick scan over all the files in that repo looks like nearly all correctly include `index.docker.io` and will be managed by `renovate`:

https://sourcegraph.com/search?q=context:%40sourcegraph+repo:github.com/sourcegraph/deploy-sourcegraph-dot-com+docker.io&patternType=literal

The only exception I've found is in the `search-blitz` manifests. It looks like we're using [`prom/prometheus` ](https://github.com/sourcegraph/deploy-sourcegraph-dot-com/blob/0d5559501c5530638eea26fb6584045df38cf278/configure/search-blitz/search-blitz.StatefulSet.yaml#L60) and [`grafana/grafana`](https://github.com/sourcegraph/deploy-sourcegraph-dot-com/blob/0d5559501c5530638eea26fb6584045df38cf278/configure/search-blitz/search-blitz.StatefulSet.yaml#L80) container images rather than using the images being built at `"index.docker.io/sourcegraph/grafana"` and `"index.docker.io/sourcegraph/prometheus"`. @daxmc99 is this intentional? Should these be swapped to the sourcegraph images?

Also cc @keegancsmith: the [`search-blitz`](https://github.com/sourcegraph/deploy-sourcegraph-dot-com/blob/0d5559501c5530638eea26fb6584045df38cf278/configure/search-blitz/search-blitz.StatefulSet.yaml#L39) image right now is using `us.gcr.io/sourcegraph-dev` which to my knowledge will _not_ be automatically updated by renovate in this repository. Should this be added to renovate or is it intentional that this will be manually updated in cloud for now?

**Comment by keegancsmith** [comment]
yes this is a sourcegraph.com only image which is very rarely updated and is done manually by our team.

**Comment by daxmc99** [comment]
@danieldides `searchblitz` is primarily operated by @sourcegraph/search-core (I believe) 

I think this enough to close out this issue. One service I noticed in `base` was `search-badger`. This looks like an older service that we can move out of `base` such that `base` only contains our core services.

**Comment by danieldides** [comment]
@daxmc99 Thanks. I can submit a PR to move `search-badger`.
