### ISSUE TITLE
option to allow anonymous API requests regardless of auth provider

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#2875]
Today, it is only possible to allow anonymous API requests on a Sourcegraph instance (i.e. without specifying a token) when using `"auth.public": true`, but this option only works with the `builtin` auth provider and not the `http-header` or others.

In some deployments it is desirable to use `http-header` or similar so that user accounts are not separately stored in Sourcegraph, but still allow anonymous API requests for e.g. ease of writing internal tooling without making use of access tokens.

Proposal: add an `"auth.public-api": true` option which works regardless of auth provider type in use.

I am optimistically tagging for 3.3, but this issue could be deferred to 3.4 if needed since this is a security related issue and all such changes have to be done right.

**Comment by slimsag** [comment]
After some further discussion with @beyang I realize this approach is actually not logically sound. It would only be logically sound if the auth provider was responsible merely for providing (mostly optional) identity, but since in most cases it is responsible for actually restricting access to the Sourcegraph instance this approach would be incorrect in most cases, too. One way to effectively achieve the same thing would be creating a Sourcegraph "api" user and creating a PAT on that user which is shared everywhere (and that is obviously not secure if the PAT is leaked and the instance is accessible by a potential attacker).

**Comment by slimsag** [comment]
When a [`http-header` auth provider](https://docs.sourcegraph.com/admin/auth#http-authentication-proxies) is in use, it seems the correct way to enforce this would be to make that auth provider pass through a `usernameHeader` (e.g. `X-Forwarded-User`) when there is no authenticated user, e.g. `X-Forwarded-User: apiuser`.

If your auth proxy does not support this easily, another option is to place Sourcegraph behind e.g. Apache and then [set the header when it does not exist](https://serverfault.com/questions/520477/set-header-in-apache-if-it-doesnt-already-exist).

Closing for now since there is no direct action to take.

**Comment by beyang** [comment]
@slimsag we could add a field to the `http-header` config that specifies the "unauthenticated user username". If the HTTP header sets that, then Sourcegraph handles the request as unauthenticated. I assume (1) $CUSTOMER wants all auth logic to be handled by their auth proxy, and (2) this includes a way to provision access tokens for API clients to authenticate to their auth proxy?
