### ISSUE TITLE
lang filter breaking searches?

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#28769]
I can’t get any (seemingly) simple literal searches to work with a lang filter. For example: https://sourcegraph.com/search?q=context:global+lang:JavaScript+test&patternType=literal won’t work with python either. No errors in my network tab.

Apparently regexp search is affected as well.

Flagging both search teams as I'm not sure who owns.

**Comment by eseliger** [comment]
This was a mismatch between zoekt and frontend versions. I think we can close it.

**Comment by coury-clark** [comment]
Resolved in incident 58
