### ISSUE TITLE
insights: Show year on x-axis labels 

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#28766]
We should either show year: 

1. When multiple years are shown on the graph 
2. All the time

1 is very much preferred but if it's more complicated than it's worth right now, 2 is okay. 

This solves a problem of confusing-at-a-glance graphs (these are Sourcegraph or test insights, not customer insights, so okay to post here publicly): 
![image](https://user-images.githubusercontent.com/11967660/145306022-da44fdac-5695-47c8-9d8d-a59c2b4afdd8.png)
![image](https://user-images.githubusercontent.com/11967660/145306045-8fa5d70f-c66d-4150-83ad-4b0fc5a100db.png)

**Comment by Joelkw** [comment]
This came up again internally – https://github.com/sourcegraph/sourcegraph/issues/33533 . This is effectively in our "design backlog" cc @AlicjaSuska (we don't need designs urgently but it may need your input/signoff before we can put this in on deck – or can we just add the four digit year to the chart?)

**Comment by Joelkw** [comment]
@vovakulikov do you think this actually needs design? I'd like to move this out of needs-design and just keep in our "ready when we have a moment" on deck status.

**Comment by vovakulikov** [comment]
@Joelkw If @AlicjaSuska doesn't have anything to add to the visual aspects of the x-axis grid for the year's translation I'm good to move this out of needs-design.

**Comment by Joelkw** [comment]
Sweet thanks @vovakulikov ! Feels like something we can experiment with "live" if we have to, agree.

**Comment by coury-clark** [comment]
p1

**Comment by AlicjaSuska** [comment]
@vovakulikov maybe we can use the same mechanism we used for aggregation and rotate the labels to show the year?
