### ISSUE TITLE
Docker compose instructions for AWS seem incomplete

### ISSUE THREAD

**Issue by zestyping** [sourcegraph/sourcegraph#28780]
#### Describe the issue
I'm looking at this page for instructions on setting up Sourcegraph on AWS:
https://docs.sourcegraph.com/admin/install/docker-compose/aws

There's a big code block with a bash script in it.  But what am I supposed to do with this script?  Run it?  Install it as /etc/rc.local?  Save it somewhere?  It doesn't seem like it can be executed because I haven't created any storage yet.  It looks like something got lost or rearranged at some point.

#### Where is the issue located?
It's just below the "Warning" block in the page: https://docs.sourcegraph.com/admin/install/docker-compose/aws

#### Suggested resolution
Explain what to do with the bash script.

**Comment by northyg** [comment]
Hello @zestyping - Thank you for bringing this to our attention! We also agree the docs are confusing regarding what to do with the script. @DaedalusG  [Made an update to the document ](https://github.com/sourcegraph/sourcegraph/pull/29350) to clarify how to use the script. We hope that helps! :)

**Comment by zestyping** [comment]
@northyg Cool, thank you so much for the clarification!  That solves the problem for me.

A minor thing I noticed at https://docs.sourcegraph.com/admin/install/docker-compose/aws — it looks like there is a formatting error with the asterisks here, which I assume were meant to be bullet points:
![image](https://user-images.githubusercontent.com/236086/147714681-839fd82c-55a2-4541-9b72-50a79639c2ca.png)

**Comment by northyg** [comment]
@zestyping Whoops! Fixed :) Btw, being that we're open source we welcome contributions too (even if its little things :D )
Cheers!

**Comment by zestyping** [comment]
Noted! :) Thanks!
