### ISSUE TITLE
Support glob/regex in repo config in search context

### ISSUE THREAD

**Issue by sluongng** [sourcegraph/sourcegraph#28782]
#### Question description

Support glob/regex in search context setting?

#### Is your question related to a problem? If so, please describe or link to another issue.

I am trying to convert my `search.repositoryGroups` settings into the new search context.
However it seems like in repositoryGroups configs, I was able to use regex for matching multiple repositories in 1 config
but with search context I have to explicitly list out repos 1-by-1.

There are 2 problems with this approach:

1. I have to generate the new context settings by querying sourcegraph/github/gitlab api to list all repos that matched the old regex, then hardcode them into my search context setting

2. I will have to update my search context setting everytime a new repo was created in a group that I am interested in

Could you guys please consider supporting glob/regex for repo config in search context?

#### Additional context

Here are some examples config i used previously

```
"search.repositoryGroups": {
    "bazel": [
      // Matches multiple repos in groups
      {
        "regex": "github\\.com/bazelbuild"
      },
      {
        "regex": "github\\.com/bazelruby"
      },
   ]}
```

Relevant source code that does not allow glob match.

https://sourcegraph.com/github.com/sourcegraph/sourcegraph@21db69ae154b2644c8ff07c5837beb61bf66fb58/-/blob/internal/types/types.go?L1234-1241

If would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are not [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

**Comment by benvenker** [comment]
We support this now with query-based search contexts in 3.36 and beyond. You can define your contexts using regex patterns, including down to subdirectories: https://sourcegraph.com/contexts/new
