### ISSUE TITLE
search: measure performance of querying with nesting enabled/disabled

### ISSUE THREAD

**Issue by ijt** [sourcegraph/sourcegraph#2879]
#### Feature request description

Add an endpoint that gets the top 100 recent queries from the `searches` table, and outputs a CSV table containing timings with and without nesting enabled.

#### Is your feature request related to a problem? If so, please describe.

We currently don't have a clear picture of search latency on sourcegraph.com and customer installations. It seems to be more anecdotal, based on manually running particular queries.

#### Describe alternatives you've considered.

One other possibility is to look at latency percentiles, but that approach doesn't show the worst case and it also doesn't tell which queries are slow.

**Comment by nicksnyder** [comment]
@ijt Please set appropriate values for assignee and milestone :)

**Comment by ijt** [comment]
Done.

**Comment by ijt** [comment]
This is part of #1005.

**Comment by ijt** [comment]
Closing this for now. We can revisit this when we restart the work on nested search.
