### ISSUE TITLE
Feature request: function dependency graph

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#2883]
For answering things like "What are the possible side effects of this function [i.e., does it have `os` as a transitive dependency?]", "What other libraries use this function?".

This could be a list UI showing the transitive dependencies of a function's code, and the callers of a function grouped by calling library.

(Split off from #2278, related to #2881 and #2882)

**Comment by sqs** [comment]
From user feedback (https://sourcegraph.slack.com/archives/C0W2E592M/p1553791017004000):

> Thank you for reaching out.  I didn't actually get what we were looking for from SourceGraph.  We need the graph - the function dependency trees and module dependencies - so I was looking for some sort of graph query API but as far as I can see SourceGraph is just a hyperlinked view of the code.  Is there a straightforward API that can query the dependency tree?  If so can you send me an example of how to use it, e.g. given a Haskell function, list all transitive dependencies?
> Just for clarity; I do see the search functionality but that seems to offer just locating code, which does not suffice.  It does not give the dependencies of that code.

**Comment by macraig** [comment]
This feature request is now tracked in [Productboard](https://sourcegraph.productboard.com/feature-board/1825051-code-intel/features/8233720/detail)
