### ISSUE TITLE
ci: detect job duration large deviations or at least job duration going over x minutes. 

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#28834]
See [INC-59](https://docs.google.com/document/d/1HXKZa9L3MVswK6pDpRN5TdCgUcEcQca9Re4vCwlb6Ek/edit#) 

> We have no detection mechanism for a job that hangs and they can stay up for 2h before reaching a hard timeout. When doing so, they are clogging the queue and will slow down the whole CI system.

Having an alert about this would notice us of such cases, reducing the hard timeout for jobs completion would mitigate them if we're unable to respond.

**Comment by bobheadxi** [comment]
This would be closed by https://github.com/sourcegraph/sourcegraph/pull/28759 , which will treat hanging jobs as failures
