### ISSUE TITLE
Scroll position is not preserved when going back to search results

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#28845]
- **Sourcegraph version:** live on Cloud today.
- **Platform information:** Web, Firefox.

Reported by @mrnugget in https://sourcegraph.slack.com/archives/C0W2E592M/p1639134784325400?thread_ts=1639059715.308200&cid=C0W2E592M

#### Steps to reproduce:

1. Open search page https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph+countervec&patternType=literal
2. Scroll down
3. Click on result
4. Go back to search results
5. The scroll bar is at the top of the page

#### Expected behavior:
I expected the scroll position from step 2 to be preserved

#### Actual behavior:

![CleanShot 2021-12-10 at 12 28 36](https://user-images.githubusercontent.com/1408093/145567563-2a229518-bf73-4b71-a8cd-b66c849f9207.gif)

**Comment by macraig** [comment]
@taylorsperry this feels like quite the pain point, any thoughts on prioritization?

**Comment by valerybugakov** [comment]
Closed by https://github.com/sourcegraph/sourcegraph/pull/29178.
