### ISSUE TITLE
pre-aggregated stat from zoekt.List for usagestats

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#28849]

**Comment by jjeffwarner** [comment]
@keegancsmith @tsenart Any update on this?

**Comment by keegancsmith** [comment]
I think @tsenart shipped this? Not sure if we did the work on the sourcegraph/sourcegraph side.

**Comment by tsenart** [comment]
Yep, this was done in #28977, so this issue overlapped with #28799.
