### ISSUE TITLE
insights: improve determinism of backfiller process

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#28858]
When creating a code insight that records values, there are 2 major components involved.

1. The **historical enqueuerer** will iterate over a selection of repositories (currently global), perform some logic to decide if each datum needs a query, and queue up one record per query.
2. The **indexed recorder** will perform global indexed searches after +1 interval of time by queuing up a single row per global indexed search. This fails for search types that do not support global searching (commits over X repos)

The approach in 1. is fragile for a variety of reasons:
1. The cardinality of the repositories means it is difficult to have visibility into what is happening at each stage, and for each repository. This makes debugging / reporting errors difficult.
2. The approach of queueing every time frame at the same time without any state means it is difficult to look back and understand which dates have been backfilled and which didn't. One could imagine how we would like to add new points to a backfill, but are currently unable in this system.
3. The backfiller iterates all series at the same time. Any new series that is created won't begin backfilling for up to `N` minutes, depending on configuration (10 currently). Ideally we could parallelize this but still preserve shared caching over repositories.
4. The backfiller process is limited to a single instance of `worker` and doesn't support concurrency.
5. The backfiller process has a very naive implementation of `complete`, which is achieved by iterating over the entire repository set once successfully without error. This is acceptable on small enough instances, but scales very poorly with cardinality of repositories. Additionally, any transient errors result in either an all or nothing approach. Ideally we would have a better way of tabulating state. See: https://github.com/sourcegraph/sourcegraph/issues/23844

**Comment by coury-clark** [comment]
Here is an idea to stabilize the backfill (and current, actually) recordings. We maintain a set of `(seriesID, recording_time, repo_offset)` tuples. Each tuple will track what is the maximum `repo_id` that has been processed for that `series, time` pair.

The process of creating a new series would be to add the dates that need to be processed to this set with a default of 0 for each repository offset:
| series_id  | recording_time | repository_offset |
| ------------- | ------------- | ------------- | 
| series1  | 2021-12-01  | 0 | 1
| series1  | 2021-11-01  | 0 | 1
| series1  | 2021-10-01  | 0 | 1
| series1  | 2021-09-01  | 0 | 1

The advantage of this approach is that we can keep the same basic architecture we have now. A single background process can select any `series, time` pairs that need processing. It can iterate through the global set of repositories in `repo_id` order. Each series will have a set of `time` for which `repository_offset` < `current_repository_id`, for which we can compress and enqueue any queries that are required. Periodically (every `N=500` repos), we can update each of these tuples with a new `repository_offset` representing the maximum value that was analyzed to preserve at-least-once semantics

In the background process, to simplify any scenarios where `time A` and `time B` fall out of sync (different `repository_offset`) we can group by `series_id` and consider the `repository_offset` the minimum `(repository_offset, time)` in the set of times. This will have the side effect that any new tuples will cause each time to be reanalyzed. This is an acceptable trade-off in the short term, long term we can consider other strategies:
1. Grouping the `(series_id, time, offset)` tuples explicitly with a `group` field


As a neat side effect, this would give us a relatively simple ([but not necessarily efficient](https://wiki.postgresql.org/wiki/Slow_Counting)) way to calculate the percentage complete:
``` 
% = count(repos < repository_offset) / count(repos >= repository_offset)
```

Error handling becomes a challenge, we either have to skip failed repositories or somehow keep track and retry them separately. The current behavior is to skip them, which is an acceptable short-term trade-off. Long term, we would probably want to have a more sophisticated way of marking and retrying failed repositories.

As an additional note, this does not solve the problem of scoping down the set of repositories we iterate over. This would still iterate over every repository on Sourcegraph.

**Comment by chwarwick** [comment]
Spiking on related work in https://github.com/sourcegraph/sourcegraph/issues/42013. New issues will be created as output of that spike.
