### ISSUE TITLE
Highlight Smarty Files

### ISSUE THREAD

**Issue by shyim** [sourcegraph/sourcegraph#2885]
#### Feature request description

Currently smarty files are not highlighed (.tpl)
https://sourcegraph.com/github.com/shopware/shopware/-/blob/themes/Frontend/Bare/frontend/listing/index.tpl

**Comment by slimsag** [comment]
Fixed by #10374 and will be in Sourcegraph 3.16.

![image](https://user-images.githubusercontent.com/3173176/80898412-f412d480-8cb7-11ea-98f7-7f2610a54cd9.png)
