### ISSUE TITLE
[Accessibility] Keyboard shortcut does not toggle between light to dark mode on Mac

### ISSUE THREAD

**Issue by northyg** [sourcegraph/sourcegraph#28868]
- **Sourcegraph version:** N/A
- **Platform information:**  OS: Mac

According to our keyboard shortcut menu, toggling the color scheme should work with Alt + T. This works on Windows machines, but not Macs.

![image](https://user-images.githubusercontent.com/27694443/145623670-4f57466b-76e2-49e9-a16b-ab6b21dc976e.png)

#### Steps to reproduce:

1. On a Mac machine, go to www.sourcegraph.com or your own Sourcegraph instance
2. Depending on your keyboard, try pressing Alt or Option + T to Toggle from Light to Dark mode
3. The theme does not change

#### Expected behavior:

Pressing Option + T or Alt + T should toggle from Light to Dark mode or vice versa

#### Actual behavior:

Nothing happens - theme does not change.

If would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are not [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

**Comment by umpox** [comment]
Related audit: https://github.com/sourcegraph/sourcegraph/issues/34415

**Comment by gitstart-sourcegraph** [comment]
@umpox `Command` `Shift` `T` on MacOS is already used in Chrome for restoring last closed tabs.

**Comment by gitstart-sourcegraph** [comment]
@umpox ... and on MacOS `Alt` + `t` will return key code `†` that's the reason, so we just need to replace `t` with `†` to make it works.

**Comment by umpox** [comment]
Sounds good! @gitstart-sourcegraph
