### ISSUE TITLE
Not redirecting to GitLab for OAuth  

### ISSUE THREAD

**Issue by mrvaghani** [sourcegraph/sourcegraph#28870]
- **Sourcegraph version:** 3.33.0
- **Platform information:** Docker version 19.03.15, build 99e3ed8919

#### Steps to reproduce:

1. [Create GitLab OAuth application](https://docs.gitlab.com/ee/integration/oauth_provider.html)
2. [Configure Sourcegraph as per documentation](https://docs.sourcegraph.com/admin/auth#gitlab)

```jsonc
	"auth.providers": [
	{
		// See https://docs.sourcegraph.com/admin/auth#gitlab for instructions
		"type": "gitlab",
		"displayName": "GitLab",
		"url": "https://gitlab.mydomain.com/",
		"clientID": "54...9f",
		"clientSecret": "63...2e"
	}
	,
	{
		"type": "builtin",
		"allowSignup": false
	}
	]
```

#### Expected behavior:
When I visit `http://sourcegraph.mydomain.com:7080`, it should redirect me to GitLab instance where I can authenticate against GitLab.

#### Actual behavior:
When I visit `http://sourcegraph.mydomain.com:7080`, it just sits on the main login page with the builtin login prompt.

#### Additional Information:
I did notice that whenever I visit `http://sourcegraph.mydomain.com:7080/sign-in`, the following URLs return `401`

`http://sourcegraph.mydomain.com:7080/.api/graphql?FetchFeatureFlags`
`http://sourcegraph.mydomain.com:7080/.api/graphql?ViewerSettings`
`http://sourcegraph.mydomain.com:7080/.api/graphql?LogEvent`

EDIT: Updated domain names to be consistent

**Comment by mrvaghani** [comment]
It seems like this might be related to issue #9590

**Comment by mrvaghani** [comment]
Even after disabling adblock extension and setting up SSL via reverse proxy, I am still not able to get native GitLab integration. Does anyone have any other suggestions I might be able to test?

**Comment by mrnugget** [comment]
@mrvaghani I'm going to close this, since we worked a lot on the auth providers in the last 2 years. If this is still a problem, please re-open.
