### ISSUE TITLE
insights: global insights default time interval

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#28875]
Once the webapp allows editing / creating global insights ("over all repos") with a custom time interval, we should default these insights to an appropriate value. Repo scoped insights are defaulted to 2-week intervals, I propose we keep the current standard for global insights and default to 1-month intervals.

**Comment by coury-clark** [comment]
cc @Joelkw

**Comment by Joelkw** [comment]
Note from @vovakulikov : the default time is 1 month for all insights now. 

Related to #28874

**Comment by Joelkw** [comment]
Should be closed
