### ISSUE TITLE
Remove css transitions from hover/focus/active states

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#28901]
**Problem** 

We've received some feedback that Sourcegraph doesn't always feel "snappy."

There's a few ways to unpack this that the team is already addressing. However, there's a quick win we can follow through on: today, we use a mix of css transitions for hover/focus/active states on different UI elements across the app. These transitions add a visual "delay" to interacting with some elements, but not others, which makes the app feel less "snappy" because it literally does take longer to "respond" to user interaction.

As well, we use these transitions inconsistently throughout the app, where one element might have a transition on hover, and an otherwise-identical element next to it may not. Here's a quick example of this, which does a good job of visualizing the perceived "snappiness" with and without the transition.

https://user-images.githubusercontent.com/6304497/145795235-b832a8ed-39ba-429c-9a43-e32f5817393a.mp4

**Proposal**

I propose we remove all css transitions for hover/focus/active states across the product. This will immediately solve this and make the app feel more responsive to user actions. 

(If, in the future, we feel there's value in specific transitions for these states, we can then design those transitions intentionally as part of Wildcard and implement them consistently across the app.)

**Comment by AlicjaSuska** [comment]
@umpox Following up on the last week's conversation about this issue: I've analyzed this issue and had a discussion with @quinnkeast to make sure we're all on the same page. Let's move forward with removing the transitions and see how the app feels.

**Comment by umpox** [comment]
@AlicjaSuska @quinnkeast Please have a play around with this branch: https://github.com/sourcegraph/sourcegraph/pull/30244

I've removed all of the core Bootstrap transitions, which were affecting a lot of these components.

This might solve this particular issue. We might want to also follow up and evaluate our usage of the [`transition`](https://sourcegraph.com/search?q=context:global+repo:github.com/sourcegraph/sourcegraph+transition:&patternType=literal) and [`animation`](https://sourcegraph.com/search?q=context:global+repo:github.com/sourcegraph/sourcegraph+animation:&patternType=literal) properties. There might be more areas that we should address here.

**Comment by umpox** [comment]
@gitstart-sourcegraph Please can you pick up investigating this issue?

I have made a PR here that achieves what we want: https://github.com/sourcegraph/sourcegraph/pull/30244

The remaining issue I see is this:

https://user-images.githubusercontent.com/9516420/155292666-a221373e-6fdb-4ad9-8e31-21285fc563cb.mp4

This is on the search results page, it seems that the `Reactstrap` `Collapse` component flickers when transitions are disabled. Can you look into this issue and fix if possible?
