### ISSUE TITLE
git: Apply sub-repo filtering on git.ListFiles

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#28916]
Used [here](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+git.ListFiles&patternType=literal)

It's only used from code-intel related code which appears to be called from [frontend and workers](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+ListFiles%28&patternType=literal). We've already initialised our checker in frontend and the best place to initialise for workers is probably [here](https://github.com/sourcegraph/sourcegraph/blob/6b2a82ff689adf072a194e5101b167ce1ea3bcb7/cmd/worker/workerdb/db.go#L17)

**Comment by mollylogue** [comment]
https://github.com/sourcegraph/sourcegraph/pull/29365
