### ISSUE TITLE
git: Apply sub-repo filtering on git.BlameFile

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#28918]
BlameFile is only called from the frontend so we should be safe to add sub-repo filtering [here](https://github.com/sourcegraph/sourcegraph/blob/78aa518cacc037f81aade50299e6f9ccdaffa522/internal/vcs/git/blame.go#L50)

We should be able to use [this PR](https://github.com/sourcegraph/sourcegraph/pull/28859) as a template and we only need to return a `nil` list of hunks if the current user is not allowed to read the file.

**Comment by ryanslade** [comment]
@mollylogue This could be a good first sub-repo task to pick up so I'm going to assign it to you.

Please let me know if you have any questions.

**Comment by mollylogue** [comment]
> @mollylogue This could be a good first sub-repo task to pick up so I'm going to assign it to you.
> 
> Please let me know if you have any questions.

Yay! I'll take a look today.

**Comment by mollylogue** [comment]
Questions. 
1) Do we care about the potential renaming of the file? If you look at the test in https://github.com/sourcegraph/sourcegraph/blob/78aa518cacc037f81aade50299e6f9ccdaffa522/internal/vcs/git/blame_test.go we see that the file "f" was renamed to "f2" and that's the filename being passed into `BlameFile`. If we do filtering at the top, and the user has read access to "f" but not "f2", they wouldn't end up getting anything back. But maybe that's what we want? It's only slightly more complex to do it at the end of the function (once we have all the potential filenames) so I'm happy to do it that way if it's preferable. 
2) When it comes to initializing/passing through the checker, is it preferable to have it initialized at the top level and have it set as a field on a top-level struct so we have access to it down the stack? Or are we just opting for setting the default at the top level?

**Comment by ryanslade** [comment]
> Questions.
> 
> 1. Do we care about the potential renaming of the file? If you look at the test in https://github.com/sourcegraph/sourcegraph/blob/78aa518cacc037f81aade50299e6f9ccdaffa522/internal/vcs/git/blame_test.go we see that the file "f" was renamed to "f2" and that's the filename being passed into `BlameFile`. If we do filtering at the top, and the user has read access to "f" but not "f2", they wouldn't end up getting anything back. But maybe that's what we want? It's only slightly more complex to do it at the end of the function (once we have all the potential filenames) so I'm happy to do it that way if it's preferable.

Good question. I *think* what we want is to check based on current permissions, so in this case for `f2`. Our permissions code is not aware of changes to permissions over time, only what the current permissions are. 

> 2. When it comes to initializing/passing through the checker, is it preferable to have it initialized at the top level and have it set as a field on a top-level struct so we have access to it down the stack? Or are we just opting for setting the default at the top level?

At the moment the plan is to have the `checker` be a parameter you pass into the exported function, in this case `git.BlameFile`. We then pass that down to the helper function. Internally the `git` package will only know about the checker that's it's given and at the call site it'll currently come from `authz.DefaultSubRepoPermsChecker`. 

It's a bit of a middle-ground to make our lives easier now and we can later refactor to remove the global default checker and  thread it all the way from main. We need a single global instance per service so that we can share the cache.

**Comment by mollylogue** [comment]
@ryanslade So what you're describing leads me to believe that you're in favor of the option where we do the filtering at the end of the function. If we filter at the beginning and the user has access to "f2", they will see the hunks containing "f" as well . However, if we filter at the end of the function, we can filter out those versions of the file with a different name (that the user may not have access to), and only return results with filename "f2". does that make sense?

**Comment by mollylogue** [comment]
Or are you saying that if the user has access to "f2", then they should be able to see the history of it even if it had a different name (which would be filtered out by sub-repo perms)?

**Comment by ryanslade** [comment]
> Or are you saying that if the user has access to "f2", then they should be able to see the history of it even if it had a different name (which would be filtered out by sub-repo perms)?

This ☝️ 😄

**Comment by mollylogue** [comment]
> > Or are you saying that if the user has access to "f2", then they should be able to see the history of it even if it had a different name (which would be filtered out by sub-repo perms)?
> 
> This ☝️ 😄

Awesome. Thanks for clarifying 😅

**Comment by mollylogue** [comment]
https://github.com/sourcegraph/sourcegraph/pull/29145
