### ISSUE TITLE
git: Apply sub-repo filtering on git.DiffPath

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#28912]

**Comment by mollylogue** [comment]
Just taking an initial look at this and where this function is called. It seems that following this up to the top level leads me to https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/main.go. Should we initialize the default client there? Or, should it happen when `authz` is initialized: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/main.go?L52 in this `authz.Init` function?

**Comment by ryanslade** [comment]
> Just taking an initial look at this and where this function is called. It seems that following this up to the top level leads me to https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/main.go. Should we initialize the default client there? Or, should it happen when `authz` is initialized: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/main.go?L52 in this `authz.Init` function?

We already initialise it in the frontend here: 
https://github.com/sourcegraph/sourcegraph/blob/6b2a82ff689adf072a194e5101b167ce1ea3bcb7/cmd/frontend/internal/cli/serve_cmd.go#L233

That's a shared "main" function that's called by frontend on startup.

**Comment by mollylogue** [comment]
https://github.com/sourcegraph/sourcegraph/pull/29362
