### ISSUE TITLE
Make it possible to search across all transitive dependencies of a repository

### ISSUE THREAD

**Issue by macraig** [sourcegraph/sourcegraph#28932]
#### Feature request description

As a user I might want to run a search across my repos and their referenced dependencies. In this case it would be useful to have a _repo-dependencies_ keyword filter to define the options while searching across a repo's dependency graph.

For example:
_repo-dependencies: transitive_ to search across the repo's entire dependency graph  
_repo-dependencies:direct_ to only search among the repo and it's direct dependencies (just one level of depth in the dependency graph)
_repo-dependencies: exclude_ optionally exclude any repo dependencies from the search 

Another idea would be to add an "N levels of depth" option, to search across the first N levels of the dependency graph.  

#### Additional context
Documenting @olafurpg's feature request idea. Please feel free to add further detail to the issue.

**Comment by olafurpg** [comment]
Thank you for opening this @macraig 

Here's a screenshot of the text search in IntelliJ to demonstrate how you can choose to search in "All places" (which includes transitive dependencies of your codebase) or "Project files" (which is only for your current repository/directory). 

![CleanShot 2021-12-14 at 10 18 48@2x](https://user-images.githubusercontent.com/1408093/145969628-03a87819-779c-449c-aae4-cd998bcbdf2e.png)

A use-case where this would be helpful: searching for an error message that you see in production. Currently, Sourcegraph makes it easy to search for an error message globally or in the current repo but there's no way to easily search for an error message in all repos that the current repo transitively depends on.

**Comment by benvenker** [comment]
This is a great idea, thanks for raising @olafurpg and for creating the issue @macraig.

**Comment by olafurpg** [comment]
@benvenker Sidenote: I think this feature could also be used to improve result ranking. Repos with a large number of inverse dependencies are typically the repos you want to surface at the top of search results.

**Comment by benvenker** [comment]
Love that idea.

**Comment by tsenart** [comment]
From a syntax perspective, `repo:deps(sourcegraph/sourcegraph, 2)` looks better to me.

**Comment by tsenart** [comment]
PS: 2, being the depth. First argument would be a regex matching on repo name. For negation, it would just be adding a `-` in front of the `repo` filter, like we already support today.

**Comment by lguychard** [comment]
> For negation, it would just be adding a - in front of the repo filter, like we already support today.

We do support negating plain `repo:` filters, but not [negation for predicates](https://github.com/sourcegraph/sourcegraph/issues/24325).

**Comment by efritz** [comment]
Implementation proposal:

1. Build off of the [ranked dependency candidate CTE query](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@053767ebe72da8c98d9d54b0cbed2332dd9afaae/-/blob/enterprise/internal/codeintel/stores/dbstore/uploads.go?L483:5) already defined to show (direct) dependencies or dependents of an _upload_. This can be pretty easily used in a recursive CTE to get all _transitive_ dependencies/dependents, and can be used to map uploads to and from repositories (with commits of interest).
2. Implement a way to parse common lock files in-repos that will return a list of dependency names and versions.
3. Mirror the lsif_packages/lsif_references table for lockfiles that operate directly on repository/commits and not on an upload.
4. Write a background routine to parse lock files from the head of repos.
5. Enable querying repos from both sources of data (falling back or mixing results as intuitive).

**Comment by keegancsmith** [comment]
@tsenart and @olafurpg are hacking on this. I believe they have a prototype and they wrote up [RFC 593](https://docs.google.com/document/d/1SkM8CG0IksvPEKRBRVLKipiRJTopx6Vq_hSWRJ9NyKs): Unlocking use cases based on the dependency graph of repositories.

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket, please let us know how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
