### ISSUE TITLE
Code views unreliably detected on large PRs

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#2893]
- Visit a PR with many files changed, for instance https://github.com/sourcegraph/sourcegraph/pull/2838/files
- Witness not all code views have "view file" button initially

![image](https://user-images.githubusercontent.com/1741180/54764433-12bf2480-4bf8-11e9-903c-911f4bc3b5cc.png)

- If you scroll down too quickly, code views will not be detected.
- If you scroll up/down some more, eventually the code views will all be detected.

I believe this is due to [`emitWhenIntersecting()`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/browser/src/libs/code_intelligence/code_views.ts#L11-49)

**Comment by felixfbecker** [comment]
Possibly fixed by #2909

**Comment by felixfbecker** [comment]
Seems to be fixed.
