### ISSUE TITLE
Auth provider secrets not redacted in UI

### ISSUE THREAD

**Issue by emchap** [sourcegraph/sourcegraph#28940]
- **Sourcegraph version:** 3.34.2
- **Platform information:** Demo

#### Steps to reproduce:

1. Go to Site configuration
2. Look for an OAuth or OpenId auth provider
3. Secret is not redacted

#### Expected behavior:

We redact it. 

#### Actual behavior:

We do not.

**Comment by mollylogue** [comment]
I've merged a PR to redact at least some of the secrets. If there are any that I missed, it's pretty trivial to get those redacted now that this code change is in place.
