### ISSUE TITLE
On notebook files rendered in sourcegraph, always show run button

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#28960]
When interacting with a notebook, it's not always obvious that the next block needs to (or can be) run. After you click "run" on a block, all the other run buttons disappear until you click the page somewhere again.
https://cln.sh/7sJP6S

**Comment by benvenker** [comment]
This may be moot now that we have the "run all" button...

**Comment by novoselrok** [comment]
Yep, I'll proactively close this now that we have the run all button. For further context, if we always showed all right-side block menus, they would start to overlap (that's why we only show one at a time).

**Comment by benvenker** [comment]
Thanks!
