### ISSUE TITLE
Config validator that covers all site, critical, and external services config

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#2897]
When all configuration came from a single place, our validation logic could validate its entirety. Now that external services config is separate from site/critical config, we have 2 places for validation logic: [one for site/critical config](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@72471a085671049a06f5ccbe0e6b070f39f839cb/-/blob/pkg/conf/validate_custom.go#L34:6) and [one for external services](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@72471a085671049a06f5ccbe0e6b070f39f839cb/-/blob/enterprise/cmd/frontend/db/external_services.go#L17:10).

The two sets of validation code do not have access to one another. This is problematic, because:
* Validity of external services config can depend on current site config value and vice versa (e.g., GitHub permissions are set in external service config but require GitHub auth provider to be set in critical site config; ditto sometimes for GitLab permissions; external service permission settings that rely on username equivalency are not secure if users can change their own username).

Proposal:
* There should be one validation package (`pkg/conf/validate`) that validates the entirety of site/critical config and external services config.
* This package should accept a site/critical config value and values for each external services config (via dependency injection) to avoid a dependency path from a config package to the DB (which would likely result in a dependency cycle).
* This validation logic should be invoked whenever (1) the site config changes, (2) the critical config changes, (3) an external service is updated/added/removed. Validation errors should prevent the change from applying and show up in the UI being used to change the config. 

After this is implemented, the following TODOs are follow-ups:
- [ ] Add validation logic that guarantees the properties described above (the necessary auth providers are set with permissions are enabled, username immutability holds when required, etc.)
- [ ] Make errors show up in management dashboard UI (they currently do not).

**Comment by slimsag** [comment]
Before starting work on this, let's chat about this over a call. I think it's important to make sure we have a strong configuration model and there may be ways to resolve this without adding conglomerate validation. I want to make sure I understand the challenges here in-depth
