### ISSUE TITLE
Wildcard V2 Feedback: Storybook update

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#28982]
This feedback came out of our monthly Wildcard Component Library survey, which is a [roadmap item](https://github.com/sourcegraph/sourcegraph/issues/27915) related to the OKR [Frontend devs rate productivity of Wildcard component library 4+ out a scale of 5](https://github.com/sourcegraph/product-engineering-tracker/issues/6).

> I wish the storybook deployed at https://storybook.sgdev.org/ had examples and prop descriptions — I can, of course, go find the storybooks in repo and look at them, but distinguishing the idiomatic way of using components from all the options isn't always obvious.

Is this kind of documentation more appropriate for our planned Docusaurus work?

**Comment by umpox** [comment]
@taylorsperry I think this is something that we want to address as part of the Docs work. We have specifically talked about having code examples alongside UI example for this!

I've added this comment to https://github.com/sourcegraph/sourcegraph/issues/29034 and I will close this issue. Feel free to reopen if you disagree!
