### ISSUE TITLE
Wildcard V2 Feedback: new <FilteredConnection />

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#28981]
This feedback came out of our monthly Wildcard Component Library survey, which is a [roadmap item](https://github.com/sourcegraph/sourcegraph/issues/27915) related to the OKR [Frontend devs rate productivity of Wildcard component library 4+ out a scale of 5](https://github.com/sourcegraph/product-engineering-tracker/issues/6).
 
There should be a better way to do what the existing `<FilteredConnection />` does. This is a component that we use in a ton of places and should possibly be broken down into several new, smaller components. 

Some of the data fetching work that @umpox is working on probably addresses some of this.

**Comment by umpox** [comment]
Yeah this will be solved by [useConnection](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/components/FilteredConnection/hooks/useConnection.ts) and the FilteredConnection abstract ui components: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/components/FilteredConnection/ui/index.ts

I propose moving `useConnection` to Wildcard for more visibility. We can keep the `FilteredConnection` components in their current folder. Often we override these styles anyway, and we're planning on implementing similar styles through components like the `Combobox`

We can track FilteredConnection migration in this ticket: https://github.com/sourcegraph/sourcegraph/issues/23157

**Comment by umpox** [comment]
Added https://github.com/sourcegraph/sourcegraph/issues/29035 that will close this issue

We can track FilteredConnection migration in this ticket: https://github.com/sourcegraph/sourcegraph/issues/23157

**Comment by valerybugakov** [comment]
@umpox, @taylorsperry, since the problem described in this issue will be addressed by a combination of other tickets, should we close this one?

**Comment by umpox** [comment]
@valerybugakov I agree, I'll close this
