### ISSUE TITLE
Remove `New subscription button` from subscriptions page

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#28987]
As part of [this proposal](https://docs.google.com/document/d/1XBIJkarIk6b9Kve311X6N6TCMAdyFM0DOi_iWbmCcQc/edit#), we'd like to Remove the `New subscription` button from the subscriptions page (Update Settings > Subscriptions) and update the copy to read, “Contact us to purchase a subscription for a self-hosted Sourcegraph instance. See [pricing](https://about.sourcegraph.com/pricing/) for more information.” Reference below:

<img width="1437" alt="28987 - Subscription page updates" src="https://user-images.githubusercontent.com/43555476/146025194-b6d70437-2626-4241-98d2-3efdb0df740f.png">

**Comment by anthonygedeon** [comment]
I'll take this one!

**Comment by anthonygedeon** [comment]
@sourcegraph/contribution-reviewers
On the local build (sg start oss), there is no subscription button to click on the sidebar. When I visit sourcegraph.com I can navigate to the settings page and click on Subscription. What I see is the same thing that is shown on this issue.

**Comment by oleggromov** [comment]
Hey @anthonygedeon, thank you for the contribution! It's all good except two tiny comments that I left in the PR.

**Comment by taylorsperry** [comment]
Hey, @oleggromov, I know you gave us an update on this and why it's in "Waiting," but I forget. Would you please remind me?

**Comment by oleggromov** [comment]
@taylorsperry we've been waiting for the PR opened by the external contributor to be updated but since there has been no requested updates, I am now closing that one and opening a new one which will be merged soon.
