### ISSUE TITLE
Wildcard V2 Feedback: Storybook and Figma integration

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#28984]
## Problem statement

This feedback came out of our monthly Wildcard Component Library survey, which is a [roadmap item](https://github.com/sourcegraph/sourcegraph/issues/27915) related to the OKR [Frontend devs rate productivity of Wildcard component library 4+ out a scale of 5](https://github.com/sourcegraph/product-engineering-tracker/issues/6).

> It'd be cool if the components in the storybook had links to the corresponding frames from the Figma design system file, or vice versa. I often find that I jump between the two when I'm not sure if a certain component or variant has been implemented yet (or that I start from Figma vs. storybook, if I'm working off of a prototype design).

## Success criteria

All Wildcard components are linked to relevant wireframes in Figma.

## Implementation details

As a part of this issue, we can go through existing components and add links to relevant Figma frames. 
E.g., here's the for the `<Button />` component: 

https://github.com/sourcegraph/sourcegraph/blob/98b87fe6dd1da0304c10b600559ee659c0a9f091/client/wildcard/src/components/Button/story/Button.story.tsx#L23-L31

## Time estimate

- Pull requests with ~450 lines changed should take **4 hours** at maximum. Ping the reviewer in the spec pull request if time-consuming changes are required.
- Split the work into multiple pull requests if the total diff is bigger than 450 lines of code.

**Comment by taylorsperry** [comment]
I think that's a great idea, @valerybugakov--this is the sort of thing that I imagine is not "difficult" but could be very time-consuming. 💯

**Comment by gitstart-sourcegraph** [comment]
@valerybugakov Should we reopen this issue for updates of https://github.com/sourcegraph/sourcegraph/pull/31348#issuecomment-1042316859
