### ISSUE TITLE
Non bare repo check triggers deletion of Perforce repos

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#28988]
This [recent change](https://github.com/sourcegraph/sourcegraph/pull/28895) appears to be causing deletion of repos cloned using `p4-fusion`. 

An example log seen in local dev:

```
[gitserver] INFO removing corrupt repo, repo: /Users/ryan/.sourcegraph/repos/dax-golang/.git, reason: non-bare
```

**Comment by keegancsmith** [comment]
Just revert the PR and we can rework. But:

- Why are the perforce imports not bare? We should make them bare asap. We don't need the working copy at all, this seems like an oversight. Working copies are for dev machines, not servers and you end up running into a variety of issues. This might also explain how we ended up with a bare repo at the customer (who does use perforce). Note they ran into issues here.
- Can we exclude perforce repos here and get this check back?

**Comment by ryanslade** [comment]
I think this only affects clones initiated using the new `p4-fusion` client. It definitely used to clone bare repos but there may have been a regression. I don't think it's urgent to roll back the bare check yet but I'll know more tomorrow.
