### ISSUE TITLE
file: and path: filters

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#29004]
from @camdencheek ([slack thread for context](https://sourcegraph.slack.com/archives/C022SPMNR0W/p1639507551391400)):

this is different from `type:file` and `type:path`. That is a separate (and also confusing) issue. This is about the `file:` filter, not `type:file`. In an ideal world, I’d love to do the following things to solve all these issues, but I think it would require some nasty backwards-incompatible changes.
- Rename `type:file` to `type:content`
- Rename `type:path` to `type:file`
- Make a new `path:` filter that does what `file:` currently does (`path:^package\.json$` does not match `nested/package.json`)
Change the behavior of the `file:` filter to match the file name, not the full file path (e.g. `file:^package\.json$ matches nested/package.json`)

**Comment by camdencheek** [comment]
Closing since the current plan from the @sourcegraph/search-platform team is to merge `type:file` and `type:path` and make path a searchable field on the file result type.
