### ISSUE TITLE
Enforce PR approval

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#29005]
In order to meet the SOC2 requirement below, we need to enforce peer-review of all PRs before they're merged into main. 

> Code changes are systematically required to be peer-reviewed and approved prior to merging code into the main branch.

**Comment by bobheadxi** [comment]
@pdubroy mentioned potentially maintaining a list of unreviewed PRs instead of enforcing it strictly, but the wording here seems pretty clear-cut - WDYT Patrick?

**Comment by bobheadxi** [comment]
I've enabled the requirement, and updated https://github.com/sourcegraph/sourcegraph/pull/28759 to enforce it as well
