### ISSUE TITLE
insights: frontend creation form UI regression on pill treatment 

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#29002]
The repo: archived: and fork: filter help text on creating a search based insight seems to have a new pill treatment (assuming as a result of capture group forms or the search box work) and it looks: 

1. Like it’s missing padding on both light and dark themes – is the color supposed to cut off that close to the edge of the text? 
2. [Blocker] Unreadable on dark theme.
3. It also seems like the corner rounding / border radius is a bit much, though maybe that's just a visual side effect of the actual issue with the padding 

### Before this regression:
![image](https://user-images.githubusercontent.com/11967660/146062537-847812e0-0c0e-4d95-bcbb-a6d5e91b379e.png)

### Now: 
![image](https://user-images.githubusercontent.com/11967660/146062601-d74998a4-d490-423a-8234-ffb87b38305f.png)
![image](https://user-images.githubusercontent.com/11967660/146062640-dfe19604-7ca1-4680-a39d-121dd9de7538.png)

#### Normal screen size to show dark theme is hard to read: 
![image](https://user-images.githubusercontent.com/11967660/146062790-aaa67e66-8240-4ed8-b3d5-f3a4907575f0.png)

**Comment by Joelkw** [comment]
cc @unclejustin  @vovakulikov

**Comment by unclejustin** [comment]
@AlicjaSuska this is the CSS I was requesting in Figma. Could you please give me what you want this to be?

**Comment by vovakulikov** [comment]
@unclejustin I think according to the last design spec we don't have any background for these code pills.

**Comment by unclejustin** [comment]
Fixed with: https://github.com/sourcegraph/sourcegraph/pull/28923#issuecomment-994681523
