### ISSUE TITLE
Insights: regex capture groups failing if regex includes an `@` symbol

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#29025]
I think that @ is breaking on the backend capture groups endpoint but not in Sourcegraph. This is a valid regexp, the frontend UI tells me so (doesn’t throw a “regex formatting” error), but I get a backend error. I [can search this regexp in Sourcegraph and it’s valid](https://k8s.sgdev.org/search?q=TODO+%40(%5B%5Cw%5D%2B)+patterntype%3Aregexp).

So it seems like a problem with either our backend parsing or the compute endpoint? 

![image](https://user-images.githubusercontent.com/11967660/146105294-f567f6c7-421c-4411-b0bc-86ff99ed112a.png)

**Comment by CristinaBirkel** [comment]
I think this is a bug in the `compute` endpoint. I opened a new issue with the specific repro steps: https://github.com/sourcegraph/sourcegraph/issues/29477

**Comment by CristinaBirkel** [comment]
Fixed by: https://github.com/sourcegraph/sourcegraph/pull/29489. I tried this out on k8s where it's been deployed, and it doesn't throw an error anymore 🎉
