### ISSUE TITLE
"sg start monitoring" leaks docker containers

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#29026]
When `sg start monitoring` rebuilds services on file changes (example: working on dashboards), I think it leaves dangling containers behind.

Evidence:

1. docker ps output with duplicated container names
```
CONTAINER ID   IMAGE                            COMMAND                  CREATED          STATUS          PORTS                    NAMES
f55bf9089257   ctags                            "/usr/local/bin/univ…"   6 minutes ago    Up 6 minutes                             universal-ctags-23122
2aa898853a8f   ctags                            "/usr/local/bin/univ…"   15 minutes ago   Up 15 minutes                            universal-ctags-75517
26ba0267ef06   postgres_exporter:dev            "/usr/local/bin/post…"   16 minutes ago   Up 16 minutes   0.0.0.0:9187->9187/tcp   postgres_exporter
831f7cdadd2d   ctags                            "/usr/local/bin/univ…"   16 minutes ago   Up 16 minutes                            universal-ctags-65171
e04139ece213   ctags                            "/usr/local/bin/univ…"   16 minutes ago   Up 16 minutes                            universal-ctags-65125
63a66fc3d274   sourcegraph/syntax-highlighter   "sh -c '/http-server…"   23 minutes ago   Up 23 minutes   0.0.0.0:9238->9238/tcp   syntax-highlighter
```

1. errors about duplicate container names when re-running `sg start monitoring`

```
docker: Error response from daemon: Conflict. The container name "/postgres_exporter" is already in use by container "26ba0267ef06412c3e1e4c4840d013e8025f5a4131956b66b1d0497a78d1218a". You have to remove (or rename) that container to be able to reuse that name.
```

---

Manually `docker stop`ing the postgres_exporter container is mildly annoying, but eventually all the dangling containers slow my system to a crawl and I have to restart my computer (I suspect the qemu emulation on my M1 mac exacerbates this). 

I think possible solutions would include:

- Making sure that we include the `rm` flag whenever we need to `docker run` a service
- including a helper command that would automate running `docker kill (docker ps -q) && yes | docker system prune --all` as a way to "flip the table" if I need to totally reset my docker state

**Comment by bobheadxi** [comment]
cc @burmudar
