### ISSUE TITLE
Add quick configure buttons to critical site config console

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#2905]
Add "quick configure" buttons to management console critical site config editor for common actions like:
* Add auth provider
* Set license key
* Set external URL

**Comment by beyang** [comment]
@sqs what do you think about the above actions? This could alleviate more friction around enabling repository permissions / configuring auth.

**Comment by slimsag** [comment]
The management console has nothing to do with TLS since we don't do it in-app anymore.

**Comment by slimsag** [comment]
I think this is a good idea, these were actually originally goals when implementing the management console so I suspect @sqs will still agree they are good ideas. The only reason we don't have them today is due to them being cut out of scope to save time.

**Comment by sqs** [comment]
@beyang Can this be closed since https://github.com/sourcegraph/sourcegraph/pull/3387 was merged?

**Comment by slimsag** [comment]
Closing since there is nothing left to do here. @beyang reopen if important.
