### ISSUE TITLE
Helm chart: allow override for container args

### ISSUE THREAD

**Issue by caugustus-sourcegraph** [sourcegraph/sourcegraph#29063]
Right now, args are hardcoded for each container ([example](https://sourcegraph.com/github.com/sourcegraph/deploy-sourcegraph-helm@b86eb85dfb813b5215c93084dce78075bed1e0e7/-/blob/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml?L57)). When troubleshooting, it can be useful to replace the args with something custom like a sleep command, and [certain deployments](https://sourcegraph.com/github.com/sourcegraph/deploy-sourcegraph-helm@b86eb85dfb813b5215c93084dce78075bed1e0e7/-/blob/sourcegraph/templates/cadvisor/cadvisor.DaemonSet.yaml?L59) may have more long-lived customizations.

Add the ability to override container args in the values.yaml file. If feasible, provide the existing args as a template-level default instead of specifying them in values.yaml as an explicit default. ([example default](https://sourcegraph.com/github.com/sourcegraph/deploy-sourcegraph-helm@b86eb85dfb813b5215c93084dce78075bed1e0e7/-/blob/sourcegraph/templates/pgsql/pgsql.Deployment.yaml?L137))

**Comment by michaellzc** [comment]
## Option 1 - the most generic approach

`_helper.tpl`

```tpl
{{- define "sourcegraph.args" -}}
{{- $top := index . 0 }}
{{- $service := index . 1 }}
{{- $defaultArgs := index . 2 }}
{{- default $defaultArgs (index $top.Values $service "args") | toYaml }}
{{- end }}
```

```tpl
spec:
  containers:
  - name: migrator
    args:
    {{ include "sourcegraph.args" (list . "migrator" (list "up")) }}
```

cons:
Caller is easy to mess up the indentation. We can't use `nindent` in the partial template because the partial tpl could be referenced at different places and indentation may not be the same. 

for example, this won't work.
```tpl
spec:
  containers:
  - name: migrator
    args: {{ include "sourcegraph.args" (list . "migrator" (list "up")) }}
```

## Option 2 - each service has its own partial template

```tpl
{{- define "sourcegraph.migrator.args" -}}
{{- default (list "up") .Values.migrator.args | toYaml | nindent 8 }}
{{- end }}
```

```tpl
spec:
  containers:
  - name: migrator
    args: {{ include "sourcegraph.args" (list . "migrator" (list "up")) }}
```

cons:
We need to creat a ton of new partial template
