### ISSUE TITLE
"Enabled / disabled" label for toggles in code intel configuration is confusing

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/sourcegraph#29096]
- **Sourcegraph version:** main

#### Steps to reproduce:

1. Click "Create new policy" under the Code Intel > Configuration as a site admin.

#### Expected behavior:

There should be no text (because most people are likely already familiar with toggles), or the text should match the button position.

#### Actual behavior:

Left = greyed out / Disabled, Right = colored / Enabled.

However, the button has a label next to it which says "Enabled / disabled" which makes it a little confusing: does left = enabled and right = disabled?

![Screenshot showing toggle with confusing label](https://user-images.githubusercontent.com/93103176/146351989-c5070df1-d224-4e37-890a-c8ac877dce7f.png)

It's not a big deal, but seems like an unnecessary bit of friction.

**Comment by mrnugget** [comment]
What about some sweet radio buttons and enough space for descriptive text?

![screenshot_2022-01-03_18 12 26](https://user-images.githubusercontent.com/1185253/147959453-272ec844-dfc6-45f9-9d8e-5b201c7c5085.gif)

(I checked other dev-tool-y sites on how they do their settings page and I really like what Netlify does: they use these radio buttons with more text next to each button so it's clear what's toggled.)
