### ISSUE TITLE
Don't have configmap updates require restarting deployments

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#29125]
We can use `kustomize` to generate these configmaps

**Comment by filiphaftek** [comment]
@daxmc99 is this task done? We use kustomize on preprod so config maps are generated and deployment is restarted. [implementation](https://github.com/sourcegraph/deploy-sourcegraph-cloud/blob/release/overlays/preprod/frontend/kustomization.yaml#L14)

**Comment by daxmc99** [comment]
I think this should be more than just pre-prod. We should duplicate this change to prod as well.
