### ISSUE TITLE
Create search homepage for VS Code extension

### ISSUE THREAD

**Issue by tjkandala** [sourcegraph/sourcegraph#29122]
The VS Code extension MVP currently just displays an empty search bar when a search tab is opened. We should create a proper "search homepage" with some educational examples/links and better layout for an empty state.

[See in Figma](https://www.figma.com/file/EXXvfxVwtCIsrbQez4rPlF/VS-Code-Extension-MLP?node-id=1371%3A2976)

**Comment by abeatrix** [comment]
Search Homepage for VSCE Desktop + VSCE Web Completed
![Screen Shot 2021-12-21 at 11 40 59 AM](https://user-images.githubusercontent.com/68532117/147005576-580edb6d-e8fd-4c82-842b-687e804959d3.png)
![homepage](https://user-images.githubusercontent.com/68532117/147005639-2c11dea1-c676-4451-9ef6-3f5af2304921.png)
