### ISSUE TITLE
Add onboarding view to VS Code extension sidebar

### ISSUE THREAD

**Issue by tjkandala** [sourcegraph/sourcegraph#29121]
Add an "onboarding view" to the VS Code extension sidebar that 
- gives a summary of functionality 
- links to learning resources
- prompts users to create an account/sign in with an access token

[See in Figma (add metrics from cards)](https://www.figma.com/file/EXXvfxVwtCIsrbQez4rPlF/VS-Code-Extension-MLP?node-id=1371%3A2976)

**Comment by abeatrix** [comment]
![image](https://user-images.githubusercontent.com/68532117/152559707-63ec756e-1e27-4b6b-9196-ab23323afee8.png)
![image](https://user-images.githubusercontent.com/68532117/152559808-19353058-85ea-42d1-847f-db940097a163.png)
