### ISSUE TITLE
Bug: Adding email to users with no primary emails would break Emails and Site Admin page

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#29120]
- **Sourcegraph version:** 3.34.2
- **Platform information:** All platforms 

#### Steps to reproduce:

1. Log in as a Site Admin
2. Create a new user **without** an email
3. Log in as the new user > Settings > Emails > Add email address
![image](https://user-images.githubusercontent.com/68532117/146410272-020828ac-b61d-4ee7-b7de-63c680be8985.png)

#### Expected behavior:
Emails page show up normally with the newly added email showing as `not verified` 

#### Actual behavior:
Emails page stuck in loading
![image](https://user-images.githubusercontent.com/68532117/146410407-1a7e9611-507d-41a3-94a7-fc00b5986d65.png)
An error would show up after refreshing the page: `User email not found: [id xx]`
![image](https://user-images.githubusercontent.com/68532117/146410494-758688f9-5756-4e43-9200-35ad4dcbbfa7.png)
It would also break the Site Admin > Users page until the user has verified their email
![image](https://user-images.githubusercontent.com/68532117/146411238-c0bae0e9-baaf-4883-a6e2-eb474bdc9acf.png)

#### Note:
This issue would resolve after the user has verified their email (through the verification email sent to their inbox, fixed in https://github.com/sourcegraph/sourcegraph/pull/25008), but I think we might need to handle the error better (to stop it from breaking the Email and SIte Admin Users pages) before the user can verify the email.

**Comment by jplahn** [comment]
Not sure this is Repo Management. It seems closest to user auth which @sourcegraph/cloud-saas is handling.

@sourcegraph/cloud-saas please push back if you disagree 🙂.

**Comment by unknwon** [comment]
@jplahn I agree, created https://sourcegraph.atlassian.net/browse/CLOUD-194

**Comment by abeatrix** [comment]
@unknwon I've created a PR as an attempt to fix this issue since a customer has just brought up this issue again and added you and your team as the reviewers 😄

**Comment by unknwon** [comment]
@abeatrix thank you!
