### ISSUE TITLE
Search menu navbar item not cmd-clickable to open a new tab

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#29130]
I’m no longer able to cmd-click on the “search” menu item to create a new tab opened to the home search page. (For example, if I want to start a new search without losing my current place, or want to test a search for an insights/context/monitoring tab open). The other navbar items still work. Slightly more frustratingly, cmd-clicking this navbar item takes me to the search page in my current tab, meaning I get taken away from my page – when I explicitly want to stay on the page and instead open a tab in the background.

To reproduce, visit any sourcegraph instance and cmd-click on the "Search" (not the dropdown items) from any non-homepage.

**Comment by camdencheek** [comment]
Closing as no longer relevant
