### ISSUE TITLE
GitLab integration roadmap

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#2916]
This issue captures the work (which spans multiple releases) to improve Sourcegraph's integration with GitLab.com and self-hosted GitLab instances.

- [Direct UI integration and deployment bundling with GitLab](https://github.com/sourcegraph/sourcegraph/issues/1000)

**Comment by keegancsmith** [comment]
@felixfbecker The 3.6 milestone will be closed very soon. Please triage / backlog this to another milestone.

**Comment by felixfbecker** [comment]
Closing in favor of #5380
