### ISSUE TITLE
Document exact postgres permissions needed

### ISSUE THREAD

**Issue by caugustus-sourcegraph** [sourcegraph/sourcegraph#29208]
https://docs.sourcegraph.com/admin/postgres#role-requirements documents required extensions and says the `sg` role must have `full access` to the `sg` database.

It would be helpful to replace that with exact permissions / commands to run to create the role, and confirm that this is sufficient to start up the pgsql and codeintel databases.

Related: https://github.com/sourcegraph/customer/issues/596

**Comment by caugustus-sourcegraph** [comment]
The 3.36 release includes support for the migrator container (though it's not used by default). This container can use a separate set of credentials from frontend to perform DDL transformations, so that frontend can run as a less-privileged user.

Slightly more context (mentioned in the linked issue, but this is the most relevant comment):
https://sourcegraph.slack.com/archives/C02E4HE42BX/p1639697874024200?thread_ts=1639685813.016400&cid=C02E4HE42BX

**Comment by kevinwojo** [comment]
I admittedly haven't tracked 3.36 as closely as I should've in terms of migrations. I think the main issue is that our migrations assume that the user has SUPERUSER permissions -> mainly the ability to CREATE (enable) extensions on the database and apparently even delete a ROLE. 

To that end I've done some discovery in terms of codeintel and pgsql: https://docs.google.com/document/d/1BdzgBM53xSCclLaDhysaQpXEea0_tC4bLs8dwF2VTPs/edit?usp=sharing

**Comment by kevinwojo** [comment]
I still need to test against a running instance of Sourcegraph

**Comment by kevinwojo** [comment]
https://github.com/sourcegraph/sourcegraph/pull/30124

**Comment by kevinwojo** [comment]
Perhaps related? https://github.com/sourcegraph/sourcegraph/issues/28729
