### ISSUE TITLE
errors: unify on a standard multi-error library

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#29219]
https://github.com/sourcegraph/sourcegraph/pull/29062#discussion_r770000050

![image](https://user-images.githubusercontent.com/23356519/146629668-ce10b13f-57a3-442c-8b0b-d79cd0bcbdfd.png)

**Comment by efritz** [comment]
Found a related issue as well I took care of: https://github.com/sourcegraph/sourcegraph/pull/30604

**Comment by bobheadxi** [comment]
This was closed by https://github.com/sourcegraph/sourcegraph/pull/31466
