### ISSUE TITLE
search: improve repository index status page

### ISSUE THREAD

**Issue by stefanhengl** [sourcegraph/sourcegraph#29246]
- [ ] Add shard size
- [ ] Add button to force reindex

See [code-intelligence](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/code-intelligence/uploads/TFNJRlVwbG9hZDoxMDQ3MDkx) for more inspriation.

**Comment by ggilmore** [comment]
I moved the tool tip part of this to a new issue: https://github.com/sourcegraph/sourcegraph/issues/34950

**Comment by ggilmore** [comment]
> Add shard size:

Isn't this already on the settings page?
<img width="1719" alt="Screen Shot 2022-05-04 at 4 25 52 PM" src="https://user-images.githubusercontent.com/9022011/166847260-d99ccfca-bf44-49ba-b3ad-3e6b7866042a.png">

**Comment by stefanhengl** [comment]
> Isn't this already on the settings page?

Where?

**Comment by ggilmore** [comment]
We discussed this offline, but I was referring to the index size in the screenshot above. (I realize now that the arrow is misleading)

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket, please let us how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
