### ISSUE TITLE
Integrate `sg ops` into deployment repos for image updates

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#29251]
This will replace Renovate. 

First steps for this:
1. Create a composable CI step to add the `sg` tool to our CI pipeline. 
1. Replace the Renovate daily image update job 
1. Test to ensure that these changes are useful

**Comment by danieldides** [comment]
`sg ops` to be created/merged in this PR: https://github.com/sourcegraph/sourcegraph/pull/29158

**Comment by jhchabran** [comment]
FYI https://github.com/sourcegraph/sourcegraph/pull/38489
