### ISSUE TITLE
Add seperate overlays for deploy-sourcegraph-cloud

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#29255]
We need to have two seperate deployment envs for Cloud

1. `pre-prod`
2. `prod`

We are going to use to `kustomize` to template out the environment. 

High-level guidance:
We should have `pre-prod` use 1/4 the resources of the prod overlay

Part of https://github.com/sourcegraph/sourcegraph/issues/28082

**Comment by daxmc99** [comment]
Estimate is 2 days of dev time for this

**Comment by filiphaftek** [comment]
@daxmc99 are we going to use kustomize also for production deployment?

**Comment by filiphaftek** [comment]
Related to [this](https://github.com/sourcegraph/sourcegraph/issues/29125)

**Comment by filiphaftek** [comment]
@daxmc99 should we update all applications to use kustomize? Same as we did we frontend?

**Comment by daxmc99** [comment]
@filiphaftek I think that would be nice but doing the frontend was the major component. I think this should be enough to close or we should move this issue back to a planning stage instead of waiting for feedback

**Comment by filiphaftek** [comment]
@daxmc99 I agree - frontend is the component which caused some downtimes in the past b/c of missing configMap reload. I am closing this.
