### ISSUE TITLE
Display filename first in `file:` completions

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#29270]
* **Sourcegraph version:** live on Cloud
* **Platform information:** Firefox

#### Steps to reproduce:

1. Type in query `repo:^github\.com/scalameta/metals$ file:Parser`
2. Trigger code completion

#### Expected behavior:

The top completion should be "ScaladocParser.scala - mtags/src/main/scala-2/scala/meta/internal/docstrings\`. Something that looks similar to the "Go to file" command in VS Code

![image](https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/4004bca4-ebca-4689-a8a6-d9148f068aae/d89951f6-43dd-41f2-8065-c0871ee413cf?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy80MDA0YmNhNC1lYmNhLTQ2ODktYThhNi1kOTE0OGYwNjhhYWUvZDg5OTUxZjYtNDNkZC00MWYyLTgwNjUtYzA4NzFlZTQxM2NmIiwiaWF0IjoxNzE4MDM0ODc2LCJleHAiOjMzMjg4NTk0ODc2fQ.DA4YMPCdBlFOmh8tg4TZLuHt0HtekDOXDhicJYa-AzI "=616x")

#### Actual behavior:

The completion is `file:^mtags/src/main/scala-2/scala/meta/internal/docstrings/ScaladocParser\.scala$` and the `ScaladocParser.scala` filename is not visible because the directory name is too long.

![image](https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/e2395f0d-a6fe-4c67-ae70-c2aacaa1278b/b8e8c9d4-09b5-4d37-af45-b96ca7aa7080?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy9lMjM5NWYwZC1hNmZlLTRjNjctYWU3MC1jMmFhY2FhMTI3OGIvYjhlOGM5ZDQtMDliNS00ZDM3LWFmNDUtYjk2Y2E3YWE3MDgwIiwiaWF0IjoxNzE4MDM0ODc2LCJleHAiOjMzMjg4NTk0ODc2fQ.RH2QGHbXxh86O4rgAjQU3d8hkD6-zDKnFLHFZjfoOrs "=1101x")

**Comment by fkling** [comment]
We do not show the file name first but we have a lot more space to show the file name now. Closing this for now

<img src="https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/bf32f787-e2dd-4447-be98-974a674539c2/04a5e855-98fa-4bf9-9217-e914ddd18262?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy9iZjMyZjc4Ny1lMmRkLTQ0NDctYmU5OC05NzRhNjc0NTM5YzIvMDRhNWU4NTUtOThmYS00YmY5LTkyMTctZTkxNGRkZDE4MjYyIiwiaWF0IjoxNzE4MDM0ODY2LCJleHAiOjMzMjg4NTk0ODY2fQ.zEoOtW1bLN28nMrA1WBlDcL9FHa-yEb4Mj1ZxhudbuI " alt="Screenshot 2024-06-10 at 17.53.50.png" width="1150" height="491" />
