### ISSUE TITLE
Code Insights: [BE] Support filters in `createLineChartSearchInsight`

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#29293]
At the moment we don't have a filters field in the input type for the `createLineChartSearchInsight` mutation. Because of this FE has to create insight without filters and then send another mutation `updateLineChartSearchInsight` to be able to set filters. 

All of this brings a lot of complexity to the FE so it would be good to support filters in the `createLineChartSearchInsight`

**Comment by vovakulikov** [comment]
cc @coury-clark @CristinaBirkel

**Comment by CristinaBirkel** [comment]
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/27836
