### ISSUE TITLE
Upgrade `reactstrap` to latest version

### ISSUE THREAD

**Issue by gitstart-sourcegraph** [sourcegraph/sourcegraph#29301]
## Ref
https://github.com/sourcegraph/sourcegraph/issues/27691

## Problem statement

we're currently on 8.9.0 and the latest is 9.0.1. We're interested in using a new feature of the Collapse component in Batch Changes that was introduced in 9.0.0, but we found that when we tried to upgrade, it actually broke the tooltips.

## Implementation details

1. Upgrade the `reactstrap` package to latest version,
2. Update <Tooltip /> to ensure it is not broken due to upgrade process
## Time estimate

- Pull requests with ~450 lines changed should take **3 hours** at maximum. Ping the reviewer in the spec pull request if time-consuming changes are required.
- Split the work into multiple pull requests if the total diff is bigger than 450 lines of code.

**Comment by gitstart-sourcegraph** [comment]
Hello @valerybugakov @oleggromov 
Latest version of Reactstrap (`v9`) requires usage of bootstrap `v5.1 +` [Ref here](https://reactstrap.github.io/?path=/docs/home-upgrading--page), kindly confirm if as part of this upgrade we can upgrade to bootstrap `v5.1` from current `4.5.2`

**Comment by valerybugakov** [comment]
@umpox @gitstart-sourcegraph, I would say that it's out of the scope. We don't have the capacity for this major migration, especially considering that we work on removing our dependency on Bootstrap where possible.

I suggest leaving a comment in the original tickets that it's blocked by Bootstrap v5.1 migration.

**Comment by valerybugakov** [comment]
@umpox @gitstart-sourcegraph, I would say that it's out of the scope. We don't have the capacity for this major migration, especially considering that we work on removing our dependency on Bootstrap where possible.

I suggest adding a comment to the issue description that it's blocked by Bootstrap v5.1 migration.
