### ISSUE TITLE
Collect latency across more actions and dimensions

### ISSUE THREAD

**Issue by ebrodymoore** [sourcegraph/sourcegraph#29314]
[Private issue](https://github.com/sourcegraph/analytics/issues/335) for reasons and context. I'm tagging each team here passively right now in case anybody can take a look. Shortly when we all return from the holidays I'd like to have a point person from each team at least evaluate the feasibility of this ask, so I'll follow-up in Slack after the break. 

- [ ] Since we are streaming we might want to add a dimension here: {time to first result, time to (10 results or completion)}. Not sure what the right unit of time is (week? day? hour?). Minimum would be the current reading, but ideally we would have a chart to track trend over time.
- [ ] 90th percentile file view latency (same presentation as above)
- [ ] 90th percentile latency for hover tooltip load, go to definition, find references time to first result (same presentation as above) (@ebrodymoore: we collect codeintel.lsifDocumentHighlight but not sure what exactly that's measuring)

**Comment by taylorsperry** [comment]
I've created a [separate issue](https://github.com/sourcegraph/sourcegraph/issues/36561) for Frontend Platform to take a look at how we can help address this, and am removing the label from this issue.

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket, please let us know how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
