### ISSUE TITLE
Update NGINX distribution in Cloud

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#29315]
While creating the pre-prod environment we found that our nginx ingress resource is out of date. 
This is causing issues with upgrading our overall cluster. 

Plan to upgrade: 
1. Move to the latest released version of Nginx 
2. Leverage Helm to allow us to easily see our changes
3. Upgrade the ingress on dogfood before attempting the production upgrade. 

Process for production cutover: 
1. Create a separate, new ingress controller with a separate ingress class
1. Create a new ingress resource that replicates the existing ingress resource except for ingress class
1. Allocate a new `external_address` in Terraform and use that for the Ingress IP
1. Manually test that the new ingress via `curl --resolve` to ensure the site is reachable at the IP and has a valid origin cert
1. Make the Terraform change in `dns/` to switch the DNS record to point to the new service. 
1. Enable Full TLS (strict) in Cloudflare on dogfood and cloud

**Comment by danieldides** [comment]
Using dogfood as a test environment. This is the helm configuration we've used to deploy the latest nginx ingress controller:
 https://github.com/sourcegraph/deploy-sourcegraph-dogfood-k8s/pull/3641

**Comment by JenRed777** [comment]
Dog food will be deployed this week.
