### ISSUE TITLE
yarn.lock being update at yarn install - why and should we fix it? 

### ISSUE THREAD

**Issue by oleggromov** [sourcegraph/sourcegraph#29321]
## Issue 
When I run `sg start` or `yarn` on my development machine, it seems to update `yarn.lock` file - and I just tend to `get reset` it back to the current `HEAD` state.

For instance, the most recent diff at`8b026d4a3e72ba73ee29ac9b24a3a44644932e09` looks like this: https://gist.github.com/oleggromov/53af1c8b5013705528b5477c251bd55e

## Questions and possible solutions

1. Why does this happen exactly? Is it because of some dependencies (or even us) aren't fixing their deps version in `package.json`-s? I tried to track down deletion of `readdirp@~3.6.0` from `yarn.lock` via git blame but couldn't. It just got me to the 1-year-old PR and I am not sure who's relying on `readdirp` and why it is no longer needed.

2. Should I just accept the changes after `yarn install` and commit the changes? This doesn't feel right because I don't even know why they have happened but could be a decent one-off solution.

3. In general, should we **a) prevent yarn.lock from being updated when not expected** or **b) forget about it and commit it every time it changes**? I am leaning towards 2 because I dislike unexpected/unplanned changes - I would expect only explicit `yarn add` or similar to update my lock files.

Please LMK what you think is the best possible solution in this particular case and in general.

**Comment by valerybugakov** [comment]
Thanks for raising this, @oleggromov!

> Why does this happen exactly?

Usually, it doesn't happen, at least on my local machine.

> Should I just accept the changes after yarn install and commit the changes?

Ideally, we want to understand why it happened and fix the root cause. It might be a one-off case caused by some PR merged without proper `yarn.lock` update.

> In general, should we a) prevent yarn.lock from being updated when not expected or b) forget about it and commit it every time it changes?

The answer to the previous question is applicable here.

**Comment by oleggromov** [comment]
@valerybugakov this makes sense to me. I've created a one-off fix for now and will keep watching out for the instances of the same issue.

**Comment by oleggromov** [comment]
After a quick discussion with @umpox, I am closing this and will be on a lookout for new occurrences of package-lock.json changes.
