### ISSUE TITLE
Depricate or Update - Sourcegraph Server Gen

### ISSUE THREAD

**Issue by DaedalusG** [sourcegraph/sourcegraph#29338]
#### Describe the issue
Documentation still references use of `sourcegraph-server-gen` for migrating blue green deployments. However this script no is out of date and doesn't currently create a `pg_dump` for codeintel-db. Further is it is to be supported the documentation on how to install and run the script could use an update.

#### Where is the issue located?
In our docs: [https://docs.sourcegraph.com/admin/install/kubernetes/update#updating-blue-green-deployments](https://docs.sourcegraph.com/admin/install/kubernetes/update#updating-blue-green-deployments)
Sourcegraph Server Gen repo: [https://github.com/sourcegraph/sourcegraph-server-gen](https://github.com/sourcegraph/sourcegraph-server-gen)

#### Suggested resolution
This script seems workable and maybe even valuable for use in more general migration scenarios. Leaving this in the hands of delivery to determine value. If this script is not going to be updated it should be removed from docs. 

Related Issue: https://github.com/sourcegraph/sourcegraph/issues/11600

**Comment by caugustus-sourcegraph** [comment]
The docs were removed (temporarily?) in https://github.com/sourcegraph/sourcegraph/pull/29440
