### ISSUE TITLE
Sourcegraph.com does not auto add soft-deleted repositories

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#2933]
I've been out for a week. But this issue reported we couldn't add kubernetes/kubernetes to Sourcegraph.com last Friday https://github.com/sourcegraph/sourcegraph/issues/2773

I just tried to, and it seems our special-casing for Sourcegraph.com is not working, since the repo is not auto-adding.

https://sourcegraph.com/github.com/kubernetes/kubernetes/

**Comment by keegancsmith** [comment]
Potentially useful trace https://app.lightstep.com/sourcegraph-prod/trace?span_guid=5d3d901b84d3cb83&at_micros=1553263646434285

**Comment by tsenart** [comment]
I just checked a repo which didn't exist in the DB, visited, and it worked: https://sourcegraph.com/github.com/tsenart/haskell-learning

**Comment by keegancsmith** [comment]
So the root cause of this is kubernetes is soft-deleted. It seems the auto-add logic doesn't un-soft delete repositories on Sourcegraph.com

**Comment by keegancsmith** [comment]
We now hard delete, so this is no longer an issue.
