### ISSUE TITLE
Puppeteer flake that crashes node

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#29359]
See [this build](https://sourcegraph.slack.com/archives/C02FLQDD3TQ/p1640110904268100?thread_ts=1640110346.267900&cid=C02FLQDD3TQ) for the context. 

I just saw another [failure](https://sourcegraph.slack.com/archives/C02FLQDD3TQ/p1640774664273200) today, so this is still happening. 

@valerybugakov and @umpox I took the initiative of assigning you. I tried to pinpoint the faulty test but did not succeed. Because we cannot retry those puppeteer steps, this forces to re-run entirely a given build.

Could you bump this at the top of your backlog as this is happening frequently and hard to diagnose 🙏 ?

**Comment by umpox** [comment]
Update: Since fixing the log spam (https://github.com/sourcegraph/sourcegraph/pull/29439) we haven't seen any more failures. Going to keep an eye on it for the next few days and close if it doesn't reappear

**Comment by umpox** [comment]
Update: Still no failures. Going to close this issue! We can reopen if we see it again
