### ISSUE TITLE
Tree view: element is present but not visible when loading

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#2936]
[CI failed](https://buildkite.com/sourcegraph/sourcegraph/builds/29894#f7b46967-f982-4a35-a995-aa9938440cf9/42-204) when attempting to click on an invisible element:

https://github.com/sourcegraph/sourcegraph/blob/62f8620ef06e79778a448bdc9815107eefeb77bf/web/src/e2e/index.e2e.test.tsx#L426-L430

I think this means that the `[data-tree-path="godockerize.go"]` element was present, but not visible. The [failure screenshot](https://buildkite.com/sourcegraph/sourcegraph/builds/29894#f7b46967-f982-4a35-a995-aa9938440cf9/42-151) shows that the page was still loading:

![image](https://user-images.githubusercontent.com/1387653/54840306-ed7af680-4c89-11e9-81a9-effc2f7d309b.png)

Assignees to triage.

The e2e tests have been modified to not get tripped up on this in the future https://github.com/sourcegraph/sourcegraph/pull/2935

**Comment by pdubroy** [comment]
Closing this — last update was over two years ago, so I'm assuming it's obsolete. Please feel free to re-open if I'm wrong.
