### ISSUE TITLE
Search streaming API should not be exposed under two separate routes, should not be exposed under UI router

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#29399]
[This search](https://sourcegraph.com/search?q=context:%40sourcegraph+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+/search/stream+lang:go+file:router&patternType=literal) shows me that the search streaming API is registered in three places:

1. `sourcegraph.com/search/stream` under `app/ui/router.go` (this does not make sense)
2. `sourcegraph.com/.api/search/stream` under `httpapi/router/router.go` (this is good)
3. The internal HTTP API under `httpapi/router/router.go` (this is good)

We should:

1. Ensure no clients are using `/search/stream`, update them to use `/.api/search/stream` instead.
2. Remove this route entry entirely: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@276bd3513b286c29d127fbd11ede8735e5c3ab00/-/blob/cmd/frontend/internal/app/ui/router.go?L137

Why:

1. It's confusing, and these routes will have different behavior: because `/search/stream` is a UI route, all cross-origin requests to it will be denied outright - whereas the `/.api/search/stream` one is an API route which allows it to be used from other domains, used with access tokens, etc.
2. It's weird to expose an API under the UI router - it doesn't match our security model and could confuse others when trying to reason about the security model (but there is no imminent danger here)

**Comment by slimsag** [comment]
@sourcegraph/search-core Is this something you could execute? Should be pretty easy to fix, the hardest part here is just updating clients to use `/.api/search/stream`.

**Comment by stefanhengl** [comment]
Clients 
- [ ] search-blitz
- [ ] src-cli
- [ ] browser
- [ ] batches
- [ ] gqltestutil

Documentation
- [ ] stream API documentation

**Comment by stefanhengl** [comment]
@slimsag [The browser uses the standard EventSource](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/shared/src/search/stream.ts?L437&subtree=true) to consume events from /search/stream. According to [this discussion](https://github.com/whatwg/html/issues/2177), EventSource does not support setting headers. One way to fix this is to implement a SSE client from scratch with fetch just like we did for Go. Before we investigate in that direction, do you see an opiton to change something in the backend, e.g. adding a middleware, so that we could keep using the standard SEE client?

**Comment by slimsag** [comment]
Why would we need to set headers at all?

`/.api` routes are authenticated using session authentication / cookies (no headers needed) as long as the request came from a trusted origin (sourcegraph instance itself, browser extension, or one of the origins listed in `corsOrigin` site config) Should just be fine to switch directly over.

To be clear, the current `/search/stream` API in use is MORE restricted in what it can do than `/.api/search/stream`, so if anything switching over will help you 😛

As an aside note.. we should switch to Microsoft's https://github.com/Azure/fetch-event-source over the browser's native EventSource API, as browser native one is quite limited in what it can do. `fetch`-based ones are just plain better IMO.

**Comment by stefanhengl** [comment]
The SSE request is rejected as not authenticated because the browser's native EventSource doesn't send an `origin` Header.

the API handler uses `session.CookieMiddlewareWithCSRFSafety` unlike the APP handler which uses `session.CookieMiddleware`.  in `session.CookieMiddlewareWithCSRFSafety` we check (1) if the request contains the header `x-requested-with` or (2) if it comes from a trusted origin. The trusted origin is based on the `origin` header. However the SSE request doesn't send an `origin' header and we cannot add it with `EventSource`.

Microsoft's fetch-event-source looks promising, I will check it out.

**Comment by slimsag** [comment]
Ahh okay, I see, I had forgotten about this, interesting. I actually knew this, quoting what I wrote earlier in https://github.com/sourcegraph/sourcegraph/pull/27931#issue-1057760849:

> Browsers do not always send the Origin header. From https://fetch.spec.whatwg.org/#origin-header
> 
> > The `Origin` header is a version of the `Referer` [sic] header that does not reveal a path.
> > It is used for all HTTP fetches whose request’s response tainting is "cors", **as well as those
> > where request’s method is neither `GET` nor `HEAD`. Due to compatibility constraints it is
> > not included in all fetches.**
> 
> For example, a GET request to Sourcegraph's search streaming API endpoint would likely not have an `Origin` header sent along with the request. In this situation, we have no way of telling if the request came from a trusted origin or not, and so `X-Requested-With` being included can inform us that the request came from a trusted origin _because for that header to be included, the request must have passed the CORS preflight._

But yeah, we should use a fetch-based SSE API for the browser. If that doesn't work let me know and I can brainstorm.

**Comment by stefanhengl** [comment]
@sourcegraph/search-product I need support for the typescript parts of this change. The gist of it is that EventSource does not send an origin header and is therefore blocked when calling .api/search/stream instead of /search/stream (see more details above). What do you think about using Microsoft's fetch-event-source instead to set the origin header? Could search-product take this over?

**Comment by limitedmage** [comment]
Maybe @benvenker and @lguychard can help prioritize this for Search Product team. Currently I don't think we have much bandwidth to look at this. Looking at https://github.com/Azure/fetch-event-source though, it seems fairly straight-forward to get a prototype working. Relevant code is here: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/shared/src/search/stream.ts?L437

**Comment by rvantonder** [comment]
I have... updates. Been hacking at getting Compute endpoint (implemented at `/.api/compute/stream`) to work over auth. After trying https://github.com/Azure/fetch-event-source, I learned:

- No matter what the potatoes I do, setting the origin header explicitly with `Azure/fetch-event-source` doesn't work--the header will not appear in the HTTP GET request. It just won't get set. Any other headers will get set. So: Although I can't find a reliable source for this, I assume the browser will actually not allow you to set the `origin` header for `GET` requests explicitly (and `Azure/fetch-event-source` is powerless here). This is ~sorta in line with what is said in [the spec](https://fetch.spec.whatwg.org/#origin-header):

> `origin` is used for all [HTTP fetches](https://fetch.spec.whatwg.org/#concept-http-fetch) whose [request](https://fetch.spec.whatwg.org/#concept-request)’s [response tainting](https://fetch.spec.whatwg.org/#concept-request-response-tainting) is "cors", as well as those where [request](https://fetch.spec.whatwg.org/#concept-request)’s [method](https://fetch.spec.whatwg.org/#concept-request-method) is neither `GET` nor `HEAD`.

In the sense that, the spec basically says, there is no guarantee when the header is `GET`. It seems browsers go and enforce this by simply not letting origin be set. When I run the request and add an `origin` header directly in curl, it works, so this is a browser decision, and again, `Azure/fetch-event-source` is powerless here.

- The `origin` header _IS_ set when using a `POST` method. So, I'm going to support the compute endpoint via `POST` only going forward (assuming nothing else blocks me). I would rather do that, then have to implement the compute streaming endpoint in `ui/router` (which is what we're trying to get away from riiight?)

---

> We should use a fetch-based SSE API for the browser. If that doesn't work let me know and I can brainstorm.

### Take away for this issue: getting rid of the `ui/router` endpoint and only using `/.api/search/stream` seems like we'll also have to switch from `GET` requests to using `POST` method. Either that or, @slimsag has to do more brainstorming.

**Comment by slimsag** [comment]
I think using POST is a bit of a hack. You don't have to send an `Origin` header. you need to send *either* an origin header OR `X-Requested-With: Sourcegraph` - the latter is preferred.

Adding that header should enforce a CORS pre-flight request and grant your request cookie-based auth, i.e. 'just work'

**Comment by rvantonder** [comment]
Ohhh, totally missed that. I shall add it to my spellbook and revisit updating this later. It does not seem so horrible to have a `POST` handler (longer query strings, if that's ever an issue), but yeah sounds like I should prefer `X-Requested-With`

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket, please let us know how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
