### ISSUE TITLE
branch previews for web app

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#29410]
Placeholder, will come back to flesh this out: https://sourcegraph.slack.com/archives/C07KZF47K/p1641302527428800

> Hey, everyone! Do we have a way to deploy a branch (web changes) somewhere temporary to share w/ stakeholders before merging PR?

> I haven't used this myself, but `sg run web-standalone-http-prod` or similar seems to spin up a web app that proxies to another Sourcegraph instance, maybe something like that + ngrok? 

> Yeah, it works locally, but I was thinking about something similar to netlify deploys, like a temporary server where I can deploy and just share a link.

**Comment by taylorsperry** [comment]
Closed by https://github.com/sourcegraph/sourcegraph/pull/33642
