### ISSUE TITLE
Support Cloudflare Access: Identity and Access Management

### ISSUE THREAD

**Issue by KattMingMing** [sourcegraph/sourcegraph#2941]
#### Feature request description

Users who depend on Cloudflare Access would find it beneficial to use it for Sourcegraph instead of other SSO options.

More information about Cloudflare Accesss can be found here: 
- https://developers.cloudflare.com/access/
- https://developers.cloudflare.com/access/setting-up-access/securing-applications/

Sourcegraph auth documentation here: https://docs.sourcegraph.com/admin/auth

Customers:

- https://app.hubspot.com/contacts/2762526/company/623971957

**Comment by terinjokes** [comment]
Thanks @KattMingMing for opening this ticket. This looks like something that would be feasible for me to go ahead and attempt to add.

**Comment by sqs** [comment]
@terinjokes Excellent! Tentatively adding to the 3.3 milestone (shipping April 20) for our tracking purposes.

**Comment by sqs** [comment]
Moving to backlog. This is not going to ship in 3.3 because there is no PR yet. @terinjokes I will move it back into a release milestone if you want to send up a PR. Thanks!
