### ISSUE TITLE
Chrome plugin does not work on https://github.com/kubernetes/kubernetes

### ISSUE THREAD

**Issue by ankitpateledu** [sourcegraph/sourcegraph#2943]
#### Question description

I have installed chrome plugin and logged in using github credentials. 
I can visit https://github.com/GoesToEleven/GolangTraining and have plugin activated to help me understand the code, check function definition and references etc. 

How ever  it doesn not work with https://github.com/kubernetes/kubernetes
here i get "Repository not found To access this repository, contact the Sourcegraph admin." message

can you help ??

#### Additional context
![image](https://user-images.githubusercontent.com/25492444/54863154-5e5df500-4d02-11e9-9acf-f8097200f536.png)

![image](https://user-images.githubusercontent.com/25492444/54863151-3bcbdc00-4d02-11e9-96b0-5ff97a2acf7f.png)

**Comment by sqs** [comment]
Thank you for reporting this. We're tracking this in https://github.com/sourcegraph/sourcegraph/issues/2773#issuecomment-475858086 and #2933. Sorry for the issue!
