### ISSUE TITLE
Wildcard V2: `<Menu />`,` <MenuItem />` Manual migration, for `Reactstrap` Dropdown components 

### ISSUE THREAD

**Issue by gitstart-sourcegraph** [sourcegraph/sourcegraph#29436]
## Manual migration required to update our code to use the `<Menu />, <MenuItem />` Wildcard component.

See [Wildcard V2 - Planned work](https://docs.google.com/document/d/1NisbJPiadtt5jQw4vUUYJOr8dD6Urwn5V0mVq2wt6bE/edit#heading=h.g4cw92w3ouhw) for more context

Note: Before doing this, we should check if there is scope for a codemod to automate this migration. If so, the codemod should be implemented and ran before starting work on this issue.

### Ref
https://github.com/sourcegraph/sourcegraph/issues/27701

## Implementation
1. Migrate all usage of the `Dropdown` | `DropdownMenu` | `DropdownItem` | `DropdownToggle` Reactstrap components from this list:

let's only focus on components below
- SearchContextOwnerDropdown.tsx
- ExtensionRegistrySidenav.tsx
- MenuNavItem.tsx
- UserNavItem.tsx
- NavDropdown.tsx
- RepoHeader.tsx
- SearchNotebookPageHeaderActions.tsx
- ButtonDropdownCta

See this PR: https://github.com/sourcegraph/sourcegraph/pull/28979 for the implementation of these components

## Acceptance criteria
- [ ] All incorrect usage of the previous pattern has been updated to use the Wildcard component

**Comment by gitstart-sourcegraph** [comment]
Reactstrap's `ButtonDropdown` component as used in stories such as `MenuNavItem.story.tsx`, has a default opened state, however the `MenuButton`/ `Menu` component's opened state are non-controllable. could you confirm if we could remove the support for that prop (`openByDefault`) and would could trigger a click event on story to auto show dropdown content

**Comment by valerybugakov** [comment]
@umpox, could you take a look?

**Comment by umpox** [comment]
@gitstart-sourcegraph Looking into this.

I've also noticed that some of the `DropdownMenu` component usage might be better in the `Popover` component. e.g. the `FeedbackPrompt` shouldn't use `DropdownMenu`. I'll update this issue with a list of areas that need to be migrated specifically

**Comment by umpox** [comment]
@gitstart-sourcegraph Yes please remove support for the `openByDefault`

Please note. I have updated our issue for this ticket: https://github.com/sourcegraph/sourcegraph/issues/27701

Please can we only focus on those components that are mentioned in the updated ticket
