### ISSUE TITLE
How do queries against the mega repo perform against our OKR goals

### ISSUE THREAD

**Issue by jjeffwarner** [sourcegraph/sourcegraph#29454]
Create and monitor an initial set of queries against the mega repo to determine where there are problems areas that can be improved in our domain.

**Comment by ggilmore** [comment]
I believe our current dashboards at https://sourcegraph.com/-/debug/grafana/d/frontend/frontend?orgId=1 answer this question.

**Comment by jjeffwarner** [comment]
@ggilmore would you be up for creating a Loom video for this and sharing it out?
