### ISSUE TITLE
compute endpoint fails to match all capture group results

### ISSUE THREAD

**Issue by CristinaBirkel** [sourcegraph/sourcegraph#29459]
**Repro**:

1. On sourcegraph.com, open up the API console.
2. Run the following query:
```
query {
  compute(query:"patterntype:regexp background-color:#([0-9]) count:all repo:^github\\.com/sourcegraph/sourcegraph$@87f96d3608db4f6c535897b90f34256cc5b093c2") {
    ... on ComputeMatchContext{
        matches {
            value
	}
    }
  }
}
```
Note that this matches groups with values `4`, `3`, and `1`. 
3. Now modify that query slightly by changing the capture group from `[0-9]` to `[0-9a-z]` and re-run the query.

**Expected**:
The initial matches should all still be there, with any additions (in this case `f`) from the newly added `a-z`

**Actual**:
`3` is missing from the results

**Comment by rvantonder** [comment]
Yeah looks like a bug. I will look into this a bit later, hopefully by EOD tomorrow.

[console query](https://sourcegraph.com/api/console#%7B%22variables%22%3A%22%22%2C%22query%22%3A%22query%20%7B%5Cn%20%20compute(query%3A%5C%22patterntype%3Aregexp%20background-color%3A%23(%5B0-9a-z%5D)%20file%3Amerge-request.html%20count%3Aall%20repo%3A%5Egithub%5C%5C%5C%5C.com%2Fsourcegraph%2Fsourcegraph%24%4087f96d3608db4f6c535897b90f34256cc5b093c2%5C%22)%20%7B%5Cn%20%20%20%20...%20on%20ComputeMatchContext%7B%5Cn%20%20%20%20%20%20%20%20path%5Cn%20%20%20%20%20%20%20%20matches%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%5Ctenvironment%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20variable%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20value%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20value%5Cn%5Ct%7D%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%7D)

Search queries to reproduce:

[original query](https://sourcegraph.com/search?q=context:global+background-color:%23%28%5B0-9%5D%29+file:merge-request.html+count:all+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24%4087f96d3608db4f6c535897b90f34256cc5b093c2&patternType=regexp)

[buggy query](https://sourcegraph.com/search?q=context:global+background-color:%23%28%5B0-9a-z%5D%29+file:merge-request.html+count:all+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24%4087f96d3608db4f6c535897b90f34256cc5b093c2&patternType=regexp)
