### ISSUE TITLE
Identify and address missing alerts in the monitoring system

### ISSUE THREAD

**Issue by jjeffwarner** [sourcegraph/sourcegraph#29455]
The existing monitoring system does not have adequate alerts in place for a production system. This story would be a review of existing dashboards and monitors to do the following:
1. Identify missing alerts
2. Identify poor or outdated thresholds for alerts
3. Critical missing monitor or dashboards

Review the findings with the team and create appropriate stories for the work. This is likely a Q2 OKR opportunity.

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket,  please let us how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
