### ISSUE TITLE
Failed to resolve submodule repository name from clone url

### ISSUE THREAD

**Issue by markus-wa** [sourcegraph/sourcegraph#2947]
- **Sourcegraph version:** sourcegraph.com
- **Platform information:** Firefox

#### Steps to reproduce:

1. Visit https://sourcegraph.com/github.com/markus-wa/demoinfocs-golang

#### Expected behavior:
No error (like [here](https://sourcegraph.com/github.com/markus-wa/gobitread))

#### Actual behavior:
`Failed to resolve submodule repository name from clone url: https://gitlab.com/markus-wa/cs-demos`

[https://gitlab.com/markus-wa/cs-demos](https://gitlab.com/markus-wa/cs-demos) is available of course.
This might be a regression, iirc it used to work, not 100% sure though.

**Comment by KattMingMing** [comment]
This looks related to https://github.com/sourcegraph/sourcegraph/issues/2773

**Comment by dadlerj** [comment]
Reported by https://app.hubspot.com/contacts/2762526/company/693777177

**Comment by keegancsmith** [comment]
I'm unsure if we ever supported sub-modules. cc @sqs

**Comment by sqs** [comment]
We do support them by linking them in the file tree to the repo they refer to; see 2.11.0 changelog at https://sourcegraph.com/github.com/sourcegraph/sourcegraph@1c1d9ca000a7995c0872d2770f0a4e356bbf548e/-/blob/CHANGELOG.md#L464:7:

> Git submodules entries in the file tree now link to the submodule repository.

This was added for https://app.hubspot.com/contacts/2762526/company/578600789.

**Comment by markus-wa** [comment]
Any news yet? 🙂

**Comment by jjlin** [comment]
Having a similar issue on a private instance running 3.4.2. In my case, I don't necessarily expect Sourcegraph to be able to resolve the submodule, but the bigger issue for me is it aborts display of the entire directory where the submodule resides, leaving only the error message

> Error loading tree: failed to resolve submodule repository name from clone url: ssh://git@bitbucket-xyz.example.com:7999/project/repo.git

I'd prefer that the directory be displayed as usual, but with the submodule marked as unresolvable, perhaps with an error icon or a struck-through name.

**Comment by keegancsmith** [comment]
@markus-wa @jjlin apologies for the slow turn-around time. This is fixed on sourcegraph.com. We will be cutting a patch release for 3.4.3 including the fix.

**Comment by markus-wa** [comment]
@keegancsmith no worries, thank you very much for the fix!
