### ISSUE TITLE
Bitbucket Datacenter test environment

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#29475]
Test that Batch Changes is compatible with Bitbucket data center.

From the documentation, it should be the case. We should verify it and write it down in docs.

#### Impacted customers

https://github.com/sourcegraph/accounts/issues/3
https://github.com/sourcegraph/accounts/issues/6731
https://github.com/sourcegraph/accounts/issues/4914

#### Next steps

We need a bitbucket datacenter test instance linked to k8.

**Comment by bobheadxi** [comment]
Bumped to planned in response to @dan-mckean 's request on behalf of repo-management

**Comment by davejrt** [comment]
We'll be looking at deploying something from this repo
https://github.com/atlassian/data-center-helm-charts

**Comment by bobheadxi** [comment]
Copied from Slack:

It appears we can [run it on a trial for 30 days](https://www.atlassian.com/software/bitbucket/download/data-center) to get started, so we likely won't be blocked on getting started at least

There [does not appear to be a developer license that parallel's GitHub's app developer program](https://www.atlassian.com/licensing/purchase-licensing#manage-account), emphasis mine:

> Developer licenses are available to *existing commercial and academic self-managed license holders* (not available for cloud) who wish to deploy non-production installations for use in testing and development of the Atlassian software (e.g. version upgrades, customizations to the software, etc) that should not be done on a live production environment. 

So it seems likely that to keep it running we will incur some costs in licensing. Dave and I will look into this on Friday, when we plan on dedicating some time to spin up a test instance

**Comment by malomarrec** [comment]
Test report: 
https://github.com/sourcegraph/sourcegraph/issues/29915
