### ISSUE TITLE
search error containing `@`: parsing regex: "missing closing )"

### ISSUE THREAD

**Issue by CristinaBirkel** [sourcegraph/sourcegraph#29477]
**Repro:**

1. Run this query on `sourcegraph.com`:
```
query {
  compute(query:"patterntype:regexp TODO @([\\w]+) count:all repo:^github\\.com/sourcegraph/handbook") {
	... on ComputeMatchContext{
          matches {
              value
	  }
    }
  }
}
```

**Expected:**
Should return results. Note that if you change the `repo` to be `sourcegraph/sourcegraph` rather than `sourcegraph/handbook` it does return results.

**Actual:**
Error message:
```
"1 error occurred:\n\t* Repo search failed: bad request: error parsing regexp: missing closing ): `(TODO).*?(`\n\n"
```

**Comment by rvantonder** [comment]
This looks like a general search issue, possibly todo with how we use `@` in repo revisions. Note the pattern

`TODO @([\w]+)` is converted to something like `(TODO).*@([\w]+)` as per our usual regex "convention" so while I investigate, I suggest doing any of:

- `TODO\ @([\w]+)` (escape the space explicitly)

or

- `TODO\s@([\w]+)` (use `\s` for spaces)`

or 

- `/TODO @([\w]+)/` (also just interprets the space as space, not `.*`)

Note there are no results for this query, but here's an example https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/handbook+TODO%5Cs%40%28%5B%5Cw%5D%2B%29&patternType=regexp

**Comment by rvantonder** [comment]
Or, actually, just add `type:file` as another workaround.
