### ISSUE TITLE
Track events from onboarding emails

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#29483]
We currently do not track inbound events generated from our onboarding mechanisms. 

This means we are unable to determine the effectiveness of our email programs at creating engagement, improving retention and completing important actions such as adding code hosts and sync repositories. 

Onboarding emails contain UTM parameters that describe the campaign. We can use these parameters to generate EventLog events which can be tracked in both Amplitude and Looker. 

See this thread for more details:
https://sourcegraph.slack.com/archives/CN4FC7XT4/p1641475183006200

_Note: we are waiting on the correct UTM parameters to trigger on._

**Comment by rrhyne** [comment]
Batchers can safely ignore this. I suppose the word 'c a m p a i g n' triggered the notification.

**Comment by rrhyne** [comment]
A list of events and UTM parameters we can use to generate (and not generate event logs) is here: https://docs.google.com/spreadsheets/d/1U0HRC5WVz3tsP6z9pqDLG8igTMSf2-pQGhbRoVn_iu0/edit#gid=0

**Comment by philipp-spiess** [comment]
@rrhyne Do you have any advice on how I could get one of those marketing emails in my inbox so I can play around with it? I've been trying to play with the product but I only got it to send a monitoring test notification email and those have their links removed 😅 

Also what specifically does "EventLog" refer to? I only found the event log feature within the source graph product which seems to be an audit log. Is this what you refer to or is this a specific API for Amplitude/Looker?

**Comment by philipp-spiess** [comment]
Okay so an update here, we found the place in the code where we create events for specific UTM sources here: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/tracking/eventLogger.ts?L257-264&utm_source=VSCode-1.4.0#L248:1-255:6

Given that we don't have an exhaustive list of all UTM parameters (i.e looking for `code-monitoring-email` in the spreadsheet won't yield any results) it probably makes sense to add a generic event that includes all UTM parameters if a UTM source is set. Would that make sense?
