### ISSUE TITLE
VSCE: Add searchResultsInfoBar

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#29486]
Add a simple searchResultInfoBar for Save Search and Share features
Currently on web the searchResultInfoBar looks like:
![image](https://user-images.githubusercontent.com/68532117/149552530-3a52d108-7ccc-4583-8197-08d7830c7460.png)

**Comment by abeatrix** [comment]
Implemented with save search and share features
![image](https://user-images.githubusercontent.com/68532117/149552238-fa35e6e7-5c71-46c6-b881-c896b482e326.png)

**Comment by jjinnii** [comment]
@abeatrix Will be adding the x results found in y repositories in z seconds information? (As well as the "Some results excluded" dropdown? I don't think it's super important but curious whether it was too hard to implement within VS Code

**Comment by abeatrix** [comment]
It's not! I just added it! 
<img width="2518" alt="Screen Shot 2022-01-18 at 9 18 11 AM" src="https://user-images.githubusercontent.com/68532117/149986462-1a59bf05-ebdc-42f7-8db2-4a3456dcca6f.png">
