### ISSUE TITLE
`sg` and enterprise

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#29501]
Right now/soon (as of https://github.com/sourcegraph/sourcegraph/pull/29158), `sg` imports and uses a number of `enterprise` packages, namely `enterprise/dev/ci/images` and `enterprise/dev/ci/internal/ci`. However, `sg` is in the non-enterprise `dev/sg`.

This is needed to add:

- `sg ci` - preview and interact with continuous integration pipelines 
- ~`sg ops` - update images in kubernetes manifests, etc (https://github.com/sourcegraph/sourcegraph/pull/29158)~ this didn't end up importing and enterprise package: https://github.com/sourcegraph/sourcegraph/pull/29158/files

Possible solutions:

- build enterprise commands separately in `enterprise/dev/sg` as a separate distribution of `sg`
- move `sg` entirely to `enterprise/dev/sg`

**Comment by bobheadxi** [comment]
cc @malomarrec since I recall you've worked on licensing for other parts of sourcegraph - do you have any thoughts/recommendations here?

**Comment by malomarrec** [comment]
Replied on slack :)
For the record, we have this page https://handbook.sourcegraph.com/departments/product-engineering/engineering/process/licenses#open-source-philosophy about open source philosophy, that lays out broad principles.

**Comment by bobheadxi** [comment]
It looks like we don't actually _import_ any enterprise code in sg, but we do _run_ a lot of enterprise code:

https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+f:%5Edev/sg+enterprise+count:all&patternType=literal

It turned out https://github.com/sourcegraph/sourcegraph/pull/29158 did not end up importing the enterprise `images` package.

I think as long as we keep this delineation we should be in the clear! We can selectively extract non-critical components that we do want to import in `sg`, such as https://github.com/sourcegraph/sourcegraph/pull/30935, into OSS packages
