### ISSUE TITLE
insights: panic if the insights worker queue has records for an insight series that no longer exists

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#29502]
When the insights queue worker picks up work to perform searches, [it first retrieves the insight metadata](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/enterprise/internal/insights/background/queryrunner/work_handler.go?L90&utm_product_name=GoLand&utm_product_version=GoLand#L129:26). In this case, if the serise no longer exists in the `insight_series` table, this will return nil and cause a panic.

```
[enterprise-worker] panic: runtime error: invalid memory address or nil pointer dereference
[enterprise-worker] [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x3743a0f]
[enterprise-worker] goroutine 1118 [running]:
[enterprise-worker] github.com/sourcegraph/sourcegraph/enterprise/internal/insights/background/queryrunner.(*workHandler).Handle(0xc001fcce40, {0x41babf0, 0xc00199f620}, {0x41724e0, 0xc000abbbc0})
```

**Comment by Joelkw** [comment]
Known logging issue but minimal customer end impact. Most likely due to our messing with the database on dogfood.

**Comment by coury-clark** [comment]
Just noting a quick observation:

We just had two series that were in a perpetual fail-retry loop in the backfill process ([logs](https://sourcegraph.grafana.net/explore?orgId=1&left=%5B%221643119099000%22,%221643122699000%22,%22grafanacloud-sourcegraph-logs%22,%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22dogfood-k8s%5C%22,%20app%3D%5C%22worker%5C%22%7D%20%7C%3D%20%5C%2224AAEtPcSHtjdpmLU4h3XUvhzIm%5C%22%22%7D%5D)). Simultaneously we had the queue worker in a panic loop ([logs](https://sourcegraph.grafana.net/explore?orgId=1&left=%5B%221643119099000%22,%221643122699000%22,%22grafanacloud-sourcegraph-logs%22,%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22dogfood-k8s%5C%22,%20app%3D%5C%22worker%5C%22%7D%20%7C%3D%20%5C%22panic%5C%22%22%7D%5D)).

I cleaned the queue out (for unrelated reasons) except these two relevant series, which stopped the panic loop ([logs](https://sourcegraph.grafana.net/explore?orgId=1&left=%5B%221643124690000%22,%221643126430000%22,%22grafanacloud-sourcegraph-logs%22,%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22dogfood-k8s%5C%22,%20app%3D%5C%22worker%5C%22%7D%20%7C%3D%20%5C%22panic%5C%22%22%7D%5D))` and allowed the backfiller to start up successfully ([logs](https://sourcegraph.grafana.net/explore?orgId=1&left=%5B%221643125530000%22,%221643125830000%22,%22grafanacloud-sourcegraph-logs%22,%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22dogfood-k8s%5C%22,%20app%3D%5C%22worker%5C%22%7D%20%7C%3D%20%5C%22historical%5C%22%22%7D%5D)).

This implies there is a relationship between the execution of the backfiller and the queue worker. This changes the impact of this issue since it effectively preempts *all* series from backfilling, instead of just the series causing the panic.
