### ISSUE TITLE
flaky CI (management-console already exists and is not an object file)

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#2950]
https://buildkite.com/sourcegraph/sourcegraph/builds/29941#3dc2beea-13fe-4fb1-975e-110c6a824b11 had a failure unrelated to my commit:

```
[2019-03-23T11:53:04Z] go install github.com/sourcegraph/sourcegraph/cmd/management-console: build output "/buildkite/builds/buildkite-agent-79c58b864f-t6ksv-1/sourcegraph/.golang/sourcegraph/bin/management-console" already exists and is not an object file
```

**Comment by sqs** [comment]
Rerunning that build step worked. I am no longer blocked.

@chrismwendt 	You have been fixing a lot of flaky CI things, so I'm assigning to you in the hopes you know the best solution (or who to assign this to).

**Comment by chrismwendt** [comment]
I've never seen this before. It looks like the file was overwritten more recently by another build, so the state is gone, but the next time this happens, let's try running:

```
$ kubectl exec -n buildkite -ti buildkite-agent-79c58b864f-t6ksv /bin/bash

# file /buildkite/builds/buildkite-agent-79c58b864f-t6ksv-1/sourcegraph/.golang/sourcegraph/bin/management-console
/buildkite/builds/buildkite-agent-79c58b864f-t6ksv-1/sourcegraph/.golang/sourcegraph/bin/management-console: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/l, not stripped

# ls -lh /buildkite/builds/buildkite-agent-79c58b864f-t6ksv-1/sourcegraph/.golang/sourcegraph/bin/management-console
-rwxr-xr-x 1 root root 18M Mar 23 16:13 /buildkite/builds/buildkite-agent-79c58b864f-t6ksv-1/sourcegraph/.golang/sourcegraph/bin/management-console
```

I skimmed over our pipeline steps looking for other steps that run `go install`, thinking there might be a race condition, but I didn't see anything suspicious.

**Comment by sqs** [comment]
hasn't been seen since, closing
