### ISSUE TITLE
Favicon has fuzzy edges in Firefox running on macOS

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/sourcegraph#29514]
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:** macOS 12, Firefox 95.0.2

#### Steps to reproduce:

Open any page on sourcegraph.com.

<img width="131" alt="screenshot of favicon" src="https://user-images.githubusercontent.com/93103176/148736433-dcf7e104-2223-41da-91ff-dbe7428a2aee.png">

#### Expected behavior:

The favicon should look sharp/crisp, similar to how GitHub's favicon (shown on the right) looks crisp.

#### Actual behavior:

The edges of the capsules look fuzzy, especially for the sky blue capsule. This looks particularly odd next to other favicons which are often geometrically more complex.

I'm not sure if this is the reason for the difference, but I noticed that the Sourcegraph favicon is a PNG whereas GitHub's favicon is an SVG.

**Comment by umpox** [comment]
We should use an SVG for the favicon icon.

I believe we currently use `enterprise/ui/assets/img/favicon.png` or `ui/assets/img/favicon.png`

We should instead use `enterprise/ui/assets/img/sourcegraph-mark.svg` or `ui/assets/img/sourcegraph-mark.svg`.

cc: @gitstart-sourcegraph
