### ISSUE TITLE
Helm chart: use service account credentials for publishing releases

### ISSUE THREAD

**Issue by caugustus-sourcegraph** [sourcegraph/sourcegraph#29546]
The helm publish github workflow in https://github.com/sourcegraph/deploy-sourcegraph-helm is using a token generated from a personal user account. A new token should be generated using org-level credentials and used in place of CR_PUBLISH_TOKEN.

**Comment by michaellzc** [comment]
`CR_PUBLISH_TOKEN` has been replaced with an personal access token of @sourcegraph-bot (credentials is in 1password)

Side notes, the right way would be using GitHub App to authenticate. That's not something our team should work on but DevX or Security.
