### ISSUE TITLE
insights: add all repos checkbox to detect and track page

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#29551]
For global capture groups, we will need the ability to select "run my insight over all repos".

<img width="730" alt="image" src="https://user-images.githubusercontent.com/5090588/148857117-18b25a51-5145-4b4c-a1d3-975f22fe173b.png">

Backend issue: https://github.com/sourcegraph/sourcegraph/issues/27230

**Comment by felixfbecker** [comment]
@sourcegraph/code-insights-frontend who will work on this this iteration and what's your size estimate? 🙂

**Comment by vovakulikov** [comment]
@felixfbecker the estimation of it is 2 points | units (seems like a straightforward ticket) @unclejustin is the primary assignee for this ticket.
