### ISSUE TITLE
Definition window: hovering shows the horizontal scrollbar on the top of the content

### ISSUE THREAD

**Issue by viktorkuznietsov1986** [sourcegraph/sourcegraph#2956]
- **Sourcegraph version: v19.3.22.1110** 
- **Platform information: Mac OS Mojave 10.14.3, Google Chrome 73.0.3683.86** 

#### Steps to reproduce:

1. Navigate to .py file within github repo (you can use https://github.com/viktorkuznietsov1986/human_protein_atlas/blob/master/models/inceptionv3.py)
2. Click on method declaration.
3. The definition window appears.
4. Click on method name in definition window.

#### Expected behavior:
If the content needs to be scrolled, the scrollbar should appear outside of the content area.

#### Actual behavior:
The scrollbar appears inside of the content area and hides the test.

**Comment by chrismwendt** [comment]
Is this what you see?

![image](https://user-images.githubusercontent.com/1387653/55185880-86aa8100-5152-11e9-8036-c528992827dc.png)

**Comment by viktorkuznietsov1986** [comment]
Yes.

Regards,
Viktor Kuznietsov

**Comment by chrismwendt** [comment]
I don't see the scrollbar getting stuck on Firefox. There might be a CSS property we can set to prevent it from getting stuck in Chrome.

**Comment by felixfbecker** [comment]
Hi @viktorkuznietsov1986, whether scroll bars are shown inside or outside the content area are controlled by your macOS system settings:

<img width="780" alt="Screenshot 2019-03-30 at 12 44 09" src="https://user-images.githubusercontent.com/10532611/55275677-bc35a280-52e9-11e9-96ed-40edcc90f375.png">

If it is set to "When scrolling", scroll bars will always be inside the content area, when set to "Always", they will always be outside (not overlap with the content).

It is unfortunately not possible to control for us without completely replacing the native scrollbars with custom ones.

Does this solve your issue?

**Comment by viktorkuznietsov1986** [comment]
Hi,

Thanks. Yes.

Regards,
Viktor Kuznietsov

**Comment by felixfbecker** [comment]
Awesome.
