### ISSUE TITLE
VSCE: Add Save Search Feature

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#29574]
As discussed with @jjinnii , logged in users should have access to the saved search feature like on dot com.

**Comment by abeatrix** [comment]
@jjinnii Regarding this feature, users are able to add searches to save search within the extension currently but has no way to retrieve them within the extension. On dotcom, they will have to go to their own user setting to find their saved search. As discussed, should we display the saved search somewhere within the extension for easy access?

**Comment by jjinnii** [comment]
@abeatrix By retrieve, we mean modify/delete saved searches right? (not too familiar with this feature sorry). Because even in sourcegraph.com, the only place to access a saved search is within ser settings I believe?

**Comment by abeatrix** [comment]
Implemented as discussed in https://github.com/sourcegraph/sourcegraph/issues/29837#issuecomment-1016929102
