### ISSUE TITLE
SOC2- GN-86 How are events requiring remediation are logged and tracked

### ISSUE THREAD

**Issue by JenRed777** [sourcegraph/sourcegraph#29579]
Due: February 1, 2022
Sourcegraph uses a system capacity and performance monitoring tool that alerts the Security team on a real-time basis. Events requiring remediation are logged and tracked through completion.

Describe to the auditor Prom/Grafana; Then show alert channel for all alerts; p1 alerts through opsgenie; finally show incidents.io for remediation

**Comment by filiphaftek** [comment]
# Description
[Sourcegraph](https://sourcegraph.com/) main monitoring and alerting tools are Prometheus and Google Cloud monitoring.

Sourcegraph alert types:
- [default application alerts](https://docs.sourcegraph.com/admin/observability/alert_solutions)
- [custom Cloud alerts](https://k8s.sgdev.org/github.com/sourcegraph/deploy-sourcegraph-cloud/-/blob/base/prometheus/prometheus.ConfigMap.yaml)
- [GCP alerts](https://k8s.sgdev.org/github.com/sourcegraph/infrastructure/-/blob/cloud/alerting.tf)

When alert is being fired, it notifies channels:
- [channels configuration](https://k8s.sgdev.org/github.com/sourcegraph/deploy-sourcegraph-cloud/-/blob/base/frontend/non-sensitive-site-config.ConfigMap.yaml?L75:8)
- Slack channels: `#opsgenie`, `#bots-production`
- direct notification via Opsgenie application

Incidents tracking and remediation:
- [handbook](https://handbook.sourcegraph.com/departments/product-engineering/engineering/process/incidents#incident-roles-and-responsibilities)
- [incident.io](https://app.incident.io/follow-ups)

**Comment by filiphaftek** [comment]
@JenRed777 I described all in the comment, please let me know if we need to update the handbook with such informations. Thank you.
