### ISSUE TITLE
1st file in GitHub PR does not have Sourcegraph actions/hovers initially

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#2958]
Repro:

1. Go to https://github.com/sourcegraph/go-diff/pull/31/files#diff-1d80fd3313706b7349ac29bdc684e129R513
1. Try to hover over things in the first file (`diff/diff_test.go`); nothing happens. Also notice that there is no **View file diff** button on the first file's header.
1. Scroll down all the way on the page
1. Scroll back up
1. Now hovers work on the first file and the **View file diff** button appears

I am not able to repro this on other PRs such as https://github.com/gorilla/mux/pull/463/files. I don't know why. But this is an important bug to fix because this we intend to use this go-diff PR as a demo at dotGo tomorrow.

**Comment by felixfbecker** [comment]
Confirmed that this is not reproducible with #2909 

![image](https://user-images.githubusercontent.com/10532611/54934450-d1dc4e00-4f1e-11e9-9a15-1c30c3d434a8.png)
