### ISSUE TITLE
SOC2 - GN-100 Sourcegraph maintains separate development, test, and production environments.

### ISSUE THREAD

**Issue by JenRed777** [sourcegraph/sourcegraph#29595]
Due: February 28, 2022

Sourcegraph maintains separate development, test, and production environments.

**Comment by daxmc99** [comment]
@dcomas Is there a requirement for automation here?

**Comment by daxmc99** [comment]
Clarification: Pre-prod & prod are enough for environments.

What we need to complete this are: 
- Demonstrate that there is an environment before production that all changes must pass through

**Comment by JenRed777** [comment]
For Managed Instances:
The newly created release or patch is tested on dogfood.sourcegraph.com as well as a newly created managed instance before being rolled out to the production managed instances.

**Comment by daxmc99** [comment]
Issue that satisfies this for cloud: https://github.com/sourcegraph/sourcegraph/issues/28082#issuecomment-1057156130

**Comment by danieldides** [comment]
Document available for review: https://docs.google.com/document/d/1tXGlVyfE_p9SJK-o8zM1msbfihB9gLjv4siDwWNpntc/edit?usp=sharing

Many aspects of this document are not necessarily true yet. Things that need a citation still or demand work I highlighted in red.

To be able to close this ticket, the following need to be accomplished:
- [ ] merge `preprod` into `release`
- [ ] modify renovate (or `sg ops update-images`) to create PRs against `preprod` first
- [ ] define SLAs for how long it should take changes to get from dev machine to production (via preprod)
- [ ] create some sort of cron-job to automatically create the PRs to merge `preprod` into `release`

There's also a pile of [Handbook changes](https://github.com/sourcegraph/handbook/pull/2654) that need to be merged in once the aforementioned work is true. These should more or less document the ideal state.
