### ISSUE TITLE
Irregular GraphQL behavior after repo path changes on codehost

### ISSUE THREAD

**Issue by DaedalusG** [sourcegraph/sourcegraph#29597]
# Irregular GraphQL behavior after repo path changes on codehost
- **Sourcegraph version:** v3.33 to v3.35.1
- **Platform information:** 

#### Steps to reproduce:
1. Clone a repo from your codehost
2. Change that repos path on the codehost (tested in github and gitlab)

#### Expected behavior:
Sourcegraph should recognize that the repos path has changed and update the repo accordingly. Or report that no such repo exists any longer and then clone the new repo path (assuming the codehost config will pick it up), and remove the old path from search functionality. 

#### Actual behavior:
[Various features](https://github.com/sourcegraph/sourcegraph/issues/28509), in this issue specifically graphQL queries seem to fail with results for the old repo path causing issues. 

#### Exploration / Evidence

Consider the following query from the graphQL console --

```graphql
query ($query: String!) {
   search(query: $query, version: V2) {
      results {
         results {
            __typename
            ... on FileMatch {
                  ...FileMatchFields
                  }
            ... on Repository {
               ...RepositoryFields
            }
         }
      }
   }
}

fragment FileMatchFields on FileMatch {
   repository {
      name
      url
   }
   file {
    content
  }
}

fragment RepositoryFields on Repository {
   name
   url
   externalURLs {
      serviceType
      url
   }
   label {
      html
   }
}
```
```graphql
{
  "query": "count:10000 (file:README\\.md or file:package\\.json)"
}
```
This is a broad query that isn't specific to a particular repo and should return some results. 

Instead the following error is observed --
```graphql
{
  "errors": [
    {
      "message": "repository does not exist: github.com/sourcegraph/deploy-sourcegraph-dot-com",
      "path": [
        "search",
        "results",
        "results",
        395,
        "file",
        "content"
      ]
    },
```
**Why is this strange?** The repo `github.com/sourcegraph/deploy-sourcegraph-dot-com` no longer exists as the repo in question has changed its path to `sourcegraph/deploy-sourcegraph-cloud`, investigating further shelling into the gitserver it can be observed that the path there is correct and that no repo exists with path `sourcegraph/deploy-sourcegraph-dot-com`

_Note: The same query has been observed to fail in a gitlab instance whose **group** assignment has changed_

With a little further exploration on Gitlab, a test repos path was changed numerous times on the codehost in the course of an hour, and the same graphQL query returned numerous results, with the old paths

```graphql
{
  "data": {
    "search": {
      "results": {
        "results": [
          {
            "__typename": "FileMatch",
            "repository": {
              "name": "gitlab.com/change-again-test/learn-gitlab-ultimate-trial",
              "url": "/gitlab.com/change-again-test/learn-gitlab-ultimate-trial"
            },
            "file": {
              "content": "# Learn Gitlab\n\nWe prepared tutorials to help you set up GitLab in a way to support your complete software development life cycle. Each tutorial is contained in an issue, and features a task to complete.\n\nView the tutorials by clicking on [Issues > Boards](../../boards) in the left sidebar. Complete each tutorial in turn by working through the Open list. When you've completed a tutorial, drag its issue card to the Closed list and move on to the next.\n\n<a href=\"../../boards\"><img src=\"/issue-board.png\" width=\"700\" /></a>\n\n# Don’t need this project anymore?\n\nYou can delete it by going to [Settings > General](../../../edit), then expand the “Advanced” section at the bottom of the page and either archive or remove the project.\n"
            }
          },
          {
            "__typename": "FileMatch",
            "repository": {
              "name": "gitlab.com/change-group/learn-gitlab-ultimate-trial",
              "url": "/gitlab.com/change-group/learn-gitlab-ultimate-trial"
            },
            "file": {
              "content": "# Learn Gitlab\n\nWe prepared tutorials to help you set up GitLab in a way to support your complete software development life cycle. Each tutorial is contained in an issue, and features a task to complete.\n\nView the tutorials by clicking on [Issues > Boards](../../boards) in the left sidebar. Complete each tutorial in turn by working through the Open list. When you've completed a tutorial, drag its issue card to the Closed list and move on to the next.\n\n<a href=\"../../boards\"><img src=\"/issue-board.png\" width=\"700\" /></a>\n\n# Don’t need this project anymore?\n\nYou can delete it by going to [Settings > General](../../../edit), then expand the “Advanced” section at the bottom of the page and either archive or remove the project.\n"
            }
          },
          {
            "__typename": "FileMatch",
            "repository": {
              "name": "gitlab.com/cs-sourcegraph/learn-gitlab-ultimate-trial",
              "url": "/gitlab.com/cs-sourcegraph/learn-gitlab-ultimate-trial"
            },
            "file": {
              "content": "# Learn Gitlab\n\nWe prepared tutorials to help you set up GitLab in a way to support your complete software development life cycle. Each tutorial is contained in an issue, and features a task to complete.\n\nView the tutorials by clicking on [Issues > Boards](../../boards) in the left sidebar. Complete each tutorial in turn by working through the Open list. When you've completed a tutorial, drag its issue card to the Closed list and move on to the next.\n\n<a href=\"../../boards\"><img src=\"/issue-board.png\" width=\"700\" /></a>\n\n# Don’t need this project anymore?\n\nYou can delete it by going to [Settings > General](../../../edit), then expand the “Advanced” section at the bottom of the page and either archive or remove the project.\n"
            }
          }
        ]
      }
    }
  }
}
```
Note the changing second **group** part of the path `cs-sourcegraph` -> `change-group` -> `change-again-test`

This query isn't currently failing however I suspect after the instance has run for some time, and garbage cleanup has occurred in the repo-updater, it will fail with errors for the absence of the previous two paths

I'll update this issue if this is confirmed.

**Comment by DaedalusG** [comment]
More explicitly linking another issue that I believe may be related to how codehost name changes are acting stangely
https://github.com/sourcegraph/sourcegraph/issues/28509

**Comment by keegancsmith** [comment]
> `repository does not exist: github.com/sourcegraph/deploy-sourcegraph-dot-com`

@DaedalusG Is this on sourcegraph.com? We could follow the trail and work it out via a trace and inspecting the db/etc.

**Comment by DaedalusG** [comment]
@keegancsmith this is actually on the CS teams k8s instance, here's a [link](https://cse-k8s.sgdev.org/api/console#%7B%22query%22%3A%22query%20(%24query%3A%20String!)%20%7B%5Cn%20%20%20search(query%3A%20%24query%2C%20version%3A%20V2)%20%7B%5Cn%20%20%20%20%20%20results%20%7B%5Cn%20%20%20%20%20%20%20%20%20results%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20__typename%5Cn%20%20%20%20%20%20%20%20%20%20%20%20...%20on%20FileMatch%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20...FileMatchFields%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20...%20on%20Repository%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20...RepositoryFields%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%7D%5Cn%7D%5Cn%5Cnfragment%20FileMatchFields%20on%20FileMatch%20%7B%5Cn%20%20%20repository%20%7B%5Cn%20%20%20%20%20%20name%5Cn%20%20%20%20%20%20url%5Cn%20%20%20%7D%5Cn%20%20%20file%20%7B%5Cn%20%20%20%20content%5Cn%20%20%7D%5Cn%7D%5Cn%5Cnfragment%20RepositoryFields%20on%20Repository%20%7B%5Cn%20%20%20name%5Cn%20%20%20url%5Cn%20%20%20externalURLs%20%7B%5Cn%20%20%20%20%20%20serviceType%5Cn%20%20%20%20%20%20url%5Cn%20%20%20%7D%5Cn%20%20%20label%20%7B%5Cn%20%20%20%20%20%20html%5Cn%20%20%20%7D%5Cn%7D%22%2C%22variables%22%3A%22%7B%5Cn%20%20%5C%22query%5C%22%3A%20%5C%22count%3A10000%20(file%3AREADME%5C%5C%5C%5C.md%20or%20file%3Apackage%5C%5C%5C%5C.json)%5C%22%5Cn%7D%22%7D) to the failing query. 

I did grab a trace for this, but, its huge and I've had trouble uploading it.

**Comment by keegancsmith** [comment]
How do I get access to this instance? I think I need to dive in given you say there is no repo table entry nor gitserver clone. Out of interest, any mention of it in the site configuration? :)

**Comment by DaedalusG** [comment]
@keegancsmith I've sent over some credentials for our instance. Going to feel silly if this turns out to be something simple I missed 😅

**Comment by DaedalusG** [comment]
Checking myself again 😅 

Heres the gitserver insides -- 
```bash
/data/repos/github.com/sourcegraph # pwd
/data/repos/github.com/sourcegraph
/data/repos/github.com/sourcegraph # ls -al | grep deploy-sourcegraph
drwxrwsr-x    3 root     sourcegr      4096 Dec  7 15:19 deploy-sourcegraph
drwxrwsr-x    3 root     sourcegr      4096 Nov 30 00:19 deploy-sourcegraph-aws
drwxrwsr-x    3 root     sourcegr      4096 Jan  7 14:42 deploy-sourcegraph-big-data
drwxr-sr-x    3 root     sourcegr      4096 Dec 16 00:01 deploy-sourcegraph-cloud
drwxrwsr-x    3 root     sourcegr      4096 Dec 12 21:52 deploy-sourcegraph-core
drwxr-sr-x    3 root     sourcegr      4096 Dec 23 03:19 deploy-sourcegraph-cse-k8s
drwxrwsr-x    3 root     sourcegr      4096 Jan  4 23:12 deploy-sourcegraph-dhall
drwxrwsr-x    3 root     sourcegr      4096 Dec  7 03:11 deploy-sourcegraph-dhall-archived
drwxrwsr-x    3 root     sourcegr      4096 Dec 10 02:05 deploy-sourcegraph-digitalocean
drwxrwsr-x    3 root     sourcegr      4096 Dec 21 03:31 deploy-sourcegraph-docker
drwxrwsr-x    3 root     sourcegr      4096 Jan 12 07:24 deploy-sourcegraph-dogfood-k8s
drwxrwsr-x    3 root     sourcegr      4096 Jan  4 17:42 deploy-sourcegraph-dogfood-k8s-archived
drwxrwsr-x    3 root     sourcegr      4096 Oct 24 00:56 deploy-sourcegraph-dogfood-server
drwxrwsr-x    3 root     sourcegr      4096 Jan  8 10:26 deploy-sourcegraph-executors
drwxrwsr-x    3 root     sourcegr      4096 Jan  3 06:52 deploy-sourcegraph-grail-replica
drwxr-sr-x    3 root     sourcegr      4096 Dec  3 19:10 deploy-sourcegraph-helm
drwxrwsr-x    3 root     sourcegr      4096 Dec 26 12:41 deploy-sourcegraph-lyft
drwxrwsr-x    3 root     sourcegr      4096 Nov 22 08:01 deploy-sourcegraph-lyft-replica
drwxrwsr-x    3 root     sourcegr      4096 Jan  1 22:12 deploy-sourcegraph-managed
drwxrwsr-x    3 root     sourcegr      4096 Jan  4 12:29 deploy-sourcegraph-qc-test
drwxr-sr-x    3 root     sourcegr      4096 Nov 30 18:28 deploy-sourcegraph-twit-test
drwxrwsr-x    3 root     sourcegr      4096 Jan 10 10:36 deploy-sourcegraph-uber
drwxrwsr-x    3 root     sourcegr      4096 Jan 12 06:41 deploy-sourcegraph-uber-replica
drwxrwsr-x    3 root     sourcegr      4096 Dec 22 05:47 deploy-sourcegraph-updater-test
```

**Comment by keegancsmith** [comment]
We are not deleting deploy-sourcegraph-dot-com index from the disk on zoekt-indexserver. I filed <https://github.com/sourcegraph/sourcegraph/issues/29685> to follow up with a fix. Hopefully resolving that fixes this as well.

While debugging I also came across another issue which I resolved. The zoekt disk was full, so it can't make any progress. I removed the tempdir and trash and it recovered a lot of space (I forgot to check which dir was the bad one). Unfortunetly this didn't resolve this issue.

    indexed-search-0:/data/index# ls | grep dot-com
    github.com%2Fsourcegraph%2Fdeploy-sourcegraph-dot-com_v16.00000.zoekt
    indexed-search-0:/data/index# df -h .
    Filesystem                Size      Used Available Use% Mounted on
    /dev/sdc                195.8G    195.8G         0 100% /data
    indexed-search-0:/data/index# rm -rf .trash/ .indexserver.tmp/
    indexed-search-0:/data/index# df -h .
    Filesystem                Size      Used Available Use% Mounted on
    /dev/sdc                195.8G      6.2G    189.6G   3% /data

Some extra info. The last reference in the tsv logs to deploy-sourcegraph was on the `Wed Dec 15 09:32:37 PM SAST 2021` for an upsert. The other references around remove/restor where in oct so unrelated. I need to follow up by grepping for the repository ID.

    zoekt-builder-shard-log.tsv: ... snip lots of entries about upsert
    zoekt-builder-shard-log.tsv:1639596757  upsert  github.com%2Fsourcegraph%2Fdeploy-sourcegraph-dot-com_v16.00000.zoekt   2817305 github.com/sourcegraph/deploy-sourcegraph-dot-com
    zoekt-indexserver-shard-log.tsv:1634919655      remove  github.com%2Fsourcegraph%2Fdeploy-sourcegraph-dot-com_v16.00000.zoekt   0       github.com/sourcegraph/deploy-sourcegraph-dot-com       200
    zoekt-indexserver-shard-log.tsv:1634923095      remove  github.com%2Fsourcegraph%2Fdeploy-sourcegraph-dot-com_v16.00000.zoekt   0       github.com/sourcegraph/deploy-sourcegraph-dot-com       200
    zoekt-indexserver-shard-log.tsv:1634923328      restore github.com%2Fsourcegraph%2Fdeploy-sourcegraph-dot-com_v16.00000.zoekt   3113525 github.com/sourcegraph/deploy-sourcegraph-dot-com       200

**Comment by DaedalusG** [comment]
Little follow up regarding the gitlab testing --
```bash
warrengifford@Warrens-MacBook-Pro index % pwd
/Users/warrengifford/.sourcegraph/data/zoekt/index
warrengifford@Warrens-MacBook-Pro index % ls
gitlab.com%2Fchange-again-test%2Flearn-gitlab-ultimate-trial_v16.00000.zoekt
gitlab.com%2Fchange-group%2Fkali-arm_v16.00000.zoekt
gitlab.com%2Fchange-group%2Flearn-gitlab-ultimate-trial_v16.00000.zoekt
gitlab.com%2Fcs-sourcegraph%2Fcs-testing_v16.00000.zoekt
gitlab.com%2Fcs-sourcegraph%2Fiterm2_v16.00000.zoekt
gitlab.com%2Fcs-sourcegraph%2Fjekyll_v16.00000.zoekt
gitlab.com%2Fcs-sourcegraph%2Flearn-gitlab-ultimate-trial_v16.00000.zoekt
zoekt-builder-shard-log.tsv
```
*Here we can observe in the sourcegraph server test I'm running locally the old indexes are sticking around after a repo is renamed

**Comment by keegancsmith** [comment]
This is about to land in main https://github.com/sourcegraph/sourcegraph/pull/29855. Once it does, I would regard this issue as solved. Would be great to confirm on your test cluster once it has this commit. @DaedalusG gonna assign to you to follow up if you don't mind?

**Comment by keegancsmith** [comment]
@DaedalusG I just tried the GraphQL query out that you linked on your instance. It is working, so gonna close out :)

**Comment by DaedalusG** [comment]
Confirmed fix on my single container instance as well
```
warrengifford@Warrens-MacBook-Pro ~ % cd /Users/warrengifford/.sourcegraph/data/zoekt/index
warrengifford@Warrens-MacBook-Pro index % ls -al
total 190504
drwxr-xr-x  10 warrengifford  staff       320 Jan 13 11:32 .
drwxr-xr-x   3 warrengifford  staff        96 Jan 11 10:59 ..
drwxr-xr-x   5 warrengifford  staff       160 Feb  1 15:56 .indexserver.tmp
drwxr-xr-x   2 warrengifford  staff        64 Jan 11 10:59 .trash
-rw-r--r--   1 warrengifford  staff     10594 Jan 11 11:17 gitlab.com%2Fchange-again-test%2Flearn-gitlab-ultimate-trial_v16.00000.zoekt
-rw-r--r--   1 warrengifford  staff  24609942 Jan 11 11:00 gitlab.com%2Fchange-group%2Fkali-arm_v16.00000.zoekt
-rw-r--r--   1 warrengifford  staff      1311 Jan 11 11:00 gitlab.com%2Fcs-sourcegraph%2Fcs-testing_v16.00000.zoekt
-rw-r--r--   1 warrengifford  staff  72721706 Jan 11 11:02 gitlab.com%2Fcs-sourcegraph%2Fiterm2_v16.00000.zoekt
-rw-r--r--   1 warrengifford  staff    176605 Jan 11 11:00 gitlab.com%2Fcs-sourcegraph%2Fjekyll_v16.00000.zoekt
-rw-r--r--   1 warrengifford  staff       912 Jan 11 11:17 zoekt-builder-shard-log.tsv
```
Note there's only one instance of `learn-gitlab-ultimate-trial`
