### ISSUE TITLE
SOC2 - GN-122 How do we address autoscaling to guarantee headroom

### ISSUE THREAD

**Issue by JenRed777** [sourcegraph/sourcegraph#29590]
Due: February 15, 2022

Sourcegraph continuously assesses system requirements and capacity needs to plan for system changes required to support service commitments.

Notes: Autoscaling with guaranteed headroom; if you onboard a new big client, will that cause a disruption? How are we planning to avoid this?

**Comment by JenRed777** [comment]
For Managed Instances: 
The Delivery team is notified when system capacity has been reached. If we need to scale the system there is downtime that will occur. The downtime is similar to what is seen during a version upgrade.

**Comment by danieldides** [comment]
Ready for review: https://docs.google.com/document/d/1fy-tD637Lmh6y9uX8DD8Ud1I8FpoiyBwjlsVdteopCg

**Comment by daxmc99** [comment]
@danieldides Might be a good idea to add GCP Quota alerts as part of this?

**Comment by danieldides** [comment]
Updated the document with a small blurb and screenshot of quotas.

**Comment by JenRed777** [comment]
LGTM
