### ISSUE TITLE
SOC2 - GN - 81 Production replicated across AZ

### ISSUE THREAD

**Issue by JenRed777** [sourcegraph/sourcegraph#29593]
Due: February 28, 2022

Production resources are replicated across Availability Zones to help ensure failover capabilities.

Notes:  Need evidence for managed,  cloud and on-prem. On-prem just needs to demonstrate that the product can be deployed multi-AZ

**Comment by JenRed777** [comment]
For Delivery:
This is currently not possible. How should this be described to the Auditors?

**Comment by daxmc99** [comment]
Google drive doc describing process for cloud: https://docs.google.com/document/d/1hDi0OiPzsa4KYzeTk5noL1WqbUaVQKox5gRKvP-BKcU/edit#heading=h.8klr4d9lyj5o
We actually perform the steps in GN-80 in order to accomplish this.

**Comment by daxmc99** [comment]
Final SOC2 document describing process: https://docs.google.com/document/d/1E6GHjgedE0vEcWB6MzFxWnHwzIY_K8Cum-3eM2l74G0/edit#

**Comment by daxmc99** [comment]
Required to merge before closing: https://github.com/sourcegraph/deploy-sourcegraph-cloud/pull/15871

**Comment by daxmc99** [comment]
Further work tracked https://github.com/sourcegraph/security-issues/issues/226
