### ISSUE TITLE
SOC2 - GN-82 Failover testing is performed

### ISSUE THREAD

**Issue by JenRed777** [sourcegraph/sourcegraph#29594]
Due: February 28, 2022

Failover testing is performed [frequency] to help ensure Company is prepared in the event of a scenario requiring failover.

Notes: 
Managed instances -> walk through db or system failover; 
Cloud -> failover testing needed for db (trigger cloud sql failover), Nodes -> remove node from Avail zone A;

**Comment by daxmc99** [comment]
Google drive link: https://docs.google.com/document/d/1GpUm2JUi57Fp01xjk-wcObr7LF0-pUsGozg2-V3SVhw/edit?usp=sharing

**Comment by caugustus-sourcegraph** [comment]
Added details to https://docs.google.com/document/d/1GpUm2JUi57Fp01xjk-wcObr7LF0-pUsGozg2-V3SVhw/edit for the managed instance failovers

**Comment by JenRed777** [comment]
@caugustus-sourcegraph 
For this control we will want to show a table top exercise where the team goes through and says what each persons role would be following a failover type incident. Almost like a retro type document. You could even use the steps that you all took to get the demo server back up and running last week.
For example:
- Delivery Person on-call was notified of a situation with the demo instance.
- On-call person logged in and found that services were not running.
And then the steps you took to fix the services. 

Let me know if you have any questions!

**Comment by caugustus-sourcegraph** [comment]
@JenRed777 - updated the doc with your recommendations! Let me know if there's still anything missing.

**Comment by JenRed777** [comment]
@caugustus-sourcegraph this looks great! Thank you
