### ISSUE TITLE
Redis OOM error prevents sign in or using server.

### ISSUE THREAD

**Issue by mcdan** [sourcegraph/sourcegraph#296]
- **Sourcegraph version:** sourcegraph/server:2.11.2 
- **Platform information:** 
```
➜  ~ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial
➜  ~ docker info
Containers: 24
 Running: 8
 Paused: 0
 Stopped: 16
Images: 55
Server Version: 18.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 462
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-104-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 15.44GiB
Name: coldplay
ID: TDMA:6IQ6:X2BE:S4NA:RDBL:TGJW:B22K:WAET:5N24:RK3E:CDJT:S7QC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```
#### Steps to reproduce:
Run the server for a while, with a bunch fo repos. I think I have about 8 or so configured with 5 language servers.
1. Try and login

#### Expected behavior:
1. Login and use site.
#### Actual behavior:
1. Login succeeds but you get into a redirect loop:
POST /-/sign-in : 200 OK
GET /search?toast=integrations : 302 -> /sign-in?returnTo=%2Fsearch%3Ftoast%3Dintegrations
POST.... etc, etc. never allows me in.

Meanwhile inside the server container I see 10s of these message per second:
```
16:06:24   repo-updater | t=2018-10-05T16:06:24+0000 lvl=warn msg="failed to execute redis command" cmd=SETEX error="OOM command not 
allowed when used memory > 'maxmemory'."
16:06:24   repo-updater | t=2018-10-05T16:06:24+0000 lvl=warn msg="failed to execute redis command" cmd=SETEX error="OOM command not 
allowed when used memory > 'maxmemory'."
16:06:24   repo-updater | t=2018-10-05T16:06:24+0000 lvl=warn msg="failed to execute redis command" cmd=SETEX error="OOM command not 
allowed when used memory > 'maxmemory'."
16:06:24   repo-updater | t=2018-10-05T16:06:24+0000 lvl=warn msg="failed to execute redis command" cmd=SETEX error="OOM command not 
allowed when used memory > 'maxmemory'."
16:06:24   repo-updater | t=2018-10-05T16:06:24+0000 lvl=warn msg="failed to execute redis command" cmd=SET error="OOM command not al
lowed when used memory > 'maxmemory'."
```

**Comment by keegancsmith** [comment]
Yeah I haven't seen this before, so warrants further investigation. Ideally we should be using less memory in redis. We rely on it working. However, I'm surprised we managed to put that much into redis that we hit memory warnings.

**Comment by mcdan** [comment]
@sqs It was as of a few weeks ago the 2.11.2 container I still have running is throwing those errors and I cannot log in. I do not have it even scraping "many" repos, perhaps around 20? That doesn't seem like a ton. I will retest this week with 2.11.3 and get back to you.

**Comment by mcdan** [comment]
So I've had 2.11.3 running for a few days now and I don't seem to get into the login loop but I do still see a large number of those redis OOM exceptions still. I currently only have 2 repos being indexed.

**Comment by mcdan** [comment]
Actually I stand corrected, just got the server into this state again. I had _just_ added a new repository bringing the total up to 3 and now I'm stuck in the redirect loop.

Is there anything I can pull off the system or container to help figure out what's the root cause? There is still plenty of memory and cpu available on the machine it's running on so it's not a resource issue locally.

I see the "frontend" process and a repo_updater using a pretty significant amount of CPU, but's a 16 core machine so overall the machine still has spare capacity.

One more detail, you only get in the redirect loop when you sign in properly, it correctly rejects bad credentials so it's something after the credentials are checked in the sign-in process.

**Comment by mcdan** [comment]
Another piece of the puzzle, I can sign in when all the high CPU usage goes away. So there is something probably really pounding redis which then causes the login to fail presumably because it can't put the new session id in redis.

**Comment by keegancsmith** [comment]
Could you share (with possibly sensitive information redacted) the output of `docker exec -it e746e5644cd8 redis-cli monitor` at startup. Where `e746e5644cd8` is the container ID for sourcegraph. We may have sensitive data in redis (eg http caching responses from code hosts), so you can also share the output just to me via keegan@sourcegraph.com

**Comment by tsenart** [comment]
In our server image, we currently have `maxmemory=1gb` and `maxmemory-policy=noeviction`. Is this the right eviction policy or could we benefit from using one of the others? Here's the run-down:

- noeviction: return errors when the memory limit was reached and the client is trying to execute commands that could result in more memory to be used (most write commands, but DEL and a few more exceptions).
- allkeys-lru: evict keys by trying to remove the less recently used (LRU) keys first, in order to make space for the new data added.
- volatile-lru: evict keys by trying to remove the less recently used (LRU) keys first, but only among keys that have an expire set, in order to make space for the new data added.
- allkeys-random: evict keys randomly in order to make space for the new data added.
volatile-random: evict keys randomly in order to make space for the new data added, but only evict keys with an expire set.
- volatile-ttl: evict keys with an expire set, and try to evict keys with a shorter time to live (TTL) first, in order to make space for the new data added.

**Comment by slimsag** [comment]
I think the right policy will depend on whether or not our server image shares a redis instance for cache & store data. I.e. I think one of the LRU options would be desirable for redis-cache but for redis-store we probably would want noeviction

**Comment by slimsag** [comment]
Hah, indeed, that is what we do in Kubernetes deployments:

- https://github.com/sourcegraph/infrastructure/blob/master/docker-images/redis-cache/redis.conf
- https://github.com/sourcegraph/infrastructure/blob/master/docker-images/redis-store/redis.conf

**Comment by keegancsmith** [comment]
yup, we should probably spin up two redis instances for server, one for cache and one for store (much less data in store)

**Comment by tsenart** [comment]
Closing given all the work that went into Redis in #8235. Will reopen if it resurfaces.
