### ISSUE TITLE
spin up GitLab test instance

### ISSUE THREAD

**Issue by courier-new** [sourcegraph/sourcegraph#29609]
[In November, 2021, it was discovered that our internal Sourcgraph GitLab instance, gitlab.sgdev.org, was compromised.](https://sourcegraph.slack.com/archives/C1JH2BEHZ/p1636068110056000) This resulted in the VM immediately being terminated. Due to the fact that there was no clear owner or maintainer of these private code host instances at the time that the issue was first raised, there hasn't been an opportunity to restore the GitLab instance since then.

gitlab.sgdev.org continues to be listed as [the recommended way for testing GitLab](https://handbook.sourcegraph.com/departments/product-engineering/engineering#sourcegraph-deployments-and-other-developer-test-instances) in the handbook despite being unavailable, and the desire to restore the private instance is shared across teams and departments. It's very helpful when testing new code host interactions or reproducing customer issues to have a private GitLab instance to test with, vs. playing "out in the open" on gitlab.com and needing to rely on the smaller collection of Sourcegraph test repositories there.

#### Next Steps
- Follow up on the security incident from when the instance was discovered to be compromised and determine what actions need to be taken to safely recover the instance, including if that requires starting fresh with a new instance.
- Determine if it's possible to run the instance in a way that's not publicly accessible:
  > Dax: There are a few services we run like this for backend tests (github, gitlab, perforce). I would love to centralize access to of them and work to make them non-publicly accessible (using Google private IPs and auth-proxy's for access).
If there is a doc for collaboration on this, happy to provide suggestions there too.
- Update `dev-private` external service configuration

**Comment by michaellzc** [comment]
close via https://github.com/sourcegraph/handbook/pull/3831, https://github.com/sourcegraph/infrastructure/pull/3408
