### ISSUE TITLE
SOC2 - GN111 Sourcegraph tests their Disaster Recovery and Business Continuity Plan on an annual basis

### ISSUE THREAD

**Issue by JenRed777** [sourcegraph/sourcegraph#29602]
Due: February 28, 2022

Sourcegraph tests their Disaster Recovery and Business Continuity Plan on an annual basis. Testing includes scenarios related to information system recovery and the continuity of business operations.

Notes: Tabletop of an in-sync scenario where GCP Cloud Services are down. How we preform simulations. GN-111 is the simulation of what you say you can solve in GN-110

**Comment by JenRed777** [comment]
This one is similar to GN-82. We should be able to use the same table top for this.

**Comment by JenRed777** [comment]
We should actually use what we do for GN-81 for this one. Blocked until that one is completed.

**Comment by daxmc99** [comment]
Blocked on https://github.com/sourcegraph/sourcegraph/issues/29593

**Comment by daxmc99** [comment]
Document created here: https://docs.google.com/document/d/1Et5Y1H5y6NEgKLnEqpgIMUy080UAUpl6Ab7Ar7csJ7U/edit# 
Still need to complete final items
