### ISSUE TITLE
SOC2 - GN-110 Sourcegraph has a Disaster Recovery and Business Continuity Plan.

### ISSUE THREAD

**Issue by JenRed777** [sourcegraph/sourcegraph#29601]
Due: February 28, 2022

Sourcegraph has a Disaster Recovery and Business Continuity Plan.

Notes: Document in handbook, "what do we do when we lose the main db", restore from backup. Playbook level quality, scenario with specific instructions. Possible scenario: All production databases have been corrupted

**Comment by JenRed777** [comment]
Still need to come up with plan for Managed Instnaces

**Comment by daxmc99** [comment]
@caugustus-sourcegraph Can you comment with the document you created?

**Comment by caugustus-sourcegraph** [comment]
@daxmc99  - No doc created yet, I put the info in https://docs.google.com/document/d/1GpUm2JUi57Fp01xjk-wcObr7LF0-pUsGozg2-V3SVhw (all the "Failover type" things). We decided those sections didn't fit in GN-82 so they could be transferred to GN-110 instead.

Let me know if I need to make a doc or if you were just looking for the info!

**Comment by JenRed777** [comment]
Cloud Playbook on disaster recovery is located here: https://handbook.sourcegraph.com/departments/product-engineering/engineering/process/incidents/playbooks/dotcom_deleted_entirely/
Delivery Playbook on disaster recovery it located here: https://handbook.sourcegraph.com/departments/product-engineering/engineering/cloud/delivery/managed/upgrade_process/

**Comment by JenRed777** [comment]
Want to see if we need to have a document that points to these references or not

**Comment by daxmc99** [comment]
> Cloud Playbook on disaster recovery is located here: [handbook.sourcegraph.com/departments/product-engineering/engineering/process/incidents/playbooks/dotcom_deleted_entirely](https://handbook.sourcegraph.com/departments/product-engineering/engineering/process/incidents/playbooks/dotcom_deleted_entirely/)

Need to update this to use Velero backup instructions

**Comment by JenRed777** [comment]
Created GN-110 [Doc](https://docs.google.com/document/d/1_-lMPNyCRiEgtFAe53g_BLmLzAC0lRGntyviOjpbTuE/edit#)
