### ISSUE TITLE
Invalid Semantic Version when logging in to k8.sgdev

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#29618]
## Steps to reproduce
I followed the quickstart here:
https://docs.sourcegraph.com/batch_changes/quickstart#install-the-sourcegraph-cli

```
curl -L https://k8.sgdev.org.api/src-cli/src_darwin_amd64 -o /usr/local/bin/src
chmod +x /usr/local/bin/src
```

Set the src-cli endpoint and token as en variables, then 

```
src login
```
returns Authenticated as malo on https://k8s.sgdev.org

Run: 

```
src batch preview -f somespec.yml
```

## Crash output:

```
❌ Error:
   failed to check version returned by Sourcegraph: Invalid Semantic Version
```

**Comment by courier-new** [comment]
Looks like this is actually a different issue with the version string that's currently on k8s: https://sourcegraph.slack.com/archives/C01N83PS4TU/p1642013850061100

Should be fixed by https://github.com/sourcegraph/sourcegraph/pull/29654.
