### ISSUE TITLE
sg: prompt the user for auto-updating rather than issuing a warning that new version is available. 

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#29619]
Quoting @unknwon from Slack: 

> I'm doing it almost every single day... and I need to open a separate tab for running this command... could we instead prompt a "Y/n" (default no) and do the upgrade automatically (like oh-my-zsh) :grin:

**Comment by KShivendu** [comment]
Hey @jhchabran I'd like to work on this. Please assign it to me :)

**Comment by jhchabran** [comment]
@KShivendu There you go! Feel free to mention me here if you need any feedback or if you have any questions :)
