### ISSUE TITLE
RepoSubsetText search failed: git command [git show-ref] failed (output: ""):

### ISSUE THREAD

**Issue by rohitagarwal003** [sourcegraph/sourcegraph#29670]
- **Sourcegraph version:** "Sourcegraph.com"
- **Platform information:** macOS 12.1, Google Chrome 97.0.4692.71 (Official Build) (x86_64)

#### Steps to reproduce:

1. Go to https://sourcegraph.com/search?q=context:global+pod-deletion-cost+repo:/*/kubernetes+f:annotation_key_constants.go+-f:vendor/+fork:yes+rev:*refs/heads/*1.19*&patternType=literal

#### Expected behavior:
Should see some results or a no results page

#### Actual behavior:
Getting internal error messages.

<img width="1792" alt="Screen Shot 2022-01-13 at 6 01 55 AM" src="https://user-images.githubusercontent.com/695290/149244665-782f54aa-fa8b-4ee5-8ac9-ce44d993c202.png">

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket,  please let us how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
