### ISSUE TITLE
SSBC-EM3.2: Enable initial cut of designs

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#29688]
- [x] #28939 **`3d`** @courier-new
  - [x] Write-up and proposal/prototype **`1d`**
  - [x] Implementation **`2d`**
- [x] #30064 **`0.5d`** @courier-new 
- [x] Implement UI for execution options dropdown **`1d`** @courier-new
- [x] Implement basic filters in workspaces list **`3d`** @eseliger 
- [x] Implement search **`4d`** @eseliger 
  - [x] in workspaces list **`2d`** @eseliger 
  - [x] in workspace preview list **`2d`** @eseliger 
- [x] Add retry workspace to UI
- [x] Implement workspaces stats resolver
- [x] Display batch changes stats (number of workspaces errored, successful, etc)
- [x] Show statically skipped steps in UI as skipped (currently omitted)
- [x] Show if condition on steps
  - [x] Design: https://www.figma.com/file/cTKjwbvWqU6xAykZmCTTqy/SSBC?node-id=1549%3A49280
- [x] Show/link to execution on Draft Batch Change page **`1d`**
- [x] Implement "Draft" Batch Changes (**Requires EM2.4**)
  - [x] Introduce draft: Boolean! field in graphql API
  - [x] Allow filtering by draft state in BatchChangeConnection
  - [x] Add "Draft Batch Changes" to UI
- [x] We create an initial cut of user-facing docs for SSBC **`2d`**
  - [x] What it does **`0.5d`**
  - [x] Setup **`0.5d`**
  - [x] How to get started with SSBC **`0.5d`**
  - [x] Limitations **`0.5d`**
- [x] #29583 **`1.5d`**

**Comment by malomarrec** [comment]
> * Update workflow (Update batch spec and re-execute) **`Xd`**
TBD in today's design sync

**Comment by courier-new** [comment]
Whoops didn't mean to close this yet.
