### ISSUE TITLE
zoekt: work out why incremental gitserver interactions fail sometimes

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#29695]
I have seen this pop up a few times, most recently [#inc-68-zoekt-index-is-stuck-on-a-4-hour-old-commit-for-srcsrc](https://sourcegraph.slack.com/archives/C02U4GB0Y8H). I added a mitigation, but I need to dive in to work this out since this may be happening more than we think.

First port of call is detailed observability around repository updates in gitserver. This will also help me understand what is happening in zoekt.

**Comment by keegancsmith** [comment]
I'm pausing work on this for this week, will reconsider next week.

**Comment by keegancsmith** [comment]
FYI I did some refactorings in preperation for fixing this on Friday. I believe I root caused the issue to do with us mishandling gitserver being down.

Refactors:
- https://github.com/sourcegraph/zoekt/pull/287
- https://github.com/sourcegraph/zoekt/pull/286

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket,  please let us how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
