### ISSUE TITLE
Create repo page in VSCE when clicking in to repo search result

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#29699]
Problem: Currently, if the search results directs a user to a repository, it only opens a line item in the Files section, which could be collapsed, have a lot of entries, etc. It's too subtle and easy to miss. 

Solution: [Create a modified repository page in vSCE.](https://www.figma.com/file/EXXvfxVwtCIsrbQez4rPlF/VS-Code-Extension-MLP?node-id=1591%3A5977) At the moment, only the functionality to navigate within that repository has been maintained, and all additional features for Changes, APIs, etc. have been removed. They are not critical functionality for MVP, and can be added post first release.

**Comment by abeatrix** [comment]
@jjinnii I have implemented a simple repo page before this issue was created so I didn't see the suggested design. I can work on it next week but want to know if we should open the repo page in a separate tab? (If yes then I would need to create a new webview component and might be a 2-3 days work)

This is what the repo page currently looks like: 
![image](https://user-images.githubusercontent.com/68532117/149551306-2ab3f87f-62fa-4d5d-8f26-f8e2df7b2cd8.png)

**Comment by jjinnii** [comment]
@abeatrix Thanks for calling that out! I had initially thought opening in a separate tab made the most sense, as a user will most likely end up opening a file from that repo. However, I don't think that behavior is important enough to warrant 2-3 days development time. I will modify my design, and maybe add an issue in the icebox for opening in a separate tab for post-release.

**Comment by jjinnii** [comment]
Design updated :)

**Comment by abeatrix** [comment]
Discussed with Sara on how users can go back to the search result page, waiting for their updates.

For now, I've added a back to search result button to display previous search results:
![image](https://user-images.githubusercontent.com/68532117/149844526-0ef04edf-5c79-43c4-b49c-7a84a2ccea80.png)

**Comment by abeatrix** [comment]
@jjinnii Added 1rem of space between the button and the repo header. Let me know if this looks ok (it's an easy change so feel free to let me know if you want to play around with the spacing!) 
<img width="2196" alt="Screen Shot 2022-01-19 at 7 56 12 AM" src="https://user-images.githubusercontent.com/68532117/150167385-4e0151f6-9d30-4e4f-8045-35990bce3950.png">

**Comment by jjinnii** [comment]
Looks amazing, thanks @abeatrix !
