### ISSUE TITLE
no buildable Go source files

### ISSUE THREAD

**Issue by dpopiashvili** [sourcegraph/sourcegraph#297]
Hey guys

I just cloned sourcegraph but I'm unable to invoke dev/launch.sh. I get the following error:

> can't load package: package ./pkg/version/minversion: no buildable Go source files in /home/dato0011/go/src/sourcegraph/pkg/version/minversion
> Go version 1.11.x or newer must be used to build Sourcegraph; found: go version go1.6.2 linux/amd64
> 

Any idea what could be wrong?

Thanks

**Comment by kevinburke** [comment]
@dpopiashvili Hey there - the error is in the second part of that message, specifically:

>  Go version 1.11.x or newer must be used to build Sourcegraph; found: go version go1.6.2 linux/amd64

Rerun `go version` and check that you are using a new version of Go. It looks like you're trying to run with go 1.6, which is not compatible, unfortunately.
