### ISSUE TITLE
Create VSCE specific signup page 

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#29703]
We have multiple re-directs from the VSCE to sourcegraph.com to promote account creation, however, we are directing users to Sourcegraph's generic signup page, where the messaging is not effectively communicating the value of account creation to a VSCE user. (For example, "Navigate through code with IDE-like go to definition and reference hovers" seems out of place when a user is coming as a VS Code user.)

It will be very powerful to have a signup page with copy that better communicates the value of account creation to an IDE-user.

**Comment by jjinnii** [comment]
Amazing work, thanks so much @philipp-spiess !!! 

@abeatrix @tjkandala lmk if you need me to create a separate issue for this, but all ["Create an account"](https://www.figma.com/file/EXXvfxVwtCIsrbQez4rPlF/VS-Code-Extension-MLP?node-id=1371%3A2976), ["Sign up for Sourcegraph"](https://www.figma.com/file/EXXvfxVwtCIsrbQez4rPlF/VS-Code-Extension-MLP?node-id=246%3A11) buttons should now link to this new VSCE signup page.

**Comment by abeatrix** [comment]
@philipp-spiess Looks great!! 

@jjinnii Is `https://sourcegraph.com/sign-up?editor=vscode=1&showEmail=true` the correct path to use?

**Comment by jjinnii** [comment]
@abeatrix Do we need to show the "showEmail=true" for a technical reason? It seems like sourcegraph's default signup page just has the URL: https://sourcegraph.com/sign-up. Perhaps we can cut off our path after vscode if possible?

**Comment by abeatrix** [comment]
@jjinnii i just saw the `showEmail=true` part from the @philipp-spiess's [PR](https://github.com/sourcegraph/sourcegraph/pull/29744#issue-1103612339) so I just want to confirm with you on which URL to use 😆

**Comment by philipp-spiess** [comment]
> showEmail=true

Yeah this is because right now the email field is only shown as a "second step" after this screen:

![Screenshot 2022-01-20 at 18 32 41](https://user-images.githubusercontent.com/458591/150391340-7e3b37f7-06ab-44b6-84d9-6f13131915e1.png)

I copied this from the existing cloud sign up, @slimsag probably has more context :)

**Comment by jjinnii** [comment]
Okay really not a big deal! If we can remove that "showEmail=true", great -- if it's there for a reason, then no problem at all.
