### ISSUE TITLE
VSCE: Support pre-release version

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#29706]
Ref: https://code.visualstudio.com/api/working-with-extensions/publishing-extension#prerelease-extensions

Context: https://sourcegraph.slack.com/archives/C01T0BL4EFN/p1641390780041300

**Comment by abeatrix** [comment]
In our current release workflow, we would run the `vsce package` in the vscode directory manually to create the VSIX file that we use to upload to the VS Code Marketplace as we do not have the necessary token to run `vsce publish` to publish the extension using the CLI.

The workflow would be the same for publishing a pre-release version of the extension ([docs](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#prerelease-extensions)) by adding a pre-release flag in the package step: `vscode package --pre-release`

**Comment by abeatrix** [comment]
@jjinnii @tjkandala just wants to make sure we are on the same page that the next VSCE release's version number will be `2.2.0` instead of `2.1.0` following the VS Code version numbering rule if we want to have both release and pre-release versions for the extension. We can close this issue if this looks good to everyone.

**Comment by abeatrix** [comment]
Thank you both 🙇

**Comment by jjinnii** [comment]
Sounds good to me, thanks @abeatrix! Do we expect any changes to the marketplace copy/user docs required due to the new numbering? (will be good to know for future reference for myself as well 😄 )

**Comment by abeatrix** [comment]
It does, i'm actually working on it right now. I will link it to this thread once I'm done to close this issue, thanks for pointing it out!

**Comment by jjinnii** [comment]
Thank _you_ for being proactive about it! 🚀
