### ISSUE TITLE
Document testing process that are not mandatory and establish audit trail

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#29718]
Given that some of our "encouraged" testing processes will not be able to be enforced (due to complexity or velocity constraints), identify and document an "audit trail" that shows malicious and/or breaking code is prevented from reaching production.

**Comment by taylorsperry** [comment]
We've broken this down into smaller issues that will be addressed separately.

**Comment by bobheadxi** [comment]
Linking for context, presumably relevant issues are now in https://github.com/sourcegraph/sourcegraph/issues/29724
