### ISSUE TITLE
Identify testing processes that should be mandatory, enforce, and update docs

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#29717]
Audit our testing documentation, determine which testing processes should be mandatory, and make necessary adjustments to enforce those processes. Update documentation accordingly.

**Comment by taylorsperry** [comment]
We've broken this down into smaller issues that will be addressed separately.

**Comment by bobheadxi** [comment]
Linking for context, presumably all issues are in https://github.com/sourcegraph/sourcegraph/issues/29724
