### ISSUE TITLE
Security team approval for updated SOC2-related documentation

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#29719]
Once issues https://github.com/sourcegraph/sourcegraph/issues/29717 and https://github.com/sourcegraph/sourcegraph/issues/29718 have been addressed, request review from security team to approve updated processes and documentation.

**Comment by bobheadxi** [comment]
https://github.com/sourcegraph/sourcegraph/pull/29927 and using these tags going forward would make it easier for us to request this review 👍

**Comment by bobheadxi** [comment]
For clarification: we own these items, and don't need security approval
