### ISSUE TITLE
deploy ranking for customers

### ISSUE THREAD

**Issue by jjeffwarner** [sourcegraph/sourcegraph#29729]
Ranking has been abled on Cloud by enabling the default features in Zoekt. The next step is to make this available with a feature switch so customers can enable/disable it.

Also need an explanation about how the ranking algorithm works currently. -- @keegancsmith

**Comment by keegancsmith** [comment]
We had the better "result" ranking enabled only for sourcegraph.com employees. This is about to be turned on for everyone by https://github.com/sourcegraph/sourcegraph/pull/29691

I think there is likely still something around repo star ranking which we haven't enabled yet for everyone outside of cloud. Lets use this issue to track that as well.

**Comment by keegancsmith** [comment]
Status: the PR to enable hunk based ranking is still in progress. We have one UI issue.

I have on my todo list to follow up on the final item around enabling repo ranking for customer installations. Hopefully get it done before branch cut :)

**Comment by keegancsmith** [comment]
FYI the hunk based ranking is now in main! It will be in the next release :) https://github.com/sourcegraph/sourcegraph/issues/29729
