### ISSUE TITLE
Insights Spike: Search Contexts for Insights

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#29723]
We have [customer and prospect feedback](https://sourcegraph.productboard.com/feature-board/1793095-code-insights/features/9370711/insights) that they want to use search context - like objects to run insights over for the case that is >10 explicit repos and < all repos. 

There are multiple "kinds" of search contexts now – search-defined and JSON-defined – and we should aim to support both, ideally from the start, to avoid confusion around communicating only 1 kind of context (and confusion on the frontend as we integrate "you can 1-click from search and it now keeps your context, rather than stripping it"). 

We should spike to figure out what might be involved for iteration v0 of this feature to ship a first version. This is somewhat a backend and frontend question, perhaps: right now, if you use a context, it flatlines insights to the "current revision" because that's how contexts were originally pinned.

![image](https://user-images.githubusercontent.com/11967660/149408817-ffa485a8-94ca-4332-bfcc-4ab459724308.png)

Specific questions from the product POV: 
- If we did [x proposal] could you use all search context types? Just some? 
- Can we limit persisted insights given a scope to just run over the repos in a context (or should that be a separate exploration), to improve performance? 

Not direct questions, but things to think about: 
- If we had to ship this with only 1 iteration, what version / what might be build? 
- If we had 2 months to do it "perfectly" how would you want to approach it? 
- (Is there a way we can make both of those the same :) )

**Comment by coury-clark** [comment]
A few other considerations for this spike:
1. Some amount of the new query prefix contexts are implemented client side. What would be the effort to replicate that behavior / move it to a common backend, or otherwise be able to detect that this context is not usable?
2. Could we explore snapshotting the repositories that match a context with something like a `select:repo` query with just the provided context? 
    1. What if this gets really big, how do we handle this?
    2. Would the GraphQL API continue to be sufficient here, or do we need to stream?
    3. Do we go against Sourcegraph search, or directly to the db? If direct, we could paginate with repo id.
    4. How would we extract the context out of the search query? Can the parser do this for us?
    5. Does this snapshot against the current index satisfy a true match over all repos? Maybe the direct DB route is better here after all?
    6. We could separate the context from the query using our `repositoryScope` concept, similar to how we separate out individual repositories now. This might solve some of these problems above.

**Comment by Joelkw** [comment]
Notes from team sync: 
- We likely may want to do something similar to the repository list? 
- From vova – can you set different series to have different contexts? 
- Backend will be built per series anyway, so whether we collect them by series is a frontend consideration 
- Do we support multiple contexts by insight? 
- You won't be able to pin revisions to contexts 
- We may have to sidestep context functionality and look up repos directly, or something 
- We might only support search-based contexts? Figure out the vision there. 
- Contexts are being pinned as the org construct on cloud.

**Comment by coury-clark** [comment]
Thinking just about filtering a pre-generated series:
1. Can we filter on both a repository regexp and a search context?

**Comment by coury-clark** [comment]
The ability for a search context to support pinned revisions is a feature that is currently (and tentatively) incompatible with Code Insights. One other question I have is how search contexts might evolve over time, and whether or not we can continue to support the full set of those new features. We may also consider supporting a minimal version of a search context, for example:
1. Repository revisions will only take the repository
2. Search query prefixes will support repository name matching

**Comment by coury-clark** [comment]
We can extract the regexp for include / exclude from the context by parsing the query:

``` go
	var plan query.Plan
	q := "repo:sourcegraph/.* -repo:asdf/.*"
	plan, err := query.Pipeline(
		query.Init(q, query.SearchTypeRegex),
	)
	if err != nil {
		t.Fatal(err)
	}

	t.Log(plan.ToParseTree().Repositories())
```
```
[sourcegraph/.*] [asdf/.*]
```

**Comment by coury-clark** [comment]
Closing based on doc above
