### ISSUE TITLE
Symlinked repos don't appear in search

### ISSUE THREAD

**Issue by DaedalusG** [sourcegraph/sourcegraph#29726]
- **Sourcegraph version:**  v3.35.1
- **Platform information:** 

#### Steps to reproduce:
1. Create a repo containing symlinked files
```bash
warrengifford@Warrens-MacBook-Pro ~ % mkdir symlink-test
warrengifford@Warrens-MacBook-Pro ~ % cd symlink-test
warrengifford@Warrens-MacBook-Pro symlink-test % git init
Initialized empty Git repository in /Users/warrengifford/symlink-test/.git/
warrengifford@Warrens-MacBook-Pro symlink-test % mkdir a-dir
warrengifford@Warrens-MacBook-Pro symlink-test % mkdir b-dir
warrengifford@Warrens-MacBook-Pro symlink-test % mkdir c-dir
warrengifford@Warrens-MacBook-Pro symlink-test % ls
a-dir	b-dir	c-dir
warrengifford@Warrens-MacBook-Pro symlink-test % cd a-dir
warrengifford@Warrens-MacBook-Pro a-dir % touch deploy.yaml
warrengifford@Warrens-MacBook-Pro symlink-test % ln -s ./a-dir/deploy.yaml ./b-dir/deploy.yaml
warrengifford@Warrens-MacBook-Pro symlink-test % ln -s ./a-dir/deploy.yaml ./c-dir/deploy.yaml
```
After a procedure like above you should have one `deploy.yaml` file in `a-dir` and two other directories containing symlinked `deploy.yaml` files
2. Sync the git repo to Sourcegraph
3. Run a search in the repo for the `deploy.yaml` files -- `repo:^github\.com/DaedalusG/symlink-test$ file:deploy.yaml`

#### Expected behavior:
You would expect that such a search returns all three instances of a `deploy.yaml` file
#### Actual behavior:
Only the one `a-dir/deploy.yaml` file is returned in the search
![Screen Shot 2022-01-13 at 2 28 29 PM](https://user-images.githubusercontent.com/13024338/149419097-5f4045e3-17ab-47d1-883f-3425acc46efa.png)

Sourcegraph is currently working on better support for symlinks and we expect to have this and similar issues resolved soon. There are two issues we need to resolve to support symlinks better. 

1. When reading the contents of a file for display, we currently seem to have a [bug](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/vcs/git/tree.go?L64:3&subtree=true) that prevents from reading the contents of the linked file.
2. In Zoekt, we skip symlinks, so they are not indexed. We'll need to fix that too (cc @stefanhengl, please comment with details).

We're aware of these issues and hope to have them resolved in a release soon, here are some PRs of ongoing work --
https://github.com/sourcegraph/zoekt/pull/237
https://github.com/sourcegraph/sourcegraph/pull/29567
https://github.com/sourcegraph/sourcegraph/pull/29687

If would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are not [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

**Comment by stefanhengl** [comment]
This has been fixed on main with the PRs mentioned in @DaedalusG description. It will be shipped with the next release. Here is an example of a query on our Cloud instance that now return symbolic links

https://sourcegraph.com/search?q=context:global+r:stefanhengl/symlink-test+file:deploy.yaml&patternType=literal
