### ISSUE TITLE
GN-105: Document process for deviating from standards

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#29764]
Add documentation to our [Continuous Integration](https://docs.sourcegraph.com/dev/background-information/continuous_integration) page that enumerates "break glass" scenarios (any time we have to deviate from a process) and our process for handling them.

Definition of Done: For any deviation from our process, we have a documentation for how it should be handled, and a running log of (an "audit trail") for these deviations.

**Comment by taylorsperry** [comment]
@jhchabran Are the CI docs the right place for this information?

**Comment by jhchabran** [comment]
@taylorsperry that should be the handbook, because that's solely applicable to teammates and not external contributors.

**Comment by taylorsperry** [comment]
Gotcha, thanks! Is[ Sourcegraph releases](https://handbook.sourcegraph.com/departments/product-engineering/engineering/process/releases) a better spot?

**Comment by jhchabran** [comment]
I don't think so, that one is particularly specific to releases and we don't want releases to include messages like these. It's probably best put in section that we need to create under https://handbook.sourcegraph.com/departments/product-engineering/engineering/process

**Comment by bobheadxi** [comment]
This seems very closely tied to https://github.com/sourcegraph/sourcegraph/issues/29765 - I'll work on this one
