### ISSUE TITLE
GN-105, GN-104: Provide audit trail for break glass scenarios

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#29765]
All "break glass" events must be logged in such a way that an auditor can read through them chronologically (an "audit trail").

A potential solution might be to create a bot that can push a PR comment ("We tested this manually because of X, and verified that it worked in this link").

Definition of Done: We have created and documented a centralized space where deviations can be reviewed chronologically.

**Comment by jhchabran** [comment]
FYI Our Slack account has a retention policy (can be exempted apparently) https://sourcegraph.slack.com/archives/C01CSS3TC75/p1641566033032300?thread_ts=1641507795.015300&channel=C01CSS3TC75&message_ts=1641566033.032300

**Comment by bobheadxi** [comment]
Reference: JH's proposal + discussion from RFC 568 https://docs.google.com/document/d/1d0o1O1ReazXKoDB_MANo1MuWfqBlgeU-5VZAAZRGamc/edit#heading=h.8jd76lorwhek

I am leaning towards the approach that creates an issue in a repo
