### ISSUE TITLE
GN-106: Document soft failures

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#29761]
Add documentation to our [Continuous Integration page ](https://docs.sourcegraph.com/dev/background-information/continuous_integration) that describes soft failures as temporary exceptions that result from experimental or in-progress work. This should only be a short paragraph.

**Comment by taylorsperry** [comment]
@jhchabran are the CI docs the best place to add this short paragraph?

**Comment by jhchabran** [comment]
Yes, and we'll mention them on the final SDLC page in the handbook!

**Comment by jhchabran** [comment]
Example resources:
  - Good structure: https://about.gitlab.com/stages-devops-lifecycle/
  - Overly exhaustive and should not be replicated: https://about.gitlab.com/handbook/engineering/workflow/
