### ISSUE TITLE
insights: nil error when creating a dashboard with an invalid userId

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#29774]
When creating dashboard with an orgID or userID that doesn't belong to the current user, the API returns the following error:
```
{"errors":[{"message":"graphql: got nil for non-null \"InsightsDashboardPayload\"","path":["createInsightsDashboard"]}]
```

Reported by @andreeleuterio

**Comment by unclejustin** [comment]
Is the proposed solution here to just surface a user-friendly error message?

**Comment by Joelkw** [comment]
Let's determine this is not a security issue at least, even if we don't fix fully – validate that this isn't a problem, then re-evaluate whether worth fixing.
