### ISSUE TITLE
Scale structural search with streaming and worker pool

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#29785]
Issue description in notebook: https://sourcegraph.com/notebooks/Tm90ZWJvb2s6Mjk=

**Comment by tsenart** [comment]
@rvantonder @camdencheek: I didn't manage to make enough progress here before switching focus to dependency search. The very WIP and debuggy code that I ran @camdencheek through lives here: https://github.com/sourcegraph/sourcegraph/tree/ts/streaming-structural-search
