### ISSUE TITLE
Spacing issues in sidebar

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#29826]
Small discrepancies in spacing of elements in the VSCE sidebar. Please see below screenshot. Increased height is causing the "Seach your private code" section to be hidden for users, depending on their browser height. 
<img width="288" alt="Screen Shot 2022-01-17 at 3 36 39 PM" src="https://user-images.githubusercontent.com/87138876/149834553-622a5c16-962b-4fe0-96b8-1b9077c0bd92.png">

**Comment by abeatrix** [comment]
Updated spacing to match Figma design
![image](https://user-images.githubusercontent.com/68532117/149971923-6b4ac682-1280-46ed-86c0-2277d033ce89.png)
![image](https://user-images.githubusercontent.com/68532117/149972264-3815cc29-50d0-43e6-a9d1-81179d72ec9a.png)
![image](https://user-images.githubusercontent.com/68532117/149974478-e81a68cf-3b30-4890-907b-829ddb50f307.png)

**Comment by jjinnii** [comment]
Thanks @abeatrix! Sorry for being nitpicky here, just a couple additional things: Again to clarify, this issue is not high priority in the least -- if there are other issues that you feel are more impactful, please feel free to shift focus!

* The "Welcome" and "Search your private code" subtitles look a bit larger than the other subtitles -- which I think is also contributing to "Sourcegraph Search" and "Welcome" looking much closer together than in my mockups. Would you be able to double check this? 

![sidebar 1](https://user-images.githubusercontent.com/87138876/150035158-7d0122a7-d342-4b1f-af04-1a758aef6e46.png)

* There's a question mark after "Have an account?" :) 
* We seem to lose the spacing between the input field and "Update Access Token" button when an error occurs. Also typically error messages go below the input field 

![sidebar 2](https://user-images.githubusercontent.com/87138876/150035301-2f9b7a73-cc5d-43cc-8cb9-a6dce64d6249.png)

**Comment by abeatrix** [comment]
@jjinnii No problem! I should have asked before 😅 but is there a way to check the spacing you are using on your figma files?

**Comment by abeatrix** [comment]
This is what I have for now. I have updated to use vs code built-in color scheme for warnings and font (size and color). Please let me know changes are required, thanks Sara! 


<img width="1860" alt="Screen Shot 2022-01-20 at 4 52 13 PM" src="https://user-images.githubusercontent.com/68532117/150445800-53f741c0-4428-4cec-9ca9-58ca5bc3d306.png">

<img width="1904" alt="Screen Shot 2022-01-20 at 4 25 21 PM" src="https://user-images.githubusercontent.com/68532117/150445631-f4eb12b6-8a37-41b5-8fb4-4df2a0360b84.png">

<img width="1904" alt="Screen Shot 2022-01-20 at 4 44 15 PM" src="https://user-images.githubusercontent.com/68532117/150445688-4df9826e-3a9a-4c03-bb74-7f0d78ab8133.png">

**Comment by jjinnii** [comment]
Thanks @abeatrix , looks great! Just a super small nit here -- could we double check the spacing btw the "Welcome" section and "Search your private code" section? I have it as 40px and it looks a bit more closer tgt than my designs. If it is accurate, can we add an extra rem of spacing? It's a bit hard to visually distinguish the two sections right now :)

**Comment by abeatrix** [comment]
Hey @jjinnii , I just updated so that the spacing between those sections are 2.5rem (40px) apart, and within each section, the paragraphs are 1rem(16px) apart, and then the space between the input area and button and link below the buttons are at 0.5rem (8px), following your figma design. Please let me know if this looks ok :) 
<img width="1904" alt="Screen Shot 2022-01-25 at 7 34 54 AM" src="https://user-images.githubusercontent.com/68532117/151008128-0ddbc760-77c5-4e77-8af8-7312ca8ae01f.png">
<img width="1904" alt="Screen Shot 2022-01-25 at 7 35 57 AM" src="https://user-images.githubusercontent.com/68532117/151008152-c79cac02-6ea4-41c4-a557-53e452a0c0eb.png">

**Comment by jjinnii** [comment]
Looks phenomenal, thanks so much @abeatrix !
