### ISSUE TITLE
Add feedback button

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#29827]
There is a need to add a feedback button to the VSCE UI, so that users can easily provide feedback for the extension. The button also helps to communicate to users that this is an early release of the extension. This button should be exposed in all pages of the extension, and will link to a Github discussion board. (TBD on the URL)

**Comment by jjinnii** [comment]
@abeatrix Designs updated to include feedback button: 

[On homepage](https://www.figma.com/file/EXXvfxVwtCIsrbQez4rPlF/VS-Code-Extension-MLP?node-id=1371%3A2976)
[On search results page](https://www.figma.com/file/EXXvfxVwtCIsrbQez4rPlF/VS-Code-Extension-MLP?node-id=1286%3A1662)

It's a bit more difficult to add in a feedback button when a user is clicked into a file, as the dividing line btw VS Code the IDE and Sourcegraph search is a bit more blurred at that point. For MVP, I think it's sufficient to have the feedback buttons captured on the main search results and homepage.

**Comment by abeatrix** [comment]
Feedback buttons added
<img width="1863" alt="Screen Shot 2022-01-24 at 8 37 20 AM" src="https://user-images.githubusercontent.com/68532117/150834140-3755ab1c-b2f7-43fd-89d3-5a457a061a2c.png">
<img width="1909" alt="Screen Shot 2022-01-24 at 9 25 14 AM" src="https://user-images.githubusercontent.com/68532117/150834156-37fd6088-4253-4414-993d-d29dacf0f1b7.png">

**Comment by jjinnii** [comment]
Looks great, thank you @abeatrix !
