### ISSUE TITLE
Flake: TestSearch/stream/And/Or_search_expression_queries

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#29828]
- **Name of test:** TestSearch/stream/And/Or_search_expression_queries
- **Example failure:** https://buildkite.com/sourcegraph/sourcegraph/builds/125871#d45febe8-ca19-4509-97b7-e73d89e38276/204-208
- **PR**: https://github.com/sourcegraph/sourcegraph/pull/29829

#### Additional details

https://sourcegraph.grafana.net/goto/NkChYsJ7z?orgId=1

**Comment by camdencheek** [comment]
I ran this test ~1000 times locally, and didn't manage to reproduce the flake, so maybe a CI-specific flake?

**Comment by rvantonder** [comment]
Re-enabled as of https://github.com/sourcegraph/sourcegraph/pull/29873

**Comment by rvantonder** [comment]
This is a legitimate failing test, it's just nondetermnistic. Maybe a separate bug report issue works better? Or should we repurpose this issue?

**Comment by bobheadxi** [comment]
If the test remains nondeterministic ("flakey"), it should be disabled until the test is fixed or removed entirely (https://docs.sourcegraph.com/dev/background-information/testing_principles#flaky-tests) and this issue should stay open until one of those things happen

**Comment by rvantonder** [comment]
@tsenart can you share your script to reproduce this issue? I wanted to write up an issue to track the bug but need a reliable way to reproduce so I can understand the problem exactly.

**Comment by rvantonder** [comment]
Via @tsenart for debugging:


```
go test -failfast -count=1000 -long -base-url "https://sourcegraph.test:3443" -email derp -username derp -password derp -run TestSearch/stream/And/Or_search_expression_queries/Exact_default_count_is_respected_in_OR_queries
```


I've also seen this one come up but not on `main` (yet), which is likely same issue:

https://buildkite.com/sourcegraph/sourcegraph/builds/126709#74e941bd-2149-4433-aa6a-682c4e146570/567-570

> --- FAIL: TestSearch/graphql (2.76s)
--
  | --- FAIL: TestSearch/graphql/global_text_search (0.56s)
  | --- FAIL: TestSearch/graphql/global_text_search/something_with_more_than_1000_results_and_use_count:1000 (0.02s)
  | search_test.go:678: Want at least 1000 match count but got 999

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket, please let us how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
