### ISSUE TITLE
Remove "Recent History" from sidebar on search results page

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#29837]
To better mirror the experience of sourcegrah.com, we should remove "Recent History" from the extension sidebar when a user is on a search results page. Currently, Recent History (Recent Repositories, Recent Files, Recent Searches) are only populated on the homepage of sourcegraph.com. Removing "Recent History" also helps to declutter the sidebar when utilizing filters for search results.

Current state: 
<img width="1292" alt="Screen Shot 2022-01-17 at 4 54 05 PM" src="https://user-images.githubusercontent.com/87138876/149840851-b2812433-2ccf-41fb-90aa-042209e29885.png">

Expected State: 
[Designs](https://www.figma.com/file/EXXvfxVwtCIsrbQez4rPlF/VS-Code-Extension-MLP?node-id=1413%3A3549)

**Comment by abeatrix** [comment]
@jjinnii I'm currently working on this and want to see if you think this will also be a good place to add the Saved Searches to the Recent History Sidebar? I am still bugged by the fact that the users can add save search via the extension but no one to retrieve them  😆

**Comment by abeatrix** [comment]
This is what I have so far. Should I go ahead and add Search Type to the top or wait for your confirmation on Save Searches? 
![image](https://user-images.githubusercontent.com/68532117/150216916-8390da24-e2df-4e35-8e84-91a61309967b.png)

<img width="1866" alt="Screen Shot 2022-01-19 at 1 28 20 PM" src="https://user-images.githubusercontent.com/68532117/150216678-9ac6eb17-0dd6-4b89-936a-f24bad93dfff.png">

**Comment by jjinnii** [comment]
[Added "Saved Search" section](https://www.figma.com/file/EXXvfxVwtCIsrbQez4rPlF/VS-Code-Extension-MLP?node-id=1287%3A2397) in sidebar for _home page view only_. This section will only be exposed once a user has successfully created a saved search and/or their Sourcegraph account already had saved searches after authentication. 

For MVP -- we will not have a pathway to edit a Saved Search within the extension. In the future, we could easily add an edit icon next to the Saved Searches in the sidebar and redirect to sourcegraph.com, but until we are able to measure the volume of users that actually create accounts + save searches via the extension, this is not a priority. 

Recent Files and Recent Repositories will not be exposed until a user has recent file/repo history to be populated.

cc: @abeatrix

**Comment by abeatrix** [comment]
Added Saved Search section for homepage view only for logged in users:
<img width="2258" alt="Screen Shot 2022-01-19 at 4 49 42 PM" src="https://user-images.githubusercontent.com/68532117/150242366-431a5259-fd8d-4a18-b1e5-2757c2935d7a.png">


For non-logged in users
<img width="2258" alt="Screen Shot 2022-01-19 at 4 50 43 PM" src="https://user-images.githubusercontent.com/68532117/150242334-8ed7bb1d-e6d9-4acc-8bce-ba5236e13890.png">

**Comment by jjinnii** [comment]
Thanks @abeatrix ! Is it possible for us to expose just the name (description) of the saved search instead of the full query?

**Comment by abeatrix** [comment]
Thanks for pointing that out @jjinnii I've updated to expose just the name of the searches instead of the full query.

<img width="1814" alt="Screen Shot 2022-01-20 at 7 38 31 AM" src="https://user-images.githubusercontent.com/68532117/150371030-e01192d0-ab1c-4cb4-a93d-d0e55610512b.png">

**Comment by jjinnii** [comment]
Looks great! Thanks @abeatrix . Curious -- what is the "Show more" button in the sidebar? I don't believe I've seen that before. 🤔

**Comment by abeatrix** [comment]
I was trying to display user's 5 most recent repositories but somehow it only display 1 with 4 hiding so clicking on `show more` will show more of the recent repos searches. I will work on it to make sure it displays `5` at the beginning if that sounds good to you?

**Comment by jjinnii** [comment]
@abeatrix That sounds great! I don't particularly care about the flat number (4-6 is fine), but I think having "show more"'s for each section would get annoying interaction -wise fast for the user :)

**Comment by abeatrix** [comment]
Agree! Just to clarify: do you want me to remove the show more button for all sections and set it to a flat number (say 5)? or do you want me to keep it for one of the sections?

**Comment by jjinnii** [comment]
Hmmmm do you think we could just introduce a scrollbar (which we already have), and then just cap results for all sections to 15-20? I think like google, after that point, we don't need to store more history/offer a "show more" to look for a result that's further back. 

To further clarify, the section can show five repo results, after that point a user can scroll down to view up to 15-20 more past repo searches. After that point, there isn't a "show more" or go further back in history. 

@abeatrix thoughts? Would appreciate feedback, as I'm kind of making these decisions on the spot here 😆

**Comment by abeatrix** [comment]
Yea I think what you suggested is great and makes sense. I really do not see the points of going all the way back to to check my search history, and I doubt people will be working with more than 5-10 repos at a time.

**Comment by jjinnii** [comment]
Great! Let's go with that implementation then :)

**Comment by abeatrix** [comment]
Sounds good. Updated as discussed:
<img width="1831" alt="Screen Shot 2022-01-20 at 2 01 39 PM" src="https://user-images.githubusercontent.com/68532117/150429246-836dd113-4d8b-4365-9a73-8995d7e2f2e7.png">
