### ISSUE TITLE
INC-62 Followup: Understand if users that hit this error need to delete/add their services, or if this will be fixed automatically.

### ISSUE THREAD

**Issue by jplahn** [sourcegraph/sourcegraph#29833]
Follow up on action item from https://app.incident.io/incidents/62

**Comment by sashaostrikov** [comment]
Syncs are happening on schedule. If the limits are increased, next sync will be successful without user actions.

@ryanslade Will deleting of some repos/services will trigger new sync or will it be still executed on schedule?

**Comment by ryanslade** [comment]
If the user modifies the list of repos they care about then it will trigger a sync since in the background we are actually updating their external service. Each time an external service is saved it will trigger a new sync for that service.

**Comment by mollylogue** [comment]
Same question for this issue. Is there more to look into here or should we close this out?
