### ISSUE TITLE
Datadog integration roadmap

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#2983]
This issue captures the work (which spans multiple releases) to improve Sourcegraph's integration with Datadog (https://sourcegraph.com/extensions/sourcegraph/datadog-metrics).

(WIP)

Customers:

- https://app.hubspot.com/contacts/2762526/company/1100581370/

**Comment by nicksnyder** [comment]
Going to close this in favor of https://github.com/sourcegraph/sourcegraph/issues/3297
