### ISSUE TITLE
Modify sidebar on extension "homepage" view

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#29841]
For users who have authenticated their account OR performed searches within the extension, the extension sidebar displays search history. However to better mirror the homepage on sourcegraph.com, we need to remove the "Search Reference" section, as well as separate out Recent History into: Recent Searches, Recent Files, and Recent Repositories. 

I am maintaining Search Types (distinct from sourcegraph.com) because I've observed in user testing that many first-time Sourcegraph users used Search Types to get started. 

Current state:

<img width="1289" alt="Screen Shot 2022-01-17 at 4 58 49 PM" src="https://user-images.githubusercontent.com/87138876/149841235-2b891243-de1a-44b1-99eb-db92701a60ea.png">

Expected state: 
[Designs](https://www.figma.com/file/EXXvfxVwtCIsrbQez4rPlF/VS-Code-Extension-MLP?node-id=1287%3A2397)

**Comment by jjinnii** [comment]
Work being captured in related [issue 29837](https://github.com/sourcegraph/sourcegraph/issues/29837)

**Comment by abeatrix** [comment]
Recent history has been separated from the search sidebar:
 
Sidebar on homepage:
<img width="2258" alt="Screen Shot 2022-01-19 at 4 50 43 PM" src="https://user-images.githubusercontent.com/68532117/150242545-57707d5e-6fdd-43da-b5cf-a749a83aad33.png">

Sidebar on search page:
<img width="2258" alt="Screen Shot 2022-01-19 at 4 53 06 PM" src="https://user-images.githubusercontent.com/68532117/150242576-64ae2e22-9b40-4106-91e7-3e709849889b.png">

**Comment by jjinnii** [comment]
Looks great thank you!
