### ISSUE TITLE
Sentry integration roadmap

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#2985]
This issue captures the work (which spans multiple releases) to improve Sourcegraph's integration with Sentry (https://sourcegraph.com/extensions/sourcegraph/sentry).

- https://github.com/sourcegraph/sourcegraph/issues/2628
- https://github.com/sourcegraph/sourcegraph/issues/3177
- https://github.com/sourcegraph/sourcegraph/issues/3536
- https://github.com/sourcegraph/sourcegraph/issues/3305
- https://github.com/sourcegraph/sourcegraph/issues/4149

Customers (not exhaustive):

- https://app.hubspot.com/contacts/2762526/company/419771425 
- https://app.hubspot.com/contacts/2762526/company/693777200

**Comment by nicksnyder** [comment]
@sqs It feels weird to me to have this tracking issue of tracking issues sitting out in the backlog. Can we just close this in favor of those other issues linked in the description?

**Comment by sqs** [comment]
@nicksnyder These are linked from the roadmap at https://docs.sourcegraph.com/dev/roadmap. I think there is value in having 1 place to see "all issues related to Sentry and other context + customer list for Sentry", so I'd like to keep it.
