### ISSUE TITLE
G Suite integration roadmap

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#2987]
This issue captures the work (which spans multiple releases) to improve Sourcegraph's integration with G Suite (Google domain account management, auto-installing the Sourcegraph browser extension for all users in an organization/group, Google Chrome Enterprise, etc.).

(WIP)

**Comment by nicksnyder** [comment]
Closing because this is stale and conversation should be tracked on our actual roadmap https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit
