### ISSUE TITLE
FOSSA integration roadmap

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#2988]
This issue captures the work (which spans multiple releases) to improve Sourcegraph's integration with [FOSSA](https://fossa.io).

(WIP)

**Comment by nicksnyder** [comment]
Closing because this is stale and not in our near term roadmap https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit
