### ISSUE TITLE
Content in diff view bleeds over column boundaries

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#29888]
When a line is long and unsplittable (I assume this is just word wrapping stuff), the line overlaps with the next column in diff view.

<img width="1237" alt="Screen Shot 2022-01-18 at 14 56 42" src="https://user-images.githubusercontent.com/12631702/150025419-4d4b6471-1826-4218-8e60-f4d0ff22be6d.png">

Reproduction [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/69a0bf28da1599985645a62c23a826be4b03073e?visible=5#diff-ab3d7ededa7ce8cf3219f9b968c63451)

**Comment by oleggromov** [comment]
An example of this bug may be found here: https://sourcegraph.com/github.com/angular/angular/-/commit/f593552cfe44ced74a3ec7e95a9ae847094fb632

Enable the split view and then scroll down to `aio/content/examples/service-worker-getting-started/src/app/app.component.html`

**Comment by oleggromov** [comment]
Hi @camdencheek thanks for your report. This has been addressed in the linked PR and will be closed as soon as we merge it.
