### ISSUE TITLE
Get rid of per-binary pop-ups on macOS when using sg start

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/sourcegraph#29908]
When running `sg start` on macOS recently, I and other folks have been seeing multiple pop-up modals (one per binary which changed, IIUC):
```
Do you want the application "worker" to accept incoming network connections?
```
You need to tediously click through all of them. This is an unnecessary bit of friction.

I think this may be because of the firewall settings required for SoC2. I haven’t changed OS versions recently, but I did change that setting. https://discussions.apple.com/thread/7418556

It looks like code-signing the generated binaries should get rid of this modal. https://stackoverflow.com/a/21052254/2682729 

Ad-hoc code-signing can be done with `codesign -s - path/to/binary`. I don't know if that's good enough to fix the pop-up, or one needs to set up a separate code-signing identity and use that to sign the binaries.

Moreover, this happens on ~every recompilation, so making local changes runs into a few pop-ups every time you save a file, depending on how many binaries were recompiled and replaced.

**Comment by varungandhi-src** [comment]
[Official docs:](https://support.apple.com/en-in/HT201642)

> ## Automatically allow signed software to receive incoming connections
>
> [...]
> 
> If you run an unsigned app that is not listed in the firewall list, a dialog appears with options to Allow or Deny connections for the app. If you choose Allow, OS X signs the application and automatically adds it to the firewall list. If you choose Deny, OS X adds it to the list but denies incoming connections intended for this app.
>
> [...]
>
> Some apps check their own integrity when they are opened without using code signing. If the firewall recognizes such an app it doesn't sign it. Instead, it the "Allow or Deny" dialog appears every time the app is opened. This can be avoided by upgrading to a version of the app that is signed by its developer.

**Comment by mrnugget** [comment]
Commenting here to say that I found this on StackOverflow and am not sure whether codesigning will get rid of the popups:
![screenshot_2022-01-20_09 29 45@2x](https://user-images.githubusercontent.com/1185253/150331293-deba93a3-c245-4d3f-8286-298c1378dc9f.png)

**Comment by mrnugget** [comment]
Can confirm. `sudo codesign` requires typing in password and clicking "accept" whenever the binary changes. 

https://user-images.githubusercontent.com/1185253/150340591-96d8d39b-4718-47f3-90cc-52f1f24be894.mp4

**Comment by eseliger** [comment]
According to SO, it should not ask if we directly bind to localhost and not 0.0.0.0, maybe that's something we could try as a temporary thing?

**Comment by mrnugget** [comment]
IIRC, there are a lot of problems when running services inside a Docker container that bind to `localhost`, which is also one of the reasons why we have https://github.com/sourcegraph/sourcegraph/blob/1d7aafd28630cbdad2ad6a3e36016dccb1c9b7c7/dev/check/no-localhost-guard.sh

**Comment by camdencheek** [comment]
What about `127.0.0.1` instead of localhost? It seems that should also work to fix the firewall warnings, and shouldn't trigger any resolver issues.

**Comment by bobheadxi** [comment]
`127.0.0.1` points to the Docker VM in MacOS IIRC, which is not the same as `127.0.0.1` on the host machine, and could cause funny behaviour

**Comment by bobheadxi** [comment]
Closed by https://github.com/sourcegraph/sourcegraph/pull/30747 by @jhchabran I think! 

```
sg start --add-to-macos-firewall
```

**Comment by bobheadxi** [comment]
Reopening because this has become an issue again and is quite problematic. I've hacked around with the firewall and nothing seems to work reliably https://github.com/sourcegraph/sourcegraph/pull/34680 so I think the way forward is to investigate what we can do to not bind on 0.0.0.0 

There's also the codesigning approach, which I poked around with briefly and also doesn't work (mostly you still have to accept the prompt on the first time, or go through a convoluted process to set up a certificate to sign with)

**Comment by bobheadxi** [comment]
That seems worth exploring further! Re: not using `0.0.0.0` if we can do some kind of smart detection we can use `host.docker.internal` instead. Can see which approach is the easiest

**Comment by mrnugget** [comment]
What's the current thinking on using a separate firewall for devs?

**Comment by jjeffwarner** [comment]
@mrnugget IT was okay with devs using a different firewall, I tested out [Vallum](https://www.vallumfirewall.com) and it worked well for me. Once I got it configured I never got the popup again. I am happy to help others get it configured. One person had a problem with the wired connection with BC + Vallum. I think they moved to the signed app approach instead.

**Comment by bobheadxi** [comment]
So it turns out we have a flag called `INSECURE_DEV` that seems to take us 99% of the way to switching everything to listen on 127.0.0.1, and... I don't seem to be getting firewall popups anymore?

Testing https://github.com/sourcegraph/sourcegraph/pull/34714
