### ISSUE TITLE
Unable to clone GitLab repositories with self signed certificate

### ISSUE THREAD

**Issue by KattMingMing** [sourcegraph/sourcegraph#2990]
- **Sourcegraph version:** 3.2
- **Platform information:** Localhost, AWS, GCP
#### Details

Users are unable to clone GitLab repositories with self signed certificates – even when adding the certificate to the GitLab external service configuration as documented here: https://docs.sourcegraph.com/admin/external_service/gitlab#configuration

Implementation details can be found here: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@v3.2.0/-/blob/cmd/repo-updater/repos/gitlab.go#L243

#### Steps to reproduce:
1. Deploy Sourcegraph 3.2 to AWS, GCP, Digital Ocean
2. Add a self signed certificate
3. Configure a GitLab external service (only tested with an on-prem GitLab instance). Add the certificate details to the external service: https://docs.sourcegraph.com/admin/external_service/gitlab#configuration
4. Add the external service
5. Click **Enable** on one of the repositories.
#### Expected behavior:

GitLab external service should use the certificate provided to clone repositories.

#### Actual behavior:

Repositories are discovered, but unable to clone with the following error.

```
repo not found (name=some-host/some/repo/path url=https://git:xxxxxx@some-host/some/repo/path.git notfound=false) because exit status 128 (output follows)
fatal: unable to access 'https://git:xxxxxx@some-host/some/repo/path.git/': SSL certificate problem: unable to get local issuer certificate
```

**Comment by KattMingMing** [comment]
There's various workarounds for this that are not documented:

1. Update **http.sslCAInfo** or **http.sslCAPah** as documented here: https://git-scm.com/docs/git-config#Documentation/git-config.txt-httpsslCAInfo

To point to the certificate that should be trusted

2. Add a ssh key to the sourcegraph/server docker container so that ssh is used instead of https. This needs additional documentation since users have been confused why ssh cloning is not working.

**Comment by MMulero** [comment]
I Have a similar issue. In my case the error is:
**sourcegraph    | 15:49:23       repo-updater | t=2019-04-09T15:49:23+0000 lvl=eror msg="Error processing configured GitLab connection. Skipping it." url=https://git.svb.lacaixa.es error="invalid certificate"**

I tried to add the certificate in Configure a GitLab external service (only tested with an on-prem GitLab instance). Add the certificate details to the external service: https://docs.sourcegraph.com/admin/external_service/gitlab#configuration

Additional I added the CA in OS as explained in:

https://github.com/sourcegraph/sourcegraph/issues/71

**Comment by MMulero** [comment]
> There's various workarounds for this that are not documented:
> 
> 1. Update **http.sslCAInfo** or **http.sslCAPah** as documented here: https://git-scm.com/docs/git-config#Documentation/git-config.txt-httpsslCAInfo
> 
> For example: `git config --global http.sslCAPath /path/to/certs`
> 
> 1. Add a ssh key to the sourcegraph/server docker container so that ssh is used instead of https. This needs additional documentation since users have been confused why ssh cloning is not working.

How do you configure sourcegraph/server docker container so that ssh is used instead of https?

**Comment by KattMingMing** [comment]
@MMulero when adding an external service you'll need change the `gitURLType` to ssh. Example for GitHub below:

```
{
  "url": "https://github.com",
  "token": "PERSONAL_ACCESS_TOKEN",
  "repositoryQuery": [
    "REPO_QUERY"
  ],
  "gitURLType": "ssh"
}
```

Additional documentation can be found here: https://docs.sourcegraph.com/admin/repo/auth#repositories-that-need-http-s-or-ssh-authentication

**Comment by keegancsmith** [comment]
@sourcegraph/core-services so we need to update gitserver so that we git config `http.sslCAInfo` per repo? Alternatively we can document how users can do globally set the git config `http.sslVerify`. Does that sound like the path forward?

**Comment by tsenart** [comment]
> Does that sound like the path forward?

Yep.

**Comment by jjlin** [comment]
> There's various workarounds for this that are not documented:
> 
> 1. Update **http.sslCAInfo** or **http.sslCAPah** as documented here: https://git-scm.com/docs/git-config#Documentation/git-config.txt-httpsslCAInfo
> 
> For example: `git config --global http.sslCAPath /path/to/certs`
> 
> 1. Add a ssh key to the sourcegraph/server docker container so that ssh is used instead of https. This needs additional documentation since users have been confused why ssh cloning is not working.

If you're running this inside the Sourcegraph container, you probably need `git config --system ...` so that the config goes into `/etc/gitconfig` rather than `/root/.gitconfig`. It seems `gitserver` runs `git` commands with a very limited environment that doesn't include `HOME`, so `/root/.gitconfig` won't be found even though `gitserver` is running as root.

So for example, `git config --system http.sslVerify false` if you're not concerned about security, or mount the resulting config file into the Sourcegraph container at `/etc/gitconfig` for persistence.

**Comment by slimsag** [comment]
Had someone else ask about this over support just now. There are two workarounds at present:

1. Configure Sourcegraph to clone repositories from GitLab/etc using SSH by setting `"gitURLType": "ssh"` in the external service configuration, and adding the relevant SSH configuration to the Sourcegraph container: https://docs.sourcegraph.com/admin/repo/auth#repositories-that-need-http-s-or-ssh-authentication

2. Configure Sourcegraph's git usage globally to not verify SSL certificates, by creating a file at `$HOME/.sourcegraph/config/ssh/config` (assuming you’re using the default `--volume $HOME/.sourcegraph/config:/etc/sourcegraph` run command) with the following in it and then `docker restart $CONTAINER`:

```
[http]
sslVerify = false
```

**Comment by keegancsmith** [comment]
I looked a bit into this issue. I think the better solution is to solve https://github.com/sourcegraph/sourcegraph/issues/71 since special casing GitLab feels like it isn't justified for a more general solution (that actually shouldn't be _too_ much work).

**Comment by keegancsmith** [comment]
3.12 will contain an experimental setting `experimentalFeatures/tls.external` which will allow you to turn of TLS/SSL verification for git cloning and external code host communication. We will continue to work on a more general solution for this problem (including adding certificates) in 3.13 which will be tracked in #71.
