### ISSUE TITLE
Code Insights: Show how many dashboards have the current editing insight

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#29943]
## Context

At the moment we have a possible security issue when a user shared a dashboard via public org and other users took one or more insights from this dashboard to their private dashboards. Then if the first user (or any other users actually) takes this previously shared dashboard back other users who took insights from this dashboard still can see those insights. 

But the problem is if some of the users try to edit these insights then these edits will affect the insights in other users' personal dashboards. [See this loom for more details](https://www.loom.com/share/997923648f894abf9ac8bc9ba8dc29fe)

[Related slack thread](https://sourcegraph.slack.com/archives/C02KE7E9GMR/p1642622909035400)

A possible solution to solve this problem for GA release: adding dashboard count where to the edit page of the insight which was included in more than one dashboard and notify in the pre-submit step that these changes will affect dashboards for other users as well.  

## For version 1: 
We can just show the total count, not the dashboard names.

**Comment by unclejustin** [comment]
Do we have this number presently available? Can we get it back in the existing "get insight" query or do we have to make another?

**Comment by Joelkw** [comment]
Needs a new GraphQL node, frontend side is acceptable.

**Comment by Joelkw** [comment]
Should be split into two separate issues by frontend/backend @coury-clark @CristinaBirkel

**Comment by coury-clark** [comment]
API issue #30031

**Comment by AlicjaSuska** [comment]
The [design](https://www.figma.com/file/db3qb0UjYLo9RYFxQYjWXz/Show-how-many-dashboards-have-the-current-editing-insight-%2329943-WIP?node-id=246%3A11) of the popup including information about the dashboards is ready for review.

**Comment by Joelkw** [comment]
closing since we discussed in sync this isn't necessary.

**Comment by vovakulikov** [comment]
@Joelkw I think you closed this one by an accident, no? I think the right one was about the closing issue about creating personal dashboard if a user hasn't created any dashobard yet.

**Comment by Joelkw** [comment]
@vovakulikov good call. moving to TODO because we decided this was a security issue, right?
