### ISSUE TITLE
Add documentation to clarify that users need to add their ssh key to sourcegraph/server

### ISSUE THREAD

**Issue by KattMingMing** [sourcegraph/sourcegraph#2994]
User's often stumble when cloning repositories via ssh.

We should document that users need to add an ssh key to their sourcegraph/server instance and improve the error messages when attempting to clone via ssh without any ssh key.

- [ ] Add documentation #2996 
- [ ] Improve error messages #2997

**Comment by ryan-blunden** [comment]
Closing in favor of two separate issues:

- Add documentation #2996 
- Improve error messages #2997
