### ISSUE TITLE
insights: order capture group series key alphabetically/ascending?

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#29949]
![image](https://user-images.githubusercontent.com/11967660/150233233-a202fd94-5661-4ac3-a8ad-c8a90074610a.png)
The tooltip displays in count order, which is fine, but perhaps the key legend should display alphabetically so that a user can scan and see the versions present and trust the first one is the earliest and the last one is the latest version, in order?

**Comment by unclejustin** [comment]
Leaving a note to account for ordering 1, 2, 9, 10. Such that the order does not come out 1, 10, 2, 9.
