### ISSUE TITLE
Add team page and beta form to post sign-up

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#29944]
Currently, users can join the Organizations on Cloud beta list through a form linked at the top of the site. These form submissions are a valuable source of leads. Additionally, in the future, we will want to allow users to create a team and invite their users to it as part of the sign-up flow.

If we combine these two concepts together we have an opportunity to generate additional leads while experimenting with placement for future functionality. 

Tasks:

- [ ] Create a new wizard step in the post sign-up flow
- [ ] Add the ability to display a Hubspot form when the user requests to be added to the beta
- [ ] Track all activity on this page carefully 

Figma:

https://www.figma.com/file/9KUQex1haXP6BpC2wDgtXC/?node-id=628%3A4251

**Comment by philipp-spiess** [comment]
A couple of thoughts:

- Do we want some kind of animation when a user clicks the "Apply" button? Should the white content box fade out and grow while we simultaneously load the form? I can try to whip up what I have in mind and show it to you as well.
- @rrhyne do you know if there is a different API to embed the form (other than using the stand-alone link we already link to?) I can request access to Hubspot to look for myself but maybe you know the answer quickly and we can avoid that :) 
- The Figma screen shows the content area grow exactly to the height that fits the form. This may not be possible (i.e if HubSpot has origin isolation, we can't inspect it and compute the size). I'll see what I can do though.
- I suppose when they submit the form we need a way either want to go to the next screen (import repos) or change the "Skip this step" button to something that makes it clear that the step was completed. Any idea what we could do if none of this is available (when we can't hook into the form)?

**Comment by philipp-spiess** [comment]
While I’m waiting for access to HubSpot, here's a preview including an example of what I meant by the animation:

https://user-images.githubusercontent.com/458591/151807210-7762626d-f710-4c16-a82b-e1365283e1ea.mov

**Comment by philipp-spiess** [comment]
Okay the animation with the actual form content is proving more difficult than I thought so I've removed it for now but depending on what you think @rrhyne I can try to make it work (I'll need some custom code to measure the form height somewhere offscreen to make a smooth transition). Here's what I got so far:

https://user-images.githubusercontent.com/458591/151831574-e9a846ce-f9ad-4c09-8c5d-6d1ebce6245d.mov

If you have any design feedback, let me know! :-)

**Comment by rrhyne** [comment]
Thought I replied last week... might have lost it. I think I answered anything we didn't talk about in Slack:

Animation:

Perhaps you can transition the apply text and button out, then load the form as is? It would still, pop but it would help users understand what is happening a bit. 

Another idea is to grow the containing div height from top to bottom with a clip-path or similar. This would reveal the form without trying to animate the entire thing. 


> I suppose when they submit the form we need a way either want to go to the next screen (import repos) or change the "Skip this step" button to something that makes it clear that the step was completed. Any idea what we could do if none of this is available (when we can't hook into the form)?

What happens when the form is submitted? Is there a 'thanks for submitting' page?

> Do we need to put this behind a feature flag or a/b test this?

Let's just run it for a bit and look for fall-off in the funnel.

**Comment by philipp-spiess** [comment]
> What happens when the form is submitted? Is there a 'thanks for submitting' page?

![Screenshot 2022-02-01 at 13 19 41](https://user-images.githubusercontent.com/458591/151967423-b922d91a-a60f-421b-9726-4c166e07f971.png)

Yeah in it's current form there's a message similar to this. It's probably reasonable to keep this as-is and avoid further jumping around between the screens (=> I would rather show the user a success message then just moving them on to another screen with no context)

**Comment by rrhyne** [comment]
Awesome. I'm sure we can adjust that message. A few observations:

* Where did "the complete the form below" text come from? Can we hide it after they submit or remove it entirely?
* We seem to have two buttons to move forward: "not right now' and "Skip this step". Can we remove the "Not right now"?
* I believe the prior step underlines should be colored to signal completion
*

**Comment by philipp-spiess** [comment]
cc @rrhyne (In case you didn't get a notification otherwise)

**Comment by rrhyne** [comment]
Thanks... meetings. 

The line of text makes sense for the form page (and is needed), but not after submission. I just checked out hubspot forms and found that we can add a line of text at the top of the form itself. 

Let's remove it from our implementation.

**Comment by rrhyne** [comment]
Ok, let's do something a bit different here... because the user is kind of opting into this form, and it is loooooong, I want to allow each user to quickly move on if they don't want to do this. 

I've updated the design to have skip this step in the top right and use the "Not right now" on the bottom. I think that should make it clear this isn't required while following existing patterns as you point out. 

Does that work for you?

Roger on the step color.
