### ISSUE TITLE
Insights: click to turn on/off a line series

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#29958]
Needs design. 

[Motivated by capture groups insights but should apply to all insights. ](https://sourcegraph.slack.com/archives/C014ZCKMCAV/p1642023166106800)

Provide a way to turn on/off lines on a graph to dig in further. 

The y-axis should update to adjust to the remaining lines (so if you remove a big high-count line, the y-axis might shrink to make it easier to see the others).

**Comment by Joelkw** [comment]
from @AlicjaSuska – we have to decide if we want a select or deselect as the default action. Will share a loom.

**Comment by AlicjaSuska** [comment]
Here is the final design and walkthrough for Turning on/off the lines on the chart. I've implemented the feedback you shared for the first exploration some time ago.
- [Loom](https://www.loom.com/share/1a5e2c81a90f4a589ed5f8b5766f6a8f) - please watch before reviewing
- [Figma](https://www.figma.com/file/fWW7rO9nUVZJEqUZXTMxcX/Click-to-turn-on%2Foff-a-line-series-%2329958?node-id=275%3A1628) - I moved the designs to a new file (to align with the scope of the issue, the old one contained many other topics as well)

I would like to limit the scope of this issue to hover states & tuning the lines on/off and skip the 'bring back all lines' functionality. We could come back to it in the future iteration once we have the sorting feature ready (more info about it in the video).

@Joelkw please let me know if you give a green light from you to split it. Thank you!

Looking forward to your thoughts!

**Comment by AlicjaSuska** [comment]
[Design](https://www.figma.com/file/fWW7rO9nUVZJEqUZXTMxcX/Click-to-turn-on%2Foff-a-line-series-%2329958-%5Bready-for-dev%5D?node-id=246%3A11) is ready for dev.

Scope:
- add hover states: highlighted line (ad data point) + other lines faded out
- add the ability to toggle lines on and off

TBD:
- add 'show all' button - final call to be made by @Joelkw. I recommend implementing it now, but I'm ok with waiting for feedback since it doesn't block the flow.

@unclejustin FYI

**Comment by Joelkw** [comment]
Since we're worried about capacity and it's not blocking, I suggest we hold on the `show all` button for now, and I will actively seek feedback after we ship this to invalidate/prove myself wrong and determine if we need to add it!
