### ISSUE TITLE
GCP SSH Permissions and Service Account Access

### ISSUE THREAD

**Issue by kevinwojo** [sourcegraph/sourcegraph#29993]
Background: https://sourcegraph.slack.com/archives/C02E4HE42BX/p1642707752067900

I manually granted Jason access to the "instance" service account user for managed instances. I suspect there is a cleaner way to do this, but I don't really have a ton of insight into how Sourcegraph manages groups and access for GCP. 

Perhaps this is an IT Ops question or whomever owns our access and control processes?

Just noting this down as my "quick fix" is not sustainable.

**Comment by caugustus-sourcegraph** [comment]
https://cloud.google.com/compute/docs/access/#granting_users_ssh_access_to_vm_instances:

```If the instance is set up to run as a service account, you must also grant the roles/iam.serviceAccountUser role before the member can connect to the instance.```

I modified the gcp-managed@sourcegraph.com role to grant `ServiceAccountUser` permissions unconditionally in the Managed Instances folder. This technically means they can user any service account in that folder, not just the `instance` one, but a) there aren't any other ones except the default and b) this matches their also-unlimited Compute Admin permissions.

![gcp-managed](https://user-images.githubusercontent.com/91073224/151388232-de526726-43e5-40e6-9b81-6be64bb83718.png)

**Comment by caugustus-sourcegraph** [comment]
Work is tracked separately in https://github.com/sourcegraph/customer/issues/664
