### ISSUE TITLE
Delete search stack items

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#30003]
Allow users to:
- [x] individually delete items in the stack ([ProductBoard](https://sourcegraph.productboard.com/feature-board/3965875-notebooks/features/11507178/insights))
  - https://github.com/sourcegraph/sourcegraph/pull/30687
- [ ] Select/unselect one or more items with Cmd+click and...
- [ ] Select a range of stack items with shift+click and bulk deleting selected items with backspace and delete key presses ([ProductBoard](https://sourcegraph.productboard.com/feature-board/3965875-notebooks/features/11605695/insights))

**Comment by fkling** [comment]
> Select a range of stack items with shift+click 

Did you have thoughts on how the "first" entry would be selected? Would people use cmd+click to select one item and then shift+click on the last item to select the range?

I think shift+click is useful, I'm just wondering how it would work in this case. In the contexts where I usually use shift+click, selection is initiated with a normal click. But that is not the case here, a normal click will navigate to entry, and a shift+click in "non-select" mode might even open the entry in a new tab/window.

**Comment by benvenker** [comment]
Hm. I guess was I was actually thinking that the first selection could be made with a normal click. Did you mean that's not how it appears in the prototype, or that there's a technical reason that approach wouldn't work here?

**Comment by fkling** [comment]
More from a technical/UX aspect: Right now clicking an item navigates to that item. But for me selecting and navigating are two different things. Imagine a file browser that opens files on click. You wouldn't want the file to open if all you wanted was to select a range of files... Not saying that this is as bad in our case, but it might be surprising behavior?
I'm just thinking out loud here 🙂

**Comment by benvenker** [comment]
Oh, are you talking about the annotation opening on initial click?

**Comment by fkling** [comment]
No, although now that you mention this, that's also a concern. I think we both might have a different model of how the search stack is working. From what you are saying it looks like clicking on an item in the list won't bring you to corresponding page anymore (e.g. search or file view)?

**Comment by benvenker** [comment]
Ah. Ok so in that case (this is not clear in the prototype really) clicking
on the stack item body (not the link) would select the item. Clicking
directly on the link in the stack item _would_ take you to the
corresponding page (search or file view).

Coury had suggested getting rid of the down chevron that was on the stack
item, whose purpose was to expand/collapse the annotations, but maybe we
should bring that back, for clarity. That way selecting an item would just
select it, no surprises, and you can view or hide annotations with a
separate action. At its core, the stack item should support these actions:

   - Being selected
   - Being deleted
   - Showing/hiding the annotation box
   - Navigating to its linked content (file, search)

I'll update the prototype tonight so that's the represented experience. We
can sync on it quickly tomorrow just to be safe.
