### ISSUE TITLE
Add line range to code block sometimes doesn't work

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#30012]
Often, when I click add line range, the page sort of scrolls down but nothing actually happens and I have to click it twice. This seems to mostly happens after I've already added a couple and am farther down the screen.

**Comment by novoselrok** [comment]
@benvenker Trying to reproduce this bug, but with no success. Can you still reproduce it?

**Comment by benvenker** [comment]
Giving it a shot now

**Comment by benvenker** [comment]
@novoselrok I was able to just now. If it's helpful, try shortening your browser height. It seems to happen most often when the file preview goes below the fold.

**Comment by limitedmage** [comment]
@novoselrok is this obsolete with the new file block experience in #32506?

**Comment by novoselrok** [comment]
Yep, it should be, since we don't have the `Add line range` menu button anymore.
