### ISSUE TITLE
Cookie info is not sent through to HubSpot when signing up to Cloud via oauth

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#30020]
#### Steps to reproduce:

1. Sign up for a cloud account via GitHub or GitLab auth
2. If you have to log in, or approve a connection with Sourcegraph, the cookie values we send in https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/internal/auth/oauth/session.go?L93-94 do not get sent, because those cookies don't exist on GitHub/GitLab. 

I'm not familiar enough with the auth code to implement a fix. I tried implementing a middleware but that didn't work because, again, the request originates from GitHub and doesn't contain the cookie. Appreciate thoughts on how we could make this work. I imagine we could encode this info in the request to GitHub, and pass that info when we return to the sign in page.

@unknwon do you have suggestions on how we could do this?

**Comment by unknwon** [comment]
If the code has been called (https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/internal/auth/oauth/session.go?L93-94), that means the user has been redirected back to Sourcegraph and thus should have cookies (this is our code after all). Have and/or how you confirmed this code has been called after OAuth flow?

**Comment by attfarhan** [comment]
Joe and I found the reason for this. Our cookies have a SameSite policy of `Strict`, so they only get passed in requests within our site. However, this means that when following links to our site, or when getting redirected to our site (which is the case when a user uses OAuth), we do not send the cookie over. Opening a PR to change these values to Lax (pending security approval)
