### ISSUE TITLE
Code Intel panel: General UX issues

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#30022]
Example URL: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@c6df1d96db729f11301e1eac84b814ad7916fa22/-/blob/cmd/frontend/graphqlbackend/batches.go?L486:20#tab=implementations_go

GitHub issue to track some known issues with the Panel UX.

### Loading behavior
Navigating directly to URL with panel open results in a layout shift:

<details>
  <summary>Example</summary>

  ![PanelLoading](https://user-images.githubusercontent.com/9516420/150506559-2fc86722-1eb6-4fa9-b48d-9e204aa05555.gif)

</details>

### Navigating between tabs
There is a noticeable click delay when navigating between tabs. Navigation should be instant, the loading state (spinner) should only be what is used to show loading status. This also seems to be present when opening/closing the panel

<details>
  <summary>Example</summary>

![ClickDelay](https://user-images.githubusercontent.com/9516420/150506807-1807555e-39b9-4695-8058-0fd3e91c2388.gif)

</details>

### Caching between tabs
Requests aren't cached between tabs. This is particularly problematic for large requests. These requests shouldn't change once the user has viewed them, at least for as long as they are on the current page. We should cache these with Apollo so we can immediately show data.

Note: These requests go through the extension host, so it might be difficult to use Apollo

<details>
  <summary>Example</summary>

![PanelRequestCache](https://user-images.githubusercontent.com/9516420/150507687-5816a017-a84f-42aa-a50d-3676a2d7cd5a.gif)

</details>

### Panel is not sticky (https://github.com/sourcegraph/sourcegraph/issues/13722)

Clicking on data such as references should preserve the panel in view, allowing users to maintain their UX state whilst navigating through the list.

Potential PR to solve this: https://github.com/sourcegraph/sourcegraph/pull/30021

Slack thread: https://sourcegraph.slack.com/archives/C01LTKUHRL3/p1642591921027100

<details>
  <summary>Example</summary>

![persistent-find-references-panel-request](https://user-images.githubusercontent.com/9516420/150508107-8c219d72-681b-49e0-8cfe-562abee2147a.gif)

</details>

**Comment by Numbers88s** [comment]
These finding are for the old reference panel. Closing.
