### ISSUE TITLE
Reduce sizing of homepage content to match designs

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#30048]
Current implementation of the homepage in VS Code extension matches sourcegraph.com exactly. However, due to the sidebar of VS Code, there is less screen real estate (width), causing the search examples to wrap on a user's default view. (unless they have the sidebar hidden, which users likely will not do) 

The [designs](https://www.figma.com/file/EXXvfxVwtCIsrbQez4rPlF/VS-Code-Extension-MLP?node-id=1371%3A2976) have a reduced sizing of the homepage content (search examples, Watch & Learn video), icon, etc.).

**Comment by abeatrix** [comment]
@jjinnii does this look alright?
<img width="1904" alt="Screen Shot 2022-01-24 at 12 35 07 PM" src="https://user-images.githubusercontent.com/68532117/150860524-68fd27c3-5735-4d50-ac38-896a8c4c3840.png">

**Comment by jjinnii** [comment]
@abeatrix Would you be able to send a screenshot of what this view looks like at around 1440px? :) It's hard for me to tell without knowing how wide the screen is in that screenshot you just sent!

**Comment by jjinnii** [comment]
@abeatrix  Never mind! I downloaded the new version from TJ's slack message, and seeing the updated spacing: 

Design nit -- is the font for the copy below the search examples perhaps smaller than my [design](https://www.figma.com/file/EXXvfxVwtCIsrbQez4rPlF/VS-Code-Extension-MLP?node-id=1287%3A2397)? 


<img width="1440" alt="Screen Shot 2022-01-24 at 3 06 06 PM" src="https://user-images.githubusercontent.com/87138876/150864963-5e175528-f4c1-42e5-96ec-b581afdc3781.png">


We tend to avoid having one word in a line of text -- designers call them widows :) Obviously, it'll change depending on the responsive screen width, but since 1440px will be the default for many laptop users, I want to double-check on this screen width!

**Comment by abeatrix** [comment]
>  is the font for the copy below the search examples perhaps smaller than my design?
I set the font size to the font size of the VS Code editor, I have updated it to use the font size of VS Code (see picture below, shown at screen size 1440px) but should I update it to match the font size of your design which is 14px? 

![image](https://user-images.githubusercontent.com/68532117/150885481-3b8355aa-ad2b-47ea-b83b-32e285a0a182.png)

**Comment by jjinnii** [comment]
@abeatrix  Nope, that looks much better, thank you for the attention to detail!

**Comment by abeatrix** [comment]
You're very welcome!
