### ISSUE TITLE
Document steps to remove repositories from cloud

### ISSUE THREAD

**Issue by jplahn** [sourcegraph/sourcegraph#30045]
Work with @airamare01 on defining steps to remove repositories from cloud.

This is a follow up from https://github.com/sourcegraph/customer/issues/609 and the associated post mortem https://docs.google.com/document/d/1dDfzudK6rCyzgKYdfb4ee_PT_05gnyx3_HApp46VQEs/edit#.

- Define a process for removing repositories from Cloud, documenting:
- Owner: Stompy Mwendwa
- Which team is responsible for performing this process 
- What is the recommended action for removal of:
  - Public repositories
  - Public forks of private repositories
  - Public repositories made private
  - Public repositories that are also added by other users/organizations
  - Private repositories
- For each case above, how do we do this:
  - Instruct the user how to do it themselves
  - Wait for existing automation
  - Access prod-db 
  - Use API
  - Manage allowlists / blocklists?
- How can we verify repository data was removed from gitserver / zoekt / other components?

**Comment by jplahn** [comment]
We're tentatively planning to get to this issue this week. If we do, @indradhanush will reach out to you @airamare01 .

**Comment by airamare01** [comment]
Sure thing @jplahn. Ready to rock and roll

**Comment by airamare01** [comment]
@ryanslade I can add you as a reviewer for the PR for the doc in a while to help catch any errors I might have made.

**Comment by airamare01** [comment]
@ryanslade @mollylogue @jplahn 

Hey folks. Just a heads up that I pushed the PR and would love to have your thoughts and input on V1.

**Comment by indradhanush** [comment]
@airamare01 Is there a link to the PR that I can take a look at?

**Comment by airamare01** [comment]
https://github.com/sourcegraph/handbook/pull/2487

cc: @indradhanush

**Comment by airamare01** [comment]
Closing this with [this](https://github.com/sourcegraph/handbook/pull/2487) merged PR

**Comment by mollylogue** [comment]
@airamare01 Thanks for your work on this! 🙏
