### ISSUE TITLE
Replace "Three ways to search"  Watch & Learn video with VS Code extension video

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#30046]
Related to issue #29700 - @muratsu when you've recorded the video, please share with @abeatrix so that we can replace the Watch & Learn video prior to the release.

**Comment by abeatrix** [comment]
Video by Murat: https://youtu.be/w6pz4GPL80g

**Comment by abeatrix** [comment]
@jjinnii Link and Preview image updated as below:
<img width="1904" alt="Screen Shot 2022-01-25 at 9 54 10 AM" src="https://user-images.githubusercontent.com/68532117/151032163-d052e374-ef5e-4b10-a210-e19602195e15.png">
Please let me know if changes are required

**Comment by jjinnii** [comment]
@abeatrix Is it at all possible to have the preview image start at :01 seconds? The white bg for dark theme is a bit high contrast, and I think it'd be great to have a human face for the video :) (lol Murat will be famous)

**Comment by abeatrix** [comment]
Yea this is just a screenshot I took of the video. Is this the image you want to use? 😆 
![image](https://user-images.githubusercontent.com/68532117/151033412-731ce4f3-1729-4fb6-8bb5-4d7088aaaa35.png)

**Comment by jjinnii** [comment]
Yes! @muratsu front and center

**Comment by abeatrix** [comment]
<img width="1904" alt="Screen Shot 2022-01-25 at 10 13 12 AM" src="https://user-images.githubusercontent.com/68532117/151034939-d8e34c0d-f5a4-43ce-bfa6-5dff412839f9.png">
@jjinnii thoughts?

**Comment by muratsu** [comment]
🙈🙈🙈🙈

**Comment by jjinnii** [comment]
I think that looks a lot better! Don't love that the play button covers Murat's face lol, but it works a lot better than the white image IMO.

**Comment by abeatrix** [comment]
@jjinnii I can move Murat to the side 😏 
![image](https://user-images.githubusercontent.com/68532117/151036421-c16603a1-7788-4db2-b29f-9f2220e85416.png)
