### ISSUE TITLE
Get rid of client/browser/src/browser

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#3005]
This was added as an abstraction layer for Safari, which we don't support anymore, and to wrap APIs in Promises, which we get through the `browser` API (#3200).

The way they wrap APIs is highly problematic and inconsistent. For example:

https://github.com/sourcegraph/sourcegraph/blob/master/client/browser/src/browser/permissions.ts

uses global `chrome.permission` APIs with inconsistent and questionable handling of global `chrome` not being defined (e.g. in Phabricator integration or Firefox). Some functions cause a "Cannot read property permissions of undefined" error which is currently spammed as unhandled rejections when running tests. Other functions will never settle the returned Promise  if `chrome` is not defined, which doesn't seem like a good solution either. ~~We need to think about a consistent, predictable behaviour here and prevent the unhandled rejections. Example: When asking if we are permitted to do something that is only restricted in Chrome extensions, if `chrome` is not defined, we could return `true`. If it is only _allowed_ in Chrome extensions, we would return `false` in that case.~~

We should 
- migrate references to src/browser/* to using the `browser` API directly
- as we do that, make sure they are never called from the Phabricator integration, so the hacky `if (chrome)` checks are not needed

**Comment by lguychard** [comment]
> Phabricator integration

I would like to eliminate the possibility of calling code that relies on browser extension APIs in the case of the Phabricator integration - I think this could be achieved if the Phabricator integration had a different `PlatformContext` (the same context is used for the Phabricator integration and the browser extension currently).

This would avoid having `if (isPhabricator || isInPage)` (where `isInPage` and `isPhabricator` are globals) scattered in the code.

> Firefox

Unintuitively enough, the global `chrome` _is_ defined on Firefox (it is to be understood as "the browser chrome", not "the Chrome browser").

**Comment by felixfbecker** [comment]
Note I didn't actually verify what environments had `chrome` defined, the one environment where I noticed this was testing, and then I saw the inconsistency and the dangling Promises which are definitely not good

**Comment by lguychard** [comment]
No, definitely not. Just wanted to clarify :)
