### ISSUE TITLE
insights: persisted global capture groups loading state should match normal loading state

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#30071]
Both of these insights have not run yet, but they show different states: 

![image](https://user-images.githubusercontent.com/11967660/150630047-c23a97ec-4306-413b-89da-422eba84ce31.png)

Right side: capture group that hasn't run yet. Left side: normal global search insights. 

We should show the same loading state for both, that the capture group insight is processing, *not* "no data to display." This will mislead users to thinking their query was wrong because they would expect both to show the loading state. 

I realize there may be some backend complexity in how we expose loading state from compute.

**Comment by unclejustin** [comment]
From slack, this appears to be a backend issue after all. Re-assigning to @coury-clark and updating labels.
