### ISSUE TITLE
Add notes/annotations to search stack items

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#30078]
The ability to tie descriptions to stack elements while in the stack.

Important note: these annotation must be pulled into the Notebook, below the item they're associated with, so they appear in chronological order when the Notebook is  created.
More in [ProductBoard](https://sourcegraph.productboard.com/feature-board/3965875-notebooks/features/11507186/insights)

**Comment by fkling** [comment]
Annotations have been added in https://github.com/sourcegraph/sourcegraph/pull/31248 but they are rendered above the item in the notebook. Do you have a strong preference/reason to show them below?
