### ISSUE TITLE
Permissions sync error rate has no data in Grafana

### ISSUE THREAD

**Issue by indradhanush** [sourcegraph/sourcegraph#30088]
Link to panel: https://sourcegraph.com/-/debug/grafana/d/repo-updater/repo-updater?viewPanel=100130&orgId=1&from=now-7d&to=now

![image](https://user-images.githubusercontent.com/2682729/150739249-b4802424-4933-4e2b-ba58-6b76ac36bae9.png)

Blocks https://github.com/sourcegraph/sourcegraph/issues/28724.

- **Sourcegraph version:** 
- **Platform information:** 

#### Steps to reproduce:

1.
2.

#### Actual behavior:

If would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are not [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

**Comment by indradhanush** [comment]
Looks like it fixed itself. 

https://sourcegraph.com/-/debug/grafana/d/repo-updater/repo-updater?viewPanel=100130&orgId=1&from=now-7d&to=now

![image](https://user-images.githubusercontent.com/2682729/152850255-50ad5a4e-1422-4903-8a0a-f93f55a4f473.png)

**Comment by bobheadxi** [comment]
@indradhanush this is likely caused by no errors showing as no data. To fix this, you want to add `monitoring.PanelOptions.ZeroIfNoData` to this observable panel: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/monitoring/monitoring/panel_options.go?L249-254
