### ISSUE TITLE
Sourcegraph badge not rendered correctly on a public repo - request times out

### ISSUE THREAD

**Issue by pavelnikolov** [sourcegraph/sourcegraph#30089]
- **Sourcegraph version:** Public open-source project
- **Platform information:**  MacOS, Chrome 
#### Steps to reproduce:

1. Use your browser of choice and navigate to https://github.com/graph-gophers/graphql-go
2. Wait for a few seconds and you will see that the Sourcegraph badge is broken.

#### Expected behavior:
Expected to see Sourcegraph's badge rendered correctly.

#### Actual behavior:
<img width="836" alt="Screen Shot 2022-01-24 at 9 46 12 am" src="https://user-images.githubusercontent.com/441740/150741900-914cb0ab-6e93-4eb1-980f-2c76740d5de2.png">

The code used to render the badge seems correct according to your docs:
```
[![Sourcegraph](https://sourcegraph.com/github.com/graph-gophers/graphql-go/-/badge.svg)](https://sourcegraph.com/github.com/graph-gophers/graphql-go?badge)
```
however, the response from https://sourcegraph.com/github.com/graph-gophers/graphql-go/-/badge.svg is always:
```
Error: HTTP 408: Request Timeout
```

If would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are not [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

**Comment by umpox** [comment]
@pavelnikolov Thanks for raising this!

This seems to be working as expected now, so closing this issue. It was possibly related to some downtime on our side, we'll keep an eye on it and reopen if this continues to be a problem
