### ISSUE TITLE
Investigate frequently triggered alert "0+ rate of growth of update queue length over 5 minutes for 2h0m0s"

### ISSUE THREAD

**Issue by indradhanush** [sourcegraph/sourcegraph#30110]
The alert has started getting triggered for the last few days. And although processing of sync jobs appears to remain unaffected, we need to dig into the root cause of this. 

- [x] Add debug logs for resetting counter #30103
- [x] Feature flag jitter in repo update interval #30154 

/cc @sourcegraph/source

**Comment by daxmc99** [comment]
Related https://github.com/sourcegraph/sourcegraph/issues/30151

**Comment by jplahn** [comment]
@indradhanush can we close this?

**Comment by indradhanush** [comment]
@jplahn Sorry I missed this in my notifications. I wouldn't close this yet, as we have a silenced alert (mentioned in #30151) in cloud and the issue has not been resolved. I'll move this out of in-progress.
