### ISSUE TITLE
Make Go test failures easily accessible in UI

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/sourcegraph#30115]
I ran into a test failure with a PR where I kept only seeing "PASS:" in the UI, and yet at the end, it said that there was a failure. https://buildkite.com/sourcegraph/sourcegraph/builds/126913#5e397eb1-5948-4e21-9e69-e319ddc75691/6

This is because the build log in the UI was truncated:

> Warning: This log has exceeded the 1MB display limit. Below we are only showing the last 1MB of output.
>
> See <a href="https://buildkite.com/docs/guides/managing-log-output" target="_blank">https://buildkite.com/docs/guides/managing-log-output</a> for tips on managing your log output.

There is still a way to download the log, which is good. But not having the actual error show up in the UI felt a bit confusing to me. I ended up retrying the job multiple times, thinking that there was some failure on the buildkite side, so retrying would make the failure go away. I also started looking at other PRs and was about to post a question in Slack if anyone else had seen some spurious failure.

It would be nice if the names of the failing tests were printed again at the bottom, or if the passing tests were suppressed (or shown concisely). Regardless of the specific fix, it would be nice to be able to easily identify failures in the build output.

**Comment by bobheadxi** [comment]
There are **7,443 log lines** in `TestWorkerHandlerNonRetryableFailure`! I can't even open the section in the UI without causing a browser slowdown, and at a glance it seems to be the biggest emitter of log lines in this step. cc @mrnugget @efritz based on git blame

![image](https://user-images.githubusercontent.com/23356519/150832505-e74242a6-4a67-4c99-81f6-6458b8987dc9.png)

A better summary would be good though - I'd also add that you can use `sg ci logs` to find failures:

```
❯ sg ci logs --build 126913 | grep FAIL
          {"node":{"__typename":"BatchSpec","id":"QmF0Y2hTcGVjOiI5YnBjMGtxaGVrYSI=","originalInput":"\nname: my-unique-name\ndescription: My description\n'on':\n- repositoriesMatchingQuery: lang:go func main\n- repository: github.com/sourcegraph/src-cli\nsteps:\n- run: echo 'foobar'\n  container: alpine\n  env:\n    PATH: \"/work/foobar:$PATH\"\nchangesetTemplate:\n  title: Hello World\n  body: My first batch change!\n  branch: hello-world\n  commit:\n    message: Append Hello World to all README.md files\n  published: false\n","parsedInput":{"name":"my-unique-name","description":"My description","on":[{"repositoriesMatchingQuery":"lang:go func main"},{"repository":"github.com/sourcegraph/src-cli"}],"steps":[{"run":"echo 'foobar'","container":"alpine","env":{"PATH":"/work/foobar:$PATH"}}],"changesetTemplate":{"title":"Hello World","body":"My first batch change!","branch":"hello-world","commit":{"message":"Append Hello World to all README.md files"},"published":false}},"creator":{"id":"VXNlcjox","databaseID":1,"siteAdmin":false},"namespace":{"id":"VXNlcjox","databaseID":1,"siteAdmin":false},"applyURL":"/users/testuser-11/batch-changes/apply/QmF0Y2hTcGVjOiI5YnBjMGtxaGVrYSI=","viewerCanAdminister":true,"createdAt":"2022-01-24T16:20:54Z","expiresAt":"2022-01-31T16:20:54Z","diffStat":{"added":0,"deleted":0,"changed":0},"appliesToBatchChange":null,"supersedingBatchSpec":null,"allCodeHosts":{"totalCount":0,"nodes":[]},"onlyWithoutCredential":{"totalCount":0,"nodes":[]},"changesetSpecs":{"totalCount":0,"nodes":[]},"state":"FAILED","workspaceResolution":{"state":"COMPLETED"},"startedAt":"2022-01-24T14:41:54Z","finishedAt":"2022-01-24T16:11:54Z","failureMessage":"Failures:\n\n* failure message\n","viewerCanRetry":true}}
          {"node":{"__typename":"BatchSpec","id":"QmF0Y2hTcGVjOiI5YnBjMGtxaGVrYSI=","originalInput":"\nname: my-unique-name\ndescription: My description\n'on':\n- repositoriesMatchingQuery: lang:go func main\n- repository: github.com/sourcegraph/src-cli\nsteps:\n- run: echo 'foobar'\n  container: alpine\n  env:\n    PATH: \"/work/foobar:$PATH\"\nchangesetTemplate:\n  title: Hello World\n  body: My first batch change!\n  branch: hello-world\n  commit:\n    message: Append Hello World to all README.md files\n  published: false\n","parsedInput":{"name":"my-unique-name","description":"My description","on":[{"repositoriesMatchingQuery":"lang:go func main"},{"repository":"github.com/sourcegraph/src-cli"}],"steps":[{"run":"echo 'foobar'","container":"alpine","env":{"PATH":"/work/foobar:$PATH"}}],"changesetTemplate":{"title":"Hello World","body":"My first batch change!","branch":"hello-world","commit":{"message":"Append Hello World to all README.md files"},"published":false}},"creator":{"id":"VXNlcjox","databaseID":1,"siteAdmin":false},"namespace":{"id":"VXNlcjox","databaseID":1,"siteAdmin":false},"applyURL":null,"viewerCanAdminister":true,"createdAt":"2022-01-24T16:20:54Z","expiresAt":"2022-01-31T16:20:54Z","diffStat":{"added":20,"deleted":4,"changed":10},"appliesToBatchChange":null,"supersedingBatchSpec":null,"allCodeHosts":{"totalCount":1,"nodes":[{"externalServiceKind":"GITHUB","externalServiceURL":"https://github.com/"}]},"onlyWithoutCredential":{"totalCount":1,"nodes":[{"externalServiceKind":"GITHUB","externalServiceURL":"https://github.com/"}]},"changesetSpecs":{"totalCount":2,"nodes":[{"__typename":"VisibleChangesetSpec","type":"BRANCH","id":"Q2hhbmdlc2V0U3BlYzoiNXdvNGZycE1OZHYi","description":{"baseRepository":{"id":"UmVwb3NpdG9yeTox","name":"repo-1-1"}}},{"__typename":"VisibleChangesetSpec","type":"BRANCH","id":"Q2hhbmdlc2V0U3BlYzoiNE44WmE2REI2b3gi","description":{"baseRepository":{"id":"UmVwb3NpdG9yeTox","name":"repo-1-1"}}}]},"state":"FAILED","workspaceResolution":{"state":"COMPLETED"},"startedAt":"2022-01-24T14:41:54Z","finishedAt":"2022-01-24T16:11:54Z","failureMessage":"Validating changeset specs resulted in an error:\n* 2 changeset specs in repo-1-1 use the same branch: refs/heads/conflicting-head-ref\n","viewerCanRetry":true}}
  --- FAIL: TestQueueIndexesInferred (0.00s)
  --- FAIL: TestQueueIndexesForPackage (0.00s)
  FAIL
  FAIL  github.com/sourcegraph/sourcegraph/enterprise/internal/codeintel/autoindex/enqueuer     0.108s
  FAIL
```

This ran very quickly for me

**Comment by varungandhi-src** [comment]
Yep, once I downloaded the log, I could figure it out.

> - I'd also add that you can use sg ci logs to find failures:

Nice! If the build number is accessible in the environment, it would be cool to put the exact command (which one can copy-paste) at the bottom of the log.

> There are 7,443 log lines in TestWorkerHandlerNonRetryableFailure! I can't even open the section in the UI without causing a browser slowdown, and at a glance it seems to be the biggest emitter of log lines in this step

I saw that `go test` supports JSON output, maybe that output can be truncated if the test succeeded?

**Comment by bobheadxi** [comment]
The excessive log lines caused a prolonged build incident today since it obfuscated the test results: https://github.com/sourcegraph/sourcegraph/pull/30296
