### ISSUE TITLE
Determine how to monitor for code waiting for semaphore

### ISSUE THREAD

**Issue by jjeffwarner** [sourcegraph/sourcegraph#30148]
From retro on Jan 24, 2022.
Find a way to monitor for code that is waiting for a semaphore and is not running. Would be very useful for monitoring and alerting. [Suggested resource from the Slack channel](https://www.youtube.com/watch?v=7hg4T2Qqowk).

**Comment by keegancsmith** [comment]
@ggilmore I think this is related to the block profiler idea? What are our next steps? Is this issue worth keeping open?

**Comment by jjeffwarner** [comment]
@ggilmore you were looking at some options on this, is the work still viable or should we close it out for now?

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket, please let us how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
