### ISSUE TITLE
compute-search: StreamMinimalRepos fails to parse regexp

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#30140]
Given a query (on k8s-dogfood) such as the following: `patterntype:regexp #!/usr/bin/env python([0-9]\.[0-9]+) archived:no fork:no count:all repo:^ghe\.sgdev\.org/sourcegraph/fink-fink$@af22462da1399944b2a6541013101670e1e700ff` the `compute` GraphQL search returns the following error:
```
"ERROR: invalid regular expression: invalid embedded option (SQLSTATE 2201B)"
```

The error seems to originate from Postgres.

[Here is a trace](https://sourcegraph.grafana.net/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22grafanacloud-sourcegraph-traces%22,%7B%22refId%22:%22A%22,%22queryType%22:%22traceId%22,%22query%22:%2226a5313baca10bbf%22%7D%5D)

**Comment by coury-clark** [comment]
Unable to reproduce on stream / webapp. [Here is an API console query with a repro](https://k8s.sgdev.org/api/console#%7B%22variables%22%3A%22%22%2C%22operationName%22%3A%22Run%22%2C%22query%22%3A%22query%20Run%20%7B%5Cn%20%20compute(query%3A%5C%22patterntype%3Aregexp%20%23!%2Fusr%2Fbin%2Fenv%20python(%5B0-9%5D%5C%5C%5C%5C.%5B0-9%5D%2B)%20archived%3Ano%20fork%3Ano%20count%3Aall%20repo%3A%5Eghe%5C%5C%5C%5C.sgdev%5C%5C%5C%5C.org%2Fsourcegraph%2Ffink-fink%24%40af22462da1399944b2a6541013101670e1e700ff%5C%22)%20%7B%5Cn%5Ct__typename%5Cn%20%20%20%20...%20on%20ComputeMatchContext%20%7B%5Cn%20%20%20%20%20%20repository%20%7B%5Cn%20%20%20%20%20%20%20%20name%5Cn%20%20%20%20%20%20%20%20id%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20commit%5Cn%20%20%20%20%20%20path%5Cn%20%20%20%20%20%20matches%20%7B%5Cn%20%20%20%20%20%20%20%20value%5Cn%20%20%20%20%20%20%20%20environment%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20variable%5Cn%20%20%20%20%20%20%20%20%20%20value%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%7D)

**Comment by coury-clark** [comment]
Appears to be a regression caused by https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/20a35de21ec2f7dd93bf3a299337cf2e2b6dd959?visible=2#diff-230367d20c7312daee3a634f56b38230R214

Note: this is not part of 3.36 or 3.36.1

**Comment by rvantonder** [comment]
On the search side, we should improve validation around this issue: 

[query](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+%28%3Fi:%23%21/usr/bin/env+python%28%5B0-9%5D%5C%5C.%5B0-9%5D%2B%29%29&patternType=regexp)
