### ISSUE TITLE
Audit trail for repository status changes

### ISSUE THREAD

**Issue by jjeffwarner** [sourcegraph/sourcegraph#30147]
From the Jan 24, 2022 retro - generate an audit trail for repository status changes since Gitserver is the source of truth for repos. This would make it easier to recover from repos missing due to status changes.

**Comment by keegancsmith** [comment]
I think we lost track of this. To be honest, given we haven't done anything along these lines I think it isn't worth clogging up the backlog with it and close this out. WDYT?
