### ISSUE TITLE
New panel to show how many repos are blocked from indexing

### ISSUE THREAD

**Issue by jjeffwarner** [sourcegraph/sourcegraph#30146]
From the retro on Jan 24, 2022. Additional panel to show how many repos are blocked from indexing as a troubleshooting and alerting tool.

**Comment by keegancsmith** [comment]
This sounds related to https://github.com/sourcegraph/sourcegraph/issues/29746. Is this still useful @stefanhengl?

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket, please let us how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
