### ISSUE TITLE
Code Insights: Implement limited access ('demo') mode for the code insight pages

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#30165]
## Context 

In case of customers haven't purchased code insights we still have to provide a demo mode for code insights. 
You can find [designs about this here](https://www.figma.com/file/EFgTP7gpdpQSEo1n4FUfsW/In-product-landing-page-WIP?node-id=1130%3A8493). 

Edited Mar 2 with updates [from RFC](https://docs.google.com/document/d/1WIInNUMtgOPIeiIONGios2_y67CSkkZr0WtFtU4h_IY/edit#heading=h.qp2pvnk0jby)

**Non-purchasing instance users can:**

1. Create up to N=2 code insights with no more than 3 data series on a single insight. 
  a. Excepting capture group insights 
  b. This means the instance can never have >N insights
2. Still see live preview when creating insights
3. All share a single dashboard that is globally available instance-wide

**Free users cannot:**

1. Make any of their own dashboards or keep any insights private – they get a single dashboard everyone can see
2. Create any Insights running over all repositories

## Tech notes

It seems like we should create another FE/BE class implementation where we disable some actions and operations according to the rules above. We also should extend a base interface with permissions model on FE to be able to specify UI (disable buttons, provide tooltip explanation texts) 

We gonna provide this by license flag. If the user doesn't have a proper license for code insights we are going to provide a special demo backend implementation for our UI. [Example how batch changes does license checking ](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@c39158187e8b56a5befe236a2727000b94589c61/-/blob/client/web/src/enterprise/batches/list/BatchChangeListPage.tsx?L141:11)

**Comment by coury-clark** [comment]
Just as a note, I believe the current plan is we don't actually have in-product enforcement for these things:
* Customers in this mode can't create more than N (probably N=2) insights
* Customers in this mode cant' create insight dashboards.
* Customers in this mode can have only one predefined insight dashboard (probably it's going to be the "All insights" virtual dashboard)
* All operations over the dashboard should be disabled (create, delete, assign insights, ...etc)

**Comment by vovakulikov** [comment]
Related RFC about limited access mode https://docs.google.com/document/d/1WIInNUMtgOPIeiIONGios2_y67CSkkZr0WtFtU4h_IY/edit#heading=h.qp2pvnk0jby

**Comment by unclejustin** [comment]
@Joelkw @AlicjaSuska 

How do you want to handle a user trying to create more than 2 insights?

- Disable the add insight button?
- Redirect to dashboards page if they try to navigate directly?
- Just add a warning message on the creation page and disable that?

**Comment by Joelkw** [comment]
@unclejustin I think this is covered in the designs [here](https://www.figma.com/file/EFgTP7gpdpQSEo1n4FUfsW/In-product-landing-page-%5Bdone%5D?node-id=1130%3A8493) and [here](https://www.figma.com/file/EFgTP7gpdpQSEo1n4FUfsW/In-product-landing-page-%5Bdone%5D?node-id=1130%3A8493) – looks like disabling a button with the tooltip message.

**Comment by unclejustin** [comment]
After speaking with @vovakulikov we are going to break this up into smaller issues and use this one as kind of a tracking issue. Will update description as we define the new issues.

**Comment by unclejustin** [comment]
Closing this issue in favor of the newly created smaller issues.
