### ISSUE TITLE
Add dotcom page showing license expiration status

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#3017]
See retrospective filed at https://docs.sourcegraph.com/dev/retrospectives/customer_license_expiration for context

Customers:

- https://app.hubspot.com/contacts/2762526/company/419771425

**Comment by sd9** [comment]
This is for https://app.hubspot.com/contacts/2762526/company/1100581370/ too.

**Comment by sd9** [comment]
Does https://app.hubspot.com/contacts/2762526/company/1100581370/ need this too?
