### ISSUE TITLE
insights: update onboarding docs to reflect current state

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#30195]
A lot has changed in Code Insights since September when we last updated the onboarding docs. We need to use this time [to update the dev docs](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/doc/dev/background-information/insights/backend.md)

**Comment by Joelkw** [comment]
@coury-clark was this the dev docs PR you sent out (in which case, can you or I link and close) or was this something else?

**Comment by Joelkw** [comment]
cc @coury-clark  Just checking on the above as I'm looking at our iteration plans!

**Comment by felixfbecker** [comment]
@sourcegraph/code-insights-backend this is in "Done" but not closed, should it be closed or should the status be changed?

**Comment by felixfbecker** [comment]
Ping @sourcegraph/code-insights-backend
