### ISSUE TITLE
v3.36.2 patch release to revert poor onboarding UX change

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#30197]
@sourcegraph/delivery I am requesting a v3.36.2 patch release be made for:

* https://github.com/sourcegraph/sourcegraph/pull/30193

See https://docs.google.com/document/d/1yz_YkUrrS6p6QMeSbuLVmosYJjjXLKCJ8kU2C5tCBAM/edit# for more details.

I have already merged this into the 3.36 branch and tested there, and created a v3.36.2 changelog entry on that branch. https://github.com/sourcegraph/sourcegraph/commit/5aed7ed7fe66278f527451d2d07aafeceab7a139

---

The intent of the questions below is to ensure we keep Sourcegraph high quality and [only create patch releases based on a strict criteria.](https://handbook.sourcegraph.com/engineering/releases#patch-releases) If you can answer yes to many or most of these questions, we will be happy to create the patch release.

I have read [when and why we perform patch releases](https://handbook.sourcegraph.com/engineering/releases#patch-releases) and answer the questions as follows:

> Are users/customers actively asking us for these changes and cannot wait until the next full release?

Yes.

> Are the changes extremely minimal, well-tested, and low risk such that not testing as we do in a full release is OK?

Yes.

> Is there some functionality completely broken that warrants redacting the prior release of Sourcegraph and advising users wait for the patch release?

No, CS has been advised already.

> This will interrupt our regular planned work and release cycle, taking one full working day of our time, and will take up all of our site admin's valuable time by asking them to upgrade or producing noise for them if they don't need to upgrade.
>
> Do you believe the changes are important enough to warrant this?

Yes.

> Patch releases are a signal we can do something better to improve the quality of Sourcegraph. Have you already scheduled a call (or created a google doc) to perform a [retrospective](https://about.sourcegraph.com/retrospectives) and identify ways we can improve?

Yes, we have some process improvements already in mind from this.

---

**For the [release captain](https://handbook.sourcegraph.com/engineering/releases#release-captain)** - after reviewing this request:

- [ ] **Comment on this issue** with a decision regarding the request.
- [ ] If approved, **add it to a patch release**:
  - If there is [already an upcoming patch release](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+), add the listed commits alongside a link to this issue
  - If there is no upcoming patch release, create a new one:
    - Update [`dev/release/release-config.jsonc`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/release/release-config.jsonc) with the patch release in `upcomingRelease` and `releaseDate` (and open a PR to `main` to update it)
    - `yarn release tracking:issues`
    - Add the listed commits alongside a link to this issue to the generated [release tracking issue](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+)
- [ ] **Comment and close this issue once the relevant commit(s) have been cherry-picked into the release branch**.

**Comment by caugustus-sourcegraph** [comment]
Patch is approved
