### ISSUE TITLE
Extensions item not always displayed

### ISSUE THREAD

**Issue by joebowbeer** [sourcegraph/sourcegraph#302]
- **Sourcegraph version:** "Sourcegraph.com"
- **Platform information:** Various

#### Description

I don't always see the Extensions menu at Sourcegraph.com.

On OSX, I only see it in Safari, but not in Chrome (69.0.3497.100) or Firefox.
On iPad, I see it in Safari and Chrome (69.0.3497.105).

View of Chrome on iPad attached. This item is missing on OSX.

![c8f871d1-57c2-4290-83d9-5f5d4868940b](https://user-images.githubusercontent.com/28679/46555506-6a5f1300-c898-11e8-8030-20ec02c56e32.jpeg)

**Comment by sqs** [comment]
This was caused by a config mistake that accidentally re-added a feature flag to disable the Extensions link. It is fixed.
