### ISSUE TITLE
Code insights backend: default to `archived:no` and `fork:no` filters on backend searches

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#30204]
Related to #24023, which was resolved just with our help text. Ultimately, it was not a priority to resolve this, but long term we should implement these defaults in some way. 

We should make it so we default to `archived:no` and `fork:no`. Right now, we default to yes. The search GUI defaults to no for reasons described in the linked ticket, and we should match that default.

**Comment by leo** [comment]
Wrong username, I think!

**Comment by felixfbecker** [comment]
(tentatively assigning @leonore )

**Comment by coury-clark** [comment]
Closed by https://github.com/sourcegraph/sourcegraph/pull/35271
