### ISSUE TITLE
Logging for Unavailable API Route

### ISSUE THREAD

**Issue by benjaminwgordon** [sourcegraph/sourcegraph#30208]
- **Sourcegraph version:** 3.35.1

Multiple customer instances have reported the following error message repeated indefinitely in the frontend logs after upgrading to 3.35.1:
`API no route: POST /.internal/saved-queries/list-all from`

It may be associated with some page load latency issues, but I haven't confirmed this across all instances affected by this yet.

Is this expected, or indicative of a real error?

**Comment by camdencheek** [comment]
Hi @benjaminwgordon! Thanks for the report. That endpoint was removed when we removed query runner.

I'm not sure why it would still be getting hit, but I'll do some looking. As far as I can tell, it was already unused when I removed the endpoint.

**Comment by benjaminwgordon** [comment]
Entirely possible, I'll check in with my customers now that I know this is due to a removed route.

**Comment by camdencheek** [comment]
Thanks! I expect it's a little unlikely given there are two separate customers that have this issue, but it's not entirely impossible that our recommendation for something at somepoint was just "hit this API".

**Comment by camdencheek** [comment]
Summary from our sync chat:

It seems possible that the customers this affects are using custom overlays which refer to `query-runner`, causing a pod to still exist in the cluster that shouldn't. This might also be why our test cluster has a `query-runner` pod. If that is the case, the `query-runner` process is likely polling `frontend` at that now-nonexistant endpoint, causing these error logs. Ben will follow up with the customers and the owner of our test cluster infra to see if this is the cause.

**Comment by benjaminwgordon** [comment]
Resolved, both customers had running instances of query-runner, which should no longer be running after its deletion.  Resolved by deleting the deployment and ensuring the manifests were properly removed from the deployment repositories
