### ISSUE TITLE
Maintain scroll location after user clicks into a search result 

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#30211]
#### Expected behavior:

As a user, if I navigate to a file from search results and return to the Sourcegraph search tab, I would expect to maintain my scroll position from before I clicked into the search result.

#### Actual behavior:

Currently, if a user clicks into a search result and returns to the Sourcegraph search tab, a user is returned to the top of the search results. This is a problem because I lose the context of the results I was viewing before I navigated to a file. 

#### Additional context:
Request made from [internal feedback](https://sourcegraph.slack.com/archives/C02E3HHDZ98/p1643129138043300).

**Comment by olafurpg** [comment]
A related issue got fixed for the web version not too long ago https://github.com/sourcegraph/sourcegraph/issues/28845
