### ISSUE TITLE
Feature request: Navigation hierarchy or trail

### ISSUE THREAD

**Issue by amarsiingh** [sourcegraph/sourcegraph#3025]
#### Feature request description

- When a user is going through source code and navigating definitions or references, it would be nice to have a trail or hierarchy at the top, so that user can go back to the original point where he/she started code search from.

#### Is your feature request related to a problem? If so, please describe.

- currently, once a user starts search through the code, particularly if they're unfamiliar with or new to the repo, they will find it difficult to get back to the original point in navigation history.

#### Describe alternatives you've considered.

- remembering the original file I was into to go back to.

**Comment by attfarhan** [comment]
Hey @amarsiingh, thanks for raising this! We have another issue open for this same feature request here: https://github.com/sourcegraph/sourcegraph/issues/2065. I'll add your comments there and close this one out.
