### ISSUE TITLE
A/B test: New getting started tour

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#30258]
### Motivation
  
We are trying to determine if the new getting started tour does a better job of retaining users and convincing them to sign up. 

### Test

* The control is the current homepage design which offers examples and a brief search language popover. This content is not available elsewhere in the product. 
* The test version is a pervasive todo based widget that can be seen from multiple areas of the application.
  
### Metric and experimental design
  
**Metric:** We will evaluate the retention rate of test users and the sign-up conversion ratio of test users. 

**Smaller significant change:** A 5% improvement in the retention rate of users who search (currently 11.9%) would mark an improvement. This means a retention rate of 12.4% would mark a significant improvement at a 5% threshold. 

**Significance threshold:** 5% 
**Duration/size:** 50K users in the test would be sufficient to accurately gauge results. Calculator here: https://www.evanmiller.org/ab-testing/sample-size.html. This means the test should run for about 1.5 to 2 weeks with current traffic levels. 
  
  
#### Descriptive analytics

[Search user retention](https://analytics.amplitude.com/sourcegraph/chart/txy3fjl) and signup conversation rates. 

 
### Flag

getting-started-tour  `AB-test/getting-started-tour`

### Other resources
- [Cloud users traffic chart](https://analytics.amplitude.com/sourcegraph/chart/rxb1ebs?source=search)

**Comment by erzhtor** [comment]
Hey, @rrhyne, to clarify, does this mean you want to enable feature flag (onboarding) to 50% of the traffic? cc @attfarhan

**Comment by erzhtor** [comment]
Enabled on 50% of the traffic.

**Comment by erzhtor** [comment]
Hey, @rrhyne! 

1. Do you know how we can measure this? Maybe there is an already existing chart/metrics to check?
2. I'm [trying to analyze how it is performing](https://analytics.amplitude.com/sourcegraph/notebook/2u5hmri?source=breadcrumbs) and it seems like, as @ryankscott noticed, we lack a few more metrics/events to fully understand the funnel performance:
    1. such as when user sees tour
    2. when user closes tour
With that said, not many people seem to interact with a getting started tour, at least from what I got based amplitude charts above, but again would be interesting to see the full funnel `seen > (interacted or dismissed) > (completed or dismissed) > (CTA clicked or dismissed or restarted)`

WDYT, should be our next steps on this?
cc @ryankscott
