### ISSUE TITLE
create-snapshot.ts script doesn't work with instance without any prior snapshot

### ISSUE THREAD

**Issue by michaellzc** [sourcegraph/sourcegraph#30266]
## Description

https://github.com/sourcegraph/deploy-sourcegraph-managed/blob/main/util/create-snapshot.ts doesn't create snapshot as expected when the managed instance has no prior manual snapshot.

## How to reproduce

When the `terraform.tfvars` looks something like

```tf
project              = "sourcegraph-managed-michael"
domain               = "michael.sourcegraph.com"
machine_type         = "n1-standard-8"
data_disk_size       = 250 # GB
load_balancer_target = "red"
deployments          = ["red"]
disks = {
  red = { from_snapshot = null }
}
snapshots = {}
public = true
```

It will produce the following output without making any rewrite to the tfvars file

```
../util/create-snapshot.ts red
Preparing snapshot upgrade-from-3-36-2 from default-red-data-disk
comby: performing rewrite on 'terraform.tfvars'
comby: match='snapshots = { :[snapshots] }'
comby: rewrite='snapshots = {
  :[snapshots]
  upgrade-from-3-36-2 = { from_disk = "default-red-data-disk" }
}'
terraform.tfvars
comby: generating diff
comby: no diffs were generated
```

However, if you do have at least one prior snapshot

```tf
project              = "sourcegraph-managed-michael"
domain               = "michael.sourcegraph.com"
machine_type         = "n1-standard-8"
data_disk_size       = 250 # GB
load_balancer_target = "red"
deployments          = ["red"]
disks = {
  red = { from_snapshot = null }
}
snapshots = {
  upgrade-from-3-35-2 = { from_disk = "default-red-data-disk" }
}
public = true
```

it works

```
Preparing snapshot upgrade-from-3-36-2 from default-red-data-disk
comby: performing rewrite on 'terraform.tfvars'
comby: match='snapshots = { :[snapshots] }'
comby: rewrite='snapshots = {
  :[snapshots]
  upgrade-from-3-36-2 = { from_disk = "default-red-data-disk" }
}'
comby: generating diff
diff --git a/michael/terraform.tfvars b/michael/terraform.tfvars
index a027e30..6e11da7 100644
--- a/michael/terraform.tfvars
+++ b/michael/terraform.tfvars
@@ -7,5 +7,8 @@ deployments          = ["red"]
 disks = {
   red = { from_snapshot = null }
 }
-snapshots = {}
-public    = true
+snapshots = {
+  upgrade-from-3-35-2 = { from_disk = "default-red-data-disk" }
+  upgrade-from-3-36-2 = { from_disk = "default-red-data-disk" }
+}
+public = true
```

## Workaround

I haven't used comby before nor have the bandwidth to look into its [syntax](https://comby.dev/docs/syntax-reference#match-and-rewrite-syntax).

For now I will just hardcode one to get the script working...

## Fix

This line is trying to match the `snapshots = { ... }` in `terraform.tfvars`, maybe it can't match an empty map?

https://github.com/sourcegraph/deploy-sourcegraph-managed/blob/5b25781e8464558239e7b4ab5c7cb74697e96c5f/util/create-snapshot.ts#L19

**Comment by michaellzc** [comment]
I am not sure who's the owner of this script. The last person touched it was Robert, feel free to remove the `team/devx` label if I'm wrong.

**Comment by kevinwojo** [comment]
This is a known issue! https://github.com/sourcegraph/customer/issues/442 I ran into it as well.

**Comment by michaellzc** [comment]
Duplicate https://github.com/sourcegraph/customer/issues/442
