### ISSUE TITLE
remove bootstrap style import `@import 'bootstrap/scss/custom-forms`

### ISSUE THREAD

**Issue by gitstart-sourcegraph** [sourcegraph/sourcegraph#30280]
## Problem statement
We depend on Bootstrap styles in our global styles a lot. But we don't plan to move forward with Bootstrap because we're working on our design system called Wildcard. To ease the transition to our styles and gain more control over visual changes, we want to move Bootstrap styles that we need into our codebase and eventually drop Bootstrap dependency.

## Ref
https://github.com/sourcegraph/sourcegraph/issues/29200

## Success criteria
1. All highlighted imports has been removed
2. All css rules currently used from the imports are now available in style sheets

## Implementation details
let's also remove the following imports and copy CSS rules that we need to our CSS files:
1. remove the import `@import 'bootstrap/scss/custom-forms` from global `index.scss` file
2. copy styles used in codebase into new global `custom-forms.scss` file within `client/branded/src/global-styles`
3. import file into global `index.scss`

Note: some style rules from `@import 'bootstrap/scss/custom-forms` are already being modified by styles in `forms.scss`

## Time estimate

- Pull requests with ~450 lines changed should take **5 hours** at maximum. Ping the reviewer in the spec pull request if time-consuming changes are required.
- Split the work into multiple pull requests if the total diff is bigger than 450 lines of code.

**Comment by oleggromov** [comment]
Set "in progress" state on Frontend Platform team board to reflect the current status.
