### ISSUE TITLE
Increase Cloudflare Timeout

### ISSUE THREAD

**Issue by danieldides** [sourcegraph/sourcegraph#30327]
[Long GraphQL](https://sourcegraph.com/api/console#%7B%22operationName%22%3A%22ChangesetRepos%22%2C%22query%22%3A%22query%20ChangesetRepos(%24query%3A%20String!)%20%7B%5Cn%20%20search(query%3A%20%24query%2C%20version%3A%20V2)%20%7B%5Cn%20%20%20%20results%20%7B%5Cn%20%20%20%20%20%20results%20%7B%5Cn%20%20%20%20%20%20%20%20__typename%5Cn%20%20%20%20%20%20%20%20...%20on%20Repository%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20...repositoryFields%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20...%20on%20FileMatch%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20file%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20path%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20repository%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20...repositoryFields%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%5Cn%5Cnfragment%20repositoryFields%20on%20Repository%20%7B%5Cn%20%20%20%20id%5Cn%20%20%20%20name%5Cn%20%20%20%20url%5Cn%20%20%20%20externalRepository%20%7B%5Cn%20%20%20%20%20%20%20%20serviceType%5Cn%20%20%20%20%7D%5Cn%20%20%20%20defaultBranch%20%7B%5Cn%20%20%20%20%20%20%20%20name%5Cn%20%20%20%20%20%20%20%20target%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20oid%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%7D%5Cn%22%2C%22variables%22%3A%22%7B%5Cn%20%20%5C%22query%5C%22%3A%20%5C%22file%3Acomposer.json%20count%3A999999%5C%22%5Cn%7D%22%7D) queries are experiencing Cloudflare timeouts and returning nasty Cloudflare 504 HTML errors in the GraphQL API testing box. This is creating a misleading and poor user experience.

[Slack Conversation](https://sourcegraph.slack.com/archives/CMBA8F926/p1643332369518989)

We should (as an enterprise customer) be able to increase the timeout for `sourcegraph.com` utilizing the `Change Proxy Read Timeout setting` in Cloudflare. 

Looks like maybe we can set it with [Terraform](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/zone_settings_override#string-values).

**Comment by daxmc99** [comment]
@sourcegraph/search-core Is there any concern here with DDos? Increasing the timeout sounds like it could expose us to more intensive graphQL queries. 

cc @sourcegraph/security for visibility.

**Comment by tsenart** [comment]
> @sourcegraph/search-core Is there any concern here with DDos? Increasing the timeout sounds like it could expose us to more intensive graphQL queries.

We are already exposed to heavy queries, it's just that we time out at *some point*. There's no search rate limiting in place, or API rate limiting for that matter, which I think is a more robust solution that choosing and arbitrary point to time-out a heavy query. How does one know the optimal point? I don't think there is one.

The query linked is a "exhaustive query" (i.e. count:9999999), so by definition it may need lots of time to complete. We have a big DDoS blindspot already without proper rate limiting, so increasing this timeout doesn't make it worse as I currently see it.

**Comment by eseliger** [comment]
this could be another user running into this: https://github.com/sourcegraph/sourcegraph/issues/30734

**Comment by daxmc99** [comment]
Set directly via Cloudflare API to `300` 
https://api.cloudflare.com/#zone-settings-change-proxy-read-timeout-setting

**Comment by daxmc99** [comment]
The above query now completes.
