### ISSUE TITLE
code-insights: enable snapshotting for individual stories

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#30338]
## Context 

Hey team! The frontend platform team started looking into ways to limit our Chromatic spending that went out of hand.

It's a high-priority task. And as a first remediation measure, we propose [disabling snapshotting all stories by default](https://github.com/sourcegraph/sourcegraph/pull/30331). Snapshotting can be enabled for an individual story [by adding `disableSnapshot: false` to story parameters](https://www.chromatic.com/docs/ignoring-elements#ignore-stories). That way, it becomes a more conscious decision, and engineers can decide what's important to snapshot.

## Action required

We ask you to allocate time to go through stories that your team owns and explicitly enable snapshotting for important stories. 

_Bonus points for stories optimization_: instead of having a separate story of each variant of a small component — merge them into one story that [shows all component permutations](https://storybook.sgdev.org/?path=/story/wildcard-button--all-buttons) and enable snapshotting only for this story. It decreases the number of snapshots and makes the Chromatic diff easier to review.

**Comment by valerybugakov** [comment]
@sourcegraph/code-insights, could you share an estimate of when you might be able to look into this issue?

**Comment by vovakulikov** [comment]
@valerybugakov I think it should be feasible to resolve this by the end of this week. I will take a look at this shortly (tomorrow morning Moscow time) 😉 . Thanks for mentioning it seems I lost it in many other GH notifications sorry.

**Comment by unclejustin** [comment]
@valerybugakov hah! @vovakulikov beat me to it! But I should be able to look into this today (Central time). Hopefully it will be ready for Vova to review tomorrow 💪

**Comment by valerybugakov** [comment]
@vovakulikov, @unclejustin, thank you!

**Comment by felixfbecker** [comment]
@sourcegraph/code-insights-frontend before we add this to our iteration with 3 days left, what's your size estimate of this task?

**Comment by vovakulikov** [comment]
@felixfbecker It should be just 1 according to our estimation scale. By I pass it to Justin since he took this one

**Comment by felixfbecker** [comment]
Okay. If you feel confident that we can still do it this iteration after the work we have planned, we can append it to the iteration plan (i.e. move it to "Todo"), but I see this as lower priority than the other issues we still have on the plan.

**Comment by vovakulikov** [comment]
@felixfbecker this issue has been passed to review a few hours ago. Sorry that we hadn't moved this in todo before (it slipped from me). What do you mean by `than the other issues we still have on the plan`? Justin is assigned for this issue and I don't see other issues for this iteration that we have at the moment on Justin.

**Comment by felixfbecker** [comment]
Not currently assigned to Justin, but I see we do have multiple frontend issues still in review _and_  in todo, and it's already end of Thursday (i.e. only 1 day left in the iteration). So I want to make sure that before we add anything _new_ to the iteration, we first check whether more important issues are still on track and if not redistribute those before jumping on this issue.
