### ISSUE TITLE
search: enable snapshotting for individual stories

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#30336]
## Context 

Hey team! The frontend platform team started looking into ways to limit our Chromatic spending that went out of hand.

It's a high-priority task. And as a first remediation measure, we propose [disabling snapshotting all stories by default](https://github.com/sourcegraph/sourcegraph/pull/30331). Snapshotting can be enabled for an individual story [by adding `disableSnapshot: false` to story parameters](https://www.chromatic.com/docs/ignoring-elements#ignore-stories). That way, it becomes a more conscious decision, and engineers can decide what's important to snapshot.

## Action required

We ask you to allocate time to go through stories that your team owns and explicitly enable snapshotting for important stories. 

_Bonus points for stories optimization_: instead of having a separate story of each variant of a small component — merge them into one story that [shows all component permutations](https://storybook.sgdev.org/?path=/story/wildcard-button--all-buttons) and enable snapshotting only for this story. It decreases the number of snapshots and makes the Chromatic diff easier to review.

## Progress
- [x] #30369
  - web/enterprise/code-monitoring
  - web/enterprise/searchContexts
  - web/savedSearches
  - web/search/home
  - web/search/panels
  - web/search/results/StreamingSearchResults
  - search-ui

- [x] #30467
  - web/search/notebook

- [x] #30627
  - web/search/results/sidebar
  - web/search/Search Stack

**Comment by limitedmage** [comment]
I'll own the following components:
- web/enterprise/code-monitoring
- web/savedSearches
- web/searchContexts
- web/search/home
- web/search/panels
- web/search/results/StreamingSearchResults
- search-ui

@novoselrok Can you please own 
- web/search/notebook

@fkling Can you please own
- web/search/results/sidebar
- web/search/Search Stack

**Comment by valerybugakov** [comment]
@fkling, @novoselrok, @limitedmage, could you share an estimate of when you might be able to close this issue?

**Comment by novoselrok** [comment]
The notebooks part is done, and I think https://github.com/sourcegraph/sourcegraph/pull/30369 just has to get merged.

**Comment by valerybugakov** [comment]
@novoselrok, thanks! 🙌 I missed the PR since it wasn't linked to this issue.

**Comment by valerybugakov** [comment]
@novoselrok, I thought it would be in a separate PR. Got it 👍
