### ISSUE TITLE
"Can't perform a React state update on an unmounted component" error on Bitbucket Server PR view

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#3035]
Bitbucket Server version: 15.5.1

- Navigate to a file diff on a Bitbucket Server PR
- Witness errors in console: 
![image](https://user-images.githubusercontent.com/1741180/55224984-e582ff80-5211-11e9-87b0-38da4f607ae9.png)

Code intelligence hovers and code view toolbar buttons seem to be working OK, but there is likely a real problem there.

**Comment by felixfbecker** [comment]
I guess this was caused by async MutationObserver events and is now fixed that this code is removed

**Comment by felixfbecker** [comment]
It also may be fixed by #3191
