### ISSUE TITLE
Create a cron job to monitor repo syncing issues

### ISSUE THREAD

**Issue by jplahn** [sourcegraph/sourcegraph#30360]
See https://github.com/sourcegraph/customer/issues/622#issuecomment-1023219379 

If possible, we want to create a cron job to monitor the status of repo syncing to avoid relying on the customer to alert us when things are broken. This is a temporary solution until we work out a better, long term strategy with the Delivery team.

**Comment by indradhanush** [comment]
For posterity, here's the DB query I've been using to check for errors for the customer linked above:

```
select * from gitserver_repos as g left join repo as r on r.id = g.repo_id where g.last_error is not null and r.deleted_at is null order by g.updated_at;
```

As long as this query returns no matching rows we're sure that all is good. A cron job could be as simple as a bash script exec-ing into the docker container running postgres and executing this query. But getting that information out in case the query returns non-matching rows would be slightly time consuming. I haven't researched any way to send emails at the moment.

**Comment by jplahn** [comment]
Closing this for now. Will re-open if we move forward with a cron job or we'll create a new issue for the solution we decide to proceed with.

**Comment by mollylogue** [comment]
Can anyone give me context on why this was closed? It seems that the customer wants us to do this as a part of a follow-up to https://github.com/sourcegraph/customer/issues/622. This was just mentioned in that issue again and I'm not sure why we closed this without implementing it?
