### ISSUE TITLE
Decouple migrations: Testing plan for deployment changes

### ISSUE THREAD

**Issue by caugustus-sourcegraph** [sourcegraph/sourcegraph#30362]
https://github.com/sourcegraph/sourcegraph/issues/25257 and https://github.com/sourcegraph/sourcegraph/issues/25256 will be adding the new migrator container to docker-compose and Kubernetes deployments. Due to the special nature of this change, we're planning some extended testing.

## Test scenarios
For all these situations, set `NEW_MIGRATIONS=true` on the frontends if https://github.com/sourcegraph/sourcegraph/pull/29144 is not already merged. This will prevent the frontend from trying to run migrations.

Before and after tests, confirm the values in the schema_migrations table (**Note** this instruction may be incorrect, we may need to check migration_logs instead) and watch the logs of the migrator container itself for unexpected errors. A curl command against the site every few seconds could also be handy.

Keep an eye towards the UX of this change - the migrator code itself is well-tested, so we're focusing here on the experience of a customer deploying this change. Deployments may be running directly by an administrator (`kubectl apply` style) or in a CI pipeline where manual intervention is difficult.

When restarting frontends, "no impact" means there may be a warning message but that the container should be healthy and no crashloops or downtime is expected.

### Docker-compose
- [x] Clean install of 3.37 release
- [x] Install 3.36.0, upgrade to 3.37, confirm OOB migration fix is present
- [x] Install 3.36.0, upgrade to 3.37 using a slow migration (2+ minutes)
- [x] Install 3.36.0, upgrade to 3.37 using a broken migration, then resolve the problem by editing migration_logs and finish upgrade

### Kubernetes
- [x] Clean install of 3.37 release in Kubernetes with 4 frontend containers running. Repeat this test several times to gain confidence that we've eliminated the previously-seen race conditions.
- [x] Install 3.36.0, upgrade to 3.37, confirm OOB migration fix is present
- [x] Install 3.36.0, run 3.37 migrator as a standalone job, restart frontend (still on 3.36) and confirm no impact, upgrade frontend to 3.37
- [x] Install 3.36.0, upgrade to 3.37 with a slow migration and 4 frontend containers running
- [x] Install 3.36.0, upgrade to 3.37 with a broken migration and 4 frontend containers running. Resolve the problem and finish upgrade
- [x] Install 3.36.0, upgrade to 3.37 with a broken migration and 4 frontend containers running. Downgrade to 3.36 and confirm no impact.
- [x] Install 3.36.0, run 3.37 migrator as a standalone job with a slow migration. Restart frontend while the frontend runs and confirm no impact.
- [x] Install 3.36.0, run 3.37 migrator as a standalone job with a broken migration, restart frontend (still on 3.36) and confirm no impact, resolve the problem and finish upgrading to 3.37
- [x] Clean install of 3.37 release using non-privileged overlays
- [x] Clean install of 3.37 release using very slow-to-startup DB's (maybe add a sleep command so that they don't return ready until 5 minutes has passed)

**Comment by caugustus-sourcegraph** [comment]
No major issues seen.

**QoL requests:**
- Add logging to migrator when running add-log commands (no output currently seen)
- Add logging to frontend containers when waiting on migrator to complete

**Doc updates needed:**
- Improve example shown in https://docs.sourcegraph.com/admin/how-to/dirty_database#3-add-a-migration-log-entry - customers need to use ["add-log", "-db=<schema>", "-version=<version"]

**Docker-compose:**
- _Problem_: Customers can experience downtime due to a failed migration if they are upgrading all containers at once instead of running the migration as a standalone event. See discussion: https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/684#discussion_r802516291
  This can be avoided in the future by upgrading docker-compose versions and using `service_completed_successfully` conditions.

  _Fix_: Customers can prevent this behavior by performing migrations before upgrading the rest of the stack.

**Kubernetes:**
- _Problem_: Customers may have difficulty finding logs from the migrator during a failed migration.
  Running `kubectl logs <frontend pod>` showed ```Error from server (BadRequest): container "frontend" in pod "sourcegraph-frontend-69f4b68d75-w98lx" is waiting to start: PodInitializing```.
  You need to specify kubectl logs <frontend pod> -c migrator` in order to get the actual logs.

  _Fix_: Doc update to help customers know what command to run to find the logs

- _Problem_: Running the migrator to fix a failed migration is cumbersome
  Customers will need to run the migrator with the `add-log` command, then run it again with `up` to resume migrations. It will be tempting for customers to modify their existing initContainer for the `add-log` command, but the frontend will crash after that completes if there are still pending migrations.

  _Fix_: Encourage customers to run the `add-log` command as a standalone Job, or by temporarily adding a second initContainer

**Comment by efritz** [comment]
@caugustus-sourcegraph Thanks for the updates! I'll handle updating some of these items in #31366 and #31367 this week.

This **doesn't** include updating docker-compose upgrade instructions to encourage them to perform the migration prior to the upgrade (the fix in the docker-compose section).

Two open questions to help me finish up:

- What other documents (besides the dirty database/new migrator docs) should we mention how to find migrator logs? Specifically in the k8s upgrade operations guide?
- Is there a behavior difference you'd recommend for making the add-log/up process less cumbersome? Could you suggest another workflow we could bake into the migrator (e.g., such as supplying it with a list of ids you fixed which combines the add-log/up operations into one "deploy")?

**Comment by caugustus-sourcegraph** [comment]
@efritz 
> What other documents ... Specifically in the k8s upgrade operations guide?

Yeah, that's the only other one I can think of! Adding it to the steps here, maybe? https://docs.sourcegraph.com/admin/install/kubernetes/update#steps

> behavior difference

Not that I can think of! Now that I think about it, it's just a good idea to keep recommending that the `add-log` command is run as a standalone migrator instance, as the docs say. Otherwise every frontend replica will write its own log (?).

**Comment by caugustus-sourcegraph** [comment]
Closing this out - all the work mentioned above is either completed or tracked in https://github.com/sourcegraph/sourcegraph/issues/31367
