### ISSUE TITLE
Highlight variables

### ISSUE THREAD

**Issue by alex-bender** [sourcegraph/sourcegraph#3037]
Hello!
Here is a feature request -- it seems that code would be more readable with variable highlighting like in picture provided.

![image](https://user-images.githubusercontent.com/3628862/55225527-81fdcf80-521b-11e9-940b-83c8fe5b858b.png)

So on text selection (word) automatically would be highlighted same words in current scope (function, class, global, ...)
Thanks!

Probably this one is duplicate for https://github.com/sourcegraph/sourcegraph/issues/1283 but I'm not sure.

**Comment by chrismwendt** [comment]
This is a duplicate, but I'm going to copy your nice screenshot to https://github.com/sourcegraph/sourcegraph/issues/1283 :smiley:
