### ISSUE TITLE
Keybinding support for notepad

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#30394]
## Keybindings to support
So far, we've identified several:

~- [ ] a: Add selected range in file or search result OR, if nothing selected add search or add file (from search results or file page), depending on context~
Had to change a: above because of some technical issues around there almost always being a line selected. Instead, we're going to give users a choice of whether to add the file or the selected range. There will be a UI affordance for this, but also key commands, below:
- [ ] a[s, f]: "a" will not be a precursor keybinding that will signal the user wants to copy a file results OR a file range (we can't know which easily). **a -> f** will save the file, **a -> r** will save the range 
- [ ] d: Delete selected inbox items
- [ ] i: Focus top Inbox item
- [ ] t (or right arrow on selected, left arrow to close): open annotation box of focused item
- [x] Shift+Left click: Select a range of Inbox items
- [x] Cmd+Left Click: Select/deselect individual Inbox items
- [ ] e: toggle stack open or closed
- [ ] Add key commands to key command menu (triggered on shift + ? on .com)

**Comment by lguychard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Search-Product-61302e38f801dc0012e2e050/issues/sourcegraph/sourcegraph/30394?planning-poker) with ZenHub @rvantonder @limitedmage @camdencheek @marisak @benvenker @novoselrok @fkling

**Comment by fkling** [comment]
For clarification: It looks like `a[s,f,r]` and `e` are supposed to be global shortcuts, where only `e` is probably always available and `a[s,f,r]` is available when there actually is an item to add.

The others should only trigger when focus is inside notepad itself?

**Comment by benvenker** [comment]
I was thinking “I” would be global but now that we’re default showing the first item maybe that doesn’t make sense or isn’t necessary

**Comment by fkling** [comment]
Should we close this for now? @benvenker

**Comment by benvenker** [comment]
I'll move to unplanned.

**Comment by camdencheek** [comment]
Closing since notepad is gone
