### ISSUE TITLE
soc2: audit trail of PR reviews 

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#30396]
In the context of GN-104, we need to make sure that all PRs are reviewed before getting merged. Technically, the GitHub setting on the repository enforces that and prevents any exception to the rule. 

But providing the evidence that all PRs were reviewed is hard because we don't have an audit trail of that setting being changed in the admin, nor traces of anyone having used admin privileges to merge one. 

To fix that, similarly to #30278, we could log reviews and keep the issue open if a review has been skipped without a proper explanation.

**Comment by jhchabran** [comment]
@bobheadxi is that something you could take on as you're already working on the process, assuming of course we all agree on the solution before anything else.

**Comment by bobheadxi** [comment]
@jhchabran  I thought the acceptance checklist would include a "I have ensured my changes have been thoroughly peer-reviewed" - https://github.com/sourcegraph/sourcegraph/pull/30278 would cover it by default in that case. Would that work?

**Comment by jhchabran** [comment]
@bobheadxi you're right, it would and I suppose we can consider the PRs as the audit trail. Thanks for catching this 🙏  

I think in that case, the only remaining thing to do is to record when a PR is merged without a review at all if someone used his admin privileges. I will open up a new issue to avoid any confusion.

**Comment by jhchabran** [comment]
@bobheadxi If the author does not tick the acceptance checklist because they cannot get a review, that will create an exception that will get logged. It works as long as people are following the process. 

How hard would it make sure that any merge without review even with the box ticked, creates a ticket in the audit trail? That would add more validity to our system.

**Comment by bobheadxi** [comment]
> How hard would it make sure that any merge without review even with the box ticked, creates a ticket in the audit trail? That would add more validity to our system.

If we don't need to check for a _review approval_, the payload includes `review_comments: number` which I can check is >0 which indicates a PR likely has been reviewed. I will add that as an auto-closing issue - do you think that will work @jhchabran ?

**Comment by jhchabran** [comment]
Alright, I think it's worth it then, AFAIU that's a very obvious case that the auditor will seek to inspect.
