### ISSUE TITLE
Fallback to basic-code-intel preventing display of go to def button in some cases

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#3039]
I noticed this because of [browser extension e2e failures](https://buildkite.com/sourcegraph/sourcegraph/builds/30218#8ce1baeb-0dc2-4ce3-a639-bd4f58cce9db) when trying to deploy the browser extension, but it's reproducible on sourcegraph.com too:

- Visit https://sourcegraph.com/github.com/gorilla/mux/-/compare/5ab525f4fb1678e197ae59401e9050fa0b6cb5fd...3ceedf6401c1e0e9c5df5245354b94b1505091ef#diff-7907dc0efec1833675561b8c7f402e59R41
- Click on the `typ` token
- Witness the hover tooltip never displays a hover content or go to def button:
![image](https://user-images.githubusercontent.com/1741180/55240805-095a3b80-523a-11e9-976d-b417239d287d.png)
- Click on `regexType`, then on `typ` again, witness a hover content + go to def button is now displayed:
![image](https://user-images.githubusercontent.com/1741180/55240889-2ee74500-523a-11e9-85ce-5e9029c28eb8.png)

I believe this is due to the implementation of [`withFallback()`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph-go/-/blob/src/lang-go.ts#L547-567) in sourcegraph/sourcegraph-go

**Comment by chrismwendt** [comment]
Fixed by disabling the behavior for now in https://github.com/sourcegraph/sourcegraph-go/pull/58
