### ISSUE TITLE
Search-based intel: accurate local code navigation

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#30393]
Currently, we use ctags exclusively to power our search-based code intel. Ctags only indexes global variables (public methods and classes) and no local variables (const/let/var statements inside methods or blocks). This means that search-based intel never returns accurate results when the symbol is a local variables.

We have validated that we can fix this issue with simple static analysis of the AST of the open source file (by definition, local variables cannot be referenced in external files). The original PR implementing this strategy is https://github.com/sourcegraph/sourcegraph/pull/29254 We closed that PR because

- it used ad-hoc tree traversals instead of declarative tree-sitter queries
- it used Go bindings for tree-sitter instead of the Rust bindings

The PR https://github.com/sourcegraph/sourcegraph/pull/30016 addresses both of those issues by adding infrastructure to run tree-sitter queries via the Rust bindings from our syntax-highlighter service. However, that PR only implements syntax highlighting (not local code navigation). The next step so implement accurate code navigation for local are:

- [x] setup service to invoke tree-sitter queries #30016
- [ ] add `Occurrence.{symbol,symbol_rols}` support to syntax-highlighter (currently, it only emits `Occurrence.syntaxKind`).
- [x] Golang support
- [x] Java support
- [x] JS/TS support
- [x] C++ support
- [x] Python support
- [x] #31796

**Comment by chrismwendt** [comment]
Implemented in https://github.com/sourcegraph/sourcegraph/pull/34477
