### ISSUE TITLE
insights: add code insights tag to the license generator

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#30417]
The Sourcegraph enterprise license generator needs to be able to accept a tag for code insights.

Only questions: is `codeinsights` acceptable, or `code-insights`? Any concern we will encounter similar naming confusion as between the databases `codeintel-db` and `codeinsights-db` @Joelkw

**Comment by Joelkw** [comment]
@coury-clark  I'll check with CEs, but since code-intel has no license tag I think we'll likely be okay. I think `code-insights` is more in line with `batch-changes` though, from https://handbook.sourcegraph.com/departments/ce/process/license_keys#license-key-tags

**Comment by Joelkw** [comment]
@coury-clark  confirmed with a couple CEs that `code-insights` tag makes sense and seems conventional to them (and they're the ones who primarily generate licenses).
