### ISSUE TITLE
Sourcegraph Developer Onboarding Series 2022 Tracking

### ISSUE THREAD

**Issue by marekweb** [sourcegraph/sourcegraph#30425]
Tracking issue for: Sourcegraph Developer Onboarding series 2022

- [x] #30487 
- [x] #31720
- [x] #30368 
- [ ] #30482 
- [x] #31660

**Comment by bobheadxi** [comment]
cc @marekweb I opened an issue for the CI onboarding: https://github.com/sourcegraph/sourcegraph/issues/31660
