### ISSUE TITLE
Add ability to enable/disable token click-to-def in bext advanced settings

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#30437]
#### Feature request description

Ability to opt into the token click to definition function in the Sourcegraph extension settings.  

#### Is your feature request related to a problem? If so, please describe.

There was a [customer request ](https://sourcegraph.slack.com/archives/C01HW836940/p1643225019120600)to maintain the browser's double click to highlight copy functionality. This native browser functionality was overridden by the [new token click-to-def implementation](https://github.com/sourcegraph/sourcegraph/pull/28520) work. 

We are also getting [various feedback from users](https://sourcegraph.slack.com/archives/C0W2E592M/p1643656761794129) who are confused about re-directs to Sourcegraph upon token click. While click-to-def re-directs users within Github, in certain situations (such as user is already at definition, and click would open up a references panel), a user is redirected to Sourcegraph.com.

#### Describe alternatives you've considered.

There were[ two workarounds that were suggested](https://sourcegraph.slack.com/archives/C01HW836940/p1643311326132000?thread_ts=1643225019.120600&cid=C01HW836940): 
- User could click and drag to highlight copy (this browser native functionality is maintained even with click-to-def functionality)
- We could introduce a 100ms delay to the re-direct, and cancel page navigation if user double clicks

Both were not ideal solutions, as the first workaround is asking users to modify a user habit, and the second workaround could result in a less snappy experience for other users. 

#### Additional context

For the browser extension moving forward, we should allow users the ability to enable/disable any features that conflict or override native browser functionality. In this specific user problem, while the customer didn't necessarily dislike the click-to-def feature, they were confused by and preferred the native browser click behavior.

**Comment by jjinnii** [comment]
@erzhtor @taras-yemets Would love your thoughts as users on whether token click-to-def for the bext should be opt in (disabled by default) or enabled by default. 

My opinion is to make it opt-in: it's not clear atm that the click-to-def behavior is coming from Sourcegraph's extension, and it results in unexpected jumping files and sometimes, re-directs to sourcegraph.com. We can tackle the problem of how to better inform users that we have click-to-def behavior available through bext separately.

**Comment by erzhtor** [comment]
So, @taras-yemets and I discussed and came w/ a list of possible options for this:
1. Opt-in click&goToDef feature in browser extension options page -> advanced settings section
2. Disable click&goToDef behavior, and make browser extension behave as previously. So only hover buttons will work.
3. Replace single clicks w/ "CMD or CTRL + Click" as in most IDEs

>@erzhtor @taras-yemets Would love your thoughts as users on whether token click-to-def for the bext should be opt in (disabled by default) or enabled by default.
> 
> My opinion is to make it opt-in: it's not clear atm that the click-to-def behavior is coming from Sourcegraph's extension, and it results in unexpected jumping files and sometimes, re-directs to sourcegraph.com. We can tackle the problem of how to better inform users that we have click-to-def behavior available through bext separately.

By default, it should be the same behavior as the main sourcegraph.com since browser extension is its product. However, tbh click-to-def is slightly confusing/unexpected even on the sourcegraph.com page.

As engineers, we are got used to IDE-like behavior, which is CMD/CTRL+click for goToDef. Was this particular option considered in the code-intel team, and if yes, why was it rejected in favor of single clicks?

cc @muratsu @jjinnii @taras-yemets

**Comment by jjinnii** [comment]
Thanks for the options @erzhtor! Yes, you can read up on the [decision for click-to-def here](https://docs.google.com/document/d/1ge8pPI5Xk2vuxbgfeh8L5PMEpwmjhs1ayOAijMy0fjE/edit#heading=h.3ps469qorpbk) -- we carefully weighed the different benefits and cons to cmd-click versus click. 

I think option 1 makes the most sense, with click to def being **opt in** from advanced settings. Reasons for this: 
- While I generally agree that we need to mirror main sourcegraph.com behavior, we need to take into consideration that bext injects the sourcegraph experience into a different product. So we need to make modifications as needed from main sourcegraph.com behavior if a feature disrupts the experience in a code host. 
- We should make this opt in, especially based on the [recent understanding](https://sourcegraph.slack.com/archives/C0W2E592M/p1643724603171249?thread_ts=1643386472.213299&cid=C0W2E592M) that there are multiple instances where we would redirect to Sourcegraph.com (multiple definitions, already at def)

Let me know if you'd prefer designs before working on this, or I can just review the implementation as well. :)
