### ISSUE TITLE
Improve build times on CI

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#3045]
Right now PR builds take 10-12 minutes on CI. It would be nice to cut this in half.

Here is an example build:
https://buildkite.com/sourcegraph/sourcegraph/builds/30219

We have enough concurrency available (no jobs were waiting for more than a few seconds) so the problem reduces to speeding up (or splitting up) the long tail jobs.

Questions to answer:
- Can we run e2e tests concurrently with other steps or speed them up? Right now that is ~3 minutes of the build.
- Can we speed up (or split up) the `./cmd/server/pre-build.sh && ./cmd/server/build.sh` step which is the long tail of the concurrent phase (~8 minutes)?
  - If we can get the above down to below 5 minutes, then there are a few other phases hovering at 5 minutes we could attempt to optimize:
    - `dev/ci/yarn-build.sh web`
    - `dev/ci/yarn-build.sh web` (enterprise)
    - `go generate ./... && go install -tags dist ./cmd/... ./enterprise/cmd/...`
- Are there steps in the build that benefit from caching between different builds? If so, how much speedup would we observe if we didn't autoscale down buildkite agents as aggressively (which destroys caches).

**Comment by ggilmore** [comment]
Our Buildkite agents now only use Skylake CPUs.

**Comment by tsenart** [comment]
Nice! I'm retrying a build right now, and it seems like we'd benefit from a few more agents for parallelism too.

**Comment by chrismwendt** [comment]
The critical path is: build server image THEN run e2e tests

Breakdown of time spent building `sourcegraph/server`:

- 50s yarn
- 3m40s build web app
- 10s build schema
- 7s generate schema
- 40s build web app (again?)
- 40s build Go services
- 40s build sqlite for the symbols service
- 16s Docker build

Breakdown of time spent in the e2e test step (parallelism within this step wouldn't help):

- 5s clean the git dir
- 10s copy the `sourcegraph/server` Docker image to the dedicated e2e test k8s node
- 15s start the `sourcegraph/server` container
- 50s yarn
- 15s start Chromium
- 1m20s run e2e tests (I'm going to [rewrite the e2e setup code](https://sourcegraph.slack.com/archives/C08JA8Q1H/p1553805698012800?thread_ts=1553805006.011000&cid=C08JA8Q1H) to shave ~30s off of this step)

**Comment by slimsag** [comment]
> 50s yarn
> 3m40s build web app

Is this saying 50s installing dependencies with yarn, then 3m40s building webapp TS code?

**Comment by slimsag** [comment]
> 40s build sqlite for the symbols service

We could pre-build some binaries for this and just fetch them from a GCS bucket.

**Comment by chrismwendt** [comment]
> > 50s yarn
> > 3m40s build web app
> 
> Is this saying 50s installing dependencies with yarn, then 3m40s building webapp TS code?

I believe so, yes.

**Comment by chrismwendt** [comment]
One idea that @ryan-blunden had is to move the e2e tests out of CI and into an asynchronous Buildkite pipeline.

Pros:

- Drastically cuts down on PR CI time (from ~12m down to ~5m)
- Avoids rebuilding the `sourcegraph/server` image (reduces load a tad)
- Flakiness and slowness in e2e tests don't block CI

Cons:

- Bigger time gap between introducing a bug and finding out about it
- Bugs that would be caught by e2e tests can get into master
- We would be notified in Slack of e2e failures rather than in the PR that introduced the bug

I'm on the fence about this. Does anyone else have thoughts or preferences?

**Comment by nicksnyder** [comment]
Would we still be able to tie e2e test failures to a specific commit/PR? Overall I think it is a good thing to require e2e tests to pass on branches because we want master to be releasable at any time.

Is there something that prevents us from running the e2e step concurrently with the previous steps in the current pipeline?

**Comment by felixfbecker** [comment]
We used to have e2e tests run async by a bot instead of in CI, with notifications in Slack. It wasn't good. Way more failures on master (i.e. deployed to prod) and people ignored e2e failures. I spent time back then migrating it into Buildkite.

**Comment by chrismwendt** [comment]
> Would we still be able to tie e2e test failures to a specific commit/PR?

Yes, we could create a new Buildkite pipeline `sourcegraph-e2e` but use the same `sourcegraph/sourcegraph` repository so the commits would be the same.

> Is there something that prevents us from running the e2e step concurrently with the previous steps in the current pipeline?

Yes, Buildkite's config language is not quite flexible enough to express that while satisfying other constraints:

- Only 1 e2e test step can run at any given time due to resource contention causing panics, so we put the e2e step in a [concurrency group](https://buildkite.com/docs/pipelines/controlling-concurrency#concurrency-groups) with a concurrency limit of 1
- The e2e test step depends on the Docker image built earlier in the pipeline, so to prevent the e2e test step from running before the image is built, we added a wait between all the other steps and the e2e test step

**Comment by felixfbecker** [comment]
> 40s build web app (again?)

I couldn't see this in the logs, but we do build the web app and the management console serially. Maybe we could build these in parallel.

**Comment by felixfbecker** [comment]
When a lot of builds are happening the e2e test concurrency limit of 1 becomes a real bottleneck. Right now there are many builds that have been running for over an hour.

Can we increase the limit? I suggested this in the past but I don't remember whether it was ever tried out

**Comment by chrismwendt** [comment]
> Can we increase the limit? I suggested this in the past but I don't remember whether it was ever tried out

See my comment above:

> Only 1 e2e test step can run at any given time due to resource contention causing panics, so we put the e2e step in a concurrency group with a concurrency limit of 1

@ggilmore and I investigated this a few months ago and found that running multiple instances of Sourcegraph on a single machine causes some kind of resource contention (might be CPU, might be something else, we didn't narrow it down that far) which makes DB initialization take 30+s and causes timeouts, killing the server.

I don't know what one would find, but it very well might be worth digging a bit further to figure out why DB initialization takes so long in the presence of other initializing instances.

**Comment by felixfbecker** [comment]
I can imagine that without any limit there would be contention, but was any limit >1 tried already?

**Comment by chrismwendt** [comment]
I don't recall the exact number of concurrent processes that caused failures, but I remember it was quite low (e.g. 3).

**Comment by tsenart** [comment]
Build times have been improved. :rabbit:
