### ISSUE TITLE
SSBC: Unify column headers on editor screen

### ISSUE THREAD

**Issue by courier-new** [sourcegraph/sourcegraph#30464]
- Library header should be h4 and not capitalized
- Editor should have batch spec header
- Workspaces preview header should be h4
- All three should have single underline

See [Rob's QA feedback](https://www.figma.com/file/cTKjwbvWqU6xAykZmCTTqy/SSBC?node-id=1819%3A54863).

**Comment by adeola-ak** [comment]
https://www.figma.com/file/cTKjwbvWqU6xAykZmCTTqy/SSBC?node-id=1819%3A54863
