### ISSUE TITLE
SSBC: Clean up workspace items

### ISSUE THREAD

**Issue by courier-new** [sourcegraph/sourcegraph#30468]
Before starting, consider if it's worth pursuing this separately from #30469.

- [x] Whole item should be clickable
- [x] Items should match striping of Workspaces Preview from editor page
- [x] Icon should occupy its own column
- [x] Text styles should match Workspaces Preview
- [x] Header should be h4 and match Workspaces Preview

See [Rob's QA feedback](https://www.figma.com/file/cTKjwbvWqU6xAykZmCTTqy/SSBC?node-id=1819%3A54863).

**Comment by Cris747dz** [comment]
Thnx
