### ISSUE TITLE
SSBC: Default to "All" filter on list page

### ISSUE THREAD

**Issue by courier-new** [sourcegraph/sourcegraph#30461]
The batch changes list (index) page currently defaults to the "Open" batch changes filter. It should default to "All," so that drafts are more easily surfaced.

**Comment by adeola-ak** [comment]
<img width="276" alt="Screen Shot 2022-02-09 at 10 21 52 PM" src="https://user-images.githubusercontent.com/67931373/153331059-f595842d-68dd-41ca-a7eb-fa289027a594.png">

Since 'All' will be the new default.. wondering if the order should be changed from what it is ^ to 

All, Open, Draft, Closed?

**Comment by courier-new** [comment]
I definitely think that'd make more sense! We expect to see the default one "first" usually.

However, it also strikes me that https://github.com/sourcegraph/sourcegraph/issues/30463 will supercede that, so don't worry about it too much. 🙂

**Comment by adeola-ak** [comment]
Ahhh yea okay i skipped that one for now because I had a question about it and then forgot the radios were going bye bye lol. So should i still push these changes until I maybe work on that one tomorrow?

**Comment by courier-new** [comment]
Yeah sounds great!
