### ISSUE TITLE
Remove <span class="underline"> from alert links

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#3048]
https://sourcegraph.com/search?q=r:sourcegraph/sourcegraph+className%5C%3D%5C%22.*underline

Link styling should be consistent.

**Comment by dadlerj** [comment]
@francisschmaltz any thoughts?

**Comment by francisschmaltz** [comment]
This looks right. It underlines the span when it's hovered. The classname should be documented/different so it's clearer what this does.

https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/browser/src/shared/components/alerts.scss#L24:22

**Comment by dadlerj** [comment]
I can fix this in https://github.com/sourcegraph/sourcegraph/pull/2969. Odd that this is necessary at all — I'll see if whatever parent class is preventing the link from automatically underlining on hover can be fixed.

If it's a painful fix, and I just want to rename to be more clear instead, what would a good name be here @francisschmaltz?

**Comment by felixfbecker** [comment]
@francisschmaltz why not underline _all_ links on hover (i.e. just remove that `span.underline` from that selector)?

**Comment by francisschmaltz** [comment]
@felixfbecker because not all spans **should** be underlined. There are a lot of spans that are some kind of block link. E.g. User menu, explore page, sidebars

**Comment by felixfbecker** [comment]
Could you give an example?

**Comment by francisschmaltz** [comment]
> E.g. User menu, explore page, sidebars

**Comment by felixfbecker** [comment]
How do those relate to link in alerts? Our global styles for links already apply underscoring afaik and those elements all have overrides anyway

**Comment by pdubroy** [comment]
Closing this — last update was over two years ago, so I'm assuming it's obsolete. Please feel free to re-open if I'm wrong.
