### ISSUE TITLE
Long processing times for lsif-tsc dumps

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/sourcegraph#30493]
Slack discussion: https://sourcegraph.slack.com/archives/CHXHX7XAS/p1643723019205479?thread_ts=1643718475.378599&cid=CHXHX7XAS

Honeycomb: https://ui.honeycomb.io/sourcegraph/datasets/codeintel-worker/result/gDdCJXeH9dk

It looks like starting around Jan 16 ~ Jan 17, the compressed LSIF dumps for the `client/web` directory became ~144M in size from ~50M earlier. Processing times went from about ~4 minutes to ~50 minutes (!!!). Such long processing times create long queue latencies, since we index every commit for sourcegraph/sourcegraph, and there are only 4 upload processing jobs running in parallel.

We didn't land any changes in sourcegraph/lsif-node during that time.

So far, I've reproduced the smaller tarball size with 214c3eb4f6 (Jan 14) and the larger tarball size with c2b559adf7 (Feb 1).

**Comment by varungandhi-src** [comment]
Git bisection log:

```
git bisect start
# good: [010d9e2b437d38677a036521220ad19ba09a38d3] open insight preview results in new tab (#29905)
git bisect good 0000000000000000000000000000000000000000
# bad: [a9a435f2c879dbfff3b14a02b332ef1e6cc9f393] buildchecker: correctly get build URL (#29962)
git bisect bad 0000000000000000000000000000000000000000
# good: [9c3485a411f75f917a4dd5d0cfbd5056cf188b76] search: use shorter query parser helper (#29947)
git bisect good 0000000000000000000000000000000000000000
# good: [e3b0ce401473cb70f8cac1540be75e69256d698b] codeintel: fix nil pointer in no-progress-output upload (#29975)
git bisect good 0000000000000000000000000000000000000000
# good: [c7f9aeaf38737c9621027e2906d50ed181a1b242] codeintel: make dependencies/dependents list collapsible (#29977)
git bisect good 0000000000000000000000000000000000000000
# bad: [8c14f63c429b9f443ff74b8e954465c14c8665c9] search: use field mapper for substituting context query (#29951)
git bisect bad 0000000000000000000000000000000000000000
# bad: [49350e2cd321cbe2c5c2a48c4043dd687abf528a] Remove use of edge repos, pinned versions (#29986)
git bisect bad 0000000000000000000000000000000000000000
# bad: [29ef1da2a95cfd8766b56fd303ac2b31bde06e7f] Create search and search-ui packages (#29773)
git bisect bad 0000000000000000000000000000000000000000
# first bad commit: [29ef1da2a95cfd8766b56fd303ac2b31bde06e7f] Create search and search-ui packages (#29773)
```

For commits including and after 29ef1da2a9 (which is +2260, -1392), it looks the compressed dump size is about 126M, whereas it is about 50M before.

**Comment by varungandhi-src** [comment]
Some more details:

- c7f9aeaf38 - Time to emit index: 3m5s . Uncompressed size: 496M . Compressed with `tar -czf`: 59M
- 29ef1da2a9 - Time to emit index: 7m0s . Uncompressed: 896M . Compressed with `tar -czf`: 113M

Processing times for both: (with a local sourcegraph instance)

```
correlateFromReader:, duration: 11.684012791s, entries: 4564692
canonicalizeDocuments, duration: 1m28.473026709s
canonicalizeReferenceResults, duration: 37.854166ms
canonicalizeResultSets, duration: 367.729583ms
canonicalizeRanges, duration: 1.237329125s
prune DefinitionData, duration: 25.570791ms
prune ReferenceData, duration: 35.153083ms
prune ImplementationData, duration: 84ns
prune total, duration: 239.423959ms
serializeBundleDocuments, duration: 5.334µs
serializeResultChunks, duration: 41.01975ms
gatherMonikersLocations (definitions), duration: 290.108083ms
gatherMonikerLocations (references), duration: 355.597167ms
gatherMonikerLocations (implementation), duration: 242.38825ms
collectDocumentation, duration: 21µs
gatherPackages, duration: 20.7355ms
gatherPackageReferences, duration: 366.74225ms

correlateFromReader:, duration: 21.351584042s, entries: 8394099
canonicalizeDocuments, duration: 11m2.12545125s
canonicalizeReferenceResults, duration: 95.559125ms
canonicalizeResultSets, duration: 828.618625ms
canonicalizeRanges, duration: 2.662273875s
prune DefinitionData, duration: 72.105959ms
prune ReferenceData, duration: 108.625083ms
prune ImplementationData, duration: 84ns
prune total, duration: 417.716375ms
serializeBundleDocuments, duration: 7.541µs
serializeResultChunks, duration: 81.581583ms
gatherMonikersLocations (definitions), duration: 611.498ms
gatherMonikerLocations (references), duration: 747.980084ms
gatherMonikerLocations (implementation), duration: 534.241333ms
collectDocumentation, duration: 26.041µs
gatherPackages, duration: 19.332917ms
gatherPackageReferences, duration: 445.586791ms
```

The problem seems to be in `canonicalizeDocuments`.

**Comment by varungandhi-src** [comment]
One clue for this seems to be the large number of duplicate documents in the index. The smaller upload has about 4044 duplicate documents, whereas the larger upload has about 14309 duplicate documents.

I measured the number of duplicate documents by doing a `documentIDs.values().map(|ids| ids.len() - 1).sum()` in `canonicalizeDocuments.

**Comment by varungandhi-src** [comment]
The long processing times are leading to queue buildup; dogfood only has 2 workers (as opposed to 4 in production), so it has a queue size of 4500+ uploads. 😢

**Comment by varungandhi-src** [comment]
I took a 15 minute profile in a local dev environment which covers the processing of the larger LSIF dump (see below, click to enlarge). Most of the time is being spent in map lookup and iteration when canonicalizing documents.

![pprof CPU usage graph](https://user-images.githubusercontent.com/93103176/152562382-29795317-2bf4-4346-be4b-78d8d8133782.svg)

**Comment by varungandhi-src** [comment]
Here's a CPU usage graph (click to expand) for 15 minutes in production for `client/web` being processed. The main problem is still the same: map operations taking up a lot of time.
![pprof CPU graph](https://user-images.githubusercontent.com/93103176/153384397-f2854121-ed5c-44a0-a4d1-ab7f0997ef2d.svg)

**Comment by varungandhi-src** [comment]
I've turned off LSIF uploads for client/web (https://github.com/sourcegraph/sourcegraph/pull/30952). That should help as a temporary workaround until we fix the core issue.

**Comment by efritz** [comment]
Possible/partial solution: https://github.com/sourcegraph/sourcegraph/pull/30978

**Comment by efritz** [comment]
@varungandhi-src @Strum355 Can we consider this closed?
