### ISSUE TITLE
Move selected search filters to the front

### ISSUE THREAD

**Issue by vanesa** [sourcegraph/sourcegraph#305]
#### Feature request description

If a user has many search filters and selects one that is for example at the end of the list, it would be more comfortable for this filter to move towards the front of the list so that user can de-select it easier instead of having to scroll horizontally again to find it.

#### Is your feature request related to a problem? If so, please describe.

It would provide a better UX.

#### Additional context

As shown below, I need to scroll all the way to the right to find my selected filter.
![image](https://user-images.githubusercontent.com/9110008/46559815-591d0300-c8a6-11e8-9b6c-a3b8cfeb90dd.png)

**Comment by sqs** [comment]
The difficulty here is to make it so that the filter doesn't jump around right when you click (that would be undesirable). Not high priority, backlogged.

**Comment by nicksnyder** [comment]
@attfarhan assigning this to you as background info since you will be working on search frontend. Don't spend time solving this directly, but I imagine the new search experience that you are working on  will solve this incidentally.

**Comment by slimsag** [comment]
I am going to close this as it doesn't seem relevant anymore given the more broad improvements we are making to the search UI, feel free to reopen if you believe this is wrong.
