### ISSUE TITLE
Focus search input issues when using keyboard navigation

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#30510]
Issue 1: search input not adding cursor when using keybindings to navigate back and forth between tabs.

#### Expected behavior:

When keyboard navigating back and forth between other files back to Sourcegraph search file, users expect that hitting tab once in the Sourcegraph search will highlight input field and add cursor to edit. 

#### Actual behavior:

Taken from [internal feedback](https://sourcegraph.slack.com/archives/C02E3HHDZ98/p1643662302885139). When user keyboard navigates to a different VS Code file then returns to the Sourcegraph search file (using keyboard nav), hitting tab once on the Sourcegraph search file highlights the search input field, but does not include a cursor for a user to edit.

**Comment by jjinnii** [comment]
Issue 2: search input not focusing when using the `sourcegraph.search` command 

#### Actual behavior: 

Taken from [internal feedback](https://sourcegraph.slack.com/archives/C02E3HHDZ98/p1643878593089489). When user uses the `cmd + shift + 9` sourcegraph.search command to navigate to the Sourcegraph search tab, the search bar is not focused.

![CleanShot 2022-02-03 at 09 55 09](https://user-images.githubusercontent.com/87138876/152377783-a33dfea7-f47d-4dc9-8757-04c21b5cf4e3.gif)

**Comment by abeatrix** [comment]
Both fixed in V2
