### ISSUE TITLE
Create documentation for generic webhook schema

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#30525]
Bonus points if there is a tutorial on how to configure it for Zapier or another similar tool.

Also need to update [the `Alert` inside of `WebhookAction`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/enterprise/code-monitoring/components/actions/WebhookAction.tsx?L106) to link to this documentation.

**Comment by lguychard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Search-Product-61302e38f801dc0012e2e050/issues/sourcegraph/sourcegraph/30525?planning-poker) with ZenHub @benvenker @camdencheek @limitedmage

**Comment by limitedmage** [comment]
Fixed by #34016
