### ISSUE TITLE
Buffering in development suppresses output

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#30529]
In local development, something is buffering stdout waiting for a newline, which makes it look like nothing is happening. That means if you write:

```go
for {
  // tight loop
  fmt.Printf("%v", foo)
}
```

and you forgot the `\n`, then you might waste time tracking down why that line isn't getting executed.

cc @mrnugget in case this is under the purview of `sg`.

**Comment by mrnugget** [comment]
Yes, that's in `sg`. Sorry about that. 

More specifically it's somewhere in here:

https://github.com/sourcegraph/sourcegraph/blob/8468f234ff821c2382bf0bf2a9a3fcc08e84a66b/lib/process/logger.go#L76-L108

I touched this last with @Strum355 in here 0292a1648fd8486cc4befb58244896f803232e6e. Not sure if we broke something.

Time to write some tests.

**Comment by chrismwendt** [comment]
I think I hit this again today, and it took a few hours to debug. gitserver was trying to log a slow request and it included a huge URL parameter:

<img width="755" alt="CleanShot 2022-02-03 at 13 15 20@2x" src="https://user-images.githubusercontent.com/1387653/152421740-4772d533-68ae-40d1-9a23-20fc19d88c55.png">

This screenshot is from running gitserver outside of `sg`.

**Comment by mrnugget** [comment]
@chrismwendt the huge URL parameter problem: was that also missing a newline? Because I just tried to reproduce and even with 10k char long string it prints nicely.

**Comment by chrismwendt** [comment]
Nope, I'm pretty sure it had a newline because it was logged using `log15.Warn()`:

![CleanShot 2022-02-04 at 11 48 59@2x](https://user-images.githubusercontent.com/1387653/152586028-4124e591-4f61-4c80-9520-6098f9f63648.png)

This screenshot is from after merging this truncation PR https://github.com/sourcegraph/sourcegraph/pull/30657

I'm not sure how big the URL was, but probably closer to 10M chars.

**Comment by mrnugget** [comment]
10 _million_ characters? Uhm okay
