### ISSUE TITLE
Browser extension URL config behaves strangely at times

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#3052]
Browser extension version: v19.3.29.1904

## Case 1: Only supplying a hostname doesn't work

If a user has Sourcegraph running locally and only enters `localhost:7080`, unless they have Chrome developer mode enabled and they have the background script open, they won't easily know that they have to enter the `http://localhost:7080`, especially as by clicking the `localhost:7080` hyperlink in the extension error message works.

Browsers accept URLs without the protocol so I would expect the extension URL input to exhibit the same behavior.

![ScreenFlow](https://user-images.githubusercontent.com/133014/55263391-09ecd500-522e-11e9-91e5-36815469b2d7.gif)

## Case 2: General input weirdness

This one is more contrived as it does not emulate a users likely behavior, but it should not be possible for the connection status to be reported incorrectly.

![ScreenFlow](https://user-images.githubusercontent.com/133014/55263595-c34baa80-522e-11e9-9057-b664246dd57a.gif)

## ✅ (FIXED) Case 3: Sometimes rejecting https://sourcegraph.com

This seems to be caused by the extension not having `https://sourcegraph.com/` in its list of origins. I have not yet been able to determine what gets the extension into this state.

![ScreenFlow](https://user-images.githubusercontent.com/133014/55264733-9d280980-5232-11e9-8d54-dab4e436af52.gif)

**Comment by chrismwendt** [comment]
I opened a separate issue for case 3 https://github.com/sourcegraph/sourcegraph/issues/3056
