### ISSUE TITLE
devx: establish interest and get feedback for cross-team collab proposal

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#30555]
Send out https://docs.google.com/document/d/1ZoO-zySXHs7E0p98j8byfz8TZFhKHWVP8s-2IL0fUCQ/edit : 

- Inform of our intent and hopes
- Establish points of contact
- Gain feedback on our proposed process and ideas: We want this to be productive for both teams and non-blocking, so we want to invite feedback

Share intent with the caveat that we might not be actioning on it _now_, given potential workload with the 25-minute-deployment KR, but we want to start a discussion regardless.

**Comment by kstretch9** [comment]
looks good!

**Comment by bobheadxi** [comment]
Update - brought this up at backend crew meeting today, and will be asking issues to be tagged as `devx/cross-team` - also see https://sourcegraph.slack.com/archives/C02MWRMAFR8/p1643918752336059

**Comment by bobheadxi** [comment]
Status update went out yesterday, and we have 4 contacts on the signup 😁 should be enough to get the ball rolling
