### ISSUE TITLE
Patch release: PR #30547

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#30553]
@sourcegraph/delivery I am requesting the following commits be included in a patch release. They are already merged into `main`:

In response to INC-76, the following commit was made to fix it:
https://github.com/sourcegraph/sourcegraph/commit/dbc5723990672d130981e1496103c0cea3a6acfd

This affects versions 3.35 and 3.36, so I'm requesting that we make a patch release for both of those versions.

---

The intent of the questions below is to ensure we keep Sourcegraph high quality and [only create patch releases based on a strict criteria.](https://handbook.sourcegraph.com/engineering/releases#patch-releases) If you can answer yes to many or most of these questions, we will be happy to create the patch release.

I have read [when and why we perform patch releases](https://handbook.sourcegraph.com/engineering/releases#patch-releases) and answer the questions as follows:

> Are the changes extremely minimal, well-tested, and low risk such that not testing as we do in a full release is OK?

Yes

> Is there some functionality completely broken that warrants redacting the prior release of Sourcegraph and advising users wait for the patch release?

No

> This will interrupt our regular planned work and release cycle, taking one full working day of our time, and will take up all of our site admin's valuable time by asking them to upgrade or producing noise for them if they don't need to upgrade.
>
> Do you believe the changes are important enough to warrant this?

Yes

> Patch releases are a signal we can do something better to improve the quality of Sourcegraph. Have you already scheduled a call (or created a google doc) to perform a [retrospective](https://about.sourcegraph.com/retrospectives) and identify ways we can improve?

Will be performed as part of the incident. Additionally, we have plans to add integration tests to validate this sort of thing.

---

**For the [release captain](https://handbook.sourcegraph.com/engineering/releases#release-captain)** - after reviewing this request:

- [ ] **Comment on this issue** with a decision regarding the request.
- [x] If approved, **add it to a patch release**:
  - If there is [already an upcoming patch release](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+), add the listed commits alongside a link to this issue
  - If there is no upcoming patch release, create a new one:
    - Update [`dev/release/release-config.jsonc`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/release/release-config.jsonc) with the patch release in `upcomingRelease` and `releaseDate` (and open a PR to `main` to update it)
    - `yarn release tracking:issues`
    - Add the listed commits alongside a link to this issue to the generated [release tracking issue](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+)
- [ ] **Comment and close this issue once the relevant commit(s) have been cherry-picked into the release branch**.

**Comment by michaellzc** [comment]
Approved

**Comment by michaellzc** [comment]
Sourcegraph 3.36.3 has been published
* Changelog: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/CHANGELOG.md#3-36-3
* GitHub release: https://github.com/sourcegraph/sourcegraph/releases/tag/v3.36.3
* Release batch change: https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.36.3

**Comment by michaellzc** [comment]
Sourcegraph 3.35.2 has been published
* Changelog: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/CHANGELOG.md#3-35-2
* GitHub release: https://github.com/sourcegraph/sourcegraph/releases/tag/v3.35.2
* Release batch change: https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.35.2
