### ISSUE TITLE
Docs instruct to fork a public repo then make it private, which isn't possible per GH docs.

### ISSUE THREAD

**Issue by jwayman** [sourcegraph/sourcegraph#30572]
#### Describe the issue
I'm following along with the Docker Compose instructions, and it advised to make a fork of the sourcegraph/deploy-sourcegraph--docker reference repository.

At one point is advises: "WARNING: Set your fork to private if you plan to store secrets (SSL certificates, external Postgres credentials, etc.) within the repository."

However, in trying to change the visibility, Github says it does not allow the visibility of a fork of a public repo to be changed to private.

I found some instructions on how to duplicate a repository to get around that requirement... but is this a case of the docs are incorrect, or my understanding is lacking.

#### Where is the issue located?
[Docker Compose instructions](https://docs.sourcegraph.com/admin/install/docker-compose/operations#configure)

#### Suggested resolution
I found this: (https://stackoverflow.com/questions/10065526/github-how-to-make-a-fork-of-public-repository-private#:~:text=Just%20go%20to%20https%3A%2F%2F,in%20%22Privacy%22%20select%20Private%20).

But, not sure if that's a supported route. I couldn't find any official GH docs on that process. I might be looking for the wrong thing though.

[This GitHub documentation](https://docs.github.com/en/repositories/creating-and-managing-repositories/duplicating-a-repository)

**Comment by JeanPaulSG** [comment]
Updated text and created a pull request: https://github.com/sourcegraph/sourcegraph/pull/35694
