### ISSUE TITLE
Clear search results on Sourcegraph extension tab close

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#30583]
#### Expected behavior

As a user, I expect that if I close the Sourcegraph extension and re-open the extension, I will view the [extension homepage](https://www.figma.com/file/EXXvfxVwtCIsrbQez4rPlF/VS-Code-Extension-MLP?node-id=1287%3A2397) with access to Recent History. (For example, how Google behaves) 

#### Actual behavior
Currently, we are saving the search query and results from the user's most recent search and re-opening the extension to the search results page. 

#### Additional context

Based on[ internal feedback](https://sourcegraph.slack.com/archives/C02E3HHDZ98/p1643738352084459?thread_ts=1643711828.769109&cid=C02E3HHDZ98). We have solved the larger issue about having access to the Soucegraph account authentication section in the sidebar (outside of the homepage). This is a non-critical UX issue of clearing user's search results upon closing the extension and opening new to the homepage.

**Comment by abeatrix** [comment]
PR: https://github.com/sourcegraph/sourcegraph/pull/32087/commits/13b07a25c5dfbbdbcfd1aceafebdf71a01ec072a
![clearresults](https://user-images.githubusercontent.com/68532117/157742582-4a881e68-7cad-477f-9671-45a538bae7fe.gif)

**Comment by abeatrix** [comment]
Included in the 2.2.0 release: [changelog](https://marketplace.visualstudio.com/items/sourcegraph.sourcegraph/changelog) / [PR/30084](https://github.com/sourcegraph/sourcegraph/pull/30084)
