### ISSUE TITLE
Clicking on repo name in search results breadcrumbs should direct users to repo page

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#30585]
#### Expected behavior:

As a user, I expect that clicking specifically on the repo name in the breadcrumbs of a search result will take me to the repo page, not the file location. (how it is implemented in sourcegraph.com)

#### Actual behavior:

Currently, clicking anywhere in the breadcrumbs redirects users to the file location.

**Comment by tjkandala** [comment]
Closed by #33102
