### ISSUE TITLE
Sourcegraph context has no repos in menu or results on sourcegraph.com

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#30598]
Not much else to say, see below.

https://sourcegraph.com/search?q=context:%40sourcegraph+repo:.*&patternType=literal

![image.png](https://images.zenhubusercontent.com/5467e9ba7c6ccc6277a5f103/6c762351-d439-44c3-bf3b-a2fd2cd7edd0)

**Comment by novoselrok** [comment]
Not a bug, we only have one repo synced in our code host connections.
