### ISSUE TITLE
Update copy in welcome sidebar 

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#30594]
Based on [feedback](https://sourcegraph.slack.com/archives/C02E3HHDZ98/p1643834562578609) from product marketing, I have updated the copy in the Welcome sidebar messages to better align with our use case messaging. 

#### Original

<img width="246" alt="Screen Shot 2022-02-02 at 4 19 00 PM" src="https://user-images.githubusercontent.com/87138876/152247007-627f64ac-399c-4336-8ec9-43b608f49b33.png">

#### Updated (updated in [Figma](https://www.figma.com/file/EXXvfxVwtCIsrbQez4rPlF/VS-Code-Extension-MLP?node-id=1371%3A2976) as well) 

<img width="238" alt="Screen Shot 2022-02-02 at 4 20 53 PM" src="https://user-images.githubusercontent.com/87138876/152247226-b8a473d2-e4dd-4a2d-a0ba-8e7d436b739b.png">

**Comment by abeatrix** [comment]
Updated in the latest PR https://github.com/sourcegraph/sourcegraph/pull/30502
