### ISSUE TITLE
insights: landing page pings for GA launch

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#30608]
RFC: https://docs.google.com/document/d/1J-fnZzRtvcZ_NWweCZQ5ipDMh4NdgQ8rlxXsa8vHWlQ/edit# 

I will make sure this RFC is done and approved by February 9th. Update: it's approved as of Feb 9th. 

## Prioritized list of pings, if we don't have time for all of them for 3.37. 

**[Here is the figma with the definitions / locations.](https://www.figma.com/file/EFgTP7gpdpQSEo1n4FUfsW/In-product-landing-page-WIP?node-id=1688%3A27177)** 

This naming matches the RFC and assumes that each item includes both uniques and total, the same way we have it for the creation funnel [docs](https://docs.sourcegraph.com/dev/background-information/insights/code_insights_pings#code-insights-view-click-creation-funnels). Top priority first. 

1. Get-started-pageview
    1. **Very important note** on implementation – we should filter this out of the “insights pageview” [we already collect](https://docs.sourcegraph.com/dev/background-information/insights/code_insights_pings#unique-page-views-count). This should be its own category, and not a subset of the other category. So our normal pageview pings contain NO pageviews of the get-started-page, and the get-started-pageviews contain NO other pageviews. They are distinct sets, the venn diagram is two circles with no overlap. 
1. Get-started-page-hovers are FILTERED 
      1. Note: This is not the priority of collecting the hovers, but rather the priority of making sure we **do not include them in our existing hover stats**. If that means we just remove the event from firing, that is fine! It is important not to include hovers here in our other stats because hovers are a good indication of use of "actual insights they created" – since they did not create these insights on the getting-started-page, we do not want to include those in the normal hovers pings! See the later list item for the priority of otherwise separately collecting the hovers. 
2. Get-started-primary-cta-click
5. Get-started-template-copy-click and get-started-template-use-click
6. Get-started-tab-[TABNAME]-click and get-started-tab-[TABNAME]-more-click
   1. Note this is "dynamic" and should match the actual tab's name where it says "[TABNAME]" so it'd show up as like "get-started-tab-migrations-more-click" for example
4. Get-started-big-template-click
3. Get-started-query-modification and get-started-repo-modification
     1. Note – we can debounce these, or just count them per pageview (so it’s max 1 time unless you refresh the page). That won’t tell us if the # of modifications matters to the conversion, but that’s more granular than we’re able to easily get in pings anyway (tying things to individual sessions isn’t something we can do in pings). 
8. Get-started-docs-clicks
9. Get-started-page-hovers
     10. Note on implementation – we should separate these hover counts from our existing hover counts. These can be in a separate json section – we don’t want them to impact our data counting of existing hovers. 
9. Video-plays-clicks (we will have a video is my understanding)

Our "must have" goals would get us to implementing through  number 5 on this list (the TABNAME pings), our "good state" goals get us to number 7 (so query/repo modification pings), and our "stretch goals" are to get all the way through this list.

**Comment by vovakulikov** [comment]
@unclejustin I've been thinking about this and this issue actually has a tech debt blocker at the moment. [Currently, we have tracking logic around insight UI-related events right inside of chart view components](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/client/web/src/views/components/view/content/ViewContent.tsx?utm_product_name=WebStorm&utm_product_version=WebStorm&utm_source=JetBrains-v1.2.2#L71:29). 

So if we want to have special tracking events for the landing page and still re-use these components we have to either
- Extend these view chart components with tracking props settings to be able to set up tracking inside properly 
- Extract tracking logic from the view components (I like this option more than the first one but it also might be a bit complicated and therefore we perhaps don't have enough time for the GA launch. 

@unclejustin let me know what you think about this.

**Comment by unclejustin** [comment]
> Extract tracking logic from the view components

@vovakulikov I totally agree. I would love to find a way to encapsulate the tracking logic into composable components. I have ideas, but they will not make it before GA.

We can extend the component for now 🤢 but we need to make sure it's scheduled to clean them up quickly.

This is marked as a "must have" so I don't think we have much choice.
