### ISSUE TITLE
Reduce risk of user added external service syncs blocking

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#30619]
On sourcegraph.com we currently run a few external service syncs concurrently (6 as of today).

However, we have 4 "site level" external services that are very large and can take a long time
to complete syncing. This raises the possibility that they are all running at the same time and
block user or org services from syncing as was seen in a [recent incident](https://app.incident.io/incidents/79).

As we add more site level services this is likely to happen again. 

One option is to work from two different queues, one for user / org services and another for site
level.

**Comment by eseliger** [comment]
user owned external services no longer exist - closing
