### ISSUE TITLE
Investigate return of deleted external service

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#30620]
During a [recent incident](https://docs.google.com/document/d/15WLcuZ4COWDMiFjoNZVJGjRvJXqPmqsNH30u-fxSHcs/edit#heading=h.wz8bfue0fh4) it was noticed that an external service that
was deleted from the UI seemed to become undeleted on sourcegraph.com after some time.

This should not be possible and we need to investigate whether this was a deployment / config issue
or caused by a bug in our code.

**Comment by eseliger** [comment]
I think think we have any data left here to investigate, so we will look at this if it happens again.
