### ISSUE TITLE
ui: show progress indicator when cloning repositories

### ISSUE THREAD

**Issue by ijt** [sourcegraph/sourcegraph#3063]
I added a config with about 8k repositories and clicked the "Update external service button". Time passed, I think it was hours, during which I had no indication that anything was happening. Then the repositories showed up on the Repositories page, all at once it seems. It would be a better experience to show that progress is being made and how much. Or maybe the repos could show up on the Repositories page as they are cloned, not all at once.

**Comment by ijt** [comment]
I just tried again and this time the repos showed up quickly and there are indicators next to the ones that are being cloned. I guess it's fine after all!

**Comment by ggilmore** [comment]
I have seen this behavior on 3.2. If you add thousands of repos at once, it can take a very long time until they show up on the Repositories list. According to @slimsag, this is because Sourcegraph is fetching the metadata for every repository before it appears in that list.

**Comment by keegancsmith** [comment]
@ggilmore Can you try it on your dev version now? We have changed the behaviour of the syncer, and it defaults to on in current master.

Some more details on your external service configuration would also be useful. For example if you used a Github advanced search we previously had a bad bug I solved yesterday in https://github.com/sourcegraph/sourcegraph/pull/3400

**Comment by keegancsmith** [comment]
@mrnugget I believe we have this now?

**Comment by mrnugget** [comment]
> @mrnugget I believe we have this now?

I'd say so, yes. The status indicator shows you whether we're cloning or not.
