### ISSUE TITLE
insights: [spike] investigate how to record a series non-globally

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#30635]
Currently all series that are recorded are global. This was a mechanism to simplify the logic - allowing the process to simply iterate over the entire set of repositories. We have a strong signal and desire to make it faster to backfill these series by reducing the scope of repostiories that they execute against, likely using [Search Contexts](https://github.com/sourcegraph/sourcegraph/issues/28858#issuecomment-995104668).

This spike is to investigate and propose the requisite architectural changes in the backend to support this behavior.

Some questions we may answer:
1. Do we retain a global iterator for series that are actually executed globally?
2. Can we cache any data to reduce network calls if we separate series out individually?
3. Do we run these concurrently?
4. What happens if the set of repositories changes? Currently we would identify it as a new data series  - would changing the set of repos precipitate a new backfill? How does that work if the set of repositories is dynamic (from a context query)?
5. How do we observe / get visibility into these executions - does anything change here?
6. What assumptions / changes in the API need to happen to support this? (many things are assumed around global series)

**Comment by Joelkw** [comment]
Noting that permissions work is ongoing in [RFC 617](https://docs.google.com/document/d/1B3A-PQTykOSnp6BtHZTbIFpSRrvbiV-0FrnukJeaM3A/edit#) but either way, once we resolve contexts to lists of repos, this will still be relevant.

**Comment by coury-clark** [comment]
Based on the proposal in [RFC 689](https://docs.google.com/document/d/16JPGhOZHAfgc1_fUcqrdey08W4ghjo7JHOYIjL64dk4/edit) we are going to migrate all of the current just-in-time behavior to a pre-recorded insight, similar to global insights.

1. Will we reuse the data, in the same way we try to reuse for a global series?
  1. I recommend we do not
  2. But we may want to have some monitoring / pings to understand how many timeseries and how big they are to iterate on this decision
2. We will need to modify snapshots / interval recordings to execute non-global queries. This may mean generating queries that have `repo:A or repo:B` instead of global.
3. We can probably make some small changes to the historical enquerer to reuse it. I think the primary changes here would be a new iterator instead of only the "all repos iterator".

**Comment by chwarwick** [comment]
I believe the only UI change needed will be #35306 which updates the webapp to pull the insight data from the insights api instead of forming it own queries.  

The should be no need to change any Create/Edit mutations because they already include all of the relevant data.

**Comment by chwarwick** [comment]
> 3. We can probably make some small changes to the historical enquerer to reuse it. I think the primary changes here would be a new iterator instead of only the "all repos iterator".

I had hacked around on this some last iteration by making a "some repos iterator"  that kept a map of repoNames and wrapped the allReposIterator and skipped items that weren't in the map.  It was nice in that it allowed access to the repoID

**Comment by coury-clark** [comment]
Opened these work issues:

- [ ] https://github.com/sourcegraph/sourcegraph/issues/35580
- [ ] https://github.com/sourcegraph/sourcegraph/issues/35655
- [ ] https://github.com/sourcegraph/sourcegraph/issues/35581
