### ISSUE TITLE
github v3 client: remove hard dependency on redis cache

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#30656]
Due to [this usage of redis cache in our GitHub v3 client](
https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/internal/extsvc/github/v3.go?L222), anyone that uses the github client needs redis, instead of a cache. It would be better for the github client to accept a cache as a parameter on construction.

That way you can make a cache interface that rcache conforms to, and construct an object that wraps that package at app startup rather than every consumer of the github package.

**Comment by bobheadxi** [comment]
Some more context: https://sourcegraph.slack.com/archives/C07KZF47K/p1643932238892759?thread_ts=1643912808.738049&cid=C07KZF47K

> No, but anyone that uses the github client now need redis, instead of a cache. It would be better for the github client to accept a cache as a parameter on construction. That way you can make a cache interface that rcache conforms to, and construct an object that wraps that package at app startup rather than every consumere of the github package.

**Comment by davejrt** [comment]
Based on a lot of digging through code and the suggestions in the attached PR. it seems as through the consensus it to use [this](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/extsvc/github/v3.go?L154:68&subtree=true) function in place of `get` in other places in the code where we interact with a cache. 

I understand the logic and intent here, but following the various functions it's not entirely clear to me where this should be implemented.  My hunch is [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/extsvc/github/common.go?L1821&subtree=true), given this is where the actual `c.get` called is made, and what `GetRepository` is calling.

**Comment by bobheadxi** [comment]
@davejrt could we just replace the specific calls to `get` with `getConditional`?
