### ISSUE TITLE
3.35 and 3.36 patch release request

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#30652]
@sourcegraph/delivery I am requesting the following commits be included in a patch release. They are already merged into `main`:

https://github.com/sourcegraph/sourcegraph/commit/0dc50100668b7aef5e54e273926f73371d160394 fixes a disk cleanup routine in the `symbols` service that was causing unbounded disk usage growth.

Affects both **3.35** and **3.36**.

---

The intent of the questions below is to ensure we keep Sourcegraph high quality and [only create patch releases based on a strict criteria.](https://handbook.sourcegraph.com/engineering/releases#patch-releases) If you can answer yes to many or most of these questions, we will be happy to create the patch release.

I have read [when and why we perform patch releases](https://handbook.sourcegraph.com/engineering/releases#patch-releases) and answer the questions as follows:

> Are users/customers actively asking us for these changes and cannot wait until the next full release?

Yes https://sourcegraph.slack.com/archives/C015JREMBTR/p1643926551972399?thread_ts=1643144056.003300&cid=C015JREMBTR

> Are the changes extremely minimal, well-tested, and low risk such that not testing as we do in a full release is OK?

Yes

> Is there some functionality completely broken that warrants redacting the prior release of Sourcegraph and advising users wait for the patch release?

No

> This will interrupt our regular planned work and release cycle, taking one full working day of our time, and will take up all of our site admin's valuable time by asking them to upgrade or producing noise for them if they don't need to upgrade.
>
> Do you believe the changes are important enough to warrant this?

Unsure, maybe this fix does not warrant a release by itself (especially considering the high burden on the delivery team right now), but could get bundled in the next patch release.

> Patch releases are a signal we can do something better to improve the quality of Sourcegraph. Have you already scheduled a call (or created a google doc) to perform a [retrospective](https://about.sourcegraph.com/retrospectives) and identify ways we can improve?

See the [Slack thread](TODO).

---

**For the [release captain](https://handbook.sourcegraph.com/engineering/releases#release-captain)** - after reviewing this request:

- [ ] **Comment on this issue** with a decision regarding the request.
- [ ] If approved, **add it to a patch release**:
  - If there is [already an upcoming patch release](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+), add the listed commits alongside a link to this issue
  - If there is no upcoming patch release, create a new one:
    - Update [`dev/release/release-config.jsonc`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/release/release-config.jsonc) with the patch release in `upcomingRelease` and `releaseDate` (and open a PR to `main` to update it)
    - `yarn release tracking:issues`
    - Add the listed commits alongside a link to this issue to the generated [release tracking issue](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+)
- [ ] **Comment and close this issue once the relevant commit(s) have been cherry-picked into the release branch**.

**Comment by chrismwendt** [comment]
@sourcegraph/delivery is there anything I can help with to get this patch in 3.35 and 3.36?

It looks like it's been approved, but there hasn't been a comment on this issue yet:

<img width="680" alt="CleanShot 2022-02-08 at 16 12 42@2x" src="https://user-images.githubusercontent.com/1387653/153091369-574643dc-b902-41db-8bec-360be56ccfa5.png">

I understand these can take time. If this is approved, do you have a very rough estimate for when it might get released (days vs weeks)?

**Comment by michaellzc** [comment]
Hi @chrismwendt 

The box was checked by mistake (my bad)

The Delivery no longer owns the release process and there's a separate process in place to get us to a rotating base Release Captain. cc @bcreager 

learn more
- https://sourcegraph.slack.com/archives/C02VDNKBWDU/p1643934685497039
- https://sourcegraph.slack.com/archives/C02E07JDBD3/p1644345613736169
- https://sourcegraph.slack.com/archives/C0EPTDE9L/p1643915838386829
- https://github.com/sourcegraph/product-engineering-tracker/issues/66

**Comment by jjwon0** [comment]
any eta on this? we've been deleting symbols manually every 8-12h for a week now.

**Comment by JenRed777** [comment]
@chrismwendt What is your status on this? Were you able to create the patch or are you waiting for this to be included in the release going out next week?
