### ISSUE TITLE
Integrate APM into Sourcegraph

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#30699]
Add datadog APM agent & evaluate opentelemetry

Scoped under [RFC 575 ](https://docs.google.com/document/d/1xnAgloZB8sEkyhecjml2ByQl-aUCrJdWDYOBj3asA9g/edit#)

**Comment by daxmc99** [comment]
Hold open until final review from @keegancsmith

**Comment by keegancsmith** [comment]
@daxmc99 I see you are holding it open for me. I see lots of attached PRs/etc. What should I look at/review so you can close this out? :)

**Comment by daxmc99** [comment]
@keegancsmith SOC2 has taken most of my focus. I'm going to be coming back to this next week. The slack channel #wg-observability has some more context. 
I think the last thing we need before we turn this back on in cloud is ensuring that traceURLs work in Cloud. 
No immediate reviews are needed.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/cloud-devops - the "team/devops" label was applied to this issue.
