### ISSUE TITLE
Add (back) the ability to share links to code intel popover locations

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#30698]
#### Feature request description

Add back the ability to generate a shareable link to an identifier (code intel tooltip). As a user, I would like the ability to share a link to a specific code intel popover so that I can better communicate with my peers or document a specific token identifier. This contributes to our use cases for helping developer onboarding. 

Internal feedback: 
* [missing ability to send link to popover](https://sourcegraph.slack.com/archives/CHXHX7XAS/p1642694595303100)
* [missing ability to generate URL](https://sourcegraph.slack.com/archives/CHXHX7XAS/p1638880544350500?thread_ts=1638858834.347800&cid=CHXHX7XAS) prevents users from being able to share to token locations

How might we incrementally improve the j2d feature to incorporate back the ability to share URLs to a code intel popover?

#### Additional context

Prior to the token click-to-def implementation, users could click on a token, which would change the URL to be specific to the popover location. Since the [ j2d implementation](https://github.com/sourcegraph/sourcegraph/pull/28520), clicking now takes a user directly to the definition location and no longer generates a URL.

**Comment by macraig** [comment]
This will be part of the https://github.com/sourcegraph/product-engineering-tracker/issues/67 effort.

**Comment by scalabilitysolved** [comment]
Figma [design](https://www.figma.com/proto/YYEGdPNU4zirLS0uWfoYWW/Ability-to-pin-the-code-intel-popover?page-id=1118%3A2609&node-id=1118%3A3370&viewport=287%2C48%2C0.56&scaling=min-zoom&starting-point-node-id=1118%3A3370&show-proto-sidebar=1).

**Comment by jjinnii** [comment]
@macraig @chrismwendt 

After discussing with María, I've separated out this issue into two user problems: 
- This issue with the user problem of not being able to share URLs to a popover location (<- higher priority and tagged as being a low hanging fruit for the dev onboarding use case)
- Issue #34322 for the user problem of not being able to make the popover sticky

They _could_ be solved together, like in my original Figma designs, but does not necessarily have to. It's just that our original behavior (clicking on the token) did them together. 

@chrismwendt (may be a dumb question), is there a way to re-incorporate generating URLs to a popover technically, short of adding an icon into the popover? If not, I'll work on separate designs for a clearer "copy link" behavior.

**Comment by jjinnii** [comment]
Thanks @chrismwendt. With a shortcut or modifier key, we'd still need to communicate the pattern to users as we don't have a standard location (like a right click menu) to educate users on the shortcuts. 

Do you know if we have a utilize a[ right aligned button](https://www.figma.com/file/YYEGdPNU4zirLS0uWfoYWW/Ability-to-pin-the-code-intel-popover?node-id=1174%3A3518) in the popover currently? It's built into the Wildcard component in Figma by default, but I've never come across an instance of the popover with this button.

**Comment by jjinnii** [comment]
I think this works! I know right now when we have the "Find implementations" button, we just cut off the buttons and introduce a horizontal scroll -- should we ensure that the popover width always accounts for the full width of the buttons? 

Once clicked, there is a "success" state where we show ["Copied to clipboard"](https://www.figma.com/file/YYEGdPNU4zirLS0uWfoYWW/Ability-to-pin-the-code-intel-popover?node-id=1174%3A3518) as well! 

cc: @macraig

**Comment by macraig** [comment]
@chrismwendt do you feel you have a clear understanding of next steps clear based on @jjinnii's comment above?

**Comment by chrismwendt** [comment]
Adding a button to the hover popover makes sense 👌 

- Any preference on what the URL param should be? For example: `mux.go?share=L10:5`
- When you copy the link to the clipboard, should we change the URL to that, too?

Upon loading a link to a symbol:

- Should the hover popover be opened immediately?
- If the popover is opened immediately, how does the user dismiss the hover popover?
- Should the symbol be highlighted?
- When does the URL param get cleared?
- Should the ref panel be opened immediately?

**Comment by macraig** [comment]
> Any preference on what the URL param should be? For example: mux.go?share=L10:5
I would default to the URL we used before adding click to def (I cannot remember what the URL was though). 

> When you copy the link to the clipboard, should we change the URL to that, too?
Yes

> Should the hover popover be opened immediately?
Yes, as this is what the user intended to share.

> If the popover is opened immediately, how does the user dismiss the hover popover?
I think it should follow the same workflow as if you were to open a popover normally and be dismissed by hovering on another symbol or moving away from it (I think this is also how it used to be when you opened a symbol URL in the past so we'd be adding back that)

> Should the symbol be highlighted?
Yes

> When does the URL param get cleared?
When the user clicks on a line/symbol/button (any new click) like we do with line clicking

> Should the ref panel be opened immediately?
No

Note: I might be missing some technical constraints here so feel free to challenge my answers.

**Comment by chrismwendt** [comment]
> I think it should follow the same workflow as if you were to open a popover normally and be dismissed by hovering on another symbol or moving away from it (I think this is also how it used to be when you opened a symbol URL in the past so we'd be adding back that)

If the popover is dismissed by moving the mouse away, then it'll probably disappear immediately upon opening the link because the mouse is probably floating over some other part of the page.

The old behavior required you to click elsewhere. Do you recall if that behavior was confusing to users, or is there another reason this wasn't your first thought?

Maybe the popover needs to get pinned by either clicking the "Copy link" button or by opening such a link. It would get unpinned by clicking away or clicking the X on the top right (and we'd need to add such a button, too).

**Comment by macraig** [comment]
> The old behavior required you to click elsewhere. Do you recall if that behavior was confusing to users, or is there another reason this wasn't your first thought?

I don't think it was confusing, I just couldn't remember exactly how it worked before and thought unpinning by clicking away wasn't an option. Clicking away sounds like the best option IMO
