### ISSUE TITLE
VSCE: Add button to remove repo from file tree

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#30703]
Add the ability to remove a repository from the file tree.
Feedback from Noahj in [slack](https://sourcegraph.slack.com/archives/C02E3HHDZ98/p1643741917840709?thread_ts=1643711828.769109&cid=C02E3HHDZ98)

**Comment by jjinnii** [comment]
@abeatrix if we're trying to get this in before v1 launch, could you please send a screenshot of how you are going to implement this please? Thanks!

**Comment by abeatrix** [comment]
@jjinnii Sorry the V1 tag was added by accident lol we are not trying to get this in before v1 launch. it's currently working in my local build as below:
![deleterepo](https://user-images.githubusercontent.com/68532117/152608305-841164db-779c-4fd9-bdbb-fe5b57f0bb3d.gif)

**Comment by jjinnii** [comment]
Okay thanks @abeatrix ! I had created an issue to track this request in #30590 . No worries if we have a dup, just need to mention and close them tgt :)

**Comment by abeatrix** [comment]
Woops I will close this so we can continue tracking there , sorry about that
