### ISSUE TITLE
Fix: requesting specific number of commits w/ sub-repo perm filtering

### ISSUE THREAD

**Issue by mollylogue** [sourcegraph/sourcegraph#30704]
As highlighted in https://github.com/sourcegraph/sourcegraph/issues/28280 the "commits" page for a repo shows a limited number of commits and fails to display the "show more" link. This is because with sub-repo permissions filtering enabled when we request a specific number of commits we may filter some out and not get that exact number back (leading the frontend to think that these are all the commits available)

To fix: ensure that even with filtering enabled, we return the requested number of commits if possible.

**Comment by ryanslade** [comment]
My bad, I didn't realise you had created this issue and I created a [duplicate](https://github.com/sourcegraph/sourcegraph/issues/30750)

As the other one is already shared externally and linked to the PR I'll close this one.
