### ISSUE TITLE
Increase disk space on gitserver on cloud and re-enable silenced alerts

### ISSUE THREAD

**Issue by indradhanush** [sourcegraph/sourcegraph#30721]
The less than 15% disk space remaining alert is firing. We need to action on this immediately next week.

**Comment by ryanslade** [comment]
@filiphaftek Is this still something we need to do on Cloud?

**Comment by indradhanush** [comment]
@ryanslade Some of the instances are close to the 20% threshold which is preventing us from re-enabling the alerts for gitserver disk space on cloud. 

There was some plan to expand the disk space further but it looks like it's yet to be done. 

[Link to relevant Slack thread](https://sourcegraph.slack.com/archives/C0J618TTM/p1644993840247649).
