### ISSUE TITLE
If repo does not exist on instance, hover just shows loading forever

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#3072]
![image](https://user-images.githubusercontent.com/10532611/55278524-acc85080-530d-11e9-9b96-bd428d419644.png)

If the repo doesn't exist on Sourcegraph, no hover should be shown.

I don't know in which component this bug is in (bext, extension API, TypeScript extension). I see though that no WebSocket is created.

**Comment by lguychard** [comment]
I don't think this still happens @felixfbecker ?

**Comment by felixfbecker** [comment]
Looking at the code, this should now throw a `RepoNotFound` error before even initializing the code view. We don't handle that error, and probably should (log and ignore), because it will break the `codeViews` Observable pipeline. But this issue can't happen anymore afaict
