### ISSUE TITLE
No schema reference for extension package.json contributes schema

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#3073]
https://docs.sourcegraph.com/extensions/authoring/contributions is the only docs we have on the `contributions` field, but there is no schema references docs as we have for config (autogenerated from the JSON schema). The schema is very complex so it is important that we have good docs on it, but currently there are no docs for many things, e.g. adding buttons to the toolbar.

**Comment by lguychard** [comment]
Auto-generate docs from the existing schema (exhaustive docs).
