### ISSUE TITLE
Code Insights: Fetch a first indexed repository URL for the first demo section on the in-product landing page

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#30745]
[Related Slack thread](https://sourcegraph.slack.com/archives/C01RVEVPWLC/p1644233373567219)

## Background

What is the right value for the repositories field for the code insights demo? Currently, we use [github.com/sourcegraph/sourcegrpah](http://github.com/sourcegraph/sourcegrpah) repo for the repo field and on the k8s it looks good. 

But our on-prem customers don't have sourcegraph repo in their index DB so we will have a validation error about this repo value as soon as the page is rendered.

<img width="549" alt="Screenshot 2022-02-07 at 14 32 37" src="https://user-images.githubusercontent.com/18492575/152796656-7005c73d-7a07-4249-8586-da9683801eaa.png">

So possible options here
- We should somehow process customer repos and pick the right one for the demo insight landing page. This implies some effort from backend engineers and as we discussed this on the last team sync we couldn't process repo on BE to be 100% that this repo is a good candidate for the TODO (or any other) demo code insights.
- Fetch the first indexed on the frontend and put this URL in the repositories field. This is chip and should be easy to do but in this option, there is no guarantee that this repo is a good candidate for the TODO example. It might be some non-tech-related repo there is no TODO and hence it would be a flat (no-data) chart. 
```gql 
query FirstIndexedRepository {
  repositories(first: 1) {
    nodes {
      name
    }
  }
}
```
- Do nothing and leave this field empty and let users fill this field out by themself, hopefully, we have suggestions over this field so it should be easy to do for them.

**Comment by AlicjaSuska** [comment]
Thank you for writing this @vovakulikov. We should go with option 1 or 2. Option 3 (empty field) would cause us to show an empty chart - basically, it would defeat the purpose of having the chart in the first section.

If it's possible (and we have capacity), option 1 would be the best solution - if we can ensure that the chart is showing results different than 0, it's perfect.

If we go with option 2 (first indexed repo) - we're risking potentially showing a chart with a line on value 0. It's fine for V.1 but it would be ideal to come back to it later on and implement option 1. 

Why is option 2 fine for v.1:
- there is a high probability that repo will contain some TODOs in many cases
- even if (in the worst case) we show the line on 0, it still creates some understanding of the chart + use will be inclined to edit the repo field (where we have suggestions so it's a fairly smooth experience)

What I'd like to avoid at all costs is to show the 'no data' state of the chart.

**Comment by Joelkw** [comment]
Discussion from team sync: can we grab a repo that matches a `select:repo TODO count:1` search on the frontend and put it in? 

Do we have a query tool to do a streaming search instead of the graphQL API? Use streaming search if available. 

What if no match? We need a fallback that just grabs any repo that is on the instance, like `select:repo count:1`. 

Could we store this elsewhere? Long term yes but out of scope for this.
