### ISSUE TITLE
Code Insights: Create a default personal dashboard for new users who haven't created any dashboards yet

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#30746]
## Background 

For the new users currently, we have just one default dashboard - the "All insights" dashboard. We have to create a user's personal dashboard in case this user doesn't have any other dashboards yet. [Designs](https://www.figma.com/file/EFgTP7gpdpQSEo1n4FUfsW/In-product-landing-page-WIP?node-id=1624%3A23488)

## Technote

Possible options here
- Call `createDashboard` mutation on the frontend if a user doesn't have any other custom dashboards.
- Change behavior on the backend and make that all users have at least one personal dashboard. Interesting what @sourcegraph/code-insights-backend think about it. Is it even possible (relatively easy) to do with the dashboard arch that we currently have?

**Comment by Joelkw** [comment]
@vovakulikov  I believe in our sync we decided this was not necessary, correct? I thought I commented and closed the issue but don't see now.

**Comment by Joelkw** [comment]
https://github.com/sourcegraph/sourcegraph/issues/29943#issuecomment-1031916336 yep, closing.
