### ISSUE TITLE
Resource Estimator: Generate new data

### ISSUE THREAD

**Issue by caugustus-sourcegraph** [sourcegraph/sourcegraph#30765]
Generate / gather information about resource usage from live sources, and update in a spreadsheet similar to [this](https://docs.google.com/spreadsheets/d/1in1sfEkgXGVB2_HInX93bxNOFJPA_r3ugfD5lEKCk_U/edit#gid=0).

Potential sources:
* Existing customer technical docs (managed by CE)
* Internal deployments and managed instances
* [Historical CS issues](https://github.com/sourcegraph/support-tools-internal/tree/main/resolved-tickets)

Deadline: Friday 5/27

**Comment by kevinwojo** [comment]
Additional data from CE & CS collaboration:

**Comment by caugustus-sourcegraph** [comment]
Next steps:
- Check with CE (and CS?) about any customer information they have. Goal is to get 5 customers of data.
- Start short list of metrics / characteristics that define a healthy deployment. This can be very rough, we'll use this to start gauging our confidence in the data.

By Monday we'll be in a place to begin analyzing the data and provide resource estimations based on the customer profiles.

**Comment by kevinwojo** [comment]
Historical artifact: https://docs.google.com/spreadsheets/d/1in1sfEkgXGVB2_HInX93bxNOFJPA_r3ugfD5lEKCk_U/edit#gid=0

Original data source for resource estimator

**Comment by briemcnally** [comment]
@kevinwojo is this complete?

**Comment by briemcnally** [comment]
Complete please see: https://docs.google.com/spreadsheets/d/1N7X_OXDwKk0QSR2Ghbj7ZhjVrQXcMNj-yC8mF1amBi4/edit#gid=1332137664
