### ISSUE TITLE
Resource Estimator: Generate Docs Prototype for Scaling Overview for Services

### ISSUE THREAD

**Issue by caugustus-sourcegraph** [sourcegraph/sourcegraph#30769]
Use the data from https://github.com/sourcegraph/sourcegraph/issues/30765 to update the guidance currently provided by the resource estimator into a static document. Add any missing services and, if feasible, disk space estimates.

In Scope:
- [x] #37707
- [x] Gather feedback from CE & Design on the format
- [x] Submit for tech review - so that all engaged teams are providing sign off that the info is correct
- [x] #38853

Out of scope:
 - updating the resource estimator calculator (will revisit after this quarter)

**Comment by kevinwojo** [comment]
https://github.com/sourcegraph/sourcegraph/issues/11205

**Comment by abeatrix** [comment]
Google Docs created: https://docs.google.com/document/d/1pvzdVdI00evOcvFCjNuLioZEs7fr-Sx5kkUdb29wt94/edit?usp=sharing

Status: WIP and not ready for review
