### ISSUE TITLE
standardize how namespaced entities are implemented in the backend

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#30763]
"Namespaces" are what we currently use to scope the ownership/permissions of different entities in the sourcegraph backend. A "namespace" is defined either a `user_id` or an `org_id`. If present, the namespace user ID indicates the entity is scoped to the user. If a namespace org ID is present, it indicates the entity is scoped to the org. 

For example, in the database notebooks have a `namespace_user_id` and a `namespace_org_id`. Those two columns are mutually exclusive. This pattern is common in our DB layer. 

Currently, there is a lot of duplication in logic for namespaces. We have [checks for the mutually-exclusive invariant](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/notebooks/store.go?L232-234) uplicated all throughout the code, as well as with [CHECK constraints in the DB](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@0d560445d13a887db7e58e0f5e8450fb90dc40f2/-/blob/internal/database/schema.md?L1625). We don't have an easy way of checking permissions against a namespace (or if we do, it's not used widely). 

Basically, I think there is a lot of opportunity to reduce duplication around namespaces and to establish a set of best practices for them. 

Another thing maybe worth thinking about: centralizing the handling of namespaces might make it easier to implement something like "teams" in the future.

-------------

CAVEAT: This section is just a few things I've thought about briefly. They are in no way vetted or researched, just potential areas of improvement/deduplication. Feel free to ignore if you think of better ways to handle this 😄 

_**Create a `namespace` composite type in Postgres**_

We could replace all the `namespace_user_id` and `namespace_org_id` column pairs with a database type that captures the idea. Then we have a single column that we're working with rather than two columns with mutual constraints. 

```sql
CREATE TYPE namespace AS (
    user integer,
    org integer
);
```

**_Create a backend type that maps to the Postgres type_**

Once we have a DB type, we could pretty easily create a backend `Namespace` type that implements the `sql.Valuer` interface so we can drop the type directly into our db-layer types. 

```go
type Namespace {
  UserID *int64
  OrgID *int64
}

func (n *Namespace) Scan(value interface{}) error {
  _, err := fmt.Sscanf(string(src.([]byte)), "(%d,%d)", &n.UserID, &n.OrgID)
  return err
}

func (n *Namespace) Value() (driver.Value, error) { 
  return fmt.Sprintf("(%d, %d)", n.UserID, n.OrgID), nil
}
```

**_Create Postgres utility functions for permissions checks_**

With a namespace composite DB type, we could then implement db functions like `userInNamespace(userID, namespace)` that replaces complex permissions checks like [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@0d560445d13a887db7e58e0f5e8450fb90dc40f2/-/blob/enterprise/internal/notebooks/store.go?L102). Bonus points if this facilitates better query optimization. 

**_Figure out what the `names` table is_**

We have a `names` table, which seems to be what we use to determine the uniqueness of a "name", but it also has the exact format of namespaces. I don't know if we could repurpose this, or if we should repurpose this, but it's a pretty [minimally used table](https://sourcegraph.com/search?q=context:global+repo:github.com/sourcegraph/sourcegraph%24+from+names&patternType=literal), and it's not actually clear to me whether it's needed at all.

**_Interop with `graphqlbackend.Namespace`_**

We use namespaces much more in the `GraphQL` layer and have a `NamespaceResolver` [type](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/namespaces.go?L103:6), so having good helpers to translate between these would be nice.

**Comment by bobheadxi** [comment]
A recent RFC that arose on what appears to be the same topic: [RFC 617 Unifying "user groups" permissions models](https://docs.google.com/document/d/1B3A-PQTykOSnp6BtHZTbIFpSRrvbiV-0FrnukJeaM3A/edit#). I've made mention of this issue in the RFC: https://docs.google.com/document/d/1B3A-PQTykOSnp6BtHZTbIFpSRrvbiV-0FrnukJeaM3A/edit?disco=AAAAV4csOlo

**Comment by malomarrec** [comment]
Hey @camdencheek, this issue didn't have a team label. Given you created it, I assigned you and added your team label. Feel free to unassign yourself. If this is not the right label, can you make sure to add the right one?

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.
