### ISSUE TITLE
Resource Estimator: Internally document summaries of service behavior and scaling info

### ISSUE THREAD

**Issue by caugustus-sourcegraph** [sourcegraph/sourcegraph#30768]
Update resource estimator documentation to include summaries of the key metrics or behaviors contributing to resource usage for each service.

* Use comments in https://github.com/sourcegraph/resource-estimator/blob/master/internal/scaling/references.go as a basis
* If it's obvious who a service owner is, ask them for advice
* Reference https://docs.sourcegraph.com/admin/install/kubernetes/scale#tuning-replica-counts-for-horizontal-scalability for ideas

**Comment by caugustus-sourcegraph** [comment]
https://github.com/sourcegraph/customer/issues/722 has some extra info on code-intel and code insights DB patterns. 

We see some general patterns, but should back these up with real-world data:
- More repos = more disk usage in Code Insights
- Bigger repos = more memory usage in Code Insights
- Memory usage in Code Intel and Postgres increases with larger payloads (== bigger repos??)
- Code Intel memory usage is higher than Code Insights
- Batch changes uses very little disk space and uses the postgres DB

**Comment by caugustus-sourcegraph** [comment]
Another resource: https://docs.sourcegraph.com/code_intelligence/explanations/features#symbol-search-behavior-and-performance

**Comment by kevinwojo** [comment]
There are some hints left in the resource estimator's source code: https://sourcegraph.com/github.com/sourcegraph/resource-estimator/-/blob/internal/scaling/references.go?L56

**Comment by briemcnally** [comment]
@abeatrix is this done based on the survey data?

**Comment by abeatrix** [comment]
@briemcnally I'd say so! Link to [docs](https://docs.google.com/document/d/1dQPkU4ajp6WlgIvfSo2iYk4xgzhT1BrZ65mSGklDIuw/edit#heading=h.bfnn2f5y1eqc)
