### ISSUE TITLE
Server-side batch changes (SSBC) Experimental Phase

### ISSUE THREAD

**Issue by christinaforney** [sourcegraph/sourcegraph#30778]
NOTE: CHRISTINA AND NICK ARE DOING AN EXPERIMENT. IGNORE FOR NOW.

## Problem to solve

Two problems:
1. Batch changes are run locally on machines, which limits a developer's ability to run massive batch changes depending on the hardware they have available.
1. The fact that you have to run batch changes on your machine is a complicated workflow that takes an upfront investment to run a simple batch change, so there is a high cost to entry for a new user of batch changes.

We have heard from our batch changes customers that this is limiting adoption of rolling out batch changes across an organization. By launching this, we expect adoption and an increase in revenue from customers X, Y, Z.

## Measure of success

3 customers create 200+ changesets with server-side Batch Changes.
TO DO: Link to chart for tracking current progress.

## Solution summary

We are building executors so Sourcegraph has the ability to run arbitrary code. This will allow us to run batch changes server-side, among other things like auto-indexing of precise code intelligence (this is shared infrastructure). This will enable us to build easy-to-use batch changes flows into our UI, and will enable developers to create massive batch changes without having to think about how to provision resources.

Artifacts:
- [PD 26](https://docs.google.com/document/d/1MnfaA9P7mtur7aQbMvy2x96_zy_IrOhY-MbGUo5I5wk/edit)
- #27841 

## What specific customers are we iterating on the problem and solution with?
- https://github.com/sourcegraph/accounts/issues/565
- https://github.com/sourcegraph/accounts/issues/537
- https://github.com/sourcegraph/accounts/issues/580

## Use case

NOTE: CHRISTINA AND NICK MADE UP THIS SECTION AS AN EXAMPLE OF WHAT A "GOOD" DESCRIPTION LOOKS LIKE. THIS SECTION IS NOT REAL OR A REPRESENTATION OF WHAT THIS CUSTOMER SAID.

Batch changes is a critical part of most of the use cases because it facilitates actually editing code (which improves code health, fixes vulnerabilities, fixes incidents, and aids in refactoring and re-using code). 

https://github.com/sourcegraph/accounts/issues/565 is specifically interested in server-side batch changes so that they can more quickly respond to and fix incidents like Log4j. Both dimensions of the problem statement are important to them. They need it to be easy to create a change to fix security vulnerabilities so it can be done quickly and by anyone on the security team. They also need batch changes to be able to scale across all of the code at the organization to resolve incidents like Log4j.

## Delivery plan

- [ ] TO DO

**Comment by jyavorska** [comment]
We will not use this demo issue for actually tracking this work, so closing.

**Comment by nicksnyder** [comment]
I am also deleting the item in the project that links to this

**Comment by jyavorska** [comment]
This was a sample issue @malomarrec please use https://github.com/sourcegraph/sourcegraph/issues/30816 for this feature in the roadmap.
