### ISSUE TITLE
Resource Estimator Docs: How to monitor and adjust resource utilization / performance

### ISSUE THREAD

**Issue by caugustus-sourcegraph** [sourcegraph/sourcegraph#30770]
Write documentation on how customers can monitor and adjust resource limits based on their own performance data.

The FAQ has some good questions, such as https://docs.sourcegraph.com/admin/faq#what-should-i-look-at-when-my-instance-is-having-performance-issues and https://docs.sourcegraph.com/admin/faq#how-much-resources-should-i-add-after-receiving-alerts-about-running-out-of-resources, which could link to this documentation or be expanded on in-place.

**Comment by abeatrix** [comment]
@briemcnally sorry for overlooking this. 

May I get some clarifications on this, please? Perhaps an example of the information we should add to the existing docs?

**Comment by abeatrix** [comment]
For reference, I wrote the original docs as requested by one of our customers. 
The questions in the FAQ were provided by them here https://github.com/sourcegraph/customer/issues/332#issuecomment-839118015

**Comment by abeatrix** [comment]
@briemcnally do you think [the Scaling Overview for Services - Prototype docs](https://docs.google.com/document/d/1pvzdVdI00evOcvFCjNuLioZEs7fr-Sx5kkUdb29wt94/edit#) we are working on would cover this issue?

**Comment by abeatrix** [comment]
Closing since this is covered by the works done in https://github.com/sourcegraph/sourcegraph/issues/30769
