### ISSUE TITLE
Project newcomers: how are you finding the getting started experience?

### ISSUE THREAD

**Issue by kevinburke** [sourcegraph/sourcegraph#308]
Kevin from Sourcegraph here. We have done a fair amount of work to get the repository ready for prime time, and I wanted to get your feedback on how you have found that process.

- What was confusing?
- Was there anything you wanted to do, that you couldn't figure out how to do?
- Did you follow the local development instructions? Did you get the project up and running ok?

**Comment by jeroenherczeg** [comment]
Hi,

Thank you for making this open!

I quickly found https://about.sourcegraph.com/docs/ under Try it yourself in de README file.
Getting it up and running was super easy with the docker command.
Under configuration, I added Github token and added a personal repo. It installed the PHP language server automagically. And I was searching through code in less then 5 minutes!

The only thing that I did wrong afterwards was, I wanted to add a public github repo for a package I heavily use. I went to configuration, clicked on "Add an other repository" and added the github clone url. When I saw it couldn't clone this, I saw the "Add public github repository" button under repositories , and fixed my mistake.

I am exited to explorer more of its capabilities and experimenting with search and api!
