### ISSUE TITLE
Change Docker Compose Caddy Container image to 2.4.2 Or Greater

### ISSUE THREAD

**Issue by DaedalusG** [sourcegraph/sourcegraph#30805]
#### Feature request description

The newever versions of Caddy have some nice automation features, and most of the community forums and documentation for caddy now seems to assume users are running v2.4.2 or greater -- 

#### Is your feature request related to a problem? If so, please describe.

I recently encountered an issue in which my local Lets Encrypt cert was revoked due to problem with the certs identified by Lets Encrypt

I discovered this by receiving the following email
> Hello,
>
>Please immediately renew your TLS certificate(s) that were issued from
Let's Encrypt using the TLS-ALPN-01 validation method and the following
ACME registration (account) ID(s):
>
> <REDACTED>
>
>We've determined that an error made it possible for TLS-ALPN-01
challenges, completed before today, to not comply with certificate
issuance requirements. We have remediated this problem and will revoke
all unexpired certificates that used this validation method at 16:00 UTC
on 28 January 2022. Please renew your certificates now to ensure an
uninterrupted experience for your site visitors.
>
>We apologize for any inconvenience this may cause. If you need support
in the renewal process, please comment on our forum post. Our staff and
community members are available to help:
>
>https://community.letsencrypt.org/t/170449
>
>Thank you,
>
>The Let's Encrypt Team

After doing a little research I learned that the [newer caddy versions automatically detect such revocations](https://community.letsencrypt.org/t/questions-about-renewing-before-tls-alpn-01-revocations/170449/21) and acquire a new cert -- unfortunately v2.0.0 does not. I was able to resolve this issue by navigating to the storage location of CA certs in the caddy container of a running deployment `/caddy-storage/data/caddy/certificates # rm -rf acme-v02.api.letsencrypt.org-directory/`, I then restarted the container and it acquired a new cert. 

#### Describe alternatives you've considered.

-- we could just leave this as is, but it would be nice to get things more in line with the current caddy.

**Comment by virginiaulrich** [comment]
This is now done :)
