### ISSUE TITLE
Batch Changes on Cloud

### ISSUE THREAD

**Issue by jyavorska** [sourcegraph/sourcegraph#30801]
## Problem to solve

Batch changes, a powerful enterprise focused tool allowing users to 'find-and-replace' across their codebase, is not available to cloud customers at all today. 

11% of customers who requested access via the Cloud waitlist listed "making wide-scale code changes" as their top value for Sourcegraph, and those users needs are not fully being met by Sourcegraph Cloud today. 

## Measure of success

- x Batch Changes Cloud MAUs
- secondary: register -> activate conversion metric

## Solution summary

A limited, downscoped (TBD) version of Batch Changes on Cloud, invite-only for testers (customers, OSS community)

Artifacts:
- TO DO

## What specific customers are we iterating on the problem and solution with?

- TO DO

## Impact on use cases

All use cases

## Delivery plan

Depends on
- Cloud pricing is figured out.
- Cost analysis
- Gating/billing on cloud.
- Enterprise tier in the cloud.

- [ ] TO DO

**Comment by malomarrec** [comment]
This is not relevant anymore, as Cloud = MIs and Batch Changes is already supported on MIs
