### ISSUE TITLE
Find and replace without writing code

### ISSUE THREAD

**Issue by jyavorska** [sourcegraph/sourcegraph#30803]
## Problem to solve

Using batch changes requires running a code rewrite tool (refactoring tool, comby, sed) which many users don't intuitively grok. Iterating on simple batch changes takes time, and isn't intuitive for many devs.
The consequence is that today, only a small niche of users use batch changes. We have an opportunity to make batch changes useful for every dev.

## Validation

- We had conversations with https://github.com/sourcegraph/accounts/issues/3, who initially expected that all that batch changes does is search and replace strings and found that compelling on its own. See [notes](https://docs.google.com/document/d/1ywVPx1uFmG5MjRVYsrRV5VZSvyNF5_AK_ef-ByZgtVI/edit#heading=h.ey3oi8j49w6b).
- We had similar feedback from https://github.com/sourcegraph/accounts/issues/7583. Example use cases where rebranding a project (eg. after an acquisition), which involves changing logo URLs or names across a large codebase.

## Solution summary

Users can "replace in files" just like they do in the IDE:
- MVP: string search and replace
- Later: regex, structural search and replace

See [RFC 713: Compute-powered batch changes](https://docs.google.com/document/d/1c9vGgSfh35HNzhPSMltgVkMA9B1NO4QF5GgZwFlt5Ys/edit#heading=h.trqab8y0kufp) for current candidate

[mockup](https://www.google.com/url?q=https://www.figma.com/proto/q8pwZ1WECUTIJa3D0UzlOS/Search-And-Replace-Batch-Changes?page-id%3D37%253A6133%26node-id%3D51%253A7646%26viewport%3D1789%252C532%252C0.63%26scaling%3Dmin-zoom%26starting-point-node-id%3D51%253A7646&sa=D&source=docs&ust=1658501644158787&usg=AOvVaw1Xftx3JgdGjx-IK8mlPyTj)

## Measure of success

- MAUs increase 2x
- number batch changes/customer increase x3

## Delivery plan

- [x] map out solution candidates in RFC

**Comment by malomarrec** [comment]
@danielmarquespt tagging you in there, it's now extremely likely that this is our next area of focus.

**Comment by malomarrec** [comment]
@courier-new I turned this into a tracking issue for the compute work. Thanks for drafting up a plan!
Whenever you proposed estimate, I added them as labels as a first order approximation, which doesn't prevent us from re-estimating at next sprint planning :)

**Comment by malomarrec** [comment]
@courier-new I'm using this issue to document feedback on find-and-replace without writing code, even though we might pursue a different implementation path than previously
