### ISSUE TITLE
Auto LSIF Indexing on Cloud

### ISSUE THREAD

**Issue by jyavorska** [sourcegraph/sourcegraph#30804]
## Problem to solve

Auto-Indexing of LSIF data is a powerful feature that removes the need for users to upload the LSIF files for precise code intelligence. Auto-Indexing is already turned on for several repositories on Cloud (the Sourcegraph repo, several go repos, etc) but is not a user-accessible feature. 

Precise code-intelligence is one of Sourcegraph's most powerful features, esp when compared directly to GitHub code search. On-prem enterprise customers often have admin/DevOps teams who bake LSIF creation into their CI/CD systems. Conversly SMBs do not, meaning without auto-indexing, they have to undergo significant work to setup LSIF uploading into Cloud. 

## Measure of success

TODO

## Solution summary

Enable a user-focused way for auto-indexing, understand how this impacts our profit margins, and understand any security requirements. 

Artifacts:
- TO DO

## What specific customers are we iterating on the problem and solution with?

- TO DO

## Impact on use cases

TODO

## Delivery plan

- [ ] TO DO

**Comment by jyavorska** [comment]
@macraig in the spreadsheet (https://docs.google.com/spreadsheets/d/1hmQLdqO1KYyNlXKpOirvxL0YVr2VtPokPEDQ-YWxxYo/edit#gid=0) this had no tier or quarter. I put in guesses (l3 and fy24q2) but these are probably wrong and you should update them.

**Comment by macraig** [comment]
No longer relevant due to company strategy updates
