### ISSUE TITLE
Code Insights "OOTB Templates"

### ISSUE THREAD

**Issue by jyavorska** [sourcegraph/sourcegraph#30819]
## Problem to solve

It currently takes ~5 minutes to make your first insight – read over the UI, possibly check docs, write a correct search

Customers want to know how to get the most value from insights and have asked for this. Also, if we can get the time to first insights <60 seconds or in-product show a better version of this, we'll see faster and wider adoption during trials.

## Measure of success

topline insights ARR, leads; secondary: direct usage

## Solution summary

https://sourcegraph.productboard.com/feature-board/1793095-code-insights/features/9370699/detail

Artifacts:
- TO DO

## What specific customers are we iterating on the problem and solution with?

- https://github.com/sourcegraph/accounts/issues/531
- https://github.com/sourcegraph/accounts/issues/5066
- https://github.com/sourcegraph/accounts/issues/246

## Impact on use cases

Code health, code re-use, fixing vulnerabilities

## Delivery plan

https://sourcegraph.productboard.com/feature-board/1793095-code-insights/features/9370699/detail

- [ ] TO DO

**Comment by Joelkw** [comment]
Done – visit the bottom of https://demo.sourcegraph.com/insights/about?dashboardId=all to see them!

**Comment by Joelkw** [comment]
Closing!
