### ISSUE TITLE
Bitbucket Cloud support

### ISSUE THREAD

**Issue by jyavorska** [sourcegraph/sourcegraph#30815]
## Problem to solve

Batch Changes is not available on Bitbucket Cloud

- Bitbucket server will EOL in 2024 and is deprecated.
- Some deals are dependent on BB Cloud ($200k IARR overall, not all deal breakers)

## Measure of success

1 customer on Bitbucket Cloud

## Solution summary

TODO

Artifacts:
- TO DO

## What specific customers are we iterating on the problem and solution with?

- https://github.com/sourcegraph/accounts/issues/250
- https://github.com/sourcegraph/accounts/issues/8016
- https://github.com/sourcegraph/accounts/issues/8267
- 

## Impact on use cases

Code reuse

## Delivery plan

#24199

- [ ] TO DO

**Comment by chrispine** [comment]
@malomarrec Do we mark this done now, or when it's released?
