### ISSUE TITLE
Improved monorepo support

### ISSUE THREAD

**Issue by jyavorska** [sourcegraph/sourcegraph#30811]
## Problem to solve

Some core user flows of Sourcegraph are slow or unusable on large-scale monorepos.

Monorepos at 6GB to 15GB in size are not consistently performant.

## Measure of success

At a P75 level, a synthetic repo of 15GB will index in less than 30 minutes, index searches complete in < 2s and unindexed searches complete in < 10s

## Solution summary

Support incremental Zoekt indexing as well as improvements to unindexed searches

Artifacts:
- TO DO

## What specific customers are we iterating on the problem and solution with?

- https://github.com/sourcegraph/accounts/issues/6716
- https://github.com/sourcegraph/accounts/issues/574
- https://github.com/sourcegraph/accounts/issues/578

## Impact on use cases

All use cases

## Delivery plan

- [ ] TO DO

**Comment by jyavorska** [comment]
@eugeniaft now that the last release of Q1 has shipped we should know if this made it or not. Can you please either close it and mark it as done or move it to Q2 or whatever quarter it is targeting now?

**Comment by eugeniaft** [comment]
The work in Q1 has been focused on research and testing.
Here are the update on deliverables:
- Incremental indexing prototype is ready for testing.
- Researched and defined prototype for unindexed search using both searcher and zoekt to start testing in Q2.
- Created testing framework to measure performance improvements: creation of gigarepo (repo with 15 GB head size) and sentinel queries.
