### ISSUE TITLE
Gather feedback and iterate on Notebooks

### ISSUE THREAD

**Issue by jyavorska** [sourcegraph/sourcegraph#30812]
## Problem to solve

Following Beta launch of Notebooks we want to iterate and reifne the feature based on customer feedback to integrate it more deeply into the developer velocity and onboarding use case.

Notebooks have capabilities to integrate with onboarding and velocity use cases (and others) but isn't yet specifically targeted at them. We want to refine the UX toward that use case based on user feedback.

## Measure of success

20% of cloud teams have created at least 1 Notebook by end of Q2

## Solution summary

- Post-Notebooks Beta, engage with our users to better understand  their pain points with onboarding and Notebooks
- Invest more in dogfooding Notebooks to accelerate development

Artifacts:
- TO DO

## What specific customers are we iterating on the problem and solution with?

https://github.com/sourcegraph/accounts/issues/1503

## Impact on use cases

Onboarding & velocity

## Delivery plan

Potentially dependent on a Sourcegraph-wide implementation of a categorization method (such as folders or tags) to group Notebooks together. This is likely a paradigm we'd want to make pluggable across products (folders/groups of Insights, for example) and so that could delay development in the case where we find that functionality is key for users.

- [ ] TO DO

**Comment by jyavorska** [comment]
@benvenker finding product-market-fit is a pretty open ended topic. Is there some way to constrain what we plan to achieve in Q2 here?

**Comment by benvenker** [comment]
This could use a tune up. It was one of our deliberately fuzzy items from the ask to put the full year’s roadmap items together. Will update as part of our planning this week.

**Comment by benvenker** [comment]
@jyavorska I'm thinking we should just cancel this one or replace/rename it. We are leaving open the possibility that we could have nontrivial Notebooks development in Q2 if we're actively onboarding clients, but our preference is to let user feedback come in over the quarter and build up a Q3 and beyond roadmap based on that. Any thoughts on what to do with this issue in light of that?

**Comment by jyavorska** [comment]
@benvenker if you want to "reserve time in the roadmap" or make it visible I'd call this something like "Gather feedback and iterate on Notebooks". As much as you can constrain it that's a win (for example, are you focusing on a specific use case?) I just think "Find PMF" specifically is a bit too vague.

**Comment by jyavorska** [comment]
@benvenker this was set to Q2 with a launch date of September, for now just to make things consistent I've set the launch date to July. Feel free to update it one way or the other when you make a final decision.

**Comment by benvenker** [comment]
Ok makes sense, thanks.
