### ISSUE TITLE
Code Insights on Cloud 

### ISSUE THREAD

**Issue by jyavorska** [sourcegraph/sourcegraph#30822]
## Problem to solve

Code Insights is not available on cloud now

- To collect cloud ARR
- To quickly learn/iterate (no wait for on-prem)
- To differentiate our cloud product vs competition

## Measure of success

- Primary: cloud ARR / upgrades to Enterprise plans
- Secondary: leads and product feedback

## Solution summary

Finish building out "groups of repos" (use: groups < all instance repos, but >10) backend capabilities for on-prem, then take the learnings to Cloud

Artifacts:
- TO DO

## What specific customers are we iterating on the problem and solution with?

- https://github.com/sourcegraph/accounts/issues/2007
- https://github.com/sourcegraph/accounts/issues/4189

## Impact on use cases

All use cases

## Delivery plan

Depends on Cloud launch success – we'll wait to confirm Cloud is a revenue generating product and ready for Insights

- [ ] TO DO

**Comment by Joelkw** [comment]
Closing as this is no longer relevant given cloud shifts.
