### ISSUE TITLE
Code Insights GA Launch 

### ISSUE THREAD

**Issue by jyavorska** [sourcegraph/sourcegraph#30820]
## Problem to solve

We can't collect ARR or promote insights publicly until launch. 

This feature is highly requested from customers, already brought in ARR, helps differentiate from competitors and solve for all our use cases. 

## Measure of success

Overall ARR from code insights in year 1, as well as growth trends and deal attach rate. 

## Solution summary

We are going to release code insights in February. For more concrete details see this [overall FAQ.](https://docs.google.com/document/d/19Ys8JcIUhXb6ETU0wqL-3oO-CrOrEhgHSJLHo_ofCPA/edit) 

The GA specific launch issues can be [found here](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+is%3Aopen+label%3Ainsights-GA), and the marketing source of truth is [the asana board ](https://app.asana.com/0/1200993686288594/list). #code-insights-ga-gtm for any questions. 

## What specific customers are we iterating on the problem and solution with?

- All, but especially users-not-yet-purchased customers/prospects here: https://docs.google.com/spreadsheets/d/1e4tu3OA6KBXoeORJuqbQaRweaB403DK-V0pA-bLJ3Rg/edit#gid=0 

## Impact on use cases

[All use cases – see this document.](https://docs.google.com/document/d/1NXR0eX9VseJGT_BfCata_WR-yP0VxPsyYIyrsTOuoPs/edit#)

## Delivery plan

Broadly, these are some sources of truth for in-progress marketing and engineering items. There is a long tail of smaller items that @Joelkw is personally tracking. If you have specific questions sometime before the launch (which is [very soon](https://docs.google.com/document/d/19Ys8JcIUhXb6ETU0wqL-3oO-CrOrEhgHSJLHo_ofCPA/edit)) please just reach out to him via #code-insights-ga-gtm. 

- [x] [delivered product](https://demo.sourcegraph.com/insights/dashboards/all)
- [ ] GA release cut with [GA issues](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+is%3Aopen+label%3Ainsights-GA) shipped - Feb 18
- [ ] [GA FAQ doc](https://docs.google.com/document/d/19Ys8JcIUhXb6ETU0wqL-3oO-CrOrEhgHSJLHo_ofCPA/edit)
- [ ] GA release same-day run of show - [WIP document](https://docs.google.com/document/d/1fqAMXqJ53XyVetfGxmMItAK4AizkGHkgVUc9v5T5uEg/edit) - date private, see the doc
- [ ] [The asana board ](https://app.asana.com/0/1200993686288594/list) for marketing tracking

**Comment by jyavorska** [comment]
@Joelkw it looks like https://github.com/sourcegraph/sourcegraph/issues/27584 are duplicates now. You should merge them in some way so there's only one. I'd recommend keeping this one since it already has the new structure, but up to you.

**Comment by Joelkw** [comment]
Thanks @jyavorska ! Closing that other one.

**Comment by jyavorska** [comment]
@Joelkw I set this to done, from in-progress. Let me know if this was wrong and you are keeping it open for a reason.

**Comment by Joelkw** [comment]
Closing!
