### ISSUE TITLE
Track account creation from VS Code extension CTAs 

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#30859]
In order to understand the effectiveness of the VS Code extension in Sourcegraph Cloud account creation (Acquisition), we want to log UTM parameters when a CTM for account creation is clicked in the VS Code extension.

A list of events for UTM parameters can be found in the [UTM tracker](https://docs.google.com/spreadsheets/d/1U0HRC5WVz3tsP6z9pqDLG8igTMSf2-pQGhbRoVn_iu0/edit#gid=0). I've added VS Code events in lines 142-144, one for each CTA we have in the VSCE:
- [Sidebar CTA](https://www.figma.com/file/EXXvfxVwtCIsrbQez4rPlF/VS-Code-Extension-MLP?node-id=1371%3A2976)
- [Banner CTA](https://www.figma.com/file/EXXvfxVwtCIsrbQez4rPlF/VS-Code-Extension-MLP?node-id=1286%3A1662)
- [CTAS from Save Search, and Create Monitor buttons](https://www.figma.com/file/EXXvfxVwtCIsrbQez4rPlF/VS-Code-Extension-MLP?node-id=246%3A11)

These UTM parameters will be used to track traffic from these CTAs to the VSCE signup page, and eventually account creation. End goal is to create a funnel conversion view with steps: 

1. Clicked on CTA in VSCE
2. Landed on Cloud VS Code sign up page
3. Clicked sign up
4. Created account
5. Synced repo

**Comment by jjinnii** [comment]
@muratsu is this something @philipp-spiess could potentially help us with since he's recently done this for the cloud marketing campaigns? 

Also FYI : @brady-garrett

**Comment by philipp-spiess** [comment]
Happy to take a look at this 😊

**Comment by philipp-spiess** [comment]
@jjinnii Draft PR up [here](https://github.com/sourcegraph/sourcegraph/pull/30890). I need some support to get the extension working properly in development mode so I can add tracking to the banner and save search/create monitor buttons.

**Comment by philipp-spiess** [comment]
I merged the changes for this into the WIP branch from @abeatrix and @tjkandala. It'll go out with the next VSCE release but from what TJ said this is likely going to be mid next week as we're improving the stability of the build pipeline first. Does that sound reasonable @jjinnii?

**Comment by jjinnii** [comment]
Hmm @tjkandala  is out early week next week, @abeatrix did you have any insight into this? I would love for these changes to be available early-mid next week, as Murat and I are working on documenting the outcomes of the v1 launch using this data. :) No pressure if it's not possible though.

**Comment by abeatrix** [comment]
> Hmm @tjkandala  is out early week next week, @abeatrix did you have any insight into this? I would love for these changes to be available early-mid next week, as Murat and I are working on documenting the outcomes of the v1 launch using this data. :) No pressure if it's not possible though. 

I can publish the build if needed!

**Comment by jjinnii** [comment]
Amazing! Thanks so much @abeatrix  and @philipp-spiess 🎉 

@abeatrix let's talk in our sync later about potentially squeezing in the VPN proxy issue if we're going to publish a build anyway.

**Comment by philipp-spiess** [comment]
@abeatrix Let me know when you do and if you do it before we merge back the work into `main` I can cherry-pick the sourcegraph.com changes to create the UTM event logs to `main` in a separate PR.

**Comment by abeatrix** [comment]
We haven't started merging this with main yet. We have been building it from TJ's branch so your PR should work?

**Comment by philipp-spiess** [comment]
> We haven't started merging this with main yet. We have been building it from TJ's branch so your PR should work?

There's a change necessary on sourcegraph.com. Here's a quick PR if you stamp that we can roll it out independent from the VSCE changes: https://github.com/sourcegraph/sourcegraph/pull/31084
