### ISSUE TITLE
Define EngEd prioritization process

### ISSUE THREAD

**Issue by marekweb** [sourcegraph/sourcegraph#30901]

**Comment by taylorsperry** [comment]
We have lots of ideas for content that we COULD create, but we need to be deliberate about working on the right things first.

Factors to consider: 
- Does it contribute to the onboarding use case? 
- How often is this kind of content requested?
- How much effort is involved in putting together this video? 

Potential resources for informing the factors above: 
- Process Street surveys
- Engineering Pulse surveys
- Inés's 3-month interview
- Onboarding buddies
- New Sourcegraph engineers (<1 month)

Given the factors and resources above, we're experimenting with a [Priority Matrix](https://docs.google.com/spreadsheets/d/1cCOE5PMn1mkvQgNM_4OE2BBxygRLsWyOWo24CDPkFVg/edit#gid=0) to help guide our planning. It's WIP.

**Comment by davejrt** [comment]
Closing as the priority matrix is done.
