### ISSUE TITLE
sg fails to start when using the fish shell

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#30909]
```
$ sg start enterprise-codeintel
✅ Check "docker" success!
✅ Check "redis" success!
✅ Check "postgres" success!
❌ Check "git" failed: unexpected output from git server: source: '/Users/chrismwendt' is not a file
git version 2.34.1
Failed to get correct git version. Run "sg setup" to make sure you have the right version.
error: failed checks: git
$ 
```

I think the logic here has an empty `shellrc` variable:

https://github.com/sourcegraph/sourcegraph/blob/48763a0f1d2bd3e0437118574a2120e97ee0479b/dev/sg/internal/usershell/usershell.go#L40-L52

It might be caused by https://github.com/sourcegraph/sourcegraph/pull/30037

**Comment by mrnugget** [comment]
Well, well, well, so we meet again, fish shell... 

Chris, fish shell is not officially supported 😬 But I'll see if it's easy to fix. cc @jhchabran

**Comment by mrnugget** [comment]
Closing this because I think this is fixed now and I can successfully run `sg start` in `fish`. @chrismwendt feel free to reopen if that's not the case.
