### ISSUE TITLE
Move code monitors to worker service

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#30931]
Code monitors currently live in `repo-updater`, which is run using the internal actor. Ideally, the code monitor jobs should be moved to the worker service which is more flexible.

**Comment by lguychard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Search-Product-61302e38f801dc0012e2e050/issues/sourcegraph/sourcegraph/30931?planning-poker) with ZenHub @benvenker @camdencheek @fkling @limitedmage @marisak @novoselrok @rvantonder
