### ISSUE TITLE
JetBrains plugin: Make Java/Kotlin decision

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#30977]
Random notes:
 - Kotlin seems to be a lot closer to JS than Java
 - Our [existing plugin](https://github.com/sourcegraph/sourcegraph-jetbrains) is written in Java, as well as [Coury's branch](https://github.com/sourcegraph/sourcegraph-jetbrains/tree/hackathon)
 - No research on the JS aspect as well
 - We (the G&I team) woudl prefer this to be a collaborative act rather than a one-man show, and none of us is very experienced in Java or Kotlin. Doing it in TypeScript somehow would be best from this angle.

**Comment by vdavid** [comment]
So far, I have this input on this decision point:
- I asked @coury-clark ([here](https://docs.google.com/document/d/1W1kJnCyJi7kHoWr2NygJmEnpdUNZw_QdfSzBc7W2CyM/edit#bookmark=id.knba0ts44yac)). He suggested **Java** because
  1. our existing codebase is Java,
  2. more devs know Java than Kotlin,
  3. he says modern Java feels good to work with.
- I asked the JetBrains community for opinions ([here](https://intellij-support.jetbrains.com/hc/en-us/community/posts/4467583956754)) 1.5 days ago, but I've got **no responses** yet.
- Today, I also asked @olafurpg for his opinion.
- **Personally**, I worked four years with **Java** (but 16 years ago), and I have zero experience with Kotlin. However, Kotlin seems more similar to TypeScript for me, so it probably has a steeper learning curve for our developers.
- A good **Java → Kotlin converter** ([J2K](https://kotlinlang.org/docs/mixing-java-kotlin-intellij.html#converting-an-existing-java-file-to-kotlin-with-j2k) by JetBrains) exists, so converting our existing codebase would probably mean a supervised conversion rather than a rewrite. But maintenance might still be tricky.
- I haven't found any info on a web-based (**TypeScript**) solution, and knowing the IDE, it personally doesn't sound viable for me either, so I'd **drop** this direction for now.
- For JetBrains plugin development, Kotlin seems more like an alternative to **Java** than the recommended path. They don't strictly say this, but I got this feeling from [their doc on the topic](https://plugins.jetbrains.com/docs/intellij/kotlin.html).

If I had to make a decision now, I'd go with **Java** because
1. the reasons Coury mentioned
2. I have more experience with Java
3. the team has more experience with Java, plus it's easier to find Java people for the team later
4. it seems more standard for JetBrains plugin writing
5. the current codebase is Java
6. Java→Kotlin conversion is easier, so staying with Java is a decision that's easier to change

I'll wait for Olaf's thoughts, though.

**Comment by slimsag** [comment]
+1 for Java from me, sounds most reasonable

**Comment by olafurpg** [comment]
I don't think you can go wrong with Java or Kotlin, both are safe choices. I agree with all of the points above in favor of Java so +1 to Java from me.

Kotlin may have a minor advantage when it comes to ergonomics of writing tests. For example, I think the following test code reads more nicely in Kotlin compared to Java

- https://github.com/JetBrains/intellij-ui-test-robot/blob/master/ui-test-example/src/test/kotlin/org/intellij/examples/simple/plugin/CreateCommandLineKotlinTest.kt
- https://github.com/JetBrains/intellij-ui-test-robot/blob/master/ui-test-example/src/test/java/org/intellij/examples/simple/plugin/CreateCommandLineJavaTest.java

> I haven't found any info on a web-based (TypeScript) solution, and knowing the IDE, it personally doesn't sound viable for me either, so I'd drop this direction for now.

You can access all APIs from the IntelliJ Platform SDK via JavaScript by using this hackathon project https://plugins.jetbrains.com/plugin/17669-flora-beta-/ I wouldn't use it for a real-world project today, but it's cool that this exists and it might become a popular way to write JetBrains plugins in the future.

**Comment by vdavid** [comment]
Thanks, Flora looks interesting, but I agree, definitely not stable enough for production.
I'll go with **Java**.
