### ISSUE TITLE
Code Intel panel has bad links layout

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#30993]
At the moment code intel reference panel has links with no margins which makes it a little bit clumsy. 
Repro link for the following screenshot https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/shared/src/search/stream.ts?L463:17#tab=references

<img width="1296" alt="Screenshot 2022-02-10 at 22 21 03" src="https://user-images.githubusercontent.com/18492575/153482538-083ffd9a-3fd7-4cac-9f4e-66641494e2e3.png">

**Comment by mrnugget** [comment]
`git bisect` tells me this is the cause for the regression: https://github.com/sourcegraph/sourcegraph/pull/30954
