### ISSUE TITLE
Search doesn't work for Sourcegraph versions 3.31.2 and prior

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#31017]
#### Expected behavior:

TBD. @muratsu We need to make a decision on up till what versions of Sourcegraph should we support the full functionalities of VSCE? What customers are on versions 3.31.2 or prior that we should be aware of?

#### Actual behavior:

Search does not work. Video of behavior [here](https://docs.google.com/document/d/1ocy4KcY8_U2S0Jl616g96qYZi1-7CMfJ92p56WY_an8/edit#heading=h.2zhvzgqridfy).

**Comment by jjinnii** [comment]
A [document](https://docs.google.com/document/d/1ocy4KcY8_U2S0Jl616g96qYZi1-7CMfJ92p56WY_an8/edit#) that defines what versions support what.

**Comment by jjinnii** [comment]
@ryankscott Wanted to put this on your radar! @muratsu mentioned that this is something that should be thought about on a systematic, integrations level; rather than a decision specific to VSCE. 

I'm going to put this specific issue in the backlog, and you can see in the prior comment with a document that @abeatrix and @tjkandala are updating as we discover new limitations specific to VSCE. 

I think we have a few other high-level discussions that needs to be had with integrations before we tacke this, but just as an FYI.

**Comment by ryankscott** [comment]
Thanks @jjinnii. For clarity, this is the VS Code extension not working with certain versions of Sourcegraph, correct?

I'm guessing the nuance here is that it's not a VS Code extension problem specifically, rather it's what is available in certain versions of Sourcegraph?

**Comment by jjinnii** [comment]
@ryankscott 

>  For clarity, this is the VS Code extension not working with certain versions of Sourcegraph, correct
Yes! Certain features of the VS code extension not being supported the older versions of Sourcegraph we get.

> I'm guessing the nuance here is that it's not a VS Code extension problem specifically, rather it's what is available in certain versions of Sourcegraph?
Yes, if we make a decision for example to say, after Sourcegraph 3.31.2 we won't try to support for VS Code extension, that's a decision that should apply for all integrations. @muratsu to provide better insight into this though. :)

**Comment by ryankscott** [comment]
Cool, I'd love to hear more about if we have any way of doing feature detection to find out if version X supports feature Y.

**Comment by abeatrix** [comment]
A list of private instance version numbers: https://sourcegraph.looker.com/looks/436

**Comment by philipp-spiess** [comment]
3.31.2 is now over a year old and with the new multi version upgrade tool, it's easier than ever to upgrade. Because of this we'd rather focus on improving support with the current versions.
