### ISSUE TITLE
Improve empty collaborators error message

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#31011]
Based on a user feedback, it may be difficult for users to understand that collaborators come from their repositories and that they can see collaborators here if they add repositories they've worked with other people on.

Adjust the text and add links to the prior step to help them do so:
<img width="573" alt="image" src="https://user-images.githubusercontent.com/539268/153502635-3053767c-fc81-449d-9139-91b192534682.png">

Additionally the invite all button still appears when the list is empty. 

Figma:
https://www.figma.com/file/9KUQex1haXP6BpC2wDgtXC/Inviting-collaborators?node-id=783%3A6849

**Comment by philipp-spiess** [comment]
There are actually two slightly different null states we have to handle here:

1. The case you outlined here where we don't find any collaborators in any of the repos.
2. The case when using the search box to filter down the collaborators and we have none matching (even though there are collaborators).

I'll keep the existing null text for the second case + I will also make changes to how the input box works when no results are found (I’m likely just disabling it but I can also remove it).
