### ISSUE TITLE
Write PD (product document) for the JetBrains IDE plugin

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#31027]
TBA

**Comment by vdavid** [comment]
Update: we have the draft [here](https://docs.google.com/document/d/1l18Gq1VFkjwE3iimeOLrl8evqwVwnuDb4fDfuTnh5LM/edit#). We've made good progress. On Monday, we're discussing the technical details, which is pretty much the last missing section, and it's waiting for me to write.

**Comment by vdavid** [comment]
Update: I've added my part.
I'm not sure what the next step is with the product document @jjinnii.
This is the first time I'm using this format, so I'm not sure how far the scope of the PD goes and when we switch to an RFC or other place to continue the planning.
If you write a few words on the scope of the document, that should help me.

**Comment by vdavid** [comment]
Update: I think the PD is almost final. I don't have any additions in mind anymore, but there are about five decision points and unknowns listed that will need attention. I'm unsure if the results of these decisions and discoveries should go in the PD or not, what do you think, @jjinnii?

**Comment by vdavid** [comment]
Great, closing it :)
