### ISSUE TITLE
Explore whether user color theming work can be applied to Sourcegraph Cloud 

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#31024]
I'd like us to look into whether the work that we've done in issue #29704 could be applied to Sourcegraph Cloud. This could manifest in users with custom color palettes on their local machines or expand broader into general user customization on Sourcegraph Cloud.

**Comment by philipp-spiess** [comment]
@jjinnii @ryankscott David and I are currently cleaning up older issues and we came across this one. We do think this is a great idea that we should preserve but it's not scoped out well enough to be immediately actionable and this effort will likely also be something that not only our team will need to work on. Do we have another place where we can preserve this idea? Maybe an idea list?

**Comment by ryankscott** [comment]
Personally I would close this. I think it's likely it will come up again if it isn't already being tracked by another team.
