### ISSUE TITLE
Improve VSCE support and feedback CTAs 

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#31021]
#### Feature request description

Currently, we only have one CTA for Feedback that links to our [Sourcegraph Github discussions board](https://github.com/sourcegraph/sourcegraph/discussions/categories/feedback). We also link to our Sourcegraph user docs, but our user docs currently don't offer a lot of information on the VSCE. (a to do item[ issue #29769](https://github.com/sourcegraph/sourcegraph/issues/29769))

As the VSCE is still early v1, we should do a better job of communicating how users might troubleshoot, ask us questions, and provide feedback. 

#### Is your feature request related to a problem? If so, please describe.

We've already documented a number of bugs/gaps from our CE teams from customers with various issues related to private instance account authentication. We've since then added to our [troubleshooting docs](https://github.com/sourcegraph/sourcegraph/pull/30918#event-6037919504), that we should surface on the VSCE UI.  

#### Additional context

Below is an example of a Help and Feedback section taken from another VS Code extension. Instead of finding multiple locations to put CTAs for help, docs, and feedback, this is a great example of how we can utilize VS Code's sidebar functionality.

![image (6)](https://user-images.githubusercontent.com/87138876/153516271-62b992b4-dfe4-4bee-8b2a-dc272137d655.png)

**Comment by jjinnii** [comment]
VS Code native icons: https://code.visualstudio.com/api/references/icons-in-labels

**Comment by jjinnii** [comment]
@abeatrix @tjkandala [Designs ready in Figma](https://www.figma.com/file/DmiZkq0n6j7A42uKCjNAs2/VSCE-authentication-%26-feedback-flow-improvements?node-id=2223%3A993). 

Icons need to replaced by VS Code native icons (aside from the Sourcegraph wildcard icon). All links in the section link out to a pre-existing page, except for ["Authenticate account"](https://www.figma.com/file/DmiZkq0n6j7A42uKCjNAs2/VSCE-authentication-%26-feedback-flow-improvements?node-id=2224%3A1613). Clicking on Authenticate account expands the authenticate account section that currently lives at the bottom of the sidebar. 

Please let me know if the additional work to include the "authenticate account" into this help and feedback section expands scope of this issue too much to achieve by this iteration. I can break out the authenticate account action into a new issue, and this issue can just cover the work to implement all buttons other than account authentication if that is the case.

**Comment by jjinnii** [comment]
@abeatrix designs updated and ready for implementation! Again, this issue is larger in scope than just adding a feedback section with the expand/collapse authentication flow, so feel free to adjust other issues around as needed to work on this. 😄

**Comment by abeatrix** [comment]
@jjinnii I added a question to the figm design

**Comment by jjinnii** [comment]
@abeatrix Is there a branch that I can run so I can see this in VSCE myself? Want to try out the feel of the authenticate expand/collapse to give better feedback 😄

**Comment by abeatrix** [comment]
@jjinnii yup! Here is the PR related to this issue: https://github.com/sourcegraph/sourcegraph/pull/32586
The branch is called [bee/vsce-feedback](https://github.com/sourcegraph/sourcegraph/tree/bee/vsce-feedback)

**Comment by jjinnii** [comment]
@abeatrix Looks great overall 😄 , just a few followups:

- Feedback buttons on the [homepage ](https://www.figma.com/file/DmiZkq0n6j7A42uKCjNAs2/VSCE-authentication-%26-feedback-flow-improvements?node-id=2223%3A1175)and [search results page](https://www.figma.com/file/DmiZkq0n6j7A42uKCjNAs2/VSCE-authentication-%26-feedback-flow-improvements?node-id=2283%3A1532) from the prior design should be removed, now that we have a dedicated location for feedback
- For authenticated users, based on the last screenshot in your last comment, I thought we were removing "Create an account" and "Authenticate account" if a user has authenticated, but I'm seeing this. Was this maybe just a change not reflected in that build? 
<img width="277" alt="Screen Shot 2022-03-15 at 5 27 43 PM" src="https://user-images.githubusercontent.com/87138876/158482824-7af30275-143e-4226-b0f7-72d45e6e9700.png">



- Is it possible for us to adjust the default height of the "help and feedback" section to match the designs? This is the default height for me currently, which has a lot of empty space and covers what would be the "get started" section for unauthenticated users:

**Default**
<img width="316" alt="Screen Shot 2022-03-15 at 5 21 06 PM" src="https://user-images.githubusercontent.com/87138876/158482447-1c075603-06d6-4ad1-b798-0ccf925bcbd6.png">

**Proposed**
<img width="280" alt="Screen Shot 2022-03-15 at 5 25 56 PM" src="https://user-images.githubusercontent.com/87138876/158482584-4970e40a-fd81-41af-8c51-4b53a123c136.png">

And I don't believe we can shorten the height of the Files section by default any more either.

**Comment by abeatrix** [comment]
Hi @jjinnii I forgot to mention that the build was temporary and does not include all the changes that I made as we are in the process of merging the branches, it was just to let you see how the expand/collapse work on the auth section, sorry about that! 

We don't have control over the height of each section, unfortunately, but I will see if there is other workaround we can use. 

Also here is a list of the vs code icons for your reference: https://microsoft.github.io/vscode-codicons/dist/codicon.html
FYI, in the image you shared:
Give feedback is using `github`,
Report Issue is using `bug`,
Troubleshooting is using `notebook`,
Create an account is using `smiley` (will replace it with sourcegraph logo later),
Authenticate account is using `account`

Let me know if you would like me to replace the icons with something else, thanks!

**Comment by jjinnii** [comment]
@abeatrix No worries at all! Icons looked good to me. Love the smiley, but Sourcegraph probably works better 😄 And thanks so much, let me know if there might be some workaround to reduce height of the section! My primary concern is that it covers the "get started" content on the homepage, so users will by default collapse or hide this section (maybe before even digesting what this section is for), which drastically reduces the value of having a dedicated section for feedback.

**Comment by abeatrix** [comment]
@jjinnii Looks like there is no way to customize the height for the sidebar sections according to [this feature request](https://github.com/microsoft/vscode/issues/122283)
Currently it looks like:
![Screen Shot 2022-03-17 at 2 32 11 PM](https://user-images.githubusercontent.com/68532117/158898915-d53d3873-5241-4096-aceb-15b50473faf2.png)

We can either hide the section by default (users will need to expand the section manually) or add it as part of the search sidebar.

Please let me know what you think :)

**Comment by jjinnii** [comment]
Agreed! Love the innovative idea of adding it as an embedded section in the search sidebar, but agreed that we should keep it as a separate section. Also agreed that it's self-explanatory. Maybe in the future when we improve on onboarding, we can point out this section there, instead of shoving it in the user's face by having it expanded by default 😄

**Comment by jjinnii** [comment]
@abeatrix This just came to mind, but could we add Amplitude events to track clicks on the actions within this help & feedback section? Happy to create a separate issue for this since this issue is closed 😄

**Comment by abeatrix** [comment]
I've already added them :) 
https://docs.google.com/document/d/17RdHBJ3XVm4dznP5ZGqhzxhJbjhYZsXTPZOdvMCQDDA/edit

**Comment by jjinnii** [comment]
🤯 Your forward-thinking never fails to amaze me!
