### ISSUE TITLE
All search keywords link should be pointed to sourcegraph docs site

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#31023]
#### Expected behavior:
Search keyboards link should be pointed to sourcegraph.com docs site because the docs site lives on [Sourcegraph docs](https://docs.sourcegraph.com/code_search/reference/queries).

#### Actual behavior:

All search keywords link not working for non-sourcegraph instance

**Comment by abeatrix** [comment]
Fixed and released with 2.0.8 https://github.com/sourcegraph/sourcegraph/pull/31111
