### ISSUE TITLE
Documentation of what changes to sourcegraph.com will carry over to VSCE releases 

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#31029]
Create documentation of what changes made on sourcegraph.com ( For example #875 ability to select code from search results was recently completed) will carry over to VSCE once releases are made, as well as what changes wouldn't. (For example, changes to the VSCE home page was modified from sourcegraph.com's homepage)

**Comment by abeatrix** [comment]
Link to google docs for tracking purpose: https://docs.google.com/document/d/1-0JKFuvUQGMUK0kHvmX0Q6pxTBudFZH0BEG7jl4KYVs/edit?usp=sharing

**Comment by tjkandala** [comment]
@abeatrix Great work, I'm assuming it's safe to close this issue? Anything _not_ in the doc should carry over in each release
