### ISSUE TITLE
Missing timeout on git archive

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#31036]
https://github.com/sourcegraph/sourcegraph/pull/30884 inadvertently removed the default timeout on the git archive call here:

https://github.com/sourcegraph/sourcegraph/blob/aa368f7a054d44973f1cae7cd17056f82391daad/cmd/gitserver/server/server.go#L883-L897

This kind of mistake is perhaps what @keegancsmith had in mind when he [suggested `NoTimeout`](https://github.com/sourcegraph/sourcegraph/pull/30790#discussion_r801265565) as the default.

**Comment by keegancsmith** [comment]
Hah I just commented on that PR, yes this is indeed why I think NoTimeout is the better field.
