### ISSUE TITLE
Configure Multiple Sourcegraph instances

### ISSUE THREAD

**Issue by sbueringer** [sourcegraph/sourcegraph#3104]
#### Feature request description

It would be nice if the Sourcegraph Chrome/Firefox extensions would support to configure multiple Sourcegraph instances depending on the Github instance/ URL.

Our use case is to host one internal Sourcegraph for our internal Github enterprise. For github.com we would like to use sourcegraph.com. I couldn't find documentation if this is possible. 

If this is currently not supported, would PRs to add this feature be accepted?

**Comment by sbueringer** [comment]
Sorry, issue can be closed. I wasn't aware of the `disablePublicRepoRedirects` property in the Sourcegraph site  configuration

**Comment by sqs** [comment]
Glad to hear this is working for you. You can find more info at https://docs.sourcegraph.com/admin/federation/public_repositories. We do want to support multiple instances intelligently in the browser extension, but it is complex to make it work 100% and not leak repository names, etc. That is why it's not supported natively in the browser extension.
