### ISSUE TITLE
do not opsgenie for non-critical alerts

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#31051]
We have performance alerts that sometimes fail. Mostly around sentinal queries. These often resolve themselves and are related to other systems breaking. These should not alert us, since they can be the main cause of alert fatigue. We have other higher signal alerts that we can instead rely on for paging.

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket, please let us how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
