### ISSUE TITLE
repo-updater should backoff if gitserver is unavailable

### ISSUE THREAD

**Issue by indradhanush** [sourcegraph/sourcegraph#31060]
When gitserver is deployed we get these errors in the logs:

```
lvl=eror msg="runUpdateLoop: error requesting repo update" uri=github.com/meteorlxy/meteorlxy.github.io err="Post \"http://gitserver-6.gitserver:3178/repo-update\": dial tcp: lookup gitserver-6.gitserver on 10.165.0.10:53: no such host"
lvl=eror msg="retrying HTTP request failed" attempt=3 method=POST url=http://gitserver-6.gitserver:3178/repo-update status=0 err="dial tcp: lookup gitserver-6.gitserver on 10.165.0.10:53: no such host"
```

This causes the number of errors to spike up during the deployment which usually lasts close to 30 minutes. This has forced us to [increase the timeout threshold](https://github.com/sourcegraph/sourcegraph/pull/30682) before an alert triggers to 25 minutes. Unfortunately this also means that in real scenarios of errors in production with repo-updater, we won't be alerted for the first 25 minutes which is a rather high limit of tolerance. 

To get around this, repo-updater can back-off if gitserver is unavailable to a maximum backoff of 5 mins which is more than enough for an instance to be updated with the new image and be up and running. This should also reduce errors and help us to ultimately pull back the threshold for the repo-updater alert.

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.
