### ISSUE TITLE
Refactor browser extension FileInfo to disallow invalid states at the type level

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#3107]
The [`FileInfo`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@fd9eef0b5893dfb3358d2a3358d15f3e9b14ca9e/-/blob/browser/src/libs/code_intelligence/code_intelligence.tsx#L262-299) interface in the browser extension is a core part of the code intel logic. It has lots of properties that depend on each other. For example, all the `base`-prefixed properties should either all exist or none of them should. The [`headHasContent`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@fd9eef0b5893dfb3358d2a3358d15f3e9b14ca9e/-/blob/browser/src/libs/code_intelligence/code_views.ts#L99-100) boolean is redundant to the `content` property (except that we seem to set `content` to an empty string even if an error happened: #3085). These invalid possible states were the source of bugs in the Bitbucket integration.

It should disallow invalid states, something like this:
```ts
type DiffFileInfo = { head: FileInfo } | { base: FileInfo } | { head: FileInfo, base: FileInfo }
interface FileInfo {
  content
  commitID
  repoName
  filePath 
}
```

**Comment by lguychard** [comment]
This would be a risky change.

It hasn't been a big source of instability lately, but would likely be a prerequisite for https://github.com/sourcegraph/sourcegraph/issues/4062

**Comment by marekweb** [comment]
I'm considering two possible angles for this refactor:

A) Refactor the operations that use `FileInfo` to use the new definition of `FileInfo`, so that that functions like `ensureRevisionsAreCloned` and `resolveRepoNames` will deal with just a single base or a head, and the calling code will handle calling them for the head and for the base.

B) Refactor operations that use `FileInfo` to use the new `DiffFileInfo` instead, so that the functions will continue to handle the logic for operating on the head and base as they do now (but no longer relying on the `base*` prefixes to do it)

Related to that, when we have a `FileInfo` with extra properties such as `FileInfoWithRepoNames`, `FileInfoWithContent`, I'm investigating whether that means we need a e.g. `DiffFileInfoWithContent` to contain it, or allow `DiffFileInfo` to contain `FileInfo`s which may or may not have those extra properties

**Comment by lguychard** [comment]
B) seems like it would be the most incremental approach, so I'd go with that.

> Related to that, when we have a FileInfo with extra properties such as FileInfoWithRepoNames, FileInfoWithContent, I'm investigating whether that means we need a e.g. DiffFileInfoWithContent to contain it, or allow DiffFileInfo to contain FileInfos which may or may not have those extra properties

I'd rather avoid optional properties here, as they could allow creating other invalid states, for example a diff file info where the base has file contents but the head doesn't. We could use generics to express this:

```typescript
type DiffFileInfo<T extends FileInfo = FileInfo> = { base: T } | { head: T } | { base: T head: T }
type DiffFileInfoWithContents = DiffFileInfo<FileInfo & { contents: string }>
```

As an example, this is how we'd express what  `resolveRepoNames()` does at the type level with this approach:

```typescript
const resolveRepoNames = <T extends FileInfo>(info: DiffFileInfo<T>): Observable<DiffFileInfo<T & { repoName: string }>>
```

**Comment by marekweb** [comment]
I drafted a refactor of `FileInfo` into a diff-focused structure (tentatively named `FileDiff` and containing `head` and `base`).

I'm looking for input for how to also represent non-diff files. The code host's `resolveFileInfo` needs to be able to return a diff or a non-diff file.

Option A) Re-use the same type as for diffs by putting the non-diff file into the `base` field. We could differentiate from diffs with a different `type` value. This is closer to how the way `FileInfo` currently works before this refactoring, i.e. re-using the same structure for diffs and non-diffs.

Option A) Use a union type to use a different structure for diffs and for non diffs. That would basically look like `FileInfo | {head: FileInfo, base: FileInfo}` (that's a simplified pseudo representation). This might mean having to branch into handling these cases with separate logic in some places, e.g. having a separate set of operations on the diffs and the non-diffs.

Not sure if one approach or the other would better match the actual `resolveFileInfo` implementations on each code host.

**Comment by lguychard** [comment]
> The code host's resolveFileInfo needs to be able to return a diff or a non-diff file.

This is a correct assumption. For example, for BitBucket Server, we have:
- [`resolveFileInfoForSingleFileSourceView()`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@f4b43d0fa5d65cd2f203791868f087af6f59fa96/-/blob/browser/src/libs/bitbucket/file_info.ts#L14-20)
- [`resolvePullRequestFileInfo()`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@f4b43d0fa5d65cd2f203791868f087af6f59fa96/-/blob/browser/src/libs/bitbucket/file_info.ts#L22-31)

Regarding A) versus B), I think they're similar in terms of implementation complexity. When it comes to data representation, option B feels "cleaner" to me.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
