### ISSUE TITLE
Tracking issue: expose "code-intel inside™" in GraphQL API 

### ISSUE THREAD

**Issue by Strum355** [sourcegraph/sourcegraph#31071]
### Goal

Expose information in GraphQL API whether and what kind of code intel is available for a given list of repositories, a repository, a directory, or a file.

### GraphQL API

```graphql

type CodeIntelSupport {
    searchBasedSupported: boolean
    preciseSupported: "unknown" | "supported" | "3rdparty" // supported: we own indexers, 3rd party indexers
}

extend GitBlob {
  codeIntelInfo {
    support: codeIntelSupport
    lsifUploads: LSIFUploadConnection
  }
}

extend GitTree {
  codeIntelInfo {
    lsifUploads: LSIFUploadConnection
    support: []{
        language: string
        numFiles: int
        coveredPaths: []string
        support: codeIntelSupport
      }
   }
  }
}
```

### Tracked issues

- [x] #31073
	- [x] #31442
- [x] #31074
	- [x] #32167
- [x] #31635

### Design

Figma: https://www.figma.com/file/p5rVseXjNvXRkvXCdttbWt/Semantic-badge?node-id=541%3A227

**Comment by efritz** [comment]
[mayo inside](https://c.tenor.com/vddzwSayj5UAAAAd/mayo-thermal.gif)

**Comment by Strum355** [comment]
Im proposing that we change `CodeIntelSupport.searchBasedSupport` to be a (nullable?) string, allowing us to expose the language association that ctags will use (e.g. Apex files are associated with the ctags java indexer)

**Comment by efritz** [comment]
@Strum355 100% expose the uploads that can respond to a commit/path from the `*LSIFData` type. As long as we can get the data without having to query other things on a fresh page (we'll likely want to show stencil data though) things seem good.

**Comment by jjinnii** [comment]
Just want to hop in to make sure we're in sync about the design artifacts that are needed! 

I have[ issue #31180](https://github.com/sourcegraph/sourcegraph/issues/31180) to capture the design work, and it outlines what's ready for implementation, what I'm working on, and things I will not be covering. Please take a look to ensure that this is in line with your expectations. 😄 

I'm assuming that this tracking issue is intended only for the backend component of this feature, issue #31180 can transition to span the frontend implementation of the design work after this issue is closed. But please let me know if this is not what you prefer! 

cc: @macraig

**Comment by efritz** [comment]
> I'm assuming that this tracking issue is intended only for the backend component of this feature

@jjinnii This is exactly it. We were going to sync with you tomorrow during planning about discussing how to expose this. This ticket (or at least the active part of it) only covers up to the GraphQL layer at this point.

**Comment by Strum355** [comment]
Updated on the schema: with `lsifUploads` being moved out directly into `GitBlobLSIFData` and `GitTreeLSIFData`, I've collapsed `codeIntelInfo` as per the screenshot: 
![image](https://user-images.githubusercontent.com/18282288/155388985-12c5afc4-85c1-4716-9b9c-6f2362e2712d.png)

**Comment by Strum355** [comment]
Proposal schema for `Repository`, all names subject to change.
My aim for this schema is to provide a high-level and quickly actionable overview based on these (subjective) user opinions:

If Im viewing a repository (either in the search page or repo page), I:
1. Dont care _which_ individual files have _what level_ of search-based support
2. Do care what quality of search-based codeintel to expect in this repo
3. Do want to know what precise code-intel indexers could be applicable to this repo (and potentially at what roots)

```graphql
extend type Repository {
	codeIntelInfo: RepoCodeIntelSupportOverview
}

type RepoCodeIntelSupportOverview {
    # how many files (as a percentage?) are covered by search-based support. We could break this down further by support _level_ if we wanted?
	searchBasedCoverage: Float! # or Int ?
	
	# list of directories for which we've inferred there could be precise code intel support for
	possiblePreciseCodeIntelTargets: [InferredPreciseCodeIntelSupport!]
}

type InferredPreciseCodeIntelSupport {
	# directory for which code intel support was inferred
	root: String!
	# potentially supported configurations e.g. if package.json and go.mod are found at a directory, we can indicate support for 
	# both lsif-tsc/lsif-typescript/lsif-eslint and lsif-go in two different groups
	support: [PreciseCodeIntelSupport!]!
}
```

**Comment by jjinnii** [comment]
@Strum355 This makes sense to me and allows us to achieve the scope of work outlined in issue #31180 - make precise intel discoverable. There is now a new issue #32293 for improving code intel reliability (Tracking issue #32294) that may require more information than what you've outlined in your schema, but until I start exploring this issue it's hard to say. I think it's safe to move forward with your suggestion, and create a new issue/iterate on this as we uncover the needs for the new feature of making code intel reliable. cc: @macraig @efritz does that sound sensible?

**Comment by Strum355** [comment]
After todays pre-planning with :eric: and :horsten:, we're unifying the data for `Repository` and `GitTree`, so heres my new proposed `GitTree` model based on the following user perspectives:

1. Could this directory have precise code-intel (discoverability)
	a. What indexers/links should I visit to learn more?
	b. Caveats/pre-requisites/confidence in suggestion?
2. Does this directory have precise code-intel (reliability)
	a. What files are covered by precise code-intel
3. What files are covered by search-based code-intel? (reliability)

```graphql
extend type GitTree {
	codeIntelInfo {
		searchBasedSupport: []{
	        coveredPaths: [String!]!
    	    support: SearchBasedCodeIntelSupport!
		}
		preciseSupported: []{
			# this is separate from the search-based groupings e.g. `.kts` and `.kt` would be supported by the same `Kotlin` search-based support
			# but only `.kt` would be supported by lsif-java.
			# The files here don't have to be unique e.g. if a tool only supports languages (x,y) and another supports languages (x,z)
			coveredPaths: [String!]!
			confidence: InferredPreciseSupportLevel!
			support: PreciseCodeIntelSupport!
		}
	}
}

# we dont need to handle unsupported case here, those cases would just be omitted from `preciseSupported` list
enum InferredPreciseSupportLevel {
	# when a supported language is found but the project structure may not be, based on the current tree
	LANGUAGE_SUPPORTED 
	# when a supported language is found and the project structure is known to be supported
	PROJECT_STRUCTURE_SUPPORTED 
}
```

**Comment by mrnugget** [comment]
> What files are covered by search-based code-intel? (reliability)

Just to make sure I'm not missing anything: by using `codeIntelInfo` on `GitBlob` we can find out which files are covered by precise code intel, right?

**Comment by efritz** [comment]
`GitBlob` is a single file, `codeIntelInfo` on `GitTree` should tell you what direct (?) paths are covered by _some_ level of index.

Would we also want to expose the exact upload records here?
