### ISSUE TITLE
Add ability to dismiss create account banner 

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#31089]
#### Feature request description

Add "close" icon to[ sign up banner ](https://www.figma.com/file/EXXvfxVwtCIsrbQez4rPlF/VS-Code-Extension-MLP?node-id=1286%3A1662)in VSCE.

#### Is your feature request related to a problem? If so, please describe.

The banner promoting account creation is visually dominant and pushes down the main search results content. While we want to promote account creation, we should give users the ability to dismiss the banner once it's been shown to them. 

#### Additional context

There is a related issue to add the ability to same banner in sourcegraph.com, however, the banner has been customized for VSCE and we will need to implement a feature inside VS Code.

**Comment by abeatrix** [comment]
PR: https://github.com/sourcegraph/sourcegraph/pull/33325

**Comment by abeatrix** [comment]
![image](https://user-images.githubusercontent.com/68532117/162492963-97ca795b-df40-4a4b-be32-bdfc3bcc948a.png)
