### ISSUE TITLE
SSBC: See "overview" from execution page when no workspace is selected

### ISSUE THREAD

**Issue by courier-new** [sourcegraph/sourcegraph#31088]
Currently the execution page doesn't offer much to look at until you drill into a specific workspace and just says "Select a workspace to view details." We could do more with this space to give a better overview of the execution progress.

For example, particularly at the beginning of execution when we might be waiting in the queue for a while, it might help to surface the earliest position in the queue:

![Screen Shot 2022-02-11 at 10 12 16 AM](https://user-images.githubusercontent.com/8942601/153647840-3a35a898-904a-4f1a-93a6-faa4b9cb4112.png)

Or, once we start to have changesets available to look at, show "recent changesets" here:

![Screen Shot 2022-02-11 at 10 14 12 AM](https://user-images.githubusercontent.com/8942601/153648232-ea006d9e-78af-41cc-ad15-53e13796d373.png)

(We've talked about these before and may have even started designs for them but I can't find them at the moment)

**Comment by rrhyne** [comment]
Designs are available at: https://www.figma.com/file/cTKjwbvWqU6xAykZmCTTqy/?node-id=2013%3A60194
