### ISSUE TITLE
Files will always open in https even though the sourcegraph.url is set as http

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#31095]
#### Behavior:

Currently, files always open as https, even if a user sets the instance URL to HTTP. 

<img width="727" alt="Screen Shot 2022-02-11 at 2 57 21 PM" src="https://user-images.githubusercontent.com/87138876/153661632-3866493a-692f-4c57-ac69-b495f0666a1b.png">

We have a non-zero number of private instance users whose instant URLs are set to HTTP. We need to support HTTP in sourcegraph URL.

**Comment by abeatrix** [comment]
Fixed and released with v2.0.8 https://github.com/sourcegraph/sourcegraph/pull/31111
