### ISSUE TITLE
SSBC-EM4: Post-beta

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#31090]
Note: this is a WIP, that will depend on input from the beta phase.

Outcome: We feel comfortable giving the feature to every user. It will still have some features that are missing, but quirks here and general stability are good for use by anyone at this point. 

Wishes (not saying tasks until these become more concrete):

- [ ] #37834
- [x] #27564
- [x] Resolvers and UIs are fast for at least 10000 changesets
- [x] We have great, simple instructions on how to get an executor running
  - [x] The setup burden is low
- [x] The product behaves predictably and is fast
  - [x] Ensure that SSBC and Batch Changes work well at scopes we haven't seen before. This unlocks 10k+ changeset campaigns
  - [x] #28031
  - [x] #26716
  - [x] #26145
  - [x] #26146
- [ ] Bulk exclude workspaces
- [ ] #25085
- [ ] References panel on batch spec editor page
- [ ] Visual distinction for monaco editor in read-only mode
- [ ] Implement AutoApplyOnComplete
  - [ ] Make sure errors are surfaced somewhere
  - [ ] How do we deal with publish-from-UI? 
- [ ] More user-facing docs for the SSBC feature
- [ ] avoid duplicate marshal/unmarshal in MarkComplete https://github.com/sourcegraph/sourcegraph/pull/27212/files#r745096222
- [ ] Per-user fairness for cache entries
- [ ] Allow to start execution before workspace resolution has finished
- [ ] Better sorting of workspaces list (by place in queue, by status, most important ones at top, ...)
- [ ] Track which src-cli version was used to create which changeset spec
- [ ] Editor experience:
  - [ ] Investigate language-in-language support of monaco (Like we have in TS where we get highlighting for gql in `gql` tag strings) so we can support the same hover tooltips and syntax highlighting as we have for the search bar
    - [ ] Also for fields like command.run to support bash highlighting
  - [ ] References support for output variables:
    - [ ] For highlights
    - [ ] For renames
- [ ] "Force execution" of ignored batch specs by editing spec
- [ ] Better iteration and debugging on batch specs:
  - [ ] Overwrite single steps in repos
  - [ ] Step wise retries
  - [ ] Make src-cli use new workspaces API
    - [ ] Cleanup src-cli and remove unneeded code
  - [ ] Kubernetes support after we've managed to pull functionality out of src-cli and into the backend/executor
- [ ] src-CLI is integrated well into SSBC workflows
  - [ ] no distinction between the two modes anymore, both get the new execution UI
- [ ] Visibility of batch changes (private vs. public)
- [ ] User-land executors
- [x] https://github.com/sourcegraph/sourcegraph/issues/22342
- [ ] https://github.com/sourcegraph/sourcegraph/issues/26147
- [ ] https://github.com/sourcegraph/sourcegraph/issues/26361
- [ ] Allow to keep polling for repo to be cloned when part of a search: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/gitserver/server/server.go?L1276:17-1276:38&subtree=true
  - And then poll until it's cloned
- [ ] Cleanup: Expose `executionURL` field on `BatchSpec` on GraphQL schema, so that consumers don't have to build it every time.
- [ ] Cleanup: Give executions "vanity" numerical IDs scoped to the batch change they belong to in order to have prettier execution URLs like `/batch-change-name/executions/2`.
- [ ] Cleanup: Expose `latestSpec` field on `BatchChange` on GraphQL schema to resolve the latest batch spec associated with it, so that consumers don't have to query the connection if they only care about latest.
- [ ] Enable filtering batch specs connection by execution state(s)
- [ ] Update `SupersedingBatchSpecAlert` copy for batch specs created with SSBC
- [ ] https://github.com/sourcegraph/sourcegraph/issues/34248
  - [ ] **Design**: https://github.com/sourcegraph/sourcegraph/issues/34247
- [ ] https://github.com/sourcegraph/sourcegraph/issues/34103
  - [ ] **Design**: https://github.com/sourcegraph/sourcegraph/issues/34105
- [x] https://github.com/sourcegraph/sourcegraph/issues/34102
- [x] https://github.com/sourcegraph/sourcegraph/issues/34294
  - [x] **Design**: https://github.com/sourcegraph/sourcegraph/issues/31424 
- [ ] Cmd+Z support after you replace the contents of your batch spec with a library example
- [ ] Execution page: Overview when no workspace is selected **`4d`**
  - [ ] **Design**: #31088
- [ ] Admin: Users know if executors are set up **`3d`**
  - Needs design
- [ ] https://github.com/sourcegraph/sourcegraph/issues/31171

**Comment by malomarrec** [comment]
I suggest closing this issue, and using the `server-side` label from now on to group those issues.
I think large tracking issues were great to get to beta, but now we're gonna want to become more iterative.

**Comment by eseliger** [comment]
Yes, I want to clean this up, then convert it into separate tickets and then get rid of it.

**Comment by chrispine** [comment]
Does it make sense to consider this issue as the clean-up task Erik was talking about, and prioritize it higher? (Maybe just make it P0 and get it out of the way sooner rather than later?)

**Comment by eseliger** [comment]
This is a big bucket list of wishes, thoughts, feature gaps,... I've been meaning to split it up into individual tickets and closed this one out so we can prioritize them 1 by 1 but didn't get to it yet 🙃

**Comment by eseliger** [comment]
converted the big ones into tickets, closing this one.
