### ISSUE TITLE
Saved search query requires that a patterntype is defined

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#31093]
#### Steps to reproduce:

1. Try to "save search" for any search query on VSCE without a patterntype defined
2. 
<img width="901" alt="Screen Shot 2022-02-11 at 2 51 00 PM" src="https://user-images.githubusercontent.com/87138876/153659926-86a7be11-bc64-4141-bb35-3a875f1196d9.png">

#### Expected behavior:

Sourcegraph.com does not require that a patterntype be defined for a user to create a saved search.

**Comment by gitstart-sourcegraph** [comment]
Hi @jjinnii! This is @gitstart-sourcegraph. The SourceGraph Frontend team offloads a good amount of issues to me already (100+ merged PRs [link](https://github.com/sourcegraph/sourcegraph/pulls?q=is%3Apr+is%3Aclosed+assignee%3Agitstart-sourcegraph)) 

This looks like a bug issue we can help with. Can we pick it up and ship back a PR for your review?

**Comment by abeatrix** [comment]
fixed in the VSCE v2.2.1 release
