### ISSUE TITLE
Merge ability to highlight code in search results 

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#31092]
The ability to highlight code from search results was added to sourcegraph.com in [issue #875](https://github.com/sourcegraph/sourcegraph/issues/875). This new feature needs to be merged into VSCE for it to be available for extension users. 

Related issue #31029

**Comment by abeatrix** [comment]
The current version in tjk's branch has merged the ability to highlight code in search results; however, the result file will also be opened when trying to highlight the code. @tjkandala is working on refactoring the search result component so that file will not be opened until clicks.

**Comment by tjkandala** [comment]
Closed by #33102
