### ISSUE TITLE
zoekt-git-index spawns ctags using 40GB of memory on the megarepo

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#31106]
I added https://sourcegraph.com/github.com/sgtest/megarepo to my local Sourcegraph instance and managed to get a screenshot of ctags using 40GB of memory.

<img width="506" alt="CleanShot 2022-02-11 at 15 23 21@2x" src="https://user-images.githubusercontent.com/1387653/153678874-615e62aa-3808-4e2d-a40a-b5a884f2986d.png">

Right after I clicked "info" on ctags, it got killed, but the parent process (zoekt-git-index) was still visible:

<img width="601" alt="CleanShot 2022-02-11 at 15 23 28@2x" src="https://user-images.githubusercontent.com/1387653/153678877-76c60d79-8544-4485-bdd3-68e30d988934.png">

@sourcegraph/search-core any idea how this might be happening? Usually ctags only needs a few hundred MB of memory.

**Comment by keegancsmith** [comment]
Maybe a memory leak in ctags? I recently bumped the version of ctags we use, did you also upgrade just to rule that out?

We could maybe occasionally restart the ctags process just to shake out any bugs in it. Not the ideal solution, but a practical strategy.

**Comment by chrismwendt** [comment]
I upgraded my ctags on Feb 11 at 14:34. That's about 1 hour before reporting this issue, and my Sourcegraph instance might have still been using the old version, so I can't rule that out.

Current version:

```
$ ctags --version
Universal Ctags 5.9.0(p5.9.20220206.0), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Feb 11 2022, 14:34:02
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +gnulib_fnmatch, +gnulib_regex, +iconv, +option-directory, +xpath, +json, +interactive, +yaml, +case-insensitive-filenames, +packcc, +optscript, +pcre2
```

Occasionally restarting ctags would help reduce the likelihood of OOMing like this, and it's quick to restart :+1:

I'll reopen if I notice this happen again now that I upgraded ctags and restarted my Sourcegraph instance.
