### ISSUE TITLE
Update pings documentation doc with the new 3.37 pings

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#31120]
We should keep our docs up to date! Didn't want to put this in for the prior iteration because not time sensitive, but now that the release will be out we should add the landing page (and any new dashboard) pings to the [docs page](https://docs.sourcegraph.com/dev/background-information/insights/code_insights_pings). 

The tickets that may need to be documented, if they complete: 
- [x] #30633
- [x] #31078
- [x] #30608
- [ ] #29959

**Comment by CristinaBirkel** [comment]
https://github.com/sourcegraph/sourcegraph/pull/32092/files covers the dashboard BE pings.
