### ISSUE TITLE
Rockskip: deploy to dogfood and collect stats

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#31139]
In order to vet Rockskip for production deployment, let's deploy it to dogfood and throw fake traffic at it.

In the process, let's also collect stats and compare them to the current implementation of the `symbols` service.

Stats to collect:

- % of requests that time out (5s) and show the user an error
- Disk used and Postgres table sizes
- Distribution of search response times
- Breakdown of timing by task (holding locks, parsing, etc.)

Once we have stats, we can see if Rockskip is better or worse than the current implementation, and by how much. That will inform decisions about investing more effort into Rockskip and whether or not a hybrid solution is worth pursuing.

**Comment by mrnugget** [comment]
@chrismwendt isn't this done? (Was just looking at the board and wondering about this)

**Comment by chrismwendt** [comment]
Yup, here are the stats we got:

- % of requests that time out: 100% until the cold start finishes, then none of the queries I ran timed out regardless of which commit I was on :pogfish:
- Postgres table sizes: the `rockskip_symbols` table ends up being roughly the same size as the `.git` directory
- Distribution of search times: didn't collect this info, seems to be ~100ms even on regex queries (`pg_trgm` FTW)
- Breakdown of timing by task: here's a sample:

> Tasks (3538.30s total, current ArchiveEach): AppendHop+ 45.87% 14688x, AppendHop- 18.39% 14688x, DeleteRedundant 13.95% 14687x, parse 5.51% 156165x, ArchiveEach 4.75% 29376x, GetSymbol 4.11% 713664x, InsertSymbol 2.39% 131100x, UpdateSymbolHops 2.02% 89270x, GetCommitByHash 0.96% 265606x, get hops 0.83% 14688x, CommitTx 0.51% 14687x, InsertCommit 0.40% 14688x, RevList 0.17% 1x, Log 0.15% 1x, iLock 0.00% 1x, idle 0.00% 1x, 

Most time is spent in `AppendHop{+,-}`, which is difficult to optimize and/or avoid. The perf is acceptable at ~15 hours to index the megarepo.
