### ISSUE TITLE
Fuzzy finder not working after using files sidebar with Firefox

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#31145]
- **Sourcegraph version:** live on Cloud now
- **Platform information:** Firefox 96.0.3 (64-bit), macOS Intel

#### Steps to reproduce:

Originally reported by @coury-clark on Slack https://sourcegraph.slack.com/archives/CHXHX7XAS/p1644337960653609

1. Open page https://sourcegraph.com/github.com/sourcegraph/docsite/-/blob/markdown/metadata.go
2. Open another file in the files sidebar, for example `fs.go`
3. Trigger fuzzy finder with Cmd+K (macOS) or Ctrl+K (Linux/Windows)
4. Type "search.go", select top result
5. The URL switches to `search.go` for a brief second and then goes back to `fs.go`

#### Expected behavior:
The URL should permanently switch to `search.go` in step 5.

#### Actual behavior:
The URL goes back to `fs.go` in step 5.

### Context

I'm only able to reproduce with Firefox, not Safari or Chrome. cc/ @sourcegraph/frontend-platform any idea what browser feature we're using that breaks only on Firefox?

**Comment by fkling** [comment]
I'm not able to reproduce this anymore.
