### ISSUE TITLE
Update cockroachdb/errors to the latest version 

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#31160]
Once https://github.com/cockroachdb/errors/pull/92 is included in new release, we will finally be able to get rid of the warnings on sentry.io by being able to replace the import to their forked version of `sentry-go` which is stuck to v0.6.1. 

Or we can pin the latest commit.

**Comment by knz** [comment]
it's included now - v1.8.7

**Comment by jhchabran** [comment]
Thanks for the heads up @knz 🙏 !

**Comment by jhchabran** [comment]
Already handled by https://github.com/sourcegraph/sourcegraph/pull/31466
