### ISSUE TITLE
batches: Rethink filters on batch change page

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#31164]
We recently defaulted to "All" as the standard, because we felt that Draft BCs were hidden too much. 
While I agree, I think this causes another problem, especially on the global list, where the list might be extremely long by default because it includes all those closed ones from the past.
Maybe we should default to draft + open, instead of "All", like GitHub does for PRs and issues?

**Comment by courier-new** [comment]
Bumping this to 2d because we don't actually have a Wildcard multi select component yet to support combined states like this, as far as I can tell. Hoping I can reuse or take inspiration from our `MultiSelectContext` for selecting items in a connection list for this.

**Comment by eseliger** [comment]
Also, we don't have a way in the backend to filter by multiple arbitrary states.

**Comment by courier-new** [comment]
Cough 👀
<img width="879" alt="image" src="https://user-images.githubusercontent.com/8942601/155633246-6b4f9b76-1b24-4bfc-992e-8b37e4e204c4.png">
