### ISSUE TITLE
ci: possible flake caused by unbounded concurrent build

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#31190]
See https://github.com/sourcegraph/sourcegraph/pull/31186#issuecomment-1039388850

<img width="829" alt="image" src="https://user-images.githubusercontent.com/10151/153921109-78cbe70c-548a-4727-b18f-8b5d453347e2.png">

**Comment by keegancsmith** [comment]
I am removing concurrency in the hopes this sorts it out. In the last 15min 38 builds passed, 8 failed. That is pretty bad.
