### ISSUE TITLE
Can't Signout -- OAuth as only Auth

### ISSUE THREAD

**Issue by DaedalusG** [sourcegraph/sourcegraph#31192]
- **Sourcegraph version:** 
- **Platform information:** 

#### Steps to reproduce:
1. Create a Sourcegraph instance and configure OAuth as the only source of login
```json
	"auth.providers": [
		// {
		// 	"type": "builtin",
		// 	"allowSignup": false
		// },
		{
			"type": "github",
			"displayName": "GitHub",
			"clientID": "REDACTED",
			"clientSecret": "REDACTED",
			"allowSignup": false, // Set to true to enable anyone with a GitHub account to sign up without invitation
			"allowOrgs": [ "sourcegraph" ] // Restrict logins to members of these orgs.
		},
          ]
```
2. Sign out and attempt to sign back in

#### Expected behavior:

You should be able to signout

#### Actual behavior:

You'll very briefly be signed out -- but you'll immediately be signed back in

This is because Sourcegraph will automatically attempt to use the only available sign in method id only one sign on option is available. If OAuth is the only available option a OAuth signing will immediately be attempted. 

Just noting this is documented in our [codebase comments](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+If+there+is+only+one+auth+provider+configured&patternType=literal), so its not a bug per say

**Comment by DaedalusG** [comment]
@dan-mckean yeah that's exactly it -- not a bug per say although I think it might sometimes cause some problems with our license renewal flow -- I can't find an issue on that but I seem to recall a case where users became unable to sign in to an instance due to this automated boot signing flow

**Comment by dan-mckean** [comment]
Thanks @DaedalusG . 

We're not going to work on this as a support thing - weird though it is. 

There are conversations going on about ownership of auth. This isn't exactly strategic work,  but it certainly is a UX enhancement that warrants being made! Thanks for flagging it.

**Comment by DaedalusG** [comment]
Just want to make a further note that in a test instance where this setup was enabled -- I have a test instance running with this configuration as well as some session exipracy settings --
```json
	"authz.enforceForSiteAdmins": true,
	"auth.sessionExpiry": "1h",
```

After an upgrade some odd login flow issues were observed for some users --
![image (9)](https://user-images.githubusercontent.com/13024338/159805377-5b739b63-2bbf-417c-a65a-1ba007e44990.png)
![image (8)](https://user-images.githubusercontent.com/13024338/159805380-f8be7989-fa01-4b25-a9b9-41904d281aa5.png)

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.
