### ISSUE TITLE
Complete V2 of Wildcard Component Library

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#31204]
## Problem to solve

Engineering teams need reusable UI components to improve velocity and consistency across the application. 

## Measure of success

Wildcard V2 components fully implemented and codebase fully migrated. 

## Solution summary

Artifacts:
- [Wildcard V2 - Planned work](https://docs.google.com/document/d/1NisbJPiadtt5jQw4vUUYJOr8dD6Urwn5V0mVq2wt6bE/edit#heading=h.ez83dxila4ol)
- [Wildcard Components Prioritisation](https://docs.google.com/spreadsheets/d/1o_eHs6h7zEHxM75bUMMI6-v7st_-GwJqtSfOaVHlNdk/edit#gid=1724329724)

## What specific customers are we iterating on the problem and solution with?

Internal Sourcegraph developers, especially those focused on the frontend. 

## Impact on use cases

Reusable UI components will improve the velocity of all product teams, enabling them to more effectively deliver on use case solutions. 

## Delivery plan

WCL V2 components still in progress:
- [x] Panel
- [x] Link
- [x] FeedbackPrompt
- [x] Select
- [x] Popover
- [x] Icon
- [x] Typography
- [x] Checkbox
- [ ] Input
- [x] Menu
- [x] ButtonLink
- [x] Tabs

For more details, see the [tracking issue](https://github.com/sourcegraph/sourcegraph/issues/27606) for this body of work

**Comment by taylorsperry** [comment]
This work will spill into the first month of Q2 for the following reasons:
1. The team has been at reduced capacity since mid-February.
2. This is non-blocking work that was safely de-prioritized in favor of various support and CI issues.
3. Remaining work is clearly planned and scoped, and much of it has been assigned to Gitstart. The team will still be able to focus on Q2 roadmap issues. 

See [this thread in Slack](https://sourcegraph.slack.com/archives/C029WBCNR9R/p1650370638842679) for more details on what's been implemented this quarter, and what's left to do.

**Comment by valerybugakov** [comment]
Closed by completing https://github.com/sourcegraph/sourcegraph/issues/27606
