### ISSUE TITLE
Pressing escape key while on search result page causes Monitor and Saved Search to appear

### ISSUE THREAD

**Issue by marekweb** [sourcegraph/sourcegraph#31218]
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:** all

#### Steps to reproduce:

1. Be logged out
2. Perform a search
3. Press escape on the search result page

#### Expected behavior:

Focus is removed from the search box and nothing else happens

#### Actual behavior:

The "Monitor" and "Saved searched" popups both become visible.

Pressing escape again toggles their visibility.

![Screenshot from 2022-02-14 18-34-13](https://user-images.githubusercontent.com/602886/153964776-7edacd1c-e014-4802-9cc7-bf3f693cd134.png)

**Comment by umpox** [comment]
This was likely caused by this migration: https://github.com/sourcegraph/sourcegraph/pull/29582

We have since fixed a few different bugs caused by this, and I can no longer replicate this bug.

Please reopen if it can be replicated still!
