### ISSUE TITLE
insights: add "new" tag to menu bar insights item

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#31213]
Code Insights is going GA! We should make this a bit more prominent in the product to help announce our launch, and now that we have a landing page that helps folks use it. [RFC with full discussion.](https://docs.google.com/document/d/1oBofTBXCKnV4yYEc6aBl7OETfJR37h_wVkCUc7gN8i0/edit#)

Let's implement a "New" tag on the menu item, which should appear in the navbar after 3.37: 

https://www.figma.com/file/9Dbsa4uK73yqbdzyVSWOYq/RFC-598-PRIVATE%3A-Code-Insights-GA-In-Product-Marketing-('NEW'-badge)?node-id=275%3A1628

This new badge should appear: 
- In the product immediately after upgrade to 3.37 
- Optionally, if time: 
   - Can we make it go away after the user clicks on it?

**Comment by vovakulikov** [comment]
@Joelkw A few moments around this tag's disappearing. 
- If users click on the "Insight" main nav bar this tag is disappearing (this is core logic)
- If users for example visit any code insight pages (like on click creation UI from the search page) should we hide this tag? 
- If we ignore the second point - should we hide this tag if a user has visited `/insights/` (the main page) directly by URL and didn't click on the main nav bar.

**Comment by Joelkw** [comment]
@vovakulikov good questions. 

* If a user clicks on insights in the main nav bar we should make it disappear, yes.
* If they visit any pages from the search button it's okay (but not optimal) if it disappears but it might be nice if it only disappears after you click the navbar item itself (so you see the getting started page still).
* If a use has visited the main page directly then yeah we can hide it (or not, no preference so whatever is easiest here, not a big deal at all). 
*

**Comment by AlicjaSuska** [comment]
Thank you @Joelkw I've updated the link to the [design](https://www.figma.com/file/9Dbsa4uK73yqbdzyVSWOYq/RFC-598-PRIVATE%3A-Code-Insights-GA-In-Product-Marketing-('NEW'-badge)?node-id=275%3A1628) in the description (I needed to create a new file since the one you've shared was 'view only')
