### ISSUE TITLE
"View file diff" button and code hover actions don't appear consistently in GitHub commit diffs.

### ISSUE THREAD

**Issue by wtodom** [sourcegraph/sourcegraph#3122]
When viewing a commit on GitHub such as [this one](https://github.com/mtgred/netrunner/commit/5e99b857cd81f51ab0bb5473d19ab3bee40b522a) or [this other one](https://github.com/mtgred/netrunner/commit/957eeaa7c49c49999f8f37e126bda01ab877e82b#diff-078e2f1f1f50e2565ab500fe3accebc4), it seems that I often have to scroll to the bottom of the page and back up before most of the Sourcegraph plugin functionality begins working on the page. Additionally, it looks like the failures happen at the file diff level, since the functionality works for some files initially - specifically the ones that are "off-screen" when the page loads. Screenshots demonstrating this:

**Upon page load, before scrolling**
![before-scroll](https://user-images.githubusercontent.com/690431/55361027-d490f300-548a-11e9-8710-4e6ab0b643c6.jpg)

**After scrolling part of the way down the page**
![mid-scroll](https://user-images.githubusercontent.com/690431/55361037-d6f34d00-548a-11e9-96a3-dbc485f8ad85.jpg)

**After scrolling down and then back up to the top**
![after-scroll](https://user-images.githubusercontent.com/690431/55361044-d8bd1080-548a-11e9-8835-ed04989ca7a6.jpg)

The same "late-loading" effect can be seen for Sourcegraph's code hover popup functionality as well.

**Comment by felixfbecker** [comment]
Hi @wtodom, I just published a new version 19.4.1.2142 with a big change that should fix this. Could you ensure you have that version and check if you still see this issue?

**Comment by wtodom** [comment]
Oh wow, we just barely missed each other - I installed the extension just an hour ago or so. I was able to update to the new version and verify that this behavior appears to be fixed. Thanks!

**Comment by felixfbecker** [comment]
Awesome! In case you meet any other issue, don't hesitate to file it and I'll take a look.
