### ISSUE TITLE
sg: migration running code at init time prevent to use sg outside the repo

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#31251]
This effectively breaks `sg setup` entirely. 

See https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/sg/sg_migration.go?L114-136

**Comment by jhchabran** [comment]
@efritz could you take a look at this? We should really avoid relying on init stage in `sg`, this can create this kind of bug. 

I'll write a unit test so we can catch this much sooner!

**Comment by mrnugget** [comment]
Fixed by @bobheadxi in #31329
