### ISSUE TITLE
Code monitoring: Add "Include results" toggle in UI

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#31265]
#31001 added the 'IncludeResults' option and #31212 uses it. We need to add this to the UI when creating/editing code monitor actions.

**Comment by lguychard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Search-Product-61302e38f801dc0012e2e050/issues/sourcegraph/sourcegraph/31265?planning-poker) with ZenHub @benvenker @camdencheek @fkling @limitedmage @marisak @novoselrok @rvantonder
