### ISSUE TITLE
"Code Search" dropdown menu stuck open

### ISSUE THREAD

**Issue by courier-new** [sourcegraph/sourcegraph#31281]
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:** Most major browsers (Chrome, Firefox, Safari, Brave tested)

#### Steps to reproduce:

1. Visit sourcegraph.com.
2. Hover "Code Search" in the top menu to expand the dropdown menu.
3. Keeping mouse cursor within top menu, slide mouse horizontally to the right until it hovers another menu item, e.g. "Extensions."
4. Slide mouse cursor down to exit the menu.

#### Expected behavior:
"Code Search" dropdown menu collapses.

#### Actual behavior:
"Code Search" dropdown menu is stuck open until mouse enters and leaves the dropdown container's left, right, or bottom edge.

https://user-images.githubusercontent.com/8942601/154165268-3ad23466-4784-4c76-a932-431866dbbd7c.mov

**Comment by umpox** [comment]
Closed by reverting to the previous implementation. I'll make sure we check this when the dropdown is reimplemented in https://github.com/sourcegraph/sourcegraph/issues/31492
