### ISSUE TITLE
Use GitHub API caching when fetching repo metadata

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#31302]
The GitHub API supports caching, as described [here](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#conditional-requests) 

We should be able to use this when syncing repo metadata. Local testing indicates that this works
for the `repos/{owner}/{name}` endpoint and most importantly doesn't incur any rate limiting when 
the repo has not been modified recently.

We should be able to use this in our repo syncer to reduce the load on the GitHub API.

**Comment by eseliger** [comment]
This has been implemented generically using our HTTP redis cache.
