### ISSUE TITLE
Include helm chart in our release process

### ISSUE THREAD

**Issue by michaellzc** [sourcegraph/sourcegraph#31335]
## Context
Our helm chart is still in beta. Given this is on our Q1 plan, we should improve the tooling and properly support it. 

## The problem

Our [release process](https://handbook.sourcegraph.com/departments/product-engineering/engineering/process/releases/) doesn't include update to helm chart. Right now, we just rely on Crystal to remember running this [script](https://github.com/sourcegraph/delivery-scratch/blob/main/2022/helm-updates/update-tags.sh) to cut a new release for helm chart.

We actually forgot to update our helm chart for the 3.36.3 patch release.

## What do do

- [x] Update handbook to include updating our helm chart for new releases
- [x] Port the [script](https://github.com/sourcegraph/delivery-scratch/blob/main/2022/helm-updates/update-tags.sh) with a more proper implementation within the [sourcegraph developer tool](https://docs.sourcegraph.com/dev/background-information/sg) https://github.com/sourcegraph/sourcegraph/pull/31141
  - the tool can also make our life easier when testing changes locally.
- [x] Update batch change to use `sg` for releases

**Comment by caugustus-sourcegraph** [comment]
@michaellzc -  Once the sg tool is updated to work with specific versions, could we incorporate this update into the normal release batch change?

**Comment by michaellzc** [comment]
yes! that's the plan
