### ISSUE TITLE
ci/flake: cluster QA disabled

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#31342]
### Test

Sourcegraph Cluster (deploy-sourcegraph) QA

### Example failure

- https://buildkite.com/sourcegraph/sourcegraph/builds/132037#85b8f258-9b65-4b71-9db0-bcf23d79418f
- https://buildkite.com/sourcegraph/sourcegraph/builds/131754#baa33320-20b7-4698-9835-c38115c1a9c3

### Disabling PR

https://github.com/sourcegraph/sourcegraph/pull/31339

### Additional details

Unfortunately, it looks like both the tests and the deployment are unstable: https://sourcegraph.grafana.net/goto/oqXtXMfnz?orgId=1

<img width="1721" alt="image" src="https://user-images.githubusercontent.com/23356519/154351031-fd3c38a8-9024-4e87-8b87-f4ae277a3b5e.png">

See disabling PR for more details

**Comment by davejrt** [comment]
Closing as we now have a soft fail for this, and the last flake was an upstream issue...not in our tests.

**Comment by bobheadxi** [comment]
> Closing as we now have a soft fail for this

@davejrt We should only close the issue if tests are stable, otherwise the tests are still flakey and this issue should remain open - for now, I'm opening a PR to re-enable the tests: https://github.com/sourcegraph/sourcegraph/pull/32410
