### ISSUE TITLE
Link error

### ISSUE THREAD

**Issue by imba-tjd** [sourcegraph/sourcegraph#31371]
#### Describe the issue

![image](https://user-images.githubusercontent.com/24759802/154390827-08e5a527-2b2a-467d-913a-21618be6780d.png)

The link is `https://docs.sourcegraph.com/code_intelligence/explanations/precise_code_intelligence)` which is wrong.

Besides, these two links are *Not found*:

![image](https://user-images.githubusercontent.com/24759802/154400966-0ad644ad-95f3-4593-b532-ec22d58cf2d1.png)

#### Where is the issue located?

A hint message.

#### Suggested resolution

IDK

**Comment by r-shahid** [comment]
hey @imba-tjd that link has been fixed, thanks for calling attention to it!
