### ISSUE TITLE
sub-repo explicit permissions API

### ISSUE THREAD

**Issue by dan-mckean** [sourcegraph/sourcegraph#31405]
## Problem to solve
Two large customers using CVS require support for sub-repo level permissions support. Without it, we're not honoring their permissions governing who can access what code within CVS. 

Rather than undertake a huge amount of work to implement Native CVS support (which requires supporting it as a code host and a auth provider), we're going to provide sub-repo permissions support via [the Explicit Permissions API](https://docs.sourcegraph.com/admin/repo/permissions#explicit-permissions-api).

As a extra element of this work, we're going to enable the Explicit Permissions API to be utilized alongside native permissions support for another code host (as required by one of the customers). More info in [RFC 626: Permissions Mechanisms in Parallel](https://docs.google.com/document/d/1nWbmfM5clAH4pi_4tEt6zDtqN1-z1DuHlQ7A5KAijf8/edit#).

## Measure of success
We will be able to support sup-repo CVS permissions.

## Solution summary

Artifacts:
- TO DO

## What specific customers are we iterating on the problem and solution with?

- https://github.com/sourcegraph/accounts/issues/5
- https://github.com/sourcegraph/accounts/issues/8004

## Impact on use cases

No direct correlation with any of the use cases, but support for code hosts and permissions is fundamental to basic Sourcegraph usage.

## Delivery plan

- [ ] TO DO

**Comment by dan-mckean** [comment]
# Update: 2022-04-07
## Status
🟠  at risk for running over into Q2

## Complete
- [x] Validation of viability
   - We can extend the Explicit Permissions API
   - We can support Explicit Permissions API to be used alongside native code host permissions

## In Progress
- [ ] Planning (nearing completion)

## Next actions 
- Execution of the work

## Any other helpful context/information
No

**Comment by eseliger** [comment]
Closed by https://github.com/sourcegraph/docs/pull/283
