### ISSUE TITLE
Show banner on draft batch change when execution is running

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#31419]
Instead of this empty list, we want to show a banner that links to the execution.

<img width="1128" alt="image" src="https://user-images.githubusercontent.com/19534377/154539001-4687ef14-ae7a-485f-97bb-55e66571f0ca.png">

**Comment by malomarrec** [comment]
@rrhyne this is upcoming in the next sprint

**Comment by courier-new** [comment]
Looks like we left off with this:
https://www.figma.com/file/cTKjwbvWqU6xAykZmCTTqy/SSBC?node-id=2160%3A65223

**Comment by rrhyne** [comment]
@courier-new I've updated the Figma with a hot take on an empty screen and copy for this page. 

https://www.figma.com/file/cTKjwbvWqU6xAykZmCTTqy/SSBC?node-id=2244%3A67825

**Comment by courier-new** [comment]
Thanks @rrhyne!! I like it, I think that's even better than a banner.

**Comment by rrhyne** [comment]
What I linked was a notice for the draft that has not been executed, which is slightly different than the title of this item. I found the existing design for execution is running which is just a banner, but I think it works well as a notification from any tab.

**Comment by courier-new** [comment]
Closing this since design work is complete!

**Comment by courier-new** [comment]
Engineering ticket for implementation: https://github.com/sourcegraph/sourcegraph/issues/32589
