### ISSUE TITLE
SSBC: Signify unsupported and ignored workspaces in lists

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#31424]
In workspaces lists, we want to show when we found search results in unsupported or ignored workspaces.

- We will always show all workspaces (including unsupported and ignored) in the list for now
- Unsupported and ignored workspaces should have a status icon indicating they are unsupported/ignored
  - Status icon should have tooltip that explains we will not execute or produce changesets for this workspace
- On execution screen, unsupported and ignored workspaces are not clickable

**Comment by danielmarquespt** [comment]
Design Solution: Just add a simple tag to the row 

Figma: https://www.figma.com/file/vW0D7Os7vkQ0eFNPXhcqas/%F0%9F%A6%A1-Batch-Changes-MAIN-%5BWIP%5D?node-id=33%3A4113
