### ISSUE TITLE
Cloud pre-prod/staging environment 

### ISSUE THREAD

**Issue by bcreager** [sourcegraph/sourcegraph#31441]
## Problem to solve
Historically, Sourcegraph Cloud was used as a large-scale testing enviornment for new features since there were no paying customers on Cloud. Today that culture continues and commits to the master branch are directly deployed to cloud, without any staging enviornment. This leads to increased incidents, caused by code that has not been fully tested.  

## Solution summary
- A staging (or pre-prod) enviornment that  mimics our production enviornment to allow for robust testing of new changes. 
- CD Process Update"

## What specific customers are we iterating on the problem and solution with?
Paying cloud customers

## Impact on use cases
N/A

**Comment by RafLeszczynski** [comment]
The scope planned by DevOps team is mostly done with two remaining items in progress that the team is planning to complete this week:

- https://github.com/sourcegraph/sourcegraph/issues/32878
- https://github.com/sourcegraph/sourcegraph/issues/29251
