### ISSUE TITLE
Feature request: Search support for Lookahead / Lookbehind

### ISSUE THREAD

**Issue by northyg** [sourcegraph/sourcegraph#31454]
#### Feature request description

Hello! @rvantonder and @camdencheek !  Passing along this feedback on behalf of Sourcegraph users who have run into errors like this when trying to use Lookahead / Lookbehind type searches.

Example:
```
http://(?!localhost)
Unable To Process Query
Error parsing regexp: invalid or unsupported Perl syntax: (?!
```
It's [known that we support](https://docs.sourcegraph.com/code_search/reference/queries#regular-expression-search) the following: [RE2 syntax](https://golang.org/s/re2syntax) because lookahead / lookbehind is said to be resource intensive. https://github.com/sourcegraph/sourcegraph/issues/636

However, we don't seem to have a clearly documented way for customers to achieve what they'd like with a work around. https://github.com/sourcegraph/sourcegraph/issues/15365 Essentially, customers would like to use this type of search and it's fairly common for these types of questions to come up.

**Comment by camdencheek** [comment]
Hi @northyg! As mentioned in #636, I'd agree that we're very unlikely to ever support lookahead/lookbehind as in the example. Right now, I think the best options are either to:
1) Use and/or/not to get similar results. You can get pretty close to your example with `http:// not http://localhost` even if it's not exactly semantically the same.
2) Query through the API / src CLI and use a tool that does have lookahead/lookbehind to filter results. Something like `src search  -json 'http://' | jq  -r '.Results[].file.content' | rg --pcre2 'http://(?!localhost)'` should do what they're looking for

**Comment by northyg** [comment]
Thanks @camdencheek ! I appreciate your response and suggestions. I definitely understand where we're coming from here :)
