### ISSUE TITLE
Optimize onboarding for visitors to increase retention

### ISSUE THREAD

**Issue by anna-mmikhova** [sourcegraph/sourcegraph#31460]
## Problem to solve

Activation and Retention for Sourcegraph.com do not provide enough pipeline to capture target Revenue for FY23.  We want to become top of mind for our users for their use case, they can clearly identify value and continue to engage with our platform. Active / signed in users are more likely to convert to paying customers therefore we want to pull valuable experiences earlier in the funnel so we can create recurring usage. 

Signed in users do not return to the product at a healthy rate. By week 12, we've retained half the registered users who came back in week 1. 

## Measure of success

We aim to positively impact the following:

- Activation increase
- Retention Increase
- PQL Increase

## Solution summary

Polish our funnel, be deliberate in our targeting and get users quickly to the solution that will benefit their use case.  Partner with marketing to create focus around use-cases and ensure visitors get what they came for.

## Impact on use cases

Bring new users within each use case to their "Aha" moment faster

## Delivery plan

- [x] [Getting started checklist for visitors](https://github.com/sourcegraph/sourcegraph/issues/27177)
- [x] [Getting Started Checklist for authenticated users](https://github.com/sourcegraph/sourcegraph/issues/28322)

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @a-bergevin - the "team/growth" label was applied to this issue.

**Comment by a-bergevin** [comment]
I am marking this issue as "done" and creating a new one for the next steps on evolving these features. Since the goal was to launch these two checklists this quarter and the team did that. Otherwise this could just be a never ending roadmap item if I just tweak it and move it to the next quarter.
