### ISSUE TITLE
Replatform about.sourcegraph.com/blog

### ISSUE THREAD

**Issue by marybelzer** [sourcegraph/sourcegraph#31504]
## Problem to solve

1. About.sourcegraph.com/blog is currently difficult to develop on.
2. Unifying our tech stack across platforms will reduce the pain of context switching between sites, and allow us to reuse more code between properties.
3. This is a prerequisite for implementing the Contentful CMS on about.sourcegraph.com/blog

## Solution summary
Replatform about.sourcegraph.com/blog to next.js

Artifacts:
- Full scope of blog work is being tracked [here](https://github.com/orgs/sourcegraph/projects/227/views/16)

## What specific customers are we iterating on the problem and solution with?

-Marketing

## Impact on use cases

The blog is full of rich content about Sourcegraph and how to use it across the five use cases. A more reliable and easy-to-modify blog will better empower the marketing team to draw customers in through blog content and share the message of the five use cases.

## Delivery plan

- [ ] [TO DO](https://github.com/orgs/sourcegraph/projects/227/views/16?layout=board&filterQuery=repo%3A%22sourcegraph%2Fblog%22+is%3Aissue+label%3Aconfig)

**Comment by jeanduplessis** [comment]
The blog was re-platformed to Next.js along with the re-platform of the marketing site: https://github.com/sourcegraph/sourcegraph/issues/31498
