### ISSUE TITLE
TypeError: [(...O.values(...))].flatMap is not a function

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#3159]
This was [reported on Sentry](https://sentry.io/organizations/sourcegraph/issues/964678642/?project=1334031&referrer=alert_email&statsPeriod=14d)

The code was added with the #2909 refactor:

https://github.com/sourcegraph/sourcegraph/blob/8617b20038b21d8c65534c9407ca092afc73b12f/client/browser/src/libs/code_intelligence/code_intelligence.tsx#L517-L529

https://github.com/sourcegraph/sourcegraph/blob/8617b20038b21d8c65534c9407ca092afc73b12f/client/browser/src/libs/code_intelligence/code_intelligence.tsx#L665-L673

**Comment by felixfbecker** [comment]
Ah, this is because of an old Chrome version: 68.0.3440.
Our browserslist policy says to only support the most recent.

**Comment by felixfbecker** [comment]
Closing as updating resolves this
