### ISSUE TITLE
`cmd/server/Dockerfile` still uses `sourcegraph/syntect_server` image

### ISSUE THREAD

**Issue by tjdevries** [sourcegraph/sourcegraph#31593]
While investigating, I found that https://sourcegraph.com/gitlab.com/sourcegraph/sourcegraph/-/blob/cmd/server/Dockerfile?L61&subtree=true is using an older version of the docker image for syntect_server (not syntax-highlighter). This should be updated.

Probably worthwhile to go through and delete all references to `syntect_server` in the codebase as  well.

_Originally posted by @tjdevries in https://github.com/sourcegraph/sourcegraph/issues/30016#issuecomment-1041043521_

**Comment by eseliger** [comment]
It looks like this is no longer true
