### ISSUE TITLE
Chrome regression: in-page Chrome search no longer works for most queries

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#3160]
When searching using browser's built in page search, it is now broken if your search query includes a dash `-`, parentheses `(` or `)`, period `.`, or any other token-separating characters.

I believe this is a regression since the last released version of Sourcegraph, as I use this regularly in my workflow and would've noticed if it was a regression longer ago.

Reproduce:

1. Go here: https://sourcegraph.com/github.com/jaegertracing/jaeger/-/blob/plugin/storage/cassandra/schema/docker.sh
2. Cmd+f (or ctrl+f on Windows).
3. Type `jaeger-cassandra`, notice it turns up no results.

- Another example (search for `errors.New`): https://sourcegraph.com/github.com/gorilla/mux/-/blob/mux.go
- Another example (search for `[]*Route`): https://sourcegraph.com/github.com/gorilla/mux/-/blob/mux.go (this one behaves very strangely, sometimes finding one result but not finding secondary ones)

**Comment by slimsag** [comment]
@felixfbecker any idea about what may have introduced this, or who may have most context?

**Comment by felixfbecker** [comment]
I can't think of any changes to that code in a long time o.O

Could it possibly be a browser bug? I don't understand why Chrome would not be able to search this text. Firefox works fine...

**Comment by felixfbecker** [comment]
The only thing that could be preventing searching is splitting into `span`s but we need to do that for syntax highlighting and hovers and it doesn't make a lot of sense that that would keep a browser from searching the text

**Comment by slimsag** [comment]
Interesting, it definitely could be a browser regression, I'll see if it happens on an older version of Sourcegraph like 2.x

**Comment by slimsag** [comment]
Confirmed, it must be a regression in Chrome as it also occurs in Sourcegraph 2.12.3

**Comment by slimsag** [comment]
I am backlogging because I guess there is nothing we can do, but keeping open because this is a real issue and it sucks. Maybe make a small reproduction and file upstream?

**Comment by dadlerj** [comment]
@slimsag @sourcegraph/code-nav any updates on this? Did we file upstream? Just received a question about this from https://app.hubspot.com/contacts/2762526/company/693777177 

I assume building an in-app search would be the last option here, but curious what Code Nav team thinks about prioritization.

**Comment by felixfbecker** [comment]
Building in-app search would take significant work. This seems like a pretty bad bug in a browser, so I would file it in the chromium bug tracker first.

**Comment by slimsag** [comment]
Yeah that makes sense. @felixfbecker can you or someone else on the code nav team own moving this forward? (i.e. finding out which version of Chrome caused this regression, doing a minimal reproduction & filing an issue on Chromium so we have high likelihood of it being fixed?)

**Comment by felixfbecker** [comment]
Yes. I don't think finding the version is needed, it would be a lot of work. A repro should be trivial, just need to copy the HTML of the DOM nodes where this happens from the DOM explorer.

**Comment by danielpops** [comment]
I also ran in to this issue today where I couldn't search for yaml keys that ended in colons => https://i.fluffy.cc/Nv3V3LWXZnJHL3bS63674tsj8QLSKJRn.png

I could not find any results when I included that trailing colon.

Out of curiosity, I found other websites that display yaml which _can_ be searched as expected => https://i.fluffy.cc/GP2GfpZ59ZsFTG0Vc8fX4K7DLSnhrcDJ.png

Not sure what the exact difference is, but maybe sourcegraph can make some minor changes to the markup to make it work again?

**Comment by christinaforney** [comment]
Hey @felixfbecker and @lguychard - do we have a bug filed with Chrome about this that we can link here for tracking? 

Just had another customer hit this: https://app.hubspot.com/contacts/2762526/company/561806411/
