### ISSUE TITLE
Configure Git LFS for browser extension integration fixtures

### ISSUE THREAD

**Issue by erzhtor** [sourcegraph/sourcegraph#31620]
Currently, we are tracking all polly.js fixtures of pages in git. As we add more tests, it will grow even further. We need to start tracking them using git-lfs + to make sure that it works on CI.
 
 See https://docs.github.com/en/repositories/working-with-files/managing-large-files/configuring-git-large-file-storage

**Comment by taras-yemets** [comment]
Git LFS was configured in [pull/31572](https://github.com/sourcegraph/sourcegraph/pull/31572)
