### ISSUE TITLE
GraphQL API's setRepositoryEnabled deprecation path

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#3162]
We learned that a customer relies on our GraphQL API's `setRepositoryEnabled` mutation from a custom CLI script to prevent Sourcegraph from showing repos that are actually private and shouldn't be visible to all the customer's employees. It would hurt our chances of success if 3.3 removed `setRepositoryEnabled` without an alternative. They can achieve the same outcome by editing the external service JSON config via the GraphQL API, but this would require their script to know JSONC (JSON with comments and trailing commas), which would be error-prone for them. Is it possible/planned to preserve the functionality of `setRepositoryEnabled` in 3.3 and just make it perform the update to the ext svc's `exclude` property?

Part of #2025

**Comment by tsenart** [comment]
I'm starting on this now.

**Comment by tsenart** [comment]
@sqs, @keegancsmith, @slimsag: This endpoint takes in a Sourcegraph repository id and sets the enabled state directly on it. This means that they must be listing all repositories that exist too. However, repos that are managed by the new syncer are always enabled, so I'm not sure what this endpoint would do, as listing all the repos in the first place would return only enabled repos (of external services managed by the new syncer).

**Comment by slimsag** [comment]
@tsenart by chance could you explain how #3227 relates to this and/or how you're thinking about this? I trust you but just want to be sure I am on the same page about end result here so I know how to communicate it :D

**Comment by tsenart** [comment]
@slimsag: #3227 is just a necessary change to implement an HTTP endpoint in repo-updater that adds repos to the exclude list of their respective external services. This endpoint would be called from the graphql mutation resolver.

**Comment by keegancsmith** [comment]
> They can achieve the same outcome by editing the external service JSON config via the GraphQL API, but this would require their script to know JSONC (JSON with comments and trailing commas), which would be error-prone for them. 

@sqs we have a PR out to which updates the setEnable mutation to edit the config. However, what is the automation that runs? We now have an `exclude` and `repos` field for bitbucket/gitlab/github and `repositoryQuery` for bitbucket. Would this be good enough to remove the need for the automation they have?

**Comment by slimsag** [comment]
No, the reason that alone is not sufficient is because they have an
bitbucket access token with access to all repositories, then subsequently
based on a list disable ones that plain users should not have access to.
When we eventually have bitbucket server ACL enforcement then that would be
sufficient to remove this automation, but until then it's an ad-hoc
solution. Does that make sense?

**Comment by keegancsmith** [comment]
> then subsequently based on a list disable ones that plain users should not have access to.

How is that list generated? Is it static? We support a list of in external service config of repos to exclude.

**Comment by slimsag** [comment]
It is not static, but i don't know exactly how it is generated. They have
some script which generates it, I presume. That list + its generator
already exists (it isn't something they made just for Sourcegeaph, they
also use for other tools that don't support bitbucket ACLs)
