### ISSUE TITLE
dependencies api: Persist lockfile parsing result to database

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#31639]
Add a new set of tables that mirror `lsif_packages` and `lsif_references` table. We need a new set of tables since the structure is different (the existing tables link uploads together, where we need to link repositories together directly).

We should construct a unified view that pulls the repository dependency information from the LSIF tables, then supplement it with lockfiles when missing. This should be what we query from as a first step, then fall back to writing through to this database layer on-demand.

**Comment by mrnugget** [comment]
@efritz roughly, in ~5 bullet points, how and where would you implement this?

**Comment by efritz** [comment]
@mrnugget See PR 😋
