### ISSUE TITLE
New reference panel: hide panel when navigating away from BlobPage

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#31640]

**Comment by jjinnii** [comment]
@mrnugget Could you add some more information on this issue? What does navigating away refer to, and does this differ from the current ref panel behavior?

**Comment by mrnugget** [comment]
Sure! Here you go:

<img width="1147" alt="screenshot_2022-02-24_09 14 36@2x" src="https://user-images.githubusercontent.com/1185253/155488575-86a59210-3a0c-4ee5-b602-cbf51a2c00a8.png">
