### ISSUE TITLE
Code Insights: Non UI final tweaks around the cloud landing page

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#31650]
Desings [Figma](https://www.figma.com/file/EFgTP7gpdpQSEo1n4FUfsW/In-product-landing-page-WIP?node-id=1791%3A29077)

## Background

This is basically a follow up for the https://github.com/sourcegraph/sourcegraph/pull/31177

Things that are left from the cloud LP implementations at the moment.

- [x] Add promo video
- [x] Add gif (hero image) for the first section
- [x] Add pings
- [x] Make sure that pings from the in-product landing page and cloud landing page work independently
- [x] One more added by @joelkw : https://github.com/sourcegraph/sourcegraph/issues/31686
- [ ] Merge this issue PR and close this issue when code insights GA will happen.

**Comment by felixfbecker** [comment]
We have this issue in the iteration of size 3 and also https://github.com/sourcegraph/sourcegraph/issues/30166 of size 8, which this is said to close. It looks like they basically represent the same work, could we just keep this issue and remove the other from the milestone so we don't double-track the work?

Also, can this be closed given the checklist is fully checked?

**Comment by felixfbecker** [comment]
Going to unassign @unclejustin since he still has the limited access mode tickets to do and it seems all PRs so far were from @vovakulikov

**Comment by vovakulikov** [comment]
@felixfbecker I'm sorry about confusing with which issue closes other issues. I updated the checkbox list for this issue and moved the closes statement to the PR instead of this issue (that was weird I perhaps just messed up with this linking) Thanks for removing this "proxy" issue from the iteration board.

**Comment by felixfbecker** [comment]
Since all the work is done, as an exception for next iteration I'll just add the PR to the board, and we can close this issue. That way (merging) the PR counts as size 1, as opposed to these issues with size 3 + size 8.
