### ISSUE TITLE
insights: for charts with many lines, when hovering over a series in the legend, bring the entire line to the top of the z-index stack

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#31658]
Specific user feedback here: 

https://sourcegraph.slack.com/archives/C013FEJKFPX/p1645557745287229

For example, if you have the below insight and hover over version 1.12 on the side in the key legend of the graph, all bright green line points should come to the front. 
![image](https://user-images.githubusercontent.com/11967660/155206678-9532055c-f025-4453-a3ef-a9186d2e4865.png)

**Comment by vovakulikov** [comment]
@Joelkw nice call! @AlicjaSuska I want to bring your attention to this one. What do you think about making the line a little bit bold for the line-hover state? I think it also should help with visual recognition of the hovered line, curios about your thoughts on this

**Comment by AlicjaSuska** [comment]
@unclejustin as per our discussion yesterday let's only change the Z index for this issue and skip any visual changes as they will be addressed in the design for a separate project ([capture groups v.2](https://www.figma.com/file/YoMwiXPV7fSdfWJPmm7pMT/Capture-groups-v.2-%2329956?node-id=1115%3A18627)) that I'll be testing shortly. 

@vovakulikov thank you for raising the issue :)
