### ISSUE TITLE
[Design] Enhancements to share notebook modal

### ISSUE THREAD

**Issue by marisak** [sourcegraph/sourcegraph#31677]
There are two potential parts to this work: (A) Change the arrangement of items in the sharing modal as it currently exists; (B) Add the ability to embed individual blocks via a URL.

User flows: Edit notebook; Read notebook? 
Estimate: 1–5 
Reason for estimate: 
- If just (A), then a 1 or 2, since that would be a minimal change limited to visuals that shouldn't have effects outside of notebooks. There's potential tie-in with the notebooks header. 
- If (A) and (B), this may also have effects on the actions for each block. Feedback from the content marketing team should be requested. This raises the estimate to 3–5. 

Will revisit this description as needed. This issue may need to be split into two separate issues for (A) and (B).

**Comment by camdencheek** [comment]
Closing since notebooks have been deprioritized
