### ISSUE TITLE
[Design] Redesign file block display

### ISSUE THREAD

**Issue by marisak** [sourcegraph/sourcegraph#31675]
The focus of this issue is to polish the visuals of the file block. This issue is part of the "redesign add block to notebook experience" epic. Because of [#31929 Change action menu for blocks](https://app.zenhub.com/workspaces/search-product-design-616db3900ad0860010044670/issues/sourcegraph/sourcegraph/31729), the appearance of the file block will likely need to be updated. 
Currently, there are two different background colors used for the file block. The difference is especially noticeable on dark theme. 

User flows: Create notebook; Edit notebook; Read notebook
Estimate: 3
Reason for estimate: 
- Interaction changes are covered by [#31929 Change action menu for blocks](https://app.zenhub.com/workspaces/search-product-design-616db3900ad0860010044670/issues/sourcegraph/sourcegraph/31729)
- Visual changes will still be required but can be considered separately. 

Related issues: 
- [Reimagine how to add blocks to a notebook
](https://app.zenhub.com/workspaces/search-product-design-616db3900ad0860010044670/issues/sourcegraph/sourcegraph/31678)
- [Redesign search query block](https://app.zenhub.com/workspaces/search-product-design-616db3900ad0860010044670/issues/sourcegraph/sourcegraph/31679)
- [Change action menu for blocks](https://app.zenhub.com/workspaces/search-product-design-616db3900ad0860010044670/issues/sourcegraph/sourcegraph/31729)

**Comment by camdencheek** [comment]
Closing since notebooks have been deprioritized
