### ISSUE TITLE
insights: Update the dotcom landing page quote 

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#31686]
**This is the final approved quote from the customer** 

Make sure the quote text is: 

_As we’ve grown, so has the need to better track and communicate our progress and goals across the engineering team and broader company. With Code Insights, our data and migration tracking is accurate across our entire codebase, and our engineers and managers can shift out of manual spreadsheets and spend more time working on code._

And make sure it is attributed to (and handle the special characters in the name correctly): `Balázs Tóthfalussy, Engineering Manager`

**Comment by Joelkw** [comment]
@vovakulikov  yep, it's a completely new quote (we just had a placeholder, but this one comes from the source of truth email thread where they approved it).

**Comment by vovakulikov** [comment]
Closing this since this change has been done and reviewed in this PR https://github.com/sourcegraph/sourcegraph/pull/31704. Closing just to simplify code insights landing page issues pipeline.
