### ISSUE TITLE
[Design] Navigating between notebooks 

### ISSUE THREAD

**Issue by marisak** [sourcegraph/sourcegraph#31683]
Right now, there's no built-in way to navigate between notebooks. Currently, one could create a text block and add links to other relevant notebooks. Is that sufficient? Do we want to introduce a "related notebooks" section? "Playlists" or "folders," which also get into a question of organization? 

User flows: Create notebook; Read notebook 
Estimate: 5–13
Reason for estimate: 
- Because the solution we want to pursue is not defined, more design exploration is needed to figure out the design impacts of some of these proposals. 
- "Navigating between notebooks" and "organizing notebooks" are related, but probably separate questions

**Comment by camdencheek** [comment]
Closing since notebooks have been deprioritized
