### ISSUE TITLE
[Design] Incorporate document outline 

### ISSUE THREAD

**Issue by marisak** [sourcegraph/sourcegraph#31681]
Adding a table of contents or document outline to notebooks (similar to what's in [Google Docs](https://support.google.com/docs/answer/6367684?hl=en&co=GENIE.Platform%3DDesktop)) should make it easier to navigate within a notebook, or get a summary of the content at a glance. There are open questions around where the outline should be placed in the UI, and how it should behave on mobile. 

User flows: Read notebook 
Estimate: 5
Reason for estimate: 
- This work is partially in progress, though not finished by either design or engineering. 
- Mobile considerations increase scope of work 
- Also relates closely to the notebooks header

**Comment by camdencheek** [comment]
Closing since notebooks have been deprioritized
