### ISSUE TITLE
Dan's re-onboarding to Delivery

### ISSUE THREAD

**Issue by dan-mckean** [sourcegraph/sourcegraph#31696]
- [x] Review the board and get a feel for the stuff currently in flight (just for my awareness)
- [x] Understand what level of involvement I need to have in the new approach to releases (hoping none :sneaky: )
- [ ] Review (and maybe iterate on) the tracking issues we have for Q1
- [x] Book a meeting to revisit our Q1 plans
  - More to follow when I book it and share an agenda but the gist is to sanity check the plans for Q1, perhaps tentatively ID what would be next (Q2) and basically make sure you’re all happy and bought in to what we do in this Q.
  - **Update:** 
    - [Slack message](https://sourcegraph.slack.com/archives/C02VDNKBWDU/p1645619946175709)
    - [Delivery FY23 Q1/Q2 Roadmap Ideation](https://docs.google.com/document/d/1KaghOujg8hiJAoYd5i340hSRQweo0n83ZjnHAnt4rzA/edit#heading=h.fu0y94d8f3kd)
- [x] Finalize and share with you the results of some product gap analysis
  - For those who don’t know, CE and Sales record product gaps (think feature requests) in Salesforce
  - [Here’s a sneak peak](https://docs.google.com/spreadsheets/d/1cBS9wQr8H45hEu45h0Ttx_1Xy19j243LxlokUnB3DL4/edit#gid=1584477721) of what I’m working on.
  - It’s not likely much of that will be in Q1 as we get some time-sinks under control
- [ ] Review [RFC 551 WIP: Managed Instance Upgrade Automation](https://docs.google.com/document/d/1vZR75HsekwMpop_vKpQv4JLcQoucqtp8cTRx7fu_onM/edit#heading=h.trqab8y0kufp)
  - This seems like a given for Q1 to claw back time for the team
  - In particular help cement the scope and convert from an RFC into actionable plans we can progress
- [x] Review (again) [RFC XXX WIP: Updating Resource Estimator](https://docs.google.com/document/d/1GYOslxPz4wIueSPXAJUAqC6a9aUMs4BHgKz8x64C6Zk/edit#heading=h.trqab8y0kufp)
  - This is tentatively included in the roadmap for Q1. But will be interested in your thoughts (in the roadmap call mentioned in no.4) in terms of ROI in time saved.
- [ ] Helm
  - [x] Chase down progress that contacted customers made with Helm (and any feedback)
  - [ ] Judge whether we have enough to green-light official support
  - [ ] If needed start the beta back up
  - [ ] Establish a todo-list with Crystal on what we need to do to formalize our support for Helm

**Comment by virginiaulrich** [comment]
Agreed in 2022-03-28 planning session this can be closed
