### ISSUE TITLE
Revision searches with a prefixed at sign breaks search result links

### ISSUE THREAD

**Issue by soyarsauce** [sourcegraph/sourcegraph#31692]
Hiya
I've been loving this feature:
https://about.sourcegraph.com/blog/search-multiple-revisions/
The result links work fine when using the vscode extension, but not in sg web;
I presume because of the tag being prefixed with @ tripping up the url parsing, more details below:

- **Sourcegraph version:** 3.34.2, also Sourcegraph.com
- **Platform information:** Chrome 98.0.4758.109 + Firefox 97.0.1

#### Steps to reproduce:

1. Do a multi revision search OR single revision search with `@` in revision (tag in this instance) name
-  [repo:^github\.com/emotion-js/emotion$@main:@emotion/core@11.0.0 file:^package.json$](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/emotion-js/emotion%24%40main:%40emotion/core%4011.0.0+file:%5Epackage.json%24&patternType=literal)
- [repo:^github\.com/emotion-js/emotion$ rev:@emotion/core@11.0.0 file:^package.json$](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/emotion-js/emotion%24+rev:%40emotion/core%4011.0.0+file:%5Epackage.json%24&patternType=literal)
2. Click `package.json` result

#### Expected behavior:
See page/file view for `package.json` file

#### Actual behavior:
Hit a 404 page

**Comment by benvenker** [comment]
Thanks for reporting @soyarsauce, I've moved this into the Search Product team's backlog for now, so we'll take a look at this in our next iteration. Thanks for reporting!

**Comment by soyarsauce** [comment]
Hey @benvenker thanks for the triage - is there an update / timeframe to when the "next iteration" occurs? 🙏

**Comment by benvenker** [comment]
@novoselrok did you ever get a chance to take a look at this one?
