### ISSUE TITLE
user invites on-prem: Add site or user configuration option to turn off user invitations on on-prem

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#31703]
Part of https://github.com/sourcegraph/sourcegraph/issues/31214

See https://sourcegraph.slack.com/archives/C01LZKLRF0C/p1645585709938119?thread_ts=1645565266.889989&cid=C01LZKLRF0C for more context

**Comment by slimsag** [comment]
should be really easy to do. We can do add this to the user settings schema https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/schema/settings.schema.json

Once added there, an admin can turn that on/off for all users via the global user settings page. This also let's individual users configure it which seems nice. Also, it's easier to access in the frontend code if we do it there.
