### ISSUE TITLE
user invites: Detect if server has emails configured

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#31702]
Part of https://github.com/sourcegraph/sourcegraph/issues/31214

We need a way to find out if SMTP/email sending is reasonably configured so that we can conditionally hide the invites features if that is the case.

Something simple like "any config for email is set" should suffice.

**Comment by slimsag** [comment]
https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+window.context.EmailEnabled&patternType=literal

![](https://media4.giphy.com/media/5z0cCCGooBQUtejM4v/giphy.gif?cid=ecf05e47jaurxx1towft47g256y02hkefszhedc3euj8riut&rid=giphy.gif&ct=g)

(I don't know why we keep it in the window context lol.)

**Comment by philipp-spiess** [comment]
Duh 😓 Ty
