### ISSUE TITLE
github code intelligence doesn't show on hover or click

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#31716]
Edit:
It's clear that this is actually GH intelligence, not Sourcegraph. So the issue I suppose is that Sourcegraph intelligence isn't getting triggered?

```
https://github.com/sourcegraph/sourcegraph/find-references?blob_path=cmd/frontend/internal/app/ui/router.go&code_nav_context=DIFF_VIEW&col=31&language=Go&q=Handler&ref=rn/enable-embed-on-private-instances&row=279
```

Our code intel popover on GitHub isn't working for me at the moment. Network calls are being made - interestingly they are returning `text/html` which was a bit surprising, is that intentional? The calls return results, so this seems like a problem in the extension.

I'm on this PR https://github.com/sourcegraph/sourcegraph/pull/31714/files, any symbol has the same behavior.

I'm running bext 22.2.11.1553 on Firefox 97.0

https://user-images.githubusercontent.com/5090588/155351244-fca7accb-88d8-4c29-a7df-84892574e271.mp4

**Comment by taras-yemets** [comment]
Hey @coury-clark!

Thanks for reporting!

Just tried on the same extension and browser versions on my machine and it seems to work, although it takes more time than usual to load code intel.

https://user-images.githubusercontent.com/25318659/155360458-1f4c7ce7-8acc-49ea-934c-7ec13612f055.mp4

I'll revisit this issue later and update you on its status.
