### ISSUE TITLE
Browser Extension: Unable to update Sourcegraph URL

### ISSUE THREAD

**Issue by KattMingMing** [sourcegraph/sourcegraph#3172]
The browser extension options menu freezes when updating the Sourcegraph URL input box.

**Reproduction Steps**
1. Click Sourcegraph icon
2. Delete `https://sourcegraph.com`
3. Start typing new URL
4. Notice the input freezes and new characters cannot be entered.

**Expected behavior**
The URL to be updated correctly

**Comment by felixfbecker** [comment]
I cannot repro. What version of ext and browser are you on?

**Comment by lguychard** [comment]
Closing as we have no repro.
