### ISSUE TITLE
Update the pipeline generator to randomize adding stateless agents to build

### ISSUE THREAD

**Issue by davejrt** [sourcegraph/sourcegraph#31724]
@bobheadxi mentioned on a call that we could randomize the way buildkite jobs get assigned to different agent types between our stateful and stateless agents. 

this would be a nice way to canary test the stateless agents on `sourcegraph/sourcegraph` without cutting over 100% in one go.

**Comment by bobheadxi** [comment]
Dashboard: https://sourcegraph.grafana.net/d/eaFPBoP7z/buildkite-stateless-agent-rollout?orgId=1
