### ISSUE TITLE
release: improve visibility of release cut

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#31737]
When the release is cut, there is no obvious indication to other teammates. This means people have to ask "is it safe to merge".

A few thoughts:
1. Add a new announcement to the slack announcer
2. And / or cut against a specific revision, such that people don't need to be worried about it being "safe" to merge

**Comment by bobheadxi** [comment]
Let's go with a Slack annoouncement, this should be easy to add (there actually used to be one, before we worked to make the cut period shorter and more invisible)
