### ISSUE TITLE
release: check if `main` is ahead of remote

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#31734]
The release tool currently has a check if the local copy of `main` is [behind](https://github.com/sourcegraph/sourcegraph/blob/main/dev/release/src/util.ts#L95-L99) origin. To prevent any issues with unintended commits to `main` we should also check that the local `main` is not ahead of origin.

**Comment by marsblkm** [comment]
Hi I have just initiated a pr for this.

**Comment by bobheadxi** [comment]
Closed by https://github.com/sourcegraph/sourcegraph/pull/35360
