### ISSUE TITLE
release: add helpful `sg` tool commands to release tool output

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#31740]
Some of the release tool commands generate builds, for example:
`release:create-candidate`
`yarn run release release:finalize`

We now have a useful tool in `sg` to monitor builds and send notifications. I think we should output these commands in the help text of the release tool, for example

`N=1; yarn release release:create-candidate $N`
would output
`sg ci status -branch=v3.37.0-rc.1 --wait`

**Comment by bobheadxi** [comment]
Definition of done: find (up to) 3 places to recommend helpful sg commands

**Comment by davejrt** [comment]
Closed by https://github.com/sourcegraph/sourcegraph/pull/39575
