### ISSUE TITLE
proposal: standardize on Jaeger+Prometheus+Grafana in all deployments

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#3175]
## State of tracing+metrics today

Note: LightStep is proprietary / paid cloud service tracing, Jaeger is open-source tracing.

- Sourcegraph.com (k8s cluster) uses Lightstep (not Jaeger) + Prometheus + Grafana
- sourcegraph.sgdev.org (Sourcegraph Server) uses Lightstep (not Jaeger) + no other metrics
- _Very rarely_ do k8s customers run Jaeger + Prometheus + Grafana, as it requires extra configuration & work to set up on the users part.
- Almost all sourcegraph/server users do not have any form of tracing of metrics systems.

## How do we handle customer-reported performance issues?

One can imagine our response flow today looking roughly like:

1. Can we reproduce the issue elsewhere? In bad cases the answer is no.
2. Can the customer provide us with a sample trace / some metrics we are interested in? No, they don't have these set up.
3. Request the customer set up Jaeger/Prometheus.
4. If we've actually gotten to this point, customer provides us with some jaeger trace or prometheus query result.
5. Our devs only use Lightstep, so there is uncertainty around using Jaeger ("How do I set it up? How does it behave in X situation?").

## The problem

I would estimate that:

- 95% of customer deployments (i.e. excluding large customers) have no tracing/metrics system in place.
- 95% of our engineering team does not know how to use Jaeger with Sourcegraph, or have never used Jaeger at all.
- 95% of our customers would not be interested in signing a Lightstep deal just in order to let us debug our product.

This is all to say: We are not setting up our small customers for success when it comes to performance issues today.

# Proposed direction

The proposal here is to formally adopt Jaeger+Prometheus+Grafana (& our dashboards) as much as possible in all deployment environments, so we have a standard way of debugging perf issues & getting sourcegraph metrics from our customers.

This only proposes the direction we should move in, actually prioritizing this work relative to other things is a separate task (we wouldn't do all of this at once):

1. **Make Sourcegraph.com and sourcegraph.sgdev.org use Jaeger instead of Lightstep, as we should familiarize ourselves with using Jaeger since that is what our customers will be using.**
    - If there is something Lightstep does particularly well, we can switch over to it temporarily while performing that action OR if we need to do this regularly we can write a tracer that goes to both Jaeger & Lightstep.
2. **Strongly advise all deploy-sourcegraph clusters deploy Jaeger, Prometheus, and Grafana (with our custom dashboards loaded).**
    - If you are against this as a Sourcegraph admin, you can of course opt-out. This means our ability to debug your perf issues is more limited (we'll still try our best, of course).
    - We would still indicate that Jaeger, Prometheus, and Grafana are not core parts of Sourcegraph and if you run into issues with them we may not be best suited to help as we are just users of these services same as you.
3. **Run Jaeger+Prometheus+Grafana in our dev instances.** (they are very useful when debugging perf issues, so it makes sense to do so).
4. **Investigate running Jaeger+Prometheus+Grafana in sourcegraph/server deployments**
    - This is more tricky, for example because these may use many resources and sourcegraph/server is targeted towards quickly trying sourcegraph. Same issue applies to [enabling indexed search by default](https://github.com/sourcegraph/sourcegraph/issues/2176) there. We would investigate this, but the outcome may just be "we shouldn't do it [...] and users running into perf issues on server should upgrade to a cluster deployment"

Leave a comment or thumbs up/down emoji to cast a vote.

**Comment by chrismwendt** [comment]
:+1: I'm often lost in Prometheus syntax, so a built-in Grafana dashboard would be convenient and informative.

Can you list what we'd gain/lose by moving from LightStep to Jaeger? Sometimes I look at the distribution of latencies of operations in the go-langserver to find low operations. Does Jaeger have that?

**Comment by slimsag** [comment]
> Can you list what we'd gain/lose by moving from LightStep to Jaeger?

Frankly, I don't know aside from maybe dashboards that Lightstep provides. I suspect Lightstep may be better at gathering traces as well, since it is fully managed and they adjust it to our workload instead of us having to do that.

Part of the problem here is just that, though: nobody on our team except a select few really use Jaeger so when it comes to debugging customer deployment perf issues we're in the dark unless you are one of those select few :)

> Sometimes I look at the distribution of latencies of operations in the go-langserver to find low operations. Does Jaeger have that?

You can get an idea of what it has in the UI here: https://github.com/jaegertracing/jaeger-ui#jaeger-ui

> I'm often lost in Prometheus syntax, so a built-in Grafana dashboard would be convenient and informative.

We used to have dashboards at https://grafana.sgdev.org/?orgId=1 but they are gone now I guess. Dunno why.

**Comment by felixfbecker** [comment]
> 95% of our engineering team does not know how to use Jaeger with Sourcegraph, or have never used Jaeger at all.

We did a switch to Jaeger for a short time twice. The amount of teammates that were around then is >5%.
Jaeger is also not very different from Lightstep (not surprising given it's both OpenTracing).
So I wonder how accurate this number is, and also how many teammates are familiar with LightStep.

I do like the idea of sharing our Grafana dashboards.

**Comment by slimsag** [comment]
@felixfbecker Yep, that is absolutely true. It's an estimate, so definitely not accurate. But I am also considering things like:

- If I asked you to set up Jaeger on a Sourcegraph cluster today, would you be able to do so with the same level of confidence as setting up Lightstep? (hint: I tried this yesterday and couldn't get it to work, our instructions have been broken for a while)
- If you had to request a jaeger trace from a customer, would you feel confident in your ability to direct that customer on how to do so?

etc

**Comment by slimsag** [comment]
i.e. the part you quoted is not just about making use of Jaeger as a user, but also operating it as an admin

**Comment by tsenart** [comment]
This proposal makes sense and I think we should go deeper into designing a standard set of dashboards  and work back from that to the Prometheus exporters we need.

For instance, @ggilmore was recently talking about a customer issue he had no way of debugging. I read you and @beyang had a guess that it could be Postgres connection limits being exhausted. A Postgres dashboard that includes a visualisation of this resource usage over time would aid in validating that hypothesis.

**Comment by tsenart** [comment]
Some more thoughts:

1. We should consider adapting our Definition of Done for a feature to include monitoring (including Grafana dashboards).

1. On-boarding documentation for new engineers on how to use Grafana an Jaeger when on-call would be beneficial.

**Comment by beyang** [comment]
> We used to have dashboards at https://grafana.sgdev.org/?orgId=1 but they are gone now I guess. Dunno why.

@slimsag We still have Grafana dashboards: https://grafana.sgdev.org/dashboards. The most commonly useful ones are the ones prefixed with "dc:" ([1](https://grafana.sgdev.org/d/000000042/dc-frontend?orgId=1), [2](https://grafana.sgdev.org/d/000000045/dc-resources?orgId=1)). The gitserver one appears to be down, however, so there is some maintenance debt here.

I'd recommend splitting this issue into separate ones (and linking to those from here if you like). Recommending Jaeger as the default tracing system for on-prem Sourcegraph deployments SGTM, but we should stop short of making it an official part of the Sourcegraph distribution IMO. In my experience, there is significant variation in customer environments (some have an existing tracing instance, some may not want to share a tracing instance but want to use the same tracing system as is used elsewhere in the company, some may want to allocate a lot of resources to the tracing instance, etc.). That means the most efficient division of labor is for us to recommend / provide an example of what we do with our own instance, but ultimately leave it in the hands of the customer to figure out how to deploy into their internal environment.

**Comment by slimsag** [comment]
> We still have Grafana dashboards

Ack; I noticed this yesterday when @ggilmore pointed it out to me. I was just confused.

> I'd recommend splitting this issue into separate ones (and linking to those from here if you like). 

This issue is just for figuring out the direction we want to go in. The actual work that we want to do (both short and long term) will be tracked in other issues as we figure out what we want to do. I agree the consensus is "standard grafana dashboards" -- but we already have those (someone should propose exactly what we want to improve there, aside from just fixing the gitserver dashboard).

> Recommending Jaeger as the default tracing system for on-prem Sourcegraph deployments SGTM, but we should stop short of making it an official part of the Sourcegraph distribution IMO. In my experience, there is significant variation in customer environments (some have an existing tracing instance, some may not want to share a tracing instance but want to use the same tracing system as is used elsewhere in the company, some may want to allocate a lot of resources to the tracing instance, etc.). That means the most efficient division of labor is for us to recommend / provide an example of what we do with our own instance, but ultimately leave it in the hands of the customer to figure out how to deploy into their internal environment.

I agree. In specific, what I am thinking of is something like this:

> Sourcegraph uses OpenTracing to debug issues and performance problems. When you run into issues with Sourcegraph, traces give us a great amount of insight into how the system was operating when the issue occurred.
>
> One such implementation of OpenTracing is Jaeger, which we will guide you through installing now. If you prefer not running a tracing system, or using your own, you may skip this step (but this means our ability to debug issues and performance problems may be hindered).

What do you think of that?

**Comment by tsenart** [comment]
As informed by a recent customer issue, we should ship a standard set of alerts together with the dashboards. One to keep in mind: Disk space utilization %

**Comment by slimsag** [comment]
Filed https://github.com/sourcegraph/sourcegraph/issues/3301 for discussing logging in specific.

**Comment by slimsag** [comment]
deploy-sourcegraph-docker contains standardized Jaeger + Grafana + Prometheus metrics.

I've filed an issue for us to upstream them to deploy-sourcegraph so that other Kubernetes deployments can benefit from the improvements made there: https://github.com/sourcegraph/sourcegraph/issues/3410

The consensus here seems to be that moving forward with this proposal is a good idea. The devil is in the details, as always, but we can discuss those details when we start working on this further in #3410.

Given this consensus, I'll close this issue. If anyone disagrees, please reopen so we can discuss further.
