### ISSUE TITLE
release: improve process for populating upgrade guides

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#31755]
There is currently a step in the release [tracking issue](https://github.com/sourcegraph/sourcegraph/issues/30051) that leads to [this PR](https://github.com/sourcegraph/sourcegraph/pull/31586) that specifies to `Update the upgrade guides in` with no other context or instructions. It turns out these upgrade guides are information we can give to customers before they update.

It makes no sense that a release captain should be responsible for filling this out. Not only is the captain unlikely to have the context required to fill it out, this should be updated and reviewed *prior* to the release cut.

So this issue is to improve this process:
1. Clarify the copy on the PR template that this is something that may not have any contents, and otherwise comes from any teams making significant updates in the release
2. Otherwise, introduce a process such that this can just be part of the release cut, similar to the changelog. This file should generated after the previous release, and updated as necessary with contents during the month, and simply cut on release cut day.

**Comment by bobheadxi** [comment]
+1 the upgrade guides should follow the same conventions as changelog (`Unreleased` gets promoted to a fixed version etc)
