### ISSUE TITLE
user invites on-prem: design improvements for admin communication

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#31780]
We will need to update the frontend designs for on-prem user invites to make it clear to admins:

* That we've added user-invites on-prem, and how they work.
* How to disable them if they wish to.
* That inviting someone merely sends them a link as if you'd done it yourself, there is no special access granted.
* That we find collaborators via Git repository history, so if you see someone unexpected as a suggestion that's where it came from. Not a security concern.

May slip into G&I iteration 4.

**Comment by philipp-spiess** [comment]
> That we've added user-invites on-prem, and how they work.

Do we have an existing pattern (i.e like a "whats new section") that we can use to communicate these changes? This sounds like something that hasn't come up the first time.
