### ISSUE TITLE
Mount files when starting a remote execution with src-cli

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#31792]

**Comment by malomarrec** [comment]
I'm moving this to triage, suggest moving this to P2 and starting design work ASAP.

**Comment by BolajiOlajide** [comment]
Estimate 3-4 days! 
Might be dependent on #31791

**Comment by Piszmog** [comment]
> Estimate 3-4 days! Might be dependent on #31791

I agree. I think there will be some dependency between the two. #31791 will introduce storing the files in some sort of store, and this Issue will probably use that store to run the files server-side.

**Comment by malomarrec** [comment]
Curious to see where that went: does the issue depend on #31791 ?

**Comment by Piszmog** [comment]
#31791 depends on this Issue. This Issue introduces the functionality or storing the retrieving files that are used in remote execution. 

Hopefully, this Issue will make #31791 less work since a lot of foundation is being laid here.

**Comment by Piszmog** [comment]
All PRs are ready for review (over half are approved already). Hopefully, close right after 4.0.
