### ISSUE TITLE
Display mounted files as read-only in UI

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#31791]
Design ticket https://github.com/sourcegraph/sourcegraph/issues/37192

**Comment by BolajiOlajide** [comment]
@adeola-ak & I are interested in this. Wondering if Randell's done with the mounting of files implementation before we start this.

**Comment by malomarrec** [comment]
@danielmarquespt

**Comment by danielmarquespt** [comment]
Created the issue https://github.com/sourcegraph/sourcegraph/issues/37192

This is a good candidate for the next design session. I'll add to the agenda

**Comment by malomarrec** [comment]
I'm moving this to P2 as the result of this thread.

**Comment by malomarrec** [comment]
P2
