### ISSUE TITLE
Fail gracefully when backwards compatibility is not available 

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#31808]
Feature Request: For versions 3.31.2 and prior, we should communicate to users that searches are not working due to backwards compatibility issues. It is a known problem from issue #31017 that we users cannot perform searches prior to 3.31.2.

**Comment by jjinnii** [comment]
@abeatrix Are we able to tell upon authentication what version a private instance user is using? The ideal flow is when a user successfully authenticates their private instance account, we could show a VS Code native notification, communicating that key components of the extension will not work for their Sourcegraph version.

**Comment by abeatrix** [comment]
@jjinnii Yes we can! I will work on this and show you a demo next week

**Comment by jjinnii** [comment]
Thanks @abeatrix ! Looks great. Couple suggestions: 

* Your Sourcegraph instance version is not "fully" compatible with "the" Sourcegraph extension.
  * Because the extension still loads, it's just that certain features aren't supported 
* Can we add a "Learn more about support for your Sourcegraph instance" and link out to our [troubleshooting docs](https://docs.sourcegraph.com/admin/how-to/troubleshoot-sg-extension#unsupported-features-by-sourcegraph-version)?

**Comment by abeatrix** [comment]
@jjinnii Thanks! 

Updated to: Your Sourcegraph instance version is not fully compatible with the Sourcegraph extension. Please ask your site admin to upgrade the Sourcegraph instance to 3.32.0 or above for full compatibility. Visit our [troubleshooting docs](https://docs.sourcegraph.com/admin/how-to/troubleshoot-sg-extension#unsupported-features-by-sourcegraph-version) to learn more about support for your Sourcegraph instance.
![image](https://user-images.githubusercontent.com/68532117/159363013-ee5d5a47-f4dc-4850-ae80-9e04dad8b65a.png)
![Screen Shot 2022-03-21 at 2 00 14 PM](https://user-images.githubusercontent.com/68532117/159363031-bf9647c7-d843-4997-b633-aa43086a6012.png)
![Screen Shot 2022-03-21 at 2 00 16 PM](https://user-images.githubusercontent.com/68532117/159363048-acf67ab6-c0bc-4fbb-9001-fa0a57b6beb3.png)

**Comment by jjinnii** [comment]
@abeatrix Thanks so much! Sorry, just to trim down the word count, what do you think about:

"Your Sourcegraph instance version is not fully compatible with the Sourcegraph extension. Please ask your site admin to upgrade to version 3.32.0 or above. Read more about version support in our troubleshooting docs."

**Comment by abeatrix** [comment]
@jjinnii I agree that the message is too long! I have updated it to what you have suggested:
![Screen Shot 2022-03-22 at 10 33 07 AM](https://user-images.githubusercontent.com/68532117/159541049-911779ad-1a66-4da6-aae2-12e073713a64.png)

![image](https://user-images.githubusercontent.com/68532117/159541094-6c1389fd-e337-46c0-953b-09f64de46e6a.png)

**Comment by jjinnii** [comment]
Thanks @abeatrix!
