### ISSUE TITLE
Improve authentication process for private instance users 

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#31805]
TBA

**Comment by ryankscott** [comment]
Have we looked into or thought about OAuth here?

**Comment by jjinnii** [comment]
Oops this is apparently a duplicate issue that I created of[ this issue](https://github.com/sourcegraph/sourcegraph/issues/31804). I don't think OAuth is necessary for the specific UX improvement that this issue was intended to tackle, but please take a look at the other issue + designs there and lmk if you want to discuss on OAuth further! @ryankscott
