### ISSUE TITLE
Switch to 64-bit ints for pending permissions

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#31810]
We've been [concerned in the past](https://github.com/sourcegraph/sourcegraph/blob/7148009913d77239bb24e79274682cc1e0866c32/enterprise/internal/database/perms_store.go#L655-L662) about exceeding the limit of the current `integer` primary key column for `user_pending_permissions`.

Recently, we've seen a customer [hit this issue](https://github.com/sourcegraph/customer/issues/712).

For this reason, we should switch to a 64-bit, `bigint` ids for pending permissions.

Due to deployments rolling out to services at different times we'd ideally need to make this a multi release process where we introduce the new columns and have old and new code paths. However, given that pending permissions are only there as a mechanism to speed up permissions syncing when new users are added we can probably avoid complexity by simply clearing out data from these tables as part of the migration. This removes the risk of integer overflows where old code is dealing in `ints` but we've already migrated to `bigint` in the database. 

What we actually need to do:
 
* Truncate `user_pending_permissions` and `repo_pending_permissions`
* Reset the `user_pending_permissions_id_seq` sequence
* Migrate the `id` field from `integer` to `bigint` on `user_pending_permissions`
* Migrate the `user_ids_int` column in `repo_pending_permissions`
* Switch `user_pending_permissions_id_seq` to `bigint`
* Switch away from the `roaring` package to a package that support set operations on `int64`. `roaring64` is not an option due to poor performance. The package may need to support order guarantee, see this [comment](https://github.com/sourcegraph/sourcegraph/issues/31810#issuecomment-1058881832)
* We'll need to make this switch wherever we are dealing with integers that originate from the `id` field of `user_pending_permissions`
* We should *NOT* change type of fields that reference other primary keys, for example the [field](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@73448297a71f52e3ab7493e5830cc0034319bf53/-/blob/internal/authz/perms.go?L149) on `RepoPermissions`

**Comment by ryanslade** [comment]
@unknwon What do you think of the above? Anything I've missed? I'm mostly concerned about exactly which instance the bitmaps in code we actually need to update since I think we should only worry about the one for pending permissions.

@dan-mckean @jplahn I think this should be fairly high priority and ideally ready to go out with out next release as it's already affecting at least one customer. For now I'm going to assign to our High Priority column.

**Comment by unknwon** [comment]
TIL roaring64, should have used that in the beginning...

>I'm mostly concerned about exactly which instance the bitmaps in code we actually need to update since I think we should only worry about the one for pending permissions.

If the [roaring](https://github.com/RoaringBitmap/roaring) and [roaring64](https://github.com/RoaringBitmap/roaring/tree/master/roaring64?rgh-link-date=2022-02-24T16%3A08%3A33Z) have similar performance, I'd suggest fully switching to roaring64 so we're being consistent? (would roaring64 increase memory usage significantly?)

**Comment by ryanslade** [comment]
I'm guessing that switching to`roaring64` will double the memory requirements, however the compression used may reduce this. I'll try and test this.

My concern with switching everything to 64-bit is that it makes the migration trickier since we'd need to, for example, also migrate columns such as `user_ids_ints` in `repo_permissions`.

It would be good to eventually migrate everything to 64-bit but for now maybe we can focus just on the problematic table?

**Comment by ryanslade** [comment]
Performance of adding ints and memory size appears to be pretty similar when adding uint32s, however when adding larger ints it appear significantly slower. I'll keep looking into this, for now this is what I'm doing to test:

https://gist.github.com/ryanslade/47ba9a04b82bcde9fcf532a49fc34543

**Comment by unknwon** [comment]
> My concern with switching everything to 64-bit is that it makes the migration trickier since we'd need to, for example, also migrate columns such as `user_ids_ints` in `repo_permissions`.

No I don't think so, isn't int64 a superset of int32?

**Comment by ryanslade** [comment]
Unfortunately I don't think we're going to be able to switch to `roaring64`. On larger numbers the performance drops considerably.

**Comment by ryanslade** [comment]
I don't think we need to use a `roaring` implementation at all. Any set datastructure that support 64-bit ints should be fine since we actually store everything in the database as int arrays. I think we only use roaring bitmaps for historical reasons, @unknwon is that correct?

I've updated the description at the top to mention this.

**Comment by unknwon** [comment]
> I don't think we need to use a `roaring` implementation at all. Any set datastructure that support 64-bit ints should be fine since we actually store everything in the database as int arrays. I think we only use roaring bitmaps for historical reasons, @unknwon is that correct?

I agree. Just wanna call out we do rely on the "uniquely sorted" property of roaring bitmap. Some operations in Postgres with intarray provides the same guarantee, but would be good to double check at all places.

**Comment by varsanojidan** [comment]
Hey @ryanslade , wondering what your opinion is on removing roaring altogether vs just removing it for the PendingPermissions functions. Im wondering because both Permissions and PendingPermissions utilize authz.RepositoryPermissions a object which contains a roaring.Bitmap field (UserIds). So I can either work around this and only remove the use of bitmaps for Pending permissions or remove bitmaps altogether from both Permissions and PendingPermissions (obviously being a larger change).

**Comment by ryanslade** [comment]
I'm happy to remove from all places but let's do that across multiple PRs to make it easier to review.

Let's focus on removing just from pending permissions for now and create an issue to remove from other places.
