### ISSUE TITLE
insights: Document codeinsights-db resources for the resource estimator

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#31829]
We should provide guidance on sizing `codeinsights-db` on the https://docs.sourcegraph.com/admin/install/resource_estimator resource estimator page. 

Related to #31738 – but this is for the codeinsights-db, not the codeintel-db .

**Comment by Joelkw** [comment]
I think this will be of added importance given this change about Cloud architecture/strategy: https://sourcegraph.slack.com/archives/C01RVEVPWLC/p1647454837409439

**Comment by leonore** [comment]
this looks like it might have been resolved in the latest resource estimator: https://github.com/sourcegraph/resource-estimator/pull/13

just confirming with delivery whether we can update the resource estimator script on docs.sourcegraph.com, as it hasn't been updated to the latest yet

**Comment by leonore** [comment]
closing as there have been recent efforts by the Delivery team to update the resource estimator / scaling information and this has been updated with information we gave them on codeinsights-db scaling:

https://docs.sourcegraph.com/admin/deploy/scale#codeinsights-db
