### ISSUE TITLE
Post Slack notifications of a PR being deployed in pre-prod or production (cloud). 

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#31839]
### Context 

A pull request merged on the `main` branch is going through the pre-prod environment and the cloud production environment by successive deployments. 

We want to enable developers to track the status of this process and to give visibility on when these changes were tested in pre-prod as well as when they were deployed. 

### Definition of done

1. As a Sourcegraph teammate, when my PR is deployed in either environment, I am pinged on Slack, so I know that my changes have been deployed. 
	- ⚠️ Whether it gets deployed directly or bundled with another PR being deployed does not change anything. It notifies in both cases.   
2. If a rollback occurs in any environment, I am notified as well. 
3. (optional) if a rollback fails and an incident is created, I am automatically invited to the resulting incident channel. 

### Outcome

- TBD

### Iterations

- https://github.com/sourcegraph/sourcegraph/pull/32459

### Resources

- [Miro Board](https://miro.com/app/board/uXjVOKqPSDM=/)
- [RFC 592](https://docs.google.com/document/d/13kVYJSoTWYgyeBFXeJnasF3WU7SHyOjhSNpp9yV_pvY/edit#)
- [RFC 586](https://docs.google.com/document/d/1x7Luv4YM5g3iGxtRcc8YUhf6LKky8P0MOFmbSryrzic/edit#)

**Comment by bobheadxi** [comment]
@jhchabran does this overlap with https://github.com/sourcegraph/sourcegraph/issues/32154?

**Comment by bobheadxi** [comment]
@jhchabran I've updated the iterations as https://github.com/sourcegraph/sourcegraph/pull/32459 seems to close both cases
