### ISSUE TITLE
Automate incident creation on specific pre-prod and cloud production deployment scenarios 

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#31854]
### Context 

With the ongoing effort to create a pre-prod and cloud production environment, and to wire it to the CD pipeline, we need to take immediate action on a few edge cases requiring manual intervention. 

Please see the [pre-prod frame](https://miro.com/app/board/uXjVOKqPSDM=/?moveToWidget=3458764519518414295&cot=14) and the [cloud production frame](https://miro.com/app/board/uXjVOKqPSDM=/?moveToWidget=3458764519518414649&cot=14) for a list of scenarios where creating an incident is needed.

### Definition of done

1. Given the list of scenarios mentioned in the two frames linked above, an incident is automatically created. 

### Outcome

- TBD

### Resources

- [Miro Board](https://miro.com/app/board/uXjVOKqPSDM=/)
- [RFC 592](https://docs.google.com/document/d/13kVYJSoTWYgyeBFXeJnasF3WU7SHyOjhSNpp9yV_pvY/edit#)
- [RFC 586](https://docs.google.com/document/d/1x7Luv4YM5g3iGxtRcc8YUhf6LKky8P0MOFmbSryrzic/edit#)

**Comment by jhchabran** [comment]
incidents.io does not have a public API at the moment. There may be a way to workaround this by going through ops-genie.

**Comment by bobheadxi** [comment]
This was rolled back in https://github.com/sourcegraph/deploy-sourcegraph-cloud/pull/16663

**Comment by bobheadxi** [comment]
Feedback from @daxmc99: 

> Can we disable automated incident creation? I didn’t see any RFC or handbook change regarding this… How can we disable this pending a wider review?
> [...]
> I suppose I have a built-in assumption that incidents are created by people but that also isn’t stated anywhere

For context, the background behind this addition is in linked boards and RFCs in the issue description, namely:

![image](https://user-images.githubusercontent.com/23356519/170787169-43dd90f4-abe4-4009-9fa1-c86918d86216.png)

**Comment by jhchabran** [comment]
As discussed over https://docs.google.com/document/d/13kVYJSoTWYgyeBFXeJnasF3WU7SHyOjhSNpp9yV_pvY/edit in the comments, we need to create alerts on ops-genie rather than creating incident.io incidents. 

We'll re-enable the reporting once that's done.
