### ISSUE TITLE
Update documentation for creating a StorageClass and using an overlay

### ISSUE THREAD

**Issue by kevinwojo** [sourcegraph/sourcegraph#31858]
Slack context: https://sourcegraph.slack.com/archives/C02E4HE42BX/p1645804202321439

# Problem

A customer is guided to create a storageclass following [the kubernetes installation documentation](https://docs.sourcegraph.com/admin/install/kubernetes/configure#amazon-web-services-aws).

When they run `overlay-generate.sh`, the storage class is not recognized and the customer receives errors.

**Comment by virginiaulrich** [comment]
Agreement in today's planning session is that since Helm is close to GA and this only comes up in deployment, no longer relevant to document so agreed to close
