### ISSUE TITLE
JetBrains: Form a prioritized feature list, and set the appetite for a v1

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#31861]

**Comment by vdavid** [comment]
Update: We're still working on this in the [product document](https://docs.google.com/document/d/1l18Gq1VFkjwE3iimeOLrl8evqwVwnuDb4fDfuTnh5LM/edit#).

**Comment by jjinnii** [comment]
Sorry for the delay on this. Here's a first pass at potential groupings of work based on user/business goals. Please note that these priorities aren't indicative of phases/releases - they're just my opinion on priorities. These groupings inform the consumable "chunks" of work that I'd like to tackle design and engineering on, not what constitutes a v1. (Almost everything here is technically considered a v1 based on RFC [528](https://docs.google.com/document/d/1aaEZTzst4nE_hJV5X-Ckq7rzHjcSZ68M8mRxQGtUjRw/edit))

@ryankscott @vdavid Would love your thoughts on the groupings of feature work and prioritization. The next step once we come to an agreement is to create issues to track these groupings of work, and I can start working on designs.


**P-0**
* Core search capabilities
  * Submit a search
  * Search auto-complete
* View list of results
    * View list of results across respository/projects
    * Preview results
      * Important to keep in mind how the plugin might behave if a user were to insert the modal as a panel in their workspace. How might we maintain or modify preview? 
* Ability to open read-only (non-indexed) version of a file at location of search result

**P-1**
  * Activation: How can we teach new users how to use Sourcegraph? 
    * Watch & Learn video
    * Links out to Sourcegraph and user docs
    * Checklist
    * Other onboarding concepts that feel more natural to JetBrains
* Authentication
  * Cloud users
  * Private instance users
* Sourcegraph advanced features
  * Synced search history
  * Save Searches
  * Code Monitors (not available on VS Code yet either)
  * Code Insights

**P-2**
* Acquisition
  * How can we promote Sourcegraph account creation at opportune moments in a user flow? 
  * How can we communicate the benefits of a Sourcegraph Cloud account?
* Retention/Referral
  * Ability to share link to search results 
  * Ability to navigate to editable location of local files 
  * Ability to provide feedback, troubleshoot, and file issues

**Comment by ryankscott** [comment]
@jjinnii I really like the content, thanks for this. I'd like to try split it a (slightly) different way using "jobs to be done" so that it's very customer orientated. 

**1. Existing Sourcegraph users with private code**
When I'm about to implement a new feature, I want to see if someone in my organization has done something similar, so that I can reuse the code they've written

Steps:
- Install plugin
- Authenticate with my instance
- Submit a search (with auto-complete)
- View list of results across my organizations repository/projects
- Preview results
- Open read-only (non-indexed) version of a file at location of search result

**2. Existing Sourcegraph users without private code**
When I'm using a library I'm unfamiliar with, I want to see how others in the public have used this so I can understand how to use it better

Steps:
- Install plugin
- Submit a search (with auto-complete)
- View list of results across public repository/projects
- Preview results
- Open read-only (non-indexed) version of a file at location of search result

**2. New to Sourcegraph users**
When I'm exploring code search with Sourcegraph for the first time, I want to understand how to use it effectively, so that I can get the most value out of it.

Steps:
- Watch & Learn video
- Read Sourcegraph user docs
- Complete checklist(?)
- Be introduced to on-boarding concepts that feel more natural to JetBrains
- Create an account so that you can search private code

This however, doesn't include the following which could be future milestones:
- Synced search history
- Save Searches
- Code Monitors (not available on VS Code yet either)
- Code Insights
- Retention/Referral
- Ability to share link to search results
- Ability to navigate to editable location of local files
- Ability to provide feedback, troubleshoot, and file issues

@vdavid  @jjinnii What do you think?

**Comment by jjinnii** [comment]
@ryankscott Love the idea of tying the scope to jobs to be done. Few thoughts:

- JTBD 2 "Existing Sourcegraph users without private code" is essentially what I had under P-0. It's a large chunk of work, but I think that's OK. Realistically, I think it'd be hard to segment both design and engineering any further - for example, how would I design for the search experience, not thinking ahead to how the results might be shown. 
- My take on prioritization (and this is purely based on how it makes sense for design, so feel free to chime in here): 
  1.  Existing Sourcegraph users without private code
  2.  Existing Sourcegraph users with private code (Working on Authentication. I would potentially argue that Sourcegraph advanced features may belong in this JTBD)
  3.  New Sourcegraph users (Onboarding, Marketing Sourcegraph Cloud)
- When you say future milestones, do you mean post v1? The list I had sent were my thoughts on v1 features - the JTBD is a useful method to prioritize and segment the work, but all intended for a v1.

**Comment by ryankscott** [comment]
> JTBD 2 "Existing Sourcegraph users without private code" is essentially what I had under P-0. It's a large chunk of work, but I think that's OK. Realistically, I think it'd be hard to segment both design and engineering any further - for example, how would I design for the search experience, not thinking ahead to how the results might be shown.

Agree, unfortunately for me this is the smallest user flow that provides value. 

> My take on prioritization (and this is purely based on how it makes sense for design, so feel free to chime in here):
    i. Existing Sourcegraph users without private code
    ii. Existing Sourcegraph users with private code (Working on Authentication. I would potentially argue that Sourcegraph advanced features may belong in this JTBD)
    iii. New Sourcegraph users (Onboarding, Marketing Sourcegraph Cloud)

Agree with that. However I wouldn't release until atleast ii. is complete. I suspect (not proven) that the JetBrains users are *more likely* using this with private code compared to VSCode. 

> When you say future milestones, do you mean post v1? The list I had sent were my thoughts on v1 features - the JTBD is a useful method to prioritize and segment the work, but all intended for a v1.

Unsure yet :) It depends on how long things take. Let's make that decision after we have an understanding of relative timeframes. At least splitting it this way means we can provide customer value after the first flow is complete.


@vdavid  one thing that sticks out to me as a risk is authentication and whether using user based access tokens will work for our enterprise customers. It'd be good to explore this with the JetBrains team if there's a convention here.

@jjinnii we should probably validate the above with customers.

**Comment by jjinnii** [comment]
@ryankscott Agreed that authentication is a must-have for v1, just from the customers we have expressed interest in the plugin already.

Question on how we make decisions on what features should be prioritized for v1- If we're talking only talking to customers for validation, I feel as if onboarding and promoting account creation will naturally be de-prioritized. JetBrains users wanting to use Sourcegraph for private code doesn't imply that onboarding or promoting Cloud creation is not important, just that our _existing_ customers won't see them as important. (As they likely already have accounts and have been using SG)

To your point, we can make these decisions after we have understanding of effort, just wanted to clarify on this point. 😄 I'll start exploring designs for the JTBD user flow next week (I'll create an issue to track design work).

**Comment by jjinnii** [comment]
Sorry suggestion based on my question above ^ Maybe after we work on the first and second user flows, it may be worth some usertesting.com testing to see how important onboarding may be?

**Comment by ryankscott** [comment]
> Question on how we make decisions on what features should be prioritized for v1- If we're talking only talking to customers for validation, I feel as if onboarding and promoting account creation will naturally be de-prioritized

Yep, good call out and we shouldn't over index on just existing customer feedback, we also need to talk / think about potential users. In the PD I tried to have user goals and business goals and an ideal solution would satisfy both of these. 

> JetBrains users wanting to use Sourcegraph for private code doesn't imply that onboarding or promoting Cloud creation is not important, just that our existing customers won't see them as important. (As they likely already have accounts and have been using SG)

That's why I tried to split the jobs based on if they're existing Sourcegraph customers or not. We always have CTAs for people to sign-up where it makes sense.

**Comment by vdavid** [comment]
Thanks for all the input and sorry for joining late. Responses to a few points:

> @jjinnii: Would love your thoughts on the groupings of feature work and prioritization.

I liked both the feature list and the JTBD approach. I understand we'll need some effort to discover and prioritize between customer vs. lead needs. I think I can add no value here, I think both of your approaches are great and validation is on the way, so this thread looks great to me!

> @jjinnii: insert the modal as a panel in their workspace. How might we maintain or modify preview?

This is an easy one: users can't change a modal to a panel. They can move panels around, and resize modals, but not dock them: modals and panels are different concepts in their UI.

> @ryankscott: I suspect (not proven) that the JetBrains users are more likely using this with private code compared to VSCode.

I share that suspicion. That said, I wouldn't discount the user base who uses these IDEs on public code. Would be nice to find some numbers on these.

> @ryankscott: "I wouldn't release until atleast ii. is complete." (where "i. Existing Sourcegraph users without private code" and "ii. Existing Sourcegraph users with private code")

I'd do this differently. I'd gradually deliver each small feature that we're done with, to maximize delivered value and get feedback early.
Why wouldn't you release until ii. is complete?

> @ryankscott: @vdavid one thing that sticks out to me as a risk is authentication and whether using user based access tokens will work for our enterprise customers. It'd be good to explore this with the JetBrains team if there's a convention here.

It shouldn't be IDE-specific: whatever works in VS Code should work in JetBrains IDEs too. Does it work in VS Code? Is there a difference that I'm missing, or maybe misunderstanding this thought?

**Comment by ryankscott** [comment]
> I'd do this differently. I'd gradually deliver each small feature that we're done with, to maximize delivered value and get feedback early.
Why wouldn't you release until ii. is complete?

I think the team "release" is a little overloaded. By that I mean, do a full marketing effort and let people know. The reason why is that I wouldn't want us to get to a point where people try it, it doesn't work for their use case (E.g. searching public code) and never come back.

I'm happy to build and ship it incrementally and target specific customers on the way.

>It shouldn't be IDE-specific: whatever works in VS Code should work in JetBrains IDEs too. Does it work in VS Code? Is there a difference that I'm missing, or maybe misunderstanding this thought?

Yeah it does, it's just copying and pasting an access token. I just don't know if JetBrains provides some tooling for rolling out plugins or their IDEs that make this manual step cumbersome. However, the current approach works so let's go and see if it actually becomes a pain point.

**Comment by vdavid** [comment]
> Release

Ah, sure, then I fully agree!

> Auth

Yes, I think, worst-case we can fall back to the access token method; I'm pretty sure it'll work. And we can look for a better solution during the feature design phase.

**Comment by vdavid** [comment]
Update: We're finalizing this with Sara tomorrow or on Monday. Then we can close this issue.

**Comment by vdavid** [comment]
We have the feature list and milestones. :)
