### ISSUE TITLE
Extract and package a subset of the integration/e2e tests to run only on pre-prod. 

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#31869]
### Context 

A pull request merged on the `main` branch is going through the pre-prod environment and the cloud production environment by successive deployments. 

We want to run a set of e2e tests to ensure that the changes are not going to disrupt the cloud production environment. These tests should be minimalistic but still cover some essential paths taken by Sourcegraph Cloud users. 

### Definition of done

- Tests providing confidence that the pre-prod is running Sourcegraph in a usable state
  - [ ] A user can sign in and sign out. 
  - [ ] A very basic (very quick) search is returning some results
  - [ ] ~Test specific features specific to Cloud?~ deprioritized for now.
  - [ ] ... 
1. The integration/e2e tests are fast (<4m) 
1. They should not flake. 
1. They are instrumented in a Builkdite Analytics' specific test suite, with monitors in place to report flakiness immediately.  

### Outcome

- [x] #34278
- [ ] #34280
- [ ] Preprod application tests: search (waiting for team inputs)
- [x] Code Insights have been moved within the CI, see https://github.com/sourcegraph/sourcegraph/issues/34704

### Resources

- [Miro Board](https://miro.com/app/board/uXjVOKqPSDM=/)
- [RFC 592](https://docs.google.com/document/d/13kVYJSoTWYgyeBFXeJnasF3WU7SHyOjhSNpp9yV_pvY/edit#)
- [RFC 586](https://docs.google.com/document/d/1x7Luv4YM5g3iGxtRcc8YUhf6LKky8P0MOFmbSryrzic/edit#)

**Comment by jhchabran** [comment]
Challenging this ticket: what values are these tests providing compared to running them in CI in a classic way?

**Comment by bobheadxi** [comment]
@jhchabran this sounds super similar to https://github.com/sourcegraph/sourcegraph/issues/31859 , maybe they can just be merged? User sign-out, search, etc. is already covered in that issue
