### ISSUE TITLE
Suggest to change the timeout: instead of the count: when timeout is reached

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#31873]
#### Feedback

![image](https://user-images.githubusercontent.com/23640224/155761938-68d98d2f-0e15-4cee-a5a7-717bd182c46b.png)

In this example, the server appears to have timed out.  It doesn't matter how large of a number that is provided to `count:`, it will still always return ~75 results.  And, it always seems to take roughly 60s ([the default](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@fee1e1c8cf3c096a1feaf62f46d8df2639c7271b/-/blob/internal/search/limits/limits.go?L41:22)).  Perhaps the suggestion should be to change the default `timeout:` parameter instead?

#### Customer

[Customer](https://github.com/sourcegraph/accounts/issues/6716)

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket, please let us how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
