### ISSUE TITLE
npm auto indexing issue

### ISSUE THREAD

**Issue by andreeleuterio** [sourcegraph/sourcegraph#31885]
- **Sourcegraph version:** dogfood

I indexed a [repository](https://k8s.sgdev.org/github.com/andreeleuterio/src-cli-test/-/blob/package-lock.json?L15) that uses two npm packages. One is public and one is private. I created an npm code host in k8s and indexed the repository but the npm packages were not indexed and are not available for search in the instance.

~~I added the repository through the `dependecies` setting of the code host but it also didn't work. The code host doesn't seem to be saving the changes made.~~

#### Steps to reproduce:

1. Create and publish a [private npm package](https://docs.npmjs.com/creating-and-publishing-private-packages)
2. Create a repository that uses the package
3. Create an npm code host in dogfood with credentials from the npm user
4. Index the repository in dogfood
5. Can't find either of the expected packages: `is-even` and `andreeleuterio/andreresearch-scary-alerts`

cc @varungandhi-src

**Comment by andreeleuterio** [comment]
Update: I was able to index the repo by adding the name directly to the code host `dependencies` field. The package is visible in the instance. @varungandhi-src do you think it would have behaved the same if the indexing happened through picking up the repo on the LSIF upload?

**Comment by varungandhi-src** [comment]
> do you think it would have behaved the same if the indexing happened through picking up the repo on the LSIF upload

Yes, that matches my expectation.

**Comment by andreeleuterio** [comment]
Following up on https://github.com/sourcegraph/security-issues/issues/219
