### ISSUE TITLE
docs: Update kubectl port-forwards to use deploy/NAME

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#3190]
Came across this. Apparently kubectl now support `port-forward` on a `svc/` or a `deploy/`. We no longer need to use shell substitution on the output of `kubectl get po -l app=...`.

https://twitter.com/X1alejandro3x/status/1113144966967115776

cc people who may be interested in this @beyang @ggilmore

**Comment by leonore** [comment]
from a quick search this no longer seems relevant to our current docs, so closing. feel free to reopen if I'm wrong!

https://sourcegraph.sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph+file:doc+kubectl+get+po+-l&patternType=literal

https://sourcegraph.sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph+file:doc+kubectl+port-forward&patternType=literal
