### ISSUE TITLE
sgdev: Unable to load the gigarepo

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#31915]
After regenerating the gigarepo, sgdev can't load the homepage:

- ✅ Loads https://k8s.sgdev.org/gigarepo@e2e0a3b436e8c91ea49d9749f53a853be7053882 (this commit is ~10K commits from the initial commit, so very early in the gigarepo git history considering there are 3.7M commits total)
- ❌ Times out https://k8s.sgdev.org/gigarepo

Here's what the Cloudflare error looks like:

![image](https://user-images.githubusercontent.com/1387653/155896659-5a36e2aa-a369-47ac-aeb7-6e1bc6c203d4.png)

From [Slack](https://sourcegraph.slack.com/archives/C023ELQLV7F/p1645989679551379?thread_ts=1645458918.861179&cid=C023ELQLV7F).

**Comment by chrismwendt** [comment]
I discovered and fixed another bug in git-combine https://github.com/sourcegraph/sourcegraph/pull/32038 and added the megarepo to sgdev, but it can't load the megarepo either.

Any tips on debugging this? I checked the gitserver logs and saw a flood of messages, I could try narrowing that down further.

**Comment by keegancsmith** [comment]
If I am not mistaken this is resolved.
