### ISSUE TITLE
Extension API context evaluation/parsing significantly slows down switching tabs on GitHub

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#3192]
To reproduce:
- Open a PR on GitHub, go to the files tab and make sure the code views/extensions get initialised (get a hover).
- Now switch the tab back to "discussion", or to "issues", something that removes the code view again.
- This switching is significantly delayed compared to without the browser extension running, indicating the JavaScript main thread is blocked on something CPU intensive.
- Switching back and forth now exhibits the same behaviour

Profiling reveals that most time is spent parsing context expressions:

![image](https://user-images.githubusercontent.com/10532611/55477670-f7054680-5619-11e9-99e2-d6e54993ee76.png)

![image](https://user-images.githubusercontent.com/10532611/55477694-03899f00-561a-11e9-8786-494dda14f7ca.png)

Potential solutions:
- Can we optimise the evaluation process? E.g. reduce the amount of things that need to be recomputed, don't recompile expressions on new code views but just reevaluate them
- Can we run this CPU-intensive work in the background script / extension host instead?
- Can we do away with context expression parsing completely?

I found one TODO in this file, could this help? https://sourcegraph.com/github.com/sourcegraph/sourcegraph@d5467869681e187eb19199b2848aede9598b61f1/-/blob/shared/src/api/client/services/contribution.ts#L127:1

cc @sqs
 
Profile:
[Browser Extension ext API slowdown profile.json.zip](https://github.com/sourcegraph/sourcegraph/files/3038518/Browser.Extension.ext.API.slowdown.profile.json.zip)

**Comment by felixfbecker** [comment]
The main offender here is clearly the parsing (not the evaluation):

![image](https://user-images.githubusercontent.com/10532611/55478907-25385580-561d-11e9-9067-c298e92b7afc.png)

Hottest code paths:
- `evaluateContributions()` -> [`evaluateTemplate()`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@d5467869681e187eb19199b2848aede9598b61f1/-/blob/shared/src/api/client/context/expr/evaluator.ts#L27-29) -> `parse()` 38.1% 226ms
- `filterContributions()` -> `contextFilter()` -> [`evaluate()`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@d5467869681e187eb19199b2848aede9598b61f1/-/blob/shared/src/api/client/context/expr/evaluator.ts#L17-19) -> `parse()` 27.6% 164ms

These two functions always instantiate a new parser and parse the expression again. They never reuse the parser, nor reuse the compiled expression. It looks like changing this to reuse the compiled expressions would eliminate this perf problem.

**Comment by sqs** [comment]
For removing them entirely, you would need to propose an alternative. I can’t think of any viable alternatives. It seems like there is low hanging fruit to make it faster, though.
