### ISSUE TITLE
Update private repository sync banners in browser extension settings

### ISSUE THREAD

**Issue by taras-yemets** [sourcegraph/sourcegraph#31920]
Follow up on [issues/3066](https://github.com/sourcegraph/sourcegraph/issues/3066).

Update private repository sync banners for both on-prem and cloud users.
See details in PR #31690 discussion.

**Comment by taras-yemets** [comment]
@ryankscott @jjinnii 

PR https://github.com/sourcegraph/sourcegraph/pull/31690 suggested updating instructions for signed-in users on how to sync private repositories with Sourcegraph cloud to get code intel and other browser extension features (screenshot 3 of [this comment](https://github.com/sourcegraph/sourcegraph/pull/31690#issuecomment-1050921974)).
Those changes were excluded from that PR as it was decided that these use-cases need more thinking.

I suggest leaving the text for Sourcegraph Cloud instance as described in case 3 of the referenced comment. For self-hosted instances, we can add text like this
![Screenshot from 2022-03-18 12-42-35](https://user-images.githubusercontent.com/25318659/158988871-98be95e0-18b7-45df-9382-64662b5eb6de.png)

What do you think about it?

**Comment by ryankscott** [comment]
Just to confirm, the above screenshot *only* changes for on-prem users? Does it show for both admins and non-admins?

If it shows for non-admins don't you end up reading documents that you can't action yourself? It would be great if we could detect this and have a different call to action. 

If this change is for on-prem users only I think it's fine and we should roll it out if @jjinnii agrees.

We do need to take a step back and do an exercise of mapping all the user flows here. I feel like we don't have a holistic view of the journey and the possible branches that we need to cater for.

**Comment by taras-yemets** [comment]
> Just to confirm, the above screenshot only changes for on-prem users? Does it show for both admins and non-admins?

Nice catch, @ryankscott! This is the message for admin users. Non-admin users will see something like "Repo is not synced. Contact your admin to add the repository to your instance". Will share all three flows (cloud user, on-prem admin, on-prem user) screenshots in the https://github.com/sourcegraph/sourcegraph/pull/31922 description once it's implemented.

**Comment by taras-yemets** [comment]
> Agreed that after this, some design thinking on user flows would help us to better improve our bext onboarding/banner flows. Can create an issue tagging design to track.

Good idea, @jjinnii! Just FYI, we also have an issue https://github.com/sourcegraph/sourcegraph/issues/31843 to update browser extension docs including options page instructions.
