### ISSUE TITLE
Remove repo filter requirement from code monitoring creation UI

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#31943]

**Comment by lguychard** [comment]
To take into consideration: should we keep a repo limit validation rule / hint on sourcegraph.com, where the number of repos will be considerably higher than the repo limit?

**Comment by camdencheek** [comment]
Closing as duplicate of #31943

**Comment by limitedmage** [comment]
@camdencheek is this a duplicate of #25803? This issue is to track the UI side of this (removing the restriction/requirement on the search box when creating the monitor)

**Comment by camdencheek** [comment]
Oh lol. I just closed it as a duplicate of itself 🤦 Thanks Juliana 😄
