### ISSUE TITLE
Log VS Code extension uninstall events

### ISSUE THREAD

**Issue by tjkandala** [sourcegraph/sourcegraph#31947]
We can [run a script on extension uninstall](https://code.visualstudio.com/updates/v1_21#_extension-uninstall-hook). Ideally, we would be able to use the user's persisted anon id to have insight on behavior of users that uninstall, but this event would be valuable to us regardless of whether that's possible (depends on `ExtensionContext` passed to `activate` function, so unlikely).

**Comment by abeatrix** [comment]
@tjkandala I came across a post that might be related to this: it looks like we won't be able to access the vscode API to retrieve the URL and accesstoken from users' settings when running the post-uninstall script: https://github.com/microsoft/vscode/issues/35006#issuecomment-372384164

**Comment by tjkandala** [comment]
@abeatrix got it, so we won't be able to log uninstall events. Should we remove "install state" from pings?

**Comment by abeatrix** [comment]
We can try to see if we can get those info from the user setting file using fs? If that doesn't work then I can remove it from the pings, or @jjinnii do you think we should just send all the uninstall pings to cloud to just get an overall uninstall number? (Without knowing who)

**Comment by jjinnii** [comment]
@abeatrix  If overall uninstall number means: flat count of uninstalls (monthly/weekly whatever cadence) from our customers, but we can't tell which customers/users, that's still useful for us!

**Comment by erzhtor** [comment]
Hey, @abeatrix! I think we can access VsCode settings using `fs` module from uninstall script. Snyk seems to use same approach for their VsCode extension https://sourcegraph.com/github.com/snyk/vscode-extension/-/blob/src/uninstall.ts?L101-139. 
So if we will store apiToken/anonymousUserId in there, we can event after uninstall identify user, thus send smth like `VSCEUninstalled` event.

**Comment by erzhtor** [comment]
Also, related question, will we add an install event too? Smth like `VSCEInstalled`? This would help to build different charts, such as churn. I have a related issue to add `has_vsce_extension=true` user property in Amplitude https://github.com/sourcegraph/sourcegraph/issues/32039, so adding custom VSCEInstalled/Uninstalled events would be helpful.

**Comment by abeatrix** [comment]
@erzhtor thanks for looking into this, the link you shared is exactly what I was looking for so thank you! And your second point makes sense too, we can maybe log the VSCE install event during the step when we first create an anonymous user id? I will work on it today, this is super helpful thanks Erzhan!

**Comment by abeatrix** [comment]
Update: @tjkandala and I have found a way to log uninstall events while the extension still has access to the VS Code API ([by watching the `.obsolete` file](https://github.com/sourcegraph/sourcegraph/blob/fbafd128f0294dabe4a1e854c3624d3b2b722e32/client/vscode/src/settings/uninstall.ts)). This method also allows us to display an uninstall survey without needing the user to restart VS Code re: https://github.com/sourcegraph/sourcegraph/issues/31018

**Comment by jjinnii** [comment]
Thanks @abeatrix! Moving this issue into next iteration. I'll provide some design guidance on this after I get answers on whether we can/should use the Hubspot NPS forms. ([Slack thread](https://sourcegraph.slack.com/archives/C01T0BL4EFN/p1647026947469529)) I'll update you here once designs are ready/I have answers!

**Comment by abeatrix** [comment]
Uninstall event will now be logged starting from the 2.2.0 release: [changelog](https://marketplace.visualstudio.com/items/sourcegraph.sourcegraph/changelog) / [Commit](https://github.com/sourcegraph/sourcegraph/pull/30084/commits/3066356f4f62e8495e4886d390bcc97c0ec649fc)
