### ISSUE TITLE
Unify git archive code

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#31982]
Fetching a git archive is done [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@3d690041bc587a1e951a04a758546a86dc60d3ca/-/blob/internal/vcs/git/archive.go?L26:6). We reject the request if sub-repo permissions are enabled for the repo.

Note, that it calls `gitserver.DefaultClient.Command`

However, we also have a specific `Archive` endpoint in `gitserver` called [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@3d690041bc587a1e951a04a758546a86dc60d3ca/-/blob/internal/gitserver/client.go?L311) which is served [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@3d690041bc587a1e951a04a758546a86dc60d3ca/-/blob/cmd/gitserver/server/server.go?L862)

We should instead be using the `archive` endpoint in order to be consistent and also because it allows supplying a list of paths to include in the archive. By allowing this, we can perform sub-repo filtering on the paths first and then request only those paths from the archive. An example of doing this can be seen [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@3d690041bc587a1e951a04a758546a86dc60d3ca/-/blob/internal/codeintel/lockfiles/service.go?L55-69)

Thanks @tsenart for spotting this

**Comment by mollylogue** [comment]
Thankfully [git.LsFiles](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/vcs/git/tree.go?L99) already has sub-repo filtering implemented so we should just be able to leverage that.

**Comment by tsenart** [comment]
> I'm guessing that this list is then what we want to pass into the actual git archive command to be included in the archive? (and we could do any filtering at that point, once we have the list of all files, before we call git archive). Does that make sense/fit with what you're thinking?

Yes that's exactly it. Plus doing all of that inside the [archive endpoint](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/gitserver/server/server.go?L862:18&subtree=true) to avoid an [extra round-trip like we're doing here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/codeintel/lockfiles/service.go?L55-73&subtree=true).

**Comment by ryanslade** [comment]
This all sounds good, but we should check a couple of things before rolling it out:

1. If sub-repo permissions are not enabled we should just ask for all files using `.`
2. Test what happens when, after filtering, we need to pass a very large list of files. I can imagine on some large repos we may be passing through file lists in the order of 100k files and I worry about something breaking at that level.

**Comment by mollylogue** [comment]
Update: At this point I don't think there's a way for us to handle repos with very large lists of files. We can update the code to pass the list of files as a request body to `gitserver` to workaround a 431 http error, but then we will still get an error like: `error: fork/exec /opt/homebrew/bin/git: argument list too long (stderr: "")`. As far as I can tell there isn't a way around this, unless eventually `git` supports something like the `--files-from` or `-T` argument for the `tar` command, which takes a file which contains a list of file names to include in the archive (thus working around the `argument too long` error). As it stands, though, `git` doesn't have this feature.

**Comment by chrismwendt** [comment]
A couple ideas:

`git cat-file --batch` - you can stream paths in via stdin and get file contents out via stdout.

The ["exclude" magic pathspec](https://css-tricks.com/git-pathspecs-and-how-to-use-them/#aa-exclude) will omit paths that match from the results: `git archive HEAD ":!foo/"` will give you all but the `foo/` directory.

**Comment by mollylogue** [comment]
> A couple ideas:
> 
> `git cat-file --batch` - you can stream paths in via stdin and get file contents out via stdout.
> 
I'll look into that idea. Looks promising.

> The ["exclude" magic pathspec](https://css-tricks.com/git-pathspecs-and-how-to-use-them/#aa-exclude) will omit paths that match from the results: `git archive HEAD ":!foo/"` will give you all but the `foo/` directory. This works if the sub-repo perms model can be converted to a combination of include/exclude rules.

Last I checked the git pathspecs weren't compatible w/ the format of sub-repo permissions but it's worth me taking another look at that. If we could provide include/exclude rules instead of a full list of files, that would be amazing.

**Comment by mollylogue** [comment]
PR to finish unifying git archive code: https://github.com/sourcegraph/sourcegraph/pull/32101

Draft PR to implement sub-repo filtering for git archive https://github.com/sourcegraph/sourcegraph/pull/32738
