### ISSUE TITLE
globalstatedb package is a disaster and should be rewritten

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#3201]
Original title: Cleanup global_state DB code to remove duplicate entries and prevent site_id from changing

Reported by https://app.hubspot.com/contacts/2762526/company/407 948923 

When creating a new user account, the management console password is reset to a newly-generated secure password incorrectly. This causes the `/site-admin` page to show the new password prompt again:

![image](https://user-images.githubusercontent.com/3173176/55498227-f360c800-55f7-11e9-96a1-47b23b115eee.png)

1. **This is very confusing behavior as a user** because it seems worrying, it is also quite annoying seeing the password prompt come back.
2. **This cannot be used to breach security**, as the newly generated password is indeed a secure one. The worst case scenario outcome from this is:
    - The site admin needs access to their management console but doesn't know the password as it has been reset and can't retrieve it via the `/site-admin` page (e.g. if site is down). [The admin would have to reset the password manually to gain access in this case](https://docs.sourcegraph.com/admin/management_console#how-can-i-reset-my-management-console-password).

### Technical explanation

The `global_state` table which tracks whether or not the site is initialized and stores the bcrypt'd version of the management console password can have multiple rows.

This occurs when [`tryInsertNew`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/pkg/db/globalstatedb/globalstatedb.go#L89) runs more than once -- or any time that `globalstatedb.EnsureInitialized` is called, effectively.

Related: https://github.com/sourcegraph/sourcegraph/issues/2322

### Resolution timeline

I've scheduled this tentatively for 3.3, but it is possible it will be pushed back to a follow up patch release or 3.4 given other more important work on my plate and given this issue is just an annoyance.

Another option is to prioritize this issue for 3.3 by scheduling another team member to work on this. Happy to do so if anyone wants to request we definitely get the fix in 3.3.

**Comment by slimsag** [comment]
https://github.com/sourcegraph/sourcegraph/pull/4014 fixes the user-observable issue here, changing this issue to reflect the major debt we have here.

Today, the `global_state` table contains four values: `site_id`, `initialized`, `mgmt_password_plaintext` and `mgmt_password_bcrypt`.

The table can have multiple entries which is very hard to reason about. It has multiple entries because of concerns that by doing any sort of lock on this table we would harm perf substantially (after all, site initialization is checked for every request going through Sourcegraph). There are multiple worrisome points about this table:

- Although eventually consistent because updates to this table affect all rows, the query to select `initialized` has a `LIMIT 1` but no order clause which means we are relying on undefined postgres ordering.
- Whenever a new table entry is created, the site ID is regenerated which means all site IDs sent to us via telemetry in the past 6-8mo (at least) have been randomly regenerated as soon as someone creates a new user account on their instance. (I've chatted with @dadlerj about this over Slack, he said it's not the end of the world but can harm us in a bunch of small/minor ways).
- It is hard to maintain the management console password across new table entries because the table is unordered and we have to select (again, at undefined postgres order) the existing one from the previous row.

To fix this we should:

1. Delete the current implementation in `pkg/db/globalstatedb` except public functions.
2. Create a new implementation with sound engineering principles and lots of tests.
3. Verify the new implementation is just as fast so we're not majorly regressing on performance site-wide.

**Comment by slimsag** [comment]
For a more up-to-date picture of the challenges here and what we should do next, see https://github.com/sourcegraph/sourcegraph/pull/19769#issuecomment-816847686

**Comment by slimsag** [comment]
A note from @indradhanush on Slack about attempting to do this and running into the same challenges:

> Thank you. You've already answered a question that I would have asked next, that is if it is worth the risk and effort to try to fix #12229 in the existing implementation or live with it a little longer until we can come back and do a rewrite.
>
> I am going to stop working on this as I've spent more time on fixing the issue than I think is justified and yet I am no closer to the fix. After having spent around two days trying to work on the fix, it has been harder to take care of all the edge cases than what I could have imagined when I started out on this issue.
>
> Exhibit A: this issue in this thread itself where it appears to me that we incorrectly return false from the function as the answer to "is the site initialized?" when we've just made a database write to update initialized=true. And yet, in my PR where I've "fixed" this behavior to return true if the database writes initialized=true, some existing tests fail.  ¯\_(ツ)_/¯

**Comment by indradhanush** [comment]
Closed by #38781.
