### ISSUE TITLE
Add a user property for "IDE extension user" in Amplitude

### ISSUE THREAD

**Issue by ryankscott** [sourcegraph/sourcegraph#32039]
It'd be great to track both:
- If a user is using one of our IDE extensions
- Which IDE extension the user is using

I believe we could achieve this by [updating a user property](https://help.amplitude.com/hc/en-us/articles/115002380567-User-properties-and-event-properties) upon installation of our IDE extensions

**Comment by rrhyne** [comment]
This is a bit of a nit, but I think we need an "IDE Installed" event (probably with type: VSCode, Jetbrains, etc.). I mention this because "a user is using one of our IDE extensions" is close to repeated events such as searching and because we might also want an "IDE uninstalled" event.

**Comment by ryankscott** [comment]
> This is a bit of a nit, but I think we need an "IDE Installed" event (probably with type: VSCode, Jetbrains, etc.

I believe we already have this for VSCode and could add this for JetBrains when we get there.

I'm unsure how we use Amplitude here. Do we infer user state by recreating events? For example do I tell that someone is currently using the VSCode IDE extension by looking for installation event without a subsequent uninstallation event. What happens if they then reinstall? 

I've always struggled with accuracy when trying to recreate state from events in analytics platforms. That's why I was thinking it might make sense to have this as a user property (as well as the events).

**Comment by rrhyne** [comment]
If we have it, that's great let's close this. I didn't think we did. 

> I'm unsure how we use Amplitude here. Do we infer user state by recreating events? For example do I tell that someone is currently using the VSCode IDE extension by looking for installation event without a subsequent uninstallation event. What happens if they then reinstall?

If the event has a high business value I think it is more clear to have a single explicit event log. For example: if my goal is to cause installations and I need to report on the funnel from CTA shown to install, then having an explicit install event is ideal. 

That said, I think you can also infer that by ending the funnel with SearchViaIDE {type:VSCE}, even though there are many of those events per user.

**Comment by jjinnii** [comment]
@abeatrix @tjkandala Please jump in here if I'm wrong, but I think we've just implemented this in #32000 . From that issue "This PR also adds a new EventSource type `IDEEXTENSION` to log all ide-extensions-related events as suggested in [RFC 547](https://docs.google.com/document/d/1YzDrXEhpa0dvE4On1S672w8l01EsLcXhLsJrLOgcQKQ/edit?usp=sharing)", which includes intall/uninstall data as well as active usage data.

**Comment by ryankscott** [comment]
@rrhyne I think we're talking about slightly different things. To clear things up, I would like to see:

1. An event in Amplitude for (un)installation of IDE extensions. I had thought we had this.
2. A [user property](https://help.amplitude.com/hc/en-us/articles/115002380567-User-properties-and-event-properties#h_39e46c92-7b7f-4358-a96f-c82cc3342e3e) for each user to know if they are a user of an IDE extension or not.

If we want to track whether or not users the behaviour of users who have IDE extensions installed differs to those who don't, I believe it will be easier with #2. Otherwise, you have to reconcile installation and uninstallation events to know if a user is using an IDE extension. This may or may not be a problem depending on how we use Amplitude, so I'm happy to hear whether or not this is the right approach.

**Comment by rrhyne** [comment]
@ryankscott  I agree with both of those points. Didn't mean to intone I did not!

**Comment by erzhtor** [comment]
We decided to go with a similar approach to https://github.com/sourcegraph/sourcegraph/issues/30843 approximation using the last usage timestamp.
