### ISSUE TITLE
"Enable on this domain" often not showing up

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#3204]
![image](https://user-images.githubusercontent.com/10532611/55500841-6e060380-5649-11e9-9049-4e5b16ccb263.png)

I often need to reinstall to make it show up

**Comment by lguychard** [comment]
The module we use to add this relies on `runtime.onInstalled()` and there may be some flakiness there, but this is a lot less critical now that permissions can be granted directly from the popup:

![image](https://user-images.githubusercontent.com/1741180/56222081-aeaf4500-606b-11e9-9c3d-fa252d3b6a0e.png)

**Comment by fregante** [comment]
This was fixed in v1: https://github.com/fregante/webext-domain-permission-toggle/pull/8

Which was merged recently https://github.com/sourcegraph/sourcegraph/pull/5116

It should work more reliably now

**Comment by felixfbecker** [comment]
Awesome. Will reopen in case it happens again
