### ISSUE TITLE
Add a Dependencies button / icon in type:repo search results

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#32046]

**Comment by stefanhengl** [comment]
cc @rrhyne tagging you here because you have been thinking about this. If you don't think this is relevant anymore we should close it.

**Comment by rrhyne** [comment]
Is the idea that from any given repo result we could easily pivot to view it's dependancies from the search results page?

**Comment by stefanhengl** [comment]
I am not 100% sure but I think Tomas just talked about a visual clue that distinguishes packages from repos.

**Comment by stefanhengl** [comment]
This feature has been discontinued.
