### ISSUE TITLE
Add a user property for "Browser extension user" in Amplitude

### ISSUE THREAD

**Issue by ryankscott** [sourcegraph/sourcegraph#32040]
It'd be great to track both:
- If a user is using one of our Browser extensions
- Which Browser extension the user is using

I believe we could achieve this by [updating a user property](https://help.amplitude.com/hc/en-us/articles/115002380567-User-properties-and-event-properties) upon installation of our IDE extensions

**Comment by rrhyne** [comment]
This is a bit of a nit, but I think we need an "Bext Installed" event, probably with type: Gitlab, GitHub, etc., and maybe a 'browser' property?. I mention this because "a user is using one of our Browser extensions" is close to repeated events and because we might also want a "Bext uninstalled" event.

**Comment by erzhtor** [comment]
We do have events for determining Browser extension installs/uninstalls https://github.com/sourcegraph/sourcegraph/issues/31486 (PRs are merged, but we need to release a new browser extension, which we will do next week probably):
- `BrowserExtensionInstalled` + event properties `platform={chrome|firefox|safari}-extension; version={browser-extension-version}`
- `ViewStaticPage` with `utm_campaign=browser-extension-uninstall;utm_source={chrome|firefox|safari}-extension;utm_content={browser-extension-version}`

@ryankscott, @rrhyne, to clarify, do you think we should add an Amplitude user property too?

**Comment by ryankscott** [comment]
@erzhtor IMO yes. Especially if we want to do feature detection to show banners etc.

**Comment by erzhtor** [comment]
Discussed this during the planning and we decided to go with a similar approach to https://github.com/sourcegraph/sourcegraph/issues/30842 approximation using the last usage timestamp.
