### ISSUE TITLE
Generate Apple Distribution Certificate

### ISSUE THREAD

**Issue by taras-yemets** [sourcegraph/sourcegraph#32071]
Apple Distribution Certificate is about to expire.

To generate a new certificate, sign in and visit [Certificates, Identifiers & Profiles](https://developer.apple.com/account/resources/certificates/list).
Certificate: Distribution
Team ID: see in [thread](https://sourcegraph.slack.com/archives/C01T0BL4EFN/p1646084388463119)
To learn more about expired certificates, visit the [certificates support page](https://developer.apple.com/support/certificates/).

**Comment by taras-yemets** [comment]
@muratsu It looks like your _personal_ distribution certificate expires at the end of this month.
As it follows from the [certificate docs page](https://developer.apple.com/support/certificates/) expired or revoked certificate affects mostly the ability to sign apps using it in future, the existing ones are not likely to be affected.
Current Safari extension release is published using @erzhtor valid certificate.
I don't think we should take any action on it now. If you want to publish the exension by yourself after this certificate expires, you can always generate a new one.

**Comment by muratsu** [comment]
Thank you for looking into this @taras-yemets !
