### ISSUE TITLE
gitserver: "killed" signal without any error message

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#32098]
When indexing https://k8s.sgdev.org/github.com/sgtest/megarepo (500K commits) with [Rockskip](https://github.com/sourcegraph/sourcegraph/pull/28719), I'm noticing some cryptic errors from gitserver:

Error when calling `git archive`:

> t=2022-03-02T23:25:04+0000 lvl=eror msg="indexing error" repo=github.com/sgtest/megarepo commit=1d470e4562a24b453a8693e379f638c563c1a7fa err="LogReverseEach: ParseLogReverseEach: getSymbols (deleted): while looping ArchiveEach: FetchRepositoryArchive: readTar: signal: killed (stderr: \"\")"

Error when calling `git rev-list`:

> t=2022-03-02T23:25:08+0000 lvl=eror msg="indexing error" repo=github.com/sgtest/megarepo commit=a6665784494263d152cdae5d2b1f86ac590ed9b2 err="RevList: signal: killed (stderr: \"\")"

Does anyone know what this might be caused by? OOM? Timeout? Git dir corruption? I might dig deeper in case this is as puzzling to others as it is to me.

**Comment by chrismwendt** [comment]
I'm seeing a lot of `signal: killed` errors in gitserver logs:

> 2022-03-03T03:51:01.501959185Zt=2022-03-03T03:51:01+0000 lvl=eror msg="performing background repo update" error="failed to fetch: failed to update with output \"error: rev-list died of signal 9\\nerror: git-remote-https died of signal 9\\n\": signal: killed"

I'm guessing killed for being OOM. gitserver-0 is regularly getting killed and restarted:

<img width="483" alt="CleanShot 2022-03-02 at 21 53 19@2x" src="https://user-images.githubusercontent.com/1387653/156498637-32711701-7648-424b-8921-7c99c3f60413.png">

<img width="645" alt="CleanShot 2022-03-02 at 21 52 05@2x" src="https://user-images.githubusercontent.com/1387653/156498648-af9b33c9-c8fc-43ee-b29f-4f4e9aaa26fe.png">

Probably a bad repo. I'm guessing the megarepo/gigarepo. I've been regenerating both of them recently, and there was a bug that caused over 10M commits, fixing in https://github.com/sourcegraph/sourcegraph/pull/32038

I commented out the gigarepo in the site config in an attempt to delete it from the instance and clear it out.

**Comment by chrismwendt** [comment]
htop shows `repack` is taking a ton of memory 9.8GB:

<img width="2284" alt="CleanShot 2022-03-04 at 18 55 32@2x" src="https://user-images.githubusercontent.com/1387653/156863198-bf1ecefd-1092-4ad7-b295-86bc45e1a4b9.png">

It appears to be called by `sg_maintenance.sh`:

https://github.com/sourcegraph/sourcegraph/blob/2bb6927bb0283ea8a7395afc3100e6d67bfb68fc/cmd/gitserver/server/sg_maintenance.sh#L49-L54

Unless it's stuck on a cold start of some kind, I don't think the execution time is actually proportional to the new objects because I pulled the megarepo locally a few days ago and then again just now and it only took 12s with ~1K files:

```
git pull
remote: Enumerating objects: 4537, done.
remote: Counting objects: 100% (1327/1327), done.
remote: Compressing objects: 100% (166/166), done.
remote: Total 4537 (delta 1169), reused 1316 (delta 1158), pack-reused 3210
Receiving objects: 100% (4537/4537), 6.38 MiB | 4.76 MiB/s, done.
Resolving deltas: 100% (2222/2222), completed with 736 local objects.
From github.com:sgtest/megarepo
   26034d844c1a6..35dfe91d29500  main       -> origin/main
Updating 26034d844c1a6..35dfe91d29500
...about 1000 files
```

**Comment by tsenart** [comment]
The `-c pack.windowMemory=100m` flag is supposed to limit the amount of memory used during repacking. We might just need to give gitservers more memory in dogfood? Gigagrepo is way bigger than the megarepo.

**Comment by keegancsmith** [comment]
This has been fixed in master by @stefanhengl so I will be closing this out. The upstream issue is https://github.com/sourcegraph/sourcegraph/issues/33353

I am currently re-enabling gigarepo on dogfood. If you spot anything please re-open / tell us :) Just to be safe I will regenerate the repo with the latest version of git-combine before enabling.
