### ISSUE TITLE
insights: handle "downgrading" to limited access mode

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#32099]
We need to handle the downgrade experience, specifically what happens to insights created when you had >2 insights ability during a trial. 

This is described in [this section of the RFC 567](https://docs.google.com/document/d/1WIInNUMtgOPIeiIONGios2_y67CSkkZr0WtFtU4h_IY/edit#bookmark=id.pb9dx6uwjbcu). 

[Designs here](https://www.figma.com/file/38cMCA2pOScKIqzt3ZNuiz/?node-id=246%3A11)

This is a followup to #30165.

**Comment by felixfbecker** [comment]
@unclejustin is in the progress of breaking this up by today afternoon

**Comment by unclejustin** [comment]
Closing in favor of smaller created issue.
