### ISSUE TITLE
Add/update existing user onboarding docs

### ISSUE THREAD

**Issue by erzhtor** [sourcegraph/sourcegraph#32115]
Update existing docs pages to make them more organized and clear https://docs.sourcegraph.com/code_search (or create a separate). 

Something like "Using Sourcegraph" group/section docs with two main user targets: 
1) I'm user > teach how to use sourcegraph functionality
2) I'm admin > teach how to administer/manage instance

Follow-up on [PD 31 doc](https://docs.google.com/document/d/1-cIAX6UDL3x4kFVcEOL3DR0MgMmi28Q2-ELS1truJ48/edit?disco=AAAAWD3gNFg)

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @a-bergevin - the "team/growth" label was applied to this issue.
