### ISSUE TITLE
Investigate sub-repo filtering for Rockskip

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#32124]
The experimental Rockskip code is being added to the symbols services.

From there, we see that we're making raw command requests to gitserver without
sub-repo filtering. 

We need to investigate whether we require adding filtering or whether out existing symbols
filtering will be enough.

At the very least, we may want to move the `Command` calls into our `vcs/git` package if possible
since we want to isolate that code and eventually remove the ability to make raw calls.

**Comment by ryanslade** [comment]
Awesome, thanks for the detailed writeup!

AFIAK @chrismwendt is working on this. Chris, are there any reasons you can think of not to make the changes listed above?

**Comment by chrismwendt** [comment]
:+1: to moving the commands to the `git` package with sub-repo perms checking + a comment in Rockskip saying filtering happens elsewhere.

Replacing `LogReverseEach` with `Commits` might make it use more memory because `LogReverseEach` streams, whereas `Commits` doesn't.

**Comment by mollylogue** [comment]
> 👍 to moving the commands to the `git` package with sub-repo perms checking + a comment in Rockskip saying filtering happens elsewhere.
> 
> Replacing `LogReverseEach` with `Commits` might make it use more memory because `LogReverseEach` streams, whereas `Commits` doesn't.

Ah gotcha. We can at least move it into the `git` package and I can add a comment that it doesn't currently do sub-repo filtering. It wouldn't be too hard to implement filtering in the same way we do for `Commits`, (i.e. adding the `--name-only` flag to the command and filtering out commits w/ files the user doesn't have access to) but there's currently no reason to do that.

**Comment by mollylogue** [comment]
git commands are now all going through the `git` package. No sub-repo filtering is necessary.

**Comment by ryanslade** [comment]
Nice, thanks!
