### ISSUE TITLE
Searching for method calls with no params does not work as expected

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#3214]
Using repository sourcegraph/sourcegraph - Searching for `open(` works and disables regex, but searching for `open()` doesn't yield the results you'd expect if you first typed `open(`.

![ScreenFlow](https://user-images.githubusercontent.com/133014/55519491-eb6f4b00-562c-11e9-9acf-aeccd1f1e6f5.gif)

**Comment by sqs** [comment]
This can wait until we have more search query fix ups. I don’t think this is a common enough source of confusion to immediately prioritize a fix of this over other search issues or to roll back the search query autofixes (this was a known consequence).

**Comment by ijt** [comment]
It's really easy to fix this. I had support for this and more in my initial version of the autofix PR.
