### ISSUE TITLE
Remove code-insights deployment on Cloud 

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#32150]
The codeinsights-deployment on Cloud is not used. We should remove it along with the service and persistent volumes

**Comment by danieldides** [comment]
Slack context: https://sourcegraph.slack.com/archives/C07KZF47K/p1646329196329549

[deploy-sourcegraph-cloud](https://github.com/sourcegraph/deploy-sourcegraph-cloud/tree/release/base/codeinsights-db) files.
