### ISSUE TITLE
Create CI check to ensure the image updates to Sourcegraph cloud are use the same image tag

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#32152]
Issue:
Last week Renovate picked the different commits to deploy in the same PR. 

Fix:
We need to do a check with each deploy to ensure that the image that is being updated has the tag that we want to actually deploy.

**Comment by danieldides** [comment]
`#inc-88-worker-crashlooping` channel on Slack. Should link to [this](https://sourcegraph.slack.com/archives/C02KX975BDG/p1646315070150499) thread on Slack about the specific issue that occurred.

In a normal, healthy state renovate should update _all_ images to the exact same commit for all containers. On this PR (https://github.com/sourcegraph/deploy-sourcegraph-cloud/pull/15760) renovate randomly decided to change only a couple deployments and use a couple different versions for them for no reason. As a result, there was an incident.

This ticket should hopefully come up with some way of looking at Renovate's PRs and verify that _all_ containers are found there and that they're all updating to the same image.

**Comment by JenRed777** [comment]
Talked with @jhchabran and DevEx is going to implement a short term solution for this issue until we are ready to pick up working on a more long term solution.

**Comment by jhchabran** [comment]
Actually, there was a little miscomprehension, I was referring to alerting when `sg live` is raising an error because it can't find the deployed version in the last 20 commits, which is a sign of the prod to be lagging behind, usually because some renovate job did not run.
