### ISSUE TITLE
Report metrics for deployments pre-prod

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#32153]
- [x] Submit metrics to HoneyComb
- [x] Create a Dashboard
- [ ] Document the dashboard

**Comment by jhchabran** [comment]
https://ui.honeycomb.io/sourcegraph/board/ev4yWqP5h3u/Deployments

<img width="962" alt="CleanShot 2022-04-11 at 11 39 53@2x" src="https://user-images.githubusercontent.com/10151/162711479-a15bec0c-c033-4180-8a0e-28896d6c2690.png">

**Comment by bobheadxi** [comment]
Added derived minutes, and a chart for showing the services that take longest to deploy:

<img width="1229" alt="image" src="https://user-images.githubusercontent.com/23356519/163088721-fe59d875-c167-4b04-8a4c-110d0ef22c3b.png">

Requires https://github.com/sourcegraph/sourcegraph/pull/33823
