### ISSUE TITLE
stretch: deploy changes based on whether or not diff affects stateful services

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#32151]
## Problem

See this part of the [Miro board](https://miro.com/app/board/uXjVOKqPSDM=/?moveToWidget=3458764519763646753&cot=14) 

Some services which are stateful introduce a silent interruption of service when deployed, i.e deploying `gitserver` will prevent some search results to happen. As such, the current approach is to deploy those on a daily basis and to exclude them from continuous deployment. 

RFC 586 aims to rely on a cron-job in order to address this, postponing the deployments to limit disruption toward our customers. 

## Expected Outcome 

- We manage to find a way to confidently distinguish between the PRs that are not affecting those services from those who do. This enables us to identify PRs which are eligible for a continuous deployment where we can keep going with RFC 592.

**Comment by bobheadxi** [comment]
From my comment in the miro board:

> Probably too complex upfront to tackle in an granular fashion - a simpler approach would be to leave comments on PRs whenever a commit deploys, with a list of _which_ services have deployed, and let the author figure out if it is relevant

**Comment by jhchabran** [comment]
Because filtering out the notifications on deployment notifications works the same way as this, I run some explorations and came up with the following approach: 

1. For every docker image of a given service, we add an additional label:

```sh
## gitserver/build.sh
# Create a reproducible checksum of the binary named `
go build -trimpath -ldflags "-X github.com/sourcegraph/sourcegraph/internal/version.version=no-version  -X github.com/sourcegraph/sourcegraph/internal/version.timestamp=no-version" -buildmode exe -tags dist -o "$OUTPUT/checksum-$(basename $pkg)" "$pkg"
serviceChecksum="$(sha1sum $OUTPUT/checksum-$(basename $pkg) | cut -f 1 -d ' ')"

go build -trimpath -ldflags "-X github.com/sourcegraph/sourcegraph/internal/version.version=$VERSION  -X github.com/sourcegraph/sourcegraph/internal/version.timestamp=$(date +%s)" -buildmode exe -tags dist -o "$OUTPUT/$(basename $pkg)" "$pkg"

docker build -f cmd/gitserver/Dockerfile -t "$IMAGE" "$OUTPUT" \
  --progress=plain \
  --build-arg COMMIT_SHA \
  --build-arg DATE \
  --build-arg VERSION \
  --label BIN_CHECKSUM="${serviceChecksum}"

```

```dockerfile
# gitserver/Dockerfile
# ...

LABEL org.opencontainers.image.revision=${COMMIT_SHA}
LABEL org.opencontainers.image.created=${DATE}
LABEL org.opencontainers.image.version=${VERSION}
LABEL com.sourcegraph.github.url=https://github.com/sourcegraph/sourcegraph/commit/${COMMIT_SHA}
# This is the new label
label com.sourcegraph.github.checksum=${bin_checksum}

# ... 
```

2. When we are going through the pull requests in `deployment-notifier`
  - for each PR that we found to be included:
    - Grab the token to query the registry: `token=$(curl -s "https://auth.docker.io/token?service=registry.docker.io&scope=repository:${repo}:pull" | jq -r '.token')`
    - Fetch the digest so we can get the manifest details `digest=$(curl -s -H "Accept: application/vnd.docker.distribution.manifest.v2+json" -H "Authorization: Bearer $token" "https://registry-1.docker.io/v2/${repo}/manifests/COMMIT_TAG" \
  | jq .config.digest -r)`
       - because we need to be able to query the manifest for a specific commit and we don't know the exact tag of the previous commits because the tags are formed with additional data that we don't have at this stage, we need to add tag the image when building them on the merge commit.
    - And finally get the labels `curl -s -L -H "Accept: application/vnd.docker.distribution.manifest.v2+json" -H "Authorization: Bearer $token" "https://registry-1.docker.io/v2/${repo}/blobs/$digest" | jq .config.Labels` 
      - <img width="1160" alt="image" src="https://user-images.githubusercontent.com/10151/165049705-fc240307-a187-4f11-bcad-670fdeca9a49.png">
    - take note of the `BIN_CHECKSUM` 
  - run the same API calls as above, but for the previous image, the one that this deployment is removing (the `-` in the diff) and take note of that `BIN_CHECKSUM`
  - This gets us a list of the form: `[{commit, BIN_CHECKSUM}]`, where the first element is the previous deployment and the others are the PRs in chronological order. 
    - iterate through that list:
      - if the `BIN_CHECKSUM` at the current position differs from the previous one, it means that this PR affected this service. 
      - if it does not, we remove that PR from the list of PR to mention. 

3. Now that for every service, we have a list of PR that affected them, we only notify about those.

4. If we are to ping, we only ping on the above. 

--- 

Changes: 
  - We need to generate the checksums for every service, possibly including other files such as migrations. 
  - We need to tag the docker images with the commit that generated them, so we can find them when listing the checksums of intermediary PRs.

Problems:
  - Not every PR is getting built on main, which means we'd have holes in the racket and can't compare the checksum for those missing builds. 
    - We could mitigate that by assuming that the checksum did not change, but if the next checksum that we have did change, we consider that PR to also have changed the service. Worst case scenario, we notify on a PR that had no changes, if its build failed on `main`.  
  - Handling how the checksum is computed can be a bit tedious to maintain and it's easy to forget something in there.

**Comment by jhchabran** [comment]
> Or better, we let each service define their own hash script

Yes, that would be the best course of action here 😊

**Comment by davejrt** [comment]
TIL about the above, nice!
