### ISSUE TITLE
Limited access mode - creation & editing UI

### ISSUE THREAD

**Issue by unclejustin** [sourcegraph/sourcegraph#32161]
### Data series updates
**Search insights**
- Change copy to "Add up to 10 data series": [Design](https://www.figma.com/file/38cMCA2pOScKIqzt3ZNuiz/Limited-access-mode-RFC-Private-567-%2330165-%5BWIP%5D?node-id=1117%3A8924)
- Add [contextual badge: 'Limited access | Unlock Code Insights for unlimited data series'](https://www.figma.com/file/38cMCA2pOScKIqzt3ZNuiz/Limited-access-mode-RFC-Private-567-%2330165-%5BWIP%5D?node-id=1165%3A11148) above 'add data series' button
- Disable add series button when series total >= 10

**Capture group insights**
- Update [data series note copy ](https://www.figma.com/file/38cMCA2pOScKIqzt3ZNuiz/Limited-access-mode-RFC-Private-567-%2330165-%5BWIP%5D?node-id=1153%3A17581) to reflect 10 series limit
- Add [contextual bage](https://www.figma.com/file/38cMCA2pOScKIqzt3ZNuiz/Limited-access-mode-RFC-Private-567-%2330165-%5BWIP%5D?node-id=1168%3A11791) above the note

### Create button updates (all types of insights, note: please add also to language insight)
- Add [contextual label: 'Limited access | Unlock Code Insights to create unlimited insights'](https://www.figma.com/file/38cMCA2pOScKIqzt3ZNuiz/Limited-access-mode-RFC-Private-567-%2330165-%5BWIP%5D?node-id=1117%3A8989) above "Create code insight" button
- Disable "Create code insight button" if insight total >= 2

### Edit insights:
- disable the 'save changes' button if user tries to modify the locked insight. Add the [contextual badge](https://www.figma.com/file/38cMCA2pOScKIqzt3ZNuiz/Limited-access-mode-RFC-Private-567-%2330165-%5BWIP%5D?node-id=1153%3A16387)
- [insights with >10 data series](https://www.figma.com/file/38cMCA2pOScKIqzt3ZNuiz/Limited-access-mode-RFC-Private-567-%2330165-%5BWIP%5D?node-id=1165%3A11235): disable remaining data series and implement logic of keeping up to 10 active data series. Use case: if user has 12 data series, 10 should be active, 2 should be disabled. If user deletes one active data series, we should update the list and show 10 enabled + 1 disabled data series).

[Designs](https://www.figma.com/file/38cMCA2pOScKIqzt3ZNuiz/Limited-access-mode-RFC-Private-567-%2330165-%5BWIP%5D?node-id=1117%3A8907)

[RFC for more details](https://docs.google.com/document/d/1WIInNUMtgOPIeiIONGios2_y67CSkkZr0WtFtU4h_IY/edit#heading=h.qp2pvnk0jby)

Related to https://github.com/sourcegraph/sourcegraph/issues/30165

**Comment by AlicjaSuska** [comment]
@unclejustin I've also updated this issue description with more details
