### ISSUE TITLE
Support RhodeCode as an external service

### ISSUE THREAD

**Issue by carun** [sourcegraph/sourcegraph#3216]
#### Feature request description

Is it possible to add support for RhodeCode as an external service?

I found sourcegraph a few minutes ago and I pulled the docker image and went to the setup to see that many hosting services were supported (predominantly git based). I couldn't find a way to add RhodeCode as an external service.

![image](https://user-images.githubusercontent.com/471374/55520810-c5e54000-5632-11e9-8ffb-ad39d629a834.png)

**Comment by sqs** [comment]
Thanks for posting. There was past discussion of this on Hacker News at https://news.ycombinator.com/item?id=18124208.

@carun What VCS type (Git/Hg/Subversion) do you use?

**Comment by carun** [comment]
@sqs We predominantly use Hg.

**Comment by keegancsmith** [comment]
@carun Currently we don't support HG, nor do we have any plans for it on our roadmap.

**Comment by sqs** [comment]
@carun Would a workaround using `git-hg` like the one described for Perforce at https://docs.sourcegraph.com/admin/repo/perforce solve your problem?
