### ISSUE TITLE
Limited access mode - dashboards

### ISSUE THREAD

**Issue by unclejustin** [sourcegraph/sourcegraph#32164]
**General items**
- [x] Add [limited access note](https://www.figma.com/file/38cMCA2pOScKIqzt3ZNuiz/Limited-access-mode-RFC-Private-567-%2330165-%5BWIP%5D?node-id=1117%3A8220) to dashboard dropdown
- [x] ['Add or remove insights' button](https://www.figma.com/file/38cMCA2pOScKIqzt3ZNuiz/Limited-access-mode-RFC-Private-567-%2330165-%5BWIP%5D?node-id=1155%3A10969) should be disabled. Please note: it applies to the contextual button on the dashboard, not to the primary 'create insight' button.

**'All insights' dashboard:**
- [x] [Add "Limited access | Create up to two global insights" label](https://www.figma.com/file/38cMCA2pOScKIqzt3ZNuiz/Limited-access-mode-RFC-Private-567-%2330165-%5BWIP%5D?node-id=1135%3A8524) to 'All insights' dashboard
- [ ] Hide [Create Insight](https://www.figma.com/file/38cMCA2pOScKIqzt3ZNuiz/Limited-access-mode-RFC-Private-567-%2330165-%5BWIP%5D?node-id=1135%3A11287) card when insight count greater than 2. Please note: on custom dashboards we do not display the 'create insight' card. **Note: we need to create this card.**
- [x] Show only '[copy link](https://www.figma.com/file/38cMCA2pOScKIqzt3ZNuiz/Limited-access-mode-RFC-Private-567-%2330165-%5BWIP%5D?node-id=1155%3A10927)' option in the dashboard menu

**'Leftover' custom dashboards:**
- [x] [Add "Limited access | Unlock Code Insights for full access to custom dashboards" label](https://www.figma.com/file/38cMCA2pOScKIqzt3ZNuiz/Limited-access-mode-RFC-Private-567-%2330165-%5BWIP%5D?node-id=1135%3A8524) to 'leftover' custom dashboards
- [x] Add [limited access overlay](https://www.figma.com/file/38cMCA2pOScKIqzt3ZNuiz/Limited-access-mode-RFC-Private-567-%2330165-%5BWIP%5D?node-id=1155%3A11078) to locked insights
	- We need to preserve the insight size (wide vs. narrow) to correctly display the key.
- [x] Only show "[Delete](https://www.figma.com/file/38cMCA2pOScKIqzt3ZNuiz/Limited-access-mode-RFC-Private-567-%2330165-%5BWIP%5D?node-id=1165%3A11232)" option in dashboard menu

**Locked insight** can be:
- [x] edited - opens edit UI but cannot save changes (see ‘Creation and Editing UI section below)  
- [x] removed from the dashboard - only available on custom ‘left over’ dashboards so that users can ‘clean up’  
- [x] deleted - delete forever

**Add new dashboard screen**
- [x] Disable "Create dashboard" button on [Add new dashboard](https://www.figma.com/file/38cMCA2pOScKIqzt3ZNuiz/Limited-access-mode-RFC-Private-567-%2330165-%5BWIP%5D?node-id=1117%3A4840) screen
- [x] Add 'Limited access | Unlock Code Insights to create unlimited custom dashboards' to the form

**Comment by AlicjaSuska** [comment]
@unclejustin I've added some items that were missed (labels and copy changes). Also, I grouped them to make it easier to work with. I hope it helps
