### ISSUE TITLE
Decide how we version the chart and release process

### ISSUE THREAD

**Issue by michaellzc** [sourcegraph/sourcegraph#32177]
Decide how we version the chart and release process ([Delivery - helm chart versioning convention](https://docs.google.com/document/d/19yNi5Tc6D8Mwxwa6Muw8TB60ssJPi3OxBaHAwq12198/edit?usp=sharing))

**Comment by caugustus-sourcegraph** [comment]
When we make a decision on this, update the release tool to match the new versioning scheme (https://github.com/sourcegraph/sourcegraph/blob/main/dev/release/src/release.ts#L515-L516).

The sourcegraph-migrator (and future sourcegraph-rbac) chart should be included; right now they aren't part of the batch release process.

**Comment by caugustus-sourcegraph** [comment]
Minor / patch / hotfix releases all set, we're largely following the existing deployment process with a hopefully-never-used workaround to deal with hotfixes.

Still TBD is how we approach insiders builds, but that shouldn't block GA.

**Comment by caugustus-sourcegraph** [comment]
Insiders builds are now being generated on commits to main and pushed to a separate chart repo tagged with `<chart version>-insiders-{short sha}`. This doesn't strictly follow semver according to helm so versions won't show up in a search unless you add the `--devel` flag, i.e.:
```
 helm search repo insiders --devel
 ```
