### ISSUE TITLE
Update dogfood environment to use helm

### ISSUE THREAD

**Issue by michaellzc** [sourcegraph/sourcegraph#32179]
We will mix helm + kustomize together to deploy dogfood https://github.com/kubernetes-sigs/kustomize/blob/master/examples/chart.md

### Needs review

- [x] https://github.com/sourcegraph/infrastructure/pull/3178
- [x] Enable `--enable-helm` feature flag on dogfood argocd https://github.com/sourcegraph/infrastructure/pull/3157
- [ ] Add helm deployment https://github.com/sourcegraph/deploy-sourcegraph-dogfood-k8s/pull/4018

### Blockers

- [x] Upgrade argo to 2.2.x to mitigate the helm vulnerability https://github.com/sourcegraph/security-issues/issues/216 (@michaellzc is looking into it)
- [x] https://github.com/sourcegraph/deploy-sourcegraph-dogfood-k8s/pull/4040
- [x] Update https://github.com/sourcegraph/deploy-sourcegraph-dogfood-k8s/pull/4018 to remove the `yesRoot` override since we're now doing non-root migration before helm

### Migration plan

- [ ] announce in #dev-ops that dogfood will be down for a short time
- [ ] merge https://github.com/sourcegraph/deploy-sourcegraph-dogfood-k8s/pull/4018
- [ ] we perform a soft (non-cascading) deletion of all previous argo app, i.e., no kubernetes resources will be removed by argo `argo-cd app delete --cascade=false --yes dogfood-k8s`
- [ ] scale `pgsql`, `codeinsights-db`, and `codeintel-db` to zero (we https://github.com/sourcegraph/deploy-sourcegraph-helm/pull/70 in helm, otherwise, the new sts won't be able to mount the PVC)
- [ ] apply the new app https://github.com/sourcegraph/infrastructure/pull/3157/files#diff-791a98a7d47c416a6a03a8cc151968a09dc54db5511789f9515b1fd2f2dafa94
- [ ] merge https://github.com/sourcegraph/infrastructure/pull/3157
- [ ] Clean up legacy plain k8s manifests in the deploy-dogfood repo to avoid future confusion and open a new PR

### Fallback plan

We're not touching any PV/PVC during the migration so there's no concern for potential data loss. We should be able to remove the added argo app and reapply previous apps again

**Comment by caugustus-sourcegraph** [comment]
@michaellzc - 
```
scale pgsql, codeinsights-db, and codeintel-db to zero (we https://github.com/sourcegraph/deploy-sourcegraph-helm/pull/70 in helm, otherwise, the new sts won't be able to mount the PVC)
```

We might be able to get away with just applying those changes without scaling to 0. During my testing for https://github.com/sourcegraph/sourcegraph/issues/27759 I applied the statefulset changes on an existing deployment and it Just Worked(TM).

**Comment by caugustus-sourcegraph** [comment]
> we should run a scrtip to overwrite all app.kubernetes.io/instance label 

If we're doing this anyway, should we just take the opportunity to fix the labeling so that all the kustomization patches aren't required?

**Comment by michaellzc** [comment]
> @michaellzc -
> 
> ```
> scale pgsql, codeinsights-db, and codeintel-db to zero (we https://github.com/sourcegraph/deploy-sourcegraph-helm/pull/70 in helm, otherwise, the new sts won't be able to mount the PVC)
> ```
> 
> We might be able to get away with just applying those changes without scaling to 0. During my testing for #27759 I applied the statefulset changes on an existing deployment and it Just Worked(TM).

It works in helm because helm was able to purge previous pgsql deployment and create the new sts, so the PVC was no longer occupied by the previous deployment.

For dogfood migration, I don't think there's way I can roll the new argo app out and argo can purge previous deployment itself? We have to either scale previous pgsql deployment down to zero or just get rid of them manually (`k delete`.

> If we're doing this anyway, should we just take the opportunity to fix the labeling so that all the kustomization patches aren't required?

We can't patch `matchLabels`, so we need recreate all deploy/sts. Given the current strategy will require a little downtime anyway.

My only concern is if it breaks and we have to rollback, we will have to re-create all deploy/sts to get it working with the current stuff. Maybe we don't care? LOL

**Comment by caugustus-sourcegraph** [comment]
> It works in helm

OH of course I knew there was a reason my brain was like "Hey that's not going to work" but I said it anyway. Thank you for the patient explanation 😆 

> extra downtime

It's up to the devops team but some limited downtime seems very reasonable to me. The dogfood instance is purely for internal use anyway so there's no SLA's here.
