### ISSUE TITLE
Onelogin SSO not working

### ISSUE THREAD

**Issue by DrGonzo65** [sourcegraph/sourcegraph#3218]
- **Sourcegraph version:** 3.2.0
- **Platform information:** Amazon Linux 2
#### Steps to reproduce:

1. Build EC2 instance with terraform as specified in deploy-sourcegraph-aws.
2. Configure OneLogin SSO as described in the docs.

#### Expected behavior:
Onelogin SSO works.
#### Actual behavior:
Error: Unexpected error refreshing SAML authentication provider.

**Comment by DrGonzo65** [comment]
Got it closer. Found that the URL for the metadata was wrong, but now, getting: Error validating SAML assertions.

**Comment by sqs** [comment]
Sorry you are experiencing this issue. Just checking, you configured OneLogin to include the `email` field as mentioned in https://docs.sourcegraph.com/admin/auth/saml_with_onelogin, right?

The `identityProviderMetadataURL` should resemble `https://my-company-name.onelogin.com/saml/metadata/123456`.

Are you using a service provider certificate/private key?

Can you please set the env var `INSECURE_SAML_LOG_TRACES=1` on the `sourcegraph/server` Docker container and post the content here (after scrubbing it of sensitive information)? You can also send it to support@sourcegraph.com if you don't want to post it here.

**Comment by beyang** [comment]
@KattMingMing can you triage this to the appropriate milestone?

**Comment by DrGonzo65** [comment]
metadata url from onelogin looks like: https://app.onelogin.com/saml/metadata/<uuid> (obscured the uuid).

XML metadata contains the x509 and relevant URLs. 

Turning on that log trace now. Where do the logs go? I don't see any config for location.

**Comment by DrGonzo65** [comment]
Confirmed on the email parameter field as well.

**Comment by sqs** [comment]
Thanks. The trace logs go to stderr on the Docker container.

**Comment by DrGonzo65** [comment]
Here's the log:

03:59:21           frontend | ======================================== SAML trace: Identity Provider metadata: https://app.onelogin.com/saml/metadata/2e251ab5-8ea9-4f68-b8ec-a0284177cd5e
03:59:21           frontend | <?xml version="1.0"?>
03:59:21           frontend | <EntityDescriptor xmlns="urn:oasis:names:tc:SAML:2.0:metadata" entityID="https://app.onelogin.com/saml/metadata/2e251ab5-8ea9-4f68-b8ec-a0284177cd5e">
03:59:21           frontend |   <IDPSSODescriptor xmlns:ds="http://www.w3.org/2000/09/xmldsig#" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
03:59:21           frontend |     <KeyDescriptor use="signing">
03:59:21           frontend |       <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
03:59:21           frontend |         <ds:X509Data>
03:59:21           frontend |           <ds:X509Certificate>X509 Redacted</ds:X509Certificate>
03:59:21           frontend |         </ds:X509Data>
03:59:21           frontend |       </ds:KeyInfo>
03:59:21           frontend |     </KeyDescriptor>
03:59:21           frontend |     <SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://company.onelogin.com/trust/saml2/http-redirect/slo/913174"/>
03:59:21           frontend |
03:59:21           frontend |       <NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</NameIDFormat>
03:59:21           frontend |
03:59:21           frontend |     <SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://company.onelogin.com/trust/saml2/http-redirect/sso/913174"/>
03:59:21           frontend |     <SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://company.onelogin.com/trust/saml2/http-post/sso/913174"/>
03:59:21           frontend |     <SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:SOAP" Location="https://company.onelogin.com/trust/saml2/soap/sso/913174"/>
03:59:21           frontend |   </IDPSSODescriptor>
03:59:21           frontend | </EntityDescriptor>
03:59:21           frontend | ================================================================================================================================================
03:59:21           frontend | ======================================== SAML trace: AuthnRequest:
03:59:21           frontend | <samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="_85d28d6b-2636-42a9-b4a4-e31444a930cd" Version="2.0" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" AssertionConsumerServiceURL="https://sg.company.local/.auth/saml/acs" IssueInstant="2019-04-05T03:59:21Z" Destination="https://company.onelogin.com/trust/saml2/http-redirect/sso/913174"><saml:Issuer>https://sg.company.local/.auth/saml/metadata</saml:Issuer><samlp:NameIDPolicy AllowCreate="true" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent"/></samlp:AuthnRequest>
03:59:21           frontend | =======================================================
03:59:22           frontend | ======================================== SAML trace: SAML RelayState
03:59:22           frontend | eyJrIjoiIiwiciI6Ii9zaWduLWluP3JldHVyblRvPSUyRiJ9
03:59:22           frontend | ========================================================
03:59:22           frontend | ======================================== SAML trace: Identity Provider metadata: https://app.onelogin.com/saml/metadata/2e251ab5-8ea9-4f68-b8ec-a0284177cd5e
03:59:22           frontend | <?xml version="1.0"?>
03:59:22           frontend | <EntityDescriptor xmlns="urn:oasis:names:tc:SAML:2.0:metadata" entityID="https://app.onelogin.com/saml/metadata/2e251ab5-8ea9-4f68-b8ec-a0284177cd5e">
03:59:22           frontend |   <IDPSSODescriptor xmlns:ds="http://www.w3.org/2000/09/xmldsig#" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
03:59:22           frontend |     <KeyDescriptor use="signing">
03:59:22           frontend |       <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
03:59:22           frontend |         <ds:X509Data>
03:59:22           frontend |           <ds:X509Certificate>X509 Redacted</ds:X509Certificate>
03:59:22           frontend |         </ds:X509Data>
03:59:22           frontend |       </ds:KeyInfo>
03:59:22           frontend |     </KeyDescriptor>
03:59:22           frontend |     <SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://company.onelogin.com/trust/saml2/http-redirect/slo/913174"/>
03:59:22           frontend |
03:59:22           frontend |       <NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</NameIDFormat>
03:59:22           frontend |
03:59:22           frontend |     <SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://company.onelogin.com/trust/saml2/http-redirect/sso/913174"/>
03:59:22           frontend |     <SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://company.onelogin.com/trust/saml2/http-post/sso/913174"/>
03:59:22           frontend |     <SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:SOAP" Location="https://company.onelogin.com/trust/saml2/soap/sso/913174"/>
03:59:22           frontend |   </IDPSSODescriptor>
03:59:22           frontend | </EntityDescriptor>
03:59:22           frontend | ================================================================================================================================================
03:59:22           frontend | ======================================== SAML trace: AuthnResponse:
03:59:22           frontend | <samlp:Response xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" ID="Rd0c6101f85f4fae6b4a9ec4a6a9cab97f4441239" Version="2.0" IssueInstant="2019-04-05T03:59:21Z" Destination="https://sg.company.local/.auth/saml/acs" InResponseTo="_85d28d6b-2636-42a9-b4a4-e31444a930cd"><saml:Issuer>https://app.onelogin.com/saml/metadata/2e251ab5-8ea9-4f68-b8ec-a0284177cd5e</saml:Issuer><samlp:Status><samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/></samlp:Status><saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Version="2.0" ID="pfxaa91df32-8f06-eecf-4d2b-76e0efe536ce" IssueInstant="2019-04-05T03:59:21Z"><saml:Issuer>https://app.onelogin.com/saml/metadata/2e251ab5-8ea9-4f68-b8ec-a0284177cd5e</saml:Issuer><ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#"><ds:SignedInfo><ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/><ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/><ds:Reference URI="#pfxaa91df32-8f06-eecf-4d2b-76e0efe536ce"><ds:Transforms><ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/></ds:Transforms><ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/><ds:DigestValue>lf6YjxU9RthHwvJrhDAiBnax8TE=</ds:DigestValue></ds:Reference></ds:SignedInfo><ds:SignatureValue>Signature Redacted</ds:SignatureValue><ds:KeyInfo><ds:X509Data><ds:X509Certificate>X509 Redacted</ds:X509Certificate></ds:X509Data></ds:KeyInfo></ds:Signature><saml:Subject><saml:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress">nshortway@company.com</saml:NameID><saml:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer"><saml:SubjectConfirmationData NotOnOrAfter="2019-04-05T04:02:21Z" Recipient="https://sg.company.local/.auth/saml/acs" InResponseTo="_85d28d6b-2636-42a9-b4a4-e31444a930cd"/></saml:SubjectConfirmation></saml:Subject><saml:Conditions NotBefore="2019-04-05T03:56:21Z" NotOnOrAfter="2019-04-05T04:02:21Z"><saml:AudienceRestriction><saml:Audience>https://sg.company.local/.auth/saml/acs</saml:Audience></saml:AudienceRestriction></saml:Conditions><saml:AuthnStatement AuthnInstant="2019-04-05T03:59:20Z" SessionNotOnOrAfter="2019-04-06T03:59:21Z" SessionIndex="_475ab230-394f-0137-ca58-06b0a03d96de"><saml:AuthnContext><saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</saml:AuthnContextClassRef></saml:AuthnContext></saml:AuthnStatement><saml:AttributeStatement><saml:Attribute Name="email" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">nshortway@company.com</saml:AttributeValue></saml:Attribute></saml:AttributeStatement></saml:Assertion></samlp:Response>
03:59:22           frontend | ========================================================
03:59:22           frontend | t=2019-04-05T03:59:22+0000 lvl=eror msg="Error validating SAML assertions. Set the env var INSECURE_SAML_LOG_TRACES=1 to log all SAML requests and responses." err="invalid SAML AuthnResponse: &{OneTimeUse:false ProxyRestriction:<nil> NotInAudience:true InvalidTime:false}"

Certs redacted and company changed.

**Comment by DrGonzo65** [comment]
Fixed. The Audience URL had to be the metadata one, not acs.

**Comment by sqs** [comment]
Thank you for posting the resolution. Reopening for us to figure out how to update docs or make other changes to make this easier.

**Comment by beyang** [comment]
This will be addressed by a "Quick configure" button targeting OneLogin in 3.4: https://github.com/sourcegraph/sourcegraph/pull/3387

**Comment by sqs** [comment]
@beyang Did #3387 actually fix it for OneLogin? I don't see a OneLogin-specific button.

**Comment by beyang** [comment]
It's not in the screenshot, but I added it later: https://github.com/sourcegraph/sourcegraph/pull/3387/files#diff-bc9c8fc7a0c1c52bb78ceded277114e4R168
