### ISSUE TITLE
gitserver: Store repository size in gitserver_repos table

### ISSUE THREAD

**Issue by asdine** [sourcegraph/sourcegraph#32197]
We currently don't have any information about the disk space taken by each repository.
Having this information in the database is a pre-requisite for [RFC 595](https://docs.google.com/document/d/1sZBF6EhFCMu3JTJBIPHP221zhmEDmjZvk_tJdAOS3Eo/edit#) so that we can quickly calculate if shards have enough disk space before running the migration.
The Cloud and Search teams have also expressed interest in this information.

Add a new column to the gitserver_repos table and, every time a repo is cloned or updated, we must update that column with the size of the repository directory on disk.
Note that repos only contain .git directories.

**Comment by asdine** [comment]
It can be done in two different ways:

1/ **Synchronously**: Every time a repo is either cloned / fetched we calculate the new disk size and update the database
  - Pros:
    - Easy to implement
    - Database state is consistent with the state of the disk
  - Cons:
    - Calculating disk space is expensive and slow
    - If multiple repos get cloned at the same time, most of the disk read bandwidth will be consumed by this
 
2/ **Asynchronously**: A background job queries the database and calculates disk space of repos with an outdated `repo_size_bytes` column.
  - Pros:
    - Impact on the node is controlled
  - Cons:
    - Slightly more difficult to implement
    - The database state is eventually consistent
 
Solution 1/ could be improved with a semaphore to control how many disk usage calculations are done concurrently, but this will slow down overall clone and update times drastically.

Solution 2/ Can operate in batches and deal with multiple repos concurrently to reduce the lag.

-------------

For the needs of [RFC 595](https://docs.google.com/document/d/1sZBF6EhFCMu3JTJBIPHP221zhmEDmjZvk_tJdAOS3Eo/edit#), I would go for solution 2/ as we don't necessarily need to be absolutely accurate, we only need to ensure the data is accurate enough (this can be verified by querying the `gitserver_repos` table)

Any opinion @sourcegraph/repo-management @tsenart @rafax ?

**Comment by asdine** [comment]
The gitserver janitor already calculates the size of every repo periodically (every minute by default), so one solution would be to modify the janitor to update the database for every repo.

**Comment by rafax** [comment]
Solution #1 is simpler to implement and reason about, but I don't how big of a problem is the cost to calculate size - is this a problem currently? 
A [naive implementation](https://gist.github.com/rafax/5e3fc23099374340153e239cd3f2d7b8) in Go takes ~10ms to calculate size of Kubernetes / Sourcegraph repos, `git count-objects -vH` is a bit faster.

If we choose #2, can we add a column for when the size was last updated?

**Comment by rafax** [comment]
gitserver janitor is also an option - does it run irrespective of disk pressure?

**Comment by asdine** [comment]
> does it run irrespective of disk pressure? Does it calculate the size of all repos, or ex. only the oldest ones?

Yes for both questions, basically it calculates disk size for every repo and aggregates them.

An easy solution would be to make it update the database for each repo.
Worst case scenario, the database state would be about 1 minute old (or whatever the chosen janitor interval is, provided the job doesn't take more than that interval. Unfortunately there are no metrics that indicate how long it takes to run the janitor job.)

> If we choose #2, can we add a column for when the size was last updated?

Yes, we're gonna need it to measure how far behind we are.

**Comment by asdine** [comment]
> Solution https://github.com/sourcegraph/sourcegraph/issues/1 is simpler to implement and reason about, but I don't how big of a problem is the cost to calculate size - is this a problem currently?

I don't know either. I assumed that it is not cheap on spinning hard drives, especially for customer that have large repos.
Is there a simple way of testing that on Cloud?
If we can afford it, solution 1/ is probably the best.

**Comment by rafax** [comment]
From what you say above, janitor calculates size of all repos every minute, so it sounds size-calculation can't be that big of a problem.

I tried size calculation on the smallest VM supported by GCP (e2-micro), with 10GB spinning disk attached, and it still calculates <10ms for sourcegraph (the VM struggles to check out megarepo).

**Comment by asdine** [comment]
I agree. I will calculate the size synchronously then and we'll monitor the impact on Cloud once it's deployed

**Comment by tsenart** [comment]
Related project from github: https://github.com/github/git-sizer/
