### ISSUE TITLE
insights: modify API to take into account frozen insights

### ISSUE THREAD

**Issue by CristinaBirkel** [sourcegraph/sourcegraph#32190]
1. Add a new field `isFrozen` to the `InsightView` type in the API and make sure it accurately reflects whether or not the insight is frozen, (based on the `is_frozen` field in `insight_view`.) 
2. When returning insights, do not return any `dataSeries` data for frozen insights.
3. Other restrictions on the API based on whether or not the user has a Code Insights license:
    - At the very least, any newly created insights should be automatically created with `is_frozen=TRUE`
    - Consider if it's easy to add in other restrictions, [but if not no big deal.](https://docs.google.com/document/d/1WIInNUMtgOPIeiIONGios2_y67CSkkZr0WtFtU4h_IY/edit?disco=AAAAWcJkJCs)

**Comment by coury-clark** [comment]
I think I would actually expect the API to return a field `isFrozen` and the DB column to either match, or just be called `frozen`. It's a nitpick, but is slightly nonstandard in the Sourcegraph API otherwise.

> Other restrictions on the API based on whether or not the user has a Code Insights license: 

Are you actually proposing this as part of this issue? It isn't clear to me.

**Comment by CristinaBirkel** [comment]
@coury-clark Yeah good callout, I'll make the API field `isFrozen` in that case. (Changed in the issue description.)

As far as other restrictions, yes I am proposing at the very least that we make sure any insights created while in limited access mode have `is_frozen=TRUE`. And to also consider how easy it would be to add other restrictions, (with low priority, if it's complicated at all.)

**Comment by coury-clark** [comment]
My suggestion would be to separate that into another issue, so that we can close the MVP quickly. Otherwise looks good!

**Comment by coury-clark** [comment]
@CristinaBirkel So if we are going to do the work to check and limit API access based on license, why are we allowing the API request at all? In the case of no license, why aren't we just outright denying them, rather than creating them in a frozen state?

**Comment by CristinaBirkel** [comment]
@coury-clark Hmm, good question! I think we do need to allow them to create a global insight if they have < 2 global insights. But I think you're right that it's perhaps easier to reject the API call than it is to create a frozen insight. And maybe more user-friendly too?

**Comment by coury-clark** [comment]
I'm going to separate these limitations into a new issue, so we can merge the MVP quickly.
