### ISSUE TITLE
Helm: internal training resources

### ISSUE THREAD

**Issue by caugustus-sourcegraph** [sourcegraph/sourcegraph#32206]
TBD: What sort of additional resources would CE/CS need to supplement what has already been produced?

Existing resources:
- https://www.loom.com/team-videos/Helm
- https://github.com/sourcegraph/customer-helm-demo

WIP resources:
- https://github.com/sourcegraph/sourcegraph/blob/03-10-doc_add_helm_docs/doc/admin/install/kubernetes/helm.md

**Comment by michaellzc** [comment]
close in favor https://handbook.sourcegraph.com/departments/product-engineering/engineering/cloud/delivery/deployment/helm/
