### ISSUE TITLE
search: Allow files matching a pattern to be skipped in Zoekt indexing

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#32257]
In package repos, but also elsewhere, it's common to have minified JS bundles which are not worth to index or search. We should provide a way to skip files matching a pattern during indexing.

![image](https://user-images.githubusercontent.com/67471/157033068-89b307b2-cc13-4ee9-8b70-faf04f071450.png)

**Comment by olafurpg** [comment]
Thank you for opening this issue! Relatedly, it feels a bit unreliable/non-deterministic whether these auto-generated files get indexed or not. For example, users in a small repo may get used to the fact that Sourcegraph indexes `yarn.lock` and then one day day the `yarn.lock` grows to exceed the maximum size limit and Sourcegraph will silently skip indexing that file. Maybe it's better to not index that file from the start to avoid giving the impression that yarn.lock is always indexed.

**Comment by ggilmore** [comment]
We do support a `sourcegraph/ignore`  file that will prevent some files from being indexed, but that relies on the user actually committing that file to the repo. I'd imagine we'd want some default ignore patterns that don't require configuration?

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket, please let us know how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
