### ISSUE TITLE
Update to 3.2.0 issue (Bad file format reading the append only file...)

### ISSUE THREAD

**Issue by techman84** [sourcegraph/sourcegraph#3226]
- **Sourcegraph version:**  3.1.1 (wanted to update to 3.2.0)
- **Platform information:**  Windows 10 Pro - Docker version 18.03.0-ce

#### Steps to reproduce:
I had Sourcegraph v.3.1.1 installed with data stored in a volume named `sourcegraph-data-volume`.
I wanted to update it to the v.3.2.0, so I used with this command:
```
docker run --restart always --publish 7080:7080 --publish 2633:2633 --volume ~/.sourcegraph/config:/etc/sourcegraph --volume sourcegraph-data-volume:/var/opt/sourcegraph sourcegraph/server:3.2.0
```

#### Expected behavior:
Sourcegraph update to the v.3.2.0 and reattach the data volume `sourcegraph-data-volume`

#### Actual behavior:
The command produces this error:
```
docker run --restart always --publish 7080:7080 --publish 2633:2633 --volume
~/.sourcegraph/config:/etc/sourcegraph --volume sourcegraph-data-volume:/var/op
t/sourcegraph sourcegraph/server:3.2.0
15:13:58     syntect_server | Configured for production.
15:13:58           postgres | 2019-04-04 15:13:58.630 UTC [50] LOG:  listening on IPv4 address "127.0.0.1", port 5432
15:13:59 management-console | t=2019-04-04T15:13:59+0000 lvl=info msg="management-console: listening" addr=:2633
15:13:59 management-console | 2019/04/04 15:13:59 Generating and using self-signed TLS cert/key
15:14:07              redis | 80:M 04 Apr 15:14:07.083 # Bad file format reading the append only file: make a backup of your AOF file, then use ./redis-check-aof --fix <filename>
15:14:07              redis | Terminating redis
redis died. Shutting down...
15:14:07     syntect_server | Terminating syntect_server
15:14:07  zoekt-indexserver | Terminating zoekt-indexserver
15:14:07    zoekt-webserver | Terminating zoekt-webserver
15:14:07              nginx | Terminating nginx
15:14:07          gitserver | Terminating gitserver
15:14:07       github-proxy | Terminating github-proxy
15:14:07           searcher | Terminating searcher
15:14:07            symbols | Terminating symbols
15:14:07       repo-updater | Terminating repo-updater
15:14:07       query-runner | Terminating query-runner
15:14:07 management-console | Terminating management-console
15:14:07           frontend | Terminating frontend
15:14:07           postgres | Terminating postgres
```

**Comment by slimsag** [comment]
Hi, can you try running:

```
docker exec -it CONTAINER_ID redis-check-aof --fix /var/opt/sourcegraph/redis/appendonly.aof
```

Where `CONTAINER_ID` is the ID of the container shown by `docker ps` on the system

**Comment by techman84** [comment]
I tried executing the command, then restarted the container. But Sourcegraph is still offline with a "502 Bad Gateway". Any other operations to do after executing the fix command? Thanks.

**Comment by sqs** [comment]
@techman84 Sorry that didn't work. Any luck or other attempts since? Are you still seeing the same error?

**Comment by techman84** [comment]
Hi @sqs. Unfortunately the same error.
If there's no way to get a solution, I'll re-install a new copy from scratch.

**Comment by sqs** [comment]
We plan to look into this, but not in the next few days, unfortunately. Can you please try installing a new copy from scratch and seeing if that works?

cc @sourcegraph/core-services Is this the same as https://github.com/sourcegraph/sourcegraph/issues/651? If so, can you please merge the issues?

**Comment by keegancsmith** [comment]
> @sourcegraph/core-services Is this the same as #651? If so, can you please merge the issues?

I'll leave it to @tsenart to comment. I haven't investigated the redis stuff enough yet to know.

**Comment by tsenart** [comment]
Seems like it's the same issue as #651. Closing.
