### ISSUE TITLE
Run A/B test for a more compact CTA design

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#32288]
## Context
We have CTAs on the "search" and "file" pages.
We have three types right now: 1. "Sign up!", 2. "Download browser extensions!", 3. "Download IDE extensions!".
We'll only deal with 2. and 3. in this issue.

## Problem
We got some feedback on the CTAs being a bit obtrusive.

## Solution
We want to try using smaller CTAs.
The current ones have pretty good conversion rates, so we don't want to go all in for smaller CTAs at this point, but rather, set up and A/B test, and see how the small ones convert vs the larger ones, and how user feedback compares.

Here is the [Figma](https://www.figma.com/file/VlpvIoBXrG6GFWsEFmc6rB/Browser-extension-CTA-improvements?node-id=204%3A9486) for the new design.

**Comment by vdavid** [comment]
@philipp-spiess I've assigned this one to you as we agreed, but I'd like to note that this one has a lower priority based on our conversation with @rrhyne and @ryankscott. Please work with Rob and Ryan to prioritize this one against other backlog items.

**Comment by ryankscott** [comment]
Have we considered putting this right at the top or bottom of the window? That tends to be convention for these sorts of things as it's less obtrusive and can be made visually different to the rest of the product.
