### ISSUE TITLE
insights: remove the GA announcement modal from 3.38

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#32285]
We should remove the GA modal so it only fires to new 3.37 users and is not a part of 3.38. If you immediately upgrade past 3.37 (say, from 3.35 to 3.38) you will never see this modal, but that is okay, because: 

1. Our docs, landing pages, announcement blog, and changelog will all indicate code insights is GA 
2. Part of the reason we needed a modal was to cover ourselves for folks who upgraded before we announced GA and saw the product labels change (good thing we did, since that announcement got pushed back). 

So this task is: 
1. Remove the GA modal so it only fires if you are on 3.37 (and have no license tag, etc.) 

This will be replaced with a limited access modal in 3.38.

**Comment by unclejustin** [comment]
Duplicate
