### ISSUE TITLE
At narrow widths, the global navbar omits the username, etc.

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#323]
- **Sourcegraph version:** master and sourcegraph.com

#### Steps to reproduce:

1. Go to https://sourcegraph.com or localhost:3080 on master
2. Make your browser window somewhat narrow

![screenshot from 2018-10-05 21-50-56](https://user-images.githubusercontent.com/1976/46567508-e5e8b080-c8e8-11e8-9044-9d9cc13d0542.png)

#### Expected behavior:

Still able to access user profile and other global navbar links

#### Actual behavior:

Unable to access them

**Comment by francisschmaltz** [comment]
This happened because the homepage needs to hide these elements on mobile. I incorrectly added css to hide them on small viewports. I've moved this to the body container class for the start page.

Address in https://github.com/sourcegraph/sourcegraph/pull/326

**Comment by francisschmaltz** [comment]
@felixfbecker reviews and created second PR and merged https://github.com/sourcegraph/sourcegraph/pull/329/

**Comment by sqs** [comment]
This is occurring again for me on iOS Safari:

![fcf7abf6-d555-4cc9-a1d4-d5615a184e95](https://user-images.githubusercontent.com/1976/47128552-8a9eb280-d246-11e8-8a4d-a261544ebddb.png)

**Comment by francisschmaltz** [comment]
This is intentional on /start on mobile

**Comment by francisschmaltz** [comment]
When we have a mobile ready app we should add a sign in button, but until then the app should be hidden due to the bad experience. You can still get to it at /search

**Comment by sqs** [comment]
It felt like a bug to me to not have that visible, and I didn't know it was available at `/search`. I think it should be shown even though the app is not mobile ready, or at least give the user some way to know that going to `/search`  would result in it being shown.

**Comment by francisschmaltz** [comment]
This issue has been resolved.
