### ISSUE TITLE
src CLI tool & GraphQL API stability: High-value low-effort work

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#3231]
There are some problems with the `src` CLI tool that we could resolve that are low-effort and would give our users large gains. Specifically:

1. It is currently impossible to know which version of the `src` tool is needed for your Sourcegraph version. The latest version of the tool works in the latest version of Sourcegraph, but aside from that you are on your own to figure out which version of `src` corresponds to which version of Sourcegraph.

2. The `src` tool is broken often due to changes in our GraphQL API. CI on the `src` tool only runs when people send PRs to it, so we don't notice these breakages. We only guarantee GraphQL API stability on a single version of Sourcegraph.. but this is a signal that what we're doing today doesn't work (if we can't keep our own tool up to date with GraphQL API changes, how on earth would a customer do so?)

Solutions:

1. When we build the Sourcegraph release docker images, have our CI identify what the latest version on https://github.com/sourcegraph/src-cli/releases is. Then have the app redirect requests to e.g. https://sourcegraph.example.com/src-cli/src_darwin_amd64 to the github releases download. This way, it is always easily possible to grab a version of `src` compatible with your Sourcegraph version. Then we can update the src-cli README to reflect this.

2. Keep ourselves honest about GraphQL changes: We don't do enough today. We are supposed to document breaking changes here between releases, but many slip through the cracks. This is more important for customers than it is for the `src` tool (which just acts as a test bed for keeping us honest). The way we can do this is by running the `src-cli` test suite as part of CI in this repo (i.e. clone that repo, run `src` tests against this Sourcegraph instance the same way we do e2e tests).

**Comment by felixfbecker** [comment]
👏 to both solutions.

**Comment by tsenart** [comment]
With @sqs's work on `src-cli` in the context of automation, this works gains additional importance.

**Comment by efritz** [comment]
Implemented in #7600.

**Comment by slimsag** [comment]
It doesn't look to me like the 2nd testing point was done?

**Comment by malomarrec** [comment]
This ticket has been inactive for a while, and after checking in internally it appears to be outdated. Closing.
If you come across this and think this ticket shouldn't have been close, please reopen and leave a comment so that we can reconsider it!
