### ISSUE TITLE
gitserver: Add support for repository pinning

### ISSUE THREAD

**Issue by asdine** [sourcegraph/sourcegraph#32319]
Add a configuration variable that allows admins to pin one or more repos to a particular gitserver instance.
Ensure that gitserver clients and the gitserver janitor always read that config first to determine which instance to query.

Related to [RFC 595](https://docs.google.com/document/d/1sZBF6EhFCMu3JTJBIPHP221zhmEDmjZvk_tJdAOS3Eo/edit#heading=h.trqab8y0kufp)

**Comment by ryanslade** [comment]
What is the status of this? I know we started some work on pinning but I don't think it's been completed, is that correct?

No problem if it's not being worked on right now, but if that's the case can we move it to a different column in the repo management project?

**Comment by asdine** [comment]
@ryanslade actually I think we can close this, as it has already been done by @vrto in this [PR](https://github.com/sourcegraph/sourcegraph/pull/32831).
