### ISSUE TITLE
"View repository on Sourcegraph" button will always show if repo exists on sourcegraph.com, but then link to configured instance (where it 404s)

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#3232]
`resolveRev()` is used by the "view repo on sourcegraph" button to check for the repos existence. However, `resolveRev()` calls into `queryGraphQL()`, which has logic to retry the requests automatically on sourcegraph.com if it fails on the configured instance.
This low-level magic retry logic is dangerous - if the repo is on a different instance, we need to explicitly detect that early on, then pass the instance URL of that repo around so we don't retry all the time.

**Comment by lguychard** [comment]
I _think_ avoiding bugs like this may have been the idea behind the [`repoUrlCache`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/browser/src/shared/util/context.tsx#L19:14&tab=references)

But indeed the best path forward to fix this is probably #3233 - and then nuke the `repoUrlCache` logic in the process.

**Comment by lguychard** [comment]
Fixed by https://github.com/sourcegraph/sourcegraph/pull/3292
