### ISSUE TITLE
New reference panel: avoid 10s+ loading times for 100 references

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#32328]
It can sometimes take 10s+ or 30s+ to load the reference panel. Seems to be related to how many cross-repo references/implementations there are.

Example trace: [https://sourcegraph.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud[…]ge%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D](https://sourcegraph.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-sourcegraph-traces%22,%22queries%22:%5B%7B%22query%22:%2202a643c05e5d7f63%22,%22queryType%22:%22traceId%22,%22refId%22:%22A%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D)

Multiple options:

1. Make the backend faster
2. Do not load 100 references/implementations on first load, but load, say, 10, and then in the background fetch more in batches of 10

**Comment by efritz** [comment]
The dominating time here is trying to find the relevant indexes to search in. Paging smaller chunks won't make this faster as we have to do the same amount of work to find the _next_ result in the first place.

**Comment by efritz** [comment]
Not if the first result is always `n` false positives in the bloom filter away.

**Comment by efritz** [comment]
Batch log helped profile. Current effort is now in https://github.com/sourcegraph/sourcegraph/pull/33737, which adds a way to configure the batch size (previously hard-coded) of cross-index navigation queries. We can configure this variable higher on cloud to see the impact it has on cross-repo find refs.
