### ISSUE TITLE
SSBC: Integrate "Create" form into 4-step layout as step 1: Configuration

### ISSUE THREAD

**Issue by courier-new** [sourcegraph/sourcegraph#32337]
We resolved in [these designs](https://www.figma.com/file/cTKjwbvWqU6xAykZmCTTqy/SSBC?node-id=2080%3A67535) to clarify the "Create" form for a batch change by integrating it into the now-4-step layout under the new name "Configuration."

Scope of this issue includes:
- Integrating "Create" form into 4-step layout
  - No actions section (e.g. "Run batch spec" button) should be present
  - Steps 2-4 should be disabled until batch change is configured and created
- Aliasing new URL path `batch-changes/<name>/executions/<id>/configuration` to read-only version of configuration (editing configuration is a separate issue)

NOTE: We should wait to begin work on this issue until ["Incorporate editor into actual stage 1 of execution page"](https://github.com/sourcegraph/sourcegraph/issues/33395) is completed first, or else reverse the order and wait to work on that one until this one is complete.

**Comment by courier-new** [comment]
@eseliger I know we talked about some ideas for this when we were polishing the "Create" form. Would you be able to recall that conversation and maybe add a bit of definition to this ticket? I can't remember what all we were suggesting.

**Comment by eseliger** [comment]
I think my ambition was to make it really fancy and clear what you are doing here, but in the end I think we agreed on just adding a descriptive sentence below the header 😆 It's somewhere in the Figma jungle 👀

**Comment by courier-new** [comment]
Oh found it! Turns out we hadn't expressly settled on one option or another maybe?
https://www.figma.com/file/cTKjwbvWqU6xAykZmCTTqy/?node-id=2080%3A67535

**Comment by courier-new** [comment]
Updating this ticket given our design decisions. Given the changes in scope (from update some text and design on the form to changing how the form integrates into the workflow), I'm also updating the estimate.

**Comment by courier-new** [comment]
I'm also going to bump this to the next EM, given we're most of the way through the current one.

**Comment by danielmarquespt** [comment]
> For the configuration step, the Run specification button shouldn't be displayed, as the batch change hasn't been created yet so we can't run a specification.

I think you are right. It was a probably a copy paste done wrong.

> The header information seem to change when we get to to the Batch specification step, I added two screenshots below:

I think the new change makes the header static. So I think we are removing the namespace from the header and just keep "Create Batch Change". 

Right @rrhyne ?

> Does the URL schema for the 4 steps differ from what we currently have?

I'm not seeing any advantages of changing the schema. So lets keep it as is?

> Lastly, we have a tab navigation for the read-only spec page, do we want to hide the tab created for the Create Batch Change flow when the batch spec is in read-only mode.

Need help on this one @rrhyne 😆

**Comment by eseliger** [comment]
I think the URL should be in line with what you listed there: `/users/<namespace_user_id>/batch-changes/<batch_change_name>/configuration`.
