### ISSUE TITLE
Go language intelligence is wrong because of basic code intelligence

### ISSUE THREAD

**Issue by ijsnow** [sourcegraph/sourcegraph#3234]
- **Sourcegraph version:** sourcegraph.com
- **Platform information:** MacOS Firefox

#### Steps to reproduce:

1. Go to https://sourcegraph.sgdev.org/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/shared/frontend.go#L19:13
2. Note that the docs string is for the `Main` function we are currently in, not `cli.Main`
2. Click "Go to definition"

#### Expected behavior:

Go to definition of `cli.Main` and show correct docs string.

#### Actual behavior:

Go to the `Main` function this token is in.

![Screen Recording 2019-04-04 at 02 50 PM](https://user-images.githubusercontent.com/11557758/55590908-17500680-56e9-11e9-882d-ab25d9d38674.gif)

**Comment by chrismwendt** [comment]
Ah, this happens because there's a definition by the same name in the current file, and basic code intel returns early in that case.

I'm going to change it so that it searches the whole repo to begin with.

**Comment by chrismwendt** [comment]
Oh, and we don't have the Go language server running on sgdev (your link).
