### ISSUE TITLE
search: Refine text of repo:deps snippet

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#32348]
We want to expose the repo:deps(...) option in the repo typeahead suggestions. Ideally, we'd add some text indicating it only works for NPM/Maven(?) for now, and that's is a Beta feature. Something like this:
![image](https://user-images.githubusercontent.com/4605817/157303715-14b4c3f7-dee0-4cbe-8c44-4e5eae701064.png)

**Comment by benvenker** [comment]
cc @tsenart  @novoselrok and @olafurpg something like this is what I was thinking here based on our discussion today.

**Comment by tsenart** [comment]
I'm not sure if the BETA label is easy, but changing the text of the existing snippet is. @novoselrok: Thoughts on the label?
