### ISSUE TITLE
SSBC: Show status pill on "Executions" tab with active executions

### ISSUE THREAD

**Issue by courier-new** [sourcegraph/sourcegraph#32341]
If any executions are actively happening on a batch change, show pill with count from BC page "Executions" tab.
Figma: https://www.figma.com/file/cTKjwbvWqU6xAykZmCTTqy/SSBC?node-id=1485%3A53103

**Comment by adeola-ak** [comment]
Hi Kelli!
 
I just took a look and these are the states I see for a batch spec, 

PENDING = 'PENDING',
PROCESSING = 'PROCESSING',
FAILED = 'FAILED',
COMPLETED = 'COMPLETED',
QUEUED = 'QUEUED',
CANCELING = 'CANCELING',
CANCELED = 'CANCELED',

So do I only want to show the badge with the count of batch specs that are in a state of PROCESSING?

**Comment by courier-new** [comment]
Great question! I think we could also count `QUEUED`. On the list page, the `BatchChangeStatePill` will show the "executing" secondary status (screenshot below) if the latest batch spec is either in the `QUEUED` or `PROCESSING` state ([here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@kr/temporary-settings-bc-list-filters/-/blob/client/web/src/enterprise/batches/list/BatchChangeStatePill.tsx?L99%3A9-100%3A36=) in code), so it would make sense to me to match that.

![image](https://user-images.githubusercontent.com/8942601/159080993-80e954d6-2dc8-4e88-9317-cf8824fe1d81.png)

**Comment by adeola-ak** [comment]
thank you! just made a PR
