### ISSUE TITLE
Does sourcegraph-zoekt-indexserver ever.. stop indexing?

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#3235]
It seems like sourcegraph-zoekt-indexserver, according to the code, will always index repositories even if the commits that would be indexed have already been indexed.

- The only usage of `indexedCommit`, effectively, is to prioritize already-indexed repositories lower in the queue of repositories to index -- but nothing ever ignores them: https://sourcegraph.com/github.com/sourcegraph/zoekt/-/blob/cmd/zoekt-sourcegraph-indexserver/queue.go#L123
- So `queue.Pop()` returns repositories that are already indexed: https://sourcegraph.com/github.com/sourcegraph/zoekt/-/blob/cmd/zoekt-sourcegraph-indexserver/main.go#L123
- And then we index them anyway: https://sourcegraph.com/github.com/sourcegraph/zoekt/-/blob/cmd/zoekt-sourcegraph-indexserver/main.go#L129

If true, we would be wasting a lot of resources once we have indexed all repositories on an instance, no?

**Comment by keegancsmith** [comment]
`-incremental` is the important flag https://sourcegraph.com/github.com/sourcegraph/zoekt/-/blob/cmd/zoekt-sourcegraph-indexserver/main.go#L153 

The command we shell out to inspects the shards it has indexed and the command line arguments. If we have incremental enabled and the shards reflect the command line arguments it is a noop.
