### ISSUE TITLE
Code Insights: Use wildcard popup instead of native confirmation modal for insight operation confirmation step

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#32374]
Follow up for the https://github.com/sourcegraph/sourcegraph/pull/32327

## Context 

> I think we should stop using the browser confirmation modal.
It looks like an error -- both for removing and deleting

c @AlicjaSuska 

At the moment we use `window.confirm` UI for the removing and deleting insights. We should use a proper wildcard UI for this step instead of a native browser UI regarding Alicja feedback.

**Comment by unclejustin** [comment]
@AlicjaSuska I have a quick question about displaying the popover. [Here's a loom](https://www.loom.com/share/331c6edb876747c9b2b81c97d3acb418) with some details.

**Comment by AlicjaSuska** [comment]
Summary of our yesterday's call with @unclejustin:
- modal in the center of the screen looks good
- primary button should be red and have a more descriptive label ('Delete insight' / 'Remove insight' / 'Delete dashboard')
- more vertical spacing between the header and the body text (24px)
- change the header color to red ($danger-01)
- - copy for 'delete dashboard' popup (approved in past [designs](https://www.figma.com/file/g5lSlPBnHt00wCogjRFnt5/RFC-398%3A-Easily-Viewing-and-Sharing-Code-Insights?node-id=1450%3A12630) for RFC 398: Easily viewing and sharing code insights):

Header: 'Delete ‘[dashboard name]’?
Body: 'This can't be undone. You will still be able to access insights from this dashboard in "All insights”.'
Buttons: Cancel / Delete forever
