### ISSUE TITLE
[Accessibility]: `mdi-react` currently doesn't support adding correct accessibility attributes to SVG icons

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#32379]
### Problem description

We need to provide a `<title>` within the SVG and link that to the root SVG element using `aria-labelledby`.

This is currently not supported by [mdi-react](https://www.npmjs.com/package/@mdi/react), however it is supported by a different library [@mdi/react](https://www.npmjs.com/package/@mdi/react) which seems to be more actively used and is maintained by a Material Design contributor.

We should investigate if we can use `@mdi/react` and, if so, migrate fully to using it to ensure we can use accessible SVGs.

### Expected behavior

We are able to insert a `<title>` element into our material design icons and label it using `aria-labelledby`.

We can test this by using a screen reader and expecting the title to be read out on hover.

**Comment by umpox** [comment]
I've investigating if we can migrate to using this library. Migration can be done by GitStart if so.

**Comment by valerybugakov** [comment]
Closing this issue because the migration was completed here: #34582
Let me know if we need to reopen it @umpox!
