### ISSUE TITLE
Kubernetes not found on sourcegraph.com

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#3237]
From https://twitter.com/ahmetb/status/1113954726020653056

**Comment by nicksnyder** [comment]
Related to https://github.com/sourcegraph/sourcegraph/issues/2773 ?

**Comment by KattMingMing** [comment]
Also looks related to https://github.com/sourcegraph/sourcegraph/issues/2947

**Comment by keegancsmith** [comment]
Duplicate of #2773
