### ISSUE TITLE
sg: update prompt is almost always present

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#32399]
Original [Slack Thread](https://sourcegraph.slack.com/archives/C01N83PS4TU/p1646844766873049) 

@leonore said: 

> quick feedback- when running sg update  the HEY! New version of sg available. Run 'sg update' to install it.  banner will still display, which seems kinda redundant

**Comment by bobheadxi** [comment]
This has been resolved by auto-updates https://github.com/sourcegraph/sourcegraph/pull/33132
