### ISSUE TITLE
ci: kubectl wait errors out before resources exist

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#32403]
Looks like the pods weren't created in time for a `kubectl` command, so the command threw an error

![CleanShot 2022-03-09 at 11 40 53@2x](https://user-images.githubusercontent.com/1387653/157512394-77058930-6978-4d9b-8187-da08c47086c0.png)

I retried and it passed.

From [Slack](https://sourcegraph.slack.com/archives/C02FLQDD3TQ/p1646851154834029)

**Comment by bobheadxi** [comment]
cc @davejrt I think this is related to the investigation you were doing into the cluster tests
