### ISSUE TITLE
Remove GitHub "server banners"?

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#3241]
They have been behind an off-by-default feature flag for over 8 months and were only implemented for GitHub: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@bext-styling-overhaul/-/blob/client/browser/src/libs/github/inject.tsx#L22:22

@sqs?

**Comment by sqs** [comment]
Yes, remove. We will probably add back at some point but not worth keeping the current code paths in.
