### ISSUE TITLE
pr-auditor: unable to set status on PRs from forks

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#32427]
I don't think this is particularly urgent - once PRs get merged, if anything is missing an audit trail issue will still be created.

The issue is setting commit statuses on PRs from forks, i.e. external contributors - the check does run (see check logs), but for whatever reason GitHub doesn't allow you to set the status on commits on forks 😬

> preMergeAudit: CreateStatus: POST [api.github.com/repos/sourcegraph/sourcegraph/statuses/96ae789554c724890663518d83cc8b895aacc0a9:](https://api.github.com/repos/sourcegraph/sourcegraph/statuses/96ae789554c724890663518d83cc8b895aacc0a9:) 403 Resource not accessible by integration []

We could use run output, but this doesn't work for us because we use the pull request events so that we get the pull request payload in the event - subsequent pushes will look "green" when it is not. We can run on push, but that doesn't include the PR payload, necessitating extra API requests to perform the PR description check

See various things I've tried:

- https://github.com/sourcegraph/sourcegraph/pull/32421
- https://github.com/sourcegraph/sourcegraph/pull/31946#issuecomment-1054550210
- https://github.com/sourcegraph/sourcegraph/pull/32423

**Comment by keegancsmith** [comment]
Is there something we can do to skip the step from running when its on a fork just to avoid the red signal we must avoid?

**Comment by keegancsmith** [comment]
It seems this is a required step, so now I can't merge this contribution. See this PR https://github.com/sourcegraph/sourcegraph/pull/35360 @bobheadxi @jhchabran is there some workaround here?
