### ISSUE TITLE
release: automatically notify customer support when cutting a patch

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#32448]
From [RFC 612](https://docs.google.com/document/d/1Gecnsk4mnmf_p9SO4ExICSTC_op-eL2I_kwutHvwSmU/edit#bookmark=id.aax1bwn43p7s) we have decided to include a step to notify support when a patch is cut. It would be useful if this could be automatically included in the release tooling, so that this step is never forgotten or accidentally skipped.

**Comment by bobheadxi** [comment]
I think we can just cc customer support in Slack on the proposed release cut message from https://github.com/sourcegraph/sourcegraph/issues/31737#issuecomment-1158094007
