### ISSUE TITLE
JetBrains plugin customer interviews

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#32454]
TBD

**Comment by vdavid** [comment]
Feel free to also use [this list](https://docs.google.com/spreadsheets/d/1Dj0Di4eoiGMBSBUXECjiI5HzeAsHXC-4fxo5xXdCrX8/edit#gid=0) for the customer interviews @jjinnii @ryankscott (original issue: https://github.com/sourcegraph/sourcegraph/issues/31863#issuecomment-1052662572)
