### ISSUE TITLE
Sourcegraph extensions feature audit 

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#32452]
[Sourcegraph extensions feature audit](https://docs.google.com/document/d/1ISsNzuVdguZtMTNLm1csr-ratjNGIMdmiH0CGa1cCzA/edit#heading=h.trqab8y0kufp)

- [x] @tjkandala to add names of people to reach out to for each extension
- [x] @tjkandala to add brief information on core functionality
- [ ] @ryankscott @jjinnii to reach out to SMEs and fill out document

**Comment by tjkandala** [comment]
@jjinnii @ryankscott I've listen SMEs and features for each extension on the list

**Comment by jjinnii** [comment]
Thanks TJ!

**Comment by ryankscott** [comment]
Closing this based on the sunset.
