### ISSUE TITLE
Add src login to `src-cli` help

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#32450]
## Expected behaviour

Running `src` or `src -h` tells me about `login`

`src login checks that the SRC_ENDPOINT and SRC_TOKEN are appropriately set`

## Actual bebaviour

Running `src` or `src -h` does not mention the `login` command

<img width="1373" alt="image" src="https://user-images.githubusercontent.com/25070988/157695996-a4c74590-73c9-4be7-a0b2-d038b3a862d8.png">

**Comment by northyg** [comment]
Hi @malomarrec 👋 I have PR to add the `login` command. I also re-ordered the list to be alphabetical. Let me know if you would like to keep that change, thanks!
