### ISSUE TITLE
Search sidebar adds duplicate filters when alias is used

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#32465]
When a revision from the search sidebar is selected and a query contains `r:asdf`, `repo:asdf` is added to the query as well.

[This function accepts `FilterType | keyof typeof AliasedFilterType`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/shared/src/search/query/validate.ts?L50%3A8=) but then it doesn't check for this.

**Comment by camdencheek** [comment]
Closing as irrelevant since this functionality no longer exists in the same form.
