### ISSUE TITLE
Implement auth provider for Gerrit

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#32494]
Follow the steps defined [here](https://handbook.sourcegraph.com/departments/product-engineering/engineering/enablement/repo-management/support-new-code-host/#extra-steps-if-permissions-syncing-is-required)

The following issues need to be completed first:

* https://github.com/sourcegraph/sourcegraph/issues/32493
* https://github.com/sourcegraph/sourcegraph/issues/32495

**Comment by mollylogue** [comment]
This is a pretty large task and should likely be broken down a lot. Here are the pieces I can think of:
- Stub out the Provider interface & implement easy methods
- One task/PR each for the functions FetchAccount, FetchUserPerms, FetchRepoPerms
- Add the auth section for Gerrit in the config and initialize the auth provider
- Pull in sub-repo permissions

I'm going to start at the top and work my way down this list.

**Comment by jplahn** [comment]
Can you create issues for each sub-task, create rough estimates, and link them back into the tracking issue?

**Comment by mollylogue** [comment]
> Can you create issues for each sub-task, create rough estimates, and link them back into the tracking issue?

Will do. I'll likely wait until after @varsanojidan and I sync up (tomorrow morning) to ensure this is the right list of tasks.

**Comment by mrnugget** [comment]
Implemented as part of https://github.com/sourcegraph/pr-faqs/issues/41
