### ISSUE TITLE
Spike: Investigate branch based permissions

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#32490]
Some code hosts, for example Gerrit, use branch based permissions.

We should investigate the scope of work required to extend sub-repo permissions
to support this.

We'll need to audit all the places where we currently check sub-repo permissions and
confirm the work required to add branch information there if we don't already have it.

Looking at [all the places where we use RepoContent](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+RepoContent&patternType=literal) is a good start.

We also need to spec out the changes required to the `sub_repo_permissions` table.

**Comment by mrnugget** [comment]
Made outdated as part of https://github.com/sourcegraph/pr-faqs/issues/41
