### ISSUE TITLE
gitserver: Not propogating traces

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#3253]
While debugging a customer issue I noticed we did not have any gitserver traces. This is the same for sourcegraph.com

**Comment by beyang** [comment]
Is there any other logging we could add that would elucidate what the issue was with $CUSTOMER? Like printing out the error on the frontend graphqlbackend handler?

**Comment by keegancsmith** [comment]
> Is there any other logging we could add that would elucidate what the issue was with $CUSTOMER? Like printing out the error on the frontend graphqlbackend handler?

I'm looking into that now.
