### ISSUE TITLE
Add docs to override `postgres.conf` for pure-docker deployment method

### ISSUE THREAD

**Issue by michaellzc** [sourcegraph/sourcegraph#32565]
## Context

A customer database is not working as expected and we have to tune some pg config.

Learn more https://github.com/sourcegraph/customer/issues/754

## Implementation

Consider document it here https://docs.sourcegraph.com/admin/config/postgres-conf

**Comment by virginiaulrich** [comment]
Agreed in planning that since this deployment method was legacy, we wouldn't want to create a document for all customers, and all Netflix work happened on the customer-specific ticket
