### ISSUE TITLE
search: add endpoint returning top N recent queries

### ISSUE THREAD

**Issue by ijt** [sourcegraph/sourcegraph#3256]
There should be an endpoint in graphqlbackend that returns something like this:
```
select query, count(*) from recent_searches group by query order by count desc limit 100;
```

**Comment by ijt** [comment]
cc @KattMingMing

**Comment by ijt** [comment]
This will enable realistic benchmarking and finding out if new configurations, such as enabling indexing, cause problems for common queries.

**Comment by KattMingMing** [comment]
This would be great and it's something that our users and customers also have expressed interest in. More specifics below:

Exposing the `recent_searches` table to the frontend would be useful for site admins and individual users.

**Site admin benefits**
Site admins can use the `recent_searches` to quickly test performance of their instance. As a new admin, I would want to understand how performant my Sourcegraph instance is and if it needs additional resources. A quick way to do this would be to use the  `src-cli`:
- Query `recent_searches` via GraphQL endpoint
- Iterate over the results and execute a search for each result
- Measure performance
    - Diagnosing problems and understanding the current performance against our benchmarks. Something like Google's lighthouse: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fsourcegraph.com&tab=desktop

Site admins might also want to know how users are using the instance.

- This can provide audit log like functionality should the table also include the ID of users.
- Understand if there are certain searches that are common and use that information to create `repogroups`, saved searches, or other search presets.

**Individual user benefits**
If the `recent_searches` can be queried at the individual user level, this would provide an easy way for a user to see their search history.
- Access previous searches quickly
    - Users may forget to save a search query or jump immediately to the result.
    - Reducing the time to see search results would also reduce friction to sharing Sourcegraph links. 
    - Similar value to symbol history

**Comment by ijsnow** [comment]
I added this as a stretch goal for 3.3 in the tracking issue.

**Comment by ijt** [comment]
@ijsnow is busy with #1624. Grabbing this since we need it to get more confidence that a deployment won't crash when indexing is turned on.
