### ISSUE TITLE
Configure sample log pipeline on DataDog

### ISSUE THREAD

**Issue by sanderginn** [sourcegraph/sourcegraph#32568]
In order for the teams involved in reviewing DataDog adoption a properly configured log pipeline helps to determine the added value. Zoekt will serve as the log source for this ticket (`zoekt-webserver` & `zoekt-indexserver`).

Todo: 
- [ ] Refactor log statements in sourcegraph/zoekt to be compliant with logfmt 
- [ ] Configure DD log pipeline including remappers

**Comment by sanderginn** [comment]
Waiting for DataDog to respond to a support request regarding unexpected behaviour with [key value parsing](https://docs.datadoghq.com/logs/log_configuration/parsing/?tab=matchers#key-value-or-logfmt).

**Comment by daxmc99** [comment]
Closed part of https://github.com/sourcegraph/sourcegraph/issues/37568
