### ISSUE TITLE
Sourcegraph error on hover, text document does not exist with URI on Gitlab

### ISSUE THREAD

**Issue by ryankscott** [sourcegraph/sourcegraph#32601]
More information on the following ticket.

https://gitlab.com/gitlab-org/gitlab/-/issues/355474#note_870778329

**Comment by erzhtor** [comment]
> FYI, this seems to be related to the file name containing `##` symbols because the browser extension also incorrectly builds the "Open on Sourcegraph" button link omitting those symbols from the file path. I will work on fixing them, and then we will need to release a new Browser Extension and the `@sourcegraph/code-host-integration` package.
> 
> After that, we need to tackle #32599 to update/migrate to a new npm dependency.

FYI, created a separate https://github.com/sourcegraph/sourcegraph/issues/33310 and https://github.com/sourcegraph/sourcegraph/pull/33311 for this because seems to be unrelated to the hovers.

**Comment by erzhtor** [comment]
Commented in the original GitLab issue https://gitlab.com/gitlab-org/gitlab/-/issues/355474#note_899754806
