### ISSUE TITLE
Stream search results in the web app

### ISSUE THREAD

**Issue by ijsnow** [sourcegraph/sourcegraph#3261]
Search results should be streamed back to the client. This improves UX by:

- Less time to see results
- Less complicated code around returning partial results for long-running queries

Work required to support streaming results:
- [ ] Isolate search code so that we can expose it in any way we want (not just graphql) #3011
- [ ] Modify search code to support use of channels or another streaming solution
- [ ] Implement web socket endpoint that uses the streaming search function (above bullet point)
- [ ] Modify web app to search via web socket endpoint rather than graphql

**Comment by nicksnyder** [comment]
> Less jank due to loading spinner

Can you explain this more?

> Less complicated code around returning partial results for long-running queries

Do we currently return partial results for long running queries? It isn't clear to me how implementing streaming results would simplify the code.

**Comment by ijt** [comment]
Isn't there risk of getting bit rot in the existing GraphQL-based search API if we move to using only a new (websocket-based) search endpoint?

Is there anything besides the frontend that uses the GraphQL search endpoint?

**Comment by slimsag** [comment]
This makes perfect sense to me. I definitely think websockets are the right approach for this over.

One important aspect to consider here is: if the webapp is using websockets, how do we not regress on our graphql search API which customers rely on for scripting purposes? An ideal set up would actually be providing our customers with a plain REST API for search, as that would be a LOT easier to query (look at the src tools search.go file to see how aweful writing a graphql search query is) and would have more clear performance characteristics (you can't select a result.repo.field which is computationally heavy to query)

> Modify search code to support use of channels or another streaming solution

This should be easy/straightforward to do once my cleanup/refactor of search result merging code is back in (we would just need to update the search funcs to send results over a channel, basically): https://github.com/sourcegraph/sourcegraph/commit/1933d5619848b9f7125dfbd7fa75f082e248c2aa

**Comment by felixfbecker** [comment]
>  Modify web app to search via web socket endpoint rather than graphql

Have you considered just using HTTP to stream results? Since you won't need bidirectional communication, HTTP seems simpler.

**Comment by sqs** [comment]
This would be awesome. It would need to work with the dynamic search filters, too (those would need to be updated based on the full result set or something similar, so that if a bunch of vendor matches were found, it would suggest omitting vendor files).

- How does this affect pagination (which is a near-term priority)?
- Ranking and sorting of search results is a very long-term priority that this would affect, but not worth considering now.

**Comment by ijt** [comment]
@felixfbecker one advantage with websockets would be the possibility of detecting when a client has disconnected, so it's no longer necessary to keep sending back results. Then we wouldn't need to have a timeout on the results.

**Comment by felixfbecker** [comment]
Why is that not possible with HTTP?

**Comment by slimsag** [comment]
> How does this affect pagination (which is a near-term priority)?

I am working on pagination, the only concern is conflicting work happening. There is no fundamental reason why we cannot support both streaming of results in a "fastest result" order AND support pagination of results in a "logical order".

I would like to hear about estimated timeline on this work relative to other things, so I can assess risk of conflicting work.

**Comment by ijsnow** [comment]
Just throwing out another idea here, if we used websockets, we could take advantage of the bidirectional communication and send modified queries back and immediately swap out results. This would also help with search suggestions. This is just an idea and would not be v1 of result streaming.

Thanks for all the questions! I'll group all these and discuss them in a design doc.

**Comment by ijt** [comment]
> Why is that not possible with HTTP?

@felixfbecker , fair question. It's not with HTTP/1, but it is with HTTP/2. https://developers.google.com/web/fundamentals/performance/http2/

**Comment by felixfbecker** [comment]
@jit are you referring to anything specifically in that doc? What prevents this in HTTP/1?

**Comment by ijsnow** [comment]
One benefit of isolating the search code is that we can easily provide any number of ways to access search. We can still fully support the graphql endpoint as well as a basic rest one and this new streaming endpoint. Pagination is more of an implementation detail of the way it's being exposed due to how search is implemented. Until we have the stable search result ordering, pagination won't actually be true pagination.

**Comment by francisschmaltz** [comment]
> Less jank due to loading spinner

> Can you explain this more?

The loading spinner from a users perspective might make them feel less confident in Sourcegraph. We make it seem like it's a really easy problem to deliver results - even though it's not. When a user sees the loading spinner on a hover it might make them think something is wrong vs something is happening.

**Comment by slimsag** [comment]
> Until we have the stable search result ordering, pagination won't actually be true pagination.

I am working on this. (more details soon)

**Comment by slimsag** [comment]
https://github.com/sourcegraph/sourcegraph/issues/2865 for discussing my work on pagination

**Comment by ijsnow** [comment]
Re loading spinner: It's an opinion, a lot of UX enthusiasts agree. [Googling "loading spinners result in janky ui"](https://www.google.com/search?client=firefox-b-1-d&q=loading+spinners+result+in+janky+ui) results in a lot of blog posts with good content, including this one I found to be interesting: https://blog.iamsuleiman.com/stop-using-loading-spinner-theres-something-better/

**Comment by felixfbecker** [comment]
> The loading spinner from a users perspective might make them feel less confident in Sourcegraph. We make it seem like it's a really easy problem to deliver results - even though it's not. When a user sees the loading spinner on a hover it might make them think something is wrong vs something is happening.

I don't understand this argument - when streaming results, I would still expect a loading spinner, to communicate that results are still loading. I wouldn't think something is wrong because of it - the contrary, if there is nothing happening _without_ any loading indicator, I would think something is wrong. Why would showing nothing make them think something is happening?

**Comment by nicksnyder** [comment]
> The loading spinner from a users perspective might make them feel less confident in Sourcegraph. We make it seem like it's a really easy problem to deliver results - even though it's not. When a user sees the loading spinner on a hover it might make them think something is wrong vs something is happening.

We are talking about search, not hovers. Right now our search page has a loading spinner. With streaming results it would probably have to have a loading spinner too. I don't understand why a loading spinner for streaming results would be "less janky".

Given the amount of conversation on this issue, it feels premature to discuss without a more thought out proposal on the table (i.e a design doc).

**Comment by ijt** [comment]
> @jit are you referring to anything specifically in that doc? What prevents this in HTTP/1?

@felixfbecker , that probably wasn't the best choice to explain the difference. Try searching for "cancel", first in the [HTTP/1 RFC](https://tools.ietf.org/html/rfc2616) and then in the [HTTP/2 RFC](https://tools.ietf.org/html/rfc7540). Cancellation does not appear to be supported at all in HTTP/1.

**Comment by ijsnow** [comment]
Good point, @felixfbecker. I'll remove that point from the list as it doesn't have much weight in the case for streaming results.

**Comment by francisschmaltz** [comment]
@nicksnyder I corrected my response but in any situation, it'd be better to show some results or progress rather than just s spinner

**Comment by felixfbecker** [comment]
> it'd be better to show some results or progress rather than just s spinner

I think nobody disagrees with that :)

**Comment by felixfbecker** [comment]
@jit can't you just close the connection in HTTP/1? I would guess HTTP/2 needs explicit mechanisms for cancellation because it shares sockets

**Comment by felixfbecker** [comment]
@ijt I verified it with a quick node script, making a request from the browser:

![2019-04-05 20 56 30](https://user-images.githubusercontent.com/10532611/55650221-6d09d900-57e5-11e9-9e9a-5a6ec0086030.gif)

**Comment by ijt** [comment]
> @ijt I verified it with a quick node script, making a request from the browser:

Looks like I just learned something. Wouldn't have guessed it from the RFC.

**Comment by felixfbecker** [comment]
@ijt I think it doesn't appear in the HTTP RFC because it's through the transport layer, you can always just close the socket and the server can react to that (I don't know exactly how it interacts with Keep-Alive though)

**Comment by ijt** [comment]
We don't necessarily have to give up on GraphQL for this just because the Go implementation of GraphQL has no steaming. We could use graphql-js instead, possibly doing an RPC from that to some Go code. gRPC supports streaming.

**Comment by ijsnow** [comment]
I’m not proposing we give up on graphql. The graphql endpoint will still
fully support search just as it does now. The work needed section just
states we need to isolate search code so that we can expose it in any way
we want. I’ll go into more detail in the design document.

Re-implementing the code in js will be a lot more work, though Felix would
probably be happy :)

**Comment by ijt** [comment]
What I have in mind is a thin layer of Nodejs that handles graphql queries
by making RPCs. It's quite compatible with how you want to move the logic
out of the graphql layer.

**Comment by felixfbecker** [comment]
I would be happy about TS but I would not be happy about the added complexity of another RPC interface and the duality of two GraphQL layers.

Btw we also used gRPC at some point but got rid of it in favour of simple HTTP APIs. Legend has it that  Cuddy ripped out the gRPC layer.

Adding a search endpoint that uses HTTP streaming or WebSockets is very simple. It's also not like we only use GraphQL, we also have the REST raw API, so this is not a totally new thing.

From what I know of streaming support in GraphQL, going through GraphQL doesn't seem like the right option to me here. GraphQL subscriptions seem significantly more complex than a simple request/response stream model, and GraphQL live queries are essentially polling, so a simple streaming endpoint seems better.

**Comment by nicksnyder** [comment]
I am going to close this issue and redirect further discussion to this design document:
https://docs.google.com/document/d/1U2IpbO7mlPV8AxLy2LQ0_Tl-bUAy63lBRCUZ0feHL5Y/edit?ts=5cb6407b#

If/when the time comes to implement streaming in search, please open a fresh issue the describes the concrete next steps.
