### ISSUE TITLE
Ability to open editable version of local file from a search result 

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#32633]
#### Feature request description

As a user, if I click into a search result that is a location in a file that I have locally, I expect that I will be able to edit from this result. Currently, regardless of whether the file is available locally or not, all search results open to a read-only version of the file. 

#### Is your feature request related to a problem? If so, please describe.

While many of our individual users rely on the extension to search OSS code, this is a key "blocking" moment in a user journey if they plan to use the Sourcegraph extension to perform searches on local code. Users would have to leave the extension experience and try to find the same location on their local file if they want to edit. 

#### Additional context
[Internal user feedback.](https://sourcegraph.slack.com/archives/C02E3HHDZ98/p1646930224287999)

**Comment by jjinnii** [comment]
@abeatrix Adding this to Proposed for this iteration! I think this will be a decent level of complexity, but high impact- we would somehow have to check the user's VS Code directory to see if a file is available locally then open it to the exact location in the local file. Rather than solving it this iteration, maybe even looking into the possibility/level of effort for better planning next iteration would be awesome!

**Comment by abeatrix** [comment]
@jjinnii @tjdevries Do you think implementing the feature from our [open-in-vscode extension](https://github.com/sourcegraph/sourcegraph-open-in-vscode) to the VS Code extension is the right approach for this?

**Comment by abeatrix** [comment]
Definitely wrong TJ, @tjdevries sorry about that 😅 . 

Tagging the right @tjkandala

**Comment by abeatrix** [comment]
feature is now included in the VSCE v2.2.1 release
