### ISSUE TITLE
Add `lib/logging` to allow external log initialisation

### ISSUE THREAD

**Issue by sanderginn** [sourcegraph/sourcegraph#32673]
[sourcegraph/zoekt ](https://github.com/sourcegraph/zoekt) uses the standard log library, resulting in a different log format compared to other Sourcegraph services. To streamline Zoekt logs, it would be convenient to reuse the [internal logger](https://github.com/sourcegraph/sourcegraph/blob/main/internal/logging/main.go#L107). Introducing it in `lib` allows external imports.

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket, please let us know how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
