### ISSUE TITLE
Run at least two gitservers and indexservers on pre-prod.

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#32672]
The reason for this is that we want the pre-prod to be able to catch issues before running in production and typically some replicated/sharded services are behaving differently when running on multiple instances. 

By making the pre-prod having at least two instances of gitserver, we would be able to get closer to what we're seeing in production. That will never be perfect because that's not the same count of replica or load, but that would be a start.

> @jhchabran I agree we should run >1 gitserver & indexservers 
> Could you file a ticket? I think the change is overall pretty small but I don't want us to forget about it. We are currently using pre-prod for some SOC2 testing so we don't want to change it very much now.
> _Originally posted by @daxmc99 in https://github.com/sourcegraph/deploy-sourcegraph-cloud/pull/15374#issuecomment-1068104478_

**Comment by filiphaftek** [comment]
Done via [this PR](https://github.com/sourcegraph/deploy-sourcegraph-cloud/pull/15950)
