### ISSUE TITLE
Make saved searches available through our GraphQL API

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#3268]
#### Feature request description

Currently, it's not possible to query for saved searches directly via our GraphQL API. You have to query settings and parse the JSON. This should be possible. 

We've received a more specific request to show all saved searches that have email notifications.

Customers:

- https://app.hubspot.com/contacts/2762526/company/419771425 wanted to see all saved searches with email notifications

**Comment by sd9** [comment]
This would be very useful for https://app.hubspot.com/contacts/2762526/company/410280829 and https://app.hubspot.com/contacts/2762526/company/408826980.

**Comment by attfarhan** [comment]
Fixed via https://github.com/sourcegraph/sourcegraph/commit/a00f2fc02a83c4e8710d4dcf696b5b86e7105172
