### ISSUE TITLE
Support Batch Changes for Azure DevOps 

### ISSUE THREAD

**Issue by bdschaap** [sourcegraph/sourcegraph#32716]
#### Feature request description

I'd like to request that the Batch Changes feature be supported for Azure DevOps.

#### Depends on 

- [ ] #32717

#### Impacted customers

- https://github.com/sourcegraph/accounts/issues/8293

**Comment by malomarrec** [comment]
Thanks for raising this. We briefly discussed this internally, it _sounds like_ this would be possible at least for the git version control option, given of Azure DevOps has the concept of changesets / PRs.
This depends on
- [ ] Support Azure DevOps as a first-class codehost
that I raised with our @sourcegraph/repo-management team.

**Comment by courier-new** [comment]
This was officially added in 5.0. 🎉
