### ISSUE TITLE
Support Azure DevOps as a first-class codehost

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#32717]
There's also a product gap tracking this:
https://sourcegraph2020.lightning.force.com/lightning/r/Product_Gap__c/a1B5b00000LABF7EAP/view

#### Impacted customers

- https://github.com/sourcegraph/accounts/issues/8293

**Comment by malomarrec** [comment]
Possible duplicates of https://github.com/sourcegraph/sourcegraph/issues/23828, although the scope there is unclear.

**Comment by malomarrec** [comment]
My bad :/

**Comment by eseliger** [comment]
Azure DevOps is supported in Sourcegraph today: https://docs.sourcegraph.com/admin/external_service/azuredevops!
