### ISSUE TITLE
URL q parameter is not encoded when selecting from the "Repositories" list

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#32744]
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:** N/A

#### Steps to reproduce:

1. Search for a repo or view a repo in Sourcegraph.  
    Example: [view sourcegraph/sourcegraph](https://sourcegraph.com/github.com/sourcegraph/sourcegraph)
2. Go back to the home page
3. Click on the repo in the `Repositories` list
![image](https://user-images.githubusercontent.com/23640224/158887187-31344b93-b910-4f12-8e60-6574be3792b0.png)
4. After navigating, copy the URL from the browser
![image](https://user-images.githubusercontent.com/23640224/158888271-68a67407-4563-42ed-ae82-52b680895f82.png)
6. Notice that the URL will look like this: `https://sourcegraph.com/search?q=repo:^github\.com/sourcegraph/sourcegraph$`

##### Why does this matter to an end user?
The easiest example of why this matters is when pasting the link into a chat program like Slack.  Here's what happens:
<img width="607" alt="image" src="https://user-images.githubusercontent.com/23640224/158886956-6ece020d-2842-4198-8dde-ca54c3437b72.png">
(it's not able to properly parse the URL)

#### Expected behavior:

URL is encoded

#### Actual behavior:

URL is not encoded making it difficult for apps like Slack to parse the URL

#### Customer

[REDACTED CUSTOMER](https://github.com/sourcegraph/accounts/issues/6716)

**Comment by taylorsperry** [comment]
Closing because I don't think this is relevant to the new search page / Simple UI. Please reopen if that's not the case!
