### ISSUE TITLE
Narrowing Search in Monadic contexts

### ISSUE THREAD

**Issue by risingBirdSong** [sourcegraph/sourcegraph#32764]
#### Feature request description

It would be nice to be able to narrow the search scope with more context. Specifically i'm thinking of Monadic contexts because they are nice and widely used contexts in Haskell.

For example in Haskell using Yesod, there are Monadic contexts like IO (general input / output), Handler (for handling web requests and responses), DB (for making database queries).

narrowing the search space to look inside these monadic contexts could help be more precise and reduce noise.

It could become more powerful by combining and overlapping these contexts as well.
 
for example, narrowing a search to Handler's that call DB (database) functions... Or search for Handlers that call out to IO functions and search inside that IO context. 

Or, narrowing to the DB context, then again narrowing to Maybe context and searching for some string or using some structual in that refined context.

This could give some real power and precision in search imo.

#### Is your feature request related to a problem? If so, please describe.

Yes my current approach seems hacky. 

let's say I'm looking for something that is used inside the DB monad (doing a database query)
currently (and my workflow likely isn't great and could be improved!) I might search 
`-> DB` , and open the results in a new editor so I can do a secondary search for something i'm looking for. It's sloppy
because it'll include search results that just so happen to have `-> DB` string somewhere and doesn't guarantee that the results are in the DB context. 

or looking inside specific folders, but this approach can often be very limited and clunky.

#### Describe alternatives you've considered.

Hoogle has some nice basic search but doesn't seem to offer this level of expression in a search.
Getting better at regex would probably be worthwhile, but regex is hard and I'd rather more powerful and expressive tools like structural search.

#### Additional context

discussion in Slack:
https://sourcegraph-community.slack.com/archives/C02BG0M0ZJ7/p1646848096116009

**Comment by benvenker** [comment]
@risingBirdSong interesting idea! I’m not very familiar with Haskell but would love to know more. Could you paste a few examples of what good search results might look like in these cases? Maybe a few examples of what it means to be in the db context? Thanks!

**Comment by rvantonder** [comment]
@risingBirdSong hi! Thanks for your thoughts. I'm myself a fan of functional abstractions (long time OCaml coder) so I follow the high level idea here. Speaking purely practically, it's a pretty difficult task to try and model our search as a composition over a context chain (i.e., reader monad), just on the implementation side. There's a lot going on underneath the hood: we have lots of different backends and contextual information is highly dependent on the availability of even just very simple things like "is a repository indexed or not?" or "is this a search over commit data or code?". So yeah, the first thing is that parameterizing a context over the backends that serve these questions is... extremely difficult with the current way the code works.

The second part is that, we don't really have enough precision to answer some of those contextual questions (esp. things like type signatures that power Hoogle). We'd need some pretty heavy analysis to make that DB example work the way you describe (at least, heavy compared to what we have right now--the closest analog to your example of this flavor of semantic information is probably only loosely available in the major languages we support in our Code Intelligence DB, and unfortunately Haskell isn't one of them yet).

So yeah, we very much rely on users getting value from coding regex, and then some of the semantic/LSIF code intelligence info for jump-to-definitions and type hovers. Over time, I suspect these worlds will merge, we'll have better support for Haskell, and then could tackle the nice abstraction and power you mentioned here! For now it's pretty much out of reach for the next, I would say, 2 years.

**Comment by risingBirdSong** [comment]
@rvantonder thanks for the thoughtful response explaining the difficulties and time consuming nature with this idea. Still though, i'm glad to share ideas like this in hopes of one day these sort of nuanced searches being included. I think they could be useful!

**Comment by camdencheek** [comment]
Closing out this issue since we have no plans to expand the search language to capture this type of search and I'm cleaning up some old issues. Thank you for reaching out  though -- we really do appreciate the ideas!
