### ISSUE TITLE
Command palette not being added to GitHub.com

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#3281]
On GitHub.com, the command palette is not being added to the GitHub.com global nav. 

- There is *no* difference in the initial DOM in the `<header>` element on GitHub between the pages, so this suggests it is NOT an A/B test that changes the DOM.
- This problem is occurring with Refined GitHub turned *off*, so that is not a factor here.
- There are no relevant JS console errors.
- v19.4.3.1802 on Chrome.
- Everything above applies to all kinds of pages (code view, PR files changed, repo, etc.).

It works (the problem does NOT occur) on a dev build of the browser extension as of current master. Maybe just need to publish a recent fix?

Also reported by @Rush in https://github.com/sourcegraph/sourcegraph/issues/1116#issuecomment-480347056.

**Comment by felixfbecker** [comment]
This is already fixed in master.
