### ISSUE TITLE
Pull `reactstrap` `Tooltip` implementation into the codebase

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#32819]
## Problem statement

We want to [get rid of Bootstrap styles](https://github.com/sourcegraph/sourcegraph/issues/29200). Since `reactstrap` depends on `bootstrap` styles, we need to extract component implementations that we use.

## Success criteria

1. All `Tooltip` imports from `reactstrap` are removed.
2. `reactstrap` `Tooltip` implementation is pulled into our codebase into the Wildcard package as is.

## Implementation details

- [Tooltip implementation link](https://github.com/reactstrap/reactstrap/blob/ae4b5c5f5dddb6f928e51b89cf2a055cf078c481/src/Tooltip.js).
- Create a separate folder `ReactstrapTooltip` for pulled implementation in `client/wildcard/src/components/Tooltip`
- Copy all required files into this folder without changes.
- Add `README.md` saying that this folder will be deleted with the re-implementation of the `Tooltip` component later linking [this issue](https://github.com/sourcegraph/sourcegraph/issues/32362).
- Explicitly add dependencies required for the component to our `package.json` like `react-popper` based on the version that we rely on right now in our `yarn.lock`.

## Time estimate

- Pull requests with ~450 lines changed should take **4 hours** at maximum. Ping the reviewer in the spec pull request if time-consuming changes are required.
- Split the work into multiple pull requests if the total diff is bigger than 450 lines of code.

**Comment by valerybugakov** [comment]
@gitstart-sourcegraph, let's pause this issue because we might have the capacity to reimplement the `Tooltip` next week.

**Comment by gitstart-sourcegraph** [comment]
Hi @valerybugakov I believe the `Tooltip` component has been re-implemented, Is it safe to close this issue?

**Comment by valerybugakov** [comment]
@gitstart-sourcegraph, yes!
