### ISSUE TITLE
`reactstrap` `Dropdown` migration to Wildcard components

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#32820]
## Problem statement

We want to [get rid of Bootstrap styles](https://github.com/sourcegraph/sourcegraph/issues/29200). Since `reactstrap` depends on `bootstrap` styles, we need to extract component implementations that we use.

## Success criteria

1. All `Dropdown, DropdownItem, DropdownMenu, DropdownToggle` imports from `reactstrap` are removed.
2. Components affected are migrated to the combination of `Menu` and `Popover` components depending on UI requirements.

## Time estimate

- Pull requests with ~450 lines changed should take **10 hours** at maximum. Ping the reviewer in the spec pull request if time-consuming changes are required.
- Split the work into multiple pull requests if the total diff is bigger than 450 lines of code.

**Comment by umpox** [comment]
@gitstart-sourcegraph Please prioritise focus on https://github.com/sourcegraph/sourcegraph/issues/27701 and https://github.com/sourcegraph/sourcegraph/issues/27695 so we can avoid any duplication of work. This issue should be to refactor anything that isn't covered by those issues already

**Comment by valerybugakov** [comment]
@gitstart-sourcegraph, would it be possible to make the `Menu` component controllable via props? We might need this functionality later in other cases, and I would prefer this solution to the `ReachMenu` accessibility features implementation. Thank you for keeping us in the loop! 🙌

**Comment by valerybugakov** [comment]
@gitstart-sourcegraph, I see that `@reach-ui` [issues](https://github.com/reach/reach-ui/issues/699) are blocking the work on this feature. Let's explore the options of using `Popover` as you mentioned in the previous message.

**Comment by gitstart-sourcegraph** [comment]
@valerybugakov as discussed, since it might take considerably more time to re-implement the accessibility features on `Popover` to replicate existing behaviour, [here's an issue](https://github.com/sourcegraph/sourcegraph/issues/33218) as requested, for an improvement to tackle some technical depth to using the current reach's `MenuItem`

**Comment by valerybugakov** [comment]
Blocked by https://github.com/sourcegraph/sourcegraph/issues/27701#issuecomment-1131214314
Will be closed by the migration tickets of the new `Listbox` component that we need to implement first.
