### ISSUE TITLE
GitHub domFunctions.getCodeElementByLineNumber() should not call isDomSplitView() on every call

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#3284]
I noticed bad decorations performance on GitHub and profiling revealed time is spent in heavy `querySelector()` calls inside `isDomSplitView()`, which is called on every call to `getCodeElementByLineNumber()`, which is called for every line decoration.
`getCodeElementByLineNumber()` finds the `lineNumberCell` first, from there it should be easy to infer unified or split view by checking the number of cells in the row.

This is a requirement to implementing decoration support on diffs, because on PRs this has a big perf impact.

Before changing this, we need to add tests for the DOM functions to make sure the function will still work on GitHub, GHE and Refined GitHub (Enterprise).

**Comment by felixfbecker** [comment]
@lguychard was there progress made on this?

**Comment by lguychard** [comment]
Following my refactor in https://github.com/sourcegraph/sourcegraph/pull/3494, `isDomSplitDiff()` now only looks at the code view element, and doesn't perform `document.querySelector()` calls anymore (or call `parseURL()`...).

That being said, working on that PR showed me that the number of cells in a row is not a reliable indicator of whether a view is split/unified.

**Comment by felixfbecker** [comment]
Sounds like this is sufficient.
