### ISSUE TITLE
insights: codeinsights-db on postgres image breaks CI

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#32861]
When running CI against `src/src` with the `codeinsights-db` pointed to plain postgres instead of timescale, CI takes a very long time and fails to pass.

Failing PR: https://github.com/sourcegraph/sourcegraph/pull/32697

From @caugustus-sourcegraph: 
> I think I’ve discovered part of the reason CI tests are so slow - in our custom postgres image we [force a reindex](https://github.com/sourcegraph/sourcegraph/blob/main/docker-images/postgres-12-alpine/rootfs/reindex.sh) if it hasn’t been done before. This is probably getting triggered on every test and causing everything to be slow - disabling the reindex restores the original test timings.

**Comment by coury-clark** [comment]
Looking at a snippet of the CI logs, it's strange that we are passing on many tests in a reasonable amount of time, then suddenly fail on another test https://buildkite.com/sourcegraph/sourcegraph/builds/137473#d0b9c477-eabc-4b35-be91-70c43ac36708

**Comment by coury-clark** [comment]
The timeout occurs on this line: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/enterprise/internal/insights/dbtesting/insights.go?L58&utm_product_name=GoLand&utm_product_version=GoLand&utm_source=JetBrains-v1.2.1

**Comment by coury-clark** [comment]
It seems that the problem is the max connections must be configured externally in the timescale version, and it's set in the app code for our postgres image. Here is a branch of the timescale image branch with insights tests passing by configuring 10 max connections, similar to the main app db: https://buildkite.com/sourcegraph/sourcegraph/builds/138461#_

**Comment by coury-clark** [comment]
Closed https://github.com/sourcegraph/sourcegraph/pull/32697#issuecomment-1075734143

**Comment by caugustus-sourcegraph** [comment]
@coury-clark - Bad news, we're seeing CI tests fail again due to timeouts in https://github.com/sourcegraph/sourcegraph/pull/32697 - https://buildkite.com/sourcegraph/sourcegraph/builds/138877
