### ISSUE TITLE
Increase instance count on Preprod of horizontally scaled services known to behave differently at scale 

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#32873]
The preprod environment aims to provide a way to build up confidence that what we're going to release in production is going to work. What we've seen happening on a few occasions in different behavior in CI because we've been testing things on a single instance, but things take a different turn when it's getting scaled/sharded. 

As such, we want the preprod to reflect the production environment more accurately. It's not planned to run the pre-prod at the same exact scale we're running the production, but we can try to approximate it. 

Let's take the case of git-server: presently the preprod only runs a single instance. 

If we were to change that, what would give us more confidence? 

1. Running two instances, with reasonable resources. 
2. Running as many instances as we do on production, with very limited resources.
3. Something in between. 

In the case of 2. we need to know what's the lower bound for running gitserver before starting to see issues related to low resources, which would be irrelevant to our usage pattern in production. 

## Plan

- [x] @jhchabran: gather feedback and requirements from the relevant teams 
  - [x] [`gitserver`](https://sourcegraph.com/github.com/sourcegraph/deploy-sourcegraph-cloud/-/blob/base/gitserver/gitserver.StatefulSet.yaml?L15&subtree=true) https://sourcegraph.slack.com/archives/C02EDAQAJQZ/p1647938552759909
  - [x] [`indexed-search`](https://sourcegraph.com/github.com/sourcegraph/deploy-sourcegraph-cloud/-/blob/base/indexed-search/indexed-search.StatefulSet.yaml?L36&subtree=true) https://sourcegraph.slack.com/archives/CHEKCRWKV/p1647939143841169
    - > scaling is related to the number of repos you want to index. Basically we use memory which has a somewhat linear relationship to the size of indexed data. pre-prod having 3mil repos doesn't seem like a wise investment vs having a much smaller scale. Then you can just have much smaller pods and we will spread the load. 
- [ ] ➡️ @sourcegraph/cloud-devops: roll-out the changes.

**Comment by ryanslade** [comment]
How many repos are we thinking about tracking in the preprod environment? gitserver would need to be scaled in proportion to the number of repos. It can be scaled both horizontally and vertically but bear in mind that scaling horizontally will lead to almost all repos needing to be recloned, at least until [this](https://github.com/sourcegraph/sourcegraph/issues/32311) is done.

I would suggest keeping the existing vertical scaling as this will allow us to catch places where we hit the limits of an individual instance and we scale horizontally in proportion the number of repos in prod. For example, if we expect 50% of the repos we want 50% of the number of instances, but each with the same resources as we have in prod.

Also, bear in mind that a lot of what gitserver does is shell out to `git` so we can't look at just the resources used by the gitserver instance. A lot of this happens on demand based on user traffic which will be a lot lower on the preprod instance.

**Comment by jhchabran** [comment]
@ryanslade yes we're aware of the repo needing to be recloned, but while I don't have the numbers, the amount is much lower than the production and that would be a one-time fee when we roll out the change. 

I pinged the cloud-devops folks about the size, so we can estimate what would work best here.

**Comment by filiphaftek** [comment]
What we could propose is, as @ryanslade suggested, to keep same size of gitserver instance as on prod (this also will allow us i.e. to test i.e. new `n2` cores before starting them on production). As we do not have imho yet (at least I do not know) the expected number of repos on preprod, I would propose to keep at least 2 instances of gitserver, to have some HA - I said some, as I know that rolling out any instance of gitserver makes some repositories unavailable anyway. 

@sourcegraph/cloud-devops any suggestions?

**Comment by daxmc99** [comment]
👍 to moving to 2 instances of `gitserver` on cloud. We should also do the same for `indexed-search` since this is the other stateful set. 

I do think this will result in `gitservers` being overprovisioned for their current workload on pre-prod though. If we would leverage the vertical pod autoscaler and get some scaling profiles that might be helpful here as well.

**Comment by filiphaftek** [comment]
@jhchabran @daxmc99 which services, apart from `gitserver` & `zoekt` should also be in HA mode on preprod? B/c we do rolling update, I think i.e. frontend should have no downtime.

**Comment by jhchabran** [comment]
@filiphaftek sorry for the late answer, lost track of my GH notifications. We're good with those two. Just a minor question, shouldn't we also increase the size for `search-indexer` as well (it's also zoekt)?

**Comment by filiphaftek** [comment]
@jhchabran on `preprod` we have same size for zoekt as on production [kustomize](https://github.com/sourcegraph/deploy-sourcegraph-cloud/blob/preprod/overlays/preprod/indexed-search/sts.yaml), and for gitserver a bit smaller CPU (b/c we use on preprod faster cores) [kustomize](https://github.com/sourcegraph/deploy-sourcegraph-cloud/blob/preprod/overlays/preprod/gitserver/sts.yaml#L16).
Of course the disks are smaller, but if we find the need, we can extend them quickly,

**Comment by jhchabran** [comment]
My mistake, I did not use the correct word, I meant replica count / horizontal scaling. In the PR the replica count for search indexer was still at 1. 

I double-checked myself and my comment is irrelevant, I got confused with the naming with `indexed-searcher` and `search-indexer`. Just ignore my remark 🙏

**Comment by jhchabran** [comment]
Fixed by https://github.com/sourcegraph/deploy-sourcegraph-cloud/pull/15950/files
