### ISSUE TITLE
enable `release` branch branch protections in deploy-sourcegraph-cloud

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#32876]
As discussed during our last sync about RFC-592 with the @sourcegraph/cloud-devops team, we want to make sure it's not possible to push on the `release` branch of https://github.com/sourcegraph/deploy-sourcegraph-cloud without going through a PR. 

@daxmc99 and @danieldides at the time of writing this, I don't have access to the settings to list here what's currently in place. I suppose that's already being done, in which case we can close this, if and only if this is documented already. 

In the eventuality of a PR needing to be expedited, `pr-auditor` will always raise an exception if it sees a PR not being reviewed. 

TODO:

- [ ] Define the policy 
- [ ] Document the policy 
- [ ] Enact the policy 
- [ ] Post an announcement over Slack + include it newsletters.

**Comment by daxmc99** [comment]
Still need to verify but this likely has been done

**Comment by filiphaftek** [comment]
Branches `release` & `preprod` are protected.
