### ISSUE TITLE
Update the miro board of RFC 592 to include the separation of continuous deployments and schedule based deployments 

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#32877]
Miro board: https://miro.com/app/board/uXjVOKqPSDM=/

Presently, the Miro board abstracts the details of the difference of continuous deployments (frontend, ...) VS schedule based deployments (gitserver, ...). 

In order to make the board more accurate, we need to update the flow to reflect it.

**Comment by filiphaftek** [comment]
@jhchabran should I modify the Miro flow to actual, existing state? as I see some elements (i.e. rollbacks) which are manual yet.

**Comment by filiphaftek** [comment]
@jhchabran great, thank you! I have sent the invite.
