### ISSUE TITLE
Shut down insightstest managed instance

### ISSUE THREAD

**Issue by caugustus-sourcegraph** [sourcegraph/sourcegraph#32885]
Once work on the TImescale deprecation is completed ()https://github.com/orgs/sourcegraph/projects/200/views/43), the insighstest instance can be shut down.

**Comment by virginiaulrich** [comment]
Blocked by testing per https://github.com/sourcegraph/sourcegraph/issues/32075

**Comment by sanderginn** [comment]
Instance has been shut down.
