### ISSUE TITLE
docker-compose supports customizing pg-conf

### ISSUE THREAD

**Issue by michaellzc** [sourcegraph/sourcegraph#32918]
## Context

We currently have no documentation for tunning postgresql.conf for docker-compose distro, but k8s https://docs.sourcegraph.com/admin/config/postgres-conf

## Implementation

Similar to how we ship postgresql.conf via a ConfigMap in our k8s distro, we should include such file in the `deploy-sg-docker` repo as well.

below is an illustration of the new file tree

> the content of `postgresql.conf` should be either copied from [pgsql.ConfigMap.yaml](https://github.com/sourcegraph/deploy-sourcegraph/blob/master/base/pgsql/pgsql.ConfigMap.yaml) or from the image `sourcegraph/postgres-12-alpine` directly
```
- pgsql
  - conf
    - postgresql.conf
```

such file will be mounted into the `pgsql` container during runtime

```yaml
pgsql:
  volumes:
    - '../pgsql/conf:/conf/'
```

The conf file will get picked up by `pgsql` automatically

For users who are looking to customize stuff, they should add their override __at the bottom__ to avoid future merge conflict

Part of https://github.com/sourcegraph/customer/issues/778

**Comment by sourcegraph-bot-2** [comment]
Heads up @caugustus-sourcegraph @kevinwojo @michaellzc - the "team/delivery" label was applied to this issue.

**Comment by michaellzc** [comment]
We posted a note in CS and CE channel to figure out if any users are customizing pgsql in docker-compose https://sourcegraph.slack.com/archives/CU93UDUBV/p1647983354716749
No response indicates anyone is doing such thing

Additionally, I try looking up the ticket archived https://k8s.sgdev.org/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/support-tools-internal%24+postgres+content:%22Deployment:+docker-compose%22&patternType=literal

It looks like pretty much everyone are using managed postgres, so I wouldn't worry too much with my proposed approach. We can get away with including notes in the changelog.

**Comment by michaellzc** [comment]
related https://github.com/sourcegraph/sourcegraph/issues/33016

**Comment by michaellzc** [comment]
@michaellzc will sum up the options and send to dan for review

**Comment by virginiaulrich** [comment]
@michaellzc where did you leave off on this one? It was in "waiting/review" -- but maybe it should just be in the backlog?

**Comment by virginiaulrich** [comment]
This looks to be done; closing unless you tell us we are wrong @michaellzc :)
