### ISSUE TITLE
zoekt incremental indexing: add support for .sourcegraph/ignore to prototype

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#32922]
_Follow up to_ https://github.com/sourcegraph/zoekt/pull/295#discussion_r827714788

---

# Background 

The `.sourcegraph/ignore` file ([docs link](https://docs.sourcegraph.com/code_search/explanations/search_details#exclude-files-and-directories)) defines a list of files Sourcegraph should ignore while searching. 

As part of this, Zoekt's indexing process should also skip over any files contained in `.sourcegraph/ignore`. The original (non-delta) indexing process correctly implements this: https://sourcegraph.com/github.com/sourcegraph/zoekt@7ad19f68605348354f3c50b47e33ce7dbc4d9d04/-/blob/gitindex/index.go?L413-430

However, the delta-indexing prototype currently implements a stop gap solution: it falls back to a non-indexed build if a `.sourcegraph/ignore` file is present: [sourcegraph/zoekt@`7eb6bc3` (#310)](https://github.com/sourcegraph/zoekt/pull/310/commits/7eb6bc3ad05d3898605c40391b21dfc285f8b05d)

# Goal 

This stop-gap solution is correct, but falling back negates all of the advantages of the delta-indexing strategy.

The delta-indexing prototype should implement full support for `.sourcegraph/ignore` files and retire the stop gap solution. There will be some minor edge cases that we need to think about (how the .sourcegraph/ignore and FileTombstones that will need to be figured out/documented. The [existing test framework](https://sourcegraph.com/github.com/sourcegraph/zoekt@d6b7925f0f82f23d0e4efa025f7d4f86b5d059cb/-/blob/gitindex/index_test.go?L69) should make it straightforward to enumerate all of them, however.

**Comment by sourcegraph-bot-2** [comment]
Heads up @jjeffwarner - the "team/search-core" label was applied to this issue.

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket, please let us know how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
