### ISSUE TITLE
zoekt incremental indexing: add support for repository submodules in prototype

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#32921]
_follow up to https://github.com/sourcegraph/zoekt/pull/295#discussion_r827705975_

---

to be discussed further in a sync meeting:

We have some documentation saying that Sourcegraph supports submodules https://docs.sourcegraph.com/admin/how-to/submodule-configuration. However, I've seen that Zoket itself doesn't actually support this feature (as Sourcegraph uses it)? https://sourcegraph.slack.com/archives/C023ELQLV7F/p1651150065010399?thread_ts=1651126890.981449&cid=C023ELQLV7F

We should hash this in one of our sync meetings?

---

Regardless, it would be nice to have even a stop-gap solution for handling submodules when performing incremental-indexing. The simplest thing to do would be to fall back to a normal build (similar to what we do for[ .sourcegraph/ignore](https://github.com/sourcegraph/zoekt/pull/310/commits/7eb6bc3ad05d3898605c40391b21dfc285f8b05d)).

**Comment by sourcegraph-bot-2** [comment]
Heads up @jjeffwarner - the "team/search-core" label was applied to this issue.

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket, please let us know how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
