### ISSUE TITLE
Web: [Charts] Create separate charts component with new LineChart 

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#32937]
## Background

In the Code Insights, we've got a few static visualization chart components that might be useful for other teams. So we probably want to use it outside of code insights. In order to do this, we need to create a separate package (the directory in the web folder) and we could start with sharing the LineChart component. 

Also, it might be a good reason to revisit our chart API.

**Comment by vovakulikov** [comment]
This issue was closed by https://github.com/sourcegraph/sourcegraph/pull/29372

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
