### ISSUE TITLE
Web: Add Pie chart to the Chart package 

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#32936]
## Background 

In the code insights, we've developed the pie chart component for the code insights needs. Since this component might be useful not only for the code insights team but for other teams as well we should share it through our newly created `/charts` package in the web directory. It also might be a good reason to revisit the API of the component and solve possible performance problems.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
