### ISSUE TITLE
Web: [Charts] Use wildcard `Popover` component instead of `floating-ui` custom library

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#32939]
## Background

We use the `floating-ui` tooltip for the chart tooltip component. Since we have our own `Popover` component as a part of the wildcard package this PR simply replaces the `floating-ui` with our Popover.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by vovakulikov** [comment]
This issue has been closed by https://github.com/sourcegraph/sourcegraph/pull/32543
