### ISSUE TITLE
Web: [Charts] Add stacked data support for the Line Chart component

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#32938]
## Background
In the charts package, we have the LineChart component that renders a series line chart. Each line/series is rendered independently but it might be useful to have a chart where all series/lines are stacked. This allows seeing the same data from different angles. 

For example, on the picture below you can see the same dataset but at the right chart these data series are rendered independently, and at the right chart these data series are stacked. 

<img width="813" alt="Screenshot 2022-03-23 at 13 41 22" src="https://user-images.githubusercontent.com/18492575/159669831-4a8dec7d-676d-4357-bd88-1ffe3c6542dc.png">

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by vovakulikov** [comment]
This issue has been closed by https://github.com/sourcegraph/sourcegraph/pull/31142
