### ISSUE TITLE
Web: [Charts] Add group series bars support for the `BarChart` component

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#32942]
Follow up for https://github.com/sourcegraph/sourcegraph/issues/32940

## Background 

At the moment we have a BarChart component but this component doesn't support series view. At the moment it supports only "grouped" by type bars and doesn't support timeline data. I think it might be useful to have series line representation BarChart component, the one like you can see on the screenshot below. It will allow us to change different chart views for the Code Insights Search insights.

<img width="826" alt="Screenshot 2022-03-23 at 13 56 56" src="https://user-images.githubusercontent.com/18492575/159672909-f4611874-6ef8-404c-a5d2-e4d93eb6ffb7.png">

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by felixfbecker** [comment]
@vovakulikov what is/was the size of this issue?
