### ISSUE TITLE
Web: [Charts] Add BarChart component in the chart package

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#32940]
## Background

In the code-insights team we have already developed the `BarChart` component for the code-insights team needs (I think it was used for one of extensions, but currently it isn't used anywhere but we still have this component in our codebase) However, I think it might be useful for code-insights in the near future and other teams as well. It also could be a good reason to revisit this component API and fix possible performance problem.

<img width="435" alt="Screenshot 2022-03-23 at 13 50 03" src="https://user-images.githubusercontent.com/18492575/159671430-5876dda6-dfa5-4a83-bd4c-16289ab1b1ee.png">

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by vovakulikov** [comment]
@Joelkw Sorry that didn't mention this in the description, I think this issue is mostly about technical groundwork for implementing this bar chart. Will it need designs? I think it will require some input from @AlicjaSuska just to be sure that I don't mess up with the axis and labels for this. 

> do users need a way to choose the chart type?

I think I have to create a separate package of issues with the adoption plan for Code Insights.

**Comment by vovakulikov** [comment]
The first draft with Alicja's designs for the bar chart component in the context of code insights capture group insight
https://www.figma.com/file/YoMwiXPV7fSdfWJPmm7pMT/Capture-groups-v.2-%2329956?node-id=1147%3A5946

**Comment by Joelkw** [comment]
Notes from sync discussion – not clear if we actually need this item or not. The goal is just that once we have a UI that requires a bar chart, that's an easy option – this work is just to get ahead of knowing we want to enable a bar chart.
