### ISSUE TITLE
Code Insights: Revisit/refactor code insights card layout component for the dashboard and creation UI pages

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#32944]
## Background 

Our current implementation of the card layout has a lot of problems because we couldn't predict so much usage of this component in so many different use cases.  Because of all these possible states of this card, we ended up with really bad tech decision three in API and this already slows us down. I think we should revisit this component as soon as possible to avoid problems in the future with new functionality over the charts.

We also are using the legacy charts (XY visx chart) for the insight card component. We should remove those components and use new chart components from the `/charts` package.

Tech problems that we need to solve 
- Reuse this card for the creation of UI live previews
- Decrease complexity in API where we specify different consumers 
- Revisit the mobile layout of this card with different types of charts
- Lock mode charts

![Frame 1](https://user-images.githubusercontent.com/18492575/159676630-3288075c-f1f8-4664-8ca1-55ae46dcf536.png)

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
