### ISSUE TITLE
Web: [Charts] Add support stacked series data for the `BarChart` component

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#32943]
Follow up for https://github.com/sourcegraph/sourcegraph/issues/32942

## Background 

This issue is about adding stacked like representation of the data series for the BarChart component. Similar that we had for the `LineChart` in this issue https://github.com/sourcegraph/sourcegraph/issues/32938 but only for BarChart. 

For the reference 
<img width="836" alt="Screenshot 2022-03-23 at 13 59 55" src="https://user-images.githubusercontent.com/18492575/159673595-dda72c71-b373-477f-a2cf-3487fb22b9ff.png">

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by felixfbecker** [comment]
@vovakulikov what is/was the size of this issue?
