### ISSUE TITLE
Fix ranking of dependency repos in repo searches

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#32952]
For NPM, investigate using the popularity score from the registry. Generally, rank based on number of dependents.

<img width="738" alt="image" src="https://user-images.githubusercontent.com/67471/159711401-b800a3ee-0752-404c-a8fd-b38669634558.png">

[Slack thread](https://sourcegraph.slack.com/archives/C032G1CLM7X/p1648008550980589)

**Comment by sourcegraph-bot-2** [comment]
Heads up @jjeffwarner - the "team/search-core" label was applied to this issue.

**Comment by stefanhengl** [comment]
This feature has been discontinued.
