### ISSUE TITLE
Code Insights: The drill down filter panel has a weird heading/visual structure 

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#32963]
## Background

The main header in this panel has h4 ("Filter repositories" heading) This looks a bit off since the labels also has the same visual style. And it seems we have the hr here without any purpose. 

<img width="532" alt="Screenshot 2022-03-23 at 19 45 52" src="https://user-images.githubusercontent.com/18492575/159739634-2c57711e-3537-4cfa-b1b8-00ebea488236.png">

## Possible layout 

@AlicjaSuska take a look. Here I tried to simplify layout and adjust general layout of filter panel. Also this visual marker connects marker at the filter button and builds mental connection between filtered/not filtered visual states.

<img width="603" alt="Screenshot 2022-03-23 at 19 55 39" src="https://user-images.githubusercontent.com/18492575/159741791-504ce5c4-e1d6-4170-aceb-378449d1c422.png">

**Comment by AlicjaSuska** [comment]
Thank you for brining this up @vovakulikov 

1. Layout changes: let's work on changes in the [Figma](https://www.figma.com/file/Ml5dtV9ni4mfffbfOfF9jg/?node-id=260%3A11) about adding search context.
2. Dot: it's an interesting point but may be misleading as:
- we use dot to indicate ANY filter is applied, not only default
- if we add a dot next to the 'default filters applied' text, it would make a connection pink dot = default filters applied
- when user changes default filters or adds filters to the insight with no default filters, we would still show the pink dot next to the icon. This is the confusing moment

In the first versions of filter popover design, I explored the option of:
- blue dot for default filters
- pink dot for filters in general
This may be worth coming back to at some point and then adding a dot next to the 'default filters applied' text would be justified. 

That being said, I think that value to investment ratio for implementing this logic now is low. We should wait for feedback about filtering in general and see if it comes up.

**Comment by AlicjaSuska** [comment]
@vovakulikov since we're implementing chages in #33249, would it be ok to close this issue with the note?

**Comment by vovakulikov** [comment]
@AlicjaSuska thanks for your thoughts on this. I like the idea of different color coding for different states of filters and yeah I agree that I missed this problem with default !== applied filters.

About closing this let's wait until we finish https://github.com/sourcegraph/sourcegraph/issues/33249 and after we will close this with follow up about color-coding states or with other follow-ups as well in case we won't fix all layout problems in https://github.com/sourcegraph/sourcegraph/issues/33249
