### ISSUE TITLE
VSCE: Looker dashboards for VSCE to track customer usage

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#32988]
TBA

Related to issue #29124

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @rrhyne @jjinnii @ryankscott - the "team/growth-and-integrations" label was applied to this issue.

**Comment by abeatrix** [comment]
Closing. See https://sourcegraph.slack.com/archives/C01T0BL4EFN/p1652255707236109
