### ISSUE TITLE
Tracking issue: Code host API usage expectations

### ISSUE THREAD

**Issue by indradhanush** [sourcegraph/sourcegraph#32982]
### Plan

Create a tool to calculate the expected number of API requests based on the following factors:

- Type of code host
- Total number of repositories
- Total number of organizations and / or teams
- Total number of users

Depending on the code host and the feature set supported on each the answer may be different. A tool would be helpful for our customers and customer engineers to know what to expect and detect any deviations from the expectation early.

:exclamation: Code hosts to be supported in the tool:

- [ ] GitHub

🙆 Stretch goals:

- [ ] Gitlab
- [ ] Bitbucket

Here is a list of customer issues we have received in the past which justifies the need for such a tool to quickly answer and understand customers' issues and expectations:

- 👩 [customer/issues/658](https://github.com/sourcegraph/customer/issues/658)
- 👩 [customer/issues/742](https://github.com/sourcegraph/customer/issues/742)

While there are multiple sources of API requests, permissions syncing is a big part of it. The planning doc for [scaling repository permissions syncing](https://docs.google.com/document/d/17iD_Y1tG_lWFnQOI9xQ0p0VtcYVOOUzoeU83l7Uq20I/edit#heading=h.i3xwfyw7s3bs) has some existing literature on expected number of API requests when cached permissions syncing is enabled which will be helpful to get started but needs verification.

### Tracked issues

@unassigned: __5.00d__

- [ ] https://github.com/sourcegraph/sourcegraph/issues/32983  __3.00d__   🏳️ [code-host-api-usage](https://github.com/sourcegraph/sourcegraph/milestone/185)
- [ ] https://github.com/sourcegraph/sourcegraph/issues/28602  __2.00d__   🏳️ [code-host-api-usage](https://github.com/sourcegraph/sourcegraph/milestone/185)

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.
