### ISSUE TITLE
Global config "search.defaultPatternType": "regexp" - stops working in v3.36.x

### ISSUE THREAD

**Issue by DaedalusG** [sourcegraph/sourcegraph#32989]
- **Sourcegraph version:** v3.36.x ->
- **Platform information:** 

#### Steps to reproduce:
1. Enable the global site config `"search.defaultPatternType": "regexp"`
2. Navigate to your `/search` homepage and observe that regex is not enabled by default

Below is a screen capture of the phenomenon --
![regexp-config-bug](https://user-images.githubusercontent.com/13024338/159817697-9166db5b-478c-4f35-9196-5bcf4f2dd635.gif)

During testing I upgraded a docker-compose instance from `v3.31.0` to `v3.38.0` checking if regex was enabled by default after every upgrade. 

I observed that this functionality no longer worked after upgrading from `v3.35.2` ->  `v3.36.3`

I then tested this functionality against a kubernetes instance running in v3.38.0 and observed the setting wasn't working there either.

#### Expected behavior:

With this setting enabled, navigating to the homepage should by default have regex based search enabled.

#### Actual behavior:

Search is patternType literal by default.

If would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are not [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.
