### ISSUE TITLE
Migrate dogfood to non-root

### ISSUE THREAD

**Issue by michaellzc** [sourcegraph/sourcegraph#32980]
## Steps

- [x] notify `#dev-ops` dogfood will be down for non-root migration

- [x] soft-delete all existing argo application to avoid argo from syncing any further changes

The way how these apps are created right now is prevent us from applying overlay on them https://github.com/sourcegraph/infrastructure/tree/main/dogfood/kubernetes/argocd/apps

We are going to remove all of them

```sh
argo-cd app list --grpc-web | awk '(NR>1)' | awk '{print $1}' | xargs -I % argo-cd app delete --cascade=false --yes %
```

- [ ] rebase and catch up with updated `base` https://github.com/sourcegraph/deploy-sourcegraph-dogfood-k8s/pull/4040

- [ ] commit generated `migrate-nonroot` overlay https://github.com/sourcegraph/deploy-sourcegraph-dogfood-k8s/pull/4040

this will commit the `generated-cluster` manifests to the dogfood repo

- [ ] add the new argo app https://github.com/sourcegraph/infrastructure/pull/3181

```sh
kubectl apply -f dogfood/kubernetes/argocd/dogfood-k8s.yaml
```

the new app will sync manifests under `generate-cluster`

Caveats:
- we may need to manually reset or apply the `instance` label on resources to get argo working properly

- [ ] commit the generated `non-root` overlay 

__TODO__ after migration is done

### What about renovate?

First of all, renovate hasn't been run on dogfood for a few days. Is this expected?

Maybe we can configure a GitHub CronJob actions to periodically generate the overlay and commit back to repo as a temp solution?

**Comment by sourcegraph-bot-2** [comment]
Heads up @caugustus-sourcegraph @kevinwojo @michaellzc - the "team/delivery" label was applied to this issue.

**Comment by daxmc99** [comment]
Let's ensure we include a status update to #dev-ops channel to led others know we are going to have downtime

**Comment by michaellzc** [comment]
it's done
