### ISSUE TITLE
Switch order for git blame states

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#32987]
#### Feature request description

Currently, the git extension has 3 states in the order of: 
1. show blame on a highlighted line
2. show blame on all code
3. turn off 

There is a documented user problem captured in issue #17429 that the 3 states of the git blame extension are hard to understand. There's a need to do some discovery work to understand -- do we need 3 states? If so, do users opt to use one more than another? Does it make sense to be configurable? 

Until Product/Design has the bandwidth to conduct discovery, we'd like to propose a temporary "little" fix of switching the git blame states:
1. show blame on all code
2. show blame on a highlighted line
3. turn off

#### Is your feature request related to a problem? If so, please describe.

This quick fix _alleviates_ the user problem that the 3 states are hard to understand. It is more intuitive behavior that we'd show the all blame state first. (I'm failing to think of an example right now, but it's more common that apps/webpages will show you an "all" view, followed by a filtered or pared down view)

This feature does not solve issue #17429. Separate design work will be conducted in that issue after this fix.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @rrhyne @jjinnii @ryankscott - the "team/growth-and-integrations" label was applied to this issue.
