### ISSUE TITLE
gitserver janitor: check and insert repo size to gitserver_repos table

### ISSUE THREAD

**Issue by sashaostrikov** [sourcegraph/sourcegraph#33000]
Related to https://github.com/sourcegraph/sourcegraph/issues/32197

Some repos still don't have a size in `gitserver_repos` table. Gitserver janitor calculates repos' sizes every time it runs, so this information can be used to update only repos with `repo_size_bytes == null`.

There will be 1 SQL query with batch update of repos with no size.
This query will run exactly once during the first run of the janitor.

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.
