### ISSUE TITLE
JetBrains: Work on first iteration of design for first jobs to be done flow 

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#33011]
TBA

**Existing Sourcegraph users without private code**
When I'm using a library I'm unfamiliar with, I want to see how others in the public have used this so I can understand how to use it better

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @rrhyne @jjinnii @ryankscott - the "team/growth-and-integrations" label was applied to this issue.
