### ISSUE TITLE
Investigate differences between postgres configurations

### ISSUE THREAD

**Issue by caugustus-sourcegraph** [sourcegraph/sourcegraph#33016]
The postgres config shipped in deploy-sourcegraph-docker deployments is different than what is provided in deploy-sourcegraph.

Tasks:
* Identify the significant differences and determine if they're legitimate
* Identify the significant difference between pgsql / codeintel / codeinsights 
* Update the configuration used in https://github.com/sourcegraph/deploy-sourcegraph-managed/pull/372 and https://github.com/sourcegraph/deploy-sourcegraph-managed/pull/371 if necessary

**Comment by michaellzc** [comment]
Here's a diff

https://docs.google.com/document/d/1MzTpztUW-R8qARjQjYngA62LM64Y6OSImI04J_DPXTQ/edit

It's produced from https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/792/files#diff-e9e7e9726963cc7ea7780ff81b0c2e19dff02d031fddc02f67da8212fb012c69

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/cloud-devops - the "team/devops" label was applied to this issue.

**Comment by michaellzc** [comment]
this is done https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/792
