### ISSUE TITLE
Discussion: How/should we standardized on a log aggregator?

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#3301]
This issue is to hold the discussion around how we should, and whether or not we should, standardize on a log aggregator like Loki, elasticsearch, etc. This is a breakout issue from https://github.com/sourcegraph/sourcegraph/issues/3175 because logging in particular requires more discussion.

---

In https://github.com/sourcegraph/sourcegraph/issues/3230 @ggilmore tried to use Loki in production but ran into difficulties / instabilities. He last said:

> Since most of this isn't well documented + looks complex, I'm tempted to just start looking into an ELK stack. Thoughts @keegancsmith @tsenart @slimsag @beyang ?

@tsenart said in response

> @ggilmore: Operating ElasticSearch is hard. I'd be reticent to bestow such a burden on customers that don't have the in-house expertise.
>
> This leads me to think whether we should standardize on a logging solution at all, or whether we'd be better off delegating that to the customer's existing centralize logging pipeline. I think there's more benefit and much less cost on shipping Prometheus + Grafana, compared to an ELK stack.
>
> Have we seen many cases where customers don't already have one in place?

@ggilmore said on Slack that he is aware of at least one such customer (https://app.hubspot.com/contacts/2762526/company/419771425), also stating:

> We are also managing customer instances inside different environments (GKE, AWS, etc.) and it is difficult to get the team comfortable with multiple different kinds of logging/monitoring tools (AWS, GKE, etc.). It would be beneficial to pick one and use that everywhere

@slimsag said on Slack he is aware of one customer (https://app.hubspot.com/contacts/2762526/company/407948923  ) that would be opposed to standardized logging, prefers standard linux log-rotation (but they are the exception, not the rule)

**Comment by slimsag** [comment]
I share @tsenart's concern about managing an ES stack. I haven't worked with ES before, but from everything I know it just screams complex. I wonder if there is a more lightweight competitor we could use that could basically just grab our kubernetes pod logs and store them for later? I'm also asking around on some semi-related projects like Blast, a ES competitor, e.g. https://github.com/mosuka/blast/issues/54

**Comment by tsenart** [comment]
I found this and it looks reaaaaally interesting: https://github.com/ekanite/ekanite

**Comment by tsenart** [comment]
```
Ekanite is a high-performance syslog server with built-in text search. Its goal is to do a couple of things, and do them well -- accept log messages over the network, and make it easy to search the messages. What it lacks in feature, it makes up for in focus. Built in Go, it has no external dependencies, which makes deployment easy.
```

**Comment by tsenart** [comment]
Looking at the issues in the repo, it looks like it's not actively maintained, and while promising, it'd likely take quite a bit of work from us on performance, polish, etc.

Another idea: Instead of shipping a full log management solution, how about we setup only a log-shipper like fluentd or https://github.com/jedisct1/flowgger, and provide documentation to customers to configure it to store compressed logs in some cloud storage bucket with a well defined retention policy and data scrubbing filters to redact sensitive data?

Would this be sensible, and, feasible? In debugging situations, we'd just ask customers to download the logs archive for a given day / hour and send it to us (or provide us access to that cloud bucket directly).

**Comment by keegancsmith** [comment]
Has there been any work towards this in this milestone? What is the plan moving forward?

**Comment by ggilmore** [comment]
Sorry, we had a discussion when @sourcegraph/distribution went over https://docs.google.com/document/d/1lm9rqsWq--DSpwAsrDE9J8GEi0ivlnH-AMG9iOCGda0/edit#. The plan is to just use/document the cloud provider's default log aggregation solution for now. 

This isn't critical for 3.4, but it will be addressed in a minor release in https://github.com/sourcegraph/deploy-sourcegraph
