### ISSUE TITLE
RFC 624: (M1) Create Lua sandbox executor service

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#33042]
Implements a portion of [RFC 624: Configurable auto-indexing recognizers](https://docs.google.com/document/d/1LOVI6xogkt4Iifl1F_8Gb_H9pXQ_MrynW8vmr6D05A0).

Create an `internal/luasandbox` package that covers the basic generic Lua sandbox construction, execution, and callback linking machinery.

**Comment by sourcegraph-bot-2** [comment]
Heads up @macraig - the "team/code-intelligence" label was applied to this issue.
