### ISSUE TITLE
RFC 624: (M2) Harden recognizer gitserver client

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#33044]
Implements a portion of [RFC 624: Configurable auto-indexing recognizers](https://docs.google.com/document/d/1LOVI6xogkt4Iifl1F_8Gb_H9pXQ_MrynW8vmr6D05A0).

Consider different types of limits we can place on gitserver requests as made in the sandbox introduced in #33041. These may include rate limits on a per-request or global basis, possibly keyed by some identifying information (e.g., repository), or may include data input or output limits (e.g., max 5k files, content size below 5KB, etc).

Devise the correct set of rate limits that will protect us immediately as well as limits that will be applicable after the execution model of #33040 is decided.

**Comment by sourcegraph-bot-2** [comment]
Heads up @macraig - the "team/code-intelligence" label was applied to this issue.
