### ISSUE TITLE
RFC 624: (M5) Make recognizer behavior configurable

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#33046]
Implements a portion of [RFC 624: Configurable auto-indexing recognizers](https://docs.google.com/document/d/1LOVI6xogkt4Iifl1F_8Gb_H9pXQ_MrynW8vmr6D05A0).

After deciding on a target API design in #33040:

- ~Create a new set of Lua builtins (the "sg" script available inside the sandbox; will likely be mix of Lua + Go code)~
- ~Update our default recognizer implementations to use new API~
- Add a database table, store methods, and GraphQL resolvers to expose optional recognizer script configuration
- Create a quick-and-dirty site admin page where the recognizer script can be updated
- Inform design we've created a mess

**Comment by sourcegraph-bot-2** [comment]
Heads up @macraig - the "team/code-intelligence" label was applied to this issue.

**Comment by efritz** [comment]
#35451 made the override script configurable via an environment variable. This ticket now represents the _user-facing_ way to configure these overrides. We should have a way to _at a minimum_ put it in a site config via the UI.
