### ISSUE TITLE
RFC 624: (M0) Gather requirements

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#33047]
Implements a portion of [RFC 624: Configurable auto-indexing recognizers](https://docs.google.com/document/d/1LOVI6xogkt4Iifl1F_8Gb_H9pXQ_MrynW8vmr6D05A0).

Identify a few customers that would benefit from this feature and determine exactly what behavior they are looking to fulfill with auto indexing. Alternatively (or additionally), we can look for specific types of OSS projects which have been too niche to concentrate effort on for the Cloud auto-indexing corpus as a learning exercise.

These requirements should be gathered to inform the design of a new recognizer API, tracked in #33040.

**Comment by sourcegraph-bot-2** [comment]
Heads up @macraig - the "team/code-intelligence" label was applied to this issue.
