### ISSUE TITLE
RFC 624: (M4) Design new recognizer interface

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#33040]
Implements a portion of [RFC 624: Configurable auto-indexing recognizers](https://docs.google.com/document/d/1LOVI6xogkt4Iifl1F_8Gb_H9pXQ_MrynW8vmr6D05A0).

Re-implement the [existing recognizer behaviors](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@cd2182763d2839b43cd49edfc877aa2ac5a07b80/-/blob/lib/codeintel/autoindex/inference/recognizers.go?L23:5#tab=references) into a greenfield API in Lua and get team alignment on the user ergonomics, behavior, and execution model. See [this gist](https://gist.github.com/efritz/c69fa750c1a036827464e3a1905bd539) for an example API.

**Update**: Scope of ticket has changed to _improve_ the existing API as merged in #33756. This must be informed by the results of #33047 and blocks #33046.

**Comment by sourcegraph-bot-2** [comment]
Heads up @macraig - the "team/code-intelligence" label was applied to this issue.
