### ISSUE TITLE
Shared scrolling context for repos/files/code snippets in references panel is unergonomic

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/sourcegraph#33061]
The panel conceptually has three "levels", first the repo, then the files in the repo, and then the code snippets. However, they share the same scrolling context, which means that if you scroll a bit to see the repos, and if you select a repo, the files and matching code snippets for that repo may not longer be in view, and you need to scroll up again.

In the example screenshot below, I was trying to scroll the list of repos, but you can see that the list of files and the code snippet are getting "chopped off" from the top because of this.

<img width="726" alt="Screenshot of references panel" src="https://user-images.githubusercontent.com/93103176/160065239-4dad59b3-abb4-4cd9-89a6-f238d52fd9a6.png">

Arguably, these three levels should have their own separate scrolling contexts. As an example, here is macOS's finder. Notice that there are three scroll bars for the three levels, not just one.

<img width="727" alt="Screenshot showing three levels of directories in macOS's Finder" src="https://user-images.githubusercontent.com/93103176/160065028-49b65476-fb33-4ad4-8724-cd9cb6e07e9a.png">

**Comment by sourcegraph-bot-2** [comment]
Heads up @macraig - the "team/code-intelligence" label was applied to this issue.

**Comment by mrnugget** [comment]
Doesn't exist in this form in the new reference panel (although that could still use some improvements to how it represents long lists)

**Comment by Numbers88s** [comment]
Closing, this refers to the old reference panel.
