### ISSUE TITLE
Showing uncached retention overview for an upload takes 15+ seconds

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/sourcegraph#33064]
If I select an upload from https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/code-intelligence/uploads/ and expand the "Retention Overview" section from the upload's page, the spinner is replaced with results after about 15s-17s (I timed it with a stopwatch), which seems a little high.

There appears to be some level of caching going on, so trying it the second time for related commits doesn't incur the same delay, it happens ~instantly. However, if you type in something in the search bar to filter the retention policies, the latency is higher again.

**Comment by sourcegraph-bot-2** [comment]
Heads up @macraig - the "team/code-intelligence" label was applied to this issue.

**Comment by Strum355** [comment]
Looks like a duplicate of https://github.com/sourcegraph/sourcegraph/issues/32691, so Im going to close this issue 🙂

**Comment by varungandhi-src** [comment]
🙂
