### ISSUE TITLE
insights: store structs use singular `ID` variables for arrays

### ISSUE THREAD

**Issue by leonore** [sourcegraph/sourcegraph#33075]
In the backend we have a few structs for store query arguments that use singular `ID` naming for variables that actually are arrays. It seems this is also only something that happens in insights: https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+ID%5Cs%2B%5C%5B%5C%5D&patternType=regexp.

The goal of this ticket is just to remove this tech debt by updating the ID variables to be plural.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by OladapoAjala** [comment]
@leonore has this issue been fixed? I see you reference it in the PR 32901

**Comment by leonore** [comment]
@OladapoAjala It hasn't, that PR is what made me notice the need for this issue :)

**Comment by OladapoAjala** [comment]
Sure I'd look into it then.

**Comment by jasonhawkharris** [comment]
PR: https://github.com/sourcegraph/sourcegraph/pull/54556
