### ISSUE TITLE
Extension does not match help 

### ISSUE THREAD

**Issue by wxio** [sourcegraph/sourcegraph#3308]
- **v19.4.8.1301** 
- **Linux Ubuntu 17 - https://sourcegraph.com - Chrome 67.0.3396.99, Firefox 61.0.1 **

I am having issues getting sourcegraph to work (will post separate issues detailing this) as a starting point the help documentation does not match the installed addin.

https://docs.sourcegraph.com/integration/browser_extension
![image](https://user-images.githubusercontent.com/24236711/55766952-36b8ac00-5aba-11e9-9bd3-662c9c6cf7b3.png)

![image](https://user-images.githubusercontent.com/24236711/55766859-d9245f80-5ab9-11e9-962c-7f03a2dbc8bc.png)

**Comment by felixfbecker** [comment]
Hi @wxio, what do you mean with "does not match"? Sorry for my confusion.

**Comment by millergarym** [comment]
@felixfbecker the extensions (second image) (v19.4.8.1301) does not have any controls to dis/enable sites and importantly does not show which sites have been enabled. This info is in the extension (first image) from the animated gif on the help page.

**Comment by ryan-blunden** [comment]
Hi @wxio, are you still having this issue?

The browser extension will now ask to you "grant permissions" to enable the browser extension if on a code that that is not GitHub or Sourcegraph.com

![ScreenFlow](https://user-images.githubusercontent.com/133014/56681152-90ee6b00-667d-11e9-8998-8de724268462.gif)

**Comment by ryan-blunden** [comment]
Hi @wxio, just wanted to check if you're still having this issue.

**Comment by kghopson** [comment]
Hey @ryan-blunden ! Just going through some of my backlog. Is it safe to say this issue has been resolved or is no longer relevant? I saw that it went in the backlog for a previous release

**Comment by felixfbecker** [comment]
@kghopson Ryan doesn't work for Sourcegraph anymore - given @wxio didn't reply to Ryan's request, I'd close this. (@wxio if this is still an issue please let us know)
