### ISSUE TITLE
Decide search box technology

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#33088]

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @rrhyne @jjinnii @ryankscott - the "team/growth-and-integrations" label was applied to this issue.

**Comment by vdavid** [comment]
@philipp-spiess and I decided to go with the [hybrid view option](https://docs.google.com/document/d/1Lkj_2MjayAqlvOTLjaLFGHYJnobV1ieRxXhH_jJDBgQ/edit#heading=h.mtqarxams9mf) for the search window.
The search bar and result list will be a web view, and the preview box will be a native Swing component.
This decision is easy to change later, so we decided to go ahead with it.
That'll be our primary direction unless Sara’s final designs will be very different or contain some element that we can’t make work this way.
