### ISSUE TITLE
Filenames on BC preview page link to nowhere

### ISSUE THREAD

**Issue by danielmarquespt** [sourcegraph/sourcegraph#33083]
Clicking on the filenames on the preview batch change page leads the user nowhere. Currently they are just an anchor for the link it self.

Expected behaviour: Link to the actual file in Sourcegraph. If this is not possible the name of the file should be just plain text.

**Video 31:18:**
https://drive.google.com/file/d/1oAv83WTADvdtCd7ZYKgSTCG3aOfR9ze3/view?t=31m18s

**Screenshot:**
![Screenshot 2022-03-25 at 13 49 04](https://user-images.githubusercontent.com/7814431/160133157-09830809-ef68-417f-b8b0-eb93f5e5740f.png)

**Comment by LawnGnome** [comment]
Update to this: we probably just want to make this not a link, since there isn't always a logical place to link to.

**Comment by adeola-ak** [comment]
Investigate where all this component appears and if there is no link in all places and if links are needed in some but not all or none.. etc
