### ISSUE TITLE
Preview Batch Changes command results in a CLI error

### ISSUE THREAD

**Issue by danielmarquespt** [sourcegraph/sourcegraph#33082]
The suggest preview command to preview a batch change on the src-cli results in an error. This needs to be fixed as it results in a major friction point for the UX.

Video: https://drive.google.com/file/d/1oAv83WTADvdtCd7ZYKgSTCG3aOfR9ze3/view?t=21m09s

![Screenshot 2022-03-25 at 13 43 23](https://user-images.githubusercontent.com/7814431/160132156-beca8f93-3c4d-4bd3-91b8-c53bdfdb05b0.png)

Tasks:

- [x] Check if this is fixed in the SSBC flow

- [ ] Propose new design/copy to fix this

**Comment by adeola-ak** [comment]
hi @danielmarquespt, so for now I'll adjust the text to say `src batch preview -f batch.spec.yaml` to match what's expected in the SS you provided, as it is expecting a file name and so there won't be an error. Happy to hear any further design improvements you wish to recommend
