### ISSUE TITLE
Getting started help

### ISSUE THREAD

**Issue by wxio** [sourcegraph/sourcegraph#3309]
#### Feature request description

Getting started tour or walk through built into the extension.

#### Is your feature request related to a problem? If so, please describe.

Wrapping ones head around sourcegraph is not a trivial exercise.
Many another way of saying this is that getting value out of sourcegraph is a steep learning curve.

#### Describe alternatives you've considered.

Some suggestions;

- A bouncy icon with tool-tips that does something as simple as point to the extension and then point to the sourcegraph icon on the github page.

- A feedback button directly from the extension

- Chat built into the extension

#### Additional context

I am new to sourcegraph, my current way of understanding and navigating code is to clone and load into a IDE.  I can see some obvious advantages to using sourcegraph (discovering thing I don't no exist, searching across branches etc). 

IMO it needs to be easier to get started.

**Comment by sqs** [comment]
Thank you. I agree, this would be valuable. I've prioritized it for the next release.

**Comment by christinaforney** [comment]
[Chrome uninstall feedback](https://app.hubspot.com/forms/2762526/a1bc77c9-019c-4f83-b5ba-327949f8e587/submissions/8c802b20-d86f-48ab-aa70-c6a6f97fb793) on 7/26 about ease of getting started: 
"I don't understand how to start using"
