### ISSUE TITLE
gitdomain consistent pointer receivers

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#33099]
Extracted from a TODO:

https://github.com/sourcegraph/sourcegraph/blob/5a58d3fbe0058b45ce521a48d00b6da95156f715/internal/gitserver/gitdomain/errors.go#L10-L12

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.

**Comment by DaivikDave** [comment]
Hey @ryanslade 
https://sourcegraph.com/search?q=context:global+repo:github.com/sourcegraph/sourcegraph+Error%28%29+string&patternType=literal  A lot of error methods are not pointer receivers. I can take this issue. 
What would be a right way to approach this issue given the changes are in multiple packages and might affect PR's of others?
Should we have a seperate PR for each package?

**Comment by ryanslade** [comment]
Hey @DaivikDave, thanks for your help!

For now I think we should just focus on this one package and after that we can decide whether we want to make it a broader change.

Please tag @sourcegraph/repo-management for review with your PR.

**Comment by DaivikDave** [comment]
Hey @ryanslade, thanks for getting back.
I have gone through the gitserver package. Changes to only one error struct was required, rest of them had pointer receivers. I have made the PR. Thanks
