### ISSUE TITLE
Can sourcegraph be dockerized?

### ISSUE THREAD

**Issue by dpopiashvili** [sourcegraph/sourcegraph#331]
I've been asked at work to dockerize this application. I've never worked with SG before, so might be asking something obvious, but since SG depends on docker daemon, does that mean that we can't run it inside container? Did anyone tried this before?

Thanks

**Comment by slimsag** [comment]
Hi @dpopiashvili -- could you clarify what you mean exactly? Do you mean run in a single container?

Sourcegraph currently uses the access to the Docker daemon to run language servers, but this is optional, see my post here: https://github.com/sourcegraph/sourcegraph/issues/225#issuecomment-426505896

In the near future we will be investigating a different way of deploying language servers that does not require access to the Docker socket, which would make a single container deployment possible.

**Comment by dpopiashvili** [comment]
Hey @slimsag, thank you very much for your reply. Yes that's what I mean, to run SG in single container. I commented out `docker run` command from run-server-image.sh and server started :-). Is there a better way to disable docker dependency?

Thanks again

**Comment by slimsag** [comment]
@dpopiashvili If the goal is to run Sourcegraph in a single Docker container, simply remove `-v /var/run/docker.sock:/var/run/docker.sock` from the `docker run` command we provide anywhere (e.g. at https://about.sourcegraph.com/docs/) and it'll work.

This will disable automatic code intelligence, where Sourcegraph starts the language servers for you. You will need to follow instructions here to run them yourself and point Sourcegraph at them for now: https://about.sourcegraph.com/docs/code-intelligence/install#manual-installation

We are investigating different ways of improving this and getting rid of our default suggestion of passing through the Docker socket.

**Comment by dpopiashvili** [comment]
Hey Stephen. 

Thanks again for the update, but there are also several `docker pull` invocations. I guess I should comment them out right?

**Comment by slimsag** [comment]
@dpopiashvili Which `docker pull` commands are you speaking of? To be clear, if you are trying to run a non-development Sourcegraph Server, you should follow the steps in our [Quickstart guide](https://about.sourcegraph.com/docs/)

**Comment by sqs** [comment]
@dpopiashvili The link above should help. This is a very well supported way of using Sourcegraph. Please reopen if your problem is not solved, however.
