### ISSUE TITLE
VSCE: Merge feature branch to main

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#33102]
Currently the latest VSCE code lives in the [tjk/vsce-search-ui](https://github.com/sourcegraph/sourcegraph/tree/tjk/vsce-search-ui) branch. We should plan to merge it into the main branch before it grows too big.
Issues caused by the code living in the feature branch:
https://github.com/sourcegraph/sourcegraph/issues/32894
https://github.com/sourcegraph/sourcegraph/issues/31092

**Comment by tjkandala** [comment]
Done!
