### ISSUE TITLE
Cursor is invisible when entering text in code host field

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/sourcegraph#33101]
- **Sourcegraph version:** Sourcegraph.com as well as main
- **Platform information:** Firefox 98.0.1 on macOS 12.2.1

#### Steps to reproduce:

1. Creating a new code host under site-admin.
2. Click on the field with the code host name (no blinking cursor shows up) and try inputting text (works, but still no cursor) or hitting the left or right arrow key.

#### Expected behavior:

There should be a cursor when the code host name text input is selected.

#### Actual behavior:

There is no cursor.

https://user-images.githubusercontent.com/93103176/160156175-b434fc8c-d0de-4d42-9c37-395260e77e92.mov

**Comment by varungandhi-src** [comment]
cc @sourcegraph/frontend-platform

**Comment by umpox** [comment]
I can't seem to replicate this on Chrome/Safari/Firefox 🤔

**Comment by lrhacker** [comment]
I also can't reproduce. Going to close for now, @varungandhi-src let us know if you are still seeing this!
