### ISSUE TITLE
Factor out PackageSyncer from NPMPackagesSyncer, JVMPackagesSyncer and GoModulesSyncer

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#33103]

**Comment by sourcegraph-bot-2** [comment]
Heads up @jjeffwarner - the "team/search-core" label was applied to this issue.

**Comment by tsenart** [comment]
From @ryanslade about IsCloneable:

> Idea, for later: Maybe we don't want to make this a required method for the interface. We could make it an optional one and check whether the syncer implements it in fetch
