### ISSUE TITLE
Pin current directory and ancestors for large directories in file explorer

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/sourcegraph#33129]
Say you're looking through the files in a large directory in the tree-style file explorer. Right now, the scrolling just works as a plain list, so you lose track of the current directory and its ancestors (in the video below: `lib`, `AST` and `RequirementMachine`). So you can't quickly collapse them, and you've lost context.

https://user-images.githubusercontent.com/93103176/160319350-87df993e-191d-452e-8302-2d9206909584.mov

Instead, if they were temporarily pinned like so:

```
Files   Symbols
==========================
v lib
  v AST
    v RequirementMachine
-------------------------- <- light divider maybe to show temporary pinning
        ⋮ <- vertical ellipses or maybe some light shadow showing that some files are being hidden
       NameLookup.cpp
       NameLookup.h
       etc.
```

You could quickly click on the `v` and collapse the right ancestor. You'd also have easy visual access to the path you're at.

**Comment by sourcegraph-bot-2** [comment]
Heads up @macraig - the "team/code-intelligence" label was applied to this issue.

**Comment by Numbers88s** [comment]
Proposed Solution:
- Make the parent directories sticky while scrolling
