### ISSUE TITLE
Improve frontend runtime error monitoring with Sentry

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#33125]
## Problem to solve

Today, we lack processes around client-side monitoring errors, error reporting, and prioritizing and fixing runtime errors. Consequently:
- The cloud instance can be inaccessible for a significant amount of time without anyone noticing
- Even when problems are observed, it's unclear where to report and track the issue
- Issues are ignored when ownership areas are unclear
- Errors are swallowed that shouldn't be

## Solution summary

Artifacts:
- [RFC 501 REVIEW: Runtime error monitoring](https://docs.google.com/document/d/1d18e_YFJsw5cgDId8Iz1MT8A_GsHZTOGHMuem1JMzuM/edit#)

## What specific customers are we iterating on the problem and solution with?

Internal Sourcegraph developers

## Delivery plan

- [ ] TO DO

**Comment by valerybugakov** [comment]
We have a tracking issue for this RFC [here](https://github.com/sourcegraph/sourcegraph/issues/26570). Probably we should close one as a duplicate or update the description to communicate the difference.
