### ISSUE TITLE
Symbols search bar should be pinned when scrolling through list of symbols

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/sourcegraph#33127]
When scrolling, the symbol search bar is part of the scroll view, which means that narrowing down search or searching for something requires scrolling back up again.

https://user-images.githubusercontent.com/93103176/160312278-0c81bcea-382e-41ac-ad7d-b3a603ba41e6.mov

We should change this so that scrolling only affects the list of symbols. Originally [reported in Slack](https://sourcegraph.slack.com/archives/CHXHX7XAS/p1648187224028399).

**Comment by sourcegraph-bot-2** [comment]
Heads up @macraig - the "team/code-intelligence" label was applied to this issue.
