### ISSUE TITLE
Overlay panels (fuzzy finder, help) are incorrectly positioned on dragging window across monitors

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/sourcegraph#33128]
Tested on macOS 12.2.1 with Firefox 98.0.2. See potato quality GIF below (it looks like GitHub can't handle either mp4 videos, potrait mode videos or potrait mode mp4 videos).

Resizing the window fixes the positioning (not shown).

![Dragging window with fuzzy finder box moves its top left anchor much further right and below where it ought to be](https://user-images.githubusercontent.com/93103176/160315019-390f151a-3e9b-40a8-9ba6-33511b23fe91.gif)

**Comment by varungandhi-src** [comment]
This doesn't seem to be limited to the fuzzy finder panel. It also happens for the help panel. So it seems like a generic component issue rather than something specific to the fuzzy finder panel.

**Comment by varungandhi-src** [comment]
cc @sourcegraph/frontend-platform

**Comment by jasongornall** [comment]
I can't repro :(

**Comment by varungandhi-src** [comment]
@jasongornall can you inline the GIF? Clicking https://ezgif.com/split/ezgif-1-b1582a99a5.gif redirects me to https://ezgif.com/split

**Comment by jasongornall** [comment]
from this
![image](https://user-images.githubusercontent.com/6912393/180452157-0d69e7d3-89ae-4da9-bd65-fe40bd73d2f9.png)
to this
![image](https://im3.ezgif.com/tmp/ezgif-3-b1582a99a5-gif-im/frame_06_delay-0.08s.gif)


my screen seems ok though

**Comment by varungandhi-src** [comment]
Maybe there is something funky with my monitor set up. I recall having to use some software to change the resolution of the external monitor, I don't recall if that was active when I recorded this. I'll reopen if I'm able to reproduce in a normal setting.
