### ISSUE TITLE
Gitserver instance unavailable

### ISSUE THREAD

**Issue by filiphaftek** [sourcegraph/sourcegraph#33133]
- **Sourcegraph version:** spotted on `139109_2022-03-25_f0376a1e15e3@sha256:bfa227fe78098e48e55aff13e0c24e63ecb880737d65e7c6973f126c12f4992c`
- **Platform information:** Cloud

#### Steps to reproduce:

On 26th of March we have received an alert from GCP that gitserver endpoint is not responding for over 3mins:
<img width="1502" alt="GCPHealthCheck" src="https://user-images.githubusercontent.com/7045340/160353390-c37744eb-f51a-4b4d-863c-b61922ce5827.png">

While checking [Grafana](https://sourcegraph.com/-/debug/grafana/d/6ddhHJTnk/cloud-devops-alerting?orgId=1&from=1648262844420&to=1648264153134), we have spotted weird CPU usage on single instance and increased number of 500s errors.

#### Expected behavior:

As this was not gitserver rollout, endpoint should be available 100% of the time.

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.

**Comment by eseliger** [comment]
I don't think there's any trace of data left to investigate this issue unfortunately - if it reoccurs please report it again :)
