### ISSUE TITLE
Feature idea: File type icons in file tree explorer

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/sourcegraph#33130]
Xcode has [file type icons](https://youtu.be/dUlZiHa9qVs?t=45) which make it visually easy to understand the file types when browsing through files in a tree-style explorer. This is particularly useful for C, C++, ObjC codebases, which often have implementation files and header files with the same name right next to each other. Here is an example from the apple/swift repository and how the files look in Sourcegraph.

<img width="198" alt="Different files with similar names" src="https://user-images.githubusercontent.com/93103176/160317099-7bd43c91-a180-4c0d-a8df-99cd28199896.png">

I think having icons (at the front) would make it a little easier to be able to tell file types at a glance, compared to looking at the extension which is at the end.

Here is a screenshot with icons from Xcode (I couldn't get the files working because the Xcode project shows "virtual folders" instead of "physical" folders.)

<img width="214" alt="Screen Shot 2022-03-27 at 8 33 01 PM" src="https://user-images.githubusercontent.com/93103176/160322107-952a0cf5-8973-45db-ae08-410c78ee75e5.png">

(Xcode also supports an option to suppress the file extension, which is turned on by default in Xcode 13. It can also be turned on selectively for certain extensions. But I'm not proposing adding that option here.)

**Comment by sourcegraph-bot-2** [comment]
Heads up @macraig - the "team/code-intelligence" label was applied to this issue.

**Comment by Strum355** [comment]
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/24947 and possible others, there are some similarly titled issues but with vague/lost in time descriptions

**Comment by varungandhi-src** [comment]
OK, let's close this as it's a duplicate of https://github.com/sourcegraph/sourcegraph/issues/24947.
