### ISSUE TITLE
Multi-branch indexing - "invalid settings: experimentalFeatures: Additional property search.index.branches is not allowed"

### ISSUE THREAD

**Issue by bdschaap** [sourcegraph/sourcegraph#33145]
I tried adding the following json to Global settings on Site Admin but receive the error message below.  I am following the instructions [here](https://docs.sourcegraph.com/code_search/explanations/features#multi-branch-indexing-experimental).  Am I doing something wrong?

```json
  "experimentalFeatures": {
    "search.index.branches": {
      "myRepo": ["myNonDefaultBranch"]
    }
  }
```

`invalid settings: experimentalFeatures: Additional property search.index.branches is not allowed`

**Comment by sourcegraph-bot-2** [comment]
Heads up @jjeffwarner - the "team/search-core" label was applied to this issue.

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket, please let us know how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
