### ISSUE TITLE
Fix tracking of event properties for about.sourcegraph.com

### ISSUE THREAD

**Issue by erzhtor** [sourcegraph/sourcegraph#33154]
For https://github.com/sourcegraph/sourcegraph/issues/31486, the `@sourcegraph/event-logger` was not correctly set to send `argument` and `publicArgument` fields.

1. Fix `sourcegraph/eventlogger` and publish a new version to npm
2. Update `sourcegraph/about` to use new npm package version

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @rrhyne @jjinnii @ryankscott - the "team/growth-and-integrations" label was applied to this issue.
