### ISSUE TITLE
Invalid Id when previewing batch change ran server side

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#33174]
When clicking on preview, after having ran a batch change server-side, I get "invalid id". I was able to reproduce.

https://user-images.githubusercontent.com/25070988/160582206-b945cfe1-2038-416b-bcc7-af881807b52e.mp4

**Comment by eseliger** [comment]
Is that on demo?

**Comment by malomarrec** [comment]
This is fixed on main, and will be in next release.
Deselecting the workspace before previewing is a workaround.
