### ISSUE TITLE
Update docs site to recommend helm

### ISSUE THREAD

**Issue by caugustus-sourcegraph** [sourcegraph/sourcegraph#33179]
Followup to https://github.com/sourcegraph/sourcegraph/issues/32180 and https://github.com/sourcegraph/sourcegraph/pull/33178. When Helm enters GA, we want to promote this installation method alongside kustomize.

1. Find all mention of Kustomize and update to recommend Helm, with something like… “But we also support Kustomize”

1. Look at all the general intros to how to use Kubernetes with Sourcegraph and make sure Help is recommended with Kustomize as a backup. Kustomize is almost an afterthought, which kind of makes a little sense… you only need it to make customizations. Whereas we’d want to suggest Helm as the method to deploy, meaning it needs to be mentioned and suggested a lot earlier and more prominently than Kustomize has been. For example on https://docs.sourcegraph.com/admin/install/kubernetes and https://docs.sourcegraph.com/admin/deployment_best_practices

**Comment by sourcegraph-bot-2** [comment]
Heads up @caugustus-sourcegraph @kevinwojo @michaellzc - the "team/delivery" label was applied to this issue.

**Comment by caugustus-sourcegraph** [comment]
@dan-mckean Closing this out, I think you completed the work.
