### ISSUE TITLE
Update dogfood environment to use helm

### ISSUE THREAD

**Issue by michaellzc** [sourcegraph/sourcegraph#33188]
see below

**Comment by sourcegraph-bot-2** [comment]
Heads up @caugustus-sourcegraph @kevinwojo @michaellzc - the "team/delivery" label was applied to this issue.

**Comment by michaellzc** [comment]
previous issue broken and I can't make any update to the descprtion
https://github.com/sourcegraph/sourcegraph/issues/32179

**Comment by michaellzc** [comment]
We will mix helm + kustomize together to deploy dogfood https://github.com/kubernetes-sigs/kustomize/blob/master/examples/chart.md

### Needs review

- [x] https://github.com/sourcegraph/infrastructure/pull/3178
- [ ] Enable `--enable-helm` feature flag on dogfood argocd https://github.com/sourcegraph/infrastructure/pull/3157
- [ ] Add helm deployment https://github.com/sourcegraph/deploy-sourcegraph-dogfood-k8s/pull/4018

### Blockers

- [x] Upgrade argo to 2.2.x to mitigate the helm vulnerability https://github.com/sourcegraph/security-issues/issues/216 (@michaellzc is looking into it)
- [x] https://github.com/sourcegraph/deploy-sourcegraph-dogfood-k8s/pull/4040
- [ ] Update https://github.com/sourcegraph/deploy-sourcegraph-dogfood-k8s/pull/4018 to remove the `yesRoot` override since we're now doing non-root migration before helm

### Migration plan

- [ ] announce in #dev-ops that dogfood will be down for a short time
- [ ] merge https://github.com/sourcegraph/deploy-sourcegraph-dogfood-k8s/pull/4018
- [ ] we perform a soft (non-cascading) deletion of all previous argo app, i.e., no kubernetes resources will be removed by argo `argo-cd app delete --cascade=false --yes dogfood-k8s`
- [ ] scale `pgsql`, `codeinsights-db`, and `codeintel-db` to zero (we https://github.com/sourcegraph/deploy-sourcegraph-helm/pull/70 in helm, otherwise, the new sts won't be able to mount the PVC)
- [ ] apply the new app https://github.com/sourcegraph/infrastructure/pull/3157/files#diff-791a98a7d47c416a6a03a8cc151968a09dc54db5511789f9515b1fd2f2dafa94
- [ ] confirm all pods are healthy (especially with the added `readOnlyRootFilesystem: true` security context)
- [ ] remove jsonPatches that "fix" the `matchLabels`, delete all existing deploy and sts, re-apply the argo app
- [ ] merge https://github.com/sourcegraph/infrastructure/pull/3157
- [ ] Clean up legacy plain k8s manifests in the deploy-dogfood repo to avoid future confusion and open a new PR

### Fallback plan

We're not touching any PV/PVC during the migration so there's no concern for potential data loss. We should be able to remove the added argo app and reapply previous apps again

**Comment by michaellzc** [comment]
we need to fix this https://github.com/sourcegraph/deploy-sourcegraph-dogfood-k8s/blob/release/dogfood-helm/kustomization.yaml#L66-L80

**Comment by michaellzc** [comment]
it's done
