### ISSUE TITLE
ci/flake: golangci depguard disabled

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#33183]
### Test

golangci's depguard check

### Example failure

https://buildkite.com/sourcegraph/sourcegraph/builds/139526#e6db285d-059a-440f-8cb0-fd15499a5a16

### Disabling PR

https://github.com/sourcegraph/sourcegraph/pull/33182

### Additional details

https://github.com/sourcegraph/devx-scratch/blob/main/2022/support/log.md#2022-03-25

**Comment by bobheadxi** [comment]
This is still disabled: https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/.golangci.yml?L6-7

**Comment by mucles** [comment]
@jhchabran,  I have not been able to reproduce the the (typecheck) errors seen in the bk failure example., I do see the following I do see warning for imports that are in the denylist when enabling depguard, but seem unrelated. Those seems more related to the following [discussion on golangci-run](https://github.com/golangci/golangci-lint/discussions/2214]) 👀 
  
We are using version v1.45.2 of golangci-run which uses v1.1.0 for depgaurd. In the next latest release of golangci-run it looks like they will upgrade depgaurd to v1.1.1 ,  should we just upgrade to that version of golangci-run when it is available before reenabling depgaurd again ? or what are your thoughts on that ?

here are the changes from v1.1.0 ->  v1.1.1
https://sourcegraph.com/github.com/OpenPeeDeeP/depguard/-/compare/v1.1.0...v1.1.1?visible=2

**Comment by mucles** [comment]
also, the denylist errors that I am seeing are consistent with the defined deps that are specified in the denylist, so that checks out as well ✔ 
https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/.golangci.yml?L28-36
