### ISSUE TITLE
"Multiline" placeholder results in multiline cursor

### ISSUE THREAD

**Issue by fkling** [sourcegraph/sourcegraph#33209]
Due to how CodeMirror's default placeholder extension works, having a placeholder that spans multiple lines causes a single tall cursor to be rendered (since the document is actually empty and only has a single line).

![Screenshot 2022-03-30 at 12.30.08.png](https://images.zenhubusercontent.com/614899f55d273b9067f17b27/0ae8f707-b6af-4cbc-8687-6e5a44d79fc6)

For more context: CodeMirror's default placeholder extension doesn't modify the editor content but renders a widget decoration at position 0, which contains the placeholder text. Therefore a "multi-line" placeholder is really just a single-line one that happens to wrap and cause the single line to be taller.

We should file an official bug report (if necessary) but also look into alternative approaches.

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.
