### ISSUE TITLE
search: Missing results from dependencies search

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#33214]
Dependencies search relies on unindexed searching, since it would be too much for Zoekt to index every single revision of a dependency and package repos are generally smaller that normal repos.

After deploy Go dependency repos to production, I [tried to search](https://sourcegraph.com/search?q=context%3Aglobal+r%3Adeps%28%5Egithub%5C.com%2Fsourcegraph%2Fsourcegraph%24%29+r%3A%5Ego+ComputeProperty&patternType=literal&case=yes&trace=1) for a a method I knew existed in one of our dependencies.

While that produced no results, I scoped down the query to only dependency repos that matched "json", because I knew the repo that should have a match would be included in that smaller set.

[That worked](https://sourcegraph.com/search?q=context%3Aglobal+r%3Adeps%28%5Egithub%5C.com%2Fsourcegraph%2Fsourcegraph%24%29+r%3A%5Ego+r%3Ajson+ComputeProperty&patternType=literal&case=yes&trace=1).

After reproducing locally, I tracked this down to zoekt.PartitionRepos  [in here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/search/zoekt/indexed_search.go?L263).

It seems that for each page of resolved repos, we're limiting the number of unindexed searches to 200, which is a problem for dependencies search.

Would it be problem to increase this number to the page size of the repo pager so we never miss any results?

**Comment by sourcegraph-bot-2** [comment]
Heads up @jjeffwarner - the "team/search-core" label was applied to this issue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by tsenart** [comment]
Seems like this was the commit that introduced this logic: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/cad0dd70d57d43f15b3097f1acfec8e370409147?visible=4
