### ISSUE TITLE
Switch github client mock to use gomockgen

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#33232]
Instead of a custom mock [here](https://github.com/sourcegraph/sourcegraph/blob/5f58ccc3464734ae967b433c3cf8d405050ab337/enterprise/internal/authz/github/client.go#L62-L77) we can generate one using `gomockgen` like we do in other parts of the codebase.

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.
