### ISSUE TITLE
insights: Allow search contexts as filters to code insights (v0) 

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#33249]
We have an awesome prototype of the functionality here: https://www.loom.com/share/60aced6eff204c1babf2c972fa8240d3 . 

While this does not begin to solve all possible uses of Search Contexts + Code Insights, it's a nice start to enable some early uses and get user feedback. This would also solve [a couple of prospects' and customer+Code Insights prospects' direct needs](https://sourcegraph.productboard.com/feature-board/1793095-code-insights/features/8235634/insights), since not all groups of repos can be easily captured as single `repo:` filter. 

Additional background on this prototype [can be found here](https://sourcegraph.slite.com/app/docs/sAvsnfJT3RmKX9). There are valid permissions questions [we are slowly working through](https://docs.google.com/document/d/1B3A-PQTykOSnp6BtHZTbIFpSRrvbiV-0FrnukJeaM3A/edit) but they are not blocking, primarily because right now you can link someone to a search or search notebook with your personal user context and they can see it/run it (may not get the same results due to repo permissions, of course, but that's already the case for insights). 

So, 

## Goals of this initial version: 
1. Allow users to filter insights by context in the filter panel. Ideally, this works for any insight type that already has a filter panel (so everything but jit-scoped-search insights). If for some reason it doesn't work for capture groups, we should discuss alternatives. 
2. Allow users to save context filters on their insights, the same way repo filters work now. 

## Open questions: 
1. Can you filter a context and also attach a repo filter? (You can in Sourcegraph search, this "can you" is a question about what we can enable in Insights). 
2. Especially given point 1, we may need to modify the filter panel, or add a context option to it (longer term we can revisit redesigns as need be). cc @AlicjaSuska is this the type of smaller change we could design within 3-4 days?

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by Joelkw** [comment]
from @coury-clark – if we want to handle repo prefix, there are questions raised about the pinned revisions. We can extract repos, but we need to still educate about the differences. 

Decision for first scope: let's limit to just query type contexts, and communicate to users (design callout) this limitation.

**Comment by coury-clark** [comment]
Some questions from @AlicjaSuska  (moving here from a DM):

> I'd like to make sure I understand the [search context decision correctly](https://github.com/sourcegraph/sourcegraph/issues/33249#issuecomment-1084875080). My understanding is that user can either use the repo / -repo filters or choose context. Not combine both. Is that correct?

I don't think I've seen any decision on that. We would need to choose what the semantics are, whether we consider multiple filters to be required (AND) or optional (OR). In order to have mutual exclusion we'd have to also build that, so it's not free either.

> Also Joel mentioned:
> > Decision for first scope: let's limit to just query type contexts, and communicate to users (design callout) this limitation.
> 
What are query type contexts?

Query contexts are derived from a Sourcegraph query "prefix". You can see below. They don't include specific repositories, they match based on a query pattern.
<img width="891" alt="image" src="https://user-images.githubusercontent.com/5090588/161867546-014553b8-e1ed-4b45-9d03-7577d97f4fb0.png">

> Also, what did you mean by pinned revisions here?
>> from [@coury-clark](https://github.com/coury-clark) – if we want to handle repo prefix, there are questions raised about the pinned revisions. We can extract repos, but we need to still educate about the differences.

The non-query kind of search context allows a non-main branch revision to be "pinned", meaning it's always searched when the context is searched instead of the main branch. We won't be supporting this yet (or possibly ever).

**Comment by AlicjaSuska** [comment]
Thank you for moving this conversation and your reply @coury-clark. I've prepared designs for two possible variants:
- context AND regex filters
- context OR regex filters
Here is the [loom](https://www.figma.com/file/Ml5dtV9ni4mfffbfOfF9jg/?node-id=260%3A11) with the walkthrough and design details. I think that context AND regex filters create a better experience overall.

@Joelkw @coury-clark @vovakulikov

**Comment by Joelkw** [comment]
Thanks @AlicjaSuska ! Left comments on the figma. TL;DR I like the design pattern/use of space for the "OR" case but wonder if we can actually use it for the "AND" case, because I agree the AND case is a functional requirement/better experience.

**Comment by AlicjaSuska** [comment]
Thank you @Joelkw :) 
@Joelkw @coury-clark @vovakulikov fyi: I've added an option with [collapsable sections](https://www.figma.com/file/Ml5dtV9ni4mfffbfOfF9jg/Allow-search-contexts-as-filters-to-code-insights-(v0)-%2333249?node-id=1163%3A15096) as an alternative for 'context AND regex' variant.

**Comment by vovakulikov** [comment]
We probably want to ship changes from https://github.com/sourcegraph/sourcegraph/issues/32963 in this issue

**Comment by AlicjaSuska** [comment]
SCOPE UPDATE:
- in this issue, we will ship the minimal scope: add 'context' field without autocomplete and collapsable sections. See the [v.0 design](https://www.figma.com/file/Ml5dtV9ni4mfffbfOfF9jg/?node-id=246%3A11).
- in the next iteration, we will work on v.1: collapsable sections and autocomplete for context filed ([design](https://www.figma.com/file/Ml5dtV9ni4mfffbfOfF9jg/Allow-search-contexts-as-filters-to-code-insights-(v0)-%2333249?node-id=1163%3A15096))

---

CHANGES FOR V.0:

1. CORE 
- add 'context' input field above the existing input fields
- add placeholder for context field ('global [default]') - [design](https://www.figma.com/file/Ml5dtV9ni4mfffbfOfF9jg/Allow-search-contexts-as-filters-to-code-insights-(v0)-%2333249?node-id=1281%3A18394)
- change helper text above the fields to include info about the contexts and lint to [Docs](https://docs.sourcegraph.com/code_search/how-to/search_contexts#beta-query-based-search-contexts)

2. ADDITIONAL VISUAL IMPROVEMENTS
- Change the 'Defult filters applied. [link: Learn more]' to '[link: Defult filters] applied' and move it to the bottom section - [design](https://www.figma.com/file/Ml5dtV9ni4mfffbfOfF9jg/Allow-search-contexts-as-filters-to-code-insights-(v0)-%2333249?node-id=1281%3A26780)
- add 'Clear filters' button to the header; disable until any of the input fields is filled out.
- disable 'reset' buttons until input filed is filled out
- add divider above the bottom section with buttons
- make sure that the logic regarding 'default filters' works as designed ([see the details here](https://www.figma.com/file/Ml5dtV9ni4mfffbfOfF9jg/Allow-search-contexts-as-filters-to-code-insights-(v0)-%2333249?node-id=1281%3A26570))

**Comment by AlicjaSuska** [comment]
@Joelkw @vovakulikov I've created an issue for v.1 (the follow up for this one) - #33830
