### ISSUE TITLE
Fix illegal package names entering database

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/sourcegraph#33251]
Recently, we get [an error](https://app.datadoghq.com/logs?query=service%3Arepo-updater%20npm&agg_q=status%2Cservice&cols=host%2Cservice&event=AQAAAX_ZbDtChTvkeQAAAABBWF9aYkVHV0FBQThYSlRDWjJtbnhnQTc&index=&messageDisplay=inline&sort_m=%2C&sort_t=%2C&stream_sort=desc&top_n=10%2C10&top_o=top%2Ctop&viz=pattern&from_ts=1645717630136&to_ts=1645804030136&live=true) like so:

```
t=2022-03-30T06:03:43+0000 lvl=eror msg="failed to parse npm package name retrieved from database" package=@builder.io/qwik/server error="expected dependency in (@scope/)?name@version format but found @builder.io/qwik/server@0"
```

While the parsing failure is understandable, the problem shouldn't have happened "by construction" -- it shouldn't be possible to construct packages with invalid names, and hence it a package with an invalid name shouldn't have been entered into the database. So it seems like validity checks are missing in one or more places.

**Comment by sourcegraph-bot-2** [comment]
Heads up @macraig - the "team/code-intelligence" label was applied to this issue.
