### ISSUE TITLE
Fix styles for file container bottom gap caused by "quick start" tour

### ISSUE THREAD

**Issue by erzhtor** [sourcegraph/sourcegraph#33273]
Reported by @eseliger in [slack](https://sourcegraph.slack.com/archives/C01LZKLRF0C/p1648721326168159)

> Found a little CSS bug, the new quickstart guide is pushing down the scroll container for the files, so that there’s a weird gap at the end of the page

| | |
| --: | :--|
| ![image](https://user-images.githubusercontent.com/6717049/161044720-c05295ab-82ee-4fad-929f-2552d6c69ff4.png) | ![image](https://user-images.githubusercontent.com/6717049/161044752-e776eac3-b94e-42dd-be42-5eb70fa49e2c.png) |

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @rrhyne @jjinnii @ryankscott - the "team/growth-and-integrations" label was applied to this issue.
