### ISSUE TITLE
Support for dependency search

### ISSUE THREAD

**Issue by eugeniaft** [sourcegraph/sourcegraph#33287]
## Problem to solve

Allow users to search dependencies across repositories.

## Measure of success

- Total number of repo:dependencies(..) queries on Cloud and on-prem.
- Total number of lockfile indexers (JS/TS, Go, JVM, …).
- Total number of customers who have expressed explicit interest in this functionality to help with “Accelerate developer onboarding” and “Resolve incidents faster”.

## Solution summary

In collaboration with Code Intelligence, the team is working on adding support for dependency search. Dependency search adds indexed, language specific support for packages and dependencies. [See RFC 593](https://docs.google.com/document/d/1SkM8CG0IksvPEKRBRVLKipiRJTopx6Vq_hSWRJ9NyKs/edit#heading=h.trqab8y0kufp). The initial work has focused on adding support for JavaScript/Typescript with npm and Yarn as well as supporting Go dependencies. This has provided an opportunity to gather feedback from internal and external users.

## What specific customers are we iterating on the problem and solution with?

- TO DO

## Impact on use cases

All of them

## Delivery plan

- [ ] TO DO

**Comment by jyavorska** [comment]
@eugeniaft this is marked as done but still open. Should it be closed?
