### ISSUE TITLE
preprod frontend smoke tests are broken

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#33282]
It looks they're broken. I suppose that should be a quick fix! 

<img width="1909" alt="image" src="https://user-images.githubusercontent.com/10151/161075668-3ddf64c6-aa41-486f-ae0f-b832c2588c63.png">

**Comment by valerybugakov** [comment]
Fixed it by https://github.com/sourcegraph/smoke-tests/commit/b2bc64c38c19de3d690110d251117fbd8118cc38. 
It seems stable for me locally: executed 100 times without failure. Let me know if you bump into it again.

**Comment by valerybugakov** [comment]
Cc @umpox to keep you in the loop.
