### ISSUE TITLE
Move gitserver commands onto the client

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#33280]
Move all functions in [vcs/git](https://github.com/sourcegraph/sourcegraph/tree/main/internal/vcs/git) that call the gitserver client into the client itself.

We should move all the exported functions over as well as any associated tests and helper functions.

[Search](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+gitserver.NewClient+file:vcs/git+-file:_test+&patternType=literal) showing all the places where we create a gitserver client in the `vcs/git` should give us a good list of candidates.

See this [example PR](https://github.com/sourcegraph/sourcegraph/pull/33177)

[Insights here](https://k8s.sgdev.org/insights/dashboards/ZGFzaGJvYXJkOnsiSWRUeXBlIjoiY3VzdG9tIiwiQXJnIjo3MjcyNDN9)

More details can be seen in the [refactoring proposal](https://docs.google.com/document/d/1hE8NHeNiEJkTDnRm0EihSM-nvQiqra5Y-fntP1K0rv8/edit#)

*Please convert an item to a task below before taking it so that we don't duplicate work*
(You do that by hovering over it and clicking the little circle that appears)

- [x] #37511
- [x] #37512
- [x] #37513
- [x] #37514
- [x] #33355
- [x] #33346
- [x] #37516
- [x] #37515
- [x] #35433
- [x] #37517
> All items above need `git.GetCommit ported ^`
- [x] Move vcs/git.GetDefaultBranch to gitserver.Client
- [x] Move vcs/git.GetDefaultBranchShort to gitserver.Client
- [x] Move vcs/git.HasCommitAfter to gitserver.Client
> All items above need `git.ResolveRevision ported ^`
- [x] #33597
- [x] Move vcs/git.ListFiles to gitserver.Client
- [x] Move vcs/git.LsFiles to gitserver.Client
> All items above need support for `MakeGitRepository` that needs to run a gitserver instance
- [x] #33359
- [x] #33439
- [x] #33586
- [x] #33313
- [x] #33775
- [x] #36289
- [x] Move vcs/git.NewFileReader to gitserver.Client
- [x] #33604
- [x] Move vcs/git.ReadFile to gitserver.Client
- [x] Move vcs/git.RefDescriptions to gitserver.Client
- [x] #36368
- [x] #34048
- [x] Move vcs/git.GetBehindAhead to gitserver.Client
- [x] #37561
- [x] #36436
- [x] #36535
- [x] #35627

*Work needed to unblock running tests in gitserver package*
- [x] #34167
- [x] Use interface instead of implementation in GitCommand function
- [x] #34258
- [x] Use new implementation in tests

**Comment by ryanslade** [comment]
cc @vrto

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.

**Comment by mollylogue** [comment]
@ryanslade Would any of these be good things to pick up? Or is @vrto going to be tackling all of them? Just looking for my next thing to work on 👀

**Comment by ryanslade** [comment]
They're open for anyone to pick up, please do :) They're nice small tasks that we can hopefully fit into a little bit of debt tackling time :)

**Comment by vrto** [comment]
@mollylogue I'll try to pick some but defo not all 😅 Your involvement is more than welcome!

**Comment by mollylogue** [comment]
I've picked up git.LsFiles/git.ListFiles/etc, basing off of @sashaostrikov 's unmerged branch that implements the helper functions for testing.

**Comment by mollylogue** [comment]
Hefty draft PR [here](https://github.com/sourcegraph/sourcegraph/pull/35888) for moving over contents of the git/commits.go file. I'm gonna keep chipping away at it (only thing left is just figuring out what's wrong with the unit tests)

**Comment by mollylogue** [comment]
https://github.com/sourcegraph/sourcegraph/pull/36928
