### ISSUE TITLE
lsif-go failing on the Sourcegraph repo

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/sourcegraph#33285]
Example [failure](https://github.com/sourcegraph/sourcegraph/runs/5769278399?check_suite_focus=true).

Thorsten points out that this [started failing with Squirrel](https://github.com/sourcegraph/sourcegraph/actions/workflows/lsif-go.yml?query=branch%3Amain).

Error message:

```
error: failed to index: failed to load packages: packages.Load: err: exit status 1: stderr: go build github.com/smacker/go-tree-sitter/java: build constraints exclude all Go files in /go/pkg/mod/github.com/smacker/go-tree-sitter@v0.0.0-20220209044044-0d3022e933c3/java
```

[Original Slack thread](https://sourcegraph.slack.com/archives/CHXHX7XAS/p1648722914210009).

**Comment by sourcegraph-bot-2** [comment]
Heads up @macraig - the "team/code-intelligence" label was applied to this issue.
