### ISSUE TITLE
Sourcegraph Extensions do not work on HTTP instances

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#33286]
- **Sourcegraph version:**  confirmed on 3.37.0 & 3.38.0 
- **Platform information:**  all instances that are not deployed in secure contexts (HTTPS)

#### Steps to reproduce:

1. Set up an instance that does not run in secure contexts (HTTPS)
2. Run Sourcegraph extensions, git-extras for example

#### Expected behavior:
Extensions are shown to be enabled in the side bar, and are actually running and working (code-intel, git extras etc):
![image](https://user-images.githubusercontent.com/68532117/161103640-fb406d21-8086-4003-ad8d-1cc704110eb1.png)

#### Actual behavior:
Extensions are shown to be enabled in the side bar but do not work. 

In the console, the extensions are shown to be activating with the following error `crypto.subtle is undefined`:
![image](https://user-images.githubusercontent.com/68532117/161104201-61c98ffb-2d0e-4479-acda-abc6b98202b8.png)

But both code-intel and git extras are not working:
![image](https://user-images.githubusercontent.com/68532117/161104497-9b569cb2-3396-4857-8722-1cd6d0169a49.png)

After the investigation carried in https://github.com/sourcegraph/customer/issues/784, we believe the `crypto.subtle` error coming from the [hashCode](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@v3.37.0/-/blob/client/shared/src/api/extension/activation.ts?L174) function that is being run during the activating process is causing the issue. This error occurs as `crypto.subtle` is available only in [secure contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts) (HTTPS) [according to the Mozilla docs](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/subtle).

This is preventing the extensions from running on air-gapped / non-secured instances.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @rrhyne @jjinnii @ryankscott - the "team/growth-and-integrations" label was applied to this issue.
