### ISSUE TITLE
insights: handle alerts for insights consuming streaming search

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#33291]
When a series is set to `search-stream` mode we are [currently ignoring alerts.](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@a717b2db19ef4c0e25519ea689e57c2446f74ce8/-/blob/enterprise/internal/insights/query/streaming/decoder.go?L26) We should try to achieve some feature parity with the [GraphQL errors that are available and currently handled](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@a717b2db19ef4c0e25519ea689e57c2446f74ce8/-/blob/enterprise/internal/insights/background/queryrunner/work_handler.go?L134-153).

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by coury-clark** [comment]
Accidentally created duplicate
