### ISSUE TITLE
debt: GraphQL backend ConnectionArgs can have a negative first value

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#3329]
This shouldn't be allowed, and will likely lead to weird DB behaviour / panics if someone did that.

**Comment by keegancsmith** [comment]
I checked out what GitHub does, and they also use an `Int` as the type for `first`. So they return an error if you specify a negative value:

```json
"errors": [
    {
      "type": "INVALID_PAGINATION",
      "path": [
        "repository",
        "defaultBranchRef",
        "target",
        "history"
      ],
      "locations": [
        {
          "line": 6,
          "column": 11
        }
      ],
      "message": "`first` on the connection cannot be less than zero."
    }
  ]
```

So I think we can just update our ConnectionArgs type to return an error when we try and set a db.LimitOffset.

cc @sqs I think you added our `graphqlutil` package. cc @tsenart who pointed this out when reviewing my PR.

**Comment by indradhanush** [comment]
I researched this issue and as of this moment, the `batchChanges` API [handles the edge case and returns an error](https://github.com/sourcegraph/sourcegraph/blob/50f691da487632bb62199b6c91b3ed120ad6dd6d/enterprise/internal/batches/resolvers/resolver.go#L999-L1014) like:

```
{
  "errors": [
    {
      "message": "first param -1 is out of range (min=0, max=10000)",
      "path": [
        "batchChanges"
      ]
    }
  ],
  "data": null
}
```

The other APIs don't seem to ignore the error silently and return a response like:

```
{
  "data": {
    "repositories": {
      "nodes": []
    }
  }
}
```

While we _should_ return helpful and descriptive error messages from all of our APIs, the initial concern in this ticket was about avoiding silent writes to the database with negative values or avoiding panics in our call stack. And as we don't have these unintended side effects at the moment, it is safe to close this issue.
