### ISSUE TITLE
insights: handle errors in streaming search mode

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#33290]
When a series is set to `search-stream` mode we are [currently ignoring alerts.](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@a717b2db19ef4c0e25519ea689e57c2446f74ce8/-/blob/enterprise/internal/insights/query/streaming/decoder.go?L26) We should try to achieve some feature parity with the [GraphQL errors that are available and currently handled](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@a717b2db19ef4c0e25519ea689e57c2446f74ce8/-/blob/enterprise/internal/insights/background/queryrunner/work_handler.go?L134-153).

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by leonore** [comment]
To keep track of the work involved: we need to handle events where the query limit is hit, and we have cloning/missing/timed out errors. The equivalent information for streaming search is held in the `Stats` field in [`SearchEvent`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/internal/search/streaming/stream.go?L14:6).

**Comment by leonore** [comment]
API events [are returned a bit differently ](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/internal/search/streaming/api/progress.go?L22)that in-process, so we'll have to go through the `SkippedReasons` for `Skipped` events using `OnSkipped`: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/internal/search/streaming/api/types.go?L53:6
