### ISSUE TITLE
Upgrade to the latest version of React

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#33302]
## Problem statement

Our `react` version is outdated, and we need to upgrade to the latest one to use new features.

## Success criteria

React version is upgraded to the latest version

## Implementation details

Let's split this work into multiple pull requests:
1. Upgrade `react` to [17.0.2](https://www.npmjs.com/package/react/v/17.0.2)
2. Upgrade to the latest version of [the JSX transform](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#how-to-upgrade-to-the-new-jsx-transform) and remove redundant `React` imports.
3. Upgrade to [the latest `react` version](https://www.npmjs.com/package/react) and migrate to [the new root API](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-client-rendering-apis).

If you encounter issues with the new JSX transform integration, please ping @valerybugakov to look into it together.

## Time estimate

- Pull requests with ~450 lines changed should take **6 hours** at maximum. Ping the reviewer in the spec pull request if time-consuming changes are required.
- Split the work into multiple pull requests if the total diff is bigger than 450 lines of code.

**Comment by gitstart-sourcegraph** [comment]
@valerybugakov here are the checklist of things that needs to be done to complete `Upgrade to the latest react version and migrate to the new root AP`

1. Upgrade react testing library
2. Support usage of `children` props in most components, since inbuilt support was removed in v18

**Comment by valerybugakov** [comment]
@gitstart-sourcegraph, thanks for the heads up!

1. Should it be done together with the `react` upgrade? If not, let's do it in a separate PR.
2. Could you take a look at using this codemod in a separate PR https://github.com/eps1lon/types-react-codemod#implicit-children?

**Comment by gitstart-sourcegraph** [comment]
Thanks @valerybugakov would try out the suggestions.

**Comment by gitstart-sourcegraph** [comment]
@valerybugakov After resolving upgrades [noted here](https://github.com/sourcegraph/sourcegraph/issues/33302#issuecomment-1112875877), We have another package (`react-stripe-elements`) which seam to also throw error on react v18, which needs to be upgraded as well.
WDYT about migrating it to `@stripe/react-stripe-js` in  a separate PR?

**Comment by valerybugakov** [comment]
@gitstart-sourcegraph,

> WDYT about migrating it to @stripe/react-stripe-js in a separate PR?
Sounds good!

**Comment by gitstart-sourcegraph** [comment]
## Related Issues
https://github.com/sourcegraph/sourcegraph/issues/35349
