### ISSUE TITLE
Remove teams beta waitlist from sign-up flow

### ISSUE THREAD

**Issue by ryankscott** [sourcegraph/sourcegraph#33309]
The upcoming launch of teams (April 21st) will move to our open-beta phase meaning any user will be able to create an organization and we will no longer have a waitlist.

We need to remove the sign-up form that was previously there. ~and give users the option to create a team. If they want to, take them to the onboarding flow for creating an organization / team.~

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @rrhyne @jjinnii @ryankscott - the "team/growth-and-integrations" label was applied to this issue.
