### ISSUE TITLE
Fix "Open on Sourcegraph" button for files with symbols in the filePath

### ISSUE THREAD

**Issue by erzhtor** [sourcegraph/sourcegraph#33310]
Looks like the "Open on Sourcegraph" button doesn't correctly handle files with symbols in filePath, which causes Sourcegraph to show 404 when clicking it.
Example file: https://gitlab.com/pedropombeiro/dotfiles/-/blob/master/.shellrc/zshrc.d/functions/gdk.sh%23%23class.Work#L55-L117

<img width="1290" alt="image" src="https://user-images.githubusercontent.com/6717049/161263138-921abadc-f0cd-4c37-92f6-37b73c698593.png">

<img width="1581" alt="image" src="https://user-images.githubusercontent.com/6717049/161263315-b420d506-2883-4608-88c3-3ce4dc3ec26f.png">

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @rrhyne @jjinnii @ryankscott - the "team/growth-and-integrations" label was applied to this issue.
