### ISSUE TITLE
code-intel: Whitespace characters are sometimes hoverable

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#33328]
- Visit https://sourcegraph.com/github.com/sourcegraph/lsif-java@5d7ccd55d13282980b843c94dbe5ce88786e2cc3/-/blob/lsif-semanticdb/src/main/java/com/sourcegraph/lsif_semanticdb/SignatureFormatter.java?L288

<img width="183" alt="CleanShot 2022-04-01 at 17 01 38@2x" src="https://user-images.githubusercontent.com/1387653/161352503-e7fe7943-3b3d-4af7-bf7c-2a5d883c3fa1.png">

Not sure exactly what's going on here, but I'm guessing it's an off-by-1 issue. I noticed this right after deploying [local code intel with tree-sitter](https://github.com/sourcegraph/sourcegraph/pull/32122), so that's the first place I'd look.

**Comment by efritz** [comment]
Is this reproducible on a particular repository? Where was that screenshot from?

**Comment by chrismwendt** [comment]
Added a link in the description ☝️
