### ISSUE TITLE
Investigate syntax highlighting timeouts for Dockerfiles and protobuf files

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/sourcegraph#33323]
For a customer, we've seen [syntax highlighting timeouts for Dockerfiles and protobuf files](https://sourcegraph.slack.com/archives/CHXHX7XAS/p1648841249803679?thread_ts=1648790924.079399&cid=CHXHX7XAS). We don't have access to minimal examples, but we should probably look at Honeycomb and see if we have any examples for highlighting timeouts for these files. If so, that would be helpful in identifying common patterns causing timeouts and potentially identifying a fix.

At the time of writing this (2022 Apr 1) both Dockerfiles and protobuf files are marked as having ["in-development" tree-sitter grammars](https://tree-sitter.github.io/tree-sitter/#available-parsers).

**Comment by sourcegraph-bot-2** [comment]
Heads up @macraig - the "team/code-intelligence" label was applied to this issue.

**Comment by varungandhi-src** [comment]
In the past 60 days, I looked at Honeycomb and only saw highlighting timeouts for Dockerfile and protobuf respectively for these files.

- Dockerfile
    - https://sourcegraph.com/github.com/spiffe/spire@49a49e8ed92d030e5e4121418ebc40b59e0b585d/-/blob/test/integration/suites/nested-rotation/Dockerfile

- Protobuf
    - https://sourcegraph.com/github.com/argoproj/argo-workflows@dee7ec5e190a0ee17185f461db12506a467ad89f/-/blob/pkg/apis/workflow/v1alpha1/generated.proto
    - https://sourcegraph.com/github.com/dfinity/ic@86a428d07fd25fb23d8813ba4bc72690b9cf9b54/-/blob/rs/nns/governance/proto/ic_nns_governance/pb/v1/governance.proto
    - https://sourcegraph.com/github.com/dfinity/ic@86a428d07fd25fb23d8813ba4bc72690b9cf9b54/-/blob/rs/sns/swap/proto/ic_sns_swap/pb/v1/swap.proto

However, those highlight just fine right now. It might be related to some kind of load issue rather than being a grammar issue. Closing this as no longer reproducing.
