### ISSUE TITLE
Capture product feature/stage usage counts in pings

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#3333]
#### Feature request description

Add a count of users using Sourcegraph by software development lifecycle stage (Manage, Plan, Code, Review, Monitor, Configure, Deploy, Package, Verify, Secure, Automate) to Sourcegraph [server pings](https://docs.sourcegraph.com/admin/pings). This mapping will be based on product feature usage where possible. 

#### Is your feature request related to a problem? If so, please describe.

Sourcegraph can be used in many different ways. It's critical to understand what features are actually being used, and for what purpose, to be able to prioritize product development (to make Sourcegraph better). 

#### Additional context

WIP planning doc: https://docs.google.com/document/d/19SkGnf0ClEwMuu1xWH5Nz_DSTNPukgLpPLNQL1kuWgM/edit#

CC @sqs @KattMingMing

**Comment by slimsag** [comment]
Fixed by #3366
