### ISSUE TITLE
Quick Start tour feedback based updates and fixes. Part 1

### ISSUE THREAD

**Issue by erzhtor** [sourcegraph/sourcegraph#33339]
- [x] Make the checkbox icon-color when at 0 completed and make the distance between the icon and text 4px. [Figma](https://www.figma.com/file/hpL5H1kmNOgSJdnFDUpN9L/AUTHenticated--Getting-started-checklist?node-id=370%3A9986)
- [x] Move inside Quick start when displayed vertically. [Figma](https://www.figma.com/file/hpL5H1kmNOgSJdnFDUpN9L/AUTHenticated--Getting-started-checklist?node-id=370%3A9986)
- [x] Fix styles for file container bottom gap caused by "quick start" tour
- [x] Fix styles for language selector in dark mode/theme
- [x] Disable SignUp/IDE/BEXT install CTA on results/file pages when showing tour info panel
- [x] Remove "~__Quickly__~ Understand a new codebase", the word isn’t worth the line break and alignment issues.

See [slack thread](https://sourcegraph.slack.com/archives/C0217T4HW3X/p1648804069805999)

> Moved rest of the changes/updates to a separate issue #33650

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/growth-and-integrations" label was applied to this issue.
