### ISSUE TITLE
[Accessibility]: Global color contrast

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#33343]
### Problem description

We need to address areas of global color contrast.

Note: The algorithm that determines color contrast will be changed in WCAG 3.0, we should consider this.

See this thread for issues related to the WCAG 2.1 vs WCAG 3.0 color contrast algorithm: https://twitter.com/DanHollick/status/1417895151003865090

Relevant GitHub issue: https://github.com/w3c/wcag/issues/695

### Expected behavior

- Our application passes color contrast checks.

**Comment by Myndex** [comment]
Hello, I am a co-author of WCAG 3 and wrote the section on contrast, and developed the APCA.

I created a version called "Bridge-PCA" which is backwards compatible to WCAG_2 contrast, but uses APCA technology, and so corrects many of the WCAG_2 problems, and aligns better with the future guidelines.

In particular, WCAG_2 contrast can not calculated for "dark mode" but Bridge-PCA can.

The [Bridge-PCA repo](https://github.com/Myndex/bridge-pca/blob/master/README.md) is here on GitHub
_NPM Install:_ ` npm i bridge-pca `

For questions, comments, discussion, please see the [discussion tab at the main APCA repo.](https://github.com/Myndex/SAPC-APCA/discussions)

Thank you

Andy

**Comment by felixfbecker** [comment]
Not sure if there is anything actionable left on this issue, or if this is all captured in individual issues.
