### ISSUE TITLE
Tracking issue: sg maintenance

### ISSUE THREAD

**Issue by stefanhengl** [sourcegraph/sourcegraph#33353]
### Plan
Gitserver periodically runs various cleanup jobs on the repositories. One of
those jobs is "sg maintenance". 

The goal of "sg maintenance" is to optimize repositories mainly  by repacking
and pruning. It is on per default and replaces the legacy "git gc" job. 

Recently we have seen OOMs on smaller Soucegraph instances. The OOMs
directly trace back to "sg maintenance". Logs shows that "sg maintenance"
exits with code 137.  

At the same time, we have seen an increase in I/O since we switched from "git gc"
to "sg maintenance".

This issue tracks the progress we are making towards resolving the issue and improving "sg maintenance".

### Tracked issues / PRs

- #32841
- #33079 
- #33217 
- #33259 
- #33281 
- #33304 
- #33432
- #35939

**Comment by sourcegraph-bot-2** [comment]
Heads up @jjeffwarner - the "team/search-core" label was applied to this issue.

**Comment by keegancsmith** [comment]
@stefanhengl I believe all the work done for this? I'll give you the honour of hitting the close button.
