### ISSUE TITLE
Show function name in UI when navigating code

### ISSUE THREAD

**Issue by indradhanush** [sourcegraph/sourcegraph#33368]
#### Feature request description

Indicate function in the UI whose code is currently visible on the screen similar to what is seen in most modern IDEs.

![image](https://user-images.githubusercontent.com/2682729/161596082-60dd0c7b-ff52-414d-879f-f61ee33493a3.png)
![image](https://user-images.githubusercontent.com/2682729/161596090-f6a14f98-a791-4186-8b5d-df94a13b96d0.png)

**Comment by sourcegraph-bot-2** [comment]
Heads up @macraig - the "team/code-intelligence" label was applied to this issue.

**Comment by camdencheek** [comment]
We can consider this aas part of the redesign in #60428, but closing in the mean time
