### ISSUE TITLE
Use pinned container versions for auto-indexing by default

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/sourcegraph#33369]
Currently, we default to using the latest tags for the Docker images for auto-indexers. `lsif-typescript:autoindex` and `lsif-go:latest`. We should pin the images being used. That makes development on the indexers a little more painful for us, but it seems like the better default for on-prem/enterprise customers.

**Comment by sourcegraph-bot-2** [comment]
Heads up @macraig - the "team/code-intelligence" label was applied to this issue.

**Comment by chrismwendt** [comment]
Why is pinning a better default for on-prem? I imagine that lead to a lot of customers being on old versions of indexers and maintenance headaches.

**Comment by varungandhi-src** [comment]
It's the same reason as using lockfiles and using pinned versions elsewhere: predictability. Being able to upgrade dependencies at your own pace (which should be easy to do!) means that you can stick to a version of an indexer which works, instead of the configuration changing underneath you.

E.g. if there was a bug that slipped in to the latest version of an indexer, we'd have the customer run into the same version too.

cc @efritz

**Comment by efritz** [comment]
@varungandhi-src Sorry this took SOOO long to get up to the top of the backlog. I'm working on setting the defaults to a pinned version now (and making it configurable via site-config). Can you give me the tags/sha hashes you'd like me to use for the following indexers?

```
	"clang":      "sourcegraph/lsif-clang",
	"java":       "sourcegraph/scip-java",
	"lsif-go":    "sourcegraph/lsif-go:latest",
	"python":     "sourcegraph/scip-python:autoindex",
	"rust":       "sourcegraph/lsif-rust",
	"typescript": "sourcegraph/scip-typescript:autoindex",
```
