### ISSUE TITLE
Repository shows up as empty when "disableAutoGitUpdates" is true

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#3336]
Repro steps:
• Set `"disableGitAutoUpdates": true`
• Add Gitolite external service w/ some repositories
• Visit repo on Sourcegraph, observe "Empty repository"
• Go to repo settings mirroring page, observe an error. (After merging https://github.com/sourcegraph/sourcegraph/pull/3334, you'll see the error below. Before merging that, the error you see is a JSON unmarshalling error.)

![image](https://user-images.githubusercontent.com/1646931/55851685-832dd700-5b0e-11e9-8ebc-7ec965660a9d.png)

I can fix the issue by setting `"disableGitAutoUpdates": false`

The specific error message is the error gitserver returns, because the repo directory does not yet exist. (It's trying to cd into that directory to find the clone URL, but it doesn't exist.) In theory, gitserver would kick off a `git clone` in that scenario, but it doesn't appear to.

## Investigation

* [This](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/pkg/gitserver/client.go#L468:18&tab=references) is the method that generates the error shown in the UI. It errors because it attempts to compute the repo remote URL by cd'ing into a directory (the gitserver directory for the repo) that doesn't exist.
* [This enqueue-repo-update handler](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/gitserver/server/server.go#L377:18&tab=references) is invoked to kick off a clone on gitserver. It never fires when `disableAutoGitUpdates` is true.
* [This](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@f6a6de81d2a24bb9cc14e4fae872b33bb6b35f13/-/blob/cmd/frontend/internal/app/ui/handlers.go#L188:37) is a code path that hits `enqueue-repo-update` regardless, but it only activates when the repo already exists in gitserver. It's possible that this should fire regardless of whether the repo has already been cloned.

**Comment by beyang** [comment]
@keegancsmith @tsenart I've looked into this a fair bit (debug branch `bl/3.2-patch`), but there are pieces I'm missing about how repo-updater is supposed to work / what its contract should be / what triggers gitserver to clone a repo. Empirically, it appears to be the case that directly visiting a repo page no longer triggers a clone if the repo doesn't already exist on gitserver. Is that expected behavior?

If this makes sense for one of you to own, let me know; otherwise, I'll continue looking into this tomorrow.

**Comment by tsenart** [comment]
> Empirically, it appears to be the case that directly visiting a repo page no longer triggers a clone if the repo doesn't already exist on gitserver. Is that expected behavior?

When `disableGitAutoUpdates` is set to `true`, repo-updater doesn't trigger any Git updates, either via periodic syncing or through explicit visits to the repo.

This was introduced here: https://github.com/sourcegraph/sourcegraph/pull/2094

**Comment by beyang** [comment]
Where do we expect `EnqueueRepoUpdate` to be called from? Can it be called from anywhere?

**Comment by beyang** [comment]
Ah, the difference appears to be that the clone URL for Gitolite repos is only made available in *some* cases.

**Comment by tsenart** [comment]
@beyang: Answered your questions in the PR.

**Comment by keegancsmith** [comment]
@beyang Are there any answers missing from the PR? 

Meta: What is a good place to store this sort of information which is longer lived, and documents a poor architecture we plan on improving.

**Comment by tsenart** [comment]
> Meta: What is a good place to store this sort of information which is longer lived, and documents a poor architecture we plan on improving.

I think the issue related to cleaning up this stuff would be a good place.

**Comment by beyang** [comment]
> Meta: What is a good place to store this sort of information which is longer lived, and documents a poor architecture we plan on improving.

For things pertaining to the internal architecture of the repo-updater service, I'd say long-term place would be package doc of the `cmd/repo-updater` package. For architecture of how repo-updater and other services interact, top-level dev README maybe?
