### ISSUE TITLE
Drop Datadog features we are not using

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#33367]
We need to uninstall a few features that we do not plan to use:

- [ ] Cloud SIEM
- [ ] [Network](https://docs.datadoghq.com/network_monitoring/performance/setup/?tab=agentlinux#setup)

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/cloud-devops - the "team/devops" label was applied to this issue.

**Comment by ferozsalam** [comment]
@daxmc99 I have disabled the PubSub push to Datadog, which should hopefully end our use of the Cloud SIEM

**Comment by daxmc99** [comment]
Verified we are no longer using these services
