### ISSUE TITLE
RFC 619: (M7) Consolidate dependencies service

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#33378]
Implements a portion of [RFC 619: Code Intelligence Data Platform](https://docs.google.com/document/d/1AjZ_d0nJVHbV75IH3jZRkrGXhsv_AXp2kS4nrw2SAQ8).

Extract code that deals with dependencies from the existing symbols service across the dependencies API boundary.

**Comment by sourcegraph-bot-2** [comment]
Heads up @macraig - the "team/code-intelligence" label was applied to this issue.

**Comment by efritz** [comment]
Closing explicit order; this will happen naturally as we interact between services.
