### ISSUE TITLE
RFC 619: (M2) Initial documents service implementation

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#33373]
Implements a portion of [RFC 619: Code Intelligence Data Platform](https://docs.google.com/document/d/1AjZ_d0nJVHbV75IH3jZRkrGXhsv_AXp2kS4nrw2SAQ8).

Implement the documents service as described in the [RFC's instructions](https://docs.google.com/document/d/1AjZ_d0nJVHbV75IH3jZRkrGXhsv_AXp2kS4nrw2SAQ8/edit#bookmark=id.kiktif2fg5im).

**Comment by sourcegraph-bot-2** [comment]
Heads up @macraig - the "team/code-intelligence" label was applied to this issue.

**Comment by efritz** [comment]
Rolled documents service into codenav.
