### ISSUE TITLE
RFC 619: (M6) Initial auto-indexing service implementation

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#33377]
Implements a portion of [RFC 619: Code Intelligence Data Platform](https://docs.google.com/document/d/1AjZ_d0nJVHbV75IH3jZRkrGXhsv_AXp2kS4nrw2SAQ8).

Implement the auto-indexing service as described in the [RFC's instructions](https://docs.google.com/document/d/1AjZ_d0nJVHbV75IH3jZRkrGXhsv_AXp2kS4nrw2SAQ8/edit#bookmark=id.ijn99z7ul92).

**Comment by sourcegraph-bot-2** [comment]
Heads up @macraig - the "team/code-intelligence" label was applied to this issue.
