### ISSUE TITLE
RFC 619: (M1) Generate service skeletons

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#33372]
Implements a portion of [RFC 619: Code Intelligence Data Platform](https://docs.google.com/document/d/1AjZ_d0nJVHbV75IH3jZRkrGXhsv_AXp2kS4nrw2SAQ8).

Generate a trivial service skeleton (including service method and transport definitions, but no implementations) for the services in the linked RFC:

- symbols 
  - #33616
  - #34239
- documents 
  - #33612
  - #34243
- dependencies 
  - #34025
- uploads 
  - #33613
  - #34242
- policies 
  - #33615
  - #34240
- auto-indexing 
  - #33614
  - #34241

**Comment by sourcegraph-bot-2** [comment]
Heads up @macraig - the "team/code-intelligence" label was applied to this issue.
