### ISSUE TITLE
Remove usage of submodules for tree-sitter grammars

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/sourcegraph#33384]
We currently have [three git submodules for tree-sitter grammars](https://github.com/sourcegraph/sourcegraph/blob/main/.gitmodules).

- [x] [tree-sitter-go](https://github.com/tree-sitter/tree-sitter-go)
- [x] [tree-sitter-sql](https://github.com/m-novikov/tree-sitter-sql)
- [x] [tree-sitter-c-sharp](https://github.com/tree-sitter/tree-sitter-c-sharp)

Keegan reported that ["From eyeballing a few runs what I can tell we are paying a cost of 1 minute every step"](https://sourcegraph.slack.com/archives/C01N83PS4TU/p1649074147208429). That seems bad. Moreover, it looks like [it isn't possible to configure the usage of submodules on a per-job in Buildkite](https://github.com/buildkite/agent/issues/1053). 

Also, submodules add friction to the development experience.

All of these crates are published on crates.io, which is a good sign. However, some of the releases are fairly old. We may be able to submit patches upstream to cut new releases. In the meantime, we could use git-based dependencies in Cargo.toml. If the crates are configured correctly to build with a pure cargo invocation (they should be if they’re on crates.io).

**Comment by sourcegraph-bot-2** [comment]
Heads up @macraig - the "team/code-intelligence" label was applied to this issue.
