### ISSUE TITLE
insights: extend GraphQL API to support search context filters

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#33381]
Parent issue https://github.com/sourcegraph/sourcegraph/issues/33249

Support filters on an insight view that map to search contexts that are limited to filtering **repositories** on the `repo` values in query prefix contexts. If a context is provided that does not have a query prefix, we can silently accept it (and it will effectively no-op), or we could consider returning an error on the edit mutation.

This will not include `file` or any other file in the query prefix, since we do not currently support post-hoc filtering on anything other than repository name.

Extend the input filters object https://sourcegraph.com/github.com/sourcegraph/sourcegraph@81107520254738bc78021cc6dc7646d5d211d885/-/blob/cmd/frontend/graphqlbackend/insights.graphql?L616:7
to include an array of context names

``` gql
input InsightViewFiltersInput {
    """
    A regex string for which to include repositories in a filter.
    """
    includeRepoRegex: String
    """
    A regex string for which to exclude repositories in a filter.
    """
    excludeRepoRegex: String

    searchContexts: [String!]
}
```

And extend the response object https://sourcegraph.com/github.com/sourcegraph/sourcegraph@81107520254738bc78021cc6dc7646d5d211d885/-/blob/cmd/frontend/graphqlbackend/insights.graphql?L939:6 to include the current contexts.

``` gql
type InsightViewFilters {
    """
    A regex string for which to include repositories in a filter.
    """
    includeRepoRegex: String

    """
    A regex string for which to exclude repositories from a filter.
    """
    excludeRepoRegex: String

    searchContexts: [String!]
}
```

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
