### ISSUE TITLE
3.38 patch to fix broken observability alerting

### ISSUE THREAD

**Issue by michaellzc** [sourcegraph/sourcegraph#33399]
@sourcegraph/release-guild am requesting the following commits be included in a patch release. They are already merged into `main`:

- https://github.com/sourcegraph/sourcegraph/commit/8d884dbf87571629667d799b2d40f2f3ee00dadf

---

The intent of the questions below is to ensure we keep Sourcegraph high quality and [only create patch releases based on a strict criteria.](https://handbook.sourcegraph.com/engineering/releases#patch-releases) If you can answer yes to many or most of these questions, we will be happy to create the patch release.

I have read [when and why we perform patch releases](https://handbook.sourcegraph.com/engineering/releases#patch-releases) and answer the questions as follows:

> Are users/customers actively asking us for these changes and cannot wait until the next full release?

Not yet, but they will. This is a critical bug we have identified and it's affecting all sourcegraph releases since March 14 https://github.com/sourcegraph/sourcegraph/pull/32554

This should be considered as a P1 issue to all our on-prem admins who rely on our altering to maintain sourcegraph deployment
https://sourcegraph.slack.com/archives/C03A27VPQTC/p1649121934551549?thread_ts=1649120874.838499&cid=C03A27VPQTC

Learn more from https://sourcegraph.slack.com/archives/C03A27VPQTC

> Are the changes extremely minimal, well-tested, and low risk such that not testing as we do in a full release is OK?

Yes

> Is there some functionality completely broken that warrants redacting the prior release of Sourcegraph and advising users wait for the patch release?

Yes. On-prem admin is missing out on critical alerts.

> This will interrupt our regular planned work and release cycle, taking one full working day of our time, and will take up all of our site admin's valuable time by asking them to upgrade or producing noise for them if they don't need to upgrade.
>
> Do you believe the changes are important enough to warrant this?

Yes

> Patch releases are a signal we can do something better to improve the quality of Sourcegraph. Have you already scheduled a call (or created a google doc) to perform a [retrospective](https://about.sourcegraph.com/retrospectives) and identify ways we can improve?

We will as part of the postmortem of INC93.

---

**For the [Release Captain]** - after reviewing this request:

- [x] **Comment on this issue** with a decision regarding the request.
- [x] If you are a first-time [Release Captain], please review the high-level overview of the [patch release process].
- [x] If approved, **add it to a patch release**:
  - If there is [already an upcoming patch release](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+), add the listed commits alongside a link to this issue
  - If there is no upcoming patch release, create a new one:
    - [x] Update [`dev/release/release-config.jsonc`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/release/release-config.jsonc) and open a PR to `main` to update it
      - [x] Change `upcomingRelease` to the current patch release
      - [x] Change `previousRelease` to the previous patch release version
      - [x] Change `releaseDate` to the current date (time is optional) along with `oneWorkingDayAfterRelease` and `oneWorkingDayBeforeRelease`
      - [x] Change `captainSlackUsername` and `captainGitHubUsername` accordingly
    - [x] `yarn release tracking:issues` 
    - [x] Add the listed commits alongside a link to this issue to the generated [release tracking issue](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+)
- [x] **Comment and close this issue once the relevant commit(s) have been cherry-picked into the release branch**.

[release captain]: https://handbook.sourcegraph.com/engineering/releases#release-captain
[patch release process]: https://handbook.sourcegraph.com/departments/product-engineering/engineering/process/releases#patch-release-process

**Comment by camdencheek** [comment]
This patch release has been approved, and I plan to start the release this afternoon. I will act as the captain for this patch release.
