### ISSUE TITLE
Code Insights: testing spike

### ISSUE THREAD

**Issue by unclejustin** [sourcegraph/sourcegraph#33392]
This issue is just to catalog what code needs testing, and what type of tests we can best use to cover it. The end result should be a small number of issues for each of the groups of tests identified.

This spike will be time-boxed to no more than 1 day.

Time permitting this will include a small exploration into using [msw](https://mswjs.io/) to mock responses instead of mock-apollo

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by unclejustin** [comment]
This is a duplicate. GH had a special moment while creating and so we have two of them.
