### ISSUE TITLE
helm: readOnlyRootFilesystem breaks Sourcegraph services

### ISSUE THREAD

**Issue by michaellzc** [sourcegraph/sourcegraph#33396]
Go to dogfood and tail prometheus logs

```
level=error ts=2022-04-04T23:07:28.953Z caller=nflog.go:365 component=nflog msg="Running maintenance failed" err="open /alertmanager/nflog.f615c995bca69e7: read-only file system"
level=info ts=2022-04-04T23:07:28.953Z caller=silence.go:389 component=silences msg="Running maintenance failed" err="open /alertmanager/silences.7516f7fffda8ca91: read-only file system"
```

this looks like it's related with enabling read-only root fs

**Comment by michaellzc** [comment]
we caught this while looking into INC93.

I am not 100% this is what's going on. I'll revisit it and share more.

**Comment by michaellzc** [comment]
With helm locally on a kind cluster, I can reproduce

```
k logs -l app=prometheus -f                                                                                                                                                                                                                                                                                                                                  20:31:46
level=info ts=2022-04-05T02:21:07.705Z caller=silence.go:389 component=silences msg="Running maintenance failed" err="open /alertmanager/silences.59722a9a3a1f1580: read-only file system"
level=error ts=2022-04-05T02:21:07.705Z caller=nflog.go:365 component=nflog msg="Running maintenance failed" err="open /alertmanager/nflog.719e632888466e9a: read-only file system"
level=info ts=2022-04-05T02:36:07.726Z caller=silence.go:389 component=silences msg="Running maintenance failed" err="open /alertmanager/silences.2eceb5f14aab81c8: read-only file system"
level=error ts=2022-04-05T02:36:07.726Z caller=nflog.go:365 component=nflog msg="Running maintenance failed" err="open /alertmanager/nflog.455d580249d14b34: read-only file system"
level=info ts=2022-04-05T02:51:07.686Z caller=silence.go:389 component=silences msg="Running maintenance failed" err="open /alertmanager/silences.6000d3f772986292: read-only file system"
level=error ts=2022-04-05T02:51:07.686Z caller=nflog.go:365 component=nflog msg="Running maintenance failed" err="open /alertmanager/nflog.4edbab8632d3958a: read-only file system"
level=info ts=2022-04-05T03:06:07.710Z caller=silence.go:389 component=silences msg="Running maintenance failed" err="open /alertmanager/silences.2312057614eb0257: read-only file system"
level=error ts=2022-04-05T03:06:07.710Z caller=nflog.go:365 component=nflog msg="Running maintenance failed" err="open /alertmanager/nflog.78c6805f582e479: read-only file system"
level=error ts=2022-04-05T03:21:07.716Z caller=nflog.go:365 component=nflog msg="Running maintenance failed" err="open /alertmanager/nflog.654470a07e3dd92: read-only file system"
level=info ts=2022-04-05T03:21:07.716Z caller=silence.go:389 component=silences msg="Running maintenance failed" err="open /alertmanager/silences.7872ad4eaf00d591: read-only file system"
```

**Comment by michaellzc** [comment]
🤔emm

on a live GKE cluster it is fine. Maybe a `kind` limitation with security context?

**Comment by sourcegraph-bot-2** [comment]
Heads up @caugustus-sourcegraph @kevinwojo @michaellzc - the "team/delivery" label was applied to this issue.

**Comment by caugustus-sourcegraph** [comment]
@michaellzc:

https://sourcegraph.com/github.com/sourcegraph/sourcegraph@c931c45bf523334341eb6f44dda41a6f5fb3b78f/-/blob/docker-images/prometheus/cmd/prom-wrapper/main.go?L37 - Our prometheus wrapper modifies files in the `/sg_config_prometheus` directory, which is set to read-only in helm.

I don't see a good way around this - we can't mount a writable volume on top because there are a lot of files in that directory that we need to keep, and we still want the docker image to provide the initial source for all of those. Further, even if we can work around this problem, there may be other issues, like this:
```
level=info ts=2022-04-07T17:38:22.301Z caller=silence.go:389 component=silences msg="Running maintenance failed" err="open /alertmanager/silences.238812dcc79eea00: read-only file system"
```

Feels like the best approach is just to remove the read-only root file system requirement from helm for the Prometheus deployment. So far it seems like that's the only one we have an issue with, but it'd be good to check the dogfood logs and confirm (are they sent to some central log store that we can easily search?).

**Comment by kevinwojo** [comment]
Here is the [GCP Log Explorer Search query](https://console.cloud.google.com/logs/query;query=labels.%22k8s-pod%2Fdeploy%22:%22sourcegraph%22%20AND%20labels.%22k8s-pod%2Fapp%22:%22prometheus%22%20AND%20%22read-only%20file%20system%22%0A;timeRange=P90D;cursorTimestamp=2022-04-12T17:27:48.132646728Z?project=sourcegraph-dogfood)

![Screen Shot 2022-04-12 at 12 36 53 PM](https://user-images.githubusercontent.com/9081680/163021450-8dadc8cd-0cff-43e7-8f95-7d6b1e186bec.png)

**Comment by virginiaulrich** [comment]
This ticket will be for the short-term fix that needs to be complete this week; and https://github.com/sourcegraph/sourcegraph/issues/34012 will be used for a long-term root-cause focus fix at a later date

**Comment by kevinwojo** [comment]
Closed by: https://github.com/sourcegraph/deploy-sourcegraph-helm/pull/108
