### ISSUE TITLE
New reference panel: lists are uncollapsed when clicking on a reference

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#33418]
Steps to reproduce:

1. Open new reference panel
2. Collapse groups of references (say 2 out of 3 files)
3. Click on reference in open group
4. Lists will be uncollapsed

Gif:

![screenshot_2022-04-05_13 52 59](https://user-images.githubusercontent.com/1185253/161748118-bcf01cd6-8970-4591-9fde-2a3f49eea704.gif)

**Comment by sourcegraph-bot-2** [comment]
Heads up @macraig - the "team/code-intelligence" label was applied to this issue.
