### ISSUE TITLE
New reference panel: support filtering of results when using search-based code intel

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#33412]
Currently the reference panel only supports filtering of results when using precise code intel, because we do it in the backend.

When falling back to search-based code intel, the backend doesn't do anything, which means we need to do client-side filtering. Or rewrite the filter pattern into a `file:...`f ilter.

**Comment by sourcegraph-bot-2** [comment]
Heads up @macraig - the "team/code-intelligence" label was applied to this issue.
