### ISSUE TITLE
JetBrains: Decide what/how to do the left side filter

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#33429]

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/growth-and-integrations" label was applied to this issue.

**Comment by vdavid** [comment]
Bottom line: **We won't include this in v1.**

---

Details:

As Sara wrote: "Hey David! Based on my wireframes and the technical guidance I’ve gotten from you and Philipp, I don’t think I’ll be including a filter sidebar component for v1.
I think it could be a post v1 exploration for an [optional feature](https://www.figma.com/file/nmNPZGYCoGIUN0YMylmPTT/JetBrains-plugin-MLP?node-id=1566%3A6477) to open the search results in a filter sidebar, like the one we mentioned in our pairing."

So I'll close this one.
