### ISSUE TITLE
JetBrains: Find out how to add extension settings

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#33425]
Is there a UI for that? Where do we store the settings data?

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/growth-and-integrations" label was applied to this issue.

**Comment by vdavid** [comment]
It's pretty straightforward and written down [here](https://plugins.jetbrains.com/docs/intellij/settings-tutorial.html#the-appsettingsstate-class).
Needs three things:
 - A state object to save. Needs to contain all the structure we need to store the state (in our case, it's probably just a URL)
 - A JPanel that's displayed on the Settings UI
 - An `AppSettingsConfigurable` that holds the whole thing together, and which the `plugin.xml` references.

I didn't create a prototype and it's also not the scope of this issue, so I'll just close it with these notes.
The important thing is that this part seems straightforward; I don't expect any rabbit holes here.
