### ISSUE TITLE
JetBrains: Test in low memory conditions

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#33424]
There are some concerns about increased memory consumption when using JCEF.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/growth-and-integrations" label was applied to this issue.

**Comment by vdavid** [comment]
I've done some tests. Didn't go super great, but the results look good for us.

I used IntelliJ IDEA Community Edition for the testing.
I didn't find a way to see memory use for each individual plugin inside the IDE. (And external to the IDE, one can only see blended data.)

Two sources of data that I used:
1. The IDE shows current memory use at the bottom right corner once you right-click the status bar and check "Memory Indicator".
2. Activity Monitor (`AM`) shows memory use for the process.

These show wildly different numbers:
- The IDE shows 250–450 MB after a clean start.
- `AM` shows ~1.7 GB for a clear start.

In "Help → Change Memory Settings", once can set "Maximum Heap Size" from 4,096MB to anything above 256 MB.

Some numbers for `AM` with different settings:
- With the public version of our plugin installed: 1.69 GB
- With our "web view" branch of the plugin installed, after the web view was loaded: 1.71 GB
- Same, with the max heap limited to 1000MB: 1.70 GB
- Same, limited to 400 MB: 1.35 GB
- Same, limited to 300 MB: 1.35 GB
- Same, limited to 257 MB: 1.35 GB

Once I limited the heap to 257 MB, the IDE started struggling to perform even its vital functions, it started lagging and freezing. But even in this case, the web view loaded up without glitches, pretty slowly but not any worse than the rest of the UI.

So I'd say **we don't need to worry**: the IDE won't kill the web view early in case of low memory.
