### ISSUE TITLE
JetBrains: Focus entering and leaving the web view (with keyboard)

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#33420]
We've heard concerns around focus management when moving from native UI components into the WebView. As part of our JetBrains explorations we should look into that.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/growth-and-integrations" label was applied to this issue.

**Comment by vdavid** [comment]
I agree that we probably won't need it.
Regarding the "Open in Find Window" button:
1. It won't be a part of v1, so this is a question for later.
2. If we wire up the Ctrl+Enter shortcut in the web view with the event that occurs when pressing this button, that's enough to cover 95% of the uses.
3. If we _really_ want to make the tab in - tab out functionality work, we only need to add custom handlers to the elements with the lowest and highest tab index, plus the element preceding and following the web view in the native part. That's four event handlers and a bit of bridging between the JCEF and Swing. I'm confident that I could do it in a few hours.

**Comment by vdavid** [comment]
I think we can close this issue because you've discovered that we won't need this now, and these findings will be enough for a starting point for the future when we'll need the info.

**Comment by philipp-spiess** [comment]
Agreed!
