### ISSUE TITLE
Improve resource usage alerting

### ISSUE THREAD

**Issue by caugustus-sourcegraph** [sourcegraph/sourcegraph#33438]
## Context

As a site admin, I am missing out on important infra-level alerts.

## Deliverable

Review the existing provisioning alerts with an eye towards notifying site admins about underprovisioned setups.

For example:
- [ ] Add critical-level alerts for exceeding provisioning limits
- [ ] Add warnings for long-term downward trends
- [ ] CPU throttling, 
- [ ] OOM @sourcegraph/cloud-devops will implement this
- [ ] container restarts
- [x] max connection errors from the databases @sourcegraph/cloud-devops will implement this
- [ ] Improve instruction how to address memory limit issue https://github.com/sourcegraph/sourcegraph/pull/34808/files#r863734505

Are there any other performance metrics that could be monitored ("golden signals")?

Are there any metrics about site configuration errors?

**Comment by sourcegraph-bot-2** [comment]
Heads up @caugustus-sourcegraph @kevinwojo @michaellzc - the "team/delivery" label was applied to this issue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/cloud-devops - the "team/devops" label was applied to this issue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @RafLeszczynski - the "team/cloud" label was applied to this issue.

**Comment by rafax** [comment]
@michaellzc do you think we should prioritize this, or wait for V2 (and close this ticket)?

**Comment by michaellzc** [comment]
closing

this is better to be done as a proper project "fine-tune cloud resource consumption"
