### ISSUE TITLE
Add resource usage dashboard

### ISSUE THREAD

**Issue by caugustus-sourcegraph** [sourcegraph/sourcegraph#33437]
## Context

As a site admin, I am unable to view provisioning stats across all services.

## Deliverable

Add a new dashboard or extend the built-in Containers dashboard to include an overview of resource usage compared to provisioning limits. This information is currently available on individual service dashboards, but there is no centralized summary.

If possible, include graphs for the following:
- [ ] CPU throttling
- [ ] container restarts @sourcegraph/cloud-devops will implement this
- [ ] OOM errors @sourcegraph/cloud-devops will implement this
- [ ] Comparison of total available resources compared to usage (particularly for docker-compose setups, is the full node being used) @sourcegraph/cloud-devops will implement this

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/cloud-devops - the "team/devops" label was applied to this issue.

**Comment by daxmc99** [comment]
Closely related https://github.com/sourcegraph/sourcegraph/issues/33438

**Comment by michaellzc** [comment]
this is done
