### ISSUE TITLE
Tooltip covered up

### ISSUE THREAD

**Issue by jasongornall** [sourcegraph/sourcegraph#33442]
- **Sourcegraph version:** https://k8s.sgdev.org/ Version: 140546_2022-04-05_cd76bc939633
- **Platform information:** Chrome, MacOs, 100% repro

![image](https://user-images.githubusercontent.com/6912393/161795963-24debb06-b28e-4452-a0c7-6f6dac2b23e1.png)

#### Steps to reproduce:

1. Load https://k8s.sgdev.org/search and click the input field
2. Observe strange tooltip

#### Expected behavior:
Tooltip is clear and easy to read. (potentially increase z-index on that tooltip?)

#### Actual behavior:
Tooltip is hard to read

If would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are not [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by camdencheek** [comment]
Closing since I can no longer reproduce this and the onboarding tour has been removed
