### ISSUE TITLE
gitserver: Empty creatordate leads to bad date format error

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/sourcegraph#33446]
We're seeing an error in prod for torvalds/Linux: ([logs](https://sourcegraph.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-sourcegraph-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bapp%3D%5C%22worker%5C%22,namespace%3D%5C%22prod%5C%22%7D%20%7C%3D%20%5C%22commit%5C%22%22%7D%5D,%22range%22:%7B%22from%22:%22now-5m%22,%22to%22:%22now%22%7D%7D))

```
gitserver.RefDescriptions: unexpected output from git for-each-ref (bad date format) \"c39ae07f393806ccf406ef966e9a15afc43cc36arefs/tags/v2.6.11 \"
```

It seems like the problem is that somehow, one is ending up an empty value for `%(creatordate)`, which the code doesn't handle. It's not super clear when why that is happening here; tags seem to act as roots for git gc, so resetting HEAD, rebasing etc. don't end up affecting the `creatordate`. Maybe there's some other git operation that leaves tags behind pointing to a non-existent commit?

One unusual thing is that `c39ae07f393806ccf406ef966e9a15afc43cc36a` isn't a valid commit hash for torvalds/linux right now. However, the GitHub UI does show `v2.6.11` as a valid tag. However, if you click on that tag, it gives a 404.

![Linux repo showing v2.6.11 tag](https://user-images.githubusercontent.com/93103176/161801435-ee98828a-8220-4fa0-acc9-5c25f7b6ef29.jpeg)
![Linux repo showing 404 on navigating to v2.6.11 tag](https://user-images.githubusercontent.com/93103176/161801441-d9442fad-097d-4d0c-a5fe-108591a285f1.jpeg)

**Comment by Strum355** [comment]
Fun fact about the tag:
```
 git show v2.6.11
tag v2.6.11-tree

This is the 2.6.11 tree object.

NOTE! There's no commit for this, since it happened before I started with git.
Eventually we'll import some sort of history, and that should tie this tree
object up to a real commit. In the meantime, this acts as an anchor point for
doing diffs etc under git.
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.2.4 (GNU/Linux)

iD8DBQBCeV/eF3YsRnbiHLsRAl+SAKCVp8lVXwpUhMEvy8N5jVBd16UCmACeOtP6
KLMHist5yj0sw1E4hDTyQa0=
=/bIK
-----END PGP SIGNATURE-----

tree v2.6.11

COPYING
CREDITS
Documentation/
MAINTAINERS
Makefile
README
REPORTING-BUGS
arch/
crypto/
drivers/
fs/
include/
init/
ipc/
kernel/
lib/
mm/
net/
scripts/
security/
sound/
usr/
```

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.
