### ISSUE TITLE
enqueue-repo-update should use an ID

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#3345]
We do some hard to understand stuff were we pass name around. Trying to untangle this is gonna be tough, so this issue still needs to be fleshed out.

Related https://github.com/sourcegraph/sourcegraph/issues/2609

**Comment by beyang** [comment]
Will it still take a clone URL as an optional argument (required if the caller wants it to succeed if gitserver has never cloned it before)?

**Comment by keegancsmith** [comment]
> Will it still take a clone URL as an optional argument (required if the caller wants it to succeed if gitserver has never cloned it before)?

The ID is the ID in the `repos` table. If we want a repository to be managed by us we require it to be in our repo table. Once there we can let gitserver clone it. So if we have an endpoint calling `enqueue-repo-update` on a repository not in the repo table, then the call should fail.
