### ISSUE TITLE
worker: potentially use AWS's default credential provider instead of static

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#33461]
Use AWS default credential chain provider rather than just the [current static provider](https://github.com/sourcegraph/sourcegraph/blob/ce2005995a8126960451c125605605dd54696f49/enterprise/cmd/worker/internal/executorqueue/aws_reporter.go#L96).

 In https://github.com/sourcegraph/accounts/issues/565 's case, it could eliminate the need to inject AWS keys via env vars.

**Comment by chrispine** [comment]
no objection to backlogging this one
