### ISSUE TITLE
monitoring: track time to first result per sentinel query in Honeycomb

### ISSUE THREAD

**Issue by stefanhengl** [sourcegraph/sourcegraph#33489]
There is a mismatch of how we track sentinel queries an report them in Honeycomb v. Prometheus. For Honeycomb, we don't report "time to first result", which is the most relevant for a user's interactive search experience.

**Comment by sourcegraph-bot-2** [comment]
Heads up @jjeffwarner - the "team/search-core" label was applied to this issue.

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket, please let us know how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
