### ISSUE TITLE
gitserver: add batched getting repos by name functionality to gitserverRepoStore 

### ISSUE THREAD

**Issue by sashaostrikov** [sourcegraph/sourcegraph#33485]
Add a batched version of a `GetByName(ctx context.Context, name api.RepoName) (*types.GitserverRepo, error)` function

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.

**Comment by ryanslade** [comment]
Is this still "in review"?

**Comment by sashaostrikov** [comment]
Closed by https://github.com/sourcegraph/sourcegraph/pull/34047
