### ISSUE TITLE
M.P. onboarding issue 

### ISSUE THREAD

**Issue by stefanhengl** [sourcegraph/sourcegraph#33488]
#### Week 1-2

- [x] Make sure you went through [software engineer onboarding](https://about.sourcegraph.com/handbook/engineering/onboarding/software-engineer-onboarding).
- [x] Set up a backend development intro session with @stefanhengl
- [x] Improve the team's onboarding docs 

#### Week 2-3

Get started with some smaller tasks

- [ ] https://github.com/sourcegraph/zoekt/issues/319
- [ ] https://github.com/sourcegraph/zoekt/issues/320
- [ ] https://github.com/sourcegraph/zoekt/issues/321
- [ ] https://github.com/sourcegraph/sourcegraph/issues/33489

#### Week 3-4
- [ ] https://github.com/sourcegraph/zoekt/issues/322
- [ ] https://github.com/sourcegraph/zoekt/issues/323

**Comment by sourcegraph-bot-2** [comment]
Heads up @jjeffwarner - the "team/search-core" label was applied to this issue.

**Comment by jjeffwarner** [comment]
@stefanhengl Please take a look at these tasks and determine which ones were closed and created a new story with the remaining items that we can pick up once we wrap up the tiger team work. We can close this one after the new one is created.

**Comment by stefanhengl** [comment]
All of these tasks are already tickets. I will close the tickets that are done and the rest can just stay open until we get around fixing them.
