### ISSUE TITLE
Improve on-demand repo syncing in background

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#33496]
When we perform an on-demand sync now, we spawn a goroutine for each incoming
request with a short timeout applied to the context:

https://github.com/sourcegraph/sourcegraph/blob/f44313ce2a0a021316fd8b5aadf7cc6663cffed7/internal/repos/syncer.go#L291-L304

Instead, we should spawn a single background goroutine when the syncer starts and an on demand sync 
simply adds repos to a channel or queue which is processed by the one background routine. We already apply 
our internal rate limiter and the GitHub proxy ensures that only one API request at a time can take place so processing them
one at a time from the queue is fine.

We should not add an item to the queue if it is already in the queue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.
