### ISSUE TITLE
[Accessibility Audit] Insights: Create insight via dashboard page

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#33493]
### Steps to replicate journey

Taken from the [user journey list document](https://docs.google.com/document/d/1m8oYTFgim8epA2IfPFCTN2QFSDxODV5WJNe2JhRdMZA/edit?usp=sharing). Use this for further context.

- Click on the “create insights” button at the dashboard page
- Choose the right type of insight that you want to create
- Fill-in the creation UI form
- Click the submit button and see that you has been redirected to the dashboard page with newly created insight (the dashboard you came from)

### How to audit

Follow the instructions here: [Auditing a user journey](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#auditing-a-user-journey)

**Note:** We are planning on arranging thorough third-party audit in the future, so our focus here is just to find the _majority_ of accessibility issues. Don't worry if you feel you haven't found 100% of potential issues, it is better to focus on the core essentials to complete the journey rather than spending lots of time going through every possible problem.

### How to raise discovered problems

Follow the instructions here: [Raising an accessibility bug](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#raising-a-bug)

### Any other questions?

See the [audit FAQ](https://docs.google.com/document/d/1nCi7TvYRpj9eG0_QtgqK1c4L28EiJKVuxyuvg1lAGgo/edit#) - add your question if it isn't there already!

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by vovakulikov** [comment]
Created a few issues for the dashboard page, all other a11y issues were covered by Justin work around creation/edit UI
