### ISSUE TITLE
[Accessibility Audit] Insights: Create your own private dashboard

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#33497]
### Steps to replicate journey

Taken from the [user journey list document](https://docs.google.com/document/d/1m8oYTFgim8epA2IfPFCTN2QFSDxODV5WJNe2JhRdMZA/edit?usp=sharing). Use this for further context.

- Go to the dashboard page and click create the “create dashboard” button
- Fill-out the dashboard creation form (specify dashboard title field and visibility section, in this use case specify private to create private dashboard)
- Click “Create” button and see that you have been redirected to the newly created dashboard
- You should see the “Add insights” card-like button within the dashboard
- By clicking this button you can add insights to this dashboard via “Add or remove insights” UI view. (see Add insights to the dashboard)

### How to audit

Follow the instructions here: [Auditing a user journey](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#auditing-a-user-journey)

**Note:** We are planning on arranging thorough third-party audit in the future, so our focus here is just to find the _majority_ of accessibility issues. Don't worry if you feel you haven't found 100% of potential issues, it is better to focus on the core essentials to complete the journey rather than spending lots of time going through every possible problem.

### How to raise discovered problems

Follow the instructions here: [Raising an accessibility bug](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#raising-a-bug)

### Any other questions?

See the [audit FAQ](https://docs.google.com/document/d/1nCi7TvYRpj9eG0_QtgqK1c4L28EiJKVuxyuvg1lAGgo/edit#) - add your question if it isn't there already!

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
