### ISSUE TITLE
Add support for Perforce

### ISSUE THREAD

**Issue by KattMingMing** [sourcegraph/sourcegraph#3349]
Customers have been asking for Sourcegraph to support Perforce, not just by using our `git p4` documentation found here: https://docs.sourcegraph.com/admin/repo/perforce

Customers:
https://app.hubspot.com/contacts/2762526/company/990502538
https://app.hubspot.com/contacts/2762526/company/693777200

**Comment by Hokwang** [comment]
I am also waiting this.

**Comment by tsenart** [comment]
cc @keegancsmith

**Comment by keegancsmith** [comment]
@Hokwang we have an experimental tool to help export just the working copy from perforce into Sourcegraph. It does not preserve commit history. Would this suit your use-case?

**Comment by Hokwang** [comment]
@keegancsmith thanks for your comment,
I read your doc and if mean it "git p4", it does not suit, I need more native way.

**Comment by keegancsmith** [comment]
It doesn't use `git p4`. Instead, it "fakes" it by just taking any directory on your machine and creating a git repo of it. So this is a bridge just for the code, not the metadata. With that explanation, does that seem effective?

**Comment by peterguy** [comment]
Sourcegraph has supported configuring and syncing Perforce depots via `git p4` and more recently `p4-fusion` for awhile now (since before my time) and we are now looking into cloning Perforce depots natively.
