### ISSUE TITLE
[Accessibility Audit] Insights: Add insights to the dashboard

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#33495]
### Steps to replicate journey

Taken from the [user journey list document](https://docs.google.com/document/d/1m8oYTFgim8epA2IfPFCTN2QFSDxODV5WJNe2JhRdMZA/edit?usp=sharing). Use this for further context.

- Open the dashboard to which you want to add an insight
- Click the “Add or remove” button
- You should see the modal where you can find the list of all available to you insights
- Check (include) or uncheck (remove) insights checkbox in the list
- Click the “Save” button
- See the newly added insights on the dashboard

### How to audit

Follow the instructions here: [Auditing a user journey](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#auditing-a-user-journey)

**Note:** We are planning on arranging thorough third-party audit in the future, so our focus here is just to find the _majority_ of accessibility issues. Don't worry if you feel you haven't found 100% of potential issues, it is better to focus on the core essentials to complete the journey rather than spending lots of time going through every possible problem.

### How to raise discovered problems

Follow the instructions here: [Raising an accessibility bug](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#raising-a-bug)

### Any other questions?

See the [audit FAQ](https://docs.google.com/document/d/1nCi7TvYRpj9eG0_QtgqK1c4L28EiJKVuxyuvg1lAGgo/edit#) - add your question if it isn't there already!

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
