### ISSUE TITLE
[Accessibility Audit] Insights: Drill down insights (filter the insight result)

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#33499]
### Steps to replicate journey

Taken from the [user journey list document](https://docs.google.com/document/d/1m8oYTFgim8epA2IfPFCTN2QFSDxODV5WJNe2JhRdMZA/edit?usp=sharing). Use this for further context.

- For insights that have been created with “All repositories mode” (see create new insights section) you can specify the sub-set of repositories (repositories regexp) that you want to include/exclude from the chart
- Click on the filter icon button on the insight card
- Fill out include/exclude filter form
- See that chart was reloaded with filtered down data
- Click the “Update default filters” button if you want to save this insight with filter as a default
- Click the “Save as new view” if you don’t want to change the current insight but want to create another one with predefined default filters

### How to audit

Follow the instructions here: [Auditing a user journey](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#auditing-a-user-journey)

**Note:** We are planning on arranging thorough third-party audit in the future, so our focus here is just to find the _majority_ of accessibility issues. Don't worry if you feel you haven't found 100% of potential issues, it is better to focus on the core essentials to complete the journey rather than spending lots of time going through every possible problem.

### How to raise discovered problems

Follow the instructions here: [Raising an accessibility bug](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#raising-a-bug)

### Any other questions?

See the [audit FAQ](https://docs.google.com/document/d/1nCi7TvYRpj9eG0_QtgqK1c4L28EiJKVuxyuvg1lAGgo/edit#) - add your question if it isn't there already!

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
