### ISSUE TITLE
[Accessibility Audit] Insights: Sharing insight with someone else in the account

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#33502]
### Steps to replicate journey

Taken from the [user journey list document](https://docs.google.com/document/d/1m8oYTFgim8epA2IfPFCTN2QFSDxODV5WJNe2JhRdMZA/edit?usp=sharing). Use this for further context.

- Create dashboard with public (org one or global one) visibility value
- Go to the newly created dashboard page (you will be redirected to this automatically after submission the dashboard creation from)
- Click the “Assign or remove insights” button and select any amount insights that you want to include in this public dashboard (by checking them in the “Assign or remove” view list
- Click the “Save” button and see newly added insights on the public dashboard
- Click three dot menu button next to the dashboard select
- Click the copy link button
- Send the link for this dashboard to anyone you want to share this dashboard/insight with.

### How to audit

Follow the instructions here: [Auditing a user journey](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#auditing-a-user-journey)

**Note:** We are planning on arranging thorough third-party audit in the future, so our focus here is just to find the _majority_ of accessibility issues. Don't worry if you feel you haven't found 100% of potential issues, it is better to focus on the core essentials to complete the journey rather than spending lots of time going through every possible problem.

### How to raise discovered problems

Follow the instructions here: [Raising an accessibility bug](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#raising-a-bug)

### Any other questions?

See the [audit FAQ](https://docs.google.com/document/d/1nCi7TvYRpj9eG0_QtgqK1c4L28EiJKVuxyuvg1lAGgo/edit#) - add your question if it isn't there already!

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
