### ISSUE TITLE
[Accessibility Audit] Code Intel: Search symbols for a repository

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#33508]
### Steps to replicate journey

Taken from the [user journey list document](https://docs.google.com/document/d/1kA6aVOAgID_uPm-d6uEC1DG6WHjJ8fPT0UAXQcML_KQ/edit?usp=sharing). Use this for further context.

- Navigate to a repository in Sourcegraph.
- Optional: Show left sidebar if hidden.
- Optional: Select the Symbols tab if the Files tab is active.
- Search for a symbol in the symbols search bar.
- Scroll through results and click on a result.

### How to audit

Follow the instructions here: [Auditing a user journey](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#auditing-a-user-journey)

**Note:** We are planning on arranging thorough third-party audit in the future, so our focus here is just to find the _majority_ of accessibility issues. Don't worry if you feel you haven't found 100% of potential issues, it is better to focus on the core essentials to complete the journey rather than spending lots of time going through every possible problem.

### How to raise discovered problems

Follow the instructions here: [Raising an accessibility bug](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#raising-a-bug)

### Any other questions?

See the [audit FAQ](https://docs.google.com/document/d/1nCi7TvYRpj9eG0_QtgqK1c4L28EiJKVuxyuvg1lAGgo/edit#) - add your question if it isn't there already!

**Comment by sourcegraph-bot-2** [comment]
Heads up @macraig - the "team/code-intelligence" label was applied to this issue.

**Comment by varungandhi-src** [comment]
Just noticed a usability issue on mobile. Clicking on a symbol in the symbols sidebar doesn't seem to do anything. You need to close the sidebar explicitly to see the file.

https://user-images.githubusercontent.com/93103176/167510648-5f1b12ea-31ef-43c5-b2bd-c7952b753d55.mov

.

**Comment by Numbers88s** [comment]
Yeah, I guess I thought that was a UX problem, instead of an accessibility issue per the requirements above. Happy to record that as an issue tho 👍

**Comment by varungandhi-src** [comment]
You're right, I wasn't thinking about that distinction, but it makes sense. 👍
