### ISSUE TITLE
[Accessibility Audit] Insights: Delete dashboard

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#33504]
### Steps to replicate journey

Taken from the [user journey list document](https://docs.google.com/document/d/1m8oYTFgim8epA2IfPFCTN2QFSDxODV5WJNe2JhRdMZA/edit?usp=sharing). Use this for further context.

- Open the dashboard page and select the dashboard you want to delete
- Click three dot menu next to the dashboard select
- Click the “delete” context item
- Note: that all insights on this removed dashboard won’t be removed, You still have access to them through the “All insights” dashboard and you can add them to other dashboards later

### How to audit

Follow the instructions here: [Auditing a user journey](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#auditing-a-user-journey)

**Note:** We are planning on arranging thorough third-party audit in the future, so our focus here is just to find the _majority_ of accessibility issues. Don't worry if you feel you haven't found 100% of potential issues, it is better to focus on the core essentials to complete the journey rather than spending lots of time going through every possible problem.

### How to raise discovered problems

Follow the instructions here: [Raising an accessibility bug](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#raising-a-bug)

### Any other questions?

See the [audit FAQ](https://docs.google.com/document/d/1nCi7TvYRpj9eG0_QtgqK1c4L28EiJKVuxyuvg1lAGgo/edit#) - add your question if it isn't there already!

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by vovakulikov** [comment]
**Audit result**
- Navigate through the journey using only the keyboard. - I didn't notice any problems with keyboard navigation that would block me from deleting the dashboard 🍏 
- Enable a screen reader. - All elements were announced properly (within delete dashboard flow)
- Navigate through the user journey using a viewport that has a width of 320px
    - It isn't directly related to a11y audit but I found 1 visual bug with the dashboard header component on mobile. https://github.com/sourcegraph/sourcegraph/issues/37881
