### ISSUE TITLE
feature request: Get information about the imported dependency

### ISSUE THREAD

**Issue by niinpatel** [sourcegraph/sourcegraph#3350]
When working on a codebase, we often come across imported dependencies which about which we don't know much about. 

So here's the idea: On clicking/hovering on an imported dependency, pull its short description from the [npm website](https://www.npmjs.com) or [PyPI](https://pypi.org/) or whichever website it happens to be on and show it to the user. 

We can have an option to know more about the dependency, in which you can either fetch the whole description of the module or redirect the user to the website. 

Something like this maybe: 
![dependency_import](https://user-images.githubusercontent.com/31539366/55912581-9faa3c00-5c00-11e9-818e-5ad5f2c2e5a4.PNG)

**Comment by sqs** [comment]
Excellent idea! Would you or anyone else want to write this? You can make a Sourcegraph extension https://docs.sourcegraph.com/extensions.

**Comment by chrismwendt** [comment]
Check out https://sourcegraph.com/extensions/chris/sourcegraph-npm-import-stats, which is similar:

![](https://user-images.githubusercontent.com/1387653/46236952-54040500-c336-11e8-885a-a68c3fff4ba4.gif)

**Comment by scalabilitysolved** [comment]
Likely something we'll tackle as we start on dependency navigation, should this be rolled into a higher level issue @macraig ?

**Comment by macraig** [comment]
Dependency navigation efforts are now tracked in [#20832](https://github.com/sourcegraph/sourcegraph/issues/20832)
