### ISSUE TITLE
Datadog use cases in Handbook

### ISSUE THREAD

**Issue by filiphaftek** [sourcegraph/sourcegraph#33500]
#### Describe the issue
Requirements of having handbook documentation how to use Datadog.

Part of [issue](https://github.com/sourcegraph/sourcegraph/issues/29651)

#### Suggested resolution
Documentation in CloudDevops section.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/cloud-devops - the "team/devops" label was applied to this issue.

**Comment by filiphaftek** [comment]
@daxmc99 can we close it with the state we have now by merging [PR](https://github.com/sourcegraph/handbook/pull/2983)? If we need to add more use cases, I think we can just add separate issue not to keep this too long.

**Comment by daxmc99** [comment]
Yup, I'll close this by merging that PR
