### ISSUE TITLE
[Accessibility Audit] Code Intel: Inspecting LSIF uploads for a repository

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#33512]
### Steps to replicate journey

Taken from the [user journey list document](https://docs.google.com/document/d/1kA6aVOAgID_uPm-d6uEC1DG6WHjJ8fPT0UAXQcML_KQ/edit?usp=sharing). Use this for further context.

- Navigate to a repository in Sourcegraph.
- Click on the 🧠 Code Intelligence button.
- Scroll through the list of uploads.
- Optional: Adjust Upload State filter.
- Optional: Search uploads for specific uploads.
- Click on > next to an upload to inspect it.
- Potential options:
  - Click the 🗑 Delete upload button.
  - Expand Dependencies section
    - Optional: Show dependents.
    - Optional: Search dependencies.
    - Click on > next to an upload to inspect it.
  - Expand Retention overview section.
    - Optional: Click Show matching only.
    - Optional: Type filter in “Search Matches…”
    - Click on a retention policy.

### How to audit

Follow the instructions here: [Auditing a user journey](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#auditing-a-user-journey)

**Note:** We are planning on arranging thorough third-party audit in the future, so our focus here is just to find the _majority_ of accessibility issues. Don't worry if you feel you haven't found 100% of potential issues, it is better to focus on the core essentials to complete the journey rather than spending lots of time going through every possible problem.

### How to raise discovered problems

Follow the instructions here: [Raising an accessibility bug](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#raising-a-bug)

### Any other questions?

See the [audit FAQ](https://docs.google.com/document/d/1nCi7TvYRpj9eG0_QtgqK1c4L28EiJKVuxyuvg1lAGgo/edit#) - add your question if it isn't there already!

**Comment by sourcegraph-bot-2** [comment]
Heads up @macraig - the "team/code-intelligence" label was applied to this issue.

**Comment by varungandhi-src** [comment]
Closing as all relevant issues have been filed, or the problems have already been fixed.

**Comment by varungandhi-src** [comment]
Noticed one more issue:
- [ ] https://github.com/sourcegraph/sourcegraph/issues/44553
