### ISSUE TITLE
[Accessibility Audit] Code Intel: Editing auto-indexing policies for an instance (site-admin)

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#33518]
### Steps to replicate journey

Taken from the [user journey list document](https://docs.google.com/document/d/1kA6aVOAgID_uPm-d6uEC1DG6WHjJ8fPT0UAXQcML_KQ/edit?usp=sharing). Use this for further context.

- Navigate to site admin settings in Sourcegraph.
- Click on Configuration in the 🧠 Code Intelligence section in the sidebar.
- Rest of the steps are the same as for [Editing auto-indexing policies for a repository.](https://docs.google.com/document/d/1kA6aVOAgID_uPm-d6uEC1DG6WHjJ8fPT0UAXQcML_KQ/edit#heading=h.f4aysc1m2vd0)

### How to audit

Follow the instructions here: [Auditing a user journey](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#auditing-a-user-journey)

**Note:** We are planning on arranging thorough third-party audit in the future, so our focus here is just to find the _majority_ of accessibility issues. Don't worry if you feel you haven't found 100% of potential issues, it is better to focus on the core essentials to complete the journey rather than spending lots of time going through every possible problem.

### How to raise discovered problems

Follow the instructions here: [Raising an accessibility bug](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#raising-a-bug)

### Any other questions?

See the [audit FAQ](https://docs.google.com/document/d/1nCi7TvYRpj9eG0_QtgqK1c4L28EiJKVuxyuvg1lAGgo/edit#) - add your question if it isn't there already!

**Comment by sourcegraph-bot-2** [comment]
Heads up @macraig - the "team/code-intelligence" label was applied to this issue.

**Comment by efritz** [comment]
Noting differences from https://github.com/sourcegraph/sourcegraph/issues/33516:

- [ ] Impossible to navigate to create repository filters
  - https://github.com/sourcegraph/sourcegraph/issues/35187
  - [ ] Testing blocked on additional forms for now
