### ISSUE TITLE
Bitbucket Cloud Permissions Syncing

### ISSUE THREAD

**Issue by dan-mckean** [sourcegraph/sourcegraph#33529]
## Problem to solve
Bitbucket Cloud is one of two options for customer migration from the end-of-life BB Server.

We've already validated support for support for BB Datacenter ([Validate BB Datacenter support](https://github.com/sourcegraph/sourcegraph/issues/30175)) but the alternative is BB Cloud. 

For Cloud we currently support repo syncing, but not permissions, and the APIs for that are different from those used for Server and Datacenter.

With BB Server going end of life, a lack of support may put existing customers at risk, and prevent us signing new prospects.

## Measure of success
We will have full support for BB Cloud.

## Solution summary

Artifacts:
- TO DO

## What specific customers are we iterating on the problem and solution with?

- https://github.com/sourcegraph/accounts/issues/8016
- https://github.com/sourcegraph/accounts/issues/250

## Impact on use cases

Indirectly enables use case value by enabling use of Sourcegraph.

## Delivery plan

- [ ] TO DO

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.

**Comment by mrnugget** [comment]
@pjlast we do have this now, right?

**Comment by pjlast** [comment]
@mrnugget yes we do!
