### ISSUE TITLE
GitHub Apps (rather than OAuth) for repository access and permissions syncing (self-hosted & MIs)

### ISSUE THREAD

**Issue by dan-mckean** [sourcegraph/sourcegraph#33528]
## Problem to solve
We currently lack any support for GHApps authentication and scope management for connections to GH, for self-hosted and managed instances. 

As a result, we require more permissions than we actually need, due to low scope granularity, and we often get access to user's non-company repos when their personal tokens are utilized.

## Measure of success
- Fully functional support for GH Apps code host connectivity for both github.com and GH Enterprise, including:
- Authentication
- Repository syncing
- Permissions syncing
- Guidance &/or a mechanism for migration from token-based auth to a GH App

## Solution summary
Cloud SaaS are adding fully functional support for GH Apps but only in Cloud - [RFC 549 APPROVED: GitHub Apps integration for Cloud SaaS](https://docs.google.com/document/d/180iMviFZ4xGeHQGCO7LMqfl5luFIM9RA7FCWW0NNVAI/edit).

The aim is to replicate / port that support, to self-hosted and managed instances.

Artifacts:
- TO DO

## What specific customers are we iterating on the problem and solution with?

- https://github.com/sourcegraph/accounts/issues/1572
- https://github.com/sourcegraph/accounts/issues/1503
- https://github.com/sourcegraph/accounts/issues/8285
- https://github.com/sourcegraph/accounts/issues/7107
- https://github.com/sourcegraph/accounts/issues/8288
- https://github.com/sourcegraph/accounts/issues/6859
- https://github.com/sourcegraph/accounts/issues/8262
- https://github.com/sourcegraph/accounts/issues/558
- https://github.com/sourcegraph/accounts/issues/3564

## Impact on use cases

Underpinning functionality that simplifies or unlocks customers use of our product - enabling other use cases.

## Delivery plan

- [ ] TO DO

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.

**Comment by eseliger** [comment]
@pjlast is this ok to close? does our app implementation cover this?
