### ISSUE TITLE
Code storage and permissions rearchitecture

### ISSUE THREAD

**Issue by dan-mckean** [sourcegraph/sourcegraph#33531]
## Problem to solve
Alongside work to introduce a high quality of HA to our services, there are a number of potential architecture changes that would enable our own new engineers to onboard more rapidly, and enable other teams within Sourcegraph to more easily read and contribute to our part of the codebase.

## Measure of success

TODO

## Solution summary

Artifacts:
- TO DO

## What specific customers are we iterating on the problem and solution with?

NA

## Impact on use cases

Enables us to better iterate on our code base, enabling faster development of our product.

## Delivery plan

- [ ] TO DO

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.

**Comment by eseliger** [comment]
no actionable items in here.
