### ISSUE TITLE
dogfood: search returns no results if gigarepo is not indexed

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#33538]
Edit: this issue was first just about structural search, but it is any search. I know we used to support this use case, and there was some chat about it in recent PRs by @rvantonder around this (I think?). But the regression may be older than that and related to work around not calling repo.List done by @tsenart? Assigning to search product at first since my gut tells me it is somehow related to that work.

Right now gigarepo is failing to index on dogfood. When doing a structural search against it we just get back that no results are found, rather than an error / etc. I am not sure if this is intentional or a regression.

[`repo:^gigarepo$ strings.ToUpper(...)`](https://k8s.sgdev.org/search?q=context:global+repo:%5Egigarepo%24+strings.ToUpper%28...%29&patternType=structural)

> No results matched your query

[Trace](https://sourcegraph.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-sourcegraph-traces%22,%22queries%22:%5B%7B%22query%22:%226ba77d36dba3167c%22,%22queryType%22:%22traceId%22,%22refId%22:%22A%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D)

![image](https://user-images.githubusercontent.com/187831/161987955-4f4ed33d-3e06-441c-bfd5-0d14f48242d4.png)

An example of forcing the non-index path being taken returning results:

![image](https://user-images.githubusercontent.com/187831/161988968-1a897742-c353-40b2-b382-ade670379d2d.png)

cc @rvantonder

**Comment by keegancsmith** [comment]
@stefanhengl while @tsenart is out, do you think this might be related to the older work we did around repo.List being called less / repo pagination stuff?

**Comment by camdencheek** [comment]
Looking at the [trace](https://sourcegraph.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-sourcegraph-traces%22,%22queries%22:%5B%7B%22query%22:%22309befeb9f8d1236%22,%22queryType%22:%22traceId%22,%22refId%22:%22A%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D) for a search like `repo:^gigarepo$ test`, it appears that `zoektStreamer.List` is listing the gigarepo as indexed, but then also returning no results for that repo.

I would expect that, if indexing is failing on zoekt, it would not list the gigarepo with `zoektStreamer.List` and we would fall back to unindexed search.

**Comment by keegancsmith** [comment]
> Looking at the [trace](https://sourcegraph.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-sourcegraph-traces%22,%22queries%22:%5B%7B%22query%22:%22309befeb9f8d1236%22,%22queryType%22:%22traceId%22,%22refId%22:%22A%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D) for a search like `repo:^gigarepo$ test`, it appears that `zoektStreamer.List` is listing the gigarepo as indexed, but then zoekt is returning no results for that repo.

Nice find! I have no idea how this can happen lol. Thank you so much, I will dive into this today.

**Comment by keegancsmith** [comment]
I am closing this issue out since I can't reproduce locally or on dogfood anymore. If this happens again it will be easy to reproduce since gigarepo is still not indexing. My best guess as to why this happened is emergent behaviour from when I manually was messing around with gigarepo a while ago trying to get it to index. Maybe my manual invocations didn't set ID but name?

Notes:

<span class="timestamp-wrapper"><span class="timestamp">[2022-04-07 Thu 09:43] </span></span> Looking at the settings page, it reports still indexing. This directly calls zoekt.List with the specific repo. Here is the [trace](https://sourcegraph.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-sourcegraph-traces%22,%22queries%22:%5B%7B%22query%22:%2221c9780ccfc649b3%22,%22queryType%22:%22traceId%22,%22refId%22:%22A%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D) which shows the empty response.

![img](https://user-images.githubusercontent.com/187831/162147540-d5a071f8-a260-4fbf-bcc3-0fec6e920020.png)

<span class="timestamp-wrapper"><span class="timestamp">[2022-04-07 Thu 10:21] </span></span> Need to read code now to see how things fit together now. Reading the code, I can only assume that somehow zoekt is returning this is indexed when asked for all items, but not when asking for the gigarepo specifically. The code caching code, the splitting code, etc all look legit.

I tried reproducing locally by making zoekt-git-index blow up after writing out the first shard (but not renaming into place yet):

    ❯ git diff
    diff --git a/build/builder.go b/build/builder.go
    index 7a8e3c3..35936e2 100644
    --- a/build/builder.go
    +++ b/build/builder.go
    @@ -759,6 +759,13 @@ func (b *Builder) flush() error {
                    return b.buildError
            }
    
    +       if strings.Contains(b.opts.RepositoryDescription.Name, "sqlf") {
    +               defer func() {
    +                       log.Println("boom")
    +                       os.Exit(1)
    +               }()
    +       }
    +
            hasShard := b.nextShardNum > 0
            if len(todo) == 0 && hasShard {
                    return nil
    
    zoekt on  k/disable-lazy [$!] ❄️ shell
    ❯ go build -o ../../sourcegraph/sourcegraph/.bin/zoekt-git-index ./cmd/zoekt-git-index/
    
    zoekt on  k/disable-lazy [$!] ❄️ shell
    ❯ pkill -SIGUSR1 zoekt-sourcegra

My hope this would simulate something that is happening on dogfood (ooms). This didn't work. I then tried to reproduce on dogfood and couldn't!

**Comment by keegancsmith** [comment]
Re-opening since I can reproduce again on dogfood. I think this is specific to gigarepo which is failing to index. Will try catch what is happening. But from what I can tell, this is a problem in zoekt not frontend.

**Comment by keegancsmith** [comment]
Tried grepping zoekt-webserver logs to see it loading gigarepo or the ID it is associated with, got nothing. Went onto the zoekt and found an empty index! I realised how this likely happened:

-   I enabled gigarepo in our external services.
-   gitserver clones the repo
-   I then noticed gigarepo source was empty, quickly undid adding it.
-   gitserver still has the old clone, since it implements a soft delete/gc pattern. This clone is empty.
-   I fix gigarepo source so it isn't empty
-   I re-add gigarepo to the external service
-   gitserver uses the empty clone at first, but runs git fetch in the background. This is intentional behaviour and not a bug.
-   zoekt indexes the empty clone. (or it did it earlier and restored from trash)
-   gitserver finishes fetching the large version
-   zoekt starts failing to index it, never getting to the point where it can delete the empty index.

Phew. So you could call this emergent behaviour from us hacking away :)

**Comment by camdencheek** [comment]
Nice, good find!
