### ISSUE TITLE
Feedback: Repository home page should link to the code host under title

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#3354]
On the repository homepage, it would be nice if somewhere near the large title `sourcegraph/sourcegraph` there was a link to jump to the repository on the code host. It is easy to miss in the upper right hand corner on this page.

![image](https://user-images.githubusercontent.com/3173176/55920995-bd9b8080-5baf-11e9-9f8b-50bbdc7db3f6.png)

Customers:

- Someone from https://app.hubspot.com/contacts/2762526/company/407948923 said the icon to jump to the repo was not discoverable enough and specifically suggested this

**Comment by slimsag** [comment]
@sqs @francisschmaltz thoughts on this? I am wondering if just #3355 is enough or if you think we should do this.

**Comment by jasongornall** [comment]
I'm not inclined to lean into pushing people away from our product offering. I feel like as long as it is there we don't need to make it too loud. Feel free to reopen if you disagree
