### ISSUE TITLE
Configurable default rate limiter

### ISSUE THREAD

**Issue by mollylogue** [sourcegraph/sourcegraph#33551]
Current behavior: The default rate limiter has an infinite rate limit. This rate limiter is returned from the rate limiter registry if the key used to look up the rate limiter is of an unknown type.

Proposed behavior: A config variable to set a default rate limit, so the default rate limiter returned by the registry would have this configured limit. If no config variable is specified we fallback to the current behavior of the infinite rate limiter.

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.

**Comment by mollylogue** [comment]
https://github.com/sourcegraph/sourcegraph/pull/33575
