### ISSUE TITLE
Popover double renders

### ISSUE THREAD

**Issue by macraig** [sourcegraph/sourcegraph#33557]
The code intel popover has some weird double-renders at times (I suspect that this stray `?References` GraphQL query has something to do with it):

https://user-images.githubusercontent.com/1185253/157445115-c638b89f-ec5b-4afe-bf2a-861bf6d78282.mp4

**Comment by sourcegraph-bot-2** [comment]
Heads up @macraig - the "team/code-intelligence" label was applied to this issue.

**Comment by chrismwendt** [comment]
@mrnugget Are you still able to repro? I tried it and I'm not seeing the double render problem (Chrome and Firefox):

https://user-images.githubusercontent.com/1387653/162317872-83e1837e-6b89-4fd1-b8d9-a734d344b4f7.mp4

**Comment by mrnugget** [comment]
I could never reliably reproduce it and now I can't reproduce it on that example :(

But while trying to reproduce just now I recorded this video and ran into this behaviour while hovering over `results` (at 11s in the video):

https://user-images.githubusercontent.com/1185253/163336846-afa040fa-9208-495e-be10-f4c8b214b397.mp4

If we look at what happens frame-by-frame we can see that when the tooltip first renders it shows up here:

<img width="593" alt="screenshot_2022-04-14_09 37 05@2x" src="https://user-images.githubusercontent.com/1185253/163337125-a44d3dc9-69f3-4b8f-a544-f873613c8558.png">

And then it's moved up to here:

<img width="638" alt="screenshot_2022-04-14_09 37 31@2x" src="https://user-images.githubusercontent.com/1185253/163337167-503f6c32-d641-44ee-8a4b-6acd611ff6a2.png">

Definitely feels glitchy and I'd consider that a bug. Question is: is it a separate one? Or is this a hint for what we're looking at here? Are double-renders the same as reposition-and-rerender? Or red herring?

**Comment by chrismwendt** [comment]
Ah, I'm also able to repro now by alternating hovering over multiple different tokens.

I think there's 2 separate bugs, so I filed:

- https://github.com/sourcegraph/sourcegraph/issues/33985
- https://github.com/sourcegraph/sourcegraph/issues/33987

**Comment by chrismwendt** [comment]
Reopened https://github.com/sourcegraph/sourcegraph/issues/33987

**Comment by chrismwendt** [comment]
Re-fixed https://github.com/sourcegraph/sourcegraph/issues/33987
