### ISSUE TITLE
Dropdown for control of case sensitive and regex search options

### ISSUE THREAD

**Issue by francisschmaltz** [sourcegraph/sourcegraph#3356]
Sourcegraph 3.1.0 changed case-sensitive search to be the default without much fanfare. This causes confusion from a few people internally and maybe externally. 

We should have a UI to quickly (and globally) enable/disable case-sensitive and regex searches.

Continuation of conversation here: https://sourcegraph.slack.com/archives/C0C324C91/p1554939528108000

**Comment by francisschmaltz** [comment]
I'll create mocks of what this control might look like and add it here.

**Comment by felixfbecker** [comment]
I think a dropdown wouldn't solve this, as a dropdown wouldn't communicate the state without opening it (if it only shows a caret)
