### ISSUE TITLE
Use different Browser Extension icons for development version

### ISSUE THREAD

**Issue by erzhtor** [sourcegraph/sourcegraph#33587]
It would be nice to use different Browser Extension icons for the development version, similar to the web.

https://github.com/sourcegraph/sourcegraph/blob/1ff729a32e87d802756931b0a8cbfaf3f3eba133/client/browser/src/browser-extension/browser-action-icon.ts

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/growth-and-integrations" label was applied to this issue.
