### ISSUE TITLE
Match highlights in GraphQL API are returned in inconsistent ways

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#336]
Line matches are returned with this type in GraphQL:
```graphql
# A line match.
type LineMatch {
    # The preview.
    preview: String!
    # The line number.
    lineNumber: Int!
    # Tuples of [offset, length] measured in characters (not bytes).
    offsetAndLengths: [[Int!]!]!
    # Whether or not the limit was hit.
    limitHit: Boolean!
}
```
But commit and diff search return matches with this type:
```graphql
# A string that has highlights (e.g, query matches).
type HighlightedString {
    # The full contents of the string.
    value: String!
    # Highlighted matches of the query in the preview string.
    highlights: [Highlight!]!
}

# A highlighted region in a string (e.g., matched by a query).
type Highlight {
    # The 1-indexed line number.
    line: Int!
    # The 1-indexed character on the line.
    character: Int!
    # The length of the highlight, in characters (on the same line).
    length: Int!
}
```

The different types make it difficult to implement match highlighting for all result types as one needs to write completely different implementations for text and commit search. Note how line matches use _offsets_, while diff and commit search use line+character. Both should use the same types.

@slimsag assigning you to triage since I think you worked on diff search and the API overhaul a couple months ago

**Comment by slimsag** [comment]
I noticed the same issue while implementing highlighting of search results in `src search`: https://github.com/sourcegraph/src-cli/blob/master/cmd/src/search.go#L302-L306

But I don't have any special context here, so I am un-assigning myself so anyone can work on this and tagging as debt.

**Comment by felixfbecker** [comment]
This debt still exist and should continue to be tracked.

**Comment by poojaj-tech** [comment]
@felixfbecker the inconsistency in the GraphQL API feels more like a bug - is that correct in your opinion? If yes, I'd like to add a bug label for the search backlog.

**Comment by felixfbecker** [comment]
Yeah

**Comment by stefanhengl** [comment]
@camdencheek Doing triage. Please reopen if this is still relevant. Tagging you because it touches commit/diff search types.

**Comment by camdencheek** [comment]
I think it's fair to close this, but it's still a problem. However, it's captured by [other issues](https://github.com/sourcegraph/sourcegraph/issues/31028) that will be addressed this quarter.
