### ISSUE TITLE
Fix multiple command palettes issue on GitHub

### ISSUE THREAD

**Issue by taras-yemets** [sourcegraph/sourcegraph#33607]
Multiple command palette buttons are rendered when not logged in user navigates repository folders on GitHub.

![image](https://user-images.githubusercontent.com/25318659/162222675-83334801-fcaa-4acd-bd19-8e96437a0530.png)

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/growth-and-integrations" label was applied to this issue.
