### ISSUE TITLE
Regression (not yet published) in browser extension

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#3361]
@felixfbecker I think your change at https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/88537f3ebe77b32fb132bdd84a2ec5384efea207#diff-e436809213b3fca50e3bfcde92ac2fe0 broke the browser extension (not yet published though). Now `requestGraphQL`'s emission is `{result: {data, errors}}` not just `{data, errors}`, which causes all `requestGraphQL` calls to fail (because they usually pipe to a `map(({data, errors}) => ...)`.

cc @lguychard

**Comment by lguychard** [comment]
I'm fixing this atm
