### ISSUE TITLE
Background goroutine recover logic is not robust

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#33622]
This logic merely prints the error and continues:

https://github.com/sourcegraph/sourcegraph/blob/0454acb6db7baf2ed88b131ff2b55c683a8c77be/internal/goroutine/goroutine.go#L17-L22

This is not always desirable behavior. What should it be?

**Comment by camdencheek** [comment]
Maybe log a sentry error instead?

**Comment by malomarrec** [comment]
Hey @chrismwendt, this issue didn't have a team label. Given you created it, I assigned you and added your team label. Feel free to unassign yourself. If this is not the right label, can you make sure to add the right one?

**Comment by macraig** [comment]
@chrismwendt is this for the platform and nav team to own?

**Comment by chrismwendt** [comment]
Closing until we have a use case for changing the behavior (I don't think I had one to begin with).
