### ISSUE TITLE
Update Notepad icons 

### ISSUE THREAD

**Issue by marisak** [sourcegraph/sourcegraph#33629]
A few suggestions for updating the icons used in notepad: 
- The standard "delete" icon that we use is just called [delete](https://materialdesignicons.com/icon/delete); it looks like `trash-can` is being used currently 
- I've noticed some buttons with two icons, usually both the plus icon and an icon for the type of item being added. This isn't a pattern that we have, so one or both of the icons should be removed. 
- The "x" icon in the notepad header is misleading because it actually collapses the notepad instead of closing it. I suggest either a minimize icon like [minus](https://materialdesignicons.com/icon/minus) or [chevron-up](https://materialdesignicons.com/icon/chevron-up) and [chevron-down](https://materialdesignicons.com/icon/chevron-down) depending on state.

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by fkling** [comment]
This was done in https://github.com/sourcegraph/sourcegraph/pull/33814
