### ISSUE TITLE
Can't scroll on compare pages

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#33635]
- Visit https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/compare/4e8c6403e79f38580776733f9c282a20063aa10b...bcb2f0d3f1699e93b72e128999bbb7f5a9e9a13b?utm_source=chrome-extension&visible=1#diff-4af58b135a04a0994c8abef8653995b5
- Notice you can't scroll

**Comment by varungandhi-src** [comment]
Same as https://github.com/sourcegraph/sourcegraph/issues/33573?

**Comment by varungandhi-src** [comment]
Closing as duplicate. #stackoverflow 😅
