### ISSUE TITLE
VSCE Bug: Code Monitor toggle button open web link instead of modal

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#33631]
- **Sourcegraph version:** v3.38.0
- **Platform information:**  VSCE v2.2.0
#### Steps to reproduce:

1. Make a search in VS Code Sourcegraph extension without logging in
2. Click on the `Monitor` button above the search results

#### Expected behavior:
A modal would pop up to ask users to sign up:
![image](https://user-images.githubusercontent.com/68532117/162331361-76dff164-c144-4df9-88f6-4f0582221926.png)

#### Actual behavior:
1. The modal would pop up along with the browser
2. Wrong button color within the modal - should be using the primary button
![image](https://user-images.githubusercontent.com/68532117/162331541-f1d241fe-c868-4710-8979-af70d300053e.png)
![image](https://user-images.githubusercontent.com/68532117/162331737-cbdedf4a-4ecc-4df4-92c8-db49a4d5d15a.png)

If would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are not [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/growth-and-integrations" label was applied to this issue.
