### ISSUE TITLE
debug unreliable gigarepo zoekt indexing

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#33657]
It managed to index, but we need to work out how to make it more reliable. This is low priority since the delta shard work (https://github.com/sourcegraph/sourcegraph/issues/29731) will improve reliability.

**Comment by sourcegraph-bot-2** [comment]
Heads up @jjeffwarner - the "team/search-core" label was applied to this issue.

**Comment by keegancsmith** [comment]
cc @ggilmore you expressed some interest in doing atleast some next steps on this. IE I believe you said you could try running the build without symbols enabled, since we have a suspicion ctags is the root cause of the problems here.

I've added this to the "Next" column to represent that.

**Comment by jjeffwarner** [comment]
@ggilmore I think we can close this after your latest changes on the giga repo?

**Comment by ggilmore** [comment]
Yes. ctags indexing is still disabled on the gigarepo - but it is indexing reliably.
