### ISSUE TITLE
hybrid zoekt + searcher prototype

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#33656]
This issue is for tracking our work on a prototype to do hybrid unindexed and indexed searches. The idea is when searching a commit, you can ask searcher to only search the files that have changed since the indexed commit which should be a small set. Then you can ask zoekt to search everything else.

The hope is not only do we avoid the slow cache fill path, but for truly large repos (many gb) we have comparable perf to indexed search.

The scope of the prototype is to only work on text search. This prototype will hopefully then be able to be quickly improved to ship to customers.

**Comment by sourcegraph-bot-2** [comment]
Heads up @jjeffwarner - the "team/search-core" label was applied to this issue.

**Comment by keegancsmith** [comment]
This was our original planned approach https://github.com/sourcegraph/sourcegraph/issues/28612 This has some of the same ideas, but hopefully will be much more powerful and simple to implement.
