### ISSUE TITLE
Programming languages don't show under "All" category in extension registry

### ISSUE THREAD

**Issue by ryankscott** [sourcegraph/sourcegraph#33660]
If you click on the "All" category in our extension registry, any of the items under "Programming languages" don't show up. 

I'm not sure if this is by design or a bug, so it'd be good to understand if that's intentional behaviour and if so, why. 

See Slack message for context: https://sourcegraph.slack.com/archives/C022SPMNR0W/p1649231997108089?thread_ts=1649222932.508749&cid=C022SPMNR0W

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/growth-and-integrations" label was applied to this issue.
