### ISSUE TITLE
Determine GA destination for helm charts

### ISSUE THREAD

**Issue by caugustus-sourcegraph** [sourcegraph/sourcegraph#33679]
https://docs.google.com/document/d/19yNi5Tc6D8Mwxwa6Muw8TB60ssJPi3OxBaHAwq12198/edit?disco=AAAAX5xayPE

Right now we use Github Pages to host the helm chart artifacts and the chart-publisher github action. We're also using the default hostname (https://sourcegraph.github.io).

Decisions:
* Is GCS a better option?
* What hostname should we actually use?

[Setup documentation](https://docs.sourcegraph.com/admin/install/kubernetes/helm) will need to be updated to reflect any change to the hostname. We should leave the old host up for a certain time so that we don't break any existing usage.

**Comment by sourcegraph-bot-2** [comment]
Heads up @caugustus-sourcegraph @kevinwojo @michaellzc - the "team/delivery" label was applied to this issue.

**Comment by caugustus-sourcegraph** [comment]
Using a custom domain with Github Pages will break the existing url, so it may be better to make the swap to another host pre-GA.
