### ISSUE TITLE
Easy way to collect config from customers

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#3367]
When a customer files an issue, we often ask for config information in order to reproduce the issue. There are several pieces of relevant config:
* critical site config
* site config
* global settings
* user settings
* which extension are enabled
* external services config (for each service)

It is onerous to collect all these pieces of info, because they live in different parts of the app. Should make it possible to collect all pieces of config at once. This button should ideally be easily accessible (perhaps a "file a ticket" button that appears on every page?) An alternate idea is to add this to the src CLI.

It would also be nice if these feature auto-redacted fields that contain secrets.

It would *also* be nice if config changes (with secrets redacted) were synced back to sourcegraph.com automatically (this could be opt-in or opt-out depending on what customers prefer). This would make it much easier to quickly answer questions like "what value does customer X have for setting Y?", which come up when dealing with issues at comparable customers.

Customers (not exhaustive):

- https://app.hubspot.com/contacts/2762526/company/464956351 would have been helpful in a recent upgrade
- https://app.hubspot.com/contacts/2762526/company/419771425 would have been helpful in past upgrades

**Comment by slimsag** [comment]
Is this actually a priority for 3.4? IMO there are higher priority issues than this. This feels "nice to have" to me.

**Comment by beyang** [comment]
I'd like to at least discuss it. We can punt if there are enough higher-pri items, but IMO this affects our ability to offer quick support to customers (wasting both their time and ours). Doesn't need to be a UI; we should go after the simplest solution here.

**Comment by beyang** [comment]
Related: https://github.com/sourcegraph/sourcegraph/issues/3634

The config collection mechanism should probably be tied to the feedback collection mechanism, which might be tied to filing an issue.

Proposal:
* Feedback widget that has 2 buttons: (1) Quick feedback (2) File an issue
  * Quick feedback is just for text issues. It should send the current page the user is on (redacting any sensitive info from the URL) and the current config (redacting any secrets)
  * File an issue is for cases when one of the following holds: the user wants to paste an image, the user anticipates longer discussion, the user wants to close the loop ("tell me when this issue is closed")
* UI mechanism to collect config. Maybe this is a button in the feedback widget.
* GitHub issue template directs people to collect config from UI

**Comment by keegancsmith** [comment]
It doesn't look like any work has been done on this, so putting it into the backlog.
