### ISSUE TITLE
Expand support for dependencies search

### ISSUE THREAD

**Issue by eugeniaft** [sourcegraph/sourcegraph#33688]
## Problem to solve
As part of the work proposed in [RFC 593](https://docs.google.com/document/d/1SkM8CG0IksvPEKRBRVLKipiRJTopx6Vq_hSWRJ9NyKs/edit#heading=h.trqab8y0kufp), this issue tracks the work of the team to expand dependencies search to more languages and adding reverse dependencies search.

## Measure of success
Users can search through the dependencies of their repositories in Python and JVM.

## Solution summary
Support [searching dependencies](https://docs.sourcegraph.com/code_search/how-to/dependencies_search) in more ecosystems.

## What specific customers are we iterating on the problem and solution with?

- TO DO

## Impact on use cases

Incident Responses / Fixing Vulnerabilities
Code Reuse

## Delivery plan

- [x] [pypi support](https://github.com/sourcegraph/sourcegraph/issues/32659)
- [ ] <strike>[JVM support](https://github.com/sourcegraph/sourcegraph/issues/32660)</strike>
- [ ] `repo:dependents(...)` : #32661

**Comment by jyavorska** [comment]
@eugeniaft I'm changing this from engineering milestone to L3 as it does benefit customers (engineering milestone is specifically for things like prototypes or internal tooling, where customers don't benefit.) If I'm misunderstanding that and customers won't benefit, please feel free to change it back.
