### ISSUE TITLE
Upgrade `@visx` dependencies to `^2.0.0` to fix `react` peer dependency warnings

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#33712]
## Problem

Run `yarn install` locally on [this branch](https://github.com/sourcegraph/sourcegraph/pull/33641) to see `react` peer dependency warnings.

## Expected behavior

There are no warnings related to invalid `react` peer dependency declared by `visx` packages.
[Link](https://github.com/airbnb/visx/blob/master/CHANGELOG.md#v210-2021-08-17) to the `visx` release that should fix the issue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
