### ISSUE TITLE
Code Insights: Add new insight button disabled

### ISSUE THREAD

**Issue by unclejustin** [sourcegraph/sourcegraph#33733]
Cristina's notes from Slack:

1. Added a license to `k8s` without `code-insights`. (Then restarted the worker so it would freeze the insights right away.)
2.  Verified that the Limited Access Mode Dashboard was created and had the correct 2 insights attached to it.
3.  Verified that I cannot add/remove insights from the LAM dashboard. (Frontend check.)
4.  Deleted one of the insights from the LAM dashboard.
5.  Tried deleting the Limited Access Mode Dashboard and got an error saying I can't. (Which is correct.)
6.  Went to the All Insights page and tried to add a new insight. ![:bug:](https://a.slack-edge.com/production-standard-emoji-assets/13.0/apple-medium/1f41b@2x.png) [@Justin Boyson](https://sourcegraph.slack.com/team/U029KKZV916) this seems to be disabled on the front end. How are we checking for this? There's currently only one unfrozen insight at this step.
7.  Plugged in the license key with `code-insights`
8.  Verified that all of the insights were unfrozen.
9.  Verified that I could remove insights from the LAM dashboard and also delete it.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by unclejustin** [comment]
@Joelkw @CristinaBirkel I think this might be just a misunderstanding. Can you two please take a look at [this loom](https://www.loom.com/share/d7bbb5e864794d60b6817e419279119f)?

Cristina, can you confirm this is what you ran into? 
Joel, can you confirm this is working as intended?

**Comment by Joelkw** [comment]
@unclejustin agree that if Cristina confirms the issue was just looking at the wrong button, then there is no problem with this button being disabled. 

@unclejustin not sure I do understand your loom though, because it shows only 1 insight on your dashboard yet that insight is locked. My understanding is that if you have <3 insights in LAM, all insights should be unlocked. Is this just because you're testing in a weird environment or is this either a bug or misunderstanding on my part?

**Comment by CristinaBirkel** [comment]
@unclejustin No I meant the "Create code insight" button on the create insights page. Was that working for you? I can try it again. Maybe I should have made a loom!

**Comment by unclejustin** [comment]
I see! Mine is working as expected. [Check it out](https://www.loom.com/share/0fa00a20593a48aa9cb5516f47bb373e).

cc @CristinaBirkel @Joelkw

**Comment by unclejustin** [comment]
Fixed with https://github.com/sourcegraph/sourcegraph/pull/33809
