### ISSUE TITLE
insights: allow users to fuzzy filter by typing in the dashboard dropdown

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#33731]
[Design](https://www.figma.com/file/Kq8cyQqj5bcyWZMBUdLikX/Fuzzy-filter-by-typing-in-the-dashboard-dropdown-%2333731?node-id=246%3A11)
- add search box (regular size, not small) to the dropdown
- highlight and match after one character
---
Allow users to filter the dashboard dropdown by typing directly into the combobox and fuzzy filtering on the dashboard titles.

Hacked something together on a branch:
https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/5b5176effd50f35a62165a85e090f410716d71b8?visible=3

https://user-images.githubusercontent.com/5090588/162791046-bfa995ea-a71c-4858-a28b-2285ff8ced8c.mp4

Ideally the input would probably not be a separate input box, but instead just allow typing directly when the combo is open. Also, as a stretch goal it would be neat to highlight the fuzzy matches in the dashboard title, but that may be weird / difficult.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by Joelkw** [comment]
We want to reuse the search context box style: 
![image](https://user-images.githubusercontent.com/11967660/163439619-685dddb8-2bec-4485-922d-989f67ff7d8c.png)

**Comment by AlicjaSuska** [comment]
@coury-clark @Joelkw @vovakulikov I've created a [design](https://www.figma.com/file/Kq8cyQqj5bcyWZMBUdLikX/Fuzzy-filter-by-typing-in-the-dashboard-dropdown-%2333731?node-id=275%3A1628):
- incorporates search box directly in the drodpdown
- highlighting matches - I think it'd be a nice touch. TBD after how many characters ([feedback card](https://www.figma.com/file/Kq8cyQqj5bcyWZMBUdLikX/Fuzzy-filter-by-typing-in-the-dashboard-dropdown-%2333731?node-id=1614%3A10300))

Please review as soon as you have a moment so we can move forward with this issue :) Thank you!

**Comment by AlicjaSuska** [comment]
Updated the description with design info

**Comment by AlicjaSuska** [comment]
@unclejustin let's sync for design QA review once you're ready with the implementation. Thank you!
