### ISSUE TITLE
Continue improvements to monorepo support

### ISSUE THREAD

**Issue by eugeniaft** [sourcegraph/sourcegraph#33738]
## Problem to solve

Sourcegraph search is reported to be slow for customers with large monorepos. Customers with a monorepo with a HEAD working copy size > 10 GB are directly affected by this although customers with smaller monorepo but under provisioned or with lots of users may experience performance issues. Slow search impacts user experience. Moreover, time to index after a new commit can be slow resulting in wait times for users wanting to search through recent changes made to the codebase.

## Measure of success

Current goal: At a P75 level, synthetic monorepo with a HEAD working copy size of 15 GB will index in less than 30 minutes, indexed searches complete in less than 2 seconds, and unindexed searches complete in less than 10 seconds. Based on customer feedback this goal could be adjusted.

## Solution summary

The search core team has been working on several initiatives to improve performance, including [incremental indexing](https://github.com/sourcegraph/sourcegraph/issues/29731) and a faster[unindexed search prototype](https://github.com/sourcegraph/sourcegraph/pull/33783). Additionally the team has also established a testing framework to measure performance improvements. Our FY23Q1 goal was met for indexed searches and is on track for unindexed searches. In this quarter, the team will continue the work started in Q1 and iterate on customer feedback.

## What specific customers are we iterating on the problem and solution with?

- https://github.com/sourcegraph/accounts/issues/6716
- https://github.com/sourcegraph/accounts/issues/574
- https://github.com/sourcegraph/accounts/issues/578

## Impact on use cases

No direct use case impact, this work will impact our overall core product.

## Delivery plan

- [ ] Engage with customers to gather feedback on performance and test improvements worked on in Q1.
- [ ] Monitor synthetic monorepo performance metrics and adjust goals based on feedback.
- [ ] Issue tracking work: [#36473](https://github.com/sourcegraph/sourcegraph/issues/36473)

**Comment by malomarrec** [comment]
Hey @eugeniaft, this issue didn't have a team label. Given you created it, I assigned you and added your team label. Feel free to unassign yourself. If this is not the right label, can you make sure to add the right one?

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/search-core - the "team/search-core" label was applied to this issue.

**Comment by eugeniaft** [comment]
We have recently made significant improvements towards our performance goals:

- Incremental indexing prototype. Early performance numbers show that the time it takes to index a repo after a new commit is decreased by 75% from 36 mins to 9 mins. These numbers are based on our gigarepo (a synthetic monorepo of HEAD size of 15 GB

- hybrid searcher + zoekt prototype is ready to be productionized. Initial latency numbers show unindexed search results complete in less than 1 second.

In this quarter we will: 

- Iterate with customers to gather feedback around incremental indexing

- Productionalize hybrid searcher + zoekt prototype
