### ISSUE TITLE
Getting started page for notebooks 

### ISSUE THREAD

**Issue by marisak** [sourcegraph/sourcegraph#33753]
The design team is working on a rubric for estimating design effort. The RFC is not approved yet, but you can read it [here](https://docs.google.com/document/d/1Ji4Mljsr1iXTir3gLhPXlwnEXXxarrBuYm4af-UpIDM/edit#heading=h.r76ejvr0z0y2). Estimates may change as the process evolves. 

**T-shirt size:** M

**Discover** 
- Is exploratory research required: Minimal research around what information should be included based on customer feedback; Refer to other designers' research/work on getting started pages 
- How much risk is involved: Low risk, we already have other getting started pages; Worst case, this turns out unhelpful, but not a detractor 

**Define**
- No RFC required 
- Need design support, not just consultation 
- Single iteration required due to release timeline 
- User flows would be beneficial 

**Develop/Design**
- High-fi designs will be needed, will require iteration 
- Would benefit from some user testing but won't have time for it 
- Content will need to be developed (Ben has signed up to do this) 

**Deliver**
- Designer will need to review PR 
- No scope for user testing 
- Risk: Getting started content should be validated before launch 

**Measure**
- (?) Unsure if new metrics need to be added 
- Additional documentation not needed 

See also: [Content for notebooks getting started page](https://app.zenhub.com/workspaces/search-product-61302e38f801dc0012e2e050/issues/sourcegraph/sourcegraph/33755)

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by rrhyne** [comment]
@marisak  Meta comment: I think the issue would be more succinct if we only included what we will do, not what we won't do. WDYT?

**Comment by marisak** [comment]
@rrhyne I think if we have the whole spectrum of templates fleshed out, it'll be easier to determine what's not being done by comparison. To me, there's some value in clearly stating "normally we might want to do X, but for Y reasons, we're not right now."

**Comment by marisak** [comment]
Whoops, haven't updated this issue in a few days. Here's the latest. 

I took another look at the getting started after some feedback from Rob and Ben around consistency with our other “getting started” pages. The two most important changes to make for consistency’s sake are: (1) put the getting started content in a separate tab, and (2) use a single card at the top of the page instead of a carousel. I’ve explored some other types of content we could incorporate into getting started, focusing on what we have available to us right now due to timeline constraints.
Figma: https://www.figma.com/file/32wyz09t6u2bSBvsJwmDEA/Search-Notebooks-GA?node-id=2381%3A16536
Loom: https://www.loom.com/share/ddd0e4e14e6a485e91a08963df7bcbdd

Additional discussion in Slack.

**Comment by marisak** [comment]
Following today's pairing session with Rok and Ben, here's the layout we agreed on ([Figma](https://www.figma.com/file/32wyz09t6u2bSBvsJwmDEA/Search-Notebooks-GA?node-id=2427%3A16681)). I moved the agreed-on design to the Wireframes page instead of Playground, though all the past work is still in the Playground page.
