### ISSUE TITLE
Content for notebooks getting started page 

### ISSUE THREAD

**Issue by marisak** [sourcegraph/sourcegraph#33755]
The "getting started" page for notebooks will need written content to give new users more information on notebooks. Videos or gifs may also be needed. 

See also: [Getting started page for notebooks](https://app.zenhub.com/workspaces/search-product-design-616db3900ad0860010044670/issues/sourcegraph/sourcegraph/33753)

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.
