### ISSUE TITLE
Turn on notepad for notebooks GA 

### ISSUE THREAD

**Issue by marisak** [sourcegraph/sourcegraph#33752]
The notepad feature allows users to create notebooks from search results and file pages. It will ship disabled by default, but we want to make it easy to discover the feature and allow users to enable and disable it. 

#### Discover
- [x] Reviewed with product team and incorporated their ideas (include in Notebooks list page header)

#### Define
- [x] Github issue

#### Develop/Design
- [x] [High fidelity design](https://www.figma.com/file/32wyz09t6u2bSBvsJwmDEA/?node-id=2181%3A12754)

#### Deliver
- [x] [Loom](https://www.loom.com/share/289726c3a5f440279fb1fb850b22dc80)
- [x] Team review
- [x] Designer review
- [x] QA

#### Measure
- [x] Metrics have been defined

NOTE:
The design team is working on a rubric for estimating design effort. The RFC is not approved yet, but you can read it [here](https://docs.google.com/document/d/1Ji4Mljsr1iXTir3gLhPXlwnEXXxarrBuYm4af-UpIDM/edit#heading=h.r76ejvr0z0y2). Estimates may change as the process evolves.

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by rrhyne** [comment]
Initial exploration + metrics definitions:
https://www.figma.com/file/32wyz09t6u2bSBvsJwmDEA/?node-id=2181%3A12754

Loom video explaining the proposal:
https://www.loom.com/share/289726c3a5f440279fb1fb850b22dc80
