### ISSUE TITLE
Accessibility auditing and remediation

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#33759]
Execute work required for WCAG compliance. We expect this to take one full engineer's time on Search Product in FY23 Q2.

**Comment by jyavorska** [comment]
@benvenker I'm changing this from engineering milestone to L3 as it does benefit customers (engineering milestone is specifically for things like prototypes or internal tooling, where customers don't benefit.) If I'm misunderstanding that and customers won't benefit, please feel free to change it back.

**Comment by benvenker** [comment]
All good! Just didn't have an obvious use case and we don't anticipate much
design work, if any, so wasn't 100% sure.

**Comment by benvenker** [comment]
Added the "KPI/ARR Retention" label as this effort was started by a mandate from CVS. If someone has a better option here (or that situation has changed) please feel free to update.
