### ISSUE TITLE
Rockskip is slow when Postgres latency is high

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#33751]
A customer [reported](https://sourcegraph.slack.com/archives/C015JREMBTR/p1649703632317229?thread_ts=1648162520.650689&cid=C015JREMBTR) Rockskip being really slow:

```
    progress 17.62% (indexed 82030 of 465540 commits), 480h50m24.283812818s remaining
    Tasks (370253.72s total, current CommitTx): GetSymbol 56.11% 7456945x, InsertSymbol 14.72% 1906512x, UpdateSymbolHops 11.00% 1424752x, get hops 6.54% 82031x, GetCommitByHash 3.47% 465541x, AppendHop+ 2.89% 82031x, AppendHop- 2.12% 82031x, CommitTx 0.76% 82031x, DeleteRedundant 0.64% 82031x, InsertCommit 0.64% 82031x, Log 0.61% 1x, parse 0.28% 849129x, ArchiveEach 0.22% 164062x, RevList 0.00% 1x, idle 0.00% 1x, iLock 0.00% 1x,
```

Based on GetSymbol taking 56% of the time with an average of 40/s, I'm guessing the network latency to Postgres is around 25ms, which is pretty high and Rockskip hasn't been optimized for high latency (yet). There's probably room for improvement here.

The customer ran `tcptraceroute` (because Amazon RDS instances block ping) and discovered the latency is around 28ms.

**Comment by sourcegraph-bot-2** [comment]
Heads up @macraig - the "team/code-intelligence" label was applied to this issue.
