### ISSUE TITLE
Add notebooks to Sourcegraph global navigation 

### ISSUE THREAD

**Issue by marisak** [sourcegraph/sourcegraph#33754]
The design team is working on a rubric for estimating design effort. The RFC is not approved yet, but you can read it [here](https://docs.google.com/document/d/1Ji4Mljsr1iXTir3gLhPXlwnEXXxarrBuYm4af-UpIDM/edit#heading=h.r76ejvr0z0y2). Estimates may change as the process evolves. 

T-shirt size: S-M

Discover 
- Is exploratory research required: No
- How much risk is involved: Low risk? Adding new items to the top navigation is a standard for our major product launches 

Define
- No RFC required 
- Need design support, not just consultation 
- Also need signoffs from rest of design team 
- Single iteration required due to release timeline 
- User flows would help to situate this change in the larger environment of search product, but may not have time 

Develop/Design
- High-fi designs will be needed, will require minor iteration 
- Would benefit from some user testing but won't have time for it 
- In particular, need to find an icon; hopefully will not need to create one 

Deliver
- Designer will need to review PR 
- No scope for user testing 

Measure
- (?) Unsure if new metrics need to be added 
- Will affect documentation of notebooks

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by marisak** [comment]
I propose using [book-outline](https://materialdesignicons.com/icon/book-outline) as the icon for notebooks. Here's a [Figma file](https://www.figma.com/file/32wyz09t6u2bSBvsJwmDEA/Search-Notebooks-GA?node-id=2141%3A12369) showing some example usages and justification.

**Comment by benvenker** [comment]
Looks good to me!

**Comment by marisak** [comment]
I've published all the changes to the Wildcard Figma; here's a clean frame ([Figma](https://www.figma.com/file/32wyz09t6u2bSBvsJwmDEA/Search-Notebooks-GA?node-id=2304%3A18460)) with the proposed changes at all 3 sizes.
