### ISSUE TITLE
insights: refactor where time series are resolved in the resolver hierarchy

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#33804]
Refactor where the timeseries data is loaded for insight views such that we don't have multiple disparate places loading data depending on the series type. Most likely this will mean raise it to the highest level in the resolver hierarchy (InsightViewResolver) for all types.

[Here is a notebook with a walkthrough](https://sourcegraph.com/notebooks/Tm90ZWJvb2s6NjM4#insight-series-loading-behavior-5fcdd217-2e0b-4ef0-9636-375e87260a62)

And here is a diagram showing the hierarchy and where the loading occurs for different types.
![export(5)](https://user-images.githubusercontent.com/5090588/163010920-238fcca2-7ef1-4c95-b6fb-b18b5da49f61.png)

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
