### ISSUE TITLE
insights: LAM dashboard won't be automatically re-created if it's deleted

### ISSUE THREAD

**Issue by CristinaBirkel** [sourcegraph/sourcegraph#33808]
Repro:

1. Enter Limited Access Mode
2. Ensure that the LAM dashboard is created.
3. Upgrade to leave LAM.
4. Delete the LAM dashboard.
5. Re-enter LAM

Expected: The LAM dashboard shows back up.
Actual: It stays soft-deleted and does not reappear.

Should be an easy fix!

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
