### ISSUE TITLE
self-hosted pgsql is crashing in large deployment

### ISSUE THREAD

**Issue by michaellzc** [sourcegraph/sourcegraph#33807]
## Context

When deployment has a large number of repositories, we noticed weird memory behaviour in `pgsql`. The memory will keep on increasing until it hits the memory limit and gets OOMKILL by the kernel. Upon getting OOMKILL, the database will restart right away and users may experience a brief longer page load.

## Fix

We're currently investigating the root cause of such behaviour.

**Comment by malomarrec** [comment]
Hey @michaellzc, this issue didn't have a team label. Given you created it, I assigned you and added your team label. Feel free to unassign yourself. If this is not the right label, can you make sure to add the right one?

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/cloud - the "team/cloud" label was applied to this issue.
