### ISSUE TITLE
Search results should remove extra indention from code

### ISSUE THREAD

**Issue by francisschmaltz** [sourcegraph/sourcegraph#3382]
Search results use the indention of the code on the page. In some situations, this can cause the search results to be closer to the center rather than left aligned. We should remove all of the common indention so that the results are always aligned correctly.

![Screen Shot 2019-04-12 at 11 00 06 AM](https://user-images.githubusercontent.com/11583013/56056907-5e09b600-5d12-11e9-8bd1-7a4446e4eae2.png)

**Comment by dadlerj** [comment]
It seems correct to me to do it this way. If you're scrolling down the page, there's information conveyed in the whitespace (even if it looks a bit weird when there are a lot of them).

**Comment by nicksnyder** [comment]
I agree with Dan. I am not convinced that this is the right thing to do.

@francisschmaltz If you want to pursue this the right next step is to collect customer feedback. My overall sense is that there are a lot of other things we could do that are more important and more impactful, so I am going to close this.
