### ISSUE TITLE
Insights: Allow search contexts as filters to code insights (v.1) - collapsable sections and autocomplete

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#33830]
This issue is a continuation of the v.0 implemented in #33249 - we've added a simple context input field without autoselection.

Scope for V.1 ([designs](https://www.figma.com/file/Ml5dtV9ni4mfffbfOfF9jg/Allow-search-contexts-as-filters-to-code-insights-(v0)-%2333249?node-id=1163%3A15096) WIP)
- add collapsable sections
- add indicator to each section that appears when non-default values are applied
- when section(s) is(are) collapsed, show the value (could be truncated) - content name or regex filter (if applied)
- add autocomplete for context field. List of the context should be filtered to show only query-based contexts.
- add empty state to the list (no results)

Reminder: apply visual issues raised in #33249 (@vovakulikov)

Support only one context:
-- We don't want to support multi-context filter here because it introduces unnecessary complexity and we can't find the case where it is useful if they work with in intersection mode (Figma [comment thread](https://www.figma.com/file/Ml5dtV9ni4mfffbfOfF9jg?node-id=1313:24763#182347150) for more info)

- We probably want to have context as a possible input in repositories field in the insight creation UI.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
