### ISSUE TITLE
dev/ci: allow steps to require only subsets of `.tool-versions`

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#33854]
See https://github.com/sourcegraph/sourcegraph/pull/33853 - even a fresh install of just 1 required tool can be a lot faster than using the asdf cache. Could be helpful to get subsets of tools cached as well though

**Comment by jhchabran** [comment]
That's interesting! It would be useful to see which tools are slowing things down exactly.
