### ISSUE TITLE
Cannot enable readOnlyRootFilesystem in Sourcegraph prometheus container

### ISSUE THREAD

**Issue by kevinwojo** [sourcegraph/sourcegraph#33862]
# Problem 
Alerting breaks when `readOnlyRootFilesystem` is set to "true" on our Kubernetes installations (helm and kustomize). 

Sourcegraph uses `prom-wrapper` to wrap Prometheus and AlertManager so that the `sourcegraph-frontend` service can provide dynamic configurations for Prometheus alerts and Alertmanager routing. The prometheus container has a directory `/sg_config_prometheus` that contains `alertmanager.yml` that is dynamically updated by `prom-wrapper`. If the filesystem is set to read-only mode, `prom-wrapper` is unable to modify the file and apply the correct alert routing, preventing alerts from being delivered.

# Workaround
Set `readOnlyRootFilesystem: false`.

This issue is referenced in the workaround.

**Comment by sourcegraph-bot-2** [comment]
Heads up @caugustus-sourcegraph @kevinwojo @michaellzc - the "team/delivery" label was applied to this issue.
