### ISSUE TITLE
insights: incorrectly taking /insights to the getting started tab even when insights exist on the instance

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#33883]
We had logic that shows you the all insights page if there are any insights visible to you, and otherwise the getting started page if not. (Because we want to show you relevant insights if they exist; they do a better job of explaining the feature than the getting started page's fake examples.) 

Loom of the incorrect current state (because k8s has insights and it should take me to the all insights dashboard): 
https://www.loom.com/share/7a83478517df404c86acbdc4bd966fd9?focus_title=1&muted=1&from_recorder=1

This seems to have regressed sometime in the last few days. 

Test flow: 
1. Click the "insights" tab on an instance with insights created
2. Correct: You are taken to the "all insights" dashboard 
    1. Incorrect (current state): you are taken to the getting started page. 

Also test the opposite case: 
1. Click the "insights" tab on an instance with no insights created. 
2. Correct: you are taken to the getting started page
     1. (Incorrect: you are taken to an empty all insights dashboard)

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by vovakulikov** [comment]
From the slack thread
>I think the culprit here is this PR about fixing creation button permission https://github.com/sourcegraph/sourcegraph/pull/33809
For the context. To determine which page should be rendered we fetch just one insight with `insightViews(first:1) {...}`

>If we have at least one insight we redirect you to the dashboard page, otherwise - in product landing page. For the creation UI create button we also use this query to understand  do we have enough available "slots" (active insights) on our backend in LAM. 

>And if we have more than 2 active insights we should disable button (Justin's PR fixed this) but this also means that for this case we load all data about all available insights on the frontend just for disabling one button on the creation UI.

>@Cristina Birkel I think it worth to try to move this logic on the backend and provide some API query over insight specific user permissions, like canCreate, canUpdate, insightsLimit, .... in order to avoid overfetching on the frontend

> @Cristina Birkel Or we could extend our filters in insightView query and add filter about isFrozen state. Like
insightViews(first: 2, stateType: NonFrozen) {...} this would help us to check the create insight button availability and avoid fetching a big chunk of data. cc @Coury Clark since I remember he was working on filters there as well

cc @unclejustin @coury-clark @CristinaBirkel
