### ISSUE TITLE
insights: capture mid-interval daily updates (snapshots) for capture group insights

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#33881]
On search insight types, we capture a daily snapshot and "save" that snapshot every x_timeframe (whatever the user defined as their interval). For capture groups, we _do_ update them every user-defined-interval after creation, but we don't capture nor display a daily point like we do with search insights. This means a user with a monthly interval only sees a new datapoint every month. 

We should unify this feature because the daily values provide a useful "what is the value right now," provide reasons for users to check and get more frequent value out of their code insights, and are more efficient in storage size than the alternative, which is to set every insight to have a daily interval (if you do care about having a "today's value" always available).

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
