### ISSUE TITLE
Clean up usage of git.execSafe

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#33890]
[git.ExecSafe](https://github.com/sourcegraph/sourcegraph/blob/c31661b83a7163a5cc4dc3c37c7f3ea90ae865cf/internal/vcs/git/exec.go#L24)  is only called by [getDefaultBranch](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@c31661b83a7163a5cc4dc3c37c7f3ea90ae865cf/-/blob/internal/vcs/git/default_branch.go?L43).

Why does this specific call need to be safe and no others? The only thing that makes `execSafe` safe is that we call [gitdomain.IsAllowedGitCmd](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@c31661b/-/blob/internal/gitserver/gitdomain/exec.go?L77). However, we call this at the [server](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@c31661b83a7163a5cc4dc3c37c7f3ea90ae865cf/-/blob/cmd/gitserver/server/server.go?L1319) anyway so what not check it all for all commands on the client too?

We should be able to remove `execSafe` and check for safety when constructing any command.

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.
