### ISSUE TITLE
Remove CTA for creating a team in the "Getting started checklist"

### ISSUE THREAD

**Issue by ryankscott** [sourcegraph/sourcegraph#33901]
We no longer are going to push people to create teams so we should remove this step

**Comment by erzhtor** [comment]
Hey, @ryankscott. Added it to our backlog. Quick question, should we replace it w/ some other step or drop it at all?

**Comment by ryankscott** [comment]
In the short term I'd drop it. We can re-evaluate that onboarding flow later.
