### ISSUE TITLE
Fix command palette styles on GitLab

### ISSUE THREAD

**Issue by taras-yemets** [sourcegraph/sourcegraph#33906]
Investigate and fix the command palette issue on GitLab: items are rendered, but not visible.

![image](https://user-images.githubusercontent.com/25318659/163400883-fd4ad341-2f20-4859-a53c-436e7f7fbda2.png)

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/growth-and-integrations" label was applied to this issue.
