### ISSUE TITLE
dev/sg: spike approachability of sg.config.yaml

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#33913]
[sg.config.yaml is also nearing 1000 lines of configuration](https://github.com/sourcegraph/sourcegraph/blob/main/sg.config.yaml), which may become problematic -  it will soon (and IMO already has) become rather daunting to change and contribute to.

We also have issues regarding running runsets of multiple teams/cross-domain (merging runsets), etc. that might contribute to solving this (if we make things more composable)

One idea is to have runsets be in code, leaving individual commands and tests in `sg`, so that merging strategies are easier to define

**Comment by bobheadxi** [comment]
From duplicate https://github.com/sourcegraph/sourcegraph/issues/33448: 

> Also see: https://sourcegraph.slack.com/archives/C01N83PS4TU/p1648811099908759
>
> Possibly related: https://github.com/sourcegraph/sourcegraph/issues/25438

**Comment by jhchabran** [comment]
Important: re-eval this ticket

**Comment by bobheadxi** [comment]
On a more serious note, I've come to think of the `sg.config.yaml` sprawl as not too bad. It might even be nice that everything is in one gigantic file, and I can add anything I want to it
