### ISSUE TITLE
insights: migrate compute searches to the streaming endpoint

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#33925]
To fully migrate all of our Search integrations to a stream, we need to move the compute queries to their respective streaming endpoint.

Notebook for context https://sourcegraph.com/notebooks/Tm90ZWJvb2s6NjU5

Some thoughts:
1. Is the schema the same as the standard streaming API?
2. Are there any differences between the GraphQL and stream in terms of available response fields?

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by coury-clark** [comment]
Open work items:

- [ ] https://github.com/sourcegraph/sourcegraph/issues/34228
- [ ] https://github.com/sourcegraph/sourcegraph/issues/34230
