### ISSUE TITLE
notepad: annotation sometimes don't make it to a created notebook

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#33922]
This is difficult to reproduce, but I've had it happen twice to me in two days.

1. Use notepad to add some file ranges. Annotate the blocks and close the annotation with cmd+enter.
2. Press create notebook

In my first encounter, *none* of the annotations on about 5 blocks persisted. When navigating back in the browser, all of the annotations were empty in the notepad but the searches / ranges were still there.

The second encounter, one of two ranges had preserved their annotations. Incidentally in this case it was the most recently added that did not persist. Navigating back in the browser resulted in the same (image below):

<img width="312" alt="image" src="https://user-images.githubusercontent.com/5090588/163433006-370b6481-1ce2-49c1-95fb-a91a14f7d9fb.png">

Here is the notebook as it was created from the notepad:
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/5090588/163433081-14a70f8e-418c-4b88-b158-7f39a3c4bc47.png">

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by benvenker** [comment]
@fkling FYI. I know you're on PTO tomorrow so @novoselrok was going to see if you had any bandwidth to see if anything stood out to you in the code that could cause this; I know you're not necessarily familiar with the notepad component code though.
