### ISSUE TITLE
Search for repos depending on a specific package

### ISSUE THREAD

**Issue by eugeniaft** [sourcegraph/sourcegraph#33934]
## Problem to solve

Dependencies search currently only allows users to search through the dependencies of their repositories but does not allow users to search what repositories depend on a specific package. This is important for identifying the impact of vulnerabilities.

## Measure of success

`repo:dependents(...)` is implemented

## Solution summary

Allow easily finding which repos depend on a given package, with a new `repo:dependents(...)` predicate.

## What specific customers are we iterating on the problem and solution with?

- TO DO

## Impact on use cases

Incident Responses / Fixing Vulnerabilities

## Delivery plan

- [ ] [Implement repo:dependents(...)](https://github.com/sourcegraph/sourcegraph/issues/32661)

**Comment by sourcegraph-bot-2** [comment]
Heads up @jjeffwarner - the "team/search-core" label was applied to this issue.

**Comment by eugeniaft** [comment]
This was done by https://github.com/sourcegraph/sourcegraph/pull/35374
