### ISSUE TITLE
insights: spike: figure out the problem statement with our API problems?

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#33931]
From a planning sync, it was determined that "working with our API sucks" which slows down our overall velocity. But we aren't even sure on the problem statement(s), and that's the first step to solving this issue. 

In general, things we'll want our API to handle in the next three months: 
1. Saving insights metadata (per-insight) for things like:
     1.  capture group sort order #33930
     2. y-axis set at 0 or not #31516
     3. chart types #32940, #32942 , #32943 
     4. other chart settings (derivative vs cumulative values) #33327
     5. potential permissions settings (setting permissions per insight) upcoming, RFC 617

This issue is "done" when: 
1. We have a clear understanding of what's hard in our API now. 

A followup to this work (or, optionally, part of this issue) would be: 
1. Proposals to fix these solutions and the relative time gain of doing that work (e.g., "it might take us a week or two to do X change but given the above plans it'll ultimately save as three weeks net")

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by Joelkw** [comment]
closing this in favor of #33933
