### ISSUE TITLE
insights: spike – recording additional metadata on capture group types to save sort order 

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#33930]
We want to allow users to create capture group insights that are most valuable to them, meaning they need a way to deterministically sort the results returned. This is from [RFC 655](https://docs.google.com/document/d/1Kv83fCz4dfqv8AGUTWpt7z5w_CGlO53WEXtDSfVG5e0/edit#)

We likely want to allow users to set: 
1. Sort order (by current point in time): four different orders: 
    1. return N items by top results count (so the top 20 most seen patterns, for example)
    2. return N items by lowest results count (20 least seen patterns, for example)
    3. return N items by ascending lexicographical/semvar sort (whatever we used in our key sorting) – (return the oldest 20 versions, for example, or the first 20 css variables in use starting with a-, or b-, etc.) 
    4. return N items by descending lexicographical/semvar sort – (return the newest 20 versions, for example, or the last 20 css variable names by alphabetical order, so z-, y-, etc.) 
5. Sort size – let then specify N series, N greater than or equal to 1 and less than or equal to 20

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by coury-clark** [comment]
@Joelkw Is there any reason this should be limited to capture group insights? Is this a general property we might want to enable for insights (to sort over all of the series by label or by count)?

**Comment by AlicjaSuska** [comment]
+1 to @coury-clark 's comment - I also think we should enable it for all insights.

I've started working on designs for this issue. I would love your feedback about this first iteration. Here is the [loom walkthrough](https://www.loom.com/share/56eefdeadd5041fe9bed52c7b40d3910) with all the necessary details. Please, comment in [Figma](https://www.figma.com/file/lYD20GUga7m3aZ49fYh1Vu/Charts-with-20%2B-matches-%7C-RFC-655-%7C-%2333930-%5BWIP%5D?node-id=1614%3A31). Thank you!

@CristinaBirkel @Joelkw @vovakulikov
