### ISSUE TITLE
Deployment on cloud production that skipped preprod are logged as an exception in github.com/sourcegraph/sec-pr-audit-trail/

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#33959]
Follow-up of the discussion over https://github.com/sourcegraph/sourcegraph/issues/33789. 

In the eventuality of someone deploys directly in the `release` branch, an exception should be logged.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/cloud-devops - the "team/devops" label was applied to this issue.

**Comment by danieldides** [comment]
In the `sec-pr-audit-trail` ticket it would be great if we could inform the user that they now need to also merge their changes into `preprod` as well otherwise the next automated release will be stuck waiting for someone to click `Update Branch` or merge `release` -> `preprod` again.
