### ISSUE TITLE
vscode: add integration test cases for searching

### ISSUE THREAD

**Issue by tjkandala** [sourcegraph/sourcegraph#33972]
On top of #33921.

Assert that:
- Clicking on each type of search match (examples: commit, repo) results in the expected behavior (example: repo match should open repo page, search match should open remote file editor). 
- Clicking on a filter in the sidebar webview should update the query in the search panel webview

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/growth-and-integrations" label was applied to this issue.

**Comment by abeatrix** [comment]
completed and merged to main
