### ISSUE TITLE
Codeintellify hover popover reposition jank

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#33987]
Using the same demo extension in https://github.com/sourcegraph/sourcegraph/issues/33985 the popover gets jankily repositioned:

Frame 1

<img width="198" alt="CleanShot 2022-04-15 at 19 29 28@2x" src="https://user-images.githubusercontent.com/1387653/163656595-660da40a-d29c-4bbd-a71d-ece50ac9cf67.png">

Frame 2

<img width="184" alt="CleanShot 2022-04-15 at 19 29 44@2x" src="https://user-images.githubusercontent.com/1387653/163656602-34e07e39-df30-43d5-b79b-ed8f33536478.png">

Frame 3

<img width="189" alt="CleanShot 2022-04-15 at 19 29 58@2x" src="https://user-images.githubusercontent.com/1387653/163656607-0bce419f-65dd-4289-8758-2cf294e25be1.png">

[Tippy.js](https://atomiks.github.io/tippyjs/) doesn't suffer from this problem because it uses [`inset`](https://developer.mozilla.org/en-US/docs/Web/CSS/inset) with values `0` (anchor) and `auto` (calculate) values to tell the browser to anchor the tooltip to the correct corner or calculate the right value based on the size of the element:

![CleanShot 2022-04-15 at 19 33 14@2x](https://user-images.githubusercontent.com/1387653/163656729-3f1e1237-3569-459a-91d8-6a7887a56283.png)

Maybe we can do that, too.

Discovered while investigating https://github.com/sourcegraph/sourcegraph/issues/33557

**Comment by chrismwendt** [comment]
Had to [revert](https://github.com/sourcegraph/sourcegraph/pull/34206) the [fix](https://github.com/sourcegraph/sourcegraph/pull/34028) due to unexpected spacing problems that I didn't see in local dev. I haven't been able to repro.

**Comment by mrnugget** [comment]
@chrismwendt what's the status of this?

And also, second question, is this related? Or should I create a separate ticket for this?

https://user-images.githubusercontent.com/1185253/165926551-f39cb82a-b761-4f43-9e98-4e4b4fa13afa.mp4

**Comment by chrismwendt** [comment]
I managed to repro and submitted a second attempt at fixing this: https://github.com/sourcegraph/sourcegraph/pull/34859

It turns out that the browser extension was setting `relativeElement` to `document.body`, which isn't positioned at all, let alone `position: relative`, so the `bottom` property's origin was falling back to the viewport's height rather than the height of `document.body`.
