### ISSUE TITLE
Only send external service ID when requesting a sync

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#33997]
When requesting an external service sync we currently pass through an external service API sruct:
https://github.com/sourcegraph/sourcegraph/blob/7148009913d77239bb24e79274682cc1e0866c32/internal/repoupdater/client.go#L240

This means that on the handler side we need to reconstruct the service here:
https://github.com/sourcegraph/sourcegraph/blob/656d2404285f49d4692d783c668083bfdcff033d/cmd/repo-updater/repoupdater/server.go#L197-L202

It's *very* easy to miss a field and recently led to a [bug](https://github.com/sourcegraph/sourcegraph/pull/33995)

Instead, we should just send over the ID and fetch the external service from the database.

We should probably add a new field [here](
https://github.com/sourcegraph/sourcegraph/blob/82cb6e6fdc6dda5f8a262a98a6bd48786135a219/internal/repoupdater/protocol/repoupdater.go#L277) and deprecate the old struct.

We'll need to roll this out over two releases in order to safely remove the old field.

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.
