### ISSUE TITLE
Code Insights: Catch new user paths/journeys in integration and unit tests 

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#34001]
We have stagnation in our test coverage over Code Insights pages and new functionality. We should consider writing new integration and unit test to cover 
- Dashboard creation UI
- Dashboard updating
- Adding insights to the dashboard
- Remove insights from the dashboard action 
- Visual settings for the chart and context menu

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
