### ISSUE TITLE
Search backend: add more consistent tracing for job fields

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#34009]
Tracing on [jobs](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@933e3215c645a428931e005f9732626c80e1a5e4/-/blob/internal/search/job/job.go) has been at least partially unified in [observe.go](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@933e3215c645a428931e005f9732626c80e1a5e4/-/blob/internal/search/job/observe.go). This uses the job name and wraps the stream to provide a trace log on every stream event.

Currently though, most jobs do not add their fields to the traces. This makes debugging more difficult than it could be since the arguments the jobs are executing with are not visible in the traces. The only job that currently adds its fields is [CommitSearch](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@933e3215c645a428931e005f9732626c80e1a5e4/-/blob/internal/search/commit/commit.go?L54-54).

I _think_ the nicest way to handle this would be to add a `Fields()` method to all search jobs, then make that part of the job interface so that we can add them to the trace automatically in [job.StartSpan](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@933e3215c645a428931e005f9732626c80e1a5e4/-/blob/internal/search/job/observe.go?L21-21).

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by lguychard** [comment]
This is "done" in our board, so I will close.
