### ISSUE TITLE
Add required displayName eslint rule

### ISSUE THREAD

**Issue by erzhtor** [sourcegraph/sourcegraph#34005]
It seems like we have lots of anonymous components in React DevTools. It would be good to enforce adding either displayName or named functions. Try migrating existing if not many, or add as warning.

See https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/display-name.md

**Comment by erzhtor** [comment]
@thenamankumar, just FYI, that after https://github.com/sourcegraph/eslint-config/pull/245 is merged and auto-released by CI, it would be better to update https://github.com/sourcegraph/sourcegraph/blob/fa2e2a7709beb4e9a8ce96e63aa1f8ee553c67aa/package.json#L132 as well. 
P.S: Although, maybe dependabot will pick up the changes and automatically create an update PR).

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @a-bergevin - the "team/growth" label was applied to this issue.
