### ISSUE TITLE
Search expressions interpreted wrong due to heuristic

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#34018]
`repo:a b or repo:c d` => `(repo:a repo:c b) or (repo:a repo:c d)` which is wrong.

`(repo:a b) or (repo:c d)` works correctly. This is probably a bug in the heuristic for hoisting terms when parens are absent. Either a bug in this function, or it getting called when it shouldn't: [function](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/search/query/transformer.go?L328&subtree=true)

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by rvantonder** [comment]
Oof, this is more difficult than I thought.

Basically, we treat:

`repo:a b or repo:c d`

and

`repo:a b or d repo:c`

equivalent under the heuristic. But we want the heuristic to fire on the second example and treat it as:


`repo:a (b or d) repo:c`

But it does this also for the first example. So: ordering matters in the visual impression of the expression, which we should map in the heuristic. But we don't actually take this into account when applying it.

The parse tree isn't structured to care about node ordering at this stage of query parsing, and it would be a bit hazardous to assume it. Don't know that there's a way to improve the heuristic to handle this case... My proposal is to make applying the heuristic more strict instead, allowing it to fire only when _one_ query subexpression contains parameters. This would handle the cases:


- `repo:foo file:bar a or b` -> `repo:foo file:bar (a or b)`
- `b or repo:foo file:bar a` -> `repo:foo file:bar (a or b)`
- `b or a file:bar repo:foo` -> `repo:foo file:bar (a or b)`
- `file:x b or a file:bar repo:foo` -> No heuristic.

**Comment by rvantonder** [comment]
> Don't know that there's a way to improve the heuristic to handle this case... 

Turns out I can use ranges on terms in the original query string to know the order, so I can make this more robust the way it was originally intended.
