### ISSUE TITLE
Remove "Join the waitlist" for Teams beta banner from search home page

### ISSUE THREAD

**Issue by erzhtor** [sourcegraph/sourcegraph#34014]
See [this](https://sourcegraph.slack.com/archives/C03B4EMBXL4/p1650278265103289) and [this](https://sourcegraph.slack.com/archives/C025BKWFPDY/p1650300034418469) slack threads.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @a-bergevin - the "team/growth" label was applied to this issue.
