### ISSUE TITLE
Implement RFC 656: Site-wide request allow/blocklist

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#34011]
This ticket tracks the implementation of [RFC 656](https://docs.google.com/document/d/1nCd09UjilJy5pljZrPf5iNIOyoUO971kbkUBK7keATw/edit#heading=h.trqab8y0kufp). It may be split into multiple tickets as necessary.

Tasks:
- [ ] Implement a `MatchList` type that can match against either hostname or IP
- [ ] Implement deserialization for the `MatchList`. Entries should allow globbed hostnames (`*.sourcegraph.com`), IP addresses (`192.168.1.1`), CIDR blocks (`192.168.1.0/24`), and probably also a set of predefined aliases (`link-local`, `private`). IP addresses should support both IPv4 and IPv6.
- [ ] Implement filtering based on the configured allow and block lists for both `InternalDoer` and `ExternalDoer`. The [Gitea implementation](https://sourcegraph.com/github.com/go-gitea/gitea@b74322dfce8d15e9204900913bb815a7b0ba073f/-/blob/modules/hostmatcher/http.go?L30-55&subtree=true) will be a good reference here.
- [ ] Implement configuration of allow/block lists. It has not yet been decided whether this will be configurable by a site admin, or whether it should be set as part of the deployment configuration.
- [ ] Decide on default values for internal/external allow/block lists. Most likely, it will be something like `internal-block-list: []`, `internal-allow-list: ["link-local", "private"]`, `external-block-list: ["link-local", "private"]`, `external-allow-list: []`, but we should ensure that there are no additional IP ranges that we want to add to the defaults. The [IANA special purpose address registry](https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml) will be a good reference here.

Note that specifics are left to the implementer. These are just [my](https://github.com/camdencheek/ ) initial thoughts on how to best approach it.

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by camdencheek** [comment]
This is being handled by @evict ([related PR](https://github.com/sourcegraph/sourcegraph/pull/42108))

**Comment by evict** [comment]
@sourcegraph/repo-management we want to implement allow and block lists as mentioned in this ticket. While working on the implementation I noticed that [we use `ExternalDoer` / `ExternalClient`'s for connections to `github-proxy`](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/repos/github.go?L178-180) (which is internal). Is this intended? I understand GitHub is an external service, but since we are using `github-proxy` would it make sense to use the `InternalClient` for connections to `github-proxy` instead?

**Comment by camdencheek** [comment]
Closing since I think think this has been abandoned. I don't have any plans to work on this.
