### ISSUE TITLE
Improve layout/typography of new code intel reference panel

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#34023]
#### Feature request description
Updates to the typography, layout, and colors of the code intel reference panel prototype, as well as standardizing based on Wildcard. ([Figma design](https://www.figma.com/file/DZMyEJT3g2HT6HmJGNNOnW/%22Better%22-code-intel-panel?node-id=1220%3A3878)) I've also highlighted the reference to make it easier when exploring different reference locations where the token is in the preview.  

#### Is your feature request related to a problem? If so, please describe.
Since sharing the new code intel prototype, we've received internal feedback collated [here](https://docs.google.com/document/d/1qTlcqyLzmmO_MW8UfQvskNH0TLHQ84kl8g0uETrimeM/edit#heading=h.isllvouuw5l9). There is strong feedback that the current sizing of font and layout is not conducive to quickly being able to understand and explore the references.

**Comment by sourcegraph-bot-2** [comment]
Heads up @macraig - the "team/code-intelligence" label was applied to this issue.

**Comment by jjinnii** [comment]
A few very minor changes to improve the consistency and design of the reference panel. Not all the changes I'm listing here are reflected in the screenshots, just what I managed to play around with in the inspector tool 😄 

- Change font size of repository, file path, and occurrence count to .875 rem. We use .875 rem for the breader and filetree and promotes a better visual consistency

**Before**
<img width="1437" alt="Screen Shot 2022-07-25 at 6 55 16 PM" src="https://user-images.githubusercontent.com/87138876/180766096-1889332a-1e58-4b35-92a6-9e005c2ffbb8.png">

**After**
<img width="1435" alt="Screen Shot 2022-07-25 at 7 47 54 PM" src="https://user-images.githubusercontent.com/87138876/180761552-5d12f32c-0d6c-4265-ae3f-4e93163c393f.png">


- Increase font size of the filter input search to reflect the font size used in the symbols input field. Both come up as .75 rem, but as you can see in the screenshot the font size in the symbols input field looks noticeably larger than the one in ref panel. 🤔 

<img width="276" alt="Screen Shot 2022-07-25 at 9 12 42 PM" src="https://user-images.githubusercontent.com/87138876/180775141-a7f0b2da-2eea-4019-ba27-3db536678506.png">

- Enlarge filter icon to 16px by 16px (currently 13.71 x 13.71)

**Comment by jjinnii** [comment]
@oleggromov I've provided some design guidance on this issue. I'm going to remove myself as Assignee and leave it for you to pick up when you have the chance! cc: @macraig
