### ISSUE TITLE
vscode: The link for issue and feature requests to the visual sutdio code extension are broken

### ISSUE THREAD

**Issue by ptxmac** [sourcegraph/sourcegraph#34035]
#### Describe the issue
On the [sourcegraph extension marketplace](https://marketplace.visualstudio.com/items?itemName=sourcegraph.sourcegraph) page under the "Questions & Feedback" section there's a link to creating issues and feedback: 

> New issues and feature requests can be submitted at https://github.com/sourcegraph/sourcegraph-vscode/issues/new.

This link points to a now deprecated repository

#### Where is the issue located?

I assume the source for the marketplace text is this README: https://github.com/sourcegraph/sourcegraph/tree/main/client/vscode#questions--feedback

#### Suggested resolution

Use a link to the correct repository, possibly even with a template specific for vscode

**Comment by jdorfman** [comment]
@ptxmac thanks so much for the heads up!

Do you want to fix it and get the credit? https://github.com/sourcegraph/sourcegraph/edit/main/client/vscode/README.md

If not I can do it, just wanted to give you the option.

**Comment by ptxmac** [comment]
To do it _right_ I would suggest someone from the sourcegraph team create an issue template first, and in that case it's probably much easier to just do both changes, instead of having a ping-pong with me to make a tiny change 😄

**Comment by marekweb** [comment]
Thank you for submitting this issue. This has now been fixed in #34930
