### ISSUE TITLE
codeintel: JVMPackagesSource doesn't respect rate limit config

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#34041]
Despite [existing](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/schema/jvm-packages.schema.json?L42-47), it doesn't seem like it's used at all, since we use a [coursier command invocation to make requests.](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/extsvc/jvmpackages/coursier/coursier.go?L145-202)

**Comment by sourcegraph-bot-2** [comment]
Heads up @macraig - the "team/code-intelligence" label was applied to this issue.

**Comment by olafurpg** [comment]
Sounds good. I've added this to our next planned iteration. Should be an easy fix.

**Comment by tsenart** [comment]
After further discussion, let's repurpose this issue to actually implement rate limiting around `coursier` command invocations.

**Comment by sourcegraph-bot-2** [comment]
Heads up @jjeffwarner - the "team/search-core" label was applied to this issue.

**Comment by stefanhengl** [comment]
This was part of the effort to implement dependency search, which has been discontinued.
