### ISSUE TITLE
Code Insights: Don't render an empty combobox when we do not render suggestions 

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#34044]
When we focus the repositories field we shouldn't render the reach ui Combobox panel below. 

<img width="941" alt="Screenshot 2022-04-19 at 14 17 54" src="https://user-images.githubusercontent.com/18492575/163983052-bf7beab2-a0c0-45fe-aa8e-e85aa689598d.png">

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
