### ISSUE TITLE
Prometheus metrics for language servers

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#3406]
Share Prometheus metrics for monitoring language servers.

Idea: just make grafana.sgdev.org public and read-only.

Requested by:
- https://app.hubspot.com/contacts/2762526/company/464956351

**Comment by slimsag** [comment]
@beyang To the extent that you are thinking of how to handle standard Prometheus metrics etc, and not just creating a dashboard or something, let's talk. I've filed an issue https://github.com/sourcegraph/sourcegraph/issues/3410 which outlines how I believe this will all work.

**Comment by beyang** [comment]
Closing this in favor of #3410

**Comment by slimsag** [comment]
We don't have standard / recent Grafana dashboards for language servers. Those need to be created on grafana.sgdev.org

#3410 is just about taking what exists and deploying it on customer grafana instances, basically.
