### ISSUE TITLE
[Accessibility Audit] Batch Changes: View the results of a previously executed batch spec on an open batch change (with server-side execution)

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#34084]
### Steps to replicate journey

Taken from the [user journey list document](https://docs.google.com/document/d/1XgG0udYL37G3RxuT5shizulpHgb6xVtY5L9kBeSkXYk/edit?usp=sharing). Use this for further context.

- Click “Batch Changes” in the top navigation bar
- Scan the list to find the open batch change
- Click the name of the batch change on the list item
- Click the “Executions” tab above the list of changesets
- Scan the list for the execution you wish to view
- Click the link named like “Executed by courier-new about 2 hours ago”
- The execution details overview for this batch spec will be visible

### How to audit

Follow the instructions here: [Auditing a user journey](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#auditing-a-user-journey)

**Note:** We are planning on arranging thorough third-party audit in the future, so our focus here is just to find the _majority_ of accessibility issues. Don't worry if you feel you haven't found 100% of potential issues, it is better to focus on the core essentials to complete the journey rather than spending lots of time going through every possible problem.

### How to raise discovered problems

Follow the instructions here: [Raising an accessibility bug](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#raising-a-bug)

### Any other questions?

See the [audit FAQ](https://docs.google.com/document/d/1nCi7TvYRpj9eG0_QtgqK1c4L28EiJKVuxyuvg1lAGgo/edit#) - add your question if it isn't there already!

**Comment by courier-new** [comment]
Will share some overlap with https://github.com/sourcegraph/sourcegraph/issues/34083.

**Comment by LawnGnome** [comment]
Opened #37908; otherwise complete.
