### ISSUE TITLE
[Accessibility Audit] Batch Changes: View previously executed batch specs for an open batch change (with server-side execution)

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#34083]
### Steps to replicate journey

Taken from the [user journey list document](https://docs.google.com/document/d/1XgG0udYL37G3RxuT5shizulpHgb6xVtY5L9kBeSkXYk/edit?usp=sharing). Use this for further context.

- Click “Batch Changes” in the top navigation bar
- Scan the list to find the open batch change
- Click the name of the batch change on the list item
- Click the “Executions” tab above the list of changesets
- The list of all executions on this batch change will be visible

### How to audit

Follow the instructions here: [Auditing a user journey](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#auditing-a-user-journey)

**Note:** We are planning on arranging thorough third-party audit in the future, so our focus here is just to find the _majority_ of accessibility issues. Don't worry if you feel you haven't found 100% of potential issues, it is better to focus on the core essentials to complete the journey rather than spending lots of time going through every possible problem.

### How to raise discovered problems

Follow the instructions here: [Raising an accessibility bug](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#raising-a-bug)

### Any other questions?

See the [audit FAQ](https://docs.google.com/document/d/1nCi7TvYRpj9eG0_QtgqK1c4L28EiJKVuxyuvg1lAGgo/edit#) - add your question if it isn't there already!

**Comment by courier-new** [comment]
Will share some overlap with https://github.com/sourcegraph/sourcegraph/issues/34094.

**Comment by LawnGnome** [comment]
Complete. I don't think there's any immediate action required — as with other audits, the issues at this point are mostly around base Wildcard components, such as the tabs not having obvious horizontal scroll indicators on small screens, or VoiceOver focus changing unpredictably when screen elements change.
