### ISSUE TITLE
[Accessibility Audit] Batch Changes: Apply a batch spec (aka apply the results in the preview to the batch change)

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#34080]
### Steps to replicate journey

Taken from the [user journey list document](https://docs.google.com/document/d/1XgG0udYL37G3RxuT5shizulpHgb6xVtY5L9kBeSkXYk/edit?usp=sharing). Use this for further context.

- Follow the workflow to preview the results of executing a batch spec (with server-side execution) OR follow the workflow to create and execute a batch spec
- Verify the changesets and publish statuses match your desired outcome
- Click the “Apply” button
- The updated batch change details will be visible

### How to audit

Follow the instructions here: [Auditing a user journey](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#auditing-a-user-journey)

**Note:** We are planning on arranging thorough third-party audit in the future, so our focus here is just to find the _majority_ of accessibility issues. Don't worry if you feel you haven't found 100% of potential issues, it is better to focus on the core essentials to complete the journey rather than spending lots of time going through every possible problem.

### How to raise discovered problems

Follow the instructions here: [Raising an accessibility bug](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#raising-a-bug)

**Comment by eseliger** [comment]
Audit done.
