### ISSUE TITLE
Upstream standard Prometheus+Grafana+Jaeger work to deploy-sourcegraph

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#3410]
deploy-sourcegraph-docker has a standard set of Prometheus metrics & Grafana dashboards that should be upstreamed to deploy-sourcegraph for other deployments.

We will have to maintain these two copies separately as there are subtle but critical differences between Prometheus metrics on Kubernetes and Docker deployments:

- Must select on `instance`, not `app` etc. Kubernetes tags.
- Prometheus service discovery in Docker deployment isn't done by k8s, so things are different.
- Other random differences.

Basically, our dashboards and prometheus metrics should be a defined standard that both deploy-sourcegraph and deploy-sourcegraph-docker implement independently.

Other things that deploy-sourcegraph-docker does that deploy-sourcegraph would benefit from include:

- Loading Grafana dashboards via provisioning options. This makes the dashboards non-savable via the UI and automatically loaded on start of a Sourcegraph cluster, so you basically just enter a password + press a button on Grafana and you have every Sourcegraph dashboard. The JSON for the dashboards is then committed, and we manage them for customers side by side with our regular versions.
- Jaeger docs are almost entirely broken in deploy-sourcegraph, multiple issues resolved in deploy-sourcegraph-docker.
- deploy-sourcegraph-docker uses a jaeger cassandra schema init container instead of requiring admin to explicitly run some scripts after cloning a repo (which we don't even document how to do today).
- deploy-sourcegraph-docker uses a newer version of Jaeger.
- other nice things I haven't remembered off the top of my head.

**Comment by keegancsmith** [comment]
We can update the prometheus config to rewrite the `instance` label to `app`.

**Comment by slimsag** [comment]
Oh, I didnt know prom could do that. How?

**Comment by keegancsmith** [comment]
https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/deploy-sourcegraph%24%40master+target_label

**Comment by slimsag** [comment]
This will slip 3.4 but can come shortly after.

**Comment by slimsag** [comment]
Given the above linked PRs, this has finally been completed.
