### ISSUE TITLE
StatusMessages is experiencing high response times

### ISSUE THREAD

**Issue by sanderginn** [sourcegraph/sourcegraph#34110]
### Description
The `StatusMessages` endpoint is causing response times that run into multiple seconds. Since this issue was first observed (25th of February), an upwards trend in response times is observable:

![Screen Shot 2022-04-19 at 6 07 15 PM](https://user-images.githubusercontent.com/2979513/164047930-2528fa8c-0692-431b-9bd1-0f955b263281.png)

[Relevant Slack thread](https://sourcegraph.slack.com/archives/C07KZF47K/p1648718206569109)

**Comment by ryanslade** [comment]
Potential fixes suggested [here](https://sourcegraph.com/notebooks/Tm90ZWJvb2s6OTAz) after some investigation by @tsenart

**Comment by ryanslade** [comment]
Still seeing some spikes on that dashboard, do we know whether we can close this issue?

**Comment by eseliger** [comment]
Fixed.
