### ISSUE TITLE
[Accessibility Audit] Cloud SaaS: Create a new organization

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#34118]
### Steps to replicate journey

Taken from the [user journey list document](https://docs.google.com/document/d/1h3bh6prxPX31aOiWkNsRCvXUbmtakaaj3Kn986uZYkc/edit?usp=sharing). Use this for further context.

Note: View the above document for a video walkthrough of this journey.

- Click on the button “Create organization” in the organization list page.
- Fill in the form for joining open beta.
  - This form collects some basic information about the customer, size of the company, which code host they use and why they want to use sourcegraph (see screenshot below)
- Click “Continue” button on the bottom right
- A form for organization creation is visible.
- Fill in the input for organization name. Organization ID is created automatically for you.
  - If there is already an existing organization with the same ID, the system generates a new ID and let’s the user edit it manually.
- Accept the terms of service by making sure the checkbox is checked
  - Without this step, it is impossible to continue with organization creation
- Click “Continue” button
- You should see a getting started page for the organization

### How to audit

Follow the instructions here: [Auditing a user journey](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#auditing-a-user-journey)

**Note:** We are planning on arranging thorough third-party audit in the future, so our focus here is just to find the _majority_ of accessibility issues. Don't worry if you feel you haven't found 100% of potential issues, it is better to focus on the core essentials to complete the journey rather than spending lots of time going through every possible problem.

### How to raise discovered problems

Follow the instructions here: [Raising an accessibility bug](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#raising-a-bug)

### Any other questions?

See the [audit FAQ](https://docs.google.com/document/d/1nCi7TvYRpj9eG0_QtgqK1c4L28EiJKVuxyuvg1lAGgo/edit#) - add your question if it isn't there already!

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam-and-admin-experience - the "team/iam-admin-experience" label was applied to this issue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.
