### ISSUE TITLE
[Accessibility Audit] Cloud SaaS: Add/Verify/Edit/Remove email

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#34115]
### Steps to replicate journey

Taken from the [user journey list document](https://docs.google.com/document/d/1h3bh6prxPX31aOiWkNsRCvXUbmtakaaj3Kn986uZYkc/edit?usp=sharing). Use this for further context.

To access the email page:

- Open the main sourcegraph page (sourcegraph.com) as a logged in user
- Click on the dropdown button on the top right, next to your profile picture
- A dropdown menu should appear, click on “Settings”
- A settings page should appear, click on “Emails”

Add additional email address to the account:

- Type a valid email into the input under “Add email address” label (if the email address is invalid, an error will be shown)
- Click on “Add” button
- The newly added email address should appear in the list of emails on the top of the page

Verify email:

- Add a new email using the steps above.
- Click on the “Verify account” link in the email or copy the link and follow it in the browser
- Once the verification link is visited by the same user account, the email is marked as verified in the list of emails.

Change primary email address:

- Click on the “Primary email address” dropdown
- Select a different email address
- Click on “Save” button

Remove email address:

- Click on the “Remove” link on the right side, next to each email address that can be deleted.

### How to audit

Follow the instructions here: [Auditing a user journey](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#auditing-a-user-journey)

**Note:** We are planning on arranging thorough third-party audit in the future, so our focus here is just to find the _majority_ of accessibility issues. Don't worry if you feel you haven't found 100% of potential issues, it is better to focus on the core essentials to complete the journey rather than spending lots of time going through every possible problem.

### How to raise discovered problems

Follow the instructions here: [Raising an accessibility bug](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#raising-a-bug)

### Any other questions?

See the [audit FAQ](https://docs.google.com/document/d/1nCi7TvYRpj9eG0_QtgqK1c4L28EiJKVuxyuvg1lAGgo/edit#) - add your question if it isn't there already!

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam-and-admin-experience - the "team/iam-admin-experience" label was applied to this issue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.
