### ISSUE TITLE
[Accessibility Audit] Cloud SaaS: Pending organization invitations

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#34128]
### Steps to replicate journey

Taken from the [user journey list document](https://docs.google.com/document/d/1h3bh6prxPX31aOiWkNsRCvXUbmtakaaj3Kn986uZYkc/edit?usp=sharing). Use this for further context.

List invitations:

- Open the main sourcegraph page (sourcegraph.com)
- Click on the dropdown button on the top right, next to your profile picture
- A dropdown menu should appear, click on “Your organizations”
- You should see a view with a list of organizations you are a member of
- Pick one which was not configured yet and hence is still showing the getting started page
- Go to “Members” tab on the top and then select “Pending invites” in the sidebar

Copy invitation link:

- Follow above steps to list invitations
- Click the cog button on the right from an invitation
- A dropdown with options should appear
- Click the “Copy invite link” option
- A confirmation dialog should appear saying that the link is copied in the clipboard

Resend invitation:

- Follow above steps to list invitations
- Click the cog button on the right from the invitation
- A dropdown with options should appear
- Click the “Resend invite” option
- A confirmation should appear above the list of pending invitations saying that the invitation was resent.

Revoke invitation:

- Go to pending invitations screen
- Click the cog button on the right from the invitation
- A dropdown with options should appear
- Click the “Revoke invite” option
- A confirmation dialog should appear. If confirmed, the invitation is revoked and it should not appear in the list anymore.
- There is also a confirmation above the list of pending invitations saying that the invitation was revoked.

### How to audit

Follow the instructions here: [Auditing a user journey](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#auditing-a-user-journey)

**Note:** We are planning on arranging thorough third-party audit in the future, so our focus here is just to find the _majority_ of accessibility issues. Don't worry if you feel you haven't found 100% of potential issues, it is better to focus on the core essentials to complete the journey rather than spending lots of time going through every possible problem.

### How to raise discovered problems

Follow the instructions here: [Raising an accessibility bug](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#raising-a-bug)

### Any other questions?

See the [audit FAQ](https://docs.google.com/document/d/1nCi7TvYRpj9eG0_QtgqK1c4L28EiJKVuxyuvg1lAGgo/edit#) - add your question if it isn't there already!

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam-and-admin-experience - the "team/iam-admin-experience" label was applied to this issue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.
