### ISSUE TITLE
Code monitoring logs throw an error if unauthenticated

### ISSUE THREAD

**Issue by muratsu** [sourcegraph/sourcegraph#34151]
#### Steps to reproduce:

1. When I try to visit the page as an unauthenticated user, I get an error page

https://user-images.githubusercontent.com/1308560/164104723-fa6a0a88-9996-482f-a708-ba468906b5c8.mp4

#### Expected behavior:
As a new user, I expect some information about this product before I create an account to try it out.

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by camdencheek** [comment]
Code monitors has been removed from dotcom, which is the only instance that allows unauthenticated access. Closing this as no longer relevant.
