### ISSUE TITLE
Show warnings for copy-paste extension config

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#3417]
https://app.hubspot.com/contacts/2762526/company/464956351   encountered issue where they naively copy-pasted extension settings from extension docs and didn't change the values. E.g., from https://sourcegraph.com/extensions/sourcegraph/go:
```
  "go.serverUrl": "ws://langserveruser:PASSWORD@host.docker.internal:7080/go",
  "go.sourcegraphUrl": "http://host.docker.internal:7080",
```

The settings editor should show an error/warning when the field value matches the default value (which should be changed).

**Comment by sd9** [comment]
This can be done by adding JSON Schema validations that the value doesn't contain the placeholder values. See https://sourcegraph.com/github.com/sourcegraph/sourcegraph@36591d9f1ff20bc37d97e16f8ef7286c2ee4fc36/-/blob/schema/bitbucket_server.schema.json#L28-31 for an example.

**Comment by sqs** [comment]
This can be done by adding JSON Schema validations that the value doesn't contain the placeholder values. See https://sourcegraph.com/github.com/sourcegraph/sourcegraph@36591d9f1ff20bc37d97e16f8ef7286c2ee4fc36/-/blob/schema/bitbucket_server.schema.json#L28-31 for an example.

**Comment by beyang** [comment]
Filed this as a follow-up: https://github.com/sourcegraph/sourcegraph/issues/3561. I found the docs pretty confusing myself.
