### ISSUE TITLE
JetBrains: Text input issues inside web view

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#34181]
We're currently having two major text input issues:

1. On Linux (Tested on x64) keyboard events have the wrong code set in the web view causing them not to be correctly applied. I observed that the key property is correct and modifiers are correct as well.
2. On Mac (Tested on AArch64) backspace is not sent to the web view. When used with a modified (e.g. cmd+backspace) the event is received.

## Next steps

- @philipp-spiess to create a reduced repro and create two tickets with JetBrains.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by philipp-spiess** [comment]
I prepared a minimal repro here: https://github.com/sourcegraph/sourcegraph-jetbrains/tree/ps/input-bug

**Comment by philipp-spiess** [comment]
Filed two JetBrains issues:
- https://youtrack.jetbrains.com/issue/JBR-4408/Inside-JCEF,-backspace-events-on-Mac-are-not-sent-to-the-web-vie
- https://youtrack.jetbrains.com/issue/JBR-4407/Inside-JCEF,-keyboard-events-on-Linux-have-the-wrong-code-set-an?s=Inside-JCEF,-keyboard-events-on-Linux-have-the-wrong-code-set-an

**Comment by philipp-spiess** [comment]
Update: I looked into various ways of working around this issue. One thing that I found particularly interresting: If we can intercept the events on the Java side, can we inject them into the web view manually?

Turns out that this works, albeit with a few caveats. Here's an example of the Mac issue with this hack applied:

https://user-images.githubusercontent.com/458591/164469306-1c0a45ee-c4a1-4d16-8b3a-930cced8a370.mov

The caveats:
- I can't proof this but it _feels like_ the backspace button was lagging a bit compared to the text input. Please note that this is very subjective and might be because I _assume_ I would notice a delay by this apporach.
- This exact hack _won't work_ for our search box out of the box. The reason is that we have to simulate a backspace event and in the case of the input field we have to manually alter the current text value to account for the deletion. Our web search box uses a content editable field and this might be a lot of headache to simulate potentially.
- If you hit a key and don't release it, the OS normally has a delay configured after which it presses this button repeatedly. E.g. if you want to delete a whole word, you can press backspace and don't release. We do not seem to get these native events forwarded to Java so we can only react to the first keystroke.

Overall this experience is very suboptimal and I want to urge as to not double down on this hack.

**Comment by philipp-spiess** [comment]
Thanks to @madppiper we have a fix for this issue now 🎉 

c.f. https://sourcegraph.slack.com/archives/C035WT8V856/p1650875969604069?thread_ts=1650542014.263549&cid=C035WT8V856
