### ISSUE TITLE
JetBrains: Set up JS build pipeline

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#34186]
Similar to the VSCE, we want a script (`yarn build`) to create the JavaScript dependencies for our JetBrains extension. 

A prototype of this already exists in [ps/jetbrains-demo](https://github.com/sourcegraph/sourcegraph/tree/ps/jetbrains-demo).

Ideally this comes with [esbuild support like #34010](https://github.com/sourcegraph/sourcegraph/pull/34010)

**Comment by tjkandala** [comment]
I'll let you know when I have the style plugin working for the VS Code extension, then it shouldn't be too much effort to get esbuild working with jetbrains!

**Comment by philipp-spiess** [comment]
@tjkandala Awesome, ty!

**Comment by tjkandala** [comment]
Here's a [rough draft](https://github.com/sourcegraph/sourcegraph/pull/34010/commits/653ea61f8428c138622e2ad01cada1912d245b66#diff-adf45bcfd7931fee649ddc29d8b72e1d4bf58cd375643b31485cc2c62d10982fR101) of what I needed to do to get esbuild working. It was just a simple module resolution issue, I'll refactor/cleanup tomorrow

**Comment by philipp-spiess** [comment]
I’m going to close this, there's more work in the future to migrate to `esbuild` and keep up the changes with VSCode but I'd rather create a new task for this as it is not blocking our current milestone. :)

**Comment by philipp-spiess** [comment]
Created #34571
