### ISSUE TITLE
[Accessibility Audit] Search: Making a search

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#34188]
### Use cases to replicate

Taken from the [user journey list document](https://docs.google.com/document/d/1IA90OFew5MTcxFndKS2Xn4vb8sOt68sj537P7AGj_Tk/edit?usp=sharing). Use this for further context.

Please take these following use cases and replicate them when running your audit.

Submit search:

- I can type a query in the search box and submit the search
- I can type a query in the search box, I can get suggestions for search filters, repositories, and other common search items. I can select these suggestions with either the keyboard or the mouse.
- I can distinguish between different types of search terms in the search box, including filters and boolean operators.

Additional search controls:

- I can use the toggles next to the search box to enable or disable case sensitivity, regex pattern matching, or structural search in my search.
- I can use the Copy Query button to copy the full contents of my query to the clipboard, including hidden parameters represented by the toggles and search context dropdown..

Utilizing search contexts:

- I can open the Search Contexts dropdown to view a list of all the contexts I have access to and click on one to change what search context I am searching through; I can open Sourcegraph later and my selected search context is preserved; I can click the "Reset" button on the dropdown to revert back to the default context.

### How to audit

Follow the instructions here: [Auditing a user journey](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#auditing-a-user-journey)

**Note:** We are planning on arranging thorough third-party audit in the future, so our focus here is just to find the _majority_ of accessibility issues. Don't worry if you feel you haven't found 100% of potential issues, it is better to focus on the core essentials to complete the journey rather than spending lots of time going through every possible problem.

### How to raise discovered problems

Follow the instructions here: [Raising an accessibility bug](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#raising-a-bug)

### Any other questions?

See the [audit FAQ](https://docs.google.com/document/d/1nCi7TvYRpj9eG0_QtgqK1c4L28EiJKVuxyuvg1lAGgo/edit#) - add your question if it isn't there already!

**Comment by limitedmage** [comment]
Completed with the following successor issues:
- https://github.com/sourcegraph/sourcegraph/issues/34720
- https://github.com/sourcegraph/sourcegraph/issues/34727
- https://github.com/sourcegraph/sourcegraph/issues/34732
- https://github.com/sourcegraph/sourcegraph/issues/34733
