### ISSUE TITLE
Browser extension code intel popup styles issue on GitHub

### ISSUE THREAD

**Issue by taras-yemets** [sourcegraph/sourcegraph#34184]
Code intel popup is rendered, but not visible on GitHub. Popup positioning has been changed on GitLab too. Inspecting other code hosts might also be needed.

| Code host | Expected | Actual |
| ------------- | --------- | ------ |
| GitHub | ![image](https://user-images.githubusercontent.com/25318659/164264766-26fa2924-74c7-4ea0-85dd-5e9135cd4ff2.png) | ![image](https://user-images.githubusercontent.com/25318659/164264372-388aeaf8-b625-4ebe-8f2b-4c72f9825a13.png) |
| GitLab | ![image](https://user-images.githubusercontent.com/25318659/164264656-7b00ef76-91c2-4243-af39-f52e118c7efb.png) | ![image](https://user-images.githubusercontent.com/25318659/164264124-502a009a-85d9-4efa-8bbf-26bcdc85766c.png) |

**Comment by taras-yemets** [comment]
@chrismwendt, could it be the side effect of https://github.com/sourcegraph/sourcegraph/pull/34028? I reverted this PR locally and this issue went away. [Percy build](https://percy.io/Sourcegraph/Sourcegraph/builds/17431721/changed/978125858?browser=chrome&browser_ids=23&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1920&widths=1920) in the PR pipeline reports this change: albeit code intel popup is visible on the GitHub snapshot, it's positioned a bit higher than it was before.

**Comment by chrismwendt** [comment]
Yes, I think #34028 broke the popover despite it working for me locally at sourcegraph.test. I also saw this problem [yesterday](https://sourcegraph.slack.com/archives/CHXHX7XAS/p1650445922594929). Reverting in https://github.com/sourcegraph/sourcegraph/pull/34206. Thanks for reporting 🙇

**Comment by chrismwendt** [comment]
The fix needs to get into 3.39 because the breaking change was merged prior to v3.39.0-rc.1 getting tagged.

@keegancsmith If you're handling the 3.39 release, could you cherry pick the revert?

The revert commit on main is: baba39941321305c5ab943290ddf94658b5b7ad1

**Comment by keegancsmith** [comment]
@chrismwendt ok I have cherry-picked, it will go out with the 3.39 release.
