### ISSUE TITLE
Code Insights: In some cases you can't hover over corner point on the line chart

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#34182]
I still don't have a clear repro for this problem but @coury-clark could manage to capture this in his insight 

![CleanShot 2022-04-19 at 11 17 38](https://user-images.githubusercontent.com/18492575/164252324-077772f1-cb25-4042-a03a-7f45420b34f3.gif)

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by chwarwick** [comment]
@vovakulikov I can reproduce locally if you need another look at it.

**Comment by Joelkw** [comment]
@vovakulikov I can reproduce this on k8s if you'd like to take a look. Take a look at this insight: you can't hover the datapoint for April unless you expand the size of the insight. https://k8s.sgdev.org/insights/dashboards/ZGFzaGJvYXJkOnsiSWRUeXBlIjoiY3VzdG9tIiwiQXJnIjo3MjcyNTJ9

**Comment by vovakulikov** [comment]
@coury-clark @Joelkw thanks a lot! After playing with different data sets locally I also could manage to repro this. But good to have a prod ready data shape example to test a fix for it, thanks

**Comment by Joelkw** [comment]
Thanks @vovakulikov ! I'd like to try to fix this by the next release (if this is a small issue) – since you glanced at it already, do you have a sense of the quick points estimate and could you enter that in if so?

**Comment by vovakulikov** [comment]
@Joelkw I found a problem but this, unfortunately, doesn't mean in this case that I know the exact solution for it.

In the nutshell, we should come up with a better point area distribution algorithm to avoid this problem. At the moment we use the Voronoi algorithm to bound the cursor position and the closes point position. 

So to fix this we should rewrite it or contribute to visx Voronoi helper function to fix it. I will discuss this with @unclejustin next week and will update this issue then accordingly with our thoughts on this.

**Comment by unclejustin** [comment]
I'm wondering if we can't "cheat" this by adding padding around the chart area. @vovakulikov do you know if that's possible? Can we render all the points farther from the edge?

**Comment by vovakulikov** [comment]
Interesting idea @unclejustin, I think we have control over it. I will try to experiment around this this week.

**Comment by Joelkw** [comment]
#35163 is even more important, but we should target both.
