### ISSUE TITLE
[Accessibility Audit] Search: (Authenticated) Search homepage

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#34189]
### Use cases to replicate

Taken from the [user journey list document](https://docs.google.com/document/d/1IA90OFew5MTcxFndKS2Xn4vb8sOt68sj537P7AGj_Tk/edit?usp=sharing). Use this for further context.

Please take these following use cases and replicate them when running your audit.

- As an authenticated user, I can load the search homepage and see my recent activity, including recently searched repositories, recent search queries, and recently viewed files. I can click on any of these to execute the search or open the file.
- As an authenticated user on Sourcegraph Server, I can open the search homepage and see saved searches. I can toggle between viewing only my saved searches and all saved searches I have access to. I can click on any saved search to execute it.
- As an authenticated user on Sourcegraph Cloud, I can open the search homepage and see all the community search contexts available on Sourcegraph Cloud. I can click on any of them to navigate to a tailored search homepage for that community.

### How to audit

Follow the instructions here: [Auditing a user journey](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#auditing-a-user-journey)

**Note:** We are planning on arranging thorough third-party audit in the future, so our focus here is just to find the _majority_ of accessibility issues. Don't worry if you feel you haven't found 100% of potential issues, it is better to focus on the core essentials to complete the journey rather than spending lots of time going through every possible problem.

### How to raise discovered problems

Follow the instructions here: [Raising an accessibility bug](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#raising-a-bug)

### Any other questions?

See the [audit FAQ](https://docs.google.com/document/d/1nCi7TvYRpj9eG0_QtgqK1c4L28EiJKVuxyuvg1lAGgo/edit#) - add your question if it isn't there already!

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by limitedmage** [comment]
Completed with the followup issues:
- https://github.com/sourcegraph/sourcegraph/issues/34721
- https://github.com/sourcegraph/sourcegraph/issues/34727
- https://github.com/sourcegraph/sourcegraph/issues/34734
- https://github.com/sourcegraph/sourcegraph/issues/34735
