### ISSUE TITLE
JetBrains: Merge sourcegraph-jetbrains into our monorepo

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#34185]
We are going to use web views for the next version of the JetBrains extension. For that, we want to reference components from web and VSCE. To make development easier, we're going to move the work to our monorepo.

c.f. #33777

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
