### ISSUE TITLE
[Accessibility Audit] Search: Code Monitoring - Getting started

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#34193]
### Use cases to replicate

Taken from the [user journey list document](https://docs.google.com/document/d/1IA90OFew5MTcxFndKS2Xn4vb8sOt68sj537P7AGj_Tk/edit?usp=sharing). Use this for further context.

Please take these following use cases and replicate them when running your audit.

- On the getting started page, I can use the button that says “Create code monitor” to create a new code monitor. This goes to the create code monitor flow.
- On the getting started page, I can click on “create copy of monitor” on the example code monitors cards in order to create a copy of the code monitor in my code monitors. There are a variety of examples that I can use.

### How to audit

Follow the instructions here: [Auditing a user journey](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#auditing-a-user-journey)

**Note:** We are planning on arranging thorough third-party audit in the future, so our focus here is just to find the _majority_ of accessibility issues. Don't worry if you feel you haven't found 100% of potential issues, it is better to focus on the core essentials to complete the journey rather than spending lots of time going through every possible problem.

### How to raise discovered problems

Follow the instructions here: [Raising an accessibility bug](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#raising-a-bug)

### Any other questions?

See the [audit FAQ](https://docs.google.com/document/d/1nCi7TvYRpj9eG0_QtgqK1c4L28EiJKVuxyuvg1lAGgo/edit#) - add your question if it isn't there already!

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by limitedmage** [comment]
@almeidapaulooliveira if this audit is complete, please close this issue and list any follow-up work items. Thank you!

**Comment by almeidapaulooliveira** [comment]
I opened an issue (##35148) from this audit.
