### ISSUE TITLE
[Accessibility Audit] Search: Notepad

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#34198]
### Use cases to replicate

Taken from the [user journey list document](https://docs.google.com/document/d/1IA90OFew5MTcxFndKS2Xn4vb8sOt68sj537P7AGj_Tk/edit?usp=sharing). Use this for further context.

Please take these following use cases and replicate them when running your audit.

Perquisite: The notepad is enabled in settings

- When I run a search:
  - I see the notepad component in the bottom right corner of the screen
  - I can add a search to the notepad by clicking the “+ search” button in the notepad
    - When I add a search I can optionally add an annotation related to it
  - When I view a file:
    - I can add a file to the notepad by clicking the “+ file” button in the notepad
      - When I add a file I can optionally add an annotation related to it
    - If one or more lines are selected, I can add a file range to the notepad by clicking the “+ range” button in the notepad
      - When I add a range I can optionally add an annotation to it
  - I can delete an item added to the notepad by clicking the “x” icon in the item component
  - I can add/edit the annotation on an item by clicking the “note” icon in the item component
  - When a notepad item is selected, I can delete it from the keyboard with Cmd/Meta + Backspace
- I can delete all items in the notepad by clicking the “trash can” icon and confirming that I want to delete all items when the confirmation message pops up
- I can create a Notebook from items in the notepad by clicking the “Create Notebook” button
- I can select one or more individual notepad items by Cmd/Meta + right clicking on them
- I can select a range of notepad items by clicking on one notepad item and then holding Shift while clicking on subsequent item that is above or below the currently selected item
- I can collapse the annotation box of any item by clicking the “note” icon in the item header
- I can select the next/previous item with the up and down arrow keys

### How to audit

Follow the instructions here: [Auditing a user journey](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#auditing-a-user-journey)

**Note:** We are planning on arranging thorough third-party audit in the future, so our focus here is just to find the _majority_ of accessibility issues. Don't worry if you feel you haven't found 100% of potential issues, it is better to focus on the core essentials to complete the journey rather than spending lots of time going through every possible problem.

### How to raise discovered problems

Follow the instructions here: [Raising an accessibility bug](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#raising-a-bug)

### Any other questions?

See the [audit FAQ](https://docs.google.com/document/d/1nCi7TvYRpj9eG0_QtgqK1c4L28EiJKVuxyuvg1lAGgo/edit#) - add your question if it isn't there already!

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by limitedmage** [comment]
@fkling  Is this audit complete? If yes, can you list the successor work items and close this issue? If not, can you finish it or give me a list of stories and audit types to still be done so I can finish the audit? Thanks!

**Comment by limitedmage** [comment]
Audit complete.
