### ISSUE TITLE
[Accessibility Audit] Search: Search results

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#34190]
### Use cases to replicate

Taken from the [user journey list document](https://docs.google.com/document/d/1IA90OFew5MTcxFndKS2Xn4vb8sOt68sj537P7AGj_Tk/edit?usp=sharing). Use this for further context.

Please take these following use cases and replicate them when running your audit.

After executing a search:

- I can see search results as they come in; I don't have to wait for the search to complete to start seeing results.
- I can view search progress, the number of results, and any errors, warnings or information on skipped results.
- I can click a button to start the creation of a new search context, code monitor, or saved search based on my query.
- For all results, I can see the result type (file, path, symbo, repository, diff, or commit message), repository name, code host, stars, and the last time that repository was synced with Sourcegraph. I can click on the repo name to go to that repo's page.
- For file, path, and symbol results, I can see the file's path. I can click on the file path to go to that file's page.
- For file results, I can see the number of content matches and a snippet of the content matches. If too many content matches exist for the file, only a portion of them will be shown; I can click a button to show all of them and revert back; I can also click a button to expand/contract all snippets for all results. I can click on any snippet to go to the file's page on the snippet locations. I can select text in the snippet and copy it to the clipboard with either the context menu or the keyboard.
- For symbol results, I can see the number of matches for the file and the list of matches with the symbol's type and name. I can click on a symbol to go to the file's page on the symbol's location.
- For repository results, I can see the repository's description from its code host.
- For diff and commit message results, I can see the author, commit title, commit short hash, and relative timestamp and I can click on any of these to go to the commit's page. I can see snippets that match the search and I can click on these to go to the commit's page.
- For diff results, I can see in the snippets which file they were found in and if it is an add or remove change.
- I can use the search sidebar to modify my search:
  - To only find specific types of results; for example, repositories or commit messages.
  - To add filters suggested based on the results of my search; for example, filter by one of the different programming languages in the results.
  - To add a repository filter based on the results of my search.
  - To add any filter or search operator; if I don't know what each filter does, I can easily learn it by viewing a short description.
  - To add a custom search snippet I have defined in my settings.
- If I have no results or have an error in my search, I can get helps and hints on how to modify my search to fix any issues and help find what I’m looking for.

### How to audit

Follow the instructions here: [Auditing a user journey](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#auditing-a-user-journey)

**Note:** We are planning on arranging thorough third-party audit in the future, so our focus here is just to find the _majority_ of accessibility issues. Don't worry if you feel you haven't found 100% of potential issues, it is better to focus on the core essentials to complete the journey rather than spending lots of time going through every possible problem.

### How to raise discovered problems

Follow the instructions here: [Raising an accessibility bug](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#raising-a-bug)

### Any other questions?

See the [audit FAQ](https://docs.google.com/document/d/1nCi7TvYRpj9eG0_QtgqK1c4L28EiJKVuxyuvg1lAGgo/edit#) - add your question if it isn't there already!

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by limitedmage** [comment]
Audit completed with the following successor issue:
- https://github.com/sourcegraph/sourcegraph/issues/34722
- https://github.com/sourcegraph/sourcegraph/issues/34723
- https://github.com/sourcegraph/sourcegraph/issues/34724
- https://github.com/sourcegraph/sourcegraph/issues/34728
- https://github.com/sourcegraph/sourcegraph/issues/34737
- https://github.com/sourcegraph/sourcegraph/issues/34738
