### ISSUE TITLE
VSCE: implement nightly builds

### ISSUE THREAD

**Issue by tjkandala** [sourcegraph/sourcegraph#34205]
See #34135 for our desired end-state for VS Code extension integration testing. 

We want nightly builds similar to what we have for the [browser extension](https://sourcegraph.com/-/editor?remote_url=git@github.com:sourcegraph/sourcegraph.git&branch=tjk/vsce-integration&file=dev/ci/runtype/runtype.go&editor=VSCode&version=2.2.0&start_row=20&start_col=50&end_row=20&end_col=50&utm_campaign=vscode-extension&utm_medium=direct_traffic&utm_source=vscode-extension&utm_content=vsce-commands). Ideally, we will be alerted in a Slack channel when the nightly build fails.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by tjkandala** [comment]
@abeatrix I'm assigning this to you because it'll be interesting (a bit outside what we normally do), don't worry about prioritizing it until the integration tests have been merged to `main`

**Comment by abeatrix** [comment]
https://sourcegraph.com/github.com/sourcegraph/sourcegraph@tjk/vsce-integration/-/blob/enterprise/dev/ci/internal/ci/pipeline.go?L133:15

**Comment by tjkandala** [comment]
Thought: we should use a fixed version of VS Code (optional argument [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/vscode/tests/vsce.test.ts?L16)) for client PR tests for stability, and use the latest version for nightly tests to check if VS Code updates have broken the extension

**Comment by abeatrix** [comment]
@tjkandala I'm not sure what i'm doing yet but I've pushed what I've done so far to the [bee/vsce-nightly](https://github.com/sourcegraph/sourcegraph/commit/afe0fe66e70035f86e607054502ff01523e59e7c) branch.

Am I on the right track lol ?

**Comment by tjkandala** [comment]
@abeatrix it looks like you're on the right track!

**Comment by tjkandala** [comment]
I'm not sure how we would get the tests to actually run nightly though, it may be in code or in the Buildkite UI? Could be helpful to check with Taras since he has experience with the browser extension nightly tests

**Comment by abeatrix** [comment]
> I'm not sure how we would get the tests to actually run nightly though, it may be in code or in the Buildkite UI? Could be helpful to check with Taras since he has experience with the browser extension nightly tests

Yea I've scheduled a pairing session with him next week when he's back from his time off on Wednesday, will keep you posted!

**Comment by abeatrix** [comment]
Note: I found [this from Slack ](https://sourcegraph.slack.com/archives/C01N83PS4TU/p1649153350283829) where it says we can do it by adding cron-like schedules to an existing pipeline.

**Comment by abeatrix** [comment]
PR: https://github.com/sourcegraph/sourcegraph/pull/34522
Test build: https://buildkite.com/sourcegraph/sourcegraph/builds/144406#f339da56-29ac-4146-8dfa-7eec8a19a0d1

**Comment by abeatrix** [comment]
The nightly build was added to the main pipeline and is running daily as expected:
![image](https://user-images.githubusercontent.com/68532117/166982258-60bfff3a-75c2-42de-a376-1d580c468e0e.png)
