### ISSUE TITLE
VSCE Bug: Misleading errors displayed when the extension is loaded for the first time

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#34207]
- **Sourcegraph version:** 3.38.1
- **Platform information:** VS Code Extension 2.2.1

#### Steps to reproduce:

1. Load the extension for the first time (For example, try freshly installing the extension on github.dev)
2. Receive errors about version number not supported AND cannot determine instance version number

#### Expected behavior:
The extension should load without any errors if connected to a supported instance. 

#### Actual behavior:
Errors about version number pop up when loading the extension for the first time
![image](https://user-images.githubusercontent.com/68532117/164281727-82d6c050-0524-47d6-aef2-458109961dbf.png)

If would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are not [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by abeatrix** [comment]
Fix is included in the v2.2.2 release
