### ISSUE TITLE
Notebooks jump cursor to end of markdown block after pressing enter/return

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#34216]
As in description. Add markdown block. Put the cursor anywhere but not at the end. type stuff. press enter. type stuff. the cursor jumped to the end

https://user-images.githubusercontent.com/888624/164295092-98835669-14e0-4d83-9175-67921aebb19e.mp4

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by benvenker** [comment]
@fkling I added you as an assignee here since this seems like it could be related to the CodeMirror change. Also, while you're in there would it be possible to make the cursor white?
