### ISSUE TITLE
insights: delete insight title contains stray characters 

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#34219]
Title in modal for deleting an insight contains stray characters.

<img width="621" alt="Screen Shot 2022-04-20 at 3 03 01 PM" src="https://user-images.githubusercontent.com/6098507/164303963-f8e05142-2995-453e-a294-4afff7e133af.png">

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
