### ISSUE TITLE
Refactor search result components

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#34236]
Our search result components have some [technical debt](https://github.com/sourcegraph/sourcegraph/pull/31146#discussion_r807212130) that needs to be fixed.

- [ ] Split `SearchResult` into `RepoSearchResult` and `CommitSearchResult` components
- [ ] Rename `FileMatch` to `FileSearchResult`
- [ ] (Possibly) Factor out any common UI between `RepoSearchResult`, `CommitSearchResult`, and `FileSearchResult` into a new `SearchResult` component

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.
