### ISSUE TITLE
Complete search homepage panels suggestions RFC

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#34235]
The [RFC](https://docs.google.com/document/d/1nSIuv5a6kRMAiSHHbZFLkmaFButZupwz_y3IM--NFLw/edit#) needs to be fleshed out to include the proposed solution.

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.
