### ISSUE TITLE
insights: return errors in compute stream

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#34230]
For Code Insights to utilize the compute stream with GraphQL parity we will need to consume errors from the search or match. [Currently these are not propagated in the compute stream.](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/internal/compute/streaming/compute.go?L45)

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by coury-clark** [comment]
From @rvantonder 
> I have a branch somewhere that propagates errors so that should be mostly solved.
...
> so yeah I'm actively aware but not working on them immediately.

We can take on this work since it's actively involved in our roadmap to move to this streaming API. @rvantonder do you think you could dig up that branch mentioned above?

**Comment by rvantonder** [comment]
> I have a branch somewhere that propagates errors so that should be mostly solved.

So I went back and found this branch, it does basically nothing unfortunately. The good news is I believe hard search errors _are_ being propagated. Here's guidance:

- The search stream backend generates error and alert events here: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@21f25fe73c5c30ee8f9840e76d39fb9d0a8a9564/-/blob/cmd/frontend/internal/search/search.go?L229-250&subtree=true

- The compute stream backend is a fork of the above, which removed a bunch of stuff (for good reasons) that don't apply to compute. One thing not done is propagating [compute errors](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/internal/compute/streaming/compute.go?L44). Search errors _are_ [propagated on the events channel](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/internal/compute/streaming/compute.go?L71-77) (and compute errors are not yet). These errors will only tell you if the query is invalid, basically. Maybe you don't care about them.

- Hard search errors _are_ propagated on that channel, so it looks like I preserved that: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/internal/compute/streaming/stream.go?L114-117. Alerts are _not_ generated or propagated, if this seems like something that could matter, have a look at the search stream code. I don't have a good answer on what the set of hard errors and alerts are, that are possible. 

So maybe this is in better shape to unblock the Code Insights change than I thought. Don't know if there's a good way to test.


Sorry for delayed reply, I got back from vacay this week

**Comment by rvantonder** [comment]
![Screen Shot 2022-04-28 at 4 28 42 PM](https://user-images.githubusercontent.com/888624/165863658-e00ae181-d19a-4f9f-9eab-2124c35a8c04.png)

**Comment by rvantonder** [comment]
When I mentioned:

> Alerts are not generated or propagated, if this seems like something that could matter, have a look at the search stream code.

I was referring to the search stream code linked earlier in that comment, this: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@21f25fe73c5c30ee8f9840e76d39fb9d0a8a9564/-/blob/cmd/frontend/internal/search/search.go?L229-250&subtree=true
