### ISSUE TITLE
Move noisy internal rate limit logs to metrics

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#34249]
We log whenever client requests are [delayed by our internal rate limiter](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+request+delayed+longer+than+expected+due+to+rate+limit&patternType=literal).

These can become very noisy. Instead, we should record the wait times in a histogram and provide dashboards to monitor 
this.

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.

**Comment by mike-r-mclaughlin** [comment]
[Customer](https://github.com/sourcegraph/accounts/issues/3) is running into this.  See [internal slack conversation](https://sourcegraph.slack.com/archives/C022SPMNR0W/p1650487579563249).

**Comment by ryanslade** [comment]
Closed by https://github.com/sourcegraph/sourcegraph/pull/35857
