### ISSUE TITLE
JetBrains: Focus entering and leaving the web view (with keyboard)

### ISSUE THREAD

**Issue by muratsu** [sourcegraph/sourcegraph#34245]
/cc @muratsu @jjinnii @ryankscott

**Comment by malomarrec** [comment]
Hey @muratsu, this issue didn't have a team label. Given you created it, I assigned you and added your team label. Feel free to unassign yourself. If this is not the right label, can you make sure to add the right one?

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @a-bergevin - the "team/growth" label was applied to this issue.
