### ISSUE TITLE
Charts: [LineChart] remove double sorting calls in points and lines render function 

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#34250]
Follow up for https://github.com/sourcegraph/sourcegraph/pull/33820

At the moment we render points and lines separately and therefore we have to sort this separately as well since we want to have a synthetic z-index over SVG elements (see original issue https://github.com/sourcegraph/sourcegraph/pull/33820). 

We should render points and lines together to be able to sort only lines and render points in the same group with lines to avoid over sorting at line chart render methods, this is important because this might lead us to possible performance problems

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
