### ISSUE TITLE
Research and create a signup/registration flow diagrams for cloud/on-prem/oss modes

### ISSUE THREAD

**Issue by erzhtor** [sourcegraph/sourcegraph#34254]
> @[erzhan.torokulov@sourcegraph.com](mailto:erzhan.torokulov@sourcegraph.com) The scope here is probably just to tackle the new website visitor - > registration flow, but I want to make sure I also understand how new paid users are added to existing accounts. So...
>
> Can you also make sure the figma diagrams cover how new users are generated on existing paid accounts. If an account has 100 users and adds 10 more licenses - how do those users get:
> 1) Created on the back end when an admin adds them
> 2) Notified of their access
> 3) Set up login credentials - is this already set up by admin through SSO or is there also a need for some users to create passwords after they've been invited?

> Create a flow of current signup flow and desired with email validation flow

> Notes on data being shared (with other systems & also events sent to Amplitude/Looker) and the process behind each step

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @a-bergevin - the "team/growth" label was applied to this issue.

**Comment by a-bergevin** [comment]
Another path people approach installation from is extensions. In VS code if you don't have an access token you are prompted to "create account" which takes you to this page: https://sourcegraph.com/sign-up?editor=vscode&utm_content=sign-up

**Comment by erzhtor** [comment]
Sharing a [link to diagrams](https://www.figma.com/file/iikQoAAxnFoTH3PNwwCvTX/Sourcegraph-Email-Sign-Up-Flow?node-id=0%3A1) that we've prepared together with Naman. @a-bergevin, @muratsu, please, let us know if you have questions/feedback.
