### ISSUE TITLE
SSBC: Record brief demonstration video for running batch changes server-side

### ISSUE THREAD

**Issue by courier-new** [sourcegraph/sourcegraph#34251]
Video should be inserted into the modal with information about setting up server-side batch changes: [Figma](https://www.figma.com/file/cTKjwbvWqU6xAykZmCTTqy/SSBC?node-id=2080%3A67527).

- A video is better than a GIF and can just be made to look like a GIF, like the [video at the top of the getting started page](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/enterprise/batches/list/GettingStarted.tsx?L19%3A21-37%3A29=) that just plays automatically and doesn't have any sound
- Video should roughly follow this script:
  - Pick a relevant example batch spec from examples repo, or from recent memory, and prepare at least 5 repositories across different code hosts that are indexed by your instance and that would be affected by the batch spec
  - Start from SSBC editor, with batch spec already pasted, but remove the last command from the steps
  - Start recording
  - Retype last command from the steps
  - Change at least one execution option
  - Preview workspaces
  - Execute spec
  - Select a workspace
  - Expand the logs as it's processing
  - Focus on the changeset diff once it finishes
  - Select another workspace and pretend to review the diff
  - Go to the preview
  - Select all changesets and change action to "Publish as Draft"
  - Click "Apply"
  - Wait for changesets to finish processing
  - Stop recording
  - If that's too long, you can cut out the parts where it's loading in post 😉
- Video should be prepared as both an mp4 and webm
  - The mp4 file for the video should be < 5MB
  - The webm file for the video should be < 1MB
- The video files should be uploaded to our GCP storage bucket, under `sourcegraph-assets/batch-changes` (where the getting started video also is)

**Comment by malomarrec** [comment]
@adeola-ak how's this coming along? Any help needed?

**Comment by malomarrec** [comment]
How's the video going? Can I help?
