### ISSUE TITLE
Preprod application tests: code-intel

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#34278]
In the context of the preprod effort, we're looking to list the scenarios that would leverage the fact that the preprod is running multiple instances of gitserver / indexserver, as opposed to what we're testing in CI. 

--- 

[Slack discussion](https://sourcegraph.slack.com/archives/CHXHX7XAS/p1650383216829859) and [scratch-pad](https://docs.google.com/document/d/1XPF6mEvd2Uo9IxQLTAINHQwYW8cpRuQQm4KgEzJMbHA/edit#). 

The code-intel team reported that running the codeintel-qa test suite over the preprod would hit multiple gitservers concurrently, which is not currently exercised in CI. 

DoD: adapted codeintel-qa tests are running against the preprod. 

- [ ] #34900

**Comment by bobheadxi** [comment]
@jhchabran here is an overview: https://sourcegraph.com/notebooks/Tm90ZWJvb2s6NzMz

Looks easy enough to set up and run!

**Comment by jhchabran** [comment]
https://github.com/sourcegraph/deploy-sourcegraph-cloud/pull/16301

**Comment by jhchabran** [comment]
We found out thanks to @efritz that the tests were failing because the auto-index is enabled on preprod whereas for now, the test suite expects it to be disabled.
