### ISSUE TITLE
Preprod application tests: repo-management

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#34280]
In the context of the preprod effort, we're looking to list the scenarios that would leverage the fact that the preprod is running multiple instances of gitserver / indexserver, as opposed to what we're testing in CI.

--- 

[Slack](https://sourcegraph.slack.com/archives/C02EDAQAJQZ/p1650383138542569) and [scratch-pad](https://docs.google.com/document/d/1XPF6mEvd2Uo9IxQLTAINHQwYW8cpRuQQm4KgEzJMbHA/edit#)

Proposed scenario by @asdine: 

1. On a new user, add multiple code hosts (totaling about 200 repositories).
2. Sync.
3. Wait until the repositories' status is marked as completed. 
4. Perform a search on content that should surface from these repositories. 
5. (Totally hypothetic, but still mentioning it) Kill a gitserver and expect to find missing search results, to ensure that the sharding is working. 

## Plan 

- [ ] @jhchabran Write some GQL tests similar to the backend integrations ones.

**Comment by ryanslade** [comment]
For step 4 we'd also need to wait for the code to be indexed or we can try and force a non-indexed search. 

An indexed search will be closer to what we want to test in prod though, it just means we'll have to wait a longer and that we're also testing zoekt.

**Comment by ryanslade** [comment]
We could also confirm that you can browse to one of the synced repos and see repo content.

**Comment by jhchabran** [comment]
@ryanslade how wait are we talking about here? I suppose that if downscale the amount of repo we index, we'd obviously get faster timings, so we could probably work around that.

**Comment by varsanojidan** [comment]
Would it also make sense to capture some permissions syncing in this end-end test? Have some of the clone repos prohibit access to the user, maybe even prohibit access based on branches/sub-repo permissions and validate that the user cant navigate to them even though they are cloned?

**Comment by ryanslade** [comment]
@jhchabran We have to wait for two things:

1. Zoekt needs to poll to find out that there is a new repo to index
2. The repos needs to be indexed

I'm actually not sure about the timings on these, but someone in search-core should know.

**Comment by ryanslade** [comment]
> @asdine @ryanslade Would it also make sense to capture some permissions syncing in this end-end test? Have some of the cloned repos prohibit access to the user, maybe even prohibit access based on branches/sub-repo permissions and validate that the user cant navigate to them even though they are cloned?

Yep, I think we probably want to at least check normal permissions syncing. I wouldn't worry about sub-repo permissions yet since they're not widely used yet.
