### ISSUE TITLE
Show all dependencies (of a repository, directory, globally, etc.)

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#3428]
As a dev manager, I would like to see all dependencies (such as npm packages) used by all repositories. I would also like to be able to slice this by repository, tree, or some combination of those (eg multiple repositories).

Customers:

- https://app.hubspot.com/contacts/2762526/company/726905220

**Comment by wimo7083** [comment]
This is a functionality I would really love.  Is there an ETA for this?

**Comment by christinaforney** [comment]
Hi @wimo7083 - thanks for letting us know this would be useful to you! I'll revisit with the team and see how it fits with our current priorities.

**Comment by macraig** [comment]
Feature request is now being tracked in [Productboard](https://sourcegraph.productboard.com/feature-board/1825051-code-intel/features/8155415/detail). The issue will be reopened when the feature is on the roadmap and implementation starts.
