### ISSUE TITLE
insights: Add API support for live preview of insights with multiple series

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#34290]
Currently the server side insight live preview only supports capture group insights.  These are defined as a single series which is then expanded into multiple series based on the values returned from the capture group.  To support live preview for non-capture group insights the resolver must be able to accept multiple series definitions.  [See resolver here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/insights/resolvers/live_preview_resolvers.go?L15:20)

**Comment by Joelkw** [comment]
@chwarwick from slack: 
> We could leave the live preview to run via the webapp but update all the “created” just in time insights to use the API, but to be able to remove all the UI code we need to complete this live preview issue.

**Comment by chwarwick** [comment]
Originally I was thinking that I needed to make a new field that could take an array of the preview arguments:
```graphql
insightLivePreview(input: [SearchInsightLivePreviewInput!]!): [SearchInsightLivePreviewSeries!]!
```
This aligns with what the UI is currently doing to preview search insights.  Once I started on this I'm not sure this is the best way to handle this because when going though the creation UI a single series is created at a time which then triggers the preview for all series to be recaptured.

An alternative would be that I could remove the restriction in the current `searchInsightLivePreview` that only allows capture group insights.  The impact would be that the UI would need to keep track of the preview for each series.   The benefit would be that on each change we would only need to update the preview for the impacted series instead of all of them.  

@sourcegraph/code-insights-frontend  do you have any thoughts or preference on approach?

**Comment by chwarwick** [comment]
Modified the signature of the new preview mentioned about, https://github.com/sourcegraph/sourcegraph/pull/34925 is a draft showing the example of supporting multiple series in 1 preview request.

**Comment by vovakulikov** [comment]
@chwarwick I see your points around fetching data for only changed parts of the insight (only changed series). Unfortunately, I don't think we have time in the near future to change this conception on the frontend. All our abstractions are groped around insight as to the main entity and not around series (line).

I like this approach with series granularity though, this is what we definitely should de in the long horizon I believe but it requires a lot of time to make it in the right way on the frontend cc @unclejustin

**Comment by vovakulikov** [comment]
@chwarwick just want to add that for the edit UI we could have more than just one series for the insight at the very beginning of the page load. In this case with series granularity level would we have multiple GQL queries at once? 

With your suggested API, we could form requests with multiple series as an input and therefore avoid having multi requests. 

After updating some particular series on the frontend we could understand what exactly series/line has been changed and run `insightLivePreview` only for this changed series and merge the result with other series on the frontend. 

The same thing works for the creation UI. 

As I see this we also could move iteratively with this approach and for the first version on the frontend always send all series regardless of what series has been changed and add smart merging logic later. 

cc @unclejustin

**Comment by chwarwick** [comment]
@vovakulikov  That was my concern when I looked at the ui code it looked like it would be a large effort to cut over to thinking about it as previewing a series and stacking them on top of each other.  I think for now I'll add this new preview that can handle multiple series in addition to the existing one and then over time, probably as we work on the unifying insights we can look at it again.
