### ISSUE TITLE
MI O11Y: Tracking issue

### ISSUE THREAD

**Issue by michaellzc** [sourcegraph/sourcegraph#34306]
### Plan

Tracking issue for [RFC XXX Review: Improve managed instances observability](https://docs.google.com/document/d/15FFluIuZEyJ-ahdAmcuFND3HQAM1meOL5ugLqkGK3gU/edit#heading=h.8tr9za1nr44v)

### Tracked issues

@michaellzc

- [ ] https://github.com/sourcegraph/sourcegraph/issues/33437 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/33438 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/cloud-devops - the "team/devops" label was applied to this issue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @RafLeszczynski - the "team/cloud" label was applied to this issue.

**Comment by RafLeszczynski** [comment]
@sourcegraph/cloud do we still want to do this and if yes when would be the right to do it and as part of what initiative?
