### ISSUE TITLE
deploy-sourcegraph-docker test failures don't report as CI failures

### ISSUE THREAD

**Issue by caugustus-sourcegraph** [sourcegraph/sourcegraph#34305]
https://buildkite.com/sourcegraph/deploy-sourcegraph-docker/builds/10580#a2fce70f-215f-4762-bb67-5d37c428e5fd

Both the docker-compose-test and pure-docker-test runs here failed due to errors, but the build was marked as a success.

**Comment by sourcegraph-bot-2** [comment]
Heads up @caugustus-sourcegraph @kevinwojo @michaellzc - the "team/delivery" label was applied to this issue.

**Comment by caugustus-sourcegraph** [comment]
Related: https://github.com/sourcegraph/sourcegraph/issues/35968
