### ISSUE TITLE
Maximum transaction duration graph is misleading

### ISSUE THREAD

**Issue by michaellzc** [sourcegraph/sourcegraph#34317]
I was looking into the maximum transaction duration alert on a MI instance

![CleanShot 2022-04-21 at 19 22 50](https://user-images.githubusercontent.com/8373004/164583860-9d0c230c-663a-4cd4-8e04-4ee34e5e8c3c.png)

The graph only shows graph by `datname` and failed to consider the fact that db name is identical across the built-in `pgsql` and `codeintel-db`

For this MI, it was `codeintel-db` has a few long-running transactions instead of pgsql. I look really hard into pgsql until I realized the metrics were messed up.

maybe we should `max by (datname, job)` instead?

![CleanShot 2022-04-21 at 19 26 54](https://user-images.githubusercontent.com/8373004/164584231-2f8c2eec-d662-42f5-86ab-348a15518d11.png)

https://github.com/sourcegraph/sourcegraph/blob/273d79b278ee86db2c4d9d52946ff9de4e474293/monitoring/definitions/postgres.go#L37-L46

**Comment by sourcegraph-bot-2** [comment]
Heads up @caugustus-sourcegraph @kevinwojo @michaellzc - the "team/delivery" label was applied to this issue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/cloud-devops - the "team/devops" label was applied to this issue.

**Comment by michaellzc** [comment]
I have no idea who owns monitoring so I tag both delivery and devops...
