### ISSUE TITLE
Every GitHub page shows a warning about HubSpot and Jira extension

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#3431]
> To use the HubSpot extension, you must upgrade to Sourcegraph 3.3 (or the latest version of the browser extension).

> To use the Jira extension, you must upgrade to Sourcegraph 3.3 (or the latest version of the browser extension).

![image](https://user-images.githubusercontent.com/187831/56190557-bd293c80-602a-11e9-9207-4a02d2bd1d5d.png)

Note: I can't dismiss the warning.

I'm unsure how widespread this is, but if its affecting people outside of the Sourcegraph this is a p0 bug. As such I am filing it with that priority. Please adjust once we have triaged.

**Comment by keegancsmith** [comment]
So this was just enabled for the sourcegraph org. The warning went away when I updated to the latest version of the extension.

**Comment by sqs** [comment]
It's only shown for us in the sourcegraph org. It should go away once your browser extension updates. Can you try manually updating in chrome:extensions?

**Comment by sqs** [comment]
sniped

**Comment by keegancsmith** [comment]
![phew](https://media.giphy.com/media/EDt1m8p5hqXG8/giphy.gif)
