### ISSUE TITLE
Error notifications from extensions are clipped

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#3432]
![image](https://user-images.githubusercontent.com/1741180/56192146-12b31880-602e-11e9-8a5e-5259aa9f81e2.png)

**Comment by sqs** [comment]
fixed in https://github.com/sourcegraph/sourcegraph/pull/3419, but @keegancsmith's browser ext hadn't updated to that yet

**Comment by lguychard** [comment]
Oh, hadn't seen this yet. We're just all sniping one another this morning huh 😅
