### ISSUE TITLE
Add (back) the ability to pin code intel popover

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#34322]
**Feature request description**

Add back the ability to pin 📍 the code intel popover. As a user, I would like the ability to keep the code intel popover open without having to leave my cursor on the identifier, so that I can:

- view other parts of the file but retain context of the token I was exploring before
- better read popover content (especially those with long bodies of text)

**Additional context**

Prior to the token click-to-def implementation, users could pin the code intel popover by double-clicking on a token. Since the https://github.com/sourcegraph/sourcegraph/pull/28520, we have received internal feedback that users would like back the ability to pin the popover.

**Comment by chrismwendt** [comment]
> view other parts of the file but retain context of the token I was exploring before

What context? Clicking on a line to mark it retains the line context:

![CleanShot 2022-04-22 at 16 15 35@2x](https://user-images.githubusercontent.com/1387653/164802973-8dc29ed7-79fc-4fd3-ae2a-33df01a922a3.png)

It remains marked while you scroll, too.

> better read popover content (especially those with long bodies of text)

How would pinning make it easier to read? Long docstrings wrap and can be scrolled:

https://user-images.githubusercontent.com/1387653/164803247-3d89397e-5734-47e7-a7b7-51255d16964b.mp4

**Comment by macraig** [comment]
@jjinnii should we close/icebox/backlog this one?

**Comment by camdencheek** [comment]
Related to the design work happening in https://github.com/sourcegraph/sourcegraph/issues/60428. Closing since we will likely completely rethink how popovers work.
