### ISSUE TITLE
Improve VS Code extension activation

### ISSUE THREAD

**Issue by ryankscott** [sourcegraph/sourcegraph#34339]
## Problem to solve

We believe that using Sourcegraph within an IDE positively impacts user retention and frequency of use. However, the current usage of our IDE extensions and we believe one reason is that [most users (>60%)](https://analytics.amplitude.com/sourcegraph/dashboard/oi4b1pi?source=sidebar) don't complete their first search and consequently don't experience the value of Sourcegraph. Improving this activation is one of the most impactful ways we can get users to form a habit of searching with Sourcegraph and consequently improve user retention and frequency.

## Measure of success

- Increase the fraction of users who complete their first search from ~30% to 50%
- Increase the 7 day retention from 3.9% to 10%

## Solution summary

Artifacts:
- https://github.com/sourcegraph/sourcegraph/issues/28311

## What specific customers are we iterating on the problem and solution with?

- TO DO

## Delivery plan

- [ ] TO DO

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by ryankscott** [comment]
Superseded by https://github.com/sourcegraph/sourcegraph/issues/34346#issuecomment-1107876430
