### ISSUE TITLE
Improve Git Blame extension functionality

### ISSUE THREAD

**Issue by ryankscott** [sourcegraph/sourcegraph#34349]
## Problem to solve

We've had numerous customers mention that our Git blame extension is not intuitive and hard to use this includes:
- It's not obvious how to disable it
- It's not obvious that there are two different modes (current line, and whole file)
- The current styling makes information hard to read

As this is one of our most popular extensions (on by default), it provides a poor first experience. This reduces trust in our extensions and makes it unlikely people will install further extensions.

**References:**
- [Productboard feedback](https://sourcegraph.productboard.com/roadmap/4491721-integrations-okr-roadmap/features/6723352/detail)
- Product gaps [1](https://sourcegraph2020.lightning.force.com/lightning/r/a1B5b00000L7TwkEAF/view), [2](https://sourcegraph2020.lightning.force.com/lightning/r/a1B5b00000K4qZEEAZ/view)

## Solution summary

Artifacts:
- TO DO

## What specific customers are we iterating on the problem and solution with?

- TO DO

## Delivery plan

- [ ] TO DO

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
