### ISSUE TITLE
Make Sourcegraph Extensions enterprise friendly

### ISSUE THREAD

**Issue by ryankscott** [sourcegraph/sourcegraph#34347]
## Problem to solve

Enterprise customers have shared feedback with us regarding their expectations from a 3rd party extension registry:

- As we don't have any verification process and anyone can submit to our registry, customers are concerned that they may install malicious extensions by accident. In order to prevent this, they'd like to be limited to only installing extensions created by Sourcegraph, or themselves.
- In some instances, they want Sourcegraph to work in an air-gapped environment. The Sourcegraph Extensions currently don't support this scenario.
- Larger clients want to perform security audits on extensions and the current experience is not ideal. We use scripts to bundle extensions together so that they can publish them to their own instance, once they pass a security audit. (we're using this [script](https://github.com/sourcegraph/sourcegraph-extensions-cloning-scripts))
- We've had numerous customers mention that our Git blame extension is not intuitive and hard to use:
  - It's not obvious how to disable it
  - It's not obvious that there are two different modes (current line, and whole file)
  - The current styling makes information hard to read
  - As this is one of our most popular extensions (on by default), it provides a poor first experience. 

We believe by addressing these concerns we'll build trust in our extensions, increasing the current adoption and building the groundwork for future integration strategy. 

#### Product Gaps
- [Only allow extensions created by Sourcegraph](https://sourcegraph2020.lightning.force.com/lightning/r/Product_Gap_Submission__c/a1C5b00000AEyllEAD/view)
- [Add ability to configure Git Blame extension](https://sourcegraph2020.lightning.force.com/lightning/r/a1B5b00000L7TwkEAF/view)
- [Git Blame toggle should indicate state](https://sourcegraph2020.lightning.force.com/lightning/r/a1B5b00000K4qZEEAZ/view)

#### Productboard feedback
- [Only allow extensions created by Sourcegraph](https://sourcegraph.productboard.com/roadmap/4491721-integrations-okr-roadmap/features/12735027/detail)
- [Improve git blame](https://sourcegraph.productboard.com/roadmap/4491721-integrations-okr-roadmap/features/6723352/detail)

#### Analytics
- [VS Code Marketplace Stats](https://docs.google.com/spreadsheets/d/1WHgEy9nGR4vSPlPpGggfSBfVrqmSracPk7wWvp5eUp8/edit?skip_itp2_check=true&pli=1#gid=1393591588)

## Solution summary

Artifacts:
- https://github.com/sourcegraph/sourcegraph/issues/34628

## What specific customers are we iterating on the problem and solution with?

- TO DO

## Delivery plan

- [ ] TO DO

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
