### ISSUE TITLE
search: Diff and commit search should skip dependency repos

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#34345]
Dependency repos have no history since they are generated from source code fetched from package hosts. All code in a package version is a single commit, with a fixed date. It [can be confusing](https://sourcegraph.slack.com/archives/CHEKCRWKV/p1650532792550079) to search such repos for commits or diffs.

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @jjeffwarner - the "team/search-core" label was applied to this issue.

**Comment by stefanhengl** [comment]
This feature has been discontinued.
