### ISSUE TITLE
JetBrains: Basic search results list

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#34367]
In the current prototype, this is just a plain list that often crashes. For next iteration we want to:

- Have basic styling that resembles the rough layout of our first design sketches
- Allows basic keyboard navigations (arrow up/down)
- Efficiently handles larger amounts of data (pagination?)
- Doesn't break if the search result is of type `repo`.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
