### ISSUE TITLE
JetBrains: Support previewing files

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#34368]
We already have search results inside the web view. This task is about adding a way for the web view <> Java bridge to open a file in the preview panel.

---

One thing I am just thinking of architecture wise is that we can have the same file appear multiple times in the search results list with different occurrences in the same file. For this we need to make sure to:

1. Only create one virtual file 
2. Make sure we properly update the highlights as we move between those search results.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by vdavid** [comment]
Scrolling to the highlighted line is still missing.

I've tried this:
```java
            ScrollingModel scrollingModel = editor.getScrollingModel();
            scrollingModel.disableAnimation();
            scrollingModel.scrollTo(editor.offsetToLogicalPosition(previewContent.getAbsoluteOffsetAndLengths()[0][0]), ScrollType.CENTER);
            scrollingModel.enableAnimation();
```
