### ISSUE TITLE
JetBrains: Make all search box features work

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#34369]
Our current prototype of the search box has a lot of APIs stubbed out. As such, e.g. contexts don't load. We want to audit all props and provide a sensible implementation instead to mimic the behavior of our open source logged-out search: https://sourcegraph.com/search

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by vdavid** [comment]
I’ve identified all individual issues for this broader one, so I’m making this a tracking issue.

Here are the items:

- [ ] https://github.com/sourcegraph/sourcegraph/issues/35171
- [ ] https://github.com/sourcegraph/sourcegraph/issues/35172
- [ ] https://github.com/sourcegraph/sourcegraph/issues/35173
- [ ] https://github.com/sourcegraph/sourcegraph/issues/35174
- [ ] https://github.com/sourcegraph/sourcegraph/issues/35175
- [ ] https://github.com/sourcegraph/sourcegraph/issues/35176
- [ ] https://github.com/sourcegraph/sourcegraph/issues/35177
- [ ] https://github.com/sourcegraph/sourcegraph/issues/35178
