### ISSUE TITLE
Update helm release process to update mainline chart version

### ISSUE THREAD

**Issue by caugustus-sourcegraph** [sourcegraph/sourcegraph#34373]
https://github.com/sourcegraph/deploy-sourcegraph-helm/pull/114 - when cutting a release to helm, we publish to a `release/x.y` branch and update the chart version. That same update needs to be incorporated into main somehow so that future chart versions are correctly incremented.

**Comment by sourcegraph-bot-2** [comment]
Heads up @caugustus-sourcegraph @kevinwojo @michaellzc - the "team/delivery" label was applied to this issue.

**Comment by caugustus-sourcegraph** [comment]
https://github.com/sourcegraph/handbook/pull/3986 - it's a manual step but documented as part of the release now.
