### ISSUE TITLE
search: expose richer ctags classifications

### ISSUE THREAD

**Issue by stefanhengl** [sourcegraph/sourcegraph#34374]
Currently [we map ctags kinds to Microsoft's LSP kinds](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/search/result/symbol.go?L61&subtree=true) before returning to the client. [This leads to Go types being relabeled as "class"](https://sourcegraph.com/search?q=context:%40sourcegraph+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+type:symbol+select:symbol.class+search&patternType=regexp&case=yes).

We should investigate to use the ctags kind directly and expose a richer set of select options.

**Comment by sourcegraph-bot-2** [comment]
Heads up @jjeffwarner - the "team/search-core" label was applied to this issue.

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket, please let us how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
