### ISSUE TITLE
[Accessibility]: Fix issues from Batch Changes user journey audits

### ISSUE THREAD

**Issue by courier-new** [sourcegraph/sourcegraph#34376]
As part of our goal to obtain WCAG 2.1 AA Accessibility compliance by the end of FY23, we will need to audit all major user journeys within the Batch Changes product, log accessibility issues, and plan to fix as many as we can.

This issue reflects the **fixing** stage of this work.

See https://github.com/sourcegraph/sourcegraph/issues/31475 for more.

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by umpox** [comment]
@courier-new I'm going to close this issue as it looks like it's unused!
