### ISSUE TITLE
Regex Search Functionality Doesn't Work for Large JS Files

### ISSUE THREAD

**Issue by Rhynorater** [sourcegraph/sourcegraph#34380]
- **Sourcegraph version:** 3.39.0
- **Platform information:** Docker-Compose/DO Droplet

I have a large JS file (3MB) that I would like to search with regexes. I've set the
```
search.largeFiles": ["*.js"]
```
setting in site administration, but whenever I go to this file and turn on `regex` in the search bar, I cannot get it to turn up any results from the search `function`. Which it certainly should.

#### Steps to reproduce:
1. Load the attached `myaccountmain.js` into a sourcegraph instance
2. Ensure the above `search.largeFiles` setting is in place (and restart SG)
3. Attempt to search this file for the regex: `function`

#### Expected behavior:
It would show the definition of every function.

#### Actual behavior:
It shows no results. 

Settings.json: https://gist.github.com/Rhynorater/cec4a36131e4f3d36f1cdc9c38bcaff4
myaccountmain.js: https://gist.github.com/Rhynorater/857d5be81d480b1cb20f75e346124f76

**Comment by sourcegraph-bot-2** [comment]
Heads up @jjeffwarner - the "team/search-core" label was applied to this issue.

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket, please let us know how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
