### ISSUE TITLE
Notebooks: Getting started improvements 

### ISSUE THREAD

**Issue by marisak** [sourcegraph/sourcegraph#34384]
No estimate or timeline at present, just tracking for now. 

Per feedback from design team and others: 
- (not strictly limited to getting started) Condense "Create" "Import" and "Toggle Notepad" buttons into two ("Create" and "Actions") 
- (not strictly limited to getting started) Change capitalization of tabs to title case - Addressed in [#33480](https://github.com/sourcegraph/sourcegraph/issues/34480)
- Re-record main video or create animation due to current video being small 
- Add "Create Notebook" CTA to main card, similar to Code Insights getting started - Addressed in [#33480](https://github.com/sourcegraph/sourcegraph/issues/34480) 
- Edit some of the copy (e.g. tagline in top card) - Addressed in [#33480](https://github.com/sourcegraph/sourcegraph/issues/34480)
- Interactive demo? 
- Change bottom CTAs to 1 column wide with empty column between them (or find a third CTA) - Addressed in [#33480](https://github.com/sourcegraph/sourcegraph/issues/34480)
- Add link to enable notepad to bottom CTAs

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by camdencheek** [comment]
Closing since I cannot reproduce.
