### ISSUE TITLE
File tree does not update after navigation via code intelligence

### ISSUE THREAD

**Issue by ijsnow** [sourcegraph/sourcegraph#3439]
When you navigate via code intelligence in the same repo AND the target file is a child of the current root of the file tree, the tree does not update. This problem was magnified for me in this repo while digging around in the code because there are multiple files with the name builder and I was glancing at the file tree to know what file I was looking at but often times it was wrong and it took me a while to orient where I was. Another point I'd like to mention is that the obvious blue item in the file tree draws the eye quicker than the bread crumbs that do in fact get updated properly.

Repro:

1. Open up [sourcegraph/zoekt on sourcegraph.com](https://sourcegraph.com/github.com/sourcegraph/zoekt) (must be at root of repo, not directly a file yet)
2. Using file tree, open `cmd > zoekt-archive-index > main.go`
3. cmd+f to find the token `build.NewBuilder` and hover over `NewBuilder and click go to def
4. You'll be taking to `build/builder.go` but the file tree won't update

Assigning @attfarhan as the author of the file tree and @lguychard because this component/issue feels more related to the code-nav team than search-team. Feel free to triage however you'd like.

**Comment by chrismwendt** [comment]
Cannot repro (likely fixed).
