### ISSUE TITLE
Support freeform queries with opportunistic search

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#34394]
This is a 1-day time boxed task where I will make as much progress to support freeform search queries. The idea is to run a search for a freeform inputs that returns meaningful results. E.g., implement a procedure for a kind of decision tree that creates mappings like:

- `routing functions in Go` -> `lang:go func.*route`

- `my/stack/trace/bad.go my/stack/trace2/bad2.go` -> `file:trace/bad.go or file:trace/bad2.go`
 
- `rust` -> show `repo:rust` results first then files containing `rust`. Our results for just the search term [`rust`](https://sourcegraph.com/search?q=context:global+rust&patternType=literal) is poor. It's not possible to express this "show results for this first, then something else" in our query syntax, but it is [now possible in the runtime semantics](https://github.com/sourcegraph/sourcegraph/pull/34315))

Advent of optimized query expressions and our search job abstractions means it's finally possible to implement something like this efficiently. The spike won't implement everything, it's a starting point of ideas to keep growing.

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.
