### ISSUE TITLE
CLA verification is not working

### ISSUE THREAD

**Issue by ptxmac** [sourcegraph/sourcegraph#34391]
#### Steps to reproduce:

1. Follow the [Reviewer's guide](https://docs.sourcegraph.com/dev/contributing/accepting_contribution)
2. Sign the CLA
3. Crate a PR for clabot-config: sourcegraph/clabot-config#67

#### Expected behavior:

clabot should be able to confirm that I've signed the CLA and land the PR for me(?)

It's possible this step need to be performed manually by the sourcegraph team, but the documentation in the reviews guide does not mention that

#### Actual behavior:

clabot keeps denying that I've signed the CLA (and I've tried to sign it a few time, just to make sure I didn't make any typos)

**Comment by jdorfman** [comment]
@ptxmac yeah I'm having issues as well and I work here. I'll see what is happening.

**Comment by bobheadxi** [comment]
Hello, the Reviewer's guide is for reviewers - Sourcegraph teammates - to follow. I've gone ahead and merged your confirmed CLA signing!

**Comment by jdorfman** [comment]
Thanks @bobheadxi

**Comment by jdorfman** [comment]
@ptxmac We are working on a fix for the CLA bot issues #26992
