### ISSUE TITLE
Implement graph visual prototype for compute queries

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#34396]
I want to continue my graph prototype and possibly check it in for notebooks (see this thread: https://sourcegraph.slack.com/archives/C89KCDK5J/p1648269077268509)

Recent feedback prompts more urgency to demo this kind of thing and opportunity for a lot of impact: https://sourcegraph.slack.com/archives/C89KCDK5J/p1650579824188759

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.
