### ISSUE TITLE
[Accessibility Audit] Frontend Platform: Commit diff view

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#34431]
### Steps to replicate journey

Taken from the [user journey list document](https://docs.google.com/document/d/1rSp77P0UDY6ewHq6iXmW0nuilBtkMW05n1ciMB8gQ3w/edit?usp=sharing). Use this for further context.

Note: We are not responsible for code view within the diff view. Specifically, we are not responsible for syntax highlighting (we are responsible for diff highlighting), hover definitions or any other code intel functionality.

Viewing diff commit metadata

- Navigate to commit diff view
- View commit author, message and date
- Click the copy icon next to the commit to copy the full commit SHA hash to your clipboard
- Click the copy icon next to the parent commit to copy the full commit SHA hash to your clipboard
- Click the parent commit to navigate to the commit diff view for said commit
- Click “Browse files at …” to navigate to the repository tree page with commit as the selected repository revision.

Viewing diff commit changes

- Click “Unified” or “Split” to toggle between different diff views
- Collapse changes to a file by clicking the down arrow next to a file path
- Click “View” next to the file path, to load that file in the typical code view, with the current commit as the selected revision.
- Click on the base commit above a file to navigate to the commit diff view for said commit
- Click on a line number to navigate directly to that line (useful for generating links to send)

### How to audit

Follow the instructions here: [Auditing a user journey](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#auditing-a-user-journey)

**Note:** We are planning on arranging thorough third-party audit in the future, so our focus here is just to find the _majority_ of accessibility issues. Don't worry if you feel you haven't found 100% of potential issues, it is better to focus on the core essentials to complete the journey rather than spending lots of time going through every possible problem.

### How to raise discovered problems

Follow the instructions here: [Raising an accessibility bug](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#raising-a-bug)

### Any other questions?

See the [audit FAQ](https://docs.google.com/document/d/1nCi7TvYRpj9eG0_QtgqK1c4L28EiJKVuxyuvg1lAGgo/edit#) - add your question if it isn't there already!

**Comment by jasongornall** [comment]
https://github.com/sourcegraph/sourcegraph/issues/36254
https://github.com/sourcegraph/sourcegraph/issues/36252
https://github.com/sourcegraph/sourcegraph/issues/36251
