### ISSUE TITLE
Increase max-age of assets to 1 year

### ISSUE THREAD

**Issue by nihaals** [sourcegraph/sourcegraph#34433]
## Problem statement

Cache busted assets are refetched more than necessary due to the current max-age only being 2 days instead of forever/as long as possible, leading to longer initial loads more than needed and more egress.

## Success criteria

- All cache busted assets (as far as I can tell, all of them) should have their max-age set to 31536000

## Implementation details

The only reference to the current max-age used is part of assetsutil:
https://github.com/sourcegraph/sourcegraph/blob/58e63dffa8fc8cf8a243215c353586c593a88c9d/cmd/frontend/internal/app/assetsutil/handler.go#L58

## Estimated amount of work

T-shirt size estimate: **XS**.

## Contributors

1. Check out [contributing guidelines](https://github.com/sourcegraph/sourcegraph/blob/main/CONTRIBUTING.md).
2. Join the Sourcegraph [Community Space](https://srcgr.ph/join-community-space) on Slack and join the `#help` channel where the Sourcegraph team can help you!
3. Check out [the good first issues board](https://github.com/orgs/sourcegraph/projects/210) to find more curated issues.

**Comment by heyajulia** [comment]
I want to take this issue on, if possible. Unfortunately, I can't join the Community Space right now because the invite link has expired.

Is the line of code you mentioned in the issue the only thing that needs to be changed?

**Comment by nihaals** [comment]
> Is the line of code you mentioned in the issue the only thing that needs to be changed?

[As far as I can tell](https://sourcegraph.com/search?q=repo%3A^github\.com%2Fsourcegraph%2Fsourcegraph%24%409aefc1feb281e95648fae31c682222991e7d232f+172800&patternType=literal), yes.

**Comment by jdorfman** [comment]
@heyajulia 

> Unfortunately, I can't join the Community Space right now because the invite link has expired.

can you try clicking the link again, please?

**Comment by heyajulia** [comment]
That worked, thank you! :)
