### ISSUE TITLE
dev/ci: experiment with spot/preemptible VMs for agents

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#34458]
Re: https://github.com/sourcegraph/sourcegraph/pull/34370
If it's possible to recover from lost agents, I wonder if we might want to consider using spot/preemptible nodes for CI? https://cloud.google.com/compute/docs/instances/spot#pricing

> Spot prices, the prices for Spot VMs, change over time, up to once every 30 days. Specifically, Spot VMs provide at least a 60% discount and up to a 91% discount on the price of standard VMs with the same machine types.

Copied from https://sourcegraph.slack.com/archives/C02MWRMAFR8/p1650903202002139

We could start with a separate node pool to experiment

**Comment by bobheadxi** [comment]
@davejrt did something tangential around streaming images for faster image pulls when deploying agents

**Comment by bobheadxi** [comment]
Notes from @davejrt : we should maintain bare minimum that run on non-spot nodes perhaps

**Comment by davejrt** [comment]
minimum viable dedicated node count has been implemented [here](https://github.com/sourcegraph/infrastructure/pull/3347) so in the event we don't have availablity for spot nodes at this spec, it's still possible to deploy dedicated infra to support CI until we can scale back up or change our node type for spot nodes.
