### ISSUE TITLE
[Accessibility]: Settings page menus are not responsive

### ISSUE THREAD

**Issue by courier-new** [sourcegraph/sourcegraph#34454]
### Audit type

Mobile device navigation

### User journey audit issue

https://github.com/sourcegraph/sourcegraph/issues/34073

### Problem description

When I navigate to a settings page, the menus push the main page content out and produce a horizontal scrollbar. They also wrap weirdly.

### Expected behavior

Adam's suggestion: Get rid of the user-level navigation entirely, on any screen size.

### Additional details

![image](https://user-images.githubusercontent.com/8942601/165130381-ecdefed7-1ac4-46fa-9e88-5a4d83d2c839.png)

### Assigning labels

- [X] Please give this issue an estimate by applying a label like `estimate/Xd`, where X is the estimated number of days it will take to complete.
- [X] If this issue is specific to a specific Sourcegraph product, e.g. Code Intel, Batch Changes, etc., please assign the appropriate team label to this issue.
- [X] If this issue will require input from designers in order to complete, please assign the label `needs-design`.

**Comment by umpox** [comment]
Related audit: https://github.com/sourcegraph/sourcegraph/issues/34429
