### ISSUE TITLE
Searchable search history

### ISSUE THREAD

**Issue by PatMyron** [sourcegraph/sourcegraph#34460]
I'd love to search my past searches beyond recent searches:

<img width="853" alt="Screen Shot 2022-04-25 at 9 50 55 AM" src="https://user-images.githubusercontent.com/7014355/165136185-da3d2e6f-84f3-49b7-aa7a-1eab41af3103.png">

#### Describe alternatives you've considered.

Recent searches and browser history are decent starts, but [URL encoding](https://en.wikipedia.org/wiki/Percent-encoding) makes browser history difficult to search/read

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by camdencheek** [comment]
Hi @PatMyron! Thanks for the request. 

We're actively thinking about how to improve the search input experience, and one of the things we were looking at was navigating through your search history with `ctrl+n` and `ctrl+p` (similar to shell history).

@benvenker @fkling, wondering if we should also consider fzf-like search in the query bar 🤔

**Comment by PatMyron** [comment]
Just realized search history is back:
https://github.com/sourcegraph/sourcegraph/pull/43594 🥳
Wish it defaulted to searching history while typing; the clock icon is too subtle
