### ISSUE TITLE
Add exclusions to GCP Datadog to ensure that VMs without agents are not counted against our host budget

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#34467]
We have hosts that are reporting to Datadog that do not have agents. We should exclude those hosts so we are not billed for them

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/cloud-devops - the "team/devops" label was applied to this issue.

**Comment by daxmc99** [comment]
Confirmed infra hosts are now down from where they were. We now have no on-demand host usage. 49 when we pay for 70. 
https://app.datadoghq.com/billing/usage?data_source=billable&summary_month=2022-05&trends_start_date=2022-05-01&trends_time_frame=Monthly
