### ISSUE TITLE
Visiting a repository for the first time shows "starting to clone" but doesn't start

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#3447]
1. Add external service: GitHub, Access token, `Add organization repositories`, enter `sourcegraph`.
2. Go to repositories page, search for repository you want e.g. `sourcegraph/infrastructure`.
3. Click on it, it says `starting to clone`.
4. It doesn't start cloning, you end up waiting several minutes while all other repositories clone first.
5. Refresh the page because you are tired of waiting, finally it starts cloning.

Seems like we only kick off cloning for a viewed repository on an actual hard page refresh?

**Comment by nicksnyder** [comment]
> we only kick off cloning for a viewed repository on an actual hard page refresh

I believe that this has been the behavior for a long time now (for better or for worse).

**Comment by keegancsmith** [comment]
This isn't a regression unfortunately. This is pre-existing behaviour. We will triage this issue today to decide when we tackle it.

**Comment by slimsag** [comment]
Guessing you pinned this issue by accident, so unpinning.

**Comment by mrnugget** [comment]
I started digging into this today. I'm not yet sure how the code works, but I just wanted to document the actual behavior I could confirm:

1. In the repositories list we actually say "Visit the repository to clone it"

<img width="442" alt="Screen Shot 2019-06-03 at 19 18 57" src="https://user-images.githubusercontent.com/1185253/58821703-f0a14400-8635-11e9-9172-ac9ba35fc18b.png">

2. When you then visit the repository the repository _does_ get cloned in the background, but the request is sent off asynchronously and you only see this, *after waiting 2-3 seconds* (I don't yet know why there's such a lag)

<img width="1225" alt="Screen Shot 2019-06-03 at 19 19 07" src="https://user-images.githubusercontent.com/1185253/58821918-74f3c700-8636-11e9-917a-988d07686c3e.png">

I _think_ what's actually wrong is the "Empty repository" message and that we don't automatically reload the page

**Comment by mrnugget** [comment]
@keegancsmith and I just found out that this ticket here has been fixed by his fix for https://github.com/sourcegraph/sourcegraph/issues/1744 :)
