### ISSUE TITLE
Setting up metrics and finalizing v1 state for code intel badge feature

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#34490]
Tracking remaining efforts to get to a v1 state as defined by [RFC 672](https://docs.google.com/document/d/1i_o3nbOxd9rSNNuHN-uVsfT6b6wurG6ZmfpvtjTLBKw/edit#) for feature #31180 .

- [x] Mirror code intel icon and dropdown menu on repository page
- [x] Set up pings unique count of clicks on ["I want precise support" CTA](https://www.figma.com/file/p5rVseXjNvXRkvXCdttbWt/Semantic-badge?node-id=1098%3A17704) 
- [x] Set up pings for unique count of clicks on ["Set up for this repository" CTA](https://www.figma.com/file/p5rVseXjNvXRkvXCdttbWt/Semantic-badge?node-id=1100%3A17710)
- [x] Set up pings for unique count of clicks on [error message CTAs ](https://www.figma.com/file/p5rVseXjNvXRkvXCdttbWt/Semantic-badge?node-id=1100%3A17711)

---------

> @efritz is it possible for us to track/set up pings for "indexer configured" and "error resolved" so that we can track how successful the CTAs were in leading to a precise intel configuration or resolving an error?

**Decision:** After v1, we will explore how we might better measure how this feature has impacted self-servicing (configuration or error fixing).

**Comment by efritz** [comment]
To reduce the burden on the BizOps team let's try to get as many of these as possible in a single schema change. we can bundle these in https://github.com/sourcegraph/analytics/pull/412, which adds fields to track the "I want precise support!" CTA.

**Comment by efritz** [comment]
@jjinnii Is it possible for us to track/set up pings for "indexer configured" and "error resolved"

Are you asking for a dual of the pings already listed? For example, one of the pings above indicates a user clicked "Set up for this repository" - are you asking for another ping that shows if the user followed-through with that action? Right now the links only go to an external indexer page, or it redirects to a sibling view with `?state=errored`.

**Comment by jjinnii** [comment]
@efritz Yes! If we could have some ping for "(some) indexer successfully configured" or "error resolved", we could try to create a view that starts with the CTA click and the progression of events after that. I imagine this might be difficult, but I just wanted to ask.

**Comment by macraig** [comment]
@jjinnii I don't think we'd be able to tell whether they've configured an indexer or solved an error as a result of their clicks on the CTA. What we could do eventually is loosely correlate to how many customers are setting up and using indexers.

**Comment by efritz** [comment]
For v1 I can absolutely count clicks/unique clicks on all of these, and for v2 we can iterate as we scope the user flow for each of these out.

**Comment by jjinnii** [comment]
Okay sounds good to me. 😄  I thought it might be difficult for v1, but I wanted to explore first whether it'd even be possible for us to measure how this feature is directly contributing to user self-servicing. I've updated this feature to reflect that the metrics should just track count of clicks on the various CTAs - I'll create a new issue for tracking funnel conversion from these CTA clicks for a future improvement! 

cc: @efritz
