### ISSUE TITLE
3.39 patch to fix broken code insights line charts

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#34495]
@sourcegraph/delivery I am requesting the following commits be included in a patch release. They are already merged into `main`:
- https://github.com/sourcegraph/sourcegraph/commit/12af2224f32027c08181cee959e853568e3387ce

I have read [when and why we perform patch releases](https://handbook.sourcegraph.com/engineering/releases#patch-releases) and answer the questions as follows:

> Are users/customers actively asking us for these changes and cannot wait until the next full release?

Not yet, but they will. This is a critical bug we have identified and it may affect a big number of code insights chart https://github.com/sourcegraph/sourcegraph/pull/32554 . 

(added by @Joelkw : CEs are already [asking for these changes and cannot wait](https://sourcegraph.slack.com/archives/C01JKF7KUBD/p1650911844472799), as this impacts demos. Moreover,  this bug affects any two-datapoints-old search or capture group insight running over all repos – we know that [this will impact 30+ customers](https://sourcegraph.looker.com/explore/sourcegraph_events/view_counts?qid=fZNDGMy0miffsx0eD0U9xx&origin_space=318&toggle=fil,vis). Many of these customers will be in sales conversations to purchase insights this week or in the next one month.) 

> Are the changes extremely minimal, well-tested, and low risk such that not testing as we do in a full release is OK?

Yes.

> Is there some functionality completely broken that warrants redacting the prior release of Sourcegraph and advising users wait for the patch release?

Yes, code insights charts with more than 1 series have bad visual series (lines) in some cases when points are not aligned with each other by the x-axis value. 

![](https://user-images.githubusercontent.com/6098507/165202472-c63bf888-7265-4fb3-bc89-715cedaceca5.png)

> This will interrupt our regular planned work and release cycle, taking one full working day of our time, and will take up all of our site admin's valuable time by asking them to upgrade or producing noise for them if they don't need to upgrade.
>
> Do you believe the changes are important enough to warrant this?

Yes.

> Patch releases are a signal we can do something better to improve the quality of Sourcegraph. Have you already scheduled a call (or created a google doc) to perform a [retrospective](https://about.sourcegraph.com/retrospectives) and identify ways we can improve?

Yes, you can find it here https://docs.google.com/document/d/11WPnLpV6MPcLSgPWTTSP1ThHabp5QXM3spguVokktgQ/edit?usp=sharing

---

**For the [Release Captain]** - after reviewing this request:

- [ ] **Comment on this issue** with a decision regarding the request.
- [ ] If you are a first-time [Release Captain], please review the high-level overview of the [patch release process].
- [ ] If approved, **add it to a patch release**:
  - If there is [already an upcoming patch release](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+), add the listed commits alongside a link to this issue
  - If there is no upcoming patch release, create a new one:
    - [ ] Update [`dev/release/release-config.jsonc`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/release/release-config.jsonc) and open a PR to `main` to update it
      - [ ] Change `upcomingRelease` to the current patch release
      - [ ] Change `previousRelease` to the previous patch release version
      - [ ] Change `releaseDate` to the current date (time is optional) along with `oneWorkingDayAfterRelease` and `oneWorkingDayBeforeRelease`
      - [ ] Change `captainSlackUsername` and `captainGitHubUsername` accordingly
    - [ ] `yarn release tracking:issues` 
    - [ ] Add the listed commits alongside a link to this issue to the generated [release tracking issue](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+)
- [ ] **Comment and close this issue once the relevant commit(s) have been cherry-picked into the release branch**.

[release captain]: https://handbook.sourcegraph.com/engineering/releases#release-captain
[patch release process]: https://handbook.sourcegraph.com/departments/product-engineering/engineering/process/releases#patch-release-process

**Comment by caugustus-sourcegraph** [comment]
@sourcegraph/release-guild

**Comment by coury-clark** [comment]
Here is the commit (from 3.39 tag) without all of the additional refactor work: https://github.com/sourcegraph/sourcegraph/commit/50b17c5b3f4bd04c44707df5f2b543a3a6327a4b

**Comment by coury-clark** [comment]
50b17c5b3f4bd04c44707df5f2b543a3a6327a4b
df57afd768ad453df6097a2bde83b9cde04c5656

**Comment by coury-clark** [comment]
Cherry picked into 3.39.1 https://github.com/sourcegraph/sourcegraph/issues/34545
