### ISSUE TITLE
"Create with batch change" message breaks customers workflow

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#34496]
### Problem

This customer has a specific changeset body format, that is used by an automated system to land their changesets.
Changeset bodies need to _end_ with (key: value) metadata that gets turned into [git trailers](https://git-scm.com/docs/git-interpret-trailers).

Batch Changes automatically appends a "created with batch changes" message at the end of PRs that breaks this flow.

<img width="942" alt="image" src="https://user-images.githubusercontent.com/25070988/165274608-8b251347-259a-4f17-ab45-537e925f68e9.png">

#### Workardound

There is no workardound

### Impacted customer

- https://github.com/sourcegraph/accounts/issues/3078

[Product gap](https://sourcegraph2020.lightning.force.com/lightning/r/Product_Gap__c/a1B5b00000MwV1nEAF/view)

**Comment by chrispine** [comment]
One idea (from Malo): Like by default it is at the end (If the spec does not contain {{batchChangeLink}}. But you can also put it wherever by explicitly using {{batchChangeLink}}

**Comment by LawnGnome** [comment]
Another idea (from Adam): we could move the default template (which isn't actually a template right now, but there's no technical reason it couldn't be) into a site configuration setting and then allow it to be customised by the site admin.
