### ISSUE TITLE
3.39 patch to fix notebooks markdown editing

### ISSUE THREAD

**Issue by fkling** [sourcegraph/sourcegraph#34509]
@sourcegraph/delivery I am requesting the following commits be included in a patch release. They are already merged into `main`:

- bb9f0e69752a9deedaed1b9026108f5fa0c4ba4e

---

The intent of the questions below is to ensure we keep Sourcegraph high quality and [only create patch releases based on a strict criteria.](https://handbook.sourcegraph.com/engineering/releases#patch-releases) If you can answer yes to many or most of these questions, we will be happy to create the patch release.

I have read [when and why we perform patch releases](https://handbook.sourcegraph.com/engineering/releases#patch-releases) and answer the questions as follows:

> Are users/customers actively asking us for these changes and cannot wait until the next full release?

Not yet since we are just about to GA notebooks and promote it publicly, but we don't want to promote a broken product. [It has been raised internally](https://sourcegraph.slack.com/archives/CHEKCRWKV/p1650476807821959). 

> Are the changes extremely minimal, well-tested, and low risk such that not testing as we do in a full release is OK?

Yes. The change introduces a check so that the caret will only be moved if the editor doesn't already have focus.

> Is there some functionality completely broken that warrants redacting the prior release of Sourcegraph and advising users wait for the patch release?

Notebooks markdown editing will be quite unusable without the fix. For completeness: Without this fix entering a carriage return will move the caret to the end of the editor, disrupting the user's editing flow.

> This will interrupt our regular planned work and release cycle, taking one full working day of our time, and will take up all of our site admin's valuable time by asking them to upgrade or producing noise for them if they don't need to upgrade.
>
> Do you believe the changes are important enough to warrant this?

Considering that we are actively promoting a new feature/product, yes.

> Patch releases are a signal we can do something better to improve the quality of Sourcegraph. Have you already scheduled a call (or created a google doc) to perform a [retrospective](https://about.sourcegraph.com/retrospectives) and identify ways we can improve?

No, but I will.

---

**For the [Release Captain]** - after reviewing this request:

- [ ] **Comment on this issue** with a decision regarding the request.
- [ ] If you are a first-time [Release Captain], please review the high-level overview of the [patch release process].
- [ ] If approved, **add it to a patch release**:
  - If there is [already an upcoming patch release](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+), add the listed commits alongside a link to this issue
  - If there is no upcoming patch release, create a new one:
    - [ ] Update [`dev/release/release-config.jsonc`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/release/release-config.jsonc) and open a PR to `main` to update it
      - [ ] Change `upcomingRelease` to the current patch release
      - [ ] Change `previousRelease` to the previous patch release version
      - [ ] Change `releaseDate` to the current date (time is optional) along with `oneWorkingDayAfterRelease` and `oneWorkingDayBeforeRelease`
      - [ ] Change `captainSlackUsername` and `captainGitHubUsername` accordingly
    - [ ] `yarn release tracking:issues` 
    - [ ] Add the listed commits alongside a link to this issue to the generated [release tracking issue](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+)
- [ ] **Comment and close this issue once the relevant commit(s) have been cherry-picked into the release branch**.

[release captain]: https://handbook.sourcegraph.com/engineering/releases#release-captain
[patch release process]: https://handbook.sourcegraph.com/departments/product-engineering/engineering/process/releases#patch-release-process

**Comment by coury-clark** [comment]
Cherry picked into 3.39.1 https://github.com/sourcegraph/sourcegraph/issues/34545
