### ISSUE TITLE
Add telemetry for "Home page / More search features" link

### ISSUE THREAD

**Issue by erzhtor** [sourcegraph/sourcegraph#34516]
Add `HomepageExampleMoreSearchFeaturesClicked" event:

<img width="489" alt="image" src="https://user-images.githubusercontent.com/6717049/165335720-1ec3d154-8c28-408c-95e4-4e76c4040841.png">

See [slack thread](https://sourcegraph.slack.com/archives/C03B4EMBXL4/p1650983348988029?thread_ts=1650921892.061019&cid=C03B4EMBXL4)

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @a-bergevin - the "team/growth" label was applied to this issue.
