### ISSUE TITLE
Notepad drag and resize exploration

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#34513]
We're hearing more frequently from users (so far internally) that it would be nice to be able to drag/reposition and resize the notepad. It makes sense and is something we thought about initially, but deliberately marked as out of scope so we could wait for some feedback.

I'd like to preemptively get some design eyes on this so that we can at least start thinking about pitfalls and getting some idea of how this is implemented well in other products. From there, we can create some more tickets for additional work.

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.
