### ISSUE TITLE
insights: click in functionality associates incorrect `before` and `after` times

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#34523]
When clicking into an insight chart the `before` and `after` dates are getting swapped such that it is impossible to ever match any results:

Example result from a click in:
https://sourcegraph.test:3443/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24++type:diff+after:2022-01-25T17:00:00-07:00+before:2021-12-25T17:00:00-07:00+func&patternType=literal

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by chwarwick** [comment]
This is being caused by difference in sort order of the data points being returned for just in time capture group insights vs the backfilled search insights.
