### ISSUE TITLE
Users' display names are reset to only their first name (SSO)

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#3452]
A user reported that their Sourcegraph user display names are reset to only contain their first name. It sounds like SSO is overwriting the display name upon login, and SSO is computing the display name to only be the first name. This is probably an issue with our mapping of SSO user attribute fields. Maybe we need to support more field names that could contain the last name, or maybe we are just doing it incorrectly. The SSO system here in use is AD.

Reported by https://app.hubspot.com/contacts/2762526/company/693777177 (we will need more info to solve this)

**Comment by keegancsmith** [comment]
I am not exactly sure what the next steps here are, but my guess is to research what user attribute fields AD can return for last name? Once we have that, it should be an easy change to make? Does that sound correct @beyang?

**Comment by beyang** [comment]
(Low priority)
