### ISSUE TITLE
Trace logs are not being correlated in the Datadog UI

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#34521]
Sourcegraph [heavily uses](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/internal/search/job/observe.go?L57:8#tab=references) opentracing logging 

Datadog does not [does not currently support this field](https://github.com/DataDog/dd-trace-go/blob/v1.27.1/ddtrace/opentracer/span.go#L43) and it doesn't seem like they plan to https://github.com/DataDog/dd-trace-go/issues/205. 

Possible solutions: 

- [ ] Uses a more Opentracing-compatible tracing solution
- [ ] Emit logs via our new observation pkg at these call sites when `DD_ENV` is set. Datadog supports log parsing this [explicit field](https://docs.datadoghq.com/tracing/faq/why-cant-i-see-my-correlated-logs-in-the-trace-id-panel/?tab=custom#trace_id-option).

**Comment by daxmc99** [comment]
Filed a support ticket: https://help.datadoghq.com/hc/en-us/requests/800703

These logs are not being ingested due to a difference in timestamp format. 

https://docs.datadoghq.com/logs/log_configuration/processors/?tab=ui#log-date-remapper 

We output logs in the Unix nanosecond format per [OpenTelemetry](https://opentelemetry.io/docs/reference/specification/logs/data-model/#field-timestamp)

**Comment by bobheadxi** [comment]
Related workaround by having `internal/observation.TraceLogger` emit normal logs as well:

1. https://github.com/sourcegraph/sourcegraph/pull/34456
2. https://github.com/sourcegraph/sourcegraph/pull/34703
3. https://github.com/sourcegraph/sourcegraph/pull/34838

**Comment by bobheadxi** [comment]
Closing, we are not proceeding with datadog (https://github.com/sourcegraph/sourcegraph/issues/37568)
