### ISSUE TITLE
[Accessibility]: testing automation

### ISSUE THREAD

**Issue by courier-new** [sourcegraph/sourcegraph#34553]
### Audit type

Keyboard navigation

### User journey audit issue

test

### Problem description

Automation testing

### Expected behavior

Automation testing

### Assigning labels

- [ ] Please give this issue an estimate by applying a label like `estimate/Xd`, where X is the estimated number of days it will take to complete.
- [ ] If this issue is specific to a specific Sourcegraph product, please assign the appropriate team label to this issue.
- [ ] If this issue will require input from designers in order to complete, please assign the label `needs-design`.

**Comment by eseliger** [comment]
@courier-new is this ticket still relevant?

**Comment by courier-new** [comment]
I was trying to use it to get [this tracking issue](https://github.com/sourcegraph/sourcegraph/issues/34376) to work, but it's just not picking it up. 🙁 I'll just close it, it's not worth the trouble heh.
