### ISSUE TITLE
JetBrains: Warn user when copying a link to a branch that doesn’t exist on the remote

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#34569]
## Summary

When the user uses the "Copy link" feature on a branch that's not pushed, the link goes 404. Warning the user and/or letting them link to `main` instead would be nice.

## Context

We have a {right click on editor} → Sourcegraph → Copy link to file feature

<img width="1075" alt="CleanShot 2022-04-27 at 13 17 04@2x" src="https://user-images.githubusercontent.com/2552265/165506775-8208c238-e8ee-4fa8-b3df-1cd2e41f5090.png">

## Problem

@courier-new wrote for VS Code, but it also applies to JetBrains: “often, I haven’t published my branch, and I just get an ugly 404 page and end up having to go modify the URL manually.”

## Solution

a.) Warn the user when copying a link to a branch that doesn't exist on the default remote
b.) If the warning will be a popup that we can customize, offer a “copy link to {default branch} instead” option

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
