### ISSUE TITLE
JetBrains: Move TS build pipeline to tsbuild

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#34571]
After getting started with a basic TypeScript pipeline, we want to make sure to keep the dev experience as good as possible. One improvement that we're currently making for the VSCE is to use `esbuild` to speed up build times. We want the JetBrains setup to reflect those improvements.

c.f #34186

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by vdavid** [comment]
@philipp-spiess is this something you'd feel like taking on next week, or maybe work on it together?
I have some vague memory of you mentioning build tools as a weak area for yourself, and I feel similarly about it for myself.

**Comment by philipp-spiess** [comment]
@vdavid Yeah would love to pair on it 🙂

**Comment by vdavid** [comment]
Status update: We're waiting for @tjkandala's solution for VS Code.

**Comment by vdavid** [comment]
@tjkandala, do you have any updates on the esbuild setup for VS Code? I remember you saying that you were practically done with it and only needed to create the PR. No rush at all; I just want to plan accordingly and make sure that I didn't miss updates on this.

**Comment by philipp-spiess** [comment]
This is now unblocked https://github.com/sourcegraph/sourcegraph/pull/34010#issuecomment-1151872076
