### ISSUE TITLE
Add git.sr.ht/~eliasnaur/gio to Sourcegraph.com

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#3457]
At https://github.com/sourcegraph/sourcegraph/issues/1027#issuecomment-483957854 @eliasnaur requested we add https://git.sr.ht/~eliasnaur/gio to Sourcegraph.com.

I added an OTHER external service with:

```json
{
  // Requested at https://github.com/sourcegraph/sourcegraph/issues/1027#issuecomment-483957854
  "url": "https://git.sr.ht",
  "repos": ["~eliasnaur/gio"]
}
```

but the repository is not showing up in the site admins repositories list. Any ideas, @keegancsmith @tsenart?

**Comment by keegancsmith** [comment]
This is a regression in the other service _only_ on Sourcegraph.com. See https://github.com/sourcegraph/sourcegraph/issues/3459

**Comment by keegancsmith** [comment]
To solve this we need to support partial syncing on Sourcegraph.com. This is a nice to have, so unlikely it will happen soon vs more pressing needs.

**Comment by ryanslade** [comment]
This works now: https://sourcegraph.com/site-admin/repositories?query=%7Eeliasnaur%2Fgio
