### ISSUE TITLE
Support new syncer in sourcegraph.com deployment

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#3459]
Tasks:

- [ ] Endpoint for lazily inserting new repositories.
- [ ] Keep CloneURL up to date in database.
- [ ] **Stretch** Lazily refresh data

In #2025, we deferred working on making sourcegraph.com work with the new syncer. This needs to be done still.

Related to this, since we removed support for the old OtherExternalServicesSyncer, #3457 depends entirely on this.

**Comment by keegancsmith** [comment]
A thread with some discussion on how to do this https://sourcegraph.slack.com/archives/CHPC7UX16/p1557735685001300

> Additional note: I think the full "add repo if it doesn't exist" should be moved to repo-updater. Right now the frontend just does a repo-lookup in that code path, but I think it should all happen in repo-updater.
>
> Because then you could do a sync which supports renames / etc. Just do NewDiff where
> sources: A singleton containing the repo.
> stored: All repos with that name or external ID.
>
> That way we get for free rename detection (and we could in future make it work for deletion)
>
> additionally it moves all writes to the repo table into repo-updater, which we want to fully own the repo table.

**Comment by keegancsmith** [comment]
To support use cases like this, maybe we should run the syncer but exclude the kind github? https://github.com/sourcegraph/sourcegraph/issues/3457 cc @tsenart @mrnugget

**Comment by keegancsmith** [comment]
This is done! We somewhat backported how it worked before which is completely fine. We may one day want to clean this up so we also answer sg.com repoLookup requests from the DB. But for now what we have is acceptable.
