### ISSUE TITLE
Add "verify email notification banners" for cloud

### ISSUE THREAD

**Issue by erzhtor** [sourcegraph/sourcegraph#34603]
Currently, when signing up with an email, a verify email is sent to the user, but user still can continue using without verification. To encourage email verification, we propose to show a non-dismissable notice banner on top with the information about emails not verified and a link to re-send verify email.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @a-bergevin - the "team/growth" label was applied to this issue.

**Comment by erzhtor** [comment]
It is blocked by https://github.com/sourcegraph/sourcegraph/issues/34604. We will launch this under the feature flag and test the new feature flagging system.

**Comment by a-bergevin** [comment]
@erzhtor I'd like to baseline this and track it as a metric (% verified emails). But I tried to pull up the events in amplitude and while I can see events firing for "verification email sent" I can't see any properties recorded for the email being verified or not verified for the user. Any ideas why this isn't working for me? https://analytics.amplitude.com/sourcegraph/notebook/6jamtck/breadcrumbs/chart/4xlw43w

**Comment by erzhtor** [comment]
@a-bergevin, do you mean Amplitude User Property for email verification status? 
If so, I think it is done via a scheduled query, which periodically (1 hr) syncs user properties https://github.com/sourcegraph/analytics/blob/master/BigQuery%20Schemas/amplitude_user_characteristics.sql. I guess, @sourcegraph/bizops could help to update to include email verification status?

**Comment by a-bergevin** [comment]
Analytics team is digging into why this isn't populating. They asked me to submit it as an issue so here it is for further tracking. https://github.com/sourcegraph/sourcegraph/issues/34844
