### ISSUE TITLE
postgres less than 5 connection warning is misleading

### ISSUE THREAD

**Issue by michaellzc** [sourcegraph/sourcegraph#34616]
Since 3.39, we started collecting postgres metrics from `codeinsights-db`, and all managed instances are constantly complaining about "less than 5 active connections for 5m0s", learn more https://sourcegraph.slack.com/archives/C017SLJGA2Z. IMO it's just code-insights related codes do not interact with the database that much.

The warning-level alert of [less than 5 active connections for 5m0s](https://docs.sourcegraph.com/admin/observability/alert_solutions#postgres-connections) was added [a long time ago](https://github.com/sourcegraph/sourcegraph/blame/d249c8e6446037fafcc1e6186647046b1279778c/monitoring/definitions/postgres.go#L31), maybe now it is a good time to revisit this alert and decide whether we should remove it or not.

This alert is useful in a way that it could indicate a portion of services are currently down (clients are disconnected from the db), but such thing should be represented using a different metrics (pods/containsers are down, oomkill, etc).

we should care more about whether there is enough connections available and alerting admin when the db is running out of connection.

should we just remove it?

**Comment by sourcegraph-bot-2** [comment]
Heads up @caugustus-sourcegraph @kevinwojo @michaellzc - the "team/delivery" label was applied to this issue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/cloud-devops - the "team/devops" label was applied to this issue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @RafLeszczynski - the "team/cloud" label was applied to this issue.

**Comment by RafLeszczynski** [comment]
@michaellzc  please prepare this issue for grooming and make sure the description clearly communicate:
- the problem that has to be solved
- expected outcomes
- acceptance criteria

**Comment by michaellzc** [comment]
I suggest we should close this issue

- #cloud no longer cares about this alert since we maintain a whitelist of alerts that would yield an opsgenine alerts
- resoloving this issue doesn't help with Cloud initiative 
- codeinsights-db is used by code insights, hence I am expecting the component team to own the alerts and decide what to do with it.
