### ISSUE TITLE
Completion "loading..." dropdown appears seemingly at random

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#3461]
When typing on Github text fields, the completion "loading..." dropdown often appears when typing text that shouldn't trigger it:

![image](https://user-images.githubusercontent.com/1741180/56285670-14590b00-6118-11e9-8f61-402245dad784.png)

I would only expect it to appear when typing `$` for Hubspot, and `[A-Z]+-` for Jira, but here it appears on `a`.

I can't reproduce this in all text fields, but I could reliably reproduce it when typing a PR review comment on https://github.com/sourcegraph/sourcegraph/pull/3441

**Comment by sqs** [comment]
I think this is related to https://github.com/sourcegraph/sourcegraph/issues/3433. It sometimes takes more than 2000ms due to GC. I could fix it by removing the "Loading...", but that is only a partial fix. When you see "Loading...", is typing also laggy?

**Comment by nicksnyder** [comment]
I am seeing this too. Typing is laggy. I assumed this logic would only trigger when a hotkey `$` is used/present in the text?

**Comment by sqs** [comment]
Indeed related to #3443. Closing as dupe. It does not only trigger when you press `$`. Each successive keystroke adds about 48 event listeners. Disable the "Experimental text field completion" feature flag to fix it 100%, or (if you really want the HubSpot completion, as I do 😄 ) just live with it and reload the GitHub page if it gets bad. I will be fixing this but there is no ETA as it is an internal-only feature now.
