### ISSUE TITLE
insights: test monorepo improvements and confirm success

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#34613]
We've been making improvements to code insights running over large monorepos. This issue is focused on the testing and confirming we are "done" with our monorepo support work, and monorepo codebases (repo size 4GB+) are supported as well as any other codebase. 

To test this, we should create common _persisted_ (backend) insights over the megarepo and gigarepo for some common flows: 
1) A single-series insight with a literal search
2) A single-series insight with a regexp search
3) A 5-series insight with literal searches, at least one file: or lang: filter on a series
4) A 5-series insight with regexp searces (using OR modifiers as well, like `|`), at least one file: or lang: filter on a series
5) A capture group series over just the monorepo for something with 20+ match types (think licenses, go versions, docker versions) 
6) A capture group series over all repos including the monorepo for something with 20+ match types
7) a language pie chart insight over the monorepo 

We should then test that those insights (where applicable) handle: 
- Filtering to only include the monorepo 
- Filtering to exclude the monorepo
- A context that includes the monorepo 

When we test this, we should track (roughly) time to completion to see if performance is an order of magnitude worse. Heuristically, if these test insights take >24 hours to run individually, that approaches the upper bound of acceptable first-class-supported performance.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by felixfbecker** [comment]
We should probably test this rather sooner in the iteration than later, in case there are issues found we need to fix. Assigning @leonore tentatively since you and @coury-clark worked on this

**Comment by leonore** [comment]
WIP plan for queries for these.

1. A single-series insight with a literal search

We need to enable streaming search on backend insights for this #34989.

`context:global lang:SCSS -file:module select:file patterntype:literal`

2. A single-series insight with a regexp search

`file:go\.mod$ go\s*(\d\.\d+) patterntype:regexp`

3. A 5-series insight with literal searches, at least one file: or lang: filter on a series

same as 1) above.

`redis`

`postgres`

`database/sql lang:go`

`mongodb`

`sqlite`

4. A 5-series insight with regexp searches (using OR modifiers as well, like `|`), at least one file: or lang: filter on a series


`patterntype:regexp file:package.json "[license|licence]":\s(.*),` <- notice added |

`patterntype:regexp sourceCompatibility (\d[_\.]\d) f:build\.gradle$`

`patterntype:regexp file:helm lang:YAML \sversion:\s[v']?(\d+\.\d+\.\d)`

5. A capture group series over just the monorepo for something with 20+ match types (think licenses, go versions, docker versions)

`patterntype:regexp color:#([0-9a-fA-f]{3,6}) archived:no fork:no`

6. A capture group series over all repos including the monorepo for something with 20+ match types

`patterntype:regexp var\(--(.*color.*)\) lang:css`

7. a language pie chart insight over the monorepo



* Filtering to only include the monorepo
* Filtering to exclude the monorepo
* A context that includes the monorepo

monorepo: `github.com/sgtest/megarepo`

https://k8s.sgdev.org/contexts/@leo.p/sg-and-megarepo

**Comment by Joelkw** [comment]
@leonore thanks for listing the test plan! 

One other thing I wanted to add/note explicitly: can we ensure we also test "correctness" in addition to performance, for these states? 

(For correctness verification, in the past we just use Sourcegraph searches, the trick is just making sure you're searching the older revisions and that those older revisions are the correct date matches, which can be done with our `repo:someRepo@version` filter).

**Comment by Joelkw** [comment]
Update: 

For #5) – this may not be relevant if it runs JIT; we just want to test the backend persisted/streaming. (Customers would love it, but it wasn't part of our original work plan so I don't necessarily expect it works.) 
For #7) – this is more important than #5 to get working, but still ultimately less important than any other case listed here.

**Comment by Joelkw** [comment]
Thanks @leonore ! Are there github issues for the remaining steps we'd need to either spike on or implement to provide full monorepo support? My understanding is that your third bullet means we don't support large monorepos yet for customers to not have issues making insights over them – or that incorrect?

**Comment by leonore** [comment]
@Joelkw yes that's correct, because of the issues with indexed search mentioned there we can't provide full support. I've chased the search teams about improvements they can make there so that we can link issues here. ideally if we can get some streaming errors surfaced to us in insights then we could retry on them.

I'll close this issue in favour of working on that once I get more information.

**Comment by Joelkw** [comment]
Thanks @leonore !

**Comment by leonore** [comment]
@camdencheek following up here as it will be easier not to lose track of. you mentioned [in slack](https://sourcegraph.slack.com/archives/CHEKCRWKV/p1652724992497029?thread_ts=1652714972.348659&cid=CHEKCRWKV) that partial timeout errors might not get propagated. is there a plan to surface them, and if so, is there a ticket for this/can one be created so insights can then eventually use that info?

**Comment by camdencheek** [comment]
Okay, so looking closer at this, I think we _do_ propagate the "timed out" message, but not as an error. We send it up as a `SkippedReason`. For the code insights use-case, it looks to me like receiving an event with `skipped.Reason == "shard-timeout"` [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/insights/query/streaming/decoder.go?L58:1) should be translated to an error so code insights knows it isn't getting complete results for that query and can retry.

@leonore does that make sense based on what you've seen?

**Comment by leonore** [comment]
@camdencheek yep I can see some logs on dogfood where we are hitting `shard-timeout`. so I'll open an issue for us to work on using that information, see if that fixes the issue. thanks!
