### ISSUE TITLE
insights: Backend work to sort series

### ISSUE THREAD

**Issue by CristinaBirkel** [sourcegraph/sourcegraph#34612]
Continuing off of spike ticket: https://github.com/sourcegraph/sourcegraph/issues/33930

API changes:

1. `createLineChartSearchInsight`: anything needed here? Do we want users be able to set this at creation time?
2. `updateLineChartSearchInsight`: I believe changes here will be needed in order to persist the sort order and display count. Which I think we want to be able to do? [That's what I did in this draft PR. ](https://github.com/sourcegraph/sourcegraph/pull/34611/files#diff-ad80c5c19b82ee4efe98223115a1f7621b20251d79019cd9718311f3d909cafcR617) Any thoughts here about the structure?
3. `insightViews`: I assume we'll need to add an additional argument to take the sort filters. I didn't consider this use case at first and will need to add it into the PR. I wonder in general if this belongs with the `filters` argument, or is a separate thing? It's not really a filter.
4. Any other API changes needed?

As far as sorting options, I've added these:
```
enum SeriesSortOrder {
    HIGHEST_RESULT_COUNT
    LOWEST_RESULT_COUNT
    ASC_LEXICOGRAPHICAL
    DESC_LEXICOGRAPHICAL
}
```
I may need to add `OLDEST` and `LATEST` as well, given the designs.

I think one open question is whether this applies only to capture group insights. There may be conflicting thoughts there. Right now I'm storing this metadata at the `insight_view` level, but if it's only for capture group series I wonder if it belongs on the capture group series itself.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by unclejustin** [comment]
@CristinaBirkel we want this for all insights, not just capture groups. 100% we need a way to add these sorts to `insightsView` so we can get a temporary sort/filter.

@AlicjaSuska if a user sorts/filters should they be able to save that directly? I think it would be nice to have. This way you never have to leave the dashboard.

Flow like this:
- User creates insight
- Realizes they just want to see the top 10
- Updates from the dropdown 
- Decides they want to keep this
- Clicks a "save" button

**Comment by unclejustin** [comment]
Oh and yes we probably want this at create time as well as edit. @AlicjaSuska do we have designs for the creation/edit UIs for sorting/filtering?

**Comment by coury-clark** [comment]
I'd suggest we separate order from sort mode. For example
``` gql
input SortOptions {
    direction: SortDirection!
    mode: SortMode!
}

enum SortDirection {
    ASCENDING
    DESCENDING
}

enum SortMode {
    RESULT_COUNT
    LEXICOGRAPHICAL
}
```

In the `insightViews` query we can add a new argument:

``` gql
query insightViews(..., sortOptions: SortOptions)
```

I think this structure will make it overall easier to both grok (discover available options) and to build the implementation.

**Comment by CristinaBirkel** [comment]
@coury-clark That could work.. I guess with `OLDEST` and `LATEST` it could maybe be asc/desc on `DATE_ADDED`? My main concern is that this might not work for every type of sort we may ever want. Can every sort order be codified in this way? Will we ever want a sorting option that is only asc and not desc?

To me it's a little harder to grok because it takes a second to understand what asc/desc mean for different types of sorts. That might just be me though. And then we either need another column in the database or to translate it in the resolver. I guess I'm leaning that I think it's simpler to just spell them out in one `enum`. I don't feel super strongly about it though. If you do I'm happy to do it in this split format. Let me know what you think!

**Comment by CristinaBirkel** [comment]
@coury-clark 

> This seems like it would be true regardless if this is separated or not.

I'm not sure.. I think that one could argue that `sortBy: HIGHEST_RESULT_COUNT` is more intuitive than `sortDirection: DESCENDING, sortMode: RESULT_COUNT` It's subjective, but having that flexibility to name things intuitively seems nice to me. 

> I think my ultimate point is that you are going to have to separate these for the implementation anyway

I'm not sure I understand this point. [This is how I did it here so far.](https://github.com/sourcegraph/sourcegraph/pull/34611/files#diff-d30dc8d1e713c83bf8f40cb57812975d24a13d182482e3d3a8f80feb5df919f6R446) And I'm just storing it in the database as a single `sort_series_by` field. It's never going to be super high cardinality (two options per sort mode,) so it doesn't seem excessive to me.

@unclejustin any thoughts here? What seems easier to you as the caller?

**Comment by AlicjaSuska** [comment]
@unclejustin the only updates in creation / editing UI are copy updates that indicate that sorting will be available later on - [design](https://www.figma.com/file/lYD20GUga7m3aZ49fYh1Vu/Charts-with-20%2B-matches-%7C-RFC-655-%7C-%2333930-%5BWIP%5D?node-id=1656%3A19026)
