### ISSUE TITLE
[placeholder]: capture group insights support setting deterministic ordering (especially for 20+ patterns matched)

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#34624]
Placeholder for [these designs](https://www.figma.com/file/lYD20GUga7m3aZ49fYh1Vu/Charts-with-20%2B-matches-%7C-RFC-655-%7C-%2333930-%5BWIP%5D?node-id=0%3A1) and related to https://github.com/sourcegraph/sourcegraph/issues/33930 ; for [RFC 655](https://docs.google.com/document/d/1Kv83fCz4dfqv8AGUTWpt7z5w_CGlO53WEXtDSfVG5e0/edit#heading=h.trqab8y0kufp)

Child issues:
- https://github.com/sourcegraph/sourcegraph/issues/34649
- https://github.com/sourcegraph/sourcegraph/issues/34652
- https://github.com/sourcegraph/sourcegraph/issues/34653
- https://github.com/sourcegraph/sourcegraph/issues/34612

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by unclejustin** [comment]
Closed in favor of [tracking issue](https://github.com/sourcegraph/sourcegraph/issues/34661)
