### ISSUE TITLE
Repo permissions: Explicitly allow read for all users

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#34631]
A [customer](https://github.com/sourcegraph/accounts/issues/3) would like to be able to specify that some repos are accessible by all users on their instance when using explicit permissions. 

Technically they could grant all their users permissions to view the repo but this would require constantly needing to update the list for each repo so that it contains all users.

## Proposal 

Add a new `bool` column to `repo_permissions` called `unrestricted`. A true value in that row indicates that any user can view the repo and we should not perform any user specific checks. `unrestricted` was chosen to be consistent with the naming for unrestricted external services. 

We will then need to update our authz [query](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@d67ebebf298b54ba678490e361742792e8f4622c/-/blob/internal/database/repos_perm.go?L62) to take this value into account.

For now, we'll only allow updating the value of this field using our explicit permissions API by adding a new mutation, something like:

```graphql
setRepoPermissionsUnrestricted(
        """
        The repository ids we want to set unrestricted permissions on.
        """
        repositories: [ID!]!
        """
        true: Any user can access the repo
        false: Use existing user permissions
        """
        unrestricted: Boolean!
    ): EmptyResponse!
```

## TODO

- [x] CHANGELOG
- [x] Update docs
- [x] Indicate unrestricted state in the UI https://github.com/sourcegraph/sourcegraph/pull/35423

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.

**Comment by ryanslade** [comment]
@sourcegraph/repo-management @unknwon @bobheadxi I was trying to think of the most direct way of solving this problem with a small blast radius, thoughts?

**Comment by unknwon** [comment]
It makes sense to me 🤔 Would be nice if we also have a DB constraint to make sure either `unrestricted` is `false` or `user_ids_int` is empty (if possible).

**Comment by ryanslade** [comment]
FYI @mike-r-mclaughlin

**Comment by mike-r-mclaughlin** [comment]
@ryanslade could we deploy just a single container to test this out?  if so, which one?  Should we wait for the next release or use insiders build?

**Comment by ryanslade** [comment]
I think it's best to wait for the next release, which is being cut later this week since this involves a migration and touches multiple servicess

**Comment by asdine** [comment]
@mike-r-mclaughlin I'm not sure if I understand the question correctly, but basically both will be available and can be used to either "unrestrict" a specific repo or all the repos of a bitbucket project.
