### ISSUE TITLE
MI Resource estimation: Tracking issue

### ISSUE THREAD

**Issue by sanderginn** [sourcegraph/sourcegraph#34633]
### Plan

Tracking issue for [RFC 6XX WIP: Managed Instance resource estimation improvements
](https://docs.google.com/document/d/19YmiTSq5URW4A9C5ScNV58u7PJj5ZizB0OJfG_hSHCQ)

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/cloud-devops - the "team/devops" label was applied to this issue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @RafLeszczynski - the "team/cloud" label was applied to this issue.

**Comment by rafax** [comment]
We decided not to implement this (to focus on higher priority items) for v1.1, and we'll revisit resource allocation for v2.
