### ISSUE TITLE
Self-Hosted Migration: Create Secure Storage Infrastructure

### ISSUE THREAD

**Issue by kevinwojo** [sourcegraph/sourcegraph#34641]
![image](https://user-images.githubusercontent.com/9081680/165764414-8c03de3f-bf0d-4d64-b995-0a240710881f.png)

**Represents #2 in diagram**

# Context
In order to transfer data between the customer and Sourcegraph, we will use Google Cloud Platform (GCP) Storage since it is an existing system within Sourcegraph that meets the requirements for this process. 

- The customer does not need a dedicated account if are leveraged. Initial thoughts around this involve sharing a GCP credentials file with the customer and leveraging the `gcloud CLI`.
- Google Cloud Platform (GCP) has security controls that Sourcegraph Security Team has implemented including encryption, audit logging, shared link expiration, and MFA-enforced authentication.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/cloud-devops - the "team/devops" label was applied to this issue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @RafLeszczynski - the "team/cloud" label was applied to this issue.

**Comment by RafLeszczynski** [comment]
@sourcegraph/cloud do we still plan to work on this or should we archive this issue

**Comment by michaellzc** [comment]
do we have a clear ownership of on-prem -> cloud migration? I remember the decision was #cloud is not responsible for doing it, but which team is up for it?

**Comment by RafLeszczynski** [comment]
> do we have a clear ownership of on-prem -> cloud migration? I remember the decision was #cloud is not responsible for doing it, but which team is up for it?

It would be Customer Engineering or Delivery

**Comment by michaellzc** [comment]
> > do we have a clear ownership of on-prem -> cloud migration? I remember the decision was #cloud is not responsible for doing it, but which team is up for it?
> 
> It would be Customer Engineering or Delivery

I vote to archive this issue from the Cloud board and assign it to the CE team

**Comment by michaellzc** [comment]
I think we can close any self-hosted migration related issues since it's been decided #cloud does not own the work
