### ISSUE TITLE
Code Insights [FE] - New popup for sort/filter data series

### ISSUE THREAD

**Issue by unclejustin** [sourcegraph/sourcegraph#34649]
Subset of https://github.com/sourcegraph/sourcegraph/issues/34624

[Designs](https://www.figma.com/file/lYD20GUga7m3aZ49fYh1Vu/Charts-with-20%2B-matches-%7C-RFC-655-%7C-%2333930-%5BWIP%5D?node-id=1615%3A7742)

|![image](https://user-images.githubusercontent.com/1855233/165789304-3569c0e1-6b41-49c9-b916-da3f45b330e6.png)|
|:--:|
|As of Apr 28|

**Comment by Joelkw** [comment]
@unclejustin just noting conversation from sync – we should evaluate keeping this in the existing panel and if it's faster let's certainly do that (and if it's equal work, let's perhaps default to that or sync again, given we don't have strong conviction on design needing to be a separate panel).

**Comment by unclejustin** [comment]
@Joelkw, apologies for not making it clear, but I will keep it in the same panel. This is just the standalone form part that will be stuffed into the existing panel in a hot new PR coming soon to a repo near you.
