### ISSUE TITLE
Self-Hosted Migration: Develop Migration Helper Utility

### ISSUE THREAD

**Issue by kevinwojo** [sourcegraph/sourcegraph#34642]
![image](https://user-images.githubusercontent.com/9081680/165764414-8c03de3f-bf0d-4d64-b995-0a240710881f.png)

**Represents #3 in diagram**

# Context
In order to migrate a self-hosted Sourcegraph installation to a Managed Instance, the Site Administrator must perform a complex set of tasks for the migration to be considered successful. Due to the complexity of this process, it can be error-prone which can cause delays. 

Taking an interactive approach, we should develop a stand-alone utility that encapsulates the manual actions we require the Site Administrator to perform. While this proposal does not address technology selection, it does capture the requirements and level of effort.

# Outcomes

The migration helper utility is an easily-distributable artifact that Site Administrators with shell (SSH / Console) access to the self-hosted installation.

The migration helper utility must be able to:

- Extract database data from the Frontend Database (pgsql), Code Intel Database (codeintel-db) and Code Insights Database (codeinsights-db). 
- The database exports needed will vary depending on the customer’s usage of Sourcegraph. Consult the [Doc Site for more information](https://docs.sourcegraph.com/admin/install/migrate-backup) about data recreation.
- Code Host configuration is migrated as a part of the pgsql database dump. In the current architecture, we require all Code Hosts to be publicly available (ex: public Github, Gitlab, Bitbucket)
- Extract the Site Configuration JSON from the self-hosted instance.
- Extract any encryption keys stored as files
- Compress the database data and Site Configuration JSON.
- Encrypt the compressed file.
- Transmit the compressed file to Box.

Additionally the utility must be easily distributable. The customer should be able to use the utility with minimal installation steps or dependencies. This proposal does not prescribe the exact implementation, but outlines the requirements and spirit of the development activity. Some customers will prefer to have a more hands-on approach than other customers. When it comes to implementation, the team should collaborate with the Product Manager to explore this decision more closely.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/cloud-devops - the "team/devops" label was applied to this issue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @RafLeszczynski - the "team/cloud" label was applied to this issue.

**Comment by RafLeszczynski** [comment]
@sourcegraph/cloud do we still plan to work on this or should we archive this issue

**Comment by michaellzc** [comment]
I think we can close any self-hosted migration related issues since it's been decided #cloud does not own the work
