### ISSUE TITLE
Self-Hosted Migration: Document Process in handbook

### ISSUE THREAD

**Issue by kevinwojo** [sourcegraph/sourcegraph#34640]
![image](https://user-images.githubusercontent.com/9081680/165764414-8c03de3f-bf0d-4d64-b995-0a240710881f.png)

**Represents #1 in diagram**

# Context
The following are proposed changes to handbook documentation to support this new business process: [Sourcegraph Handbook Pull Request](https://github.com/sourcegraph/handbook/pull/2765). There are two main changes to the handbook documentation including the creation of an internal process for executing migrations and an SLA for the migration process. These changes are intended to drive consistency and set expectations internally and externally.

This will need to be updated to reflect work done in https://github.com/sourcegraph/sourcegraph/issues/34641 and https://github.com/sourcegraph/sourcegraph/issues/34642

At this time, the PR captures the work done to as a "one-off" to evaluate the viability and demand of a Self-Hosted -> Managed Instance service.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/cloud-devops - the "team/devops" label was applied to this issue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @RafLeszczynski - the "team/cloud" label was applied to this issue.

**Comment by RafLeszczynski** [comment]
@sourcegraph/cloud do we still plan to work on this or should we archive this issue

**Comment by michaellzc** [comment]
I think we can close any self-hosted migration related issues since it's been decided #cloud does not own the work
