### ISSUE TITLE
Code Insights [FE] - Filter data series using new filter popup

### ISSUE THREAD

**Issue by unclejustin** [sourcegraph/sourcegraph#34653]
Subset of https://github.com/sourcegraph/sourcegraph/issues/34624

Depends on [Code Insights [FE] - Add new popup to insight card](https://github.com/sourcegraph/sourcegraph/issues/34652)
Depends on [BE implementation](https://github.com/sourcegraph/sourcegraph/issues/34612)

---

Use new filter pop to actually filter data series for insight.

TBD
- Save filter?

**Comment by vovakulikov** [comment]
@unclejustin is there any particular thing that requires FE review?

**Comment by unclejustin** [comment]
Will be closed with https://github.com/sourcegraph/sourcegraph/issues/34653

@vovakulikov you've already reviewed the PR for this one
