### ISSUE TITLE
insights: handle search alerts of an empty repository gracefully

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#34651]
When a search returns no repositories in a result it reports an alert:

``` json
{
  "data": {
    "search": {
      "results": {
        "alert": {
          "title": "No repositories found"
        },
        "results": []
      }
    }
  }
}
```

Currently the Code Insights background processor treats these alerts as transient errors, and triggers retry logic that ends up spamming a lot of queries that are guaranteed to return the same result. We should handle this alert more gracefully and avoid triggering the retry condition.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by leonore** [comment]
In the non-streaming path this is where we're not handling this: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/insights/background/queryrunner/work_handler.go?L178-195=

The streaming path does generate that alert too, can be tested this way. 
```
curl --header "Accept: text/event-stream" \
--header "Authorization: token [token]" \
--get \
--url "https://sourcegraph.test:3443/.api/search/stream" \
--data-urlencode "q=repo:AAAAAAAFFFF test"
event: alert
data: {"title":"No repositories found","description":"Try using a different `repo:\u003cregexp\u003e` filter to see results","proposedQueries":null}

event: progress
data: {"done":true,"matchCount":0,"durationMs":12,"skipped":[]}

event: done
data: {}
```

So we'd need to add some `OnAlert` logic in the decoder: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/insights/query/streaming/decoder.go?L29-70.

**Comment by felixfbecker** [comment]
(tentatively assigning @leonore )
