### ISSUE TITLE
Integrate AWS Code Commit with new syncer

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#3465]
- [x] Integrate AWSCodeCommit with new syncer
  - [x] Implement AWSCodeCommitSource
  - [x] Enable new syncer for AWSCodeCommit external services
   - [x] Use AWS' `repositoryId` as `external_id` in `repo` table for AWS CodeCommit repositories
      - [x] Change [ExternalRepoSpec](https://github.com/sourcegraph/sourcegraph/blob/8bb3cc4124818b6f5c47bf0c7a6b50a932309379/pkg/extsvc/awscodecommit/codehost.go#L17) to use `repositoryId` as `ID` instead of `ARN`
      - [x] Write "reset" migration so that syncer writes `respositoryId` to `external_id` (see https://github.com/sourcegraph/sourcegraph/pull/3850 for example)
   - [x] Implement `awscodecommit.exclude` to support enabled state deprecation (this should use AWS `repositoryId` as `id`, see previous step)
   - [x] Implement enabled state deprecation migration of AWSCodeCommit external services
      - [x] Migrate all disabled repos to `awscodecommit.exclude` list.
      - [x] Deprecate `awscodecommit.initialRepositoryEnablement` setting.

Follow up on #2025
Part of #3467

**Comment by tsenart** [comment]
Hey @mrnugget, it turns out we don't need `awscodecommit.repos` anymore because it's not needed in the enabled state deprecation migration since this PR: https://github.com/sourcegraph/sourcegraph/pull/3598

**Comment by tsenart** [comment]
Updated the issue description accordingly.

**Comment by mrnugget** [comment]
Just to be on the safe side: am I correct in assuming that I don't need to add`awscodecommit.repositoryQuery`because AWS CodeCommit does not seem to support querying? (See [docs here](https://docs.aws.amazon.com/codecommit/latest/APIReference/API_ListRepositories.html) and [code here](https://sourcegraph.com/github.com/aws/aws-sdk-go-v2/-/blob/service/codecommit/api.go#L4969))

**Comment by tsenart** [comment]
Sounds right to me @mrnugget. It wasn't included in the checklist above anyways. I suppose you were looking at it from the Bitbucket Server PR.

**Comment by mrnugget** [comment]
> Sounds right to me @mrnugget. It wasn't included in the checklist above anyways. I suppose you were looking at it from the Bitbucket Server PR.

Yes, exactly :) I looked at what every other source is doing and came across this.
