### ISSUE TITLE
[Accessibility Audit] Search: Saved Searches

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#34658]
### Use cases to replicate

Taken from the [user journey list document](https://docs.google.com/document/d/1IA90OFew5MTcxFndKS2Xn4vb8sOt68sj537P7AGj_Tk/edit?usp=sharing). Use this for further context.

Please take these following use cases and replicate them when running your audit.

- I can open my saved searches from any page by opening the user menu and clicking on “Saved Searches”
- I can open my saved searches from the user settings page by clicking on the tab that says “Saved Searches” 
- I can open the saved searches for any org I belong to by going to the org’s settings page and clicking on the tab that says “Saved Searches”
- On the saved searches pages page for a user or org, I can see all the saved searches that belong to that user or org, showing the description and buttons to open settings and delete the saved search
- I can click on the “Add a saved search” button in a saved searches page to open a page that will let me create a new saved search for that user or org. I can set a description and a search query and click “Add saved search” to create the search and navigate back to the list page. If there is an error with the search query, an error message is displayed instead.
- I can click on the saved search’s name to run the search
- I can click on the settings button next to the saved search to open the editor where I can modify the saved search’s description and query.  I can make any changes and click “Update saved search” to update the search in place. If there is an error with the search query, an error message is displayed instead.
- I can click on the delete button next to the saved search to get a confirmation dialog; clicking “Cancel” will not delete the saved search; clicking “OK” will delete it.

### How to audit

Follow the instructions here: [Auditing a user journey](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#auditing-a-user-journey)

**Note:** We are planning on arranging thorough third-party audit in the future, so our focus here is just to find the _majority_ of accessibility issues. Don't worry if you feel you haven't found 100% of potential issues, it is better to focus on the core essentials to complete the journey rather than spending lots of time going through every possible problem.

### How to raise discovered problems

Follow the instructions here: [Raising an accessibility bug](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#raising-a-bug)

### Any other questions?

See the [audit FAQ](https://docs.google.com/document/d/1nCi7TvYRpj9eG0_QtgqK1c4L28EiJKVuxyuvg1lAGgo/edit#) - add your question if it isn't there already!

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by limitedmage** [comment]
Audit completed with the following follow-up issues:

- https://github.com/sourcegraph/sourcegraph/issues/35169
- https://github.com/sourcegraph/sourcegraph/issues/35162
