### ISSUE TITLE
Code Insights [FE] - Add new popup to insight card

### ISSUE THREAD

**Issue by unclejustin** [sourcegraph/sourcegraph#34652]
Subset of https://github.com/sourcegraph/sourcegraph/issues/34624

Depends on [Code Insights [FE] - New popup for sort/filter data series](https://github.com/sourcegraph/sourcegraph/issues/34649)

[Design](https://www.figma.com/file/lYD20GUga7m3aZ49fYh1Vu/Charts-with-20%2B-matches-%7C-RFC-655-%7C-%2333930-%5BWIP%5D?node-id=1615%3A7614)

|![PixelSnap 2022-04-28 at 10 36 27](https://user-images.githubusercontent.com/1855233/165790215-79ceca80-8650-46ae-a1a0-8aa96a341d64.png)|
|:--:|
| As of Apr 28 |

**Comment by vovakulikov** [comment]
Close this one in favour of reusing of existing filter popup cc @AlicjaSuska
