### ISSUE TITLE
RepoLookup should load metadata from database

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#3466]
Since all code hosts are synced with upstream metadata included (#2025), we can answer RepoLookup queries by speaking to our own database. This removes the need to speak to an upstream code host API on user requests. Additionally we can remove a lot of our application caching logic in code host clients.

This can only be done once we have migrated all code hosts.

**Comment by tsenart** [comment]
Additional reason for us to do this comes from #3589: Since we have the links in the database now, we can just serve them without contacting the code host. This is resilient to rate limit exhaustion.
