### ISSUE TITLE
Code Insights: Capture Group Ordering Tracking issue

### ISSUE THREAD

**Issue by unclejustin** [sourcegraph/sourcegraph#34661]
### Plan

[Designs](https://www.figma.com/file/lYD20GUga7m3aZ49fYh1Vu/Charts-with-20%2B-matches-%7C-RFC-655-%7C-%2333930-%5BWIP%5D?node-id=0%3A1)
Related to https://github.com/sourcegraph/sourcegraph/issues/33930
For [RFC 655](https://docs.google.com/document/d/1Kv83fCz4dfqv8AGUTWpt7z5w_CGlO53WEXtDSfVG5e0/edit#heading=h.trqab8y0kufp)

Allow sorting and filtering of capture group insights.

### Tracked issues

@CristinaBirkel

Completed
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/34612  🛠️   🏳️ [Insights iteration 18](https://github.com/sourcegraph/sourcegraph/milestone/160)

@unclejustin

Completed
- [x] (🏁 today) https://github.com/sourcegraph/sourcegraph/issues/34653  🛠️   🏳️ [Insights iteration 18](https://github.com/sourcegraph/sourcegraph/milestone/160)

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
