### ISSUE TITLE
insights: chart rendering breaks when screen size is too small 

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#34668]
Reproduced on firefox 99.0.

When insight charts get too narrow, all of the points collapse into the corner. They do not "uncollapse" when they get wider than this breakpoint.

![CleanShot 2022-04-28 at 13 34 11](https://user-images.githubusercontent.com/5090588/165841211-b2528959-d527-4b6f-b645-ea1c8b89e1fa.gif)

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by Joelkw** [comment]
For added info, this weirdly "fixes itself" if you scroll the insights off the page and back on (not acceptable state, but maybe this info helps with debugging): https://www.loom.com/share/de6d476c04694fbf95b4a41fcd9dae56

**Comment by vovakulikov** [comment]
@Joelkw this is correct because we do not render cards that we can't see. So this problem fixes itself because we rerender charts when they re-appear in the viewport.
