### ISSUE TITLE
Search Contexts: search contexts picker doesn't provide a proper search for some search strings

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#34686]
#### Steps to reproduce:

1. Go to k8s.sgdev.org
2. Try to find query by full spec string (for example if we have context @vova/hello then try to search vova
3. See that picker provides no contexts  

<img width="630" alt="Screenshot 2022-04-29 at 14 09 03" src="https://user-images.githubusercontent.com/18492575/165892953-ed0dd024-05d8-4932-8f17-372a67d0d38b.png">

<img width="519" alt="Screenshot 2022-04-29 at 14 09 13" src="https://user-images.githubusercontent.com/18492575/165892986-1cc80c96-319c-4106-8dc8-2c78142e6639.png">

#### Expected behavior:
Search over contexts should work properly with all possible search strings. 

#### Actual behavior:
Search doesn't work properly if we don't pass context name explicitly

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by camdencheek** [comment]
@vovakulikov can you still reproduce this? Contexts have changed a bit since this was created and I think it's probably safe to close.
