### ISSUE TITLE
Unable to set SourcegraphURL from G Suite Configuration

### ISSUE THREAD

**Issue by KattMingMing** [sourcegraph/sourcegraph#3468]
When installing the browser extension as an organization policy via G Suite – there's an option to pass a configuration file that will set the browser extension's default settings.

This is used so that one admin can set the `SourcegraphURL` for all user's. Documentation for how we suggest doing this is described here: https://admin.google.com/AdminHome#ChromeAppDetails:appId=dgjhfomjieaadpoljlnidmbgkdffpack&appType=CHROME&flyout=reg

The issue is that when passing in a configuration file like:

```
{
	"sourcegraphURL": {
		"Value": "https://sourcegraph.example.com"
	}
}
```

The SourcegraphURL is not set and therefore users will need to configure their own URL.

The fix is to check the chrome managed storage settings when the extension is installed and also when the managed storage is updated so that users who already have the extension receive updates to the configuration.

Requested by https://app.hubspot.com/contacts/2762526/company/1753262050

**Comment by lguychard** [comment]
In appearance, we already do this:
- Check managed storage on installation: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/browser/src/extension/scripts/background.tsx#L319-340
- Listen to storage updates: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/browser/src/extension/scripts/background.tsx#L96-127

However, I can tell that there are several potential bugs lingering there, for instance calling `setSourcegraphURL()` in the background page on a storage update doesn't actually persist the sourcegraph URL to `storage.sync`, which is what is used in the content script...

**Comment by lguychard** [comment]
Fixed in https://github.com/sourcegraph/sourcegraph/pull/5894
