### ISSUE TITLE
JetBrains: Fix the JCEF flickering at first load

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#34694]
## Problem

When the JCEF component in the modal first loads, its background is white at first, then changes to grey as the page loads. [10-sec Loom demo](https://www.loom.com/share/aadc973b964e47a79e34aea7a6a3d637)
This looks weird and we don't want this.

## Solution

The white background might come from two places:
a.) the page background
b.) the JCEF component background

If it's a.) then the proposed solution is to dynamically set the body background early.
If it's b.) then the proposed solution is to render a different Swing component over the JCEF until the document loads.

**Comment by vdavid** [comment]
@philipp-spiess I've tried a couple of things with this on the weekend, but in the end, I realized that even if I manually set the background of the HTML page (e.g. to red), there is some time when the background is white.

Same with `browser.setPageBackgroundColor()` that you tried: it doesn't solve the flickering.

I think we'll need to go with option _b.)_ and do some hack to hide the JCEF component until the document starts loading.

**Comment by philipp-spiess** [comment]
Yeah, makes sense!

**Comment by madppiper** [comment]
@vdavid perhaps a quick solution: 

just set jcefWindow.getContent().setVisible(false); 

on load and change it back after the page has been loaded  (via the onLoadEnd event i showed you). That should solve the "flickering" and some other issues too

**Comment by vdavid** [comment]
I'll try that, thanks!

**Comment by vdavid** [comment]
It doesn't work. I've added [this line](https://github.com/sourcegraph/sourcegraph/pull/34815/files) (same as `jcefWindow.getContent().setVisible(false);`) but then the `onLoadEnd` even doesn't fire. I've added a breakpoint to line 43 ([here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@dv/jetbrains-prevent-web-view-flickering-on-load/-/blob/client/jetbrains/src/main/java/com/sourcegraph/bridge/JSToJavaBridge.java?L43%3A1-44%3A1=&utm_product_name=IntelliJ+IDEA&utm_product_version=IntelliJ+IDEA)), but it never reaches that line. When I don't hide the panel, the breakpoint does get triggered.
I guess it makes sense for the UI engine not to load the component while it's not visible.
Any other ideas @madppiper?

**Comment by madppiper** [comment]
Had a few minutes and played around with the initialization. This seems to work just fine:

https://github.com/ilscipio/sourcegraph/commit/c62cef0115fd40b7ceb17ee3b64271322e7b7a95

**Comment by vdavid** [comment]
For the record: the above suggestions included off-screen rendering, and didn't help after all because of Linux and MacOS bugs.

Trying [OverlayLayout](https://www.logicbig.com/tutorials/java-swing/overlay-layout.html) next

**Comment by madppiper** [comment]
Just cause this might be useful info later: 

Over the weekend, I looked into different settings of the CefBrowser and also looked around the Cef Forums for potential other parties having similar issues. The way I understood it, the problem is an inherit one, which derives from how the browser itself is loaded before any browser page or editor styling is applied - hence the reason it "flickers". 

Unfortunately for us, the only solutions provided suggested to use the offscreen rendering. I played around with it some more, but the end result was that thought it would solve it on windows, it would reintroduce the bug on linux/mac. 

Knowing this, we could however force a refresh of the browser, once we know it is added to screen. It may also act as a workaround for us, without it being of any real concern for the user.

**Comment by vdavid** [comment]
Asked Yann Cébron at JetBrains → he's asking around for help. Hoping to get some clues.

My question to him, for the record:

---

When I first display the JCEF component, it’s white for a half a second (here is a [10-second Loom](https://www.loom.com/share/aadc973b964e47a79e34aea7a6a3d637) where I demo this), then it renders the HTML page where the background matches the theme, and from then on, we’re fine.
Now, this white flicker bothers us a lot because it looks very weird, but not sure how to get rid of it.
We’ve tried:
- **Off-screen rendering.** But there are several known issues about off-screen rendering not working well on Mac and Linux.
- **Hiding the JCEF** at first, and only show it at the CefLoadHandler.onLoadEnd() event. But the event never fires when the JCEF is hidden, probably because Swing is smart enough not to load it before we show it.
- **Using an OverlayLayout** to render another component in front of the JCEF browser. But same here, the onLoadEnd() event never gets triggered.

**Comment by madppiper** [comment]
@vdavid Perhaps we should add: 

We can consistently remove the flashing issue via offscreen renderer by loading a blank page first, applying the background style and then loading the original url in a subsequent request. So this would be a preferable way for us. 

However, offscreen rendering remains problematic with input fields where the key events are registered (i checked), but not inserted into the field.

**Comment by madppiper** [comment]
It is easier if i just post this from my recent tests: 

```
public FindPopupPanel(Project project) {
        super(new BorderLayout());

        setPreferredSize(JBUI.size(1200, 800));
        setBorder(PopupBorder.Factory.create(true, true));
        setFocusCycleRoot(true);

        // Create splitter
        Splitter splitter = new OnePixelSplitter(true, 0.5f, 0.1f, 0.9f);
        add(splitter, BorderLayout.CENTER);

        PreviewPanel previewPanel = new PreviewPanel(project);

        JBPanelWithEmptyText jcefPanel = new JBPanelWithEmptyText(new BorderLayout()).withEmptyText("Unfortunately, the browser is not available on your system. Try running the IDE with the default OpenJDK.");
        JSToJavaBridgeRequestHandler requestHandler = new JSToJavaBridgeRequestHandler(previewPanel);
        browser = JBCefBrowser
                .createBuilder()
                .setOffScreenRendering(true)
                .setUrl("about:blank")
                .setCreateImmediately(true)
                .createBrowser() ;


        if (browser != null) {
            browser.getCefBrowser().getUIComponent().setFocusTraversalKeysEnabled(true);

            // Create and set up JCEF browser
            browser.getJBCefClient().setProperty(JBCefClient.Properties.JS_QUERY_POOL_SIZE,100);
            CefApp.getInstance().registerSchemeHandlerFactory("http", "sourcegraph", new HttpSchemeHandlerFactory());
            browser.setPageBackgroundColor(ThemeUtil.getPanelBackgroundColorHexString());
            browser.setProperty(JBCefBrowserBase.Properties.NO_CONTEXT_MENU, Boolean.TRUE); // remove context menu

            browser.loadURL("http://sourcegraph/html/index.html");

/*Uncomment to test keyboadhandler: 

browser.getJBCefClient().addKeyboardHandler(new CefKeyboardHandler() {
                @Override
                public boolean onPreKeyEvent(CefBrowser cefBrowser, CefKeyEvent cefKeyEvent, BoolRef boolRef) {
                    return false;
                }

                @Override
                public boolean onKeyEvent(CefBrowser cefBrowser, CefKeyEvent cefKeyEvent) {
                    cefBrowser.executeJavaScript("var template=document.createElement('div');template.innerHTML='"+cefKeyEvent.character+"';document.body.appendChild(template);",cefBrowser.getURL(),0);
                    return false;
                }
            },browser.getCefBrowser());*/

            String initJSCode = "window.initializeSourcegraph(" + (ThemeUtil.isDarkTheme() ? "true" : "false") + ");";
            JSToJavaBridge jsToJavaBridge = new JSToJavaBridge(browser, requestHandler, initJSCode);
            jcefPanel.add(browser.getComponent(), BorderLayout.CENTER);
            Disposer.register(browser, jsToJavaBridge);
        }

        splitter.setFirstComponent(jcefPanel);
        splitter.setSecondComponent(previewPanel);
    }
```

This will: 

1) remove flickering (note how i first load a blank page, set the background color then load the desired one)
2) break on Linux

if you uncomment the lines starting with "Uncomment to test keyboadhandler: " you will see that the keyboard events are triggered in the CefOsrBrowser ... but they are not really captured by the input field.

**Comment by madppiper** [comment]
@vdavid I added a test - which makes it load much more gracefully (loadtime is still too long for my taste and there is still a minor flash, probably due to the way a redraw of the components is happening when i remove one of them, but it is progress): 

https://github.com/ilscipio/sourcegraph/commit/71878b98b72b3c962db73722b2318d79e2743c5c

**Comment by vdavid** [comment]
TBH I don't see any difference in the flickering. :/

**Comment by philipp-spiess** [comment]
> TBH I don't see any difference in the flickering. :/

I wonder if it would be better to wait for a custom JavaScript side event that we manually trigger once the page is rendered instead of the onload event?

**Comment by vdavid** [comment]
@madppiper's solution worked for him because he tested it on Windows.
I had actually already developed the same solution with LayoutManagers, and it was failing because of the same bug that's apparent on macOS!
So, without the bug, a JLayeredPane allows you to add components atop each other. Ones with the lower indexes cover the ones with higher indexes.
But on Mac, because of a bug, the JCEF component is always rendered on top!
[2-min demo here!](https://www.loom.com/share/e3fb60bbba9b450bb600611547a127ea)
I think it's somehow connected to the JCEF bug related to off-screen rendering.
I'll create a new issue with JetBrains about this.

I’m now trying to make the browser 1x1px then while it loads 🤷‍♂️

**Comment by vdavid** [comment]
> I wonder if it would be better to wait for a custom JavaScript side event that we manually trigger once the page is rendered instead of the onload event?

Nice, I just saw this. My thinking exactly. :) It's part of the PR above.
