### ISSUE TITLE
Improve gitserver purge worker

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#34695]
Some ideas pulled out of a [PR](https://github.com/sourcegraph/sourcegraph/pull/34693)

- [ ] Enable the purge worker on cloud and ensure it only removes repos deleted after some grace period.
- [x] Rate limit the purge worker
- [x] Add a dashboard (Added metrics to track purgeable repos)
- [x] Add a UI to manually trigger a purge (Added a basic admin area under instrumentation/repo-updater)

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.
