### ISSUE TITLE
JetBrains: Recognize dark vs light theme

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#34697]
## Problem

Our search box doesn't display right:

<img width="954" alt="CleanShot 2022-04-29 at 14 17 24@2x" src="https://user-images.githubusercontent.com/2552265/165942777-3d39358a-354b-4fd9-a010-c34ab3150474.png">

The problem is that it needs a top-level class of either `dark-theme` or `light-theme` to display right.

## Solution

There is no dark/light theme setting in IntelliJ, just one can download themes and that's it.
However, after doing some research in the theme marketplace, it shows that all themes use either use a light or a dark background for the editor. (They need to display legible text, after all.)
So, a good solution seems to be to request the editor background color from the theme, and set the <html> class dynamically based on that.
For determining light vs dark, the HSP (Highly Sensitive Poo) equation from http://alienryderflex.com/hsp.html seems like a great solution.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by vdavid** [comment]
One tiny piece is missing: the theme setting in the initialization of the <SearchBox> component is currently not dynamic.

**Comment by vdavid** [comment]
Created a separate issue for the missing piece, closing this one.
