### ISSUE TITLE
Sourcegraph should not show banner to add repos after repos are added.

### ISSUE THREAD

**Issue by francisschmaltz** [sourcegraph/sourcegraph#347]
Sourcegraph should not show the banner to "Configure repositories and code hosts
 to add to Sourcegraph" after repositories are added.

Currently, the banner will show until a token for a code host is added.

![screen shot 2018-10-09 at 11 39 58 am](https://user-images.githubusercontent.com/11583013/46690846-3ba6ac80-cbb8-11e8-917b-a75bf424df2e.png)

**Comment by nicksnyder** [comment]
This is a product question for @sqs

**Comment by sqs** [comment]
This banner is now dismissible, so this is now acceptable as-is. The work necessary to automatically hide this when you've added a repository is not worth it given the dismissibility, given that it's still useful to know you can configure code host integrations, and it's so easy to dismiss.
