### ISSUE TITLE
insights: 1 click debug information about a code insight

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#34707]
To facilitate easier support requests, I propose we build a 1 click export button on a code insight (possibly behind a debug mode? `?debug` that will export as much relevant information about the code insight (or the instance) as possible.

Some things we may want to export:
- Insight view metadata
- Insight view filters
- Insight view permissions
- Insight series metadata
- Insight series error counts (this might be tricky due to cardinality constraints)
- Debug events (tracking things like time we started backfill, time backfill finished queuing, etc)
- Backfill statistics (how many repos were queued, compressed, skipped, etc)

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by Joelkw** [comment]
Sync notes: 
- would be on top of organized queue improvements
- eventually part of admin page but could come before.

**Comment by coury-clark** [comment]
p2

**Comment by chwarwick** [comment]
p0 - I'd say p0 for at least a limited set of this.  Being able to know queue status for an insight count of jobs by status, and details of last X errors would be so much better than trying to ask for db access every time an insight fails.

**Comment by coury-clark** [comment]
lets focus on admin level visibility here (see all info):

user path is likely coming from non-admin user, does that mean we need to think about what the admin does with this info?

**Comment by chwarwick** [comment]
closed by #44113
