### ISSUE TITLE
Create CTA for users to try out new reference panel

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#34702]
We would like to collect external feedback on our new reference panel at the same time that we've enabled it for internal dogfooding. Instead of a controlled user test, we will try out a CTA to try out a beta experience of the reference panel and collect feedback. cc: @macraig @rrhyne 

- [x] Create a new (or clean up) existing issue #30227 for external use. It should include instructions for set up, as well as instructions to provide feedback directly into the issue
- [x] Create [alert inside reference panel](https://www.figma.com/file/DZMyEJT3g2HT6HmJGNNOnW/%22Better%22-code-intel-panel?node-id=1348%3A5246) that links to the external-facing issue for reference panel 
- [x] Metrics: Can we track the count of non-sourcegraph-teammate users who have enabled the feature flag? Or would we have to track count of clicks on the CTA?

**Comment by mrnugget** [comment]
Also: we will need to add an alias feature flag name that's not "coolCodeIntel" ("newReferencePanel" maybe?).
