### ISSUE TITLE
Copy query button confirmation message delayed and not aligned

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#34717]
1. Open Sourcegraph
2. Hover over copy query button on the search box
3. Click button

Expected:
Confirmation appears immediately and is aligned

Actual:
Confirmation is delayed and is not aligned

https://user-images.githubusercontent.com/206864/166068114-0aa91441-48fc-4cc0-a344-e65be82721c4.mp4

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by camdencheek** [comment]
Closing since the "Copy query" button has been removed
