### ISSUE TITLE
VSCE:  Update Create Issue links with the proper labels applied

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#34713]
# Issue

As discussed in this [Slack Thread](https://sourcegraph.slack.com/archives/C01T0BL4EFN/p1650887239718659), we are missing issues created by users as the correct labels are not applied, so the team was not notified in a timely manner. 

# Suggestion
To resolve this issue, we suggested replacing all the current issue-reporting links to a link with proper team labels applied using a URL Query ([docs](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue#creating-an-issue-from-a-url-query)). 
For example:
VSCE: https://github.com/sourcegraph/sourcegraph/issues/new?labels=team/integrations,vscode-extension&title=VSCode+Bug+report:+&projects=Integrations%20Project%20Board
JetBrains: https://github.com/sourcegraph/sourcegraph/issues/new?labels=team/integrations,jetbrains-ide&title=JetBrains:+&projects=Integrations+Project+Board/1

CC @ryankscott @jjinnii

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
