### ISSUE TITLE
VSCE: Display version number in frontend

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#34729]
Since there are instances ([link to example)](https://sourcegraph.slack.com/archives/C01LZKLRF0C/p1644624319070789?thread_ts=1644619285.987489&cid=C01LZKLRF0C) where VS Code is showing users that they are running on the latest version when they are not, it would be helpful if we can display the version number in frontend for us to confirm with users for debugging purpose.

The solution for running an older version is to [completely uninstall the extension](https://stackoverflow.com/questions/36746857/completely-uninstall-vs-code-extensions) as mentioned in the thread.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
