### ISSUE TITLE
JetBrains: Create JS→Java bridge

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#34748]
## Problem

There is no native sophisticated way to call Java from the JS and get data back.

## Solution

Use [@philipp-spiess's](https://sourcegraph.com/github.com/sourcegraph/sourcegraph-jetbrains@ps/webview/-/blob/src/main/java/com/sourcegraph/SourcegraphBridgeThread.java) and [Paul's](https://github.com/madppiper/sourcegraph-jetbrains/blob/playground/src/main/java/com/sourcegraph/ui/JCEFWindow.java#L55-L82) prototypes to create a bridge that can be called from the JS side with a simple function call and a type-safe, Promise-based interface, and get data back.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
