### ISSUE TITLE
VSCE: Document release process

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#34742]
1. We should document our release process (both before and after the update) for visibility purposes once it is finalized in  https://github.com/sourcegraph/sourcegraph/pull/34522
2. The release process and changelog are currently not available in our [handbook IDE Extensions page](https://handbook.sourcegraph.com/departments/product-engineering/engineering/cloud/integrations/ide-extensions/). 
  - The release process for the browser extension can be found [here](https://handbook.sourcegraph.com/departments/product-engineering/engineering/cloud/integrations/browser-extensions/release-process/)

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
