### ISSUE TITLE
Code Insights: Add search context filter for the FE integration test cases 

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#34751]
Follow up for https://github.com/sourcegraph/sourcegraph/pull/34620

Also in this ticket, it may make sense to catch up in unit tests around the new filter panel functionality, related comment https://github.com/sourcegraph/sourcegraph/pull/34620#discussion_r862254217

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
