### ISSUE TITLE
Code Insights: Fix "default applied filter" text appearance 

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#34752]
@AlicjaSuska originally found this issue during testing the Search Context filter's PR here https://github.com/sourcegraph/sourcegraph/pull/34620

> I've noticed one thing about 'default filters applied' message that needs correcting (probably in a separate issue):
>1. open insights with default filters applied - 'Default filters applied' text is displayed, pink dot displayed
>2. Change filters (reduce scope)  / reset filters - text should disappear (now, it's still being displayed), dot disappears

> Here is the [loom](https://www.loom.com/share/1c21be7e23574826bc4b7ae7ec1a58e3) showing what's happening and the [Figma design](https://www.figma.com/file/Ml5dtV9ni4mfffbfOfF9jg/Allow-search-contexts-as-filters-to-code-insights-(v0-%2333249-%26-v.1-%2333830)-%5Bready-for-dev%5D?node-id=1281%3A26570) (diagram) that shows the desired flow.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
