### ISSUE TITLE
Code Insights: Implement header element/control component for the independent insight page

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#34759]
## Background

[Designs](https://www.figma.com/file/Y4grZjTxnXHEQSoeB14vU1/Share-a-link-to-an-individual-code-insight-RFC-654?node-id=1228%3A16270) 

![Group 483](https://user-images.githubusercontent.com/18492575/166216810-23d1810b-a22a-4abc-93c1-12e62a3a19e2.png)

## Definition of done: 
- Implement header component  
- Action Buttons should work properly Edit, Delete, Copy link.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by felixfbecker** [comment]
(@vovakulikov TODO: split out pills into separate issue)
