### ISSUE TITLE
search: make integration testing easy and clear

### ISSUE THREAD

**Issue by ijt** [sourcegraph/sourcegraph#3475]
I would like to test the sourcegraph search system to see that it gets expected results for given sets of repos and queries. This currently involves either manual work tearing down and setting up repos in the local dev instance or writing [unit tests that have a bunch of mocks](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/search_results_test.go).

An alternative approach would be to add a new command, say `dev/srcsearch`, that runs the entire search system within a single process. This command could be used for manual testing, like this:

```
$ srcsearch --fakes=repos.json 'func main'
<graphql output for the query 'func main' on the given repositories>
```
The `repos.json` file could look like 
```
[
  { "name": "user1/project1", files: { "a.go": "...", "b.go": "..." } },
  ...
]
```
This command could have its own readable tests that would effectively be integration tests of sourcegraph search, with the added benefit that we would be able to see meaningful code coverage stats from them since everything would run in a single process.

This would help with #1005.

**Comment by ijt** [comment]
cc @keegancsmith, @nicksnyder, @ijsnow

**Comment by keegancsmith** [comment]
It isn't that clear to me why you need a file with fakes, when we could just have repos (say under github.com/sgtest). Maybe what you desire is a way to automate setting the external configs of an instance and wait for all repos to be cloned. We already have the [src-cli](https://github.com/sourcegraph/src-cli) tool which can do searches from the command line. That could be extended to support the usecase I describe above => all you need is a simple bash script.

**Comment by ijt** [comment]
Having a file with fakes means the `srcsearch` command would have to have machinery in place to create repos based on concise descriptions suitable for writing fast, readable, self-contained tests.

The src-cli tool will most likely not allow us to get the code coverage data we want.

**Comment by nicksnyder** [comment]
> I would like to test the sourcegraph search system to see that it gets expected results for given sets of repos and queries.

There are three relevant services: frontend, zoekt, searcher. Assume that all the following exist:
- Unit tests of searcher http api handler that mock out calls to gitserver (and any other external services). Test cases cover all known ways that the frontend calls search.
- Unit tests of frontend search API handler that mock out calls to searcher and zoekt (and any other external services).
- Unit tests of zoekt http API handler that cover all known ways that the frontend calls zoekt.

If all of the following existed, would that satisfy your requirements? If not, what information or requirements would be missing?

**Comment by ijt** [comment]
That might be viable. I would want to ditch the monkey-patching approach and instead spin up fake versions of the other services, defined as Go HTTP servers in the same files as the tests. The one exception would be the database. For that it would be best to inject the db layer into things that use it.

**Comment by ijt** [comment]
Even with all those unit tests I think it would be worthwhile to have tests of the whole system in a way that lets us clearly see the inputs (repos and query) and outputs (search results) without brittle technicalities.

What I'm thinking of would look something like this:

```go
func TestSearch(t *testing.T) {
	type args struct {
		repos []repo
		query string
	}
	tests := []struct {
		name    string
		args    args
		want    []result
		wantErr bool
	}{
		{
			name: "no repos and empty query returns no results",
			args: args {
				repos: nil,
				query: "",
			},
			want: []result{},
			wantErr: false,
		},
		{
			name: "tiny repo with matching query gets a result",
			args: args {
				repos: []repo{ repo { name: "a/a", files: map[string]string{"a": "a" } } },
				query: "a",
			},
			want: []result{
				result {
					fr: &fileResult	{
						// ...
					},
				},
			},
			wantErr: false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := Search(tt.args.repos, tt.args.query)
			if (err != nil) != tt.wantErr {
				t.Errorf("Search() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			if !reflect.DeepEqual(got, tt.want) {
				t.Errorf("Search() = %v, want %v", got, tt.want)
			}
		})
	}
}
```

**Comment by ijt** [comment]
A first approximation would be to have this test take a flag for an existing sourcegraph instance.

**Comment by nicksnyder** [comment]
> I would want to avoid the monkey-patching approach and instead spin up fake versions of the other services, defined as Go HTTP servers in the same files as the tests.

What monkey patching approach are you talking about? Do the fake services return fixture data?

> What I'm thinking of would look something like this:

Thanks for sharing a sketch of the tests. What does the implementation of Search look like? Does the implementation for this function live in a `_test.go` file?

Might be worthwhile to discuss in person and then document results of conversation.

**Comment by ijt** [comment]
Here is an example of quasi-monkey patching:
https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/search_results_test.go#L59

The fake services could return fixture data or do something more sophisticated depending on what we are testing.

Go doesn't actually allow monkey patching, so it's being simulated in the sourcegraph code with  global function variables that get checked and called if not nil in the functions that are being mocked.

`Search` would
* blow away any existing repos
* add the given repos
* hit the `graphqlbackend` with the given search query

**Comment by rvantonder** [comment]
Just noting that an integration test would be useful for replacer too, so some variation or extension of this is likely to happen.

**Comment by ijt** [comment]
Here's what I'm thinking for the layout: add a new command called something like `cmd/monolith` that eventually runs all of sourcegraph as a single process, but for now runs only enough for search to work.

**Comment by ijt** [comment]
I'm closing this out for now since it seems not to have been focussed enough to get it done in a reasonable amount of time. Let's see how far we can get with unit tests and mocks for now. If they aren't enough we can give something like this another go.
