### ISSUE TITLE
Code Insights: prepare separate page route for the independent insight link 

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#34758]
[Designs](https://www.figma.com/file/Y4grZjTxnXHEQSoeB14vU1/Share-a-link-to-an-individual-code-insight-RFC-654?node-id=1228%3A16270)

This is an initial issue to start work on the new page for the Code Insights app. 

Definition of done
- We have a separate route for the page
- This route can be enabled/disabled by a feature flag
- This page has minimal UI just for testing purposes

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
