### ISSUE TITLE
Code Insights: Implement UI for the dashboard pills for the independent insight page

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#34760]
[Designs](https://www.figma.com/file/Y4grZjTxnXHEQSoeB14vU1/Share-a-link-to-an-individual-code-insight-RFC-654?node-id=1228%3A16270)

![Frame 482](https://user-images.githubusercontent.com/18492575/166218038-db0d8675-804c-47fc-b3ff-293955a3326d.png)

## Definition of done 
- [Stretch] We can see these pill dashboard rows below the header on the independent dashboard page
- We have storybook stories where we can see pill components that match with our designs around these elements 

## Potential blockers: 
We currently don't have API to fetch a list of dashboards where a particular insight was included. cc @CristinaBirkel @chrismwendt @leonore do you think this is feasible to include in our GQL API?

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by felixfbecker** [comment]
Cutting pills out of scope for this iteration

**Comment by Joelkw** [comment]
Untagging the backend label because I believe the API endpoint is completed in the linked issue.
