### ISSUE TITLE
Code Insights: Implement Share by link modals on the dashboard page

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#34766]
[Designs](https://www.figma.com/file/Y4grZjTxnXHEQSoeB14vU1/Share-a-link-to-an-individual-code-insight-RFC-654?node-id=1214%3A6728)

![Group 485](https://user-images.githubusercontent.com/18492575/166222743-cd2dd07a-2a8d-45d9-b045-ad54a5892d30.png)

![Dialog](https://user-images.githubusercontent.com/18492575/166222785-2104d3d6-1203-4ad3-97cc-4f921f15b1e2.png)

![Dialog](https://user-images.githubusercontent.com/18492575/166222809-a0408bda-9b17-4395-855c-0426cf7dfb26.png)

![Content](https://user-images.githubusercontent.com/18492575/166222845-8f35b32b-8f1e-452e-a3f9-c81982026943.png)

## Definition of done
- You're able to copy link the insight share link
- Depending on dashboards visibility levels in which this insight was included we should render three different modes of share link modal UI

## Blockers
@chwarwick @leonore @CristinaBirkel We currently don't have information about dashboards that have the insight so we can't render different modes of share link modal UI. I think if we had a dashboard insight relation in the GQL API it would be possible for us to calculate all data that we're needed on the frontend. We actually have an issue where we also need this relation in the GQL API. 

https://github.com/sourcegraph/sourcegraph/issues/34760

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by Joelkw** [comment]
@vovakulikov [based on this confusion](https://sourcegraph.slack.com/archives/C0183JV3Q0Y/p1651507269381079?thread_ts=1651461139.147369&cid=C0183JV3Q0Y), I think we should update the private modal to say: 
![image](https://user-images.githubusercontent.com/11967660/166301789-9d17cf35-bc97-41ec-bc65-2b7e5653d72c.png)

[I also updated the figma](https://www.figma.com/file/Y4grZjTxnXHEQSoeB14vU1/Share-a-link-to-an-individual-code-insight-RFC-654?node-id=1214%3A6728)

> Only you can see this insight, because it's only on private dashboards. Add this insight to public dashboards to share with others.

> _The “all insights” dashboard shows you all insights available to you regardless of their visibility to others._
