### ISSUE TITLE
Code Insights: Reuse the Insight component from the dashboard page in the insight independent page

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#34762]
## Background

[Designs](https://www.figma.com/file/Y4grZjTxnXHEQSoeB14vU1/Share-a-link-to-an-individual-code-insight-RFC-654?node-id=1228%3A16270)

![Code insight](https://user-images.githubusercontent.com/18492575/166219364-55fb2c98-e878-48ff-a49b-fcc98f3b9e2a.png)

We should reuse the same insight component that we're using on the dashboard page in order to avoid increasing entropy around insight components 

## Definition of done 
- You can see the insight card on the independent insight page
- However, this issue doesn't imply that this card is connected to the filter panel above this will be done in the separate issue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
