### ISSUE TITLE
Code Insights: Extract drill down filter form into separate re-usable component

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#34761]
## Background
We have a similar design and component in the drill down filter panel UI but this component isn't ready for reusing on the independent insight page. This issue is about extracting this component and making the filter layout that we have in our designs. 

[Designs](https://www.figma.com/file/Y4grZjTxnXHEQSoeB14vU1/Share-a-link-to-an-individual-code-insight-RFC-654?node-id=1228%3A16270)

![Frame 5109](https://user-images.githubusercontent.com/18492575/166218684-a77c0d16-e6b1-4e65-af12-8dbff5e2db89.png)

## Definition of done
- You can see a proper layout of the drill-down component in the storybook stories

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
