### ISSUE TITLE
Code Insight: Connect the insight card component with filter panel component

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#34763]
## Background

This issue implies that we connect the insight card and  he drill-down filters 

[Designs](https://www.figma.com/file/Y4grZjTxnXHEQSoeB14vU1/Share-a-link-to-an-individual-code-insight-RFC-654?node-id=1228%3A16270)

![Group 484](https://user-images.githubusercontent.com/18492575/166220645-56cb730c-0230-4f54-a253-a727ef7fd7df.png)

## Definition of done

- Filters should be connected to the insight card in the same way how they are connected on the dashboard page
- For the runtime insights we won't have any filters so I assume we just won't render them cc @Joelkw (mention you just to be sure you're ok with this)

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
