### ISSUE TITLE
JetBrains: Determine list of tracking events for MVP

### ISSUE THREAD

**Issue by ryankscott** [sourcegraph/sourcegraph#34778]
We mean high-level events for analytics.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by vdavid** [comment]
Any context on this one, @ryankscott? What are "tracking events"?

**Comment by ryankscott** [comment]
I don't know what our terminology is here, but pings and/or cloud events. We need to work out what questions we want to answer and consequently what events we need to track in our analytics.

**Comment by vdavid** [comment]
Cool, added a few words to the description to clarify that it's about analytics

**Comment by vdavid** [comment]
@ryankscott is event tracking something that you want to see in v1, or can we leave this to a v1.x?

a.) Yes, definitely 1.0
b.) Let's add it as a "nice to have" for 1.0
c.) Let's leave it for later, shipped in >1.0

**Comment by ryankscott** [comment]
a) 😄 
But of course, everything is a trade-off so we can discuss.

**Comment by jjinnii** [comment]
Agreed on A 😄 Maybe @ryankscott and I can work to clarify what we consider as "A" must-have tracking events and potential "B" nice to have events.

**Comment by philipp-spiess** [comment]
We sat down today with @ryankscott  and @vdavid and defined a minimum set for our v1 release at https://docs.google.com/document/d/1ZvsSwc5oPi6Q4YVqy0DUcy-2FCGtswNxk5omxaIBld0/edit

cc @jjinnii Can you think of anything that we might be forgetting here? 🙂

**Comment by jjinnii** [comment]
Thanks @philipp-spiess ! Touched base with Ryan, and that covers everything that I would think of as critical for first release (especially given that we don't yet have individual user tracking).

**Comment by philipp-spiess** [comment]
Awesome, I think this issue can be closed then. We have noted down the required events for a v1 here: https://docs.google.com/document/d/1ZvsSwc5oPi6Q4YVqy0DUcy-2FCGtswNxk5omxaIBld0/edit#heading=h.q1u6g1p5c22o
