### ISSUE TITLE
JetBrains: Make sure the web view is not empty after closing and reopening the popup.

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#34773]
## Problem

Sometimes the web view content disappears after opening and closing the popup several times (but not always). Then it looks like this:

![CleanShot 2022-05-02 at 16 10 02@2x](https://user-images.githubusercontent.com/2552265/166248252-70b77364-124c-4892-ad55-220272f2a7bc.png)

([Video](https://www.loom.com/share/6da15ccac8244bd2993519f4c5df00e3): at 0:30) 

The console is pretty messy, so not sure if there's always a trace of an error when this happens, but it might be that uncaught errors on the Java side cause the problem.

## Solution

Make sure the web view content doesn't disappear (or is gracefully refilled), even in case of uncaught errors.
Test it with both uncaught errors on the Java-side and the JS-side.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by vdavid** [comment]
Asked Yann Cébron at JetBrains → he suggested it was probably a crash in their native code → Created [an issue](https://youtrack.jetbrains.com/issue/IDEA-293854/Disappearing-JCEF-browser-and-Main-quit-unexpectedly-error) in their tracker. Hoping to get help soon.

**Comment by vdavid** [comment]
@madppiper This is a breaking issue. The web view keeps on disappearing, which renders the plugin unusable. We’ve got no response from JetBrains on the [issue](https://youtrack.jetbrains.com/issue/IDEA-293854/Disappearing-JCEF-browser-and-Main-quit-unexpectedly-error) I created six days ago. I think we have two ways to go in solving this:
1. Figure out the cause and fix the cause
2. Find an indicator of the failure and create a solution that bridges over the problem, for example, re-render the whole thing when it fails. Currently, we get no error messages or anything, so I have no clue even how to recognize this error occurring.

Do you have any pointers on what we should look into to learn more about this problem?
(It happens on the main branch if you’d like to test it)

**Comment by madppiper** [comment]
@vdavid - sure, i'll take a look and try to reproduce. 

Just to make sure - you are running an iMac?

**Comment by vdavid** [comment]
No, MacBook Pro. But macOS, yes.

**Comment by philipp-spiess** [comment]
I tired a couple of things today on this (all without luck) but wanted to document what I tried somewhere:

1. I tried a couple different methods on the JCEFBrowser and JCEFClient to "force" a redraw, none of them worked.
2. I noticed that this only happens if a JBPopup is disposed at least once. If you remove the code to avoid opening more than one popup in total, I can repeatedly type `ctrl+a` and the browser will always "move" to the latest popover. Only if I close the popup, this failure scenario can happen.
3. I tried moving the popup creation into the UI Thread and the Write Thread. This didn't make any difference.
4. I looked for a verbose mode in the JCEF component so that we have more idea of what's going on (since there aren't any logs otherwise besides the one on the first render?) but couldn't find anything.
5. There's not an obvious API that sticks out that we could use to detect this issue happening. If you query the components of the different swing views, the hierarchy does not change. The browser and other views are also not disposed.
6. I tried to avoid the JBPopup from being disposed at all and just have it hidden. However with my swing knowledge this wasn't really something that I could make work.

**Comment by vdavid** [comment]
@philipp-spiess and I collected the next actions yesterday ([here](https://docs.google.com/document/d/1ZvsSwc5oPi6Q4YVqy0DUcy-2FCGtswNxk5omxaIBld0/edit#heading=h.rdajyfnqs3k9)).
- [ ] David: Yann: Would be nice to figure out how important this development is for JetBrains.
- [ ] David: Try to look at Mac vs Windows vs Linux percentages for JetBrains
- [ ] David: Try to install another plugin (e.g. GraphBuddy)
- [ ] David: Take one more look into the “Quit unexpectedly” error messing
- [ ] Philipp: Test on Windows and Linux
- [ ] Both: try to find some trace of the error happening
- [ ] Both: try to move the browser to the main IDE interface from the popup
- [ ] Both: try recreating the webview each time
- [ ] Both: random trials

**Comment by vdavid** [comment]
> David: Yann: Would be nice to figure out how important this development is for JetBrains.

He wrote "we are certainly much more in a (2) position w/r to your plugin"
where (1) meant "JetBrains doesn't care more about the Sourcegraph plugin than any other plugin, and (2) meant "This is of huge business importance for JetBrains because it sucks that VS Code has a Sourcegraph extension but JetBrains products don't."

> David: Try to look at Mac vs Windows vs Linux percentages for JetBrains

Yann said "I don’t think we have _public_ data on the OS distribution, but the share of Mac users is substantial"
→ So macOS is important for them and should be important for us.

He also wrote: "please bear in mind that JCEF is a rather “newish” part of our IDE and thus more prone to such problems in general"
Yeah, we noticed :D

**Comment by vdavid** [comment]
> David: Try to install another plugin (e.g. GraphBuddy)

Graph Buddy kept on erroring out, so I tested with this Open source project that uses JCEF: MarkDown editor. [GitHub](https://github.com/shuzijun/markdown-editor) [Plugin page](https://plugins.jetbrains.com/plugin/17254-markdown-editor)
The result is that this other web view is showing steadily, while ours is failing.
My guess is that the difference is not our use of JCEF, but that we're showing it in a popup. But that's just a guess, I haven't looked into his code yet. Might be worth looking into it, though.

**Comment by vdavid** [comment]
> David: Take one more look into the “Quit unexpectedly” error report

Here is the log: [Quit unexpectedly.txt](https://github.com/sourcegraph/sourcegraph/files/8737745/Quit.unexpectedly.txt)
Threads 71–81 seem to be directly related to JCEF, and thread #74 is the one that crashed.

I read through the report multiple times and tried to Google parts of it, but I am not much smarter after this. I bumped into some random off-screen rendering issues, so it's a vague reassurance that it's related to that, but it might also be just confirmation bias.
So, all in all, the only takeaway here is that the crash is related to JCEF.

**Comment by philipp-spiess** [comment]
>  Philipp: Test on Windows and Linux

I can confirm this only happens on macOS according to my tests.
