### ISSUE TITLE
Code Insights: Add more data (corner use case) mocks  for the insight card component

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#34772]
## Background

[In the 3.39 release, we had to release a patch release](https://docs.google.com/document/d/11WPnLpV6MPcLSgPWTTSP1ThHabp5QXM3spguVokktgQ/edit) because we missed a few problems that appear only in a particular set of insight data (unsorted set of data with unaligned time intervals between data points). 

To avoid this in the future we should extend our snapshot/screenshot testing with more mock data that simulate this situation with unsafe data from the backend.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
