### ISSUE TITLE
Search results Create monitor tooltip should be below the button

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#34777]
All the buttons at the top of search results have a tooltip that opens below the button, except code monitors. Change the code monitor tooltip to open below the button to be consistent. 

## Code monitor opens the tooltip below:
![image](https://user-images.githubusercontent.com/539268/166255692-4ee11485-fada-425d-afe7-8f3915cf9597.png)

## Insights and others open below:
<img width="545" alt="image" src="https://user-images.githubusercontent.com/539268/166255738-40d757e7-1bb8-40e1-84b7-b4b9bc52341b.png">

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by camdencheek** [comment]
No longer relevant with the new actions bar
