### ISSUE TITLE
VSCE Bug: Cannot open local files from search result on windows

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#34788]
- **Sourcegraph version:** V2.2.1 and 2.2.2
- **Platform information:** VS Code on Windows

#### Steps to reproduce:

1. search for files that exist in your current workspace / basepath
2. click on a search result

#### Expected behavior:
open local copy of the file

#### Actual behavior:
Remote files are open instead of local files

If would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are not [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

**Comment by abeatrix** [comment]
Current workaround: remove drive from basePath, and make sure only `/` is used instead of `\`
eg. `C:/Users/bee/Documents` => `Users/bee/Documents`

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by abeatrix** [comment]
Investigration update:

#### Root cause
The base path is not being parsed correctly:
![image](https://user-images.githubusercontent.com/68532117/167033352-471b1519-a642-4eca-92a4-ac6cee811e97.png)
![image](https://user-images.githubusercontent.com/68532117/167033369-8500167d-725c-4740-a66d-3151b70d13a8.png)

#### solution

Encode the URL as a file path using the VS Code URI API has resolved the issue:

#### TODO 
This approch has messed up the open-in-sourcegraph link where part of the file path is cut off:
https://cse-k8s.sgdev.org/github.com/sourcegraph/src-cli/-/blob/ternal/batches/service/service_test.go?L9%3A11=

"internal" has become "ternal"
