### ISSUE TITLE
Complete migrations for error monitoring

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#34795]
## Problem to solve

This roadmap item captures anticipated **migration follow-up** from the [All Sourcegraph components can easily raise runtime errors for debugging roadmap](https://github.com/sourcegraph/sourcegraph/issues/33240) work in Q2. By Q3, we expect to have:
- Agreed upon a set of conventions for how to write errors so that they 
  1. Have enough metadata to identify what component they're coming from
  2. Are easily accessed
  3. Can be reported across all instance types.
- Completed migrations for at least one service.

The bulk of the work in Q3 will be completing migrations across services. 

## Measure of success

The work from Q2 is complete and all services have been migrated. 

## Solution summary

- TODO

Artifacts:
- TODO

## What specific customers are we iterating on the problem and solution with?

Internal Sourcegraph developers and SREs. 

## Impact on use cases

This effort contributes to the company-wide effort to improve Observability.

## Delivery plan

- [ ] TODO

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by bobheadxi** [comment]
cc @jhchabran is this issue valid do you think? All of this is being taken care of via the Sentry integration, with no real action required other than migrating to the new logging library?

**Comment by bobheadxi** [comment]
I am closing this as unnecessary - in the backend, Sentry reporting is now done entirely via logging: https://docs.sourcegraph.com/dev/how-to/add_logging#automatic-error-reporting-with-sentry

This means that completing migrations for error reporting is simply completing the logging migration, which is a long-term background task we are tackling in https://github.com/sourcegraph/sourcegraph/issues/37586
