### ISSUE TITLE
JetBrains: Build a Java→JS bridge

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#34797]
## Context

We already have a JS→Java bridge.
On the Java side, we can run any JS with `cefBrowser.executeJavaScript()`.
Example use case: notifying the web view when the theme changes.

## Problem

Running _any_ JS doesn’t sound like a good idea.
If there is no planning around this, it'll likely become tough to understand what we're calling from Java and when.

## Solution
Create a dedicated interface on the Java side. It would give us a single place for JS calls, plus some type safety.
The result should probably be similar to the JS→Java bridge.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by vdavid** [comment]
Notes:
- Simple [JBCefJSQuery﻿ example](https://plugins.jetbrains.com/docs/intellij/jcef.html#jbcefjsquery)—helped a bit
- A [complex example](https://bitbucket.org/Phylanx/java-cef-jos/commits/b6ceb2bf4c7e44bdbd4a72e6642505ae1949cce5) from the [CEF forum](https://www.magpcss.org/ceforum/viewtopic.php?f=17&t=17303&start=0)
- Ways to get back a response in a non-blocking way: Using Threads, FutureTask, or CompletableFuture. ([source](https://www.baeldung.com/java-asynchronous-programming))

**Comment by vdavid** [comment]
Yes, I have an open branch for this but it's low priority so I haven't
progressed with this for a while. But I guess while I have the branch it's
in-development?
