### ISSUE TITLE
All Sourcegraph components can export standardized traces

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#34796]
## Problem to solve

This roadmap item captures anticipated **tracing follow-up** from the [All Sourcegraph components can easily raise runtime errors for debugging roadmap](https://github.com/sourcegraph/sourcegraph/issues/33240) work in Q2. 

## Measure of success

- TODO

## Solution summary

- TODO

Artifacts:
- TODO

## What specific customers are we iterating on the problem and solution with?

- TODO

## Impact on use cases

This effort contributes to the company-wide effort to improve Observability.

## Delivery plan

- [ ] TODO

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by bobheadxi** [comment]
Closing in favour of the simpler https://github.com/sourcegraph/sourcegraph/issues/27386 for now - we can recreate a tracking issue later if needed
