### ISSUE TITLE
insights: add new graphql field to InsightView with list of dashboards the InsightView has been added to

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#34791]
In the graphql schema add a new field to the `InsightView` type called `dashboards` which contains a list of `InsightsDashboardConnection` the current insightview is present on.

Acceptance Criteria:
The list of dashboards should be should be security trimmed to only show the dashboards the current user has access to.
The list of dashboards should be pageable using the `after` and `first` arguments like [`views` on `InsightsDashboard`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/insights.graphql?L271:5#tab=def)

blocks #34766
blocks #34759
blocks #34760

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
