### ISSUE TITLE
Code intel sometimes doesn't work on GitHub PRs

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#3480]
- Visit https://github.com/sourcegraph/sourcegraph/pull/3221
- Hover on some tokens
- Notice this console error:

![image (15)](https://user-images.githubusercontent.com/1387653/56327861-25fadc80-6131-11e9-95cc-48520eeba250.png)

Original Slack discussion: https://sourcegraph.slack.com/archives/C07KZF47K/p1555544943062900

**Comment by beyang** [comment]
Note that on hard refresh, it works, and on subsequent page loads, it seems to work as well. Smells like a race condition?
