### ISSUE TITLE
CodeCov Extension does not work as expected

### ISSUE THREAD

**Issue by topebali** [sourcegraph/sourcegraph#34818]
- **Sourcegraph version:** v3.39 and sourcegraph.com
- **Platform information:** 

#### Steps to reproduce:

1. Install [Sourcegraph for Chrome](https://chrome.google.com/webstore/detail/sourcegraph/dgjhfomjieaadpoljlnidmbgkdffpack)
2. [Enable the Codecov extension on Sourcegraph](https://sourcegraph.com/extensions/sourcegraph/codecov)
3. Visit [tuf_store.go in theupdateframework/notary on GitHub](https://github.com/theupdateframework/notary/blob/master/server/storage/tuf_store.go) (or any other file in a public repository that has Codecov code coverage)
4. Create a fork of that repo, Index it on sourcegraph. 

#### Expected behavior:
1. Codecov to work on a forked repo.

#### Actual behavior:
1. Codecov does not work on forked repo.
2. In screenshot 1: the repo is not found on cse-k8 and codecov appears.
3. In screenshot 2: the repo is found on [sourcegraph.com](http://sourcegraph.com/) but codecov does not appear.
![image](https://user-images.githubusercontent.com/38654489/166436433-0e6b4f64-b762-4bcb-a79a-66d0754cc807.png)
![image](https://user-images.githubusercontent.com/38654489/166436466-03b2dfa4-4246-4dc7-bd7a-a9fa96fe13dc.png)

I would like to also ask, does codecov extension works in the sourcegraph cloud?

If would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are not [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by taras-yemets** [comment]
Hi @topebali 👋🏻 
Thank you for reporting it!

> I would like to also ask, does codecov extension works in the sourcegraph cloud?
Yes, it is expected to work on Sourcegraph Cloud.

> In screenshot 2: the repo is found on [sourcegraph.com](http://sourcegraph.com/) but codecov does not appear.
Is codecov extension enabled for your account?

**Comment by topebali** [comment]
Hi @taras-yemets 
Thank you so much for looking into this.
So it works on the original repository when the extension is enabled [screenshot2] but it does not work on a fork of the repo [screenshot1].
<img width="1541" alt="image" src="https://user-images.githubusercontent.com/38654489/166446419-316c3b4e-aefe-4b14-9c5d-963525722cfb.png">
<img width="1521" alt="image" src="https://user-images.githubusercontent.com/38654489/166446508-13a5ba65-a583-4a38-af6f-eb0bbf77e260.png">

Is it expected not to work on a forked repo?

Thank you for confirming its expected to work in cloud, I believe the instructions to follow for cloud is the instructions for the **[With private GitHub.com repositories](https://sourcegraph.com/extensions/sourcegraph/codecov)** right?

**Comment by taras-yemets** [comment]
@topebali 

> the instructions to follow for cloud is the instructions for the [With private GitHub.com repositories](https://sourcegraph.com/extensions/sourcegraph/codecov) right?

Yes, correct. But it's worth mentioning that it may take some time to sync repository coverage data (see [this comment](https://github.com/sourcegraph/sourcegraph/issues/32445#issuecomment-1094964603)). 

> Is it expected not to work on a forked repo?

I suppose that as long as the forked repo is synced with the corresponding codecov.io profile I'd expect codecov extension to work. Is it correct, @tjkandala?

**Comment by topebali** [comment]
> Yes, correct. But it's worth mentioning that it may take some time to sync repository coverage data (see https://github.com/sourcegraph/sourcegraph/issues/32445#issuecomment-1094964603).

@taras-yemets thanks for this! 
So if I understand this correctly, Zcodecov isn't going to work on the forked repo without some form of  configuration between the forked repo and the corresponding codecov.io profile from the original repo so codecov can appear on the forked repo as well right?

**Comment by taras-yemets** [comment]
> codecov isn't going to work on the forked repo without some form of configuration between the forked repo and the corresponding codecov.io profile from the original repo so codecov can appear on the forked repo as well

@topebali, yes, correct. It can be either codecov.io profile used for the original repo if that codecov.io profile has proper access right to the forked (new) repository, or another codecov.io profile. 
For example, I forked [notaryproject/notary](https://github.com/notaryproject/notary) repo yesterday and it appeared in "Not yet setup" tab of my codecov.io profile (I have all my repos synced with it).
![image](https://user-images.githubusercontent.com/25318659/166663522-05425333-66e6-4cd5-a709-e0a90c18ebaa.png)
Clicking 'setup' on my fork navigated me to [this instruction](https://app.codecov.io/gh/sourcegraph/about/new).

**Comment by taras-yemets** [comment]
Hey @topebali,

> Is this expected behavior, that codecov does not integrate so well with the sourcegraph firefox browser extension?

Firefox extension doesn't support codecov. We can't run remote scripts on Firefox ([RFC 173](https://docs.google.com/document/d/1YN9xdRD7RhAkCrR2RYbIQpYrC_wrVNteuzp_nCguuoI/edit)) and workaround this issue by bundling code-intel extension only. Bundling codecov extension was also discussed in the RFC, but it hasn't been implemented yet.

> The customer sees value in sourcegraph and this is a potential blocker for them if codecov does not work so well in firefox, is this going to be an easy fix?

It seems a relatively easy fix given that we already have the code-intel working example.

**Comment by topebali** [comment]
@taras-yemets I really appreciate this insightful feedback. Considering this RFC is 2 years old, I would assume there is no  ETA for fix right? I basically want to know what expectations I should be setting for the customer. Thanks!
