### ISSUE TITLE
JetBrains: Get rid of the "Quit unexpectedly" error when closing the IDE

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#34813]
https://www.loom.com/share/6da15ccac8244bd2993519f4c5df00e3

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by vdavid** [comment]
@madppiper gave you access to the Loom.

**Comment by vdavid** [comment]
Asked Yann Cébron at JetBrains → he suggested it was probably a crash in their native code → Created [an issue](https://youtrack.jetbrains.com/issue/IDEA-293854/Disappearing-JCEF-browser-and-Main-quit-unexpectedly-error) in their tracker. Hoping to get help soon.

**Comment by vdavid** [comment]
https://github.com/sourcegraph/sourcegraph/pull/35788 seems to have fixed this! I can't reproduce it anymore on the current `main`!
