### ISSUE TITLE
JetBrains: Update web view theme when the theme changes

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#34812]
## Context

We currently check the theme at the web view start and apply some CSS to make it fit in.

## Problem

The user might change the theme later. If the web view doesn't adjust accordingly, it'll look out of place.

## Solution

Listen to theme change events.
Create a way to elegantly call the JS from a Java. (https://github.com/sourcegraph/sourcegraph/issues/34797 should help)
Call JS when the theme changes.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
