### ISSUE TITLE
perf: rewrite search regexes to make all groups non-capturing

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#34826]
The go regex engine is much faster at running a regex when a group is non-capturing. Given both searcher and zoekt never do captures, we can rewrite any regex we run to ensure all groups are non-capturing.

I've labelled this as a good first issue since in general work like this requires a focussed change (just doing some work with go's regexp/syntax) and the places to change in the code are very targetted in both zoekt and searcher.

For more context see https://github.com/sourcegraph/sourcegraph/pull/34683 and https://app.slack.com/client/T02FSM7DL/C020S8AT3LN/thread/C020S8AT3LN-1651194738.322429

**Comment by sourcegraph-bot-2** [comment]
Heads up @jjeffwarner - the "team/search-core" label was applied to this issue.

**Comment by keegancsmith** [comment]
FYI @jjeffwarner this is likely a good self contained onboarding task.

**Comment by keegancsmith** [comment]
FYI @jac and I hacked a little bit on this, this morning.

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket, please let us know how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
