### ISSUE TITLE
VSCE: Update feedback link to new discussion topic

### ISSUE THREAD

**Issue by ryankscott** [sourcegraph/sourcegraph#34822]
When you click the "Give feedback" button you're taken to our general discussion area. I've created a discussion topic for our VS Code extension that we should link to instead:

https://github.com/sourcegraph/sourcegraph/discussions/34821

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by abeatrix** [comment]
Added in https://github.com/sourcegraph/sourcegraph/pull/34930
Will be included in the next patch release: 2.2.3
