### ISSUE TITLE
VSCE: Work out best way to get added to a repositories / workspace recommended extensions

### ISSUE THREAD

**Issue by ryankscott** [sourcegraph/sourcegraph#34829]
One way we might be able to gain adoption within an organization is to be added to the [workspace's recommended extensions](https://code.visualstudio.com/docs/editor/extension-marketplace#_workspace-recommended-extensions).

I'm not sure the best way about doing this? For example we could:
- Recommend this as part of the CE onboarding of our customers
- Add it as an example batch change
- Suggest it as an action post-installation

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by abeatrix** [comment]
@ryankscott We can create a button (maybe in the help and feedback sidebar) that could add our extension to the `extensions.json` in the `.vscode` folder if that helps? Other than that working with the CEs on this makes sense too.

**Comment by ryankscott** [comment]
Could we utilise the [onStartupFinished](https://code.visualstudio.com/api/references/activation-events#onStartupFinished) event and do a one-time ask if you'd like to added it to the recommended extensions?

**Comment by abeatrix** [comment]
Yea we can! like a CTA on the homepage where it won't show up again if they have dismissed once, or do we keep showing the CTA every time they start SG in VS Code?

**Comment by ryankscott** [comment]
Definitely only once :) I'm not sure where this is best suited, if it's an alert or something else. Perhaps we can wait until @jjinnii is back.

**Comment by abeatrix** [comment]
Sounds good! If this is the case I will move this to the next interaction then and wait for @jjinnii

**Comment by jjinnii** [comment]
Sorry if this is my shallow understanding of what workspace means at VS Code. I've read through the docs but still find it a little confusing. Who would be our target user for showing this CTA? And what impact would one user adding it to the recommended extensions have on other users? 

For example, is the expected user flow that any VS Code user (not necessarily a system admin or tech ops admin) can click on a CTA to add our extension to "their" workplace, and this action would add our extension to recommended extensions for everyone in their workspace? (my assumption here is that our customers would have shared workspaces with their coworkers so the impact would be for everyone in the organization?)

cc: @abeatrix

**Comment by jjinnii** [comment]
Okay thanks @abeatrix! 

In the above thread when you and Ryan were talking about making this a one-time CTA, I think we were talking about making sure if a user dismisses it, it doesn't come back again. What about if one user in that workplace (or in that repository) clicks "Add to workplace"- can we recognize this and stop showing this CTA to everyone in that workspace?

**Comment by abeatrix** [comment]
Yea I believe that can be done. We can first check if Sourcegraph exists in that file, if it doesn't, we will check if the user has clicked dismiss it before, and then display the notification if both of them are false --does this make sense?

**Comment by jjinnii** [comment]
> first check if Sourcegraph exists in that file

Exists in that file meaning exists as recommended in that workplace, not that the individual user has the extension installed right? This was my thought on the behavior: 

* We _want_ to show the CTA for users who have installed the extension, but the extension is not yet listed as recommended in their workplace
* We don't want to show the CTA for users who installed the extension, but the extension is already listed as recommended in their workplace
* We don't want to show the CTA for users who don't have the extension installed, but the extension is already listed as recommended in their workplace

cc: @abeatrix

**Comment by abeatrix** [comment]
Yup! Once sourcegraph is added to their recommendation list, VS Code will take care of the rest automatically (ask them if they want to install the recommended extensions, and won't ask them if they already have etc). I think the part we will need to take care of is to ask if the user want to add our extension to their recommendation list if it is not already in it.

**Comment by jjinnii** [comment]
Sounds good to me! This sounds like a great way to promote usage for our customers 😄

**Comment by abeatrix** [comment]
Released in the latest version of vsce v2.2.3
