### ISSUE TITLE
When using CodeMirror, search patterns have literal highlighting and hovers on page load

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#34824]
- **Sourcegraph version:** Cloud
- **Platform information:** Safari 15.4

⚠️ CodeMirror feature flag turned on (`"editor": "codemirror6"`)

#### Steps to reproduce:

1. Navigate to [this link](https://sourcegraph.com/search?q=context:global+file:BUILD%24+%40bazel_tools.*javac+-repo:bazelbuild/bazel&patternType=regexp&case=yes)
2. Witness the query's patternType is `regex`, and the regex toggle state is correct. 
3. Witness the pattern, `@bazel_tools.*javac`, has literal syntax highlighting and hovers

<img width="314" alt="image" src="https://user-images.githubusercontent.com/1741180/166459280-7d01ac0b-0f15-46bf-9ef9-5e850eefa05e.png">

4. Toggle regex off, then on again. 
5. Witness the pattern now has correct highlighting + hovers. 

<img width="436" alt="image" src="https://user-images.githubusercontent.com/1741180/166459631-f7eb1dba-bb97-4fa3-a386-bff08346180d.png">

#### Expected behavior:

Pattern is correctly highlighted as regex on page load.

#### Actual behavior:

Pattern is incorrectly highlighted on page load when using `"editor": "codemirror6"`

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by lguychard** [comment]
I know, `sourcegraph-bot-2`, I created it 🙄
