### ISSUE TITLE
Make UI work when batch changes have 10,000 changesets

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#34846]
Scope needed.
Need to determine:
- what are the technical limitations of the frontend we want to fix to support 10,000 changesets
- what UX improvements need to be made to support 10,000 changesets

**Comment by eseliger** [comment]
This has probably two angles
- Technical
- UX

where "technical" is probably mostly performance-related (ie. things don't resolve at all for large numbers of changesets)
