### ISSUE TITLE
G.L  onboarding issue

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#34850]
#### Week 1-2

- [x] Make sure you went through [software engineer onboarding](https://about.sourcegraph.com/handbook/engineering/onboarding/software-engineer-onboarding).
- [x] Set up a backend development intro session with @ggilmore 
- [x] Improve the team's onboarding docs 

#### Week 2-3

Get started with some smaller tasks

- [ ] https://github.com/sourcegraph/sourcegraph/issues/34950 
- [x] https://github.com/sourcegraph/sourcegraph/issues/34951

#### Week 3-4

Incremental indexing themed

- [x] https://github.com/sourcegraph/sourcegraph/issues/36330 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/36332
- [ ] https://github.com/sourcegraph/sourcegraph/issues/32922 
- [ ] https://github.com/sourcegraph/sourcegraph/issues/32921

**Comment by sourcegraph-bot-2** [comment]
Heads up @jjeffwarner - the "team/search-core" label was applied to this issue.

**Comment by jjeffwarner** [comment]
@gl-srgr can we close this?

**Comment by ggilmore** [comment]
Yes, this can be closed.
