### ISSUE TITLE
VSCE: extension is broken by the new search components

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#34856]
The new search components  (CommitSearchResult and RepoSearchResult) introduced to our main branch ([PR](https://github.com/sourcegraph/sourcegraph/pull/34804)) is breaking the VS Code extension as we are currently importing the old search component ( [SearchResult](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@v3.39.1/-/blob/client/vscode/webpack.config.js?L145&utm_source=chrome-extension&utm_campaign=open-on-sourcegraph) ) that has been split into two different components (CommitSearchResult and RepoSearchResult):
![image](https://user-images.githubusercontent.com/68532117/166574254-bed90fd1-411e-481b-9a51-8c0d22ea2fff.png)

Build failed at:
https://buildkite.com/sourcegraph/sourcegraph/builds/145545#76716825-de2f-4e48-a97a-ead3dbf4390a

This has led to VS Code Integration test failing in the main pipeline: Slack [thread 1](https://sourcegraph.slack.com/archives/C02FLQDD3TQ/p1651596263461169), [thread 2](https://sourcegraph.slack.com/archives/C01LZKLRF0C/p1651596204763489) blocked the new search components to be added to main. As a result, we have now removed the VS Code Integration test from the main pipeline ([PR](https://github.com/sourcegraph/sourcegraph/commit/f196a44f65f8da02b0b5ddf48514689297147208)) and disabled the nightly test from running in main until the extension has been updated using the new search components.

![image](https://user-images.githubusercontent.com/68532117/166573974-ec9a7b06-6ec5-41d2-af44-bef4e672a5a2.png)

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
