### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by amir4q** [sourcegraph/sourcegraph#34872]
- **Sourcegraph version:** 
- **Platform information:** 

#### Steps to reproduce:

1.
2.

#### Actual behavior:

If would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are not [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

**Comment by jdorfman** [comment]
Closing this. Reopen if needed.
