### ISSUE TITLE
Enforce compute limit usage for batch changes executors on managed instances

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#34879]
The Beta phase of server-side batch changes on managed instances requires us the teammate standing up the instance to:
- enforce a compute-minute usage limit for customers (setup as a config when deploying the instance)
- enforce a compute-minute usage limit per user, to avoid a given user eating up all the quota

#### Scope (needs validation by cloud devops)

- [ ] define and document a process for a CE to communicate the compute-usage limit to cloud devops when standing up the instance (in this [issue](https://github.com/sourcegraph/customer/issues/new?assignees=&labels=team%2Fdevops%2C+mi&template=new_managed_instance.md&title=) most likely)
- [ ] as part of the managed instance deployment, executors compute usage limits can be set
- [ ] users can view compute credits left in the interface
- [ ] when compute-limit is reached, site-admin gets alerted

**Comment by eseliger** [comment]
"The beta phase requires" - so this is blocking beta? Can we scope this out, please? Happy to sync on this.

**Comment by eseliger** [comment]
IMO all required for this ticket is done so closing it. We effectively limit spend by limiting the number of executors spawned per MI.
