### ISSUE TITLE
Integrate Phabricator with new syncer

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#3490]
- [ ] Integrate Phabricator with new syncer
  - [x] Unified Phabricator client #3533
  - [ ] Implement PhabricatorSource and enable new syncer for Phabricator external services
  - [ ] Implement `phabricator.exclude`.
  - [ ] Update UI to remove enabled state for Phabricator repos.
  - [ ] Update UI to remove explicit deletion for Phabricator repos.

Follow up on #2025
Part of #3467

**Comment by tsenart** [comment]
It seems that we store Phabricator repos separately from other repos in the `phabricator_repos` table. 

In Slack, @beyang said this:
> I don't believe `phabricator_repos` is actually written to as part of the Phabricator external service. I believe it holds metadata that is actually generated by the Gitolite external service. It exists, because https://app.hubspot.com/contacts/2762526/company/464956351 wanted to link repos on Sourcegraph to repos on Phabricator (which is not their code host, but merely their code review tool)

We actually store repos in this table from both the Gitolite and Phabricator integrations, but in Gitolite we store both in the normal repos table and in the phabricator_repos one.

This should be cleaned-up to work with the new Syncer.

Would it be possible for https://app.hubspot.com/contacts/2762526/company/464956351 to configure a Phabricator external service rather than a Gitolite one? I'm wondering if the Phabricator API returns clone URLs of the actual code host, in this case, Gitolite.

**Comment by tsenart** [comment]
Additionally, should get rid of this difference between Phabricator repos and other repos.

https://sourcegraph.com/search?q=repo:%5Egithub.com/sourcegraph/sourcegraph%24+PhabricatorRepo#5

**Comment by beyang** [comment]
https://app.hubspot.com/contacts/2762526/company/464956351 had the following issues:
- Couldn’t provide us network connectivity to their Phabricator instance
- Couldn’t obtain the conduit token needed to hit the Phabricator API (and we’d need to verify the API return value will let us map us back to the source gitolite repo)

I will check if the situation has changed for them at all.

**Comment by tsenart** [comment]
Some more notes on my archaeological expedition into our Phabricator integration.

1. It seems that Phabricator repos don't show up on the site admin repos listing page.
2. It seems that Phabricator repos don't show up on search results.

This is all due to Phabricator repos being created only on the `phabricator_repos` table. It seems to me that the only Sourcegraph feature working with the Phabricator integration is code intelligence.

**Comment by tsenart** [comment]
It seems that we have two Go Phabricator clients.

1. https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/pkg/phabricator/phabricator.go
2. https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/repo-updater/repos/phabricator.go

I'm going to consolidate those two into `pkg/extsvc/phabricator` and use https://github.com/uber/gonduit instead of building our own.

To that end, I opened two PRs upstream to support our use case:
- Introduce basic context.Context compatibility (https://github.com/uber/gonduit/pull/8)
- core: Parameterise Client on ClientOptions (https://github.com/uber/gonduit/pull/7)

**Comment by tsenart** [comment]
More findings: Despite us [claiming that the browser extension works with Phabricator](https://docs.sourcegraph.com/integration/phabricator#browser-extension), it doesn't seem to work at all. I suppose that https://app.hubspot.com/contacts/2762526/company/464956351 and https://app.hubspot.com/contacts/2762526/company/565067980 have the [Native Extension](https://docs.sourcegraph.com/admin/external_service/phabricator#native-extension) installed, or they wouldn't be getting code intelligence.

cc @sqs @beyang

**Comment by beyang** [comment]
https://app.hubspot.com/contacts/2762526/company/464956351 has it installed natively, but I'm not sure what the state of GRAIL is. @KattMingMing might know?

**Comment by keegancsmith** [comment]
@ijsnow did we ever support Phabricator outside of the native extension? I don't think we ever did, so this is a bug in our documentation + the design of when we added the external services UI.

The easiest fix here is to just remove phabricator from the external service UI and update the docs. We can then only rely on the gitolite field for linking repositories to phabricator.

However, if our customers could instead switch to using a 1st class Phabricator external service that is much nicer and would remove technical debt. We would likely get better repository names out of it as well, since most users who use phabricator probably interact with the names Phabricator uses rather than the clone urls of gitolite. (Open question about breaking existing URLs / repo filters in saved searches).

So depending on the amount of work this is we should make decision between the two options above. I do believe there is some risk in breaking existing customers on switching to 1st class Phab support. Given that, we should work closely with the TAM to get a really good idea of what conduit returns for the user and what would change for the customers.

**Comment by sqs** [comment]
> @ijsnow did we ever support Phabricator outside of the native extension? I don't think we ever did, so this is a bug in our documentation + the design of when we added the external services UI.

When I was writing https://docs.sourcegraph.com/integration/phabricator and https://docs.sourcegraph.com/admin/external_service/phabricator#repository-syncing-and-linking, I intended to convey that Phabricator was different, but clearly this failed. I just pushed up a PR to clarify this at https://github.com/sourcegraph/sourcegraph/pull/3676.

Same with the external services UI, which says "Phabricator **connection**" and "Add links ..." not "Add Phabricator repositories", but I clarified that, too, in the PR.

![image](https://user-images.githubusercontent.com/1976/56959764-7136c700-6b03-11e9-9750-6f9b03c79f8e.png)

**Comment by keegancsmith** [comment]
I believe the decision we made for 3.4 was to just "port" the hack to the new syncer. I don't think we plan on creating a first class phabricator integration any time soon (unless customer priorities change).
