### ISSUE TITLE
Support allowSignup attribute for GitLab

### ISSUE THREAD

**Issue by miveronese** [sourcegraph/sourcegraph#34917]
We currently support allowSignup for the following auth providers:[ Github, OpenID, Builtin and SAML](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/schema/schema.go?L396). The goal of this task is to support this attribute also for GitLab.

**Comment by unknwon** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IAM-627aebcc9f8b7c00128a8ab6/issues/sourcegraph/sourcegraph/34917?planning-poker) with ZenHub @ryphil

**Comment by miveronese** [comment]
Feature added by this PR: https://github.com/sourcegraph/sourcegraph/pull/36202

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.
