### ISSUE TITLE
Support filtering users in the SAML auth provider by LDAP group membership

### ISSUE THREAD

**Issue by miveronese** [sourcegraph/sourcegraph#34918]
In our current SAML implementation, when a user logs in/tries to sign up, our backend receives, from our customers Identity Providers (via a POST request to the /acs endpoint), an XML file  that contains  information such as username, email and display name. But we can retrieve more information and use this information to grant/limit access to Sourcegraph.

Options:
- the user object could have an extra attribute such as "sourcegraph: true" 
- or we could use other field (added as an attribute statement, for example) that the user defines and translates to truth

References:
Okta - supports  Attribute Stamens and also [Group Statements](https://help.okta.com/en/prod/Content/Topics/Apps/Apps_App_Integration_Wizard_SAML.htm#)
[OneLogin](https://developers.onelogin.com/saml/examples/response), [Azure AD](https://docs.microsoft.com/en-us/azure/active-directory/develop/single-sign-on-saml-protocol#attributestatement), [PingOne](https://docs.pingidentity.com/bundle/pingfederate-103/page/nuc1564003013480.html), [AD FS](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-saml-claims-customization) also allow users to  add Attribute Statements.

Subtasks:

- [ ] Determine how we want to add additional attributes to the user object for SAML
- [ ] Do the actual filtering of users for SAML (before the actual user object is created in the database)
- [ ] Make the filter configurable with site config, similar to how we can filter github orgs

**Comment by unknwon** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IAM-627aebcc9f8b7c00128a8ab6/issues/sourcegraph/sourcegraph/34918?planning-poker) with ZenHub @ryphil

**Comment by kopancek** [comment]
I see 3 subtasks in this issue at the moment, each of them can be probably worked separately:
- [ ] Determine how we want to add additional attributes to the user object for SAML
- [ ] Do the actual filtering of users for SAML (before the actual user object is created in the database)
- [ ] Make the filter configurable with site config, similar to how we can filter github orgs

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.

**Comment by eseliger** [comment]
@pjlast this ticket has a merged PR attached but is not closed, any chance you recall if there's any additional work required?

**Comment by pjlast** [comment]
@eseliger I think this can be closed
