### ISSUE TITLE
Code views fail to be handled in Firefox: TypeError: "'requestAnimationFrame' called on an object that does not implement interface Window."

### ISSUE THREAD

**Issue by ijsnow** [sourcegraph/sourcegraph#3492]
- **Sourcegraph version:** 
- **Platform information:** Mac, [Firefox developer edition](https://www.mozilla.org/en-US/firefox/developer/)

#### Steps to reproduce:

1. With the extension enabled and pointing at sourcegraph.com, [open a PR.](https://github.com/sourcegraph/sourcegraph/pull/3337/files)

#### Expected behavior:

Code intelligence to work, links to be injected for code view, etc.

#### Actual behavior:

Nothing happens for code views. See this error in console: 

> TypeError: "'requestAnimationFrame' called on an object that does not implement interface Window."

This is probably coming from rxjs. [This line seems to be assigning requestAnimationFrame to something](https://sourcegraph.com/github.com/ReactiveX/rxjs@a9c87f6/-/blob/src/internal/scheduler/AnimationFrameAction.ts#L27:58) and FF seems to not like it, probably because of binding.

We may just be able to remove the [animation frame scheduler.](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/browser/src/libs/code_intelligence/code_intelligence.tsx#L489:19) I know there has been a lot of refactoring/perf work done since I added it.

**Comment by lguychard** [comment]
This is fixed now.
