### ISSUE TITLE
Suggestion : Filename-path + query-string searches

### ISSUE THREAD

**Issue by dwgillies** [sourcegraph/sourcegraph#3493]
#### Feature request description

In a previous jobs using a tool called codesearch, you could enter searches like this:

lyft/etl  "string I want to find"

And it would search below that directory tree for "string I want to find" (exact match).  Or alternately

filename.py  NotMyFunction

again, it would query all filename.py files for the word NotMyFunction.  It would be awesome if sourcegraph could support this kind of searching.  Two huge benefits of this functionality:

(1) I often know the right subtree or a directory fragment of the subtree for a search query, but don't want to bother with 3-8 clicks to navigate to the subtree-specific search page for that search; this is a speedup.  Imho it's a hassle to have to type file:xyz everywhere.

(2) I often want to put code links in email announcements or documentation/.md files.  I know it's possible to use a sourcegraph file search, with a line number in the URL, but that line might be valid for weeks or even days, at most  As more and more code is checked in, or if the code is refactored, my url link will become out of date.  So instead, I use a search like the second search above to pinpoint a file, and then using unique symbols nearby my link, I nail it down to e.g. a function name, so even if the file is completely refactored and/or moved around in the directory tree, the link will still be correct.

#### Is your feature request related to a problem? If so, please describe.

N/A

#### Describe alternatives you've considered.

For both use cases, I do not know a better way to support the feature.

#### Additional context

**Comment by sqs** [comment]
Thanks for posting these!

There are some features of Sourcegraph that may solve your problems.

- The `file:` (alias `f:`) keyword in searches lets you filter by file path. For example, https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/lyft/amundsenfrontendlibrary%24+f:mod+previewdata finds lines containing `previewdata` in `amundsen_application/models/preview_data.py`. I could also have typed `f:models`, but `f:mod` is even shorter and I guessed that it would be unambiguous.

  The `repo:` (`r:`) keyword works the same way. The <kbd>?</kbd> button next to the **Search** button shows all these (or if on an older version, just read https://docs.sourcegraph.com/user/search/queries): 
![image](https://user-images.githubusercontent.com/1976/56399208-88231280-6201-11e9-930e-6d3ddcf80c3f.png)

  So you could type `f:etl string i want to find` (or `r:etl` if `etl` is a repository name), or `f:filename.py NotMyFunction`. Does this address your problem? (We could also try to recognize filenames/paths without `f:`, but so far we've leaned toward being explicit. If you'd prefer we be smarter here, let me know.)
- For permalinks, you can press `y` or click the `Permalink` (link) icon in the file header to go to the permanent URL for the file line/range you're looking at, with the full Git SHA. For example, from https://sourcegraph.com/github.com/lyft/amundsenfrontendlibrary/-/blob/docs/configuration.md?view=code#L8, press <kbd>y</kbd>, and you are taken to https://sourcegraph.com/github.com/lyft/amundsenfrontendlibrary@5b8db1f612756f6bd271966bda0cbbf80bab1176/-/blob/docs/configuration.md?view=code#L8.

  Of course, this means that visitors won't see any newer changes to the file. Do you want a way to link to the *current* version of the file, but to a specific line/range that is identified not by line number (which can change) but rather by some search query? That would be a great feature--let me know!

**Comment by dwgillies** [comment]
OMG I didn't realize that file: could be abbreviated as f:, thanks!  So I can type f:some/dir/path xyz and it will search for xyz under some/dir/path directory?

**Comment by aneeshusa** [comment]
@dwgillies is something like https://sourcegraph.lyft.net/search?q=r:lyft/etl+f:mac+%22test_s3_location%22 what you are looking for? If not, can you expand on what additionally you would be looking for?

**Comment by lguychard** [comment]
This is stale, and the replies appear to solve the original request.
