### ISSUE TITLE
Introduce ability for admins to control user sign-ups

### ISSUE THREAD

**Issue by ryphil** [sourcegraph/sourcegraph#34934]
## Problem to solve
Today, Sourcegraph does not provide administrators the ability to specify who can and cannot sign up for Sourcegraph, yet this functionality is critical for customers who want to adopt a land-and-expand strategy for adoption within their organization. 

## Measure of success
Administrators have the ability to limit sign-ups of users based on a group defined in customer's identity providers. For example, Sourcegraph should provide admins the ability to limit sign-ups based on a GitHub organization or AD group. 

Respective entitlements should be reflected in Sourcegraph within X minutes of being updated in the identity provider (exact SLA for updates is being validated with users). 

## Solution summary
TBD.

## Delivery plan

**Comment by ryphil** [comment]
Over the past month, we’ve organically added support for filtering users by [github teams](https://docs.sourcegraph.com/admin/auth#how-to-control-user-sign-up-and-sign-in-with-github-auth-provider), [gitlab groups and subgroups](https://docs.sourcegraph.com/admin/auth#how-to-control-user-sign-up-and-sign-in-with-github-auth-provider) and [SAML group membership](https://docs.sourcegraph.com/admin/auth/saml#how-to-control-user-sign-up-and-sign-in).

The long term plan for this work can be found in [RFC 707](https://docs.google.com/document/d/1bNL1zVoWO3wpi3z83kajHtBZ5sKZxEC_9P3CTKuPB5w/edit#).

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.
