### ISSUE TITLE
Define technical vision for a unified permissions model across Sourcegraph features

### ISSUE THREAD

**Issue by ryphil** [sourcegraph/sourcegraph#34938]
## Problem to solve
Today, nearly all Sourcegraph features (Code insights, batch changes, search notebooks, etc) have unique, custom permissions models, creating confusion for users and preventing cross-feature use cases from being developed. 

A full breakdown of our existing permissions models across features can be found in the [working RFC.](https://docs.google.com/document/d/1B3A-PQTykOSnp6BtHZTbIFpSRrvbiV-0FrnukJeaM3A/edit#)

## Measure of success
A documented and agreed upon technical plan to implement a unified permissions model across Sourcegraph. 

## Solution summary
TBD.

## Delivery plan

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.

**Comment by ryphil** [comment]
Closing this ticket as this work has been paused for Q2FY23.

For Sourcegraph employees, the latest proposal can be found [here](https://docs.google.com/document/d/1-FhtXfIAJJp6Tfcgp4-U1wQ6vRzXDSRhxRQgf562rJE/edit).
