### ISSUE TITLE
MVP of the unified feature permissions layer across Sourcegraph

### ISSUE THREAD

**Issue by ryphil** [sourcegraph/sourcegraph#34939]
## Problem to solve
Today, nearly all Sourcegraph features (Code insights, batch changes, search notebooks, etc) have unique, custom permissions models, creating confusion for users and preventing cross-feature use cases from being developed. 

A full breakdown of our existing permissions models across features can be found in the [working RFC.](https://docs.google.com/document/d/1B3A-PQTykOSnp6BtHZTbIFpSRrvbiV-0FrnukJeaM3A/edit#)

This ticket describes the implementation of the MVP. 

## Measure of success
A minimum viable product of a unified permissions layer across Sourcegraph. While the MVP is currently being scoped, success is defined as... 
- The ability for feature teams to implement basic permissions (edit and view) 
- Documentation required for teams to leverage this tech

## Solution summary
TBD.

## Impact on use cases
This work is required to enable cross-feature user journeys. For example, allowing users to embed code insights into a search notebook to aid in tracking fixes for vulnerabilities. 

## Delivery plan

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.

**Comment by ryphil** [comment]
Closing this ticket as this work has been paused for Q2FY23. 

For Sourcegraph employees, the latest proposal can be found [here](https://docs.google.com/document/d/1-FhtXfIAJJp6Tfcgp4-U1wQ6vRzXDSRhxRQgf562rJE/edit).
