### ISSUE TITLE
-clean-archives flag failed to clear repo archives in a large batch change

### ISSUE THREAD

**Issue by adeola-ak** [sourcegraph/sourcegraph#34943]
A user ran a large batch change (36 hours, 3700 batch changes) which caused the cache to get so big and caused OOM errors even on a large VM. In this instance, -clean-archives did not clear the repo archives and after applying, the user could still see the archives were persisted in the repo.

more details in [slack thread](https://sourcegraph.slack.com/archives/CMMTWQQ49/p1651620274050939)

**Comment by eseliger** [comment]
I don't think I fully understand what the customer is experiencing here. It seems to me like there's three things in this ticket.

1. So they run a large batch change, and src-cli runs out of memory eventually, correct?

That seems plausible, we keep all the patches in memory rn and for 3700 repos with possibly large diffs, that seems very likely. We can fix that by either uploading changeset specs as they come in (but then we will be hoarding data), or by temporarily storing them on disk until we write them to the server.

2. They report that -clean-archives is not working as expected, and the archives are not actually deleted. Correct? How did they validate this?

3. They see some archives appear in the repo? What does this mean, a zip is added to the diff?

**Comment by adeola-ak** [comment]
I think the first sentence about the details of the large batch change was just for context and this ticket is mostly aimed at the fact that -clean -archives did not work to clear the repo archives.

But thanks, we can still address all your points here, 

1. regarding src-cli running out of memory during the large batch change and the fix for this, I think i like the proposal of temporarily storing them on disk. Are there any cons to this or any reason you can think of regarding why we arent already doing that? 
2. regarding how did customer validate -clean -archives did not work: It was reported that after applying, he could see the archives were still persisted in the repo. I'm not exactly sure what this means though. Can i ask what are repository archives anyways? And why they need to be downloaded

**Comment by eseliger** [comment]
> @eseliger I think the first sentence about the details of the large batch change was just for context and this ticket is mostly aimed at the fact that -clean -archives did not work to clear the repo archives.

Got it!

> regarding src-cli running out of memory during the large batch change and the fix for this, I think i like the proposal of temporarily storing them on disk. Are there any cons to this or any reason you can think of regarding why we arent already doing that?

I think we just haven't considered this to be a problem. Nothing that should prevent us from doing it :) 

> regarding how did customer validate -clean -archives did not work: It was reported that after applying, he could see the archives were still persisted in the repo. I'm not exactly sure what this means though. Can i ask what are repository archives anyways? And why they need to be downloaded

I am also not sure what that means 😆 the repo should never contain the archive 🤔 Can we get more information here from the user?

A repository archive is a zip folder containing the contents of the repository, sort of a "quick clone". We need the repository contents on disk so the `steps` can work over those files.

**Comment by eseliger** [comment]
Should we create a separate ticket for the OOM issue here?

**Comment by LawnGnome** [comment]
Closed in favour of the three tickets linked above.
