### ISSUE TITLE
VSCE: improve release workflow

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#34940]
Follow up on https://github.com/sourcegraph/sourcegraph/pull/34522

Currently, the release process is not fully automated as it still requires us to update the version number in the package.json manually after the extension has been released and relies on the correct commit message to build ([read current release process here](https://github.com/sourcegraph/sourcegraph/issues/34742)).

The automated process should also support `pre-release`

TBC

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
