### ISSUE TITLE
Improved usage analytics experience for admins

### ISSUE THREAD

**Issue by ryphil** [sourcegraph/sourcegraph#34941]
## Problem to solve
We’ve observed that the current statistics experience on site admins is limited in terms of functionality, usability, and actionability, which makes it difficult to understand and act on user engagement without workarounds involving querying the database directly or talking directly with users.

## Measure of success
If we improve these issues, it will make it easier for site admins to understand user engagement, and ultimately better manage user licenses and expansions, identify power users, and convey value to their internal leaders.

(Specific measures of success TBD until further discovery with customers has been completed.)

## Solution summary
TBD.

## Delivery plan

**Comment by malomarrec** [comment]
Hey @malomarrec, it looks like this issue was created by someone outside Sourcegraph. Assigning you to triage it! Please answer and route to the right team by adding their team label.

**Comment by ryphil** [comment]
Closing this as MVP is complete and launching in 3.42.
