### ISSUE TITLE
EngEd Video: Troubleshooting CI builds

### ISSUE THREAD

**Issue by marekweb** [sourcegraph/sourcegraph#34952]
Production code: `P13`
[Planning doc](https://docs.google.com/document/d/1ex6j3TwgPU64vjaPUXhUx4FZeDbMX_ZIrU7-vCV6oBw/edit?usp=sharing) 

- [ ] Planning / script
- [ ] Video recording
- [ ] Screen recordings/screenshots
- [ ] Editing
- [ ] Upload
- [ ] Add transcript
- [ ] Add thumbnail
- [ ] Add description / links

**Comment by jhchabran** [comment]
https://handbook.sourcegraph.com/departments/product-engineering/engineering/process/incidents/playbooks/ci/
