### ISSUE TITLE
add documentation for the indexing statistics terms on the repository settings page

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#34950]
Each repository has its own settings page (example: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/settings/).

The "indexing" section of this settings page contains some statistics about the repository's index:

<img width="1719" alt="Screen Shot 2022-05-04 at 4 25 52 PM" src="https://user-images.githubusercontent.com/9022011/166841184-636dd8f9-22c9-4755-aa5e-86c2def80107.png">

It would be great if there was some additional documentation that explained what each of these terms meant. I think this can happen in two stages:

- [ ] create a new page in our documentation that explains this page and the statistics on it 
- [ ] stretch: add hover tool tips to the repository settings page. When a user hovers over a term, they can get a short explanation for what the term means. 
	- I believe this can be accomplished by adding a `data-tooltip` attribute to the term's react component. See [this link](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@03526e551a5a52f4ce562529afa7e64b43a3dde7/-/blob/client/web/src/enterprise/extensions/registry/RegistryExtensionSourceBadge.tsx?L21-22) for how this is implemented on the [extension registry page](https://k8s.sgdev.org/site-admin/registry/extensions)
		- <img width="1071" alt="Screen Shot 2022-05-04 at 4 42 06 PM" src="https://user-images.githubusercontent.com/9022011/166842533-4f5b8463-06d4-4758-97d7-faf5ca40ea54.png">

**Comment by sourcegraph-bot-2** [comment]
Heads up @jjeffwarner - the "team/search-core" label was applied to this issue.

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket, please let us know how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
