### ISSUE TITLE
Search bar with new editor: completion button gets hidden with long repository names

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#34968]
- **Sourcegraph version:** sourcegraph.com
- **Platform information:** chrome

#### Steps to reproduce:

1. Type in `repo:github.com/sourcegraph/tiny-go-` and wait for completion

#### Expected behavior:

Everything looks fine

#### Actual behavior:

![image](https://user-images.githubusercontent.com/1185253/166900944-4a7fcaba-e75c-47ef-898c-6e32c771a3a6.png)

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by fkling** [comment]
That's actually the Monaco implementation and since we are replacing it we won't fix this.
