### ISSUE TITLE
Provide better support for air-gapped instances

### ISSUE THREAD

**Issue by ryankscott** [sourcegraph/sourcegraph#34963]
By default Sourcegraph instances require access to sourcegraph.com in order to fetch extensions from our extension registry. In an air-gapped instance, this isn’t possible and so we recommend that customers use their [own private extension registry](https://docs.sourcegraph.com/admin/extensions#publish-extensions-to-a-private-extension-registry). However, by default this registry has no extensions and core features of Sourcegraph don’t function (e.g. code intelligence).

For more see relevant [RFC](https://docs.google.com/document/d/1ymCMW9TBeirdqjTPx0zmYfNc5v-zYKCwLF2bxZJzXiA/edit#)

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by ryankscott** [comment]
Marking as done / complete.
