### ISSUE TITLE
JetBrains: Save window size

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#34967]
## Context

We currently always open the Find on Sourcegraph popup at a 1200x800px size.
The native "Find in Files" popup remembers its last size and position, which is a quite nice UX.

## Problem

It's frustrating to resize the window at each open when I need it at a certain size

## Solution

Save the last size and position somewhere.
It might get tricky when considering multiple screens and screen resolution changes. Test these cases.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by vdavid** [comment]
The [Popups section of the SDK docs](https://plugins.jetbrains.com/docs/intellij/popups.html#showing-popup) might help.
[JBPopup has a bunch of](https://sourcegraph.com/github.com/JetBrains/intellij-community/-/blob/platform/ide-core/src/com/intellij/openapi/ui/popup/JBPopup.java) `show*()` methods.
We currently use `popup.showCenteredInCurrentWindow()`, but perhaps `showInBestPositionFor()` would be better.

**Comment by vdavid** [comment]
Adding something similar to `setDimensionServiceKey(project, LOCATION_SETTINGS_KEY, true)` in `SourcegraphWindow.java:createPopup()` might solve this.

**Comment by vdavid** [comment]
The way the JetBrains team casually mentions this capability [here](https://plugins.jetbrains.com/docs/intellij/popups.html#:~:text=and%20support%20remembering%20their%20size) would lead me to believe that this is something simple. However, [this](https://sourcegraph.com/github.com/JetBrains/intellij-community/-/blob/platform/lang-impl/src/com/intellij/find/impl/FindPopupPanel.java?L257&subtree=true) is how they actually solved it for the Find in Files popup, which makes it seem extremely tricky to do. I'll ask Yann at JetBrains.
