### ISSUE TITLE
Only allow Sourcegraph authored extensions

### ISSUE THREAD

**Issue by ryankscott** [sourcegraph/sourcegraph#34962]
We've had a number of requests to only allow extensions created by Sourcegraph as users are concerned about the likelihood of installing malicious extensions. 

As part of this we also need to define what are "Sourcegraph authored" extensions.

Product Gaps
- [Only allow extensions created by Sourcegraph](https://sourcegraph2020.lightning.force.com/lightning/r/Product_Gap_Submission__c/a1C5b00000AEyllEAD/view)

Productboard feedback
- [Only allow extensions created by Sourcegraph](https://sourcegraph.productboard.com/roadmap/4491721-integrations-okr-roadmap/features/12735027/detail)

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
