### ISSUE TITLE
dependencies search: lockfile service call should not hard fail on first error

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#34977]
[This query shows "No results"](https://sourcegraph.com/search?q=context:global+r:deps%28%5Egithub%5C.com/sourcegraph/%29&patternType=literal&trace=1), even though we know some of the repos (like sourcegraph/sourcegraph) definitely have dependencies. I briefly looked at a failing trace and I think the reason is we hard fail the whole thing if *any* (repo, rev) pair errors when calling the lockfile service on it.

https://github.com/sourcegraph/sourcegraph/blob/e3de126a593b9b52f0cdb355fcd57f8505f1dcec/internal/codeintel/dependencies/service.go#L150-L163

Instead, we should aggregate errors and convert them to a search alert, but still return results for what we can find.

**Comment by sourcegraph-bot-2** [comment]
Heads up @jjeffwarner - the "team/search-core" label was applied to this issue.

**Comment by stefanhengl** [comment]
This feature was discontinued.
