### ISSUE TITLE
add Python dependency search test case to gqltest

### ISSUE THREAD

**Issue by stefanhengl** [sourcegraph/sourcegraph#34978]
We don't have a python repo with a poetry.lock file in sgtest. We should add it and then add a test that targets it.

- [ ] add toy repo with poetry lockfile to sgetst
- [ ] update TestSearch

**Comment by malomarrec** [comment]
Hey @stefanhengl, this issue didn't have a team label. Given you created it, I assigned you and added your team label. Feel free to unassign yourself. If this is not the right label, can you make sure to add the right one?

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/search-core - the "team/search-core" label was applied to this issue.

**Comment by keegancsmith** [comment]
cc @mrnugget

**Comment by stefanhengl** [comment]
We have stopped development of dependency search.
