### ISSUE TITLE
Move SCIP definition to a separate repository

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#34983]
Currently, the SCIP definition lives inside the sourcegraph/sourcegraph monorepo. We'd like to move this code to a separate repo to improve the contribution experience for external contributors.

**Comment by tjdevries** [comment]
If we do that, do we also put the bindings in that repo too? Should we add a package you can import (`@sourcegraph/scip-dev` or whatever) for usage within projects, instead of copy paste into other projects?

We can version it as well that way?

**Comment by olafurpg** [comment]
Yeah, I think it would be nice to include the bindings with that repo as well. Ideally, we could publish the bindings using the official package managers for each ecosystem. To begin with, we can copy-paste like we've been doing so far.

**Comment by varungandhi-src** [comment]
Is moving the `lsif-typed` CLI tool to the new repo part of this ticket?

**Comment by olafurpg** [comment]
Good question. I'd say yes, and we should move the "repro" testing DSL as well. If it's a lot of work then we can delay it for after the initial announcement.

**Comment by olafurpg** [comment]
For the `scip` comman-line tool, I think it's nice that the initial version has proper subcommands 

```bash
scip lsif --from=dump.lsif-typed --to=dump.lsif
scip lsif --from=dump.lsif --to=dump.lsif-typed
scip snapshot --output-directory=foobar
```
