### ISSUE TITLE
insights: enable streaming for search backend insights

### ISSUE THREAD

**Issue by leonore** [sourcegraph/sourcegraph#34989]
We enabled streaming search for just-in-time search insights in #34149, but we have yet to do it for backend insights. We should enable it as part of the monorepo improvements.

nb: we should consider removing `types.SearchStream` as well, as per [this Slack convo](https://sourcegraph.slack.com/archives/C02KE7E9GMR/p1651674137940929).

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
