### ISSUE TITLE
Allow users to send feedback directly to us from self-managed instances

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#3499]
> Would like a feedback widget in the app (so he can surface these complaints easily / in real-time).

Requested by https://app.hubspot.com/contacts/2762526/company/557692615 via @beyang

**Comment by sqs** [comment]
@christinaforney Reassigning to you because you had mentioned wanting this, too.

**Comment by pdubroy** [comment]
Closing since we have a feedback widget now.
