### ISSUE TITLE
Allow multiline searches

### ISSUE THREAD

**Issue by akshetpandey** [sourcegraph/sourcegraph#35]
Hey, its very common to have a single objc function call span multiple lines. Is there was to search multiple lines in sourcegraph?

**Comment by beyang** [comment]
Yes, I can see the pain with a language like Objective-C. @keegancsmith any thoughts on how hard this would be to support?

**Comment by keegancsmith** [comment]
There isn't a way right now. Our JIT backend could support it, our indexed backend probably could as well (would need to investigate). For the JIT backend in theory it could be faster, since a surprising cost in regex engines is finding newlines and counting them. Our bigger issue is the way the API is structured assumes single line matches, which affects us all the way up into our frontend. As such I don't see it being a short term priority to implement.

**Comment by beyang** [comment]
@akshetpandey it sounds like this will be a non-trivial amount of dev work. Can you share some more information to help us prioritize accordingly?

* Can you point to some code examples from open source that demonstrate the problem and give us a clear target? Perhaps there is a simpler solution that doesn't require "full" multiline support.
* Is this a dealbreaker for your use of Sourcegraph on the Objective-C code you care about?
* If so, are you still finding Sourcegraph useful in other languages, or is Objective-C the primary language you wish to index?

**Comment by akshetpandey** [comment]
1> https://github.com/AFNetworking/AFNetworking/blob/master/Example/iOS%20Example/Controllers/GlobalTimelineViewController.m#L91-L92

Support I want to find all implementation of that delegate because I want to refactor it and find out who is affected.

2>
Its not a deal breaker but with no support for language server for objc and no multiline matches its basically as good as github org search. 

3>
Objc is about 90% of our code base and very few people deal in other languages. Its still early days to find out how sourcegraph would impact our workflow. I personally have been using ripgrep for all my searches so I am still trying to figure out how to fit sourcegraph into my use cases but the potential seems interesting.

**Comment by beyang** [comment]
Thanks for describing those, Akshet. In full transparency, we will likely not get around to addressing this directly in our next iteration (the next month or so). After that, we will revisit the following proposals that may address your issue:
* Multiline search
* Objective-C code intelligence

Will post back to this issue when there is more news to report.

**Comment by FranklinYu** [comment]
The searching function is the key; how it is present doesn’t really matter. For example, if I search `tableView:heightForRowAtIndexPath:`, I wouldn’t mind if Sourcegraph gives single line result

https://github.com/AFNetworking/AFNetworking/blob/5890adc404d0187dcc452f467c8fc3cedc19869d/Example/iOS%20Example/Controllers/GlobalTimelineViewController.m#L91

Shall we start with Objective-C language server?

**Comment by zmt** [comment]
Also desirable to multi-line match in yaml files (and many other file types).

**Comment by dobrou** [comment]
Hi,
we plan to migrate from Opengrok to Sourcegraph and missing multi line search is crucial.

I'd like to propose one way, how "multi line" search could work, very similar to how it works in Opengrok.

In short: 
- Input: multiple sub queries, separated eg. by OR keyword
- Output: results will be intersection of matching FILES results from each query. 
  - And reported lines in each file may be concat of all lines from all queries, in case file was found by every sub query.

Example:
1) If query: "myclassname"
returns results: "myfile.cs : line 10"
and another query "mymethodname"
returns results: "myfile.cs : line 15, anotherfile.c : line 22"
than query: "myclassname OR mymethodname"
with current implementation returns nothing
and I would expect to get results: "myfile.cs : line 10,15"

From my shallow understanding of Sourcegraph internals, based only on comments above, I assume this approach:
- will not need any changes in indexer
- should not need any changes in UI or results pipeline - it's still "lines per file"
- will need to refine way how to express sub queries
- will need to implement results intersector
  - may be hard, in case one subquery returns large result set. Eg. query "MyInterface OR ulong" - where I try to find every implementation of interface which use ulong data type.

Summary:
My proposal will not allow user to use full regexp matching across multiple lines.
But it should have cheaper implementation and maybe cheaper performance cost.
However at least for my usual use case, it's more than good enough.

My primary target language is dotnet, however I don't feel this feature is related to any specific language.

@akshetpandey would this approach work also for you?

@keegancsmith @beyang Do you think cheaper but still good enough variant will be worth doing?

Thank you

**Comment by beyang** [comment]
> UPDATE: Ok, now I see I re-invented wheel and basicaly desribed existing feature request #1005

Great minds think alike :) Thank you for sending this feedback!

**Comment by tsenart** [comment]
@attfarhan: Is this done? :)

**Comment by attfarhan** [comment]
Yup, this is done now. You can use `\n` in your queries to search in multiple lines.
