### ISSUE TITLE
Enable Git Extras by Default

### ISSUE THREAD

**Issue by brentshermana** [sourcegraph/sourcegraph#3501]
A common feature among text editor extensions with Git integration is the ability to display the last commit message that changed a particular line.

Currently, when viewing a source file on github with SourceTree's browser extension, you can navigate using references to and definitions of symbols. It would also be cool to be able to navigate to the last commit that changed the line you're clicking on (if you're clicking on whitespace rather than code)?

**Comment by sqs** [comment]
You can do this!

1. Install the [Sourcegraph browser extension](https://docs.sourcegraph.com/integration/browser_extension)
1. Enable https://sourcegraph.com/extensions/sourcegraph/git-extras
1. On GitHub, in the ≡ menu added by Sourcegraph in the top nav bar, select `Git: Show blame`
1. Click on a line number on a file on GitHub

Video here: https://drive.google.com/file/d/1zpKN1VHooDZjk0cKRfJkPjUkphDWqJbD/view?usp=sharing

Does this solve your problem?

We should probably enable `sourcegraph/git-extras` by default for everyone, so you can get this just by installing the browser extension.

**Comment by brentshermana** [comment]
Thanks, that's what I was looking for. Enabling git-related features by default makes sense.

**Comment by dadlerj** [comment]
During a live install/demo session with a software architect at https://app.hubspot.com/contacts/2762526/company/694012030 yesterday, there was a lot of confusion about how to enable blame. We walked through it together:

* going to the extensions page
* searching for `git-extras` (which they never would have found if I hadn't been on the call)
* enabling it
* going back to a file
* toggling inline blame on using the "Blame" button in the file header

This is a pretty confusing experience for end users, and I doubt most users would ever find it in the first place... 

@sourcegraph/web @sqs @christinaforney  should we enable `git-extras` by default for now (and think about the onboarding experience for extensions in future projects)?

**Comment by felixfbecker** [comment]
I’m surprised it isn’t already

**Comment by dadlerj** [comment]
Any update on adding this to the default? I think it would be a huge benefit for most users.

**Comment by christinaforney** [comment]
+1 to enabling by default. 

cc @imtommyroberts to separately think about the experience of enabling an extension at some point.

**Comment by lguychard** [comment]
Here goes: https://github.com/sourcegraph/sourcegraph/pull/9540
