### ISSUE TITLE
Proposal: sunset #cloud-devops slack channel

### ISSUE THREAD

**Issue by danieldides** [sourcegraph/sourcegraph#35025]
# Context
Currently we have both  `#cloud-devops` and a `#dev-ops` Slack channels. Currently `#dev-ops` has 132 members while `#cloud-devops` only has 83. `#dev-ops` is also a recommended channel in the [Sourcegraph Handbook](https://handbook.sourcegraph.com/departments/product-engineering/engineering/#slack-channels). Without any clear distinction between channels we've noticed that most communications favor the larger `#dev-ops` channel and `#cloud-devops` has largely turned into a channel of bot integrations. Because of this, it's become easier to ignore that channel and miss legitimate communication efforts in the spam. Posting in `#dev-ops` also exposes the message to more people which increases the opportunity for cross-team input.

# Plan
In an effort to reduce the number of duplicate channels and cross-channel linking required to keep everyone informed, we are proposing sunsetting the `#cloud-devops` channel and centralizing all communications on the `#dev-ops` channel. All integrations currently running in the `#cloud-devops` channel will be redirected as outlined in the plan below. `#cloud-devops-internal` will still remain to allow internal team communications but all external requests and cross-team communications will only take place in the larger `#dev-ops` channel.

# Integrations migration
- OpsGenie alerts -> `#cloud-devops-internal`
- BuildKite Deployment failures -> `#cloud-devops-internal`

**Comment by virginiaulrich** [comment]
This all makes sense! Only suggestion would be ... would you like #cloud-devops-internal to just be renamed to #devops-internal?

**Comment by danieldides** [comment]
@virginiaulrich This was actually discussed (briefly) in the retro this morning. Dropping "cloud" from the name may make sense as Cloud DevOps is now owning Managed Instances (which historically haven't really been thought of as "Sourcegraph Cloud") and there are no other DevOps teams. The idea seemed generally well received but I don't want to speak for anyone else.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/cloud-devops - the "team/devops" label was applied to this issue.

**Comment by danieldides** [comment]
All integrations have been redirected and intent has been reaffirmed by the team.

We are going to rename the channel to `FROZEN-cloud-devops` and limit write permissions to prevent new messages being posted to it.

**Comment by michaellzc** [comment]
no applicable anymore after the team transition
