### ISSUE TITLE
lockfiles: support pipfile.lock for Python dependency search

### ISSUE THREAD

**Issue by stefanhengl** [sourcegraph/sourcegraph#35041]
We already support poetry.lock files. We should also add a parser for pipfile.lock.

**Comment by stefanhengl** [comment]
cc @tsenart

**Comment by sourcegraph-bot-2** [comment]
Heads up @jjeffwarner - the "team/search-core" label was applied to this issue.

**Comment by mpimenov** [comment]
Do we have a better pipfile.lock spec than the call stack of the (reference?) implementation below?

https://pipenv.pypa.io/en/latest/basics/#pipfile-lock-security-features

https://github.com/pypa/pipenv/blob/3e15161cb71c5520fc88078333d16393fdd0679d/pipenv/cli/command.py#L302
https://github.com/pypa/pipenv/blob/3e15161cb71c5520fc88078333d16393fdd0679d/pipenv/core.py#L1073
https://github.com/pypa/pipenv/blob/3e15161cb71c5520fc88078333d16393fdd0679d/pipenv/project.py#L821
https://github.com/pypa/pipenv/blob/3e15161cb71c5520fc88078333d16393fdd0679d/pipenv/vendor/plette/lockfiles.py#L16
https://pypi.org/project/plette/

The last one links circularly to https://github.com/pypa/pipfile so probably that's the way to go.

**Comment by tsenart** [comment]
Some prior art: https://github.com/aquasecurity/go-dep-parser/tree/main/pkg/python/pipenv
