### ISSUE TITLE
Extension active status is not synced between different cards

### ISSUE THREAD

**Issue by taras-yemets** [sourcegraph/sourcegraph#35042]
The active status of the extension card in the featured extensions list and the similar card in all extensions list are not synced.

**Sourcegraph version:**  Latest build on Cloud (fc3c81f52a34 built on 2022-05-06 at the time the issue is created). Should be reproducible on any other instance too.  

https://user-images.githubusercontent.com/25318659/167085255-216c9229-0259-43c3-a495-2f17cfd00e5c.mov

#### Steps to reproduce:

1. Navigate to the extensions page on your Sourcegraph profile.
2. Configure the search query in the way so that you have the same extension both in featured and other lists.
3. Toggle any of these cards active state and check whether that state was updated on another card.

#### Expected behavior:
Cards active states are synced.

#### Actual behavior:
Cards active states are not synced.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
