### ISSUE TITLE
Code Insights: Implement 404 screen for the standalone insight page 

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#35045]
[Designs](https://www.figma.com/file/Y4grZjTxnXHEQSoeB14vU1/Share-a-link-to-an-individual-code-insight-RFC-654?node-id=1214%3A6728)

In case if we couldn't find the insight on the backend we should render 404 screen with proper copy about that this. (We also should consider that an insight might be deleted or user just has a wrong link)

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
