### ISSUE TITLE
Code Insights: Add collapse state for the drill-down filter panel on the standalone page

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#35044]
Follow for https://github.com/sourcegraph/sourcegraph/pull/35043

Currently we don't collapsed state for the drill-down filter panel. We should add this in order to improve the standalone page UI. 

Also we don't have a separator element between different filter sections in the horizontal mode of the drill-down component's layout. We should add this, it's relatively small change so it might be a part of this issue. 

[Designs](https://www.figma.com/file/Y4grZjTxnXHEQSoeB14vU1/Share-a-link-to-an-individual-code-insight-RFC-654?node-id=1228%3A16270)

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
