### ISSUE TITLE
Optimize Email Campaign & Landing Flows for Unactivated Registered Users

### ISSUE THREAD

**Issue by a-bergevin** [sourcegraph/sourcegraph#35055]
### Problem to solve

Email can be a powerful tool for re-engaging dormant users. However, developer personas can be particularly sensitive to sales/marketing language and may be quick to unsubscribe if they feel our emails do not create value for them. Product has not invested in email testing as a tool for onboarding. Our partners in marketing have done limited work in this area as well - not having the contact information or legal clearance to contact self-hosted trial customers they have only done a small amount of testing with campaigns for cloud users. Investing in the overall registration flow and onboarding funnel presents an optimal moment to reconsider how we can best use email to return users to the product and engage in experiences that lead toward the aha moment.

The developer audience is particularly sensitive to email campaigns, so we want to ensure any email SG sends are:

1. Minimal overall (very few in the series)
2. Narrowly Targeted (do not email about X if they’ve already used X)
3. Designed for the user & heavily tested to optimize performance
4. Provide clear opportunities to opt out with systems that cleanly records & respect those preferences

### Measure of success

The real outcome we want to impact is returning to the product so we'll watch metrics like:
- `One and done` rate is reduced
- `1-week-retention` is up
- `2-week-retention` is up
- `# of days active in first 30 days` is up

More immediately related to email we'll be watching for
- `Unsubscribes` below X % (need to baseline)
- `Open rate`
- `CTR`

### Solution summary
Partner with marketing and/or work on our own to develop email campaigns designed to maximize engagement in the first 30 days. Emails should be built so each has a clear goal, optimal post click experience (designed landing page with clear next steps for the user), and a/b tested subject lines, templates, and CTAs.

We want to avoid duplication of effort and a poor user experience where the user gets emails from both product and marketing teams. Execution will depend on bandwidth and interest of the involved teams (product and demand gen), but our team is flexible as to who actually performs sending of the email as long as we are aligned in testing plans, goals, and ensuring a positive user experience.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @a-bergevin - the "team/growth" label was applied to this issue.

**Comment by malomarrec** [comment]
Outdated, closing
