### ISSUE TITLE
docker-compose users are unable to run batch changes

### ISSUE THREAD

**Issue by michaellzc** [sourcegraph/sourcegraph#35059]
context:
- https://sourcegraph.slack.com/archives/C01HW836940/p1651836581316509
- https://sourcegraph.slack.com/archives/CMMTWQQ49/p1651853501985949
- https://sourcegraph.slack.com/archives/CMMTWQQ49/p1651858843636259

@sourcegraph/delivery I am requesting the following commits be included in a patch release. They are already merged into `main`:

> not a real patch change, only requires hotfix to our https://github.com/sourcegraph/deploy-sourcegraph-docker repo

- https://github.com/sourcegraph/deploy-sourcegraph-docker/commit/17e53f2c7a7b6efb999ca0b1e56cc13f09b74847 https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/813 (replaced with commit when it's merged)

---

The intent of the questions below is to ensure we keep Sourcegraph high quality and [only create patch releases based on a strict criteria.](https://handbook.sourcegraph.com/engineering/releases#patch-releases) If you can answer yes to many or most of these questions, we will be happy to create the patch release.

I have read [when and why we perform patch releases](https://handbook.sourcegraph.com/engineering/releases#patch-releases) and answer the questions as follows:

> Are users/customers actively asking us for these changes and cannot wait until the next full release?

Yes

> Are the changes extremely minimal, well-tested, and low risk such that not testing as we do in a full release is OK?

Yes

> Is there some functionality completely broken that warrants redacting the prior release of Sourcegraph and advising users wait for the patch release?

Yes. If they use batch changes

> This will interrupt our regular planned work and release cycle, taking one full working day of our time, and will take up all of our site admin's valuable time by asking them to upgrade or producing noise for them if they don't need to upgrade.
>
> Do you believe the changes are important enough to warrant this?

Yes

> Patch releases are a signal we can do something better to improve the quality of Sourcegraph. Have you already scheduled a call (or created a google doc) to perform a [retrospective](https://about.sourcegraph.com/retrospectives) and identify ways we can improve?

No

---

**For the [Release Captain]** - after reviewing this request:

- [ ] **Comment on this issue** with a decision regarding the request.
- [ ] If you are a first-time [Release Captain], please review the high-level overview of the [patch release process].
- [ ] If approved, **add it to a patch release**:
  - If there is [already an upcoming patch release](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+), add the listed commits alongside a link to this issue
  - If there is no upcoming patch release, create a new one:
    - [ ] Update [`dev/release/release-config.jsonc`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/release/release-config.jsonc) and open a PR to `main` to update it
      - [ ] Change `upcomingRelease` to the current patch release
      - [ ] Change `previousRelease` to the previous patch release version
      - [ ] Change `releaseDate` to the current date (time is optional) along with `oneWorkingDayAfterRelease` and `oneWorkingDayBeforeRelease`
      - [ ] Change `captainSlackUsername` and `captainGitHubUsername` accordingly
    - [ ] `yarn release tracking:issues` 
    - [ ] Add the listed commits alongside a link to this issue to the generated [release tracking issue](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+)
- [ ] **Comment and close this issue once the relevant commit(s) have been cherry-picked into the release branch**.

[release captain]: https://handbook.sourcegraph.com/engineering/releases#release-captain
[patch release process]: https://handbook.sourcegraph.com/departments/product-engineering/engineering/process/releases#patch-release-process

**Comment by michaellzc** [comment]
Patch PR: https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/814

**Comment by unknwon** [comment]
Hmm, is this still needed given it is part of 3.40?

**Comment by caugustus-sourcegraph** [comment]
This was included in 3.39 and can be closed out. It didn't warrant an official patch, we just updated the deploy-sourcegraph-docker branch directly, but wanted this issue for tracking purposes.
