### ISSUE TITLE
Batch changes "Show more" button doesn't show more, makes me sad

### ISSUE THREAD

**Issue by chrispine** [sourcegraph/sourcegraph#35060]
- **Sourcegraph version:** 
Version: 146274_2022-05-06_89604132f410

- **Platform information:** 
macOS 12.1, Chrome Version 100.0.4896.127 (Official Build) (arm64)

#### Steps to reproduce:

1. Go to [this batch change](https://k8s.sgdev.org/users/jeff.wayman/batch-changes/deploy-docs-folder-links-rename/executions/QmF0Y2hTcGVjOiI2WEtUUnRSd0Z3eSI=/execution/workspaces/QmF0Y2hTcGVjV29ya3NwYWNlOjk5MjAyMw==?visible=1) and look at the workspaces pane. It says "24 workspaces total (showing first 20)" and has a "Show more" button.
2. Don't get your hopes up.
3. Click the button.

#### Expected behavior:
It should show more.

#### Actual behavior:
It shows no more, just the exact same amount, which is less than the "more" I was hoping for and led to expect.

**Comment by eseliger** [comment]
I am going to pull this into this sprint, otherwise it would miss the release and I think it should be fixed asap.

**Comment by eseliger** [comment]
This deserves a write-up of the issues that were found while debugging our apollo connection handler. Since this is a general-purpose component, we should be able to hand this off once we have that.

**Comment by eseliger** [comment]
Also, this has been fixed on our end for now, using lots of duct tape :)

**Comment by sourcegraph-bot-2** [comment]
Heads up @taylorsperry @jasongornall - the "team/frontend-platform" label was applied to this issue.

**Comment by jasongornall** [comment]
this appears to be resolved for me!

**Comment by eseliger** [comment]
No, it's still happening but only with substantial enough lag, >1s network round trip (so less often locally but almost always on deployed instances)

**Comment by courier-new** [comment]
I think the 1-3d estimate is pretty optimistic. 🙃 We're likely going to be fighting Apollo internals because we're doing something that really isn't supported here.

**Comment by courier-new** [comment]
One option that's potentially more okay by Apollo standards is to poll workspace statuses separately from the filtered connection, then stitch them back together (Apollo's caching is supposed to handle that automatically, but it's been pretty hit-or-miss with our implementation because of the way we handle node types). We could poll for the full list of workspaces, but only get the id and status fields. Then our filtered connection data wouldn't have to poll, so the connection parameters changing wouldn't be fighting with the latest polled data to be accepted into Apollo cache.

**Comment by eseliger** [comment]
I was thinking to just throw out apollo for this list 😆 What do you think would be a better estimate?

**Comment by courier-new** [comment]
Removing the 4.0 label since we deemed this not critical to 4.0, but I'm still going to prioritize getting this in if I have time today.
