### ISSUE TITLE
[Discovery] Introduce GitHub App for Site Level Codehost connections

### ISSUE THREAD

**Issue by ryphil** [sourcegraph/sourcegraph#35077]
Today, we have successfully implemented a GitHub App for individual user code host connections. This is currently behind a feature flag on Sourcegraph Cloud. We have heard from customers that they are interested in this.

Related: 
- [RFC 549: GitHub Apps integration for Cloud SaaS](https://docs.google.com/document/d/180iMviFZ4xGeHQGCO7LMqfl5luFIM9RA7FCWW0NNVAI/edit)

**Comment by unknwon** [comment]
Discovery report: https://docs.google.com/document/d/1AP6ioihbgPx79GyQv0rWZe8Y2Gs5lik2MV3gsmeos14/edit#

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.
