### ISSUE TITLE
Searching over a repo query context instead searches all repositories on instance

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#35096]
We have a `@sourcegraph/all` context that's defined as `r:^github\.com/sourcegraph/`:

<img width="626" alt="Screen Shot 2022-05-08 at 8 39 20 PM" src="https://user-images.githubusercontent.com/888624/167336796-5fa1d29b-8584-44f0-b83e-0c85469cc84f.png">

But when searching with that context, we seem to be searching _all_ repositories. Just listing the repositories, we see the most popular GH ones, and they definitely do not match `r:^github\.com/sourcegraph/`:

<img width="1440" alt="Screen Shot 2022-05-08 at 8 39 30 PM" src="https://user-images.githubusercontent.com/888624/167336807-fa4a8903-b7fd-44c2-afbf-89abfb7fdc6d.png">

Query listing all repos, not just those defined by the query in `@sourcegraph/all: https://sourcegraph.com/search?q=context:%40sourcegraph/all+&patternType=literal

This seems like a big bug. Don't know if it's related to this context specifically, or all query contexts, or one using the `r:` alias maybe?

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @jjeffwarner - the "team/search-core" label was applied to this issue.

**Comment by rvantonder** [comment]
Turns out, this is related to whether the user has allowed private repositories, I think. I haven't allowed Sourcegraph to access private repos that is in the set of this context/query. So it seems to fall back to "entire world of repos". Which seems buggy. Don't know what a better behavior would be ("showing all repos, please enable private repos"?).

**Comment by tsenart** [comment]
@rvantonder: I can't reproduce. Maybe share a trace?
<img width="1708" alt="image" src="https://user-images.githubusercontent.com/67471/167718163-2a4a9364-0ffb-4709-9cc1-6539d96aa012.png">

**Comment by tsenart** [comment]
> Turns out, this is related to whether the user has allowed private repositories, I think. I haven't allowed Sourcegraph to access private repos that is in the set of this context/query. So it seems to fall back to "entire world of repos". Which seems buggy. Don't know what a better behavior would be ("showing all repos, please enable private repos"?).

I only read this now. What does it mean for a user to "allow private repositories"?

**Comment by rvantonder** [comment]
OK so looked into this again, you can reproduce my issue by adding this to experimental features:

```
      "searchContextsQuery": false,
```

So OK: it says this option is deprecated and on by default, but it surfaces the issue. The problem is that search context query is somehow bypassing validation (so it seems to be constructing a query from the context, that is not correct).

Here's an example query that returns results when this search query context is applied:

https://sourcegraph.com/search?q=context:%40sourcegraph/all+%28%28repo:zoekt+case:yes%29+OR+%28repo:%5Egithub%5C.com/sourcegraph/handbook%24%29%29+case:no+select:repo&patternType=literal

But changing the context to `context:global` and running the same query incognito, says that the query is invalid (the query _IS_ invalid, the one above should not succeed):

https://sourcegraph.com/search?q=context:global+%28%28repo:zoekt+case:yes%29+OR+%28repo:%5Egithub%5C.com/sourcegraph/handbook%24%29%29+case:no+select:repo&patternType=literal

So I'll rephrase this issue to say: 

using search based query contexts could create and execute invalid queries. you can surface the issue by toggling `      "searchContextsQuery": false,` and seeing what should be happening instead (query is reported invalid).

**Comment by tsenart** [comment]
Here are my findings so far as I debug this locally. Even when that settings is set to true, the bug that @coury-clark reported manifests.

Logging the query plan [after the transformation](https://github.com/sourcegraph/sourcegraph/blob/94832d43cdd7b1fbcb5e92ee3bc6dfdd8a16c8d3/internal/search/run/run.go#L81-L90) yield the following results.

- `context:go-deps (r:protobuf OR r:PROTOBUF)` => `(or (and "repo:^go/" "repo:protobuf") (and "repo:^go/" "repo:PROTOBUF"))` ✅
-  `context:go-deps (r:protobuf OR r:PROTOBUF) select:repo` => `(and "repo:^go/" "select:repo")` ❌

Digging into our query parsing code and what changes went into it recently.

**Comment by rvantonder** [comment]
interesting. sounds good, will take over frim here then, sounds like it's something on me then!

**Comment by tsenart** [comment]
Update: The issue manifests with 3.37.0, so the commit that introduced the bug was between 3.36.0 and 3.37.0.

**Comment by camdencheek** [comment]
Pushed a (bandaid) fix [here](https://github.com/sourcegraph/sourcegraph/pull/35483)
