### ISSUE TITLE
zoekt: interface to find skipped vs indexed files

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#35106]
We often get users and admins reporting results missing. We should work out how we can better surface this information. For example a search query listing skipped files?

**Comment by sourcegraph-bot-2** [comment]
Heads up @jjeffwarner - the "team/search-core" label was applied to this issue.

**Comment by keegancsmith** [comment]
I've marked this as good first issue, but it has a bit of meat to it. So not a quick task, depending on direction chosen. cc @eugeniaft this can fall under improving admin observability.
