### ISSUE TITLE
Hitting ADO API Limit

### ISSUE THREAD

**Issue by bdschaap** [sourcegraph/sourcegraph#35120]
I'm using the generic git host repository type to configure many ADO repos.  250+ repos a few of which are very large.  I'm able to clone the ADO repos but then eventually hit ADO's individual user API limit .  Any suggestions?  Is there a setting or way to use Sourcegraph that may help reduce the number of API calls to ADO?

**Comment by malomarrec** [comment]
Hey @malomarrec, it looks like this issue was created by someone outside Sourcegraph. Assigning you to triage it! Please answer and route to the right team by adding their team label.

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.

**Comment by eseliger** [comment]
@varsanojidan

**Comment by varsanojidan** [comment]
Hi @bdschaap is this still an issue for you? You can use this [setting](https://docs.sourcegraph.com/admin/config/site_config#defaultRateLimit) to set the global default for rate limits. Unfortunately there is no way to currently set limits on generic git code host connections.

Also check out the [ADO external service](https://docs.sourcegraph.com/admin/external_service/azuredevops) type if you are using Azure DevOps Services!

**Comment by bdschaap** [comment]
Haven't tried in a while but if there is a global default then I can try that.
