### ISSUE TITLE
Code monitor illustration is relatively huge on small browser widths

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#35141]
This isn't urgent, but at ≤ 990px the Code monitor illustration gets huge. It looks like it's auto-resizing but at that width it's not really readable. Possibly we should start it at a smaller width on small screen sizes.
![image.png](https://images.zenhubusercontent.com/5467e9ba7c6ccc6277a5f103/13b42433-055f-46a0-887f-5d7efd444aa3)

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by camdencheek** [comment]
Seems to have been fixed along the way. The illustration now resizes along with the window
