### ISSUE TITLE
insights: fix checkbox alignment in "add to dashboard" modal 

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#35163]
The checkbox is no longer on the screen: 
![image](https://user-images.githubusercontent.com/11967660/167491568-8eee2fa4-cd0e-40eb-886a-106be6c59172.png)

See also: 
https://www.loom.com/share/896e053d922348d59552d3b8f25453a4

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by vovakulikov** [comment]
Is this a duplicate of https://github.com/sourcegraph/sourcegraph/issues/35124
