### ISSUE TITLE
JetBrains: SearchBox: Hook up telemetryService to send events

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#35178]
This is currently set to NOOP_TELEMETRY_SERVICE.

We need this to send telemetry data and monitor search box use.
Not sure if we'll need to do this in Java or JS, but batching the requests will be important in either case.
An argument for Java is that we should register install & uninstall events as well, in which cases the web view won't exist.

See VS Code's `SearchResultsView.tsx` for inspiration.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by vdavid** [comment]
Collecting the list of events to track: https://github.com/sourcegraph/sourcegraph/issues/34778

**Comment by vdavid** [comment]
How to log events:

- log them using the logEvents [endpoint](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/user/settings/backend.tsx?L127-132)
- also the LogUserEvent endpoint ([deprecated](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/user/settings/backend.tsx?L98)) because [logUserEvent is the only](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@1458b0cd20d0c7b2053b859d854774e7b4ec5ce2/-/blob/cmd/frontend/graphqlbackend/user_usage_stats.go?L77&utm_source=chrome-extension&utm_campaign=open-on-sourcegraph) place where “last active” and “last active in code host or code view” values are set, which are shown in side-admin/usage-stats.
- keep logUserEvent even when logEvents will be updated because not all customers will quickly update their instances. Maybe we can remove it after half year or year.

[source](https://sourcegraph.slack.com/archives/C01LZKLRF0C/p1655308824678899)

**Comment by philipp-spiess** [comment]
We're splitting the work into these sub-areas:

- [x] @philipp-spiess Set up hooks for install/uninstall events and ensure we have a stable anonymous user ID
- [ ] @vdavid Create a Java class to log the install uninstall events via custom POST requests to the GraphQL endpoint (using the new endpoint only)
- [ ] @vdavid Create a Java method that can give us version information for our current extension version (we’ll use that both on the Java and TS side so that value also need to be passed through the config call)
- [ ] Copy the VSCode TypeScript files for event batching and log to the new graphQL endpoint. If we detect a search event, also log to the legacy endpoint.

**Comment by vdavid** [comment]
We have identified these further tasks:
- [ ] Log install/uninstall events when access token and/or URL changes. 
  - [ ] If only the **access token** changes: see if we've successfully sent the "install" event, and try to send it again if not.
  - [ ] If only the **URL** changes, or **both** change: send the "uninstall" event before applying the change and the "install" event after.
- [ ] Pass version info and anonymous token to TypeScript (in config)

**Comment by vdavid** [comment]
@philipp-spiess and @ryankscott, I've just realized that "Log install/uninstall events when access token and/or URL changes." will need a bit more thinking because the access token and sourcegraph URL are set **per project** rather than per app. The purpose of this is to allow using the same IDE for OSS projects and private project in parallel. Let's get back to this next week.

**Comment by vdavid** [comment]
...but I guess, if we assume that they will only use one project for their work and we don't care about cloud (https://sourcegraph.com) then we're good with our current approach.
If they use multiple projects for work, we'll duplicate logging so we need to:
a.) be okay with this or
b.) make sure that the ping logic deduplicates this correctly based on the user ID that uniquely identifies each user.

**Comment by philipp-spiess** [comment]
## Per-project authentication

From looking at our VS Code, it seems that we save the settings into the user specific (so application level) by default. However VS Code has a system that allows project level settings for every setting by default.

I am not sure if _per-project_ authentication is a good default. I understand your point with the additional OSS projects but the reality in most companies is that you do not have time/budget to work on OSS and most companies have more than one internal repo, so setting up a new token for all of the individual projects a dev is working on might be _super tedious_ in some cases.

The use case you mentioned with being able to search for open source is something that we, IMO, should solve on the product side. Open source search is available for free for anyone at the moment so why does it become impossible once you log into your private instance? Unfortunately we don't have a product answer for this yet and as a result our users will feel it whenever they get a self-hosted instance :( 

cc @jjinnii @ryankscott I’m curious about your thoughts here as well!

**Comment by ryankscott** [comment]
I'd agree we shouldn't do per project authentication by default, it should be per user specific / application level.

Right now, we don't support the usage of OSS search if you have a private instance (I believe it's even a license violation). I'm not saying this is right / wrong, it's just how it is right now.

**Comment by ryankscott** [comment]
For clarification, I'm not sure I understand the impact of not doing this, especially with respect to tracking. 
- From a user perspective does this mean I have to authenticate for each project I add to a JetBrains IDE?
- From a tracking perspective does that mean we're treating each authenticated project as a different "user"?

If either of those are true, I would strongly recommend this is in v1.
