### ISSUE TITLE
Saved searches: remove copy related to notifications

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#35170]
"Manage notifications and alerts for specific search queries" on list page and "Get notifications when there are new results for specific search queries" on create/edit page are no longer accurate.

<img width="417" alt="image" src="https://user-images.githubusercontent.com/206864/167495691-67b88d33-31eb-4008-a472-8da238ce1f1f.png">

<img width="576" alt="image" src="https://user-images.githubusercontent.com/206864/167495648-d461c082-af6e-4c04-bf5e-149d77338ad9.png">

@benvenker / @marisak / @almeidapaulooliveira  can you recommend new copy here?

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by camdencheek** [comment]
Closing as done.

![Image](https://github.com/sourcegraph/sourcegraph/assets/12631702/a5a8061a-f24b-464c-9304-4b0038dce13d)
