### ISSUE TITLE
Research/evaluate Amplitude as a feature flagging and experimentation system

### ISSUE THREAD

**Issue by erzhtor** [sourcegraph/sourcegraph#35221]

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @a-bergevin - the "team/growth" label was applied to this issue.

**Comment by erzhtor** [comment]
Done. See [docs](https://docs.google.com/document/d/1j6NMCiVM_veN6UyDVHMoYwgakX1-UxUnSCh5R3kfINU/edit#heading=h.ug9yxemk6v19).
