### ISSUE TITLE
Set up alerting route to Content Platform team for about.sourcegraph.com

### ISSUE THREAD

**Issue by sanderginn** [sourcegraph/sourcegraph#35234]
The Content Platform team would like to receive alerts for about.sourcegraph.com. [Link to slack thread](https://sourcegraph.slack.com/archives/C02KX975BDG/p1652181619120989)

Discussed with @filiphaftek, we agreed that the best solution would be
* Set up Opsgenie team for Content Platform team
* Add an extra uptime check for this endpoint to the [GCP alert policies](https://k8s.sgdev.org/github.com/sourcegraph/infrastructure/-/blob/cloud/terraform.tfvars?L16)
* Dynamically add the [notification channels](https://k8s.sgdev.org/github.com/sourcegraph/infrastructure/-/blob/cloud/uptime_checks.tf?L52) from the variable content

This uptime is already defined in [Prometheus](https://k8s.sgdev.org/github.com/sourcegraph/deploy-sourcegraph-cloud/-/blob/base/prometheus/prometheus.ConfigMap.yaml?L417), but to reuse that definition we'd have to extend the monitoring package of `sourcegraph/sourcegraph` with Cloud-specific configuration (i.e. the Content Platform team would have to be added to the observability groups). Going the GCP route is easier and scoped better.

### Action items
- [x] Someone with appropriate rights in Opsgenie should create the team for Content Platform

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/cloud-devops - the "team/devops" label was applied to this issue.
