### ISSUE TITLE
Notebooks file block title should parallel search layout

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#35249]
Notebook file blocks list the file path and the repository. Users have learned to read and use the search results repo and file path header. Reuse that pattern to maintain consistency. 

![image](https://user-images.githubusercontent.com/539268/167673263-43f3a6ec-bb2b-4146-bb64-55711cf33227.png)

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.
