### ISSUE TITLE
Sourcegraph "private mode" does not save "SameSite: None" cookie

### ISSUE THREAD

**Issue by muratsu** [sourcegraph/sourcegraph#35248]
The original issue is reported at gitlab: https://gitlab.com/gitlab-org/gitlab/-/issues/361820

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by muratsu** [comment]
Thank you for the investigation @abeatrix! Can you update the Gitlab thread and let them know that it's expected behavior to not work if the connection is unsecured and everything works fine if we have HTTPS enabled?

**Comment by abeatrix** [comment]
@muratsu Will do! I would like to check with the dev exp team first to confirm my findings since the issue happens with the `sg start oss` instance that has HTTPS enabled, will report back

**Comment by abeatrix** [comment]
Replied to the user and let them know that this is expected when running the open source version of Sourcegraph.
