### ISSUE TITLE
lib/log: investigate logfmt or better-for-local-dev encoders

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#35257]
Right now we just use [Zap's](https://pkg.go.dev/go.uber.org/zap#section-documentation) default "human-readable" `console` format, which is not terribly readable because it dumps all attributes as JSON: 

![image](https://user-images.githubusercontent.com/23356519/167687286-554c5a42-f124-496e-9136-6fcdd2f3506f.png)

There are a few custom encoders out there we might be able to use, e.g. https://github.com/sykesm/zap-logfmt but I haven't experimented with them yet. I also wonder if there are better ones out there for Zap that's not strictly logfmt that we can use instead

See discussion: https://github.com/sourcegraph/sourcegraph/pull/35105#issuecomment-1121406416

**Comment by keegancsmith** [comment]
I tried out `github.com/sykesm/zap-logfmt`. The output format was quite ugly. I think forking the code and making it formatted like zapcore's console logger would be better. Comparison in zoekt:

```
1661244448582109362	INFO	searcher	zoekt-webserver/main.go:448	main.(*loggedSearcher).log	search	{"Resource": {"service.name": "zoekt-webserver", "service.instance.id": "8f8ca20b-2163-4d4b-ab0a-404470ade5af"}, "Attributes": {"query": "TRUE", "traceID": "", "opts.EstimateDocCount": false, "opts.Whole": false, "opts.ShardMaxMatchCount": 1, "opts.TotalMaxMatchCount": 1, "opts.ShardMaxImportantMatch": 0, "opts.TotalMaxImportantMatch": 0, "opts.MaxWallTime": 0, "opts.MaxDocDisplayCount": 1, "stat.ContentBytesLoaded": 27943, "stat.IndexBytesLoaded": 0, "stat.Crashes": 0, "stat.Duration": 0.00023915, "stat.FileCount": 21, "stat.ShardFilesConsidered": 0, "stat.FilesConsidered": 21, "stat.FilesLoaded": 0, "stat.FilesSkipped": 54985, "stat.ShardsScanned": 21, "stat.ShardsSkipped": 0, "stat.ShardsSkippedFilter": 0, "stat.MatchCount": 21, "stat.NgramMatches": 0, "stat.Wait": 0.00001089}}

Attributes.Timestamp=1661244343271048775 Attributes.SeverityText=INFO Attributes.InstrumentationScope=searcher Attributes.Caller=zoekt-webserver/main.go:448 Attributes.Body=search Resource="service.name=zoekt-webserver service.instance.id=b03f8841-c5fe-48a2-8596-7026af95008a" Attributes.query=TRUE Attributes.traceID= Attributes.opts.EstimateDocCount=false Attributes.opts.Whole=false Attributes.opts.ShardMaxMatchCount=1 Attributes.opts.TotalMaxMatchCount=1 Attributes.opts.ShardMaxImportantMatch=0 Attributes.opts.TotalMaxImportantMatch=0 Attributes.opts.MaxWallTime=0 Attributes.opts.MaxDocDisplayCount=1 Attributes.stat.ContentBytesLoaded=27943 Attributes.stat.IndexBytesLoaded=0 Attributes.stat.Crashes=0 Attributes.stat.Duration=0.000201829 Attributes.stat.FileCount=21 Attributes.stat.ShardFilesConsidered=0 Attributes.stat.FilesConsidered=21 Attributes.stat.FilesLoaded=0 Attributes.stat.FilesSkipped=54985 Attributes.stat.ShardsScanned=21 Attributes.stat.ShardsSkipped=0 Attributes.stat.ShardsSkippedFilter=0 Attributes.stat.MatchCount=21 Attributes.stat.NgramMatches=0 Attributes.stat.Wait=0.00001064
```

It seems zap-logfmt just raw dumps the structure as logfmt and ends up being very verbose. I think I'd like something which:

-   removes the attributes prefix
-   specially formated timestamp, severity and message

Then on top of that, personally I'd like to not include things like caller and resource in my dev logs.

**Comment by jhchabran** [comment]
`sgtail` addresses this
