### ISSUE TITLE
User search scopes clobber global and organizational search scopes

### ISSUE THREAD

**Issue by sfllaw** [sourcegraph/sourcegraph#3529]
- **Sourcegraph version:** 3.3.0
- **Platform information:** n/a

#### Steps to reproduce:

1. Create some global search scopes.
2. Go to the home page and see the search scope buttons.
3. Add the following to your user’s settings:
   ``` json
   "search.scopes": []
   ```
4. Go to the home page and look at the search scope buttons.

#### Expected behavior:
You should still see the global search scopes.

Concretely: global, organizational, and user search scopes should be merged.

You might argue that more specific search scopes should be able to suppress more global ones, but that is an unexpected default. No matter what solution is chosen, it should be possible to either include more global search scopes in more specific ones.

#### Actual behavior:
They’ve all disappeared and been replaced by the user’s empty search scopes.

---

Reported by https://app.hubspot.com/contacts/2762526/company/726905220

**Comment by sqs** [comment]
@attfarhan Adding to 3.4, and we should release a patch release to 3.3 as well to fix this because this is a regression.

The final search scopes shown for a viewer should be the concatenation of search scopes from their global, orgs, and user settings.

**Comment by attfarhan** [comment]
Hey @sfllaw, thanks for reporting this. We've shipped a patch release 3.3.5 with a fix for this.

**Comment by sfllaw** [comment]
Confirmed fixed in 3.3.5.
