### ISSUE TITLE
datacenter docs link 404s

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#353]
The link (from sourcegraph/server:2.11.2) goes to https://about.sourcegraph.com/docs/server/datacenter which 404s

![image](https://user-images.githubusercontent.com/187831/46728020-25652300-cc82-11e8-908d-2cf95a9d98bd.png)

I assume this has to do with the website redesign not redirecting subdomains to the deploy-sourcegraph repo?

Reported by a user.

**Comment by attfarhan** [comment]
Fixed by https://github.com/sourcegraph/about/commit/ad866e1d8bb23a411fe186740ca1953da103cc18
