### ISSUE TITLE
Weird behaviour with password reset

### ISSUE THREAD

**Issue by michaellzc** [sourcegraph/sourcegraph#35309]
- **Sourcegraph version:** 3.39.1
- **Platform information:** docker-compose distro

#### Steps to reproduce:

After creation of the managed instance and hand it off to the customer, the customer ran into a unexpected behaviour.

context: https://sourcegraph.slack.com/archives/C02Q9G9A59S/p1652287006028409

1. Created user
1. Generated link without admin rights
1. Failed
1. Added admin rights and regenerated link
1. Failed
1. Recreated user, promoted to admin, generated link
1. Success

#### Actual behavior:

If would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are not [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

**Comment by malomarrec** [comment]
Hey @michaellzc, this issue didn't have a team label. Given you created it, I assigned you and added your team label. Feel free to unassign yourself. If this is not the right label, can you make sure to add the right one?

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/cloud - the "team/cloud" label was applied to this issue.
