### ISSUE TITLE
Update custom feature flagging system to use on lazy evaluation

### ISSUE THREAD

**Issue by erzhtor** [sourcegraph/sourcegraph#35308]
Our current custom feature flagging system evaluates all existing feature flags all at once for the given (anonymous) user. It leads the user to get assigned to a feature flag even when they might not experience the change behind that feature flag. 

> NOTE: currently, we solve/hack around by adding an additional event log that indicates if the user has experienced a new change/feature or not, e.g.: `TourShown`, and then using it in Amplitude as additional filtering.

- [x] #35541
- [x] #35542
- [x] #35543
- [x] #35544
- [x] Communicate the change in #dev-chat #product, etc
- [x] Create a new release marker in Amplitude

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @a-bergevin - the "team/growth" label was applied to this issue.
