### ISSUE TITLE
Sourcegraph popup is hidden on gitlab merge requests

### ISSUE THREAD

**Issue by muratsu** [sourcegraph/sourcegraph#35315]
Gitlab team reported that when using the Merge Request diff view, the Sourcegraph popup seems to be mostly hidden and pushed outside the file container.

More context: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/70002#note_940349106

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
