### ISSUE TITLE
[spike] insights: start collecting backfilling benchmark pings

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#35325]
In order to understand and prioritize improvements to our backfill completion times, we should start collecting actual data. 

We can collect p75, p90, p95 points. 

I wonder if this RFC/design should be led by engineering rather than product/me? You might have the best sense of what performance captures we want to make. Our objective / the goal is primarily to understand how long it takes code insights on an instance to go from "created" to "no longer loading data" (done), so we can prioritize improvements or catch/validate odd behavior on certain instances if customers raise issues. 

We can model this somewhat off how we collect these stats for search queries. 

We already collect the # of repos on a customer instance, so we can cross-reference with that per customer, but other questions/concepts to keep in mind: 

1. If we eventually allow you to backfill over "some" repos, and not all repos, is it useful to collect how many repos that was? Probably (so our ping design should allow for this future expansion). 

Pings RFC for bizops approval coming this iteration as well.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by CristinaBirkel** [comment]
Opened an RFC for this issue with a proposal for implementation: https://docs.google.com/document/d/1pCoMsWWinaigBktIBeI4g5hnXU2LDivpzLqQ_gjtbeg/edit#
