### ISSUE TITLE
JetBrains: SearchBox: Set selected search context

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#35323]
We already load search contexts, but `setSelectedSearchContextSpec` is set to a mock function.
To fix this, see VS Code's SearchResultsView.tsx

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by vdavid** [comment]
https://github.com/sourcegraph/sourcegraph/pull/35326 fixed this.
