### ISSUE TITLE
symbol search slow at scale

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#3534]
Because symbol search is implemented via `repository -> SQLite regex` matching, it can be very slow when hitting large repositories (100+ seconds for repositories on the order of ~20GB). This is in contrast to our zoekt search which is rather fast on a similar size repository I believe.

Most of these perf issues occur in `filterSymbols` here: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/symbols/internal/symbols/search.go#L155

Possible solutions:

1. Optimize simple regex matches to `LIKE` matches, e.g. `f.*b.*r.` becomes `LIKE f%b%r_` to match `foobar1`. This is a good idea but will only help in simple cases.
2. Prioritize proper indexing of symbols via zoekt. I believe this makes sense for multiple reasons:
    1. It would improve symbol search performance substantially in all cases
    2. It would improve perf of basic code intel and allow us to more easily support it on sourcegraph.com as both would be heavily reliant on symbol search perf.

Reported by https://app.hubspot.com/contacts/2762526/company/407948923

**Comment by slimsag** [comment]
I'll tackle the first optimization in 3.4.

More discussion is needed before committing to the 2nd solution here (which would be the proper long term solution I believe).

**Comment by chrismwendt** [comment]
Do you happen to know what the common usage patterns are? Are users searching in the sidebar? Maybe a prefix index would be a sufficient optimization for that.

**Comment by slimsag** [comment]
Via a script I believe.

**Comment by chrismwendt** [comment]
For literal matches, `^foo$` (hits the index) is much faster than `foo` (not indexed, falls back to a scan).

**Comment by ijt** [comment]
@slimsag, are you actively working on this? Are you still planning to finish it for 3.4?

**Comment by slimsag** [comment]
I'll tackle the first optimization in 3.4.

But we do need someone here to be aware of the broader issue & take ownership on the 2nd issue point here.

**Comment by ijt** [comment]
I reproduced this locally with fakehub on the Linux kernel.

![Screen Shot 2019-05-07 at 5 48 38 PM](https://user-images.githubusercontent.com/15530/57341752-83f76000-70f0-11e9-9ff9-7ff0ae72501a.png)

**Comment by slimsag** [comment]
I missed this in 3.4 but may come in a subsequent patch release. Moving to 3.5

**Comment by slimsag** [comment]
@keegancsmith said:
> FYI zoekt has support to run and index ctags output.

**Comment by slimsag** [comment]
Reasons for pursuing symbol search via Zoekt:

- Queries like `type:symbol ^Router$ count:9999999` taking much longer than indexed zoekt text searches (and sometimes timing out). e.g. compare [plaintext](https://k8s.sgdev.org/search?q=%5ERouter%24+count:999999) vs. [symbol](https://k8s.sgdev.org/search?q=type:symbol+%5ERouter%24+count:999999) (this is a real query indicative of what a major customer is trying to do).
- Timeouts on a large customer instance when running non-large-count queries when many of these queries (incl. large-count) are ongoing. Zoekt-based textsearch doesn't behave poorly in this way.
- High memory usage introduced in 3.3, not directly attributed to sqlite-based symbol search but I suspect could be helped by a zoekt-based implementation, see https://github.com/sourcegraph/sourcegraph/issues/4643 for further explanation here.

Note that even though we persue symbol search via Zoekt, we will still maintain the old implementation specifically for cases of non-indexed branches and revisions.

**Comment by chrismwendt** [comment]
Those problems could also be solved by eagerly indexing symbols, right? I'm wondering if it would be faster to implement that.

That said, the eager-indexing infrastructure code might already be implemented for Zoekt (or even inside it?), and reimplementing it for symbols might take longer than switching to Zoekt. Also, there might be customer need to run a lot of non-`^...$` symbols searches (which Zoekt is specifically designed for).

**Comment by keegancsmith** [comment]
> Reasons for pursuing symbol search via Zoekt:
> 
> * Queries like `type:symbol ^Router$ count:9999999` taking much longer than indexed zoekt text searches (and sometimes timing out). e.g. compare [plaintext](https://k8s.sgdev.org/search?q=%5ERouter%24+count:999999) vs. [symbol](https://k8s.sgdev.org/search?q=type:symbol+%5ERouter%24+count:999999) (this is a real query indicative of what a major customer is trying to do).
> * Timeouts on a large customer instance when running non-large-count queries when many of these queries (incl. large-count) are ongoing. Zoekt-based textsearch doesn't behave poorly in this way.
> * High memory usage introduced in 3.3, not directly attributed to sqlite-based symbol search but I suspect could be helped by a zoekt-based implementation, see #4643 for further explanation here.
> 
> Note that even though we persue symbol search via Zoekt, we will still maintain the old implementation specifically for cases of non-indexed branches and revisions.



> Those problems could also be solved by eagerly indexing symbols, right? I'm wondering if it would be faster to implement that.
> 
> That said, the eager-indexing infrastructure code might already be implemented for Zoekt (or even inside it?), and reimplementing it for symbols might take longer than switching to Zoekt. Also, there might be customer need to run a lot of non-`^...$` symbols searches (which Zoekt is specifically designed for).

**Comment by keegancsmith** [comment]
> Those problems could also be solved by eagerly indexing symbols, right? I'm wondering if it would be faster to implement that.

I would be surprised if our current architecture could handle 30k repo symbol requests. For example, just resolving HEAD for 30k repos is not possible, so we would need some caching for that as well. We have the correct architecture to keep up to date a large set of repos.

Additionally zoekt has two things in its favour to our current impl:

- It is purpose built to answer any regex quickly.
- It has some support for ctags already.

> That said, the eager-indexing infrastructure code might already be implemented for Zoekt (or even inside it?), and reimplementing it for symbols might take longer than switching to Zoekt. Also, there might be customer need to run a lot of non-`^...$` symbols searches (which Zoekt is specifically designed for).

Yes, zoekt only does eager indexing so we can't get rid of symbol searcher. However, once you have Zoekt handling HEAD its then becomes quite hard to do searches for large reposets which aren't HEAD (with our current query syntax). So the mix of both is great.


Some extra context from a discussion I had on slack with @kzh:

> zoekt only retains the indices (start, end) of the symbols from the ctags information generated for its rankings. It discards the rest (excluding `language`) including a notable field, `kind` which we use to indicate the type of the symbol (ie `func`, `interface`, etc).

@kzh is now modifying zoekt to index more information. We will see where this takes us.


@slimsag: What is a case where we do symbol searches across all repos. Is it only in the case of `type:symbol` queries, or is it triggered more than that now? Maybe language extensions using symbol search instead of text search?

**Comment by slimsag** [comment]
I missed this, apologies.

> @slimsag: What is a case where we do symbol searches across all repos. Is it only in the case of `type:symbol` queries, or is it triggered more than that now? Maybe language extensions using symbol search instead of text search?

Basic code intel is implemented 100% on top of `type:symbol` queries, or at the very least uses it heavily for cross-repo ops, so this is a major source of these requests and how it ended up central to our product AFAIK.

**Comment by keegancsmith** [comment]
I've bumped to the next milestone since we will be continuing work on this.

**Comment by slimsag** [comment]
https://github.com/sourcegraph/sourcegraph/issues/5364

**Comment by keegancsmith** [comment]
@kzh @slimsag Can we close this out?

**Comment by slimsag** [comment]
Yep.
