### ISSUE TITLE
J.C. onboarding

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#35347]
#### Week 1-2

- [ ] Make sure you went through [software engineer onboarding](https://about.sourcegraph.com/handbook/engineering/onboarding/software-engineer-onboarding). (same for intern)?
- [ ] Set up a backend development intro session with @ggilmore or @keegancsmith 
- [ ] Improve the team's onboarding docs 

#### Week 2+

Smaller task (warm up)?:

- [x] https://github.com/sourcegraph/sourcegraph/issues/13348

Incremental indexing themed:

- [ ] https://github.com/sourcegraph/sourcegraph/issues/35346

**Comment by sourcegraph-bot-2** [comment]
Heads up @jjeffwarner - the "team/search-core" label was applied to this issue.
