### ISSUE TITLE
What to do about TLS. I am running into this

### ISSUE THREAD

**Issue by vrto** [sourcegraph/sourcegraph#35351]

**Comment by vrto** [comment]
@camdencheek My recommendation is to use gRPC with SSL as intended. Even though we're only going to use it for east-west traffic, I think our data in-flight ought to be encrypted, as with [HTTP2, this barely brings any performance penalty whatsoever](https://istlsfastyet.com). Here's a rough outline we can follow:

**Server Authentication**
- we operate as our certificate authority (CA) instead of relying on 3rd party (e.g., Let's Encrypt)
- we can use something like [CloudFlare CFSSL](https://github.com/cloudflare/cfssl) for building TLS certificates. It's somewhat involved; we'd roughly need:
  - configure CA's certificate
  - configure CA policy
  - call `cfssl gencert` for creating the certs

The Go code then needs to reference the certificates:
```
	cert, err := tls.LoadX509KeyPair("./server/cert/public.crt", "./server/cert/private.key")
	if err != nil {
		log.Fatalln(err)
	}
 
	opts := []grpc.ServerOption{
		// Enable TLS for all incoming connections.
		grpc.Creds(credentials.NewServerTLSFromCert(&cert)),
	}
 
	lis, err := net.Listen("tcp", ":50051")
	if err != nil {
		log.Fatalln(err)
	}
 
	srv := grpc.NewServer(opts...)
 
	log.Fatalln(srv.Serve(lis))
```

**Client Authentication (Mutual TLS)**
- needs one cert per client
- update server to be aware of client's cert & key files

Client code (roughly):
``` 
	creds, err := credentials.NewClientTLSFromFile("./client/cert/public.crt", "localhost")
	if err != nil {
		log.Fatalln(err)
	}
 
	opts := []grpc.DialOption{
		grpc.WithTransportCredentials(creds),
		grpc.WithBlock(),
	}
 
	conn, err := grpc.Dial(":50051", opts...)
	if err != nil {
		log.Fatalln(err)
	}
	defer conn.Close()
 
	client := SomeService(conn)
```

Good resources:
- https://grpc.io/docs/guides/auth/#go
- http://www.inanzzz.com/index.php/post/gq4x/using-tls-ssl-certificates-for-grpc-client-and-server-communications-in-golang
- https://www.oreilly.com/library/view/distributed-services-with/9781680508376/ (Chapter 5)

**Other thoughts**

That being said, I'd hate to do all of this manually. Let's involve the security team and explain our intention. I also think that the certs need to vary per _customer_ 🤔 so their generation might need to be a part of the installation process?

**Comment by camdencheek** [comment]
This sounds good to me. Does this make SSL on east-west traffic a prerequisite to gRPC?

**Comment by michaellzc** [comment]
I don't have the full context about what we're doing, but here's some of my thoughts from DevOps perspectives:

- maintaining your own CA sounds scary and it also affects on-prem customers experience.
  - on dotcom, I imagine we will want to use managed service to provide the cert
  - for on-prem, we need some way to auto provision selfsigned cert for the sake of simplicity but it should be configurable

> this is debatable 
- application code itself shouldn't care about TLS, but it will just accept plain non-encrypted traffic and let the service mesh (e.g. istio, linked) to handle mTLS.

anyway, I think @sourcegraph/cloud-devops and @sourcegraph/delivery should be involved in the gRPC effort.

**Comment by kevinwojo** [comment]
I am still building context here but I do have some concerns that should also be considered. Largely I think @michaellzc raises some paths forward but I still have a few questions around the implementation here.

PKI = Private Key Infrastructure -> TLS

1. What is the lifecycle of this PKI? How do we provide guidance to customers regarding expired or revoked certificates? How do we distribute and maintain a Certificate Revocation List? 
2. How would we account for customers that have strict controls over PKI for compliance reasons? Some of our customers require a detailed inventory of PKI and that the settings meet a minimum set of standards (eg: TLS v1.2 or greater, algo requirements, etc)
3. Would we account for third-party PKI management solutions? (cloud-provider cert managers, Hashicorp Vault, etc)

**Comment by kevinwojo** [comment]
@camdencheek is gRPC going to be exposed to the outside as a separate endpoint from the frontend?

**Comment by camdencheek** [comment]
@kevinwojo I'm not a decider here, just an input provider 😄 However, I think the current consensus is that we're only planning to expose gRPC endpoints internally, at least for the first implementation

**Comment by vrto** [comment]
@michaellzc thank you, this is exactly the kind of feedback I was looking for.

> maintaining your own CA sounds scary and it also affects on-prem customers experience

100% agreed, I claim neither expertise nor particular interest in becoming a CA maintainer :D 

@kevinwojo 

> is gRPC going to be exposed to the outside as a separate endpoint from the frontend?

No, just internal.


🎯 My next steps are re-consider whether we absolutely need TLS for the internal traffic.

**Comment by rafax** [comment]
I think we shouldn't block gRPC adoption on supporting mTLS -> we do not support mTLS in our current internal RPCs (so there's no regression), moving to gRPC doesn't make future work to adopt mTLS harder, and we could really use some benefits of gRPC (standardized RPC + IDL from protobuf + built-in streaming)

I agree with the concerns mentioned above - looks like there is no good way to support mTLS across all our deployment environments (managed / on-prem) and "models" (Kubernetes / Compose / single-container), and some of the suggested solutions ("just adopt a Service Mesh") are even more complex. In general, think in the future we may have to consider restricting certain "features" to specific deployment models, or we risk only being able to build for the lowest-common-denominator, which is pretty low for Compose / Docker.

**Comment by malomarrec** [comment]
Hey @vrto, this issue didn't have a team label. Given you created it, I assigned you and added your team label. Feel free to unassign yourself. If this is not the right label, can you make sure to add the right one?
