### ISSUE TITLE
Excessive job queue delays

### ISSUE THREAD

**Issue by jjeffwarner** [sourcegraph/sourcegraph#35377]
There are excessive delays in the queue for indexing repos. Excessive in this case is hours or even days based on the [monitors for .com](https://sourcegraph.com/-/debug/grafana/d/zoekt/zoekt?orgId=1). There is no reported customer impacted but the issue should be explored and the cause identified and discussed with the team to determine a path forward.

Sample graph
![Screen Shot 2022-05-12 at 9 12 33 AM](https://user-images.githubusercontent.com/3095053/168108535-3513b50e-cd63-464a-aa5c-45fda6a2f42f.png)

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket, please let us know how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
