### ISSUE TITLE
zoekt: incremental-indexing: Filetombstones should use document IDs, not strings 

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#35389]
Following up on https://github.com/sourcegraph/zoekt/pull/273#discussion_r806879984

Incremental-indexing introduces a `FileTombstones []string` field to each shard. If a file path is contained in this field, zoekt's searcher process will [skip over that file](https://sourcegraph.com/github.com/sourcegraph/zoekt@108fddf760ab3abc17a8997b53d0ee37f55cd625/-/blob/eval.go?L232-242) when it's looking for search results. 

This works, but the use of strings for this check is inefficient for a variety of reasons (lots of small heap allocations, etc.). The solution to this problem would be to switch FileTombstones to be a slice of document IDs (probably sorted?) instead of strings. 

---

To do this string  -> docID switch, there will need to be a migration process since we're changing the on-disk shard format. We should do this migration before we show this to our customers so that we can minimize the painfulness of the transition.

**Comment by sourcegraph-bot-2** [comment]
Heads up @jjeffwarner - the "team/search-core" label was applied to this issue.

**Comment by ggilmore** [comment]
Fixed via https://github.com/sourcegraph/zoekt/commit/44a2987733da39bda3e384e54249b3d33f01f86f
