### ISSUE TITLE
Make Docker image search performance warning dismissible for an entire instance

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#3538]
We should consider adding a way for site admins to disable the [new single-node Docker image search performance alert](https://github.com/sourcegraph/sourcegraph/pull/3374) for everyone on their instance. Perhaps a settings or configuration option.

Requested by:
* https://app.hubspot.com/contacts/2762526/company/561806411

**Comment by nicksnyder** [comment]
Site admins can workaround this by adding the following script to `htmlBodyBottom` in the [critical config](https://docs.sourcegraph.com/admin/config/critical_config)

```json
"htmlBodyBottom": "<script>localStorage.setItem('DismissibleAlert/performanceWarningAlert/dismissed', 'true')</script>"
```

@dadlerj is this sufficient or should we still add a config option?

**Comment by beyang** [comment]
@dadlerj please re-open if the workaround is insufficient.
