### ISSUE TITLE
insights: refactor historical enquerer to support non-global insights

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#35397]
The [historical enquerer](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/insights/background/historical_enqueuer.go) is the background process that generates historical data for global insights. We want to be able to reuse this capability, but synchronously and scoped to a subset of repositories (known at invocation time).

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by coury-clark** [comment]
Duplicate
