### ISSUE TITLE
Support clickable tokens in hover messages

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#354]
The project https://github.com/alexwl/haskell-code-explorer is very cool and supports clickable tokens in hover messages. This makes it easier to explore the code (by letting you skip a few go-to-definition or go-to-type jumps). As @alexwl said:

> - Types on hover in haskell-code-explorer are not just text or highlighted source code. Each type constructor in a type signature is clickable (left mouse button -> go to definition, right mouse button -> show kind of a type). There is also "expand type synonyms" button/feature, which is Haskell-specific.

**Comment by alexwl** [comment]
I think the relevant code in Sourcegraph's codebase is here:  [https://sourcegraph.com/github.com/sourcegraph/codeintellify@c496d1e4bd5765f7edbb4ae412099a3dbd1dfa22/-/blob/src/HoverOverlay.tsx#L172](https://sourcegraph.com/github.com/sourcegraph/codeintellify@c496d1e4bd5765f7edbb4ae412099a3dbd1dfa22/-/blob/src/HoverOverlay.tsx#L172)
