### ISSUE TITLE
Fix Navbar on desktop+ screen when having many nav items

### ISSUE THREAD

**Issue by erzhtor** [sourcegraph/sourcegraph#35408]
On a very specific screen width (>~990px), when the get started menu entry is rendered, the navbar looks broken
![image](https://user-images.githubusercontent.com/6717049/168250359-d3a3f02c-42cb-458b-9c30-c764c6d8f716.png)

Reported in [slack thread](https://sourcegraph.slack.com/archives/C03CSAER9LK/p1652358412800659) by @eseliger

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @a-bergevin - the "team/growth" label was applied to this issue.
