### ISSUE TITLE
refactor: share dependenciesSource for gitserver and repo-updater 

### ISSUE THREAD

**Issue by stefanhengl** [sourcegraph/sourcegraph#35425]
Both gitserver and repo-updater implement the interface `dependenciesSource` with a lot of duplicate code. We should move the shared code to a dedicated package and import it both in gitserver and repo-udpater.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/search-core - the "team/search-core" label was applied to this issue.

**Comment by keegancsmith** [comment]
cc @mrnugget

**Comment by stefanhengl** [comment]
We have stopped development of dependency search.
