### ISSUE TITLE
dependencies api: Implement `Dependents`

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#35436]
After #35435 is implemented, we can write a `Dependents` method that...

- queries data from `codeintel_lockfiles`/`codeintel_lockfile_references` (see query below)
- queries data from `lsif_packages`/`lsif_references`

...and merges the two results together.

The query that will need to be written to get inverse lockfile data will be something like (shorthanded SQL):

```sql
select repository_id, commit_bytea
from codeintel_lockfiles
where codeintel_lockfile_reference_ids @> (
    select array_agg(id) -- or some other crazy incantation
    from codeintel_lockfile_references
    where repository_id = %s and commit_bytea = %s
)
```

The query needed for precise code intel is described [in this comment](https://github.com/sourcegraph/sourcegraph/issues/31638#issuecomment-1126503354).

**Comment by efritz** [comment]
Opened a draft PR for this issue. See #35447.

**Comment by mrnugget** [comment]
Here's my draft PR with client-side changes: https://github.com/sourcegraph/sourcegraph/pull/35374
