### ISSUE TITLE
Code insights: SVG doesn't shrink properly when the legend block doesn't have enough space

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#35458]
Step to reproduce 
1. Open the dashboard page
2. Find an insight with more than one legend block 
3. Resize the page until the legend block of the insight moves the legend item on the second line
4. See that the moved legend item is out of the card visually

<img width="1156" alt="Screenshot 2022-05-16 at 17 16 23" src="https://user-images.githubusercontent.com/18492575/168560775-1b8ca7fb-3805-4f2f-a243-98c2b5b358df.png">

Expected behaviour 
- SVG chart container should shrink if there is not enough space to render the whole legend block

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by vovakulikov** [comment]
A quick idea to fix this problem: We can make the chart container `flex-shrink: 1`, mark this container with `position: relative`, and make the SVG element `position: absolute`. I believe the problem comes from the fact that SVG is getting exact width and height attributes that make SVG container "not shrinkable"; therefore, there is not enough space for the legend block. 

cc @unclejustin
