### ISSUE TITLE
Insight creation on empty repositories has inconsistent UI feedback between insight types

### ISSUE THREAD

**Issue by Kelvin-Lee** [sourcegraph/sourcegraph#35450]
- **Sourcegraph version:**  3.39.0, also present on [3.39.1](https://github.com/sourcegraph/customer/issues/952#issuecomment-1127004764)
- **Platform information:**  docker-compose, AWS EC2 infra (3.39.0), and docker-compose, GCP infra (3.39.1).

#### Steps to reproduce:

1. Prepare an empty repository.

<img width="1163" alt="Screen Shot 2022-05-15 at 12 36 38 PM" src="https://user-images.githubusercontent.com/7654435/168490800-2c6cc2da-c266-448d-9e02-ed1bf01010d3.png">

2. Attempt to author an Insight. Observe that all three (current) types report errors differently (right hand side of screenshots, red-alert box):

 - Search:
 
 
<img width="1273" alt="Screen Shot 2022-05-15 at 12 32 04 PM" src="https://user-images.githubusercontent.com/7654435/168490760-37ee74db-0655-4dbb-bccf-621f32d44c9b.png">

 
 - Capture Group
 
 
<img width="1258" alt="Screen Shot 2022-05-15 at 12 32 47 PM" src="https://user-images.githubusercontent.com/7654435/168490771-913a8c74-fd5e-4ac1-b599-5fb0e78efe7e.png">

 
 - Language Usage
 
 
<img width="1261" alt="Screen Shot 2022-05-15 at 12 33 18 PM" src="https://user-images.githubusercontent.com/7654435/168490777-0202f2b7-4d1b-4d99-bcf6-2a9f475030d8.png">

 

#### Expected behavior:

All probably ought to report something similarly/human-readable, so as not to spook our users.

#### Actual behavior:

Very spooky.

If would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are not [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by chwarwick** [comment]
@Kelvin-Lee  Thanks for the very detailed write up, there are some differences between how the different types of insights run that is causing the difference in error messages.   I added this to the tracking for resolving those differences.

**Comment by Joelkw** [comment]
@Kelvin-Lee just wanted to also say thank you for the writeup here!
