### ISSUE TITLE
Experiment with GCP alloydb on preprod

### ISSUE THREAD

**Issue by filiphaftek** [sourcegraph/sourcegraph#35454]
#### Infrastructure request description

Switch to [GCP PG compatitble DB](https://cloud.google.com/alloydb) on preprod.

Check list:
- [ ] verify Sourcegraph is working
- [ ] verify performance
- [ ] verify pricing

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/cloud-devops - the "team/devops" label was applied to this issue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @RafLeszczynski - the "team/cloud" label was applied to this issue.

**Comment by RafLeszczynski** [comment]
We do no longer own preprod - closing this issue
