### ISSUE TITLE
Write to lsif_dependency_repos from lsif-python uploads

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#35459]
lsif-python uploads won't currently create entries in the lsif_dependency_repos table like other lsif-* indexer uploads. We need to add an entry to [this map](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@d67ebeb/-/blob/enterprise/cmd/worker/internal/codeintel/indexing/dependency_sync_scheduler.go?L23-26&subtree=true) and test that the data format of name and version is compatible with what we extract from lockfiles in [`parsePoetryLockfile`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/codeintel/dependencies/internal/lockfiles/poetry.go?L13:4&subtree=true).

**Comment by taylorsperry** [comment]
@stefanhengl will you please reassign if @sourcegraph/search-core isn't the right team for this? Thanks!

**Comment by mrnugget** [comment]
Assigned to myself since I'm now working on dependency search. But I'm also not in a team. So I created a `dependency-search` label and attached that.
