### ISSUE TITLE
Single-click jump-to-definition feedback

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#3546]
Post feedback on single-click jump-to-definition https://github.com/sourcegraph/sourcegraph/pull/3444 here.

![2019-04-16 14 57 36](https://user-images.githubusercontent.com/1387653/56553711-31407480-6544-11e9-8172-df77fb300fc6.gif)

This is an experimental feature that we're trying for the Sourcegraph org on Sourcegraph.com with the intent to get a feel for different UX behavior, and ultimately to decide whether or not to keep it.

In about a week (towards the end of April), we'll take stock of the feedback and make a decision. If there's consensus then that's convenient and we can move forward immediately. If not, then Head Of Product:tm: will decide.

To disable it for yourself, set `singleClickGoToDefinition` in user settings to `false`.

**Comment by slimsag** [comment]
https://sourcegraph.slack.com/archives/C0C324C91/p1555994411030400

**Comment by chrismwendt** [comment]
@slimsag Your feedback was about basic-code-intel, not single-click j2d, right?

**Comment by lguychard** [comment]
@chrismwendt retagged as code-intel, but is this still relevant?

**Comment by chrismwendt** [comment]
It's not a priority right now, and implementing this for all code hosts will require more work.
