### ISSUE TITLE
Add "nameTransformations" code host setting support for the browser extension on GitLab

### ISSUE THREAD

**Issue by taras-yemets** [sourcegraph/sourcegraph#35470]
GitLab code host "nameTransformations" setting is not supported by the browser extension.
More details in [this thread](https://sourcegraph.slack.com/archives/C01LZKLRF0C/p1652471996276359).

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by ryankscott** [comment]
We also have a [Product Gap](https://sourcegraph2020.lightning.force.com/lightning/r/a1B5b00000II6lmEAD/view) for this now
