### ISSUE TITLE
Suggestions text

### ISSUE THREAD

**Issue by fkling** [sourcegraph/sourcegraph#35489]
Monco suggestions show the matching test and additional information only if an entry is hovered over. CodeMirror allows us to always show additional information. We need to decide what to show for which type of result.

Monaco:
![2022-05-16_17-25.png](https://images.zenhubusercontent.com/614899f55d273b9067f17b27/9ef5e353-5be0-4ca0-856e-62eafb6a4fe6)

CodeMirror:
![2022-05-16_17-26.png](https://images.zenhubusercontent.com/614899f55d273b9067f17b27/184551f5-8ef2-4df4-b6f2-b78f391e17e2)

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.
