### ISSUE TITLE
Port Monaco search query input tests to CodeMirror

### ISSUE THREAD

**Issue by fkling** [sourcegraph/sourcegraph#35490]
Investigate which tests for the current seach query input exists and duplicate/port/adapt them for CodeMirror.

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by fkling** [comment]
There are still [other tests](https://sourcegraph.com/search?q=context:%40sourcegraph/all+%23monaco+file:%5Eclient/web/src+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+&patternType=literal) which directly reference `#monaco-query-input`, but those don't test editor specific behavior. They'll have to be updated eventually though.
