### ISSUE TITLE
Diffs render incorrectly in preview mode

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#35492]
From customer: https://github.com/sourcegraph/accounts/issues/6859

> I’m still seeing incorrectly rendered diffs in preview mode.  For example, when I delete the function at the end of a Go file, the diff doesn’t show that the trailing } is deleted, it’s just missing from the diff.

**Comment by malomarrec** [comment]
Cc @eseliger

**Comment by eseliger** [comment]
diff view page and changeset previews for batch changes, I think

**Comment by malomarrec** [comment]
That's an awesome change. This was a papercut for some, and a massive pain
for others
