### ISSUE TITLE
CodeMirror design work

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#35497]
[RFC 637 Review solutions: Replace Monaco with CodeMirror](https://docs.google.com/document/d/1vwR0YnaAv2GOzGg8ggsjUJeKmPZgZv9W-YOFmGnZwxI/edit#heading=h.trqab8y0kufp)

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by lguychard** [comment]
This appears to have been stale for a while and has little context in the issue; The initial version of the CodeMirror query input has been released; closing.
