### ISSUE TITLE
Code Insights: [tracking] All insights load fast 

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#35504]
### Plan
Make it so that _All insights data loads equally as fast as the fastest insights’ data loads now._ 

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by vovakulikov** [comment]
@chwarwick is this something that you want to tackle on the FE side? or this is about BE data resolvers?

**Comment by chwarwick** [comment]
@vovakulikov this is just a tracking issue that didn't yet pick up the related issues. It's going to be primarily backed work replacing the just in time insights.
