### ISSUE TITLE
Code Insights:  [tracking] Live Preview for all insights

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#35503]
### Plan
Unlock live preview for all insights, even those that will run over all repositories

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by chwarwick** [comment]
removing as duplicate
