### ISSUE TITLE
Code Insights: [tracking] Common Features (Filters/Sorting) for all search insights

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#35505]
### Plan
You can see and use the filter panel on all search insights

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by chwarwick** [comment]
replaced by #35387
