### ISSUE TITLE
Code Insights: [tracking] Full data series with snapshots for all search insights

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#35506]
### Plan
You can continue to collect future + past data on all insights (rather than re-running 7 points in time from today; run the original number of points and then continue collecting snapshots)

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by chwarwick** [comment]
replaced by #35387
