### ISSUE TITLE
Syncer: Backoff during sourcing errors

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#35529]
External service syncs should still back off if "sourcing" fails.

Currently, if we fail [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@c76c1cf19bb47a9e78600206d2427e3f86855b0f/-/blob/internal/repos/syncer.go?L520), we return early and don't calculate a next sync time. This can cause an external service to get stuck with an old `last_synced_at` value which triggers alerts.

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.
