### ISSUE TITLE
JetBrains: Make the search box dropdown multiline

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#35546]
# Context

The web view is a large webview by default. Many items in the dropdown should fit in it.

# Problem

The dropdown is often (but not always!) rendered as a single-line thing.

It looks like this:
<img width="1200" alt="CleanShot 2022-05-17 at 14 26 52@2x" src="https://user-images.githubusercontent.com/2552265/168810578-1b84664f-8732-4cbd-9880-77d9ffd5945c.png">
(But there are several items in it, and it scrolls!)

# Solution

Not sure why this happens. Figure out the cause and make it always use the space it has.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by vdavid** [comment]
For the record, I've filed an issue with Monaco Editor: https://github.com/microsoft/monaco-editor/issues/3147
And another one with VS Code: https://github.com/microsoft/vscode/issues/152324
The bug _technically_ belongs to VS Code, but it's not likely to get any attention because it's difficult to reproduce the issue there and it's a tiny edge case.
I hope the Monaco Editor dev team will also accept the bug, though, because it's a lot more severe bug for them.
