### ISSUE TITLE
JetBrains: Resize the web view with the popup

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#35545]
# Context

When we resize the “Find on Sourcegraph” popup **horizontally**, the web view **grows** with it.

# Problem

When we narrow it down, however, then it **doesn't shrink**.

# Solution

Make the web view shrink with the popup.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by taras-yemets** [comment]
@vdavid, I can reproduce this issue neither in Brave nor in Chrome ([Loom](https://www.loom.com/share/6923b6a05e1d4a799552210891e78bc0)). The only difference in Chrome is that it takes a bit longer to resize.

**Comment by vdavid** [comment]
For the record: we discussed this on Slack and we could reproduce it in the browser.
