### ISSUE TITLE
JetBrains: search results: display commit search results

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#35547]
We currently only show the in-file search results.

Also display `type:commit` search results, and feed the commit message to the preview.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by vdavid** [comment]
Test it with: `type:commit repo:github.com/sourcegraph/sourcegraph test plan`

**Comment by vdavid** [comment]
Also discovered that our current app fails with the Korean version of this file:
`repo:github.com/996icu/996.ICU Protest Over Chinese Tech Companies`
because it uses "\r\n" line breaks.
