### ISSUE TITLE
Syntax highlighting broken in browser extension

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#3554]
Visit here: https://github.com/sourcegraph/sourcegraph/pull/3533/commits/e7415b654b66cf47ea732c417a62da6a3bde68a6

![image](https://user-images.githubusercontent.com/1646931/56602255-e5c4af80-65b1-11e9-9c43-1b0e015f9e41.png)

**Comment by lguychard** [comment]
Interestingly, it's not broken for all tokens.

![image](https://user-images.githubusercontent.com/1741180/56602670-4da0e780-65fe-11e9-8d1d-3bbd701c901d.png)

@chrismwendt do you reckon this could be due to the hover content that is return for this specific token?

**Comment by chrismwendt** [comment]
I'll check to see if basic-code-intel is wrapping the code with triple backticks and `go`.

**Comment by chrismwendt** [comment]
I don't see anything wrong with basic-code-intel's markdown here.

![image](https://user-images.githubusercontent.com/1387653/56603288-4e149080-65b4-11e9-9bf2-19f09bea9436.png)

Here it is rendered in this issue:

**BEGIN**

```go
ListRepos(context.Context) ([]*Repo, error)
```

---

ListRepos returns all the repos a source yields.

**END**

I think it **is** being syntax highlighted, but all of the tokens in that particular hover are plain identifiers (not keywords). One might expect `error` to be highlighted.

> As a side note, that `ListRepos` hover is coming from another definition in a different file. That explains why we don't see that hover line start with `func (s * PhabricatorSource) ListRepos(...`. Even if basic code intel weren't showing the wrong definition, we'd see this same syntax highlighting problem elsewhere.

Unless we're willing to switch markdown renderers, I don't think there's much we can do here.
