### ISSUE TITLE
JetBrains: search results: display path search results

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#35551]
We currently only show the in-file search results.

Also display `type:path` search results, and leave the preview empty.

Example search that should work: `type:path sourcegraph`

Each hit should be one line, and we should only have repo headers, no file headers.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
