### ISSUE TITLE
Hover information sometimes appears to be incorrect or lagging

### ISSUE THREAD

**Issue by fkling** [sourcegraph/sourcegraph#35555]
https://images.zenhubusercontent.com/41288708/62d1b705-a75a-436e-b730-6cbeeafbb409/cm_hover.mp4

See video. This could be because we are not computing the right boundaries for the ranges, but given that the hover information is correct when you start hovering `text` (in the example), it might also be an issue with the built-in hover extension or a misconfiguration.

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.
