### ISSUE TITLE
JetBrains: wire up the preview box in the standalone web app

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#35556]
## Context

We use `yarn standalone` to run a dev environment when developing/testing web view features.

## Problem

We have previews in the real app, but the standalone version doesn't implement the communication between the preview box and the top part of the UI

## Solution

Wire it up.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
