### ISSUE TITLE
JetBrains: search results: display symbol search results

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#35552]
We currently only show the in-file search results.

Also display `type:symbol` search results, and fill the preview with the code.

[Example search](https://sourcegraph.com/search?q=context:global+type:symbol+sourcegraph&patternType=literal) that should work: `type:symbol sourcegraph`

Try to reuse as many parts as we can from the web part.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
