### ISSUE TITLE
Write RFC for long term plan on "Control users that sign in to SG"

### ISSUE THREAD

**Issue by kopancek** [sourcegraph/sourcegraph#35557]
We need a long term plan and technical roadmap for the "Control users that sign in to sourcegraph" feature. 

**Expected outcomes**
- RFC with technical roadmap written and reviewed by our team, at least a few engineers outside of the team, security, etc.
- RFC will contain: definition of the problem, architecture of the long term solution, technical proposal and steps on how to achieve the proposal

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam-and-admin-experience - the "team/iam-admin-experience" label was applied to this issue.

**Comment by RafLeszczynski** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IAM-and-Admin-Experience-627aebcc9f8b7c00128a8ab6/issues/sourcegraph/sourcegraph/35557?planning-poker) with ZenHub @kopancek @miveronese @pjlast @unknwon

**Comment by RafLeszczynski** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IAM-and-Admin-Experience-627aebcc9f8b7c00128a8ab6/issues/sourcegraph/sourcegraph/35557?planning-poker) with ZenHub @pietrorosa77
