### ISSUE TITLE
Technical scoping for usage analytics improvements

### ISSUE THREAD

**Issue by RafLeszczynski** [sourcegraph/sourcegraph#35569]
Please take a look at the identified problems and proposed next steps on how to organize the discovery process.

https://docs.google.com/document/d/1KbJRkbHXzGct2heCa0e8c_bMMd5zdgbvRaubxOuvoTo/edit#heading=h.izkaferm7bx8

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam-and-admin-experience - the "team/iam-admin-experience" label was applied to this issue.

**Comment by unknwon** [comment]
Update: I'm currently taking on the part ["Insight into active users"](https://docs.google.com/document/d/1KbJRkbHXzGct2heCa0e8c_bMMd5zdgbvRaubxOuvoTo/edit#heading=h.8hduwdlrbr3).

I'll leave myself assigned until we have a dedicated issue for it, or we can keep multiple assignees.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.
