### ISSUE TITLE
Perform accessibility audit on IAM & Admin Exp features

### ISSUE THREAD

**Issue by kopancek** [sourcegraph/sourcegraph#35563]
@kopancek as our accessibility champion is responsible for performing an accessibility audit on features that our team owns. The result of this audit is a set of github issues created, that we or other teams (and an external company) can tackle. Doing the accessibility audit is a sourcegraph Q2 goal and @kopancek promised to do it until the end of May.

More details on the audit itself are in the slack thread here: https://sourcegraph.slack.com/archives/C038K3PR2M7/p1650964728902099

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam-and-admin-experience - the "team/iam-admin-experience" label was applied to this issue.

**Comment by RafLeszczynski** [comment]
@kopancek do we have a list of features/functionalities that we need to audit. Having such list would be great not only for tracking the progress on this task but in general to understand what features/functionalities we as a newly created team should be looking into from the UI/UX perspective

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.
