### ISSUE TITLE
sourcegraph.configuration should correctly implement Subscribable

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#3557]
`sourcegraph.configuration` does not properly implement `Subscribable`. This means that when trying to use it with rxjs operators, hacky workarounds are needed:

```typescript
const configurationChanges = new BehaviorSubject<void>(undefined)
    context.subscriptions.add(sourcegraph.configuration.subscribe(() => configurationChanges.next(undefined)))
```

**Comment by felixfbecker** [comment]
This is also annoying for the stubs because it can't just be stubbed out with a Subject...

**Comment by felixfbecker** [comment]
(found a solution though) https://github.com/sourcegraph/extension-api-stubs/pull/3

**Comment by lguychard** [comment]
We should remove workarounds in our extensions when we fix this.
