### ISSUE TITLE
Code Mirror search bar color highlighting is different and low contrast (in dark mode)

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#35587]
Previously:
<img width="331" alt="Screen Shot 2022-05-17 at 12 34 28 PM" src="https://user-images.githubusercontent.com/888624/168895531-404b3090-becd-4754-a8f4-8f312a378bb1.png">

Now:
<img width="322" alt="Screen Shot 2022-05-17 at 12 33 39 PM" src="https://user-images.githubusercontent.com/888624/168895548-76e48a9b-2378-4d85-b956-de84ca07b6e5.png">

This is creating low contrast in Code Mirror that falls below desired builtin threshold for browsers:
<img width="307" alt="Screen Shot 2022-05-17 at 12 35 55 PM" src="https://user-images.githubusercontent.com/888624/168895832-f050a46f-7734-4298-93c3-2ae72a12a6ce.png">

versus previous:

<img width="341" alt="Screen Shot 2022-05-17 at 12 36 03 PM" src="https://user-images.githubusercontent.com/888624/168895845-773f1914-4391-4ae6-9d8c-c540fffd4923.png">

Can we preserve the color scheme?

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.
