### ISSUE TITLE
Evaluate managed observability tools (GCP Prometheus, Grafana Cloud)

### ISSUE THREAD

**Issue by danieldides** [sourcegraph/sourcegraph#35589]
Currently we run a self-hosted instance of Prometheus alongside each Managed Instance. This service is essential towards our observability and alerting stack, driving all our alerts, Grafana dashboards, and some core functionality of services. Evaluate the cost and feasibility of moving to a hosted solution for metric aggregation and visualization.

Candidates include (but are not limited to):
- [GCP Prometheus](https://cloud.google.com/stackdriver/docs/managed-prometheus)
- [Grafana Cloud](https://grafana.com/metrics/)
- Datadog

Considerations:
- Cost per instance increase or decrease (weighed against the VM + storage cost of hosting our own)
- Accessibility and integration with existing tools (proxied grafana instances, alertmanager, tracing, logging, etc)
- Ease of provisioning (terraform support)

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/cloud-devops - the "team/devops" label was applied to this issue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @RafLeszczynski - the "team/cloud" label was applied to this issue.

**Comment by rafax** [comment]
@danieldides do we still need this issue, or is this covered by your Centralized observability work?

**Comment by michaellzc** [comment]
I think we can close this cc @danieldides

**Comment by danieldides** [comment]
This was a scoping issue for the initial implementation of Centralised Observability. It's not needed now, we went with GCP Managed Prometheus. More info: https://github.com/sourcegraph/customer/issues/1151
