### ISSUE TITLE
JetBrains: SearchBox: Load last config

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#35583]
When you open the same project in IntelliJ, the last search settings (context, case sensitivity, regex setting, query) should load up from `sourcegraph.xml`.

This usually doesn’t work right now. There is probably a race condition that prevents this. In particular, the query gets overwritten with an empty string.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by philipp-spiess** [comment]
@vdavid Is the idea here to persist the last search _in the case the project is closed/opened_ again? Simply re-opening the modal after it was already open in a session does reuse the browser anyways already.

**Comment by vdavid** [comment]
@philipp-spiess Yes, in case the project or the IDE is closed and reopened.
Hence the low priority.
The only reason why I'd tackle it sooner than later is that we have the feature half-implemented, and it's buggy.
It currectly loads the “is case sensitive” and similar settings, but not the query. And if you check the bridge requests being made, you'll see that it actually loads the query correctly, too, but then immediately overwrites it with an empty string.
It doesn't cause any major issues, but it bugs me to know that there's this weird behavior in the background :)

**Comment by philipp-spiess** [comment]
> @philipp-spiess Yes, in case the project or the IDE is closed and reopened.

Wow I did not think this was a thing but the native find in files works the same way 😮
