### ISSUE TITLE
insights: refactor backfiller to support non-global repository sets

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#35580]
Refactor the backfiller ([historical_enquerer](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/insights/background/historical_enqueuer.go)) to support non-global repository iterators given a list of repository names.

For simplicity we can allow the non-global iterator to resolve repository information completely before construction, and fail if any repository information cannot be resolved.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by coury-clark** [comment]
For the first iteration we can also assume that the rate limiter is locally scoped to each invocation of this historical backfiller. The actual Sourcegraph queries will remain rate limited globally by means of the limiter on the queue consumer, this limiter will only affect the git operations done in the request scope.
