### ISSUE TITLE
Bitbucket Server external service cannot exclude an entire project

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#3558]
When you plug an access token into a Bitbucket Server external service, you have to manually list out all of the repositories that you want to exclude one-by-one.

In some cases this is not practical because you want to disable an entire project from being accessed via Sourcegraph (e.g. in case any new repositories are added to that project).

If we had [Bitbucket ACL support](https://github.com/sourcegraph/sourcegraph/issues/1108), the need for this would be mitigated a bit -- but it would still be nice to have when not using bitbucket ACL support.

This could be as simple as allowing regex exclusion:

```
  "exclude": [
    {
      "regex": "SECRETS/.*"
    }
  ]
```

Originally reported by https://app.hubspot.com/contacts/2762526/company/407948923 but the priority here is just nice-to-have as https://github.com/sourcegraph/sourcegraph/issues/1108 is the real desire for them.

**Comment by tsenart** [comment]
You can select the repos belonging to the project that you want only using `repositoryQuery`. Does that not solve the problem?

**Comment by slimsag** [comment]
That lets me select a project to include, but does not let me select a project to _exclude_. So nope.

**Comment by tsenart** [comment]
> That lets me select a project to include, but does not let me select a project to exclude. So nope.

But if you don't include a project's repos via `repositoryQuery` nor via `repos`, those repos won't show up. So, I'm not following.

**Comment by slimsag** [comment]
Perhaps a better way to communicate the problem:

I want all repositories that are on my Bitbucket instance on Sourcegraph, excluding one project's repositories in specific. What would be the configuration to achieve this?

**Comment by tsenart** [comment]
> I want all repositories that are on my Bitbucket instance on Sourcegraph, excluding one project's repositories in specific. What would be the configuration to achieve this?

You'd have to configure your `repositoryQuery` to match all projects, except that one you want to exclude. How many projects would you need to match? If it's a handful it should be quite straightforward.

```json
"repositoryQuery": [
    "?projectname=PROJECT-0",
    "?projectname=PROJECT-1",
     ...
    "?projectname=PROJECT-N"
]
```

**Comment by tsenart** [comment]
Docs on the query syntax for Bitbucket Server: https://docs.atlassian.com/bitbucket-server/rest/6.1.2/bitbucket-rest.html#idp355

**Comment by tsenart** [comment]
@slimsag: Ping.

**Comment by slimsag** [comment]
> How many projects would you need to match? If it's a handful it should be quite straightforward.

Thousands, with tens being created and deleted each day. Doing this manually is not feasible and would require me to write a script to update this config after dumping the list from bitbucket.

**Comment by tsenart** [comment]
Gotcha.

**Comment by keegancsmith** [comment]
Proposal:

An exclude list item is currently `{ name: string, id: int }`. Update it to also allow `{ pattern: regex }`. If a name matches the regex, we exclude it. Pattern is mutually exclusive to specifying name or id. WDYT @tsenart?

**Comment by tsenart** [comment]
@keegancsmith: Sounds good!
