### ISSUE TITLE
insights: just-in-time capture group pattern insights incorrectly handle multiple repositories, returning incorrect partial results

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#35602]
If you create a just-in-time capture group insight like the following: 

![image](https://user-images.githubusercontent.com/11967660/168933072-f97dedd0-386f-40fc-b518-95a832b0d676.png)

The results returned are *incorrect* and undercount the true results. 

What happens is: 

1. In reverse-listed order in the UI form (so starting at the end of the list first), we return results for capture groups for just the last-matching repository. This means in the above example: 
      1. the sourcegraph/about repo[ has 193 matches](https://sourcegraph.com/search?q=context:global+repo:%5E%28github%5C.com/sourcegraph/handbook%29%24+code%5Csinsights&patternType=regexp) for  `code\sinsights`  – as shown in the tooltip for 193, but it [misses 482 results from sourcegraph/sourcegraph
](https://sourcegraph.com/search?q=context:global+repo:%5E%28github%5C.com/sourcegraph/sourcegraph%29%24+code%5Csinsights+count:all&patternType=regexp)
     1. Because there are [_no_ results for `code\sinside` in /handbook](https://sourcegraph.com/search?q=context:global+repo:%5E%28github%5C.com/sourcegraph/handbook%29%24+code%5Csinside&patternType=regexp), it correctly reports [the 1 result from /sourcegraph](https://sourcegraph.com/search?q=context:global+repo:%5E%28github%5C.com/sourcegraph/sourcegraph%29%24+code%5Csinside&patternType=regexp) – it skips the "last repo" because it has no results and uses the "first repo with results" (in this case, the only other repo. 

What should happen is: 
1. We correctly sum the results across all repos, for each capture group. So in this case `code\sinsights` should have 675 matches (for `ghts).

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by Joelkw** [comment]
You can find that broken example insight at the end of this dashboard: https://k8s.sgdev.org/insights/dashboards/ZGFzaGJvYXJkOnsiSWRUeXBlIjoiY3VzdG9tIiwiQXJnIjo3MjY2NTZ9

**Comment by leonore** [comment]
To keep a record of my findings, so far I've been able to establish:
* we return correct values from [this call](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@26ec51664965c53b20e6574da492f3d27ac1b696/-/blob/enterprise/internal/insights/query/capture_group_executor.go?L120)
     * from the logs I was able to see we get the high match counts expected for the sourcegraph repo
* currently in dev we hit stream compute for JIT capture group insights, but I confirmed the results returned are the same for both stream and non stream.
So somewhere after this data is fetched we construct it incorrectly into a response and data is lost. where tbd

**Comment by leonore** [comment]
Haven't narrowed it down quite yet but my belief is that the error comes from [this code block](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@26ec51664965c53b20e6574da492f3d27ac1b696/-/blob/enterprise/internal/insights/query/capture_group_executor.go?L133-141&utm_source=VSCode-2.2.2) where we assign values to certain times.

We share timestamps for data points across repos. This line in a for loop looks suspicious to me: `pivoted[value][execution.RecordingTime] = timeGroupElement.Count` as I believe this would overwrite the data in `pivoted` on every iteration i.e. get the data for the last repo only.
