### ISSUE TITLE
Verify color mapping for syntax highlighting

### ISSUE THREAD

**Issue by fkling** [sourcegraph/sourcegraph#35620]
Reported [here](https://sourcegraph.slack.com/archives/C03CSAER9LK/p1652833254336289).

It looks like I didn't get the right CSS color variables for the corresponding token types. We need to go over [the color mapping](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@b5a8c49ca5c91fc362d50f590ee8f7c69194f1e1/-/blob/client/shared/src/components/MonacoEditor.tsx?L24-145) again and verify that the right colors are used.

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by fkling** [comment]
There is already an issue for this specific case: https://github.com/sourcegraph/sourcegraph/issues/35587
