### ISSUE TITLE
zoekt: faster indexing when many repos need indexing

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#35632]
I believe there is scope for zoekt to more quickly index large amounts of repos which are not yet indexed. Normally users/admins do not notice this, but here are some places this is noticeable:

- When creating a new instance of Sourcegraph zoekt needs to index all the repos that are added.
- An admin adding a large codehost organisation/project to Sourcegraph.
- Rebalancing after scaling the zoekt cluster
- Debug cycles during setups.

For the last point, we recently observed a customer resolving an issue with the zoekt cluster that resulted in it needing to index many thousands of repos. This is what motivated the issue, because we believe there is scope to increase the speed of this.

Note: This doesn't apply once zoekt is in its steady state. Most of the time an indexserver is in fact not indexing, it is waiting for things to index.

Opportunities:
- We shallow clone then index a repo. We could shallow clone a repo while indexing another (hide latency).
- Most repos are small, so we don't take advantage of indexbuilders concurrency. We could index several repos concurrently. however, we do not want this behaviour for large repos.

I'm hoping we have some wins here which do not add significant complexity to indexserver.

**Comment by keegancsmith** [comment]
@eugeniaft this is something @stefanhengl and I talked about recently. Do you mind finding out how we could prioritize this work?

cc @sourcegraph/search-core

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket, please let us know how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
