### ISSUE TITLE
insights: refactor create / edit mutations to deprecate just-in-time insights

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#35655]
In the create and edit mutations for insights we do some simple work to determine if an insight should be recorded in the background, or just-in-time https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24%40a879f18+file:%5Eenterprise/internal/insights/resolvers/insight_view_resolvers%5C.go+just&patternType=literal. We would like to deprecate just-in-time insights and prefer to record all insights (limited to line charts at the moment).

To simplify the scope of this issue, we will make the following assumptions:
1. Any series that is defined as non-global (non-null repository scope) will be given a unique `series_id` and we will *not* perform semantic matching as we do for global series. This means that:
    1. We will not reuse data that has already been calculated by another series
    2. The `series_id` must be provided on edit mutation, else it will be considered a brand new series (same semantic as is today)
2. Any modifications to the series will necessarily trigger a recalculation (and purge the old data). For example if the repository scope changes, we will not try to preserve a subset of the intersecting repositories and only calculate the difference.
3. The operation to queue up the work will be performed transactionally7 in the scope of the request, but the queries themselves will execute asynchronously in the background. This means that users will receive an error from the mutation if there is any problem up to actually performing the searches.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
