### ISSUE TITLE
insights: refactor backfill statistics to remove package access

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#35664]
Refactor the [backfill statistics struct](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/insights/background/historical_enqueuer.go?L190%3A7=&utm_product_name=GoLand&utm_product_version=GoLand) such that we can calculate discrete stats on separate instance of historical enqueuer.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by coury-clark** [comment]
Just kidding, this is already done 🤦
