### ISSUE TITLE
Update documentation for 'control user sign-ups' short term changes

### ISSUE THREAD

**Issue by ryphil** [sourcegraph/sourcegraph#35676]
This ticket will include documentation updates based on the following changes: 
#34917 
#34918 
#34922 
#35548

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam-and-admin-experience - the "team/iam-admin-experience" label was applied to this issue.

**Comment by RafLeszczynski** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IAM-and-Admin-Experience-627aebcc9f8b7c00128a8ab6/issues/sourcegraph/sourcegraph/35676?planning-poker) with ZenHub @kopancek @miveronese @pjlast @unknwon

**Comment by RafLeszczynski** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IAM-and-Admin-Experience-627aebcc9f8b7c00128a8ab6/issues/sourcegraph/sourcegraph/35676?planning-poker) with ZenHub @pietrorosa77

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.
