### ISSUE TITLE
VSCE Bug: Sourcegraph icon in help sidebar is not visible on light theme

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#35672]
- **Sourcegraph version:**  3.39.1 
- **Platform information:**  VSCE v2.2.2

#### Steps to reproduce:

1. Use light theme on VS Code 
2. Check the Help and Feedback sidebar in the Sourcegraph extension

#### Expected behavior:

Can see the sourcegraph icon next to `Create an account`
![image](https://user-images.githubusercontent.com/68532117/169161961-b4219840-0df0-45ed-ae88-7c56686c8be0.png)

#### Actual behavior:
The sourcegraph icon next to `Create an account` is barely visible because of the color
![image](https://user-images.githubusercontent.com/68532117/169162036-8912828a-df83-4548-a75f-00fc672dd103.png)

#### Note

The icon should change depends on the current theme 

If would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are not [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by abeatrix** [comment]
Fixed in https://github.com/sourcegraph/sourcegraph/pull/35339
![Screen Shot 2022-05-19 at 1 11 38 PM](https://user-images.githubusercontent.com/68532117/169563393-192be46b-4d14-4562-93c6-cb1fdefdeff2.png)
