### ISSUE TITLE
zoekt: expose indexserver debug cmds via http

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#35692]
We have a debug cmd for indexserver. However, it requires admins execing into pods to run them. This is fine for us, but we should provide a cleaner way to get the detailed debug info. This issue proposes exposing the information via the debug HTTP endpoint, which is currently proxied via the instrumentation page for sourcegraph admins.

**Comment by sourcegraph-bot-2** [comment]
Heads up @jjeffwarner - the "team/search-core" label was applied to this issue.

**Comment by keegancsmith** [comment]
@stefanhengl I think this PR solves this issue? https://github.com/sourcegraph/zoekt/pull/346

All that is left likely is a changelog entry?

**Comment by stefanhengl** [comment]
https://github.com/sourcegraph/sourcegraph/pull/36067
