### ISSUE TITLE
Responsive actions toolbar on Search results

### ISSUE THREAD

**Issue by almeidapaulooliveira** [sourcegraph/sourcegraph#35696]
#### Component description
A responsive actions toolbar for general use. 

- Flexible: support one or more action buttons. 
- Responsive: buttons pile up into a sub-menu in reaction to the available space.
- Dynamic: possibility to hide buttons depending on the context.

**Press play to see the component functioning:**

https://user-images.githubusercontent.com/64257673/169549016-600010a0-c91c-41e3-8d98-37a4d33a909a.mp4

### Primary use
On search results toolbar:

<img width="1268" alt="Screen Shot 2022-05-19 at 07 39 05" src="https://user-images.githubusercontent.com/64257673/169274889-8bc722b2-bd9c-413d-ab69-89142e9a5d98.png">

#### Have designs already been created? If so, please link them here.
[Figma file.](https://www.figma.com/file/5mzMLOSQfaCGZiQs6b26CP/Create-a-batch-change-from-the-search-result?node-id=1101%3A190)

#### Related to
- [Create a batch change from the search result page.](https://github.com/sourcegraph/sourcegraph/issues/22352)
- [Search results Create monitor tooltip should be below the button.](https://github.com/sourcegraph/sourcegraph/issues/34777)

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by almeidapaulooliveira** [comment]
Cc: @rrhyne

**Comment by almeidapaulooliveira** [comment]
This design debt (https://github.com/sourcegraph/sourcegraph/issues/34777) will be fixed here.
