### ISSUE TITLE
Implement FetchUserPerms for Gerrit provider

### ISSUE THREAD

**Issue by mollylogue** [sourcegraph/sourcegraph#35744]
Implement FetchUserPerms method, stubbed out [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/authz/gerrit/gerrit.go?L29)

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.

**Comment by mrnugget** [comment]
Implemented as part of https://github.com/sourcegraph/pr-faqs/issues/41
