### ISSUE TITLE
Implement FetchRepoPerms for Gerrit provider

### ISSUE THREAD

**Issue by mollylogue** [sourcegraph/sourcegraph#35746]
Implement FetchRepoPerms method, stubbed out [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/authz/gerrit/gerrit.go?L33)

**Comment by mrnugget** [comment]
Implemented as part of https://github.com/sourcegraph/pr-faqs/issues/41
