### ISSUE TITLE
Implement ValidateConnection for Gerrit provider

### ISSUE THREAD

**Issue by mollylogue** [sourcegraph/sourcegraph#35747]
Implement method for ValidateConnection, stubbed out [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/authz/gerrit/gerrit.go?L53)

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.
