### ISSUE TITLE
Allow underscores in usernames

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#35751]
#### Feature request description

Usernames currently [do not allow underscores](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/site-admin/SiteAdminCreateUserPage.tsx?L138:33).  Some naming conventions require that usernames use underscores.  This is the case at [customer #6716](https://github.com/sourcegraph/accounts/issues/6716).

#### Is your feature request related to a problem? If so, please describe.

Details are in [this Slack thread](https://sourcegraph.slack.com/archives/C01D50MSA7L/p1652910934966579).

#### Describe alternatives you've considered.

N/A

#### Additional context

N/A

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.

**Comment by unknwon** [comment]
Relevant code: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/auth/auth.go?L74:6&subtree=true
