### ISSUE TITLE
When docs page is short, the footer takes half the page and blocks the sidebar

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#3575]
![image](https://user-images.githubusercontent.com/10532611/56675635-ec8c1900-66bc-11e9-872f-1b4f8552cc4e.png)

https://docs.sourcegraph.com/extensions/authoring/tutorials

**Comment by ryan-blunden** [comment]
What would you propose is the right way to fix this?

**Comment by felixfbecker** [comment]
Something like `min-height: 90vh` or even `100vh` on the content

**Comment by ryan-blunden** [comment]
Thanks! I've applied that fix to #3568 

Preview: http://newdocs.sgdev.org:5080/extensions/authoring/tutorials/hello-world
