### ISSUE TITLE
Completion widget is not readable in VS Code Light theme

### ISSUE THREAD

**Issue by tianzerun** [sourcegraph/sourcegraph#35767]
### Issue type

Bug fix

### Problem description

I am using the Sourcegraph VS Code extension. When I try to enter something in the search box that triggers the completion/suggest widget, I notice its color combination is making it unreadable. It would be nice to use contrasting colors to improve readability.

After some preliminary search, I found out it might be a monaco editor issue, mentioned here https://github.com/microsoft/monaco-editor/issues/2822. It seems like some color registrations are removed so they didn't take effect. It should be fixed if you could upgrade the monaco-editor dependency from ^0.24.0 to ^0.31.1.

![sourcegraph-vsce-unreadable](https://user-images.githubusercontent.com/23252886/169438765-26b259c4-bc6c-4fd1-87c6-a4e845b2c74c.gif)

### Context

Sourcegraph extension: v2.2.2
VS Code theme:  Light/Light+ theme

### Assigning labels

- [ ] If this issue will require input from designers in order to complete, please assign the label `needs-design`.

**Comment by valerybugakov** [comment]
@tjkandala, do you think it's something the @sourcegraph/integrations team can look at?
The @sourcegraph/frontend-platform doesn't maintain the VSCode extensions and the component used for the autocompletion widget.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by abeatrix** [comment]
@valerybugakov Thanks for letting us know
@tjdevries I took a look at this and came up with a fix here https://github.com/sourcegraph/sourcegraph/pull/35884
