### ISSUE TITLE
Review render.com cleanup action

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#35770]
## Problem statement

Some render.com services are not cleaned up as expected. 
Check out [the billing dashboard](https://dashboard.render.com/billing) in the render.com account to inspect stale web services.

## Success criteria

render.com services for stale PRs are deleted after 5d as was specified in [this PR](https://github.com/sourcegraph/sourcegraph/pull/33859).

## Time estimate

- Pull requests with ~450 lines changed should take **4 hours** at maximum. Ping the reviewer in the spec pull request if time-consuming changes are required.
- Split the work into multiple pull requests if the total diff is bigger than 450 lines of code.

**Comment by gitstart-sourcegraph** [comment]
@valerybugakov after merged the PR, I think it's good now. On render.com dashboard, you can see the last services on table have last deployed 5 days ago text. Or to be sure, we can try to decrease the time from 5 days to 4 days to see what happens.

**Comment by valerybugakov** [comment]
It looks good now. Thank you!
