### ISSUE TITLE
maxReposToSearch set to 50 on dogfood

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#3578]
On dogfood I tried to do searches 30 min ago and was told that there were too many repos to search. This didn't used to be a problem. At https://sourcegraph.sgdev.org/site-admin/configuration I noticed that maxReposToSearch was set to 50 explicitly (and I just removed it, so global searches work now). I am pretty sure it wasn't set to 50 before, because I was able to do global (without repo: filter) searches on dogfood yesterday.

Did something related to https://github.com/sourcegraph/sourcegraph/pull/3262 cause this?

**Comment by ijt** [comment]
I'm not getting this error. `https://sourcegraph.sgdev.org/search?q=foo`. Can you post a link to a search that reproduces the issue?

**Comment by sqs** [comment]
@ijt You aren't getting it because I removed the `maxReposToSearch` set to 50 in the dogfood site config yesterday. If you add it back, you will get the error. The question is why it was added (if it was added) or else why suddenly it became an issue.

**Comment by ijt** [comment]
I don't see anything in #3262 that would cause this. It seems more likely that someone made the change manually.
