### ISSUE TITLE
"Must be authenticated as user with id: X" when trying to generate a token for a user

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#35797]
- **Sourcegraph version:** 3.38.1

When trying to generate an access token as a site admin on behalf of a user, you receive an error.   It seems like, this button should be removed or made to work.

#### Steps to reproduce:

1. Login to Sourcegraph with a site admin account
2. Go to Users > (select user) > Account tokens
3. Click '+ Generate new token'
4. Add a description
5. Click '+ Generate token'

#### Expected behavior:

Token is generated for the user.

#### Actual behavior:

You receive an error:
```
Must be authenticated as user with id X
```
![image](https://user-images.githubusercontent.com/23640224/169549852-887eabb5-cc49-449d-8812-633357c4ef55.png)

**Comment by mike-r-mclaughlin** [comment]
Noticed by [customer 6716](https://github.com/sourcegraph/accounts/issues/6716) in [this slack thread](https://sourcegraph.slack.com/archives/C01Q57DU4TX/p1653055962039429)

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam-and-admin-experience - the "team/iam-admin-experience" label was applied to this issue.

**Comment by RafLeszczynski** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IAM-and-Admin-Experience-627aebcc9f8b7c00128a8ab6/issues/sourcegraph/sourcegraph/35797?planning-poker) with ZenHub @kopancek @miveronese @pjlast @unknwon

**Comment by RafLeszczynski** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IAM-and-Admin-Experience-627aebcc9f8b7c00128a8ab6/issues/sourcegraph/sourcegraph/35797?planning-poker) with ZenHub @pietrorosa77

**Comment by miveronese** [comment]
I was able to reproduced this issue.
There's [a security note here, in our graphql backend,](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/access_tokens.go?L43) informing that site admin should not be allowed to create tokens for other users, which makes sense, imo.

So, I will go ahead and remove/hide "Generate Access Token" button from this page.
But will preserve the other components and current behavior  the site admin will still be able to see  the name of a token (not the token itself) created by a user, its scopes and also will be able to delete it. (see image attached)



![Image](https://user-images.githubusercontent.com/1552863/173369745-bcaff539-7afa-4ffd-a1a2-d1f200b091e7.png)

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.
