### ISSUE TITLE
linksForRepository failed to RepoLookup

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#3581]
https://app.hubspot.com/contacts/2762526/company/561806411 is reporting lots of these log messages:

```
23:12:22           frontend | t=2019-04-24T23:12:22+0000 lvl=warn msg="linksForRepository failed to RepoLookup" repo=redacted/redacted error="Post http://127.0.0.1:3182/repo-lookup: dial tcp 127.0.0.1:3182: connect: connection refused"
```

https://sourcegraph.slack.com/archives/GDS3PJ8GK/p1556147590006800?thread_ts=1556144204.001000&cid=GDS3PJ8GK

**Comment by slimsag** [comment]
These errors occur when repo-updater is not responding correctly, e.g. due to rate limiting. They are a symptom but not a cause. The real issue here is https://github.com/sourcegraph/sourcegraph/issues/3582

**Comment by slimsag** [comment]
Closing in favor of https://github.com/sourcegraph/sourcegraph/issues/3589
