### ISSUE TITLE
insights: migration that converts just in time insights into backfilled insights that run over some repos

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#35817]
Create a migration that will convert all just in time insights into insights that run over only the specified repos and will then be picked up by the backfilling processor.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by Joelkw** [comment]
Recommend testing this migration UX intentionally – we have a script to snapshot on every x internval.

**Comment by chwarwick** [comment]
New migration strategy is to work the migration into the historical enqueuing worker to avoid the need for an out of band migration.  It should do the following:

Check the deprecate JIT insights feature flag.  
If it is disabled - do no new logic

if it is enabled 
- Query JIT series that are not lang-stats
- For each series
    - check backfill attempts (greater than 10 means leave as is)
    - Increment backfill attempts
    - Run scoped Backfiller
    - Update series  just_in_time = false, next_snapshot = tomorrow, next_recording = 1 interval from now
