### ISSUE TITLE
insights: webapp series sorting for all search insights

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#35816]
The first implementation sorting of series only worked for capture group insights.  Add series sorting support for the remaining types search insights.

depends on https://github.com/sourcegraph/sourcegraph/issues/35711

**Comment by chwarwick** [comment]
@unclejustin a heads up that this exists if you have an estimate.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
