### ISSUE TITLE
Improve `sg migration`/`migrator` `drift` recommendations

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#35827]
Currently the drift command gives you only the diff of what's wrong. It would also be useful to either suggest hints on how to construct/reconstruct the items that are different (with listed caveats). These are sometimes simple:

- a missing index can just run the associated definition (with a caveat that maybe we tried to create it concurrently initially, or that duplicate values may exist if the index was unique and was missing for a period of time)
- a missing view can be recreated just by running the associated definition with newlines replaced from the json output

There are also more complex issues:

- we store column definitions but would have to reconstruct the SQL text to recommend something runnable to the user
- ordering of object creation matters if there are dependencies, so we can't resolve things in a correct order automatically
- modify type is limited and _additional_ values will require a change on all views and tables that depend on that type; not something we'd want to perform non-manually as there's a lot of minutiae on this transform

One interesting blanket solution would be to:

- ensure that each commit has an up-to-date "squashed" version of migrations for each schema (we can add this to schemadoc generation so it doesn't affect developers)
- when we see a diff, we give a sourcegraph.com search link for that particular file/revision to guide the user to an automated source of truth to help them self-serve schema restorations

**Comment by bobheadxi** [comment]
> when we see a diff, we give a sourcegraph.com search link for that particular file/revision to guide the user to an automated source of truth to help them self-serve schema restorations

This seems super neat 😁

**Comment by DaedalusG** [comment]
It'd be cool if the `-version` flag was consistent between `upgrade` and `drift` I believe currently `drift` requires the `v` prefix while `upgrade` does not

**Comment by DaedalusG** [comment]
Also making a note here about the flow of the upgrade command -- if schema drift is detected the `upgrade` command will ask you to run `drift` and apply the suggested changes however it may detect changes that aren't a problem like white space changes etc

When this is the case you can run `-skip-drift-check` to disregard the irrelevant "drift" but we could definitely improve on that -- more context in this [internal issue](https://github.com/sourcegraph/customer/issues/1620)

**Comment by efritz** [comment]
See [this customer issue](https://github.com/sourcegraph/customer/issues/1891).
