### ISSUE TITLE
Repos migration triggers abuse detection rate limit on GitHub Enterprise

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#3582]
Reported by https://app.hubspot.com/contacts/2762526/company/561806411 after upgrading to 3.3.1

https://sourcegraph.slack.com/archives/GDS3PJ8GK/p1556145913003900?thread_ts=1556144204.001000&cid=GDS3PJ8GK

```
22:15:40       repo-updater | t=2019-04-24T22:15:40+0000 lvl=eror msg=store.done error="migrate.repos-enabled-state-deprecation.sources.list-repos: 1 error occurred:\n\t* Error getting GitHub repository: nameWithOwner=pascal-carole/datachef: request to http://127.0.0.1:3180/repos/pascal-carole/datachef returned status 403: You have triggered an abuse detection mechanism. Please wait a few minutes before you try again.\n\n"
22:15:40       repo-updater | t=2019-04-24T22:15:40+0000 lvl=eror msg=migrate error="migrate.repos-enabled-state-deprecation.sources.list-repos: 1 error occurred:\n\t* Error getting GitHub repository: nameWithOwner=pascal-carole/datachef: request to http://127.0.0.1:3180/repos/pascal-carole/datachef returned status 403: You have triggered an abuse detection mechanism. Please wait a few minutes before you try again.\n\n" waiting=5s
root@i-0b5d6613c1b911c64:/home/byron_grogan#
2:14:17       repo-updater | t=2019-04-24T22:14:17+0000 lvl=eror msg=migrate error="migrate.repos-enabled-state-deprecation.sources.list-repos: 1 error occurred:\n\t* Error getting GitHub repository: nameWithOwner=philip-snowberger/puppet_control: request to http://127.0.0.1:3180/repos/philip-snowberger/puppet_control returned status 403: You have triggered an abuse detection mechanism. Please wait a few minutes before you try again.\n\n" waiting=5s
n.sources.list-repos: 1 error occurred:\n\t* Error getting GitHub repository: nameWithOwner=philip-snowberger/puppet_control: request to http://127.0.0.1:3180/repos/philip-snowberger/puppet_control returned status 403: You have triggered an abuse detection mechanism. Please wait a few minutes before you try again.\n\n" waiting=5s
22:15:28       repo-updater | t=2019-04-24T22:15:28+0000 lvl=eror msg=store.done error="migrate.repos-enabled-state-deprecation.sources.list-repos: 1 error occurred:\n\t* Error getting GitHub repository: nameWithOwner=pascal-carole/datachef: request to http://127.0.0.1:3180/repos/pascal-carole/datachef returned status 403: You have triggered an abuse detection mechanism. Please wait a few minutes before you try again.\n\n"
```

Customer's GitHub Enterprise config looks like this:
```json
{
  "gitURLType": "ssh",
  "repositoryPathPattern": "{nameWithOwner}",
  "token": "<SNIPPED>",
  "url": "https://<SNIPPED>",
  "repositoryQuery": [
    "org:company created:<2016-01-01",
    "org:company created:2016-01-01..2017-12-31",
    "org:company created:2018-01-01..2018-12-31",
    "org:company created:>2019-01-01",
    "org:foobarbaz",
    "org:third-party"
  ]
}
```

Does the migration honor all rate limits?

I wonder if this line of code might be the issue:
https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/repo-updater/repos/github.go#L420:2

We are concurrently querying repository queries which might trigger abuse detection mechanisms, even if we are staying under the rate limit. Perhaps we should do this serially.

**Comment by nicksnyder** [comment]
Yeah, we need to not do concurrent requests and we should respect retry-after header https://developer.github.com/v3/guides/best-practices-for-integrators/#dealing-with-abuse-rate-limits

**Comment by tsenart** [comment]
@nicksnyder: This hasn't changed, however, so I suspect it was exacerbated by what #3598 fixes. Another question this raises is what `github-proxy` is doing: Isn't it supposed to serialise requests?

**Comment by nicksnyder** [comment]
I forgot about github-proxy. Whether or not it attempts to enforce this, our system is clearly failing to enforce this.

**Comment by slimsag** [comment]
Awesome that we improved the respect of rate limits here, but worth noting the real issue for the customer here I believe was https://github.com/sourcegraph/sourcegraph/issues/3590

**Comment by nicksnyder** [comment]
For https://app.hubspot.com/contacts/2762526/company/561806411 I think this was the real issue, given that their instance is now fine after they removed the deleted repos.

#3590 is only a problem if the rate limit is being unnecessarily exhausted (which is this issue), or if it not possible to list all repositories within the rate limit enforcement window (is this the situation that https://app.hubspot.com/contacts/2762526/company/407948923 is in?)

**Comment by slimsag** [comment]
No, that is not the situation https://app.hubspot.com/contacts/2762526/company/407948923 is in.

I believe it is only by luck that https://app.hubspot.com/contacts/2762526/company/561806411 got out of #3590. If you look at the timeline (although we do not have concrete times), it appears their instance was blocked and repo-updater was not starting for a while. I suspect this was happening for multiple hours until it was reported, and it was only by luck that their rate limit reset and the migration was able to complete and get repo-updater out of its broken state.
