### ISSUE TITLE
issue tracker:: bitbucket repos using ssh not supported

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#35834]
This is to track https://github.com/sourcegraph/customer/issues/961 since the original issue cannot be added to the integrations team project board

Summary: a user reported that bitbucket repos cloned using ssh links are not supported by vsce, resulting in error `git remote URL "remote url" not supported`

Check the original issue for the latest update

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by abeatrix** [comment]
Located the issue where the package the editor endpoint relies on does not support BitBucket Cloud currently. Have referred support to reach out to the team that is responsible for the fix / file feature request. Details can be found in original issue
