### ISSUE TITLE
python dependency search: support other package formats

### ISSUE THREAD

**Issue by stefanhengl** [sourcegraph/sourcegraph#35850]
We already support *.tar.gz and *.whl but historically Python supports other format as well https://docs.python.org/3/distutils/sourcedist.html.

**Comment by malomarrec** [comment]
Hey @stefanhengl, this issue didn't have a team label. Given you created it, I assigned you and added your team label. Feel free to unassign yourself. If this is not the right label, can you make sure to add the right one?

**Comment by keegancsmith** [comment]
cc @mrnugget

**Comment by stefanhengl** [comment]
We have stopped development of this.
