### ISSUE TITLE
JetBrains: Figure out how to tag releases

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#35861]
@vdavid's Slack message to #dev-chat:

---

I’m wondering about the new release process for our updated JetBrains plugin.
**Context:** The plugin used to live in its dedicated repo, and the [release process](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/client/jetbrains/README.md?L76) included creating a new release [here](https://github.com/sourcegraph/sourcegraph-jetbrains/releases/) and tagging the released commit with the version number. This process was helpful because it **preserved a pointer to the repo state for each version**. I’d love to keep this feature.
**Problem:** The plugin code is now merged to the monorepo. We already use the [releases page](https://github.com/sourcegraph/sourcegraph/releases/) for our main Sourcegraph product releases.
**Examples of solutions** that don’t seem to preserve a pointer to the repo state:
- Marek [mentions](https://youtu.be/WR5yOdzJWdo?t=428) the sg repo as a release-only repo in a recent video. However, it only contains the release binaries, and I’m not sure how I could know exactly which repo version those releases were generated from.
- For the VS Code extension, we use a CHANGELOG.md file to track releases. No clear pointers to the matching repo state.
If I find no good solution, I’ll let this go, but it’d be helpful to us to find an elegant way to track multiple product releases in the monorepo.

---

Responses:
- Dax: "Release repo with a changelog? It might require a manual sync but that is what I would use. Essentially just a copy of the specific folder in the monorepo that is updated per-release."
- Joe Chen: "Just a wild idea... release repo includes the commit of monorepo as a submodule :joy: then tag on the change of the submodule."
- Joe Chen: "Other note: have you thought about [GitHub packages](https://github.com/orgs/sourcegraph/packages)? is/could the plugin be an Apache Maven package? Which I think you might be able to publish without a relation to the repository's releases

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by philipp-spiess** [comment]
@vdavid I think there are two separate problems that you're talking about:

1. Preserve a pointer to the repo state. This was done with "tags" and I see no reason why we can't add tags on the monorepo (e.g. we tag a commit as `jetbrains-v1.2.4`). 
2. Publishing the build artifacts as a zip archive somewhere. This is what the Release tab is for. You're right as to the fact that we can not use these going forward. However, the question here is: Do we really need to? Customers are getting the plugin from the JetBrains store AFAIK and this also contains a change log list. If we do need that, we could still publish this as a release to the `sourcegraph-jetbrains` repo while having the main branch contain only a README that explains where to find the source.

**Comment by vdavid** [comment]
Thanks, everyone for helping me think this through.
We'll tag the releases with `jetbrains-{version}` and publish the build artifacts right to the JetBrains store.
This is perfectly fine with me, so I'll just close this issue, the decision will be here for reference.
