### ISSUE TITLE
TODO bot opened duplicate issues

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#3587]
https://github.com/sourcegraph/sourcegraph/issues/3584
https://github.com/sourcegraph/sourcegraph/issues/3585

**Comment by tsenart** [comment]
Hmmm, let's see if this keeps happening. Hopefully it's a transient event.

**Comment by tsenart** [comment]
Thanks for flagging it, but do you think it's worth keeping an issue open for this?

**Comment by nicksnyder** [comment]
Can reopen this if we see it again
