### ISSUE TITLE
Automate steps to drop and re-index precise intel uploads

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#35872]
Over the past months, we have regularly had to

- rename an indexer. For example, s/lsif-typescript/scip-typescript.
- retrigger index jobs. For example, because we released a critical bugfix.

So far, I've mostly pinged @efritz every time this happens and has has written custom scripts to fix the situation. Given that it's a repeating pattern, especially the "retrigger index jobs" use-case, it would be nice if we provided some higher-level tools to deal with this situation.

An ideal use-case for me would be to have a button from the site-admin UI where I can trigger a reindex for all existing uploads matching a query. Very naively, something like this

![CleanShot 2022-05-23 at 16 56 08](https://user-images.githubusercontent.com/1408093/169847983-aa1de2ee-4adf-4a9e-a0f9-daea0be7f2af.png)

However, I'd also be fine with having a solution that only works from the command-line. If this is something we expect customers to run then we may prefer a UI-based solution.

**Comment by eseliger** [comment]
Invalidating all indexes by an indexer below a version threshold would also be a neat feature.

**Comment by efritz** [comment]
This should be covered by #41193.
