### ISSUE TITLE
Code Insights Still In Queue After Deleting From Dashboard

### ISSUE THREAD

**Issue by alexAtSourcegraph** [sourcegraph/sourcegraph#35882]
- **Sourcegraph version:** 3.38.0
- **Platform information:** Kubernetes 

#### Steps to reproduce:

- Create the following insights: 
  * `select:repo file:yarn.lock archived:no fork:no`
  * `try {:[_]} catch (:[e]) {} finally {:[_]} lang:java patternType:structural archived:no fork:no`
- Delete both insights from the dashboard
- Check the primary database to see if the jobs are in any other state rather than `terminated` with the following query
  * `select count(*) from insights_query_runner_jobs where state in ('queued', 'processing', 'errored')`

#### Expected behavior:
After deleting all the insights from the dashboard, running the following query should return a count of 0 and the jobs should be terminated.

`select count(*) from insights_query_runner_jobs where state in ('queued', 'processing', 'errored')`

#### Actual behavior:

After deleting all insights from the dashboard, `searcher` evictions occur every 30 - 60 minutes and there is a queue of `insights_query_runner_jobs` in various states other than `terminated`.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by leonore** [comment]
validated that this is an oversight, created https://github.com/sourcegraph/sourcegraph/issues/36229

I also want to highlight that the `terminated` state isn't triggered by any workflow at the moment in insights, it's a manual override that means insight query jobs will stop running. deleting an insight won’t set the corresponding job to `terminated`
