### ISSUE TITLE
Add experimental feature flag for home panels compute suggestions

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#35890]
A feature flag is needed for the [home panels suggestions project](https://docs.google.com/document/d/1nSIuv5a6kRMAiSHHbZFLkmaFButZupwz_y3IM--NFLw/edit#heading=h.trqab8y0kufp).

- The name of this feature flag could be `homePanelsComputeSuggestions` (if you have a better name feel free to use it :) ) 
- The feature flag needs to be added to https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/schema/settings.schema.json under `experimentalFeatures`
- Once the schema is updated (run `yarn generate` and `go generate ./...`), you can use the feature flag with the hook `useExperimentalFeature`. [See example use.](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/search/home/SearchPage.tsx?L58:11)

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.
