### ISSUE TITLE
Show compute in search results page

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#35906]
[ProductBoard link](https://sourcegraph.productboard.com/roadmap/4223336-search-product-technical-capabilities/features/13135271/detail)

Under the `showComputeComponent`, display the same compute component used in Notebooks in the Search Results page if the query is a compute query.

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by limitedmage** [comment]
@benvenker  I'm reopening this since it's not done. I've put this work on hold and have a draft PR out. If you think we should stop work on this entirely, please close it as "not planned". Thanks! :)

**Comment by benvenker** [comment]
Oh whoops. I'm not sure I meant to do that, sorry!

**Comment by lguychard** [comment]
@limitedmage @benvenker I'm going to close this, because code insight's current work on adding aggregation features to search results effectively make this irrelevant.
