### ISSUE TITLE
Add Gerrit support information to Sourcegraph Docs

### ISSUE THREAD

**Issue by jplahn** [sourcegraph/sourcegraph#35901]
Update the Sourcegraph docs to detail our Gerrit support upon completion of implemention

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.

**Comment by mrnugget** [comment]
Implemented as part of https://github.com/sourcegraph/pr-faqs/issues/41
