### ISSUE TITLE
repo-updater 3.3 auto-migration: can become blocked on rate limit forever

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#3590]
See #3594 for details (ctrl+f on that page for this issue #)

**Comment by tsenart** [comment]
After #3598 is merged, there's nothing about this migration that is different than normal background syncing in regards to code host communication, so I believe this will become a non-issue. Otherwise, if that still happens for another reason we haven't yet foreseen, is there a particular fix for this that you can think of? We need to run this migration.

**Comment by slimsag** [comment]
The context for this is in the linked issue above, i.e. this part:

> As part of migrating disabled repositories to the exclude list, our migration code must list all repositories on the code host.
>
> If the code host API rate limit is already significantly consumed, and there are a lot of repositories to list (100 per page), the ListAll logic will return an error which bubbles up to fail the migration.
>
> When the migration fails, the repo-updater process exits and Kubernetes/Docker restarts the process which starts the migration again and consumes more of the API quota making the problem worse.

Fundamentally the issue here is that when we are hitting the code host API rate limit, the migration fails. When the migration fails, repo-updater exits and restarts, trying the migration again. When it tries the migration again it consumes more rate limit and makes the problem worse by triggering abuse detection in the code host.. this doesn't stop unless you're lucky.

I believe this is what https://app.hubspot.com/contacts/2762526/company/561806411 faced early on in their report of this issue. You can see it from their logs here: https://sourcegraph.slack.com/archives/GDS3PJ8GK/p1556145913003900?thread_ts=1556144204.001000&cid=GDS3PJ8GK

I will send a PR with one possible fix.
