### ISSUE TITLE
sg lint go hangs in CI if the repo is dirty after running go generate

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#35918]
Hanging build: https://buildkite.com/sourcegraph/sourcegraph/builds/149225#dcb576ca-808b-4df0-ba06-4a057c3a9aa9 
Fixed build: https://buildkite.com/sourcegraph/sourcegraph/builds/149245#8b4da59a-f68e-4414-a783-43bb2127b8d1 

Diff: https://github.com/sourcegraph/sourcegraph/commit/a9b15bdc32409bbec9c5522c55d4b1f8b20c299c 

This is what happened to @efritz yesterday as well. 

Edit: narrowed it down to `output.WriteMarkdown`. With just using `.Write` it works.

**Comment by jhchabran** [comment]
@bobheadxi after a quick inspection, I didn't see anything obvious. Could you take a look as you've fixed issues with buffering recently?

**Comment by jhchabran** [comment]
Forgot you're OOO for now, I'll take it :)

**Comment by bobheadxi** [comment]
Thanks for taking a look! That said, would like to not keep the solution implemented in https://github.com/sourcegraph/sourcegraph/pull/36043 since `sg` should be completely not-buildkite-aware (output keeps a reference to Buildkite env but we should avoid using it IMO)

**Comment by bobheadxi** [comment]
I think I've found the issue - the dark background detection seems to hang forever after being added in https://github.com/sourcegraph/sourcegraph/pull/35983

**Comment by bobheadxi** [comment]
Found a safer solution here: https://github.com/sourcegraph/sourcegraph/pull/36193
