### ISSUE TITLE
JetBrains: Search context dropdown is partially hidden

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#35916]
## Problem

It currently hangs, like this:
![image](https://user-images.githubusercontent.com/2552265/169993178-d54d38c8-fc0f-4f20-9759-7f0710431cc8.png)

## Solution

Set its maximum size to the viewport height.
Would be best to also set up a window `resize` event listener and update the max height accordingly.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
