### ISSUE TITLE
JetBrains: SearchBox sometimes doesn’t search

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#35917]
Here is a demo of this happening: https://www.loom.com/share/9fc447f26a6b4c94aa6a0444ab398aff

It's pretty inconsistent, I've found no 100% sure way to reproduce this.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by philipp-spiess** [comment]
I _think_ this be related to #35929: If the editor was loading `test` from a previous search it might have bailed out from the search code even (since lastSearch would be populated with `test`). I'd say we try to reproduce this again after we land #35929

**Comment by philipp-spiess** [comment]
I played around with this today and wasn't able to reproduce. One thing that is a bit awkward still is that we don't show a difference between "loading" and "0 results found" in the UI but that's something we will for sure fix later (in fact, I might as well get started on the result number display right now as we already identified it).

@vdavid Can you also take a moment to try and reproduce this?

**Comment by vdavid** [comment]
Yeah, I can't reproduce it anymore. I think something we did along the way fixed this. :)

Closing the issue.
