### ISSUE TITLE
repo-updater 3.3 auto migration: invalidated external service config fully blocks migration

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#3592]
See #3594 for details (ctrl+f on that page for this issue #)

**Comment by tsenart** [comment]
Working on this now.

**Comment by tsenart** [comment]
I assume that the customers that didn't have the username field set were setting it in the credentials part of the url. Otherwise their installation couldn't be operating normally.

Apart from documenting that admins must now set this field in the upgrade process, we can create a best effort migration that takes the username from the url and puts in the username.

**Comment by slimsag** [comment]
So unfortunately #3601 wouldn't have fixed the issue for https://app.hubspot.com/contacts/2762526/company/407948923 

This configuration was valid before 3.3:

```json
{
    "url": "https://bitbucket.company.com",
    "excludePersonalRepositories": true,
    "gitURLType": "ssh",
    "token": "<TOKEN>",
}
```

This is valid without a `username` field AND without the username in the URL, because cloning is being performed via SSH. Gitserver only required the username when cloning via HTTPS. This obscure detail wasn't noticed in https://github.com/sourcegraph/sourcegraph/pull/3299#issuecomment-481138097 I imagine.

Now, does this matter? I think probably not, actually. This means it only applies to users of Bitbucket Server with SSH cloning turned on, which is relatively obscure for our users (most use HTTPS cloning, the default).

So this wouldn't have solved the issue https://app.hubspot.com/contacts/2762526/company/407948923 ran into, but that's probably OK because:

1. This won't affect any new users
2. This won't affect any old users unless they are using both bitbucket AND ssh cloning.

So it's probably fine to leave this closed.
