### ISSUE TITLE
Feature Variance by Deployment Type for New Registrants

### ISSUE THREAD

**Issue by a-bergevin** [sourcegraph/sourcegraph#35950]

**Comment by a-bergevin** [comment]
Not all features are available in all deployments. For example - Code Insights & Batch changes are not. Here's some context from a slack discussion:

The way I am thinking about it the major cases here are:
🟢 **New visitor, curious about code insights (and product overall) - chooses to demo** (no solution needed)
🟠 **New visitor, curious about code insights (and product overall) - chooses to `Get Started`** (This is what we've been discussing, it's not ideal. Design and I can keep this as a requirement in future tests we may do on the deployment decision page. I won't speculate here on solutions, but we can try to make it clearer before EOQ. This is a high traffic inflection point so I think we want to make sure we don't increase bounce rate, but also that we don't create the frustration Murat was reporting)
🟡 Cloud registered user decides they are curious about insights....how can we make it clear what that feature does or how they can experience it. I feel like https://sourcegraph.com/insights could be more up front (especially for logged in users) at the top of page about how it's not available in their Cloud instance. Right now that's not spelled out, just implied by the focus on demo & local install via k8s/docker-compose. Not sure if it's in scope for your team to make some minor tweaks to this page or if our engineers could help here. But I think clarification here could help.
🟡 Self-hosted on single container decides they are curious about insights....how do we make this clearer? Do they see the same page as the Cloud person on the previous bullet? Maybe it's the same solution
🟢: Enterprise customer decides they are interested -- this is the use case I think you've most addressed. They can create up to 2 instances insights and reach out to support/ce/ae to talk about getting licenses. No PLG here yet.
So there are a few different journeys and a few different severity of problems. Seems like we can make those yellow severity circles a green with pretty low effort. And the orange one will take a bit more time, but my team can move it towards yellow/green as part of our registration work once we have a designer

**Comment by a-bergevin** [comment]
Current decision is it's not worth building a full "try out insights" product flow for either local in stall or cloud. We may revisit that if changes in user behavior indicate it has significant potential for lead gen. 

In the near term it seems better that teams make it clear on dedicated product pages (and in the docs) which deployment types support those features. And possibly add more screenshots, videos, links to resources to dive deeper into the feature (maybe once insights can embed in a notebook we could run it on cloud on a single popular repo and showcase it there with some level of interactivity?)

And the Growth team will work on the user journey around new user registrations on the website & clarifying up front which features are in which deployment type. More discovery and design is needed here. But the goal would be to clarify that certain features like Batch Changes & Code Insights are better demonstrated on a demo or if the user prefers a more self guided process it's a more involved deployment for self-hosted.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @a-bergevin - the "team/growth" label was applied to this issue.

**Comment by a-bergevin** [comment]
Original feedback that lead to this discussion 
<img width="731" alt="image" src="https://user-images.githubusercontent.com/102552520/170066016-b29e70b2-c1d3-4a5a-9318-7126d00c6e52.png">

**Comment by Joelkw** [comment]
@a-bergevin thanks for writing this up! Great tos ave it. 

Real quick – since this is a public issue, can you please remove the screenshot of slack that you posted? We don't post customer names (company names or individual names, part of ["customer information"](https://handbook.sourcegraph.com/company-info-and-process/values/#open-and-transparent)) to Github unless the customer has already made one or both of those public in filing an issue.

**Comment by a-bergevin** [comment]
Thanks @Joelkw for the catch! - Still getting used to this whole company repo being public thing. 🤦🏻‍♀️ I'll get there!

**Comment by malomarrec** [comment]
Looks outdated. Closing. Re-open if you disagree.
