### ISSUE TITLE
vsce: integration-test is failing

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#35955]
Our nightly build has been failing in the past 4 days in our pipeline.

 
![image](https://user-images.githubusercontent.com/68532117/170086331-73c3b5c8-be00-4404-9035-a4522877a920.png)

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
