### ISSUE TITLE
Structural search: stream to and from comby

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#35964]
We recently upgraded comby to the latest version (1.7.1). One of the new features added since the last version is the ability to stream input to comby with the `-tar` flag. 

Currently, we have two codepaths for comby: [indexed](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@57ffdb4f30d17b59ba94e6339fe3eead48567b45/-/blob/cmd/searcher/internal/search/search_structural.go?L293-293) and [unindexed](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@57ffdb4f30d17b59ba94e6339fe3eead48567b45/-/blob/cmd/searcher/internal/search/search_structural.go?L174-174). For both paths, we generate a list of candidate matches and write them to a zip file, then [run comby over that zip file](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@57ffdb4f30d17b59ba94e6339fe3eead48567b45/-/blob/cmd/searcher/internal/search/search_structural.go?L260-260). 

There are a few problems with this batch approach: 
1) We cannot start searching with comby until the entire result set is downloaded and written to disk (zip files can't be streamed)
2) We cannot stream matches out of comby because we might need to retry a batch request with a higher limit, so any previously streamed results might be repeated.
3) We have to request far more candidate results than necessary because we don't know how many of the candidate matches will match, and we don't want to have to retry too many times. 

So, we'd like to implement streaming into and out of comby to fix these issues and make structural search a more pleasant experience.

**Comment by rvantonder** [comment]
> we might need to retry a batch request

> Hey, @sourcegraph/batchers  we have been mentioned. Let's take a look.

lol.

---

> So, we'd like to implement streaming into 

For context, how will this interact with Zoekt? IIRC we can request Zoekt stream content now, right?

**Comment by rvantonder** [comment]
Or is it that we could stream from gitserver (?)

**Comment by eseliger** [comment]
Always happy to help make things batch anything 🖖

**Comment by camdencheek** [comment]
> For context, how will this interact with Zoekt? IIRC we can request Zoekt stream content now, right?

The Zoekt client will already stream matches, but we collect them and write them to disk before passing them to Comby. The big win here will be to stream directly to Comby so we can get rid of the retries resulting from requesting too small a batch from Zoekt. We can just keep streaming until Comby returns enough matches to hit the result limit.

Additionally, for unindexed search, we can stream matched files to comby rather than doing a full search of a repo then passing the matched paths to comby. This is less of a big win because we still pay the latency cost of fetching the full archive from gitserver (if not cached) before we even start a regex search. Streaming from gitserver is a separate (but very valuable) problem to solve.

**Comment by camdencheek** [comment]
One thing I didn't consider until now is that (currently) every structural search will only execute over one repo, which is usually exactly one shard, which I think means we won't actually get a meaningful "stream" within a single search. 

cc @sourcegraph/search-core could you confirm that the Zoekt streaming API will return one event per shard, and won't stream results within a single repo? I'm struggling a bit to navigate all the interfaces and adapters, so want to make sure I'm understanding them correctly.

**Comment by keegancsmith** [comment]
one event per shard. However a repo can be more than one shard. And we have compound shards, so we can have multiple repos in a single shard.

**Comment by camdencheek** [comment]
So, my concern here is that we'd need to read an entire shard's worth of matches and file contents into memory in `searcher` since there is no streaming within a shard. For normal search, this doesn't matter much because we're not returning the file contents. I guess the max event size will be roughly 4GB (max shard size), which might be okay, but that's still larger than I'm comfortable with. 

Limits only sorta help here since file size and the spread of matches across files will _dramatically_ impact how big the payload is. I think this is part of what's leading to the current unpredictability of structural search performance for different patterns. 

@keegancsmith 1) does this seem concerning to you, and if it does, 2) how difficult would it be to chunk large events from the streaming side of things? It looks to me like it would be non-trivial since the zoekt server doesn't seem to know anything about streaming.

**Comment by stefanhengl** [comment]
For compound shards we stream by repo. Since repos in compound shards are by definition small you can just assume that an event contains only results from 1 shard. The max-shard size is then around 300 Mib. In other words, you can ignore compound shards as a Zoekt client.

**Comment by keegancsmith** [comment]
shard size is about 300mb, but the max content size cutoff is 100mb. These sound like nice sized chunks. One issue you may have though is all replicas sending back 100mb events. You will want to ensure there is decent back pressure so we don't oom.

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.
