### ISSUE TITLE
Comments interleaved in a multi-line command are not valid in bash

### ISSUE THREAD

**Issue by jasonhawkharris** [sourcegraph/sourcegraph#35968]
- **Sourcegraph version:** 3.40
- **Platform information:**  Pure Docker deployment

#### Steps to reproduce:

1. Attempt to deploy/upgrade 3.40 in a pure docker deployment.
2. Note broken deployment.

#### Expected behavior:
Expect `cadvisor` to deploy without issue.

#### Actual behavior:
New comments in 3.40 seen in [this diff](https://github.com/sourcegraph/deploy-sourcegraph-docker/commit/f2acef87ab46d2b707a3935629a5340086205a8b) are not valid in bash and therefore, break the deployment.

Fix: Deleting the comments fixed the issue.

If would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are not [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

**Comment by sourcegraph-bot-2** [comment]
Heads up @caugustus-sourcegraph @kevinwojo @michaellzc - the "team/delivery" label was applied to this issue.
