### ISSUE TITLE
Resource Estimator: Generate a metric inventory and identify DRIs for each service.

### ISSUE THREAD

**Issue by kevinwojo** [sourcegraph/sourcegraph#35961]
Using data from https://github.com/sourcegraph/sourcegraph/issues/30765, generate a metric inventory and identify DRIs for each service. 

## Metric Inventory
* Specifically understand a service's profile with respect to memory, cpu, and disk in response to # of users, # of repos, and size of repos.
 * If there are behaviors that affect a service, to identify those. Identify the critical bounds of a service (CPU-bound, memory-bound, disk I/O, network throughput).

This ticket relates to: https://github.com/sourcegraph/sourcegraph/issues/30768

**Comment by sourcegraph-bot-2** [comment]
Heads up @caugustus-sourcegraph @kevinwojo @michaellzc - the "team/delivery" label was applied to this issue.

**Comment by briemcnally** [comment]
Complete please see metric inventory in [mini-SDD here ](https://docs.google.com/document/d/1dQPkU4ajp6WlgIvfSo2iYk4xgzhT1BrZ65mSGklDIuw/edit#)
