### ISSUE TITLE
3.40 patch to fix broken admin UI for managing code hosts

### ISSUE THREAD

**Issue by courier-new** [sourcegraph/sourcegraph#35970]
@sourcegraph/release-guild I am requesting the following commits be included in a patch release. They are already merged into `main`:

- 5d8cc87b9f79370428782ecdcf1b34ea8d2615e0

---

The intent of the questions below is to ensure we keep Sourcegraph high quality and [only create patch releases based on a strict criteria.](https://handbook.sourcegraph.com/engineering/releases#patch-releases) If you can answer yes to many or most of these questions, we will be happy to create the patch release.

I have read [when and why we perform patch releases](https://handbook.sourcegraph.com/engineering/releases#patch-releases) and answer the questions as follows:

> Are users/customers actively asking us for these changes and cannot wait until the next full release?

No, the issue was [surfaced internally](https://sourcegraph.slack.com/archives/C03CSAER9LK/p1653311222557759) before any reports from customers.

> Are the changes extremely minimal, well-tested, and low risk such that not testing as we do in a full release is OK?

Yes. The change only fixes a regression at the GraphQL layer for an `ExternalService` that doesn't have webhooks support. The case is covered with a fixed unit test as well.

> Is there some functionality completely broken that warrants redacting the prior release of Sourcegraph and advising users wait for the patch release?

No. Site admins are the only individuals who would be affected by this regression, it is only in the UI, and it only affects the configuration of code hosts that lack webhooks support (e.g. Gerrit, Perforce, Azure DevOps, AWS Codecommit, etc.).

> This will interrupt our regular planned work and release cycle, taking one full working day of our time, and will take up all of our site admin's valuable time by asking them to upgrade or producing noise for them if they don't need to upgrade.
>
> Do you believe the changes are important enough to warrant this?

Yes. It's a regression that breaks the UI. A site admin can choose not to upgrade if they are only using unaffected code hosts with their Sourcegraph instance.

> Patch releases are a signal we can do something better to improve the quality of Sourcegraph. Have you already scheduled a call (or created a google doc) to perform a [retrospective](https://about.sourcegraph.com/retrospectives) and identify ways we can improve?

Our team has discussed this internally over a sync already.

---

**For the [Release Captain]** - after reviewing this request:

- [x] **Comment on this issue** with a decision regarding the request.
- [x] If you are a first-time [Release Captain], please review the high-level overview of the [patch release process].
- [ ] If approved, **add it to a patch release**:
  - If there is [already an upcoming patch release](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+), add the listed commits alongside a link to this issue
  - If there is no upcoming patch release, create a new one:
    - [x] Update [`dev/release/release-config.jsonc`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/release/release-config.jsonc) and open a PR to `main` to update it
      - [x] Change `upcomingRelease` to the current patch release
      - [x] Change `previousRelease` to the previous patch release version
      - [x] Change `releaseDate` to the current date (time is optional) along with `oneWorkingDayAfterRelease` and `oneWorkingDayBeforeRelease`
      - [x] Change `captainSlackUsername` and `captainGitHubUsername` accordingly
    - [x] `yarn release tracking:issues` 
    - [ ] Add the listed commits alongside a link to this issue to the generated [release tracking issue](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+)
- [ ] **Comment and close this issue once the relevant commit(s) have been cherry-picked into the release branch**.

[release captain]: https://handbook.sourcegraph.com/engineering/releases#release-captain
[patch release process]: https://handbook.sourcegraph.com/departments/product-engineering/engineering/process/releases#patch-release-process

**Comment by unknwon** [comment]
https://github.com/sourcegraph/sourcegraph/commit/5d8cc87b9f79370428782ecdcf1b34ea8d2615e0 has been cherry-picked to the 3.40 branch, but looks like missing a CHANGELOG entry, could you add that as well?

**Comment by unknwon** [comment]
CHANGELOG entry added in https://github.com/sourcegraph/sourcegraph/pull/36060.
