### ISSUE TITLE
"Remove code host" warning and "Sync selected repositories" alignment 

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#35986]
- **Sourcegraph version:** 
Sourcegraph.com
- **Platform information:** 
Chrome 101.0.4951.54

Two small issues that I noticed walking through the Repo Management user journeys. 

**Issue 1** 
<img width="1211" alt="Screen Shot 2022-05-24 at 3 57 45 PM" src="https://user-images.githubusercontent.com/43555476/170146486-387bb16b-a0fe-49a0-9f76-db16fbbfbf1c.png">

I was a little alarmed by this warning and pinged Jordan to make sure that I wasn't going to break anything by removing a connection. I think "members of organization" makes it sound like by removing the connection from my **own** account, I'll remove it from the account of everyone else in the organization as well. 

To reproduce: Go to "Code host connections" under user settings and click "Remove".

**Issue 2**
<img width="874" alt="Screen Shot 2022-05-24 at 5 04 40 PM" src="https://user-images.githubusercontent.com/43555476/170146781-3d65491f-3f83-4d33-9304-5af45c09b149.png">

The checkboxes look like they're not lined up correctly with the repo name, right?

To reproduce: Go to "Your repositories" --> "Manage repositories" and select "Sync selected repositories"

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.

**Comment by eseliger** [comment]
Should be fixed.
