### ISSUE TITLE
search: ranking results from searcher with zoekt

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#35993]
Currently searcher's results are not ranked. This can race with zoekt and lead to surprising results on Sourcegraph.com where not everthing is indexed. Searcher can beat out zoekt thanks to streaming and a cached repository. For example searches I was trying both where taking under 8ms to run leading to this race.

The solution here is likely having something which can take into account both zoekt and searcher when doing ranking. This is a bit of work so in the meantime we should first implement https://github.com/sourcegraph/sourcegraph/issues/35994 as a workaround.

Original report: https://sourcegraph.slack.com/archives/C023ELQLV7F/p1653395689610599

> Searching for `r:sourcegraph/sourcegraph config`, the first few results are from package repos (eg. `go/github.com/sourcegraph/sourcegraph/enterprise/lib`), then all subsequent results are from the GitLab mirror of sourcegraph/sourcegraph. No result from `github.com/sourcegraph/sourcegraph` is displayed. This feels off.

> I tried something more unique which should work, but sometimes when I do it it isn't ranked properly. [`repo:sourcegraph/sourcegraph fast, global, semantic code search & cross-reference engine`](https://sourcegraph.com/search?q=context:global+repo:sourcegraph/sourcegraph+fast%2C+global%2C+semantic+code+search+%26+cross-reference+engine)

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/search-core - the "team/search-core" label was applied to this issue.

**Comment by jtibshirani** [comment]
I'm closing this as we already merged #35994 and we have other ideas that would improve searcher ranking:
* https://github.com/sourcegraph/sourcegraph/issues/60442
* Add a "reranking" layer on top of the retrievers (Zoekt, searcher) and move most interesting ranking logic there
