### ISSUE TITLE
search: run zoekt before searcher on Sourcegraph.com

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#35994]
As a temporary workaround to https://github.com/sourcegraph/sourcegraph/issues/35993 we can fix the user experience by running zoekt before running searcher. This isn't ideal, since it is possible for zoekt to run a slow query. However, for the majority of cases this will result in better ranked results which is a much better user experience. I recommend gating this logic to only run on sourcegraph.com since customer instances don't suffer from the same problem (all repos are indexed for them).

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/search-core - the "team/search-core" label was applied to this issue.

**Comment by keegancsmith** [comment]
Added this to our support project since we should do the workaround asap.

**Comment by keegancsmith** [comment]
@rvantonder is creating an alternative PR in https://github.com/sourcegraph/sourcegraph/pull/36197 so I am gonna assign this to him. @rvantonder if you don't have time to pick this up soon, please just ping me. Maybe I'll just land my bad approach so we get better results on sourcegraph.com sooner.
