### ISSUE TITLE
Browsing private repositories works in chrome but not in firefox

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#360]
A user reported on [reddit](https://www.reddit.com/r/programming/comments/9kmr4p/sourcegraph_is_now_open_source/e7gp8hu/?context=3&st=JN21XASR&sh=44bfd46d) that they were having trouble using our Chrome extension via server. However, when browsing via Firefox instead it worked. I assume this is a problem in the extension code rather than the server given that condition.

> Trying out Sourcegraph's server currently using docker and trying to make it play nice with my source graph chrome extension. Seems like for public repos the extension works fine, i.e, i can see references, goto, in the github repo, but for private github repos not so much. Is it a bug or thats a premium feature?
> Edit: So looks like this is related to the chrome extension only. Tried with firefox and it works. so just the chrome extension needs fixing.

I have linked back into this issue from reddit to helpfully get more information.

**Comment by ijsnow** [comment]
I was able to reproduce locally and the problem was that `"corsOrigin": "https://github.com"` was not set. I'm not sure how it can work in Firefox with this though.

**Comment by ijsnow** [comment]
[The user solved this on his own.](https://www.reddit.com/r/programming/comments/9kmr4p/sourcegraph_is_now_open_source/e7kia8d/) I'll open an issue on the browser extension repo for making this more obvious.
