### ISSUE TITLE
JetBrains: Write guest post on JetBrains’ Platform Blog

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#36000]
Yann Cébron wrote:

> For plugins, we offer the possibility of contributing a "guest post" on our Platform Blog as described here https://blog.jetbrains.com/platform/2021/12/tips-for-writing-a-guest-post/.
> This is basically a mixture of "look behind the scenes" of an actual plugin and its development, as well as promoting the plugin/features itself.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
