### ISSUE TITLE
Overhaul usage of sourcegraph URL in browser extension

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#3600]
At the moment, multiple ways are used to access the Sourcegraph URL:
- `window.SOURCEGRAPH_URL`
- `localStorage.getItem('SOURCEGRAPH_URL')`
- `storage.getSync(({ sourcegraphURL }) => ...)`
- `import { sourcegraphURL } from ...`

We need to define and use a single source of truth and also react to its changes everywhere (e.g. with an Observable)

**Comment by lguychard** [comment]
Do you feel like https://github.com/sourcegraph/sourcegraph/pull/3849 satisfyingly resolves this?

**Comment by felixfbecker** [comment]
Yup
