### ISSUE TITLE
Code Insights: Add links/actions to the standalone insight page

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#36006]
Based on "the share by link" [designs](https://www.figma.com/file/Y4grZjTxnXHEQSoeB14vU1/Share-a-link-to-an-individual-code-insight-RFC-654?node-id=1228%3A16270) 

> How to get to the standalone insight page:
> - copy shareable link from context menu
> - click on the insight title on the card
> - ~~click on the ‘save and copy link’ button in the creation ui~~

We should enhance our UI to add ~~all three~~ two points/actions. The first one `copy shareable link from context menu` is already implemented. In this issue we should update creation UI and the dashboard page insight card.

**Comment by AlicjaSuska** [comment]
@vovakulikov Thank you for creating this issue. There was a decision made to cut out 'save and copy' button (checkbox) for now ([comment](https://www.figma.com/file/Y4grZjTxnXHEQSoeB14vU1?node-id=1228:25708#182157785))

**Comment by vovakulikov** [comment]
@Joelkw Yes
