### ISSUE TITLE
Move MI subdomains to deploy-sourcegraph-managed (dsm) repo

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#36035]
DNS subdomains creation should be moved to DSM repo to faciliate further automation of Sourcegraph managed instances

## Deliverables

- [ ] All MI subdomains exist in dsm repo
- [ ] Tombstone present in infra repo warning others to not create subdomains for MIs there

**Comment by michaellzc** [comment]
I think this should only be done to the new module for the time being https://github.com/sourcegraph/deploy-sourcegraph-managed/tree/main/modules/terraform-managed-instance-new
