### ISSUE TITLE
Sourcegraph icon on top-right of PR files is offset vertically by a few pixels

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [sourcegraph/sourcegraph#3603]
- **Sourcegraph version:** "Github.com"
- **Platform information:** Chrome 73 on Mac OS

#### Steps to reproduce:

1. Install the Chrome browser extension
2. Visit https://github.com/sourcegraph/sourcegraph/pull/3602/files

#### Expected behavior:

Beautiful consistent vertical centering

#### Actual behavior:

![image](https://user-images.githubusercontent.com/3335181/56738238-32d38d80-673a-11e9-8fab-46919b7aa15b.png)

**Comment by sqs** [comment]
Possibly caused by the same GitHub DOM change in #3577

**Comment by felixfbecker** [comment]
Fixed
