### ISSUE TITLE
Move GCP MI projects out of infrastructure repo

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#36034]
To fully automate MI creation, we need to move GCP projects out of our infra repo and into deploy-sourcegraph-managed.

This is only for the actual GCP projects in `gcp/org/` 

https://github.com/sourcegraph/infrastructure/tree/main/gcp/projects

**Comment by michaellzc** [comment]
If we move MI GCP Project state oursief infra repo, we have another chicken and egg problem

The GCS bucket we provision for each MI lives inside the MI GCP project https://github.com/sourcegraph/deploy-sourcegraph-managed/blob/main/template-new/gcp-tfstate/gcp-tfstate.tf

**Comment by sanderginn** [comment]
I think @michaellzc is right, and I can't immediately think of anything that improves the current situation in a meaningful way without leveraging a third party tool that manages state.

Honestly the biggest thing is getting the project and service API setup to a point where it is done in seconds rather than minutes for now, I think.

**Comment by michaellzc** [comment]
@sanderginn We should prioritize this https://github.com/sourcegraph/sourcegraph/issues/36036 over the rest

**Comment by sanderginn** [comment]
@michaellzc if you have time to pick it up go ahead, otherwise I can do it tomorrow

**Comment by kalanchan** [comment]
I think this becomes a org admin level discussion if we decide to "decentralize" project creation and delegate it to each team. If we scale this to huge proportions, I can see security having issues with projects scattered everywhere across repos.

**Comment by daxmc99** [comment]
> I think this becomes a org admin level discussion if we decide to "decentralize" project creation and delegate it to each team. If we scale this to huge proportions, I can see security having issues with projects scattered everywhere across repos.

I consider this the exception rather than the rule. Projects should nearly always be created in `infrastructure`
We are making an exception here to allow additional automation for managed instances. Creating new projects via terraform should be fairly infrequent

**Comment by kalanchan** [comment]
Yeah having it as the exception makes sense to me.
