### ISSUE TITLE
Remove unused StorageItems from browser extensions

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#3604]
There are a lot of StorageItems that are not _written_ to anywhere in the code base (they are _read_ though).

https://github.com/sourcegraph/sourcegraph/blob/68b73cac8a1fd9a9f2ad221ee12d53bd53b84d15/client/browser/src/browser/types.ts#L55-L79

@KattMingMing @sqs can we remove them or are they set through GCloud Admin and used by customers? If they are, which of them, and who did we document them to?

**Comment by sqs** [comment]
Any keys that are not written to in the browser extension code can be removed.

But please wait for @KattMingMing to answer this for https://app.hubspot.com/contacts/2762526/company/734382054 to confirm.

**Comment by felixfbecker** [comment]
Could someone explain to me how managed storage is configured? Can the admin just edit a JSON file, i.e. set arbitrary keys? Or is it only keys we declared somewhere?

**Comment by felixfbecker** [comment]
I found https://sourcegraph.com/github.com/sourcegraph/sourcegraph@browser-api/-/blob/client/browser/src/extension/schema.json#L7:25 which is referenced in the manifest as the managed schema. I assume those are the keys that are supported and I can remove all others.

**Comment by felixfbecker** [comment]
So `phabricatorMappings` is in that schema but I don't see that value ever being read from managed storage, only sync storage. But to sync storage it is never written to. Am I correct to assume it can be removed from the managed storage manifest?

Really need some info on which config customers actively use - who can I ask? Which customers use GCloud at all?

**Comment by felixfbecker** [comment]
Related https://github.com/sourcegraph/sourcegraph/issues/2471
