### ISSUE TITLE
Patch request for GitLab expiring tokens

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#36040]
@sourcegraph/release-guild I am requesting the following commits be included in a patch release. They are already merged into `main`:

- https://github.com/sourcegraph/sourcegraph/commit/8b6c870971edbeee9934e45f33a69b72a66b7907
- https://github.com/sourcegraph/sourcegraph/commit/bf23a6315c476ecf48c6b6a0079ddebeda266ebf

---

The intent of the questions below is to ensure we keep Sourcegraph high quality and [only create patch releases based on a strict criteria.](https://handbook.sourcegraph.com/engineering/releases#patch-releases) If you can answer yes to many or most of these questions, we will be happy to create the patch release.

I have read [when and why we perform patch releases](https://handbook.sourcegraph.com/engineering/releases#patch-releases) and answer the questions as follows:

> Are users/customers actively asking us for these changes and cannot wait until the next full release?

Yes, for example https://github.com/sourcegraph/customer/issues/968

This is an ongoing incident: https://app.incident.io/incidents/109

> Are the changes extremely minimal, well-tested, and low risk such that not testing as we do in a full release is OK?

Yes, the changes are scoped only to GitLab and we have added a unit tests and tested manually.

> Is there some functionality completely broken that warrants redacting the prior release of Sourcegraph and advising users wait for the patch release?

Yes, any customer who has upgrade their GitLab instance to version 15.0 or uses gitlab.com will be affected since their OAuth tokens will expire after two hours and old token have been revoked.

> This will interrupt our regular planned work and release cycle, taking one full working day of our time, and will take up all of our site admin's valuable time by asking them to upgrade or producing noise for them if they don't need to upgrade.
>
> Do you believe the changes are important enough to warrant this?

Yes, this is an existing incident:
https://app.incident.io/incidents/109

> Patch releases are a signal we can do something better to improve the quality of Sourcegraph. Have you already scheduled a call (or created a google doc) to perform a [retrospective](https://about.sourcegraph.com/retrospectives) and identify ways we can improve?

Yes, we will do this as part of the incident retro.

---

**For the [Release Captain]** - after reviewing this request:

- [x] **Comment on this issue** with a decision regarding the request.
- [x] If you are a first-time [Release Captain], please review the high-level overview of the [patch release process].
- [ ] If approved, **add it to a patch release**:
  - If there is [already an upcoming patch release](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+), add the listed commits alongside a link to this issue
  - If there is no upcoming patch release, create a new one:
    - [x] Update [`dev/release/release-config.jsonc`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/release/release-config.jsonc) and open a PR to `main` to update it
      - [x] Change `upcomingRelease` to the current patch release
      - [x] Change `previousRelease` to the previous patch release version
      - [x] Change `releaseDate` to the current date (time is optional) along with `oneWorkingDayAfterRelease` and `oneWorkingDayBeforeRelease`
      - [x] Change `captainSlackUsername` and `captainGitHubUsername` accordingly
    - [x] `yarn release tracking:issues` 
    - [ ] Add the listed commits alongside a link to this issue to the generated [release tracking issue](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+)
- [ ] **Comment and close this issue once the relevant commit(s) have been cherry-picked into the release branch**.

[release captain]: https://handbook.sourcegraph.com/engineering/releases#release-captain
[patch release process]: https://handbook.sourcegraph.com/departments/product-engineering/engineering/process/releases#patch-release-process

**Comment by coury-clark** [comment]
The release guild is taking ownership of this patch (3.40.1) and the captain will be @unknwon. This patch will go out by May 31.
