### ISSUE TITLE
Open new ref panel feedback discussion board in new tab

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#36062]
Based on [external feedback](https://github.com/sourcegraph/sourcegraph/discussions/35668#discussioncomment-2823766) on our new CTA to try out and provide feedback on the beta reference panel. Users don't want to be taken away from their context on sourcegraph.com to provide feedback. The discussion board should be opened in a new tab instead.

**Comment by olafurpg** [comment]
@Numbers88s Is this issue still going to be worked on?

**Comment by jjinnii** [comment]
@macraig @olafurpg I'd feel comfortable closing this issue out as we're actively trying to ship the reference panel for all users in the very near future.

**Comment by olafurpg** [comment]
Sounds good.
