### ISSUE TITLE
insights: update series pings for backend unification effort

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#36097]
Right now, we collect pings that look like: 
![image](https://user-images.githubusercontent.com/11967660/170532912-5f54023f-639b-4617-9f9d-4d244f14fd79.png)

In other words, we have 3 options: 
`insight-type`::`repo-scope`::`generation`. 

After the unification work, anything that is currently `...::scoped::jit` will become `...::scoped::recorded`. 

We should make sure to update our pings so we capture this new reality.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by Joelkw** [comment]
@chwarwick added the pings issue!

**Comment by chwarwick** [comment]
Confirmed this works out of the box no code updates needed
