### ISSUE TITLE
insights: add feature flag to enable/disable just in time insights

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#36098]
Add a setting that is used to determine if insights that are scoped to specific repos run just in time or via the new backfilled method.  This flag does _not_ need to disable backfilling or snapshots/future points but instead should be used to determine if the _get_ path of the insight runs just in time returns the recorded points.

Webapp may need to see/use this setting to show the correct experience during live preview  https://github.com/sourcegraph/sourcegraph/issues/36094

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
