### ISSUE TITLE
insights: add pings for tracking share link feature usage 

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#36092]
We should track the pageviews and types of shares that people use, so we can determine the success of the feature and its usage (to prioritize improvements or bugfixes). 

Pings RFC to come.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by vovakulikov** [comment]
@Joelkw do you have any specific event that we want to add? 
So far I see a few events to add
- Click edit/copy/delete buttons
- Dashboard pills click 
- Filter change events

**Comment by Joelkw** [comment]
@vovakulikov take a quick look at this RFC – would love your thoughts: https://docs.google.com/document/d/1wDZRxiWBVbLs5Xh13rarBOGZS2ZekppSOSFIdGlkp9Q/edit#
