### ISSUE TITLE
Easier creation of batch specs

### ISSUE THREAD

**Issue by chrispine** [sourcegraph/sourcegraph#36106]
Based on presentations by @LawnGnome, @courier-new, @adeola-ak, and our design sprint with @danielmarquespt at our Lisbon offsite. Lots of cool ideas here:

- Notebooks as a way to ease into BC
- Build-a-BatchSpec
- Tutorial/sandbox ("AdeolaHub")

For more context, see our [offsite notes](https://docs.google.com/document/d/1IX2aERbWs8PVMni8m-VDP15TNJoNINS06VU29sbkvDU/edit#)

**Comment by camdencheek** [comment]
Closing since we no longer have context on this
