### ISSUE TITLE
vsce: log platform name

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#36118]
Ref: [slack](https://sourcegraph.slack.com/archives/C01T0BL4EFN/p1653210047961649?thread_ts=1652168724.890639&cid=C01T0BL4EFN) 

Currently, the extension is logging all events with `vscode` as the editor.

We should log appHost name to avoid misattribution of usage to VS Code as now the extension can be used on different platforms, like GitPod, and[ GitLab web](https://sourcegraph.slack.com/archives/C01LZKLRF0C/p1653372912130219) for example.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
