### ISSUE TITLE
JetBrains: Move settings from XML to the UI

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#36113]
## Context

Settings, such as Sourcegraph URL and access token are currently in the (project-specific) `sourcegraph.xml` file.

## Problem 

Without a UI, it's not convenient to edit the settings.

## Solution

Move them to the application Preferences (“Settings” on Windows) window.

The IntelliJ SDK has a pretty good toolkit to add a custom UI for plugins to edit their settings. [docs here](https://plugins.jetbrains.com/docs/intellij/settings.html)

The settings we currently have are:
 - **Sourcegraph URL**: string, default is “https://www.sourcegraph.com”, needs a textbox
 - **Default branch name**: string, default is “main”, needs a textbox
 - **Remote URL replacements**:
     - currently, just a string
     - it should actually be an array of string pairs: “search” → “replacement”.
     - This UI element would be totally cool and hopefully simple to use: https://share.cleanshot.com/qGbHFI – but this UI doesn’t seem to be part of IntelliJ Community Edition, so we can’t just copy and paste it.
     - There is a similar one: https://share.cleanshot.com/c8wSWQ and we have [source code](https://sourcegraph.com/github.com/JetBrains/intellij-community/-/blob/platform/platform-impl/src/com/intellij/ide/browsers/BrowserSettingsPanel.kt?L2&subtree=true) for this one, just has an extra column that we don’t need. 
 - **Globbing on/off**: boolean, needs a checkbox
 - **Access token**: string, default is “”, needs a textbox

It’s a good question which ones we want to make project-specific and which ones should be IDE-specific. **Project-specific** seems like a better solution.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by vdavid** [comment]
Notes while going through the [tutorial](https://plugins.jetbrains.com/docs/intellij/settings-tutorial.html).
- Comparison to the MVC model:
  - [Configurable](https://github.com/JetBrains/intellij-sdk-code-samples/blob/main/settings/src/main/java/org/intellij/sdk/settings/AppSettingsConfigurable.java): Controller. It interacts with the other two and the IntelliJ Platform.
  - [State](https://github.com/JetBrains/intellij-sdk-code-samples/blob/main/settings/src/main/java/org/intellij/sdk/settings/AppSettingsState.java): Model. It stores the Settings persistently.
  - [Component](https://github.com/JetBrains/intellij-sdk-code-samples/blob/main/settings/src/main/java/org/intellij/sdk/settings/AppSettingsComponent.java): View. It displays and captures edits to the State.

- [Application vs project](https://plugins.jetbrains.com/docs/intellij/settings-guide.html#extension-points-for-settings)
  - we want "project"
- [Attribute list and their meaning](https://plugins.jetbrains.com/docs/intellij/settings-guide.html#settings-declaration-attributes)
  - **instance**: required, set it to Configurable class
  - provider: we won't use this, we use "instance".
  - **nonDefaultProject**: set it to **false** ("how Settings for all projects.")
  - displayName: not sure if this is really needed because the Configurable has a mandatory method "getDisplayName"
  - key and bundle: not using these as the plugin won't be localized at this point.
  - **id**: required
  - **parentId**: see below.
  - groupWeight: 0 (lowest) seems to be fine. This would be more useful if we had more pages.
  - dynamic: not used
  - childrenEPName: not used
- [Parent IDs](https://plugins.jetbrains.com/docs/intellij/settings-guide.html#values-for-parent-id-attribute)
  - "tools" seems to be the right category for us: "Child group containing Settings to configure integration with third-party applications, specify the SSH Terminal connection Settings, manage server certificates and tasks, configure diagrams layout, etc."
