### ISSUE TITLE
repo-updater: Refactor observability code in {github|gitlab|etc}Connection

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#3612]
As @ijt so well noticed, the business logic is drowning in observability code, an orthogonal concern.

We should try to adopt something like we did for `Source` and `Store`: https://github.com/sourcegraph/sourcegraph/blob/master/cmd/repo-updater/repos/observability.go

**Comment by keegancsmith** [comment]
we mostly killed off the connection code. @tsenart is this still valid?

**Comment by tsenart** [comment]
The code that @ijt referred still exists. Example: https://github.com/sourcegraph/sourcegraph/blob/master/cmd/repo-updater/repos/github.go#L228
