### ISSUE TITLE
Improve auto-indexing global policies configuration messaging

### ISSUE THREAD

**Issue by macraig** [sourcegraph/sourcegraph#36120]
### Problem

When trying to configure a global policy users get prompted with the following warning:

> This Sourcegraph instance has disabled global policies for auto-indexing. Create a more constrained policy targeting an explicit set of repositories to enable this policy.

<img width="1180" alt="CleanShot 2022-05-26 at 17 38 13@2x" src="https://user-images.githubusercontent.com/1657213/170576081-9ca8fa31-cca0-4684-bea4-2c4ca691dd55.png">

The current message is problematic because:

A) It isn't actionable (no links to solution)
B) We haven't documented `codeIntelAutoIndexing.allowGlobalPolicies`, which forced the user to find a solution by navigating the entire codebase first
C) The red alert was described as "scary" for someone who is onboarding to auto-indexing configuration

### Potential solution

- [ ] #42283
- [ ] Add links to docs in the alert for the user to understand A) How to create more constrained policies and B) Create a global policy anyway (which would link to the doc created in the item above).
- [ ] Tone down the alert to reduce the sense of urgency in the warning.

Slack thread: https://sourcegraph.slack.com/archives/C03CSAER9LK/p1653536487299679

**Comment by Numbers88s** [comment]
Solution:

- Add link to autoindexing docs 👉 https://docs.sourcegraph.com/code_intelligence/how-to/enable_auto_indexing#configure-auto-indexing-policies
- Change the alert color to warning (yellow)
