### ISSUE TITLE
Perforce: Create a `main` branch as opposed to `master`

### ISSUE THREAD

**Issue by twarit-waikar** [sourcegraph/sourcegraph#36135]
**Requested by:** https://github.com/sourcegraph/accounts/issues/6938, https://github.com/sourcegraph/accounts/issues/6716

#### Feature request description

As part of a drive to see more inclusive language in our repositories, would it be possible to configure Sourcegraph's Perforce code host to create `main` branches when cloning Perforce code using git-p4.py or p4-fusion, as opposed to creating a `master` branch?

In particular, p4-fusion uses the libgit2 library which respects the `init.defaultBranch` setting in the environment's Git config (system level/repo level). Hence, if I run:

 ```shell
git config --global init.defaultBranch main
``` 

...before running p4-fusion on my system then it creates a `main` branch instead of master. If this feature is added to Sourcegraph, it might utilize the same command to make this change.

#### Is your feature request related to a problem? If so, please describe.

Just an effort to have more inclusive language in the eco-system. There is no hard engineering problem being caused by this.

#### Describe alternatives you've considered.

p4-fusion could be programmed to always create branches called `main`, however, this is something that is supported in libgit2 (the library that p4-fusion uses) only through the `init.defaultBranch` Git config. I haven't found a way in libgit2 to create a new named branch in a repository with no commits through just the libgit2 API.

#### Additional context

1. The branch creation API needs a commit to point to - https://libgit2.org/libgit2/#HEAD/group/branch/git_branch_create
2. libgit2 respects `init.defaultBranch` - https://github.com/libgit2/libgit2/releases/tag/v1.1.0

Encountered at https://github.com/sourcegraph/accounts/issues/6716

/cc @mrnugget

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.

**Comment by eseliger** [comment]
Verified working.

**Comment by ggilmore** [comment]
I verified this is working after forcibly reclining perforce repositories on S2

![Image](https://github.com/sourcegraph/sourcegraph/assets/9022011/53af4999-3e1f-4f79-8334-5afed6d5211b)
