### ISSUE TITLE
Patch release 3.3.2

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#3613]
# 3.3.2 Release

- [x] Create a checklist of the changes that you want to release (i.e. open or merged PRs).
    - [x] https://github.com/sourcegraph/sourcegraph/commit/90938366c4c2bcacd58220333cfd51f93a701aa9
    - [x] https://github.com/sourcegraph/sourcegraph/commit/68b73cac8a1fd9a9f2ad221ee12d53bd53b84d15
    - [x] https://github.com/sourcegraph/sourcegraph/commit/fdfb5daed01981c83395d77e57689a977adefc5b
    - [x] https://github.com/sourcegraph/sourcegraph/commit/e1917e5843549dc44551f95df07e8b87e9300d91
    - [x] https://github.com/sourcegraph/sourcegraph/commit/386d71dca996b5f3a53c91777b71c65848ed4b4b
    - [x] https://github.com/sourcegraph/sourcegraph/commit/00198eb0bfcc396c7dfeea7113fcf231ccbb3b9a
    - [x] 0c7ddbffc601a1d4d0624681592232ef7b6aab9a
- [x] Communicate your intentions by sending a message to #dev-announce that includes a link to this issue.
- [x] Cherry pick changes into the release branch and check them off the list above.
    - [x] Ensure that the cherry-picked commits don't depend on any commits that aren't already in the release branch.
- [x] Push the release branch with your cherry-picked commit(s) and make sure CI passes.

## Release sourcegraph/server

- [x] Create an annotated git tag and push it (this triggers CI to build the Docker images for the new version). For example:
    ```
    VERSION='v3.3.2' bash -c 'git tag -a "$VERSION" -m "$VERSION" && git push origin "$VERSION"'
    ```

- [x] Wait for the final Docker images to be available at https://hub.docker.com/r/sourcegraph/server/tags.

## Release Kubernetes deployment

In [deploy-sourcegraph](https://github.com/sourcegraph/deploy-sourcegraph):

- [x] Wait for Renovate to open a PR to update the image tags and merge that PR ([example](https://github.com/sourcegraph/deploy-sourcegraph/pull/199)).
- [x] Follow the ["Cutting a new patch version" instructions in https://github.com/sourcegraph/deploy-sourcegraph/blob/master/README.dev.md](https://github.com/sourcegraph/deploy-sourcegraph/blob/master/README.dev.md#cutting-a-new-patch-version-eg-v2121)

## Update the docs

- [x] Update the version (major.minor.patch) of Sourcegraph in the docs ([example](https://github.com/sourcegraph/sourcegraph/pull/2841)) by running the following 
  ```
  find . -type f -name '*.md' -exec sed -i '' -E 's/sourcegraph\/server:[0-9\.]+/sourcegraph\/server:$NEW_VERSION/g' {} +
  ```
- [x] Update versions in docs.sourcegraph.com template ([example](https://github.com/sourcegraph/sourcegraph/pull/2841/files#diff-3d0e70da24a04f44a1fdc404b7242b89L32))
- [x] Update `latestReleaseKubernetesBuild` and `latestReleaseDockerServerImageBuild` ([example](https://github.com/sourcegraph/sourcegraph/pull/2370/commits/15925f2769564225e37013acb52d9d0b30e1336c)).
- [x] Create a new section for the patch version in the changelog. Verify that all changes that have been cherry picked onto the release branch have been moved to this section of the [CHANGELOG](https://github.com/sourcegraph/sourcegraph/blob/master/CHANGELOG.md) on `master`.
- [x] Post a reply in the #dev-announce thread to say that the release is complete.

**Comment by ggilmore** [comment]
@nicksnyder FYI, I have cherry-picked a commit ontop of the 3.3 branch https://github.com/sourcegraph/deploy-sourcegraph/commit/3094adaed9bc47add2089ccdd7d1b54028704ac4. Could you make sure to include it when you tag 3.3.2 for deploy-sourcegraph?
