### ISSUE TITLE
OSS version always delete my mannually cloned repository .git info

### ISSUE THREAD

**Issue by hitzhangjie** [sourcegraph/sourcegraph#36136]
- **Sourcegraph version:** docker hub sourcegraph/server:insiders
- **Platform information:** macOS catalina

#### Steps to reproduce:

1. clone git repo and put it under .sourcegraph/data/repos/<host>/<org>/<repo>
2. at site admin UI, add the repo

#### Expected behavior:
sourcegraph can index it and search

#### Actual behavior:
sourcegraph delete the .git folder under <repo> and cannot index and search
This make it unusable for mannually cloned repository.

And it may stuck when I press Ctrl+C to terminal the docker container, docker kill <containerID> not work, neither. I have to restart docker engine.

**Comment by hitzhangjie** [comment]
This make it unusable for mannually cloned repository.

**Comment by mrnugget** [comment]
Hey @hitzhangjie! For local repositories we recommend using `src serve-git`. `.sourcegraph/data/repos` is an internal folder.

See: https://docs.sourcegraph.com/admin/external_service/non-git
