### ISSUE TITLE
Clojure code intelligence is spotty

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#3614]
- **Sourcegraph version:** Sourcegraph.com

#### Steps to reproduce:

0. Enable the Clojure extension: https://sourcegraph.com/extensions/sourcegraph/clojure
1. Visit any Clojure repo on Sourcegraph.com, via https://github.com/trending/clojure, e.g. in https://sourcegraph.com/github.com/tonsky/FiraCode@master/-/blob/clojure/glyphs.clj
2. See that SOME symbols show hovers (e.g. [`current-char`](https://sourcegraph.com/github.com/tonsky/FiraCode@master/-/blob/clojure/glyphs.clj#L11:7) works for me, but not [`skip-ws!`](https://sourcegraph.com/github.com/tonsky/FiraCode@master/-/blob/clojure/glyphs.clj#L17:7)). Most symbols don't work. Other repos have similar behavior.

Requested by:
* https://app.hubspot.com/contacts/2762526/company/694011992

**Comment by chrismwendt** [comment]
Ah, I need to make the `identCharPattern` configurable per language https://github.com/sourcegraph/sourcegraph-basic-code-intel/blob/a74c0aa6b41a36ce99da9484f6a855a69e409a2f/package/src/handler.ts#L15

**Comment by FelipeCortez** [comment]
Not sure if I should post this to the sourcegraph-basic-code-intel repo instead, but some characters are still missing from the regex. From the [Clojure reader reference](https://clojure.org/reference/reader):

> Symbols begin with a non-numeric character and can contain alphanumeric characters and *, +, !, -, _, ', ?, <, > and = (other characters may be allowed eventually).

I think the correct regex should be something like `[A-Za-z0-9_\-!?*+\'<>=]`

**Comment by dadlerj** [comment]
Hey @FelipeCortez — we actually made one additional update after the PR above to add several of the other characters: https://github.com/sourcegraph/sourcegraph-basic-code-intel/pull/188

The new regex looks like: `/[A-Za-z0-9_\-!?+*<>=]/` (we left out `'` due to risk of causing tokenization issues. If it's important for you, we can build a workaround.)

The highlighting issue was _not fixed_, but the ability to hover and go-to-definition should have been fixed.

Just to check, can you hover on symbols with the new characters (such as `->`) and get type information?

@chrismwendt did you end up publishing the final version?

**Comment by chrismwendt** [comment]
> @chrismwendt did you end up publishing the final version?

Yes, I checked by downloading the JS code for sourcegraph/clojure from https://sourcegraph.com/extensions/sourcegraph/clojure (at the moment it's https://sourcegraph.com/-/static/extension/3313-sourcegraph-clojure.js?bzwm0grg8tww--sourcegraph-clojure) and found the latest regex:

![image](https://user-images.githubusercontent.com/1387653/72933439-fe1f5180-3d1e-11ea-9369-7110dc7eb801.png)

**Comment by FelipeCortez** [comment]
@dadlerj this fixes it! I don't think the `'` is too important. I can hover on symbols with the new characters and get the popup, yes!

One more thing: we rely on [Plumatic Schema](https://github.com/plumatic/schema) a lot so most of our defns are actually `(s/defn ,,,`. Is there any way to make the code intelligence work for that?

**Comment by chrismwendt** [comment]
@FelipeCortez I created https://github.com/sourcegraph/sourcegraph-basic-code-intel/issues/225 to track the work required to support other definition keywords like `s/defn`.

**Comment by efritz** [comment]
We've improved ctags support for Clojure so symbols defined by def, defn (was already supported), deftype, defrecord, and defprotocol will be visible for code intel as well as their _s/_ variants.

See https://github.com/sourcegraph/sourcegraph/pull/8413. This will be available in 3.13.

**Comment by macraig** [comment]
We can close it for now and reopen if someone finds it buggy again. For the interest in Clojure LSIF I can add the request to Productboard, the HubSpot link seems broken though, do you remember from who this was?

> Requested by:
> https://app.hubspot.com/contacts/2762526/company/694011992

**Comment by scalabilitysolved** [comment]
Are we able to close now @macraig ?

**Comment by dadlerj** [comment]
Sorry for not responding to your earlier question @macraig —this was for https://app.hubspot.com/contacts/2762526/company/2528658277 (they are no longer a prospect).
