### ISSUE TITLE
Hover tooltip shows up in peek code view of new reference panel

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#36140]
- **Sourcegraph version:** sourcegraph.com
- **Platform information:** chrome

#### Steps to reproduce:

1. Go to https://sourcegraph.com/github.com/sourcegraph/go-diff/-/blob/diff/diff.go?L22:2#tab=references
2. Click through references

#### Expected behavior:

No additional popover shows up in the "peek" code view on the right

#### Actual behavior:

Popover shows up (sometimes with slight delay) in "peek" code view, showing redundant information and covering the surrounding code, which is what the user most likely wants to see in the peek code view.

Video:

https://user-images.githubusercontent.com/1185253/170654848-28c03edd-8cd9-4f14-8834-358aee640376.mp4

**Comment by chrismwendt** [comment]
I think the same underlying bug is causing https://github.com/sourcegraph/sourcegraph/issues/36131 I'm looking into this today 👀
