### ISSUE TITLE
JetBrains: Recalculate offset for Windows linebreaks

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#36144]
Before [this PR](https://github.com/sourcegraph/sourcegraph/pull/36079), Java failed with an error when we sent a string that included Windows-style line breaks. The PR fixed it, but now the highlight position is off:

![image](https://user-images.githubusercontent.com/2552265/170661217-0edba34b-07b3-4c81-bd10-0b1f81132b14.png)

Test it with [this search](https://sourcegraph.com/search?q=context:global+repo:github.com/996icu/996.ICU+Protest+Over+Chinese+Tech+Companies+file:ko_KR&patternType=literal):
```
repo:github.com/996icu/996.ICU Protest Over Chinese Tech Companies file:ko_KR
```

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
