### ISSUE TITLE
JetBrains: Handle "no preview" case better

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#36151]
As @philipp-spiess pointed out [here](https://github.com/sourcegraph/sourcegraph/pull/36079/files/6cd0fe2016e1c145268bf107120d8b39dafbf454#r883383652), we should handle the "no preview available" case in a nicer way. Right now, we just write "No preview available" in the preview box, but it'd be nicer to have a dedicated empty component for this (probably a `JBPanelWithEmptyText` wrapper around the preview panel).

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by jjinnii** [comment]
@vdavid Please share any ideas/solutions for possible other solutions for a "no preview". I'll be thinking through it in Figma as well, but it will be heavily constrained by what components we can utilize/how much.

**Comment by vdavid** [comment]
Update: We now have the `JBPanelWithEmptyText` in place, but it doesn't work well. Raising the priority of this issue for this reason, it's practically a bug now.

**Comment by vdavid** [comment]
Oh, this was actually fixed by my recent PR: https://github.com/sourcegraph/sourcegraph/pull/37130
