### ISSUE TITLE
JetBrains: Disallow opening non-file search results

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#36152]
As @philipp-spiess pointed out [here](https://github.com/sourcegraph/sourcegraph/pull/36079/files/6cd0fe2016e1c145268bf107120d8b39dafbf454#r883384698), we need to make sure the user can't initiate opening a search result in the editor which is not an actual file.

I think it already works this way, but it's not intentional (maybe just errors out in the background), so it needs a review and possibly a fix.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by philipp-spiess** [comment]
Instead of disallowing (and potentially have a user stuck without a nice way to unstuck them) what do you think about opening a user's browser and navigate the sourcegraph.com in these scenarios?

**Comment by vdavid** [comment]
We could totally do that!
Btw, to be specific, this issue covers the `repo` and `commit` search types.

**Comment by vdavid** [comment]
Also, just to save this somewhere, this is the way to open the browser:

https://stackoverflow.com/questions/5226212/how-to-open-the-default-webbrowser-using-java

**Comment by vdavid** [comment]
This is already done.
