### ISSUE TITLE
JetBrains: Clean up search result CSS

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#36155]
It's a mess now and it'll be difficult to maintain if we leave it this way.

Extract the search-type specific parts to search-type specific CSS, and attach the common CSS to a wrapper component (we'll create one in https://github.com/sourcegraph/sourcegraph/issues/36154).

(Suggested by @philipp-spiess here: https://github.com/sourcegraph/sourcegraph/pull/36079#discussion_r883391550)

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
