### ISSUE TITLE
JetBrains: TS refactor: extract search result properties to a wrapper

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#36154]
We have this repeated for each search result type:
```jsx
 <div id={`search-result-list-item-${resultId}`}
    className={classNames(styles.line, { [styles.lineActive]: resultId === selectedResult })}
    onClick={onClick}
    key={resultId}>
```

As @philipp-spiess suggested [here](https://github.com/sourcegraph/sourcegraph/pull/36079/files/6cd0fe2016e1c145268bf107120d8b39dafbf454#r883388808), “This part can probably be extracted in a wrapper component and reused (since it got quite specific behavior like the html id property that we need to ensure is correctly used across all search results).”

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
