### ISSUE TITLE
JetBrains: Improve UX for different search result types

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#36158]
## Context

Right now it looks like this:
![image](https://user-images.githubusercontent.com/2552265/170696589-f4ad69ee-47f8-4382-bd85-33503c6e7d2d.png)

## Problem

It's difficult to make out the different parts. (suggested by @philipp-spiess here: https://github.com/sourcegraph/sourcegraph/pull/36079#discussion_r883386301)

## Solution

We could render the repo name in a different color so that the line is easier to scan visually.
@jjinnii will come up some design to make this nice.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by philipp-spiess** [comment]
@jjinnii Can we close this task or are you still working on some follow-up fixes here? 🙂

**Comment by vdavid** [comment]
Based on the description, this should be done. I'm closing this for a feeling of success for Iteration 11 😄 (everything else is done! 🎉 )
