### ISSUE TITLE
Change git `init.defaultBranch` configuration on `gitserver` to `main`

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#36177]
#### Feature request description

[`p4-fusion`](https://github.com/salesforce/p4-fusion/tree/master/p4-fusion) respects the git config `init.defaultBranch` when generating a new git repository.  git normally creates a default branch named `master` for new repositories and hence `p4-fusion` is creating a master branch by default.   It would be better if it created a default branch named `main` instead.

#### Describe alternatives you've considered.

We could run `git config --global init.defaultBranch main` from `p4-fusion` or manually on `gitserver`.  But it seems better to have the default behavior of `gitserver` changed or to allow users of Sourcegraph to configure it.

#### Additional context

[Customer #6716](https://github.com/sourcegraph/accounts/issues/6716) suggested this change in [this Slack thread](https://sourcegraph.slack.com/archives/C01D50MSA7L/p1653593461791489).

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.

**Comment by mike-r-mclaughlin** [comment]
duplicate of #36135
