### ISSUE TITLE
insights: editing an insight from the single view page takes you back to the dashboard view

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#36186]
When editing an insight from the "share" page (the single insight view page), the user is redirected to the "all insights" dashboard after the edit is complete. I'd expect the user to be redirected back to the single view page.

Reproduce:
1. Pick an insight and navigate to the sharable link
2. Edit the insight and click create
3. Get redirected back to the all insights dashboard

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
