### ISSUE TITLE
SSBC: Template variable errors only caught in execution

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#36183]
When template variables are unknown, or the template doesn't compile properly, that is only determined during the actual execution. Seems efficient to do it earlier in the pipeline, ideally in the editing stage. Also, this error is not surfaced in the UI, it just generically fails.

**Comment by eseliger** [comment]
Ideally, we fix both because there can still be discrepancies between the backend and executor src version.

**Comment by chrispine** [comment]
This feels like an important ease-of-use issue: help customers solve their own problems.

However, how often to people even use template variables? If it's more than _rarely_, I'd vote to keep this one in P2.

**Comment by courier-new** [comment]
I wish we had usage metrics on that sort of thing. 😅 Given the estimate, I might vote to bump it up to P1 or P0 since it's in line with the stability theme.

**Comment by malomarrec** [comment]
I vote for P0

**Comment by malomarrec** [comment]
We just got feedback from a [user](https://sourcegraph.slack.com/archives/C020ZQA5MH8/p1661953670057259) at https://github.com/sourcegraph/accounts/issues/532 that encountered this.

**Comment by eseliger** [comment]
Additional note: I think it would be perfect if this would also work pre-preview (as in, either have an endpoint that we can convert to LSP for monaco, or implement a TS version of the validator), but should not a blocker to getting a first version of it out.

**Comment by malomarrec** [comment]
This definitely is a bad experience, and small things like prevents SSBC from fully shining. Great to see this is in progress :)

**Comment by mrnugget** [comment]
did someone say abstract interpretation just now?!

**Comment by eseliger** [comment]
that ticket here is up for _interpretation_
