### ISSUE TITLE
batches: This repository was archived so it is read-only.

### ISSUE THREAD

**Issue by sfllaw** [sourcegraph/sourcegraph#36201]
- **Sourcegraph version:** 3.40.0

#### Steps to reproduce:

1. Create a batch change with a changeset that affects an [archived repository](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories).
2. Publish that changeset

#### Expected behavior:

Sourcegraph realizes that the repository is archived and does something sensible.

It should probably leave the changeset as _Unpublished_ and maybe offer you the option to change the state to _Archived_.

#### Actual behavior:

> Failed to run operations on changeset
> Creating commit from patch for repository "github.com/sfllaw/archived-repo": gitserver: pushing ref: exit status 128
> ```
> $ git -c credential.helper= -c protocol.version=2 push --force https://<redacted>@github.com/sfllaw/archived-repo 0f010a375f9b8bb7e96a7aa2c610fb5d6729d910:refs/heads/branch
> remote: This repository was archived so it is read-only.
> fatal: unable to access 'https://github.com/sfllaw/archived-repo/': The requested URL returned error: 403
> ```

**Comment by BolajiOlajide** [comment]
Hello @sfllaw,

Thanks for   this issue. 
We've added it to our planning discussion list and we will respond after.

Cheers!

**Comment by LawnGnome** [comment]
@sfllaw We're trying to understand the scenario that led to this error — in your batch spec, did you include `archived:true` in your search query, or explicitly add the repository to the batch spec?

**Comment by sfllaw** [comment]
@LawnGnome I did include `archived:true` in my search query, but Sourcegraph doesn’t always respect this flag. But even if it did, there’s a race between archiving a repository and publishing the changeset, so publishing should not result in a generic failure.

By racing, I mean:
1. Use batch changes to create an unpublished changeset against an active repository
2. Archive that repository
3. Publish the changeset

**Comment by LawnGnome** [comment]
To close this off: we've added support for handling archived repositories in Sourcegraph 3.42 (out today, hopefully!). 

Changesets that are open on repos that become archived now move into a *Read-Only* state, and if the repo is unarchived, they move back into whatever state is appropriate (presumably *Open*, in most cases). Applying a batch spec now detects and handles archived repos appropriately — not as errors, but by migrating non-read-only changesets into read-only, and by not trying to make further changes to read-only changesets.

Thanks again for the report, and especially for your comment on #26820, which definitely informed our testing plan!
