### ISSUE TITLE
Code Insights: The filters section on the standalone page has unresponsive layout

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#36214]
If you open the standalone insight page for insight that can have a sort series setting (filter) you can see that the open state for the filter panel takes too much space because it doesn't adapt to the content properly 

<img width="1184" alt="Screenshot 2022-05-30 at 14 10 40" src="https://user-images.githubusercontent.com/18492575/170928321-ea1149ae-066c-43e8-9835-a026ee4ffb97.png">

Insight to reproduce https://k8s.sgdev.org/insights/insight/aW5zaWdodF92aWV3OiIyMjZENHJKUVd3RkpFWktMYmlWeWFHNmtjenQi

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
