### ISSUE TITLE
Datadog-metrics extension doesn't work as expected

### ISSUE THREAD

**Issue by taras-yemets** [sourcegraph/sourcegraph#36213]
Chime reports [datadog-metrics](https://sourcegraph.com/extensions/sourcegraph/datadog-metrics) extension doesn't work for them ([thread](https://sourcegraph.slack.com/archives/C01LZKLRF0C/p1653588845616569)).
They suspect ([Chorus snippet](https://hello.chorus.ai/listen?guid=7a12ebf7d6e84f04b9df72f545475325)) it may be because [the regex](https://github.com/sourcegraph/sourcegraph-datadog-metrics/blob/master/src/datadog-metrics.ts#L5) used by the extension doesn't match their datadog service calls.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by taras-yemets** [comment]
@drohnow, the issue is that our customer calls to the Datadog API are different from our default case ([regex](https://github.com/sourcegraph/sourcegraph-datadog-metrics/blob/master/src/datadog-metrics.ts#L5), [usages](https://github.com/sourcegraph/datadog-democode/blob/master/democode.py) on lines 33, 49, 65, 90), correct?

For example, datadog-metrics extension currently handles usages like `statsd.doSomething('metric.name')` and our customers expect support for something like `genericStatsdWrapper.doSomethingElse('metric.name')`.
