### ISSUE TITLE
JetBrains: Add offset to symbol search results

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#36223]
SymbolMatch doesn't contain the coordinates: https://share.cleanshot.com/0kq3ni so we'll need to assemble this on our own apparently. :/
This will also come up when we fix the highlight jumps: https://github.com/sourcegraph/sourcegraph/issues/36222

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
