### ISSUE TITLE
insights/compute: improve compute client to expose skipped reasons

### ISSUE THREAD

**Issue by leonore** [sourcegraph/sourcegraph#36227]
this is an issue parallel to https://github.com/sourcegraph/sourcegraph/issues/36226 for compute.

we'd like the compute client to expose skipped reasons so that we can retry on shard timeouts.

according to the search team:

> I think you want something like [progressAggregator](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@1385aaa591ad131cd93b79c082c9890e6865a0ef/-/blob/cmd/frontend/internal/search/progress.go?L13-25) for compute. It will be [updated](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@1385aaa591ad131cd93b79c082c9890e6865a0ef/-/blob/cmd/frontend/internal/search/progress.go?L27-27) with the compute [Event](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@1385aaa591ad131cd93b79c082c9890e6865a0ef/-/blob/enterprise/cmd/frontend/internal/compute/streaming/event.go?L5-7) type, and you’ll probably need to add the [Stats](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@1385aaa591ad131cd93b79c082c9890e6865a0ef/-/blob/internal/search/streaming/progress.go?L14-14) field (which is how we stream repo status) to the Event result similar to how it’s done on the [SearchEvent](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@1385aaa591ad131cd93b79c082c9890e6865a0ef/-/blob/internal/search/streaming/stream.go?L14-17) type.
Then, you’ll just want to either add a progress event to the output stream (similar to [how it’s done in the search stream](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@1385aaa591ad131cd93b79c082c9890e6865a0ef/-/blob/cmd/frontend/internal/search/search.go?L222-222)), or since you probably don’t care about getting progress updates incrementally, you could probably just add that information to the [done event](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@1385aaa591ad131cd93b79c082c9890e6865a0ef/-/blob/enterprise/cmd/frontend/internal/compute/streaming/stream.go?L60-60).

once that is done we can then use those skipped reasons in the insights [decoder](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/insights/query/streaming/decoder.go?L140) like it will be done in the issue above.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
