### ISSUE TITLE
JetBrains: Preview: Jump to highlights in all five search result types

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#36222]
We want to jump to the highlighted section of the search results when we render the preview.
Currently, this feature is not implemented for any search type.

- [ ] commit
- [x] content
- [ ] path
- [x] symbol
- [ ] repo

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by philipp-spiess** [comment]
commit, path, and repo results have no sensible highlights in the API response that we could display and jump-to so I think it is fine if we don't have that!

**Comment by vdavid** [comment]
Absolutely!
