### ISSUE TITLE
insights: `DeleteInsightView` never soft deletes insight series

### ISSUE THREAD

**Issue by leonore** [sourcegraph/sourcegraph#36229]
found as part of https://github.com/sourcegraph/sourcegraph/issues/35882

if an insight view is deleted, we don't soft delete (`is_deleted = time()`) insight series, which means query runner jobs don't get pruned [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/enterprise/internal/insights/background/data_prune.go?L36:33)

considerations:
* we should only delete insight_series if they are not shared across multiple views.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by leonore** [comment]
actually @Joelkw apologies about this but it might be a redundant issue and this information could just be condensed into a comment on the original bug report, if we want to close this one. sorry if I rushed into this one!

**Comment by leonore** [comment]
closing this as we can just hold this information in the original issue
