### ISSUE TITLE
JetBrains: Previewing files with special character encodings don't work

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#36231]
Try to search for a file with some special characters. You will see the following error in the console and the preview won't open. This is likely an encoding error,

![Screenshot 2022-05-30 at 14 44 03](https://user-images.githubusercontent.com/458591/170994953-05530a6f-dce6-400b-be03-663fe8fade83.png)

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by philipp-spiess** [comment]
Actually, this doesn't happen consistently with files containing some special characters, it may be something more specific, i.e. I tried adding `Čeština` to the query and not all files were broken. 

Here's a specific query to get to the error consistently:

```
Čeština file:README-ro.md r:^github\.com/jlevy/the-art-of-command-line$ 
```
