### ISSUE TITLE
ci: logs over 1mb are getting rejected by Loki

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#36240]
Example: https://buildkite.com/sourcegraph/sourcegraph/builds/150519#018114ed-f676-487a-b0ea-8f28752d2271/459-462 

Slack context: https://sourcegraph.slack.com/archives/C07KZF47K/p1653917535527729?thread_ts=1653915784.426589&cid=C07KZF47K

Basically, some verbose jobs are racking up logs very quickly, which are then getting rejected by Loki for being too large. This is problematic, because it impedes our ability to search for previous failures.

**Comment by bobheadxi** [comment]
@burmudar quick thought - we can split up the entries that are too big, and submit them as separate entries incremented by a nanosecond or something. We need to be careful with this, since duplicate/misaligned timestamped entries will be rejected by Loki
