### ISSUE TITLE
Map new proposed flow - share with design & marketing for review

### ISSUE THREAD

**Issue by erzhtor** [sourcegraph/sourcegraph#36247]

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @a-bergevin - the "team/growth" label was applied to this issue.

**Comment by thenamankumar** [comment]
@erzhtor here is the proposed flow open for review: https://www.figma.com/file/iYTAwYgdFIWL5whkKYfQVs/Expanded-Registration-Flow-A%2FB-Test?node-id=0%3A1
