### ISSUE TITLE
repo-updater: debt: ugly rate limit handling code introduced by me in migration codepath

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#3624]
In https://github.com/sourcegraph/sourcegraph/pull/3617 I introduced an ugly fix for #3590 by using string error comparison and a sleep statement.

As mentioned in the TODO, ideally the underlying codehost source `ListRepos` would have an option passed down to it via the migration codepath which would cause it to slow down when rate limiting is encountered. I did not do it this way because I wasn't confident in my ability to do so quickly for the emergency patch release without introducing other potential regressions.

It would be good to remove this code sooner rather than later in favor of a proper fix, but probably can be done in just 3.4 with no need for a subsequent patch release I think.

**Comment by tsenart** [comment]
Cross posting this comment because it applies here: https://github.com/sourcegraph/sourcegraph/pull/3617#issuecomment-486970503

**Comment by slimsag** [comment]
@tsenart about your comment, thanks for the links.

I am curious if you could explain how this log line occurred to me? https://sourcegraph.slack.com/archives/GDS3PJ8GK/p1556144718002600?thread_ts=1556144204.001000&cid=GDS3PJ8GK

definitely possible I've just misunderstood one of your changes in some way

**Comment by tsenart** [comment]
Pasting those log lines with private info redacted here for context:

```
repo-updater | t=2019-04-24T22:15:40+0000 lvl=eror msg=migrate error="migrate.repos-enabled-state-deprecation.sources.list-repos: 1 error occurred:\n\t* Error getting GitHub repository: nameWithOwner=foo/bar: request to http://127.0.0.1:3180/repos/foo/bar returned status 403: You have triggered an abuse detection mechanism. Please wait a few minutes before you try again.\n\n" waiting=5s
```

This indicates that we hit the abuse rate limit, not the normal rate limit. [Until yesterday](https://github.com/sourcegraph/sourcegraph/issues/3582) I wasn't aware of the difference.

But we fixed this by making requests [serially for the same code host](https://github.com/sourcegraph/sourcegraph/pull/3605) and respecting [`Retry-After` headers](https://github.com/sourcegraph/sourcegraph/pull/3609).

We should not hit more [*abuse*](https://developer.github.com/v3/guides/best-practices-for-integrators/#dealing-with-abuse-rate-limits) rate limits after those changes.

**Comment by slimsag** [comment]
Got it, that makes sense. The context I was missing was that we handled _rate limiting_ properly but just not _abuse rate limiting_. I assumed we needed to handle both in that situation, when in reality your change yesterday addressed it because we've only received reports with logs indicating the latter.

Reverting my change SGTM then!
