### ISSUE TITLE
UI bug in site config page `save changes` button

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#36268]
This is a stub issue of https://github.com/sourcegraph/customer/issues/979 for grooming purposes.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam-and-admin-experience - the "team/iam-admin-experience" label was applied to this issue.

**Comment by unknwon** [comment]
Hey team! Please add your planning poker estimate with ZenHub @kopancek @miveronese @pietrorosa77 @pjlast @unknwon

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.
