### ISSUE TITLE
EngEd Video: Wildcard Component Library

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#36266]
To coincide with the completion of V2 of the Wildcard Component Library, we'll collaborate with the Frontend Platform Team to raise awareness about the WCL internally, highlight its value, and offer examples of how we're using Sourcegraph Code Insights to help build Sourcegraph. 

- [ ] Planning & script
- [ ] Video recording
- [ ] Screen recording
- [ ] Editing
- [ ] Upload
- [ ] Add thumbnail
- [ ] Add transcript
- [ ] Add to handbook
- [ ] Add related links
- [ ] Add feedback link

**Comment by marekweb** [comment]
> offer examples of how we're using Sourcegraph Code Insights to help build Sourcegraph.

We'll discuss if this part fits in this intro video, or if if we'll include it in a follow-up video.
