### ISSUE TITLE
zoekt: incremental-indexing: support compound shards

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#36273]
Right now, the compound shard logic is completely unaware of the incremental indexing prototype. Up until now, this hasn't been an issue since zoekt only creates compound shards for inactive repositories (no commits within two weeks or so). 

This hasn't been the case for any of our test repositories (sourcegraph, megarepo, gigarepo), but it will be an issue once we start opt-in less-active repositories into the incremental indexing prototype. 

Ways of supporting this could include: 

1. compound shards ignore delta shards - this approach has a problem in that currently you can't differentiate between shards that are produced from the incremental indexing strategy, or ones that were produced via the normal strategy 
2. adding full support for supporting delta builds with compound shards (if a repository in a compound shard is updated- should we explode the compound shard and then use part of those shards as the base shards for the build? )

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/search-core - the "team/search-core" label was applied to this issue.

**Comment by stefanhengl** [comment]
Merging currently excludes repos with more than 1 shard. This means we automatically exclude delta shards which I think is a nice property. 

Do we compact delta shards if the repo has been inactive for some time? If not, maybe we should add it?

1. active repos have delta shards
2. if they turn inactive we compact them
3. if they are small enough (=1 shard) and still inactive we merge them into a compound shard (current behavior)
4. if a repo in a compound is updated we index it from scratch (this is fine because repos in compound shards are per definition small)

**Comment by stefanhengl** [comment]
> if a repository is in a compound shard, but later gets a commit, the first step is to mark the repo as "deleted/tombstoned" in the compound shard
Then, we can immediately do a full index using the old strategy. This will place the shard(s) on disk separately, outside of a compound shard.

That's the strategy we already have right now

**Comment by stefanhengl** [comment]
> definitively identifying a shard as a delta shard (it seems like this is worth implementing, since this has been brought up many times)

Once we have this we can just reindex every delta shard after X days in the cleanup loop.

> Could we do this by bumping/inserting a new entry into the indexing queue and forcing it to use the old indexing strategy?
We 

Either that or call call forceIndex holding the lock.

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket, please let us know how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
