### ISSUE TITLE
JetBrains: Code preview does not scroll to make the highlight visible

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#36279]
When previewing a larger file where the match is not in the first view LOCs, we want the preview component to scroll to the highlight to behave like the native search component. An example for this is the following query:

```
r:^github\.com/sourcegraph/sourcegraph$ file:README.md Enable web view debugging
```

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
