### ISSUE TITLE
Code Insights: Sort and limit filters don't work as other filters

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#36286]
Follow up for https://github.com/sourcegraph/sourcegraph/pull/34611

In general, we implemented the sort and limit filter section in a different way compared to other filter sections. 

The problem
- You can't save "Sort and limit" filters until you changed something in other filters
- "Sort and limit" filters don't have a filter changed marker (purple dot next to the filter section title)
- "Default filter applied" is shown even if  "Sort and limit" filters have been changed. 

<img width="1184" alt="Screenshot 2022-05-31 at 19 23 31" src="https://user-images.githubusercontent.com/18492575/171163368-84c642ff-9abb-4664-9b57-398d7d0486eb.png">

@AlicjaSuska Personal feedback (from @vovakulikov) it seems like we don't use space in this filters section in an optimal way, have we considered using a different layout for this section? 

<img width="1184" alt="Screenshot 2022-05-31 at 19 35 34" src="https://user-images.githubusercontent.com/18492575/171164298-77fa6ec4-36ce-4472-b381-f474d32c0af0.png">

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
