### ISSUE TITLE
JetBrains: Preview doesn't always update for commit search results

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#36293]
40-sec Loom demoing the bug [here](https://www.loom.com/share/5b758594b823400f968bee7f134ac214).

The search query I used in the demo is this one: `repo:^github\.com/sourcegraph/sourcegraph$@main type:diff latest`

**Comment by vdavid** [comment]
Ah, okay, this might be caused by the wrong line separators that has been fixed by @philipp-spiess in https://github.com/sourcegraph/sourcegraph/pull/36282 which hasn't been merged yet.

**Comment by philipp-spiess** [comment]
@vdavid Yeah let's revalidate after https://github.com/sourcegraph/sourcegraph/pull/36282 is merged otherwise have you looked into the JS debug console?

**Comment by vdavid** [comment]
It looks like it works now, I couldn't reproduce the problem. Tested it in the IDE ([15 sec, no audio Loom](https://www.loom.com/share/fc97c595b7d840adb1afc828910c7fe2)) and in the standalone version. Closing this.
