### ISSUE TITLE
unused internal routes

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#36290]
According to prometheus on sourcegraph.com and k8s.sgdev.org these are the unused internal routes. They might get triggered in other environments, although in most cases this is unlikely. So some confirmation is required before deleting the code.

- [x] internal.can-send-email
- [x] internal.extension
- [x] internal.external-services.list
- [x] internal.git.exec
- [x] internal.git.resolve-revision
- [x] internal.orgs.get-by-name
- [x] internal.orgs.list-users
- [x] internal.phabricator.repo.create
- [x] internal.repos.get-by-name
- [x] internal.repos.inventory
- [x] internal.repos.inventory-uncached
- [x] internal.repos.list
- [x] internal.settings.get-for-subject
- [x] internal.users.get-by-username

<details>

```promql
max by (route)(max_over_time(src_http_requests_last_timestamp_unixtime{route=~"internal.*"}[30d]))
```

Combined list for sourcegraph and k8s.sgdev. There where differences, so anything missing from this list will require some confirmation that it is indeed a dead route.

    internal.app-url
    internal.configuration
    internal.external-services.configs
    internal.git.info-refs
    internal.git.upload-pack
    internal.repos.index
    internal.search-configuration
    internal.send-email
    internal.stream-search
    internal.user-emails.get-email

Then the list of routes defined:

```shell
src search 'r:^github\.com/sourcegraph/sourcegraph$ f:router "internal.' \
    | egrep -o 'internal\.[^"]+' | sort | uniq
```

    internal.app-url
    internal.can-send-email
    internal.configuration
    internal.extension
    internal.external-services.configs
    internal.external-services.list
    internal.git.exec
    internal.git.info-refs
    internal.git.resolve-revision
    internal.git.upload-pack
    internal.orgs.get-by-name
    internal.orgs.list-users
    internal.phabricator.repo.create
    internal.repos.get-by-name
    internal.repos.index
    internal.repos.inventory
    internal.repos.inventory-uncached
    internal.repos.list
    internal.search-configuration
    internal.send-email
    internal.settings.get-for-subject
    internal.stream-search
    internal.user-emails.get-email
    internal.users.get-by-username

So the list of routes not currently getting hit in prod:

```bash
comm -13 <(echo "${used}") <(echo "${names}") | awk '{printf("- [ ] %s\n", $1)}'
```

</details>

**Comment by keegancsmith** [comment]
@camdencheek Nice. I see in your discussion you did it using editor tooling. If you check the details in the task description you can see this list was based off usage data via prometheus. So you can have a bit more confidence. I wonder if we can resurrect that PR since the list seems to be the same?

**Comment by camdencheek** [comment]
> If you check the details in the task description you can see this list was based off usage data via prometheus.

Yes! I hadn't thought to double check with prometheus. Happy to resurrect it if it saves any effort.

**Comment by eseliger** [comment]
did some more here and ticked them off above: https://github.com/sourcegraph/sourcegraph/pull/39304

**Comment by ryanslade** [comment]
@keegancsmith: Regarding `internal.git.resolve-revision` I see this comment on the handler:

https://github.com/sourcegraph/sourcegraph/blob/ac88f10e353573ad3b245f146dcf90b6278851d7/cmd/frontend/internal/httpapi/internal.go#L121

Any ideas whether that's safe to remove?

**Comment by keegancsmith** [comment]
> Any ideas whether that's safe to remove?

Go for it, that command hasn't existed for years :)

**Comment by eseliger** [comment]
I think `internal.phabricator.repo.create` is actually used on instances that have a phab code host connected, but dotcom doesn't so it appears in this list.

**Comment by ryanslade** [comment]
> I think `internal.phabricator.repo.create` is actually used on instances that have a phab code host connected, but dotcom doesn't so it appears in this list.

Yep, agreed that I'm not comfortable removing that one

**Comment by keegancsmith** [comment]
Agreed, I gave the provision that confirmation by reading code would be required :) I just did that in the phab case and can confirm it is possible to execute that code path. So removed it from the list.

Hopefully when we have been removing the endpoints we have been removing the client code that exists as well and that would tell us if it is actually used.

**Comment by eseliger** [comment]
I tried to clean that up in my PRs, hope I didn't miss anything.

**Comment by keegancsmith** [comment]
I just realised something, the phabricator route exists from the days when repo-updater couldn't access the DB. It now accesses the db a _lot_. So bonus points to someone just deleting the route and replacing it with a simple call to the DB.

**Comment by ryanslade** [comment]
> I just realised something, the phabricator route exists from the days when repo-updater couldn't access the DB. It now accesses the db a _lot_. So bonus points to someone just deleting the route and replacing it with a simple call to the DB.

I'm taking a look at this now
