### ISSUE TITLE
Language extensions are not enabled when specified in site config

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#363]
- **Sourcegraph version:** latest master

#### Steps to reproduce:

1. Start a fresh instance
2. Add `"langservers": [ { "language": "go" } ]` to site config
3. View global settings

#### Expected behavior:

The Go language extension should be enabled.

#### Actual behavior:

The Go language extension is not enabled. The global settings have not been modified.

### Potential solution

Set up a `conf.Watch()` that looks at `langservers` and enables/disables each language extension.

Reported by @ggilmore

**Comment by slimsag** [comment]
SGTM
