### ISSUE TITLE
Investigate adding self-hosted executors to managed instances

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#36301]
#### Context 

Running batch changes server-side is moving to Beta soon.
We'd like managed instances customers to be able to use it, too, provided they host and connect their own executors. later on, we'll host executors ourselves.
- if this is possible, we'll go ahead and move server-side to Beta regardless of the deployment mode, provided customers self-host executors.
- if it's not, we should make sure that SSBC is behind a feature flag for managed instances customers.

#### Problem

Investigate if hooking up self-hosted executors to a managed instance is feasible. If it is, add docs.

**Comment by eseliger** [comment]
Should not be a problem. Self-hosted executors don't differ to those that we deploy for managed instances, with the exception for metrics scraping and auto scaling. Those limitations have been added to the docs.
