### ISSUE TITLE
Instant search

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#3630]
Instant search is where as you type each letter in a search query, it shows the results instantly (without needing to hit enter).

This makes users feel search is faster.

Customers interested:

- https://app.hubspot.com/contacts/2762526/company/547457240 (Livegrep user)
- https://app.hubspot.com/contacts/2762526/company/632191097 (Livegrep user)
- https://app.hubspot.com/contacts/2762526/company/694011992 (Livegrep user, specifically requested instant search in Sourcegraph because it feels faster)

**Comment by nicksnyder** [comment]
I think we would probably want to implement result streaming first.

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by stefanhengl** [comment]
@lguychard Please reopen if you feel instant search is still relevant now that we have streaming.

**Comment by lguychard** [comment]
Streaming is an enabler, not a replacement, for instant search, and dynamic responsiveness of results to user input in the query field might still be desirable.

While there are no plans at this time to implement instant search, and I'm unsure what the priority would be (cc @benvenker), I think we should keep this open for tracking.

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket, please let us know how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
