### ISSUE TITLE
cli: clarify -clean-archives behaviour

### ISSUE THREAD

**Issue by LawnGnome** [sourcegraph/sourcegraph#36304]
From #34943: we suspect that some of the confusion in the original feedback was due to `-clean-archives` only (1) cleaning up archives for repositories that were matched, and (2) when a normal, clean shutdown of `src` occurs.

We should document the behaviour better in the flag help and the docs.

**Comment by chrispine** [comment]
not a lot of work, but also doesn't feel very high priority to me; no strong feelings about this one

**Comment by eseliger** [comment]
P0?
