### ISSUE TITLE
could not open file : I/O error (SQLSTATE 58030)

### ISSUE THREAD

**Issue by hitzhangjie** [sourcegraph/sourcegraph#36316]
- **Sourcegraph version:** 3.40.1
- **Platform information:** macOS Catalina
#### Steps to reproduce:

1. run the docker conatainer sourcegraph/server:3.40.1
2.kill and restart and kill and restart several times.

#### Expected behavior:
the server still runs successfully.

#### Actual behavior:
it shutdown because some errors like 'could not open file \"base/16384/17341\": I/O error (SQLSTATE 58030)"}'.

**Comment by malomarrec** [comment]
Hey @Joelkw, it looks like this issue was created by someone outside Sourcegraph. Assigning you to triage it! Please answer and route to the right team by adding their team label.

**Comment by malomarrec** [comment]
Hey @Joelkw, just a reminder to triage this issue and remove the triage-bot/needs-triage label when you're done!
