### ISSUE TITLE
Support sending a specific list of alerts

### ISSUE THREAD

**Issue by michaellzc** [sourcegraph/sourcegraph#36320]
## Context

Per SOC2 [CI-25](https://github.com/sourcegraph/security-issues/issues/249), DevOps is responsible for tracking and responding application-level performance alerts on managed instances.
Sourcegraph omits a lot of alerts. Unlike dotcom where alerts are routed to the component team, alerts coming from MI are only sent to DevOps. 
MI is not mature enough that DevOps is comfortable of routing all alerts to the component team yet

In order to satisfy the SOC2 requirements and keeping us sane at the same time before MI is at a better stage where we can hand off alert responding duty to component team. We decided to identify selected key metrics and only response to them.

Due to the limitation of our observability stack and its current ownership model, we are unable to only route selected alerts to a specific channel. In other words, you can route all `critical` alerts that are owned by `code-intel` to a specific channel, but you cannot route a specific list of `critical` alerts to a specific channel. The only way to do so is to silence all alerts that we do not care.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/cloud-devops - the "team/devops" label was applied to this issue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @RafLeszczynski - the "team/cloud" label was applied to this issue.
