### ISSUE TITLE
Hovering broken for hidden data series

### ISSUE THREAD

**Issue by unclejustin** [sourcegraph/sourcegraph#36325]
When toggling the visibility of a data series on an insight to "hidden" it's still rendered, just set to opacity 0. Because of this it messes up the "nearest point" hover affect as shown in the video below.

We probably have to actually update the array (which we were trying to avoid) and remove the invisible series.

https://user-images.githubusercontent.com/1855233/171299690-6bef1961-4ab7-40ee-ad15-ac7ab0240264.mov

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by Joelkw** [comment]
Understood, thank you for the update @vovakulikov ! Agree with your assessment – it seems this would worst case be solved if a user refreshed the page?

**Comment by vovakulikov** [comment]
@Joelkw yeah with page refreshing we reset all toggle series state and users will see all series therefore hovering logic will work correctly. The full fix for this problem will be shipped in this PR https://github.com/sourcegraph/sourcegraph/pull/37224
