### ISSUE TITLE
zoekt: incremental indexing: fallback to a full build if the indexoptions changes

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#36332]
In Zoekt, [certain higher level options ](https://github.com/sourcegraph/zoekt/blob/6c563dc28bcad305aecb33fbada2229773ff38ee/build/builder.go#L108-L118)(aside from the list of commits) also influence the contents of a shard. These include whether or not symbols analysis should be performed, the maximum file size of the shard, etc. 

Incremental indexing builds can automatically update commit metadata in older shards. However, if any of these options change - it's likely that we'll need to fall back to a full build and reindex everything in order to have all the data /settings  in the shards be coherent. Incremental indexing should implement this behavior. 

(As an example, what if a repository has symbols disabled, then later enabled? It doesn't make sense for _some_ of the shards to have symbols information, and for others to not. In this scenario, it's easier to reindex everything from scratch so that we can know that _every_ shard has symbols information).

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/search-core - the "team/search-core" label was applied to this issue.

**Comment by ggilmore** [comment]
Fixed via https://github.com/sourcegraph/zoekt/pull/376
