### ISSUE TITLE
Wildcard <Icon /> accessibility, Default `role="img"`

### ISSUE THREAD

**Issue by gitstart-sourcegraph** [sourcegraph/sourcegraph#36338]
## Problem statement
In order to split the Icon accessibility efforts into smaller PRs, we've had to remove the default prop `role="img"` from the wildcard's icon component.

## Success criteria
We now have `img` set as default role, within the wildcards's Icon component.

## Implementation details
1. Make role prop default to `img` within the wildcard component
2. we have ensured to follow this order during migration `<Icon role="img" ... />` i.e use the find and replace tool (on vscode or any other editor), to find every usage instance of `<Icon role="img" ` and replace with `<Icon `

## Time estimate

- Pull requests with ~450 lines changed should take **2 hours** at maximum. Ping the reviewer in the spec pull request if time-consuming changes are required.
- Split the work into multiple pull requests if the total diff is bigger than 450 lines of code.

**Comment by umpox** [comment]
Now finished!
