### ISSUE TITLE
Upgrade search backend

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#36354]
This is a bucket epic tracking work outlined in docs by @camdencheek ([Search backend feature hierarchy](https://docs.google.com/document/d/1P7l-2DMCDZyimjP7wtti_IMLGAOnlDvAUhQELNeZh20/edit#)) and @rvantonder ([Search backend & Compute prospects work Q2 and onward](https://docs.google.com/document/d/1hjHguJovYReCwiuolvLk2d36GZfMl45lTCb77wm-SdY/edit)).

- https://github.com/sourcegraph/sourcegraph/issues/31028
- https://github.com/sourcegraph/sourcegraph/issues/35964

**Comment by camdencheek** [comment]
I don't think this epic is providing any meaningful information at this point, so I'm closing it in favor of the sub-epics.
