### ISSUE TITLE
SSBC QA

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#36364]
Before we enable the feature flag by default, we want to do some QA testing of SSBC.

This should include:

- [x] QAing the visual design and UX of basic workflows
- [x] Dogfooding SSBC internally
  - [x] Everyone on the team should spend 0.5d on this and open tickets
- [x] Validate old workflow continues to work with feature flag on

**Comment by courier-new** [comment]
Visual design and UX issues being audited as part of greater design debt audit [here](https://docs.google.com/spreadsheets/d/1JULmLL5I4J-nLXBCKwDeEsA5lNcAm-DhF3YTFeNLqsQ/edit#gid=573436235). Daniel will be converting them into issues and prioritizing them later this sprint.
