### ISSUE TITLE
Create the ExplicitPermissionsBitbucketProjectWorker boilerplate

### ISSUE THREAD

**Issue by sashaostrikov** [sourcegraph/sourcegraph#36370]
[Follow the worker documentation](https://docs.sourcegraph.com/dev/background-information/workers) to implement all the necessary code to link the workerutil package to the [explicit_permissions_bitbucket_projects_jobs](https://github.com/sourcegraph/sourcegraph/issues/36443) table.

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.
