### ISSUE TITLE
Remove smart-casing behavior from search

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#3638]
Smart casing (see `case:` on https://docs.sourcegraph.com/user/search/queries) is the search behavior where the search is case-sensitive if the query text contains an uppercase letter, and case-insensitive otherwise.

While the idea is potentially good, it needs more UI work to be intuitive. The UI needs to explicitly communicate that smart-casing behavior is active when it is. Otherwise, users who enter a query with an uppercase letter are confused that Sourcegraph is omitting lowercase results, and that is the most critical kind of problem/confusion we want to avoid.

We should remove this feature entirely, including from the doc page (which was in a separate commit), and include the removal in the next patch release.

Reported as confusing by https://app.hubspot.com/contacts/2762526/company/407948923 and other incoming individual user feedback.

**Comment by attfarhan** [comment]
Reverted smart-casing in patch release 3.3.5.
