### ISSUE TITLE
EPIC: Incremental Indexing

### ISSUE THREAD

**Issue by jjeffwarner** [sourcegraph/sourcegraph#36415]
Implement incremental indexing to improve indexing performance for large monorepos.

### Stories
1. #29731
2. #29731

**Comment by malomarrec** [comment]
Hey @jjeffwarner, this issue didn't have a team label. Given you created it, I assigned you and added your team label. Feel free to unassign yourself. If this is not the right label, can you make sure to add the right one?

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket, please let us know how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
