### ISSUE TITLE
Use compute to show suggested repos to users in homepage panel

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#36424]
In the homepage panel for repos, show suggested repos to user if the panel would otherwise be empty (the user doesn't have any repos in their search history).

A compute query that could be used for this is 
`content:output((.|\n)* -> $repo) author:"[USER EMAIL HERE]" type:commit after:"1 year ago" count:all`

Think about how you would handle edge cases (eg. user doesn't have any repos, or the search has an error).

Any work done here should be under a feature flag and not show if the feature flag is disabled. To use the feature flag, there is a hook: `const homePanelsComputeSuggestionsEnabled = useExperimentalFeatures(features => features.homePanelsComputeSuggestions)`

[`RepositoriesPanel.tsx`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@jp/refactorcodeexcerpt/-/blob/client/web/src/search/panels/RepositoriesPanel.tsx?L1%3A1=) is a good place to start working on this.

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.
