### ISSUE TITLE
Permissions: Avoid resyncing failed user permissions forever

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#36444]
When we fail to sync user permissions we don't update the `updated_at` or `synced_at` columns
in the `user_permissions` table. This means that the same users will stay at the front of the queue
and will keep being picked up for sync. Instead, we should do something [similar](https://github.com/sourcegraph/sourcegraph/blob/9a4140334c2e22ee24005baf263e817f1f3e2db8/enterprise/internal/database/perms_store.go#L104) to what we do for
repo permissions and "touch" the row so that it goes to the back of the queue.

Seen in [this issue](https://github.com/sourcegraph/customer/issues/993)

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam-and-admin-experience - the "team/iam-admin-experience" label was applied to this issue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.

**Comment by thenamankumar** [comment]
@ryanslade I think it was solved with commit: https://github.com/sourcegraph/sourcegraph/commit/31ed25c39c89dc9339f955ab6cdc9687e50aea9c

**Comment by ryanslade** [comment]
Yep, you're right. I'll close this.
