### ISSUE TITLE
When command palette is empty, UI is confusing

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#3644]
This UI doesn't tell me what Sourcegraph actions are, how I can get them, or why the list is empty and that is confusing to me:

![image](https://user-images.githubusercontent.com/3173176/56830980-bc5b8c00-681c-11e9-8139-6f02d2258816.png)

Ideally it should tell me this information and that actions are contributed by extensions and where I can install those.

**Comment by christinaforney** [comment]
Duplicates #1841 closing to track in that issue.
