### ISSUE TITLE
Create the explicit_permissions_bitbucket_projects_jobs table

### ISSUE THREAD

**Issue by asdine** [sourcegraph/sourcegraph#36443]
Create a table that implements the worker package requirements (see [Worker documentation](https://docs.sourcegraph.com/dev/background-information/workers)).

Additional columns:
- project key
- permissions (json should be fine)
- unrestricted
- code host id

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.
