### ISSUE TITLE
Create a database method that lists the Bitbucket worker jobs

### ISSUE THREAD

**Issue by asdine** [sourcegraph/sourcegraph#36453]
Create a database method that lists the Bitbucket worker jobs.
It takes an optional parameter to filter the jobs by:

- project keys: only return jobs that are related to one of the given projects. By default, returns all jobs
- status : only return jobs that have the given status. By default, returns all jobs

It takes a mandatory parameter, `count` which limits the number of returned tasks.
By default, it returns the last 100 jobs.

The list of jobs must be ordered by `queued_at` DESC.

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.
