### ISSUE TITLE
Create a database method to apply a list of permissions to a list of repos

### ISSUE THREAD

**Issue by asdine** [sourcegraph/sourcegraph#36450]
This method receives a list of repos and a list of permissions that need to be applied to both the `user_permissions` table and `repo_permissions` table.

- [x] This method must completely replace old permissions with the new ones.
- [x] It doesn't need to be atomic (i.e. can use batches in different transactions without the need to rollback everything)
- [x] It must be idempotent (i.e. the workerutil package might call this method multiple times in case of errors)

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.
