### ISSUE TITLE
Regression? User settings editor is broken / only has few pixels height

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#3645]
I cannot edit user settings on my v3.2.4 and v3.3.2 (latest) instances because the editor is only a few pixels in height:

![image](https://user-images.githubusercontent.com/3173176/56831535-2fb1cd80-681e-11e9-89e7-5831a9fca843.png)

- This also occurs on the Global Settings page, but not the site config page.
- This occurs in both latest Firefox and Chrome versions.
- It occurs for all users, regardless of what their settings are.
- There are no browser console errors, and the GraphQL request to fetch settings worked without error.

Here is how the DOM structure looks:

![image](https://user-images.githubusercontent.com/3173176/56832017-91266c00-681f-11e9-993e-bfdde5e980bd.png)

I cannot reproduce this on Sourcegraph.com however.

There are no page modifications on my instance that would cause this.

Also observed at https://app.hubspot.com/contacts/2762526/company/407948923

**Comment by ggilmore** [comment]
@slimsag It works for me on https://sourcegraph.sgdev.org

**Comment by slimsag** [comment]
Yeah, also works on sourcegraph.com just not on customer deployments it seems. Maybe it's recently fixed and thus working on sgdev and .com?

We need to check if this is broken in latest released version

**Comment by felixfbecker** [comment]
Possibly related https://github.com/sourcegraph/sourcegraph/pull/2088 @sqs

**Comment by sqs** [comment]
Looking into this now

**Comment by sqs** [comment]
Trying to repro...

## sourcegraph/server:3.3.2 (works)

![image](https://user-images.githubusercontent.com/1976/56961107-b65cf800-6b07-11e9-98f3-a5a24d956000.png)
![image](https://user-images.githubusercontent.com/1976/56961120-bd840600-6b07-11e9-9ba8-3b63cfd10dde.png)

## sourcegraph/server:3.3.5 (works)

![image](https://user-images.githubusercontent.com/1976/56961061-90375800-6b07-11e9-8d26-363ea505e0fc.png)
![image](https://user-images.githubusercontent.com/1976/56961070-97f6fc80-6b07-11e9-8df9-40e58a5fb4bd.png)

**Comment by ggilmore** [comment]
I have just seen this in 3.3.6 @slimsag

**Comment by ggilmore** [comment]
https://github.com/sourcegraph/sourcegraph/blob/fb236dd863a56e0d297b309dfb91d1368bf56c90/web/src/settings/SettingsFile.scss#L5

Manually turning off this flex property seems to fix it

**Comment by slimsag** [comment]
@sqs I can still reproduce this on a v3.2.4 customer instance https://app.hubspot.com/contacts/2762526/company/407948923 

I'm not running the 3.3.2 instance anymore. Both are deploy-sourcegraph-docker instances. 

Chrome Version 74.0.3729.108 (Official Build) (64-bit)

**Comment by sqs** [comment]
@felixfbecker Can you please look into this? AFAICT in https://github.com/sourcegraph/sourcegraph/issues/3645#issuecomment-487930443 this is not related to #2088 and my recent change, and I am not able to repro.
