### ISSUE TITLE
Code Insights: show only active data series in the tooltip

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#36463]
Connected to #35771

As per @vovakulikov's [comment](https://github.com/sourcegraph/sourcegraph/pull/35771#issuecomment-1136762777) - when user toggles on and off the data series, only active data series should be shown in the tooltip.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
