### ISSUE TITLE
Code Insights: add hover state to active data series and key items

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#36462]
**Description**
Connected to #35771

As per design - when user hovers on an active [data series](https://www.figma.com/file/fWW7rO9nUVZJEqUZXTMxcX/Click-to-turn-on%2Foff-a-line-series-%2329958-%5Bready-for-dev%5D?node-id=1617%3A162) or on [key item](https://www.figma.com/file/fWW7rO9nUVZJEqUZXTMxcX/Click-to-turn-on%2Foff-a-line-series-%2329958-%5Bready-for-dev%5D?node-id=1614%3A2614) the line should be highlighted and brought to the top (changed z-index), other lines should be faded out.

@coury-clark's [loom](https://www.loom.com/share/4a2d407e0c1c4c188c0447d2f0d2b011) shows the correct behaviour (time: 1:55)

[Slack thread](https://sourcegraph.slack.com/archives/C014ZCKMCAV/p1653670217431089) for more context.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by unclejustin** [comment]
@AlicjaSuska can you confirm the following assumptions for me?

Given three series A, B & C.

Scenario 1: No series selected, no series hovered

A, B & C: Rendered full color.

Scenario 2: No series selected, series A hovered

A: Rendered full color.
B & C: Rendered dimmed.

Scenario 3: Series A selected, no series hovered

A: Rendered full color.
B & C: Hidden.

Scenario 4: Series A selected, Series A hovered

A: Rendered full color.
B & C: Hidden.

Scenario 5: Series A selected, Series B hovered

A: Rendered full color.
B: Rendered dimmed.
C: Hidden.

**Comment by AlicjaSuska** [comment]
@unclejustin thank you for those scenarios. All looks correct.

Just for clarification:
- 'hovered' on non-hidden series means that hovering either a line or a key item
- 'hovered' on the hidden series (scenario 5) means that hover on a key item (since the line is not visible)
