### ISSUE TITLE
JetBrains: Hiding the popup the way we do it now doesn’t work well with some themes

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#36479]
## Context

We keep our popup open in the background (we just hide it) when the user “closes” it.
We need this behavior because the JCEF browser has glitches with off-screen rendering on Mac, and we can’t reliably close and reopen it.

## Problem

Some themes define a gray overlay over the whole editor when a popover is opened.
Since we keep our popover alive, it does not go away when we press Escape.

The IDE looks faded, like this:

![image](https://user-images.githubusercontent.com/2552265/171651791-fe213d98-3c8f-45d5-9c80-f8cebebbe363.png)

This can be reproduced with the [Material UI theme](https://plugins.jetbrains.com/plugin/8006-material-theme-ui)

## Solution ideas

- Figure out what aspect of the popup these themes watch, and try to imitate it being closed.
- Close the popup, and “save” the JCEF browser in some other, visible area of the IDE by making it 1x1px and putting it somewhere
- Think about more solutions? :)

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by philipp-spiess** [comment]
I DM'd the author of the material theme. There are similar issues with other plugins as well though: https://github.com/mallowigi/material-theme-issues/issues/26

**Comment by philipp-spiess** [comment]
Re-opening because we have to revert: https://github.com/sourcegraph/sourcegraph/pull/36738

**Comment by philipp-spiess** [comment]
Started a discussion with the material UI author: https://github.com/mallowigi/material-theme-issues/issues/179
