### ISSUE TITLE
Remove container around alert message

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#36505]
Code intel settings utilize an unnecessary container around the flash message. 

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/539268/171727234-d81cacc2-66bd-434d-8d67-e4b8dfaadb6a.png">

Example of an alert used properly over the full background above a container:
<img width="899" alt="image" src="https://user-images.githubusercontent.com/539268/171727576-cd67789b-61f4-4ea3-ae10-3ff049e51f2d.png">

**Comment by efritz** [comment]
Fixed by #39844.
