### ISSUE TITLE
Admin experience - repository settings page

### ISSUE THREAD

**Issue by eugeniaft** [sourcegraph/sourcegraph#36506]
## Problem to solve

The repository administrator indexing site is limited in terms of relevant information and actionability. The current process to understand for instance where in the queue a repository is or how long it has been in the queue requires workarounds involving inspecting zoekt-indexserver pods. Moreover, there is currently no mechanism to allow admins to trigger an index.

## Measure of success

TBD

## Solution summary

- Adding observability and actionability to repository admin site

## Delivery plan

- [ ] [#36509](https://github.com/sourcegraph/sourcegraph/issues/36509)

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/search-core - the "team/search-core" label was applied to this issue.

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket, please let us know how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
