### ISSUE TITLE
insights: spike on commit/diff timeouts

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#36503]
Once commit/diff timeout config options are available and the 10000-repo limit is removed, we should see if the current state solves our needs or we should reconfigure the timeout to better enable diff click on points of data.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by peterguy** [comment]
closed by #61953
