### ISSUE TITLE
EPIC: Admin experience improvements

### ISSUE THREAD

**Issue by eugeniaft** [sourcegraph/sourcegraph#36509]
Tracking issues related to adding observability and actionability to repository index settings page
#### Stories
1. #37051

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/search-core - the "team/search-core" label was applied to this issue.

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket, please let us know how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket, please let us know how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
