### ISSUE TITLE
insights: remove insights database from single container

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#36515]
The code insights database was added to the single container deployment with the intention of only being active in integration tests. Somehow for some customer installations the migrator and database initializers are stuck trying to start the code insights database, and they are unable to upgrade. https://github.com/sourcegraph/customer/issues/991

For now, we should just revert the changes that added code insights database to the single container image.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
