### ISSUE TITLE
Verify (and fix) search onboarding tour

### ISSUE THREAD

**Issue by fkling** [sourcegraph/sourcegraph#36525]
The search onboarding popover wasn't visible in a Percy screenshot in  https://github.com/sourcegraph/sourcegraph/pull/36044, which seems to indicate that there issues with the integration of the tour and CodeMirror.

`search-onboarding.test.ts` should be adapted once #36044 was merged and any issues surfaced by this should be fixed.

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.
