### ISSUE TITLE
SSBC in orgs

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#36536]
Make sure everything works on an org-level as well. Currently, I think the permissions checks don't do the org part.
It's possible one can't spawn an execution in an org namespace.

**Comment by courier-new** [comment]
As part of this PR, revert the changes from https://github.com/sourcegraph/sourcegraph/pull/37187 to restore the namespace selector.

**Comment by chrispine** [comment]
Looks like no customers have run into this yet? If not, I'm okay with Backlog until we hear something about it. (Unless someone thinks this is very likely to come up soon and cause us problems.)

**Comment by eseliger** [comment]
We told some customers to use orgs, because that's how they retain their batch changes when someone leaves the company, not doing it probably means that those customers would not use SSBC for anything serious until we support it. That said, it hasn't come up, so happy to delay it a bit further (but maybe not until someone actively mentions it?)

**Comment by LawnGnome** [comment]
If we didn't have giant whacks of library, compute, and 4.0 work looming I'd probably argue for P1-2, but I think this has to be backlog for now.

**Comment by eseliger** [comment]
Since the above comment isn't 100% true anymore and I think this is a big step towards feature parity, P1?

**Comment by chrispine** [comment]
pre-req for private BCs

**Comment by courier-new** [comment]
https://github.com/sourcegraph/sourcegraph/issues/36021
