### ISSUE TITLE
JetBrains: Document auth and other settings better

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#36538]
The auth process is done (via manually copying the access token to the plugin settings) but underdocumented.

Some of the other settings are also non-trivial, some explaining texts would be nice there, too.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by philipp-spiess** [comment]
We'll look into [#36783](https://github.com/sourcegraph/sourcegraph/issues/36783) instead.
