### ISSUE TITLE
Files sidebar color regression

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#36551]
### Issue type

Bug fix

### Problem description

The files sidebar collapse button should be an icon color instead of the the link color. 

![image](https://user-images.githubusercontent.com/43555476/171872287-4bb64e10-023a-47e6-b218-82028ce9f1c0.png)

### Context

See Slack discussion for [context](https://sourcegraph.slack.com/archives/C01LTKUHRL3/p1654179499719959). 

### Assigning labels

- [ ] If this issue will require input from designers in order to complete, please assign the label `needs-design`.

**Comment by oleggromov** [comment]
Merged the PR.
