### ISSUE TITLE
Documentation for `repositoryQuery` in GitHub default configuration is wrong

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#3656]
The current `defaultConfig` for GitHub contains this documentation and default value for `repositoryQuery`:

https://github.com/sourcegraph/sourcegraph/blob/5632b59b90bd7de7430ca91d0de7e9ca0ea33423/web/src/site-admin/externalServices.tsx#L197-L200

The problem is that the documentation (`An array of strings specifying [...]`) describes the `repos` attribute documented here: https://docs.sourcegraph.com/admin/external_service/github#configuration

If you follow the documentation (as I did) and put in, for example, `["sourcegraph/sourcegraph"]` you end up with something completely different than expected.

This default configuration is the result of multiple commits. https://github.com/sourcegraph/sourcegraph/commit/da3743ece358fbe6709f07e95d5fd97bd554e047 by @tsenart and https://github.com/sourcegraph/sourcegraph/commit/d2b0714b293d0e916dd7ae0bb06f8dc59d1d606e by @sqs. The last commit that touched this part and removed the `repos` attribute from the default configuration is [this one](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/67264581ebe82d22d0cce169207004518087ea1e) by @tsenart.

What are your opinions on this? I'm not sure I get all of the reasons for the changes and why things have been added/removed.

But since the default configuration is rather unhelpful (documentation is misleading and you don't have any examples included) I think we now have two options:

1. Change the documentation to correctly describe `repositoryQuery`
2. Re-add `repos` so users know how to add single repos to the configuration

Opinions? :)

**Comment by tsenart** [comment]
From the documentation:

```
// An array of strings specifying which GitHub or GitHub Enterprise repositories to mirror on Sourcegraph. The valid values are:
//
// - `public` mirrors all public repositories for GitHub Enterprise and is the equivalent of `none` for GitHub
//
// - `affiliated` mirrors all repositories affiliated with the configured token's user:
// 	- Private repositories with read access
// 	- Public repositories owned by the user or their orgs
// 	- Public repositories with write access
//
// - `none` mirrors no repositories (except those specified in the `repos` configuration property or added manually)
//
// - All other values are executed as a GitHub advanced repository search as described at https://github.com/search/advanced. Example: to sync all repositories from the "sourcegraph" organization including forks the query would be "org:sourcegraph fork:true".
//
// If multiple values are provided, their results are unioned.
//
// If you need to narrow the set of mirrored repositories further (and don't want to enumerate it with a list or query set as above), create a new bot/machine user on GitHub or GitHub Enterprise that is only affiliated with the desired repositories.
"repositoryQuery": [
	"none"
],
```

How did you come to this conclusion? 

> The problem is that the documentation (An array of strings specifying [...]) describes the repos attribute documented here: https://docs.sourcegraph.com/admin/external_service/github#configuration

**Comment by mrnugget** [comment]
> How did you come to this conclusion?

Looking at it now again: I have no idea! 😉 Sorry about that, it seems like I misread something and then jumped to the wrong line in the documentation and ultimately to the wrong conclusion.

That being said: in the context of GitHub and repositories the sentence `An array of strings specifying which GitHub or GitHub Enterprise repositories [...]` immediately made me think of `:owner/:repository`. A commented-out example would have avoided that. Even `none` as the default  value would probably have stopped me from putting `["sourcegraph/sourcegraph"]` in there.

What do you think about adding something like `"org:sourcegraph"` as a commented out default value?

```typescript
"repositoryQuery": [
  // "org:sourcegraph"
]
```

**Comment by tsenart** [comment]
> What do you think about adding something like "org:sourcegraph" as a commented out default value?

That sounds good to me.
