### ISSUE TITLE
Code Insights: Sort and limit filters should use useForm API

### ISSUE THREAD

**Issue by unclejustin** [sourcegraph/sourcegraph#36589]
Related to https://github.com/sourcegraph/sourcegraph/issues/36286

In the previous issue, we addressed the customer-facing differences. This one is to clean up the way Sort & Limit filters function. Right now they use their own state management and separate function calls. This creates some extra work and props.

We want to update this code to use the useForm API like the rest of the filters do.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
