### ISSUE TITLE
Code Insights Drilldown improvements

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#36591]
## Problem to solve

Code insights is a powerful tool that turns your codebase into a database, allowing you to explore trends, analyses, and current state. But the user flow to go back and forth between the graph charts and search results is lacking. Right now, you can jump to a diff search to show you the individual diff search results that contributed to an increase/decrease in a measure, but you can't answer questions like: 

- Why is there such a significant dip at the end – which repositories contribute to this significant change?
- How do I tell when a specific series started to appear in the results?
- Which repositories are not changing?
- How do I tell which repositories contributed to the first matches of a particular series?
- What was the current state of the codebase in the past – where did these results come from? (A revision search, not a diff search between two datapoints). 

## Measure of success

Primary/quantitative: we will track "drilldown interations" via pings on the new features. The number of clicks/hovers and drilldown expands on individual graphs.

Secondary/qualitative: we have early signal that tying code insights to search results more closely is a major feature differentiator compared to in-house tools or custom scripts, and we'll continue to watch for further statements this is the case. 

## Solution summary

We will make it easier to answer the above questions in as few clicks/interactions as possible. 

[RFC 561 has some early thoughts](https://docs.google.com/document/d/1kgBu3aWy0XMJYjW0lwRTmVm37fwbqU-EMwIzfUWtYHw/edit#). 

Artifacts:
- [RFC 561](https://docs.google.com/document/d/1kgBu3aWy0XMJYjW0lwRTmVm37fwbqU-EMwIzfUWtYHw/edit#)

## What specific customers are we iterating on the problem and solution with?

- https://github.com/sourcegraph/accounts/issues/551
- https://github.com/sourcegraph/accounts/issues/8329
- https://github.com/sourcegraph/accounts/issues/6312
- https://github.com/sourcegraph/accounts/issues/8375

## Impact on use cases

This enables all 5 use cases (because it applies to all code insight jobs to be done, letting you answer more specific questions like those above), but especially code health, code security, incident response, and code reuse.  

For code reuse, this better enables insights to show you where and how people are reusing aspects of code. 
For code health, this lets you find and follow up with specific groups/repos/owners who are making progress or falling behind on a migration. 
For code security and incident response, this gives you at-a-glance better breakdown view of where vulnerabilities or incidents may be present in your code. 
For onboarding devs, this helps you find places your onboarding tooling may be missing or not maintained (docs, readmes). 

## Delivery plan

- Late Q2 / early Q3 – engineering / design collaboration 
- Q3 - prototype and deliver with above customers

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by Joelkw** [comment]
whoops, duplicate of #30821, closing and updated that one instead.
