### ISSUE TITLE
Repo drilldown input is no longer monospace font

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#36595]
<img width="562" alt="image" src="https://user-images.githubusercontent.com/10532611/171963735-f92b4955-e89a-4e7c-8d4e-822c05b25db6.png">

This makes it look inconsistent with the search bar (which is the equivalence that input is going for, using the `repo:` prefix) and also inconsistent with the search context filter, which is monospace:

<img width="551" alt="image" src="https://user-images.githubusercontent.com/10532611/171963803-ad2bd2d6-e9ca-4a32-b92a-7b7535070e6c.png">

Are those two inputs not reusing the same component?

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by vovakulikov** [comment]
@felixfbecker Those two are the same component but we just failed with styles there, we specified them (monospace font) only in the search context section but not in the shared component. 

I will do a quick fix there, thanks for noticing and filling the issue.
