### ISSUE TITLE
Non-human-readable "Implementations" tab error messages

### ISSUE THREAD

**Issue by amandanagai** [sourcegraph/sourcegraph#366]
- **Sourcegraph version:**  see below
- **Platform information:**  Chrome plugin v1.16.2

#### Steps to reproduce:

1. Use plugin to search dgrijalva/jwt-go repo
2. Find ParseFormRequest function
3. Go to implementations tab, check error message

#### Expected behavior:
I expected to see a designed "No results"-type message, if there are no results.

#### Actual behavior:
Something like this shows up:

![screen shot 2018-10-10 at 3 07 10 pm](https://user-images.githubusercontent.com/18563225/46833454-8ca3d580-cd5d-11e8-84f8-f6f222301ce6.png)

![screen shot 2018-10-10 at 3 07 34 pm](https://user-images.githubusercontent.com/18563225/46833467-93324d00-cd5d-11e8-9f9b-8ba187721166.png)

**Comment by sqs** [comment]
Sorry for the slow response here.

@chrismwendt This error message comes from https://sourcegraph.com/github.com/sourcegraph/sourcegraph-extension-api@a438c3f49c52938573613050b507d6b4f78d4346/-/blob/src/protocol/jsonrpc2/connection.ts#L371:42. The full message should just read `Error getting implementations: Method not found: textDocument/implementation`. (Obviously the `Method not found: textDocument/implementations` message is also not very helpful, but that's from the lang server itself, so changing that is out of scope of this issue.)

**Comment by chrismwendt** [comment]
I'm making the error messages less cryptic in https://github.com/sourcegraph/sourcegraph-extension-api/pull/103

Regarding seeing the error in the first place, a better approach would be to not even show the Implementations button in the UI at all https://github.com/sourcegraph/sourcegraph/issues/492
