### ISSUE TITLE
Unable to resend verification email

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#36632]
- **Sourcegraph version:** 3.40.1
- **Platform information:** macOS

#### Steps to reproduce:

1. Add a new email to the user **Settings > Emails** page
2. Without verifying it, click on the "Resend verification email"

#### Expected behavior:

Being able to resend successfully.

#### Actual behavior:

![CleanShot 2022-06-06 at 16 54 29@2x](https://user-images.githubusercontent.com/2946214/172129337-2d6b0c08-7360-4bbf-a5c9-d1611f78ff3f.png)

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam-and-admin-experience - the "team/iam-admin-experience" label was applied to this issue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.
