### ISSUE TITLE
Go code intel: Find References and hover tooltips shows duplicate definitions

### ISSUE THREAD

**Issue by KattMingMing** [sourcegraph/sourcegraph#3665]
When hovering over https://sourcegraph.com/github.com/gorilla/mux@master/-/blob/mux.go#L25:17&tab=references and viewing the references there's several definitions that appear in the hover tooltip.

It looks like there's also several **References: Search mode** buttons in the panel header.

Screenshot below:

<img width="1440" alt="Screenshot 2019-04-29 08 44 43" src="https://user-images.githubusercontent.com/4897310/56908532-5577e600-6a5b-11e9-8e8f-8363c998d92a.png">

**Comment by chrismwendt** [comment]
Can you open the "Ext" menu at the bottom right? I'm curious if there are extra extensions running.

**Comment by chrismwendt** [comment]
Can't repro, but let's reopen this if/when we see it happen again.
