### ISSUE TITLE
insights: Add totalSeriesCount to insights returned via the API

### ISSUE THREAD

**Issue by CristinaBirkel** [sourcegraph/sourcegraph#36660]
Add a `totalSeriesCount` field to the insights returned via the API. Context: https://github.com/sourcegraph/sourcegraph/pull/36376#discussion_r890252309

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
