### ISSUE TITLE
Add e2e test for Phabricator integration

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#3667]
To make sure we can be confident that the Phabricator integration still works before we release.

Should probably spin up a Phabricator instance using our script and then check hovers/buttons appear through Puppeteer.

**Comment by chrismwendt** [comment]
@lguychard submit a draft PR of your branch https://github.com/sourcegraph/sourcegraph/compare/phabricator-e2e and I'll push up some local changes.
