### ISSUE TITLE
Log search arguments on slow CodeIntelSearch queries

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#36688]
Currently the logs on both `frontend` and `symbols` don't have repo info (constructed from memory):

> slow graphql?CodeIntelSearch id=27

We should add more info so we can better determine the cause:

> slow graphql?CodeIntelSearch id=27 repo=github.com/gorilla/mux args=^Route$

**Comment by topebali** [comment]
Hi @chrismwendt 

Nutanix is seeing a spikes in memory utilization in its frontend chart. 
![image](https://user-images.githubusercontent.com/38654489/172662801-fd61ff31-b0e1-4bf9-b3a6-73ae11e981f9.png)

I requested for logs and I see the same errors in the output of `describe` pod

```
Last State:  Terminated
      Reason:    OOMKilled
      Message:   t=2022-06-08T02:55:51+0000 lvl=info msg="endpoints: using rendezvous hashing"
t=2022-06-08T02:55:51+0000 lvl=info msg="Checked current schema state" schema=frontend appliedVersions=[] pendingVersions=[] failedVersions=[]
t=2022-06-08T02:55:51+0000 lvl=info msg="Schema is in the expected state" schema=frontend
Jaeger URL from env  http://jaeger-query:16686/
✱ Sourcegraph is ready at: https://sourcegraph.canaveral-corp.us-west-2.aws/
t=2022-06-08T03:00:48+0000 lvl=warn msg="slow search request"
t=2022-06-08T03:00:52+0000 lvl=eror msg="API HTTP handler error response" method=POST request_uri=/.api/graphql?HighlightedFile status_code=500 error="unexpected EOF" trace= traceID=
t=2022-06-08T03:00:52+0000 lvl=warn msg="unexpected status code" method=POST url=/.api/graphql?HighlightedFile code=500 duration=51.377353ms x_forwarded_for=127.0.0.1 user=6029
t=2022-06-08T03:00:59+0000 lvl=warn msg="slow search request"
t=2022-06-08T03:01:02+0000 lvl=warn msg="slow search request"
t=2022-06-08T03:01:04+0000 lvl=warn msg="slow search request"
t=2022-06-08T03:01:19+0000 lvl=warn msg="slow search request"
t=2022-06-08T03:01:19+0000 lvl=warn msg="slow http request" method=POST url=/.api/graphql?CodeIntelSearch code=200 duration=16.15779419s x_forwarded_for=127.0.0.1 user=6029
t=2022-06-08T03:01:22+0000 lvl=warn msg="slow search request"
t=2022-06-08T03:01:22+0000 lvl=warn msg="slow http request" method=POST url=/.api/graphql?CodeIntelSearch code=200 duration=17.734276507s x_forwarded_for=127.0.0.1 user=6029
t=2022-06-08T03:01:30+0000 lvl=warn msg="slow search request"
t=2022-06-08T03:01:30+0000 lvl=warn msg="slow http request" method=POST url=/.api/graphql?CodeIntelSearch code=200 duration=22.577643532s x_forwarded_for=127.0.0.1 user=6029
t=2022-06-08T03:01:32+0000 lvl=warn msg="slow search request"
t=2022-06-08T03:01:32+0000 lvl=warn msg="slow http request" method=POST url=/.api/graphql?CodeIntelSearch code=200 duration=23.057623069s x_forwarded_for=127.0.0.1 user=6029

      Exit Code:    137
      Started:      Wed, 08 Jun 2022 08:25:51 +0530
      Finished:     Wed, 08 Jun 2022 08:33:24 +0530
      
```
 Requested for chart in the last 24hours:
 
![image](https://user-images.githubusercontent.com/38654489/172663428-00783912-a630-405e-ba12-80f24fd2d42b.png)

Requested for a chart in the last 5mins:
![image](https://user-images.githubusercontent.com/38654489/172663528-27fa1629-5489-44c2-b5e2-5187ae144212.png)

Found out if there are any alerts firing from the frontend:
![image](https://user-images.githubusercontent.com/38654489/172663825-85dda071-b7c7-4010-a9b1-67aa8fccfe84.png)

After looking at the logs and the alerts firing. I think they might be related. I see alot of slow CodeIntelSearch queries from  user=6029  in the logs which coincides with the alerts firing.

I instructed they perform some of the next steps suggested in the [alert mitigation](https://docs.sourcegraph.com/admin/observability/alerts#frontend-99th-percentile-search-codeintel-request-duration)


I think this might be helpful in figuring out an RCA as many of these slow requests are from code intel?
