### ISSUE TITLE
Make search querying experience more predictable

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#36680]
This is a placeholder epic tracking issues that attempt to enhance our UX with some experiences similar to GitHub's new code search.

- https://github.com/sourcegraph/sourcegraph/issues/34394
- https://github.com/sourcegraph/sourcegraph/issues/34395

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.
