### ISSUE TITLE
Disabling CodeCov doesn't disable branch hit information

### ISSUE THREAD

**Issue by ryankscott** [sourcegraph/sourcegraph#36690]
When you toggle the CodeCov extension off, it only toggles off the line decorations, not the "branch hit" information. This is confusing and should disable *all* functionality related to CodeCov

https://sourcegraph.slack.com/archives/C03CSAER9LK/p1654513861496369

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
