### ISSUE TITLE
search: make display limit configurable in site configuration

### ISSUE THREAD

**Issue by stefanhengl** [sourcegraph/sourcegraph#36691]
We hardcode the display limit to 1500. However, users have asked us to make it configurable for customer installations. As long as we make it clear in the documentation that a higher display limit may lead to a worse performance in the browser we should allow customers to change the default.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/search-core - the "team/search-core" label was applied to this issue.

**Comment by namit-chandwani** [comment]
Hey @stefanhengl, I've setup the sourcegraph repo locally on my system and would like to get started with some beginner issue.

Can you please assign this issue to me?

**Comment by namit-chandwani** [comment]
@stefanhengl Yes, I've already brought Sourcegraph up locally on my machine after going through the docs.

I was working on another issue till now: https://github.com/sourcegraph/sourcegraph/issues/38348. 
Now that I've already raised a PR for that issue, will start working on this current one :)

**Comment by namit-chandwani** [comment]
Hey @stefanhengl, I went through the issue description, documentation and the codebase and understood the following things:


|  | Display limit | Results fetched  | Results displayed |
|--|--|--|--|
| Existing Behaviour | = 1500 | = Count search filter value | = Minimum(Count filter value, Actual result count) |
| Desired Behaviour | = Count search filter value | = Count search filter value | = Minimum(Count search filter value, Actual result count) |

<br>

Now there are 2 options that I can think of:
- Create a new search filter to capture the display limit from the users
- Simply directly use the count search filter value itself as the new display limit as stated above in the table

<br>

What do you suggest as our next course of action?
Additionally, are there any other alternatives we should consider?

**Comment by namit-chandwani** [comment]
Hi @stefanhengl, I've created a PR which can close this issue.
Have tested the changes locally as well with the screen recording of the same included in the PR description.

Request you to review the PRs whenever free

- PR Links:
	- Code changes: https://github.com/sourcegraph/sourcegraph/pull/60761
	- Documentation updation: https://github.com/sourcegraph/docs/pull/114

TIA
