### ISSUE TITLE
"Syntax highlighting this file took too long."

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#367]
@chrismwendt encountered this error here:

https://sourcegraph.com/github.com/sourcegraph/sourcegraph-extension-api@01e628bfdbd18578a6e19e8c11c9b649b266c86e/-/blob/src/client/context/expr/evaluator.ts#L18:12

![image](https://user-images.githubusercontent.com/3173176/46833704-38e5bc00-cd5e-11e8-99a3-362a0f73c2c1.png)

If you see this error, please paste a link to the file you saw it on here.

**Comment by slimsag** [comment]
@chrismwendt are you still seeing this?

**Comment by chrismwendt** [comment]
Nope, I'm guessing this was a transient issue.

**Comment by li-zeyuan** [comment]
> o the file you saw it on he

https://sourcegraph.com/github.com/jiechud/taro-mall@master/-/blob/src/pages/auth/login/login.jsx
https://sourcegraph.com/github.com/jiechud/taro-mall@master/-/blob/src/pages/index/index.jsx
I see the same error.
