### ISSUE TITLE
JetBrains: Set up a Windows test environment on GCP

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#36705]
Clue: we don't need to set up a whole build environment, just a process to upload the built versions of the plugin.

Include dev docs on how to use it.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by philipp-spiess** [comment]
This works great for me! 🎉
