### ISSUE TITLE
JetBrains: Log errors through Sentry

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#36709]
We'll probably need it on both the Java and JS sides:
 - on the JS side, it should be straightforward to wire up since we can forward all uncaught errors
 - on the Java side we need a fallback if the web view does not work. We can’t listen for all uncaught errors, but if we add it to a few select places, or create a lightweight error handling abstraction, it should be good.

A good source of inspiration is [PR #1192](https://github.com/sourcegraph/sourcegraph/pull/1192/files).

A few more thoughts on Sentry from Philipp (edited) to David: “Sentry has an API that one can add to the frontend code. They do have a lot of spam protection built-in. We have this configured for our browser extensions. Its main purpose is client-side error logging. On the server, simple deployments usually log errors to a log file but on clients, you usually fly blind, so Sentry helps.”

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by philipp-spiess** [comment]
Looks like we would only be able to capture logs if the plugin is connected to `https://sourcegraph.com` ([see this thread](https://sourcegraph.slack.com/archives/C07KZF47K/p1657114901030069)).

With the decreased focus on dot-com, do we want to close this issue for now @vdavid?

**Comment by vdavid** [comment]
Yup. Thanks, @philipp-spiess!
