### ISSUE TITLE
JetBrains: Style the rest of the window (outside of the JCEF)

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#36704]
- [x] File name between search results and preview
- [x] Loading indication for the preview
- [x] Padding around the elements?

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by vdavid** [comment]
Decision about icons: we'll fork JetBrains' [icons](https://sourcegraph.com/github.com/JetBrains/intellij-community/-/tree/platform/icons/src/actions) ([list](https://jetbrains.design/intellij/resources/icons_list/)) and create React components for them similar to [this one](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/branded/src/components/SourcegraphLogo.tsx).
Apache 2.0 should cover us as long as we keep the comment at the top. (thanks, @philipp-spiess, for thinking together about this!)

**Comment by vdavid** [comment]
Icons that I'll need:
- `AllIcons.Actions.Cancel` for clearing the query
- `AllIcons.General.ArrowDown` for the dropdown
- `AllIcons.Ide.External_link_arrow` for the external link indicator
- `AllIcons.Actions.Search` for the search box

**Comment by vdavid** [comment]
> Loading indication for the preview

@philipp-spiess or @jjinnii do you perhaps remember what we meant by this? I can't see any designs for this or find more info in the [notes of the related meeting](https://docs.google.com/document/d/1ZvsSwc5oPi6Q4YVqy0DUcy-2FCGtswNxk5omxaIBld0/edit#heading=h.mn6ouogwu60q).

> Padding around elements

Just for the record, I think what we meant here was a fix for https://github.com/sourcegraph/sourcegraph/issues/35919 and the very similar window resize issue, by adding a little padding around the web view.

**Comment by philipp-spiess** [comment]
> Loading indication for the preview

I wrote that down but I don't think this was something we discussed prior. I find it strange when I am navigating through search matches and there is a bigger file to download. Right now we just show the previous file until the new one is loaded and when this takes a couple of seconds it feels like there is a bug in the UI when in fact we just still download the file. This might be even more of an issue for users on slow networks.

**Comment by vdavid** [comment]
Cool, thanks for the clarification, I'll create a fix for that.

**Comment by philipp-spiess** [comment]
Reopening this because it doesn't seem like we got design approval so technically this is not fixed yet. :-)

**Comment by vdavid** [comment]
I suggest we add distinct items for each fix that @jjinnii suggests. Having this monolith of an issue was a pain. :/

**Comment by vdavid** [comment]
Added https://github.com/sourcegraph/sourcegraph/issues/37482 for the remaining part of this.

**Comment by jjinnii** [comment]
@vdavid @philipp-spiess Feel free to close out this issue. I'll create a new one with UI review items labeled with priority. 😄
