### ISSUE TITLE
Patch release request to fix GHE OAuth flow

### ISSUE THREAD

**Issue by sashaostrikov** [sourcegraph/sourcegraph#36724]
@sourcegraph/release-guild I am requesting the following commits be included in a patch release. They are already merged into `main`:

- https://github.com/sourcegraph/sourcegraph/commit/b99999b6ec19b84c304cd1e2bee5657bd0213c69 (just look at this perfect palindrome hash :chefskiss:)
- https://github.com/sourcegraph/sourcegraph/commit/95d833e8610d9391c6a08715f7c4f1463f55228b
- https://github.com/sourcegraph/sourcegraph/commit/d50d46406ebca24b47a3d133faa042afdf508ddf

---

The intent of the questions below is to ensure we keep Sourcegraph high quality and [only create patch releases based on a strict criteria.](https://handbook.sourcegraph.com/engineering/releases#patch-releases) If you can answer yes to many or most of these questions, we will be happy to create the patch release.

I have read [when and why we perform patch releases](https://handbook.sourcegraph.com/engineering/releases#patch-releases) and answer the questions as follows:

> Are users/customers actively asking us for these changes and cannot wait until the next full release?

Basically it affects any customer on v3.40+ using GHE OAuth flow.
Affected (potentially) customers can be tracked [here](https://sourcegraph.looker.com/looks/436)
The hottest issue is: https://github.com/sourcegraph/customer/issues/1005
> Are the changes extremely minimal, well-tested, and low risk such that not testing as we do in a full release is OK?

Yes, it is just a revert of a commit updating one dependency (`github.com/dghubble/gologin`), which was tested by multiple @sourcegraph/repo-management developers locally. Reverting the dependency (i.e. downgrading it) doesn't brake anything because no newer features of a most recent version were used after the version was originally bumped up.

> Is there some functionality completely broken that warrants redacting the prior release of Sourcegraph and advising users wait for the patch release?

GHE OAuth flow results in errors, so upgrading to this patch version is recommended for all customers using GHE as an OAuth provider. It's worth adding an announcement and sending affected customers emails.

> This will interrupt our regular planned work and release cycle, taking one full working day of our time, and will take up all of our site admin's valuable time by asking them to upgrade or producing noise for them if they don't need to upgrade.
>
> Do you believe the changes are important enough to warrant this?

yes

> Patch releases are a signal we can do something better to improve the quality of Sourcegraph. Have you already scheduled a call (or created a google doc) to perform a [retrospective](https://about.sourcegraph.com/retrospectives) and identify ways we can improve?

not yet

---

**For the [Release Captain]** - after reviewing this request:

- [x] **Comment on this issue** with a decision regarding the request.
- [x] If you are a first-time [Release Captain], please review the high-level overview of the [patch release process].
- [x] If approved, **add it to a patch release**:
  - If there is [already an upcoming patch release](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+), add the listed commits alongside a link to this issue
  - If there is no upcoming patch release, create a new one:
    - [x] Update [`dev/release/release-config.jsonc`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/release/release-config.jsonc) and open a PR to `main` to update it
      - [x] Change `upcomingRelease` to the current patch release
      - [x] Change `previousRelease` to the previous patch release version
      - [x] Change `releaseDate` to the current date (time is optional) along with `oneWorkingDayAfterRelease` and `oneWorkingDayBeforeRelease`
      - [x] Change `captainSlackUsername` and `captainGitHubUsername` accordingly
    - [x] `yarn release tracking:issues` 
    - [x] Add the listed commits alongside a link to this issue to the generated [release tracking issue](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+)
- [x] **Comment and close this issue once the relevant commit(s) have been cherry-picked into the release branch**.

[release captain]: https://handbook.sourcegraph.com/engineering/releases#release-captain
[patch release process]: https://handbook.sourcegraph.com/departments/product-engineering/engineering/process/releases#patch-release-process

**Comment by coury-clark** [comment]
FYI there is a second patch request that can ideally be bundled with this when released: https://github.com/sourcegraph/sourcegraph/issues/36746

**Comment by sashaostrikov** [comment]
added 2 commits which fix the build (https://github.com/sourcegraph/sourcegraph/commit/95d833e8610d9391c6a08715f7c4f1463f55228b and https://github.com/sourcegraph/sourcegraph/commit/d50d46406ebca24b47a3d133faa042afdf508ddf)
