### ISSUE TITLE
Replace custom Tooltip component with @reach/tooltip

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#3672]
This looks like a well-made component to me: https://ui.reach.tech/tooltip/
It would save us from spending time on maintaining our own custom Tooltip component.

**Comment by carloslfu** [comment]
I will take this, but I need some feedback before proceeding. Here is my proposal:
- Create a wrapper around the `@reach/tooltip` component that has the same look as the Bootstrap Tooltip including the triangle pointer.
- Refactor all the places where `data-tooltip` is being used, for each file I have to:
  - Explicitly import the `@reach/tooltip` wrapper.
  - Remove the `data-tooltip` prop and wrap the component with the `@reach/tooltip` wrapper, i.e.:
```jsx
<Tooltip label="Save">
  <button>💾</button>
</Tooltip>
```

**Comment by felixfbecker** [comment]
That sounds good to me!

**Comment by jasongornall** [comment]
cc @lrhacker
