### ISSUE TITLE
In VSCode Extension, Open File in Sourcegraph Web shows a 404 if current branch does not exist and defaultBranch is set

### ISSUE THREAD

**Issue by wukkuan** [sourcegraph/sourcegraph#36743]
- **Sourcegraph version:** Sourcegraph.com (affects all versions)
- **Platform information:** macOS, vscode extension 2.2.3

#### Steps to reproduce:

1. Install sourcegraph vscode extension
2. Set `sourcegraph.defaultBranch` to `master` in vscode settings
3. Clone https://github.com/wukkuan/sourcegraph-test
4. Check out a new branch that doesn't exist (name doesn't matter, but let's go with `test`)
5. Open the cloned repository in vscode
6. Open the README.md file
7. Right click in the file, click Open file in sourcegraph web

#### Expected behavior:
The branch does not exist on the remote, so we expect to be directed to the file on sourcegraph.com on the `master` branch. The URL should be similar to: https://sourcegraph.com/github.com/wukkuan/sourcegraph-test@master/-/blob/README.md

#### Actual behavior:
We are directed to the file on sourcegraph.com on the `main` branch (which does not exist) and see a `404` error. The URL is similar to: https://sourcegraph.com/github.com/wukkuan/sourcegraph-test@test/-/blob/README.md

If I remove the `sourcegraph.defaultBranch` setting I am prompted to choose between "main" and cancelling.

**Comment by wukkuan** [comment]
This appears to have been introduced in https://github.com/sourcegraph/sourcegraph/pull/35519. The description in that PR doesn't match what I see, particularly the screenshots. There are no sub-menus on the "Open File in Sourcegraph Web" menu item when right clicking a file.

If we can agree on how this should work, I am willing to work on this. My proposal:
> If `defaultBranch` is set, it should behave the exact same as if it's not set, but if the user clicks on the prompt's "main" option, they should be directed to the user's chosen `defaultBranch`.

**Comment by SamSokolin** [comment]
+1!
