### ISSUE TITLE
Code Insights: Text labels look too big on the dashboard and the standalone page

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#36765]
## Background

If you go to the dashboard page you can see that all insight card titles have H2 styles. This happened because we made a mistake in this PR https://github.com/sourcegraph/sourcegraph/pull/36383. Our assumption was wrong that `<H4 as={H2} />` is the same that `<H2 />`. As a result, we have the following  

<img width="1149" alt="Screenshot 2022-06-08 at 11 10 52" src="https://user-images.githubusercontent.com/18492575/172525124-98115531-9f87-4186-9157-6073cd610d29.png">

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
