### ISSUE TITLE
zoekt: use structured logging for all of zoekt

### ISSUE THREAD

**Issue by gl-srgr** [sourcegraph/sourcegraph#36764]
Message logging is handled via simple logging approach utilizing the builtin log package. Structured JSON logging would provide improved read/parse/query capabilities.

Issue [34951](https://github.com/sourcegraph/sourcegraph/issues/34951) implements this type of logging for a small scope of operations, specifically two indexing related operations conducted by zoekt-sourcegraph-indexserver. This issue's acceptance criteria is to expand the scope of structured logging to all of zoekt.

Current plan (update on 2022 June 15): Repository [sourcegraph/log](https://github.com/sourcegraph/log) was created recently and our first attempt of integrating that structured logging is in PR [374](https://github.com/sourcegraph/zoekt/pull/374). 

Alternatives if sourcegraph/log needs to be removed:

- Instead of `logfmt` for structured logs sourcegraph uses an internal logging standard compliant with OpenTelemtry's model. This [doc](https://docs.sourcegraph.com/admin/observability/logs#opentelemetry) describes the sourcegraph logging configuration. Would compliance with this model be a requirement of zoekt's structured json logging?
- If we do not import a logging solution then we can utilize [zap](https://pkg.go.dev/go.uber.org/zap) loggers in zoekt. For an example of what this would look like see [PR 355](https://github.com/sourcegraph/zoekt/pull/355).
- log15 is another logging package that's utilized by the deprecated sourcegraph [logging](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/logging/main.go?L107)

The aforementioned considerations and other questions/concerns discussed in this slack [thread](https://sourcegraph.slack.com/archives/C023ELQLV7F/p1647435239044179).

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/search-core - the "team/search-core" label was applied to this issue.

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket, please let us know how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
