### ISSUE TITLE
Problem of adding a repo too large for the provisioned resources

### ISSUE THREAD

**Issue by sashaostrikov** [sourcegraph/sourcegraph#36776]
This is related to https://github.com/sourcegraph/customer/issues/1009

Cloning of a big repo can cause an OOM and currently nothing stops gitserver from cloning such repos.

This ticket is created to tackle and eventually solve this issue, any ideas can be added in comments. Current possible solutions include:

- [ ] Make a configurable maximum repository size, which is checked before repo is cloned
- [ ] Create a metric/alert when trying to clone a repo that exceeds this maximum size

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.

**Comment by eseliger** [comment]
It's possible to limit repo size now for select code hosts.
