### ISSUE TITLE
JetBrains: Symbol name is not a unique identifier

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#36797]
Right now for `type:symbol` results we use the symbol name to identify the line. This is, however, not a unique identifier which results in a broken navigation when a file contains the same identifier name multiple times, e.g.:
![Screenshot 2022-06-08 at 16 36 13](https://user-images.githubusercontent.com/458591/172644164-75387c79-0466-4e0a-9251-5dc82331fc5a.png)

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
