### ISSUE TITLE
Repos should be able to be removed more than one at a time

### ISSUE THREAD

**Issue by francisschmaltz** [sourcegraph/sourcegraph#368]
Repos should be able to be removed all-at-once, by group, or by platform.

Example: I removed my GitHub.com token but there is a cache of all repositories I have access too, including ones that weren't cloned. If I want to remove them, I have to do so one at a time.

**Comment by sqs** [comment]
We plan to address this pain with https://github.com/sourcegraph/sourcegraph/issues/914. I am closing this issue in favor of that one, because fixing that one will prevent Sourcegraph from getting into the bad state that motivates this issue.
