### ISSUE TITLE
JetBrains: Tooltip for showing overflowing text itself overflows

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#36813]
This happens because the words are not broken mid-word so long words (e.g. filenames in our path) might cause it to overflow the tooltip container.

You can see this happening in action in the video I posted here: https://github.com/sourcegraph/sourcegraph/pull/36809. [Link to video](https://www.loom.com/share/6ba6f9a04f634ccc8f763b41bf36208a) (see it overflow at 4:11)

**Comment by taras-yemets** [comment]
It seems to be the default `Tooltip` component behavior.

<img width="628" alt="Screenshot 2022-06-17 at 17 23 10" src="https://user-images.githubusercontent.com/25318659/174318733-87d111a4-972b-43b0-9b12-ce4ac041cb00.png">

cc: @philipp-spiess

**Comment by taras-yemets** [comment]
@jasongornall, thank you for looking into this!
Yes, the UX was my primary concern for posting it into the dev-frontend channel.
