### ISSUE TITLE
RFC 696: Implement push metrics

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#36843]
Implements a portion of [RFC 696: Reduced isolation deployments for executor](https://docs.google.com/document/d/16SVTBbuqAc2RizJBZgBRCfv5fsMVhR_a2QrIHnEh5T0).

This should change us scraping metrics from executors directly from Prometheus (which requires burdensome deployment setup) and instead receive periodic heartbeats from the executors and relay metrics from the instance itself.

**Comment by efritz** [comment]
Rough idea of implementation:

1. Accept a new message type from executors that stores (for a short time) metrics payloads in redis
1. Modify executors to send current metrics to the new frontend endpoint
1. Add second metrics endpoint to frontend that relays executor metrics from redis
1. Add new metrics endpoint to Prometheus scrape configuration
1. Have executor scrape node exporter metrics to include resource usage

**Comment by eseliger** [comment]
Done! Rolled out to our instances, ready for 3.43 and cleaned up resources :)
