### ISSUE TITLE
Extensions: improve troubleshooting docs for air gapped instances

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#36851]
Setting up an air-gapped instance is becoming popular among our customers which currently are not covered by our troubleshooting docs.

We should improve our troubleshooting docs to help our user admins understand how extensions work in an air gapped instance and how to set them up for success.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
