### ISSUE TITLE
Double API calls when creating an insight

### ISSUE THREAD

**Issue by unclejustin** [sourcegraph/sourcegraph#36872]
From @coury-clark via Slack

> When I create an insight we have two networks calls back to back:
`FirstStepCreateSearchBasedInsight`
then
`UpdateLineChartSearchInsight`
I suspect there is something wrong causing us to duplicate series when we create (probably the series_id isn’t getting propagated. With JIT insights this has no impact, but now that we backfill this has a real impact and is causing bugs.
There is a [comment](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/enterprise/insights/core/backend/gql-backend/methods/create-insight/create-insight.ts?L67-71) that says this is happening because of missing filters, but that exists in the create [mutation](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/cmd/frontend/graphqlbackend/insights.graphql?L614%3A7-614%3A31=&utm_product_name=GoLand&utm_product_version=GoLand) - is there another reason or has this just not been migrated yet?

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by vovakulikov** [comment]
I think it's because the FE logic had been written before we supported filters in the create insight mutation 

Original issue https://github.com/sourcegraph/sourcegraph/issues/27836
