### ISSUE TITLE
Update series display limit option max to be actual series count

### ISSUE THREAD

**Issue by unclejustin** [sourcegraph/sourcegraph#36873]
NOTE: this requires a change on the backend to return `totalSeries`.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by unclejustin** [comment]
cc @CristinaBirkel this is an issue for the slack conversation we were having about restricting seriesDisplayOptions->limit to whatever the actual series count is.

cc @AlicjaSuska

**Comment by coury-clark** [comment]
@unclejustin I think this is done, can you confirm?

**Comment by leonore** [comment]
closing since we're pretty sure it's done
