### ISSUE TITLE
Basic Protobuf/Thrift/GraphQL/etc. code intel

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#3688]
As a user:

- I would like to be able to hover over a token (service name, type name, or method/field name) in an IDL file (Protobuf, Thrift, or GraphQL) and see "Find references" (more important) and "Go to definition". These should find tokens in files of *all* languages (i.e., in generated code *and* code that uses the generated code), not just in the IDL files.
- (Less important, can be in v1) I would also like to be able to hover over a token in generated code *or* code that uses the generated code and have "Go to definition" or "Find references" include definitions in Protobuf, Thrift, or GraphQL IDL files and other code-genned code.

Related: While #1263, #981, and #669 would be nice, basic (text-heuristic-based) support for these IDL files is better than nothing.

Requested by:

- https://app.hubspot.com/contacts/2762526/company/814799425 said this would be the best "wow" moment when demoing to the team (without us suggesting it)
- https://app.hubspot.com/contacts/2762526/company/547190400 *also* said this woud be a great wow moment when demoing to the team (without us suggesting it)

**Comment by felixfbecker** [comment]
I would use this myself a lot

**Comment by creachadair** [comment]
Now that #206 is live in sourcegraph.com, we have basic code intelligence results for GraphQL schema files (addressing part of #981 as well). You get some cross-language results simply by virtue of the way search works, but the results are neither complete nor comprehensive. 

To give meaningful results we'd need to take account of code generation steps. Thrift and Protobuf have well-established code generators, but I'm not sure how widespread codegen is for GraphQL schemata.

**Comment by christinaforney** [comment]
Request today from https://app.hubspot.com/contacts/2762526/company/768958891 for protobuf support. Would be great to start with a simple solution to add basic code intel (similar to GraphQL above) and syntax highlighting, and can improve as requested.

**Comment by creachadair** [comment]
> Would be great to start with a simple solution to add basic code intel (similar to GraphQL above) and syntax highlighting, and can improve as requested.

As far as I can tell, Sourcegraph already supports [syntax highlighting for protobuf schema files](https://sourcegraph.com/github.com/kythe/kythe/-/blob/kythe/cxx/indexer/proto/testdata/basic/enums.proto).  It looks like universal-ctags already supports Protobuf, and it's enabled by default on our instances, so I think I just have to add an extension.

https://github.com/sourcegraph/sourcegraph-basic-code-intel/pull/241 should help.

**Comment by dadlerj** [comment]
Request from a user at https://app.hubspot.com/contacts/2762526/company/554275594 today for the same

**Comment by dadlerj** [comment]
Requested by https://app.hubspot.com/contacts/2762526/company/451097663 during a 101 training session today

**Comment by macraig** [comment]
Closing to merge with [#981](https://github.com/sourcegraph/sourcegraph/issues/981)
