### ISSUE TITLE
Saved searches cannot be edited or deleted from the homepage

### ISSUE THREAD

**Issue by francisschmaltz** [sourcegraph/sourcegraph#369]
Global saved searches cannot be edited or deleted on the homepage. Trying to edit a saved search duplicates it and trying to delete it does nothing. This can cause an issue if there is an intensive search that is duplicated and using more cycles. 

Workaround: it can still be deleted in the global config file.

![saved-search](https://user-images.githubusercontent.com/11583013/46834350-0f2d9480-cd60-11e8-93a8-4d4eb676c000.gif)

**Comment by attfarhan** [comment]
This isn't a regression, so it is not release blocking. IIRC @slimsag worked on saved searches, so going to assign to him.

**Comment by slimsag** [comment]
I don't know who added those edit/etc buttons on the homepage. AFAIK, usually you can only edit saved searches through the searches page. I bet if you did it there, it would work fine.

**Comment by slimsag** [comment]
Actually, @vanesa this is likely a frontend bug and probably not too difficult to fix. The payoff is rather good for us as well (i.e. having a bug on our search homepage sucks). Would you maybe be interested in taking a try at fixing this?

**Comment by vanesa** [comment]
Fixed with https://github.com/sourcegraph/sourcegraph/pull/614
