### ISSUE TITLE
Research how can we improve "Admin Analytics"

### ISSUE THREAD

**Issue by erzhtor** [sourcegraph/sourcegraph#36910]
Summary message from @a-bergevin from slack channel:

> How do we know it's a problem: customers keep telling us.
> - [This WIP RFC](https://docs.google.com/document/d/1f873V5UiZkpymkYd6UXqtcknriyFyZ7bXex19ce9flY/edit#) is a draft with a lot of collaborators bringing in ideas/comments around this space. You can see there's a lot of feedback/ideas/energy
> - My general discovery notes are in [this document](https://docs.google.com/document/d/1NKZ_jNdMeEk4hbtyBAwl4B1KobZQbccYhaZNCgZUYSk/edit?usp=sharing) for now
> - Ryan's [early stage notes](https://docs.google.com/document/d/1KbJRkbHXzGct2heCa0e8c_bMMd5zdgbvRaubxOuvoTo/edit) from when he was working on discovery here.
> - I'm gathering things in [#admin-analytics](https://sourcegraph.slack.com/archives/C03JNPY7V3L)
> - I will start scheduling customer interviews, pulling what I can find in Product Board and seeing what I can dig up in Chorus
>
> WHAT are we doing?
> - We are building a fixed set of visualizations - **not** a customer data tool where they can built queries/charts.
> - We have some ideas of where to start on visualizations so **Rob wants to start prototyping and get very early stage feedback** (oh yeah, I should mention, found out [@rob](https://sourcegraph.slack.com/team/U012SFU7BNJ) is planning on being involved a bit here from a design perspective so that is really helpful with our design gap. I mentioned your suggestion [@Erzhan Torokulov](https://sourcegraph.slack.com/team/U02AKL4DMP0) that we try to keep a similar look and feel to Code Insights.)
> - After Erzhan and Naman wrap up their existing projects they will start digging in on technical discovery - what data exists, what vizzes could we build, how would they like to build this, what questions do they have for product, etc.
>
> I think that is all I have for now. I will try to check in briefly tomorrow to answer any quick questions, but good luck on this early discovery, looking forward to tackling this with you all when I get back.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @a-bergevin - the "team/growth" label was applied to this issue.
