### ISSUE TITLE
add a way to "retry all failed changesets"

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#36921]

**Comment by eseliger** [comment]
This exists!

**Comment by malomarrec** [comment]
@eseliger Are you sure? (See new title, maybe this was confusing)

**Comment by eseliger** [comment]
Positive 
<img width="755" alt="Screenshot 2022-06-10 at 15 23 57@2x" src="https://user-images.githubusercontent.com/19534377/173074501-21878df0-99cd-4a44-8866-0a9771430c78.png">

**Comment by malomarrec** [comment]
OMG some major feature blindeness opening on my end. Sorry

**Comment by eseliger** [comment]
I also forgot about it :)
