### ISSUE TITLE
SSBC: Hide "Run batch spec" button by default on managed instances

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#36920]
#### Context

Batch Changes is going Beta soon. We don't have the capacity to deploy executors for all managed instances customers. As a result, we don't want to promote running server-side to MIs customers that do not have executors setup.

#### Desired outcome

- By default, the "run batch spec" button is hidden on managed instances that don't have executors setup
- No change for self-hosted customers
- Batch Changes users on MIs that use executors see the run batch changes button
- Cloud team is aware and onboard with the solution we implement

<img width="1056" alt="Screenshot 2022-06-09 at 18 34 54" src="https://user-images.githubusercontent.com/25070988/172898931-bf76bc45-6636-48da-89b2-bf867c340aba.png">

Here is the matrix:

|                 | **Have executors setup**                                  | **Don't have executors setup**                                                |
|-----------------|-----------------------------------------------------------|-------------------------------------------------------------------------------|
| **MI**          | Run batch spec button on top. Download for src-cli below  | Download for src-cli below                                                    |
| **Self-hosted** | Run batch spec button on top.  Download for src-cli below | Download for src-cli on top. Run batch spec below, that opens SSBC info modal |

**Comment by BolajiOlajide** [comment]
Approach recommended by the #cloud-devops team is to create a feature flag and activate it for MIs.

[#37235](https://github.com/sourcegraph/sourcegraph/pull/37235) handles creating the feature flag - #cloud-devops will use the mutation shared to activate for all MIs.

```
mutation createFeatureFlag {
  createFeatureFlag(name: "hide-run-batch-spec-for-mi", value: true) {
    __typename
  }
}```

You can follow [the discussion here](https://sourcegraph.slack.com/archives/C02KX975BDG/p1655241315271259).

**Comment by BolajiOlajide** [comment]
This is tracked [here](https://github.com/sourcegraph/customer/issues/1050)
