### ISSUE TITLE
JetBrains: Make sure our ping logic handle our events well

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#36992]
@philipp-spiess's findings make this a lot easier:

According to [VSCode's RFC](https://docs.google.com/document/d/1fdathYEEOUgyLbnpEKV7g_7qqHfbvftCGVQt_mXyqmI/edit), the payload already has an `IdeKind` field, and we might already have everything we need on the on-prem servers. Ping logic: [Go](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/usagestats/ide_extensions.go) | [Test](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/usagestats/ide_extensions_test.go)

Example record: `(5, 'IDESearchSubmitted', '{"version": "0.0.1", "editor": "jetbrains"}', '', 2, '420657f0-d443-4d16-ac7d-003d8cdc19ac', 'IDEEXTENSION', $1::timestamp - interval '2 months', '{"version": "0.0.1", "editor": "jetbrains"}', '3.36.2')`

We'll need to think through all scenarios, though.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by philipp-spiess** [comment]
Discussion for this is happening here: https://sourcegraph.slack.com/archives/C035WT8V856/p1655135979958679

**Comment by vdavid** [comment]
Based on the discussion, it seems like the answer is yes. The only open question now is whether we can set up a hook for the uninstalls, but that doesn't affect the ping logic, so I suggest we close this. @philipp-spiess WDYT?

**Comment by philipp-spiess** [comment]
> The only open question now is whether we can set up a hook for the uninstalls

I found this in my limited (1min) research but I’m not sure if this works. Will look into it more when implementing it I suppose.

> but that doesn't affect the ping logic, so I suggest we close this. @philipp-spiess WDYT?

💯

**Comment by philipp-spiess** [comment]
Yeah 🤦  https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000156564-Hook-for-plugin-uninstall-process?page=1#community_comment_360000157724
