### ISSUE TITLE
Corrupted repo broke search result

### ISSUE THREAD

**Issue by michaellzc** [sourcegraph/sourcegraph#37029]
Per #INC-115 and https://github.com/sourcegraph/customer/issues/1014

sometime user is unable to see search result but an error message saying `Unable to fetch repo revisions`

## Expected behaviour

Regardless repo is corrupted or not, I still expect to see indexed result

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.

**Comment by michaellzc** [comment]
this is also happening to `demo`

https://sourcegraph.slack.com/archives/CU93UDUBV/p1654858630967749

**Comment by alexAtSourcegraph** [comment]
Dropping screenshot of issue directly into the issue for posterity.

![image (13)](https://user-images.githubusercontent.com/86978415/176281192-96189c8a-698b-4f96-9f0b-ef055d93ce75.png)

**Comment by indradhanush** [comment]
Moving out of support issues list to icebox.
