### ISSUE TITLE
Packages: artifact hosts and package status in the admin view

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#37046]
Packages will be a first-class entity in the system. We currently manage package hosts in the admin via a section called code hosts and packages in the repositories section. 

This will be confusing to admins. As such, we should move the management of package hosts out of repositories and onto their own settings pages. 

However, this is a low-priority and high-effort initiative. To address the issue more cost-effectively, we should rename the code host section to `Code and package hosts` and the repositories section to `Repositories and packages`

![image](https://user-images.githubusercontent.com/539268/173135656-aa332912-be51-40f3-bf39-63b5703054c6.png)

**Comment by Strum355** [comment]
Given the Sourcegraph Packages job fair project, we're thinking of having separate page(s) for package repos after all. This will be to separate the concept of packages from repos in terms of 1) where they are listed, to not clobber the repo listing 2) the operations that can be performed on them (delete package/version, blocklist package/version etc) 3) the information surfaced about them.

For the time being, artifact hosts/package hosts will likely remain alongside other code hosts.

**Comment by umpox** [comment]
Closed through https://github.com/sourcegraph/sourcegraph/issues/47093

Other tasks are covered in other issues. See above comment.
