### ISSUE TITLE
Chrome extension displays underneath GitLab code in MRs

### ISSUE THREAD

**Issue by TheAlmightyBob** [sourcegraph/sourcegraph#37045]
- **Sourcegraph version:**  3.36.3
- **Platform information:**  Chrome 102.0.5005.61, Sourcegraph extension 22.4.7.1712, GitLab Enterprise 14.2.7-ee

I've previously used the Sourcegraph Chrome Extension with GitLab for a couple years, but in recent weeks/months something broke such that it's now displaying the popups _underneath_ the GitLab code in Merge Requests, rendering it quite useless. 😢 

It still works properly when browsing files in GitLab, only Merge Requests (where the extension was most useful!) seem to have the problem.

#### Steps to reproduce:

1. Enable Sourcegraph Chrome Extension
2. Hover over symbols in GitLab

#### Expected behavior:

Tooltip/popup is displayed with Sourcegraph info.

<img width="586" alt="image" src="https://user-images.githubusercontent.com/7707864/175611208-82e93c8a-7e62-4419-9a06-d7fccf548540.png">

#### Actual behavior:

Tooltip/popup is underneath the GitLab UI... which you can see here as it is just barely peeking through in the gap.

<img width="186" alt="image" src="https://user-images.githubusercontent.com/7707864/173128810-ade44b78-a1bd-42c3-aaa1-219963982727.png">

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by taras-yemets** [comment]
Fixed in https://github.com/sourcegraph/sourcegraph/pull/35403.
Included in `v22.7.11.926` Chrome/Firefox release.

**Comment by TheAlmightyBob** [comment]
I noticed that it was working again earlier today! Thanks @taras-yemets and @abeatrix!
