### ISSUE TITLE
Add observability and actionability to repository admin page

### ISSUE THREAD

**Issue by eugeniaft** [sourcegraph/sourcegraph#37051]
Display in repository admin page:
- indexing status of repository
- where in the queue a repository is
- how long it has been in the queue
- time of last indexing job
- files that are not indexed within that repository
- action to manually trigger index of a repo
- option to include a file to index
- option to index additional branches 
- option to alert admin when a repo has not successfully indexed

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/search-core - the "team/search-core" label was applied to this issue.
