### ISSUE TITLE
Code monitoring: GA webhooks (Slack and generic)

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#37052]
Webhooks were enabled as "Beta" in #37037. Eventually, we should GA them. Assigning to @benvenker so he can notify when we're ready to remove the Beta tag. We should also deprecate the feature flag at this point.

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by lguychard** [comment]
Because we don't have data to look into yet, we will not GA these things yet, and will do a beta announcement around "code monitors don't have a repo limit anymore".
