### ISSUE TITLE
Lucky search improvements for MVP

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#37062]
It's now possible to interpret a query in a lot of smart-ish ways. There are two usability issues that stop this from being a first rate feature:

1. Currently we don't track whether a generated search job returns results. Right now though, we return an alert even if the query just ran (and it may return no results). If we can just track this info, we can use it to know whether to display proposed queries that ran and returned results. I have a sense that we can add the bookkeeping to the stream func without _too_ much hassle, but maybe I'm over simplifying.

2. It looks generated jobs continue to run even past the 500 result limit. This shouldn't be happening [and the code exists to return early](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/search/job/jobutil/feeling_lucky_search_job.go?L86-90&subtree=true), but there is probably some bug. 
 
Here is a query that illustrates both of the above issues (the first couple of queries return no results, we shouldn't show them--the last 2 or three return results beyond 500 results, for some reason). Note this was on a local machine and depends on your repos:

![Screen Shot 2022-06-10 at 5 26 03 PM](https://user-images.githubusercontent.com/888624/173165267-d63fc25d-a017-416d-ae85-b28207cbe2e9.png)

A MVP launch will depend on thinking a bit more carefully about deduplication strategies, but that's not really part of this issue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by lguychard** [comment]
@rvantonder are the two usability issues listed above still current (AFAIK at least the first one isn't).

**Comment by rvantonder** [comment]
(1) and (2) are solved. there is a follow issue that we have to run deduplication for every search, which wouldn't be the case for usual searches. i will close this issue because these issues are addressed (and, anyway, the MVP works, but that doesn't mean "ship on by default")
