### ISSUE TITLE
Prototype Pollution in minimist

### ISSUE THREAD

**Issue by gitstart-sourcegraph** [sourcegraph/sourcegraph#37087]
## Description
The latest possible version that can be installed is 0.0.8 because of the following conflicting dependency:
`puppeteer-firefox@0.5.1 requires minimist@0.0.8 via a transitive dependency on mkdirp@0.5.1`

`Minimist <=1.2.5 is vulnerable to Prototype Pollution via file index.js, function setKey() (lines 69-95).`

## Ref
[#35989](https://github.com/sourcegraph/sourcegraph/issues/35989)
[Link to dependabot alert](https://github.com/sourcegraph/sourcegraph/security/dependabot/111)

## Time estimate

- Pull requests with ~450 lines changed should take **4 hours** at maximum. Ping the reviewer in the spec pull request if time-consuming changes are required.
- Split the work into multiple pull requests if the total diff is bigger than 450 lines of code.

**Comment by valerybugakov** [comment]
@gitstart-sourcegraph, we're going to discuss the possibility of dropping the `puppeteer-firefox` dependency to unblock this issue.
