### ISSUE TITLE
Write down plan for closing down dotcom

### ISSUE THREAD

**Issue by ryphil** [sourcegraph/sourcegraph#37080]
Following the shift to focus on Managed instances, Sourcegraph made the hard decision to shut down our multi-tenant Cloud offering (aka dotcom). This decision can be found [here](https://sourcegraph.slack.com/archives/C0EPTDE9L/p1654277506400829) and more discussion [here](https://sourcegraph.slack.com/archives/C03JA8BAM7C/p1654502214881509) in slack.

This task is to document the technical needs listed in [the plan to wind down dotcom](https://docs.google.com/document/d/1owIo8QA_omwnFqSfS5EKyIhd4SpMDdn7cZJrsvgjl-E/edit?usp=sharing).

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam-and-admin-experience - the "team/iam-admin-experience" label was applied to this issue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.
