### ISSUE TITLE
ssbc: Retry failed button is not accessible when preview button is shown

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#37084]
<img width="686" alt="Screenshot 2022-06-13 at 01 31 59@2x" src="https://user-images.githubusercontent.com/19534377/173258074-532cd252-724c-46f4-819c-ec5a8e574ab7.png">

In the place of that button, we have an actions menu that has a retry all failed button. It's hidden post-completion though. We should show that.

**Comment by courier-new** [comment]
I would think this needs design input. Do we show the "Actions" menu *and* the "Preview" button next to each other? It doesn't really make sense to have an actions _menu_ if there's only one action on it for "Retry all". So then do we just show a second button? Or do we move "Preview" to an option on the "Actions" menu? But then that obscures when a preview is ready. Or is there something else we can do?

I vote P2 and adding the `needs-design` label.

**Comment by eseliger** [comment]
This has been mentioned in direct customer feedback (1/2 things we've _ever_ heard so far), so I strongly vote for P0 and getting _anything_ done for this release would show them we listen to feedback!

**Comment by courier-new** [comment]
Created a follow-up issue to explore designs for this: https://github.com/sourcegraph/sourcegraph/issues/37245.
