### ISSUE TITLE
Transite perms syncer to workers

### ISSUE THREAD

**Issue by RafLeszczynski** [sourcegraph/sourcegraph#37097]
As of now, our permissions syncer is operating under [a single thread and resides in repo-updater](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/repo-updater/internal/authz/perms_syncer.go), as the Cloud usage of private repositories grow, the single-thread in-memory stateful model could be a shortcoming to scale up at the time of Small Orgs GA.

Given we have [workers](https://docs.sourcegraph.com/admin/workers) infrastructure and other teams have done migration, we should also make a technical evaluation about migrating the permissions syncer to use the workers.

**Resources**

- [Grafana dashboard for permissions](https://sourcegraph.com/-/debug/grafana/d/repo-updater/repo-updater?orgId=1&from=now-24h&to=now)

**Comment by RafLeszczynski** [comment]
As of now, our permissions syncer is operating under [a single thread and resides in repo-updater](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/repo-updater/internal/authz/perms_syncer.go), as the Cloud usage of private repositories grow, the single-thread in-memory stateful model could be a shortcoming to scale up at the time of Small Orgs GA.

Given we have [workers](https://docs.sourcegraph.com/admin/workers) infrastructure and other teams have done migration, we should also make a technical evaluation about migrating the permissions syncer to use the workers.

**Resources**

- [Grafana dashboard for permissions](https://sourcegraph.com/-/debug/grafana/d/repo-updater/repo-updater?orgId=1&from=now-24h&to=now)

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam-and-admin-experience - the "team/iam-admin-experience" label was applied to this issue.
