### ISSUE TITLE
Decisions/trade-offs we accepted in our development process

### ISSUE THREAD

**Issue by RafLeszczynski** [sourcegraph/sourcegraph#37098]
- Why do we have a single repo for all services?
- Why do we have a distributed monolith?
- How does our continuous deployment model work?
- Why we are using GraphQL API?

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam-and-admin-experience - the "team/iam-admin-experience" label was applied to this issue.

**Comment by ryphil** [comment]
@RafLeszczynski - Shouldn't this be owned by the enablement team? Or why is this on IAM?

**Comment by unknwon** [comment]
> @RafLeszczynski - Shouldn't this be owned by the enablement team? Or why is this on IAM?

@ryphil I think this issue was specifically for just the IAM team.
