### ISSUE TITLE
Make Admin-User page header be sortable

### ISSUE THREAD

**Issue by RafLeszczynski** [sourcegraph/sourcegraph#37096]
Original request: https://sourcegraph.slack.com/archives/C0W2E592M/p1624475505313100

- investigate if the list of users returned by the api is paged then
    - if it’s paged we need to apply sorting on api side and return (this is expensive since it requires both api and ux update)
    - if the api return the entire list apply sorting on client (so only ux is touched)

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam-and-admin-experience - the "team/iam-admin-experience" label was applied to this issue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.

**Comment by ryphil** [comment]
This work is being picked up by the Admin Analytics tiger team. Closing ticket.
