### ISSUE TITLE
Am I debugging an issue on production - where can I find logs, metrics, events, and traces?

### ISSUE THREAD

**Issue by RafLeszczynski** [sourcegraph/sourcegraph#37102]

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.

**Comment by ryphil** [comment]
@RafLeszczynski A few questions:
- is this tied to dotcom? Or MI? 
- Is this meant for the IAM team?
