### ISSUE TITLE
Overview of the DotCom infrastructure setup

### ISSUE THREAD

**Issue by RafLeszczynski** [sourcegraph/sourcegraph#37100]

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam-and-admin-experience - the "team/iam-admin-experience" label was applied to this issue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.

**Comment by ryphil** [comment]
Closing while we focus on Managed Instances.
