### ISSUE TITLE
[Design Debt][SSBC QA] Align Show More at center of the Batch Changes List page

### ISSUE THREAD

**Issue by danielmarquespt** [sourcegraph/sourcegraph#37118]
This should be at the center, closer to the line displaying the number of items in the list

![Image](https://user-images.githubusercontent.com/7814431/173352692-19c9f1ad-4c7b-4ddf-9daa-dfc626aafb41.png)

**Comment by eseliger** [comment]
lol, that was definitely center at some point.

**Comment by courier-new** [comment]
*cough*

https://github.com/sourcegraph/sourcegraph/pull/37189
