### ISSUE TITLE
search: productionize hybrid zoekt+searcher prototype

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#37112]
https://github.com/sourcegraph/sourcegraph/issues/33656 is shipped and running in production. Lets get this over the finish line and have it useable for the next release via a feature flag.

Tasks:
- [x] heuristics for falling back to normal searcher
  - test on old commits to determine thresholds
  - see if we need better caching behaviour by doing repeated searches on somewhat old commits
- [x] A dashboard showing performance and health of this feature
- [x] Observability to follow-up on how this is working in production
- [ ] A way to disable once we default to on
- [x] stream from zoekt
- [x] Lots of manual testing

Next branch cut is likely this week so unsure we will have enough data by then. So aiming to make this easy to opt into for admins.

Parent https://github.com/sourcegraph/sourcegraph/issues/27042

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/search-core - the "team/search-core" label was applied to this issue.

**Comment by keegancsmith** [comment]
This has been done. It will now bake on sourcegraph.com for a month and will be released in 4.3.

**Comment by keegancsmith** [comment]
One last improvement before I think this is production worthy (other than more bake time that is): https://github.com/sourcegraph/zoekt/pull/482
