### ISSUE TITLE
[Design Debt] Improve the "Close" batch change flow

### ISSUE THREAD

**Issue by danielmarquespt** [sourcegraph/sourcegraph#37128]
The way we are doing this today is not optimal. The message displayed tells the user that closing a batch change allows them to preview. This is not standard (closing something to get a preview) and the overall flow of closing a BC needs to be revised and improved wherever possible

![Image](https://user-images.githubusercontent.com/7814431/173356255-05295240-2c5f-43c5-b419-370c323da5c9.png)

Pending on a better design proposal

**Comment by courier-new** [comment]
I 100% agree this is a confusing workflow that needs a better design solution! However, since closing a batch change isn't SSBC-specific, I'd vote to put it in the backlog for now. (I've also removed [SSBC QA] from the title)

**Comment by danielmarquespt** [comment]
Closing this one and centralising this issue on: https://github.com/sourcegraph/sourcegraph/issues/38713
