### ISSUE TITLE
OAuth tokens should be refreshed by a dedicated job

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#37145]
Currently for user OAuth tokens, we refresh them while doing a background permissions sync.

There is chance that before a token is refreshed we perform a *repo* permissions sync at that
moment the token has expired. The user will then not be allowed to see that token

(TODO: Confirm that latest sync wins)

We should instead have a dedicated job that looks at all OAuth tokens an optimistically refreshed them
to ensure they never expire. Initially we can scope this just for GitLab and remove our current implementaion
of `maybeRefreshGitLabOAuthTokenFromAccount`.

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam-and-admin-experience - the "team/iam-admin-experience" label was applied to this issue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.
