### ISSUE TITLE
insights: Commit Indexer returns errors on empty repos

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#37151]
When the insights commit indexer attempts to index commits for empty repos it logs an error 
```
error fetching commits from gitserver repo_id: {REPO_ID}: git command [git log --format=format:%H%x00%aN%x00%aE%x00%at%x00%cN%x00%cE%x00%ct%x00%B%x00%P%x00 --after=2021-06-02T08:22:43Z --date-order] failed (output: \\\"\\\"): exit status 128\"\n","stream":"stderr"
```
This should not be an error and the index metadata can be marked as up to date. In addition the error log causes confusion when attempting to debug other issues.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
