### ISSUE TITLE
Add db startup probes to helm

### ISSUE THREAD

**Issue by caugustus-sourcegraph** [sourcegraph/sourcegraph#37176]
https://github.com/sourcegraph/deploy-sourcegraph/pull/4136, but for helm.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/delivery - the "team/delivery" label was applied to this issue.

**Comment by caugustus-sourcegraph** [comment]
https://github.com/sourcegraph/deploy-sourcegraph-helm/pull/133
