### ISSUE TITLE
insights: build new GraphQL resolver for compute type insight

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#37174]
For the compute insight project we will need a resolver that returns data. We will likely use this as an opportunity to implement and explore some of the ideas presented [here](https://github.com/sourcegraph/sourcegraph/pull/35623#discussion_r895121808).

One point to consider is the migration path and how this new resolver (if a different schema) will behave. Currently _all_ insights are returned by the `insightViews` query. If we want to preserve this semantic we would need to modify the `InsightView` type to support a union of sub-types.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by coury-clark** [comment]
Removing compute insight label since this will end up in a future iteration of compute insights

**Comment by coury-clark** [comment]
Closing since this issue is ambiguously defined
