### ISSUE TITLE
insights: support single time point insights for compute types

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#37175]
With compute types we will want to support behavior that is not a historical reference but instead is a single datum. This time point can be either 
1. current time (updated daily) 
2. a specific point in time

In the first mode, we can use a similar approach to the [current time snapshots used for standard insights](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/insights/background/insight_enqueuer.go?L78-89)

For the second mode, we will need to consider a historical backfill with a cardinality of 1 (a single datum) over all the applicable repositories.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
