### ISSUE TITLE
[DESIGN] Display mounted files as read-only in UI

### ISSUE THREAD

**Issue by danielmarquespt** [sourcegraph/sourcegraph#37192]
Design Ticket for [#31791](https://github.com/sourcegraph/sourcegraph/issues/31791)

To be addressed at the next design session

Figma File: https://www.figma.com/file/vW0D7Os7vkQ0eFNPXhcqas/%F0%9F%A6%A1-Batch-Changes-MAIN-%5BWIP%5D?node-id=209%3A4570

**Comment by malomarrec** [comment]
@danielmarquespt could you link the draft figma in here? Thanks!
