### ISSUE TITLE
Create a "/latest" stub URL for redirecting to the latest release blog post

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#37193]
_Just going to copy-paste [my comment on Slack](https://sourcegraph.slack.com/archives/C0C324C91/p1653642916502079?thread_ts=1653420503.479099&cid=C0C324C91)_:

>Do you think there’s a way to do that programmatically?
For example, if 3.XX is the latest release
If /blog/release/3.XX exists, link to it
If /blog/release/3.XX doesn’t exist, then don’t show any blog link

The way I was thinking is to on the blog site, automatically redirect "/latest" to the specific URL for the latest release post, as a compromise, some users may see the second-latest release post for a short period of time. Not sure if this compromise is acceptable but IMO this is more robust and we would have more control since changes can be made on our (server) side, not on customers' instances side.

**Comment by malomarrec** [comment]
Hey @unknwon, this issue didn't have a team label. Given you created it, I assigned you and added your team label. Feel free to unassign yourself. If this is not the right label, can you make sure to add the right one?
