### ISSUE TITLE
customer call follow-up issues

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#37194]
This issue is to track the follow-up work after a customer call from https://github.com/sourcegraph/customer/issues/977

Just filing one big issue for convenience. Some may split off into own issues.

- [ ] metric src_search_requests_total is lieing
- [ ] resource estimator lies about indexserver vs webserver. Says they need 4 zoekt-webserver and 2 zoekt-sourcegraph-indexserver. This confused and wasted a bunch of time.
- [ ] wants to make an slo by search type. need to get back and share the metrics for them to use.
- [ ] the time taken for a search was different to what user experiences. I've seen this myself.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/search-core - the "team/search-core" label was applied to this issue.

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket, please let us know how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
