### ISSUE TITLE
JetBrains: Monaco editor does not shrink when context gets longer

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#37210]
When we change the context dropdown to a larger string, the icons on the side of the editor gets pushed outside of the viewport. Strangely enough the selecting a smaller string will properly re-layout the editor.

This behavior works on sourcegraph.com so it must be something with our own flex rules but I can't easily figure out what it is so I’m postponing this with an issue :( 

https://user-images.githubusercontent.com/458591/173578660-f819bbd4-4fb5-4d84-90fb-160bb86423dc.mov

There's [special logic in Monaco to re-layout the editor when the container element changes dimensions](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/search-ui/src/input/MonacoQueryInput.tsx?L199-212). This callback is _run_ in our case yet the width does not properly calculate.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by vdavid** [comment]
@taras-yemets's recent PR (https://github.com/sourcegraph/sourcegraph/pull/37381) fixed this as well!
