### ISSUE TITLE
Add caching strategy for files mounted on step containers

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#37216]
#### Current state
In the first iteration of mounting files on step containers, caching is disabled. That's because, if the spec does not change but the mounted file does, our current implementation would just used cached results and not know about the changed file.

#### Proposed state

Add caching strategy for files mounted on steps containers. Note that files can be big binaries.

**Comment by Piszmog** [comment]
I was thinking this is a P0. Good item to follow-up on right after the initial file mount issue
