### ISSUE TITLE
Testing public roadmap item Zap

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#37228]
Linear issue: https://linear.app/sourcegraph/issue/SP-2/testing-public-roadmap-item-zap
# Problem to solve

…

# Measure of success

…

# Solution summary

…

# What specific customers are we iterating on the solution with?

…

## Product gaps and their customers/prospects for these projects

…

# Impact on use cases

…

# Delivery plan

* [ ] …
* [ ] …

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.
