### ISSUE TITLE
Second roadmap item zap test

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#37229]
Linear issue: https://linear.app/sourcegraph/issue/SP-3/second-roadmap-item-zap-test
**Public Roadmap Item**

# Problem to solve

…

# Measure of success

…

# Solution summary

…

# What specific customers are we iterating on the solution with?

…

## Product gaps and their customers/prospects for these projects

…

# Impact on use cases

…

# Delivery plan

* [ ] …
* [ ] …

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.
