### ISSUE TITLE
Testing again

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#37234]
<p><strong>Linear issue linkback <a href="https://linear.app/sourcegraph/issue/SP-5/testing-again">SP-5</a></strong></p>
**Public Roadmap Item**

# Problem to solve

…

# Measure of success

…

# Solution summary

…

# What specific customers are we iterating on the solution with?

…

## Product gaps and their customers/prospects for these projects

…

# Impact on use cases

…

# Delivery plan

* [ ] …
* [ ] …

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.
