### ISSUE TITLE
ci/flake: Batch changes details integration test

### ISSUE THREAD

**Issue by courier-new** [sourcegraph/sourcegraph#37233]
### Test

"Batch change details" (`client/web/src/integration/batches.test.ts:556`)

### Example failure

https://sourcegraph.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-sourcegraph-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bapp%3D%5C%22buildkite%5C%22%7D%20%7C%3D%20%5C%22Node%20is%20either%20not%20clickable%20or%20not%20an%20HTMLElement%5C%22%22%7D%5D,%22range%22:%7B%22from%22:%22now-7d%22,%22to%22:%22now%22%7D%7D

### Disabling PR

https://github.com/sourcegraph/sourcegraph/pull/37232

**Comment by umpox** [comment]
Reopening this, had a failure on `main` [here](https://buildkite.com/sourcegraph/sourcegraph/builds/159986#0181f2dd-6959-4065-90d5-aaf8c6131b29/6-109).

Disabled the test in this PR: https://github.com/sourcegraph/sourcegraph/pull/38669

**Comment by BolajiOlajide** [comment]
This is failing again. I haven't disabled it yet though but it seems the test fails when viewing a batch change belonging to an org.

The `user`  level batch change details doesn't flake, it's mostly at the `org` level

**Comment by jhchabran** [comment]
I have disable the test again, it flake a lot over the past few days, see https://sourcegraph.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-sourcegraph-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22editorMode%22:%22builder%22,%22expr%22:%22%7Bapp%3D%5C%22buildkite%5C%22%7D%20%7C%3D%20%60.test-file-diff-node%60%22,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%22now-7d%22,%22to%22:%22now%22%7D%7D

**Comment by BolajiOlajide** [comment]
This is technically a new flake.

<img width="1042" alt="CleanShot 2022-08-05 at 12 29 20@2x" src="https://user-images.githubusercontent.com/25608335/183073020-81827021-cf2c-45c1-96f7-cfd03a2a6fca.png">
