### ISSUE TITLE
Extend security audit logging

### ISSUE THREAD

**Issue by filiphaftek** [sourcegraph/sourcegraph#37264]
#### Feature request description

We need to extend security logging:
- [x] - 1. Extend `security_events` to support API token operations
- [x] - 2. Extend `security_events` to support OIDC logins
- [x] - 3. Extend `security_events` to support Github Auth logins
- [x] - 4. Extends `security_events` to login impersonate user actions - [sudo access token](https://docs.sourcegraph.com/api/graphql#sudo-access-tokens)
- [x] - 5. ~Allow enable audit_logs via env variable (to avoid changing by admin in site-config.json) - now it's only in [dot-com mode]~ ([PR](https://github.com/sourcegraph/sourcegraph/issues/37264))(https://sourcegraph.com/github.com/sourcegraph/sourcegraph@409dfa0859f481c7038160de0a8e7bee95464c2b/-/blob/internal/database/security_event_logs.go?L105) -> ended up using granular site config settings after all
- [x] - 6. Allow send audit logs to dedicated logger (not only to DB) - [log framework](https://docs.sourcegraph.com/dev/how-to/add_logging)
 
#### Is your feature request related to a problem? If so, please describe.

Required for Managed Instances - [OIDC logging](https://github.com/sourcegraph/customer/issues/997)
Short-lived tokens aka impersonate user - [issue](https://github.com/sourcegraph/deploy-sourcegraph-managed/pull/580)

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/cloud-devops - the "team/devops" label was applied to this issue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @RafLeszczynski - the "team/cloud" label was applied to this issue.

**Comment by RafLeszczynski** [comment]
@filiphaftek should this be part of V2 security hardening work or something independent?

**Comment by filiphaftek** [comment]
@RafLeszczynski @andreeleuterio this is harding/securing of whole Sourcegraph as a project, not only Cloud related, so I would propose to make this cross-team epic maybe? B/c we would need to change a bit of code of crucial SG login mechanisms.

**Comment by andreeleuterio** [comment]
@filiphaftek looping in @vrto who will work on many things related to audit logging on the application. Totally agree it goes beyond just Cloud.

**Comment by RafLeszczynski** [comment]
@andreeleuterio @vrto @filiphaftek 

I understand that there is a scope of work that will be a cross-team effort for different security-related initiatives connected with the Cloud.

I'd like to keep the Cloud team backlog containing only Cloud team-specific items - issues that the Cloud team engineers will own execution and delivery. 

Should this GH issue land in the CLoud team or the Security team backlog?

**Comment by vrto** [comment]
@RafLeszczynski I think the audit log should be agnostic to the deployment method, so I'd say Security.

**Comment by sourcegraph-bot-2** [comment]
Heads up @dcomas - the "team/security" label was applied to this issue.

**Comment by willdollman** [comment]
All PRs merged, all `security_events` discussed are being logged.
