### ISSUE TITLE
Line-number links in diff views are broken

### ISSUE THREAD

**Issue by plibither8** [sourcegraph/sourcegraph#37261]
- **Sourcegraph version:** sourcegraph.com
- **Platform information:** macOS Monterey, Google Chrome v102

#### Steps to reproduce:

1. Open any diff view, [like this](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/24da09b7547fb59011eea5a4135bc2219ffcd9b6?visible=3)
2. Click one the line-numbers either in unified or split view

#### Expected behavior:

The link should be an anchor relative to the current diff page, and should scroll to line number.

Example: `https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/24da09b7547fb59011eea5a4135bc2219ffcd9b6?visible=3#diff-2f2646f22e6965ade83312dfb963ed12L102`

#### Actual behavior:

The link with the anchor is absolute to the base URL.

Example: `https://sourcegraph.test:3443/#diff-2f2646f22e6965ade83312dfb963ed12L102`

**Comment by oleggromov** [comment]
It is actually interesting that this bug [must have existed](https://github.com/sourcegraph/sourcegraph/blame/main/client/web/src/components/diff/__snapshots__/DiffHunk.test.tsx.snap) for about 6 months based on the snapshot changes. Look at links, which are absolute.

**Comment by umpox** [comment]
I think it must be fairly recent? I loaded https://demo.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/24da09b7547fb59011eea5a4135bc2219ffcd9b6#diff-2f2646f22e6965ade83312dfb963ed12R110 (demo instance is usually slightly older, but not 6 months I'd have thought) and the bug isn't there. 

@oleggromov Does your PR not fix this? 🤔

**Comment by oleggromov** [comment]
No it does fix this exact bug.
The question was why in the snapshots, which were updated 6+ months ago, the URL starts with a slash - I thought it was because of the same bug. But it seems that this is most likely due to the way router is instantiated in the tests.

**Comment by oleggromov** [comment]
Merged my PR - must fix this issue: https://github.com/sourcegraph/sourcegraph/pull/37413
