### ISSUE TITLE
insights: hard errors from downstream APIs should be retried by default

### ISSUE THREAD

**Issue by leonore** [sourcegraph/sourcegraph#37284]
work for #35227 included a change where we made API errors terminate by default. we should approach this the other way, and specify which cases should *not* be retried (i.e. invalid queries, network errors). we can then add on to those cases if we find any more (see #34990)

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
