### ISSUE TITLE
insights: default to fork:yes archive:yes for scoped insights

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#37287]
When defining insights with a scoped repository field (non-global) it makes sense to include all of the provided repositories in the results, regardless of fork / archive status.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by Joelkw** [comment]
@coury-clark @chwarwick I thought we do this already? (I thought this was just to prevent a regression after we unify everything to run on the backend, but the current just-in-time insights do this?)

**Comment by chwarwick** [comment]
I went back to 3.40.1 to check, the current Just in time insights do not add any fork or archive parameters to the search query however results from forks `are included` which must be the search default if a specific repo is named.

So it appears this would be a regression for scoped insights and live preview.
