### ISSUE TITLE
OOMKILL events are not picking up by prometheus

### ISSUE THREAD

**Issue by michaellzc** [sourcegraph/sourcegraph#37304]
## Context

We are seeing processes (specifically childprocesses) are getting OOMKILL but not getting pick up by our OOMKILL monitoring graph in grafana

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/cloud-devops - the "team/devops" label was applied to this issue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/delivery - the "team/delivery" label was applied to this issue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @RafLeszczynski - the "team/cloud" label was applied to this issue.

**Comment by RafLeszczynski** [comment]
@michaellzc is this still something we plan to work on or should we close this issue?

**Comment by michaellzc** [comment]
> @michaellzc is this still something we plan to work on or should we close this issue?

Yes, I believe this is something we should be doing. Especially with the introducing of auto indexing and SSBC, we are expected to see more unpredictable RAM-extensive operations.

We need to ensure we are notified whenever it happens.

**Comment by michaellzc** [comment]
We briefly look into it once and it seems non-trivial to resolve this.

Maybe our services (component) should be responsible for monitoring and reporting status of child processes they spawn?

**Comment by michaellzc** [comment]
looks like we figured it out ;) 

https://github.com/sourcegraph/deploy-sourcegraph-managed/pull/917
