### ISSUE TITLE
JetBrains: Popup stays on top of other apps when clicking away

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#37322]
The popup stays on top of other apps on Mac (didn't test it in other OSes) until two clicks made on the other app:

<img width="500" alt="CleanShot 2022-06-16 at 12 07 48@2x" src="https://user-images.githubusercontent.com/2552265/174047496-e6aca5d4-5c2b-4841-899e-9ef702c9e89f.png">

[45-sec Loom demoing the behavior](https://www.loom.com/share/93fab13bad8645e68843fbacd4416d85)

This is rather annoying for me as a user, and not the way the Find in Files and other popups work in JetBrains IDEs.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
