### ISSUE TITLE
VSCE: log user events using LogUserEvent endpoint

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#37342]
Ref to [Slack thread C01LZKLRF0C](https://sourcegraph.slack.com/archives/C01LZKLRF0C/p1655308824678899)

> [logUserEvent is the only](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@1458b0cd20d0c7b2053b859d854774e7b4ec5ce2/-/blob/cmd/frontend/graphqlbackend/user_usage_stats.go?L77&utm_source=chrome-extension&utm_campaign=open-on-sourcegraph) place where “last active” and “last active in code host or code view” values are set, which are shown in side-admin/usage-stats.

Even though the LogUserEvent endpoint has been deprecated, it's the only endpoint that logs user activities. 
As a result, we should also log user events using the deprecated endpoint for backward compatibility

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by philipp-spiess** [comment]
This is no longer relevant after https://github.com/sourcegraph/sourcegraph/pull/38826

**Comment by philipp-spiess** [comment]
This is no longer relevant after https://github.com/sourcegraph/sourcegraph/pull/38826
