### ISSUE TITLE
insights: duplicate time values are returning from API [timeboxed]

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#37345]
When clicking on an insight point the wrong query was generated. @vovakulikov identified that the API response is returning duplicate values for a single time period.

Typically we deduplicate data coming out of the database, so my first instinct would be to look at the resolver construction and see if there is any duplicates there.

Relevant insight
https://demo.sourcegraph.com/insights/insight/aW5zaWdodF92aWV3OiIyNU9UM0FkT2hSem1reHJxbWFKZE9Qekt5VUUi

``` json
{
    "data": {
        "insightViews": {
            "nodes": [
                {
                    "id": "aW5zaWdodF92aWV3OiIyNU9UM0FkT2hSem1reHJxbWFKZE9Qekt5VUUi",
                    "dataSeries": [
                        {
                            "seriesId": "25OT3D2PbaSBv2w4o3QQEf5oZV0",
                            "label": "this.skip() or it.skip(",
                            "points": [
                                {
                                    "dateTime": "2021-06-20T00:00:00Z",
                                    "value": 12,
                                    "__typename": "InsightDataPoint"
                                },
                                {
                                    "dateTime": "2021-07-20T00:00:00Z",
                                    "value": 12,
                                    "__typename": "InsightDataPoint"
                                },
                                {
                                    "dateTime": "2021-08-20T00:00:00Z",
                                    "value": 14,
                                    "__typename": "InsightDataPoint"
                                },
                                {
                                    "dateTime": "2021-09-20T00:00:00Z",
                                    "value": 12,
                                    "__typename": "InsightDataPoint"
                                },
                                {
                                    "dateTime": "2021-10-20T00:00:00Z",
                                    "value": 12,
                                    "__typename": "InsightDataPoint"
                                },
                                {
                                    "dateTime": "2021-11-20T00:00:00Z",
                                    "value": 12,
                                    "__typename": "InsightDataPoint"
                                },
                                {
                                    "dateTime": "2021-12-20T00:00:00Z",
                                    "value": 22,
                                    "__typename": "InsightDataPoint"
                                },
                                {
                                    "dateTime": "2022-01-20T00:00:00Z",
                                    "value": 22,
                                    "__typename": "InsightDataPoint"
                                },
                                {
                                    "dateTime": "2022-02-20T00:00:00Z",
                                    "value": 24,
                                    "__typename": "InsightDataPoint"
                                },
                                {
                                    "dateTime": "2022-03-20T23:13:23Z",
                                    "value": 32,
                                    "__typename": "InsightDataPoint"
                                },
                                {
                                    "dateTime": "2022-04-20T23:13:40Z",
                                    "value": 32,
                                    "__typename": "InsightDataPoint"
                                },
                                {
                                    "dateTime": "2022-05-20T23:38:10Z",
                                    "value": 77,
                                    "__typename": "InsightDataPoint"
                                },
                                {
                                    "dateTime": "2022-05-20T23:38:10Z",
                                    "value": 77,
                                    "__typename": "InsightDataPoint"
                                },
                                {
                                    "dateTime": "2022-06-16T00:25:13Z",
                                    "value": 58,
                                    "__typename": "InsightDataPoint"
                                }
                            ],
                            "status": {
                                "backfillQueuedAt": "2022-02-20T22:58:34Z",
                                "completedJobs": 7,
                                "pendingJobs": 0,
                                "failedJobs": 548,
                                "__typename": "InsightSeriesStatus"
                            },
                            "__typename": "InsightsSeries"
                        }
                    ],
                    "__typename": "InsightView"
                }
            ],
            "__typename": "InsightViewConnection"
        }
    }
}
```

**Comment by chwarwick** [comment]
Thanks to a weekly insight I found on demo I can see this issue started after: `2022-04-22T05:13:41Z` and an hourly insight shows this ended in the hour prior to: `2022-05-30T19:38:16Z`.   It would appear as though this was introduced in 3.39 and resolved in 3.40 however the duplicate recordings still remain in the db.

**Comment by Joelkw** [comment]
Is it safe to close this issue given @chwarwick 's comment above, @sourcegraph/code-insights-backend ?

**Comment by vovakulikov** [comment]
@sourcegraph/code-insights-backend can we put a filter functionality where we will remove all duplicates before we return data from the backend just to avoid problems like this one in the future?

**Comment by coury-clark** [comment]
@vovakulikov that already exists, but only works if the times are exactly the same. Otherwise, we have no way to identify if something is a duplicate without building a window function that is the minimum aggregate. 

In general I'm still skeptical as to whether we understand the root cause here, and I'd recommend we leave it open and investigate more.

**Comment by vovakulikov** [comment]
@coury-clark but in this issue description we have the example of BE response where we have two points with exact same time values. 
```
 {
   "dateTime": "2022-05-20T23:38:10Z",
    "value": 77,
    "__typename": "InsightDataPoint"
 },
{
   "dateTime": "2022-05-20T23:38:10Z", 
   "value": 77,
   "__typename": "InsightDataPoint"
},
```

**Comment by coury-clark** [comment]
@vovakulikov That's why I'm saying we need to investigate this more 🙂

**Comment by Joelkw** [comment]
Here is another case – 

Proposal: timebox this investigation to <0.5 day to see if we should continue pursuing this fix.

**Comment by vovakulikov** [comment]
@CristinaBirkel, I reopen this since we still have this problem with rounding and duplicate points (which means wrong points  URLs). 


See [this loom](https://www.loom.com/share/f9f72884571e4a5b8ad155ff33798340) for more details. Here is the insight from the loom [(dashboard page)](https://demo.sourcegraph.com/insights/dashboards/ZGFzaGJvYXJkOnsiSWRUeXBlIjoiY3VzdG9tIiwiQXJnIjo3NDUzNn0=) and here is [the standalone insight page for this insight](https://demo.sourcegraph.com/insights/insight/aW5zaWdodF92aWV3OiIyNWN5b1BZeWFLSVdmVllXeGRqTmtUYTl2Um4i)

## NOTE
Joel just got lucky in the loom. The standalone and the dashboard insights are broken (they use the same insight data with duplicate points). Try to slightly move your cursor and you will see two different states for visually one point (but there are two points they are just placed together because of their simular time value)

<img width="410" alt="Screenshot 2022-08-09 at 12 17 55" src="https://user-images.githubusercontent.com/18492575/183612790-b749eae9-aef8-4079-b819-03e2d6c7c79b.png">

<img width="378" alt="Screenshot 2022-08-09 at 12 18 02" src="https://user-images.githubusercontent.com/18492575/183612812-73e36b65-fdb6-4d12-9351-ade31c1700c6.png">

Here is a part of a response to this insight 
```json
{
  "seriesId": "25cyro3I2B13Exc53e2qVsdSryH",
  "label": "literal docs link (bad, not versioned)",
   "points": [
     {
       "dateTime": "2022-07-19T02:34:08Z",
       "value": 12,
       "__typename": "InsightDataPoint"
      },
      {
       "dateTime": "2022-07-19T02:34:09Z",
       "value": 12,
       "__typename": "InsightDataPoint"
      },
   ],
}
```

**Comment by CristinaBirkel** [comment]
Fixed in https://github.com/sourcegraph/sourcegraph/pull/40185. That referenced this issue: https://github.com/sourcegraph/sourcegraph/issues/30642 which I think is basically the same issue.
