### ISSUE TITLE
Tracking issue - Health Status Tooling

### ISSUE THREAD

**Issue by caugustus-sourcegraph** [sourcegraph/sourcegraph#37356]
### Plan

[SDD](https://docs.google.com/document/d/1shS8DZkZXMB-T4rKwLMogU70N4mSyOpDG1G7ElkjHD4/edit#heading=h.5owhf6uyyp03)

We want to offer admins a simple way to evaluate the health of a Sourcegraph deployment.

### Requirements 
* Define a list of technical health checks that validate deployment is healthy
* Ship a prototype health status tool that provides validation that everything is set up properly. The prototype should assess the following:
  * Can services talk to each other as expected
  * Is the disk configured as expected (i.e., each replica has a separate location defined, etc)
  * Is the disk and network performing as expected
  * Can the instance communicate with the code hosts
* The tool should work for Kubernetes deployments (w/ or w/o Helm)
* The tool should render health status in a visually simple way via CLI (think stop sign colored updates). For an example please see [this Reddit post](https://www.reddit.com/r/ethstaker/comments/n3nyv8/valid8r_cli_for_easy_validator_health_check/).
* Ship documentation on remediation efforts or troubleshooting best practices. The documentation should be descriptive enough to assist customers/CEs debug at each level of the health check. The documentation should address both Yellow and Red output statuses.
* Share this tool with CE to validate with select customers

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/delivery - the "team/delivery" label was applied to this issue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/search-core - the "team/search-core" label was applied to this issue.

**Comment by jjeffwarner** [comment]
This was migrated to Delivery at https://github.com/sourcegraph/sourcegraph/issues/42663
