### ISSUE TITLE
SSBC: Restore "Don't show this again" button in src-cli modal

### ISSUE THREAD

**Issue by courier-new** [sourcegraph/sourcegraph#37360]
Due to a concern about new users accidentally dismissing the "Download for src-cli" modal permanently and getting lost in the new UI, we have temporarily disabled the "Don't show this again" button from that modal:

![Image](https://user-images.githubusercontent.com/8942601/174161613-f027ce60-6826-4a23-ae93-02b4d5e27894.png)]

See also: [slack context](https://sourcegraph.slack.com/archives/C01LJ9DK8ES/p1655384607258329).

Once SSBC has been around for a little while, we should consider restoring it, so that users who know what they're doing can skip the extra step of dealing with the modal and go straight to getting their spec downloaded.

**Comment by courier-new** [comment]
This can go to the backlog, but let's not lose track of it. We should tentatively agree on when it might make sense to bring this back.

**Comment by adeola-ak** [comment]
i vote P1 since its quick
