### ISSUE TITLE
Use compute to show recent files to users in homepage panel

### ISSUE THREAD

**Issue by AdhamKhalifa** [sourcegraph/sourcegraph#37362]
In the homepage panel for files, show recent files to user. If the git history is empty, then display the empty view.

The compute query will be used to get git history:
`content:output((.|\n)* -> $repo) author:"[USER EMAIL HERE]" type:diff after:"1 year ago" count:all`

Edge cases will include situations when the user has git history, but no recent files, or when the user doesn't have any git history.
Any work done here should be under a feature flag and not show if the feature flag is disabled.

I'll be working from `RecentFilesPanel.tsx`

**Comment by malomarrec** [comment]
Hey @malomarrec, it looks like this issue was created by someone outside Sourcegraph. Assigning you to triage it! Please answer and route to the right team by adding their team label.

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.
