### ISSUE TITLE
JetBrains: Don't let file cache grow too large on the JS side

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#37373]
## Context
We currently [use caching](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/jetbrains/webview/src/search/lib/blob.ts?L10-15) in `blob.ts` when loading file content for the "Find on Sourcegraph" popup.
This is neat because we optimize network use this way.
We never flush this cache.

## Problem

The cache can grow to an arbitrary size, and waste/use up the user's memory.

## Solution

Ideas:
- Items that are older than X minutes (30 minutes?) could be removed from the cache.
- We could track the cache size and start purging the oldest or the largest items if we hit a limit. It'd be extra neat if we could get the amount of memory that the user allows for the IDE, and perhaps even get stats from the IDE on current memory use, and work with that limit dynamically.
- Doing a purge could happen at each cache read (or write), via a repeating timer, or both.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
