### ISSUE TITLE
External service job can become stuck processing forever

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#37377]
We observed a [customer](https://github.com/sourcegraph/accounts/issues/8405) instance that had an external service sync job stuck in the queue for a very long time, many weeks.

It was in the `processing` state and had been reset twice. We deleted the row which caused a new job to be queued and repos started to sync as expected. 

Our current theory is that repo-updater was restarted while the job was processing which meant that it was never marked as complete. Then, all subsequent attempts to queue the job saw an existing job and didn't attempt to queue a duplicate.

We should:

* Ensure that we can't get into this state again, perhaps by clearing out processing jobs when repo-updater starts
* Surface the state of the sync job somewhere so that it's easier to spot if it *does* happen again

Related issue: https://github.com/sourcegraph/customer/issues/978

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.

**Comment by ryanslade** [comment]
@jplahn This is a low chance, but high risk issue which we should get to quite soon.

**Comment by ryanslade** [comment]
@asdine Assigning this to you as I think that's what was agreed during our last team sync.
