### ISSUE TITLE
batch changes: preview changesets selection has strange behaviour

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#37397]
- **Sourcegraph version:**  `155342_2022-06-17_8bb79a02abd7`
- **Platform information:**  Chrome

#### Steps to reproduce

1. Create a batch change and apply a spec
2. Wait for changesets to generate
3. In the preview page, click "view more" until all changesets visible
4. Check "select all", doesn't actually select all.
5. Select _all_ all, does select all
6. Uncheck one, unchecks everything (except some?)

Video: https://www.loom.com/share/93a4961e57404f689d44b04b3e3d2914 , the preview is here: https://k8s.sgdev.org/users/robert/batch-changes/pr-auditor-patch-test/executions/QmF0Y2hTcGVjOiI2amRTbG5ZSm5yRiI=/preview

I was only able to reproduce this in the preview page, and not the changesets page

**Comment by adeola-ak** [comment]
p1?

**Comment by chrispine** [comment]
Step 6 feels like a bug we should address. Steps 1-5 are more complicated and we don't plan on addressing those in the near term.
