### ISSUE TITLE
Fix capitalization in "Code search basics" list

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#37402]
The capitalization should be fixed to match our [style guide](https://handbook.sourcegraph.com/company-info-and-process/communication/content_guidelines/style_and_mechanics/#capitalization) (eg `Code search basics` instead of `Code Search Basics` and `Find code across...` instead of `Find Code Across...`).

![image](https://user-images.githubusercontent.com/1976/174502329-a52d901d-3be2-47ce-b32c-0a0d18387a2c.png)

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @a-bergevin - the "team/growth" label was applied to this issue.
