### ISSUE TITLE
local dev env: local state issues with gitserver when reseting the database 

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#37432]
So, while I was looking to debug https://sourcegraph.slack.com/archives/CHEKCRWKV/p1655287450540019, I've found out the following problem: 

If I wipe my database entirely, but not remove the repositories stored in `~/.sourcegraph/repos`, adding those repositories again will result in those always having the `not_cloned` status under the `gitserver_repos` table. 

It was really confusing, because I can still browse the files from these repo and the UI may say they are indexed. 

### How to reproduce the problem 

- Starting fresh: 
  - `sg db reset-pg --db=all` 
  - `sg db add-user` 
  - `rm -Rf ~/.sourcegraph/repos*`
- Checking out my branch with some gql queries that add the repos
  - `git co devx/repo-mgmt-integration` 
  - Edit `dev/ci/integration/repo-mgmt/repos_test.go` and comment the `defer` containing `		err := client.DeleteExternalService(esID, false)` so those repos are not wiped after running the test. 
- `sg start` 
- Run the repomgmt integration test: 
  - `cd dev/ci/integration/repo-mgmt`
  - `export GITHUB_TOKEN=<secret>`
  - `go test -long -base-url "https://sourcegraph.test:3443" -email "sourcegraph@sourcegraph.com" -username "sourcegraph" -password "sourcegraphsourcegraph" -v`

This should succeed. 

- Let's reset the state, but without removing the gitserver files:
  - `sg db reset-pg --db=all` 
  - `sg db add-user` 
- Run the test from above again, and it will timeout.
- If you look at the `gitserver_repos` table, all the repos statuses are `not_cloned`, even though you can browse those files in the UI.

**Comment by jhchabran** [comment]
cc @asdine as we talked about this over slack :)

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.
