### ISSUE TITLE
SPIKE: Investigate using notebooks query block in code monitor creation page

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#37465]
- [ ] See what the technical effort would be to use the notebook search query block for previewing monitor results
- [ ] Identify any design impacts of the change
- [ ] Update this issue with findings so we can decide on priority

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by camdencheek** [comment]
Closing as "won't do" since both notebooks and monitors have limited dev time allocated
