### ISSUE TITLE
JetBrains user testing 

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#37480]
**Pre-testing tasks**
- [x] @jjinnii Finalize [user testing protocol](https://docs.google.com/document/d/1rra86ThotRy6tmILgZ_GlK-DtPbP3IJKMlOdEFWhkgc/edit#heading=h.qm18wutam9wr). Need guidance from @vdavid @philipp-spiess on user tasks and installation instructions. 
- [x] @vdavid @philipp-spiess Provide guidance on how to distribute the plugin for large groups of unmoderated testing. Bulk emailing the most recent package poses security concerns. 
- [x] ~~@vdavid @philipp-spiess Address #37322 issue tagged as higher priority to address before external testing.~~ No longer a priority prior to testing, but high priority prior to release.

**Testing plan** 

1. Internal test with 1-2 internal users by EOW 2022-06-24
-  Internal user 1 scheduled for 2022-06-23
-  Internal user 2 scheduled for 2022-06-24
2. External moderated testing (From 2022-06-27) 
-  Customer 1 scheduled for 2022-06-29
-  Customer 2 - (TBD)
3. External unmoderated testing (From 2022-06-27) *_dependent on how we can securely distribute plugin_
4. Share for internal dogfooding (From 2022-06-27)

**Comment by vdavid** [comment]
> Finalize user testing protocol. Need guidance

On it now! Sorry for the delay.

> Bulk emailing the most recent package poses security concerns.

What do you mean here, @jjinnii? In my best understanding, the source code is available for anyone, and so are the build instructions and tools, so anyone can build the latest version of the package.
I'd only say that bulk emailing the most recent package as a file attachment is inconvenient for testers, so I'd rather send them a link to a file shared in Google Drive, but that's it.

> Address JetBrains: #37322 issue tagged as higher priority to address before external testing.

If we go with the iterative approach, then I'd say this is not even a blocker for external testing. It seems to affect only macOS and some Linux environments, and even that, not always, plus we should fix it in a few days.

> Dates

@jjinnii, could you use ISO dates in the timeline estimate as per our [style guide](https://handbook.sourcegraph.com/company-info-and-process/communication/content_guidelines/style_and_mechanics/#dates)? I'm note sure I'm getting the dates you used in the description above. "24/08/2022" seems like August to me?

**Comment by vdavid** [comment]
@jjinnii just a heads up that to my best understanding, I answered all open questions here. :)

**Comment by jjinnii** [comment]
Thanks @vdavid @philipp-spiess ! It seems @ryankscott has confirmed Google Drive is secure for our customers, so checking that one off the list. 😄 

@vdavid "If we go with the iterative approach" could you clarify what you mean here? Now that we've worked on our tasks, I will agree that it's no longer a blocker to external testing but I do still consider it high priority to address prior to release.

Also sorry on the dates, my brain got messed up with how Korea does dates. 😓

**Comment by vdavid** [comment]
> @vdavid "If we go with the iterative approach" could you clarify what you mean here? Now that we've worked on our tasks, I will agree that it's no longer a blocker to external testing but I do still consider it high priority to address prior to release.

We're in agreement. Not a blocker to external testing but high prio before the release. Sorry if what I wrote was ambiguous.

**Comment by vdavid** [comment]
I think the timeline is still wrong, though. @jjinnii, do you mean June (06) or July (07)? I think you meant June.

**Comment by jjinnii** [comment]
@vdavid Yes sorry updated again 😓 I don't know why that was so hard for me

**Comment by philipp-spiess** [comment]
I’m moving this into the next milestone as this has work scheduled for the next weeks as well.

**Comment by philipp-spiess** [comment]
Should we mark this as done? @jjinnii @ryankscott @vdavid
