### ISSUE TITLE
Anchor links in repo notebooks don't work

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#37506]
Form [slack](https://sourcegraph.slack.com/archives/C03CSAER9LK/p1655835377045129)

Anchor links in search notebooks committed to repositories don't seem to work - clicking on an anchor generates a link like this:

https://sourcegraph.com/github.com/sourcegraph/devx-scratch/-/blob/2022/support/log.snb.md#2022-06-16-45826005-6883-4201-873a-52ffc7e287ea

However, this link doesn't correctly go the desired anchor when shared

cc @bobheadxi

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.
