### ISSUE TITLE
insights: create index for series status queries

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#37520]
PGHero detected a path with no index when we determine counts of each series in the `insights_query_runner_jobs_queue`.

`
CREATE INDEX CONCURRENTLY ON insights_query_runner_jobs (series_id, state)`

https://sourcegraph.slack.com/files/UPPSGTBBK/F03MA2HT0C8/screenshot_2022-06-21_at_22.19.32_2x.png

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
