### ISSUE TITLE
Create OOB migration

### ISSUE THREAD

**Issue by miveronese** [sourcegraph/sourcegraph#37558]
Create an OOB migration that should change the source for all fields to either ‘api’ or ‘sync’ depending on whether the explicit permissions API has been enabled in site config.

- [RFC ](https://docs.google.com/document/d/1nWbmfM5clAH4pi_4tEt6zDtqN1-z1DuHlQ7A5KAijf8/edit#)
- [How we do OOB migrations at SG ](https://docs.sourcegraph.com/dev/background-information/oobmigrations#developing-an-out-of-band-migration)

/cc @sourcegraph/source

**Comment by unknwon** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IAM-627aebcc9f8b7c00128a8ab6/issues/sourcegraph/sourcegraph/37558?planning-poker) with ZenHub @kopancek @miveronese @pjlast
