### ISSUE TITLE
Make sidebar on search results page collapsible

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#37552]
Currently, the sidebar on the search results page persists and is not collapsible. We have a new design that moves the sidebar to the right, makes it collapsible, and uses more natural language to describe the filters.

![image](https://user-images.githubusercontent.com/4605817/178842204-56b23522-32f8-4305-a9c9-4d83eef52834.png)

This is inconsistent with other sidebar UX patterns in the app, and many users find this sidebar to be unhelpful or annoying.

We should:
- Make the sidebar hideable via the same mechanism employed in the file tree
- Persist the users preference in temporary settings to it's not reset when they leave the page

## Designs
[Prototype](https://www.figma.com/proto/8MkIcpDtjv6tqgxZFcEQDt/Core-workflow-punch-list?node-id=176%3A14490&scaling=scale-down&page-id=0%3A1&starting-point-node-id=176%3A19861&show-proto-sidebar=1)

[Figma](https://www.figma.com/file/8MkIcpDtjv6tqgxZFcEQDt/Core-workflow-punch-list?node-id=176%3A14490)

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by almeidapaulooliveira** [comment]
We got you covered, @rrhyne !!!
