### ISSUE TITLE
Extensions: create repo with code-intel extensions bundles

### ISSUE THREAD

**Issue by taras-yemets** [sourcegraph/sourcegraph#37550]
In order to minimize the admin's effort of enabling code intelligence on the air-gapped instances create a repo with code intel extension bundles and manifests.
Except for the latter two, this repo should also include the [code-intel-extensions](https://github.com/sourcegraph/code-intel-extensions) revision from which the bundles were created, so that admins can run security audits considering this revision. 
More details in [this thread](https://sourcegraph.slack.com/archives/C01LZKLRF0C/p1655302657310299).

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
