### ISSUE TITLE
Add unique indexes to tables that got the new "source" column

### ISSUE THREAD

**Issue by miveronese** [sourcegraph/sourcegraph#37557]
After adding the new non null column "source" to the tables below, we also need to update their unique indexes  to include the new column 

```
repo_permissions
user_permissions
sub_repo_permissions
user_pending_permissions
repo_pending_permissions
```

/cc @sourcegraph/source

**Comment by unknwon** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IAM-627aebcc9f8b7c00128a8ab6/issues/sourcegraph/sourcegraph/37557?planning-poker) with ZenHub @kopancek @miveronese @pjlast
