### ISSUE TITLE
Sunset Datadog 

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#37568]
Based on internal feedback we plan to return to our previous observability solutions and led the decision by lead by #wg-observability

Places we need to remove Datadog from:

- [ ] Cloud Helm chart https://sourcegraph.com/search?q=context:global+datadog+repo:%5Egithub%5C.com/sourcegraph/.*cloud*%24+&patternType=literal
- [ ] Possibly some places in our internal codebase (if they are not flagged off) https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+datadog&patternType=literal
- [ ] Possible revert of https://github.com/sourcegraph/sourcegraph/pull/34063 (or check that is feature-flagged)

**Comment by jhchabran** [comment]
[Finance thread](https://sourcegraph.slack.com/archives/C018LT2BTTN/p1655931380369869)
