### ISSUE TITLE
Add support for two sources of perms

### ISSUE THREAD

**Issue by miveronese** [sourcegraph/sourcegraph#37560]
This is a placeholder and more details will be added soon

Basically, what this ticket will cover are the code changes necessary to support the two new sources of permissions.

For more context, see the [RFC](https://docs.google.com/document/d/1nWbmfM5clAH4pi_4tEt6zDtqN1-z1DuHlQ7A5KAijf8/edit#).

/cc @sourcegraph/source

**Comment by pjlast** [comment]
Just going to mention here that whatever we implement here can have implications for https://github.com/sourcegraph/sourcegraph/issues/25903 and vice versa

**Comment by unknwon** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IAM-627aebcc9f8b7c00128a8ab6/issues/sourcegraph/sourcegraph/37560?planning-poker) with ZenHub @kopancek @miveronese @pjlast
