### ISSUE TITLE
Add UI page showing permissions granted and their source

### ISSUE THREAD

**Issue by miveronese** [sourcegraph/sourcegraph#37562]
The new page should be visible only to admins and should show:
-  permissions granted by user / repo
- the source of those permissions (from code host syncing or explicit permissions).

For more context: [RFC](https://docs.google.com/document/d/1nWbmfM5clAH4pi_4tEt6zDtqN1-z1DuHlQ7A5KAijf8/edit#)

/cc @sourcegraph/source

**Comment by unknwon** [comment]
This page sounds complicated and may need to involve design if we want to make things intuitive. Personally would suggest the MVP for the issue to be either a GQL query or a debugging endpoint to avoid any design work.

**Comment by unknwon** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IAM-627aebcc9f8b7c00128a8ab6/issues/sourcegraph/sourcegraph/37562?planning-poker) with ZenHub @kopancek @miveronese @pjlast
