### ISSUE TITLE
Resource Estimator: Creating buckets of customers based on user size and repo

### ISSUE THREAD

**Issue by briemcnally** [sourcegraph/sourcegraph#37572]
To begin building out reference architectures, create buckets of customers based on user size and repo. 

Define using T-shirt sizes S/M/L 
Collaborate with Analytics to determine sizes based on BQ data
Ensure criteria for t-shirt sizes is documented and linked to any queries

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/delivery - the "team/delivery" label was applied to this issue.
