### ISSUE TITLE
Disable email action in code monitors if SMTP is not enabled

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#37583]
currently, it's possible to set email as an action on a code monitor, even if SMTP is disabled. We should require it to be enabled if SMTP is not enabled on the instance.

cc @almeidapaulooliveira could use some design eyes here as well for look at how we might indicate/message that. My thought is we gray out email as an action option with a message to enable SMTP to send email notifications both in the create and edit screen :
![image.png](https://images.zenhubusercontent.com/5467e9ba7c6ccc6277a5f103/f5ad2e9b-4dbb-4fb8-a752-2881ad7be9ed)

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by almeidapaulooliveira** [comment]
I Agree, Ben. Here's a quick sketch of how it should look.
![settings](https://user-images.githubusercontent.com/64257673/175569510-55ad8f80-0cc0-4c9f-8d4d-9b89e5f4d5d0.png)
.

**Comment by almeidapaulooliveira** [comment]
[Figma](https://www.figma.com/file/F3lZ0O45OoD9fsvaz5xS56/Disable-email-action-in-code-monitors-if-SMTP-is-not-enabled?node-id=1345%3A458) file with the suggested improvement.

**Comment by almeidapaulooliveira** [comment]
@limitedmage I updated the [Figma](https://www.figma.com/file/F3lZ0O45OoD9fsvaz5xS56/Disable-email-action-in-code-monitors-if-SMTP-is-not-enabled?node-id=1345%3A458) file with the info message when users go modify a monitor with email already configured.

**Comment by limitedmage** [comment]
@almeidapaulooliveira  Thanks, this is looking good! Left a question in the feedback about how this layout should be made responsive.
