### ISSUE TITLE
Check that docker is running when running src batch

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#37594]
#### Current behaviour

If I run a `src batch preview`, but Docker is not running, I get a not very informative 

```
❌ Error:
   exit status 2
```   

This confuses users, and ... sure you need to RTFM, but that takes time.
It's a very very frequent failure mode in first usage.

#### Proposed behaviour

Check that docker is running, and fail with an explicit error

#### Environemnt

MacBook Pro / M1

**Comment by adeola-ak** [comment]
P2?

**Comment by chrispine** [comment]
We have a check that apparently isn't working anymore.

**Comment by chrispine** [comment]
customer ran into this, so moving it back to Triage

**Comment by rprince-anduril** [comment]
I just ran into this on OSX 12.5 running Docker Desktop 4.3.2
```
$ src batch preview -f fix-ecr-issues.batch                                                                                                                                 ~/Downloads

❌ Error:
   exit status 1
```
