### ISSUE TITLE
executors: Improve documentation of binary installation

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#37599]
Feedback from customer:

> with the [currently documented approach](https://docs.sourcegraph.com/admin/deploy_executors#:~:text=Download%20latest%20binary) for downloading the executor binary, its not obvious if I need to update the version of the executor binary that I'm currently using. Since the feature is now in beta, I think it might be a good idea to introduce formal versioning (a separate changelog ) for the executors binary or document if the expectation is that executors should be updated every time there is a new release of Sourcegraph.

**Comment by Piszmog** [comment]
We should specify what kind of documentation we are looking for. Maybe have a list of possible documentation update should be done as part of this issue.
