### ISSUE TITLE
migrations: Investigate why slow migrations can succeed, but are marked as failed

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#3764]
For example our migration rolling out DEFERRED was marked as dirty on Sourcegraph.com. However, the migration actually did succeed.

Working theory:

- Frontend sends migration to postgres
- Some very long period later Kubernetes health check fails, kills frontend
- The migration completed because Postgres was running the query and didn't care that frontend disconnected
- Frontend died so it didn't update the version bit

Context: https://sourcegraph.slack.com/archives/C0J618TTM/p1556765298002700

**Comment by tsenart** [comment]
No relevant anymore since we have no more application level migrations in repo-updater.
