### ISSUE TITLE
Re-enable codeintelqa integration test

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/sourcegraph#37671]
I'm temporarily turning it off because of flakiness in CI.

**Comment by varungandhi-src** [comment]
Re-opening this. Since we have separate alerting, can we run this test in a way so that failures don't block the `main` branch?

**Comment by Strum355** [comment]
This isnt blocking `main` branch, nor deploys to production, Im assuming this was cleared up earlier in slack?
