### ISSUE TITLE
JetBrains: Add access token validation button to Settings

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#37683]
It would be nice if we gave a way for the user to verify that their connection to Sourcegraph works after setting the server URL and/or access token.

The usual way to do this in JetBrains IDEs is with a "Test connection" button. These buttons don't really have a cohesive look if I remember correctly, but this is an example:

![CleanShot 2022-06-24 at 11 51 57@2x](https://user-images.githubusercontent.com/2552265/175511105-24b2dad0-7cbd-46d2-8249-7e50fd12b373.png)

We could add such a button to the settings UI.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by jjinnii** [comment]
@vdavid Could I have a bit more context on this issue please? I understand the intent, but do we expect failures with the connection after a user successfully validates? This wasn't something we ever introduced for VS Code, and to my knowledge, we haven't run into issues with users facing technical problems post authentication.

**Comment by vdavid** [comment]
I mean, as a user, I can mistype the token, copy without the first or last character, or maybe forget to change the URL. As a user, it'd be reassuring for me to see that the connection works with the URL+token that I just entered.

If we automate the auth the way Beatrix did with VS Code recently, then this is a lot less needed, but until then, I think it's quite a nice feature.
Does that make sense @jjinnii? Or am I just an outlier in this and everyone else is a lot more trusting that a copy-pasted access token _will_ work? 😄

**Comment by jjinnii** [comment]
@vdavid Would it be okay if we tied this discussion into #36783 ? I think adding some form of "Test" or "Validate" prior to closing out the Preferences, is dependent on when/how validation works inside the Preferences window. (e.g. the questions I asked [here](https://github.com/sourcegraph/sourcegraph/issues/36783#issuecomment-1174662123)) 

If you'd prefer to keep the issues separate, just keep in mind that the answers in #36783 will also define my response to the questions here!

**Comment by vdavid** [comment]
@jjinnii Sure, I agree, let's continue there!
