### ISSUE TITLE
JetBrains: Set up screenshot testing for the web view

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#37681]
We have Chromatic set up; it'd be an easy win to hook it up for our web view to protect us against visual regressions.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by vdavid** [comment]
Discoveries, thoughts:
- Probably a dead end: ~~[This search](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph+chromatic+-file:.*%5C.%28tsx%3F%7Cmd%29&patternType=regexp) (17 files) must contain the code that runs Chromatic. I guess it's somewhere in [pipeline.sh](https://sourcegraph.com/github.com/sourcegraph-testing/demo-sourcegraph/-/blob/enterprise/dev/ci/internal/ci/pipeline-steps.go).~~
- I think we'll also need to add our project's `yarn build` step to the CI pipeline. (With [this search](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph+-repo:jetbrains+-repo:lsif+-repo:scip+-repo:demo+-repo:incremental+-repo:doctree+-repo:about+-repo:langserver+-file:.*%5C.%28tsx%3F%7Cmd%29+-file:.gitignore+-path:client/jetbrains+jetbrains&patternType=regexp) I found no trace of our build step being present in the CI.
- Then I think we'll need to create a storybook for the `App` component, and Chromatic will pick it up automatically?

@philipp-spiess do you have some useful input at this point? I don't have much experience with CI, so I think it'd take much time for me alone to find where to add our build step. On the storybook/Chromatic part, I can use some thoughts too if you have some.

**Comment by philipp-spiess** [comment]
> I think we'll also need to add our project's yarn build step to the CI pipeline. (With [this search](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph+-repo:jetbrains+-repo:lsif+-repo:scip+-repo:demo+-repo:incremental+-repo:doctree+-repo:about+-repo:langserver+-file:.*%5C.%28tsx%3F%7Cmd%29+-file:.gitignore+-path:client/jetbrains+jetbrains&patternType=regexp) I found no trace of our build step being present in the CI.

We have this CI step right now which builds the JetBrains frontend: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/dev/ci/internal/ci/operations.go?L294-301

There is no test script inside the `package.json` yet so we can't start any tests. I think this is what we need to build.

> Then I think we'll need to create a storybook for the App component, and Chromatic will pick it up automatically?

Yeah this is also how I understand this method: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/dev/ci/internal/ci/operations.go?L344-368

---

It seems like we only have `.story.tsx` files inside a few of the client repos and haven't leveraged them in vscode or jetbrains yet. I’m not sure if this needs additional work. Potentially this could be expensive as now every chromatic build in the monorepo also needs to build JetBrains. This will become cheaper with #34571 though

**Comment by vdavid** [comment]
Waiting for https://github.com/sourcegraph/sourcegraph/issues/34571

**Comment by philipp-spiess** [comment]
@vdavid Since the dependency is resolved, I've put this back into the backlog
