### ISSUE TITLE
JetBrains: Stylization of dropdowns

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#37689]
**Stylization of dropdowns- medium**

Our suggested auto-complete dropdown seems to have a different, more condensed UI than native dropdowns that JetBrains is using. We're also using a grey color to show a highlighted state, whereas JetBrains uses the same blue for all their selection colors. (compare screenshots below)

<img width="630" alt="Screen Shot 2022-06-23 at 1 54 16 PM" src="https://user-images.githubusercontent.com/87138876/175294766-63c7e879-7179-468a-a27e-81ab0819b66b.png">

<img width="229" alt="Screen Shot 2022-06-23 at 1 54 57 PM" src="https://user-images.githubusercontent.com/87138876/175294829-c7fc9ec5-f803-48e6-8a25-388554264941.png">

This JetBrains style guide page on their[ dropdown UI](https://jetbrains.design/intellij/controls/drop_down/) doesn't provide exact specs on heights/colors, but does provide some guidance on their dropdown UI. Let me know if you need further guidance/designs to better align our auto-complete component to the JetBrains native UI. 

Similarly, our contexts dropdown is the only un-stylized web component in our plugin, which makes it stand out quite a bit or comes across as "missed". Happy to provide mockups to stylize the contexts menu to align more closely to JetBrains UI. Please let me know if this would help, or whether there were any technical constraints to stylizing this dropdown. 

<img width="551" alt="Screen Shot 2022-06-23 at 2 13 28 PM" src="https://user-images.githubusercontent.com/87138876/175296053-01898bb7-0414-4df2-a19c-5b8cb127cca7.png">

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
