### ISSUE TITLE
JetBrains: Handle invalid tokens gracefully

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#37685]
Think about the authentication token validation.
What happens if the auth token is wrong? What should happen? When should we notify the user about this? When to update this state?

Idea: check it at each "Find on Sourcegraph" window open. If the connection fails, clear the search result and preview UIs. Offer a quick link to the plugin Settings and to Sourcegraph settings on the website.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
