### ISSUE TITLE
unused site setting git.cloneURLToRepositoryName

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#3768]
The documentation for this setting is 

> JSON array of configuration that maps from Git clone URL to repository name. Sourcegraph automatically resolves remote clone URLs to their proper code host. However, there may be non-remote clone URLs (e.g., in submodule declarations) that Sourcegraph cannot automatically map to a code host. In this case, use this field to specify the mapping. The mappings are tried in the order they are specified and take precedence over automatic mappings.

However, I do not see anywhere in our codebase we actually read this setting. We should remove this field. cc @sourcegraph/core-services to discuss.

**Comment by unknwon** [comment]
If I'm looking at the correct configuration [`git.cloneURLToRepositoryName`](https://docs.sourcegraph.com/admin/config/site_config#git-cloneURLToRepositoryName), looks like it's still being used, call stack (bottom up):

`conf.Get().GitCloneURLToRepositoryName`:

https://github.com/sourcegraph/sourcegraph/blob/87e0033cd6b74f99a4aadb610a7eb0226bd495fe/internal/conf/reposource/custom.go#L31-L33

`cloneURLResolvers`:

https://github.com/sourcegraph/sourcegraph/blob/87e0033cd6b74f99a4aadb610a7eb0226bd495fe/internal/conf/reposource/custom.go#L51-L53

`reposource.CustomCloneURLToRepoName`:

https://github.com/sourcegraph/sourcegraph/blob/87e0033cd6b74f99a4aadb610a7eb0226bd495fe/cmd/frontend/graphqlbackend/git_tree_entry.go#L136-L138

GraphQL layer: https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24%4087e0033+file:%5Ecmd/frontend/graphqlbackend/+reposourceCloneURLToRepoName&patternType=literal

**Comment by unknwon** [comment]
I think this was a false positive, closing.
