### ISSUE TITLE
JetBrains: Make icons consistent in Sourcegraph menu

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#37692]
## Context

We have this in the context menu:
![image](https://user-images.githubusercontent.com/2552265/175523713-526f9d83-be28-4d4f-9832-92ee94f30e7e.png)

And this on the action palette:
<img width="1084" alt="CleanShot 2022-06-24 at 13 16 17@2x" src="https://user-images.githubusercontent.com/2552265/175523989-08b3fa9b-8046-4fe6-bacf-0a86f3e27855.png">

## Problem

1. It looks weird that some context menu items have an icon while others don't.
2. The icon on the sub-items actually adds more clutter than value.

## Solution

Probably the best solution would be to have the icon only for the main context menu item, and no icon for the sub-items.
But the actions on the action palette are loaded from the same source as for the context menu, and we want the icons in the action palette. So not sure if we can remove the icons from the context menu sub-items but not from the action palette items.

If we can't do that, then just add the missing icon to the sub-item, which solves problem no. 1.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by vdavid** [comment]
GitHub couldn't solve this that nicely either:

![CleanShot 2022-06-30 at 13 46 50@2x](https://user-images.githubusercontent.com/2552265/176669779-b80cdd79-6e6c-4a6f-9d5b-6f14625bdc24.png)

But what we could do is **use a grayscale icon instead of the colorful one** to blend in better with the JetBrains UI. What do you think @jjinnii? I've had this in mind subconsciously for a long time because the very colorful icon stands out for me too much from the IDE. Even worse, our updated logo is even brighter.

**Comment by vdavid** [comment]
(We have a [monochrome logo](https://handbook.sourcegraph.com/departments/engineering/design/brand_guidelines/logo/#one-color-logos) which I haven't found an svg file for, but we probably have it somewhere. We could color this dynamically for dark/light themes.)

**Comment by vdavid** [comment]
@jjinnii what do you think about using the monochrome logo?
I think we can do three things:
a.) Use the monochrome logo for menu items (then I'd be comfortable with using it in many places without cluttering the UI too much)
b.) Use the colorful logo only for the 1–2 main items (I'd also be comfortable with this)
c.) Keep the color logo and use it for all our menu items (I think this stands out too much from the UI—to me this behavior has a shady / low quality feel to it)
d.) Keep using the color logo only for _some_ (~5) menu items (I think this is the worst solution as there's no real logic behind where's a logo and where isn't)

I'm undecided between options A and B.
What would help me decide is to get a designer's point of view on how well the monochrome logo functions, and how much we as a company want to use it.
I expect that your suggestion between Options A and B will be "B", but I wanted to double-check, and also ask if perhaps you have a different idea altogether.

**Comment by vdavid** [comment]
+1 argument in favor of Option A (and Option C): if we keep the icons in the context menu then they'll also appear with the icon in the Find Action palette (these are tied together):

![Image](https://user-images.githubusercontent.com/2552265/178657505-ba4d4678-a306-4460-b2c1-c769fdba018d.png)

In case of Option A, we could, of course, keep the colorful icon in the popup header and only use the monochrome one in the context menu (and Find Action palette).
