### ISSUE TITLE
Document Markdown syntax

### ISSUE THREAD

**Issue by siddharthab** [sourcegraph/sourcegraph#3769]
#### Feature request description

Markdown rendering requirements (syntax support and styling) can vary between organizations. It will be nice for site admins to be able to plug in their markdown engines.

#### Is your feature request related to a problem? If so, please describe.

The current markdown rendering engine is a black box to users, and it is difficult to guide users into how to configure their Markdown editors such that they support the same syntax as what Sourcegraph uses. Even if we know it's [blackfriday](https://github.com/russross/blackfriday), for instance, it is not entirely clear which options are enabled.

#### Describe alternatives you've considered.

Asking users to import their commits into Sourcegraph to check their rendering.

#### Additional context

None.

**Comment by dadlerj** [comment]
Thanks @siddharthab! This would actually be a bit complex today, I believe we're doing rendering on both the backend and frontend, depending on the source of the markdown content. 

Can you share any example markdown where the renderer is failing today? Or is it just on custom syntax internal to your org?

**Comment by siddharthab** [comment]
Thanks for responding Dan.

The main problem is that Markdown syntax is not really standard. And each rendering engine supports its own flavor. Without knowing which engine Sourcegraph is using, and with which options, it will be difficult to write any Markdown documents which render nicely in Sourcegraph.

If having custom rendering engines is hard, maybe Sourcegraph can support a more popular flavor of Markdown. In either case, Sourcegraph should provide a guide to supported Markdown syntax.

**Comment by sqs** [comment]
Our doc page at https://docs.sourcegraph.com/user/markdown is blank, and this is obviously a problem. We need to write that up. Assigning to @christinaforney who also just mentioned this.
