### ISSUE TITLE
Code discussion attached to wrong line

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#377]
In a code discussion thread (private link), my comment https://sourcegraph.sgdev.org/github.com/sourcegraph/about/-/blob/projects/acls.md#tab=discussions&threadID=133&commentID=298 was intended to be posted on the line beginning `* It would be simpler`, but it got posted ~9 lines above that.

Why would this happen? What kind of auto-repositioning logic is there right now?

Possible factor: I posted it on slow airplane wifi. It is possible that between the time I opened the page and submitted the comment, the `master` branch changed.

(Note: The code discussion should've occurred on Sourcegraph.com, not sgdev, but ignore that for this issue.)

**Comment by slimsag** [comment]
Yeah, this looks like a case of the page being stale when you commented. This is a bug, you should be commenting on the revision of the code your browser is aware of not `master`.

To prove this was the case, I looked at this diff which shows 9 lines added above where your comment was placed: https://github.com/sourcegraph/about/commit/f343b1878ffe97f9ce336f54ac38f9ad27545393#diff-4529bc67559f95c922b15578691458a1

**Comment by slimsag** [comment]
(This is still a bug, as I said above :) )
