### ISSUE TITLE
VSCE: Add open-vsx publishing step to auto release pipeline

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#37704]
We have recently published VSCE to [Open VSX](https://open-vsx.org/extension/sourcegraph/sourcegraph)

Dev exp team helped create an access token using the @soucegraph-bot account for future vsce release to the open vsx registry. We should add the publishing step to our existing vsce auto release pipeline 

Ref: https://sourcegraph.slack.com/archives/C01CSS3TC75/p1656045575021719

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
