### ISSUE TITLE
insights: deprecate mentions of `metadata`

### ISSUE THREAD

**Issue by leonore** [sourcegraph/sourcegraph#37719]
metadata was added as something we thought we might need, but we don't actually use it. 

- [x] * remove `metadata` fields in structs
- [x] * remove db calls

 remove the db table to be done in separate ticket

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
