### ISSUE TITLE
JetBrains: Clicking text in the search box has no effect

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#37722]
@jjinnii reported: "I’m unable to click to or highlight on earlier parts of my search query in the search bar. The only way I can get to the start/middle of my search query is to use my keyboard arrow keys. Here’s a [Loom](https://www.loom.com/share/3351c4628a0149fb8e03a6f2cae05950) to show what I mean."

David: It's the same behavior for me. I could also reproduce this in the standalone version on latest `main`. @taras-yemets, if you have time to look at this, wink-wink :)

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
