### ISSUE TITLE
UX for ’feeling lucky’ search mode.

### ISSUE THREAD

**Issue by almeidapaulooliveira** [sourcegraph/sourcegraph#37729]
**This proposal was _deprecated_. I'm closing this issue and following up on this new issue.**

# Proposal [DEPRECATED]

### Concept 
In a **Code Intelligence Platform,** this proposal envisions a paradigm representing a conversation with the user. Where the platform's Intelligence communicates and interacts, suggesting more efficient ways to find what he is looking for, adding value to the experience.

The platform's Intelligence is backed by innovative technology, under development by the Search product team, codenamed 'lucky search.' It analyzes the user's queries and suggests corrections, more efficient ways of searching for code, and even queries that users never imagined. 

As a result, it improves first-time users' success and existing customers' workflow, making it easier for them to search without needing too much syntax.

### Goal 
**Create a space for clear communication with users**, educating and assisting them in performing better queries and succeeding with their jobs. It is a significant opportunity to create a meaningful conversation with users with the premise to be more than a search; to be a Code Intelligence Platform.

## Communication space
_To elaborate description_
<img src="https://user-images.githubusercontent.com/64257673/175472132-01d636dd-a64a-41d6-b55a-76009bcda5f8.png" width="600"/>

### Cards
Inside the **Communication Space**, the card component is a generic element with multiple functions.

The card's purpose is to have an intuitive and predictable layout with a clear information hierarchy: header, content, and actions. It is distinct from other elements we use in the search (notices, info, etc.). It intends to convey interactivity and usefulness in a meaningful way.

<img src="https://user-images.githubusercontent.com/64257673/175474620-43b7e49c-f7c7-4a90-99a4-b4abfd911797.png" />

## Prototype
[The interactive prototype](https://www.figma.com/proto/GikUoxdCrRTmbQpiu72AUi/Frontend-scaffolding-for-'Feeling-Lucky'-search-mode?node-id=1386%3A458&scaling=scale-down-width&page-id=1345%3A458&starting-point-node-id=1386%3A458) is a playground around the experience that we're building. Although the prototype looks very polished (high-fidelity), it is just a concrete representation of an idea — an open hypothesis for all directions, both divergent and convergent. You can find the design elements in [this Figma project](https://www.figma.com/file/GikUoxdCrRTmbQpiu72AUi/UX-for-%E2%80%99feeling-lucky%E2%80%99-search-mode.?node-id=338%3A0).

https://user-images.githubusercontent.com/64257673/175559784-35fdd2db-39a1-4a85-9046-07355cd4dcd7.mp4

#### Evidences of a problem:
- https://sourcegraph.slack.com/archives/C0W2E592M/p1652914114016519</div>

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.
