### ISSUE TITLE
Display total KPIs in the List Page

### ISSUE THREAD

**Issue by danielmarquespt** [sourcegraph/sourcegraph#37750]
Related with [RFC 692](https://docs.google.com/document/d/1f873V5UiZkpymkYd6UXqtcknriyFyZ7bXex19ce9flY/edit) 

We need to display total metrics in the List page of Batch Changes so that the users get a better grasp of how many BC they've ran and how impactful they were to their organisations

![Image](https://user-images.githubusercontent.com/7814431/176223647-5d67de59-d6ac-47de-ba01-12f83035b2bb.png)

**Design:**
https://www.figma.com/file/vW0D7Os7vkQ0eFNPXhcqas/%F0%9F%A6%A1-Batch-Changes-MAIN-%5BWIP%5D?node-id=254%3A7415

**Comment by adeola-ak** [comment]
@sourcegraph/batchers is the multiplier that is mentioned in the tooltip an actual number in a setting somewhere? All I have found is this from analytics:

![Screen Shot 2022-09-26 at 2 58 35 PM](https://user-images.githubusercontent.com/67931373/192358037-1cd0298e-2522-443c-bc29-d90fb7c10fc9.png)

which the number resets on refresh and doesnt appear to be stored anywhere
