### ISSUE TITLE
Add-to-workspace-recommendation notification spam

### ISSUE THREAD

**Issue by digitarald** [sourcegraph/sourcegraph#37772]
Latest Source Graph extension for VS Code.

#### Steps to reproduce:

1. Have Source Graph extension installed

#### Expected behavior:

No random notifications without context. Following [VS Code's UX guidelines for notifications](https://code.visualstudio.com/api/ux-guidelines/notifications):

> DO: Respect the user's attention by only sending notifications when absolutely necessary

#### Actual behavior:

Briefly after launching VS Code (and not even using SG) I get a notification that smells like a growth hack:

![image](https://user-images.githubusercontent.com/8599/175988902-5c704e45-c5ca-4481-bb9c-c92b2d38376d.png)

**Comment by ryankscott** [comment]
Hi @digitarald thanks for flagging this, we missed this from your UX guidelines. We'll be shortly rolling out an update that changes this behavior.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
