### ISSUE TITLE
Code Insights: Series query field has wrong line height/padding values

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#37785]
If you go to the code insights creation UI there will be a series query field that doesn't look good with the `editor: codemirror6` experimental flag. This is happening because codemirror changes the layout of the editable field and current padding and line-height values have been written only for the monaco-like field's layout. 

<img width="548" alt="Screenshot 2022-06-27 at 15 34 05" src="https://user-images.githubusercontent.com/18492575/176021475-f35fcc89-6c54-4841-88a9-21b13f2f4769.png">

Possible solution
Change (increase) top and bottom paddings for the field root element (8px)

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by Joelkw** [comment]
@vovakulikov  do we own regressions for codemirror work or do we need to just flag this to the search team?

**Comment by vovakulikov** [comment]
@Joelkw I'm not sure who is a proper owner of this actually. In my opinion, we do need to have this query-like component inside of wildcard so the @sourcegraph/frontend-platform should have this component in their scope, from the other side Sourcegraph search team and @fkling does a lot of things in terms of migration from Monaco to CodeMirror. 

I ended up with a quick fix here https://github.com/sourcegraph/sourcegraph/pull/38183/commits/2e24c373e60965a333f2ad54ceee9621e484fbe0 so this issue will be closed soon

**Comment by fkling** [comment]
@Joelkw, @vovakulikov I'm happy to take care of any regressions related to CodeMirror.

**Comment by Joelkw** [comment]
Thanks @fkling ! Un-assigning the insights teammates so I don't forget about this.

**Comment by vovakulikov** [comment]
@fkling I'm about to close this since it was fixed with https://github.com/sourcegraph/sourcegraph/commit/2e24c373e60965a333f2ad54ceee9621e484fbe0
