### ISSUE TITLE
[Design] Review read-only mode on small screens

### ISSUE THREAD

**Issue by almeidapaulooliveira** [sourcegraph/sourcegraph#37797]
## Context
Notebook's experience editing on small screens isn't perfect. The team discussed having a read-only mode activated by default on small screens since Blocks don't really make sense in read-only mode. 

Notebooks already render a read-only mode for users who do not have edit permissions.

## Purposes of design review
- Make sure that that are no inconsistencies in the UX.
- If needed, suggest minor UI improvements.

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by almeidapaulooliveira** [comment]
Cc: @novoselrok

**Comment by novoselrok** [comment]
I think we can use these changes for all screen sizes, not just the smaller ones. (Although small screens are the most problematic for reading).
