### ISSUE TITLE
buildchecker-history: slack reports not delivering

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#37807]
I think we're supposed to get buildchecker reports weekly in #ci-reports and #dev-experience, but right now it looks like neither are getting reports :( Relevant workflow: https://github.com/sourcegraph/sourcegraph/actions/workflows/buildchecker-history.yml

**Comment by bobheadxi** [comment]
@burmudar assigning you because you volunteered during today's team sync :) Let me know if you have any questions!

**Comment by burmudar** [comment]
Awesome, I'll dig into this tomorrow 🫡
![image](https://user-images.githubusercontent.com/1001709/176551115-5a5e7840-c6a5-46ef-aee4-de2bf78d2a0d.gif)
