### ISSUE TITLE
Write down plan for removing GraphQL from Free Tier

### ISSUE THREAD

**Issue by ryphil** [sourcegraph/sourcegraph#37806]
**_Description_**
Today, any user can leverage the Sourcegraph API. This has led to several lost deals as customers can get the full value of Sourcegraph without paying enterprise fees. Recently, there was an executive decision to remove the API functionality from the free tier to avoid further closed/lost deals. 

**_Open Questions_**
- What is the most efficient way technical solution to prevent free users from using the API? 
- Do we allow teams <10 in size to use the API? Or only paying enterprise customers? 
- Do we want more than one tier (i.e. allow customers to use 100 calls before access is removed)? Or simply remove all free usage?

**_Definition of Success_**
A user should not be able to use the Sourcegraph API unless they have an enterprise key. 

Additional context can be found in the [Slack Thread](https://sourcegraph.slack.com/archives/C024S6JG7B6/p1654712273723879)

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.

**Comment by unknwon** [comment]
We use exact same set of GraphQL APIs for both our own web app and users, as long as this doesn't change, it doesn't make any difference in terms of removing the ability to hit the GraphQL APIs, because either our web app breaks, or users can just look at the network tab and find out which API to call.

**Comment by unknwon** [comment]
x-post the initial draft doc: https://docs.google.com/document/d/1SgDt6qNVWGmFFqyhdH8pacRBCNWUIi6gpsHHuYR1yiU/edit#

**Comment by unknwon** [comment]
@ryphil Do you want to close this issue and create another issue about limiting access token creation or re-purpose this same issue?

**Comment by unknwon** [comment]
The conclusion is that we are going to remove access token creation from OSS and the Free version (i.e. require a valid license).

**Comment by unknwon** [comment]
Issue for the actual eng work: https://github.com/sourcegraph/sourcegraph/issues/38267
