### ISSUE TITLE
Update link in dotcom 'get started'

### ISSUE THREAD

**Issue by ryphil** [sourcegraph/sourcegraph#37805]
In support of the dotcom wind-down, we need to adjust the link of the 'Get Started' button (Purple button in screenshot below) to point to https://about.sourcegraph.com/get-started/self-hosted. This button appears in the nav-bar of all pages for unauthenticated users. This does not appear for authenticated users. 

![Image](https://user-images.githubusercontent.com/2636675/176095788-8230680b-6932-46da-a46a-e765f4cf7b57.png)

Timeline: This change should be merged on Thursday, June 30th to align with the blog post. Per Alex, it does not need to be the exact same timing as the blog, as long as it is on Thursday.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.

**Comment by unknwon** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IAM-627aebcc9f8b7c00128a8ab6/issues/sourcegraph/sourcegraph/37805?planning-poker) with ZenHub @kopancek @miveronese @pjlast
