### ISSUE TITLE
devx: send sg analytics to Honeycomb

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#37810]
We currently send sg analytics to OkayHQ - we should consider tee-ing them to Honeycomb, or switching them to a Honeycomb format entirely

https://ui.honeycomb.io/sourcegraph/environments/sg/send-data

**Comment by jhchabran** [comment]
@bobheadxi isn't this at least partially done with https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/268c5357ef3241b5c6d9285414e2d57016039f73 ? Though we need a way to access the honeycomb token to be able to have this working properly.

**Comment by bobheadxi** [comment]
I'll open a new issue for tokens

**Comment by bobheadxi** [comment]
Closed by https://github.com/sourcegraph/sourcegraph/pull/38889
