### ISSUE TITLE
JetBrains: Search selection should work without a "selection"

### ISSUE THREAD

**Issue by ryankscott** [sourcegraph/sourcegraph#37817]
At the moment this is disabled if you have not highlighted text. Unsure if this should work by using the line that you're currently on as the input.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by vdavid** [comment]
https://github.com/sourcegraph/sourcegraph/issues/38003 is a newer duplicate but it has more info, so closing this one.
