### ISSUE TITLE
JetBrains: Image in the readme is broken in marketplace

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#37823]
This one:
![CleanShot 2022-06-28 at 11 35 42@2x](https://user-images.githubusercontent.com/2552265/176146448-adaffc12-9ebd-4242-abd5-08cc63d9b6eb.png)

Probably just remove the icon.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
