### ISSUE TITLE
Use a single name for scopes & filters consistently

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#3782]
I'm opening this ticket because I think new users of Sourcegraph might get confused by the inconsistent naming of the feature called "scopes" or "filters".

Example: on `/search` it's called "scopes" (`Edit search scopes`, `Add search scopes for quick filtering`, ...). In the "User settings" too. But when looking at search results, the scopes show up next to `Filters:`.

I know that scopes technically are filters and the other way around, but from a new user's/admin's perspective it would be great if there was just one name for the same thing everywhere.

If these two *are* distinct features, never mind, we shouldn't use a separate name for them. But maybe we should make that distinction clearer.

**Comment by sqs** [comment]
This is indeed confusing. We have several semi-overlapping concepts:

- scopes
- filters
- dynamic filters/suggestions
- search keywords/tokens/operators

And we don't use consistent language for these.

**Comment by sqs** [comment]
[RFC 184 REVIEW: product terms and naming debt](https://docs.google.com/document/d/1SHky6nodPs1w_zRXz24jB2nq5LbMCJl1u7hcLTGHDL8/edit) does this

**Comment by camdencheek** [comment]
Closing as stale since "scope" is no longer a word used in the product
