### ISSUE TITLE
Review/update/create playbooks for common IAM issues and debugging

### ISSUE THREAD

**Issue by miveronese** [sourcegraph/sourcegraph#37835]
It was noted,[ in the Repository Permissions Landscape doc](https://docs.google.com/document/d/1UTdablpNpSLjlcxOHOKMj7UTa3Ru31TKkX-uW3pcqpU/edit), that we are missing playbooks for common issues and debugging that could be useful for CE and support engineers.

Examples:
- Ensure the configuration is correct
- Inspecting the state of user account in question, e.g. verified emails, permissions syncing information
- Inspecting the information of repositories in question, e.g. permissions syncing information

Related issues (they can be used as reference for a FAQ page, for example):

- https://github.com/sourcegraph/sourcegraph/issues/37103
- https://github.com/sourcegraph/sourcegraph/issues/37102
- 
The goal here is:
- review the playbooks that we already have making sure the instructions are correct and updating them if necessary
- add missing playbooks

This issue should be updated (or, depending on the size of the effort, broken down into other issues or different PRs) as playbooks are added and updated.

/cc @sourcegraph/source

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.

**Comment by unknwon** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IAM-627aebcc9f8b7c00128a8ab6/issues/sourcegraph/sourcegraph/37835?planning-poker) with ZenHub @kopancek @miveronese @pjlast
