### ISSUE TITLE
Add 5 changeset gate on SSBC

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#37834]
A user without an Enterprise License is able to run more than 5 changesets when using batch changes server-side. It appears that there is no limit/gate set for users without a license when using SSBC.

Add logic to prevent users without an Enterprise License (Free plan) from running more than 5 changesets when using SSBC.

**Comment by Piszmog** [comment]
P0?

**Comment by malomarrec** [comment]
Just checking: this didn't make it in the release?

**Comment by Piszmog** [comment]
@malomarrec Correct, this did not make it into the release. There is a draft PR opened #38490

**Comment by malomarrec** [comment]
@dmarques @Piszmog what's left to do to get this in the next release?

**Comment by Piszmog** [comment]
@malomarrec Just get the PR merged
