### ISSUE TITLE
Gitlab webhooks cannot decode timezone offset

### ISSUE THREAD

**Issue by NiklasRosenstein** [sourcegraph/sourcegraph#37842]
- **Sourcegraph version:** 3.41.0
- **Platform information:** Ubuntu 20.04, deployed with Docker

#### Steps to reproduce:

1. Set up Batch changes
2. Set up a System hook for Merge events in Gitlab (Admin > System Hooks)
3. Send a merge request event

#### Expected behavior:

The webhook should succeed and source graph should update the status of merge requests associated with the repository in open Batch changes.

#### Actual behavior:

<img width="1271" alt="image" src="https://user-images.githubusercontent.com/1318438/176201655-15c88923-b1fc-4888-be64-ecc77f377a03.png">

```
unmarshalling payload: unmarshalling typed event: parsing time "2022-06-28 16:08:11 +0200" as "2006-01-02 15:04:05 MST": cannot parse "+0200" as "MST"
```

It appears to me that Sourcegraph cannot decode the `+0200` timezone offset.

**Comment by BolajiOlajide** [comment]
Hello @NiklasRosenstein ,

Thanks for raising this issue. We're currently looking into this and will have a fix for it out soon.
Thanks

**Comment by NiklasRosenstein** [comment]
Thanks, it seems to work with 3.42.0 :)
