### ISSUE TITLE
Notebooks social preview

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#37848]
Provide a social preview that will show when sharing a notebook

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by novoselrok** [comment]
Here is a quick mockup that shows the basic information about a notebook that we could show:

![notebook-preview-2](https://user-images.githubusercontent.com/6417322/176213600-43d715c5-4278-481d-8930-aaa54c23dbed.png)

**Comment by benvenker** [comment]
Nice! My only comment is is this our font?

**Comment by novoselrok** [comment]
I'm not sure what "our" font is, I think we're using the system font stack, so we can't be exactly sure. We'll have to choose a specific font (e.g. from Google Fonts) that we want to use, otherwise, we can get weird results.

**Comment by almeidapaulooliveira** [comment]
Looking good @novoselrok, you gonna get me out of the job [🤣](https://emojipedia.org/rolling-on-the-floor-laughing/).

You're right, we use the system font and [Source Sans Pro](https://fonts.google.com/specimen/Source+Sans+Pro#standard-styles) on [Figma](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/%E2%9C%B3%EF%B8%8F-Wildcard-Design-System?node-id=5601%3A65477). 

I agree to choose a font to maintain consistency in the layout, I would follow with the [Source Sans](https://fonts.google.com/specimen/Source+Sans+Pro#standard-styles) (it's a Google font).
