### ISSUE TITLE
dev/sg: auto update can be very slow and annoying

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#37852]
Crude analytics indicates the process can be quite slow:

<img width="1138" alt="image" src="https://user-images.githubusercontent.com/23356519/176223048-e2c39e3f-9a16-4b9e-8a46-c8d7a3d8c232.png">

Anecdotally starting my day and being interrupted by an auto update is rather annoying 😆  @jhchabran do you think it might be possible to push this to be in the background?

**Comment by jhchabran** [comment]
Interesting, I'm curious how come it was slow? Yeah, we should def push it in the background then 🙏

**Comment by bobheadxi** [comment]
Maybe my internet is bad :(

**Comment by burmudar** [comment]
I've actually completely forgot to push more analytics. Submitted some of mine now!

Would there be some benefit in reminding users to submit their analytics ? Like when view the changelog "Have you made your fellow DevXer happy and submitted your analytics with `sg analytics submit` ?"

**Comment by bobheadxi** [comment]
I think ideally we will eventually be able to push analytics automatically on a regular basis
