### ISSUE TITLE
insights: validate pings for compute type insight

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#37866]
For v1 we need to ensure that we are capturing the following pings for compute type insight (in priority order)

1. count them as insights in overall count (critical count)
2. Add them as series to our view series counts table 
3. Hovers

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by vovakulikov** [comment]
@CristinaBirkel I think we can't tell it at the moment. We definitely aim to finish at least the first stage of compute insight integration on the dashboard page within this week, cc @unclejustin
