### ISSUE TITLE
insights: polling for backfilling insights does not stop on error

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#37862]
When loading an insights data for display the insight will poll for updated data and stop when it is no longer in a backfilling state.  If the API returns an error the polling does not stop and will continue to return errors.  Polling should stop when an error is received.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
