### ISSUE TITLE
insights: live preview for compute type insight

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#37867]
We need to add a live preview resolver and path for the compute type insight. Since for the v1 we are retrofitting our current API to support this type, this can be included in the searchInsightLivePreview [resolver](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/insights.graphql?L206) and fork based on a group by input value

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
