### ISSUE TITLE
git operations on megarepo don't work on dogfood

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#37872]
Git operations on the megarepo are failing. Example: https://k8s.sgdev.org/site-admin/repositories?query=megarepo

Error message from the page above: https://gist.github.com/coury-clark/955e4213ca43d725936515dd2a5bb4fe

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/search-core - the "team/search-core" label was applied to this issue.

**Comment by ggilmore** [comment]
https://lore.kernel.org/git/581c7ef2-3de4-eb8a-bfbb-d4bca3522a2d@github.com/T/

I don't understand all the details, but according to ^ there seems to be an unresolved bug related to this in git `2.36.1`. 

I believe this was introduced in https://github.com/sourcegraph/sourcegraph/commit/04c98ab493e0889394e2e60fb85e1a53225e5a35 (this techincally attempted to upgrade git to _any verison_ past `2.35.2`, which includes `2.36.1`.
