### ISSUE TITLE
PUBLISH Bulk Operation when working on imported changesets

### ISSUE THREAD

**Issue by BolajiOlajide** [sourcegraph/sourcegraph#37882]
When working with [`imported changesets`](https://k8s.sgdev.org/users/bolaji.olajide/batch-changes/test-imported?tab=bulkoperations&visible=3), users get the `PUBLISH` bulk operation when an imported changeset is selected, this always leads to an error because we don't allow publishing of imported changesets.

![CleanShot 2022-06-28 at 21 55 32@2x](https://user-images.githubusercontent.com/25608335/176286146-d8fae78f-3dec-4e2b-9826-c1d558a89531.png)

It might be better if we disable publishing when querying for available bulk operations on an imported changesets. 
Question, is how do we recognize imported changesets at the point where they're being displayed?

[Context - https://sourcegraph.slack.com/archives/CMMTWQQ49/p1656447528013549](https://sourcegraph.slack.com/archives/CMMTWQQ49/p1656447528013549)

**Comment by chrispine** [comment]
Also from that Slack thread: can we show greyed out actions instead of just not showing actions?

**Comment by chrispine** [comment]
P2?

**Comment by LawnGnome** [comment]
P1? 0.5-1d?
