### ISSUE TITLE
dotcom: set up Loki logging that properly ingests OTel logs as structured logs

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#37901]
Right now in Loki the logs are somewhat mangled due to a weird `stderr F` prefix on all messages: https://sourcegraph.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-sourcegraph-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bapp%3D%5C%22sourcegraph-frontend%5C%22%7D%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D

We should implement some kind of forwarding that allows Loki to treat these natively as structured logs

**Comment by davejrt** [comment]
@bobheadxi is this still an issue? Is there more context on how we're currently forwarding logs we can use to work on this if required?

**Comment by bobheadxi** [comment]
Yes, we currently forward logs via grafana-agent: https://sourcegraph.sourcegraph.com/github.com/sourcegraph/deploy-sourcegraph-cloud/-/blob/configure/grafana-agent/grafana-agent.ConfigMap.yaml

It doesn't work very well, and doesn't ingest the logs properly as JSON

We want to explore sending logs via otel-collector instead

**Comment by bobheadxi** [comment]
Grafana Cloud for dotcom has been spun down, we no longer use it and this issue is no longer valid
