### ISSUE TITLE
s2: set up frontend/backend Sentry error reporting

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#37900]
s2 == sourcegraph.sourcegraph.com until we find a better name :)

This error reporting should just be via our logging integration

**Comment by bobheadxi** [comment]
Set up the Sentry project and config but do not see any errors coming in - TODO validate

**Comment by jhchabran** [comment]
@valerybugakov told me that having sentry errors for the frontend from S2 would really be useful as this type of instance is our main target business wise.

**Comment by bobheadxi** [comment]
Hmm, I've had the following set up for a while: 

```
   "sentry": {
      "backendDSN": "...",
      "codeIntelDSN": "...",
      "dsn": "..."
    },
```

but there are still no events in the project: https://sentry.io/organizations/sourcegraph/issues/?groupStatsPeriod=auto&page=0&project=6583153&query=is%3Aunresolved&statsPeriod=14d

**Comment by bobheadxi** [comment]
Events are live - closing this as done!
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/23356519/186778563-310ed5bb-ccca-43b2-9f7d-e988e40fdbfa.png">

cc @valerybugakov @jhchabran
