### ISSUE TITLE
Search query builder omits useful result types

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#3790]
The search query builder shows this:

![image](https://user-images.githubusercontent.com/3173176/57098509-1e116f80-6ccf-11e9-9d3a-438c4c0165eb.png)

It is missing:

- `type:file` (only give me code matches, different from "default" which includes more than just code matches)
- `type:repo` (only give me repo matches)
- `type:path` (only give me filepath matches

Additionally, I find it strange that `Code (default)` returns ALL result types. I would expect:

- `Code` -> ONLY code matches
- No selection -> ALL result types

Reported by https://app.hubspot.com/contacts/2762526/company/407948923

**Comment by attfarhan** [comment]
Query builder is feature flagged off by default and will be removed, so closing.
