### ISSUE TITLE
otel/trace: forwarding web app OTel traces

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#37907]
We have several options here:

- some kind of endpoint in frontend that can forward OTel traces to the configured backend, e.g. an OTel collector instance (ideal)
- otherwise, we have to make OTel collectors available directly, e.g. as described in https://www.honeycomb.io/blog/opentelemetry-browser-instrumentation/ 
- or the web app has to send traces directly to e.g. Honeycomb

Notes: https://docs.google.com/document/d/1pYgSqJUE9M0_LZFUBzL-5nRTpmbMqXsWCUVU32J-AEo/edit#

**Comment by olafurpg** [comment]
> otherwise, we have to make OTel collectors available directly, e.g. as described in https://www.honeycomb.io/blog/opentelemetry-browser-instrumentation/

I implemented the client-side component for this approach in the PR
https://github.com/sourcegraph/sourcegraph/pull/37843 My concern with this approach is that opentelemetry adds 36kb to the bundle size, which is IMO a lot if we only want to measure a few specific components (in particular, the performance of loading the blob page, which is currently slow due to browser rendering that we can't measure from the server side). 

For our needs I'd be happy with using the existing function `TelemetryService.logPageView('Blob', {elapsedTime: MILLISECONDS})`. Would it be possible to forward those events to honeycomb (or any other product) that would render the MILLISECONDS on a dashboard? We just need a way to confirm that our blob page optimizations are working as expected.

**Comment by valerybugakov** [comment]
>  if we only want to measure a few specific components (in particular, the performance of loading the blob page, which is currently slow due to browser rendering that we can't measure from the server-side). For our needs I'd be happy with using the existing function `TelemetryService.logPageView('Blob', {elapsedTime: MILLISECONDS})`

The Frontend Platform team doesn't have the capacity to implement a generalized performance monitoring solution this quarter. Still, it would be nice to start with something that can naturally scale to other parts of the application to give us full-featured performance monitoring data eventually. With the focus on core workflows, other teams would need similar metrics to optimize and monitor their parts of the product. Any tool chosen would negatively affect the bundle size; we just have to decide which is the lesser evil.

A note on the `TelemetryService`. IIRC it's used primarily for product analytics event logs. It might be easy to patch this pipeline to forward metrics like `elapsedTime` to Honeycomb through our backend, however, I'm not sure if we want to mix product analytics with observability. 🤔 

Curious what @sourcegraph/frontend-platform-devs think about this.

**Comment by bobheadxi** [comment]
> For our needs I'd be happy with using the existing function TelemetryService.logPageView('Blob', {elapsedTime: MILLISECONDS}). Would it be possible to forward those events to honeycomb (or any other product) that would render the MILLISECONDS on a dashboard? We just need a way to confirm that our blob page optimizations are working as expected.

at the moment we don't have any intention of extending support for custom events in the backend - we want to lean heavily towards just logging (structured events) and tracing. _However_, perhaps we can extend `logPageView` with an option that says "emit this as a structured log event"? That would then be able to go to our structured events backend (e.g. https://github.com/sourcegraph/sourcegraph/issues/37958 )

cc @vrto @jhchabran

**Comment by valerybugakov** [comment]
@bobheadxi, going to discuss internally with the team and come back here 👍

**Comment by valerybugakov** [comment]
We're going to [pilot OTel instrumentation](https://sourcegraph.slack.com/archives/C03N0HGN069/p1658293744294689), and we would like [to integrate it into our backend OTel pipeline](https://github.com/sourcegraph/sourcegraph/issues/37907). I've added a couple of questions to [our observability sync doc](https://docs.google.com/document/d/1pYgSqJUE9M0_LZFUBzL-5nRTpmbMqXsWCUVU32J-AEo/edit#) related to the issue. Let's chat there!

**Comment by bobheadxi** [comment]
This tunnel would simply forward requests to e.g. `/-/debug/otlp/traces`, which would determine where to forward requests based on https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md

I would advise `/-/debug/otlp/traces` instead of just `/-/debug/otlp` to avoid having to unmarshal incoming requests to determine what kind of payload they have (we could implement other parts of the OTLP spec in the future, like metrics)

**Comment by jhchabran** [comment]
Hey folks, @valerybugakov @bobheadxi, it seems we haven't touched this in a long time, what's the status here?

**Comment by valerybugakov** [comment]
@jhchabran, I'd say we're happy on the client side with the experimental integration that's currently in place. We can close this issue as done and continue improving the current setup in follow-up issues. @bobheadxi, what do you think?

**Comment by bobheadxi** [comment]
This was implemented in https://github.com/sourcegraph/sourcegraph/pull/39401 and https://github.com/sourcegraph/sourcegraph/pull/39453 - closing as done!
