### ISSUE TITLE
codeintel: investigate relevant places to add automatic tracing instrumentation

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#37905]
https://opentelemetry.io/registry/?language=go

**Comment by jhchabran** [comment]
Made some progress with `otelsql` 👇  

![CleanShot 2022-07-22 at 15 04 22](https://user-images.githubusercontent.com/10151/180445583-351515c8-d759-4cb0-a43d-771d1dfdf456.png)

The good news is that it's working, the bad one is that I had to patch the lib as is caches the tracer as soon as it instanciates the DB and never reach out the global tracer again. 

That should be not that hard to polish though and I could submit a PR upstream.

**Comment by jhchabran** [comment]
Fixed by https://github.com/sourcegraph/sourcegraph/pull/39300
