### ISSUE TITLE
User-centric perms syncing in parallel

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#37918]
Currently, we use a single thread to process both user-centric and repo-centric permissions syncing, but there is an opportunity that given user-centric syncing uses different OAuth tokens for each user, it is reasonable to have a config option for the number of user-centric permissions syncing tasks being processed in parallel.

---

Derived from https://github.com/sourcegraph/customer/issues/993#issuecomment-1165365539

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.
