### ISSUE TITLE
Compute insights v1 design

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#37923]
[Figma](https://www.figma.com/file/DqZHetdfqHSVzzWtyfjOmr/?node-id=246%3A11)

### Objective
Design a minimal version of Compute in Code Insights that we can deliver in this iteration.

### Process

- [x] Align on the MVP scope
- [x] Alicja to update the designs for Creation UI

---

### Scope
As per meeting on Tue, Jun 28 ([notes](https://docs.google.com/document/d/1EFFB8FmVtatq20jm3xwfl9XXMHLDggqb2C9xtMuhTN4/edit#bookmark=id.2fot4rlqle8r)):
- Separate form – separate “insight type” – the “selection page” needs changes as well – 
- One path only – manually defined series
- Current point in time only 
- Sorting works however it currently works / no modifications 
- Bar graphs (which group if multiple series) only (no stacked bar, no line, no pie chart) – https://www.figma.com/file/DqZHetdfqHSVzzWtyfjOmr/Compute-x-Insights-%5BWIP%5D?node-id=1651%3A15171 
- No “other” bar – only show partial results is fine
- Not taking raw query – we should offer the pill buttons – but we’ll get to this last; if search product can help us with that – 
  - @coury-clark will raise the question about the parsing aspect)
- Feature - flagged off by default 
- @AlicjaSuska  will prepare the above in a figma
- @coury-clark  not sure if pings will be automatic 
   - Priority – count them as insights in overall count (critical count)
     - Add them as series to our view series counts table 
     - Hovers
   - Or call out the gaps

**Comment by felixfbecker** [comment]
I'm changing this issue to emcompass only the initial design, since we already have the the tracking issue https://github.com/sourcegraph/sourcegraph/issues/37857 to track all subtasks/implementation.

Please close to indicate when the design is done/approved/ready for dev 🙂

**Comment by AlicjaSuska** [comment]
All comments in Figma resolved, ready for dev.
