### ISSUE TITLE
Rust: SCIP support

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#37932]
rust-analyzer currently only supports LSIF, and this implementation doesn't reliably support cross-repo navigation. We should send a PR to rust-analyzer to add SCIP support with proper cross-repo support.

**Comment by tjdevries** [comment]
associated PR: https://github.com/rust-lang/rust-analyzer/pull/12976

**Comment by tjdevries** [comment]
PR Was merged! Will update our rust actions to use new scip commands
