### ISSUE TITLE
Code Insights: `getInsights` called multiple times on dashboard

### ISSUE THREAD

**Issue by unclejustin** [sourcegraph/sourcegraph#37953]
On larger screens `getInsights` is called multiple times with the same variables. Meaning it loads the exact same thing multiple times. I suspect something is off with how we are lazy loading inisghts.

![PixelSnap 2022-06-29 at 11 51 55](https://user-images.githubusercontent.com/1855233/176492475-4535adf6-b9c5-41f6-9918-2d2c3c3a4589.png)

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
