### ISSUE TITLE
log: send sampled log events -> otel-col -> Honeycomb

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#37958]
Each log entry could just be a standard Honeycomb event. We might need to adjust trace context fields to fit into Honeycomb's trace model.

Alternatively, there might be some way to do this on an external log sink side, but the above seems easiest, and the sink plugin model we have in the logger would enable this nicely.

**Comment by bobheadxi** [comment]
Understand how to integrate with otel-collector

**Comment by bobheadxi** [comment]
Sampling is purely a cost concern

**Comment by jhchabran** [comment]
Otel Collector has a mechanism to deal with this on its own: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/tailsamplingprocessor/README.md
