### ISSUE TITLE
Code Insights: Add compute-powered insight model as a possible model for the backend insight card

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#37969]
## Background 

After the implementation compute-powered creation UI we should be able to see this insight on the dashboard page. To do this we should extend `BackendInsight.tsx` card component with a new computer-powered insight FE model. 

Definition of done for this issue:
- You can view compute-powered (bar chart) insight on the dashboard page
- Drill down filters work in the same way how they are currently working
- Context menu should be able available as it's available for other insight types.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
