### ISSUE TITLE
Code Insights: Implement Map mode picker for the compute insight creation UI

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#37961]
### Background 

[Designs](https://www.figma.com/file/DqZHetdfqHSVzzWtyfjOmr/Compute-x-Insights%2C-RFC-696%2C-%2337923-%5BReview%5D?node-id=1933%3A17636)

This issue does imply only storybook component implementation, this component will be used on the creation UI/edit UI page later in a separate issue. 

![Frame 516](https://user-images.githubusercontent.com/18492575/176537461-e30b5c9d-8fe9-46ee-b704-feabb855bd56.png)

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
