### ISSUE TITLE
insights: remove graphql path from backend search provider

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#37968]
Remove the optional and deprecated GraphQL search option used in the backend

https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+useGraphQL&patternType=literal

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by leonore** [comment]
@coury-clark should we make a separate ticket for removing all the graphql-related functions, or do you want this ticket to take care of that too?

**Comment by coury-clark** [comment]
@leonore Its up to you. If its easier to break it out into a separate issue that works! End goal is to remove all of these code paths in addition to the setting option (deprecate it).
