### ISSUE TITLE
Code Insights: Add compute-power insight creation UI live preview component

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#37966]
## Background

[Designs](https://www.figma.com/file/DqZHetdfqHSVzzWtyfjOmr/Compute-x-Insights%2C-RFC-696%2C-%2337923-%5BReview%5D?node-id=1933%3A17636)

This issue implies 
- Implement compute-powered insight fetcher for the live preview data 
- Implement a live-preview chart card for the creation and edit UI of compute-powered insight
- Connect live-preview component to the compute-powered creation UI

Similar to [LineChartLivePreview](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/client/web/src/enterprise/insights/pages/insights/creation/LineChartLivePreview.tsx?L41&utm_product_name=WebStorm&utm_product_version=WebStorm&utm_source=JetBrains-v1.2.2) which is used for the search-based and capture group insights.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
