### ISSUE TITLE
Code Insights: Assemble compute-powered insight creation UI 

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#37965]
### Background 

[Designs](https://www.figma.com/file/DqZHetdfqHSVzzWtyfjOmr/Compute-x-Insights%2C-RFC-696%2C-%2337923-%5BReview%5D?node-id=1933%3A17636)

For the compute-powered insight, we are going to have a separate page for the creation and edit UI pages. This issue implies a few things to do 
- Assemble the first visual-only creation UI page 
- Leave the live preview card as a blank card, it will be implemented and connected to the page later in a separate issue

New page should be on `/insights/create/compute` route

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
