### ISSUE TITLE
JetBrains: Replace ⌥+A with a production-ready shortcut for opening the popup

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#37998]
We currently have `⌥A` (`Alt + A`) bound for opening the “Find on Sourcegraph” popup.

`⌥A` is a premium shortcut, and our use of it might not be justified.
As a tester phrased in a [user test](https://docs.google.com/document/d/1rra86ThotRy6tmILgZ_GlK-DtPbP3IJKMlOdEFWhkgc/edit#heading=h.6br5rn2450x9) : “Option-A is a super invasive shortcut that shouldn’t be overridden.”

We could:
a.) Leave it as-is (no action)
b.) Use a shortcut related to `⌘⇧F` (Find in Files). Could be `⌥⇧F` or `⌃⇧F` (but that'd be Mac only) or `⌘⇧G`
c.) Use a shortcut using “S” as in Sourcegraph. But that might be a too-busy key already.

**Comment by philipp-spiess** [comment]
The current version of the JetBrains extension already binds `alt+a` ;-) https://github.com/sourcegraph/sourcegraph-jetbrains/blob/main/src/main/resources/META-INF/plugin.xml#L16-L18

**Comment by vdavid** [comment]
Some more research results:

- Weirdly enough, `⌥A` is available in IntelliJ (I've checked both the Ultimate and Community editions). It also has no OS-wide bindings in Windows or macOS by default, so we seem to be in the clear to use it.
- My other suggestions related to `⌘⇧F` (Find in Files) (that are `⌥⇧F`, `⌃⇧F`, and `⌘⇧G`) are all used in IntelliJ.
- `⌥S` (`Alt + S` on windows) seems to be available, though, and I think that as a user, I’d remember it much easily (“S” as in Sourcegraph) than “A”.

So how about `⌥S` (`Alt + S` on windows)?
(Also @jjinnii, you might be interested, and now there is sufficient data to get to thinking.)

**Comment by jjinnii** [comment]
If there isn't anything super defining associated to `Alt + S`, I would personally vote for that one! It seems like the logic IntelliJ used for Find in Files 😄

**Comment by jjinnii** [comment]
@vdavid  Agreed on Option C! Even if `Alt + S` is already used, as @philipp-spiess mentioned, users can always modify this and it's obvious why we as Sourcegraph chose this shortcut as default. And agreed on reducing the number of shortcuts and allowing users to add them as needed.
