### ISSUE TITLE
JetBrains: Use the new Sourcegraph logo everywhere in the plugin

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#37997]
We have a new logo ([logo handbook page](https://handbook.sourcegraph.com/departments/engineering/design/brand_guidelines/logo/), [svg link](https://handbook.sourcegraph.com/departments/engineering/design/brand_guidelines/logo/versions/Sourcegraph_Logomark_Color.svg)). We should update our icon to this one, unless we end up using the monochrome one everywhere (see https://github.com/sourcegraph/sourcegraph/issues/37692#issuecomment-1171122192), which is not likely.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
