### ISSUE TITLE
JetBrains: “Open Selection on Sourcegraph Web” doesn’t work for Sourcegraph-opened files

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#38002]
When one clicks on the “Open Selection on Sourcegraph Web” on a Sourcegraph-opened (→remote) file, it won't open on Sourcegraph.
[8-sec demo](https://www.loom.com/share/68af6201510e4dc39063c2cab3f5d81e)

As a user, I'd expect it to open, with the thought, "Hey, this is their file, they've found it for me and downloaded it for me, why can't they open it on their own website?")

Solutions:
a.) Disable/remove the menu items for non-local files
b.) Make all menu items work

Obviously, b.) would be cooler. But a.) might be less work.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
