### ISSUE TITLE
JetBrains: “Search Selection on Sourcegraph Web” in case of no selection

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#38003]
These two items are currently disabled if there is no selection:
![CleanShot 2022-06-30 at 14 22 17@2x](https://user-images.githubusercontent.com/2552265/176676026-1e46a3a6-ce95-4401-86be-3a4534430c88.png)

Our user in [user test no. 2](https://docs.google.com/document/d/1rra86ThotRy6tmILgZ_GlK-DtPbP3IJKMlOdEFWhkgc/edit#heading=h.6br5rn2450x9) seemed to struggle with this. He made no specific suggestion on what he wanted for the item to do in the lack of a selection.

Solution ideas for the case of no selection:
a.) Keep it disabled, we're fine with this
b.) Enable it and search for the whole line
c.) Enable it and when clicked, expand selection and search for the currently selected word

Note: In the case of b.) and c.), there is a worst-case scenario that we don't find anything and we'll search for an empty string (""), for example, in the case of an empty file.

I'd go with b.)

**Comment by vdavid** [comment]
@jjinnii, any thoughts on this?

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
