### ISSUE TITLE
insights: Fix back integration tests so they can run as part of the CI

### ISSUE THREAD

**Issue by CristinaBirkel** [sourcegraph/sourcegraph#38011]
Some customers had issues upgrading their single-docker sourcegraph deployments due to the codeinsights-db being included. So the codeinsights-db was removed to fix the issue, and made it so that we can't run integration tests. [Here's a link to that issue.](https://github.com/sourcegraph/sourcegraph/issues/36515)

This issue is to find a way to re-introduce the integration tests.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
