### ISSUE TITLE
insights: deprecate settings oob migration

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#38024]
Deprecate the settings out of band migration that was used to move code insights from settings to the database. This involves at least setting the version of Sourcegraph that this OOB migration is no longer valid.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by coury-clark** [comment]
Two tasks over two releases:
1. Mark the oob migration as deprecated in a specific version
2. Delete it

**Comment by leonore** [comment]
P0, has been marked as deprecated for 2 releases now so it would be good to get rid of it entirely

**Comment by coury-clark** [comment]
agree with p0 as long as this doesn't exceed 1 day

**Comment by coury-clark** [comment]
as a result of this issue I've added some color to the docs on how to deprecate. The short of it is that we can't actually remove the code for the OOB migration until we no longer support 4.0 as a multi-version upgrade target. See more [here](https://docs.sourcegraph.com/dev/background-information/oobmigrations#step-6-deprecation). In the meantime, I'm cleaning up the old non-isolated code as much as possible and will close this ticket.
