### ISSUE TITLE
Create a kustomize overlay  for resource estimator

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#38029]
For non-Helm deployments - should we recommend using a kustomize overlay instead? I'm not sure we have an existing example, though, so that's probably out of scope for this doc.

_Originally posted by @caugustus-sourcegraph in https://github.com/sourcegraph/sourcegraph/pull/37869#discussion_r908831178_

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/delivery - the "team/delivery" label was applied to this issue.
