### ISSUE TITLE
full GitHub-like blame view

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#3803]
#### Feature request description

I constantly find myself going to GitHub for their blame view. It's just a lot nicer than ours. I hate clicking the lines and how our blame displays on every single line which makes it hard to see when things changed, and it being to the right of the code line makes it difficult to scan for visually.

I would like for us to have a fully-fledged blame view. Basically what we have today, but with a UI layout like GitHub has. It would be nice to also be able to narrow down in the same way GitHub supports, but that is not necessary.

**Comment by slimsag** [comment]
Also, I prefer GitHub's blame view over others because it works more nicely with long lines, see: https://sourcegraph.slack.com/archives/C0C324C91/p1556833023085400

**Comment by ijsnow** [comment]
Be aware that the full blame view may come with performance issues. See https://github.com/sourcegraph/sourcegraph/issues/136#issuecomment-418483159

**Comment by slimsag** [comment]
Note I am arguing for the same UI layout as GitHub NOT the full feature-set of GitHub which is what causes those performance issues (it would be just as performant as our blame today).

(It would be great to have that full feature-set when performant enough, but it is not the primary thing I am requesting here)

**Comment by vanesa** [comment]
A developer from one of our customers requested this feature today too.

**Comment by felixfbecker** [comment]
This would require an extension API for adding annotations to each line of code left of the line numbers (separate from the actual code content, but in an extra table column).

Maybe it's also not worth doing through an extension but through native web integration because it's likely a lot easier and all code hosts already have a blame view.

**Comment by jasongornall** [comment]
closing this as legacy can reopen if it becomes a common painpoint
