### ISSUE TITLE
Which username we are using when cloning a gitlab repository with personal access token

### ISSUE THREAD

**Issue by ammarove** [sourcegraph/sourcegraph#38035]
#### GitLab requires a username when cloning as HTTPS with user's personal token
I'm trying to override the gitconfig file on my docker instance as per this documentation
https://docs.sourcegraph.com/admin/repo/git_config
but if I'm using a personal access token i have to configure it as below 

```
[url  "https://$USER:$TOKEN@mygit.com"]
	insteadOf =  "https://$user:$TOKEN@mygit-proxy.com"
```

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.

**Comment by unknwon** [comment]
Hey @ammarove, could you elaborate what exact problem you're trying to solve in the Sourcegraph? Is adding a GitLab code host connection in the site admin area not working?

Side: @jplahn Isn't this for repo mgmt?

**Comment by ammarove** [comment]
Hello @unknwon 
I was facing the below issue when sourcegraph is trying to clone my company repo 
`SSL: no alternative certificate subject name matches target host name 'git-proxy.compay.mobi'`
and the solution was mentioned here
https://docs.sourcegraph.com/admin/repo/git_config

[url  "https://git:$TOKEN@git.compay.mobi"]
	insteadOf =  "https://git:$TOKEN@git-proxy.compay.mobi"

I tried the user "git" and It was a nice shot, i will close this issue

the user was: **git**

**Comment by unknwon** [comment]
> Hello @unknwon I was facing the below issue when sourcegraph is trying to clone my company repo `SSL: no alternative certificate subject name matches target host name 'git-proxy.compay.mobi'` and the solution was mentioned here https://docs.sourcegraph.com/admin/repo/git_config
> 
> [url "https://git:$[TOKEN@git.compay.mobi](mailto:TOKEN@git.compay.mobi)"] insteadOf = "https://git:$TOKEN@git-proxy.compay.mobi"
> 
> I tried the user "git" and It was a nice shot, i will close this issue
> 
> the user was: **git**

Ah cool, thanks! Yeah most of time "git" is the default user name. As for the error, that look like an HTTPS certificate error rather than a user invalid error?
