### ISSUE TITLE
Code Insights: Prepare page scaffolding for the compute-powered creation UI 

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#38049]
At the moment we have a lot of conventions around the creation UI components and how to build another creation UI page for a new insight type. In this issue, we have to

- Slightly adjust page/components/import structure around the creation UI kit
- Prepare high-level components for the compute-powered insight
- Add new blank route `/insights/create/compute` for the compute-powered creation UI

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
