### ISSUE TITLE
Make git-extras blame decoration toggle use pressed 

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#3804]
The pressed property for extension buttons lets it show the enabled state, which would solve @slimsag's problem related to #3803 (why he doesn't just use the Blame toggle):

> Yes, but honestly I never know if it is on or off and not clicking lines is easier than hovering over that button to see the tooltip

**Comment by felixfbecker** [comment]
@vanesa this has been open for 3 months and we want to improve extension UX, can you fit this into 3.7? It should only take ~5min. See https://sourcegraph.com/github.com/sourcegraph/sourcegraph-typescript/-/blob/package.json#L39 for an example

**Comment by vanesa** [comment]
Sorry I already did this a month ago and forgot to close this issue:
https://github.com/sourcegraph/sourcegraph-git-extras/pull/68
