### ISSUE TITLE
Create feature flag or experimental setting for core workflow UI updates

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#38060]
I think it makes sense to go ahead and set up a feature flag or experimental setting for the upcoming core workflow changes. My memory is that feature flags are only for the Sourcegraph org and if that's the case then an experimental setting would be better.

Here's my rationale:
- We want to be able to iterate quickly on UI changes and ideally we'd be able to get feedback from both internal and external users. An experimental feature lets us widen our reach to usertesting.com and unguided user tasks that we can record
- It will reduce the weight of changes in the sense that we aren't imposing anything major on users in the next release.
- It allows us to demonstrate progress on this front to leadership without incurring design debt in the default experience

@novoselrok if you feel comfortable (and agree) with the above, feel free to go ahead and get started on this ASAP. If not, ping me when you see this and let me know what reservations you have.

cc @fkling I think this could be useful as we progress with suggestions work as well.

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.
