### ISSUE TITLE
Browser extension: fix code intel popup on merge request view on GitLab

### ISSUE THREAD

**Issue by taras-yemets** [sourcegraph/sourcegraph#38064]
Code intel popup styles seem broken in the merge request view.
More details can be found in the [original GitLab issue](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/70002#note_940349106) ([current open issue](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/91219) with reference to this problem, [Slack thread](https://sourcegraph.slack.com/archives/C01LZKLRF0C/p1656645619965099)).

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by taras-yemets** [comment]
Fixed in https://github.com/sourcegraph/sourcegraph/pull/35403.
Included in `v22.7.11.926` Chrome/Firefox release.
