### ISSUE TITLE
Migrate away from gitserver.Mocks

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#38089]
## REMAINING MOCKS TO BE REMOVED

- [x] #42941
- [x] #42942
- [x] #42943
- [x] #42944

Remove gitserver.Mocks

https://github.com/sourcegraph/sourcegraph/blob/7ba413f9f972ca7b8c60a94d28ac2e937ef0cf35/internal/gitserver/mocks.go#L20-L34

We should be able to slowly remove all of these by using the mock implementation
of the gitserver client instead.

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.

**Comment by mollylogue** [comment]
Looking into this as background work this week.

**Comment by mollylogue** [comment]
TODOs:
Remove the following mocks and refactor the code/tests accordingly
- [ ] ExecReader 
- [ ] ExecSafe
- [ ] ReadDir
- [ ] ResolveRevision
- [ ] LsFiles
- [ ] MergeBase
- [ ] GetDefaultBranch
- [ ] GetDefaultBranchShort
- [ ] ReadFile
- [ ] NewFileReader
- [ ] Stat
- [ ] GetCommit
- [ ] Commits

**Comment by mollylogue** [comment]
https://github.com/sourcegraph/sourcegraph/pull/42519

**Comment by mollylogue** [comment]
https://github.com/sourcegraph/sourcegraph/pull/42538 (`NewFileReader`)

**Comment by mollylogue** [comment]
https://github.com/sourcegraph/sourcegraph/pull/42599 `ReadDir, LsFiles, Stat, GetDefaultBranch`
