### ISSUE TITLE
insights: LineChart click through diff search for scoped but backfilled insights incorrect

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#38097]
When clicking on a LineChart Point to see the diff search for an insight over some repos that has been backfilled, and incorrect diff search is generated in that it did not scope the search to the repos for the insight.

A series scoped to a single repo with a search query of: 
`<LineChart -file:.story -file:README.md lang:TSX patterntype:regexp`  

Generated the following diff search:
```
https://{ENV_URL}/search?q=type:diff+after:2022-04-05T20:00:00-04:00+before:2022-04-19T20:00:00-04:00+%3CLineChart+-file:.story+-file:README.md+lang:TSX&patternType=regexp
```

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by vovakulikov** [comment]
@Joelkw I'm not sure about the unification work but I put this in iteration 21 and [prepared a fix for it](https://github.com/sourcegraph/sourcegraph/pull/38102) so I think it will be completed in this iteration.
