### ISSUE TITLE
insights: live preview chart click though diff search incorrect

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#38098]
Edit @unclejustin 

## Problem

Links on live preview data points are incorrect. The query is not included.

### Track changes

Appears to be working correctly.

### Detect and track patterns

Repo: `github.com/sourcegraph/sourcegraph, `
Query: `file:package.json "license":\s"(.*)"`

Click any point on any data series. The search screen is missing the query.

#### Cause

In `getInsightsPreview` uses the series label + index to map the series to metadata. 

The first problem is that capture groups don't have a label. So the meta-object key is something like `-0` where it expects `LABEL-0`.

The second problem is that we only support one capture group, so all series data needs to refer to the same index. `0`

### Group results

Can't check; the live preview is failing locally. Will investigate later.

## Solution

If the key isn't found, assume this is a capture group 🤢 

Omit the label from the key and hard code the index to 0.

---

Original content by @chwarwick 

During insight creation if a live preview chart is available the click though to the diff search is incorrect, it is missing the repo filter and the search query

Creation screen with series search query (insight over 1 repo):
```
<LineChart -file:.story -file:README.md lang:TSX patterntype:regexp
```
 
Generates the following diff search:
```
https://{ENV_URL}/search?q=++type:diff++before:2022-06-02T20:00:00-04:00+&patternType=literal
```

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by Joelkw** [comment]
(Proposing this for FE iteration 26, let's determine if it's still a bug and if it is let's fix it. But in quick tests I couldn't reproduce.)

**Comment by vovakulikov** [comment]
cc @sourcegraph/code-insights-backend I think this also implies BE effort. I think this one  is blocked by https://github.com/sourcegraph/sourcegraph/issues/38104. In general I think we should move all insight data generation logic on the backend (see my points in https://github.com/sourcegraph/sourcegraph/issues/38104 why we should do this)

**Comment by vovakulikov** [comment]
From sync with @chwarwick 
We probably want to solve this bug and then we can prioritize https://github.com/sourcegraph/sourcegraph/issues/38104 as a follow up for link generation problem
