### ISSUE TITLE
Validate that our handling of revoking/granting read access for p4 protects output is correct

### ISSUE THREAD

**Issue by mollylogue** [sourcegraph/sourcegraph#38107]
[Here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/authz/perforce/protects.go?L31-64) we define which p4 protects outputs can correspond to revoking vs granting read access to a path. We should double-check against [the documentation](https://www.perforce.com/manuals/p4sag/Content/P4SAG/protections-implementation.html) that we've interpreted this correctly, and do a quick pass over our [test data](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/tree/enterprise/internal/authz/perforce/testdata) and the corresponding parsed sub-repo perms in the [tests](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/authz/perforce/perforce_test.go) to ensure that it all looks correct.

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.
