### ISSUE TITLE
insights: queued search jobs for all repos some times have higher priority than scoped insights 

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#38115]
Scoped insights over a list of named repos are inserted into the job queue with High Priority so that they execute quickly however some searches for all respo insights end up in the queue with higher priority.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
