### ISSUE TITLE
JetBrains: Create new screenshots for the 2.0.0 release on the JetBrains marketplace

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#38146]
We need to show off our fancy new UI 😎 

![Screenshot 2022-07-04 at 12 08 58](https://user-images.githubusercontent.com/458591/177133401-59a2519e-2c4c-45f3-8876-fdda1ba5a07e.png)

**Comment by vdavid** [comment]
Here: https://plugins.jetbrains.com/plugin/9682-sourcegraph

These are the new screenshots:

Popup:

![jb-find-with-sourcegraph-popup-light](https://user-images.githubusercontent.com/2552265/181363066-05dab2e1-b608-46af-8bbd-a570aa460bd5.png)
![jb-find-with-sourcegraph-popup-dark](https://user-images.githubusercontent.com/2552265/181363097-511e77ea-778f-4ae1-beb9-06b57a4fc009.png)

Context menu:

<img width="780" alt="jb-context-menu-dark" src="https://user-images.githubusercontent.com/2552265/181363088-5a45e128-610c-4214-ab7a-63bdcfcf3f21.png">
<img width="758" alt="jb-context-menu-light" src="https://user-images.githubusercontent.com/2552265/181363123-2e2a75f1-6f5f-4693-a8a3-0c80b2db1674.png">

Settings:

![jb-settings-dark](https://user-images.githubusercontent.com/2552265/181363104-baffec1b-13d3-4e8a-a2d9-e25c6f08aac7.png)
![jb-settings-light](https://user-images.githubusercontent.com/2552265/181363114-f34e36f3-6fcd-4883-89a9-44f0da2012ce.png)

Linked this in the doc.
