### ISSUE TITLE
JetBrains: Fix “Find in/on/with Sourcegraph” grammar

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#38144]
I want to have a quick grammar check before we do the release:

We have these mentions of Sourcegraph:

- Menu item: “Open Selection **in** Sourcegraph Web”
- Menu item: “Open Revision Diff **in** Sourcegraph Web”
- Comment: “Jetbrains IDE action to open a selected revision **in** Sourcegraph.”
- Menu item: “Open **on** Sourcegraph”
- Menu item: “Search Selection **on** Sourcegraph Web”
- Menu item: “Search Selection in Repository **on** Sourcegraph Web”
- Menu item: “Find **on** Sourcegraph...”
- Menu item description: “Search all your repos **on** Sourcegraph”

Asking any native speakers on the team @abeatrix @jjinnii @muratsu @ryankscott @tjkandala to check with me: are all of these correct & what we want?

This came up in https://github.com/sourcegraph/sourcegraph/pull/38086#pullrequestreview-1027209414, where @jjinnii said “I _think_ following our [copy guidelines](https://handbook.sourcegraph.com/company-info-and-process/communication/content_guidelines/style_and_mechanics/#product-names), we say ‘Find with Sourcegraph’ rather than on/in.”, but she used italic for “think” so maybe she was also not 100% sure.

I wrote “Find on Sourcegraph” because that sounded the best for me, but I'm not a native speaker. The rest, I think, were all written by @slimsag.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by jjinnii** [comment]
@vdavid  I wasn't sure either so I asked in[ marketing](https://sourcegraph.slack.com/archives/CNC4YAL1E/p1657004642991899)! Please follow thread for answers 😄 (sorry forgot to tag you)

**Comment by vdavid** [comment]
Suggestion from two people on marketing: "with". Going with "with"! Thanks a lot, @jjinnii, for bringing this up! :)
