### ISSUE TITLE
Upgrade p4-fusion to v1.10

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#38150]
https://github.com/salesforce/p4-fusion/releases/tag/v1.10

The following instructions should explain how to perform the upgrade:
https://handbook.sourcegraph.com/departments/engineering/dev/admin-exp/repo-management/upgrade-p4-fusion/

*NOTE*: We need to ensure that we *downgrade* the library to the `2022.1` (`r22.1`) version:

https://github.com/sourcegraph/sourcegraph/blob/b9a6cee518fdac7dc48545be2c050515aa4224a7/cmd/gitserver/p4-fusion-install-alpine.sh#L102

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.
