### ISSUE TITLE
JetBrains: Add Login and Settings links to popup header

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#38154]
Design: https://www.figma.com/file/nmNPZGYCoGIUN0YMylmPTT/JetBrains-plugin-MLP?node-id=2055%3A22294

- For now, the auth button should also point to Settings. The final action depends on the changes made in https://github.com/sourcegraph/sourcegraph/issues/36783.
- The auth button should only be visible if the user is not authenticated.
- The settings button should close the popup and open Settings.

Thanks to the work that's been done last week, this is a small development.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
