### ISSUE TITLE
Execute on dotcom wind-down plan

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#38168]
Timeline can be found in https://docs.google.com/document/d/1tLEiRB-Xlp40BnMlFTla97H2KhH88r14dzKxTqOlmf4/edit#heading=h.1rgn32ygu797

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.

**Comment by ryphil** [comment]
Please also make sure to remove the add-repo status message: #39266

**Comment by unknwon** [comment]
Welcome back and assign this back to you @kopancek!

**Comment by ryphil** [comment]
@kopancek - Can we close this?
