### ISSUE TITLE
Propose long term plan for permissions syncing

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#38170]
The purpose of this ticket is to come up with actionable steps as to how we're going to approach scaling permissions syncing.

Main doc:
[Scaling permissions syncing](https://docs.google.com/document/d/1HGTmjFCG6ybqQux7ot94kxbyG4pOFeH6gM7xbB-U7_c/edit#)

Other relevant docs:
[2022-06-21 Repository permissions landscape](https://docs.google.com/document/d/1UTdablpNpSLjlcxOHOKMj7UTa3Ru31TKkX-uW3pcqpU/edit) 
[Webhook sync report](https://docs.google.com/document/d/1cldGAS0fz3wqa_9Ny1zv6SHCsIrB5EsljRWPFXXoRAg/edit#heading=h.txc2m0sczysa)
[Robert: Scaling permissions syncing](https://docs.google.com/document/d/17iD_Y1tG_lWFnQOI9xQ0p0VtcYVOOUzoeU83l7Uq20I/edit)

From the discussions in the Main doc, we have determined that the logical next steps are as follows:

- [x] #42080
- [x] #42081
- [ ] Decide which approach in the main doc would be most beneficial to focus on
- [ ] Determine what metrics and tooling are required to measure our improvements

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.

**Comment by pjlast** [comment]
Related: https://docs.google.com/document/d/1HGTmjFCG6ybqQux7ot94kxbyG4pOFeH6gM7xbB-U7_c/edit#

**Comment by pjlast** [comment]
Current proposal to get to a feasible plan:

1. Get information from strategic customers to ensure we're investing time in exploring the options with the greatest impact
2. Work with [#wg-test-at-scale](https://sourcegraph.slack.com/archives/C040LV3PS4C) to ensure we have environments that replicate the setup of these customers
3. Figure out what metrics/tooling we need to monitor health/improvements in these environments and implement them
