### ISSUE TITLE
Display connected external accounts in user settings

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#38195]
Currently, there is no way for the user to tell what external accounts (SAML, GitHub OAuth, GitLab OAuth, etc.) have been connected to the authenticated user account, which is causing a frustrating experience and sometimes ended up creating new user accounts without realizing it.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.

**Comment by thenamankumar** [comment]
@miveronese is that not covered under the Account Security page?

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/22571395/192932544-6dca546b-2132-46c6-8d4c-a08bc04b42d0.png">

**Comment by unknwon** [comment]
> is that not covered under the Account Security page?

Last time I checked, we only display GitHub and GitLab, not others, and only the first GitHub and the first GitLab if there are multiple of them.

**Comment by pjlast** [comment]
See thread here as well https://sourcegraph.slack.com/archives/C03JR7S7KRP/p1665407374648159
