### ISSUE TITLE
Update screenshots/gifs in browser extension docs

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#382]
Particularly here: https://about.sourcegraph.com/docs/features/browser-extension/configuration

But this whole section of the docs hasn't been updated in a while — seems like no codeintellify in any of the demo shots.

Also, we should probably cut this whole section, right?https://about.sourcegraph.com/docs/features/search-shortcuts#manually-creating-a-search-shortcut-in-chrome

**Comment by sqs** [comment]
I updated these docs recently when I made docs.sourcegraph.com (https://docs.sourcegraph.com/integration/browser_extension)
