### ISSUE TITLE
Remove unnecessary left pane modules

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#38229]
There are lots of home panels. Some of them are intended to be educational but it’s not clear from data + qualitative feedback about Sourcegraph usability that they actually help users learn.

The remaining panels should be:
- Repositories
- Dynamic filters

**Note:** The goal of the Lucky search work is to make it so users don’t have to learn the query language (but can always drop into it if they need to), which would greatly reduce or eliminate the need for this type of product education being so front and center.

**Another note:** We believe the correct answer here is to use one solution for quickly getting to a scoped search: contexts. We will make future efforts to improve the UX but even now it's easier to do than the other methods, and ultimately just as accessible in the product.

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by limitedmage** [comment]
@benvenker @almeidapaulooliveira I want to ensure we define exactly what we're removing or keeping. Here is the list of all modules:

1. Getting started tour (feature-flagged)
2. Search types
3. Dynamic Filters
4. Repositories
5. Revisions (only visible is searching through a single repo)
6. Search Reference
7. Search Snippets/Scopes (only visible if they exist; defined in cascading settings)
8. Quicklinks (only visible if they exist; defined in cascading settings)

I _think_ we're only removing Search Reference (6) and Quicklinks (8) based on previous discussions. Please correct me if I'm wrong.

**Comment by benvenker** [comment]
@limitedmage sorry, I missed this comment. This looks fine to me for now. Caveat that the design has some name changes for the sections and style updates for their content, but I don't think that's what you're talking about here.
