### ISSUE TITLE
JetBrains: Highlight offsets are off if the line contains an emoji 

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#38222]
This affects both the result list and the code preview area:

![Screenshot 2022-07-05 at 16 20 26](https://user-images.githubusercontent.com/458591/177351570-2565c115-da0a-47e9-8125-44076403e892.png)

However this is not an issue in our Sourcegaph Web:

![Screenshot 2022-07-05 at 16 28 42](https://user-images.githubusercontent.com/458591/177351691-1897b97d-b37f-4f5b-972a-1fea5c8b1d88.png)

Example query: `r:leonardomso/33-js-concepts test`

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
