### ISSUE TITLE
gitserver.GitCommand should be private

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#38235]
It should not be possible to create a GitCommand from outside the `gitserver` package
as this allows arbitrary arguments to be passed.

We should remove the [current usages](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+GitCommand%28+-file:gitserver&patternType=literal) and then make `client.GitCommand` private.

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.

**Comment by ryanslade** [comment]
@keegancsmith There's currently only one implementation that needs to change, the one in searcher currently used by hybrid search. I see you even have a comment to move away from the current approach:

https://github.com/sourcegraph/sourcegraph/blob/d8ba817bf0a44326564d06681d8f12cc17f96618/cmd/searcher/internal/search/search.go#L56-L58

I was about to create a custom command in gitserver that could be used here but then I remember we are in the process of [making some changes](https://github.com/sourcegraph/sourcegraph/pull/38907) that affect the way diffs can be filtered when viewed with sub-repo permissions enabled (cc @mollylogue).

I don't have enough context around what hybrid search is and whether we need to apply sub-repo filtering at this point, can you provide a summary?

**Comment by keegancsmith** [comment]
For now all we need is the output of this command:

```
GitOutput(ctx, p.Repo, "diff", "-z", "--name-status", "--no-renames", string(indexed), string(p.Commit))
```

I have plans to optimize this in the future to be more smart. IE I have this comment:

```
		// TODO if our store was more flexible we could cache just based on
		// indexed and p.Commit and avoid the need of running diff for each
		// search.
```

But yes, essentially I just want to run git diff which symbols is probably already doing via a better git command interface. I have 15min to see if I can directly use what you have already. Will update here.

**Comment by keegancsmith** [comment]
Done https://github.com/sourcegraph/sourcegraph/pull/38930
