### ISSUE TITLE
Investigate Performance when working with very large changes

### ISSUE THREAD

**Issue by BolajiOlajide** [sourcegraph/sourcegraph#38241]
[Context](https://sourcegraph.slack.com/archives/C018U1ZRFQC/p1655274148375819)

Investigate performance when running batch changes with over 400 files changed. We've been getting reports of batch changes failing when the number of files changed is a lot.

**Outcome**: Any performance improvement(s) that'd lower the probability of running into this type of errors.

**Comment by eseliger** [comment]
This is specifically for inserting changeset specs into the DB, correct?

**Comment by chrispine** [comment]
P1? (or P0 if this is sustaining, but I'm not sure it is)

**Comment by LawnGnome** [comment]
I'd consider this sustaining, and therefore P0?

**Comment by Piszmog** [comment]
Created the following Issues based on the different errors I came across and possible fixes (there may need some additional refinement like breaking the Issues, specifically #39242, up into additional Issues),
* #39242
* #39245
