### ISSUE TITLE
notebooks: support bare search links in git notebooks

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#38240]
Would be awesome if search links in `.snb.md` files (e.g. something like this file: https://sourcegraph.com/github.com/sourcegraph/devx-scratch/-/blob/2022/README.snb.md) could automatically become notebook blocks when rendered, similar to the support that already exists for other block types like file links.

https://sourcegraph.slack.com/archives/C03CSAER9LK/p1657038729048299

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.
