### ISSUE TITLE
Codeintel feedback button is rendered twice

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#3824]
https://github.com/sourcegraph/sourcegraph/pull/3817/files

![image](https://user-images.githubusercontent.com/10532611/57165569-c6baee80-6df7-11e9-9ffd-d1af3218ac2b.png)

![image](https://user-images.githubusercontent.com/10532611/57165575-cc183900-6df7-11e9-9113-7933a70208ca.png)

![image](https://user-images.githubusercontent.com/10532611/57165596-de927280-6df7-11e9-970a-750118399b0b.png)

**Comment by chrismwendt** [comment]
Strange, I only see 1. Browser extension v19.4.26.1859

![image](https://user-images.githubusercontent.com/1387653/57166669-c26ae300-6daf-11e9-9d18-2c6d9045ea92.png)

**Comment by felixfbecker** [comment]
It's flaky.

**Comment by felixfbecker** [comment]
Just had this happen again.

![image](https://user-images.githubusercontent.com/10532611/57658101-77608500-7592-11e9-9c2c-3bbf73cdba7b.png)

Initially I thought that this was a bug in the code view detection logic or toolbar rendering, but the fact that I only see it happen for the feedback button and never for the TS codeintel button makes me think it must be in the basic code intel extension that adds the button

**Comment by felixfbecker** [comment]
@chrismwendt could this be caused by the fact that both the TypeScript and Go extension were activated on this PR, and they both contribute the same button? The only `when` context expression I see is `showFeedback`, no filter for the file type etc

**Comment by chrismwendt** [comment]
Ah, yup, that's it. Good find! I'll fix this.

**Comment by felixfbecker** [comment]
I am disabling the button until this is fixed.

**Comment by lguychard** [comment]
We don't show this button anymore.
