### ISSUE TITLE
Suggestion snippets and Tab

### ISSUE THREAD

**Issue by fkling** [sourcegraph/sourcegraph#38254]
When selecting a suggestion that inserts a snippet, tabbing out of the last placeholder should place the cursor after the current filter. Instead it causes the query input to loose focus.

https://user-images.githubusercontent.com/179026/177418881-885d9b43-cd73-4293-8f35-610dbea2a62f.mp4

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.
