### ISSUE TITLE
Browser extension feels slower recently

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#3825]
The browser extension feels like it is slowing down GitHub recently.

Could this be because of Quinn's recent refactor to Model?

For example, take a look at this profile from switching two PR tabs:

![image](https://user-images.githubusercontent.com/10532611/57165780-637d8c00-6df8-11e9-9607-b1310d285cc9.png)

A lot of time is spend in `removeModel()` removing all the text documents from the code views.
Models are stored in an array and every `removeModel()` removes one model with `array.filter()`, meaning we are iterating roughly n^2 times: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@browser-api/-/blob/shared/src/api/client/services/modelService.ts#L83:28
I think it should use a Map by URI instead.

We also should probably use `asyncScheduler` instead of `animationFrameScheduler` to give the event loop time to process other macrotasks inbetween.

**Comment by felixfbecker** [comment]
The majority of the time seems to be spent on #3192

**Comment by felixfbecker** [comment]
It's so bad that I can't even _open_ big PRs

**Comment by lguychard** [comment]
Rel #3778

**Comment by felixfbecker** [comment]
This is reasonably fast now. Remove model is still inefficient, but it doesn't seem to be noticeable anymore.
