### ISSUE TITLE
Gate access token creation in OSS and Free versions

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#38267]
Currently, in the user settings page, there is the **Access tokens** page to CRUD access tokens that is used to interact with our GraphQL API outside our web app.

![CleanShot 2022-07-06 at 10 00 44@2x](https://user-images.githubusercontent.com/2946214/177451639-45aac885-06ac-4f1a-a788-11ef134dfffd.png)

We want to:
1. Disable the creation capability when there isn't a valid license supplied in the site config.
	- To make minimum effort and do it quickly when there is tight time pressure, we do not need to change any UI part but just return an error as the response to the [create access token GraphQL request](https://github.com/sourcegraph/sourcegraph/blob/6e368e0571dc13ede35e9eb717d46b195fe1dd2c/cmd/frontend/graphqlbackend/schema.graphql#L236-L249).
2. Move the creation code logic out of OSS namespace (i.e. to `enterprise/`).
3. ~~Whether or not we are going to completely remove this page and disable existing uses of access tokens in non-paid version is waiting for a confirmation in the [Slack thread](https://sourcegraph.slack.com/archives/C024S6JG7B6/p1657073232466649?thread_ts=1654712273.723879&cid=C024S6JG7B6).~~

/cc @sourcegraph/source

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.
