### ISSUE TITLE
Federation is broken

### ISSUE THREAD

**Issue by christinelovett** [sourcegraph/sourcegraph#38263]
- **Sourcegraph version:** 3.40.2
- **Platform information:** Docker Compose on AWS EC2

#### Steps to reproduce:

1. Set `disablePublicRepoRedirects` to False in Site Config
2. Search repo:^github\.com/kubernetes/kubernetes on a private instance

#### Expected behavior:

When searching a public repo available on sourcegraph.com but not indexed on your private Sourcegraph, you would expect to search repo:^github\.com/kubernetes/kubernetes and either be obviously redirected to [sourcegraph.com](http://sourcegraph.com/) or for results to populate directly in your private sg from .com

#### Actual behavior:

The search returns no repo. Copying the URL from the public Sourcegraph and swapping the hostname for your private Sourcegraph also yields no results. 

/cc @jplahn @ryphil

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by lguychard** [comment]
Note: it is expected that search returns no results; however, redirection should work, but was broken by [this commit](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/b61aa924da728db229e3b41d97b014a5c9efc791?visible=1).

**Comment by lguychard** [comment]
@benvenker I think this is a "bug" and not a "discussion", based on my comment above; However, given the source of the bug, I would reassign back to repo-management. What do you thinK?

**Comment by ceusebi-eb** [comment]
I just wanted to point out that as customers of a self hosted instance we still want to search through public code outside our org. Examples of this are:
- Security auditing libraries before we fork them and include them in our org
- Reviewing interviewees assignments
- General code browsing over repos outside our org 

Hope this helps prioritize this bug

**Comment by mrnugget** [comment]
This ticket can be closed, because I removed the broken feature for now: https://github.com/sourcegraph/sourcegraph/pull/55161 https://github.com/sourcegraph/sourcegraph/pull/55205

@ceusebi-eb we hear you! We want to build true, proper federated search some day, but this was not it :)
