### ISSUE TITLE
Wildcard: Menu button component has bad performance and glitching 

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#38262]
## Background 

On the dashboard code insights page we render a lot of insight cards, each card renders a menu button component within the card. This means we render a lot of menu buttons at the same time and since [this PR](https://github.com/sourcegraph/sourcegraph/pull/36915) we always render the menu button content elements even if they're not visible (when the menu button isn't open). This increases the number of elements on the page and therefore increases the paint load for the browser.

https://user-images.githubusercontent.com/18492575/177427308-ccee81f5-acca-4734-a981-151bf74c730d.mov

<img width="1204" alt="Screenshot 2022-07-05 at 16 30 41" src="https://user-images.githubusercontent.com/18492575/177427294-366f6922-d2e7-4a93-94d8-d6dec5a911e6.png">

## Proposal 
We should not render elements that are not visible on the page. As I recall the original fix about rendering elements on the page in order to focus the first available item came from the fact that overwise reach UI does not focus the first available item. I think this is a good sign for us that we should try different components for menu button pattern that doesn't require rendering on the page all time.

**Comment by sourcegraph-bot-2** [comment]
Heads up @taylorsperry @jasongornall - the "team/frontend-platform" label was applied to this issue.
