### ISSUE TITLE
JetBrains: Keyboard events are sometimes ignored on Ubuntu

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#38276]
Feedback from customer:

> Searching in Sourcegraph directly from your IDE
> My keyboard inputs are not actually accepted in the search bar it seems

I tried to ask them to manually click inside the input but:

> manual clicking doesn't help either

> Additional thing I just figured out, on a clean restart of GoLand it works fine
> 
> closing that first window and reopening then gets into a broken state

```
~ > cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
```

GoLand 2022.1.3

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
