### ISSUE TITLE
trailing line number

### ISSUE THREAD

**Issue by sickyoon** [sourcegraph/sourcegraph#3827]
- **Sourcegraph version:** 19.4.26.1859 (browser extension)
- **Platform information:** macOS 10.14.4, Chrome 73.0.3683.103

#### Steps to reproduce:

I am not sure if this is expected behaviour but there is trailing `:<number>` appended at the end of link.

1. Go to following github coder:
https://github.com/hyperledger/fabric/blob/release-1.4/core/chaincode/shim/chaincode.go#L458
2. Click on `handleGetState` and click on `Go to definition`
3. Check `:25` appended at the end of url.

#### Expected behavior:

Link should take you to L304
```
https://github.com/hyperledger/fabric/blob/release-1.4/core/chaincode/shim/handler.go#L304
```

#### Actual behavior:

Additional line number `:25` appended at the end. 
```
https://github.com/hyperledger/fabric/blob/release-1.4/core/chaincode/shim/handler.go#L304:25
```

**Comment by dadlerj** [comment]
Hey @sickyoon — yeah, this is expected. The `:25` indicates that the selected symbol (the function name) starts at the 25th character on the 304th line. This lets Sourcegraph know what tooltip to show if there are multiple symbols on a line (e.g. for an argument to the function).
