### ISSUE TITLE
insights: you must click 3+ times on a datapoint to get it to recognize your click 

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#38270]
On the single-page view. See [this insight](https://demo.sourcegraph.com/insights/insight/aW5zaWdodF92aWV3OiIyNWN5b1BZeWFLSVdmVllXeGRqTmtUYTl2Um4i) and [this loom ](https://www.loom.com/share/3c6b170cf7624c5aaa90349fe6166cc6). 

Maybe our click radius is just too small and I was missing it? Not sure.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by Joelkw** [comment]
@unclejustin safe to close this as a duplicate of https://github.com/sourcegraph/sourcegraph/issues/38304 then?

**Comment by vovakulikov** [comment]
@Joelkw I'm not sure that this one is a duplicate, because `before:` `after:` query filters problem is 100% sure about this issue https://github.com/sourcegraph/sourcegraph/issues/38304  but click 3+ times might be chart FE problem

**Comment by Joelkw** [comment]
Closing for #38304!
