### ISSUE TITLE
Browser extension scrolls past the definition I'd like to jump to

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#3829]
Repro:
* Go to https://github.com/sourcegraph/sourcegraph/pull/3818/files
* Scroll to `r.recentSearches` line (https://github.com/sourcegraph/sourcegraph/pull/3818/files#diff-d270aecf1b7e3730429f967a1dad8114R74)
* Click on `recentSearches`, ctrl+click (open new tab) on "Go to definition"
* That takes you [here](https://github.com/sourcegraph/sourcegraph/blob/ab0ad3499c769a9e7b9e8e37c75bcf0375d03932/cmd/frontend/graphqlbackend/graphqlbackend.go#L148:2), but with the browser extension enabled, the page seems to scroll again after loading by 1-2 lines, just enough to hide the highlighted definition past the upper scroll boundary. If you open up the same link in incognito tab (no browser extension), you get scrolled exactly to the definition and it stays there.

As a user, I was confused not to find the definition on the page I was jumped to, and assumed Sourcegraph got the wrong definition location. I also then forgot exactly what definition I was looking for, so it brought me out of flow as I traced back my steps to figure out what I was looking for.

**Comment by felixfbecker** [comment]
Cannot repro anymore - assuming this was fixed. Generally we don't do any scrolling ourselves, we just put a fragment into the URL and let the browser / GitHub scroll. So this may have been a bug in Chrome or GitHub that was fixed. We still sometimes have problems with `position: sticky` headers overlaying the element, but there isn't an easy solution for that and that seems not to be what this issue described. Please reopen if you see it again!
