### ISSUE TITLE
Make explicitly deleting "gone" repositories easier

### ISSUE THREAD

**Issue by sfllaw** [sourcegraph/sourcegraph#383]
#### Feature request description

In the [Site admin > Repositories](https://sourcegraph.com/site-admin/repositories) screen:
1. Provide a filter for "gone" repositories, where the upstream repository is not found
2. Make it obvious when there are non-zero "gone" repositories
3. Batch deletion of "gone" repositories would also be helpful. See #368.

#### Is your feature request related to a problem? If so, please describe.

Whenever an upstream repository is deleted, the logs will contain the following error:
>Repository host reported a repository as not found. If this repository was deleted on its origin, the site admin must explicitly delete it on Sourcegraph. Consult repo-updater logs for more information

#### Describe alternatives you've considered.

The current alternative is to watch the logs and delete these repositories by hand, one by one.

**Comment by sqs** [comment]
We plan to address this pain with https://github.com/sourcegraph/sourcegraph/issues/914. I am closing this issue in favor of that one, which will prevent Sourcegraph from getting into the bad state described in this issue.
