### ISSUE TITLE
Code Insights: improve testing for Line Charts

### ISSUE THREAD

**Issue by unclejustin** [sourcegraph/sourcegraph#38306]
We are having multiple bugs creeping up with line charts. The complexity has grown such that manual testing can no longer cover every scenario. We need to identify all of the possible states and add unit testing for these issues.

Related issues that should have been caught:

- https://github.com/sourcegraph/sourcegraph/issues/38304
- https://github.com/sourcegraph/sourcegraph/issues/38305

[This PR](https://github.com/sourcegraph/sourcegraph/pull/36376) is also a good example of bugs being introduced mid-PR update. Many revisions and round trips to design for testing because there are just too many scenarios to account for manually with every change.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by vovakulikov** [comment]
@unclejustin We also should consider adding tests for filter →← backend insight card interactions in order to prevent problems like this one https://github.com/sourcegraph/sourcegraph/issues/38424

**Comment by unclejustin** [comment]
Follow-up note about the size of this issue:

The bulk of time spent on this issue was debugging interaction testing. This has been much more complicated than expected. The impact here is that we still don't have as broad test coverage as I would like.

Specifically, we need to find a way to trigger the hover states. I'm going to ignore these states for now and write up issues for other cases like "start Y axis at 0".
