### ISSUE TITLE
Code Insights: have to click multiple times on line charts

### ISSUE THREAD

**Issue by unclejustin** [sourcegraph/sourcegraph#38304]
When viewing a line chart, sometimes multiple clicks are needed to actually open the URL.

This is probably related to how we have to re-shuffle the line series SVGs to make the currently hovered series "on top" of the others. This is because SVGs do not recognize z-index. So we have to actually re-order the dom and put the hovered series last for it to render on top.

[Related Loom](https://www.loom.com/share/3c6b170cf7624c5aaa90349fe6166cc6)

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by unclejustin** [comment]
Observation: Chrome was blocking popups. Strangely enough, I seem to be able to just power through by keep clicking. Doesn't make sense to me. I would expect it would never work if Chrome blocks all popups.

Adding `sourcegraph.com` to my allowed list under "Pop-ups and redirect" has completely fixed this problem for me.
