### ISSUE TITLE
Code Insights: dates on series sometimes incorrect

### ISSUE THREAD

**Issue by unclejustin** [sourcegraph/sourcegraph#38305]
When clicking the data points on some series, the before and after dates are incorrect.

These dates are [created here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/enterprise/insights/core/backend/gql-backend/methods/get-built-in-insight-data/get-search-insight-content.ts?L101:17&subtree=true).

We are creating the "after" date by using `date-fns.sub` to subtract the `step` value from the current data point's date.

Suspect a timezone issue or some "rounding error" causing the date math to fail. 

[Related Loom](https://www.loom.com/share/3c6b170cf7624c5aaa90349fe6166cc6)

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
