### ISSUE TITLE
Move "go imports search" to core workflow

### ISSUE THREAD

**Issue by ryankscott** [sourcegraph/sourcegraph#38316]
As we move to bringing extensions to the core workflow we need to identify and migrate the most used extensions to core functionality. The "go imports search" is the most used extension (by users) and one of the most used by servers. 

The extension makes it easier to search all files using a Go package by creating a new operator `go.imports:()` and replaces the significantly longer search query required without the operator.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by jjinnii** [comment]
@taras-yemets Is any design required for this issue? I think the only work may be to communicate/collaborate to the search product team that we are introducing a new filter function.

**Comment by taras-yemets** [comment]
@jjinnii, there's no need for design for this extension.
