### ISSUE TITLE
Move code-intel features to core workflow

### ISSUE THREAD

**Issue by ryankscott** [sourcegraph/sourcegraph#38317]
As we focus on moving extensions to the core workflow, we need to migrate our code intel features as they are currently built on top of our extension framework. 

This will also provide some auxiliary benefits for onboarding air-gapped customers who currently require an elaborate workaround to use code intelligence features.

**Comment by efritz** [comment]
If we migrate completely to the new reference panel we will no longer need the extensions. cc @macraig

**Comment by muratsu** [comment]
@efritz quick follow up on your point, is there a way for us to have browser extensions work with this new panel?

**Comment by efritz** [comment]
@muratsu The browser extensions don't work with the old panel either.

cc @mrnugget for any additional context he'd like to dump.

**Comment by efritz** [comment]
Sorry for the brevity there!

Yes we plan to move all code intelligence extension behavior directly into the SPA.

We are focusing on removing the old reference panel, which relies on the extensions API, and also need to ensure that the popover does not require the extensions as well.

I'm unsure of how the browser extensions should be updated - if it's viable to call the instance GraphQL API directly to replace it that may be the best solution. Our new reference panel will only rely on that API as well.

@oleggromov has just joined code intel and this will likely be one of his major areas of ownership.

**Comment by mrnugget** [comment]
Here's the little context I have from the point of view of having written the new reference panel:

* new reference panel doesn't use extensions at all
* new reference panel's URLs are backwards compatible, so if browser extensions link to the same URLs, it keeps working
* the `code-intel-extensions` provide 5 `providers`: `definitions`, `references`, `implementations`, `hover`, `documentHighlights`. the new reference panel replaces the first 3: `definitions`, `references`, `implementations`. 
* the hover tooltip (on Sourcegraph instance) and document highlights are still using the extensions, even with new reference panel. those would need to be ported over to Sourcegraph.
* ⚠️ I'm not sure how the browser extension fits into all of this and how it uses the extensions.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by taras-yemets** [comment]
Hey @oleggromov,
what would be the best way for us (Integrations team) to collaborate on it with you?

**Comment by umpox** [comment]
@mrnugget 
> new reference panel doesn't use extensions at all

Is this right?

This lovely button uses extensions right?
<img width="235" alt="image" src="https://user-images.githubusercontent.com/9516420/182193058-1233b2fe-b17f-401a-ba64-41ff0c3143a9.png">

I only ask because we have a design ask to add a new button here, and we haven't found a good way yet of how to communicate state from clicking a button in this area to a tab in the panel. Ideally we don't want to use the extension API for this! Curious if there's been any thought into how to migrate this button (or similar) away from the extension API.

cc: @lrhacker

**Comment by mrnugget** [comment]
@umpox yeah, see my comment right above your comment ;) https://github.com/sourcegraph/sourcegraph/issues/38317#issuecomment-1196931164

**Comment by philipp-spiess** [comment]
We merged https://github.com/sourcegraph/sourcegraph/pull/41128/ 🎉  cc @olafurpg
