### ISSUE TITLE
Consider queueing queries when using "run all" in notebooks

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#38326]
User on managed instance said on large notebooks (with lots of structural searches as well) all the searches kick off at the same time and all ultimately fail.

Can we put them in a queue of some kind? I thought we already were but I might be misremembering.

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.
