### ISSUE TITLE
insights: Add pings for series backfilling

### ISSUE THREAD

**Issue by CristinaBirkel** [sourcegraph/sourcegraph#38330]
RFC: https://docs.google.com/document/d/1pCoMsWWinaigBktIBeI4g5hnXU2LDivpzLqQ_gjtbeg/edit#
Depends on: https://github.com/sourcegraph/sourcegraph/issues/38329

Once the `backfill_completed_at` fields are being populated, we can use that to calculate the pings in the RFC.
```
weeklySeriesBackfill: {
	p50: average time it took to backfill a series in the past week
	p90: time (p90) it took to backfill a series in the past week
	total: total number of series that were backfilled in the past week
}
```

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
