### ISSUE TITLE
Code Insights: Support new compute powered insight type on the standalone insight page

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#38344]
## Background

Since we're going to have another insight type on the frontend - compute-powered insight type we should support it on the standalone insight page, this means we should

- support rendering different types of chart (groped bar chart)
- handle insight filters when we open the page with compute-powered insight (hide sort and limit filter section)
- handle context menu based on type chart (hide start Y with 0 option)

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
