### ISSUE TITLE
Password reset link to auto populate username signin field

### ISSUE THREAD

**Issue by DaedalusG** [sourcegraph/sourcegraph#38348]
#### Feature request description

When a user is sent a password reset link, the link navigates to a form that doesn't display a username, after submitting the password reset form they are redirected to the Sourcegraph instances login screen, however, the new login screen is unpopulated. The login page should auto populate the form with the correct username, and the initial reset link page should indicate the user whose password is being rest. 

Heres an example of the current flow
![Screen Shot 2022-07-06 at 5 18 49 PM](https://user-images.githubusercontent.com/13024338/177663572-2f372689-cde3-4b5e-8814-574313aaf936.png)
![Screen Shot 2022-07-06 at 5 19 08 PM](https://user-images.githubusercontent.com/13024338/177663583-0e1aff38-9cc8-4fd6-916d-36e887eb6011.png)
![Screen Shot 2022-07-06 at 5 19 15 PM](https://user-images.githubusercontent.com/13024338/177663589-953cdbb2-76f4-4be4-8933-41dc4c106011.png)

#### Is your feature request related to a problem? If so, please describe.

This can be confusing when users aren't quite sure what username their account is being generated with. Its easy to forget as an admin to provide this information to new users

#### Describe alternatives you've considered.

The login page should auto populate the form with the correct username, and the initial reset link page should indicate the user whose password is being rest.

**Comment by yowayb** [comment]
Could this be an extra security measure considering that the user should know the account of which the password is being requested?

**Comment by prikshit-1103** [comment]
hi @DaedalusG  this issue seems like a good initiation of my journey towards contribution to FOSS projects
, could u please assign this to me ?

**Comment by MrStacks** [comment]
@prikshit-1103 Are you working on this, or is it still open? @DaedalusG is this still open?

**Comment by MrStacks** [comment]
@camdencheek I'm not sure if you are the right person to reach out to. I created a fix for this (https://github.com/sourcegraph/sourcegraph/compare/main...MrStacks:sourcegraph:KS/auto_populate_email_on_password_reset) but I'm running into some issues testing it. 

I do a `pnpm run dev` and it sends me to `https://sourcegraph.test:3443` but the link fails. I also tried `pnpm run watch-web` but I got a `Hot Module Replacement (HMR) is not enabled!` .. Any suggestions?

**Comment by camdencheek** [comment]
Hi @MrStacks! Thanks for taking a look at this. We use the [sg](https://docs.sourcegraph.com/dev/background-information/sg) tool to run sourcegraph locally. We have a dev quickstart guide [here](https://docs.sourcegraph.com/dev/setup/quickstart) you should be able to follow to get it running on your system.

**Comment by namit-chandwani** [comment]
Hey @camdencheek, I've already setup the sourcegraph repo locally on my system (with the sg tool) and would like to get started with some beginner issue to get familiar with the codebase.

Can you please assign this issue to me?

**Comment by namit-chandwani** [comment]
Hi @DaedalusG @camdencheek, I've created a PR which can close this issue.
Have tested the changes end-to-end locally as well.
Request you to review the PR whenever free

PR Link: https://github.com/sourcegraph/sourcegraph/pull/59645

TIA

**Comment by namit-chandwani** [comment]
Hey @DaedalusG @camdencheek @bobheadxi, hope you're doing well.

Can you please direct me to someone who can review my PR that closes this issue?

- PR Link: https://github.com/sourcegraph/sourcegraph/pull/59645


Thanks in advance!
