### ISSUE TITLE
DevX: Q2B2 GCP cost savings

### ISSUE THREAD

**Issue by kalanchan** [sourcegraph/sourcegraph#38347]
### Problem
Dotcom and preprod were largely over provisioned as at the time multi-tenancy was the prioritized strategy for Sourcegraph. Now that Cloud (Single tenancy) is the new strategy, there is a huge opportunity to tune our infrastructure for cost and performance. 

### Scope
An [GCP spend analysis](https://docs.google.com/document/d/1FQScUkS6fyBfW__dG0WiHmXH6-Fl_4zWwMTY9IWASSI/edit#) has been completed, and there is an opportunity to reduce our cluster size by up to 50%. This could translate to $30000/month in savings. Further tuning can be made to each service itself to find a balance between spend and performance.

- **Boundaries**
  - Soucegraph dotcom and preprod for now
  - Other workloads and GCP projects can be analyzed in the future for further cost saving opportunities
- **Definition of done**
  - Being able to reduce cluster size without impacting SRE and performance
  - Ability to show cost savings from month to month basis
- **How**
  - Utilize GCP Cost optimization tool for [dotcom](https://console.cloud.google.com/kubernetes/workload/cost?project=sourcegraph-dev&pageState=(%22savedViews%22:(%22i%22:%227f5175881a074fc49c9aeb7780f4ea3c%22,%22c%22:%5B%5D,%22n%22:%5B%22prod%22%5D))) and [preprod](https://console.cloud.google.com/kubernetes/workload/cost?project=sourcegraph-pre-prod)
  - Extract monitored usage from [Kubecost](https://github.com/kubecost) (usage current being logged, need ~15 days to get clearer picture)
  - Once targetted CPU/Mem ratio has been identified, make changes to infrastructure and deployments files
  - Follow approach in [scratch doc](https://docs.google.com/document/d/1_Q5FuspJJNXF6EYKh4yKut7w9IXPQugu1Q0eRyW_oMA/edit#heading=h.etirvf439bq7)

### Tracked issues

Phase 1: Reduce CPU/Mem of heaviest workloads
[sourcegraph/deploy-sourcegraph-cloud/pull/17194](https://github.com/sourcegraph/deploy-sourcegraph-cloud/pull/17194)

Phase 2: Resize gitserver
https://github.com/sourcegraph/sourcegraph/issues/41546

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

**Comment by bobheadxi** [comment]
Current participants: @kalanchan @davejrt @sanderginn

**Comment by jhchabran** [comment]
Update:

With phase 1, we saved about $30k/m. 
Phase 2 is still ongoing, will continue on the next bet.

**Comment by kalanchan** [comment]
Dotcom spend
July:
![image](https://user-images.githubusercontent.com/51868853/191558623-b5ee7c93-4e66-4ad9-b6f7-cdb75950c06b.png)
August:
![image](https://user-images.githubusercontent.com/51868853/191558659-7c65a30c-1339-49da-8869-c67193bae27c.png)
Realized 25k in savings. 

I'll export this data and create a better chart next month when we highlight the gitserver savings as well
