### ISSUE TITLE
link to docs is broken when hovering over structural hole (<a href="#">)

### ISSUE THREAD

**Issue by cconcannon** [sourcegraph/sourcegraph#38341]
- **Sourcegraph version:** 3.41.0
- **Platform information:** Chrome 103 on MacOS 12.4

#### Steps to reproduce:

1. structural search with a structural hole, hover over the queried hole to view the tooltip, click the `syntax reference` link

![search_bug](https://user-images.githubusercontent.com/16453494/177655744-a4ee2f5b-c4d7-4860-9f15-06e27260ffd7.png)

#### Expected behavior:

I expect the relevant docs page to be linked, i.e.

`<a href="https://docs.sourcegraph.com/code_search/reference/structural#syntax-reference">syntax reference</a>`

#### Actual behavior:

`<a href="#">syntax reference</a>`

The sourcegraph search page reloads because the link goes nowhere

FWIW it's [line 111 in the `client/shared/src/search/query/hover.ts` file](https://demo.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/shared/src/search/query/hover.ts?L111) - the markdown doesn't appear to be generating the html element with the correct `href` attribute (the `data-href` attribute points to the expected docs link, but the `href` attribute does not)

**Comment by fkling** [comment]
I cannot reproduce this. I verified that with the CodeMirror implementation the correct HTML is generated:

```
<p><strong>Structural hole</strong>. Matches code structures contextually. See the <a href="https://docs.sourcegraph.com/code_search/reference/structural#syntax-reference">syntax reference</a> for a complete description.</p>
```

It looks like Monaco might do its own Markdown -> HTML conversion so I can't look into that, but it also works as expected on sourcegraph.sourcegraph.com.

**Comment by cconcannon** [comment]
That's interesting. I also am unable to reproduce the issue, but I'm still seeing that the element on sourcegraph.sourcegraph.com is `<a href="#" data-href="https://docs.sourcegraph.com/code_search/reference/structural#syntax-reference" title="https://docs.sourcegraph.com/code_search/reference/structural#syntax-reference">syntax reference</a>`

![Screen Shot 2022-07-12 at 3 39 31 PM](https://user-images.githubusercontent.com/16453494/178610308-f8402fc1-d92a-40e0-84c1-f43f84cc732e.png)

Anyway, thanks for looking into this.
