### ISSUE TITLE
insight: Set compute series to type mapping-compute when created

### ISSUE THREAD

**Issue by CristinaBirkel** [sourcegraph/sourcegraph#38352]
Right now when the `createLineChartSearchInsight` endpoint is used to create a compute insight, (which is how we're doing it for v1 to save time,) it doesn't set the series to use `generation_method` of `mapping-compute`. Small oversight but needs to be fixed so that the right generation method gets used to backfill the series.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by leonore** [comment]
closing as fixed with #38435
