### ISSUE TITLE
Metadata searching

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#38366]
This work consists of three parts:

## Streamline existing search predicates. 
  → increase performance and usability
  → deprecate “rotten” search features/syntax

### Why?
Even though it can solve many customer issues [[example](https://github.com/sourcegraph/customer/issues/1079#issuecomment-1162271222)], we can’t recommend this feature with confidence because of performance issues. It also unlocks paths to greater search power like searching over repository description (we want to build a much better and more capable search than GitHub, see [desire and urgency to do comparative evaluation here](https://sourcegraph.slack.com/archives/C0LJP8WTB/p1655865017748599?thread_ts=1655864568.026959&cid=C0LJP8WTB))

## Search repository descriptions
Make it possible to search over repository descriptions

### Why?
Greater integration with existing rich data into code search means more out-of-box search power for users and gives us further edge over GitHub. This is a first foray to integrate other forms of data with code search—later, we plan to expand this to, e.g., searching over file or repo sizes, code intel/SCIP metadata, etc).

## Repo metadata
Make it possible to add arbitrary repo metadata that can be searched over.

### Work items
- #38368 
- #38367 
- #39949

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by malomarrec** [comment]
Are there any plans to allow users to add their own metadata to a repo (eg. in the form of tags, but could be anything)

**Comment by camdencheek** [comment]
> Are there any plans to allow users to add their own metadata to a repo

"Plans" is a strong word, but I've been thinking about it along with the integrations team cc @muratsu @philipp-spiess

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by lguychard** [comment]
Going to close this as the initial implementation is done.
