### ISSUE TITLE
Competing search tool query language parity

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#38365]
## Improved search syntax 
Continued implementation of items in [RFC 675 REVIEW: Default search and query syntax additions](https://docs.google.com/document/d/1KebTihO_jrPcLblgeT4X428kfgs42NkFz_3kCr8bT0M/edit?usp=sharing) to increase our parity with other code search tools that users are likely to be familiar with, such as OpenGrok and GitHub.

### Standard mode
- https://github.com/sourcegraph/sourcegraph/pull/38141

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by malomarrec** [comment]
Hey @benvenker, this issue didn't have a team label. Given you created it, I assigned you and added your team label. Feel free to unassign yourself. If this is not the right label, can you make sure to add the right one?

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by benvenker** [comment]
This is correct, thanks @malomarrec!
