### ISSUE TITLE
Smart search

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#38363]
Smart search effectively eliminates the “no results” problem users often have when they first encounter our literal search default. Lucky search intercepts the user input and pipes it through a rules engine that generates multiple alternative interpretations in valid Sourcegraph query syntax, virtually guaranteeing the user at least gets back results. Today, It runs these alternative queries automatically and displays them in the UI so the user can optionally run them directly.

The work on Lucky search is the beginning of a larger effort to improve our searching experience and lays a foundation for iteratively improving the quality of our results. For now, it is functionally a static rules engine but it can be extended in multiple ways, including some kind of ML-flavored approach.

There is both platform work and applications work to be completed here. There will (probably for the foreseeable future) be iterative enhancements to the rules engine and UI work to most effectively get users to the results they need and abstract as much complexity as possible. We’re currently investing heavily in design to make this a delightful and frictionless experience.

## Related work items
- #39771
- https://github.com/sourcegraph/sourcegraph/issues/37062
### PRs 
- #38343 
- #38356 
- #37904 
- #38355 
- #38357

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by camdencheek** [comment]
Closing since the work on smart search has been completed and the platform team is largely incorporating the learnings into language updates.
