### ISSUE TITLE
Verify if `enableGithubInternalRepovisibility` works as intended

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#38372]
Context:

- https://github.com/sourcegraph/sourcegraph/pull/30329
- https://github.com/sourcegraph/sourcegraph/issues/25904
- https://github.com/sourcegraph/sourcegraph/issues/32032

/cc @sourcegraph/source

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.
