### ISSUE TITLE
Move “search exports” extension to core workflow

### ISSUE THREAD

**Issue by ryankscott** [sourcegraph/sourcegraph#38379]

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by jjinnii** [comment]
@taras-yemets I believe I've provided sufficient design guidance on this issue, and you've already implemented the designs as well! (e.g. the exports button has been moved into the simple UI menu structure, as outlined in[ this design](https://www.figma.com/file/7bVINrmqfDpxmLx3gv1uVa/Sunsetting-extensions?node-id=2123%3A7162))

If this is a correct understanding, please feel free to close out this issue. 😄
