### ISSUE TITLE
Improvements to ranking

### ISSUE THREAD

**Issue by eugeniaft** [sourcegraph/sourcegraph#38397]
Currently, results are ranked by the number of stars in a repository and are subsequently ranked within each repository using [zoekt ranking](https://docs.sourcegraph.com/dev/background-information/architecture/indexed-ranking#result-ranking). We have heard from users that current ranking heuristics are not always effective, potentially leading users to spend time finding desired results, for instance by having to modify queries to add filters to help refine results. After initial user research and feedback gathering, in this quarter we are focusing on papercuts and low hanging fruit enhancements to our ranking heuristics.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/search-core - the "team/search-core" label was applied to this issue.

**Comment by stefanhengl** [comment]
This is obsolete. We have since then made considerable improvents to the ranking logic.
