### ISSUE TITLE
Investigate improvements to memory usage of zoekt

### ISSUE THREAD

**Issue by eugeniaft** [sourcegraph/sourcegraph#38398]
## Problem to solve

The amount of resources that zoekt uses is high as can be seen in our [resource estimator](https://docs.sourcegraph.com/admin/deploy/resource_estimator). This problem particularly affects customers with a large number of repos or with a large-sized repo, we have heard feedback from some customers about this in the past. Moreover, this is an issue that will become more relevant as we prioritize managed instances and a potential [new deployment model](https://docs.google.com/document/d/1IcnOQ9jyuJaku954Nhkk20k9b-CyeYUZhkwE-0lNm3I/edit#heading=h.trqab8y0kufp) for on-prem customers. Recent efforts to save cloud computing costs internally showed that reducing memory of zoekt by 20% resulted in 10% cost savings. 

## Measure of success

We have an understanding of the engineering effort and what potential memory savings are possible.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/search-core - the "team/search-core" label was applied to this issue.

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket, please let us know how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
