### ISSUE TITLE
JetBrains: Make browser UI style look more native

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#38390]
The dropdowns are great now!
But I've found some significant differences in the UI that make the browser still feel out of place compared to the native UI.

I've tried to collect the biggest things I've spotted:
(The images on the left are the native ones, the ones on the right are ours)

1. Text selection color is different from the JetBrains native color:
<img width="237" alt="CleanShot 2022-07-07 at 11 47 40@2x" src="https://user-images.githubusercontent.com/2552265/177744994-cbf7e631-aa7e-4eb7-a9a4-e2902a98e1bd.png"> <img width="271" alt="CleanShot 2022-07-07 at 11 47 55@2x" src="https://user-images.githubusercontent.com/2552265/177745028-c9b0952c-9d85-43ff-b563-26e2ae8142a4.png">

2. Icon hover background color is different (see below)
3. Tooltip background, padding, and font size are different (see below)
4. “Copy fill query ⌘+⇧+C” is mentioned but it doesn't actually work. Let's remove this from the tooltip if we can.
<img width="243" alt="CleanShot 2022-07-07 at 11 48 06@2x" src="https://user-images.githubusercontent.com/2552265/177745318-49a2bfff-b277-4659-b900-df0f6c75aa89.png"> <img width="169" alt="CleanShot 2022-07-07 at 11 48 19@2x" src="https://user-images.githubusercontent.com/2552265/177745386-9dcb99c7-6f9b-4b31-93ad-b1c03dbbdfc9.png">

5. The dark background around the search box. JetBrains doesn't use this color for anything except code editor backgrounds. I think this is the same (white) for the default light theme, but for dark themes, it's a very different shade of gray. Here:
<img width="259" alt="CleanShot 2022-07-07 at 11 54 31@2x" src="https://user-images.githubusercontent.com/2552265/177746298-316f9d3d-1075-4828-9a79-5898dcdd44f0.png"> <img width="277" alt="CleanShot 2022-07-07 at 11 54 13@2x" src="https://user-images.githubusercontent.com/2552265/177746263-aac5cad7-053f-4191-9038-0536e2a3c430.png">

6. Even more so for the search results:
<img width="301" alt="CleanShot 2022-07-07 at 11 55 57@2x" src="https://user-images.githubusercontent.com/2552265/177746615-327c0a87-1eb6-4462-bb7d-e10b3157b831.png"> <img width="340" alt="CleanShot 2022-07-07 at 11 56 14@2x" src="https://user-images.githubusercontent.com/2552265/177746664-571464ae-f157-4372-9733-46bff2a347bb.png">

7. Repo star count and line number text is significantly smaller than it is in the native window (native is 13px, ours is `0.625rem` which is 10px)
<img width="249" alt="CleanShot 2022-07-07 at 11 57 58@2x" src="https://user-images.githubusercontent.com/2552265/177747087-51eecb0e-1fa3-43b7-b0ee-1d541abe1ae1.png"> <img width="232" alt="CleanShot 2022-07-07 at 11 58 15@2x" src="https://user-images.githubusercontent.com/2552265/177747182-537f6215-a49f-4468-80df-9014e0bcfe40.png">

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by vdavid** [comment]
@jjinnii do you agree with Priority: Medium for these?

**Comment by jjinnii** [comment]
Yup agreed non-blockers to release!
