### ISSUE TITLE
repo-updater: Provide API to sync a single repo

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#38419]
We should provide a way internally to sync a single repo.

We do offer this already via the `SyncRepo` method but this is intended for .com only.

We should provide something similar for internal use. The only complication is deciding which
external service to use if the repo belongs to more than one. In most cases picking one at random is
probably fine.

This would for example help batch changes, see [this PR](https://github.com/sourcegraph/sourcegraph/pull/38265)

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.
