### ISSUE TITLE
insights: filtering is broken

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#38424]
Filtering isn't working on k8s

![CleanShot 2022-07-07 at 08 52 28](https://user-images.githubusercontent.com/5090588/177817384-920f98af-695c-404d-af37-9378d46d9a40.gif)

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
