### ISSUE TITLE
insights: test and release validation for compute

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#38433]
Prepare for July release for compute feature.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by coury-clark** [comment]
@coury-clark reminder to open follow up issues for outstanding bugs

**Comment by Joelkw** [comment]
(This item is in this iteration just until the bugs have been filed, then can be closed.)
