### ISSUE TITLE
Consolidate action/create/extension buttons into one button

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#38438]
Put actions related to search results in the existing "Create" button, and either rename it or give it an "action" icon type.

Remaining offending actions:
- Extensions buttons (ex: export to CSV)
- Save search
- Any extensions that create buttons in this area when activated

Per @paulo we'll create a generic three dot action button and segment out the action types as in the avatar dropdown.

See the three dot button and opened dropdown below ([Figma](https://www.figma.com/file/8MkIcpDtjv6tqgxZFcEQDt/Core-workflow-punch-list?node-id=27%3A7655)):

![image](https://user-images.githubusercontent.com/4605817/178307126-d7fab9f1-7f3d-438b-b2b1-9a195de4a29d.png)

**Comment by taylorsperry** [comment]
@benvenker I think this is probably FPT, but could you share a screen shot of which part of the app you're referencing?

**Comment by taylorsperry** [comment]
Oh oh oh, I think you're talking about this. Seems more like Search, but happy to help!

![Image](https://user-images.githubusercontent.com/43555476/177871358-402e7303-c34e-4281-837e-29918fdd9f24.png)

**Comment by benvenker** [comment]
@taylorsperry yeah we own this, but thanks!

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.
