### ISSUE TITLE
insights: force queries to use patternType:literal if not explicitly defined

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#38439]
To temporarily preserve the semantic that queries default to `patternType:literal` after the [default changes to `patternType:standard`](https://github.com/sourcegraph/sourcegraph/pull/38141) we will mutate queries to be `patternType:literal` if they have no value set before queueing work.

Query builder code: https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/insights/query/querybuilder/builder.go

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by Joelkw** [comment]
@coury-clark  any way we can limit this change to only impact already-existing queries, and only ones with a `/.../` pattern? In general, we want our behavior to match the search box, and would this change otherwise mean we default to literal instead of `standard` even for new searches?

**Comment by coury-clark** [comment]
@Joelkw We would need an out of band migration to do that, which is what a general case migration would be here. Otherwise, we will have to make some trade off somewhere so that we can support `patternType:literal` after the `patternType:standard` change. Any other shortcuts have just as much chance to break a query as doing nothing (including this one).

**Comment by Joelkw** [comment]
Got it, so what you've got here is what you think the best path forward is (within the constraint of not breaking the behavior things switching from literal to standard)? If we wanted to message/deprecate this longer term, would you want to plan to remove this in 3-4 releases (and include some user-facing messaging now and until then)?

**Comment by rvantonder** [comment]
hi me again @sourcegraph/code-insights 👋 is there a timeline for this work? It's currently the only thing blocking the PR https://github.com/sourcegraph/sourcegraph/pull/38141

**Comment by CristinaBirkel** [comment]
@rvantonder I'm working on this right now!

**Comment by rvantonder** [comment]
OK sweet thanks!
