### ISSUE TITLE
insights: design for insights on the search screen

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#38443]
We need quick designs for https://github.com/sourcegraph/sourcegraph/issues/38440 . 

We likely want 1 state where the graph is not visible (a % change or some other indicator) and 1 where it is. It's likely we can work within the system / prototype structure @benvenker [set up here long term](https://sourcegraph.slack.com/archives/C03L2R35ENL/p1657213820461199), but we can't wait for it (e.g., we may also need quick designs to ship within our existing UI).

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by AlicjaSuska** [comment]
The update: [designs](https://www.figma.com/file/zJHFMF1RYta92C3Trp9y4b/Insights-on-the-search-screen-%2338443-Final-review?node-id=1887%3A10416) are finalised. Today I've opened for final review and last comments ([loom](https://www.loom.com/share/064adf7f87b646519b8feacdd002b7ae))

**Comment by AlicjaSuska** [comment]
Some final non-blocking discussions are ongoing in Figma but the design has been ready for dev since last week. Closing the design issue.
