### ISSUE TITLE
GBK encoding format is garbled 

### ISSUE THREAD

**Issue by zz-GuoYF** [sourcegraph/sourcegraph#38455]
#### Question description

The code in my GitLab uses GBK encoding, and when I synced to SourceGraph, my Chinese comments were garbled

#### Is your question related to a problem? If so, please describe or link to another issue.

null

#### Additional context

My SourceGraph deployment type is Docker Single Container, version is 3.39.1

/cc @sourcegraph/search-core

**Comment by FengQingYangyan** [comment]
![image](https://user-images.githubusercontent.com/65477849/177901937-e3ea5f9b-e42c-459d-a13b-7c58fbaa57be.png)
like this

**Comment by malomarrec** [comment]
Hey @ryphil, it looks like this issue was created by someone outside Sourcegraph. Assigning you to triage it! Please answer and route to the right team by adding their team label.

**Comment by malomarrec** [comment]
Hey @ryphil, just a reminder to triage this issue and remove the triage-bot/needs-triage label when you're done!

**Comment by malomarrec** [comment]
Hey @ryphil, just a reminder to triage this issue and remove the triage-bot/needs-triage label when you're done!

**Comment by malomarrec** [comment]
Hey @ryphil, just a reminder to triage this issue and remove the triage-bot/needs-triage label when you're done!

**Comment by ryphil** [comment]
@eugeniaft - Is this a Zoekt issue? Or a git-server issue?

**Comment by eugeniaft** [comment]
I think this would be an issue across all our product, we only support UTF-8

**Comment by FengQingYangyan** [comment]
I recently discovered that there may be a problem with my gitlab server. When I tried to edit a file on gitlab, I found that it displayed garbled text, but when I only looked at the file, it did display properly
