### ISSUE TITLE
Browser extension code intel popup styles regression on GitLab

### ISSUE THREAD

**Issue by taras-yemets** [sourcegraph/sourcegraph#38464]
**Browser extension version**: current `main` branch, not published yet.

|  Expected | Actual |
|  --------- | ------ |
| ![image](https://user-images.githubusercontent.com/25318659/164264656-7b00ef76-91c2-4243-af39-f52e118c7efb.png) | ![image](https://user-images.githubusercontent.com/25318659/164264124-502a009a-85d9-4efa-8bbf-26bcdc85766c.png) |

Steps to reproduce:
- run the browser extension locally (`sg run bext` and [load build](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/browser/README.md?L82-88&utm_source=VSCode-2.2.7))
- open file or diff view on GitLab, hover over any token and check the code intel popup styles

Potentially related to:
- https://github.com/sourcegraph/sourcegraph/issues/34184
- https://github.com/sourcegraph/sourcegraph/pull/34859

**Comment by taras-yemets** [comment]
@chrismwendt, could it be the side effect of https://github.com/sourcegraph/sourcegraph/pull/34859? I reverted this PR locally and this issue went away.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by chrismwendt** [comment]
@taras-yemets Yeah, it's likely that PR broke the popover spacing. I'll dig into this now.
