### ISSUE TITLE
insights: update backend dev documentation

### ISSUE THREAD

**Issue by leonore** [sourcegraph/sourcegraph#38478]
our [dev docs](https://docs.sourcegraph.com/dev/background-information/insights/backend) haven't been updated in a while and could use some love. this work could involve:
* removing mentions of things like `experimental` and `beta`
* updating the architecture diagram
* remove outdated mentions of work 
* remove mentions of logic that is no longer relevant (e.g. dirty queries)
* mention the `sg insights` tool in debugging
* remove outdated queries in debugging

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
