### ISSUE TITLE
GraphQL APIs are blocking forever in OSS version

### ISSUE THREAD

**Issue by Matgek** [sourcegraph/sourcegraph#3847]
- **Sourcegraph version:** 
3.2
- **Platform information:** 
OS: MacOS 10.14.1
local development 
#### Steps to reproduce:
1. I'm a newcomer to sourcegraph development. I followed exactly the instructions to set the local development environment. https://github.com/sourcegraph/sourcegraph/blob/master/doc/dev/local_development.md#step-2-install-dependencies
2. start the server with ./dev/launch.sh

#### Expected behavior:
The graphql api(Search, ExploreRepositories, etc.) works for both admins and non-admin user.
#### Actual behavior:
When I login as a site-admin user, the search, exploring repositories features worked fine. But when I login as a non-admin user,  I can't search anything. The log reports:
```
17:41:58                    web | { Error: socket hang up
17:41:58                    web |     at createHangUpError (_http_client.js:323:15)
17:41:58                    web |     at Socket.socketCloseListener (_http_client.js:364:25)
17:41:58                    web |     at Socket.emit (events.js:194:15)
17:41:58                    web |     at Socket.EventEmitter.emit (domain.js:459:23)
17:41:58                    web |     at TCP._handle.close (net.js:597:12) code: 'ECONNRESET' }
17:41:58                    web | [HPM] Error occurred while trying to proxy request /.api/graphql?ExploreRepositories from localhost:3080 to http://localhost:3081 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)
17:42:30                    web | { Error: socket hang up
17:42:30                    web |     at createHangUpError (_http_client.js:323:15)
17:42:30                    web |     at Socket.socketCloseListener (_http_client.js:364:25)
17:42:30                    web |     at Socket.emit (events.js:194:15)
17:42:30                    web |     at Socket.EventEmitter.emit (domain.js:459:23)
17:42:30                    web |     at TCP._handle.close (net.js:597:12) code: 'ECONNRESET' }
17:42:30                    web | [HPM] Error occurred while trying to proxy request /.api/graphql?Search from localhost:3080 to http://localhost:3081 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)
17:55:25                    web | { Error: socket hang up
17:55:25                    web |     at createHangUpError (_http_client.js:323:15)
17:55:25                    web |     at Socket.socketCloseListener (_http_client.js:364:25)
17:55:25                    web |     at Socket.emit (events.js:194:15)
17:55:25                    web |     at Socket.EventEmitter.emit (domain.js:459:23)
17:55:25                    web |     at TCP._handle.close (net.js:597:12) code: 'ECONNRESET' }
17:55:25                    web | [HPM] Error occurred while trying to proxy request /.api/graphql?SearchSuggestions from localhost:3080 to http://localhost:3081 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```
I also tried the graphql api console, it didn't work for any query (not work when login in as non-admin users, work fine for admins). As the graphql api is a very basic function, I suppose some mistakes when I setting the environment.  So I post the logs of running ./dev/launch.sh as an attachment.  [local-launch-issue-api-not-work.txt](https://github.com/sourcegraph/sourcegraph/files/3147503/sourcegraph-local-launch-log.txt)
Can anybody tell me what's the problem? Did I miss some settings? Thank you very much.

**Comment by dobrou** [comment]
Hello @Matgek ,
I face exactly same issues, both API and web search work only for admin users when I setup local development environment.
As non-admin users, HTTP request to API just hangs and times out after some time. There are no errors or related logs in app console.

May I ask if and how did you manage to fix the issue?
Or did anyone else face the same issue?

Thank you

**Comment by sqs** [comment]
@dobrou: When the request is hanging, can you get the stack trace? You can kill -QUIT the `frontend` process to make it print the stack trace. This will help us identify where it’s hanging.

**Comment by dobrou** [comment]
@sqs thank you for quick response and good hint with kill process.

STR:
- run clean dev build
- add any repo
- create new non-admin user
- login as non-admin user
- search 'test'
- web shows no results and some background HTTP requests to graphql times out
- I killed the frontend and logs are below:

Full log attached:
[sourcegraph.log.txt](https://github.com/sourcegraph/sourcegraph/files/3520578/sourcegraph.log.txt)

What I think is important part is here:
13:54:07 [error] 6531#6531: *41 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: , request: "POST /.api/graphql?Search HTTP/1.1", upstream: "http://127.0.0.1:3082/.api/graphql?Search", host: "dobrou-ubuntu:3080", referrer: "http://dobrou-ubuntu:3080/search?q=test"
13:54:07               frontend |       /usr/lib/go-1.12/src/net/http/server.go:1995 +0x44
13:54:07               frontend | github.com/sourcegraph/sourcegraph/cmd/frontend/internal/httpapi.AccessTokenAuthMiddleware.func1(0x1d79940, 0xc000105810, 0xc000ce5600)
13:54:07               frontend |       /home/dobrou/go/src/github.com/sourcegraph/sourcegraph/cmd/frontend/internal/httpapi/auth.go:111 +0xca1
13:54:07               frontend | net/http.HandlerFunc.ServeHTTP(0xc0009fb520, 0x1d79940, 0xc000105810, 0xc000ce5600)
13:54:07               frontend |       /usr/lib/go-1.12/src/net/http/server.go:1995 +0x44

**Comment by dobrou** [comment]
BTW this bug has symptoms suspicisously similar to https://github.com/sourcegraph/sourcegraph/issues/3634

**Comment by dobrou** [comment]
And after reading through call stacks again, I suspect graphql call is blocked here https://github.com/sourcegraph/sourcegraph/blob/master/cmd/frontend/authz/register.go#L46

And after I commented out this line `<-authzProvidersReady` , search and graphql and everything actualy starts to work.

It seems that in OSS version, authorization providers are initialized and so any call to GetProviders is blocker forever.

I do not know if it could be related just to my environment, however I build SG without any modification, I did not notice any error during build and I did not configure anything special.

**Comment by Matgek** [comment]
Sorry for late response. The cause of the issue I found out is the same as @dobrou described. 
>  It seems that in OSS version for non-admin users, authorization providers are not initialized and so any call to GetProviders is blocker forever.

**Comment by dobrou** [comment]
Thank you @Matgek , no need to say sorry.
Just existence of this case helped me to go further and at least I learned golang a little :)

**Comment by tsenart** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.9 release is scheduled for tomorrow** at 10:00 CEST.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
