### ISSUE TITLE
Make persistent “learn about precise code intel” notification permanently dismissable

### ISSUE THREAD

**Issue by macraig** [sourcegraph/sourcegraph#38482]
This notification panel can’t be removed.

![Image](https://user-images.githubusercontent.com/4605817/177200475-6c9d24bc-3973-4b64-876e-bfcddbe1e536.png)

To be clear, the notification panel inside the intel popover should be dismissible. This behavior exists in other versions of the code intel panel so shouldn’t be controversial.

**Comment by oleggromov** [comment]
Sharing for visibility. I have found where there difference comes from.
WebHoverOverlay accepts `alerts` key in `hoverOrError` prop. Whenever an alert has a `type`, it is dismissible - which is totally opaque from the outside.

**Comment by oleggromov** [comment]
The fix is now live: https://sourcegraph.sourcegraph.com/github.com/kubernetes/ingress-nginx/-/blob/cmd/nginx/flags_test.go
