### ISSUE TITLE
Removed user - batch spec still available? 

### ISSUE THREAD

**Issue by DaedalusG** [sourcegraph/sourcegraph#38494]
Removed user - batch spec still available? 

- **Deployment Type**: docker-compose
- **Sourcegraph Version**: v3.40.2
- **Impact**: inconvenienced 

## Context
This is probably going to land as a feature request, but currently, the admin is just inconvenienced in their work flow with batch changes

## Brief Description
I'm trying to pick back up work on a batch spec that was developed by teammate that has been removed from a Sourcegraph instance and have observed that the change spec that user had developed is no longer available in the UI. 

Bummer

## Steps to Reproduce
1. Check out a change spec in the batch changes UI
2. Remove a user who has change sets associated with them
3. Observe the changespec disappears 

## Possible work around

I've been able to recover an old batch change spec from the `batch_specs` table in the database with a query like --
```sql
SELECT id,raw_spec FROM batch_specs WHERE user_id IS NULL;
```
Probably I can get this via a graphQL request as well, but this is a bit of a pain

## Questions

Is there an advised workflow to get around this? 

I can see that a user might not want their batch spec to remain when they leave their company, but, at the same time, its a pain to have to recover an employees work from the database when they are removed from the Sourcegraph instance after leaving the company? wdyt?

**Comment by malomarrec** [comment]
Relates to: https://github.com/sourcegraph/sourcegraph/issues/18294
