### ISSUE TITLE
Investigate work required to build (a) string-based replacement and (b) regex/structural search and replace powered by compute

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#38500]
Investigate work required to build (a) string-based replacement and (b) regex/structural search and replace powered by compute.
Specifically:
- define scope / trade-offs and add to RFC or tickets
- estimate work

I think this is actually sitting down with @rvantonder and debriefing findings with the team / in the RFC, and coming up with an estimate.

**Comment by chrispine** [comment]
P0? (not sustaining, but would be good to have done before our next sprint)

**Comment by malomarrec** [comment]
P0 / ASAP, as this will be an input for planning, design and other teams

**Comment by chrispine** [comment]
[RFC 713](https://docs.google.com/document/d/1c9vGgSfh35HNzhPSMltgVkMA9B1NO4QF5GgZwFlt5Ys/edit#)

**Comment by malomarrec** [comment]
@BolajiOlajide @courier-new sounds like we can close this, right?
