### ISSUE TITLE
Hide notepad on homepage

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#38521]
We now show the notepad everywhere in the app. It doesn’t need to be on the homepage.

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by fkling** [comment]
@benvenker For clarification: Should it only be hidden on the search homepage (even if it has notes in it) or should we have an allow list of pages where it should be shown (and if yes, which pages should that be?)

**Comment by benvenker** [comment]
I think we really only need it on the search results page, the file page, the repo page, and the diff/commit views. Am I missing any where you're actually looking at code? I don't think we need it on the notebook creation page. Maybe keep it on the notebooks main page so when people turn it on they actually see it (even if there are no notes in it).
