### ISSUE TITLE
Remove old code tour code

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#38520]
The code tour is a massive thorn in the engineers’ side because it’s reach is everywhere, it doesn’t work, and we don’t use it anymore.

This issue includes removing the code, just disabling the tour.

**Comment by benvenker** [comment]
- https://github.com/sourcegraph/sourcegraph/pull/38142

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.
