### ISSUE TITLE
Don't wait until queries finish to show lucky search suggestions 

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#38522]
Seems like we could probably show suggestions before all the queries finish loading and get them a suggestion sooner?
![image.png](https://images.zenhubusercontent.com/5467e9ba7c6ccc6277a5f103/2b637ad0-b9f3-47f2-baff-a8503e367bfa
)

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.
