### ISSUE TITLE
Ensure code intelligence still works on Browser Extensions

### ISSUE THREAD

**Issue by ryankscott** [sourcegraph/sourcegraph#38532]
Our current Browser Extensions inject functionality into the code hosts based on the enabled Sourcegraph extensions. For example, if you have enabled the codecov extension, then you will see coverage data in your code host.

As we're sunsetting Sourcegraph extensions we need to ensure that:
* Code intelligence still works with our Browser Extensions.
* We don't break anything for users on older versions of Sourcegraph

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
