### ISSUE TITLE
Find all customers who’ve build custom extensions, what they are and what we do with them

### ISSUE THREAD

**Issue by ryankscott** [sourcegraph/sourcegraph#38535]
Being tracked [here](https://docs.google.com/spreadsheets/d/1haqOzWc2jlVVtDvEYobCkugWHDqAyZT_rZSgx4Cogdc/edit#gid=0)

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
