### ISSUE TITLE
Determine the final list of SG built extensions we need to graduate

### ISSUE THREAD

**Issue by ryankscott** [sourcegraph/sourcegraph#38534]
We need to work out what Sourcegraph authored extensions we should graduate to be part of the main application.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by ryankscott** [comment]
Based on usage / enablement, the current list for Sourcegraph authored extensions are:

- code intelligence
- git-extras
- open-in-editor
- search-exports
- go-imports-search
