### ISSUE TITLE
Decide what to do with codecov

### ISSUE THREAD

**Issue by ryankscott** [sourcegraph/sourcegraph#38530]
Codecov is quite frequently used (#5 by usage) and we are featured on their website as a means of getting code coverage data on code hosts. We need to inform them and determine next steps of deprecating their extension.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by ryankscott** [comment]
We spoke with them and decided to remove this extension. We will need to co-ordinate with them closer to the date to remove some of their blog pages that reference this.

In future we have the opportunity to work with them again when we move to a different route of ingesting coverage data.
