### ISSUE TITLE
JetBrains: Verify the validity of the \r\n => \n behavior on Windows

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#38541]
c.f. https://github.com/sourcegraph/sourcegraph/pull/38491#discussion_r917105396

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by philipp-spiess** [comment]
There appear to be no issues in opening files that have no `\r\n` on Windows.:

![Image](https://user-images.githubusercontent.com/458591/178251158-e1affd9a-3c11-4119-881b-421636c83616.png)


Even when the editor shows `CRLF` on the bottom, the file will still open properly. It might save differently when you save the file but this is not important for our plugin as long as it renders correctly.
