### ISSUE TITLE
Persist the opened/closed state of panel sections

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#38565]

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by limitedmage** [comment]
I'm closing this because it's already there and should be persisted (in temporary settings). If you've found a bug in this flow where the panel state is not preserved, please reopen the issue with more details (eg. repro steps).

**Comment by benvenker** [comment]
Ah, ok. No this was a new issue I made just because it was new behavior compared to the current sidebar

**Comment by limitedmage** [comment]
The current sidebar has had persistent collapsible sections for a very long time. If for some reason these are not working for you, let me know as that is a bug.
