### ISSUE TITLE
Fix Bitbucket Projects sync when the Project has 0 existent SG users

### ISSUE THREAD

**Issue by sashaostrikov** [sourcegraph/sourcegraph#38569]
During a customer tests one issue came up: the sync is finished with an error if there are no SG users can be mapped to BB Project users ([Slack thread](https://sourcegraph.slack.com/archives/C02EDAQAJQZ/p1657294849621919))

This should be fixed by removing the check for having more than one mapped account, because it is an edge case for the BB Project consisting only of users which are not yet added to Sourcegraph. Such projects should also be synced and the permissions are added to `user_pending_permissions` in this case.

Pending permissions logic is in place, it is just "guarded" by the above-mentioned check, which should be removed.

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.
