### ISSUE TITLE
Separate out dynamic filter types into their own filters

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#38564]
Separate filters for:
- Languages
- Files types
- Utilities
- ...

More coming, design is WIP

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by benvenker** [comment]
@limitedmage if you were just planning on following the design and implementing in another ticket you can ignore this one. It's just a work item for updating the filter content and type.

**Comment by limitedmage** [comment]
@benvenker  Is it a big deal if the changes here also affect users with the "simple UI" toggle off? This code is full-stack (filters come from the server) and it would be very challenging to make this conditional.

**Comment by benvenker** [comment]
Nice, thank you!
