### ISSUE TITLE
Extensions: Onboarding experience: Improve the authentication flow for instances that can't create access tokens

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#38575]
We [soon have customers (those on free OSS on-prem installations) that will a custom URL but won't be able to create tokens](https://docs.google.com/document/d/1436xlgrA4Xy1SEIXbB0xGCwog-k0iPeYqY0JVJmckPM/edit). 

With this change, we'll have three primary groups to consider for our onboarding experience:

1. Paying enterprise customers
   - Those will have a custom URL and be able to create access tokens.
   - In some rarer cases, they might not need an access token because they have a company-wide VPN with an [http authentication proxy enabled](https://docs.sourcegraph.com/admin/auth#http-authentication-proxies)
2. OSS users on sourcegraph.com
   - Those will connect to `https://sourcegraph.com` and don't need a custom token (but can still have them).
   - They have access to search all the open source code.
   - This user group is a good fallback for us since everyone can use this features regardless of their private code state.
 3. OSS users on free on-prem installations
   - These will have a custom URL to connect to but **won't** have the ability to create custom tokens.
   - After the changes discussed in [this document](https://docs.google.com/document/d/1436xlgrA4Xy1SEIXbB0xGCwog-k0iPeYqY0JVJmckPM/edit), these users will not be able to use the IDE extension and we should try to get them onboarded as 2) instead.
 
cc @muratsu @jjinnii @ryankscott @vdavid

## Expected outcome of this issue

- Changes to the messaging on the notification that asks users to configure their instance URL.
- Potential changes to the settings page to make it clearer what authentication options are available.
- Discussion on what this means for our **default URL**?

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by philipp-spiess** [comment]
## Personal thoughts

What if we drop the option to configure an access token when connected to `https://sourcegraph.com` to simplify our config page.

With that done, the setting page could be a simple toggle between:

- Use sourcegraph.com to search open-source code for free.
- Authenticate against your enterprise installation.

My assumption here is that free OSS on-demand users will know that they are not enterprise users and thus select the other option.

**Comment by jjinnii** [comment]
@philipp-spiess  Thank you for documenting the three cases in this issue. 😄  Just a couple of questions to make sure I understand the full scope of the problem.

> OSS users on sourcegraph.com
Those will connect to https://sourcegraph.com and don't need a custom token (but can still have them).

What would it impact anything if an OSS user does enter an access token for some reason with the URL pointed to sourcegraph.com?

> What if we drop the option to configure an access token when connected to https://sourcegraph.com to simplify our config page.

Are we able to configure the Preferences menu such that the access token input field being either shown/not shown or enabled/disabled is dependent on the URL? In other words, setting it up as:

- If sourcegraph.com in URL, don't show/disable the access token input field
- If valid URL on custom URL (from a paying enterprise customer) show/enable access token input field 

The natural next question here is, are we able to distinguish during validation whether custom URLs come from enterprise customers or from free on-prem installs? 😄

**Comment by ryankscott** [comment]
I also want that it's possible that some enterprise customers will block access to https://sourcegraph.com and we may end up in an error state as someone's first experience. 

IMO we should encourage / enforce the adding of a URL and access token as a first onboarding step and doing nothing defaults to https://sourcegraph.com.

**Comment by vdavid** [comment]
> Are we able to configure the Preferences menu such that the access token input field being either shown/not shown or enabled/disabled is dependent on the URL? In other words, setting it up as:

Yup, it's pretty easy to do.
I agree that this change would make sense with the new policies.

**Comment by jjinnii** [comment]
Thanks @vdavid and @philipp-spiess! [This is the solution](https://www.figma.com/file/nmNPZGYCoGIUN0YMylmPTT/JetBrains-plugin-MLP?node-id=2183%3A27458) that I'm thinking through at the moment, and would appreciate any feedback. It's heavily dependent on our ability to modify input fields + helper copy based on the URL input field. 

The first wireframe labeled "[Default](https://www.figma.com/file/nmNPZGYCoGIUN0YMylmPTT/JetBrains-plugin-MLP?node-id=2183%3A27458)" means _by default_, the URL is set to Sourcegraph. The helper text explains that to connect to a private instance they need to set the URL to a custom URL. 

[Once the user changes the URL](https://www.figma.com/file/nmNPZGYCoGIUN0YMylmPTT/JetBrains-plugin-MLP?node-id=2182%3A25866), the additional input field for "Access token" is then exposed. The helper text also changes to accommodate for the two types of users (1 and 3) that can have custom URLs. 

cc: @ryankscott

**Comment by vdavid** [comment]
@jjinnii From a technical point of view, it's possible to make it work. But I have an alternative suggestion that I think would lead to better UX: what do you think about this layout for the settings?

![CleanShot 2022-07-14 at 13 35 44@2x](https://user-images.githubusercontent.com/2552265/178973732-c3c4792d-d427-4ff8-bfb7-c5959f99eead.png)

There would be two options similar to the screenshot: something like "Use sourcegraph.com" and "Use your enterprise instance". If the second one is selected, the two textboxes underneath it would be enabled, and the user could enter the custom URL and the optional access token.

I like this approach better because
1. it's very transparent: no form field is hidden from sight, just the ones that don't make sense for the setting are disabled.
2. it resembles more closely what JetBrains usually does

Some of the copy from your designs could be reused, too.

**Comment by jjinnii** [comment]
@vdavid I like the idea! If you could please update and tag me for final review, that would be great. Thanks!
