### ISSUE TITLE
docs: linked scope pages for npm and rust are broken

### ISSUE THREAD

**Issue by ijt** [sourcegraph/sourcegraph#3858]
To see it, go to the bottom of `https://docs.sourcegraph.com/user/search/scopes` and click the links "Top 1000 Rust crates" and "Popular npm packages".

![Screen Shot 2019-05-06 at 3 00 22 PM](https://user-images.githubusercontent.com/15530/57257925-b715f280-700f-11e9-91d9-6517bddfe7cd.png)

![Screen Shot 2019-05-06 at 3 00 28 PM](https://user-images.githubusercontent.com/15530/57257928-ba10e300-700f-11e9-9498-47fb7b5dedf9.png)

**Comment by sqs** [comment]
@attfarhan This is a feature we haven't highlighted or worked on in a long time. It's still interesting, but not a priority. Can you please remove these from the docs (top priority) and code (lower priority)? I am not aware of any customers using them, so it's safe to remove them and just mention it in the changelog.
