### ISSUE TITLE
Change team name from "devops" to `cloud` in Opsgenie

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#38586]
This appears more complex than just changing the name of the team due to the # of MI which would also need to be updated (along with checking for examples of other integrations)

AT LEAST:

- [ ] Update ALL MIs to use the new team name

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/cloud - the "team/cloud" label was applied to this issue.

**Comment by michaellzc** [comment]
estimate: 1

**Comment by daxmc99** [comment]
estimate: 1

**Comment by danieldides** [comment]
estimate: 1
