### ISSUE TITLE
Selecting public repos on a Github code host unintentionally also lists archived repos

### ISSUE THREAD

**Issue by varsanojidan** [sourcegraph/sourcegraph#38590]
- **Sourcegraph version:** All
- **Platform information:** All

See: https://github.com/github-community/community/discussions/12554 for further details of the root cause of the issue.

#### Steps to reproduce:

1. Add a Github code host
2. Add a public repositoryQuery, and exclude archived repos in the code host config:

```json
"repositroyQuery": {
  "public"
},
"exclude":[
  {
    "archived": true
  }
]
```

#### Expected behavior:
No archived repos appear in Sourcegraph.

#### Actual behavior:

Archived repos appear when searching in Sourcegraph.

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.

**Comment by varsanojidan** [comment]
@keegancsmith I am trying to resolve this issue by listing repositories through the search API, I ran into the same issues as you guys have before where (for whatever reason) the search API is limited to 1000 results even with pagination.

I am planning to work around this by using the following query format:

```
https://<GITHUB_URL>/api/v3/search/repositories?per_page=100&page=1&&sort=updated&order=asc&q=archived:false+is:public+pushed:>1990-01-01T00:00:00Z
```

And then paginating based on the last result's pushed_at value in order to bypass the 1000 limit. Theoretically there shouldn't be an issue at least from what I've played around with in the API, but thought I'd loop you in because of a similar [issue](https://github.com/sourcegraph/sourcegraph/issues/2562) you were a part of in the past to see if you had any concerns about going about it this way.

**Comment by keegancsmith** [comment]
Rather than using the search API, why not just exclude archived? I am guessing the reason is due to that api not including the archived field? (I kind of remember that issue also existing somewhere, likely is still open)

Search API has lower rate limits and of course has the 1k result limit. I remember them being something ridiculous like 30 requests an hour, so I would just ensure those are higher these days. Otherwise you won't be able to sync more than 30k repos.

However, if you do go with this approach it looks good. However, I would test that github respects these fields and sorting by them correctly. Additionally if you ever have more than 1k repos with the same updated time, this won't work. Additionally, be wary of off by 1! IE `:>` means you need to make sure you have seen _all_ repos already with that updated time.

**Comment by varsanojidan** [comment]
@keegancsmith 

>Rather than using the search API, why not just exclude archived? I am guessing the reason is due to that api not including the archived field? (I kind of remember that issue also existing somewhere, likely is still open)

yeah exactly it's an open bug with GitHub, and unfortunately none of the repository APIs can do what exactly what we need without having to query for each repo individually to see if it's archived.

>Search API has lower rate limits and of course has the 1k result limit. I remember them being something ridiculous like 30 requests an hour, so I would just ensure those are higher these days. 

Currently the API limit is 30 requests in one minute according to this page: https://docs.github.com/en/rest/search. Which is not bad, I think that should be enough.

As for potential issues with more than 1000 repos having the same updated_at time, I'm not sure if there's too much that can be done to avoid this potential issue, it might have to be a potential limitation of this, though I'm not sure what the odds of having 1000 repose having the exact same updated time to the second would be, I guess maybe if they were updated on mass by some script and then not updated again?

It seems like the API does have consistent ordering, so if you make the same request twice you'd get the same results, but I'll double check.

**Comment by keegancsmith** [comment]
FYI you need to worry about duplicates anyways since while you are paginating through a repo may be updated. so something that appears on the first page can reappear on a later page.

**Comment by varsanojidan** [comment]
> FYI you need to worry about duplicates anyways since while you are paginating through a repo may be updated. so something that appears on the first page can reappear on a later page.

Good point, ill keep it checking against the hash map for all the results.

Also I just realized the 30 requests per minute is actually going to be ~3000 repos per minute (3000 - duplicates) because the paging size is capped at 100. I did check and you are able to configure the rate-limit for the search api specifically so that would have to be something that needs to be done from the customer's end in order to use this approach.

**Comment by varsanojidan** [comment]
Unfortunately the approach with the search API described above does not work. The `updated` sort option and the `pushed` query option don't equate to the same thing even though the docs state they represent the last time the repository was updated, there are minute nuances between them which makes them unreliable to use together.

Because of this it's not actually possible to do our own pagination on this API because there are no fields that are consistent between sort options and query options.

**Comment by varsanojidan** [comment]
Ahh I see, this is great! I'm a little concerned about the [refine](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/repos/github.go?L803:4&subtree=true) potentially racking up on our rate limit, but if this has been working well so far I will definitely give it a go, thanks Keegan!

**Comment by keegancsmith** [comment]
Yeah it should work well. It is running on sourcegraph.com to literally sync all repos on github with more than 5 stars. That is a lot of requests!
