### ISSUE TITLE
Diff from a step execution is unavailable after step finishes

### ISSUE THREAD

**Issue by courier-new** [sourcegraph/sourcegraph#38600]
**Steps to reproduce:**

1. Kick off server-side execution for at least one workspace without a cache result
2. Open workspace details for that workspace
3. Wait for step to begin execution
4. Click "Diff" tab for the step
5. Observe "Diff not available" message
6. Wait for step to finish execution

**Expected behavior:**

- "Diff not available" message disappears
- Diff from step is visible

**Actual behavior:**
- "Diff not available" message persists
- I have to close the workspace details, re-open it, and click back into that step's "Diff" tab for the diff to be visible

Recording of reproduction steps:

https://user-images.githubusercontent.com/8942601/178374834-8c27e03c-dcc0-49d8-b507-271849e2df65.mov

**Comment by eseliger** [comment]
Reloading the page fixes it, the issue is that we don't reload the diff when the step finished. Definitely a bug!

**Comment by LawnGnome** [comment]
P0, normally?
