### ISSUE TITLE
insights: No points are recorded for some repository scoped insights

### ISSUE THREAD

**Issue by CristinaBirkel** [sourcegraph/sourcegraph#38603]
Slack thread: https://sourcegraph.slack.com/archives/C01RVEVPWLC/p1657571567611359

Repro:
1. Create a new insight with the following:
    - Series with the query: `context:global type:commit`. (I had to comment out some FE validation to get it to save. Could this bug be in part due to the invalid query?)
    - Time interval (not sure it matters,) is 3 weeks.
    - Scoped to repository sourcegraph/sourcegraph
2. Let it backfill
3. Note that no series points have been recorded, even though you do see them in the live preview.

I think the culprit could be this function: [filterRecordingsBySeriesRepos](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/insights/background/queryrunner/work_handler.go?L271)

Based on printing out some before/after logs from the recordings, it looks like recordings are being filtered out before they get persisted. Not sure why; I'm adding this as an issue so that it can be prioritized before spending more time on it.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by Joelkw** [comment]
Thank you for making this issue @CristinaBirkel ! Were you able to reproduce with any non-commit-type insights?

**Comment by coury-clark** [comment]
It appears the repo_id from the search results is `0` which does not match the repo_id from the database that is used to post-hoc filter for scoped repositories.

<img width="576" alt="image" src="https://user-images.githubusercontent.com/5090588/178544756-974f9419-5417-4630-be1d-7a982136ed88.png">

**Comment by leonore** [comment]
@coury-clark was this closed with the PR mentioned above?

**Comment by coury-clark** [comment]
@leonore yep, thanks for the ping!
