### ISSUE TITLE
Add ability to download files from Sourcegraph

### ISSUE THREAD

**Issue by kevachen** [sourcegraph/sourcegraph#3860]
Often times I am viewing a repo in Sourcegraph and find non-text files such as png images. I currently get a "Cannot render binary file" error, which means I currently have no way to view the file.

Is it possible to add a button to download the raw file so that we can view these files that we can't see in Sourcegraph itself?

**Comment by sqs** [comment]
Yes, this would be a great addition.

Currently, the best workaround if you're using a code host with file links (GitHub, GitLab, Bitbucket, Phabricator, etc.) is to click the code host icon in the file header to jump to the file on your code host, then click the **Raw** button on your code host's file page.

**Comment by sqs** [comment]
Also we should add a Raw button to get the raw file contents.

**Comment by dadlerj** [comment]
Requested again by https://app.hubspot.com/contacts/2762526/company/693777177

Ping @christinaforney

**Comment by beyang** [comment]
Fixed in https://github.com/sourcegraph/sourcegraph/pull/7319
