### ISSUE TITLE
React upgrade: Migrate to the new root API

### ISSUE THREAD

**Issue by gitstart-sourcegraph** [sourcegraph/sourcegraph#38607]
## Problem statement

Our `react` version is outdated, and we need to upgrade to the latest one to use new features.

## Ref
https://github.com/sourcegraph/sourcegraph/issues/33302

## Success criteria

React version is upgraded to the latest version

## Implementation details
1. Upgrade to [the latest `react` version](https://www.npmjs.com/package/react) and migrate to [the new root API](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-client-rendering-apis).

If you encounter issues with the new JSX transform integration, please ping @valerybugakov to look into it together.

## Time estimate

- Pull requests with ~450 lines changed should take **6 hours** at maximum. Ping the reviewer in the spec pull request if time-consuming changes are required.
- Split the work into multiple pull requests if the total diff is bigger than 450 lines of code.

**Comment by valerybugakov** [comment]
@gitstart-sourcegraph, we still have [at least one occurrence](https://github.com/sourcegraph/sourcegraph/blob/da154b5a93d7505b0fa994753851c27af385a347/client/jetbrains/webview/src/bridge-mock/renderColorDebugger.tsx#L11) of using ReactDOM.render in the codebase. Does it make sense to reopen this issue and complete the migration?
