### ISSUE TITLE
Patch release request: 3.41.1

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#38614]
@sourcegraph/release-guild I am requesting the following commits be included in a patch release. They are already merged into `main`:

- https://github.com/sourcegraph/sourcegraph/commit/d8f01b6827436f88c7713cf8959e7d761be35a26
- https://github.com/sourcegraph/sourcegraph/commit/271dd20b10bd24baf55d8e821dc68f9e6c329412
- https://github.com/sourcegraph/sourcegraph/commit/28cb2e0325c2746a78a4882340ea09513f1cc4ab
- https://github.com/sourcegraph/sourcegraph/commit/ffec89594b21b080d8bd752ede21abdd68210dc5
- https://github.com/sourcegraph/sourcegraph/commit/e0a55b3fe673a01784f38b4152b22369bbba9607
- https://github.com/sourcegraph/sourcegraph/commit/8b59541a6d167df4c4e1e84f192eff6e0c8e216a
- https://github.com/sourcegraph/sourcegraph/commit/1881df46d954842cb8ba828ef1e4f45431653d18
- https://github.com/sourcegraph/sourcegraph/commit/dda458ed8922cc48a10f256492ccb6550abe1381
- https://github.com/sourcegraph/sourcegraph/commit/97f0ec13017a0e7ff8785ded33b17a75440e8992
- https://github.com/sourcegraph/sourcegraph/commit/3fc48df8bd0de577bf3d78bcbeb58fda6bd4026e

---

The intent of the questions below is to ensure we keep Sourcegraph high quality and [only create patch releases based on a strict criteria.](https://handbook.sourcegraph.com/engineering/releases#patch-releases) If you can answer yes to many or most of these questions, we will be happy to create the patch release.

I have read [when and why we perform patch releases](https://handbook.sourcegraph.com/engineering/releases#patch-releases) and answer the questions as follows:

> Are users/customers actively asking us for these changes and cannot wait until the next full release?

Yes, https://github.com/sourcegraph/accounts/issues/6716 and https://github.com/sourcegraph/accounts/issues/3

Internal Slack conversations can be shared on request.

> Are the changes extremely minimal, well-tested, and low risk such that not testing as we do in a full release is OK?

Yes, the changes only affect a small subset of features, specifically sub-repo permissions and Perforce syncing.

> Is there some functionality completely broken that warrants redacting the prior release of Sourcegraph and advising users wait for the patch release?

No

> This will interrupt our regular planned work and release cycle, taking one full working day of our time, and will take up all of our site admin's valuable time by asking them to upgrade or producing noise for them if they don't need to upgrade.
>
> Do you believe the changes are important enough to warrant this?

> Patch releases are a signal we can do something better to improve the quality of Sourcegraph. Have you already scheduled a call (or created a google doc) to perform a [retrospective](https://about.sourcegraph.com/retrospectives) and identify ways we can improve?

This is more a matter of timing on the customer side. We have added significantly more test coverage around these particular features in order to catch issues earlier.

---

**For the [Release Captain]** - after reviewing this request:

- [x] **Comment on this issue** with a decision regarding the request.
- [x] If you are a first-time [Release Captain], please review the high-level overview of the [patch release process].
- [x] If approved, **add it to a patch release**:
  - If there is [already an upcoming patch release](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+), add the listed commits alongside a link to this issue
  - If there is no upcoming patch release, create a new one:
    - [x] Update [`dev/release/release-config.jsonc`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/release/release-config.jsonc) and open a PR to `main` to update it
      - [x] Change `upcomingRelease` to the current patch release
      - [x] Change `previousRelease` to the previous patch release version
      - [x] Change `releaseDate` to the current date (time is optional) along with `oneWorkingDayAfterRelease` and `threeWorkingDaysBeforeRelease`
      - [x] Change `captainSlackUsername` and `captainGitHubUsername` accordingly
    - [x] `yarn release tracking:issues` 
    - [x] Add the listed commits alongside a link to this issue to the generated [release tracking issue](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+)
- [x] **Comment and close this issue once the relevant commit(s) have been cherry-picked into the release branch**.

[release captain]: https://handbook.sourcegraph.com/engineering/releases#release-captain
[patch release process]: https://handbook.sourcegraph.com/departments/product-engineering/engineering/process/releases#patch-release-process

**Comment by ryanslade** [comment]
Approving this release in order to start working on it.

**Comment by keegancsmith** [comment]
I brought this up in a slack thread, but after looking at this issue I wanna re-ask it. There are a lot of fixes here and I know manual testing was part of validating them. Additionally these are done via direct customer asks. It feels like it would be very high value to repeat the manual tests against the release candidate. I say this though without knowledge of the code being tested though, so it may in fact be very safe to rely on the testing which was done against main.

**Comment by sashaostrikov** [comment]
@keegancsmith I'll surely repeat the tests on `3.41` branch
