### ISSUE TITLE
Initial, empty batch spec is visible from executions list

### ISSUE THREAD

**Issue by courier-new** [sourcegraph/sourcegraph#38610]
When creating a batch change with the server-side workflow, we initiate the batch change in a "draft" state with an empty batch spec. The empty batch spec is predominantly an internal concept because it will never be executed nor applied. However, it is currently surfaced in the UI wherever we list executions/specs:

![Image](https://user-images.githubusercontent.com/8942601/178431127-c3f696f9-a7fd-4c78-b89d-852033add607.png)

It is rather bizarre and unexpected to show it here, because:
1. It will always remain in the "Processing" state, which makes it seem like something will happen with it
2. Its timer will keep counting up to infinity, because of 1.
3. It has no spec contents.
4. For a draft batch change, it will auto-open on the specs tab because it's the spec that's "currently applied"

We cannot overwrite the empty batch spec while a batch change is still a draft as the newer batch spec will not be applied yet.

I think we would be best to omit empty batch specs at the batch spec connection resolver layer, so that the following are true:
- If I have never touched the batch spec for a draft batch change, the connection should be empty.
- If I have modified the batch spec and previewed workspaces (thus saving my changes as a new unapplied batch spec), the connection should return that single batch spec.
- If none of the batch specs in the connection have been applied yet, the latest batch spec should auto-open on the specs tab instead.

There isn't presently an easy way from the DB to distinguish an empty batch spec from a non-empty one, but the most straightforward approach would probably be to match on any spec whose `raw_spec` only contains the `name:` field and nothing else. Alternatively, we could add a boolean column to index this instead and , but we'd need a migration to backfill existing batch specs.

Though less important, another success criterion is that empty batch specs should also be omitted from the admin executions view:

![Image](https://user-images.githubusercontent.com/8942601/178432454-da94f8f8-d20a-432b-b346-68037fb5f7a1.png)

**Comment by chrispine** [comment]
P2?

**Comment by eseliger** [comment]
Idea: How about we losen the constraint of having an applied batch spec for every batch change? Then we wouldn't need this at all. Not sure about the implications, haven't thought too much about it yet but we also recently made the connection between spec and change a proper connection, so why not go further and clean this up, too 😬

**Comment by LawnGnome** [comment]
Not opposed to exploring that, although I feel like we have some assumptions baked in some deep places around that. Would probably be a good timeboxed spike to figure out how immediately feasible it is.

**Comment by eseliger** [comment]
yeah I don't think the 1d estimate would be right for that. More like a .. 3d but I think that's the right way to go about it. If we don't have 3d rn, I am okay backlogging this. It's not like we get 10 reports a day about why the heck is there an empty batch spec

**Comment by courier-new** [comment]
Oops just saw this conversation. I was revisiting the [draft batch change RFC](https://docs.google.com/document/d/1In0aivqY0CJA4FFvnnp47R8RaWDWKQkUYa9LlvR83FE/edit) and thinking about this more, and I think that's a reasonable suggestion. We didn't want to loosen that constraint initially because it wasn't the right time to unpack all of the assumptions baked in deep places, as Adam puts it, in the midst of SSBC work. At this point, though, we've clearly demonstrated that conceptually at least, a batch change does perfectly fine to exist without an applied batch spec.

I still think investing 0.5d-1d to just hide the empty one from the list makes sense, if it's not too difficult to distinguish it. I'll complain 10 times a day and do it myself if that's the bar to prioritize this. 😜 But I'll also file a follow-up to do the deeper gutting and try to remove the applied batch spec requirement from a batch change.
