### ISSUE TITLE
Modify runUpdateLoop to conditionally increment error metric if error level is error

### ISSUE THREAD

**Issue by indradhanush** [sourcegraph/sourcegraph#38618]
Modify the runUpdateLoop method in repo-updater to only increment the src_repoupdater_sched_error metric if the actionable error’s level is set to error [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@f2cf1b2baca6b65b2dc275ef33530214931cb207/-/blob/internal/repos/scheduler.go?L215-222).

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.
