### ISSUE TITLE
Investigate GitRepoSyncer.Fetch how to best add custom actionable errors to this method

### ISSUE THREAD

**Issue by indradhanush** [sourcegraph/sourcegraph#38620]
The method is defined [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@ca313fbd3f9c5543fe46eefc1b5e33d7000afbce/-/blob/cmd/gitserver/server/vcs_syncer_git.go?L64-71)

The outcome of this issue is a new issue to detail the challenges in implementing custom actionable errors in this method if any. Or directly implementing them if the work is under 2 days of effort. 

In either case this issue should be updated with the latest status when the day comes.

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.
