### ISSUE TITLE
Create and populate a FAQ page on sunsetting of extensions

### ISSUE THREAD

**Issue by ryankscott** [sourcegraph/sourcegraph#38623]
Working on a document that will answer internal questions that have already come up, or we anticipate will come up.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by ryankscott** [comment]
WIP document [here](https://docs.google.com/document/d/1wZqz7C1u6bnxYyEktILt4jJyLLkSBa8DIJLO_cvxpUM/edit#)
