### ISSUE TITLE
re-enable flaky test: "Completing a negated filter should insert the filter with - prefix (codemirror6)"

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#38633]
I'm going to disable this test in a PR. Here is the ticket to re-enable after flakiness is fixed.

Example failures:

- https://buildkite.com/sourcegraph/sourcegraph/builds/159870#0181f1be-764f-4fe4-92b6-5f83376ee5dc
- https://buildkite.com/sourcegraph/sourcegraph/builds/159856#0181f1a7-0398-4598-b76b-14ee05a05b7e
- https://buildkite.com/sourcegraph/sourcegraph/builds/159836#0181f15a-cd4d-49a8-9380-b1c64428bf0d

**Comment by malomarrec** [comment]
Hey @mrnugget, this issue didn't have a team label. Given you created it, I assigned you and added your team label. Feel free to unassign yourself. If this is not the right label, can you make sure to add the right one?

**Comment by mrnugget** [comment]
Thanks @malomarrec. It's @fkling's test and he already has a PR open to fix (re-enable) the test in #38649 so I added `search-core`.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/search-core - the "team/search-core" label was applied to this issue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.
