### ISSUE TITLE
Combine file and symbol data into a single panel

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#38662]
- Nest symbols under files 
- ~Utilize hierarchy for within symbols if possible~ we'll deal with hierarchy of the symbols later

Instead of using icons for identifying symbols, use text tags ([full list here](https://www.figma.com/file/8MkIcpDtjv6tqgxZFcEQDt/Core-workflow-punch-list?node-id=542%3A22853)). We should use the same background color for the tags as their icons use, but replace the icons with these.

Example Figma [here](https://www.figma.com/file/8MkIcpDtjv6tqgxZFcEQDt/Core-workflow-punch-list?node-id=542%3A23098).
![image](https://user-images.githubusercontent.com/4605817/179609000-ee4eba8e-1993-4031-87c5-9632b273bb8f.png)

- cc @novoselrok for #38810 

Sourcegraph:
![Image](https://user-images.githubusercontent.com/4605817/177199446-0e50d1ca-467f-4866-a31b-8bd326050634.png)

GitHub:

![Image](https://user-images.githubusercontent.com/4605817/177199470-65aea952-12af-4b34-be48-8f0eb560f3f4.png)

**Comment by malomarrec** [comment]
Hey @benvenker, this issue didn't have a team label. Given you created it, I assigned you and added your team label. Feel free to unassign yourself. If this is not the right label, can you make sure to add the right one?
