### ISSUE TITLE
Remove repo dropdown selector from file header bar

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#38666]
It doesn’t ever load repositories and it’s not clear why you’d ever want to filter the file view on a repository

![Image](https://user-images.githubusercontent.com/4605817/177199283-3d1f1d29-ddae-4e27-b813-81854e86bf62.png)

**Comment by sourcegraph-bot-2** [comment]
Heads up @taylorsperry @jasongornall - the "team/frontend-platform" label was applied to this issue.

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.
