### ISSUE TITLE
Combine search info dropdown and query time/results count

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#38670]
[Figma prototype](https://www.figma.com/proto/8MkIcpDtjv6tqgxZFcEQDt/Core-workflow-punch-list?node-id=176%3A14490&scaling=scale-down&page-id=0%3A1&starting-point-node-id=176%3A19861&show-proto-sidebar=1)

[Figma frame](https://www.figma.com/file/8MkIcpDtjv6tqgxZFcEQDt/Core-workflow-punch-list?node-id=176%3A14490)

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by benvenker** [comment]
@limitedmage I realized I prematurely reassigned this to @novoselrok, thinking you were leaving earlier than you are! If you think you'll try and get to it before you leave, feel free to reassign it (or I can), but otherwise i'm going to hand it off.

**Comment by limitedmage** [comment]
I don't think I'll get to it in time, unfortunately. I'm focused on the sidebar work right now :)
