### ISSUE TITLE
Add dropdown to toggle new UI and put it behind an experimental feature

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#38696]
We've created temporary setting to store whether the user has enabled the new UI, but we need to provide a way for them to toggle the setting.

For this work item, we should insert a toggle below the "theme" section of the avatar toggle dropdown menu:
- [Figma](https://www.figma.com/file/8MkIcpDtjv6tqgxZFcEQDt/Core-workflow-punch-list?node-id=74%3A11143)

![Image](https://user-images.githubusercontent.com/4605817/178610324-9c5130c8-0661-42c4-9cca-6d1e42e12ef2.png)

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by limitedmage** [comment]
This already exists in the user settings, should it be removed from there? 
![CleanShot 2022-07-12 at 15 45 40](https://user-images.githubusercontent.com/206864/178611050-0563f172-16b4-4b13-9f2e-45d2aa76cdbc.png)

**Comment by limitedmage** [comment]
Also, by "experimental feature", do you mean a feature flag in settings or an experimental badge? I'm wondering if we really need both an experimental feature flag *and* a temporary setting or if we can show the toggle to everyone with an "experimental" badge instead. Either way, users can toggle it themselves and it's experimental.

**Comment by benvenker** [comment]
I think @lguychard's thinking was basically "enable the experimental feature to display the toggle. Then the user can toggle back and forth". I honestly forgot we had already implemented this UI in the settings, so maybe what we already have is sufficient in terms of enabling/disabling.

My concern with the current location is discoverability pre-GA and I don't think it's current location is going to be found naturally by most users. I would be fine with showing the toggle with a "beta" or "experimental" flag in the avatar dropdown menu. Does that work?
