### ISSUE TITLE
GitHub App as a possible code host in site admin

### ISSUE THREAD

**Issue by pjlast** [sourcegraph/sourcegraph#38731]
Site admins need to be able to configure GitHub App as a site-level code host. Current configs exist, but would have to be updated to remove `dotcom` and `cloud` references. These are in the `Site configuration` section of Site Admin.

Currently the setup allows for a single GitHub App to exist on an instance, because that is how Cloud would have operated. I think it would theoretically be possible to accommodate for multiple GitHub Apps with some clever management of the `state` variable, but I don't think this is how it's intended to be used, so I'd rather not explore that route.

I think it would be great if there was a GitHub App entry under `Manage code hosts`, which takes the admin to setup instructions on how to create the app and which configurations to add to the `Site configuration`

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.
