### ISSUE TITLE
Migrate existing cloud configuration and routes for GitHub App

### ISSUE THREAD

**Issue by pjlast** [sourcegraph/sourcegraph#38733]
As mentioned in #38731 , there exists `site-config` entries for GitHub App, but they refer to Dotcom and Cloud. These references should be removed, since it would be site-level.

Then, the existing GitHub App routes all have various references to cloud, such as the `/cloud` in the routes and `Cloud` in handler names, as seen [here](https://sourcegraph.com/-/editor?remote_url=git%40github.com%3Asourcegraph%2Fsourcegraph.git&branch=pjlast%2F25903-addative-user-permissions-sync&file=cmd%2Ffrontend%2Finternal%2Fapp%2Frouter%2Frouter.go&start_row=100&start_col=63&end_row=100&end_col=63)

I think these references should be removed. There are also a lot of checks for GitHub App routes and handlers that do `dotcom`-related checks, which would have to be updated as well.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.

**Comment by pjlast** [comment]
Mostly implemented so far in this PR: https://github.com/sourcegraph/sourcegraph/pull/38886
