### ISSUE TITLE
Documentation explaining how to set up GitHub App as a code host

### ISSUE THREAD

**Issue by pjlast** [sourcegraph/sourcegraph#38732]
As mentioned in #38731 , we need thorough documentation explaining how to create a GitHub App, the required scopes, where in the site config to set it up. Kind of similar to https://docs.sourcegraph.com/admin/external_service/github . Sentry also has great docs explaining this process which we can learn from: https://docs.sentry.io/product/integrations/source-code-mgmt/github

#38731 should preferably point to these docs

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.

**Comment by unknwon** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IAM-627aebcc9f8b7c00128a8ab6/issues/sourcegraph/sourcegraph/38732?planning-poker) with ZenHub @kopancek @miveronese @pjlast

**Comment by miveronese** [comment]
This[ doc has a session called "How to create and test a GH App in your local SG instance" ](https://docs.google.com/document/d/1lltYuW5lqmx8m761poR2OiR82ipPIb-ZvAaPz4zdgaw/edit#bookmark=id.4ho4hmvohk5p). My suggestion is to add it -- when the time to publish GH App doc comes -- [to this section](https://docs.sourcegraph.com/admin/how-to), in our docs, so other devs can learn from our learnings.

**Comment by unknwon** [comment]
> This[ doc has a session called "How to create and test a GH App in your local SG instance" ](https://docs.google.com/document/d/1lltYuW5lqmx8m761poR2OiR82ipPIb-ZvAaPz4zdgaw/edit#bookmark=id.4ho4hmvohk5p). My suggestion is to add it -- when the time to publish GH App doc comes -- [to this section](https://docs.sourcegraph.com/admin/how-to), in our docs, so other devs can learn from our learnings.

@miveronese - Sounds perfect1
