### ISSUE TITLE
Update existing GitHub App callback functions

### ISSUE THREAD

**Issue by pjlast** [sourcegraph/sourcegraph#38734]
The existing callback handlers for GitHub App have a few assumptions baked into them. One such an assumption is that the install will be linked to a Sourcegraph Org. This will no longer be the case.

Technically we don't have to handle an installation callback, we can just query for installations right from Sourcegraph using the API. How we want to handle this is up for debate, but I would let whatever leads to a better user experience guide us. Currently I'm of the opinion that having this handled automatically would be better, and that the Setup URL Post Installation of the GitHub App setup can be omitted.

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.

**Comment by unknwon** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IAM-627aebcc9f8b7c00128a8ab6/issues/sourcegraph/sourcegraph/38734?planning-poker) with ZenHub @kopancek @miveronese @pjlast
