### ISSUE TITLE
Rename Code Intelligence to code navigation and code graph in the UI

### ISSUE THREAD

**Issue by macraig** [sourcegraph/sourcegraph#38749]
Rename all occurrences in the UI to code navigation or code graph as applicable. Redirect any /code-intelligence to /code-graph or /code-navigation

![CleanShot 2022-07-13 at 18 42 52](https://user-images.githubusercontent.com/1657213/178786867-8221849e-4c31-4e69-b01b-f482cb8c8e1a.png)

**Comment by efritz** [comment]
Obvious things that need to be changed:

- Code intelligence button in the repository view (see graphic in original issue description)
- Code intelligence settings (for repository) sidebar title and breadcrumb
- Site admin sidebar title
- Braindot title in a repository

URLs that need to change (please add a redirect from the old URLs to not break existing links into the product):
- Code intelligence settings URL (e.g., `/site-admin/code-intelligence/indexes`)
- Code intelligence settings URL in repository (e.g., `/<repo-name>/-/code-intelligence/uploads`)
- Also update `src-cli lsif upload` to target the new URL in the UI

A more complete list of occurrences:

- https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+code+intelligence+lang:TypeScript&patternType=literal

Questions:

- Do we want to name **everything**, even "precise code intelligence uploads"?

**Comment by macraig** [comment]
> Do we want to name everything, even "precise code intelligence uploads"?

Yes, those should be "Code graph data uploads"

**Comment by malomarrec** [comment]
Hey @macraig, this issue didn't have a team label. Given you created it, I assigned you and added your team label. Feel free to unassign yourself. If this is not the right label, can you make sure to add the right one?

**Comment by efritz** [comment]
Closed by #40373.
