### ISSUE TITLE
JetBrains: Add “Successfully connected to Sourcegraph” notification

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#38802]
As @jjinnii designed it in this [figma](https://www.figma.com/file/nmNPZGYCoGIUN0YMylmPTT/JetBrains-plugin-MLP?node-id=2183%3A26067#223272011).

It should appear right after saving correct settings in Preferences, and ONLY IF the previous settings were incorrect.

Technical difficulty: we verify the connection in the embedded browser rather than in Java. If the user hadn't opened the “Find with Sourcegraph” popup before the change (which might be typical after an install), the browser is not loaded, so we have no way to know whether the authentication is successful. 

Solution ideas:
1. Only show the notification if the popup has been opened and if the browser is running.
2. Implement token verification in Java

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by jjinnii** [comment]
Okay thanks @vdavid ! I would say this one is slightly more important, as communicating to our enterprise users that they were able to successfully connect (and not guess or try out search before they know it was successful) is an important part of the authentication exploration.

Let me know if you feel as if my current design (the balloon notification) is not possible or too much work, maybe we can pair on a lighter weight solution.
