### ISSUE TITLE
Make sure all CTAs in the core workflow are using temporary settings

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#38809]
Once CTAs have been dismissed by a user they should stay dismissed. At least the editor extension CTA, if not more, continues to pop up after I’ve dismissed it. I know some CTAs have used Redis cache for tracking dismissal in the past, which temporary settings makes unnecessary

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by benvenker** [comment]
@limitedmage no pressure to pull this, just seemed in your wheelhouse :)

**Comment by limitedmage** [comment]
What CTAs are left after this? https://github.com/sourcegraph/sourcegraph/issues/38625

**Comment by benvenker** [comment]
OH. Didn't see that issue. I think we're good then.
