### ISSUE TITLE
Add symbol type information to symbol results

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#38810]
Today, we only show symbol icons next to symbol names. We know the symbol type info so we should show it. Our icons are not clear (separate problem) and really don’t communicate any information to the user, other than maybe that this symbol is different than symbol types with another icon.

## Proposals
Some options for displaying the results in [this Figma](https://www.figma.com/file/8MkIcpDtjv6tqgxZFcEQDt/Core-workflow-punch-list?node-id=780%3A25094).

![Image](https://user-images.githubusercontent.com/4605817/179650297-8bdd23ee-57d4-4c2b-ac25-25ef79aac846.png)

**Comment by benvenker** [comment]
cc @novoselrok for some ideas in the Figma. @quinnkeast if you get a chance can  you take a look at this in your AM and provide feedback. Problem to solve here is making it easier to parse our symbol results, which currently use only icons to indicate a symbol type. We sort of show some hierarchy in the sense that we will show a parent symbol's name to the right of a symbol.

The goal of the proposals is to add visualize elements to improve the user's ability to parse the results and potentially show some hierarchy. I'm not sure if we get enough data to show what's pictured in the 2nd and 4th file results here.

**Comment by novoselrok** [comment]
Yeah, 2nd and 4th are not possible at the moment because we can't the type information for symbols.

I prefer the 3rd option from the above image because injecting the symbol tag between the line number and the code will be very tricky.

**Comment by novoselrok** [comment]
The only thing I'm worried about with the new symbol display is the situation below, where there are several identical results, and the only difference is the container name:

<img width="551" alt="Screenshot 2022-07-19 at 07 54 33" src="https://user-images.githubusercontent.com/6417322/179675653-0ccdafde-674c-4164-b827-6dd63c2b6a03.png">

With the new system, a user won't be able to tell the difference beyond the different line numbers. This could be an edge case, but it would be worth considering a fix.

**Comment by benvenker** [comment]
@novoselrok did you still want to the grouping by container name?

**Comment by novoselrok** [comment]
Probably not, I'm not sure if we could do it with the new design.
