### ISSUE TITLE
Make search contexts behave as expected

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#38829]
Full, rich context in the [slack thread](https://sourcegraph.slack.com/archives/CHEKCRWKV/p1657817717306289). The UI makes you think you're getting a hard-scoped search context but you're actually not.

Source is in how the UI handles generating the query, it seems.

- potentially just transform the query before we send it?

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by camdencheek** [comment]
Closing since the slack thread with context is gone.
