### ISSUE TITLE
Code Insights: Support series color for compute-powered insight series

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#38832]
Depends on https://github.com/sourcegraph/sourcegraph/issues/39162

## Background

In the first release of compute we release series with no manually set colors and use generated on the backend series results and colors simular to the capture group insight. This is because we can't connect series with series points in case of generated series point on the backend in live preview handler `searchInsightPreview`. 

For example let's say we have insight with 2 series "compute" and "insight" in searchLivePreview query we have

```jsonc
[
    {
        "points": [ { "dateTime": "2022-07-14T17:25:28Z",  "value": 8,  } ],
        "label": "Rijnard van Tonder",
    },
    {
        "points": [ { "dateTime": "2022-07-14T17:25:28Z",  "value": 6,  } ],
        "label": "leo",
    },
    {
        "points": [ { "dateTime": "2022-07-14T17:25:28Z",  "value": 8,  } ],
        "label": "leo",
    },
    {
        "points": [ { "dateTime": "2022-07-14T17:25:28Z",  "value": 10,  } ],
        "label": "Vova Kulikov",
    },
]
```

As. you can see this is just a flat list of points and the best that we can do here is just group this flat list by label and sum up points of this groups. In this example we would have 3 bars on the bar chart with 
- Rijnard van Tonder with 8
- leo with 6 + 8 = 14
- Vova Kulikov with 10

Ideally we want to split results from different query and color them with series color, for example like on the following chart below

<img width="421" alt="Screenshot 2022-07-14 at 21 31 52" src="https://user-images.githubusercontent.com/18492575/179058132-2c701cbe-3bab-4a15-873d-e05bd858002f.png">

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by vovakulikov** [comment]
From sync — for the 4.0 we should disable multi-series support in compute-powered insight creation UI, all bars categories in the live preview should have the same colour. This also means that issue is FE only and doesn't depend on https://github.com/sourcegraph/sourcegraph/issues/39162 anymore. 

We may have support multi-series support in the future but not now
