### ISSUE TITLE
Publish final documentation to external docs

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#38853]

**Comment by malomarrec** [comment]
Hey @malomarrec, it looks like this issue was created by someone outside Sourcegraph. Assigning you to triage it! Please answer and route to the right team by adding their team label.

**Comment by malomarrec** [comment]
@abeatrix having trouble assigning this to a team. Can you add a `team/<team>` label please and remove the `triage-bot` label?

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/delivery - the "team/delivery" label was applied to this issue.
