### ISSUE TITLE
CI flakes on tests that have been stable for months (structural search)

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#38859]
Investigate https://github.com/sourcegraph/sourcegraph/pull/38858

/cc @sourcegraph/search-platform

**Comment by malomarrec** [comment]
Hey @rvantonder, this issue didn't have a team label. Given you created it, I assigned you and added your team label. Feel free to unassign yourself. If this is not the right label, can you make sure to add the right one?

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by jtibshirani** [comment]
Closing since we're not actively investing in structural search.
