### ISSUE TITLE
Java Language Server is not available to public

### ISSUE THREAD

**Issue by 40rn05lyv** [sourcegraph/sourcegraph#389]
Hi, I noticed that Java Language Server from Sourcegraph is referenced from wiki pages (e.g. from https://github.com/sourcegraph/sourcegraph/blob/master/docs/architecture.md), but the link https://github.com/sourcegraph/java-langserver leads to 404 page. All other language server implementations are open, so I suppose it's either an incorrect link or the repository was hidden by mistake.

**Comment by sqs** [comment]
We will open source it by December, most likely. (See roadmap at https://docs.sourcegraph.com/dev/roadmap for how we're prioritizing.) It will undergo a lot of changes soon as we move language support from LSP-based lang servers to Sourcegraph extensions (which can contact LSP-based lang servers, but can also do more).

**Comment by sqs** [comment]
The Sourcegraph Java lang server is now open source: https://github.com/sourcegraph/java-langserver.

We just released it and it is not *yet* well documented how to run it, etc.
