### ISSUE TITLE
structural search (a.k.a. "comby")

### ISSUE THREAD

**Issue by ijt** [sourcegraph/sourcegraph#3890]
Sourcegraph search queries currently support regular expressions, but comby patterns would be more powerful and more naturally suited for most programming languages. Comby patterns are more powerful because for example they can match patterns with nested delimiters such as parens, and they are more natural because they don't have special meanings for characters such as parens that have other meanings in various languages. 

Rijnard’s current prototype: https://github.com/comby-tools/comby

**Comment by slimsag** [comment]
would this be an alternative to regex, or a replacement for it?

I understand regex but I don't understand comby. I feel like most developers would fit into this boat.

**Comment by ijt** [comment]
To start with it should be an alternative. Eventually it would be useful if we can make the comby patterns handle everything in a way that feels intuitive for regex users.

**Comment by ijt** [comment]
CC @rvantonder

**Comment by ijt** [comment]
Closing this for now. We can file a new issue for it once we make some nearer-term changes like literal search and create an RFC for this.
