### ISSUE TITLE
Code Insights: Line chart has an odd hover areas distribution 

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#38919]
From @coury-clark 
> The distance that the cursor can move around data points on our charts is very oddly weighted to one side, and makes it feel very confusing when hovering over points

![CleanShot 2022-07-13 at 14 08 27](https://user-images.githubusercontent.com/18492575/179449383-649fdc23-4529-4b79-b3cd-8e9d1505cf43.gif)

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
