### ISSUE TITLE
Code Insights: Sort and limit filters do not show up with purple dot  

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#38926]
## Background 

Our UX logic around filters says: 
> If some insight filters have been changed and differ from the default filters, we should set a purple dot right next to the filter icon and filters panel heading. 

At the moment, sort and limit filters do not change the "dirty" purple dot appearance if we change them.

https://user-images.githubusercontent.com/18492575/179474798-c699bc8d-1de4-4f6e-878b-a65d99106202.mov

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by coury-clark** [comment]
backlog
