### ISSUE TITLE
reimplement symbol search in terms of zoekt

### ISSUE THREAD

**Issue by ijt** [sourcegraph/sourcegraph#3892]
This should help with https://github.com/sourcegraph/sourcegraph/issues/3534.

**Comment by keegancsmith** [comment]
FYI zoekt has support to run and index ctags output.

**Comment by slimsag** [comment]
I don't think splitting this out is useful, https://github.com/sourcegraph/sourcegraph/issues/3534 is about this. If anything we can split out the other smaller improvement but I'd rather keep this in one place where we can discuss symbols working better at scale.
