### ISSUE TITLE
Integration usage stats broken

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#3893]
All browser extension and related integrations (including the Phabricator native integration) are no longer sending usage statistics to the private Sourcegraph instance that they're connected to. 

CC @felixfbecker, I'll take a first stab but might ask for your help re-adding this.

See discussion in https://sourcegraph.slack.com/archives/CHXHX7XAS/p1557265704007700

**Comment by felixfbecker** [comment]
Some pointers:
- [`git checkout 1b49747 -- client/browser/src/shared/tracking/EventLogger.tsx`](https://sourcegraph.sgdev.org/github.com/sourcegraph/sourcegraph@1b497472c9c954b0aabbec2353e82e1e02b7532d/-/blob/client/browser/src/shared/tracking/EventLogger.tsx#L10:14)
- Fix type errors (e.g. `storage.getSyncItem()` -> `storage.sync.get()`)
- Remove [every reference to `NOOP_TELEMETRY_SERVICE` in the browser extension](https://sourcegraph.sgdev.org/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+f:%5Ebrowser/+-f:test+NOOP_TELEMETRY_SERVICE)
- Instantiate the event logger in each browser/src/scripts/* file
- Pass the instance through props and parameters through to where `NOOP_TELEMETRY_SERVICE` was before

**Comment by dadlerj** [comment]
Can you clarify step 4 here? I don't see a browser/src/scripts folder, and not sure I can interpret what points you're suggesting this should be instantiated at.

**Comment by dadlerj** [comment]
Never mind, I think I got this working — check out my PR
