### ISSUE TITLE
pkg/extsvc: Review code host client caching strategy

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#3895]
Some of our code host client packages have an internal caching layer:

- [AWS Code Commit](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/pkg/extsvc/awscodecommit/client.go#L17)
- [GitHub](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/pkg/extsvc/github/client.go#L66)
- [GitLab](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/pkg/extsvc/gitlab/client.go#L132)

Together with our new syncing model, where metadata of each individual repository is stored in Postgres in the `metadata` column, this caching existing layer may be at least unnecessary and at most harmful (e.g. could the syncer be loading cached data instead of fresh data as it should every time it runs?)

We need to investigate if it's still necessary or not and devise a plan accordingly.

**Comment by keegancsmith** [comment]
An additional place this is important is for sourcegraph.com where we still speak to the upstream code host (only github) in repoLookup.

**Comment by tsenart** [comment]
It turns out that sourcegraph.com still heavily relies on caching access to single repos, which this caching layer provides.
