### ISSUE TITLE
Remove old feature gates from src-cli

### ISSUE THREAD

**Issue by chrispine** [sourcegraph/sourcegraph#38967]
Src-cli has feature gates that we could remove, along with a lot of code paths we no longer test

**Comment by courier-new** [comment]
P0 or P1. In general with the issues tagged `4.0` I don't feel that any particular issues need to be prioritized before others, but I generally feel we should frontload this work in case anything unexpected is uncovered as part of it.

**Comment by courier-new** [comment]
Team, how far back do we want to go with the feature flags that we continue maintain? 6 months (3.36)? A year (3.30)? 18 months (3.24)?
