### ISSUE TITLE
GraphQL sweep: what changes/deprecations should we make?

### ISSUE THREAD

**Issue by chrispine** [sourcegraph/sourcegraph#38975]
Do a sweep of graphql and see what deprecations/changes we should make there

- Deprecated state fields on a changeset: reconcilerState, publicationState, externalState
- Several deprecated fields on batch change
- ...more?

**Comment by courier-new** [comment]
P0 or P1. In general with the issues tagged `4.0` I don't feel that any particular issues need to be prioritized before others, but I generally feel we should frontload this work in case anything unexpected is uncovered as part of it.

**Comment by courier-new** [comment]
Closed by https://github.com/sourcegraph/sourcegraph/pull/41396.
