### ISSUE TITLE
Higher base versions of code hosts

### ISSUE THREAD

**Issue by chrispine** [sourcegraph/sourcegraph#38971]
By removing support for old/outdated versions of code hosts, we can clean up our code and support more modern features/APIs.

[discussion in Slack](https://sourcegraph.slack.com/archives/C02EDAQAJQZ/p1657650372337439) about GitLab specifically

**Comment by courier-new** [comment]
P0 or P1. In general with the issues tagged `4.0` I don't feel that any particular issues need to be prioritized before others, but I generally feel we should frontload this work in case anything unexpected is uncovered as part of it.

**Comment by eseliger** [comment]
I think @courier-new did this ticket by bumping it in the docs, correct? Can we close this then? 

The actual switching to gitlab GraphQL which we're getting out of this is tracked separately anyways.

**Comment by courier-new** [comment]
Yeah I implemented https://github.com/sourcegraph/sourcegraph/issues/40106 and followed a file-up issue to promote it from a warning to an error for 4.0. If we have the API switching work tracked in a separate issue, I think we can close this.
