### ISSUE TITLE
Remove any fallbacks to global code host tokens

### ISSUE THREAD

**Issue by chrispine** [sourcegraph/sourcegraph#38972]
Remove any fallbacks to global code host tokens (and testing it all)

**Comment by courier-new** [comment]
P0 or P1. In general with the issues tagged `4.0` I don't feel that any particular issues need to be prioritized before others, but I generally feel we should frontload this work in case anything unexpected is uncovered as part of it.

**Comment by chrispine** [comment]
dupe of #25394
