### ISSUE TITLE
It is not clear that externalURL must be configured

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#3899]
Some customers like https://app.hubspot.com/contacts/2762526/company/464956351 have reported issues due to us not making it clear this should be configured. There should be a validator which confirms this has a non-default value AND when the config is invalid we should display a banner to the admin.

**Comment by beyang** [comment]
Should we add this to the activation steps, too?

**Comment by sqs** [comment]
Yes, that would be good.

**Comment by slimsag** [comment]
A customer just got seriously bitten by this and it was VERY painful to debug. See https://github.com/sourcegraph/infrastructure/issues/1514

Given this, I am kicking this out of backlog for us to reprioritize.

**Comment by slimsag** [comment]
We didn't get to this but it remains VERY important. See https://github.com/sourcegraph/infrastructure/issues/1514 for an example of how awful this can be for customers.

**Comment by slimsag** [comment]
This didn't make 3.8.

**Comment by unknwon** [comment]
#5656 has been merged, can we close this one now?
