### ISSUE TITLE
Adjust notepad display so it doesn’t overlap with the author component or the find references pane

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#38991]
## Problem
We currently display the file author information in the bottom corner of the file view. We also display the notepad component in a similar location and they often overlap.

This is (for now) the most convenient and usable location for the notepad. Author information is not always necessary, but without keybindings, the user can only access the notepad via UI actions.

![Image](https://user-images.githubusercontent.com/4605817/177200581-c1cd256a-e43f-465c-8c82-347f145b7a59.png)

Probably we should move the author somewhere else if we want it to always be visible. No reason for it to be perpetually floating like it is now.

Then, make sure the notepad is always above the references panel. Currently it is on top of it but in the bottom right corner, covering part of the refs pane.

**Comment by malomarrec** [comment]
Hey @benvenker, this issue didn't have a team label. Given you created it, I assigned you and added your team label. Feel free to unassign yourself. If this is not the right label, can you make sure to add the right one?

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by camdencheek** [comment]
Notepad has been removed
