### ISSUE TITLE
Better browser extension setup help

### ISSUE THREAD

**Issue by ceecurvin** [sourcegraph/sourcegraph#3901]
#### Feature request description

I have a very simple request, and it's not really a feature. As a first-time user, I was a bit lost on how to set up the extension. While it only took me ~5 min to figure it out, it would have been great to know that the URL in the extension stays the same. I kept changing it to my github repositories thinking that was what I was supposed to do.

Other than that, Sourcegraph is a pretty neat tool I wish I had when I was first introduced to  code reviews. This tool allows for more productive work rather than going down rabbit holes trying to understand what someone else's code is doing or means.

**Comment by felixfbecker** [comment]
Hi @ceecurvin, what would have helped you the most?
- more in-product help/guides e.g. in the option page?
- more documentation on [our docs page](https://docs.sourcegraph.com/integration/browser_extension)
- more links to that?

**Comment by felixfbecker** [comment]
This is addressed with RFC 221 #14165 🚀
