### ISSUE TITLE
sg maintenance: Identify pain points and build domain knowledge

### ISSUE THREAD

**Issue by indradhanush** [sourcegraph/sourcegraph#39025]
`sg maintenance` has been a source of frustration off late with frequent errors due to repo corruption and consequently repos not being available for search and / or being recloned endlessly.

We've noticed these especially in #inc-115 and #inc-120 recently.

Additionally, some customers have also faced issues with `sg maintenance`. 

We should deep dive this part of the code, identify ways we can improve the user experience and eventually build expertise on this area of the code. Additionally we should stress test this ourselves to ensure we've resolved the major pain points (and hopefully found a few before our customers do).

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.

**Comment by indradhanush** [comment]
https://github.com/sourcegraph/sourcegraph/pull/38947 should help resolve the conflict between sg maintenance and git's default gc.

**Comment by ryanslade** [comment]
Another data point:

In [this issue](https://github.com/sourcegraph/customer/issues/1203) we were seeing repo corruption when cloning a Perforce depot using `p4-fusion`. After disabling sgm the issue went away but this is not a good long term solution as their repo will become slow over time.

**Comment by indradhanush** [comment]
Superseded by #42207. Closing.
