### ISSUE TITLE
Include the commit that was used to build the client bundle and make it easily available. 

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#39034]
Follow-up to https://github.com/sourcegraph/sourcegraph/pull/38940

During our sync call with @valerybugakov we thought about adding a simple mechanism that would expose with which commit the client bundle was build. Something like `window.context.bundleCommit` or better. 

This way, we could potentially see asap if a single container (server) deployment is running with a cached version of the bundle that should have been invalidated.

**Comment by sourcegraph-bot-2** [comment]
Heads up @taylorsperry @jasongornall - the "team/frontend-platform" label was applied to this issue.
