### ISSUE TITLE
Double check VS Code extension dependencies on SG extensions

### ISSUE THREAD

**Issue by ryankscott** [sourcegraph/sourcegraph#39045]

**Comment by philipp-spiess** [comment]
Hey @tjkandala: @taras-yemets, @vdavid, and me were wondering if you can help out with this? We saw that the VS Code extension currently also instantiates an extension host and we'd like to know what features it uses? i.e do we support specific extensions (maybe even code intel?)?

**Comment by tjkandala** [comment]
Hey @philipp-spiess, we support specifically (and only) code intel! 

We ensure that we [load only default extensions](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/vscode/src/backend/sourcegraphSettings.ts?L71:18), so we unnecessarily load git-extras as well, but we do not make use of Sourcegraph line decorations. We call the extension host API to translate Sourcegraph extension data for use with the VS Code extension API in the [`code-intel`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/vscode/src/code-intel/SourcegraphReferenceProvider.ts) directory just for core [language features](https://code.visualstudio.com/api/language-extensions/overview) (hover content, definitions, references).

We should be able to reduce indirection to go from:
`our provider registered with VS Code <-> Sourcegraph extension host in sidebar <-> code intel extension`
to 
`our provider registered with VS Code <-> code intel functions in same context`
by bundling the code intel extension code for node/web worker environments (exact approach/details need exploration to arrive to, of course) along with the rest of the VS Code extension. The current model (sidebar webview extension host) was just a workaround to avoid adding a publishable `"node"` Sourcegraph extension type for the node environment (VS Code desktop). In hindsight, it was worth not investing in the real solution 😅.

**Comment by philipp-spiess** [comment]
Create a follow-up issue for the work necessary: #39353
