### ISSUE TITLE
As sourcegraph.com extensions registry (and the corresponding page) will not be available, suggest using src CLI to view and manage extensions

### ISSUE THREAD

**Issue by ryankscott** [sourcegraph/sourcegraph#39041]

**Comment by philipp-spiess** [comment]
I've thought about making changes to https://docs.sourcegraph.com/extensions to mention the CLI but it's really unclear to me what the value of that is?

With the 4.0 release we probably want to remove those docs anyways 🤔 Should we perhaps create a one pager doc instead that explains how the legacy extension APIs work if people need to turn it on?

**Comment by philipp-spiess** [comment]
cc @muratsu @ryankscott @jjinnii @taras-yemets @vdavid

**Comment by ryankscott** [comment]
Yeah I think this was created in our initial breakdown of work and probably doesn't make sense anymore. If people **need** extensions, they should enable the feature flag.
