### ISSUE TITLE
Make sure that the “copy” command in src cli fails against a post-4.0 instance

### ISSUE THREAD

**Issue by ryankscott** [sourcegraph/sourcegraph#39044]

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by philipp-spiess** [comment]
Some context in: https://sourcegraph.slack.com/archives/C01T0BL4EFN/p1658940250170299
