### ISSUE TITLE
What are question marks on feature list on website?

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#3906]
![image](https://user-images.githubusercontent.com/10532611/57442936-5116ae80-724d-11e9-9399-4b1ecfa0f57f.png)

It looks like we don't actually have these features yet, but just question marks don't clearly communicate that, they are more confusing. Are these supposed to have a hover tooltip?

**Comment by sqs** [comment]
Yes, they have a hover tooltip. Do you not see them?

**Comment by felixfbecker** [comment]
Nope, not seeing any in Chrome 74

**Comment by felixfbecker** [comment]
Oh, it's native HTML `title`s. They take forever to show up and are really small.
