### ISSUE TITLE
Investigate long wait times on internal rate limiter

### ISSUE THREAD

**Issue by indradhanush** [sourcegraph/sourcegraph#39069]
Initially reported in https://github.com/sourcegraph/customer/issues/1127. 

This is also evident in S2:

[Dashboard
](https://sourcegraph.sourcegraph.com/-/debug/grafana/d/repo-updater/repo-updater?viewPanel=100250&orgId=1&from=now-30d&to=now)
![image](https://user-images.githubusercontent.com/2682729/179771236-12c23a76-fc65-409e-bc72-f7d02570bad4.png)

Also to be investigated why there have been no alerts that triggered for this.

**Comment by mrnugget** [comment]
Wait times seem normal again. I also think that permission syncing improvements to rate limiters have helped a ton. Closing this.
