### ISSUE TITLE
repo-updater/githubConnection: Fetch `repos` in batch

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#3907]
While investigating why the repo-updater became unresponsive in our k8s dogfood instance, @tsenart and I discovered that the repo-updater was busy calling `GetRepository` for each of the ~13k entries in the `repos` field of the configuration.

Here is the loop:

https://github.com/sourcegraph/sourcegraph/blob/eef7a0bfcdc419823ea9fb5e8b5658f5766825c4/cmd/repo-updater/repos/github.go#L546-L571

Even if you don't have 13k entries in `repos`, fetching 1k sequentially with an average duration of ~120ms per request would still take 2 minutes. That's 2 minutes until repo-updater becomes responsive.

@keegancsmith suggested that we could probably fetch repositories in batches by switching to the GraphQL API, so we should definitely investigate this further.

**Comment by keegancsmith** [comment]
FYI @beyang had a recent PR which used this technique for the auth code.

**Comment by tsenart** [comment]
This one: https://github.com/sourcegraph/sourcegraph/pull/3881

**Comment by tsenart** [comment]
> That's 2 minutes until repo-updater becomes responsive.

This comment just made me realise that for large scale deployments where sourcing all repos is slow will indeed affect the startup time of repo updater substantially, because of the enabled state deprecation migration.

**Comment by beyang** [comment]
Maybe someone on @sourcegraph/core-services can give me a review on https://github.com/sourcegraph/sourcegraph/pull/3881. Stephen is pretty busy w/ P1s atm and auth stuff will come under core services' umbrella soon anyway. Pretty plz? :)
