### ISSUE TITLE
usage-data: scrape up to N events

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#39087]
[RFC 719](https://docs.google.com/document/d/1N9aO0uTlvwXI7FzdPjIUCn_d1tRkJUfsc0urWigRf6s/edit#)

Provide a mechanism to scrape up to N events from the buffered telemetry in `event_logs`. N should default to 5000, and be overridable with a setting. Tentatively this setting can be `maxScrapeSize`

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
