### ISSUE TITLE
usage-data: restrict scraped events to allow_list

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#39094]
[RFC 719](https://docs.google.com/document/d/1N9aO0uTlvwXI7FzdPjIUCn_d1tRkJUfsc0urWigRf6s/edit#)

Build an allow list that will restrict any scraped events to events on the allow list. Key the list by event name.

**Comment by coury-clark** [comment]
For simplicity sake, I'm going to put this in a new table for now. I don't have a good sense of how this will be used, or what kinds of trade offs we may want to make (putting it in config versus some file versus migrations, etc). 

That means that:
1. The source of truth won't necessarily be obvious in one file (unless you squash migrations)
2. Updates will need to come in the form of migrations (with insert statements)

To alleviate 1, I think it would be useful to lint / generate a markdown list of all of the allowed events.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
