### ISSUE TITLE
Opsgenie flakiness

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#3909]
We should stop the ephemeral alerts. There is one or two ones that are often ephemeral, lets adjust the triggers for them.

cc @sourcegraph/core-services

**Comment by slimsag** [comment]
Here's an alert that triggered on a gitserver deployment in prod, not sure if this is "flaky" or more expected given gitserver is so critical to all services -- but ideally it wouldn't happen on deploys of course: https://sourcegraph.slack.com/archives/C08JA8Q1H/p1557899101065100

**Comment by keegancsmith** [comment]
> Here's an alert that triggered on a gitserver deployment in prod, not sure if this is "flaky" or more expected given gitserver is so critical to all services -- but ideally it wouldn't happen on deploys of course: https://sourcegraph.slack.com/archives/C08JA8Q1H/p1557899101065100

Aah I didn't realise we deployed gitserver so often these days. In that case the alerts are more than likely surfacing a real (ephemeral) issue. But either way them constantly flipping isn't useful to our oncall users.

**Comment by keegancsmith** [comment]
I didn't actually investigate the old flakey alert this week, but it didn't seem to go off. I can't tell if this is due to:

- deploying the more aggressive gitserver disk space gc job, or
- being focussed on testing, so we did less continuous deploys

Lets see what the oncall looks like this week.

**Comment by keegancsmith** [comment]
scratch that, the flakey alert did continue. However, it only happened during PST daytime so I didn't notice.

**Comment by keegancsmith** [comment]
So I looked into this now. The way we integrate into site24x7 is using a deprecated API called "actions". The site24x7 UI doesn't expose this anymore, so you can't actually see how it integrates into opsgenie. So path forward options:

1. Update our provider to use new API. It is quite powerful and will allow us to configure thresholds / etc in quite a granular way.
2. Move all our ping checks into prometheus's blackbox-exporter. Then our customers could use most of them as well (cc @sourcegraph/distribution). We will still need to configure some sort of external pinger just to check our cluster is accessible.
3. Move to pingdom. I would still want to continue using terraform. There seems to be a reasonably popular provider for pingdom.

Site24x7 is actually pretty powerful, even though it doesn't seem that popular. So this may be the easiest route to take. However, option 2 has potential upsides for customers but is a bit more work. cc @sourcegraph/core-services

**Comment by tsenart** [comment]
If we end up not moving away from site24x7, this should be handled: https://github.com/sourcegraph/terraform-provider-site24x7/issues/7

**Comment by keegancsmith** [comment]
I think we can probably close this issue. It seems much better due to fixes to some bad registry endpoint and the go langserver being decommissioned. We also added some dedup in opsgenie for alerts from site24x7 so it isn't as bad when it does trigger.
