### ISSUE TITLE
Remove quicklinks

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#39098]
- Remove quicklinks from the UI (homepage and search sidebar) when the Simple UI toggle is on
- Mark quicklinks as deprecated in the settings schema and [docs](https://docs.sourcegraph.com/getting-started/personalization/quick_links)

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.
