### ISSUE TITLE
insights: create search insight changing from scoped to all repos modifies time granularity unit

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#39103]
When creating a search based insight checking the `Run your insight over all your repositories` changes the granularity units to months.

Steps to reproduce:
1. Click Create a new Insight and select Track Changes
2. Enter a single repository, series name and search query
3. Change the Granularity to 1 Week
4. The Live Preview Appears at 1 week intervals
5. Check the `Run your insight over all your repositories`

Expected behavior:
The Granularity should remain at 1 Week

Actual behavior:
That Granularity changed to 1 Month

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
