### ISSUE TITLE
insights: Modify OOB settings migration to be at 100% when it's a no-op

### ISSUE THREAD

**Issue by CristinaBirkel** [sourcegraph/sourcegraph#39106]
See: https://github.com/sourcegraph/sourcegraph/issues/38555
And: https://github.com/sourcegraph/sourcegraph/pull/39010

This issue enables us to deprecate our oob settings migration.

When code insights is disabled, the oob settings migration always remains at 0%. This is a problem because when we go to deprecate it, admins will get a message saying that they need to contact Sourcegraph support because their migration didn't complete.

Off the top of my head, I think we could add a dummy row to the `insights_settings_migration_jobs` _after_ adding all of the real rows, and then automatically mark it as complete. That way there will be something to signify that the migration is done even when there's no real work to do.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
