### ISSUE TITLE
Add functionality to `sg ops` to update GCR images for CloudSQL

### ISSUE THREAD

**Issue by kalanchan** [sourcegraph/sourcegraph#39102]
Currently `sg ops update-images` only updates DockerHub images, but we need to also update CloudSQL GCR images. 

Previously [Renovate](https://github.com/sourcegraph/deploy-sourcegraph-cloud/blob/4c094c17ac2107c4e8b657c1b2f1799e6f5d4e84/renovate.json5#L62) was able to handle this for us, but this has been replaced with a [github action](https://github.com/sourcegraph/deploy-sourcegraph-cloud/blob/release/.github/workflows/update-images.yaml).  

This improves upon https://github.com/orgs/sourcegraph/projects/212/views/37

**Comment by mucles** [comment]
per PR:https://github.com/sourcegraph/sourcegraph/pull/40291
Leaving non-Sourcegraph-built images to be updated by Renovate
