### ISSUE TITLE
usage-data: customer facing docs

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#39114]
Build some customer facing documentation to explain:
1. What this data pipeline does
2. What data is exported
3. How they can opt-in
4. Why we are collecting it

etc

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by coury-clark** [comment]
https://docs.sourcegraph.com/dev/background-information/data-usage-pipeline
