### ISSUE TITLE
insights: Add endpoint for RelatedInsightsForRepo

### ISSUE THREAD

**Issue by CristinaBirkel** [sourcegraph/sourcegraph#39123]
Part of https://github.com/sourcegraph/sourcegraph/issues/38428
Builds on: https://github.com/sourcegraph/sourcegraph/issues/39121

This endpoint will get insights with a `select:repo` field that match the file passed into the endpoint. See the main issue for more details. This can just return an array of matching insight ids.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
