### ISSUE TITLE
insights: Add endpoint for RelatedInsightsInline

### ISSUE THREAD

**Issue by CristinaBirkel** [sourcegraph/sourcegraph#39121]
Part of https://github.com/sourcegraph/sourcegraph/issues/38428

This is currently underway on branch: `insights/prototype-inline-insights`

See the main issue for an explanation of the approach. It's still in a prototype/experimental phase and the goal is to get something working as soon as possible to vet the approach.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
