### ISSUE TITLE
Code Insights: Scroll gradient doesn't work on initial render in Chrome 

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#39139]
Follow-up for https://github.com/sourcegraph/sourcegraph/issues/38836

Original comment from @AlicjaSuska 
>one small UI issue: the gradient on the key appears only after a scroll. It should be visible from the beginning ([loom](https://www.loom.com/share/16d01095d7ac4a8fa4458639ba6129f4))

Note that the tab component has similar visual logic about scroll and gradient; perhaps we should unify and reuse this logic to avoid bugs like this in the future.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
