### ISSUE TITLE
insights: test capture group insights with multiline matches

### ISSUE THREAD

**Issue by leonore** [sourcegraph/sourcegraph#39163]
We should be able to start using multiline matches in capture group insights: https://github.com/sourcegraph/sourcegraph/pull/39113#event-7030954029

we should test this does work with insights, and doesn't break (I'm pretty sure it used to time out every time in the query runner)

example multiline match: https://sourcegraph.com/github.com/renovatebot/renovate/-/blob/lib/modules/manager/terraform/__fixtures__/modules.tf

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by leonore** [comment]
this was tested to work (i.e. the `MatchComputeContextDecoder` does return this information now, we can use it)

however I can't seem to get a correct query to try this out on cc @Joelkw: would it be possible to get a representative query that customers would want to use this with?

e.g.
https://sourcegraph.sourcegraph.com/search?q=context:global+file:go%5C.mod%24+go%5Cs*%28%5Cd%5C.%5Cd%2B%29+%28.%5Cn*%29%2B+github.com/sourcegraph/log&patternType=regexp seems like one, but in the case of this search query there's an issue of what capture group we'd want to return?
