### ISSUE TITLE
Broken links in CONTRIBUTING.md

### ISSUE THREAD

**Issue by ismaelpadilla** [sourcegraph/sourcegraph#39188]
#### Describe the issue
The file [CONTRIBUTING.md](https://github.com/sourcegraph/sourcegraph/blob/main/CONTRIBUTING.md) has several broken links in the **Relevant development docs** section.

#### Where is the issue located?
The following links are broken:
[Getting Started Guide](https://docs.sourcegraph.com/dev/getting-started)
[Troubleshooting section](https://docs.sourcegraph.com/dev/how-to/troubleshooting_local_development)
[Size guidelines](https://handbook.sourcegraph.com/engineering/enablement#prefer-small-prs-400-lines)

**Comment by r-shahid** [comment]
These links have been updated! #39673
