### ISSUE TITLE
Decide on BC-related executor metrics for perf/correctness

### ISSUE THREAD

**Issue by chrispine** [sourcegraph/sourcegraph#39180]
[From this doc](https://docs.google.com/document/d/1Ss7ZffP82rV6nl4i5gBmICfuMK1xvSFI4Y5sLPXyDZc/edit#heading=h.p8es4qyv3ehl), with a deadline of 2022-08-22.

Batch Changes should own:
1. identifying the right metrics to review / alert on 
2. (if needed based on 1) owning instrumentation and alert definition
3. documenting how Cloud team can fix issues / when to delegate to Batch Changes

Cloud team should own:
4. wiring up instance-level alerts to Cloud on-call
5. documenting on-call procedure in Handbook
6. modifying Cloud tooling to automate fixes / detection

**Comment by chrispine** [comment]
Maybe leave this in Triage until we get some clarification in that doc?

**Comment by chrispine** [comment]
OK, updated the description; now I'm thinking P0?

**Comment by malomarrec** [comment]
Can this be exposed to self-hosted customers, too, or does that need to be another ticket?

**Comment by eseliger** [comment]
Metrics and alerts are usually portable, so should be for both. The _driver_ here is cloud but not the only beneficiary :)

**Comment by eseliger** [comment]
Let me find that out

**Comment by malomarrec** [comment]
Just following up on this ticket: is it safe to close with the current state, i.e. we decide not to track a metric? Also cc @chrispine

**Comment by eseliger** [comment]
Noah did some work on metrics stuff, like this one here: https://github.com/sourcegraph/sourcegraph/pull/40570.
Today, we don't have significantly better metrics at hand and with the massive variety of workloads we're running, it's hard to predict when things are _too slow_. So for now, this will have to suffice and we will add more alerts as we learn along the way.

**Comment by malomarrec** [comment]
cc @rafax given the above, I think we can close this and call the work required to get Batch Changes on all managed instances by default done.

**Comment by rafax** [comment]
Ack, I will update our Handbook to reflect that there's no great metric to track this, and once we confirm executors are healthy further troubleshooting will be owned by Batch Changes team.

**Comment by eseliger** [comment]
sounds good, thanks!

**Comment by eseliger** [comment]
Closing as this has been added to the handbook.
