### ISSUE TITLE
insights: Backend support for inline links to insights prototype

### ISSUE THREAD

**Issue by CristinaBirkel** [sourcegraph/sourcegraph#39191]
This is sort of a placeholder issue for the iteration, anticipating that when we integrate our new `RelatedInsights` routes with the webapp there will be some need for backend fixes, tweaks, and additional testing on `k8s`.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by felixfbecker** [comment]
@CristinaBirkel was this done? It's in "Done" but not closed
