### ISSUE TITLE
Investigate: how best to generate file patches in Go

### ISSUE THREAD

**Issue by courier-new** [sourcegraph/sourcegraph#39194]
Determine the best way to generate file patches in Go, ideally without needing to work with an actual filesystem and `git diff`.

**Comment by courier-new** [comment]
P0, estimate pending Bolaji's investigation. This is a prerequisite for basically any other work on search-and-replace to happen.

**Comment by BolajiOlajide** [comment]
I did a bit of research into this and [came up with this document](https://docs.google.com/document/d/1V_A-8nFeg0KctaR1CHLrCzZoiaSzLKrNI-7ltVQSdiM/edit?usp=sharing).

**Comment by BolajiOlajide** [comment]
I've updated the document above.

### Conclusion

After exploring all the libraries listed below, it’s evident that we’ll have to write our own implementation to generate a git-compatible patch that can be applied.
A patch in this case refers to the outcome of running `git diff` when a set of changes has been made in a repository. The patch must be applicable with the command `git apply <path/to/patch>`.

The best option to consider as a starting point for our implementation is [go tools](https://github.com/golang/tools/tree/master/internal/lsp/diff), it’s well maintained and the output is very similar to the output of `git diff`. I’ve [created a fork of `go/tools`](https://github.com/BolajiOlajide/go-diff-patch) that strips away all the unnecessary code and only contains the ones relevant for our use-case. It’s still WIP.

cc @sourcegraph/batchers
