### ISSUE TITLE
insight: new experimental resolver to support limited preview insights based on a search 

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#39222]
Part of https://github.com/sourcegraph/sourcegraph/issues/38430

## Problem 
At the moment we have to pass a clear list of repositories for the live preview as input to gql query. But on the search result page we don't have a clear list of repositories, instead of this we have `repo:` filters and query itself. 
We should extend live preview API in a way that it supports either 
- `repo:` filter value (note that this value could be complex with AND/OR operators and we can have more than one repo filter in one query)
- passing query itself and resolve live preview data by query and not by repositories and other low level fields that we have in the creation UI

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by vovakulikov** [comment]
It seems like first point here woudln't solve the problem. Imagine we have the following query 
`(test repo:^github\.com/sourcegraph|about) or (insight repo:^github\.com/sourcegraph/about$)`

In this case even if we parse query and extract repo filters we still are loosing query semantic here and hence we will have a wrong result in live preview. 

This makes me think that we should support query value in live preview gql resolver
cc @sourcegraph/code-insights-backend

**Comment by vovakulikov** [comment]
Points from sync with @chwarwick 
- We probably should create another gql resolver for this prototype and not using live preview resolver from the creation UI
- This new resolver will be used for the live preview button with 2 point trend (the button right below the search query input) and for the chart in the sidebar. Same resolver but with different input data (number of points) 
- This resolver should take query as an input parameter and process query on the backend. If code insighs backend can't process this query should return an error.

**Comment by chwarwick** [comment]
This resolver should:

- Determine the number of repos targeted by the search if it is  > TDB  return that an insight on this search is unsupported
- The most recent data point should match the search that was run by the user
- Accept but limit the number of historic data points and the interval between them  - limits TBD
- Maintain an allow or deny list of search parameters (TBD) to avoid running overly expensive historic queries.

**Comment by chwarwick** [comment]
dependent on https://github.com/sourcegraph/sourcegraph/issues/39222 for determining number of repos search executes against.

**Comment by chwarwick** [comment]
> > Maintain an allow or deny list of search parameters (TBD) to avoid running overly expensive historic queries.
> 
> Is there any more context here? What are some examples driving this need?

I'm not 100% sure but wanted to capture that initially as something to think about.  Maybe it ends up a deny list may end up empty, but fresh in my mind was commit & diff search and wanting to avoid that.

**Comment by chwarwick** [comment]
@vovakulikov  is this resolved now because of the new repo search insights?

**Comment by chwarwick** [comment]
Resolved due to insights now supporting specifying repos via a repo search.
