### ISSUE TITLE
Align Show More to center to be consistent with #37189

### ISSUE THREAD

**Issue by danielmarquespt** [sourcegraph/sourcegraph#39220]
Align "Show More" on "Files Changed" to the center so it is consistent with https://github.com/sourcegraph/sourcegraph/pull/37189

![Image](https://user-images.githubusercontent.com/7814431/180193840-c99cabe8-9d07-446d-aeb2-c5a46320fc60.png)

**Comment by chrispine** [comment]
If it's not a lot of work, P1?

**Comment by LawnGnome** [comment]
0.5d; P0/1?
