### ISSUE TITLE
insights: determine if a search query would execute against a single repo

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#39241]
To determine if it is possible to provide a preview of an insight for a search query it is necessary to understand how many repositories the search is going to target to ensure that the historical searches can be run in a timely manner without placing too large a large load on dependent systems.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by chwarwick** [comment]
The query parser can be used to extract repo filters from the query, which can then be used to issue queries against the repo table in the database.

Must account for queries with multiple repo filters and more complex queries combined with AND/OR to ensure an accurate count.

**Comment by chwarwick** [comment]
Implementing as check if a query targets a single repo or not, this will provide enough support the issues depending on this item.
