### ISSUE TITLE
Install and configure `OpenTelemetry` packages required for client tracing.

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#39273]
## Context

Add basic configuration of the OpenTelemetry tracing to the web application. 

[Honeycomb guide](https://docs.honeycomb.io/getting-data-in/opentelemetry/browser-js/)
[Prior work](https://github.com/sourcegraph/sourcegraph/pull/37843)

**Comment by sourcegraph-bot-2** [comment]
Heads up @taylorsperry @jasongornall - the "team/frontend-platform" label was applied to this issue.
