### ISSUE TITLE
Integrate client tracing with backend `OpenTelemetry` tracing passthrough

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#39277]
## Context

[Integrate client with backend tracing passthrough](https://github.com/sourcegraph/sourcegraph/issues/37907).

See more details discussed with @bobheadxi [here](https://docs.google.com/document/d/1pYgSqJUE9M0_LZFUBzL-5nRTpmbMqXsWCUVU32J-AEo/edit#).
See [the OTLP Receiver docs](https://github.com/open-telemetry/opentelemetry-collector/blob/main/receiver/otlpreceiver/README.md)

**Comment by sourcegraph-bot-2** [comment]
Heads up @taylorsperry @jasongornall - the "team/frontend-platform" label was applied to this issue.

**Comment by valerybugakov** [comment]
Closed by https://github.com/sourcegraph/sourcegraph/pull/39401
