### ISSUE TITLE
Configure client `OpenTelemetry` React components instrumentation

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#39282]
## Context

Configure client `OpenTelemetry` React components auto-instrumentation or a set of utilities to easily instrument React components rendering and hooks. See [a related auto-instrumentation from the OpenTelemetry repo](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/web/opentelemetry-plugin-react-load)

**Comment by sourcegraph-bot-2** [comment]
Heads up @taylorsperry @jasongornall - the "team/frontend-platform" label was applied to this issue.
