### ISSUE TITLE
Configure client `OpenTelemetry` network calls auto-instrumentation

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#39281]
## Context

 Configure client `OpenTelemetry` network calls auto-instrumentation.
See [a related auto-instrumentation from the OpenTelemetry contrib repo](https://github.com/open-telemetry/opentelemetry-js/tree/main/experimental/packages/opentelemetry-instrumentation-fetch)

**Comment by sourcegraph-bot-2** [comment]
Heads up @taylorsperry @jasongornall - the "team/frontend-platform" label was applied to this issue.
