### ISSUE TITLE
repo-updater fails to get updates from local repos served via fakehub

### ISSUE THREAD

**Issue by ijt** [sourcegraph/sourcegraph#3929]
#### Steps to reproduce:

1. `mkdir foo`
2. `cd foo`
3. `echo 'func blah() {}' > blah.go`
4. `git init && git add . && git commit -a -m 'add blah.go'`
5. `cd .. && fakehub .`  # launches web server on localhost:3434
6. In another terminal, run sourcegraph using `dev/launch.sh`.
6. Copy config from http://localhost:3434, paste into sourcegraph, following comment at top.
7. Search for blah on local sourcegraph. It should show one result in blah.go.
![Screen Shot 2019-05-10 at 14 45 46](https://user-images.githubusercontent.com/15530/57558494-b8f2f500-7332-11e9-96f9-cdd9d2827952.png)
8. Back in `foo`, `echo 'func yarr() {}' > yarr.go && git add yarr.go && git commit -a -m 'add yarr.go'`
9. Wait for repo updater to run. Hits are logged in `fakehub` output for `/repos/foo/.git/info/refs` and `/repos/foo/.git/HEAD`.
10. Search for yarr on local sourcegraph. 

#### Expected behavior:

A single result should come up in `yarr.go`.

#### Actual behavior:

No results.

![Screen Shot 2019-05-10 at 14 47 54](https://user-images.githubusercontent.com/15530/57558507-c4deb700-7332-11e9-88b0-cd6d52db37b4.png)

**Comment by keegancsmith** [comment]
Can you share the relevant logs which point to the problem? I'm unsure if the logs you refer to say that we have run `git fetch` or if we have just re-checked the metadata.

what happens when you search `index:no`? My gut tells me this is just a delay for zoekt to reindex the repo?

**Comment by ijt** [comment]
The logs from fakehub look like this:
```
2019/05/15 10:52:59 GET /repos/foo/.git/HEAD
2019/05/15 10:53:19 GET /repos/foo/.git/info/refs
2019/05/15 10:53:19 GET /repos/foo/.git/HEAD
2019/05/15 10:53:19 GET /repos/foo/.git/info/refs
2019/05/15 10:53:19 GET /repos/foo/.git/HEAD
```
It's just a re-check of the metadata.

Searching with `index:no` still yields no results.
