### ISSUE TITLE
Spike: Review tech debt/product pain point

### ISSUE THREAD

**Issue by unclejustin** [sourcegraph/sourcegraph#39309]
During our retrospective, we raised concerns about tech debt and general pain points in our codebase.

This spike is to create or surface actionable issues that we can size and schedule. The purpose of these issues is to create room in the iterations to make progress on these problems and grant visibility into the state of our codebase for stakeholders that do not work in the code daily. 

Notes:

1. This is not meant to be an exhaustive list. We will discuss top priority concerns and create issues for them as we can. It is expected that several of these issues will themselves be spikes to take deeper dives into a particular problem
2. This spike is timeboxed to 1 hour so that we can get as many engineers in the same meeting as possible and to keep us from going overboard.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by vovakulikov** [comment]
[Notes](https://docs.google.com/document/d/1AiAeA6ljpKw7dVI2H8uGEjMVENLi0Sue0nVNbxcwjWM/edit?usp=sharing) from meeting with chris about BE + FE tech debt/perf problems
