### ISSUE TITLE
Test: TestBitbucketProjectsPermsSync_SetPermissionsUnrestricted times out

### ISSUE THREAD

**Issue by burmudar** [sourcegraph/sourcegraph#39315]
See the following builds:
* https://buildkite.com/sourcegraph/sourcegraph/builds/162722#018226e1-881e-4777-b4dc-8dcf5215a644
* https://buildkite.com/sourcegraph/sourcegraph/builds/162711#018226aa-3eab-4a76-9138-c7689e3c3403
* https://buildkite.com/sourcegraph/sourcegraph/builds/162725#018226f5-931f-456f-b80a-83a09241b06f

Disabled in:
https://github.com/sourcegraph/sourcegraph/pull/39314

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.

**Comment by sashaostrikov** [comment]
Closed by https://github.com/sourcegraph/sourcegraph/pull/54477
