### ISSUE TITLE
Admin analytics UI tweaks

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#39310]
Several improvements can be made to increase the readability, visual appearance, and utility of the admin analytics pages: 

- [ ] KPI helper text styles should be text-muted
- [ ] Total and unique button group labels should be "Total events" and "Unique users"
- [ ] Adding a display daily/weeklyselector for controlling how the chart renders
- [ ] Using headers to describe columns in all value calculators instead of repeating labels for each input field 

## Design process

- Estimate: Less than a day
- Weighting factors:
  - [MEDIUM|LOW] risk
  - [HIGH|MEDIUM] clarity

### Discover
- [x] Product and/or engineering provide direction and/or feedback

### Define
- [x] Github issue

### Design
- [x] High fidelity design using design system - [Figma](https://www.figma.com/file/mmWwgzzqTmpLsxwmiiZwfE/Admin-analytics?node-id=1335%3A7488)
- [x] Non-visual design guidance captured in the issue

### Testing
- [ ] Hallway testing - Link

### Deliver
- [ ] Team review

**Comment by thenamankumar** [comment]
skipping adding monthly aggregation option as we have only 3 months data.

**Comment by rrhyne** [comment]
Makes sense
