### ISSUE TITLE
Add progress, size, counts, and analytics to the repositories view

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#39327]
#### Feedback

It's difficult to see what's going on with repositories in the current view.  Things that would help:

*Repository Settings Page* (`/<repo>/settings`)
- Additional analytics about each repository
   - How often does this repo appear in search results
   - How often do people click on results from this repository
   These help admins determine if it's worth it for them to keep these repositories (i.e., a very large repo that never or rarely shows up in a search might be a candidate to exclude from Sourcegraph)

#### Parts that are already done

*Repositories View* (`/site-admin/repositories`)
- [x] When a repo is "cloning", show the progress. #50234
   This along with the repository size in this view will help answer questions like "Why is this repo taking so long to clone?".  Both of these are available by clicking on the repository but if you have many repos in the cloning state, this can be cumbersome.
- Show repository sizes
- Counts for each state
    - Discovered
    - Cloned
    - Indexed
   Right now it's difficult to get a bird's eye view of the "current state" (i.e., discovered 10,000 repositories, 5,000 have been cloned, and 2,500 have been indexed, etc.)

#### Customer

https://github.com/sourcegraph/accounts/issues/6716
- [Slack discussion thread](https://sourcegraph.slack.com/archives/C01D50MSA7L/p1658439241328369)

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.

**Comment by mrnugget** [comment]
Came across this ticket again. Update from my side:

* _Show repository sizes_: done
* Counts for each state: done

**Comment by mrnugget** [comment]
Notes from grooming:

- [ ] Show "cloneProgress" on repos list page by querying `cloneProgress` (https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/schema.graphql?L3359-3368) and showing it in `<Code>` on list page

The analaytics part we can't do. That's out of scope for a single ticket and would require work in search.

**Comment by mrnugget** [comment]
Update from planning: when putting this info on the `/repositories` page we shouldn't do N+1 calls to gitserver to fetch this information. 

Option 1: batch requests to gitserver when constructing the repositories connection
Option 2: persist cloning status periodically to database (on regular interval, with rate limiter, example: https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/repos/syncer.go?L113:20)

**Comment by cbart** [comment]
Note: Currently this worked is scoped to:

> When a repo is "cloning", show the progress.
> This along with the repository size in this view will help answer questions like "Why is this repo taking so long to clone?". Both of these are available by clicking on the repository but if you have many repos in the cloning state, this can be cumbersome.

**Comment by cbart** [comment]
Starting with:
![Screenshot 2023-03-24 at 11 47 15 AM](https://user-images.githubusercontent.com/153410/227589043-ee402217-0511-46d1-b6a9-626b83f79820.png)

Problem: We're adding another piece of information (cloning progress) to the repo list item in repos view. There's bunch of data there already. GPT-4 suggests making it a card.

![Screenshot 2023-03-24 at 11 46 43 AM](https://user-images.githubusercontent.com/153410/227588958-5431a94f-f4f7-4658-b19f-bbf337adcb69.png)

**Comment by cbart** [comment]
![Screenshot 2023-03-24 at 11 58 55 AM](https://user-images.githubusercontent.com/153410/227605782-8b29b8f5-5853-44db-9505-1ee1b382666e.png)


![Screenshot 2023-03-24 at 1 07 13 PM](https://user-images.githubusercontent.com/153410/227605699-76165d4e-d091-4771-bd43-81362b6d9dcd.png)

**Comment by mrnugget** [comment]
cc @varsanojidan who also worked on this page and cc @danielmarquespt who has some thoughts

**Comment by cbart** [comment]
Something's wrong here. This was working when landing https://github.com/sourcegraph/sourcegraph/pull/50234, but I noticed on dotcom and locally I don't see the progress being displayed in repos.

**Comment by cbart** [comment]
I'll take care of this when I'm back from sick leave.

**Comment by mrnugget** [comment]
Is it the feature flag being off by default?

**Comment by cbart** [comment]
OK. Now I get it. Most clones I see on dotcom are `npm/...` repos, which means (?) there isn't a git output to cloning them as far as I understand. But I see that when a git repo appears, there isn't sometimes a line break between the status line and cloning progress. Let me fix this.

**Comment by cbart** [comment]
Since this ticket mentioned extra analytics, I think I should move it to the backlog for further planning & grooming of that work.

**Comment by mrnugget** [comment]
I'm closing this for now. Keeping this ticket around doesn't help. If we bump into the need again, let's create a new ticket.
