### ISSUE TITLE
Get rid of Bootstrap style imports in `vscode` package

### ISSUE THREAD

**Issue by gitstart-sourcegraph** [sourcegraph/sourcegraph#39345]
## Problem statement

We depend on Bootstrap styles in our global styles a lot. But we don't plan to move forward with Bootstrap because we're working on our design system called Wildcard. To ease the transition to our styles and gain more control over visual changes, we want to move Bootstrap styles _that we need_ into our codebase and eventually drop Bootstrap dependency.

## Success criteria

All Bootstrap CSS rules that we need are incorporated in our codebase. 

## Implementation details

Let's create a separate PR to work on each `SCSS` files import 

Notes:
1. We want to migrate away from SCSS variables to CSS variables when we bring Bootstrap styles to our codebase.
    - Some Bootstrap SCSS variables redefined on our side are located here: `client/branded/src/global-styles/index.scss`. Keep that in mind while migrating to CSS variables. 
2. We don't need to bring all styles defined in the imported Bootstrap package. Check what styles do we use in the codebase first.
3. Some extractions has been done as part of the migration in `web` package, which is imported to the `vscode` package 

## Time estimate

- Pull requests with ~450 lines changed should take **8 hours** at maximum. Ping the reviewer in the spec pull request if time-consuming changes are required.
- Split the work into multiple pull requests if the total diff is bigger than 450 lines of code.

**Comment by sourcegraph-bot-2** [comment]
Heads up @taylorsperry @jasongornall - the "team/frontend-platform" label was applied to this issue.
