### ISSUE TITLE
Ensure code intelligence still works on VS Code

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#39353]
Similar to #38532 but for VS Code

As we're sunsetting Sourcegraph extensions we need to ensure that:

- Code intelligence still works with our VSCE
- We don't break anything for users on older versions of Sourcegraph

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
