### ISSUE TITLE
Code Ownership: Test prototype on a massive repository 

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#39354]
We came across https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/.github/CODEOWNERS which seems like a good start.

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by philipp-spiess** [comment]
Results in this thread https://sourcegraph.slack.com/archives/C03Q186LKUY/p1658756396116409
