### ISSUE TITLE
Fix accessibility labels for branches

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#39360]
Followup to https://github.com/sourcegraph/sourcegraph/pull/38285 which is a little imprecise, we discussed that we want to make the wording here better and more explicit.

**Comment by chrispine** [comment]
P1?

**Comment by eseliger** [comment]
Since accessibility has been frozen for a bit to do some more work for the next few releases, should we reflect that for our team and make this a P2/backlog item, too?

**Comment by courier-new** [comment]
I've taken inspiration from how GitHub reports branches on PR pages and implemented improvements here.

**Comment by courier-new** [comment]
Closed by https://github.com/sourcegraph/sourcegraph/pull/44263.
