### ISSUE TITLE
New symbol results are behaving weirdly

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#39374]
You can try different languages. It's broken for python, typescript, and C# at least

https://sourcegraph.com/search?q=context:global+auth+test+type:symbol+lang:c%23+&patternType=lucky

![image.png](https://images.zenhubusercontent.com/5467e9ba7c6ccc6277a5f103/8be6d77f-151d-4b37-aff3-8c6e4404c567)

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by lguychard** [comment]
@novoselrok This had no assignee; I'm going to assign you because you last worked on it, but if you need to reassign we can talk about it at the next sync.

**Comment by novoselrok** [comment]
Already fixed 🙂
