### ISSUE TITLE
regex lazy quantifier not highlighted in codemirror query bar

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#39387]
the `?` isn't highlighted in codemirror (but the hover works)

<img width="372" alt="Screen Shot 2022-07-25 at 2 02 41 PM" src="https://user-images.githubusercontent.com/888624/180873873-115208fb-c77e-4430-bd66-e748af5e0bb6.png">

<img width="957" alt="Screen Shot 2022-07-25 at 2 02 49 PM" src="https://user-images.githubusercontent.com/888624/180873847-932e63af-23f8-4c56-8125-c0ef5a8f56a0.png">

works in monaco:

<img width="369" alt="Screen Shot 2022-07-25 at 2 03 59 PM" src="https://user-images.githubusercontent.com/888624/180873822-d11536ae-b365-43c3-953d-d9deb7f87c1b.png">

think we are just missing some decorator on the CM side

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by fkling** [comment]
Seems like it tries to use the color `var(--search-regexp-meta-character-lazy-quantifier-color)` which doesn't exist.
