### ISSUE TITLE
Increase default match chunks to 3 in beat UI search results

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#39388]
We've gotten some fairly consistent feedback that only showing 1 match chunk makes the search results basically useless in certain cases that aren't uncommon, so we'd like to be more generous here. 3 seems like a good next increment, but we'll validate in our research.

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.
