### ISSUE TITLE
usage-data: populate fields with data previously available on dot-com

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#39391]
If we compare the fields from the [dot-com event stream](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/usagestats/event_handlers.go?L100-116&subtree=true) and from the [persisted event_logs table](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/types/types.go?L1216-1226&subtree=true) there is a number of fields that are not available in the event_logs table.

```
FirstSourceURL
LastSourceURL
FeatureFlags (exists but not populated)
CohortID (exists but not populated)
Referrer 
DeviceID
InsertID
```

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by coury-clark** [comment]
Here is a query showing the different versions of the Event struct https://sourcegraph.sourcegraph.com/search?q=context:global+type+Event+struct+%7B...Argument...%7D+lang:go+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+&patternType=structural
