### ISSUE TITLE
Close batch changes that are in draft status

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#39409]
#### Current state / problem 

Today, when you run a batch changes server-side, a draft batch change is created, that contains the preview.
There's no way to close/remove one of those draft batch changes.

#### Proposed solutions

While some executions are actual draft (I want to get back to it later), some are not valuable to persist (I played with it, and don't need it anymore). It'd probably make sense to have a `discard` button easily accessible from the batch change execution page, and maybe from the batch changes list.

**Comment by danielmarquespt** [comment]
@malomarrec this is already reflected on this issue: https://github.com/sourcegraph/sourcegraph/issues/38713

I added some details, I think we can close this one.

**Comment by malomarrec** [comment]
Dammit, didn't find it. Sorry
