### ISSUE TITLE
Extract bootstrap style import `@import 'bootstrap/scss/transitions'`, `@import 'bootstrap/scss/forms'` in `client/vscode`

### ISSUE THREAD

**Issue by gitstart-sourcegraph** [sourcegraph/sourcegraph#39406]
## Problem statement
We depend on Bootstrap styles in our global styles a lot. But we don't plan to move forward with Bootstrap because we're working on our design system called Wildcard. To ease the transition to our styles and gain more control over visual changes, we want to move Bootstrap styles that we need into our codebase and eventually drop Bootstrap dependency.

## Ref
https://github.com/sourcegraph/sourcegraph/issues/39345

## Success criteria
1. All use cases of `form-*` are migrated to use wildcard's component.
1. @import 'bootstrap/scss/transitions' style import is removed

## Implementation detail
1.  Remove bootstrap import @import 'bootstrap/scss/card' in `forkedBranded.scss`.
2. Remove bootstrap import @import 'bootstrap/scss/transitions' in `forkedBranded.scss`
3. Covert use cases of `form-*` and transition className to wildcard component.
4. If step 2. above is not doable, let's copy style rule from bootstrap to be used internally.

## Time estimate

- Pull requests with ~450 lines changed should take **3 hours** at maximum. Ping the reviewer in the spec pull request if time-consuming changes are required.
- Split the work into multiple pull requests if the total diff is bigger than 450 lines of code.

**Comment by sourcegraph-bot-2** [comment]
Heads up @taylorsperry @jasongornall - the "team/frontend-platform" label was applied to this issue.
