### ISSUE TITLE
Add flag to keep legacy extensions system enabled

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#39429]
As a result from this thread, we'll add another flag that can be used to turn on legacy extensions for instances past 4.0: https://sourcegraph.slack.com/archives/C03P1V3J92P/p1658488293653899

Ideally we can hid this somehow so that we keep usage at a minimum (ideally we know everyone who uses this and can work with the customers on a reasonable upgrade path for them).

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by philipp-spiess** [comment]
Also: I think this should be an instance wide setting not a user specific one.

**Comment by philipp-spiess** [comment]
- [ ] Change the code landed in https://github.com/sourcegraph/sourcegraph/pull/39227 to use the this feature flag instead
