### ISSUE TITLE
Move git blame functionality to the core workflow

### ISSUE THREAD

**Issue by taras-yemets** [sourcegraph/sourcegraph#39433]
Under `extensionsAsCoreFeatures` experimental feature:
- make git blame functionality available as a part of the core product (file, commit and compare pages)
- do not load/activate `git-extras` extension
- each page should have its own blame visibility status (hidden by default).

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
