### ISSUE TITLE
Remove extensions decorations column display support

### ISSUE THREAD

**Issue by taras-yemets** [sourcegraph/sourcegraph#39437]
As we're going to [deprecate the current Sourcegraph extensions](https://handbook.sourcegraph.com/strategy-goals/strategy/integrations/#moving-extensions-into-the-core-workflow) there's no need in extensions decorations column view enabled under `enableExtensionsDecorationsColumnView` experimental feature (see PR https://github.com/sourcegraph/sourcegraph/pull/36007).

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
