### ISSUE TITLE
Src-cli latest version endpoint is unauthenticated and can fall back to different version

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#39468]
See https://sourcegraph.slack.com/archives/CMMTWQQ49/p1658873113895129, this endpoint uses unauthenticated requests to github which occasionally get rate-limited and thus we fall back to the minimumversion const. This is not necessarily problematic, but it causes us to serve different versions at various times during the day (at the very least the const, but not always the actually latest patch version)

**Comment by chrispine** [comment]
P0? (depending on what the estimate looks like)

**Comment by eseliger** [comment]
Not really sure yet what the fix should look like, so hard to estimate. I think using a github token for that request is not really feasible as not every instance will have a github code host, also we don't want to waste rate limit tokens for this, I guess.
Then we could try to cache it a bit better. Or we host the version somewhere ourselves so that no rate limit applies (GCS bucket?). I would say no more than 3d should be invested here, ideally less. If no one disagrees with all of the ideas, yes, let's prioritize it.

**Comment by courier-new** [comment]
Could we not host the recommended version somewhere on sourcegraph.com?

**Comment by eseliger** [comment]
Works, too.

**Comment by LawnGnome** [comment]
Likely path forward: have a Sourcegraph controlled endpoint that provides the latest patch for each branch as a static JSON or something similar.
