### ISSUE TITLE
When hovering on UserNavBar, blue color flashes

### ISSUE THREAD

**Issue by gitstart-sourcegraph** [sourcegraph/sourcegraph#39484]
## Problem statement
On hovering the UserNavItem, blue color flashes
https://www.loom.com/share/f3359ea119bd49babbbb2318515baba0

## Success criteria
Above mentioned bug is fixed

## Time estimate

- Pull requests with ~450 lines changed should take **X hours** at maximum. Ping the reviewer in the spec pull request if time-consuming changes are required.
- Split the work into multiple pull requests if the total diff is bigger than 450 lines of code.

**Comment by sourcegraph-bot-2** [comment]
Heads up @taylorsperry @jasongornall - the "team/frontend-platform" label was applied to this issue.
