### ISSUE TITLE
bext: command palette styles on GitHub seem broken

### ISSUE THREAD

**Issue by taras-yemets** [sourcegraph/sourcegraph#39495]
- **Sourcegraph version:**  Sourcegraph browser extension for Chrome v22.7.11.926
- **Platform information:**  Chrome v103.0.5060.134 

#### Steps to reproduce:

1. Open any file on GitHub with the browser extension enabled.
2. Open command palette.

<img width="843" alt="Screenshot 2022-07-27 at 16 42 35" src="https://user-images.githubusercontent.com/25318659/181262756-23c4c824-48da-4212-b975-0544aa656ab1.png">

#### Expected behavior:
Command palette item styles are consistent with the rest of the GitHub styles.

#### Actual behavior:
Command palette item styles seem broken (see screenshot).

If would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are not [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
