### ISSUE TITLE
Codeinsights page returning a Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by amberfurbush0317** [sourcegraph/sourcegraph#39527]
- **Sourcegraph version:**  3.40.1 
- **Platform information:** Docker

 Codeinsights history page returning an Unexpected token < in JSON at position 0

![image (54)](https://user-images.githubusercontent.com/85127819/181356497-9ee5502c-f1ed-4494-ba8d-d2095b950c1f.png)

#### Steps to reproduce:

1. Click on Codeinsights, and the error appears which prevents you from creating an insights graph

2. Error Message within Developer Tools: 
![2022-07-27_16-46-58](https://user-images.githubusercontent.com/85127819/181387139-2694adad-3a68-4c37-873b-3869b5b97d7b.jpg)

#### Expected behavior:

You should just be able to access the Code Insights page without error displaying and create the desired insight graphs. 

#### Actual behavior:

When experimenting with insights, this error shouldn't appear.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by felixfbecker** [comment]
Hey @amberfurbush0317, I don't think this is a specific "History" page, it's a specific insight named "History". Do you have a link to the insight? Is this on one of our instances?

**Comment by amberfurbush0317** [comment]
Hey, @felixfbecker I made mistake on that title fixing things now :) 

Thank you for pointing that out I have a few details to add to this one to make things clearer
