### ISSUE TITLE
Set git version to 2.35.2

### ISSUE THREAD

**Issue by varsanojidan** [sourcegraph/sourcegraph#39544]
As part of this [revert](https://github.com/sourcegraph/sourcegraph/pull/39537), we had to revert git version to a version that doesn't contain a fix for the this [CVE](https://github.blog/2022-04-12-git-security-vulnerability-announced/).

We want to upgrade to exactly git version 2.35.2 to have the fix for the CVE as well as avoid the commit-graph malformed bug we were experiencing [here](https://github.com/sourcegraph/sourcegraph/pull/37906)

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.

**Comment by mrnugget** [comment]
In newest `sourcegraph:gitserver/insiders` we're on

```
$ git --version
git version 2.41.0
```

Closing
