### ISSUE TITLE
JetBrains: Buttons in JCEF have pointer mouse icon on hover

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#39564]
When we hover the buttons and dropdown (incl. code completion dropdown), we see the pointer icon, which is fine in a browser, but we want to imitate native Swing behavior here, and this is currently the most obvious giveaway that something's off here.

[17-sec demo](https://www.loom.com/share/a7dd5f972b794180a0421ee7eb8f680f)

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
