### ISSUE TITLE
JetBrains: Make the plugin compatible with 2022.2

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#39571]
JetBrains [released](https://blog.jetbrains.com/idea/2022/07/intellij-idea-2022-2/) IntelliJ 2022.2 three days ago.
Our current version of the plugin doesn't work out of the box.

Three updates are needed:
- `platformVersion`: `2022.1` → `2022.2`
- `javaVersion`: `11` → `17`
- `org.jetbrains.intellij`: `1.6.0` → `1.7.0`

The good news is that after these updates, the plugin works in 2022.2

The bad news is that inside the JCEF component, we're somehow picking up the theme properties wrong:

Dark mode:
![dark mode](https://user-images.githubusercontent.com/2552265/181497684-e1ab4bfa-4e3b-428c-9a3c-458b8ec32e53.png)

Light mode:
![light mode](https://user-images.githubusercontent.com/2552265/181497691-319c00c9-3bca-4523-8381-38d17a359f74.png)

Also, the popup looks different after a theme change. Dark mode example:
![dark mode after theme change](https://user-images.githubusercontent.com/2552265/181497717-3ae63845-7d83-4a43-b237-f7422eae9f4b.png)

It should look more like the “Find in Files” popup in terms of colors, plus the theme should be the same after a new load as after a team change.

Everything else seems to work fine with 2022.2

**Comment by sourcegraph-bot-2** [comment]
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.
