### ISSUE TITLE
Create 1-click export view

### ISSUE THREAD

**Issue by sashaostrikov** [sourcegraph/sourcegraph#39589]
This is a compound issue for all the possible UI work required for https://github.com/sourcegraph/sourcegraph/issues/39588.

- [x] #39997
- [x] #39998
- [x] #39999

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.

**Comment by sashaostrikov** [comment]
the project is cancelled, closing the issue
