### ISSUE TITLE
Patch Release Request - 3.42.1

### ISSUE THREAD

**Issue by varsanojidan** [sourcegraph/sourcegraph#39591]
Check out #inc-124-gitserver-repos-are-corrupted in slack for full details of the incident and why this patch is being requested.

@sourcegraph/release-guild I am requesting the following commits be included in a patch release. They are already merged into `main`: 

- https://github.com/sourcegraph/sourcegraph/issues/39591
- https://github.com/sourcegraph/sourcegraph/commit/dd628e02c041d6100445d644cfecb95018bcc3d1
- 9d7b3fe4604ee8aa701b1bdee70230645ab59cd2
- ebdcc47f78b052bb9441c1b6aceae7c8f169d7b8
- 85d443b4e5c6a035c170e35a2aa0f07620cae060
- https://github.com/sourcegraph/sourcegraph/commit/b1ae5b52e54b03e6c133b9b07506536dbe11c1da

---

The intent of the questions below is to ensure we keep Sourcegraph high quality and [only create patch releases based on a strict criteria.](https://handbook.sourcegraph.com/engineering/releases#patch-releases) If you can answer yes to many or most of these questions, we will be happy to create the patch release.

I have read [when and why we perform patch releases](https://handbook.sourcegraph.com/engineering/releases#patch-releases) and answer the questions as follows:

> Are users/customers actively asking us for these changes and cannot wait until the next full release?

Not yet, this is preventative. But they will definitely start requesting this as more of them adopt 3.42.

> Are the changes extremely minimal, well-tested, and low risk such that not testing as we do in a full release is OK?

The changes include a revert to one commit that updated the version of git we are using on Gitserver, we know that the old version we reverted to works well because that's the version we were using in 3.41. The new version of git has a bug in it that causes our janitor job in Gitserver to unintentionally corrupt repos: https://lore.kernel.org/git/YqD5dgalb9EPnz85@coredump.intra.peff.net/T/#u
https://lore.kernel.org/git/d1d460f6-e70f-b17f-73a5-e56d604dd9d5@github.com/

> Is there some functionality completely broken that warrants redacting the prior release of Sourcegraph and advising users wait for the patch release?

Yes, repos are in a constant loop of being corrupted and restored in Gitserver which will cause serious disruptions to the usage of Sourcegraph by our customers.

> This will interrupt our regular planned work and release cycle, taking one full working day of our time, and will take up all of our site admin's valuable time by asking them to upgrade or producing noise for them if they don't need to upgrade.
>
> Do you believe the changes are important enough to warrant this?

yes

> Patch releases are a signal we can do something better to improve the quality of Sourcegraph. Have you already scheduled a call (or created a google doc) to perform a [retrospective](https://about.sourcegraph.com/retrospectives) and identify ways we can improve?

Our team is planning a post-mortem on our next team sync in order to go over what fell through the cracks here. 

---

**For the [Release Captain]** - after reviewing this request:

- [x] **Comment on this issue** with a decision regarding the request.
- [x] If you are a first-time [Release Captain], please review the high-level overview of the [patch release process].
- [x] If approved, **add it to a patch release**:
  - If there is [already an upcoming patch release](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+), add the listed commits alongside a link to this issue
  - If there is no upcoming patch release, create a new one:
    - [x] Update [`dev/release/release-config.jsonc`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/release/release-config.jsonc) and open a PR to `main` to update it
      - [x] Change `upcomingRelease` to the current patch release
      - [x] Change `previousRelease` to the previous patch release version
      - [x] Change `releaseDate` to the current date (time is optional) along with `oneWorkingDayAfterRelease` and `threeWorkingDaysBeforeRelease`
      - [x] Change `captainSlackUsername` and `captainGitHubUsername` accordingly
    - [x] `yarn release tracking:issues` 
    - [x] Add the listed commits alongside a link to this issue to the generated [release tracking issue](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+)
- [x] **Comment and close this issue once the relevant commit(s) have been cherry-picked into the release branch**.

[release captain]: https://handbook.sourcegraph.com/engineering/releases#release-captain
[patch release process]: https://handbook.sourcegraph.com/departments/product-engineering/engineering/process/releases#patch-release-process

**Comment by varsanojidan** [comment]
I'm release captain and I approve this message 👍

**Comment by ryanslade** [comment]
@varsanojidan I've update the issue with the symbols related commit, b1ae5b52e54b03e6c133b9b07506536dbe11c1da
