### ISSUE TITLE
Create a REST endpoint returning an archive with exported data

### ISSUE THREAD

**Issue by sashaostrikov** [sourcegraph/sourcegraph#39590]
This endpoint should consume the request with types of data being exported along with some parameters (e.g. limiting the rows of an SQL query output, logs level, etc.)

Here is an example request structure:
```json
{
  "includeSiteConfig": true,
  "includeCodeHostConfigs": true,
  "includeLogs": [
    {
      "serviceName": "repo-updater",
      "tail": 1000,
      "level": "warn"
    },
    {
      "serviceName": "gitserver",
      "tail": 500,
      "level": "debug"
    }
  ],
  "repoPermissionsDbQuery": {
    "count": 10000
  },
  "userPermissionsDbQuery": {
    "count": 100
  }
}
```

Response is a zip archive with requested data

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.
