### ISSUE TITLE
Browse gists on Sourcegraph

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#396]
It should be possible to browse gists on Sourcegraph.

For example it should be possible to view this gist:
https://gist.github.com/nicksnyder/2f58d30fc7ef713fd9affe34b9cb23df

On Sourcegraph here:
https://sourcegraph.com/gist.github.com/nicksnyder/2f58d30fc7ef713fd9affe34b9cb23df

**Comment by slimsag** [comment]
Why the closure here? I think this would be nice to have in the long term

**Comment by nicksnyder** [comment]
duplicate of https://github.com/sourcegraph/sourcegraph/issues/357

I posted but my browser window hung so I didn't realize it was successful
