### ISSUE TITLE
Performance: Investigate lazy syntax highlighting on search results

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#39603]
### Description

**Goal**: Render search results faster

**Reason:**
- Highlighting code takes noticeably longer than fetching file contents. One of the issues with the search results page is that we often see pop-in as we try to fetch new results (See video below). We should be able to solve that by immediately rendering formatting code and enhancing with highlighting.
- It would be faster to run two parallel queries, one to fetch the current code and immediately render, and one to fetch the highlighted code and enhance the render.
- We can reasonably say that code will generally always render fast in this way, so we can remove the loading spinner between files and have a much more editor-like experience.

https://user-images.githubusercontent.com/9516420/181581969-819c729f-17ae-4893-aceb-6a6cd49d4eb5.mp4

Related PR: https://github.com/sourcegraph/sourcegraph/pull/39563

### A/C
- Fetch file contents that has formatting **but not** highlighting. This will allow us to improve performance without introducing any layout shifts to the UX.
- Feature flag this to experiment internally

**Comment by sourcegraph-bot-2** [comment]
Heads up @taylorsperry @jasongornall - the "team/frontend-platform" label was applied to this issue.
