### ISSUE TITLE
Performance: Improve `browserslist` config

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#39606]
### Description

**Goal**: Reduce code required to be downloaded before every page can be shown. 

**Reason:**
- This determines the browsers we support and any additional code (polyfills) that we include.
- I think our app has been broken in Safari 13 for quite a long time, but we still add polyfills here. There may be other areas where we can optimize this.
- This might burn us in the future! E.g. new browser feature but not supported in a browser we inadvertently support - lots of bundle bloat.

Related PR: https://github.com/sourcegraph/sourcegraph/pull/39349

### A/C
- Browserslist is clear of any browsers that we believe we don't need to support
- Browserslist is easier to understand for future changes! (Pretty overly complex right now)

**Comment by sourcegraph-bot-2** [comment]
Heads up @taylorsperry @jasongornall - the "team/frontend-platform" label was applied to this issue.
