### ISSUE TITLE
Performance: Investigate lazy syntax highlightinging on blob pages

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#39602]
### Description

**Goal**: Render code views faster

**Reason:**
- Highlighting code takes noticeably longer than fetching file contents
- It would be faster to run two parallel queries, one to fetch the current code and immediately render, and one to fetch the highlighted code and enhance the render.
- We can reasonably say that code will generally always render fast in this way, so we can remove the loading spinner between files and have a much more editor-like experience.

Related PR: https://github.com/sourcegraph/sourcegraph/pull/39563

### A/C
- Fetch file contents that has formatting **but not** highlighting. This will allow us to improve performance without introducing any layout shifts to the UX.
- Feature flag this to experiment internally

**Comment by sourcegraph-bot-2** [comment]
Heads up @taylorsperry @jasongornall - the "team/frontend-platform" label was applied to this issue.

**Comment by umpox** [comment]
Closed through https://github.com/sourcegraph/sourcegraph/pull/39563 will test for 1 week before enabling everywhere :)
