### ISSUE TITLE
Performance: Close off remaining dependency migrations

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#39608]
### Description

**Goal** Reduce code required to be downloaded before every page can be shown.

**Reason:**
- We have a lot of ongoing migrations that we should close off:
  - Bootstrap
  - Reactstrap
  - mdi-react
- Additional dependencies add bundle size to every page, which slows down our rendering 

### A/C
- All the mentioned migrations above are completed.

**Comment by sourcegraph-bot-2** [comment]
Heads up @taylorsperry @jasongornall - the "team/frontend-platform" label was applied to this issue.

**Comment by valerybugakov** [comment]
The `mdi-react` migration was completed here: https://github.com/sourcegraph/sourcegraph/issues/32379
The `bootstrap` migration was completed here: https://github.com/sourcegraph/sourcegraph/issues/29200
The `reactstrap` migration is tracked here: https://github.com/sourcegraph/sourcegraph/issues/41630

Let's close this issue and track individual package removals in separately.
