### ISSUE TITLE
Performance: Reduce waterfall fetching on file related pages

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#39615]
### Description

**Goal**: Render file-related views faster

**Reason:**
- A lot of UI seems to depend on the `RepositoryRedirect` and `ResolveRev` queries
- These are obviously vital for any other data on the page, but perhaps it’s possible to render key elements (like the revision header, sidebar, and main panel) before populating them with content.
- Can we be confident that a part of the UI will show? Let's start rendering and populate with data as we get it.

Note: **This might be affected by future search/file UX changes**

**Comment by sourcegraph-bot-2** [comment]
Heads up @taylorsperry @jasongornall - the "team/frontend-platform" label was applied to this issue.

**Comment by umpox** [comment]
Closed through https://github.com/sourcegraph/sourcegraph/pull/40982
