### ISSUE TITLE
Implement core archiving logic

### ISSUE THREAD

**Issue by sashaostrikov** [sourcegraph/sourcegraph#39616]
There should be a common place in frontend code where the request from UI is processed and all the exported data is put into an archive and returned.

Workflow looks like this:
1) Request is received and parsed
2) Tmp directory is created
3) Processors gather data and put it into tmp dir
4) After all the processors did their job, tmp dir is archived
5) Archive is returned as a response
6) Tmp dir is deleted

Processors themselves will be implemented in separate issues.

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.
