### ISSUE TITLE
insights: Prototype aggregated search results using compute

### ISSUE THREAD

**Issue by CristinaBirkel** [sourcegraph/sourcegraph#39624]
RFC: https://docs.google.com/document/d/1yLV7MGOEXYT3yPvBxHHm8y2-p737KIrju_QPqlhBYz4/edit

This issue is to explore the option of passing the streaming search results through compute in order to calculate aggregations.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by chwarwick** [comment]
Replaced with new issue
