### ISSUE TITLE
insights: Prototype aggregated search results using existing streamed search filters 

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#39626]
This issue is to explore the option of aggregating search results using the search filter that are currently streamed to the webapp.

Successful completion of this issue will include capturing pros/cons of the approach as well as any limitations that could impact the desired outcomes in RFC: https://docs.google.com/document/d/1yLV7MGOEXYT3yPvBxHHm8y2-p737KIrju_QPqlhBYz4

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by chwarwick** [comment]
This does not appear to be a valid path forward for the aggregation feature.  The aggregates are expected to be over the the same query but with a `count:all` to include all results.  Therefore using the existing returned search results that are cut off at 500 unless specified will not support this.  

The filters that are added to the stream [logic here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/search/streaming/search_filters.go?L23) may be a useful pattern to use for inspiration.

**Comment by leonore** [comment]
@chwarwick could we not still use the search endpoint with filters events, in a new search?

**Comment by chwarwick** [comment]
@leonore yes that is a possibility to either use the filters or add on another "filter like" item  that aggregates the fields we want to use in a second `count:all` query.  We will need to decide if we want to use the compute endpoint or regular search, there are pros/cons either way.   

Pros here being that we know we can do this for every search.
Cons being supporting the capture group feature is not straight forward.
