### ISSUE TITLE
Zoekt performance change from 15th of month

### ISSUE THREAD

**Issue by jjeffwarner** [sourcegraph/sourcegraph#39622]
From the [Slack thread](https://sourcegraph.slack.com/archives/C023ELQLV7F/p1658998828149089?thread_ts=1658933667.882379&cid=C023ELQLV7F)

Either something fishy in our internal/search/zoekt stuff or in our clusters networking. Either way the traces aren't pointing at what exactly is the problem

**Comment by sourcegraph-bot-2** [comment]
Heads up @sourcegraph/search-core - the "team/search-core" label was applied to this issue.

**Comment by keegancsmith** [comment]
Here is the investigation I did so far, but for github so its easier to find than slack:

[literal_file_scope.tsv.gz](https://github.com/sourcegraph/sourcegraph/files/9217124/literal_file_scope.tsv.gz)

```bash
kubectl -n monitoring exec -it search-blitz-0 -- /bin/sh -il
for i in $(ls | grep 2022-07 | grep tsv | sort); do gunzip -c - < "$i" | grep literal_file_scope >> literal_file_scope.tsv; done
grep literal_file_scope search_blitz.tsv >> literal_file_scope.tsv
gzip literal_file_scope.tsv

kubectl -n monitoring cp search-blitz-0:/search-blitz-data/logs/literal_file_scope.tsv.gz literal_file_scope.tsv.gz
```

Def a regression on time to first result. This is based on the actual time that search-blitz observes for the first result to be streamed. The bit of awk magic averages the number over a day.

```shellsession
$ awk '/stream/ { k = substr($1, 0, 10); a[k] += $8; b[k] += 1 }; END { for (k in a) { print k " " (a[k] / b[k]) } } ' < literal_file_scope.tsv  | sort
2022-07-07 0.0980569
2022-07-08 0.542717
2022-07-09 0.100798
2022-07-10 0.0934657
2022-07-11 0.197309
2022-07-12 0.123991
2022-07-13 0.144382
2022-07-14 0.101698
2022-07-15 0.993014
2022-07-16 1.63876
2022-07-17 1.60214
2022-07-18 1.74665
2022-07-19 1.92312
2022-07-20 1.43115
2022-07-21 1.09635
2022-07-22 1.33956
2022-07-23 1.40618
2022-07-24 1.4139
2022-07-25 1.39389
2022-07-26 1.45991
2022-07-27 1.67286
2022-07-28 1.22788
```

Here is a histogram of times. So it seems a lot of the time we have a fast search, but a lot of the time we also see this regression:

```shellsession
$ awk '/stream/ && /2022-07-14/ { print $8 }' < literal_file_scope.tsv | ~/src/github.com/bitly/data_hacks/data_hacks/histogram.py
# NumSamples = 1440; Min = 0.05; Max = 1.74
# Mean = 0.101698; Variance = 0.023716; SD = 0.154000; Median 0.066548
# each ∎ represents a count of 18
    0.0512 -     0.2204 [  1370]: ∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
    0.2204 -     0.3896 [    11]:
    0.3896 -     0.5588 [    10]:
    0.5588 -     0.7280 [    20]: ∎
    0.7280 -     0.8972 [    12]:
    0.8972 -     1.0664 [     8]:
    1.0664 -     1.2356 [     5]:
    1.2356 -     1.4049 [     2]:
    1.4049 -     1.5741 [     1]:
    1.5741 -     1.7433 [     1]:
```

```shellsession
$ awk '/stream/ && /2022-07-24/ { print $8 }' < literal_file_scope.tsv | ~/src/github.com/bitly/data_hacks/data_hacks/histogram.py
# NumSamples = 1440; Min = 0.05; Max = 4.06
# Mean = 1.413902; Variance = 0.979744; SD = 0.989820; Median 2.006315
# each ∎ represents a count of 6
    0.0501 -     0.4513 [   462]: ∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
    0.4513 -     0.8525 [    15]: ∎∎
    0.8525 -     1.2538 [    26]: ∎∎∎∎
    1.2538 -     1.6550 [   103]: ∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
    1.6550 -     2.0562 [   239]: ∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
    2.0562 -     2.4575 [   444]: ∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
    2.4575 -     2.8587 [    83]: ∎∎∎∎∎∎∎∎∎∎∎∎∎
    2.8587 -     3.2600 [    60]: ∎∎∎∎∎∎∎∎∎∎
    3.2600 -     3.6612 [     7]: ∎
    3.6612 -     4.0624 [     1]:
```


-   [Trace on the 14th](https://sourcegraph.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-sourcegraph-traces%22,%22queries%22:%5B%7B%22query%22:%2247fb4b012dffdc4c%22,%22queryType%22:%22traceId%22,%22refId%22:%22A%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D) which reported 0.06s for time to first result.
-   [Trace on the 27th](https://sourcegraph.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-sourcegraph-traces%22,%22queries%22:%5B%7B%22query%22:%221b316b4bb949593c%22,%22queryType%22:%22traceId%22,%22refId%22:%22A%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D) which reported 2.09s for time to first result.

The regression seems to be zoekt. In the traces on the 27th it all seems to be one or two zoekts being slow.

It looks like zoekt is still fast. The traces on the pods are like 6ms. So either networking, or our traces aren't picking up some other form of blocking.

**Comment by jjeffwarner** [comment]
Any updates on this or should we close it?

**Comment by keegancsmith** [comment]
So much has changed not worth picking up again. Rather taking a step back and investigating our general perf on dot-com would be something we could do when there is time to. But right now perf is fine.
