### ISSUE TITLE
insights: update backend architecture diagram

### ISSUE THREAD

**Issue by leonore** [sourcegraph/sourcegraph#39674]
the architecture diagram in our developing docs page is outdated and needs updating:

http://docs.sourcegraph.com/dev/background-information/insights/backend#architecture

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by leonore** [comment]
question is: do we have a better tool than excalidraw to make this diagram, so that it's easier to modify in the future?

**Comment by felixfbecker** [comment]
I thought Excalidraw files can be source controlled?
 
Other alternatives would be Mermaid (used for the Sourcegraph architecture diagram) or SVG directly (editable e.g. with Boxy SVG). Google Docs seems like the worst option because it doesn't have any SVG export support afaik.

**Comment by leonore** [comment]
> I thought Excalidraw files can be source controlled?

if they can, you'll have to show me how! 

and google docs does:
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/29406849/181799225-e121ed60-3b19-4d86-b3f7-ea5b0d8b1023.png">

I guess we can use mermaid too though.

**Comment by felixfbecker** [comment]
Does that SVG export actually maintain text as `<text>` or vectorize it? That might have been the issue I ran into.

There's an Export button in the top left of Excalidraw that downloads a `.excalidraw` file, which I think is just a big JSON file:

<img width="248" alt="image" src="https://user-images.githubusercontent.com/10532611/181800031-1fabbfbc-56bb-492b-bd5b-c8fc38b98bfa.png">

Alternatively we could link to the Excalidraw URL.

**Comment by leonore** [comment]
> There's an Export button in the top left of Excalidraw that downloads a `.excalidraw` file, which I think is just a big JSON file:
> Alternatively we could link to the Excalidraw URL.

yeah if we can link to the Excalidraw URL that'd be great because there's no import option, so right now we'd have to start the diagram for scratch, and I just want to avoid that any time we make changes

**Comment by felixfbecker** [comment]
Pretty sure this button does that:

<img width="350" alt="image" src="https://user-images.githubusercontent.com/10532611/181803014-7c5ffad7-c593-4547-9ba0-9675df121e28.png">

(otherwise the export button wouldn't make much sense)

but agree that the importing/exporting flow is unnecessarily annoying. We should optimize to make it as easy as possible to keep docs up to date.

**Comment by leonore** [comment]
> Pretty sure this button does that:

I can't see this button, are you on Excalidraw+?

**Comment by felixfbecker** [comment]
Yeah, you can ask in #it-tech-ops to get added to our workspace (that's required anyway if we want to put the URL to the Excalidraw and make it editable)

**Comment by leonore** [comment]
closing as completed via https://github.com/sourcegraph/sourcegraph/pull/46645
