### ISSUE TITLE
repos: Stop reading repo.enabled

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#3971]
Follow-up from https://github.com/sourcegraph/sourcegraph/issues/3291

Also find other uses of enabled that can be removed. Once we stop using the field, we can drop the column in two releases.

**Comment by tsenart** [comment]
LEZZ GOOOO

**Comment by keegancsmith** [comment]
Filed https://github.com/sourcegraph/sourcegraph/issues/7815 to actually drop the column in 3.15. Because this is on the repos table, we don't want to cause downtime during upgrade with older clients trying to read the enabled column.
