### ISSUE TITLE
gitserver: Use removeRepoDirectory helper function in disk cleanup

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#3972]
Using a naive `os.RemoveAll` can lead to corrupted repositories if the operation is interrupted. There is the helper function `removeRepoDirectory` which handles atomically renaming the directory outside of the repos dir, and then removing it.

https://github.com/sourcegraph/sourcegraph/blob/cd9cc2f6beef0c93d398e88ac32af24668b265dc/cmd/gitserver/server/cleanup.go#L310-L312

**Comment by ijt** [comment]
I agree about there being some risk in using `os.RemoveAll`. I used it because `removeRepoDirectory` seemed overly complicated with its removal of empty dirs and also was not tested. Something focused and tested would be fine though, so I'll add that now.

**Comment by keegancsmith** [comment]
It should be tested? Check test coverage.
