### ISSUE TITLE
Integrate the bundlesize upload script into the CI pipeline to enable continuous bundlesize monitoring.

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#39737]
## Context

Integrate the script implemented in https://github.com/sourcegraph/sourcegraph/issues/39735 into our CI pipeline to enable continuous bundlesize monitoring.

**Comment by sourcegraph-bot-2** [comment]
Heads up @taylorsperry @jasongornall - the "team/frontend-platform" label was applied to this issue.
