### ISSUE TITLE
Implement infrastructure required for uploading events from node.js env to Honeycomb.

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#39736]
## Context

Implement infrastructure required for uploading events from node.js env to Honeycomb. It can be a separate client workspace to enable the reuse of infrastructure for other scripts later.

## Vision
Use the new package for new scripts related to client infrastructure instrumentation and analysis. Colocate logic here to benefit from having shared:
- setup configuration (libhoney.js),
- observability event schemas,
- environment variable validators,
- unit tests.

**Comment by sourcegraph-bot-2** [comment]
Heads up @taylorsperry @jasongornall - the "team/frontend-platform" label was applied to this issue.
