### ISSUE TITLE
Performance: Eliminate flicker when navigating from file blob -> search results

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#39740]
### Description

Our application tends to flicker when navigating back in the browser to search results. The browser isn't making any new network requests, it just seems that we re-render some critical elements that the browser can't reuse.

Example from @quinnkeast: https://share.cleanshot.com/C0UEod

Note: This may be partially related to a bug in the simple UI where it flickers unnecessarily: [Slack thread](https://sourcegraph.slack.com/archives/C03CSAER9LK/p1658935242055789)

**Comment by sourcegraph-bot-2** [comment]
Heads up @taylorsperry @jasongornall - the "team/frontend-platform" label was applied to this issue.
