### ISSUE TITLE
Consistent search query predicate names

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#39767]
Rename:

```
repo:contains(file:foo content:bar) => repo:contains.file(path:foo content:bar)
```

```
repo:contains.file(foo) => repo:contains.path(foo)
```

After rename, add aliases for:

- `repo:contains.file(path:foo content:bar)` => `repo:has.file(path:foo content:bar)`

- `repo:contains.content(foo)` => `repo:has.content(foo)`

- `repo:contains.path(foo)` => `repo:has.path(foo)`

- `repo:contains.commit.after(foo)` => `repo:has.commit.after(foo)`

Will need changes to frontend for hovers/descriptions, and highlighting for aliases

Will need doc updates and changelog

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by tbliu98** [comment]
This has been completed by the series of PRs linked on this issue.
