### ISSUE TITLE
Support predicates and args in autocomplete suggestions

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#39760]
- We don't show predicate suggestions well
- We don't support arguments in suggestions
- We don't support syntax highlighting in the same way, at least for `repo:has.description()`

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by benvenker** [comment]
@tbliu98 are you taking a look at this as part of your current predicate work, or is this more in the scope of application workstream?

**Comment by tbliu98** [comment]
@benvenker I have not looked into this, at a glance it seems like more of an application workstream thing

**Comment by benvenker** [comment]
ok cool, thanks!
