### ISSUE TITLE
repository API returns error when the project does not have any authorized users

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#39763]
- **Sourcegraph version:** 3.42.0
- **Customer**: https://github.com/sourcegraph/accounts/issues/3

#### Steps to reproduce:

1. query for  `repository`/`authorizedUsers` on a repo that has no authorized users

Example:
```
query repo {
   repository(name: "bitbucket.com/PROJECT/repo") {
    authorizedUsers(first: 100) {
      nodes {
        username
        displayName
      }
      totalCount
    }
  }
}
```

#### Expected behavior:

You get an empty list of users and a totalCount = 0.

#### Actual behavior:

```

returns this error:
 
{
  "errors": [
    {
      "message": "panic occurred: runtime error: index out of range [-1]",
      "path": [
        "repository",
        "authorizedUsers",
        "nodes"
      ]
    }
  ],
  "data": {
    "repository": null
  }
}
```

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn - the "team/repo-management" label was applied to this issue.

**Comment by mrnugget** [comment]
Fixed in https://github.com/sourcegraph/sourcegraph/pull/55191
