### ISSUE TITLE
Add Code navigation admin analytics

### ISSUE THREAD

**Issue by macraig** [sourcegraph/sourcegraph#39769]
### High-level goal

Giving admins a better workflow and dashboards to help them get precise code graph data for all repositories (whether they do it themselves or encourage others in their organization to do it) and understand where there are gaps.
Answer questions like: What % of navigation events are precise? How can I make that number higher?

### Metrics we can surface

- the number of code nav actions (defs, refs, hovers), if available
- the ratio of precise/search-based actions
- the number of repos with and without precise navigation

[Current looker dashboard for reference](https://sourcegraph.looker.com/dashboards/158?Unique+Server+ID=Databricks&Company+Type= )

(Updated after consulting with @efritz )

What we **can** get:
- Total number of repositories
- Total number of repositories without precise code intel (global)
- Total number of repositories with precise code intel (global)
- Total number of repositories with precise code intel for language X

What we **can’t** get:
- Total number of repositories for language X
- Total number of repositories without precise intel for language X
- % of precise per repo 

### Ideas
- Find the repo that has more usage and a high ratio of search-based/precise, or no precise. Prompt for admin: "If you enable indexing for this repo, you can expect X more precise events which translate to Y dev time saved"
- For languages we support: "If you set up Ruby you would get X more precise events which translate to Y dev time saved"

### Tracker

- [x]  Design finalized in [Figma](https://www.figma.com/file/mmWwgzzqTmpLsxwmiiZwfE/Admin-analytics?node-id=1945%3A10104)
- [x] #40345
- [x] #39780

**Comment by rrhyne** [comment]
> the number of code nav actions (defs, refs, hovers), if available
> the ratio of precise/search-based actions


I believe these two, minus hovers are already in the analytics and the calculator. Might be good to massage them. 

Agree that uploads could be interesting and also that any content that helps more end users experience intel is very important.

**Comment by macraig** [comment]
Thanks for the input @rrhyne! I added a few ideas to go over with @jjinnii, feel free to comment on them as well.

**Comment by jjinnii** [comment]
@macraig Is this a tracking issue for the implementation of the new code intel admin analytics designs? Or can I close this out. 😄

**Comment by macraig** [comment]
@jjinnii it's the tracking issue :)

**Comment by jjinnii** [comment]
@macraig Should we close out this issue now since Chris has implemented admin analytics designs?

**Comment by macraig** [comment]
@jjinnii I'll close once we've merged the remaining PRs

**Comment by jjinnii** [comment]
@macraig Closing this issue as we've shipped code nav admin analytics with 4.0. Any further improvements should be captured in new issues!
