### ISSUE TITLE
Smart Search UX

### ISSUE THREAD

**Issue by almeidapaulooliveira** [sourcegraph/sourcegraph#39771]
['Lucky search' eliminates](https://github.com/sourcegraph/sourcegraph/issues/38363) the 'no results' problem users often have when they first encounter our literal search default. 

This design initiative addresses the need to create an easy-to-use UI to interact with 'lucky search' suggestions. It is the beginning of a more significant effort to improve our searching experience and lays a foundation for iteratively improving the quality of our results.

## Design process (Size: M)

  - Estimate: Three weeks
  - Weighting factors:
    - MEDIUM risk
    - MEDIUM clarity

### 'Lucky' and 'standard' search modes

- [x] [Low-fidelity (Figma board) ](https://www.figma.com/file/GikUoxdCrRTmbQpiu72AUi/UX-for-%E2%80%99feeling-lucky%E2%80%99-search-mode.?node-id=1747%3A8824)exploration and discussion.

**Main takeaway from Discover:**
In the discovery process, deciding [how effectively to switch between search modes](https://github.com/sourcegraph/sourcegraph/issues/40670), many [discussions](https://www.figma.com/file/GikUoxdCrRTmbQpiu72AUi/UX-for-%E2%80%99feeling-lucky%E2%80%99-search-mode.?node-id=1747%3A8824) led to a different understanding: 'Lucky search' is not a search mode per se, nor is the standard search mode. Instead, all searches are implicitly standard, and 'lucky search' is an **extended query interpretation** feature applied on top of it, with the possibility of being enabled and disabled.

<img src="https://user-images.githubusercontent.com/64257673/185955807-6532ad5d-e38b-44d0-9208-969a626b58a5.png" width="500"/>

## Define

**`Goal:`** Decision on UX for the **extended query interpretation** interaction model.

**`Problem statement:`** From recent research, we've learned how users struggle to discover and use search-related features. 'Lucky search' aims to improve the searching experience. Still, if not well explained, it could lead to users not understanding how to use it (enable, disable, etc.) and more frustration. Therefore, this design will create a simple and easy-to-use UI with the addition of a straightforward education effort.

**`Design challenges:`** Having discovered a new understanding of 'lucky search,' we get back to the following challenges:

- How might we explain the **extended query interpretation** functioning to users?
- How might we present the **extended query interpretation** suggestions to users?
- How might we educate users on discovering how to toggle it between enabled and disabled?

### Sprint 1
- [x] Hi-fi [visual design (Figma file)](https://www.figma.com/file/GikUoxdCrRTmbQpiu72AUi/UX-for-%E2%80%99feeling-lucky%E2%80%99-search-mode.?node-id=2167%3A6256) and discussions.
- [x] [Interactive prototype.](https://www.figma.com/proto/GikUoxdCrRTmbQpiu72AUi/UX-for-%E2%80%99feeling-lucky%E2%80%99-search-mode.?node-id=2153%3A7273&viewport=-58%2C1966%2C0.33&scaling=scale-down-width&starting-point-node-id=2153%3A7273&show-proto-sidebar=1)
- [x] [Loom.](https://www.loom.com/share/e4b6f75351934b7a9c4fa7e55f3d9795)
- [x] Designer review.

**Main takeaways of Sprint 1:**
- Adopted **Smart Search** as the customer-face name of 'lucky search.'
- Defined the copy for the majority of the components.
- Approved the [dropdown component ](https://www.figma.com/file/GikUoxdCrRTmbQpiu72AUi/UX-for-%E2%80%99feeling-lucky%E2%80%99-search-mode.?node-id=2083%3A5184)for toggling Smart Search.
- [Find the necessity](https://www.figma.com/file/GikUoxdCrRTmbQpiu72AUi?node-id=2153:7273#252439157) of user testing the informational component to seek more clarity on how to move forward.
- [Find the need](https://www.figma.com/file/GikUoxdCrRTmbQpiu72AUi/UX-for-%E2%80%99feeling-lucky%E2%80%99-search-mode.?node-id=2695%3A6912) to explore further the 'no results' page.
- [Find the need](https://www.figma.com/file/GikUoxdCrRTmbQpiu72AUi?node-id=2695:6911#254739559) to have an icon for Smart Search.
- ----

### Sprint 2
- [x] Hi-fi [visual design (Figma file)](https://www.figma.com/file/GikUoxdCrRTmbQpiu72AUi/UX-for-%E2%80%99feeling-lucky%E2%80%99-search-mode.?node-id=2750%3A8148) and discussions.
- [x] Interactive prototypes:
   -  [Version with Carousel and text-based info panel.](https://www.figma.com/proto/GikUoxdCrRTmbQpiu72AUi/UX-for-%E2%80%99feeling-lucky%E2%80%99-search-mode.?node-id=2750%3A6681&viewport=-307%2C361%2C0.2&scaling=min-zoom&starting-point-node-id=2944%3A9035&show-proto-sidebar=1)
   -  [Version with CTA for video.](https://www.figma.com/proto/GikUoxdCrRTmbQpiu72AUi/UX-for-%E2%80%99feeling-lucky%E2%80%99-search-mode.?node-id=2944%3A8093&viewport=-307%2C361%2C0.2&scaling=min-zoom&starting-point-node-id=2944%3A8093&show-proto-sidebar=1&hide-ui=1)
   -  [Version with video on autoplay.](https://www.figma.com/proto/GikUoxdCrRTmbQpiu72AUi/UX-for-%E2%80%99feeling-lucky%E2%80%99-search-mode.?node-id=2757%3A10293&viewport=-307%2C361%2C0.2&scaling=min-zoom&starting-point-node-id=2757%3A10293&show-proto-sidebar=1&hide-ui=1)
- [ ] User testing:
   - [User testing issue.](https://github.com/sourcegraph/sourcegraph/issues/41337)
   - [Research plan.](https://docs.google.com/document/d/1-n8Oe9Ttu45kHgT6wzdWxgGU899z7y7d6e92OUQWnZg/edit#heading=h.q01m69gfe2oh)
- [ ] Loom.

## Testing
- [ ] [Sprint 2 user testing.](https://github.com/sourcegraph/sourcegraph/issues/41337)

## Deliver
- [ ] Announce in #progress.
- [ ]  Team review.
- [ ]  Design team review.

## Measure
- [ ] [Define metrics.](https://www.figma.com/file/GikUoxdCrRTmbQpiu72AUi/UX-for-%E2%80%99feeling-lucky%E2%80%99-search-mode.?node-id=3304%3A9738)

## Related work items
- #40670
- #41337
- #39586
- #39576
- #37062

**Comment by sourcegraph-bot-2** [comment]
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by almeidapaulooliveira** [comment]
@benvenker , I deprecated (closed) the[ old issue](https://github.com/sourcegraph/sourcegraph/issues/37729) since we're working on a new proposal.
