### ISSUE TITLE
Decide on metrics showing auto-indexing performance / correctness

### ISSUE THREAD

**Issue by macraig** [sourcegraph/sourcegraph#39772]
Decide on metrics showing auto-indexing performance/correctness, implement alerting & write Cloud playbook.

See [RFC 723](https://docs.google.com/document/d/1Ss7ZffP82rV6nl4i5gBmICfuMK1xvSFI4Y5sLPXyDZc/edit#) for details

**Comment by Strum355** [comment]
Preliminary metrics to add:
- Total (uncompressed) size of uploads being processed by precise-code-intel-workers to guide provisioning of pciw based on expected upload sizes https://github.com/sourcegraph/sourcegraph/pull/39690
- Alerts for when auto indexing queue is not progressing and/or active handlers = 0 and queue > 0
- Alerts for when uploads are reset e.g. in the case of pciw OOM

TODO: more
