### ISSUE TITLE
User administration + analytics designs

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#39782]
Users require the ability to view event data alongside the users they are managing. Transform the current administration page to use a table, present event data and be sortable and filterable to allow users to remove users by various criteria.

- [Minimum required functionality](https://www.figma.com/file/mmWwgzzqTmpLsxwmiiZwfE/Admin-analytics?node-id=1565%3A10969)
- [Desired functionality](https://www.figma.com/file/mmWwgzzqTmpLsxwmiiZwfE/Admin-analytics?node-id=1601%3A8291).

Make it be enabled/disabled via feature flag.

Subtasks:
- [x] https://github.com/sourcegraph/sourcegraph/issues/39820
   - https://github.com/sourcegraph/sourcegraph/pull/39926
   - https://github.com/sourcegraph/sourcegraph/pull/40077
   - https://github.com/sourcegraph/sourcegraph/pull/40123
   - https://github.com/sourcegraph/sourcegraph/pull/40301
- [x] https://github.com/sourcegraph/sourcegraph/issues/39821
- https://github.com/sourcegraph/sourcegraph/pull/40339
- https://github.com/sourcegraph/sourcegraph/pull/40437

**Comment by erzhtor** [comment]
I think this can be considered done. Feel free to re-open if not.
