### ISSUE TITLE
insights: save as a new view from the single insight share page takes me to a page that doesn't exist

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#39788]
https://www.loom.com/share/dcaac9a8774440fba3b133bfc6678523 

Go to single insight view page, add a filter, save it as a new view, name it, hit save, you get redirected to `https://k8s.sgdev.org/insights/dashboardall` which doesn't exist.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
