### ISSUE TITLE
SSBC error message is confusing when there's a version mismatch between sg and executors

### ISSUE THREAD

**Issue by michaellzc** [sourcegraph/sourcegraph#39781]
## Context

https://sourcegraph.slack.com/archives/C03JR7S7KRP/p1659383776707789

During Sourcegraph upgrade, there's a short window where executors and sourcegraph versions are different, and running SSBC will result in confusing errors to users

It's not super important, but worth logging it

## Desired behaviour

- provide a more meaningful error message
- executors and sourcegraph are at least n+1 compatible

**Comment by chrispine** [comment]
Is the 1.5d estimate for doing both of the items suggested?

**Comment by adeola-ak** [comment]
p1?
