### ISSUE TITLE
insights: z-index of line and dots don't always match so you get a mixed array of line segments and dot colors 

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#39789]
<img width="596" alt="image (87)" src="https://user-images.githubusercontent.com/11967660/182253199-04945ec8-ca85-435e-ae33-4995215c0a7c.png">

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
