### ISSUE TITLE
Pseudographic symbols break on Windows Docker Toolbox

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#398]
- **Sourcegraph version:** all versions
- **Platform information:** Windows, Docker Toolbox

#### Steps to reproduce:

1. Run `docker run ... sourcegraph/server` so that the logo graphic would be printed

#### Expected behavior:

It should start up.

#### Actual behavior:

```
New state of 'nil' is invalid.
```

Reported by @40rn05lyv in https://github.com/sourcegraph/sourcegraph/issues/374#issuecomment-429579811

> I tried to perform steps from my comment here: https://github.com/sourcegraph/sourcegraph/issues/381#issuecomment-429577461 , however now I have another exception:
![image](https://user-images.githubusercontent.com/1200215/46910519-a2c4b800-cf4e-11e8-836f-72abf67021ed.png)
I suppose it can be caused by pseudographic symbols that is used to show sourcegraph logo (see https://github.com/docker/toolbox/issues/695#issuecomment-356218801 ) - probably Docker Toolbox doesn't support them.

**Comment by keegancsmith** [comment]
This looks like a bug in the terminal render, this isn't go reporting the error. In fact when we print the logo we are just writing a string to the terminal (see the string here https://sourcegraph.com/github.com/sourcegraph/sourcegraph@6a69e6bebaf9c2163e3e59ddf72081c21b19e102/-/blob/cmd/frontend/internal/cli/logo.go#L4 )

I suppose by supporting the TODO just above that it will solve this issue.

**Comment by keegancsmith** [comment]
This actually looks like a docker bug! https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/docker/+%22new+state+of%22

**Comment by keegancsmith** [comment]
The upstream issue https://github.com/Azure/go-ansiterm/issues/26

**Comment by felixfbecker** [comment]
I don't have this problem:

![image](https://user-images.githubusercontent.com/10532611/46969159-78413f00-d0b5-11e8-838b-06ede65fb64d.png)

This is using plain Docker (not Docker toolbox):

![image](https://user-images.githubusercontent.com/10532611/46969193-9018c300-d0b5-11e8-8821-e7570b462c96.png)

Do we use emojis anywhere?

**Comment by keegancsmith** [comment]
This is a bug in docker toolbox, not docker. I think it has a terminal emulator somewhere, and its crashing due to the logo we output. I don't know how to detect the bad terminal (maybe someone else has an idea?).

My suggested fix is documentation for windows docker toolbox users to `LOGO=false` as an environment variable. Sound good @sqs?

**Comment by felixfbecker** [comment]
Also note that Docker toolbox is deprecated:

**Comment by sqs** [comment]
@keegancsmith 	sounds good. I am migrating the docs to this repo from the about repo, so I'll assign this to myself and add it to the docs.

**Comment by 40rn05lyv** [comment]
The workaround by @sqs (`-e LOGO=false`) helps to hide the error from logs. However, looks like it works even _without_ this workaround. I forgot that in Docker Toolbox the Linux has it's own IP address (`localhost` won't work), so I need to get IP using `docker-machine ip default` and then open `http://found_ip:7080/` in a browser.

**Comment by keegancsmith** [comment]
@40rn05lyv ok so the crash is only in the terminal emulator of docker toolbox? The docker container is still running.

**Comment by 40rn05lyv** [comment]
@keegancsmith It's more like a warning message in the terminal (not crash). The container with sourcegraph is ok.
