### ISSUE TITLE
Performance: Preload repository and revision metadata where possible

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#39825]
### Description

**Goal**: Render repo related pages + code views faster

**Reason:**
- We fetch `RepositoryRedirect` and `ResolveRevision` queries whenever we load a **new** repository from search results.
  - Often this means clicking a second search result from the list is faster (as we already have the metadata)
- Typically there won't be as many different repositories in results as there will be files. It might be a good idea after a search to prefetch the first 10(?) repositories and their metadata so we already have this information when a result is clicked.

Note:
- Partially related to https://github.com/sourcegraph/sourcegraph/issues/39614

**Comment by sourcegraph-bot-2** [comment]
Heads up @taylorsperry @jasongornall - the "team/frontend-platform" label was applied to this issue.

**Comment by umpox** [comment]
Note: 

This PR may close this issue: https://github.com/sourcegraph/sourcegraph/pull/40244

We might be able the use the URL as a source of truth for key queries like `Blob`, and we will be able to render the UI immediately which will help for perceived performance.

Consider closing this issue if https://github.com/sourcegraph/sourcegraph/pull/40244 is closed
