### ISSUE TITLE
insights: query runner metrics are not being emitted

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#39838]
It appears the query runner metrics were accidentally removed in a a refactor, and are no longer emitted.

https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/a36bacb3bd1c84a99b3fc9962810d1c9a9645036?visible=4

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
