### ISSUE TITLE
insights: converting just in time insights backfills from series creation date instead of current date

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#39866]
When converting from a Just in time to Backfilled scoped insight the conversion process is incorrectly using the series created date as the starting point for backfilling points.  It should use the current date.  This causes a gap between points that is equal to the difference between the created date to the conversion date + 1 time interval.  

For example if an insight was created at June 1st 2022 with a 1 week interval and converted to backfilled on July 1st 2022 the following would be the state.

- 12 backfilled points with the most recent point at June 1st
- The next snapshot will be on July 2nd
- The next recorded point will be July 7th

In app workaround:
Edit the insight - no changes are necessary just open the edit screen and press save

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
