### ISSUE TITLE
Redesign how request is processed and processors are invoked

### ISSUE THREAD

**Issue by sashaostrikov** [sourcegraph/sourcegraph#39869]
See how can necessary processors be invoked and how dependencies (logger, db connection, etc.) should be passed to them: e.g. during initialization, or per-request

_Possible implementation of this: make all the processors run as a separate goroutines._

_Another idea: make processors not generic and accept `any` and then cast any request to desired type. This will let us just have one map of processors in `DataExporter`_

**Comment by sourcegraph-bot-2** [comment]
Heads up @jplahn @ryphil - the "team/repo-management" label was applied to this issue.
