### ISSUE TITLE
Web [Charts]: Update readme for charts package

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#39878]
## Background

It's been a while since the last time when we updated our chart readme documentation, since then some chart API has been deprecated, some parts has been outdated. 

In this issue we should update this doc, provide good examples and guidenes for any consumers that want to build their custom charts with our low level abstractions or just use our pre build in house components (that we primary use in Code Insights UI)

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.
