### ISSUE TITLE
insights: validate query before creating insight

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#39875]
To reduce the number of bad queries that make it into the background processor, we should at least try and parse the query before creating / editing an insight.

**Comment by sourcegraph-bot-2** [comment]
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by CristinaBirkel** [comment]
@coury-clark Did you have in mind which function we should use to parse the query here? I'm trying to wrap my head around the various functions, and I wonder if it would make the most sense to just re-use the logic we use when enqueuing a job, to flush out any errors that way?

**Comment by coury-clark** [comment]
@CristinaBirkel in general for search queries we can use the query parser directly, for example: https://sourcegraph.sourcegraph.com/search?q=context:global+query.Pipeline+file:builder&patternType=standard

Essentially the bare minimum validation would be that can pass.

Note, for compute queries it has to run through [`compute.Parse`](https://sourcegraph.sourcegraph.com/search?q=context:global+compute.Parse+file:builder&patternType=standard)
