### ISSUE TITLE
Update `@sentry/browser` dependency to `v7.8.1`

### ISSUE THREAD

**Issue by plibither8** [sourcegraph/sourcegraph#39899]
We’ve been using a rather old release (almost a year) of the `@sentry/browser` package (`v6.13.2`). It’ll be beneficial for us to update it to the [latest one](https://github.com/getsentry/sentry-javascript/releases) (`v7.8.1`).

Probably good to update to have more reliable tracking, and will also remove the warning alert that’s attached to the Sentry issues we see.

**Comment by sourcegraph-bot-2** [comment]
Heads up @taylorsperry @jasongornall - the "team/frontend-platform" label was applied to this issue.
