### ISSUE TITLE
Update to comlink v4

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#3989]
Being stuck on our v3 fork prevents us from profiting of upstream performance improvements.

**Comment by lguychard** [comment]
Typings in v4 as not as good as @felixfbecker's.

We should start by upgrading our fork to V4.

**Comment by felixfbecker** [comment]
PR to upstream to fix types: https://github.com/GoogleChromeLabs/comlink/pull/451
