### ISSUE TITLE
insights: unique lables in grouping insight are not being summed

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#39913]
Duplicate labels should be summed since as long as the series are not being split out by groups.

https://sourcegraph.slack.com/files/U021CRVEQ5V/F03QNSELURW/cleanshot_2022-07-18_at_13.21.59_2x.png

/cc @joelkw @felixfbecker @vovakulikov @unclejustin

**Comment by vovakulikov** [comment]
Closes by https://github.com/sourcegraph/sourcegraph/pull/39021
