### ISSUE TITLE
insights: track 4.0 aggregation feature usage via pings

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#39922]
RFC TBA – 

We will want to track: 
1. Number of data hovers 
2. Number of bar clicks/to filter
3. ~~Number of clicks through to "create insights"~~
4. ~~Number of insights created (** new, session-like tracking) from that page~~
5. Number of capture-group type searches where this runs proactively 

/cc @joelkw @felixfbecker @vovakulikov @unclejustin

**Comment by vovakulikov** [comment]
We also should track hover over save insight button and send different pings based on this button enable/disable state
See origin message from slack https://sourcegraph.slack.com/archives/C01RVEVPWLC/p1660585825345719

**Comment by AlicjaSuska** [comment]
@Joelkw @vovakulikov I've also added the metrics page to aggregation project in [Figma](https://www.figma.com/file/cKSeCtmBh9aiPsAVoKsLgM/Aggregation-insights%3A-display-%22grouped%22-insights-for-existing-searches-%2339126-%5Bready-for-dev%5D?node-id=2377%3A31025) - for the event logs from Cloud ([context](https://sourcegraph.slack.com/archives/C03JR7S7KRP/p1660775794446229)).

**Comment by chwarwick** [comment]
Removed pings for items that are no longer in 4.0 scope.

**Comment by Joelkw** [comment]
@vovakulikov @CristinaBirkel I have added an RFC for this now: https://docs.google.com/document/d/1v6-T0UTGfQ1H7SBybuNXlPFAm4Ilu7r1aU23p_5MhrE/edit# . The event names match the figma. There are two in my doc that are not in the figma now – is it possible we can add those as well? (they are number 4 and number 6)
