### ISSUE TITLE
VSCE: Add a batch change example to add our extension to workspace recommendations

### ISSUE THREAD

**Issue by ryankscott** [sourcegraph/sourcegraph#39933]
We should create a batch-change [example](https://github.com/sourcegraph/batch-change-examples) that adds our extension to `extensions.json` file.

We should also add this to the trial / deployment checklist for CEs and reference this in docs. 

/cc @muratsu @jjinnii @ryankscott

**Comment by philipp-spiess** [comment]
Fixed in https://github.com/sourcegraph/batch-change-examples/pull/44
