### ISSUE TITLE
saved_searches vs saved_queries table name

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#3993]
On latest master, I got an error:

```
22:51:33               frontend | ERROR migrate.saved-queries: unable to migrate search.savedQueries because cannot tell if saved searches table is empty. Please report this issue., error: pq: relation "saved_searches" does not exist
```

But I see the table name in PostgreSQL is `saved_queries`.

This error is not blocking me in any way, I just wanted to report the discrepancy.

**Comment by attfarhan** [comment]
You should have both a `saved_searches` and `saved_queries` table in your DB after the saved search migration is run. Can you check what migration number is in your `schema_migrations` table: `select * from schema_migrations`?

**Comment by sqs** [comment]
Ah, OK. Nevermind then - I was manually updating the schema_migrations version number because I have some local DB changes. So that is why this happened.
