### ISSUE TITLE
special-instructions-for-rhel-fedora-centos-and-others command is incorrect

### ISSUE THREAD

**Issue by ben-alkov** [sourcegraph/sourcegraph#39963]
#### Describe the issue
The command in "[special-instructions-for-rhel-fedora-centos-and-others](https://docs.sourcegraph.com/admin/deploy/docker-single-container#special-instructions-for-rhel-fedora-centos-and-others)" is incorrect

#### Where is the issue located?
https://docs.sourcegraph.com/admin/deploy/docker-single-container#special-instructions-for-rhel-fedora-centos-and-others

#### Suggested resolution

`chown` has no `-t` option - you want `chcon` to fix the selinux context:

```diff
- mkdir -p ~/.sourcegraph/config ~/.sourcegraph/data && chown -R -t svirt_sandbox_file_t ~/.sourcegraph/config ~/.sourcegraph/data
+ mkdir -p ~/.sourcegraph/config ~/.sourcegraph/data && chcon -R -t svirt_sandbox_file_t ~/.sourcegraph/config ~/.sourcegraph/data
```

**Comment by jdorfman** [comment]
Thanks for reporting @ben-alkov. Digging in.

**Comment by ben-alkov** [comment]
PR looks good. Thanks for quick turnaround!

**Comment by jdorfman** [comment]
Hey @ben-alkov fixed!
![Image 2022-08-04 at 1 58 08 PM](https://user-images.githubusercontent.com/398230/182951455-0efb720f-9e7a-4129-9a20-a5dce58609cb.jpg)

Thanks so much for bringing this to our attention :)

**Comment by jdorfman** [comment]
@ben-alkov would love to send you some swag, feel free to drop me a line and I will send you a link. =)
