### ISSUE TITLE
insights: surface timeout limit hit to end users in the UI 

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#39969]
It's possible to hit a timeout but not see that in the UI for insights and mistakenly assume your insight is correct. 

This issue is limited on large results sets/searches that timeout. 

We should surface this in the UI if a snapshot or insight has hit this limit. Ideally we can do per-point but otherwise per-insight is fine. 

cc @AlicjaSuska we mostly need a design for this; I believe we track this in `dirtyqueries` in the db somehow already. (if this is small, we will prioritize this for sometime in later Q3). 

/cc @joelkw @felixfbecker @vovakulikov @unclejustin

---

## Design process

  - Estimate: Less than a day
  - Weighting factors:
    - LOW risk
    - HIGH clarity

  ### Discover
  - [x] Product and/or engineering provide direction and/or feedback (see description above)

  ### Define
  - [x] Github issue #39969 

  ### Design
  - [x] High fidelity design using design system - [Figma](https://www.figma.com/file/aMO6sPoUHDUUcqa25wFnWl/Surface-timeout-limit-hit-to-end-users-in-the-UI-%2339969-Review?node-id=260%3A11)
  - [ ] Non-visual design guidance captured in the issue

  ### Testing
  - [ ] Hallway testing - Link (skip)

  ### Deliver
  - [x] Team review
  - [x] QA'd by designer before release

  ### Measure (in the follow-up issue)
  - [ ] Metrics defined in the Figma file ([i](https://handbook.sourcegraph.com/departments/product-engineering/product/design/metrics/defining-metrics/)) - Link
  - [ ] Followup task will analyze metrics to ensure successful completion - Link

**Comment by leonore** [comment]
> I believe we track this in dirtyqueries in the db somehow already. (if this is small, we will prioritize this for sometime in later Q3).

FYI we no longer do track this in db; this was something we did for frontend insights (see https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/5a34b7670bae695d918143b5355cf7fd5627b572?visible=12 for removal). on the other hand we do receive those timeout events from search, which we can surface one way or another

**Comment by Joelkw** [comment]
Ah, thanks for that info @leonore ! Appreciate the detail.

**Comment by Joelkw** [comment]
@AlicjaSuska you mentioned we have a design for this in our planning sync. If that's the case, can you please link it here? I would like to prioritize this given our extra frontend capacity in iteration 26, if so.

**Comment by Joelkw** [comment]
Notes from sync on eng side: 
- Surfacing it is important
- Adding an admin way to retry is also important 
- May strat customers may time out 
- How do we break out non-strat improvements vs strat improvements? 
-
