### ISSUE TITLE
repo-updater: Take `ExternalRepo` into account in `RepoLookup`

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#3996]
In https://github.com/sourcegraph/sourcegraph/pull/3967#discussion_r283293070 @tsenart noticed that we do not take the `ExternalRepo` field of `protocol.RepoLookupArgs` into account:

https://github.com/sourcegraph/sourcegraph/blob/58f657de688b0905ca026fbb9c2d1a60086cd230/cmd/repo-updater/repoupdater/server.go#L342-L344

The `protocol.RepoLookupArgs` matches the `external_*` columns we have in the `repo` table:

https://github.com/sourcegraph/sourcegraph/blob/58f657de688b0905ca026fbb9c2d1a60086cd230/pkg/api/api.go#L52-L73

There are multiple places in the codebase that make use of this field:
- [repos_vcs.go#L57:68]( https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/backend/repos_vcs.go#L57:68)
- [repository.go#L122:66]( https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/externallink/repository.go#L122:66)
- [repository_mirror.go#L67:80]( https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/repository_mirror.go#L67:80)

We can either:
1. Only use `ExternalRepo.ServiceType` in the `Kinds` field of `repos.StoreListReposArgs`
2. Extend the store with a `GetRepo` method that takes in a `GetRepoArgs` that has `ExternalId`, `ExternalServiceType`, `ExternalServiceID` fields

**Comment by tsenart** [comment]
> There are multiple places in the codebase that make use of this field:

This may be an important bug to work on, specially for code navigation with the browser extension on repos in the code host that got renamed but haven't got synced yet on sourcegraph.

> Extend the store with a GetRepo method that takes in a GetRepoArgs that has ExternalId, ExternalServiceType, ExternalServiceID fields

Would make more sense to extend `ListRepos` to support listing by external id, like it does for names.

**Comment by mrnugget** [comment]
> Would make more sense to extend `ListRepos` to support listing by external id, like it does for names.

Yeah, that _does_ make more sense, because ListRepos is more versatile (you can always just list 1 repo)

**Comment by mrnugget** [comment]
After discussing this with @keegancsmith and @tsenart we realized that since `repo.name` is unique, it's enough if we only search for `Name`. And all the call-sites that pass in `ExternalRepo` also pass in name.

That means, we can get rid of `ExternalRepo` in `protocol.RepoLookupArgs`.
