### ISSUE TITLE
How to get 30 day enterprise trial key AFTER creating an admin account

### ISSUE THREAD

**Issue by moldach** [sourcegraph/sourcegraph#39977]
When I created a admin account the first time I logged into Sourcegraph there was an option to click a box to start the trial.

I never clicked that box initially because I knew it would take me to get it setup before I could try out functionalities like batch change. Now I would like to get a trial - where do I click now to get this?

**Comment by malomarrec** [comment]
Hey @malomarrec, it looks like this issue was created by someone outside Sourcegraph. Assigning you to triage it! Please answer and route to the right team by adding their team label, then **remove** the `triage-bot/needs-triage` label

**Comment by jdorfman** [comment]
@moldach the fastest way to do this is to request a demo: https://about.sourcegraph.com/demo

They can get you set up with a trial.

**Comment by yowayb** [comment]
Thank you @jdorfman !  Hi @moldach !  Thank you for meeting with us last Wednesday.  If you decide to go ahead with a trial, I will create the license key for you.
