### ISSUE TITLE
insights: migrate all logging to `sourcegraph/log`

### ISSUE THREAD

**Issue by leonore** [sourcegraph/sourcegraph#39976]
we should update our code to use the `sourcegraph/log` library: https://docs.sourcegraph.com/dev/how-to/add_logging

/cc @joelkw @felixfbecker @vovakulikov @unclejustin

**Comment by YashasviChaurasia** [comment]
@leonore, I would like to work on this Issue.
Thank you.

**Comment by leonore** [comment]
hi @YashasviChaurasia, I accidentally tagged this one as `good first issue`- please refer to our [general list](https://github.com/sourcegraph/sourcegraph/labels/good%20first%20issue) to see if there are any other issues you'd like to work on

**Comment by leonore** [comment]
as mentioned in the issue above this might be low-effort enough and would be nice to get done, P1

**Comment by coury-clark** [comment]
IMO backlog - we have a lot of other things to get done and this is a pretty low value migration for us right now
