### ISSUE TITLE
totalCount is missing from repositories statuses "Needs index", "Failed fetch/clone"

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#39980]
- **Sourcegraph version:** 3.42

#### Steps to reproduce:

1.  Invoke API 
```
query{
	repositories(first:1000, notIndexed: true, indexed:false){
		totalCount
	}
}
```
or
```
query{
	repositories(first:1000, failedFetch:false, notCloned:false){
		totalCount
	}
}
```

Response:
```
{
  "data": {
    "repositories": {
      "totalCount": null
    }
  }
}
```

#### Expected behavior:

`totalCount` has a value when looking for status "Needs index" and "Failed fetch/clone".

#### Actual behavior:

`totalCount` is `null`

#### Additional Details
- [Internal Slack discussion](https://sourcegraph.slack.com/archives/C02EDAQAJQZ/p1659556145900659)
- Customers: https://github.com/sourcegraph/accounts/issues/6716, https://github.com/sourcegraph/accounts/issues/3

/cc @jplahn @ryphil

**Comment by mrnugget** [comment]
`needsIndex` is a whole different thing (for now), but I added `totalCount` for cloned/uncloned: https://github.com/sourcegraph/sourcegraph/pull/41370

**Comment by cbart** [comment]
Did not mean to close this. That was just one pull request.
