### ISSUE TITLE
Ruby support

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#4]
Support Ruby on Sourcegraph.

**Comment by nicksnyder** [comment]
We will actually be adding experimental support for Ruby in our 2.8 release which is scheduled for next week. Keep an eye out for our blog post!

In general, we are committed to supporting all languages through the Language Server Protocol. Check out https://github.com/sourcegraph/lsp-adapter/tree/master/dockerfiles/ruby and http://langserver.org for more info!

**Comment by chrismwendt** [comment]
Experimental Ruby support has been shipped in Sourcegraph 2.8! Check out the blog post https://about.sourcegraph.com/blog/code-intelligence-for-more-languages-and-lsp-language-server-protocol-support

![ruby](https://user-images.githubusercontent.com/1387653/40394458-68820f36-5dd8-11e8-9a6b-72f421c2864f.gif)

Thanks go to the [castwide/solargraph](https://github.com/castwide/solargraph) project for providing the language server.

**Comment by franklinyu** [comment]
@chrismwendt I expect it to land on sourcegraph.com when it becomes stable in future?

**Comment by chrismwendt** [comment]
We would love to :smiley: Language servers on sourcegraph.com implement [extensions to the Language Server Protocol](https://github.com/sourcegraph/language-server-protocol) that describe cross-repository code intelligence and a virtual file system for performance reasons. We're looking forward to more language servers supporting these extensions in the future, and we keep track of the functionality that each language server provides on http://langserver.org/.

In the meantime, you can get Ruby support by running your own instance of Sourcegraph Server and [enabling the Ruby language server](https://about.sourcegraph.com/docs/code-intelligence/experimental-language-servers#using-an-experimental-language-server-on-sourcegraph-server) (it's really quick to set up!).

**Comment by sqs** [comment]
See https://twitter.com/srcgraph/status/1070628324542603265:

💎 Ruby code intelligence is here...kind of!

The [basic-code-intel Sourcegraph extension](https://sourcegraph.com/extensions/sourcegraph/basic-code-intel) finds definitions and references in code using text search + ctags heuristics.

Now enabled for everyone on https://sourcegraph.com and the [Chrome/Firefox browser extensions](https://docs.sourcegraph.com/integration/browser_extension).

Try it at https://sourcegraph.com/github.com/rails/rails/-/blob/activesupport/lib/active_support/cache/redis_cache_store.rb#L48:11&tab=references or any other Ruby project.

**Comment by FranklinYu** [comment]
The "Go to definition" works great. I understand that Ruby is such a dynamic language that method resolution would be rather difficult.

Look forward to more improvements. It would be awesome if documentation can also be generated (with Yardoc or similar tools).

Thank you for your work.

**Comment by chrismwendt** [comment]
Ruby code intelligence has been added in Sourcegraph 3.0 :tada:

https://about.sourcegraph.com/blog/sourcegraph-3.0#code-intelligence-for-all-languages

[Try it out](https://sourcegraph.com/github.com/jnunemaker/httparty@011c1ac3e3888218ffacc49db231bd81efe0f7f8/-/blob/lib/httparty/connection_adapter.rb#L114:7) on Sourcegraph.com:

![image](https://user-images.githubusercontent.com/1387653/54005751-6ff2aa80-410f-11e9-8ed1-fd981ff706b5.png)

**Comment by FranklinYu** [comment]
@chrismwendt Is documentation generated in the hover card? I don’t think I saw that on Sourcegraph.com.

**Comment by chrismwendt** [comment]
@FranklinYu Yup! I updated the example to one which has documentation.

**Comment by FranklinYu** [comment]
@chrismwendt The httparty gem doesn’t really have much documentation, so it’s not a good example of this feature. Most documentations in that gem are just one line of description. What I was asking for is structured documentation like [this one](https://sourcegraph.com/github.com/jneen/rouge@v3.3.0/-/blob/lib/rouge/regex_lexer.rb#L32:11) (note the special syntax `@see`). It should be rendered like [this](https://www.rubydoc.info/gems/rouge/3.3.0/Rouge/RegexLexer/State) (note the subsection “See Also” under section “Overview”).

IDEs like RubyMine correctly show tooltip with those documentations. It would be cool if Sourcegraph does that as well.

**Comment by chrismwendt** [comment]
@FranklinYu Thanks for the feedback! I included it in https://github.com/sourcegraph/sourcegraph/issues/2298
