### ISSUE TITLE
spike: Web Charts: Expose chart UI building blocks together with built-in high level charts

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#40009]
Preparation for https://github.com/sourcegraph/sourcegraph/issues/36094

## Background

Currently, we expose only high-level chart components from the chart package. This brings a significant benefit in that consumers don't need to think about how to implement all chart UI parts themselves. But at the same time, this approach blocks us from high-level customisations in charts. Like adding additional data with particular styles, with unique hover and tooltip content. More on this in this comment https://github.com/sourcegraph/sourcegraph/issues/36094#issuecomment-1192357209

In this issue, we should develop building blocks API and expose it together with high-level charts from the chart package. This will allow them to build their charts by re-using complicated chart parts but bringing their custom content. 

We don't need to refactor the whole chart codebase for it. Some part of this has been done in this PR about axis components https://github.com/sourcegraph/sourcegraph/pull/39805. 

/cc @joelkw @felixfbecker @vovakulikov @unclejustin

**Comment by unclejustin** [comment]
https://github.com/sourcegraph/sourcegraph/pull/41448 introduced a property that is only used by aggregations.

We could (should?) make it possible to provide a `sortBy` function, but right now, the chart uses lodash `groupBy` internally. This means we must know about the structure that `groupBy` uses to sort.

**Comment by vovakulikov** [comment]
## Thoughts 
So in the past 1-2 months, we introduced a few consumer-specific props in the high-level charts. This is a bad thing that stands against the high-level chart principle - "High-level chart doesn't support all possible cases but provides a simple good first data visualization". 

To be more specific, we added.

- **`pixelsPerYTick?: number`**
- **`pixelsPerXTick?: number`**
- **`hideXTicks?: boolean`**
- **`minAngleXTick?: number`**
- **`maxAngleXTick?: number`**
- **`getScaleXTicks?: <T>(options: GetScaleTicksOptions) => T[]`**
- **`getTruncatedXTick?: (formattedTick: string) => string`**

Most of these props are related to the Axis components, so we need to expose these components together with high-level charts in the chart package. In order to build your own chart right in the consumer and manipulate with axis components directly in consumers 

Example 
```tsx
function ConsumerChart() {
  const xScale =  scaleBand<string>({ domain: ['category1', 'category2', 'category3'], padding: 0.2 }),
  const yScale = scaleLinear<number>({ domain: [0, 100] })

  return (
     <Chart xScale={xScale} yScale={yScale}>
        <ChartAxisLeft {/* Any consumer specific props */}/>
        <ChartAxisBottom {/* Any consumer specific props */} /> 

        <ChartContent>
              { content => <AnyConsumerSpecificContent {/* Any consumer specific props */}/> }
        </ChartContent>

        <ChartTooltip {/* Any consumer specific props */} />
     </Chart>
  )
}
```

This API saves high-level charts from consumer-specific props and handling too many logic branches within high-level chart render. `<AnyConsumerSpecificContent />` means that the consumer could render anything custom, but it also may be useful to provide prepared content UI blocks (as we do with the axis component in this example above) 

for example 

```tsx
 <ChartContent>
      { content => <GroupedBars {/* Any consumer specific props */}/> }
 </ChartContent>
```

`<GroupedBars />` is just an example here; it also might be `BarStack`, similar to what visx does. Any other low-level components consumers can use from the Visx directly (like <Group /> Line, Rect, ...etc)

So the full list of this UI abstraction as a see this is
- `GroupedBars` - renders standard group (list) of bars
- `StackedBars` - renders stacked bars 

Any other (custom) abstractions should live outside of the chart package and should be stored in chart consumer where it's used

## List of actions to adopt this API 
- [ ] Expose SvgAxis low-level compound components (we already have them and we need just wrap them with chart components (or rename them) and expose them from the chart package) 
- [ ] Extract the `GroupedBars` component from the bar chart codebase and also export it 
- [ ] Extract the `StackedBars ` component from the bar chart codebase and also export it. We also need to restructure API and implementation there to support active bar highlighting
- [ ] Extract the `Tooltip` component and make it compoundable with the root `Chart` component or order to connect it with actions (focus, hover) in GroupedBars or StackedBars components
- [ ] Provide a set of examples in the chart package documentation 
- [ ] After all of this, we can start removing high-level chart props and replace high-level bar charts in consumers where it's needed (like aggregation UI) 

Note that this change doesn't cover LineChart high-level component. But we also need to tackle it to support more custom charts in the code insights live preview (see for more details https://github.com/sourcegraph/sourcegraph/issues/36094#issuecomment-1192357209) 

For the line chart, we need to come up with a similar approach 
- [ ] Adopt new SVG axis components in the line chart UI
- [ ] Reuse the `Tooltip` component that we extracted in the bar chart API work 
- [ ] Expose LineSeries and LineStackedSeries components 
- [ ] After this, we can start working on a custom live preview problem in the creation UI https://github.com/sourcegraph/sourcegraph/issues/36094 


cc @unclejustin

**Comment by unclejustin** [comment]
This approach looks good to me. We're good to close this issue and create a tracking issue for this debt.

**Comment by leonore** [comment]
@vovakulikov FYI I'm closing the milestone this is one, just so you don't forget this issue exists

**Comment by vovakulikov** [comment]
Closing this one, as a result of this spike we filed a tracking issue for chart api improvements https://github.com/sourcegraph/sourcegraph/issues/42008
