### ISSUE TITLE
repo-updater: store repo links in repo.sources

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#4001]
In https://github.com/sourcegraph/sourcegraph/issues/3466 we already noticed that once we load data solely from the database (which is now done after merging https://github.com/sourcegraph/sourcegraph/pull/3967) we can store  repo links in the repo.sources column and service them straight from the database, too, instead of constructing them on the fly here RepoLookup

**Comment by keegancsmith** [comment]
Out of interest what is the benefit of this vs just leaving it as is?

**Comment by mrnugget** [comment]
I think @tsenart's idea behind this was that we reduce the places in the codebase where we construct a "fully formed" repository. At the moment we construct the one part when sourcing them and then we add the links on-the-fly when we load them from the database.

As I understand it, this is not a pressing issue but rather an optimization (since it would also make RepoLookup faster, I guess)

**Comment by tsenart** [comment]
> I think @tsenart's idea behind this was that we reduce the places in the codebase where we construct a "fully formed" repository. At the moment we construct the one part when sourcing them and then we add the links on-the-fly when we load them from the database.

That was the idea.

> As I understand it, this is not a pressing issue but rather an optimization (since it would also make RepoLookup faster, I guess)

I agree. Not a pressing issue.

**Comment by keegancsmith** [comment]
I suppose this brings up a more meta question for me. Is this worth tracking in our issue tracker? How do we distinguish this issue amongst more pressing issues?

**Comment by tsenart** [comment]
Not relevant anymore, so closing.
