### ISSUE TITLE
Spike: investigate dynamic content for homepage filter chips

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#40013]
Currently filter chips only show static, predefined content.

We want to show data that actually exists on the instance (repo names, file names, authors).

Strawman idea from @lguychard: if we run `type:diff count:1` that will give us a valid repo name, file name, author, commit message. We could cache the results in temporary settings to avoid running this on every homepage load.

/cc @benvenker @lguychard

**Comment by quinnkeast** [comment]
I have high confidence these filters will remain after iteration:

- `repo:org/repo`
- `repo:org/*`
- `file:example.ext`
- `author:name type:commit`

I think each of these would be good candidates to be dynamic. They don't need to personalized to the user, just the instance.
