### ISSUE TITLE
insights: generate new queries from captured values

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#40045]
To facilitate drill down when viewing an aggregation insight that is grouping on values we need to be able to produce new search queries 

### Limitations
For v1, the limitation is being applied that _matches_ will only originate from the leftmost capturing group in the pattern (ie. group `$1`). This replacement will also not work for `patternType:structural`. Additionally, there is a limitation that only a single value can be replaced (we will not allow multiple selections).

### Implementation notes
For a `patternType:literal` the entire search `content` can simply be replaced.

For a `patternType:regexp` we need to generate new regexp strings that have replaced a portion of the pattern with the literal matches. When a pattern is generated it should be wrapped in a non-capturing group, allowing the query to effectively iterate and drill down. The replacement string should be regexp escaped.

#### Regexp
| old pattern    |  text   |  new pattern   |
|-----|-----|-----|
|   `(\w+)`  |  `bear`   | `(?:bear)`    |
|  `(\w+)-(\w+)`   |  `dog-cat`   |  `(?:dog)-(\w+)`   |
|  `(?:\w+)-(\w+)`   |  `dog-cat`   |  `(?:\w+)-(?:cat)`   |
|   `(.*)`  |  `\w`   | `(?:\\w)`    |

**Comment by felixfbecker** [comment]
@coury-clark is there a reason the `(?:bear)` is wrapped in a non-capturing group? Since the content of that group is always a literal, seems like it should be safe to just put it into the query literally (escaped of course, but without the need to wrap it)

**Comment by coury-clark** [comment]
@felixfbecker it simplifies the implementation and I think makes the most sense (that way it's always the same pattern). I think the implementation might be quite a bit more complicated for what is semantically the same query.

**Comment by felixfbecker** [comment]
How does it simplify the implementation/how would it otherwise not always be the same pattern?

**Comment by coury-clark** [comment]
@felixfbecker oh sorry, maybe I've misunderstood (I thought you meant turn it into a literal search if possible). You just mean drop the group around it?

**Comment by felixfbecker** [comment]
Yeah, sorry when I said "literal" I meant that it is just a string of characters, not a regular expression. I wasn't referring to literal search. The only reason I could see why a group would be needed was if what we were trying to replace it with a regular expression that could be something like `a|b` (need to isolate the "OR"/`|`), but it's always just a string.

**Comment by coury-clark** [comment]
Ah got it. Yeah, so in the linked PR you will see that I put up an implementation where it _can_ support multiple matches in an OR-ed group. For the purposes of this issue maybe we can drop that, but I think implementation wise it's easy to generalize the replacement and then stop counting after group number 1

But this conversation did remind me that the contents need to be regexp escaped, so I've added a note.

**Comment by coury-clark** [comment]
Closed by https://github.com/sourcegraph/sourcegraph/pull/40533
