### ISSUE TITLE
Implement enforcements for updated packaging

### ISSUE THREAD

**Issue by ryphil** [sourcegraph/sourcegraph#40064]
More details can be found in [this document](https://docs.google.com/document/d/1q1AiigPbzX1bwpSfQblGJfWTpGlwpRfxlW5GIL6ZnjY/edit#bookmark=id.tf1cgyb53jqw). 

Note: This ticket is only focused on gating the 3 enterprise tiers (Free/Business/Enterprise). Each team will own OSS gating. 

### TODO

- [x] Quick discovery for scoping the work needed @unknwon https://docs.google.com/document/d/1R2LM0JEPTjn7YdoMqKvmGWTkKzSldW1knQpnrNg_-p8/edit#

**Comment by unknwon** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IAM-627aebcc9f8b7c00128a8ab6/issues/sourcegraph/sourcegraph/40064?planning-poker) with ZenHub @kopancek @miveronese @pjlast

**Comment by unknwon** [comment]
FYI @ryphil @miveronese Here is the work breakdown I identified so far, OSS is excluded since we plan not to do it for now: https://docs.google.com/document/d/1R2LM0JEPTjn7YdoMqKvmGWTkKzSldW1knQpnrNg_-p8/edit#
