### ISSUE TITLE
Search input state toggles incorrect size

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#40074]
The buttons embedded in the search query UI (Case sensitivity, regex, structural, copy query) are presently 20x20. These are intended to be 24x24. Similarly, the content within the buttons is undersized relative to the specification in Wildcard. 

**Current:**

<img width="391" alt="image" src="https://user-images.githubusercontent.com/6304497/183387030-660becd8-26be-4a3d-aa79-120c03ec5e79.png">

<img width="250" alt="image" src="https://user-images.githubusercontent.com/6304497/183387171-d8815ee3-72ac-4a10-903b-8cdd28dc5c4e.png">

**Expected size:**

<img width="323" alt="image" src="https://user-images.githubusercontent.com/6304497/183387103-fa59667b-2f2a-4fae-82ae-446deaf37b56.png">

<img width="341" alt="image" src="https://user-images.githubusercontent.com/6304497/183387262-cc0d8c2a-811d-4d6d-ada8-05ee25094d71.png">

Reference to elements in Wildcard in Figma: [https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/%E2%9C%B3%EF%B8%8F-Wildcard-Design-System?node-id=815%3A76280](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/%E2%9C%B3%EF%B8%8F-Wildcard-Design-System?node-id=815%3A76280) 

/cc @benvenker @lguychard

**Comment by camdencheek** [comment]
Seems to have been fixed with the newish search input
