### ISSUE TITLE
Tweaks to autocomplete popover formatting

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#40072]
### Background

We're exploring a minimal prototype of search history as an autocomplete suggestion in an empty search input (#39944). While making sure that the search history items were usable/legible, we did a few adjustments to the spacing and padding in the autocomplete dropdown content.

When we switched to CodeMirror for the search input and autocomplete dropdowns, the visual UI didn't receive explicit design consideration. As such, there's a few small changes we can make to improve the usability through style adjustments and timing changes.

### Proposed changes

[Visual proposal can be viewed in Figma](https://www.figma.com/file/fbJ80hSyycPhBcGCeUAYVK/Tweaks-to-autocomplete-popover-formatting?node-id=0%3A1).

The specific changes:

- [x] Right align the helper content. 
  - [x] When content is longer than can be shown: truncate the right side of the helper text with ellipses (note—use the single-character `…` rather than three dots `...`).
- [x] Remove italics from helper content and reduce the font size a bit further to `0.75rem` (to start—may need to adjust further).
- [x] Shift the top edge of the autocomplete popover `~5px` lower, so that the top edge of an autocomplete dropdown aligns with the top edge of the search contexts popover.
- [ ] Add a small delay (~100ms to start, we'll adjust from there) before displaying an autocomplete dropdown. The goal is to only show the dropdown _after_ the user has paused typing, but quickly enough that it's not a noticeable delay. This change will prevent the dropdown from appearing in a spastic way.

## Additional consideration

Right aligning the helper text means the `Tab` tip causes text jumping. This could be fixed by showing the `Tab` element absolutely, with a background colour + underlying gradient on top of the item; however, that this element exists at all is a UX workaround for the autocomplete dropdown not accepting `Enter` to select an item, which we weren't previously able to resolve. With the switch to CodeMirror, this is resolved in #39177. 

If we were to enable this updated behaviour by default, we could remove the `Tab` helper altogether.

## Additional consideration

Right aligning the helper text means the `Tab` tip causes text jumping. This could be fixed by showing the `Tab` element absolutely, with a background colour + underlying gradient on top of the item; however, that this element exists at all is a UX workaround for the autocomplete dropdown not accepting `Enter` to select an item, which we weren't previously able to resolve. With the switch to CodeMirror, this is resolved in #39177. 

If we were to enable this updated behaviour by default, we could remove the `Tab` helper altogether.

**Comment by limitedmage** [comment]
Working through this issue, I can't get the delay to work nicely. It looks like CodeMirror, the library we use for the search query input, does not support delaying showing the autocomplete. I managed to make it sort-of work with a hacky animation, but now the autcompletion flickers every time it gets new results. Here's a video:

https://user-images.githubusercontent.com/206864/186536008-fede7a9e-2f95-4a79-b039-ee0c4e7e9794.mp4

I'm not sure if adding that delay will be possible without a ton of work of going through every autocomplete source and somehow passing a keyboard event to see if the user has finished typing before sending anything :confused: Seems like a very high cost for this. If we want to keep trying for this, I think it's best to wait until @fkling returns from vacation since he's the expert on this and might be able to figure it out better than I can.

**Comment by limitedmage** [comment]
Reopening and assigning to @fkling to see if you can figure out the delay.

**Comment by fkling** [comment]
Sorry, I did not notice that this was assigned to me 😬 

There isn't an option to configure the delay but I can look at how exactly it is triggered by default and see we can implement this behavior ourselves with delay.

**Comment by fkling** [comment]
So, delaying showing the suggestions didn't really work (would need proper support from upstream) but there is an alternative approach to reduce the flickering: https://github.com/sourcegraph/sourcegraph/pull/43165

Let me know what you think!
