### ISSUE TITLE
HubSpot extension in browser extension fails due to CORS

### ISSUE THREAD

**Issue by christinaforney** [sourcegraph/sourcegraph#4007]

**Comment by felixfbecker** [comment]
@christinaforney do you have more details? I just filed https://github.com/sourcegraph/sourcegraph/issues/9501 but I didn't see anything that would indicate it is because of CORS

**Comment by christinaforney** [comment]
I think I filed this issue on my first day at Sourcegraph - probably with the help of someone else and honestly have no idea what it was about (apologies for the lack of information 🤦‍♀ ). Probably best to close it out.
