### ISSUE TITLE
WIP: src-cli users clean

### ISSUE THREAD

**Issue by DaedalusG** [sourcegraph/sourcegraph#40102]
### Plan
This is a project to bring a python utility script `users_clean.py` into the main project under `src`. Currently the CE team often provides this utility script to customers as a bandaid for cleaning up users for license seat reasons. 

The script to be emulated: https://github.com/sourcegraph/customer-assets/blob/main/ce-tools/pysdk/cleanup_users.py
_Thanks @mike-r-mclaughlin !_

### Tracked issues

Working branch: 
https://github.com/sourcegraph/src-cli/tree/users-clean

- 👩 Customer issue
Users need to be able to remove users in a single command based on usage, this will help to maintain seats for an accurate number of users

- 🙆 Stretch goal
- specify hard removal and soft removal
- send emails to removed users

**Comment by DaedalusG** [comment]
The majority of this after my initial hack session is contained in: https://github.com/sourcegraph/src-cli/blob/users-clean/cmd/src/users_clean.go

Currently the command just gets the necessary data from the graphQL API and prints to confirm
```
warrengifford@Warrens-MacBook-Pro cmd % src users clean
Time now: 2022-08-08 09:48:16.754539 -0700 PDT m=+0.574291190
Last Active: 2022-08-06T17:02:47Z2022-08-06T17:02:47Z -- 1000
beatrix  true beatrix@sourcegraph.com
Time now: 2022-08-08 09:48:16.755247 -0700 PDT m=+0.574999199
Last Active: 2022-08-08T10:03:09Z2022-08-08T10:03:09Z -- 1000
warren  true warren@sourcegraph.com
```

Will soon implement `time.Sub()` and the Time type object for the graphQL return
`time.Parse(time.RFC3339, payload.UsageStatistics.LastActiveTime)`

**Comment by mike-r-mclaughlin** [comment]
https://github.com/sourcegraph/accounts/issues/6716 is very interested in this.  see this [internal slack thread](https://sourcegraph.slack.com/archives/C01D50MSA7L/p1659431596108699).

**Comment by DaedalusG** [comment]
Little update on progress here:
https://loom.com/share/16a577e248e040aea9ebe40fac043dfc

https://user-images.githubusercontent.com/13024338/184427099-75717dc3-4c5d-45d9-81bd-d91edc23ce0b.mp4
