### ISSUE TITLE
Add site admin alert for sites with one or more pre-v12 GitLab code hosts

### ISSUE THREAD

**Issue by LawnGnome** [sourcegraph/sourcegraph#40106]
Since it looks like we'll be going ahead with removing support for GitLab < 12 soon (hopefully in 4.0), we should add a site admin alert banner ASAP that becomes visible if there are one or more code hosts using older versions of GitLab. The CTA here would presumably be to upgrade their GitLab instance before upgrading to Sourcegraph X.Y (whatever version we decide we're going to drop legacy version support in).

Determining this will presumably involve [adding a site alert](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@097d6c301c02c2fecb500d3b048fcc39eeb6bcd3/-/blob/cmd/frontend/graphqlbackend/site_alerts.go?L13) that calls [`gitlab/Client.GetVersion`](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@097d6c3/-/blob/internal/extsvc/gitlab/version.go?L12-31) on startup and then periodically (once a day?) for each GitLab code host. I think we could likely get away with just keeping that in a global `frontend` variable, rather than persisting it anywhere.

**Comment by chrispine** [comment]
Hard P0

**Comment by chrispine** [comment]
We got the green light! Note that this ticket should also include updating [the docs](https://docs.sourcegraph.com/admin/external_service/gitlab#supported-versions).

**Comment by courier-new** [comment]
I have created a follow-up issue to remove this alert (or promote it to an error?) before we release 4.0: https://github.com/sourcegraph/sourcegraph/issues/40290
