### ISSUE TITLE
executors: Better shared secret

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#40101]
OIDC? This has been suggested.

It should be possible to rotate, and not be long-lived.

**Comment by eseliger** [comment]
Also potentially look into limiting executor access to things that it requires for the currently owned jobs. 
Ie. only let it clone repos {X,Y} when it actively works on those.

**Comment by eseliger** [comment]
Might close https://github.com/sourcegraph/sourcegraph/issues/27539

**Comment by eseliger** [comment]
```
diff --git a/enterprise/cmd/frontend/internal/executorqueue/handler/handler.go b/enterprise/cmd/frontend/internal/executorqueue/handler/handler.go
index 8f7c2625b7..6b48ed15b6 100644
--- a/enterprise/cmd/frontend/internal/executorqueue/handler/handler.go
+++ b/enterprise/cmd/frontend/internal/executorqueue/handler/handler.go
@@ -70,6 +70,18 @@ func (h *handler) dequeue(ctx context.Context, executorName string) (_ apiclient
 		return apiclient.Job{}, false, errors.Wrap(err, "RecordTransformer")
 	}
 
+	// Create ExecutorSecret Scope: HandlerAccess
+	// Attach Secret value to job as APIToken
+	// TODO: A database trigger to delete tokens when the job is wiped?
+	// This token is to be used on the executor side to properly identify
+	// as the owner of the job.
+	// In all executors handlers except Dequeue this tokens should be the only
+	// allowed authentication mechanism.
+	// TODO: The next step would be to add an endpoint to "register" an executor.
+	// That would also fix the heartbeat - telemetry problem from another ticket.
+	// That register endpoint would return a dequeue token. That way, we track
+	// which executor was compromised.
+
 	return job, true, nil
 }
 
@@ -119,6 +131,8 @@ func (h *handler) markComplete(ctx context.Context, executorName string, jobID i
 	if !ok {
 		return ErrUnknownJob
 	}
+	// TODO: Delete executor token.
+
 	return nil
 }
 
@@ -136,6 +150,8 @@ func (h *handler) markErrored(ctx context.Context, executorName string, jobID in
 	if !ok {
 		return ErrUnknownJob
 	}
+	// TODO: Delete executor token.
+
 	return nil
 }
 
@@ -153,6 +169,8 @@ func (h *handler) markFailed(ctx context.Context, executorName string, jobID int
 	if !ok {
 		return ErrUnknownJob
 	}
+	// TODO: Delete executor token.
+
 	return nil
 }
 
```

**Comment by eseliger** [comment]
After a few months of talking about various things on this topic, I think this is a twofold issue:

Executors should have 2 secrets, not one. 
Secret number 1 is what we know as the shared secret today. It is used by the executor to authenticate with Sourcegraph and "register" as an executor. This token will only be usable for registering the executor, for heartbeat requests and for dequeueing a job. When the token is leaked, the blast radius is limited to dequeueing jobs and doing whatever with those.
Secret number 2 is a new secret and will be issued *per job*. In dequeue, a new secret is created and attached to the job, then that secret is returned to the executor as part of the job payload. This secret is used to authenticate logAppend requests, MarkFailed, MarkComplete, to clone the jobs repo, and to upload artifacts. In the route handlers, we should only accept this secret type for those endpoints. When validating the secret, we should also validate that it belongs to the given job, and for the git endpoint that it belongs to the given repo. That will reduce the blast radius of leaking any of the two secret types, because only repos will be cloneable that are actually attached to the jobs owned by that executor. This will also prevent malicious executors from marking unowned jobs as failed or injecting bad logs.

So the flow would be something like the following:

```
Executor --secret1--> SG: Dequeue
SG --Job{secret2}--> Executor
Executor --secret2--> AddExecutionLogEntry
Executor --secret2--> UpdateExecutionLogEntry
...
Executor --secret2--> UpdateExecutionLogEntry
Executor --secret2--> MarkComplete
```

**Comment by Piszmog** [comment]
Closing this issue in favor of #46171 (Job specific tokens)
