### ISSUE TITLE
Audit all functionality that is used in the CommandPalette

### ISSUE THREAD

**Issue by ryankscott** [sourcegraph/sourcegraph#40132]
We should look at all the functionality provided by the CommandPalette and see if anything is left after we remove extensions

**Comment by philipp-spiess** [comment]
Both [Taras](https://github.com/sourcegraph/sourcegraph/pull/40247#discussion_r944298496) and me had a look now and it seems that command palette is not doing anything if there are no extensions providing actions. I’m going to remove it as part of #40247
