### ISSUE TITLE
batches: non-site-admin cannot view drafts, execution status in main BC list

### ISSUE THREAD

**Issue by courier-new** [sourcegraph/sourcegraph#40157]
**EDIT** See comment below for updated findings.

**Steps to repro:**

1. Create a batch change with server-side UI but leave it in the draft state
2. Create a batch change and execute the spec with server-side UI, but don't apply it
3. View the batch changes list page as a site admin
4. View the batch changes list page as a non-site admin

**Expected behavior:**
- The draft BC is visible, and the BC with the active execution has the execution status pill inset

**Actual behavior:**
- Only the site admin can see the draft BC and execution status pill inset

**Comment by courier-new** [comment]
The executions list for a batch change is also completely empty.

**Comment by courier-new** [comment]
This is actually expected behavior as drafts are treated as private and therefore should not be visible by non-admins. Likewise, executions for a batch change are private except to the user who authored the batch change.

Until we have implemented public vs. private batch changes, we can in the meantime fix up the UX slightly in two ways:

1. While a non-admin cannot view the list of executions for a batch change, they can currently still view a single execution via its URL. We should treat a single execution consistently with the list and also restrict access except to admins/the author.
2. When a non-admin views the list of executions for a batch change they did not author, the list conveys that there are no executions, not that the current viewer simply cannot see them. We should either improve the empty list UX for non-admins or remove the "Executions" tab from the BC details page entirely, if a non-admin non-author is viewing it.

**Comment by adeola-ak** [comment]
do I need to consider organizations with this fix as well?

**Comment by courier-new** [comment]
Hey @adeola-ak, I just noticed we have this same "bug" for draft batch changes: a non-admin can't see draft batch changes on the list page, but they can still navigate to a draft by URL if they know the name of it (e.g. `/users/<username>/batch-changes/<bc_name>`). Either on this ticket or as a follow-up (however is best for you), do you think you could apply the same fix to the resolver for a batch change?
