### ISSUE TITLE
insights: insights return no data points for 0 values

### ISSUE THREAD

**Issue by leonore** [sourcegraph/sourcegraph#40167]
loom: https://www.loom.com/share/463efcf0ba6a474d863cf6d64701af45

this doesn't happen in the live preview- so there's a discrepancy in behaviour

when there are no historical captured value for a result (e.g. https://sourcegraph.sourcegraph.com/search?q=context:global+file:go%5C.mod%24+go%5Cs*%28%5Cd%5C.%5Cd%2B%29+%28.%5Cn*%29%2B+github.com/sourcegraph/log&patternType=regexp we have no captured results beyond a certain time), we return null

/cc @joelkw @felixfbecker @vovakulikov @unclejustin

**Comment by leonore** [comment]
the loom shows a lack of data for a recent match, this is because the frame is built from midnight UTC. so the snapshot point would pick up the newest data point

**Comment by leonore** [comment]
actually it is possible this is happening for search insights as well:

https://sourcegraph.sourcegraph.com/insights/insight/aW5zaWdodF92aWV3OiIyQ3VLekQ5c0hnVm5Dckp4MjgwcWQ0bHR2OVIi

![Image](https://user-images.githubusercontent.com/29406849/183939983-05ff801a-8600-482b-969e-6cedea48b0c1.png)

**Comment by Joelkw** [comment]
sync discussion – may not be as easy as we expect, it could be 2 solid weeks of time. Definitely a backend issue.

**Comment by leonore** [comment]
closing as duplicate of #39883
