### ISSUE TITLE
Error starting enterprise start.sh 

### ISSUE THREAD

**Issue by christinaforney** [sourcegraph/sourcegraph#4016]
![image](https://user-images.githubusercontent.com/1559622/57738214-5f0c6b00-7663-11e9-9a6e-aab7d4e4c544.png)

Just trying again worked to get things up and running, but for tracking purposes am logging here. This is low priority.

Specifically errored on `Did not find authentication provider matching "https://gitlab.sgdev.org"` causing the frontend server to terminate.

**Comment by keegancsmith** [comment]
@beyang any insight into why this is happening?

**Comment by dadlerj** [comment]
If not testing auth, you can add the environment variable `NO_KEYCLOAK=1 ./dev/start.sh` to avoid this I believe

**Comment by beyang** [comment]
This is a race condition on when the critical site config is loaded from dev-private, I believe. If the `gitlab.sgdev.org` auth provider is not added to critical site config before the app tries to initialize, we get this error.

**Comment by slimsag** [comment]
Very high chance this is fixed by https://github.com/sourcegraph/sourcegraph/pull/4154 or my change that preceded it.

**Comment by beyang** [comment]
Can't repro so closing, re-open if this re-occurs
