### ISSUE TITLE
Improve history item selection behavior

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#40182]
## Successful outcomes of this issue
- [ ] When a history item is active or hovered on:
  - [ ] Populate the search input with the history as if it was selected by enter or tab in today's implementation
  - [ ] Place an active cursor in the search input at the end of the input content
- [ ] If a search history item is clicked on with a mouse cursor or enter is pressed when the item is active, run the search directly

## Background
There are two defaults we don't have in our search history, that are convention in both browser histories and search engine suggestions/history and which, if implemented, eliminate the tradeoffs being debated in the comments below:

1. We don't populate the search input with the highlighted history item as you navigate through the history
2. Because of 1. we can't (and so don't) put an active cursor at the end of item displayed in the input, making it possible and natural to both edit a search if desired or run it directly by pressing enter

Additionally, with the change in typeahead behavior to allow enter or tab to autocomplete suggestions, but the simultaneous removal of the first item's automatic selection, we now require the user to press the down arrow to first select a suggestion before completing it.

### Video examples of browser history, Sourcegraph history, and Google search behavior

<video width="800" src="https://user-images.githubusercontent.com/4605817/186539037-2fa4e4ec-b47a-401c-9ae1-ecbbf99dda7b.mp4"></video>

---
#### Previous issue content for posterity
- Currently, when I click on a search history item, it populates the query but doesn't run the search.
- When I click on enter with a search history item, it runs an empty search. I know this is because of existing suggestion behavior but in this context it's more confusing than normal.*

*I think this will be partially resolved by a recent PR from @fkling, but not sure if there's more implementation work required for history.

**Comment by fkling** [comment]
> Currently, when I click on a search history item, it populates the query but doesn't run the search.

Is that the behavior we want? cc @quinnkeast

**Comment by benvenker** [comment]
It's how browser (at least FF and chrome) search history works and how editor search history works, so I think it's the sanest default. I would want to see a compelling argument for why we should deviate from those two experiences.

**Comment by quinnkeast** [comment]
+1 on populating but not running the search. Like @benvenker mentioned, this is basically resolved by the recent PR from @fkling, which is enabled for all users on S2 now—so, using this on S2 reflects the intended experience.

**Comment by fkling** [comment]
So to summarize:

- @benvenker wants to run the search when selecting the entry
- @quinnkeast does *not* want to run the search when selecting the entry

?

**Comment by quinnkeast** [comment]
🤦‍♂️ my brain's still pretty foggy, and I interpreted @benvenker's comment backwards.

Here's my compelling argument in why we should deviate: 

- As implemented, the search history is an autocomplete suggestion, same as every other autocomplete suggestion. While it's function is a bit different, the form is identical. However the selection behaviour works on the others should be the same, or it becomes inconsistent and untrustworthy.
- Users may be using the history for two reasons: to run the same search again, or as a starting point for a new search. For the former, it'd be a bit more convenient to have it run instantly, but hitting enter / search isn't a big deal. For the latter, running the search instantly interrupts the "starting point" by creating a new loading moment / change of context. This is more disruptive than having to hit enter again.

Should this history become part of an actual `⌘K` or similar console or other distinct element, then diverging behaviour would make sense.

**Comment by benvenker** [comment]
@quinnkeast and @fkling sorry, I missed the last comment. Some thoughts:
>As implemented, the search history is an autocomplete suggestion, same as every other autocomplete suggestion.

From a technical implementation perspective, search history is a suggestion component, but it doesn't behave like any of our other autocomplete suggestions. As soon as you start typing it disappears until you clear the entire input, which in practice makes it decidedly not an autocomplete suggestion–it's just a static list triggered on focus. All our autocomplete suggestions filter displayed options as you type, except the search history.


>Users may be using the history for two reasons: to run the same search again, or as a starting point for a new search.

True, but I'm willing to lean on the time-tested UX of browser histories and Google (and #2 Bing!) search to posit with confidence that users expect a search to be run directly when a history or suggestion is clicked or when a user presses "enter" while it's selected.

I feel pretty safe guessing that these are two of the most common searches a user ever performs in a web browser. I'm also confident that many more users than we'll ever have have needed to perform an iteration on a history item in Chrome, Firefox, or Google search, yet we have the browser and Google search UX we have today. That doesn't mean it's optimal, but it does mean that users are more likely to expect that UX than any other.

We can easily add event logs to validate that the majority of our users use the history to begin an iterative search and change our UX if needed, but existing web conventions indicate that that shouldn't be our default assumption.

One additional related UX note that might address both our issues: there are two standards we don't adhere to in both browser history and search engine suggestions/history that I think would resolve both @quinnkeast's and my issues if implemented:

1. We don't populate the search input with the highlighted history item as you navigate through the history
2. Because of 1. we can't (and so don't) put an active cursor at the end of item displayed in the input

These two defaults are convention in both browser histories and search engine suggestions/history and eliminate the tradeoffs being debated above.

I'm going to change the title and content of this issue to reflect this new approach so we can move forward with improving the experience.
