### ISSUE TITLE
Can we remove the basic-code-intel extension?

### ISSUE THREAD

**Issue by christinaforney** [sourcegraph/sourcegraph#4018]
The basic-code-intel extension is showing up in the list of Top Extensions on sourcegraph.com. We should either exclude deprecated extensions from showing up in the top list, or remove this extension entirely.

![image](https://user-images.githubusercontent.com/1559622/57739725-97af4300-7669-11e9-90af-f47583a51ed7.png)

**Comment by chrismwendt** [comment]
The old basic-code-intel extension has been deprecated for multiple iterations now, and the individual language extensions have been available since 3.0, so I deleted the old one.
