### ISSUE TITLE
Search history overlaps on bottom of search input

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#40181]
![serach input history overlap.png](https://images.zenhubusercontent.com/5467e9ba7c6ccc6277a5f103/178df066-e63d-45eb-a698-a1bd7c5fd6fb)

/cc @benvenker @lguychard

**Comment by quinnkeast** [comment]
This would also be addressed in #40072.

**Comment by lguychard** [comment]
Was addressed #40072

**Comment by lguychard** [comment]
Was addressed #40072
