### ISSUE TITLE
Executors should be backwards compatible 1 version

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#40191]
We want to start looking into what it takes to make executors at least 1 version backward compatible for smooth upgrades.

**Comment by chrispine** [comment]
Sounds like a good idea. Would the outcome be an RFC, or something else? Estimate?

**Comment by eseliger** [comment]
I think this will mostly require developer (Erik) discipline to not move too fast. The general product already follows this approach since we have backcompat testing that ensures new DB schemas work with 1 version behind code, and beyond that there it's also just developer discipline.
I don't think for executors we need anything special here that we wouldn't do already throughout the rest of the product, it's more a "when do we make this decision". Ideally, of course, executors had a test pipeline that we could set up in a similar fashion like we do DB backcompat testing, but sadly there is no E2E test platform for executors today. 
I think we can technically close this ticket and just say we want to practice this from now on, I mostly flagged it as a reminder to myself that this came up in a discussion.
