### ISSUE TITLE
cannot find package "github.com/google/zoekt/rpc"

### ISSUE THREAD

**Issue by h8liu** [sourcegraph/sourcegraph#402]
- **Sourcegraph version:** 
Commit 35835332f59c7cb9f4567e01166744b43f557b3f

- **Platform information:** 
Does not matter.

#### Steps to reproduce:

`go get github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend`

#### Expected behavior:

Success.

#### Actual behavior:

```
package github.com/google/zoekt/rpc: cannot find package "github.com/google/zoekt/rpc" in any of:
	/usr/local/go/src/github.com/google/zoekt/rpc (from $GOROOT)
	/Users/h8liu/go/src/github.com/google/zoekt/rpc (from $GOPATH)
```

The package `github.com/google/zoekt/rpc` does not seem to exist. Where is it from?

**Comment by h8liu** [comment]
Looks like I need to use go module to build.

**Comment by erezeshkol** [comment]
Hey @h8liu , I have the same issue (and am not at all familiar with golang) - could you please let me know how you fixed this? It'll also be useful for future people stumbling upon this issue :)

**Comment by h8liu** [comment]
@erezeshkol one is supposed to use go module to build.

https://golang.org/doc/go1.11#modules

fwiw, I did not fix it; I simply stop using it.
