### ISSUE TITLE
Write guide on how to manage Chrome extension downloads

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#40214]
- [ ] How to add the Sourcegraph extension automatically to Chrome managed instances
- [ ] Can we improve the setup experience by pre-defining the URLs?

(This is not a sunset extensions related feature but I added the label regardless so that we have it at the place we look at the most 🙈)  

/cc @muratsu @jjinnii @ryankscott

**Comment by vdavid** [comment]
New location for the doc @ryankscott linked above: https://docs.sourcegraph.com/integration/browser_extension/how-tos/google_workspace#automatically-install-with-google-workspace
