### ISSUE TITLE
insights: new graphql query endpoint to return aggregations for search results

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#40212]
Create a new graphql query endpoint and resolvers to return aggregation data for a search query.  This should accept as arguments the type of aggregation requested as well as the search query, version and search type currently sent to search a query parameters `q, v and t`.

The return value should include  a descending list of key (repo name, author, etc..) and counts (number of search results) ordered by the count field. 

In addition the response should indicate if the api was unable to aggregate this data in the allowed time, this should not be returned as an error.

**Comment by chwarwick** [comment]
We can use [this discussion](https://github.com/sourcegraph/sourcegraph/discussions/40194) to iterate on schema design.

**Comment by chwarwick** [comment]
Initial thoughts from @vovakulikov moved from a discussion

> Based on this comment about compute API for aggregations https://github.com/sourcegraph/sourcegraph/pull/40173#pullrequestreview-1067461986, it seems that we're going to use a standard GQL API instead of Compute streaming API. In this discussion, I want to talk about what FE may want from this possible GQL aggregation API for the search result page.
> 
> So it seems like that with designated aggregation resolver on the backend, we could move sorting and aggregation itself to the backend instead of calculating these things on the frontend (as initially planned and as it works in compute notebook card, for example)
> 
> If we're building API for the search result page, it seems that we could also move a link/query generation to the backend. Here I mean links for bars on the aggregation bar chart. We'll discuss it this week, but for now, it seems that not all link generation logic is trivial to have on the frontend.
> 
> We don't need to break down the query on the frontend to build a valid compute API query. This means that in this new GQL Aggregation resolver, we could pass just a regular query (as a string) and as the second param aggregation mode. (For Compute API, we had to extract non-filter substring in a separate string to build a valid content:insights() query)
> 
> So taking into account all these aspects, the API might look like

```graphql
enum AggregationMode {
   Repo,
   File,
   Author,
   CaptureGroup,
 }
 
 enum AggregationSort {
   ASC,
   DESC
 }
 
 query GetSearchAggregations($query: String!, aggregationMode: AggregationMode!) {
    aggregations: (sortBy: AggregationSort.ASC) {
       nodes: {
          label
          value
          // This is a drill-down query; it's the original query with replaced  
          // aggregation search part (if we aggregate by author, then this query has an additional author: filter)
          query
       }
    }
 }
```

**Comment by chwarwick** [comment]
I think it's important to note that sorting/filtering is out of scope for v1.  I proposed in the issue that we state the aggregations will be returned in descending order.  Any future changes or sorting could be accomplished by adding to the schema.

**Comment by chwarwick** [comment]
@vovakulikov  I worked on this some today and was thinking of a schema something along the lines of this:

```graphql
extend type Query {
    """
    Returns information about aggregate the potential results of a search query.
    """
    searchQueryAggregate(query: String, patternType: SearchPatternType): SearchQueryAggregate
}

"""
Supported aggregation modes for search aggregations
"""
enum SearchAggregationMode {
    REPO
    PATH
    AUTHOR
    CAPTURE_GROUP
}

"""
Information about search aggregations
"""
type SearchQueryAggregate {
    """
    A list of the possible aggregation modes and if they are available
    """
    modeAvailability: [AggregationModeAvailability!]!

    """
    A result of aggregating a search query.
    """
    aggregations(mode: SearchAggregationMode = REPO): SearchAggregationResult
}

"""
Information regarding the availability of a SearchAggregationMode
"""
type AggregationModeAvailability {
    """
    The SearchAggregationMode
    """
    mode: SearchAggregationMode!
    """
    Boolean indicating if the mode is available
    """
    Available: Boolean!
    """
    If the mode is unavailable the reason why
    """
    UnavailableReason: String
}

"""
Information regarding the availability of a SearchAggregationMode
"""
type SearchAggregationModeResult {
    """
    A list of individual aggregation values
    """
    values: [AggregationValues!]!
    """
    A count to capture the number of results that were not included in a named aggregation values
    """
    overflowCount: Int
}

"""
Information regarding the availability of a SearchAggregationMode
"""
type AggregationValues {
    """
    A label associated with the Aggregation for example a Repo name or Author name
    """
    label: String!
    """
    The number search results associated with this label
    """
    count: Int!
    """
    A modified search query that would filter the original query to just these values
    """
    query: String
}

"""
Defines how the data series is generated.
"""
union SearchAggregationResult = SearchAggregationModeResult | SearchAggregationNotAvailable

"""
Indicates that a search aggregation is not available
"""
type SearchAggregationNotAvailable {
    """
    The reason a search aggregation is not available
    """
    reason: String
}
```

I'm open to naming suggestions I struggled to find names to describe what  

Key things I was trying to accomplish:

- There is a way to query which aggregations types are supported without having to try run an aggregation
- When attempting to query for an aggregations if it is unable to process for a known reason such as: client asks for something not available, or it times out. We can express that via a type and aren't relying on deciphering error messages.
- Leaving space in returned object so that we can provide additional context about the list of aggregations.  For example, this list is not exhaustive, there were X results that overflow from the 500 Repo/Author/etc... that we returned

**Comment by vovakulikov** [comment]
@chwarwick this schema looks good to me. I like the union pattern here with a kind of error handling. We recently discussed this with @leonore about error handling in general for code insights queries.
