### ISSUE TITLE
Prepare doc + presentation for auth deep dive session

### ISSUE THREAD

**Issue by miveronese** [sourcegraph/sourcegraph#40255]
/cc @sourcegraph/iam

**Comment by malomarrec** [comment]
Hey @miveronese, this issue didn't have a team label. Given you created it, I assigned you and added your team label. Feel free to unassign yourself. If this is not the right label, can you make sure to add the right one?

**Comment by miveronese** [comment]
Slides: https://docs.google.com/presentation/d/1Py3g2sp3CSSy5m6Rq8_td3YJzMIEYluUDgJLQKTS0kM/edit
Recording: https://drive.google.com/drive/folders/1WYxoSsDAPhFBFK9M5qLt7ddtvUMsCzIV
