### ISSUE TITLE
Add "Analytics / Overview" page

### ISSUE THREAD

**Issue by erzhtor** [sourcegraph/sourcegraph#40264]
/cc @muratsu @a-bergevin

**Comment by malomarrec** [comment]
Hey @erzhtor, this issue didn't have a team label. Given you created it, I assigned you and added your team label. Feel free to unassign yourself. If this is not the right label, can you make sure to add the right one?

**Comment by erzhtor** [comment]
Closed by https://github.com/sourcegraph/sourcegraph/pull/40780.
