### ISSUE TITLE
Improve the message that appears in the UI when there are problems with repos in a code host

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#40271]
#### Feedback

A warning icon appears in the upper right corner of the UI for site admins when there are problems syncing repositories from a code host.  

Example:
![image](https://user-images.githubusercontent.com/23640224/184183679-ff8f81a4-3f41-482c-9c89-60727aa7ae4e.png)

It is always a generic (and sometimes misleading) [message](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/nav/StatusMessagesNavItem.tsx?L426:39&subtree=true): "Can't connect to  &lt;the code host name&gt;"

This can cause a lot of confusion and lost time when there is actually no problem connecting to a code host but rather there is a problem with a single (or a subset of) repository contained in the code host.   For example, if the token does not have access to a single repository, this message appears.  There is no problem connecting to the code host.  In fact, there's not a problem with all of the repositories except 1 in this example.  If you remove/exclude the failing repo, this message goes away.

#### Customer

https://github.com/sourcegraph/accounts/issues/3 and https://github.com/sourcegraph/accounts/issues/554

/cc @jplahn @ryphil

**Comment by jjeffwarner** [comment]
@jplahn I think the UI side of this is with your team if not, please feel free to reassign it.

**Comment by mrnugget** [comment]
I changed the wording slightly in https://github.com/sourcegraph/sourcegraph/pull/41254 and made the title/header of that message different. Let me know if that helped.

**Comment by mike-r-mclaughlin** [comment]
we heard about this same issue today from https://github.com/sourcegraph/accounts/issues/554.  Their feedback was that it's a very concerning message.  But, when you go and look at the status, the reality is that it's just a handful of repos that are having problems (not cloned or failed to fetch).  Here's an example:
![image](https://user-images.githubusercontent.com/23640224/188980984-afdb23d6-6a5e-4d88-8ab0-4b5bc8642333.png)

Also: it seems like a better user experience to have a link to the repository status page rather than the manage code host page (or maybe just link to both).

**Comment by mrnugget** [comment]
To avoid confusion, here's a (maybe) helpful graphic of what changed 😄 

![screenshot_2022-09-08_10 08 28@2x](https://user-images.githubusercontent.com/1185253/189070193-d23cb999-467d-43da-b5fb-3be2a277a444.png)

So in _your screenshot_ it looks like there are 2 problems:

1. The `GitHub Prod` code host connection cannot sync. That's the first message in your screenshot. This is still an error and links to the config for the code host connection.
2. Some repositories failed to `git fetch`/`git clone` - that's the third message in you screenshot. This will now be a warning and link to the "Failed fetch" repositories page.

So, your screenshot will change from 2 red messages to 1 red and 1 yellow.

Problem (1) will still exist though and the question is: what's the exact problem? To find out, you'd need to go to the code host connection page (which the first message links to). Example: https://sourcegraph.com/site-admin/external-services/RXh0ZXJuYWxTZXJ2aWNlOjE4Njg= Here you see why it failed to sync repositories:

<img width="970" alt="screenshot_2022-09-08_10 14 10@2x" src="https://user-images.githubusercontent.com/1185253/189071275-6ac35a66-60c2-4036-a738-b92f87e33756.png">

**Comment by mrnugget** [comment]
Closing this. Let's reopen when it pops up again.
