### ISSUE TITLE
Run / Document perforce manual tests

### ISSUE THREAD

**Issue by mollylogue** [sourcegraph/sourcegraph#40277]
Using the new perforce testing [tools](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/tree/dev/perforce-testing-helpers) run through suite of manual tests to verify perforce sub-repo permissions functionality, and document the process for running these tests in a doc. (There will be potentially future work to automate these tests but we are not currently set up for that.)

/cc @jplahn @ryphil

**Comment by ryphil** [comment]
@mollylogue - Are you actively working on this? If not, can you remove yourself from the assignee?

**Comment by mollylogue** [comment]
> @mollylogue - Are you actively working on this? If not, can you remove yourself from the assignee?

@ryphil no, not currently. I can remove myself. There's a google doc I created that I shared w/ folks months ago when we were doing some of this testing, but I got pulled off onto other priorities and it never got turned into a formal document. I'll find it and link it here.
