### ISSUE TITLE
Update search home filter content

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#40298]
We've landed on a first iteration of the search home content that we feel confident taking into further testing. 

In the linked Figma, the new content is included. For all the dynamic content, I've included new default values that should maximize usability (I'm not 100% sure on the term `organization` in the `repo:` filter examples though—will that be correct across possible code hosts? Thoughts appreciated here!).

I've also specified three separate followup tips. These seem like the obvious ones. If there's others that might be used with the other filters, please suggest!

[Link to Figma](https://www.figma.com/file/xq3ZrkzZ3Ytnqf8jTHmNYb/Search-home-in-simple-UI-%2339817?node-id=1994%3A20492)

/cc @benvenker @lguychard

**Comment by novoselrok** [comment]
> I'm not 100% sure on the term organization in the repo: filter examples though—will that be correct across possible code hosts?

Probably not correct 100% of the time, but it's a reasonable assumption.
