### ISSUE TITLE
Remove GitLab < 12.0 deprecation site alert

### ISSUE THREAD

**Issue by courier-new** [sourcegraph/sourcegraph#40290]
We will stop support GitLab versions < 12.0 in Sourcegraph 4.0. We have [added a site alert](https://github.com/sourcegraph/sourcegraph/pull/40289) for admins to warn them to upgrade if we detect they are using a code host on an unsupported version. Before we release 4.0, we should either remove the alert or promote it into a more aggressive error (e.g. "You're running an unsupported version of GitLab, plz upgrade now before something breaks").

**Comment by chrispine** [comment]
I vote for the more aggressive error.

**Comment by courier-new** [comment]
We'll take the more aggressive error route until we actually migrate to the GraphQL API, at which point we would expect more obvious things to break.
