### ISSUE TITLE
Code Insights: Conduct design UI/UX review for the aggregation project 

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#40306]
[RFC](https://docs.google.com/document/d/1yLV7MGOEXYT3yPvBxHHm8y2-p737KIrju_QPqlhBYz4/edit) 
[Figma Desings](https://www.figma.com/file/cKSeCtmBh9aiPsAVoKsLgM/Aggregation-insights%3A-display-%22grouped%22-insights-for-existing-searches-%2339126?node-id=275%3A1628) 

Before shipping (turning on by default aggregation UI), we must conduct a proper design (UI/UX) review for new functionality. 

/cc @joelkw @felixfbecker @vovakulikov @unclejustin

**Comment by vovakulikov** [comment]
From sync - our goal to start this issue is the second week of iteration 25

**Comment by Joelkw** [comment]
sync notes from @AlicjaSuska  – split this into 2, one for side panel, one for expanded view (stretch)

**Comment by AlicjaSuska** [comment]
Design QA page available [here](https://www.figma.com/file/cKSeCtmBh9aiPsAVoKsLgM/Aggregation-insights%3A-display-%22grouped%22-insights-for-existing-searches-%2339126-%5Bready-for-dev%5D?node-id=2598%3A29508) - I'm still adding things but there are already many items to adddress.
