### ISSUE TITLE
Chrome extension flashes your logo for a brief moment

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [sourcegraph/sourcegraph#4033]
- **Sourcegraph version:** Sourcegraph extension 19.4.26.1859
- **Platform information:** Chrome 74 on Mac

#### Steps to reproduce:

1. Install the Sourcegraph extension
2. Load a GitHub PR

#### Expected behavior:

Your logo not being flashed for a brief moment

#### Actual behavior:

Your logo flashes into view for a brief moment

Apologies for the .zip instead of a .gif, Github doesn't support video uploads and I didn't want to downsample to a gif. It's between seconds 7 and 8.

![image](https://user-images.githubusercontent.com/3335181/57778743-b0177000-76f2-11e9-941a-5558f06d6a63.png)

[Screen Recording 2019-05-15 at 9.16.19 AM.zip](https://github.com/sourcegraph/sourcegraph/files/3182658/Screen.Recording.2019-05-15.at.9.16.19.AM.zip)

**Comment by sqs** [comment]
This seems like a very high-priority bug

**Comment by sqs** [comment]
I think this is because the elements are injected before the stylesheet is finished loading (even though it is a local stylesheet).
