### ISSUE TITLE
Blob view: don't display flickering hover popover if there is no code intel

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#40337]
To reproduce, hover over symbols in this file https://sourcegraph.com/github.com/google/skia-buildbot/-/blob/bazel/external/google_cloud_sdk.bzl

Sometimes, the popover appears for a brief moment and then disappears again

![CleanShot 2022-08-15 at 09 27 06](https://user-images.githubusercontent.com/1408093/184593920-e75fcedd-6bbf-4981-ae22-53e990d5c4d1.gif)

I would prefer if the popover didn't appear at all, or if the popover displayed something like "no code intel" (better formulation needed) to make it obvious that we don't know what do display for this location.

**Comment by fkling** [comment]
I think this got fixed.
