### ISSUE TITLE
Perforce Change List Number Support in URLs

### ISSUE THREAD

**Issue by ryphil** [sourcegraph/sourcegraph#40330]
**Requested by:** https://github.com/sourcegraph/accounts/issues/6716, https://github.com/sourcegraph/accounts/issues/583

## Problem to solve

Perforce has the concept of [changelists](https://www.perforce.com/perforce/doc.051/manuals/p4guide/07_changelists.html), which is analogous to git commit history but not exactly the same. 

> A Perforce changelist is a list of files, their revision numbers, and operations to be performed on these files. 

Sourcegraph doesn't currently support changelists: instead, we convert everything into a git commit history. This breaks an expectation for Perforce users who use and rely on changelists. The changelist number functions the same as a git hash, but has slightly different properties. Currently, p4-fusion adds the changelist number to the commit message when we convert a Perforce change to a git commit. This preserves the mapping of git commit -> Perforce change, but is challenging for customers to query and use. 

One particular customer use case:

> They tightly integrate ChangeList Numbers with their code review process and often use ChangeList Numbers to navigate the code. They claim it would too severely interrupt their workflows by losing this number.

Another customer anecdoet:

> Because a Perforce depot is converted to a Git repo, each Changelist is converted to a Git commit. In this process, the Changelist Number is effectively lost and instead a seemingly random Git hash is created in its place. This creates problems in DR scenarios or blue-green style deployments because the Git hash will get regenerated each time. So, permalinks are no longer permanent and users who have bookmarked pages will lose those bookmarks. This happened in a recent re-deployment to a new cluster. Many users' permalinks were no longer valid because the Perforce depot's git repo was re-created.

## Measure of success

This issue will focus on adding support for Changelist Ids in Sourcegraph URLs. For example, instead of URLS in the format of `https://sourcegraph.com/CODE-HOST/DEPOT-NAME/-/commit/42a19df7824e4c23bb6013b23acc361ba3208828`, we want URLs in a format like `https://sourcegraph.com/CODE-HOST/DEPOT-NAME/change/1234`.

Permalink changes will follow with #50488.

UI changes (for example, to show wording like "changelist" instead of "commit") are covered in #46488.

## Solution summary

Will probably need a database table containing mappings from changelist id to commit hash. The alternative is to use `git log` to find the commit with the changelist id in the message, which doesn't scale at all. The table will need to be repopulated on every clone; we'll need to figure out what index to use - probably code host name + depot name or whatever is in `repositoryPathPattern`. That's what's in the current URLs.

Artifacts:
- TO DO
- [ ] populate `repo_commits` table with mappings. Do the population after clone/fetch
- [ ] set up a temporary cache in `gitserver` to use when the `repo_commits` table is not populated
- [ ] write GQL API for use by the route handler to resolve CID to SHA so that the URLs `/{repo}/-/changelist/12345` can be translated to commit SHAs
- [ ] Write route handler to display pages for `/{repo}/-/changelist/12345` URLs

/cc @ryphil

**Comment by sashaostrikov** [comment]
@jplahn @ryphil do we have anything more detaild on this except `TODO`s? 😁

**Comment by jplahn** [comment]
That's left as an exercise to the reader. 

Let me edit it with more detail

**Comment by mike-r-mclaughlin** [comment]
Additional details in [this internal doc](https://docs.google.com/document/d/1LoGORWVoAhQ4zqa6hlE8OnJ0e-mLfN0ElgzSLkkd7iE/edit#)

**Comment by peterguy** [comment]
added an estimate of 3 days to support general changelist vs commit research that applies to several issues.

Other issues that have to do with changelists:
- [ ] #46488 
- [ ] #48278 

Can we address this by using changelist ids instead of commit hashes in URLs? For example, instead of `https://k8s.sgdev.org/perforce/LifeBox@d10551f4c5b260b1271c2c48de12b46089edacc9/-/blob/README.md`, the permalink could be something like `https://k8s.sgdev.org/perforce/LifeBox@CL12345/-/blob/README.md`. That would require storing a changelist to commit hash map somewhere; could be in the `frontend` database, or in `gitserver` somewhere. The map could be built on-demand by searching commit messages for a particular pattern, or could be a backend process that indexes the commits.

**Comment by indradhanush** [comment]
This has become an epic of its own. As branch cut comes close here's a short update on where we stand. Here are the tasks in order of preference that we want to get in the next release:

[ ] **[WIP]** perforce: Perform changelist mapping for new and existing depots imported as git repos #51860 **0.5d**
	- [ ] https://github.com/sourcegraph/sourcegraph/pull/51860/
	- [ ] Done. To be merged tomorrow.
- [ ] **[WIP]** GQL API to support lookup by changelist ID **2d**
	- [ ] Draft here https://github.com/sourcegraph/sourcegraph/pull/52937 
- [ ] **[WIP]** UI to render pages under `/-/changelist/<CID>` **3d**
- [ ] Add parallelization in producer consumer pipeline **0.5d**
- [ ] Add support to re-map an existing repo on reclone / undelete **3d**
- [ ] Testing and bug fixes **3d**
- [ ] Push to mapping queue on successful code host sync **0.5d**
- [ ] - [ ] Document edge case around force pushes and why we do not handle this **0.5d**
	- [ ] P4-fusion / git-p4 does not support history rewriting

**Risks**

- On support next week
- Unknown UI work coming up ahead
- Large perforce repos after clone will remain unserviceable until changelist mapping job has completed - caching work not planned above
	- Maybe document this caveat

**Comment by peterguy** [comment]
Measure of success obtained; followup issues will address search results and others captured in https://docs.google.com/document/d/1Wd_c0dCcOD6xuwRbN_xqJn5YX9JSGfGUB01YaTsI-eE/edit
