### ISSUE TITLE
codeintel: improve usefulness of auto-indexing grafana dashboard

### ISSUE THREAD

**Issue by Strum355** [sourcegraph/sourcegraph#40342]
Today, `Code Intelligence > Autoindexing` dashboard is only a collection of low-level RED panels. This is extremely limited in usefulness for cloud engineers and on-prem customers.

Higher level panels that could be introduced:
- Index jobs queued over 5min
- MORE

Related to https://github.com/sourcegraph/sourcegraph/issues/39772

**Comment by efritz** [comment]
Can we have the important metrics from the `executor` dashboard (related to codeintel only) also shown on this dashboard? I'd like to have dashboards for services AND domains, and it's totally fine to share groups/panels between dashboards.

Things that we already seem to have (but would be good to have alerts on all):
- size of queue
- longest time in queue
- handler error rates
- scheduler/dependency indexer error rates
