### ISSUE TITLE
Adjust "spaces" when selecting a history item from search suggestions

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#40341]
When selecting an item in the search history from the search suggestions, there's two quick changes that should improve usability:

- A leading space character is currently inserted before the query. This should be removed.
- Insert a space after the query. This will make it easier to immediately start building on the same query, and will prevent a second search suggestion from being shown immediately, such as in this screenshot:

<img width="514" alt="image" src="https://user-images.githubusercontent.com/6304497/184618141-cc3e0679-bc24-4708-9acb-6c8d3c3c046f.png">

/cc @benvenker @lguychard

**Comment by camdencheek** [comment]
Closing since we now submit the search query immediately
