### ISSUE TITLE
Add "Analytics / Extensions" page

### ISSUE THREAD

**Issue by erzhtor** [sourcegraph/sourcegraph#40349]
- [Figma designs](https://www.figma.com/file/mmWwgzzqTmpLsxwmiiZwfE/Admin-analytics?node-id=1601%3A8994)

/cc @muratsu @a-bergevin

**Comment by malomarrec** [comment]
Hey @erzhtor, this issue didn't have a team label. Given you created it, I assigned you and added your team label. Feel free to unassign yourself. If this is not the right label, can you make sure to add the right one?
