### ISSUE TITLE
insights: enable search aggregations on single docker deployments

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#40368]
Currently all code insights graphql resolvers are disabled when they are run in single docker deployment mode.  

Search aggregations should be enabled in this mode.  Update the initialization of insights resolvers to enable the running of search aggregation query even if the deployment is single docker.

/cc @joelkw @felixfbecker @vovakulikov @unclejustin

**Comment by Joelkw** [comment]
@chwarwick thanks for documenting this. Marking this issue as stretch / a lower requirement for 4.0 than the other work, but keeping in the iteration for now.

**Comment by coury-clark** [comment]
@Joelkw is it safe to assume this is no longer in scope for 4.0 given the other outstanding issues? If so, can we move out of the milestone?

**Comment by Joelkw** [comment]
Sync notes: 
- is this just put the resolver in a different resolver chain? 
   - Chwarwick – yes, 
   - @coury-clark  what happens without? 
   - @chwarwick we have to put another line in 
- we return whether or not it's saveable or not
- Vova – we'll have a reason for why it's not saveable? 
- Felix – is the API merged already? Yes
- Is this a stretch issue? 
-    - what happens to single docker? 
       - will it error to the insights component on the page? 
       - it will brick the whole page? 
       - what happens on the menu item and page? page loads and is disabled
       - Felix – maybe we don't have to worry about it? 
       - If we don't tell the API we're on single docker, it fails 
 - Should we just turn this off on single docker? 
     - just as much work to put the aggregation API in the non-insight resolver chain and return the "is-saveable = false" for single docker 
     - just as much work 
   - DECISION: enable by moving the resolver chain, and just keeping saving disabled.

**Comment by leonore** [comment]
I just want to confirm the expected behaviour in writing:

Regardless of enterprise license, or code insights being enabled, we want people on single docker deployments to be able to access the aggregations API from the console, and to be able to see the aggregations UI from search (when the feature flag is enabled)?

**Comment by felixfbecker** [comment]
Correct.
