### ISSUE TITLE
Repository that ends with ".git" is not cloned

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#40372]
- **Sourcegraph version:** 3.42.0, 3.42.1
- **Reported by:** https://github.com/sourcegraph/accounts/issues/3 , https://github.com/sourcegraph/accounts/issues/7485
#### Steps to reproduce:

1. Create a new repository in Bitbucket (GitHub will not allow you to create a repo that ends with .git it seems) called `test.git`
![image](https://user-images.githubusercontent.com/23640224/184689979-4dbab242-2e03-4e8a-a4e1-8578a7d83ddc.png)

2. Add this repository to Sourcegraph

**Example**
```
{
  "url": "https://bitbucket.example.org",
  "token": "REDACTED",
  "username": "test",
  "repos": [
    "test/test.git",
    "test/test-repository"
  ]
}
```
3. Go to the Repository status page

#### Expected behavior:

Repository `test.git` is cloned and searchable

#### Actual behavior:

Repository status page shows:
![image](https://user-images.githubusercontent.com/23640224/184689632-27924cda-3569-4b5d-bc97-daeb74dccd2e.png)

`gitserver` logs show:
`
17:58:04                 gitserver | {"SeverityText":"WARN","Timestamp":1660586284538288671,"InstrumentationScope":"server.handleRepoUpdate","Caller":"server/server.go:912","Function":"github.com/sourcegraph/sourcegraph/cmd/gitserver/server.(*Server).handleRepoUpdate","Body":"error cloning repo","Resource":{"service.name":"gitserver","service.version":"3.42.1","service.instance.id":"127.0.0.1:3178"},"Attributes":{"repo":"bitbucket.example.org/test/test","error":"get VCS syncer: get repository: repo not found: name=\"bitbucket.example.org/test/test\""}}
`

/cc @jplahn @ryphil

**Comment by pjlast** [comment]
We have a bunch of places in the code that trims `.git` suffixes from repo names: https://sourcegraph.com/search?q=context%3Aglobal+r%3Asourcegraph%2Fsourcegraph+TrimSuffix+and+%22.git%22&patternType=standard&sm=1&groupBy=repo

Most of these happen in a vacuum (i.e. on `gitserver` where the request only contains the repo name) so it's hard to add a check for the original code host type. It's not obvious which of these `.git` trims are load bearing, so we're going to think about this one a bit.

**Comment by mrnugget** [comment]
Moving back to backlog because this is more than 0.5day

**Comment by mrnugget** [comment]
Calling it "won't fix" since this is a lot of (painful) work.
