### ISSUE TITLE
Add link from user in the usage stats to the user's profile

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#40374]
#### Feature request description

Add a link on the Usage statistics page `/site-admin/usage-statistics` from the username to the user's profile page.

![image](https://user-images.githubusercontent.com/23640224/184693117-1820292f-ab59-4131-872b-775079ca22df.png)

This makes it easy to get to the user's activity log quicker.

#### Additional context

**Requested by:** https://github.com/sourcegraph/accounts/issues/6716 [via Slack](https://sourcegraph.slack.com/archives/C01D50MSA7L/p1660067726560879)

**Comment by ryphil** [comment]
FYI: @rrhyne, @erzhtor and @thenamankumar - Added this to our board to capture for future iterations.

**Comment by thenamankumar** [comment]
It is there now, closing the issue.
