### ISSUE TITLE
Parameterized notebooks (similar to papermill)

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#40386]
#### Feature request description

> The use-case i've thought out most here is being able to share a notebook with our front-line support colleagues who often get localized error messages shared with them from customers.
> I want to be able to come up with specific queries, and allow other users to leverage them without parsing through the contents and modifying the parameters i expect to be static.

1. Notebook parameter (localized error message) `{param0}`
2. Run search query `file:.*labels.* {param0}`
3. Markdown to instruct user to extract info from result of query
    Results generally look something like this: `<param name="{param1}">{param0}<param>`
5. Enter extracted`{param1}`
6. Run search query `-file:.*labels.* -file:.*test.* (lang:Java or lang:JavaScript) {param1}`

From @benvenker 
![image](https://user-images.githubusercontent.com/23640224/184714678-fab7ccfd-1236-435d-9000-334e30b186eb.png)

#### Additional context

Similar to [papermill](https://pypi.org/project/papermill/) for Jupyter notebooks

**Requested by:** https://github.com/sourcegraph/accounts/issues/6716 [via Slack](https://sourcegraph.slack.com/archives/C01P4R0RZH9/p1659124081759529)

/cc @benvenker @lguychard

**Comment by marcleblanc2** [comment]
Also requested by https://github.com/sourcegraph/accounts/issues/5929
