### ISSUE TITLE
executors: alert when executors are making no progress on a non-empty queue

### ISSUE THREAD

**Issue by Strum355** [sourcegraph/sourcegraph#40409]
When queue > 0, but num handlers = 0, we want to trigger an alert indicating no forward progress is being made. The case of only failures is already handled by an existing alert, so this is just for when handlers don't seem to be starting up.

Some delay is needed to account for scale-from-zero, although this may not be necessary for cloud cc @rafax just to confirm, cloud executors are always on, not scale to zero, correct?

**Comment by rafax** [comment]
They are scale-to-zero by default - can we make this alert look at a time window larger than the cold start of VM (say, 15 minutes? 1 hour?)?

**Comment by Strum355** [comment]
> They are scale-to-zero by default - can we make this alert look at a time window larger than the cold start of VM (say, 15 minutes? 1 hour?)?

yup, thats the plan :+1: thanks for confirming
