### ISSUE TITLE
Pricing & Packaging: in-product communication [design]

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#40419]
**Description**
Design the UI updates needed to communicate P&P changes in our product. Refer to this [table](https://docs.google.com/document/d/1q1AiigPbzX1bwpSfQblGJfWTpGlwpRfxlW5GIL6ZnjY/edit#bookmark=id.tf1cgyb53jqw) for the full list of changes (UI changes required: yes).

**Comment by pjlast** [comment]
This has already been implemented for the 4.0 launch based on the Figma illustrations: https://www.figma.com/file/kr9G8tazfhVTAHpcSsKbau/Pricing-%26-Packaging-2022%3A-in-product-communication-%234419?node-id=246%3A11
