### ISSUE TITLE
Browser extension: Make sure BExt works post 4.0

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#40433]
~~This is currently blocked by whatever we do for #38317.~~

~~We need to change the browser extensions to not use Sourcegraph extensions but the new code navigations APIs that will be used for #38317.~~

Either use the new code intel APIs or load only the code intel extension for instances post 4.0

/cc @muratsu @jjinnii @ryankscott

**Comment by taras-yemets** [comment]
The Sourcegraph browser extension works as expected and respects the `enableLegacyExtensions` site config parameter (checked on https://github.com/sourcegraph/sourcegraph/commit/b53e219b56ed9edef74bd012e3e4db7a0c0dea27 revision):
- code-intel features work regardless of the `enableLegacyExtensions` value
- code-intel extensions bundles come from:
  - the browser extension bundle if `enableLegacyExtensions` is `false`
  - extensions registry  if `enableLegacyExtensions` is `true`
- if `enableLegacyExtensions` is `true` the browser extension also loads other than code-intel extensions if enabled.
