### ISSUE TITLE
JetBrains: 'Search on Sourcegraph' doesn't open browser on Fedora/Chrome

### ISSUE THREAD

**Issue by gabtorre** [sourcegraph/sourcegraph#40452]
- **Sourcegraph version:** 
- **Platform information:** 
Fedora 36
IntelliJ IDEA 2022.2
Plugin version: 2.0.0 

#### Steps to reproduce:

1. Open file in IntelliJ IDEA with Sourcegraph plugin
2. Click 'Search selection on Sourcegraph Web,' 'Search Selection in Repository on Sourcegraph Web,' or 'Open selection in Sourcegraph Web.'

#### Actual behavior: The browser doesn't open until IntelliJ IDEA is closed.

https://user-images.githubusercontent.com/69164745/185008530-a7d58c97-5ae1-401f-bc04-8c578ba45875.mov

If would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are not [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

/cc @muratsu @jjinnii @ryankscott

**Comment by vdavid** [comment]
Do we have the logs that run in the background, or the IDEA log export? (One can export the IDE logs through `Help | Collect Logs and Diagnostic Data…`).

Our implementation covers two scenarios:
1. The environment has a default browser open and we have access to it. → In this case we open the browser.
2. Else: we display a standard IDE notification at the bottom right saying “Hey, we can’t open your browser, but here is a link, click here to copy it, then paste it in your browser”

but in this case, neither of these happen. So I’m very curious about this setup and what goes wrong. The logs would help.

**Comment by gabtorre** [comment]
Thanks, @vdavid, here is the log file after trying the actions in 'steps to reproduce.'
[idea.log](https://github.com/sourcegraph/sourcegraph/files/9376832/idea.log)

**Comment by vdavid** [comment]
This is the relevant part of the log:

```
INFO - #c.s.g.GitUtil - Cannot run program "git" (in directory ""): error=2, No such file or directory
java.io.IOException: Cannot run program "git" (in directory ""): error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at java.base/java.lang.Runtime.exec(Runtime.java:594)
	at java.base/java.lang.Runtime.exec(Runtime.java:418)
	at com.sourcegraph.git.GitUtil.exec(GitUtil.java:109)
	at com.sourcegraph.git.GitUtil.getCurrentBranchName(GitUtil.java:93)
	at com.sourcegraph.git.GitUtil.getRepoInfo(GitUtil.java:30)
	at com.sourcegraph.website.SearchActionBase.actionPerformedMode(SearchActionBase.java:46)
	at com.sourcegraph.website.SearchSelectionAction.actionPerformed(SearchSelectionAction.java:9)
```

So the problem is apparently that the `git` command is not configured. This is a dependency that is not documented, but it _should_ be documented. I've created an issue to track this: https://github.com/sourcegraph/sourcegraph/issues/40613

Not sure if we should also mention that the plugin doesn't currently support Perforce, SVN, etc.

@gabtorre Could you work with the client to make sure that they have the `git` command working?
The `in directory ""` part is also weird, and I see a chance that the `git` command is set up correctly and something else is the matter.
But first I'd check the `git` command.

**Comment by gabtorre** [comment]
Hey @vdavid,

I installed git and the errors went away but the plugin still doesn't open the window.


Here are some new logs. [idea.log](https://github.com/sourcegraph/sourcegraph/files/9446778/idea.log)

It seems like changing the [following line](https://github.com/sourcegraph/sourcegraph-jetbrains/blob/main/src/main/java/com/sourcegraph/action/SearchActionBase.java#L71) to use the the Intellij [BrowserUItil](https://github.com/JetBrains/intellij-community/blob/master/platform/platform-api/src/com/intellij/ide/BrowserUtil.java#L68) API for opening the browser instead of the java.awt.Desktop API, opens the browser window as expected. It seems like java.awt.Desktop is not working well on Fedora 36.

**Comment by rakeshjosh2003** [comment]
Hi,

As discussed in the integration channel, posting the issue here for Salesforce. Salesforce is also facing the same issue, they are using the below setup 

Ubuntu 20.04.4 LTS and macOS
IntelliJ 2021.3.3
Sourcegraph IntelliJ plugin 2.0.0
Chrome 104.0.5112.101 (64-bit)
Intel CPU


```
2022-08-25 08:48:42,684 [ 681578]  INFO -  #com.sourcegraph.git.GitUtil - Cannot run program "git" (in directory ""): error=2, No such file or directory 
java.io.IOException: Cannot run program "git" (in directory ""): error=2, No such file or directory
```

They confirmed git is installed properly, I suspect they are using the perforce project hence facing this issue.

**Comment by rakeshjosh2003** [comment]
[openSelectionInSourcegraphWeb.log](https://github.com/sourcegraph/sourcegraph/files/9448456/openSelectionInSourcegraphWeb.log)

**Comment by vdavid** [comment]
@gabtorre thanks for the tip on BrowserUtil. It's great news that it works well under Fedora. I'm checking out this option now, hoping to solve the browser opening problem with a quick fix.

**Comment by brisssou** [comment]
I'm facing the same `Cannot run program "git" (in directory "")` error.
Maybe something more specific here: I'm using WSL. So `git` is the WSL one (which is properly detected by the IDE).
