### ISSUE TITLE
prod: repo-updater: insert: pq: duplicate key value violates unique constraint "repo_external_service_unique_idx"

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#4046]
on Sourcegraph.com we are seeing jump-to-code-host links not appearing. This is due to a query to repo-updater to lookup the repository failing: 

https://sourcegraph.com/github.com/sourcegraph/sourcegraph@ee5cad06b25a2805cfc0d83f703dac6e9e6078d0/-/blob/cmd/frontend/graphqlbackend/externallink/repository.go#L121-131

(There is a separate issue to make the frontend actually report this error instead of silently not display the link, https://github.com/sourcegraph/sourcegraph/issues/3589)

This is occurring because the repo lookup request to repo-updater is violating a constraint:

![image](https://user-images.githubusercontent.com/3173176/57810431-9b4fd200-771c-11e9-9d11-ba45c62fb5dc.png)

Trace link: https://app.lightstep.com/sourcegraph-prod/trace?span_guid=23bdf059c3177301&at_micros=1557954611403681#span-29b170085880e1f0

To reproduce this simply visit any repository on Sourcegraph.com and look for the `GraphQL?Repository` query's `x-trace` header, which will be a Lightstep link.

**Comment by keegancsmith** [comment]
This is fixed. However, I can't confirm due to us using a pinned commit in prod until https://github.com/sourcegraph/sourcegraph/issues/4057 is resolved.
