### ISSUE TITLE
Tracking: Speed up startup of executors run

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#40477]
## Problem

Executor runs are slow to start, which is degrading the experience of running batch changes server-side: for some small workloads, users get slower results than locally

**Comment by malomarrec** [comment]
Backlog?

**Comment by eseliger** [comment]
yeah, I'll pick it up as time allows and other blocking progress allows to work on this.

**Comment by eseliger** [comment]
Some progress, we don't need to copy workspaces into the VM anymore.

**Comment by eseliger** [comment]
Next one: https://github.com/sourcegraph/sourcegraph/issues/42477
