### ISSUE TITLE
Search UI: Decouple logic in `<SearchFilterSection />` component

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#40481]
Follow-up for https://github.com/sourcegraph/sourcegraph/pull/40381

## Background 
In https://github.com/sourcegraph/sourcegraph/pull/40381 we decoupled the search bar panel and search filters section components. This allows reuse in different places without knowing a lot about their implementation. But `FilterSection` UI still has a lot of complexity, and it's hard to maintain. 

This issue implies rewriting this component in a way where we would have a list of small and easy-to-maintain components for building another search UI filter section. 

/cc @benvenker @lguychard

**Comment by fkling** [comment]
This can probably be closed as well, since no longer relevant?
