### ISSUE TITLE
CodeMirror blob: Popover font differences

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#40485]
#### Expected behavior:
<img width="564" alt="Screen Shot 2022-08-17 at 11 36 56 PM" src="https://user-images.githubusercontent.com/87138876/185164403-b0a0bb9c-66f7-4511-a8a6-1ad35ad7fe3b.png">

#### Actual behavior:
<img width="585" alt="Screen Shot 2022-08-17 at 11 36 45 PM" src="https://user-images.githubusercontent.com/87138876/185164447-3e5b2511-a805-43b3-9e58-3282c10dce43.png">

Different font weight (maybe size) being used for the popover buttons, as well as different font weight for the "precise" and "search-based" tags.

**Comment by macraig** [comment]
Adding feedback from @felixfbecker in [this slack thread](https://sourcegraph.slack.com/archives/C03CSAER9LK/p1660770782433899):

> The font of the hover tooltip buttons seems very hard to read and inconsistent with other WCL buttons (it's font size 11px and has negative letter spacing)

<img width="868" alt="image" src="https://user-images.githubusercontent.com/1657213/185382719-bc737bde-d2a6-4c18-abd9-caf6c1b589f5.png">
