### ISSUE TITLE
CodeMirror Blob: Preview pane should have syntax highlighting

### ISSUE THREAD

**Issue by scalabilitysolved** [sourcegraph/sourcegraph#40510]
### Problem

The preview pane has no syntax highlighting after selecting a result in the reference panel: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/search/query/parser.go?L23:6#tab=implementations_go 

![Image](https://user-images.githubusercontent.com/1309599/185229696-3e2551b4-8268-430b-90ef-2caefbd3f47d.png)

**Comment by jjinnii** [comment]
@olafurpg The Preview pane has the same visual inconsistencies in font that have already been documented in other issues. Let me know how you'd prefer to track the work required to make sure the preview pane has consistency with the file blob as well! (I wasn't sure if updating the fonts would automatically reflect in Preview pane as well)

**Comment by olafurpg** [comment]
@jjinnii let's create a separate issue for the inconsistent font in the preview pane. I just opened a PR https://github.com/sourcegraph/sourcegraph/pull/40567 to fix the syntax highlighting inconsistency that should close this issue here

**Comment by jjinnii** [comment]
@olafurpg Created issue #40597 !
