### ISSUE TITLE
Error when adding GitHub external service

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#4052]
![image](https://user-images.githubusercontent.com/10532611/57816322-bd9f1b00-772f-11e9-8390-ffa7f0548755.png)

```
Error saving invalid configuration:

warning: external service created, but sync request failed: syncer.sync.sourced: 1 error occurred:
* failed to list GitHub repositories for search: page='\x02', searchString="org:sourcegraph",: github repository search returned incomplete results. This is an ephemeral error: query="org:sourcegraph" page=2 total=272
```

This is the commented-out example query.

I also think the "Error saving invalid configuration" is weird. If you knew it was invalid, why did you try to save it instead of telling me what is invalid?

**Comment by mrnugget** [comment]
The error comes from Github's API and we can't predict whether it gets returned or not before we try to do a sync:

> To keep the Search API fast for everyone, we limit how long any individual query can run. For queries that exceed the time limit, the API returns the matches that were already found prior to the timeout, and the response has the `incomplete_results` property set to true.
https://developer.github.com/v3/search/#timeouts-and-incomplete-results

We have a test case that even makes sure that this error aborts the syncer: https://github.com/sourcegraph/sourcegraph/blob/b6b985b38dba79b4d08932ada718fd19e8cc30b5/pkg/extsvc/github/repos_test.go#L298-L333

To quote the comment in the test case:

```go
	// If we have incomplete results we want to fail. Our syncer requires all
	// repositories to be returned, otherwise it will delete the missing
	// repositories.
```

I guess we can improve the error message?

**Comment by felixfbecker** [comment]
@mrnugget as a user, that doesn't help me - what am I supposed to do when this error occurs? How can I resolve it? I am currently blocked on testing because I can't get repositories to sync to my instance.

So there are two problems here:
- I am unable to set up my instance to sync all repositories from the Sourcegraph org with this repositoryQuery
- I am getting an error that is confusing and unhelpful

**Comment by slimsag** [comment]
Probably not a regression from 3.3, but bad behavior nonetheless

**Comment by beyang** [comment]
This does not block testing and is likely not a regression, so removing `release-blocker` and moving into the 3.4-c milestone now.

**Comment by mrnugget** [comment]
@felixfbecker I agree. The message tells you, the user, nothing you can or should be able to understand. I think we need to improve it by making clear what the error means and signifies (Github decided the search takes too long) and we could even offer suggestions: "try reduce the scope of the search" or "try again" (which helps surprisingly often — I, for example, could not reproduce your error with the exact same configuration)

**Comment by keegancsmith** [comment]
Actually in this case this is an ephemeral error, not the other issue you mention. GitHub's search API occasionally fails with this explicitly marked ephemeral error. In the case of our usual sync this is fine, we just try again. However, in the case of an admin saving an external service configuration we should retry.

**Comment by mrnugget** [comment]
> Actually in this case this is an ephemeral error, not the other issue you mention. GitHub's search API occasionally fails with this explicitly marked ephemeral error.

What do you mean with "the other issue"? Because I saw this as an ephemeral error too :) GitHub's official docs even describe it as such (even though they don't use the word ephemeral): https://developer.github.com/v3/search/#timeouts-and-incomplete-results and https://developer.github.com/changes/2014-04-07-understanding-search-results-and-potential-timeouts/
