### ISSUE TITLE
CodeMirror Blob: Improve design consistency of Cmd + F 

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#40542]
When users have the file view in focus, we override the browser `cmd + f` with CodeMirror's own search. This needs to be updated for visual consistency with the rest of the problem. Additionally, some thinking is required on how to communicate this change in browser-core behavior. 

<img width="1132" alt="Screen Shot 2022-08-18 at 4 02 30 PM" src="https://user-images.githubusercontent.com/87138876/185326279-8034e913-f26a-42ef-8f03-07617ebc417c.png">

**Comment by jjinnii** [comment]
FYI the [designs](https://www.figma.com/file/xZ7os2VODDE3rNe4uFRDFu/CodeMirror-UI-Imrovements?node-id=2%3A6463) are ready, but I'll be sharing in design sync today to get a pulse from the other designers how impactful we think this change is and whether a notification/onboarding will be required once we enable CodeMirror as GA. 

cc: @olafurpg @macraig

**Comment by fkling** [comment]
@jjinnii Do you remember if there have been any results from that meeting that are relevant here? Or should I just implement it as shown in Figma?

**Comment by jjinnii** [comment]
## Design process

  - Estimate: One day to a week
  - Weighting factors: Medium risk Medium certainty

  ### Discover
  - [ ] Existing customer feedback - Link
  - [ ] Product and/or engineering provide direction and/or feedback

  ### Define
  - [x] Github issue
  - [ ] Design challenge

  ### Design
  - [x] Wireframes - Link
  - [ ] High fidelity design using design system - Figma
  - [ ] Non-visual design guidance captured in the issue
  - [ ] Prototype - Link
  - [ ] Designer review

  ### Testing
  - [ ] Hallway testing - Link
  - [ ] Usertesting.com task based evaluation - Link

  ### Deliver
  - [ ] Loom - Link
  - [ ] Team review
  - [ ] Design team review
  - [ ] QA - Link

  ### Measure
  - [ ] Metrics defined in the Figma file ([i](https://handbook.sourcegraph.com/departments/product-engineering/product/design/metrics/defining-metrics/)) - Link
  - [ ] Followup task will analyze metrics to ensure successful completion - Link

**Comment by jjinnii** [comment]
@fkling The designs can be implemented as shown in Figma as it's just implementing the same CodeMirror search bar with Wildcard components. However, now that we have more time to address CodeMirror issues, I'd like to re-visit related issue #40724 which touches on the _behavior_ of the Cmd + F. There is guidance provided in the issue, but I think it was a solution we quickly landed on when trying to ship CodeMirror for 4.0 that could use some additional validation/testing with a larger group.

Feel free to work on the UI and close this issue, and I'll re-visit #40724! 
FYI: @olafurpg
