### ISSUE TITLE
Reference Panel: Mix precise and search-based results shouldn't be wrapped

### ISSUE THREAD

**Issue by macraig** [sourcegraph/sourcegraph#40554]
Feedback on ref panel from @felixfbecker 

> Would expect this to not be wrapped (as it means there is no padding to the borders, and there is enough horizontal space)

![Image](https://user-images.githubusercontent.com/1657213/185383523-46c0064e-bdd3-487a-9ead-1c088b5ba1aa.png)

**Comment by mrnugget** [comment]
I think @oleggromov fixed this. It's already live on sourcegraph.com but not sourcegraph.sourcegraph.com yet.
