### ISSUE TITLE
CodeMirror Blob: Syntax highlighting color is the same for almost all tokens

### ISSUE THREAD

**Issue by macraig** [sourcegraph/sourcegraph#40551]
### Problem

The syntax highlighting in the new blob view for almost all tokens seems to be blue. [Example file](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/cmd/progress-bot/main.go)

Old blob view:
![CleanShot 2022-08-18 at 12 15 10](https://user-images.githubusercontent.com/1657213/185382087-435c8550-4492-44ae-8de9-16916e097388.png)

New blob view:

![Image](https://user-images.githubusercontent.com/1657213/185381688-78d0904d-680d-45a7-8354-5aaad7046f6e.png)

**Comment by olafurpg** [comment]
Pending PR that improves the situation significantly for Go and TypeScript, should land sometime early next week

**Comment by olafurpg** [comment]
Closing this as fixed because the new CM blob should have significantly improved highlighting now for most common languages we use at Sourcegraph. There's still a difference from the old blob and those can be addressed with separate smaller issues for concrete languages or bugs.
