### ISSUE TITLE
Cannot use Google GSuite OIDC auth 

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#4056]
- **Sourcegraph version:** Docker image 3.4.0-rc.2
- **Platform information:** 

#### Steps to reproduce:

1. Spin up a Sourcegraph cluster following the docs on deploying to Google Cloud VM following https://docs.sourcegraph.com/admin/install/docker/google_cloud.
2. Set an external URL for your instance
3. Access the management console and set up Google OIDC auth following https://docs.sourcegraph.com/admin/auth#g-suite-google-accounts
4. Go back to your instance, and sign out. You'll see this error page
![image](https://user-images.githubusercontent.com/16265452/57819755-a156aa80-773e-11e9-8599-3a517aee7277.png)

5. Following the URL takes you back to your OAuth credential, and see that it had the correct redirect URL:
![image](https://user-images.githubusercontent.com/16265452/57819694-68b6d100-773e-11e9-8fff-db8bf301b55d.png)

#### Expected behavior:

- Can log out properly.

#### Actual behavior:

- Failed log out.

**Comment by beyang** [comment]
This is also an issue in 3.3, so not a regression, but still a P1 issue.

**Comment by beyang** [comment]
@sourcegraph/core-services this might be a good starter auth issue.

**Comment by tsenart** [comment]
I'm on this one.
