### ISSUE TITLE
Sourcegraph.com saved searches page never loads: QueryContext(2): pq: syntax error at or near ")"

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#4058]
- **Sourcegraph version:** Sourcegraph.com

![image](https://user-images.githubusercontent.com/5589410/57825338-43808d80-7753-11e9-8743-92a9b00c3da3.png)

#### Steps to reproduce:

1. Visit https://sourcegraph.com/search/searches
2. Open console to see:

```
AggregateError: QueryContext(2): pq: syntax error at or near ")"
```

(This might not be a release blocker if it only affects dotcom.)

**Comment by attfarhan** [comment]
Hmm I don't know why this is occurring, but Sourcegraph.com should be upgraded to latest master soon, which includes my new UI for saved searches and would solve this issue. 

I keep seeing this in the site admin area though:
![image](https://user-images.githubusercontent.com/16265452/57825751-23ea6480-7755-11e9-8fbc-840c0fbbfc0a.png)

I'm getting on my flight @dadlerj could you check with other teammates maybe why Sourcegraph.com is not updating?

**Comment by dadlerj** [comment]
Yeah I also filed that issue at https://github.com/sourcegraph/sourcegraph/issues/4057 and posted about it in Slack. Not sure if it's related 🤷‍♂

**Comment by dadlerj** [comment]
Safe flight!

**Comment by slimsag** [comment]
Looks like a major regression potentially. Note this doesn't happen on sourcegraph.com currently due to me reverting it back to a commit ~5d old.

**Comment by attfarhan** [comment]
@slimsag did you do any additional digging here? Were you able to repro on a release candidate and are therefore calling it a major regression? If we fix the JS bundles issue, this saved searches page will no longer exist on Sourcegraph.com, since Sourcegraph.com will be deployed with the new UI, but want to confirm this isn't a problem on the latest release -- I haven't been able to repro it myself on release candidates.

**Comment by beyang** [comment]
I'm unable to repro this, as well, @dadlerj does it still repro for you?

**Comment by dadlerj** [comment]
No — I never saw it locally, and I don't see it on dotcom anymore (though maybe because it got rolled back)

**Comment by slimsag** [comment]
Havent done any digging or reproduced, but it looks like an SQL syntax error. It is possible that whatever is causing the bundle issue was also causing this, maybe two old front-end versions at once? cc @sqs

**Comment by sqs** [comment]
@slimsag I actually don't think the other issue implied that there were 2 conflicting version frontends running at once; see https://github.com/sourcegraph/sourcegraph/issues/4057#issuecomment-493343987 2nd and 3rd bullet points for why.

---

This line looks suspect: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@392986c01d02c790a75713a5157eded48fa6c0de/-/blob/cmd/frontend/db/saved_searches.go#L158.

If there are 2 items in the `orgConditions` slice (eg `org_id=456` and `org_id=789`), isn't the query going to look like:

```
SELECT id, etc FROM saved_searches
WHERE user_id=123 OR org_id=456 ) OR (org_id=789
```

I think you need to change the joiner string to ` OR ` not ` ) OR (`, or remove the parens around `%v` like `sqlf.Sprintf("%v or (%v)", ...`.

I don't see a test for this function :smile:

**Comment by attfarhan** [comment]
Ahhh yes this could be it. Thanks, I will push up a fix.
