### ISSUE TITLE
Improved user management for customers with large number of users

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#40586]
**Requested by:** https://github.com/sourcegraph/accounts/issues/6716

#### Feature request description

- Add pagination to the User Management  page in site admin (`/site-admin/users`).  
- Show the date joined, and the date last used
- Allow multi-selection of users for bulk actions
    - Action for deleting users

#### Is your feature request related to a problem? If so, please describe.

When customers have large numbers of users (100s or 1000s), it's very difficult to manage those users in the current view.  Pagination would help (i.e., not just "show more" but having pages).  

Pagination will help with scripts that customers write using APIs as well.  Currently, the only API available is `query users` and that API requires you to make one API call to get all users (i.e., there is a `first` parameter that allows you to get the "first x users";  but, there is no way to know if there are more users after that).

**Comment by rrhyne** [comment]
@mike-r-mclaughlin can you confirm the new user management screen solves the majority of the issues listed here?

**Comment by mrnugget** [comment]
Ping on this, since this ticket is in the strategic customers roadmap :)

**Comment by mike-r-mclaughlin** [comment]
thanks @mrnugget and @rrhyne .  i'm just waiting for the latest version to get through the security reviews at https://github.com/sourcegraph/accounts/issues/6716 to get their direct feedback.  From my own review, it solves everything but pagination.  I honestly have forgotten why that was important to them so it may not be that big of a deal.

**Comment by rrhyne** [comment]
Thanks Mike. There is some light pagination in the new user admin, but we're very interested in how it scales out to many many users from a perf and UX standpoint. 

If you have a meeting in this regard, could you include either me or @AlicjaSuska on it?

**Comment by ryphil** [comment]
@thenamankumar - Can we close this based on your recent pagination work?

**Comment by thenamankumar** [comment]
This issue is pre user management revamp. Pagination and all other suggestions, including date joined, last active, and bulk actions exist now.

Closing the issue.
