### ISSUE TITLE
CodeMirror Blob: UI parity in the reference panel Preview

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#40597]
#### Expected behavior:
The Preview panel in the reference panel has the same UI consistencies as documented in issues #40484 #40486. As a general rule, any UI improvements we make in the file blob view to reach visual parity with the current file view should be reflected in the reference panel Preview. 

#### Actual behavior:

<img width="1435" alt="Screen Shot 2022-08-19 at 6 29 13 PM" src="https://user-images.githubusercontent.com/87138876/185589462-ca87ae75-6b69-4945-986f-1887e8804bf1.png">

**Comment by olafurpg** [comment]
@jjinnii Can you elaborate on what changes are needed to close this P1 issue?

**Comment by jjinnii** [comment]
@olafurpg Sure! This issue just documents that the UI inconsistencies in the CodeMirror file blob (font, typography, etc.) is also reflected in the reference panel. There likely isn't additional engineering work required to have any changes reflected in both ref panel and file blob. If this is the case, feel free to close out after issues #40484 and #40486 are addressed!

**Comment by fkling** [comment]
https://github.com/sourcegraph/sourcegraph/issues/40484 and https://github.com/sourcegraph/sourcegraph/issues/40486 have been closed!
