### ISSUE TITLE
Search: `lang:xml` returns `*.d.ts` files

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#40595]
The query `lang:xml` currently returns TypeScript definition files https://sourcegraph.com/search?q=context:global+lang:xml&patternType=lucky

![CleanShot 2022-08-19 at 10 31 33](https://user-images.githubusercontent.com/1408093/185578641-6779030b-a4ae-479a-83d4-510b9aed7fcc.png)

I expected the query to only return files matching the pattern `.*\.xml$`

/cc @sourcegraph/search-core

**Comment by keegancsmith** [comment]
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/7841
