### ISSUE TITLE
JetBrains: Document dependency on the "git" command

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#40613]
The `git` command dependency not being documented caused a problem with a client here: https://github.com/sourcegraph/sourcegraph/issues/40452

We should mention this dependency in the plugin's [README.md](https://github.com/sourcegraph/sourcegraph/tree/main/client/jetbrains), plus the [plugin page](https://plugins.jetbrains.com/plugin/9682-sourcegraph) in the JetBrains Marketplace.

/cc @muratsu @jjinnii @ryankscott

**Comment by ryankscott** [comment]
@vdavid Why do we have a dependency on git?

**Comment by vdavid** [comment]
@ryankscott We use it for four things, all for the URL sharing features:
1. To get the **remote URL of a repo** for a file
2. To get the **root path of the repo** for a file
3. To get to current **branch name** for a fille
4. To check **if a a remote branch exists**—to avoid copying links to non-existing URLs
