### ISSUE TITLE
Saved searches forms are missing Slack webhook option

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#4061]
- **Sourcegraph version:** 3.4-rc.3
- **Platform information:** Kubernetes/Docker

#### Steps to reproduce:

1. Enter a search query, click on `Save this search query`

or

1. Go to `/search/searches`, click on `Add new search`

#### Expected behavior:

I can enable "Slack notifications" [as described in the documentation here](https://docs.sourcegraph.com/user/search/saved_searches#configuring-email-and-slack-notifications)

#### Actual behavior:

I don't see an option to enable Slack notifications

<img width="875" alt="Screen Shot 2019-05-16 at 15 34 44" src="https://user-images.githubusercontent.com/1185253/57857851-41204100-77f0-11e9-8d9d-d02888554abf.png">

or

<img width="1032" alt="Screen Shot 2019-05-16 at 15 36 16" src="https://user-images.githubusercontent.com/1185253/57857918-62812d00-77f0-11e9-8508-d2a97762cfc6.png">

---

It looks like everything relating to Slack was removed from the saved search UI in #4015 (https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/ea219ab65b03da026e44c80bda05a05e3a6f7b94)

**Comment by mrnugget** [comment]
I just noticed that #4015 wasn't cherry-picked into 3.4: https://github.com/sourcegraph/sourcegraph/commits/3.4

The instances I tested this on were using `3.4-rc.3`

**Comment by attfarhan** [comment]
This is intentional, we are deprecating slack webhook URL support for saved searches. Unfortunately the new UI did not make the release candidate so that is also expected.

**Comment by attfarhan** [comment]
I will file a separate issue to remove the docs.

**Comment by slimsag** [comment]
I am reopening this just to double-check and re-confirm: no customers are relying on this and product (@sqs @dadlerj 
 @christinaforney) are okay with Slack support here being removed in 3.4?

**Comment by slimsag** [comment]
Ah, based on what you've said in #4701 it sounds like we removed some specific form of Slack integration in favor of a different way of doing it, is that right?

**Comment by attfarhan** [comment]
Existing saved searches that have slack webhook URLs associated with them will continue to have Slack notifications appear. What was removed is the ability to create a _new_ saved search with Slack notifications

**Comment by attfarhan** [comment]
And yes, we plan to allow users to specify arbitrary webhooks to receive notifications in the next release.

**Comment by slimsag** [comment]
Makes sense, thanks for clarifying. Last thing here is I just want to make sure this was previously discussed as being okay for our biggest saved searches user (https://app.hubspot.com/contacts/2762526/company/419771425 if I remember correctly)?

**Comment by attfarhan** [comment]
Yup, turns out they were not using Slack notifications at all.

**Comment by slimsag** [comment]
Ah okay, great, thanks for the details here!
