### ISSUE TITLE
"Create batch change" is still visible on search result page even when batch changes is disabled

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#40612]
- **Sourcegraph version:** 3.42.0
- **Reported by:** https://github.com/sourcegraph/accounts/issues/3

#### Steps to reproduce:

1. Go to Site Admin > Site Configuration
2. Set the property `"batchChanges.enabled": false`
3. Open sourcegraph web page and perform a search

#### Expected behavior:

The "Create Batch Change" button is not visible on the search results page.

#### Actual behavior:

The "Create Batch Change" button is visible on the search results page even though batch changes is disabled.

![image](https://user-images.githubusercontent.com/23640224/185639963-4c074a15-6d29-4210-ac88-cf6181367b9e.png)

If would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are not [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

**Comment by chrispine** [comment]
P0 quick fix?
