### ISSUE TITLE
"Not cloned" repositories page times out if there are a lot of repositories and none are cloned

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#4063]
Repro:
* Go to https://k8s.sgdev.org/site-admin/repositories?filter=not-cloned
* Wait
* Observe 504 error after awhile

![image](https://user-images.githubusercontent.com/1646931/57874346-369c8200-77c5-11e9-98bc-bd80835b8c6e.png)

**Comment by slimsag** [comment]
Fixed by #4279
