### ISSUE TITLE
topQueries wrongly includes partial queries

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#4067]
A query is logged every time a search occurs, filling the top query collection with unfinished searches.

New logic needs to be introduced so a search is only logged when the user initiates it, such as hitting *Enter*, pressing the *Search* button.

![ScreenFlow](https://user-images.githubusercontent.com/133014/57881850-28eff800-77d7-11e9-9935-3573bb51dd0d.gif)

I would like to see this pulled from 3.4 until it is fixed.

**Comment by beyang** [comment]
Can be fixed by reverting 5b744fb132e4d4cfb6381914325dcc442d6537ba

**Comment by slimsag** [comment]
I don't think this is a release blocker. At worst, it means the data we gather from  `topQueries` would be useless, correct? Or could this harm performance?

**Comment by ryan-blunden** [comment]
It's not a release blocker, but I would prefer to revert it, or, if that's not possible, remove the entry from the CHANGELOG (so it's essentially invisible) until we fix the data collection code.

**Comment by beyang** [comment]
Reassigned to @ijt to fix in 3.5. Will also remove the CHANGELOG entry.

**Comment by ijt** [comment]
I'm on vacation with limited internet access. Feel free to revert if
necessary. I can put in something better after I'm back on Monday.

**Comment by beyang** [comment]
No need to revert, just fix in 3.5
