### ISSUE TITLE
Feature request: exclude files in `search.largeFiles`

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#40688]
Feature requested by https://github.com/sourcegraph/accounts/issues/8205

#### Feature request description

The site config setting `search.largeFiles` should allow file exclusions so that known large files can be excluded from the index.

The customer has several thousand repos all with a very large file called `.gitmodules` (over 50,000 lines). They would like to exclude only this file and allow indexing other files. 

#### Is your feature request related to a problem? If so, please describe.

This would be a workaround to address #40686

#### Describe alternatives you've considered.

- Using `.sourcegraph/ignore` is not feasible because the customer has several thousand repos they would need to create this file for.
- Fix #40686 or #40687

#### Additional context

/cc @sourcegraph/search-core

**Comment by limitedmage** [comment]
cc @tbliu98 who is working on a similar solution for another customer

**Comment by gl-srgr** [comment]
This has been merged and the changelog entry is under the Added section (will be in 4.3) https://github.com/sourcegraph/sourcegraph/blob/main/CHANGELOG.md#added
