### ISSUE TITLE
Same user cannot load another tab of Sourcegraph if the first tab has lots of pending GraphQL calls

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#40687]
- **Sourcegraph version:** 3.41
- **Platform information:** N/A

Issue reported by https://github.com/sourcegraph/accounts/issues/8205

#### Steps to reproduce:

1. Create a search that will have lots of pending GraphQL calls (for example, due to #40686)
2. While the search results load, open a new tab in the same browser and go to Sourcegraph

#### Expected behavior:

New tab loads Sourcegraph

#### Actual behavior:

Sourcegraph doesn't load, network tab shows that GraphQL calls are pending to load the page and won't complete until those in the first tab completes.

Opening a new tab in incognito mode does work.

/cc @sourcegraph/search-core

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket, please let us know how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
