### ISSUE TITLE
insights: [spike] scope work required to enable search aggregations on sourcegraph.com

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#40684]
Determine what work needs to be done and create issues for the work that would need to be completed to enable search aggregations to run on sourcegraph.com 

Non exhaustive list of items to answer: 

- Does sourcegraph.com have access to insights apis? If not does the work in https://github.com/sourcegraph/sourcegraph/issues/40368 resolve this?
- Will any of the search aggregation `count:all` queries complete in the allocated time?
- Any additional resource constrain issues/concerns?

/cc @joelkw @felixfbecker @vovakulikov @unclejustin

**Comment by leonore** [comment]
Seems like the work on the single-docker issue has addressed enabling this on dotcom. 

Here's how I tested it:
1. Added `search-aggregation-filters` (**set to false** by default)
2. Added an override for my user ID
To find your user ID you can run a gql query and [decode the result](https://www.base64decode.org/)
```gql
query user {
  user(username:"leonore") {
    id
  } 
}
```
3. Did a good old search

it doesn't look like aggregation queries complete unless a single repo is specified, but it does work well for single repos. will have to test with explicit aggregation requests

**Comment by leonore** [comment]
closing as we've disabled this by default on dotcom but it's enablable
