### ISSUE TITLE
insights: disable search aggregations on sourcegraph.com

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#40683]
Code Insights search aggregations should be fully disabled (not present in the sidebar and not submitting any api requests) by default on sourcegraph.com 

Another issue will scope the work required to enable aggregations on sourcegraph.com .

/cc @joelkw @felixfbecker @vovakulikov @unclejustin

**Comment by chwarwick** [comment]
Issue to determine scope of changes needed to support aggregations on .com https://github.com/sourcegraph/sourcegraph/issues/40684

**Comment by unclejustin** [comment]
Related issue https://github.com/sourcegraph/sourcegraph/issues/40427

This issue may be handled in the above issue. Close if appropriate.

**Comment by vovakulikov** [comment]
It seems that this issue was covered by https://github.com/sourcegraph/sourcegraph/issues/40088

We just need to set the global admin feature flag to false on sourcegraph.com.
