### ISSUE TITLE
RFE: Configurable timeouts for repository administration pages

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#40697]
**Requested by:** https://github.com/sourcegraph/accounts/issues/6716 via [Slack](https://sourcegraph.slack.com/archives/C01D50MSA7L/p1629700563270300)

#### Feature request description

Allow administrators to configure the timeouts for administrative pages like the repository status.

#### Is your feature request related to a problem? If so, please describe.

![image](https://user-images.githubusercontent.com/23640224/186016525-e81f901b-14f1-404d-bdab-dc5978bb767f.png)

**Comment by mike-r-mclaughlin** [comment]
@mrnugget that all makes sense to me.   This was a very common occurrence for https://github.com/sourcegraph/accounts/issues/6716 and frustrating user experience.  if these errors are much less likely to occur now, then it makes sense to me to close this.

**Comment by mrnugget** [comment]
Understood, thanks! Let's reopen if it happens again.
