### ISSUE TITLE
RFE: Index GitHub Gists

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#40695]
**Requested by:** https://github.com/sourcegraph/accounts/issues/6716 via [Slack](https://sourcegraph.slack.com/archives/C01D50MSA7L/p1634787978003300)
#### Feature request description

Index and allow users to search GitHub [gists](https://docs.github.com/en/rest/gists).

#### Additional context

[Internal Product Gap](https://sourcegraph2020.lightning.force.com/lightning/r/Product_Gap__c/a1B5b00000K4TUYEA3/view)

**Comment by mrnugget** [comment]
Closing this since it doesn't seem relevant right now. Can reopen later.
