### ISSUE TITLE
Go-to-GitHub icon on files should take you to branch rev, not SHA rev

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#407]
Reported by @sqs 

Repro:

1. Go to https://sourcegraph.sgdev.org/github.com/sourcegraph/docs-private/-/blob/201809/private-cxp-registry.md
2. As a user I want to edit the file, so I click the GitHub icon in the header and it takes me to https://github.com/sourcegraph/docs-private/blob/HEAD/201809/private-cxp-registry.md#L27

Actual: once on GitHub, I need to switch to the `master` branch in the GitHub rev switcher to be able to click the "Edit" icon to edit the file

Expected/desired: clicking the GitHub icon in step 2 should take me to https://github.com/sourcegraph/docs-private/blob/master/201809/private-cxp-registry.md so I can edit the file directly

Our current behavior (of mapping "no rev in Sourcegraph URL" to "HEAD on GitHub") is not *definitively* incorrect but it is very rarely the expected/desired behavior.

**Comment by vanesa** [comment]
I think its related tot his issue I'm working on: https://github.com/sourcegraph/sourcegraph/pull/364
