### ISSUE TITLE
lsif uploads UI - improve management of `FAILED` and `QUEUED` uploads via UI or worker jobs

### ISSUE THREAD

**Issue by DaedalusG** [sourcegraph/sourcegraph#40708]
#### Feature request description
We need admin buttons to do bulk operations on lsif uploads!

#### Is your feature request related to a problem? If so, please describe.
Yes this feature request is directly related to a problem in queued uploads have stacked up to a huge degree and dont seem to get cleaned up by the janitor. It highlights a need to have an emergency lever for cleaning up the uploads

#### Describe alternatives you've considered.
Creating a script to run bulk operations on uploads by programmatically consuming the graphQL API and issuing a bunch of mutation requests.

#### Additional context

For Sourcegraph team members this request is directly related to: https://github.com/sourcegraph/customer/issues/1238

**Comment by DaedalusG** [comment]
Further clarification on this issue -- retention policies for uploads specifically govern uploads in a COMPLETED state. Queued uploads may stack up and clutter the UI if the `precise-code-intel worker` service is under performing or encountering some other problem. `codeintel-janitor worker` [env vars](https://docs.sourcegraph.com/code_navigation/references/envvars#codeintel-janitor) can't be configured to more aggressively remove uploads in a `FAILED` or `QUEUED` state. 

In light of this we should also provide an additional janitor job for cleaning up old failed upload records.

**Comment by efritz** [comment]
Covered by #40417 and #41193.
