### ISSUE TITLE
insights: escape whitespace for aggregation drilldown queries

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#40707]
When author fields have whitespace they will break the semantic of a drilldown query unless whitespace is escaped. For example:

Aggregation query:
`type:commit insight`

Returning drilldown:
`type:commit author:Santa Claus insight`

In reality we need to generate:
`type:commit author:Santa\ Claus insight` or `type:commit author:Santa\sClaus insight`

/cc @joelkw @felixfbecker @vovakulikov @unclejustin

**Comment by felixfbecker** [comment]
I think simple quoting works too: `author:"Santa Claus"`. Quotes are not valid as git names or emails so that should be easy.

**Comment by coury-clark** [comment]
@felixfbecker I ended up just leaning into the fact its a regexp pattern and [wrapped it in a group](https://github.com/sourcegraph/sourcegraph/pull/40757)

**Comment by coury-clark** [comment]
To be more specific, I think with quotes it will still overmatch as a regexp, for example:
`repo:^github\.com/sourcegraph/sourcegraph$ type:commit author:"coury"` will still match `coury-clark`

**Comment by felixfbecker** [comment]
I'll close this for now since the issue is fixed, using quotes is more of an aesthetic follow-up

**Comment by leonore** [comment]
closed by #40757
