### ISSUE TITLE
Aggregation chart: Add "other" grouping for x-axis labels

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#40719]
Follow up for https://github.com/sourcegraph/sourcegraph/issues/39935

On the aggregation chart we could have a lot of labels on the x axis. In order to fit most of them in an appropriate way we have to hide some labels at the end of dataset and group them as Other (or just hide and render number of hidden labels) 

See [Figma designs](https://www.figma.com/file/cKSeCtmBh9aiPsAVoKsLgM?node-id=275:1628#251087317) for more details 

The first version of this could be just adding +n label at the chart container corner. 

/cc @joelkw @felixfbecker @vovakulikov @unclejustin

**Comment by Joelkw** [comment]
@vovakulikov can this be closed since we do have the "+30" or whatever that displays, or do we still need this open?

**Comment by vovakulikov** [comment]
Yes, I'm closing this, thanks for catching this one
