### ISSUE TITLE
CodeMirror Blob: override browser Cmd+F

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#40724]
Currently, users need to manually focus on the blob view to search through the contents of the blob view. It's not obvious that the focus state controls the behavior of Cmd+F. There are two alternative solutions that we could implement to address this issue:

- Auto-focus on the blob view: this has the benefit of making it still possible to use the built-in Cmd+F functionality by unfocusing the blob view, but it has the problem that it's easy to miss the focus state of the blob view and it's not obvious how to recover it.
- Override the browser Cmd+F functionality to only search via CodeMirror. This has the benefit of making it obvious how to search inside the file (via CodeMirror search), but it has the problem that it's not clear how users should trigger the built-in search functionality.

Related Slack discussions https://sourcegraph.slack.com/archives/C03PPPY5T6V/p1661248589303509?thread_ts=1661247389.478549&cid=C03PPPY5T6V

We agreed that the second option is the lesser evil so that's the approach we will try first.

- [ ] https://github.com/sourcegraph/sourcegraph/pull/40739
- [ ] Trigger CM search on Cmd+F when the search bar is focused
- [ ] (optional) Add search input in the "Files" sidebar
- [ ] (optional) Update ref panel search input to include matches from file contents

**Comment by jjinnii** [comment]
> users need to manually focus on the blob view to search through the contents of the blob view.

Just to expand on this, users can search through the contents of the blob view even when using the brower's native `cmd + f`. It's just that the CM search allows users to search through much longer files more effectively. Is this a correct understanding @olafurpg ?

I just want to clarify this because this was the point of confusion for me and Quinn when reading the working doc.

**Comment by olafurpg** [comment]
Currently, users can only search the visible lines of the blob using the builtin browser Cmd+F. To search for non-visible lines of code, you currently need to manually click on the CM view before triggering Cmd+F to activate the CM search component. 

I just opened https://github.com/sourcegraph/sourcegraph/pull/40739 which makes it so that Cmd+F triggers CM search even if the blob view is not focused. It doesn't work while the search bar is focused, @oleggromov is going to look into that separately.

**Comment by jjinnii** [comment]
## Design process

  - Estimate: One day to a week
  - Weighting factors: Medium risk, low certainty

  ### Discover
  - [x] Product and/or engineering provide direction and/or feedback

  ### Define
  - [x] Github issue
  - [ ] Design challenge

  ### Design
  - [ ] Wireframes - Link
  - [ ] High fidelity design using design system - Figma
  - [ ] Non-visual design guidance captured in the issue
  - [ ] Prototype - Link
  - [ ] Designer review

  ### Testing
  - [ ] Hallway testing - Link
  - [ ] Usertesting.com task based evaluation - Link

  ### Deliver
  - [ ] Loom - Link
  - [ ] Team review
  - [ ] Design team review
  - [ ] QA - Link

  ### Measure
  - [ ] Metrics defined in the Figma file ([i](https://handbook.sourcegraph.com/departments/product-engineering/product/design/metrics/defining-metrics/)) - Link
  - [ ] Followup task will analyze metrics to ensure successful completion - Link

**Comment by jjinnii** [comment]
@fkling Just an update, I've shared some [updated designs ](https://www.figma.com/file/xZ7os2VODDE3rNe4uFRDFu/CodeMirror-UI-Imrovements?node-id=118%3A13553)for the cmd + f that includes the file searchbar to the design team for review. They'll be reviewing by EOD Friday, and I'll confirm final designs for implementation by EOD or start of your day Monday. 😄
