### ISSUE TITLE
Hubspot extension now borks typing completely

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#4072]
`Experimental text field completion` being on now completely borks typing in GitHub input fields. In the following gif I:

1. Type `Was this closed intentionally?`
2. Then move my cursor to the front and type `I don't understand WTF is going on?`

![](http://g.recordit.co/yPASeImKuj.gif)

**Comment by sqs** [comment]
Any clue what might’ve made this start happening, anyone?

**Comment by sqs** [comment]
@felixfbecker Low priority ask (less important than 3.4 release) - can you think of any changes that would've caused this new glitchiness?

**Comment by felixfbecker** [comment]
Yeah I think I know the reason for this. In #4025 I changed `EditorService.editors` to only emit if anything about the editor itself changed, not the underlying Model it points too (except if it suddently points to a _different_ model, but not if just _properties_ of the Model changed, like different text). To listen to changes to Models, you should use `ModelService.models`. This was an important optimization. The completion widget however listens to `EditorService.editors` to get notified of Model changes:  https://sourcegraph.com/github.com/sourcegraph/sourcegraph@4b21c240e0a8a2dd3d2d6714818c891cefa136b2/-/blob/shared/src/components/completion/EditorCompletionWidget.tsx#L52:9-65:118

**Comment by sqs** [comment]
Fix in PR #4546
