### ISSUE TITLE
Auth: searches don't work when signed-in via GitHub Enterprise

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#4074]
- Run Sourcegraph 3.4.0-rc.4
- Add a GHE external service pointing to ghe.sgdev.org
- Configure sign-in via GitHub in the management console
- Sign in via GitHub
- Run a search for `r:`
- Notice this error:

![image](https://user-images.githubusercontent.com/1387653/57893020-281a8e80-77f6-11e9-980f-94db508ff59f.png)

When I sign in using built-in auth, that search works.

I noticed the URL is http://ghe.sgdev.org/api/v3/graphql but GitHub's GraphQL API is v4.

**Comment by beyang** [comment]
@chrismwendt I'm unable to reproduce this. I'm signed in as `beyang@sourcegraph.com` on ghe.sgdev.org, and I have the following GitHub external service config:

```
{
  "url": "http://ghe.sgdev.org",
  "token": "$TOKEN",
  "repositoryQuery": [
    "affiliated"
  ]
}
```


And the following critical site config:

```
{
	"auth.providers": [
    {
      "type": "github",
      "displayName": "GitHub",
      "url": "http://ghe.sgdev.org/",
      "allowSignup": true,
      "clientID": "$CLIENT_ID",
      "clientSecret": "$CLIENT_SECRET"
    }
	]
}
```
