### ISSUE TITLE
insights: Investigate how to get more capture group aggregations to finish in time

### ISSUE THREAD

**Issue by CristinaBirkel** [sourcegraph/sourcegraph#40756]
Now that we're adding in the capture group aggregations, it's clear that these might need more time to finish in general. Can we give these searches more than 2 seconds? Can we improve the performance some other way? Can we make do with less results?

/cc @joelkw @felixfbecker @vovakulikov @unclejustin

**Comment by felixfbecker** [comment]
I'm curious what about capture groups makes them require more time than other attributes?
And what's the implication of not raising the timeout, i.e. in what % of searches would proactive insights not be shown?

**Comment by chwarwick** [comment]
@felixfbecker I looked at this a bit more after talking with @CristinaBirkel, it does not appear to be directly related to capture groups but more that regex queries can take longer to run.  When filters are applied to limit where results are expected they can complete quickly.  An example was a regex that was pulled from an insight `go\s*(\d\.\d+)` searching for go versions took about 6 seconds to complete, if it were filtered to the go.mod file where you would expect to find that it completes about 0.7 seconds well within our current time limits.

There isn't a way to answer the 2nd question.

**Comment by felixfbecker** [comment]
Okay, so maybe this isn't an issue then? We could just do the 2s timeout and not show a proactive chart in the case of an expensive query like that?

**Comment by CristinaBirkel** [comment]
Just as an update: as per [this slack thread](https://sourcegraph.slack.com/archives/CHEKCRWKV/p1661353098792049), we may see some performance improvement here pending https://github.com/sourcegraph/sourcegraph/issues/34826.

**Comment by felixfbecker** [comment]
I would say we should rely on those performance improvements then and otherwise accept that proactive capture group insights may time out more often. As long as we still fix https://github.com/sourcegraph/sourcegraph/issues/40861 there will always be a way to re-run without a timeout.

Since this was an investigation ticket, I propose we close it?

**Comment by CristinaBirkel** [comment]
@felixfbecker that sounds good. Closing.
