### ISSUE TITLE
"Try Sourcegraph Enterprise free for 30 days" checkbox appears to do nothing

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#4076]
1. Start a sourcegraph/server
2. When creating the admin account, check the `Try Sourcegraph Enterprise free for 30 days" checkbox.
3. Finish creating the admin account & be surprised when you are left on a site admin page saying that your Sourcegraph version is just "core" and that to upgrade you need to buy a license.

I assume we reach out to these individuals via email -- but it is confusing that we don't tell them we will do that or communicate that at all.

**Comment by dadlerj** [comment]
Thanks for reporting. Yes, we reach out via email (and these can fall behind). Do you think it would be better if we shot an auto email back to anyone who checks it that says something like "We received your request, we'll be in touch"?

**Comment by slimsag** [comment]
I think just changing the wording would suffice.

```diff
- Try Sourcegraph Enterprise free for 30 days
+ Try Sourcegraph Enterprise free for 30 days (via email next business day)

**Comment by slimsag** [comment]
Or when you check it, add a text line that says that: `We'll send you a trial key within the next business day via email"
