### ISSUE TITLE
External Services blank state page could be better

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#4077]
When I run sourcegraph/server for the first time I am left on the site admin page:

![image](https://user-images.githubusercontent.com/3173176/57894364-7ed69700-77fb-11e9-859c-cf1ad46ce307.png)

The banner at the top is pretty clear that I should next configure external services, so I click that link and end up here:

![image](https://user-images.githubusercontent.com/3173176/57894380-93b32a80-77fb-11e9-9e9a-6617997a14a1.png)

On its own this page does a poor job of communicating to me what I am doing or why I should care about "external services" (whatever those are).

As soon as I click "Add external service" I suddenly see all of the code hosts and it is very obvious what I am doing: I'm adding my repositories.

![image](https://user-images.githubusercontent.com/3173176/57894419-b5acad00-77fb-11e9-9fe9-ff358d105c39.png)

Proposal: When there are no external services, the listing page `/site-admin/external-services` simply redirects to the above page `/site-admin/external-services/new`.

**Comment by attfarhan** [comment]
This appears to have been fixed. Closing.
