### ISSUE TITLE
External service default configurations are missing trailing commas which make them invalid

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#4078]
The commented out entries in the external service default configurations `repos` and `exclude` are missing trailing commas, so as a first time admin when I uncomment and fill in the relevant details in them I am suddenly greeted with:

![image](https://user-images.githubusercontent.com/3173176/57894693-a67a2f00-77fc-11e9-8022-f3a5679bf097.png)

This is particularly surprising because my first instinct is to check the lines _I added_ and the commas on those are right, only to a few minutes later realize it is the lines I just uncommented that were incorrect.

https://github.com/sourcegraph/sourcegraph/commit/8dc720498ce81841ac8e39a9bf6838e787912d63#diff-0431c8afac7c36bfdd0c890c23e527e1R221

**Comment by ryan-blunden** [comment]
Good call. Now that I know no commas are worse than unnecessary trailing comma's I'll submit a new PR for 3.4

**Comment by sqs** [comment]
#4100 helps here too
