### ISSUE TITLE
Repo search fails to return matching repositories

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#4079]
- **Sourcegraph version:** k8s.sgdev.org

#### Steps to reproduce:

1. Search for `repo:sourcegraph` and see a lot of results (https://k8s.sgdev.org/search?q=repo:sourcegraph), including many repos named "github.com/sourcegraph"
![image](https://user-images.githubusercontent.com/5589410/57894718-bc87ef80-77fc-11e9-9755-86429ad627fd.png)

2. Search for `repo:github.com` and see only two results — none matching those that were displayed in the previous search (https://k8s.sgdev.org/search?q=repo:github.com)
![image](https://user-images.githubusercontent.com/5589410/57894738-d45f7380-77fc-11e9-90de-847c9904978a.png)

#### Expected behavior:
All of the results from the first search should have also appeared on the second search

#### Actual behavior:
None of the results from the first search appeared on the second search

**Comment by slimsag** [comment]
If you escape the `.` in `github\.com` it works. I don't expect that at all (it should be matching "any character, including a period" but it may not be a regression.

**Comment by dadlerj** [comment]
Cool, I'm open to being told this isn't a release blocker, I leave this up to the code owner!

**Comment by sqs** [comment]
This is likely a bug in how we translate regexps to PostgreSQL LIKE patterns for efficient querying in the db package. I am surprised we haven’t seen this before, and it is a critical bug (unless we find that it could only occur in very rare situations).

We need to see if anything here changed that could’ve caused it. If so, this is a release blocker. If not (which implies it occurs only in very rare circumstances), it is OK to fix this in a patch release and not have this block release.

**Comment by keegancsmith** [comment]
@mrnugget I'll take a look at this today since I'm very familiar with this code path. If you wanna pair on it to learn some of our search stuff, just shout.

**Comment by keegancsmith** [comment]
@sqs turns out this is something we have always done, but I think it should be removed. We literally have a check that if pattern starts with `github.com`, translate that into `^github.com`.

**Comment by sqs** [comment]
Ah, good find. I believe I added this because otherwise repo:github.com/foo queries were slow. If they are or can be made fast, definitely no need for this anymore.

**Comment by keegancsmith** [comment]
> Ah, good find. I believe I added this because otherwise repo:github.com/foo queries were slow. If they are or can be made fast, definitely no need for this anymore.

I just special cased it so it would only run on sourcegraph.com
