### ISSUE TITLE
sg: propagate sg analytics Honeycomb token

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#40806]
sg analytics requires a honeycomb token, which prompts the user. We want to fetch this from a remote location automatically. 

Right now it must be manually retrieved from 1pass (https://team-sourcegraph.1password.com/vaults/all/allitems/skz23jc6jdi7jvve36f7nn2pla)

**Comment by davejrt** [comment]
depends on: https://github.com/sourcegraph/sourcegraph/pull/41579

**Comment by michaellzc** [comment]
I believe most engineering teammates have `gcloud` installed (or already authenticated)

we can share secret over GSM (or `dev-private` repo)

we can either shell it out to`gcloud` CLI using `run` or use the GCP Go SDK to retrieve the API token from GSM

**Comment by burmudar** [comment]
Added Honeycomb token to Gcloud sercret manager under `Sourcegraph Local Dev`
