### ISSUE TITLE
Fill out docs page for search aggregations

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#40805]
The page should explain the feature and the known limitations of proactive (and non-proactive) aggregation insights.

The "Learn more" link in the UI needs to be updated to point to the page.

/cc @joelkw @felixfbecker @vovakulikov @unclejustin

**Comment by felixfbecker** [comment]
@Joelkw can add outline once we have first version to play with, but will need engineers to document the limitations.

**Comment by Joelkw** [comment]
@felixfbecker scaffold is up, I'm unassigning myself now.
