### ISSUE TITLE
Cloning repositories return 404 Not Found

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#4081]
See the tab title

![image](https://user-images.githubusercontent.com/10532611/57894885-9151d000-77fd-11e9-80e2-b99a62f4d4b8.png)

**Comment by slimsag** [comment]
Would indicate we're not hitting this code branch I believe: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/app/ui/handlers.go#L172-175

Should be reproducible using the specially-handled `github.com/sourcegraph/AlwaysCloningTest` repository.
