### ISSUE TITLE
User and Global settings / monaco field unusable

### ISSUE THREAD

**Issue by vanesa** [sourcegraph/sourcegraph#4082]
#### Steps to reproduce:

1. Spin up a new instance
2. Create an admin account
3. Visit the user settings or global settings
4. Settings fields are too small.

Seems to be similar to this former issue: https://github.com/sourcegraph/sourcegraph/issues/1943

#### Expected behavior:
Normal sized empty settings field.
#### Actual behavior:
![image](https://user-images.githubusercontent.com/9110008/57893786-125a9880-77f9-11e9-9993-c1d44fb7bde2.png)

![image](https://user-images.githubusercontent.com/9110008/57894811-2ef8cf80-77fd-11e9-9e85-801eaf51df53.png)

**Comment by slimsag** [comment]
This was allegedly fixed 8 days ago: https://github.com/sourcegraph/sourcegraph/issues/3645

What version of Sourcegraph did you reproduce this on?

**Comment by vanesa** [comment]
Oh oops!
