### ISSUE TITLE
Improve search history activation

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#40833]
## Successful outcomes of this issue
- [ ] Trigger history on focus (or after 100ms if that's the activation time for the rest of the suggestions)
- [ ] When activating with `Ctrl + space`, also trigger after 100ms (or whatever the standard suggestion time is), not the current longer wait time
- [ ] Support activating search history with `Ctrl/Meta + N`
  - [ ] And support navigating the list downward with `Ctrl/Meta + N` and downward with `Ctrl/Meta + P`

## Background
It takes a long time (feels like almost a second) to activate search history on input focus and when manually activated with `Ctrl + space`. The other suggestions activate/can be manually triggered instantly, making the history delay feel slow and inconsistent, especially when manually activated. 

By comparison, Google suggestions, which include history items, are displayed instantly when you click in or press down arrow in the input (if they're hidden).

I found [this Slack thread](https://sourcegraph.slack.com/archives/C020S8AT3LN/p1659687438643809) which provides some context as to how we got to the current state, but it also seems like what was ultimately landed on was a short (100ms?) delay for showing suggestions when available, not a separate and longer delay exclusively for activating search history, which is what seems to have also been implemented.

**Comment by fkling** [comment]
I don't think this is relevant anymore with the new search input (and we are looking into how we better integrate history anyway).
