### ISSUE TITLE
Reference panel: display message in preview pane to indicate that syntax highlighting timed out 

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#40841]
Currently, we display unhighlighted code in the reference panel preview pane if syntax highlighting times out without displaying an explanation why the code is not highlighted. It would be nice if we displayed a message to explain what happened

![CleanShot 2022-08-25 at 13 25 53](https://user-images.githubusercontent.com/1408093/186652470-2b802728-1e58-4337-84e6-653a717a64eb.png)

**Comment by camdencheek** [comment]
Closing and linking https://github.com/sourcegraph/sourcegraph/issues/60428 since this will be covered under the code nav redesign with its associated messaging improvements.
