### ISSUE TITLE
"Go ifaces/impls" text appears on Explore page

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#4085]
- **Sourcegraph version:** k8s.sgdev.org

#### Steps to reproduce:

1. visit https://k8s.sgdev.org/explore to see the explore page how it is supposed to look
2. next, visit any Golang file on the instance, e.g. https://k8s.sgdev.org/github.com/gorilla/mux/-/blob/context_test.go
3. from that Go file, click on the "Explore" button in the top right
4. see the text "Go ifaces/impls" appear in the middle of the page:

![image](https://user-images.githubusercontent.com/5589410/57895318-e2fb5a00-77ff-11e9-8cf6-a9c19796f0bf.png)

Tagged you two because it seems vaguely related to extensions, but no idea who should own it. Not a huge deal.

**Comment by felixfbecker** [comment]
The Panel is contributed by the Go extension, and certainly shouldn't have such a title: https://sourcegraph.sgdev.org/search?q=Go+ifaces/impls @chrismwendt 

For why panels are rendered there at all (doesn't seem to make sense for implementations), that's a question for @sqs who added this: https://sourcegraph.sgdev.org/sourcegraph/sourcegraph@323bab7479ba6f7ca7808c667d58b66cb8035841/-/blob/web/src/extensions/explore/ExtensionViewsExploreSection.tsx#L28:14&tab=references

**Comment by sqs** [comment]
Let’s just remove this from the explore page. Showing these was experiments and I didn’t realize this bad outcome would occur.

**Comment by chrismwendt** [comment]
Is this still an issue? I can't seem to repro.

**Comment by felixfbecker** [comment]
Cannot repro anymore
