### ISSUE TITLE
corner case query issues for regex matching only white space

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#40864]
something like this is fine:

<img width="881" alt="Screen Shot 2022-08-25 at 12 04 52 PM" src="https://user-images.githubusercontent.com/888624/186747830-cd97a1b8-2347-4a5e-b084-71f61caab90e.png">

but if you only search for `\n` or something like `(\r\n|\r|\n)`, this breaks on S2:

<img width="1262" alt="Screen Shot 2022-08-25 at 12 08 04 PM" src="https://user-images.githubusercontent.com/888624/186748296-ba019a36-69df-4c78-bbe4-0c7bafaa733b.png">

[**Query**](https://sourcegraph.sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+%5Cn&patternType=regexp)

---

Also, on Sourcegraph.com, we show all kinds of `0` empty results

<img width="1498" alt="Screen Shot 2022-08-25 at 12 08 54 PM" src="https://user-images.githubusercontent.com/888624/186748471-a2dd7ab8-8e41-4816-ab3b-8e88854ebbf7.png">

[**Query**](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+%28%5Cr%5Cn%7C%5Cr%7C%5Cn%29&patternType=regexp)

/cc @benvenker @lguychard

**Comment by fkling** [comment]
I can't reproduce this anymore.
