### ISSUE TITLE
bitbucket server configuration links to aws code commit docs

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#4087]
https://github.com/sourcegraph/sourcegraph/blob/v3.4.0-rc.4/web/src/site-admin/externalServices.tsx#L310

**Comment by slimsag** [comment]
@ryan-blunden I think your change may have caused this regression? not positive though

**Comment by mrnugget** [comment]
This has been fixed in #4099: see [here](https://github.com/sourcegraph/sourcegraph/pull/4099/files#diff-0431c8afac7c36bfdd0c890c23e527e1R310)
