### ISSUE TITLE
Better reason tooltips for aggregations that are not available

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#40870]
Currently, all `reasonUnavailable` messages, which come from the backend and get displayed to the user in a tooltip, are of the form "this specific query does not support aggregation by CAPTURE_GROUP".

<img width="308" alt="image" src="https://user-images.githubusercontent.com/10532611/186765650-7d189f45-b698-4429-880a-fbb23b632db6.png">

- The attribute should not be in ALL_CAPS
- The message should be capitalized at the beginning
- Instead of just stating that the query doesn't support it, it should give a bit more info as to why. For example, if the type of the query doesn't support it, it should say "Commit message queries cannot be aggregated by file". If the query doesn't have a capture group, it should say "The query does not contain a capture group". If it's not patterntype regex, it should say etc etc

/cc @joelkw @felixfbecker @vovakulikov @unclejustin

**Comment by felixfbecker** [comment]
Reasons are in https://github.com/sourcegraph/sourcegraph/issues/40682

**Comment by Joelkw** [comment]
Per our style guidelines I don't believe that in "Group by File..." or "Group by Author..." neither File nor Author should be capitalized. (No specific guidelines for tooltips but for headings/buttons/confirmations we use sentence case: https://handbook.sourcegraph.com/company-info-and-process/communication/content_guidelines/actionable_language/#buttons )
