### ISSUE TITLE
ci/flake: TestSubRepoPermissionsPerforce/cannot_read_hack.sh disabled

### ISSUE THREAD

**Issue by tbliu98** [sourcegraph/sourcegraph#40882]
### Test

TestSubRepoPermissionsPerforce/cannot_read_hack.sh

### Example failure

https://buildkite.com/sourcegraph/sourcegraph/builds/169326#0182d7a7-632b-4827-ac70-140abd1f42f4

### Disabling PR

https://github.com/sourcegraph/sourcegraph/pull/40881

/cc @jplahn @ryphil

**Comment by sashaostrikov** [comment]
This is the only non-flaky sub-test, actually :)
