### ISSUE TITLE
Disable `no-abbreviations` rule in shared `eslint-config`

### ISSUE THREAD

**Issue by gitstart-sourcegraph** [sourcegraph/sourcegraph#40884]
## Descripition
Disable `no-abbreviations` rule in the shared eslint config, and update version used in `package.json` file on this repo once it's published to npm registry.

## Success criteria

`no-abbreviations` - rule should be disabled in the shared eslint-config, and version updated on monorepo once published to npm.

## Time estimate

- Pull requests with ~450 lines changed should take **30min** at maximum. Ping the reviewer in the spec pull request if time-consuming changes are required.
- Split the work into multiple pull requests if the total diff is bigger than 450 lines of code.

**Comment by valerybugakov** [comment]
Closing this one since it's done.
