### ISSUE TITLE
ci/flake: nightly VSCE integration tests disabled

### ISSUE THREAD

**Issue by taras-yemets** [sourcegraph/sourcegraph#40891]
### Test

Nightly VSCE integration tests

### Example failure

https://buildkite.com/sourcegraph/sourcegraph/builds/169322

### Disabling PR

https://github.com/sourcegraph/sourcegraph/pull/40890

/cc @muratsu @jjinnii @ryankscott

**Comment by philipp-spiess** [comment]
@taras-yemets We're unsure about the status of the fix. Does this need additional work?

**Comment by vdavid** [comment]
@taras-yemets just responded that it doesn't need more work, closing this.
