### ISSUE TITLE
Reference panel: very easy to click on repository when trying to expand item

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#40904]
The button to expand items in the reference panel is very small making it difficult to click.
Meanwhile, the link to the repository is large and easy to accidentally click on

![CleanShot 2022-08-26 at 12 37 56](https://user-images.githubusercontent.com/1408093/186886270-9667cd99-9450-4cef-b394-eb452b750965.gif)

I'd prefer if clicking anywhere on the name of the repository would expand the list, and we'd have a small icon to go to the repo directory (which I suspect is a niche use-case)

To reproduce, open the new ref panel and click on any of the file/repo items in the tree view

![CleanShot 2022-08-26 at 12 40 44](https://user-images.githubusercontent.com/1408093/186886861-db3bcd63-1467-4e4c-b02f-51194629f3cc.png)

https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/database/code_monitor_slack_webhook.go?L44:65&popover=pinned#tab=references

**Comment by jjinnii** [comment]
Thanks for the feedback @olafurpg! I would agree with changing the entire row to be the expand/collapse area prior to release for a few reasons: 

-  This change would make the reference panel more consistent with the file treeview. While it's a different interaction as the file blob is live updating as the user navigates up/down directories, users may expect that clicking on the entire row (arrow + path) will expand/collapse like in our treeview. 
- Agreed that the expand collapse click area is too small, when the more frequent use case would be navigating through results, as opposed to jumping immediately to a file. 
- More consistent with industry standards (Chromium for reference panel, and VS Code/JetBrains file treeviews also use the entire line for expand/collapse behaviors) 

This behavior requires a[ few changes to the UI](https://www.figma.com/file/DZMyEJT3g2HT6HmJGNNOnW/%22Better%22-code-intel-panel?node-id=1722%3A10977): 

1. I've changed the colors of the file path from the "link-blue" to "body-color". I used the link blue in the prior design to visually distinguish from the arrow expand/collpase versus the re-direct.
2. Updated the color of the arrow from "body-color" to "icon-color". (This was a miss on my part outside of this issue)
3. I'm intentionally not adding an icon to navigate directly to the directory without first expanding the Preview. As you mentioned, this is likely a smaller use case, and we can always add this ability back after collecting more feedback.
