### ISSUE TITLE
Configure `srcCliVersionCache` on dotcom

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#40909]
After https://github.com/sourcegraph/sourcegraph/pull/40827 https://github.com/sourcegraph/sourcegraph/pull/40828 landed we can start configuring the version cache on dotcom.

**Comment by LawnGnome** [comment]
P1, only because we can't do this until 4.0 is deployed to dotcom, and I don't know if that will be in the next sprint.

**Comment by eseliger** [comment]
does it need to wait for 4.0 to be a thing, or would it just need the code? Dotcom is updated ~daily.

**Comment by LawnGnome** [comment]
It just needs the code. I actually thought dotcom was handled like a managed instance in that regard, so I guess we could do this whenever, then.

**Comment by LawnGnome** [comment]
Oh, I did this already. See https://sourcegraph.com/.api/src-cli/versions/4.0 for a fun example.
