### ISSUE TITLE
Saved searches not migrated when upgrading to 3.4

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#4091]
- **Sourcegraph version:** 3.3.7 --> 3.4
- Single-server docker image

#### Steps to reproduce:

1. Spin up a server in 3.3.7
2. Save a saved search in global settings, e.g.:

![image](https://user-images.githubusercontent.com/5589410/57895994-61a5c680-7803-11e9-9263-ca180864c74f.png)

3. Shut down the server, and restart it on 3.4.0-rc.3
4. Visit saved searches and see nothing there:

![image](https://user-images.githubusercontent.com/5589410/57896012-7aae7780-7803-11e9-9f38-cba6be4a8599.png)

Haven't yet tried with saved searches in user or org settings (only global)

**Comment by dadlerj** [comment]
Edit: the saved search clearly IS migrated, as it still appears for a site-admin on 3.4.0-rc.3. It no longer appears for my non-admin user, however. 

See the screenshot below for two users signed in next to each other (on 3.4.0-rc.3). On the left, the site-admin view, on the right, the non-admin view:

![image](https://user-images.githubusercontent.com/5589410/57896171-3374b680-7804-11e9-8b6a-1dcf907e43dc.png)

**Comment by dadlerj** [comment]
Perhaps intentional given https://github.com/sourcegraph/sourcegraph/issues/4094#issuecomment-493282071 but not the best experience

**Comment by attfarhan** [comment]
Yeah this is intentional, we removed global saved searches and assign them to the first site admin user on the instance.
