### ISSUE TITLE
Saved searches list page shows incorrect number of results

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#4093]
While following the [test plan](https://docs.google.com/document/d/10QryO5cvEEVw6m5VI6D7JY-oYcD1yJbwUp_uqNFdySg/edit#heading=h.9ks991mkjfr6), I was able to receive the email notification but the saved search list page has not updated the results to 3 as it should have.

![ScreenFlow](https://user-images.githubusercontent.com/133014/57896035-97e34600-7803-11e9-851b-7bcbcde06c97.gif)

It may have something to do with my server taking a while to perform the diff search but not sure.

![Screen Shot 2019-05-16 at 6 00 53 PM](https://user-images.githubusercontent.com/133014/57896237-97977a80-7804-11e9-8285-6c18df0b7ab4.png)

[Email link](https://165.227.55.213/search?q=repo%3Asourcegraph%2Ftest-saved-searches%24+type%3Adiff+This+is+test+file+after%3A%222019-05-17T00%3A36%3A52Z%22&utm_source=saved-search-email)

**Comment by slimsag** [comment]
These links only run the query that the saved search is set to run, so the bug here is that diff search is slow on your system. Unclear if this is a regression or not.

With that being said, if you click the link in the email notification it would be scoped to a specific time-range and should load fine.

**Comment by slimsag** [comment]
Unlikely to be a regression so I am removing release-blocker.

**Comment by beyang** [comment]
assigning to @attfarhan to decide what to do with this.

**Comment by slimsag** [comment]
#4279 fixed #4063 not this issue.

**Comment by malomarrec** [comment]
Tagging similar issue in #20158 to feed into prioritisation work.

**Comment by lguychard** [comment]
Saved searches no longer support notifications, no similar issue has been reported for code monitoring.
