### ISSUE TITLE
I can no longer save searches to global settings as an admin

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#4094]
- **Sourcegraph version:** 3.4.0-rc.3
- **Platform information:** Single-server Docker image

#### Steps to reproduce:

1. Run server on 3.4.0-rc.3
2. Sign in as an admin
3. Run a search
4. Click "Save this search query"
5. Note that there's no way to save it anywhere except user settings, and perhaps orgs if I was in any. I can no longer save to global settings.

If this is intentional, feel free to close.

**Comment by slimsag** [comment]
This is intentional, we've removed the ability to create global saved searches. They are only associated with an organization or user now.

**Comment by slimsag** [comment]
(and all previously global saved searches are migrated to the first admin user on the instance)
