### ISSUE TITLE
RFE: Button to delete repository and resync on the repo status page

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#40950]
**Requested by:** https://github.com/sourcegraph/accounts/issues/6716 [via Slack](https://sourcegraph.slack.com/archives/C01D50MSA7L/p1638941361245400)

#### Feature request description

Add a button to allow an administrator to delete a failed repository and reclone from the repository status page.

#### Is your feature request related to a problem? If so, please describe.

Often a failed repository can be fixed by trying again.  Currently, the only way to force this is to login to the gitserver and delete the repository manually.  In some cases customers cannot login to the services directly or it is challenging to do so.  Having a button on the UI makes this step easier.

#### Additional context

[Internal Product Gap](https://sourcegraph2020.lightning.force.com/lightning/r/a1C5b00000AEophEAD/view)

**Comment by pjlast** [comment]
See merged Pull Request here: https://github.com/sourcegraph/sourcegraph/pull/42177
