### ISSUE TITLE
No clear indication if hover came from basic or precise code intel

### ISSUE THREAD

**Issue by christinaforney** [sourcegraph/sourcegraph#4095]
When doing testing for the 3.4.0 release, Beyang and I were looking at an issue:
* (https://github.com/sourcegraph/sourcegraph/pull/4031/files)
* hovered over line 520: `defer a.mu.Unlock()` and did not see a hover result for `Unlock`. 
* hovered over line 519: `a.mu.Lock()` and got a result
* We assumed the second hover result was correct and initially thought that the defer statements were not working
* We next discovered that other standard library references were also not working and thought that it was standard library that was broken.
* We did not notice that the result for the `Lock()` hover was actually an incorrect reference and this was a red herring for us.
* It turns out I only had basic code intel enabled, but this was not obvious.

Ultimately, we should improve the way that this information is surfaced to users to make this sort of configuration difference more apparent.

@chrismwendt can we discuss whether we should prioritize this for 3.5 - it might seriously impact code-nav UX.

**Comment by chrismwendt** [comment]
Added to the code nav sync notes for the next meeting https://docs.google.com/document/d/1H9j1nopKePsopMeYQeQPB0jif7LAxIJVodo4ZenDhpQ/edit#

**Comment by efritz** [comment]
We've added badges and CTA notices since this issue was filed.
