### ISSUE TITLE
CodeMirror blob: make popover more sticky

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#40969]
Currently, the popover quickly disappears when the mouse hovers around the borders. We should increase the border radius of the hover region to make it easier to move the mouse to definition/references buttons 

Original report https://sourcegraph.slack.com/archives/C03CSAER9LK/p1661556219158469

**Comment by sqs** [comment]
Added release-blocker label as I'm noticing this happen a lot when using the new hover.

**Comment by olafurpg** [comment]
@sqs Agreed. I added release-blocker to a few more CodeMirror blob-related issues, tracked here https://github.com/orgs/sourcegraph/projects/211/views/21?filterQuery=label%3Ateam%2Fcode-navigation+is%3Aopen+-status%3A%22🧊+Icebox%22++-no%3Astatus+CodeMirror+label%3Arelease-blocker

Progress on the blob view has been slow over the past week due to team size changes and lattice reviews. We'll see how many of these issues we can fix in the coming week, we might make a lot of quick progress with Felix returning from PTO. I estimate we'll have a decent answer by EoD wednesday whether we're confident about enabling the new blob view or not.
