### ISSUE TITLE
Add deprecation notice to extension repos

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#40974]
e.g. [sentry extension](https://github.com/sourcegraph/sourcegraph-sentry)

- [x] Collect all repos

Open in Editor (added by @vdavid):
- [ ] Open in Editor – [repo](https://github.com/sourcegraph/open-in-editor-extension) – [PR](https://github.com/sourcegraph/open-in-editor-extension/pull/27)
- [ ] VSCode – [repo](https://github.com/sourcegraph/sourcegraph-open-in-vscode)
- [ ] WebStorm – [repo](https://github.com/1inuxoid/sourcegraph-open-in-webstorm) (third-party!)
- [ ] IntelliJ – [repo](https://github.com/sourcegraph/sourcegraph-open-in-intellij) – not published?
- [ ] Atom – [repo](https://github.com/sourcegraph/sourcegraph-open-in-atom)
- (Sublime – though “Open in Editor”)

All repos:
## List of Sourcegraph-maintained extension repositories

Here are all repositories beyond sourcegraph/sourcegraph that relate to extensions. 

### Code host integrations
- [phabricator-extension](https://github.com/sourcegraph/phabricator-extension)
- [bitbucket-server-plugin](https://github.com/sourcegraph/bitbucket-server-plugin)

### Editor extensions
- [sourcegraph-vscode](https://github.com/sourcegraph/sourcegraph/tree/main/client/vscode)
- [sourcegraph-sublime](https://github.com/sourcegraph/sourcegraph-sublime)
- [sourcegraph-atom](https://github.com/sourcegraph/sourcegraph-atom)
- [sourcegraph-jetbrains](https://github.com/sourcegraph/sourcegraph/tree/main/client/jetbrains)

### Sourcegraph Extensions
- [extension-api-classes](https://github.com/sourcegraph/extension-api-classes)
- [codeintellify](https://github.com/sourcegraph/codeintellify)
- [create-extension](https://github.com/sourcegraph/create-extension)
- [extension-api-stubs](https://github.com/sourcegraph/extension-api-stubs)
- [codecov/sourcegraph-codecov](https://github.com/codecov/sourcegraph-codecov)
- [sourcegraph-extension-samples](https://github.com/sourcegraph/sourcegraph-extension-samples)
- [sourcegraph-git-extras](https://github.com/sourcegraph/sourcegraph-git-extras)
- [sourcegraph-code-ownership](https://github.com/sourcegraph/sourcegraph-code-ownership)
- [sourcegraph-jira](https://github.com/sourcegraph/sourcegraph-jira)
- [sourcegraph-search-export](https://github.com/sourcegraph/sourcegraph-search-export)
- [sourcegraph-code-discussions](https://github.com/sourcegraph/sourcegraph-code-discussions)
- [sourcegraph-debug-extension](https://github.com/sourcegraph/sourcegraph-debug-extension)
- [contributors-extension](https://github.com/sourcegraph/contributors-extension)
- [skeleton-language-extension](https://github.com/sourcegraph/skeleton-language-extension)
- [sourcegraph-sentry](https://github.com/sourcegraph/sourcegraph-sentry)
- [sourcegraph-eslint](https://github.com/sourcegraph/sourcegraph-eslint)
- [codenav-bash](https://github.com/sourcegraph/codenav-bash)
- [sourcegraph-github-extras](https://github.com/sourcegraph/sourcegraph-github-extras)
- [sourcegraph-lightstep](https://github.com/sourcegraph/sourcegraph-lightstep)
- [open-in-editor-extension](https://github.com/sourcegraph/open-in-editor-extension)
- [sourcegraph-open-in-intellij](https://github.com/sourcegraph/sourcegraph-open-in-intellij)
- [sourcegraph-open-in-atom](https://github.com/sourcegraph/sourcegraph-open-in-atom)
- [sourcegraph-open-in-sublime](https://github.com/sourcegraph/sourcegraph-open-in-sublime)
- [sourcegraph-open-in-vscode](https://github.com/sourcegraph/sourcegraph-open-in-vscode) (vscode-extras)
- [sourcegraph-datadog-metrics](https://github.com/sourcegraph/sourcegraph-datadog-metrics)
- [sourcegraph-hubspot](https://github.com/sourcegraph/sourcegraph-hubspot)
- [sourcegraph-sonarqube](https://github.com/sourcegraph/sourcegraph-sonarqube)
- [sourcegraph-snyk](https://github.com/sourcegraph/sourcegraph-snyk)
- [sourcegraph-link-preview-expander](https://github.com/sourcegraph/sourcegraph-link-preview-expander)
- [sourcegraph-contact-author](https://github.com/sourcegraph/sourcegraph-contact-author)
- [sourcegraph-who-knows-about-this](https://github.com/sourcegraph/sourcegraph-who-knows-about-this)
- [python-imports-search](https://github.com/sourcegraph/python-imports-search)
- [java-imports-search](https://github.com/sourcegraph/java-imports-search)
- [go-imports-search](https://github.com/sourcegraph/go-imports-search)
- [js-dependency-search](https://github.com/sourcegraph/js-dependency-search)
- [sourcegraph-find-replace](https://github.com/sourcegraph/sourcegraph-find-replace)

Text to be added: we have no official copy but [this example](https://github.com/sourcegraph/open-in-editor-extension/pull/27/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) might help.

/cc @muratsu @jjinnii @ryankscott

**Comment by vdavid** [comment]
Created a PR for Open in Editor. If it's accepted by the team, I intend to add the same copy for the other three “Open in Editor” repos that are our own. For the WebStorm one, I intend to create a PR and message the repo owner.

**Comment by ryankscott** [comment]
We need to add this to *all* of our extension repos. Obviously the copy will change slightly depending on whether they're being graduated or not. 

I hope that this list of [repositories](https://docs.sourcegraph.com/dev/background-information/sourcegraph_extensions#sourcegraph-extensions) is up to date and complete.

**Comment by vdavid** [comment]
Absolutely. I just started with “Open in Editor” because I didn't have a list of all repos.
So thanks for the list, and I'm pretty happy to go through all our repos and add similar versions of the deprecation notice, I think I could do it in less than an hour for the 35 listed repos after some initial discussion & decision-making.

**Comment by vdavid** [comment]
Done with 17! 🎉
In three cases, I didn't have write access, so created PRs instead:

https://github.com/sourcegraph/sourcegraph-contact-author/pull/3
https://github.com/sourcegraph/sourcegraph-who-knows-about-this/pull/3
https://github.com/sourcegraph/sourcegraph-find-replace/pull/7

**Comment by vdavid** [comment]
Done. @taras-yemets if yours are all merged then we can close this. If you also have a few PRs that you can't merge, I suggest you drop another message to #dev-chat with the list of your PRs.
