### ISSUE TITLE
Update the extension documentation so it's clear that extensions are deprecated

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#40991]
We have a couple of options:

- Keep the extensions as-is with the deprecation notices
- Delete the documentation. However, when we do that, users that are on pre-4.0 instances are also no longer able to easily see the documentation (as public links on sourcegraph.com won't work anymore).
- Change the documentation to make it clear that this is only enabled with `enableLegacyExtensions`
- Delete the documentation but have a new doc page added about `enableLegacyExtensions` with the most useful information from the previous docs

cc @sourcegraph/integrations 

/cc @muratsu @jjinnii @ryankscott

**Comment by ryankscott** [comment]
This is a fun one. For clarity this is the documentation on docs.sourcegraph.com (and anyone who updates beyond 4.0) right?

I don't want to point out the feature flag directly, I'd prefer customers to work with CEs so we know _why_ people are enabling it. 

Option #3 makes the most sense to me but we shouldn't mention the feature flag, just that it's now legacy. I'd also be tempted to move this to the bottom of the sidebar, and/or suffix it with legacy e.g. [LEGACY] Extensions.

**Comment by philipp-spiess** [comment]
> For clarity this is the documentation on docs.sourcegraph.com (and anyone who updates beyond 4.0) right?

Exactly! I assume that at least some of users are accessing the documentation through our web domain for ease of use, even if their on-prem instance is a version behind.

**Comment by vdavid** [comment]
Do we know which docs page our customers use? When you start Sourcegraph with `sg`, it starts the docs site by default, but not sure how customers run it and whether it's in their standard setup workflow to set up a docs page with their instance. Plus, I'm unsure whether we link `docs.sourcegraph.com` or their local docs copy throughout our app, docs, and communication.

If a significant amount of customers use `docs.sourcegraph.com` (which is my assumption), then I agree that we should not delete the docs on extensions, just mark them clearly "deprecated starting 4.0".
I hope we'll soon have time for an effort to make the docs versioned, and then changes like this would be easier.

I agree with Ryan that we shouldn't mention the flag.

**Comment by jjinnii** [comment]
After chatting with @ryankscott, this is what we're thinking at the moment:

1. Keep the extensions as-is with the deprecation noticed EXCEPT fully delete any documentation on authoring new extensions
2. In any menus, preface links to the extensions pages with a badge for "Legacy". I would use either out "Outline" or "Secondary" badge style!

<img width="487" alt="Screen Shot 2022-08-30 at 8 45 19 PM" src="https://user-images.githubusercontent.com/87138876/187428421-1b7ed5f9-a1ac-44f0-ac8f-f08c0f02eefe.png">

What do you think? @philipp-spiess @vdavid

**Comment by vdavid** [comment]
Sounds perfect to me, thanks for thinking this through!

**Comment by philipp-spiess** [comment]
Yeah this makes a lot of sense to me as well. :) I'll rename the title of this issue so that we can use it to track the work needed to change this. We will/need to work on this next week.
