### ISSUE TITLE
Repo sizing

### ISSUE THREAD

**Issue by jjeffwarner** [sourcegraph/sourcegraph#40999]
We need to improve the information we collect around repo sizing. We currently use [this approach](https://docs.sourcegraph.com/admin/monorepo#statistics) but it does not include enough information. Suggested improvements:

1. Heat size is important.
2. A script and/or a Go program, potentially include [git-sizer](https://github.com/github/git-sizer#usage).
3. How to include Perforce information.
4. Should we include history information?

Make sure this work includes an update to the handbook.

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket, please let us know how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
