### ISSUE TITLE
insights: reduce historical enqueuer delay

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#41019]
Until we make substantial improvements to our queueing mechanism, there is a quick win to reduce [the delay between iterations](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/insights/background/historical_enqueuer.go?L124&subtree=true) of the `historical_enqueuer` to something quite small. This is safe now because:
1. All of the work is now processed in this queue and effectively rate limited
2. Work is blocked while the historical enqueuer is processing, so this will not double up.

I propose 30 seconds between cycles for this job.

This will substantially improve the experience for smaller customers that are making all repo insights.

/cc @joelkw @felixfbecker @vovakulikov @unclejustin

**Comment by Joelkw** [comment]
Proposing for post-4.0 cut just to avoid extra changes right before 4.0
