### ISSUE TITLE
Allow to override 2s timeout in API for intentional aggregations

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#41010]
For https://github.com/sourcegraph/sourcegraph/issues/40861, we need to add a boolean GraphQL argument to override/raise the 2s timeout to 60s.

/cc @joelkw @felixfbecker @vovakulikov @unclejustin

**Comment by chwarwick** [comment]
note for implementation: Include updates to the returned failure reason to indicated if, the search timed out with a short timeout that could be extended or if the search timed out with the longer timeout and needs additional filtering to possibly return values.

**Comment by chwarwick** [comment]
closed by #41010
