### ISSUE TITLE
Aggregation by file without query fails with `Panic occurred: runtime error: index out of range [0] with length 0 panic occurred: runtime error: index out of range [0] with length 0`

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#41016]
https://k8s.sgdev.org/search?q=context%3Aglobal+repo%3A%5Egithub%5C.com%2Fsourcegraph%2Fsourcegraph%24+file%3Apackage.json+&patternType=standard&case=yes&groupBy=PATH

Gives the error:

`Panic occurred: runtime error: index out of range [0] with length 0
panic occurred: runtime error: index out of range [0] with length 0`

<img width="277" alt="image" src="https://user-images.githubusercontent.com/10532611/187287828-4ce01c3b-135b-4bbb-bed9-59902845eb0d.png">

/cc @joelkw @felixfbecker @vovakulikov @unclejustin

**Comment by chwarwick** [comment]
I just ran into this issue too, the issue is here.  There is no search pattern I believe this should fail with `UnsupportedPatternTypeErr`:
https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/insights/query/querybuilder/regexp.go?L173-182
