### ISSUE TITLE
using Dockerfile fails because autologin.conf does not exist

### ISSUE THREAD

**Issue by cconcannon** [sourcegraph/sourcegraph#41017]
The Dockerfile referenced in [this line](https://github.com/sourcegraph/sourcegraph/blob/a36a30f46cde240b1df85f48fbd677591eec1944/doc/admin/deploy_executors.md?plain=1#L134) fails to build because `autologin.conf` does not exist.

Can these instructions please be updated so that the required `autologin.conf` file is created prior to building the Docker image with this Dockerfile?

**Comment by eseliger** [comment]
Docs have been updated and a new process makes it that customers don't need to build this manually anymore.
