### ISSUE TITLE
Convert all null strings to null literals on changeset_specs.published

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#41029]
See https://github.com/sourcegraph/sourcegraph/pull/41028 for context, this should be done for 4.1.

**Comment by LawnGnome** [comment]
P1, then?

**Comment by Piszmog** [comment]
To clarify, this Issue is meant to migrate the string null values (`'null'`) in the `changeset_specs.published` column to actual null (`NULL`) in the database?

**Comment by eseliger** [comment]
correct, I messed up there.

**Comment by eseliger** [comment]
P1 or P0, easy thing but should clean it up properly.
