### ISSUE TITLE
Test legacy extension deprecation with native code host integrations

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#41039]
Native code host integrations can be configured in e.g. GitLab on prem and will automatically inject the browser extension code into the code host so that users don't have to load the browser extension.

We need to verify that this loads the proper feature detection code with our changes to the extension API.

To do that:

1. Set up an on prem gitlab version (or use a test instance if you find any)
2. Configure native code integrations and point it to an instance with extensions disabled (soon S2)
3. See if it works 

/cc @muratsu @jjinnii @ryankscott

**Comment by vdavid** [comment]
Update:
- [x] I've found a GitLab on-prem deploy at https://gitlab.sgdev.org (l/p in 1Password)
- [x] Went to settings (following [this guide](https://docs.gitlab.com/ee/integration/sourcegraph.html#configure-your-gitlab-instance-with-sourcegraph)) and saw that it's already set up with `https://k8s.sgdev.org/`
- [x] Switched the two flags on k8s
- [x] Found no real repo added to our GitLab? So added sourcegraph/sourcegraph
- [ ] Still waiting for the import to finish...
- [ ] Final step is to open the repo on GitLab and see if it works well.
- [ ] Cleanup: remove my personal GitHub access token from our test GitLab instance.

**Comment by vdavid** [comment]
Hmm, @philipp-spiess, I don't see code intel appear in GitLab. See this [1-min Loom](https://www.loom.com/share/e16e9993a0b540c4b02d3afe94ab4eea)

**Comment by philipp-spiess** [comment]
I noticed two things:

- The setting was enabled to block Sourcegraph on private code (but disabling this didn't change it)
- I can not find the repo indexed on k8s.sgdev.org (only `/github.com/sourcegraph/sourcegraph-jetbrains` so the copy hosted on GitHub)

**Comment by philipp-spiess** [comment]
Okay now the issue seems that the repo is not indexed in Sourcegraph:
 
![Screenshot 2022-09-08 at 16 37 29](https://user-images.githubusercontent.com/458591/189150943-060664f9-a78c-4882-a2d6-cafb72f9bbda.png)

**Comment by philipp-spiess** [comment]
I’m kinda of worried since it doesn't fetch the new endpoint to check for the `enableLegacyExtensions` flag cc @taras-yemets 🤔 But I think we should try to import the repo on k8s before we jump to any conclusions.

**Comment by philipp-spiess** [comment]
I think this needs some more attention tomorrow 🤔 

![Image](https://user-images.githubusercontent.com/458591/189184845-c92e10b8-6e03-4424-92c0-8e2a95daf3f7.png)

**Comment by philipp-spiess** [comment]
I think we have a bigger problem here because the code for the integration is bundled with the GitLab release and not downloaded from Sourcegraph. So this is pretty outdated 🤔 

![Image](https://user-images.githubusercontent.com/458591/189185387-089af2e0-4122-49bc-b41d-744601e973b4.png)

**Comment by philipp-spiess** [comment]
Okay yeah this is bundled 😐 https://sourcegraph.com/gitlab.com/gitlab-org/gitlab/-/blob/config/webpack.config.js?L585-590

**Comment by philipp-spiess** [comment]
The bundled version is also over a year old 😬  https://snyk.io/advisor/npm-package/@sourcegraph/code-host-integration

**Comment by vdavid** [comment]
> * The setting was enabled to block Sourcegraph on private code (but disabling this didn't change it)
> * I can not find the repo indexed on k8s.sgdev.org

Ah, okay, my understanding of what GitLab did was a bit different. I thought GitLab would just clone the repo. As Git itself is decentralized, I thought GitLab's “import” would just add another peer to the public repo and that's it.

Also, thanks for the rest of your research, we'll figure out something tomorrow.

**Comment by vdavid** [comment]
Summarizing and capturing the results of our [Slack convo](https://sourcegraph.slack.com/archives/C01T0BL4EFN/p1662658196974949) (edits for clarity):

@muratsu: "github & bitbucket are not native integrations, they go through the bext."

@philipp-spiess:
"Our GitLab integration is using a bundled special entry point for us that we ship via npm ([sourcegraph/code-host-integration](https://www.npmjs.com/package/@sourcegraph/code-host-integration)).
The version GitLab is injecting is over a year old.
We can’t control the GitLab upgrade path so this might be a potential problem.
We may be able to “disable” extensions by incepting the server side config call  and filtering out anything that is not necessary for code intel We’ll likely need to make the extensions registry available for this use case.
We have zero control over old GitLab versions (not even GitLab has any guarantees). We’ll probably need a much much longer period where we keep some of these APIs alive.
I’ll look into exactly what the contract is between the code host integration and a Sourcegraph instance."
