### ISSUE TITLE
insights: pings on proactive/excessive limit timeouts (stretch)

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#41033]
From this comment, we want to also collect pings on: 

> proactive limit hit
> proactive limit success 
> explicit limit hit
> explicit limit success

This will tell us what % of searches are successfully served by our current defaults. 

Added to the [RFC here](https://docs.google.com/document/d/1v6-T0UTGfQ1H7SBybuNXlPFAm4Ilu7r1aU23p_5MhrE/edit#bookmark=id.1tikj1ozcle9). 

/cc @joelkw @felixfbecker @vovakulikov @unclejustin

**Comment by Joelkw** [comment]
Originally suggested here: https://github.com/sourcegraph/sourcegraph/issues/40861#issuecomment-1230577014

**Comment by unclejustin** [comment]
## Implementation details

For each of the following pings, they should be unique by query per session.

Add pings to enum in `aggregation/pings.ts`

### proactive limit hit

Determined by `searchQueryAggregate?.aggregations.__typename === 'SearchAggregationNotAvailable'` and `searchQueryAggregate?.aggregations.type === NotAvailableReasonType.TIMEOUT_EXTENSION_AVAILABLE`

### proactive limit success

Determined by `searchQueryAggregate?.aggregations?.__typename !== 'SearchAggregationNotAvailable'` and `extendedTimeout` is `false`

### explicit limit hit

Determined by `searchQueryAggregate?.aggregations.__typename === 'SearchAggregationNotAvailable'` and `searchQueryAggregate?.aggregations.type === NotAvailableReasonType.TIMEOUT_NO_EXTENSION_AVAILABLE`

### explicit limit success

Determined by `searchQueryAggregate?.aggregations?.__typename !== 'SearchAggregationNotAvailable'` and `extendedTimeout` is `true`

**Comment by vovakulikov** [comment]
Reopen since PR for this issue has been reverted https://github.com/sourcegraph/sourcegraph/pull/42522

**Comment by coury-clark** [comment]
@leonore whats the status of this? You reopened this most recently but it isn't clear if there is actually work to do here.
