### ISSUE TITLE
Check all tooltips in batches if they still work

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#41030]
I discovered that a couple are throwing errors and don't render properly anymore. The fix seems to be to switch to `svgPath`.

**Comment by LawnGnome** [comment]
P0, given the importance of tooltips to some parts of our UX?

**Comment by courier-new** [comment]
As part of this ticket, perhaps any elements where we deem the tooltips to be critical should also receive a storybook story with `defaultOpen={true}`, so that if we one day turn Chromatic coverage back on for them, we can make sure there aren't regressions!
