### ISSUE TITLE
conf: EXTSVC_CONFIG_FILE does not override if external services already exist

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#4108]
I think this was an oversight when the feature was added. We retained the behaviour we used for dev configs, were we only wanted to apply the ext-svc once.

https://github.com/sourcegraph/sourcegraph/blob/v3.4.0-rc.5/cmd/frontend/internal/cli/config.go#L99-L101

From https://github.com/sourcegraph/sourcegraph/pull/4017

**Comment by slimsag** [comment]
Thank you for filing!
