### ISSUE TITLE
gitolite.exclude description and example does not match JSON schema

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#4109]
Reproduced on 3.4.0-rc4

1. Add or edit a Gitolite external service
2. Try to specify an `"exclude"` entry using a `pattern` (as suggested by the description and examples)
3. Witness `pattern` is not allowed by the JSON schema, external service cannot be saved:

![image](https://user-images.githubusercontent.com/1741180/57930089-5a3ef580-78b5-11e9-96a6-58f5bfecdcf6.png)

**Comment by keegancsmith** [comment]
Thanks for reporting! Just fixed this. We accidently included this behaviour in the schema.
