### ISSUE TITLE
Guided batch changes tutorial video

### ISSUE THREAD

**Issue by adeola-ak** [sourcegraph/sourcegraph#41099]
Requested by Bachi Degli Innocenti for social media purposes, a 2-3 minute voiceover video with the following specs & structure:
 
Size: 16:9 (1920x1080)
File format: .mov or .mp4

Video structure:
Intro yourself
What is batch changes
How to implement them
Outtro - Call to action "Try it today in Sourcegraph"

**Comment by eseliger** [comment]
This is in "done" but still open, is it done yet? If so please close it :)
