### ISSUE TITLE
RFC 619: Move ✨policies resolvers types ✨ from graphqlbackend package to Policies transport layer

### ISSUE THREAD

**Issue by Numbers88s** [sourcegraph/sourcegraph#41131]
Move ✨ policies resolvers types ✨ from graphqlbackend package to Policies transport layer as part of our ongoing efforts to implement RFC 619 Code Intelligence Platform.

**Comment by efritz** [comment]
Fixed by https://github.com/sourcegraph/sourcegraph/pull/41596.
