### ISSUE TITLE
when gitMaxCodehostRequestsPerSecond=0, repo-updater logs are spammed with rate: Wait(n=1) exceeds limiter's burst 0

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#41152]
- **Sourcegraph version:** 3.42
- **Reported by:** https://github.com/sourcegraph/accounts/issues/6716 [via Slack](https://sourcegraph.slack.com/archives/C01D50MSA7L/p1661862070324559?thread_ts=1661364672.754819&cid=C01D50MSA7L)

#### Steps to reproduce:

1. Set `gitMaxCodehostRequestsPerSecond` = 0 in site configuration [[docs](https://docs.sourcegraph.com/admin/config/site_config#gitMaxCodehostRequestsPerSecond)]
2. Check `repo-updater` logs

#### Expected behavior:

`repo-updater` logs a message but not repeatedly

#### Actual behavior:

`repo-updater` logs are spammed with `rate: Wait(n=1) exceeds limiter's burst 0`

If would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are not [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

/cc @jplahn @ryphil

**Comment by jplahn** [comment]
Nice one @ryanslade !
