### ISSUE TITLE
otel: prevent sampling processor to discard traces that are explicitly selected for tracing

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#41177]
#41176 added support for the probabilistic sampling processor, but this comes with an issue: if we enable selective tracing and that we explicitly ask for a request to be traced, chances are that the collector will still discard the trace regardless of that flag. 

This is counter-intuitive at worse, surprising at best, so it would be great to get this fixed in the future. 

The most probable course of action is rely on the `sampling.priority` tag that we could add on spans to signify that this request should not be discarded. See https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/probabilisticsamplerprocessor for more informations about this.

**Comment by bobheadxi** [comment]
> The most probable course of action is rely on the sampling.priority tag that we could add on spans to signify that this request should not be discarded.

This sounds like a good approach! Setting the ShouldTrace context value can also set this tag at the same time
