### ISSUE TITLE
Fix typos in extensions analytics page

### ISSUE THREAD

**Issue by ryankscott** [sourcegraph/sourcegraph#41182]
There's a collection of small typos / changes needed to be made:

## Instances of VSCode which needs to be VS Code ##
<img width="322" alt="Screen Shot 2022-09-01 at 11 18 45" src="https://user-images.githubusercontent.com/2660760/187879087-3636bf73-139c-4292-806b-3c67bfae5e9f.png">

<img width="319" alt="Screen Shot 2022-09-01 at 11 18 56" src="https://user-images.githubusercontent.com/2660760/187879138-98103265-fdd6-4c98-adb9-b8d170c2a7a9.png">
 
<img width="891" alt="Screen Shot 2022-09-01 at 11 22 52" src="https://user-images.githubusercontent.com/2660760/187879980-cdb33afb-7d3d-443a-a690-b4bb0fd32496.png">

<img width="747" alt="Screen Shot 2022-09-01 at 11 23 36" src="https://user-images.githubusercontent.com/2660760/187880146-72e88385-3f44-4101-a86f-f6ecb9ed5a20.png">

## Other typos / wording changes ##

- This should be date, rather than time:
<img width="729" alt="Screen Shot 2022-09-01 at 11 19 04" src="https://user-images.githubusercontent.com/2660760/187879175-e34cb385-4ee5-4e81-bd7a-c64b069dafb4.png">
- Unique rather than Uniques
<img width="470" alt="Screen Shot 2022-09-01 at 11 19 19" src="https://user-images.githubusercontent.com/2660760/187879235-3836cb10-a99e-49f8-a8ed-1217f2dc39bd.png">

- This needs to be reworded:
<img width="603" alt="Screen Shot 2022-09-01 at 11 19 42" src="https://user-images.githubusercontent.com/2660760/187879322-cee49b0a-790a-48cd-916a-e8983757fa17.png">
I'd suggest:

> We’ve calculated the time saved by reducing context switching between tools.

- "Searches from JetBrains across all of your company's code **across code hosts**, without locally cloning repositories or complex scripting." should be:

> "Searches from JetBrains IDEs across all of your company's code without locally cloning repositories or complex scripting."

- "Searches from VS Code across all of your company's code **across code hosts**, without locally cloning repositories or complex scripting." should be:

> "Searches from VS Code across all of your company's code without locally cloning repositories or complex scripting." should be:

## Other ##

- Why are the default "Minutes per" different for JetBrains and VS Code (1.5 vs. 3)

<img width="416" alt="Screen Shot 2022-09-01 at 11 20 43" src="https://user-images.githubusercontent.com/2660760/187879531-7f03325b-ef02-4924-8e49-8057ecb5919f.png">

- What does "Minutes per" mean? Should that be "Minutes saved per event"?

- VS Code extension link goes to the browser extension page, it should go to https://docs.sourcegraph.com/integration/editor
<img width="1420" alt="Screen Shot 2022-09-01 at 11 23 25" src="https://user-images.githubusercontent.com/2660760/187880105-56d165eb-0057-43b0-a339-d72e10008af0.png">

- Browser extension link goes to the IDE page, it should go to https://docs.sourcegraph.com/integration/browser_extension
<img width="1349" alt="Screen Shot 2022-09-01 at 11 24 47" src="https://user-images.githubusercontent.com/2660760/187880456-e8888d57-2475-4cbf-8cb1-e01a307e69a6.png">

FYI @thenamankumar  @erzhtor  @ryphil @rrhyne

**Comment by rrhyne** [comment]
Thanks Ryan!
