### ISSUE TITLE
insights: intermediate aggregation chart labels are skipped

### ISSUE THREAD

**Issue by leonore** [sourcegraph/sourcegraph#41191]
<img width="265" alt="Screenshot 2022-09-01 at 13 47 11" src="https://user-images.githubusercontent.com/29406849/187917340-96d18abc-d2ff-445e-803c-4db10a623743.png">

[Example search that triggered this](https://sourcegraph.sourcegraph.com/search?q=context%3Aglobal+TODO%5B%28%5D%28%5Cw%2B%29%5B%29%5D+count%3Aall&patternType=regexp&groupBy=CAPTURE_GROUP)

/cc @joelkw @felixfbecker @vovakulikov @unclejustin

**Comment by chwarwick** [comment]
I think this is covered in https://github.com/sourcegraph/sourcegraph/issues/40766

**Comment by leonore** [comment]
ah my bad, I missed that when reading through it. closing then. to any reader: feel free to reopen to use as a scoping issue

**Comment by felixfbecker** [comment]
I think it wouldn't be a bad idea to keep this open separately because it was descoped out of #40766 and the PR that will close #40766 does not fix it

**Comment by vovakulikov** [comment]
I think I don't understand this issue comment. @leonore what behave do you expect here? render full set of labels? If yes I think it's not optimal from UI point of view and this also violates a11y requirements about dense of text and UI elements on the page. For example, the chart above has all original set of labels and it's not easy to read these labels. (changing Font size of them also introduce problems)

<img width="416" alt="Screenshot 2022-09-03 at 22 00 49" src="https://user-images.githubusercontent.com/18492575/188284717-17c18721-5d62-463c-bde9-699c8c2cd36e.png">

The labels are still accessible through tooltip see I think this it should be no problem that we skip intermediate labels on the chart in the sidebar panel.

**Comment by leonore** [comment]
@vovakulikov I see what you mean. but when I saw my example above it looked like the UI was broken, rather than it was a choice for additional readability. I think it's because the rotation looked odd as well

I don't necessarily have a solution to offer, and it might be something we want to fix post 4.0

**Comment by vovakulikov** [comment]
@leonore I will try to look in rotation logic to make it more robust. Just FYI, for label skipping problem we have a separate issue where we have a conversation about this problem https://github.com/sourcegraph/sourcegraph/issues/39935

**Comment by AlicjaSuska** [comment]
@vovakulikov I agree that rotation could be improved here. I propose we link this issue to #39935 and keep the discussion there.
