### ISSUE TITLE
Add a global "repositories are cloning"/"Sourcegraph is not ready yet" indicator

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#4120]
[As discussed in Slack](https://sourcegraph.slack.com/archives/C0C324C91/p1558008005125800), I'm quoting myself here:

> I wish we had a global "repositories are cloning"/"sourcegraph is not ready yet" indicator. After setting up a new Sourcegraph instance and adding your GitHub repositories (which can easily be in multiple hundreds if you use `affiliated` as `repositoryQuery`) it's pretty disheartening that you don't get search results for things you _know_ have to be there. And if you're a new user you don't know that you can check "Repositories"

Also including @sqs's reply:

> the fact that some repos are unavailable is shown very diminutively in the search results header, but basically everyone misses that. So we should remove that and treat "repos currently being cloned" as a global notice, not a per-search-results-page notice. (This makes sense because it would also affect code browsing and cross-references, not just search.) 

I also found that this ticket is highly related to:

- https://github.com/sourcegraph/sourcegraph/issues/3063
- https://github.com/sourcegraph/sourcegraph/issues/4120

**Comment by sqs** [comment]
@christinaforney and I started on this yesterday and she will own it

**Comment by mrnugget** [comment]
Here's what @christinaforney and I came up with for a first, minimum-viable version of this feature, after discussing scope and rough idea of implementation with @tsenart and @keegancsmith:

### Scope

This first iteration of a "global status indicator" will just be a "cloning status indicator" that tells site-admins via an icon in the navbar how many repositories are currently cloning or whether all repositories have been cloned.

## UI

* Icon in the navbar
  * Only shown to site-admins in this first iteration!
  * Between "Explore" and the action menu in the navbar
  * Inactive (greyed out) when nothing is cloning in the background
    * OK icon
  * Active when repositories are cloning
    * Spinner
* When you click on icon
  * If nothing is cloning: "All repositories cloned"
  * If cloning: "Currently cloning $X repositories"
    * Click on "Currently cloning..." and you get redirect to the list of repositories, with the "cloning" filter activated

## Implementation

All of this is just a rough first draft and especially the naming and schema of the objects is subject to change, because the difficulty here is to create something that's not over-architected for our minimal-viable usecase but at the same time open for expansion for future additions.

* New `repo-updater` endpoint: `/status-messages`
* If something is cloning, this endpoints returns one status message:

```json
[
  {"type": "cloning_in_progress", "message": "Currently cloning 5 repositories..."}
]
```

* If nothing is cloning the array is empty (for now, can be extended later)
* When the request to `repo-updater` is made, `repo-updater` asks `gitserver` for the number of currently cloning repositories
* `gitserver` has that number in memory
* We need a `/currently-cloning` endpoint for `gitserver` that returns the number of currently cloning repositories
* GraphQL API gets a new `statusMessages` query that returns the aggregated status messages from all services (in this first iteration it just asks `repo-updater` for status messages)
* `web` then polls the GraphQL API and updates icon accordingly
  * if there is a `cloning_in_progress` message in there it shows the message and links to the list of repositories with `cloning=true` filter
  * if there is no `cloning_in_progress` message it shows the `ok` symbol

## Future expansion

* Show status messages for different code hosts ("Could not fetch repositories from GitHub", "Gitlab configuration invalid didn't yield any repositories"...)
* Show status messages for indexing service ("Currently indexing 30 repositories...")
* Show status messages for syncing status ("Synced GitHub Enterprise repository metadata...")
* ...

**Comment by mrnugget** [comment]
With https://github.com/sourcegraph/sourcegraph/pull/4861 merged, I'm going to close this and we can create follow-up tickets for extending the status indicator.
