### ISSUE TITLE
VSCE: Unrecognized patternType on versions 3.39.0 and under

### ISSUE THREAD

**Issue by gabtorre** [sourcegraph/sourcegraph#41236]
- **Sourcegraph version:** 3.39.0
- **Platform information:** VSCE version 2.2.9

#### Steps to reproduce:

1. Run a query on the Sourcegraph VSCode Extension v2.2.9 and a private Sourcegraph instance v3.39.0 and under.

#### Expected behavior:
The query resolves successfully.
<img width="816" alt="Screen Shot 2022-09-01 at 4 52 12 PM" src="https://user-images.githubusercontent.com/69164745/188031212-3c933e94-6c05-4215-8b8a-9c7eb6556ce0.png">

#### Actual behavior:
There's an `Unrecognized patternType` error.
<img width="865" alt="Screen Shot 2022-09-01 at 4 48 48 PM" src="https://user-images.githubusercontent.com/69164745/188030943-cccbdbfb-267c-4c90-a077-00fbaca82a02.png">

#### Workaround:
Sourcegraph VSCE Version 2.2.7 works as expected on Sourcegraph v3.39.0 and under.

/cc @muratsu @jjinnii @ryankscott

**Comment by digitalmaster** [comment]
Same here: 
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/1279335/189906430-5efc95dc-08bd-4074-8396-d960740c60c7.png">

**Comment by nfearnleypro** [comment]
![image](https://user-images.githubusercontent.com/111157142/192336032-b3105b7f-8845-4972-bd88-f33d713de7da.png)

Sourcegraph: 3.37.0
VSCode Extension: 2.2.10
