### ISSUE TITLE
insights: add 4.0 pings to our pings documentation

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#41237]
Important to do this while it's still fresh and so we have a SSOT reference in the future! Here is the docs page: https://docs.sourcegraph.com/dev/background-information/insights/code_insights_pings 

We can just add them to the bottom. Perhaps it might be nice to add them as a separate #section since they are all related to this rather separate feature. 

/cc @joelkw @felixfbecker @vovakulikov

**Comment by leonore** [comment]
closed by https://github.com/sourcegraph/sourcegraph/pull/41503, not adding any new pings so far
