### ISSUE TITLE
New version available "Reload to update" button lost button styles (browser native button look)

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#41230]
When the browser bundle is outdated and a request to load a chunk fails, we show this page:

<img width="408" alt="image" src="https://user-images.githubusercontent.com/10532611/188003284-e7f74544-52c8-4e79-a543-16d8a87f4872.png">

Notice how the button lost our Wildcard button style.

/cc @taylorsperry @muratsu

**Comment by valerybugakov** [comment]
@felixfbecker, thanks for the report!

@gitstart-sourcegraph, we need to move `<WildcardThemeContext.Provider value={WILDCARD_THEME}>` above the `                <ErrorBoundary location={null}>` in the `SourcegraphWebApp` component to fix this. Let's check other applications too. They might have a similar problem.
