### ISSUE TITLE
user-management: update "User" column to show detailed info (displayname, email) on hover

### ISSUE THREAD

**Issue by erzhtor** [sourcegraph/sourcegraph#41247]
https://www.figma.com/file/mmWwgzzqTmpLsxwmiiZwfE/Admin-analytics?node-id=2564%3A11976

/cc @muratsu @a-bergevin

**Comment by malomarrec** [comment]
Hey @erzhtor, this issue didn't have a team label. Given you created it, I assigned you and added your team label. Feel free to unassign yourself. If this is not the right label, can you make sure to add the right one?

**Comment by erzhtor** [comment]
Hey @malomarrec! Sorry for not adding the label. I thought it was enough to add to the GitHub Board.

I've added `team/admin-analytics` label, and @thenamankumar is already working on the issue, I believe.
