### ISSUE TITLE
A deleted code host continues to run a sync job until completion

### ISSUE THREAD

**Issue by indradhanush** [sourcegraph/sourcegraph#41255]
If a external service sync job is running and the external service is deleted, the sync job continues to be in `processing` state. 

**Expected state:**

The sync job is aborted

**Steps to reproduce**

1. Add a code host connection with enough repositories that takes at least a few minutes (a reasonably open `repositoryQuery` may do the trick)
2. Wait or trigger a manual sync from the edit code host connections page
3. Delete the code host connection while the sync job is running

Issue originally noticed in a bitbucketserver connection.

**Comment by indradhanush** [comment]
Didn'g see this immediately after deletion but after some time the sync job fails with the failure message:

```
fetching external services: external service not found: 2
```

**Comment by mintbomb27** [comment]
Hey! Can i take this up?

**Comment by indradhanush** [comment]
@mintbomb27 Sure thing!

**Comment by omerisildak** [comment]
Can I try this too?

**Comment by mrnugget** [comment]
Has been removed in #44549, I think
