### ISSUE TITLE
Write docs about migrated extensions

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#41262]
Since those are now in the product, we should move the documentation from the extension repos into our product docs.

- Open in editor: https://github.com/sourcegraph/sourcegraph/pull/41105
- Git extras
- Search export
- Go import search

/cc @muratsu @jjinnii @ryankscott

**Comment by ryankscott** [comment]
FYI @jjinnii and I reviewed the other extensions and we aren't going to add documentation for the other features. This is because they don't require any configuration, the previous pages didn't have much content outside screenshots and they *should be* relatively straight forward to use.
