### ISSUE TITLE
[ReOps] Create Research Panel

### ISSUE THREAD

**Issue by meglynst** [sourcegraph/sourcegraph#41267]
See RFC 660: https://docs.google.com/document/d/1xEPEozZwaRXvbUnjbF2waWwcTd69wmGFf7lIRNzn3_s/edit?usp=sharing

- [x] Approve RFC
- [x] Approve sign up form
- [x] Update sign up form
- [x] Create form disbursement plan with Sales and CE teams
- [x] Meet with Marketing
- [x] Add details about adding details to NPS
- [ ] Reach out to Front End Platform to ask about creating banner

Update Sept 1, 2022: 
Joel Kwartler suggests also creating feedback channels
Ajay Uppaluri suggest making one channel for feedback from multiple companies

Sales: 
- Add information about panel and link to form to deployment package/schema
- Append form link to surveys going forward
- Have AEs send to every admin

CE:
tbd

**Comment by malomarrec** [comment]
Hey @malomarrec, it looks like this issue was created by someone outside Sourcegraph. Assigning you to triage it! Please answer and route to the right team by adding their team label, then **remove** the `triage-bot/needs-triage` label
