### ISSUE TITLE
[ReOps] Setting up research repository

### ISSUE THREAD

**Issue by meglynst** [sourcegraph/sourcegraph#41270]
See RFC 712: https://docs.google.com/document/d/1nFKpK9NmMbTSu4KcWCQBXIp88hc9P7UJ5kyq2eUaQaw/edit#

- [x] Approve RFC
- [x] Upgrade Markup
- [x] Establishing global taxonomy
- [x] Importing past research
- [x] Create Loom to explain Dovetail
- [x] Add Dovetail handbook page
- [x] Invite users
- [x] Create Dovetail folders for each feature team [updated re-org Oct 31]

**Comment by malomarrec** [comment]
Hey @ryphil, just a reminder to triage this issue and remove the triage-bot/needs-triage label when you're done!

**Comment by meglynst** [comment]
@malomarrec @ryphil This issue was made Megan St. Andrew (me) who currently works at Sourcegraph.
