### ISSUE TITLE
RFC 697: Testing - CSE user story

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#41287]
See [RFC 697: Multiple version upgrades](https://docs.google.com/document/d/1eNiwzWZmfpvzFhs9IDcM7Sbchv_Hm8Uj-6bI-3TDlvg).

This PR tracks general testing of multi-version upgrades as well as CSE-specific test scenarios. 

See the [testing strategy announcement in slack](https://sourcegraph.slack.com/archives/C02KZ941RNX/p1660748283465879).

**Core story**:

1. Run a search for the `sourcegraph/sourcegraph` repository
2. Search for the term `GetUploads` on `HEAD`
3. Open a result and ensure the file renders
4. Check that file sidebar and symbols sidebars are populated
5. Ensure code navigation (go to definition and find references) work as expected
6. Repeat steps 2-5 on an old tag to ensure that unindexed paths are also functional
7. Visit each site-admin page to ensure there are no obvious error banners

**Instructions**:

The following issues provide detailed instructions for upgrading a single-server image distribution of Sourcegraph:

- #40702
- #40700
- #40703
- #40704
- #40701

Similar instructions should be followed on the `cse-aws` and `cse-k8s` instances.

🍍 There are now [docs on how to upgrade](https://github.com/sourcegraph/sourcegraph/pull/41067) available to follow.

**Comment by airamare01** [comment]
Hi @efritz ,I noticed that this is more docker leaning testing. Would you recommend it if I attempted to follow these steps on say, minikube?
Any particular reason why the preference is a single docker server? A hunch suggests that this is because of the databases but would appreciate it if you could please confirm.

**Comment by efritz** [comment]
Sorry if the ticket was unclear. I linked to the product team tickets which used the single docker image to make it easy to test application level but not infrastructure level testing.

This ticket asks specifically to update two cse clusters to a newer version. If there are other distribution methods you'd like to test on new or existing clusters please do so!

The more coverage we get on testing this the higher our confidence well catch odd issues before a user does so we can either fix or find a workaround for those that encounter it.

The bigger the spread of testing the better, and minikube would be a completely valid test setup.

**Comment by airamare01** [comment]
Thanks, be back with my findings soon!

**Comment by airamare01** [comment]
I'm completely confused. Hit several blockers with @topebali @Rhia2 on sync @efritz on k8s and docker-compose

Could we jump on a quick sync sometime?

**Comment by efritz** [comment]
I can make some time this week. What blockers did you hit?

**Comment by mibali** [comment]
Error got when trying to run the migrator command.

```
Status: Downloaded newer image for sourcegraph/migrator:3.43.1
❗️ An error was returned when detecting the terminal size and capabilities:

   GetWinsize: inappropriate ioctl for device

   Execution will continue, but please report this, along with your operating
   system, terminal, and any other details, to:
     https://github.com/sourcegraph/sourcegraph/issues/new

✱ Sourcegraph migrator v3.43.1
{"SeverityText":"FATAL","Timestamp":1662474888308930409,"InstrumentationScope":"migrator","Caller":"migrator/main.go:21","Function":"main.main","Body":"upgrading \"frontend\" from \"3.39.0\" to \"3.43.1\" is not allowed, please refer to https://docs.sourcegraph.com/admin/updates#update-policy","Resource":{"service.name":"migrator","service.version":"3.43.1","service.instance.id":"f1e2b68b-a199-49c5-adf1-f9f27783e468"},"Attributes":{}}
```

**Comment by airamare01** [comment]
Just for context, we upgraded `cse-k8s `from `3.42.2` to `3.43.1`

**Comment by efritz** [comment]
@airamare01 can you use `sourcegraph/migrator:insiders` rather than` 3.43.1`? `sourcegraph/migrator:insiders@sha256:8c93c6f6c6477721ad9fddf25bf5967cb228ce45a83eeecd281f0538f838faa4` looks like the latest build.

**Comment by efritz** [comment]
> Constantly hit migrator command not found

 @airamare01 Just hit me: are you putting `migrator` explicitly in the quoted string? The migrator should be the entrypoint so you only want to change the subcommand, not the full command as it would be invoked by something like bash.

**Comment by efritz** [comment]
Before the offsite @DaedalusG and I checked out the k8s and compose instances and the upgrades were successful.
