### ISSUE TITLE
insights: the "additional bars" indicator is way far from the chart on s2, in both simple UI mode and normal

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#41283]
See: 
![Screen Shot 2022-09-02 at 11 02 44 AM](https://user-images.githubusercontent.com/11967660/188222165-ca8d9949-4453-4890-bb98-92ee6c3f7258.png)

![Screen Shot 2022-09-02 at 11 01 58 AM](https://user-images.githubusercontent.com/11967660/188222174-875b7eb3-6a62-44db-aa5b-d8bc3917aefc.png)

In both cases the "+5147" is way too high and too far removed from the chart. 

/cc @joelkw @felixfbecker @vovakulikov

**Comment by vovakulikov** [comment]
Close it since it's solved in https://github.com/sourcegraph/sourcegraph/pull/41212
