### ISSUE TITLE
Aggregation: Fix copy of missing groups tooltip

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#41291]
Follow up from https://github.com/sourcegraph/sourcegraph/pull/41212#discussion_r960889857

We need to update copy. Suggested copy is 
>There are ${missingCount} more groups that are not shown.

Also fix the copy pluralization
>we need to handle pluralization for the case of missingCount being 1: In that case, it needs to say "There is 1 more group that is not shown."

/cc @joelkw @felixfbecker @vovakulikov

**Comment by Joelkw** [comment]
@vovakulikov thanks for filing this! Can we make the copy instead slightly shorter, to: 

> There are ${missingCount} more groups not shown.

**Comment by vovakulikov** [comment]
Yes, we can, and for one group, it would be
> There is one more group not shown.
