### ISSUE TITLE
Users.Delete does not soft-delete data from 'settings' table; Why does settings table have user relationship?

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#413]
When [deleting a user](https://sourcegraph.sgdev.org/github.com/sourcegraph/sourcegraph@9f467018d92c6e2b046f9950015eddb592da7e88/-/blob/cmd/frontend/db/users.go#L356:17), we fail to soft-delete settings data created by the user. This appears in two fields of the `settings` table:

```
sg=# \d+ settings;
                                                          Table "public.settings"
     Column     |           Type           |                       Modifiers                       | Storage  | Stats target | Description 
----------------+--------------------------+-------------------------------------------------------+----------+--------------+-------------
 id             | integer                  | not null default nextval('settings_id_seq'::regclass) | plain    |              | 
 org_id         | integer                  |                                                       | plain    |              | 
 contents       | text                     |                                                       | extended |              | 
 created_at     | timestamp with time zone | not null default now()                                | plain    |              | 
 user_id        | integer                  |                                                       | plain    |              | 
 author_user_id | integer                  | not null                                              | plain    |              | 
```

1. Question: What is the difference between `user_id` and `author_user_id`?
2. Question: Why does the settings table need record of author / user? This is not the only location where this has caused us trouble, e.g. @chrismwendt had to add special hacks to handle new instances due to this: https://github.com/sourcegraph/sourcegraph/blob/master/cmd/frontend/internal/bg/langservers.go#L41-L43
3. Question: If we do need to keep user relationship here, what does it mean for settings to be authored by a user who no longer exists? When a user is deleted, do those settings get deleted?

@sqs I think you implemented significant portions of our settings arch, can you answer the above questions?

**Comment by sqs** [comment]
I believe @ggilmore built this originally but I can answer. 

1) author user is the person who edited it. User or org id is who the settings are for, and exactly 1 of them is non-null. 
2) to track edit history for debugging or reverting. This has been useful a few times for debugging for me. @keegancsmith recommended tracking history when this was originally built.
3) If the author user is hard deleted (but the subject user or org remains), it would still be nice to know who did it, but it’s not important. It could just make the author user id value null.

**Comment by slimsag** [comment]
@sqs it looks like you fixed this for hard deleting, but not for soft deleting. There is still nothing here deleting settings references when doing soft deletes:

https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/db/users.go#L356-418

**Comment by sqs** [comment]
It retains the foreign key value for auditability but at query time it returns soft-deleted users as nil in Settings.AuthorUserID. I think that’s sufficient.

**Comment by slimsag** [comment]
Ah, I missed that, got it.
