### ISSUE TITLE
insights: search for repo without query allows aggregation by file

### ISSUE THREAD

**Issue by leonore** [sourcegraph/sourcegraph#41318]
see https://sourcegraph.sourcegraph.com/search?q=context%3Aglobal+repo%3Asourcegraph%2Fwebloop&patternType=standard&groupBy=path

we allow aggregation by file even though there will never be any results. we should consider implementing a query check such that if the only queries are for repos we don't allow aggregations by file

issue is exacerbated by the fact that no results just returns empty square (so it looks odd)

/cc @joelkw @felixfbecker @vovakulikov

**Comment by leonore** [comment]
this is made more complicated by contexts being passed in and allowing queries in them- so we'd need to unwrap contexts on each hit i.e. hit the database, so I'd be more inclined to pass on this issue, or at least only check if we're in global context

**Comment by coury-clark** [comment]
I'm not sure I like the approach of trying to determine this from the query. I realize that may mean we aren't always prescriptive about what aggregations are possible, but I think _in reality_ that is an outcome we will never exactly reach. 

Given we are always aggregating on an exhaustive result set, what if we inspect the contents of the results to make some determinations? Its not exactly trivial but should be feasible to produce some information about what can be aggregated based on the results.

I'd also suggest that maybe this just needs design / UI solutions, some kind of "no results" copy. Ultimately I think the most important thing would be to surface feedback to the user so they can modify their query. For example:

<img width="282" alt="image" src="https://user-images.githubusercontent.com/5090588/188687132-4cc46254-6acb-4c37-895b-ff1e28b1374e.png">


Pinging @AlicjaSuska and @vovakulikov about the possibility of adding some helpful UI text here?

**Comment by Joelkw** [comment]
@leonore I'm closing this just to keep the board clean/scoped for now, but feel free to reopen and put in our "backlog" status (instead of TODO) and tagged with no milestone if you want to preserve it. Thanks for filing!
