### ISSUE TITLE
Git blame UI review improvements 

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#41314]
UI review for issue #40615. Necessary to close #38377 :

**Edge cases that @taras-yemets raised:**

- [x]  "Git blame column with Codecov line decorations line background on hover conflict ([Loom](https://www.loom.com/share/44bb0d3ec655455a9a730ffd4a61fd71)). This kind of conflict may happen with any extension which changes line colors. Customers with enableLegacyExtensions experimental feature flag enabled are affected."
  - As this only impacts customers with the legacy extensions enabled _and_ have to enable both CodeCov and blame, I think a minimal effort solution is best here. I think your first suggestion that blame highlight takes precedence over other extensions is sufficient, as it's our top-used extension based on our current data. 
- [x] "There is a gap between the blame decoration and the popover. When there are multiple lines in a row with decorations and the user hovers over one of them and then tries to hover over the popover, they should move the cursor over the code area, but not over the blame column, as the previous line decoration will trigger opening its popover. Moving the cursor over the code area may trigger showing the code-intel popover, so we may end up with two popovers ([Loom](https://www.loom.com/share/82364b7d2bf64043bfa07316ec207495))."
  - This is less an edge case, but poor UX of how the blame popover interacts with the popover. I'm [seeing that there's a latency](https://www.loom.com/share/330439ac77fd4750850e6ceed8f5f705) in the blame popover disappearing when a user's cursor has moved outside of the blame column, which is why there's an overlap with the code intel popover. Is it possible for us to instantly close the blame popover if a user's cursor moves outside the blame column? 

**Additional UI feedback** 

- [x] The blame popover still looks large when used alongside the code intel popover. Having trouble inspecting the font sizes of the popover using the inspect tool ☹️ , could someone double-check the styling?
<img width="1115" alt="Screen Shot 2022-09-05 at 8 18 48 PM" src="https://user-images.githubusercontent.com/87138876/188438649-97c0f1ad-35ab-4e72-a4cc-f117dc6e002d.png">
<img width="1112" alt="Screen Shot 2022-09-05 at 8 18 52 PM" src="https://user-images.githubusercontent.com/87138876/188438705-3ca302f9-d58c-41cc-a6d1-576f89b3a68b.png">

- [x] You can also see in the above screenshots that the positioning of the popover is different from the code intel popover. The code intel popover is anchored directly above the hovered token, whereas our blame popover has an ambiguous relationship to the line being hovered. It's standard for popovers on Sourcegraph to be positioned directly alongside the content; could we adjust the positioning? 
- [x]  I've intentionally changed the font of the blame column from the font used for code to our body font family. Blame is content, not code, and it's more consistent with Github as well! 
- [x] On a similar note on font, the row being hovered should transition to [being Label/small-underline](https://www.figma.com/file/7bVINrmqfDpxmLx3gv1uVa/Sunsetting-extensions?node-id=2116%3A22361). 
- [x] (**Open to feedback on this**) I transitioned to using absolute dates for better formatting, but open to feedback on this!

/cc @muratsu @jjinnii @ryankscott

**Comment by philipp-spiess** [comment]
> As this only impacts customers with the legacy extensions enabled and have to enable both CodeCov and blame, I think a minimal effort solution is best here. I think your first suggestion that blame highlight takes precedence over other extensions is sufficient, as it's our top-used extension based on our current data.

Just to clarify with that you mean the behavior that is already shown in Tara's video? 

I suppose this is already how it works (because of the video) but I have a hard time checking this since I don't really understand how to enable the codecov extension. Do you have it running by any chance @jjinnii and can test this on dot-com?

**Comment by philipp-spiess** [comment]
> This is less an edge case, but poor UX of how the blame popover interacts with the popover. I'm [seeing that there's a latency](https://www.loom.com/share/330439ac77fd4750850e6ceed8f5f705) in the blame popover disappearing when a user's cursor has moved outside of the blame column, which is why there's an overlap with the code intel popover. Is it possible for us to instantly close the blame popover if a user's cursor moves outside the blame column?

I don't think this would be a good fix UX wise. If you look at Tara's video again, all he's doing is to try and click the button on the popover which causes his mouse to move a bit to the center of the popover. I don't think it would be intended in this case to close the git blame popover in favor of code intel. 

I've played around with this feature now as well and what's really unexpected for me is that when you are not super fast, moving the mouse to the content of the bit blame window will hover over another line and thus change the git blame info to the one on the line above/below. 

I think what is really unexpected is that somehow if you hover over a new blame column, the popup will switch instantly but if you hover from a blame column to the code to show a code intel column, this is not the case.

Maybe it helps if we just add a slight delay in showing a popover for a new git blame line _if a git blame popover is currently shown_?

**Comment by philipp-spiess** [comment]
I'll wait for Taras to come back tomorrow to continue investigating the first two items (the edge cases that @taras-yemets  raised). I think it will be faster if we pair on this 😕.

**Comment by philipp-spiess** [comment]
> On a similar note on font, the row being hovered should transition to [being Label/small-underline](https://www.figma.com/file/7bVINrmqfDpxmLx3gv1uVa/Sunsetting-extensions?node-id=2116%3A22361).

Alright last question (sorry for these unorganised comments): Are you specifically talking about an animation here or what do you refer to? The lines already show an underline when hovered so I’m not quite sure what is missing!

**Comment by philipp-spiess** [comment]
>  (Open to feedback on this) I transitioned to using absolute dates for better formatting, but open to feedback on this!

Ok ok really last one 😓: I like the relative date inside the git blame column since it's much easier to parse what is recent and what is not this way but I'd also like to show the full time stamp in the overlay where I want more details. What do you think about such a hybrid solution?

(I'll post a PR in a sec which will contian my thoughts more organized as well)

**Comment by taras-yemets** [comment]
> > As this only impacts customers with the legacy extensions enabled and have to enable both CodeCov and blame, I think a minimal effort solution is best here. I think your first suggestion that blame highlight takes precedence over other extensions is sufficient, as it's our top-used extension based on our current data.
> 
> Just to clarify with that you mean the behavior that is already shown in Tara's video?
> 
> I suppose this is already how it works (because of the video) but I have a hard time checking this since I don't really understand how to enable the codecov extension. Do you have it running by any chance @jjinnii and can test this on dot-com?

Overriding the bg color set by extensions decoration with the bg color set when hovering over the blame decoration has been already implemented in https://github.com/sourcegraph/sourcegraph/pull/40615 (see Loom from [this comment](https://github.com/sourcegraph/sourcegraph/pull/40615#issuecomment-1233096762)).

cc: @jjinnii, @philipp-spiess

**Comment by taras-yemets** [comment]
> I have a hard time checking this since I don't really understand how to enable the codecov extension

@philipp-spiess, it doesn't seem stable because of implementation specifics.
1. Extension [gets the file line coverage](https://sourcegraph.com/github.com/codecov/sourcegraph-codecov/-/blob/src/model.ts?L28-43.
2. When processing the file coverage data, it[ iterates through the files array in the commit report](https://sourcegraph.com/github.com/codecov/sourcegraph-codecov/-/blob/src/model.ts?L69-84). 
3. Commit report may not include the currently viewed file; that's why the coverage data may not be available.
<img width="2539" alt="Screenshot 2022-09-07 at 11 14 08" src="https://user-images.githubusercontent.com/25318659/188826908-e11e5365-ad64-4528-90f1-9097e07daab1.png">
