### ISSUE TITLE
Extensions: Move icons into the new "actions" toolbar (previously known as extensions toolbar)

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#41327]
![Screenshot 2022-09-05 at 17 20 52](https://user-images.githubusercontent.com/458591/188480497-f5144fb9-c196-4d59-9176-840ba7d77d4a.png)

![Screenshot 2022-09-05 at 18 39 34](https://user-images.githubusercontent.com/458591/188490572-132a98a3-dd83-42e1-9bb4-c8b2a97d421d.png)

- Move git blame icon
- Move GitHub icon
- Change the collapsed state icon
- Agree on the name: I used "action panel" 

/cc @muratsu @jjinnii @ryankscott

**Comment by philipp-spiess** [comment]
@jjinnii I've assigned this to you to figure out what we do regarding the "collapsed" state icon (See the second screenshot I added).

**Comment by jjinnii** [comment]
@philipp-spiess I think this can be as simple as changing the "collapsed" icon from the extensions icon to a [collapse icon](https://www.figma.com/file/7bVINrmqfDpxmLx3gv1uVa/Sunsetting-extensions?node-id=2617%3A15769)! (the same icon flipped). This is consistent with the collapse/expand behavior in other areas of our product, including the same icon for collapsing/expanding the file sidebar.

**Comment by jjinnii** [comment]
@philipp-spiess Works for me 😄  Thanks for the checking in on the details!

**Comment by philipp-spiess** [comment]
@jjinnii Another question here:

We currently show this sidebar in the file view but also in the compare and diff view, e.g.:

![Screenshot 2022-09-06 at 17 50 46](https://user-images.githubusercontent.com/458591/188680256-b661b4ac-d879-417a-95a1-eb16d03137a9.png)

With the extension deprecation in mind, does it still make sense to show the actions panel outside of the file view?

**Comment by philipp-spiess** [comment]
Weeell I guess we show the GitHub icon there as well 🤔 

this is going to be fun to move around lol

**Comment by jjinnii** [comment]
😓 @philipp-spiess @ryankscott Do we have the ability to see the usage of that Github action on specific the compare and diff view? We've made the decision to remove blame on these pages, but I can see how it's much more of a use case that users might want to open these pages on Github and maybe even editors??

**Comment by philipp-spiess** [comment]
@jjinnii I don't know about the data but I guess we could also leave the GitHub icon as-is and just remove the actions sidebar for those views. This means that only tree and file views will show the github icon in the actions sidebar and the other views won't show the sidebar alltogether?

I suppose for open in editor, not showing the icon in diff and commit view is okay?

**Comment by jjinnii** [comment]
@philipp-spiess I think that's the best solution for now 😓 ! The GitHub icon has always existed on those pages, so I don't feel comfortable removing them without any data. The open-in-editor would only have been shown for those who had the extension enabled, so I think its' OK to remove them on the diff/commit views. We can always add them back if we get feedback that users would like that functionality on those pages, and at that point we can re-think through how the vertical/horizontal toolbars should work with only one icon in each 😄 

cc: @ryankscott
