### ISSUE TITLE
Testing at Scale: provision a minimal playground instance 

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#41330]
1. Deploy some playground cluster
	- make sure it's accessible
	- https://github.com/sourcegraph/infrastructure/pull/3881
	- https://github.com/sourcegraph/infrastructure/pull/3883

3. Wire it to an existing code host
4. Make sure we can update and deploy seamlessly on it

**Comment by davejrt** [comment]
-[ ] Cloud SQL users + permissions need to be set.
-[ ] Databases need to be created and hooked up with Cloud SQL proxy (I think?) to their respective applications.
-[ ] Executors are not yet enabled. If that needs to happen, there’s a repo for it. The accompanying secrets need to be added in GSM, enabled in gsm-secrets.tf, and the volumes/volumeMounts need to be commented in (lol) again.
-[ ] A DNS record for scaletesting.sgdev.org still needs to be added (I am fairly confident that frontend and the ingress controller are configured properly now, but it might be a good idea to look through the helm values of nginx to see if there are any references to dogfood or k8s.sgdev.org still. The certs are mounted in frontend at least).
-[ ] Code hosts set up
-[ ] Site config config’d
-[ ] Users added

**Comment by jhchabran** [comment]
Documentation PR: https://github.com/sourcegraph/handbook/pull/4823

**Comment by jhchabran** [comment]
- [] Test `sg ops update-images` with the instance 
- [] Update the documentation to show how to do this 
- [] Update the documentation to show how to apply infrastructure changes (for ex running more gitservers or more RAM on Frontend)
