### ISSUE TITLE
search: add `repoHasFile` flag

### ISSUE THREAD

**Issue by ijt** [sourcegraph/sourcegraph#4134]
Add a new search query filter `repoHasFile` which supports getting results only if the repository has a file matching the specified filepath regexp.

Example: `error repoHasFile:foo/.*\.py language:go`

**Comment by slimsag** [comment]
Usability issues I see with the current implementation:

1. [ ] As @keegancsmith [pointed out in his review feedback](https://github.com/sourcegraph/sourcegraph/pull/4247/files#r288947598), I too expect that `repoHasFile:foo repoHasFile:bar` be treated as "repositories containing a file matching `foo` OR `bar`".
    - **Does this block release of this feature?** It is a serious flaw, and while the customer would (I think) be able to use it with just one `repohasfile` filter -- it's something we cannot change in the future as it'd break existing queries. So it makes sense to change it before releasing. If fixing it is super difficult for some reason, we could temporarily enforce only one filter is present for the release and mark the feature as experimental / don't call it out in our blog post but this is obviously not optimal.
2. [ ] As a user I expect the `repohasfile` keyword to be case insensitive. `repohasfile`, `repoHasFile` and `RepoHasFile` should all work.
    - I am against enforcing just a single casing like `repoHasFile` or `RepoHasFile` because:
        a. It would be inconsistent with what existing search users expect I think unless we enforced just `repohasfile` (all existing tokens are lowercase).
        b. `repohasfile` is noticeably uglier than `repoHasFile` and it'd be nice to call it `repoHasFile` in docs and allow users to neglect the case if they prefer.
    - **Does this block release of this feature?** No, I don't think so. It'd be nice to fix before release though and we should try to do that.

**Comment by slimsag** [comment]
> Note: this currently only works if there is another search term in addition to the repohasfile value, so the query repohasfile:\.md would return no results. Is this sufficient for the customer's needs @slimsag?

This is fine, as long as we:

- [ ] Update search docs to include this filter and declare that it is a pure filter and cannot operate on its own.

**Comment by ijt** [comment]
@slimsag, I'd like to close this issue since we do effectively now have a `repoHasFile` field, and have new issues for the remaining concerns.

**Comment by slimsag** [comment]
where is the issue for case sensitivity? I couldn't find it

**Comment by slimsag** [comment]
eh, nvm on that one
