### ISSUE TITLE
search: add `repoHasCommitSince` flag

### ISSUE THREAD

**Issue by ijt** [sourcegraph/sourcegraph#4135]
For example: `error repo.hasCommitSince:"1 month ago"` returns files matching the word `error`, only from repositories that have had a commit in the past month.

**Comment by slimsag** [comment]
As mentioned in https://github.com/sourcegraph/infrastructure/issues/1475#issuecomment-495021234 for the $CUSTOMER in question this would be intrinsically dependent on also having https://github.com/sourcegraph/sourcegraph/issues/4138

**Comment by ijt** [comment]
@attfarhan, I'm assigning this to you but feel free to grab the other flag issue #4134 first/instead if you find out that it's more important.

**Comment by kzh** [comment]
I'm currently working on this and will start with familiarizing myself with `cmd/searcher`.

**Comment by slimsag** [comment]
Here is some additional context from conversations I've had with @attfarhan and @Ijt (which unfortunately were in Slack DMs and not public, will try to do better here in the future)

Conversation I had with @attfarhan about the perf impact of this feature:

> farhan [7:05 PM]
> What are the perf expectations for this btw? I imagine hasCommitSince is going to involve `git log`-ing, and based on how diff/commit search is, that will probably mean a slower experience. Do they just care that this functionality is available?
>
> stephen [10:54 PM]
> I think that performance would not be impacted much by this and in some cases it could actually be much quicker than regular search queries. What this would be is:
>
> 1. Run the search query
> 2. Before we search a repository, check if it had a commit after the specified time
> 3. If it didn't have a commit since then, don't search the repository (and inherently, don't include its results)
> 4. If it did have a commit since then, search the repository.
>
> In many cases this will mean we are actually trading costs: we have to ask when the most recent commit to the repo was, but in exchange we are not searching a significant number of repositories

Conversation I had with @ijt about this feature:


> stephen [11:43 AM]
> the goal of `repohascommitsince` is to exclude older repositories without active maintainers that violate some internal movement a customer has have to refactor things, e.g. a customer wants all READMEs to use some new format and want to find every actively-developed repo not following that format to tell those owners to update.
>
> ijt [11:45 AM]
> The simplest way to do it involves making git calls on all the repos. I’d like us to try that and measure its performance in their use cases.
>
> stephen [11:50 AM]
> Definitely, I expect it would be something like:
>
> 1. Find which repositories we intend to search (we do this today already)
> 2. On each repository, run the Git command to get the time of the latest commit (e.g. https://stackoverflow.com/a/25564443)
> 3. Exclude the repo if needed
> 4. Search the repos
> I suspect perf will be totally fine especially because we'll be ignoring what sounds like a reasonably large amount of repos from doing actual search work
> only thing we need to do is make sure running those git commands we don't e.g. flood gitserver too much
>
> ijt [11:51 AM]
> sg.

**Comment by slimsag** [comment]
Also, here's how I would get started on this:

- For actually adding the new search keyword `repohascommitsince`
    - I would use @attfarhan's PR here as a reference: https://github.com/sourcegraph/sourcegraph/pull/4247
    - In particular you may want to look at `FieldBefore` and `FieldAfter` which are also duration-based fields today. https://sourcegraph.com/github.com/sourcegraph/sourcegraph@b6e29f1/-/blob/cmd/frontend/internal/pkg/search/query/searchquery.go#L24-25 Example query showing how it works: https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24%40b6e29f1+type:commit+after:%223+days+ago%22
- For filtering out the repositories that don't match the search filter:
    - You can place that logic here which is the central area where we determine "which repositories should we search over?" https://sourcegraph.com/github.com/sourcegraph/sourcegraph@b6e29f15f81769e5b0daabba6947af729bb3031e/-/blob/cmd/frontend/graphqlbackend/search.go#L372:6
    - You would then just need to pass in your new `repohascommitsince` filter into that function via one of these fields: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@b6e29f15f81769e5b0daabba6947af729bb3031e/-/blob/cmd/frontend/graphqlbackend/search.go#L363-364
- To actually do the filtering inside of that func by calling the Git command:
    - Declare a new function that runs the Git command you want, e.g. https://stackoverflow.com/a/25564443, e.g. alongside other commit functions we have here: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@b6e29f1/-/blob/pkg/vcs/git/commits.go#L94-105
    - Once you have that function defined, you can call it from within `resolveRepositories` doing something like this: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@b6e29f1/-/blob/cmd/frontend/graphqlbackend/git_commits.go#L56:10
    - You would do the filtering on the repos list returned by this func, I believe, and that is also what you'd pass into your git command as the repo argument: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@b6e29f15f81769e5b0daabba6947af729bb3031e/-/blob/cmd/frontend/graphqlbackend/search.go#L418

That I believe would get you to a functional version^ but there are probably some pieces above I may have been wrong about. Also adding tests along the way will be important and something I didn't cover. Feel free to give me a ping on Slack if you have questions!

**Comment by kzh** [comment]
Thanks @slimsag! This is very helpful. I was thinking the same thing about digging through Git metadata and using that to filter the results.
