### ISSUE TITLE
search: go straight to blob view for query with only 1 file result

### ISSUE THREAD

**Issue by leonore** [sourcegraph/sourcegraph#41355]
this is a _proposal_ that gets regularly brought up (slack: [february](https://sourcegraph.slack.com/archives/C0W2E592M/p1645794607869219), [july](https://sourcegraph.slack.com/archives/C03CSAER9LK/p1656692330686989), and I initially wanted to work on this in the march hackathon). it would need proper triage

[main slack discussion thread (february ’22)](https://sourcegraph.slack.com/archives/C0W2E592M/p1645794607869219)

some key points made in slack threads so they don't get lost forever:
* "opening the file directly when a search result has only one match? Ditto for repos. This change would significantly improve my regular workflow of using the search bar tab completion to open a specific file in a specific repo"
* likely to cause confusion for new users/be very unexpected
* might be good for user personalisation (do we want yet another user setting?)
* adding a hotkey to select the first result, pressing return would then load the file 

/cc @benvenker @lguychard

**Comment by camdencheek** [comment]
Closing since this is solved by improvements to the completions menu that allow you to jump straight to a completion item.
