### ISSUE TITLE
3.4 tweet

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#4139]
Sourcegraph 3.4 is out! The open-source, self-hosted code search/nav tool, now with:

🛠️ Repo syncing improvements for AWS CodeCommit and Gitolite
🗂 New option to load config from the file system or ConfigMaps (for config changes in PRs)

And more...

https://about.sourcegraph.com/blog/sourcegraph-3.4

**Comment by christinaforney** [comment]
Good to go for sending tomorrow morning!

**Comment by christinaforney** [comment]
Sent!
