### ISSUE TITLE
Users.Delete does not soft-delete user activity data

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#414]
This is an unintentional bug; when Users.Delete is called it is not soft-deleting data from the `user_activity` table. cc @dadlerj 

See this function:

https://sourcegraph.sgdev.org/github.com/sourcegraph/sourcegraph@9f467018d92c6e2b046f9950015eddb592da7e88/-/blob/cmd/frontend/db/users.go#L356:17

**Comment by slimsag** [comment]
Ah, it seems like I am partially wrong. This table exists in prod but not in local instances; I wonder why?

**Comment by slimsag** [comment]
We should still be deleting user_activity data from Redis Store in the above func though.

**Comment by dadlerj** [comment]
The `user_activity` postgres table is no longer in use, it's all been migrated to redis. Not sure why it's still around in prod.

I'm not sure I entirely agree with this issue though. I recall intentionally not adding it to the `Users.Delete` function in the past. User activity data is useful for admins to see historical trends. Soft-deleting a user today shouldn't remove the historical fact that there was usage in the past. What do you think?

(though I agree we should delete the user ID-keyed record from redis, but not necessarily the historical date-keyed records that store a count of users)

**Comment by slimsag** [comment]
Sounds fine to me, as long as it is intentional. Maybe we could add a note to the code about this?

For GDPR-style data deletion requests I am adding a separate nuking button which does much harsher data deletion (such as deleting survey responses, and in the future user_activity data as well in an automated fashion instead of manually like we do today)

**Comment by ryanslade** [comment]
@dadlerj @slimsag I stumbled upon this old issue. 

I think we now use the `event_logs` table. Do we want to remove user logs from there when a user is deleted? (Do we want to treat hard and soft deletes differently)?

**Comment by dadlerj** [comment]
Ideally we wouldn't remove usage stats or rewrite history (usage numbers are used for things like billing). Is there some way to anonymize those instead—e.g., delete the user ID and replace it with a random/anon id? 

If not, then a more complicated solution would be required, in which we cache the number of users on a daily/weekly/monthly, so that hard deletions don't rewrite history.

**Comment by ryanslade** [comment]
@dadlerj PTAL at the linked PR
