### ISSUE TITLE
Code intel admin analytics: UI Review

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#41404]
UI Review for issue #40345. Related PR #40681 cc: @macraig 

**"Top repositories" table**

- Could we double-check the font weights in the "Top Repositories" table? I think we're using "var-bold" for the numerical values in this table, while the other tables use font-weight "600". 
- Can we add padding for the list under "Precise navigation"? In my mockups, I have a padding of 4px for each line item.
- For lists where there is a mix of set up precise languages and CTAs for setting up languages (screenshot below), could we manipulate the order such that all CTAs go below any languages that are showing a % coverage?
  <img width="288" alt="Screen Shot 2022-09-07 at 4 56 57 PM" src="https://user-images.githubusercontent.com/87138876/188822726-1c066e1b-2cd1-4bfd-b8a9-6b55e1d302bd.png">

**"Events by language" graph**

- The table can be much wider. If you look at the "Weekly activity" chart at the top of the page, that chart occupies the whole page container with only 16px of padding. We should widen the chart to have it start left-aligned to where the "Weekly activity" chart begins. 
- It seems the admin analytics team used a different font weight (font-weight-base) for their numerical headers, than what we're using. See below for the comparison. Let's use the font weight, or else just the Events by language numerical value has too heavy a weight. 
<img width="168" alt="Screen Shot 2022-09-07 at 4 59 11 PM" src="https://user-images.githubusercontent.com/87138876/188823614-8c9b53b4-0c2f-4f79-9a7a-397680bfc162.png">
<img width="223" alt="Screen Shot 2022-09-07 at 4 59 06 PM" src="https://user-images.githubusercontent.com/87138876/188823622-50b70068-0e5b-4364-98f7-c3cf12939a20.png">

**Comment by macraig** [comment]
@jjinnii what do you think of @chrismwendt 's suggestion to only show the top 10 used langs in the chart? Or at least not showing the languages that have no events at all?

@chrismwendt would you be able to tackle https://github.com/sourcegraph/sourcegraph/issues/39780 as part of the UI changes? We'd listed it as part of the tracking issue in https://github.com/sourcegraph/sourcegraph/issues/39769

**Comment by jjinnii** [comment]
@macraig I think it makes sense not to show languages that don't have any events, as the intent of the graph is to surface languages and their usage. From an admin's POV, it wouldn't be compelling for them to set up precise intelligence for languages with no search-based events. And I think it'd be highly unlikely that precise intel would be set up for a language with zero search-based _and_ precise events.

I'm hoping that this will alleviate the clutteredness. A top 10 list would require that in situations where there are more than 10 languages being used, we have to present a UI to see which languages at what %.

**Comment by macraig** [comment]
@jjinnii agreed!
