### ISSUE TITLE
3.43.2: Patch release to fix context canceled errors in bitbucketserver code host sync

### ISSUE THREAD

**Issue by indradhanush** [sourcegraph/sourcegraph#41400]
@sourcegraph/release-guild I am requesting the following commits be included in a patch release. They are already merged into `main`:

- https://github.com/sourcegraph/sourcegraph/commit/e49cda4784797ce73bf2de65cf615210ae9313e1
- https://github.com/sourcegraph/sourcegraph/commit/bdb0a0decb1c7d3937b4c05336ae8b6f295be5b6
- https://github.com/sourcegraph/sourcegraph/commit/c407226c05c32ae6f0e2b89ae10d0c297b1634cb
- https://github.com/sourcegraph/sourcegraph/commit/d85d39171eb77ca793ac4f12e7a277753e0a57e9
- https://github.com/sourcegraph/sourcegraph/commit/c85cd000abe095d59ec0185f5bfe4821842e439f

---

I have read [when and why we perform patch releases](https://handbook.sourcegraph.com/engineering/releases#patch-releases) and answer the questions as follows:

> Are users/customers actively asking us for these changes and cannot wait until the next full release?

Yes. This is for the following [customer](https://github.com/sourcegraph/accounts/issues/3).

> Are the changes extremely minimal, well-tested, and low risk such that not testing as we do in a full release is OK?

Yes. The changes have been reviewed and tested. This adds a new endpoint for validating external services and changes the code to use this endpoint instead of the existing one when a sync is triggered manually from the site admin.

> Is there some functionality completely broken that warrants redacting the prior release of Sourcegraph and advising users wait for the patch release?

Yes. Manually triggering a sync dumps a long chain of errors in the site admin.

> This will interrupt our regular planned work and release cycle, taking one full working day of our time, and will take up all of our site admin's valuable time by asking them to upgrade or producing noise for them if they don't need to upgrade.
>
> Do you believe the changes are important enough to warrant this?

Yes. See [this](https://sourcegraph.slack.com/archives/C03MV6CKU1X) channel on Slack.

> Patch releases are a signal we can do something better to improve the quality of Sourcegraph. Have you already scheduled a call (or created a google doc) to perform a [retrospective](https://about.sourcegraph.com/retrospectives) and identify ways we can improve?

No retro. This was a long standing [issue](https://github.com/sourcegraph/sourcegraph/issues/40153) which was hard to reproduce extending the timeline for the fix. 

---

**For the [Release Captain]** - after reviewing this request:

- [x] **Comment on this issue** with a decision regarding the request.
- [x] If you are a first-time [Release Captain], please review the high-level overview of the [patch release process].
- [x] If approved, **add it to a patch release**:
  - If there is [already an upcoming patch release](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+), add the listed commits alongside a link to this issue
  - If there is no upcoming patch release, create a new one:
    - [x] Update [`dev/release/release-config.jsonc`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/release/release-config.jsonc) and open a PR to `main` to update it
      - [x] Change `upcomingRelease` to the current patch release
      - [x] Change `previousRelease` to the previous patch release version
      - [x] Change `releaseDate` to the current date (time is optional) along with `oneWorkingDayAfterRelease` and `threeWorkingDaysBeforeRelease`
      - [x] Change `captainSlackUsername` and `captainGitHubUsername` to the patch captain's
    - [x] Run `yarn release tracking:issues` on `main`
    - [x] Add the listed commits alongside a link to this issue to the generated [release tracking issue](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+)
- [x] **Comment and close this issue once the relevant commit(s) have been cherry-picked into the release branch**.

[release captain]: https://handbook.sourcegraph.com/engineering/releases#release-captain
[patch release process]: https://handbook.sourcegraph.com/departments/product-engineering/engineering/process/releases#patch-release-process

**Comment by indradhanush** [comment]
I'm signing up as the patch captain to drive this ship to shore. 🚢

**Comment by unknwon** [comment]
LGTM on behalf of the release guild 👍

**Comment by varsanojidan** [comment]
Patch Released: https://github.com/sourcegraph/sourcegraph/issues/41485
