### ISSUE TITLE
CodeMirror, lazy highlighting and long line wrapping layout shifts unnecessarily

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#41413]
### Description

Using [lazyBlobSyntaxHighlighting](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/schema/settings.schema.json?L360-367) with [enableCodeMirrorFileView](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/schema/settings.schema.json?L352-359) has a noticeable bug

Enable wrapping long lines" seems to cause the file viewer to jump around. This might be due to CodeMirror attempting to "scrollTo" twice.

### To replicate:
1. Set `enableCodeMirrorFileView` and `lazyBlobSyntaxHighlighting` to `true`.
2. Load [this URL](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/schema/settings.schema.json?L352-359) (dotcom)
3. Click "Disable/Enable wrapping long lines". Notice that the entire file view shifts more than you would expect. This also happens on load if the setting is already enabled.

/cc @taylorsperry @muratsu

**Comment by fkling** [comment]
What you are saying might be true, but even without lazy syntax highlighting I feel that toggling line wrapping can sometimes cause the editor to jump unpredictably.
