### ISSUE TITLE
Simplify Perforce rule matching

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#41444]
Our current logic attempts to detect conflicting rules and remove them. There are potential situations
where this may remove rules too broadly and cause us to leak data.

Instead, we should simplify our current approach even if it's slower initially in order to guarantee correctness.
We can improve the performance later by optimising the code and adjusting the algorithm. 

Instead of keeping a separate lists of include and exclude rules we keep one list of rules in the same order they appear in the protection table, just converted into a glob pattern. We can continue to filter out rules that don't apply to the current depot. 

Then, for each path we just move down the list one rule at a time granting or revoking read access until we get to the end. Once we're at the end we'll know whether the path is allowed or not. We'd always start with a no access to be safe.

This will definitely be slower as we'll need to check all the rules (ie, O(n) where n is the number of rules) but it may be fast enough for our needs and is simpler and at least much easier to reason about.

For reference, our current logic to generate the list of rules is [here](https://github.com/sourcegraph/sourcegraph/blob/a94c7eb7beca6acdd720c5a12bd99d0946b4f116/enterprise/internal/authz/perforce/protects.go#L327)

We may need to introduce a new database column in `sub_repo_permissions` to store all rules and use the new code path if it is populated or the old code path if not in order to allow a smooth migration for customers. 

/cc @sourcegraph/iam

## Todo

- [x] #41781
- [x] #41789
- [x] #41788
- [x] #41927
- [x] #41992
- [x] #42156
- [ ] #42417

**Comment by pjlast** [comment]
includes: [1, 2, 3], excludes: [2]

if 2 in excludes:
    return
 else:
     check if in includes
     
 paths: [1, 2, 3, -2]
 
 // iterate over paths with excludes last should preserve the current behaviour, while allowing us to upgrade without maintaining multiple versions

**Comment by sashaostrikov** [comment]
**September 20th sync w/ @ryanslade @pjlast **

The work should be done incrementally like so:

0) Create a DB migration to add new `paths` column (vs. old `paths_includes`, `paths_includes`)
1) Implement rules parsing and storing them to the new `paths` column
2) Add alternative branch of logic to "understand" new `paths`
3) "re-path" -- check if new rule is present -- read from there and read the new format, if not -- fallback to existing code
5) keep the old and new code for transition period
6) deprecate the old code in a later release

**Comment by mollylogue** [comment]
Quick question here. Doesn't it matter the order in which the includes and excludes are listed in the protections file? It seems like you're suggesting that we just put includes and then excludes into a single array, but I think the rules should be ordered by how they appear in the original protections table. Does that make sense?

**Comment by pjlast** [comment]
@mollylogue So this is only for regression. The way it works at the moment, it checks for Exclusions first so that it can return early. So essentially, all exclusions take preference.

So, by doing the DB migrate by appending the exclusions to the inclusions in the new column, we only have to look at the new column. Since the exclusions are at the bottom of the list, they'll take preference (just like they do at the moment).

Then on subsequent rule updates, the rules will be ordered correctly.

Doing it like this allows us to migrate to the new column without having to maintain multiple code paths

**Comment by mollylogue** [comment]
> @mollylogue So this is only for regression. The way it works at the moment, it checks for Exclusions first so that it can return early. So essentially, all exclusions take preference.
> 
> So, by doing the DB migrate by appending the exclusions to the inclusions in the new column, we only have to look at the new column. Since the exclusions are at the bottom of the list, they'll take preference (just like they do at the moment).
> 
> Then on subsequent rule updates, the rules will be ordered correctly.
> 
> Doing it like this allows us to migrate to the new column without having to maintain multiple code paths

Okay great 🙏  That makes sense. Thank you for clarifying.
