### ISSUE TITLE
Iterative Searchs

### ISSUE THREAD

**Issue by DaedalusG** [sourcegraph/sourcegraph#41475]
#### Feature request description

Some users would like the ability to execute iterative queries. For example a search for repos matching some pattern. Then a subsequent search scoped within the context of the repos returned by the previous search for a separate regex pattern. In this way users can do an iterative filtering of results. This could be helpful for a variety of different programmatic applications and in some cases may be more comprehensible that a intersectional search using `and` or `not` to return the final results.

#### Is your feature request related to a problem? If so, please describe.

Not explicitly but it came about in a use case where users wanted to search for a set of repos containing a certain pattern but **not** containing matches to another pattern. In this case the `not` operator wasn't totally useful in that it matched any repo where _any_ file matched the initial pattern and also excluded the `not` pattern. This isn't quite right.

`patterntype:regexp select:repo pattern-1 not pattern-2`

#### Describe alternatives you've considered.

You could accomplish something like this using [search contexts](https://docs.sourcegraph.com/code_search/how-to/search_contexts#beta-query-based-search-contexts) but currently that UX is a little limited
<img width="1734" alt="Screen Shot 2022-09-07 at 4 52 54 PM" src="https://user-images.githubusercontent.com/13024338/189002677-da994063-8d5d-46d3-a6ae-9d95cec1573e.png">
<img width="833" alt="Screen Shot 2022-09-07 at 4 54 11 PM" src="https://user-images.githubusercontent.com/13024338/189002691-b0391cc2-0f9f-4822-8720-50bba7bed797.png">

#### Additional context

/cc @benvenker @lguychard

**Comment by camdencheek** [comment]
Would something like `repo:has.content -repo:has.content(pattern-2)` work? While I agree that generalized subqueries would be awesome, it's not realistically something that we're anywhere close to being able to execute on.

**Comment by DaedalusG** [comment]
It absolutely would, this actually came up as a possibility, but currently negation there isn't supported 
<img width="948" alt="Screen Shot 2022-09-07 at 5 54 25 PM" src="https://user-images.githubusercontent.com/13024338/189010130-f7002139-3f3e-428b-a00a-ec57e220dda1.png">

**Comment by camdencheek** [comment]
Oh! Sure enough. I'm actually working on this [right now](https://github.com/sourcegraph/sourcegraph/pull/40283)

**Comment by Phoenixmatrix** [comment]
(I'm one of the person who @DaedalusG was trying to help with this). Negated #40283 will absolutely solve the problem we were having (it's actually the first thing I tried). Awesome to know it might be on the way!

> While I agree that generalized subqueries would be awesome

Subqueries wasn't exactly what we were talking about. My thought would be being able to use something like a Lua or JS script in lieu of a query to manipulate the datasets, and use the results in Notebooks, Monitoring, Insights, etc. 

For now using the CLI tool in a script works perfectly fine for most of our use cases, but the output obviously can't be used in other parts of Sourcegraphs. I don't expect that any time soon, but that would be a hell of a killer feature :)

**Comment by Phoenixmatrix** [comment]
> need to be able to display whatever the user outputs

I'd expect an MVP of that would beed that the only thing that could be returned from the script would be objects in the same format as regular queries, and anything else fails (or just display as is in a text area). Behind an experimental flag so no one complains that its quirky 😆 

But for now, negated predicates and the cli tool will do nicely.
