### ISSUE TITLE
Sentry platform integration

### ISSUE THREAD

**Issue by christinaforney** [sourcegraph/sourcegraph#4149]
In conjunction with the Sentry extension, we are also going to write an integration into the Sentry platform. This will allow users to jump directly to Sourcegraph from a Sentry instance.

Good example integration with Rookout: 
- https://sentry.io/integrations/rookout/ 
- https://docs.sentry.io/workflow/integrations/global-integrations/#rookout

Docs on how to integrate with their platform: https://docs.sentry.io/workflow/integrations/integration-platform/

**Comment by lguychard** [comment]
Retagging this as "web+extensions" for lack of a more precise label.

**Comment by lguychard** [comment]
@christinaforney closing this, let's reopen if/when we put it back on our roadmap.
