### ISSUE TITLE
Hang when using sg setup

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/sourcegraph#41509]
Configuration: Ubuntu 22.04.1, sg: built from commit 801e751f535dff3226cb92737722868a6cccbe15, default terminal

Running `sg setup` gets to the 'Running checks' step (I selected 'y' for 'Are you a Sourcegraph teammate'), but is stuck at 0% progress. Sending SIGQUIT or SIGABRT doesn't do anything. SIGKILL works, but after that, re-running `sg setup` immediately exits (it doesn't get to the hang).

**Comment by jhchabran** [comment]
Took a quick look on the side, it's broken by https://github.com/sourcegraph/sourcegraph/pull/36593/files, it works before that PR.

**Comment by bobheadxi** [comment]
I reviewed that PR again and i'm pretty sure the flags we determine are the same. Additionally, we have https://github.com/sourcegraph/sourcegraph/actions/workflows/sg-setup.yml which runs test on ubuntu
