### ISSUE TITLE
Reference panel: "you are at the definition" does not work inside preview pane

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#41512]
When hovering over a definition in the preview pane, the "Go to definition" button is active
![CleanShot 2022-09-08 at 15 22 02](https://user-images.githubusercontent.com/1408093/189133187-d59aee7f-4465-433d-8cc1-0cee5aeffb95.png)

When hovering over a definition in the main blob view, the "Go to definition" button is disabled and has the text "You are at the definition"
![CleanShot 2022-09-08 at 15 22 31](https://user-images.githubusercontent.com/1408093/189133182-853a35b0-24ef-4d45-9ab8-dc353ed5212c.png)

**Comment by olafurpg** [comment]
The "You are at the definition" button is determined by this condition here 

https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@8d7f8e5fc05ea29d1d01c18c18fc8ea0d0975234/-/blob/client/shared/src/hover/actions.ts?L207

My guess is that we can fix this issue by making that function use locations from the in-memory router.

**Comment by olafurpg** [comment]
Steps to reproduce. 

- Visit https://sourcegraph.com/github.com/tensorflow/tensorflow@f76855b072f816b14674ad2fcd12342296334740/-/blob/tensorflow/go/attrs.go?L28#tab=references
- Hover over `makeCShape` in the preview pane, "Go to definition" button is enabled
- Hover over `makeCShape` in the main blob view, "Go to definition" button is disabled with message "You are at the definion"


Video recording 
![CleanShot 2022-09-08 at 16 04 59](https://user-images.githubusercontent.com/1408093/189143586-a5e79a2c-a2c5-446d-a06c-6e8ef8138af0.gif)


I'm unable to reproduce this issue in repos that have precise code intel enabled, for example here https://sourcegraph.com/github.com/golang/go/-/blob/src/io/io.go?L83:6#tab=implementations_go

![CleanShot 2022-09-08 at 16 06 48](https://user-images.githubusercontent.com/1408093/189143682-84de6f59-cb3b-400f-accf-db41fce48725.png)

**Comment by fkling** [comment]
We don't show hover information in the preview panel anymore, so this issue is no longer relevant.
