### ISSUE TITLE
Add Batches File Handler Metrics to Grafana Dashboard

### ISSUE THREAD

**Issue by Piszmog** [sourcegraph/sourcegraph#41525]
As part of #40829, metrics are being emitted for the different operations (`GET`, `HEAD`, `POST`). These metrics should be added to the frontend Grafana dashboard.

## Technical Direction
See the following for examples,
* https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/monitoring/definitions/frontend.go?L333%3A1-335%3A74=
* https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/monitoring/definitions/shared/batches.go?L14%3A1-44%3A2=

**Comment by eseliger** [comment]
P1 or P0, as we start rolling this feature out soon likely?

**Comment by Piszmog** [comment]
I agree with P1. Since this depends on #40829, it can't be worked on till that is merged.
