### ISSUE TITLE
Regression: `OpenInEditorActionItem` can cause infinite request retries on error

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#41522]
More context: https://sourcegraph.slack.com/archives/CMBA8F926/p1662559931542359

### Steps to reproduce

1. Have invalid settings (because schema has been changed, for example)
2. Open a blob view, like: https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/Layout.tsx?L125
3. See your requests go up:
![screenshot_2022-09-07_16 32 24](https://user-images.githubusercontent.com/1185253/189159376-1569dbb2-0d54-49db-a84a-0c0e8613579a.gif)
4. Browser tab crashes and you get blocked by Cloudflare

### Debug info

I nailed this down to this PR https://github.com/sourcegraph/sourcegraph/pull/41105 which introduced these lines https://github.com/sourcegraph/sourcegraph/blob/b7b9d52c2e7b15b04e6faa01e4fd23137b74c570/client/web/src/open-in-editor/OpenInEditorActionItem.tsx#L54-L66

they show up in the stack trace of the 10s of thousands of `OverwriteSettings` calls that seem to happen:

![image](https://user-images.githubusercontent.com/1185253/189159169-4da25d30-caea-4aed-8dee-7aa1a1bbb6de.png)

Here's the error response

![image](https://user-images.githubusercontent.com/1185253/189159217-e4235f48-9a84-4cab-9b32-ffdefedeca8b.png)

/cc @muratsu @jjinnii @ryankscott

**Comment by mrnugget** [comment]
Okay, this is more serious than I thought: it also does the infinite loop when there's no error. Might explain why Sourcegraph felt a bit slow past days.

https://user-images.githubusercontent.com/1185253/189161338-8c62d04d-c699-444d-bf15-72b6d79a8c1d.mp4

**Comment by mrnugget** [comment]
It's on dotcom too:

https://user-images.githubusercontent.com/1185253/189162924-15ca4a3a-e893-4fcd-a538-6bef750125cb.mp4

**Comment by vdavid** [comment]
Thanks for spotting this, my bad!
@taras-yemets also kind of noticed this and fixed it in https://github.com/sourcegraph/sourcegraph/pull/41431 which I'm reviewing now

**Comment by philipp-spiess** [comment]
Fix here: https://github.com/sourcegraph/sourcegraph/pull/41527
