### ISSUE TITLE
Downsize Gitserver

### ISSUE THREAD

**Issue by kalanchan** [sourcegraph/sourcegraph#41546]
Tracking issue for resizing gitserver. 

GitServer: 20 * 19.5TB = 400TB 
https://github.com/sourcegraph/deploy-sourcegraph-cloud/blob/d437871591a0576a6c971afcb32fe439570a482d/base/gitserver/repos-gitserver-0.PersistentVolume.yaml#L12

Current usage: 157TB/400TB ~ 39.3% usage

![Image](https://user-images.githubusercontent.com/51868853/189220455-1698afcc-e81a-45ab-be76-3c4a21dc501e.png)

Proposal: decrease disk to 10 TB -> saves ~ 200TB of disk
Proposed Usage: 157TB/200TB ~ 78.5% usage

Indexed-Search: 48 * 2TB = 98TB
https://github.com/sourcegraph/deploy-sourcegraph-cloud/blob/d437871591a0576a6c971afcb32fe439570a482d/base/indexed-search/indexed-search-0.PersistentVolume.yaml#L11

Current Usage: 26TB/98TB ~ 26.5% usage

![Image](https://user-images.githubusercontent.com/51868853/189220649-f5893c0b-c893-40b0-ae8a-a8d821cf9bb0.png)

![Image](https://user-images.githubusercontent.com/51868853/189220592-c63803b3-de2e-4de1-8b3a-b84b78b6f496.png)

Proposal: decrease disk to 750GB -> total 36TB saves ~62TB of disk
Proposed Usage: 26TB/36TB ~ 72% usage

**Comment by kalanchan** [comment]
https://github.com/sourcegraph/deploy-sourcegraph-cloud/pull/17296

**Comment by jhchabran** [comment]
@kalanchan this is marked as done, can we close this?

**Comment by kalanchan** [comment]
@jhchabran closed! ty for the heads up
