### ISSUE TITLE
Sourcegraph.com should use *_CONFIG_FILE via Kubernetes

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#4156]
We can now commit our Sourcegraph.com configuration to our repository using the new `*_CONFIG_FILE` environment variables. We should also set `DISABLE_CONFIG_UPDATES` after https://github.com/sourcegraph/sourcegraph/pull/4154 is merged.

This would prevent issues like https://github.com/sourcegraph/sourcegraph/issues/3966#issuecomment-494602066 from happening again by accident.

**Comment by slimsag** [comment]
Still an issue and has bitten us again since this was filed.

**Comment by davejrt** [comment]
Closed via PR #2428

**Comment by slimsag** [comment]
Was this fixed? From a quick glance at our YAML it seems GLOBAL_SETTINGS_FILE is not set

**Comment by davejrt** [comment]
@slimsag this was merged this morning
