### ISSUE TITLE
Unable to fork a repo when multiple repos have same name

### ISSUE THREAD

**Issue by Piszmog** [sourcegraph/sourcegraph#41641]
When forking repos with the same name, the following error occurs,

```
Failed to run operations on changeset
Getting user fork for "some-user": repo was not forked from the given parent
```

## Scenario

* 2 repos with same name
    * `bitbucket.mycompany.org/Foo/hello-world`
    * `bitbucket.mycompany.org/Bar/hello-world`
* Forks are enabled for batch changes in site settings

Running a batch change for these repos causes the `Getting user fork for "{batch_changes_user}": repo was not forked from the given parent`

## Initial Thoughts

`BitbucketServerSource.getFork(..)` is not able to handle where the repo names are the same but are not forks.

**Comment by Piszmog** [comment]
I’m looking thru the code and it appears that the first repo (`GAB/bae-test`) gets forked correct (to `~milton/bae-test`). When going to fork the second repo, it checks to see if a fork already exists for the repo (by searching if a repo `~milton/bae-test` exists). It does exist, but that repo belongs to another parent/project.

**Comment by courier-new** [comment]
It's a bug, so P0? @Piszmog do you have an idea for an estimate on this one?

**Comment by LawnGnome** [comment]
P0, 1-2d would be my guess.

**Comment by Piszmog** [comment]
yea 1-2d. Depends on how to go about working around this issue

**Comment by adeola-ak** [comment]
@Piszmog noticed you used bitbucket in the repro case, was this discovered to be just on bitbucket?

**Comment by Piszmog** [comment]
This specific issue is Bitbucket. But my gut feeling is this is also a GitHub and GitLab issues (not 100% sure on that)

**Comment by courier-new** [comment]
Currently blocked by https://github.com/sourcegraph/sourcegraph/issues/43153.
