### ISSUE TITLE
Search result: Unstable search result layout

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#41651]
Follow up for https://github.com/sourcegraph/sourcegraph/pull/41590
Original comment https://github.com/sourcegraph/sourcegraph/pull/41590#issuecomment-1242802787

https://user-images.githubusercontent.com/18492575/189501200-b0138795-8109-4730-8c17-0c2cc6360eff.mov

I've noticed that this happens only when navbar has the full items mode (when we render global nav bar items with words) and it doesn't happen when we render global nav bar items as just icons. 

Note: I couldn't reproduce this on k8s but I saw this on sourcegraph.sourcegraph.com and on local instance. 

/cc @benvenker @lguychard

**Comment by fkling** [comment]
Closing this since we redesigned the whole search results page.
