### ISSUE TITLE
Strange behaviour with repo regex query

### ISSUE THREAD

**Issue by aboulart** [sourcegraph/sourcegraph#4166]
- **Sourcegraph version:** 3.4 
- **Platform information:** Ubuntu 18.04 

#### Steps to reproduce:

Both on my local docker instance, and on the public sourcegraph.com search, I see weird behaviour when doing regex paren searches on repos. 

Example: https://sourcegraph.com/search?q=repo:golang/%28oauth.*%7Cbla%29+file

The query above doesn't return any results. If I remove the '.*', it returns results from golang/oauth2:

https://sourcegraph.com/search?q=repo:golang/%28oauth%7Cbla%29+file

I would expect both queries to return the same results from the golang/oauth2 repo. Am I doing something wrong? 

Thanks!

**Comment by keegancsmith** [comment]
@aboulart thank you for your report. We have a PR out which fixes the issue you saw. It will be out on Sourcegraph.com and the next minor release of Sourcegraph (3.5).

Note: In this case the `.*` is unnecessary since you do not include `$`, so `.*` implicitly is added. However, this did unearth a real issue in our repo search query optimizer that has been fixed.

**Comment by aboulart** [comment]
Hi, thanks for the speedy update. I noted that the PR references `.*` patterns, however that was just a test example. My real use case was something like `org/(prefix\..+|altToken1|altToken2)$` I hope that the query engine will eventually be able to handle any valid regex inside the `repo:` specifier. 

Either way, I've since found how to use `repogroup:`, which solves my use case even better. Keep up the good work!

**Comment by keegancsmith** [comment]
Ok great. Yeah I note in the PR there are more bugs lurking to solve. In general we support any regex, but try to avoid using postgresql’s regex support if we can for perf reasons. The bug is we sometimes do not fallback to regexes even though we should.
