### ISSUE TITLE
Repository page: Commit picker has slightly wrong layout

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#41714]
At the moment, commit picker has slightly wrong layout - suggestion items don't place the entire width of the suggestion panel. Maybe we also could reuse [combobox UI wildcard component](https://github.com/sourcegraph/sourcegraph/pull/41639) for this picker and therefore fix this problem and possible problems with layouts in the future and increase consistency in the codebase and in the product. 

Current:

<img width="589" alt="Screenshot 2022-09-17 at 18 51 21" src="https://user-images.githubusercontent.com/18492575/190865550-e4888fc1-ccec-4fdd-af20-9e5ff0bca657.png">

As in Wildcard:

<img width="549" alt="image" src="https://user-images.githubusercontent.com/6304497/191013300-07decd40-9e85-4549-8c8b-68ce8e882970.png">

/cc @benvenker @lguychard

**Comment by quinnkeast** [comment]
Updated OP to include current vs. Wildcard definition. @almeidapaulooliveira

**Comment by quinnkeast** [comment]
Some specific notes:

- Row items aren't full-width and have wrong left/right spacing internally.
- Background is body-bg instead of white.
- Badge is too large.
- "Find" input has incorrect left/right spacing and is the normal size rather than small size.
