### ISSUE TITLE
Get GITHUB_TOKEN from an app instead of using PAT

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#41728]
Right now, we've been seeing issues with rate limiting when using PATs, because they cap at 5k an hour. We have created bot accounts to deal with these cases, but that's a fairly cumbersome process (the last one we created got flagged, had to reach out the support to sort this out). 

Another solution would be to replicate the same logic we're seeing here https://github.com/peter-murray/workflow-application-token-action which would get us fresh disposable tokens we could use in CI, which is better for security purposes, as well as increasing the rate-limit to 15k req/hour.

**Comment by davejrt** [comment]
Tooling is now available via https://github.com/sourcegraph/sourcegraph/pull/42674

Any implementation should it be required can be captured in a new issue
