### ISSUE TITLE
Allow admins to revoke redis sessions from Site Admin

### ISSUE THREAD

**Issue by pjlast** [sourcegraph/sourcegraph#41720]
See https://sourcegraph.slack.com/archives/C03GMM0F2BA/p1663567147631619

Would be helpful if admins could manage user sessions themselves (would also help in cases where a user's laptop is lost or something similar).

/cc @sourcegraph/source

**Comment by taras-yemets** [comment]
@pjlast, @eseliger, the referenced Slack thread is no longer available. Can you please provide more context on it?

@unknwon and I briefly looked into this issue, and it seems that admins can already manage user sessions by forcing users to sign out in the admin interface. 

https://github.com/sourcegraph/sourcegraph/blob/3ee60cddb742a5e7b03e1137b4b301f91a36d94c/client/web/src/site-admin/UserManagement/queries.tsx#L65-L71
 https://github.com/sourcegraph/sourcegraph/blob/0fd4b2effb18b69b57c3bb6f8f682cec4fc7af8b/internal/session/session.go#L442-L447

**Comment by pjlast** [comment]
@taras-yemets this does indeed look like it has been implemented 🙏  I'll close the issue. Thanks for looking into it, our backlog is still a bit chaotic 🙇
