### ISSUE TITLE
Error: javascript is not defined

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#41745]
I got the following stacktrace while browsing stuff on sourcegraph.com

![CleanShot 2022-09-19 at 16 31 16](https://user-images.githubusercontent.com/1408093/191042266-6436e0c3-fa61-4f33-ad30-f3c7cb82724f.png)

```
Error: javascript is not defined
j — helpers.ts:22
dr — RepoRevisionSidebarCommits.tsx:106
mu — react-dom.production.min.js:166:139
gi — react-dom.production.min.js:289:389
hs — react-dom.production.min.js:279:392
ds — react-dom.production.min.js:279:323
fs — react-dom.production.min.js:279:180
es — react-dom.production.min.js:270:91
Ji — react-dom.production.min.js:267:432
Ji
S — scheduler.production.min.js:13:205
T — scheduler.production.min.js:14:128
(anonymous function) — startup:6
runTask — startup:6
invokeTask — startup:6
(anonymous function) — directives.ts:4
O — index.js:40
L — index.ts:5
```
![CleanShot 2022-09-19 at 16 30 14](https://user-images.githubusercontent.com/1408093/191042057-b60c078e-8e79-4816-95f6-48fb4e7014a4.png)

**Comment by olafurpg** [comment]
To reproduce, visit https://sourcegraph.com/github.com/gildas-lormeau/zip.js@4e47b6c5bccc337e919fef7e589b1dec6387823a/-/blob/lib/zip-full.js?L51:2#tab=references

**Comment by sqs** [comment]
I just encountered this as well. 

It comes from https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@422a96a798f25a9aba58c2e2cf860f6a07787c1f/-/blob/client/shared/src/codeintel/legacy-extensions/language-specs/languages.ts?L419.

I'm not sure of the scope of this bug, but it initially appears to occur whenever finding references on JavaScript code. If so, that would be patch-worthy for 4.0.

**Comment by sqs** [comment]
Draft PR in https://github.com/sourcegraph/sourcegraph/pull/42055. I don't have much experience in this part of the codebase. This PR should be taken over by a code intel team member (or whoever you think is best).
