### ISSUE TITLE
Hierarchical symbol sidebar

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#41778]
Currently, our symbol sidebar displays a flat list of symbols. To reproduce, visit https://sourcegraph.com/github.com/sourcegraph/maintainerbot/-/blob/sgbot.go

![CleanShot 2022-09-20 at 08 28 26@2x](https://user-images.githubusercontent.com/1408093/191183476-89604f47-2c0d-460e-a916-09b3c7387767.png)

Ideally, the sidebar should be hierarchical like the outline view in VS Code or IntelliJ

<img width="407" alt="CleanShot 2022-09-20 at 08 29 29@2x" src="https://user-images.githubusercontent.com/1408093/191183590-0fc6c530-e537-4310-bce9-829e001234d5.png">

<img width="1117" alt="CleanShot 2022-09-20 at 08 30 47@2x" src="https://user-images.githubusercontent.com/1408093/191183783-55c36c44-6282-4ec4-8bcc-1ed75a02314d.png">

**Comment by olafurpg** [comment]
It would also be nice if it was possible to populate the symbols sidebar with SCIP

**Comment by chrismwendt** [comment]
ctags has scoping info (notice `scope`, at least for Go):

```
$ # in gorilla/mux
$ ctags -R --output-format=json | tail -1 | jq
{
  "_type": "tag",
  "name": "wildcardHostPort",
  "path": "regexp.go",
  "pattern": "/^\twildcardHostPort bool$/",
  "typeref": "typename:bool",
  "kind": "member",
  "scope": "mux.routeRegexp",
  "scopeKind": "struct"
}
```
