### ISSUE TITLE
Perforce: create database migration to merge includes and excludes column

### ISSUE THREAD

**Issue by pjlast** [sourcegraph/sourcegraph#41780]
/cc @sourcegraph/iam

**Comment by malomarrec** [comment]
Hey @pjlast, this issue didn't have a team label. Given you created it, I assigned you and added your team label. Feel free to unassign yourself. If this is not the right label, can you make sure to add the right one?

**Comment by pjlast** [comment]
@malomarrec thanks, this was supposed to be deleted, but it seems it only deleted it from the GitHub Project and not the actual issue itself. Apologies. Will close
