### ISSUE TITLE
search: try a literal interpretation for queries (a.k.a. "always try everything")

### ISSUE THREAD

**Issue by ijt** [sourcegraph/sourcegraph#4178]
It would be useful if sourcegraph could interpret search queries literally rather than always assuming they are regular expressions. For example, if we search for the code snippet `for i := range`, sourcegraph search currently returns an error:

![Screen Shot 2019-05-22 at 17 43 00](https://user-images.githubusercontent.com/15530/58217758-0ff4b480-7cb9-11e9-9e12-501960b297d4.png)

Even if we correct the error by escaping the colon, the results are surprising:

![Screen Shot 2019-05-22 at 17 44 52](https://user-images.githubusercontent.com/15530/58217821-5cd88b00-7cb9-11e9-811d-39da609e4f77.png)

The query has apparently been reinterpreted as `for.*i.*\:=.*range` whereas the simplest interpretation would be that we wanted the literal string we asked for. To get what we want, the query has to be quoted:

![Screen Shot 2019-05-22 at 17 59 38](https://user-images.githubusercontent.com/15530/58218362-767ad200-7cbb-11e9-8ce3-095257e64083.png)

One way to make this friendlier would be for sourcegraph to always try the literal interpretation and give it precedence in the search results. This would be a better experience for users who don't know regexes. It would also be better in cases where a literal query is all that is wanted, and regexes are just getting in the way.

This issue is similar to https://github.com/sourcegraph/sourcegraph/issues/633, but there would be no guessing about what the query means. It would simply be interpreted both ways, and any results would be combined with literal matches showing up first. Later, we can also run queries with `:[foo]` as structural searches.

CC @slimsag, @keegancsmith, @sqs, @christinaforney

**Comment by keegancsmith** [comment]
I like the idea of preferring the literal matches. A simple way to implement this today is in our result sorting code to prefer shorter line matches to longer ones. However, this wouldn't resolve issues with writing the query.

**Comment by ijt** [comment]
> I like the idea of preferring the literal matches. A simple way to implement this today is in our result sorting code to prefer shorter line matches to longer ones. However, this wouldn't resolve issues with writing the query.

What issues are those?

**Comment by ijt** [comment]
@slimsag raised the interesting question of what to do for the query `.*` where the user wants to find the literal pattern of a dot followed by a star. As long as we show the literal results first, that should still be fine. The good matches will show up at the top if there are any.

**Comment by keegancsmith** [comment]
It doesn't look like this will ship for 3.6. Putting it onto the backlog for search to triage.

**Comment by rvantonder** [comment]
Literal search exists as of 3.9 so am closing this.
