### ISSUE TITLE
Use Draft instead of WIP in GitLab >= 14.0

### ISSUE THREAD

**Issue by Piszmog** [sourcegraph/sourcegraph#41796]
As of GitLab 14.0, [`WIP:` has been removed in favor of `Draft:`](https://docs.gitlab.com/ee/update/removals.html#wip-merge-requests-renamed-draft-merge-requests). If a customer is on GitLab >= 14.0, we should use `Draft:` instead.

[See code](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@rc/remote-mount-executor/-/blob/internal/extsvc/gitlab/merge_requests.go?L64-70) where we still default to `WIP:`.

### Related Issue

See #40290 where we no longer support GitLab < 12.0.

### Additional Considerations

* `Draft:` was introduced in GitLab 13.2. Prior, `WIP:` was the only way to mark a Pull Request as "work in progress"

**Comment by LawnGnome** [comment]
Given this breaks draft functionality in GitLab 14: P1, 1d? I _think_ it's pretty easy for us to check the GitLab version, from my recollection of the deprecation notice.

**Comment by courier-new** [comment]
Yes it should be! It sounds like this is also a bug, albeit one that not too many customers might be hitting. I might vote P0 since it sounds small.

**Comment by eseliger** [comment]
We already handle draft for the state detection, [would just need to add the version gate here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@es/startupctx/-/blob/internal/extsvc/gitlab/merge_requests.go?L59%3A1-76%3A2=) to the write operation, so 1d sounds totally fair to me.
