### ISSUE TITLE
Regression in repo contributors tab - v3.42.2

### ISSUE THREAD

**Issue by DaedalusG** [sourcegraph/sourcegraph#41825]
- **Sourcegraph version:** v3.42.2
- **Platform information:** 

#### Steps to reproduce:
1. Navigate to a repo page [https://sourcegraph.com/github.com/sourcegraph/sourcegraph](https://sourcegraph.com/github.com/sourcegraph/sourcegraph)
2. Select the Contributors tab and then any time range not `All time` [https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/stats/contributors?after=30+days+ago](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/stats/contributors?after=30+days+ago)

#### Expected behavior:
You should see a list of contributors on the repo
<img width="1311" alt="Screen Shot 2022-09-20 at 2 27 06 PM" src="https://user-images.githubusercontent.com/13024338/191367917-0764cf04-a4ad-4297-b557-268c5272c35f.png">

#### Actual behavior:
You'll receive the following errors
 
 Starting with these 400 errors
<img width="1344" alt="Screen Shot 2022-09-20 at 2 13 47 PM" src="https://user-images.githubusercontent.com/13024338/191368154-32faa7dd-7ab7-4738-9220-23171d9d599c.png">

Then eventually hitting this screen
<img width="1781" alt="Screen Shot 2022-09-20 at 2 17 24 PM" src="https://user-images.githubusercontent.com/13024338/191368130-c4a24ea4-da80-4842-853f-3c2216b0e0c5.png">

If would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are not [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

/cc @taylorsperry @muratsu

**Comment by sqs** [comment]
Fixed in https://github.com/sourcegraph/sourcegraph/pull/42050
