### ISSUE TITLE
RFE: add a notification for when repositories are deleted due to disk pressure

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#41826]
**Requested by:** https://github.com/sourcegraph/accounts/issues/6716 via [Slack](https://sourcegraph.slack.com/archives/C01D50MSA7L/p1663641853312449)

#### Feature request description

Send an alert when repositories are deleted due to disk pressure.

#### Is your feature request related to a problem? If so, please describe.

Once the disk space gets low enough for the services to start removing repositories to make room, the admin is not aware that this is happening.  And, looking at the dashboards you might assume that the disk space is staying constant, when in reality, it is actually just continuously deleting repos to stay above 10%.

#### Describe alternatives you've considered.

There is [an alert](https://docs.sourcegraph.com/admin/observability/alerts#gitserver-disk-space-remaining) for when disk space is getting close to the point of removing repositories (15% critical).  This tells you when `gitserver` at least is getting close to deleting repositories.

/cc @jplahn @ryphil

**Comment by mrnugget** [comment]
Fixed in two ways:

- we don't delete repos anymore
- we alert when you run out of space
