### ISSUE TITLE
zoekt: monitor vm.max_map_count

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#41849]
A hard to debug error in zoekt is hitting max_map_count. This manifests as golang failing to alloc memory. We should proactively monitor and warn:
- logging a warning if number of shards is within 5% of max_map_count (there are other users of mmap, so need to be conservative)
- ensuring we have this on a dashboard somewhere.

Leaving a breadcrumb here, but prometheus/procfs is likely a way to provide this sort of info (and others we have talked about cc @ggilmore)

See customer issue https://github.com/sourcegraph/customer/issues/1311

/cc @sourcegraph/search-core

**Comment by indradhanush** [comment]
> logging a warning if number of shards is within 5% of max_map_count (there are other users of mmap, so need to be conservative)

Would an alert be a better idea? 🤔

**Comment by keegancsmith** [comment]
@ggilmore do you wanna add an alert in sourcegraph based on this metric? Wanna be able to notice this going wrong.
