### ISSUE TITLE
Silent query state change for smart search

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#41888]
When smart search is active, and you add a `case:yes` filter, the filter will be removed and the URL/query state now stickies `case:yes`. But there is no longer a visible toggle that shows up on the right that indicates case sensitivity is sticky. This silent behavior is really bad, we either need to decide:

- (1) remove `case:yes` from the query bar as usual _and then also_ automatically disable smart search, and show the case-sensitivity toggles, and keep it active until the user decides to re-enable smart search. OR:

- (2) don't remove query filters like `case:yes` if we keep smart search enabled

In the early prototype where I added a lightning bolt toggle for smart search, I did (1), and I think that's still the right preference. 

/cc @benvenker @lguychard

**Comment by rvantonder** [comment]
Update: I see we do (1) when the query specifies `patterntype:regexp`, so then it's just a missing branch to handle `case:yes`/`case:no`. When `case:yes`/`case:no` is manually specified we just do the same thing we do for manually-specified `patterntype`.

**Comment by rvantonder** [comment]
@limitedmage I think this might be an easy fix?

**Comment by limitedmage** [comment]
Hmm I'm not super familiar with how we could do this. Maybe @fkling has a better idea of how this could be done, since he's more familiar with the search query state management?

**Comment by zhimin-z** [comment]
This might be related to [Issue#43491](https://github.com/sourcegraph/sourcegraph/issues/43491).

**Comment by peter-kehl** [comment]
Hi. If this issue applies to `sourcegraph.com/search` as-is, then please note that currently `sourcegraph.com/search` still "absorbs/consumes" `case:yes`, but at the same time it DOES activate/highlight the case sensitivity button. (See #62127).

Side question: What is "Smart Search" today on `sourcegraph.com/search`, does it still exist and how is it called? Is it enabled/disabled, and how can I activate/deactivate it?

Thank you for `sourcegraph.com/search`.
