### ISSUE TITLE
Husky's .huskyrc post-install scripts don't run on Windows

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [sourcegraph/sourcegraph#419]
Following #400, `.sh` scripts won't work on Windows.

PowerShell `.ps1`s would; would you like me to write those out? This kind of check works for `.huskyrc`, but if you have something cleaner that'd be nice 😉:

```json
{
    "hooks": {
      "post-merge": "node -e \"process.exit(!require('is-windows')())\" && powershell ./hooks/post-merge.ps1 || sh ./hooks/post-merge.sh"
    }
  }
```

**Comment by felixfbecker** [comment]
Are you sure `.sh` scripts don't work on Windows? Afaik git for Windows installs `bash`, which runs `.sh` scripts as a file handler. Note we use shells script everywhere for various build scripts (including the most important want, `./dev/launch.sh`). Our services also run Unix-specific syscalls in many places so running Sourcegraph on Windows is best done in WSL as mentioned in our dev guide: https://github.com/sourcegraph/sourcegraph/blob/master/docs/local-development.md#windows-support (although I agree that git hooks should be able to run in the Windows host as that is ran from e.g. VS Code, outside of WSL)

**Comment by JoshuaKGoldberg** [comment]
> git for Windows installs `bash`

Indeed, it does, and I can run these scripts normally. But the way Windows runs bash is a little wonky - although it's on the bash, Husky won't recognize it by default to run the files.

```
C:\Code\sourcegraph (master-> origin) (@sourcegraph/webapp@1.10.1)
λ git commit -m "temp"
husky > pre-commit (node v9.7.1)
'dev' is not recognized as an internal or external command,
operable program or batch file.
husky > pre-commit hook failed (add --no-verify to bypass)

C:\Code\sourcegraph (master-> origin) (@sourcegraph/webapp@1.10.1)
λ where bash
C:\Program Files\Git\usr\bin\bash.exe
```

**Comment by felixfbecker** [comment]
Interesting. I wonder how husky spawns these scripts.
Can you double click .sh files and they launch with bash?
Does it work for you if you prefix the huskyrc scripts with “bash ”?

**Comment by JoshuaKGoldberg** [comment]
> prefix the huskyrc scripts with "bash "

Oh, that does work! Thanks so much 😁 I'd never thought to do that. Will send a PR.
