### ISSUE TITLE
Allow negation of suggested repo: filter

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#4192]
> If I do a query, sourcegraph helpfully gives the boxes across the top to quickly narrow to repos. Is there any way to do the opposite and filter out repos? (eg, looking for something that shows up a lot, but want to know where it shows up outside of places I expect by interactively scoping out repos)

> > Yes, you can use `-repo:PATTERN` in your query to exclude repositories matching `PATTERN`. Most of the search keywords support negation; see https://docs.sourcegraph.com/user/search/queries for the details.

> > There is no 1-click button to do this for you - if that would be helpful (eg shift-clicking on a suggested repo filter negates it), let me know!

> yeah, the shift click type interactive approach would be great

1. Make shift-clicking a suggested `repo:` search filter cause its negation to be added. If the user is holding down shift and hovers the `repo:` search filter, the tooltip should say "Shift+Click: Exclude my/repo/name".
1. Make this work for all suggested search filters that support negation (I believe currently all suggested search filters support negation, but make this robust against us adding new ones in the future that do not, such as `type:diff after:"1 month ago"` for "Recent matching changes", for example).

(If the user always wanted to filter out the same set of repos, they could use a search scope with `-repo:pattern-to-exclude`, but in this case, it's a different set each time.)

See context at https://sourcegraph.slack.com/archives/C68386Z5Z/p1558651253000200.

Requested by a person at https://app.hubspot.com/contacts/2762526/company/407948923

**Comment by fkling** [comment]
We actually show the negated filters in the suggestions now as well.
