### ISSUE TITLE
Extensions: empty popover for dockerfile

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#41931]
![CleanShot 2022-09-22 at 15 24 14](https://user-images.githubusercontent.com/1408093/191759055-0b3ddb4b-733e-4baf-8d19-c6a9977c44b2.png)

To reproduce, hover over any token on this file here https://sourcegraph.sourcegraph.com/github.com/sourcegraph/src-cli/-/blob/Dockerfile

/cc @muratsu @jjinnii @ryankscott

**Comment by fkling** [comment]
For completeness this does not only impact Dockerfiles but all "plaintext" files, e.g. `.gitignore`, `README.md`, etc.
