### ISSUE TITLE
Create RFC for RBAC

### ISSUE THREAD

**Issue by courier-new** [sourcegraph/sourcegraph#41940]
- We enumerate the BC team's needs for (some part of) RBAC
- We set up a meeting with Petri and Raf G (and/or start an RFC) to determine a general direction as well as which parts of this the BC team will work on
- We break down and estimate (roughly) what kind of investment we're talking about, and prioritize accordingly

**Comment by courier-new** [comment]
Outcome of this is a plan and additional issues to get us to implementing RBAC and eventual batch change creation restriction.

**Comment by malomarrec** [comment]
@BolajiOlajide can you link the RFC and other work in progress here (for folks outside our teams scanning this)?

**Comment by BolajiOlajide** [comment]
RFC: https://docs.google.com/document/d/1mCg5-GiqRuBx2Hrls8lrYEfPMlzuZHmUQ4rCJd0JLeg/edit#

I'll add the tracking issue later once I'm done breaking down the work to be done.
