### ISSUE TITLE
Flash of white in dark mode when navigating to new pages in docs

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/sourcegraph#41963]
#### Describe the issue

When navigating to a new page on docs.sourcegraph.com, I see a noticeable flash of white in dark mode before the page loads. This is particularly jarring when performing searches, because every search results in a new page.

https://user-images.githubusercontent.com/93103176/191862565-1b1789ab-ecc6-4c3a-b7c1-cb21a19115f9.mov

#### Where is the issue located?

docs.sourcegraph.com

#### Suggested resolution

I don't know how to fix this, but it would be nice to avoid this flash.

**Comment by marekweb** [comment]
I'm seeing that the page first loads with `<body class="theme-light">` and gets switched to `<body class="theme-dark">` later during the page load. That might be causing the flash.
