### ISSUE TITLE
insights: reroute sentry alerts for code insights to team channel

### ISSUE THREAD

**Issue by CristinaBirkel** [sourcegraph/sourcegraph#41960]
If our pings object is `null`, (which means there was some error,) is there a way to hook into that and get an alert?

/cc @joelkw @felixfbecker @vovakulikov

**Comment by CristinaBirkel** [comment]
It looks like `Looker` has an Alerts feature. Maybe that could be useful in checking if data is coming back on `k8s` or `s2`? Would have to dig in more to find out, but just wanted to put down the thought.

**Comment by CristinaBirkel** [comment]
@coury-clark @leonore @chwarwick 

Just want to make a note here that the mitigation for future pings errors still needs alerts to be set up on `k8s` and `s2`, as desired.

I believe someone with admin privileges needs to set up the [alert on Grafana](https://sourcegraph.grafana.net/a/grafana-alerting-ui-app/?tab=rules&rulessource=grafanacloud-sourcegraph-logs). (Looks like we have some in the legacy system, but I think the new one should probably be in the new system.)

Here's an example where I made it error out to verify that errors were being logged: [grafana k8s logs](https://sourcegraph.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22dogfood-k8s%5C%22%7D%20%7C%3D%20%5C%22getAndMarshalCodeInsightsUsageJSON%5C%22%22,%22editorMode%22:%22code%22,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%221665979200000%22,%22to%22:%221666238399000%22%7D%7D)

A way to easily get it to error is to go into the `event_logs` db and add a string for the `index` argument for an existing `GroupResultsChartBarHover` ping. (It expects an int, so it errors.) Then you can revert it back when you're done testing the alert.

I didn't look as much into the GCP alert for `s2`, but was planning to use [this documentation](https://cloud.google.com/logging/docs/alerting/log-based-alerts) as a guide. And as Chris pointed out in the PR, it would be a good idea to check with perhaps the cloud team and see if it's okay to do this.

**Comment by felixfbecker** [comment]
P0?

**Comment by coury-clark** [comment]
I'm a little confused (maybe I'm missing some context about the background here). I think we use sentry for monitoring errors already, and we have a feed set up from s2 in [Slack](https://sourcegraph.slack.com/archives/C03V51C8K53/p1668025163551409). Given that, we would already get an alert in the case of an error from pings.

**Comment by felixfbecker** [comment]
I'd guess Cristina wasn't aware of that (tbh, I wasn't either). Does anyone monitor that channel? What prevented us from catching the issue through that channel earlier?

**Comment by chwarwick** [comment]
Rescoped to route any issues with "insight" to an insights channel in slack so that we are aware of it.

**Comment by coury-clark** [comment]
rescoping to reroute insights specific sentry errors to a team slack channel

**Comment by leonore** [comment]
@sourcegraph/code-insights-backend for review: I have created two rules (for **s2**), [one specifically for pings](https://sentry.io/organizations/sourcegraph/alerts/rules/s2/12750076/details/), and [one for general events containing "insights"](https://sentry.io/organizations/sourcegraph/alerts/rules/s2/12774698/details/) that we might want to revisit depending on noise that comes through. feel free to close issue on approval 👍
