### ISSUE TITLE
admin: add diagnostics page

### ISSUE THREAD

**Issue by ijt** [sourcegraph/sourcegraph#4196]
We currently validate our releases with laborious manual testing, running through a test grid on a spreadsheet. It would expedite our releases if we automated this process by adding a diagnostics page that runs these tests and some benchmarks. It would also help us track down customer reported issues by showing us test results and latencies within their environment.

**Comment by ijt** [comment]
CC @christinaforney, @beyang, @sqs, @chrismwendt

**Comment by beyang** [comment]
A few questions:
* Would this run the test suite in a separate docker container?
* Would this be something managed from the Sourcegraph web app itself, or run by someone externally
* Should we make this available to customers?
* If the data is stored in the Sourcegraph DB, will the test suite runner run with admin permissions? How will it impersonate other users?

What does the v0 of test automation look like? It seems like whatever we end up doing, we'll want to have some sort of script that can be run with a particular Sourcegraph instance URL. Should we start there first and worry about the presentation of the test results in the UI later?

**Comment by ijt** [comment]
> A few questions:
> 
> * Would this run the test suite in a separate docker container?

What I have in mind would run in the same process as the frontend, so no.

> * Would this be something managed from the Sourcegraph web app itself, or run by someone externally

Yes, this would be part of the Sourcegraph web app itself. One possibility would be to have a single page with a `Run Tests` button that would then run some typescript to hit various endpoints, one per test, and show the results in a table. That way, one test timing out won't affect the others.

> * Should we make this available to customers?

Yes. Then they can run the diagnostics and send them to us when things go wrong.

One risk would be that a bug in the diagnostics could cause problems in the instance, especially if it mutates the db or the `~/.sourcegraph` directory.

> * If the data is stored in the Sourcegraph DB, will the test suite runner run with admin permissions? How will it impersonate other users?

If you're talking about data from test results, we don't have to store those in the db. They can just be displayed on the diagnostics page.

We might want to have another page like this for non-logged-in users and another for logged in users who are not admin.

> What does the v0 of test automation look like? It seems like whatever we end up doing, we'll want to have some sort of script that can be run with a particular Sourcegraph instance URL. Should we start there first and worry about the presentation of the test results in the UI later?

I don't know of a good way to do this without some sort of UI. It doesn't have to be polished for a first version, and we could refrain from linking to it until we're happy with the user experience.

**Comment by chrismwendt** [comment]
What are some examples of customer issues that we could have tracked down faster with tests and diagnostics? Making tests specifically for those cases would probably be more effective than bundling the entire set of release tests into the app.

If we run these tests prior to release and they pass, in which cases would they fail for customers? What kinds of endpoints would the tests hit?

Between pre-release browser e2e tests and in-app error messages, where would these diagnostics fit?

**Comment by beyang** [comment]
Closing in favor of https://github.com/sourcegraph/sourcegraph/issues/4238. Currently not planning to implement any sort of UI until we have an automated test suite. Please comment on that issue.
