### ISSUE TITLE
CodeMirror: line selection UX 

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#41975]
Line selection in CodeMirror changes the behavior to only select lines when clicking on line numbers as well as token selection. This is different from the current implementation where we support line selection by clicking on whitespace for line selection. 

As sharing links to lines of code as well as tokens is an important use case for our users, this is a medium to high risk change. User testing should be utilized to gather additional data points to decide on a behavior that best serves our users. 

([Slack thread for reference](https://sourcegraph.slack.com/archives/C03PPPY5T6V/p1663854649172709))

**Comment by jjinnii** [comment]
## Design process

  - Estimate: One day to a week
  - Weighting factors: Medium risk, Medium certainty

  ### Discover
  - [ ] Existing customer feedback - Link
  - [ ] Product and/or engineering provide direction and/or feedback

  ### Define
  - [x] Github issue
  - [ ] Design challenge

  ### Design
  - [ ] Non-visual design guidance captured in the issue
  - [ ] Prototype - Link
  - [ ] Designer review

  ### Testing
  - [ ] Hallway testing - Link
  - [ ] Usertesting.com task based evaluation - Link

  ### Deliver
  - [ ] Loom - Link
  - [ ] Team review
  - [ ] Design team review
  - [ ] QA - Link

  ### Measure
  - [ ] Metrics defined in the Figma file ([i](https://handbook.sourcegraph.com/departments/product-engineering/product/design/metrics/defining-metrics/)) - Link
  - [ ] Followup task will analyze metrics to ensure successful completion - Link

**Comment by jjinnii** [comment]
As discussed in team sync today @fkling will look into achieving line selection parity with the old blob view. If effort is reasonable, we will aim for behavior parity with CodeMirror release, and additional changes/behaviors to line selection UX can be made in the future.

**Comment by fkling** [comment]
@jjinnii Not sure whether you want to do more with this issue or whether implementing the old behavior suffices to close this.

**Comment by jjinnii** [comment]
@fkling Yup since we've reached parity with the old behavior, this issue is no longer needed! We can re-open or create a new one in the future for when we want to introduce improvements to line selection UX.
