### ISSUE TITLE
4.0.1:  Patch release to fix broken code intel tooltip for blobs with no symbols/refs

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#41989]
@sourcegraph/release-guild I am requesting the following commits be included in a patch release. They are already merged into `main`:
- e2df224db1727d9b25e91001fc762e2b22ded136
- 367b874419cc498bcdd4f323f997d475be647b6f

---

The intent of the questions below is to ensure we keep Sourcegraph high quality and [only create patch releases based on a strict criteria.](https://handbook.sourcegraph.com/engineering/releases#patch-releases) If you can answer yes to many or most of these questions, we will be happy to create the patch release.

I have read [when and why we perform patch releases](https://handbook.sourcegraph.com/engineering/releases#patch-releases) and answer the questions as follows:

> Are users/customers actively asking us for these changes and cannot wait until the next full release?

This problem with popover seems like a very core functionality that we can't afford to have in a broken state. 

> Are the changes extremely minimal, well-tested, and low risk such that not testing as we do in a full release is OK?

Yes, they are extremely minimal and manually tested. 

> Is there some functionality completely broken that warrants redacting the prior release of Sourcegraph and advising users wait for the patch release?

Yes, the code intel tooltip has broken layout on the files that don't have proper symbols/refs (like *.md, *.txt and all files that we do not have LSIF metadata). See this PR for more details https://github.com/sourcegraph/sourcegraph/pull/41958

> This will interrupt our regular planned work and release cycle, taking one full working day of our time, and will take up all of our site admin's valuable time by asking them to upgrade or producing noise for them if they don't need to upgrade.
>
> Do you believe the changes are important enough to warrant this?

Yes.

> Patch releases are a signal we can do something better to improve the quality of Sourcegraph. Have you already scheduled a call (or created a google doc) to perform a [retrospective](https://about.sourcegraph.com/retrospectives) and identify ways we can improve?

https://docs.google.com/document/d/1VYnfQvr3wtgMz56R0Ty2BkiymI99kBVUeDv9jEVPLpI/edit?usp=sharing

---

**For the [Release Captain]** - after reviewing this request:

- [ ] **Comment on this issue** with a decision regarding the request.
- [ ] If you are a first-time [Release Captain], please review the high-level overview of the [patch release process].
- [ ] If approved, **add it to a patch release**:
  - If there is [already an upcoming patch release](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+), add the listed commits alongside a link to this issue.
  - If there is no upcoming patch release, create a new one:
    - [ ] Update [`dev/release/release-config.jsonc`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/release/release-config.jsonc), open and merge a PR to `main` to update it.
      - [ ] Change `upcomingRelease` to the current patch release
      - [ ] Change `previousRelease` to the previous patch release version
      - [ ] Change `releaseDate` to the current date (time is optional) along with `oneWorkingDayAfterRelease` and `threeWorkingDaysBeforeRelease`
      - [ ] Change `captainSlackUsername` and `captainGitHubUsername` to the patch captain's
    - [ ] Run `yarn release tracking:issues` on `main`
    - [ ] Add the listed commits alongside a link to this issue to the generated [release tracking issue](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+)
- [ ] **Comment and close this issue once the relevant commit(s) have been cherry-picked into the release branch**.

[release captain]: https://handbook.sourcegraph.com/engineering/releases#release-captain
[patch release process]: https://handbook.sourcegraph.com/departments/product-engineering/engineering/process/releases#patch-release-process

**Comment by camdencheek** [comment]
Forgot to respond here, but this patch request has been accepted and will be included in the 4.0.1 release today.
