### ISSUE TITLE
JetBrains: No JCEF is available with JetBrains Gateway

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#41991]
As reported by @mibali:

When opening the “Find in Sourcegraph” popup, the window doesn’t show the search box. It shows this error message:

> Your IDE doesn’t support JCEF. You won’t be able to use “Find with Sourcegraph”. If you believe this is an error, please raise this at [support@sourcegraph.com](mailto:support@sourcegraph.com), specifying your OS and IDE version.

OS: macOS 12.6
IDE: JetBrains Client 2022.2.1 ([JetBrains Gateway](https://www.jetbrains.com/remote-development/gateway/))
Plugin: 2.0.1

/cc @muratsu @jjinnii @ryankscott

**Comment by vdavid** [comment]
@mibali Actually, we've never tested with JetBrains Gateway (I didn't even know this tool TBH), so my next step is to look into what this is, how it works, and whether we can somehow make JCEF (the internal browser we use in the plugin) work with it.
One thing that you could ask in the meantime is whether the [Markdown plugin](https://plugins.jetbrains.com/plugin/7793-markdown) works for the same customer. This is a plugin developed by JetBrains. If it doesn't work then we probably can't do a lot.

**Comment by mibali** [comment]
Got it, reaching out right away!
