### ISSUE TITLE
insights: batch insert SeriesPoints data to database

### ISSUE THREAD

**Issue by leonore** [sourcegraph/sourcegraph#42009]
right now we store series point data through repetitive function calls to a single insert db function (see `RecordSeriesPoints`). we could make improvements by batching this into one call.

https://docs.sourcegraph.com/dev/background-information/sql/batch_operations

/cc @joelkw @felixfbecker @vovakulikov

**Comment by eseliger** [comment]
We're ready to help batching 😎
