### ISSUE TITLE
Signing out of SAML provider by clicking "Sign out of <name of SAML provider>" doesn't work

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#4200]
- **Sourcegraph version:** 3.4.1
- **Platform information:** Docker instance, running locally, using Okta as SAML provider

#### Steps to reproduce:

* Go to `/site-admin` on your Sourcegraph instance, copy the management console password, open the management console, insert the password
* Copy the Okta SAML config from our Sourcegraph internal dev `critical-config.json`
    * IMPORTANT: The Okta application in the configuration requires your Sourcegraph instance to run under port 3080.
* In the management console, under `auth.providers`, insert the copied Okta SAML config
* In the management console, add the top-level entry `"externalURL": "http://localhost:3080"`
* Save the changes
* Log out of your Sourcegraph instance (not the management console)
* Go to `/sign-in` and click on `Sign in with Okta SAML (dev)`
* Enter Okto credentials and log in
* You're redirect to Sourcegraph. Go to user menu, click "Sign out", expect to be signed out
* On the sign out page, click "Sign out of <name of the SAML provider>"

#### Expected behavior:

I'm logged out of Okta

#### Actual behavior:

I get a `400 Bad Request` response from Okta

<img width="557" alt="Screen Shot 2019-05-24 at 11 05 51" src="https://user-images.githubusercontent.com/1185253/58316478-f1570080-7e13-11e9-96b7-1de805793cfb.png">

**Comment by unknwon** [comment]
The milestone seems somehow messed up? It should be in 3.15 or backlog?

**Comment by unknwon** [comment]
We no longer have this option/button on sign-out page.
