### ISSUE TITLE
zoekt-indexserver: better behaviour for recurring index failing

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#42011]
Seen bad behaviour both on a cloud instance and at a customer. In those cases recurring OOMing lead to us not cleaning up the disk properly and disk space getting close to running out.

Here is the slack thread inspiring this https://sourcegraph.slack.com/archives/C023ELQLV7F/p1663933123986959

Here is my response on things we should do.

> does zoekt have a "disk pressure" mechanism similar to gitserver (to stop it from using all available disk)?

No. We'll plan for implementing this but we will track in a separate issue from 42011: see issue [42216](https://github.com/sourcegraph/sourcegraph/issues/42216).

> should indexserver give up on indexing repos that continuously produce errors (something similar to dead letter queue in queuing systems)?

Yes we should implement that.

> should indexserver prioritize cleaning up tempfiles ahead of indexing (so it doesn't consume all available disk on failed attempts, making it impossible to index correctly)

It deletes any tmp files older than 4h. However, I think the code is likely too naive and is missing out on the temporary clones which is likely the cause of the increased disk use. I think we should add something which creates a new $TMPDIR (under the current $TMPDIR) per job and cleans that up.

/cc @sourcegraph/search-core

**Comment by keegancsmith** [comment]
Ok it does seem we cleanup the temp clones properly, but we will need to wait 4h before cleaning up `.tmp` files. It seems like that may be the cause? So lets clear those out at the start of an index job for a repo. It is possible that maybe the oom killer is causing a coredump and that is filling up disks? But I doubt that is the case.

**Comment by gl-srgr** [comment]
@keegancsmith Sure i'll look into this

**Comment by mike-r-mclaughlin** [comment]
Additional details about the repository:
- 5.4GB
- Many binary files (including archives)

They are setting this repo up on a dev server now.  We can use that for debugging/troubleshooting more if needed.

**Comment by gl-srgr** [comment]
@mike-r-mclaughlin The backoff logic is completed but for JPMC specific troubleshooting we can continue the discussion in #1245.
