### ISSUE TITLE
blog post changelog link is broken

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#4205]
Go here: https://about.sourcegraph.com/blog/sourcegraph-3.4

At the top of the page click `📝 Changelog`

Links you to `#340-changelog` which is wrong, should be `#34-changelog`

**Comment by ryan-blunden** [comment]
Fixed in https://github.com/sourcegraph/about/commit/58ed545ddcc860a8503211aa373dce14ccd3f9f7
