### ISSUE TITLE
insights: `insight definition not found for series_id` when creating a scoped insight

### ISSUE THREAD

**Issue by leonore** [sourcegraph/sourcegraph#42077]
observed this behaviour locally when creating a *scoped* insight only and was able to reproduce on s2. two insights are created. only one of these insights is attached to a view, but we are wastefully creating two insights. 

this issue should look at the source of this problem and fix it

reproduction steps:
1. create a scoped insight
2. observe logs to see `insight definition not found for series_id` errors
3. observe database to watch two insight_series being created for the query at near-identical times, but one is deleted

expected behaviour:
* we only create one insight_series
* there is no such error log

/cc @joelkw @felixfbecker @vovakulikov

**Comment by leonore** [comment]
looks like this is coming from the webapp sending two separate calls on insight creation, one for create, one for update. 
<img width="358" alt="image" src="https://user-images.githubusercontent.com/29406849/192271027-3a8d8bb1-7ea1-44e5-9c73-2afda5ab1b47.png">

on first create we create the insight_series and attach it to a view
on the update call we have the insight_series we have the [series_id set](https://sourcegraph.sourcegraph.com/-/editor?remote_url=git%40github.com%3Asourcegraph%2Fsourcegraph.git&branch=main&file=enterprise%2Finternal%2Finsights%2Fresolvers%2Finsight_view_resolvers.go&start_row=607&start_col=16&end_row=607&end_col=16&editor=JetBrains&version=v2.0.1) so instead the view attachments are updated and the original insight is set as deleted

so the backend is working as expected. apparently this is a known issue but I haven't been able to find the original issue created for this, if anyone can find it and mark this as a duplicate or merge the two issues that'd be great

cc @sourcegraph/code-insights-frontend

**Comment by unclejustin** [comment]
Here is the duplicate issue: https://github.com/sourcegraph/sourcegraph/issues/36872

**Comment by vovakulikov** [comment]
Since the original problem on the BE has been fixed https://github.com/sourcegraph/sourcegraph/issues/27836
I think we should include https://github.com/sourcegraph/sourcegraph/issues/36872 in the next iteration (it should be a quick fix)
