### ISSUE TITLE
Get user management information from strategic customers

### ISSUE THREAD

**Issue by pjlast** [sourcegraph/sourcegraph#42080]
In order to implement a permissions syncing strategy with maximum impact, we need realistic information on how our customers manage user access to their repositories.

We have some information already, but I'll list a complete list of questions for completeness:

- How many users do they have?
- How many repositories do they have?
- What is the maximum number of repositories a single user has access to?
- What is the maximum number of users that have access to a specific repository? (one that's not marked as Public)
- How many users have access to a repository on average?
- How many repositories does a user have access to on average?
- Do they use code host groups/teams to manage user permissions?
- If not, how do they manage user permissions? Do they have a custom system that syncs between code hosts?

/cc @sourcegraph/iam

**Comment by ryphil** [comment]
Meeting requests:
- [IBM](https://sourcegraph.slack.com/archives/C037XJ5THK2/p1663904277636159)
- [JPMC](https://sourcegraph.slack.com/archives/C01U497GASZ/p1663904356042839)
- [Salesforce](https://sourcegraph.slack.com/archives/C043NFH7X3J/p1663904377070589)
- [Cap1](https://sourcegraph.slack.com/archives/C01SSSJR0GN/p1663904419364439)
- [MeLi](https://sourcegraph.slack.com/archives/C0294MXDZ17/p1663904842029149)

Are there any other pieces of information we want from them? Or just the above questions?

**Comment by malomarrec** [comment]
I'll tag along and ask questions about executors: cc @eseliger:
- Do you currently self-host CI agents? How does that work? How do you deploy workloads that run arbitrary user code, and what are isolation constraints?
- If SG deployed in kubernetes, is it in its own cluster? Or alongside other workloads? If so, what type of workloads?
- Lastly, what's the deployment model that makes more sense for executors (the equivalent of CI agents for Sourcegraph, that we use for precise code intel auto-indexing and running batch changes server-side) among those described [here](https://docs.google.com/document/d/16SVTBbuqAc2RizJBZgBRCfv5fsMVhR_a2QrIHnEh5T0/edit#bookmark=id.3abznnkwtb6i)?
  - VM-level isolation (current)
  - Expose a pluggable compute interface, allowing to run in a kubernetes namespace
  - Use docker-isolation / docker in docker with privileged containers?
