### ISSUE TITLE
ScaleTesting: Gigantic Git repositories

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#42092]
For now we have https://github.com/sgtest/megarepo (about 5Gb) and [gigarepo](https://k8s.sgdev.org/gigarepo) (about 10Gb) which are not big enough. 

Our target is 16k < X < 30Gb, with history.

**Comment by jhchabran** [comment]
Convo: https://sourcegraph.slack.com/archives/C040LV3PS4C/p1664300250417349?thread_ts=1663680855.500709&cid=C040LV3PS4C

**Comment by jhchabran** [comment]
https://github.com/sourcegraph/deploy-sourcegraph-scaletesting/pull/9

**Comment by jhchabran** [comment]
https://github.com/sourcegraph/infrastructure/pull/3978

**Comment by jhchabran** [comment]
https://github.com/sourcegraph/devx-scratch/commit/5ddc16dbdff686eadb6e93acf39cb267fb5d3e1f

**Comment by mucles** [comment]
[gigarepo](https://scaletesting.sgdev.org/gigarepo) is now available in the scale testing instances

**Comment by jhchabran** [comment]
https://github.com/sourcegraph/deploy-sourcegraph-scaletesting/pull/14
