### ISSUE TITLE
ScaleTesting: Perforce: Create gigantic Depot for testing purpose

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#42091]
Point of Contact: @ryanslade 

The RepoMgmt & IAM teams are trying to fix performance issues with `CUSTOMER` but do not have yet something to compare with. 

We tried importing Git repositories in order to have historical data, but it's incredibly slow and a total dead end. Therefore, we have to generate synthetic repositories on our own. 

- [ ] Size: 16 GB < X < 30 GB 
- [ ] Commits:  >=1000 commits (see https://github.com/sourcegraph/sourcegraph/issues/42091#issuecomment-1262536850)

**Comment by burmudar** [comment]
Generated a Repo in Perforce called `RacoonTest`. The depot contains a series of folders and files generated from a UUUID. There are a variety of different file sizes namely 1mb, 10mb and 20mb. The current size of the repo (depot) is 10 GB.

1. To generate new files and upload them to Perforce you can execute the following command on the synthforce tool `go run main.go -root ./Perforce -depot RacoonTest -client Williams-MBP -generate -filesizemb 20 -maxsizemb 5000` which will generate files with 20mb size and generate a total of files that amount to 5000mb (5GB)
2. If you have some generated files but they haven't been uploaded to perforce you can execute `go run main.go -root ./Perforce -depot RacoonTest -client Williams-MBP` and it will scan all the files in the depot and only upload the missing ones

**Comment by ryanslade** [comment]
cc @mollylogue @varsanojidan

**Comment by burmudar** [comment]
@mollylogue Definitely possible! What would be like a good amount of commits?

I'll start working on it and get back to you once it is ready.

**Comment by mollylogue** [comment]
I think we'd need >=1000 commits to effectively test

**Comment by burmudar** [comment]
Added a readme on how to use the tool in https://github.com/sourcegraph/synthforce/pull/5

**Comment by burmudar** [comment]
I've created a 20 GB depot named `devx-large-20GB`.

The depot has the following characteristics
* varying file sizes of 1, 2, 3, 5, 10, 15 mb
* contains `8356` files
* `2937` changes / commits

**Comment by burmudar** [comment]
I'm going to close this issue for now as the created depots seem adequate enough for current testing purposes.

@mollylogue Please don't hesitate to re-open this task or ask for larger or more varied depots!
