### ISSUE TITLE
ScaleTesting: Create a VM that we can use to run long-lived script 

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#42099]
Because most of the synthetic data generating scripts are usually taking a long time, we need to have a VM available to be able to run those without fearing to see them interrupted. 

A VM is the best choice there, and we already have one available at `gcloud compute ssh --zone "us-central1-a" "devx"  --project "davedev-sg"`. 

- [x] Document accessing the VM 
- [x] Make sure all DevX teammates can access it
- [x] Make sure all teammates from other teams working on this project can access it.

**Comment by davejrt** [comment]
VM is up and running, docs are up. Closing this.
