### ISSUE TITLE
ScaleTesting: Create and link Sentry project to capture errors yielded by tests

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#42095]
Our users need to be able to see what issues have been created when they are running their tests. Ideally, this should also be linked to a Slack channel where they can observe those issues.

**Comment by burmudar** [comment]
Added "scaletesting sentry token" to secret vault

**Comment by burmudar** [comment]
- [ ] Announced sentry project in `#wg-testing-at-scale` work group
- [ ] Created channel `#scaletesting-sentry` where new issues from sentry will be posted too
