### ISSUE TITLE
ScaleTesting: Save and restore the cluster.

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#42096]
At some point, we're bound to mess with a cluster so much that it'll be utterly broken. We don't want to spend hours restoring it to a blank slate. 

Therefore, we need a backup mechanism or a script to restore the cluster to the correct shape quickly. 

Should be included: 

- [ ] Admins (see all individuals working with us at this stage)
- [ ] Sentry should be linked
- [ ] Tracing should be wired.
- [ ] And of course, the instance should be usable out of the box.

**Comment by kalanchan** [comment]
i can work on this, i'm working out a new strategy for backups on dotcom as well so it's pretty relevant here

**Comment by kalanchan** [comment]
i think we can close/deprioritize this for now as we are moving towards job fair, and scaletesting has no SLA.

**Comment by sanderginn** [comment]
@kalanchan I agree, but perhaps you can set up a simple backup schedule for the attached disks (and VM snapshots if that makes sense)? It would be great to have the data secured in case we do need to restore.
