### ISSUE TITLE
🙆‍♂️ ScaleTesting: enable alerting so testers can be notified exactly like they would on a real instance. 

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#42102]
This is a stretch goal. 

The idea is that testers can see the same exact alerts they would see on a real instance.

**Comment by burmudar** [comment]
Monitoring is available at https://scaletesting.sgdev.org/-/debug/grafana/?orgId=1 allowing us to setup/activate alerts when we deem it necessary

**Comment by burmudar** [comment]
Closing this for now as complete. Teams are equipped now to enable alerting with monitoring being available.
