### ISSUE TITLE
"insert: pq: duplicate key value violates unique constraint" on clean 3.4.1 instance

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#4210]
- **Sourcegraph version:** Upgrading from 3.2.1 to 3.4.1
- **Platform information:** 

#### Steps to reproduce:

Reported by: 
* https://app.hubspot.com/contacts/2762526/company/887065580
* https://app.hubspot.com/contacts/2762526/company/693777177

1. Occurred immediately after the user ran into https://github.com/sourcegraph/sourcegraph/issues/4208

>4. I moved the data and config directories to a separate location (outside the docker volume mount location) and restarted with version 3.4.1.
>5. I added my external GitLab source as before. It took about 10 minutes to load.
>6. I saw the unique key constraint errors.
>
>7. I tried repeating 4-6, but with no success.

```
19:45:05       repo-updater | t=2019-05-24T19:45:05+0000 lvl=eror msg=store.upsert-repos error="insert: pq: duplicate key value violates unique constraint \"repo_name_unique\"" count=4235
19:45:05       repo-updater | t=2019-05-24T19:45:05+0000 lvl=eror msg=store.done error="syncer.sync.store.upsert-repos: insert: pq: duplicate key value violates unique constraint \"repo_name_unique\""
19:45:05       repo-updater | t=2019-05-24T19:45:05+0000 lvl=eror msg=Syncer error="syncer.sync.store.upsert-repos: insert: pq: duplicate key value violates unique constraint \"repo_name_unique\""
```

Code host: GitLab

External services config (redacted) is:

```{
  "url": "https://xxx.xxx.net",
  "token": "xxx",
  "projectQuery": [
    "?archived=false&visibility=public",
    "?archived=false&visibility=internal"
  ],
  "exclude": [
    {
      "name": "group/project"
    }
  
]
```

Find detailed logs in the thread at https://sourcegraph.slack.com/archives/C0W2E592M/p1558727607004600

**Comment by mrnugget** [comment]
@dadlerj What kind of PostgreSQL/Sourcegraph setup is the customer running? Are they using the Docker deployment? I'm asking because I'm wondering whether that step here would've cleared the database table:

> 4. I moved the data and config directories to a separate location (outside the docker volume mount location) and restarted with version 3.4.1.

**Comment by slimsag** [comment]
I am like 90% sure it is just vanilla sourcegraph/server (built in postgres)

**Comment by keegancsmith** [comment]
@dadlerj is the customer in a good place? We are trying to understand prioritisation of this issue for this milestone (ie work on ASAP or later in the milestone).

**Comment by dadlerj** [comment]
@mrnugget Stephen is correct, just basic docker image-based deployment. He can repro as well — he sees this after a fresh install.

@keegancsmith no, they've been offline since last Friday. I'm not totally sure what to ask to help us get a repro. See https://sourcegraph.slack.com/archives/CHPC7UX16/p1559061216008400 and https://sourcegraph.slack.com/archives/C0W2E592M/p1558797178018900?thread_ts=1558727607.004600&cid=C0W2E592M. Anything you can suggest here?

**Comment by dadlerj** [comment]
Looks like this hit https://app.hubspot.com/contacts/2762526/company/693777177 as well (see log message at: https://sourcegraph.slack.com/archives/CFNURMWHE/p1559240677000300)

**Comment by keegancsmith** [comment]
825b1534631375bc09a5908b4680fa8404b68b8a cherry-picked onto 3.4 as 970be8bb35cb7d2103704d55a63f855b695e89e6

**Comment by dadlerj** [comment]
@keegancsmith just to confirm, your comment above means that this got cherry-picked into 3.4.0, 3.4.1, AND 3.4.2? So new instances that start up using docs.sourcegraph.com won't have to worry about this?

**Comment by keegancsmith** [comment]
no, it is in the 3.4 branch. When distribution does another release (3.4.x) it will be included. FYI this issue only affects customers which have repositories with different repos but the same name case insensitively. So most customers should not be affected.

**Comment by dadlerj** [comment]
Cool, just wondering if I could email those two orgs listed at the top that ran into the bug. @slimsag owns communications with https://app.hubspot.com/contacts/2762526/company/693777177 on next steps to get to 3.4.x.

**Comment by slimsag** [comment]
@dadlerj No, this isn't released yet so don't email yet. I plan to ship it EOD tomorrow so we can email them Thurs. morning. See https://github.com/sourcegraph/infrastructure/issues/1505#issuecomment-498390625
