### ISSUE TITLE
insights: save default filters and save as new view are retriggering insight calculation for scoped insights

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#42116]
When looking at a scoped insight (limited to a set of repos), the post-hoc filtering functionality seems to be always retriggering insight calculation.

This will be very problematic when we introduce dynamic scopes.

/cc @joelkw @felixfbecker @vovakulikov

**Comment by coury-clark** [comment]
p1

**Comment by chwarwick** [comment]
There are a number of duplicate issues for this, part of this should be to find and link/close those.

**Comment by chwarwick** [comment]
p0
