### ISSUE TITLE
Unexpected HTTP error: 520 Origin Error on index:no search

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#4211]
For customer: https://app.hubspot.com/contacts/2762526/company/407948923/

Performing the search `(hunk|repository)resolver index:no timeout:1000s` returned ` HTTP error: 520 Origin Error on index:no search`

**Comment by slimsag** [comment]
Ah, this isn't a bug but rather is an issue that stemmed from this instance not supporting indexing earlier and me telling you to add `index:no`. Adding `index:no` works in e.g. searching across a single repo but across thousands just wreaks havoc so this is expected behavior.

No issue here.
