### ISSUE TITLE
Search results components hierarchy refactor

### ISSUE THREAD

**Issue by novoselrok** [sourcegraph/sourcegraph#42159]
## A sketch of the current situation

![sketch](https://user-images.githubusercontent.com/6417322/192514480-a42bbef6-d586-4bd0-a1e3-b7f99b776bfc.png)

## Rough refactor plan

* Ensure all search result types are covered by screenshot tests
* Refactor CommitSearchResultMatch
    * I believe the implementation can be simplified
    * It does not need to rely on VisibilitySensor since VirtualList already wraps all components in it
    * VSCode extension relies on it
        * We want to avoid refactoring the extension as well
        * Will have to figure out a way to make the changes compatible
* Refactor ResultContainer component
    * It’s used to render the title, description, and the star count
    * It controls collapsed/expanded state of the search result
        * Only the file content matches can be expanded, so it doesn’t make sense for the rest of the search results to have this functionality
        * This should be moved to individual search results components
    * Keep the title as a render prop
    * Use the children prop to render content
    * Also used in the VSCode extension
* Refactor FileSearchResult & FileMatchChildren
    * Preferably with fire
    * Way too much complexity in those two components
    * Split rendering line (content) matches, symbols, and paths into separate components
        * Render separately at the StreamingSearchResults list level
    * Rework line match grouping (LineRanking/ZoektRanking) and the expand/collapse functionality
        * Ideally, groups should only be calculated once
        * And then slice the groups array if you want to show fewer matches

/cc @benvenker @lguychard

**Comment by limitedmage** [comment]
I did a [recent refactor](https://github.com/sourcegraph/sourcegraph/issues/34237) of these components a few months ago, and yes, many components (especially CodeExcept) are incredibly complex, and changes I had to make were very tricky and time-consuming. From my experience with that refactor, there should be good enough test coverage that we can be confident that any changes we make don't break stuff, but it wouldn't be a bad idea to double-check.

**Comment by fkling** [comment]
Since don't have much insight into the actual components I probably can't give that much feedback, but what you wrote seems reasonable to me. A couple of notes:

> Preferably with fire

I don't understand 😅 

> Render separately at the StreamingSearchResults list level

I read that as trying to flatten component hierarchy (or at least pulling things up), and I very much agree. Maybe this can also be done for other components. We should have smaller/simpler components that can be composed rather than deeply nested components.

Some things that weren't called out specifically (that may or may not be applicable in this specific situation):
- Reduce use of rxjs if it makes sense
- Decouple "business" logic from React as much as possible

**Comment by novoselrok** [comment]
> > Preferably with fire
> 
> I don't understand 😅

Haha, I just meant that it might be easier to start from scratch rather than trying to refactor the existing components 😄 

> > Render separately at the StreamingSearchResults list level
> 
> I read that as trying to flatten component hierarchy (or at least pulling things up), and I very much agree. Maybe this can also be done for other components. We should have smaller/simpler components that can be composed rather than deeply nested components.

Agreed.
