### ISSUE TITLE
First 10 users on an instance should only cost $10 total

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#422]
- [x] Update pricing page @dadlerj (@francisschmaltz to do design)

- [x] Update pricing docs @dadlerj 

- [x] Update plans in billing system @KattMingMing 

- [ ] Add note to all 'purchase a license' (and equivalent) CTAs @dadlerj

**Comment by sqs** [comment]
@dadlerj This is implemented now. Do you have more updates to make, or can we close this?

**Comment by dadlerj** [comment]
Still would like to add a notif to the /pricing page! @francisschmaltz, going to reassign you here. We can keep this super-simple, and if you're busy this week, I can take a first shot — let me know.

**Comment by sqs** [comment]
Ping on this
