### ISSUE TITLE
GitLab OAuth no longer available for unlicensed instance in v4.0

### ISSUE THREAD

**Issue by LER0ever** [sourcegraph/sourcegraph#42215]
#### Question description

The GitLab OAuth feature (which provides SSO login support for self-hosted GitLab instances) seems to be moved behind a paywall and no longer available to the free tier in SourceGraph 4.0.  This is not documented anywhere in the [Changelog](https://docs.sourcegraph.com/CHANGELOG) / [Release notes](https://about.sourcegraph.com/blog/release/4.0) or [Upgrade note](https://docs.sourcegraph.com/admin/updates). It was available on the same instance running 3.43.x and was silently disabled during the upgrade to 4.0.1. 

Just want to confirm this is indeed an intentional change for v4 to remove a feature from free tier and break feature availability / backward compatibility in upgrade without a notice, rather than a mistake / bug.

#### Additional context

The following notice appeared as a banner after upgrading to v4:

> A Sourcegraph license is required to enable following authentication providers: GitLab OAuth. [Get a license.](https://src.rongyi.io/site-admin/license)

![CleanShot 2022-09-27 at 19 07 06](https://user-images.githubusercontent.com/10568668/192671216-fe04f269-f580-49f2-a00f-93d213925aab.png)

If would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are not [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

**Comment by philippe-granet** [comment]
See https://github.com/sourcegraph/sourcegraph/discussions/42399

**Comment by malomarrec** [comment]
Hey @malomarrec, it looks like this issue was created by someone outside Sourcegraph. Assigning you to triage it! Please answer and route to the right team by adding their team label, then **remove** the `triage-bot/needs-triage` label

**Comment by malomarrec** [comment]
Hello - This sounds like it was resolved, so I am closing the issue. Re-open and ping me if needed!
