### ISSUE TITLE
Mark a repo as corrupted if it fetch / clone fails as a result of repo corruption

### ISSUE THREAD

**Issue by indradhanush** [sourcegraph/sourcegraph#42213]
Blocked by:
- [x] #42394 
- [x] https://github.com/sourcegraph/sourcegraph/issues/42852

TODO:

- [ ] Detect a failed fetch / clone as a result of repo corruption
- [ ] Ensure that the `last_error` column in the `gitserver_repos` table is also updated with the failure message

/cc @jplahn @ryphil

**Comment by indradhanush** [comment]
We can use the error message to detect the repo corruption. For example see [this](https://github.com/sourcegraph/customer/issues/1236). Also this [list](https://github.com/sourcegraph/customer/issues?q=is%3Aissue+repo+corrupt+is%3Aclosed) of issues with repo corruption for more signal.

**Comment by ryphil** [comment]
@indradhanush - Are you actively working on this? If not, can you remove yourself from the assignee?

**Comment by mrnugget** [comment]
@burmudar isn't this fixed?

**Comment by burmudar** [comment]
> @burmudar isn't this fixed?

Yip it is! Apologies, I'll link the PRs and close this tomorrow

**Comment by burmudar** [comment]
This is fixed by the following PRs - they're stacked so only linking the first of the stack

- https://github.com/sourcegraph/sourcegraph/pull/45667

Related PRs
- https://github.com/sourcegraph/sourcegraph/pull/46413
- https://github.com/sourcegraph/sourcegraph/pull/46410
