### ISSUE TITLE
Investigate approaches for a SCIP indexer for C++

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/sourcegraph#42280]
There are a few different approaches which are possible:
1. New Clang-based indexer: Build a new indexer from scratch. There are two different sub-options:
    - Build on top of libclang
    - Create a new fork of Clang/LLVM and build on top of that
2. New Apple Clang-based indexer: Build a new indexer on top of Apple Clang. There are a few different sub-options here:
    - Fork Apple Clang and get it to emit a custom SCIP index (instead of the current index format)
    - Fork IndexStoreDB and add a separate indexer binary to it
    - Consume IndexStoreDB as a library and create a new indexer on top of that.
3. New Glean-based indexer: Fork the C++ indexer in Glean and make it emit SCIP.
4. Update lsif-clang to recent Clang + get it to emit SCIP.
5. Modify clangd to emit SCIP indexes.
6. Modify searchfox to emit SCIP indexes.
7. Add Kythe -> SCIP conversion (at least, as much needed for the C++ indexer) and use Kythe's C++ indexer.

This issue can be marked as resolved once we've settled on what approach we will take. One expected artifact of this work would be an RFC describing the observations made, trade-offs involved and suggested decision.

**Comment by varungandhi-src** [comment]
I've added some comments about the current status of different indexers here: https://github.com/clangd/clangd/issues/1340#issuecomment-1284895543

Copying the main table:

Indexer | Base | Index format | Feature completeness
--- | --- | --- | ---
clangd | Upstream LLVM | Custom | I don't know this one. Are there known gaps for Objective-C, Windows etc.? Known perf issues? Is it robust in face of unimplemented libc++/Clang features? (I can take a look at the issue tracker here...).
[Kythe's C++ indexer](https://github.com/kythe/kythe/tree/master/kythe/cxx/indexer) | Upstream LLVM | Kythe (Protobuf) | Based on some exploration of the Chromium codebase, many common things do work, but Find References in certain headers doesn't seem to work reliably (as one example). Should support cross-language code nav with Protobuf, but it didn't seem to work for me.
[Glean's C++ indexer](https://github.com/facebookincubator/Glean/tree/main/glean/lang/clang) | libclang 12† | Glean (Thrift) | Used in prod at Meta, but I don't have any live code examples, and they don't seem to have many snapshot tests, so it is hard to tell.
[libIndexStore](https://github.com/apple/llvm-project/tree/apple/main/clang/tools/IndexStore)+[IndexStoreDB](https://github.com/apple/indexstore-db) | apple/llvm-project | Custom, shared with Swiftc | This powers navigation for Clang-based languages in Xcode; largely works well. In conjunction with Swiftc, supports cross-language code nav for Objective-C and Swift.
mozsearch/searchfox | libclang v?? | Custom (JSON) | Seems to work well based on a brief look
lsif-clang | Forked LLVM 12 | LSIF (JSON) | There are some known issues with stability. Having forked LLVM is also not great for maintenance.

†I think Meta internally uses closer to upstream LLVM/Clang for their indexer, but any related patches have not been made part of the OSS Glean distribution yet.

**Comment by varungandhi-src** [comment]
Writing down some notes here on the challenges, constraints etc. here, that we need to keep in mind for whatever solution we end up deciding on.

(If you have small questions etc., prefer using the Sourcegraph-internal Slack or public [Sourcegraph Discord](https://discord.gg/2Dz7aAUmKT) so that this thread can stay focused. But responding here is OK too if either of those is not preferable for some reason.)

## Robustness

Given the feedback loops with some customers, not-super-fast baseline Clang speed, large codebase sizes, if (in the worst case) there is a crash when indexing a single file, the rest of the indexing process must keep going. I'm thinking of having a multi-process architecture so that we can get this right in a reliable way. Related notes:
* [Boost.Interprocess](https://www.boost.org/doc/libs/1_80_0/doc/html/interprocess.html) provides many utilities for writing multiprocessing code.
* [nelhage/rules_boost](https://github.com/nelhage/rules_boost) makes it possible to consume Boost libraries from Bazel.

## Feature parity+ with clangd, CLion etc.

C++ has a lot of language features which potentially require special attention and testing. Clang will do a lot of the heavy lifting for us, but we need to make sure that we're behaving correctly for many different kinds of code. Some examples of features that may potentially stress code navigation:

* Go to def and Find refs for macros: Can we handle also macro arguments too (on a best-effort basis)?
* SFINAE, ADL
* Template specializations
* Implicit conversions (should we specially mark references to implicit constructors?). How will these be surfaced in the UI? (See also: #43348)
* Multiple inheritance
* Very large nested templates

Even if we decide to build on top of clangd directly, we need to test that indexing actually supports the various features that clangd supports.

## Cross-repo support

We need a way of mapping file paths to project information (name, version). We'd need the build information to plumb through this information to the indexer. The format needs to be flexible enough so that it can potentially handle complexities like depending on "system" libraries (i.e. anything installed outside the build but that is getting pulled in by the build). The problem of figuring how how to get the source code for relevant system libraries into the Sourcegraph instance would likely need to be dealt with by the customer.

## Controlling duplicate work (CPU and memory)

Repeated header processing can take up a lot of time. I'd earlier landed a [patch in lsif-clang](https://github.com/sourcegraph/lsif-clang/pull/85) which, based on some upstream changes, cut down on duplicate processing by quite a bit. Similarly, searchfox has some file-locking going on. We need to make sure to implement this optimization as best as possible.

We also need to figure out how to do de-duplication in the presence of multi-config indexing (see point below).

## Multi-config indexing

* There may be many different build configs of interest. The most common would be DEBUG/NDEBUG, but arch-specific code would also matter in some situations.
* There may also be different build targets of interest, which may share headers. How much can we de-duplicate information during indexing? What do we need to aggregate indexes before uploading? What de-duplication do we need to do during aggregation?

## Build system support

* We should have easy integration with CMake, as that is one of the most popular build systems. This probably just takes the form of accepting the compilation database format as an input, but we should make sure that this works.
* Some large Sourcegraph customers use Bazel for C++ builds. Ideally, we would support a simple way of plugging the indexer into the Bazel build graph. [Aspects](https://bazel.build/extending/aspects) seem like the right abstraction for this approach -- we would create:
    * One indexing action for every "generate object file for C++ translation unit" action.
    * One index aggregation action for every linking action.
  At the end, you would optionally need an extra aggregation action which combines all "top-level" indexes which were generated. There may be more than one "top-level" index because you may be indexing different build configs separately, and you'd have one index per config.

## Compatible with incremental indexing

For sure, we want to add incremental indexing at some point because some C++ codebases are just too large (even doing distributed indexing whole-sale every time would be too resource intensive). If the indexer is operating on individual files and dividing the work, I think this should most "just fall out" as a consequence, but we need to be careful about avoiding any design decisions which would perhaps accidentally make incremental indexing unfeasible.

## Standard library

Some customers use GCC, which comes with libstdc++. Clang is bundled with libc++, not libstdc++. Based on some quick googling, it seems like Clang will link against libstdc++ by default on Linux. Customers may also be using different versions of libstdc++. We should try our best to make sure that the right stdlib is used. There are some open questions here:
* Is Clang able to use headers from most/all recent libstdc++ releases?
* Do we create a special repo for libstdc++/GCC in the Sourcegraph instance for customers using GCC?
* Do we create a special repo for libc++/Clang in the Sourcegraph instance for customers using Clang? For executors, passing `-stdlib` for libc++ should emit references for libc++ headers.

## Deployment

* Can we create (mostly) static binaries that avoid dependencies on things other than libc? This would make usage and testing easier.

## Infrastructure

* We will very likely need custom Buildkite infrastructure with Bazel or CMake+sccache, as well as a largish build cache, to have decent build times.
* It would be very valuable to be able to have integration tests for large repos, but this may be a maintenance challenge too. Maybe we should have periodic tests instead of PR testing here?
* Can we have testing infrastructure using asserts builds, and/or with sanitizers?
* We need to decide on the branching/merging strategy from Clang upstream (if we're not working in upstream directly). Are we importing LLVM as a Bazel dependency? If so, how regularly should we update which version we use? If we're using a fork, should we have automergers and/or a separate stabilization branch (similar to apple/llvm-project)?
  * If we're working from a fork, we should try to isolate changes as much as possible, and try to upstream generally useful changes to reduce chances of conflicts. So far, we haven't run into many issues with scip-ruby, but the pace of LLVM development is much higher compared to Sorbet, so the cost of carrying patches is larger.
  * With Bazel, it is possible to have extra patches on top of upstream. We should try to merge patches upstream if possible so that we're not maintaining extra patches for too long, because these will potentially be a headache when updating LLVM.

## Complexity budget

* Working with C++ already has a lot of complexity, and we have limited C++ expertise at Sourcegraph. Clang is also a complex codebase, and many parts are not well documented. It would be preferable to have a similar tech stack as scip-ruby (esp. Bazel) to avoid folks having to be familiar with CMake. It seems like upstream LLVM's unofficial Bazel build config is reasonably stable (it is consumed by Kythe etc.); it would be nice to reuse that compared to forking.

**Comment by varungandhi-src** [comment]
I spent some time last week and today investigating Kythe's C++ indexer. I'm reporting my observations so far below: (TU = translation unit = (roughly) C++ file with included headers)

* Extraction seems to take about half the time as a debug build. The extracted output is later used by the C++ indexer. The extractor generates 1 kzip per translation unit. For reference, Clang/LLVM has about 6M lines of code, and a Clang build has about 4.4k TUs.
* With good temperatures, indexing a TU seems to take about 1x~3x the time for a debug build.
* The indexer works on a per-TU basis. Parallelism is added by a separate driver on top (which can be as simple as using GNU parallel along with every kzip). This means that de-duplication across indexes has to be done after generating all indexes.
  * However, there is an experimental flag `--experimental_dynamic_claim_cache=--SERVER=localhost:11211` which can utilize a running memcached to do some de-duplication during indexing. This did seem to reduce indexing time for me, but I didn't see the memory of the memcached process increase, so not sure what was going on there.
* There are two different kinds of indexes, the "normal" ones and a "lite" index (via `--experimental_index_lite`).
  * The largest uncompressed non-lite index I've seen was 2.5GB, but these are routinely 500MB+.
  * Lite indexes seem to about 2x-3x smaller and indexing takes about half the time.
  * Indexes are heavily compressible; on compressing with `gzip` with default settings, the size becomes about 1/12-th to 1-8th of the original. Even so, compressed indexes are very large compared to our existing indexes. E.g. if you take a 20MB compressed index per TU, 4.4k x 20M ~ a 88GB index for a single index of Clang/LLVM would be way too much. In contrast, the 99 percentile compressed index size on Sourcegraph.com is currently 66MB (and this is probably inflated due to the inefficiency of LSIF). Granted, Clang/LLVM is a very large codebase, but the scale is not unusual if we compare to customers' scale.
  * The very large index sizes have been mentioned multiple times on the [Kythe mailing list](https://groups.google.com/g/kythe). I/O throttling was also mentioned here. Indeed, I [saw my SSD heat up](https://unix.stackexchange.com/questions/723067/kythe-code-indexing-processes-being-throttled-despite-normal-cpu-temperature/723068#723068), causing heavy throttling, slowing down indexing to a crawl; a full index of Clang took over 6 hours, in comparison to a full debug build which took about 10 minutes on that machine.

Given the above, I'm a little negative on building on top of Kythe. The Kythe C++ indexer does seem to be doing a fair bit of heavy-lifting, but the current output seems ill-matched for what we're prepared to handle, and very different from what our other indexers emit. In particular, consuming Kythe output directly and massaging it to SCIP seems like a bad idea. Instead, cutting down on the output right when/before it is being created is probably the better approach.

One of the next steps here would be to do some back-of-the-envelope calculations on what index sizes we'd get with a potential standalone SCIP indexer, assuming some "reasonable" numbers for de-duplication efficiency, density of occurrences, pre-processed TU sizes etc.

If we do decide to build on top of Kythe, we should do the following first:
* Figure out where exactly we'd hook into the emission process.
* Look into what is going on with the dynamic claiming, and why it didn't seem to dramatically shrink emitted indexes (Or if it did, why memcached's memory usage didn't change).

**Comment by varungandhi-src** [comment]
(These notes were shared internally in Slack earlier, but putting them up publicly for future reference.)

Some customers use GCC, and have asked if we will be implementing support for indexing via GCC. I do not think that is a feasible approach, at least, not for the main C++ indexer that we write/maintain/support. Instead, we will have to build on top of Clang. Here are some of the reasons why:

1. There are several options which could help us write a Clang-based indexer much faster than a GCC-based indexer.
2. Clang is commonly used on all 3 platforms, whereas GCC isn’t.
3. If we want to support Objective-C at some point, we need to have a Clang-based indexer
4. Clang/LLVM has a larger community around its development, making hiring (relatively) easier
5. The IDE tooling ecosystem around Clang is growing, whereas the one around GCC is sparse~non-existent from what I know. Customers are using Clangd-based tooling anyways and have some level of Clang support because of folks using VS Code etc.
6.  Clang will likely eventually catch up to GCC in terms of feature parity (and we can help plug those gaps if needed and if headcount permits — it is somewhat of a scoped problem), but getting GCC up to speed in terms of Objective-C support or MSVC compatibility / Windows support will likely be much harder, and is more of an unscoped problem.
7. GCC uses the GPL license and an indexer built on top would also have to be GPL; some customers are strongly averse to GPL.

Basically, my point is that, if we’re going to be writing two C++ indexers anyways (which I’m not convinced is entirely necessary — and would require serious maintenance effort), I think it makes sense to first write the one that gives us greater coverage. We will still be able to do cross-repo (except for the caveat around modules) which gives the wow factor.

So far, we have had some customers try out lsif-clang and it does work to some extent, except for issues around performance, stability, feature incompleteness and lack of cross-repo support. Briefly discussing these on-by-one:

- Performance: We can profile & fix individual things — GCC is not much faster than Clang. Main thing here is we need to integrate with the build system to be able to parallelize across machines and largely have a no-shared architecture.
- Stability: Fixable with a slightly different architecture (multi-process instead of multi-threading). Multi-process requires reducing and/or eliminating sharing, so it would be complementary to perf-oriented no-shared architecture.
- Feature incompleteness: This can be mostly be built on top of Clang, barring very new features.
- Lack of cross-repo support: Fixable on top of Clang.

**Comment by varungandhi-src** [comment]
Copying an abbreviated version of some of my [internal notes on Glean's C++ indexer](https://sourcegraph.slack.com/archives/D02JS6R0EA2/p1656937350347279) from early July here:

> I spent a bit on Saturday and all of today trying to get the C++ indexer in Glean to work. Just building it from source took a bunch of time due to type-checking and linking errors, but that’s done now. The public CI pipeline has been failing for about 7 days now, which is a little concerning.
>
> I’ve been working on a Google cloud machine on Linux, which is also slowing me down a bit (didn’t even try macOS since it isn’t supported and the corresponding GitHub issue from someone received 0 attention). One of the problems is that the error messages on failure have little detail. The use of Haskell means that exceptions don’t even give stack traces by default, not helping with debugging.
>
> I still don’t have it fully working (generating a Glean database, not talking about LSIF or SCIP here).

I did manage to get it working the next day with a CMake based project and I was able to use the accompanying REPL to query the database.

Some of the concerns I had at the time:
- Debugging: Potential problems with troubleshooting indexing issues on customer codebases, especially if there are failures/crashes. Having stack traces is essential.
- Clang support: The most recent Clang version in the Glean docs is Clang 12, so the support for newer Clangs hadn't been upstreamed.
- Deployment: The indexer involves several binaries and dynamically linked libraries. It would be simpler for customers if there were a single statically linked binary.

**Comment by varungandhi-src** [comment]
I was looking at the size of preprocessed output for LLVM as an example. Out of 4504 TUs 

Statistic | clang -E ... \| wc -l | SLOC
---: | ---: | ---:
q1      | 83.5K | 79
median |  116K | 195
q3      | 166K | 534
max    | 1M | 41K
sum    | 575M | 2.6M
mean  |  128K | 587
stddev  | 61K | 1468

(The SLOC numbers exclude headers.)

If I run till type-checking only, then on a 10 core MacBook Pro, the code is type-checked (via `-fsyntax-only`) in about 9m16s. So it seems like type-checking is happening at about 100K lines/sec on pre-processed output (575M / (10 x 9 x 60) ~ 106.5K).

For TypeScript (as an example), the Sourcegraph monorepo has about 300K SLOC TypeScript which translates to an uncompressed 65M SCIP index. At that same rate (big assumption), without de-duplication, an uncompressed index for LLVM would be 124GB. If we're looking at SLOC directly, then the ~7M SLOC of C and C++ code in LLVM translates to a more reasonable 1.5GB.

This means that we probably want to have nearly perfect de-duplication, which is kinda' what is roughly true for most headers; most of them do not expand differently in different contexts. This also means that we probably do not want to do de-duplication after-the-fact. Rather we'd detect "ahead-of-time" which headers expand differently. Headers which expand the same way will be assigned to some specific job for indexing. Other jobs can skip over method bodies in such headers and avoid recording index information.

^ This bit seems to largely mimic what is described in the Kythe docs for claiming, so I'm wondering if its claiming implementation is working as expected (I would expect indexes to be smaller if the static claiming was working correctly). Maybe we can reuse some of the implementation bits from there...

**Comment by varungandhi-src** [comment]
After my investigations above, I think the approach we should go for here is to
- Implement our own SCIP indexer, taking inspiration from bits of Clangd, Kythe etc. on an as-needed basis.
- The SCIP indexer would build directly on top of Clang main (and not an existing indexer) which we'll update regularly
- Uses Bazel as its build system

Below, I'll briefly describe the rationale for why I think this is the right decision.

The key things we need to optimize for are:
- Technical requirements:
  - High-quality indexer output
  - Robustness in face of errors, esp. because we may have slow feedback loops with some customers
  - Low overhead over pure type-checking (the indexer shouldn't be an order of magnitude slower).
- Process requirements:
  - Ease of maintenance with at most 1-2 engineers working on the indexer full-time for the foreseeable future.
  - Ease of iteration and shipping changes (e.g. cutting releases, running CI quickly)
  - Ease of customization for Sourcegraph use cases, such as special support for autoindexing, distributed indexing, incremental indexing etc.

Here is how the recommendation above aligns well with the requirements:
1. Implementing our own SCIP indexer.
   - Quality & performance are fully under our control (we can decide on the number of AST traversals etc.)
   - We can use a multi-processing architecture for robustness (I've already been prototyping this in the scip-clang repo).
   - Working by ourselves lets us move quickly -- working upstream with an existing indexer requires consensus-building for lots of things, which is likely to be time-consuming because of time zones, company boundaries etc. It also reduces iteration speed because of PR review latency, CI not necessarily being under our own control, etc.
   - We can introduce dependencies we need on 3rd party libraries as we see fit. There are some good 3rd party libraries used in scip-ruby, and being able to use the same inside scip-clang would make working across the two codebases easier.
2. Building on top of ToT Clang.
   - None of the existing indexers fit our needs very well; since the other indexers are OSS, we still can pick and choose specific parts of code from other indexers on an as-needed basis (yes, we need to properly handle licensing and attribution, but that's not a big deal).
   - Other indexers building on top of Clang instills confidence that it is possible with reasonable effort to build an indexer on top of Clang, whereas with GCC there is less clarity of how much work would be needed.
   - Using Clang main instead of libclang allows us to freely use "internal" headers, and we can use more natural C++ APIs instead of C APIs. As two examples, both Kythe and Glean (kinda') build with Clang main, and the Kythe docs mention this is because libclang doesn't expose all the necessary APIs.
3. Using Bazel as the build system:
   - Bazel is easier to use and debug compared to CMake.
   - LLVM's unofficial Bazel support is widely used, so there is low risk.
   - Bazel handles dependency management, avoiding the need to use a separate package manager like Conan, installing build deps system-wide, vendoring or using submodules for deps, or working inside a Docker container or VM.
   - scip-ruby already uses Bazel, and the Sourcegraph monorepo is also exploring using Bazel, so using Bazel here makes working across codebases easier.

I believe none of the other options in my [original comment](https://github.com/sourcegraph/sourcegraph/issues/42280#issue-1390662560) do a better job of meeting these requirements.

**Comment by varungandhi-src** [comment]
I've created an [issue in the scip-clang](https://github.com/sourcegraph/scip-clang/issues/2) repo tracking what's needed for the first release.

**Comment by varungandhi-src** [comment]
Answering a question I got in Slack which is kinda' related to this issue: (paraphrased for brevity)

> Several large prospects and existing C++ customers that are actively asking about C++ (so not counting some customers happily running lsif-clang) seem to be:
> * [Redacted1](https://github.com/sourcegraph/accounts/issues/8004): P0 -- using GCC
> * [Redacted2](https://github.com/sourcegraph/accounts/issues/7229): High priority (not captured as a P) -- using Clang/GCC but moving to GCC
> * [Redacted3](https://github.com/sourcegraph/accounts/issues/564): Existing customer/renewal -- unknown but potentially using GCC
> * [Redacted4](https://github.com/sourcegraph/accounts/issues/3078): P1 -- using Clang and GCC
> * [Redacted5](https://github.com/sourcegraph/accounts/issues/238): P1 -- unknown (Varun's inline note: I have justified belief that they are at least using Clang in a non-trivial capacity)
>
> If we're building on top of Clang, what does that mean for customers using GCC? That there will be extra steps?  That they may encounter certain errors? What are some other implications?
>
> Also, I'm curious about what the 1% that isn't compatible (between Clang and GCC) looks like, would it just mean we can't navigate there, that the indexer barfs etc.

Customer experience should be that it should "just work" independent of whether they're using Clang or GCC. Discrepancies should be fixable bugs. Generally, we will ignore unknown stuff and keep ploughing ahead.

The 1% is a bit broad, but it would fall into a few different categories of things:
1. Unsupported CLI flags: These are quite likely to be related to optimizations or codegen, so it shouldn't matter.
2. Unsupported attributes: Attributes don't really matter for code navigation, so we can just ignore these.
3. Lagging support for newest language features: This is the big one and kind of an unknown. If Clang crashes inside an implementation file, the blast radius will be limited to a single file. If Clang crashes inside a header, the blast radius will spread to every implementation and header file directly or indirectly including the bad header. If Clang emits an error inside a declaration, we can limit the blast radius to within the declaration and any other declarations that transitively reference the bad declaration. However, Clang crashes are bugs (for both supported and unsupported features), and patches for crashes would be welcome upstream without needing to implement the full feature.

We will need to check with upstream docs and folks on the differences and add dedicated tests for these to gain confidence.

> Related: with 3 confirmed Bazel users (+1 suspected Bazel user), are we targeting Bazel support with the MVP?

For Bazel users, generating a compilation database (a JSON file carrying all compilation invocations) is not hard. Every customer using Bazel seems to already be doing this anyways for clangd to work. The indexer MVP will piggyback off this same file.

Based on the [time for type-checking I posted earlier](https://github.com/sourcegraph/sourcegraph/issues/42280#issuecomment-1342500849), and the overhead numbers for Apple's indexer (about 2-5% according to their docs) which does comparable work, scip-clang should be able to process about 15K-25K SLOC/min/core. For a 150M SLOC codebase, that translates to about 6000-10000 core minutes. On a high core count machine (GCP N2D machines have 224 cores), that is about 25~45 minutes (excluding the time to generate the compilation database). So indexing every commit on a main branch would not be possible during peak hours with the MVP (no incremental or distributed build support), but it shouldn't be too bad.

**Comment by i-ky** [comment]
> If Clang emits an error inside a declaration

Indexer can define a macro (e.g. `__sourcegraph_cpp_indexer__`) and problematic code can be "hidden" behind a few `#ifdef`'s.

**Comment by varungandhi-src** [comment]
> Indexer can define a macro (e.g. __sourcegraph_cpp_indexer__) and problematic code can be "hidden" behind a few #ifdef's.

I think suppressing errors is the right default because many customers have a LOT of code, and we do not want people to pepper their code with macros for what is a moving target. Ideally, we would have graceful recovery which avoids needing this.

> -specs is one of GCC-specific flags, that clang does not support and if a GCC-targeted project makes use of spec files, then making it work with clang-based tooling is a huge pain.

Thanks for flagging this; I wasn't aware of this functionality. My current (unconfirmed) hypothesis is that at least for customers, since they're already using Clang-based tooling, they've probably have `-fsyntax-only` working fine, which means there is at least some build configuration where this flag is not used. But I can check, and if this is indeed an issue, we can consider adding a workaround or a reasonable-enough subset of a full implementation.

**Comment by HighCommander4** [comment]
> 3. Lagging support for newest language features:

In addition to new language features (which clang presumably at least plans to support even if it doesn't yet), there may also be language extensions that gcc supports that clang doesn't (and may not even plan to).

One example that has [come up in clangd](https://github.com/clangd/clangd/issues/1342) is [nested functions](https://gcc.gnu.org/onlinedocs/gcc/Nested-Functions.html).
