### ISSUE TITLE
[placeholder] RFC 741 proposal B – scoped repo list of insights

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#42295]
Project lead TODO. 

Design issue TODO. 

[RFC](https://docs.google.com/document/d/1vWxSDSbslZQFEK24rhlo8-K2sCiaaCX5PQoCqEdpI_8/edit#heading=h.fk19ml1xzjrd). 

/cc @joelkw @felixfbecker @vovakulikov

**Comment by Joelkw** [comment]
Sync notes: 
- Primarily a backend-led project
- there's a doc of ideas somewhere we'll link to the RFC that @coury-clark  has 
- @CristinaBirkel will take on project lead 
- Is rewriting queue management part of this? That's separate / or is it? 
    - Some pieces like observability are difficult to get to, how much work will be done, how much is remaining
    - Dynamic list is faster / that requirement necessitates a change to how the backend process works 
    - Differentiating this feature vs all strategic work 
    - There is work to be done on the scheduler to support this, whether it's faster or not 
- Job of the project lead is to structure this project to include the necessary improvements to make this usable / functionally able to run

**Comment by coury-clark** [comment]
I've created the label insights-dynamic-scope for this project

**Comment by CristinaBirkel** [comment]
Closing in favor of the tracking issue: https://github.com/sourcegraph/sourcegraph/issues/42328

**Comment by CristinaBirkel** [comment]
@coury-clark I see a note in Joel's comment: "there's a doc of ideas somewhere we'll link to the RFC that @coury-clark has." What is that?
