### ISSUE TITLE
Code intelligence on Stackoverflow code snippets

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#423]
#### Feature request description

When browsing a Stackoverflow page like https://stackoverflow.com/questions/1760757 it would be nice to have code intelligence on snippets in the question and answers via our browser extensions. Code intelligence would only work on snippets where (1) we can detect the language without a file extension hint and (2) are well formed enough for code intelligence to work (e.g. a self contained program).

#### Proposed implementation

Given our current architecture, we can only provide code intelligence on code that exists in a Git repository. The proposal here is to build a Git proxy service than transforms a page on Stackoverflow to a git repository. This service will be hosted by Sourcegraph (e.g. on git.sourcegraph.com).

Using https://stackoverflow.com/questions/1760757 as an example, here is a hypothetical sketch of what should be possible:

```shellsession
$ git clone git.sourcegraph.com/stackoverflow.com/questions/1760757
$ cd 1760757
$ cat 1766304-1 # the first snippet in the answer with id 1766304
package main

import (
    "bytes"
    "fmt"
)

func main() {
    var buffer bytes.Buffer

    for i := 0; i < 1000; i++ {
        buffer.WriteString("a")
    }

    fmt.Println(buffer.String())
}

$ cat 23857998-1 # the first snippet in the answer with id 23857998
BenchmarkConcat  1000000    64497 ns/op   502018 B/op   0 allocs/op
BenchmarkBuffer  100000000  15.5  ns/op   2 B/op        0 allocs/op
BenchmarkCopy    500000000  5.39  ns/op   0 B/op        0 allocs/op

$ cat 23857998-2 # the second snippet in the answer with id 23857998
package main

import (
    "bytes"
    "strings"
    "testing"
)

func BenchmarkConcat(b *testing.B) {
    var str string
    for n := 0; n < b.N; n++ {
        str += "x"
    }
    b.StopTimer()

    if s := strings.Repeat("x", b.N); str != s {
        b.Errorf("unexpected result; got=%s, want=%s", str, s)
    }
}

func BenchmarkBuffer(b *testing.B) {
    var buffer bytes.Buffer
    for n := 0; n < b.N; n++ {
        buffer.WriteString("x")
    }
    b.StopTimer()

    if s := strings.Repeat("x", b.N); buffer.String() != s {
        b.Errorf("unexpected result; got=%s, want=%s", buffer.String(), s)
    }
}

func BenchmarkCopy(b *testing.B) {
    bs := make([]byte, b.N)
    bl := 0

    b.ResetTimer()
    for n := 0; n < b.N; n++ {
        bl += copy(bs[bl:], "x")
    }
    b.StopTimer()

    if s := strings.Repeat("x", b.N); string(bs) != s {
        b.Errorf("unexpected result; got=%s, want=%s", string(bs), s)
    }
}

// Go 1.10
func BenchmarkStringBuilder(b *testing.B) {
    var strBuilder strings.Builder

    b.ResetTimer()
    for n := 0; n < b.N; n++ {
        strBuilder.WriteString("x")
    }
    b.StopTimer()

    if s := strings.Repeat("x", b.N); strBuilder.String() != s {
        b.Errorf("unexpected result; got=%s, want=%s", strBuilder.String(), s)
    }
}

$ git fetch # fetch the latest version of the files (in case answers have been updated).
```

The generated repository doesn't need to have a commit history, it can just be a single commit of the current content of the site. If the content of the site changes, then the proxy will create a new git repo with a single commit (as if the history was force pushed).

The commit should have a git tag pointing to it that encodes the timestamp of the most recent update to the code snippets on the page. In the case of Stackoverflow `max(question created timestamp, question edited timestamp, answer created timestamp, answer edited timestamp)` (e.g. `2018-08-28_08-24-36`)

The first goal is for Stackoverflow, but the implementation should be designed in a way that makes it easy to add support for other sites in the future.

#### Alternatives considered

1. Put code snippets into Gists and then perform code intelligence on those gists. We would need to write some service that translates a page (like Stackoverflow) to code files and then uploads them as a Gist. Instead of doing the latter it seems simpler to just ephemerally host the git repo directly from this service.
2. Modify our architecture to remove the requirement that code exists in a git repository. This would either require adding code paths everywhere that allow passing file contents directly instead of a git repo (which would be an invasive change), or create a Sourcegraph API that creates temporary git repos only on gitserver (that isn't hosted anywhere else). We still need to write webpage -> git repo logic and add special cases, so the proposed solution seems better.

**Comment by nicksnyder** [comment]
Thanks for the offer @antham! We currently have someone else tentatively scheduled to work on this in the next week or so, but we'll let you know if the situation changes.

**Comment by antham** [comment]
Ok fine.

**Comment by faec** [comment]
A few high-level questions as I'm starting on this:

- What kind of traffic magnitude do we expect? Are there other platform considerations? I don't know how Sourcegraph hosts things like this, but I'm guessing this is expected to run on a single machine or maybe sharded across a few, and that it probably doesn't have to be too deeply tied to Sourcegraph-specific infrastructure or deployment procedure? I'm essentially thinking of adding a binary under `cmd/` that serves static files out of an on-disk repository cache, updating them in the background when they get stale. Should incoming requests be rate-limited or anything?
- I imagine we'll want to fetch the backend data via the stackexchange API (both to be considerate and because getting an app key for it will increase our request quota)? Does Sourcegraph already have this setup somewhere, and if not can someone with the appropriate permissions [get a request key](https://api.stackexchange.com/docs) that the proxy can use?
- It looks like we're already depending on `go-git`, so I assume it's ok / preferred to use this for repo manipulation?

**Comment by nicksnyder** [comment]
For traffic, our Chrome extension currently [45k users](https://chrome.google.com/webstore/detail/sourcegraph/dgjhfomjieaadpoljlnidmbgkdffpack) according to the store. Imagine how often these users go to stackoverflow and hover over some code. We will probably hide this behind a feature flag in the browser extension to start.

I imagine our first deployment of this service will be a single node, but in the future we might have multiple nodes with a load balancer in front. The nodes shouldn't need to be aware of each other though.

Optimize for simplicity first, and scale second. It would be ideal if this service was as lazy and stateless as possible. For example, it shouldn't automatically update anything. Instead, it should be completely driven by requests from our system. The rough lifecycle is:

1. User visits Stackoverflow.com with Sourcegraph browser extension enabled
2. Browser extension makes request to Sourcegraph.com for code intelligence
3. Our internal infrastructure detects either:
    - We don't have this git repo cloned to our system, so our gitserver calls `git clone git.sourcegraph.com/stackoverflow.com/questions/1760757` which is handled by the proposed service here.
    - We have this git repo cloned to our system but we detect it is outdated so gitserver and performs a `git fetch` for the repo (which is also handled by this proposed service).

The point of the above is that our gitserver already handles caching and refreshing, so to a first approximation this proposed service just needs to serve data on demand.

Your target can be a Go binary that runs a http server and exposes the routes defined in the spec (e.g. `git clone http://localhost:8080/stackoverflow.com/questions/1760757`. If your service would benefit from writing files to disk (e.g. a cache), make the location configurable with an environment variable. If you are writing to disk, make sure there is a clear lifecycle for that data (e.g. when does the cache get garbage collected so we don't grow unbounded?). The port should also be configurable with an environment variable. For production, the Go binary needs to run in a Docker image, but that is not the important part so I would do it last if I were you (and I can help with that if necessary).

Using the stackexchange API sounds ideal. We don't already have a stack exchange key setup, so you can create a test one for yourself for development. Make it configurable via an environment variable when running the server.

I only see [one usage of go-git in our app](https://sourcegraph.sgdev.org/search?q=go-git+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:%5C.go%24+). Most of the time we just [run git commands](https://sourcegraph.sgdev.org/search?q=Command%5C%28%5C%22git%5C%22+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:%5C.go%24+), but in any case do whatever is easiest/simplest for what you need to accomplish.

**Comment by faec** [comment]
Ok, your comments sound like more or less what I expected. A potential yellow flag is that the stackexchange API has a default cap of 10K calls / ip / day (and we might need multiple calls per fetched question). We could get more if we get users to authenticate to stackexchange before calling our proxy, but that seems undesirable. It's possible we could talk to them about getting more quota, though.

**Comment by nicksnyder** [comment]
As a comparison, GitHub's rate limit is 5k/hour or 120K/day (12x higher than Stackoverflow) and we are able to manage that on sourcegraph.com currently. 10k / ip / day might be problematically low in the long run, or it might not. Doing an auth dance seems inconvenient for the user.

What if the design was changed to be as follows:

1. User visits stackoverflow.com/questions/1760757 with Sourcegraph browser extension enabled and hovers over a piece of code.
2. The browser extension gets the necessary code data (either by calling the API from the browser, or by querying the raw dom) and pushes it to the new proposed service to create a git repo.
3. The browser extension then sends the normal code intelligence requests and the rest of the flow proceeds as before.

The difference here would be that we are pushing data to the new service, where it should be cached on disk with a short TTL, or LRU algorithm.

Thoughts?

cc @ijsnow would be curious to hear your thoughts too

**Comment by faec** [comment]
Maybe this is already implicit in your suggestion, but it seems like at this point there's ~no connection left to stackoverflow, and we might as well just expose a general public api for creating ephemeral git repositories from arbitrary short code snippets: The client sends a POST with a (filename -> content) map, we return a short URL that can be used to clone the corresponding repo for the next $TTL minutes.

Stackoverflow is still a natural initial deployment for the browser extension, but in general we could extend coverage as fast as the extension can learn to recognize code blocks, and potentially make it available as a general tool for others to integrate with. We could do user- or IP-based rate limits to keep things feasible, and boosted rate limits would be a natural perk for upgraded or enterprise accounts.

**Comment by nicksnyder** [comment]
Yeah, the per-site logic would live in the browser extension so the services could be pretty site-agnostic, as you described.

We do need to make sure there is a stable identifier for the git repo, which kind of implies that the client needs to provide the identifier when creating the repo.

e.g.

POST /create-ephemeral-git-repository (name not important)
```
{
    "id": "stackoverflow.com/questions/1760757",
    "files": {
        "path/to/a/file": "file content"
        "file-at-repo-root": "file content"
    }
}
```
Then I should be able to git clone a repo using that ID with those two files.

**Comment by faec** [comment]
What do you mean when you say "stable identifier?" I would have thought we wouldn't want clients choosing the key in a more generic API because of the possibility of contention -- I was expecting we'd auto-generate a unique id and return it on successful request. With the current scope it doesn't seem like there's enough potential redundancy to be worth using a shared repo for a duplicate url, especially if the creation / update requests are coming from untrusted sources.

Also, what kind of TTL were you thinking of? I was thinking of something on the order of <1 hour in the typical case, given the initial use cases, but is there a reason to have something longer or to persist ids over a longer time span?

Finally, I'm inclined to enforce a flat single directory for the initial implementation (everything in repo root, no subdirectories), because allowing arbitrary paths is slightly more sensitive and (as far as I know?) we have no use case that would benefit from it. But let me know if you think it's important to support subdirectories too.

**Comment by nicksnyder** [comment]
I agree that avoiding duplication isn't that important.

For debugging, I think it would be nice to have semantic ids though, so perhaps we can do both things:
1. Client provides a "name" field (e.g. "stackoverflow.com/questions/1760757")
2. Server returns a unique ID that contains the name. It might append a timestamp, or a short random string (e.g. "stackoverflow.com/questions/1760757-dejfys") that would make it unique in the cache.

> <1 hour

Sounds good to me!

> I'm inclined to enforce a flat single directory for the initial implementation

Yeah, folders are unnecessary.

**Comment by nicksnyder** [comment]
This is was a venture idea and is no longer a priority.
