### ISSUE TITLE
Observability

### ISSUE THREAD

**Issue by quinnhare** [sourcegraph/sourcegraph#42307]
**Summary:** As of today we have no automation related to observability. In terms of obersverability and our operational maturity we are at the lowest level because we are relying on customers' complaints and logs. 

- [Observability North Star (pitch)](https://docs.google.com/document/d/19bPH4Zxb8zl4DwDyOMfdSx5o4PI3UkshGsAh89QBdlM/edit?usp=sharing)

**Status:** Ongoing work; Observability is a piece of work that we can always make better so this will always be a part of our team's efforts but we would like to make significant strides on this over the next 6 months. 

**Goal over next 6 months:**

- Improved debugging
- Tracking SLOs

**Benefits:**
- Improves teams ability to achieve strategic readiness
- Allows our teams to move away from being reactive by testing scale instead of relying on our customers to report issues

**Comment by malomarrec** [comment]
Hey @quinnhare, this issue didn't have a team label. Given you created it, I assigned you and added your team label. Feel free to unassign yourself. If this is not the right label, can you make sure to add the right one?
