### ISSUE TITLE
Scale Testing

### ISSUE THREAD

**Issue by quinnhare** [sourcegraph/sourcegraph#42306]
**Summary:** Enable teams to be able to test out their features at scale (ie large amount of users, repos, large size of repos, etc)
- [Codehost Scale Testing](https://docs.google.com/document/d/1f9GcEpqJ5KA3YvfsOy48mdhILkvJZrqD9SfpZoNlQTg/edit?usp=sharing)

**Status:** We have released V0, working on getting codehosts in place and creating large repos. 

**Goal in Next 6 Month:** Get tooling and automation in place; anyone can reproduce customer instance on their own and be able to test freely; these tools should be tracking usage and other metrics (think how we track sg)

**Benefits:**

- _Improves teams ability to achieve strategic readiness_
- Allows our teams to move away from being reactive by testing scale instead of relying on our customers to report issues

**Comment by malomarrec** [comment]
Hey @quinnhare, this issue didn't have a team label. Given you created it, I assigned you and added your team label. Feel free to unassign yourself. If this is not the right label, can you make sure to add the right one?
