### ISSUE TITLE
GCP Cost Savings

### ISSUE THREAD

**Issue by quinnhare** [sourcegraph/sourcegraph#42305]
**Summary:** Over the past few months we’ve identified cost saving opportunities in GCP and have prioritized optimizing our infrastructure to become as cost efficient as possible. We have made changes to our infrastructure in Cloud which will realize over $50k/month in savings - with further improvements on the way.
- [Ownership of GCP Cost reduction](https://docs.google.com/document/d/1EaVPITPNBubfW2T8a8irJH-wFmgqd4j6Pkf70rCSwDA/edit?usp=sharing)

**Status:** We have identified cost saving opportunities and made changes to our infrastructure in Cloud to reduce costs.

**Goal over next 6 months:** We will complete most of the most major GCP cost saving efforts over the next month 
- Note: Over the longer term we may initiate further improvements such as creating centralized dashboards for teams  to view their spend and add in tooling to efficiently scale clusters down based on load. This is not be committed to within the next 6 months.

**Benefits:** 
- Cloud optimization will save us >$600k/year in spend
- It starts the conversation among teams to be more aware of their spend and resource allocation
- Reduce tech debt by removing things we don’t need, and finding better solutions
- Stretch goal is to reduce by $1M/year

**Comment by malomarrec** [comment]
Hey @quinnhare, this issue didn't have a team label. Given you created it, I assigned you and added your team label. Feel free to unassign yourself. If this is not the right label, can you make sure to add the right one?
