### ISSUE TITLE
Batch Changes repo page nav button flashes when toggling action bar

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#42302]
https://user-images.githubusercontent.com/10532611/193103981-103b2bce-2a79-4054-b1e3-77a435460d10.mov

**Comment by chrispine** [comment]
Assuming this is a quick fix, P0?

**Comment by courier-new** [comment]
P(-1), I just fixed it. 😉

**Comment by chrispine** [comment]
killing it!
