### ISSUE TITLE
insights RFC 741 proposal B: design for running insights over partial sets

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#42333]
This issue/the design needs are both to – 

1. Answer product questions (with user research/prototypes/technical research) like the ones listed [in the RFC](https://docs.google.com/document/d/1vWxSDSbslZQFEK24rhlo8-K2sCiaaCX5PQoCqEdpI_8/edit#bookmark=id.fch8wwll1mh5)
2. Create implementation designs for allowing users to set "groups of repos" to run the insight over

/cc @joelkw @felixfbecker @vovakulikov

---

## Design process

  - Estimate: Two weeks to one month
  - Weighting factors:
    - MEDIUM risk
    - MEDIUM clarity

  ### Discover
  - [x] RFC
  - [ ] Existing customer feedback - Link
    - [ ] NPS scores
    - [ ] Feedback submissions
    - [ ] Customer support requests
  - [ ] Self serve quantitative analysis - Link
  - [ ] Light Analogous / competitive research - Link
  - [ ] Internal users - Link
  - [ ] External users - Link, Link

  ### Define
  - [x] Product document or RFC - [Link](https://docs.google.com/document/d/1vWxSDSbslZQFEK24rhlo8-K2sCiaaCX5PQoCqEdpI_8/edit)
  - [x] Github issue
  - [x] Design challenge / Eng challenge ([link](https://docs.google.com/document/d/1U_tkYhT1Ai2klXZ9NKllhP_RwXp82cNedaez7rvbnnU/edit#))

  ### Design
  - [x] Low fidelity design - [Link](https://www.figma.com/file/ZUSD4DTNBdGGomLn6uKZFj/RFC-741-proposal-B%3A-design-for-running-insights-over-partial-sets-%2342333?node-id=260%3A11)
  - [x] High fidelity design using design system - [Figma](https://www.figma.com/file/ZUSD4DTNBdGGomLn6uKZFj/RFC-741-proposal-B%3A-design-for-running-insights-over-partial-sets-%2342333?node-id=275%3A1628&t=GMWdOya3IdEK6dvz-4)
  - [x] Prototype - [Link](https://www.figma.com/proto/ZUSD4DTNBdGGomLn6uKZFj/RFC-741-proposal-B%3A-design-for-running-insights-over-partial-sets-%2342333?page-id=1902%3A11036&node-id=1902%3A19598&viewport=305%2C392%2C0.05&scaling=min-zoom&starting-point-node-id=1902%3A11037)
  - [x] Designer review
  - [x] [Loom](https://www.loom.com/share/d1cb4f02230d442db648f32bb3a1313d)

  ### Testing
  - [ ] Hallway testing - [Scenario](https://docs.google.com/document/d/1BXRi8Ta3Tlz_iSevqBjN8yCC72jHyb7oEmXn-L-y9h0/edit#heading=h.g0gjwch98szj), Link
  - [ ] Usertesting.com task based evaluation - Link

  ### Deliver
  - [ ] Announce in #progress
  - [ ] Loom - Link
  - [ ] Team review
  - [ ] Design team review
  - [ ] QA - Link

  ### Measure
  - [ ] Metrics defined in the Figma file ([i](https://handbook.sourcegraph.com/departments/product-engineering/product/design/metrics/defining-metrics/)) - Link
  - [ ] Followup task will analyze metrics to ensure successful completion - Link

**Comment by Joelkw** [comment]
Next steps – mocking examples of user-scoped insights and what happens if you have the option to expand it.

**Comment by Joelkw** [comment]
Updates – we need to drive a decision on the frontend UI for a decision of "accept a single `repo:` filter first"

**Comment by leonore** [comment]
closing as new repo UI will be shipped in 4.5
