### ISSUE TITLE
insights: make decision if oob migration to save recording times interval for past insights is required

### ISSUE THREAD

**Issue by leonore** [sourcegraph/sourcegraph#42346]
depends on #42343, #42345

this issue also involves deciding whether we do want an oob migration. the purpose of such a migration would be to save recording times intervals for insights created in the past so they can also benefit from the 0-value fix

/cc @joelkw @felixfbecker @vovakulikov

**Comment by coury-clark** [comment]
need decision if this is required

**Comment by leonore** [comment]
the general consensus is that right now this is not required; when this is rolled out to customers, if customers run into this issue and want it fixed on existing insights, they can recreate it (e.g. using a slightly different query with parameters moved about, or by adding whitespace). 

if we decide to implement this, the work that would be required would be:
1. construct the recording times for the historical data according to BuildFrames (12 points only)
1. fetch unique recording times for series points (additional points)
1. add this data to insight_series_recording_times

there would still be very edge cases where if we don’t have series points data for a point in time, we’d still get no point there, in which cases we might want to use BuildFrames logic to add a point in between.

**Comment by leonore** [comment]
reopening as discussions ongoing

**Comment by leonore** [comment]
opened https://github.com/sourcegraph/sourcegraph/issues/43496 to actually write the migration, as it's been decided all insights should benefit from this. closing this decision issue
