### ISSUE TITLE
add sourcehut/sr.ht and gitea/codeberg support thankss

### ISSUE THREAD

**Issue by yuuyins** [sourcegraph/sourcegraph#42344]
#### Feature request description

support these

- https://sourcehut.org
- https://sr.ht

---

- https://gitea.io
- https://codeberg.org

#### Is your feature request related to a problem? If so, please describe.

proprietary's a problem
free, ideally community lead like gitea idea, but sourcehut also pretty good and popular
they will be the first to become federated as well

**Comment by jdorfman** [comment]
@yuuyins thanks! I added them to our list of hosts to add https://github.com/sourcegraph/community/issues/36
