### ISSUE TITLE
insights: save insight series recording times intervals on backfill and recording

### ISSUE THREAD

**Issue by leonore** [sourcegraph/sourcegraph#42343]
part of #39883

this issue should tackle adding a new table or new column to save the recording intervals for an insight_series on creation and update. 

when an insight is backfilled the 12 frames should initially be saved. then on each recording we should remove the oldest point and add the newest one

/cc @joelkw @felixfbecker @vovakulikov

**Comment by chwarwick** [comment]
> when an insight is backfilled the 12 frames should initially be saved. then on each recording we should remove the oldest point and add the newest one

@leonore  is this true, that we should only every have 12 data points plus 1 snapshot?

**Comment by leonore** [comment]
> @leonore is this true, that we should only every have 12 data points plus 1 snapshot?

no, we either have
1. 12 data points, if all data point times cover more than a year
2. 1 year of data, if all data points are within a year

https://github.com/sourcegraph/code-insights-scratch/blob/main/eclectic_knowledge.md#query-history-and-frames. 

the description was simplifying this, but does that make sense?

**Comment by chwarwick** [comment]
Ok so we are actually only querying for the last 12 points (or 1 year) but we aren't cleaning up expired data. Which is what I was thinking about and saw this issue.  Is removing point data that is no longer displayed in scope for this?

**Comment by leonore** [comment]
no, that should be a separate issue. I brought this up on [slack](https://sourcegraph.slack.com/archives/C02KE7E9GMR/p1664474095999549), it's in the [general improvements doc](https://docs.google.com/document/d/1n0XseRq5JXzB5CALK4Aw3jd7ryHl5KEjNcx9YHyE1SA/edit#heading=h.sjs3cejmrybm). we definitely should make an issue for this, just slipped my mind
