### ISSUE TITLE
management console bundle is 6mb and not being minified, takes 1-4s to load

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#4235]
https://sourcegraph.com/github.com/sourcegraph/sourcegraph@6ca56ce896094b13245a55ab9a9e91ffd9b11f1c/-/blob/cmd/management-console/web/package.json#L10-11

To fix, we would need to turn on minification (easy) and build a server image to confirm that source maps are being served properly so that if customers run into issues we can debug them.

**Comment by keegancsmith** [comment]
This seems like quite a quick win? Any reason why we have delayed doing it?
