### ISSUE TITLE
insights: Clean up k8s to enable reliable scale testing

### ISSUE THREAD

**Issue by CristinaBirkel** [sourcegraph/sourcegraph#42379]
It's hard to trust and test things on `k8s` because we have so many old/broken series, and possibly other kinds of old data that we don't need anymore. Find out:

- Is anyone relying on insights they've created on `k8s`? Or has everyone moved to `s2`? If we can narrow down any insights that are being used (and suggest they be re-created on `s2`, really,) we can feel free to clean things up and get this environment into more of a known state.
- Clean up `k8s` insights. We may even want to start more-or-less from scratch here. Let's definitely get buy-in from the team, but this environment could be useful to do preliminary scale testing on--particularly to figure out some of our current limitations.

/cc @joelkw @felixfbecker @vovakulikov

**Comment by Joelkw** [comment]
@CristinaBirkel are we supposed to use k8s or the new https://scaletesting.sgdev.org/ instead? 

If we do clean up k8s, let's save the insight series/configs to our scratchpad repo first just for reference (just the queries is fine, in case people want to reference them)

**Comment by leonore** [comment]
I believe we should modify insights that have a high sampling rate (daily, hourly, weekly), clean up their old data, pending a fix on 
- https://github.com/sourcegraph/sourcegraph/issues/42880

We can also check for invalid query errors in the query runner and disable the associated queries. We should then see if k8s is a bit more healthy.

k8s is generally unhealthy beyond our code insights. I think the scaletesting environment does enable reliable scaletesting, and just needs to be populated with a high scale of insights data, so my opinion is to use that if we find that it is easy to add data. It will make benchmarks we gather from the environment more reliable.

**Comment by leonore** [comment]
closing this issue as k8s is looking to be in a finer shaper since our recent fixes. we can revisit if needed
