### ISSUE TITLE
insights: Document how we can use the scale testing environment

### ISSUE THREAD

**Issue by CristinaBirkel** [sourcegraph/sourcegraph#42378]
Relating to this [scale testing effort](https://docs.google.com/document/d/1f9GcEpqJ5KA3YvfsOy48mdhILkvJZrqD9SfpZoNlQTg/edit#heading=h.egbxrewbg3nl), figure out how we can use this to test code insights at scale. Coordinate with people in the #wg-test-at-scale to figure out how this is all going to work and how we can use it.

The outcome of this ticket will be some documentation or a plan for how we can use that environment in particular, and/or work that will need to be done to enable it.

/cc @joelkw @felixfbecker @vovakulikov

**Comment by leonore** [comment]
From a preliminary look it looks like it's pretty well documented in the [handbook](https://handbook.sourcegraph.com/departments/engineering/dev/tools/scaletesting/#tldr-to-conduct-a-test) how to use the environment, but there's always gotchas. I've asked for an account on the instance and will report to see if anything is out of the ordinary.

my hope is to mark out a set of steps that'd be required to run a test at scale, I think the issue for us would be to populate the environment with data of scale comparable to what's on k8s.

**Comment by leonore** [comment]
confirm we can use scaletesting as we want. there's one admin account and it's in 1password

ideally we follow principles of

* documenting the steps we follow for our tests
* creating the data for the test and cleaning up after ourselves

this isn't what devx asked me to do, but what I think we should do

closing this as it was just exploratory
