### ISSUE TITLE
Remove unhelpful OpenGraph previews (Slack link unfurling)

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#4237]
When you paste a Sourcegraph link into Slack, it shows a generic OpenGraph link unfurl:

![image](https://user-images.githubusercontent.com/1976/58516606-66e90680-815d-11e9-8364-b957564b0219.png)

I think the ideal behavior is:

- If you link to the homepage (the `/` path on a Sourcegraph instance), it should show this generic description.
- The default for all other paths is NO OpenGraph preview, so pasting the URL into Slack/Twitter shows no unfurl.
- There still should be a search engine meta description, though, for all pages.
- In the future, we can add nice OpenGraph previews for certain pages, but this is not a priority because most customer instances do not currently show OpenGraph previews because Slack is not able to access their instance (due to it being protected). I.e., this is really only a problem for Sourcegraph.com now.

**Comment by slimsag** [comment]
👍 these are so annoying

**Comment by kzh** [comment]
Since "/" redirects to `https://about.sourcegraph.com` if the user is unauthenticated and on the public sourcegraph instance and to "/search" otherwise, should we leave the metadata on just the `/search` path?

**Comment by slimsag** [comment]
@kzh For Sourcegraph.com `/` redirects to about as you noted. For all other instances, it doesn't (e.g. try https://theoa.sgdev.org in incognito window).

The problem with leaving metadata on `/search` would be that all search links would show the metadata, which is the annoying thing this issue tries to solve.

I think that:

- `/` should serve metadata (for private instances that get linked to publicly, like if you paste http://theoa.sgdev.org in slack today)
- about.sourcegraph.com should serve metadata (for the case of linking to https://sourcegraph.com)
- `/search` should NOT serve metadata (note opengraph requests made by e.g. Slack will always be unauthenticated so the request will never redirect to /search, and even if it did we probably wouldn't want the metadata)

**Comment by kzh** [comment]
Ah right, the auth middleware. So for unauthenticated requests (ex. unfurling Slack/Twitter/etc), `/` redirects to:
- https://about.sourcegraph.com on the public instance (handles its own metadata)
- `/sign-in?returnTo=%2F` on a private instance (PR to place metadata here only)
