### ISSUE TITLE
Log the P4 command that was executed when reporting it failed

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#42388]
**Requested by:** https://github.com/sourcegraph/accounts/issues/583

#### Feature request description

During syncing of a Perforce depot, it failed with this message:

`"error cloning repo: repo perforce/path/to/depot not cloneable: exit status 1 (output follows)\n\nYou don't have permission for this operation."}}` 

The `this operation` is vague and doesn't help the user figure out what is wrong.   Ideally, we could list the command line that was executed (or the command like `ping`)

#### Is your feature request related to a problem? If so, please describe.

Trying to debug why the P4 sync wasn't working.  In order to track this down we used Sourcegraph to find [this function](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@4787b6a477d329eff7235328a3cd1245f3ff27f1/-/blob/cmd/gitserver/server/vcs_syncer_perforce.go?L34:30) which led us to `p4 ping` command.  It would be a lot better if this information were just in the log.

/cc @jplahn @ryphil

**Comment by jplahn** [comment]
Let's gooo. Nice work @sashaostrikov !
