### ISSUE TITLE
Release testing automation

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#4238]
- [x] Automate some subset of the tests in the [3.4.1 release testing grid](https://docs.google.com/spreadsheets/d/1y7JPkq_KucroiI1Eet2Cd53pt7F7Cx_2NStg8qqUvow/edit#gid=0)
- [ ] Provide clear examples and documentation for how to do this, with the aim that we distribute the automation tasks to the whole team in 3.5 release testing
- [ ] Ask @sourcegraph/distribution to write additional automation tests
- [ ] Ask 1 other person to write automation tests
- [ ] https://github.com/sourcegraph/sourcegraph/issues/4176
- [ ] Have this ready for 3.5 release testing
- [ ] Make this available to customers (as described in https://github.com/sourcegraph/sourcegraph/issues/3405)

Other
- [ ] Integrate Percy (for screenshot consistency from release to release).

**Comment by keegancsmith** [comment]
@beyang The 3.6 milestone will be closed very soon. Please add to another milestone / backlog.

**Comment by unknwon** [comment]
Should this issue be moved to 3.10 milestone?
