### ISSUE TITLE
Manually setup Sourcegraph with Perforce to identify pain points

### ISSUE THREAD

**Issue by jplahn** [sourcegraph/sourcegraph#42393]
A lot of the pain points we know of with our Perforce integration are raised by customers or CEs. As owners of Perforce integration, _we_ need to be the experts on where the experience is missing the bar. 

In this issue, we will setup Sourcegraph with Perforce multiple times at different scales to identify where the experience should be improved for our admins. 

More to come.

/cc @jplahn @ryphil

**Comment by mrnugget** [comment]
Closing because @peterguy did this many times.
