### ISSUE TITLE
Janky Monaco editor CSS/behavior

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#424]
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:** Chrome and Firefox

#### Steps to reproduce:

1. Visit https://sourcegraph.com/site-admin/global-settings (or any settings page)
2. Try selecting text

#### Expected behavior:

The selection behaves like a normal text box.

#### Actual behavior:

The selection is erratic and the cursor shows up in the wrong place:

![2018-10-16 13 26 46](https://user-images.githubusercontent.com/1387653/47045392-89d32700-d147-11e8-9fb1-38aac2827030.gif)

**Comment by chrismwendt** [comment]
@felixfbecker Do you know what's wrong, or who might know how to fix this?

This works fine on `2.12.0`, but is broken on `insiders` https://hub.docker.com/r/sourcegraph/server/tags/

**Comment by felixfbecker** [comment]
No, I don't know what could cause this, what change could be responsible, nor do I have any special context on Monaco or our use of it.

**Comment by sqs** [comment]
Prefer keeping this public issue open over the enterprise issue

**Comment by sqs** [comment]
I didn't realize this was also occurring in prod. For some reason I thought it was only happening on local dev. (I am pretty sure it's broken on 1 computer but works on another.)

I bumped this up to October 2018.

**Comment by sqs** [comment]
I believe I found the issue. The `enterprise/webpack.config.ts` file used the wrong `monacoEditorPaths` path (it should be `../node_modules/monaco-editor`, not just `node_modules/monaco-editor`).
