### ISSUE TITLE
Add warning when creating very large batch changes

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#42408]
##### Context

Batch Changes works at very large scales from a changeset creation standpoint (scale-testing in progress to confirm that), however the user experience for managing those large changesets will be degraded.

##### Proposal

Set expectations of users and recommend to split large batch changes. When I preview a batch change with more than `n` changesets.
- When running server-side, `n=2,000`:
	- When users run "preview workspaces" show a disclaimer in the UI
	- When running `src batch remote`,  show a disclaimer and ask for confirmation
- When running locally, `n=500`
	- When running src batch preview, show a warning
	- I'm thorn here if we should ask for confirmation (in that case, we also need to have a `-f ` [or `-yolo`] for users that run src-cli in a pipeline eg. CI), or just warn.

<img width="1703" alt="image" src="https://user-images.githubusercontent.com/25070988/193467809-a8fb95cf-a5e3-49b8-8fd4-79f1e035177d.png">

>This batch change is targeting 2,000 workspaces. It may be hard to manage using the current interface. We're working on improving that!
Meanwhile, we recommend breaking it down into several batch changes.

**Comment by chrispine** [comment]
P0?

**Comment by courier-new** [comment]
> When running locally, n=500
> - When running src batch preview, show a warning
> - I'm torn here if we should ask for confirmation (in that case, we also need to have a -f [or -yolo] for users that run src-cli in a pipeline eg. CI), or just warn.

I personally think it's okay if we just warn for local execution, especially when thinking about batch changes running in a CI pipeline.
