### ISSUE TITLE
the batch changes demo video is very outdated

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#42412]
I was clicking through the product feature pages on sourcegraph.com and I noticed the video on https://sourcegraph.com/batch-changes is very old. Sourcegraph looks and behaves completely differently now, as well as Batch Changes. We may want to consider content that is more time durable, or a new demo video on this page.

cc @malomarrec

**Comment by chrispine** [comment]
P0?

**Comment by courier-new** [comment]
I think we said Adeola's slightly longer version of the SSBC demo video that had a script would do well to replace this.
