### ISSUE TITLE
📕 Webhook-based Permissions Syncing

### ISSUE THREAD

**Issue by pjlast** [sourcegraph/sourcegraph#42413]
## Overview

Sourcegraph relies on constantly polling code hosts to sync permissions. This is an expensive process that grows in complexity as the number of users and repositories on an instance increase, and adds a hard limit to what we're able to keep in sync.

Some code hosts offer webhooks as a way to get notified from the code host when a change that we're interested in takes place. We can leverage this to be less dependent on polling code hosts for changes, and in doing so also have a more up-to-date system as a whole.

## Goals

Implement webhook-based permissions syncing for code hosts that support it to offer a system that's closer to the code hosts true permissions state at any given time.

## Relevant Docs/Discussions

- [Using webhooks to sync repository permissions](https://docs.google.com/document/d/1BkE-42jXJNOHDn0h3txwFpmfyBPaN189yLvYLj7v9pE/edit#)

## Definition of Success

/cc @sourcegraph/source

**Comment by mrnugget** [comment]
@pjlast didn't we implement some of this?

**Comment by pjlast** [comment]
@mrnugget yep! Closing. Any further improvements would not need an overall tracking issue like this.
