### ISSUE TITLE
Prometheus metrics for monitoring high-level error rates of internal requests

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#4241]
For "[Sourcegraph monitoring v0.5](https://github.com/sourcegraph/sourcegraph/issues/4260)"

Today we have hundreds of per-service prometheus metrics but surprisingly nothing that just says "are HTTP/RPC requests to service X generally successful or failing?"

Having this information in Prometheus would be super valuable to be able to determine overall system health.

Helps https://app.hubspot.com/contacts/2762526/company/407948923

**Comment by slimsag** [comment]
To get started working on this:

1. Identify which services use which methods to talk to other services (gitserver uses HTTP or RPC, I forget, frontend talks to services via HTTP, etc).
2. Add new Prometheus metrics around that indicating "are most of these requests failing or succeeding?"

**Comment by uwedeportivo** [comment]
what we have so far (with panels in various dashboards):

- histogram metric:  src_repoupdater_request_duration_seconds, gives us latency and error rate of all requests to repoupdater from all clients of it
- histogram metric: src_gitserver_request_duration_seconds_bucket, gives us latency and error rate of all requests to gitserver from all clients of it
- rate of deadline exceeded: src_gitserver_client_deadline_exceeded when gitserver makes requests to code hosts
- histograms (latency, error rate) for repo-updater to external services (github, gitlab and bitbucket)
- lsif upload requests, query requests
- searcher requests
- graphql requests
- overall http requests to frontend

**Comment by uwedeportivo** [comment]
we are missing request metrics for the various indexing services (zoekt, ctags)

**Comment by slimsag** [comment]
A good step forward towards this has been made in 3.11 and we're continuing to plan further / more concrete improvements in #7525 -- closing this conglomerate issue in favor of more specific ones linked there.
