### ISSUE TITLE
Perforce (future): drop path_includes and path_excludes columns

### ISSUE THREAD

**Issue by sashaostrikov** [sourcegraph/sourcegraph#42417]
Depends on several things:

- Merging of https://github.com/sourcegraph/sourcegraph/issues/41781
- Waiting for at least a release after https://github.com/sourcegraph/sourcegraph/issues/41781 was merged so that we are confident enough that all Perforce clients are on latest version and stable (i.e. doesn't want to downgrade)

/cc @sourcegraph/source/iam

**Comment by peterguy** [comment]
Time to do this @sashaostrikov?

**Comment by sashaostrikov** [comment]
![image](https://github.com/sourcegraph/sourcegraph/assets/94846361/a27711fc-4826-4074-8b88-b9e08db5b574)
https://github.com/sourcegraph/sourcegraph/pull/55195

@peterguy it's time!
