### ISSUE TITLE
Insights: Add license check for the create insight mutation 

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#42443]
## Background 

At the moment, we do have a license check on the frontend in [uiFeatures hook](https://sourcegraph.com/-/editor?remote_url=git%40github.com%3Asourcegraph%2Fsourcegraph.git&branch=vk%2Ffix-bar-chart-focus&file=client%2Fweb%2Fsrc%2Fenterprise%2Finsights%2Fhooks%2Fuse-ui-features.ts&start_row=90&start_col=18&end_row=90&end_col=18&editor=JetBrains&version=v2.0.1) This async method introduces a lot of complexity and possible bugs in the creation UI pages.

Instead of FE check we should add one check in the create insight mutation and throw an error if already created insights count is bigger than N (on the FE we defined N = 2)

/cc @joelkw @felixfbecker @vovakulikov

**Comment by coury-clark** [comment]
p2

**Comment by coury-clark** [comment]
@vovakulikov from sync discussion it seems we proactively show this in UI so that the user knows about the cap before they hit create - thoughts??

**Comment by felixfbecker** [comment]
Wait, so if we do a check when the user goes to the page, why would we need another check on clicking Create? Why do we even allow the user to click Create if we already know it won't work?

**Comment by vovakulikov** [comment]
@felixfbecker 
> Why do we even allow the user to click Create if we already know it won't work?

We don't know. Because create button availability depends not only on license state but also on how many insights users already have. If this number is bigger than N (currently N = 2) we blocked creation functionality. 

At the moment all these checks live on the frontend and it seems like overkill to me. I suggest we throw an error on the backend if we run create insight mutation and we already have N insights.

**Comment by felixfbecker** [comment]
@vovakulikov what did you mean with this then? What is the information that is being shown proactively?

> we indeed proactively show information about limited mode

**Comment by vovakulikov** [comment]
@felixfbecker I meant that at the moment in the creation UI we do add a few UI parts that tell users that they are in the limited access mode 

<img width="570" alt="Screenshot 2022-10-18 at 15 40 20" src="https://user-images.githubusercontent.com/18492575/196516721-df004e9c-d9e2-421b-9847-2a67ef0cac72.png">

- We show limited access label next to the create button "Unlock Code Insights to create unlimited insights"
- And we disable create button if the user is in the limited access mode and has more insights that limited access mode implies (N > 2) 

I want to remove the second check (disabling create insight button) from the frontend and move this check to the backend. If user clicks create insight button and they have more than N insights already backend throws a specific error about it and we show it with `ErrorAlert` in the creation UI 

The reason for this is having this creation availability check adds complexity on the frontend (we have to make an additional API request to fetch number of insights and disable or enable the create insight button) 

We did it on the frontend because we didn't have enough time on the backend when we were developing limited access mode but I still think that we should have limited access mode gate/checks in the API on the backend instead of having them in the web app.

**Comment by felixfbecker** [comment]
That makes sense to me. Kind of weird to have the check _only_ on the client anyway, if that means you can still create insights with the API. Feels like there should be a check in the backend mutation regardless that returns a simple error otherwise.

**Comment by chwarwick** [comment]
This license check already exists https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/insights/resolvers/insight_view_resolvers.go?L1519:6-1519:31#tab=references

**Comment by chwarwick** [comment]
Closing as license check on mutation already exists.
