### ISSUE TITLE
Saving Sort & Limit filters does not work

### ISSUE THREAD

**Issue by unclejustin** [sourcegraph/sourcegraph#42459]
As seen in [this line](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@74ef319533f48e310fa8dae377bc81bbb8af8660/-/blob/client/web/src/enterprise/insights/core/backend/gql-backend/methods/create-insight/serializators.ts?L93), `insight.appliedSeriesDisplayOptions` should have the update filter values but it does not.

Suspect updated form inputs are not updating state.

In the screenshot below, the "number of data series" has been updated from 20 to 5. Clicking "Save as new view" and saving, will create a new insight without the updated limit.

Note: This problem affects all values in the "Sort & Limit" pane.

![PixelSnap 2022-10-03 at 16 37 36](https://user-images.githubusercontent.com/1855233/193689745-f4ff938b-92a8-4546-b4c4-f22559ce0320.png)

/cc @joelkw @felixfbecker @vovakulikov

**Comment by chwarwick** [comment]
@leonore  I know you were just working on some other unrelated issues with save & new do you know if this issue still exists?

**Comment by leonore** [comment]
yes it still doesn't work. the values on sort and filter aren't saved on the frontend, the query is always sent with defaults to the backend. once this is fixed on the frontend it should all work on the backend, even with save as new view etc.

**Comment by leonore** [comment]
will be closed by #46653
