### ISSUE TITLE
insights: Add a repo scoping filter to the API and insight_series table

### ISSUE THREAD

**Issue by CristinaBirkel** [sourcegraph/sourcegraph#42455]
Not 100% we'll need this, (see [this comment](https://docs.google.com/document/d/1vWxSDSbslZQFEK24rhlo8-K2sCiaaCX5PQoCqEdpI_8/edit?disco=AAAAgOVjncA),) but I would say probably.

One way we can do this is to modify the [`RepositoryScopeInput`](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/insights.go?L414) to have an additional nullable field for `Context` or `Filter` or whatever it ends up being. And then persist it in the `insight_series` table. If we do it this way, we need to ensure that both `Repositories` and the new field are not filled in at the same time.

/cc @joelkw @felixfbecker @vovakulikov

**Comment by chwarwick** [comment]
closed by https://github.com/sourcegraph/sourcegraph/pull/45740
