### ISSUE TITLE
insights: series based backfiller - create a task that gets the specific repos to iterate over for the series

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#42462]
The backfilling process needs to be split into 2 parts.  The first part analyzes the series to estimate the amount of work needed to be done but does not actually do any work.

The first version of this should be to take the series and get a list of repos that it will need to run over.  This data will then be persisted so the scheduler/runner can make an informed decision about which series to work on first.

/cc @joelkw @felixfbecker @vovakulikov

**Comment by coury-clark** [comment]
Closing in favor of https://github.com/sourcegraph/sourcegraph/issues/42890
