### ISSUE TITLE
insights: Backfill based on repos returned from a search

### ISSUE THREAD

**Issue by CristinaBirkel** [sourcegraph/sourcegraph#42479]
This is somewhat dependent on design decisions about what the user will be passing in. But we will need a way to resolve a filter into a list of repos that we can pass to the backfilling process.

Some options:
- Use a `select:repo` option and run a sourcegraph query. Will this be against the current index, different points in time, something else?
- Possibly some direct call against the database, if we want the current list of repos. Is it faster or easier to code?

This issue is the work of writing whatever function we need to take a filter and return a list of repos.

Updated- Nov 11 2022

Logic exists to get the list of repos from a search query.  This issue should depend on that logic and update the v2 backfiller to support populating the repo list from a search defined on the series..

**Comment by chwarwick** [comment]
p0

**Comment by chwarwick** [comment]
depends on https://github.com/sourcegraph/sourcegraph/issues/42455
