### ISSUE TITLE
Use V3 search in batch changes

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#42495]
Make sure that we use V3 search, so that the search behavior is the same between the search bar and the spec input.

**Comment by chrispine** [comment]
P0 or P1?

**Comment by courier-new** [comment]
What does updating to V3 entail beyond updating the src-cli search queries to set `version: V3` and sending it as a parameter wherever the workspace resolver calls the search API?

**Comment by eseliger** [comment]
I hope that's it, honestly 😬 2 constants, a bit of testing and see if everything still works as expected
