### ISSUE TITLE
Don't show "Create batch change" button in search for unsupported query types

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#42496]
Batch changes can only handle a subset of all queries as input, diff and commit searches for example don't work. For those, we should not suggest to create a batch change from the results page.

**Comment by chrispine** [comment]
P0 or P1?

**Comment by courier-new** [comment]
How about... done? 😉

**Comment by chrispine** [comment]
Now you're just showing off 😆
