### ISSUE TITLE
Re-create bitbucket.sgdev.org

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#4253]
Create a [Bitbucket](https://docs.gitlab.com/omnibus/docker/) instance on the [tooling cluster](https://github.com/sourcegraph/infrastructure/tree/master/kubernetes/tooling) for @sourcegraph/core-services to use with their load-testing. 

The credentials for the current bitbucket.sgdev.org are missing.

**Comment by sqs** [comment]
Any updates here? I would like to test something on our Bitbucket instance.

**Comment by tsenart** [comment]
In the meantime, you can use the official Docker image locally. That’s what I used to work on the recent ACLs feature.

**Comment by ggilmore** [comment]
bitbucket.sgdev.org is online again.
