### ISSUE TITLE
Replace ctags with tree-sitter to improve symbol quality/robustness

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#42537]
[ctags](https://github.com/universal-ctags/ctags) vs [tree-sitter](https://tree-sitter.github.io/tree-sitter):

- tree-sitter grammars/queries are a lot easier to read/write/debug than ctags parsers
- ctags has built-in symbol extraction support, so we'll need to replicate that behavior with tree-sitter
- ctags is not pure (caused a [bug in Rockskip](https://github.com/sourcegraph/sourcegraph/pull/36612))
- They're about the same [speed](https://github.com/chrismwendt/ctags-vs-tree-sitter)

Steps to migrate:

- Add a `switch` statement that picks either the old ctags implementation or the new tree-sitter one (noop for now) depending on the language (so we don't have to migrate all at once)
- Implement symbol extraction using tree-sitter queries or ad-hoc tree traversal for each language
- Eventually drop ctags and the `switch` statement

Prior art:

- https://github.com/sourcegraph/sourcegraph/pull/36601

**Comment by malomarrec** [comment]
Hey @chrismwendt, this issue didn't have a team label. Given you created it, I assigned you and added your team label. Feel free to unassign yourself. If this is not the right label, can you make sure to add the right one?
