### ISSUE TITLE
sg: setup command wasn't able to detect asdf $PATH

### ISSUE THREAD

**Issue by mucles** [sourcegraph/sourcegraph#42540]
![image](https://user-images.githubusercontent.com/78464298/193940375-638284c5-f7c3-4939-8b75-4e1f192b599b.png)

context: https://sourcegraph.slack.com/archives/C01N83PS4TU/p1664311495029479

**Comment by abitrolly** [comment]
I've got the same problem while trying to setup Gitpod in #43684

**Comment by abitrolly** [comment]
@jhchabran so how it was fixed?
