### ISSUE TITLE
faster deploys to sourcegraph.com and k8s.sgdev.org

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#4254]
Right now, deploys to sourcegraph.com and k8s.sgdev.org can take ~90 minutes since Renovate is an asynchronous tool. This can make it hard to correlate failures with recent deploys. 

Some possible solutions:

1. Use renovate-pro with webhooks
1. Bring back deploy-bot (basically re-implement what Renovate does)

**Comment by nicksnyder** [comment]
This seems to have gotten worse recently: https://github.com/sourcegraph/sourcegraph/issues/7576

And we have continued to hear complaints from the team about the latency here: https://sourcegraph.slack.com/archives/C07KZF47K/p1578413971004000

Can we prioritize this as one of the dev productivity tasks this quarter?

**Comment by nicksnyder** [comment]
> 1. Use renovate-pro with webhooks
> 1. Bring back deploy-bot (basically re-implement what Renovate does)

I think we should consider a third option of triggering deployments synchronously in the master build on sourcegraph/sourcegraph. In CI we would push a commit directly to the release branch of deploy-sourcegraph-dot-com and then the deploy would happen as it does today. No renovate or bot needed.
