### ISSUE TITLE
Unable to sync repos on dev instance

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#4255]
https://sourcegraph.slack.com/archives/C07KZF47K/p1559156522085200

**Comment by mrnugget** [comment]
I've added a valid token to our credentials repo and 1Password account. Let me know if that solves the issue.

**Comment by mrnugget** [comment]
Turns out that the `http://` for our GHE instance should've been an `https://`. Pushed that too.

**Comment by mrnugget** [comment]
I'm quoting myself here from the mentioned Slack conversation:

> In summary: the GHE configuration in `dev-private` was invalid, which is why `repo-updater` was failing to sync the repos from GHE. Deleting/changing the GHE external service through site-admin and _then_ restarting Sourcegraph was useless, because when running in enterprise mode, everything in `dev-private` overwrites the content in the DB when restarting
