### ISSUE TITLE
Tracking Issue: First class webhooks

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#42569]
Manual tracking issue for first class webhooks, Milestone 1 in [this doc](https://docs.google.com/document/d/1cldGAS0fz3wqa_9Ny1zv6SHCsIrB5EsljRWPFXXoRAg/edit#).

## Milestone 1

https://github.com/sourcegraph/sourcegraph/issues/42569#tasklist-block-01184002-6968-4c04-8e63-fd57429eb0e2

## Milestone 2

https://github.com/sourcegraph/sourcegraph/issues/42569#tasklist-block-006ace5f-7d26-4bab-805c-6a179a65f5b9

## Milestone 3

https://github.com/sourcegraph/sourcegraph/issues/42569#tasklist-block-7ae036ac-539e-4f79-9413-ee20f132e580

## Milestone 4

https://github.com/sourcegraph/sourcegraph/issues/42569#tasklist-block-226cf7f8-1aba-499c-aaa5-aba5d2009a0e

## Milestone 5

https://github.com/sourcegraph/sourcegraph/issues/42569#tasklist-block-b3c250f2-d382-4b78-a047-6c38f5f3c073

## Bugs and Improvements

https://github.com/sourcegraph/sourcegraph/issues/42569#tasklist-block-5934f2f2-db38-4d2e-ac1c-894084d7ba80

**Comment by sashaostrikov** [comment]
Large part of Milestone 1 is complete!
Database layer development is finished and GraphQL functionality is already in progress.

As soon as all GraphQL resolvers are implemented and HTTP handler is in place -- Milestone 1 will be achieved 🎉

**Comment by ryanslade** [comment]
Thanks to the great work of @sashaostrikov @pjlast and @mollylogue Milestone 1 is almost complete.

There was a little but of extra work needed to ensure that the new top level hook works well with our existing code but we've made good progress on that and have [a PR](https://github.com/sourcegraph/sourcegraph/pull/43224) to integrate existing hooks.

While we're finishing off the last few bits of Milestone 1, @sashaostrikov and @pjlast will start work on the UI next week. @mollylogue will most likely start on integrating the `webhook_logs` table.

**Comment by ryanslade** [comment]
We're still making steading progress.

Work has started on the UI with some expected ramp up time. 

@pjlast has made good progress on migrating our old handlers, GitHub is done and GitLab is up for final code review. 

@mollylogue Integrated the our new handlers into the `webhook_logs` table and also confirmed that we can already handle `push` events and we just need a little bit of refactoring done after we've migrated all to handle old GitLab and Bitbucket payloads.

One extra piece of work is that we have decided to make webhook handling enterprise only, so we'll need to move some code around and only register the new handlers in enterprise mode.

**Comment by ryanslade** [comment]
@alexAtSourcegraph has been making good progress on the UI, see his [latest PR](https://github.com/sourcegraph/sourcegraph/pull/44372) for a demo video.

Only one remaining task left for Milestone 1 which is to ensure that we can handle existing bitbucket events with out new handlers. @mollylogue is making good progress on this.

I am cautiously optimistic that we should have Milestones 1-3 complete for the `4.3.0` release.

**Comment by sashaostrikov** [comment]
This project has been finished.
