### ISSUE TITLE
Create CRUD store for `webhooks` table

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#42573]
Once https://github.com/sourcegraph/sourcegraph/issues/42572 is complete create a new store in the `database` package.

`WebhooksStore`:

* Create
* Delete
* Update
* List (with filter by kind and pagination)

We can start with an empty implementation and split work after that.
We need tests for each method.

### Work tracking

- [x] #42621
- [x] #42686
- [x] #42642
- [x] #42671
- [x] #42739
- [x] #42741
- [x] #42740
- [x] #42798

**Comment by jplahn** [comment]
💪

**Comment by sashaostrikov** [comment]
As last PR from this issue [got merged](https://github.com/sourcegraph/sourcegraph/pull/42775), we can close it! 🎉
