### ISSUE TITLE
improve documentation on using our cache

### ISSUE THREAD

**Issue by leonore** [sourcegraph/sourcegraph#42578]
our docs don't say much [about using our cache](https://docs.sourcegraph.com/search?q=cache&v=), beyond what it's been initially used for. after initial investigation for insights caching and aligning with devex/other teams on expected usage it would be nice to update the docs.

**Comment by coury-clark** [comment]
is this saying you already have things you want to add to docs, or just want to go find out first? If the former I'm happy to vote p0
