### ISSUE TITLE
Single File Diff View: Show list of commits relevant to only the selected file

### ISSUE THREAD

**Issue by lrhacker** [sourcegraph/sourcegraph#42571]
Currently, we only show the list of commits between revisions when [looking at the full set of files changed](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/compare/...main-dry-run/mv/debug-integration-test). When [comparing just a single file](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/compare/...main-dry-run/mv/debug-integration-test?filePath=enterprise%2Fcmd%2Ffrontend%2Finternal%2Fauthz%2Fresolvers%2Fresolver.go&visible=1), we hide the list, as we do not currently support querying for the commits relevant to just that single file (and showing a potentially long list of irrelevant commits could be confusing).

This will need some backend support to update [the query](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/repo/compare/RepositoryCompareCommitsPage.tsx?L28-43) to allow for an optional set of file paths. If any paths are specified, the list of commits returned would be only those relevant to those files (i.e. commits where the files were actually modified).

**Comment by lrhacker** [comment]
@sourcegraph/search-product Is the backend work for this something your team could help support? It is only a medium priority for us at the moment, so does not need to be done immediately. If it's something you can help with, when would be a reasonable timeframe?

Also, I'm happy for any feedback on this feature as a concept and what would be necessary to support it (maybe there's some significant hurdle that would block it). Thanks!

**Comment by camdencheek** [comment]
@lrhacker Just took a peek, and it was a pretty easy change. PR [here](https://github.com/sourcegraph/sourcegraph/pull/42597)
