### ISSUE TITLE
In-Product Analytics Users Count Issues

### ISSUE THREAD

**Issue by thenamankumar** [sourcegraph/sourcegraph#42598]
DOC: [User counts issues](https://docs.google.com/document/d/1goz-DzMdLgyp2D-Q-Seb-fI8JZU9vaLKXEsKo2VPYuY/edit?usp=sharing)

For Users Activity Analtyics page under `/site-admin/analytics/users`
- [ ] Add percentage, total numbers toggle for frequency of day use
- [ ] Move BuildFrequencyDatums to backend
- [ ] Track only registered users for MAUs & frequency of day use. (currently based on anonymous id)
- [ ] Change "Average DAU/WAU/MAU for the date range" chart to show MAUs for last 3 months. @rrhyne should we take 3 months before current month?
- [ ] [Exclude event types](https://sourcegraph.slack.com/archives/C03JNPY7V3L/p1660795181951239)

**Comment by rrhyne** [comment]
> Add percentage, total numbers toggle for frequency of day use

Can you explain this? 

> Change "Average DAU/WAU/MAU for the date range" chart to show MAUs for last 3 months. @rrhyne should we take 3 months before current month?

Please include the current month so users can see how they are trending.  One question, are we likely to see half of the 3rd month of data due to how we delete event log data or do we delete event logs for entire months at a time?  If users might see partial data for the month, please do not show that month, only show the months that have complete data or the current month.

**Comment by thenamankumar** [comment]
> > Add percentage, total numbers toggle for frequency of day use
> 
> Can you explain this?
> 
> > Change "Average DAU/WAU/MAU for the date range" chart to show MAUs for last 3 months. @rrhyne should we take 3 months before current month?
> 
> Please include the current month so users can see how they are trending. One question, are we likely to see half of the 3rd month of data due to how we delete event log data or do we delete event logs for entire months at a time? If users might see partial data for the month, please do not show that month, only show the months that have complete data or the current month.

1. For the frequency day use chart we plan to add a toggle between raw nos of users vs percentage of active users. LIke 100% for 1 day, 70% for 2 days, 40% for 3 days active. 
2. Yes we store only the last 93 days of data. So we will always cover the last 2 complete months + 1 ongoing current month data. We will skip the partial part of minus 3 months.
