### ISSUE TITLE
Get Prometheus/Grafana in sourcegraph/server by setting MONITORING=true

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#4259]
Historically we haven't included monitoring in sourcegraph/server because it would either be too resource intensive or because it would be technically complex (like embedding Jaeger in our container).

We could at least allow getting Prometheus/Grafana in server deployments when `MONITORING=true` and perhaps make that the default if Prometheus doesn't use too many resources?

**Comment by uwedeportivo** [comment]
prometheus: https://github.com/sourcegraph/sourcegraph/pull/5131
grafana: https://github.com/sourcegraph/sourcegraph/pull/5141

i unilaterally decided to not make it optional given that we want to expose the dashboards in the UI in an iframe. if we decide differently we can open this issue again or open another issue.

i still plan to clean up the configs and make them more shareable between the different deploy contexts.
