### ISSUE TITLE
Sourcegraph monitoring (high level / overview)

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#4260]
It occurs to me that I could better communicate my high level vision for improved monitoring of Sourcegraph by site admins (and us on Sourcegraph.com). This is my attempt at doing so 😃 

My hope is to give visibility to @sourcegraph/core-services (since we chatted this morning about e.g. relevance of including search perf metrics), @christinaforney as it relates to customers more broadly and everyone else who is interested.

### Monitoring tools today

**If you understand what monitoring tooling / setup looks like today, skip this section**

Today we use a multitude of monitoring/debugging tools in various different ways and deployments:

- **Tracing**: Provided by Lightstep and Jaeger
    - Example: A specific request of yours is slow or broken, tracing lets you see what happened behind the scenes with that specific request.
- **Metrics**: Provided by Prometheus
    - Example: "Over the last two months, what was the 95th percentile request latency?" -> Prometheus answers this
- **Dashboards**: Provided by Grafana
    - Example: You want to make a good overview of the data in Prometheus
- **Analytics/tracking**: Provided by HubSpot
    - Example: How many users complete our activation user flow on Sourcegraph.com?
- **Logging**: Either no log consumer or Google Stackdriver / whatever the cloud host provides.
- **In-app metrics**: These are only used for communicating usage stats, user surveys, etc.

The story for most deployments is not a good one:

| Tool | Sourcegraph.com | Kubernetes cluster | Docker container | deploy-sourcegraph-docker |
|---|---|---|---|---|
| Tracing | ✅ (inconsistent) | Optional (undocumented, broken) | ❌ | ✅ |
| Metrics | ✅(incomplete) | Optional | ❌ | ✅(incomplete) |
| Dashboards | ❌(broken) | ❌ | ❌| ✅|
| Analytics/tracking | Optional | Optional | Optional | Optional |
| Logging | Google StackDriver | Up to cloud host | Up to cloud host | Up to cloud host |
| In-app metrics | ✅| ✅| ✅| ✅|

- It was [just recently](https://github.com/sourcegraph/sourcegraph/issues/3175) that deploy-sourcegraph-docker had a good story and we agreed to standardize on some tooling like a single tool for tracing instead of varying ones.
- [Work](https://github.com/sourcegraph/sourcegraph/issues/3410) needs to be done to take the deploy-sourcegraph-docker niceness and transfer it to our Kubernetes cluster deployments (most of our customers).
    - This would apply to Sourcegraph.com inherently.
- For `Docker container`, it is unclear how much we can/want to do, but given a substantial portion of our customers run this we likely want to do something, so: https://github.com/sourcegraph/sourcegraph/issues/4259

### Monitoring issues today

1. Customers want to know when Sourcegraph is having issues.
2. When Sourcegraph is having issues, they want to potentially be alerted about them so that someone can look into it or alert us.
3. When Sourcegraph is having issues, they want to be able to narrow down the problem and have a good understanding of how bad the problem is (is everything broken? just some parts? is it just running a little slow? etc)

#### Main dashboard

This main dashboard would show you:

- Sourcegraph is green -> everything's good.
- Sourcegraph is yellow -> something may be up, things may be a little slower than usual -- but it might solve itself and there is no need to actively investigate
- Sourcegraph is red -> something is broken. You should rollback, contact support, etc.

#### Narrowing

Narrowing down the above, you can see the health of each major service we have:

- frontend
- searcher
- gitserver
- repo-updater
- query-runner
- etc.

Maybe something like 0% to 100% healthy as a graph.

Accompanying documentation would describe the importance of each of those and that e.g. query-runner having issues means saved searches may not work but other things are OK for example.

- in 3.5, this health will be computed based on some service-specific metrics but mostly just based on whether or not most requests to the service are failing or not. This will give us good high-level data but not service/team-specific data.
- Any service above can define new Prometheus metrics (of course) that play into this health metric. The expectation is that long term these are based on very service (and team) specific metrics:
    - repo-updater health goes down if we're having trouble updating or cloning repos, hitting code host API limits.
    - searcher health goes down if searches are super slow for some reason.
    - gitserver health goes down if we're running out of disk space, or it can't connect to the codehost.
    - searcher team adds some caching somewhere, to monitor it we add search-specific metrics and they contribute to the overall health that searcher has etc.

The point of this is that we can get (and continue to be) really specific with our metrics, and still keep them at a high-level capable of being alerted on and legible to site admins who don't know what a specific metric is, e.g., I can understand searcher is operating at 50% health, but I as a site admin can't understand what "15 failures of searcher zip archive cache fetch requests per minute" means -- obviously it's bad, but how bad? (we get to define that! 😃)

The only thing we have to be cautious of is defining these such that they are not noisy, after all we're talking about e.g. customers being alerted "Sourcegraph is broken!" so when we say that we want to be positive in some way (and this makes it super important for us to use these same metrics on our deployments for alerting).

#### Even more specific

So you're a site admin, Sourcegraph is yellow or red, it says searcher's health is 50% but why?

This is where the service-specific dashboards come in. Each service/team should display the most important things there (we're pretty close to that already, we just have a few missing metrics and dashboards). These are what customers would e.g. send us a screenshot of when something is going wrong.

407948923

**Comment by beyang** [comment]
A few side notes here:
* Logging: at least one customer has hooked up logging to ELK
* Sentry: at least one customer uses Sentry (and we have it hooked up on sourcegraph.com, though we're not getting as much value out of it as we could I think). It's kind of a hybrid between high-level error tracking/monitoring and a drill-down tool that lets you see individual error requests.
* I'd put ops tools into 2 high-level buckets: (1) aggregate/alerting and (2) drill-down tools:
  * Aggregate/alerting
    * Alerting (OpsGenie, PagerDuty, Alertmanager) 
    * Metrics (Prometheus)
    * Dashboard (Grafana)
    * Uptime monitoring
  * Drill-down
    * Logs
    * Sentry (kind of a hybrid, though)
    * Tracing (Jaeger, Lightstep)
    * In-app metrics, which you probably only access when debugging a prod issue
    * Sourcegraph (to pinpoint location in source you need to change in response to an incident)

**Comment by slimsag** [comment]
The v0 of this should look like:

- One _Prometheus metric per service indicating the health of the service_. For now, just computed based on a per-service metric of whether or not most requests to that service are failing or succeeding (this does not exist in our app yet and will need to be added, see below).
    - We should be able to divide this into "green" (healthy), "yellow" (something *could* be wrong, but it may auto-resolve itself and no need to actively investigate or page someone), "red" (something is definitely wrong, page someone and you should rollback, contact support, investigate, etc).
- An aggregate prometheus metric, based on the per-service ones in the above step, indicating whether or not Sourcegraph overall is in a green/yellow/red status.

The v1 of this would be:

- Take these changes from deploy-sourcegraph-docker, which benefit https://app.hubspot.com/contacts/2762526/company/407948923 -- and apply them to https://github.com/sourcegraph/deploy-sourcegraph (applies to all cluster customers) and https://github.com/sourcegraph/deploy-sourcegraph-dot-com and alter our own OpsGenie-based alerting to begin alerting on these metrics.

How to get started working on the v0:

1. Familiarize yourself with deploying https://github.com/sourcegraph/deploy-sourcegraph-docker on your local machine. This is an easy way to get a Sourcegraph cluster up locally _with Prometheus_.
    - Note: If your dev laptop has less than the # of cores required in that project, `deploy.sh` will give you a Docker error about it. You can just temporarily change the `--cpu` flag to a lower number since the CPU flags do not really matter on a dev laptop instance.
2. Familiarize yourself with this file: https://github.com/sourcegraph/deploy-sourcegraph-docker/blob/master/deploy-prometheus.sh and the standard Prometheus rules we declare here for deployments: https://github.com/sourcegraph/deploy-sourcegraph-docker/tree/master/prometheus
3. In the rules files, come up with a way to declare for each service a "health" metric that we can monitor and alert on. SLOs as defined in this blog post that @tsenart shared sounds like it may be a good way to go so it is worth investigating: https://sourcegraph.slack.com/archives/CJX299FGE/p1560594933039100
    - A very important fact here is that we are NOT noisy/flaky with these metrics. A target should be that customers can alert on these metrics easily and have high confidence we're not waking them up in the middle of the night for something that is a non-issue. i.e. initially I'd rather have less metrics considered but be more certain about what they mean. That is why in the original post above I mentioned the first step being this:

> in 3.5, this health will be computed based on some service-specific metrics but mostly just based on whether or not most requests to the service are failing or not. This will give us good high-level data but not service/team-specific data.

When you ask "what is the metric for whether or not requests to X service are failing or not?" the answer is we don't have that yet :) We will want to spin up a goroutine in each of our services that pings each service it talks to, i.e. the ones in the cmd dir here https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/tree/cmd

- To find examples of how you would register this in Prometheus see https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+prometheus.MustRegister and also look at Prometheus documentation online.
- To look at how you would spin up this goroutine in each service, you could do so in `tracer.Init` I believe: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/pkg/tracer/tracer.go#L98:6
- To figure out how the pinging would work, look to the existing health check endpoints in services: https://github.com/sourcegraph/deploy-sourcegraph/blob/ff7b6f31ef21da1ad578e7cddc1ca83364ef10a4/base/searcher/searcher.Deployment.yaml#L46-L49
- To figure out how the services would hit the health checks, look to this function which does something similar: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@70fb03d24127cad384f3900f5ec00f3a070475f0/-/blob/pkg/api/internal_client.go#L31

**Comment by uwedeportivo** [comment]
i started working on this. so far everything seems clear and straightforward to execute. i'm not sure i see the need for an additional ping endpoint for a service. we should just instrument the actual http or rpc traffic between a client and a service (for example frontend <-> gitserver) and deduce from that whether the service is healthy, reachable, in trouble...

the only advantage i see with an extra periodic ping is that even with no "normal" traffic we know that the service is up. the downside is that it overlaps with what kubernetes/docker/mesos already does. it also could be that the pings succeed and the normal endpoint fails. additionally we still want to instrument the normal traffic anyways (from both client and server POV) to measure latency and error rate of them. i don't mind doing the pings but as a first approximation i think we can just watch the normal traffic.

**Comment by slimsag** [comment]
Sounds good, great thoughts! I agree as a first approximation watching normal traffic is great.

**Comment by uwedeportivo** [comment]
Some breadcrumbs so I don't forget:

- this starts (among other things) the prometheus end points: sourcegraph/pkg/debugserver/debug.go
- sourcegraph/dev/src-prof-services.json has the port mappings for each service (in dev env, env var SRC_PROF_SERVICES points to it)

**Comment by uwedeportivo** [comment]
More notes: https://github.com/danielfm/prometheus-for-developers#measuring-request-durations

**Comment by efritz** [comment]
I'd like to throw in some additional thoughts here: https://www.weave.works/blog/the-red-method-key-metrics-for-microservices-architecture/ and, as an implementation, https://github.com/efritz/go-instrument and https://github.com/efritz/imperial/blob/ff1b721e1e7429cdb8c6df921ca5e04c518a93bf/prometheus/reporter.go#L15. 

This gets you 90% of the way for things you need to instrument, at least for request-based and service-to-service communication and this technique has served me well in the past.

**Comment by uwedeportivo** [comment]
@efritz thanks. will check it out. we already do many metrics so i'll try to follow the same conventions, but i'll definitely play with go-instrument, it looks cool.

**Comment by uwedeportivo** [comment]
a lot of the metrics code is already present (thanks :-) ). sourcegraph/pkg/metrics has middleware ready to be hooked up and it's used in a couple of places. it counts requests and breaks it down by http status code and has an extra one for errors in the counter vector. i only need to add latency metrics to this and then hook it up to all the other places it can be used to measure requests. so 👍 to what's there

**Comment by uwedeportivo** [comment]
- https://github.com/sourcegraph/sourcegraph/pull/4963
- https://github.com/sourcegraph/sourcegraph/pull/5093
- https://github.com/sourcegraph/sourcegraph/pull/5131

**Comment by uwedeportivo** [comment]
https://github.com/sourcegraph/sourcegraph/issues/5188

**Comment by uwedeportivo** [comment]
Found https://github.com/sourcegraph/infrastructure/blob/master/sh/prom-metric-docs/main.go
to generate documentation of all our metrics.

**Comment by slimsag** [comment]
This has been implemented in 3.11: 

Further work and concrete items are being planned in https://github.com/sourcegraph/sourcegraph/issues/7240 and all known monitoring issues/improvements can be found at https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aopen+is%3Aissue+label%3Amonitoring
