### ISSUE TITLE
Invalidate execution cache entries if secret value changes

### ISSUE THREAD

**Issue by courier-new** [sourcegraph/sourcegraph#42611]
Follow up to https://github.com/sourcegraph/sourcegraph/issues/27926.

When a secret value that is referenced by a batch spec changes, we should automatically invalidate the cache for that batch spec execution.

This is effectively blocked by https://github.com/sourcegraph/sourcegraph/issues/41831 as it's very hard to do with the current parser.

**Comment by eseliger** [comment]
This will be supported by secrets V1!
