### ISSUE TITLE
docs: Clarify that changing a value in `steps.env` does not invalidate the cache

### ISSUE THREAD

**Issue by courier-new** [sourcegraph/sourcegraph#42612]
We recently discussed that changing an environment variable does not invalidate the batch spec execution cache, but the team agreed that it probably ought to (https://github.com/sourcegraph/sourcegraph/issues/42611). We should clarify in our docs that when changing the value of an env variable, the user will need to run without cache if they had previously executed the batch spec with a different value.

**Comment by eseliger** [comment]
P1/P0 depending on other load I'd say, given it never came up yet as feedback or confusion. But good to be proactive rather than reactive :)

**Comment by courier-new** [comment]
Am I misunderstanding this or do we actually invalidate the cache when an env var changes. 👀 We [use](https://sourcegraph.com/-/editor?remote_url=https%3A%2F%2Fgithub.com%2Fsourcegraph%2Fsourcegraph.git&branch=main&file=lib%2Fbatches%2Fexecution%2Fcache%2Fcache.go&editor=VSCode&version=2.2.12&start_row=117&start_col=1&end_row=117&end_col=1) both the local `steps.env` and the `GlobalEnv` to compute the cache key hash, so we actually _eagerly_ invalidate the cache any time _any_ environment variable changes, even if it isn't used in the step.

I tested this locally with src-cli, with both an environment variable set by my local environment and one defined inline with the steps, as well as server-side with a variable defined inline. In every case, the cache was invalidated whenever the environment variable changed (and used whenever they didn't). Is there some other case I'm missing?

**Comment by courier-new** [comment]
Talked about this with Erik, we're good on the env vars front! Going to close this one and update #42611.
