### ISSUE TITLE
Code intelligence for ASP.NET (aspx/ashx/asmx/...)

### ISSUE THREAD

**Issue by dobrou** [sourcegraph/sourcegraph#4262]
#### Feature request description

Add code intelligence and syntax highlight for ASP.NET (aspx/ashx/asmx/...).
Currently aspx/ashx/asmx files lacks any syntax highlight and code intelligence.

Those files are usually mix of xml and dotnet code, while both parts are already supported in sourcegraph.

#### Is your feature request related to a problem? If so, please describe.

I miss syntax highlight and code intelligence in asp.net files.
I miss also symbol search results from asp.net files.

**Comment by slimsag** [comment]
Syntax highlighting added in #10374 and will be in Sourcegraph 3.16.

Other code intelligence language support will still need to be added.

Example:

![image](https://user-images.githubusercontent.com/3173176/80898270-4ce16d80-8cb6-11ea-893f-49ab53f9e9ed.png)

**Comment by scalabilitysolved** [comment]
With syntax highlighting working and our current year planned out, should this issue be closed for now or tracked somewhere else? @macraig

**Comment by macraig** [comment]
Closing issue, feature request tracked in Productboard (so both :) )
