### ISSUE TITLE
`sourcegrap/sourcegraph` repo clone is much slower than expected in regression tests

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#42637]
## Steps to reproduce:

1. Add `describe.only` to [the "Basic code graph regression test suite" test](https://github.com/sourcegraph/sourcegraph/blob/3f3d8f4d4979577877acda66f2d5edbb11562604/client/web/src/regression/codeintel.test.ts#L103).
2. `TAG=insiders sg run server`
3. `SOURCEGRAPH_BASE_URL=http://localhost:7080/ GITHUB_TOKEN=XXX SOURCEGRAPH_SUDO_TOKEN=XXX sg test web-regression`

See [docs on how to run regression tests locally](https://docs.sourcegraph.com/dev/how-to/testing#starting-regression-tests).

## Expected behavior:

The https://github.com/sourcegraph/sourcegraph clone is not timed out.

## Actual behavior:

The https://github.com/sourcegraph/sourcegraph [clone](https://github.com/sourcegraph/sourcegraph/blob/3f3d8f4d4979577877acda66f2d5edbb11562604/client/web/src/regression/codeintel.test.ts#L66-L80) is timed out. The timeout [was increased](https://github.com/sourcegraph/sourcegraph/pull/15809) two years ago. [Recently tests started failing](https://bit.ly/3CixAcW) with a low percentage of the repo being closed before the timeout (in my local testing, it failed with 6-10% of the repo being cloned). We can increase the timeout again, but the time regression looks big enough to investigate the reasons behind it.

/cc @jplahn @ryphil

**Comment by valerybugakov** [comment]
Added two team labels:
1. The code-intelligence team owns the failing test.
2. The issue is caused by the slow repo clone, which is a domain of the repo management team.

Please reassign if you see a better owner.

**Comment by jhchabran** [comment]
I'd like to add that this issue is affecting the CI pretty often as the following graph shows: 

<img width="1580" alt="CleanShot 2022-10-06 at 15 22 44@2x" src="https://user-images.githubusercontent.com/10151/194324291-bb74ffaf-929b-44ba-830a-f2375985b245.png">

Therefore, it would really help if we could fix this promplty 🙏

**Comment by mollylogue** [comment]
@valerybugakov I'm looking into this now, trying to reproduce the behavior. Can you tell me where to find the secrets for running the tests locally? Particularly `SOURCEGRAPH_SUDO_TOKEN`

**Comment by valerybugakov** [comment]
@mollylogue, for my local testing, I created `SOURCEGRAPH_SUDO_TOKEN` manually via site-admin. Following my instructions above, the URL would be: http://localhost:7080/site-admin/tokens

<img width="1479" alt="Screenshot 2022-10-07 at 16 26 27" src="https://user-images.githubusercontent.com/3846380/194508632-4ba9da92-90c2-4c31-8c4e-4714c52f6e85.png">
 
For `GITHUB_TOKEN,` I used my personal token. We also have a couple of GH tokens in the company 1Password vault, but I didn't test them.

**Comment by mollylogue** [comment]
So, I can reproduce the behavior locally, but I'm wondering... is the concern that the repo clone is taking a while? It looks like it takes a bit longer in this test setup than it does on a production instance (I tried cloning it on the scaletesting instance and it took somewhere between 1-1.5 minutes). Is the concern here that clones in general are too slow, or that it's particularly slow in this test setup? Are we looking to diagnose why repo clones are slow in general or do we want to figure out how to speed things up in this testing scenario so we don't see timeouts? To that end, is there a reason why this test _needs_ the sourcegraph monorepo? Would it be better to do the test with a smaller repo that would clone more quickly?

**Comment by valerybugakov** [comment]
> is the concern that the repo clone is taking a while?

The concern is the significant increase in time required to clone the `sourcegraph/sourcegraph` repo in this regression test. It started happening recently, so it might indicate the underlying problem that will bite us later. 

> To that end, is there a reason why this test needs the sourcegraph monorepo?

Looking at the test logic, I would say that the `sourcegraph/sourcegraph` repo is not required.

> Would it be better to do the test with a smaller repo that would clone more quickly?

If the regression is not concerning and it's expected behavior for test setup, we can look into switching to a smaller repo.
