### ISSUE TITLE
CIP Research Support

### ISSUE THREAD

**Issue by danielmarquespt** [sourcegraph/sourcegraph#42648]
## Design process

  - Estimate: 3 days 

[Supporting Document](https://docs.google.com/document/d/1Q6enYeShQOWlHE1DpkgVIPzJxpqhterz8qb6a5dEbko/edit#)

  ### Discover
  - [ ] Product and/or engineering provide direction and/or feedback
  - [X] Competitive Analysis

  ### Define
  - [X] Github issue

  ### Interviews
  - [ ] Call users

  ### Deliver
  - [ ] Compile Insights
  - [ ] Export quotes from recordings

**Comment by malomarrec** [comment]
Hey @danielmarquespt, this issue didn't have a team label. Given you created it, I assigned you and added your team label. Feel free to unassign yourself. If this is not the right label, can you make sure to add the right one?
