### ISSUE TITLE
Adding AMI support for GCP

### ISSUE THREAD

**Issue by jjeffwarner** [sourcegraph/sourcegraph#42660]
- [x] #43407
- [x] #43408
- [x] #43409
- [x] #43406
- [x] #43410
- [ ] #43438

/cc @sourcegraph/delivery

**Comment by abeatrix** [comment]
google compute images are available to use and download in our docsite: https://docs.sourcegraph.com/admin/deploy/machine-images/gce

we already have customer using the images https://sourcegraph.slack.com/archives/CDVGH9RDF/p1667320184539029
