### ISSUE TITLE
insights: capture group aggregations and insights are only returning the last sub-match from a set of matches

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#42665]
We should be able to match all capture groups from the "first" capture group, across all sub-matches.

For example given a regexp `(hot)-(dot)` we should be able to match against the string `hot-dog hot-dog` and get `hot:2`

This unblocks use cases like tracking which items are imported from an API in typescript, like the below example ("which components are imported from rxjs the most"). 

For example, this query matches but [the insight](https://sourcegraph.sourcegraph.com/insights/insight/aW5zaWdodF92aWV3OiIyRmxpeU5qQzBVMTI1Nkc0ekVQdlJDcWwyc00i) and [aggregation](https://sourcegraph.sourcegraph.com/search?q=repo%3A%5E%28github%5C.com%2Fsourcegraph%2Fsourcegraph%29%24+import%5Cs%7B%28%3F%3A%5Cn%5Cs%2B%28%5Cw%2B%29%2C%29%2B%5Cn%7D%5Csfrom%5Cs%27rxjs%27&patternType=regexp&groupBy=group) only return the final match (last match in the set, or last component in the list). 

![image](https://user-images.githubusercontent.com/11967660/194403577-fd0286ea-18fe-46d5-970b-aa42c29c2dc9.png)

![image](https://user-images.githubusercontent.com/11967660/194403840-61f56dff-f3d8-4b08-960f-e1a9a97f9866.png)

![image](https://user-images.githubusercontent.com/11967660/194403927-bc53cebe-bb48-48d7-b0ed-36104b8cc985.png)

/cc @joelkw @felixfbecker @vovakulikov

**Comment by coury-clark** [comment]
Just to clarify, there was a misunderstanding in Slack and I suggested this should be possible with regexp. That isn't the case, since repeating groups will not cause repeated captures as group $1. We can consider adding support for structural search into aggregations for this purpose. I'm going to close this until we have a reason to move towards that direction.
