### ISSUE TITLE
webapp regression: highlighted search result snippets are not bailed out after a few seconds as they should be

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#4268]
It used to be the case that if you ran a search and it hit very large files the syntax highlighter could not handle that we would bail out after a few seconds and display a plaintext version.

Instead, today, we appear to have a regression in which these files take as long as they please to highlight -- making some search result snippets not load for over 30s.

Reported by https://app.hubspot.com/contacts/2762526/company/407948923

**Comment by beyang** [comment]
What kind of test would prevent this sort of regression in the future? Unit, dogfooding, load test, e2e?

**Comment by slimsag** [comment]
https://github.com/sourcegraph/sourcegraph/pull/4364 for how we can test this in the future (e2e test).

**Comment by felixfbecker** [comment]
Isn't the bug here in the frontend render code? Why can't we test this with a frontend unit test?

**Comment by slimsag** [comment]
@felixfbecker https://github.com/sourcegraph/sourcegraph/pull/4364#issuecomment-499001945
