### ISSUE TITLE
Users.Delete is mostly untested

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#427]
We have a single test for `db.Users.Delete`, and it basically only tests that a user account created will be deleted. However, it does not test / verify that any associated data (excluding code discussions) is deleted and we delete A LOT of associated data.

**Comment by sqs** [comment]
You and I both added more tests in the last few days (me in https://github.com/sourcegraph/sourcegraph/pull/514), so it's not as bad as it was. I am going to close this because I assume that you'd consider the lack of tests to no longer be issue-worthy (since there are fairly good tests now).
