### ISSUE TITLE
[Site Admin - User Administration] Sorting by Last Active shows never active accounts first

### ISSUE THREAD

**Issue by c69-addepar** [sourcegraph/sourcegraph#42708]
#### Steps to reproduce:

1. Go to `Site Admin > Users` https://FIRM-SUBDOMAIN.sourcegraph.com/site-admin/users
2. Sort by `Last Active`, descending

#### Expected behavior:

The most recent last active is first.

#### Actual behavior:

Never active users (column value `null` ?) are shown first:
![image](https://user-images.githubusercontent.com/73544321/194603684-5f09180e-28ee-47d2-b960-77d0484d3812.png)

/cc @sourcegraph/iam

**Comment by mrnugget** [comment]
Code here needs to be modified: https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@fbb2b8ca1bd3e78169fd26b22bb27f2b63bde25b/-/blob/internal/users/stats.go?L188-203

**Comment by malomarrec** [comment]
@c69-addepar we've added this, and it's shipping in the upcoming January release (we typically release around the 20th). Thanks again for submitting feedback!
