### ISSUE TITLE
webhooks: Implement List database method

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#42740]
/cc @jplahn @ryphil

**Comment by mollylogue** [comment]
@sashaostrikov were you wanting to work on this? sorry if I stepped on your toes... I just have a WIP PR for the first part of the implementation so far.

**Comment by mollylogue** [comment]
https://github.com/sourcegraph/sourcegraph/pull/42775

**Comment by sashaostrikov** [comment]
Nono, I just thought it is unassigned 😀 then saw a WIP PR and realized that it is assigned in fact, sorry for the mess :)
