### ISSUE TITLE
Cannot click on Saved search link

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#4274]
![ScreenFlow](https://user-images.githubusercontent.com/133014/58672877-d39b0700-82fd-11e9-8982-fad71e935694.gif)

**Comment by dadlerj** [comment]
This is a pretty bad one — is there any other way to use saved searches @attfarhan or is this just totally broken?

**Comment by slimsag** [comment]
This was actually ONLY a regression on Sourcegraph.com, since it was introduced in ea219ab which has not been released in any official version.
