### ISSUE TITLE
Code Insights: Improve dashboard context menu positions and visual state

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#42753]
[Related slack thread](https://sourcegraph.slack.com/archives/C0HMGV90V/p1664537026786349)

At the moment, in code insights, we align menu items by the right side (because of this, whenever you read a new item below, you have to look it's beginning to read it)

| Current position | Proposal |
| ---------------- | --------- |
| <img width="378" alt="screenshot_2022-09-30_at_17 35 48" src="https://user-images.githubusercontent.com/18492575/194873231-6cd4d566-f0bd-4c0e-9048-43daa8047769.png"> |  <img width="553" alt="screenshot_2022-09-30_at_17 40 48" src="https://user-images.githubusercontent.com/18492575/194873562-b73aa7fa-60da-4e46-912c-b503530de375.png"> |

- Left align items in the menu
- Move the menu to the right, analogically to how filters open
- Add pressed/opened state for context menu triggers (three-dot button)

/cc @joelkw @felixfbecker @vovakulikov

**Comment by coury-clark** [comment]
backlog
