### ISSUE TITLE
aws: AWS Marketplace

### ISSUE THREAD

**Issue by jjeffwarner** [sourcegraph/sourcegraph#42769]
- [ ] Foundational Technical Review for AWS Marketplace ([chat](https://sourcegraph.slack.com/archives/C042DHN76HE/p1663302496231619?thread_ts=1662702169.213699&cid=C042DHN76HE)) @beyang 

/cc @sourcegraph/delivery/search-core

**Comment by malomarrec** [comment]
Hey @jjeffwarner, this issue didn't have a team label. Given you created it, I assigned you and added your team label. Feel free to unassign yourself. If this is not the right label, can you make sure to add the right one?

**Comment by beyang** [comment]
Closing in favor of #46756
