### ISSUE TITLE
Cannot make GitLab source stop cloning all the repositories

### ISSUE THREAD

**Issue by zurp** [sourcegraph/sourcegraph#4277]
- **Sourcegraph version:** insiders
- **Platform information:** linux 5.1.5-arch1-2 x86_64, docker 18.09.6-ce

#### Steps to reproduce:

1. Add GitLab (enterprise) source with:

```json
{
  "url": "...",
  "projectQuery": [
    "groups/my-group/projects",
    "?membership=true"
  ],
  "projects": [
    {
      "id": 123
    }
  ],
  "initialRepositoryEnablement": false
}
```

2.

#### Expected behavior:

It respects the rules and doesn't import & clone repositories outside of the projectQuery / projects / initialRepositoryEnablement configurations.

#### Actual behavior:

It imports all the repositories and starts cloning them immediately.

**Comment by keegancsmith** [comment]
initialRepositoryEnablement is deprecated and not respected anymore. See the documentation for the field in the schema:

> Deprecated and ignored field which will be removed entirely in the next release. GitHub repositories can no longer be enabled or disabled explicitly. Configure repositories to be mirrored via "repos", "exclude" and "repositoryQuery" instead.

Are there being repositories being cloned which are outside of your projectQuery and projects list?

Additionally I am unsure which version `insiders` is exactly (Changes over time). Can you report what http://yoursourcegraph.com/__version says?

**Comment by neculaesei** [comment]
@keegancsmith version 36237_2019-05-30_cdedd0e

It's cloning all the repositories (over 250), ignoring the projectQuery and projects properties.
What I've tried is rebuilding the container multiple times (deleting data as well) and setting it up from scratch.

**Comment by keegancsmith** [comment]
will investigate and report back here. cc @sourcegraph/core-services

**Comment by tsenart** [comment]
Sorry for the long wait. This fell through the cracks. It seems to us that what is making Sourcegraph clone all your repositories is the `"?membership=true"` project query. Are you sure you're not a member of all those projects being returned?

**Comment by tsenart** [comment]
@zurp: Friendly ping :)

**Comment by zurp** [comment]
> @zurp: Friendly ping :)

Sorry for the delay, missed the previous reply and had to set up sourcegraph again.
I can confirm that I'm not a member of the projects that were getting cloned.
I managed do what I wanted initially like this:

```
"projectQuery": [
    "none"
  ],
  "projects": [
    {
      "name": "my-team/project"
    }
  ]
```
Thank you!

**Comment by keegancsmith** [comment]
@zurp great so you are unblocked now with the new config you tried? If you need any other help, go ahead and file an issue and feel free to ping us :)

**Comment by zurp** [comment]
@keegancsmith yes, it all works great now! thank you for the help!
