### ISSUE TITLE
webhooks: Create new "top level" HTTP handler

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#42812]
Our [current webhook](https://github.com/sourcegraph/sourcegraph/blob/3dd98920f51d16c0b3a26545b1b2ed7dfb19fe6a/cmd/frontend/internal/httpapi/router/router.go#L59-L62) routes are code host specific: 

`/github-webhooks`
`/gitlab-webhooks`
etc

Instead, we want a new route to handle all webhooks:

`/webhooks/{webhook_id}` where `webhook_id` is the `uuid` column from our
new `webhooks` table.

The handler only needs to look up the correct `webhook` entity in the database 
to determine the kind. From there it can hook into our existing handler code and
use the secret stored against the `webhook` where needed. 

Out existing handlers should continue to handle requests until we deprecate them 
later.

- [x] Ensure top level handler works for existing GitHub payloads
- [x] Ensure top level handler works for existing GitLab payloads
- [ ] #44063

/cc @jplahn @ryphil

**Comment by ryanslade** [comment]
@pjlast I added some subtasks to track ensuring that the new handler works with existing payloads

**Comment by pjlast** [comment]
@ryanslade perfect, thanks!

**Comment by ryanslade** [comment]
I don't think we can close this until we've ensured that it works with the existing payloads for GitHub, GitLab and Bitbucket

**Comment by sashaostrikov** [comment]
@ryanslade @pjlast

How should we ensure that existing payloads work with new handler? Do we have/need a task for it?

Asking because this issue is the last in a Milestone 1 and looks like we are being this close to achieve it, but holding off for some reason.

**Comment by ryanslade** [comment]
We're done for [GitHub](https://github.com/sourcegraph/sourcegraph/pull/43224) and [GitLab](https://github.com/sourcegraph/sourcegraph/pull/43471)

The plan was for the batch changes team to take on the final one for BitBucket but perhaps we should take that too so that we have Milesone 1 done before the next release.

**Comment by sashaostrikov** [comment]
@ryanslade I've decided to create a task for that for extra motivation (and tracking of it)

https://github.com/sourcegraph/sourcegraph/issues/44063

**Comment by ryanslade** [comment]
Cool, I added it to the tracking issue.

**Comment by ryanslade** [comment]
I'm going to close this parent issue since the last remaining task is already tracked separately
