### ISSUE TITLE
sg start oss failing after a few checks

### ISSUE THREAD

**Issue by garythung** [sourcegraph/sourcegraph#42853]
System: GCP VM instance, Ubuntu 22.04.1 LTS

First issue was `sg setup` would hang.

<img width="1644" alt="image" src="https://user-images.githubusercontent.com/7055455/195244622-4f914dbf-4ef0-458c-b0ee-91f608250dc0.png">

I got around this by manually installing/fixing the sg setup dependencies.

Then, `sg start oss` fails after a few checks run (it's random; not always the same 3-4).

<img width="402" alt="image" src="https://user-images.githubusercontent.com/7055455/195244536-3872738e-a76c-46f1-ac5a-04b36a263ef0.png">

**Comment by garythung** [comment]
Removing the docker check for oss in `sg.config.yaml` fixes it. However, my machine is having trouble responding to `CTRL + C` SIGINTS.

**Comment by burmudar** [comment]
@garythung This should be fixed! If experience anything else don't hesitate to re-open this issue!
