### ISSUE TITLE
sourcegraph logo doesn't load in the /search 

### ISSUE THREAD

**Issue by thara003** [sourcegraph/sourcegraph#42854]
- **Platform information:**  macOS and Brave v1.44.108

#### Steps to reproduce:

1. Go to https://sourcegraph.com/search
2. See the logo in the left-top corner

#### Expected behavior:

Logo is supposed to be loaded.

#### Actual behavior:

Logo isn't loading instead alt text is shown which makes the UI inconsistent.

![Screenshot 2022-10-12 at 11 27 04 AM](https://user-images.githubusercontent.com/79561774/195262592-065069b1-1a2f-44aa-8631-60e7549ad21c.png)

**Comment by LawnGnome** [comment]
Thanks! I just noticed this as well.

I think this was caused by #42736; cooking up a fix now.

**Comment by thara003** [comment]
You're welcome! I was searching a code snippet and found the bug.
