### ISSUE TITLE
insights: data retention / data pruning spike

### ISSUE THREAD

**Issue by leonore** [sourcegraph/sourcegraph#42872]
right now we have no functionality in place to delete data that is older than 12 frames of data/older than a year i.e. delete data that we do not show to a user. insights only went into GA in march so this might not have too much impact now but could make a big preemptive step to save data

/cc @joelkw @felixfbecker @vovakulikov

**Comment by coury-clark** [comment]
I'm not so sure that deleting old points is the right approach, we might also want to consider downsampling instead. That way we can still preserve the long term trends, but more recent points have the granularity.

p2

**Comment by chwarwick** [comment]
pending product decision on what to retain.

**Comment by leonore** [comment]
closing as a product decision has been made and we can move forward with the engineering work. tracking issue https://github.com/sourcegraph/sourcegraph/issues/45775
