### ISSUE TITLE
insights: Set a maximum number of data points retained for a series 

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#42880]
Currently insights displays all data points for the last 12 months and will extend that timeframe to ensure at least 12 points are displayed. These are good defaults for Monthly and Yearly insights but insufficient for hourly, daily or weekly insights.  Users have little incentive to delete an insight when it is no longer in use so they will continue to add data.  

Using the existing methodology: 
- weekly insights could contain up to 52 points
- daily insights could contain up to 365 points
- hourly insights could contain up to 8760 points.

With this many data points recorded we increase the storage requirements and load time of the insight, in addition the chart produced becomes very compressed and difficult to distinguish any individual points.  Example here:

<img width="566" alt="Screen Shot 2022-10-12 at 10 20 04 AM" src="https://user-images.githubusercontent.com/6098507/195369110-b375126e-2a9b-48df-9d13-ab453eec33ad.png">

While this [issue](https://github.com/sourcegraph/sourcegraph/issues/42872)  relates to purging series data once it will no longer be displayed, it does not address lower the amount of points that a single series could accumulate in 12 months.

This issue is to limit the maximum number of individual data points any series can contain to `24` points plus 1 snapshot.  This means that for weekly, daily or hourly insights a user will get an additional 12 time intervals before any data is removed.   

/cc @joelkw @felixfbecker @vovakulikov

**Comment by coury-clark** [comment]
product question: what to do here? lots of complications around the granularity / size of insight
