### ISSUE TITLE
insights: spike on structural search for either/both aggregations and capture-group insights

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#42895]
We can split this spike into two. Noting at the moment we are not sure if over-time is important to the driving use case – will confirm before we'd determine which to spike on (if not, aggregations likely easier to spike on). 

[Context](https://sourcegraph.slack.com/archives/C01RVEVPWLC/p1665593043295639)

/cc @joelkw @felixfbecker @vovakulikov

**Comment by coury-clark** [comment]
p1

**Comment by chwarwick** [comment]
backlog

**Comment by chwarwick** [comment]
Closing this is currently unplanned.  Will create a new issue if we revisit this in the future.
