### ISSUE TITLE
Supporting LFS

### ISSUE THREAD

**Issue by jjeffwarner** [sourcegraph/sourcegraph#42903]
- [ ] Research and document finding around using LFS for indexing
- [ ] Research and document finding for displaying content on web interface.
- [ ] MVP for web interface awareness of LFS files.

[Slack conversations](https://sourcegraph.slack.com/archives/C023ELQLV7F/p1665578436931409?thread_ts=1665115385.257219&cid=C023ELQLV7F)

**Comment by keegancsmith** [comment]
web interface awareness of LFS files was done here https://github.com/sourcegraph/sourcegraph/pull/43686
