### ISSUE TITLE
Bazel: Make sure Bazel has permission to access storage bucket as remote cache

### ISSUE THREAD

**Issue by marekweb** [sourcegraph/sourcegraph#42908]
Setting Bazel's remote cache with the build flag, to point to the storage bucket for the purpose, `sourcegraph_bazel_cache`

```
--remote_cache=https://storage.googleapis.com/sourcegraph_bazel_cache
```

We need to make sure Bazel has read and write permissions to the storage bucket from within CI:

```
--google_credentials=/path/to/your/secret-key.json
```

or with default application authentication:

```
--google_default_credentials
```

Bazel docs section: https://bazel.build/remote/caching#cloud-storage

**Comment by jhchabran** [comment]
Bet closed, see tracking issue for a recap.
