### ISSUE TITLE
Botched scope in SentryS2-P7

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#42934]
`[server.SecurityEvents.session > Execute > AlertJob > TimeoutJob > LimitJob > ParallelJob > RepoPagerJob > searchrepos.Pagina...`

See https://sentry.io/organizations/sourcegraph/issues/3665218062/?project=6583153

**Comment by davejrt** [comment]
@jhchabran can we sync on this so I can get some more context on what is exactly is wrong? I found the offending code but not entirely sure what's "bad" about the results.

**Comment by jhchabran** [comment]
The bad part about the result is this: 

<img width="1345" alt="CleanShot 2022-11-10 at 10 44 43@2x" src="https://user-images.githubusercontent.com/10151/201056859-1d53787a-f5be-461b-8eb3-dbfb8016378e.png">


This should be something of the form `a.x.y.z` not `a.x > .... > ...` it seems that the wrong string is passed to the scope.

**Comment by davejrt** [comment]
Found another example here

https://sentry.io/organizations/sourcegraph/issues/3794046312/?project=6583153&query=RepoPagerJob&referrer=issue-stream&statsPeriod=14d

Following the code path, I have to admit I'm a little lost. I'm going to schedule some time next week to properly dig into this.
