### ISSUE TITLE
insights: spike on user scoped insights

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#42948]
1. expanding scope from user A to user B on a user scoped insight

goal should be to determine orders of magnitude in how complicated edge cases are to inform product decisions

/cc @joelkw @felixfbecker @vovakulikov

**Comment by coury-clark** [comment]
timebox to 3-5d

**Comment by leonore** [comment]
findings are that this might be an overly complex paths, with many edge cases. highlights:

- we'd need to store backfill state per-user (which isn't impossible but adds a lot of complexity)
- this still doesn't tackle the issue that we don't know how to limit repos e.g. user's A insight is ran to a permissions across 30k repos, but user B has access to 60k more repos. do we want to enforce that limit? if this keeps growing across users eventually we will reach an all repos insight.

given the latter, pivoting to a more useful implementation-specific spike, related to actually giving users the option of creating scoped insights more usefully: https://github.com/sourcegraph/sourcegraph/issues/43497
