### ISSUE TITLE
Add a few repos to instances by default

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#42982]
When users initially join a trial instance, there's no repo indexed.
This creates a "cold start" effect where you don't get any sense of value until you add your codehosts.

#### Proposal

- add a few OSS repos to the instance so that users can immediately start searching code.
- syncing: (depends on investigation), preference for yes
- context: create a context that contains those default repositories (maybe called `onboarding`)

#### Next steps

- [ ] @erzhtor will investigate mechanism
- [ ]  @malomarrec  best way to only enable a feature: env variable or license? (some [points](https://docs.google.com/document/d/1jbh3z9YkvW-40QFVHIib9f40JNl-FvXKhIGodI_iHgc/edit?disco=AAAAiBXwniQ) here)
- [ ] brainstorm list of repos
- [ ] build!

**Comment by malomarrec** [comment]
**Brainstorm**: list of repos we should pre-load?

I think we need one per language.

- golang
- java
- C
- python
- typescript
- frontend frameworks (vue, react, angular, svelte, ember)

**Comment by malomarrec** [comment]
Status:
- there's a working draft PR
- it's not as low effort as we thought
- we can postpone in favor of onboarding as initially planned

**Comment by malomarrec** [comment]
@erzhtor what was the draft PR that you had for this?

**Comment by erzhtor** [comment]
> Add initial onboarding (public) repos #44398

This one https://github.com/sourcegraph/sourcegraph/pull/44398. It is also linked/mentioned in the issue

**Comment by malomarrec** [comment]
Dammit. Guess what: it doesn't appear when you open the issue in the GitHub board view


![Image](https://user-images.githubusercontent.com/25070988/204316620-de1cbedd-8c7d-4a1f-aa95-97826c9592f0.png)

**Comment by erzhtor** [comment]
Closing in regards to https://github.com/sourcegraph/pr-faqs/issues/1.
