### ISSUE TITLE
executors: Fix up Terraform Deployment Docs

### ISSUE THREAD

**Issue by Piszmog** [sourcegraph/sourcegraph#43011]
While [setting up executors](https://github.com/sourcegraph/infrastructure/pull/4078) for the scaletesting instance, I dogfood our [terraform deployment docs](https://docs.sourcegraph.com/admin/deploy_executors_terraform). I ran into a few confusions while setting everything up (thus slowing me down and making me unsure about what I was doing).

## Updates

* Add a table or list of the possible `<cloud>` values. 
    * Be nice to associate values with links to the terraform module repos
* Update references to all variables to match what the user would actually use (for example, instead `min_replicas` it should be `executor_min_replicas`)
* Revisit the step-by-step installation guide to ensure everything still makes sense
    * If a user is setting up a batches executor, they probably do not need to set `codeIntelAutoIndexing.enabled` in the site config
* Update references to `4.0.0` to `4.0.1` (there is a bug in `4.0.0`)
* Autoscaling should have `metric_writer_credentials_file` with `sensitive = true`
    * User needs to run `terraform output  metric_writer_credentials_file` to get value
    * This may apply to the AWS values as well
* Specify what roles a user must have to set everything up in GCP and AWS 
    * For example in GCP, user must have `compute.disks.create`, `iam.serviceAccounts.create`, `compute.networks.create`, and permissions to create a role in the project (scaling requires Secret Manager permissions). There are probably more roles a user needs beyond these

**Comment by chrispine** [comment]
I love me some tight docs! I'd prefer not backlog for this one, but no strong feelings otherwise
