### ISSUE TITLE
scaletesting: update the handbook about the GHE instance

### ISSUE THREAD

**Issue by burmudar** [sourcegraph/sourcegraph#43032]
Document the newly added GHE instance in scaletesting

- https://github.com/sourcegraph/infrastructure/pull/4082

Should cover: 

- [ ] How to access it 
- [ ] How to deploy / edit it 
- [ ] How to get admin access
- [ ] How to deal with the licenses 
- [ ] What are the expectations toward the data on that instance

**Comment by kalanchan** [comment]
PR here:
- https://github.com/sourcegraph/handbook/pull/5309
