### ISSUE TITLE
ScaleTesting: GitHub: Declaratively support creating users on a GHE instance

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#43045]

**Comment by sanderginn** [comment]
@jhchabran if I understand it correctly, do you mean with this ticket "Given a file or state with a list of users (and perhaps other entities), create those users on the instance"?

**Comment by sanderginn** [comment]
Moving this back to "proposed" until there is a clear use case for this.

**Comment by sanderginn** [comment]
Closing, not in scope with current Job Fair projects.
