### ISSUE TITLE
Scaletesting: [IAM] Reproducing an existing customer environment to hunt bugs

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#43049]
- In order to reproduce _customer_ issues, we need to have:
  - [x] #43051
  - [x] #43052

/cc @sourcegraph/iam

**Comment by kopancek** [comment]
Commented on the linked issues as to what actual size we are looking for. Let me know if that is too much to ask.

**Comment by sanderginn** [comment]
Closed by linked issues
