### ISSUE TITLE
webhooks: Basic CRUD UI

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#43050]
This is a supertask for webhooks site admin page implementation.

Pages should be hidden by default so that we can iterate on them without impacting customers.

### Note
[Figma mockups](https://www.figma.com/file/ngPEwLqRVFAfXQC7lE0WLz/Webhooks?node-id=0%3A1) are not final and subject to change.

### Subtasks (new tasks can be added)

- [x] #43486
- [x] #43487
- [x] #43488
- [x] #43490
- [x] #44000
- [x] #44135
- [x] #44696
- [x] #44720
- [x] #44730
- [x] #44758
- [x] #45150
- [x] #45206
- [x] #45237
- [x] #45325
- [x] #45401

/cc @jplahn @ryphil

**Comment by mollylogue** [comment]
Notes: 
- remove "send test event" button
- ensure that the "copy" button next to the webhook url works
- in practice, the "External Service" column in the logs under the webhook page is showing "Unmatched". Is it just matched for the deprecated webhooks? How is this value populated, and is there a way to make this look less confusing to the user?

**Comment by sashaostrikov** [comment]
@mollylogue "copy button" works for me 🤔 
can you pls double-check it?

**Comment by mollylogue** [comment]
> @mollylogue "copy button" works for me 🤔 can you pls double-check it?

Yes, it does. 🤦‍♀️ I wonder how I messed that up last time. Looks good 👍

**Comment by sashaostrikov** [comment]
🎉🎉🎉
