### ISSUE TITLE
Scaletesting: [IAM] 200k repos on GHE with just a README

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#43051]
Let's just write a script that does that.

**Comment by kopancek** [comment]
We would like to get to 2XL scale testing. Based on this doc: https://docs.google.com/spreadsheets/d/1n-KfGc8m1w09rIzNKm5tRxAYmP4-w11CVOCplMvVazk/edit#gid=1172385107 that's 500k repositories.

But I'm not sure if 200k vs 500k is a major hurdle.

**Comment by burmudar** [comment]
@kopancek We've created these repos on https://ghe-scaletesting.sgdev.org instead, since ghe.sgdev.org is very slow atm. The repos can be found at https://ghe-scaletesting.sgdev.org/blank200k. I'm busy converting them to be private
