### ISSUE TITLE
webhooks: Add a resolver that requests a ping event and confirms delivery

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#43104]
Initially we can implement this just for GitHub. 

The idea is that we have a resolver that will request a ping event and then check that the event appears
in our `webhook_logs` table in a defined period of time.

Before this can be implemented we need to store the external hook id with our webhook entity. Until 
we decide how best to do that, this issue is on hold.

/cc @jplahn @ryphil

**Comment by malomarrec** [comment]
Hey @ryanslade, this issue didn't have a team label. Given you created it, I assigned you and added your team label. Feel free to unassign yourself. If this is not the right label, can you make sure to add the right one?

**Comment by ryanslade** [comment]
In order to cut scope a little I think maybe we should drop this feature. 

It's already pretty easy to test without a button since we are able to view received payloads in our UI and code hosts often already allow you to send test events (confirmed with GitHub and GitLab).

It seems like unnecessary complexity to add a new UI with async behaviour to trigger an event on the code host.

**Comment by mrnugget** [comment]
Closing this. Let's see when it pops up again.
