### ISSUE TITLE
webhooks: Integrate with existing webhook_logs table

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#43105]
We need to integrate the existing webhook_logs table with out new webhooks table.

We'll need to add an optional foreign key to webhook_logs so that we can link the two tables. It's
optional since the existing logs table also needs to record logs for "old style" webhooks that are linked
to an external service.

We need to ensure that hooks coming in via our new global handler are also recorded in the
webhook_logs table.

/cc @jplahn @ryphil

**Comment by mollylogue** [comment]
@ryanslade Could you clarify what this means exactly?

**Comment by ryanslade** [comment]
Hah, the sourcegraph-bot overwrote my comments 😦

**Comment by mollylogue** [comment]
Plan: Do this in a few PRs
- [ ] add webhook_id column to webhook_logs table w/ fk constraint
- [ ] update the handler where the logs are created to add the webhook id

(see [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/webhooks/middleware.go?L66-76) and [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@155c9cd8019a0c2c8288209908761fe4e133d5b6/-/blob/cmd/frontend/webhooks/github_webhooks.go?L53-59) for where the external service id is found/set for the webhook log)

**Comment by mollylogue** [comment]
Just wanting to make sure I'm understanding here... When we find/set the external service id (which we then use when creating the webhook_log entry) we use the form value (see [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@155c9cd8019a0c2c8288209908761fe4e133d5b6/-/blob/cmd/frontend/webhooks/github_webhooks.go?L144&subtree=true)) _or_ we iterate through all configured GitHub external services (in [this function](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@155c9cd8019a0c2c8288209908761fe4e133d5b6/-/blob/cmd/frontend/webhooks/github_webhooks.go?L151&subtree=true)) to find one that matches. Is the idea that the webhooks coming from GitHub will be configured to contain the webhook id, so we can also look it up in a similar way to the external service? Or should we use the external service id we find to look up a webhook which matches the type/url/secret?

**Comment by mollylogue** [comment]
Nvm.. I see where the routes containing the webhook uuids were added [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@155c9cd8019a0c2c8288209908761fe4e133d5b6/-/blob/cmd/frontend/webhooks/webhooks.go)

**Comment by ryanslade** [comment]
We just moved things around a little which means they're now at `/.api/webhooks/uuid`:

https://github.com/sourcegraph/sourcegraph/blob/c08bb6b90030e53780554fb5c43993c29d85c4ca/cmd/frontend/internal/httpapi/router/router.go

**Comment by mollylogue** [comment]
I've validated locally that the appropriate webhook id gets added to the webhook log when an event comes in. So we should be good to close this.
