### ISSUE TITLE
insights: better error message in the UI that repo revisions disallowed 

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#43114]
Context from a teammate at sourcegraph (so screenshots okay to share): 
> I just found a chicken-and-egg problem when using the rev: filter in an Insight. I'm told to include the repo: filter and try again, but when I add the repo: filter to my search query, I get a different error message that I should not include the repo: filter because the targeted repos are added in a different form input than the query. See screenshots. I'm trying to create an Insight to show query results in main vs. non-main branches 

![image](https://user-images.githubusercontent.com/11967660/196510056-08fdd0ce-a9e3-4f99-a053-e9a0a6b06056.png)
![image](https://user-images.githubusercontent.com/11967660/196510108-485ffed1-06f1-4659-b0e7-e0e4d3200ce0.png)

/cc @joelkw @felixfbecker @vovakulikov

**Comment by chwarwick** [comment]
`rev:` should be disallowed too

**Comment by vovakulikov** [comment]
@chwarwick are you saying that we should include rev filter in client validation check? or backend should extract this filter from the query and process processed query without non support filters? or both?

**Comment by chwarwick** [comment]
@vovakulikov  I'm saying that currently it should not be valid to create an insight with a `rev:` filter.

**Comment by vovakulikov** [comment]
In this case it seems like a FE issue, I added it to triage column.

**Comment by coury-clark** [comment]
p0
