### ISSUE TITLE
Remove "external service namespace" from the database layer

### ISSUE THREAD

**Issue by miveronese** [sourcegraph/sourcegraph#43115]
We do not support any more code host connections (aka external services) added by users, only those added by site admins (via the admin area) are supported.

The removal of "namespaced external services" has been done in different steps:

- In the perms_syncer layer: e removed the code that was  fetching and syncing permission for user's external services (`fetchUserPermsViaExternalServices`) PR #42844
- In the graphql / frontend layer: removed some  checks for  external service/code host connections access and usage of `namespace_user_id` and `namespace_org_id`. PRs #43014 and #43023

The next step, covered by this issue, is to remove external services namespaces from the DB layer.

/cc @sourcegraph/source/iam

**Comment by malomarrec** [comment]
Hey @miveronese, this issue didn't have a team label. Given you created it, I assigned you and added your team label. Feel free to unassign yourself. If this is not the right label, can you make sure to add the right one?

**Comment by mrnugget** [comment]
Update: I think everything here is ready. `namespace_user_id` and `namespace_org_id` haven't been used in 2-3 releases.
