### ISSUE TITLE
Adding an accessing token and executing a curl command adds a duplicate / for the hostname for the .api path

### ISSUE THREAD

**Issue by amberfurbush0317** [sourcegraph/sourcegraph#43123]
- **Sourcegraph version:** 3.17.2
- **Platform information:** Docker Compose
- **Reported by:** https://github.com/sourcegraph/accounts/issues/6716 via [Slack](https://sourcegraph.slack.com/archives/C01D50MSA7L/p1665001608589309)

#### Steps to reproduce:

1.  Go into the UI 
2. Navigate to Access Token
3. Click `+ Generate new token`
4. Once the token is generated, it will pre-fill the Sourcegraph instance’s API endpoint, and it adds a duplicate `/` between the hostname and the .api path, so the command doesn’t work.

![image](https://user-images.githubusercontent.com/23640224/197060441-e68acc67-0762-44a8-bc5b-b4c75b5af42a.png)

#### Expected behavior:

The duplicate / shouldn't be between the hostname and the .api path.

#### Actual behavior:

In the UI, when the curl command example pre-fills the Sourcegraph instance’s API endpoint, it adds a duplicate / between the hostname and the .api path, so the command doesn’t work.

If you would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are not [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

/cc @sourcegraph/iam

**Comment by kopancek** [comment]
I cannot reproduce this issue on dotcom or S2.



![Image](https://user-images.githubusercontent.com/9974711/198573725-ceffe941-1996-4327-b271-c63863e27fa8.png)
![Image](https://user-images.githubusercontent.com/9974711/198573726-59735565-fa58-4c4a-8b43-072e825df057.png)

**Comment by kopancek** [comment]
Can we change their `externalURL` in site config to not contain a trailing slash? That should fix the problem while I change the code so that this cannot happen anymore.
