### ISSUE TITLE
Code navigation accessibility: Support arrow key blob navigation

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#43175]
## Description

We should allow <kbd>Up</kbd> <kbd>Down</kbd> <kbd>Left</kbd> <kbd>Right</kbd> arrow key navigation in the blob view.

**Acceptance criteria**:
- Up/Down navigation works in ALL files (even those without code intelligence)
  - Should just change the visible "focused" line, when clicked it should navigate to this line
- Left/Right navigation works in files with code intelligence.
  - Should allow cycling between tokens on a specific line. Allows for 1 handed keyboard nav in the blob view.

## Implementation

WIP Here: https://github.com/sourcegraph/sourcegraph/pull/42980

/cc @felixfbecker/frontend-platform

**Comment by limitedmage** [comment]
My personal opinion: What would be the difference/advantage between using left/right vs using tab/shift+tab? I think we should make the tokens tab-focusable and avoid left/right.

I like up/down though.

**Comment by quinnkeast** [comment]
I don't think that tab/shift+tab and left/right arrows are mutually exclusive options. Tab/shift+tab could _cycle_ through all the tokens (left-to-right, then wrap to the next line and continue), while arrow keys can act on the X and Y axes.

The advantage of supporting arrow keys on both X and Y axis is increased usability and intuitivity—the user can navigate quickly between tokens from just the arrow keys.

**Comment by lrhacker** [comment]
Navigation via arrow keys has been added in with #44698.
