### ISSUE TITLE
Tracking issue: Blob keyboard navigation

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#43176]
# [RFC](https://docs.google.com/document/d/1_y3OhK9V7k1axcvdtroqyjP15dmpvw2J4byaM3FGXW0/edit#heading=h.trqab8y0kufp)

## Description

Tracking issue for work required for improved keyboard nav in the blob view.

## Issues:

- https://github.com/sourcegraph/sourcegraph/issues/43175
- https://github.com/sourcegraph/sourcegraph/issues/42421
- https://github.com/sourcegraph/sourcegraph/issues/42420
- https://github.com/sourcegraph/sourcegraph/issues/42974
- https://github.com/sourcegraph/sourcegraph/issues/43179
- https://github.com/sourcegraph/sourcegraph/issues/43431

/cc @felixfbecker/frontend-platform

**Comment by camdencheek** [comment]
Closing as no longer up-to-date since we've switched from monaco to codemirror in the mean time, and codemirror supports tab-driven keyboard navigation by default
