### ISSUE TITLE
insights: menu next to insight dashboard selector is very hard to see in dark mode

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#43209]
The button to open then menu next to the insight dashboard selector is very difficult to see in dark mode.  I only found it existing when testing keyboard navigation.

<img width="528" alt="Screen Shot 2022-10-19 at 6 13 14 PM" src="https://user-images.githubusercontent.com/6098507/196814984-6862dfbe-18d7-49ae-be10-47573d1e7c21.png">

/cc @joelkw @felixfbecker @vovakulikov

**Comment by vovakulikov** [comment]
I was just filling the same thing, thanks for noticing!
