### ISSUE TITLE
Search Aggregation v1 displaying error message on OSS

### ISSUE THREAD

**Issue by jonathanmorley** [sourcegraph/sourcegraph#43203]
### Issue type

Bug fix

### Problem description

When running Sourcegraph OSS (either as a single image server, or as multi image docker compose), searches result in an error message in the right hand bar.

The error message is:

```
Unknown type "SearchAggregationMode".
Variable "$mode" cannot be non-input type %!q().
Cannot query field "searchQueryAggregate" on type "Query".
Unknown type "SearchAggregationMode".
Unknown type "ExhaustiveSearchAggregationResult".
Fragment "SearchAggregationDatum" cannot be spread here as objects of type %!q() can never be of type %!q().
Unknown type "NonExhaustiveSearchAggregationResult".
Fragment "SearchAggregationDatum" cannot be spread here as objects of type %!q() can never be of type %!q().
Unknown type "SearchAggregationNotAvailable".
Fragment "SearchAggregationModeAvailability" cannot be spread here as objects of type %!q() can never be of type %!q().
Unknown type "AggregationModeAvailability".
Unknown type "AggregationGroup".
```

<img width="267" alt="image" src="https://user-images.githubusercontent.com/605837/196810363-92a67f4c-72b3-4f28-99e5-7f29a83c7cca.png">

### Context

I mean OSS, not Free. The sourcegraph/server image does not display this behaviour

### Steps to reproduce

Checkout the `4.0.1` tag

Build an OSS server image with

```
cmd/server/pre-build.sh
cmd/server/build.sh
```

Run it, add some repos to it, run a search

### Assigning labels

- [ ] If this issue will require input from designers in order to complete, please assign the label `needs-design`.

/cc @joelkw @felixfbecker @vovakulikov/frontend-platform

**Comment by jonathanmorley** [comment]
@limitedmage pinging you here because of your investigation on some other OSS-related tickets

**Comment by limitedmage** [comment]
@sourcegraph/code-insights can you take a look at this? This panel should probably not exist in OSS since it looks like the backend is not part of the OSS build.

**Comment by coury-clark** [comment]
@vovakulikov can you give this a rough estimate on how much effort to disable this panel in OSS? I remember there was some complication between linking in enterprise and oss builds, for example

**Comment by limitedmage** [comment]
There is an injected value called `codeInsightsEnabled` that could probably be used for a quick fix.

**Comment by felixfbecker** [comment]
@limitedmage Search Aggregations are separate from Code Insights (doesn't require Code Insights license, separate feature flags) so my hunch is that value would not work

**Comment by limitedmage** [comment]
In that case we probably need a new injected flag to enable/disable aggregations.

**Comment by vovakulikov** [comment]
It should be relatively simple change (I'd say it's 1-2 in our estimation points) I updated estimation fields for this issue. 

> In that case we probably need a new injected flag to enable/disable aggregations.

Agree, but want to highlight that this (boolean/sg version problem) strikes again, this is another good example that our current approach forces us to have a bunch of synthetic and micro boolean flag (but in reality we don't need to have them we just need to inject UI itself between different sg versions.)

**Comment by jensim** [comment]
It looks pretty much the same in 4.3.1 I'm afraid

I left my [OSS release train](https://github.com/jensim/sourcegraph-release-train) running, but forgot to upgrade versions on my local install until today. I was gonna report a bug but @jonathanmorley beat me to it 😄

**Comment by coury-clark** [comment]
@vovakulikov this got moved to done but I don't see a linked PR - was this actually included in 4.3? If not, can we get it in 4.4?

**Comment by vovakulikov** [comment]
@coury-clark Sorry I think I used a wrong link, it was fixed in this PR https://github.com/sourcegraph/sourcegraph/pull/45932 it was included in the 4.3 I believe

**Comment by coury-clark** [comment]
Ah I see, thanks.

@jensim looks like this will go out in 4.4 in the January release. Sorry for the confusion!

**Comment by vovakulikov** [comment]
Oh I forgot that we had early release cut in December, yes it will be part of the 4.4 release
