### ISSUE TITLE
Decorations disappear on Bitbucket when window is resized or sidebar is closed

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#4323]
![2019-06-03 09 43 27](https://user-images.githubusercontent.com/10532611/58784588-143b9e80-85e4-11e9-9b6b-80a21380ae47.gif)

cc @chrismwendt as this could be solved by using the CodeMirror API

**Comment by felixfbecker** [comment]
As an alternative, we would have to use our MutationObserver to also detect removals of decortations (not just entire code views)

**Comment by vdavid** [comment]
We've deprecated extensions, so this is a non-issue. Closing.
