### ISSUE TITLE
Epic: Improve CTAs and sign-up flows across domains

### ISSUE THREAD

**Issue by bretthayes** [sourcegraph/sourcegraph#43239]
## Hypothesis
It's hard for users to sign up for a cloud trial if we're hiding the button from them. Putting the right CTAs in the right spots, and connecting them to sign-up flows that make sense, will drive visitors to sign up. 

## Why this needs grooming
- We need to gather a list of CTAs across our sites so that we can optimize them (and add them where they're missing). WIP [Sheet list of Prominent CTAs](https://docs.google.com/spreadsheets/d/1rktrDwzhdIqnsWPu3Z4ytJ0UmG9wYDNvwKV7NFxkaJU/edit#gid=0)
- We need to know what kind of sign-up flow each of those CTAs is connected to and articulate how they need to be improved. 
- We need to define what success looks like. 
   - We know that we need to see these CTAs increase the number of qualified trials, but by how much?  

## Related context
- [Activation journeys and unified messages to drive growth](https://docs.google.com/document/d/1LfsHVvoMvlyVYdT3BTV275vRdN-h8RUt6U4tlqyhecg/edit#) discussion doc. 
- [See point 3 in slack thread](https://sourcegraph.slack.com/archives/C046X8AG5NY/p1666207440130689)
- [See thread discussion for context](https://sourcegraph.slack.com/archives/C046X8AG5NY/p1666207676903329)
- Today the CTAs are: Login (to /search) → Start trial (Cloud). In an ideal world, there would be more logical CTA routing: Login (To either /search or Cloud) and Sign up (For either /search or Cloud). 

## Issues of this epic
- sourcegraph/about#5875
- #43296
- #43382 
- #43383
- #43405
- #5875
- #5874
- #43672
- https://github.com/sourcegraph/sourcegraph/issues/43750
- https://github.com/sourcegraph/sourcegraph/issues/43752
- https://github.com/sourcegraph/sourcegraph/issues/43754
- https://github.com/sourcegraph/sourcegraph/issues/43917
- https://github.com/sourcegraph/sourcegraph/issues/43989
- https://github.com/sourcegraph/sourcegraph/issues/43955

**Comment by bretthayes** [comment]
Pausing in the mean time while I work on #43253

**Comment by almeidapaulooliveira** [comment]
I loved the sheet list. I'll make a map with all screens so we can have a visual guide in one place. Also, see connections between pages as a flow, design tracking (events), and so on.
