### ISSUE TITLE
Search history iteration and implementation for 4.2

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#43230]
## Problem Statement

In previous explorations into bringing search history back to Sourcegraph after its removal from the search home, we learned that surfacing the history in relation to the search input is generally effective (our original hypothesis in #39817), but presenting it in a search suggestion only on an empty cursor generally falls short of being an effective solution.

We need to iterate on the initial implementation of the search history to build on this to deliver an effective way for users to access and use previous searches as the basis for new searches.

### Problems and constraints

- Only presenting the search history on an empty cursor limits its discoverability.
- CodeMirror, which we use for suggestions, has limitations out of the box that we would have to work around by either forking or building our own plugin from scratch:
  - CodeMirror suggestions cannot be reliably grouped or ordered (e.g. to mix actual suggestions with history suggestions). The order is either determined by how well the suggestion matches the input (if CodeMirror does the filtering) or determined by the order the suggestions source provides them. But mixing filtered and non-filtered sources can yield undesirable results.
  - CodeMirror suggestions cannot have headers or other similar non-actionable elements.
- Search history is relevant wherever the search input appears (home, search results, repo and file views). Solutions should not depend on the page context where they appear, e.g. the search home.
- We have ~2 weeks to design, build, and test a solution that we can ship in 4.2.

## Design process

  - Estimate: Two weeks to one month
  - Weighting factors:
    - Medium risk – Need to ship a GA solution for accessing search history in 4.2. Risk is in not landing an effective GA-ready solution before this (branch cut for 4.2 is November 18).
    - Medium clarity – Previous and existing solutions and directions provide some direction, and previous user testing suggests the search input / moment of conducting a search is an effective place for history to be accessed. Further design exploration will be necessary here.

#### Previous artifacts and efforts for reference
- #42432
- #39817
- [Recent searches panel](https://docs.google.com/document/d/16LmD6IQ-lQUGf9mScX9JfGH11fsv_rE6PxdsdfAFpl8/edit#bookmark=id.k9r3tld8i0ua) from original Server homepage interaction description

### Define
- [x] Github issue & design challenge – #43230

### Design
- [x] Figma file – [Link](https://www.figma.com/file/jkNpzm8s6MTqGmP6RUSaZ8/XXXXX---Search-history-iteration?node-id=0%3A1)
- [x] Low fidelity design – [Excalidraw link](https://app.excalidraw.com/s/4Dr1S6qmmY7/9cXG2Ld2i5B)
- [x] High fidelity design using design system – [Figma link](https://www.figma.com/file/jkNpzm8s6MTqGmP6RUSaZ8/43230---Search-history-iteration?node-id=1754%3A13537)
- [x] Prototype – [Link](https://www.figma.com/proto/jkNpzm8s6MTqGmP6RUSaZ8/43230---Search-history-iteration?page-id=246%3A12&node-id=1722%3A10051&viewport=1991%2C-293%2C0.24&scaling=min-zoom&starting-point-node-id=1722%3A10051)
- [x] Designer review

### Testing
- [ ] Hallway testing – Link
- [ ] Usertesting.com task based evaluation – Link

### Deliver
- [x] Announce in #progress
- [ ] Loom – Link
- [x] Team review
- [x] Design team review
- [ ] QA – Link

### Measure
- [ ] Metrics defined in the Figma file ([i](https://handbook.sourcegraph.com/departments/product-engineering/product/design/metrics/defining-metrics/)) - Link
- [ ] Followup task will analyze metrics to ensure successful completion - Link

---

## Notes for followup
- [x] Mobile adaptation is necessary
- [ ] Implementation will involve updating the "search how to" content on empty search results to include search history

**Comment by limitedmage** [comment]
Hey Quinn, thanks for putting together the loom and design prototype. The overall flow makes sense but I have some comments/questions that I left on the Figma prototype.

**Comment by quinnkeast** [comment]
Initial implementation is underway in #43594.
