### ISSUE TITLE
Code Navigation not working on Sourcegraph OSS

### ISSUE THREAD

**Issue by jonathanmorley** [sourcegraph/sourcegraph#43231]
- **Sourcegraph version:** 4.0.1
- **Platform information:** Amazon Linux 2 ECS Optimized

#### Steps to reproduce:

1. Build an OSS image of sourcegraph/server
2. Run the image
3. Follow the steps under 'Get started with Sourcegraph'
4. Step 3 involves Code Navigation
5. Observe an error of '(intermediate value).__type is undefined' when hovering over any code
6. Observe the following errors when doing 'Find references' on a token

```
Cannot query field "lsif" on type "GitBlob".
Fragment "PreciseCodeIntelForLocationFields" cannot be spread here as objects of type %!q(<nil>) can never be of type %!q(<nil>).
Unknown type "GitBlobLSIFData".
Fragment "LocationConnectionFields" cannot be spread here as objects of type %!q(<nil>) can never be of type "LocationConnection".
Fragment "LocationConnectionFields" cannot be spread here as objects of type %!q(<nil>) can never be of type "LocationConnection".
Fragment "LocationConnectionFields" cannot be spread here as objects of type %!q(<nil>) can never be of type "LocationConnection".
```

#### Expected behavior:

Either the 'Get started with Sourcegraph' steps should be updated to not include mentions of Code Navigation or 'Find References' if they are not supported by OSS Sourcegraph, or

Using Code Navigation and Find References should work on OSS Sourcegraph

#### Actual behavior:

See steps to reproduce

If would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are not [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

**Comment by jonathanmorley** [comment]
<img width="637" alt="image" src="https://user-images.githubusercontent.com/605837/197215723-66e3bc07-03a1-4839-a9cf-1c0dee0449a3.png">

and 

<img width="1117" alt="image" src="https://user-images.githubusercontent.com/605837/197215832-29246eed-217d-4a53-99d2-d8cfe1d918a5.png">

**Comment by jonathanmorley** [comment]
@limitedmage pinging you here because of your investigation on some other OSS-related tickets

**Comment by limitedmage** [comment]
Code Intel is *also* not supported in OSS. @sourcegraph/code-intel or @umpox  can you take a look? 

@jonathanmorley Thank you for reporting all of these. We don't test our OSS build very often, so we end up developing the frontend on assumptions that are not true (eg. code intel available everywhere). We need to do a better job of this so our OSS build is polished and stable.

**Comment by umpox** [comment]
Thanks for raising this @jonathanmorley, I'm looking at this and we'll push out a patch with a fix soon.

**Comment by grrttedwards** [comment]
Any updates on this?

**Comment by fkling** [comment]
We don't have an OSS version anymore, so this is no longer relevant.
