### ISSUE TITLE
Epic: Cleaning up noise below the search bar on dotcom

### ISSUE THREAD

**Issue by st0nebraker** [sourcegraph/sourcegraph#43255]
## Hypothesis
When someone lands on sourcegraph.com/search for the first time, there's a lot of noise that gets in the way of them interacting with the product, and product interaction is what will help them understand the value of Sourcegraph and sign up for a free trial. We need to make sure we're surfacing the most valuable information to them right away. 

![Screen Shot 2022-10-18 at 9 39 24 AM](https://user-images.githubusercontent.com/43555476/197063739-412efe2b-8784-4033-ab0f-33f63bded168.png)

## Why this needs grooming
- We should consider adding example queries that highlight popular open source repos below the search bar (and removing the OSS logos that look more like marketing than a way to search). 

- We should decide which other blocks below the search bar should be removed or updated. 
   -  Design has already done some research around this, and we should leverage their learnings. 
   - Today we have: 
      - Search bar
      - Code search basics, which is also in the sidebar on the search results page
      - Watch and learn video, which is being updated
      - Tips and Tricks
      - About site CTA
      - Open source community logos
      - Self-hosted CTA block (soon to be replaced with Cloud CTA)
      - Customer logos 
 
- We need to define what success looks like.
    - We know that the status quo is bad, and we know that there are probably going to be more searches now than there were last week because we've redirected people to `.com/search` instead of `about`. Is "success" attaching metrics to everything we change here and beginning to understand their relationship to trial sign ups? 
    
[Thread](https://sourcegraph.slack.com/archives/C046X8AG5NY/p1666207440130689)

## Issues of this epic
- #43294
- #43494
- #43570 
- #43572

**Comment by kelsey-brown** [comment]
@st0nebraker I think I'm going to move this from measuring to done. I'm still measuring some of the issues associated to this epic but they've been added to "Measuring" separately, and I think @almeidapaulooliveira's assessment [here](https://sourcegraph.slack.com/archives/C046X8AG5NY/p1668265810510179) wraps up everything else, but let me know if I'm missing something.

Unless I hear different from you guys I'll move this to done at end of day!  ✅
