### ISSUE TITLE
Download and Settings Option Drop Down not working after the first attempt - Safari Only v16.0

### ISSUE THREAD

**Issue by pravasna** [sourcegraph/sourcegraph#43258]
- **Sourcegraph version:** 
- **Platform information:** 
Download and Settings Option Drop Down not working after the first attempt - Safari Only v16.0

#### Steps to reproduce:

1. Open SourceGraph - Click the profile button, it will work for the first time
2. Click on it again and the button will register the click however the drop down menu does not pop up.

Same behavior with the download button (...) to export the search results for a queyry

#### Expected behavior:

This works in Chrome and I want the same behavior in safari as well

**Comment by justdueck** [comment]
Resolved by https://github.com/sourcegraph/sourcegraph/pull/42779
