### ISSUE TITLE
scaletesting: Run batch changes at 2XL scale

### ISSUE THREAD

**Issue by Piszmog** [sourcegraph/sourcegraph#43252]
Ticket for tracking all work associated with performing batch changes at 2XL scale.

## Done

- Execute all testing scenarios (doc below)
- Create Issues for any problems found
- Close all opened Issues.

## Related Docs

- [Strategic-ready Batch Changes](https://docs.google.com/document/d/1vXAnhui-AGBk2aar4pXt-uTuTIQfZU5LFFtrMAU2e4s)
- [Batch changes scenarios](https://docs.google.com/document/d/1oTfTw4delRt58sDc6T0jKWRsRIpXbzxYHORjXNsoqEY)

## Other Helpful Stuff

* Python (python 3) script to automate creating large changesets (with not much waiting)
    * [script.zip](https://github.com/sourcegraph/sourcegraph/files/10377145/script.zip)
    * Example command. - `python run.py -s ./ghe-125k.yml -u https://sourcegraph.test:3443 -t <Token>`
* Batch Spec + external services JSON
    *  [scaletesting-env.zip](https://github.com/sourcegraph/sourcegraph/files/10377179/scaletesting-env.zip)

## Related Issues

- [x]  #40923
- [x] #16562
- [x] #42655
- [x] #44502
- [ ] #44503
- [x] #44504
- [ ] #44505
- [ ] #44506
- [ ] #44507
- [ ] #44508
- [ ] #44510
- [ ] #44511
- [ ] #44512
- [ ] #44527

### Discovered Issues

- [ ] #44920 
- [x] #44678
- [ ] #44953

**Comment by Piszmog** [comment]
Attached the python script I used to automate creating large changesets (within a reasonable amount of time) and the external-service.json I used (takes ~12+ hrs for my local instance to clone everything and index the code)

**Comment by courier-new** [comment]
Moving the tracking issue on this back to the backlog since the remaining work for this has been deprioritized until after Starship in March.
