### ISSUE TITLE
Auto-indexing executor fails setup at git checkout on repository with LFS enabled

### ISSUE THREAD

**Issue by jpalpant** [sourcegraph/sourcegraph#43277]
I have recently deployed Sourcegraph (Free version) on Kubernetes using Helm, following the guidance in the docs, and everything has been going great. Sourcegraph is functioning and connected to my personal GitLab deployment.

I decided to attempt to set up auto-indexing, and have deployed an executor to a spare Linux machine I have on hand using the instructions for systemd. I have disabled Firecracker in this instance.

For any repository with LFS files, the executor fails in the Setup stage, as it fails to smudge any git LFS objects.

```
Downloading samples/grafana.txt (784 B)
Error downloading object: samples/grafana.txt (53e7181): Smudge error: Error downloading samples/grafana.txt (53e7181bdb74cdddbcb434775ddde3d4367e3c14ccdeeb80874923b6c4f4f2f3): batch response: Authorization error: http://127.0.0.1:35719/gitlab.palpant.us/justin/chromedp-load-agent.git/info/lfs/objects/batch
Check that you have proper access to the repository
Errors logged to /tmp/workspace-3-3746157955/.git/lfs/logs/20221020T142511.182195749.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: samples/grafana.txt: smudge filter lfs failed
```

![image](https://user-images.githubusercontent.com/9629191/197124972-fd535c43-8467-40f1-ab8c-a7bbcd13d5d6.png)

The [repository in this instance](https://gitlab.palpant.us/justin/chromedp-load-agent) is public.

I think likely the LFS objects aren't necessary for auto-indexing in my case - is it possible to set GIT_LFS_SKIP_SMUDGE=1 in some way to get past this? It would also be a convenient way to speed up code checkout where applicable.

At the same time, I'm sure many repositories do need LFS files for auto-indexing. Is it possible to support LFS smudge from private Gitlab repositories? Is this misconfiguration of my setup, or a true issue?

**Comment by eseliger** [comment]
Hi! Thanks for the report :) Sourcegraph currently doesn't support LFS so executors don't really either, _but_ that shouldn't mean that they shouldn't be able to index regardless. So.. I just tried this locally and it seems to work fine when git-lfs is not installed on that machine. Can you give that a try as a temporary workaround?

**Comment by jpalpant** [comment]
Good to know, and that makes sense! Yes, I can give that a try. 

If that's the case and Sourcegraph would like to skip on LFS in all cases, what you think about adding a hard `GIT_LFS_SKIP_SMUDGE=1` to all checkouts on the executor? It looks like there's `GIT_TERMINAL_PROMPT=0` [here](https://github.com/sourcegraph/sourcegraph/blob/192655059f757e0ebaa519961f8c7385ed53fad1/enterprise/cmd/executor/internal/worker/workspace/clone.go#L22) already, for similar ("make it work without git being difficult") reasons.

**Comment by eseliger** [comment]
Yep that makes sense to me :) Just wanted to give you a quick option to get around this issue!

**Comment by jpalpant** [comment]
Sadly, just hard-removing git-lfs (`apt remove git-lfs`) from the machine didn't convince git not to try:

```
git-lfs filter-process: 1: git-lfs: not found
fatal: the remote end hung up unexpectedly
```

That was surprising, because when I clone the repo on a machine without git-lfs it does what you would expect, and goes ahead happily.

But I forgot `git-lfs` is persistent; you have to first, before uninstalling the package, run `git lfs uninstall`, and _then_ remove the package. And in case that wasn't odd enough, it seems like it was important to run `git lfs uninstall` as the same user that the systemd job is attached to (root, in my case) - just running it as my user did nothing.

But then: perfect. 
<img width="949" alt="Screen Shot 2022-10-21 at 12 27 06 PM" src="https://user-images.githubusercontent.com/9629191/197274447-c0f1d6d3-324f-4f5b-904d-08044ee72020.png">

I'm happy to consider this closed, but if you'd like to keep it open to reference for adding GIT_LFS_SKIP_SMUDGE, I'll leave it open. I'd also be happy to put up a diff but it might take me til later today (CLA, etc.).

**Comment by eseliger** [comment]
Yeah totally, I'll add it this week and close this ticket out after :) Thanks for reporting and debugging with me!

**Comment by eseliger** [comment]
Closed in https://github.com/sourcegraph/sourcegraph/pull/43701
