### ISSUE TITLE
Create nurture campaigns for .com users

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#43271]
### Problem description

People who have signed up on `.com` might not realize that they need to self-host or start a Cloud trial in order to use Sourcegraph on private code. 

### Context

[We deactivated all dotcom email campaigns when we sunset dotcom in August. ](https://sourcegraph.slack.com/archives/C03B4EMBXL4/p1666240855222869) We should create a new one that mentions and encourages a cloud trial. 

[Related thread. ](https://sourcegraph.slack.com/archives/C03B4EMBXL4/p1666240855222869)

### User journey stage

Consideration

### Impact

High

### Effort

3 hours

### Success criteria

It would be great if we could check the email addresses of people who signed up for a cloud trial against the list of people who receive the nurture email, but there's probably some fuzziness there (they might have gotten the email at their personal address, someone else on their team might be the one who signs up for the trial, etc). At the very least, we need to determine what a meaningful bump in cloud trial signups would look like after the email goes out. 

### Assigning labels

- [ ] If this issue will require input from designers in order to complete, please assign the label `needs-design`.

**Comment by sqs** [comment]
I thought we were already sending nurture emails out to dotcom signups, but we actually aren't. Given that, I don't think that starting to do so is higher priority than making it clearer in the product that you need to do Cloud or self-hosted for private code.
