### ISSUE TITLE
Compute VM Images have low limits and are preventing the docker-executor-mirror to be recreated

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#43282]
Ported from: https://sourcegraph.slack.com/archives/C01N83PS4TU/p1666342052484089

@unknwon got the following: 

```
Updated [https://compute.googleapis.com/compute/v1/projects/sourcegraph-ci/global/images/sourcegraph-executors-docker-mirror-4-1-179156].
An error occurred (ResourceLimitExceeded) when calling the ModifyImageAttribute operation: You have reached your quota of 204 for the number of public images allowed in this Region. Deregister unused public images or make them private, or request an increase in your public AMIs quota.
```

We took a look with @burmudar at [this list of images](https://console.cloud.google.com/compute/images?tab=images&project=sourcegraph-ci&pageState=(%22images%22:(%22f%22:%22%255B%257B_22k_22_3A_22_22_2C_22t_22_3A10_2C_22v_22_3A_22_5C_22executor_5C_22_22%257D_2C%257B_22k_22_3A_22_22_2C_22t_22_3A10_2C_22v_22_3A_22_5C_22docker-mirror_5C_22_22%257D%255D%22,%22s%22:%5B(%22i%22:%22creationTimestamp%22,%22s%22:%220%22),(%22i%22:%22type%22,%22s%22:%220%22),(%22i%22:%22name%22,%22s%22:%220%22)%5D))) and found out that we had even images from 2021 in there. 

We deleted 21 of them, which should unblock @unknwon but we should find a better long term solution to handle this.

**Comment by eseliger** [comment]
Turns out this was AWS not google rate limiting us.

**Comment by jhchabran** [comment]
Ok! Thanks for the update.

**Comment by eseliger** [comment]
This is probably still going to be a problem in the next release, should we increase massive quota increases at AWS?
