### ISSUE TITLE
Search Contexts not working on Sourcegraph OSS

### ISSUE THREAD

**Issue by jonathanmorley** [sourcegraph/sourcegraph#43299]
- **Sourcegraph version:** 4.0.1 OSS
- **Platform information:** Amazon Linux 2 ECS Optimized

#### Steps to reproduce:

1. Build and run an OSS sourcegraph server image

#### Expected behavior:

Search contexts should be available to create and choose from

#### Actual behavior:

No search contexts are configurable, the dropdown under the Code Search tab is empty

<img width="425" alt="image" src="https://user-images.githubusercontent.com/605837/197215539-4be4287c-a2c6-4cf5-bb24-7297dd86d0d9.png">

If would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are not [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

/cc @lguychard

**Comment by coury-clark** [comment]
Thanks for the report! Pinging some more relevant folks

cc @sourcegraph/search-product

**Comment by limitedmage** [comment]
Hey @jonathanmorley , what process are you following to build and run the OSS image?

**Comment by limitedmage** [comment]
@jonathanmorley OK I've figured it out. This is happening because search contexts are not under the open source license and thus are not available in the open source build. The menu being present is a bug. I'll try to fix it to avoid confusion.
