### ISSUE TITLE
Notebooks not working in Sourcegraph OSS

### ISSUE THREAD

**Issue by jonathanmorley** [sourcegraph/sourcegraph#43300]
- **Sourcegraph version:** 4.0.1 OSS
- **Platform information:** Amazon Linux 2 ECS Optimized

#### Steps to reproduce:

1. Build and run a sourcegraph server OSS image
2. Click the Notebooks tab

#### Expected behavior:
Either:
  Able to create notebooks
Or:
  The Notebooks tab is not available (because its not an OSS feature)

#### Actual behavior:

Error message:
```
Unknown type "NotebooksOrderBy".Variable "$orderBy" cannot be non-input type %!q().Cannot query field "notebooks" on type "Query".Fragment "NotebookFields" cannot be spread here as objects of type %!q() can never be of type %!q().Unknown type "Notebook".Unknown type "MarkdownBlock".Unknown type "QueryBlock".Unknown type "FileBlock".Unknown type "SymbolBlock".Unknown type "ComputeBlock".
```
is raised

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/605837/197216361-e9b9ccb5-89b0-4e26-9ba2-7feee3603ba8.png">

If would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are not [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

/cc @lguychard

**Comment by coury-clark** [comment]
Thanks for the report! Pinging some more relevant folks

cc @sourcegraph/search-product

**Comment by limitedmage** [comment]
Notebooks are not supported in OSS, except for viewing `.snb.md` files in repos. These pages will be removed from the OSS.
