### ISSUE TITLE
Fuzzy finder: followup items

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#43315]
- https://github.com/sourcegraph/sourcegraph/pull/42825
- Use `TabList` and `TabPanel` wildcard components https://github.com/sourcegraph/sourcegraph/pull/43225#discussion_r1002033207

/cc @felixfbecker

**Comment by felixfbecker** [comment]
Are these still outstanding?

**Comment by olafurpg** [comment]
Closing as fixed
