### ISSUE TITLE
updates to externalURL are not reflected in CSRF middleware

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#4332]
The following violate the constraint that `conf` users respond to configuration changes appropriately:

1. ~The session store cannot handle the URL changing from HTTP -> HTTPS or vice-versa:~

https://sourcegraph.com/github.com/sourcegraph/sourcegraph@ac24a24cf91b9fe29b69cf14619787b833f5cd3a/-/blob/cmd/frontend/internal/app/app.go#L25:18

2. The CSRF middleware also has the same issue:

https://sourcegraph.com/github.com/sourcegraph/sourcegraph@ac24a24cf91b9fe29b69cf14619787b833f5cd3a/-/blob/cmd/frontend/internal/cli/http.go#L48:18

In both cases, the site admin would just need to restart the frontend. This is a documented known bug, so it's not the end of the world: https://docs.sourcegraph.com/admin/config/critical_config#known-bugs

**Comment by slimsag** [comment]
I am wrong about the first one, I see @tsenart actually added a wrapping session store that handles it.

**Comment by slimsag** [comment]
The CSRF middleware remains an issue. The reason for this is because `CSRFMIddleware` is only being called once to generate the handler, so even though the return value of `secure()` changes it doesn't matter because the parent function is only called once.

https://sourcegraph.com/github.com/sourcegraph/sourcegraph@ac24a24cf91b9fe29b69cf14619787b833f5cd3a/-/blob/cmd/frontend/internal/pkg/handlerutil/middleware.go#L20

@tsenart seems like your PR was actually trying to address all of this, so maybe you will want to fix this and remove the documented bug from https://docs.sourcegraph.com/admin/config/critical_config#known-bugs

**Comment by tsenart** [comment]
> The CSRF middleware remains an issue. The reason for this is because CSRFMIddleware is only being called once to generate the handler, so even though the return value of secure() changes it doesn't matter because the parent function is only called once.

Damn it. I completely missed that, thinking it was a handler getting called on every request. I'll follow up with a fix now and will update the docs on known bugs. Thanks!
