### ISSUE TITLE
batches: Document that experimental containerd pulling doesn't work

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#43346]
When the flag for experimental containerd based pulling of images is enabled in Docker for Mac, src-cli stops working. That is, because the output of docker image inspect slightly changed. 
We want to add a notice to our docs to warn users so they don't run into this and are lost.

**Comment by chrispine** [comment]
P0 or P1 (which means adding it to the docsathon)

**Comment by LawnGnome** [comment]
P0; 0.5d.

**Comment by eseliger** [comment]
Fixed upstream, we decided that this is enough of an edge-case that we shouldn't put too much effort into this
