### ISSUE TITLE
insights: remove code_insights_deprecate_jit feature flag

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#43374]
The feature flag to toggle between just in time insights and scoped backfilled insight still exists in code `code_insights_deprecate_jit`.  This has been defaulted `true` since v3.42.  Removing this feature flag will simplify the code around insight creation.

**Comment by chwarwick** [comment]
p1

**Comment by coury-clark** [comment]
We need to construct an OOB migration to ensure all customers are migrated if they are using the new migrator tool. This isn't as simple as removing a flag + code related. I'd say p2

**Comment by chwarwick** [comment]
duplicated by https://github.com/sourcegraph/sourcegraph/issues/43379
