### ISSUE TITLE
insights: remove and deprecate just-in-time feature flag

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#43379]
We should deprecate the just-in-time feature flag and eventually remove the just-in-time code paths. This will probably require an OOB migration to permanently deprecate the JIT migration.

/cc @joelkw @felixfbecker @vovakulikov

**Comment by coury-clark** [comment]
p2

**Comment by coury-clark** [comment]
might be deprecated by https://github.com/sourcegraph/sourcegraph/issues/43565

**Comment by chwarwick** [comment]
Partially handled by https://github.com/sourcegraph/sourcegraph/issues/43565.  The code for JIT can be removed when the OOB migration is retired in https://github.com/sourcegraph/sourcegraph/issues/45275
