### ISSUE TITLE
ci: add bundle size github token

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#4339]
See https://buildkite.com/sourcegraph/sourcegraph/builds/36759#ac6dcac6-041a-413b-ad63-0b9304236d91

![Screen Shot 2019-06-03 at 2 42 57 PM](https://user-images.githubusercontent.com/9022011/58836536-e66b4f80-860d-11e9-9534-71cb259f7890.png)

That page links to: https://github.com/siddharthkp/bundlesize#2-build-status

Apparently we can see the diff in bundle size as a GH PR check: 

![Screen Shot 2019-06-03 at 2 43 59 PM](https://user-images.githubusercontent.com/9022011/58836605-0dc21c80-860e-11e9-816a-f9aac1c1d315.png)

cc @sourcegraph/code-nav 

@felixfbecker feel free to re-assign this, I just thought that you'd know who to hand this off to

**Comment by felixfbecker** [comment]
We intentionally unset the GitHub token because bundlesize sends commit messages to a public service. I guess now that everything is open source that doesn't matter anymore.

https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/ci/yarn-build.sh#L21:15

**Comment by felixfbecker** [comment]
Bundle size is broken and unmaintained unfortunately.
