### ISSUE TITLE
Theme should be set in settings (not localStorage)

### ISSUE THREAD

**Issue by francisschmaltz** [sourcegraph/sourcegraph#434]
The user's theme should be set in user settings and follow the user on any device they sign into. Currently it is set in localStorage; this means it defaults to the light theme on a user's other devices and there is no way for a site admin to set the default dark theme globally.

CC: @yevbar

**Comment by yevbar** [comment]
I've only used Sourcegraph locally (via docker) and know there's a way to set up an admin account that way (which I presume would be on an accessible IP for a team). Would the solution for this be along the lines of having a universal Sourcegraph account?

**Comment by francisschmaltz** [comment]
The theme would be part of your user’s configuration file. This would be unique to the instance

**Comment by yevbar** [comment]
Oh so somewhere in the `.sourcegraph` directory?

**Comment by sqs** [comment]
No, in your Sourcegraph user account’s settings at the /users/$USER/settings URL path on your instance.

**Comment by sqs** [comment]
I updated the description of what to do in the top comment to simplify it. One consequence is that users would need to sign in to be able to change the theme, but this is acceptable (and in fact desirable for simplicity).

**Comment by felixfbecker** [comment]
Idk, I actually think you might _want_ this to be per-device. See also YouTube:

![image](https://user-images.githubusercontent.com/10532611/58385820-a517e600-7ff6-11e9-97b0-2d1d0f60c83b.png)

**Comment by felixfbecker** [comment]
I'm closing this because with the prevalence of reacting to the OS theme dark theme fits best as a client setting.
