### ISSUE TITLE
UX: Improve CTAs and sign-up flows across domains

### ISSUE THREAD

**Issue by almeidapaulooliveira** [sourcegraph/sourcegraph#43405]
### This is a design issue of this Epic:
- #43239

## Define
We need to map and understand different users' journeys in discovering Sourcegraph and how we can better communicate and convey value.

We need consistency in our communication and drive users to convert. Chaining pages and talking with them through the journey. If the user starts on page A and moves to B. The message should follow him, convincing him and avoiding bouncing. 

Also, important to communicate our purpose, our promise, our pillars, and our copywriting style. 

### Related work:
- #43296 

## Design
- [x] [Map: Journeys and paths for sign-ups.](https://www.figma.com/file/x7JkAkHQZXIhyDVuhErIZz/Journeys-and-paths-for-sign-ups-map?node-id=1%3A54)
- [x] Activation journeys [(Figma file)](https://www.figma.com/file/x7JkAkHQZXIhyDVuhErIZz/Map%3A-Journeys-and-paths-for-sign-ups?node-id=123%3A420)
- [x] [Activation journeys and unified messages to drive growth](https://docs.google.com/document/d/1LfsHVvoMvlyVYdT3BTV275vRdN-h8RUt6U4tlqyhecg/edit#heading=h.2fxktdtfwdir)

## Related issues:
- #43672 

## Design process (Size: S)

- Estimate: three days
- Weighting factors:
  - LOW risk
  - MEDIUM clarity

**Comment by taylorsperry** [comment]
Changed the title so that, on our project board, it's easier to see that this is tied to the corresponding epic.
