### ISSUE TITLE
4.1.1 patch release request

### ISSUE THREAD

**Issue by LawnGnome** [sourcegraph/sourcegraph#43412]
@sourcegraph/release-guild I am requesting the following commits be included in a patch release. They are already merged into `main`:

- 881a4c23906a3e60f7bcecbd3ee55932cf4fff93

As discussed on Slack, we don't believe this merits an immediate patch release, but we would like this to ride along if a patch release is requested for a higher priority issue.

---

The intent of the questions below is to ensure we keep Sourcegraph high quality and [only create patch releases based on a strict criteria.](https://handbook.sourcegraph.com/engineering/releases#patch-releases) If you can answer yes to many or most of these questions, we will be happy to create the patch release.

I have read [when and why we perform patch releases](https://handbook.sourcegraph.com/engineering/releases#patch-releases) and answer the questions as follows:

> Are users/customers actively asking us for these changes and cannot wait until the next full release?

Yes; please see [this Slack thread](https://sourcegraph.slack.com/archives/CMMTWQQ49/p1666636538241929).

> Are the changes extremely minimal, well-tested, and low risk such that not testing as we do in a full release is OK?

Yes; this adds a single `UPDATE` statement to a migration added in 4.1.0.

> Is there some functionality completely broken that warrants redacting the prior release of Sourcegraph and advising users wait for the patch release?

This prevents users from migrating to 4.1 if they have changesets in the `draft` changeset without JSON encoding, which we previously didn't believe was possible, but has now occurred for one customer as noted above.

> This will interrupt our regular planned work and release cycle, taking one full working day of our time, and will take up all of our site admin's valuable time by asking them to upgrade or producing noise for them if they don't need to upgrade.
>
> Do you believe the changes are important enough to warrant this?

Sort of. (See above about not requesting an immediate patch release.)

> Patch releases are a signal we can do something better to improve the quality of Sourcegraph. Have you already scheduled a call (or created a google doc) to perform a [retrospective](https://about.sourcegraph.com/retrospectives) and identify ways we can improve?

We will discuss this in our next team retro, and have informally discussed this at our offsite this week already.

---

**For the [Release Captain]** - after reviewing this request:

- [x] **Comment on this issue** with a decision regarding the request.
- [x] If you are a first-time [Release Captain], please review the high-level overview of the [patch release process].
- [ ] If approved, **add it to a patch release**:
  - If there is [already an upcoming patch release](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+), add the listed commits alongside a link to this issue.
  - If there is no upcoming patch release, create a new one:
    - [x] Update [`dev/release/release-config.jsonc`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/release/release-config.jsonc), open and merge a PR to `main` to update it.
      - [x] Change `upcomingRelease` to the current patch release
      - [x] Change `previousRelease` to the previous patch release version
      - [x] Change `releaseDate` to the current date (time is optional) along with `oneWorkingDayAfterRelease` and `threeWorkingDaysBeforeRelease`
      - [x] Change `captainSlackUsername` and `captainGitHubUsername` to the patch captain's
    - [ ] Run `yarn release tracking:issues` on `main`
    - [ ] Add the listed commits alongside a link to this issue to the generated [release tracking issue](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+)
- [ ] **Comment and close this issue once the relevant commit(s) have been cherry-picked into the release branch**.

[release captain]: https://handbook.sourcegraph.com/engineering/releases#release-captain
[patch release process]: https://handbook.sourcegraph.com/departments/product-engineering/engineering/process/releases#patch-release-process

**Comment by BolajiOlajide** [comment]
I'll be cutting a patch release for this. cc @sourcegraph/release-guild

**Comment by BolajiOlajide** [comment]
4.1.1 is out.
