### ISSUE TITLE
Bug: Bulk revote/promte site-admin access not working 

### ISSUE THREAD

**Issue by Rhia2** [sourcegraph/sourcegraph#43411]
- **Sourcegraph version:** 4.0.1 and later
- **Platform information:** Kubernetes

#### Steps to reproduce:

1. From User administration page, select multiple users by checking the check box by the username
2. click on Promote/revoke to site admin button from the bottom dropdown

#### Expected behavior:
It's expected to revoke or promote all users selected 

#### Actual behavior:
Promotes or revokes just one the users selected.

/cc @sourcegraph/iam/frontend-platform

**Comment by kopancek** [comment]
I think this is not a bug. From my point of view, the screenshot clearly shows that bulk actions are only available on the top:
<img width="916" alt="Screenshot 2022-10-26 at 14 02 18" src="https://user-images.githubusercontent.com/9974711/198021137-c1a23d6c-6b6c-447d-ae6e-e8e122f631bb.png">

We could disable the three dots menu when multiple users are selected, which would fix the bug of being able to run an action on a single user when multiple are selected, but that would not solve the problem of the customer.

If they really want to be able to promote multiple people as site-admin (or revoke), we need to support it in the multi-action dropdown. Which IMO is a feature request, not a bug. @Rhia2 should I reclassify this problem as a feature request?

**Comment by Rhia2** [comment]
@kopancek, thank you for looking into this.
They were not using the action from ..., there is a bottom dropdown with the action revoke site-admin. One would assume that this is for bulk action, and if this is not meant to be for bulk action, it would be best to remove the link from the dropdown for User experience.

<img width="924" alt="image" src="https://user-images.githubusercontent.com/32063636/198236217-4dd70f46-ba65-4e01-af1d-2a49a41e5e1a.png">
