### ISSUE TITLE
repository syncing logic is causing Perforce repos to be continuously renamed on dogfood

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#43426]
- **Sourcegraph version:**: k8s.sgdev.org
- **Platform information:**: version of sourcegraph running at this commit: https://github.com/sourcegraph/deploy-sourcegraph-dogfood-k8s/commit/bb1623afe917913668ff9872c5a5bb3f81888bf6

On k8s.sgdev.org, there seems to be a bug in the repository syncing logic. Two repositories are being continuously renamed (specifically, flip flopping between the `perforce` and `perforce-fusion` prefixes):
1. perforce/test-perms <->  perforce-fusion/test-perms
2. perforce/test-large-depot <->  perforce-fusion/test-large-depot

#### Steps to reproduce:

1. Take a look at [recent logs](https://sourcegraph.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22builder%22,%22expr%22:%22%7Bnamespace%3D%5C%22dogfood-k8s%5C%22,%20app%3D%5C%22indexed-search%5C%22,%20container%3D%5C%22zoekt-indexserver%5C%22,%20pod%3D%5C%22indexed-search-1%5C%22%7D%20%7C%3D%20%60removing%20shards%20for%60%22,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%221666681200000%22,%22to%22:%221666710000000%22%7D%7D) from one of the zoekt-indexserver instances running k8s.sgdev.org. You'll see a lot of messages that look like: 

```
"2022-10-25T14:58:47.440156645Z stderr F 2022/10/25 14:58:47 removing shards for 432 due to multiple repository names: perforce%2Ftest-perms_v16.00000.zoekt perforce-fusion%2Ftest-perms_v16.00000.zoekt"
"2022-10-25T14:58:47.439597522Z stderr F 2022/10/25 14:58:47 removing shards for 430 due to multiple repository names: perforce%2Ftest-large-depot_v16.00000.zoekt perforce-fusion%2Ftest-large-depot_v16.00000.zoekt"
"2022-10-25T14:54:00.169997661Z stderr F 2022/10/25 14:54:00 removing shards for 430 due to multiple repository names: perforce%2Ftest-large-depot_v16.00000.zoekt perforce-fusion%2Ftest-large-depot_v16.00000.zoekt"
```

2. The "test-perms" and "test-large-depot" are both specified  in two different Perforce code host configurations:
	- "Perforce fusion": https://k8s.sgdev.org/site-admin/external-services/RXh0ZXJuYWxTZXJ2aWNlOjQ4
	- "Perforce": https://k8s.sgdev.org/site-admin/external-services/RXh0ZXJuYWxTZXJ2aWNlOjIx

4. The log from zoekt comes from this log line (which is only emitted if a repository is being renamed) https://github.com/sourcegraph/zoekt/blob/0ec03e4b8885824a093a10440af53dbcad041263/cmd/zoekt-sourcegraph-indexserver/cleanup.go#L76-L96 

#### Consequences 

These renames means that zoekt is spending a lot of time re-cloning and re-indexing repositories that haven't changed. However, I believe the fundamental error lives in the **repository syncer**. 

If the same repository is specified across multiple code hosts, we should be picking a "winning" code host in some way (sorting on the code host name, newest code host wins, etc.)

/cc @sourcegraph/iam

**Comment by ryanslade** [comment]
You're correct in that this is being caused by two code host connections with `repositoryPathPatterns` that are renaming the same repo. Each code host connection is synced independently and so as each one is synced the repo is renamed.

I think this is an edge case we should not support and our docs even mention this, for example:

> If different code hosts generate repository names that collide, Sourcegraph's behavior is undefined.
 
https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/schema/schema.go?L32

I've "fixed" this on dogfood for now by only having one code host connection. We could also get around it by ensuring that two connections don't rename the same repo.

The reason I took the nuclear option and removed one the connection is to deal with [another issue](https://github.com/sourcegraph/sourcegraph/issues/44096) that needs to be solved.
