### ISSUE TITLE
FE scale audit: Batch changes: Workspace preview takes long to compute

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#43420]
When previewing the affected repos for a batch changes, the query takes a long time. What is noticeable is that it takes longer than the same query inside the search box. 

Can be repro'd on the scale testing instance with this query:

<img width="1051" alt="Screenshot 2022-10-25 at 16 27 43" src="https://user-images.githubusercontent.com/458591/197801114-425d1522-ef4d-4e6c-a228-ea5449cec681.png">

Once the query completes, the UI is fast and only shows 100 entries:

<img width="508" alt="Screenshot 2022-10-25 at 16 29 03" src="https://user-images.githubusercontent.com/458591/197801471-48a4846e-0fc3-4146-badb-2722ba5ca6fb.png">

**Comment by courier-new** [comment]
We discussed ideas for this today as a team and have come up with several different ways to approach this and incremental improvements to make both to the UX, for perceived performance, and on the backend, for actual performance. I've created several individual tickets to reflect these ideas but will also keep this one around to track the overall effort.

**Comment by eseliger** [comment]
strategic-ready/high - sounds like backlog? Maybe we could prioritize the design work in the next ~2 sprints after the sustaining sprint so maybe p2-ish for the design ticket?

**Comment by courier-new** [comment]
We have another set of labels to worry about now that came from the frontend scale audit. The one that's relevant here is `scale-audit/must-have`. I'll change our label to `strategic-ready/very-high`. 😅

This issue itself is more of a tracking issue for the 4 more specific issues that are linked to it (that aren't visible from the issue preview overlay UI thing 🙄). We have been asked to complete _something_ here to improve the workspaces preview for strategic readiness before 4.4 in January, though, so this needs to be P2.

**Comment by eseliger** [comment]
before = needs to land in 4.4 or needs to land before 4.4 so 4.3?

**Comment by courier-new** [comment]
Ah sorry, I should have said _by_ 4.4, so in 4.4 would be fine. 🙂

**Comment by courier-new** [comment]
Backlogging this for now; it's been deprioritized in favor of other strategic work with direct, higher customer impact.
