### ISSUE TITLE
Blob keyboard navigation: Add tracking metrics

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#43431]
## Description

We should add tracking metrics whenever a user uses the blob keyboard navigation. This will help us work out if users are actually discovering this, or if we should tweak it in any way.

AC:
- Fire event on keyboard navigation trigger (e.g. `Enter` to open references panel or go to definition)
- Other metrics?

/cc @felixfbecker/frontend-platform

**Comment by camdencheek** [comment]
Closing since we will evaluate metrics as part of the ongoing designs of the blob view
