### ISSUE TITLE
GCP Marketplace

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#43438]
Notes:
- https://cloud.google.com/marketplace/docs/partners/get-started#requirements
- https://cloud.google.com/marketplace/docs/partners/vm

Checklist from official docs:

At a high level, you must do the following:
- [ ] [Set up your Google Cloud environment](https://cloud.google.com/marketplace/docs/partners/vm/set-up-environment) so that you can distribute and display your product on Google Cloud Marketplace.
- [ ] [Review the pricing options, and select a pricing model](https://cloud.google.com/marketplace/docs/partners/vm/select-pricing). We recommend deciding on a pricing model and submitting it for processing before proceeding with the next steps. Pricing models might take up to two weeks to process. You can continue setting up your VM product while the pricing model is being processed.
- [ ] [Build your VM image](https://cloud.google.com/marketplace/docs/partners/vm/build-vm-image).
- [ ] [Create your deployment package](https://cloud.google.com/marketplace/docs/partners/vm/create-deployment-package).
- [ ] [Test your product](https://cloud.google.com/marketplace/docs/partners/vm/test-product) end-to-end.
- [ ] [Submit your product to Cloud Marketplace](https://cloud.google.com/marketplace/docs/partners/vm/submitting). To publish your product, you submit various parts of your product for review. The Partner Engineering team reviews each submission and works with you to resolve any issues before approving it. After all reviews are approved, you can publish and launch the product within a few minutes.
- [ ] [Maintain and monitor your product](https://cloud.google.com/marketplace/docs/partners/monitor-analytics) after it has launched.

**Comment by beyang** [comment]
Is this done?
