### ISSUE TITLE
FE scale audit: Auto-index configs crash on large repos

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#43449]
As part of the [FE scale audit](https://docs.google.com/spreadsheets/d/1tqpi22csQJNlk7Q9JFWcFj09VbWOiFdp-Vf18qJsWHc/edit#gid=0), we noticed that auto-index configs inside the repo page are crashing and becoming unable to use on larger repos:

```
Error fetching index configuration: Inference limit: requested content for more than 100 (100) files
```

This can be reproduced on dotcom, e.g. on the VS Code repo: https://sourcegraph.com/github.com/microsoft/vscode/-/code-graph/index-configuration

Here is a screenshot of the issue: https://www.figma.com/file/SiFt7KlbjUwSMXPfsXXdew/Strategic-readiness---design?node-id=135%3A5

**Comment by varungandhi-src** [comment]
Dupe of https://github.com/sourcegraph/sourcegraph/issues/42452?

**Comment by philipp-spiess** [comment]
@varungandhi-src Yeah, thanks. I'll merge.
