### ISSUE TITLE
RFE: Detect corrupt repositories and show log events in the UI 

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#43445]
**Requested by:** https://github.com/sourcegraph/accounts/issues/6716 via [Slack](https://sourcegraph.slack.com/archives/D01GNUPH28M/p1666706405543149)

#### Feature request description

Have a process that looks for and marks repositories as corrupt.  On the initial detection, output log events when a corrupt repo is found.   Also on the repository status list page:

* Show a "repository is corrupt" indicator 
* Show the log messages captured about the corrupt repo

Finally, add a metric and graph in Grafana of the number of corrupt repositories found.

#### Is your feature request related to a problem? If so, please describe.

https://github.com/sourcegraph/accounts/issues/6716 [found](https://sourcegraph.slack.com/archives/C01D50MSA7L/p1665579735335619) a corrupt repository weeks after it was initially corrupt.  Initially, it looked like the repository was corrupt after an upgrade.  But, after digging through the logs, we discovered it actually became corrupt weeks before the upgrade.

/cc @jplahn @ryphil

**Comment by mrnugget** [comment]
Fixed by @burmudar in https://github.com/sourcegraph/sourcegraph/pull/46415 et al.
