### ISSUE TITLE
Export batch change PR URLs

### ISSUE THREAD

**Issue by christinelovett** [sourcegraph/sourcegraph#43454]
#### Feature request description

[Customer](https://github.com/sourcegraph/accounts/issues/560) noted Batch Changes would be more useful if we provided all PR URLs which are `open` in a given batch change.  This would make it easier for them to share the PRs with their team for approval. 

#### Is your feature request related to a problem? If so, please describe.

After opening PRs, it's necessary to receive approvals before changes can be merged. Because we do not currently support tagging or assigning through Batch Changes, they had to manually aggregate the open PRs. 

#### Describe alternatives you've considered.

The user followed these steps:

- Open each PR in a new tab
- Bookmark all tabs into a new folder
- Copy from bookmarks manager

The user also considered using the web developer mode to inspect elements and extract that way. 

CE suggested grabbing the URLs through the Sourcegraph API as well, but it is still not a frictionless workaround. 

#### Additional context

User suggested design:

> It would be nice if there was a copy all PRs, or an API, which would dump all PRs (maybe with filters like, open, closed etc )

Similar to `Search Export` functionality but for Batch Changes

**Comment by chrispine** [comment]
Would #39255 meet these customers needs?

**Comment by malomarrec** [comment]
https://github.com/sourcegraph/sourcegraph/issues/39255 duplicates this.
I'm closing this, but this is a great ticket we'll refer to in the future when we prioritise it.
