### ISSUE TITLE
Delivery: Investigate viability of switching to statefulsets for searcher + symbols services

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#43493]
ref. https://sourcegraph.slack.com/archives/C02E4HE42BX/p1666716762921609?thread_ts=1666123600.908089&cid=C02E4HE42BX

/cc @sourcegraph/delivery

**Comment by abeatrix** [comment]
Changes in https://github.com/sourcegraph/deploy-sourcegraph/pull/4215 introduce the ability to deploy searcher and symbols as Deployment / StatefulSets.
