### ISSUE TITLE
insights: write migration to save recording times for existing insights

### ISSUE THREAD

**Issue by leonore** [sourcegraph/sourcegraph#43496]
part of the 0-value issue

1. try and generate time sequence through psql's internals and compare to BuildFrames output; if satisfactory we could do this using an in-band migration
2. if this isn't; we can do this using an oob migration:
* construct the recording times for the historical data according to BuildFrames (12 points only)
* fetch unique recording times for series points (additional points)
* add this data to insight_series_recording_times

/cc @joelkw @felixfbecker @vovakulikov

**Comment by leonore** [comment]
P0 to release this in 4.2 with the actual augmentation change

**Comment by coury-clark** [comment]
agree

**Comment by coury-clark** [comment]
try to come up with some heuristic for matching missing recordings after original backfill, for example +/- half an interval

**Comment by coury-clark** [comment]
from @Joelkw async checkin - don't want to spend a ton of time making something perfect, not interested if we can't also fill in most values including recordings
