### ISSUE TITLE
insights: spike on actual implementation for fetching a user's allowed repos

### ISSUE THREAD

**Issue by leonore** [sourcegraph/sourcegraph#43497]
see title. is it possible for a user to run search queries so that they can get an order of magnitude of what they don't have access to?

timebox to 2d max

decision should inform whether a search query box is the best solution

/cc @joelkw @felixfbecker @vovakulikov

**Comment by coury-clark** [comment]
I opened https://github.com/sourcegraph/sourcegraph/issues/43512 - is this the same?

**Comment by leonore** [comment]
@coury-clark yes. your issue might be set out clearer

**Comment by chwarwick** [comment]
https://github.com/sourcegraph/sourcegraph/issues/43512 is closed should this be too?

**Comment by leonore** [comment]
it was closed as duplicate afaik, but to confirm
