### ISSUE TITLE
How to create a private extension registry for OSS sourcegraph?

### ISSUE THREAD

**Issue by xingx-xx** [sourcegraph/sourcegraph#4349]
#### Question description

I setup an OSS sourcegraph for test in our private network, and I wanna use some greate extensions for sg.

How to create an extention registry like "https://sourcegraph.com/.api/registry"? Is there any documents?

**Comment by slimsag** [comment]
Hi there, unfortunately private extension registries are only available in our enterprise Unlimited plan: https://about.sourcegraph.com/pricing/

What you can do (for free) is use our Sourcegraph Core offering (which is built from our OSS code) via e.g. our Docker image and use the Sourcegraph.com extension registry with Sourcegraph to install and use as many extensions as you like on your own private Sourcegraph instance.

To get started with that see https://docs.sourcegraph.com/

Let me know if this helps!
