### ISSUE TITLE
Out of Memory - Docker

### ISSUE THREAD

**Issue by soggysec** [sourcegraph/sourcegraph#435]
Hello, is there a way of increasing the amount of memory dedicated to the Docker Container version of SourceGraph? 

I received the following error:
```bash
17:19:53 zoekt-indexserver | 2018/10/17 17:19:53 error indexing test@97ee3dd48690a88e3282b35d5187981f99fb75ae: command [zoekt-archive-index -parallelism=2 -index /var/opt/sourcegraph/zoekt/index -file_limit 1048576 -incremental -branch HEAD -commit 97ee3dd48690a88e3282b35d5187981f99fb75ae -name test http://127.0.0.1:3090/.internal/git/test/tar/97ee3dd48690a88e3282b35d5187981f99fb75ae] failed: exit status 2
17:19:54 zoekt-indexserver | OUT:
17:19:54 zoekt-indexserver | ERR: fatal error: runtime: out of memory
```

**Comment by nicksnyder** [comment]
If you want to allocate more memory to Docker, this is generally done by configuring Docker itself. For example in Docker for Mac the preference screen looks like this:

![image](https://user-images.githubusercontent.com/754768/47115926-fe27cc00-d214-11e8-827a-1ead7a52e921.png)

**Comment by sqs** [comment]
@soggysec Are you still seeing this issue? Did @nicksnyder's fix help?

**Comment by soggysec** [comment]
@sqs I have not seen this issue again, and wasn't able to try the same docker configuration as it's seemingly more involved on Linux.

**Comment by soggysec** [comment]
Closing until it becomes a bigger issue
