### ISSUE TITLE
Pagination - UI component (page selector) - must have - FE scale audit - strategic readiness

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#43535]
### Description

Update the [page selector](https://storybook.sgdev.org/?path=/story/wildcard-pageselector--all-page-selectors) component so that it universally meets the needs of various places in the app (batch changes, admin area, code insights, etc.)

<img width="869" alt="Screenshot 2022-10-28 at 19 39 05" src="https://user-images.githubusercontent.com/20326070/198698835-48662a5f-5a3f-42d9-9f02-b90268ca6f23.png">

### Plan

- [x] Update this issue with a design template
- [ ] Determine the milestone when it is delivered

---
Additional resources:

- [Product Experience at Scale: Great vs. Good vs. Bad](https://docs.google.com/document/d/1KPsPfZqZ2AAIJ5Ybe7QrWKuaafYF5vUcaB1IfiF82Po/edit#heading=h.4jfhf6ai2t49)
- [Raw scale audit](https://docs.google.com/spreadsheets/d/1tqpi22csQJNlk7Q9JFWcFj09VbWOiFdp-Vf18qJsWHc/edit#gid=0)
--- 

## Design process

  - Estimate: 3 days
  - Weighting factors:
    - LOW risk
    - HIGH clarity

  ### Discover
  - [X] Product and/or engineering provide direction and/or feedback

  ### Define
  - [X] Github issue

  ### Design
  - [x] High fidelity design using design system - [Figma](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/%E2%9C%B3%EF%B8%8F-Wildcard-Design-System?node-id=21502%3A49150&t=DfkX7L9NSMR993e7-1)
  - [x] Designer review

  ### Deliver
  - [ ] Loom - Link
  - [x] Team review
  - [x] Design team review
  - [ ] QA - Link

**Comment by philipp-spiess** [comment]
Linking some important content and limitations from the Slack discussion: https://sourcegraph.slack.com/archives/C01C3NCGD40/p1667543288287339

**Comment by danielmarquespt** [comment]
Limitations summary from [Slack Discussion](https://sourcegraph.slack.com/archives/C01C3NCGD40/p1667543288287339)

- We can only link to the First Page, Previous Page, Next Page, and Last Page
- We can display the total number o items on all pages  
- We **cannot** display the current page number, nor any interval from the total
