### ISSUE TITLE
webhooks: Deprecate old config, handlers, and GraphQL

### ISSUE THREAD

**Issue by mollylogue** [sourcegraph/sourcegraph#43569]
We want to eventually make our new `/.api/webhooks/UUID` endpoints the only way to receive webhooks.

In order to do this, we should mark our existing endpoints as deprecated and define a point at which they
will be removed. 

- [x] Document in CHANGELOG that old style code host specific webhook HTTP handlers are deprecated.
- [x] Mark the `webhooks` section in external service config as deprecated.
- [x] Marks `WebhookLogs` field on `ExternalService` in GraphQL schema as deprecated. 
- [x] Add deprecation notice (and a redirect to /site-admin/webhooks) on old Batch Changed > Incoming webhooks page
- [x] Add deprecation notice in batch changes banner on external service config page

I would suggest that we mark it as deprecated in release N, simply via a CHANGELOG entry and marking the config
as deprecated in the schema. Then, we can remove the code 3 releases later.

Depends on https://github.com/sourcegraph/sourcegraph/issues/43050

/cc @jplahn @ryphil

**Comment by mollylogue** [comment]
@ryanslade  or @sashaostrikov could y'all clarify what's meant by this? The first thing that came to mind for me was removing the experimental flag for `EnableWebhookRepoSync` and removing the code enqueueing a webhook build job from the SyncExternalService code (see [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/repos/syncer.go?L662-677) When we _do_ automate creating webhooks, I'm guessing we don't want to do it there anymore, since we don't want to tie it directly to the syncing of the external service.) 
 I'm assuming that since Batch Changes also uses the webhook handlers, we should _not_ remove references to an external service from the webhooks handlers, i.e. logging the id in the [middleware](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/webhooks/middleware.go?L84). 
What else should be deprecated?

**Comment by ryanslade** [comment]
I updated the description. I think we should do this only once the CRUD ui is done, we don't want to deprecate the current method until we have a solution that will replace it.

**Comment by ryanslade** [comment]
The `EnableWebhookRepoSync` should stay hidden behind a flag since this is something we're only going to start working on in Milestone 4.
