### ISSUE TITLE
Code Search Basics: Example queries

### ISSUE THREAD

**Issue by st0nebraker** [sourcegraph/sourcegraph#43572]
### Problem description
[Figma](https://www.figma.com/file/qdUtoveMtn2wI8eaysE1De/UX%3A-Cleaning-up-noise-below-the-search-bar-on-dotcom)

When someone lands on sourcegraph.com/search for the first time, there's a lot of noise that gets in the way of them interacting with the product, and product interaction is what will help them understand the value of Sourcegraph and sign up for a free trial. So we must immediately ensure we're surfacing them with the most valuable information.

### Context

#43255

### User journey stage

Consideration

### Impact

High

### Effort

3 days

### Success criteria

Iteration on top of #43570 

- Add toggle between syntax basics & example queries
- Add example queries
- Add drop down for OSS contexts (needs Refinement)

### Assigning labels

- [ ] If this issue will require input from designers in order to complete, please assign the label `needs-design`.

**Comment by kelsey-brown** [comment]
Tracking chart is [here](https://analytics.amplitude.com/sourcegraph/dashboard/jsg5f3q). Planning to revisit ~ Nov 18 to assess:
- Are search examples being used
- Most popular search examples
- Cohorting for users who click search examples - do they convert/retain better than users who don't?

**Comment by kelsey-brown** [comment]
Update: 

- Conversion [dropped off a bit last week](https://analytics.amplitude.com/sourcegraph/chart/new/nx2djnb) but not significantly. I'm not concerned about this at this point. 
- Over the past few weeks, new users clicking query examples are [more likely to click CTAs](https://analytics.amplitude.com/sourcegraph/chart/new/wwmjgte) than new users who don't search at all, and maybe slightly more likely than users who search without examples
- Affect on [30-day retention](https://analytics.amplitude.com/sourcegraph/chart/new/33bl8kf) seems negligible  

I'm going to move this out of measuring - I feel good concluding that repo filters are "working:" users who click them are more likely to [search multiple times](https://analytics.amplitude.com/sourcegraph/chart/new/92fb6nz), and more likely to click CTAs, than users who don't
