### ISSUE TITLE
External service config errors shown for different external service

### ISSUE THREAD

**Issue by christinaforney** [sourcegraph/sourcegraph#4357]
When updating the external service configuration for github.com, an error is shown that a different external service (github enterprise) is failing to sync. This is out of context error is confusing and misleading because it shows up in response to saving an unrelated configuration.

To reproduce:
1. Run enterprise locally
1. [Go to external services](http://localhost:3080/site-admin/external-services)
1. Click on "GITHUB #1" Settings
1. Without changing anything, click 'Update external service'

![image](https://user-images.githubusercontent.com/1559622/58918828-bd67bf00-86e0-11e9-9fac-01cde034d13d.png)

**Comment by keegancsmith** [comment]
We have to sync all services in our current architecture. We do want to move this warning to a top level notifcation this iteration, rather than blocking the external service updates. That would probably remove the confusion. cc @sourcegraph/core-services

**Comment by keegancsmith** [comment]
Fixed by https://github.com/sourcegraph/sourcegraph/pull/4637
