### ISSUE TITLE
Support Two-Factor Authentication with built in auth

### ISSUE THREAD

**Issue by francisschmaltz** [sourcegraph/sourcegraph#436]
Support Two-Factor Authentication with built in auth and on Sourcegraph.com

We should support TFA to increase security on sourcegraph.com as well as instances with out another auth provider.

https://github.com/sourcegraph/enterprise/issues/13684

**Comment by nicksnyder** [comment]
This is not a priority unless specific customers ask for it.

Sourcegraph.com doesn't have a lot of sensitive information right now (e.g. no private code).

Customer instances are protected by their company's network security (e.g. their SSO provider, or being firewalled from the internet).

**Comment by tsenart** [comment]
We're considering working on this in the next cycle (two weeks from now).

**Comment by quinnkeast** [comment]
Since this will involve several separate actions to support implementation, I've created a new tracking issue #15352 for implementing 2FA.

**Comment by ryanslade** [comment]
@flying-robot Not sure if your new tickets mean we can close this one?
