### ISSUE TITLE
4.1.2 patch release request: fix performance regression by removing "activation" component

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#43602]
@sourcegraph/release-guild I am requesting the following commits be included in a patch release. They are already merged into `main`:

- https://github.com/sourcegraph/sourcegraph/commit/58568e4e3ef5e06a5ce9e8e7c83cbf742f836237
- https://github.com/sourcegraph/sourcegraph/commit/d185c3d979774c750c307e495afa12866122dfbd

---

The intent of the questions below is to ensure we keep Sourcegraph high quality and [only create patch releases based on a strict criteria.](https://handbook.sourcegraph.com/engineering/releases#patch-releases) If you can answer yes to many or most of these questions, we will be happy to create the patch release.

I have read [when and why we perform patch releases](https://handbook.sourcegraph.com/engineering/releases#patch-releases) and answer the questions as follows:

> Are users/customers actively asking us for these changes and cannot wait until the next full release?

Yes. See [this slack thread for context](https://sourcegraph.slack.com/archives/C03TGHH1S3V/p1666747586140109) and the PR description here https://github.com/sourcegraph/sourcegraph/pull/43591.

Customers are impacted, reached out to support, rolled back an upgrade, had to hotfix performance themselves by adding database indexes, ...

> Are the changes extremely minimal, well-tested, and low risk such that not testing as we do in a full release is OK?

The changes aren't minimal, but they are low-risk since they only remove code and and make the web app simpler. 

> Is there some functionality completely broken that warrants redacting the prior release of Sourcegraph and advising users wait for the patch release?

Customer's database was pinned at 100% CPU usage and all DB connection pools were completely exhausted so they had to roll back their upgrade from 3.43.2 to 4.0.1

> This will interrupt our regular planned work and release cycle, taking one full working day of our time, and will take up all of our site admin's valuable time by asking them to upgrade or producing noise for them if they don't need to upgrade.
>
> Do you believe the changes are important enough to warrant this?

Yes

> Patch releases are a signal we can do something better to improve the quality of Sourcegraph. Have you already scheduled a call (or created a google doc) to perform a [retrospective](https://about.sourcegraph.com/retrospectives) and identify ways we can improve?

No

---

**For the [Release Captain]** - after reviewing this request:

- [x] **Comment on this issue** with a decision regarding the request.
- [x] If you are a first-time [Release Captain], please review the high-level overview of the [patch release process].
- [x] If approved, **add it to a patch release**:
  - If there is [already an upcoming patch release](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+), add the listed commits alongside a link to this issue.
  - If there is no upcoming patch release, create a new one:
    - [x] Update [`dev/release/release-config.jsonc`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/release/release-config.jsonc), open and merge a PR to `main` to update it.
      - [x] Change `upcomingRelease` to the current patch release
      - [x] Change `previousRelease` to the previous patch release version
      - [x] Change `releaseDate` to the current date (time is optional) along with `oneWorkingDayAfterRelease` and `threeWorkingDaysBeforeRelease`
      - [x] Change `captainSlackUsername` and `captainGitHubUsername` to the patch captain's
    - [x] Run `yarn release tracking:issues` on `main`
    - [x] Add the listed commits alongside a link to this issue to the generated [release tracking issue](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+)
- [x] **Comment and close this issue once the relevant commit(s) have been cherry-picked into the release branch**.

[release captain]: https://handbook.sourcegraph.com/engineering/releases#release-captain
[patch release process]: https://handbook.sourcegraph.com/departments/product-engineering/engineering/process/releases#patch-release-process

**Comment by BolajiOlajide** [comment]
Approved.
