### ISSUE TITLE
Indexing doesn't work on specific yarn.lock file, why?

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#4360]
This turns up no search results: https://k8s.sgdev.org/search?q=repo:%5Egithub%5C.com/sourcegraph/codeintellify%24+marked

Disabling indexing by adding `index:no` to the query fixes it: https://k8s.sgdev.org/search?q=repo:%5Egithub%5C.com/sourcegraph/codeintellify%24+marked+index:no

Other yarn.lock files work: https://k8s.sgdev.org/search?q=repo:%5E35%5C.247%5C.108%5C.89/repos/13/github%5C.com/sourcegraph/sourcegraph/%5C.git%24%40fb7acbf+%22helper-module-transforms%22

Why is this? What is it about this specific file that causes indexing on it to not work properly? @ryan-blunden also encountered this on a different sourcegraph/server instance

**Comment by ijt** [comment]
I repro'd it locally with fakehub.

![Screen Shot 2019-06-04 at 20 12 01](https://user-images.githubusercontent.com/15530/58927843-177a7b80-8705-11e9-8908-e8148c6aa5bd.png)

**Comment by ijt** [comment]
Zoekt doesn't index it because the file is larger than a certain threshold:

![Screen Shot 2019-06-04 at 20 20 25](https://user-images.githubusercontent.com/15530/58928165-46452180-8706-11e9-94e1-b716a098eeff.png)

**Comment by ijt** [comment]
Also it's an auto-generated file, so probably not very interesting for code search.

**Comment by ijt** [comment]
I'm closing this since it's by design, but open to discussing more if you think it's worth changing.

**Comment by keegancsmith** [comment]
We added a feature for this to force indexing: https://github.com/sourcegraph/sourcegraph/pull/3337
