### ISSUE TITLE
Pagination - admin: repositories - must have - FE scale audit - strategic readiness

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#43620]
### Description
Change pattern for 'Admin: repositories' page list to traditional pagination ([example page](https://scaletesting.sgdev.org/site-admin/repositories))

Currently implemented paginated infinite scroll is not an optimal experience for users with many items. Infinite scroll is best for users who are looking to explore content. Pagination works better for end users with an end destination or desired outcome. It would also provide more information about the number of items and easier navigation through it (it's easier to jump to the end or middle of the list, and recall on which page the item was).

![image](https://user-images.githubusercontent.com/20326070/198702015-1ea067d1-8bd0-474f-b8f9-a5b34d630374.png)

### Plan

- [ ] Engineering spike to determine the limitations (if any) for implementing the pagination component. Some of the questions to answer: can we show the total number of pages, can the user jump to the first or last page, how many pages user can jump forward and back, etc.
- [ ] Update this issue with a design template
- [ ] Adjust pagination component #43535 (delivery date TBD) if needed
- [ ] Determine the milestone when it is delivered

---
Additional resources:
- [Product Experience at Scale: Great vs. Good vs. Bad](https://docs.google.com/document/d/1KPsPfZqZ2AAIJ5Ybe7QrWKuaafYF5vUcaB1IfiF82Po/edit#heading=h.4jfhf6ai2t49)
- [Raw scale audit](https://docs.google.com/spreadsheets/d/1tqpi22csQJNlk7Q9JFWcFj09VbWOiFdp-Vf18qJsWHc/edit#gid=0)

**Comment by mrnugget** [comment]
cc @vdavid who's been looking at moving the table-based design over to this page. This ticket is currently assigned to @thenamankumar so make sure you don't step on each other's toes.

**Comment by thenamankumar** [comment]
@mrnugget David told me earlier that he is working on the migration. 

Do you still need help with the table component @vdavid ?

**Comment by vdavid** [comment]
@mrnugget Thanks a lot for connecting us; possible that this helped avoid some duplicate work.

@thenamankumar
I'm indeed looking at changing the page. I'm currently collecting info, but I'd likely have reached out to you later today to set up a meeting.
Yesterday I collected your and Erzhan's PRs related to the back-end and front-end changes of the User admin page changes.
Today's plan is to go through the PRs and understand the changes needed to make the backend support sorting the data, and also to understand the front-end components.
Then the next step on my agenda would be to set up a meeting with you.
Have you started working on this already? Do you perhaps want to pair on it later today or tomorrow? (If so, we can do any scheduling in GCal / Slack.)

**Comment by philipp-spiess** [comment]
Linking some context regarding how to proceed with this issues from Slack: https://sourcegraph.slack.com/archives/C03MW9T8G6A/p1668531004016079

**Comment by vdavid** [comment]
I've removed myself from this because I ended up solving the repo page sorting in a different way.
