### ISSUE TITLE
Pagination - admin: user list - must have - FE scale audit - strategic readiness

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#43621]
### Description
Change pattern for 'Admin: user list' page list to traditional pagination ([example page](https://scaletesting.sgdev.org/site-admin/users?searchText=&offset=0&limit=25&orderBy=EVENTS_COUNT&descending=false&isAdmin=&maxEventsCount=&lastActiveAt=&createdAt=&deletedAt=))

Currently implemented paginated infinite scroll is not an optimal experience for users with many items. Infinite scroll is best for users who are looking to explore content. Pagination works better for end users with an end destination or desired outcome. It would also provide more information about the number of items and easier navigation through it (it's easier to jump to the end or middle of the list, and recall on which page the item was).

![image](https://user-images.githubusercontent.com/20326070/198702343-483de7db-fd20-45cf-b098-995a7c807935.png)

### Plan

- [ ] Engineering spike to determine the limitations (if any) for implementing the pagination component. Some of the questions to answer: can we show the total number of pages, can the user jump to the first or last page, how many pages user can jump forward and back, etc.
- [ ] Update this issue with a design template
- [ ] Adjust pagination component #43535 (delivery date TBD) if needed
- [ ] Determine the milestone when it is delivered

---
Additional resources:
- [Product Experience at Scale: Great vs. Good vs. Bad](https://docs.google.com/document/d/1KPsPfZqZ2AAIJ5Ybe7QrWKuaafYF5vUcaB1IfiF82Po/edit#heading=h.4jfhf6ai2t49)
- [Raw scale audit](https://docs.google.com/spreadsheets/d/1tqpi22csQJNlk7Q9JFWcFj09VbWOiFdp-Vf18qJsWHc/edit#gid=0)

/cc @sourcegraph/source

**Comment by thenamankumar** [comment]
@AlicjaSuska @philipp-spiess on the current users management page there is pagination and not infinite scroll. Though the current paginal is different from the PageSelector component used at other places. 

We use the following custom component: 
<img width="376" alt="image" src="https://user-images.githubusercontent.com/22571395/201871401-4727c1f5-18e8-48e5-ae93-c4aee5beff9a.png">


Should I replace this with the PageSelector component or should I keep both. The current selector has page size selector as well and I think that can be useful for admins. 

I propose to keep the current component at the top where it right now is and add the PageSelector at the bottom of the table. What do you think?

**Comment by philipp-spiess** [comment]
Linking some context regarding how to proceed with this issues from Slack: https://sourcegraph.slack.com/archives/C03MW9T8G6A/p1668531004016079

**Comment by AlicjaSuska** [comment]
@thenamankumar thank you for bringing this up. I've created a mockup showing the changes we should make those this page:
- move the pagination to the bottom
- change the current pagination/selector to a dropdown where user can select the number of items on the page
- merge texts at the bottom of the table
Please, see [Figma](https://www.figma.com/file/SiFt7KlbjUwSMXPfsXXdew/Strategic-readiness---design?node-id=385%3A994) for details and this [loom](https://www.loom.com/share/17245593a832441f911bdf0d2cee07cd) for the walkthrough.
Thank you!

![image](https://user-images.githubusercontent.com/20326070/202193337-93f9c2b7-0e9f-4433-847a-713fd0c219f9.png)

**Comment by mrnugget** [comment]
@peterguy @cesrjimenez this would be something that now falls to you, right? I couldn't find a proper label (or project board) to attach here, hence this hand-chiseled message

**Comment by peterguy** [comment]
Labeling it with `code-search` was perfect - that'll get it into our board in triage mode and we'll take a look at it! Thanks!

**Comment by camdencheek** [comment]
Can we close this? The users page is already paginated -- I'm not sure why this was marked as "infinite scrolling"

**Comment by vovakulikov** [comment]
I think we can close it since this track with scale audit has passed already, and apparently, we don't have problems with the user's page  (I think the 1-10k range is an okay range for offset pagination and I doubt that we will have more than this range users even with big customers). But for the record, this is open because currently, users' page uses offset-based pagination. Ideally, if we stick to consistency, we should migrate all pagination endpoints to the reference-based.

**Comment by eseliger** [comment]
Was this intentionally reopened or linear foo? 😅

**Comment by camdencheek** [comment]
Ope, just linear. Thanks!
