### ISSUE TITLE
Pagination - repo: commits page - must have - FE scale audit - strategic readiness

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#43658]
### Description

Change pattern for 'repo: commits page' page list to traditional pagination ([example page](https://scaletesting.sgdev.org/ghe.sgdev.org/sourcegraph/DefinitelyTyped-DefinitelyTyped/-/commits?first=80))

Note: no need for pagination in the commits popover.

Currently implemented paginated infinite scroll is not an optimal experience for users with many items. Infinite scroll is best for users who are looking to explore content. Pagination works better for end users with an end destination or desired outcome. It would also provide more information about the number of items and easier navigation through it (it's easier to jump to the end or middle of the list, and recall on which page the item was).

![image](https://user-images.githubusercontent.com/20326070/198969485-7e8f7621-d96a-4892-b160-2ad014b338a5.png)

### Plan

- [ ] Engineering spike to determine the limitations (if any) for implementing the pagination component. Some of the questions to answer: can we show the total number of pages, can the user jump to the first or last page, how many pages user can jump forward and back, etc.
- [ ] Update this issue with a design template
- [ ] Adjust pagination component #43535 (delivery date TBD) if needed
- [ ] Determine the milestone when it is delivered

---
Additional resources:
- [Product Experience at Scale: Great vs. Good vs. Bad](https://docs.google.com/document/d/1KPsPfZqZ2AAIJ5Ybe7QrWKuaafYF5vUcaB1IfiF82Po/edit#heading=h.4jfhf6ai2t49)
- [Raw scale audit](https://docs.google.com/spreadsheets/d/1tqpi22csQJNlk7Q9JFWcFj09VbWOiFdp-Vf18qJsWHc/edit#gid=0)

/cc @felixfbecker

**Comment by philipp-spiess** [comment]
Linking some context regarding how to proceed with this issues from Slack: https://sourcegraph.slack.com/archives/C03MW9T8G6A/p1668531004016079

**Comment by philipp-spiess** [comment]
I got some findings from looking at the backend for this. The TL;DR is that the we can probably make forward pagination a lot more performant but it also does not look like we can make backward pagination possible.

My ideas are to use ranges and commit IDs as cursors (instead of an increasing limit on the client side, yikes), so that:
- `first: <n>` => `git log -n <n> <current_commit>`
- `first: <n>, after: <after_commit>` => `git log -n n <after_commit>`
- However `-n` does not work together with `--reverse` so we can't implement backward pagination :( I'll be asking around if others have idea but we might need to think about what we can do here if we have this hard limitation from the git backend @AlicjaSuska

**Comment by indradhanush** [comment]
I was thinking about reverse pagination while working on the PR you just linked and ran into the same challenge with reverse. I'm not aware of a git native way yet (haven't researched this thoroughly). But in case this is a hard limitation on git, maybe we will need to write commit logs to the DB to be able to go both forwards and backwards. Might also help with monorepo scale limits. Any thoughts?

**Comment by mrnugget** [comment]
> But in case this is a hard limitation on git, maybe we will need to write commit logs to the DB to be able to go both forwards and backwards. Might also help with monorepo scale limits. Any thoughts?

That would blow up the scope immensely. I think that's out of scope for this. We might, at some point, save commits in the database, but it should be separate from this.

**Comment by felixfbecker** [comment]
I think given Git's data model and also that forward pagination is more common than backwards from a user perspective, it's fine to optimize (make fast) forward pagination and have backwards pagination be less efficient.

**Comment by philipp-spiess** [comment]
Responded here: https://github.com/sourcegraph/sourcegraph/pull/45157#issuecomment-1339057515

**Comment by philipp-spiess** [comment]
Will update the commits page once @indradhanush updates the `useFetchMorePagination` hook to allow using a differently named `after` cursor (c.f. https://github.com/sourcegraph/sourcegraph/commit/cc18b7b42322360e6e99a8f17dc82cf4ba1c75e9)

**Comment by philipp-spiess** [comment]
@AlicjaSuska With the current implementation this is not possible, no :(
