### ISSUE TITLE
Sorting - UI component - must have - FE scale audit - strategic readiness

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#43678]
### Description

Audit all the places in the application when sorting is available and create a pattern (a component, if needed) that all those places should be aligned to.

Note: it's a design issue that prepares a general pattern, it doesn't mean that implementation of new sorting in all the places listed below is a must-have, high-priority item. Please, refer to [sorting tracking issue](https://github.com/sourcegraph/sourcegraph/issues/43676) for must-have's and [FE audit](https://docs.google.com/spreadsheets/d/1tqpi22csQJNlk7Q9JFWcFj09VbWOiFdp-Vf18qJsWHc/edit#gid=0) for nice-to-haves.

Sorting in Sourcegraph:
- contexts: all contexts
- notebooks (order by: ...)
- admin: [users](https://www.figma.com/file/SiFt7KlbjUwSMXPfsXXdew/Strategic-readiness---design?node-id=21%3A3)
- admin: [repositories](https://www.figma.com/file/SiFt7KlbjUwSMXPfsXXdew/Strategic-readiness---design?node-id=22%3A12)
- admin: [code graph data uploads](https://www.figma.com/file/SiFt7KlbjUwSMXPfsXXdew/Strategic-readiness---design?node-id=22%3A14)
- admin: [executors](https://www.figma.com/file/SiFt7KlbjUwSMXPfsXXdew/Strategic-readiness---design?node-id=105%3A10)
- batch changes: [workspaces sorting](https://www.figma.com/file/SiFt7KlbjUwSMXPfsXXdew/Strategic-readiness---design?node-id=22%3A9)
- batch changes: [all BCs list](https://www.figma.com/file/SiFt7KlbjUwSMXPfsXXdew/Strategic-readiness---design?node-id=285%3A22)
[this list may not be exhaustive; please add new locations if needed]

Possible locations that need sorting:
- monitors (especially 'all' tab)
- insights (all insights page)
- org: members (maybe)

### Plan

- [x] Update this issue with a design template
- [ ] Determine the milestone when it is delivered

---
Additional resources:

- [Product Experience at Scale: Great vs. Good vs. Bad](https://docs.google.com/document/d/1KPsPfZqZ2AAIJ5Ybe7QrWKuaafYF5vUcaB1IfiF82Po/edit#heading=h.4jfhf6ai2t49)
- [Raw scale audit](https://docs.google.com/spreadsheets/d/1tqpi22csQJNlk7Q9JFWcFj09VbWOiFdp-Vf18qJsWHc/edit#gid=0)

**Comment by jjinnii** [comment]
## Design process

  - Estimate: One day to a week
  - Weighting factors: High clarity, Low risk 

  ### Discover
  - [ ] Existing customer feedback - Link
  - [ ] Product and/or engineering provide direction and/or feedback

  ### Define
  - [x] Github issue

  ### Design
  - [x] High fidelity design using design system - [Figma](https://www.figma.com/file/bNslgBGdDYj7DSk25M47Nv/Strategic-FE-Audit---Sorting?node-id=2263%3A2902&t=Z64Ii4T9DmSGVEnM-1)
  - [x] Non-visual design guidance captured in the issue
  - [ ] Prototype - Link
  - [x] Designer review

  ### Testing
  - [ ] Hallway testing - Link
  - [ ] Usertesting.com task based evaluation - Link

  ### Deliver
  - [x] Loom - [Link](https://www.loom.com/share/235f831c4f574bb4b5a0edcfdaa01c31)
  - [] Team review
  - [x] Design team review
  - [ ] QA - Link

  ### Measure
  - [ ] Metrics defined in the Figma file ([i](https://handbook.sourcegraph.com/departments/product-engineering/product/design/metrics/defining-metrics/)) - Link
  - [ ] Followup task will analyze metrics to ensure successful completion - Link

**Comment by jjinnii** [comment]
@AlicjaSuska @philipp-spiess After concluding design review, I've moved the[ sorting & filtering component](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/%E2%9C%B3%EF%B8%8F-Wildcard-Design-System?node-id=21449%3A49023&t=yCGEjXS2DmsCT6IU-1) into Wildcard. The audit of where sorting & filtering occurs is located [here in the working file](https://www.figma.com/file/bNslgBGdDYj7DSk25M47Nv/Strategic-FE-Audit---Sorting?node-id=2224%3A2465&t=Vyv8FZKn4UGt4qYT-1)!

How should we proceed with deciding which milestone this component will be worked on?

**Comment by philipp-spiess** [comment]
Thanks @jjinnii! 

Do we have any prioritization framework to know which components we need to work on first? It would also be helpful to know which of the places listed in the original ticket by @AlicjaSuska and in your Figma are a _must-have_. 

I see a couple of scenarios here and want to make sure we're taking the right steps:

- There's a must-have item that affects a code exploration owned view or an owner team that does not have sufficient front-end resources, in which case we'll prioritize work on the necessary components accordingly 
- There's a must-have item that affects another team with front-end resources in which case we'll prioritize the needed components in a supporting role.
- None of the items are must-have in which case we (code exploration) still want to drive this from the eng side but might get to it after a few more urgent issues.

/cc @sourcegraph/code-exploration for additional input that helps us prioritze this work

**Comment by jjinnii** [comment]
@philipp-spiess This[ tracking issue ](https://github.com/sourcegraph/sourcegraph/issues/43676)shows that only one sorting related issue #43679 is identified as a must have for Strategic readiness :). 

I'm not sure if for this issue specifically the audit + creating the component is design only or whether it entails creating Storybook components. @AlicjaSuska could you help clarify?

**Comment by jjinnii** [comment]
@AlicjaSuska bump on the above question! 😄

**Comment by AlicjaSuska** [comment]
Since all other issues are nice-to-haves, we can deliver this component after we're done with all the must-have's from strategic audit. My proposition is to:
- treat this issue as design only issue and close it as soon as components and all the necessary documentation is created and moved to Wildcard in Figma (@jjinnii)
- create a follow-up engineering issue for adding the component to our UI library, label it as scale-audit/nice-to-have and scheduled it for January

@jjinnii could you please create a follow-up issue, edit this one as needed and close it? Thank you for all he work :)

**Comment by jjinnii** [comment]
Sorting & filtering components are designed and documented in[ Figma](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/%E2%9C%B3%EF%B8%8F-Wildcard-Design-System?node-id=21449%3A49023&t=LXX6XqDyNFDm4X1h-1). Follow up implementation issue #45055 created as a nice to have.
