### ISSUE TITLE
Sorting - Contexts: order by - must have - FE scale audit - strategic readiness

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#43679]
### Description

The currently implemented label 'Scope ascending/descending' is confusing. The objective of this issue is to change the label to 'Alphabetically A-Z' and 'Alphabetically Z-A'

[Slack thread](https://sourcegraph.slack.com/archives/CHEKCRWKV/p1666601723239429) for context.

### Plan

- [ ] Determine the milestone when it is delivered

---
Additional resources:
- [Product Experience at Scale: Great vs. Good vs. Bad](https://docs.google.com/document/d/1KPsPfZqZ2AAIJ5Ybe7QrWKuaafYF5vUcaB1IfiF82Po/edit#heading=h.4jfhf6ai2t49)
- [Raw scale audit](https://docs.google.com/spreadsheets/d/1tqpi22csQJNlk7Q9JFWcFj09VbWOiFdp-Vf18qJsWHc/edit#gid=0)

/cc @sourcegraph/search-product

**Comment by felixfbecker** [comment]
Aren't search contexts owned by @sourcegraph/search-product?

**Comment by limitedmage** [comment]
Yes, this will be addressed by #44542

**Comment by novoselrok** [comment]
This was fixed in: https://github.com/sourcegraph/sourcegraph/pull/43926

**Comment by jjinnii** [comment]
@novoselrok Sorry should have clarified in this issue. I was first working on #43678 to define the sorting component before providing guidance on this issue. 

While designing the component/specs for the sort component, the design team [decided to standardize on "A to Z" and "Z to A"](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/%E2%9C%B3%EF%B8%8F-Wildcard-Design-System?node-id=21449%3A49023&t=cq5Na1EjmvmDnjaZ-1). Can we create a follow up PR to make this change?

**Comment by novoselrok** [comment]
Ok, if I understand correctly:
* we need to drop "Alphabetically" from the label,
* change "Order by" to "Sort by",
* change "Last update descending" to "Newest updates" and 
* "Last update ascending" to "Oldest updates"

**Comment by jjinnii** [comment]
@novoselrok Yes that's correct! 😄 Thanks for confirming the exact changes
