### ISSUE TITLE
Charts - insight: loading helper text - must have - FE scale audit - strategic readiness

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#43673]
### Description

Improve the helper text for insights to inform better how long users can expect the insight to load or that the process is still in progress. The current solution may be interpreted as an error or blocked process.

![image](https://user-images.githubusercontent.com/20326070/199003223-19b9d45b-9db5-4f70-9d95-5c470410ca3f.png)

### Plan

- [x] Update this issue with a design template - consultive effort, no need for a template
- [x] Determine the milestone when it is delivered

---
Additional resources:
- [Product Experience at Scale: Great vs. Good vs. Bad](https://docs.google.com/document/d/1KPsPfZqZ2AAIJ5Ybe7QrWKuaafYF5vUcaB1IfiF82Po/edit#heading=h.4jfhf6ai2t49)
- [Raw scale audit](https://docs.google.com/spreadsheets/d/1tqpi22csQJNlk7Q9JFWcFj09VbWOiFdp-Vf18qJsWHc/edit#gid=0)

**Comment by AlicjaSuska** [comment]
Update: @coury-clark implemented the percent complete (part of new backfilling system implementation) - demo in [Slack](https://sourcegraph.slack.com/archives/C014ZCKMCAV/p1667600849324339)

**Comment by leonore** [comment]
https://github.com/sourcegraph/sourcegraph/issues/44048

**Comment by leonore** [comment]
As a temporary solution while we wait for the full fix (if it takes too long) we can add a link to helpful docs in the message and potentially rotate "waiting messages" on the UI.

**Comment by AlicjaSuska** [comment]
From the sync: @Joelkw let's focus on improving copy and adding the link to docs here. It is a temporary solution (3-6 months) until we have a better solution to actually estimate/show progress/improve the speed.

**Comment by coury-clark** [comment]
@AlicjaSuska do you have any specific copy you'd like to add here?

**Comment by coury-clark** [comment]
Removing myself from this issue since we've descoped it to copy changes.

**Comment by AlicjaSuska** [comment]
Proposition of updated copy: [Figma](https://www.figma.com/file/zhZx7ma7EH6Y9MHwTUVemS/Charts---insight%3A-loading-helper-text---must-have---FE-scale-audit---strategic-readiness-%2343673?node-id=275%3A1628&t=Osyce3yEcUyR7rQf-4)
