### ISSUE TITLE
Charts - insights: preview in the Creation UI crashes - must have - FE scale audit - strategic readiness (aka make error communication UX better, not necessarily fix the underlying error)

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#43674]
### Description

Preview of the insight displayed in the creation UI crashes and display a non-user-friendly error for big repo. We need to either fix the issue or at least adjust the preview/error text.

Note: if it becomes an issue of only adjusting the error message, move the issue from 'charts' to 'error messages and alerts' tracking issue.

![image](https://user-images.githubusercontent.com/20326070/199003580-26f23556-6a76-4fc9-914e-61ac11a4bf71.png)
### Plan

- [ ] Engineering spike to investigate the cause and potential solutions
- [ ] Update this issue with a design template (if needed)
- [ ] Determine the milestone when it is delivered

---
Additional resources:
- [Product Experience at Scale: Great vs. Good vs. Bad](https://docs.google.com/document/d/1KPsPfZqZ2AAIJ5Ybe7QrWKuaafYF5vUcaB1IfiF82Po/edit#heading=h.4jfhf6ai2t49)
- [Raw scale audit](https://docs.google.com/spreadsheets/d/1tqpi22csQJNlk7Q9JFWcFj09VbWOiFdp-Vf18qJsWHc/edit#gid=0)

/cc @joelkw @felixfbecker @vovakulikov

**Comment by coury-clark** [comment]
@AlicjaSuska 
What were the circumstances in which this test ran? The error message in the screenshot above implies the instance was not healthy when the screenshot was taken.

**Comment by AlicjaSuska** [comment]
cc: @philipp-spiess could you please provide more details? Thank you!

**Comment by coury-clark** [comment]
Yeah - I agree this issue with the bad error message has been something we've known about for a while. Just wanted to double check that's what we were talking about here and not something different!
