### ISSUE TITLE
Browser extension redirects to `https://slimsag/mega` on "Go to definition"

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#4368]
- Browser extension points at: https://sourcegraph.sgdev.org

#### Steps to reproduce:

1. Hover over `fetcher` here: https://github.com/sourcegraph/sourcegraph/blob/master/pkg/diskcache/cache.go#L60
2. Click on "Go to definition"

#### Expected behavior:

I'm being redirected to the definition

#### Actual behavior:

I'm being redirect to https://slimsag/mega/blob/f68f39f4fc4229a542a554bd3f7c765973512d51/docker/trust/trusts.go#L28:2

#### Live footage

![wrong_redirect](https://user-images.githubusercontent.com/1185253/58944039-40405680-8781-11e9-9653-57f7fce531df.gif)

**Comment by felixfbecker** [comment]
This is probably related to our dogfood instance repo names missing the `github.com` prefix and us making incorrect assumptions.
