### ISSUE TITLE
Alerts warnings - repo: file tree folder view - must have - FE scale audit - strategic readiness

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#43691]
### Description

Update the content, placement and possibly style of the alert in the file tree. Note: this issue depends on the outcomes of https://github.com/sourcegraph/sourcegraph/issues/43689

![image](https://user-images.githubusercontent.com/20326070/199046415-4b0dcbbb-77fb-4865-9033-43da49daec78.png)

### Plan

- [ ] Update this issue with a design template
- [ ] Determine the milestone when it is delivered

---
Additional resources:

- [Product Experience at Scale: Great vs. Good vs. Bad](https://docs.google.com/document/d/1KPsPfZqZ2AAIJ5Ybe7QrWKuaafYF5vUcaB1IfiF82Po/edit#heading=h.4jfhf6ai2t49)
- [Raw scale audit](https://docs.google.com/spreadsheets/d/1tqpi22csQJNlk7Q9JFWcFj09VbWOiFdp-Vf18qJsWHc/edit#gid=0)

/cc @felixfbecker

**Comment by philipp-spiess** [comment]
There are some accessibility fixes for the file tree underway. I'm syncing with @lrhacker so we fix the scale issues together with the accessibility issues.

**Comment by AlicjaSuska** [comment]
@philipp-spiess any news about this one? Is it still blocked?

**Comment by philipp-spiess** [comment]
@AlicjaSuska Yeah we haven't gotten around to working on the changes for this yet. Laura is focused on the upcoming accessibility audit but will have availability again very soon.

I think we can already start design work for this, though.

**Comment by philipp-spiess** [comment]
This is currently blocked by https://github.com/sourcegraph/sourcegraph/issues/43689

**Comment by AlicjaSuska** [comment]
Design progress: see the #43689
