### ISSUE TITLE
Alerts warnings - batch changes: many workspaces - must have - FE scale audit - strategic readiness

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#43692]
### Description

Update the content, placement and possibly style of the alert in the workspaces area. Note: this issue depends on the outcomes of https://github.com/sourcegraph/sourcegraph/issues/43689

![image](https://user-images.githubusercontent.com/20326070/199046202-3e5cfd81-0912-4a0b-80fe-5d53b9482347.png)

### Plan

- [ ] Update this issue with a design template
- [ ] Determine the milestone when it is delivered

---
Additional resources:

- [Product Experience at Scale: Great vs. Good vs. Bad](https://docs.google.com/document/d/1KPsPfZqZ2AAIJ5Ybe7QrWKuaafYF5vUcaB1IfiF82Po/edit#heading=h.4jfhf6ai2t49)
- [Raw scale audit](https://docs.google.com/spreadsheets/d/1tqpi22csQJNlk7Q9JFWcFj09VbWOiFdp-Vf18qJsWHc/edit#gid=0)

**Comment by eseliger** [comment]
Sprint planning note: this depends on another ticket, so probably backlog until then?

**Comment by courier-new** [comment]
Agreed -- @danielmarquespt since this is a requirement from the frontend scale audit, do you think you could keep an eye on the prerequisite design ticket here so we can make sure to prioritize this again once that's complete?

**Comment by courier-new** [comment]
@danielmarquespt I see the dependent design issue has been completed! Do you have capacity to help prepare designs/recommendations to apply this in the batch changes workspaces preview area?

**Comment by danielmarquespt** [comment]
@courier-new its already done https://www.figma.com/file/J2WdQXin01d16XCpzYDjua/Alerts-warnings---UX-writing-guidelines---must-have---FE-scale-audit---strategic-readiness-%2343691?node-id=275:1628&t=yhp3B5s1p56xG44y-0

**Comment by courier-new** [comment]
Oh, amazing, thank you!! 🙌

**Comment by courier-new** [comment]
Based on the designs, the location of this banner isn't changing, only the copy and appearance. I've given it a 1 day estimate to reflect that.
