### ISSUE TITLE
☂️Handling repositoryPathPatterns in the browser extension and extension API

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#4370]
Currently, the browser extension and extensions make assumptions that repo names start with the code host hostname.

This is a wrong assumption for private instances, where the repo name is _arbitrary_.

When we have a Sourcegraph instance defined, we need to consult it for the right repo name for a repo.

One possible approach for this is to get the clone URL and use the GraphQL API to resolve this to a repo (this may be difficult if we cannot easily get or infer the clone URL on every page, and could cost more).
Another is to fetch the `repositoryPathPatterns` and run the mapping on the client side (which may be dangerous if the logic is complex and we'd have to duplicate lots of logic).

If we are on a private repo that's not on the instance (e.g. sourcegraph.com), we need to do the codehost-name prefixed behavior.

For extensions, we need to expose ways to get info about the repo source so extensions can know where it came from (e.g. what code host).
An idea for this is exposing info from the GraphQL `externalRepository` field on the `WorkspaceRoot` interface (which currently only has `uri`).

Fixes #4368
Fixes #4278
Fixes #4414 
Rel #2471

**Comment by keegancsmith** [comment]
Right now if you lookup a repository by name it will return try both the full name, and the name after `repositoryPathPatterns` have been applied (preferring the first). If you want to get the full name back, the repository.url in graphql contains it.

What issues are you running into? I did some testing of the go extension and didn't run into anything. However, I am sure there is probably something super simple I didn't try and breaks.

**Comment by felixfbecker** [comment]
See the linked issue as an example. Also the CodeCov extension needs to know what code host a text document is own to call the right CodeCov API endpoint.

Are you talking about the `repository(name: String!)` GraphQL query? So basically `name` can also be a pathname of a code host repo URL?

`repository.url` doesn't sound like the right field because we don't care about a browser URL, we care about the repo name to construct a `git://reponame?rev#file` URI to pass to extensions

**Comment by keegancsmith** [comment]
> Are you talking about the `repository(name: String!)` GraphQL query? So basically `name` can also be a pathname of a code host repo URL?

eg for sgdev you can pass "github.com/sourcegraph/sourcegraph" or "sourcegraph/sourcegraph". Both will resolve to the same repo. The response will have:

``` json
{
  name: "sourcegraph/sourcegraph",
  uri: "github.com/sourcegraph/sourcegraph",
}
```

if our sgdev instance didn't have repositoryPathPattern configured, then we would only respond to "github.com/sourcegraph/sourcegraph" with the response:

``` json
{
  name: "github.com/sourcegraph/sourcegraph",
  uri: "github.com/sourcegraph/sourcegraph",
}
```

To make this crystal clear, this isn't the pathname. For example if sgdev had the repositoryPathPattern `gh/{nameWithOwner}` then we would respond to "github.com/sourcegraph/sourcegraph" or "gh/sourcegraph/sourcegraph" with:

``` json
{
  name: "gh/sourcegraph/sourcegraph",
  uri: "github.com/sourcegraph/sourcegraph",
}
```

> `repository.url` doesn't sound like the right field because we don't care about a browser URL, we care about the repo name to construct a `git://reponame?rev#file` URI to pass to extensions

Sorry I meant URI. See the example I gave above. I would suspect the name you should pass to extensions is the name on Sourcegraph? IE in our sgdev example it should be `git://sourcegraph/sourcegraph?rev#file`.

**Comment by felixfbecker** [comment]
> Sorry I meant URI.

So, I assume you mean `repository.name`, since `repository.uri` is deprecated

**Comment by keegancsmith** [comment]
uri is no longer deprecated

**Comment by lguychard** [comment]
Also fixes https://github.com/sourcegraph/sourcegraph/issues/4414#issuecomment-499826869

**Comment by lguychard** [comment]
Handled in https://github.com/sourcegraph/sourcegraph/pull/4470, closing.
