### ISSUE TITLE
zoekt-indexserver: Enhance sophistication of backoff of recurring index failure

### ISSUE THREAD

**Issue by gl-srgr** [sourcegraph/sourcegraph#43732]
As of completion of issue 42011 we've implemented a basic and predictable backoff strategy. The backoff strategy's goal is to backoff subsequent indexing attempts for a given repository for a period of time because we've identified that the preceding indexing attempt has failed. The backoff period of time is finite and increases linearly with consecutive indexing failures.

There are opportunities to apply greater sophistication. We will capture all improvement efforts and suggestions in this issue and spin off tickets as necessary.

1. We never apply indefinite backoff. Should we ever apply an indefinite backoff such that a repository will not index until some intervention by a person or system? If indefinite backoff is applied then we need to provide a means of removing the backoff.
2. Currently we will not attempt to index until the backoff duration has passed. Should we consider removing the backoff in response to some changes external to indexserver?
3. Should we persist which repos we identified as misbehaving on disk so that on restart we continue backoff strategy from where it left off?
4. Should we consider non consecutive failures in our decision to backoff? e.g. alternating b/w failure and success means wasted effort and we'd still consider this success rate as misbehavior.
5. Report current backoff status via Site Admin or another gui
6. Allow for admins to manually apply backoff via site admin page or another user friendly gui?
7. Related to (5.): Schedule backoff duration in advance
8. Provide more options for backoff strategy. For example: exponential backoff instead of linear. As of now we have the linear approach and also the option to disable.
9. Provide repository specific backoff strategy. For example, a customer could distinguish two repositories based on frequency of changes, susceptibility to indexing blockers, quantity of contributors and viewers, and significance to operations. These factors could be taken into account for each repository's backoff durations.

Predecessor ticket: [42011](https://github.com/sourcegraph/sourcegraph/issues/42011)

/cc @sourcegraph/search-core

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket, please let us know how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.
