### ISSUE TITLE
Ref panel filter by filename not working on dotcom

### ISSUE THREAD

**Issue by macraig** [sourcegraph/sourcegraph#43740]
- **Sourcegraph version:** Sourcegraph.com (haven't been able to reproduce on S2)
- [Slack thread](https://sourcegraph.slack.com/archives/CHXHX7XAS/p1667225626474409)
- [Loom video](https://www.loom.com/share/a3e034c061de4a9aab54412d5c21e889)

#### Steps to reproduce:

1. Open https://sourcegraph.com/github.com/freeCodeCamp/freeCodeCamp/-/blob/tools/scripts/seed/seedAuthUser.js?L13:27&subtree=true#tab=references 
2. Try filtering by a name that doesn't exist on the results

#### Expected behavior: 
Results should be 0

#### Actual behavior: 
Results remain the same

**Comment by varungandhi-src** [comment]
No longer reproduces; closing.
