### ISSUE TITLE
Improve CTAs - Add CTAs to Batch Changes and Insights pages on .com

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#43754]
This is an implementation issue for [Epic: Improve CTAs and sign-up flows across domains](https://github.com/sourcegraph/sourcegraph/issues/43239).

Related design issue TODO. Figma design [here](https://www.figma.com/file/x7JkAkHQZXIhyDVuhErIZz/Map%3A-Journeys-and-paths-for-sign-ups?node-id=130%3A1437).  

All users, whether they're auth'd or unauth'd should have the CTAs on the Batch Changes and Insights pages link them to the cloud signup page . If they're unauth'd the signup page should include the option to create an account (see https://github.com/sourcegraph/sourcegraph/issues/43750).

**Comment by almeidapaulooliveira** [comment]
@taylorsperry - Sorry, I pointed to the wrong Figma. Here are the correct designs:
- [Batch Changes](https://www.figma.com/file/x7JkAkHQZXIhyDVuhErIZz/Map%3A-Journeys-and-paths-for-sign-ups?node-id=123%3A577) 
- [Insights](https://www.figma.com/file/x7JkAkHQZXIhyDVuhErIZz/Map%3A-Journeys-and-paths-for-sign-ups?node-id=127%3A3626)

**Comment by st0nebraker** [comment]
Blocked to merge on this [outstanding Q](https://www.figma.com/file/x7JkAkHQZXIhyDVuhErIZz?node-id=125:3625#306914319)

**Comment by taylorsperry** [comment]
I think this OK to merge as is because the most important part of this issue is to get the Cloud CTAs in there. @danielmarquespt and @almeidapaulooliveira are discussing further changes[ in Figma](https://www.figma.com/file/ScpDpxciO5DeT9YlUGzPUX/UX%3A-Sign-up-journeys-for-auth'd-users?node-id=1%3A53&t=imIGSJFemRoSrktz-0), but they shouldn't block this update.
