### ISSUE TITLE
Improve CTAs - Add nav, pro tip, and settings page cloud trial CTAs for auth'd user

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#43752]
This is an implementation issue for [Epic: Improve CTAs and sign-up flows across domains](https://github.com/sourcegraph/sourcegraph/issues/43239).

[UX: Unified sign-up journey](https://github.com/sourcegraph/sourcegraph/issues/43672) is the related design tracking issue. 

An auth'd user (who has either a .com or self-hosted account) should see cloud trial CTAs. 

- [x] There should be one in the nav bar that says "Search your code" for a .com user and "Try Sourcegraph Cloud" for a self-hosted user (open to feedback on language).
- [x] The nav bar button should replace the "Feedback" button, which takes up a weird amount of space and should be placed somewhere less prominent. 
- [x] For both .com and self-hosted users, they should see the "Pro tip" CTA below the search bar (currently only available to unauth'd users). 
- [x] The settings page should also have a cloud trial CTA.

**Comment by bretthayes** [comment]
@taylorsperry
> For the nav bar CTA, let's say "Search private code" for a .com user (auth'd or unauth'd) and still do "Try Sourcegraph Cloud" for a self-hosted user.

"Auth'd or unauth'd" would conflict with the sign up button since it would be a duplicate button. I think just auth'd makes more sense here.

**Comment by taylorsperry** [comment]
> "Auth'd or unauth'd" would conflict with the sign up button since it would be a duplicate button. I think just auth'd makes more sense here.

Good catch! 🙇
