### ISSUE TITLE
"Context deadline exceeded" on Sourcegraph.com search

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#4382]
- **Sourcegraph version:** Sourcegraph.com

#### Steps to reproduce:

1. https://sourcegraph.com/search?q=r%3Agithub.com%2Fhashicorp+todo

#### Expected behavior:

Ideally, actual results :). If that's not possible, then perhaps some recommendation for how to adjust — e.g. add a `timeout:`? Filter my `repo:` filter more? Etc. It'd be great to see something like "This matched 1,327 repos, that's too many for us, you need to reduce to X" so I have a sense for how far off I am from it working.

#### Actual behavior:

"Context deadline exceeded" error

**Comment by ijt** [comment]
Adding `timeout:3m` to the query works:

![Screen Shot 2019-06-13 at 11 47 38](https://user-images.githubusercontent.com/15530/59459204-17e3d800-8dd1-11e9-9dea-c7c6675f0ca6.png)

it would be nice if we could suggest it though.
