### ISSUE TITLE
Query diagnostics not triggering after toggles are clicked

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#43836]
Query diagnostics tend to "stick" regardless of toggle switching, so we might either continue to display a diagnostic when it's no longer valid, or we might not show diagnostics when we should.

To reproduce:

- This query shows an error diagnostic for `type:commit` when structural search is enabled https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+type:commit+asdf&patternType=structural

- Now click the structural search toggle to disable.

- The diagnostic still shows (but it should disappear)

---

The other way around:

- This query shows no diagnostics, and `type:commit` is set: https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+type:commit+asdf&patternType=structural

- Now click the structural search toggle to disable.

- No diagnostic shows up (but we should be showing the diagnostic that `type:commit` isn't supported)

**Comment by fkling** [comment]
Interestingly sometimes it does update. E.g. having structural search enabled, only entering `type:commit` and then disabling structural search removes the diagnostic message for me. But your examples reliably reproduce the issue...

**Comment by fkling** [comment]
Ah, that was a red herring... I had a space at the end of the query and we seem to strip it (and update the query (-> input changes)) when submitting it.
