### ISSUE TITLE
Open in Editor url doesn't consider repo name when repositorypathpattern is set for IntelliJ

### ISSUE THREAD

**Issue by rakeshjosh2003** [sourcegraph/sourcegraph#43839]
#### Feedback

When a file is opened in the IntelliJ editor, the path doesn't consider the repo name in URL when `"repositoryPathPattern": "{nameWithOwner}"` is set in the code host config. This was working fine before and stopped working since version 4.1.0.
I tested it on version 4.0.1, and it works fine.

Editor settings 

```
“openInEditor”: {
    “projectPaths.default”: “/Users/RJ/“,
    “editorIds”: [
      “idea”
    ]
  },
```

If the repository URL is 

```
gitHub.com/abcd/abcd/licenses/LICENSE-copybutton.txt&line=1&column=1
```

and we set `"repositoryPathPattern": "{nameWithOwner}"` in the code host config

then in 4.1.0, it generates URL 

```
github.com/licenses/LICENSE-copybutton.txt&line=1&column=1
```

the expected URL is  

```
github.com/abcd/licenses/LICENSE-copybutton.txt&line=1&column=1
```
( which works fine in 4.0.1)

#### Customer
https://sourcegraph2020.lightning.force.com/lightning/r/Account/0013t00001XibW6AAJ/view

/cc @sourcegraph/integrations

**Comment by philipp-spiess** [comment]
Hey @rakeshjosh2003,

We've been discussing this a bit in [Slack](https://sourcegraph.slack.com/archives/C01LZKLRF0C/p1667453554438929). Right now the `repositoryPathPattern` config option is not properly taken into account for the issue. We're still figuring out how to fix it though. Can you share insights with us (in Slack) about the customer that is affected so we can properly prioritize this?

**Comment by vdavid** [comment]
Clues:
- This seems to be the PR that broke the behavior: https://github.com/sourcegraph/sourcegraph/pull/41844
- The structure of `repositoryPathPattern` is described [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/schema/github.schema.json?L153)
