### ISSUE TITLE
Navigation bar in Open source version includes items that are not usable

### ISSUE THREAD

**Issue by simhnna** [sourcegraph/sourcegraph#43861]
- **Sourcegraph version:** 4.1.2 OSS

* The dropdown on code search is empty in OSS builds. In OSS builds it should be a plain button
* Notebooks is an enterprise feature that shouldn't be visible in OSS builds
* Code Monitoring is an enterprise feature that shouldn't be visible in OSS builds

**Comment by jdorfman** [comment]
Thanks for reporting this. Any chance you can attach a screenshot so we can get it fixed faster? Thanks!

**Comment by FB-KH** [comment]
@jdorfman I've been experiencing the same issue. I've attached a screenshot of the notebooks page. The monitoring menu item just sends me to a search for `repo:^code-monitoring$`

![unsupported menu items](https://user-images.githubusercontent.com/101691643/203433445-db4714f8-66f1-4ecf-8137-cae03988510c.png)

**Comment by jdorfman** [comment]
@FB-KH thank you, this makes more sense.

**Comment by simhnna** [comment]
No longer is the case in 4.4.2
