### ISSUE TITLE
Add "Search private code" above search bar on .com

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#43863]
Add "Search private code" with a link to signup.sourcegraph.com to the copy between the Sourcegraph logo and the search bar for both auth'd and unauth'd visitors to .com. It should read "Search millions of open source repositories | Search private code." Let's add a unique tracker to this link so that we can see which CTAs are working best. 

![Screen Shot 2022-11-03 at 7 53 41 AM](https://user-images.githubusercontent.com/43555476/199739347-5d05f89a-184b-4607-ad8d-7c1e0444998a.png)

**Comment by almeidapaulooliveira** [comment]
@taylorsperry - Metrics [here](https://www.figma.com/file/qdUtoveMtn2wI8eaysE1De/UX%3A-Cleaning-up-noise-below-the-search-bar-on-dotcom?node-id=293%3A3165) and how the design will look like [here](https://www.figma.com/file/qdUtoveMtn2wI8eaysE1De/UX%3A-Cleaning-up-noise-below-the-search-bar-on-dotcom?node-id=51%3A4681).

**Comment by taylorsperry** [comment]
@kelsey-brown lmk if I didn't do the tracking right 😬

**Comment by kelsey-brown** [comment]
@taylorsperry just a heads up that the "pro tip" under the search examples uses the same event name (`ClickedOnCloudCTA`) so we won't be able to differentiate between the two (ex isolate if one is getting more clicks than the other). Are you ok with that? The only time it might come up is if we want to remove one or the other and want to ensure we're removing the less-clicked one. I don't really expect to need to do that in the near term so I'm good with it if you are.

**Comment by almeidapaulooliveira** [comment]
@kelsey-brown, it's the [same event](https://www.figma.com/file/qdUtoveMtn2wI8eaysE1De/UX%3A-Cleaning-up-noise-below-the-search-bar-on-dotcom?node-id=293%3A3165&t=D7k1IZbr17VTP97d-4) but with different `origin` parameters. Do you think we should use different events for the same action but different sources?

**Comment by kelsey-brown** [comment]
I think if the different events could have different event properties that would probably be ideal. Basically anything passed in the `argument` field gets parsed as an event property and is searchable/filterable in Amplitude. Could we add the origin parameter to the argument field? 

We could also possibly update the pipeline to also pull the `origin` field, but I think as a rule I'd rather have everything we care about live in the same field if it's possible (I think most other event properties live in that field). Or do you guys have other suggestions for the easiest way to do this? I haven't worked a ton with new cloud events/event properties in the past so I'm  open to suggestions/best practices here if you've got 'em.

**Comment by almeidapaulooliveira** [comment]
@rrhyne, can you share your experience on how to use parameters on Amplitude events?

**Comment by kelsey-brown** [comment]
@almeidapaulooliveira  We also had a discussion about this in this [thread](https://sourcegraph.slack.com/archives/C046X8AG5NY/p1668535280011809)

**Comment by almeidapaulooliveira** [comment]
Oh, I missed that. Thanks, Kelsey!!

**Comment by kelsey-brown** [comment]
Update is [here](https://sourcegraph.slack.com/archives/C046X8AG5NY/p1669046517781869?thread_ts=1669046499.560689&cid=C046X8AG5NY) - moving this out of measuring
