### ISSUE TITLE
GHE DogFood perf issues

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#43874]
### User Experience
When you navigate to https://ghe.sgdev.org/settings/organizations you'll get a 502. Initially we thought it was just the sheer amount of repos/users. But @jhchabran also reported a **significant** decrease in performance when copying repos to the GHE instances compared to GHE-scaletesting.

@indradhanush also reported that the performance of the instance has dramatically slowed down his testing. 

###### **Note:** The instance where GHE deployed is not in the usual projects `Sourcegraph`, `Sourcegraph-cloud` or `Sourcegraph CI`. Its in its own project `sourcegraph-github-enterprise`. 

Immediately when you look at the instance GHE is deployed on, GCP recommends the instance gets upgraded
![Screenshot 2022-11-03 at 16 23 46](https://user-images.githubusercontent.com/1001709/199773491-9f5d9840-4de8-44f5-b522-7b29c74c6ea6.png)
![Screenshot 2022-11-03 at 16 24 53](https://user-images.githubusercontent.com/1001709/199773509-f7015cbc-8ded-4d0e-b439-535ddbc8dbe9.png)

Looking at the CPU utilization we can see the machine is very busy. This is especially true if you consider the machine type of this insance is `n2-standard-48`, meaning there are 48 CPUs with 192 GB of Memory
![Screenshot 2022-11-03 at 16 30 50](https://user-images.githubusercontent.com/1001709/199773646-2d6d5425-3673-40f1-9b18-7aec03cf448f.png)

Unfortunately you can't see the memory utilization in GCP, but GHE has a monitoring page on it's management console. Viewing the dashboard there we can not only see the memory utilization but also _what_ is using so much resources.

#### Memory
![Screenshot 2022-11-03 at 16 51 49](https://user-images.githubusercontent.com/1001709/199774433-4dc0f5d1-a92d-4b74-9695-a2ea34915ab0.png)

##### I think Unicorn is the ruby app that powers GHE
![Screenshot 2022-11-03 at 18 15 49](https://user-images.githubusercontent.com/1001709/199775269-5301409a-b62b-4d76-a58f-67ab4350ed32.png)

![Screenshot 2022-11-03 at 16 52 10](https://user-images.githubusercontent.com/1001709/199774750-06602de4-dba4-46b3-a48e-94d6fdab43f4.png)

I do see there are a lot of sleeping processes? Something to look into
![Screenshot 2022-11-03 at 18 17 34](https://user-images.githubusercontent.com/1001709/199775642-5d60a072-640d-4bbf-b43e-b809f3f3a5dd.png)

**Comment by sanderginn** [comment]
This instance is also used by the CI pipeline, which means that builds take longer and/or become flaky. Worth bumping in priority.

**Comment by jhchabran** [comment]
Quick update as I'm driving by: 

- we've identified some redis queues to be blocked with 12k jobs pertaining to the visibility change we've done on the 200k repos for IAM. 
- we've reached out the support and are awaiting some reply.
