### ISSUE TITLE
Clean up "No results" - Add CTA

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#43899]
This is an issue for [Epic: Clean up "No results" page](https://github.com/sourcegraph/sourcegraph/issues/43898).  

Add a CTA to "Search private code" in the event that someone is looking for something in a private repo. Let's update the copy below "No results matched your query" to say: 

Looking for something in a private repo? [Search private code](https://signup.sourcegraph.com/)
Learn more about how to search [in our docs](https://docs.sourcegraph.com/code_search/explanations/features). 

We should add tracking to both the cloud CTA and the link to the docs to help us understand how many visitors are clicking these links when they land on "No results."

**Comment by bretthayes** [comment]
@kelsey-brown ready to measure `ClickedOnDocs`. No other cta link was added since we already have a `ClickedOnCloudCTA` link above the no results banner message.

**Comment by kelsey-brown** [comment]
Thanks! Cool if I move this to measuring?

**Comment by bretthayes** [comment]
Yes for sure! @kelsey-brown
