### ISSUE TITLE
Add "Search private code" CTA to all search results pages

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#43902]
We should add a CTA to "Search private code" to all search result pages, probably in the right-hand panel. 

Design issue:
- #44097

**Comment by taylorsperry** [comment]
Should this have a status of "measuring," since we added a new CTA and tracker?

**Comment by bretthayes** [comment]
@taylorsperry that's a good idea!

**Comment by bretthayes** [comment]
@kelsey-brown the event `ClickedOnCloudCTA ` is on `/search?q=`

**Comment by kelsey-brown** [comment]
We’ve seen an [uptick](https://analytics.amplitude.com/sourcegraph/chart/new/af7u24j) in conversion in the search --> CTA click funnel in the past week, which is likely the result of the new CTA on the search results page.
