### ISSUE TITLE
Improve sign-up journey for auth'd users (from `context`)

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#43907]
This is an issue for [Epic: Update context:global](https://github.com/sourcegraph/sourcegraph/issues/43905).

Changes from [Figma](https://www.figma.com/file/ScpDpxciO5DeT9YlUGzPUX/UX%3A-Sign-up-journeys-for-auth'd-users) & short term changes from Quinn Keasts' [proposal](https://docs.google.com/document/d/1-zkb9WKJxFPapB2EwSy7ePUAUTJ-GHETdRGNwkIZ35I/edit#)

Design issue:
- #44097

**Comment by almeidapaulooliveira** [comment]
@taylorsperry , @st0nebraker - The proposal also includes the following:
- [Pre-fill](https://www.figma.com/file/x7JkAkHQZXIhyDVuhErIZz/Map%3A-Journeys-and-paths-for-sign-ups?node-id=147%3A1226) the form with data from auth'd users.
- [Dynamic copy](https://www.figma.com/file/x7JkAkHQZXIhyDVuhErIZz/Map%3A-Journeys-and-paths-for-sign-ups?node-id=130%3A1648) (on the sign-up page) to connect what the user clicked and the landed page.

Do you think it's feasible, or should we keep it out of the scope of this issue?

**Comment by st0nebraker** [comment]
I think those ideas are really impactful. Pre-fill for sure, checking on Dynamic copy. We can always make a follow-up ticket to iterate them in.

**Comment by st0nebraker** [comment]
Added #44184 for the dynamic enhancements since this work would be on a different repo/platform anyway, so it's best to capture the work separately. Also, we need a few copy variations for the dynamic copy idea. Let me know how I can help map that out @almeidapaulooliveira
