### ISSUE TITLE
Epic: Update context:global

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#43905]
We should optimize the context settings on .com to help users understand that they're searching open source code and they need to sign up if they want to search private code. We need to: 

- ~~Change the `context:global` in the search bar to `context:public`~~
-  Add `Search private code` with a link to signup.sourcegraph.com to the context drop down and add CTA to [`/contexts`.](https://sourcegraph.com/contexts).
- ~~Update docs to reflect this change (and check for anywhere else that we need to add clarification. For self-hosted / managed instances the context should still be `context:global`.~~

Issues in this epic:
- https://github.com/sourcegraph/sourcegraph/issues/43906
- https://github.com/sourcegraph/sourcegraph/issues/43907
- https://github.com/sourcegraph/sourcegraph/issues/43908
- #44097

**Comment by taylorsperry** [comment]
@almeidapaulooliveira I'm adding the `needs-design` label because while we have a Figma file with designs for https://github.com/sourcegraph/sourcegraph/issues/43907, I don't know if it would help streamline the workflow to also have a proper design issue attached to this epic.

**Comment by almeidapaulooliveira** [comment]
@taylorsperry - Created design issue: #44097

**Comment by almeidapaulooliveira** [comment]
True, good job on syncing with the Search team, Becca.
