### ISSUE TITLE
Improve CTAs  - Add CTA to Notebooks & Monitoring

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#43917]
This is an implementation issue for [Epic: Improve CTAs and sign-up flows across domains](https://github.com/sourcegraph/sourcegraph/issues/43239).

Similar to https://github.com/sourcegraph/sourcegraph/issues/43754, we need to add CTAs that link to signup.sourcegraph.com. 

The top section for an un-auth'd user should provide prompts to either "sign in" (to create a Notebook for open source) or "sign up" to create a Notebook for private code. Those links should include metrics that help us track how often they're clicked. 

An auth'd user should see a CTA to create a Notebook for their private code. 

-----------

This is an implementation issue for https://github.com/sourcegraph/sourcegraph/issues/43239.

Similar to https://github.com/sourcegraph/sourcegraph/issues/43754, we need to update the CTAs on the [Monitoring](https://sourcegraph.com/code-monitoring) page. The "Get started with Code Monitors" should link to a dynamic  signup.sourcegraph.com (like Batch Changes and Insights will after https://github.com/sourcegraph/sourcegraph/issues/43754). 

The "Free for registered users" CTA at the bottom of the page should make it clear that this is an option to create code monitors for *open source* code.

**Comment by almeidapaulooliveira** [comment]
- #44097
- [Figma file](https://www.figma.com/file/ScpDpxciO5DeT9YlUGzPUX/UX%3A-Sign-up-journeys-for-auth'd-users?node-id=127%3A951)
