### ISSUE TITLE
Add Request a Demo back to About

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#43956]
We want to add the option to request a demo back to the home page on `/about`, along with the appropriate tracking. 

![Request a demo](https://user-images.githubusercontent.com/43555476/200191268-0eb946cc-8e39-4dd0-b817-2417ae4b6ce6.png)

**Comment by kelsey-brown** [comment]
Chart for measuring is [here](https://analytics.amplitude.com/sourcegraph/chart/bioy9q9)

Planning to revisit this ~18 Nov to make sure demo requests have returned to their pre-removal levels and see if there's been any impact to button clicks for the other CTAs.

**Comment by kelsey-brown** [comment]
- [Demo request clicks](https://analytics.amplitude.com/sourcegraph/chart/bioy9q9/edit/ny46sp2) started to pick up again, though they’re still lower than they were before we started offering cloud trials (which is not surprising). 
- Get free trial button clicks don’t appear to have been meaningfully impacted
- Conclusion: Not much else to see here. I’m going to move this out of measuring.
