### ISSUE TITLE
Improve CTAs - signup.sourcegraph.com follow-up

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#43955]
This is an implementation issue for [Epic: Improve CTAs and sign-up flows across domains](https://github.com/sourcegraph/sourcegraph/issues/43239) and a follow up to https://github.com/sourcegraph/sourcegraph/issues/43750. 

The self-hosted CTA in the "or" block on signup.sourcegraph.com should be more prominent than signing up for a free account. Let's move the self-hosted "or" block up/bold and the free account "or" block down/small, and have both self-hosted links direct to the docs.

**Comment by kelsey-brown** [comment]
The below events merged as part of the linked pull request all have an associated chart on this [dashboard](https://analytics.amplitude.com/sourcegraph/dashboard/jsg5f3q). Moving this to done!

- ClickedOnSelfHostedCTA
- ClickedOnDotComSignUpCTA
- ClickedContinueSignUp, and lastly;
- Signup
