### ISSUE TITLE
Dynamic Contexts from repository metadata

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#43958]
Requested by: https://github.com/sourcegraph/accounts/issues/3

#### Feature request description

[Search Contexts](https://docs.sourcegraph.com/code_search/how-to/search_contexts) allow users to reduce the scope of their search query.  However, they must be created manually and be kept up-to-date manually.   This is a challenge for larger organizations where new repositories are coming in and out of Sourcegraph daily.  

It would be great if contexts could be created and maintained dynamically.   What would be great is if the repository object had metadata associated with it that could be updated via an API (or perhaps by syncing directly from code hosts).  A simple "tag" would allow administrators to tag a repository with a key/value pair.  For example, a repository could be tagged with "team=my_team",  "group=my_group", "director=my_director", etc.  

Once you have metadata tied to a repository, the contexts could then use that metadata.  For example, a context could be created for all repositories that are tagged with "team=my_team" or all

Additionally, it would be great if we can allow users to filter queries by metadata without a context too.  Something like `repo:hastag(team=my_team) TODO`.

#### Is your feature request related to a problem? If so, please describe.

Large organizations like https://github.com/sourcegraph/accounts/issues/3 have 10s and 100s of thousands of repositories.  As Sourcegraph examples to different lines of businesses within these organizations, it becomes challenging for users to see just "their code" (or the code they are interested).  

#### Describe alternatives you've considered.

https://github.com/sourcegraph/accounts/issues/3 has automated the creation of contexts.  But, that is also time consuming with their scale.  And, it's an administrative burden to manage a script to do this step.  This script must be monitored and checked regularly for errors.

#### Additional context

Similar request: https://github.com/sourcegraph/sourcegraph/issues/40508

/cc @sourcegraph/search-product

**Comment by limitedmage** [comment]
@rvantonder @novoselrok What is the cost of supporting repo metadata for search-query-based contexts?

**Comment by alexfogg** [comment]
Adding a link to these [two slides](https://docs.google.com/presentation/d/1U0mJHoilylEqr_GWUNrh5swYy2ffzBz2mvZXhQRRvCQ/edit#slide=id.g184f48d9be9_0_0) to provide additional visual context into why this is so painful for https://github.com/sourcegraph/accounts/issues/3 and what the ideal state we've heard them ask for.

**Comment by tbliu98** [comment]
@mike-r-mclaughlin Use of `repo:has()`, `repo:has.tag()`, and `repo:has.key()` in the creation of query-based search contexts will be enabled in 4.3 (see #44897)

**Comment by limitedmage** [comment]
@tbliu98 can we close this issue as completed?

**Comment by tbliu98** [comment]
Closing as this has been implemented in https://github.com/sourcegraph/sourcegraph/pull/44897
