### ISSUE TITLE
Observability: Additional garbage with our Honeycomb metrics from CI

### ISSUE THREAD

**Issue by burmudar** [sourcegraph/sourcegraph#43977]
If we look at our CI metrics that gets sent to Honeycomb we see a lot of extra fields that don't make sense or fields that are cut off. We need to investigate why this happens and implement a fix.

<img width="202" alt="Screenshot 2022-11-05 at 16 59 03" src="https://user-images.githubusercontent.com/1001709/200126576-62fc3f42-a5f3-4075-a5ab-5f2d74b2ae62.png">

**Comment by marekweb** [comment]
I'm investigating the hypothesis that this is coming from the buildkite message being parsed incorrectly as trace fields
