### ISSUE TITLE
Observabillity: Investigate move Honeycomb v1 datasets to v2

### ISSUE THREAD

**Issue by burmudar** [sourcegraph/sourcegraph#43978]
Some of our datasets in Honeycomb still use "Honeycomb classic" and we're missing out on features. We should try see what is involved with moving to the new v2 dataset.

**Comment by marekweb** [comment]
Docs: https://docs.honeycomb.io/honeycomb-classic/migration/

**Comment by burmudar** [comment]
In general to use v2 requires us to use a new API key and then when our events use this API key they'll be tied to the v2 dataset.

The move is not so simple. We currently have a 'split brain' 🧠  with our observabillity. Somethings use OpenTelemetry and get exported by the Otel Collector. While others use `libhoney` and directory export to Honeycomb.

The `libhoney` code should be moved over to use the Open Telemetry stac. We have to reach out to stake holders who currently use `libhoney` and rely on it and ensure they'll still get what they currently get just via using OpenTelemetry.

So open tasks:
- [ ] Talk to stakeholders and inform them of the _intention_ to move to v2. Maybe get them to use the v2 API key then technically, the only thing that changes is _how_ the traces are shipped to Honeycomb
- [ ] Migrate libhoney (large body of work)
