### ISSUE TITLE
Add ability to move "filter sidebar" back to the left side

### ISSUE THREAD

**Issue by RichardBelzer** [sourcegraph/sourcegraph#43976]
I recently upgraded sourcegraph from 3.41 to 4.1.2 and noticed that the "filter sidebar" appears on the right side after performing a search. It has always been on the left side, so I'm not sure when it was defaulted to the right side now. This is a feature request for making a configuration option to put the filter sidebar back on the left side.

/cc @sourcegraph/search-product

**Comment by RichardBelzer** [comment]
Another argument for it being back on the left side: When you search in Sourcegraph, your search results are only clickable the left side so you have to click there. If the filters are all the way on the right side, it's more distance for your mouse to constantly be moving, especially if you keep manipulating filters on the right and clicking results on the left. A lot of back and forth.

This UI/UX issue is amplified if you have an ultrawide monitor.

**Comment by limitedmage** [comment]
cc @almeidapaulooliveira

**Comment by camdencheek** [comment]
Closing since the filters panel is now on the left again. cc @taiyab for thoughts on whether this should be configurable.
