### ISSUE TITLE
Improve CTAs - Add CTA to Monitoring

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#43989]
This is an implementation issue for https://github.com/sourcegraph/sourcegraph/issues/43239.

Similar to https://github.com/sourcegraph/sourcegraph/issues/43754, we need to update the CTAs on the [Monitoring](https://sourcegraph.com/code-monitoring) page. The "Get started with Code Monitors" should link to a dynamic  signup.sourcegraph.com (like Batch Changes and Insights will after https://github.com/sourcegraph/sourcegraph/issues/43754). 

The "Free for registered users" CTA at the bottom of the page should make it clear that this is an option to create code monitors for *open source* code.

**Comment by almeidapaulooliveira** [comment]
- #44097 
- [Figma file](https://www.figma.com/file/ScpDpxciO5DeT9YlUGzPUX/UX%3A-Sign-up-journeys-for-auth'd-users?node-id=127%3A952)

**Comment by st0nebraker** [comment]
Closing to combine into #43917
