### ISSUE TITLE
Replace "Use Sourcegraph" / "Search code" button with link to Sourcegraph.com

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#43990]
The "Use Sourcegraph" and "Search Code" buttons in the nav bar on about feel confusing (it's "Use Sourcegraph" on the home page and "Search code" on all the other pages). It's not clear how "Use Sourcegraph" is different from a "free trial" (the other nav bar CTA) and "Search code" is pretty vague. 

Let's remove the Use Sourcegraph/Search Code button and have the first link in the nav bar say "Sourcegraph.com" and link to sourcegraph.com/search (with tracking). 

![Image](https://user-images.githubusercontent.com/43555476/200191718-c150fe33-3e06-41b8-bbe0-2884a675c88c.png)

**Comment by bretthayes** [comment]
@taylorsperry a lot of people have actually clicked on the `Search code` button when that's what the CTA text was before. I remember @jdorfman had some folks on Twitter wondering where the button went and how they could get back to dotCom when we changed it to `Use Sourcegraph`.

Having `Sourcegraph.com` as a text link right after the Sourcegraph logo looks a bit weird. It looks a bit better after `Docs` but thoughts on changing the wording here? Maybe `Search open source` instead would make more sense?

![Screen Shot 2022-11-10 at 5 54 53 PM](https://user-images.githubusercontent.com/1733936/201223200-a0f83ff6-240c-4c30-9833-825ce239257a.png)
![Screen Shot 2022-11-10 at 5 55 07 PM](https://user-images.githubusercontent.com/1733936/201223202-b73527b7-50df-4f90-af7d-ca2b778bbc82.png)
![Screen Shot 2022-11-10 at 5 55 21 PM](https://user-images.githubusercontent.com/1733936/201223205-94af1c65-5d8c-4ce7-8dc5-62d374256a16.png)

**Comment by taylorsperry** [comment]
Hm, I see what you mean. If "Search code" was working, then we don't need to reinvent the wheel here. Thank you for the context!

**Comment by bretthayes** [comment]
Sounds good! Shall we keep the outline button as is with `Search code`, or move it to a text link at the end of the nav items?

![Screen Shot 2022-11-10 at 6 12 41 PM](https://user-images.githubusercontent.com/1733936/201225512-2fc3afe2-593f-4ce6-bd71-015922e57b18.png)

**Comment by bretthayes** [comment]
@taylorsperry sounds good! Shall we keep the outline button as is with `Search code`, or move it to a text link at the end of the nav items?

![Screen Shot 2022-11-10 at 6 12 41 PM](https://user-images.githubusercontent.com/1733936/201225512-2fc3afe2-593f-4ce6-bd71-015922e57b18.png)

**Comment by taylorsperry** [comment]
Hm, I kind of like it in the nav bar (feels a little cleaner?) but WDYT?

**Comment by bretthayes** [comment]
@taylorsperry yeah it does look clean as a text link. Is that what you mean? I just hope folks don't miss it or go looking for it again compared to the outline button. But it does emphasize the "Get free trial" button now. We could experiment this and see if we get a spike in trials after this PR merge. We can compare it against the `Search code` text link.

**Comment by taylorsperry** [comment]
Oh duh, "nav bar" is both--sorry. I did mean the text link. Let's give it a try and see if it boosts trials (or if @jdorfman gets more questions about how to get to .com).

**Comment by jdorfman** [comment]
@taylorsperry the text link worked great before but I will let you know if it is an issue
