### ISSUE TITLE
Show file/path results on searches where the `file:` filter is specified

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#44]
- Issue type: bug report
- Sourcegraph version: sourcegraph.com

Reported by a user, file/path results don't show if the search query is specified in the `file:` filter

Steps to reproduce:

1. Try searching both:
https://sourcegraph.com/search?q=repo:github%5C.com/Microsoft/vscode+file:referencesearch.ts
and
https://sourcegraph.com/search?q=repo:github%5C.com/Microsoft/vscode+referencesearch.ts

2. Note that the first search returns nothing but suggestions, while the bottom one returns, as expected, the desired file.

**Comment by sqs** [comment]
This works as expected now
