### ISSUE TITLE
GitHub organization repos are not shown in list and updated

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#440]
This is a regression in the GitHub.com GraphQL API. See https://platform.github.community/t/unable-to-fetch-users-repositories-by-organization-membership/7557

This affects all versions of Sourcegraph. The GitHub API is not returning the repositories that a user is affiliated with. This leads to us not syncing the repositories. For most installations, this is the vast majority of repositories. For example Sourcegraph's own dogfood instance usually indexes 100s of github repositories, is now only indexing 3.

We have not yet had reports about this affecting GHE codehosts.

We do not yet have an ETA on a fix from GitHub, so we should work around the upstream issue. Likely by adjusting the query we run.

**Comment by nicksnyder** [comment]
I am going to cut a new release 2.12.1

**Comment by nicksnyder** [comment]
2.12.1 appears to not work for GitHub Enterprise (e.g. 2.14.7), but 2.12.0 does. This needs further investigation so we can find a solution that works for both.

@KattMingMing can you any other relevant details from your testing?
