### ISSUE TITLE
Drop column `repo_status` from `gitserver_repos` table

### ISSUE THREAD

**Issue by indradhanush** [sourcegraph/sourcegraph#44009]
We [recently](https://github.com/sourcegraph/sourcegraph/pull/42846) added the `repo_status` column. 

This was the first step towards identifying and fixing corrupted repos. https://github.com/sourcegraph/sourcegraph/issues/42213

However, this wasn't so well thought and we should revisit this, especially since the source of repo corruption (sg maintenance) was [disabled](https://github.com/sourcegraph/sourcegraph/pull/42856) by default for all instances. With this change, putting more effort into fixing repo corruption may not be the best place to focus at the moment.

As a result, we want to remove this column and if at all we want to do this again in the future, we would like to think through this better.

## Examples from the past

- https://github.com/sourcegraph/sourcegraph/pull/27201

### Suggested steps

- [x] Run `sg setup` to ensure local dev instance is working
- [x] Add a new migration to drop the column
  - [x] Check docs for `sg migration`: https://docs.sourcegraph.com/dev/background-information/sg/reference#sg-migration
  - [x] Generate migration with `sg migration add`
  - [x] Write forwards migration file
  - [x] Write backwards migration file
- [x] Verify migration
  - [x] Run `sg migration up` to verify the migration works
  - [x] Run `sg migration downto` or `sg migration undo` to verify the migration works  backwards as well
- [x] Run `sg generate` to update the schema
- [x] Apply the migration one last time to your local dev instance
  - [x] Verify that `sg start` starts up without any errors
- [x] Optional
  - [x] Add a code host connection or update an existing code host connection
  - [x] Trigger a code host sync
  - [x] Trigger a repo sync

/cc @jplahn @ryphil

**Comment by amustaque97** [comment]
I want to work on this issue

**Comment by jasonhawkharris** [comment]
PR: https://github.com/sourcegraph/sourcegraph/pull/44299
