### ISSUE TITLE
Show all Bulk Operations (but disable unavailable operations )

### ISSUE THREAD

**Issue by BolajiOlajide** [sourcegraph/sourcegraph#44017]
[Context 1](https://sourcegraph.slack.com/archives/C03CSAER9LK/p1667817632317469)
[Context 2](https://sourcegraph.slack.com/archives/C03CSAER9LK/p1667817863069249)

This is a two-part request that can be solved at once. We currently compute available bulk operations in the backend whenever a user selects (one or more) changesets, these operations aren't ordered.

We could get away with ordering if we revert to displaying the static list of operations on the frontend (which was ordered), however, we disable the unavailable operations so the user can't carry out those actions.

**Comment by BolajiOlajide** [comment]
Do you have any thoughts on this? @danielmarquespt 

Personally, I think it's a good idea.

**Comment by chrispine** [comment]
love it! P1?

**Comment by courier-new** [comment]
Moved, since there's a consensus. 🙂
