### ISSUE TITLE
No codeintel on go-ethereum

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#4401]
Reported by https://app.hubspot.com/contacts/2762526/contact/16137251

There is no codeintel on https://github.com/ethereum/go-ethereum/blob/master/eth/sync.go

I tested with the latest extension on master.

Error in console:

```
errors.tsx:55 Uncaught Error: rev 19fa9064d713369796da01ed3299a9b8f5a58401 not found
    at MapSubscriber.project (backend.tsx:80)
    at MapSubscriber._next (map.ts:85)
    at MapSubscriber.Subscriber.next (Subscriber.ts:100)
    at MapSubscriber._next (map.ts:90)
    at MapSubscriber.Subscriber.next (Subscriber.ts:100)
    at SwitchMapSubscriber.notifyNext (switchMap.ts:167)
    at InnerSubscriber._next (InnerSubscriber.ts:18)
    at InnerSubscriber.Subscriber.next (Subscriber.ts:100)
    at subscribeToPromise.ts:10
```

**Comment by lguychard** [comment]
The rev is correctly detected by the browser extension, but sourcegraph.com doesn't have it yet (it only has `645756cda5becf364ec9442891e9b7a7945e2cb3`, from two days ago).

Code intelligence works correctly on the [`release/1.8`](https://github.com/ethereum/go-ethereum/blob/release/1.8/eth/sync.go) branch:
![image](https://user-images.githubusercontent.com/1741180/59044112-cd68d580-887d-11e9-8f14-8791eace85e4.png)

**Comment by felixfbecker** [comment]
So we don't handle clone in progress correctly? Or we don't trigger it maybe?

**Comment by lguychard** [comment]
We receive `cloned: true` from the graphQL backend, but with a `null` commit. We correctly throw a `RevNotFound` error as a result :

![image](https://user-images.githubusercontent.com/1741180/59044532-95ae5d80-887e-11e9-9185-15ddfbe2a409.png)

I'm not sure what the update strategy is for public repos on sourcegraph.com. @sourcegraph/core-services maybe you can shine a light here?

**Comment by tsenart** [comment]
> I'm not sure what the update strategy is for public repos on sourcegraph.com. @sourcegraph/core-services maybe you can shine a light here?

In sourcegraph.cpm, repos are updated on demand when users visit them.

**Comment by lguychard** [comment]
@tsenart is that just for the initial clone, or is visiting an already cloned repo supposed to schedule an update as well?

**Comment by felixfbecker** [comment]
@tsenart how is a "visit" defined? One could argue a visit through the browser extension is a visit too, but it seems like a GraphQL request does not trigger a clone.

**Comment by tsenart** [comment]
> @tsenart is that just for the initial clone, or is visiting an already cloned repo supposed to schedule an update as well?

It should trigger an update as well.

> @tsenart how is a "visit" defined? One could argue a visit through the browser extension is a visit too, but it seems like a GraphQL request does not trigger a clone.

Which GraphQL resolver is this?

**Comment by felixfbecker** [comment]
I'd guess `resolveRev`. @lguychard?

**Comment by lguychard** [comment]
Indeed: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/browser/src/shared/repo/backend.tsx#L56-65

**Comment by felixfbecker** [comment]
Ping @tsenart 🙂 Do you happen to know whether the backend expected to update the repo on the above GraphQL request too? Or only on actual sourcegraph.com browser page visits?

**Comment by unknwon** [comment]
> whether the backend expected to update the repo on the above GraphQL request too?

I think yes, if GraphQL asks for the commit (which we do based on https://github.com/sourcegraph/sourcegraph/issues/4401#issuecomment-499911413):

```graphql
repository(name: $repoName) {
	...
	commit(rev: $rev) {
		oid
	}
}
```

**Comment by keegancsmith** [comment]
There is indeed a regression here. Fixed at https://github.com/sourcegraph/sourcegraph/pull/9500
