### ISSUE TITLE
Observabillity: Investigate why structured logs are not being processed properly on s2

### ISSUE THREAD

**Issue by burmudar** [sourcegraph/sourcegraph#44016]
We've moved to using structured logs but they logs are not properly parsed in providers like GCP. We need to investigate why this is happening.

**Comment by bobheadxi** [comment]
@burmudar previous discussion: https://sourcegraph.slack.com/archives/CMBA8F926/p1667491800552439?thread_ts=1667489917.928899&cid=CMBA8F926

tl;dr

> 8s uses fluentd directly, which supports json detection, whereas the gcplogs driver we use in Cloud and docker-compose doesn't seem to. Likely to be resolved out-of-the-box with Cloud v2

**Comment by burmudar** [comment]
@bobheadxi Thanks! I'll definitely hit you and @michaellzc up once we start on this
