### ISSUE TITLE
Bitbucket Server "Failed to update" errors in logs (logspam?)

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#4402]
- **Sourcegraph version:** 3.4.0
- **Platform information:** Bitbucket Server

Reported by https://app.hubspot.com/contacts/2762526/company/557889642

>We have a lot of errors like this in our log:
>
>`Jun 06 01:19:49 ENG-AUS dockerd-current[6391]: 06:19:49          gitserver | t=2019-06-06T06:19:49+0000 lvl=eror msg="Failed to update" repo=org/repo error="exit status 128" output="fatal: unable to access 'https://username:token@bitbucket.example.com/scm/path.git/': transfer closed with outstanding read data remaining\n"`
>
>And like this:
>
>`Jun 06 01:07:40 ENG-AUS dockerd-current[6391]: 06:07:40          gitserver | t=2019-06-06T06:07:40+0000 lvl=eror msg="Failed to update" repo=org/repo error="exit status 128" output="fatal: https://username:token@bitbucket.example.com/scm/path.git/info/refs not valid: is this a git repository?\n"`
>
>We are currently using SC version 3.4.0, but we had this problem even before. It’s interesting because I would say “all” of our repos fail like this, but only occasionally, because when I take a look on some repository cloned in SourceGraph I can see it’s been cloned before some hours without any issue. So basically everything is working on frontend, but we would like to take rid of those errors. I’ve also contacted Atlassian support, as this is probably issue on Bitbucket side.

**Comment by keegancsmith** [comment]
So they want us to not spam the logs, even though it is indicating a real issue? Can they not filter this out in there log consumer? It would be a bit strange for us to add specific code to make this log line configurable.

**Comment by dadlerj** [comment]
The response from the user made me think the error was a red herring, and the repo WAS actually being updated (on the frontend). I can confirm that though.

**Comment by tsenart** [comment]
@dadlerj: Can this be closed?
