### ISSUE TITLE
Tooling: Log outgoing requests

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#44027]
We want to log all outgoing requests from Sourcegraph, and make them discoverable on the web UI.
Original initative by @mrnugget.

Goals:
 - Raise awareness of requests in dev mode. **Developers** should raise their eyebrows when there are bursts of requests.
 - Allows **admins** to see what’s happening and what the requests are.
 - Make it easy to **duplicate** these requests for debugging purposes: Add options to retry/rerun each request. Add “copy as curl” to each request.

Details:
- Could hook into `httpcli.NewExternalClientFactory` to ensure that every request to the outside of Sourcegraph is logged.
- We want to plan to **Redis**.
- We can keep the last **50 requests** or so **per external host**.
- We want to strip out **security**-relevant data.
- We want to record the **caller**, by going up the stack frame and finding it.
- **Enable** logging these requests by default in developer mode. 
- We want a page that shows the last 50 requests per external host on the admin **UI**. Just by looking at the URL, it’s often easy to tell whether something fetches permissions, repos, code, or something else.

/cc @sourcegraph/integrations

**Comment by vdavid** [comment]
Hey @ryanslade!

@mrnugget and I kicked off this effort, in line with what he wrote in his [Invest in tooling](https://docs.google.com/document/d/1_pZB1AAqUyftP4R4L_4UmEQcGmuenh8ZLppTGXRNeo0/edit#) doc earlier.
Before jumping into it, I wanted to make sure that I'm not duplicating any work, and I found your issue https://github.com/sourcegraph/sourcegraph/issues/43560 which has been pretty active lately. So I'm reaching out.

The main similarity between our projects is that we both want to log outgoing requests.

The differences that I'm seeing between our projects:
 - I intend to catch **all** requests, not just the ones made at code host sync. This means that the data I'm logging might be less specific and might not be enough for your needs. (But we could tweak it to make the logged data structure flexible enough to suit your team's needs.)
 - I intend to store the data in **Redis**, not the DB or elsewhere. (But this is flexible so far.) Related to this, I probably intend to store the data for less time.
 - I intend to strip **sensitive info**, and my understanding is that you want to save it. (But this might be flexible, too.)

For me, this would be my first real back-end work at Sourcegraph (with some front-end elements, that is, the UI), and I'm doing it as a four- to six-week effort, tops.
I've just started this and at this point, I don't have enough context to take a good enough guess whether it makes sense to join these efforts, and how.

I wanted to ask you about your thoughts on how our initiatives overlap, how we can make sure we're strengthening each other the most rather than making each other's work redundant, and whether you maybe feel like working together on this in some way or another.
Feel free to take this convo to Slack if you prefer a shorter form or a more private discussion. I defaulted to transparency because I saw no problems with sharing this publicly.

**Comment by ryanslade** [comment]
Hey @vdavid, thanks for the detailed writeup and reaching out 😄 

First off, what I've done so far was just a quick proposal and I'm not sure how much time I'm going to have to actually push it over the line, assuming other's are happy with the approach. I'm not sure if you saw the [PR](https://github.com/sourcegraph/sourcegraph/pull/43664/files) with a very basic implementation, maybe you can get some inspiration from that? 

To your points above:

* When you say you're logging all outgoing requests, do you mean also inter service requests? For example API calls between `repo-updater` and `gitserver`? 
* Storing the data for less time is fine, the initial use case will be mainly for debugging issues that are happening at "now".
* How will you identify sensitive data? This may be trickiest things to figure out IMO. In our case we were only really worried about exposing the code host API tokens and we knew what those were up front so they would be easy to redact.

Plan sounds good to me :)

**Comment by mrnugget** [comment]
Just to chime in here:

> * When you say you're logging all outgoing requests, do you mean also inter service requests? For example API calls between `repo-updater` and `gitserver`?

The idea is to modify the [`ExternalClientFactory`](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/httpcli/client.go?L96&subtree=true), so it would cover all requests made to external services.

> How will you identify sensitive data? This may be trickiest things to figure out IMO. In our case we were only really worried about exposing the code host API tokens and we knew what those were up front so they would be easy to redact.

I think it's fine to not log HTTP basic auth (username/password) and then not log headers. I'm 99% sure we don't send tokens in query parameters, for example.
