### ISSUE TITLE
Upgrade p4-fusion to version 1.12

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#44030]
Upgrade the version of p4-fusion that we use in our `gitserver` and `server` images.

Instructions [here](https://handbook.sourcegraph.com/departments/engineering/teams/repo-management/upgrade-p4-fusion/)

The 1.12 release is [here](https://github.com/salesforce/p4-fusion/releases/tag/v1.12)

/cc @jplahn @ryphil

**Comment by jasonhawkharris** [comment]
PR: [#44301](https://github.com/sourcegraph/sourcegraph/pull/44301)
