### ISSUE TITLE
insights: migrate backfill_completed_at

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#44039]
Deprecate the old background routine and migrate backfill_completed_at to use the new stateful backfiller

/cc @joelkw @felixfbecker @vovakulikov

**Comment by coury-clark** [comment]
p1

**Comment by chwarwick** [comment]
grab but dependent on full cutover to new backfiller.

**Comment by chwarwick** [comment]
replaced by https://github.com/sourcegraph/sourcegraph/issues/45008
