### ISSUE TITLE
Add handlers for permissions syncing through GitHub webhooks

### ISSUE THREAD

**Issue by pjlast** [sourcegraph/sourcegraph#44032]
This doc outlines how webhooks should be used for permissions syncing: https://docs.google.com/document/d/1BkE-42jXJNOHDn0h3txwFpmfyBPaN189yLvYLj7v9pE/edit#

/cc @sourcegraph/iam

**Comment by malomarrec** [comment]
Hey @pjlast, this issue didn't have a team label. Given you created it, I assigned you and added your team label. Feel free to unassign yourself. If this is not the right label, can you make sure to add the right one?
