### ISSUE TITLE
Bitbucket Server docs shouldn't say SSH cloning isn't an option

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#4405]
https://docs.sourcegraph.com/admin/external_service/bitbucket_server#https-cloning indicates that SSH cloning isn't available

But it is, via the `gitURLType` schema option (search that page for it).

I leave it up to the core team to decide what this should say instead.

**Comment by keegancsmith** [comment]
This seemed to have been a bad rewording in https://github.com/sourcegraph/sourcegraph/pull/2279

Originally it read

> SSH cloning is not used by default and as such you do not need to configure SSH cloning.
