### ISSUE TITLE
1st permissions scale test - without permissions

### ISSUE THREAD

**Issue by kopancek** [sourcegraph/sourcegraph#44077]
Child of
- #40327

In order to compelte this, we need to:

- [ ] Define the scale test ([doc here](https://docs.google.com/document/d/1vj2gixi6sh2KneGvzibE_pRXtmGcV3Ofv1yn-jiAjOw))

- [ ] Implement a script to run it
- [ ] Perform the test and collect data

/cc @sourcegraph/source/iam

**Comment by mrnugget** [comment]
Closing because we did thisone rate limit for all code hosts that use [github.com](http://github.com/) for example?
