### ISSUE TITLE
4.1.3 Security approval

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#44079]
Security must close this issue before releases. It is the responsibility of the Security Engineer on rotation the week the release is cut. More steps will be added in the future.

- [x] All feasible CVEs are closed.
- [x] Any open CVEs are documented in the handbook.

cc @sourcegraph/security

Release tracking issue: https://github.com/sourcegraph/sourcegraph/issues/44078

**Comment by mohammadualam** [comment]
All current accepted open CVEs are documented in the handbook.
