### ISSUE TITLE
Pathname "..." could not be decoded. This is likely caused by an invalid percent-encoding.

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#4408]
#### Steps to reproduce:

1. Run latest `sourcegraph/server` `insiders` build (https://github.com/sourcegraph/sourcegraph/commit/9e3604b92a36a8a7b2670326a37ad5493a8154f2 at this time of writing)
2. Add a github.com external service with the https://github.com/ggilmore/q-test repository

```js
{
  "url": "https://github.com",

  // token: GitHub API access token. Visit https://github.com/settings/tokens/new?scopes=repo&description=Sourcegraph
  // to create a token with access to public and private repositories
  "token": "REDACTED",
  "repositoryQuery": [
  	"none"
  ],
  "repos": [
    "ggilmore/q-test"
  ],

}
```

Run a search for "test": http://localhost:7080/search?q=test

See the following error:

![Screen Shot 2019-06-06 at 3 01 59 PM](https://user-images.githubusercontent.com/9022011/59069471-0e57ee80-886c-11e9-85d1-9795161434d5.png)

```
Pathname "/github.com/ggilmore/q-test@82c0b5724db782d5983ac8aace4635762266e892/-/blob/Geoffrey's random queries.32r242442bf/% token.4288249258.sql" could not be decoded. This is likely caused by an invalid percent-encoding.
```

Visiting http://localhost:7080/github.com/ggilmore/q-test directly shows the same error message.

I am assuming that this is some URL decoding issue?

Assigning to @felixfbecker for triaging

**Comment by felixfbecker** [comment]
What's the console output?

**Comment by keegancsmith** [comment]
You can just visit https://sourcegraph.com/github.com/ggilmore/q-test to see the error. The backend seems to be handling this fine. However, I am unsure if it needs to do some escaping, etc. Here is the response from the tree request

```json
{
  "data": {
    "repository": {
      "commit": {
        "tree": {
          "entries": [
            {
              "name": "Geoffrey's random queries.32r242442bf",
              "path": "Geoffrey's random queries.32r242442bf",
              "isDirectory": true,
              "url": "/github.com/ggilmore/q-test/-/tree/Geoffrey's random queries.32r242442bf",
              "submodule": null,
              "isSingleChild": true
            },
            {
              "name": "% token.4288249258.sql",
              "path": "Geoffrey's random queries.32r242442bf/% token.4288249258.sql",
              "isDirectory": false,
              "url": "/github.com/ggilmore/q-test/-/blob/Geoffrey's random queries.32r242442bf/% token.4288249258.sql",
              "submodule": null,
              "isSingleChild": false
            }
          ]
        }
      }
    }
  }
}
```

**Comment by felixfbecker** [comment]
Yeah that `url` field has spaces in it, which is clearly not valid for a URL. This is a backend issue therefor

**Comment by felixfbecker** [comment]
This file is also affected by https://github.com/sourcegraph/sourcegraph/issues/4421

**Comment by keegancsmith** [comment]
@felixfbecker To reproduce the issue with `path` visit https://sourcegraph.com/github.com/ggilmore/q-test/-/tree/Geoffrey's%20random%20queries.32r242442bf and click on the file `% token.4288249258.sql`

**Comment by felixfbecker** [comment]
I tracked it down to a bug in `history` (used by `react-rotuer`) which was fixed 3 months ago but is unreleased: https://github.com/ReactTraining/history/issues/505

**Comment by slimsag** [comment]
https://app.hubspot.com/contacts/2762526/company/407948923 just ran into this as well, see https://sourcegraph.slack.com/archives/C0W2E592M/p1560281236044600
