### ISSUE TITLE
UX: Sign-up journeys for auth'd users

### ISSUE THREAD

**Issue by almeidapaulooliveira** [sourcegraph/sourcegraph#44097]
### This is a design issue of this Epic:
- #43905

## Define
We have several opportunities to engage users with a [Sourcegraph account (See the full context and support data here).](https://docs.google.com/document/d/1LfsHVvoMvlyVYdT3BTV275vRdN-h8RUt6U4tlqyhecg/edit#bookmark=id.y69jjy0pos0)

`Hypothesis:` We must engage users when trying to use a feature they want access to. For example, a user is trying to link their private repos, create a Batch Changes specs or create a Code Insights. They perceive the value of it and are willing to do it. We unlocked the value and need to settle it, driving them to sign up for a cloud trial.

## Design
- [x] Batch Changes journey ([Figma file](https://www.figma.com/file/ScpDpxciO5DeT9YlUGzPUX/UX%3A-Update-context%3Aglobal?node-id=1%3A53)).
- [x] Insights journey ([Figma file](https://www.figma.com/file/ScpDpxciO5DeT9YlUGzPUX/UX%3A-Update-context%3Aglobal?node-id=1%3A1877)).
- [x] Context dropdown journey ([Figma file](https://www.figma.com/file/ScpDpxciO5DeT9YlUGzPUX/UX%3A-Update-context%3Aglobal?node-id=1%3A2693)).
- [x] Notebooks journey ([Figma file](https://www.figma.com/file/ScpDpxciO5DeT9YlUGzPUX/UX%3A-Sign-up-journeys-for-auth'd-users?node-id=127%3A951))
- [x] Code Monitoring journey ([Figma file](https://www.figma.com/file/ScpDpxciO5DeT9YlUGzPUX/UX%3A-Sign-up-journeys-for-auth'd-users?node-id=127%3A952))
- [x] CTA on all search results pages ([Figma file](https://www.figma.com/file/ScpDpxciO5DeT9YlUGzPUX/UX%3A-Sign-up-journeys-for-auth'd-users?node-id=128%3A1587)).
- [x] Designer review.

## Measure
Our [key metric](https://docs.google.com/document/d/1-M1iM-rCCZk0aPDx78ARWLxBbbGSVup_3hVVa1mG8Xo/edit?pli=1#bookmark=id.a0uyr0duh63g) is activations. We'll configure pings that form tracking funnels for the three activation journeys above and measure how they convert over time.

  - [x] Track different events to see how users are interacting ([Figma page](https://www.figma.com/file/ScpDpxciO5DeT9YlUGzPUX/UX%3A-Sign-up-journeys-for-auth'd-users?node-id=1%3A2316)).

## Design process (Size: XS)
- Estimate: two days
- Weighting factors:
  - LOW risk
  - MEDIUM clarity

**Comment by rrhyne** [comment]
@almeidapaulooliveira, is code monitoring not in scope?

**Comment by almeidapaulooliveira** [comment]
@rrhyne - [Monitoring](https://www.figma.com/file/ScpDpxciO5DeT9YlUGzPUX/UX%3A-Sign-up-journeys-for-auth'd-users?node-id=127%3A952) and [Notebooks](https://www.figma.com/file/ScpDpxciO5DeT9YlUGzPUX/UX%3A-Sign-up-journeys-for-auth'd-users?node-id=127%3A951).
