### ISSUE TITLE
Add PageRank announcement to .com

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#44112]
[Figma](https://www.figma.com/file/XJKAYHao1pf1xgv2nEA4vF/UX%3A-Announcements-component-for-.com?node-id=25%3A1427#302844373)

As a non-developer, we'd like to easily make brief announcements for new content on dotcom's homepage.

**Acceptance criteria**:
- Make a component that intakes 4 props ((1) The non-linked text, (2) the linked text, (3) the link destination, (4) the end date)
- Announcement should have an expiration date to not show after, to avoid stale callouts
- First use case: Advert our improved PageRank-backed search results. Context in this [thread](https://sourcegraph.slack.com/archives/CHXHX7XAS/p1667843373046269). 

Related design issue: https://github.com/sourcegraph/sourcegraph/issues/44108

**Comment by st0nebraker** [comment]
Paused in lieu of using global admin settings for notices to achieve this goal. Exploring & Taylor will follow up to add handbook documentation.

**Comment by st0nebraker** [comment]
Closed in [this PR](https://github.com/sourcegraph/deploy-sourcegraph-cloud/pull/17473). Takeaways: These notices must be updated on a different repo [here](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/deploy-sourcegraph-cloud/-/blob/overlays/prod/frontend/files/global-settings.json?L77) to change on dotcom. Docs on markdown syntax [here](https://docs.sourcegraph.com/admin/config/settings#notices)
