### ISSUE TITLE
`Uncaught Error: Extension context invalidated` in content script after browser extension got updated

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#4413]
Browser: Chrome Version 74.0.3729.169 (Official Build) (64-bit)

I was reviewing https://github.com/sourcegraph/sourcegraph/pull/4403/files and whenever I hovered over a symbol I only got a spinner.

Opening the console I see the following error, multiple times:

```
Uncaught Error: Extension context invalidated.
    at Object.send (inject.bundle.js:149)
    at MessagePort.t.onmessage (inject.bundle.js:149)
send @ inject.bundle.js:149
t.onmessage @ inject.bundle.js:149
```

Live footage:

![extension](https://user-images.githubusercontent.com/1185253/59089433-5f1e2480-890a-11e9-8a80-1e53a3df9c16.gif)

**Comment by lguychard** [comment]
I believe your extension got updated :) This occurs whenever the background page is reloaded, and a new browser extension version got deployed last night. Try a hard reload and let us know if this happens again.

**Comment by mrnugget** [comment]
Wow, yeah, hard reloading fixed it. Is there any way to catch this and let the user know?

**Comment by lguychard** [comment]
We could explore listening to the `onInstalled` event (which is also fired on update), and disconnecting the stale content script + re-injecting when that happens. Some people have [gone down that route](https://stackoverflow.com/questions/10994324/chrome-extension-content-script-re-injection-after-upgrade-or-install/11598753#11598753).

**Comment by fregante** [comment]
There seems to be a solution: https://stackoverflow.com/a/55336841/288906

Or you can catch that error and offer a reload

**Comment by stiti75** [comment]
dgdg

**Comment by stiti75** [comment]
dfgdf

**Comment by Joelkw** [comment]
This is no longer an active bug.
