### ISSUE TITLE
Remove long-held lock in external service syncing

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#44146]
We identified a race condition previously: When an external service sync is started, and the external service is deleted while the sync is still running, the sync will still continue to run (to my understanding, we should validate that).

That was fixed by adding a new advisory lock that is held when deleting an external service and also when syncing it, to make the two operations mutually exclusive.
Since some external service sync jobs can take 17h (Starburst on dotcom), this holds a transaction for 17h. This defers migrations like index creation until the end of that transaction, which can (and has) caused rollout issues. We should find another way that doesn't require long-held transactions to fix this behavior.
Maybe we should just remove sync jobs when deleting external services and that's good enough? Not sure.

/cc @jplahn @ryphil

**Comment by indradhanush** [comment]
We've had some trouble with advisory locks in the past. Sharing for context: https://github.com/sourcegraph/sourcegraph/pull/25383
