### ISSUE TITLE
Implement URL field for mounted files

### ISSUE THREAD

**Issue by BolajiOlajide** [sourcegraph/sourcegraph#44179]
The [`getPathParts`](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@25ddd2c7/-/blob/enterprise/cmd/frontend/internal/batches/httpapi/file_handler.go?L140:6) method in the file handler currently caters for two types of IDs.

1. Unmarshalled Random IDs (sent via the [executor](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@53c394b9a8b52b562f0c41b2ab2576ff1572b969/-/blob/enterprise/cmd/frontend/internal/executorqueue/queues/batches/transform.go?L161:40))
2. Marshalled Random IDs (sent via the UI)

Instead of supporting two different types of ID, it'd be nice if this method supports just one. A good approach would be to implement the `URL` field so it's used by both executors and client when making request to get a file.

**Comment by chrispine** [comment]
sounds like sustaining work! estimate?
