### ISSUE TITLE
Native SSBC execution

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#44183]
Follow-up to https://github.com/sourcegraph/sourcegraph/pull/44034

## Done

Ensure the following works,

- [x] Skippable steps
    - [x] Dynamic skipping (e.g. output of previous step determines if step should be skipped)
    - [x] Hard coded skip
- [x] Workspace File Mounts
    - [x] Binary
    - [x] Script
    - [x] Sub-directory
- [x] File Mounts
    - It is unclear if all variants of file mounts still work. Basic cases do work. Files used to be read-only in src-cli, they aren't now, but content is still reset in between steps. 
    - The assumption that everything operates in `/data` is broken here, because we need to use what executors give us to persist out-of-repo state in between containers (like the step result from the previous step)
- [x] `tee` dependency
    - It depends on `tee` being available in the docker images to capture the cmd.stdout/cmd.stderr properly for template variable rendering
    - Called out in documentation
- [x] Environment Variable Rendering
    - Env-vars are not rendered in their evaluated form post-execution
- [x] Secrets
- [x] File Permissions
    - File permissions are unclear and might be similarly broken to how they are now - or even worse
- [x] Caching
    - Cache keys are not correctly computed if using workspace mounts - the metadataretriever is nil
- [x] Log Outputs
    - We still use log outputs to transfer the AfterStepResults to the Sourcegraph instance, this should finally become an artifact instead. Then, we don't have to rely on the execution_log_entires anymore and can theoretically prune those after some time. This column is currently growing indefinitely.
    - Created [#50538](https://github.com/sourcegraph/sourcegraph/issues/50538) to track this work.

**Comment by courier-new** [comment]
After we switch over running natively by default, we should revisit https://github.com/sourcegraph/sourcegraph/issues/43712.
