### ISSUE TITLE
Settings: Remove additionalFields json validation field

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#44180]
Related Slack [thread](https://sourcegraph.slack.com/archives/C07KZF47K/p1668017087734149)

## Problem 
At the moment we have `additionalFields: false` in the` experimentalFeatures` section in the sourcegraph settings json file. This has two implications
- You can't store any additional fields in the `experimentalFeatures` section (you see an error if you try  to save settings with not allowed fields there)
- Settings editor highlights these not allowed fields in the UI 
<img width="362" alt="Screenshot 2022-11-09 at 19 49 16" src="https://user-images.githubusercontent.com/18492575/200959027-563cafeb-37c9-44e2-91a3-289dc394a376.png">

But this system forces us to have all experimental feature flags all time because we can just delete them because then our settings will become invalid (see point 1 above)

So in order to solve this problem for now we need to remove this `additionalFields: false` from the setting json schema (and also remove the deprecated features flags from the schema since it will become possible). 

/cc @joelkw @felixfbecker @vovakulikov

**Comment by chwarwick** [comment]
backlog

**Comment by limitedmage** [comment]
This should also be addressed for site config. See https://github.com/sourcegraph/sourcegraph/discussions/45232
