### ISSUE TITLE
Support easy AWS/S3 backup for docker instance

### ISSUE THREAD

**Issue by stephenh** [sourcegraph/sourcegraph#442]
The docker instance is amazing to get up and running quickly, but we held off on using it "for real" with the local-only storage since that is so easily lost.

Our ops team had to setup a separate VPC/etc. anyway so also created an EBS/persistent storage for it while in the process, but in general seems like "just point it at an S3 bucket" would have been the easiest thing for us. Even just periodic saves/reloads, e.g. every 5 minutes or after a change or what not would be cool, doesn't have to be super-real-time/etc.

**Comment by sqs** [comment]
Thanks for the idea. What data would you expect to be stored on this persistent storage?

- Database backups (PostgreSQL and Redis) and site configuration
- Cache data (Git repository clones)
- Other things?

For DB backups, would [using an external DB](https://docs.sourcegraph.com/admin/external_database#using-your-own-postgresql-server) on something like RDS that had backups address your problem (and better or worse than an S3 bucket backup)?

**Comment by stephenh** [comment]
Good question; I was primarily thinking of the site configuration data, e.g. whatever config/auth options have been setup in the admin panel + the list of enabled repos (but not the cache data). Basically so that once every ~month when the instance reboots (either on purpose due to an upgrade or not), it can take ~an hour/whatever to fetch the git data it needs, but is otherwise hands-off/back-to-normal by itself.

If the external pg database is all of that (the docs mention the internal user auth data but don't mention the top-level JSON/admin config, so as long as that isn't a file on disk), then yeah, we probably would I have done that; I don't think we realized that there was an "easier-than-EBS" way to get ~good enough cross-restart persistence.

(E.g. maybe even just a hint in the "Install on AWS" doc about "if you want easy cross-container persistence, setup RDS".)

**Comment by sqs** [comment]
Thanks! I added sections to the following docs:

- http://docs.sourcegraph.com/admin/install/docker/aws#using-an-external-database-for-persistence
- http://docs.sourcegraph.com/admin/install/docker/google_cloud#using-an-external-database-for-persistence
