### ISSUE TITLE
Investigate cause behind "no refresh token available" errors

### ISSUE THREAD

**Issue by indradhanush** [sourcegraph/sourcegraph#44207]
We recently started [logging](https://github.com/sourcegraph/sourcegraph/pull/43998) the error instead of ignoring it but this causes log spam and had to [revert](https://github.com/sourcegraph/sourcegraph/pull/44202).

We should investigate the source of the errors.

/cc @sourcegraph/iam

**Comment by pjlast** [comment]
So GitHub OAuth tokens aren't refreshable. So the default implementation of the refresh function there is to return the "no refresh token available" error.

The question here is, what's causing it to enter that code path 🤔 what is marking the refresh token as "expired"?
