### ISSUE TITLE
Search toggles don't have large enough target size (22x22px vs 24x24)

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#44226]
[2.5.8: Target Size (Minimum)](https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum.html) requires buttons/clickable components to be at least 24px x 24px.

> The size of the [target](https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum.html#dfn-target) for [pointer inputs](https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum.html#dfn-pointer-input) is at least 24 by 24 [CSS pixels](https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum.html#dfn-css-pixel), except where:
> 
> - Spacing: The [target offset](https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum.html#dfn-target-offset) is at least 24 CSS pixels to every adjacent target;
> - Equivalent: The function can be achieved through a different control on the same page that meets this criterion.
> - Inline: The target is in a sentence or block of text;
> - User agent control: The size of the target is determined by the user agent and is not modified by the author;
> - Essential: A particular presentation of the target is [essential](https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum.html#dfn-essential) or is legally required for the information being conveyed;

The toggles in the search bar are 22px x 22px and the exceptions don't apply here.

<img width="365" alt="image" src="https://user-images.githubusercontent.com/10532611/201178625-d09fa286-f06e-4aa2-9aba-5e1128b86d69.png">

/cc @sourcegraph/search-product

**Comment by limitedmage** [comment]
FYI @quinnkeast since you were looking into changing the size for these?

**Comment by quinnkeast** [comment]
Ah, thanks for the tag! I'd recently scaled down the size of these buttons to 22px for the sake of visual hierarchy. 

QQ: can we achieve the a11y outcome here with an _interaction area_ of 24px, but a _visual implementation_ of 22px? For example, if the button were 24px but had a 1px internal border that reduced the visual boundary to 22px. 

If so, that'd accomplish both the a11y outcome and the visual hierarchy outcome I was after.

**Comment by limitedmage** [comment]
@quinnkeast Yes, we can do that but it requires a bit extra work to make an invisible but clickable border area. Can we delay this until after the a11y work? Maybe grouped with more searchbox refinements if they're ready by then.

**Comment by quinnkeast** [comment]
Yep, of course!
