### ISSUE TITLE
executors: Randomize Terraform Resource Names

### ISSUE THREAD

**Issue by Piszmog** [sourcegraph/sourcegraph#44239]
In the Terraform Modules ([Google](https://github.com/sourcegraph/terraform-google-executors) and [AWS](https://github.com/sourcegraph/terraform-aws-executors)) some resources are created with hardcoded names. This can cause issue when running terraform against an infrastructure that is already setup with executors or just happen to already have taken the names.

## Done

Avoid hardcoding resource names and add randomness to avoid naming collisions.

**Comment by Piszmog** [comment]
Some work is already being done on this front.
* [Google](https://github.com/sourcegraph/terraform-google-executors/pull/69)

**Comment by eseliger** [comment]
this has come up multiple times, P1? Since we already got a good draft PR for it, I assume this should be 2d at most.

**Comment by eseliger** [comment]
Draft PR is here: https://github.com/sourcegraph/terraform-google-executors/pull/69

**Comment by Piszmog** [comment]
@sanderginn is this complete?

**Comment by sanderginn** [comment]
- Completed with https://github.com/sourcegraph/terraform-aws-executors/pull/73
