### ISSUE TITLE
$CUSTOMER (P3): Make searcher/symbols ephemeral storage persistent; change Deployments to StatefulSets

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#44233]
$CUSTOMER informed us of this issue; ref. https://sourcegraph.slack.com/archives/C02E4HE42BX/p1666970323282099

1. Symbols `SYMBOLS_CACHE_SIZE_MB` should probably be more clearly documented in our deployment templates, either that or we should push codeintel to base this on free disk space. As it stands today, the service will consume a fixed cache size(?) and either stop there, or, if there is not enough space, die as a result.

2. Some clusters do not have multiattach capabilities, which makes the "attach a PVC to a deployment" approach non-viable. We should just make searcher/symbols ephemeral storage actually be persistent, across the board, and document it is just cache space and does not need to be backed up.

Otherwise $CUSTOMER and others will face ephemeral storage limits; and fixing it requires an extensive change (changing deployment to statefulset for persistent volumes) which is hard to maintain across upgrades.

Supersedes https://github.com/sourcegraph/deploy-sourcegraph-helm/pull/195 and https://github.com/sourcegraph/sourcegraph/issues/43493

/cc @sourcegraph/delivery

**Comment by scjohns** [comment]
@slimsag any updates here? I know you said you were planning on working this in the not too distant future.

**Comment by slimsag** [comment]
No update yet, we do want to make this change in the next 1-2 months. It is on our roadmap/radar, and plan on updating the customer once we have an update here.

**Comment by scjohns** [comment]
Helm updates here: [sourcegraph/deploy-sourcegraph/helm#242](https://github.com/sourcegraph/deploy-sourcegraph-helm/pull/242)

**Comment by abeatrix** [comment]
k8s / kustomize can also be found here: https://github.com/sourcegraph/deploy-sourcegraph-k8s
