### ISSUE TITLE
Replace minio

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#44254]
Ref. `#wg-no-minio` in Slack.

/cc @sourcegraph/delivery

**Comment by malomarrec** [comment]
Hey @macraig, it looks like this issue was created by someone outside Sourcegraph. Assigning you to triage it! Please answer and route to the right team by adding their team label, then **remove** the `triage-bot/needs-triage` label

**Comment by slimsag** [comment]
Fixed: https://docs.sourcegraph.com/admin/how-to/blobstore_update_notes
