### ISSUE TITLE
Explore: "slice bounds out of range" on Sourcegraph.com 

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#4426]
- Visit https://sourcegraph.com/explore
- Notice this error at the bottom:

![image](https://user-images.githubusercontent.com/1387653/59142455-c32d0100-897b-11e9-8ef7-cff041007178.png)

Does anyone know where to find this in stackdriver?

cc @sourcegraph/core-services

**Comment by tsenart** [comment]
Shared link in Slack.

**Comment by tsenart** [comment]
This seems to be the culprit: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/repositories.go#L189

**Comment by keegancsmith** [comment]
Cherry-picked onto 3.4 as b3d1d180495d3313038ee1cae82d553aeeb66604 will add a changelog entry for 3.4.4
