### ISSUE TITLE
hover display wrong on struct field with complex tag in golang

### ISSUE THREAD

**Issue by morya** [sourcegraph/sourcegraph#4431]
- **Sourcegraph version:** 
  Sourcegraph.com , date: 2019-06-10
- **Platform information:** 
  firefox 67.0
#### Steps to reproduce:

1. open project
`https://sourcegraph.com/github.com/TruthHun/BookStack@a821c6eda3726157de5ea7a7903431b1fa1f9a7c/-/blob/models/book.go#L36:6`
2. left click the struct `Book`

#### Expected behavior:

normal display of tag content

#### Actual behavior:

and the tag 
```
`orm:"pk;auto;unique;column(book_id)" json:"book_id"`
```
is rendered as `"orm:\"pk\n    uto` , you know `\n`

I think it is overkilled by sql-injection scan or maybe script defend?

**Comment by efritz** [comment]
Doesn't seem to have odd rendering with the current deployment.

<img width="566" alt="Screen Shot 2020-07-27 at 3 19 08 PM" src="https://user-images.githubusercontent.com/103087/88588085-9a9f1500-d01c-11ea-963e-70bc7652ec8a.png">

<img width="566" alt="Screen Shot 2020-07-27 at 3 19 30 PM" src="https://user-images.githubusercontent.com/103087/88588087-9a9f1500-d01c-11ea-85d7-a1ff2c88a542.png">

@morya If you are seeing something different can you re-open and post a screenshot?
