### ISSUE TITLE
Error: RepoLookup: {Repo: $REPO ExternalRepo:<nil>}: http status 500

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#4432]
- **Sourcegraph version:** 3.4.3

Reported by: 
* https://app.hubspot.com/contacts/2762526/company/693777177

#### Steps to reproduce:

A Sourcegraph customer (using Gitolite as code host) sees the following error on repo settings pages after upgrading to 3.4.3 from 3.2.x:

`Error: RepoLookup: {Repo: $REPO ExternalRepo:<nil>}: http status 500`

Will update with more info as available.

**Comment by keegancsmith** [comment]
3.5 will include the error body in the messages now when they hit 500. I would be interested to see why they are hitting 500. Has the customer upgraded yet?

**Comment by dadlerj** [comment]
I believe the customer ultimately was able to get around this by purging their repo table: see https://sourcegraph.slack.com/archives/CFNURMWHE/p1560196497021000?thread_ts=1559869692.013600&cid=CFNURMWHE for details

@slimsag feel free to reopen if there's actually any follow-up required here
