### ISSUE TITLE
insights: make sure search sanitization is not broken with aggregations

### ISSUE THREAD

**Issue by leonore** [sourcegraph/sourcegraph#44375]
follow up on https://github.com/sourcegraph/sourcegraph/pull/44244#issue-1444650499

we need to make sure we don't leak data in search aggregations

/cc @joelkw @felixfbecker @vovakulikov

**Comment by coury-clark** [comment]
Search aggregations follows the same logic as search and does not use the internal actor. After verifying the code path and tests, this is not an issue.
