### ISSUE TITLE
implementation proposal: make regexp opt-in via UI toggle button

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#4438]
This is an implementation proposal for how we would do opt-in regexp searching via a UI toggle button, similar to how almost all editors do it (VS Code, Sublime, etc):

<img src="https://user-images.githubusercontent.com/3173176/59243534-586f0600-8bc5-11e9-9632-f64e5716ef7f.png" width=200></img>

## Goal

It is important to have a common goal. The goal here is to resolve Alice's user story problem that exists today, see below.

## User behavior stories

**a.** Alice is a new user of Sourcegraph and notices the search input gives her errors when typing `NewRouter(` in and wishes it just gave her the results she wanted instead of trying to do regexp.
**b.** Bob has found some useful search results and wants to share them with Alice. He wants to just be able to send her the link and have it show her the same results.
**c.** Carol has some search links from Bob a few months ago like https://sourcegraph.com/search?q=err.*+case:yes and wants those links to be permanent so that she can always refer to them in the future. (the results should always be regexp and case matched).
**d.** Danny has used Sourcegraph for a while and it is a part of his core development workflow. He doesn't want to be surprised by any changes, like Sourcegraph's search syntax changing overnight because it would slow him down.

## Proposal

Alice visits https://sourcegraph.com/search:

-  As a new user, she does not have `"search.forceRegexp": true` set in her settings and therefor the regexp button is off by default.
- When she types `NewRouter(` and presses enter, she gets the URL https://sourcegraph.com/search?q=NewRouter%28&force_regexp=false
- When she lands on the search results page, since `force_regexp=false` in the URL the search is forced to be a literal match just as if she'd written it in quotes. Done.

Bob has found some useful results at https://sourcegraph.com/search?q=NewRouter%28&force_regexp=true or any other URL:

- He copies the URL and shares it with Alice.
- Alice clicks the link, and since `&force_regexp=true` is in the URL the query is executed as regexp. The button also indicates that regexp is on.
- Alice clicks the button to turn regexp off. `"search.forceRegexp": false` is set in her user settings and the page reloads with `&force_regexp=false`.

Carol finds an old Sourcegraph link https://sourcegraph.com/search?q=err.*+case:yes and clicks it:

- There is no `&force_regexp=false` parameter in the URL, so we do not force literal matching and the query is executed as regexp just as before.
- There is no `&force_case=true` parameter in the URL, so we do not force case matching and the query is executed as case-insensitive just as before.

Danny visits https://sourcegraph.com/search after a long weekend and after Sourcegraph was upgraded:

- As a long-time user of Sourcegraph just coming across this new behavior, a dismissible bubble appears next to the buttons telling him: "You can now control regexp, case, etc via these buttons." and regexp is defaulted to _off_.
- Danny likes regexp, so he clicks the button turning it on. This sets `"search.forceRegexp": true` in his user settings.
- If he reloads the page or visits https://sourcegraph.com/search in the future, his user settings are read and the button is on.
- When he searches, since his user settings indicate `"search.forceRegexp": true`, `&force_regexp=true` is added to his search URL and results are regexp-matched ones.

#### What about sharing a search query without the URL?

1. If they want the same results, just share the URL or else the person receiving will have to click the right toggle buttons.
2. We already don't handle this case completely today. For example:
    - `repo:^github\.com/koofr/pb$ u` is not the same as https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/koofr/pb%24+u#7

#### How hard would implementing this be?

It would be 90% frontend code, I would estimate Farhan could do it in a week or two off the top of my head.

#### Wouldn't it be better to just have both result types always show up (i.e. regexp and literal matches)?

I don't think so. I think that doing that and pulling it off effectively would be very complex and tricky because:

1. It is technically more complex to implement.
2. From a product usability standpoint, it challenges a lot of the ways in which we present search results today which in my mind means we need to do some user surveys etc. before being able to commit to it or roll it out fully.

By contrast, my proposal above is built primarily on existing functionality which makes it far easier to implement and doesn't challenge how we present results so we could roll out this change confidently and achieve the same goal.

Immediate challenges that come to mind with the all-result-types approach:

a. How do we display regex and literal matches? How do we differentiate between the two and communicate which it is to users?
b. What do we do for case vs. non-case? Do we also perform case and non-case-sensitive matching all at once?
c. If we're running 4x as many queries (non-regexp, regexp, non-case, case) what does that do to perf?
d. How do we communicate this change to consumers of our API?
    - What about API consumers specifying `count:999999`? How does it affect them?
e. As Danny, I was used to being able to [search my codebase for `new.*`](http://theoa.sgdev.org/search?q=repo:%5E50%5C.112%5C.230%5C.151/TEST/apache--hawq%24+new.*) and getting code results back. Now when I run the same query [I instead first see a bunch of SQL files](http://theoa.sgdev.org/search?q=repo:%5E50%5C.112%5C.230%5C.151/TEST/apache--hawq%24+%22new.*%22) and I am surprised by this.

**Comment by felixfbecker** [comment]
> 2. We already don't handle this case completely today. For example:
repo:^github\.com/koofr/pb$ u is not the same as sourcegraph.com/search?q=repo:%5Egithub%5C.com/koofr/pb%24+u#7

Interesting, what is the difference here?

--------

Some options I would like to see being discussed:

- The toggle would pre-fill `regex:yes`/`no` into the query (it would still be persistent). This is similar to how GitHub issue search pre-fills the search query with `is:issue is:open`.
- When copying from the search query to the clipboard, we intercept the copy event and add a `regex:` operator if needed to the copied text.

**Comment by slimsag** [comment]
> Interesting, what is the difference here?

One jumps you to the 7th result, the other does not. i.e. we do not encode the scroll position in the query.

**Comment by slimsag** [comment]
> The toggle would pre-fill regex:yes/no into the query (it would still be persistent). This is similar to how GitHub issue search pre-fills the search query with is:issue is:open.

This is something I have considered and discussed a bit with Issac, the only downside to it is that queries would quickly expand and be quite verbose:

- You type `NewRouter` and press enter, scroll down slightly
- Your query becomes `NewRouter regex:no case:yes word:yes scroll:1`

Note `regex:no` cannot be omitted because we must maintain regex-on-by-default for the backwards compatability user story (Carol above).

> When copying from the search query to the clipboard, we intercept the copy event and add a `regex:` operator if needed to the copied text.

This sounds reasonable and easy to do.

If my argument about not needing to do this for the MVP is bought, then this would be a nice-to-have and could be done at a later date.

If my argument is not bought, then doing this is quite simple because we are already sending the query in text form like this to the backend so all we would do is intercept the copy event and store the query we would normally send to the backend -- i.e. almost all of the work to support this would already be done.

**Comment by slimsag** [comment]
This was implemented a while ago.
