### ISSUE TITLE
sg: enable starting from a specific commit

### ISSUE THREAD

**Issue by burmudar** [sourcegraph/sourcegraph#44400]
When diagnosing regressions you want to start old commit versions of sourcegraph. Currently it requires you to checkout the repository on the commit you want to test out, but we could pull the docker images for this commit and start them.

We could provide two flags that do this?
Checkout the repository at the commit and start it ... there might be some complications here with the "dev" having to be rolled back to older versions
```
sg start --commit DEADBEEF
```
Pulls the versions at the specified commit from docker and starts it, the benefit here is that the dev environment will not have to rolled back and is unaffected
```
sg start --commit DEADBEAF --docker
```

**Comment by jhchabran** [comment]
todo @mucles ask in the context of esc-eng to Application Engineers if that would be valuable (to debug stuff from old customers)
