### ISSUE TITLE
Update signup page to remove code hosts and streamline options

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#44418]
After talking to @jdorfman and @malomarrec we're going to run an A/B test to see if removing the code hosts from the signup section reduces friction for cloud trials. cc @danielmarquespt 

![Screen Shot 2022-11-15 at 8 15 05 AM](https://user-images.githubusercontent.com/43555476/201955826-90751242-96c2-4181-8dbb-5d1f6cbcf498.png)

**Comment by almeidapaulooliveira** [comment]
@taylorsperry, this is a good candidate for quick research.

**Comment by st0nebraker** [comment]
Optimize A/B test setup [here](https://optimize.google.com/optimize/home/#/accounts/4705180113/containers/15523203/experiments/21). Blocked currently from launching from a missing tag in the domain. PR to hopefully unblock that is [here](https://github.com/sourcegraph/console/pull/152).

**Comment by st0nebraker** [comment]
This A/B test is live now. I'm leaving the ticket in `Measuring` for us to observe & make a decision on what to do in 2-4 weeks after seeing the interaction we get. cc @taylorsperry @almeidapaulooliveira
