### ISSUE TITLE
Create a configurable where admins can set a default page limit on the file history commits, and users can configure their own.

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#44431]
- **Requested by:** https://github.com/sourcegraph/accounts/issues/6716 via [Slack](https://sourcegraph.slack.com/archives/C01D50MSA7L/p1668535192009239)

#### Feature request description

When viewing the history of a file, how many commits are loaded in each page of commits, before a Show more link is shown at the bottom? Can we create a configurable where admins can set a default to ~5, and users can change that if they like?

#### Is your feature request related to a problem? If so, please describe.

For large repositories, it can take a significant amount of time to load this history tab and most users may not need to see 100 commits.

/cc @jplahn @ryphil

**Comment by mrnugget** [comment]
The change would look similar to what I did in https://github.com/sourcegraph/sourcegraph/pull/31837.

1. Add a `history.defaultStartPageSize` (or a better name) setting
2. Pass it into `RepoRevisionSidebarCommits`: https://github.com/sourcegraph/sourcegraph/blob/15dc7723d8ba62fbf9a667204ec2a0ecb70713df/client/web/src/repo/RepoRevisionSidebarCommits.tsx#L61-L68 (see how the `absoluteTimestamps` is set: https://github.com/sourcegraph/sourcegraph/blob/15dc7723d8ba62fbf9a667204ec2a0ecb70713df/client/web/src/repo/blob/panel/BlobPanel.tsx#L105)
3. Use it here, if set: https://github.com/sourcegraph/sourcegraph/blob/15dc7723d8ba62fbf9a667204ec2a0ecb70713df/client/web/src/repo/RepoRevisionSidebarCommits.tsx#L91

---

Side note: we don't paginate anything here. If someone hits "Show more" we simply load more. That's bad.

**Comment by mike-r-mclaughlin** [comment]
hey @indradhanush will this make it into 4.2?  See [slack thread](https://sourcegraph.slack.com/archives/C01D50MSA7L/p1669672729402689)
