### ISSUE TITLE
Make it more clear when src-cli freezes because docker is unresponsive

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#44432]
Midway through an execution, the docker daemon seems to become unresponsive at some point occasionally. 
Users would usually be confused, wait for quite an additional while, and then often reach out to get support why their execution is stuck. 99% of these requests seem to just be docker locking up, so we should tackle this problem and give users proper insight why things are stuck, so they know how to get unstuck.

What we want to do here:
- We add a watchdog that is running while an execution is ongoing, to check if docker is becoming unresponsive (docker ps is known to hang, for example)
- If that watchdog triggers, we show an additional banner in the src-cli output, next to the execution saying some nice messaging about "hey docker might be stuck, if no progress is made, restart docker and and maybe try reducing concurrency with `-j`

**Comment by chrispine** [comment]
Estimate on this one?

**Comment by eseliger** [comment]
P1? This is SUPER annoying and a frequent source of support tickets.
