### ISSUE TITLE
Rename Timeline modal to Diagnostics

### ISSUE THREAD

**Issue by BolajiOlajide** [sourcegraph/sourcegraph#44443]
For purpose of clarity, we are renaming the `Timeline` modal to Diagnostics so customers can better understand it's purpose.

![CleanShot 2022-11-15 at 22 11 41@2x](https://user-images.githubusercontent.com/25608335/202026248-30bf0ac1-2f0c-4963-863a-bd8aa9a98a8b.png)

**Comment by chrispine** [comment]
P1, let's just do it!

**Comment by courier-new** [comment]
P(-1), let's just done it: https://github.com/sourcegraph/sourcegraph/pull/44535
