### ISSUE TITLE
Surface execution logs for non-site administrators

### ISSUE THREAD

**Issue by BolajiOlajide** [sourcegraph/sourcegraph#44446]
Non-site administrators are unable to send diagnostics to help troubleshoot when there's an execution error because we don't display logs for them. We need to surface logs for all users.

![CleanShot 2022-11-15 at 14 10 51@2x](https://user-images.githubusercontent.com/25608335/202027868-0fcca1d2-9c11-4885-ac57-c08328ec835f.png)

**Comment by chrispine** [comment]
How much do we want this for our own debugging? Like, a P1 amount? or...?

**Comment by courier-new** [comment]
How about a P(-1) amount: https://github.com/sourcegraph/sourcegraph/pull/44536
