### ISSUE TITLE
batches: Improve loading state of workspaces preview

### ISSUE THREAD

**Issue by courier-new** [sourcegraph/sourcegraph#44460]
Users don't necessarily understand that the workspaces preview search does not correspond 1:1 with Sourcegraph search. This reduces user confidence that things are working as expected if workspaces preview takes a long time (>10 seconds), especially when searching the same query from the normal search box may start streaming results back much faster.

We should improve the loading state to enumerate the steps that are happening behind the scenes, to give a users a better sense of what's happening during the wait.

**Comment by courier-new** [comment]
Related to https://github.com/sourcegraph/sourcegraph/issues/43420.

**Comment by chrispine** [comment]
sr/high looks right to me (so backlog for now)

**Comment by courier-new** [comment]
Given this is the _bare minimum_ we need to do for https://github.com/sourcegraph/sourcegraph/issues/43420, I'm going to adjust the label to very-high and suggest very strongly that we make this a P2.

**Comment by courier-new** [comment]
It's hard to estimate this since there's design work involved, but I put some tentative numbers down given this is mostly about copy + presentation in a very narrowly scoped part of the UI.

**Comment by courier-new** [comment]
Closing in favor of https://github.com/sourcegraph/sourcegraph/issues/44462, which is strictly an improvement and already in progress.
