### ISSUE TITLE
sg: improvie `ci build` flow and handle external builds better

### ISSUE THREAD

**Issue by burmudar** [sourcegraph/sourcegraph#44485]
Issuing `sg ci build -c $SOME-COMMIT` for an external contributor while you're on the main branch will a main pipeline run even though the commit that is triggered is not in on the main branch for the repository. This effect can be seen on this [PR](https://github.com/sourcegraph/sourcegraph/pull/34279) and it's associated [build](https://buildkite.com/sourcegraph/sourcegraph/builds/183809). A Quick fix was submitted in
 - https://github.com/sourcegraph/sourcegraph/pull/44484

The code in `ci build` as changed and grown over time and it's become difficult to maintain and improve. We should relook at the approach and reimplent to since we have a better understanding of the requirements now

**Comment by jhchabran** [comment]
ddone
