### ISSUE TITLE
Provide more information on the permissions page when there is a problem syncing

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#44496]
#### Feature request description

Display an error message or error indicator in the user's permissions sync status UI (`/users/<username>/settings/permissions`) when there is a problem syncing permissions.

#### Is your feature request related to a problem? If so, please describe.

A user was unable to see repositories that they had permissions to on the code host (Bitbucket).  When we went to the user's permissions page, we saw that permissions syncing had recently completed.  We assumed it had completed successfully.    

<img width="879" alt="image" src="https://user-images.githubusercontent.com/23640224/202224934-70fd68f1-89cd-4a25-8ce1-8d35459eca8a.png">

However, after reading the repo-updater logs, we found error messages.  It would be great if the site admin could see the actual error in the UI and the user could see a simple indicator that indicated their permissions syncing failed.

/cc @sourcegraph/source/iam

**Comment by mrnugget** [comment]
I'm closing this because I think this has been fixed with the permission center.
