### ISSUE TITLE
AWS: Evaluate spend and billing observability

### ISSUE THREAD

**Issue by kalanchan** [sourcegraph/sourcegraph#44611]
Ask from @steveyegge to breakdown AWS spend (~30k/month) and identify areas of cost reduction. Evaluate how we can create observability into AWS spend and create better resource isolation among teams that use AWS. 

To keep in mind for the future, we need to put in place proper ownership of AWS, process for account creation, and create an AWS organization to help identify which teams are using what.

**NOTE**: AWS accounts == GCP projects. the terminology can be confusing

Tasks:

- [ ] Identify who uses AWS and why its costing so much
- [ ] cleanup unused resources
- [ ] Sink AWS billing data into GCP and create billing dashboard

**Comment by davejrt** [comment]
@kalanchan I'd drop  cleanup unused resources and Sink AWS billing data into GCP and create billing dashboard from this issue entirely, as they are outcomes of the initial investigation. 

The alternative is that this should be a tracking issue, with an issue for each of those tasks. Identifying owners and getting a full view of currently deployed resources is not a small task in itself. 

If there are actions as a result they should be seperate. We didn't scope this volume of work for this bet along with the remaining GCP work.

**Comment by jhchabran** [comment]
update: @chrispine to check the current context/state

**Comment by chrispine** [comment]
I'm sorry, but I haven't gotten to this, and realistically will not have time in the next couple of months at least, so I'm unassigning myself
