### ISSUE TITLE
dogfood: investigate why traces aren't being uploaded

### ISSUE THREAD

**Issue by kalanchan** [sourcegraph/sourcegraph#44614]
Dogfood was previously using Grafana Cloud and has been switched over to use [GCP Cloud tracing via otel](https://github.com/sourcegraph/deploy-sourcegraph-dogfood-k8s/pull/5687). However it seems like only zoekt traces are being uploaded at the moment, need to investigate why this is and how to enable all traces to get uploaded.

Also need to monitor cost, if it deems expensive to use Cloud tracing, we can also use our own grafana setup. 

see https://console.cloud.google.com/traces/list?project=sourcegraph-dogfood

only zoekt traces
![Image](https://user-images.githubusercontent.com/51868853/202766288-c26e44f4-0222-4ebf-adf6-bd21b95b7927.png)

**Comment by burmudar** [comment]
Addressed in https://github.com/sourcegraph/sourcegraph/issues/44490
