### ISSUE TITLE
Remove right extensions actions sidebar, move actions into top bar

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#44622]
With the removal of extensions, there is no clear reason why some actions (e.g. open in editor) are in the vertical right sidebar and while others are in the top bar (e.g. open on code host). 

Unless the extensions feature flag is on, the bar and collapse/expand button should not be rendered and all the native actions in there should be in the top toolbar instead.

cc @jjinnii 

/cc @felixfbecker

**Comment by philipp-spiess** [comment]
Fixed
