### ISSUE TITLE
Add keyboard navigation for search results

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#44628]
There should be a way to select search results with the keyboard without having to <kbd>tab</kbd> through all tabstops (basically skipping only from result to result).

Related hack project: https://github.com/sourcegraph/sourcegraph/pull/41693

Related issue: #19021 

/cc @felixfbecker

**Comment by limitedmage** [comment]
@novoselrok Is this closed by #44806 ?
