### ISSUE TITLE
Batch Changes - monitoring rolloutWindow - github "secondary" rateLimit

### ISSUE THREAD

**Issue by DaedalusG** [sourcegraph/sourcegraph#44631]
#### Is your feature request related to a problem? If so, please describe.
Users often encounter rateLimits from GitHub when implementing their first batch changes. This is discovered when github issues blocks requests from the user token for around an hour.

Currently Sourcegraph displays the following error message in the UI under a carrot dropdown in the `batchs` UI
<img width="1021" alt="Screen Shot 2022-11-18 at 4 34 02 PM" src="https://user-images.githubusercontent.com/13024338/202824637-9a6c01e3-edfb-47bf-b28f-28a0498985ea.png">
```
reached GitHub's internal creation limit: see https://docs.sourcegraph.com/admin/config/batch_changes#avoiding-hitting-rate-limits
```
[(PR where this was added)](https://github.com/sourcegraph/sourcegraph/pull/40169)

Unfortunately if an admin runs into this error it can be difficult to determine what rate to set here -- effectively the troubleshooting process is too decrement the rate intermittently until requests are no longer being limited, waiting an hour between each decrement until a stable rate is reached.

This is a known issue relating in part to Githubs [lack of response signal](https://github.com/cli/cli/issues/4801#issuecomment-1029207971) about the remaining requests before hitting the [secondary limit](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#secondary-rate-limits). 

It would be ideal if we could --
1. document more information about how batch changes consume the graphQL UI so that admins may make a more informed decision about what rate to set.
2. provide some monitoring about the number of requests consuming this API in grafana

#### Describe alternatives you've considered.

a long shot would be to automate this whole process so that Sourcegraph could asses and configure a good rateLimit automatically, while leaving the ability to manually configure this limit. 

#### Additional context

This issues was observed in customer instances twice in a week, so it is assumed to be affecting a lot of batch changes users.

**Comment by DaedalusG** [comment]
This issue follows up on https://github.com/sourcegraph/sourcegraph/issues/39847

**Comment by chrispine** [comment]
How frequently does this happen? Is it basically a think that only happens once for new accounts? What percentage of accounts see this?

**Comment by malomarrec** [comment]
https://github.com/sourcegraph/sourcegraph/pull/44980

**Comment by malomarrec** [comment]
Quick fix was done by Warren, moving to backlog for a potential longer term fix.

**Comment by bahrmichael** [comment]
Closing this as there's no data to indicate this happened in Q1 and Q2 of 2024. https://sourcegraph.slack.com/archives/C01JR51JR5J/p1723464828354009?thread_ts=1723443318.248029&cid=C01JR51JR5J
