### ISSUE TITLE
Epic: Create Cloud landing page for About

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#44660]
Taylor will work with @iskyOS to create content for a Cloud landing page on About. Once we have content, @almeidapaulooliveira to create a design issue and we'll follow up with an implementation issue. 

Related issues:

- [Create Cloud landing page - content](https://github.com/sourcegraph/sourcegraph/issues/44662)
- [Create Cloud landing page - design](https://github.com/sourcegraph/sourcegraph/issues/44661)
- [ Create Cloud landing page - implementation ](https://github.com/sourcegraph/sourcegraph/issues/44663)

**Comment by almeidapaulooliveira** [comment]
Thanks, @taylorsperry, if possible, I would like to participate in the content creation as well.
