### ISSUE TITLE
Code Insights: Capture group search query input has weird (not working) focus management 

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#44674]
Originally reported by @leonore 

If you try to focus input with your mouse pointer/cursor you will see that capture group asterisk button steals focus from capture group series input. This makes search query input completely unaccessible from mouse devices. 

You still can navigate to the field with keyboard though. 

https://user-images.githubusercontent.com/18492575/203106093-d9b303ce-4853-4bd7-8835-4f9ba10f6c3f.mov

/cc @joelkw @felixfbecker @vovakulikov

**Comment by vovakulikov** [comment]
P0 since this seems like a big problem for code insight creation UI

**Comment by felixfbecker** [comment]
I think this is a violation of WCAG [3.2.2: On Input](https://www.w3.org/WAI/WCAG21/Understanding/on-input.html)
