### ISSUE TITLE
Applying large number of changesets times out

### ISSUE THREAD

**Issue by Piszmog** [sourcegraph/sourcegraph#44678]
When trying to apply [125k changesets](https://scaletesting.sgdev.org/users/Piszmog/batch-changes/GHE-125k/executions/QmF0Y2hTcGVjOiI0Tng4MG1udFdNVCI=/preview), `ApplyBatchChange` fails with a `502`.

### Logs

It seems that the request is taking too long and is timing out (after 1 min).

```text
2022/11/21 16:55:35 [error] 60#60: *178150861 upstream timed out (110: Operation timed out) while reading response header from upstream, 
client: 172.68.34.254, 
server: scaletesting.sgdev.org, 
request: "POST /.api/graphql?ApplyBatchChange HTTP/1.1", 
upstream: "http://172.20.1.217:3080/.api/graphql?ApplyBatchChange", 
host: "scaletesting.sgdev.org", 
referrer: "https://scaletesting.sgdev.org/users/Piszmog/batch-changes/GHE-125k/executions/QmF0Y2hTcGVjOiI0Tng4MG1udFdNVCI=/preview"
```

### Sentry 
The error in [Sentry](https://sentry.io/organizations/sourcegraph/issues/3755583273/?project=6735436&query=is%3Aunresolved&referrer=issue-stream).

```json
{
  "count": 1, 
  "elapsed": 59.998660404
}
```

### Video

https://user-images.githubusercontent.com/38407415/203119179-d658b8b1-0276-47ce-9a0b-a0787ac6b159.mov

## Done

Be able to publish a large number of changesets (100k+).

**Comment by Piszmog** [comment]
Some observations

* [`GetRewirerMappings`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/batches/store/changeset_specs.go?L640)
    * Queries the DB for all changeset specs
    * Queries the DB for all changesets
    * Queries the DB for all repos
    * Stores the above data in a single struct
* [`Rewire`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/batches/rewirer/rewirer.go?L29)
    * Iterates thru the result of `GetRewirerMappings` and updates the chanegsets to be updated by the reconciler
    * Returns the list of all changesets
* [`ValidateChangesetSpecs`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/batches/service/service.go?L1276)
    * Potentially could return every changeset

**Comment by chrispine** [comment]
Is this different from [this issue](https://docs.google.com/document/d/1vXAnhui-AGBk2aar4pXt-uTuTIQfZU5LFFtrMAU2e4s/edit#bookmark=id.t080l34unpiw) (which says sr-med)?

**Comment by Piszmog** [comment]
If I am understanding that issue correctly, it seems to be more about actually opening the changesets (PRs/MRs) on the code host.

My Issue is about trying to just apply the the changeset spec to the batch change (before publishing the changesets to the code hosts)

**Comment by eseliger** [comment]
Feels like worth an investigation, since scale testing and other results of it are very-high: P0-P1, depending on availability? Hard to estimate, I'd say timebox to 2d to investigate?

**Comment by Piszmog** [comment]
After loading up my local development with 125k changesets and attempting to apply them. I found the bottleneck.

It is when we are [updating each changesets ui publication state](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/enterprise/internal/batches/service/service_apply_batch_change.go?L160-168). We update each changeset one-by-one.

I let this run on my computer for 15 minutes before just killing the process.
