### ISSUE TITLE
Make load test tool k6 available for external users

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#44673]
Our [load test tool - k6](https://github.com/sourcegraph/k6) is currently configured to be used internally only.

We will need to add instructions and functions so that external users can use the search performance test on their instances, as requested in this Slack thread [here](https://sourcegraph.slack.com/archives/C040LV3PS4C/p1667495885394099)

/cc @sourcegraph/delivery

**Comment by mike-r-mclaughlin** [comment]
https://github.com/sourcegraph/accounts/issues/284 would be most interested in these details

**Comment by slimsag** [comment]
k6 is AGPL, we cannot ship it to customers. We can look at other tools like Vegeta
