### ISSUE TITLE
WIP: Repo-Management Remove Cloudv1 Relics Tracking issue

### ISSUE THREAD

**Issue by varsanojidan** [sourcegraph/sourcegraph#44686]
### Plan

We want to get rid of any code related to Cloudv1 concepts (like namespace_org_id and namespace_user_id) as they are currently no longer supported and are just dead code.

#### Legend

- 👩 Customer issue
- 🐛 Bug
- 🧶 Technical debt
- 🎩 Quality of life
- 🛠️ [Roadmap](https://handbook.sourcegraph.com/departments/product-engineering/process/planning-process#roadmap)
- 🕵️ [Spike](https://en.wikipedia.org/wiki/Spike_(software_development))
- 🔒 Security issue
- 🙆 Stretch goal

/cc @jplahn @ryphil

**Comment by sashaostrikov** [comment]
whoa, that was fast, brat! (should we reopen it? 😄)

**Comment by varsanojidan** [comment]
😅 of course brat you know how I do. I spoke with @jplahn  and we decided it might be better to just track these issues individually under our techdebt tracking issue

**Comment by sashaostrikov** [comment]
@varsanojidan SGTM 👍🏻 I'd add `cloudv1-debt` label along, it seems nice to have

**Comment by ryanslade** [comment]
Oops, didn't see this issue and create something similar:
https://github.com/sourcegraph/sourcegraph/issues/44700
