### ISSUE TITLE
Make codehost connection issues more clear to the user.

### ISSUE THREAD

**Issue by varsanojidan** [sourcegraph/sourcegraph#44683]
Following up on this [thread](https://sourcegraph.slack.com/archives/C02EDAQAJQZ/p1668795542313089).

<img width="891" alt="image" src="https://user-images.githubusercontent.com/20795805/203124359-b8acb1eb-f204-45d7-9d0d-07bcdcfbbc30.png">

We want codehost connection issues to be much more noticeable for users of Sourcegraph. Two things that can be improved on are:

1) @mrnugget suggested that it would be nice to have a "Test Repository Connection" button on the codehost config page that would let you validate a codehost config by sending an actual request to the codehost without having to save the codehost config first.

2) Make errors reaching the codehost (like the image above) more obvious. After talking with @cbart, one way to do this would be to add a ping to the codehost as part of the repo-syncing process and avoid the repo-sync if the ping fails. 

### Scope

For now:

- [ ] GitHub
- [ ] GitLab
- [ ] Bitbucket Server
- [ ] Frontend side

/cc @jplahn @ryphil

**Comment by cbart** [comment]
From @varsanojidan 

> One thing we can probably do is lookup the IP of the codehost to validate that DNS is working correctly as a first check: https://jameshfisher.com/2017/08/03/golang-dns-lookup/

**Comment by cbart** [comment]
I did not mean to close this yet. I'm probably missing something in how should I attach pull requests to a github issue without closing it on merge. 🤷

**Comment by mrnugget** [comment]
If you write "fixes #1234" in a PR then when the PR is merged the ticket is closed. What I usually do to avoid that is to say "Part of #1234", which then links the PR to this one and makes the PR show up in here.

**Comment by cbart** [comment]
This includes

- Extending the connection checking API on `Source` to indicate whether the check succeeded, failed or (new option) we do not actually know.
- Implement GraphQL API for the above.
- Wire up errors from checking as part of a sync to the UI to surface with a toast.
- Add a checking button which indicates the status.

**Comment by indradhanush** [comment]
This is now feature complete. 🎉

**Comment by peterguy** [comment]
Adding Perforce: https://github.com/sourcegraph/sourcegraph/pull/56697
