### ISSUE TITLE
IAM Project Plan: Free Tier updates

### ISSUE THREAD

**Issue by jplahn** [sourcegraph/sourcegraph#44690]
### Problem
Company leadership and marketing are making changes to the Free tier. We need to make updates accordingly. 

### Requirements & Out-of-Scope
Below are the proposed changes to the free tier. 

<b id="docs-internal-guid-bc50938e-7fff-cca8-0481-e02196995aa1" style="font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-weight: normal;"><div dir="ltr" align="left" style="margin-left: 0pt;">

  | Current “Free” tier | Proposed “New Free” tier
-- | -- | --
Seats | 10 | 10
Code host connections | 1 | 1
Batch Changes | 5 changesets | 10 changesets
Code Insights | 2 insights | 2 insights
Public repositories | Unlimited | Unlimited
API | Unlimited | Unlimited
Private repositories | Unlimited | 1
Code monitoring | Included | Included
Code scale | Implied limited, but technically unlimited | Unlimited
SSO/SAML | Yes, but not promoted | No
Repository permissions | Not promoted - unsure if it’s technically included | Yes

</div></b>

All _existing_ Free tier customers should remain on the current Free tier plan, unless they self-select into moving to the new plan. If an existing customer self-selects into the new plan, they cannot return to the old plan. All _new_ customers should be directed to the new Free tier plan. We do not have a defined expiry date on the existing free plan, it should live indefinitely. 

### Success Criteria
1. 100% of existing Free tier customers remain on the existing Free tier plan
2. Existing Free tier customers should have a way to self-select into the new Free tier plan
3. 100% of new Free tier customers use are on the new Free tier plan after it launches
4. The updated free tier launches in the January release of Sourcegraph, to align with marketing

### Proposed Solution
Filled out by engineering DRI. A high level, crisp discussion of the proposed solution. This should give the reader a clear understanding of how we want to solve the problem.

### Delivery Plan
Filled out by the engineering DRI. A breakdown of the milestones and sub-steps required to deliver the proposed solution with estimates. Initially, the delivery steps can be a bulleted list of text with associated effort estimates. After team estimation, the delivery steps will become individual GitHub issues with high-confidence estimates. 

#### Milestone 1
1. Deliverable 1 [1 week]
5. Deliverable 2 [2 weeks] 

#### Milestone 2
1. Deliverable 3 [2 weeks] 
2. Deliverable 4 [2 weeks]

### Risks and Mitigations
Filled out by the engineering DRI. This section highlights any risks associated with the solution or delivery plan along with proposed mitigations (or why we’re ok accepting the risk). This section should also call out any one way door decisions. 

/cc @sourcegraph/source/iam

**Comment by jplahn** [comment]
> Hey, @sourcegraph/batchers (@eseliger @LawnGnome @courier-new @adeola-ak @BolajiOlajide @Piszmog @malomarrec @chrispine @danielmarquespt) - we have been mentioned. Let's take a look.

I don't think so...

**Comment by chrispine** [comment]
If you use the word "batch" we're gonna know about it. We have spies _everywhere..._

**Comment by mrnugget** [comment]
Closing this, seems not relevant anymore. Happy to be proven wrong by Ryan Phillips.
