### ISSUE TITLE
Cannot create org batch change after creating new org

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#44708]
Steps to reproduce:

- Create a new org
- Land on the org page
- Click on batch changes
- Click create
- The org namespace is not preselected and also not in the dropdown
- Sad

A page refresh fixes it. That is probably because we take the orgs from the authedUser object and that is never refetched.

**Comment by courier-new** [comment]
Seems likely a quick fix, like 0.5d. Maybe P0, or P1 if there's not capacity?
