### ISSUE TITLE
debt: Remove Cloud V1 code

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#44700]
Remove code associated with Cloud V1. For now, we'll only remove code and leave database cleanup as another final step.

- [x] [ViewerNeedsCodeHostUpdate]( https://github.com/sourcegraph/sourcegraph/blob/4487207ad95d02e784cee08ae7bfa0d591687403/cmd/frontend/graphqlbackend/org.go#L257-L297) 
- [x] [Code related](https://sourcegraph.sourcegraph.com/search?q=context%3Aglobal+repo%3A%5Egithub%5C.com%2Fsourcegraph%2Fsourcegraph%24+user_public_repos&patternType=standard&sm=1&groupBy=path) to `user_public_repos`
- [x] The GitHub and GitLab implementation of [CreateCodeHostConnection]( https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/internal/auth/oauth/session.go?L38:2#tab=references)
- [x] [`ExternalService.IsSiteOwned()`](https://github.com/sourcegraph/sourcegraph/blob/4eab8dddfcba41c62b12c223924487c534f59bfb/internal/types/types.go#L623-L624) can be removed since it's all site-owned external services now
- [ ] Remove `NamespaceUserID` and `NamespaceOrgID` from external service

/cc @sourcegraph/source/iam

**Comment by mrnugget** [comment]
First one deleted in here: https://github.com/sourcegraph/sourcegraph/pull/44785

**Comment by ryanslade** [comment]
I'm going to take a look at removing the `user_public_repos` code.

**Comment by mrnugget** [comment]
> Looks like the third one was also done via #44785 right?

Yes! Correct.

I added another one to the list.

**Comment by mrnugget** [comment]
All done
