### ISSUE TITLE
Rebooting search input

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#44705]
## Design process

  - Estimate: Two weeks to one month
  - Weighting factors:
    - HIGH risk
    - MEDIUM clarity

  ### Define
  - [ ] RFC – [RFC 760: Rebooting the search input](https://docs.google.com/document/d/1eeb63tAEJ3hkJLh5_tTbwlUlfpnP8onJaBqi5_CWrAA/edit)
  - [ ] Github issue – #44705

  ### Design
  - [x] Low fidelity design – Link TBD
  - [x] High fidelity design using design system – [Figma](https://www.figma.com/file/aenTj3SG2zl1g90HcMDUm2/RFC-760-WIP%3A-Rebooting-the-search-input-UI?node-id=260%3A11&t=mAjBUfPwTbeHkfr8-0)
  - [ ] Prototype – [Link](https://www.figma.com/proto/aenTj3SG2zl1g90HcMDUm2/RFC-760-WIP%3A-Rebooting-the-search-input-UI?page-id=2043%3A17239&node-id=2043%3A24092&scaling=min-zoom&starting-point-node-id=2043%3A18911)
  - [ ] Designer review

  ### Testing
  - [ ] Hallway testing - Link
  - [ ] Usertesting.com task based evaluation - Link

  ### Deliver
  - [ ] Announce in #progress
  - [ ] Loom - Link
  - [ ] Team review
  - [ ] Design team review
  - [ ] QA - Link

  ### Measure
  - [ ] Metrics defined in the Figma file ([i](https://handbook.sourcegraph.com/departments/product-engineering/product/design/metrics/defining-metrics/)) - Link
  - [ ] Followup task will analyze metrics to ensure successful completion - Link

/cc @sourcegraph/search-product

**Comment by malomarrec** [comment]
Hey @malomarrec, it looks like this issue was created by someone outside Sourcegraph. Assigning you to triage it! Please answer and route to the right team by adding their team label, then **remove** the `triage-bot/needs-triage` label

**Comment by malomarrec** [comment]
@quinnkeast Could you add a team label here? (Could be `team/design`)
