### ISSUE TITLE
Batch change changeset list page style issues

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#44716]
On the changesets list page, on narrower screens the list overflows:

![Screenshot 2022-11-22 at 15 49 10](https://user-images.githubusercontent.com/19534377/203344411-ab906e07-13e2-4db7-a341-5cdccebdc396.png)

Between the diff stat and the stats items should be some gap, this looks very arrow and broken:

![Screenshot 2022-11-22 at 15 49 47](https://user-images.githubusercontent.com/19534377/203344650-65e9c2ec-866e-43ef-bea4-ceb25773ad04.png)

**Comment by courier-new** [comment]
May be a regression from the recent a11y fixes that converted this into actual semantic list elements. Shouldn't be too troublesome to fix, so maybe 0.5d and P0 or P1 if there isn't capacity?
