### ISSUE TITLE
Strategic: files are not showing up on depots added to the scale testing instance

### ISSUE THREAD

**Issue by miveronese** [sourcegraph/sourcegraph#44710]
Depots added to the Scale Testing instance are successfully synced and displayed, but not their files.

**How to reproduce**
- Go to the Scale Testing Instance
- Log in as an admin (credentials can be found in 1Password)
- Search for perforce repos/debots
- Check if you can see their files

**Example**
https://scaletesting.sgdev.org/perforce/iam-test

**Screenshot**

![Image](https://user-images.githubusercontent.com/1552863/203336399-eb8fb818-dabb-4316-bb19-ec03e304f66b.png)

**Comment by peterguy** [comment]
When I follow the instructions, I see files.

<img width="1109" alt="Screenshot 2023-04-05 at 21 09 15" src="https://user-images.githubusercontent.com/129280/230269993-17edafaa-ff41-43c1-b779-09cb05b2f58e.png">
