### ISSUE TITLE
Weird pinning behavior

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#4471]
![2019-06-12 14 30 06](https://user-images.githubusercontent.com/10532611/59351409-a2b7ca80-8d1e-11e9-92b3-66684030a1cc.gif)

I clicked on the token.
Notice how the close button appears, then disappears.

**Comment by lguychard** [comment]
@felixfbecker I haven't been able to reproduce this in the webapp or in the browser extension. Can you still reproduce this?

**Comment by Joelkw** [comment]
closing this, it's not still an issue / this is an old design
