### ISSUE TITLE
webhooks: Update documentation. 

### ISSUE THREAD

**Issue by mollylogue** [sourcegraph/sourcegraph#44723]
Once our initial UI is complete, we should add documentation that walks an admin 
through the process of setting up webhook receivers. 

Remember to document that encryption key needs to be added to config to enable 
secret encryption. 

This also includes linking to the new docs from old docs.

/cc @jplahn @ryphil

**Comment by malomarrec** [comment]
Hey @mollylogue, this issue didn't have a team label. Given you created it, I assigned you and added your team label. Feel free to unassign yourself. If this is not the right label, can you make sure to add the right one?

**Comment by mrnugget** [comment]
@ryanslade you wanted to add screenshots, right?

**Comment by sashaostrikov** [comment]
@mrnugget I'll do it here https://github.com/sourcegraph/sourcegraph/issues/45655

Ryan is onto another stuff, so I'm taking this over :)
