### ISSUE TITLE
batches: 'patch does not apply' error when trying to publish changeset

### ISSUE THREAD

**Issue by adeola-ak** [sourcegraph/sourcegraph#44743]
The following error was produced when trying to publish a changeset both locally and with src-cli: 

`CreateCommitFromPatch "http://127.0.0.1:3502/create-commit-from-patch": CreateCommitFromPatch: http status %!d(string=500 Internal Server Error), {"Rev":"","Error":{"RepositoryName":"bitbucket.sgdev.org/~MILTON/project-euler-solutions","InternalError":"gitserver: applying patch: exit status 1","Command":"git -c credential.helper= -c protocol.version=2 apply --cached -p0","CombinedOutput":"error: patch failed: Euler 0011/README.txt:25\nerror: Euler 0011/README.txt: patch does not apply\nerror: patch failed: Euler 0015/README.txt:3\nerror: Euler 0015/README.txt: patch does not apply\n"}}`

The following day the same issue was reported by a customer, where some, but not all, patches would fail:

`Failed to run operations on changeset
CreateCommitFromPatch http://gitserver-0:3178/create-commit-from-patch: CreateCommitFromPatch: http status %!d(string=500 Internal Server Error), {
    "Rev":"",
    "Error":{
        "RepositoryName":REPOSITORY,
        "InternalError":"\u003credacted\u003eserver: applying patch: exit status 1",
        "Command":"\u003credacted\u003e -c credential.helper= -c protocol.version=2 apply --cached -p0",
        "CombinedOutput":"\u003cstdin\u003e:4449: trailing whitespace.
\u003cstdin\u003e:4464: trailing whitespace.
error: patch failed: fuzz/unpack_pack_fuzzer_seed_corpus/EmptyArray:1
error: fuzz/unpack_pack_fuzzer_seed_corpus/EmptyArray: patch does not apply
error: patch failed: fuzz/unpack_pack_fuzzer_seed_corpus/EmptyObject:1
error: fuzz/unpack_pack_fuzzer_seed_corpus/EmptyObject: patch does not apply
error: patch failed: fuzz/unpack_pack_fuzzer_seed_corpus/ExcessiveNesting:1
error: fuzz/unpack_pack_fuzzer_seed_corpus/ExcessiveNesting: patch does not apply
"}}`

I am able to reproduce this error. Tested locally, as this repo was failing to be added to s2 at the moment...

I then made a few changes to the repo by excluding some files from being read by the batch change. First starting with Euler 0011, which had an outlier diff > The issue still persisted

I then deleted all files except Euler 0001.. and the issue was no longer. I was able to create the changeset.. very interesting. This is all the testing I was able to complete at the moment, but next I would probably try to bring back each file one by one to narrow down which file could be causing the error.. or look at each file carefully to see if anything jumps out at me.

I found that an error like this has happened before, I didnt get to dig into the entire issue, but i will link it [here](https://github.com/sourcegraph/sourcegraph/issues/6625)

I would appreciate any insights or further testing results

**Comment by eseliger** [comment]
This is an actual issue, the Readme.txt was encoded with a non-utf-8 encoding. These two PRs will fix it in the next Sourcegraph version:
https://github.com/sourcegraph/sourcegraph/pull/44779
https://github.com/sourcegraph/src-cli/pull/887
