### ISSUE TITLE
Remove more references to users code host connections

### ISSUE THREAD

**Issue by miveronese** [sourcegraph/sourcegraph#44745]
We still have references to code host connections owned by users -- and this needs to be removed as we don't support this anymore.

Here's an example recently found:
https://sourcegraph.com/github.com/sourcegraph/sourcegraph@0ca8da09fc74cb973ec7d22b256f895fb93a92db/-/blob/enterprise/cmd/frontend/internal/auth/gitlaboauth/session.go?L144

/cc @sourcegraph/source/iam

**Comment by malomarrec** [comment]
Hey @miveronese, this issue didn't have a team label. Given you created it, I assigned you and added your team label. Feel free to unassign yourself. If this is not the right label, can you make sure to add the right one?

**Comment by mrnugget** [comment]
That's been fixed.
