### ISSUE TITLE
Add experimental tag into fuzzy finder button

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#44765]
[Figma designs](https://www.figma.com/file/E0vD9UduSp2liVyDb7dplw/Fuzzy-finder-UI-improvements?node-id=1714%3A3559&t=0SpFxKgo23DF6Fzz-1)

**Goal:** 
* Improve design consistency of the fuzzy finder button 
  * The current implementation of the fuzzy finder button is inconsistent and visually dominating in the primary nav. The logo-purple border on buttons is only used for the "Sign Up" button, as the color is equal weight to the current active tab in the primary navigation. 
* Communicate that fuzzy finder is an experimental feature once shipped 

**Updates:**
* An "experimental" badge added into the fuzzy finder button
* Border for fuzzy finder button changed from logo-purple to border-color
* Active state for fuzzy finder button updated to logo-purple 
* Added primary focus state for keyboard navigation 

/cc @felixfbecker

**Comment by olafurpg** [comment]
I recommend the following updates to achieve the goal:

* Remove the fuzzy finder button by removing this line here https://sourcegraph.com/github.com/sourcegraph/sourcegraph@a2ca304f3b173dfc5c55d3572b3939d7d46633c6/-/blob/client/web/src/components/fuzzyFinder/FuzzyFinderFeatureFlag.ts?L21 The navbar is already busy making it not ideal to add another button for the fuzzy finder. By removing this button, we sacrifice discoverability but I don't think that's a blocking issue for the initial launch. We can solve the discoverability issue in the future after collecting real-world feedback from customers. It's enough for now that the fuzzy finder is documented in the `?` menu help and we can also mention it in the release notes.
* Optionally, we can add some "experimental" badge to the `FuzzyModal` footer with a link to post a comment here https://github.com/sourcegraph/sourcegraph/discussions/42874

**Comment by taras-yemets** [comment]
> * Remove the fuzzy finder button by removing this line here https://sourcegraph.com/github.com/sourcegraph/sourcegraph@a2ca304f3b173dfc5c55d3572b3939d7d46633c6/-/blob/client/web/src/components/fuzzyFinder/FuzzyFinderFeatureFlag.ts?L21 The navbar is already busy making it not ideal to add another button for the fuzzy finder. By removing this button, we sacrifice discoverability but I don't think that's a blocking issue for the initial launch. We can solve the discoverability issue in the future after collecting real-world feedback from customers. It's enough for now that the fuzzy finder is documented in the `?` menu help and we can also mention it in the release notes.

- https://github.com/sourcegraph/sourcegraph/pull/44809

> * Optionally, we can add some "experimental" badge to the `FuzzyModal` footer with a link to post a comment here [Fuzzy Finder Feedback #42874](https://github.com/sourcegraph/sourcegraph/discussions/42874)

- https://github.com/sourcegraph/sourcegraph/pull/44815
