### ISSUE TITLE
Minor fixings for Sign-up journeys

### ISSUE THREAD

**Issue by almeidapaulooliveira** [sourcegraph/sourcegraph#44786]
## 1. Problems
- The context dropdown isn't adjusting to the content height, and the vertical scrollbar shouldn't appear. 
- Unnecessary empty space at the bottom of the footer.
- The purple arrow (icon) isn't aligned with the first text line.

https://user-images.githubusercontent.com/64257673/203783591-0b249438-6c11-42cf-a8c3-77c99f743a3b.mov

## 1. Solutions
- Fix the dropdown height.
- Remove the empty space at the bottom.
- Align the purple icon with the first line of text (image below).

![Screen Shot 2022-11-24 at 09 25 55](https://user-images.githubusercontent.com/64257673/203784637-78d148b6-a601-4285-96b2-3a7fd6fee090.png)

---
## 2. Problems
- On the 'Code monitoring' page, the Logs tab throws an error for **unauth'd users**.

https://user-images.githubusercontent.com/64257673/203785038-6cf3da2b-8906-44d8-b5a2-8f78614a8d84.mov

## 2. Solutions
- Is it possible to show logs on for unauth'd users? If not, remove the tab item.

---
## 3. Problems
-  On the 'Batch Changes' page, the 'All batch changes' tab shows that this feature isn't available on .com for auth'd and unauth'd users.

https://user-images.githubusercontent.com/64257673/203785888-dd517646-6fcc-46c8-9c0d-410342d5494d.mov

## 3. Solutions
- Remove the tab component and the 'All batch changes' view. Only the 'getting started' view should be visible. As in the 'Insights' page.

**Comment by almeidapaulooliveira** [comment]
Cc: @taylorsperry

**Comment by st0nebraker** [comment]
Hey @almeidapaulooliveira - I'm not seeing the added bottom spacing for context dropdown (#1 on this ticket). Which browser and screen width do you see this on?

**Comment by almeidapaulooliveira** [comment]
I'm using Chrome, the screen resolution is 2560 × 1080, and the browser viewport is 1500 x 970.

**Comment by st0nebraker** [comment]
Got it, thanks @almeidapaulooliveira . I have a fix up in PR[#44957](https://github.com/sourcegraph/sourcegraph/pull/44957). I'm not allowing scroll/overflow on the outter container for this popover, so this should take care of the added extra space on the footer as well 😄
