### ISSUE TITLE
externalURL does not seem to work with G-Suite and OpenID

### ISSUE THREAD

**Issue by sciffer** [sourcegraph/sourcegraph#4478]
- **Sourcegraph version:3.4.3**
- **Platform information:
     Using formal docker image
     Kubernetes cluster: 1.10.8 (running as a statefulset, behind ingress - with filter to our specific IP)
     Docker version: 17.3.2
     Chrome: 75.0.3770.80 
      OpenIDAuth with GSuite** 

#### Steps to reproduce:

1. spin up a pod/statefulSet with a single instance of sourcegraph.
2. expose it using ingress with external URL referring to it.
3. configure the external URL as the above URL (in management console)
4. configure the openIdAuth for GSuite(based on the formal documentation)
5. Try to login usingopenIdAuth.

#### Expected behavior:
Authentication should work and at the end the user should be reffered back to the external URL
#### Actual behavior:
Authentication works, but the user gets refered back to https://127.0.0.1:7080/.auth/callback?
Obviously it ignores the external URL(BTW, google also gets the 127.0.0.1 and based on the doc it should get the external URL, I had to add http://127.0.0.1:7080/.auth/callback to the google authorized URL redirects - which is a bad idea by itself).
I can confirm that authentication was successful as if I just replace the http://127.0.0.1:7080 with my external URL prefix - everything works as expected.

The management console config looks like this:
```
{
  "externalURL": "https://sourcegraph.????????.???",
	"auth.providers": [
		{
			"type": "builtin",
			"allowSignup": true
		},
    {
      "type": "openidconnect",
      "issuer": "https://accounts.google.com",
      "clientID": "???????????????????????????????????????????",
      "clientSecret": "?????????",
      "requireEmailDomain": "???????.com",
      "displayName": "GoogleAuth",
    }
	]
}
```
Obviously replaced the sensitive data with "?"

**Comment by slimsag** [comment]
Hi, if you haven't already could you try restarting the server or `docker restart <sourcegraph_container>` after you've set the `externalURL` field? (we've just recently fixed this issue but it's not yet released)

**Comment by sciffer** [comment]
Yep, that did it.
Thanks.
