### ISSUE TITLE
Sign-up mobile page fixings

### ISSUE THREAD

**Issue by almeidapaulooliveira** [sourcegraph/sourcegraph#44790]
## Problem
- On mobile, the page shows the form on top of the value proposition message. In a recent TL;DR campaign, 44% of the traffic came from mobile devices. Although we couldn’t identify a correlation, we had an average visit duration of 25 seconds and an 88% bounce rate (on mobile only). A user is unlikely to sign up just by looking at a form without understanding the value proposition.

![mobilea](https://user-images.githubusercontent.com/64257673/203805087-8853343f-8b8b-45b2-881e-e5644e2b23e8.png)

## Solutions
- Switch the element's position as in the image below.
- Remove the 'or' from the line separator (on mobile and desktop pages).
![mobilebd](https://user-images.githubusercontent.com/64257673/203805684-c0f37949-3724-4197-848e-2d93d5086916.png)

**Comment by almeidapaulooliveira** [comment]
Cc: @RafLeszczynski, @taylorsperry

**Comment by almeidapaulooliveira** [comment]
Related to #44418, I opened it as a separate issue because this it's an urgent fix and doesn't require much design.

**Comment by taylorsperry** [comment]
@kelsey-brown let's see if this impacts bounce rates on mobile at all 📵

**Comment by bretthayes** [comment]
@kelsey-brown ready to measure

**Comment by kelsey-brown** [comment]
Bounce rate on mobile [hasn't shown improvement yet](https://analytics.amplitude.com/sourcegraph/chart/new/wwmjgte). That being said, we also haven't gotten a ton of mobile visitors in the past week (~400). I'm going to leave this in measuring and revisit in a week or two.
