### ISSUE TITLE
Code Insights: timeout popover (with timed-out points) - follow up issue to #43842

### ISSUE THREAD

**Issue by AlicjaSuska** [sourcegraph/sourcegraph#44811]
### Description

In #43842 we've implemented a simple tooltip, triggered by clicking on info icon, that informs users that:
- some points on the data series timed out
- some points in the whole insight timed out

Based on this [conversation](https://sourcegraph.slack.com/archives/C01RVEVPWLC/p1666689601773129?thread_ts=1665553291.511069&cid=C01RVEVPWLC), I would like to propose an improvement:
- adding the list of timed-out data points to the popover/tooltip
- change the style of the popover to move away from our tooltip style more towards a popover style

### Design
- [for the general insight error](https://www.figma.com/file/aMO6sPoUHDUUcqa25wFnWl/Surface-timeout-limit-hit-to-end-users-in-the-UI-%2339969-Ready-for-dev?node-id=2034%3A5798&t=xP5LLRo3QxEqZnoH-4)
- [for the data series only error](https://www.figma.com/file/aMO6sPoUHDUUcqa25wFnWl/Surface-timeout-limit-hit-to-end-users-in-the-UI-%2339969-Ready-for-dev?node-id=2021%3A5229&t=xP5LLRo3QxEqZnoH-4)
- [for the data series error with a long (scrollable) list of points](https://www.figma.com/file/aMO6sPoUHDUUcqa25wFnWl/Surface-timeout-limit-hit-to-end-users-in-the-UI-%2339969-Ready-for-dev?node-id=2021%3A5229&t=xP5LLRo3QxEqZnoH-4)

/cc @joelkw @felixfbecker @vovakulikov

**Comment by Joelkw** [comment]
(noted as dupe by vova)

**Comment by vovakulikov** [comment]
It was closed by this PR https://github.com/sourcegraph/sourcegraph/pull/45317
