### ISSUE TITLE
Chrome extension does weird things to text input on issues/comments/etc

### ISSUE THREAD

**Issue by danielpops** [sourcegraph/sourcegraph#4485]
- **Sourcegraph Extension version: 19.6.6.2105 ** 
- **Platform information: github.com, mac osx mojave 10.14.5, chrome 75.0.3770.80 **
#### Steps to reproduce:

1. Install plugin
2. Try to write text in a new or existing issue or comment, notice things are really wonky
3. Disable plugin, refresh current page
4. Try to write text in a new or existing issue or comment, notice it works

I'll provide a gif of the behavior shortly => http://www.giphy.com/gifs/eLkBUIKoH1yu65akug
In both cases, i'm typing `Typing works just fine`

**Comment by christinaforney** [comment]
Hey @danielpops - I hit this issue recently too! I think you might have accidentally enabled an experimental feature that is causing this issue. Take a look at your extension settings:

![image](https://user-images.githubusercontent.com/1559622/59448254-9cc2f780-8db9-11e9-94b0-3e0c454fee37.png)

and make sure you have un-checked the "Experimental text field completion" box.

Let me know if this doesn't fix your issue!

**Comment by danielpops** [comment]
@christinaforney++ that was it!

Amazing, I could type this reply without disabling the extension :)

**Comment by christinaforney** [comment]
Awesome! Glad you're all sorted :)
