### ISSUE TITLE
CI: pods get stuck in containerCreating and holds nodes up

### ISSUE THREAD

**Issue by kalanchan** [sourcegraph/sourcegraph#44871]
We have an issue with the dispatcher where pods are stuck in `pending containerCreating` because the pods can't find the associated PVs to attach to. I believe this is because the PVs are being cleaned out after a certain time. These pods do eventually die after the 2 hour TTL, but it holds up nodes for way too long. 

I suspect it might have something to do with when we create the PVs and clean them up
https://sourcegraph.sourcegraph.com/github.com/sourcegraph/infrastructure/-/blob/buildkite/buildkite-git-references/prune-pvcs.sh

![Image](https://user-images.githubusercontent.com/51868853/204391084-9657e52c-2068-4923-a186-c3a59e56e2b0.png)

![Image](https://user-images.githubusercontent.com/51868853/204390929-df6a3580-0995-4246-94d9-50845013756e.png)

**Comment by davejrt** [comment]
Anecdotally we have seen this behaviour quite a bit, not only on CI. 

Sometimes there can be stale attachments to nodes that have been removed. You can checked this via `kubectl get volumeattachment`

**Comment by jhchabran** [comment]
update: bandaid fix has been applied still need a better fix.
