### ISSUE TITLE
Commit filter on UI doesn't allow search using commit hash

### ISSUE THREAD

**Issue by rakeshjosh2003** [sourcegraph/sourcegraph#44881]
Currently, the commit filter on a file being searched allows one to search the commits based on commit headlines and not commit hash. I have tested this internally and replicated the behavior. The search should allow searching with a commit hash.
Attaching a short video for reference. Thank you.

https://sourcegraph2020.lightning.force.com/lightning/r/Account/0013t00001XicE2AAJ/view

**Comment by rakeshjosh2003** [comment]
https://user-images.githubusercontent.com/102702631/204430252-e6e9fc51-cabd-45bc-9c2f-7767f5f12fcd.mov

**Comment by rakeshjosh2003** [comment]
https://user-images.githubusercontent.com/102702631/204431135-21bb9196-8705-4ce1-bfb5-01e266adafcf.mov

**Comment by camdencheek** [comment]
Oh whoops, this seems to be about using the commit hash in a search, not about using the rev picker. Reopening
