### ISSUE TITLE
Move the error messages from `p4` commands from the banner to the external code host and include the command that failed

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#44916]
**Requested by:** https://github.com/sourcegraph/accounts/issues/6716

#### Feature request description

When there are errors from `p4 ping` or other commands that are executed outside of the normal workflow for sync'ing from Perforce, they seem to show up in the banner like this:

![image](https://user-images.githubusercontent.com/23640224/204615924-f99b2727-c464-4e34-8f75-becfedc79354.png)

But, on the code host it shows everything is green / healthy:

![image](https://user-images.githubusercontent.com/23640224/204616054-7cc664b9-54dc-4be3-a8cf-2e0795a0172c.png)

Request:
1.  It would be less confusing to have these messages appear in one location (near the code host).  
2. Also, it would be nice if the message included the command that was executed that caused the error message.

#### Is your feature request related to a problem? If so, please describe.

It's difficult to troubleshoot when there are conflicting messages (green/healthy on one page and errors appearing elsewhere).

#### Additional context

/cc @jplahn @ryphil

**Comment by peterguy** [comment]
Was this addressed by fixing issue #43855?

**Comment by indradhanush** [comment]
<img width="2556" alt="image" src="https://user-images.githubusercontent.com/2682729/233034671-7873e89a-0008-42f2-8384-ee631f25695f.png">

I just tested this behaviour locally and am now able to see the same error in the code host sync details now.

As for if this error should be present in the banner or not - I would suggest to leave it as is as the behavior is consistent with other code hosts (see error message from azuredevops in the screenshot) and helps to surface code host sync errors earlier.

Removing the sync errors from the banner completely should be a separate discussion.

**Comment by indradhanush** [comment]
cc: @mike-r-mclaughlin

**Comment by indradhanush** [comment]
Also the error shows up in the code hosts list page as expected now. ✅

<img width="2557" alt="image" src="https://user-images.githubusercontent.com/2682729/233102015-dc320889-8f44-4d7c-b497-e739ac338530.png">

**Comment by indradhanush** [comment]
Closing this as fixed. Reopen if needed.
