### ISSUE TITLE
Fix anonymous_user_id so it persists from about site to signup site

### ISSUE THREAD

**Issue by kelsey-brown** [sourcegraph/sourcegraph#44914]
### Problem description

The anonymous user id is overwritten when page path goes from about to signup. 

You can reproduce this by opening the javascript console in your browser and observing the anonymous_id given to your browser when you load the about site (be sure to log out of sourcegraph/use a private browsing window). Then click a CTA that brings you to the signup site, and watch how your anonymous_id changes 

### Context

This work is part of the [web analytics traffic requirements](https://docs.google.com/document/d/1Jf3JiYXXlIHWoy-EUm3w1T3JvfYYx26UjYZaTjDHsuI/edit#) effort (this effort is EventLogger8)

### User journey stage

Consideration

### Impact

High

### Effort

1 day

### Success criteria

Anonymous_user_id persists from about to signup. 

### Assigning labels

- [ ] If this issue will require input from designers in order to complete, please assign the label `needs-design`.

**Comment by st0nebraker** [comment]
I'm taking over this since Brett has left. Is this bug coming from SG or the Marketing Site / About site? The marketing site doesn't use the evenLogger. Also, I'm not sure how to find the `anonymous_id` from the browser developer tools. Where is that value? Or under which object do I need to look up? @kelsey-brown

**Comment by kelsey-brown** [comment]
Thank you for jumping on this @st0nebraker!

> Is this bug coming from SG or the Marketing Site / About site? The marketing site doesn't use the evenLogger.

I might be misinterpreting what you mean by this (if so I'm sorry!), but we are logging events on the about site. We only log `ViewStaticPage` and `StaticPageButtonClick` right now (so we don't have the same breadth of events on about as we do on dotcom) but we are getting them. [Here's](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/about/-/blob/src/hooks/eventLogger.ts) some of the code for example (I _think_ this is the right repo...)

>  I'm not sure how to find the anonymous_id from the browser developer tools. Where is that value? Or under which object do I need to look up?

In Chrome I go to Developer tools > Application > Storage > Cookies and then look for `sourcegraphAnonymousUid`. There are screenshots of this [here](https://docs.google.com/document/d/1Jf3JiYXXlIHWoy-EUm3w1T3JvfYYx26UjYZaTjDHsuI/edit#bookmark=id.5d54usf5aww2).

**Comment by st0nebraker** [comment]
@kelsey-brown - my bad! I hadn't used eventLogger on about and overlooked that file. Thanks for the help to repro, I'm on it now 🤓

**Comment by kelsey-brown** [comment]
TY! Let me know if you need anything else from my end/if I can answer any questions

**Comment by st0nebraker** [comment]
This issue is fixed now @kelsey-brown !

**Comment by kelsey-brown** [comment]
THANK YOU!
