### ISSUE TITLE
Docker: update syntax-highlighter for single-container deployments

### ISSUE THREAD

**Issue by sanderginn** [sourcegraph/sourcegraph#44933]
The following PR contains initial work but build doesn't pass yet, as well as context:
- https://github.com/sourcegraph/sourcegraph/pull/42486

Preferably this would be fixed before the next release (assuming that'd be 4.3.0, but sooner is better).

**Comment by davejrt** [comment]
Fixed by https://github.com/sourcegraph/sourcegraph/pull/45005
