### ISSUE TITLE
Code Insights: Newly created insight doesn't appear in the dashboard after mutation 

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#44960]
Steps to reproduce 
- Go to the dashboard page (to the all insight dashboard)
- Open the drill-down panel and try to create insight with the "save as new view" button 
- See that you can't see newly created insight on the all insights dashboard 
- But you can see it after the page refresh 

Note that in all other dashboard mutation update works properly and you don't need to refresh the page

Expected behaviour: you should be able to see newly create insight on the all insight page without page refresh.

/cc @joelkw @felixfbecker @vovakulikov

**Comment by chwarwick** [comment]
@vovakulikov I pretty sure I understand the reason here now and this is what is happening locally with app as well.

https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/enterprise/insights/pages/all-insights-view/AllInsightsView.tsx?L25&subtree=true

When the user returns to the All Insights page after creation of an insight it does not re-run the pagination query since there are no changes to any of the query variables.  This tab doesn't unmount during any of the navigation.

**Comment by vovakulikov** [comment]
@chwarwick Aha, interesting I didn't know about mounting/unmounting aspect. I probably changed something recently about this in the Tab component. 

Usually when it comes to situation like this (when you create something and then you also have queries that should have newly created entity) we have to work with cache directly on the client to update it. This is how "save as new view" functionality works on the dashboard tab for example. In this particular case this might be non trivial because - All insight tab has pagination, when we create insight I suspect it will be the last card on the all insight tab, so even if you update the cache and you will see this insight on the screen, next time you will see this newly created insight in different position (and for this you have to click load more until you get the end of the list)

So I think we probably just to need fix the tab UI and make it that this tab will remount every time then you visit the all insight tab

**Comment by vovakulikov** [comment]
I just checked the rendering of these tab and it seems like they are lazy rendered, and we re-render then every time when we visit each of them. Maybe we just need to tune fetch-policy for the all insights configurations query, and make it network only to eliminate the cache data 

https://user-images.githubusercontent.com/18492575/221663867-859e6164-88ca-4467-8a50-5a5a8e6a8921.mov

**Comment by chwarwick** [comment]
@vovakulikov  You're right I just played with this some and I found 2 options.

I can replace the cache policy with `cache-and-network` or I can update the optimisticUpdate to `cache.evict({ fieldName: 'insightViews' })`.  They both appear to get to the desired result, `cache-and-network` is more bandwidth consuming on a regular basis but also probably more reliable.    What do you think is the better approach?
