### ISSUE TITLE
Code Insights: Implement second version of insight error UI

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#44961]
We implemented the first simple version of the timeout error UI in this PR. https://github.com/sourcegraph/sourcegraph/pull/43842

In this issue, we should
- Revamp timeout error UI (include information about timeout points). See [designs](https://www.figma.com/file/aMO6sPoUHDUUcqa25wFnWl/Surface-timeout-limit-hit-to-end-users-in-the-UI-%2339969-Ready-for-dev?node-id=260%3A11&t=Rn4YdAyQ9KWclcui-0)
- Add handling and simple UI for more general errors (non-timeout errors). See draft PR from @coury-clark here https://github.com/sourcegraph/sourcegraph/pull/44956

/cc @joelkw @felixfbecker @vovakulikov

**Comment by vovakulikov** [comment]
After conversation with @AlicjaSuska and @coury-clark we need to clarify a few points about second version of error UI. 

## Current state
- A week ago @coury-clark added extended API with generic error types (basically all errors that may happened on the backend during backfill except timeout errors).
- The current state of original V2 designs doesn't cover all error types (timeout and generic error, it covers only timeout error UI) 
- We need to adjust design in order to get along with different error types in error UI 

## Design decisions
- Since we could have different types of errors within one series (one point has timeout other point has generic error) we need to group errors not by error type but by points 

![Untitled-2022-11-24-1256-7](https://user-images.githubusercontent.com/18492575/206007837-e1c9f975-f249-4dbc-9677-7f15e7846f35.png)

- Originally we agreed on that when all series have got at least one error we render insight level error icon, in order to reduce visual noise from many icons next to series. But since we don't want to have a super complicated insight error tooltip with list of all errors from all series, we decided that we won't have insight-level error UI for the search-based insight. 

- Only Capture group insight will have insight-level error UI since capture group insight can have only one error type for all series. (like it has all series that are timeout or all series with generic errors) cc @coury-clark to confirm. 

cc @AlicjaSuska @Joelkw

**Comment by coury-clark** [comment]
The 3 error types we categorize right now are :
1. Timeout
2. Exceeds error limit (the series was disabled because it had more errors than the error limit allows)
3. Generic (anything not above)

**Comment by coury-clark** [comment]
> Only Capture group insight will have insight-level error UI since capture group insight can have only one error type for all series. (like it has all series that are timeout or all series with generic errors) cc @coury-clark to confirm.

That sounds fine. The capture group insight is limited through the form to a single series anyway, so the scenario of multiple error types per point would only be relevant for search insights.

**Comment by vovakulikov** [comment]
@coury-clark 
>2. Exceeds error limit (the series was disabled because it had more errors than the error limit allows)

But we still will get array of incomplete points for this type of errors, right? The part about _"the series was disabled because it had more errors than the error limit allows"_ sounds like this type of error applies for the whole series not the points within this series.

**Comment by vovakulikov** [comment]
@coury-clark also you specified three types of errors above but I see that currently we have only two implementations of `IncompleteDatapointAlert` interface, is it because Exceeds error limit and Generic are different only by reason (error message) field. Or Exceeds error limit type is not implemented yet?
