### ISSUE TITLE
Permissions scale testing followup

### ISSUE THREAD

**Issue by kopancek** [sourcegraph/sourcegraph#44988]
Tasks

(all of these tasks should be split up into separate tickets with the correct "estimate" label assigned)

- [ ] Run those tests (see google doc) (blocked right now by dev-experience) (`1d`)
- [ ] Experiment: migrate database `permissions` table to new format (test performance locally) (`2d`)
- [ ] Disable repo-based permission syncing (only rely on user-based permission syncing) (`4d`)
    - [ ] First task is to find out how to implement this confidently, so that we can test/debug it and explain to Product/CE what this change does 
    - [ ] Come up with 1-paragraph explanation "why" we're doing this
    - [ ] Change default, don't migrate old customers
    - [ ] Docs page that explains difference between user- and repo-based permission syncing.
        - Page should explain in napkin-math: "If you have 300 repos and 150 users, we will do X requests in Y hours" 
    - [ ] Changelog entry
    - [ ] Communicate to CE
- [ ] Define SLAs (milan is already working on it, but no ticket exists yet, `1d`)
- [ ] Collab with Ryan P to define what ping data we need, then update ping data accordingly (`3d`)
- [ ] Sub-repo permissions: collect [customer](https://github.com/sourcegraph/accounts/issues/6716) metrics on sub-repo permissions
    - [ ] review current metrics and propose new ones if needed (`1d`)
    - [ ] make sure our test instance for perforce is working as expected (timebox `2d`)
    - [ ] add docs on how a dev could setup and test  perforce (those items are in my to-do list) (`1d`)

/cc @sourcegraph/iam

**Comment by pjlast** [comment]
Repo-based permissions syncing is fundamentally flawed. User OAuth tokens can be scoped to have specific permissions, and repo-based permissions syncing does not care about those scopes, as it uses the "ground truth" instead of what the user is able to see.

We've had minor run-ins with this before (GitLab oauth tokens expiring comes to mind). But from a fundamental perspective, it is better to rely only on user-based permissions syncing.

**Comment by kopancek** [comment]
I'm closing this issue in favor of all the children issues that I created:
- #45195 
- #45183 
- #45191 
- #45192 
- #45186 
- #45193
