### ISSUE TITLE
Zoekt unloading repositories, driving high requests to Bitbucket Server

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#4498]
- **Sourcegraph version:** 3.4.0

Reported by https://app.hubspot.com/contacts/2762526/company/557889642

>there was a lot of requests to out Bitbucket server, so I’ve configured "repoListUpdateInterval": 60,. But after doing so I found out, there’s another.
>
>In logs I can see zoekt is unloading repositories. According to disk space those repositories are still on the disk, but when I look into Sourcegraph UI I can see those repos are marked as “Not cloned”, so when I try some search I won’t get data from those repositories. Until I visit them through UI, so they load again.
>
>`$: 12:25:31    zoekt-webserver | 2019/06/13 12:25:31 unloading: /var/opt/sourcegraph/zoekt/index/<repo>_v15.00002.zoekt”`
>
>Is this normal behavior? 
>In the past we ran into the problem where there was disk overflow so Sourcegraph stopped working. We are at 94GB from 10GB at the moment. Did you apply some change that prevents overflow, so it doesn’t store all data and is randomly rotating repositories instead?

Should we recommend bumping disk size here (assuming the user mean "94GB from 10**0**GB")?

**Comment by ijt** [comment]
We recently added a periodic cleanup in `repo-updater` that makes sure there is `$SRC_REPOS_DESIRED_FREE_GB` (defaults to `10`) of free disk space by removing old repositories.

That doesn't quite match what they're describing but let's recommend bumping the disk size to something like 200GB and see if that fixes it.

**Comment by dadlerj** [comment]
Helpful, thanks! How is it different from what they're seeing? The Zoekt interactions?

**Comment by ijt** [comment]
The difference is that they're saying the repositories are still on the disk, but this cleanup would delete the repositories. When I manually delete repos in `~/.sourcegraph/repos` I don't see `zoekt-webserver` unloading anything, so I guess what they're seeing is caused by something other than the `repo-updater` cleanup.

**Comment by dadlerj** [comment]
From the user, increasing disk space cleared up this issue entirely.
