### ISSUE TITLE
Paginate Blob GraphQL API

### ISSUE THREAD

**Issue by varsanojidan** [sourcegraph/sourcegraph#44990]
Related to: https://github.com/sourcegraph/customer/issues/1309
Example of issue: https://sourcegraph.com/github.com/microsoft/TypeScript/-/blob/src/compiler/checker.ts

Working towards better performance for large repos (and large files in general), the Blob API sends back all of the content of a file at once, which causes large files to appear painfully slowly in the UI (see above). The API should be paginated in order to make the UI more responsive.

<img width="670" alt="image" src="https://user-images.githubusercontent.com/20795805/205046454-e107c42e-7e58-4a7e-bd0e-8fe42f9cfa27.png">

/cc @jplahn @ryphil

**Comment by mrnugget** [comment]
Note from Grooming Meeting: putting `3d` as a timebox and guardrail on it. After 3d we should decide where we are and what to do in next iteration.

**Comment by varsanojidan** [comment]
Done: https://github.com/sourcegraph/sourcegraph/pull/45435
