### ISSUE TITLE
Add 'Great Place to Work' badge to the careers page

### ISSUE THREAD

**Issue by fabicastp** [sourcegraph/sourcegraph#44996]
Add badges to the careers page 
[Images](https://drive.google.com/drive/folders/1NLJ5G8h9T9cS9Rdc8rDLZa-PJ-Lyq7Ab): 
-We're_certified 
-Amazing_culture

Mockup coming soon --> Tracey is sick and OOO but this is on their to-do list.

**Comment by malomarrec** [comment]
Hey @ryphil, it looks like this issue was created by someone outside Sourcegraph. Assigning you to triage it! Please answer and route to the right team by adding their team label, then **remove** the `triage-bot/needs-triage` label

**Comment by fabicastp** [comment]
Hi there! This is Fabiana, I work here :') 

@taylorsperry [mockup is ready](https://www.figma.com/file/ZSrUNnMU0sa9I41VOPpj0V/Careers-page?node-id=0%3A1&t=Q6zcEJfVZ1hMQbqU-0)
