### ISSUE TITLE
Hierarchical view of search results and references

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#4502]
Requested by https://app.hubspot.com/contacts/2762526/company/436902646

#### Feature request description

* The user would _love_ more hierarchical/visual/relational ways of viewing search or reference results, e.g.:
 * Show search results in a file tree format (use case: is this component used widely across the company, or only on one library/team?)
 * Show search results in a code ownership tree
 * Show references in a semantic/module hierarchy
 * Etc

#### Is your feature request related to a problem? If so, please describe.

Example use case:
* Lots of pages in a frontend app, owned by different teams
* Looking for a certain data structure, not sure which one to use
* Sometimes the name alone is enough, but sometimes you run into similarly named things (e.g. “user”) and you either can or can't reuse the code from another team
* How to determine: are it’s usages all in one part of the app? Or are they spread among different trunks of the tree?
* Today people do this via a mental map in their head, but it could be automatically generated

This is a reflection of Conway's law — the code looks like the organization

**Comment by camdencheek** [comment]
Closing since I don't think we have any plans to do this, but I do think it's an interesting idea still. cc @taiyab for design inspiration
