### ISSUE TITLE
Bug in `fork:` filter results on sourcegraph.com

### ISSUE THREAD

**Issue by DaedalusG** [sourcegraph/sourcegraph#45036]
- **Sourcegraph version:** 4.2.0
- **Platform information:** sourcegraph.com, chrome

#### Steps to reproduce:
1. Run the following search with filters on dotcom
```
-lang:Kotlin file:"build.gradle" content:org.checkerframework.checker select:repo archived:yes count:all
```
<img width="392" alt="Screen Shot 2022-12-01 at 2 37 57 PM" src="https://user-images.githubusercontent.com/13024338/205182514-23e0c3c3-cbe1-4048-849b-d48bfb18ab90.png">

Using the UI add the `fork:` filter
```
-lang:Kotlin file:"build.gradle" content:org.checkerframework.checker select:repo archived:yes count:all fork:yes
```
<img width="1169" alt="Screen Shot 2022-12-01 at 3 45 56 PM" src="https://user-images.githubusercontent.com/13024338/205182674-15d73508-c5e3-4831-b1ea-d99c52472281.png">

_Note you'll get 22 results each time none listed as forks_
2. Now run the same search again, but specify a popular repo pattern for the search
```
-lang:Kotlin file:"build.gradle" content:org.checkerframework.checker select:repo archived:yes count:all fork:yes repo:checker-framework
```
<img width="1494" alt="Screen Shot 2022-12-01 at 3 30 04 PM" src="https://user-images.githubusercontent.com/13024338/205180945-29b7d2e1-d380-4c18-b95a-60e9da6b8a9b.png">
_Note that there are now repos returned specified as forks_

#### Expected behavior:
The forked repos should be returned in search results for the general search without the `repo:` filter when the UI is used to add the `fork:` filter. Or the UI should not suggest the `fork:` flag to users when `repo:` filter is not also present in the initial search.

#### Actual behavior:
The `fork:` filter is suggested in a general search for `type:repo` wether or not `repo:` is being used. Some results are only returned if `repo:` is in use.

If you would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are no [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

/cc @sourcegraph/search-product

**Comment by camdencheek** [comment]
This is working as intended. The short version is that a query without a `repo:` filter is a "global search" (with caveats). Global searches do not search unindexed code by default on sourcegraph.com for performance and cost reasons.

When you add a `repo:` filter, global search is deactivated, so repos that are not indexed are searched. You'll notice that the forks returned when the `repo:` filter is added have one and two stars, which is below the threshold of what is indexed on sourcegraph.com by default. 

Note that this behavior only exists on sourcegraph.com. It should work as you described on a customer instance.

**Comment by camdencheek** [comment]
I think there is an additional point of confusion here about the wording of the "results skipped" popup. It's not actually "results skipped", it's "repos that weren't searched".

**Comment by DaedalusG** [comment]
Gotcha, I agree this is a bit confusing due to unique behaviors on dotcom, will go ahead and close since its not a bug in the resolvers though 👍
