### ISSUE TITLE
Insight filtered by context shows no data

### ISSUE THREAD

**Issue by nihaals** [sourcegraph/sourcegraph#45032]
- **Sourcegraph version:** 4.2.0

#### Steps to reproduce:

1. Create a context set to `repo:^github\.com/sourcegraph/sourcegraph$ OR repo:^github\.com/sourcegraph/about$`
2. Create an insight ("Track changes" or "Detect and track patterns") for `github.com/sourcegraph/sourcegraph` with results
3. Notice results on the graph
4. Filter the insight to the created context
5. Notice results disappear
6. Edit the context to `repo:^github\.com/sourcegraph/sourcegraph$`
7. Notice results show
8. Edit the context to `repo:^github\.com/sourcegraph/`
9. Notice the results show

#### Expected behavior:

The results show in all 3 cases (matching making a manual search query).

#### Actual behavior:

The results only show in 1 of the cases and shows no results in the other 2 cases (screenshot below).

<img width="275" alt="image" src="https://user-images.githubusercontent.com/18350092/205175572-3b7a0e87-13d1-40c2-8c93-750cb0b4f532.png">

#### Additional context:

This also affects creating an insight for all repos, this was just used as a MWE to make it more clear that the results should be included.

/cc @joelkw @felixfbecker @vovakulikov

**Comment by malomarrec** [comment]
Hey @macraig, it looks like this issue was created by someone outside Sourcegraph. Assigning you to triage it! Please answer and route to the right team by adding their team label, then **remove** the `triage-bot/needs-triage` label

**Comment by chwarwick** [comment]
This will be included in v4.4.0

**Comment by nihaals** [comment]
> This will be included in v4.4.0

@chwarwick Did it miss the 4.3 cut-off? I see it in the 4.3.0 changelog on `main` but haven't checked the version branch.

**Comment by chwarwick** [comment]
> > This will be included in v4.4.0
> 
> @chwarwick Did it miss the 4.3 cut-off? I see it in the 4.3.0 changelog on `main` but haven't checked the version branch.

@nihaals  It did miss the cutoff and is not included in the changelog on the 4.3 release branch, I'll correct the change log on main.
