### ISSUE TITLE
Percy should not run on release branches

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#4505]
As soon as we start cutting patches, Percy is broken because it is out of sync with master.

- https://github.com/sourcegraph/sourcegraph/commits/3.4
- https://github.com/sourcegraph/sourcegraph/commits/3.3
- https://github.com/sourcegraph/sourcegraph/commits/3.2

etc.

**Comment by felixfbecker** [comment]
We need to set `PERCY_TARGET_BRANCH` in CI when running on release branches to the release branch itself

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
