### ISSUE TITLE
Can't connect Sourcegraph with OIDC auth provider with custom SSL cert

### ISSUE THREAD

**Issue by ajaynz** [sourcegraph/sourcegraph#45060]
- **Sourcegraph version:*4.1.2* 
- **Platform information:*N/A* 

#### Steps to reproduce:

1. Configure an OIDC auth provider with a self signed cert
2. Configure the following in Sourcegraph site config:
```
"experimentalFeatures": {
       "tls.external": {
         "certificates": [
           "-----BEGIN CERTIFICATE-----\n..."
         ],
         "insecureSkipVerify": true
       }
  },
```
3. Attempt to connect Sourcegraph with OIDC auth provider

#### Expected behavior:
Sourcegraph should use the configured cert in site config to connect with OIDC auth provider
#### Actual behavior:
The SSL handshake fails and Sourcegraph can't connect.

/cc @sourcegraph/source/iam

**Comment by malomarrec** [comment]
Hey @quinnhare, it looks like this issue was created by someone outside Sourcegraph. Assigning you to triage it! Please answer and route to the right team by adding their team label, then **remove** the `triage-bot/needs-triage` label

**Comment by mrnugget** [comment]
@pjlast You moved this to "Done" -- does this mean we can close this issue?
