### ISSUE TITLE
Confirm support of new GitHub Fine-Grain access tokens and update documentation

### ISSUE THREAD

**Issue by ryphil** [sourcegraph/sourcegraph#45073]
**Description**
GitHub recently introduced new Fine Grain access tokens (see [blog post](https://github.blog/2022-10-18-introducing-fine-grained-personal-access-tokens-for-github)). 

**Problem**
Sourcegraph does not have clear guidance for how customers can take advantage of these tokens. This has already created confusion for [one customer](https://sourcegraph.slack.com/archives/C02EDAQAJQZ/p1669999986995489).

**Solution**

- [ ] Validate new fine-grain access tokens work with Sourcegraph
- [x] Update documentation to outline which scopes are required for new tokens

**Comment by pjlast** [comment]
Issues addressed in this PR: https://github.com/sourcegraph/sourcegraph/pull/45137
