### ISSUE TITLE
Search UI: a case of broken chunk grouping

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#45074]
On expansion of [this query](https://sourcegraph.sourcegraph.com/search?q=context:global+repo:%5E%28github%5C.com/sourcegraph/sourcegraph%29%24+file:enterprise/internal/insights/background/historical_enqueuer.go+%24+count:all&patternType=regexp&sm=0&groupBy=repo), I am seeing duplicated groups. The first chunk appears to be the whole file, and then it's followed by a bunch of duplicate chunks. 

/cc @sourcegraph/search-product

**Comment by malomarrec** [comment]
Hey @camdencheek, this issue didn't have a team label. Given you created it, I assigned you and added your team label. Feel free to unassign yourself. If this is not the right label, can you make sure to add the right one?

**Comment by camdencheek** [comment]
Can't reproduce, closing
