### ISSUE TITLE
Adding a new external service that syncs slowly results in 504 Gateway Timeout

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#4511]
I'm not sure whether we have covered this in any other ticket yet or whether it's a known issue already. It's probably highly related to the idea of turning slow operations into asynchronous ones, but maybe there's an easier fix (such as increasing a timeout somewhere)

#### Steps to reproduce:

1. Go to https://k8s.sgdev.org/site-admin/external-services
2. Add a new external service that sync really slowly, e.g. the GHE service we have in `dev-private` with this config that has two `repositoryQuery` that both yield a ton of repos:
```json
{
  "url": "https://ghe.sgdev.org",
  "token": "<foobar>",
  "repositoryQuery": [
    "public",
    "affiliated"
  ]
}
```
* Click "Add external service" and watch spinner

#### Expected behavior:

Request takes a loooong time but ultimately succeeds

#### Actual behavior:

* Spinner stops
* No confirmation that creation has been successful
* External service has been created (!)
* network tab shows that request resulted in `504 Gateway Timeout`

**Comment by mrnugget** [comment]
Does this maybe have something to do with the Cloudflare configuration in place on the k8s dogfood instance? The 504 error page in the response seems to come from Cloudflare. cc @beyang @slimsag

**Comment by slimsag** [comment]
Almost always any Cloudflare error is something wrong with our app, not Cloudflare. A 504/502 usually signals that our app either crashed (likely) or disconnected for some reason (e.g. running out of resources like FDs or something).

I would start by checking if the pods have restarted unexpectedly and grep the logs for panics.

**Comment by mrnugget** [comment]
As another data point: I can **not** reproduce this locally by, for example, adding a `time.Sleep(70 * time.Second)` to the `GithubSource` to make it slow

**Comment by mrnugget** [comment]
In the logs for `repoupdater` I can find this after ~60s:

```
E  t=2019-06-14T10:57:29+0000 lvl=eror msg=source.list-repos error="1 error occurred:\n\t* context canceled\n\n"
 
E  t=2019-06-14T10:57:29+0000 lvl=eror msg=source.list-repos error="2 errors occurred:\n\t* context canceled\n\t* context canceled\n\n"
 
E  t=2019-06-14T10:57:29+0000 lvl=eror msg=source.list-repos error="2 errors occurred:\n\t* context canceled\n\t* context canceled\n\n"
 
```

Seems like there's a 60s timeout _somewhere_, but I couldn't find it this morning or yesterday.

**Comment by ijt** [comment]
I ran into this on a local Docker instance while trying to update an external Github Enterprise service (testing task 9.2):

<img width="744" alt="Screen Shot 2019-06-18 at 13 07 19" src="https://user-images.githubusercontent.com/15530/59716309-9e7e2800-91ca-11e9-88d8-fcb256da1763.png">

(token redacted).

The logs show something similar to what @mrnugget reported:
```
20:01:02       repo-updater | t=2019-06-18T20:01:02+0000 lvl=eror msg=source.list-repos error="1 error occurred:\n\t* context canceled\n\n"                                       
20:01:02       repo-updater | t=2019-06-18T20:01:02+0000 lvl=eror msg=server.external-service-sync kind=GITHUB error="syncer.sync.sourced: 1 error occurred:\n\t* context canceled\n\n"
20:01:02              nginx | 2019/06/18 20:01:02 [error] 122#122: *452 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 172.17.0.1, server: , request: "POST /.api/graphql?UpdateExternalService HTTP/1.1", upstream: "http://127.0.0.1:8080/.api/graphql?UpdateExternalService", host: "localhost:7080", referrer: "http://localhost:7080/site-admin/external-services/RXh0ZXJuYWxTZXJ2aWNlOjE="
```

**Comment by ijt** [comment]
I just tried it again and this time it worked.

**Comment by ggilmore** [comment]
This issue appears in 3.4.4, so it isn't a release blocker.
