### ISSUE TITLE
Unicode search results has wrong highlights on web page

### ISSUE THREAD

**Issue by xingx-xx** [sourcegraph/sourcegraph#4512]
It's easy to reproduce when searching non-ascii words like below
`repo:^github\.com/xingx-xx/knative-sample-app$ type:commit 加`

**Comment by xingx-xx** [comment]
Probably this is an issue about []rune and []byte, bacause the word 加 is taking 3 bytes

**Comment by slimsag** [comment]
Thanks for reporting, looks like this is a bug. Will see when we can get around to fixing this in our upcoming planning sessions (also happy to accept a PR and provide guidance if anyone is interested in working on this sooner).

**Comment by ijt** [comment]
I reproduced it locally with indexed search:

![Screen Shot 2019-06-25 at 16 14 17](https://user-images.githubusercontent.com/15530/60139844-52039100-9764-11e9-9c4e-df1a232443c6.png)

and with non-indexed search:

![Screen Shot 2019-06-25 at 16 14 07](https://user-images.githubusercontent.com/15530/60139848-53cd5480-9764-11e9-8db5-cdb8df7ac785.png)

**Comment by ijt** [comment]
The graphql schema says the offsets are supposed to be in characters, not bytes, so that suggests it's a bug on the backend.

https://sourcegraph.com/github.com/sourcegraph/sourcegraph@511fe1eabfacf5bf57aba7ca69ddc297841e6485/-/blob/cmd/frontend/graphqlbackend/schema.graphql#L2080:34
