### ISSUE TITLE
Add instrumentation metrics to Sign-up journeys

### ISSUE THREAD

**Issue by almeidapaulooliveira** [sourcegraph/sourcegraph#45169]
### Related design issue:
- #44097

### Description

Our [key metric](https://docs.google.com/document/d/1-M1iM-rCCZk0aPDx78ARWLxBbbGSVup_3hVVa1mG8Xo/edit?pli=1#bookmark=id.a0uyr0duh63g) is activations. We'll configure pings that form tracking funnels for the activation journeys and measure how they convert over time.

Add event for the following pages:

- [x] CTA on the search results page.
- [x] CTA on context dropdown.
- [x] CTA on Notebooks pages.
- [x] CTA on Code monitoring pages.
- [x] CTA on Batch Changes pages.
- [x] CTA on Insights pages.
- [x] CTA on homepage.

Figma page with defined events:
https://www.figma.com/file/ScpDpxciO5DeT9YlUGzPUX/UX%3A-Sign-up-journeys-for-auth'd-users?node-id=1%3A2316

**Comment by almeidapaulooliveira** [comment]
Cc: @taylorsperry

**Comment by bretthayes** [comment]
Closing this since all of these CTAs already have event logs tied to them and we have a [Dashboard](https://analytics.amplitude.com/sourcegraph/chart/new/xsbui43) in Amplitude to track and filter these per URL. So manually adding the `origin` param is not necessary.
