### ISSUE TITLE
Merge on-call and support rotations for repo management team

### ISSUE THREAD

**Issue by indradhanush** [sourcegraph/sourcegraph#45164]
Currently we have two rotations:
1. Repo Management On Call - To route opsgenie alerts
2. repo-management-support - To connect @repo-management-support Slack handle via Slackgenie each week

This causes confusion and extra work for overrides. We should consolidate onto either one of these rotations to make it easier and remove any confusion for ourselves.

/cc @jplahn @ryphil

**Comment by mrnugget** [comment]
Fixed
