### ISSUE TITLE
2XL: Experiment: migrate database `permissions` table to new format

### ISSUE THREAD

**Issue by kopancek** [sourcegraph/sourcegraph#45183]
This is an experiment to verify our current assumption that the way we store repo permissions in Postgres at the moment is not efficient.

Right now we store effective permissions in 2 tables:
1. `repo_permissions`
2. `user_permissions`

We also use arrays to represent which users have access to which repos, which seems inefficient from the perspective of reading such data and indexing it.

We also store what we call `pending_permissions` for entities we do not have on sourcegraph side (either repos or users, so those are `repo_pending_permissions` and `user_pending_permissions` respectively. Those are however out of scope for this experiment.

Sub-repo permissions are also out of scope of this experiment.

The purpose of the experiment is to store the permissions in 1 table only. The new table is going to be named `code_permissions` and store the permissions in the following columns:
`id (int autoincrement, primary key; user_id (int, foreign key), repo_id (int, foreign key), updated_at(timestamptz)`

So instead of storing in 2 tables, we store in just 1 table. Instead of storing arrays, we leverage the relational model of the database and store a record for each repo-user pair.

To verify the performance, create an SQL dump of the `user_permissions` table from the scaletesting.sgdev.org instance. Load it locally into an empty sg postgres DB. 

Mimic locally with SQL script what the authzQuery does to test performance of the old format vs the new format on the read path.
Mimic locally with SQL script what the permissions sync does to test performance of the old format vs the new format on the write path.

Compare the results. If the experiment yields positive performance improvements, create a followup github issue to implement the change.

/cc @sourcegraph/source/iam

**Comment by kopancek** [comment]
The SQL dumps of `repo_permissions, user_permissions, users` tables are [uploaded in our google drive](https://drive.google.com/drive/folders/1zEv42GknF3ibDyFzAav1cQnfBtCmhMMd?usp=share_link)

**Comment by kopancek** [comment]
# Local tests

I have tested with the above dumps of tables. I have imported the tables into the same Postgres docker instance as I use for my local sg development. However I have created a new test db to dump the tables into, not to pollute my local environment.

During the course of working on the experiment, I found out, that I also need the `repo` table, at least to be able to add a foreign key reference to `repo_id` column in the newly created `permissions` table. I created a simple table with only the `id`, `created_at` and `private` columns and filling it with sql query: 

```sql
INSERT INTO repo (SELECT DISTINCT repo_id FROM permissions);
```

Dump of the complete database is available on [google drive](https://drive.google.com/file/d/1ks21jUHZF5gdkSShGv5d4vtMfDXo_WVi/view?usp=share_link).

For now, the `permissions` table only contained these columns:
![Image](https://user-images.githubusercontent.com/9974711/213452798-b04ab589-355f-4cbf-8423-b20bc9f8982a.png)

There were also following indexes:

![Image](https://user-images.githubusercontent.com/9974711/213452920-106cf65b-e744-47d9-b7d0-1bf32e45b4e5.png)

## Test results

### AuthzQuery

I first tried to replicate the (rather complex) query that we do in [AuthzQuery part of the code](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/database/repos_perm.go?L62) which is used accross the product to access repositories (e.g. search, batch changes, etc.).

The original query modified to work on the local environment looks like this: 

```sql
SELECT id FROM repo WHERE repo.id IN (127777,92725,92887,92963,93257,93277) 
AND (
  (   -- Restricted repositories require checking permissions
      SELECT object_ids_ints @> INTSET(repo.id)
      FROM user_permissions
      WHERE
          user_id = 42290
      AND permission = 'read'
      AND object_type = 'repos'
  ) 
--   OR (
--     -- Unrestricted repos are visible to all users
--     EXISTS (
--       SELECT
--       FROM repo_permissions
--       WHERE repo_id = repo.id
--       AND unrestricted
--     )
--   )
)

```

I commented out the unrestricted repositories part, as I only have private restricted repositories on my instance, so it does not make sense to run it. Also, the order of the clauses might be a little bit different as a result. But it closely resembles what we do in production.

The new query for the unified row-per-permission table looks like this:

```sql
SELECT id FROM repo WHERE repo.id IN (127777,92725,92887,92963,93257,93277) 
AND (
  (                             -- Restricted repositories require checking permissions
      SELECT TRUE
      FROM permissions
      WHERE
          user_id = 42290 
        AND permissions.repo_id = repo.id
  ) 
--   OR (
--     -- Unrestricted repos are visible to all users
--     NOT EXISTS (
--       SELECT
--       FROM permissions
--       WHERE repo_id = repo.id
--     )
--   )
)
```

The results of the experiment are collected in a [Google Sheet](https://docs.google.com/spreadsheets/d/1h2aLuKEAX-waSnqj2uOHbRsT9z2L1uC5YhJQvlWWTCE/edit#gid=683317438), but keeping them here as well.
 
The average latency of running the above queries in local SQL client 5 times are as following:

Number of repos | old query [ms] | new query [ms] | improvement
-- | -- | -- | --
200000 | 97750 | 2988.5 | 32.71
1000 | 610 | 145 | 4.21
100 | 166.2 | 92.8 | 1.79

**Comment by kopancek** [comment]
Another part that I focused on is the write path.

I thought that with 2 tables, it's rather simple. E.g. when we sync user permissions, we just update `user_permissions` table with the array of repos the user has access to, so single row update. 

But it turns out, the code says:
<img src="https://media.giphy.com/media/vPN3zK9dNL236/giphy.gif" />

We actually do a [quite involved business logic there](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/database/perms_store.go?L367-L394) to add the same information to the `repo_permissions` table as well (which I forgot about).

So in the end, if we are adding 100 repos to a user, we write 1 row to the `user_permissions` table and then need to compute, how we will modify 100 arrays in the `repo_permissions` table.

I tried to simulate the existing queries again, this is how the current query for adding user permissions for 5 repositories looks like:

```sql
INSERT INTO user_permissions
  (user_id, permission, object_type, object_ids_ints, updated_at, synced_at)
VALUES
  (13, 'read', 'repo', 
   array[127777,92725,92887,92963,93257]
   , now(), now())
ON CONFLICT ON CONSTRAINT
  user_permissions_perm_object_unique
DO UPDATE SET
  object_ids_ints = excluded.object_ids_ints,
  updated_at = excluded.updated_at,
  synced_at = excluded.synced_at;

INSERT INTO repo_permissions
	(repo_id, permission, user_ids_ints, updated_at)
VALUES
	(127777, 'read', array[13], now()),
	(92725, 'read', array[13], now()),
	(92887, 'read', array[13], now()),
	(92963, 'read', array[13], now()),
	(93257, 'read', array[13], now()),
ON CONFLICT ON CONSTRAINT
	repo_permissions_perm_unique
DO UPDATE SET
	user_ids_ints = CASE
		-- When the repository is part of "addedRepoIDs"
		WHEN repo_permissions.repo_id = ANY (array[127777,92725,92887,92963,93257]) THEN
			repo_permissions.user_ids_ints | excluded.user_ids_ints
		ELSE
			repo_permissions.user_ids_ints - array[13]::INT[]
		END,
	updated_at = excluded.updated_at

```

The same query for adding to a unified one-row-per-permission table:
```sql
INSERT INTO permissions
  (user_id, repo_id, created_at, updated_at, reason)
VALUES
  (13, 127777, now(), now(), 'user-based-sync'),
  (13, 92725, now(), now(), 'user-based-sync'),
  (13, 92887, now(), now(), 'user-based-sync'),
  (13, 92963, now(), now(), 'user-based-sync'),
  (13, 93257, now(), now(), 'user-based-sync')
ON CONFLICT (user_id, repo_id)
DO UPDATE SET
  updated_at = excluded.updated_at,
  reason = excluded.reason;
```

Just by looking at the query, we can see that the new one is much simpler.

Running the queries, there is a slowdown in comparison to running it on both tables. This is puzzling, because current query seems to be more complex. There is probably room to improve the write performance more:

Number of repos | old query [ms] | new query [ms] | slowdown
-- | -- | -- | --
1000 | 301 | 689 | 2.29
100 | 107 | 186 | 1.74
5 | 98 | 83 | 0.85

However I am not concerned about write performance that much. Today, our perms syncing performance is limited more by strict rate limits than database writes. Most commonly, users only have access to ~100 repositories or less anyway.

**Comment by kopancek** [comment]
Also noticed, that the slowdown mentioned above only happens on inserting fresh permissions. If the table already contains most of the permissions and we are doing a partial update, it takes the same amount of time on both queries.

**Comment by mrnugget** [comment]
In your benchmark for read performance here https://github.com/sourcegraph/sourcegraph/issues/45183#issuecomment-1397019076 -- how many users did you have? How many entries where in `permissions`?

**Comment by kopancek** [comment]
There are around 40k users and 200k repositories. The distribution of users to repositories is uneven. p90 repository count per user is <100, but there's some users who have access to more than 1000 repositories. 

There's 40k rows in the `user_permissions` table. There's 5 million rows in the unified `permissions` table with 1 row per permission. You can see all of this in the [database dump](https://drive.google.com/file/d/1ks21jUHZF5gdkSShGv5d4vtMfDXo_WVi/view?usp=share_link) I linked above.
