### ISSUE TITLE
Define what ping data do we need for IAM

### ISSUE THREAD

**Issue by kopancek** [sourcegraph/sourcegraph#45192]
Work with @Ryan and define what kind of ping data we are missing and need to add to better understand the business needs of IAM customers (operational pings, usage data, etc.)

Be cautious on adding pings based on what we want to know, not based on the technical feasibility of being able to add 20 new metrics.

We also need very good justification on why we need to collect this type of data. Less is more.

/cc @sourcegraph/source/iam

**Comment by mrnugget** [comment]
I'm closing this, we can reopen once need comes up again.
