### ISSUE TITLE
Collect customer metrics for sub-repo permissions

### ISSUE THREAD

**Issue by kopancek** [sourcegraph/sourcegraph#45193]
We identified 3 subtasks during our grooming meeting in Porto:
- [ ] review current metrics and propose new ones if needed (`1d`)
- [x] make sure our test instance for perforce is working as expected (timebox `2d`)
- [x] add docs on how a dev could setup and test  perforce (`1d`)

/cc @sourcegraph/iam

**Comment by kopancek** [comment]
@miveronese I'm not sure if we should split this further into multiple github issues or if we are fine with keeping them as subtasks in the description.

I also assigned you to this issue. Feel free to make any changes (like making the description better or splitting). Also feel free to unassign yourself if you feel like someone else should work on this task. I mostly did it for the continuity reasons, since you already started working on most of this.

**Comment by mrnugget** [comment]
Note from planning: closing because we're switching to database-backed worker anyway and this would be wasted effort.
