### ISSUE TITLE
System status nav item proposal

### ISSUE THREAD

**Issue by christinaforney** [sourcegraph/sourcegraph#4519]
## Future/consolidation comments:

> Can we consolidate this with the `Setup` item? Currently that is used for the initial onboarding flow. But in a sense it communicates the same thing as StatusMessageItem: "You are in a global state that is maybe not ideal, and here's what that means or how to improve it".

@mrnugget and I discussed this idea on a brainstorming call (partially captured in a [Google doc](https://docs.google.com/document/d/1dnNZobttg1o2BZlgesoDYcinthfuRC3-Vb9mQhIRGqw/edit#heading=h.kpla0aedg1j). Here are the reasons we moved away (some of which you address in later feedback that I will get to):
1. There is a difference between getting started/setup guidance prompts and system status
2. Having a single tray for messages could add to noise causing important system updates to get missed
3. [Neilsen heuristics](https://www.nngroup.com/articles/ten-usability-heuristics/) first principle is to communicate status to users of the system
 
> This UI element essentially becomes our status bar. In the future 🤔...
> 
> * It could start to hold things like the Sentry/LightStep/Datadog/Codecov enablement status:, which would declutter the file header.

I like the idea of adding in Sentry/LightStep/Datadog/Codecov status, it could indicate if there is something wrong with the connection and help with getting that fixed. 

> * It could hold notifications for checks and codemods.

I think this should be separate from "system status" state. If we bundle these together, it will likely become noisy and be easily overlooked. I do agree we need a notification tray to handle these sorts of messages, and should have further discussion about what kinds of things can go here. 

> 
> Here's an idea. It is underspecified; let me know if it would help for me to think through this in more detail.
> 
> * Consolidate both `Setup` and StatusMessageItem into a single global nav item whose icon is a circle.
> * We define the possible states of the circle, like:
>   
>   * a loading/not-loading state (BTW spinning things on screen make me dizzy, as a user I would not want this to be spinning for a long time and globally visible)
>   * a numeric indicator
>   * a look-at-me/severity state
> * We define the possible entries of the menu, using a very simple schema (text + link + tooltip + faded state + loading state) and jam both the current `Setup` items and this new cloning item into the menu
> * If there is anything in the menu that we want to make sure the user sees (eg cloning), we can programmatically open the menu (similar to how Google Cloud opens the operations menu the first time you perform a long-running operation).

I like all of this other than the combination of the two into a single nav item. The different states seem very useful and explicitly communicative. I also really like the opening of the tray when something important happens. 

> The hope is that this would be the 1 place users are trained to look if "something seems wrong" and there is no contextual error. This is similar to how VS Code extensions will show an `X` for broken code intel, linting, Live Share connection, Git syncing, etc., in the status bar, which is where users expect to look. This works acceptably despite it not being focus-grabbing because it's a single place that users need to look.

Totally agree! This doesn't feel aligned with the combination of setup and code mod checks. 

## Updated proposal for next steps

1. Improve cloning notify to handle updates vs. cloning
1. Improve cloning notify to show connection state to each code host
1. Expand cloning notify to be a "system status" tray with visual states
    - loading/not loading
    - numeric indicator (not sure on this one unless we want the status items to acknowledged/dismissable/read, and might be more associated with check notifications)
    - look at me/severity state
1. Continue to add different system configurations to the system status dropdown (that was started as cloning notify)
    - Extensions configured (Sentry, Codecov, Datadog, Lightstep)

Would love thoughts/feedback/input! 

CC: @sqs, @mrnugget

**Comment by felixfbecker** [comment]
This is implemented, right?

**Comment by christinaforney** [comment]
Sort of - this is a high level proposal for improvements + future plans. This was pre-RFCs, and really should have been an RFC. Let's close it, but @imtommyroberts - FYI on original thinking about the status indicator.
