### ISSUE TITLE
insights: live preview for up to N matching repos of a repo query

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#45219]
Given a valid strategic scoped insight query provide a live preview with up to N (probably 20) repos.

/cc @joelkw @felixfbecker @vovakulikov

**Comment by chwarwick** [comment]
p0

**Comment by chwarwick** [comment]
Group by insight is not included.

**Comment by chwarwick** [comment]
closed by https://github.com/sourcegraph/sourcegraph/pull/45910 and https://github.com/sourcegraph/sourcegraph/pull/45824
