### ISSUE TITLE
Re-enable `TestConvertLSIF` after fixing flakiness

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#45251]
`TestConvertLSIF` seems flaky because sometimes this symbol has a comment string and sometimes it doesn't: https://github.com/sourcegraph/sourcegraph/blob/c58b9e9ef6116be7412e0047c78d3673315ab634/lib/codeintel/lsif/scip/index_test.go#L79

**Comment by efritz** [comment]
Fixed by changes in #45104.

**Comment by mrnugget** [comment]
Thanks!
