### ISSUE TITLE
GCP: Create vendor-projects folder and create a tackle.io project

### ISSUE THREAD

**Issue by kalanchan** [sourcegraph/sourcegraph#45362]
Ask from Tom Pickney to create a new GCP project for tackle.io to list Sourcegraph on the GCP marketplace. 

In addition to this ask, we need to create a new `vendor-projects` folder at the top level of the Sourcegraph org to isolate permissions. Moving forward this folder will host all related vendor projects.

Please review https://sourcegraph.slack.com/archives/C03UZ353D8A/p1670280635395049?thread_ts=1669003325.274609&cid=C03UZ353D8A for more context.

Tasks:
- Create top level `vendor-projects` folder, under the Sourcegraph org in GCP
- Follow [instructions](https://docs.google.com/document/d/e/2PACX-1vQ5c74PUfgFTbGVjEH22R9sq2H5QzuSzO7msa2EAs2Mwl14wg7l9qoZpIXrhKN5c-cPmcY992QQJxT2/pub) and complete step 2.
- Create service account and assign correct roles to it. Confirm permissions are isolated in that project only and add Tackle.io team member IAM

**Comment by daxmc99** [comment]
Suggested additional task: 
- Get security sign-off before providing the customer access since this requires `owner` level access which CANNOT be avoided: https://docs.google.com/document/d/e/2PACX-1vQcnuZZ_XeIdcMXW1TbFNk27KbuH_e5coOUaqGE7jNo5dlE248aD2NkPpYoKFvGuJBHTW5hWGDbMDNi/pub?dods&urp=gmail_link

**Comment by mohammadualam** [comment]
> Suggested additional task:
> 
> * Get security sign-off before providing the vendor access since this requires `owner` level access which CANNOT be avoided: https://docs.google.com/document/d/e/2PACX-1vQcnuZZ_XeIdcMXW1TbFNk27KbuH_e5coOUaqGE7jNo5dlE248aD2NkPpYoKFvGuJBHTW5hWGDbMDNi/pub?dods&urp=gmail_link

Dax, in your opinion do you see an issue with providing this if the project is isolated into separate GCP folder or other more feasible way?

**Comment by daxmc99** [comment]
I do not. 
This request is mostly for awareness. This is the highest level of access we have granted to an external entity (as far as I'm aware). 

I don't think we can move forward without it, but I felt security should be aware and sign-off. 
(ie have this conversation here)

I believe this falls under the security team's purview from the handbook

>Proactively improve the security of our application and infrastructure. Includes [continuous code reviews](https://handbook.sourcegraph.com/departments/security/continuous-code-review-process)

**Comment by daxmc99** [comment]
Also should have been more specific that the review I suggested is a "code review" not a general security review of the approach. I was 99% sure you all would approve but I thought it best practice to let you all know.

**Comment by mucles** [comment]
Update: tackle project was created
