### ISSUE TITLE
insights: x axis labels are cut off when they are rotated

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#45371]
When labels along the x axis are rotated in line charts the label for the most recent time is cut off.  

<img width="770" alt="image" src="https://user-images.githubusercontent.com/6098507/206280351-580ebbcc-23b6-4bb8-af76-f963e289fbae.png">

/cc @joelkw @felixfbecker @vovakulikov

**Comment by chwarwick** [comment]
may be a duplicate

**Comment by st0nebraker** [comment]
Duplicate to #39876
