### ISSUE TITLE
Test PR which adds branch support to P4Fusion

### ISSUE THREAD

**Issue by ryphil** [sourcegraph/sourcegraph#45396]
A user submitted a PR to P4Fusion which adds branch support. Before upgrading the version we use, we should rigorously test the new version with Sourcegraph. Neither we not Salesforce know the person who submitted this PR so we need to be extra thoughtful about testing this change. 

PR can be found [here](https://github.com/salesforce/p4-fusion/pull/61).

/cc @jplahn @ryphil

**Comment by mrnugget** [comment]
@peterguy it looks like you're working on this (based on https://github.com/salesforce/p4-fusion/pull/61#issuecomment-1640524094), so I'm assigning to you and removing from `Source` board.
