### ISSUE TITLE
Add drop shadow to browser extension overlay

### ISSUE THREAD

**Issue by christiancueto** [sourcegraph/sourcegraph#454]
#### Feature request description

Add drop shadow to chrome extension overlay.
While the overlay styling to match GitHub's styling is spot on, I think adding some drop shadow to the overlay will allow it to stand out on the page. In my opinion, it can get lost a bit because it blends in to the background so well.

#### Additional context

![drop_shadow](https://user-images.githubusercontent.com/8916062/47224364-52ec5380-d389-11e8-92d1-7e40493ffa4b.gif)

**Comment by francisschmaltz** [comment]
@ijsnow and I have talked about this and are working on implementing it. Can you file this in the browser extension repo.

**Comment by francisschmaltz** [comment]
https://github.com/sourcegraph/browser-extensions/issues/255
