### ISSUE TITLE
Alert for repository permissions syncing is cleared even though it is not resolved

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#45422]
- **Reported by:** https://github.com/sourcegraph/accounts/issues/6716 via [Slack](https://sourcegraph.slack.com/archives/C01D50MSA7L/p1670450819509659?thread_ts=1670419077.674789&cid=C01D50MSA7L).
- **Sourcegraph version:** 4.0

#### Description

When troubleshooting a permissions issue, administrators received notifications llike:

`Critical alert 'perms syncer sync errors' is firing for service 'repo-updater' (repo-management). For next steps, please refer to our documentation: ...`

and a few minutes later would receive the resolution notification:

`Critical alert 'perms syncer sync errors' for service 'repo-updater' has resolved`

but, in reality, this alert had not actually been resolved

If you would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are no [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

/cc @jplahn @ryphil

**Comment by mrnugget** [comment]
I'm closing this because we switched away from the perms syncer that's being referenced here. We have a new one that works differently. Not saying that it won't cause these errors, but that this ticket is not actionable for us right now.
