### ISSUE TITLE
Symbols: Present Symbols in a tree-view.

### ISSUE THREAD

**Issue by JSteeleIR** [sourcegraph/sourcegraph#4544]
#### Feature request description
Right now, the symbols pane presents all symbols in a single-layer view. 
While they are "ordered" properly, (that is, methods are underneath the class they belong to), it'd be really nice if it were possible to view them in a Tree, so that it's possible to collapse symbols for all other classes and expand only the class I'm looking at.

#### Is your feature request related to a problem? If so, please describe.

Some repos/files have a lot of classes/methods, and therefore a lot of symbols in the pane. This looks pretty cluttered ATM.

#### Additional context

Preferrably, this could be implemented with a selector for view method (scoped to current file/whole package, flat-view/tree-view) and a "expand/collapse" all method.

**Comment by jeanduplessis** [comment]
@macraig FYI: https://twitter.com/Franklin_YZL/status/1404646869951680516

**Comment by chrismwendt** [comment]
Closing in favor of https://github.com/sourcegraph/sourcegraph/issues/41778
