### ISSUE TITLE
RFE: allow the administrator to manage empty and corrupt repositories

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#45487]
**Requested by:** https://github.com/sourcegraph/accounts/issues/6716 via [Slack](https://sourcegraph.slack.com/archives/C01D50MSA7L/p1670565934599759)

#### Feature request description

Even if repositories appear "empty", allow administrators to access the management interface for the repository.  In particular, access to "reclone" button.

#### Is your feature request related to a problem? If so, please describe.

When troubleshooting an "empty" repository, the admin discovered that it wasn't empty on the code host side. That likely means it's corrupt on Sourcegraph.  And, they would like to tell Sourcegraph to re-clone it without needing to exec into the gitserver.

Direct quote:
> allow admins to manage repos, even if they look empty. This repo isn’t empty on the code host, so it’s probably corrupted on the Sourcegraph disk. I need to be able to see code host connectivity / sync / etc. information from repo settings to troubleshoot, remediate / delete and reclone the repo, but the settings button isn’t available when the repo appears empty.

/cc @jplahn @ryphil

**Comment by gl-srgr** [comment]
I noticed this was reported a while back, in 2019, and from the limited info it's the same exact issue. https://github.com/sourcegraph/sourcegraph/issues/5138

**Comment by mrnugget** [comment]
@gl-srgr just to confirm: you are working on this, right?

**Comment by gl-srgr** [comment]
@mrnugget yes I'm working on this at this time

**Comment by gl-srgr** [comment]
PR 46554
