### ISSUE TITLE
Docs no longer show quickstart `docker run` command on first page

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#455]
The old docs landing page had the quickstart (i.e., the `docker run` command) front and center. Since that's been there, we now have links throughout the app that point to the docs landing page for instructions on how to set up Sourcegraph. 

Was it intentional to remove it @sqs? I will add it back now if not. At the very least, I want to add a big/bright link to our quickstart front and center on that page.

**Comment by sqs** [comment]
No, please add it back

**Comment by sqs** [comment]
Fixed on https://docs.sourcegraph.com/
