### ISSUE TITLE
Code Insights: Data series limited to 10 

### ISSUE THREAD

**Issue by gabtorre** [sourcegraph/sourcegraph#45575]
- **Sourcegraph version:** 4.2.0 

#### Steps to reproduce:

1. Create a search-based code insight with more than 10 data series.

#### Expected behavior:
Any number of data series can be edited.

#### Actual behavior:
Only the first 10 data series can be edited,  anything over 10 is disabled.

<img width="607" alt="Screen Shot 2022-12-12 at 10 19 43 AM" src="https://user-images.githubusercontent.com/69164745/207125961-53e43cf3-68b6-4d26-90c4-b8fb6cba9a81.png">

If you would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are no [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

/cc @joelkw @felixfbecker @vovakulikov

**Comment by Joelkw** [comment]
@vovakulikov I suggest p0 for next triage – seems like an easy fix (my assumption) and is blocking the customer.
