### ISSUE TITLE
Make Sourcegraph deployable on local machine as a single Go binary

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#45596]
I will be running with / taking on https://github.com/sourcegraph/sourcegraph/discussions/45134

Immediate goals:

* [ ] Review Quinn's work
* [ ] Merge Quinn's work into `main` without breaking `main`
* [ ] Make release binaries exist somewhere, maybe `brew install`-able

Other things I must address:

* [ ] https://github.com/sourcegraph/sourcegraph/issues/45594 (ditch Java dependency)
* [ ] Isolate subprocess resources with e.g. cgroups
* [ ] Find an approach to "replicas" for services (e.g. 'run three gitservers') so we can eventually run in prod / not just on local machines.

/cc @sourcegraph/delivery

**Comment by peterguy** [comment]
An initial stab at a to-do list
===
Vaguely in order of importance; no real distinction between must-haves and nice-to-haves

* [ ] fold in blobstore
Requires [Rewrite blobstore in Go](https://github.com/sourcegraph/sourcegraph/issues/45594)

* [ ] fold in redis or convert to postgresql
To eliminate another dependency.
Maybe use embedded redis, like [ledis](https://ledisdb.io/) or similar?

* [ ] generate random password for embedded postgres
To alleviate security concerns. Could store it in a file readable only to the current user, and/or encrypted (with what key?)
Maybe this is not actually required. The contents of the database are not sensitive, are they?

* [ ] fold in ctags
Currently calling `docker run` on a `ctags` container (which doesn't work for me: docker complains about not being able to find the image; haven't done any debugging of that).
Desired state is to call the [universal-ctags](https://github.com/universal-ctags/ctags) binary. Requires building from source or downloading the binaries for various architectures. Sourcegraph has a [ctags wrapper](https://github.com/sourcegraph/go-ctags) that calls the external ctags binary.
Or swap out `ctags` for [gotags](https://github.com/jstemmer/gotags) (license is permissive, but not Apache 2.0) and have a pure-go implementation that does not require running a separate binary.

* [ ] make executor access dynamic
The executors (precise code intelligence and batch changes) are separate services that are accessed via HTTP. Currently the URL and password are hard-coded; need something like a Preferences pane to define how to access them.
Probably need other config options exposed also.

* [ ] examine other service endpoints to see if they need to be folded in
Some examples:
  ```
  setDefaultEnv("SYMBOLS_URL", "http://127.0.0.1:3184")
  setDefaultEnv("SEARCHER_URL", "http://127.0.0.1:3181")
  setDefaultEnv("REPO_UPDATER_URL", "http://127.0.0.1:3182")
  ```

* [ ] resolve TODO comments in the code
  * [ ] TODO(sqs)
  * [ ] TODO(security)
  * [ ] TODO!(sqs)

* [ ] missing features
  * [ ] syntax highlighting
  * [ ] indexed search?
  * [ ] not sure which features are missing

* [ ] Usage of tools such as `p4-fusion` and `coursier` require them to be already installed and on the path.
Maybe embed the binaries in the executable to be extracted when needed, or in an installer 

* [ ]  make the LAF more of a desktop app
maybe an Electron app?

* [ ] create an installer
to set up other tools, like `ctags`, `p4-fusion`, etc... and maybe collect info about executors and databases?

**Comment by slimsag** [comment]
Closing in favor of project board: https://github.com/orgs/sourcegraph/projects/306/views/1

**Comment by theoparis** [comment]
Why was this closed? The cody app is not a solution and does not run on a headless server..
> ./usr/bin/cody: error while loading shared libraries: libEGL.so.1: cannot open shared object file: No such file or directory

**Comment by peterguy** [comment]
@theoparis this issue was closed in favor of tracking the effort of creating a locally-deployable binary via a project board.  If you want to run Sourcegraph headless, try out the [various deployment options](https://docs.sourcegraph.com/admin/deploy) for Sourcegraph on a server.
