### ISSUE TITLE
[DB Backed Perms Syncing] Milestone 1 Merge behind feature flag

### ISSUE THREAD

**Issue by pjlast** [sourcegraph/sourcegraph#45617]
Ongoing PR here: https://github.com/sourcegraph/sourcegraph/pull/44796
/cc @sourcegraph/iam

Goal: put work in #44796 behind feature flag, merge it, then iterate

Part of https://github.com/sourcegraph/sourcegraph/issues/46078

**Comment by mrnugget** [comment]
Going to flesh this ticket out

**Comment by mrnugget** [comment]
Note from planning: moved the majority of content over to https://github.com/sourcegraph/sourcegraph/issues/46078. This ticket is now about merging the prototype behind a feature flag.
