### ISSUE TITLE
Implement updates to free-licensing tier (final step of 4.0 P&P updates)

### ISSUE THREAD

**Issue by ryphil** [sourcegraph/sourcegraph#45640]
This is the ticket to track implementation of the discovery work done in #44657.

Timeline: To be released in February release cut.

**Comment by mrnugget** [comment]
Note from grooming session: we agree with the plan proposed in here https://github.com/sourcegraph/sourcegraph/issues/44657#issuecomment-1346287330 and all agree that we should test this together and all review this.

**Comment by mrnugget** [comment]
Updated estimated for new sprint
