### ISSUE TITLE
"Show more" link not appearing at the bottom of search results pages

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#4564]
- **Sourcegraph version:** 3.3.8 and 3.5.0-rc.1

Reported by:
* https://app.hubspot.com/contacts/2762526/company/407948923

#### Steps to reproduce:

cc @slimsag 

(I can repro with the following, but I'm not entirely sure if this is the same set of steps that the customer above ran into!)

1. Go to https://sourcegraph.sgdev.org/search?q=repo:sourcegraph+f:package
2. Click on "Show more" at the bottom
3. Scroll down so a new "page" of results appears (using our infinite scroll)
3. Then:
  - Go back, or;
  - Re-run the same search without a `count:` term, or;
  - Run a new search that should trigger a "show more" link

**My hypothesis: something gets set when you use the infinite scroll that persists across searches and prevents future "Show more"s from appearing (?).** 

![image](https://user-images.githubusercontent.com/5589410/59643478-ae8bfe00-911d-11e9-8539-1dc59ff561d0.png)

(I realize that this is a terrible screenshot — this search DID show a "show more" link at the top, but not at the bottom)

#### Expected behavior:

"Show more" link appears at the bottom of the page

#### Actual behavior:

"Show more" link does not appear at the bottom of the page

**Comment by slimsag** [comment]
Confirmed this is fixed on k8s.sgdev.org.
