### ISSUE TITLE
insights: replace `frames` legacy wording

### ISSUE THREAD

**Issue by leonore** [sourcegraph/sourcegraph#45656]
just follow-up on https://github.com/sourcegraph/sourcegraph/pull/45644 to make our code more understandable

/cc @joelkw @felixfbecker @vovakulikov

**Comment by subhash686** [comment]
Hi,
Is the intention to rename `frame` to `sample_times`/`sampleTimes`/`times` starting with `enterprise/internal/insights/timeseries/frames.go` and `enterprise/internal/insights/timeseries/frames_test.go` and the references, comments etc. ?

**Comment by leonore** [comment]
hi @subhash686, that's the idea, this is just a renaming ticket. another thing to consider would be to rename `timeseries/series.go` to `timeseries/time_interval.go` and `timeseries/frames.go` to `timeseries/timeseries.go`. should all be cosmetic change!

**Comment by subhash686** [comment]
Sounds good. I can take this ticket. I am new to Go and this is a good starting point for me.

**Comment by leonore** [comment]
@subhash686 sure! you can tag me or @/sourcegraph/code-insights-backend as reviewers if you do it!
