### ISSUE TITLE
okta saml: Could not setup for k8s.sgdev.org

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#4570]
Tried to test okta saml for k8s.sgdev.org. Created a new SAML application for k8s.sgdev.org with the everyone user group. Added it to the identity providers. Tried to login with our alice login. Failed with

```
Error validating SAML assertions. Try signing in again. If the problem persists, a site admin must check the configuration.
```

I'm not sure how to debug further. @beyang can you help further? I have commented out the saml config from the management console just to ensure k8s still works.

**Comment by keegancsmith** [comment]
I know core-services owns this now, just want some potential pointers to help save time so we can unblock a potential release blocker.

**Comment by beyang** [comment]
@keegancsmith I followed the steps and was able to configure auth. I left the SAML app on our Okta instance (it's called `k8s.sgdev.org (SAML) BL`) and the config in the management console. Can you take a look and let me know what you did differently? There may be some doc updates we should mamke here if it wasn't clear.

Closing this now for now, so as not to block release.

**Comment by keegancsmith** [comment]
Weird, I didn't delete my saml implementation. But yeah it seems to be gone. I tested the one you added and it works. So I regard this as working now
