### ISSUE TITLE
RFE: Display warning/error in the admin UI when gitserver or zoekt are cleaning up disk space to stay within threshold

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#45708]
**Requested by:** https://github.com/sourcegraph/accounts/issues/6716, https://github.com/sourcegraph/accounts/issues/486

#### Feature request description

When the disk space is low enough on gitserver or zoekt to require either to clean up disk space, display a warning or error to the admin.

Also, ideally, in the admin UI, display information about how much disk space is available about each gitserver and zoekt mounts.  

#### Is your feature request related to a problem? If so, please describe.

The users were seeing frequent errors that a repository was not cloned or was cloning.  It was not clear to the admin why the repositories were not cloned already.  It required us to look in the gitserver logs and see this error:

```
{"SeverityText":"WARN","Timestamp":1670707277975358792,"InstrumentationScope":"server.cleanup.freeUpSpace","Caller":"server/cleanup.go:750","Function":"github.com/sourcegraph/sourcegraph/cmd/gitserver/server.(*Server).freeUpSpace","Body":"removed least recently used repo","Resource":{"service.name":"gitserver","service.version":"4.2.0","service.instance.id":"gitserver-0"},"Attributes":{"repo":"/data/repos/foo/.git","how old":238.020677824,"free space in GiB":27.03281021118164,"actual percent of disk space free":10.818406509526136,"desired percent of disk space free":10,"space freed in GiB":3.1883410597220063,"how much space to free in GiB":1.0485763549804688}}
```

This costs extra time in troubleshooting and results in poor experience for users during this time. 

#### Describe alternatives you've considered.

Train administrators to know where to look and what to check. 

/cc @jplahn @ryphil

**Comment by mrnugget** [comment]
This one sounds easier than one might think at first. It’s not trivial. Question: doesn’t grafana alert them to disk space running low?

**Comment by mike-r-mclaughlin** [comment]
For some reason, in https://github.com/sourcegraph/accounts/issues/486 case, Grafana is not working at all (looking into this now).  In other cases, admins got the alert and forgot about it :(.  This feature should at least make it easy to quickly troubleshoot the issue when it comes up again.

**Comment by eseliger** [comment]
The gitserver cleanup job no longer exists for customer deployments, it wasn't working as intended. 
Instead, customers will now be notified from the UI that a gitserver is low on disk, can inspect disk usage any time under **Site-admin > Gitservers**, and additionally we expose Grafana metrics on disk usage which can be alerted on.

I think this resolves it, let me know if not :)
