### ISSUE TITLE
[Discovery] Add Permissions Syncing for Gerrit

### ISSUE THREAD

**Issue by ryphil** [sourcegraph/sourcegraph#45713]
Description TBD - Can be a broad holiday ticket to explore what has been done and what is still in flight. 

/cc @sourcegraph/source/iam

**Comment by varsanojidan** [comment]
I did a spike on this a while back, the doc might be useful to whoever picks this up: https://docs.google.com/document/d/1tZ7L-bJOzjuzYWHmOfeg08LPVNhS_Z1p11KbRV56kWA/edit?usp=sharing

This wasn't peer validated so don't take it as gospel, it's worth validating anything written here.
