### ISSUE TITLE
auth.orgUserMap does not work on k8s.sgdev.org

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#4571]
#### Steps to reproduce:

1. Create an org on k8s.sgdev.org, for instance `sourcegraph`
2. Through the management console, add the following to critical config:

```json
"auth.userOrgMap": {
    "*": [
      "sourcegraph"
    ]
  }
```

#### Expected behavior:

- New & current users are automatically added to the org.

#### Actual behavior:

- New & current users are not added to the org.

Note: I did not have this issue on a new docker instance running `sourcegraph/server:3.5.0-rc.1`.

**Comment by lguychard** [comment]
@beyang @slimsag not sure who to assign on this, can you help triage? Thanks!

**Comment by beyang** [comment]
I tested this now, and it worked (but I had to wait approximately 1-2 minutes). I'll update the docs to mention the wait time, but can you reproduce after waiting awhile?

Going to close this, so as to not block release, but let me know if you can reproduce after waiting a bit.
