### ISSUE TITLE
RFE: Provide a way to get from a failing repository (on repository status page) to the code host configuration

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#45722]
**Requested by:** https://github.com/sourcegraph/accounts/issues/486, https://github.com/sourcegraph/accounts/issues/6716

#### Feature request description

On the Site Admin > Repositories > Repositories (status) page, add a link to the parent code host configuration.  

#### Is your feature request related to a problem? If so, please describe.

When troubleshooting a failing repository, it's often very difficult to figure out which code host the repository is defined in (especially when there are 10-20 or more code hosts).

In some cases, particularly for "generic git" code hosts, it's impossible to find the failing repository in a code host.

/cc @jplahn @ryphil

**Comment by sashaostrikov** [comment]
Actually, this is indeed closed by https://github.com/sourcegraph/sourcegraph/pull/55392
