### ISSUE TITLE
Update the "last sync" icon in the search results UI when the repository is having problems syncing or is delayed

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#45728]
**Provided by:** https://github.com/sourcegraph/accounts/issues/6716 [Recording: https://drive.google.com/file/d/14ZdQ3U9pKCsbkonyk0KkqWsHUH2g_D-R/view] (See: [this Slack thread](https://sourcegraph.slack.com/archives/C01P4R0RZH9/p1672774997485099) also)
#### Feedback

When the user is searching for code, there is no visual indicator to the user that the repository syncing is delayed (and the result provided might not be the latest).  They do see an indicator and when hovering over it the tooltip tells the user the last sync time.  Example:

![image](https://user-images.githubusercontent.com/23640224/207931881-7213ffe1-02bc-462c-8849-38eaf595560a.png)

if there is a problem with syncing or it's delayed and the search result might be out of date, it would be nice for the user to be able to see that visually.

/cc @ryphil/search-core

**Comment by varsanojidan** [comment]
@mrnugget should be, unless there’s more things the customer wanted.
