### ISSUE TITLE
Language filters should use more than extension (including hints from file) when determining language of a file

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#45736]
**Provided by:** https://github.com/sourcegraph/accounts/issues/6716 [Recording: https://drive.google.com/file/d/14ZdQ3U9pKCsbkonyk0KkqWsHUH2g_D-R/view]

#### Feedback

A user ran a query that resulted in 109 results.  All were YAML files.  However in the filters section, the "languages" showed "MiniYAML      108".  There was nothing indicating what the other 1 result was (until we filtered out MiniYAML to see what it thought it was).    User asked: What is the difference between MiniYAML and YAML?

![image](https://user-images.githubusercontent.com/23640224/207671991-a97077a2-83a7-47fb-9559-4bb6af7c4754.png)

Feedback:
- Make it easier to figure out how Sourcegraph is determining what language a file is?(Q: Can Sourcegraph parse a hint at the top of the file?)
- Could Sourcegraph use something similar to what [GItHub uses (linguist)](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-repository-languages) for language detection?

/cc @sourcegraph/search-core

**Comment by jtibshirani** [comment]
We've made a lot of improvements here recently, including better handling for ambiguous extensions like `.yaml`.

We're also working to make language filters more precise by looking at the contents of a file, not just the filename: https://github.com/sourcegraph/sourcegraph/issues/60341. To keep things simple, I'm going to close out this issue in favor of that tracking issue.
