### ISSUE TITLE
insights: truncate series greater than N samples

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#45745]
There are a few goals we need to accomplish with data retention:
1. Bound the growth of each insight series to some upper bound
2. Support tunable insight sizes for customers that make potentially very large insights

For v1 of data retention we are looking to launch a simple truncate mechanism.

To "truncate" means that we will remove older points from the series. 

Instead of immediately deleting the points, truncated points will be moved into a separate table where they are not resolvable in the insight visualization. Points should be deleted from the truncation table after 2 years. This value should be tunable through site config.
 
Ideally the truncation should be scalable and not require a singleton node, but if that enables us to move significantly quicker then we can rely on a singleton node.

The value of N should be configurable through a site config setting. This value will represent the maximum sample size that is allowed for users. By default, we will load a much smaller set of points, for example 30.

/cc @joelkw @felixfbecker @vovakulikov

**Comment by leonore** [comment]
@coury-clark can you clarify what you mean by:

> Ideally the truncation should be scalable and not require a singleton node, but if that enables us to move significantly quicker then we can rely on a singleton node.

are you talking about what would be the truncation worker?
