### ISSUE TITLE
insights: allow user controlled sample count

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#45750]
Allow users to control how many samples should display on the insight. This value should be 1 <= X <= MAX, where max is the site config defined [here](https://github.com/sourcegraph/sourcegraph/issues/45745).

We should always render the most recent snapshot if available, in addition to the selected N points. (cc @Joelkw for opinion on this. It will probably look like an off by 1 error in the UI. Maybe we just include snapshots in N?)

Example [branch](https://github.com/sourcegraph/sourcegraph/pull/45748)

<img width="937" alt="image" src="https://user-images.githubusercontent.com/5090588/207981399-5d520b9d-b1b5-4af2-9751-719a4b4e265e.png">

/cc @joelkw @felixfbecker @vovakulikov

**Comment by felixfbecker** [comment]
Shouldn't this be a persisted setting at creation time? Or what's the thought/user value behind adding this as a view-time setting?

**Comment by leonore** [comment]
> Shouldn't this be a persisted setting at creation time? Or what's the thought/user value behind adding this as a view-time setting?

@felixfbecker I think allowing a user-controlled sample at view time adds more flexibility and has more added value for users:
* it allows a user to reduce the number of samples immediately visible for insights with a lot of data (less legible), without having to delete them
* it gives the user control if they want to show a specific trend on their insight
* it gives the user granular control on insights. even if they want to retain a larger value of samples by default on all their insights, for some they might want less samples
