### ISSUE TITLE
insights: performance testing for highly restrictive instance

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#45771]
Given a highly restrictive where a significant (>90%) of the permissions are not visible to users, validate that insights can load in acceptable times.

/cc @joelkw @felixfbecker @vovakulikov

**Comment by chwarwick** [comment]
Found that with an insight run over 300k repos with a user that only had access to 100k repos, the insight was able to load in under 2 seconds, typically just under 1.5 seconds.  The admin user with access to all repos was loading the insight between 1.25 and 1.5 seconds. 

The Insight had data from over 275k repos to ensure that there was substantial number of rows that were being aggregated.  

At this time I did not perform extended load testing as I was primarily focused on ensuring that the queries were functional in a highly restrictive environment, not in stressing the load.
