### ISSUE TITLE
type:symbol search counts incorrect

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#4578]
- **Sourcegraph version:** 3.5.0-rc.1 and sourcegraph.com

#### Steps to reproduce:

1. Visit https://sourcegraph.com/search?q=repo:%5Egithub.com/sourcegraph/sourcegraph%24+ListRepos+type:symbol
2. See that it says "15 results"

![image](https://user-images.githubusercontent.com/5589410/59725378-4f43f180-91e2-11e9-8c9f-c9553f0ecb14.png)

There are many more than 15 matching symbol results... There appear to be 15 _files_ that have symbols that match the result in them. 

#### Expected behavior:

It shows the number of symbol results.

#### Actual behavior:

It shows the number of file results (15)

**Comment by ggilmore** [comment]
@dadlerj I can reproduce this, so I am moving this issue out of the 3.5 milestone. 

cc @sourcegraph/code-search
