### ISSUE TITLE
type:symbol search results incomplete

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#4579]
- **Sourcegraph version:** 3.5.0-rc.1 and sourcegraph.com

#### Steps to reproduce:

1. visit https://sourcegraph.com/search?q=repo:%5Egithub.com/sourcegraph/sourcegraph%24+Repos+type:symbol
2. also visit https://sourcegraph.com/search?q=repo:%5Egithub.com/sourcegraph/sourcegraph%24+ListRepos+type:symbol

See that the first search has 13 results, while the second search has 15 results. The first search should be a superset of the second — how can the result set be smaller?

I don't see any indication that there are more results (e.g. no "show more" or "13+").

EDIT: to be clear, the specific bug here is my last point: there just needs to be an indication that there are more results, just like a normal text search, right?

**Comment by ggilmore** [comment]
cc @sourcegraph/code-search

**Comment by ijt** [comment]
Is this labeled as a release blocker because it was introduced in this release?

**Comment by ggilmore** [comment]
@ijt I would verify whether or not this is a new regression.

**Comment by slimsag** [comment]
- Agree this is a high priority bug. Worth adding to 3.6 milestone.
- Very unlikely this is a regression, so moving out of 3.5.
- While similar in appearance to https://github.com/sourcegraph/sourcegraph/issues/4564 it is not the same issue.

**Comment by ijt** [comment]
TODO: check whether this issue is also present in 3.4.0.

**Comment by ijt** [comment]
I verified that this bug is also present in 3.4.0 (8c2e4a7d94f94d2511b59f824b867a32d587bf1d).

**Comment by ijt** [comment]
This issue may disappear as a result of the work @kzh is about to do moving our symbol search to Zoekt.

**Comment by ijt** [comment]
Reasonable results appear after adding `count:100` to both queries:

| query | # results | 
| -- | -- |
| `repo:^github.com/sourcegraph/sourcegraph$ Repos type:symbol count:100` | 37 |
| `repo:^github.com/sourcegraph/sourcegraph$ ListRepos type:symbol count:100` | 22 |
