### ISSUE TITLE
conf.DeployType is currently broken for datacenter 

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#458]
Part of https://github.com/sourcegraph/sourcegraph/commit/f602b88c9833908c6c5866e73c63e03c6266f125 changed the `conf.DeployType()` string that represented the data center deployment to `"k8s"` instead of `"datacenter"`: https://github.com/sourcegraph/sourcegraph/commit/f602b88c9833908c6c5866e73c63e03c6266f125#diff-9579b8ef47575e9f45f0540383334f90R158. 

The issue is that datacenter deployments [currently specify the environment variable as](https://github.com/sourcegraph/deploy-sourcegraph/blob/master/base/frontend/sourcegraph-frontend.Deployment.yaml) `DEPLOY_TYPE=datacenter` (this was true even when we were using helm: https://github.com/sourcegraph/deploy-sourcegraph/blob/helm-legacy/examples/gcp/generated/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml#L32).

This means that all paths that rely on [IsDeployTypeKubernetesCluster(deployType string)](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@69a07c8e1fb849e7b60f4f96000b291e6d833b7a/-/blob/pkg/conf/computed.go#L157:6&tab=references) are broken. Luckilly, this currenly only affects update checks and langserver management (which doesn't work on data center yet). 

We should 1) revert part of f602b88c9833908c6c5866e73c63e03c6266f125 so that the  `conf.DeployType()` string is back to `"datacenter"` instead of `"k8s"` 2) remove all references to the `DEPLOY_TYPE` environment variable from https://github.com/sourcegraph/deploy-sourcegraph so that the images just use the default value.

**Comment by ggilmore** [comment]
cc @slimsag

**Comment by slimsag** [comment]
> revert part of f602b88 so that the conf.DeployType() string is back to "datacenter" instead of "k8s" 2)

I don't think we should do this. I think we should just do your second item:

> 2) remove all references to the DEPLOY_TYPE` environment variable from github.com/sourcegraph/deploy-sourcegraph so that the images just use the default value.

**Comment by slimsag** [comment]
(Customers will just upgrade to whatever base configuration we have. No customer should be actively setting `DEPLOY_TYPE` on their own)

**Comment by nicksnyder** [comment]
Fixed in 2.12.1
