### ISSUE TITLE
Saved search page warns me that I can't create an alert, but doesn't stop me from it

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#4580]
- **Sourcegraph version:** 3.5.0-rc.1

If this is intentional, feel free to close!

#### Steps to reproduce:

1. Go to the saved searches page
2. Click to create a new saved search
3. Write any name/query (as long as the query is NOT a type:diff or type:commit
4. See the warning
5. Save it anyway

#### Expected behavior:

It should stop me from saving it

#### Actual behavior:

It does not stop me from saving it

**Comment by slimsag** [comment]
It lets you do it on the assumption that it might work in the future (which is bad), and then does nothing with it at all: https://github.com/sourcegraph/sourcegraph/blob/main/cmd/query-runner/main.go#L146-L150

i.e. it's there in the DB, but we don't do anything with it and you'll never get a notification for it.

**Comment by lguychard** [comment]
Saved searches can now save any type of search, as they no longer support notifications.
