### ISSUE TITLE
sourcegraph/sourcegraph "Branches" is incredibly slow locally (30s+)

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#4581]
- **Sourcegraph version:** 3.5.0-rc.1

#### Steps to reproduce:

1. Set up server, add GitHub external service with sourcegraph/sourcegraph
2. Open the browser console
3. Visit the repo and click on the "Branches" button
4. See it take a very long time to load (I've so far gotten 31.28s, 47.32s, and 35.04s) 

I can't repro it on sgdev (http://localhost:7080/github.com/sourcegraph/sourcegraph/-/branches only takes 2-3s) and my local instance has a lot of other repos... Can anyone else repro? Or any reason why this would be so bad for me locally? I don't see any terminal or console errors.

![image](https://user-images.githubusercontent.com/5589410/59726882-3d654d00-91e8-11e9-8a34-e6ed09033417.png)

**Comment by dadlerj** [comment]
And I can't repro this on any other repos. We have 18 pages worth of branches: https://github.com/sourcegraph/sourcegraph/branches/all?page=18

**Comment by dadlerj** [comment]
Another repo with a lot of branches (`microsoft/vscode`, which has 300, versus `sourcegraph/sourcegraph`'s 357) is also VERY slow for me locally. `graphql?RepositoryGitBranchesOverview` took 51.99s
![image](https://user-images.githubusercontent.com/5589410/59727228-ae593480-91e9-11e9-85c7-424a848d4e6d.png)

**Comment by jjlin** [comment]
I'm running into this problem, or presumably something very similar.

I'm indexing repos with lots of branches, as many as 18K in some cases (no, I don't think this is a good idea, but it's not something I control). Anyway, it looks like what's happening is Sourcegraph [gets a list of branches, plus some additional commit info](https://github.com/sourcegraph/sourcegraph/blob/ee9d1e4/cmd/frontend/graphqlbackend/repository_git_refs.go#L53-L59) so it can sort branches by most recently updated. This involves running this command for each branch:
```
git log --format=format:%H%x00%x00%aN%x00%aE%x00%at%x00%cN%x00%cE%x00%ct%x00%B%x00%P%x00 -n 1 <commit>
```
`time` indicates it takes around 200 ms per call on my system, so about a minute for 300 branches, which is obviously too slow for an interactive feature.

Most users in my org just want to filter on branch names graphically, so this extra sorting work is wasted. Sorting alphabetically would be just fine for us (maybe there could be a config setting to enable this), but if you want to keep the current approach as the default, you might want to precompute that info during indexing or something.

**Comment by dadlerj** [comment]
Thanks for finding that @jjlin! Tagging @sourcegraph/core-services since this issue appears to be coming from the backend.

**Comment by tsenart** [comment]
@keegancsmith: Any clue? Seems related to git-server slowness.

**Comment by keegancsmith** [comment]
200ms does seem slow. @jjlin this may help as a temporary workaround: Delete the repository off gitserver and let it reclone it.

But yeah, doing that log command per commit seems sub-optimal. There should be a way to batch it to git. I think sorting by commit timestamp is useful though, so I think we should investigate performance before removing that feature.

**Comment by jjlin** [comment]
@keegancsmith I deleted the repo from /var/opt/sourcegraph and let Sourcegraph reclone it. It seems to be maybe 10 ms faster on the fresh clone, so not really a meaningful improvement.

I agree the current sort can be useful, but it's effectively broken on repos with any significant number of branches (the 18K branch repo in particular will never even display the branches; it always bails out with `Error: Unexpected HTTP error: 504 Gateway Time-out`). So if it's going to take a while to implement precomputation/caching for that data, it would be helpful to have an option to disable the fancy sort entirely. Or maybe it could be auto-disabled by default on repos with more than X number of branches.

**Comment by keegancsmith** [comment]
Thanks for the context, it does sound like we can do some minimal work around this to just do something dumb if the number of branches is above a certain threshold.

**Comment by keegancsmith** [comment]
The fix in master will now fallback to no sorting if it takes more than 5s, or if there are more than 1000 refs. Additionally fixed a bug where we would always fetch the commit for all branches and then filter by query. Now we filter by query first.

This will be part of 3.9.
