### ISSUE TITLE
dogfood: investigate mystery egress charges

### ISSUE THREAD

**Issue by kalanchan** [sourcegraph/sourcegraph#45828]
There are some really big egress charges on dogfood, costing over 4k a month with no reason to why. This is not seen in other environments, we need to figure out whats causing these mystery charges

https://sourcegraph.slack.com/archives/C01N83PS4TU/p1671133722600919
![Image](https://user-images.githubusercontent.com/51868853/208520589-0b24cb87-699d-4a74-9bf0-b184027fe454.png)

**Comment by jhchabran** [comment]
update: half completed, @kalanchan needs to finish this.

**Comment by jhchabran** [comment]
@sourcegraph/team-dev-infra can someone take a look if this is still a thing or not?

**Comment by davejrt** [comment]
Charges for July were $40 USD. Closing this as a one off incident.
