### ISSUE TITLE
batches: `batch_spec_resolution_jobs` prevents users from being hard deleted

### ISSUE THREAD

**Issue by LawnGnome** [sourcegraph/sourcegraph#45832]
From https://github.com/sourcegraph/customer/issues/1737: hard deleting a user currently fails on a violation of the `batch_spec_resolution_jobs_initiator_id_fkey` foreign key. It appears (from a literal 10 second glance at the current schema) that we cascade updates from the `users` table onto `batch_spec_resolution_jobs.initiator_id`, but not deletes.

My guess is that addressing this will be slightly more complicated than just `ON DELETE CASCADE`, since we may have jobs actively running — presumably we'll want to make the column nullable, `ON DELETE SET NULL`, and handle that in code. Bonus points if we can proactively cancel the job.

Whoever picks this up should probably do a quick sweep of our other foreign keys back to `users` to ensure we don't have similar issues elsewhere.

**Comment by courier-new** [comment]
Even though this isn't trivial, it still doesn't sound too bad, maybe like 1d or so? That being said, I don't know where this falls in terms of priority.

**Comment by eseliger** [comment]
If this is just about cancellation, this is taken care of by worker. It notices a record was deleted and stops working on it. So if that's the only concern that might be as simple as updating the ON DELETE hook.

**Comment by michaellzc** [comment]
> Even though this isn't trivial, it still doesn't sound too bad, maybe like 1d or so? That being said, I don't know where this falls in terms of priority.

This currently breaks the hard user deletion feature for all customers, so it's fairly important? I can imagine on-prem customers may use it to offboard users. Additionally, it broke a critical Cloud feature when an user happen to have a batch change created

**Comment by BolajiOlajide** [comment]
> > Even though this isn't trivial, it still doesn't sound too bad, maybe like 1d or so? That being said, I don't know where this falls in terms of priority.
> 
> This currently breaks the hard user deletion feature for all customers, so it's fairly important? I can imagine on-prem customers may use it to offboard users. Additionally, it broke a critical Cloud feature when an user happen to have a batch change created

I'll prioritize this. Thanks for the note @michaellzc

**Comment by BolajiOlajide** [comment]
@michaellzc This is now resolved [here](https://github.com/sourcegraph/sourcegraph/pull/46549). Thanks

**Comment by unknwon** [comment]
@BolajiOlajide thank you!
