### ISSUE TITLE
TreeView: clear the way for more editor-like UI

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#45837]
The goal of this issue is to track progress on rewriting several of our UI components to use a tree view.

### Short-term vision: `TreeView`
- [ ] Implement a new `TreeView` component that accepts a similar API as `vscode.TreeDataProvider<string>`. It's important that the API to list children is based on promises/observables instead of React hooks. The `TreeView` component should support arrow keyboard shortcuts to expand/collapse tree items and the component should be accessible by using `aria-expanded` attributes.
- [ ] Use `TreeView` to replace the Files and Symbols sidebars. The current Files/Symbols sidebar have a lot of technical debt and it's better to rewrite them than try to repair them. The Files sidebar should auto-merge nested directory that have only a single sub-directory (no file) similar to how the Sourcegraph VS Code extension does it. See [`FilesTreeDataProvider`](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@40eedcac19c50768da06f561e1baf3b58c01c2ed/-/blob/client/vscode/src/file-system/FilesTreeDataProvider.ts?L8) in our monorepo for an example.
    <img width="411" alt="CleanShot 2022-12-20 at 09 18 20@2x" src="https://user-images.githubusercontent.com/1408093/208617507-f9a0a56b-8549-44e0-b0e2-d35aa9180388.png">

- [ ] Implement a tabs UI for open blob views so that it's easy to go back to files that you've opened recently (similar to how editor tabs work in VS Code). The `CodeMirrorBlob` component already has a list of `EditorView` instances for the open files. We should keep the list of open files in session or local storage so that the tabs UI doesn't disappear when you reload the page.
- [ ] Replace the v2 ref panel (the 'new' one) with a v3 implementation using `TreeView` and move it into the sidebar next to Files/Sidebar (similar to "Find references" in VS Code). Clicking on a reference should update the main blob similar to how it works in VS Code, not the preview pane like it currently does. The URL should sync with the main blob view, not the ref panel. It should still be possible to link to the ref panel, but the ref panel doesn't have to be reflected in the URL (it's optional). See longer-term vision below about "Copy link".
- [ ] Move the Cmd+F search component into the sidebar next to files/symbols/references and display previews of the search hits in a `TreeView` (similar to VS Code). 
- [ ] Implement "Peek definition" UI with `TreeView` and display inside the blob view between lines using CodeMirror `widget` API. We should fallback to this when "Go to definition" has more than one result, which happens very frequently for search-based intel. Currently, we open the ref panel, which is confusing UX, and it's also slow because we fetch the definitions a second time with the v2 ref panel ('new' one) because it has its own React hooks-based solution to fetch  codeintel data.

### Longer-term vision: split views and link sharing
- [ ] Support vertical/horizontal split views. 
- [ ] Add a "Copy link" command to share a link to the exact same list of open files and a split layout. The generated URL would have a short hash that is the key for a KV store in the backend where the value is a JSON encoding of which files are open and the split view layout.
- [ ] Extend "Copy link" to support adding a comments to code locations. We can implement this by using the CodeMirror tooltip API.

**Comment by vovakulikov** [comment]
@olafurpg I like ideas here about reference panels and tree view. A few questions from my side. 

>It's important that the API to list children is based on promises/observables instead of React hooks.

- Why do we need to rely on promises/observables only? 


> Replace the v2 ref panel (the 'new' one) with a v3 implementation using TreeView and move it into the sidebar next to Files/Sidebar

- Why do you think VScode UI better rather than JB products UI? I've found this extremely useful to see all symbol information near the symbol itself in the popover UI. For example, If we are at the reference and click the symbol this means that we either 

    - want to go to the definition of this symbol and I think now we have a good UI/UX for it with keyboard based ref navigation (or I think cmd + click will work here as well) or
    - want to find other references (usage) of this symbol and in this case I think the following UI fits better (just my personal opinion, I'd be glad to discuss VScode approach here) 
   
<img width="1065" alt="Screenshot 2022-12-26 at 21 42 07" src="https://user-images.githubusercontent.com/18492575/209590973-e48176a9-3cd1-4c90-8167-1aa5f7c3b8f9.png">

**Comment by olafurpg** [comment]
> Why do we need to rely on promises/observables only?

This was only referring to the parts that are defined by `vscode.TreeDataProvider`, we can use hooks for other things. Hook-based APIs are difficult to reuse and it would be great if we can plug in our symbol/file/references UI components in non-React UIs like our editor integrations (where we already have a file tree view) or in an experimental Svelte rewrite. 

> Why do you think VScode UI better rather than JB products UI? 

We should do both. The last bullet point about "Peek definition" goes a long way to mirror the JetBrains UI and we can use this for "Find references" in addition to "Goto def". I'd be OK with defaulting to the peek UI when we have a small number of references (maybe <10) but once the list grows (and includes multiple files) then I personally prefer having the references in the sidebar because it makes it easy to cycle through the result list without loosing context.

**Comment by olafurpg** [comment]
Closing this issue since this was an exploration of how to incorporate tree views into more parts of our UI. The ideas in this issue are not part of any roadmap.
