### ISSUE TITLE
No search/ repos viewable as non-SiteAdmin user on k8s.sgdev.org

### ISSUE THREAD

**Issue by vanesa** [sourcegraph/sourcegraph#4583]
- **Sourcegraph version:** 3.5 
- **Platform information:** k8s.sgdev.org

#### Steps to reproduce:

1. On `k8s.sgdev.org`, login with an account that isn't a SiteAdmin via OpenID Connect
2. Try to do any search
3. Try to open a repo or file by typing in the path directly into the address bar e.g. ```k8s.sgdev.org/github.com/sourcegraph/sourcegraph```

#### Expected behavior:
a) See the results of your search when searching.
b) See the repo as typed on the address bar.

#### Actual behavior:
a) See the notification to add repos, which as a non-SiteAdmin is not possible.
![image](https://user-images.githubusercontent.com/9110008/59729177-1e6bb880-91f2-11e9-9f44-4669bf3f4ece.png)

b) Get redirected to ```sourcegraph.com``` instead of being able to view the repo/file on ```k8s.sgdev.org```
https://cl.ly/a5cb8c59c2bb

**Comment by ggilmore** [comment]
@vanesa I tried reproducing this by creating a non-admin user via the built in auth. I was able to search and access sourcegraph/sourcegraph normally. I believe the issues that you ran into were a result of https://sourcegraph.slack.com/archives/C08JA8Q1H/p1560940894011100

Please re-open this issue if you see this again.
