### ISSUE TITLE
Hover tooltips on sourcegraph.com broken and page jitter 

### ISSUE THREAD

**Issue by vanesa** [sourcegraph/sourcegraph#4585]
- **Sourcegraph version:** Sourcegraph.com

#### Steps to reproduce:

1. Go to any code view on Sourcegraph.com e.g. https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/web/src/repo/RepoHeader.tsx
2. Hover over the nav links on the right. Notice that no hover tooltips appear even though the DOM shows the rendering of the tooltip `div`.
3. Also notice the additional and redundant scrollbar that appears when hovering over the links, making the page jitter.

#### Expected behavior:
- No additional scrollbar and visible tooltips

#### Actual behavior:
- No tooltips, page shakes due to additional scrollbar
![Missing tooltips and page jitter](https://d2ddoduugvun08.cloudfront.net/items/451X3v2x1i2F0A3k1J0O/Screen%20Recording%202019-06-18%20at%2007.05%20PM.gif)

**Comment by sqs** [comment]
I think this was caused by #4545. Looking into it.
