### ISSUE TITLE
Batch Changes webhook check fails to discover Bitbucket Cloud webhooks (and maybe others)

### ISSUE THREAD

**Issue by LawnGnome** [sourcegraph/sourcegraph#45919]
Originally from https://sourcegraph.slack.com/archives/C022SPMNR0W/p1671147100385499 for https://github.com/sourcegraph/accounts/issues/8267:

In #45222, the query to detect whether webhooks have been enabled on a code host was updated to account for the new world `webhooks` table. Excellent!

Unfortunately, this appears to be broken for Bitbucket Cloud (and, I suspect, other code host kinds) due to the URNs in the `webhooks` table not matching the external service ID in the `repo` table.

Here's what I did:

1. I have a Bitbucket Cloud external service, configured thusly:
    ```json
    "BITBUCKETCLOUD": [
      {
        "url": "https://bitbucket.org",
        "appPassword": "<token>",
        "username": "<username>",
        "teams": [
          "<username>"
        ]
      }
    ]
    ```
1. I created a webhook through the new site admin UI for this external service.
1. On Bitbucket itself, I created a workspace webhook. (I don't actually think the type matters here.)
1. I created a batch change that publishes one or more changesets to Bitbucket Cloud, and observed that the webhook warning banner is still present.

The key here is that the `repo` record looks like this:

```
-[ RECORD 1 ]-------------------------
id                    | 22
name                  | bitbucket.org/aharvey-sg/src-cli
description           |
fork                  | True
created_at            | 2022-07-26 10:41:54.788513-07
updated_at            | <null>
external_id           | {6694292b-ed6e-4183-903a-d9bfc44113bd}
external_service_type | bitbucketCloud
external_service_id   | https://bitbucket.org/
archived              | False
uri                   | bitbucket.org/aharvey-sg/src-cli
deleted_at            | <null>
metadata              | {"scm": "git", "name": "src-cli", "slug": "src-cli", "uuid": "{6694292b-ed6e-4183-903a-d9bfc44113bd}", "links": {"html": {"href": "https://bitbucket.org/ah>
private               | True
stars                 | 0
blocked               | <null>
```

While the `webhooks` record looks like this:

```
-[ RECORD 2 ]-------------------------
id                 | 2
code_host_kind     | BITBUCKETCLOUD
code_host_urn      | https://bitbucket.org
secret             | <null>
created_at         | 2022-12-21 15:26:27.397005-08
updated_at         | 2022-12-21 15:26:27.397005-08
encryption_key_id  | <null>
uuid               | b177f999-6f75-462c-8c98-501e069df4f3
created_by_user_id | 1
updated_by_user_id | <null>
name               | workspace
```

Note that the first ID has a trailing slash, and the second URN omits it.

I don't see an obvious way to link the two tables, since `webhooks` has no other references to the external service or repo. Presumably we'll need to do some normalisation somewhere, or adjust the new `WHERE` clause to be fuzzier.

/cc @jplahn @ryphil

**Comment by courier-new** [comment]
I do see this also affects GitHub on S2. As a stopgap, we should disable that banner ASAP, or else it's going to show up and bother every customer who _has_ set up webhooks on every batch change page. 😬

It doesn't sound like the _worst_ idea to make the `WHERE` clause fuzzier, but we should probably sync with repo management before deciding on the appropriate approach here. I've put a really rough estimate on this with that in mind.

I've created a [PR](https://github.com/sourcegraph/sourcegraph/pull/46359) to disable the banner for now, but I don't know what the priority should be on bugs right now.
