### ISSUE TITLE
codenav: Bitbucket Server j2d on local symbol brings user to Sourcegraph code view

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#4592]
- **Sourcegraph version:** insiders

#### Steps to reproduce:

1. Ensure your Sourcegraph extension is configured to use https://k8s.sgdev.org
1. Go to https://bitbucket.sgdev.org/projects/SOUR/repos/vegeta/browse/main.go#88
1. Authenticate with 1 Password credentials
1. Click on `fs` and then "Go to definition"

#### Expected behavior:

Jumps to definition of the symbol in the same file view.

#### Actual behavior:

Jumps to definition of the symbol in Sourcegraph.

**Comment by lguychard** [comment]
Same code host jump-to-def currently only works on GitHub, `CodeHost.urlToFile()` is not implemented for any other code host. Backlogging, although this is not a huge effort and we may want to tackle it soon.

**Comment by tsenart** [comment]
I was about to file an issue for this and realised I had filed this last iteration :-)
