### ISSUE TITLE
codenav: Wrong jump to definition line

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#4593]
**Sourcegraph version:** insiders

#### Steps to reproduce:

1. Ensure your Sourcegraph extension is configured to use https://k8s.sgdev.org
1. Go to https://bitbucket.sgdev.org/projects/SOUR/repos/vegeta/browse/dump.go#8
1. Authenticate with credentials in 1 Password.
1. Click on `command` and then "Go to definition"

#### Expected behavior:

Jumps to line 114: https://k8s.sgdev.org/bitbucket.sgdev.org/SOUR/vegeta@master/-/blob/main.go#L114:6

#### Actual behavior:

Jumps to line 110: https://k8s.sgdev.org/bitbucket.sgdev.org/SOUR/vegeta@master/-/blob/main.go#L110:6

**Comment by tsenart** [comment]
This doesn't happen when going from the Sourcegraph web-app, only via the extension.

**Comment by felixfbecker** [comment]
Does k8s.sgdev.org use `repositoryPathPatterns`? If yes, it is not expected to work until #4470 is merged

**Comment by tsenart** [comment]
Nope.

**Comment by lguychard** [comment]
`command` was at line 110 in 08190d6, which is the *last commit that modified dump.go* (and the commit ID that is scraped/inferred from the code view by `getCommitIDFromLink()`):

![image](https://user-images.githubusercontent.com/1741180/59783344-3dd11700-92c0-11e9-867d-10d45a23b11e.png)

If the goToDefinition URL were https://k8s.sgdev.org/bitbucket.sgdev.org/SOUR/vegeta@08190d655e8329471d5a82c10e677e9baf32d5bb/-/blob/main.go#L110-113, it would be correct. But `toPrettyBlobURL` uses the rev, and on k8s.sgdev.org, `master` is at 0f5577e.
