### ISSUE TITLE
LSIF uploads for C++ not working at all with HEAD

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/sourcegraph#45958]
Versions:
* Sourcegraph: 26d2c29541534c58e8d18ed9cbe4c43ab8e66f18 (Dec 22)
* src-cli: b5564eaa0a237b282b9d0221cadffa4c6ce156ee (Dec 19)
* lsif-clang: 3517f4e2f82ae1033e334546507957d29388b3c0 (Jul 7 -- no changes since then)

Sourcegraph start command:

```
sg start enterprise-codeintel
```

Test repository: https://github.com/varungandhi-src/lsif-clang-test/tree/2f464d9889357979467c7ba4c3be57c125ebf017

Test LSIF upload (don't forget to change the paths inside the JSON before uploading locally):

[dump.lsif.zip](https://github.com/sourcegraph/sourcegraph/files/10295344/dump.lsif.zip)

Recording of it not working:

https://user-images.githubusercontent.com/93103176/209344984-e0a6ea5d-4499-446c-8067-4d533be2bc1c.mov

**Comment by varungandhi-src** [comment]
Code navigation should work fine for local functions and function parameters/local variables at the very least looking at code nav in LLVM. https://sourcegraph.com/github.com/llvm/llvm-project/-/blob/clang/lib/AST/Expr.cpp?L346:69-346:73#tab=references

**Comment by Strum355** [comment]
Do we have snapshot utility for LSIF? Be interesting to confirm that thats working as intended

**Comment by varungandhi-src** [comment]
Pretty sure we don't, but I tested this with Sourcegraph v4.1.3 (Nov 8) and it does work fine.

**Comment by Strum355** [comment]
Im able to get precise for every symbol in that test repo after flipping `experimentalFeatures.enableLegacyExtensions` to true in site-config

**Comment by Strum355** [comment]
Note that both search-based and precise returned once that flag was flipped, neither worked when it was set to false. So I dont believe the issue we were seeing here are affecting Customer N1

**Comment by varungandhi-src** [comment]
Several Chromium indexes are working on Sourcegraph.com; closing this issue, but going to try to repro the customer issue later.

**Comment by varungandhi-src** [comment]
Yep, navigation seems to be working fine now. https://sourcegraph.com/github.com/varungandhi-src/lsif-clang-test@2f464d9889357979467c7ba4c3be57c125ebf017/-/blob/main.cc?L2:16-2:17
