### ISSUE TITLE
search: repohasfile filter yields no results

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#4595]
**Sourcegraph version:** insiders

#### Steps to reproduce:

1. Go to https://k8s.sgdev.org/search?q=repohasfile:attack.go

#### Expected behavior:

The results of https://k8s.sgdev.org/search?q=attack.go that match on filename are included.

#### Actual behavior:

No results.

**Comment by attfarhan** [comment]
This is not a valid search with `repohasfile` at the moment. `repohasfile` doesn't return repo name matches, only text matches and file path name matches. The docs aren't merged yet, you would have known had they been, sorry! Going to close this.
