### ISSUE TITLE
insights: migration to convert all repos insights to a repo search 

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#45964]
The all repos checkbox on the insight creation screens no longer exists.  A migration should be written to populate an "all repos" repo search for any current all repos insights.

/cc @felixfbecker @vovakulikov

**Comment by chwarwick** [comment]
@vovakulikov  If we add this migration I think it means the feature flag that was added to the UI to toggle between entry modes would need to be removed.

**Comment by vovakulikov** [comment]
@chwarwick I think this is a correct assumption. In fact this logic about populating search repo query field with `repo:.*` for all repos insights has been added in this PR already https://github.com/sourcegraph/sourcegraph/pull/45687 (I still think that we need to have a proper migration on the backend though but just FYI)

Also, I want to mention here that there is another migration that should be done if we go with one single query field UI. Convert strict list of repo URLs into `repo:"repo1|repo2..."` query for the search query field.

**Comment by chwarwick** [comment]
Pending UI testing on number of repo fields in use.
