### ISSUE TITLE
Migrate all the remaining yarn commands to pnpm

### ISSUE THREAD

**Issue by gitstart-sourcegraph** [sourcegraph/sourcegraph#45990]
## Problem statement

We are migrating from `yarn` to `pnpm`, the initial setups are done in [this branch](https://github.com/sourcegraph/sourcegraph/tree/vb/pnpm-test-2), we need to migrate all remaining usages of `yarn` to `pnpm`

## Success criteria

- All `yarn` commands are replaced with `pnpm` commands
- All CI pipelines are passed

## Time estimate

- Pull requests with ~450 lines changed should take **16 hours** at maximum. Ping the reviewer in the spec pull request if time-consuming changes are required.
- Split the work into multiple pull requests if the total diff is bigger than 450 lines of code.

**Comment by valerybugakov** [comment]
Closed by https://github.com/sourcegraph/sourcegraph/pull/46143
