### ISSUE TITLE
repohascommitafter times out on instances with large # repos

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#4602]
i.e. feature doesn't work on large instances currently. need to fix before shipping.

https://sourcegraph.slack.com/archives/CHEKCRWKV/p1560802275003100?thread_ts=1560799141.001500&cid=CHEKCRWKV

Pending PR for this: https://github.com/sourcegraph/sourcegraph/pull/4567

**Comment by ijt** [comment]
How many repos?

**Comment by ggilmore** [comment]
k8s.sgdev.org

**Comment by ijt** [comment]
I see, so about 22k repos. I just tried this and it didn't time out:

![Screen Shot 2019-06-19 at 14 28 43](https://user-images.githubusercontent.com/15530/59802786-92639a80-929e-11e9-8d45-e9eb68845f22.png)

@slimsag can you post the query that you saw timing out?

**Comment by ijt** [comment]
This "No results" is incorrect as well. For example, here is a repo on k8s.sgdev.org that was modified in the past two months and contains files matching the `func main` query:

![Screen Shot 2019-06-19 at 14 34 49](https://user-images.githubusercontent.com/15530/59803245-c8554e80-929f-11e9-978a-02a9e432ce68.png)

![Screen Shot 2019-06-19 at 14 34 59](https://user-images.githubusercontent.com/15530/59803207-ad82da00-929f-11e9-9568-d489a759cd88.png)

It looks as though we have some sort of internal timeout that just returns whatever repos can be found within some short window of time and then searches them.

**Comment by slimsag** [comment]
the bad query was already linked in the issue description / slack thread I linked to FYI, here it is: https://k8s.sgdev.org/search?q=repohascommitafter:%222+months+ago%22+error

Looks like it's not timing out anymore but is still VERY slow.

**Comment by ijt** [comment]
Ah, right, I missed that. Something to consider in our other discussions: these URLs don't pop out as queries.

**Comment by slimsag** [comment]
> these URLs don't pop out as queries.

What do you mean?

**Comment by ijt** [comment]
> What do you mean?

The URLs take a moment to recognize as queries.

**Comment by kzh** [comment]
I believe the "No results" is a result of timing out (context deadline exceeded).

**Comment by slimsag** [comment]
So this is still a bit sluggish (compare [with](https://k8s.sgdev.org/search?q=repohascommitafter:%222+months+ago%22+error) vs. [without](https://k8s.sgdev.org/search?q=error), but definitely works and is not unbearably slow. We'll call this an experimental feature and when asked mention it is a little slow but otherwise I think this is good to go / the issue here is resolved.

Will test a bit more and check off release testing grid.

**Comment by slimsag** [comment]
reopening / reusing this issue for the result inaccuracy problem

**Comment by ggilmore** [comment]
https://k8s.sgdev.org/search?q=repohascommitafter:%221+second+ago%22+error returns many results (which can't be true)

**Comment by slimsag** [comment]
There are some more minor issues here still but good enough to ship as experimental now and it works in most cases nicely :)
