### ISSUE TITLE
Show site configuration edit history on details page 

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#46032]
Depends on https://github.com/sourcegraph/sourcegraph/issues/46031 and is part of https://github.com/sourcegraph/sourcegraph/issues/40377

## Tasks

To be made more granular

- [ ] Show site-configuration page below configuration show list of edits over time, including author, timestamp
- [ ] Show "diff" for each edit

Cool sketch:

<img width="963" alt="screenshot_2023-01-02_16 07 06@2x" src="https://user-images.githubusercontent.com/1185253/210249191-8bf6636b-6ba5-4355-a9d7-59347a9e8ccb.png">

**Comment by indradhanush** [comment]
WIP here: https://github.com/sourcegraph/sourcegraph/tree/ig/site-config-history-ui

**Comment by indradhanush** [comment]
Add these components to the diff info:

![image](https://user-images.githubusercontent.com/2682729/218475563-6faa7142-2c72-4de4-83cd-5fe94fb6e9d3.png)
