### ISSUE TITLE
Add API authentication check to code host connection checks

### ISSUE THREAD

**Issue by indradhanush** [sourcegraph/sourcegraph#46037]
As a follow up to https://github.com/sourcegraph/sourcegraph/issues/44683, we should add a check that will make an API request to get the currently authenticated user for example to verify that the code host connection is indeed working. 

The exact nature of the check will depend on the code host.

/cc @ryphil

**Comment by mrnugget** [comment]
Closed in https://github.com/sourcegraph/sourcegraph/pull/46918
