### ISSUE TITLE
Token selection: hovering over certain tokens doesn't trigger the code-intel popover and throws errors in the console

### ISSUE THREAD

**Issue by taras-yemets** [sourcegraph/sourcegraph#46071]
https://user-images.githubusercontent.com/25318659/210359479-3f019ead-e556-4b5a-8229-cfe2afa57548.mov

It's likely that [`hover` value](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@35ecf2f7ca68d54bb17376c92cece67375d7acfa/-/blob/client/web/src/repo/blob/codemirror/token-selection/hover.ts?L178:27&popover=pinned) for some occurrences is `undefined` though it's expected to be `HoverMerged | null`.

/cc @felixfbecker

**Comment by fkling** [comment]
I don't think we have that issue anymore.
