### ISSUE TITLE
Return matches when `repoHasFile` filter is used on its own

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#4608]
#### Feature request description

Currently, the `repohasfile` filter must be used with another search term. (E.g. `repohasfile:test foo`). It would be nice to return repository results when it is used on its own.

**Comment by ijt** [comment]
This works now.
 
<img width="538" alt="Screen Shot 2019-08-12 at 9 52 14 AM" src="https://user-images.githubusercontent.com/15530/62882532-ed39d100-bce6-11e9-8451-a3bf717ad1a3.png">
