### ISSUE TITLE
Implement `repoHasFile` filter for symbol matches 

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#4610]
#### Feature request description

Make `repohasfile` work for symbol matches.

**Comment by rvantonder** [comment]
This is possible via `contains`:

[`repo:^github\.com/sourcegraph/ repo:contains(file:README\.md) type:symbol Search`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/+repo:contains%28file:README%5C.md%29+type:symbol+Search&patternType=literal)

Will close when the parent issue #18584  is closed

**Comment by fkling** [comment]
Looks like this can be closed. We currently have a [validation for `repohasfile:... type:symbol`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@bac67ad723752a6cc5c3c6a25c5f31ce75a9f20f/-/blob/internal/search/query/validate.go?L450-464). I guess that needs to stay in place but needs to be updated to suggest the `contains(...)` predicate?

**Comment by rvantonder** [comment]
Yeah we can close this. The deprecated `repoHasFile` validation can stay, until we remove it. We can remove it once `contains` is optimized for a case where `repoHasFile` is sometimes faster.
