### ISSUE TITLE
Remove workaround for race condition in SearchResultsList

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#4612]
For me to follow up on https://github.com/sourcegraph/sourcegraph/pull/4568#issuecomment-503675317

**Comment by slimsag** [comment]
Confirmed this is fixed on k8s.sgdev.org.

**Comment by slimsag** [comment]
Oops, meant to close https://github.com/sourcegraph/sourcegraph/issues/4564 not this.

**Comment by lguychard** [comment]
Relevant code: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@02ff6fa776e5470535ff3b8a08bf61bd432c4104/-/blob/web/src/search/results/SearchResultsList.tsx#L362-375

**Comment by lguychard** [comment]
This is no longer relevant with streaming search results.
