### ISSUE TITLE
Add reason to site history config

### ISSUE THREAD

**Issue by indradhanush** [sourcegraph/sourcegraph#46153]
Follow up to #40377 and #46031.

With the introduction of persisting author in site config (#46150), we will not necessarily always have a `author_user_id` available.

For example, during site startup if the site config file being loaded has changed. (See comments in linked PR). This means even though once Sourcegraph starts storing the `author_user_id` for changes made from the UI, there will be instances where author information will not be available. 

This can be concerning for site admins at first glance as they start seeing the edit history but don’t see an associated author with it.

To alleviate any such concerns, we should consider adding a `reason` column to the `critical_and_site_config` table such that either this or the `author_user_id` is always set going forward.

**Comment by mrnugget** [comment]
Indra says he doesn't feel that strongly about this anymore. We can always reopen.
