### ISSUE TITLE
CTA metrics

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#46158]
While we've added eventLoggers to all of our new CTAs, we don't have a good way to distinguish one from another if they're on the same page (ie, have the same url). Knowing which CTAs are working better than others on a given page will help us clean up those pages by removing the ones that aren't working. 

Step 1: @kelsey-brown to determine the best way for Amplitude to ingest this information
Step 2: @almeidapaulooliveira to update Figma metrics based on input from Kelsey
Step 3: @st0nebraker or @marekweb to update the CTAs in the source code to reflect new metrics from @almeidapaulooliveira

**Comment by kelsey-brown** [comment]
@st0nebraker and I discussed this briefly yesterday; her suggestion was to log the event as part of the argument like we do [here](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/search/results/searchResultsExport.ts?L187), and I'm on board with that! We'll be able to parse the argument in the Amplitude transformation to make it accessible. 

We also agreed that we just need 1 argument field to describe the location (on the /about site CTAs we log a few description parameters for CTAs, but don't think that's needed here). Per Becca, something along the lines of: 

- `{ cloud-cta-type: NavBar }`
- `{ cloud-cta-type: ContextDropDown }`
- ...etc

**Comment by taylorsperry** [comment]
Sweet, thanks! @almeidapaulooliveira Would you please update the Figma files so that each Cloud CTA on dotcom has a unique `cloud-cta-type`? Thanks!

**Comment by almeidapaulooliveira** [comment]
I updated the following pages:
[Home page](https://www.figma.com/file/qdUtoveMtn2wI8eaysE1De/UX%3A-Cleaning-up-noise-below-the-search-bar-on-dotcom?node-id=29%3A2418).
[Internal pages](https://www.figma.com/file/ScpDpxciO5DeT9YlUGzPUX/UX%3A-Sign-up-journeys-for-auth'd-users?node-id=1%3A2316).

> One further point, on the Top nav, we have a specific event (ClickedOnTopNavTrialButton). Updating this event name will make it harder to track past analytical data, and we'll keep the same. More on it [here](https://sourcegraph.slack.com/archives/C046X8AG5NY/p1673033573496229?thread_ts=1672927026.884709&cid=C046X8AG5NY).

**Comment by st0nebraker** [comment]
This PR is live, moved ticket to `measuring` for us to keep an eye on these finer details of this event

**Comment by taylorsperry** [comment]
cc @kelsey-brown (re: measuring). Is this still something you can keep an eye on, or do we need to hand over to @ebrodymoore?

**Comment by kelsey-brown** [comment]
Thanks @taylorsperry Eric will probably take this moving forward but I'll take care of the handoff!
