### ISSUE TITLE
4.3.1 Security approval

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#46163]
Patch release issue: https://github.com/sourcegraph/sourcegraph/issues/46161
Buildkite CI link for 4.3.1-rc.1: https://buildkite.com/sourcegraph/sourcegraph/builds/191879

Security must close this issue before releases. It is the responsibility of the Security Engineer on rotation the week the release is cut. More steps will be added in the future.

- [x] All feasible CVEs are closed.
- [x] Any open CVEs are documented in the handbook.

cc @sourcegraph/security

**Comment by ferozsalam** [comment]
Have added a CVE page for the release in [this PR](https://github.com/sourcegraph/handbook/pull/5948)

**Comment by ferozsalam** [comment]
I've run the checks on our side @ggilmore – it looks good to go!

**Comment by ggilmore** [comment]
Thank you @ferozsalam !
