### ISSUE TITLE
repohasfile 500s

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#4616]
https://k8s.sgdev.org/search?q=type:path+repohasfile:go is returning a 500

**Comment by slimsag** [comment]
Likely same cause as https://github.com/sourcegraph/sourcegraph/issues/4604 see discussion thread https://sourcegraph.slack.com/archives/CHEKCRWKV/p1560992204072300

**Comment by slimsag** [comment]
Fixed by cherry-picking a commit that already existed, see slack thread above

**Comment by slimsag** [comment]
(just waiting to confirm on k8s.sgdev.org)

**Comment by slimsag** [comment]
Fixed, it now shows the error properly instead of 500ing

**Comment by ggilmore** [comment]
<img width="1440" alt="Screen Shot 2019-06-20 at 12 12 39 AM" src="https://user-images.githubusercontent.com/9022011/59828557-26118700-92f0-11e9-969e-dc35f025ff36.png">
