### ISSUE TITLE
Install the latest compatible src-cli version

### ISSUE THREAD

**Issue by Piszmog** [sourcegraph/sourcegraph#46219]
Today, when running the command `executor install src-cli`, the minimum compatible version is downloaded and installed. The minimum version is specified by a [constant](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@v4.2.1/-/blob/internal/src-cli/consts.go?L9). This can cause issues when a user runs `executor validate`.

During validation, the version of `src` is checked against the _latest_ compatible version (by checking GitHub releases). Meaning if minimum supported version is behind the latest patch version, the validation check will fail.

We have a [TODO](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/enterprise/cmd/executor/internal/run/install.go?L299) to install the _latest_ compatible version.

## Done

- Update the install command for `src` to use the _latest_ compatible version instead of the minimum supported version
- If the version of `src` that is installed meets the _minimum_ supported version, do not error out.
    - Log a warning telling the user that they should upgrade to the _latest_ compatible version

**Comment by eseliger** [comment]
just a side-note: If we were able to get the native SSBC execution turned on by default we could remove the src-cli dependency entirely eventually.
