### ISSUE TITLE
Sourcegraph for VSCode extension doesn't render search page

### ISSUE THREAD

**Issue by taras-yemets** [sourcegraph/sourcegraph#46247]
- **Sourcegraph version:**  VSCE v2.2.14
- **Platform information:**  VSCode v1.74.2

#### Steps to reproduce:

1. Install the latest VSCE extension (v2.2.14 for the time being).
2. Open it by clicking the Sourcegraph icon in the sidebar.
3. Check out the search page.

#### Expected behavior:
The search page is rendered (v2.2.13).
<img width="1524" alt="Screenshot 2023-01-09 at 15 54 25" src="https://user-images.githubusercontent.com/25318659/211324192-4547d8ba-7340-4676-90e8-e5a440d440d0.png">

#### Actual behavior:
The search page is not rendered (v2.2.14). 
<img width="1524" alt="Screenshot 2023-01-09 at 15 53 06" src="https://user-images.githubusercontent.com/25318659/211324254-04c3cd0f-4f88-433b-9d88-0a170f4729d7.png">

The following errors are thrown in the console in dev mode.
<img width="1215" alt="Screenshot 2023-01-09 at 12 12 05" src="https://user-images.githubusercontent.com/25318659/211324352-2fcf53ce-2495-402e-b467-c2f85555fa0b.png">

If you would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are no [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

/cc @felixfbecker

**Comment by felixfbecker** [comment]
Could it be that VS Code changed something about their CSP that we need to react to?
