### ISSUE TITLE
single-binary: embedded postgres port conflicts

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#46261]
On my machine I can't run the binary because Postgres is already running bound to that port:

```
.bin/sourcegraph-darwin-arm64-dist
unable to set up PostgreSQL: process already listening on port 35432
```

```
sudo lsof -i -P | grep LISTEN | grep :35432

postgres  94742 stephen@sourcegraph.com    8u  IPv6 0x5512fbcfd35265cf      0t0    TCP localhost:35432 (LISTEN)
postgres  94742 stephen@sourcegraph.com    9u  IPv4 0x5512fbd4a03ec5f7      0t0    TCP localhost:35432 (LISTEN)
```

**Comment by slimsag** [comment]
If I set `USE_EMBEDDED_POSTGRESQL=false` then it's happy to use my system Postgres, but that is probably not a good default and doesn't explain why the binary doesn't just pick an unused port.

It looks like `startEmbeddedPostgreSQL` just hard-codes `35432` as the port right now and can probably be changed to acquire a free TCP port instead or something.

**Comment by keegancsmith** [comment]
> It looks like `startEmbeddedPostgreSQL` just hard-codes `35432` as the port right now and can probably be changed to acquire a free TCP port instead or something.

Alternatively you can use unix sockets. postgres doesn't have to use TCP. I use unix sockets in my devenv with sourcegraph with no problem.
