### ISSUE TITLE
Spike: Catch up with IAM team to go over current state of permissions.

### ISSUE THREAD

**Issue by varsanojidan** [sourcegraph/sourcegraph#46270]
We haven't worked on permissions for quite some time now, this is a placeholder for a catchup call about the current state of Permissions that we would like to have with the IAM team.

The result of this spike(call) should be the creation of the stories required to implement the remainder of Permissions Syncing for ADO.

/cc @ryphil

**Comment by indradhanush** [comment]
New issues have been created and added under Milestone 2 in the [tracking issue](https://github.com/sourcegraph/sourcegraph/issues/46265).
