### ISSUE TITLE
Notebook papercuts feedback

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#46289]
[From @willdollman on Slack:](https://sourcegraph.slack.com/archives/C03CSAER9LK/p1673003624455339)

> A few pieces of ux feedback on Notebooks. These are all just little things that didn’t quite work the way I intuitively expected them to, so take with a pinch of salt:
> 
> 1. “Run all blocks” doesn’t render markdown text and save searches - instead you have to click “render”/“save” on each one (or refresh the page). Maybe “Run all” is the wrong button, but a way to render/save all blocks would be nice.
> 2. I intuitively expected grabby handles on the left side of blocks to reorder them. The move up/down buttons feel clunky compared to drag and drop.
> 3. Starting from a blank notebook it took maybe a minute to realise I needed to click on blocks in order to bring up the menu. It feels like the menu should appear when you mouseover a block, or a … indicator to hint you can click.
> 4. No click/drag to select line numbers when adding code from a file. It’d also be nice if open ranges worked, ie 15- displays line 15 onwards rather than requiring a closing line number.

Intuitively, 1 and 3 seem very easy. 2 is harder since we don't have a drag/drop library/component. Unsure about 4 since it depends on our code display component.

/cc @sourcegraph/search-product

**Comment by CSMonkee** [comment]
Copied from [here](https://sourcegraph.slack.com/archives/C03CSAER9LK/p1673525250369579) for my observations whilst playing with Notebooks for the first time.

- When selecting a search result file, it would be helpful to see my chosen file highlighted amongst the list of files returned by the search.
- When using the 'Find a file using a Sourcegraph query', it would be great to cache the line range specified for my chosen search result file. If I toggle files, this context is lost.
- Upon returning to edit a 'Find' query in the notebook, my query is no longer displayed. This feels counter-intuitive.
- When duplicating a 'Find' block, the file selected in the original block is preserved, which suggests that despite the fact the query is not shown, it's context remains.

**Comment by camdencheek** [comment]
Closing as "won't fix" since we are not investing in notebooks
