### ISSUE TITLE
Code Insights: [FE audit] Migrate "add or remove insight" view to async search 

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#46291]
## Background 

Currently code insights "add or remove insights" view (see the picture below) load all reachable/accessible to user insights at once (and actually render them all as well). After that users can search over these insights and select (add) or deselect (remove) to include/exclude insights from a dashboard. 

<img width="1025" alt="Screenshot 2023-01-10 at 16 13 32" src="https://user-images.githubusercontent.com/18492575/211640897-f8d99bdc-a877-4a99-aeb6-4e55c776183e.png">

## Problem 

The problem here has two parts
- First of all we render all insights at once which is a problem, and instead of it we should adopt here "show more"-like pagination 
- UI there isn't perfect either, we don't change the order of the insight list and this means you can't see picked insights at the beginning, you have to scroll through this list and find it manually 

## Solution 

So I think for the first problem with pagination solution is simple, we just adopt our internal show more pagination there and pagination UI. Similar to what we have in search context and branch pickers

| Search context picker | Branch picker |
| ---------- | ---------- |
| <img width="512" alt="Screenshot 2023-01-10 at 16 20 28" src="https://user-images.githubusercontent.com/18492575/211642205-e4052d92-c579-4aec-909a-a4620d01d33f.png"> | <img width="580" alt="Screenshot 2023-01-10 at 16 22 18" src="https://user-images.githubusercontent.com/18492575/211642542-bfc4e308-c779-4547-877a-a4a9e221e484.png"> | 

For the second problem with UI we should add multi combobox picker where all selected values are represented via "pills" and you can remove them individually. Similar to what we have in batch changes list page (the group filter picker) 

<img width="380" alt="Screenshot 2023-01-10 at 16 24 27" src="https://user-images.githubusercontent.com/18492575/211642958-d9e1f61d-71bf-40a0-9a97-069ee811b3e7.png">

Note: that library that we use in the batch changes UI isn't perfect (in fact we have a hunch that this library adds a lot of complexity for TypeScript compiler according to TS types profiler report). So we should implement our own multi box based on our combobox UI that we already have. It shouldn't be a big stopper for us, at the first glance it seems as not complicated tasks to do.

**Comment by felixfbecker** [comment]
I don't know if problem (2) is really a big problem in practice given if you want to remove an insight from a dashboard, the easier way to do that is to just use the context menu on the insight and click "Remove from this dashboard" instead of using the "Add insight" button, finding the insight, then unchecking it (honestly not sure why we even need the remove functionality within the modal given we have the context menu action)

**Comment by vovakulikov** [comment]
@felixfbecker I doubt that we can predict customer use cases here. I see how quickly it can get you annoying when you have to open three dot context menu and remove it one by one. I see some cases when multi edit can help you, let's say you're cleaning your team dashboard with non relevant insights. 

If we put aside insight remove action there even adding insight at the moment is problematic, if insights are not close to each other you can easily forget what you've already added (because insight selected insights are rendered in different places in the list)
