### ISSUE TITLE
single-binary: embedded postgres can leave processes around after sourcegraph exits

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#46303]
Related to https://github.com/sourcegraph/sourcegraph/issues/46261

When the single-binary exits unexpectedly, the postgres child process does not terminate. As a result, both resources are leaked and the port is bound preventing it from starting again.

**Comment by keegancsmith** [comment]
This still needs to be solved I assume, but now that we use a unix socket is the behaviour different?

**Comment by slimsag** [comment]
Yeah I believe so. Basically if the `sourcegraph` process dies the postgres server sticks around still.

**Comment by slimsag** [comment]
Presumably it should be a child process somehow so that if the parent dies, postgres also goes away. We already have a fork of embedded-postgres here: https://github.com/sourcegraph/embedded-postgres

Presumably just need to track down by the `exec.Command` in that codebase doesn't die if `sourcegraph` dies

**Comment by keegancsmith** [comment]
> Presumably just need to track down why the `exec.Command` in 
> that codebase doesn't die if `sourcegraph` dies

There are lots of reasons this could be happening. If we don't 
connect to stdout/stdin of the child then I don't think any signal 
(SIGPIPE) is sent to the child in the case of sourcegraph dieing 
hard. Postgres will just get re-parented to process 1. 
Alternatively postgres is daemonizing itself. Alternatively 
postgres is just not behaving how we want it to when the OS 
informs it that the parent is gone.

We may also not be telling the child process to shutdown. I 
suspect the most robust thing to do here is to write a little 
wrapper binary which polls if the parent is still alive and then 
does the appropriate postgres management. Depending on platform we 
can avoid polling, eg linux has a way for a child to opt into 
signals if the parent dies.

**Comment by keegancsmith** [comment]
@slimsag can you give me write access on the fork? or better yet give write access to all of engineering.

**Comment by keegancsmith** [comment]
I got started on this here https://github.com/sourcegraph/embedded-postgres/pull/1
