### ISSUE TITLE
static assets: Do we still have umami and sgdev bundles?

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#4631]
https://github.com/sourcegraph/sourcegraph/blob/b8dd663dbeaba39047978c3ddb0a1719852fb592/cmd/frontend/internal/app/assetsutil/handler.go#L79-L84

Also are these typos? Should it be .js?

**Comment by lguychard** [comment]
This looks outdated, the only reference to `umami` in our codebase is the above.

These are all the phabricator assets served by a Sourcegraph instance. They don't change for sgdev, or umami:

![image](https://user-images.githubusercontent.com/1741180/59908334-77636880-940d-11e9-9d6a-1cd56c6db468.png)

**Comment by keegancsmith** [comment]
Yeah I think this is safe to remove. Additionally I think the logic here is a bit strange. We should be setting the more conservative cache control policy for any assets which has a static name. So extensionHostFrame as well?

**Comment by lguychard** [comment]
Yeah, `extensionHostFrame` should definitely be cached, this would be an oversight on my part when I did #4187. Agreed on the logic being strange.

**Comment by keegancsmith** [comment]
Do all of these have static paths?

https://github.com/sourcegraph/sourcegraph/blob/671346a5cf792b12b6d78c21ffea6e383e59b653/browser/scripts/tasks.ts#L50-L53

If so, we should probably make them all have `Cache-Control: max-age=300, public`. Currently all of them except `phabricator.bundle.js` have `Cache-Control: immutable, max-age=172800, public`

**Comment by keegancsmith** [comment]
Additionally, what other assets have static paths? By static path I mean the path you request by doesn't change, even if the content of the file changes. Most of our assets have a file hash in the filename.

I am looking into this after noticing the cors origin + caching thing when we debugged my phabricator setup.
