### ISSUE TITLE
Add a worker to clean up the permissions sync jobs table

### ISSUE THREAD

**Issue by thenamankumar** [sourcegraph/sourcegraph#46322]
We don't want to keep all the jobs around. Implement worker to clean up completed/failed jobs from the permissions sync table based on a logic(TBD).

1. Add a new worker or extend dbworker to create a new uti -like resetter process to cleanup the jobs table. 
2. The cleanup logic should be: Keep last 5 jobs for every user/repo
3. Make it configurable with site config
4. Add unit tests

**Comment by sashaostrikov** [comment]
Or we can do as it is done for code insights query runner jobs
https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/insights/background/queryrunner/cleaner.go?L21

**Comment by thenamankumar** [comment]
> Or we can do as it is done for code insights query runner jobs https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/insights/background/queryrunner/cleaner.go?L21

sounds good
