### ISSUE TITLE
Gerrit Permission Syncing tracking issue

### ISSUE THREAD

**Issue by pjlast** [sourcegraph/sourcegraph#46334]
## Gerrit background
We have two options to interface with Gerrit: an `experimentalFeature` and a Generic Git code host.

Gerrit has some thorough access management capabilities, and users can interact with Gerrit in 3 ways:
1. Web interface
2. Over SSH
3. Using an HTTP Rest API

We can't leverage the Web interface. We could _possibly_ leverage SSH, but I don't think we quite have the necessary groundwork to have users upload SSH keys and interact with Gerrit like that. So that leaves the HTTP Rest API.

Authentication on the HTTP Rest API uses basic HTTP Auth. This means the user will have to provide us with a username and password. We'll have to be clear on this, and we should double check with customers asking for this if this is okay.

If a user's HTTP password gets reset, which is very easy to do, it's a single button click in the HTTP interface with no warning, they will have to reprovide that password on Sourcegraph.

## Tech decisions

Apart from the above decision, there is also another decision we need to make.
How do we handle the "Auth provider" part of Gerrit?

Auth providers used for permissions syncing need to be linked back to their respective code host. This is generally done through a URL and the code host type. We can do something like this with the Gerrit experimental feautre. But it would maybe be a tiny bit trickier with the generic git code host.

## Tasks

Permissions syncing

- [x] #46773
  - Use the Gerrit HTTP API to fetch repositories a user can access
  - There is no repo-based permissions syncing
    - The Gerrit HTTP API cannot provide a list of users that can access a repository, we would have to traverse groups and subgroups and try to infer permissions from rules, which is very error-prone

User account

- [x] #46622
  - Should not be presented as a sign-in option
  - Users should be able to provide a username and password pair, which would correspond with their Gerrit HTTP credentials

/cc @sourcegraph/source

**Comment by mrnugget** [comment]
Done
