### ISSUE TITLE
Web: scrolling is broken on compare view

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#4634]
#### Steps to reproduce:

1. Visit https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/compare/c8a94201b0273a86a5f91631c915963bd648c55a...a0d0a97754e5963b0bcc4e003eec9534642f2b42#diff-8fafc9dac6c701a020eafaa59db7d806

#### Expected behavior:

You can scroll to the bottom of the diff.

#### Actual behavior:

No scrolling, the bottom of the diff is clipped.

**Comment by felixfbecker** [comment]
This is why I always say in code reviews that `overflow: hidden` is dangerous. I am considering banning it through stylelint. There is really never a reason to clip content.

Here is the offending code: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@proper-tslint-extends/-/blob/web/src/repo/RepoContainer.scss#L13:22

**Comment by felixfbecker** [comment]
This is potentially a bad regression in 1.5.0 that should be patched
