### ISSUE TITLE
Git annotations don't show up in Safari and Chrome

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#46402]
If you open any file with Blob view in safari and open the annotation panel you will see that annotation texts don't show up (only avatars are rendered). This works fine in Chrome though. 

<img width="1025" alt="Screenshot 2023-01-12 at 22 59 19" src="https://user-images.githubusercontent.com/18492575/212219891-523aab70-2f07-4a03-b70d-8b9897ab3600.png">

Steps to reproduce
- Go to the any file (for example [this file](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/BackendInsight.tsx) from the screen above)
- Open the annotation panel
- See that annotation itself are not rendered 

/cc @felixfbecker

**Comment by philipp-spiess** [comment]
@vovakulikov can't repro this 😱 What Safari version are you on? I tried it with the exact link you shared and on localhost and in both cases the text renders fine for me.

<img width="1562" alt="Screenshot 2023-01-13 at 10 38 34" src="https://user-images.githubusercontent.com/458591/212287796-6ab34865-1b7d-406a-baea-dcb3fce26544.png">

cc @sourcegraph/code-exploration-devs

**Comment by vovakulikov** [comment]
@philipp-spiess I'm on Version 15.5 (17613.2.7.1.8) and checked this in the safari technology preview (Safari 16.4, WebKit 17615.1.7.1) and it works (Checked Firefox, It's also fine)

**Comment by vovakulikov** [comment]
I know that fixing bugs for the not latest Safari version isn't our priority usually but based on our browser list we should support this browser (I think this confige is usually used by us and internally only this means we don't have any obligations based on this config) but still seems like prev version of safari is might be popular 

https://browsersl.ist/#q=%3E+1%25%2C+last+1+versions+AND+not+dead+AND+not+%3C0.25%25%2Clast+1+Chrome+versions%2Clast+2+Safari+major+versions%2Cnot+IE+%3E+0
