### ISSUE TITLE
GitHub PR suggestions include after line decorations

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#4641]
![image](https://user-images.githubusercontent.com/10532611/59934083-0e024a80-944b-11e9-8e03-ce96e83fd22c.png)

Note the "0" at the end of the line

**Comment by lguychard** [comment]
Maybe: insert the content as the `before:` of an empty span?

But: decorations still need to be linkable.

**Comment by lguychard** [comment]
Potentially hard to solve.

**Comment by lguychard** [comment]
Maybe: use the text completion API?

**Comment by felixfbecker** [comment]
GitHub seems to have changed their implementation, this doesn't happen anymore.
