### ISSUE TITLE
Browser extension command palette overflows, has bad padding on GitLab.com

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#4646]
Occurs on GitLab.com:

### Chrome web store version v19.6.6.2015

Overflows and has bad padding:

![image](https://user-images.githubusercontent.com/1976/59959317-a7d8f000-9469-11e9-985c-fc4c4af8694d.png)

### `master` branch version

The padding is better but the overflow problem is still present:

![image](https://user-images.githubusercontent.com/1976/59959330-d656cb00-9469-11e9-90ee-77c747e4b05b.png)

**Comment by lguychard** [comment]
Duplicate of #6150
