### ISSUE TITLE
Itemize the current gitserver API

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#46487]
## List the current gitserver API methods, describe them, and compare them to Perforce

Will be used as a jump-off point for determining feasibility of features and for exploring options.

[Google Sheets document](https://docs.google.com/spreadsheets/d/19NW-wtX4MJTu2YG5NQHwBlP4M290Z8kW-Sixq-EeZY4/edit#gid=0)

**Comment by peterguy** [comment]
Itemization, with mappings to Perforce and SVN, is done.
