### ISSUE TITLE
Enable p4-fusion by default

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#46501]
At this point `p4-fusion` has feature parity with `git-p4`. We should move `p4-fusion` out of experimental mode and make it our default.

- [ ] Mark `git-p4` in as deprecated
- [ ] Update docs to make `p4-fusion` the recommended path
- [ ] Figure our migration path from `git-p4` to `p4-fusion`
  - [ ] Config schema will need to change
  - [ ] Investigate whether conversion that first used `git-p4` can switch to `p4-fusion` without the need to delete the repo in disk and start again.
  - [ ] If the above does not work, we may need an OOB migration to work through old repos
- [ ] After a few releases, make `p4-fusion` default in config and remove support for `git-p4`

**Comment by mrnugget** [comment]
@peterguy didn't we do this?
