### ISSUE TITLE
[Umbrella issue] Add new setup UI page

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#46512]
Since we don't have any designs at the moment for the new setup UI this issue is supposed to cover all UI work that we will have about these pages. 

- Prepare a designated route for the new setup UI
- Prepare blank UI for the setup experience (for now we can use previous designs for the cloud setup, [Figma](https://www.figma.com/file/zXvqCASHDzmvKbrAl1EVsd/Public-%26-Private-Repos-for-Users-on-Cloud?node-id=1700%3A0&t=IPJGdep7KyWzUO1k-0))
- Figure out list of API changes that we have to make in order to properly connect setup UI to the backend handlers

**Comment by almeidapaulooliveira** [comment]
@vovakulikov, I created an [design issue](https://github.com/sourcegraph/sourcegraph/issues/46571) to address the design work on this project. I suggest we ignore that old Figma file (although a lot of that design flow will be reused) and concentrate on the new design issue as the source of truth for design work.

**Comment by vovakulikov** [comment]
I'm going to close this one, since we've got designs and split this into separate issues, I will file another issue in case if we will get some valuable feedback from user testing
