### ISSUE TITLE
gRPC: migrate gitserver

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#46522]
See https://github.com/sourcegraph/sourcegraph/blob/1e1eb3fce1a2a8e9fce24a667b53105c2fe9a52e/cmd/gitserver/server/server.go#L553-L579

Done:
- [x] exec - Executes a Git command.
- [x] search - Searches files in Git repositories.
- [x] archive - Handles Git archive requests
- [x] batch-log - Returns log entries for multiple commits 
- [x] p4-exec - Executes a perforce command
- [x] list-gitolite - lists Gitolite repositories 
- [x] is-repo-cloneable - Checks to see if a repository can be cloned
- [x] repos-stats - returns stats for repositories
- [x] repo-clone-progress - returns clone progress for a repositories 
- [x] delete - deletes a repository
- [x] repo-update - updates a repository
- [x] repo-clone - clones a repository
- [x] create-commit-from-patch-binary - creates a commit from a patch
- [x] commands/get-object - retrieves a specified Git object (commit, tag, tree or blob) from a repository.

TODO:

Won't do:
- [ ] git service (`info/refs, `git-upload-pack`): there is no sense in converting this to protobuf since the git binary itself is the client - we have to conform to git client's expectations 
- [ ] create-commit-from-patch (removed because it's unused)

**Comment by eseliger** [comment]
done!
