### ISSUE TITLE
Enhancement: Make limited local install features more clear & point to user's next step

### ISSUE THREAD

**Issue by st0nebraker** [sourcegraph/sourcegraph#46545]
![Image](https://user-images.githubusercontent.com/59381432/212772155-f07dce12-625a-43e1-a68b-64237f28712e.png)

Steps to reproduce:
1. On local install, add a notebook, click the "Share" button
2. Notice above message

Since users can't be added to a local install, limited features should be more clear. Some disclaimer should be added here (i.e. "**_This is a local install sandbox, try Sourcegraph Cloud to make a team on your private code_**")

**Comment by vovakulikov** [comment]
We need to check if this is still a case, probably with Sourcegraph App this UI has been enhanced, but not sure

**Comment by st0nebraker** [comment]
This has been fixed

![image](https://user-images.githubusercontent.com/59381432/225719737-826fed45-386a-4ff3-92bc-3c0461f0bb72.png)
