### ISSUE TITLE
SOFT LAUNCH BLOCKER: If src-cli is not installed, single-binary may not start

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#46543]
```
[    sourcegraph] ERROR service run/util.go:40 Failed to get src-cli version {"error": "exit status 126"}
[    sourcegraph] ERROR service run/util.go:40 Failed to get src-cli version {"error": "exit status 126"}
```

More context: https://sourcegraph.slack.com/archives/C04F9E7GUDP/p1673895116702359?thread_ts=1673750482.204729&cid=C04F9E7GUDP

Easily reproduced (`sg start sourcegraph` with a broken `src` on your PATH)

**Comment by keegancsmith** [comment]
Do we want to embed src-cli binary into the binary, make it possible to run src-cli via the sourcegraph binary or just complain in a nicer way when the dependency is missing?

**Comment by slimsag** [comment]
Created https://github.com/sourcegraph/sourcegraph/issues/48879 - it'd be great to do that but probably not enough time before starship.
