### ISSUE TITLE
Remove webhook build job

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#46562]
This was left over from our intern project and is currently unused. With recent changes to add a dashboard to display worker processes it is confusing to see this job as it doesn't do anything at the moment.

We should at the very least remove the job from [the list of jobs](https://github.com/sourcegraph/sourcegraph/blob/fa037a33cd1f7e2fc7c319a1591b27a3acb63d8c/enterprise/cmd/worker/shared/shared.go#L41)  and ideally also remove the code and db tables as we probably won't get to background webhook creation for a while and having unused code lying around isn't great.

/cc @ryphil

**Comment by mrnugget** [comment]
> We should at the very least remove the job from [the list of jobs](https://github.com/sourcegraph/sourcegraph/blob/fa037a33cd1f7e2fc7c319a1591b27a3acb63d8c/enterprise/cmd/worker/shared/shared.go#L41) and ideally also remove the code and db tables as we probably won't get to background webhook creation for a while and having unused code lying around isn't great.

I think we shouldn't go for "keep the code, but remove from the list", which would make the code even deader. Let's remove the code.
