### ISSUE TITLE
Flatten client side routes

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#46570]
## Context

We need the routes map to use the data-loader-aware React Router. See https://reactrouter.com/en/main/routers/picking-a-router#using-v64-data-apis

**Comment by philipp-spiess** [comment]
Starting some notes for this in https://docs.google.com/document/d/1GHWw_OLEUJPKJivou8NkdhjxOtLkO4Lny00iMRJBVEE/edit#

**Comment by philipp-spiess** [comment]
@valerybugakov 

Reading through https://reactrouter.com/en/main/upgrading/v5 we may actually be able to do this iteratively by only changing the top level route (in our case the thing that `<Layout>` renders) and then the specific sub-paths that we need to reach the page we want to enable the new infra for.

E.g. if we want to migrate Blob content, we only need to make sure all `RepoContainer` routes are in the flat route list, unrelated nested routes can stay as-is.

**Comment by valerybugakov** [comment]
This is awesome! I added these notes to [our meeting document](https://docs.google.com/document/d/1_IDc-jqWZt1Oim-YvvqfofCmsZilTWVnDtT6BA_8WTc/edit#heading=h.ntdas688el7z) after we discussed them!

**Comment by philipp-spiess** [comment]
We're not going to migrate all routes to a flat route object in one go and instead will migrate routes on a per-file route basis, so I don't think this issue is relevant anymore.
