### ISSUE TITLE
Make search prototype ready for merge

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#46585]
This PR https://github.com/sourcegraph/sourcegraph/pull/45973 should be cleaned up and merged.

- We want to add feature-flagging to it
- Code review and cleanup
- Cache compiled globs in matcher

**Comment by malomarrec** [comment]
Question: does this search support looking up unowned files? I was wondering if we get that just by virtue of adding searching by owner.

**Comment by eseliger** [comment]
Yes I added that to the prototype, you can pass an empty owner that means `Owned by any` and using negation you can turn it then into NOT (Owned by any)` and that seems to work alright.

**Comment by cbart** [comment]
Some things left over:

- [ ] testing a search for owned (by anyone) files with `file:has.owner()` and without an owner `-file:has.owner()`
- [ ] allow searching with display name by querying the teams and resolving to an email or username
