### ISSUE TITLE
spike: `select:owner` search prototype

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#46587]
We've talked about adding a new search result type: Ownership. This will allow to (deduplicated) enumerate the list of owners for a given repo, set of repos, and such. Later: Contact all quick action. Also: This should help with search aggregation by owner.

Initially, we should do a ~1d spike to see what it entails to add this, so we can scope out the work better next sprint.

**Comment by eseliger** [comment]
Note: This needs to be implemented in jetbrains as well

**Comment by malomarrec** [comment]
Added an issue about the use case/scenario that this enables. Unaissigning myself now.

**Comment by eseliger** [comment]
This Figma captures initial design ideas for this: https://www.figma.com/file/IL8OZuLU8YHFP6yhC7SBlu/Own-in-search-results?node-id=1%3A5932&t=HhON7J0JQ6Zz6top-0

**Comment by eseliger** [comment]
@leonore @limitedmage Do we have an idea yet of what this entails and how the work could be split up?

**Comment by leonore** [comment]
@eseliger I have a meeting with Camden in a couple hours to talk about how we could extend the search facility with a new selector. I'll report back on findings after and hope to split up some work there. I've got a sync with Juliana on Wednesday too (timezones are making syncs complicated)

**Comment by eseliger** [comment]
Awesome! 🚀

**Comment by eseliger** [comment]
Awesome! 🚀

**Comment by leonore** [comment]
closing spike in favour of https://github.com/sourcegraph/sourcegraph/issues/46990
