### ISSUE TITLE
batches: changeset error message shouldn’t disappear from the UI until a batch change retry actually succeeds

### ISSUE THREAD

**Issue by adeola-ak** [sourcegraph/sourcegraph#46651]
a customer is unhappy with what happens during the retry loop: [slack thread](https://sourcegraph.slack.com/archives/CMMTWQQ49/p1674082705160849)

It can be hard to capture the error message as it flashes while a failed batch change continues to retry

This fix can go hand in hand with #46652 , which addresses the need to add a button or mechanism for stopping automatic retries on a given changeset that’s misbehaving.

**Comment by courier-new** [comment]
This has even annoyed me developing locally, so selfishly, P0. 😛

We should see if on the backend we can just wait to update the `FailureMessage` on a changeset until after it finishes processing and either fails with a new message or succeeds. It's useful to preserve the last failure message during the re-processing, and this avoids us having to build complicated frontend logic to save the last-seen error message as state. I've estimated this issue assuming that's viable.

**Comment by courier-new** [comment]
Let's copy the `FailureMessage` into a new column like `PreviousFailureMessage` which we could surface over GraphQL and show a slightly different "older error" styling for.
