### ISSUE TITLE
insights: search context filters do not error when a json based context is entered

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#46690]
Found in v4.4.0 

Insights can only be filtered by query based search contexts.  When a user enters a context that does not exist a red boarder is placed on the field and the user can not save the changes.  

However if the user enters the name of a json based search context the error message is displayed saying `No query-based search context found` however the user is allowed to save the value.  

![image](https://user-images.githubusercontent.com/6098507/213577835-4408fa00-73ba-43af-979a-e23314ae71a9.png)

Expected result is that the red error box should be applied and the user should not be able to save the value.

/cc @felixfbecker @vovakulikov

**Comment by gabtorre** [comment]
Hey @chwarwick, can I pick this one up?

**Comment by chwarwick** [comment]
> Hey @chwarwick, can I pick this one up?

Sure let us know if you have any questions.
