### ISSUE TITLE
repo:has.description parameter shows repo name instead of description on Bitbucket server repos

### ISSUE THREAD

**Issue by mibali** [sourcegraph/sourcegraph#46713]
- **Sourcegraph version:**<v4.2.1
- **Platform information:** Bitbucket Server v7.21.4

#### Steps to reproduce:

1. create repo with a description on [bitbucket.sgdev.org](http://bitbucket.sgdev.org/)

![image](https://user-images.githubusercontent.com/111276665/213712828-4bf758b7-6418-41e1-87a5-69d96c2ddede.png)

2. Use the `repo:has.description(some_description)` search query to get the repo name and description

![image](https://user-images.githubusercontent.com/111276665/213712880-db7650eb-4b80-4e1d-bbfa-b7c82778b1e5.png)

#### Expected behavior:
It is expected that the search query should show the repo description instead.

#### Actual behavior:
It shows the repo name instead of the repo description.

![image](https://user-images.githubusercontent.com/111276665/213713386-0ce96480-65ee-423f-a2c6-c80866701539.png)

If you would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are no [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

/cc @ryphil

**Comment by indradhanush** [comment]
Suggested solution: 

Use the [latest](https://developer.atlassian.com/server/bitbucket/rest/v807/api-group-project/#api-api-latest-projects-projectkey-repos-repositoryslug-get) API to get the repos and use the `description` from the response to set the `description` on the repo.
