### ISSUE TITLE
Show permissions overview on repo settings page

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#4672]
From a user at https://app.hubspot.com/contacts/2762526/company/557889642:
>>>
Setting this enforcement is clear. But after applying this change I’m missing some more information about its impact. Something like some information on repository Settings page, so I can clearly see that enforcement is active for that repository and some list of allowed users/groups who can see that repository.

**Comment by tsenart** [comment]
@dadlerj: Can this be closed or do you see value keeping it open?

**Comment by dadlerj** [comment]
Not relevant for the customer above anymore, but still feels like a reasonable addition 🤷‍♀. I leave it to core/product.

**Comment by tsenart** [comment]
@unknwon: This is part of the UI/UX work to be done around permissions in future milestones.

**Comment by tsenart** [comment]
@christinaforney: @unknwon is doing some work next iteration on UI for permissions. I think you and @imtommyroberts should at least be aware of that. It's not a necessity that we get designs for any of this now, but eventually I'm sure the design can be improved. For now it's easy enough to extend what is already there to account for the added features:

- #8990 
- #8989
- #8988

**Comment by imtommyroberts** [comment]
@tsenart Okay no worries, thanks for letting me know! It's probably worth me and @unknwon hopping in a call when they're working on it in case there's anything that stood out to me that would be worth changing (that fits within scope/timescales of course)

**Comment by tsenart** [comment]
Yeah, cool! @unknwon please find some time to bring @imtommyroberts up to speed on the permissions work.

**Comment by unknwon** [comment]
Pretty sure this is already implemented.
