### ISSUE TITLE
Custom (non-hyphen) username normalization

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#4674]
From a user at https://app.hubspot.com/contacts/2762526/company/557889642 while testing repository permissions

>>>
And there is one important problem that I ran into. The problem is because of SourceGraph “Username normalization” that dictates this “Any characters not in [a-zA-Z0-9-] are replaced with –“. Usernames in our company are used in form of “name.surname.” so that is an issue when they are transformed into new form “name-surname” because of that username is not same as in $CODEHOST, thus users can’t see any repositories.

**Comment by tsenart** [comment]
cc @sourcegraph/core-services

**Comment by tsenart** [comment]
Addressing this today.
