### ISSUE TITLE
Search with # in file path causes "file does not exist"

### ISSUE THREAD

**Issue by ApocDev** [sourcegraph/sourcegraph#4675]
- **Sourcegraph version:** 3.4.4
- **Platform information:** Docker:latest

#### Steps to reproduce:

1. Import a repository with a directory structure such as "src/main/c#/code_here.cs"
2. Find a result in the C# file, and attempt to follow the provided link

#### Expected behavior:

URLs with special path characters should be valid, and viewable.

#### Actual behavior:

"Git ls-tree src/main/c: file does not exist"

**Comment by camdencheek** [comment]
Closing as fixed since I can no longer reproduce
