### ISSUE TITLE
AWS Marketplace

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#46756]
**Note: this is a public issue**

Amazon FTR process checklist (docs requirements):
- Suggest disk encryption by default
- Have the option to deploy to a private subnet (right now we suggest deploying in such a way that Sourcegraph is accessible on the public internet immediately in a not-locked-down way.)

Follow up on security requirement flagged here: https://sourcegraph.slack.com/archives/C042DHN76HE/p1674755011968839

/cc @sourcegraph/delivery

**Comment by jdpleiness** [comment]
Ongoing work in progress. Currently undergoing AWS approval process

**Comment by jdpleiness** [comment]
AWS approval process in final stages.

**Comment by jdpleiness** [comment]
### Current issue with AMI launched from Marketplace unable to start

- AMI launched after customer accepts offer is not starting (v5.0.0)
- Source AMI that Marketplace AMI is based off still works as expected (v5.0.0)

TODO:

- [ ] Verify AMI contents as well as any AWS processes that may alter our AMI when submitted to the marketplace
- [ ] Update AMI in marketplace to latest version v5.0.3 atm

**Comment by jdpleiness** [comment]
Process completed. AMI has been in marketplace for some time and is in use by multiple customers.
