### ISSUE TITLE
Sourcegraph extension prevents double click for word selection on Bitbucket Server

### ISSUE THREAD

**Issue by christinaforney** [sourcegraph/sourcegraph#4676]
- **Sourcegraph version:** 
- **Platform information:** 

Reported by user at: https://app.hubspot.com/contacts/2762526/company/407948923

Extension v19.6.6.2105 (and I think I’ve had it since I installed last month)
Chrome 74.0.3729.169 (and earlier versions as well)
MacOS 10.14.5 (and again, since earlier versions as well)

#### Steps to reproduce:

1. On Bitbucket Server, double click on a word
2. See the last character at the end of the line selected, not the hovered word

#### Expected behavior:
When double-clicking the whole word is selected

Some other details:
• Triple-click still selects the full line as expected
• In all cases the sourcegraph context-popup appears as expected as I hover the mouse over any text
• The double-click behavior works on the sourcegraph site as expected

#### Actual behavior:
When I attempt to double-click on any text only the last character in that line is selected. 

Related: #4051

**Comment by chrismwendt** [comment]
I believe this will be solved by #4051, which unfortunately hasn't been published yet. There's a CI failure https://buildkite.com/sourcegraph/sourcegraph/builds/38641#d43ede2e-73ad-4beb-842d-05d9b31197dc

Assigning myself.

**Comment by chrismwendt** [comment]
Confirmed fixed in v19.6.27.856 https://buildkite.com/sourcegraph/sourcegraph/builds/38716
