### ISSUE TITLE
Cleanup nightly AMIs

### ISSUE THREAD

**Issue by Piszmog** [sourcegraph/sourcegraph#46786]
When our CI runs, it will create a nightly executor AMI (e.g. `sourcegraph-executors-nightly-12345`). These have accumulated in AWS and are quite expensive to keep around. 

We should write some sort of automation that deletes the nightly AMIs if they are over 60 days old.

## Done

- Delete nightly AMIs that have a creation date over a certain period of time.
    - Default to 60 days, but be configurable
- Run the automation to cleanup existing AMIs

## Technical Details

- Where should this automation live?
- Where should the code for this automation live?

**Comment by Piszmog** [comment]
We may be able to just have AWS do this for use. Looks like either a retention rule or an AMI lifecycle policy.

**Comment by sanderginn** [comment]
Findings so far:
- Retention rules will preserve resources that are deleted in a recycle bin for the specified amount of time before they are deleted, which is not what we are looking for
- Lifecycle policies seem to only implement deletion _and_ creation of AMIs, not just deletion, which is also not what we want
- The community Packer plugin [amazon-ami-management](https://github.com/wata727/packer-plugin-amazon-ami-management) adds a post-processor to the build step of Packer that can set a number of releases to keep or maximum age for images. This seems to be the lowest effort to implement. 
  - I don't think that the build step is the _best_ place to do this, but if it's documented in the handbook, I think it's acceptable given how straightforward it is. 
  - It will require retroactively tagging the nightly images with an additional `Amazon_AMI_Management_Identifier` tag, which is used by the plugin to determine candidate images, or a manual one-off deletion of AMIs older than X.
  - Running a dry-run test with this to see whether it works well enough.
- Alternatively this can be done with some other automation (a Buildkite step or GHA) and manual scripting, but requires more effort.
