### ISSUE TITLE
management console login fails with `error saving: 0`

### ISSUE THREAD

**Issue by ijt** [sourcegraph/sourcegraph#4679]
I tried logging into the management console of my dev instance at `localhost:2633`. After entering my admin username and management console password, it brought up an alert saying `error saving: 0`:

![Screen Shot 2019-06-25 at 14 07 16](https://user-images.githubusercontent.com/15530/60138180-3e552c00-975e-11e9-9ccc-0af3b46e8026.png)

I clicked the `OK` button but it remained with the `Loading...` message.

**Comment by ijt** [comment]
It happens on Chrome and on Firefox.
Dropping the local database and Redis doesn't help.
Using an incognito window doesn't help.

**Comment by ijt** [comment]
This issue blocks work on improving tracing. It also blocks figuring out what's causing the build to fail on https://github.com/sourcegraph/sourcegraph/pull/4649.

**Comment by slimsag** [comment]
You are not blocked on either of those: You do not need to use the management console to edit config, use `./enterprise/dev/start.sh` and edit the config in dev-private and restart your server. You have to do that anyway for tracing.

**Comment by beyang** [comment]
I could not repro this. @ijt maybe we can debug in person when you're back.
