### ISSUE TITLE
No symbols shown for files with names containing a `+`.

### ISSUE THREAD

**Issue by vanesa** [sourcegraph/sourcegraph#4687]
- **Sourcegraph version:**  Sourcegraph.com/ 3.5

#### Steps to reproduce:

1. Visit https://sourcegraph.com/github.com/neonichu/Azkaban/-/blob/Sources/azkaban/ATZPackage+Azkaban.swift
2. Click on the Symbols tab on the menu and notice that no symbols are shown.
3. Navigate to any other file in that folder that doesn't contain `+` in their name and notice that the symbols for those files do load.
4. Navigate to the parent folder `azkaban` and see that symbols inside `ATZPackage+Azkaban.swift` are listed correctly in the symbols menu and link to `ATZPackage+Azkaban.swift`, yet disappear from the menu as soon as you are viewing the file.

#### Expected behavior:
Showing symbols in the symbols menu.
#### Actual behavior:
No symbols even though there are multiple symbols in the file.

![image](https://user-images.githubusercontent.com/9110008/60218501-68712180-9824-11e9-8ff6-1e10ebb2438e.png)

**Comment by vanesa** [comment]
Also related: https://github.com/sourcegraph/sourcegraph/issues/4693

**Comment by beyang** [comment]
Can @sourcegraph/code-nav triage?

**Comment by chrismwendt** [comment]
This is a problem with a path being interpreted as a regex (not a URL encoding problem). I introduced this bug in https://github.com/sourcegraph/sourcegraph/pull/2877/files#diff-67a39d409187e44dc74f6bab6d9d7426R101
