### ISSUE TITLE
code host connection check: `net.Dial` fails behind proxy

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#46915]
Part of https://github.com/sourcegraph/customer/issues/1897 is that the connection checks fail for the customer:

![image](https://user-images.githubusercontent.com/1185253/214524962-bdd61506-0b8b-493b-8f1b-8ba9152347bc.png)

### Problem

They're behind a proxy where our ping fails:

https://github.com/sourcegraph/sourcegraph/blob/64f1e51091e39654fe03da12632bd56e074d62fd/internal/repos/check_connection.go#L113-L115

Customer says:

> Yes, the TCP dial will fail.
> Everything has to go through a proxy.
> I've not worked in a an environment for a long time where it would pass.

This was released in 4.4.

### Options

We should change the connection check to reflect what we're after: can we talk via HTTP to the API? That's not what we want for every code host, but for GitHub and GitLab it's what we want.

/cc @ryphil

**Comment by indradhanush** [comment]
This can be closed?

**Comment by mrnugget** [comment]
Yup!
