### ISSUE TITLE
Plan for LSIF support

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#4692]
[LSIF](https://code.visualstudio.com/blogs/2019/02/19/lsif) promises fast and precise code intelligence (something that neither language servers nor basic code intel have been able to provide) at the cost of CI configuration. This fits a niche that customers might be interested in, and I think the best way to see is to build it and try it ourselves.

Comparison of different code intel approaches: https://docs.google.com/document/d/1pB5OPzW-FBs-b8FegkpwgEM9FQBh1eaQ-jf5TSxAPgs/edit

Google doc with more info https://docs.google.com/document/d/1W0L0Z34Og7j0WRHEesxs_92I0vOmy-eC0BvbOVzFGww/edit

**Progress so far**

I prototyped LSIF in a Sourcegraph extension communicating with lsif-node on localhost last month:

- https://sourcegraph.slack.com/archives/C89KCDK5J/p1556934227046300
- https://sourcegraph.slack.com/archives/C89KCDK5J/p1556940616047700

**GopherCon TODO**

- [ ] Add a new kind of token, an LSIF upload token which corresponds to a specific repository, distribute these somehow (e.g. GitHub's security reports) @chrismwendt
- [ ] Convert repository names to IDs before handing off the request to lsif-server @chrismwendt
- [ ] Write a LSIF generator for Go @chrismwendt
- [ ] Docs page for how to generate LSIF and upload it to Sourcegraph @chrismwendt

**Comment by scalabilitysolved** [comment]
As we currently have several LSIF indexers and adoption I believe we can close this issue out.  Thoughts @efritz @macraig ?

**Comment by macraig** [comment]
@scalabilitysolved agreed, closing.
