### ISSUE TITLE
4.4.1 Security approval

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#46932]
Security must close this issue before releases. It is the responsibility of the Security Engineer on rotation the week the release is cut. More steps will be added in the future.

- [x] All feasible CVEs are closed.
- [x] Any open CVEs are documented in the handbook.

Release tracking issue: https://github.com/sourcegraph/sourcegraph/issues/46931

cc @sourcegraph/security

**Comment by ferozsalam** [comment]
The CVEs have been updated as part of https://github.com/sourcegraph/handbook/pull/6088, this is now good to go.
