### ISSUE TITLE
Add syntax highlighting/autocomplete for new owner search predicate

### ISSUE THREAD

**Issue by leonore** [sourcegraph/sourcegraph#46949]
once the owner search prototype is implemented we should make sure we have proper syntax highlighting and autocomplete for it.

we should also make sure the owner type is documented and can be shown in the reference panels

**Comment by eseliger** [comment]
@limitedmage was this already implemented in one of your branches?

**Comment by limitedmage** [comment]
Yes, this is already implemented in https://github.com/sourcegraph/sourcegraph/pull/47214
