### ISSUE TITLE
Updating a bitbucket pullrequest removes default reviewers configured on codehost

### ISSUE THREAD

**Issue by BolajiOlajide** [sourcegraph/sourcegraph#46970]
A feature exists on Bitbucket that gives engineers the ability to set default reviewers on a repository.

![CleanShot 2023-01-26 at 02 03 40@2x](https://user-images.githubusercontent.com/25608335/214731753-d9460804-cafc-40c5-af03-426a41baef9f.png)

https://github.com/sourcegraph/accounts/issues/565 makes use of this feature, and recently reported a bug where a changeset is created via a Batch Change, once published on the codehost and reviewers assigned to that changeset, any update to the changeset removes the default reviewers.

![CleanShot 2023-01-26 at 02 07 03@2x](https://user-images.githubusercontent.com/25608335/214732350-9107f5e8-f2c6-488d-bbfc-64cd68c9ce0c.png)

I tested using this and dug into the API [docs](https://developer.atlassian.com/server/bitbucket/rest/v807/api-group-pull-requests/#api-api-latest-projects-projectkey-repos-repositoryslug-pull-requests-pullrequestid-get) to find out why this is happening and it seems Bitbucket does a full update (as expected for a PUT request), so when the reviewers field isn't provided in the update query, it removes them on the codehost. However, I tried passing in the reviewers into the update request payload, but the same thing occurred.

Something stood out in the documentation: `Note: the reviewers list may be updated using this resource. However the author and participants list may not.`. I also found this [discussion](https://community.atlassian.com/t5/Bitbucket-questions/curl-PUT-command-removes-the-reviewers-from-pull-request-while/qaq-p/827498) while surfing the internet.

Notes from customer
> after the first apply of batch change when PRs were opened I saw reviewers there. Then I updated PR description and reran the change. There was no change in the logic how change is created so PRs were updated only in description. And after 2nd apply reviewers were removed.

[Report](https://sourcegraph.slack.com/archives/CMMTWQQ49/p1673561370619769)

**Comment by BolajiOlajide** [comment]
A probable solution (which I don't like but is the only way to get around this quickly since bitbucket doesn't look like they'll fix this anytime soon) is to check if reviewers are assigned to a pull request on update, if they are then we make a second API request to assign the reviewers that'll be removed back to the pull request.

Depending on what we come up with I'd say 1d estimate for this.

**Comment by courier-new** [comment]
Let's try to reach out to BitBucket first to see if it's an actual bug that they could fix to get the `reviewers` to be respected in update requests.

If that's not an option, Bolaji's suggestion might be our best option.

**Comment by BolajiOlajide** [comment]
Bitbucket has dropped dedicated support for Starter Licenses. I'll have to ask about this in the community platform.

![CleanShot 2023-03-17 at 20 11 01@2x](https://user-images.githubusercontent.com/25608335/225998069-491584c5-1112-422d-8e7c-81ecd0d3d46c.png)

**Comment by BolajiOlajide** [comment]
I did some digging into community issues relating to this ticket, and so far, this was intentional by Bitbucket. 

> This is totally expected behaviour. Check out [BSERV-9860](https://jira.atlassian.com/browse/BSERV-9860), where one of the Bitbucket Server dev team responded to a similar request.
The tl;dr reason is that default reviewers are suggested, not enforced. Even when creating a PR via the UI, default reviewers can be removed before creating the pull request.

> If you need to include them on PR's created via the API I'd recommend retrieving the default reviewers via [this api](https://developer.atlassian.com/static/rest/bitbucket-server/latest/bitbucket-default-reviewers-rest.html) so you can then include them when creating the PR.

https://community.atlassian.com/t5/Bitbucket-questions/How-to-add-existing-default-reviewers-when-creating-pull-request/qaq-p/627849

We also have to manually add default reviewers [when creating a PR via the API](https://github.com/sourcegraph/sourcegraph/pull/20551), so unfortunately, it seems we'll have to do something similar here in this case.

**Comment by courier-new** [comment]
Got it, thanks for doing that extra digging. That's unfortunate but makes some sense. Let's go ahead with that plan, then. Do you still feel 1d is a good estimate for this?
