### ISSUE TITLE
Use per repo/user concurrency budgets

### ISSUE THREAD

**Issue by sashaostrikov** [sourcegraph/sourcegraph#47023]
Previously, `perms_syncer` used `syncGroups` to control concurrency level per user and repo sync jobs.

We need to implement the same behaviour in new `perms_syncer_worker` which currently uses `NumHandlers` which is a sum of those 2 budgets.

This can be implemented by making `perms_syncer_worker` stateful (adding concurrency budget per sync type), decreasing it in `PreHandle` hook before handling the event and increasing it in `PostHandle` hook.

**Comment by thenamankumar** [comment]
Max concurrency for repo perms syncing is 1 and not configurable. We can also run two separate workers (same code, separate exec) for user and repo perms syncing. 

Restrict repo syncs worker to 1 and integrate numHandlers with `conf.PermissionsSyncUsersMaxConcurrency` for users perms syncs worker.

But I am also curious to see how the solutions proposed above by @sashaostrikov work.

**Comment by sashaostrikov** [comment]
Well, after taking a closer look at how to implement it I found out that it's impossible to distinguish between sync request types (repo/user) at a _pre-dequeue_ step, when we need to decide whether we have enough worker threads to process request or not.

This means that we need to go with splitting the workers as Naman wrote above. However, this also cannot be done without tweaking dequeue database layer logic of the worker itself, which is the first thing I am going to do.
