### ISSUE TITLE
 Packages: list package repos separately from repositories in site-admin

### ISSUE THREAD

**Issue by Strum355** [sourcegraph/sourcegraph#47093]
Currently, package repos are listed alongside repositories at `/site-admin/repositories`.  This shoehorns them into the existing functionality that is not geared towards package repos.

Possible ideas for things to include and surface:
- listing package repos in a separate page (`/site-admin/packages`)
- source of package/package version (referenced by upload, visited by user) 
- collapsible of versions with buttons for common operations on individual versions
  - permanently sync versions
  - blocklist package/package version.

Backend issue: https://github.com/sourcegraph/sourcegraph/issues/46930

**Comment by umpox** [comment]
Started progress on this in https://github.com/sourcegraph/sourcegraph/pull/47464

<img width="1092" alt="image" src="https://user-images.githubusercontent.com/9516420/217588891-dd0a67ff-92cc-4f4a-9818-5713ddff1291.png">

Some initial thoughts/questions, @Strum355:

1. Right now the query relies on passing a `scheme` to return any results. It would be useful if not passing a scheme would return _all_ results
2. `scheme` should be an enum so we can share type safety with the client (I can do this in my PR)
3. `PackageRepoReference.Repository` [can be null](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@tr/site-admin-list-packages/-/blob/cmd/frontend/graphqlbackend/schema.graphql?L3500). Is that correct? My understanding was that _every_ package has an associated repository.
4. We have useful repository analytics. Should we do the same for packages too? I think it would be helpful, especially as admins might not be aware that packages could be taking up a large amount of space. I believe this would need a new query, and we'll need to adjust the old one to not include packages (as well as exclude them in the repo table - assuming you're already on this 😁 )
<img width="963" alt="image" src="https://user-images.githubusercontent.com/9516420/217590396-0799d36a-833f-4bb7-8ddc-a04e01d39d6a.png">
5. I'd be keen to understand more of a typical flow of blocklisting a package or a package version (if you had one in mind when writing this). I think blocking could be done directly from the table, but for specific versions I think we'll probably want some other step. Like a modal, triggered from this page, that allows searching through specific versions of a package and blocking each one. I think we'll also want to allow filtering this table by blocked packages so users can unblock too. Eventually it'd be useful if we have some sorting of versions too!

Hope that's clear, will add more if anything comes up!

**Comment by umpox** [comment]
Also just a heads up, seems like there's an bug with pagination atm: 
https://sourcegraph.sourcegraph.com/api/console#%7B%22query%22%3A%22%7B%5Cn%20%20packageRepoReferences(scheme%3A%20%5C%22npm%5C%22%2C%20first%3A%202%2C%20after%3A%20%5C%22NzMxNQ%3D%3D%5C%22)%20%7B%5Cn%20%20%20%20nodes%20%7B%5Cn%20%20%20%20%20%20id%5Cn%20%20%20%20%20%20name%5Cn%20%20%20%20%7D%5Cn%20%20%20%20totalCount%5Cn%20%20%20%20pageInfo%20%7B%5Cn%20%20%20%20%20%20hasNextPage%5Cn%20%20%20%20%20%20endCursor%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22variables%22%3A%22%22%7D

**Comment by Strum355** [comment]
> 1. Right now the query relies on passing a `scheme` to return any results. It would be useful if not passing a scheme would return _all_ results

Yup thats 100% an oversight

> 2. `scheme` should be an enum so we can share type safety with the client (I can do this in my PR)

Was definitely considering this for the longer term. We already have the external services graphql enum, so this makes sense to do also

> 3. `PackageRepoReference.Repository` [can be null](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@tr/site-admin-list-packages/-/blob/cmd/frontend/graphqlbackend/schema.graphql?L3500). Is that correct? My understanding was that _every_ package has an associated repository.

Thats expected yea. We've no guarantee that any package repo reference will result in a repository due to reasons including them being not resolvable for various reasons

> 4. We have useful repository analytics. Should we do the same for packages too? I think it would be helpful, especially as admins might not be aware that packages could be taking up a large amount of space. I believe this would need a new query, and we'll need to adjust the old one to not include packages (as well as exclude them in the repo table - assuming you're already on this 😁 )

Thats a great point on the existing analytics. Ill discuss this with thorsten (who originally created this afaik) about this

> 5. I'd be keen to understand more of a typical flow of blocklisting a package or a package version (if you had one in mind when writing this). I think blocking could be done directly from the table, but for specific versions I think we'll probably want some other step. Like a modal, triggered from this page, that allows searching through specific versions of a package and blocking each one. I think we'll also want to allow filtering this table by blocked packages so users can unblock too. Eventually it'd be useful if we have some sorting of versions too!

My original thought would be that the external service config (the JSON) would be the "source of truth" for blocked. Users could either block individual packages/package versions or via e.g. glob matching, through either the package repo list page/package repo settings page/external service configuration. The former two would update the JSON of the latter, so there wouldnt be multiple places where something may be blocked. This seemed like the most intuitive and simple approach in terms of site-administration. We read the extsvc config every time we list/sync package repos anyways, as site admins are able to hard-code dependencies to fetch there as well as them being listed in the package repo references table (`lsif_dependency_repos`). I havent thought much on problems this might give in terms of implementation though, but it seems like it should be straight forward. What are your thoughts on this?

**Comment by umpox** [comment]
> Users could either block individual packages/package versions or via e.g. glob matching, through either the package repo list page/package repo settings page/external service configuration. The former two would update the JSON of the latter, so there wouldnt be multiple places where something may be blocked.

This makes sense to me. I think doing it from the package list/package settings page is ideal, as the big json file isn't a great UX. Totally makes sense to have that as a source of truth though.

I threw up a quick wireframe to sketch out what I had in my head. LMK your thoughts and if you think this is something that could work. 

https://app.excalidraw.com/l/4Dr1S6qmmY7/4DS9YPwj2H0
