### ISSUE TITLE
Polish new configuration policy UI

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#47111]
#46449 landed, but needs to address the design feedback from [this Figma file](https://www.figma.com/file/PqRnWEXK9pJPy6T1oxw4nQ/AutoIndex-Configuration-QA?node-id=0%3A1&t=IYRVc4F3ab5idqfo-0).

**Comment by efritz** [comment]
In addition to the Figma feedback we talked about some possible improvements:

- Lots of text/explanation all at once - is there some sort of stepwise/wizard pattern we could adopt (maybe even just for the create/non-edit flow)?
- The "protected" configuration policies should be in a separate table, allowing a more obvious CTA for users setting up indexing when they haven't otherwise configured anything
- Should not allow you to save configurations with warnings about inference limits.

**Comment by scalabilitysolved** [comment]
I keep clicking the configuration policy names to view what's been set up, however the only way to view is via the edit icon which feels a little unintuitive. 

![CleanShot 2023-02-02 at 14 10 43@2x](https://user-images.githubusercontent.com/1309599/216347592-d60a06ce-d823-4a3f-8b5a-6bdc14b21861.png)

**Comment by scalabilitysolved** [comment]
When creating a policy for a single repository, it'd be nice to potentially fill it out with the default previewed value.  i'm not sure I'd often create custom names?

![CleanShot 2023-02-02 at 14 13 54@2x](https://user-images.githubusercontent.com/1309599/216348470-ec72a6d2-3de1-467a-8d02-0553c47c22d7.png)

**Comment by scalabilitysolved** [comment]
When creating a policy that defines an auto-indexing age where we'd ignore commits, if nothing matches we say "1 tag matches this policy but only 0 of them are young enough to be auto-indexed:".  I think it'd be nicer when there are zero matches that qualify to say "1 tag matches this policy and _doesn't_ qualify etc etc"

<img width="1502" alt="CleanShot 2023-02-02 at 14 16 28@2x" src="https://user-images.githubusercontent.com/1309599/216348936-d9fddab9-5855-47c2-aebe-2c79cfbd7afd.png">

**Comment by scalabilitysolved** [comment]
We could improve the wording or link to how it affects the customer experience or whether customer action is needed for the precise indexes view page.

![CleanShot 2023-02-02 at 14 24 22@2x](https://user-images.githubusercontent.com/1309599/216351020-dbc0628e-bfe5-41cc-afb6-65e03150138d.png)

**Comment by scalabilitysolved** [comment]
It could be nice to allow the ability to filter via indexer (I know you can search for it) but I'd be interested in saying 'Show me all states of X for language Y' via a button etc.

<img width="1469" alt="CleanShot 2023-02-02 at 14 26 00@2x" src="https://user-images.githubusercontent.com/1309599/216351228-0f4a7f4b-179e-4cd6-a29a-9bfae95904c4.png">

**Comment by scalabilitysolved** [comment]
Unsure if the replaceable button deletes the index in question and then reindexes that specific commit?

![CleanShot 2023-02-02 at 14 27 39@2x](https://user-images.githubusercontent.com/1309599/216351794-71f6a748-8f56-42d6-8601-92a3c5d728cb.png)

**Comment by scalabilitysolved** [comment]
It can be confusing on the side admin page which policies are default,global/multi-repo or for single repos.  I'm wondering if they need to be split out into distinct sections?


![CleanShot 2023-02-02 at 14 33 19@2x](https://user-images.githubusercontent.com/1309599/216353410-577631b3-3960-41e8-a22f-3e92b5db7ab8.png)

**Comment by umpox** [comment]
> It can be confusing on the side admin page which policies are default,global/multi-repo or for single repos. I'm wondering if they need to be split out into distinct sections?

We can definitely split the default policies into a section (my first thought was that this page feels like it's already been configured for new users). Multi vs single repo could be a good distinction too

**Comment by umpox** [comment]
Have addressed comments and design feedback in https://github.com/sourcegraph/sourcegraph/pull/47416

@scalabilitysolved Will link your comments about the precise indexes page in this issue: https://github.com/sourcegraph/sourcegraph/issues/47262 (so they don't get lost)
