### ISSUE TITLE
Pagination of repositories is slow

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#47200]
This might be related to the new pagination.

See: https://sourcegraph.sourcegraph.com/site-admin/repositories

/cc @sourcegraph/iam

**Comment by mrnugget** [comment]
cc @thenamankumar we just ran into this in planning. doesn't seem to reproduce reliably. Petri is going to take a look

**Comment by thenamankumar** [comment]
I checked on my end but couldn't reproduce it.

**Comment by mrnugget** [comment]
yeah, same here. Closing it again. I think it might've been general DB performance and nothing specific to that page.
