### ISSUE TITLE
4.4.2 Security approval

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#47257]
Security must close this issue before releases. It is the responsibility of the Security Engineer on rotation the week the release is cut. More steps will be added in the future.

- [x] All feasible CVEs are closed.
- [x] Any open CVEs are documented in the handbook.

cc @sourcegraph/security

**Comment by mrnugget** [comment]
@evict can you close/check off the items here?

**Comment by evict** [comment]
https://github.com/sourcegraph/handbook/pull/6125 merged
