### ISSUE TITLE
Requesting patch release 4.4.2 to include "Add expired license restrictions"

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#47254]
@sourcegraph/release-guild I am requesting the following commits be included in a patch release. They are already merged into `main`:

- https://github.com/sourcegraph/sourcegraph/pull/47251/
  - 6cef2a139e376ee617024024e6e90e1ae8cebcd4

---

The intent of the questions below is to ensure we keep Sourcegraph high quality and [only create patch releases based on a strict criteria.](https://handbook.sourcegraph.com/engineering/releases#patch-releases) If you can answer yes to many or most of these questions, we will be happy to create the patch release.

I have read [when and why we perform patch releases](https://handbook.sourcegraph.com/engineering/releases#patch-releases) and answer the questions as follows:

> Are users/customers actively asking us for these changes and cannot wait until the next full release?

It's not customers that are asking us for this release, but Sales and CEO to help a customer. See [this Google Doc](https://docs.google.com/document/d/1yTLt8EytY_mgeRxZm-MFt__n9eUrkLy4WdBfKfS9g8Q/edit#heading=h.dx5upmy7urf0) and the Slack threads linked in it for more details.

> Are the changes extremely minimal, well-tested, and low risk such that not testing as we do in a full release is OK?

Yes, see the Loom in PR https://github.com/sourcegraph/sourcegraph/pull/47251/

> Is there some functionality completely broken that warrants redacting the prior release of Sourcegraph and advising users wait for the patch release?

No, but we had a loophole in our license expiration that allows users to circumvent all restrictions by updating all users to admins.

> This will interrupt our regular planned work and release cycle, taking one full working day of our time, and will take up all of our site admin's valuable time by asking them to upgrade or producing noise for them if they don't need to upgrade.
>
> Do you believe the changes are important enough to warrant this?

Yes

> Patch releases are a signal we can do something better to improve the quality of Sourcegraph. Have you already scheduled a call (or created a google doc) to perform a [retrospective](https://about.sourcegraph.com/retrospectives) and identify ways we can improve?

No

---

**For the [Release Captain]** - after reviewing this request:

- [x] **Comment on this issue** with a decision regarding the request.
- [x] If you are a first-time [Release Captain], please review the high-level overview of the [patch release process].
- [x] If approved, **add it to a patch release**:
  - If there is [already an upcoming patch release](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+), add the listed commits alongside a link to this issue.
  - If there is no upcoming patch release, create a new one:
    - [x] Update [`dev/release/release-config.jsonc`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/dev/release/release-config.jsonc), open and merge a PR to `main` to update it.
      - [x] Change `upcomingRelease` to the current patch release
      - [x] Change `previousRelease` to the previous patch release version
      - [x] Change `releaseDate` to the current date (time is optional) along with `oneWorkingDayAfterRelease` and `threeWorkingDaysBeforeRelease`
      - [x] Change `captainSlackUsername` and `captainGitHubUsername` to the patch captain's
      - https://github.com/sourcegraph/sourcegraph/pull/47255
    - [x] Run `pnpm release tracking:issues` on `main`
    - [ ] Add the listed commits alongside a link to this issue to the generated [release tracking issue](https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aissue+label%3Arelease-tracking+)
- [ ] **Comment and close this issue once the relevant commit(s) have been cherry-picked into the release branch**.

[release captain]: https://handbook.sourcegraph.com/engineering/releases#release-captain
[patch release process]: https://handbook.sourcegraph.com/departments/product-engineering/engineering/process/releases#patch-release-process

**Comment by BolajiOlajide** [comment]
Approved.

**Comment by unknwon** [comment]
@mrnugget - asking on behalf of the @sourcegraph/cloud team, how critical do you think it is for current Cloud customers? Or can Cloud customers wait until 4.5?

**Comment by mrnugget** [comment]
I don't think it's critical for every customer, since it was mainly built for 1-2 specific customers. But it does change how license expiration works. If you have customers whose license expires soon, I'd update.
