### ISSUE TITLE
 Polish new precise indexes UI

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#47262]
#46692 landed, but needs to address any design feedback.

**Comment by efritz** [comment]
We talked about some possible improvements:

- Pre-index/index steps are not visible outside of the timeline. This is essentially the configuration of the index job and should be displayed regardless of execution status.
- Timeline view is very dense and the collapsible doesn't have good discovery for interaction. FYI - components shared with batch changes.

**Comment by eseliger** [comment]
The "custom inference config" UI is unclear to me - how do I stop using a custom configuration? It does allow me to delete the whole content and hit save, but does that mean it doesn't use a custom config anymore, or that it stored a `""` now and I don't get auto indexing anymore at all? 
We should instead not show an empty editor but a banner "use your custom config" or so, and once clicked show the editor. If a config is present, there should be a third button "Remove configuration" that will delete it and go back to the banner state.

**Comment by umpox** [comment]
More feedback:
- https://github.com/sourcegraph/sourcegraph/issues/47111#issuecomment-1413834890
- https://github.com/sourcegraph/sourcegraph/issues/47111#issuecomment-1413833010
- https://github.com/sourcegraph/sourcegraph/issues/47111#issuecomment-1413830569
- https://github.com/sourcegraph/sourcegraph/issues/47111#issuecomment-1413828357

**Comment by umpox** [comment]
Closing, other work continued through https://github.com/sourcegraph/sourcegraph/issues/47550 and https://github.com/sourcegraph/sourcegraph/issues/47647!
