### ISSUE TITLE
For ownership queries the UI should display File matches owner.

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#47282]

**Comment by cbart** [comment]
![Image](https://user-images.githubusercontent.com/153410/216108654-5a837000-c6b2-42e3-b8c5-d99c0aeaf0b0.png)

**Comment by cbart** [comment]
@eseliger, I guess we need to analyze the search query here right? What if the search has both contents query and ownership query? 

Should we generally say something like file matches query instead?

Should we only say file matches owner if there is just `f:has.owner(..)` but no contents predicates?

**Comment by eseliger** [comment]
Rethinking this, I think the wording actually makes sense. It is a file with matching content, the ownership thing is just reducing the result set, nothing else.

so 

`r:sourcegraph SuperAwesome f:has.owner(erik)` would still be a match for SuperAwesome, and a file that is owned by erik. 

Do people agree with that in general?

**Comment by limitedmage** [comment]
@eseliger  In your example, the search result will render the code except:

![image](https://user-images.githubusercontent.com/206864/222856768-1c2584e2-ad55-4ab6-8151-193fd6dc6f99.png)

**Comment by limitedmage** [comment]
The ambiguous case is when you have both `file:has.owner` and `file:has.content` in the same query.

**Comment by eseliger** [comment]
Ah I see now, thanks for clarifying!

**Comment by cbart** [comment]
I'm going to resolve this as I think this works as intended at this point.
