### ISSUE TITLE
Do not use fmt.Sprintf to construct sql query

### ISSUE THREAD

**Issue by thenamankumar** [sourcegraph/sourcegraph#47363]
Possible SQL injection. 

https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/database/helpers.go

/cc @sourcegraph/source

**Comment by mrnugget** [comment]
Started hacking a bit on this here: https://github.com/sourcegraph/sourcegraph/pull/47361

I think we need to remove `*string` with a `*int` or a `struct`. What I did in my PR was to add another field for the case when there are two order columns and two before/after values.

We could also just use `[]any` here and then the stores themselves need to cast back if they need to `+= 1` the cursors (which some of them do)

**Comment by eseliger** [comment]
fixed.
