### ISSUE TITLE
gRPC: migrate gitserver.CommitExists

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#47422]

**Comment by hg6658** [comment]
I am new contributing can you give me brief context about the issue. overview how to solve it and assign me this?

**Comment by eseliger** [comment]
Closing this in favor of our other tickets that cover this.

Sorry @hg6658 for not seeing your comment earlier and thanks for your interest in this ticket, we found a different pattern for this for now.
