### ISSUE TITLE
Merge "planning collaboration doc" back to PR-FAQ doc

### ISSUE THREAD

**Issue by erzhtor** [sourcegraph/sourcegraph#47448]
Merge back [planning collaboration doc](https://docs.google.com/document/d/1j2SEgmvOCgwBPPBggIbYVuXxyAD46i6PGSRbMwgHVAk/edit#heading=h.f0c84zc5h9nt) back to [[PR-FAQ] View-only for (internal) virality](https://docs.google.com/document/d/1R56eegMahlFBiz1RHh0Y9uFZuuQ_T__LHKCaRErHky0/edit#heading=h.ci9cwbeq5v1o)

**Comment by meglynst** [comment]
@erzhtor I've merged the two docs. I'll move this to closed but feel free to leave comments on the official PRFAQ doc. I didn't edi t anything in the doc that you created.
