### ISSUE TITLE
Error when creating search context

### ISSUE THREAD

**Issue by dwssef** [sourcegraph/sourcegraph#47509]
#### Question description

I encountered an issue while creating a search context, could you please provide a solution?
![image](https://user-images.githubusercontent.com/39583993/218059678-7d23548f-1593-4d25-b5a7-9959624e1073.png)

**Comment by DaedalusG** [comment]
Hey @dwssef I was able to reproduce this and have opened a new issue on it: https://github.com/sourcegraph/sourcegraph/issues/50185

Thanks for reporting!
