### ISSUE TITLE
"Test Connection" button provides no feedback when failing in certain conditions

### ISSUE THREAD

**Issue by jasonhawkharris** [sourcegraph/sourcegraph#47522]
- **Sourcegraph version:** 4.4.2
- **Platform information:**  All platforms

#### Steps to reproduce:
1. Spin up an instance with woefully under-provisioned `redis` containers
2. Turn on `outboundRequestLogLimit` set to `5`
3. Send a ton of requests to throttle the `redis` containers
4. Press the 'test connection' button in the code host settings UI

#### Expected behavior:
1. A message of success below the 'test connection' button in the code host settings UI OR,
2. An error message and new or no tooltip indicating a malfunction.

#### Actual behavior:
1. A grayed-out button.
3. A cursor with a "no" symbol. 
4. No error message indicating why the button isn't working
5. An unchanged tooltip

<img width="423" alt="Screenshot 2023-02-11 at 7 47 11 AM" src="https://user-images.githubusercontent.com/62355966/218271409-da8948a3-ddbe-4ee8-9312-ce62f226384b.png">

**Comment by kopancek** [comment]
The [PR with a fix](https://github.com/sourcegraph/sourcegraph/pull/47539) has been merged, but I'm leaving this open in case you want to do some further work
