### ISSUE TITLE
"View file prior to this change" link takes to the "File not found" page

### ISSUE THREAD

**Issue by taras-yemets** [sourcegraph/sourcegraph#47558]
- **Sourcegraph version:**  4.4.2
- **Platform information:** 
- Reported in [this thread](https://sourcegraph.slack.com/archives/C03CSAER9LK/p1676100990842119)

The "View blame prior to this change" link in the git blame popover doesn't work if the file has been added or renamed in the current revision because we assume it had the same name in the previous one.

![screenshot_2023-02-11_08 34 46](https://user-images.githubusercontent.com/25318659/218505324-9451c1be-28a1-4f72-96d9-820bfd54f10c.gif)

#### Steps to reproduce:

1. On your Sourcegraph instance, open a file and turn on the blame decorations.
2. Hover over the decoration which "View file prior this change" link points to a revision in which this file didn't exist or was named differently (e.g. [cmd/gitserver/server/vcs_syncer_git.go?L117:6](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@391eba82580948595a0cd58a3ca4ad6cbc4fa61c/-/blob/cmd/gitserver/server/vcs_syncer_git.go?L117:6)).
3. Click "View file prior this change" link.

#### Expected behavior:
The link is inactive or not rendered at all if the file didn't exist (with this name) in the previous revision.

#### Actual behavior:
The link takes us to the "File not found page".

If you would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are no [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

**Comment by taras-yemets** [comment]
As a workaround, we can check whether the file exists in the requested revision either when the blame popover is rendered or when the “View blame prior to this change” link is clicked: intercept => loading => “file doesn’t exist” message or navigate to URL (similar to what we do when Cmd+Click on occurrence to go to definition).


<img width="1201" alt="Screenshot 2023-02-13 at 17 11 38" src="https://user-images.githubusercontent.com/25318659/218508169-a16cf22f-d3b3-41a2-914d-4679737f68a7.png">
<img width="1201" alt="Screenshot 2023-02-13 at 17 10 31" src="https://user-images.githubusercontent.com/25318659/218508179-f0632e9f-0c5a-4ada-80d4-c30a4919b155.png">

**Comment by pjlast** [comment]
Closing since we're tracking this here: https://github.com/sourcegraph/sourcegraph/issues/60159

With a fix inbound.

**Comment by fkling** [comment]
It seems we are not rendering the link anymore.
