### ISSUE TITLE
Update Code Insights page

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#47569]
This is related to [UX: Messaging/Feedback in App](https://github.com/sourcegraph/sourcegraph/issues/48273). 

# Initial screen
When you first navigate to Insights, you see this warning. It's confusing because nothing has "expired" and a user doesn't need to contact an admin to upgrade their license. 

![Image](https://user-images.githubusercontent.com/43555476/218538437-48f8773f-f2fb-4f1e-909f-5479094e764b.png)

# Insights page
On the Insights page, there should be a notice that Code Insights might be limited in the future. Designs are [here](https://www.figma.com/file/tbM21yr4k9gJNKkjNc0a4m/UX%3A-Messaging%2FFeedback-in-App?node-id=3%3A610&t=kHc5u9zhLqUYl8sD-0). 

# Insights page - Add dashboard button
When you click the "Add dashboard button," you should see the "Limited Access" warning with copy that says, "Dashboards aren't available yet for the Sourcegraph app. Start a Cloud trial to create unlimited insights and dashboards." 

# Insights page - Create insight
Users will only be able to create two insights as unauth'd app users. Right now, a user that's created two insights can still click the "Create insight" button, complete all the steps to create an insight, but then the "Create code insight" button is disabled. We should add messaging that suggests they remove an insight if they'd like to create a new one, or they sign up for a Cloud trial to create unlimited insights and dashboards. 

# Insights page - Dashboards tab
On the Dashboards tab of the Insights page, we should rethink the two "Limited Access" mentions here. It might be overkill with the warning that we're adding to the top, and we're not supporting dashboards yet in app: 
<img width="423" alt="Screen Shot 2023-02-28 at 5 05 44 PM" src="https://user-images.githubusercontent.com/43555476/222011403-42c5fd24-70d5-45c6-bcba-90eff3ce9803.png">

# Insights - Getting started tab
- The "see more use cases," "documentation," and "some of the most popular use cases" links are broken

# Insights/create
- The "learn more about the use cases" link at the bottom is broken.

**Comment by taylorsperry** [comment]
Tagging you here, @almeidapaulooliveira because I think we need some design input on this one 😄

**Comment by philipp-spiess** [comment]
@marekweb / @slimsag / @vovakulikov Do you folks know how I can best set up my dev instance to match the feature flags/license that will be enabled on a production release? Right now, `sg start app` won't include code insights at all and when I add `DISABLE_CODE_INSIGHTS: false` in the config, I am not seeing the screen that @taylorsperry posed above.

**Comment by marekweb** [comment]
Good point @philipp-spiess, there's a discrepancy with how it runs in dev, I'm not sure what the right flag/license is

**Comment by taylorsperry** [comment]
Asking [here](https://sourcegraph.slack.com/archives/C04F9E7GUDP/p1678211764553739)!

**Comment by vovakulikov** [comment]
@philipp-spiess I think you should 
- Generate an enterprise license that doesn't include a code insights tag (I think just an enterprise plan will fit in this case) 
- Put this license tag in your dev-private directory external site configuration 
- Run `sg start enterprise-codeinsights` in the terminal 

Let me know if you still won't be able to see this state

**Comment by almeidapaulooliveira** [comment]
> On the Dashboards tab of the Insights page, we should rethink the two "Limited Access" mentions here. It might be overkill with the warning that we're adding to the top, and we're not supporting dashboards yet in the app:

Agree; I think we should not display those warnings and only rely on the main banner in the page header.

**Comment by almeidapaulooliveira** [comment]
> complete all the steps to create an insight, but the "Create code insight" button is disabled. 

We should disable all steps. It could be frustrating for the user to fill out a task and then discover that it can't be completed at the end.
