### ISSUE TITLE
User research surveys

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#47564]
@meglynst is [conducting two surveys](https://sourcegraph.slack.com/archives/C04F9E7GUDP/p1675946551602429) to better understand the pain points around Cloud Trials (so that we can mitigate them in App) and expectations/incentives for users who are interested in App (so that we can begin to prioritize our roadmap in a way that's informed by data). Those surveys will go out the week of February 13 and we hope to have feedback by the end of the following week (February 20). 

See results:
[Sourcegraph App Typeform results](https://sourcegraph.typeform.com/report/JRGsBnUk/B9fsfyINHpjmdBJV)
[Sourcegraph App raw results](https://docs.google.com/spreadsheets/d/1sOR6QKDV_Re7J3plzUtctKcMjVJ8aXcKj-zJd6Bvo_A/edit?usp=sharing)
[Cloud Trial Typeform results](https://sourcegraph.typeform.com/report/nRUtopch/0yMNtyfe7ns2Uabj)

**Comment by meglynst** [comment]
Sourcegraph App results:

We didn't receive enough results to have any sort of statistical significance on the quantitative questions we asked for Sourcegraph App. However, both quantitative and qualitative results point to code navigation issues as the most salient problem in a dev's workflow as well as what they hope Sourcegraph App would improve upon compared to their current code search tool(s).

Some representative quotes that reflect the above emphasis on better code navigation/exploration:

> This respondent rated their current code search solution a 5/10: "I primarily use vscode and linux commandline for code search, based on filenames etc, can't find link to dependencies or headerfiles as usage of vscode extensions are restricted in our company, being a bank as security measures. How a particular code block links to others is and its impact on making a code change is hard to find, wastes dev time as well"

> On why they would download and try Sourcegraph App: "...I want powerful exploration capabilities...The most interesting concept to me is backtrace at any given point. How did we come to a given line of code (all possible options, ranged by some heuristic if there are many). Where can we go from here. I am inspired also by how fuzzing works -- we explore the possible parameters to a function and see where we get in terms of code path depending on the parameters we pass to functions."

> On why they would download and try Sourcegraph App: "I recently took over maintenance of a large-ish open source project. Most of the codebase is unfamiliar to me, and so most of my time is 'finding my way around' someone else's source code, and figuring out how it works, and any side-effects of changes I make."

Want to look at the results for the Sourcegraph App survey? Here's the [report in Typeform](https://sourcegraph.typeform.com/report/JRGsBnUk/B9fsfyINHpjmdBJV) and here is the [raw data in Google sheets](https://docs.google.com/spreadsheets/d/1sOR6QKDV_Re7J3plzUtctKcMjVJ8aXcKj-zJd6Bvo_A/edit?usp=sharing).

**Comment by meglynst** [comment]
Cloud Trial results:

The results for the Cloud Trial survey were small (only one response), which we expected based on past outreach efforts by product and CE team. You can view the results [here](https://sourcegraph.typeform.com/report/nRUtopch/0yMNtyfe7ns2Uabj).

Good things:

- The user rated Sourcegraph an 8 / 10 after using their Cloud Trial.


Not so good things:

- The user rated their set-up experience a 3 / 10. The very first thing they asked to be fixed for the Cloud Trial was the set up experience.
- Had difficulties purchasing licenses.
