### ISSUE TITLE
Sentry Extension V2

### ISSUE THREAD

**Issue by vanesa** [sourcegraph/sourcegraph#4756]
#### Feature request description

Currently, the Sentry extension does not communicate with the Sentry API. Instead, the extension renders links to Sentry by matching error logging code patterns presented in the file and taking the user's configurations into account. This can lead to erroneous project matching, especially if a file sends logs to multiple projects. 
For v2 of the extension we want to use the Sentry API to increase the matching accuracy between the lines of code producing the error logs and the corresponding Sentry issue pages.

#### Plan (WIP)

- [x] Setup connection with Sentry API using Auth token provided by the user in the extension settings, proxying through `cors anywhere`.
    - [x] Add Sentry.io url prefix to the `cors anywhere` whitelist. https://github.com/sourcegraph/deploy-sourcegraph-dot-com/pull/1116
    - [x] Enable passing headers (without host) as options. https://github.com/sourcegraph/infrastructure/pull/1568
    - [x] Build and push the new version of the cors image to docker hub
    - [x] Extend cors anywhere to respond to `OPTIONS`. 
- [ ] As a first step to improve project matching: 
    - [ ] Only render existing issues
    - [ ]  Retrieve projects from Sentry and offer auto-complete in settings to map projects with file paths/repos.
    - [ ] Optional: Retrieve projects from Sentry, iterate through projects to match error logging code with issue title.
- [ ] Render issues count number next to the Sentry link.
Concern: Depending on how many projects and issues exist, this could lead to performance issues.

**Comment by felixfbecker** [comment]
Note we don't currently have versioning support for extensions. I would recommend using a feature flag instead (setting a token can act as a feature flag too, i.e. progressive enhancement).

**Comment by keegancsmith** [comment]
Vanesa is currently out sick, so assuming work will continue on this and bumping to the next milestone.

**Comment by lguychard** [comment]
Closing this as no further work on the Sentry extension is currently planned.
