### ISSUE TITLE
Ability to configure default fork handling mode

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#4757]
In some organizations, it is desirable for searching over forks is the exception and not the rule. i.e.:

- today: `fork:yes` is the default, users must write `fork:no` to opt-out of fork searching.
- proposed: a global/org/user option to change the default to `fork:no` so that users must write `fork:yes` to opt-in to fork searching.

Reported by a user at https://app.hubspot.com/contacts/2762526/company/407948923 but likely to affect more users in the future.

**Comment by rvantonder** [comment]
@tsenart added this for GH in #8974. Should we close or keep this open to track progress for other code hosts (probably want to update the title in that case).

**Comment by rvantonder** [comment]
@slimsag forks are now excluded by default and need `fork:yes` to opt in. Can we close this or is there remaining work?
