### ISSUE TITLE
Clicking clone now should bump the prirority of a repo to the top of the queue

### ISSUE THREAD

**Issue by indradhanush** [sourcegraph/sourcegraph#47590]
This is supposed to be expected behaviour but it appears we don't do this anymore. 

As a start:

- [ ] Investigate the current behaviour
  - We call the enqueue repo update code [here](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/app/ui/handlers.go?L232-239&subtree=true)
- [ ] Also verify if the reclone button has this issue 

### Artifacts

- [Relevant slack thread](https://sourcegraph.slack.com/archives/C04MYS7SZPT/p1675414378946509).

/cc @ryphil

**Comment by mrnugget** [comment]
I looked into this. It still works as it did before.

You can trigger a bump when you visit the repo page. The only "problem" is that it only works when you hard-reload the page. That's the only way to trigger the backend code.

"Clone now" button uses a GraphQL mutation and that bumps the repository.
