### ISSUE TITLE
insights: write sales enablement documents for the new repo UI

### ISSUE THREAD

**Issue by leonore** [sourcegraph/sourcegraph#47613]
it would be a shame if we made all those improvements for code insights and sales didn't know how to pitch it. connect with some CEs and see how we can help them.

/cc @felixfbecker @vovakulikov

**Comment by chwarwick** [comment]
@leonore  I remember you mentioned making a loom about this, I wanted to check to see if you had done that if not I can tomorrow.   I already went though the GTM docs and made updates to the out of date content.

**Comment by leonore** [comment]
nope, thanks for volunteering 👍 happy to do it too though

**Comment by chwarwick** [comment]
I went though and updated the GTM docs in google drive.  Most were still very relevant despite being a year old, only a few minor edits on things like limitations on some/all repos.
