### ISSUE TITLE
insights: write a manual test plan for rctest

### ISSUE THREAD

**Issue by leonore** [sourcegraph/sourcegraph#47614]
for 4.5 release (shipping repo ui, retention)

/cc @felixfbecker @vovakulikov

**Comment by leonore** [comment]
for data retention/exporting:

* [] make sure exporting is available on both the insight card and the standalone view
* [] make sure docs linking works
* [] test export on a search insight
* [] test export on a capture group insight
* [] test export on a compute insight
* [] test export on an insight that has archived values
* [] test with default repo filters
* [] test # of samples filtering and saving them works
* [] test permissions are validated

**Comment by leonore** [comment]
@vovakulikov it looks like we no longer have the overlay message for the export data as CSV button on the standalone insight page

**Comment by vovakulikov** [comment]
@leonore oh, this is true, it seems like there was a problem with tooltip, here is a fix for it https://github.com/sourcegraph/sourcegraph/pull/48198

**Comment by chwarwick** [comment]
I ran a set of tests on rctest to more of a quick smoke test:

1. Create an insight over 2 repos

```
repo:^github\.com/sourcegraph/about$ or repo:^github\.com/sourcegraph/handbook$ 
Search - insights
```

2. Filter insight by each repo and validate values against current search results
3. Click the most recent -1 data point to generate the diff search 
    - remove 1 repo, type:diff and search pattern
    - use results to find the revision the point is associated with 
4. Using revision from step 3 run a historic search against that revision and validate result count
5. Export insight data
6. Validate the exported data matches the chart
