### ISSUE TITLE
search aggregations are not autodetecting the correct mode

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#47707]
Some search aggregations are not detecting the correct mode, causing a confusing UX.

Example 1:
https://sourcegraph.sourcegraph.com/search?q=context%3Aglobal+file%3Adev%2Fsg++%2Foutput%5C.%28%3F%3AStyleWarning%29%2F&patternType=regexp&case=yes&sm=0&groupBy=repo

Example 2 (clicking on capture group bar with no more capturing groups in the query)
https://sourcegraph.sourcegraph.com/search?q=context:global+/output%5C.%28%3F:StyleWarning%29/&patternType=regexp&case=yes&sm=0&groupBy=group&expanded=

**Comment by chwarwick** [comment]
closed by https://github.com/sourcegraph/sourcegraph/pull/47719
