### ISSUE TITLE
Code intel precise indexes: Support filtering by indexer

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#47723]
It is currently possible to do this through the "Search precise indexes" input, but it isn't obvious or quick.

It would be useful if there was a way to filter by indexer. I found myself looking for this option a few times when trying to figure out why I was having `scip-typescript` issues.

(Low priority)

## Example:

<img width="934" alt="image" src="https://user-images.githubusercontent.com/9516420/219312400-21201985-f167-4c17-912b-9896fd0626f1.png">

**Comment by efritz** [comment]
@umpox Do you also need a list of available indexers to populate the list?
