### ISSUE TITLE
upgrade to git > 2.39.1

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#47762]
https://github.blog/2023-02-14-git-security-vulnerabilities-announced-3/

**Comment by coury-clark** [comment]
@keegancsmith is this getting added to 4.5.0?

**Comment by keegancsmith** [comment]
Fixed by #47892, @coury-clark I am guessing will need cherry-picking?

**Comment by keegancsmith** [comment]
@coury-clark I thought this would of made it in due to the release-blocker label. But I just double checked, I don't see the relevant commit in our release. https://github.com/sourcegraph/sourcegraph/commits/v4.5.0

**Comment by coury-clark** [comment]
@keegancsmith yikes, it seems we only check blocker labels during cut, and I didn't include this in the release. I'll follow up with security team to decide what to do here

**Comment by coury-clark** [comment]
Released in v4.5.1
