### ISSUE TITLE
SEARCHER_URL, SYMBOLS_URL should allow specifying comma separated list

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#478]
Currently, `SEARCHER_URL` may only specify multiple values by using the `k8s+` syntax which utilizes Kubernetes service discovery (effectively).

In non-Kubernetes data center deployments, such as a pure-docker one, we need to be able to specify multiple via the environment variable. e.g.:

```
SEARCHER_URL=http://searcher-0:3181,http://searcher-1:3181,http://searcher-2:3181
```

https://github.com/sourcegraph/sourcegraph/blob/3d3ffe9c2a975b4dd2e623bfa16bb29d3c6ecde9/cmd/frontend/graphqlbackend/textsearch.go#L931

The same must be fixed for SYMBOLS_URL:

https://github.com/sourcegraph/sourcegraph/blob/3d3ffe9c2a975b4dd2e623bfa16bb29d3c6ecde9/pkg/symbols/client.go#L26

**Comment by nicksnyder** [comment]
In other contexts that specify a list (e.g. [SRC_GIT_SERVERS](https://sourcegraph.sgdev.org/search?q=SRC_GIT_SERVERS+count%3A1000)) we use a space separated list instead of comma separated list.

**Comment by slimsag** [comment]
Odd, but okay, sounds good from a consistency POV.
