### ISSUE TITLE
Support selections on Bitbucket code host single file source views

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#4787]
#### Steps to reproduce:

1. Activate the git-extras extension
2. Visit a Bitbucket single file code view with the native integration or browser extension activated
3. Select some lines in the code view

#### Expected behavior:

Git blame decorations are displayed

#### Actual behavior:

Git blame decorations are not displayed:

![image](https://user-images.githubusercontent.com/1741180/60578158-0747d180-9d81-11e9-8547-1bb55fbafe62.png)

This is because Bitbucket's `singleFileSourceCodeView` doesn't implement `getSelections()` or `observeSelections()`.

**Comment by ryankscott** [comment]
We are no longer going to support the git-extras extension.
