### ISSUE TITLE
Remove banners (email.smtp warning, etc.)

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#47906]
Let's remove these banners from the home screen on App. Connecting a code host will be handled by the setup wizard; SMTP isn't relevant to App MVP; and we need to sort out messaging for updates. 

![Image](https://user-images.githubusercontent.com/43555476/220169759-bc8acf42-d1ae-4662-a6d4-aa8420a051ae.png)

**Comment by taylorsperry** [comment]
This should also address [this issue](https://github.com/sourcegraph/sourcegraph/issues/47586).

**Comment by slimsag** [comment]
We just need to add an `if` statement on the `DEPLOY_TYPE` in this file for any alerts we do not want showing (probably most of them):

https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/site_alerts.go?subtree=true
