### ISSUE TITLE
app: Modify telemetry to be very limited by default until account connected

### ISSUE THREAD

**Issue by marekweb** [sourcegraph/sourcegraph#47912]
- ~~Turn telemetry that captures in-app usage off by default~~ (No longer the current plan)
- Modify telemetry to be very limited for unauth'd users
- Turn telemetry that captures in-app usage on when the user connects an account

**Comment by taylorsperry** [comment]
Not "off" but very, very limited for unauth'd users. See [here](https://docs.google.com/document/d/1eExgjFeMdzwBR8fYVBMlHgJaOCfbHHcJvfiLcuNrumg/edit?disco=AAAAqsTJGpc).

**Comment by marekweb** [comment]
Updated the title and description to reflect the new plan.

**Comment by marekweb** [comment]
Completed in #48962
