### ISSUE TITLE
highlightMatches calls ToLower, may be a bug

### ISSUE THREAD

**Issue by ijt** [sourcegraph/sourcegraph#4791]
See https://github.com/sourcegraph/sourcegraph/pull/4680#discussion_r299811837.

**Comment by ijt** [comment]
I tried `case:yes func Main` but didn't see any problem in the highlighting of the results. Closing this since we currently have no evidence of a real problem.

**Comment by slimsag** [comment]
An easy way to reproduce this is with Turkish, where:

> the lowercase letter 'i' maps to an uppercase dotted I (U+0130 LATIN CAPITAL LETTER I WITH DOT ABOVE), while the uppercase letter 'I' maps to the dotless lowercase i (U+0131).

Searching for U+0130 in the following repository produces all sorts of strange results in the highlighting. The following should only show matches on line 5:

- https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/slimsag/yayunicode%24+%C4%B0
- https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/slimsag/yayunicode%24+%C4%B0%C4%B0
- https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/slimsag/yayunicode%24+%C4%B0%C4%B0%C4%B0

This is likely to happen with any uses of Unicode where there are combining characters in use.
