### ISSUE TITLE
Moving to Wolfi distroless images will require a p4-fusion rebuild

### ISSUE THREAD

**Issue by twarit-waikar** [sourcegraph/sourcegraph#47936]
Requested by: https://github.com/sourcegraph/accounts/issues/6716

#### Feature request description

Since Wolfi images are expected to use the glibc C library instead of musl like alpine does, p4-fusion will need to be rebuilt so that it can be executed properly and can run under the new distroless Sourcegraph images based on Wolfi.

#### Is your feature request related to a problem? If so, please describe.

p4-fusion currently has a problem which only occurs when it is run under alpine, where the tool was a rare tendency to crash at the end of the computation or right at the start of the Perforce to Git conversion.

The reason for this is unknown but it has only been observed in alpine which uses the musl C library. p4-fusion doesn't show this problem when built with anything other than that.

**Comment by willdollman** [comment]
Hi @twarit-waikar - thanks for the issue! I'm leading the work to migrate to Wolfi.

This work is actually already complete! As part of the move to Wolfi I'm replacing our existing build scripts (like `p4-fusion-install-alpine.sh`) by adopting [melange](https://github.com/chainguard-dev/melange) to build and package our dependencies as Alpine packages.

The melange config for building p4-fusion [can be found here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/wolfi-packages/p4-fusion.yaml?subtree=true); the sandbox build environment is Wolfi-based, so results in a glibc-based build 🎉  

Packaging p4-fusion also makes it a lot simpler to import into our images - [this line of config](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/wolfi-images/gitserver.yaml?L31) imports the packaged binary into the Wolfi image from our Sourcegraph package repo.

**Comment by twarit-waikar** [comment]
Sounds great!
