### ISSUE TITLE
Setup Wizard: Add minimal set of telemetry to the new wizard UI

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#47974]
Basically we need to figure out what kind of events we want to have in the new wizard, not fully list of events off the top of your head

- is there any local repositories setup (how many), probably this ping should live on the backend since there is different options to setup local repos
- Clicks for the local repositories setup UI (by this, we will track percentage of the local repositories UI usage, maybe all users will use just terminal version)
- Clicks on code host type (what is the most popular code host, this will help to understand on which code host type form UI we should focus after GitHub connection UI) 
- How many code hosts users connect on the second step? 
- Do they use edit UI there? Or it's just connect, go to the next step 
- Did they finish the setup, or they abanded it without full completion, on which step they left (this might be tricky because we have to track tab close event, and there is no good API for it at the moment)

**Comment by ryphil** [comment]
From my perspective, here is what we want to find (some are similar to above, just all phrased in the form of a question): 

- What % of users complete the setup experience with code successfully synced? 
- What stages of the setup experience create the most dropoff? 
- What % of users connect a GitHub code host? BitBucket? For all code hosts supported.... 
- What errors are users most commonly receiving during the setup process? 
- 

I do not know which ones will be easy or possible due to the limited abilities we have to gather data, but I wanted to leave this comment here for completeness.

**Comment by vovakulikov** [comment]
A few tech thoughts on Ryan's points
> - What stages of the setup experience create the most dropoff?

How do you define dropoff? Like closing the page (browser tab)? I think there is now a good solution for pings like this in our codebase. 

 
> - How long does it take for a developer from start to full setup (maybe use first-search as a proxy for full setup)?

We can say that the moment you see the wizard for the first time, it's your start time, and the first search it's your due time, so subtraction it will be this time, just want to call it out that we don't track durations in other places so it may take a while to do this properly (I will try to include this in the March release, but want to mark this as risky) 

All other actions are feasible 
cc @ryphil

**Comment by almeidapaulooliveira** [comment]
I drafted the first version of the [metrics events](https://www.figma.com/file/EuRdjjQF8a9kRJMRce4HyI/UX%3A-Instance-setup-experience?node-id=1691%3A15532) for the wizard. On the page, I outlined the [desired dashboard outcome](https://www.figma.com/file/EuRdjjQF8a9kRJMRce4HyI/UX%3A-Instance-setup-experience?node-id=1819%3A19103&t=0MtzTLjt3hXZVCY9-4) that combining these events would produce and answer most questions we raised. To set up Amplitude dashboards, we only need to collect these events generically without requiring specific development.

For example, we can use Amplitude's [time-to-convert](https://help.amplitude.com/hc/en-us/articles/360053338671-Interpret-your-funnel-analysis#h_9d8fe3f6-4d0b-4725-85ef-1c20d9014799) feature to measure the time between the first and last event to answer questions like "How long does it take for a developer to be fully set up from the start?".

Additionally, Amplitude's ['show user paths'](https://help.amplitude.com/hc/en-us/articles/236032527#show-user-paths) feature allows us to analyze drop-off by different events, including when the page is closed, to answer the question, "What stages of the setup experience create the most drop-off?".

Please review the [metrics page](https://www.figma.com/file/EuRdjjQF8a9kRJMRce4HyI/UX%3A-Instance-setup-experience?node-id=1691%3A15532); if you have any doubts, I'm happy to discuss them.
