### ISSUE TITLE
Ownership API: File resolvers

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#47980]
Left over after #48056 merges:

- [x] respect pagination in `ownershipConnectionResolver` #48788
- [x] enrich ownership description with matched rule and line numbers https://github.com/sourcegraph/sourcegraph/pull/49037
- [x] implement team matchers https://github.com/sourcegraph/sourcegraph/pull/49022
- [ ] nit: rework ownership API so that it returns resolved owners

**Comment by eseliger** [comment]
If we return the file and the line numbers, we also need to handle that in the frontend and add a link
