### ISSUE TITLE
Check connection via user provided token

### ISSUE THREAD

**Issue by gl-srgr** [sourcegraph/sourcegraph#47982]
`CheckConnection()` currently uses the existing external service to check connection. However, for setup wizard we complete some requests for code host that is not added yet to external service store. 

Provide a way to confirm authentication by token is successful without needing an existing external service.

**Comment by vovakulikov** [comment]
@gl-srgr can we close this one?

**Comment by gl-srgr** [comment]
Yeah we can use the workaround for now (fetch repos to confirm token is valid) and then reopen this later.
