### ISSUE TITLE
Fetch repos and orgs by external service ID

### ISSUE THREAD

**Issue by gl-srgr** [sourcegraph/sourcegraph#47984]
New graphql Resolvers for #46648 and #46894 work for discovery requests for code hosts that may not be saved as an external service, provided that the user provides a token.

For users wanting to submit discovery requests for an existing external service, we should just use the external service's existing config for discovery fetch requests, unless the user decides to edit the token as well.

**Comment by vovakulikov** [comment]
@gl-srgr has this been resolved and merged already? if yes can we close it?

**Comment by gl-srgr** [comment]
Yes I will close this one
