### ISSUE TITLE
Sourcegraph Editor: Provide alternate PR views in Review pane

### ISSUE THREAD

**Issue by msorens** [sourcegraph/sourcegraph#48]
- Issue type: **feature request**
- Sourcegraph version: **Sourcegraph Editor 1.21.0**
- OS Version: **MacOS High Sierra**
- Docker version: **NA**

Description:
_I have previously communicated with Linda Xie regarding a feature request to see all PRs that I see at `https://github.com/<org>/<repo>/pulls`. Having thought further about it, this is a revised request, superceding that earlier one._

What I think would be really useful would be to have a “view selector” in the Review pane. This view selector would offer 3 views:

1-**Involved PRs** (this is the what you currently offer): this shows PRs that are open and where the user is the author, an assignee, mentioned in it, or a commenter.

2-**Assigned PRs**: this is like a “to do” list. It would show all open PRs where the user is an assignee and has yet to do a review. Once the user completes a review using the “Approve” button, the PR is then dismissed from this view. That way, a user can know at a glance what PRs are waiting to be reviewed, as well as keep tabs on PRs not yet approved. 

3-**All PRs on a selected repo**. I assume your Review pane would show my involved PRs across various repos, but I am only active in one so I cannot tell for sure… But I am assuming it could contain reviews from different repos, so there would need to be a picker of some type where the user can select a repo from amongst the repos associated with all involved PRs. Once selected, this view would then show all open PRs for that repo. This would just be a lot more convenient than having to go to GitHub.com, open each PR of interest, then assign myself as a reviewer. 

In all 3 above views, it would be great to additionally have:
A- next to each PR, display the number of comments posted on it  (somewhat like GitHub does).
B-embolden the PR title if there are unread comments; once the user opens the PR, switch back to normal, non-bold.

Final note: This could be a separate issue, but for completeness I am mentioning it here: your current notion of “assignee” is apparently a where the user is specifically named; it does **not** consider team memberships of the user. That is, if I am on team “foo” and team “foo” is assigned as a reviewer, that PR should show up in my list of involved PRs.

**Comment by nicksnyder** [comment]
Thanks for the detailed feedback!
