### ISSUE TITLE
Restrict self signup

### ISSUE THREAD

**Issue by sk-aaludra** [sourcegraph/sourcegraph#4800]
Hi,

We are running self hosted sourcegraph and serves the purpose beautifully. We would like to know is there a way to restrict users self signup and access the repository? 

Have tried the below in site admin - configuration, however its not accepting it

	"auth.providers": [
		{
			"allowSignup": false,
			"type": "builtin"
		}
	],
	
Any help much appreciated.

**Comment by slimsag** [comment]
The configuration you posted should definitely work. I can confirm once I am back at my desk.

When you say it doesn't accept it, what is the error you are seeing?

**Comment by sk-aaludra** [comment]
Hi,

Getting the below error. I'm running version 3.4.4

The server reported issues in the last-saved config:
(root): Additional property auth.providers is not allowed

The complete configuration as follows,

{
	"auth.providers": [
		{
			"allowSignup": false,
			"type": "builtin"
		}
	],
	"disablePublicRepoRedirects": true,
}

**Comment by sqs** [comment]
The `auth.providers` configuration is part of the **critical configuration**, which must be set in the management console (https://docs.sourcegraph.com/admin/management_console), not in the site admin area. Please see that doc page and try setting it there.

**Comment by sk-aaludra** [comment]
Sorry I missed it, yes it works fine now. Thanks for the support

**Comment by sqs** [comment]
Great, thanks!
