### ISSUE TITLE
Add JetBrains plugin build to the CI pipeline 

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#48012]
The JetBrains plugin build is broken. We didn't notice it in time because nobody uses it for local development nowadays. We should add to our CI pipeline to avoid such situations in the future.

**Comment by valerybugakov** [comment]
Based on the conversation in the PR where we discovered the build failure:
- https://github.com/sourcegraph/sourcegraph/pull/47864#issuecomment-1437674293

**Comment by taylorsperry** [comment]
I'm assuming this is OK to close, but please re-open if you think we need to @valerybugakov
