### ISSUE TITLE
CI in a backport branch doesn't check stitched migration graph

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#48070]
When merging a backport branch into a release branch (for example `some-branch` -> `4.5`), CI doesn't adequately check for diffs in the stitched migration graph. This is probably because the check in `sg lint` is pulling the static `4.5` revision which does not yet include the changes on HEAD. 

So far in the 4.5 release this has caused considerable churn. We need CI to detect diffs if we are merging into a release branch.

**Comment by coury-clark** [comment]
Example failure https://buildkite.com/sourcegraph/sourcegraph/builds/200570#018675ec-d3e6-4a8c-a96e-846e78981229

**Comment by coury-clark** [comment]
Here is where the migrator tool that generates the stitch graph gets its version from (to determine say the 4.5 revision) https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/database/migration/shared/data/cmd/generator/consts.go?L11:7&subtree=true

**Comment by coury-clark** [comment]
A short convo in slack regarding this problem https://sourcegraph.slack.com/archives/C07KZF47K/p1677021124911779

**Comment by mucles** [comment]
**Migrations Changes CI build fails Investigations Update:**

I ran two tests to see how CI would handle the different scenarios.

**First**: Created a migration change from a branch based off 4.5
4.5 <- mucles/test-migration
https://github.com/sourcegraph/sourcegraph/pull/48316
Create a PR to merge 4.5 from mucles/test-migration
as expected, CI was green with no issues

**Second**: Created a migration change from a branch based off the main, cherry-picked the commit from the branch to the 4.5 branch.
https://github.com/sourcegraph/sourcegraph/pull/48322
Cherry Picked by doing the following manual steps ( backporting tool cherry pick manual instructions)

```
    Fetch the latest updates from GitHub
    'git fetch'
     Create a new working tree
    `git worktree add ../4.5wt 4.5`,
    Navigate to the new working tree
    `cd ../4.5wt`,
    Create a new branch
    `git switch --create mucles/testing-ci-3`,
    Cherry-pick the merged commit of this pull request and resolve the conflicts
    `git cherry-pick -x --mainline 1 af24d11b9358ceee09818fd28e7bdcb05e832c5b
    Push it to GitHub
    `git push --set-upstream origin mucles/testing-ci-3`
    Go back to the original working tree
    "cd ../..",
    Delete the working tree
    `git worktree remove ../4.5wt`,
```

CI build initially failed: https://buildkite.com/sourcegraph/sourcegraph/builds/200570#018675ec-d3e6-4a8c-a96e-846e78981229

❌ frontend: malformed migration definitions: malformed migration definitions "frontend": reorderDefinitions: unknown migration 1675850599 referenced from migration 1677545403

**Steps to Resolve:**

```
1. sg migration leaves c982f23f27addb337836b650ab943037628d8a0d. // latest commit in 4.5

Leaf migrations for "frontend" defined at commit "c982f23f27addb337836b650ab943037628d8a0d"
 1675296942: (add column to changesets for external fork name)
 1676996650: (package_repos_separate_versions_table_patch1)
 1675864432: (add code_host_states to permission_sync_jobs table)
...
```
2. rewrite the parent field with the leaf migrations from above in the metadata.yaml file
3. sg generate
4. git add, git commit, git push changes
5. CI Green

We should automate either the backport tool or the sg cli to include the functionality to perform the above steps automatically whenever a backport of a migration change is required.

**Comment by coury-clark** [comment]
@mucles For now I'm mostly interested in fixing this part

> 5. CI Green

I'm okay if there is some manual work that someone needs to do while merging, we just really need CI to go red when there is a diff between the branch head and 4.5 head. Do you have any ideas on what to do here?

**Comment by coury-clark** [comment]
From sync:

Automation is probably not necessary yet, for now we are going to move forward with just visible documentation and a red CI for the backport branch.

**Comment by mucles** [comment]
Update - documentation provided in the [backport handbook page](https://handbook.sourcegraph.com/departments/engineering/dev/tools/backport/#how-to-update-the-stitched-migration-files)
