### ISSUE TITLE
Docs for query syntax is broken

### ISSUE THREAD

**Issue by andyfangdz** [sourcegraph/sourcegraph#481]
- **Sourcegraph version:** n/a
- **Platform information:** n/a

#### Steps to reproduce:

1.  go to https://docs.sourcegraph.com/user/search/queries
2. observe the table not being formatted correctly

#### Expected behavior:
tables are formatted correctly, the same as the format in github: https://github.com/sourcegraph/sourcegraph/blob/master/doc/user/search/queries.md
#### Actual behavior:
![actual format](https://s3.andyfang.me/screenshots/airbnb/Search_query_syntax_-_Sourcegraph_2018-10-22_15-19-34.png)

**Comment by sqs** [comment]
Thanks for the report, will fix in the next hour

**Comment by sqs** [comment]
Pushed a fix. Will be live on docs.sourcegraph.com in 5 minutes.

**Comment by sqs** [comment]
Confirmed fixed. Thanks again for the report.


![screenshot from 2018-10-22 17-01-30](https://user-images.githubusercontent.com/1976/47326122-213eeb00-d61c-11e8-8ee6-8cd253dc7958.png)

**Comment by andyfangdz** [comment]
Thank you @sqs!
