### ISSUE TITLE
Add text to actions-on-apply dropdown menu items when rollout windows are configured

### ISSUE THREAD

**Issue by BolajiOlajide** [sourcegraph/sourcegraph#48217]

**Comment by courier-new** [comment]
I ❤️ banners, and you know where we really need more of them? The batch change page. 😂 In all seriousness though this is probably a good idea, I just feel bad for the average user getting barraged with yet another banner warning for something that isn't even actionable to them without having admin abilities. But that's what we do for webhooks too so it's not like this would be a one-off offense. 😛

Did we talk about what the banner would say or in what style it would appear?

**Comment by courier-new** [comment]
If we could agree on the wording, this sounds like it'd be quick and valuable. Maybe P0, 0.5 estimate?

**Comment by courier-new** [comment]
Maybe on click "Apply", we show more details about what would happen in the modal (credentials, rollout window, how many would be published, etc.)

**Comment by courier-new** [comment]
Daniel suggested in our team sync we move this closer to the action. So rather than a banner across the whole page, we could add a warning banner alongside "publication states have been recalculated" if rollouts aren't configured and 15+ changesets will be updated or published.

**Comment by courier-new** [comment]
Screenshot of design idea is in the team sync doc.
