### ISSUE TITLE
backports: auto create labels and description

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#48302]
When opening a backport PR we should auto assign labels and relevant PR description. In the labels we should _always_ include a `backport` (without version) label so we can search for outstanding backport PRs

**Comment by mucles** [comment]
PR - Adds the Original PR descriptions to the backported PR 
https://github.com/sourcegraph/test/pull/25

**Comment by mucles** [comment]
I am still working on the implementation of the label for this.  We should add a label for failed backports PR that require a manual backport, maybe something like `manual backport required` or `failed-backport - <version>.`

**Comment by coury-clark** [comment]
Agreed, we can scope that under this issue https://github.com/sourcegraph/sourcegraph/issues/46649

**Comment by mucles** [comment]
Update: sourcegraph/backport creates labels and descriptions for backports
