### ISSUE TITLE
backports: auto assign reviewers

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#48301]
When we open a backport PR into a release branch we should auto assign reviewers. Some candidates that make sense are:
1. The original PR author
2. The merger

**Comment by mucles** [comment]
Backporting auto-assigned me as the reviewer (author and merger) 
https://github.com/sourcegraph/test/pull/25

**Comment by mucles** [comment]
Auto-assignment of author and merger has been added, tested, and released for the backport github action in :
https://github.com/sourcegraph/backport/pull/1
