### ISSUE TITLE
repo name searcher does serial repohasfile filtering

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#4833]
For queries such as `r:sourcegraph repoHasFile:Dockerfile` the `repoHasFile` filtering is done serially. This should be batched.

https://github.com/sourcegraph/sourcegraph/blob/2879ccb/cmd/frontend/graphqlbackend/search_repositories.go#L60

Proposal: Adjust `repoShouldBeAdded` to take a slice of repositoryRevisions.

**Comment by keegancsmith** [comment]
This bit of perf work is important for 3.6, since this feature was introduced this iteration and contains poor perf in this instance. cc @sourcegraph/core-services @ijt @attfarhan @nicksnyder

**Comment by attfarhan** [comment]
Proposal SGTM. Is this something you want someone on the search team to work on, or will core services handle this?

**Comment by slimsag** [comment]
The search team should handle it, we own the feature

**Comment by ijt** [comment]
Here is a plan to speed this up: https://www.notion.so/Speeding-up-queries-with-repohasfile-06b5a919704a4550986ad95e61f76638

**Comment by keegancsmith** [comment]
@ijt we already use zoekt if the repo is indexed. The issue here is we call `repoShouldBeAdded` serially. Instead we should pass in the full list of repos to search. This will automatically split between zoekt and searcher.

IE this line needs to take in a list https://github.com/sourcegraph/sourcegraph/blob/2879ccb/cmd/frontend/graphqlbackend/search_repositories.go#L88

**Comment by ijt** [comment]
Ah, I see. Updated the doc. I'll give it a try.
