### ISSUE TITLE
Footers link to broken documentation

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#48348]
These are broken on s2 as well. 

Browser extensions should go here: https://docs.sourcegraph.com/integration/browser_extension
Editor integrations should go here: https://docs.sourcegraph.com/integration/editor

Both need to have tracking added so that we can see that users are coming from App --> Docs. 

![Image](https://user-images.githubusercontent.com/43555476/221878402-822193cc-4e24-4cc2-8800-0b647faab248.png)

**Comment by marekweb** [comment]
The fix for this in App is in:
-  https://github.com/sourcegraph/sourcegraph/pull/48374

I'm looking into the best solution to fix it on S2 as well.

**Comment by taylorsperry** [comment]
Super, thank you. I might suggest broadening your request for reviewers (especially for something so minor) so that we're not blocking on Stephen. He's got a lot on his plate!
