### ISSUE TITLE
Include all user-related changes in the audit logs

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#48363]
We share logic with GraphQL. [Add user](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/database/users.go?L232) and [delete user](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/database/users.go?L559) already log, but modify and replace don't.
Make sure we have correct logging everywhere. Every change through SCIM should have some trace in the audit log.

**Comment by chwarwick** [comment]
@vdavid  I checked the logic here and currently no user modifications generate audit events.   

I also found that the `delete` does not indicate that it is triggered by `scim` just a delete event with the deleter set to the Internal actor. 

Is the goal here to have _UserModified_ events or to add the events *and* to be able to tie those the events back to `scim`?

**Comment by chwarwick** [comment]
>  do you know about a requirement to know whether the event was triggered on the UI or through SCIM?

@ryphil The context here is that currently when a user account is modified there is no audit log entry.  This change only creates an audit log entry if the modification is the result of a SCIM action.
