### ISSUE TITLE
Sourcegraph for Firefox has been blocked for your protection

### ISSUE THREAD

**Issue by shubhams** [sourcegraph/sourcegraph#4836]
- **Sourcegraph version:** Sourcegraph Firefox Add-on 
- **Platform information:** Ubuntu 16.04, Mozilla Firefox 67.0.4 (64-bit)

#### Steps to reproduce:

1. Open the browser.
2. Go to about:addons using the address bar.

#### Expected behavior:
The add-on should be enabled and working normally.

#### Actual behavior:
The add-on has been disabled by Firefox due to security or stability issues. It needs explicit user action to enable it again.
More details here: https://blocked.cdn.mozilla.net/9fde5729-9be6-4955-9627-67742c5ed62a.html

**Comment by nicksnyder** [comment]
Thanks for the report! We are aware of this situation and are working to explain and document the situation as soon as possible.

**Comment by christinaforney** [comment]
We have added documentation to explain the reason behind the add on being blocked: https://docs.sourcegraph.com/integration/firefox_security

Thanks so much for filing @shubhams !

**Comment by Yggdrasil** [comment]
It appears that manually re-enabling the extension via about:addons is no longer possible. At least, I can't figure out how. So the documentation at https://docs.sourcegraph.com/integration/firefox_security#what-can-i-do is now no longer accurate. Any idea if there's still a viable workaround?

**Comment by Joelkw** [comment]
@Yggdrasil You're right – we've fixed the issues and are just waiting for Firefox to approve the extension. If you want to stay updated, we'll be implementing #14233 once it's back. (As soon as we unblock that issue, it'll be safe to assume you can check Firefox and get the extension.) We're hoping to make that page redundant by the end of the week.
