### ISSUE TITLE
Add Slack notifications to saved searches

### ISSUE THREAD

**Issue by christinaforney** [sourcegraph/sourcegraph#4837]
Add Slack bot integration for notifications to saved searches. Should be easy for any Sourcegraph user to add to their personal or organization level saved searches.

Requested by: https://app.hubspot.com/contacts/2762526/company/419771425/

**Comment by patkujawa-wf** [comment]
Are there plans to implement this? I'd love it :)

**Comment by lguychard** [comment]
Saved searches no longer support notifications, and we are building new slack notifications support for code monitoring.
