### ISSUE TITLE
macOS: "App wants access to my contacts/downloads/etc"

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#48389]
When `sourcegraph` app is ran on macOS in your home directory, it scans all subdirectories for Git repos.

on macOS, this causes security prompts to come up: `Sourcegraph wants access to your Contacts`, `Downloads`, etc. which is obviously surprising to users. Two sourcegraphers have reported this. https://sourcegraph.slack.com/archives/C04F9E7GUDP/p1677592444819169?thread_ts=1677523432.586079&cid=C04F9E7GUDP

Possible solutions:

1. App doesn't scan recursively, it only detects if the current directory is a single Git repo. This is not a great choice because it'd be nice to add multiple repos at once / run it from your projects dir.
2. Detect if the user ran `sourcegraph` in their `$HOME` and then do nothing - I think this would be a good choice as this is almost always going to be a footgun.
3. Document the behavior better (we will do this regardless.)

**Comment by slimsag** [comment]
cc @keegancsmith

**Comment by keegancsmith** [comment]
This is a duplicate of https://github.com/sourcegraph/sourcegraph/issues/48389 but that issue contains more stuff in it. So I will leave this open and only close it once this specific problem is solved.
