### ISSUE TITLE
Update Monitoring page

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#48394]
Add the notice that Monitoring is only available for our Enterprise solutions. Designs [here](https://www.figma.com/file/tbM21yr4k9gJNKkjNc0a4m/UX%3A-Messaging%2FFeedback-in-App?node-id=3%3A610&t=kHc5u9zhLqUYl8sD-0).

This is a part of [UX: Messaging/Feedback in App](https://github.com/sourcegraph/sourcegraph/issues/48273).

**Comment by philipp-spiess** [comment]
Update for the monitoring page based on this [thread](https://sourcegraph.slack.com/archives/C04F9E7GUDP/p1677775360114129?thread_ts=1677764055.420189&cid=C04F9E7GUDP):

- Don't present the 'LIMITED ACCESS' banner.
- Hide the 'Code monitors' and 'Logs' tabs.
- Remove any 'Create code...' button.
- Add the 'Sign up for a Cloud' link'. [We already have this CTA for the .com](https://www.figma.com/file/ScpDpxciO5DeT9YlUGzPUX/UX%3A-Sign-up-journeys-for-auth'd-users?node-id=266%3A1259&t=OR1J43YSsZdju8VW-4)
