### ISSUE TITLE
Add "Coming soon" tab to Nav Bar

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#48396]
We're adding a "Coming soon" tab to the nav bar in App to showcase Cody and Own. Very early WIP designs are [here](https://www.figma.com/file/tbM21yr4k9gJNKkjNc0a4m/UX%3A-Messaging%2FFeedback-in-App?node-id=3%3A610&t=kHc5u9zhLqUYl8sD-0).

@malomarrec and @iskyOS could you please own the copy that should go into each of these sections and @almeidapaulooliveira will incorporate into his design. I think each section should link out to the relevant landing page on `about.sourcegraph.com`. 

@adeola-ak will be ready to implement on 3/13 to merge by 3/17. 

This is a part of [UX: Messaging/Feedback in App](https://github.com/sourcegraph/sourcegraph/issues/48273).

**Comment by malomarrec** [comment]
- Sentinel: I suggest using this: https://www.figma.com/file/BiHioe21wQ7wND8l5qLsNd/%F0%9F%9B%A1-Sentinel-Main?node-id=275%3A1628&t=uK7BJeRWAY1Qa1HD-0
- Own: we're not gonna introduce a top-level menu for Own so far, but if you do introduce one, here's [copy](https://docs.google.com/document/d/1918r_1amJJRBRJHPBc6Je83nMWz7y7rFb3jjrA0_Rjs/edit)
- Cody: here's copy https://github.com/sourcegraph/about/pull/5947

**Comment by taylorsperry** [comment]
From @beyang : For Cody, Starship CTA should be link to private beta sign up.
