### ISSUE TITLE
Update options under user profile dropdown

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#48402]
This isn't scoped yet, but we'll need to make some updates to the options under the user profile dropdown for the app. Requesting feedback in [this doc](https://docs.google.com/document/d/1DH-hlcTMs5GOUXPcqy9nJ9RIgP4gmlrMn6GD5pxq5Bc/edit).

**Comment by philipp-spiess** [comment]
@taylorsperry Provided some feedback in the doc

**Comment by philipp-spiess** [comment]
I worked on the first version of this in #48835. There are some open questions though (moving them into the issue so we can merge the PR):

- [ ] Investigate why docs link did not work for @taylorsperry (they work fine on dev)
- [ ] Admin > Analytics > Overview: How do we want to change the language
- [ ] Admin > License: What do we want to show here?
- [ ] Admin > Maintenance > Pings: @marekweb do you plan on upgrading this after the analytics changes are done?

**Comment by taylorsperry** [comment]
Thank you for https://github.com/sourcegraph/sourcegraph/pull/48835 @philipp-spiess! I've updated the doc to address outstanding questions. Everything that's new is highlighted in purple, which I hope doesn't give you a migraine, but I wanted to find a way to make sure you noticed what's changed 😬

**Comment by philipp-spiess** [comment]
@taylorsperry Thanks, appreciate the color coding! I left a comment in there about the proposed move from some admin APIs to the user config screen, let me know your thoughts.

Another question that just came to my mind is how far we want to go with these removals? Should we only remove the links to them, remove the whole pages on the frontend, or even gate out the functionality on the backend?

**Comment by philipp-spiess** [comment]
Totally, makes sense and I agree.
