### ISSUE TITLE
External service errors are lengthy and hard to understand

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#4842]
![image](https://user-images.githubusercontent.com/10532611/60978286-2fab6f00-a331-11e9-8a82-343accbf034a.png)

The asterisk in there looks weird - looks like the error message is markdown, but not rendered as such.

**Comment by mrnugget** [comment]
I'm not sure whether it's valid Markdown that can be rendered as such. The origin of this the format function here:

https://github.com/hashicorp/go-multierror/blob/886a7fbe3eb1c874d46f623bfa70af45f425b3d1/format.go#L14-L27

**Comment by slimsag** [comment]
multierror format is not Markdown.

**Comment by felixfbecker** [comment]
@slimsag what is the difference? what could happen if we rendered it as such? To me it seems like it just lists errors on each one line starting with `*`, which is exactly the list format of markdown

**Comment by mrnugget** [comment]
@felixfbecker I think it has to do with the missing newline. Just use the function I linked to and generate a message: https://play.golang.org/p/2ZonYDsoVpQ If you then try to render that as Markdown, you'll see that it's not a list that comes out the other end: https://gist.github.com/mrnugget/ddb0df38b4e7d110e34e3e60afd9d29a

**Comment by felixfbecker** [comment]
Ah, the only problem is that it prefixes each point with a tab. If it used a space or omitted it it would work. So we could do

```ts
renderMarkdown(err.message.replace(/\t/g, ''))
```

**Comment by felixfbecker** [comment]
At the very least, even if it's not markdown (it almost is, like 99% there), the message clearly contains indentation and newlines that we currently ignore.
