### ISSUE TITLE
Redesign sign-in/sign-up/request-access pages

### ISSUE THREAD

**Issue by erzhtor** [sourcegraph/sourcegraph#48421]
[Figma designs](https://www.figma.com/file/GQEBnjna5AS5l6vtm4jejD/Account-requests-UI?node-id=210%3A8442&t=8ZEWV0k6bz8zsNn5-4)

Update: We've decided to tackle this as part of auth pages redesign as part of the IAM backlog once [new page designs](https://www.figma.com/file/GQEBnjna5AS5l6vtm4jejD/Account-requests-UI?node-id=258%3A8816&t=3Ga8DFvscvI2JS1m-4) are ready. cc @rrhyne

/cc @sourcegraph/source/iam

**Comment by eseliger** [comment]
done.
