### ISSUE TITLE
POST: Send an email to the user when their account is created

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#48426]
Send a welcome email to the user when they are added.

From a business POV, this is very important.
It should drive a lot of signups once our customers enable SCIM for their org.

- Q: Do we already have a welcome email template somewhere?
   - We don't know, this needs research. If we have some, we can reuse it and trigger it from SCIM CREATE.
- Q: If we do https://github.com/sourcegraph/sourcegraph/issues/48425, this means we'll be sending two emails. Is that a problem?
  - A: No, it's not a problem; two emails are not spamming, so it's okay. They'll get tons of emails at onboarding / role changes anyway, they'll cope with it. Both emails are relevant.
- Q: This should actually happen whenever the user is added by an admin, even if from https://sourcegraph.test:3443/site-admin/users/new. Sending a welcome email is nice. Is that not so?
  - A: Yes, but it's outside of the scope of the SCIM project. We'll do whichever is simpler. We truly don't care now whether we'll start sending a welcome email at manual user creation.
- Q: Do we also want to send an email when the user becomes SCIM-enabled through PATCH or PUT?
  - A: No. They are existing users, we have no business sending them emails in that case.

**Comment by chwarwick** [comment]
> Q: Do we also want to send an email when the user becomes SCIM-enabled through PATCH or PUT?
A: No. They are existing users, we have no business sending them emails in that case.

Is this how it works when a customer is already setup? The identity provider first asks sg what users exist and then send updates for those users?

**Comment by vdavid** [comment]
Yes! With this PR: https://github.com/sourcegraph/sourcegraph/pull/49095, it'll work for Okta. We'll need to test with Azure AD and other IdPs, but I expect similar behavior.

**Comment by vdavid** [comment]
Sorry, I think I closed this by mistake
=
