### ISSUE TITLE
ranking: Change document rank return shape

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#48457]
Currently, the ranking services looks to see what ranks we have in the database for a given repo. If they exist, we return a vector of rankings that correspond to things like whether or not it's generated, a test file, a vendored dependency, etc. Zoekt already has this information so we want to reduce what we need to return here.

Instead of a `map[string][]float64`, we should return the following struct:

```go
type RepoPathRanks struct {
	MedianReferenceCount int
	Paths                map[string]PathRank
}

type PathRank struct {
	Count int
}
```

This leaves an implementation question for @jtibshirani:

If we don't have ranking data for this repo do we want to fall back? We used to return lexicographic order, but we don't want to treat those as reference counts. Should we extend count to have something like a backup ordering, or can Zoekt handle this on its own?

**Comment by jtibshirani** [comment]
My plan was to fall back to the median/ average value when precise code intel is not available. That way the files don't get badly penalized for not having precise intel available. But they are still able to compete on other ranking signals like whether they have a symbol match, repo popularity, etc.

**Comment by efritz** [comment]
@jtibshirani PTAL at #48387.
