### ISSUE TITLE
Bitbucket Server ServiceID is not consistent with other sources

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#4846]
- **Sourcegraph version:** all versions have Bitbucket Server as external source support
- **Platform information:** all platforms

#### Actual behavior:

The current `ExternalRepo.ServiceID` produced by Bitbucket Server source is not a fully qualified URL:

https://github.com/sourcegraph/sourcegraph/blob/043f340e29490e49198af69d62a460c198726fd3/cmd/repo-updater/repos/testdata/bitbucketserver-repos-simple.golden#L17

which is not consistent with other sources:
- GitHub: 

https://github.com/sourcegraph/sourcegraph/blob/043f340e29490e49198af69d62a460c198726fd3/cmd/repo-updater/repos/github_test.go#L60-L63

- GitLab:

https://github.com/sourcegraph/sourcegraph/blob/043f340e29490e49198af69d62a460c198726fd3/pkg/extsvc/gitlab/codehost.go#L16-L21

https://github.com/sourcegraph/sourcegraph/blob/043f340e29490e49198af69d62a460c198726fd3/pkg/extsvc/codehost.go#L32-L38

All test cases under "cmd/repo-updaer/rpeos/bitbucketserver_test.go", [`TestBitbucketServerSource_MakeRepo`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@master/-/blob/cmd/repo-updater/repos/bitbucketserver_test.go?diff=043f340e29490e49198af69d62a460c198726fd3#L16) have similar issue.

#### Expected behavior:

Should be either `http://bitbucket.example.com/` or `https://bitbucket.example.com/`.

#### Reference

>The ServiceID should be a fully qualified URL: `https://bitbucket.org/`

_Originally posted by @tsenart in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3MjU5MjkzODM0/pull_request_reviews/more_threads_

**Comment by Unknwon** [comment]
cc @sourcegraph/core-services

**Comment by Unknwon** [comment]
After some more digging, I think this is not something user would expect to encounter, it should only be inconsistency in tests:

https://github.com/sourcegraph/sourcegraph/blob/043f340e29490e49198af69d62a460c198726fd3/cmd/repo-updater/repos/bitbucketserver_test.go#L26-L48
