### ISSUE TITLE
[Research] Sourcegraph App Diary Study

### ISSUE THREAD

**Issue by meglynst** [sourcegraph/sourcegraph#48504]
We want to conduct a longitudinal study over two weeks to better evaluate that usability of App, the set up experience, and reboot search input job fair projects.

[Sourcegraph App: Research Plan](https://docs.google.com/document/d/1CAA70KbNGqknGC_SFLozPZ2m9nE8Mb9qHlgHxNY9TXo/edit?usp=sharing)

[High level results analysis](https://docs.google.com/spreadsheets/d/1naVdOKjTkQaEndH8xSEi-V12GqfQD9ntmp7ldrjxLWs/edit#gid=1366231875)

[Dovetail](https://sourcegraph.dovetailapp.com/projects/5jxkhs1xC5XrZp2fT2RCY/v/4JGE2aCxTxPKREMTifDPf1)

**To do**
- [x] Write Plan
- [x] Write tasks
- [x] Get approval
- [x] Recruit participants
- [x] Conduct study
- [x] Analyze Download and set up ([see results](https://docs.google.com/spreadsheets/d/1Jm83aMRfxYcxlc7G-Sf3PYk2HVv9V6ipa1sOpabNmxI/edit#gid=0))
- [ ] Analyze first search
- [ ] Analyze daily usage
- [ ] Report out to teams

**Comment by slimsag** [comment]
@meglynst what's the status of this? It's in the "Starship priorities" column and just want to make sure if it is finished that we close it

**Comment by meglynst** [comment]
@slimsag This is not finished! This test will run after Starship so we can test App and integrated features in its post-Starship state. So it should remain open as we run tests over the next couple weeks. I don't necessarily think it needs to be in the "Starship priorities" column as it will be a post-Starship test.
