### ISSUE TITLE
Search results page causes Sourcegraph tab to freeze in Firefox

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#4853]
- **Sourcegraph version:** k8s.sgdev.org
- **Platform information:** macOS, **Firefox 68.0 (64-bit)**

#### Steps to reproduce:

1. Open https://k8s.sgdev.org/search?q=route533+index:only
2. See no results
3. Wait for 5+ seconds

#### Expected behavior:

I can continue using the site, by clicking links in the UI for example

#### Actual behavior:

Site freezes, can't click on links anymore, Firefox shows a warning "this web page appears to be slow"

#### Debugging info

This appears to only happen on the results page and it seems like only when it's empty

I tried to capture a performance profile in Firefox but the browser froze when trying to save it. What I _could_ see before saving was a lot of calls to `setInterval`.

Since the status messages for the global cloning indicator are polled, I disabled that feature to see if it's the reason for the freeze. But even with that disabled and no requests happening in the background, the site freezes.

(I don't know who to assign this too, feel free to reassign @nicksnyder @christinaforney)

It also seems to be related to https://github.com/sourcegraph/sourcegraph/issues/4755

**Comment by nicksnyder** [comment]
This keeps happening regularly (but not predictably) to me on sourcegraph.com. I attempted to catch a profile but it freezes processing the profile:
![image](https://user-images.githubusercontent.com/754768/61177335-9a55e800-a587-11e9-9e80-31a30ceadce8.png)

This seems pretty bad. Can you prioritize this next @attfarhan ?

**Comment by nicksnyder** [comment]
fyi @keegancsmith I believe this is a release blocker.

**Comment by attfarhan** [comment]
I've spent the last few hours trying to repro this and haven't been able to (tried going back to old commits too, and still can't repro). I'll keep an eye out, but if anyone sees this again please comment here.

**Comment by nicksnyder** [comment]
I can very reliably reproduce this on sourcegraph.com.

1. Load this in your browser: https://sourcegraph.com/search?q=r:sourcegraph/sourcegraph+func
2. Switch to another tab for a few minutes, come back and see a blank/frozen screen.

I have not attempted to reproduce in other environments.

**Comment by nicksnyder** [comment]
My user settings are basically empty on sourcegraph.com

```
{
  "typescript.accessToken": "redacted"
}
```

**Comment by vanesa** [comment]
I can confirm that by following Nick's steps, I could reproduce the issue:
![image](https://user-images.githubusercontent.com/9110008/61259628-e6dc2780-a72f-11e9-9b5a-25b555b1e90a.png)

**Comment by attfarhan** [comment]
I screenshared with Vanesa to see her reproduce the issue, but she was not initially able to reproduce the issue in a fresh browser window. She was able to reproduce the Sourcegraph tab crashing when she opened many tabs in a browser window. BUT, it was a fresh tab going to https://sourcegraph.com/search, not a search results page that crashed, even though there was at least one search results page open. She did navigate between a bunch of different tabs, but it still seems very random.

@nicksnyder can you repro using your steps on a fresh browser window with not many other tabs? I wonder if this could be contributing to the problem.

**Comment by attfarhan** [comment]
I was finally able to repro in a browser window with many many tabs. Did not get the "pages unresponsive" warning, but saw CPU at 100% in the Chrome task manager.
 
![image](https://user-images.githubusercontent.com/16265452/61260917-e8f4b500-a734-11e9-87af-654fa26ed38b.png)

**Comment by nicksnyder** [comment]
I think I found it. It freezes as soon as you hover over "33 repositories not found":
![image](https://user-images.githubusercontent.com/754768/61264404-54dd1a80-a741-11e9-99aa-4bad0038b359.png)

Switching between tabs is only relevant insomuch as it affects the path of your mouse across the results page.

**Comment by attfarhan** [comment]
That seems to be it. Thanks Nick!
