### ISSUE TITLE
Impossible to see content that overflows the width of the Repositories filter line in Chrome on Linux

### ISSUE THREAD

**Issue by Reagankm** [sourcegraph/sourcegraph#4856]
- **Sourcegraph version:** 2.13.2
- **Platform information:** Ubuntu 18.04.2 with Chrome 75.0.3770.100

#### Steps to reproduce:

1. Search for something that will have results in enough repositories to overflow the width of the browser

#### Expected behavior:
Be able to see all repositories. Ideally, be able to see them all on the screen at once.  Worst case, should be able to horizontally scroll to see all of them.

#### Actual behavior:
Repositories overflow off the right side of the screen but there is no scroll bar nor any other way I've found to scroll to see all the results.

The CSS `overflow-x: auto` [applied here](https://github.com/sourcegraph/sourcegraph/blob/fa7ad868ad6a20033060c68ed213764f1add7036/web/src/search/results/SearchResultsFilterBars.scss#L23) should be [providing some scrolling mechanism](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-x), although this does not seem to be working. 

However, I think a better solution would be to wrap content that does not fit so you can see all the results on one page.  You can see an example of what I mean if you apply `flex-wrap: wrap` to the `search-results__filters` class.  

Is there any objection to me adding flex-wrap to the css?

**Comment by nicksnyder** [comment]
I am using Chrome on Mac and the horizontal scrolling works for me:
![Screen Recording 2019-07-15 at 07 34 AM](https://user-images.githubusercontent.com/754768/61224220-0d1faa00-a6d3-11e9-89a9-89cd2eacc163.gif)

Are you not able to horizontally scroll the repositories list in the following search?
https://sourcegraph.com/search?q=func+r%3Asourcegraph%2F+count%3A1000

**Comment by nicksnyder** [comment]
Oh, the version of Sourcegraph that you are using is pretty old. It is possible that all you need to do is upgrade to fix this issue (our current version is 3.5.2)

**Comment by Reagankm** [comment]
Yes, sideways scroll works on a Mac with Chrome, even with our old version, but it does not work on Linux with Chrome.

Also, even if sideways scroll was working, I would argue that wrapping repositories is a better UI than scrolling them. If I have a search result in 37 repos (as has happened to me more than once), I'd much rather be able to see them all at a glance than have to sideways scroll through all of them.

**Comment by nicksnyder** [comment]
Thanks for confirming that this appears to be a particular issue on Linux.

You are completely right that our current UI doesn't work well for a lot of repositories. This is feedback that we have heard a few times and we are in the early stages of designing an improved interface specifically to solve this problem. cc @christinaforney 

I don't think we could accept a PR to wrap these though because we have customers with 10k+ repos and that would break the results page :) If you have any ideas how to fix the scroll issue on Linux we would happily look at that PR. Do you know if this is also a problem with Firefox on Linux?

**Comment by Reagankm** [comment]
Confirmed sideways scroll does work on Linux with Firefox (there's a tiny scrollbar that you can use).  This is just a Linux-Chrome issue.  

If I get the time, I'll see if I can find a fix and will update this ticket if so.

**Comment by camdencheek** [comment]
We've since removed the repository filter bar at the top of the page. Since the issue here applies to a component that no longer exists, I think it's safe to close this 🙂
