### ISSUE TITLE
gRPC: write server middleware that creates logs for all HTTP responses < 200 || >= 500

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#48665]
We have some logic in our internal HTTP API that logs all errors that occur from HTTP responses < 200 or >= 500. We should write gRPC middleware that does something similar: 

https://github.com/sourcegraph/sourcegraph/blob/984bdaa36575321b48e4203bcb2b4faa028fac8d/cmd/frontend/internal/httpapi/httpapi.go#L312-L319

**Comment by camdencheek** [comment]
@ggilmore is there more to do here, or does the logging interceptor cover this?

**Comment by eseliger** [comment]
@ggilmore is what we have sufficient for now?

**Comment by ggilmore** [comment]
No, we don't need this anymore.
