### ISSUE TITLE
Use automaxprocs on all go binaries

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#4867]
We have noticed the issues mentioned in this thread https://twitter.com/embano1/status/1149654812595646471 when load testing. A simple fix is to use https://github.com/uber-go/automaxprocs

**Comment by keegancsmith** [comment]
Also sent

- https://gerrit-review.googlesource.com/c/zoekt/+/231206 all: Use automaxprocs
- https://gerrit-review.googlesource.com/c/zoekt/+/231207 all: Use GOMAXPROCS instead of NumCPU

**Comment by slimsag** [comment]
There is some prior discussion about this here:

In particular, please be careful about the sourcegraph/server case: https://github.com/sourcegraph/sourcegraph/issues/2743#issuecomment-473078122

**Comment by keegancsmith** [comment]
I'll respond in that issue, but I believe automaxprocs is the correct fix.
