### ISSUE TITLE
Try to reuse filters from library

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#48718]
We have the `scim/filter` folder that I (@vdavid) copied from the Elimity package. We use this for the heavy-lifting in the filter logic.

But the thing is, this GitHub package exists: https://github.com/scim2/filter-parser, and it seems to do the same. _Moreover_, Elimity has this package as a dependency! Not sure why they reimplemented filtering rather than using this package, but we saw some silly things in Elimity, so I'm not sure whether that's a sensible decision.
Overall, I'd trust this implementation for robustness more than Elimity's.

So, the idea is to see if we can plug in this package for the filtering and get rid of the `scim/filter` folder.

**Comment by chwarwick** [comment]
I looked at this issue, the `github.com/scim2/filter-parser/v2` library only takes care of parsing filter expressions but does not implement any logic to apply the filters to objects which is added by the logic in `scim/filter`.  As it stands we need to keep both.
