### ISSUE TITLE
Update user's email addresses

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#48720]
In [`updateUser`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/scim/user.go?L88), also update (write) the user's email addresses in the DB.

We currently only save the email address of the user on `POST` (create), but we don't update it on `PUT` or `PATCH`, which is a problem—the `user_emails` table content will be obsolete.

**Comment by chwarwick** [comment]
@vdavid Are the following assumptions correct: 

- The `user_emails` table currently only holds he primary email from SCIM and we want to keep it that way
- When SCIM replaces/changes the primary email address it will not require verification

**Comment by vdavid** [comment]
1. No, I think the `user_emails` table should contain all emails we receive through SCIM, and they should all be considered verified.
2. Correct, we expect all email addresses arriving from the IdP to be verified.

**Comment by chwarwick** [comment]
> 1. No, I think the `user_emails` table should contain all emails we receive through SCIM, and they should all be considered verified.

Ok I'll address this first on the create side and just to clarify all the emails are stored within the SCIM data, but only the primary email gets added to the `user_emails` table.

**Comment by vdavid** [comment]
Once again, I think the `user_emails` table should contain _all_ emails we get through SCIM. I think I phrased it unclearly, sorry about it, so we want _all_ emails, not just one email in there.

Reasoning: I'm not sure what we use the alternative email addresses now, but we have them there for some reason or other (probably for matching users to code hosts), and we want to maintain doing it.
One thing you should expect is that verified emails are enforced by the DB to be unique, so adding an email address might fail if it collides with an existing user's email address. I think if this happens we should just silently fail because it's not really an error and we have no way to return a warning about it through SCIM.

**Comment by chwarwick** [comment]
>adding an email address might fail if it collides with an existing user's email address. I think if this happens we should just silently fail because it's not really an error and we have no way to return a warning about it through SCIM.

I was thinking the same thing, it doesn't feel like it's required so I'll just log a warning and move on.
