### ISSUE TITLE
batches: investigate githubs beta scoped access tokens

### ISSUE THREAD

**Issue by adeola-ak** [sourcegraph/sourcegraph#48834]
Investigate if there's a way to grant less rights to batch changes with github's beta scoped access tokens

**Comment by courier-new** [comment]
@malomarrec do you think you could look into this and provide us some guidance as to what customers need and how to prioritize?

**Comment by chrispine** [comment]
@adeola-ak  Is this related to [this thread](https://sourcegraph.slack.com/archives/C04M9JE73E1/p1680287653872629)?
