### ISSUE TITLE
Disable ingestion UI and API on dotcom

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#48847]
It doesn't make sense to have CODEOWNERS ingestion on dotcom. We should hide the UI and disable the API.

**Comment by leonore** [comment]
@limitedmage it doesn't look like the UI shows up? I've tested it with `sg start dotcom` and the fflag own, can you confirm? (working on the API side of it)

**Comment by leonore** [comment]
nevermind, now I have it. @limitedmage API changes are here: https://github.com/sourcegraph/sourcegraph/pull/48994
