### ISSUE TITLE
release-tool: stop release if there are unresolved failed backports

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#48844]
Notify and soft block the release (similar to release-blockers label). We can accomplish this by adding the release-blockers label to the PR.

**Comment by mucles** [comment]
the following labels (`backports`, `failed-backport-to-<target-version>`, `release-blocker`) get added to PR when failing, plus a comment with instructions on how to manually cherry-pick the PR
https://github.com/sourcegraph/backport/pull/1
https://github.com/sourcegraph/backport/pull/2
