### ISSUE TITLE
Investigate what GitHub PAT v2 means for Batch Changes

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#48856]
Can they work for batch changes? What are required scopes? We should also update documentation.

**Comment by chrispine** [comment]
(Isn't adding the team label supposed to move it to our project board?)

**Comment by eseliger** [comment]
weird, right after you poked it it did _something_ 😬 
<img width="820" alt="Screenshot 2023-03-07 at 20 47 44@2x" src="https://user-images.githubusercontent.com/19534377/223536141-f4f5251d-001b-4198-bef8-2924787ed470.png">

maybe GH actions was just stuck or rate limited for a bit?

**Comment by courier-new** [comment]
@malomarrec do you think you could look into this and provide us some guidance as to what customers need and how to prioritize?

**Comment by courier-new** [comment]
Closing in favor of adding more details to the tracking issue.
