### ISSUE TITLE
Re-index all repos after `search.largeFiles` changes

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#4889]
A customer added the `search.largeFiles` configuration and asked how long it will take to re-index all repositories.

https://sourcegraph.slack.com/archives/G9EN3TJDD/p1563208733221700

My assumption is that we don't automatically reindex a repository unless contents have changed, but this isn't a great outcome because it means that this configuration change is not guaranteed to have an effect in any bounded amount of time.

1. Is there a manual way that customers can force all repositories to be indexed?
2. Can we make this happen automatically when `search.largeFiles` changes?

**Comment by nicksnyder** [comment]
cc @ijt @sourcegraph/core-services for any insight/ideas

**Comment by keegancsmith** [comment]
we do reindex if the config changes. https://sourcegraph.com/github.com/sourcegraph/zoekt/-/blob/build/builder.go#L200

This feature was added (including upstream) when he added the large files feature.

**Comment by nicksnyder** [comment]
What is the timebound on the index being updated? The customer updated the config this morning but it still seeing repositories like this:

![image](https://user-images.githubusercontent.com/754768/61246908-d4002d80-a704-11e9-89bb-054e28636e41.png)

**Comment by keegancsmith** [comment]
Depends on the number of repos (reindexing all can take a while). What release is the customer on, we should probably double check that indexed search had this feature. The feature blames to the 22nd of april https://github.com/sourcegraph/zoekt/commit/b45557a20308da36bf901e792fbce7d7b7cbbe95
so went out in our 3.4 release. (just double checked the version of zoekt for each release)

**Comment by nicksnyder** [comment]
Customer is on 3.4. The issue was they added `search.largeFiles` to Global config instead of site config.

**Comment by nicksnyder** [comment]
Reopening because the customer is still having this issue after setting the correct config yesterday.

non-indexed search is behaving as expected but indexed search is not.

@keegancsmith can you take over this conversation?

**Comment by ijt** [comment]
@keegancsmith, can you explain how the code you referenced makes reindexing happen when the config changes?(https://sourcegraph.com/github.com/sourcegraph/zoekt/-/blob/build/builder.go#L200).

**Comment by keegancsmith** [comment]
The function this is in has the following docstring:

```
// IndexVersions returns the versions as present in the index, for
// implementing incremental indexing.
func (o *Options) IndexVersions() []zoekt.RepositoryBranch {
```

In particular we use it here https://github.com/sourcegraph/zoekt/blob/51c44e6be08627c613f787032a2759162bf6f7c2/cmd/zoekt-archive-index/main.go#L148-L153

So if the flags we pass to index are different, IndexVersions will return nil => we don't do the incremental shortcut. See the implementation of index in our index server to see the flags we generate. We ask sourcegraph for extra flags to pass in, which will include the large files flag: https://github.com/sourcegraph/zoekt/blob/51c44e6be08627c613f787032a2759162bf6f7c2/cmd/zoekt-sourcegraph-indexserver/main.go#L186-L217

**Comment by keegancsmith** [comment]
I tested this locally and the feature is working as expected. However, I did run into an issue with frontend using a lot of memory. What is the customer using as the configuration?

**Comment by tsenart** [comment]
> However, I did run into an issue with frontend using a lot of memory. 

Hunch: Could this be `zoekt-index-server` asking the frontend for the git tarball of the repo for indexing? We proxy all of this through the frontend, which would explain this (and we do gzip compression too).

Is there a good reason to proxy this file transfer via the frontend? It'd be more efficient for the frontend to respond with a 302 with a link to git server for the download to happen directly.

**Comment by nicksnyder** [comment]
Can one of you to take over direct communication with the customer in the linked Slack conversation to figure out what the issue is?

**Comment by keegancsmith** [comment]
I've messaged the thread.

The frontend using lots of memory is due to requests, not indexing. I believe it has to do with syntax highlighting.

**Comment by keegancsmith** [comment]
So this should be working. In a steady state, roughly every 10min we should be checking if we need to reindex even if the commit hasn't changed.

I do plan on improving visibility into the index server as part of some other work I have been doing. Adding this to 3.9 to remember to play around with this bug report and use the increased visibility to understand what is going on.

**Comment by keegancsmith** [comment]
Double checked that this should be working. Updated the debug interface to force a reindex, rather than passing in `-incremental`.
