### ISSUE TITLE
Direct to /search when you first download the app

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#48936]
I wiped all my data and started a fresh install and after I logged in (log in will be removed) I was directed to localhost3080/site-admin but I should have gone to /search. 

If someone doesn't run `sourcegraph` from a project directory then the first page they should see is the setup wizard. Upon completing the setup wizard, they should also be directed to /search.

**Comment by slimsag** [comment]
Fixed!
