### ISSUE TITLE
app: add 'delete ALL DATA and restart' option

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#48940]
Add a way to delete all saved/cached App data and restart App.

This issue evolved from an earlier issue about upgrade process and migrations. Below is the old description and comments on that topic.

---

Note: App uses a different version number scheme (`yyyy.mm.dd` - which makes more sense for us because App will be released much more frequently than Enterprise versions of Sourcegraph.)

The enforcement of one-minor-version-upgrade-at-a-time is particularly bad in a desktop/consumer app; we will need to fix this somehow.

@unknwon and @DaedalusG may be working on this already; see https://github.com/sourcegraph/sourcegraph/pull/48787

**Comment by unknwon** [comment]
@efritz - the work that @DaedalusG is currently working on is to make `migrator upgrade` to be able to automatically infer the `--from` and `--to` versions. On top of that, what about making OOBM never deprecated in "App" mode? Is it a super bad idea? 🤔

**Comment by efritz** [comment]
Never making an OOB migration never deprecated in App means it's never deprecated in any code that app can use, so there's no migration at all. If we have to run all migrations always then we can never change the schema that a migrator uses.

We could, though, just have app automatically run upgrade to whatever target version is being booted unconditionally (basically @DaedalusG can force write the update column to true when in app mode).

**Comment by unknwon** [comment]
> Never making an OOB migration never deprecated in App means it's never deprecated in any code that app can use, so there's no migration at all. If we have to run all migrations always then we can never change the schema that a migrator uses.

@efritz - I think the problem here App upgrades are practically uncontrolled (i.e. no well-paced upgrade path that often can happen in the server environment).

If the user upgrades the App at two times that skipped multiple versions, and some OOBMs are deprecated in between, those OOBMs will never be run and the newer version of the App would then take the wrong assumption about the database data/schema readiness and highly likely the App is just in an unusable state (without wiping out all data and re-installed the App)?

**Comment by unknwon** [comment]
@slimsag - Right now, we used 

https://github.com/sourcegraph/sourcegraph/blob/main/internal/singleprogram/postgresql.go#L61

To bypass the problem of one-minor-version-at-a-time for normal migrations.

So I think the main concern here is how we can better handle deprecated OOBMs in future App upgrades. For that, I think the problem is not urgent to block the March Starship launch, and given we are having quarterly releases going forward, it is less time-sensitive at the current moment (used to be risking break App upgrades as soon as one month, now 3 months).

**Comment by slimsag** [comment]
Aha okay, I see. I was seeing this issue occassionally:

```
FATAL	sourcegraph	svcmain/svcmain.go:159	github.com/sourcegraph/sourcegraph/internal/service/svcmain.run.func1	failed to start service	{"Resource": {"service.name": "sourcegraph", "service.version": "2023.03.23+207861.6d0f38", "service.instance.id": "Stephens-MacBook-Pro.local"}, "Attributes": {"service": "frontend", "error": "upgrading \"frontend\" from \"0.0.0+dev\" to \"2023.3.23+207861.6d0f38\" is not allowed, please refer to https://docs.sourcegraph.com/admin/updates#update-policy"}}
```

Why does that `SG_DEV_MIGRATE_ON_APPLICATION_STARTUP` hack not let us go from `0.0.0` to `2023.3.23`? Is it because of the major version change (year)?

**Comment by unknwon** [comment]
> Why does that `SG_DEV_MIGRATE_ON_APPLICATION_STARTUP` hack not let us go from `0.0.0` to `2023.3.23`? Is it because of the major version change (year)?

@slimsag - good spot! There is another check I think we need to disable/skip for app: https://github.com/sourcegraph/sourcegraph/pull/49667

**Comment by slimsag** [comment]
Summary of where we are at with migrations from my POV since @efritz asked [this question here](https://github.com/sourcegraph/sourcegraph/pull/49667#discussion_r1142175821) and I'd rather continue that discussion here than in that PR.

I've been deferring decisions/work here to @unknwon - but I am happy to hear thoughts/advice on this issue. It is definitely mildly concerning, and it is not a problem that I have yet had a chance to think about in any depth.

My understanding as of right now:

1. App disables all enforcement that you perform upgrades in a strict linear fashion like enterprise deployments require
    * ..because enforcing this is very bad in a desktop app ("please run the previous version of Docker first" would be super awkward, and we want to release much more frequently than once-per-quarter with App.)
    * Instead, we let users upgrade to an arbitrary version as long as it is a _future version._ Caveat: it needs to be 'somewhat' recent.
    * In practice this should work just as well as it does in dev environments, since we're using the same workaround/trick (`SG_DEV_MIGRATE_ON_APPLICATION_STARTUP=1`) to force migrations to run on startup.
2. As a result of pt. 1, we should be 'generally' good with migrations BUT we have a problem with deprecating OOBM migrations [which Joe described here](https://github.com/sourcegraph/sourcegraph/issues/48940#issuecomment-1471677353) and will need solving. I'd encourage us to continue discussing that issue there.
    * ..but since we only release enterprise Sourcegraph every quarter now; in practice if someone is ~3 months up-to-date then OOBM migrations will run.
    * ..still, we need a better solution here post-Starship.

Lastly, I'd just reiterate that a desktop app has different expectations, blowing away/starting-fresh with a desktop app because you haven't upgraded in many months and the new version no longer works is much more reasonable than in an enterprise deployment of Sourcegraph.

**Comment by unknwon** [comment]
@taylorsperry just a note of caution that this still needs to be fully solved otherwise it will come to bite us later.

**Comment by taylorsperry** [comment]
Thanks, @unknwon. Re-opening!

**Comment by slimsag** [comment]
Whoever works on this should also answer #49490
