### ISSUE TITLE
Setup Wizard: Add navigation link to setup wizard

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#48967]
Since Sourcegraph app clones repositories if you run your app from the terminal it already will have some repositories on the instance, and we won't show wizard by default. 

But with the setup wizard, you can add other local repositories too so it should be possible to go to the setup somehow from the UI (even if you have some repositories on the instance) 

In this issue, we should add "Go to setup wizard" item in the user menu.

**Comment by taylorsperry** [comment]
cc @philipp-spiess I like Vova's suggestion to add to the user menu. Let's add it to "Repositories."

**Comment by philipp-spiess** [comment]
Love this as well! Anyway I can help with this @vovakulikov? I think we'd have to mount the wizard maybe under a different route for this to work?

**Comment by vovakulikov** [comment]
@taylorsperry, just make sure I understand your suggestion, do you suggest calling it "Repositories" and add to the user nav dropdown, or do you suggest putting some link that would lead to the wizard to the repositories page in site admin?

**Comment by vovakulikov** [comment]
Oh @st0nebraker beat me in this question :)

**Comment by taylorsperry** [comment]
Oh, I was just saying that I think the "Setup wizard" should be "grouped" with the Repositories section.

**Comment by st0nebraker** [comment]
Which repository section? @taylorsperry 
![image](https://user-images.githubusercontent.com/59381432/224127380-f2546ccf-b088-4b12-94f1-0a35097c4987.png)

**Comment by taylorsperry** [comment]
It's under Site admin :)

**Comment by taylorsperry** [comment]
I don't have any strong opinions here, I think I'm just agreeing that the setup wizard makes sense to be accessible from where the user is already going to add code hosts, manage their repositories, etc.

**Comment by st0nebraker** [comment]
Sounds good! Added it to that first suggestion I made to the existing PR

![Image](https://user-images.githubusercontent.com/59381432/224165158-7081e5b0-2935-48e1-9e99-05e1ec0f80d6.png)
