### ISSUE TITLE
Automatically promote first verified email to primary email

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#48996]
See this PR for context: https://github.com/sourcegraph/sourcegraph/pull/48971

> Currently, when I create a user account that initially has no email address stored, but then go in and add one, I still don't have a primary email. Now, I would just need to go in and select it from the dropdown (it actually is already selected), but the dropdown and the Save button are disabled. The only way to set a primary email address is to add a second email, mark reload the page, now be able to select the first one from the dropdown and hit Save, and then remove the second bogus email address again
> [...]
> Should we longer-term address this by instead making sure that the first verified email is always promoted to be the primary email as well? Kinda tedious if you have to go in again and also set it as primary.

/cc @sourcegraph/source/iam

**Comment by MrStacks** [comment]
Working on this.
