### ISSUE TITLE
Add HTML page preview feature. 

### ISSUE THREAD

**Issue by zheeeng** [sourcegraph/sourcegraph#49]
I'm reading a [repo](https://github.com/shichuan/javascript-patterns) which contains only HTML files. Expect Sourcegraph to provide us a nice HTML previewer for source code reading.

**Comment by felixfbecker** [comment]
Hi @zheeeng, the HTML files in the repo you linked seem to only consist of  `<script>` tags - even with an HTML preview, we wouldn't be able to execute them for security reasons.

**Comment by zheeeng** [comment]
@felixfbecker Sorry, I took a bad example. This issue is meant to request a built-in feature like https://github.com/htmlpreview/htmlpreview.github.com did. Sourcegraph is convenient for ppl reading codes and markdown, expect the HTML-reading-friendly.

**Comment by sqs** [comment]
We'd possibly want to provide this as a [Sourcegraph extension](https://github.com/sourcegraph/sourcegraph-extension-api), or at least coordinate it so that the HTML preview could also be used by extensions.

**Comment by slimsag** [comment]
@chrismwendt did you close the wrong issue? It doesn't look to me like the commits above do this.

**Comment by chrismwendt** [comment]
Oops, this got accidentally closed when I merged in the monorepo PR #596. I don't think any other issues/PRs were affected.
