### ISSUE TITLE
Imprecise type information from go language server

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#4903]
- **Sourcegraph version:** 3.6.0-rc.1

#### Steps to reproduce:

1. Ensure you have precise code intel enabled in https://k8s.sgdev.org (this is a global setting, it's only disabled if you added a user setting override).
1. Go to https://bitbucket.sgdev.org/projects/SOUR/repos/vegeta/browse/encode.go#88
2. Hover over `NewCSVEncoder`.

#### Expected behavior:

The definition is shown with the correct argument type. `func NewCSVEncoder(w io.Writer) Encoder`. This works correctly with basic code intel.

#### Actual behavior:

The definition is shown without the package name in the argument type (missing `io`): `func NewCSVEncoder(w Writer) Encoder`

**Comment by efritz** [comment]
We're no longer putting effort into language server support.
