### ISSUE TITLE
lightstep extension: No annotation on localhost 3.6.0

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#4906]
As part of release testing I tried our the lightstep extension with `sourcegraph/server:3.6.0-rc.2`. However, I got no annotations at all. I tried looking at lines with multiple different ways of invoking a start span in our sourcegraph/sourcegraph codebase.

I am unsure how to provide more details to help debug.

**Comment by felixfbecker** [comment]
Duplicate of https://github.com/sourcegraph/sourcegraph-lightstep/issues/6 ?

cc @sqs

**Comment by lguychard** [comment]
This Slack thread seems to imply that this shouldn't be release blocking: https://sourcegraph.slack.com/archives/C07KZF47K/p1558893356026000

**Comment by keegancsmith** [comment]
Duplicate of sourcegraph/sourcegraph-lightstep#6
