### ISSUE TITLE
"Configure Sourcegraph" button flashes for a second on Bitbucket Server even when Sourcegraph is configured.

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#4907]
Go to https://bitbucket.sgdev.org/projects/SOUR/repos/vegeta/browse/attack.go

See "Configure Sourcegraph" appear briefly before the Sourcegraph Icon appears. Is there any way to debounce this so there is no visual jitter?

https://cl.ly/d32fbf13b20f/Screen%252520Recording%2525202019-07-16%252520at%25252008.20%252520AM.mov

**Comment by felixfbecker** [comment]
Can't repro anymore and 90% confident that behavior is no longer codified ✨
