### ISSUE TITLE
Permissions page shows access reason as Site Admin even when authz.enforceForSiteAdmins is enabled

### ISSUE THREAD

**Issue by pjlast** [sourcegraph/sourcegraph#49099]
**Current behaviour**
When visiting the Permissions page of a repository while `authz.enforceForSiteAdmins` is enabled, if a Site Admin has access to the repository, the reason is listed as "Site Admin":

![Image](https://user-images.githubusercontent.com/6427795/224328327-5f218f12-85c6-40c7-a833-3027a587a393.png)

**Expected behaviour**
If `authz.enforceForSiteAdmins` is enabled, Site Admins cannot see repositories unless they have access through an external account. Thus the access reason should be "Permissions sync"

**Comment by thenamankumar** [comment]
Resolved: https://github.com/sourcegraph/sourcegraph/pull/49101
