### ISSUE TITLE
Disabled repository starts cloning when visited (can't repro locally)

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#491]
- **Sourcegraph version:** latest master (>2.12.1)
- **Platform information:** Mac, Chrome

#### Steps to reproduce:

(note I can't repro this locally — I only see it on our sg dev instance)

1. Start a Sourcegraph instance, add a repository, set it to disabled
2. As an admin, find the repo on the site-admin repositories page
3. Visit the repository (i.e. sourcegraph.example.com/github.com/org/repo)
4. Go back, note that it is now cloning

#### Expected behavior:

The repo should not clone while disabled

#### Actual behavior:

The repo did start cloning when visited

**Comment by tsenart** [comment]
@dadlerj: Can you provide more details on the repro steps? Particularly, which kind of external service was used. It would be good to know if you can still observe this behaviour with our current release in Dogfood. If not, let's close.

**Comment by dadlerj** [comment]
It was GitHub, but I can't recall exactly how it happened. I think this was actually pre-external services — this is probably outdated if we've seen no 👍s on this since October.

Did you try to trivially repro on sgdev? If so, and it didn't occur, then let's just close it. If not, let me know and I'll try.

**Comment by tsenart** [comment]
> Did you try to trivially repro on sgdev?

I haven't because I didn't have specific enough repro steps. If you can, please try it again and let me know if it still occurs. Thanks!

**Comment by dadlerj** [comment]
Looks like this is still happening on sgdev, it's trivial to repro as described above. I only tested GH repos.

![feb-11-2019 issue-491](https://user-images.githubusercontent.com/5589410/52588569-a6c7f000-2df1-11e9-9e17-9d736dcacd52.gif)

**Comment by tsenart** [comment]
We don't have disabled repos anymore.
