### ISSUE TITLE
Cannot add vim/vim repo on k8s instance

### ISSUE THREAD

**Issue by ijt** [sourcegraph/sourcegraph#4911]
I tried adding this external service on k8s.sgdev.org:

![Screen Shot 2019-07-16 at 12 12 33](https://user-images.githubusercontent.com/15530/61322705-2a33a600-a7c3-11e9-9830-c70d599935b1.png)

It said "Updated!" but when I looked for the repo it wasn't there:

![Screen Shot 2019-07-16 at 12 11 21](https://user-images.githubusercontent.com/15530/61322785-53543680-a7c3-11e9-8ded-6e792ff3e2bc.png)

**Comment by ijt** [comment]
It works on a local docker instance run with `IMAGE=sourcegraph/server:3.6.0-rc.2 ./dev/run-server-image.sh`:

![Screen Shot 2019-07-16 at 12 20 52](https://user-images.githubusercontent.com/15530/61323208-3ff59b00-a7c4-11e9-9858-54b5fcfcc976.png)

**Comment by mrnugget** [comment]
Is this related to [syncing being slow on k8s.sgdev.org](https://sourcegraph.slack.com/archives/C07KZF47K/p1563321839140500)?

**Comment by keegancsmith** [comment]
Yes it, since it is now present. https://k8s.sgdev.org/github.com/vim/vim

I am closing this as wontfix since our setup is unique for k8s.sgdev. Please see the slakc thread for more context.

**Comment by mrnugget** [comment]
Just so nobody is confused: I added `vim/vim` manually to a repos list and waited until it was synced.
