### ISSUE TITLE
Export CSV truncates results to 1500

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#49160]
**Reported by:** https://github.com/sourcegraph/accounts/issues/3

When we switched the CSV export feature to use the streaming search API, the hard-coded display limit of 1500 started getting applied to exported results. This is is problematic because exported results are often used for further automation, auditing, or bug fixing.

The likely fix here is to update the export feature to re-run the search without a display limit so that exports get the full result set.

/cc @sourcegraph/search-product

**Comment by camdencheek** [comment]
Fixed by #49646

**Comment by limitedmage** [comment]
Follow-up meta-issue: https://github.com/sourcegraph/sourcegraph/issues/49645
