### ISSUE TITLE
Don't show hover tooltip action buttons if capability is not supported

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#492]
Reported by a user

> Its a bit annoying when you click on implementations and it says its not implemented. Consider making it not clickable or hide from UX

Other instances:
- https://github.com/sourcegraph/sourcegraph/issues/301
- https://github.com/sourcegraph/enterprise/issues/11124

cc @felixfbecker @chrismwendt @ijsnow for comment

**Comment by lguychard** [comment]
This is now fixed: only "actionable" buttons are shown.

![image](https://user-images.githubusercontent.com/1741180/51189890-4ec8c700-18e1-11e9-9fdc-0e7261c9b01a.png)
