### ISSUE TITLE
SCIM PATCH reset primary values when one item is set to "true"

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#49210]
Ensure the PATCH endpoint is compliant with the following item from the SCIM specification: 
```
For multi-valued attributes, a PATCH operation that sets a value's "primary" sub-attribute to "true" 
SHALL cause the server to automatically set "primary" to "false" for any other values in the array.
```

This means that a PATCH operation that sets the primary value to true for an item in an array should also ensure that after that operation no other item in the array has a primary value of true.

**Comment by vdavid** [comment]
@chwarwick I'm pretty busy with the OIN enablement, and you've worked on PATCH a lot, do you think you could tackle this one?

**Comment by vdavid** [comment]
@chwarwick never mind, I think I've fixed it
