### ISSUE TITLE
Unable to verify cross repository TypeScript code intel on new k8s cluster

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#4921]
I am following this test plan: https://docs.google.com/document/d/1EIyUffiduVawHsKUL2dV_xnVLG2rjJN-xxF5G9hFlVI/edit#heading=h.xl38wt6dl3ue

1. I created a new k8s cluster following the instructions in [deploy-sourcegraph](https://github.com/sourcegraph/deploy-sourcegraph).
    `gcloud container clusters get-credentials nick-3-6-test-cluster --zone us-central1-a --project sourcegraph-server`
2. I port forwarded like this `kubectl port-forward svc/sourcegraph-frontend 3080:30080` so I could access the frontend via http://localhost:3080
3. I followed [these steps](https://github.com/sourcegraph/deploy-sourcegraph/tree/master/configure/lang/typescript#apply-the-javascripttypescript-language-server-configuration-to-the-cluster) to deploy the TypeScript language server to the cluster. I skipped setting up basic auth or TLS since those are optional steps.
4. I port forwarded the TS langserver like this `kubectl port-forward svc/lang-typescript 9876:8080`
5. I configured the server url like this:
    ```
    "typescript.serverUrl": "ws://localhost:9876"
    "typescript.sourcegraphUrl": "http://sourcegraph-frontend:30080"
    ````
6. I added an external service with sourcegraph/sourcegraph and sourcegraph/codeintellify.
7. I opened a tsx file like http://localhost:3080/github.com/sourcegraph/sourcegraph/-/blob/browser/src/libs/bitbucket/code_intelligence.tsx and was not able to jump to definition for the AdjustementDirection symbol (Which is provided by codeintellify).
![Screen Recording 2019-07-16 at 05 39 PM](https://user-images.githubusercontent.com/754768/61339097-0f782600-a7f1-11e9-8497-8c71378bc338.gif)

Here is the error text
```
2879-sourcegraph-typescript.js?bv877q76n43c--sourcegraph-typescript:1571 5:39:14 PM TypeScript backend [conn 284dfad0-a82b-11e9-929b-39ea567f707c] Error handling message { jsonrpc: '2.0',  id: 37,  method: 'textDocument/definition',  params:   { textDocument:      { uri:         'http://sourcegraph-frontend:30080/github.com/sourcegraph/sourcegraph@cdd9abe109eaca8c78e00090a3120666a699a231/-/raw/browser/src/libs/bitbucket/code_intelligence.tsx' },     position: { line: 0, character: 9 } } }  Error: Connection got disposed.    at Object.dispose (/srv/node_modules/vscode-jsonrpc/lib/main.js:876:25)    at Object.disposeAll (/srv/server/src/disposable.ts:29:28)    at Object.dispose (/srv/server/src/language-server.ts:123:24)    at restartLanguageServer (/srv/server/src/server.ts:492:28)    at tracing_1.tracePromise (/srv/server/src/server.ts:714:27)    at processTicksAndRejections (internal/process/next_tick.js:81:5)
logType @ 2879-sourcegraph-typescript.js?bv877q76n43c--sourcegraph-typescript:1571
error @ 2879-sourcegraph-typescript.js?bv877q76n43c--sourcegraph-typescript:1571
(anonymous) @ 2879-sourcegraph-typescript.js?bv877q76n43c--sourcegraph-typescript:1628
(anonymous) @ 2879-sourcegraph-typescript.js?bv877q76n43c--sourcegraph-typescript:943
(anonymous) @ 2879-sourcegraph-typescript.js?bv877q76n43c--sourcegraph-typescript:943
(anonymous) @ 2879-sourcegraph-typescript.js?bv877q76n43c--sourcegraph-typescript:943
D.<computed> @ a61b12df-9ed7-4799-bf11-2267cfa00d3c:1
w @ a61b12df-9ed7-4799-bf11-2267cfa00d3c:1
F @ a61b12df-9ed7-4799-bf11-2267cfa00d3c:1
2879-sourcegraph-typescript.js?bv877q76n43c--sourcegraph-typescript:1571 5:39:14 PM TypeScript backend [conn 284dfad0-a82b-11e9-929b-39ea567f707c] Error handling message { jsonrpc: '2.0',  id: 38,  method: 'textDocument/hover',  params:   { textDocument:      { uri:         'http://sourcegraph-frontend:30080/github.com/sourcegraph/sourcegraph@cdd9abe109eaca8c78e00090a3120666a699a231/-/raw/browser/src/libs/bitbucket/code_intelligence.tsx' },     position: { line: 0, character: 9 } } }  Error: Connection got disposed.    at Object.dispose (/srv/node_modules/vscode-jsonrpc/lib/main.js:876:25)    at Object.disposeAll (/srv/server/src/disposable.ts:29:28)    at Object.dispose (/srv/server/src/language-server.ts:123:24)    at restartLanguageServer (/srv/server/src/server.ts:492:28)    at tracing_1.tracePromise (/srv/server/src/server.ts:714:27)    at processTicksAndRejections (internal/process/next_tick.js:81:5)
logType @ 2879-sourcegraph-typescript.js?bv877q76n43c--sourcegraph-typescript:1571
error @ 2879-sourcegraph-typescript.js?bv877q76n43c--sourcegraph-typescript:1571
(anonymous) @ 2879-sourcegraph-typescript.js?bv877q76n43c--sourcegraph-typescript:1628
(anonymous) @ 2879-sourcegraph-typescript.js?bv877q76n43c--sourcegraph-typescript:943
(anonymous) @ 2879-sourcegraph-typescript.js?bv877q76n43c--sourcegraph-typescript:943
(anonymous) @ 2879-sourcegraph-typescript.js?bv877q76n43c--sourcegraph-typescript:943
D.<computed> @ a61b12df-9ed7-4799-bf11-2267cfa00d3c:1
w @ a61b12df-9ed7-4799-bf11-2267cfa00d3c:1
F @ a61b12df-9ed7-4799-bf11-2267cfa00d3c:1
location.ts:139 Error: Connection got disposed.
    at 2879-sourcegraph-typescript.js?bv877q76n43c--sourcegraph-typescript:943
    at 2879-sourcegraph-typescript.js?bv877q76n43c--sourcegraph-typescript:943
    at 2879-sourcegraph-typescript.js?bv877q76n43c--sourcegraph-typescript:943
    at D.<computed> (blob:http://localhost:3080/a61b12df-9ed7-4799-bf11-2267cfa00d3c:1)
    at w (blob:http://localhost:3080/a61b12df-9ed7-4799-bf11-2267cfa00d3c:1)
    at MessagePort.F (blob:http://localhost:3080/a61b12df-9ed7-4799-bf11-2267cfa00d3c:1)
(anonymous) @ location.ts:139
error @ catchError.ts:132
notifyError @ OuterSubscriber.ts:17
_error @ InnerSubscriber.ts:21
error @ Subscriber.ts:113
a.error @ common.ts:45
(anonymous) @ comlink.js:93
async function (async)
(anonymous) @ comlink.js:85
hover.ts:49 Error: Connection got disposed.
    at 2879-sourcegraph-typescript.js?bv877q76n43c--sourcegraph-typescript:943
    at 2879-sourcegraph-typescript.js?bv877q76n43c--sourcegraph-typescript:943
    at 2879-sourcegraph-typescript.js?bv877q76n43c--sourcegraph-typescript:943
    at D.<computed> (blob:http://localhost:3080/a61b12df-9ed7-4799-bf11-2267cfa00d3c:1)
    at w (blob:http://localhost:3080/a61b12df-9ed7-4799-bf11-2267cfa00d3c:1)
    at MessagePort.F (blob:http://localhost:3080/a61b12df-9ed7-4799-bf11-2267cfa00d3c:1)
```

**Comment by nicksnyder** [comment]
Would you like me to keep my cluster running to further debug this?

**Comment by lguychard** [comment]
I followed your steps and could not reproduce this issue:

Initially the definition URL is http://localhost:3080/github.com/sourcegraph/sourcegraph/-/blob/browser/src/libs/bitbucket/code_intelligence.tsx#L1:10 (the location of the hovered symbol).

Eventually, after dependencies are installed (after about ~1min), the correct definition URL (http://localhost:3080/github.com/sourcegraph/codeintellify@2658b95f85e1dfc7227f9e110436bd10a58f46b2/-/blob/src/hoverifier.ts#L143:13) is loaded:

![image](https://user-images.githubusercontent.com/1741180/61391010-20419e00-a8bc-11e9-9ba0-6e23ff2abbbf.png)

**Comment by lguychard** [comment]
I can also reliably get cross-repo references:

![image](https://user-images.githubusercontent.com/1741180/61392034-449e7a00-a8be-11e9-8737-baa8992757b7.png)

**Comment by nicksnyder** [comment]
Huh, it does work for me now after waiting. Did you manually visit codeintellify first? I didn't. Is it necessary to visit the dependency repo first for cross repo code intel to work?

**Comment by lguychard** [comment]
The first symbol I hovered was in sourcegraph/sourcegraph, I did not visit codeintellify first

**Comment by nicksnyder** [comment]
It was broken in some way initially (there was an error in the console) and I am not sure what resolved the issue. I'll leave it up to you whether to close this issue or keep it open for more investigation.

**Comment by nicksnyder** [comment]
I retested defs/refs for that symbol multiple times today and it worked, but I always had to wait a minute because I am assuming the cache was cold, so it wasn't the best user experience.

Since it appears to be working consistently now, I deleted the cluster and will close this issue.
