### ISSUE TITLE
Deploy to a cluster and contact us link in search performance warning notice is relative, not absolute

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#4928]
1. Go to https://demo.sgdev.org
1. Search for `(hunk|repository)resolver index:only timeout:1000s`
1. Notice Search performance warning shown. Click on Contact us link.
1. Taken to repo 404 page as the link was `/https://about.sourcegraph.com/contact`.

<img width="948" alt="Screen Shot 2019-07-17 at 10 52 53 PM" src="https://user-images.githubusercontent.com/133014/61377395-7b888600-a8e6-11e9-87c7-7823df3eac58.png">

<img width="943" alt="Screen Shot 2019-07-17 at 10 53 09 PM" src="https://user-images.githubusercontent.com/133014/61377416-85aa8480-a8e6-11e9-8ee8-d68479da0c92.png">

**Comment by ijt** [comment]
Adding over 100 repos for some reason didn't trigger the warning on my dev instance, so instead I made this hack to get it to appear:
```
[ ~/src/github.com/sourcegraph/sourcegraph ] git diff
diff --git a/web/src/search/results/SearchResultsInfoBar.tsx b/web/src/search/results/SearchResultsInfoBar.tsx
index 0193b03ee6..351ceab43c 100644
--- a/web/src/search/results/SearchResultsInfoBar.tsx
+++ b/web/src/search/results/SearchResultsInfoBar.tsx
@@ -140,6 +140,6 @@ export const SearchResultsInfoBar: React.FunctionComponent<SearchResultsInfoBarP
             </small>
         )}
         {!props.results.alert && props.showDotComMarketing && <ServerBanner />}
-        {!props.results.alert && props.displayPerformanceWarning && <PerformanceWarningAlert />}
+        {<PerformanceWarningAlert />}
     </div>
 )
```
The bad link is there. I think I have to change it from `<Link` to `<a`.

**Comment by ijt** [comment]
Yep, that did it.

**Comment by keegancsmith** [comment]
Marking release blocker since it should be easy to fix and affects our top of funnel.
