### ISSUE TITLE
504 error when searching on k8s.sgdev.org with indexed search disabled

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#4929]
1. Go to https://k8s.sgdev.org/site-admin/configuration
1. set `search.index.enabled` to `false`
1. Search for `(hunk|repository)resolver timeout:1000s`
1. The request should time out with, page displays `Unexpected HTTP error: 504`.

The error displayed to the user should be more user-friendly and explain what happened instead of just the unexpected error message.

**Comment by ijt** [comment]
I didn't get a 504 with the query shown here:
![Screen Shot 2019-07-17 at 14 01 31](https://user-images.githubusercontent.com/15530/61411796-085a2200-a89c-11e9-84fa-132332aa9ec5.png)

Adding a very high `count:` field reproduced it though:
![Screen Shot 2019-07-17 at 14 05 10](https://user-images.githubusercontent.com/15530/61411787-f8dad900-a89b-11e9-8faf-b329fc3bc6f5.png)

**Comment by ijt** [comment]
@ryan-blunden can you say more specifically what you would like the error message to say? How about "Unexpected HTTP error: 504. The request timed out on the backend."?

**Comment by keegancsmith** [comment]
We need to update this test plan. We have too many repositories on k8s.sgdev for unindexed search to work.

@sourcegraph/distribution I am removing this cell from the test grid. Closing this issue as WONTFIX.
