### ISSUE TITLE
Investigate case where repo's deleted_at was set but not renamed

### ISSUE THREAD

**Issue by pjlast** [sourcegraph/sourcegraph#49298]
Also see this Slack thread: https://sourcegraph.slack.com/archives/C03D4H7UBEV/p1678686493434869

# Background

The Starburst code host connection on sourcegraph.com had the following errors:

![Image](https://user-images.githubusercontent.com/6427795/224986766-6de6c525-95a2-46e8-bf02-3b3a2818eec4.png)

The relevant one here is the `repo_name_unique` constraint violation.

This happened because of the following scenario:
There was a repo named `github.com/elide-dev/elide` , and its `deleted_at` column in the database was set (i.e. it was not equal to NULL).

There was a another repo named `github.com/elide-dev/v3`.

In the meantime, on GitHub itself, `github.com/elide-dev/elide` had been archived and renamed to `github.com/elide-dev/archived` and `v3` had been renamed to `github.com/elide-dev/elide`.

Normally, this shouldn't be a problem, because when we try to sync the new `github.com/elide-dev/elide`, which has a new `external_id`, we will hit this part in the syncer: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/repos/syncer.go?L734-782
The conflict will be resolved, because the original repo will be deleted, and then the `elide-dev/v3` one will be renamed.

However, what happened here was that, because `github.com/elide-dev/elide` had a `deleted_at` column that was NOT NULL, the deletion code did not execute: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@cc0edb287f97b5991d7d1d9b7f6e50836ce62b85/-/blob/internal/database/repos.go?L1628-1639

As you'll see, it only deletes if `deleted_at IS NULL`. The effect that this has is that the repo is also not renamed to `DELETED-XXXXXX-github.com/elide-dev/elide` , and then, when the `v3` repo's name gets updated, it conflicts with the existing repo.

# Question

How did the original `github.com/elide-dev/elide` end up in a state where its `deleted_at` column was set, but the repo name was not `DELETED-XXXXX-github.com/elide-dev/elide` ?

**Comment by cbart** [comment]
The issue was fixed by always updating deleted_at in the store, but the reason for why the repo was in an inconsistent state is still unknown.
