### ISSUE TITLE
Should sourcegraph-test-db not be created by the tests pipeline?

### ISSUE THREAD

**Issue by mpl** [sourcegraph/sourcegraph#493]
Hi,

I'm working with your tests pipeline generated with dev/ci/gen-pipeline.go
I've gotten as far as it running ./dev/ci/ci-db-backcompat.sh, which fails when running:
"psql -t -d sourcegraph-test-db -c 'select version from schema_migrations' | xargs echo -n"
because sourcegraph-test-db does not exist. I also see it being needed in ./dev/ci/reset-test-db.sh, but nowhere in the code base did I find this database being created.

Am I supposed to add an additional step at the beginning of the tests pipeline, that creates this database?

Cheers,
Mathieu

**Comment by nicksnyder** [comment]
@beyang @keegancsmith do you know when/where our test database is created?

I don't see any obvious places here:
https://sourcegraph.sgdev.org/search?q=sourcegraph-test-db

One thought was that its creation was baked in to our buildkite image, but I don't see it there either, unless initdb does the trick?

https://sourcegraph.sgdev.org/github.com/sourcegraph/infrastructure/-/blob/docker-images/buildkite-agent/pre-entrypoint.sh#L20

**Comment by mpl** [comment]
fyi, the link to that pre-entrypoint.sh seems to be restricted to members of your org, I can't access it.

**Comment by nicksnyder** [comment]
> fyi, the link to that pre-entrypoint.sh seems to be restricted to members of your org, I can't access it.

Yeah, this link was for the people that I mentioned.

**Comment by sqs** [comment]
The DB for tests is created in [`initTest`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@5fc69ea73bf1b7c026a702318398ae16e92c3e49/-/blob/cmd/frontend/db/testing/db_testing.go#L130:28). I don't know why it is not getting created in your pipeline; perhaps it is serendipitously created by a former job when we run our tests and we never explicitly ensure it's created when running that specific step in isolation?

**Comment by mpl** [comment]
@sqs ok, I'll track down who/what is supposed to call initTest, and check whether it's included in the pipeline.

fwiw, I use something like that atm (which I extracted from what dev/ci/gen-pipeline.go generated):

	#!/bin/bash
	set -eux
	
	service postgresql start
	until runuser -l postgres -c 'pg_isready' 2>/dev/null; do >&2 echo 'Postgres is unavailable - sleeping for 5 seconds'; sleep 5; done
	sudo -i -u postgres  -- createuser --superuser root
	sudo -i -u postgres -- psql -c "ALTER USER root PASSWORD 'sourcegraph';"
	sudo -i -u postgres -- psql -c "CREATE DATABASE \"sourcegraph-test-db\";" #added to solve the issue we're talking about right now.
	./dev/check/all.sh
	yarn --frozen-lockfile && yarn run prettier
	FORCE_COLOR=1 PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true yarn --frozen-lockfile && yarn run tslint
	PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true FORCE_COLOR=1 yarn --frozen-lockfile && yarn run stylelint --quiet
	yarn --frozen-lockfile && yarn run graphql-lint
	FORCE_COLOR=1 PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true yarn --frozen-lockfile && yarn run browserslist && NODE_ENV=production yarn run build --color && GITHUB_TOKEN= yarn run bundlesize
	FORCE_COLOR=1 PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true yarn --frozen-lockfile && yarn run cover && node_modules/.bin/nyc report -r json
	curl -sL -o hadolint "https://github.com/hadolint/hadolint/releases/download/v1.6.5/hadolint-$(uname -s)-$(uname -m)" && chmod 700 hadolint && git ls-files | grep -v '^vendor/' | grep Dockerfile | xargs ./hadolint
	./dev/ci/ci-db-backcompat.sh
	./dev/ci/reset-test-db.sh || true && go test -coverprofile=coverage.txt -covermode=atomic -race ./...

**Comment by keegancsmith** [comment]
`./dev/ci/ci-db-backcompat.sh` will create the database. The `go test` in that script triggers `initTest`.

**Comment by mpl** [comment]
@keegancsmith except it doesn't seem to here. :-) But at least now I know it's supposed to, thx. I'll read the code and figure it out.

**Comment by keegancsmith** [comment]
It's probably failing due to lack of env vars. Our CI environment sets the following envvars in its docker image (and possibly more I am missing)
```
ENV PGUSER postgres
ENV PGDATABASE postgres
ENV PGSSLMODE disable
```

**Comment by nicksnyder** [comment]
In general, our CI pipeline is designed to run on our private buildkite agents which have a few things pre-configured. It would be ideal for use to move away from invisible state like so it is possible for anyone to run CI on this project and so we can run CI on all pul requests (https://github.com/sourcegraph/sourcegraph/issues/497)

**Comment by mpl** [comment]
btw, feel free to close that issue, now that I know what is supposed to happen. I'll re-open if/when I find something actually wrong in your code.

**Comment by nicksnyder** [comment]
Ok, going to close this in favor of #497
