### ISSUE TITLE
app: docs should show the same download methods as about page

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#49316]
stephen rewrote:

https://docs.sourcegraph.com/app should show the same download methods as https://about.sourcegraph.com/app - or potentially just link users to that page for download.

Note that if we choose to include the download options on the docs page, then those downloads will not be tracked in metrics so we need to be mindful of that.

**Comment by toolmantim** [comment]
It looks like https://about.sourcegraph.com/get-started could be another option too

**Comment by marekweb** [comment]
> Note that if we choose to include the download options on the docs page, then those downloads will not be tracked in metrics so we need to be mindful of that.

Actually we can already track metrics on downloads in the Docs site as long as the download link has a [data-download-name](https://sourcegraph.com/search?q=context:global+data-download-name+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+&patternType=standard&sm=1&groupBy=repo)attribute in the `<a>` tag, ideally matching the same downloadName that is used for that download on the About site.
