### ISSUE TITLE
SCIM: Azure AD Patch Validation test fails 

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#49325]
The Azure AD SCIM simulator fails when it generates a PATCH request that sets the user `active` -> false.

It is not clear why the validator is failing in this case as it reports there are missing fields however they are present in the response.

![Image](https://user-images.githubusercontent.com/6098507/225116935-5b30381c-5ce0-43d3-a9c4-5795f7c120c9.png)

**Comment by chwarwick** [comment]
After some investigation I see why this is now failing.  The validation expects this to act as a soft delete and it is not validating the result of the PATCH but the result of a later GET.  

Since we are not supporting soft delete for the initial release this failure is not a problem.

![Image](https://user-images.githubusercontent.com/6098507/225119601-1887c8f0-696d-4b42-ac85-095dd5eb1d95.png)

**Comment by vdavid** [comment]
Ah, nice, I didn't see this issue and I did the same investigation, and have come to the same conclusion.
