### ISSUE TITLE
gRPC: QA Plan

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#49347]
# QA Test Plan

## Summary

We have converted several internal services (sourcegraph-frontend-internal's zoekt configuration APIs, symbols, searcher, repo-updater, and gitserver) to use gRPC for communication instead of REST APIs.

This change improves performance and enables stronger typing and streaming APIs. It also paves the road for subsequent internal service changes to use gRPC and its large ecosystem.

#### **Functional testing**

Test all endpoints of all converted services manually to ensure functionality is preserved

#### SymbolsService:

- [x] Search

I ran a number of symbol searches with similar profiles to unindexed search. No issues.

- [x] LocalCodeIntel
- [x] ListLanguages
- [x] SymbolInfo

I clicked around in the UI and ran a few GraphQL queries to exercise these. Everything seems to be working as expected. 

There are a significant number of `Unknown` and `Unimplemented` errors. The `Unimplemented` are expected.

#### SearcherService:

- [x] Search streaming

Tested unindexed search with a variety of different searches, all which returned the same results as indexed search. Latency seems stable and low.

It looks like we might still have a slow goroutine leak in searcher. It does not immediately look to be caused by gRPC.
<img width="1466" alt="Screenshot 2023-03-22 at 11 49 13" src="https://user-images.githubusercontent.com/12631702/226993487-ad1651c5-7ce7-4e94-ac04-dc0f3e327895.png">

#### GitserverService:

- [x] Exec streaming
- [x] Search streaming

<img width="1632" alt="Screen Shot 2023-03-21 at 2 41 25 PM" src="https://user-images.githubusercontent.com/9022011/226747788-3d35d2a7-cf4b-4eb0-834b-d7250cec6432.png">

Over the past 7 days on sourcegraph.com, we've seen some error spikes in both Exec and Search methods. Most of these are explainable by either:

- New image updates (causing gitserver  pods to get bounced): https://sourcegraph.com/-/debug/grafana/d/gitserver/git-server?orgId=1&from=1678829989505&to=1679433014545&var-alert_level=All&var-shard=All&var-method=All
- (in the case of Search) a drop overall request rates which magnifies the error percentage ([Grafana link](https://sourcegraph.com/-/debug/grafana/goto/lB22_7f4k)): ![Screenshot 2023-03-21 at 14-46-33 Git Server - Grafana](https://user-images.githubusercontent.com/9022011/226748664-6aaba593-41ae-4bbb-adef-64586ee27c3c.png)

Exec's p90 response time is around 400 ms (but it's a method whose duration can vary wildly depending on the repository and exact git command called) ([grafana link](https://sourcegraph.com/-/debug/grafana/explore?orgId=1&left=%5B%221678829989505%22,%221679433014545%22,%22Prometheus%22,%7B%22expr%22:%22histogram_quantile(0.9,%20sum%20by%20(le,%20name,%20grpc_method)%20(rate(gitserver_grpc_server_handling_seconds_bucket%7Bgrpc_method%3D~%5C%22(Search)%5C%22,instance%3D~%5C%22(gitserver-0%7Cgitserver-1%7Cgitserver-2%7Cgitserver-3%7Cgitserver-4%7Cgitserver-5%7Cgitserver-6%7Cgitserver-7%7Cgitserver-8%7Cgitserver-9)%5C%22%7D%5B1m%5D)))%22,%22datasource%22:%22Prometheus%22,%22exemplar%22:true,%22requestId%22:%22Q-37ba4802-1666-4ee5-98a0-ea6cb3dd7314-0A%22%7D%5D)): 
<img width="543" alt="image" src="https://user-images.githubusercontent.com/9022011/226749874-5fb13d23-8de2-4b2d-96a8-92067207b90a.png">

Search's p90 response time is can vary between 0 and 10 seconds (but again it's a method whose duration can vary wildly depending on the repository and exact git command called) ([grafana link](https://sourcegraph.com/-/debug/grafana/d/gitserver/git-server?viewPanel=100721&orgId=1&from=1678829989505&to=1679433014545&var-alert_level=All&var-shard=All&var-method=All)): <img width="1590" alt="image" src="https://user-images.githubusercontent.com/9022011/226750146-e1b5e2f2-6c29-4081-874f-ebc6b99e7746.png">

Gitserver's memory and CPU usage haven't meaningfully changed over the course of the past month (which had gRPC enabled and disable for various periods of time) ([google resource link](https://console.cloud.google.com/kubernetes/statefulset/us-central1-f/cloud/prod/gitserver/details?project=sourcegraph-dev)): 
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/9022011/226750622-c3c8bbff-e1f3-4c92-8171-0bc01f6da581.png">

#### RepoUpdaterService:

- [x] RepoUpdateSchedulerInfo
- [x] EnqueueRepoUpdate
- [x] EnqueueChangesetSync
	- As far as I can tell, the two places that use this method (triggered via [a graphql mutation](https://github.com/sourcegraph/sourcegraph/blob/95994a6e23c34d85dc1f0f737b794dd6b8313ded/client/web/src/enterprise/batches/detail/backend.ts#L450-L462)) aren't referenced by anything anymore: 
		- https://sourcegraph.com/github.com/sourcegraph/sourcegraph@95994a6e23c34d85dc1f0f737b794dd6b8313ded/-/blob/client/web/src/enterprise/batches/close/BatchChangeClosePage.tsx?L41:14-41:34#tab=references 
		- https://sourcegraph.com/github.com/sourcegraph/sourcegraph@95994a6/-/blob/client/web/src/enterprise/batches/repo/BatchChangeRepoPage.tsx?L44:14-44:33#tab=references 
	- I manually tested this by running the following graphQL query on k8s.sgdev.org:
	```graphql
	mutation SyncChangeset($changeset: ID!) {
	  syncChangeset(changeset: $changeset) {
	    alwaysNil
	  }
	}

	{ "changeset": "<-id-of-batch-change-I-created-on-sgdev-org" }
	``` 

	- After running the above query, I saw no errors return. 
	- [Grafana link](https://k8s.sgdev.org/-/debug/grafana/goto/Ufti-nB4z) showing the updated metrics from my test (all of them succeeded, as the [graphQL resolver implementation filters out a number of bad conditions](https://github.com/sourcegraph/sourcegraph/blob/95994a6e23c34d85dc1f0f737b794dd6b8313ded/enterprise/internal/batches/service/service.go#L1043-L1089) before invoking the gRPC client): <img width="747" alt="image" src="https://user-images.githubusercontent.com/9022011/226722353-7467f162-8224-4458-81fe-3c6273046214.png">

- ~[x] SchedulePermsSync~: This [code path](https://github.com/sourcegraph/sourcegraph/blob/7d3ea2780673836a42ee702d4b77c77f5324691a/internal/authz/permssync/permssync.go#L49-L79) no longer goes through repo-updater as of this PR: https://github.com/sourcegraph/sourcegraph/pull/47783. 
- [x] SyncExternalService
- [x] ExternalServiceNamespaces
	- This function normally only runs during the setup wizard experience: https://github.com/sourcegraph/sourcegraph/blob/841c9857097896e9da4e69f45a4220d18cbb21fa/client/web/src/setup-wizard/components/remote-repositories-step/components/code-hosts/github/GithubEntityPickers.tsx#L28-L35
	- I tested this by running the following graphQL query on k8s.sgdev.org:
	```graphql
	  query GetGitHubOrganizations($id: ID, $token: String!) {
        externalServiceNamespaces(kind: GITHUB, url: "https://github.com", token: $token, id: $id) {
            nodes {
                id
                name
            }
        }
    }

		{"token: "<token-contents-here>", "id": "<external-service-id-here">}
	```
	- [Grafana link](https://k8s.sgdev.org/-/debug/grafana/goto/QXOy4ZB4k) showing the updated metrics from my test (one succeeded, one failed as expected): ![Screen Shot 2023-03-20 at 2 24 16 PM](https://user-images.githubusercontent.com/9022011/226469247-92cd5807-ecaa-4830-96c0-b66b0f2c022b.png)

	- 
- [x] ExternalServiceRepositories
	- This function normally only runs during the setup wizard experience: https://github.com/sourcegraph/sourcegraph/blob/841c9857097896e9da4e69f45a4220d18cbb21fa/client/web/src/setup-wizard/components/remote-repositories-step/components/code-hosts/github/GithubConnectView.tsx#L321
	-  I tested this by running the following graphQL queries on k8s.sgdev.org:
		```graphql

		query ValidateAccessToken($token: String!) {
		        externalServiceRepositories(
		            token: $token
		            first: 1
		            query: ""
		            kind: GITHUB
		            excludeRepos: []
		            url: "https://github.com"
		        ) {
		            nodes {
		                id
		            }
		        }
		    }

		{"token: "<token-contents-here>"}
		``` 
			- I ran the above query with both a valid and invalid github.com token, and verified that I got the responses I expected.
			- [Grafana link](https://k8s.sgdev.org/-/debug/grafana/goto/r7Z1nZfVk) showing the updated metrics from my test (one succeeded, one failed as expected): <img width="1650" alt="Screen Shot 2023-03-20 at 2 03 35 PM" src="https://user-images.githubusercontent.com/9022011/226465417-305ee1df-6558-4331-b3f5-c504dd7c7367.png">
			

- [x]  RepoLookup: 

	- [Only runs on sourcegraph.com](https://github.com/sourcegraph/sourcegraph/blob/76c1f9747a453526f70f60cc0fa887d32aaace2c/cmd/frontend/backend/repos.go#L134-L137). 
	- On sourcegraph.com, has a high error rate: ~20% in some cases. 
		- <img width="828" alt="Screen Shot 2023-03-20 at 11 48 55 AM" src="https://user-images.githubusercontent.com/9022011/226437646-5faccef9-13d3-4c16-9d70-c21b7cdbf477.png">
		- [Grafana link](https://sourcegraph.com/-/debug/grafana/explore?orgId=1&left=%5B%22now-7d%22,%22now%22,%22Prometheus%22,%7B%22expr%22:%22(100%20*%20((sum%20by%20(grpc_method)%20(rate(repo_updater_grpc_server_handled_total%7Bgrpc_code!%3D%5C%22OK%5C%22,grpc_method%3D~%5C%22RepoLookup%5C%22,instance%3D~%5C%22(repo-updater-5fd59bc854-ncfbv%7Crepo-updater-6cc6b66ff8-pq76s%7Crepo-updater-6d98868dc-tgtl2%7Crepo-updater-6db578bff-66l8z%7Crepo-updater-6db578bff-kj8fg%7Crepo-updater-7b664bd97-s9zg8%7Crepo-updater-7497bcd6b6-sjpn7%7Crepo-updater-57457c674d-g86px%7Crepo-updater-74999477c8-hds46)%5C%22%7D%5B1m%5D)))%20%2F%20(sum%20by%20(grpc_method)%20(rate(repo_updater_grpc_server_handled_total%7Bgrpc_method%3D~%5C%22RepoLookup%5C%22,instance%3D~%5C%22(repo-updater-5fd59bc854-ncfbv%7Crepo-updater-6cc6b66ff8-pq76s%7Crepo-updater-6d98868dc-tgtl2%7Crepo-updater-6db578bff-66l8z%7Crepo-updater-6db578bff-kj8fg%7Crepo-updater-7b664bd97-s9zg8%7Crepo-updater-7497bcd6b6-sjpn7%7Crepo-updater-57457c674d-g86px%7Crepo-updater-74999477c8-hds46)%5C%22%7D%5B1m%5D)))))%22,%22datasource%22:%22Prometheus%22,%22exemplar%22:true,%22requestId%22:%22Q-fdbf7476-c188-47c8-8469-b2916de8c2eb-0A%22%7D%5D) 
		- However, all errors seem to be related to transient postgres connectivity issues: https://cloudlogging.app.goo.gl/d82xJPr8Ui9rXGu58

####  ZoektConfigurationService:

- [x] SearchConfiguration
- [x] List
- [x] DocumentRanks
- [x] UpdateIndexStatus
- ~RepositoryRank~: N/A, as it doesn't appear to be used anymore: https://sourcegraph.com/github.com/sourcegraph/zoekt@06c1bce6400ae9e5e7e79c9ab885e4c4bc53b30f/-/blob/cmd/zoekt-sourcegraph-indexserver/sg.go?L199:29-199:40#tab=references 

On sourcegraph.com, over a 24 hour period we've haven't seen any errors from any of the above gRPC methods.

https://sourcegraph.com/-/debug/grafana/d/frontend/frontend?orgId=1&from=1678924800000&to=1679097599000

<img width="1658" alt="Screen Shot 2023-03-17 at 2 33 28 PM" src="https://user-images.githubusercontent.com/9022011/226057458-ee2a84a8-0e69-43cf-a61d-184530676bb1.png">

List's[p90 is: ~2.5 seconds](https://sourcegraph.com/-/debug/grafana/explore?orgId=1&left=%5B%221678924800000%22,%221679097599000%22,%22Prometheus%22,%7B%22expr%22:%22histogram_quantile(0.9,%20sum%20by%20(le,%20name,%20grpc_method)%20(rate(frontend_grpc_server_handling_seconds_bucket%7Bgrpc_method%3D~%5C%22List%5C%22,instance%3D~%5C%22(sourcegraph-frontend-6dd9db94fb-bgglb%7Csourcegraph-frontend-6dd9db94fb-jmrjz%7Csourcegraph-frontend-6dd9db94fb-pdxtb%7Csourcegraph-frontend-6dd9db94fb-sl7dq%7Csourcegraph-frontend-internal-6fb554c6cf-qmj9r%7Csourcegraph-frontend-internal-6fb554c6cf-xmt2x%7Csourcegraph-frontend-internal-7fb655fdcc-kb9lk%7Csourcegraph-frontend-internal-7fb655fdcc-kvrmc%7Csourcegraph-frontend-868585955d-9rgjk%7Csourcegraph-frontend-868585955d-dkpfn%7Csourcegraph-frontend-868585955d-dqjgp%7Csourcegraph-frontend-868585955d-stvtz)%5C%22%7D%5B1m%5D)))%22,%22datasource%22:%22Prometheus%22,%22exemplar%22:true,%22requestId%22:%22Q-f1aa50fa-fb6f-4255-9a97-bc840372ed0e-0A%22%7D%5D)

SearchConfiguration's [p90 hovers between ~.3s to 4s (but different argument sizes can explain this)](https://sourcegraph.com/-/debug/grafana/explore?orgId=1&left=%5B%221678924800000%22,%221679097599000%22,%22Prometheus%22,%7B%22expr%22:%22histogram_quantile(0.9,%20sum%20by%20(le,%20name,%20grpc_method)%20(rate(frontend_grpc_server_handling_seconds_bucket%7Bgrpc_method%3D~%5C%22SearchConfiguration%5C%22,instance%3D~%5C%22(sourcegraph-frontend-6dd9db94fb-bgglb%7Csourcegraph-frontend-6dd9db94fb-jmrjz%7Csourcegraph-frontend-6dd9db94fb-pdxtb%7Csourcegraph-frontend-6dd9db94fb-sl7dq%7Csourcegraph-frontend-internal-6fb554c6cf-qmj9r%7Csourcegraph-frontend-internal-6fb554c6cf-xmt2x%7Csourcegraph-frontend-internal-7fb655fdcc-kb9lk%7Csourcegraph-frontend-internal-7fb655fdcc-kvrmc%7Csourcegraph-frontend-868585955d-9rgjk%7Csourcegraph-frontend-868585955d-dkpfn%7Csourcegraph-frontend-868585955d-dqjgp%7Csourcegraph-frontend-868585955d-stvtz)%5C%22%7D%5B1m%5D)))%22,%22datasource%22:%22Prometheus%22,%22exemplar%22:true,%22requestId%22:%22Q-d10c3ac0-8a78-45d9-835b-b34508a3b891-0A%22%7D%5D): 

DocumentRank's [p90 is usually around 50ms](https://sourcegraph.com/-/debug/grafana/explore?orgId=1&left=%5B%221678924800000%22,%221679097599000%22,%22Prometheus%22,%7B%22expr%22:%22histogram_quantile(0.9,%20sum%20by%20(le,%20name,%20grpc_method)%20(rate(frontend_grpc_server_handling_seconds_bucket%7Bgrpc_method%3D~%5C%22DocumentRanks%5C%22,instance%3D~%5C%22(sourcegraph-frontend-6dd9db94fb-bgglb%7Csourcegraph-frontend-6dd9db94fb-jmrjz%7Csourcegraph-frontend-6dd9db94fb-pdxtb%7Csourcegraph-frontend-6dd9db94fb-sl7dq%7Csourcegraph-frontend-internal-6fb554c6cf-qmj9r%7Csourcegraph-frontend-internal-6fb554c6cf-xmt2x%7Csourcegraph-frontend-internal-7fb655fdcc-kb9lk%7Csourcegraph-frontend-internal-7fb655fdcc-kvrmc%7Csourcegraph-frontend-868585955d-9rgjk%7Csourcegraph-frontend-868585955d-dkpfn%7Csourcegraph-frontend-868585955d-dqjgp%7Csourcegraph-frontend-868585955d-stvtz)%5C%22%7D%5B1m%5D)))%22,%22datasource%22:%22Prometheus%22,%22exemplar%22:true,%22requestId%22:%22Q-d6c17435-102b-471a-a3f5-f3618c149a5b-0A%22%7D%5D)

UpdateIndexStatus'[ p90 is usually around 25ms](https://sourcegraph.com/-/debug/grafana/explore?orgId=1&left=%5B%221678924800000%22,%221679097599000%22,%22Prometheus%22,%7B%22expr%22:%22histogram_quantile(0.9,%20sum%20by%20(le,%20name,%20grpc_method)%20(rate(frontend_grpc_server_handling_seconds_bucket%7Bgrpc_method%3D~%5C%22UpdateIndexStatus%5C%22,instance%3D~%5C%22(sourcegraph-frontend-6dd9db94fb-bgglb%7Csourcegraph-frontend-6dd9db94fb-jmrjz%7Csourcegraph-frontend-6dd9db94fb-pdxtb%7Csourcegraph-frontend-6dd9db94fb-sl7dq%7Csourcegraph-frontend-internal-6fb554c6cf-qmj9r%7Csourcegraph-frontend-internal-6fb554c6cf-xmt2x%7Csourcegraph-frontend-internal-7fb655fdcc-kb9lk%7Csourcegraph-frontend-internal-7fb655fdcc-kvrmc%7Csourcegraph-frontend-868585955d-9rgjk%7Csourcegraph-frontend-868585955d-dkpfn%7Csourcegraph-frontend-868585955d-dqjgp%7Csourcegraph-frontend-868585955d-stvtz)%5C%22%7D%5B1m%5D)))%22,%22datasource%22:%22Prometheus%22,%22exemplar%22:true,%22requestId%22:%22Q-198c61d3-26a5-4788-a272-4ed2b85a0cb8-0A%22%7D%5D)

There are no ERROR severity logs related to any of the gRPC Zoekt methods that pop up: https://cloudlogging.app.goo.gl/2s5MBk7eUraGF9Vg8
- Note: I did notice some errors from the [list RPC ](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22cloud%22%0Aresource.labels.container_name%3D%22zoekt-indexserver%22%0Aresource.labels.namespace_name%3D%22prod%22%0Alabels.k8s-pod%2Fapp%3D%22indexed-search%22%20severity%3E%3DDEFAULT%0AtextPayload%3D~%22.*%2528error%7Cfailed%2529.*%22%0AtextPayload%3D~%22.*rpc%20error:.*%22%0A;timeRange=P1D;cursorTimestamp=2023-03-17T02:47:41.773073303Z?project=sourcegraph-dev) that look like `error listing repos: listRepoIDs: rpc error: code = Unknown desc = failed to connect to \`host=127.0.0.1 user=sg database=sg\`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)`. However, a frontend container restart explains this transient error (prometheus wouldn't be able to scrape this failed RPC call, which is why it didn't show up in the earlier graphs)
	-  <img width="926" alt="Screen Shot 2023-03-17 at 3 47 24 PM" src="https://user-images.githubusercontent.com/9022011/226065547-8d6c74c2-5af7-4fc8-8ebb-69bdd1348a64.png">

- [sourcegraph-frontend-internal](https://console.cloud.google.com/kubernetes/deployment/us-central1-f/cloud/prod/sourcegraph-frontend-internal/overview?project=sourcegraph-dev)'s metrics look fine  (server implementation):

	- CPU: ![CPU](https://user-images.githubusercontent.com/9022011/226061258-9cc48414-7270-472e-abeb-cb2422ccdf31.png)
	
	- Memory: ![Memory](https://user-images.githubusercontent.com/9022011/226061269-796af6e4-b1ce-4495-8d0b-dc487e2b3ce9.png)

- [zoekt-sourccegraph-indexserver](https://console.cloud.google.com/kubernetes/service/us-central1-f/cloud/prod/indexed-search-indexer/overview?project=sourcegraph-dev)'s metrics also look fine (client implementation):

	- CPU: ![CPU(1)](https://user-images.githubusercontent.com/9022011/226065877-f61eb2f9-6859-4769-a6d9-24905c430dce.png)

	- Memory: ![Memory(1)](https://user-images.githubusercontent.com/9022011/226065881-9d653218-f9bd-456f-8ad9-4e5c12e60665.png)

- Test functionality:
	- [x] Verify all gRPC services are working as expected for the new release

- Monitor logs for errors/warnings during regular use of Sourcegraph to catch any issues
- Monitor memory/CPU usage of services to ensure no major regressions

**Integration testing**

- Deploy a full Sourcegraph instance with only the gRPC-converted services and validate that core functionality (search, symbol resolve, etc) works as expected
- Flip gRPC on/off via feature flag and ensure results are consistent
- Upgrade/downgrade Sourcegraph with gRPC on/off and ensure no issues

**Performance testing**

- Compare API response times (ingest, search, etc) of gRPC vs REST and track improvements
- Test performance of large repositories and/or large result sets (many search results/symbols) to ensure no major regressions

**Security testing**

Note that we not built any mTLS support for gRPC in this release. For now, our gRPC communication is unencrypted in the same way
that our existing REST communication is unencrypted.

Other than that, the following is worth considering:

- Ensure existing auth enforcement is preserved (search access control, actor logic, etc)
- Search for common gRPC vulnerabilities (DoS, etc) and ensure changes are not vulnerable

**Usability testing**

- No user-facing changes, so no usability testing required

**Compatibility testing**

- Deploy to all infra/cloud environments (dev clusters, etc) and ensure functionality is preserved
- Ensure services start/stay running and no errors are logged

## QA Checklist

1. **Have you made any infra related changes to environment variables, new services, or deployment methods that could affect customers?**

   - [x] No infra changes required (multiplexing gRPC on existing HTTP ports)

   For starship, we're in a transitional period where not all services / methods have been converted to use gRPC. During this time, the
   gRPC servers are multiplexed on the same ports as the existing HTTP servers so that no Kubernetes service configuration (or other firewall) changes are required.

   There is one exception to this. If users are using a firewall (ex: a service mesh) that's configured to block HTTP/2 traffic or any traffic that's not plain text, they might have to add an exception to their firewall

2. **Which environments have the changes been tested on?**

   - [x] sgdev clusters (k8s, etc)
   - [x] sourcegraph.com
   - [x] (other environments if applicable)

3. **Experimental features have been marked and behind a feature flag?**

   - [x] Yes, gRPC can be enabled/disabled via feature flag

     - For most services, gRPC communication can be enabled via:

       ```jsonc
       {
         "experimentalFeatures": {
           "enableGRPC": true
         }
       }
       ```

     - For indexed-search (zoekt), an environment variable needs to be set to enable gRPC (since it doesn't obtain its configuration from Sourcegraph's database)

       - For Kubernetes, that can be done by setting the `GRPC_ENABLED=1` environment variable in the `base/indexed-search/indexed-search.StatefulSet.yaml` configuration YAML. Other deployment targets will need to update that environment variable in a similar manner.

         ```diff
         diff --git a/base/indexed-search/indexed-search.StatefulSet.yaml b/base/indexed-search/indexed-search.StatefulSet.yaml
         index 370b24db8a1..d3fa36354aa 100644
         --- a/base/indexed-search/indexed-search.StatefulSet.yaml
         +++ b/base/indexed-search/indexed-search.StatefulSet.yaml
         @@ -109,8 +109,10 @@ spec:
                     value: "10000"
                     - name: GOOGLE_CLOUD_PROFILER_ENABLED
                       value: "1"
         +           - name: GRPC_ENABLED
         +             value: "1"
                 # Upstream the image is "index.docker.io/sourcegraph/search-indexer"
                 image: sourcegraph/zoekt-indexserver:0.0.0-20230308131753-939eb52f3486
                 terminationMessagePolicy: FallbackToLogsOnError
                 ports:
                     - containerPort: 6072
         ```

4. **Completed entry to release post.**
   - [ ] Yes (will complete when testing is done)
   - [x] No

**Comment by ggilmore** [comment]
Completed for 5.0 release.
