### ISSUE TITLE
Add visual indication of tooltip pinning

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#4938]
The full context can be found [in this Slack conversation](https://sourcegraph.slack.com/archives/C07KZF47K/p1563353869150100).

The short version is: I think it would be really valuable to have _any_ visual indication of tooltip pinning. As as user it's confusing that "clicking" changes the behavior of when a tooltip shows up in a slight and subtle way without giving any indication. 

@christinaforney: I assigned this ticket to you, because I'm not sure who else to assign this to. And I'd love to get your opinion on this and the whole Slack thread mentioned above :)

**Comment by felixfbecker** [comment]
I have a solution for this, but is much harder to implement without https://github.com/sourcegraph/sourcegraph-go/issues/75 being fixed. cc @chrismwendt 

https://sourcegraph.slack.com/archives/C89KCDK5J/p1563883526000700

**Comment by chrismwendt** [comment]
Removing use of `__backcompatContents` in https://github.com/sourcegraph/sourcegraph-go/pull/88

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
