### ISSUE TITLE
Support searching across all branches of all repositories

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#4948]
Requested by:

* https://app.hubspot.com/contacts/2762526/company/407948923

A customer has the following use case:

> We are trying to find out which repositories are using a particular module. Some repos are adopting this module, but that's an ongoing task, which means actual usage of the module lives in a feature branch (non-master). We want to know that a particular repo is using the module, even if usage is not in master yet.

To cover this use case, $CUSTOMER has suggested adding the ability to search across all repositories over all named branches.

Alternatively, diff search may also satisfy this need. However, I think we would need to invest more into making diff search scale. For example, global diff searches on k8s.sgdev.org currently timeout.

This is more of an "offline", rather than "real time", use case, so some amount of latency in the search query is tolerable here.

**Comment by dadlerj** [comment]
Diff search (`type:diff`) does work, but only if you specify `@*refs/heads` at the end of the `repo:` field, e.g. https://sourcegraph.sgdev.org/search?q=repo:sourcegraph/%40*refs/heads+%22/.api/lsif/upload%22+type:diff+after:%221+day+ago%22 (which finds the commit in https://github.com/sourcegraph/sourcegraph/pull/4937)

Otherwise diff search only searches history in `master`

**Comment by beyang** [comment]
From the user:

>  I like your suggestion about searching across diffs, but that will probably give us all occurrences, even if they've been undone. So in my case, if someone used "foo" module in the past, and then got rid of it - I'd still see it in the diff results, which may be a bit misleading.

**Comment by dadlerj** [comment]
Only vaguely related, but I often wished I could do a `type:diff-added` or `type:diff-removed` (or whatever syntax makes sense here :) )
cc @christinaforney

**Comment by keegancsmith** [comment]
> This is more of an "offline", rather than "real time", use case, so some amount of latency in the search query is tolerable here.

Does this mean something like the src-cli would be an acceptable interface to this feature?

**Comment by christinaforney** [comment]
> Does this mean something like the src-cli would be an acceptable interface to this feature?

Yes, the src-cli or the API are acceptable. I believe the API is the current interface in use for this customer.

**Comment by sqs** [comment]
Partially fixed by #7459. Support for searching all branches (without needing to list each one in the query) is coming soon.

**Comment by GaetanoPiazzolla** [comment]
I'm developing a tool to search in all remote and local repos: https://github.com/GaetanoPiazzolla/git-search
