### ISSUE TITLE
OOB migration validation is disabled, why?

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#49490]
https://github.com/sourcegraph/sourcegraph/blob/1e088ffcbe304ea02940a2279b1ef22d177413a4/internal/singleprogram/singleprogram.go#L120-L125

**Comment by slimsag** [comment]
I'm actually afraid this means OOB migrations are not running at all in App right now. I'd be keen for any evidence this is not the case.

Still fixable post-starship, but scary..

**Comment by unknwon** [comment]
From my understanding, the fact we are using super large versions (dates) would effectively _not_ run any deprecated (expected) _and_ about to be deprecated (unexpected) OOBMs. An example of the latter case is, an OOBM is added in 5.0, set to be deprecated in 5.2. In normal upgrades, 5.0 and 5.1 would both run it, but because App has such large versions, it would be deprecated right away because `2023.0M.DD` is well beyond 5.2.

**Comment by slimsag** [comment]
Merging into #48940
