### ISSUE TITLE
LSIF repository verification: support more code hosts

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#4967]
Currently, only GitHub repositories can be verified.

From https://github.com/sourcegraph/sourcegraph/pull/4937#discussion_r306933015

**Comment by unknwon** [comment]
Do you think it would be more accurate to use the term "external service" instead of "code host"?

**Comment by chrismwendt** [comment]
I heard that "external service" could be confused with Datadog, Sentry, etc.

**Comment by unknwon** [comment]
Hmm... we really should have a session to have clear definition of which name means which. Then make a document.

**Comment by scalabilitysolved** [comment]
I think this can be deleted, can you confirm @efritz ?

**Comment by efritz** [comment]
Right now _anyone_ can upload LSIF dat for any non-github code host on cloud. We should probably either lock it down for others or add auth for bitbucket et al.

**Comment by macraig** [comment]
@efritz what's the effort estimation for each of those options? Looks like a big gap in non-github code hosts at the moment.

**Comment by efritz** [comment]
@scalabilitysolved We'd need (priority-ordered) set of issues for each code host, which would basically replicate [this code](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/internal/codeintel/httpapi/auth_github.go#L19:6) with another codehost's authorization API endpoints. We just need to know, given some code host-specific token, if that token is valid for the repo they're trying to upload for.

Effort depends on complexity of API.

**Comment by scalabilitysolved** [comment]
@macraig I'm going to close this out, if you have a product timeline of specific code host support we can add those.

**Comment by macraig** [comment]
Adding https://github.com/sourcegraph/sourcegraph/issues/31437

**Comment by ericremoreynolds** [comment]
Hello, I have a self-hosted sourcegraph instance, to which I'd like to upload a non-github/gitlab LSIF. I tried setting lsifEnforceAuth = false, but I still get:

```
422 (failed to authorize request: verification is supported for the following code hosts: github.com, gitlab.com - please request support for additional code host verification at https://github.com/sourcegraph/sourcegraph/issues/4967)
```

Is there some way to disable this check on my self-hosted instance?

Thanks!

**Comment by rakeshjosh2003** [comment]
Hi,  one of the customers has requested to add support for the Phabricator code host.

[Link to Slack thread with customer interest](https://sourcegraph.slack.com/archives/C01134Y4D5H/p1681856767360349)
