### ISSUE TITLE
Debt: Clean up cloud_default and related siblings

### ISSUE THREAD

**Issue by indradhanush** [sourcegraph/sourcegraph#49671]
**What is cloud_default?**

`cloud_default` is a dotcom only flag to indicate default code host connections for public cloud code hosts and is only supported for GitHub.com and GitLab.com. While the purpose for using this is dotcom only, we [don't have this enforced](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@f8316114f1c52ee60a6c261dba17dedaa896b2a4/-/blob/cmd/frontend/internal/cli/config.go?L255-271) in our code at the moment. (I was able to set `cloudDefault: true` for a GitHub code host connection locally with `sg start` which is a non dotcom enterprise mode). But this is not a big deal - but nevertheless one of many papercut UX problems.

🤡 Fun fact: At some point we transitioned to writing this value manually to the database, because on dotcom:

1. GitHub.com: Uses the deprecated flag `cloudGlobal: true`, which is unused config and has no effect
1. GitLab.com: Does not any flag

But both GitHub.com and GitLab.com public code host connections on dotcom have `cloud_default = TRUE` in the database.

**How does it affect sync?**

For code hosts with `cloud_default = TRUE`, we skip scheduling syncs for them. Triggering a sync manually from the site admin will also not work and returns a helpful message: Cloud default external services can't be synced

**Recommendations**

- [ ] Remove `cloudGlobal` flag
- [ ] Deprecate `cloudDefault` for the next release
- [ ] Remove `cloudDefault` from the code host config schema in the release after that
- [ ] Document the usage of `cloud_default` DB column and how and where it's used

**Priority**: Low

/cc @ryphil @mrnugget

**Comment by dee-d-dev** [comment]
I am working on this

**Comment by chrishalbert** [comment]
@dee-d-dev - Are you still working on this? If not, I'd like to take this on. Thanks
