### ISSUE TITLE
blobstore: Frequently crashing local stack and annoying multiple devs

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#49865]
We're seeing frequent crashes in dev environments due to `blobstore` not behaving in a consistent way.

```
[    sourcegraph] FATAL sourcegraph svcmain/svcmain.go:184 failed to start service {"service": "precise-code-intel-worker", "error": "initializing upload store: failed to create bucket: retry quota exceeded, 0 available, 5 requested"}
```

We need to either find out why this is happening in dev environments (and there are also similar error messages in some Cloud instances as well), or finish the Go port.

**Comment by slimsag** [comment]
App uses the Go version of blobstore. I wouldn't expect this to happen in either version (obviously), but it's especially surprising to hear about it happening in the new Go version.

Whatever is causing this vs. the standard dev env issue, will be different.

How can I reproduce this with the app version?
