### ISSUE TITLE
Explicit Permissions - Repository status page doesn't reflect explicit permissions

### ISSUE THREAD

**Issue by DaedalusG** [sourcegraph/sourcegraph#49888]
- **Sourcegraph version:** v4.5.x ->
- **Platform information:**  all 

#### Steps to reproduce:

1. Set up a Sourcegraph instance with [explicit permissions](https://docs.sourcegraph.com/admin/permissions/api#explicit-permissions-api)
2. Restrict read permissions on a repo for some users -- and then navigate to the repos permissions page.
3. Observe that the page returns messages that indicate all users have access to the repo --
Here a public github repo:
<img width="958" alt="Screenshot 2023-03-22 at 3 15 48 PM" src="https://user-images.githubusercontent.com/13024338/227127706-68296a76-c33a-4cc9-8cd2-275004f09009.png">
Here a private github repo:
<img width="980" alt="Screenshot 2023-03-22 at 3 15 13 PM" src="https://user-images.githubusercontent.com/13024338/227127725-6b98f4d3-8c9d-4b50-86bc-93a729aa2747.png">

#### Expected behavior:
This page should accurately reflect the permissions granted manually via the [authz package](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@c982f23/-/blob/cmd/frontend/globals/globals.go?L86-108)

#### Minor Description

The UI is makinga query called [RepoPermissionsInfo](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/enterprise/repo/settings/backend.ts?L4-11):
```graphql
{
  node(id: "UmVwb3NpdG9yeToy") {
    __typename
    ... on Repository {
      permissionsInfo {
        syncedAt
        updatedAt
        unrestricted
      }
    }
  }
}
```
^^ this is a boiled down version of the query with an example repo graphQL ID

The graphQL endpoint that actually reflects the `PermissionsUserMapping` is separate --
<img width="429" alt="Screenshot 2023-03-22 at 11 53 49 PM" src="https://user-images.githubusercontent.com/13024338/227129075-97eb0ad0-921f-4a8c-bdee-fb947d68fbee.png">

As such the UI isn't reflecting permissions controlled by the [explicit/permissionsUserMapping](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@c982f23/-/blob/cmd/frontend/globals/globals.go?L86-108) auth path.

#### Current Source of Truth
The graphqQL `authorizedUserRepositories` endpoint will still return an accurate reflection of explicitly set permissions

/cc @sourcegraph/source/iam

**Comment by kopancek** [comment]
We have a similar bug on the user permissions side. We now have the User settings -> Permissions page, which shows various information about permissions, but explicit permissions are not taken into account there.

A proper fix here would probably be to fix the underlying graphql query to `permissionsInfo` or switch the UI to use a different query.

**Comment by mrnugget** [comment]
@pjlast can you investigate?

**Comment by pjlast** [comment]
@mrnugget yeah this is fixed, can confirm
