### ISSUE TITLE
Run `perms_syncer_worker` in enterprise `worker` process

### ISSUE THREAD

**Issue by sashaostrikov** [sourcegraph/sourcegraph#49907]
Once we have distributed rate limiting (meaning: we can send requests to code hosts from outside repo-updater) we can run `perms_syncer_worker` not in [repo-updater](https://github.com/sourcegraph/sourcegraph/blob/862a564c4a4c9cb8a003518941f239738295b71e/enterprise/cmd/repo-updater/shared/shared.go#L80-L82), but as a `worker` process.

**Comment by eseliger** [comment]
Done!
