### ISSUE TITLE
Search contexts: creating a JSON-based context fails

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#49978]
Creating a JSON-based search context fails with "you must provide a `first` or `last` value to properly paginate"

![image](https://user-images.githubusercontent.com/12631702/227599778-c84876f3-4472-4510-bf63-634b5514040b.png)

**Comment by mibali** [comment]
Also, a UI improvement,  If I as a user just skip that radio button, click `Add repository` and fill in the name of the repository, that radio button does not switch automatically. I would expect it to switch automatically as that is quite a common UX pattern.




![image](https://user-images.githubusercontent.com/111276665/227947670-8f7af216-2f58-4552-92e7-e8913fd0f479.png)

**Comment by mibali** [comment]
Also, a UI improvement,  If I as a user just skip that radio button, click `Add repository` and fill in the name of the repository, that radio button does not switch automatically. I would expect it to switch automatically as that is quite a common UX pattern.




![image](https://user-images.githubusercontent.com/111276665/227947670-8f7af216-2f58-4552-92e7-e8913fd0f479.png)

**Comment by gl-srgr** [comment]
> Also, a UI improvement, If I as a user just skip that radio button, click Add repository and fill in the name of the repository, that radio button does not switch automatically. I would expect it to switch automatically as that is quite a common UX pattern.

Spun off to separate issue https://github.com/sourcegraph/sourcegraph/issues/50086
