### ISSUE TITLE
Searcher: goroutine leak

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#49987]
There appears to be a slow goroutine leak in searcher. 

<img width="1422" alt="Screenshot 2023-03-24 at 19 16 25" src="https://user-images.githubusercontent.com/12631702/227674900-056adc6d-613c-4e43-91cb-389ccd964849.png">

I pulled a goroutine dump from the most clearly affected pod:
[goroutines.txt](https://github.com/sourcegraph/sourcegraph/files/11067585/goroutines.txt)

I did a little bit of massaging of that output to get a summary of the top line of each stacktrace:

```
   1 github.com/facebookgo/muster.(*Client).worker
   1 github.com/getsentry/sentry-go.(*HTTPTransport).worker
   1 github.com/sourcegraph/log/internal/sinkcores/sentrycore.(*worker).consume
   1 github.com/sourcegraph/sourcegraph/cmd/searcher/shared.shutdownOnSignal
   1 github.com/sourcegraph/sourcegraph/internal/conf.(*client).continuouslyUpdate
   1 github.com/sourcegraph/sourcegraph/internal/endpoint.(*Map).sync
   1 github.com/sourcegraph/sourcegraph/internal/service/svcmain.run
   1 go.opencensus.io/stats/view.(*worker).start
   1 go.opentelemetry.io/otel/sdk/trace.(*batchSpanProcessor).processQueue
   1 google.golang.org/grpc/internal/transport.(*Stream).waitOnHeader
   1 os/signal.signal_recv
   1 runtime/pprof.writeGoroutineStacks
   1 sync.runtime_Semacquire
   2 github.com/sourcegraph/sourcegraph/internal/limiter.(*MutableLimiter).do
   3 time.Sleep
   6 github.com/sourcegraph/sourcegraph/internal/conf.(*client).Watch.func1
  10 github.com/sourcegraph/conc/pool.(*Pool).worker
  12 google.golang.org/grpc.(*ccBalancerWrapper).watcher
  12 google.golang.org/grpc/internal/transport.(*controlBuffer).get
 101 net/http.(*persistConn).writeLoop
 148 internal/poll.runtime_pollWait
 663 os/exec.(*Cmd).watchCtx.func1
```

There are three suspicious stacks there. Below is a copy of representative stacktraces for each of them out of the full dump:
```
goroutine 16255727 [chan send, 494 minutes]:
os/exec.(*Cmd).watchCtx.func1()
	os/exec/exec.go:665 +0x198
created by os/exec.(*Cmd).watchCtx
	os/exec/exec.go:647 +0x8e

goroutine 22778798 [IO wait]:
internal/poll.runtime_pollWait(0x7f307f80ff08, 0x72)
	runtime/netpoll.go:305 +0x89
internal/poll.(*pollDesc).wait(0xc0065e1b80?, 0xc025b9f000?, 0x0)
	internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0065e1b80, {0xc025b9f000, 0x1000, 0x1000})
	internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc0065e1b80, {0xc025b9f000?, 0x406231?, 0x4?})
	net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc00e9241d8, {0xc025b9f000?, 0x0?, 0x0?})
	net/net.go:183 +0x45
net/http.(*persistConn).Read(0xc028c19e60, {0xc025b9f000?, 0xc02f2f11a0?, 0xc011dded30?})
	net/http/transport.go:1929 +0x4e
bufio.(*Reader).fill(0xc00839c1e0)
	bufio/bufio.go:106 +0xff
bufio.(*Reader).Peek(0xc00839c1e0, 0x1)
	bufio/bufio.go:144 +0x5d
net/http.(*persistConn).readLoop(0xc028c19e60)
	net/http/transport.go:2093 +0x1ac
created by net/http.(*Transport).dialConn
	net/http/transport.go:1751 +0x173e

goroutine 22779713 [select]:
net/http.(*persistConn).writeLoop(0xc0020679e0)
	net/http/transport.go:2392 +0xf5
created by net/http.(*Transport).dialConn
	net/http/transport.go:1752 +0x1791
```

The biggest and most concerning one to me is the `os.Exec` one. I'm like 90% confident this is from structural search. If anyone wants to look at this, I would start by checking that we read/write stdout/stdin to completion on context cancellation. Alternatively...we could just disable structural search. 

A trick that has helped me track down goroutine leaks previously is adding `GODEBUG=tracebackancestors=10` to the environment. This will make the [pprof goroutines page](https://sourcegraph.com/-/debug/proxies/searcher-10.164.10.173/debug/pprof/goroutine?debug=3) list the ancestor stacks for each goroutine, which is very useful when trying to figure out where very common calls like `dialConn` are coming from.

**Comment by camdencheek** [comment]
(sorry batchers, there was a batch in the stacktrace 🤦 )

**Comment by keegancsmith** [comment]
I agree this is probably comby since I don't think we use sub processes anywhere else in searcher. I eyeballed the code and fairly confident this is the root cause: https://github.com/sourcegraph/sourcegraph/pull/50034

**Comment by camdencheek** [comment]
Goroutines in Searcher seem to have stabilized, so I think we can close this. Thanks @keegancsmith!

<img width="2466" alt="Screenshot 2023-04-03 at 10 06 48" src="https://user-images.githubusercontent.com/12631702/229565905-b33ecb65-2e96-43fa-a3b5-9fa8e2bb74ce.png">
