### ISSUE TITLE
C# code intelligence

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#5]
Support C# on Sourcegraph.

**Comment by jbaehr** [comment]
I was somewhat confused to see that C# code intelligence is *not* supported. On the [homepage](https://about.sourcegraph.com/#code-intelligence) there is a nice little screen shot (apparently from langserver.org) having lots of green tick marks for C#.

What is the state of this? Does it work if the corresponding language server is setup manually or is specific support from within sourcegraph required?
When I try e.g. https://sourcegraph.com/github.com/apache/logging-log4net/-/blob/src/Core/ILogger.cs#L43:19$references
I get the following message:
> Error getting local references: Xlang server proxy: no server registered for mode "cs"

Is there a way to perform this registration in a self-hosted environment with the current version?

**Comment by ruhullahshah** [comment]
@keegancsmith 

Hi,

I am launching a C# langserver using `lsp-adapter` on Windows and updated the `langservers` config as stated in `lsp-adapter` documentation. However, I see no communication between the `lsp-adapter` and my Sourcegraph instance. I expected Sourcegraph to check the adapter heartbeat or any sort of communication notifying the user of any errors on Sourcegraph console.  Any suggestions?
Attaching related files.

Thanks
[lsp-adapter-screenshot.zip](https://github.com/sourcegraph/issues/files/1980312/lsp-adapter-screenshot.zip)

**Comment by ggilmore** [comment]
Hello @ruhullahshah, I noticed in your Sourcegraph config that the language is defined as `"C#"`. We use the same terminology as linguist to identify languages (see https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L490-L504), so could you try using `"csharp"` instead of `"C#"` in your configuration?

**Comment by chrismwendt** [comment]
@ruhullahshah The language in the config should be `cs`:

```diff
     {
       "address": "tcp://10.100.10.100:8080",
-      "language": "C#"
+      "language": "cs"
     },
```

But, **if you are running Sourcegraph in a Docker container**, you'll need to run the brand new [sourcegraph/codeintel-csharp](https://hub.docker.com/r/sourcegraph/codeintel-csharp/):

```
docker run --rm --name csharp --network lsp sourcegraph/codeintel-csharp
```

and adjust your config:

```
    {
      "address": "tcp://csharp:8080",
      "language": "cs"
    },
```

Then try opening a file (such as [Desugarer.cs](http://localhost:7080/github.com/adamreeve/semver.net/-/blob/src/SemVer/Desugarer.cs)) and you should see hover tooltips on variables and be able to go-to-def/find-refs.

Let us know if that works, or if you run into trouble - we're happy to help get you up and running!

**Comment by ruhullahshah** [comment]
Thanks everyone for your suggestions and support. I am able to communicate with the sourcegraph/codeintel-csharp from my Sourcegraph instance

 I am able to `Find References` & `Go to definition` in a locally cloned C# project. Communication & Cloning over HTTPS/SSH is still broken in my Sourcegraph instance (https://github.com/sourcegraph/issues/issues/69)

I have a question about the most critical use case for us:

1) I locally cloned two C# projects wherein one project(consumer) refers to the symbols of the other(provider). However, on performing `Find references` on a symbol from provider project in the consumer project, I see an error

`14:21:01      lsp-proxy | ERROR textDocument/xdefinition failed: jsonrpc2: code -32601 message: Unhandled method textDocument/xdefinition {"error":"jsonrpc2: code -32601 message: Unhandled method textDocument/xdefinition","id":1,"method":"textDocument/xdefinition","mode":"cs","repo":"CommonInterfacesForPlatformAndGui","rev":"8ccccfb087df3f14c948dd0919770e2e1b526ede","session":""}`

Does this mean that C# language server needs to implement this method to support cross-referencing?

2) I wanted to know if the language server has the same view about the location of cloned repos as Sourcegraph?

**Comment by felixfbecker** [comment]
Hi @ruhullahshah, you are correct with your guess, to support cross-repository code intelligence, the language server needs to implement some extension methods that expose additional information. They are specified [here](https://github.com/sourcegraph/language-server-protocol/blob/master/extension-workspace-references.md), we are actively working on improving the documentation around this right now.

I am not sure what you mean with your second question, would you mind elaborating? The repository is checked out on the file system in a folder and the language server initialized with the `rootUri` pointing to that folder.

**Comment by chrismwendt** [comment]
To add to what @felixfbecker said, we are actively working on both adding many off-the-shelf language servers in the [lsp-adapter](https://github.com/sourcegraph/lsp-adapter) project ([sourcegraph/codeintel-csharp](https://hub.docker.com/u/sourcegraph/codeintel-csharp) is one of them), as well as indicating what features each language server supports. The Sourcegraph UI will better communicate the capabilities of these experimental language servers in the next release, so stay tuned!

**Comment by ruhullahshah** [comment]
@felixfbecker Do you guys have any idea as to when Omnisharp plans to add cross-repository code-intelligence in the C# langserver which would then be subsequently available in Sourcegraph? Also the second question of my last comment is answered now. Thanks for the explanation.

@chrismwendt  Thanks. Sure, we will keep an eye out on that.

**Comment by felixfbecker** [comment]
@ruhullahshah Looking at the commit activity of the C# langserver my guess is that it would have to come from a community contribution.

**Comment by chrismwendt** [comment]
Experimental C# support has been shipped in Sourcegraph 2.8! Check out the blog post https://about.sourcegraph.com/blog/code-intelligence-for-more-languages-and-lsp-language-server-protocol-support

![image](https://user-images.githubusercontent.com/1387653/40390312-a6141484-5dc9-11e8-9a04-64107f727db9.png)

Thanks go to the [OmniSharp/omnisharp-node-client](https://github.com/OmniSharp/omnisharp-node-client) project for providing the language server.

**Comment by ruhullahshah** [comment]
That's great news :) I gave 2.8 a shot but I faced some problems with the C# support though

  lsp-proxy | INFO  Removed serverProxyConn {"mode":"cs","repo":"my-repo","rev":"be84d6326183914b3586cd5acc0be6767f5b0924","session":"","stats":{"Created":"2018-05-23T12:44:10.747093Z","Last":"2018-05-23T12:44:10.747093141Z","TotalCount":0,"Counts":{},"TotalFinishedCount":0,"TotalErrorCount":0,"ErrorCounts":{}}}
sourcegraph    | 12:44:15      lsp-proxy | ERROR textDocument/hover failed: other goroutine failed to connect and initialize LSP server: dial tcp: i/o timeout {"error":"other goroutine failed to connect and initialize LSP server: dial tcp: i/o timeout","id":1,"method":"textDocument/hover","mode":"cs","repo":"my-repo","rev":"be84d6326183914b3586cd5acc0be6767f5b0924","session":""}
sourcegraph    | 12:44:20      lsp-proxy | INFO  Removed serverProxyConn {"mode":"cs","repo":"my-repo","rev":"be84d6326183914b3586cd5acc0be6767f5b0924","session":"","stats":{"Created":"2018-05-23T12:44:15.753903898Z","Last":"2018-05-23T12:44:15.753904001Z","TotalCount":0,"Counts":{},"TotalFinishedCount":0,"TotalErrorCount":0,"ErrorCounts":{}}}
sourcegraph    | 12:44:20      lsp-proxy | ERROR textDocument/hover failed: dial tcp: i/o timeout {"error":"dial tcp: i/o timeout","id":1,"method":"textDocument/hover","mode":"cs","repo":"code.rsint.net/contest/Applications/TTP","rev":"be84d6326183914b3586cd5acc0be6767f5b0924","session":""}

**Comment by chrismwendt** [comment]
@ruhullahshah Please create a new issue and include:

- The command you ran to start up Sourcegraph
- The `langservers` section of your site configuration
- The output of `docker inspect sourcegraph csharp`

It sounds like Sourcegraph is unable to communicate with the C# language server, which points to a networking problem.

**Comment by ruhullahshah** [comment]
@chrismwendt 

The problem was the langservers part, I updated the address from tcp://csharp:8080 to:
      "address": "tcp://cs:8080",
      "language": "cs"

Thank you for the pointers.

**Comment by chrismwendt** [comment]
@ruhullahshah My apologies - you ran into a bug where the default hostname was set to `csharp`, but it should be `cs`. The fix is in the latest `docker pull sourcegraph/server:insiders` build https://hub.docker.com/r/sourcegraph/server/

**Comment by ruhullahshah** [comment]
@chrismwendt  No problems :) Thanks for the follow up. After renaming, we are doing good for now

**Comment by Hawxy** [comment]
Any updates to this? Looks like the omnisharp node client has completely stopped development.

**Comment by sqs** [comment]
No updates on C# specifically. We plan to work on language support for languages other than JS/TS/PHP/Python/Go/Java in December 2018 (see roadmap: https://docs.sourcegraph.com/dev/roadmap#december-2018). That is the earliest we would be able to address this on our team. But we are releasing big improvements to *how* language support is built in Sourcegraph in early Nov and even more in early Dec, so it's possible someone (you?) could contribute better C# support sooner than that.

**Comment by chrismwendt** [comment]
C# code intelligence has been added in Sourcegraph 3.0 :tada:

https://about.sourcegraph.com/blog/sourcegraph-3.0#code-intelligence-for-all-languages

[Try it out](https://sourcegraph.com/github.com/drewnoakes/string-theory@be5a1db710147a72ffffdcf6494970e7ced1dcb2/-/blob/StringTheory/UI/HomePage.cs#L52:44) on Sourcegraph.com:

![image](https://user-images.githubusercontent.com/1387653/52601835-1ef3dd00-2e15-11e9-9ef0-5b1c623f9d54.png)
