### ISSUE TITLE
Sourcegraph Editor: Provide richer comment support

### ISSUE THREAD

**Issue by msorens** [sourcegraph/sourcegraph#50]
- Issue type: **feature request**
- Sourcegraph version: **Sourcegraph Editor 1.21.0**
- OS Version: **MacOS High Sierra**
- Docker version: **NA**

Description:
I had originally jumped at using Sourcegraph Editor because of its capability to do code reviews in VSCode rather than through Github.com. Ironically, that is not the main thing I use it for, though, because its support for all aspects of commenting is nice, but not on par with Github.com. I hope some of these suggestions might resonate:

1. Gotta fix that bug where opening then closing a comment makes the comment disappear in the IDE. :-(.
2. In Github.com the entire PR (i.e. all files) is linear, on a single page. But in VSCode, one views one file at a time, there needs to be a way to track existing comments that I have entered in the current PR, but not yet submitted. Ideally, there should be a comment count next to each file name in the list of files in the Review pane. In day to day work, one is often interrupted. If I come back to a PR I had started looking at before, I need a way to know if I have any pending comments that I have not yet submitted.
3. Similarly, there needs to be a way to track pre-existing comments in the current PR, both from me and from others. I often want to skim through what others have written commented on first, before digging into the code. So I would amend (2) to suggest two numbers next to each file, say a blue number for pre-existing comments and a red number for my not-yet-submitted comments.
4. Further still on the same point, just like Github, when viewing the list of PRs in the Review pane, there should be a count of comments. (And again, I would suggest two counts, one for pre-existing comments and one for comments I have not yet submitted.)
5. It would be helpful to be able to execute a search against the contents of all existing comments within the current PR. (Say I wanted to copy something from some other comment I put on a different file, for example.)
6. You have the avatars for existing reviewers in the list of PRs but that should be enhanced to show who has approved, commented, or requested changes. (Perhaps with different colored borders around the avatars, or even better, a tiny green checkmark or tiny red x in the corner of the avatar.)
7. I would like to see a way to preview a comment (as in Github.com). Which also means, that there needs to be able to display a comment as "rich text", of course.
8. I would like to see some simple editing controls for bold, italic, code, etc. (as in Github.com).
9. I would like a way to attach an icon like in Github.com. I, and my colleagues, like to put a "thumbs_up" icon as a quick way to let a reviewer know that we have acknowledged their comment.
10. I would like a "pop-out" view of comments in a file so one can view the comments, but not have them interfere with viewing the code. A good implementation of this is in Visual Studio (i.e. not VScode) when using TFS. Comments appear in a separate panel off to the side. You could then superimpose an arrow perhaps. Alternately, when one clicks on a comment in this panel, then it highlights the line of code it is attached to.
11. Would like to see support for, when typing "@", a list of colleagues names are provided as you type (as in Github.com).
12. Would be helpful to be able to edit comments not yet submitted.

A couple things I really like about your comment support:
1. The little word-bubble icon that appears near the left edge of code lines containing a comment.
2. The vertical bar next to the vertical scroll bar showing ticks for the whole file, indicating where in the file there are comments.

**Comment by sqs** [comment]
@msorens Thank you for the feedback! Very helpful to hear.
