### ISSUE TITLE
Add git clones/fetches to Outbound Requests dashboard.

### ISSUE THREAD

**Issue by varsanojidan** [sourcegraph/sourcegraph#50022]
The Outbound Requests dashboard is a great tool to help debug issues regarding outbound requests from Sourcegraph. However, at the moment it only keeps track of HTTP requests being made in Sourcegraph, I think we should also include git requests here, starting with git clones/fetches.

/cc @ryphil @mrnugget

**Comment by mrnugget** [comment]
I think this might be halfway-fixed by git debuggability work that @BolajiOlajide
