### ISSUE TITLE
Be able to filter out empty repos from code hosts

### ISSUE THREAD

**Issue by scjohns** [sourcegraph/sourcegraph#50026]
#### Feature request description

Have the option in external service configs to filter our empty repos. This will remove clutter from customer instances without the need to manually find and exclude these repos, plus it will be dynamic for if a repo ceases to be empty or becomes empty because it is being deprecated

#### Is your feature request related to a problem? If so, please describe.

https://github.com/sourcegraph/accounts/issues/3441 has a number of empty repos that should be excluded and could cause errors in the GitLab sync jobs, but has no easy way to automatically exclude empty repositories.

#### Describe alternatives you've considered.

Manually excluding all empty repos, but it isn't dynamic and would be a pain to keep updated if old repos are deprecated and emptied out (content moved) or if someone is testing and a repo is created, but doesn't ultimately add content to it.

#### Additional context

GitLab Projects API has an `empty_repos` field, which might be easily leveraged to help with this. Not sure about other code hosts equivalent fields.

/cc @ryphil @mrnugget

**Comment by scjohns** [comment]
PR for GitLab [here](https://github.com/sourcegraph/sourcegraph/pull/49982)

**Comment by varsanojidan** [comment]
Issue resolved here: https://github.com/sourcegraph/sourcegraph/pull/49982
