### ISSUE TITLE
Add LSIF support to sourcegraph/typescript

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#5008]
- ✅ sourcegraph/go has LSIF support as of https://github.com/sourcegraph/sourcegraph-go/pull/85
- ❌ sourcegraph/typescript doesn't have LSIF support yet
- ✅ All other language extensions (including sourcegraph/python) have LSIF support by virtue of being generated from https://github.com/sourcegraph/sourcegraph-basic-code-intel

Spec:

- Fallback logic is in this order: 1. LSIF 2. language server 3. basic-code-intel (this follows other language extensions)
- Doesn't change UX for existing Sourcegraph instances that have no LSIF data even when `codeIntel.lsif` is enabled

@felixfbecker As the original author of sourcegraph/typescript, do you want to add LSIF support? If so, assign this to yourself, otherwise leave it assigned to me.

**Comment by felixfbecker** [comment]
I think it would be easier for you to add since you wrote the library and added basic-code-intel fallback too. Would be great to test the official Microsoft LSIF exporter for TypeScript
