### ISSUE TITLE
JetBrains: Plugin unable to load search contexts defined in Sourcegraph

### ISSUE THREAD

**Issue by gabtorre** [sourcegraph/sourcegraph#50080]
- **Sourcegraph version:** This seems to affect Sourcegraph v4.2.1 and lower 
- **Platform information:** Plugin version: 2.1.2 
- **Customers Impacted:** https://github.com/sourcegraph/accounts/issues/6716
- 
#### Steps to reproduce:

1. Connect IntelliJ IDE with a Sourcegraph instance on v4.2.1 or lower.
2. Try to search for some code in the search bar.
3. The search bar is not showing any search contexts defined in Sourcegraph.

#### Expected behavior:
The plugin should be able to detect search contexts defined in Sourcegraph and display them in the search bar.

#### Actual behavior:
The plugin is not able to look for search contexts defined in Sourcegraph.
Error occurred while loading search contexts

<img width="995" alt="Screenshot 2023-03-28 at 2 02 11 PM" src="https://user-images.githubusercontent.com/69164745/228366032-9b2e3f8c-d974-4034-8dfb-307a83623a41.png">

#### Workaround:
Adding the context name manually works.
Plugin version 2.1.1 works with Sourcegraph v4.2.1 and lower.

If you would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are no [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

**Comment by scalabilitysolved** [comment]
Moving to a P1 based on the plugin still being functional, we're just not respecting search contexts.
