### ISSUE TITLE
Embeddings on by default on cloud instances

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#50096]
/cc @sourcegraph/cloud

**Comment by unknwon** [comment]
This means at least $120/month (if I got the calculator right) budget increase for each MI (`n2-highmem-4` -> `n2-highmem-8`). @rafax

**Comment by malomarrec** [comment]
This is very under-speced for now and just a working issue.
The outcome we want to achieve is: a site-admin at a cloud customer can just turn on cody if they have an anthropic key.

**Comment by jtibshirani** [comment]
I'm going to close this out in favor of some more focused issues. We already have a few conversations going around default embeddings policies for Cloud.
