### ISSUE TITLE
Use the up / down arrow keys to cycle through my previous prompts

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#50099]
Ability to use the up / down arrow keys to cycle through my previous prompts, like a terminal, so I can edit and resend similar prompts.

_Originally posted by @marcleblanc2 in https://github.com/sourcegraph/sourcegraph/discussions/48334#discussioncomment-5141799_

**Comment by deepak2431** [comment]
This issue is already resolved. I can use the up/down arrow keys in the Cody chat to get the previous used prompt in my chat  box

**Comment by malomarrec** [comment]
Good point! Whoever merged this probably forgot to close this issue.
