### ISSUE TITLE
Make links clickable in Cody VS Code

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#50098]
Make the links that Cody suggests AND the files that Cody read to answer clickable.
If in the local workspace, should open in VS Code.
If context from another repo, should open in the Sourcegraph file view.

**Comment by malomarrec** [comment]
https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1680015380279069

**Comment by stefanhengl** [comment]
The files that Cody read are now clickable. Links that Cody suggests are not.

**Comment by deepak2431** [comment]
> The files that Cody read are now clickable. Links that Cody suggests are not.

I can't still click over the files too. I can take up this issue to work on @malomarrec

**Comment by malomarrec** [comment]
Awesome. I think what @stefanhengl meant here is this works (Cody sources)
<img width="329" alt="image" src="https://user-images.githubusercontent.com/25070988/231128181-e2f473ed-8b16-4cc7-946d-72d45f42f3ba.png">

But natural language answers sent by Cody are not clickable.
Awesome, that's a very important feature!

**Comment by deepak2431** [comment]
> Awesome. I think what @stefanhengl meant here is this works (Cody sources)

Hmm, I see. Though I tried to click on the files, it's not working. You can see below the behaviour of it

https://user-images.githubusercontent.com/44617923/231129564-a0a50ef5-48d7-4986-9d21-0a9bffdaa628.mp4

**Comment by deepak2431** [comment]
> Interesting. I can't reproduce locally. What version of Cody are you using? Is it on Mac?

Yeah, it's on Mac M1. I am using the latest version of Cody v0.0.5

**Comment by stefanhengl** [comment]
That should work. I just checked with v0.0.5 on an M1 at it works. Curious to hear what is happening.

**Comment by deepak2431** [comment]
@malomarrec Was working on the solution to this. Just a few questions:
1.  Will the instance URL for the code search be sourcegraph.com?
2. All the repositories to be opened will be hosted on github.com?

**Comment by deepak2431** [comment]
@malomarrec @stefanhengl I have opened a PR for this issue. It would be great if you could have a look at it :)
