### ISSUE TITLE
docs: Most links to site_config options are broken

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#501]
https://sourcegraph.com/search?q=r:sourcegraph/sourcegraph%24+%22/site_config%22+file:%5C.md%24

**Comment by keegancsmith** [comment]
An additional question, how do we generate `all.md`? I don't see any references to code which generates an `all.md`.

**Comment by sqs** [comment]
`all.md` is not auto-generated anymore; I just filed https://github.com/sourcegraph/sourcegraph/issues/505 to fix that soon.

Will fix the instances in the search link in a few hours.
