### ISSUE TITLE
Recipe 8471: Migrate MyCoolLib from 5.0 to 5.1

### ISSUE THREAD

**Issue by almeidapaulooliveira** [sourcegraph/sourcegraph#50128]
Hi reviewers.

#### Reviewers:
- @tjdevries: Added because of platform ownership
- @efritz: Designated reviewer of everything
- @almeidapaulooliveira: Tagged for design review

---

The changes required for upgrading `MyCoolLib` from `5.0` to `5.1` include the following:

- `MyCoolLib.exported_func` no longer takes three arguments. The second argument
  was deprecated for 6 months and is now being removed. All references to [this function](https://sourcegraph.com/search)
  _(sourcegraph link to symbol)_ are being automatically fixed.

**Comment by tjdevries** [comment]
`@cody` Give me your first 5 examples of the change.

**Comment by tjdevries** [comment]
`@cody` open pull request

**Comment by taylorsperry** [comment]
I updated the following files from 5.0 to 5.1: 
- `enterprise/internal/batches/store/batch_spec_workspace.go`
-  `enterprise/internal/batches/store/changeset_jobs.go`

I've also updated the docs to reflect this change [here](https://docs.sourcegraph.com/).
