### ISSUE TITLE
Batch Changes Support for Perforce

### ISSUE THREAD

**Issue by peterguy** [sourcegraph/sourcegraph#50138]
Notes from hackathon
- depots are the root, folders are, by convention, branches
- file revision numbers always go with changelist numbers
- need changelist number + depot path to find out if files are up-to-date
- can't submit changes unless making those changes to tip of file - highest revision number
- branching is another revision number
- perforce can apply patches from one file in a tree to another file in another tree
- changelist can be cross-branch
- shelve a changelist for review
- helix swarm is a team tool that adds notions about projects, review (PR)

Sourcegraph admin settings wrong:
- "depots" is actually branches/folders, or depot paths, not actually depots

Getting a change into perforce
- there's no metadata on the client, like in the .git folder - it's all on the server
- p4 fstat
  - headRev vs haveRev - revisions of the latest change in the depot vs latest change in client/workspace
- p4 edit - open/checkout a file for editing - doesn't necessarily lock it
  - creates the default, un-numbered changelist
- p4 status - shows the changes to files
- p4 submit - locks the file, increases the revision number, submits the change, unlocks the file

submit a change for review, instead of submitting to main branch
- pending changelist - default pending changelist
- can submit the default pending changelist - shelve
- can change ownership of a changelist - hand it over to the code owner for example - but the original owner disappears
- unshelving the changelist applies the change to the local workspace
- comby
- hostless workspaces - but perforce admins don't like automating workspace creation - lots of server overhead
- workspace may already have been created - part of the SG setup admin process

batch change approach
- can submit changes to different depot paths separately to create multiple changelists? Do we want to do this? Maybe in the case that different users have access to different paths

part of the admin setup could be to define a url for the code review tool that can be populated with the changelist id.

check the status of the changelist - is it still pending, or has it been merged/accepted.

**Comment by mrnugget** [comment]
PR that adds Batch Changes for ADO: https://github.com/sourcegraph/sourcegraph/pull/47913/files

**Comment by peterguy** [comment]
The ADO BC support took about three weeks for a single developer; estimating two weeks for Perforce may be optimistic. There is a lot of BC management code that keeps the statuses of the BC updated in Perforce.
