### ISSUE TITLE
Configure global settings via environment variable

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#5014]
Site config and critical site config are currently configurable via environment variables. [$CUSTOMER](https://app.hubspot.com/contacts/2762526/company/554338610) has requested global settings also be settable from environment variable:

> as now we are controlling our configs via version controlled repo, we want everything we set, get up and running at the restart of docker container.

> suppose we add a new repo in external services and need to add it in quick links. Even though docker restart with new external service config via ENV variable will pick new repo, we still need to add quicklink for it manually.

**Comment by beyang** [comment]
Related issue:
* Whitelisting of remote plugins goes in site config
* Enabling extensions for users is in global settings

This caused confusion for $CUSTOMER, because site config is read through an environment variable (stored external to Sourcegraph in a git repo), while global settings still can only be set in the UI.

**Comment by spidyash** [comment]
Confusion related to extensions was there but that was a separate issue.

Generally when you are providing ENV var support for all other configs (like: critical config and site config), why not global settings ? Users should decide what config they want to use in what way.
Like, we dont want to do any config changes manually. Everything should be reflected as soon as the container is restarted with configs via ENV

**Comment by tsenart** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.9 release is scheduled for tomorrow** at 10:00 CEST.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.10 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by spidyash** [comment]
@beyang Do you know if this is fixed in any existing release ?

**Comment by unknwon** [comment]
@spidyash if "this" refers to this issue title, it's not :)

**Comment by beyang** [comment]
@spidyash It is not. We had [plans](https://docs.google.com/document/d/1_HNAEaJBRR5dN1ti-ypDRAlZ4HJMsyYTfDj5Kk_jLWU/edit) to do a broader overhaul of config/settings management that would have included addressing this issue, but that has turned into a longer-term discussion. I'll be revisiting this issue in 3.11 (due out 12.20).
