### ISSUE TITLE
Use two separate Redis instances in Docker deployment

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#5015]
This is the follow-up to https://github.com/sourcegraph/sourcegraph/pull/5011

I'm quoting @nicksnyder's [comment](https://github.com/sourcegraph/sourcegraph/pull/5011#issuecomment-517015862) here, because it's a succint description of the reasoning behind this:

>In a server deployment, even if all keys have an expiry, it seems like it is still possible for the instance to fill up if there is no global eviction policy. Given that we have session data which shouldn't be evicted, it seems like the only real solution is to have two separate instances: one without eviction for session data, and one with eviction for a cache. This is exactly what we have for k8s deployments as far as I can tell (https://github.com/sourcegraph/deploy-sourcegraph/tree/master/base/redis), so I think we should do the same thing for our docker deployment. 

Not sure who to assign this to, so I added both @sourcegraph/core-services and @sourcegraph/distribution labels.

**Comment by dadlerj** [comment]
No idea if this is relevant, but note that site usage data is stored in redis, and should be long-lived. The number of keys should be correlated to the number of user accounts on the instance.

**Comment by mrnugget** [comment]
> No idea if this is relevant, but note that site usage data is stored in redis, and should be long-lived. The number of keys should be correlated to the number of user accounts on the instance.

Definitely relevant, since I noticed that as well :)

Regarding "long-lived": does the usage data need to survive an upgrade? Or, in other words, do we need to migrate the data when switching to a dual-redis setup?
