### ISSUE TITLE
Document VM Access Requirements for Executors

### ISSUE THREAD

**Issue by Piszmog** [sourcegraph/sourcegraph#50168]
We should document what access requirements are required for executors (install, validation, running) on VMs.

## Done

- Access for Docker
- Access for Firecracker
    - `ignite` requires root
    - `NET_ADMIN` for iptables
    - KVM access
    - mounts
- Installing required packages (e.g. git, docker)
- Maybe `systemd` to start at boot
- Access to directory to read/write data

**Comment by danieldides** [comment]
Not much to add for this ticket, most of this information already exists. I went through and verified all of this info exists already:

- Access for Docker [deploy_executors_docker](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/doc/admin/executors/deploy_executors_docker.md?L15-26&view=code)
- Access for Firecracker [deploy_executors_binary](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/doc/admin/executors/deploy_executors_binary.md?L19-27&view=code)
    - `ignite` requires root https://github.com/sourcegraph/sourcegraph/pull/51309
    - `NET_ADMIN` for iptables https://github.com/sourcegraph/sourcegraph/pull/51309
    - KVM access 
    - mounts
- Installing required packages (e.g. git, docker) [deploy_executors_binary](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/doc/admin/executors/deploy_executors_binary.md?L16-17&view=code)
- Maybe `systemd` to start at boot [deploy_executors_binary](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/doc/admin/executors/deploy_executors_binary.md?L151&view=code)
- Access to directory to read/write data [deploy_executors](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/doc/admin/executors/deploy_executors.md?L35-39&view=code)
