### ISSUE TITLE
Embeddings: schedule or automatically trigger updates

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#50173]
Need to make sure admins can schedule refreshing embeddings.
Manual won't scale for any large customer!

Tracking issue: https://github.com/sourcegraph/sourcegraph/issues/52253

**Comment by jtibshirani** [comment]
I'm closing this out as we now have a way to schedule embeddings updates based on repository patterns. We are still improving the admin experience and addressing other cases like model changes -- this work is tracked in https://github.com/sourcegraph/sourcegraph/issues/52253.
