### ISSUE TITLE
[Cody VSCode] Cody does not accept full instance URLs

### ISSUE THREAD

**Issue by danielmarquespt** [sourcegraph/sourcegraph#50186]
Right know the the Cody VScode extension does not work with with urls with the trailing `/` like `https://sourcegraph.sourcegraph.com/` only `https://sourcegraph.sourcegraph.com`

We need to be more flexible about the format of the instance URL in order to minimize any potential friction on adoption

Also, we should change the label of the input to `Sourcegraph instance URL` to be more explicit about what is expected on that field

**Comment by abeatrix** [comment]
Resolved in https://github.com/sourcegraph/sourcegraph/pull/50566
