### ISSUE TITLE
storybook for permissions sync jobs table is broken due to wrong mock

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#50256]
## Problem

The story `web/src/site-admin/permissions-center/PermissionsSyncJobsTable/Six sync jobs` doesn't work.

See screenshot:

<img width="914" alt="screenshot_2023-04-01_16 49 20@2x" src="https://user-images.githubusercontent.com/1185253/229296286-736c376c-ba60-45f7-91f1-15b8f52d4df7.png">

## Reproduce

```
git checkout main && sg run storybook
```

### Investigation

`git bisect` tells me it's likely due to #48607. But that's quite a while ago. Not sure.

/cc @sourcegraph/iam

**Comment by sashaostrikov** [comment]
closed by https://github.com/sourcegraph/sourcegraph/pull/50292
