### ISSUE TITLE
Error when trying to save site configs in the local app

### ISSUE THREAD

**Issue by Ranguna** [sourcegraph/sourcegraph#50266]
- **Sourcegraph version:** 
- **Platform information:** 

#### Steps to reproduce:

1. Open the sourcegraph local app;
2. Navigate to the site settings under the `/site-admin/configuration` path;
3. Use the following config:
   ```
   {
     "auth.providers": [
       {
         "type": "builtin"
       }
     ],
     "externalURL": "http://localhost:3080",
     "codeIntelAutoIndexing.enabled": true,
     "codeIntelAutoIndexing.allowGlobalPolicies": true,
     "executors.frontendURL": "http://host.docker.internal:3080",
     "search.largeFiles": [
       "package-lock.json",
       "**/package-lock.json"
     ],
   }
   ```
4. Click save (or ctrl+s).

#### Expected behavior:
5. The settings should be saved.

#### Actual behavior:
The following error popped up:
> Error: updating site configuration not allowed when using SITE_CONFIG_FILE
> Error occured while attempting to save site configuration. Please backup changes before reloading the page.

![image](https://user-images.githubusercontent.com/5003755/229376488-098f4be1-3885-4b65-a21e-c04127a02c52.png)

If you would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are no [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

**Comment by Ranguna** [comment]
The workaround is to modify `$HOME/.config/sourcegraph-sp/site-config.json` directly.

**Comment by chwarwick** [comment]
This has been fixed for the next release of App.  https://github.com/sourcegraph/sourcegraph/pull/51415
