### ISSUE TITLE
CORS policy (header) conflicts with Chrome extension

### ISSUE THREAD

**Issue by jacobmarble** [sourcegraph/sourcegraph#503]
- **Sourcegraph version:** 2.12.2, single image
- **Platform information:** Kubernetes 1.12.1 on AWS

#### Steps to reproduce:

Create k8s deployment, manually install language support. These configs tell most of that story:
- https://gist.github.com/jacobmarble/daf66cb63ae29e70d649adfb1a9d766f
- https://gist.github.com/jacobmarble/f817960b27f590f0b70cd74afea71fa8

Install Chrome extension, change "server connection" to this instance's URL: https://sourcegraph.internal (also tried this without TLS).

#### Expected behavior:

Successful connection

#### Actual behavior:

"Unable to connect" with this message in the Chrome console:
> Access to XMLHttpRequest at 'https://sourcegraph.internal/.api/graphql?CurrentUser' from origin 'chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack' has been blocked by CORS policy: Request header field authorization is not allowed by Access-Control-Allow-Headers in preflight response.

Looks like a CORS problem, but I don't see a config fix.

**Comment by jacobmarble** [comment]
This did work briefly tonight. A new button said something like "authorize extension" in place of the message "unable to connect". I clicked that, and the status went green.

The Chrome extension works properly now (yes!) but the Chrome extension is back to "unable to connect". Console shows `https://sourcegraph.internal/.api/graphql?CurrentUser` and `https://sourcegraph.internal/.api/graphql?SiteProductVersion ` returning 401 now.

**Comment by jacobmarble** [comment]
Looks like I was logged out of sourcegraph.internal (I didn't ask for that) so logged in and everything (Chrome extension and sourcegraph.internal) seems to be working as intended now.

**Comment by sqs** [comment]
This is [fixed in Sourcegraph 2.13.3](https://github.com/sourcegraph/sourcegraph/issues/969#issuecomment-438837350).
