### ISSUE TITLE
Cody hangs for users that aren't enabled

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#50307]
Context in [thread](https://sourcegraph.slack.com/archives/C04NPH6SZMW/p1680516449820819). I've [updated](https://github.com/sourcegraph/sourcegraph/pull/50305) the README to let users know they need to request access to Cody before the extension will work, but we should also have Cody tell a user if their access token hasn't been set yet.

**Comment by malomarrec** [comment]
Sounds fixed by fixes from Beatrix AND allowlisting everybody in the future? Tentatively closing, reopen if needed!

**Comment by abeatrix** [comment]
PR: https://github.com/sourcegraph/sourcegraph/pull/51005
