### ISSUE TITLE
zoekt: Force re-index when using indexserver debug action

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#5034]
We pass in `-incremental` when responding to a user using the indexserver debug interface to index a commit. However, the users intention is likely to force re-indexing.

**Comment by keegancsmith** [comment]
This missed 3.8. Apologies. Minor change, will be more on top of minor tasks in 3.9.

**Comment by tsenart** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.9 release is scheduled for tomorrow** at 10:00 CEST.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by keegancsmith** [comment]
Fixed in https://github.com/sourcegraph/zoekt/commit/5d69bfbbd57c99f4fdaab2bcfe30b103518a8ee8
