### ISSUE TITLE
Improve UI of VSCode Extension

### ISSUE THREAD

**Issue by danielmarquespt** [sourcegraph/sourcegraph#50344]
Described here

https://sourcegraph.slack.com/archives/C04NPH6SZMW/p1680527681894859

Design Issue:
https://github.com/sourcegraph/sourcegraph/issues/49296

We can scale back the changes just to the UI Refresh without Threads and Shortcuts aka what we have today but with better UI and colors

**Comment by abeatrix** [comment]
My updates on the onboarding process and sqs's updates on the chat UI are now available in main. What would be the next steps from here? @danielmarquespt

**Comment by abeatrix** [comment]
Closing this since we have already covered most of the designs without Threads and Shortcuts implemented. We can open separate issues for other touches up if needed
