### ISSUE TITLE
Allow branches created by Batch Changes to be deleted after closing/deleting a Batch Change

### ISSUE THREAD

**Issue by BolajiOlajide** [sourcegraph/sourcegraph#50354]
This should be opt-in, where the user can select if they want Sourcegraph to delete the branch created after merging or not.

>Feature request: Ability to delete branches pushed by Sourcegraph to code hosts when a batch change is closed/deleted
"Source control hygiene" -- there's a lot of extra cost associated with keeping those branches around

**Comment by BolajiOlajide** [comment]
An approach to consider is to make this a setting configurable by the site admin and automate this to be done on Changeset merge or Batch Change close.

**Comment by marcleblanc2** [comment]
Similar issue: https://github.com/sourcegraph/sourcegraph/issues/23471

**Comment by marcleblanc2** [comment]
Related, customer https://github.com/sourcegraph/accounts/issues/569 would like the option to delete the forked repos created during a Batch Change, so I've submitted that feature request in https://github.com/sourcegraph/sourcegraph/issues/50520
