### ISSUE TITLE
Pull Cody out into separate OSS repo

### ISSUE THREAD

**Issue by dominiccooney** [sourcegraph/sourcegraph#50459]
Goals:
- Open Source contributors can pull a standalone repo and have a decent AI coding assistant development experience *without Sourcegraph*
- Don't compromise the "bring the best of Sourcegraph" integrations

**Comment by vdavid** [comment]
Thinking out loud:
- Where would the web version live, and how would it communicate with the parts in the other repo?
  - Best guess: the web version stays in the monorepo and would be a client of a Cody deployment
- Would the VS Code extension move to the Cody repo?
  - Best guess: yes—or maybe to yet another repo?
- Same for other editor extensions

Overall, I'm currently on the skeptical side, seeing more value in keeping Cody in the main repo.
I think we should weigh our options before jumping into it.
 - If there's an RFC / thinking doc for this where we weighed the pros and cons, I'd love to see.
 - If there isn't yet, I'm happy to look into it and come up with a doc, or just contribute to it with comments if someone does the thinking.

**Comment by lrhacker** [comment]
[All done](https://github.com/sourcegraph/cody)!
