### ISSUE TITLE
Ranking: no file ranks on S2 and dot com

### ISSUE THREAD

**Issue by jtibshirani** [sourcegraph/sourcegraph#50461]
Both dot com and S2 are missing ranks entirely for some repos, and for others only showing the mean rank. We should investigate to figure out if there's a problem with the job.

Example from S2 (look at the `file-rank` part of the debug text):

![Screenshot 2023-04-06 at 6 29 45 PM](https://user-images.githubusercontent.com/7461306/230522136-95086428-5d5d-40b7-90cd-9034deaa6c58.png)

**Comment by efritz** [comment]
Should be aided by https://github.com/sourcegraph/sourcegraph/issues/51117.
