### ISSUE TITLE
Deploy a p4 server for integration tests that is solely for that purpose. 

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#50474]
We're using the dogfood perforce server for both tests and experimentations, meaning we can accidentally break stuff. 

We should have a p4 server running in the `sourcegraph-ci` project solely for the purpose of integration tests.

**Comment by mucles** [comment]
https://handbook.sourcegraph.com/departments/technical-success/support/process/p4-enablement/#integration-testing-perforce-server

**Comment by mucles** [comment]
These are the places I found where the dog food perforce instance was used and got updated to the perforce-tests instance. Let me know if I am missing anything 👀
