### ISSUE TITLE
Add icons to our extensions in the extension registry

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#5048]
Icons will make it easier to scan the extension registry. I've done this before, so I can take this.

**Comment by felixfbecker** [comment]
I saw this was bumped from 3.7 to 3.8 by @attfarhan, @chrismwendt by when do you think you could get the remaining icons done?

**Comment by chrismwendt** [comment]
@felixfbecker What remaining icons? I think they're all added.

**Comment by felixfbecker** [comment]
If you go to https://sourcegraph.com/extensions, there are still multiple extensions by `sourcegraph/` (some in the first row) that don't have icons

**Comment by lguychard** [comment]
Should this be in 3.8 @chrismwendt ? From what I understand it's now only about adding icons to the remaining, non-language `sourcegraph/` extensions.

**Comment by chrismwendt** [comment]
Icons waiting for review:

- https://github.com/sourcegraph/sourcegraph-extension-samples/pull/41
- https://github.com/sourcegraph/sourcegraph-datadog-metrics/pull/24
- https://github.com/sourcegraph/sourcegraph-lightstep/pull/8

After those, the only extensions without icons will be WIP or non-sourcegraph.

**Comment by chrismwendt** [comment]
Added a half dozen more icons :tada:
