### ISSUE TITLE
JetBrains: Can't change URL to enterprise location, no access to configuration modal 

### ISSUE THREAD

**Issue by camerongable** [sourcegraph/sourcegraph#50487]
In Webstorm 2023.1, I am unable to use a lot of the functionality of the plugin like opening a file or copying the path because the URL is not correct. I am unable to find Sourcegraph under the "Tools" section in preferences so I can't update the enterprise URL to be correct.

**Comment by taylorsperry** [comment]
Sorry this got buried, @camerongable! I'm closing since there have been many versions since you reported, but please reopen if you're still running into issues.
