### ISSUE TITLE
Copy path to clipboard

### ISSUE THREAD

**Issue by johnwesonga** [sourcegraph/sourcegraph#50491]
"Copy path to clipboard" - extend this functionality, have a icon to "copy full path", which also includes the domain of the source, that I can directly get to in a browser.

![Image](https://user-images.githubusercontent.com/1172026/230683857-285d4420-ab04-430e-a0a7-3f303fec96a4.png)

**Comment by camdencheek** [comment]
Closing as somewhere between "Done" and "Won't do" because we have a separate action for "open in code host"
