### ISSUE TITLE
Phabricator integration not working, using incorrect base commit

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#5051]
- **Sourcegraph version:** 
* Sourcegraph cluster deployment
* Phabricator native integration

#### Steps to reproduce:

Reported by https://app.hubspot.com/contacts/2762526/company/555146901

> I have upgraded to the most recent SG Extension (1.2) -> but the mouse over, and code intelligence in Phabricator seems to not be working. It does show the SG Star on the top of the code, which moves you to a SG Diff page (which fails with an unfound base in my testing). 

>It was working prior to the upgrade to SourceGraph 3. 

>The diff issue looks like the staging bug. revision not found: <REPO>@phabricator/base/120831^0

**Comment by lguychard** [comment]
Closed by https://github.com/sourcegraph/sourcegraph/pull/5320
