### ISSUE TITLE
Cody VS Code extension network proxy auth header user settings

### ISSUE THREAD

**Issue by marcleblanc2** [sourcegraph/sourcegraph#50540]
#### Feature request description

In the Cody VS Code extension, customers with a network proxy auth between their laptop and their Sourcegraph instance need the ability configure HTTP authentication headers for Cody traffic to reach their Sourcegraph instance. This includes customer [578](https://github.com/sourcegraph/accounts/issues/578).

We may be able to reuse much of the [Sourcegraph VS Code extension code here](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph$+file:%5Eclient/vscode+requestHeaders+&patternType=standard&sm=1&groupBy=path).

#### Is your feature request related to a problem? If so, please describe.

Configuring the Cody VS Code extension is a struggle.

#### Describe alternatives you've considered.

No alternatives available. 

#### Additional context

Slack thread in [#ask-cody here](https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1681257445275659)

**Comment by malomarrec** [comment]
This is urgent, recommend to expedite and ship a VS Code extension release.
