### ISSUE TITLE
Highlight search result match in code editor when user clicks from search results page

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#5057]
From a user at [$CUSTOMER](https://app.hubspot.com/contacts/2762526/company/554338610):

> It would be great to highlight the keyword in a search in a file
> 
> For example:
> * Do any keyword search in a file. Example search query:  ‘beyang file:example.xml’
> * You will see search results with highlighted keyword 
> * Click on any of the search result file
> * Now the keyword highlighting is gone even though the search query is still same
> * Now you have to use browser search to highlight that keyword
> * **Expected behavior:** SG should keep the searched keyword (or string) highlighted when you are visiting search results

**Comment by beyang** [comment]
@christinaforney could you triage this with the search team?

**Comment by christinaforney** [comment]
Will do!

**Comment by christinaforney** [comment]
Just got related feedback from another user to show highlights of a clicked keyword (perhaps when we pin on double click?), to show all the occurrences of that keyword highlighted in the file. The user found themselves doing lots of browser searches to create the highlighted effect, but it would be great if this worked out of the box in Sourcegraph. 

I imagine this is largely the same functionality as the original request, and would just be a minor enhancement to change the highlighted keyword on token focus/double click.

**Comment by slimsag** [comment]
For inspiration, I would look at how editors do this. For example, in VS Code:

![image](https://user-images.githubusercontent.com/3173176/62978334-df16ae00-bdd5-11e9-88a0-658f6baed2d6.png)

Any selected word/token -> others are highlighted.

It would be nice if we did something similar _irrespective_ of the hover tooltips we do because it would e.g. allow you to highlight all occurrences of `if` or `func` despite the fact that those would have no hover tooltips.

**Comment by christinaforney** [comment]
Ah yes, thanks for pointing that out! Agree that all tokens, not just ones with hover should show highlights. I was just thinking that the double click action (which will highlight a single token) would be a good trigger - thoughts on that?

**Comment by camdencheek** [comment]
I think we can close this since we solve this with the file preview panel, which allows you to browse all matches within a file. 

![Image](https://github.com/sourcegraph/sourcegraph/assets/12631702/a46a8e84-1c56-4783-8e9f-8e14a7833454)
