### ISSUE TITLE
gitserver deletes all repositories if the disk size is ~= SRC_REPOS_DESIRED_FREE_GB

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#5059]
https://github.com/sourcegraph/sourcegraph/blob/1ed7c5fbd6300aff6436478d1ebd91d02764c8e7/cmd/gitserver/main.go#L27

Gitserver periodically runs a cleanup job so that it always keeps a certain amount of disk space free (default 10GB). However, if the actual disk size is ~= `SRC_REPOS_DESIRED_FREE_GB`, then gitsever will delete _all_ of the repos on the instance as part of the cleanup process. This forces gitserver to reclone all those repos again, which results in bad/broken UX. 

One way of fixing this is to make the cleanup threshold percentage-based instead of a fixed number. 

cc @sourcegraph/core-services

**Comment by keegancsmith** [comment]
So we should probably change this to instead target a certain percentage free (I propose 10%).

**Comment by keegancsmith** [comment]
@ggilmore the customer who ran into this, have you given them a workaround? Also good find.

**Comment by juliasourceress** [comment]
The workaround was for them to upgrade disk storage used - they were able to do 100gb in this case.

**Comment by ggilmore** [comment]
This happened with another customer today. Maybe we should look into adding a site-admin alert (telling you to increase your disk size) whenever gitserver runs this cleanup job?

**Comment by keegancsmith** [comment]
We could surface this information in the admin progress notifications that @mrnugget added? Either way I think this is a bug, we should instead be targeting a percentage free.

**Comment by mrnugget** [comment]
> We could surface this information in the admin progress notifications that @mrnugget added?

We could create a status message when we're close to running out of disk space. It's harder to do a one-off message, as in "about to run the cleanup job", because that would require state.

**Comment by ijt** [comment]
@keegancsmith, percentage free sounds good. To deal with existing usage we could also check if `$SRC_REPOS_DESIRED_FREE_GB` is set and if so, exit with a message saying to set `$SRC_REPOS_DESIRED_PERCENT_FREE`.
