### ISSUE TITLE
Configure Multiple Executor Queues

### ISSUE THREAD

**Issue by Piszmog** [sourcegraph/sourcegraph#50616]
Today, executors has an [environment variable](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/executor/internal/config/config.go?L89) (`EXECUTOR_QUEUE_NAME`) that sets the **single** queue that the executor will process. To be able to handle multiple queues (or filters), a new environment variables needs to be added.

For backwards compatibility reasons, the existing environment variable `EXECUTOR_QUEUE_NAME` should exist along side the new environment variable. `EXECUTOR_QUEUE_NAME` should be used as a fallback if the new environment variable is not set.

## Done

- Add a new environment variable that accepts multiple queue values
- Pass the value[s] to the HTTP queue client for use in the general dequeue function
- Update usages of the specific dequeue client function to the general dequeue function
- Update the HTTP queue client to use the queue in the `Job` when calling the other functions
    - For backwards compatibility reasons, if the `Job` does not have a queue, fallback to the single queue name (the general dequeue endpoint will not exist if this happens)
- Update docs
- Unit tests
- Demo

## Requires

- #50614

**Comment by sanderginn** [comment]
- Closed by https://github.com/sourcegraph/sourcegraph/pull/52020, demo will follow before merging https://github.com/sourcegraph/sourcegraph/issues/50614
