### ISSUE TITLE
Unauthed users cannot search

### ISSUE THREAD

**Issue by bencripps** [sourcegraph/sourcegraph#5061]
## Background 
Current product version: 3.6.0 (3.6.0)
Last update check: 2 minutes ago.

We recently built SG 3.6.0 from the open source image. We have it up and running, and I have created an admin account. After installing a repo, I can search the repos.

## Problem

When using an incognito window (and thus not logged in), any subsequent searches (hitting the http://127.0.0.1:7080/.api/graphql?Search endpoint) timeout. It takes about 30 seconds, but the request finally dies showing `Unexpected HTTP error: 504 Gateway Time-out`. I've also tested this with other user (not using incognito mode, but without accounts). 

As best I can tell, there are no errors in the console regarding these errors. 

Our sourcegraph-config.json file looks like:

```json
{
    "disablePublicRepoRedirects": true,
    "auth.providers": [
      {
        "type": "builtin",
        "allowSignup": false
      }
    ],
    "auth.public": true,
    "externalURL": "https://127.0.0.1:7080"
  }

```

Additionally, we're not able to access the management console. When accessing the console, at 127.0.0.1:2633 we see the following:

![image](https://user-images.githubusercontent.com/6272507/62337646-2bd7bc00-b49b-11e9-90bc-d30a200b6234.png)

It seems like both of these issues could be docker related; here is the command we're using to start the instance:

```bash
docker run --rm     --publish 7080:7080     --publish 2633:2633   -e SRC_LOG_LEVEL=dbug     -e DEBUG=t     --volume ${SOURCEGRAPH_CONFIGURATION_DIR}:/etc/sourcegraph     --volume ${SOURCEGRAPH_DATA_DIR}:/var/opt/sourcegraph   sourcegraph/server:${USER}-dev
```
To build the image, we ran

```bash
./sourcegraph/dev/dev-sourcegraph-server.sh
```
Although, interestingly, I needed to run `yarn add gulp` and `yarn add cross-env` to get the build to succeed.

**Comment by slimsag** [comment]
Extremely sorry that this was not followed up on - especially given how detailed of a report this was :( There has been some more discussion on this topic here: https://github.com/sourcegraph/sourcegraph/issues/11990 and I am kicking off a discussion with the team about how we can better support the open source image ASAP.

I'm going to close in favor of the linked issue above to keep all of this discussion in one place - hope that's okay
