### ISSUE TITLE
Use GitHub users' OAuth tokens to sync the private repos they have access to

### ISSUE THREAD

**Issue by marcleblanc2** [sourcegraph/sourcegraph#50623]
#### Feature request description

As a Sourcegraph user, I need all of the repos that I have access to available on Sourcegraph, so that I can get the full value out of the code intelligence platform.

#### Is your feature request related to a problem? If so, please describe.

I need Sourcegraph to be a single pane of glass where I can find, read, understand, analyze, and learn from all of the code I have access to.

#### Describe alternatives you've considered.

Disappointment 😂

As a user: go back to the code host to search / find / read code, splitting my attention in yet another place, and spending more time on GitHub. 

As an admin: beg the Git admin team to give me an access token with global admin permissions so that Sourcegraph can clone users' private repos, then get declined.

#### Additional context

The GitHub App / OAuth approach requires our admins to get a token with full repo perms, as write perms are required to read permissions on private repos, which means we should already have the token scope authorization to clone these private repos, so we can deliver this additional value without having to ask for more permissions.

We could even make it opt in for the site admin and opt out for users.
 
Requested by [6716](https://github.com/sourcegraph/accounts/issues/6716) in [Slack](https://sourcegraph.slack.com/archives/C01D50MSA7L/p1680206613073069) / support ticket [13304](https://sourcegraph.zendesk.com/agent/tickets/13304).

/cc @sourcegraph/source/iam

**Comment by mrnugget** [comment]
@pjlast @kopancek isn't this fixed with GitHub App?

**Comment by pjlast** [comment]
@mrnugget I think it's sort-of possible to do with GitHub App now. A user can install the App on their personal GitHub account, but a Sourcegraph admin would still need to create the code host connection for that installation
