### ISSUE TITLE
Restrict who can use Cody

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#50632]
#### Problem

- When initialling trialing Cody, customers want to restrict it to a smaller audience.
- We've also heard from customers that they'd like to turn on the natural language `/search/cody`, but not Cody. That's because approving sending code snippets out is much longer than approving sending queries out.

#### Proposal

Ultimately, this should be covered by RBAC. However, in the interest of time, we can just use a feature flag.

- Wrap cody behind the `cody-experimental` feature flag for all instances
- Make sure to wrap magical search, and any separate feature, behind a **different** feature flag.

#### Impacted customers

This will block:

- https://github.com/sourcegraph/accounts/issues/8690
- https://github.com/sourcegraph/accounts/issues/6036
- https://github.com/sourcegraph/accounts/issues/554
- https://github.com/sourcegraph/accounts/issues/579

**Comment by sqs** [comment]
See related Slack thread: https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1681418844526549

It’s directly blocking https://github.com/sourcegraph/accounts/issues/6036 and will almost certainly be a blocker for many others to start using Cody quickly with a small group. Needs to get into v5.0 patch release too.

**Comment by malomarrec** [comment]
https://github.com/sourcegraph/sourcegraph/pull/50668/files

**Comment by raznar** [comment]
This is also blocking [sourcegraph/accounts#8262](https://github.com/sourcegraph/accounts/issues/8262)

**Comment by mrnugget** [comment]
As discussed in call now:

- [ ] @malomarrec document this
