### ISSUE TITLE
cody HTML escaping issues

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#50680]
- I saw some HTML entities be rendered as text (like `&gt;` or whatever) in the stuff implemented in  #50547 in @beyang's demo last night
- I just saw an `<input>` be rendered:
![image](https://user-images.githubusercontent.com/1976/232238021-913cee6a-bf47-4c1b-ac34-1bfb960945b8.png)

**Comment by dominiccooney** [comment]
![Screenshot 2023-04-26 at 16 08 51](https://user-images.githubusercontent.com/55120/234498360-c1539b15-33e8-4405-8829-bf75459b2eeb.png)

Repro, for fun:

1. Create the HTML page on the right, with something like `font-family: serif` or `color: pink`.
2. Tell Cody in chat, "These days I really prefer purple" or "I really like the cursive font family."
3. In editor, select all, Fixup.
4. In chat, admonish Cody, "No, I said I love *purple*." or "No, I said I love *cursive*."
