### ISSUE TITLE
React to Mojave dark theme

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#507]
#### Feature request description

CSS has a standard now for detecting dark mode and it has been implemented in Safari Technology Preview 68.

https://drafts.csswg.org/mediaqueries-5/#descdef-media-prefers-color-scheme

We can read it from JS with https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia

We should support three states essentially, "light", "dark" and "OS"/"auto".

**Comment by francisschmaltz** [comment]
I'd love this but there is an API in macOS for this yet. Maybe there is one in the works..

**Comment by francisschmaltz** [comment]
https://trac.webkit.org/changeset/237156/webkit

Nice

**Comment by keegancsmith** [comment]
@francisschmaltz the commit you added https://github.com/sourcegraph/sourcegraph/commit/5a6baf47086f1c8b7d2a9ebd0f0bff02f2844455 you accidentally included `cmd/frontend/internal/app/assets/distassets_vfsdata.go`. Please don't merge that into master, it is quite a large file :) (I noticed I had to fetch a few megs this morning when running git fetch and investigated why, luckily its still just in your branch)

**Comment by francisschmaltz** [comment]
@keegancsmith Thanks! Removed in 
https://github.com/sourcegraph/sourcegraph/commit/5003f6767c3bd2264b38e8c297ef2084e1ad60bb
