### ISSUE TITLE
Browser extension codeintel fails on OSS repos with extensions enabled

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#508]
#### Steps to reproduce:

1. Enable the "Use Sourcegraph extensions" checkbox
1. Select a _private_ Sourcegraph instance endpoint
1. Visit an OSS repo on GitHub that isn't on your private instance
1. Code intel does not work, and all network requests go to the private instance instead of falling back to Sourcegraph.com

To confirm this is the issue, you can uncheck "Use Sourcegraph extensions", and then visit another repo that isn't on your instance (making sure the previous one didn't get auto-cloned).

Note this time that network requests fall back to sourcegraph.com instead of using the private instance.

**Comment by nicksnyder** [comment]
@dadlerj Are you still able to reproduce?

**Comment by nicksnyder** [comment]
old issuek unable to repro
