### ISSUE TITLE
[K8s Testing] - Client and Cluster Compatability

### ISSUE THREAD

**Issue by kalanchan** [sourcegraph/sourcegraph#50819]
# Cluster and Client compatibility 

Use the Kubernetes go client library [compatibility matrix](https://github.com/kubernetes/client-go#compatibility-matrix) as reference. We need to double check our client version works with different versions of Kubernetes. 

Goal: Test Kubernetes go client on [cluster versions 1.19 and above](https://docs.sourcegraph.com/admin/deploy/kubernetes)

```[tasklist]
## Cluster and Client testing tasks
- [x] Create makefile or automation script to spin up kind clusters with different versions (1.19 and above)
- [x] Confirm which client version we are using and note this down
- [x] Deploy Sourcegraph and test executors on them
- [x] Check Executor job spawns, CPU/Mem usage, Job completion & lifecycle
- [x] Monitor Cluster usage spikes, determine how jobs get throttled upon cluster resource limitations
```

### Batch Changes

Ensure Native SSBC is feature flag enabled.

1. Create a new Batch Change
2. Have 10+ repositories be selected by the batch spec
3. Run the batch change
4. Ensure the batch change is applied correctly to the workspace.

### Code Intel

1. Enable [Precise Code Nav](https://docs.sourcegraph.com/code_navigation/how-to/enable_auto_indexing).
2. run indexing across 10+ repositories.

**Comment by Piszmog** [comment]
Client Version: `0.25.3`

| Cluster Version | Works? |
|--------|--------|
| `1.26` | ✅ |
| `1.25` | ❓ |
| `1.24` | ❓ |
| `1.23` | ❓ |
| `1.22` | ❓ |
| `1.21` | ❓ |
| `1.20` | ❓ |
| `1.19` | ❓ |

**Comment by Piszmog** [comment]
Attached is the shell script the `Makefile` for help automate running different cluster versions.

[k8s_testing.zip](https://github.com/sourcegraph/sourcegraph/files/11277303/k8s_testing.zip)

**Comment by Piszmog** [comment]
Tested cluster versions 1.19 - 1.27. Ran batch changes and precise and it all works. I did not observe any issues with Memory or CPU. I had Executor spawning a lot of Job Pods with no issues.
