### ISSUE TITLE
Short max password length

### ISSUE THREAD

**Issue by marcleblanc2** [sourcegraph/sourcegraph#50842]
- **Sourcegraph version:** v5.0.1
- **Platform information:** docker-compose on M1 Mac

#### Steps to reproduce:

1. Create initial admin user, or try to reset password

#### Expected behavior:

1. User sees a max password length when the admin is creating the initial admin account, or when a user is setting / resetting their password
2. User gets a meaningful error message when their password is too long

#### Actual behavior:

1. When trying to create the initial admin account, I get an error message that says "Signup failed unexpectedly"
2. When trying to reset my password, I get an error message that says "Bcrypt: password length exceeds 72 bytes"

/cc @sourcegraph/source/iam

**Comment by mrnugget** [comment]
Hmmmm. Can you reproduce this on a fresh instance? If not, I'd strike it up to App and compose etc
