### ISSUE TITLE
Implement any frontend requirements (GraphQL, redirects, etc.)

### ISSUE THREAD

**Issue by pjlast** [sourcegraph/sourcegraph#50853]
We're going to need various endpoints to handle GitHub App setups.

See here as a starting point: https://docs.github.com/en/apps/creating-github-apps/creating-github-apps/creating-a-github-app

**Comment by kopancek** [comment]
Docs for prefilling the github app creation form: https://docs.github.com/en/apps/creating-github-apps/creating-github-apps/creating-a-github-app-using-url-parameters
