### ISSUE TITLE
Embeddings performance on monorepos

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#50861]
We currently have hard limits on the size of repos we can generate embeddings for. It seems to be mostly constrained by memory usage of the embedding index.

We're tackling this on two fronts:
1) Investigating a proper vector DB (Weaviate)
2) Looking into ways to reduce resource consumption of our hand-rolled embeddings search

**Comment by jtibshirani** [comment]
Here's the work we've done on point 2, Optimizing our custom embeddings search:
* https://github.com/sourcegraph/sourcegraph/pull/50953
* https://github.com/sourcegraph/sourcegraph/pull/51006

**Comment by camdencheek** [comment]
I just merged [SIMD support](https://github.com/sourcegraph/sourcegraph/pull/51372), which speeds up searching by an additional 10x.

**Comment by camdencheek** [comment]
@jtibshirani are there other things we had in mind for this ticket, or is it safe to close this as "we've done what we planned to for now"?

**Comment by jtibshirani** [comment]
@camdencheek I planned to keep this open until our target customer is upgraded and successful (in case other things pop up). Hopefully very soon!

**Comment by jtibshirani** [comment]
I opened https://github.com/sourcegraph/sourcegraph/issues/53343.
