### ISSUE TITLE
Files don't sync from Perforce depot

### ISSUE THREAD

**Issue by peterguy** [sourcegraph/sourcegraph#50860]
![Image](https://user-images.githubusercontent.com/129280/233128206-733b7ba6-49ab-41be-8562-0b4585811da9.png)

There are commits, but no files.

**Comment by peterguy** [comment]
This is similar to #43121, where the client spec is not defined correctly, so the files are not synced.

**Comment by peterguy** [comment]
In this case, the problem turned out to be that the perforce server was allowed only 20 workspace definitions, and all of them were used. The code host config did not specify a `p4.client`, so `p4-fusion` tried to create a temporary client, but failed because the server didn't allow any more clients. The failure to create the client did not stop `p4-fusion` from syncing changes, so it ended up with commits (because `p4 changes` worked without the client spec), but the commits were empty because `p4 sync` to get the files didn't work.

**Comment by peterguy** [comment]
In all cases, we need to surface errors better. In order to do that, we probably need to test the client spec ourselves, instead of relying on output from `p4-fusion` (there is output, it's just not exposed), especially since the observed behavior of `p4-fusion` is that it doesn't stop with an error, but instead iterates through the changelists, creating commits for each one.

**Comment by mike-r-mclaughlin** [comment]
Ran into this same issue at https://github.com/sourcegraph/accounts/issues/6938

Logs:
```
[ PRINT @ Main:51 ] p4-fusion v1.12.0
[ PRINT @ Main:73 ] Running p4-fusion from: p4-fusion
[ SUCCESS @ InitializeLibraries:160 ] Initialized P4Libraries successfully
[ SUCCESS @ Main:90 ] Perforce server is available
[ ERROR @ HandleError:13 ] Received error: error 'xyz' validation failed: 
*** Error: trigger client.out failed:
The workspace name gitserver-0 does not begin with your user id xyz
followed by '.' followed by something - like the branch name, task,
geck number, etc.

To create a new workspace, please follow the above naming conventions.


[ ERROR @ RunEx:118 ] Connection dropped or command errored, retrying in 5 seconds.
[ SUCCESS @ RunEx:123 ] Reinitialized P4API
[ WARNING @ RunEx:130 ] Retrying: p4 client -o
[ ERROR @ HandleError:13 ] Received error: error 'xyz' validation failed: 
*** Error: trigger client.out failed:
The workspace name gitserver-0 does not begin with your user id xyz
followed by '.' followed by something - like the branch name, task,
geck number, etc.

To create a new workspace, please follow the above naming conventions.
...
<p4-fusion continues running>
```

Worked around it by creating a client spec and providing that in `p4.client` configuration.
