### ISSUE TITLE
Configure SSO redirect URL

### ISSUE THREAD

**Issue by johnwesonga** [sourcegraph/sourcegraph#50879]
https://github.com/sourcegraph/accounts/issues/8306 would like to be able to configure the GitLab SSO redirect URL for their Sourcegraph instance. When they click on the login button on the instance homepage, it redirects to https://gitlab.com/users/sign_in and they'd like it instead to redirect to their a dedicated GitLab URL for their org so that they can do the SSO auth button click.

To work around this at the moment, they're telling users to log in to the dedicated URL in another tab and then go to Sourcegraph to log in with the button, which works and redirects to the site.

**Comment by davejrt** [comment]
The functionality they're requesting is the current behavior. 

https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/auth/SignInPage.tsx?L134 gets the URL from the siteconfig and updates the button

Can we get a look at their siteconfig to ensure the auth url is actually setup correctly?

**Comment by pjlast** [comment]
Okay I have a PR for this going, but I'd like to verify that this works, but to do that I need access to a GitLab that group that enforces SAML SSO
