### ISSUE TITLE
nameTransformations support on Gerrit

### ISSUE THREAD

**Issue by johnwesonga** [sourcegraph/sourcegraph#50887]
The customer is trying to use the Sourcegraph browser extension with their Gerrit code host but they're seeing Repo not found on the Gerrit page. Full context below:

https://sourcegraph.slack.com/archives/C01LZKLRF0C/p1679518390859439

**Comment by taras-yemets** [comment]
Closing this as duplicate of
- https://github.com/sourcegraph/sourcegraph/issues/49951
