### ISSUE TITLE
Restore deleted users

### ISSUE THREAD

**Issue by johnwesonga** [sourcegraph/sourcegraph#50881]
Toast would really like to be able to restore deleted users. When a user is deleted (intentionally or accidentally), there is no simple way to restore that user record, which means all the user's settings are lost. While there are database commands that can be run to reinstate a user, the implications of doing so are unknown, so we do not recommend this course of action, as it could lead to unforeseen issues elsewhere in the product. On top of this, we have both "Delete" and "Delete forever" options in the UI, which makes this experience even more unintuitive, as admins assume that if they "delete" a user (vs "delete forever"), that they'll be able to easily undo that action if needed.

**Comment by gl-srgr** [comment]
I believe the graphql `recoverUsers` added in this PR covers some of the work in this ticket:

https://github.com/sourcegraph/sourcegraph/pull/46654

I believe the work that is remaining would be:

- Provide a way to restore by username or email address (could be a bulk operation for restoring multiple users).
- Provide a way to search for a deleted user and/or browse a list of deleted users, so that there's a way to determine which user(s) to restore without knowing the user ids.

**Comment by gl-srgr** [comment]
issue in docsite that is related: https://github.com/sourcegraph/docsite/issues/94

**Comment by gl-srgr** [comment]
Another relevant [comment](https://sourcegraph.slack.com/archives/C022SPMNR0W/p1673302279777359?thread_ts=1672933921.969169&cid=C022SPMNR0W) I came across:

> Fly-by comment: We should be thoughtful about this decision... Are these customers on hard account caps?
> If yes, we should be super clear that it sounds like they're actively working to get past our licensing limits. For example, customers could abuse this by having a simple script to soft delete users just prior to hitting their cap. Or soft deleting a bunch of users prior to the end of a month when billing hits. I can't speak to why we haven't made the 'restore' functionality easier in the past but flagging this before we get too far down this path now.

**Comment by taras-yemets** [comment]
- https://github.com/sourcegraph/sourcegraph/pull/46654
- https://github.com/sourcegraph/sourcegraph/pull/47138

**Comment by taras-yemets** [comment]
- https://github.com/sourcegraph/sourcegraph/pull/46654
- https://github.com/sourcegraph/sourcegraph/pull/47138

**Comment by johnwesonga** [comment]
@ryphil to chime in on this cc: @anorrish
