### ISSUE TITLE
remove :7004 for src-cli

### ISSUE THREAD

**Issue by johnwesonga** [sourcegraph/sourcegraph#50900]
https://github.com/sourcegraph/accounts/issues/565

When printing URLs, remove the :7004 so clicking them is easier. Right now we need to click, then look at the TLS complaint from the browser, edit the URL, and then go to the page we need.

![Image](https://github.com/sourcegraph/sourcegraph/assets/1172026/e6655f3a-8031-44e9-8b2d-0d6f04748d99)

**Comment by davejrt** [comment]
@johnwesonga is there more context about how to replicate this? A slack thread with the customer showing where they reported it possibly?

**Comment by johnwesonga** [comment]
@superhsu this was your product gap https://sourcegraph2020.lightning.force.com/lightning/r/Product_Gap_Submission__c/a1C5b00000CSjFfEAL/view can you provide some context?

**Comment by davejrt** [comment]
Marking this as rejected, unless the customer can provide why they're using a different URL to access the sourcegraph UI, than what is in there `SRC_ENDPOINT` envvar. 

These should be the same an eliminate this problem.
