### ISSUE TITLE
Implement UI for generating SSH signing key

### ISSUE THREAD

**Issue by BolajiOlajide** [sourcegraph/sourcegraph#50935]
Create the section for generating a signing key

We are only supporting SSH for now.

**Comment by BolajiOlajide** [comment]
Another key output of this ticket is the ability to preview the SSH key (Public key). This can be mocked until the graphql API is ready.

**Comment by courier-new** [comment]
The workflow we have roughly agreed upon for this UI is now as follows:

1. The "add credential" modal now always shows the two-step tab UI, regardless of whether or not the code host requires SSH:
    <img width="533" alt="image" src="https://user-images.githubusercontent.com/8942601/234667859-7bd344ac-53c0-482a-96cd-0612f6a11afe.png">


2. Show a checkbox at the end of the form to enable a user to opt in to commit signing for that code host credential:
    <img width="537" alt="image" src="https://user-images.githubusercontent.com/8942601/234668495-b07d4f7a-8bc3-436a-8635-dcc2f155cefe.png">

    - If the code host already uses SSH, the button will still be "Next" regardless of if the box is checked, and the tooltip will explain that we will use the same SSH key for authentication and signing:
	   <img width="545" alt="image" src="https://user-images.githubusercontent.com/8942601/234673440-9237cd24-481e-4c24-a420-626233f77eea.png">

    - If the code host does not use SSH already, the button will change to "Next" only if the box is checked, and the tooltip will explain that we will generate an SSH key on their behalf for signing:
        <img width="544" alt="image" src="https://user-images.githubusercontent.com/8942601/234669507-abe76261-bb84-498d-a8f9-02d47b74afc4.png">

    - If the code host type does not support commit signing, e.g. Bitbuckets or ADO, we disable the checkbox with a tooltip:
        <img width="530" alt="image" src="https://user-images.githubusercontent.com/8942601/234670737-3aae6142-d83b-4efb-94e5-207dcceb1d03.png">
        This should match the style of the execution options dropdown on the spec editor page:
          <img width="322" alt="image" src="https://user-images.githubusercontent.com/8942601/234360642-b1d2f154-0ec1-4f01-9cb2-38c8b6f85a6f.png">

3. The `CreateBatchChangesCredential` mutation invoked on clicking "Next"/"Add" is now called with an additional argument, `preferSignedCommits: Boolean!` that reflects whether or not this checkbox is checked. In turn, this property is then queryable on the return `BatchChangesCredential` type as `prefersSignedCommits: Boolean!`.

4. When a credential is created for a code host that requires SSH, has commit signing enabled, or both, we progress to Step 2 in the modal.
    - The description text can change based on the context in which the user indicated they want to use the SSH key:
      - Just SSH: An SSH key has been generated for your batch changes code host connection. Copy the public key below and enter it on your code host.
      - SSH and commit signing: An SSH key has been generated for your batch changes code host connection. It will also be used to sign any commits coming from Sourcegraph. Copy the public key below and enter it on your code host.
      - Just commit signing: An SSH key has been generated to sign any commits coming from Sourcegraph. Copy the public key below and enter it on your code host.
    - The "Configuration instructions" link should link to the docs pages referenced in the initial issue description above for the appropriate code host. 

5. Once successfully configured, the credential node should show an indication that it uses commit signing, such as with an inline badge, and the "View public key" button should be visible for it:
    <img width="983" alt="image" src="https://user-images.githubusercontent.com/8942601/234675364-e6e3ff25-44a3-487f-ab2d-7409b4e05ae0.png">

6. Lastly, when the "view credential" modal is open, we should mirror the form checkbox here in a readonly mode:
    <img width="542" alt="image" src="https://user-images.githubusercontent.com/8942601/234676671-40b3dd76-d31b-4055-a876-d20e9580ec8f.png">
    Or replace "enable" with "disable" if it is checked.

**Comment by st0nebraker** [comment]
New solution & FE work scoped, see #48611
