### ISSUE TITLE
no longer make repogroup:sample the default for non-signed-in searches on sg.com

### ISSUE THREAD

**Issue by ijt** [sourcegraph/sourcegraph#5095]
Searches on sourcegraph.com now default to the top 500 or so Github repositories, so there is no need to have another default with fewer results.

Here is what it currently looks like to land on sourcegraph.com/search without signing in:

![Screen Shot 2019-08-05 at 5 31 59 PM](https://user-images.githubusercontent.com/15530/62502999-18806580-b7a7-11e9-8db5-febd99b72e57.png)

We should no longer have the default text in the search bar.

**Comment by ijt** [comment]
CC @nicksnyder, @christinaforney

**Comment by nicksnyder** [comment]
I am fine with this. Want to move forward with opening a PR?

**Comment by nicksnyder** [comment]
(unless you are worried about https://github.com/sourcegraph/sourcegraph/issues/5094 and think we need to solve that first)

**Comment by ijt** [comment]
I think even with #5094 it's an improvement, so I'll go ahead and open a PR for this.
