### ISSUE TITLE
Autodetect `codebase` when a git repository is opened and show status of codebase

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#50971]
Instead of the user having to set the codebase, we should autodetect the codebase.

We should also show the user whether the codebase can be found on Sourcegraph, in the UI.

We should also show the user whether we have embeddings for the given codebase and whether they will be used.

**Comment by mrnugget** [comment]
I think this is covered by @abeatrix' work in https://github.com/sourcegraph/sourcegraph/pull/50952

**Comment by abeatrix** [comment]
My PR was about validating and displaying context fetcher in UI. I will look into auto detecting codebase next week, unless somewhere else has started works or want to work on it instead 😃

**Comment by deepak2431** [comment]
@mrnugget @abeatrix Can I take up this issue? 
I can think of a solution for this:
1. The rootpath of the project opened can be fetched.
2. There's a GraphQL query implemented, which we can use to check if the embeddings exist, and the other query to check if the repo exists.
3. On getting the result, we can populate the settings of VSCode, or it will use the default keyword search. 
4. The messages can be displayed to the user using VSCode error/info.

As there's a design label in this issue so I will wait for the updates on design changes as to how the different info/error should be displayed.

**Comment by mrnugget** [comment]
@deepak2431 we're doing our sprint planning tomorrow, let me get back to you after! (or @abeatrix will)

**Comment by deepak2431** [comment]
> @deepak2431 we're doing our sprint planning tomorrow, let me get back to you after! (or @abeatrix will)

Sure, that sounds good. Looking forward to it!

**Comment by abeatrix** [comment]
Update: This is covered by beyang's PR https://github.com/sourcegraph/sourcegraph/pull/51045
