### ISSUE TITLE
Add ability to edit and resubmit chat message

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#50974]
I want the same "edit and resubmit" functionality that ChatGPT has. I've been missing this a lot.

Sometimes I come up with an elaborate (and super smart, I swear) prompt and then notice I forgot something. But I can't get to the Markdown of the prompt so I essentially need to retype it somewhere else and resubmit.

**Comment by malomarrec** [comment]
@bachidegli
