### ISSUE TITLE
Add GitHub App Installation Access Token caching with Redis

### ISSUE THREAD

**Issue by pjlast** [sourcegraph/sourcegraph#51025]
[GitHub App Installation access tokens are valid for 1 hour](https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#create-an-installation-access-token-for-an-app)

This is short enough to not be worth storing in the DB whenever we update them, but we also don't want each and every service (repo-updater, each gitserver instance, etc.) to request an entirely new Installation Access Token whenever they do something. Especially if we're doing something like repo permissions syncing, making a new token for every repo sync is unnecessary.

Instead, we can cache the token in Redis and have the authenticator check there first.

Some thing to keep in mind:
- A token will be refreshed 5 min before it expires
- What happens if two separate services are busy with the token and try to refresh it at the same time?
  - This is not a big trainsmash since both tokens should still be valid, but ideally we want to "lock" the token as soon as a service starts to refresh it.

**Comment by pjlast** [comment]
@kopancek check where he did redis modifications and link it here.

**Comment by kopancek** [comment]
Finally remembered, it is here: https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/rcache/rcache.go?L79
