### ISSUE TITLE
Add configurable rate limit in front of LLMs on sourcegraph.com

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#51037]
This is the ticket to track the work in https://github.com/sourcegraph/sourcegraph/pull/50925.

I want to make sure that we don't lose track of it and don't deploy it, etc.

**Comment by mrnugget** [comment]
TODO:

- [ ] Fix the `EXPIRE` command so it also works with redis 5. Right now the `NX` parameter throws an error. It's only supported since 7.

**Comment by keegancsmith** [comment]
Erik and I chatted about this today and we came up with an alternative use of redis to implement rate limiting which works on older redis. I believe Erik is gonna code it up tomorrow (assuming he hasn't already done it and just hasn't sent the PR yet :P)

**Comment by eseliger** [comment]
I wrote the code for it but need to test it tomorrow morning 🙂

**Comment by eseliger** [comment]
https://github.com/sourcegraph/sourcegraph/pull/51138

**Comment by eseliger** [comment]
Implemented and rolled out.
