### ISSUE TITLE
gRPC: work with CS and delivery to identify customers with exotic firewalls 

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#51067]
In the Sourcegraph 5.0.X release, we implemented gRPC for a handful of services

- symbols
- searcher 
- gitserver
- repo-updater
- frontend's zoekt internal endpoints

Right now, gRPC is disabled by default. Our plan is in 5.2.X is to enable it by default (with the ability to fallback if necessary). 

However, there might be customers with exotic firewall and service mesh configurations (blocking binary traffic on certain ports), etc. that can block gRPC traffic.

We should work together with the customer support and delivery teams to identify customers with exotic firewall configurations that would be willing to work with us. 

In near future, after the 5.1.X release, we can ask these exotic firewall customers to try enabling gRPC to see if they run into any issues.

 We should also enable them / write documentation for how do you check to see if things are working correctly (Grafana dashboards, visual inspections, logs to see if grpc.Dial is working correctly). 

# how to enable gRPC

gRPC can be enabled via the experimental feature in the site configuration 

```jsonc
 "experimentalFeatures": {
    "enableGRPC": true
  },
```

It can also be controlled via the `"SG_FEATURE_FLAG_GRPC"` environment variable: 

https://github.com/sourcegraph/sourcegraph/blob/7f492bbf51888222c8f0966de74b812d10e59ebf/internal/grpc/grpc.go#L36-L43

**Comment by eseliger** [comment]
@ggilmore  Since we're on gRPC with no way back, can we close this ticket?

**Comment by ggilmore** [comment]
We already did this work to write a migration guide for these kinds of customers https://sourcegraph.com/docs/admin/updates/grpc
