### ISSUE TITLE
Cody recipe: show "no recent changes" in summarize-changes recipe if there are none

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#51084]
This came up in Slack. When there are no recent changes in the selected timeframe, Cody simply replies with a blank answer. Instead we should say that there are no recent changes in the timeframe.

**Comment by deepak2431** [comment]
@mrnugget  On looking into this, currently; the message is just a console log, [Line 49](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/cody-shared/src/chat/recipes/git-log.ts?L49)
Making a PR for this!

Also, in line [61](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/cody-shared/src/chat/recipes/git-log.ts?L61), there's a simple TODO related to message display. Shall I take care of it in the same PR?

**Comment by mrnugget** [comment]
yeah, that'd be good! I think it doesn't have to be a warning though. Can just be a normal chat response.
