### ISSUE TITLE
Handle rate limit errors correctly

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#51090]
Since #50925 we have rate limiting for the completions API. We need to make sure that the web client handles this correctly.

**Comment by thenamankumar** [comment]
@taylorsperry hey, what will be the best message to display to the user in case Cody hit rate limits?

**Comment by taylorsperry** [comment]
@mrnugget has a suggestion for the actual rate limits [here](https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1682431165672239?thread_ts=1682364671.984449&cid=C04MSD3DP5L) and we should be aligned/have a decision after our sync on Wednesday. 

For error handling, I'm inclined to not reinvent the wheel. The ChatGPT UI looks like this: 

<img width="531" alt="Screenshot 2023-04-25 at 8 44 58 AM" src="https://user-images.githubusercontent.com/43555476/234314037-fe6e4748-b276-45e1-9d64-88a88e271325.png">

**Comment by eseliger** [comment]
@thenamankumar I have tried it locally just now to see if it is a problem and seems like we just hang and retry indefinitely. 

![Image](https://user-images.githubusercontent.com/19534377/234543433-6a15abd6-650c-4b83-a0e5-0ab0ffd39eb7.png)


The Cody VSCode client renders the rate limit error message in a banner correctly now.
