### ISSUE TITLE
cody bug: vsce chat history UI is broken

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#51101]
The UI was working previously with the old chat layout: https://github.com/sourcegraph/sourcegraph/pull/50036

![Image](https://user-images.githubusercontent.com/68532117/234335598-c6ecd543-5f97-4656-b950-57ccbf4f2bd4.png)

Currently looks broken after we have removed the bubble chat layout:

![Image](https://user-images.githubusercontent.com/68532117/234335352-295b9232-bd43-4031-b6e9-372b256270c3.png)

**Comment by philipp-spiess** [comment]
There's also @thenamankumar's awesome work for the Web UI which we might be able to reuse here? :) https://github.com/sourcegraph/sourcegraph/pull/51072

**Comment by SuperAuguste** [comment]
I plan on reusing parts of that PR so it looks as awesome as and consistent with the web interface :)
