### ISSUE TITLE
Precise code intelligence support for C++

### ISSUE THREAD

**Issue by christinaforney** [sourcegraph/sourcegraph#5114]
There are still many unknowns if a language server or LSIF is the right choice for precise code intelligence support for C++. 

Depending on the customer and their configuration, size, etc, it would help us to understand the following questions:

- Are they willing to add a step to their CI for every repository they want code intel on?
- Can they deploy a language server?
- What's the output of `cloc` for a sample set of repositories? How big is their biggest repository?
- What is the rate of commits for a sample set of repositories?
- How much disk/compute resources are they willing to spend on code intel?
- How interested are they in cross-repo support?
- Is it OK for them to not see code intel until CI completes (when LSIF data is uploaded)? If not, we can try falling back to older LSIF dumps or use a language server for recent commits
- Roughly how many concurrent users do they have on their Sourcegraph instance at peak times?
- Can we get copies of a few of their repositories to test against?

Here is a breakdown for both language server support and LSIF support. It is unclear which is the right path to go down at this point in time:

Rough roadmap for a language server:
- 2 weeks: make the clangd language server work on Sourcegraph (Dockerize it, WebSockets, zip fetching, etc.
- 2 weeks: implement lazy analysis if startup time is a problem
- 1 week: first stab at cross-repo support

Rough roadmap for LSIF:
- 2 weeks: create an LSIF generator for C++
- 1 week: use SQLite as a backend instead of JSONL files if memory usage and startup time is a problem
- 1 week: fetch LSIF data from something like S3 if high disk usage is a problem
- 2 weeks: compute deltas between commits if generating LSIF for the whole working tree is too slow

**Comment by sqs** [comment]
Update: We have LSIF support for C++ in progress at https://github.com/sourcegraph/lsif-cpp.

**Comment by macraig** [comment]
Update: lsif-cpp has been deprecated, we now have LSIF C++ support at https://github.com/sourcegraph/lsif-clang
