### ISSUE TITLE
Proposal: External Service General Protocol

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#5115]
>Special thanks to @tsenart for [showing an excellent example of a good proposal](https://github.com/sourcegraph/sourcegraph/issues/4812)!

## Abstract

This proposal outlines a potential new approach to integrate the Sourcegraph instance with arbitrary code hosts.

## Background

External service (i.e. `repo-updater`) is the very entry point of how the Sourcegraph instance finds out what repositories are available and where it should clone from. Currently, every implemented external service is a specialized client of target code host, e.g. GitHub.com, GitLab.com, etc., due to the fact they provide different sets of APIs.

The current workflow to have the Sourcegraph instance supporting a new type of external service works like this:

1. User submits feedback
2. Allocate manpower to work on it
3. Release out with a new version

#### Time consuming and low priority

Besides few well-known public services and their on-premise versions, if the user wants to integrate the Sourcegraph instance with a code host that is not one of supported external services, he/she would either have to contribute him- or herself, or [wait a fairly long time](https://github.com/sourcegraph/sourcegraph/issues/343) for the Sourcegraph team to finally (or never) have some manpower to implement due to low priority.

#### Complicated and error prone to contribute

While adding basic support (i.e. repository syncing) of Bitbucket Cloud, [31 files were touched](https://github.com/sourcegraph/sourcegraph/pull/4825/files) across the whole sourcegraph/sourcegraph repository, this is fine for a member of the Sourcegraph team. However, it could be too much effort for a user to follow architecture design, codebase updates, and testing strategies in the sourcegraph/sourcegraph repository after (or even before) his/her initial implementation.

#### Awkward situation for community effort

Even if the user chooses to implement and sends a pull request, there is a huge risk for him/her that the Sourcegraph team decides it is not worth having such external support at core codebase because the Sourcegraph team will then be responsible for its healthy and correctness during the rest of its lifetime. 

This situation (i.e. pull request gets rejected) is very likely to occur when the target code host is only popular within a small range of people and/or a heavily customized version. This is also the major part of reason why the feature request is having such low priority in the first place.

In the current approach, meaning the Sourcegraph team could unwillingly narrow down the source of information (i.e. code host):

- The Sourcegraph team would love to have support of another code host but does not want the code to be merged into core codebase.
- The user does not want to spend the effort to maintain a fork of sourcegraph/sourcegraph repository.

Combine both cases, there is basically no way to make Sourcegraph work with any unsupported code hosts (though user can still manually manage the list of Git repositories via *Other* external service).

#### Duplicated logics

Even if a user's contribute is accepted, the list of unsupported code hosts can be infinite long.

#### Maintainability burden

For every supported code host, the codebase needs specialized test cases and set up test instance during integration testing. Suddenly adds extra but unnecessary responsibilities, including how to properly set up a code host instance, respond to its API breaks/changes, and take care of to its bugs in different versions under different circumstances.

## Proposal

To address the problems described above, I propose to unify future implementations of external services, namely **External Service General Protocol**. With a unified protocol and procedures, the Sourcegraph instance can communicate to arbitrary code hosts directly or via a proxy. We can also address all of the identified problems at once.

1. **Priority is no longer an issue**: Instead of waiting the Sourcegraph team to accept the idea and find time to implement, the user, the maintainer/owner of code host, or anyone in the community who is interested, can offer help implement:
    - A native integration directly in target code host codebase.
    - A proxy which speaks the protocol and translates between the protocol and equivalent APIs of the target code host.
2. **Read docs is sufficient**: Without dive deep into sourcegraph/sourcegraph repository, the person who is interested in implementing the protocol to target code host can solely rely on the documentation, has confidence and guarantee to work nicely with the Sourcegraph instance. In short, the user will use an adapter package that requires to implement an interface `ExternalServicer`, and the adapter package takes care of all the communications to the Sourcegraph instance.
3. **User contribution is satisfied**: The risk of getting rejection on one's work is eliminated since the code does not need to be merged into sourcegraph/sourcegraph repository, gives him/her total control of his/her contribution.
4. **One language talks to all**: With a unified protocol and procedures, all parts of the system (inside and outside Sourcegraph) can safely corporate. For integration testing, the Sourcegraph team then only need to make sure the Sourcegraph instance speaks the protocol in a correct manner, regardless of any customized setup and related issues.

The most up-to-date [specification can be read here](https://www.notion.so/unknwon/External-Service-General-Protocol-c422e3b76c574b94b44674aa34c7236b).

## Rationale

This proposal aims to solve the problem once for all, allow much easier integration with any unsupported code hosts with community effort, and release responsibilities of implementing and maintaining those efforts from the Sourcegraph team.

## Compatibility

Since this protocol will be added as another type of external service independently, there is no known compatibility issues in initial implementation or with any other parts of the current system. The foreseeable compatibility concern is we should try our best effort to make the protocol in the way that we are able to incrementally add more features/details in the future.

Worth noting that the specification correlated to this proposal has defined a `/info` endpoint, it allows the Sourcegraph instance automatically recognizes sets of features that are implemented in the proxy or code host, and downgrades functionality gracefully whenever possible, but is still able to communicate.

## Implementation

For proxy and code host, any feature other than **repository syncing** is optional to the Sourcegraph instance, the proxy or code host can expose supported feature sets via `/info` endpoint:

```json
{
    ...
    "lsif_verification": true,
    "repository_permissions": false,
    "user_authentication": true
}
```

The road map in terms of the Sourcegraph instance:

- [ ] Repository syncing
- [ ] LSIF verification
- [ ] Repository permissions
- [ ] User authentication

**Comment by unknwon** [comment]
@sourcegraph/core-services please take some time to review, and any feedback is appreciated!

**Comment by tsenart** [comment]
Thanks you so much for this extensive proposal! This really helped us understand the motivation, benefits and drawbacks of your idea :clap:

As a response, we have two thoughts:

1. We think your list of pros/cons should be slightly adjusted:
    * Having to support this generic API across versions is a lot of work. Example: when we want to make breaking changes, we first need to deprecate the old version, then officially end support and then remove it. Considering the speed with which some of our customers upgrade their Sourcegraph instances, we fear that these deprecation-remove-update cycles could end up being really long. If a large-scale customer is stuck on an old version of this generic API and doesn't have the resources to upgrade to a new version, deprecating the API might not even be possible.
    * You mentioned that "the list of unsupported code hosts can be infinite long", but the in practice we feel like that there's probably only a handful of code hosts that are actually in use and that we don't support. In fact, there seems to be only one code host that users are asking for, namely gitea. 

2. So, considering that the list of pros/cons now has another big drawback (supporting the API) and one of its pros became smaller (in practice there's not an infinite number of unsupported code hosts, but only a handful), we think it's more efficient to
    * improve the process of adding a new external service by requiring less files to be changed/added. We think this is a fairly straightforward task that can yield a lot of benefits with little work: we can combine several packages into the `repos` package, make it easier to add tests for a new external service, replace the multiple switch statements for external-service-kinds with a single "external service map", etc.
   * create an external service for gitea

We feel that this would eliminate a lot of the drawbacks with the current approach while also capturing a lot of the benefits that adding a generic API would bring with it.

(PS: This was written by @mrnugget, from my account).

**Comment by unknwon** [comment]
Thanks for the feedback!

>(PS: This was written by @mrnugget, from my account).

I love this. LOL

>Having to support this generic API across versions is a lot of work. Example: when we want to make breaking changes, we first need to deprecate the old version, then officially end support and then remove it. 

There is a `version` field in the `/info` endpoint which tackles this problem specifically, and has ability to introduce breaking changes without actually breaking existing/older customer's implementations.

For example:

```json
{"version": 1}
```

vs

```json
{"version": 2}
```

Regardless of what other fields are required for each version.

The customer's implementation presents what version of the generic API it is using and the Sourcegraph instance can react to it correspondingly and precisely, e.g. identify version too old/new, fallback to older version still in deprecation-remove-update cycles (which is the same if GitHub releases v4 and we fallback to v3 if customer hasn't upgraded).

But yes, this `version` field only allows us freely introduce breaking changes, and if the primary concern is the way to completely remove the support of old APIs, then this won't help.

>Considering the speed with which some of our customers upgrade their Sourcegraph instances, we fear that these deprecation-remove-update cycles could end up being really long. If a large-scale customer is stuck on an old version of this generic API and doesn't have the resources to upgrade to a new version, deprecating the API might not even be possible.

The "large-scale customer is stuck on an old version" problem exists in every single feature needs communication to another system. Take existing external service client for example, Bitbucket Server currently does not support GraphQL and the way the Sourcegraph instance talks to its server is using RESTful APIs. At some point, a newer version of Bitbucket Server released with GraphQL support, and they will eventually deprecate the old RESTful APIs (what happened to GitHub API v1, v2), or if they don't deprecate so soon and we want to move forward with using GraphQL probably because that's more efficient.

What's our opinions and/or strategies on this?

>So, considering that the list of pros/cons now has another big drawback (supporting the API) and one of its pros became smaller (in practice there's not an infinite number of unsupported code hosts, but only a handful), we think it's more efficient to

Hmm, the primary focus of this proposal is: 

Not to rely on the Sourcegraph team's effort to implement/maintain/be responsible for support of a **specific** code host because the external APIs could change, break and/or have bugs, and low priority on our end.

If this statement can be invalidate in this particular case because we need to spend more effort on maintaining the generic APIs than accommodating changes to the external APIs, or adding a new external service, this proposal should not be accepted.

PS: I don't see the direct response to the priority problem, if we "always" have time, priority is not an issue, but that's not the case (at least is not what is happening). Would you mind comment some thoughts on this?

Besides, how do we decide which one needs more effort:

1. Syncing dev docs to tell others how our codebase is structured, what needs to be done for adding a new external service, and taking time to review pull requests with multiple round trips. Taking care of code host specific problems during integration testing.
2. Deprecating an old set of APIs, add new ones that we want, add docs for the new API version.

>improve the process of adding a new external service by requiring less files to be changed/added. We think this is a fairly straightforward task that can yield a lot of benefits with little work: we can combine several packages into the repos package, make it easier to add tests for a new external service, replace the multiple switch statements for external-service-kinds with a single "external service map", etc.

I agree, this is a good step forward both for us and others. 

>create an external service for gitea

My initial hackweek project was adding Sourcegraph support to Gogs, then I realize this can be generalized. If we decide add each one takes less effort in total, we could do that too.

Looking forward to your feedbacks!

**Comment by mrnugget** [comment]
> There is a `version` field in the `/info` endpoint which tackles this problem specifically [...]

Yes, we were aware of that when writing the previous response. But the caveat of the `version` field is, of course, that it means we need to support multiple versions. In my experience that's usually harder than keeping up with one other external API.

> The "large-scale customer is stuck on an old version" problem exists in every single feature needs communication to another system. Take existing external service client for example, Bitbucket Server currently does not support GraphQL and the way the Sourcegraph instance talks to its server is using RESTful APIs. At some point, a newer version of Bitbucket Server released with GraphQL support, and they will eventually deprecate the old RESTful APIs (what happened to GitHub API v1, v2), or if they don't deprecate so soon and we want to move forward with using GraphQL probably because that's more efficient.

Agree, that problem exist, but there are two differences:
1. We own the code and are free to implement the necessary changes whenever we see fit
2. We already have a clearly communicated policy in place ("we only support the last 2 major releases") that doesn't bind us to really old versions. Combine that with the monthly release cadence and we're far less tied down than if we were to support a generic API specification whose deprecation cadence would be dictated by changes to it. In other words and rather simplified: we only need to support old Sourcegraph code for 2-3 months, whereas we would need to support the generic API for... how long?

> If this statement can be invalidate in this particular case because we need to spend more effort on maintaining the generic APIs than accommodating changes to the external APIs, or adding a new external service, this proposal should not be accepted.

I personally think that's the case: it would be more effort with less payoff to maintain and build generic API support than to make it easier to add a new external service and then add them ourselves and/or add a documented checklist for others to add one themselves.

> PS: I don't see the direct response to the priority problem, if we "always" have time, priority is not an issue, but that's not the case (at least is not what is happening). Would you mind comment some thoughts on this?

Can you clarify what you mean with the "priority problem"? I tried to stay clear of anything regarding priority, because I feel that it's a product decision that should be made by @christinaforney or @sqs.

> Besides, how do we decide which one needs more effort:
> 
>     1. Syncing dev docs to tell others how our codebase is structured, what needs to be done for adding a new external service, and taking time to review pull requests with multiple round trips. Taking care of code host specific problems during integration testing.
> 
>     2. Deprecating an old set of APIs, add new ones that we want, add docs for the new API version.

Again, I do feel that once the cards have been put on the table it's a product decision. And also: I'd rather use the "allow others to contribute with the right to modify/remove the code in the future" option than the "support old blackbox code I don't have any control over"

Granted, that's the result of my experience maintaining public/private APIS for different client teams over the years where "deprecation" and "breaking changes" were always theoretical ideas and in practice transformed into "let's stay in close sync, keep the code working as long as possible and avoid breaking anything". It might be different here.

**Comment by unknwon** [comment]
>We already have a clearly communicated policy in place ("we only support the last 2 major releases") that doesn't bind us to really old versions. Combine that with the monthly release cadence and we're far less tied down than if we were to support a generic API specification whose deprecation cadence would be dictated by changes to it. In other words and rather simplified: we only need to support old Sourcegraph code for 2-3 months, whereas we would need to support the generic API for... how long?

Can't the same mechanism be reused? i.e. "we only support the last 2 major releases", "the generic API version used in your code host is too old and no longer supported in this version, please upgrade to at least x.y".

 >Can you clarify what you mean with the "priority problem"? I tried to stay clear of anything regarding priority, because I feel that it's a product decision that should be made by @christinaforney or @sqs.

You're right, this should be a product decision.

To make it a more direct question, in this case, why hasn't Gitea been supported?

>Granted, that's the result of my experience maintaining public/private APIS for different client teams over the years where "deprecation" and "breaking changes" were always theoretical ideas and in practice transformed into "let's stay in close sync, keep the code working as long as possible and avoid breaking anything". It might be different here.

I truly respect your knowledge and experiences because that's what I need to learn (or steal? 😏)

**Comment by mrnugget** [comment]
> why hasn't Gitea been supported?

Lack of time, I think. It's definitely nice to have, but customer-side demand hasn't been high enough to prioritize it over other work.

> I truly respect your knowledge and experiences because that's what I need to learn (or steal? 😏)

Careful there, I never said anything about knowledge, only experience — and those can be good or bad 😀

**Comment by unknwon** [comment]
>Lack of time, I think. It's definitely nice to have, but customer-side demand hasn't been high enough to prioritize it over other work.

Feels like we get back to square 1, we can put this proposal on hold until we have further needs/insights/feedback from others.

>Careful there, I never said anything about knowledge, only experience — and those can be good or bad 😀

Well... technically, knowing "those can be good or bad" is a knowledge of some kind. 🧐

**Comment by tsenart** [comment]
@unknwon: Can we close this? :-)
