### ISSUE TITLE
Adding Gitolite external service fails with Post http://127.0.0.1:3182/sync-external-service: EOF on sgdev

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#5119]
![image](https://user-images.githubusercontent.com/10532611/62620235-1211fb00-b919-11e9-84d6-a5c22908a292.png)

Config:

```jsonc
{
  // Use Ctrl+Space for completion, and hover over JSON properties for documentation.
  // Configuration options are documented here:
  // https://docs.sourcegraph.com/admin/external_service/gitolite#configuration

  "prefix": "gitolite.sgdev.org/",
  "host": "git@gitolite.sgdev.org"
}
```

The external service did appear on the page afterwards.

**Comment by tsenart** [comment]
The host in the config has a typo: `s/rog/org/`. If you fix that, and set-up [SSH authentication](https://github.com/sourcegraph/sourcegraph/issues/5119), does this still happen?

**Comment by tsenart** [comment]
@felixfbecker: Ping.

**Comment by felixfbecker** [comment]
The typo doesn't make a difference. I cannot reproduce this exact error anymore, but this happened on [sgdev.org](https://sourcegraph.sgdev.org/site-admin/external-services/RXh0ZXJuYWxTZXJ2aWNlOjEw). It seems to me like the problem here is not SSH auth, because as a user I should never see an error like `EOF`, which looks like there is some bad error handling that results in invalid messages somewhere, or maybe the service crashing completely?

I am now seeing a different (but equally "internal") error:

![image](https://user-images.githubusercontent.com/10532611/62865248-3e10f000-bd0e-11e9-98e9-1e15a214cb93.png)

**Comment by tsenart** [comment]
Closing until it resurfaces.
