### ISSUE TITLE
Scrolling position is not kept anymore when clicking "Show more"

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#5120]
#### How to repro:

- Make a search https://sourcegraph.com/search?q=test
- Scroll down to the bottom
- Click "Show more"
- Query is now https://sourcegraph.com/search?q=test+count%3A1000

#### Actual

Page is at the top

#### Expected

This used to restore scrolling position to where "show more" was clicked. A hash fragment with the position gets added, then gets removed, but the page doesn't scroll.

**Comment by slimsag** [comment]
> **Actual**
>
> Page is at the top

This is the expected behavior. Also note I tagged @sourcegraph/web in https://github.com/sourcegraph/sourcegraph/issues/7024 to define this behavior in an e2e test. Let's continue the discussion over there (whether you agree with the current behavior or not)
