### ISSUE TITLE
Repositories from gitolite don't clone

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#5121]
![image](https://user-images.githubusercontent.com/10532611/62621577-7f735b00-b91c-11e9-83ac-948d96999f94.png)

I've been waiting for 15min now and not a single repo showed up, but the status indicator shows "6 repos enqueued for cloning"

Possibly related to #5119

**Comment by tsenart** [comment]
Does following these updated docs fix it? https://github.com/sourcegraph/sourcegraph/pull/5148

**Comment by tsenart** [comment]
Closing until it resurfaces.
