### ISSUE TITLE
Setup: Revisit the local repositories setup pipeline 

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#51260]
## Feedback from user interviews

Users don't know how to best set up Sourcegraph with their repos, leading to a less than optimal set-up, leading to less likelihood of them finding a wow moment while using it. Only 1 of 8 users connected to a remote code host.

Users didn't know how many repos to add, many thinking that adding even 100 would be "too much."

Representative user quote: "[what [is] the advantage or disadvantages of adding a repository? Cuz there's obviously a lot there and a lot of, lot of repos there. I've got, you know, that's all the ones that I've had in previous lives. And are there any disadvantages to having to index them?](https://sourcegraph.dovetailapp.com/data/3ulhqqBRSRSB3iOegrm5uT#:v:h=4B1ajM5vbOwMJ13wL8pAeW)"

## Possible solutions/suggestions
- An easy fix: add better, more noticeable copy about what repos to add at each step (e.g. “Choose all the repos you are currently working on plus the repos that would be helpful to support your work,” etc.)
- One step for local/remote
- Skip the remote repositories step completely when we set up Sourcegraph app?

**Comment by taylorsperry** [comment]
Closing this as we've redesigned the setup experience to provide better guidance on which repos to add (local only), and moved the option to connect remote repos to only be available from settings.
