### ISSUE TITLE
Cody bug: code block rendering issue

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#51269]
RE: https://sourcegraph.slack.com/archives/C052G9Y5Y8H/p1682671438464739

Cody will display the cody block correctly initially

![Image](https://user-images.githubusercontent.com/68532117/235198404-deba81d0-5465-47e1-a578-5ccf29eca1c6.png)

But after a few (random) minutes it will get reverted to use HTML tags:

![Image](https://user-images.githubusercontent.com/68532117/235198826-7dad5e7d-8ee1-4d40-bc3c-c83cb0a87509.png)

**Comment by dominiccooney** [comment]
Prompting `Write "You & me" in various markdown block formats` twice still reproduces a lot of `&amp;amp;` in markup the second time. However & is escaped correctly in e.g. C++ blocks after that.

**Comment by philipp-spiess** [comment]
This looks good now :)

<img width="703" alt="Screenshot 2023-05-09 at 18 04 09" src="https://github.com/sourcegraph/sourcegraph/assets/458591/07b27c32-fe94-4a5b-be55-a227f321ae58">
<img width="687" alt="Screenshot 2023-05-09 at 18 04 06" src="https://github.com/sourcegraph/sourcegraph/assets/458591/536f993b-a7c5-44b4-bb3f-06d9bd46ae13">
