### ISSUE TITLE
Embed Sourcegraph powered code snippets on Medium.com

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#513]
#### Feature request description

I want embedded code snippets like that on [Sourcegraph.com/start](https://sourcegraph.com/start) to work on Medium.com by making Sourcegraph an Embedly provider.

**Comment by felixfbecker** [comment]
Medium supports embedding GitHub gists. @ijsnow would the browser extension work on embedded GitHub gists?
