### ISSUE TITLE
Non-Stop Cody: Add task list to UI

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#51304]
RE: https://docs.google.com/document/d/1XNJo-ckxOmC-qHi6ffM6uwZ1WvW-DU9DNqHOO4qr2Lg/edit#heading=h.vc6aowsznlvr & https://github.com/sourcegraph/sourcegraph/issues/50914#issuecomment-1528689767

Chat sidebar needs a compact widget to display the tasks and batches, show the status—queued, ready to apply, has conflicts, done, etc. Chat will be happening around that widget.

Tasks are grouped into batches for the LLM. Batches have:
- A set of tasks.
- If the LLM has started running, a snapshot of the input text to the LLM. This is the basis for a 3-way diff when applying the change.
- If the LLM has finished running, the text output by the LLM.
Batches have states:
- Running—the LLM is chewing on them.
- Ready to commit—there’s an edit and we can apply it without conflicts
- Conflicts—there’s an edit but it has conflicts with user edits
- Applied—the user has applied the changes

**Comment by dominiccooney** [comment]
Per recent discussions, we plan to avoid adding a new widget. But we will display fixup task state in comments which show up in the comments panel.
