### ISSUE TITLE
Search results navigation via keyboard disabled by deafult

### ISSUE THREAD

**Issue by rakeshjosh2003** [sourcegraph/sourcegraph#51340]
- **Sourcegraph version:**  5.0.1
- **Platform information:**  reported by https://github.com/sourcegraph/accounts/issues/6716 via [slack](https://sourcegraph.slack.com/archives/C01D50MSA7L/p1683006900106189)

#### Steps to reproduce:

1.  Run a few searches on the search bar on the UI
2. Use Arrow keys to confirm no search history can be fetched

#### Expected behavior:
Keyboard navigation should work on the search bar to view history.

#### Actual behavior:
No search history is displayed using the keyboard on the search bar.

This works fine on version 4.5.1, but not working on version 5.0.1 and up.

If you would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are no [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

/cc @sourcegraph/search-product/search-core

**Comment by fkling** [comment]
Accessing the search history has been removed after redesigning the search input. It can now be accessed via the history button at the beginning of the input. 

We are constantly working on improvements oft the search input though, including making the history easier to access, so we'll keep this in mind.
