### ISSUE TITLE
Selected context is reset when browser page is refreshed

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#51365]
- **Sourcegraph version:** surcegraph.com / 5.0.1
- **Requested by:** https://github.com/sourcegraph/accounts/issues/6716 via [Slack](https://sourcegraph.slack.com/archives/C01D50MSA7L/p1683026822073089)

#### Steps to reproduce:

1. Perform a search using a specific context ([example on sourcegraph.com](https://sourcegraph.com/search?q=context%3A%40sourcegraph%2Fdeploy-sourcegraph+test&patternType=standard&sm=1&groupBy=repo))
2. Go back to the home page by clicking on the sourcegraph logo in the upper left corner.  The context is set to the one selected (as expected).  Example below
![image](https://user-images.githubusercontent.com/23640224/235697225-54fee590-7d88-417c-8b1e-1494b792454a.png)
3. Reload the browser page

#### Expected behavior:

The context is set to the one selected in step 1

#### Actual behavior:

The context is reset to the global context

![image](https://user-images.githubusercontent.com/23640224/235697681-917b34c7-13a9-4a61-83eb-4c270253eb72.png)

If you would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are no [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

/cc @sourcegraph/search-product

**Comment by camdencheek** [comment]
This is still a problem. When we've had reports like this before, naive efforts to reproduce have failed and we've just shrugged and moved on. I can still reproduce this as described in the issue.

**Comment by fkling** [comment]
@camdencheek I thought this was an intentional decision. I don't remember if we ever persisted the last selected context.

**Comment by camdencheek** [comment]
Yep, I think that's right. It is possible to set a default context for your user, but contexts are not sticky across search sessions.
