### ISSUE TITLE
upgrades: Have migrator "up" alias "upgrade" when auto-upgrade is set in the database

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#51375]
When `auto_upgrade` in the `upgrades` table is set to true, we should upgrade `migrator up` to `migrator upgrade` with inferred to/from/etc flags. `migrator up` is the default entrypoint, meaning that we can get the upgrade to run automatically via this database flag on a container restart (specifically, restarting when a new container tag).

**Comment by Strum355** [comment]
Closed by https://github.com/sourcegraph/sourcegraph/pull/52242
