### ISSUE TITLE
upgrades: Rewrite db-connecting pods to spin-wait while the initial Postgres DSN are a opaque string signifying that a upgrade is in progress

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#51374]
The frontend process initialization reads a DSN from the environment/site-config, connects to the database, and sends these values to all other db-connecting containers via config polling (see #51373).

When an upgrade is in-progress (signified by `auto_upgrade` being true in the `versions` table), the frontend should spin-wait before becoming ready and pass an opaque value indicating all other pods to also spin-wait until the upgrade has completed. Note that `auto_upgrade` must be set back to false after a successful upgrade (which I don't think it currently does) for this to work.

This will effectively make it so that all pods restart and wait on the multi-version upgrade condition without requiring a user to do much more than the "standard" upgrade procedure.

**Comment by Strum355** [comment]
Closed by https://github.com/sourcegraph/sourcegraph/pull/52242
