### ISSUE TITLE
upgrades: Infer upgrade flags by default (and remove documentation about supplying them where possible)

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#51376]
Right now the user can supply `--to` and `--from` flags, but are inferred by default. This is misleading for users in the generic use case, which can be clarified by:

- Removing from user-facing documentation the `--to` and `--from` flags (always infer them)
- Keep `--to` and `--from` around, but only accept them if a new flag `--explicit-versions=true` is supplied as well (error if `--to` or `--from` are supplied to catch users of "legacy" documentation0

**Comment by Strum355** [comment]
Mostly done by https://github.com/sourcegraph/sourcegraph/pull/52242 ? Will keep open for docs discussion

**Comment by efritz** [comment]
New auto-MVU docs cover this until we can get rid of the legacy docs.
