### ISSUE TITLE
Account security page does not show SCIM account as linked on S2

### ISSUE THREAD

**Issue by kopancek** [sourcegraph/sourcegraph#51396]
More details in slack thread: https://sourcegraph.slack.com/archives/C03GMM0F2BA/p1683097449079099?thread_ts=1683060403.165289&cid=C03GMM0F2BA

But basically, when adding a SCIM account, that is linked to existing account. Go to account security page after the accounts are linked, the SCIM account does not show up as linked...

![Image](https://user-images.githubusercontent.com/9974711/235852525-45477e08-09c9-44e9-a188-cc3a90f5d0e0.png)

/cc @sourcegraph/source

**Comment by pjlast** [comment]
This is no longer an issue. Tested on S2 by removing my Okta connection, and then signing in with Okta again.
