### ISSUE TITLE
Improve observability and control over repo deletion for disk space cleanup

### ISSUE THREAD

**Issue by marcleblanc2** [sourcegraph/sourcegraph#51440]
#### Feature request description

Reported by customer [6716](https://github.com/sourcegraph/accounts/issues/6716) in [Slack thread](https://sourcegraph.slack.com/archives/C01D50MSA7L/p1682579874730109) / support ticket [13659](https://sourcegraph.zendesk.com/agent/tickets/13659), discussed in [ask-repo-management thread](https://sourcegraph.slack.com/archives/C04M5M8GWCX/p1683062666348529).

Customer admins need more clarity and control on repo deletions when gitserver storage volumes hit the `SRC_REPOS_DESIRED_PERCENT_FREE` threshold. 

We need to [add an alert when repos are removed due to disk pressure](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@9cee218369d2b292439bed60b2e4a94aae19d983/-/blob/monitoring/definitions/git_server.go?L446:8), so admins can search their email / Slack for these alerts and see which repos have been deleted. 

We need to add a code host config to exclude specific repos from cleanup, suggested by @indradhanush [here](https://sourcegraph.slack.com/archives/C04M5M8GWCX/p1683105418281999?thread_ts=1683062666.348529&cid=C04M5M8GWCX), most usefully delivered via a list of `repo:` search patterns. Customers would use this to include their massive monorepos that take days to reclone. 

We need to add clarity to the `gitserver: less than 10|15% disk space remaining by instance for 10m0s` alerts|warnings
- Correct the [Interpretation and NextSteps messages](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@9cee218369d2b292439bed60b2e4a94aae19d983/-/blob/monitoring/definitions/git_server.go?L114:8) to match the operation, that this means Sourcegraph will attempt to delete repos to free up disk space in order of last modified date on disk, or correct the operation to match the messages that repos will be deleted based on least usage.
- The list of repos in scope to be deleted, or that have been deleted, so admins can panic and respond quicker if they see any high value repos on the chopping block

We need to change the logic to use a more Sourcegraph-user-centred approach when picking repos to delete, such as:
- The last time a repo was visited by a user
- The last time the repo showed up in a search result
- If the repo is in use in other Sourcegraph features, ex. open Batch Changes, Insights metrics, Monitors, etc., we should at least surface this repo deletion to these users, if not prioritize keeping these repos

The [current method](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@e08c73f544165a1f2fb9006cf4c835c6981b6b83/-/blob/cmd/gitserver/server/cleanup.go?L674-677) deletes repos that have the oldest modified time on disk, which can be caused by either:
- Code host sync issues, in this case
- Repo updater queue too long
- Code host users not pushing new commits, in the assumed case 

#### Is your feature request related to a problem? If so, please describe.

User and admin trust in the reliability of the system, and the system's ability to fail as gracefully as possible.

#### Describe alternatives you've considered.

- Admins not trusting that the system will fail gracefully, and thus not passing on this trust to their users
- Admin burnout reacting to ungraceful failures
- Customer admin cost of supporting this system, needing to spend more time managing the system, and configuring their own testing and alerting to ensure their high priority repos stay on the service, even if they have code host sync issues while their disk is full

/cc @ryphil @mrnugget

**Comment by eseliger** [comment]
The mentioned cleanup job no longer exists for customer deployments, it wasn't working as intended. 
Instead, customers will now be notified from the UI that a gitserver is low on disk, can inspect disk usage any time under **Site-admin > Gitservers**, and additionally we expose Grafana metrics on disk usage which can be alerted on.
