### ISSUE TITLE
Search query `repohascommitafter:"january 1 2018"` fails if you have an empty repository

### ISSUE THREAD

**Issue by eugeneiiim** [sourcegraph/sourcegraph#5149]
- **Sourcegraph version:** 3.6.0
- **Platform information:** N/A

#### Steps to reproduce:

1. Create an empty repository called `my-org/my-empty-repo` and allow Sourcegraph to import it.
2. Search for `repohascommitafter:"january 1 2018"`

#### Expected behavior:

The query should return results for repos with commits since January 1 2018.

#### Actual behavior:

Query returns an error: `Revision not found: git.blendlabs.com/my-org/my-empty-repo@HEAD (and 2 more)`

**Comment by christinaforney** [comment]
Hi @eugeneiiim - thanks for filing! We'll take a look.
