### ISSUE TITLE
Cody: Open context search results links as workspace file

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#51490]
Follow up on https://github.com/sourcegraph/sourcegraph/pull/51077

From beyang:
> Allowing users to click on results to open them up in the editor (rather than popping them over the browser)

@abeatrix:
The f[unction has been implemented ](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@9ef60634029a21d3aa24d9a0c273792909e43f62/-/blob/client/cody-shared/src/chat/recipes/context-search.ts?L70-75)but the file links were stripped off by the CodeBlock component.

**Comment by deepak2431** [comment]
@abeatrix Was trying to fix this, but I cannot get the results based on my query. In the console, when I tried to log the file content it's printing "fetching keyword context".  Here's the screenshot attached:


![iScreen Shoter - Code - 230505174120](https://user-images.githubusercontent.com/44617923/236454736-d5ec4f4d-d779-4f0d-b1ff-22d03dbc8793.jpg)

**Comment by abeatrix** [comment]
@deepak2431 hey hey thanks for looking into this!!

Do you get results if you switch the codebase to an embedded one? 

I'll investigate on the results for local keyword context in the meantime!

**Comment by deepak2431** [comment]
Yeah, for embeddings one it's working fine.

**Comment by shivasurya** [comment]
I believe DOMPurify in chat [markdown renderer](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/cody-shared/src/chat/markdown.ts?L49:17&popover=pinned) strips the custom scheme like `vscode://`. So, should we consider adding dompurify hook to fix this? but this approach opens up for other components using `markdown` rendering such as notebook (I guess)

```
purify.addHook('uponSanitizeAttribute', (node, data) => {
  if (node.nodeName === 'A' && node.getAttribute('href') && node.getAttribute('href').startsWith('vscode://')) {
    // Allow vscode:// URLs
    data.allowedAttributes['href'] = true
  }
})
```

**Comment by abeatrix** [comment]
> I believe DOMPurify in chat [markdown renderer](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/cody-shared/src/chat/markdown.ts?L49:17&popover=pinned) strips the custom scheme like `vscode://`. So, should we consider adding dompurify hook to fix this? but this approach opens up for other components using `markdown` rendering such as notebook (I guess)
> 
> 
> 
> ```
> 
> purify.addHook('uponSanitizeAttribute', (node, data) => {
> 
>   if (node.nodeName === 'A' && node.getAttribute('href') && node.getAttribute('href').startsWith('vscode://')) {
> 
>     // Allow vscode:// URLs
> 
>     data.allowedAttributes['href'] = true
> 
>   }
> 
> })
> 
> ```

Ohhhh that's a good suggestion! What about setting ALLOWED_URI_REGEXP to allow vscode://? 👀
