### ISSUE TITLE
Enhance Bitbucket Cloud integration repo syncing

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#5151]
As the merge of https://github.com/sourcegraph/sourcegraph/pull/4825, the basic repository syncing functionality was implemented:

1. Sync all repositories of the user who is authenticated via the client
2. Sync all repositories of selected teams

The following outlines some work and concerns could be done but has not done:

- **Rate limit calculation**: specifically, it is not for sure if the values of these two values are good (values took directly from Bitbucket Server but BbS allows 1000 items per request where BbC only allows 100 items per request):

https://github.com/sourcegraph/sourcegraph/blob/35a64b73c3d007c5832ffaf0bac98c8201e0d358/pkg/extsvc/bitbucketcloud/client.go#L35-L38

- **Supported parameters are not aligned with others**: missing `repos`, `exclude`(#6035), ~~`initialRepositoryEnablement`~~, `repositoryQuery`([doc](https://developer.atlassian.com/bitbucket/api/2/reference/meta/filtering))

**Comment by tsenart** [comment]
`initialRepositoryEnablement` is deprecated and should be removed everywhere.

**Comment by tsenart** [comment]
Repos are always enabled now. In the future we'll remove that field.

**Comment by unknwon** [comment]
@tsenart thanks for the info! I've updated the content.

**Comment by keegancsmith** [comment]
Is there anything actionable in this issue still, taking into account our current plans around permissions. IE can we close this out?

**Comment by unknwon** [comment]
This issue was more like a record keeping. But since the feature has been implemented quite a while ago, I'm incline to close it, and add more functionality per customer request basis.
