### ISSUE TITLE
gRPC: work with cloud to enable gRPC on managed instances 

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#51547]
In the Sourcegraph 5.0.X release, we implemented gRPC for a handful of services

- symbols
- searcher 
- gitserver
- repo-updater
- frontend's zoekt internal endpoints

Right now, gRPC is disabled by default. Our plan is in 5.2.X is to enable it by default (with the ability to fallback if necessary). 

gRPC has been running succesfully on sourcegraph.com, sourcegraph.sourcegraph.com, and k8s.sgdev.org. Running it on our managed instances would give us more feedback to see how gRPC performs with different load patterns , and allows us to address any issues that come up before we enable it for our self hosted customers. 

See https://sourcegraph.slack.com/archives/C03JR7S7KRP/p1683328251005059, where we just started the conversation with Sourcegraph Cloud

**Comment by eseliger** [comment]
rolled out!
