### ISSUE TITLE
bzl: migrate enterprise/cmd/bundled-executors

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#51552]
Migrate [bundled-executors](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/bundled-executor/Dockerfile) to Bazel.

Wolfi packages to use/create: 

- git 
- python3 
- py3-pip 
  - Why do we need this? 
- xmlstarlet 

Bazel targets to include 

- `//enterprise/cmd/executor`
- `//enteprise/cmd/batcheshelper` 
- `@src-cli`

**Comment by jhchabran** [comment]
@sourcegraph/batchers Hey folks, would be able to explain the need for python3-pip ?

**Comment by Piszmog** [comment]
This image is a one-off work around for a user. It was created to get them off the ground and use server-side batch changes. Python was one of their use-cases (see #50617)

**Comment by eseliger** [comment]
Yeah when the customer lets us know about new packages they need, we usually add them. Python and pip was one of the requests. This image should hopefully disappear after the next release once they upgraded to k8s based executors.

**Comment by jhchabran** [comment]
Thanks @Piszmog @eseliger 🙏
