### ISSUE TITLE
Code Intel: Need to add cross repo prototypes

### ISSUE THREAD

**Issue by cesrjimenez** [sourcegraph/sourcegraph#51593]
We recently added the ability to query for prototypes. See [here](https://github.com/sourcegraph/sourcegraph/pull/50667).

We need to build on top of this and add the ability to search for cross repo prototypes as well.

**Comment by efritz** [comment]
Fixed by #54410.

**Comment by varungandhi-src** [comment]
Closing since the fix PR was merged.
