### ISSUE TITLE
Cody issue with python extension on Ubuntu

### ISSUE THREAD

**Issue by rakeshjosh2003** [sourcegraph/sourcegraph#51612]
- **Sourcegraph version:**  5.0.2
- **Platform information:** Ubuntu 20.04.5 LTS

#### Steps to reproduce:

1. Configure Cody extension on vscode to use along with Python extension version: v2023.6.1
2. Typing anything on Vscode displays the below error, which is also shown in Cody logs

Error in provideInlineCompletionItems: Error: error parsing response CodeCompletionResponse: SyntaxError: Unexpected token o in JSON at position 1, response text: no route

This works fine on Mac os.
VScode version (1.77.3)

Related slack discussion [thread](https://sourcegraph.slack.com/archives/C03CSM27NAJ/p1683248373370019) here.

#### Expected behavior:
No Error message should be displayed

#### Actual behavior:
Error message displayed on VScode
Error in provideInlineCompletionItems: Error: error parsing response CodeCompletionResponse: SyntaxError: Unexpected token o in JSON at position 1, response text: no route

If you would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are no [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

**Comment by philipp-spiess** [comment]
Heya! Sorry to hear that. You can disable completions by changing this flag in your VS Code settings to `false`:

```
  "cody.experimental.suggestions": false,
```

We're also changing how errors are reported for completions (basically hiding it from the end user) because of the annoying messaging.

That said, do you have any idea why the API request to the cody backend returned "no route"? Which server are you running Cody against?

**Comment by philipp-spiess** [comment]
@rakeshjosh2003  (forgot to ping you above 🙂)

**Comment by rakeshjosh2003** [comment]
Hey @philipp-spiess ,

The server is client's internal server.
I can't see an option to define that in settings, even in json file it doesn't allow it. Is it configurable?

**Comment by rakeshjosh2003** [comment]
![cody](https://github.com/sourcegraph/sourcegraph/assets/102702631/ed96e791-dde2-43d3-a3a8-fb7322106cf0)

**Comment by rakeshjosh2003** [comment]
Hi @philipp-spiess, Yes, the issue is resolved. Thanks for the quick fix.
