### ISSUE TITLE
Cody feature: allow editing previous prompts and wipe following history

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#51632]
See here: https://github.com/sourcegraph/sourcegraph/discussions/48334#discussioncomment-5822314

The idea is that Cody should behave just like ChatGPT: you should be able to edit a previous prompt and if you do you can resubmit it and the rest of the interaction disappears

**Comment by thenamankumar** [comment]
Edit last message feature is available on both vscode and web now. Closing the issue.
