### ISSUE TITLE
Add hover tooltips to intent-detection underlines

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#51633]
Our UI right now doesn't explain what the intent-detection underlines are. We just have colored underlines but if the user doesn't know what they mean, they're lost

**Comment by deepak2431** [comment]
![iScreen Shoter - Code - 230510190230](https://github.com/sourcegraph/sourcegraph/assets/44617923/2f4fda58-7c28-403b-aea1-eb915b98708b)

@mrnugget Was looking over this issue, just want to be more clear. Are you talking about these underlines?
Also, what message should be displayed on hover "Results of response intent" or something else?

**Comment by mrnugget** [comment]
Yep, that's exactly what I mean.

What I mean is that when you hover over a filename with green, a tooltip should say "This file exists", on orange "this file does not exist" etc.

**Comment by deepak2431** [comment]
Got it, Thanks!

**Comment by deepak2431** [comment]
@mrnugget A bit late here, as I was looking into other issues. I have opened a PR for this. Do check it out!
