### ISSUE TITLE
Cody Web pane should be default expanded/open

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#51644]
We are in early preparations to roll out Cody for enterprise users. To make the "try Cody" experience more intuitive, we'd like the Cody pane on the right to be open by default.

![Image](https://user-images.githubusercontent.com/526432/236355072-c7f89abe-5a92-4cb8-9a28-cbcf7684315c.png)

- [ ] Cody pane on the right must be open by default on sourcegraph.com
- [ ] Cody pane on the right must be open by default on sourcegraph server
- [ ] Cody pane on the right must stay closed for the rest of the session, when closed by the user
- [ ] Cody pane on the right must reopen on the next sourcegraph session

**Comment by mrnugget** [comment]
cc @flying-robot agree with this?

**Comment by rrhyne** [comment]
No, I do not. I've reached out to Greg to discuss how he can collaborate with @almeidapaulooliveira and @thenamankumar and team on how to solve the problem of Cody discoverability.

**Comment by almeidapaulooliveira** [comment]
@rrhyne, I talked with @gwestersf. I think having the Cody tab opened by default (as the initial state) would be a good quick win to make it more discoverable (plus all the Frictionless Cody flow we're implementing). Wdyt?

**Comment by rrhyne** [comment]
Let's get it into a quick design process. I'd much rather we use a technique like I did on the file page:

![image](https://github.com/sourcegraph/sourcegraph/assets/539268/6f60b992-0a98-4c1c-90ca-c59690498908)

**Comment by thenamankumar** [comment]
I like @rrhyne's idea.
