### ISSUE TITLE
ranking: Support re-indexing configuration

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#51672]
We need a way to specify _when_ a ranking job should be kicked off. We can possibly do this continuously now that we can report higher-fidelity progress. Having a simple set of rules in site-config would also be sufficient.

**Comment by efritz** [comment]
cc @jtibshirani Do you have any gold-standard ideas for what we could have in site-config about _when_ a ranking job should be kicked off? We could support on-demand + some sort of scheduled cadence (to prefer weekends, for instance).

**Comment by jtibshirani** [comment]
I think a Cron expression (or something similar) would be useful. That way, the admin could say "every evening at this time" or "every weekend at this time".

Doing it continuously would be very cool, but maybe that's a future step? It's trickier on the Zoekt side and would require some work to make efficient.
