### ISSUE TITLE
repoHasFile:foo gets silently misinterpreted as a literal pattern

### ISSUE THREAD

**Issue by ijt** [sourcegraph/sourcegraph#5168]
The query parser expects this field to be written all lower case like `repohasfile:foo`.

Writing it as `repoHasFile:foo` gets no results because that is interpreted as a literal pattern:

<img width="484" alt="Screen Shot 2019-08-12 at 9 41 14 AM" src="https://user-images.githubusercontent.com/15530/62882570-0e022680-bce7-11e9-9f68-40f73d8e5b18.png">

Writing it as `repohasfile:foo` works as expected:
<img width="538" alt="Screen Shot 2019-08-12 at 9 52 14 AM" src="https://user-images.githubusercontent.com/15530/62882637-2ffba900-bce7-11e9-8340-7611469853b6.png">

**Comment by ijt** [comment]
Desired behavior: It should either report an error or just work.

**Comment by nicksnyder** [comment]
My suggestion would be to make all filters case-insensitive
