### ISSUE TITLE
Cody: rg command window appears when using keyword context on Windows

### ISSUE THREAD

**Issue by dominiccooney** [sourcegraph/sourcegraph#51685]
- **VSCody extension version:** 0.0.10
- **Platform information:** VSCode 1.78.0-insider on Windows 10 21H2 19044.2846

#### Steps to reproduce:

1. Open a local repository, so Cody uses keyword embeddings
2. Activate fixup

#### Expected behavior:

No window pops up.

#### Actual behavior:

Ripgrep pops up a terminal window.

![Screenshot 2023-05-10 085335](https://github.com/sourcegraph/sourcegraph/assets/55120/71ae2ad5-5417-4d1f-9fb8-7e0b7052accc)

**Comment by philipp-spiess** [comment]
Some notes while I'm still on the Windows machine:

- Without any setup, Cody won't run keyword search at all on windows.
- I noticed in @dominiccooney's screenshot that he used `chocolatey` to install rg which I then also did
- With `rg` installed, it will now spawn the window and nothing more will happen.

So I think there are two issues here:
- We need to verfify if we properly bundle a `.exe` for ripgrep
- We need to use our bundled version over the one in `PATH` (or whatever the win equivalent of that is).

As a side node there seems to be some font issues with code blocks in the markdown in inline fixup. 🙈 

<img width="795" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/458591/7d6873b8-5f43-47ad-95d4-248d8a153f6f">
