### ISSUE TITLE
Some config options require a server restart but shouldn't

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#517]
Most config options can be applied on-the-fly now, and the ones that cannot are being moved into the management console soon.

See conversation: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/pkg/conf/conf.go?utm_source=email#L247:4-248:4&tab=discussions&threadID=80&commentID=108

- [ ] Once implemented, update or remove this log line: https://github.com/sourcegraph/sourcegraph/pull/2115/files#diff-6cc202581c2d5909ef0338c42176f3bcR165

**Comment by slimsag** [comment]
We'll tackle this soon, but not in 2.13.

**Comment by nicksnyder** [comment]
Is this fixed/obsolete in master?

**Comment by slimsag** [comment]
no

**Comment by keegancsmith** [comment]
What needs to be different, it isn't clear to me? Any management console change restarts everything; everything else on the fly?

This is also the sort of thing I can take of your hands if you like.

**Comment by slimsag** [comment]
I have a lot of extra context around how this would work, so I'll handle this one.

**Comment by slimsag** [comment]
I've added a point to document that changing some properties requires a restart in the interim to https://github.com/sourcegraph/sourcegraph/issues/1428

In 3.1 we should definitely fix this, but won't land in time for 3.0

**Comment by slimsag** [comment]
I won't get started on this by EOD as I didn't account for meetings I have. Deferring.

**Comment by slimsag** [comment]
Backlogging for now to reflect the fact that I don't have time to work on this. What we do have in place is documentation that does state you need to restart services when specific config options are changed. It sucks the UX doesn't tell you or do it for you -- but it's not the end of the world.
