### ISSUE TITLE
Batches: `Check State` doesn't seem to update without manual refresh

### ISSUE THREAD

**Issue by DaedalusG** [sourcegraph/sourcegraph#51782]
- **Sourcegraph version:** v5.0.3 
- **Platform information:** docker-compose 

#### Steps to reproduce:

1. Run a batch change against a repo that does CI checks, it needs to be published
2. observe that the state is initially set to pending

#### Expected behavior:

In a relatively short period of time (especially with webhooks) this state should be updated without any manual action

#### Actual behavior:

To update the state you've got to press the refresh button on each changeset

#### Waiting for the checks to finish --

<img width="1117" alt="Screenshot 2023-05-11 at 2 50 20 AM" src="https://github.com/sourcegraph/customer/assets/13024338/54db34a0-98c9-4c83-9210-6bec4d6f263d">

#### Checking the `check state` after a little time has passed --

_Note I didn't wait a huge amount of time here -- about 5 or 10 minutes, I did refresh the page, and the instance I was using is well resourced and had no other changesets being computed etc_

<img width="1699" alt="Screenshot 2023-05-11 at 2 50 05 AM" src="https://github.com/sourcegraph/customer/assets/13024338/3e7eaa2f-5d31-42ae-89dd-62e0a221edf3">

#### Check state after a refresh --

<img width="1053" alt="Screenshot 2023-05-11 at 2 50 41 AM" src="https://github.com/sourcegraph/customer/assets/13024338/e5c6b31e-7c0c-498d-a460-72b7aa924966">

If you would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are no [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

**Comment by DaedalusG** [comment]
In order to get a little more rigorous test I reran and force updated the CI tests again setting the state to pending. After 23 minutes the sync still hasn't been checked according to the UI
<img width="1009" alt="Screenshot 2023-05-11 at 3 48 10 AM" src="https://github.com/sourcegraph/sourcegraph/assets/13024338/3a48c5d8-cb2c-4ef3-a469-06513f9bb776">

A sync immediately refreshes the `check state`
<img width="991" alt="Screenshot 2023-05-11 at 3 49 05 AM" src="https://github.com/sourcegraph/sourcegraph/assets/13024338/4eaa7147-4d1f-4b51-9ec3-98b22313d36a">

**Comment by DaedalusG** [comment]
After some additional testing I did find that the check state eventually updates when no webhooks are enabled: 
![Screenshot 2023-05-11 at 10 27 25 AM](https://github.com/sourcegraph/sourcegraph/assets/13024338/53897e2e-2126-4261-bb84-1058463428e6)
^^ here I left this overnight

**Comment by DaedalusG** [comment]
After enabling a webhooks and attempting this batch change again the instance `check state` hasn't updated by automation for two hours:
![Screenshot 2023-05-11 at 1 55 02 PM](https://github.com/sourcegraph/sourcegraph/assets/13024338/c1ce3b41-9092-47a8-a71e-9350cadd760a)
_Will leave running to see how long the check will go un updated_

**Comment by DaedalusG** [comment]
With webhooks enabled the update time is the same as without, updating automatically somewhere around 8 hrs. I missed the hover script during testing but hovering over the refresh button shows that this is the expected sync time:
<img width="366" alt="Screenshot 2023-05-12 at 3 08 34 PM" src="https://github.com/sourcegraph/sourcegraph/assets/13024338/3eb70f5f-9709-4db1-bdae-641775145151">

_This said this long wait time may not be a bug, but is certainly a product gap. Users attempting to run a batch change to merge many changesets will likely need to closely monitor the `check state` of changeset as they monitor their CIs completion._

**Comment by BolajiOlajide** [comment]
I started looking into this last week Friday. I've reproduced it now; the webhooks payload is getting sent from the code host - so we can confirm it isn't a code host issue.

@DaedalusG I should have an update for you by tomorrow.

**Comment by BolajiOlajide** [comment]
```
"check_suite": {
    "id": 12905278104,
    "node_id": "CS_kwDOH1Ragc8AAAADATbqmA",
    "head_branch": "trois-pop-2",
    "head_sha": "972fc96f7d318f16c54d86fe4d75b9fe8822cf1f",
    "status": "completed",
    "conclusion": "success",
    "url": "https://api.github.com/repos/sourcegraph-testing/markdowns/check-suites/12905278104",
    "before": "0000000000000000000000000000000000000000",
    "after": "972fc96f7d318f16c54d86fe4d75b9fe8822cf1f",
    "pull_requests": [
      {
        "url": "https://api.github.com/repos/sourcegraph-testing/markdowns/pulls/33",
        "id": 1350971322,
        "number": 33,
        "head": {
          "ref": "trois-pop-2",
          "sha": "972fc96f7d318f16c54d86fe4d75b9fe8822cf1f",
          "repo": {
            "id": 525621889,
            "url": "https://api.github.com/repos/sourcegraph-testing/markdowns",
            "name": "markdowns"
          }
        },
        "base": {
          "ref": "main",
          "sha": "75824a1da2e35f5048a1be1b7d6c19daa3fef8bf",
          "repo": {
            "id": 525621889,
            "url": "https://api.github.com/repos/sourcegraph-testing/markdowns",
            "name": "markdowns"
          }
        }
      }
    ],
    "app": {
      "id": 15368,
      "slug": "github-actions",
      "node_id": "MDM6QXBwMTUzNjg=",
      "owner": {
        "login": "github",
        "id": 9919,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjk5MTk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/9919?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/github",
        "html_url": "https://github.com/github",
        "followers_url": "https://api.github.com/users/github/followers",
        "following_url": "https://api.github.com/users/github/following{/other_user}",
        "gists_url": "https://api.github.com/users/github/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/github/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/github/subscriptions",
        "organizations_url": "https://api.github.com/users/github/orgs",
        "repos_url": "https://api.github.com/users/github/repos",
        "events_url": "https://api.github.com/users/github/events{/privacy}",
        "received_events_url": "https://api.github.com/users/github/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "name": "GitHub Actions",
      "description": "Automate your workflow from idea to production",
      "external_url": "https://help.github.com/en/actions",
      "html_url": "https://github.com/apps/github-actions",
      "created_at": "2018-07-30T09:30:17Z",
      "updated_at": "2019-12-10T19:04:12Z",
      "permissions": {
        "actions": "write",
        "administration": "read",
        "checks": "write",
        "contents": "write",
        "deployments": "write",
        "discussions": "write",
        "issues": "write",
        "merge_queues": "write",
        "metadata": "read",
        "packages": "write",
        "pages": "write",
        "pull_requests": "write",
        "repository_hooks": "write",
        "repository_projects": "write",
        "security_events": "write",
        "statuses": "write",
        "vulnerability_alerts": "read"
      },
      "events": [
        "branch_protection_rule",
        "check_run",
        "check_suite",
        "create",
        "delete",
        "deployment",
        "deployment_status",
        "discussion",
        "discussion_comment",
        "fork",
        "gollum",
        "issues",
        "issue_comment",
        "label",
        "merge_group",
        "milestone",
        "page_build",
        "project",
        "project_card",
        "project_column",
        "public",
        "pull_request",
        "pull_request_review",
        "pull_request_review_comment",
        "push",
        "registry_package",
        "release",
        "repository",
        "repository_dispatch",
        "status",
        "watch",
        "workflow_dispatch",
        "workflow_run"
      ]
    },
    "created_at": "2023-05-15T15:02:15Z",
    "updated_at": "2023-05-15T15:02:29Z",
    "rerequestable": true,
    "runs_rerequestable": false,
    "latest_check_runs_count": 1,
    "check_runs_url": "https://api.github.com/repos/sourcegraph-testing/markdowns/check-suites/12905278104/check-runs",
    "head_commit": {
      "id": "972fc96f7d318f16c54d86fe4d75b9fe8822cf1f",
      "tree_id": "630d072c880dfbcca81c9a49c223b1c22e9f8ca0",
      "message": "\"Append Hello World to all README.md files\"",
      "timestamp": "2023-05-15T15:00:57Z",
      "author": {
        "name": "bool",
        "email": "REDACTED"
      },
      "committer": {
        "name": "bool",
        "email": "REDACTED"
      }
    }
  },
```

GitHub seems to have changed the payload structure for the `check_suite` event, which is causing the updates not to happen. Now that the root cause has been identified, I'll create a Pull Request to fix it.

The library we use [go-github](https://sourcegraph.com/github.com/google/go-github@v43.0.0/-/blob/github/github-accessors.go?L2048-2053) expects the repository field to be part of the `check_suite` object, however, it seems GitHub has removed that field. I can't find a changelog to confirm this. However, I can confirm from the [docs](https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#check_suite) that the `repository` field isn't part of the `CheckSuite` object anymore.

Thanks for your patience @DaedalusG
