### ISSUE TITLE
llmproxy: Determine if we need special Cloudflare configuration

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#51823]
Since we don't want disruptions from code blocks in conversations and the likes, we should make sure that we don't need to configure something additional on the cloudflare proxy side in front of our LLM Proxy deployments.

**Comment by bobheadxi** [comment]
The answer is "no" for dotcom, but we may need to fix sgdev: https://sourcegraph.slack.com/archives/C1JH2BEHZ/p1683773886805619

**Comment by eseliger** [comment]
👍
