### ISSUE TITLE
llmproxy: capture user ID in the BigQuery events

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#51853]
It is beneficial to capture the (opaque) user ID as part of the BigQuery events metadata in requests sent to the LLM proxy.

By using a combination of these user IDs and their product subscription ID, we are able to tell real-time accurate DAU of each instance and understand the usage distribution on all instances (e.g. find if one or few actors are sucking up all the quota).

Since these user IDs are opaque and meaningless outside the instance scope, there should be no PII concern.

We could re-use the `X-Sourcegraph-Actor-UID` or invent a new header name.

**Comment by keegancsmith** [comment]
Any preference here on the mechanism we use? Maybe me just being paranoid, but I would propose we use a different header name than our internal one. This just prevents coupling them since they should be treated differently.

**Comment by unknwon** [comment]
> Any preference here on the mechanism we use? Maybe me just being paranoid, but I would propose we use a different header name than our internal one. This just prevents coupling them since they should be treated differently.

@keegancsmith not more preferred on the existing header to me, i.e. anything that makes sense!
