### ISSUE TITLE
Cody Bug: endpoint setting in config and UI are not synced, cause failing auth issue

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#51869]
[Reported by Erik](https://sourcegraph.slack.com/archives/C052G9Y5Y8H/p1683842132063809):

Issue:
> it fails for wrong tokens, but doesn’t really do anything for a valid one

Cause:
> When cody.serverendpoint is set in settings.json but I use a different one from the UI it seems to be in a broken state

Suggestion: 
- remove endpoint config from user setting so that users will be directed to the UI for all configurations
- support multiple endpoints (eg dropdown menu like the one in browser extension)

**Comment by deepak2431** [comment]
@abeatrix Was looking into part-2 of this issue. Can you please point me out where I can see that implemented in the browser extension I couldn't find it.

**Comment by abeatrix** [comment]
@deepak2431 here is the screenshot from our browser extension regarding the dropdown menu:
![image](https://github.com/sourcegraph/sourcegraph/assets/68532117/2e8b3fdc-b3f7-44c5-9fb3-16f175cf02bc)

**Comment by deepak2431** [comment]
Thanks, @abeatrix. Let me look into this.

**Comment by deepak2431** [comment]
@abeatrix So, I was looking into the current implementation. For adding support for multiple endpoints, I would say the best is to include a new component to get, store and show the multiple endpoints added. On selecting a specific endpoint by the user, it should work the same as with the single endpoint for now.

To proceed with the implementation, I would have required the designs for the screen where the user would add new endpoints, display the added one, and select it.

Also, as @beyang is assigned this issue, if he is occupied I can make a PR after I get the designs!

**Comment by abeatrix** [comment]
@deepak2431 thank you, that makes sense to me! It seems like adding support for multiple endpoint is big task and deserve to be tracked in a separate issue, so I'll create a new issue for that tomorrow instead. 

Thank you so much for the offer btw! I believe this feature is currently not a priority right now so it's ok if we leave it for now 😁

**Comment by deepak2431** [comment]
@abeatrix  You're welcome! Great, that sounds good to me.

**Comment by abeatrix** [comment]
CC @toolmantim for design advices

**Comment by toolmantim** [comment]
@abeatrix I was investigating a simpler solution, and just opened #53081 which I think might cover it for now?
