### ISSUE TITLE
Figure out deployment story for embeddings proxy/api

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#51885]
Talk to Cloud team and write up a decision doc for whether we want to go with a separate deployment or a combined deployment with LLM Proxy.

**Comment by bobheadxi** [comment]
Proposal: https://docs.google.com/document/d/1N1S-WUejRIwyJlM5wCxX6vFTrYX-hW6ITX-kvBKggl8/edit#
