### ISSUE TITLE
WIP Proposal: Share prometheus rules and grafana dashboards across deploy contexts

### ISSUE THREAD

**Issue by uwedeportivo** [sourcegraph/sourcegraph#5188]
## Abstract

This proposal describes a way to share prometheus rules files and json files defining grafana dashboards across all deploy contexts.

## Background

A sourcegraph installation will soon provide out-of-the-box prometheus metrics and grafana dashboards to facilitate easier trouble-shooting for admins. These metrics and dashboards are not meant to be exclusive, they are just an initial set of ready-made out-of-the-box dashboards and they can be augmented with admin-defined additional rules and dashboards.

The sourcegraph deploy contexts are:

| Context | Config location of prometheus rules and grafana dashboards|
|---|---|
| dev/launch.sh | sourcegraph/sourcegraph/dev/{prometheus \| grafana} |
| single docker container | sourcegraph/sourcegraph/dev/{prometheus \| grafana} |
| docker cluster | sourcegraph/deploy-sourcegraph-docker/{prometheus \| grafana} |
| k8s cluster, sourcegraph.com | sourcegraph/deploy-sourcegraph/configure/prometheus |
| other...    | |

All deploy contexts will have instances of prometheus and grafana running. These instances need configuration. Parts of the configuration will be context-dependent (for example how prometheus finds its targets or how grafana finds prometheus). Those parts will be different in different deploy contexts and are not shared.

Most prometheus rules and grafana dashboards on the other hand will be the same for all deploy contexts and therefore should be shared instead of being duplicated for each deploy context.

There might be additional rules and dashboards for each particular deploy context that add/remove/override the shared configs. This should be supported in this proposal.

#### Maintenance

Changes to the shared rules and dashboards need to be propagated across all deploy contexts. 

### Expectation

With a given version of a sourcegraph installation there will be the expectation that all out-of-the-box rules and dashboards are present and the same independent of deploy context. This enables predictable debugging, monitoring and alerting.

## Proposal

It feels like the out-of-the-box shared dashboards are a fundamental part of the sourcegraph software installation if they are exposed in the UI. As such it probably is natural that they live somewhere in the sourcegraph/sourcegraph repo and are pulled into each deploy context from there. This way the dashboards are versioned together with a sourcegraph release.

How will each context get the configs ?

### dev/launch and single docker container

These two contexts already pull the configs from sourcegraph/sourcegraph/dev, so potentially only the location within the repo would change.

## Plan

- [ ] 
- [ ]

**Comment by slimsag** [comment]
@uwedeportivo this is finished, right? can we close now
