### ISSUE TITLE
cody-gateway: Limit number of concurrent requests per actor

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#51890]
Since we have a global imposed limit on API usage, we will want to limit a given actor in concurrency. We could do this by simply sleeping for a bit, or by rejecting requests with a retry after and add retry after handling in the client side.

**Comment by eseliger** [comment]
Instance wide percentage based concurrency limit per actor, configured through an env var.
We want to start with a 10s interval for that, with an env var to quickly configure this as well.

**Comment by bobheadxi** [comment]
The `StaticLimiter` model works well for this, we can just wrap them http-handler-style, building it up in `(*Actor).Limiter(...)`
