### ISSUE TITLE
Improve frictionless sign-up flow by skipping steps

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#51897]
On about.sourcegraph.com we have a flow that goes as follows:

1. "Get Cody for Free" CTAs (main hero, right nav, cody page, etc)
2. http://sourcegraph.com/search (unauthed)
3.  http://sourcegraph.com/sign-up
4. http://sourcegraph.com/search (authed)

 We want to adjust that to the following:

1. "Get Cody for Free" CTAs WITH OAUTH buttons (main hero, right nav, cody page, etc)
2. http://sourcegraph.com/search (authed)

![Image](https://github.com/sourcegraph/sourcegraph/assets/539268/cd6fdce7-cc3e-4e79-9a0c-e6db5eb78e82)

Implementation should include:
* Adding OAuth buttons for GitHub and Gitlab directly to the homepage hero signups
* Clicking other CTAs will open a modal with signup options in it
* Metrics for the actions changed have 

FIGMA:
https://www.figma.com/file/DIk3eGdgKszigQVec7Y8SD/Frictionless-cody?type=design&node-id=555-27031

**Comment by gitstart-sourcegraph** [comment]
Hi @rrhyne,
Sorry for the delay, access is granted now. Could you try again?

**Comment by rrhyne** [comment]
I still get this screen:



![Image](https://github.com/sourcegraph/sourcegraph/assets/539268/c4537907-29d8-452a-ae42-b2b32b87438e)

**Comment by gitstart-sourcegraph** [comment]
Ah sorry about that @rrhyne , sending you a mail to clarify the issue.
