### ISSUE TITLE
repohasfile: filter does not work with type:file

### ISSUE THREAD

**Issue by ijt** [sourcegraph/sourcegraph#5196]
To see the issue, try searching for [`repohasfile:dockerfile type:file "func main"`](https://sourcegraph.com/search?q=repohasfile:dockerfile+type:file+"func+main"+) and then click through on some of the repositories in the results to check if they have Dockerfiles. Here is a screencast showing that not all of them do:  https://screencast-o-matic.com/watch/cqj2bktcMt.

**Comment by ijt** [comment]
Thanks to @keegancsmith for asking a question that helped reveal this bug.

**Comment by unknwon** [comment]
Hmm... not sure if it's too late.

Took the example in the demo:

https://sourcegraph.com/github.com/ContainerSolutions/k8s-deployment-strategies/-/blob/app/Dockerfile

**Comment by ijt** [comment]
Oh, I may have made a mistake. I was only searching the root dirs of those
repos for Dockerfiles. This might not be a real issue after all. I'll have
to check but will probably have to wait until tomorrow morning.

**Comment by ijt** [comment]
Yes, it appears this issue is a non-issue. Closing it.
