### ISSUE TITLE
App: Test App connection with Cody with unverified email

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#52017]
Using Cody with dotcom now requires that the user has a verified email address.  Test the App Cody and VS Code -> App -> dotcom usage with a user with an unverified email address to ensure the proper error messages are returned to the user to know how to fix the issue.

**Comment by chwarwick** [comment]
@marekweb Since you've been working in this space this one just came up that dotcom now requires a verified email address for the Cody api's to work.  Without it they return a 403.  Since we are forwarding the LLM requests there this is likely to impact App.

There are new graphql queries available to check if the user has a verified email and if the cody apis are enabled.  

I _think_ we will probably need to forward those requests on to dotcom to check if the user has a verified email.

**Comment by marekweb** [comment]
I can confirm that there's an API error if we try using Cody via App with a user with an unverified email.

As an unverified email user, there's no indication right now that what you need to do is to verify the email. But at the time of writing this also seems to be the case when you try to use Cody with dotcom directly.

**Comment by marekweb** [comment]
See also:

- https://github.com/sourcegraph/sourcegraph/pull/51870
