### ISSUE TITLE
Improve the existing filepage TryCodyCTA

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#52034]
The design of the existing file page CTA leaves quite a bit of white space to the right of the image. Improve it to show the Cody chat window and a background gradient:

OLD version:

![Image](https://user-images.githubusercontent.com/539268/238753954-9f00e53f-f27e-4e14-bd94-0a0b7efac46c.png)

NEW version (figma): 

![Image](https://user-images.githubusercontent.com/539268/238753425-517b256d-b1ae-4aa6-a23a-4fe95691603c.png)

On larger screens, the two images can be center-aligned to a div that occupies half the screen, while the icon and text are left aligned in a div that occupies half the screen.

No change in action is required.

**Comment by gitstart-sourcegraph** [comment]
Hello @rrhyne,

Just a few questions regarding this issue, would greatly appreciate your assistance.

1. Is it possible to obtain a Figma link for the new update? This would allow us to conveniently access and review the latest changes.

2. Alternatively, if a Figma link is not available, could we be granted access to the second asset highlighted in the image below? Additionally, we would like to know the value of the gradient used in the banner's background.
![Screenshot 2023-05-17 at 7 44 56 AM](https://github.com/sourcegraph/sourcegraph/assets/89894075/d14bda9a-a6a4-426a-b181-edab2548df89)

3. Lastly, could you kindly clarify whether the gradient is intended to remain consistent in both light and dark modes?

Thank you.

**Comment by rrhyne** [comment]
Apologies, I did not specify dark mode styles for these pages. 

You can find them here:
https://www.figma.com/file/DIk3eGdgKszigQVec7Y8SD/Frictionless-cody?type=design&node-id=949-33623&t=Hr0XzGrA5FvEvjMr-4

And here:
https://www.figma.com/file/DIk3eGdgKszigQVec7Y8SD/Frictionless-cody?type=design&node-id=954-34539&t=Hr0XzGrA5FvEvjMr-4

All I've done was to change the background gradient and text color.
