### ISSUE TITLE
Make embeddings jobs cancellable

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#52066]
We can't cancel this:

<img width="958" alt="screenshot_2023-05-17_13 41 22@2x" src="https://github.com/sourcegraph/sourcegraph/assets/1185253/737bb1bc-e5d1-4942-95c2-5a00b41ac6c7">

But jobs can be cancelled. We already have this for other database-backed workers.

---

1. We need a GraphQL mutation, like this: https://github.com/sourcegraph/sourcegraph/blob/87b2b76b0f581d893941b9d37f0e644006a430c5/cmd/frontend/graphqlbackend/schema.graphql#L786-L791
2. Implemented roughly like this: https://github.com/sourcegraph/sourcegraph/blob/b94664e4b30426823033e4b16b0a8040bf4c5b8a/cmd/frontend/graphqlbackend/external_services.go#L433-L453
3. In the database layer we then need to cancel the job correctly: https://github.com/sourcegraph/sourcegraph/blob/b94664e4b30426823033e4b16b0a8040bf4c5b8a/internal/database/external_services.go#L1260
4. Make sure the worker job is actually killed

**Comment by jtibshirani** [comment]
Grabbing this because we want it up in the next couple weeks for the release. Please let me know if you were already looking into it!
