### ISSUE TITLE
cody should not reveal that it's built by anthropic

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#52061]
There's multiple prompts that trigger a response like this:

![image](https://github.com/sourcegraph/sourcegraph/assets/1185253/ee06ef13-3b6b-4cc8-89e2-e0fa7726007e)

We should figure out whether we can change our prompts to avoid this.

**Comment by philipp-spiess** [comment]
Made a typo: 

> Me: how are thouh
>
> Cody: I apologize, but I do not actually understand informal or archaic English phrases like "how are thouh". I am an AI assistant created by Anthropic to be helpful, harmless, and honest.
