### ISSUE TITLE
Bitbucket Server code host integration has old tooltips

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#521]
Reported by @doxxx at https://github.com/sourcegraph/sourcegraph/issues/395. The Bitbucket Server integration has old tooltips.

![image](https://user-images.githubusercontent.com/1976/47484895-b8a96700-d7f1-11e8-854a-dbc83d4f67c3.png)

**Comment by sqs** [comment]
@ijsnow Has this/will this be fixed by your general improvements to the browser extension code?

**Comment by ijsnow** [comment]
This is fixed in https://github.com/sourcegraph/browser-extensions/commit/9bd17ee3d8ba8afb73c3808387ecc28e62caadf0.
