### ISSUE TITLE
UI is hung when search results include a large single line Javascript file

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#52118]
- **Sourcegraph version:** 5.0.3
- **Reported by:** https://github.com/sourcegraph/accounts/issues/6938

#### Steps to reproduce:

This seems to be caused by the client-side syntax highlighting when there is a very large single-line Javascript file.

1. Search for something that will have a result in a large single line Javascript file.  For example: `context:global lang:javascript todo file:\.min\.js select:content` [[example](https://sourcegraph.com/search?q=context:global+lang:javascript+todo+file:%5C.min%5C.js+select:content&patternType=standard&sm=1&groupBy=repo)]
    * This will usually cause the the issues shown below.  If you don't spot it on the first try, you can add a large `count:` value to see it as well

#### Expected behavior:

Search results do not cause the UI to hang or crash regardless of their size

#### Actual behavior:

![image](https://github.com/sourcegraph/sourcegraph/assets/23640224/e86429eb-69b1-46ba-9565-81d231e22109)
![image](https://github.com/sourcegraph/sourcegraph/assets/23640224/29835f2e-5b03-4b6c-a1f8-8877a0d93671)

If you would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are no [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

**Comment by camdencheek** [comment]
Came across another instance of this organically. We should probably set a limit on the max length of lines that we request highlighting for since the highlight ranges can add a ton of complexity to the DOM
