### ISSUE TITLE
"Find implementations" doesn't return result from the line of the cursor

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#52132]
It looks like "Find implementation" currently excludes results from the same line as the request. This behavior is surprising when you do "Find implementation" on `extends FuzzySearch` in the line here https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/fuzzyFinder/CaseInsensitiveFuzzySearch.ts?L25#tab=implementations_typescript

![CleanShot 2023-05-18 at 09 18 17@2x](https://github.com/sourcegraph/sourcegraph/assets/1408093/4e4991bb-6afd-4200-b0c7-172fcd24771f)

The results are correct when you do "Find implementations" on the definition site of `FuzzySearch` shows three results

![CleanShot 2023-05-18 at 09 20 42@2x](https://github.com/sourcegraph/sourcegraph/assets/1408093/9bbe1440-20e3-445c-8938-f9ca3a95bed6)

**Comment by nitesh-dubey** [comment]
Hi @Numbers88s , @olafurpg, I was trying to debug it. Upon clicking `Find Implementations` in code-intel popover, I couldn't see any API calls being made in Network tab. When do these data get fetched from backend, and using which API ?

**Comment by efritz** [comment]
Fixed by #54410.

**Comment by varungandhi-src** [comment]
The current behavior after Eric's PR landed matches the desired behavior in the PR description; closing as completed.
