### ISSUE TITLE
Searching for `type:repo repohasfile:Dockerfile index:only` takes 10s on 10k repos

### ISSUE THREAD

**Issue by ijt** [sourcegraph/sourcegraph#5213]
Here it is on sourcegraph.com: https://sourcegraph.com/search?q=repohasfile:Dockerfile+type:repo+index:only.

<img width="641" alt="Screen Shot 2019-08-15 at 8 53 57 AM" src="https://user-images.githubusercontent.com/15530/63107698-48173680-bf3a-11e9-812e-a077e0ad8d9f.png">

The same problem is happening on k8s.sgdev.org:
<img width="625" alt="Screen Shot 2019-08-15 at 8 51 54 AM" src="https://user-images.githubusercontent.com/15530/63107578-0d150300-bf3a-11e9-9cd5-99672dc96e06.png">

https://github.com/sourcegraph/sourcegraph/pull/5189 was supposed to fix this.

**Comment by keegancsmith** [comment]
The implementation of `reposToAdd` creates a new query like `file:$pattern`. So it essentially throws away `index:only`. So the likely reason this was slow is it wasn't just using the index. Fixing the implementation to pass on index:only in this case might be more effort than it is worth to be honest.
