### ISSUE TITLE
In search results, error with "gob: unknown type id or corrupted data"

### ISSUE THREAD

**Issue by ijt** [sourcegraph/sourcegraph#5214]
Sometimes when running searches on sourcegraph.com, I'm seeing this error message in the results:

<img width="840" alt="Screen Shot 2019-08-15 at 9 24 23 AM" src="https://user-images.githubusercontent.com/15530/63109727-b52ccb00-bf3e-11e9-872e-a1557e5d0b9c.png">

**Comment by nicksnyder** [comment]
See https://sourcegraph.slack.com/archives/C02FSM7DU/p1565875230075300. I think this is just a deployment issue (which would be nice to fix soon)

**Comment by nicksnyder** [comment]
I am no longer seeing this.
