### ISSUE TITLE
own: fix own related files that are not in /enterprise

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#52210]
Some of our files are not in enterprise, such as our some of our DB stores. Here is an example search https://sourcegraph.sourcegraph.com/search?q=context:sourcegraph+file:own+-file:enterprise+-file:usagestats+lang:go+-file:markdown+-file:download&patternType=standard&sm=1&groupBy=repo

**Comment by sashaostrikov** [comment]
I thought it would be a quick one to knock off, but there are some tricky circular deps between `database` and `enterprise database` packages which I couldn't resolve in a reasonable time, so I'm postponing this for now.
Feel free to grab the ticket!

**Comment by sashaostrikov** [comment]
a bit more precise search query
https://sourcegraph.sourcegraph.com/search?q=context:sourcegraph+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:own+-file:enterprise+-file:usagestats+lang:go+-file:markdown+-file:download+-file:downgrade&patternType=standard&sm=1&groupBy=repo
