### ISSUE TITLE
Searching within a non-existing repogroup shows no error

### ISSUE THREAD

**Issue by ijt** [sourcegraph/sourcegraph#5224]
Try this query to see it. https://sourcegraph.com/search?q=repogroup:cantfindthis+nope

<img width="582" alt="Screen Shot 2019-08-15 at 2 45 00 PM" src="https://user-images.githubusercontent.com/15530/63129000-4f0a6d00-bf6b-11e9-9f5b-7e43c5470961.png">

The default in case of not finding the repogroup seems to be all the repositories. It would be clearer to show an error, possibly including a list of the valid repogroups in a did-you-mean box.

**Comment by rvantonder** [comment]
@keegancsmith this may be a good small issue as well, I think we maintain a list of valid repogroups somewhere right? So this should be straightforward to check a value against a list.

**Comment by lguychard** [comment]
Repogroups are deprecated.
