### ISSUE TITLE
Adding a github external service does not work

### ISSUE THREAD

**Issue by ijt** [sourcegraph/sourcegraph#5225]
I added and external Github service on k8s.sgdev.org with this configuration, but none of the repos showed up:
```
{
  "url": "https://github.com",
  "token": "$YOUR_TOKEN",
  "repositoryQuery": [ "none" ],
  "repos": [
    "vuejs/vue",
    "trekhleb/javascript-algorithms",
    "flutter/flutter",
    "danistefanovic/build-your-own-x",
    "facebook/react",
  ],
}
```

This configuration worked on a local single image instance, but failed on k8s.sgdev.org.

Here is a screen recording of my attempt: https://youtu.be/2cfnPi16G1g

**Comment by attfarhan** [comment]
@ijt those repos do appear on k8s.sgdev.org now. It takes a few minutes for repos to be added there. There was a conversation in Slack about this last testing period.

**Comment by attfarhan** [comment]
See this thread: https://sourcegraph.slack.com/archives/C07KZF47K/p1563321839140500. I'm gonna close this since I'm pretty sure this worked, reopen if you think otherwise.

**Comment by ijt** [comment]
I still think it would be better to hold off on saying the service is available until the repos from it are available.
