### ISSUE TITLE
Refactor LLM Proxy to be generic cody services gateway

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#52258]
See https://docs.google.com/document/d/1N1S-WUejRIwyJlM5wCxX6vFTrYX-hW6ITX-kvBKggl8/edit#heading=h.j8kwxsddvx7r for details on this. Related: https://github.com/sourcegraph/sourcegraph/issues/51885

**Comment by bobheadxi** [comment]
New projects are up and everything should be cut over to the new Cody Gateway deployments. Remaining tasks: 

* [ ] https://github.com/sourcegraph/sourcegraph/pull/52665
* [ ] spin down llm-proxy resources
* [ ] remove any lingering references (back-compat support etc)

**Comment by bobheadxi** [comment]
Should be all done here :) See mentioned PRs
