### ISSUE TITLE
Indexing status stuck in "Indexing" state when Perforce depot reports a successful clone but was not successful

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#52262]
- **Sourcegraph version:** 5.0.3
- **Reported by:**  https://github.com/sourcegraph/accounts/issues/6938, https://github.com/sourcegraph/accounts/issues/583

#### Steps to reproduce:

See https://github.com/sourcegraph/sourcegraph/issues/52260

1. Once a Perforce depot was "cloned" (but actually unsuccessful - see #52260), the indexing will be stuck in a status of "Indexing" permanently.  When trying to figure out why there are no files for a repo, the repository syncing reports "successful" so the admin goes to check on the indexing state.  Indexing shows up as "in progress" so the admin incorrectly assumes there is something wrong with indexing.

#### Expected behavior:

Indexing is not shown as in progress on a failed repository.

#### Actual behavior:

Because the clone appears to have worked, the admin thinks the issue is with the indexing (since it shows that it is in progress).  This leads to confusion when reporting problems.  The actual problem is that the initial repo clone was unsuccessful leading to an empty clone.  And, for some reason, this leads the indexing being perpetually in an "indexing" state.  

If you would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are no [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

/cc @ryphil @mrnugget

**Comment by peterguy** [comment]
> the initial repo clone was unsuccessful leading to an empty clone

Does "empty clone" mean the clone resulted in a repo with commits but no files?

**Comment by mike-r-mclaughlin** [comment]
> Does "empty clone" mean the clone resulted in a repo with commits but no files?
I think so.  But, I don't have a recording to verify.  Will update this thread once we spot this issue again.

**Comment by eseliger** [comment]
Should be fixed by fixing the issue that incorrectly marked invalid exports as valid.
