### ISSUE TITLE
Search results cannot be highlighted

### ISSUE THREAD

**Issue by ijt** [sourcegraph/sourcegraph#5228]
To see it, try running a query on sourcegraph.com such as `fixme`: https://sourcegraph.com/search?q=%5Cbfixme%5Cb.

Then try to highlight and copy some of the search results. Some sort of drag-and-drop thing happens instead.

Here is a screen recording of my attempt to do this: https://youtu.be/-XYFZ2xdbAk.

**Comment by felixfbecker** [comment]
This is because they are links (click targets). So more as-designed than a bug, but it could be changed.

**Comment by ijt** [comment]
@christinaforney, what do you think?

**Comment by attfarhan** [comment]
FYI there is a feature request for this here: https://github.com/sourcegraph/sourcegraph/issues/875. There is no clear solution to it so it's backlogged. I would probably close this in favor of that and continue the conversation there if needed.

**Comment by slimsag** [comment]
Closing in favor of #875
