### ISSUE TITLE
TypeScript basic code intel: cannot view multiple definitions

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#5229]
- Visit https://k8s.sgdev.org/ghe.sgdev.org/sourcegraph/DIYgod-RSSHub@638e418b093c4b93e783e26547642243ee413c7b/-/blob/lib/routes/douban/people/status.js#L37:11&tab=def
- Set `"typescript.serverUrl": ""` in settings, reload
- Notice the definitions panel is empty

This seems to work for Go https://k8s.sgdev.org/gitolite.sgdev.org/13k/travisjeffery/jocko@4c4bac5acacdf4590949e6a88d6f7f798d55d725/-/blob/jocko/conn.go#L40:49&tab=def

cc @felixfbecker in case you have any ideas what's happening before I debug this later

**Comment by felixfbecker** [comment]
I see a def panel with the langserver:

![image](https://user-images.githubusercontent.com/10532611/63132863-ec44c000-bfc2-11e9-9026-fe72983cf3b8.png)

are you sure you're not using basic code intel?

**Comment by chrismwendt** [comment]
Sorry, this is with basic-code-intel, updated repro.

**Comment by efritz** [comment]
Cannot reproduce with same link.
