### ISSUE TITLE
cody-gateway: informational rate limit alerting

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#52335]
Outside of operational alerting, we should set up alerting for customers that hit their rate limit and possibly other events of interest in the future for CE/TA/sales/etc. We may want to do this based on the metring events we emit (i.e. direct from BigQuery), but if that proves tricky we could do it directly within LLM Proxy as well.

**Comment by eseliger** [comment]
@eseliger to figure out what exactly we need here

**Comment by bobheadxi** [comment]
Earlier Slack message I wrote brainstorming some ideas: https://sourcegraph.slack.com/archives/C05497E9MDW/p1684988354832919

**Comment by unknwon** [comment]
Infra changes are needed as well

**Comment by unknwon** [comment]
Dev e2e tested

<img width="700" alt="CleanShot 2023-06-12 at 17 16 44@2x" src="https://github.com/sourcegraph/sourcegraph/assets/2946214/31f549fa-70c7-45a1-9201-221411130e63">
