### ISSUE TITLE
Results for `.` query in multiline non-indexed search are not highlighted properly

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#5234]
#### Steps to reproduce:

1. Search for `. index:no`, notice the highlights are cut off

#### Expected behavior:

All lines in preview are highlighted

#### Actual behavior:

Preview is partially highlighted.

**Comment by unknwon** [comment]
Hi, would you mind attach a screenshot? It helps realize if others encounter the same problem or should file a new one.

**Comment by rvantonder** [comment]
<img width="458" alt="Screen Shot 2019-10-25 at 2 17 50 PM" src="https://user-images.githubusercontent.com/888624/67605105-41731f80-f732-11e9-8a00-10eb0cedb923.png">

**Comment by camdencheek** [comment]
Closing since it appears this is no longer an issue:

<img width="617" alt="image" src="https://user-images.githubusercontent.com/12631702/110357942-115fb000-7ff9-11eb-9e31-c3d4bec5d3a5.png">

**Comment by rvantonder** [comment]
Still an issue when I expand the view. 

![Screen Shot 2021-03-08 at 10 44 36 AM](https://user-images.githubusercontent.com/888624/110359901-4ec53d00-7ffb-11eb-8c96-2013b5fa2b83.png)

**Comment by rvantonder** [comment]
Maybe some logic that stops highlighting up to some number of matches, and that this changed, so the highlighting behavior changed.

**Comment by camdencheek** [comment]
Nice, thanks for checking me

**Comment by rvantonder** [comment]
It is rare (in my experience) that something in Sourcegraph fixes itself without a deliberate action :P

**Comment by camdencheek** [comment]
When I implemented streaming on searcher, I removed the per-file match limit since we can just rely on the global match limit with streaming. I think that means this is largely fixed. We'll still see cut-off lines (because the global match limit will eventually be hit), but only ever in the last file returned. I think this is working as expected and can be closed, but will wait for @rvantonder to confirm since I already mistakenly closed this once 😄

**Comment by rvantonder** [comment]
it still looks bricked https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+.+index:no&patternType=regexp

![Screen Shot 2022-04-25 at 11 51 09 AM](https://user-images.githubusercontent.com/888624/165154710-f286ed25-8739-434c-ae47-e316de33386e.png)

**Comment by rvantonder** [comment]
> but only ever in the last file returned. 

I see. Still, doesn't look good. Wondering if we can do something cosmetic here but no ideas. It's ok to close this and just like do WONTFIX IMO.

**Comment by camdencheek** [comment]
I wonder if we could do something like make "limit hit" on the file level visible to the user. Just like something on the bottom of a result block that indicates why there may be truncation.

**Comment by camdencheek** [comment]
Closing as won't fix since this is just how our limits work
