### ISSUE TITLE
Line decoration links don't render until clicking inside the content container

### ISSUE THREAD

**Issue by vanesa** [sourcegraph/sourcegraph#5236]
#### Steps to reproduce:

1. Turn on the Sentry extension and copy-paste this minimum setup in your user settings.
```
{
  "sentry.decorations.inline": true,
  "sentry.organization": "sourcegraph",
  "sentry.projects": [
    {
      "projectId": "1334031"
    }
  ]
}
```
2. Go to: http://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/browser/src/libs/github/file_info.ts
3. Toggle the showing of Sentry links on and off and notice how the links don't reappear unless you click somewhere in the content area, but they do disappear with no clicking necessary.

#### Expected behavior:
To appear and reappear when using the toggle without having to click in the content area.

#### Actual behavior:
Links don't reappear when using the Sentry show lines toggle unless you in the content area.
https://cl.ly/3e5e53c5f6e6

Probably somewhat related to this issue: https://github.com/sourcegraph/sourcegraph/issues/5235

**Comment by attfarhan** [comment]
This is generalizable to all line decorations, I saw this for git blame: https://github.com/sourcegraph/sourcegraph/issues/5235.
