### ISSUE TITLE
Codecov extension leads to multiple rendering of Sentry links when using the toggle

### ISSUE THREAD

**Issue by vanesa** [sourcegraph/sourcegraph#5237]
#### Steps to reproduce:

1. Activate the Codecov extension
2. Activate the Sentry extension and setup up the minimal configurations in your user settings:
```
{
  "sentry.decorations.inline": true,
  "sentry.organization": "sourcegraph",
  "sentry.projects": [
    {
      "projectId": "1334031"
    }
  ]
}
```
3. Go to http://127.0.0.1:7080/github.com/sourcegraph/sourcegraph/-/blob/browser/src/libs/github/file_info.ts#L3
4. click on the Codecov toggle to show the lines colored
5. Click on the Sentry toggle and turn it on and off multiple times. Notice how the Sentry links start duplicating, as they don't disappear when being toggled off.

FYI: This was also happening with the Blame extension but when I was recording the screenshot (after page refresh) it didn't happen anymore so I couldn't capture it.

#### Expected behavior:
Sentry and Codecov extension working harmoniously.

#### Actual behavior:
Sentry links duplicate and sometimes Blames duplicate as well.
https://cl.ly/139a9434f041

**Comment by attfarhan** [comment]
Verified this is not a regression in 3.7, so not release blocking.
