### ISSUE TITLE
Add auto-delete branch support for Gerrit

### ISSUE THREAD

**Issue by courier-new** [sourcegraph/sourcegraph#52386]
We recently added support for a new site setting which, when enabled, will auto-delete branches associated with changesets when they are merged or closed (https://github.com/sourcegraph/sourcegraph/issues/50354). As experimental Gerrit support for Batch Changes is [underway](https://github.com/sourcegraph/pr-faqs/issues/141), we should bring this feature to Gerrit, as well.

**Update**
Since a branch doesn't really exist outside of the context of a Change (changeset on Gerrit), deleting the branch isn't really a thing that needs to happen. However, Abandoned (closed) Changes exist indefinitely on the code host unless explicitly deleted. When using Batch Changes quite actively, this could cause a similar build-up. So in the spirit of the original issue and enabling better "code host hygiene" of entities created by Batch Changes on the code host when the site setting is enabled, the equivalent action would seem to be to delete a Change on Gerrit if it is Abandoned (closed) from Sourcegraph.

We should:
- When a Change is Merged on Gerrit, do nothing
- When a Change is Abandoned on Gerrit, check the site setting and, if it is enabled use the [API](https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html#delete-change) Idan referenced to also delete the Change
- If necessary, prevent further syncing of the changeset in the future via a flag on changeset (or perhaps a property on the changeset metadata is sufficient for this?). I don't remember how we handle this today for deleted changesets on other code hosts, so this might be a no-op.
- Update the docs for this setting to indicate the slightly different behavior on Gerrit

**Comment by courier-new** [comment]
Oh Gerrit, how you continue to fascinate me. So for a Change that isn't accepted (is "abandoned", in Gerrit speak, maybe?? Idk what do I know about this mysterious code host 😂), does it just exist forever on that [Abandoned view in the UI](https://gerrit.sgdev.org/q/status:abandoned)? Is there a concept of "deleting" the change that would maybe be an equivalent clean-up measure one would take?

**Comment by varsanojidan** [comment]
Yeah you can delete a Change (PR) either through the UI or this [API](https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html#delete-change). But you can also just leave it as Abandoned for eternity if you so wish 😛.

**Comment by varsanojidan** [comment]
After talking with @courier-new, I understand what the original goal of this issue is a better, and we both agree that it probably makes sense to implement the cleanup as a: delete Change, using this [API](https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html#delete-change).

Sorry bout the confusion!
