### ISSUE TITLE
Cody Gateway: on-call and SLA

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#52409]
Spun off from https://github.com/sourcegraph/sourcegraph/issues/51830:

- [ ] Direct alerts to ~Cloud team on-call~ a Cody Gateway "team" rotation (me, Joe, Erik)
- [x] Define SLAs for Cody Gateway: https://github.com/sourcegraph/sourcegraph/issues/52409#issuecomment-1594117504

**Comment by eseliger** [comment]
Figure out if we need SLAs for the service for 5.1 or if this has some more time.

**Comment by eseliger** [comment]
Who is going to be the long term owner?

**Comment by eseliger** [comment]
What are the SLAs for GPT and Anthropic upstream APIs?

**Comment by eseliger** [comment]
Responses for the two upstreams: 

https://sourcegraph.slack.com/archives/C01GJFE26BX/p1685551366081149 https://sourcegraph.slack.com/archives/C04NPH6SZMW/p1685474366288319

**Comment by bobheadxi** [comment]
Decision: **no official SLA** for now, pending an SLA commitment from OpenAI
