### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#52404]

**Comment by slimsag** [comment]
(Juliana to try moving us along here ahead of next job-fair iteration, just best-effort, no guarantees)

**Comment by yekanchi** [comment]
does it mean build for windows?

**Comment by slimsag** [comment]
@yekanchi this would be a build of the Cody app (a desktop version of Sourcegraph) built for Windows, yep! No guarantees yet, but we're thinking of doing this over the next few months.

**Comment by nelsonjr** [comment]
Cody App for Windows is ready for alpha testing:

- https://github.com/sourcegraph/sourcegraph/pull/54263
- https://github.com/sourcegraph/sourcegraph/pull/54233
- https://github.com/sourcegraph/sourcegraph/pull/54221
- https://github.com/sourcegraph/sourcegraph/pull/54103
- https://github.com/sourcegraph/sourcegraph/pull/53832

**Comment by yekanchi** [comment]
> Cody App for Windows is ready for alpha testing:
> 
> * [Disable services that are causing issues on Windows. #54263](https://github.com/sourcegraph/sourcegraph/pull/54263)
> * [Enable servers to run on Windows OS. #54233](https://github.com/sourcegraph/sourcegraph/pull/54233)
> * [Move POSIX specific startup to dedicated build file #54221](https://github.com/sourcegraph/sourcegraph/pull/54221)
> * [Start PostgreSQL on Windows via TCP on dedicated port. #54103](https://github.com/sourcegraph/sourcegraph/pull/54103)
> * [Cody for Windows installer: builds/signs x64 msi. #53832](https://github.com/sourcegraph/sourcegraph/pull/53832)

where is the link to download and test?
