### ISSUE TITLE
Cloud icon ALWAYS shows "indexing"?

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#52416]
App doesn't support zoekt indexing, so maybe that's why?

> I only added one small repo, but I’ve been seeing “Indexing repositories…” at the top right for 5+ minutes. When I click it, I see my repo in a “CLONED” state, with no indexing progress indicated.

**Comment by vovakulikov** [comment]
I think we're going to remove this icon completely and maybe replace it with progress UI later, removing will happen here https://github.com/sourcegraph/sourcegraph/pull/53714
