### ISSUE TITLE
Chrome-style ‘something went wrong’ screen

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#52423]
This is important because otherwise if the backend crashes, we see all sorts of weird errors due to the backend simply 404'ing. It appears as though the GUI is just 'not working' in many cases.

General plan:

* If the backend crashes, show a Chrome style 'Something went wrong' screen (via app-shell.tsx)
* Suggest the user report the issue in https://github.com/sourcegraph/app (if you want to get fancy, make it easy to somehow copy+paste the logs, or something)
* Provide a button the user can click to delete all data and restart (Chris is implementing this in Tauri, we just need a button we can use to fire an event to Tauri backend)

Design (anything is better than what we have right now, and even if we designed a proper screen for this we may not be able to easily pull in CSS/etc on this app-shell.tsx page - so let's keep it lightweight/dumb/simple for now):

![Image](https://github.com/sourcegraph/sourcegraph/assets/3173176/db1fc421-c8e2-48ba-a948-4bd146bba673)

**Comment by almeidapaulooliveira** [comment]
Here's a design proposal. Please let me know if we need less styling. Figma [here](https://www.figma.com/file/8UUuaIUPVJDzp8U9ImNvA7/Connect-Cody-and-polish-setup-experience?type=design&node-id=845-4135&t=58EmpwjsCoXBjlep-4).

![Something went wrong page](https://github.com/sourcegraph/sourcegraph/assets/64257673/f560498a-7c64-49e8-81cb-c1f2393b0ad2)
