### ISSUE TITLE
Add alerting for indexed-search on sourcegraph.com

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#5243]
indexed-search got stuck in CrashLoopBackoff and made searches return incorrect results on Sourcegraph.com but we didn't receive any alerts. We should be alerted if that pod is not in the `Running` state (I believe that we have other alerts like this already).

https://github.com/sourcegraph/deploy-sourcegraph-dot-com/blob/release/configure/prometheus/prometheus.ConfigMap.yaml

**Comment by nicksnyder** [comment]
Alerts on the disk space getting full would be nice too

**Comment by ijt** [comment]
@ggilmore, I think you're a lot more familiar with this than I am. Can you take this?

**Comment by nicksnyder** [comment]
I discussed this with @ijt in person and will share notes here:
- I want teams who own services to own the alerts for those services. Since @ijt deployed this new service to prod, I would like him to be responsible for adding the appropriate alerts that will tell is if/when it isn't working.
- @ijt can get help/input from people on the team (e.g. @beyang @keegancsmith @slimsag or ask in #dev-chat) who might be more familiar with how to create Prometheus alerts, but it should also be possible to learn from first principles by referencing general documentation and existing examples.

Since we have already seen examples of indexed search getting into a bad state and causing search problems on sourcegraph.com, this is a priority for this iteration (assuming that we want to keep indexed search on for sourcegraph.com).

**Comment by ijt** [comment]
@keegancsmith, it looks like we already have alerts that are meant to cover what @nicksnyder requested. Am I reading this correctly?
```
[ ~/sg/deploy-sourcegraph-dot-com ] rg PodsMissing
configure/prometheus/prometheus.ConfigMap.yaml
465:    ALERT PodsMissing

configure/prometheus/README.md
123:- `PodsMissing`: Alerts when pods are missing.
[ ~/sg/deploy-sourcegraph-dot-com ] rg DiskSpaceLow
configure/prometheus/prometheus.ConfigMap.yaml
76:    ALERT DiskSpaceLow
85:    ALERT DiskSpaceLowCritical

configure/prometheus/README.md
128:- `DiskSpaceLow`: Alerts when a node has less than 10% available disk space.
129:- `DiskSpaceLowCritical`: Alerts when a node has less than 5% available disk space.
```

**Comment by keegancsmith** [comment]
PodsMissing will only work if your pod exports prometheus metrics which zoekt does not. So I would just start exporting prom metrics on zoekt-webserver and update the svc in deploy-sourcegraph to say it exports prom metrics. We should have disk space alerts. However, I'm unsure if we will get the alert if the pod never starts up.

**Comment by lguychard** [comment]
@uwedeportivo are you working on this/is it likely to make the 3.8 branch cut? If not, please move it to an appropriate milestone.

**Comment by uwedeportivo** [comment]
this slipped, will pick it up once monitoring UI lands

**Comment by uwedeportivo** [comment]
https://github.com/sourcegraph/zoekt/pull/31

**Comment by uwedeportivo** [comment]
https://github.com/sourcegraph/deploy-sourcegraph/pull/388

**Comment by uwedeportivo** [comment]
![indexed-search](https://user-images.githubusercontent.com/534011/66243287-e745e800-e6b8-11e9-9c55-59e54bc969c3.png)

tested on test cluster

**Comment by uwedeportivo** [comment]
i'll leave it open for now until i research the disk space part

**Comment by tsenart** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.9 release is scheduled for tomorrow** at 10:00 CEST.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Oh captain, my captain

the pod not running part has landed and was tested.
i left the issue open to research the disk space part too but ran out of time. we could close this one and open one for the disk space

**Comment by tsenart** [comment]
> we could close this one and open one for the disk space

Sounds good to me. Please proceed :-)

**Comment by uwedeportivo** [comment]
https://github.com/sourcegraph/sourcegraph/issues/5994
