### ISSUE TITLE
App: Local repos are not detected properly by VS Code codebase context 

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#52469]
When a local repo is added to App and the user is using Cody in VS Code it attempts to infer the repo, however the names do not align so the extension can not use embeddings if they were generated.

I believe the root cause of this is the VS Code extension trying to infer the name from the remote, but locally added repos in App are named based on the folder.

**Comment by Momilijaz96** [comment]
Hey @chwarwick I want to solve this issue, could you give me any leads how to start off with it?
