### ISSUE TITLE
scip-ctags: rollout

### ISSUE THREAD

**Issue by SuperAuguste** [sourcegraph/sourcegraph#52467]
- [x] Test and merge main PR (https://github.com/sourcegraph/sourcegraph/pull/50600) 
  - [x] Add Bazel logic for CI support
  - [x] Test local dev on Mac
  - [x] Test local dev (Docker) on Linux 
- [x] Merge the Zoekt PRs
  - [x] https://github.com/sourcegraph/sourcegraph/pull/52387
  - [x] https://github.com/sourcegraph/zoekt/pull/581
- [x] Refactor Dockerfile and other scripts (https://github.com/sourcegraph/sourcegraph/pull/50600#discussion_r1205749718)
- [x] Enable languages on dotcom
  - [x] Zig
  - [x] C#
  - [x] C/C++
  - [x] Kotlin
  - [x] Ruby
  - [x] Scala
  - [x] Go
  - [x] Rust
  - [x] Python
  - [x] Java
  - [x] JS/TS

Some goals as we enable languages on dotcom:

- Refine language queries if we observe inaccuracies
- Keep track of drastic stability / performance issues

**Comment by varungandhi-src** [comment]
@SuperAuguste should this be closed as completed?
