### ISSUE TITLE
Cody bug: user is required to sign in with token again after disconnected from server

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#52479]
report by [customeres](https://sourcegraph.slack.com/archives/C052CJK4EBY/p1683218865499739) and [erik](https://sourcegraph.slack.com/archives/C052G9Y5Y8H/p1685062831255539):

![Image](https://user-images.githubusercontent.com/68532117/241097625-042767e1-cf05-4d23-a666-fd650ea503b5.png)

Issue:
When a user is logged out due to server disconnection, UI suggests their token is invalid and must provide with a new one when in fact the token is valid, and is actually still exists in their secret storage, but our UI is still displaying the token field as empty.

Idea:
- display a more accurate error message in UI
- UI should still let the user know that their token still exists
- a button to reload ext?

**Comment by deepak2431** [comment]
@abeatrix I have created a PR for this by implementing the possible solution you mentioned. Do have a look, and let me know what you think :)
