### ISSUE TITLE
Cody bug: UI not showing embedding server errors

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#52480]
RE: https://sourcegraph.slack.com/archives/C053L1AQ0BC/p1684963140436959?thread_ts=1684878072.751779&cid=C053L1AQ0BC

Currently users need to check their developer tool console to see errors from embedding server

we should surface the errors in UI so that users can identify server issues in a timely manner

**Comment by deepak2431** [comment]
@abeatrix Create a PR for this. Do have a look. Tried to handle two cases but yeah let me know if there's any more.

**Comment by abeatrix** [comment]
@deepak2431 hey hey I will take a look in a bit but this is awesome! You are awesome 😎

**Comment by deepak2431** [comment]
> @deepak2431 hey hey I will take a look in a bit but this is awesome! You are awesome 😎

Thanks, @abeatrix 😊

**Comment by jtibshirani** [comment]
Closing this out as we're not investing in embeddings at the moment.
