### ISSUE TITLE
k8s.sgdev.org: GHE login results in "context deadline exceeded" when searchng

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#5250]
1. Login to k8s.sgdev.org via Github Enterprise (ghe.sgdev.org)
1. Do a text search, e.g. https://k8s.sgdev.org/search?q=nice
1. See the `Post https://ghe.sgdev.org/api/graphql: context deadline exceeded` error:

<img width="717" alt="Screen Shot 2019-08-16 at 5 16 02 PM" src="https://user-images.githubusercontent.com/9022011/63204133-8fd8b380-c049-11e9-84ad-05917157e774.png">

Note that I don't see this error when I run the single docker image locally. Maybe it's due to the large number of repos on ghe.sgdev.org?

**Comment by tsenart** [comment]
> Note that I don't see this error when I run the single docker image locally. Maybe it's due to the large number of repos on ghe.sgdev.org?

More than likely that is the case. On-going work on https://github.com/sourcegraph/sourcegraph/issues/4812 should alleviate the issue.

**Comment by attfarhan** [comment]
@tsenart any idea if this is problem existed in the previous release, or if this is a regression? It seems like the work is being done to alleviate this (in the issue you linked) but it won't fix this for this release. Is there a quicker fix for this release if it is indeed a regression? Trying to determine whether this is release blocking or not.

@ggilmore Any idea if this is going to be a problem for existing customers?

**Comment by keegancsmith** [comment]
Yeah this isn't release blocking. This is an old issue to do with ACLs at scale. Luckily @tsenart is tackling it this iteration. I just confirmed that the timeout occurred while fetching ACL information. 

The error message is very poor.

**Comment by keegancsmith** [comment]
Given we are working on fixing this in this iteration, marking as duplicate of the tracking issue.

Duplicate of https://github.com/sourcegraph/sourcegraph/issues/5250
