### ISSUE TITLE
Cody: enable Cody by default in 5.1

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#52546]
We want Cody to be enabled by default in 5.1. Before the release, we need to collect all feature-flags and have them on by default.

### Feature Flags

* If `experimentalFeatures.CodyRestrictUsersFeatureFlag` is set, then `featureflag.FromContext(ctx).GetBoolOr("cody-experimental", false)` is used, *default value: off*. Change required for release: **no**
* 
<img width="1135" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/22571395/a181e51e-2427-4a58-bd30-c9088fb07c36">

**Comment by keegancsmith** [comment]
@mrnugget Cutting patch release for 5.0.x series today, and just double checking the release-blocker label is meant for 5.1.

**Comment by mrnugget** [comment]
Confirm, it's meant for 5.1. Remove & re-apply, I just don't want us to lose track of this when cutting 5.1
