### ISSUE TITLE
Cody: Context file item UI out of sync with file events (web + VS Code)

### ISSUE THREAD

**Issue by toolmantim** [sourcegraph/sourcegraph#52542]
Cody’s Context UI updates unpredictably when navigating files in both web and VS Code, making it difficult to understand how Cody works.

I haven't verified if it's just view rendering bugs (e.g. React not picking up the prop changes) or if the context items themselves aren't being updated properly.

### Web

https://github.com/sourcegraph/sourcegraph/assets/153/b1b14d01-68b9-4696-b2b5-3264ef1417b7

### VS Code

https://github.com/sourcegraph/sourcegraph/assets/153/5c7b8627-9988-4ca2-bf4d-97a5cacf2047

### Expected behaviors:

Filenames change as soon as file navigation events happen:
- Web: when navigating to a different file or directory or repo root
- VS Code: when opening a different file, closing a file, switching tabs

### Actual behavior:

Web:
- Context file is shown temporarily and then disappears when navigating between files
- Context file doesn't update (shows previous file) until message input is changed or history is navigated to

VS Code:
- Context file sometimes doesn't updated when a file is previewed or opened, only when file buffer is edited
- Context file doesn't updated when file is closed (editor removed)

**Comment by thenamankumar** [comment]
This seems to be fixed for the web.
