### ISSUE TITLE
Pings for own Q2 improvements

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#52578]
This quarter own has added two important features:

- Ownership inference signals
- Assigning ownership

Inference signals monitoring is mostly covered by existing pings introduced in Q1. For assigned ownership feature monitoring, we need some more data.

Questions we're trying to answer:

- How often are new product surfaces of own used?
- How often are owners assigned?

We add the following events:

- `own:owner:assigned` - when an owner is assigned through the UI
- `own:owner:unassigned` - when an owner is unassigned through the UI
- `treePage:ownerTab:drilldown:viewed` - when ownership drilldown page for a directory or repo view is presented
- `treePage:ownerTab:promoteOwner:clicked` - when owner is promoted from inference signal through the UI
- `treePage:ownerTab:unassignOwner:clicked` - when owner is unassigned through the UI

To observe how signals are used, we simply return two flags:

- ownership signals enabled - true/false
  - for indexing recent contributors
  - for indexing recent viewers

The above will show us whether the customer has either signal enabled, and this compared with ownerTab and Q1's blob view pings will give us insight into how often the product surfaces with the data are accessed. In other words, we will know whether data is visible on surfaces (here with singal enabled ping) and we will know whether users are consuming the data (via Q1 pings).

We plan to introduce the following pings in order to observer how assigned ownership is used:

- total count of assigned owners - this shows us whether assigned owners are used on a daily basis
- M/W/D AUs for the following events - these show us how many custodians actively make changes. It gives us an extra data point on how should we proceed with the process of ownership assignment (for instance do we need finer-grained permissions, and so on). 
  - owner was assigned
  - owner as unassigned

**Comment by dadlerj** [comment]
The new user events look great, but:

* I don't know all of the UI interaction points, so I can't say if this is comprehensive or not
* @nathan-downs should comment on the naming scheme

For _pings_, it'd probably be worth specifying more details on how you plan to use them. How have you used the first round of Own-related ping data so far by the way? Has everything worked well?

**Comment by cbart** [comment]
Thank you @dadlerj!

- I tried adding more elaborate specification to the description above. Hope this helps to assess better.
- As for first round of pings, we're seeing [some usage](https://sourcegraph.looker.com/dashboards/473?Ownership+Panel+Opened+MAU=%3E0), but we're still early in gathering customer feedback; upcoming release enables many customers who don't have any ownership data to take better advantage of own.

**Comment by nathan-downs** [comment]
I created a draft document with the general naming convention approach to help us more easily parse events data downstream [here](https://docs.google.com/document/d/1hHUsKWqDDHaB7mL5MgNLEdIWOPnbR-9KVBWSMQMSbO4/edit?usp=sharing), but it's generally in the format of:
`[source]:[event]:[action]`

I'm not as familiar with where this code would be executed, but potentially something like:
`webOwn:promoteOwner:clicked`
`appOwn:promoteOwner:clicked`

Open to modifications to the convention as long as they are documented and are able to be parsed. If there are additional piece of data that we would like to associate with an event, we do support JSON storage of data in the argument/public_argument fields (argument stays on the instance, public_argument gets sent back to the analytics database).

**Comment by cbart** [comment]
Thank you! This sounds good. Let's then minimize the extra events to:

`web:makeOwner:clicked` - make owner button was clicked

And then the single ping I would add is the number of assigned owners across the instance. Can I proceed with implementing?

**Comment by cbart** [comment]
I've sent two pull requests:

- Handler change #52995
- Schema change sourcegraph/analytics#947
