### ISSUE TITLE
Firefore Add-on marked as Blocked by FF

### ISSUE THREAD

**Issue by bruno-garcia** [sourcegraph/sourcegraph#5260]
Not so much a bug report but an issue with the sourcegraph plugin for firefox.

I've installed it and got this:

<img width="875" alt="image" src="https://user-images.githubusercontent.com/1633368/63217986-8b4af280-c150-11e9-9362-01586b759db7.png">
<img width="686" alt="image" src="https://user-images.githubusercontent.com/1633368/63217989-92720080-c150-11e9-898b-e70db36d8a06.png">

Version: 19.8.12.2135

**Comment by tiagofassoni** [comment]
Bruno, please take a look here: https://docs.sourcegraph.com/integration/firefox_security

Unfortunately, nothing we can do about that, apparently.

**Comment by bruno-garcia** [comment]
Sorry I missed the docs. Thanks.

**Comment by tiagofassoni** [comment]
No probs, mate. Have  a wonderful day!
