### ISSUE TITLE
IDE plugin client: defensive programming for when Cody is disabled on enterprise instance (or server version is below 5.1)

### ISSUE THREAD

**Issue by gwestersf** [sourcegraph/sourcegraph#52616]

**Comment by dominiccooney** [comment]
@toolmantim is looking at designs for this; @abeatrix will work on code.

**Comment by abeatrix** [comment]
Display error messages when version of the connected instance is below 5.1.0:  $VERSION_NOT_SUPPORT_ERROR

Display error message when the "Cody-experimental" feature flag is not enabled for user: 
$FEATURE_FLAG_MISSING_ERROR

Questions for @toolmantim:
Do we allow these users to sign into Chat view?
- If yes, do we display these error messages as messages from Cody, and disable chat submit button?

**Comment by toolmantim** [comment]
Thanks for digging @abeatrix!

Sounds like our options are:
1. Fail the login if the server doesn't support Cody or have it enabled, and not store the login token
2. Make the login succeed, but show a message that Cody isn't supported, and ability to logout and remove token

I think we go for option 1. It'll mean the user creates a token each time they attempt, yeah? But I think it's the same experience, and much cleaner to handle.

wdyt?

**Comment by abeatrix** [comment]
@toolmantim sounds good. It looks like we do surface the embedding server error in chat view currently. I will work on moving it to the login view instead
![image](https://github.com/sourcegraph/sourcegraph/assets/68532117/13dcb7af-6f33-487c-bde0-cda26d491e1e)

**Comment by abeatrix** [comment]
> @toolmantim sounds good. It looks like we do surface the embedding server error in chat view currently. I will work on moving it to the login view instead
> 
> ![image](https://github.com/sourcegraph/sourcegraph/assets/68532117/13dcb7af-6f33-487c-bde0-cda26d491e1e)

On second thought, embedding not enabled for user should not stop users from being able to login and use Cody, because they can still use keyword search and completions. Thoughts?

**Comment by toolmantim** [comment]
Ah yeah, that's a great point… for now let's not block the chat.

Here's a design from a few weeks back:

![Open-source or private, + Cody App detected](https://github.com/sourcegraph/sourcegraph/assets/153/279d2973-ae79-4529-931d-c064d8dc4d27)

Let me update that a bit, and then we get something like that in? And we can use that same UI for missing embeddings etc too (https://www.figma.com/file/9112BsKsJc1BpO2j8XYwLL/%F0%9F%A4%96-Cody-VS-Code-%5BMain%5D?type=design&node-id=2953-134714)

**Comment by abeatrix** [comment]
> hey hey! is there a progress update for this? can it be shipped before June 28?

@kalanchan  The PR is approved, once I've fixed the build kit issues it's ready to go. You can follow the PR for the latest update.

**Comment by toolmantim** [comment]
@kalanchan yep, we should have linked the PR here. This is being fixed in #52739 and will be available well before June 28.

**Comment by kalanchan** [comment]
@abeatrix @toolmantim thank you! i'll update the 5.1 release sheet accordingly 😄 
![image](https://github.com/sourcegraph/sourcegraph/assets/51868853/2749ccff-82eb-4e96-b81a-12476ad06182)

**Comment by abeatrix** [comment]
@kalanchan it's merged https://github.com/sourcegraph/sourcegraph/pull/52739
