### ISSUE TITLE
App: Generate embeddings when users opt into Cody

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#52639]
When an App user opts into using Cody repo embeddings should be generated for the users repos and kept up to date.

related https://github.com/sourcegraph/sourcegraph/issues/52637 for automatic embeddings policies.

**Comment by chwarwick** [comment]
cc @almeidapaulooliveira  @vovakulikov @taylorsperry  This maybe be a step we want to integrate in to setup flow.  

Once the user add repos, is it some/all you want to generate embeddings for?  Thats a very technical term and the user may not understand, we could do this completely in the background but it feels more responsible to the user to ask which repos they want to send to a 3rd party for this processing.

**Comment by almeidapaulooliveira** [comment]
cc @danielmarquespt

**Comment by chwarwick** [comment]
API support added in https://github.com/sourcegraph/sourcegraph/pull/53547

**Comment by chwarwick** [comment]
@vovakulikov  Can you close this issue out when you merge your setup steps that call the new schedule api?
