### ISSUE TITLE
Cody recipe messages look too similar to user-typed messages

### ISSUE THREAD

**Issue by toolmantim** [sourcegraph/sourcegraph#52669]
Cody recipe messages and normal messages look exactly the same, but there is hidden context state/data sent with a recipe. This can cause some confusing situations, if people think they can just run the same prompt and get the same results:

https://github.com/sourcegraph/sourcegraph/assets/153/38b1cc0a-0e40-4169-a581-7530c2e2a690

## Suggested solution

Style the recipe messages differently to regular messages, to make sure people can see "one of these things is not like the other":

<img width="457" alt="Screenshot 2023-05-31 at 12 55 52 pm" src="https://github.com/sourcegraph/sourcegraph/assets/153/0d31f495-ed98-466c-88ca-84172cfc3bf5">

We can also introduce terms like "run recipe" (awkward alliteration) or "execute recipe" (& "recipe executed")

**Comment by deepak2431** [comment]
@toolmantim Is this issue open to work now? As I liked your idea of differentiating the recipes with normal messages. Including the icon with the title would be great to have.

CC: @abeatrix @philipp-spiess
