### ISSUE TITLE
GraphQL request for repository right after adding external service and waiting for repo to be mirrored returns null (even though UI shows repo)

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#5286]
The browser extension e2e tests for Bitbucket always fail for on the first test (even if changing order of the test), but work on the second test or after reloading the page. It also works if adding a significant artificial delay.

The test
- Creates a Bitbucket external service pointing to a localhost Bitbucket Server instance, configured to clone one repo. If it already existed it deletes it first.
- Goes to the repositories page and waits for that repo to show up
  - Note this is the critical step - given it shows up in the UI (after waiting a short while) I would expect it to not return `null` in the API.
- Goes to Bitbucket to get code intelligence through the browser extension
- Fails because the browser extension gets a `null` response and does not add buttons / code intelligence

Here's a recording: https://www.loom.com/share/3c49d17539e84f63902844b1ab35308a

**Comment by mrnugget** [comment]
@felixfbecker Do you think this is related to https://github.com/sourcegraph/sourcegraph/issues/5125#issuecomment-522271992 ?

**Comment by felixfbecker** [comment]
I thought so at first, but the behaviour is different: This returns `repository: null`, while #5125 returns `repository: { name: "" }`. Whether the problems could still be related on the backend side I don't know

**Comment by felixfbecker** [comment]
Ping - this is blocking automated e2e tests for the browser extension, which is my iteration goal for 3.8

**Comment by tsenart** [comment]
@felixfbecker: Have you found a work-around in the meantime that unblocked you? If so, can we change the milestone of this issue? Branch-cut is next Monday.

**Comment by lguychard** [comment]
Backlogging this as the 3.8 branch is cut, and it does not block the release.

**Comment by felixfbecker** [comment]
@tsenart I added a page reload, but it reduces the usefulness of the test as that could work around other legit bugs too.

**Comment by tsenart** [comment]
Any chance this can be included in #5710? cc @sourcegraph/core-services

**Comment by keegancsmith** [comment]
Will add as a stretch task.

**Comment by keegancsmith** [comment]
It's a bit hectic for me to get this all setup to reproduce (unless we have it documented somewhere). I have a hunch it is related to ACLs (although you should be using the browser extension as an admin user?) Can you try this out, but instead of using all our crazy ACL stuff, use no ACLs? eg via `./dev/launch.sh` or a fresh docker server.

**Comment by tsenart** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.9 release is scheduled for tomorrow** at 10:00 CEST.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by keegancsmith** [comment]
Putting on backlog. Waiting for feedback from @felixfbecker on https://github.com/sourcegraph/sourcegraph/issues/5286#issuecomment-540682598

**Comment by tsenart** [comment]
Closing until it re-surfaces.
