### ISSUE TITLE
Cody vscode: make file paths and function names clickable

### ISSUE THREAD

**Issue by cartermp** [sourcegraph/sourcegraph#52863]
#### Feature request description

Given an output like this:

>The code that handles this POST request is in `src/main/java/io/opentelemetry/demo/cartservice/CartController.java`.
>The `addItemsToCart` method contains the logic for adding items to a cart.

Make the `src/main/java/io/opentelemetry/demo/cartservice/CartController.java` a clickable link.

Furthermore, the `addItemsToCart` section should also ideally navigate to the line number where that method is in, but it's already much better if it can just do file navigation.

(I filed another issue where the output actually incorrect, but let's assume for a moment that it is!)

#### Is your feature request related to a problem? If so, please describe.

Easier navigation after I find what I'm interested in.

#### Describe alternatives you've considered.

Using ctrl/cmd+P to type it out, but it's a lot faster to just click.

**Comment by jdorfman** [comment]
Thanks for reporting @cartermp!
