### ISSUE TITLE
Loading a chat from the history view should have it scrolled to the bottom

### ISSUE THREAD

**Issue by toolmantim** [sourcegraph/sourcegraph#52889]
When navigating to a past chat, it should be scrolled down the bottom to the most recent point, but instead it's at the top (the very start of the conversation).

https://github.com/sourcegraph/sourcegraph/assets/153/695f66a0-23de-463b-91ef-e1fc84caa859

#### Steps to reproduce:

1. Send enough messages that you have a scrollable chat window
2. Hit new chat
3. Go to the chat history
4. Click on the history item for the long chat
5. Notice the scroll position is at the top instead of the bottom

#### Expected behavior:

The scroll position would be at the bottom

**Comment by SuperAuguste** [comment]
Closed in #52904.
