### ISSUE TITLE
`User` owned search contexts can't have ownership edited after creation

### ISSUE THREAD

**Issue by DaedalusG** [sourcegraph/sourcegraph#52886]
- **Sourcegraph version:** v5.0.4
- **Platform information:** n/a 

#### Steps to reproduce:

1. Create a search context with ownership `User`
<img width="269" alt="Screenshot 2023-06-02 at 10 36 31 AM" src="https://github.com/sourcegraph/sourcegraph/assets/13024338/1f6b8d9e-39e3-4d09-ba31-51edcd35ef11">
2. Attempt to edit the ownership after creation to global.

#### Expected behavior:
You should be able to change the ownership to global after creation. Currently this can't be done.
#### Actual behavior:
Currently this can't be done.

#### Work arounds and notes on importance

This flow is important because User owned contexts are not displayed in the search context drop downs so discovery is a pain if a user would like to share their context. Its possible to use the context but you must know it exists and manually enter its whole identifying string.

For Example:

On an instance the following contexts exist:
![Screenshot 2023-06-02 at 3 38 11 PM](https://github.com/sourcegraph/sourcegraph/assets/13024338/a84cd031-bbeb-480e-8b46-bc2baa1ebde3)

On that instance the context selection looks like so for myself user @warren:
![Screenshot 2023-06-02 at 3 39 40 PM](https://github.com/sourcegraph/sourcegraph/assets/13024338/a3658342-0651-4b6b-b2ee-7a09a4e41c8a)
However for user @doombot the contexts aren't displayed:
![Screenshot 2023-06-02 at 3 41 37 PM](https://github.com/sourcegraph/sourcegraph/assets/13024338/8e2827d9-8ca0-4ff9-a564-d5701b748ee8)

Currently the advised work around is just to create a new context with the same configurations but set the ownership to `Global`

If you would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are no [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

**Comment by DaedalusG** [comment]
After some internal discussion noting here that the inability to edit ownership of a context after creation was a design decision. Notably if you hover over that field on the `edit context` page you'll see a crossed out pointer and a hover message

![Screenshot 2023-06-20 at 9 33 05 AM](https://github.com/sourcegraph/sourcegraph/assets/13024338/0c7457f8-0c7e-4525-8d67-56054d472bea)

This still begs the question why don't public contexts owned by a specific user appear in the context dropdown box

**Comment by limitedmage** [comment]
Closing this as by-design. We may evaluate better ways of sharing search contexts in the future.
