### ISSUE TITLE
Cody backend does not have enterprise gating

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#52903]
Current status:

* Most of the important Cody code is in `enterprise` (embeddings, etc.)
* That makes it enterprise-licensed
* We don't have any gating: you can just compile Sourcegraph enterprise and use Cody/embeddings without putting in a license key.

What we should probably do:

* Create `licensing.FeatureCody`
* Add `licensign.Check(licensing.FeatureCody)` calls, like [these](https://sourcegraph.sourcegraph.com/search?q=context%3Asourcegraph+repo%3A%5Egithub%5C.com%2Fsourcegraph%2Fsourcegraph%24+licensing.Check%28licensing.Feature&patternType=standard&sm=0&groupBy=path) to the endpoints (just like the feature flag checks)
* Hide UI elements if customer doesn't have Cody (is the site-admin Cody sidebar only in enterprise? it should be)

**Comment by pjlast** [comment]
Is there a definitive list of plans that have Cody enabled?
