### ISSUE TITLE
Handle bad repositories with ref HEAD

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#5291]
- **Sourcegraph version:** k8s.sgdev.org

While testing the Gitolite external service I noticed that on `k8s.sgdev.org` the repo cloned via gitolite contains a `warning: refname 'HEAD' is ambiguous.` at the end:

<img width="564" alt="Screen Shot 2019-08-19 at 13 34 07" src="https://user-images.githubusercontent.com/1185253/63262369-08c44f00-c286-11e9-8265-6936147ec44d.png">

That is _not_ in the original file. You can see that the version cloned from `ghe.sgdev.org` does not contain it:

https://k8s.sgdev.org/ghe.sgdev.org/sourcegraph/facebook-react@827cbc4d00b668af6bbcca98f1730d4c8a546845/-/blob/packages/react-art/Wedge.js

And on `umami.sgdev.org`, which also has `Gitolite` configured (but a slightly different `callsignCommand`), it doesn't show up either:

https://umami.sgdev.org/gitolite.sgdev.org/13k/facebook/react@9c6de716d028f17736d0892d8a3d8f3ac2cb62bd/-/blob/packages/react-art/Wedge.js?diff=9c6de716d028f17736d0892d8a3d8f3ac2cb62bd

**Comment by mrnugget** [comment]
I can reproduce this locally:

<img width="726" alt="Screen Shot 2019-08-19 at 14 13 00" src="https://user-images.githubusercontent.com/1185253/63264488-7a52cc00-c28b-11e9-8f07-a683e93bc1fb.png">

If I then `cd` into the bare repository and run `git log` I get the same `warning`:

```bash
$ cd ~/.sourcegraph_docker/data/repos/gitolite.sgdev.org/13k/agermanidis/autosub
$ git log -1 | head -n 1
warning: refname 'HEAD' is ambiguous.
commit d32389cb76e63ec6959111c3f989a72f36f726fe
```

If I then clone this bare repository (we use `git --mirror` to clone repos) locally to another folder to get a work tree, the warning disappears:

```bash
$ cd ~/tmp
$ git clone ~/.sourcegraph_docker/data/repos/gitolite.sgdev.org/13k/agermanidis/autosub/.git
Cloning into 'autosub'...
done.
$ cd autosub
$ git log -1 | head -n 1
commit d32389cb76e63ec6959111c3f989a72f36f726fe
```

I'm wondering whether this is a release blocker or not at this point.

**Comment by mrnugget** [comment]
I'm pretty sure this is not a bug on our Sourcegraph side, but rather an issue with the gitolite instance. After adding private/public SSH key to my local machine I cloned one of the repositories and get the same error:

```
$ git -c protocol.version=2 clone --mirror --progress git@gitolite.sgdev.org:13k/clojure/spec-alpha2 .git
Cloning into bare repository '.git'...
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = "en_US.UTF-8",
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
remote: Counting objects: 1959, done.
remote: Compressing objects: 100% (665/665), done.
remote: Total 1959 (delta 698), reused 1959 (delta 698)
Receiving objects: 100% (1959/1959), 407.87 KiB | 147.00 KiB/s, done.
Resolving deltas: 100% (698/698), done.

$ cd .git
$ git log -1 | head -n 1
warning: refname 'HEAD' is ambiguous.
commit dc960158ccb9cf8b5dc555842eea5e1af12f28c2
```

The interesting thing is that there _is_ a branch called `HEAD`:
```
$ git branch
  HEAD
  alternate-closed-impl
  gh-pages
* master
  ns-refactor
```

And that's what's producing the error, according to this [StackOverflow question & answer](https://stackoverflow.com/questions/1692892/warning-refname-head-is-ambiguous)

**Comment by keegancsmith** [comment]
yeah this is just a bad repository. Not a release blocker, but we should see if there is a way to rev-parse the default branch even if a repo has a tag/ref called `HEAD`

**Comment by mrnugget** [comment]
Inclined to closet his since it seems the issue is the same as in https://github.com/sourcegraph/sourcegraph/issues/4619 (cc @slimsag and @kzh )

**Comment by keegancsmith** [comment]
Proposal: If a repository contains the ref `HEAD`, remove the ref. We can do this whenever we run fetch / clone (we already have some other stuff we do like this).
