### ISSUE TITLE
[aso] Support teams for assigned ownership

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#52929]
TODO list:

- [x] #52985
- [x] #52986
- [x] #52987
- [x] #52988
- [x] #52989
- [x] #52990
- [ ] #53011

**Comment by sashaostrikov** [comment]
Closing this issue because feature-wise this task is complete 🎉 

Only https://github.com/sourcegraph/sourcegraph/issues/53011 is left as a tentative tech debt.
