### ISSUE TITLE
SAML: Nil pointer error bug

### ISSUE THREAD

**Issue by justdueck** [sourcegraph/sourcegraph#52962]
- **Sourcegraph version:** 5.0 
- **Platform information:** K8s

Note: filing on behalf of https://github.com/sourcegraph/accounts/issues/8735 

Follow-up to this support ticket: https://sourcegraph.zendesk.com/agent/tickets/13522 

#### Steps to reproduce:

1. Add a SAML auth provider
2. Login using the new SAML provider

#### Expected behavior: 
Login behaves normally and no errors are thrown

#### Actual behavior:
Nil point errors are thrown in the admin panel:
![image](https://github.com/sourcegraph/sourcegraph/assets/70413452/e369a5ce-3345-478d-b787-2e697caeebd8)

#### Suspected cause (shared by customer admin): 
The SAML provider is the only provider that will return a nil, nil result from the GetPublicExternalAccountData function if it can’t find external data from the SAML provider.

[The ](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@v5.0.1/-/blob/cmd/frontend/graphqlbackend/external_account_data_resolver.go)externalAccountDataResolver[ expects ](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@v5.0.1/-/blob/cmd/frontend/graphqlbackend/external_account_data_resolver.go)that GetPublicExternalAccountData either returns a *extsvc.PublicAccountData or it return nil will an error. But never nil without an error. If a nil pointer is returned, then these functions will result in a nil pointer dereference error

In my specific case, our ID provider doesn’t return any of the fields here: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@v5.0.1/-/blob/enterprise/cmd/frontend/internal/auth/saml/user.go?L190-196
Instead it unhelpfully returns an Email field (capital E). So displayName is "" which results in nil, nil being returned.

**Comment by kopancek** [comment]
We should probably also make sure that we treat the assertion fields in a case insensitive way, so that `Email` with a capital `E` would work as well 🤔

**Comment by kopancek** [comment]
> @justdueck, thanks for the detailed description. It seems this was already fixed #50091 by @thenamankumar, as there was similar issue for another customer. However it doesn't seem to be backported to the previous patch releases. @thenamankumar should this be backported? cc @sourcegraph/iam

I created a backport PR here: https://github.com/sourcegraph/sourcegraph/pull/52981

**Comment by kopancek** [comment]
And here is a fix for the case insensitive matching:
- https://github.com/sourcegraph/sourcegraph/pull/52992
