### ISSUE TITLE
Switch GraphQL field for limit to BigInt

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#53007]
Int in graphql is the int32 type, as javascript can only properly handle 32 bit integers. For embeddings, it might be that we exceed the maximum value for int32. 

tokensPerDollar = 1 / (0.0004 / 1000)
hypothetical limit: $20 / user / month, broken down by day:
20 * uc * tokensPerDollar / 30 = 20*(1 / (0.0004 / 1000))/30 per user = 1.6M
for 5000 users that is 8.33B, > the 2B max of int32.

**Comment by unknwon** [comment]
https://github.com/sourcegraph/sourcegraph/pull/53290 has rolled out for the server-side change, we are in the compatibility period now.
