### ISSUE TITLE
Searching for `"tap(val =>" count:30` is slow on sourcegraph.com

### ISSUE THREAD

**Issue by ijt** [sourcegraph/sourcegraph#5301]
Currently, searches like `"tap(val =>" count:30` take far longer than 1s to run. In fact, this search gives a 504, probably due to exceeding the nginx timeout on the order of minutes. 

However, when run with `index:only` it returns in 0.13 seconds. 

This suggests it would be a better user experience for sourcegraph.com to default to index:only until we can track down why some of the default repos are not in the list of `zoektRepos`.

**Comment by ijt** [comment]
CC @keegancsmith who suggested this variant of the idea.

**Comment by ijt** [comment]
Care has to be taken in the code to not do this for searches that can only be run against the searchers (non-indexed).

**Comment by ijt** [comment]
@christinaforney what do you think?

**Comment by slimsag** [comment]
What about instances that do not yet have any repositories indexed?

**Comment by ijt** [comment]
In that situation, how about we display a banner saying "No results because search was run with index:only but none of the $N repositories have been indexed yet. If you need results right away, try the search again with index:yes or index:no." ?

**Comment by keegancsmith** [comment]
I don't think we should do this in general. This should only be the case for `default_repo` searches on sourcegraph.com.

For other instances global search should just work except on initial setup. But on initial setup we are cloning all repos anyways. IE we want searcher to do "global" search since it will still be a small set of repos it can do quickly => we give users a good first experience.

**Comment by ijt** [comment]
@keegancsmith, I made a new PR based on your suggestion (#5325).

**Comment by ijt** [comment]
It's still slow after merging #5325, and adding index:only still gives it a big speedup.

**Comment by ijt** [comment]
... and now it's fine. 

<img width="583" alt="Screen Shot 2019-08-21 at 10 43 10 PM" src="https://user-images.githubusercontent.com/15530/63488814-24398080-c465-11e9-9015-8892edfc2de9.png">

<img width="632" alt="Screen Shot 2019-08-21 at 10 41 42 PM" src="https://user-images.githubusercontent.com/15530/63488835-33203300-c465-11e9-8241-3d636a62c267.png">

<img width="649" alt="Screen Shot 2019-08-21 at 10 40 53 PM" src="https://user-images.githubusercontent.com/15530/63488840-387d7d80-c465-11e9-8848-b975f56f3a37.png">
