### ISSUE TITLE
Inline Chat UX Polish & Papercuts

### ISSUE THREAD

**Issue by dominiccooney** [sourcegraph/sourcegraph#53017]
- [ ] The "on brand" colors should be theme-aligned, themeable, and consistent
- [x] Inline fixup should not steal focus, selection while the user is typing elsewhere https://github.com/sourcegraph/sourcegraph/issues/53801
- [x] Branding the feature "Inline Chat" because other things are extra commands (ie /fix)
PR https://github.com/sourcegraph/sourcegraph/pull/53725
- [x] #53977
- [x] #53978
- [x] “Processing” etc. labels in the inline chat fix should match the non-stop labels
PR https://github.com/sourcegraph/sourcegraph/pull/53348
- [x] Inline Chat: Remove comment threads on doc closing
PR https://github.com/sourcegraph/sourcegraph/pull/53348
- [ ] display chat in comments only and not in side bar (some people reported it to find this confusing)
- [x] #53979

**Comment by dominiccooney** [comment]
Polish, work required for Inline Chat & Non-Stop Fixups:

TIM = @toolmantim , BEE = @abeatrix , DPC = @dominiccooney 

[TIM] Cody button in top nav bar should not be in color; weight of lines, size, etc. are wrong
⭐  [BEE] Apply all but give up if there are conflicts
[BEE] Order of icons in tree view should match actions in code lens
[BEE] Branding: Inline Chat; does have extra commands, (/fix)
[BEE] Inline Chat prompt should tease /t /c /help in its help message
[BEE] While Cody is “doing the blue stuff”, spinner should stay spinning; when the fixup is ready, change to a pencil instead of a sparkle
[BEE] Smiley face in the treeview when the LLM is done, make it a pencil
[BEE] “Processing” etc. labels in the inline chat fix should match the non-stop labels
PR https://github.com/sourcegraph/sourcegraph/pull/53348
[BEE] Inline Chat: Remove comment threads on doc closing
PR https://github.com/sourcegraph/sourcegraph/pull/53348
⭐  [DPC] Queue multiple items while chat is busy
⭐  [DPC] Respin tasks when there’s a conflict
[DPC] Add a “Cancel” button to the code lens (circle w/ slash thru it)
[DPC] Remove “Edit” for now and bring it back, needs a new label and different order
[DPC] Put a tiny part of the prompt with the “fixup ready” text and add a tooltip w/ the instructions
[DPC] Add apply all button to the top right next to the cody icon
[DPC] Highlighting in the track where Cody has edited, etc.
[DPC] When apply all fails, toast that N fixups failed and note we are respinning
[DPC] Dismiss the quickpick if you hit enter with no input
[DPC] Remove the fixups if you close and reopen the file

**Comment by mrnugget** [comment]
I'll defer to @toolmantim on this, but my 2 cents: these are still experimental features so "hiding" them in the settings is still fine. Once we have more non-experimental features that are toggleable, then yes, we should probably surface them in the Cody settings UI.

**Comment by deepak2431** [comment]
That makes sense to me. Thanks @mrnugget!

**Comment by toolmantim** [comment]
Good q @deepak2431, we've looked into it, but your own settings page is actually [a VS Code anti-pattern](https://code.visualstudio.com/api/ux-guidelines/settings). We're removing our own Settings view altogether, but also linking to the Cody section of the User Settings to make it more accessible. And we've added a Cody button to the status bar, where you can toggle things on and off (we may not include things that are very experimental).

**Comment by deepak2431** [comment]
Thanks for the response @toolmantim. So, we need to support VS Code anti-pattern for the settings page, right?
That sounds good. I can see the recent changes in the main where we have a toggle button at the top which would open the settings page for any configuration. I think this is a good solution for now.

**Comment by abeatrix** [comment]
Moved Inline Chat out of experimental: https://github.com/sourcegraph/sourcegraph/pull/54315

**Comment by abeatrix** [comment]
With all the recent changes I believe we can close this issue. I will created a separate issue for the ` display chat in comments only and not in side bar` item since that is not a priority and will add it to the backlog
