### ISSUE TITLE
Log whether embeddings are used for cody interactions

### ISSUE THREAD

**Issue by kelsey-brown** [sourcegraph/sourcegraph#53048]
Since embeddings are emerging as a key differentiator for us, it would be useful to be able to track whether cody leveraged embeddings in a given interaction so we can understand how well they are working (by correlating with 👍 / 👎  responses) and if users who leverage embeddings retain better/are more engaged, etc. 

[Link](https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1686000336694969) to thread in #ask-cody where this was discussed

**Comment by keegancsmith** [comment]
FYI there is a PR implementing this that is out. It is purely a change to cody client code, it did not require backend changes.

**Comment by keegancsmith** [comment]
> Do you know how difficult it would be/if it's possible to get this detail on other events (e.g. chat/recipe events generally), not just feedback events?

The way it is written we should be able to use this logic anywhere we have access to the transcript when logging the event. I can follow up with this once I get the more targeted PR out.

**Comment by keegancsmith** [comment]
@kelsey-brown I'm gonna be out next week. But if ya want me to follow-up with logging this sort of information in more places I'm happy to do it. Do you mind just speccing the expectations in an issue for me so I don't forget? :)
