### ISSUE TITLE
Ownership assign permission seems to be true for users role by default which it shouldn't

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#53065]

**Comment by sashaostrikov** [comment]
as per [documentation](http://localhost:5080/admin/access_control#system-roles) it is expected. So I think it is maybe an admin's responsibility to turn off some unwanted features?

**Comment by sashaostrikov** [comment]
well, actually I made a fix for that
https://github.com/sourcegraph/sourcegraph/pull/53121
