### ISSUE TITLE
Cody bug: reauth required on each restart

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#53085]
Reported by [an enterprise user on Slack](https://sourcegraph.slack.com/archives/C04SL5AKNG3/p1686147076060459?thread_ts=1685111922.547769&cid=C04SL5AKNG3)

>  extension seem to get reset randomly after re-launches of vscode which means people need to re-enter their access token

```
Debug Using the in-memory credential store as the operating system's credential store could not be accessed. Please see https://aka.ms/vscode-server-keyring on how to set this up. Details: Error calling StartServiceByName for org.desktop.secrets: Timeout was reached -- [proc: vscode-server] [output: stderr]
```

**Comment by abeatrix** [comment]
I believe this is an known issue with VS Code on Linux: https://github.com/orgs/community/discussions/46696
Here is a potential solution provided by VS Code that might help: https://code.visualstudio.com/docs/editor/settings-sync#_linux

We should look into an alternatives for users who run into this issue

**Comment by eseliger** [comment]
We should add a paragraph to our docs about this known issue and the workaround and can then close this ticket.
