### ISSUE TITLE
Cody focus: Hide unnecessary nav bar items

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#53113]
The only items in the nav bar, from left to right, should be: 

- Cody logo (replace the Sourcegraph logo)
- Back/Forward navigation buttons
- (Remove Code search)
- Cody AI tab
- (Remove Notebooks, Monitoring, Batch Changes, Insights)
- Feedback
- Try Sourcegraph Enterprise
- Indexed repos icon
- Settings gear

**Comment by limitedmage** [comment]
@taylorsperry Should we have *both* the Cody logo replacing the Sourcegraph logo *and* the cody tab? That means there will be two cody icons in the navbar.

**Comment by limitedmage** [comment]
That would make it THREE Cody icons on the top-left corner of the main page...

![Image](https://github.com/sourcegraph/sourcegraph/assets/206864/9d976b92-30cd-4a16-b9ec-54b61f297e15)
