### ISSUE TITLE
Cody Focus: Setup experience

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#53110]
Since the new version of the app will _only_ support Cody functionality, we need to update the setup experience to: 
- Remove the "skip" connect to dotcom option (all users will be required to log in through dotcom)
- Open to the Cody Chat view in the app (instead of the code search view) once setup is complete. 
```[tasklist]
### Tasks
- [ ] Remove the "skip" connect to dotcom option (all users will be required to log in through dotcom)
- [x] Open to the Cody Chat view in the app (instead of the code search view) once setup is complete.
```

**Comment by marekweb** [comment]
We will want to sufficiently test situations where the user has logged out or otherwise managed to remove or skip the dotcom requirement despite completing the setup experience wizard, to make sure they're prompted to login again.
