### ISSUE TITLE
e2e-tests: Deleting resources fails because accepting dialog does not work

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#5312]
In the e2e tests we try to delete the external services and access tokens we create in the test run by doing something like this:

```javascript
await Promise.all([
    driver.acceptNextDialog(),
    (await driver.page.waitForSelector(
        `[data-e2e-access-token-description="${name}"] .e2e-access-token-delete`,
        { visible: true }
    )).click(),
])
```

Apparently this doesn't work anymore: the database fills up with external services and access tokens.

```
psql -c "SELECT id, display_name FROM external_services"
Timing is on.
Null display is "[NULL]".
Expanded display is used automatically.
 id |    display_name
----+---------------------
 34 | e2e-test-github
 33 | e2e-aws-code-commit
 35 | e2e-aws-code-commit
 32 | e2e-test-github
(4 rows)

Time: 1.267 ms
```

```
psql -c "SELECT note FROM access_tokens"
Timing is on.
Null display is "[NULL]".
Expanded display is used automatically.
                   note
-------------------------------------------
 E2E Test 5820351
 E2E Test 2006-01-02T22:04:05.000Z 6129130
 E2E Test 2019-08-19T15:04:57.714Z 559159
 E2E Test 2019-08-19T15:14:36.553Z 8525552
(4 rows)

Time: 2.136 ms
```

I don't know whether [this change here](https://github.com/sourcegraph/sourcegraph/commit/ed3c78572444ae2969b58b253ccc64a149bda2ea#diff-98acdd9b6a32e47600edfe9b3eecf57f) is the cause of the regression.

cc @felixfbecker @lguychard — If someone could help me debug this, I'd appreciate it :)

**Comment by felixfbecker** [comment]
If the code completes, that means the delete button was clicked, and a dialog was accepted. If that doesn't work, then that can only mean the code either doesn't run, or there is no time given afterwards to actually perform the request.
Is the code guaranteed to run (i.e. even on test failure)?

**Comment by mrnugget** [comment]
Sorry for wasting your time @felixfbecker — I could confirm in the actual component that the button is clicked and the external services is deleted... I forgot that we have soft deletion for external services 🤦‍♂ 

```
psql -c "SELECT id, display_name, deleted_at FROM external_services"
Timing is on.
Null display is "[NULL]".
Expanded display is used automatically.
 id |    display_name     |          deleted_at
----+---------------------+-------------------------------
 38 | e2e-test-github     | 2019-08-20 01:32:37.458293-07
 40 | e2e-test-github     | [NULL]
 39 | e2e-aws-code-commit | 2019-08-20 01:33:12.356693-07
 41 | e2e-aws-code-commit | [NULL]
(4 rows)

Time: 2.386 ms
```
