### ISSUE TITLE
Cody focus: Rebrand as Cody app

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#53120]
* Replace the Sourcegraph icons (all of them, including system tray icon and the app icon) with Cody icon
* Rename the window title to Cody
* Rename the download / .app / .dmg / whatever to `Cody`

In the system tray right now we have:

* `Open Sourcegraph`
* `Show Cody`

The order of these should be flipped, and they should be renamed:

* `Show chat` (previously `Show Cody`)
* `Open desktop app` (previously `Open Sourcegraph`)

Change the navbar icon to Cody icon:

![Image](https://user-images.githubusercontent.com/3173176/240725952-c3f5e88f-e6ba-46a5-8752-06ddacb45dea.png)

The logo on the homepage is being discussed here: https://sourcegraph.slack.com/archives/C04F9E7GUDP/p1684957920927489

## Tracked PRs

- [x] #53518 
- [x] #53562 
- [x] #53552

**Comment by taylorsperry** [comment]
@almeidapaulooliveira or @danielmarquespt would you be able to provide assets for this? Sorry, tagging you both because I know you're kind of tag teaming app efforts right now :)

**Comment by almeidapaulooliveira** [comment]
Thanks, Taylor. Please tag us both and we split the work, no problem.

**Comment by limitedmage** [comment]
> The order of these should be flipped, and they should be renamed:
> 
> * `Show chat` (previously `Show Cody`)
> * `Open desktop app` (previously `Open Sourcegraph`)

What should each of these two options do? Both will open the Cody chat, one big and one small. Are we still going to have the smaller cody window?

**Comment by taylorsperry** [comment]
It seems redundant to have both, doesn't it. If the "big chat" is responsive and can essentially be resized to look like the "small chat," then I think we can get rid of the small chat.

**Comment by taylorsperry** [comment]
Closing because I'm pretty sure this is all done. We can address anything we missed as a papercut follow-up.
