### ISSUE TITLE
Discrepancy in reported repository count between admin and non-admin users

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#5318]
Reported by https://app.hubspot.com/contacts/2762526/company/554338610.

Repro:

* Visit /explore as a normal user and admin user
* In the “Repositories" section, a normal user just sees 4 repos and doesn't see the "view all" link at the bottom:
![image](https://user-images.githubusercontent.com/1646931/63394955-eeb66980-c376-11e9-95ee-2d15be85dbd8.png)
* An admin user sees the link, and can click to see all 7 repositories

No repository permissions have been configured on this instance.

**Comment by tsenart** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.9 release is scheduled for tomorrow** at 10:00 CEST.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
