### ISSUE TITLE
diff search results not showing with subrepository permissions enabled

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#53190]
When running the query `context:global repo:^github\.com/sourcegraph/handbook$ type:diff` on k8s.sgdev.org with subrepository permissions enabled [(link)](https://k8s.sgdev.org/search?q=context:global+repo:^github\.com/sourcegraph/handbook%24+type:diff&patternType=standard&sm=1&groupBy=author&trace=1), no results are reported. However, when I disable repository permissions in https://k8s.sgdev.org/site-admin/configuration (`experimentalFeatures.subRepoPermissions.enabled: false`), results show up again.

This issue occurs regardless of whether gRPC is enabled or not. It has been present for a while, and I've observed it with this Sourcegraph version: https://github.com/sourcegraph/sourcegraph/commit/f19120acfc23. The issue was also reported a month ago here: https://sourcegraph.slack.com/archives/C03CSAER9LK/p1684527204846789?thread_ts=1684450942.294169&cid=C03CSAER9LK

### Steps to reproduce

1. Enable subrepository permissions on k8s.sgdev.org (`experimentalFeatures.subRepoPermissions.enabled: true`)
2. Run the search query `context:global repo:^github\.com/sourcegraph/handbook$ type:diff`
3. Observe that no results are reported: <img width="1506" alt="Screenshot 2023-06-08 at 12 06 32 PM" src="https://github.com/sourcegraph/sourcegraph/assets/9022011/88123576-d11e-4fbf-bd00-6ab291658fee">
4. Disable subrepository permissions ( `experimentalFeatures.subRepoPermissions.enabled: false` )
5. Run the search query again
6. Observe that results show up: <img width="1485" alt="Screenshot 2023-06-08 at 12 07 42 PM" src="https://github.com/sourcegraph/sourcegraph/assets/9022011/5ff8f8e0-ec0e-4684-be07-2a4ca409c05f">

### Expected behavior

Search results should show up even when subrepository permissions are enabled.

### Version

Sourcegraph version: https://github.com/sourcegraph/sourcegraph/commit/f19120acfc23

/cc @ryphil @mrnugget

**Comment by keegancsmith** [comment]
Fixed by @pjlast in https://github.com/sourcegraph/sourcegraph/pull/53210
