### ISSUE TITLE
Error: `write: /home/sourcegraph/.p4trust.lck: Read-only file system` when syncing Perforce depot

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#53268]
- **Sourcegraph version:** 5.0.4

#### Steps to reproduce:

1. Connect to a Perforce server requiring P4TRUST

#### Expected behavior:

Depot sync without errors

#### Actual behavior:

Error:

```
Fetching from code host Perforce: trust: exit status 1 (output follows)
The fingerprint of the server of your P4PORT setting
'ssl:perforce:1666' (10.100.10.10:1666) is not known.
That fingerprint is 3A:32:F9:9C:AB:EC:91:EF:BE:0D:D1:BE:EC:45:4F:E6:34:F2:07:5E
Unrecoverable lock error '/home/sourcegraph/.p4trust.lck' (open for
write: /home/sourcegraph/.p4trust.lck: Read-only file system).
```

If you would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are no [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

/cc @ryphil @mrnugget

**Comment by peterguy** [comment]
One way to address this is by using the `P4TRUST` environment variable to specify a different location for the `.p4trust` file. Probably the temp directory, which is usually `/tmp`. For K8s, something like `kubectl set env statefulset/gitserver P4TRUST=/tmp`, or adding it to [the Helm chart for gitserver](https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/main/charts/sourcegraph/templates/gitserver/gitserver.StatefulSet.yaml#L51), or to [values.yaml](https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/main/charts/sourcegraph/values.yaml#L452).

**Comment by eseliger** [comment]
Closed by https://github.com/sourcegraph/sourcegraph/pull/57330
