### ISSUE TITLE
App Setup: If user added exactly 1 local repo, auto-select it in embeddings step

### ISSUE THREAD

**Issue by marekweb** [sourcegraph/sourcegraph#53275]
If I select exactly 1 local repo, then on the next step (the embeddings step) it would be an improvement if:

- the one repo is pre-selected so I only have to click "next" instead of having to select it from scratch
- OR (even better?) it automatically selects that one repo for embeddings and skips the embeddings page entirely

Screenshot of what happens currently:

![Image](https://github.com/sourcegraph/sourcegraph/assets/602886/980617ac-6ea2-4fd7-9f0c-991251a5c6a8)

**Comment by vovakulikov** [comment]
@danielmarquespt what do you think about this? Based on our conversation about this step and more educational purpose of this we may still want it even when we have just one repository, but what we can do is pre-selecting this repo item automatically so user can click Next button without selecting anything
