### ISSUE TITLE
Re-evaluate the use of `redsync.Mutex` in source syncer

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#53283]
Follow up of https://github.com/sourcegraph/sourcegraph/pull/53137#discussion_r1223770260

Determine whether we could get away with `redislock.TryAcquire` instead.

**Comment by unknwon** [comment]
I think we do want some niche feature provided by `redsync.Mutex` e.g. extending the lock period. A better time to reconsider is when we refactor the entire source sync logic next time, the risk of stability here is not worth the effort at this time.

cc @bobheadxi

**Comment by bobheadxi** [comment]
Sounds good!
