### ISSUE TITLE
Race condition having to do with search and SQL

### ISSUE THREAD

**Issue by ijt** [sourcegraph/sourcegraph#5329]
I saw this race condition in the logs today:

<img width="994" alt="Screen Shot 2019-08-21 at 10 03 33 PM" src="https://user-images.githubusercontent.com/15530/63487982-1df5d500-c462-11e9-85dd-04485f94d1a4.png">

**Comment by anukul** [comment]
Hi!

From the traceback, I found some related issues - https://github.com/golang/go/issues/23519, https://github.com/lib/pq/pull/706 and was able to reproduce the data race in general usage of `lib/pq`

![image](https://user-images.githubusercontent.com/44864521/89088279-097dc480-d3b5-11ea-878e-84ce2435e185.png)

It looks like `lib/pq` is [not maintained](https://github.com/lib/pq#status) any longer, but I can probably try to fix the problem by following an approach similar to the https://github.com/go-sql-driver/mysql/pull/943 patch for this issue, if that helps.

**Comment by unknwon** [comment]
cc @sourcegraph/cloud ^ WDYT about changing lib/pg to pgx?

**Comment by asdine** [comment]
It seems like a good opportunity to switch to pgx 👍

**Comment by lguychard** [comment]
This no longer appears to be relevant.
