### ISSUE TITLE
Chat Predictions: Toggling the feature flag should enable/disable the feature

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#53316]

**Comment by lrhacker** [comment]
After trying this out on v0.3.20230620, it appears that you can enable/disable this setting and have that change be reflected when starting a **new** chat session with Cody. After a brief discussion with @philipp-spiess, he confirmed the behavior and we agreed that it would be sufficient for the purposes of this issue.

**Comment by philipp-spiess** [comment]
@lrhacker nice!
