### ISSUE TITLE
Add docs for adding TFS repos

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#5331]
Our docs (https://docs.sourcegraph.com/admin/repo/add) don't cover how to add MSTS/TFS repos. We've had several users and companies ask about this in the last few months. 

Today, I assume users would follow our instructions for adding "other" repos at https://docs.sourcegraph.com/admin/external_service/other

**Comment by rajeshwarbharathi** [comment]
Are there any specific instructions to add Microsoft TFS code repos?

**Comment by dadlerj** [comment]
Hi @rajeshwarbharathi ! We do provide docs for this at https://docs.sourcegraph.com/admin/external_service/non-git

Essentially, you would run `git-tfs` to clone the TFS project and convert it to Git format, then run our `src-expose` tool to expose it to Sourcegraph. 

You would have to then periodically (perhaps every minute) run a command to fetch changes from TFS and merge them into the default branch (e.g. `git tfs pull`).

Please let us know if that makes sense.

CC @keegancsmith this is another use case for https://github.com/sourcegraph/sourcegraph/issues/9643
