### ISSUE TITLE
Cody testing: run end-to-end test for large monorepo 

### ISSUE THREAD

**Issue by jtibshirani** [sourcegraph/sourcegraph#53343]
With the release coming up, we'd like to run a test for generating and searching embeddings for a large monorepo (~6GB HEAD). We can assume a Cloud environment. 

This helps us double-check all the pieces come together correctly:
* We can successfully embed a large repo using Cody Gateway and not get stuck on rate limiting
* Job workers have enough memory by default (if not we can bump the Cloud defaults?)
* Embedding search service has enough memory by default
* Embedding search times are 1-2 sec as expected, given SIMD support

**Comment by marcleblanc2** [comment]
Can we test for a 17 GB HEAD? 
Slack [thread](https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1687207016996139)
