### ISSUE TITLE
grpc: re-enable zoekt-webserver grpc support

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#53356]
gRPC support for sourcegraph-frontend > zoekt-webserver communication was implemented in #50647 . However, when it was merged last week, we discovered a bug (see https://sourcegraph.slack.com/archives/C04HCK4K3DL/p1686100826372909) on sourcegraph.com that caused us to have to disable gRPC. 

We have since [re-enabled gRPC](https://github.com/sourcegraph/deploy-sourcegraph-cloud/pull/17910), and put the sourcegraph-frontend > zoekt-webserver communication behind a separate feature flag (off by default) in https://github.com/sourcegraph/sourcegraph/pull/53118. 

After the Sourcegraph 5.1.X release, we should revisit what the issue is here and re-enable gRPC supporrt for zoekt-webserver.

**Comment by eseliger** [comment]
@ggilmore is this still the case, or can we close it out?
