### ISSUE TITLE
Allow multiple auth providers to same URL

### ISSUE THREAD

**Issue by kopancek** [sourcegraph/sourcegraph#53361]
We have [several customers](https://github.com/sourcegraph/customer/issues/2157) who have complicated authentication setup. E.g. have GitHub Managed Enterprise Users alongside normal GitHub users (both on github.com) that need to be linked to the same account on Sourcegraph.

Currently our authentication data model assumes and enforces that there is a single auth provider per URL. This is because historically we were mapping auth providers to code host connections by their URL. But in general, nothing provides customers from creating multiple OAuth apps on the same code host and we should support this, going forward.

The problematic part here is the existing code, that relies on the single auth provider per URL condition. We need to figure out which parts rely on it and how to refactor everything.

/cc @sourcegraph/source/iam

**Comment by mrnugget** [comment]
@pjlast you fixed this, right? Can you link to PR and close?

**Comment by pjlast** [comment]
https://github.com/sourcegraph/sourcegraph/pull/54289
