### ISSUE TITLE
Update setup experience

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#53419]
Once designs [here](https://www.figma.com/file/ZkJFUvVzZW9TgFg7k9w9Oq/App-%5BMAIN%5D?type=design&node-id=62-661&t=EHKN7p7r9ANLUnsJ-0) are finalized, we should implement changes in time to do some user testing early next week. Ideally we could cut this release no later than Tuesday, June 20.

**Comment by cbart** [comment]
I'm going to close this issue as it seems like it's done. Please reopen if I'm wrong.
