### ISSUE TITLE
Remove blob view hyperlinks

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#53415]
When Cody "reads N files," the user can see which files Cody read and open them in the blob view. The Cody-only app won't have a blob view, so we need to remove those hyperlinks (at the very least) or (ideally) allow those hyperlinks to open the file in your editor.

**Comment by chwarwick** [comment]
@vovakulikov  Is is possible to swap out [this](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/cody/components/ChatUI/ChatUi.tsx?L236:14&popover=pinned) component for App? I think that would remove the links to the blobview

**Comment by vovakulikov** [comment]
@chwarwick it's possible to override link on the client, this component could be replaced in the runtime but we also need to have full local path of the file in order to create a vs code deep link in order to open a file in vs code (or other IDE)

**Comment by chwarwick** [comment]
Yeah for now lets just make it not broken,

We can come back later for open in client we'll need need to know client preference and local path. draft pr here https://github.com/sourcegraph/sourcegraph/pull/53721

**Comment by vovakulikov** [comment]
@chwarwick just to make sure by not broken you mean we're going to delete link?

**Comment by chwarwick** [comment]
> @chwarwick just to make sure by not broken you mean we're going to delete link?

Currently if you click one of the file links you get 
<img width="1011" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/6098507/8841203a-073b-423d-85ff-4173f41357f2">

So the top priority is making sure that doesn't happen, we can come back in another round to attach to open in the editor if we like.

**Comment by vovakulikov** [comment]
@chwarwick Yeah I understand, I just trying to understand that removing this link is ok and we will add vscode editors deep links later
