### ISSUE TITLE
[Cody] VScode Extension Sign In redirect URL is broken

### ISSUE THREAD

**Issue by JoeTot** [sourcegraph/sourcegraph#53425]
- Cody VS Code Extension, Windows 11 Pro 22H2

#### Steps to reproduce:

1. Install Cody VS Code extension from the marketplace
2. Navigate to the extension using the sidebar in VS Code
3. Click 'Continue with Sourcegraph.com
4. Observe that you are redirected to the following link in your browser: https://sourcegraph/user/settings/tokens/new/callback?requestFrom=CODY
5. Observe that this link is broken and will not authenticate the extension for the user

#### Solution
1. Update the link to the following: https://sourcegraph.com/users/{username}/settings/tokens/new/callback?requestFrom=CODY
2. Paste this link in browser
3. Observe that user is now correctly redirected to authorize Cody VS Code extension

#### Expected behavior:
- User is asked to authorize the Cody VS Code extension using Sourcegraph

#### Actual behavior:
- Broken link in browser

If you would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are no [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

**Comment by deepak2431** [comment]
@JoeTot This PR #53418 should fix it. I can reproduce it on Mac too. Thanks for reporting!

**Comment by abeatrix** [comment]
@JoeTot @deepak2431  Thank you so much for bringing this to our attention! The fix has been merged and will be included in tonight's nightly build and the next stable release!
