### ISSUE TITLE
JetBrains: Chat: Fix message field for long prompts

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#53465]
If I enter a longer prompt, it looks like this:

<img src="https://github.com/sourcegraph/sourcegraph/assets/2552265/c28e19c5-92c8-4d02-b92b-aa853ca75e0a" width=200 />

My problems with it:

- [x] Textbox height grows indefinitely. Solution: Give it a reasonable max height, such as "25% or 300px, whichever is less". (If that's too difficult to do with Swing, do either.)
- [x] Text is broken at random places and is difficult to read. Break text at word boundaries rather than at character boundaries
- [ ] This font is not easily readable and is perhaps a bit too large. Use the default UI font instead (usually a sans-serif).
- [x] After submitting the long prompt, it appears squashed in the chat: 
    <img src="https://github.com/sourcegraph/sourcegraph/assets/2552265/e47014b8-1484-4536-91cc-64bac60703cc" width=200 />
    It's because line breaks are not retained. Suggested solution: retain line breaks in user input.

**Comment by vdavid** [comment]
My prompt in the test was this:

```
Hi Cody!

I want a Python function that will analyze a given text file and compute some statistics. Specifically, the function should take the file path as input, read the file, and then return the following statistics:

The total number of words in the file
The most frequently used word and its frequency
The least frequently used word and its frequency
The average word length in the document
The function should ignore case when counting word frequencies, meaning 'The' and 'the' should be considered as the same word. Also, consider punctuation marks as separate "words" for the purpose of this task, to keep things simple. However, if you have an idea to handle them in a more sophisticated way, I'm eager to hear about that too!

I want to use this function to analyze various text files I have and gain some insights about the data. It's important that the function is efficient, as some of the text files are quite large.

Additionally, please include some error handling. If the file cannot be read or does not exist, the function should return a meaningful error message.

Can you help me with this?
```

**Comment by szymonprz** [comment]
>After submitting the long prompt, it appears squashed in the chat:
this one is fixed in https://github.com/sourcegraph/sourcegraph/pull/53543

**Comment by vdavid** [comment]
One of the problems is not fixed, so reopening.
