### ISSUE TITLE
App: Create download link redirect that always points to the latest release

### ISSUE THREAD

**Issue by marekweb** [sourcegraph/sourcegraph#53511]
We would benefit from setting up download URLs that redirect to the latest release of App, for each download type.

Use cases:

- In the editor extensions, in the CTA to download the App, it's been suggested that we should link directly to the download URL instead of linking to the download page (reducing the amount of clicks to start the download). The VSCode extension can determine the current platform (and architecture) but it does not know the latest version of App. Other editor extensions probably have a way to determine the platform as well.
- On the About site, it would take less manual effort when releasing, and it would be less error-prone, if the download button URLs always pointed to the latest release URL so we would not have to update the About site for every release of App.

How this would work:

- We need a URL for each download (which includes differentiating between Intel Mac and Apple Silicon) that redirects to the latest release URL for that download.
- The redirect destination would be updated manually or automatically when a new public release of App is published.

**Comment by chwarwick** [comment]
cc @abeatrix for having a single stable url for downloading the latest version of App from the extension.

**Comment by marekweb** [comment]
[List of ideas here](https://sourcegraph.slack.com/archives/C04F9E7GUDP/p1687451345445299)

**Comment by taylorsperry** [comment]
[Closed](https://sourcegraph.slack.com/archives/C055X672BV0/p1687895247790599?thread_ts=1687883300.706589&cid=C055X672BV0) by @slimsag
