### ISSUE TITLE
Missing Apache license file

### ISSUE THREAD

**Issue by Timmmm** [sourcegraph/sourcegraph#53528]
The [terms](https://about.sourcegraph.com/terms) link to [LICENSE.apache](https://github.com/sourcegraph/sourcegraph/blob/main/LICENSE.apache) which does not exist. The existing license files effectively mean that Sourcegraph is no longer open source. Is that intended?
```[tasklist]
### Tasks
- [ ] Ask legal what's up
```

**Comment by deepak2431** [comment]
@Timmmm, I think that the link is just broken. @jdorfman do have a look at it!

**Comment by SuperAuguste** [comment]
Please see [the new LICENSE](https://github.com/sourcegraph/sourcegraph/blob/main/LICENSE) - that page is currently out of date :)

**Comment by jdorfman** [comment]
@Timmmm I'll follow up asap.

**Comment by beyang** [comment]
As part of preparations for our upcoming release, we've made the code search parts of Sourcegraph enterprise licensed. We've made this decision after careful consideration. Here are the factors in our thought process:

- Our licensing principle remains to charge companies while making tools for individual devs open source.
- Very few individual devs or companies used the limited variant of code search that was open source. The vast majority (99.9%+) used the enterprise product. Maintaining two variants was a big burden on our engineering team that had very little benefit for users.
- Our customers and users do value the code and development being publicly visible, and we've preserved that. The source code will remain publicly available.
- Individual devs will still be able to use Sourcegraph for free on public code at sourcegraph.com and with our self-hosted free tier on private code.
- The community edition of our AI developer tool, Cody, is meant for individual devs and we've open-sourced that under Apache 2. We believe this will be the primary tool individual devs use moving forward, with code search integrating with Cody for enterprises.
- We remain committed to Zoekt, the open source code search engine, and will continue to upstream changes to it.

**Comment by Timmmm** [comment]
Ah good to know! Sorry if I accidentally scooped a blog post. :-)

**Comment by beyang** [comment]
No worries, thank you for your understanding and apologies for the confusion! We're currently working on updating the terms and other places on our site.

**Comment by paulorcf** [comment]
Same old history! Grow open, became famous, and close the code!
So sorry, I core feature it's not more open source...

:-(

**Comment by gianluca-sabena** [comment]
Is it possible to have the last commit with apache licence and the list of proprietary code to be removed so I can fork the last 100% open source version of sourcegraph?

**Comment by Timmmm** [comment]
I don't think it was ever 100% open source, but you can easily find that commit yourself by looking at the blame of the license files. It's from about 3 weeks ago.
