### ISSUE TITLE
Assigned owners are not filtered out from graphQL resolvers.

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#53555]
In own resolvers each ownership mechanism or signal has methods to compute those for relevant directory or file. See for instance `computeAssignedOwners` in https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/internal/own/resolvers/resolvers.go.

Blob resolver allows filtering ownership by reasons `ownership(first: 2, reasons: [CODEOWNERS_FILE_ENTRY, ASSIGNED_OWNER]) {...}`, there were if statements guarding this for all reasons except for assigned owners which were included always (bug). This was fixed in https://github.com/sourcegraph/sourcegraph/pull/53557/files

**Comment by varsanojidan** [comment]
Would you mind adding a bit more context on this one? Which query should they be filtered out of? Are they filtered by default?

**Comment by cbart** [comment]
My apologies, this was just a quick note and I should have followed-up with an elaborate description.

**Comment by coury-clark** [comment]
Closed by https://github.com/sourcegraph/sourcegraph/pull/53557
