### ISSUE TITLE
Configure context lines from the search results page

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#5357]
#### Feature request description

A user requested a way to configure the number of context lines shown in results on a per-search basis. So, a way to do this from the search page would be nice to have.

Perhaps a drop down/toggle/text box on the search page would work.

**Comment by slimsag** [comment]
Also requested by a user at https://app.hubspot.com/contacts/2762526/company/1712860829/ https://sourcegraph.slack.com/archives/C01574FJV35/p1598478767000100

**Comment by andelink** [comment]
+ would like to see this feature

**Comment by lguychard** [comment]
Duplicate of #2754
