### ISSUE TITLE
Animate typing of Cody's responses

### ISSUE THREAD

**Issue by dominiccooney** [sourcegraph/sourcegraph#53596]
Feedback from @eseliger in Slack: https://sourcegraph.slack.com/archives/C052G9Y5Y8H/p1686273374220809

> I find the UI for cody while it’s typing always feels a bit broken, especially for longer responses. The “streaming” is not character by character but buffered so it would often wait 500ms and then spit out a whole chunk again. That doesn’t really get me a sense of it “typing” but rather it semi broken trying to print a longer text. Maybe this is just me, but if others feel like that too, have we considered “faking” it typing more fluently before?

This is a good idea; we should make the text appearance more fluid. In the past when the stream was less buffered/processed, we did have a lot of flicker as the Markdown parser worked. So we do need some intelligent chunking of the animated chunks to avoid flash-of-un-marked-down-content.

**Comment by abeatrix** [comment]
Based on the Changelog for 4.3 it looks like @umpox has added this 😄
