### ISSUE TITLE
Allow people to scroll up during Cody response generation

### ISSUE THREAD

**Issue by toolmantim** [sourcegraph/sourcegraph#53641]
Feedback from @steveyegge in Slack: https://sourcegraph.slack.com/archives/C05AGQYD528/p1686981156410759

> Some feedback on auto-scrolling in the chat window:  Often when I ask Cody a question, I’m interested in reading its answer while it’s still generating.
> But by default we keep it scrolled to the bottom, even if you are trying to scroll up to read from the top.

**Comment by toolmantim** [comment]
I've updated the [Message Sending and Scrolling](https://www.figma.com/file/9112BsKsJc1BpO2j8XYwLL/%F0%9F%A4%96-Cody-VS-Code-%5BMain%5D?type=design&node-id=3532-142495&t=ngqO0VBlXbdjQ6qd-4) prototype with a down/follow button:

https://github.com/sourcegraph/sourcegraph/assets/153/de27cad7-1543-4bda-98ad-c0462ea1d9dc

Notes:
* When you scroll up, the follow up button appears, and clicking it will get you back down to the bottom (and keep it stuck to the bottom if it's streaming, or if you scroll back up again)
* I've adjusted the padding around the "..." indicator, and the position of the "Stop Generating" and "↓" buttons, to make sure those buttons aren't obscuring the last line of test as it's generating.

**Comment by philipp-spiess** [comment]
@umpox I think your PR #54188 has fixed this, correct? 🙂
