### ISSUE TITLE
Add notification banner for old versions of the app

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#53702]
@marekweb is working on this [Context](https://sourcegraph.slack.com/archives/C04F9E7GUDP/p1686949770932749?thread_ts=1686861996.329299&cid=C04F9E7GUDP)

**Comment by marekweb** [comment]
I opened a PR for this last week and haven't come back to it 

- https://github.com/sourcegraph/deploy-sourcegraph-cloud/pull/17949
