### ISSUE TITLE
Selecting a folder with no repos in it should display an error

### ISSUE THREAD

**Issue by danielmarquespt** [sourcegraph/sourcegraph#53701]
When selecting a folder that contains no repos, the app should display an erro/info to the user about this. Right now the apps fails to display anything and its unclear for the user what happened and why the folder was not added to the list:

https://www.loom.com/share/ae60fd95398a46d284176e1d886d58e3

**Comment by taylorsperry** [comment]
Repro'd [here](https://sourcegraph.slack.com/archives/C04PE4H6XGT/p1687893461619669).
