### ISSUE TITLE
Cody: Fix stop generating button positioning

### ISSUE THREAD

**Issue by deepak2431** [sourcegraph/sourcegraph#53729]
The new Chat layout has the Stop generating button, but the position of the stop generating button overrides the generated response.
It would be good to position it relative to the transcript item text.

CC: @toolmantim @abeatrix 

![iScreen Shoter - Code - 230620112456](https://github.com/sourcegraph/sourcegraph/assets/44617923/aad7d6b0-8ecc-46e7-a0ce-3775e9c29480)

**Comment by deepak2431** [comment]
@abeatrix @toolmantim Also tested the new chat layout, great work on it. Looks pretty impressive :)

**Comment by toolmantim** [comment]
Thanks for raising this! The layout needs some fixing for sure. The feedback buttons also aren't quite positioned correctly.

I have a design in the works to resolve both of these things (and a follow button for allowing people to scroll up). But if we wanted to get a quick fix out now, we could add `var(--spacing)` or so worth of padding to the last `.transcript-item`, if that item is still being generated.

**Comment by deepak2431** [comment]
@toolmantim  Agreed with you as just some layout fixes needed there for the feedback, stop buttons. 
Saw you created an issue to track all of them, so that would resolve all of it. Do you want a quick fix for now? I can do that based on your suggestions.

One thing more which I think should be taken care of. If you see now, the input text and the response are not that differentiable as both seem like same. Maybe using some icons would make that look better. What do you think of this?

 See this:
![iScreen Shoter - Code - 230620135202](https://github.com/sourcegraph/sourcegraph/assets/44617923/99601be0-a98f-4742-923a-089b976ef083)

**Comment by toolmantim** [comment]
Yes please, fixed are always appreciated!

**Comment by toolmantim** [comment]
> One thing more which I think should be taken care of. If you see now, the input text and the response are not that differentiable as both seem like same. Maybe using some icons would make that look better. What do you think of this?

I'm trying to visualize what you mean. Do you have an example?

**Comment by deepak2431** [comment]
@toolmantim See this example, I am just confused which is prompt and which is the response:
![iScreen Shoter - Code - 230620155159](https://github.com/sourcegraph/sourcegraph/assets/44617923/e85fac16-b1df-4f1f-b0bb-fe9e94cbe17d)


I have also added one more above

**Comment by toolmantim** [comment]
Sorry, I was asking for an example of what your suggested fix was! By icon, you mean user avatars?

**Comment by deepak2431** [comment]
@toolmantim Yeah, something like that. As I saw in one of the issues you created the design to differentiate user messages from recipes which I couldn't find. So, something like that would be helpful.

**Comment by abeatrix** [comment]
@deepak2431 thanks for the ping! I'm working on a quick fix that should address the stop generating button issue and should be included in today's release!

**Comment by deepak2431** [comment]
@abeatrix Awesome, that's great!
