### ISSUE TITLE
Add literal search interpretation of query pattern

### ISSUE THREAD

**Issue by ijt** [sourcegraph/sourcegraph#5374]
This issue tracks progress on @christinaforney's [RFC 11: Add literal search interpretation of query pattern](https://docs.google.com/document/d/1H71c86fagAyuJGgbEsgfAJ5wH0or0MXzyyGsShSIzcw/edit#) for literal search, according to the [implementation plan](https://www.notion.so/Implementing-default-literal-search-79e3f66e4d8c4e3bad4cf59a98bf6db4).

**Comment by lguychard** [comment]
Backlogging as this is unlikely to make the 3.8 branch cut, cc @attfarhan

**Comment by tsenart** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.9 release is scheduled for tomorrow** at 10:00 CEST.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by tsenart** [comment]
I believe this is resolved by #5899. Please re-open an change the milestone accordingly if not @attfarhan.
