### ISSUE TITLE
Clicking on the dock icon should open the main window

### ISSUE THREAD

**Issue by danielmarquespt** [sourcegraph/sourcegraph#53756]
After closing the main window, its only possible to open it again via the tray icon.

Clicking on the dock icon should open the main window.

https://www.loom.com/share/3ccc86ed6e5b4fac8a8cd5bfb2552aab

**Comment by vovakulikov** [comment]
@limitedmage I'm running out of time on the progress bar UI issue. Can you take a look at this? A quick check gave me not much, but that Tauri doesn't expose events from the dock menu

**Comment by limitedmage** [comment]
Yup I can take a look and see if this is possible.
