### ISSUE TITLE
App - Document apis and other measures that are available for extensions

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#53765]
Document methods that App uses for extension connections as well as APIs that are available and should be used for additional functionality. 

## App resolver

We have an API resolver that provides App calls. TODO: describe the resolver and describe API calls

The App resolver is in https://github.com/sourcegraph/sourcegraph/blob/main/enterprise/cmd/frontend/internal/app/resolvers/app.go

## Connect to App over local API

Making requests to the local App API requires an access token. You can find by opening `app.json` on the file system.

When App is installed and runs for the first time, it generates an access token and saves it in `app.json` in the App config directory.

- On MacOS `app.json` is located at:
  -  `~/Library/Application Support/com.sourcegraph.cody/app.json`
- Linux:
  - $XDG_DATA_HOME/com.sourcegraph.cody/app.json 
  - **or**- $HOME/.local/share/com.sourcegraph.cody/app.json.
- Windows:
  - Resolves to {FOLDERID_LocalAppData}/com.sourcegraph.cody/app.json.

Contents of `app.json`:

```json
{
  "token": "xxxxx",
  "endpoint": "http://localhost:3080",
  "version": "2023.06.16"
}
```

**Comment by marekweb** [comment]
I'll create a home for this information in the docs
