### ISSUE TITLE
GitLab native integration

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#5380]
Ship Sourcegraph integration as part of Gitlab.

Plan:
- On by default on gitlab.com for public repositories, talking to sourcegraph.com
- Disabled for private repos on gitlab.com (important, needs test)
- Off by default for private Gitlab instance, with admin UI to set Sourcegraph URL of a private Sourcegraph instance + links to our docs
- Native integration is published to npm for Gitlab to pull in (and update with monthly Gitlab releases) #5379 

Merge Request: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/30574

**Comment by lguychard** [comment]
@felixfbecker closing as this is done now.
