### ISSUE TITLE
JetBrains: Let users conveniently connect to Cody App

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#53834]
We want to be able to connect to Cody App rather than sourcegraph.com or an enterprise instance to access the LLM, and everything else that we use the Sourcegraph API for.

Notes:
- The most important thing to remember is that the Cody App is like any enterprise instance in most aspects. The two key differences are that it's local and that we can count on the user to have admin access to it, which means we are free to use the full GraphQL API.
- We've got some context from #job-fair-app on determining whether App is installed, where to find the access token in the file system if it is installed, and how deep linking to App works.

A hopefully complete breakdown of what we'll want to do:
- [x] Create utility function to detect whether App is installed. Clue: [this](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/cody/src/services/LocalAppDetector.ts?L44) is how VS Code does it.
- [x] Create utility function to grab App's URL and access token from the file system (location and format are [here](https://github.com/sourcegraph/sourcegraph/pull/53782))
- [x] Add a third option to Settings, like [this](https://share.cleanshot.com/Hl0ncPV2).
  - If App is not detected, gray this out, and add a gray label below to explain that App is not present, with an App download link. Ideally, try to re-detect every time the Settings window gets focus, to auto-update this state
  - If App is detected then just explain in the label that the user needs no access token, we're ready to connect
- [x] Add "Download Cody App" and "Start Cody App" states to the sidebar (Like [this](https://share.cleanshot.com/WGYq9YzN) and [this](https://share.cleanshot.com/dmPk4N85) – First two screens from the [figma](https://www.figma.com/file/9112BsKsJc1BpO2j8XYwLL/%F0%9F%A4%96-Cody-VS-Code-%5BMain%5D?type=design&node-id=3288-142843&t=rG9PiIzT1awZjwqG-0)). The design is not important for the first iteration, just make it work
- [x] Modify ConfigUtil to work well if App is set as the current server. Its API works _exactly_ like an enterprise instance, so once we wire it up with ConfigUtil, it should just work!
- [x] Test it with App ([here](https://about.sourcegraph.com/app)) and see if it connects nicely
- Plus we have two follow-on tasks that I added to a separate issue for later: https://github.com/sourcegraph/sourcegraph/issues/53916

**Comment by danielmarquespt** [comment]
Designs for the Sidebar: https://www.figma.com/file/m9Yvgv6W3aPRLfXnxgwnEz/IntelliJ?type=design&node-id=82%3A3089&mode=design&t=aQUY6NSex1mBKRPU-1

**Comment by danielmarquespt** [comment]
> If App is detected then just explain in the label that the user needs no access token, we're ready to connect

In this case if would be cool to have a "connect with app" action from the Settings screen as weel

**Comment by vdavid** [comment]
@Gedochao, I had the task to "Check what VS Code does if you want to trigger an autocompletion with Cody App but Cody App is not running. Does it show a notification or something?"
I did that, and it looks like if App is configured but isn't running, the chat just hangs forever, and there are no completions, but there is no notification or anything. So, I'd say the bar is quite low here.
We can iterate on this later.

**Comment by Gedochao** [comment]
Right.
I'd still rather have some safety nets around it if I find the time to set them up, but noted, thanks for clearing that.

**Comment by Gedochao** [comment]
Done in https://github.com/sourcegraph/sourcegraph/pull/54298
