### ISSUE TITLE
Show values of constants in tooltip

### ISSUE THREAD

**Issue by ihrankouski** [sourcegraph/sourcegraph#5383]
#### Feature request description

How difficult is it show the values of constants in the tooltip? (At least in Go files.)
That might save some time while exploring the new code.

Example: https://sourcegraph.com/github.com/wangjohn/quickselect@master/-/blob/quickselect.go#L314

That's what it looks like in Sourcegraph: 
<img width="655" alt="Screen Shot 2019-08-28 at 12 53 12 PM" src="https://user-images.githubusercontent.com/3798567/63845676-fd160e00-c992-11e9-8f99-02a5aaa3665a.png">

Compare with VScode: 
<img width="662" alt="Screen Shot 2019-08-28 at 12 53 41 PM" src="https://user-images.githubusercontent.com/3798567/63845703-0dc68400-c993-11e9-8cca-7fe015acccc5.png">

**Comment by christinaforney** [comment]
Great idea @ihrankouski ! While we can't immediately prioritize this, I'll keep it on the backlog.

@sourcegraph/code-nav how much work do you think this would be? Any concerns from an engineering perspective?

**Comment by chrismwendt** [comment]
It looks like the [go-langserver](https://github.com/sourcegraph/go-langserver) is providing that tooltip. It would probably be easy to implement, but we don't have any resources to invest in language servers at the moment. If anyone else is interested in implementing, this would be a welcome improvement.

**Comment by notjrbauer** [comment]
@christinaforney  I know this request was from awhile ago, but it was a simple fix 👍 
https://github.com/sourcegraph/go-langserver/pull/380

**Comment by efritz** [comment]
Merged. Will ensure the new version is deployed to DotCom.
