### ISSUE TITLE
Authorize app refers to Sourcegraph instead of Cody

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#53848]
Internal feedback in [thread](https://sourcegraph.slack.com/archives/C04NPH6SZMW/p1687307166854579?thread_ts=1687306987.164139&cid=C04NPH6SZMW). 

![Image](https://user-images.githubusercontent.com/43555476/247539750-8e905ea6-2d83-465b-ac23-e611a65a0ecd.png)

**Comment by marekweb** [comment]
Fixed in https://github.com/sourcegraph/sourcegraph/pull/53714 I think
