### ISSUE TITLE
migrator: Fix version printing

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#53863]
![image](https://github.com/sourcegraph/sourcegraph/assets/103087/52d1d3fd-7369-4c21-bfe1-4067be8b206c)

**Comment by Strum355** [comment]
Hackishly solved by https://github.com/sourcegraph/sourcegraph/pull/53864

**Comment by efritz** [comment]
Really solved by #54161

**Comment by efritz** [comment]
uhhh #54163 

![image](https://github.com/sourcegraph/sourcegraph/assets/103087/f805fd84-f72d-4884-a4ed-b90cd31833a9)
