### ISSUE TITLE
Add "Get Cody Enterprise" CTA

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#53891]
We previously had a link to "Try Sourcegraph Enterprise" in the app nav bar. I know we decided to remove it because it felt noisy, but it should be somewhere, and probably renamed "Get Cody Enterprise" and link to https://about.sourcegraph.com/contact/request-info.

**Comment by chwarwick** [comment]
@danielmarquespt Do you have any ideas where we should put this?

**Comment by chwarwick** [comment]
@taylorsperry  any tags on that link like `utm_source`?
