### ISSUE TITLE
Cody Chat opens docs in the UI

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#53892]
When chatting with Cody in the app Cody Chat UI, there's a prompt to check the docs for guidance. The docs then open in the Chat UI, and there's no way to get back to the Chat. I'm guessing the easiest solution is to make that a link that goes out to docs.sourcegraph.com/app. Here's a [loom](https://www.loom.com/share/068504225ce24df793b8af80b0683462?sid=bcb0d36a-1fd7-4fc8-97f3-7ca6728dedca) to describe what I'm talking about.

**Comment by marekweb** [comment]
I looked at this and the link is defined inside of the [initial Cody conversation message in markdown](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/cody-ui/src/Chat.tsx?L322%3A1-323%3A1).

This apparently blocks us from using the normal solution to open it in a new browser tab, which is to add `target="_blank"` (the `target` attribute gets stripped I think)

I'm looking for a workaround.

**Comment by marekweb** [comment]
The change I made in https://github.com/sourcegraph/sourcegraph/pull/54010 will fix this for not just the initial docs link but for all links in Cody chat messages.
