### ISSUE TITLE
FR: Add github authentication

### ISSUE THREAD

**Issue by Warchant** [sourcegraph/sourcegraph#539]
#### Feature request description

My organization actively uses github and I would like to be able to use github authentication for my hosted sourcegraph.

**Comment by sqs** [comment]
We plan to add this in the future, but I don't have an ETA. The work on repository permissions (see roadmap https://docs.sourcegraph.com/dev/roadmap) is a step in this direction.

Can you give some more details about what you need? This would help us prioritize.

- GitHub.com or GitHub Enterprise?
- Do you use SAML/OpenID as the auth provider for GitHub (on the Business plan) or GitHub Enterprise?
- If not, does your organization use any SSO systems (SAML/OpenID/LDAP/G Suite/etc.)?
- Prefer GitHub OAuth2 or GitHub Apps integration?

**Comment by Warchant** [comment]
>GitHub.com or GitHub Enterprise?

github.com

>does your organization use any SSO systems (SAML/OpenID/LDAP/G Suite/etc.)?

G Suite

>Prefer GitHub OAuth2 or GitHub Apps integration?

Github apps.

**Comment by sqs** [comment]
Thanks. Why do you prefer GitHub user authentication over G Suite user authentication? (I can think of plenty of reasons, just curious for your answer.)

**Comment by Warchant** [comment]
There is no particular reason, just personal preference :-)

**Comment by nicksnyder** [comment]
We are tracking progress on the feature in https://github.com/sourcegraph/sourcegraph/issues/964
