### ISSUE TITLE
Cody: Chat screen goes blank on load

### ISSUE THREAD

**Issue by deepak2431** [sourcegraph/sourcegraph#53911]
On Load, the Chat screen goes blank if there's any recent chat. The same happens on Reload of Window during the chat.
See this video for the behaviour: 

https://github.com/sourcegraph/sourcegraph/assets/44617923/e9c2b0e7-f4d0-491f-9508-095b6b4e22a7

I have tried to debug a bit to check if there's any issue happening while loading the recent chat from history, but I can't see any error there.
CC: @abeatrix @philipp-spiess

**Comment by philipp-spiess** [comment]
Ugh this looks like a release blocker. thanks for reporting, we'll look into it

**Comment by deepak2431** [comment]
Additionally, the token is not getting retrieved from the local storage on Load. I need to do multiple reloads for successful login.


https://github.com/sourcegraph/sourcegraph/assets/44617923/9bc63281-3a12-4b46-8a28-eead089ed4ef

**Comment by philipp-spiess** [comment]
@deepak2431 I can't reproduce the empty view anymore on `main` after https://github.com/sourcegraph/sourcegraph/pull/54021. Can you confirm?

**Comment by philipp-spiess** [comment]
There's a very awkward flickering now when you load the screen where it shows the logged out view expect the loading indicator :(

**Comment by deepak2431** [comment]
@philipp-spiess The bug when the screen goes blank is fixed, and the second one I mentioned is fixed. And, yes, to the awkward flickering.

One thing, right now, when the extension gets loaded, the behaviour is` loading extension->login screen->chat view`.
It would be good to have flow `loading extension->chat view`. So, we will read the token during the extension load phase only. WDYT?

**Comment by philipp-spiess** [comment]
Yeah I think we should at least have a `loading` state until we wait for the initialization to be complete somewhat. I wonder if @abeatrix has ideas. I wanted to look into this at the end today if I have time but I won't get to it in the next couple of hours.

**Comment by philipp-spiess** [comment]
Let me make a new ticket for this. This one is fixed ✅

**Comment by deepak2431** [comment]
@philipp-spiess Cool, I Agree with you. We should at least have a loading state, and it should not show the Login Screen if the user is already authenticated.
