### ISSUE TITLE
Cody: Running recipies with a huge selection truncates without the user being aware of it

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#53920]
When you select a lot of code and run a recipe, you cat no answer.

Repro:

- Open and select all of `cmd/frontend/internal/app/updatecheck/client.go`
- Run the code smell recipe
- Observe no answer

Expected behavior: 

- Show an error that too much text is selected

**Comment by deepak2431** [comment]
@philipp-spiess Created a PR for this. The issue was just with the smell code recipe. When we were calculating the `truncatedText`, we were passing the wrong ` token` input MAX length, which was causing this behaviour. 
All other recipes work fine with larger input too, as they have the `truncatedText` calculated correctly.

**Comment by philipp-spiess** [comment]
@deepak2431 You're an absolute hero!

**Comment by deepak2431** [comment]
Thanks a lot :)

**Comment by philipp-spiess** [comment]
I’m going to reopen this for a different change. We should add a user-facing warning somehow when the selection is truncated just so we know what's going on. This is far less critical though than the original issue :)

**Comment by deepak2431** [comment]
@philipp-spiess Got it. I can handle that in the next PR. Just a question, the warning message should be displayed as a VSCode message, or should it be displayed in the webview?

**Comment by philipp-spiess** [comment]
@deepak2431 Hmm what do you think? I think in the web view it might be less confusing since it opens anyways.

**Comment by deepak2431** [comment]
@philipp-spiess As I can see in the current implementation, any warning/error message is displayed using the VSCode editor context. So, I think that would be good for this too!

As in Webview, a new message will appear at the top while the response is generated, so in terms of UX, I don't think it's good behaviour. Just my thoughts!

**Comment by philipp-spiess** [comment]
@deepak2431 Yeah makes sense I agree!
