### ISSUE TITLE
JetBrains: Add Cody commands to the context menu

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#53934]
We have this menu now that doesn't mention Cody:

![image](https://github.com/sourcegraph/sourcegraph/assets/2552265/b83acdf3-4178-4615-912a-01c5dc8fa66e)

And in VS Code we have:

<img width="653" alt="CleanShot 2023-06-22 at 13 32 02@2x" src="https://github.com/sourcegraph/sourcegraph/assets/2552265/3618b14a-10e7-4075-830d-c6e51d7e1353">

We'll want to add these in JetBrains, too

**Comment by vdavid** [comment]
@szymonprz, I think https://github.com/sourcegraph/sourcegraph/pull/54430 closes this one?

**Comment by szymonprz** [comment]
That's right
