### ISSUE TITLE
JetBrains: Completions: Add settings to allow bring-your-own-LLM

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#53973]
(Context – not essential to complete this issue: https://github.com/sourcegraph/accounts/issues/6716 needs these. [Related Slack thread](https://sourcegraph.slack.com/archives/C04QG1H3YHW/p1686834640704379))

We want to allow customers to bring their own LLM for the completions. We solved this for VS Code in [this PR](https://github.com/sourcegraph/sourcegraph/pull/53495). It adds two new settings: "cody.completions.advanced.provider" and "cody.completions.advanced.serverEndpoint".
The goal would be to add these two new settings to the JetBrains plugin, to a not-too-prominent location. Probably adding them to the `sourcegraph-jetbrains.properties` would be the best option, then [`UserLevelConfig.java`](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/jetbrains/src/main/java/com/sourcegraph/config/UserLevelConfig.java?L27) could read it.

So no UI change is needed here, but completions should use this LLM for their stuff.

**Comment by vdavid** [comment]
We promised to deliver this by July 1

**Comment by vdavid** [comment]
@Gedochao: for testing, there is a test server mentioned in the "Test plan" section of https://github.com/sourcegraph/sourcegraph/pull/53495.
I started it with `cd client/cody && pnpm ts-node ./scripts/mock-server.ts` and it seems to work.
I think this is all we need for testing.
@philipp-spiess, do you agree, or is there anything else we should know?

**Comment by philipp-spiess** [comment]
@vdavid Yup I think this makes sense. Once you consider this done, there's a document that Mark wrote on how to connect to a VPS that has access to the "live" backend :) All that needs is to swap the URL then.
