### ISSUE TITLE
App: Add a deep link that the editor can use to launch App and which immediately redirects back to editor

### ISSUE THREAD

**Issue by marekweb** [sourcegraph/sourcegraph#53970]
### The problem

Consider this situation:

- you're in the Cody editor extension
- App has already been installed and set up
- but App isn't currently running

Then the editor extension can't use the App's API. So we need to launch App.

### Proposed solution

From the editor, opening a deep link to App will automatically launch App.

We can add a special deep link in App that automatically redirects back to the editor, so that you come back to where you were.

Once App is launched, when you return to the editor, the extension should detect that App is now running and should now use App's API.

### Implementation details

We could have a page in App that says (paraphrasing) "Go back to your editor."

Ideally the page would automatically then redirect to a deep link to the editor, if it's supported (for VS Code, this is supported with `vscode://` and we can target the Cody extension as the destination)

Whether or not we are able to automatically redirect to the editor, the page would at least tell the user the next step that they should expect.

**Comment by toolmantim** [comment]
This could be a nice improvement. I'd lean to an automatic redirect first, vs another click, but worth testing how it feels in the overall flow.
