### ISSUE TITLE
[FF EXTENSION] Authorization lost when github review page is loaded

### ISSUE THREAD

**Issue by tdorzhi** [sourcegraph/sourcegraph#540]
- **Sourcegraph version:** 
2.12.3

- **Platform information:** 
OS: Solus Project 3.99999 (kernel 4.18.9-92)
Browser: Firefox 62.0.3 64-bit
Extension: Sourcegraph 1.18.0

#### Steps to reproduce:

1. Install extension sourcegraph 1.18.0
2. Authorize in organization's sourcegraph  (extension has green connection with said server)
3. Open github page and open `Review Changes` page
4. Open organization's sourcegraph page and see login page (despite being authorized less than minute ago)

#### Expected behavior:
Authorization is intact after any github page being opened

#### Actual behavior:
Authorization lost after opening `Review Changes` page

**Comment by ijsnow** [comment]
Hello! This was fixed by [this commit](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/1857613e69cb49f3d01281b33cea4e6be242d19f). This fix was released in 2.13.
