### ISSUE TITLE
Cody context chat reset Issue

### ISSUE THREAD

**Issue by almeidapaulooliveira** [sourcegraph/sourcegraph#54002]
There is a reported bug where Cody does not respond accurately until a new chat is initiated, even after the context is selected. 

## Steps to reproduce:
 - No context in the selector. Ask Cody to explain the `sourcegraph/sourcegraph` repository. Cody answers that doesn't have access to that repository.
- Add the `sourcegraph/sourcegraph` to the context.
- Ask Cody to explain the `sourcegraph/sourcegraph` repository. Cody answers that doesn't have access to that repository.
- Start a new chat. `sourcegraph/sourcegraph` is in the context.
- Ask Cody to explain the `sourcegraph/sourcegraph` repository.
- Cody answered correctly.

---

###  Note:
I ran an old version. In that version, the context did not reset when users started a new chat. The current version (in `main`) doesn't allow us to do that, since the context is cleared when a new chat starts.

Video recording:
https://github.com/sourcegraph/sourcegraph/assets/64257673/255698f1-4762-4c01-b504-77540a2e9d4c

**Comment by almeidapaulooliveira** [comment]
@kalanchan stab on finding part of the problem:
https://sourcegraph.slack.com/archives/C04NPH6SZMW/p1687480070816299?thread_ts=1687385496.762039&cid=C04NPH6SZMW

**Comment by thenamankumar** [comment]
This PR solves it: https://github.com/sourcegraph/sourcegraph/pull/54023
