### ISSUE TITLE
Link to settings on missing embeddings status

### ISSUE THREAD

**Issue by almeidapaulooliveira** [sourcegraph/sourcegraph#54012]
This issue is part of this umbrella:
- #53844 

### Issue:
In the context selector, the user expected that when clicking on the embeddings icon status to be taken to the embeddings settings. Instead, it removed that repo from the context.

### Solution:
When showing 'no embeddings' for this repo, link to the settings page. So users can watch the progress or enable it.

<img width="506" alt="Screenshot 2023-06-22 at 7 11 01 PM" src="https://github.com/sourcegraph/sourcegraph/assets/64257673/64875a5d-c2d3-49ba-8361-49ea78f7928e">

From [Chris Pine's Cody Feedback](https://docs.google.com/document/d/1yTM0L4Qh1S1l4iZIgntW87gSLgkkeku0TITxP-DhSdY/edit)

**Comment by almeidapaulooliveira** [comment]
@toolmantim - Do you think that this solution makes sense? Or do you have another solution on #53844  that would address it better?

**Comment by toolmantim** [comment]
I think once the "Improve the indexing status tooltip" section of the linked PR is done (new copy and prominent link in the tooltip), this should be resolved.

If that's still not enough, we could investigate linking the whole thing like here.
