### ISSUE TITLE
Cody: Sidebar shows login screen when still initializing

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/sourcegraph#54045]
Right now the sidebar in Cody shows the login screen instead of a loading screen while the extension is still booting up. We need to fix this with a distinct loading phase I think. 

https://github.com/sourcegraph/sourcegraph/assets/458591/5a84abd6-d5fc-4f87-953b-769e324233e2

This might be a regression after https://github.com/sourcegraph/sourcegraph/pull/54021 cc @abeatrix

**Comment by philipp-spiess** [comment]
Some more context of this can be found in: #53911

**Comment by deepak2431** [comment]
@abeatrix @philipp-spiess I doubt if the previous logout issue is still completely fixed, as there's still some issue with it, maybe I think so. See this video for the current behaviour:


https://github.com/sourcegraph/sourcegraph/assets/44617923/915baab3-c886-4804-90e8-ffbfb72513b2

**Comment by abeatrix** [comment]
Can you try the build from https://github.com/sourcegraph/sourcegraph/pull/54106 ?

**Comment by deepak2431** [comment]
@abeatrix That needs to be merged before I can try that.

**Comment by deepak2431** [comment]
@abeatrix Just wanted to know, how's the new Login flow going to be? As of now I can't see any button to use sourcegraph.com/ other URLs. And, also I need to log in after each reloads with a new token.
