### ISSUE TITLE
App: In "Updates" page, link opens localhost:3080 in the browser

### ISSUE THREAD

**Issue by marekweb** [sourcegraph/sourcegraph#54058]
The link points to `/help/app#upgrading` but it doesn't get rewritten to `https://docs.sourcegraph.com/app#upgrading`. Instead it opens a browser to a localhost:3080 url.

![Image](https://user-images.githubusercontent.com/602886/248290666-1b8acc6a-e1ee-49f6-ae04-a9230fa8eff1.png)

**Comment by chwarwick** [comment]
closed by https://github.com/sourcegraph/sourcegraph/pull/54501
