### ISSUE TITLE
Enhancement: Worker deletes empty GitHub Apps on execution

### ISSUE THREAD

**Issue by st0nebraker** [sourcegraph/sourcegraph#54066]
Enhancement to [PR#52897](https://github.com/sourcegraph/sourcegraph/pull/52897)

When checking & syncing up GitHub App installations, also check if a GitHub App status returns a `404` (from the [Get App endpoint](https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#get-an-app)). Record that the App looks deleted, and surface that as a warning in the admin UI.

**Proposal**: Maybe the better user experience is that rather than deleting an App if we got a 404, we record that it looks deleted, and surface that as a warning from the admin UI...

**Comment by courier-new** [comment]
Good idea! The thing is, the user could theoretically uninstall it from everywhere without actually deleting it entirely, for example maybe if they're moving orgs and uninstall it from the original org before they install it in the new one. If they do eventually re-install it somewhere in the future, we wouldn't pick it up automatically anymore. So maybe we don't delete it from our DB, but just show a warning in the BC settings UI if there aren't any current installations found?

We _can_ totally delete the App if GH tells us the App has been deleted, though. We could probably check the App before trying to sync installations with the [Get App endpoint](https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#get-an-app).

**Comment by st0nebraker** [comment]
> We can totally delete the App if GH tells us the App has been deleted, though. We could probably check the App before trying to sync installations with the [Get App endpoint](https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#get-an-app).

Ah I think this would suffice, then! This is the main intent behind the issue, delete the app when relevant. Thanks for pointing the solution in the right direction!

**Comment by camdencheek** [comment]
cc @BolajiOlajide, is this related to https://github.com/sourcegraph/sourcegraph/pull/60460#discussion_r1488038017?

**Comment by BolajiOlajide** [comment]
Yes.
