### ISSUE TITLE
JetBrains: Cody agent should be disabled by default

### ISSUE THREAD

**Issue by szymonprz** [sourcegraph/sourcegraph#54127]
Cody agent is now enabled by default and the documentation of it is outdated, the cody agent should be disabled by default and we should have a proper documentation on how to enable it

**Comment by vdavid** [comment]
@szymonprz, the intended behavior is to have the Agent enabled by default for `./gradlew :runIde` (so that we dogfood it by default), and not for anything else. Is the implementation different from this?

**Comment by szymonprz** [comment]
Ohhhh I see, So i misunderstood our documentation as it says that to enable the agent we should do `./gradlew :runIde -PenableAgent=true`. Everything works as you said, so the agent is enabled only on local runs and is disabled on production plugin build
