### ISSUE TITLE
cody vscode: repo lock not communiated to user

### ISSUE THREAD

**Issue by Strum355** [sourcegraph/sourcegraph#54160]
If a user sets the repo in their global vscode settings and forgets about setting it, they may be confused when the repo used by Cody does not change when moving between vscode workspaces. We should include some indication that this is coming from global/local/whatever setting

**Comment by abeatrix** [comment]
Fixed in https://github.com/sourcegraph/sourcegraph/pull/54237

Included in the 0.4.0 release
