### ISSUE TITLE
SCIM auto deprovision users

### ISSUE THREAD

**Issue by johnwesonga** [sourcegraph/sourcegraph#54198]

**Comment by pjlast** [comment]
@johnwesonga is there somewhere I can get more information on this?

**Comment by johnwesonga** [comment]
@alexfogg is there a slack thread with more details? I looked at the product gap in Salesforce and there's not much there https://sourcegraph2020.lightning.force.com/lightning/r/Product_Gap_Submission__c/a1C5b00000BFlPPEA1/view

**Comment by johnwesonga** [comment]
I found this related GH issue https://github.com/sourcegraph/sourcegraph/issues/22732 "This feature request is to support SCIM 2.0 so that users are automatically soft-deleted when they are disabled in the IdP."

**Comment by pjlast** [comment]
@johnwesonga are we sure this is not supported? I think this was added in 5.0: https://about.sourcegraph.com/blog/release/5.0#:~:text=Admin-,SCIM%20support,-Sourcegraph%20now%20supports

From the code, it looks like the functionality is there.

**Comment by alexfogg** [comment]
Thanks for taking a look! I opened this gap up last year, so I think this should be good now as of 5.0.
