### ISSUE TITLE
Add Cody embeddings setup admin onboarding

### ISSUE THREAD

**Issue by erzhtor** [sourcegraph/sourcegraph#54205]
- [x] https://github.com/sourcegraph/sourcegraph/pull/54138
- [ ] add banner when less than 50% of repos are configured for embeddings
- [ ] add banner when more than 20% of embedding indexing jobs within last 24h are failing

cc @rrhyne, @ryphil

**Comment by mrnugget** [comment]
@rrhyne @ErikaRS we talked about this ticket in yesterday's planning and the question came up: is still up to date? should _we_ (Source) work on this?

Based on the recent rollout and [how it's not that straightforward to say that all customers should embed all code](https://sourcegraph.slack.com/archives/C04NPH6SZMW/p1688638981118639) I don't think the "less than 50% of repos are configured for embeddings" makes a lot of sense right now.

The "20% of embedding indexing jobs" failing: that's something the context team should/could own, right?

**Comment by mrnugget** [comment]
cc @cesrjimenez feel free to re-open if this comes up again
