### ISSUE TITLE
Cody context: Keyword search matches on file path

### ISSUE THREAD

**Issue by gl-srgr** [sourcegraph/sourcegraph#54236]
A keyword search that matches a filename or path should then promote that file to be used as context but from this [example](https://sourcegraph.slack.com/archives/C053L1AQ0BC/p1687507155466829) we observe that no filename matching is done.

```
In this case, both repos do not have embeddings.
`Can you show me first 10 lines from the readme.md files of all the repos in the context?`
readme.me file is not returned for any of the repo.
Do we do file name/path-based matching? And if yes, do we give them higher weightage?
```
![image](https://github.com/sourcegraph/sourcegraph/assets/105310278/2df14eff-041c-4463-bfca-dc3b5b28a173)

**Comment by thenamankumar** [comment]
Another example: I only request for 1 code result and 3 text results. 

Cody should give a much higher weightage in ranking for file name matching exactly with `useCodyChat`

<img width="1317" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/22571395/2ec7bcd3-3b5f-4686-83e9-57e390df9fb6">

**Comment by camdencheek** [comment]
Some related work: https://github.com/sourcegraph/sourcegraph/pull/54568

**Comment by jtibshirani** [comment]
Closing this in favor of https://github.com/sourcegraph/sourcegraph/issues/61571
