### ISSUE TITLE
App: Error on embeddings jobs screen on Linux

### ISSUE THREAD

**Issue by marekweb** [sourcegraph/sourcegraph#54301]
Seen on Ubuntu 22.10 x86_64 with `cody_2023.6.26+1328.bca7d2c3ed_amd64.AppImage`

May be due to limited support for this particular browser API in the webview on Linux.

![Screenshot from 2023-06-27 11-00-17](https://github.com/sourcegraph/sourcegraph/assets/602886/2941c59a-df79-45d8-b736-c6a07b2756e2)

**Comment by chwarwick** [comment]
A user has also report this issue, https://github.com/sourcegraph/app/issues/31
