### ISSUE TITLE
Context selector should not show deleted repos

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#54341]
The context selector should update to only show repos that are synced to the app. Currently, it still shows repos that have been removed from the app. [Thread](https://sourcegraph.slack.com/archives/C04PE4H6XGT/p1687894182933649).

**Comment by thenamankumar** [comment]
Should be automatically fixed with: https://github.com/sourcegraph/sourcegraph/pull/54357

**Comment by chwarwick** [comment]
closed by #54357
