### ISSUE TITLE
Simplify post signup flow

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#54465]
## Problem:

Before allowing users who have signed up to access the system, they need complete additional steps:
* Verify their email
* Indicate how they will use Cody (which causes lead generation to occur)

Currently, users who have just signed up are taken to the search homepage and we open a modal 
over the page while blocking other content. We also first cookie the users when they are coming 
from the about site to know they are new signups.   

These screens are not extendable and the code to determine this flow is a bit brittle, especially since it now requires cookies. 

## Solution:

We need to reduce the need for cookies and other measures of determining how to show these steps, and simply
redirect all signups to sourcegraph.com (but not a server installation) from any type of signup (email or OAuth) 
to dedicated ‘setup’ pages that do not require altering the main layout. 

Repurpose the existing interactions (do not block on verify, block on form submission)
  
[Figma](https://www.figma.com/file/DIk3eGdgKszigQVec7Y8SD/Frictionless-Cody?type=design&node-id=1617-37199&mode=design)
  

### Additional context: 

We previously had this exact flow. The page PostSignUp flow was part of this as it was a wizard UI that allowed multiple settings. This search may contain some helpful context at that time:

https://sourcegraph.com/search?q=context%3Aglobal+repo%3A%5Egithub%5C.com%2Fsourcegraph%2Fsourcegraph%24%40f66387f+PostSignUp&patternType=standard&sm=1&groupBy=path

Additionally, the additions from this PR can be removed https://github.com/sourcegraph/sourcegraph/pull/54422, as can logic like that added to the main layout to show the modals introduced here: https://github.com/sourcegraph/sourcegraph/pull/51523

**Comment by erzhtor** [comment]
I agree with the proposal. Having a single post-signup entry will simplify the flow and implementation. 

Here are a few notes to keep in mind while implementing this: 
1. The redirect to the new post signup flow should be added to all signup places (dotcom cloud signup, about/signup).
1. It would be even better to make this redirect universal, such as on the backend auth handlers, which will make sure that we don't forget to include `returnTo` to each signup place. 
   1. This will also allow us to catch signups via the sign-in page. Currently, users can sign-up via external auth (GitHub, GitLab, etc.) from https://sourcegraph.com/sign-in, and their account will be automatically created if they don't have one yet.
1. One question to answer, shall we allow users skip this post signup flow or it should be mandatory
   1. If mandatory, then we will need to persist the state of the post signup flow, and if they leave (close page) without finishing steps, on the next visit we should redirect them back to this post signup flow.

**Comment by rrhyne** [comment]
At the minimum, we should persist the state of verified email and if the email isn't verified that should always block the user with the Post-Sign-up flow page. 

Ideally, after the lead form is completed, we would set a `competed-sign-up` or `completed-setup` variable in the user table. This would allow us to support additional user configuration steps in the future.

**Comment by mrnugget** [comment]
@gitstart-sourcegraph I added the backend query/mutation to mark users as having completed sign-up here: https://github.com/sourcegraph/sourcegraph/pull/54676
