### ISSUE TITLE
Browser extension stops working when SAML auth token expires

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#545]
Reported by a customer today.

> I had a few users today that are getting a `401 Unauthorized` when trying to use the chrome extension

```
Error: private mode requires authentication
```

code: https://sourcegraph.com/github.com/sourcegraph/browser-extensions/-/blob/src/shared/backend/graphql.tsx#L90

I suspect the problem is as follows:

For builtin auth and OIDC we use a 90 day rolling auth window so it is extremely unlikely for an active sourcegraph user to become unauthed.

For SAML, the cookie expires every 90 days and we don't actually refresh it until it expires. If the cookie expires or is deleted, the browser extension will stop working. It would be great if we could detect this and (1) automatically refresh the token or (2) just tell the user they need to re-auth and give them a link.

The workaround if this is true if for the user to visit their sourcegraph instance to refresh the auth token.

related
- https://github.com/sourcegraph/enterprise/issues/11748
- https://github.com/sourcegraph/enterprise/issues/10324

**Comment by ijsnow** [comment]
Can the browser extension refresh the token? Shouldn't the back end refresh the token when its being used?

The browser extension now creates access tokens from the options page (which requires a Sourcegraph session) and then uses that token as auth from then on out. The reason we're still seeing 401s from this is because it's currently sending both the access token as a header and the SAML cookie. [This PR](https://github.com/sourcegraph/browser-extensions/pull/288) fixes the 401s by not sending cookies if we have a token. However, if the session has expired, the options page still will get 401s.

**Comment by nicksnyder** [comment]
This is backlog, but I want to cc new browser extension owners for visibility @felixfbecker @lguychard

**Comment by keegancsmith** [comment]
@sourcegraph/web Hey we are going through triaging 3.13 and we realised this is not core-services. Tagging you for visibility.

**Comment by felixfbecker** [comment]
@keegancsmith does that mean this solution in the OP is not possible?

> It would be great if we could detect this and (1) automatically refresh the token

**Comment by keegancsmith** [comment]
> It would be great if we could detect this and (1) automatically refresh the token

I would of suspected refresh is done by the client, not the server. However, I am not that familiar with this tech so my assumption could be far off.

**Comment by felixfbecker** [comment]
I am unfortunately also not familiar with how our SAML support works. Everything in our auth story is handled by the backend afaik - i.e. user signs in, backend sends `Set-Cookie` header, checks cookie on subsequent requests. I am not aware of any code in the webapp do handle any session tokens etc, so I'd assume the same (backend does everything) applies to SAML support. I'd guess @beyang knows more?

**Comment by nicksnyder** [comment]
Here is what I remember:

SAML auth issues a cookie that is not continuously refreshed. I forget if this is a technical limitation or a design limitation. If it were possible to make the SAML cookie get refreshed on each use, that would mitigate this problem for active users (but not mitigate it for users who stop using Sourcegraph for 90 days). I have a vague recollection that the SAML cookie is issued in the domain of the code host (not in the sourcegraph.com) and the auth dance happens on the backend.

Like I mentioned in the original report, I think solution will involve adding some logic to our browser extension TypeScript to (1) detect if a request fails due to auth and (2) redirect the user through sourcegraph.com so that they can get a frash SAML token.  I investigated this for about a day when I first reported it. I tried a few things and was unable to think of a solution (but my knowledge of what is possible on the frontend is stale). I think someone on the web team might have better luck, but really we just need a single person to own this.

**Comment by beyang** [comment]
Echoing what Nick is saying, I think this issue reduces more to session refresh, than SAML auth. Once any auth flow is completed successfully, we issue a session cookie that then authenticates user requests to Sourcegraph. This cookie has a certain expiration (configurable by `auth.sessionExpiry`). Many sites refresh this expiration whenever a request is received. We don't. Therefore, we require users to log in again after the expiry. For GUI, this is typically not an issue, as we automatically redirect to the auth login, which then auto-redirects back to Sourcegraph (if the user is still signed into the SSO provider), so from the end-user's POV, reauthing appears as just a slightly longer page load with redirects. For the browser extension, this is obviously not the case. Thus, what Nick is proposing is refreshing the session cookie expiry whenever the cookie is used. This would prevent browser extension users from having to go through a manual auth flow, so long as they use the browser extension at least once before the session expiration period.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.13 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by felixfbecker** [comment]
We now show Sign In buttons on code views if the user is not signed in.
