### ISSUE TITLE
Can't list branches of torvalds/linux repo on Github

### ISSUE THREAD

**Issue by shadyabhi** [sourcegraph/sourcegraph#5453]
- **Sourcegraph version:** 
- **Platform information:** 

#### Steps to reproduce:

1. Visit: https://sourcegraph.com/github.com/torvalds/linux/-/tags
2. Observe error

#### Expected behavior:
No error, shuold list branches.

#### Actual behavior:
Branches are not searchable and get error `Strconv.ParseInt: parsing "": invalid syntax`. 

![Issue](https://i.imgur.com/fOpg1pg.png)

**Comment by christinaforney** [comment]
This also shows up in the tags tab in the branch/tags/commit drop down from the project root:

![image](https://user-images.githubusercontent.com/1559622/64205902-f59cac00-ce4d-11e9-8797-bc97f1fa5d66.png)

**Comment by s1341** [comment]
Is anyone working on this? Any updates?

**Comment by eseliger** [comment]
I just took a peak into it and it looks like github is also having some trouble with one tag: `v2.6.11-tree`. It has no `creatordate` and also doesn't seem to point to any valid commit. I was not able to replicate such a repo state locally though 🤔 
Handing off to core-services, as I feel stuck here

**Comment by keegancsmith** [comment]
Git repos can have strange states. We need to improve the backend to handle this malformed tag/commit. Kinda funny that a bad git repo lives under the torvalds user :)

**Comment by s1341** [comment]
Any movement on this? It's been open for almost a year...

**Comment by tsenart** [comment]
@flying-robot and I are pairing on this now. The first thing we did to find the relevant code was to use [`and` search to drill down](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+strconv.ParseInt+and+tags&patternType=literal). Worked like a charm @rvantonder! We found our file very quickly: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/vcs/git/refs.go?subtree=true#L249
