### ISSUE TITLE
Tracking issue - release tooling and release process fixes and improvements

### ISSUE THREAD

**Issue by DaedalusG** [sourcegraph/sourcegraph#54626]
### Plan

This issue tracks bugs, improvements, and fixes of the release tool and the release process that are surfaced while working on releases.

### Tracked issues

- https://github.com/sourcegraph/sourcegraph/issues/54623
- https://github.com/sourcegraph/sourcegraph/issues/54624
- https://github.com/sourcegraph/sourcegraph/issues/54625
- https://github.com/sourcegraph/sourcegraph/issues/55048

Surfaced during the release of `v5.1.6`
- https://github.com/sourcegraph/sourcegraph/issues/55783
- https://github.com/sourcegraph/sourcegraph/issues/55784
- https://github.com/sourcegraph/sourcegraph/issues/55785
- https://github.com/sourcegraph/sourcegraph/issues/55786
- https://github.com/sourcegraph/sourcegraph/issues/55787
- https://github.com/sourcegraph/sourcegraph/issues/55790

**Comment by DaedalusG** [comment]
https://github.com/sourcegraph/sourcegraph/issues/55377

**Comment by sanderginn** [comment]
Updated the issue to cover all release related issues

**Comment by DaedalusG** [comment]
Closing since we plan to migrate to a new release tool and the old tool will no longer be maintained
