### ISSUE TITLE
Zoekt section count mismatch log spam

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#5466]
[$CUSTOMER](https://app.hubspot.com/contacts/2762526/company/554338610) is reporting this:

 'zoekt-webserver | 2019/09/01 17:28:59 reloading: /var/opt/sourcegraph/zoekt/index/gerrit%2Fa%2Fxxxxxx_v15.00013.zoekt, err NewSearcher(/var/opt/sourcegraph/zoekt/index/gerrit%2Fa%2Fxxxxxx_v15.00013.zoekt): section count mismatch: got 19 want 23’

This one is not causing any issues but I see lot of these lines whenever we restart the Sourcegraph container.

**Comment by beyang** [comment]
@slimsag @keegancsmith any idea what could be causing this? This is in 3.7. Could it be related to the symbols search perf issue? Am hesitant to ask the customer to downgrade to 3.6, because they are using the built-in Prometheus instance that Uwe added in 3.7. It's fine if they remain on 3.7 so long as the issue is limited to logspam.

**Comment by slimsag** [comment]
Is this on 3.7.0 or 3.7.1? Were they on 3.6.2 prior?

I don't suggest downgrading: https://github.com/sourcegraph/deploy-sourcegraph/blob/master/docs/migrate.md#371-downgrading

In 3.7.x the Zoekt index version changed from v15 to v16, meaning repositories need to be reindexed -- and in v3.7.1 backwards compatibility was added for reading the old v15 format until reindexing has occurred.

cc @kzh

**Comment by beyang** [comment]
> Is this on 3.7.0 or 3.7.1? Were they on 3.6.2 prior?
3.7.0. They were on 3.6.1 before. Should I ask them to upgrade to 3.7.1?

**Comment by slimsag** [comment]
Yep, upgrading is a good idea here.

**Comment by keegancsmith** [comment]
yeah this is fixed in 3.7.1.
