### ISSUE TITLE
v3.7.1 reindexing much slower than v3.7.0

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#5471]
It appears that with the new v15 shard reading support reindexing after upgrading to v3.7 is much slower on the same exact set of repositories. It doesn't appear to be a resource constraint of any sort, and most of the time zoekt-indexserver is sitting idle. I suspect some sort of indexer scheduling issue?

In specific, I am certain with the same set of repositories that:

- upgrading v3.5.2 -> v3.7.0 (zoekt: `014a202`) reindexing completes at a little under 6,000 repos/hr
- upgrading v3.6.2 -> v3.7.1 (zoekt: `4e4eef5`) reindexing completes at just 1433 repos/hr

It's not the end of the world (we can always advise users to just wait longer), but I would like to understand why it is so much slower on the same set of repositories and see if there is a simple solution.

@keegancsmith Any idea how the following changes could cause this? https://github.com/sourcegraph/zoekt/compare/sourcegraph:014a202...sourcegraph:4e4eef5

**Comment by keegancsmith** [comment]
There is nothing in the zoekt versions there that explain the slowdown. My best guess this is some emergent behaviour from changes in sourcegraph-frontend as well.

What exactly was your testing methodology? Are you certain the set of indexed repos was the same between v3.5 and v3.6? Do you have any logs saved from zoekt-indexserver?

My gut tells me there is a reasonable explanation for this which doesn't warrant deep diving. If you have the above information I think we can make a call on this.

**Comment by slimsag** [comment]
> What exactly was your testing methodology?

- Upgrading from 3.5.2 to 3.7.0 I first confirmed all repositories were cloned and indexed (according to the site admin "Needs index" tab). Once confirmed, I upgraded to 3.7.0 and measured how many repositories went away on the "Needs index" tab over a few hours.
- Upgrading from 3.6.2 to 3.7.1 I did the same, confirmed all repositories were cloned and indexed, then upgraded to 3.7.1. Since the reindexing repositories no longer show up on the "needs index" tab anymore after the v15 read support change, I am running the following to figure out how many have been reindexed:

```
$ ls /data/zoekt-shared-disk/ | grep v16 | wc -l
10738
$ ls /data/zoekt-shared-disk/ | grep v15 | wc -l
2532
```

> Are you certain the set of indexed repos was the same between v3.5 and v3.6?

100% positive, no doubt in my mind. They are cloned from a completely locked down and unchanged bitbucket server instance that runs locally on the same host as theoa.sgdev.org. The total repository count shown on Sourcegraph is also the same (12,981).

> Do you have any logs saved from zoekt-indexserver?

The logs don't look interesting, they appeared identical before and after to my eyes so I didn't keep the logs from 3.7.0 but I can re-gather them if helpful.

Since it sounds like there isn't an obvious answer here, I'll gather some more data / evidence tomorrow and update here with what I find.

**Comment by keegancsmith** [comment]
Ok great, that sounds good. Can you use measure the number of repos in the same way between the versions (ie using `wc -l`).

The raw logs are interesting for analysing what is going on. I would look at some specific repos and see how long they took to try and find a pattern.

**Comment by slimsag** [comment]
Cool, will do. Is there a debug var I should use? Or should there be logs
about index times? (I didn't see any)

**Comment by keegancsmith** [comment]
Came across an interesting issue on k8s-dogfood. Tried to visit the debug page for indexserver and received this error:

```
POST http://sourcegraph-frontend-internal/.internal/repos/list giving up after 5 attempts
```

I'm wondering if large amounts of repos is causing zoekt-indexserver in some cases to slowdown due to waiting on frontend.

So interesting data is on the debug port:

```
kubectl port-forward indexed-search-585bf8f74b-hh4f6 6072
# http://localhost:6072/debug/requests
```

Yeah but I couldn't find anything but error logs, so the logs aren't as useful as I hoped :/ Could backport some extra logging?

**Comment by slimsag** [comment]
I tried reproducing this again with v3.7.0 just now and couldn't. I don't know how, but I must have messed up before to get the ~6,000/hr number.

- 6:49 PM MST: Upgrade to v3.7.0 from v3.6.2, immediately showed 12981 repos needing indexing.
- 7:49 PM MST: 1478 of 12981 indexed.

So, no regression here, I just messed up somehow apparently. Apologies!

**Comment by slimsag** [comment]
Just finished testing a reindexing on v3.7.1 of 13k repositories, as well, and confirmed the speed is 1417.75 repos/hr.
