### ISSUE TITLE
downgrading from 3.7.x to 3.6.x should be easier / supported

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#5472]
Quoting my [Slack message](https://sourcegraph.slack.com/archives/CHPC7UX16/p1567152471014700) on this topic:

> If a customer upgrades to v3.7.1, encounters some issues in the product (not necessarily related to search) they effectively cannot downgrade without suffering very bad search perf (unindexed) while we reindex everything back to the old v15 format.

Keegan suggested the following and estimates it would take about a day:

> this is probably why zoekt didn’t delete before :slightly_smiling_face: We should probably make it automatic after 2 version increases. Then we tell admins to manually delete (very easy to do). [...] We already have the `.trash` dir, we could use that. If we include functionality to delete from the trash dir if disk space is low that may help?

I think we should do the above ASAP to make downgrading seamless.

**Comment by slimsag** [comment]
@keegancsmith is this something you could work on? Probably for a 3.7.2 patch just reverting the deletion logic we added would be fine, then in 3.8 we can make zoekt cleanup after itself more

**Comment by keegancsmith** [comment]
Ok, my highest priority for this release is horizontal sharding. I've had lots of delays, and its getting a bit close. So I can take on this work, but likely only on Monday. I'm at a conference now, so will see if I can prototype it before I talk :P

**Comment by keegancsmith** [comment]
@kzh is gonna take this. What are you thinking of implementing more specifically @kzh?

**Comment by kzh** [comment]
I had something minor in mind.

1) Instead of calling `os.Remove`,  we instead move the older shards to `.trash`. Before someone downgrades, they run a small script:
```
rm *_v16*.zoekt
mv .trash/*_v15.*.zoekt .
```
Would this be reasonable since downgrading isn't a typical occurrence? With this approach, there is  an increase of ~130% necessary disk space to accommodate both v15 and v16 indexes.

2) Another thought: should downgrading really be supported in the zoekt codebase? Would it be better to advise customers to be cautious and manually backup their v15 indexes before upgrading on the off chance that they would like to downgrade?
```
# before upgrading
tar -czf v15_backup.tar.gz *_v15.*.zoekt

# before downgrading
rm v16_backup.tar.gz
tar -xzf v15_backup.tar.gz
```

Zoekt doesn't normally support upgrading/downgrading index format versions so without small scripts, we would probably have to also create a patch release for 3.6 to support downgrading from 3.7 in addition to the 3.7.2 patch release.

**Comment by slimsag** [comment]
I think having to run a script on downgrade makes it more tedious and error prone, so I'd like to avoid that if possible.

Here is what I would like / think makes sense and should be easy to implement I think:

- At any given time, we keep the latest version and prior version of indexes on disk.
- You can always downgrade, with no manual intervention, but you need enough space to store both indexes (we will advise admins to ensure enough space is available before upgrading).

Examples:

- When we reindex and go from v1 -> v2 indexes, we keep both indexes on disk in the same location. If you downgrade back to an old Sourcegraph version, you don't need to do anything and we just continue reading the v1 indexes on disk.
- When we reindex and go from v2 -> v3, we delete the v1 indexes from disk all at once. i.e., we only keep v2 and v3 now.

From an implementation standpoint, this should mean we only have to:

1) Support reading the current zoekt index version and the prior zoekt index version (we already do for v15 and v16, so this is sufficient and we don't need to backport any changes to older Sourcegraph versions).
2) Ensure on upgrade from 3.6 -> 3.7.2 that we keep the v15 indexes around on disk in same location.
3) Ensure if we downgrade from 3.7.2 -> 3.6 that we use the v15 indexes on disk still (this should already be the case, so nothing to do here).

How does this sound?

**Comment by kzh** [comment]
This is implemented in https://github.com/sourcegraph/zoekt/commit/7e1236499d942785f0535f8feabe1093b8fb9ce9.

**Comment by keegancsmith** [comment]
So we need to:

- [ ] Document the behaviour
- [ ] Build new zoekt images
- [ ] Update deploy-sourcegraph to use the new images. Cherry-pick into 3.7 branch? cc @slimsag 
- [ ] Update sourcegraph/sourcegraph to latest zoekt in go.mod
- [ ] Update CHANGELOG
- [ ] cherry-pick into 3.7 patch branch

Can you do the above and close this task out once you have done that? I am guessing the tagging and releasing of 3.7.2 will be handled by @slimsag.

**Comment by slimsag** [comment]
> Document the behaviour

https://github.com/sourcegraph/sourcegraph/pull/5596 covers this now.

**Comment by slimsag** [comment]
> Update deploy-sourcegraph to use the new images. Cherry-pick into 3.7 branch? cc @slimsag

Done via https://github.com/sourcegraph/deploy-sourcegraph/pull/374 and brought onto 3.7 branch via https://github.com/sourcegraph/deploy-sourcegraph/commit/c63ddb9911be266f67f7f1ae5285f872874390a1

**Comment by slimsag** [comment]
> Update sourcegraph/sourcegraph to latest zoekt in go.mod

https://github.com/sourcegraph/sourcegraph/pull/5597

**Comment by slimsag** [comment]
Done remaining bits in https://github.com/sourcegraph/sourcegraph/pull/5600

Cutting patch release in https://github.com/sourcegraph/sourcegraph/issues/5598
