### ISSUE TITLE
Create testplan for Bitbucket Server

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#54749]

**Comment by kopancek** [comment]
The test plan was created here: https://docs.google.com/document/d/16PHT7JIsLpIWm4mGq8FVMQ3oyjR-rUoHWZCCTvYC3B4

I am leaving the ticket as in-review in case anyone adds comments today or tomorrow.

**Comment by mrnugget** [comment]
Add here: https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/doc/dev/index.md#testing-1
