### ISSUE TITLE
Add selected filter row below search bar

### ISSUE THREAD

**Issue by christinaforney** [sourcegraph/sourcegraph#5476]
See [RFC 13: Selected filter row](https://docs.google.com/document/d/1qqSdaqx8DZJkBjZjviG4xOOxiJKic69yEAwCFOLx8eg/edit#)

#4819 is a prototype PR that creates the selected filter row, but doesn't have dismissible chips.

**Comment by tsenart** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.9 release is scheduled for tomorrow** at 10:00 CEST.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by tsenart** [comment]
Moved this to Backlog since it doesn't look like it got done. Please update this issue accordingly otherwise.

**Comment by nicksnyder** [comment]
This is superseded by RFC 15
