### ISSUE TITLE
Cody Gateway: Investigate more performant JSON library

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#54766]
We do JSON unmarshaling and marshaling at the request-level, which is one of the main operations that performed. It causes the memory usage to stack up during peak times.

We should look into more [performant alternatives](https://github.com/goccy/go-json#json-library-comparison) than the `encoding/json` at some point. Even though those alternatives do not directly decrease the memory usage, the less time we spend on working with JSON, the memory footprint stacks up slower, which would allow us to serve more requests in the same period of timeframe.

Context: https://sourcegraph.slack.com/archives/C05497E9MDW/p1688516323485019

/cc @unknwon @eseliger @bobheadxi

**Comment by eseliger** [comment]
😬 https://github.com/orgs/sourcegraph/projects/343?pane=issue&itemId=32866580 but this one is better so let's keep this!

**Comment by unknwon** [comment]
It's no harm to have more attention on the topic 😂
