### ISSUE TITLE
Merge navigation bar and search bar into one component

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#54794]
At the moment our navigation and search bar are separate component visually, it's good because usually you can see the most recent query as you navigate to the repository files (because we populate query according to you viewed files) but at the same time it's problematic because it takes an additional space from actual content of the file/blob UI where we already have a lot of sticky elements. 

A main Idea of this issue is to try to merge these two elements into one (you can find a design [here](https://www.figma.com/file/ZrIRl5OchqCrj8d0kghLyV/Yet-another-search-design?type=design&node-id=18-2227&mode=design&t=p14UngcTUeelq9dR-0))

![Image](https://github.com/sourcegraph/sourcegraph/assets/18492575/8bf0592d-5032-4d8f-9ef7-0129a4a615b9)

This would give us more space for the content on the blob page and also gives more straightforward way to jump to the search page from pages like batch changes, code insights, monitoring, etc (basically any other page in the product)

**Comment by toolmantim** [comment]
Nice! I did some [related design work](https://www.figma.com/file/QqXxwyBs0hUyNXivbfBfbh/Cody-Search?type=design&node-id=0-1&mode=design) a while back:

<img width="1190" alt="Cody Search" src="https://github.com/sourcegraph/sourcegraph/assets/153/0b9580c3-97d5-4663-86be-43e9609d50f8">
