### ISSUE TITLE
Investigate multiple license info on customer instance

### ISSUE THREAD

**Issue by BolajiOlajide** [sourcegraph/sourcegraph#54813]
Customer is seeing a licensing issue when they upgrade their test environment to 5.1.2. Their license is marked as valid in site admin, but they are seeing a banner on the frontend saying their license is expired and certain features (e.g., Github Oauth) are not working for their instance.

[Slack Thread](https://sourcegraph.slack.com/archives/C02NFUV7V9A/p1688644698422069)

**Comment by akshay-grabtaxi** [comment]
We as another customer faced the same issue which got fixed after we got new keys from the Sourcegraph.

**Comment by BolajiOlajide** [comment]
## Investigation Result

This isn't a **bug**. 
As part of 5.1, changes were made to the license validation code, and when we detect that a license is being used on more than one Sourcegraph instance, the second instance will treat the license as invalid.
