### ISSUE TITLE
Cmd-F should highlight the search text in the search box if I press Cmd-F while focusing the search box

### ISSUE THREAD

**Issue by mitchellh** [sourcegraph/sourcegraph#54810]
#### Feature request description

Sourcegraph search is great, but there is often a long gap between when I search, browse around, and search again on the same page. If I hit "Cmd-F" again, it should rehighlight the search query. Most search shortcuts work this way. For example: Chrome's Cmd-F highlights, and so does its Cmd-L (address bar).

Sourcegraph _does highlight **if I'm not focused on the search box**_ but I'm requesting Cmd-F to always rehighlight even I'm already focused on the search box.

#### Is your feature request related to a problem? If so, please describe.

Without this, I'm frequently appending instead of replacing.

I'd like to search multiple times and save some keystrokes and behave idiomatically.

![CleanShot 2023-07-11 at 18 36 19@2x](https://github.com/sourcegraph/sourcegraph/assets/1299/ced8e13f-80ba-479f-870f-3163493d10e4)

**Comment by mrnugget** [comment]
Thanks! To be clear: with "highlight" you mean "select", right? (I'm 99% sure that's what you mean)

**Comment by mitchellh** [comment]
Yeah 😄
