### ISSUE TITLE
Port to Bazel: install universal-ctags binary (//dev/tools:ctags)

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#54832]

**Comment by jhchabran** [comment]
@davejrt's note:

- Noah figured out how to build it 
- Created a gcp bucket, working on automating it, I don't want this to break when it runs every quarter.

**Comment by jhchabran** [comment]
were struggling with code signing, fixed it by using `sudo` lol.

**Comment by davejrt** [comment]
Closed by https://github.com/sourcegraph/sourcegraph/pull/55944
