### ISSUE TITLE
Browser extension should default back to sourcegraph.com when URL field is emptied 

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#5483]
Otherwise, a "configure Sourcegraph" button is shown:

https://sourcegraph.slack.com/archives/CMT39K56Z/p1567618306001900

**Comment by felixfbecker** [comment]
The behavior here is fixed in that the field is invalid and will not be persisted if it's empty. I.e. the URL will stay what it was before when the menu is closed. There was a separate issue for restoring the default URL, so closing this one.
