### ISSUE TITLE
Okta connection is not working on Account security page

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#54928]
Steps to reproduce:
1. Go to https://sourcegraph.sourcegraph.com/user/settings/security
2. Next to "Okta", click the green "Add" button
3. Auth with Okta if needed
4. Get "Unexpected error associating the external account with your Sourcegraph user. The most likely cause for this problem is that another Sourcegraph user is already linked with this external account. A site admin or the other user can unlink the account to fix this problem."

Same in a [8-sec Loom](https://www.loom.com/share/e39382ae967540448c8b8f2d639477cf?sid=fb074e46-fd51-416d-ac4b-6c3c001b0cfe)
In other cases, we get redirected back to the same page, but unauthed: [15-sec vid](https://github.com/sourcegraph/sourcegraph/assets/2552265/af3dbdd9-9dda-4b96-a1ad-6167720ecc70)

Expectation: auth correctly with Okta and get back to the page. If already authenticated, show the red "Remove" button rather than the green "Add" button.

/cc @sourcegraph/source

**Comment by BolajiOlajide** [comment]
I reached out to David. I have a hunch one of these accounts is already associated with your Okta account.

<img width="910" alt="CleanShot 2023-07-17 at 16 53 26@2x" src="https://github.com/sourcegraph/sourcegraph/assets/25608335/2728f264-2604-4da0-9488-ceff7b206372">

**Comment by BolajiOlajide** [comment]
Closing this for now until it happens again (if it does).

For the case above, the error occur

**Comment by BolajiOlajide** [comment]
I'm unable to reproduce this. I'll be closing it for now.
