### ISSUE TITLE
[Research] RFC 801 - Simple Search

### ISSUE THREAD

**Issue by meglynst** [sourcegraph/sourcegraph#54932]
Target start: July 19

Background: [RFC 801 - Simple Search](https://docs.google.com/document/d/1Qe7buwMxYPag9dOfHT5E42V1fuB12WuXI--oC-2BcYM/edit)

Designer: @coury-clark 

Prototype:
https://sourcegraph.sourcegraph.com/search
[log in credentials](https://docs.google.com/document/d/1RdP5cQua3RwpCU04YdkV-_KKNMvHUKY34vQzkccPVs0/edit?usp=sharing)

Question to answer:

Test Plan(s):

Research Report:

**Comment by rrhyne** [comment]
Let's backlog this or have Paulo test it.
