### ISSUE TITLE
JetBrains: Ensure we respect site.isCodyEnabled 

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#54934]
Info:
- https://github.com/sourcegraph/sourcegraph/pull/52941 added a new GraphQL field that determines if Cody is enabled on the instance.
- Our clients should check this flag and render a nice message if not.
- VS Code solved it in https://github.com/sourcegraph/sourcegraph/pull/52739
- Once this is done, check the box on https://github.com/sourcegraph/cody/issues/156

Suggested steps to take:
- [ ] Get the `isCodyEnabled` setting from the server when loading the plugin
- [ ] Also get it when switching servers in the settings.
- [ ] If Cody is enabled in the plugin but not in the server, disable Cody features and notify the user that this happened.
- [ ] Test what happens if `isCodyEnabled == false` on the server and we try to make a Cody request. Are we getting back a response that makes it clear that the server is accessible and our token is valid but Cody is disabled? If yes, then fail the request gracefully, disable Cody, and and show the "Cody is disabled on the server" notification.
- If Cody _was_ disabled and they enabled it on the server, then the user will need to reopen the project or do a setting change (such as an "Enable Cody" action) to trigger an update. We could use a periodic background polling process here or introduce a button somewhere, but I think this is good enough.

**Comment by vdavid** [comment]
Also: Think about how to refresh settings from the servers periodically, or give the user a force update button to update server settings

**Comment by olafurpg** [comment]
Closing this as fixed. We didn't spend much time confirming 100% that it is fixed, but we can revisit if there are missing holes.
