### ISSUE TITLE
Remove statusIndicator feature flag

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#5493]
It looks like this feature flag has been enabled by default for 2 months. Can we remove it?

```
"statusIndicator": {
          "description": "Enables the external service status indicator in the navigation bar.",
          "type": "string",
          "enum": ["enabled", "disabled"],
          "default": "enabled"
        }
```
https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/schema/site.schema.json?utm_source=VSCode-1.0.14#L58:10

**Comment by mrnugget** [comment]
Yes, I'll do it. Before I'll try to find a diff: is there a canonical way to do it? I suspect we don't want to invalidate a customer's config possibly by removing a config setting from our schema.

**Comment by nicksnyder** [comment]
I don’t think there is a better way other than to delete it.
