### ISSUE TITLE
How to setup sourcegraph in vscode to jump to local definitions as that in github1s ?

### ISSUE THREAD

**Issue by Cc-Hy** [sourcegraph/sourcegraph#54948]
Hi, I'd like to ask how to set up sourcegraph in vscode to jump to local definitions.
When using the github1s website to explore github repos, I find sourcegraph really useful and it can automatically find local definitions in config files with strings:
![image](https://github.com/sourcegraph/sourcegraph/assets/82150240/c57de185-b51a-4b61-af72-fb25d5e85dc7)
And I can directly jump to definitions with ctrl + click.
![image](https://github.com/sourcegraph/sourcegraph/assets/82150240/a57c969f-3412-4972-b615-d2bb2d865e3a)
So how could I set it up in vscode to achieve this function? Thanks a lot.

**Comment by jdorfman** [comment]
Duplicate: https://github.com/sourcegraph/sourcegraph/discussions/34821#discussioncomment-6754937
