### ISSUE TITLE
Ability to filter out archived Bitbucket Server repositories

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#5494]
Bitbucket Server doesn't have a way to archive repositories natively, so it relies solely on social constructs to denote repositories as archived currently (e.g., saying "don't use this" in the README).

This also means in Sourcegraph there is no way to filter out archived repositories using the `archive:` search filter -- because Bitbucket can't tell us which repositories _are_ archived.

I propose we detect Bitbucket Server archived repositories by looking for the label on repositories named `archived` (this is non-standard, but is one obvious way to support this):

![image](https://user-images.githubusercontent.com/3173176/64462933-0439cc00-d0b7-11e9-92b5-4034a1e4a18b.png)

Requested by a user at https://app.hubspot.com/contacts/2762526/company/407948923

**Comment by zsimic** [comment]
Do you have an ETA on when this will be available?

**Comment by tsenart** [comment]
@zsimic: We added  this to our 3.12 tracking issue so, tentatively, we could have this shipped in the 3.12 release.

**Comment by keegancsmith** [comment]
I took a quick look into the bitbucket rest API. Unfortunately this information is not returned from the repository listing endpoint, instead it would require us to issue an extra http request per repo. This would be an unacceptable performance trade-off. 

Alternatively there is the `labeled` endpoint. This endpoint will return all repos with a specific label. This seems performant enough that it is a viable approach. https://docs.atlassian.com/bitbucket-server/rest/5.16.0/bitbucket-rest.html#idm8296858944

**Comment by keegancsmith** [comment]
Tested on our dogfooding instance, seems to work

```shellsession
$ curl -s -n 'https://bitbucket.sgdev.org/rest/api/1.0/labels/archived/labeled?REPOSITORY' | jq -r '.values[] | .links.self[0].href'
https://bitbucket.sgdev.org/projects/PUBLIC/repos/archived-repo/browse
$ curl -s -n 'https://bitbucket.sgdev.org/rest/api/1.0/projects/PUBLIC/repos/archived-repo' | jq -r .
{
  "slug": "archived-repo",
  "id": 10073,
  "name": "archived-repo",
  "scmId": "git",
  "state": "AVAILABLE",
  "statusMessage": "Available",
  "forkable": true,
  "project": {
    "key": "PUBLIC",
    "id": 4,
    "name": "Public",
    "public": false,
    "type": "NORMAL",
    "links": {
      "self": [
        {
          "href": "https://bitbucket.sgdev.org/projects/PUBLIC"
        }
      ]
    }
  },
  "public": false,
  "links": {
    "clone": [
      {
        "href": "https://bitbucket.sgdev.org/scm/public/archived-repo.git",
        "name": "http"
      }
    ],
    "self": [
      {
        "href": "https://bitbucket.sgdev.org/projects/PUBLIC/repos/archived-repo/browse"
      }
    ]
  }
}
$ curl -s -n 'https://bitbucket.sgdev.org/rest/api/1.0/labels/notfoundlabel/labeled?REPOSITORY' | jq .
{
  "errors": [
    {
      "context": null,
      "message": "Label not found.",
      "exceptionName": "com.atlassian.bitbucket.label.NoSuchLabelException"
    }
  ]
}
```

One thing to note is the permission required on the labelled endpoint is
> The authenticated user must have REPO_ADMIN permission for the specified repository.

This is a bit weird to be honest. I believe all the other endpoints we do for listing just require `REPO_READ` or just `read`. So if we natively integrate this in we probably need to test what happens for non admins listing, and gracefully handle that.

**Comment by keegancsmith** [comment]
Ok I just tested on our bitbucket instance, and it returned the repository even though the user I was testing with was just a normal user.

**Comment by zsimic** [comment]
Awesome! Yes, the `/rest/api/1.0/labels/archived/labeled` endpoint is what I used too (for another thing), works very nicely indeed and allows to get all repos with that label (paged query, so several requests may be needed, depending on repo count)

**Comment by keegancsmith** [comment]
@zsimic thanks, this should happen. Already have a WIP PR implementing this :) https://github.com/sourcegraph/sourcegraph/pull/7284
