### ISSUE TITLE
[ci] re-enable athens proxy 

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#5495]
In https://github.com/sourcegraph/infrastructure/pull/1633, I had to disable the athens proxy due to some build failures that we were getting after https://github.com/sourcegraph/infrastructure/pull/1629 was merged. 

Does it seem like https://github.com/gomods/athens/issues/1372 is related?

cc @sourcegraph/core-services since y'all will probably have the most context.

**Comment by keegancsmith** [comment]
I don't know if it is related? Do you have links to the build failures?

**Comment by tsenart** [comment]
This isn't going to make in 3.8 (and it doesn't matter much, since it's infra work on our side). Backlogging.

**Comment by keegancsmith** [comment]
Looks like this was done by @ggilmore in 364c3b03601f71c9c6f8f7ef0e32c8893239f80d. I see there was a new release of athens we deployed, which I assume fixed the issue.
