### ISSUE TITLE
Initial setup experience doesn't work great with self-hosted code hosts

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#54970]
The new setup experience is a great entrypoint into configuring Sourcegraph, but it currently hides enterprise GitHub and GitLab behind a JSON editor, making me think on first impression that these aren't supported. We should allow to point to a custom URL from the fancy UI as well.

<img width="944" alt="Screenshot 2023-07-14 at 20 05 14@2x" src="https://github.com/sourcegraph/sourcegraph/assets/19534377/2820a207-c704-490e-9559-8e6da3c4d10c">
<img width="927" alt="Screenshot 2023-07-14 at 20 05 25@2x" src="https://github.com/sourcegraph/sourcegraph/assets/19534377/68171ad3-2ce0-4e3b-a44e-471a45abb6f2">

/cc @sourcegraph/source

**Comment by mrnugget** [comment]
As discussed in planning: let's figure out how hard it is to fix some of these issues (the one in this ticket and in the other tickets) and whether it's worth it to disable whole wizard in patch release or whether it's fixable.

**Comment by mrnugget** [comment]
cc @cesrjimenez
