### ISSUE TITLE
Add better way for testing email setup

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#54985]
In our docs, we recommend people to run a GQL mutation, and to parse it's string output for "error or not error" (it doesn't even GQL error out). https://docs.sourcegraph.com/admin/config/email#sending-a-test-email

This is not a great experience, and this should be surfaced better somehow. Ideally, mail setup would be one step of the setup wizard, where it is tested right away. 

/cc @sourcegraph/source

**Comment by mrnugget** [comment]
@cesrjimenez fixed this!
