### ISSUE TITLE
Poor default for email.senderName

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#54984]
The default seems to be an empty string, not `Sourcegraph` like the JSON schema suggests, which renders emails not very pretty. Also, this option is nowhere mentioned under https://docs.sourcegraph.com/admin/config/email.

Not exactly source, but setup experience related, so assigning to us for now. 

/cc @sourcegraph/source

**Comment by mrnugget** [comment]
Tasks:

* Set default value to `Sourcegraph`
* Update docs page to document `email.senderName`
