### ISSUE TITLE
Add external URL configuration to initial setup experience

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#54983]
Sourcegraph instances require the external URL to be configured correctly, but the initial setup experience doesn't ask for it and once repos are synced, you just land at the search page, there's good potential for people missing this configuration. Also, the default value of http://example.com doesn't feel great. 

![Screenshot 2023-07-15 at 00 17 02@2x](https://github.com/sourcegraph/sourcegraph/assets/19534377/96833789-ba6a-4e41-80c2-3072a494bd1b)

/cc @sourcegraph/source

**Comment by eseliger** [comment]
https://www.loom.com/share/8d0b9fa3907644949120a6f69692c925 idea for this

**Comment by mrnugget** [comment]
That looks nice. One issue I have with asking external URL too early: based on my experience of setting up server software it's not always clear at the start where the instance will live. So a good default that _works_ (i.e. IP + port that can be accessed) is a hard requirement, IMHO.

**Comment by eseliger** [comment]
I see, that's a good point! The problem with not having any reachable URL is that we'll not be able to do proper auth redirects, send emails with working links and such until then, so it's relatively important. 
Changing the ExternalURL again later should not be a problem, maybe we can make clear that a temporary URL will be okay, but needs to adjusted later(?).
Sounds like more research needs to go into this 😬 Maybe we can also spend some time looking at other on-prem initial setups.
