### ISSUE TITLE
Cleanup add code host connection page

### ISSUE THREAD

**Issue by indradhanush** [sourcegraph/sourcegraph#55010]
### Proposal:
- **Please refer to:**
  - [Discussion thread.](https://sourcegraph.slack.com/archives/C03K05FCRFH/p1689860434928139?thread_ts=1689349756.331779&cid=C03K05FCRFH)
  - This [Figma board.](https://www.figma.com/file/tJ9LAWTljukeunwBZLKDbE/Cleanup-add-code-host-connection-page?type=design&node-id=0%3A1&mode=design&t=j7wbtNoGIUvyqPMq-1)
  
<img width="765" alt="Screenshot 2023-07-20 at 10 40 44 AM" src="https://github.com/sourcegraph/sourcegraph/assets/64257673/fe71a143-92e8-4b5c-a5c2-831c1dc39e0d">

### Old UI:

![image](https://github.com/sourcegraph/sourcegraph/assets/2682729/966dabb4-ff3b-4662-9e16-500806e57827)

We should make this list manageable by grouping top-level elements. So something like:

* GitHub
    - [Github.com](http://github.com/)
    - Github App
    - GitHub PAT
* GitLab
    - ...
* Bitbucket
    - ...

/cc @sourcegraph/source

**Comment by mrnugget** [comment]
I like this!
