### ISSUE TITLE
Return job IDs from scheduleRepositoriesForEmbedding

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#55040]

**Comment by marcleblanc2** [comment]
Can we please also add an input for `id` from `repoEmbeddingJobs.nodes.id` as an optional argument for the `repoEmbeddingJobs` query?

This way we can run the `scheduleRepositoriesForEmbedding` mutation, get the job id as an output, then use the job id as an input to check the status on the job. 

![Image](https://github.com/sourcegraph/sourcegraph/assets/7050295/d5268e8e-70df-442e-8922-11027d06221f)


![Image](https://github.com/sourcegraph/sourcegraph/assets/7050295/5764645e-8051-4ce8-9202-1c248020b242)

**Comment by marcleblanc2** [comment]
Bonus points, under the stats, would be to show the summed up size of the files embedded, and a size of the embeddings returned, so we can factor these in to performance evaluation calculations.

**Comment by jtibshirani** [comment]
Closing this out, as we're not investing in embeddings at the moment.
