### ISSUE TITLE
git debuggability: get design approval

### ISSUE THREAD

**Issue by sashaostrikov** [sourcegraph/sourcegraph#55061]
Get a mocked-out UI working locally to present it to @almeidapaulooliveira and get an approval eventually.

/cc @sourcegraph/source

**Comment by BolajiOlajide** [comment]
Initial LoFi mock by @almeidapaulooliveira 

![image](https://github.com/sourcegraph/sourcegraph/assets/25608335/e9f3bd2e-5583-4b12-8399-f8833398bcd9)

**Comment by BolajiOlajide** [comment]
![Image](https://github.com/sourcegraph/sourcegraph/assets/25608335/c99f3c31-7df5-4b8c-a736-44f1cd45ee78)
