### ISSUE TITLE
JetBrains: Accept server URLs without a schema

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#55104]
The URL input registers as invalid without a schema ("http://" or "https://"). It's only considered valid after putting "https://" to the front.
Many users are used to typing URLs in browsers without the schema. It'd be a better UX if we accepted it as well.

![image](https://github.com/sourcegraph/sourcegraph/assets/2552265/e0ffd2df-a572-43c1-9502-822f126c6ec7)

Suggestion for solution: Accept URLs without a schema, and assume **https**.

Needs design input on how to display this to the user.

**Comment by olafurpg** [comment]
Fixed by new account management.
