### ISSUE TITLE
JetBrains: Possible to add context to forked repositories

### ISSUE THREAD

**Issue by koppor** [sourcegraph/sourcegraph#55183]
As open source developer, I want to improve code. That code may reside in repositories, which I do not have write access to. Therefore, I fork that repository and work on the fork. The upstream repository might have more than 5k stars, but my fork has not. Thus, I cannot use Cody with (full) context, because Cody has no knowledge about the fork. -  Would it be possible that Cody / JetBrains plugin looked up context of the upstream repository in case of a fork?

Example: I have forked https://github.com/openjdk/jdk (16k stars) to https://github.com/jabref/jdk (1 star). While working on the fork, I would love to have the additional information of the upstream repository.

**Comment by olafurpg** [comment]
Thank you for reporting! I am sorry for the late reply.

In the latest 3.1 release, it's now possible to specify what repository to use for the context.


![Image](https://github.com/sourcegraph/sourcegraph/assets/1408093/97d9b234-134a-4a85-98d3-302f5c0062e7)


Note that the OpenJDK repo doesn't have embeddings enabled so it won't solve your specific problem.

![Image](https://github.com/sourcegraph/sourcegraph/assets/1408093/4fd4f8b1-c350-489d-99be-f872e478396e)

Closing as fixed.

**Comment by koppor** [comment]
> Thank you for reporting! I am sorry for the late reply.

I thank you for the follow-up!

> In the latest 3.1 release, it's now possible to specify what repository to use for the context.

Nice!

> Note that the OpenJDK repo doesn't have embeddings enabled so it won't solve your specific problem.

Oh well. Maybe item number 1387 should be removed from the list https://docs.sourcegraph.com/cody/embedded-repos

![image](https://github.com/sourcegraph/sourcegraph/assets/1366654/8ccb3135-b9bc-41f3-a498-049a70dc2b9e)

And the explanation on top of the page be updated why the OpenJDK repo has been excluded.

Maybe, there was a general decision not to index repositories any more, then please update that page, too.

**Comment by olafurpg** [comment]
@koppor My bad, openjdk/jdk actually has embeddings available on sourcegraph.com. I was using an internal account to a private instance that doesn't even have the openjdk repository. I have an open issue about having a separate icon between "repo exists, embeddings missing" and "repo doesn't exist"
