### ISSUE TITLE
Update resource estimator to include embeddings

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#55206]
We need to update the [resource estimator](https://docs.sourcegraph.com/admin/deploy/resource_estimator) (code [here](https://github.com/sourcegraph/resource-estimator/tree/master)) to include the new embeddings service.

**Comment by marcleblanc2** [comment]
[Slack thread](https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1689967364452049?thread_ts=1689962489.989259&cid=C04MSD3DP5L) with context:

This is information that TS teams need when implementing, configuring, and troubleshooting embeddings. From our conversations in the past, I remember that the embeddings container needs 1.5x the repo size (checked out working copy at HEAD rev, not the repo size shown in the Repositories list, as that's the bare clone size) summed up across all repos they hope to keep embeddings in memory, and the blobstore needs 6x the size for storage allocation, but this information that lives better in the resource estimator than in our heads.

**Comment by jtibshirani** [comment]
Closing this out, as we're not investing in embeddings at the moment.
