### ISSUE TITLE
gitserver: Ensure SyncRepoState can cleanly exit

### ISSUE THREAD

**Issue by indradhanush** [sourcegraph/sourcegraph#55215]
Currently `SyncRepoState` is invoked as a goroutine [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@6732a5fe357e77fd52854e8b44738c6557243f4b/-/blob/cmd/gitserver/shared/shared.go?L242) but we do not pass the context, which means we cannot cleanly exit from this goroutine. 

We should:

1. Pass the context to the goroutine
2. Select on `ctx.Done` for a clean exit

Spotted while working on #54663.

**Comment by eseliger** [comment]
This has been fixed when we moved this routine to be a monitored go background routine!
