### ISSUE TITLE
Precise context: Add SCIP name accordion to VSCode extension

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#55224]
The Cody VSCode extension currently shows filenames fetched from embeddings as user-facing diagnostics. We need to add SCIP names as well, as they do not correspond 1-1 with document context fetching and would like to display this in a separate way.

This will be necessary before making the extension available for internal use so we can quickly answer the questions of whether or not the context is being engaged correctly from just the user's view.

**Comment by Numbers88s** [comment]
Closed by work done in the following commit https://github.com/sourcegraph/cody/pull/78/commits/960d2d827df7ebbee2f2267662f4a680365f1ad6
