### ISSUE TITLE
Precise context: Prefer to use SCIP names from document directly

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#55221]
We can fetch names directly from a SCIP document instead of using treesitter output (this effectively removes Phases 1 & 2 in the current context service implementation with something similar to the codenav _ranges_ request).

We should do something like this instead of the heuristic Syntect <> SCIP translation when the request indicates that no local changes have been made since the indexed commit. For Cody Web, this will generally be the case, so we should front-load this effort. This is currently blocking #55220.

**Comment by efritz** [comment]
Tips from sync call:

- Need to add line/col selection in graphql API
- Guard current behavior of phase 1 and 2 with a package-level `const enableSyntect = false` that we can toggle in dev, and have the `true` branch do the new behavior of calling the SCIP index. This condition will be enhanced later, but we'll control it manually for now as the Web client can make this assumption.
- In codenav service/lsifstore, clone and modify `Stencil` and do something similar, but return SCIP names instead of occurrence ranges. This can be called in place of phase 1 and 2 above.

**Comment by Numbers88s** [comment]
Closed by work up to this commit https://github.com/sourcegraph/sourcegraph/pull/51690/commits/8c7537edd2853c72e327cd753cc6cde49b5d028c
