### ISSUE TITLE
Precise context: Remove symbols in document outside of selection

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#55227]
In one way to combat over-fetching, we'll want to prefer the symbol names directly available from the user selection (if it exists). We should throw out symbol names that come back from syntect outside of this range.

**Comment by Numbers88s** [comment]
Closed by work up this commit https://github.com/sourcegraph/sourcegraph/pull/51690/commits/8c7537edd2853c72e327cd753cc6cde49b5d028c
