### ISSUE TITLE
Precise context: Integrate initially with Cody Web

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#55220]
Add precise context, when available, to Cody web. We will use this for more immediate internal testing on the demo instance set up in #55219.

This should be done after #55221.

**Comment by Numbers88s** [comment]
Closed by the work up to this commit https://github.com/sourcegraph/sourcegraph/pull/51690/commits/8c7537edd2853c72e327cd753cc6cde49b5d028c

**Comment by Numbers88s** [comment]
Closed by worked done up to this commit 0a49d6b00c6fe7d379273f71459dc1c5be9bc1c0
