### ISSUE TITLE
Enable alerting for gitserver diskspace issues

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#5523]
Should we add on-call alerts for gitserver diskspace issues? We ran into an ops issue that revealed gitserver's disk usage is sitting at 90%. 

See thread here: https://sourcegraph.slack.com/archives/CHPC7UX16/p1568075963065700

**Comment by attfarhan** [comment]
@chrismwendt @keegancsmith I think I remember you two working on gitserver such that it would auto-delete repositories when it hits 90%, to ensure that we don't actually get alerted for gitserver disk space being full. If so, then gitserver being at 90% is by design and we can just close this issue.

**Comment by attfarhan** [comment]
And it means that it is unlikely gitserver using this much disk space was related to the kubernetes repo loading slowly.

**Comment by chrismwendt** [comment]
Hmm, I don't recall modifying gitserver, but it definitely auto-deletes repos when you're low on disk (I've seen it do this on my mac).

**Comment by keegancsmith** [comment]
Thanks, I'll take a quick look into the underlying issue here. We should have general alerts for all diskspace issues, but the original thread surprised me a bit. Maybe there is something we can tweak in the disk cleaning logic.

**Comment by tsenart** [comment]
@uwedeportivo: Is this something you have already done or something that you think fits well within your upcoming work? If so, please re-assign / re-label.

**Comment by tsenart** [comment]
@sourcegraph/distribution: Is this something you already did / own?

**Comment by slimsag** [comment]
We have a tracking issue for this and will definitely own. It's linked in our tracking issue, can't link right now but you should be able to find it there easily

**Comment by uwedeportivo** [comment]
so to be exact: this specific issue is for sourcegraph.com and our consumption i assume.

we have:
sourcegraph/deploy-sourcegraph-dot-com/base/prometheus/prometheus.ConfigMap.yaml#L294:30

there's a bunch of disk related alerts there.

if you check the prod prometheus status/alerts page they are active and observing:

<img width="460" alt="prom_alerts" src="https://user-images.githubusercontent.com/534011/72390178-ecb2c580-36de-11ea-9a2a-a1b5e066c50a.png">

we have tracking issues about enabling uniform alerts across all our deployments and with the new prometheus model @slimsag introduced it's within reach.

not sure if i should close this one or let it be until all deployments are covered but sourcegraph.com has alert coverage

**Comment by beyang** [comment]
@slimsag re-open if this is still an issue.

**Comment by slimsag** [comment]
Superseded by https://github.com/sourcegraph/sourcegraph/issues/9357
