### ISSUE TITLE
Metrics triage tracking issue

### ISSUE THREAD

**Issue by uwedeportivo** [sourcegraph/sourcegraph#5531]
We plan to include a prometheus/grafana pair with each installation of Sourcegraph. We already have a shared set of metrics getting collected (see `docker-images/prometheus/config`) and for each deploy context we have deploy-specific metrics that can be added to the set (see for example repo:deploy-sourcegraph/base/prometheus/prometheus.ConfigMap.yaml for the k8s deploy case).

This issue is a place where we can collect requests for metrics useful to our customers and which dashboards panels should present these metrics.

**Comment by beyang** [comment]
Re-open if still applicable.
