### ISSUE TITLE
Code Monitors may trigger many repeat notifications

### ISSUE THREAD

**Issue by DaedalusG** [sourcegraph/sourcegraph#55346]
- **Sourcegraph version:** All known versions
- **Platform information:** 

Code monitors with sufficiently complex queries may timeout while searching over commits. This can occur on a large repo with many commits or on a query that is sufficiently complicated. 

Code monitors that timeout during a search may not be marked as completed. However code monitoring results are streamed. As such a code monitor state is possible where a code monitor continuously reports results for the same change, sometimes in a short time interval. 

As an example this broad query generated repeat notifications for the same PR:
<img width="1136" alt="Screenshot 2023-07-27 at 12 09 29 AM" src="https://github.com/sourcegraph/sourcegraph/assets/13024338/fa4e039f-6b95-47a8-a4a3-d9cef317e6be">
<img width="930" alt="Screenshot 2023-07-27 at 12 09 19 AM" src="https://github.com/sourcegraph/sourcegraph/assets/13024338/c8bfb613-72bf-41be-bf95-7f1d50a150ee">

For more context see the compromise solution found in this PR: https://github.com/sourcegraph/sourcegraph/pull/45641#issuecomment-1350071270

**Comment by camdencheek** [comment]
Thanks for the report! We looked into this a bit and there is a writeup [here](https://github.com/sourcegraph/sourcegraph/issues/56238). Since that one is a bit closer to the root problem, I'm gonna close this as a duplicate.
