### ISSUE TITLE
Repo settings UI wording is very repetitive

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#55351]
See the annotations in the screenshot, I think we use the word settings too often on the same page here. 

![Screenshot 2023-07-27 at 13 22 30@2x](https://github.com/sourcegraph/sourcegraph/assets/19534377/714a356a-12c9-43a9-ab04-0d179d575770)

Edit: After thinking about this more, I realized we might be able to just merge his page with the "mirroring" page? 

/cc @sourcegraph/source

**Comment by mrnugget** [comment]
Decision of the council:

- [ ] combine `Options` and `Mirroring` into 1 page, make that top page, rename it `Mirroring`
- [ ] rename `Indexing` to `Search Indexing`
