### ISSUE TITLE
Cody Web: Show repo suggestions when context is empty

### ISSUE THREAD

**Issue by thenamankumar** [sourcegraph/sourcegraph#55363]
The context selector is empty for new users. We should show suggested repos to select based on :
1. and/or previous chat context. 
2. users' browsing history 
3. for dotcom hardcode top 10 open source repos
4. for enterprise first 10 repos by name

**Comment by courier-new** [comment]
Another suggestion from Ryan Aznar over [Slack](https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1690490901320879) is to prioritize repos with embeddings over repos without them when searching the list:

> In the multi-context repo picker, can we prioritize repositories in an organization that have embeddings generated for them already?
See the screenshots where `hashicorp/vault` already has embeddings but isn’t shown until `hashicorp/vau` is typed.

The suggestion received a significant number of +1s from viewers, but Ryan Philips isn't totally sold on it. I personally see value in using that metric to the ordering and think that when searching, we could prioritize and sort the results as such:
1. recently selected repos in previous chats
2. recently visited repos the user browsed
3. repos with embeddings
4. repos for which none of those things are true, alphabetized
