### ISSUE TITLE
Error handling for SMTP config issues

### ISSUE THREAD

**Issue by Galindo-J** [sourcegraph/sourcegraph#55376]
- **Sourcegraph version:**  v5.1.4
- **Platform information:**  Discovered in k8s (Cloud)

#### Steps to reproduce:

1. Properly set up and configure an [SMTP server](https://docs.sourcegraph.com/admin/config/email).
2. Set the site config in Sourcegraph with `authentication` set to `none`, and the username and password set to empty strings, like the following example: 
```  "email.address": "from@example.com",
  "email.smtp": {
    "authentication": "none",
    "username": "",
    "password": "",
    "host": "email-smtp.us-west-2.amazonaws.com",
    "port": 587
  }
}
```
3. Attempt to generate a user access token in the user Settings of Sourcegraph.  

#### Expected behavior:
Upon creating a user access token, if Sourecgraph is having an issue with connecting to the SMTP server, that process should timeout and the subprocess cancelled. I would also expect this error to be surfaced to the UI, or some messaging provided. 

#### Actual behavior:
When creating a user access token, if Sourcegraph runs into issues connecting to the SMTP server, it will retry in the background and not display the new token for 2-3 minutes when the subprocess times out. There are not visible errors in the UI to indicate this is what's happening, making the user believe there is a potential resourcing issue with the instance. Once the subprocess times out, the user access token is displayed if the user doesn't cancel it. 

If you would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are no [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

/cc @sourcegraph/source

**Comment by sashaostrikov** [comment]
@Galindo-J can you tell how urgent is this issue, how many customers are affected by it so we can prioritize accrodingly?

**Comment by Galindo-J** [comment]
@sashaostrikov, in this particular case, the issue showed up on their stage SG instance and wasn't actually necessary. They actually never intended on having this set up, so at this moment, the customer is not impacted at all currently. I'm not sure if there are other customers that are experiencing the same.
