### ISSUE TITLE
browser extension doesn't handle URLs without http/https prefix

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#5538]
When using the Chrome browser extension with Bitbucket or GitHub, it is possible to enter a URL without an `http://` or `https://` prefix:

![image](https://user-images.githubusercontent.com/3173176/64654550-758ebd00-d3de-11e9-941e-0400a301177c.png)

When you do this, nothing warns you and it shows `Connected`. However, links generated by the browser extension are then broken. For example, the jump-to-repository link on our main repo is:

https://github.com/sourcegraph/sourcegraph.com/github.com/sourcegraph/sourcegraph

Reported by a user at https://app.hubspot.com/contacts/2762526/company/407948923

**Comment by felixfbecker** [comment]
Yeah, the error handling in the URL Form is terrible.

**Comment by felixfbecker** [comment]
![image](https://user-images.githubusercontent.com/10532611/96144197-35184180-0f04-11eb-95bb-a0400f7bd1d1.png)
