### ISSUE TITLE
Use new event logs for site metrics

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#5542]
#5486 introduces a new codepath to store events in the database. The end result is that metrics data is being dual written to Redis (old codepath) and Postgres (new codepath), but reads are still being served by Redis.

This issue tracks the work to add support for computing metrics based on the event log in Postgres.

- [ ] Introduce new experimental feature flag that controls whether metrics are read from Redis or computed from the event log in Postgres.
- [ ] Update [existing `usagestats` package](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/pkg/usagestats/usage_stats.go#L41) (or create a new package) to read from Postgres when the above feature flag is enabled.

cc @dadlerj as PM and @tsenart as code reviewer

**Comment by tsenart** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.9 release is scheduled for tomorrow** at 10:00 CEST.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by dadlerj** [comment]
This is WIP (I'm doing this piecemeal)!
