### ISSUE TITLE
Investigate why the repo address cache is not being used in scaletesting

### ISSUE THREAD

**Issue by indradhanush** [sourcegraph/sourcegraph#55428]
Last week we enabled cache lookups on scaletesting by commenting out the `useGitserverAddressLookupCache` config in the [site config](https://scaletesting.sgdev.org/site-admin/configuration). 

We expect this to force cache lookups but looking at the [metrics](https://scaletesting.sgdev.org/-/debug/grafana/explore?orgId=1&left=%5B%22now-15m%22,%22now%22,%22Prometheus%22,%7B%22exemplar%22:true,%22expr%22:%22rate(src_gitserver_addr_for_repo_cache_miss%5B1m%5D)%22,%22requestId%22:%22Q-d5a37697-aeb2-490a-8040-a9a2473facbc-0A%22%7D%5D&right=%5B%22now-15m%22,%22now%22,%22Prometheus%22,%7B%22exemplar%22:true,%22expr%22:%22rate(src_gitserver_addr_for_repo_cache_hit%5B1m%5D)%22,%22requestId%22:%22Q-df7729d0-ea09-4aab-b31f-db2c35cb766e-0A%22%7D%5D), it looks like we don't get any cache hits. 

Find the bug (or if this is an operator error) and fix it. This is a blocker before deduplication can be tested / used on production.

/cc @sourcegraph/source

**Comment by eseliger** [comment]
Moving this from backlog to triage because it feels like the next necessary step. I also noticed that we don't use one global gitserverAddresses struct, so I think your cache is also not necessarily shared - might be why we don't see hits!
