### ISSUE TITLE
Provide option to force an embedding job via site admin

### ISSUE THREAD

**Issue by gl-srgr** [sourcegraph/sourcegraph#55468]
With PR [55180](https://github.com/sourcegraph/sourcegraph/pull/55180) an embedding job can succeed even though one or more chunks could not generate embeddings. This means an index could be considered incomplete, because we just exclude that chunk of text or code from their respective index altogether.

If an admin wants to reattempt indexing so that they do not have an incomplete index then the only way to force an embedding job is to submit `ScheduleRepositoriesForEmbedding` with force=true. It would be easier for admins if they could schedule this via site admin as they can now (only for force=false).

**Comment by gl-srgr** [comment]
related: https://github.com/sourcegraph/sourcegraph/issues/55334

**Comment by nihaals** [comment]
Another usecase is messing with `fileFilters`. I tried running a job and all the files were marked as skipped and I can't easily debug (although I didn't know about the mutation which I can use now) as there hadn't been any changes.

**Comment by jtibshirani** [comment]
Closing this out as we're not investing in embeddings at the moment.
