### ISSUE TITLE
observability: add kubernetes resource monitoring / unified set of container metrics across deployment types

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#5547]
Currently, we have a `Containers` dashboard but it only works in the deploy-sourcegraph-docker context because it relies on the metrics only present in that context. Main problem:

- Kubernetes and deploy-sourcegraph-docker likely have the same set of metrics, but named slightly differently (we can use rules to rename them and define a common set).
- Single container deployments won't have any container metrics, so maybe it shouldn't have a `Containers` dashboard for now?

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.12 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by slimsag** [comment]
Closing as duplicate of https://github.com/sourcegraph/sourcegraph/issues/9791 which has more context.
