### ISSUE TITLE
Evaluate embedding models performance on CPU

### ISSUE THREAD

**Issue by novoselrok** [sourcegraph/sourcegraph#55501]
# Plan

- [ ] Get the baseline latency and throughput numbers by running PyTorch models on a CPU directly.
- [ ] Investigate how changing the number of threads available to PyTorch affects the performance numbers.
- [ ] Investigate how different CPUs and architectures affect the performance numbers.
- [ ] Implement changes from the "Bert CPU scaling" blog post: https://huggingface.co/blog/bert-cpu-scaling-part-1
- [ ] Convert the models to the ONNX format and measure the performance changes (caveat: only a subset of models can be converted to ONNX).
- [ ] Quantize the models using the ONNX library and measure the changes in performance and retrieval metrics.

# Deliverables

- [ ] A series of tables with performance numbers for the above experiments. 
- [ ] Discussion and verdict on whether it is cost-effective to replace GPUs with one or more CPUs.

**Comment by jtibshirani** [comment]
Closing this out as we're not investing in embeddings at the moment.
