### ISSUE TITLE
testing: Run E2E tests locally

### ISSUE THREAD

**Issue by burmudar** [sourcegraph/sourcegraph#55511]
To enable teammates to write more E2E tests it needs to be easier to run the tests locally. At present, the E2E tests can only really run in CI since that is where all the credentials are needed to communicate with all the external dependencies for the test.

#### Open questions
- Retrieval of credentails
- Should the credentials be fetched from the devx-service
- Licensing issues due to limited number of seats
- For local testing, should be use a request replayer/mock server?

Will something like #55509 answer these open questions

**Comment by jhchabran** [comment]
Ok, so the two PRs are ready. It works, but it requires fetching secrets, which very much indicate that we want to do something like `sg test ...` to wrap running them and injecting the secrets fetched through authenticated calls to the devx-service.
