### ISSUE TITLE
JetBrains: Make sure line breaks returned by Cody are consistent with the file

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#55512]
Currently, we have no such check, and the result is some errors like this:

![image](https://github.com/sourcegraph/sourcegraph/assets/2552265/48eab456-d1cb-42f4-b9c1-408531f14de4)

Switching to Cody Agent should solve this.
(Reported by @Rhia2)

Also, as @topebali reported it:
> Everytime the user hit TAB to autocomplete.
> He gets the error
> ```
> java.lang.AssertionError: Wrong line separators: '...iteName");\r\n ...' at offset 43 at com.intellij.openapi.util.text.StringUtil.assertValidSeparators(StringUtil.java:2447) at com.intellij.openapi.editor.impl.DocumentImpl.assertValidSeparators(DocumentImpl.java:716) at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:610) at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:601) at com.sourcegraph.cody.autocomplete.AcceptCodyAutoCompleteAction.applyAutoComplete(AcceptCodyAutoCompleteAction.java:81)
> ```
> Based on the stack trace, the specific line that is triggering the error is this one in `AcceptCodyAutoCompleteAction.java` at:
> ```
> com.sourcegraph.cody.autocomplete.AcceptCodyAutoCompleteAction.applyAutoComplete(AcceptCodyAutoCompleteAction.java:81)
> ```
> 
> My understanding:
> The `applyAutoComplete` method is applying the autocomplete suggestion selected by the user.
> It looks like line 81 of `AcceptCodyAutoCompleteAction.java` is calling `Document.replaceString` to replace the text with the autocompletion.
> The Document then checks the line separators and throws the `AssertionError` on inconsistent line endings.
> So while the direct cause is line 81 calling replaceString, the root issue is inconsistent line endings in the document being edited. I am thinking maybe Fixing that should resolve the problem.

**Comment by Sa1to** [comment]
@vdavid did you start working on it? If no i would like to pick it up 😄
