### ISSUE TITLE
Assess and scope IntelliJ autocomplete feature parity work

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#55541]
Note: this issue hinges on the route we pick in delivering IntelliJ changes, due to the agent migration.

Context: Autocomplete has been fine tuned more in VS Code than in IntelliJ.

Goal: This is to find out what sort of changes can we port (and how). After we learn what changes are needed we can either:

- [ ] https://github.com/sourcegraph/sourcegraph/issues/55615
- [ ] scope out work here...

**Comment by cbart** [comment]
The work on MVP ticket https://github.com/sourcegraph/sourcegraph/issues/55615 is ongoing at this point. As the week progresses we'll scope out more work to port from VSCode autocomplete.

**Comment by cbart** [comment]
Following https://github.com/sourcegraph/sourcegraph/pull/new/cb/st/proto-intellij-embed: #55725

- I'm trying to exercise embeddings with CodeGen inside IntelliJ plugin native
- This is so that worst case we might have another avenue to explore - reduce risk
- Also: Preview how much impact can we see with CodeGen and embeddings

**Comment by chwarwick** [comment]
IntelliJ autocomplete now uses the agent which in turn uses a headless vs code plugin.
