### ISSUE TITLE
Produce SQL query to compute autocomplete acceptance rates from event logs

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#55575]
Note: please make sure the result acceptance rate is aligned with the event logging [as in IntellIJ changes](https://github.com/sourcegraph/cody/issues/123#issuecomment-1672848881).

**Comment by chwarwick** [comment]
Won't we just export this from looker?

**Comment by cbart** [comment]
Thank you! This is viewable via Looker. https://docs.google.com/document/d/1RX0aE1tXfiK-fK6Yan92hpuNq2e3PV0qdNlY4ADmqPU/edit#bookmark=id.hozefev0umn3

I was under impression that we won't have visibility into the dev instance, and need to fall back to SQL.
