### ISSUE TITLE
All files are skipped when `embeddings.fileFilters` is set

### ISSUE THREAD

**Issue by nihaals** [sourcegraph/sourcegraph#55588]
- **Sourcegraph version:** v5.1.5

#### Steps to reproduce:

1. Set `embeddings.fileFilters` to a value without setting `maxFileSizeBytes`.
2. Notice all files are skipped

#### Expected behavior:

Not all files are skipped.

#### Actual behavior:

All files are skipped.

#### Additional context

This is because if `embeddings.fileFilters` is `nil`, the default values are used, but if not, `maxFileSizeBytes` (if omitted) is set to `0`, not back to the default (1MB). This is because it satisfies [the check](https://github.com/sourcegraph/sourcegraph/blob/28ed4afc2def7a2910a2f23eefdcc6e54262e4c6/internal/conf/computed.go#L927-L934).

**Comment by jtibshirani** [comment]
Closing this out, as we're not investing in embeddings at the moment.
