### ISSUE TITLE
Show skipped file reasons in embedding job status

### ISSUE THREAD

**Issue by nihaals** [sourcegraph/sourcegraph#55589]
#### Feature request description

There should be a way to see why files were skipped when checking embedding job statuses e.g. hovering over a job on `/site-admin/embeddings`.

#### Is your feature request related to a problem? If so, please describe.

I ran into an issue where all my files were skipped and couldn't figure out why as my exclusion list shouldn't have been affecting things. After source-diving I discovered that there is a log and so enabled info logging on `worker`, which showed the skip reasons (which helped me find #55588 and the fact that autogenerated files are skipped, which isn't documented). It would be much easier if you could see the reasons for files being skipped (autogenerated, too large, excluded etc.) in the job status instead of needing to enable and check logs.

#### Describe alternatives you've considered.

Enabling logging for worker instances which is more fiddly than if it was part of the status page.

**Comment by jtibshirani** [comment]
Closing this out, as we're not investing in embeddings at the moment.
