### ISSUE TITLE
After license expiration, admins can't access management console password

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#5559]
- **Sourcegraph version:** all recent sourcegraph versions

Reported by:
* https://app.hubspot.com/contacts/2762526/company/1768250576
* https://app.hubspot.com/contacts/2762526/company/887065580

>looks like I've got an old password for my management console saved. And I cannot access the current password due to the expiration of the other license. 

The workaround to this is to reset the management console password, documented at https://docs.sourcegraph.com/admin/management_console#how-can-i-reset-my-management-console-password

This has now come up a few times with users as their trial licenses expire, due to:
1) it’s non-obvious what to do in this situation
2) Most users aren’t good about saving their management console password somewhere externally
3) That workaround above might look a bit intimidating, even if it’s quick

Rethinking this flow might be helpful. Perhaps we expose the management console password value on the “license has expired” page to admins? Or perhaps we could still allow one "primary" site admin to log in after license expiration?

cc @juliasourceress @slimsag 

Customers:  https://app.hubspot.com/contacts/2762526/company/887065580 (and others)

**Comment by dadlerj** [comment]
From a user who ran into this:
>I haven't had a chance to reset the password with the extended way yet. With the end of the quarter closing, I've had other priorities I've had to shift to. I hope to be able to get a chance to do this soon, but was hoping there would be a more convenient way.

**Comment by dadlerj** [comment]
And then after following up later:
>>>
Hi,

I had a few extra minutes this morning. To simplify things, I threw together a Docker container for this, since I don't have python nor pip installed. In case you want to add it to your docs.

Dockerfile
```
FROM python:3.7.4-alpine3.10

RUN apk add --no-cache g++
RUN pip install py-bcrypt

CMD ["sh"]
```
And a bash script to build and run it.
password-reset.sh
```
#!/usr/bin/env bash

docker build --tag=sourcegraph-password-reset .

if [[ -z ${PASSWORD} ]]; then
   read -s -p "Enter password: " PASSWORD
   echo
fi

docker run \
    -it \
   --rm \
   -e PASSWORD=${PASSWORD} \
   --name=sourcegraph-password-reset \
   sourcegraph-password-reset \
   python -c "import bcrypt; import os; print(bcrypt.hashpw(os.environ['PASSWORD'], bcrypt.gensalt(15)))"
```
The output will look something like this
```
$ ./password-reset.sh 
Sending build context to Docker daemon  4.096kB
Step 1/4 : FROM python:3.7.4-alpine3.10
 ---> 39fb80313465
Step 2/4 : RUN apk add --no-cache g++
 ---> Using cache
 ---> 3b39750a021f
Step 3/4 : RUN pip install py-bcrypt
 ---> Using cache
 ---> f4557986d504
Step 4/4 : CMD ["sh"]
 ---> Using cache
 ---> 701c74cc044e
Successfully built 701c74cc044e
Successfully tagged sg-reset-pass:latest
Enter password: 
$2a$15$ybkiQvo6pcsrAx0DWpN0FOFe/QyWXY1GIUVAlowZ1W57WlXN8A/xW
```

**Comment by uwedeportivo** [comment]
https://github.com/sourcegraph/sourcegraph/pull/6699
