### ISSUE TITLE
bug: e2e servers might not have been properly cleaned up

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#55661]
See https://buildkite.com/sourcegraph/sourcegraph/builds/237627#0189d8b1-5484-455f-b783-3095f8021c4a/72-116

This is problematic and it happens every once in a while. The most concerning thing is _why_ it can happen in the first place.

**Comment by jhchabran** [comment]
Still monitoring, didn't spot any error

**Comment by jhchabran** [comment]
@davejrt I think I accidentally reproduced it locally, or at least part of it. If for some reason Bazel gets interrupted, the containers will keep running. We have [this](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/testing/tools/integration_runner.sh?L170) in the shell script, but it's fine because we [clean things](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/.buildkite/hooks/pre-exit?L20) when exiting from the job. 

The only reason I could see this happening is because we somehow lose the agent or it dies, but that agent comes back online in a botched state. 

I think at this point, we really need to find a way to send out the logs to GCP, so we can find these agents.

**Comment by jhchabran** [comment]
Or we could call the sentry reporting code in the code.

**Comment by davejrt** [comment]
> @davejrt I think I accidentally reproduced it locally, or at least part of it. If for some reason Bazel gets interrupted, the containers will keep running. We have [this](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/testing/tools/integration_runner.sh?L170) in the shell script, but it's fine because we [clean things](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/.buildkite/hooks/pre-exit?L20) when exiting from the job.
> 
> The only reason I could see this happening is because we somehow lose the agent or it dies, but that agent comes back online in a botched state.
> 
> I think at this point, we really need to find a way to send out the logs to GCP, so we can find these agents.

Agreed, I think for now [this](https://github.com/sourcegraph/sourcegraph/pull/56059) probably addresses the short term concern but your investigation is far more scientific than mine
