### ISSUE TITLE
5.1.6 Security approval

### ISSUE THREAD

**Issue by sanderginn** [sourcegraph/sourcegraph#55724]
Security must close this issue before releases. It is the responsibility of the Security Engineer on rotation the week the release is cut. More steps will be added in the future.

- [x] All feasible CVEs are closed.
- [x] Any open CVEs are documented in the handbook.

cc @sourcegraph/security

**Comment by willdollman** [comment]
Added 5.1.6 accepted cves https://github.com/sourcegraph/handbook/pull/7568, no new issues found
