### ISSUE TITLE
ci observaility: report test flakes

### ISSUE THREAD

**Issue by davejrt** [sourcegraph/sourcegraph#55753]
Create a report for the bazel tests that enables us to report test flakes. 

The report should ideally include which teams owns the test, and determine if a test has been automatically retried, or a user is manually retrying.

**Comment by jhchabran** [comment]
To add context on this, we already have buildkit test analytics, but we don't automatically surface that to the owners, or have any mechanism to build a report. 

Right now, we're posting these manually, like a top-ten in the bi-weekly newsletter in #announce-engineering. So anything that makes that simpler is good already. Perhaps Buildkite analytics has something for this already.
