### ISSUE TITLE
backports: Prompt PR author to add changelog entry if necessary

### ISSUE THREAD

**Issue by sanderginn** [sourcegraph/sourcegraph#55787]
A lot of backported PRs do not update the changelog, even though they contain important fixes or changes. The release captain has to ask teammates who have backported to add these changes after the fact, which is inconvenient and leads to missing changelog entries.

The changelog on `main` acts as the source of truth, so this check should happen on any PRs that merge a feature branch into `main` _and_ get labeled for backporting. Before the backport PR gets created, the following cases are evaluated:
- The PR contains a diff for `CHANGELOG.md`? ✅ , create backport PR
- The PR contains no diff for `CHANGELOG.md`? ❌ , one of the following must happen:
  - The author confirms no changelog entry is required, e.g. with a `/no-changelog` comment, and the backport PR gets created
  - The author commits a changelog entry which triggers the check again and should pass now

### References
- [Slack thread](https://sourcegraph.slack.com/archives/C032Z79NZQC/p1691744143767099)

**Comment by BolajiOlajide** [comment]
Can we close this? @jdpleiness

**Comment by BolajiOlajide** [comment]
Closing this out.
