### ISSUE TITLE
JetBrains: add ability to override automatic "codebase" detection

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#55795]
The VS Code extension has a "codebase" setting that is not yet supported in the JetBrains plugin. We should add this setting to reach feature parity.

**Comment by alexfogg** [comment]
Just want to strongly +1 this, since [this customer](https://github.com/sourcegraph/accounts/issues/6947) is blocked from using embeddings on jetbrains (a large portion of their team) without the `codebase` setting.[ Slack context here.](https://sourcegraph.slack.com/archives/C059N5FRYG3/p1691768583492639)

**Comment by vdavid** [comment]
This is what this setting looks like in VS Code:

![image](https://github.com/sourcegraph/sourcegraph/assets/2552265/fdf228bc-12eb-43eb-a0c9-39069b3f9798)

But I'm unsure how this would work with multiple repo.

Question 1: How this would work in conjunction with the automatic repo recognition? @chwarwick's [recent change](https://github.com/sourcegraph/sourcegraph/pull/55900#issuecomment-1679892740) relays the auto-recognized repo to the agent. Should this be disabled if the codebase is set to non-empty?

Question 2: If I understand correctly, one customer who needs this might not use a monorepo; in that case, having a fixed codebase setting does not sound very helpful for them; perhaps what they need is more like a pattern replace option, similar to what we have for URLs?

<img width="768" alt="CleanShot 2023-08-16 at 20 53 31@2x" src="https://github.com/sourcegraph/sourcegraph/assets/2552265/0ed33664-0c8d-44a6-bfd4-ad60f737051e">

@alexfogg, your input about the requirements might help here.

**Comment by chwarwick** [comment]
In VS Code this setting takes priority over the automatic detection.  This setting is primarily used as a way to force the context to a specific repo or as a fix if the automatic detection does not work.

**Comment by alexfogg** [comment]
Yeah in this case I think, _if it's set_, override the autodetect. For this specific customer instance, they are mirroring  their on-prem GHE code to Github.com so that we can more easily index the repos without tunneling. So when it autodetects the repos, it is picking up the wrong remote.

**Comment by olafurpg** [comment]
+1 to blind override. 

@vdavid Not super important, but we may want to internally persist the data as a list of codebases instead of a string with a single codebase. This makes it easy to add support for multi-repo context in the future.

**Comment by olafurpg** [comment]
Following up from a meeting discussion about this issue:

- The plugin currently supports automatic inference of the codebase based on git metadata. This automatic inference  should work well in most cases, including IntelliJ projects that enclose multiple git repositories. 
- There is currently no way to specify multiple repositories for the context. This feature is not supported in VS Code either, but it's supported by Cody on the web.
- There's currently no way to explicitly specify which codebase should be used in case automatic inference fails.

The scope of this issue is only to fix the last bullet point.

**Comment by danielmarquespt** [comment]
UX for this: 
https://sourcegraph.slack.com/archives/C059N5FRYG3/p1694700544481319?thread_ts=1694510529.155349&cid=C059N5FRYG3

**Comment by olafurpg** [comment]
Fixed in https://github.com/sourcegraph/sourcegraph/pull/56683
