### ISSUE TITLE
Display status of exhaustive search in normal search

### ISSUE THREAD

**Issue by Piszmog** [sourcegraph/sourcegraph#55806]
If a user has an exhaustive search running/in progress/errored and the user runs a regular search that matches an exhaustive search, display a banner that they have a search. Display the progress of the search.

## Functionality

- In the regular search result page, display status of an exhaustive search if there is a matching exhaustive search

## Done

- Demo
- Storybooks

## Design

- See [wireframe](https://app.excalidraw.com/s/4Dr1S6qmmY7/AZ3e5sR7gBo)

**Comment by vovakulikov** [comment]
No longer relative, no search jobs UI on the search result page
