### ISSUE TITLE
Add button to view errors

### ISSUE THREAD

**Issue by Piszmog** [sourcegraph/sourcegraph#55807]
Add a button to be able to view the errors related to an exhaustive search.

## Functionality

- Add a button on the search list page that displays errors in a modal

## Done

- Demo
- Storybooks

## Design

- See [wireframe](https://app.excalidraw.com/s/4Dr1S6qmmY7/AZ3e5sR7gBo)

**Comment by vovakulikov** [comment]
In the October release all errors will be accessible through view logs downloaded archive file, this issue is no longer error, we may want to return to this in the further iterations over search jobs UI
