### ISSUE TITLE
Firefox extension: Code intelligence not working "LSIF /exists returned Internal Server Error"

### ISSUE THREAD

**Issue by kradalby** [sourcegraph/sourcegraph#5584]
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:** Firefox 69.0, Sourcegraph ext: 19.9.9.2248

#### Steps to reproduce:

1. Install extensions
2. Visit project on GitHub (https://github.com/google/rejoiner/blob/master/rejoiner/src/main/java/com/google/api/graphql/grpc/QueryResponseToProto.java)
3. Hover over code

#### Expected behavior:
Code intelligence

#### Actual behavior:
Nothing, and the console goes mental:

<img width="1280" alt="20190914133532" src="https://user-images.githubusercontent.com/98431/64908165-a2034b80-d6f4-11e9-897c-172ec5e9f0c8.png">

**Comment by unknwon** [comment]
I think this is fixed already? cc @chrismwendt

**Comment by chrismwendt** [comment]
Fixed in https://github.com/sourcegraph/sourcegraph-basic-code-intel/pull/145

**Comment by unknwon** [comment]
Off topic: @kradalby I love the color of you browser 😄
