### ISSUE TITLE
Upstream zoekt change to not fail indexing when ultra long symbol names exist in repo

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#5587]
I've discovered some repositories are too large to index after we added symbol indexing:

- https://github.com/noshotz/eldorito
- https://github.com/corretto/corretto-8
- https://github.com/ifsnow/facebooklivereaction

Steps to reproduce:

1. Start a dev server
2. Add any of the above repositories to your instance
3. Monitor the site-admin indexing page, or the zoekt-indexserver logs

The errors that are produced are:

```
20:29:11      zoekt-indexserver | 2019/09/14 20:29:11 error indexing github.com/corretto/corretto-8@3edc870d4f7e46056d20af8d99e388494df74178: command [zoekt-archive-index -parallelism=2 -index /Users/stephen/.sourcegraph/zoekt/index -file_limit 1048576 -incremental -branch HEAD -commit 3edc870d4f7e46056d20af8d99e388494df74178 -name github.com/corretto/corretto-8 -require_ctags http://localhost:3090/.internal/git/github.com/corretto/corretto-8/tar/3edc870d4f7e46056d20af8d99e388494df74178] failed: exit status 1
20:29:11      zoekt-indexserver | OUT: 
20:29:11      zoekt-indexserver | ERR: 2019/09/14 20:28:12 builder.go:560: finished /Users/stephen/.sourcegraph/zoekt/index/github.com%2Fcorretto%2Fcorretto-8_v16.00001.zoekt: 286913630 index bytes (overhead 2.8)
20:29:11      zoekt-indexserver | 2019/09/14 20:28:13 builder.go:560: finished /Users/stephen/.sourcegraph/zoekt/index/github.com%2Fcorretto%2Fcorretto-8_v16.00000.zoekt: 294914678 index bytes (overhead 2.8)
20:29:11      zoekt-indexserver | 2019/09/14 20:29:10 builder.go:560: finished /Users/stephen/.sourcegraph/zoekt/index/github.com%2Fcorretto%2Fcorretto-8_v16.00002.zoekt: 279052892 index bytes (overhead 2.7)
20:29:11      zoekt-indexserver | 2019/09/14 20:29:10 builder.go:309: Builder.Finish /Users/stephen/.sourcegraph/zoekt/index/github.com%2Fcorretto%2Fcorretto-8_v16.00001.zoekt258100563
20:29:11      zoekt-indexserver | 2019/09/14 20:29:10 builder.go:309: Builder.Finish /Users/stephen/.sourcegraph/zoekt/index/github.com%2Fcorretto%2Fcorretto-8_v16.00000.zoekt699348118
20:29:11      zoekt-indexserver | 2019/09/14 20:29:10 builder.go:309: Builder.Finish /Users/stephen/.sourcegraph/zoekt/index/github.com%2Fcorretto%2Fcorretto-8_v16.00002.zoekt273914109
20:29:11      zoekt-indexserver | 2019/09/14 20:29:10 main.go:235: bufio.Scanner: token too long
```

**Comment by slimsag** [comment]
### Scope

I don't know how often / likely this is to occur, that is my main worry here. On the 13k repositories I have added to my instance, the 3 linked in the description are affected -- but the repositories I added are typically small. This could happen more frequently on large repos.

### Where

This error here:

> main.go:235: bufio.Scanner: token too long

appears to be coming from `zoekt-index-archive` here:

https://github.com/sourcegraph/zoekt/blob/6d3f42993680881772674aaf3e65d2dc2abfc26e/cmd/zoekt-archive-index/main.go#L235

### Mitigation

It seems that it is blocking text indexing because we specify `-require_ctags` here:

https://github.com/sourcegraph/zoekt/blob/6d3f42993680881772674aaf3e65d2dc2abfc26e/cmd/zoekt-sourcegraph-indexserver/main.go#L190

If we didn't set that, it does seem like we would at least continue text indexing successfully:

https://github.com/sourcegraph/zoekt/blob/6d3f42993680881772674aaf3e65d2dc2abfc26e/build/builder.go#L476-L482

Maybe it is worth not specifying `-require_ctags`, if the underlying problem is not easy to solve?

### Underlying problem

The way Zoekt parses the universal-ctags output is using a `bufio.Scanner` here:

https://github.com/sourcegraph/zoekt/blob/6d3f42993680881772674aaf3e65d2dc2abfc26e/ctags/json.go#L66

It appears to be reading newline-delimited output, and some lines are exceeding the 64 KiB max size that `bufio.Scanner` [can handle by default](https://golang.org/pkg/bufio/#pkg-constants):

```Go
const (
        // MaxScanTokenSize is the maximum size used to buffer a token
        // unless the user provides an explicit buffer with Scanner.Buffer.
        // The actual maximum token size may be smaller as the buffer
        // may need to include, for instance, a newline.
        MaxScanTokenSize = 64 * 1024
)
```

This means we have two options:

1. [Specify a larger buffer size](https://golang.org/pkg/bufio/#Scanner.Buffer) -- this would probably be reasonable because the buffer size is for the entire ctags process -- which is invoked for a whole repository -- so we could probably reasonable bump the buffer size up to 1 MiB instead of 64 KiB and the memory overhead would be < 2 MiB at basically all times.
2. Refactor the code to not use `bufio.Scanner` and instead use a [`bufio.Reader`](https://golang.org/pkg/bufio/#Reader) which does not suffer from this limitation and I think would be more efficient(?)

**Comment by slimsag** [comment]
I will implement #1 above since it is a quick fix that will fully solve this semi-critical issue (given I don't really know how many repositories this affects).

@keegancsmith @kzh can one of you own refactoring the code to use `bufio.Reader` as mentioned above later on, and upstream that change to zoekt?

**Comment by slimsag** [comment]
Easier way to reproduce this:

```
$ docker run -it sourcegraph/zoekt-indexserver:0.0.20190913055037-b3e888a sh
$ zoekt-archive-index -parallelism=4 -index /tmp/zoekt-index -file_limit 1048576 -incremental -branch HEAD -commit 3edc870d4f7e46056d20af8d99e388494df74178 -name github.com/corretto/corretto-8 -require_ctags https://github.com/corretto/corretto-8/tarball/3edc870d4f7e46056d20af8d99e388494df74178
```

Outputs:

```
ctags https://github.com/corretto/corretto-8/tarball/3edc870d4f7e46056d20af8d99e388494df74178
2019/09/15 21:00:39 builder.go:542: finished /tmp/zoekt-index/github.com%2Fcorretto%2Fcorretto-8_v16.00000.zoekt: 294914658 index bytes (overhead 2.8)
2019/09/15 21:00:44 builder.go:542: finished /tmp/zoekt-index/github.com%2Fcorretto%2Fcorretto-8_v16.00001.zoekt: 286913354 index bytes (overhead 2.8)
2019/09/15 21:00:53 builder.go:542: finished /tmp/zoekt-index/github.com%2Fcorretto%2Fcorretto-8_v16.00002.zoekt: 279052872 index bytes (overhead 2.7)
2019/09/15 21:00:53 builder.go:305: Builder.Finish /tmp/zoekt-index/github.com%2Fcorretto%2Fcorretto-8_v16.00001.zoekt565948742
2019/09/15 21:00:53 builder.go:305: Builder.Finish /tmp/zoekt-index/github.com%2Fcorretto%2Fcorretto-8_v16.00002.zoekt191813613
2019/09/15 21:00:53 builder.go:305: Builder.Finish /tmp/zoekt-index/github.com%2Fcorretto%2Fcorretto-8_v16.00000.zoekt829786819
2019/09/15 21:00:53 main.go:235: bufio.Scanner: token too long
```

I have noticed it is sometimes flaky, sometimes not reproducing and other times does. Must be triggered by some indeterministic behavior in the ctags output?

**Comment by slimsag** [comment]
I have not been able to reproduce it _outside_ the container, I think due to my ctags version not being built on homebrew with `--include-json` and `--include-seccomp`: https://github.com/sourcegraph/infrastructure/blob/master/docker-images/zoekt-indexserver/Dockerfile#L19 -- or possibly due to the additional languages we add in https://github.com/sourcegraph/infrastructure/tree/master/docker-images/zoekt-indexserver/.ctags.d

**Comment by slimsag** [comment]
So... the length of the problematic line in _that_ repository is 140345 (140 KiB). I am thinking it is not smart to ask Zoekt to index those, so instead I have written the change to discard such long lines entirely which seems smarter / less likely to cause any perf issues.

Side note, in at least that repository the symbol in question is an ultra long symbol name to test a bug in a Java compiler 😆: https://sourcegraph.com/github.com/corretto/corretto-8@f83f2350525ae18bc34487c1c6eddf6cd343b02d/-/blob/src/langtools/test/tools/javac/limits/LongName.java#L38

**Comment by slimsag** [comment]
Leaving open for the follow-up work of upstreaming this change in some form: https://github.com/sourcegraph/sourcegraph/issues/5587#issuecomment-531534258

**Comment by slimsag** [comment]
Confirmed the above fixed it on the 3 problematic repos on my instance.

**Comment by keegancsmith** [comment]
I ended up over engineering a fix for this for fun. Instead of giving up on long lines, I wrote something which skips the long lines. https://gerrit-review.googlesource.com/c/zoekt/+/241732
