### ISSUE TITLE
Add authentication to internal API calls

### ISSUE THREAD

**Issue by kopancek** [sourcegraph/sourcegraph#55904]
There is no authentication for internal API calls, which leads to several problems:

- we cannot identify which service is calling which, other than looking into the source code
- when a certain service is hammered with request, we have no idea what is the cause
- we cannot add rate limiting based on the source of data - e.g. allow more requests per time period from critical services vs others

The purpose of this issue is to fix the first 2 problems by adding an auth mechanism to the internal API calls. This needs a proper RFC, but it can be as simple as adding a caller identifier field to the request context. Once we have it, we can follow-up with other work mentioned 

- [ ] provide observability for internal service calls between services
- [ ] enforce rate limiting for internal services

/cc @sourcegraph/source

**Comment by eseliger** [comment]
Can this be solved by gRPC with mTLS?

**Comment by eseliger** [comment]
We added observability to address the underlying issue of not knowing who's calling what. mTLS support, if needed, should be tracked separately.
