### ISSUE TITLE
lsif-server logging requests to /metrics is extremely verbose

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#5590]
Prometheus queries the `/metrics` endpoint of lsif-server every few seconds, and lsif-server appears to be logging that -- so the `sourcegraph/server` logs are now very verbose and contain hundreds of these after just a short while:

```
20:26:35            lsif-server | GET /metrics 200 - - 0.092 ms
20:27:05            lsif-server | GET /metrics 200 - - 0.049 ms
20:27:35            lsif-server | GET /metrics 200 - - 0.162 ms
```

**Comment by chrismwendt** [comment]
Thanks for reporting - looking into this now

**Comment by chrismwendt** [comment]
Fix pending review in https://github.com/sourcegraph/sourcegraph/pull/5591
