### ISSUE TITLE
JetBrains: test autocomplete and chat on Windows

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#55916]
We currently only test the plugin on macOS and maybe Linux. We should test the plugin on Windows to make sure it's working there as well.

**Comment by olafurpg** [comment]
Closing as fixed since we have validated that the agent loads on Windows. There may still be some unexpected issues that reproduce on Windows and will open separate issues for those.

**Comment by vdavid** [comment]
Just upgraded to 3.1.0-alpha.1 on Windows, and it gives me no chat responses or autocompletions. 😔

**Comment by olafurpg** [comment]
> I'm getting no autocompletions whatsoever. No sign of them.


Just to be 100% sure, did you enable the autocomplete setting?

> If I disable and re-enable the plugin, chat is not working.

Did you restart IntelliJ? The plugin requires a restart until we fix https://github.com/sourcegraph/sourcegraph/issues/56049

**Comment by vdavid** [comment]
Yes to both.

**Comment by vdavid** [comment]
I've found no Windows-specific issues.
- Updated to 3.0.10.alpha.2 to 3.1.0
  - **Papercut**: I got an "Open Cody sidebar to get started" notification, however, my Cody sidebar had already been open at the time.
- **Problem**: I already had a correct token set up for an enterprise Sourcegraph instance, but I'm getting no response in the Cody chat. When I open Account settings and modify the token, although it's correct, I'm getting an "Incorrect credentials. Token should match username" error message (see https://share.cleanshot.com/hRfyBKLK). I think many existing users will be in this situation, and they won't be able to set their token unless they remove and re-add their account. This is counter-intuitive. Could we just refresh the username perhaps?
- **Papercut**: When I'm in Settings | Sourcegraph & Cody, I expect an account item to open for editing upon double-clicking the item. Instead, nothing happens.
- The "Generate token" link works correctly: it opens the browser as expected.
- After removing and re-adding the same account I already have, chat works.
- **Problem**: I'm getting no completions. The status bar icon just keeps on spinning: https://share.cleanshot.com/tnZ2B9HQ
- **Problem**: For commands, Cody doesn't only explain my selected code but the whole file: https://share.cleanshot.com/dfBpCRfX – it's as if it doesn't recognize my selection. It's the same for other commands I tried.
- If I remove all accounts and click the "Sign in for free with Sourcegraph.com" link, it correctly brings me to the browser, then, after auth, it saves the token correctly and chat works again. Autocomplete, however, also hangs with dotcom.

**Comment by olafurpg** [comment]
@olafurpg Thank you! The autocomplete issue could be unrelated to Windows if you hit on the same issue that is fixed by https://github.com/sourcegraph/cody/pull/1140

**Comment by olafurpg** [comment]
I tried enabling tracing but included double quotes in the file path and it failed like this

![Image](https://github.com/sourcegraph/sourcegraph/assets/1408093/1aba5340-12fe-4738-a30a-26ec339ea4d3)

```




java.nio.file.InvalidPathException: Illegal char <"> at index 0: "C:\Users\olafurpg\IdeaProjects\agent-trace.json.txt"
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:177)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
```

**Comment by olafurpg** [comment]
I was able to get autocomplete working on Windows with this fix here https://github.com/sourcegraph/cody/pull/1264

**Comment by olafurpg** [comment]
Fixed in https://github.com/sourcegraph/cody/pull/1264
