### ISSUE TITLE
Flaky search tabs test

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#5593]
- Test failure: https://buildkite.com/sourcegraph/sourcegraph/builds/42904#b474cfef-54fe-4006-95b7-ac08c05301c1/152-268
- It passed after retrying the same e2e step

That test was added in https://github.com/sourcegraph/sourcegraph/pull/5402/files#diff-c0774af47ef6815ba80ee709b86f9a66R1136-R1141

I'm not sure what went wrong (I checked the video, too). We could `test.skip` that test until we fix the flakiness, or gather more data (i.e. wait for that test to fail again) to help identify the source of the flakiness.

**Comment by slimsag** [comment]
Skipping the test should be the default action, always.
