### ISSUE TITLE
Resolving revisions during indexing averages ~5s, should we optimize it?

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#5594]
Looking at the time we spend indexing 13k repos, about 5s on average is just spent resolving revisions but most of the requests are on average only milliseconds. If we wanted to optimize it, I suspect the first step would be turning this loop into a single request instead of multiple smaller ones:

https://github.com/sourcegraph/zoekt/blob/b3e888ac00bf35b45aa96dc5aa1db979f6076db2/cmd/zoekt-sourcegraph-indexserver/main.go#L134-L149

More details: https://github.com/sourcegraph/zoekt/pull/26#issuecomment-531540797

This would be nice-to-have, not a need by anyone currently.

**Comment by keegancsmith** [comment]
Based on https://github.com/sourcegraph/zoekt/pull/26#issuecomment-531828468 I think we can close this out? Please reopen if I am mistaken.
