### ISSUE TITLE
zoekt-indexserver should log how long indexing a given repository takes

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#5595]
Most repositories index in under 15s, but some go for several minutes. If indexing a repository takes longer than 15s, it would be ideal to log which one so that we can see if there is any optimization that makes sense to do. This should be a quick change to make.

This would be done here: https://github.com/sourcegraph/zoekt/blob/b3e888ac00bf35b45aa96dc5aa1db979f6076db2/cmd/zoekt-sourcegraph-indexserver/main.go#L166-L174

**Comment by stefanhengl** [comment]
Done. Index times are logged.
