### ISSUE TITLE
Validate Search Queries

### ISSUE THREAD

**Issue by Piszmog** [sourcegraph/sourcegraph#55973]
Implement the GraphQL API that validates queries. Prevent queries with unsupported operators.

## Unsupported Queries

- Multiple `rev` operators
- `.*`
- Predicate `file:has.content("foo")`
- Predicate `repo:has.content("foo")`
- `OR` combinator

## Done

- Unit Tests
- Demo

**Comment by vovakulikov** [comment]
I'm okay with restricted OR operators in all cases, but I think not all queries with OR operators can't be run in an exhaustive search you still can have this query "insights OR batch-changes" but only when both operands in the OR operator have `rev:` or other non-multiple "global-like" filters we should fail with validation error. 

But again I think failing with just OR makes at this point, we can iterate on this in the further releases.

**Comment by Piszmog** [comment]
Maybe we just support simple queries?
