### ISSUE TITLE
Report model identifier for current embedding indices

### ISSUE THREAD

**Issue by gl-srgr** [sourcegraph/sourcegraph#55984]
Currently the status of a given repository's embedding index is found via:

- List repositories with `embedded` and `notEmbedded` filtering options
- Checking the repository embedding jobs list (site admin, graphql) and filter for repos in question

Neither of these report the model used for the current index. When migrating we should have a means of viewing model Identifier so that admins can determine whether a migration is necessary for a given repository and whether a migration to the new model has succeeded.

Since we want to avoid fetching index from blob store to determine model ID we should complete https://github.com/sourcegraph/sourcegraph/issues/55983 as prerequisite.

**Comment by jtibshirani** [comment]
Closing this out as we're not investing in embeddings at the moment.
