### ISSUE TITLE
Remove usage of go-disk-usage dependency and switch to internal/diskusage

### ISSUE THREAD

**Issue by BolajiOlajide** [sourcegraph/sourcegraph#56023]
Since we're making a copy of `go-disk-usage`, it'll be nice to clean up the usage in:

* [internal/metrics/metrics.go](https://sourcegraph.com/-/editor?remote_url=git%40github.com%3Asourcegraph%2Fsourcegraph.git&branch=main&file=internal%2Fmetrics%2Fmetrics.go&editor=VSCode&version=2.2.16&start_row=204&start_col=1&end_row=204&end_col=33)
* [cmd/gitserver/server/servermetrics.go](https://sourcegraph.com/-/editor?remote_url=git%40github.com%3Asourcegraph%2Fsourcegraph.git&branch=main&file=cmd%2Fgitserver%2Fserver%2Fservermetrics.go&editor=VSCode&version=2.2.16&start_row=56&start_col=2&end_row=56&end_col=38)
* [cmd/gitserver/server/servermetrics.go](https://sourcegraph.com/-/editor?remote_url=git%40github.com%3Asourcegraph%2Fsourcegraph.git&branch=main&file=cmd%2Fgitserver%2Fserver%2Fservermetrics.go&editor=VSCode&version=2.2.16&start_row=47&start_col=2&end_row=47&end_col=38)
* [cmd/gitserver/server/cleanup.go](https://sourcegraph.com/-/editor?remote_url=git%40github.com%3Asourcegraph%2Fsourcegraph.git&branch=main&file=cmd%2Fgitserver%2Fserver%2Fcleanup.go&editor=VSCode&version=2.2.16&start_row=665&start_col=1&end_row=665&end_col=37)
* [cmd/gitserver/server/cleanup.go](https://sourcegraph.com/-/editor?remote_url=git%40github.com%3Asourcegraph%2Fsourcegraph.git&branch=main&file=cmd%2Fgitserver%2Fserver%2Fcleanup.go&editor=VSCode&version=2.2.16&start_row=660&start_col=1&end_row=660&end_col=37)

/cc @sourcegraph/source

**Comment by eseliger** [comment]
What's the rationale behind making a copy if we already used that dependency? Does it have a bug?
