### ISSUE TITLE
JetBrains: pressing escape to reject autocomplete suggestion does not work with IdeaVim

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#56051]
To reproduce:

- Install IdeaVim
- Use insert mode
- Trigger autocomplete
- Press escape
- Confirm that IdeaVim leaves insert mode BUT autocomplete suggestion is still visible

Expectation:

- Cody autocomplete suggestion gets disposed AND IdeaVim leaves insert mode

**Comment by olafurpg** [comment]
@jamescrosswell Thank you for reporting! The latest release in the "Alpha" channel does reject autocomplete on `Escape`. This alpha release is almost a complete rewrite of autocomplete functionality. We are planning to promote the alpha release into stable in the coming 1-2 weeks.

**Comment by jamescrosswell** [comment]
Awesome - can't wait! 😀
