### ISSUE TITLE
Track creator and last-person-to-update on external service

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#56071]
We sometimes wonder "who created this service" - since we don't have the history for external services that we have for site config, a `creator_id` and `last_updater_id` might be useful. 
We could also bring that site config diffing to external services, but that feels more involved? Or is that very pluggable? 

/cc @sourcegraph/source

**Comment by gabtorre** [comment]
Hey @eseliger, I'm working on this [PR](https://github.com/sourcegraph/sourcegraph/pull/57603) to add the rows and update the methods where the last updater and creator will be needed. I will create a follow-up PR to display the last updater and creator in the UI.

**Comment by eseliger** [comment]
nice!
