### ISSUE TITLE
Git command output should be truncated

### ISSUE THREAD

**Issue by gl-srgr** [sourcegraph/sourcegraph#56080]
Currently when running remote git commands there are return values that include the full output from a reader, for example `CombinedOutput` and `Output` for [`RemoteGitCommand`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@14d4d817c725ee3877db0f6fbc7819c252f49597/-/blob/internal/gitserver/git_command.go?L184-217). We have some logic for truncating the `stdErr` in the implementation of [`Error()`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@14d4d817c725ee3877db0f6fbc7819c252f49597/-/blob/internal/gitserver/client.go?L740-744) by the `CommandStatusError` struct. However the output is not truncated as far as I can tell and this is the issue we've encountered.

- Recent [case](https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1692222953582379) where our `git ls-tree` call returns the full output (path arg is the root dir and recursive arg is `true`). This output is included in the error which then gets stored as the job's `failure_message`. Subsequent requests for job status then has to load this large message and takes minutes to complete the request.
- Older [case](https://sourcegraph.slack.com/archives/C03TGHH1S3V/p1682987817082709?thread_ts=1682987591.585679&cid=C03TGHH1S3V) from May where `git ls-files` also has a large output that gets logged as an event.

Since these outputs are massive it isn't useful for observability and also have an impact on events logging.

/cc @sourcegraph/source

**Comment by mrnugget** [comment]
The long error message comes from here:

https://github.com/sourcegraph/sourcegraph/blob/d2d17b5d677dd3f2e9042d647595b4018c2156ca/internal/gitserver/commands.go#L567-L573

That's the exact output matching what's in the linked Slack threads.
