### ISSUE TITLE
(cross-collaboration) Define baseline feature requirements from strategic customers.

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#56165]
We need to gather customer input on which features are the baseline Cody functionality, and which editors across {VS Code, Jetbrains, NeoVim} are in scope for each customer.

- Please look for input from @taylorsperry on various editors feature sets, and how fine-grained we'd like to talk about features.
- Perhaps @taylorsperry already has the answer to that.
- Please then find the right assignee (or break down tasks for each strategic customer) to gather input from the customers.

**Comment by johnwesonga** [comment]
Feature sets doc https://docs.google.com/spreadsheets/d/1YYq354DuRwhgS_MJZahEqW05_MOeOQTbQtZsyrBeJos/edit#gid=0

**Comment by slimsag** [comment]
Challenge: NeoVim and Emacs are complex

If we need strategic work on NeoVim/Emacs, we will need to pass that work to the teams working on that (and apologize we don't know how to exit)

**Comment by cbart** [comment]
@johnwesonga do we know what are the gaps between:

- [feature sets currently](https://docs.google.com/spreadsheets/d/1YYq354DuRwhgS_MJZahEqW05_MOeOQTbQtZsyrBeJos/edit#gid=0)
- client teams planned work
- and strategic customer requests?

**Comment by cbart** [comment]
This is outside of the scope for Q4 - dropping.
