### ISSUE TITLE
Code monitors: `MonitorsEnabled*` not populated in pings

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#56216]
The [MonitorsEnabled*](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@6a8f5907de6406df4276c3796c112d9f7bb32ff2/-/blob/internal/types/types.go?L1819) fields of the code monitor pings are not being populated, so are consistently reporting 0. The query will need to be updated to collect these fields

**Comment by jasonhawkharris** [comment]
This is the query that needs to be updated: https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@6a8f5907de6406df4276c3796c112d9f7bb32ff2/-/blob/internal/usagestats/code_monitoring_usage_stats.sql

**Comment by jasonhawkharris** [comment]
PR: https://github.com/sourcegraph/sourcegraph/pull/56392
