### ISSUE TITLE
JetBrains: Fetch embedding status through the agent

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#56221]
We currently have a regression in the footer of the chat sidebar because we switched to the agent but not getting the necessary info from there.

Rough tasks to fix this:
- [ ] Add new endpoint to the protocol for requesting embedding status
- [ ] Hook it up on the agent side
- [ ] Call it from the client side
- [ ] Test it with the possible statuses

**Comment by vdavid** [comment]
Hint for adding the endpoint, from @olafurpg: we need to add a new graphql/SOMETHING to the list [here](https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/agent/src/protocol.ts?L38) and implement it like [this](https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/agent/src/agent.ts?L212)

**Comment by olafurpg** [comment]
Fixed in https://github.com/sourcegraph/sourcegraph/pull/56636
Fixed in https://github.com/sourcegraph/sourcegraph/pull/56584
