### ISSUE TITLE
Incorrect query results?

### ISSUE THREAD

**Issue by tim-neo** [sourcegraph/sourcegraph#56224]
- **sourcegraph.com** 
- **Macos Ventura 13.2.1, Chrome Version 116.0.5845.110 (Official Build) (arm64)** 

#### Steps to reproduce:

1. type in the search field has "context:global mock.*<redacted node module>"
2. click ".*" to enable regex
3. search
4. note the summary says "3 results", but the page shows only 2 (unexpeced; expected the number of results to match the summary)
5. note the results are different from my colleague in the same org when he executed the same search a minute later and retrieved many results

#### Expected behavior:
1. The number of results in the summary and shown below it match
2. The results are the same between my colleague and I who are in the same org

#### Actual behavior:
1. The number of results shown is 2, but the summary reports 3 results
2. My colleague's screen shows many more results when he executes the same search

If you would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are no [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

**Comment by jdorfman** [comment]
Hey @tim-neo thanks for reaching out. In this case, it would be better to reach out to support so they can ask troubleshooting questions without fearing anything sensitive being exposed here on GitHub. 

If you would like here, please feel free to reopen this issue. Thanks!
