### ISSUE TITLE
JetBrains: Early chat questions get no response

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#56233]
Edge case: If I’m asking Cody something within the five seconds the sidebar loads, I’m getting no response. The first “Hi” in this screenshot was right after IDE start, the second 5–10 sec later.

![image](https://github.com/sourcegraph/sourcegraph/assets/2552265/495b5c08-e653-421e-a95d-e601fe9d8f06)

@olafurpg: "`Chat` should be awaiting for the agent connection to establish via `getInitializedServer`. This sounds like a bug caused by sending the chat message before the connection gets established."

**Comment by olafurpg** [comment]
Closing as wontfix
