### ISSUE TITLE
JetBrains: Try streaming autocompletions

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#56234]
Idea: Display streaming results for autocompletions.
The IntelliJ SDK gives us enough freedom to do this. The UI would definitely feel more responsive, and I imagine it could look rad.

Why:
- For the user to know what’s going on
- To read the code while waiting
- Might contribute to a viral effect because it looks cool

Limitation: The _first_ line shouldn't be streamed if completing mid-line because we might reject the suggestion if it clashes with the end of the line.

Also, we are aware that Copilot doesn't do this, and we know that this might be a result of trial and rejection, but might also happen that they just haven't tried this.

**Comment by olafurpg** [comment]
Closing as wontfix
