### ISSUE TITLE
JetBrains: The web view doesn’t load with older IntelliJ versions

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#56231]
The “Find with Sourcegraph” (⌥S) web view doesn’t load with IntelliJ IDEA 2022.1 CE (Build #IC-221.5080.210).
It’s stuck in a loading state.

Screenshot:
![image](https://github.com/sourcegraph/sourcegraph/assets/2552265/7fef6545-3a0c-416f-ab0f-ff2e80df8e39)

**Comment by olafurpg** [comment]
Closing as wontfix. https://github.com/sourcegraph/sourcegraph/pull/56625
