### ISSUE TITLE
S: (low priority, post-close) Allow enabling LLM proxy through IntelliJ

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#56254]
> having a way to enable the proxy in that sg/socks-proxy branch without having to create a separate build / switch branches, would be super helpful

https://sourcegraph.slack.com/archives/C05JDP433DL/p1692980157982769?thread_ts=1692965207.330429&cid=C05JDP433DL

**Comment by cbart** [comment]
I've been still hitting 403 forbidden on sg/socks-proxy. For some reason the traffic (when running VS Code, not agent) is going around the proxy.

**Comment by taras-yemets** [comment]
- https://github.com/sourcegraph/sourcegraph/pull/56264
- https://github.com/sourcegraph/cody/pull/836
