### ISSUE TITLE
"Cody on self-hosted Sourcegraph" without the Enterprise part?

### ISSUE THREAD

**Issue by wadabum** [sourcegraph/sourcegraph#56268]
Following https://docs.sourcegraph.com/cody/faq#does-cody-work-with-self-hosted-sourcegraph
> Yes, Cody works with self-hosted Sourcegraph instances [...]

and https://docs.sourcegraph.com/cody/overview/enable-cody-enterprise#cody-on-self-hosted-sourcegraph-enterprise
> Prerequisites
> - Sourcegraph 5.1.0 or above
> - A Sourcegraph Enterprise subscription with [Cody Gateway access](https://docs.sourcegraph.com/cody/explanations/cody_gateway), or [an account with a third-party LLM provider](https://docs.sourcegraph.com/cody/overview/enable-cody-enterprise#using-a-third-party-llm-provider-directly).  

### Is this "or" part broken?  
**Or is this a payment-required thing?** (stumbled across https://github.com/sourcegraph/sourcegraph/issues/52903 and https://github.com/sourcegraph/sourcegraph/pull/52933 doesn´t appear to have any bypass?)

Issue being: to my understanding all functionality should be there when selfhosting and providing your own OpenAI-Keys for free.
yet the /cody page remains stuck on "Learn more about Cody → or enable it now."
and the sidebar-widget is also stuck on "Cody is disabled on this instance".

Installed via setup-script,
Version 5.1.7
Site-Config:
```
{
  "auth.providers": [ { "type": "builtin" } ],
  "externalURL": "https://sourcegraph.myorg.com",
  "executors.accessToken": "REDACTED",
  "codeIntelAutoIndexing.enabled": true,
  "cody.enabled": true,
  "completions": {
    "provider": "openai",
    "chatModel": "gpt-4",
    "fastChatModel": "gpt-35-turbo",
    "completionModel": "gpt-35-turbo",
    "accessToken": "REDACTED"
  },
  "embeddings": {
    "provider": "openai",
    "accessToken": "REDACTED",
    "excludedFilePathPatterns": [],
    "maxCodeEmbeddingsPerRepo": 3072000,
    "maxTextEmbeddingsPerRepo": 512000,
  }
}
```

I could create embeddings using the admin gui that made it all the way to "COMPLETED Completed embedding 518 files (554 skipped) about 1 hour ago" - so my API-Key is fine, (and yes it also does have gpt-4 access unlocked)

**Comment by wadabum** [comment]
Any feedback here if that is expected behavior or not?

**Comment by wadabum** [comment]
*bump* issue still persists

**Comment by epinnock** [comment]
Hi @wadabum @jdorfman  I'm also seeing the same issue. Is Cody not supported in the single instance self-hosted. If not is it supported in the docker compose version?

**Comment by jdorfman** [comment]
Thanks @epinnock 

@MaedahBatool your thoughts?

**Comment by pxz2016** [comment]
@wadabum @epinnock 
Is there a conclusion?

**Comment by epinnock** [comment]
@pxz2016 No it looks like this is not possible with the community version

**Comment by leijun507** [comment]
@epinnock If that's the case, what's the point of open source?

**Comment by pxz2016** [comment]
> @pxz2016 No it looks like this is not possible with the community version
@epinnock If that's the case, what's the point of open source?
