### ISSUE TITLE
web: Cannot add Sourcegraph as search engine to Firefox on sourcegraph.sgdev.org

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#5627]
- **Sourcegraph version:** sourcegraph.sgdev.org
- **Platform information:** macOS, Firefox, extension pointing to sourcegraph.sgdev.org

#### Steps to reproduce:

1. Go to https://sourcegraph.sgdev.org/search
2. Follow the instructions for Firefox here: https://docs.sourcegraph.com/integration/browser_search_engine#firefox

#### Expected behavior:

Sourcegraph is added as a search engine to Firefox

#### Actual behavior:

I get an error that says: `Firefox could not download the search plugin from:
https://sourcegraph.sgdev.org/opensearch.xml`

But I can manually access the URL.

#### GIF

![search](https://user-images.githubusercontent.com/1185253/65018003-520cca80-d928-11e9-9468-b31ebb8b376d.gif)

---

@lguychard Sorry, I don't know who to assign this to, since I don't know whether this behavior comes from the browser extension or not.

**Comment by lguychard** [comment]
Thanks for reporting! This does not come from the browser extension, but rather from the opensearch endpoint. Regardless, I think the web team is the right assignment here.

**Comment by muratsu** [comment]
Seems like this issue persists. Re-opening to investigate
