### ISSUE TITLE
auth.accessTokens UI experience changed

### ISSUE THREAD

**Issue by uwedeportivo** [sourcegraph/sourcegraph#5630]
this is from test grid item 8.4.1:

test plan:
https://docs.google.com/document/d/1B9bFwg1dx5qRJbrL0CEwZCv3eEanN2yHYJvcAPpaCR8/edit#heading=h.etllq...

it works but not exactly as described

non-admin user still gets the "Access token" UI even if access tokens have been turned off for non-admin users. the creation itself is prevented though

<img width="1154" alt="image" src="https://user-images.githubusercontent.com/534011/65052816-deff5600-d91f-11e9-8c95-d587db61f0ac.png">

**Comment by lguychard** [comment]
I verified that this behaviour was already present as far back as 3.4.0.

Additionally, the intention in the code has been to hide the tab only when `"allow": "none"` for a long time: https://sourcegraph.sgdev.org/sourcegraph/sourcegraph@c3497068e4c0dc6309c164d4b084c1ea9365cdec/-/blob/web/src/user/settings/sidebaritems.ts#L30

I think that this is an issue with the test plan (3.a copy/pasted from 2.a).

**Comment by uwedeportivo** [comment]
👍 i should have thought of doing that
