### ISSUE TITLE
5.1.8 Security approval

### ISSUE THREAD

**Issue by DaedalusG** [sourcegraph/sourcegraph#56397]
Security must close this issue before releases. It is the responsibility of the Security Engineer on rotation the week the release is cut. More steps will be added in the future.

- [ ] All feasible CVEs are closed.
- [ ] Any open CVEs are documented in the handbook.

cc @sourcegraph/security

**Comment by mohammadualam** [comment]
v5.1.8-rc.1 is the published image

**Comment by mohammadualam** [comment]
no new CVEs found.
