### ISSUE TITLE
[Search Jobs] Adds minimal set of telemetry events 

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#56432]
[Figma spec](https://www.figma.com/file/H4ezuXmEvVeoC6UaiNSbEa/Exhaustive-search-UI?type=design&node-id=1715-5918&mode=design&t=rUNkox1MFO6sblhZ-0)

Events:
- **ExhaustiveSearchFormShown**, Any time this form is shown, this is fired, it is active or inactive based on disabled state.
- **ExhaustiveSearchCreated**, When the exhaustive search form is displayed, show errors.It doesn’t make sense to log these errors when there is no intent shown to run the search. 
- **ExhaustiveSearchFormShown**, Any time this form is shown, this is fired, it is active or inactive based on disabled state.
- **ExhaustiveSearchValidationError**, When the exhaustive search form is displayed, show errors.It doesn’t make sense to log these errors when there is no intent shown to run the search.

**Comment by keegancsmith** [comment]
@vovakulikov this has been done right?

**Comment by vovakulikov** [comment]
Thanks for the catch, yes, it was done here https://github.com/sourcegraph/sourcegraph/pull/56745
