### ISSUE TITLE
Unable to search on non site admin accounts (k8s.sgdev.org)

### ISSUE THREAD

**Issue by kzh** [sourcegraph/sourcegraph#5643]
Search is broken on k8s.sgdev.org (`3.8.0-rc.2`) for unprivileged accounts. 

~On my local instance (98 repos), searches are hanging (infinite loading spinner). Checking the network tab, the GraphQL request isn't responding.~

On k8s.sgdev.org, the message `Error in GraphQL response: API rate limit exceeded` appears. There was a different one earlier (`Post https://ghe.sgdev.org/api/graphql: context deadline exceeded`).

<img width="1440" alt="Screen Shot 2019-09-17 at 5 14 33 PM" src="https://user-images.githubusercontent.com/3507526/65088727-3b3d9680-d96f-11e9-83eb-554205ddd071.png">
<img width="1440" alt="Screen Shot 2019-09-17 at 5 14 43 PM" src="https://user-images.githubusercontent.com/3507526/65088733-3ed11d80-d96f-11e9-9e2d-12ed5426e092.png">

#### Steps to reproduce:
1. Visit k8s.sgdev.org on a non site admin account (can use {zoom, office}@sourcegraph.com).
2. Search for 'a'.

This can also be reproduced in the API console using an unprivileged account.
```graphql
query {
  repositories(first: 1) {
    nodes {
      name
    }
  }
}
```

**Comment by unknwon** [comment]
I'm not able to reproduce on my local 3.8.0-rc.2 Docker image, and k8s.sgdev.org is hitting "Error in GraphQL response: API rate limit exceeded" at the moment.

**Comment by unknwon** [comment]
I'm able to test zoom@ account now, got error "Post https://ghe.sgdev.org/api/graphql: context deadline exceeded".

**Comment by kzh** [comment]
This issue resolved itself locally.
