### ISSUE TITLE
JetBrains：Why can't I see the configuration on the tools?

### ISSUE THREAD

**Issue by elephant5** [sourcegraph/sourcegraph#56465]
I installed the plugin, but there is no menu available in IDEA？

**Comment by olafurpg** [comment]
Thank you for reporting! In the upcoming 3.1.0 release, the settings are not under Tools > Sourcegraph & Cody



![Image](https://github.com/sourcegraph/sourcegraph/assets/1408093/5b71e0fd-5427-465f-8f8a-b9146d301159)
