### ISSUE TITLE
JetBrains: Add tooltip promoting app when embeddings are not available

### ISSUE THREAD

**Issue by danielmarquespt** [sourcegraph/sourcegraph#56497]
Should appear on click of the "no-embeddings icon" when connected with SG.com and using a repo with no embeddings

Not sure if the "Refresh plugin" is something we need, but its main purpose is to re-check the connection with app

Figma: https://www.figma.com/file/m9Yvgv6W3aPRLfXnxgwnEz/JetBrains?type=design&node-id=215%3A2737&mode=design&t=Xuwan9AcDpBbCRPZ-1

![Image](https://github.com/sourcegraph/sourcegraph/assets/7814431/c549138f-a936-4aa2-a32c-3aa20ac1ade5)

**Comment by taylorsperry** [comment]
@olafurpg @danielmarquespt Closing this issue given our decision [here](https://sourcegraph.slack.com/archives/C059N5FRYG3/p1695229216563929).
