### ISSUE TITLE
JetBrains: no way to disable auto-scroll for chat

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#56494]
Currently, the scroll behavior of the chat window feels annoying. My expectation is:

* Auto-scroll when the window is scrolled to the bottom or I send a new message
* Don't auto-scroll if I scroll up the window. Even if Cody is streaming new messages, I want to be able to disable auto-scroll

**Comment by Sa1to** [comment]
Here is outcome of my research so far:

In order manage user scrolling, in class [ChatScrollPane.java](https://github.com/sourcegraph/sourcegraph/blob/main/client/jetbrains/src/main/java/com/sourcegraph/cody/chat/ChatScrollPane.java) you have to use `MouseWheelListener` and `MouseAdapter`.

Main problem is that components added to `ChatScrollPane` are causing viewport to display them whenever updated.

I was trying to override `scrollRectToVisible` method on those added component but it wasn't effective.
