### ISSUE TITLE
Bug: Git Blame Will Occassionally Throw Sourcegraph Into A Retry Loop For A Bad URL 

### ISSUE THREAD

**Issue by alexAtSourcegraph** [sourcegraph/sourcegraph#56555]
- **Sourcegraph version:** 5.1.5
- **Platform information:** 
Chrome on Ubuntu and Safari on macOS

GitLab Code Host
#### Steps to reproduce:

1. Go to a random file in a very large git repository (not sure the large is needed but that's where it was found)
2. Click git blame
3. Modify the URL so it's invalid

#### Expected behavior:

2. An error page for an invalid file without an extended retry 

#### Actual behavior:

An error page for an invalid file does occur  but about 10% of the time there are also requests for git blame on the invalid file in the background.

The requests look like this:

`10.198.198.109 - - [07/Sep/2023:18:57:11 +0000] "GET /.api/blame/gitlab.domain.com/core/main/stream/dist/partner/service[ HTTP/1.1" 500 133 "https://sourcegraph.domain.com/gitlab.domain.com/core/main/-/blob/dist/partner/service[" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" "-"`

**Comment by pjlast** [comment]
This doesn't seem to be relevant anymore. The frontend still does the blame request, but it returns a 404 instead of a 500, which is expected. Overall I don't think it matters to much, since these requests are run in parallel.
