### ISSUE TITLE
JetBrains: collapse advanced account settings by default

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#56572]
Currently, the form to create an account looks like this

![Image](https://github.com/sourcegraph/sourcegraph/assets/1408093/9fba58a6-45f9-4a15-a3fa-18be71f71def)

We may add more advanced settings in the future, like custom URL for autocomplete provider. We should collapse advanced settings by default because most users don't need to use these advanced settings.

**Comment by mkondratek** [comment]
What particular settings are considered advanced? I cannot distinguish them looking into the dialog/code 😕 Can you precise this please @olafurpg 🙏

**Comment by mkondratek** [comment]
headers are only advanced for now
