### ISSUE TITLE
blobstore: Uploadstore loads aws config for blobstore config

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#56599]
reported by @daxmc99 here: https://sourcegraph.slack.com/archives/C04MYFW01NV/p1694631549255759

When some broken aws config is set in the environment, blobstore tries to pick it up and the uploadstore initialization blows up. We should never read the aws config from the default chain in that case.

Not sure who owns this so assigning to source for now.  

/cc @sourcegraph/source

**Comment by daxmc99** [comment]
To replicate, create an AWS credential file in `~/.aws/credentials` with a value like this:
```
[default]
aws_access_key_id=TACO
```
