### ISSUE TITLE
JetBrains: persistent chat history

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#56621]
Currently, your JetBrains chat history is lost when you restart the IDE or start a new chat. It would be nice if supported persistent history like VS Code does

![Image](https://github.com/sourcegraph/sourcegraph/assets/1408093/4b526c12-32b0-4c3e-9c53-6eec2ac22333)

**Comment by olafurpg** [comment]
Open questions before we invest in implementing this feature:

- How much is this feature used in VS Code?
- How should the design look like in JetBrains?

**Comment by exigow** [comment]
Is this a duplicate of https://github.com/sourcegraph/jetbrains/issues/119?

**Comment by dominiccooney** [comment]
This issue has been fixed, use the chat history tab of the Cody tool window.
