### ISSUE TITLE
JetBrains: fix message about repository not existing on Sourcegraph

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#56627]
The warning should say the repository doesn't have embeddings enabled.

![Image](https://github.com/sourcegraph/sourcegraph/assets/1408093/c9086620-6bd4-4286-871f-d75f829f8599)

**Comment by tanmoysrt** [comment]
Hi @olafurpg ! I like to work on this issue. Can you assign me the issue?
