### ISSUE TITLE
Database migration (user_external_accounts table) fails to encrypt all tables due to NULL value error

### ISSUE THREAD

**Issue by Rhia2** [sourcegraph/sourcegraph#56630]
- **Sourcegraph version:** old to 5.1.6
Reported by: https://github.com/sourcegraph/accounts/issues/6716 via [Slack](https://sourcegraph.slack.com/archives/D03RL9LBQKS/p1688731378151829)

Brief Description
The issue was database encryption failing to complete in their dev environment. The external_services table was fully encrypted, but user_external_accounts only reached 10.3% before erroring out.

Error: sql: Scan error on column index 2, name "auth_ data": converting NULL to string is unsupported

![image](https://github.com/sourcegraph/sourcegraph/assets/32063636/7ae17a60-17fa-4404-a8f5-d457a1c06d13)

The error message pointed to a problem converting NULL values to string during encryption in the auth_data column of the user_external_accounts table.

We did an Initial check by running SELECT * FROM user_external_accounts WHERE auth_data IS NULL, which showed around 26 rows with NULL auth_data.

This confirmed the root cause - NULL values in the auth_data column that failed to convert during encryption.

Confirmed from the schema that the auth_data is nullable, but we aren't checking for nulls when encrypting the table.

#### Steps to reproduce:

Create a record with the auth_data column as null in the user_external_accounts table
Follow this step [here](https://docs.sourcegraph.com/admin/config/encryption#enabling) to encrypt user_external_accounts table

#### Expected behavior:
100% completed

#### Actual behavior:
Stucked at 10.3% and erroring out:
![image](https://github.com/sourcegraph/sourcegraph/assets/32063636/a321dd0b-3a7c-4ef5-8f8a-9fc2abbeb8b8)

If you would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are no [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

/cc @sourcegraph/source

**Comment by airamare01** [comment]
Fixed by https://github.com/sourcegraph/sourcegraph/pull/56595
