### ISSUE TITLE
meta: Notification spam from CODENOTIFY

### ISSUE THREAD

**Issue by indradhanush** [sourcegraph/sourcegraph#56668]
I noticed that the username(s) were removed in https://github.com/sourcegraph/sourcegraph/pull/56199 but I still seem to be getting notifications even though a [quick search](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+indradhanush&patternType=standard&sm=0&groupBy=path) does not return any more references in CODENOTIFY files.

For example [this](https://github.com/sourcegraph/sourcegraph/pull/56661#event-10377445885) was earlier today.

![CleanShot 2023-09-15 at 09 13 32@2x](https://github.com/sourcegraph/sourcegraph/assets/2682729/508173d9-3c16-41ca-a1f6-d75f866042c9)

@eseliger Any chance you could take a look at what's going on with codenotify? Thank you in advance. 😄

**Comment by keegancsmith** [comment]
The 5.1 branch has the old code notify rules, so backporting the fix https://github.com/sourcegraph/sourcegraph/pull/56698
