### ISSUE TITLE
JetBrains: not regocnizing my local Cody App repo

### ISSUE THREAD

**Issue by thomasvangurp** [sourcegraph/sourcegraph#56714]
![Settings_en_probedesign_LGC_–__gitlab-ci_yml](https://github.com/sourcegraph/sourcegraph/assets/1284722/6e513132-4f1e-4997-92dc-744dfec22d26)
and
![Cody_en_WhatsApp-bèta](https://github.com/sourcegraph/sourcegraph/assets/1284722/0c29de29-a517-4aa8-9d7b-d09b455e496a)
see also https://github.com/sourcegraph/app/issues/77

**Comment by olafurpg** [comment]
Thank you for reporting! Closing as wontfix because the JetBrains plugin is not going to need the Cody App in the future to support embeddings for private repositories.
