### ISSUE TITLE
search jobs: Rename db tables from exhaustive -> search_jobs

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#56765]

**Comment by stefanhengl** [comment]
We have decided not to proceed with this. We stick with the name "exhaustive search" internally and only use "search jobs" on the API surface and in the UI. This is to prevent confusion with the query planner, which creates jobs, and jobs in workers.

**Comment by mrnugget** [comment]
Makes sense, good reasoning. I wonder whether there'll be more opportunities then to double-down on the name.
