### ISSUE TITLE
Add a Perforce client in `extsvc`

### ISSUE THREAD

**Issue by peterguy** [sourcegraph/sourcegraph#56782]
Perforce is a bit of a special duck because it needs to use `p4` for all communication with the code host, unlike most/all other sources, which can use HTTP(S) to communicate with the code host

The discussion in PR #56697 made it clear that `PerforceSource` should not assume the availability of `p4`.  #56697 changed the behavior of `CheckConnection`; now `ListRepos` needs similar attention. Currently it uses `PerforceDepotSyncer`, which uses `p4` directly. `ListRepos` may not be used in the same way that `CheckConnection1 is, so it may be ok with this behavior, but it bears examining.

**Comment by eseliger** [comment]
Does https://github.com/sourcegraph/sourcegraph/pull/57119 address this ticket?

**Comment by peterguy** [comment]
As @eseliger commented, #57119 address this issue
