### ISSUE TITLE
Add LOG_LEVEL environment variable to migrator container

### ISSUE THREAD

**Issue by marcleblanc2** [sourcegraph/sourcegraph#56785]
#### Feature request description
Many of our Docker images support the LOG_LEVEL environment container, but Migrator doesn't yet.

Migrator's database connection information should only be output to logs when LOG_LEVEL is set to debug.

#### Is your feature request related to a problem? If so, please describe.
Customer https://github.com/sourcegraph/accounts/issues/8767 is requesting that database connection information does not get output by the Migrator container's logs, so that this information is not forwarded to, and retained in their SEIM system.

#### Describe alternatives you've considered.
No alternatives exist. 

#### Additional context
Slack support [thread](https://sourcegraph.slack.com/archives/C046RLYH3LG/p1692638760585679)
Zendesk support ticket [15312](https://sourcegraph.zendesk.com/agent/tickets/15312)

**Comment by DaedalusG** [comment]
https://github.com/sourcegraph/sourcegraph/pull/56817
^^ Quick fix -- hoping it makes it into `v5.1.9` patch release
