### ISSUE TITLE
Some repositories stuck in "Empty repository" state

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#5684]
On a customer instance I am observing some repositories stuck in an "Empty repository" state refusing to clone from the code host.

**Comment by tsenart** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.9 release is scheduled for tomorrow** at 10:00 CEST.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by tsenart** [comment]
Moving this to Backlog since it doesn't look like it got done in time for 3.9. Please update accordingly otherwise.

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.10 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.11 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by slimsag** [comment]
I believe this is no longer an issue and will re-open if I see it occurring again.
