### ISSUE TITLE
JetBrains: autocomplete is stuck due to authentication issue

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#56880]
Steps to reproduce thanks to @chwarwick in https://sourcegraph.slack.com/archives/C052G9Y5Y8H/p1695255525110969?thread_ts=1695246080.682669&cid=C052G9Y5Y8H

- Setup extension to connect to [sourcegraph.com](http://sourcegraph.com/)
- Verify chat & autocomplete work
- Delete Account
- Restart IDE
- IDE starts and requests to add an account, now I use [sourcegraph.sourcegraph.com](http://sourcegraph.sourcegraph.com/)
- Autocomplete spins forever and the auth error is present in the logs

![Image](https://github.com/sourcegraph/sourcegraph/assets/1408093/3a875324-b175-4f7f-883d-5468a72645dd)

I looked at the JSON-RPC trace and the JetBrains extension is sending the correct notifications. The root problem happens in the agent. Also worth noting that chat is using the correct access token.

**Comment by olafurpg** [comment]
One possible root cause is that we currently send the following `initialize` request after restarting IntelliJ
```
[Trace - 01:00:57 PM] Sending request 'initialize - (1)'
Params: {
  "name": "JetBrains",
  "version": "3.1.0-alpha.10",
  "workspaceRootPath": "/Users/olafurpg/dev/fesh0r/fernflower",
  "extensionConfiguration": {
    "serverEndpoint": "https://sourcegraph.com/",
    "accessToken": "",
```

The `serverEndpoint` should be empty here because the user hasn't configured any account.

**Comment by chwarwick** [comment]
There is an easier way to reproduce this, just starting the extension without any existing accounts.
