### ISSUE TITLE
Allow admins to see Perforce sync logs while cloning

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#56899]
**Requested by:** https://github.com/sourcegraph/accounts/issues/6938

#### Feature request description

`Last sync log` should be visible to administrators for Perforce repositories while cloning.

#### Is your feature request related to a problem? If so, please describe.

The initial clone of a Perforce depot can take a long time.  Administrators often go to the site admin > repositories > repositories page to check on the status.  During the initial clone, all of the actions associated with a repository are grayed out.  It would be nice to allow admins to view (and also watch) the sync log.

#### Describe alternatives you've considered.

Administrators can currently see the _current line_ of the log if you go to the repository page in Sourcegraph.  This is only partially useful as it doesn't show the entire log.

/cc @sourcegraph/source

**Comment by eseliger** [comment]
This issue should be fixed - the settings page is now accessible for site-admins before a repo cloned successfully, giving better insight into the cloning process.

Do note however, that the _last_ sync log is for the _previous_ sync, so it would only be populated after the clone process finished. The p4-fusion binary streams the last log line seen to the UI though which contains progress information, similar to the git line in the below screenshot.

![Screenshot 2024-01-24 at 01 41 04@2x](https://github.com/sourcegraph/sourcegraph/assets/19534377/329485fa-16cd-46d1-a79c-94a910b064a9)

Also see here, the settings UI with all the additional knobs etc is available for this not-yet-done-cloning repo. 

![Screenshot 2024-01-24 at 01 41 21@2x](https://github.com/sourcegraph/sourcegraph/assets/19534377/4268c4bf-3d7f-495b-b360-4aae0813e701)

I hope this addresses the concerns - if not feel free to reopen
