### ISSUE TITLE
p4-fusion is running but Sourcegraph UI is no longer getting log updates

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#56901]
- **Sourcegraph version:** 5.1.7
- **Reported by:** https://github.com/sourcegraph/accounts/issues/6938

#### Overview

We saw a few incidents where `p4-fusion` was running on `gitserver` but the UI is not showing the log output.  Examples
1. `p4-fusion` running for nearly 10 days.  If we look at `git log` output of the associated tmp folder where the git repo is being created, we see a valid git repository but no new updates in days. (No longer active)
2. `p4-fusion` running.  If we look at `git log` output of the associated tmp folder where the git repo is being created, we see a valid git repository _and_ updates happening every few seconds.  (Still actively importing CLs)

In both cases, if we tried to tail the open log file from the running `p4-fusion` process (i.e., tail /proc/{pid of p4-fusion}/fd/1), we don't see anything.  If we do this same thing on other p4-fusion commands, we see output.

/cc @sourcegraph/source

**Comment by eseliger** [comment]
Sourcegraph 5.3 will come with a lot of stability improvements around this process. We didn't find a reliable repro of the above behavior so no 100% guarantee that this will be solved, but we believe that this should help. 

Closing for now, if this is coming up again please reopen :)
