### ISSUE TITLE
GraphQL diagnostics not populated for scip indexers

### ISSUE THREAD

**Issue by matthewnitschke-wk** [sourcegraph/sourcegraph#56904]
- **Sourcegraph version:** 5.1.5 (also replaceable on sourcegraph.com currently)
- **Platform information:** n/a

> [!NOTE]
> This issue was originally reported via discord, where additional context [can be found](https://discord.com/channels/969688426372825169/1153704716556050513/1153704716556050513)

#### Steps to reproduce:

1. Upload a scip file which contains diagnostic information to sourcegraph
2. Run the following gql query within the api console:
    ```graphql
    query {
      repository(name: "some-repo") {
        commit(rev: "some-hash") {
          blob(path: "some/file/path") {
            lsif {          
              diagnostics {
                totalCount
              }
            }
          }
        }
      }
    }
    ```
3. Observe the results of the query

#### Expected behavior:

If the uploaded index contained diagnostic information within it, I would expect that information queryable from the gql api. I would expect `lsif` to be renamed to something indexer agnostic though, but that's a different thing

#### Actual behavior:

`diagnostics` null `nodes` and totalCount is `0` regardless of whether the uploaded data contained diagnostics or not

If you would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are no [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

**Comment by jdorfman** [comment]
Thanks for opening this issue @matthewnitschke-wk

**Comment by varungandhi-src** [comment]
The bug seems to be have been introduced in https://github.com/sourcegraph/sourcegraph/pull/45103, where we added support for diagnostics in SCIP. The queries for SCIP and LSIF are subtly different, causing the SCIP query to fail.

**Comment by matthewnitschke-wk** [comment]
Fantastic! Thanks for looking into this for me @varungandhi-src!

Which release of sourcegraph can I expect this fix in?

**Comment by unknwon** [comment]
> Which release of sourcegraph can I expect this fix in?

5.2.2 (currently scheduled for Nov 1, 2023)
