### ISSUE TITLE
Update product process documentation

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#5692]
These pages should be reviewed to ensure that they reflect our current processes
- https://about.sourcegraph.com/handbook/product

More generally, we need to document how planning works and the relationship between OKRs, roadmap, tracking issues, GitHub issues, and company slides.

**Comment by tsenart** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.9 release is scheduled for tomorrow** at 10:00 CEST.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.10 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.11 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by nicksnyder** [comment]
@christinaforney updated this in https://github.com/sourcegraph/about/pull/412
