### ISSUE TITLE
JetBrains: persist project codebase setting

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#56948]
Currently, `CodyAgentCodebase.{inferredCodebase,explicitCodebase}` are normal string fields that needs to be recomputed every time the IDE restarts. We should persist these values so that they have stable values even after a restart.

https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@63055924b5dff0e458063c5778e3ddd705eaf766/-/blob/client/jetbrains/src/main/java/com/sourcegraph/cody/agent/CodyAgentCodebase.kt?L14-15

**Comment by szymonprz** [comment]
And when do you want to recompute them? Only when they're empty? Does any action in the IntelliJ should recalculate the options? maybe changing the codebase from the embedding status panel?

**Comment by exigow** [comment]
Reopening in response latest revert: https://github.com/sourcegraph/jetbrains/pull/17
