### ISSUE TITLE
JetBrains: Sourcegraph Cody+

### ISSUE THREAD

**Issue by aanokhin** [sourcegraph/sourcegraph#56992]
Inside of IntelliJ IDEA 2023.2.1 (Ultimate Edition):
3.2.0 Plugin doesn't enable Cody context menu
3.3.0-alpha.1  Cody context menu is enabled but doesn't do much any more. No that is incorrect after second restart Cody context menu is disabled in this version as well

It is frustrating, because on the same local folder/project in VSC it works. I guess there are some compatibility issues to be resolved.

**Comment by jdorfman** [comment]
Thanks for reporting @aanokhin. We will dig in

**Comment by taylorsperry** [comment]
Thank you for reporting, @aanokhin, and sorry this got buried! I'm closing since this was before our Beta release and we've had many smaller releases since then, but please let us know if you're still having issues!
