### ISSUE TITLE
cody-gateway: fallback mechanism for when Sentry quota is exceeded

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#57012]
Certain projects in the Sourcegraph sentry org sometimes emit millions of events, consuming our quota and preventing errors from all projects from being received. Cody Gateway depends on Sentry somewhat heavily for monitoring - we need another mechanism, e.g. a log-based metrics, when our Sentry goes down.

/cc @unknwon @eseliger @bobheadxi @efritz @ggilmore

**Comment by rafax** [comment]
We worked around this for now by setting a per-project quota.
