### ISSUE TITLE
No code intelligence hovers on Docker install / internal Gitlab server

### ISSUE THREAD

**Issue by woopla** [sourcegraph/sourcegraph#5704]
Hello,

Using Sourcegraph v3.8.0 in a Docker container.

#### Steps to reproduce:

1. Connect to internal Gitlab instance
2. Specify a large single C++ repo to analyze
3. Install the Sourcegraph extension and connect it to the local Sourcegraph instance
3. Go to a source file and hover on a method

#### Expected behavior:
Hover with _Go to definition_ and _Find references_ appears both on the Sourcegraph webpage and Gitlab.

#### Actual behavior:
No hover appears in either one. The hover appears when clicking on a symbol on the left pane, _Symbols_ tab.

Sorry for the short bug report, I'm open to instructions as to where to look for clues :)

**Comment by woopla** [comment]
(5 minutes later)... Some symbols appear to have that popup working. It's as if the backend is still analyzing the symbols, and many of them do not have the definition/references info just yet.

Could you modify the UI to grey out such symbols in that case? It's confusing to see symbols but not information about.

This repo has 25 years of history and some 14 million lines of C++ code, so I guess it's going to take a little while to analyze. This is fine by me, but I'd like to get insights into the progress. Indexing and mirroring are up-to-date according to the settings page for that repo.

**Comment by unknwon** [comment]
cc @chrismwendt

**Comment by christinaforney** [comment]
Hi @woopla - thanks so much for this feedback! I agree we can do a better job of surfacing what is going on with code intelligence behind the scenes and better set expectations with the person interacting with the UI. I'm going to start thinking about ways to improve this and hopefully start to address this issue in the near future!

**Comment by woopla** [comment]
Thanks for the update @christinaforney!

**Comment by scalabilitysolved** [comment]
@shrouxm @tjdevries feels like we could close this issue out or ask them to try with lsif-clang?

**Comment by macraig** [comment]
Closing as this issue should be solved by running [lsif-clang](https://github.com/sourcegraph/lsif-clang).
