### ISSUE TITLE
Why do so many repo-rev jobs fail with "context canceled"?

### ISSUE THREAD

**Issue by stefanhengl** [sourcegraph/sourcegraph#57070]

**Comment by keegancsmith** [comment]
When we hit limits (eg default match limit of 500) the context is canceled. As a first fix, we need to add in much higher default limits for exhaustive. But after that we need more robust alert handling/reporting. I will do the former now.

Very easy to reproduce, for example

```
repo:^github\.com/sourcegraph/zoekt$@repository-rank-request search
```

You can then download the results and you will see a lovely round number for the number of results found:

```
sqlite> .mode csv
sqlite> .import search-jobs_33_2023-09-27_113937.csv results
sqlite> .schema results
CREATE TABLE IF NOT EXISTS "results"(
"Repository" TEXT, "Revision" TEXT, "File path" TEXT, "Match count" TEXT,
 "First match url" TEXT);
sqlite> select sum("Match count") from results;
500
```
