### ISSUE TITLE
Tracking Issue: Flaky CI builds

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#5721]
In the past few weeks we've seen a lot of CI failures that were fixed with simple retries. In other words: they're flaky.

Flaky tests & builds lead to a lot of noise, which leads to us to losing confidence in our tests & builds, which leads to us ignoring them. Let's fix them.

#### Plan

As a first step, we stop those flaky builds from disappearing in Buildkite and Slack and use this issue to catalog flaky CI failures (those that were fixed by retrying them).

That makes them not only more visible, but also easier to classify (do e2e tests fail? linters? infrastructure?) and thus hopefully easier to fix.

Then we try to fix them and check them off in this list.

#### Flaky builds

| # | Failing CI step | Reason for failure | Fix | Builds |
| - | --------------- | ------------------ | ----- | ------------- |
| 0 | ~e2e tests~       | ~Login failed~       | [PR #5711](https://github.com/sourcegraph/sourcegraph/pull/5711) | [Link](https://buildkite.com/sourcegraph/sourcegraph/builds/43598#a0be2ad6-0cab-4ff2-a443-2ea58b1edb09) |
| 1 | ~`golangci-lint`~ | ~A warning? Or `agent lost`?~  buildkite-agents OOM     |  Most likely: https://github.com/sourcegraph/infrastructure/pull/1652  | [43568](https://buildkite.com/sourcegraph/sourcegraph/builds/43568#0a2058a8-5ee6-431c-bc3a-e04ca0cb3b6c), [44421](https://buildkite.com/sourcegraph/sourcegraph/builds/43421#0d48d263-39a8-4867-b1cb-2453a896e1f8), [43333](https://buildkite.com/sourcegraph/sourcegraph/builds/43333#3ce4d0d4-5033-4430-abb0-4846a0760a59), [42891](https://buildkite.com/sourcegraph/sourcegraph/builds/42891#98ae16a5-db43-4faf-a957-4850c6834083), [43639](https://buildkite.com/sourcegraph/sourcegraph/builds/43639#9aee4368-5bdd-4a53-b409-c908d9a18a22) |
| 2 | ~`golangci-lint`~ | ~"Error return value not checked" - did not pop up in PR build~ |  It didn't pop up in PR build, because on master golangci-lint was passed the correct rev. Not a flake. | [43420](https://buildkite.com/sourcegraph/sourcegraph/builds/43420#c630897c-18f7-49bf-a29f-52de6a4ec497)
| 3 | `go generate`   | `build output "/buildkite/builds/buildkite-agent-5898f757cb-hbk2l-1/sourcegraph/.golang/sourcegraph/bin/server" already exists and is not an object file` | Could be fixed by fix for **1**, since OOM error prevented build cleanup from happening | [43411](https://buildkite.com/sourcegraph/sourcegraph/builds/43411#19d61534-dacd-42ce-97e4-025036bab77f) |
| 4 | `./dev/check-all.sh` | `./todo-security.sh: No such file or directory` | - | [43198](https://buildkite.com/sourcegraph/sourcegraph/builds/43198#8e5537cf-107c-44cf-a53c-6aef78d938ce), [43366](https://buildkite.com/sourcegraph/sourcegraph/builds/43366#2673063c-1517-40cb-b4e9-d003b18f5e6b), [44936](https://buildkite.com/sourcegraph/sourcegraph/builds/44936#cf9350ea-28fb-4dda-b4aa-31dd4b76ed76) |
| 5 | e2e tests | themes did not load (reported in logs that repos are not found) | - | [43747](https://buildkite.com/sourcegraph/sourcegraph/builds/43747#b2fd9347-df48-4653-91a7-58d22131fa10)
| 6 | e2e tests | `Saved searches › Save search from saved searches page` | - | [43824](https://buildkite.com/sourcegraph/sourcegraph/builds/43824#de072e07-b59d-483f-8a2c-748d899f9dd7)
| 7 | e2e tests | `Repository component › symbol sidebar › displays valid symbols at different file depths for Go (./examples/cmd/webapp-opentracing/main.go.go)` | - | [43827](https://buildkite.com/sourcegraph/sourcegraph/builds/43827#d6c7437b-498f-4f9a-8e54-7681315cab02)
| 8 | ~e2e tests~ | ~http://localhost:7080 was not accessible within 60s~ | Fixed https://github.com/sourcegraph/sourcegraph/pull/5960 | [43896](https://buildkite.com/sourcegraph/sourcegraph/builds/43896#1d8940b1-0af5-4270-9a20-5ddc2b50f6f9), [44308](https://buildkite.com/sourcegraph/sourcegraph/builds/44308#38daa7d5-5aed-431d-879c-09cd544acdae/77-688), [44309](https://buildkite.com/sourcegraph/sourcegraph/builds/44309#e07b3848-041c-49cd-8a5c-da8370a51c19/84-124), [44603](https://buildkite.com/sourcegraph/sourcegraph/builds/44603#7713a5dc-0b56-4c2d-a931-ec0274084fd6), [44859-1](https://buildkite.com/sourcegraph/sourcegraph/builds/44859#be1be08d-8518-4106-96f3-75a87a6a2faf), [44859-2](https://buildkite.com/sourcegraph/sourcegraph/builds/44859#00d7f6eb-1e30-4c99-892c-36355232c448) |
| 9 | e2e tests | `http://localhost:7080 was not accessible within 60s.` | Seems like it wasn't fixed by **8** | [45931](https://buildkite.com/sourcegraph/sourcegraph/builds/45931#dcaa554d-7749-42f5-b33b-9f55410a880f), [46347](https://buildkite.com/sourcegraph/sourcegraph/builds/46347#13a4338b-f073-42b8-986a-0075154e2ace)
| 10 | e2e tests | `e2e test suite › Visual tests › Search results file` | | [46136](https://buildkite.com/sourcegraph/sourcegraph/builds/46136#29092529-c73b-462a-adb4-7706f993c6ca), [46532](https://buildkite.com/sourcegraph/sourcegraph/builds/46532#959f3012-6b61-48f1-b04f-1059369a3470)
| 11 | e2e tests | `e2e test suite › Repository component › hovers › Blob › jump to definition › noops when on the definition` | | [46055](https://buildkite.com/sourcegraph/sourcegraph/builds/46055#3340f838-97a6-4435-8317-b47dec906516) 
| 12 | e2e tests | `e2e test suite › Repository component › rev resolution › updates rev with switcher` | | [45917](https://buildkite.com/sourcegraph/sourcegraph/builds/45917#6326a997-9612-4848-a568-40210afceda0) failed.
| 13 | e2e tests | `e2e test suite › Repository component › hovers › Blob › gets displayed and updates URL when clicking on a token` and `e2e test suite › Repository component › hovers › Blob › gets displayed when navigating to a URL with a token position` | | [46176](https://buildkite.com/sourcegraph/sourcegraph/builds/46176#52a963e1-06ed-4306-94e8-58849bcec7f2)
| 14 | `symbols` test | `FAIL: TestSearch/0 > search_test.go:205: {foo false false false  [] false false 0 true false} failed: non-200 response: code=503 body=context deadline exceeded` | | [46932 (failed)](https://buildkite.com/sourcegraph/sourcegraph/builds/46932#c68e95fd-3d8d-4b45-89cc-c88a4e9213ba), [46944 (passed - same commit)](https://buildkite.com/sourcegraph/sourcegraph/builds/46944#3b7aa3ca-4815-4bcb-b3ce-f19052df898c)
| 15 | Start Docker image for e2e tests | `Error response from daemon: reference does not exist open /var/lib/docker/tmp/docker-import-163672497/repositories: no such file or directory` |
| 16 | Flaky LSIF tests | BeforeAll failed, _references only returned if dumps visible at tip_ failed     | | [50253](https://buildkite.com/sourcegraph/sourcegraph/builds/50253#481967e3-4147-466d-b716-5a4ef34f11d9) |
| 17 | Flaky eslint test | `dev/ci/yarn-run.sh build-ts all:eslint` fails with module not found | | [50468](https://buildkite.com/sourcegraph/sourcegraph/builds/50468#0a8007d3-46c4-4ab2-a71c-913e31c2e719)
| 18 | e2e tests |`e2e test suite › Campaigns › Create campaign preview for credentials campaign type` | | [#1485](https://buildkite.com/sourcegraph/sourcegraph-e2e/builds/1485#a8d1c4a3-c042-43d3-a212-8f5f0f1d55cd)
| 19 | e2e tests |`e2e test suite  › External services › External service add, edit, delete ` | | [#51680](https://buildkite.com/sourcegraph/sourcegraph-e2e/builds/1544#b6ebbd9e-043f-414d-abac-48be18906927)

**If you run into a flaky build: please add it to this list!**

**Comment by mrnugget** [comment]
Regarding **1**: in every build it says at the bottom `Exited with status -1 (agent lost)` — is that the real reason? That an agent shuts down? Or is that just a symptom?

**Comment by keegancsmith** [comment]
Added new failure not already in list (num 8). It seems sourcegraph was not accessible `http://localhost:7080 was not accessible within 60s`. However, the docker logs indicate frontend was listening. Maybe nginx was having issues?

**Comment by mrnugget** [comment]
> Added new failure not already in list (num 8). It seems sourcegraph was not accessible `http://localhost:7080 was not accessible within 60s`. However, the docker logs indicate frontend was listening. Maybe nginx was having issues?

That happened before, I think. @slimsag [reported nginx not booting up](https://sourcegraph.slack.com/archives/C07KZF47K/p1568363147113900?thread_ts=1567411847.037700&cid=C07KZF47K) for another test run:

> In other words, it took longer than 15s for ✱ Sourcegraph is ready at: http://127.0.0.1:7080 to happen which may or may not be a problem (DB initialization could take 15-20s, so arguably not a problem). The real problem here, though, is that in the 1st run it appears we couldn't talk to the container within 60s of starting it: https://buildkite.com/sourcegraph/sourcegraph/builds/42679#33368b0b-b34b-4a98-898b-120548943b1b/82-121
> > http://localhost:7080 was not accessible within 60s. Here's the output of docker inspect and docker logs:

> This is despite the fact that the logs claim it was indeed listening and running. So why couldn't we contact it?
> nginx didn't start in the first run. Maybe it didn't have enough time to, or maybe it failed to start for some reason?

**Comment by keegancsmith** [comment]
I have no idea what is going on here. It seems like every test failed, but when you watch the test video it does a lot of stuff. Weird part about the test video is it just waits for a long time on the add external services page without doing anything. https://buildkite.com/sourcegraph/sourcegraph/builds/44147#0034e8b8-9749-4c73-b94b-9ffb4559be2e

**Comment by efritz** [comment]
I'm fairly certain [this](https://buildkite.com/sourcegraph/sourcegraph/builds/44181#de6cb61d-53e3-42d3-8a8e-31863b87467c/162-360) counts (rerunning it made the visual test pass).

**Comment by felixfbecker** [comment]
I have another one: https://buildkite.com/sourcegraph/sourcegraph/builds/44338#338b7a75-ab10-4bf3-be88-fb48ff22c24b

@sourcegraph/core-services In the video recording (click on the mp4 file in the artifacts tab), there is a warning shown from creating the external service that looks like it shouldn't happen. And we should also probably abort the test when we get one?

![image](https://user-images.githubusercontent.com/10532611/66252413-ac48c080-e75b-11e9-9300-e1ba8b230074.png)

**Comment by slimsag** [comment]
Uwe ran into problem #8 above here: https://buildkite.com/sourcegraph/sourcegraph/builds/44603#7713a5dc-0b56-4c2d-a931-ec0274084fd6

**Comment by uwedeportivo** [comment]
To give an update on number 8 above: I did spend a couple of hours diving into this, staring at the stack traces and the code.  If more stack traces appear that have the same fingerprints then I'm convinced it's not a coincidence and a io.ReadFull from the DB conn is stuck waiting forever for 5 bytes. go-migrate is trying to acquire an advisory lock and is executing the stmt with a context.Background instead of a context with some timeout. Not sure why pg is not responding and there is no error.

For now though this is speculation and not useful. We have to keep an eye on it and keep populating this issue when the tests fail.

**Comment by efritz** [comment]
> go-migrate is trying to acquire an advisory lock and is executing the stmt with a context.Background instead of a context with some timeout.

Because, by design, advisory locks block forever.

**Comment by uwedeportivo** [comment]
more evidence related to number 8:

https://buildkite.com/sourcegraph/sourcegraph/builds/44859

**Comment by chrismwendt** [comment]
Number 8 could also be caused by our 129 migrations taking more than 30s to apply, triggering the 30s timeout originally intended to catch deadlock due to misuse of config watching.

Considering that sourcegraph/server takes 12s to initialize on my macOS and run 129 migrations, is it all that surprising that CI is timing out at 30s? I mean, should each migration on average run in less than 100ms?

I instrumented the golang-migrate library and confirmed that migrations are taking the majority of the initialization time. https://buildkite.com/sourcegraph/sourcegraph/builds/44905#5cecd17b-197c-4a02-818a-4745ef25b02a/76-113

Would it be such a bad solution to bump the timeout to 60s? After all, we continue to add migrations over time.

More context in [Slack](https://sourcegraph.slack.com/archives/C07KZF47K/p1570754492058000?thread_ts=1570556984.178400&cid=C07KZF47K).

**Comment by ggilmore** [comment]
Added a new row - a flaky symbols test

**Comment by felixfbecker** [comment]
I see this one _a lot_ on PRs recently:

```

[2019-12-01T12:26:51Z] + env DOCKER_HOST=tcp://dind:2375 'DOCKER_PASSWORD=Mm5F8BORRH*8mQxgO3vOng1f9vyn5T' DOCKER_USERNAME=sourcegraphci docker save sourcegraph/server:49536_2019-12-01_ae89b6e_candidate
--
  | [2019-12-01T12:26:51Z] + docker load
  | [2019-12-01T12:26:51Z] Error response from daemon: reference does not exist
  | [2019-12-01T12:26:51Z] open /var/lib/docker/tmp/docker-import-163672497/repositories: no such file or directory
```

https://buildkite.com/sourcegraph/sourcegraph/builds/49536#dd26210e-abb0-4d54-be7f-7bea7866580f/55-56

**Comment by felixfbecker** [comment]
@sourcegraph/code-intel Flaky LSIF tests: https://buildkite.com/sourcegraph/sourcegraph/builds/50253#481967e3-4147-466d-b716-5a4ef34f11d9

**Comment by mrnugget** [comment]
@sourcegraph/web Flaky `dev/ci/yarn-run.sh build-ts all:eslint`: https://buildkite.com/sourcegraph/sourcegraph/builds/50468#0a8007d3-46c4-4ab2-a71c-913e31c2e719

**Comment by felixfbecker** [comment]
@sourcegraph/core-services flaky `go-test`: https://buildkite.com/sourcegraph/sourcegraph/builds/50521#3bb6458d-a3f3-444f-950c-626b3125a156

**Comment by keegancsmith** [comment]
> @sourcegraph/core-services flaky `go-test`: https://buildkite.com/sourcegraph/sourcegraph/builds/50521#3bb6458d-a3f3-444f-950c-626b3125a156

@rvantonder test failure is in replacer. Looks like we just have a low timeout somewhere and CI can be overloaded.

```
replace_test.go:71: {func derp .go } failed: non-200 response: code=503 body=context deadline exceeded
```

**Comment by rvantonder** [comment]
Yes, [as per comment](https://sourcegraph.slack.com/archives/CMMTWQQ49/p1575968239372000), this is surprising, since it's a timeout on the archive fetch `500ms`, which is [the same](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@8248533108ae3f47bd5fcb451b3912a4f0152e0a/-/blob/cmd/replacer/replace/replace_test.go#L67) as the one used in searcher tests, and has never triggered before. As a preemptive measure it may make sense to bump the time for [search_test.go](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@d501db0/-/blob/cmd/searcher/search/search_test.go#L201) as well.

**Comment by rvantonder** [comment]
I updated tests to be more robust, and the PR build passes. After merging into master, the change I made apparently triggers a build failure: https://buildkite.com/sourcegraph/sourcegraph/builds/50601#ead17d68-c6f3-4da4-8a57-5d303a977825. I don't know why making the tests more robust cause them to be more flaky.

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.11 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by sqs** [comment]
Flaky e2e test failure at https://buildkite.com/sourcegraph/sourcegraph-e2e/builds/929#e08ad8d5-cf42-4897-bf08-2a5ca70fccd4 just now

**Comment by sqs** [comment]
Skipped flaky LSIF tests, issue to reenable them in https://github.com/sourcegraph/sourcegraph/issues/7208

**Comment by sqs** [comment]
Another e2e flakiness question: https://github.com/sourcegraph/sourcegraph/issues/7212

**Comment by mrnugget** [comment]
One of the Automation e2e tests seems to be flaky: https://buildkite.com/sourcegraph/sourcegraph-e2e/builds/1485#a8d1c4a3-c042-43d3-a212-8f5f0f1d55cd

Restarting fixed it after the first test run timed out. cc @eseliger

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.12 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by felixfbecker** [comment]
Saw this one multiple times now:

![image](https://user-images.githubusercontent.com/10532611/73071758-eb8a5100-3eb3-11ea-8b0a-eea3a3a56dd8.png)

**Comment by felixfbecker** [comment]
@sourcegraph/core-services this seems to be a backend issue if I'm not mistaken. Is the registration of external service types somehow async? Or how could the properties not be accepted?

![image](https://user-images.githubusercontent.com/10532611/75727501-5e71bd80-5ce5-11ea-9e58-fb62c4dee366.png)

https://buildkite.com/sourcegraph/e2e/builds/6568#c5762214-eff6-4a06-bbd9-acb05b0fca1e/160-302

**Comment by eseliger** [comment]
it feels like a webapp issue, reporting the wrong `type` of external service to add 🤔 Look at the monaco editor, it also shows validation errors on the json, so apparently the passed json schema is also for another type of service

**Comment by mrnugget** [comment]
> it feels like a webapp issue, reporting the wrong `type` of external service to add 🤔 Look at the monaco editor, it also shows validation errors on the json, so apparently the passed json schema is also for another type of service

Correct. It looks like it's trying to create an AWS Code Commit external service (which is the config it used) but chose Bitbucket Server instead (which is where the validation errors come from)

**Comment by felixfbecker** [comment]
I see, makes sense. I hope that #8789 fixed it.

**Comment by felixfbecker** [comment]
Another one I saw in https://buildkite.com/sourcegraph/e2e/builds/6757#70a76c53-9e0b-4f56-952f-f83993575868 seems to be a backend issue though:

![image](https://user-images.githubusercontent.com/10532611/75895998-b10ebf00-5e36-11ea-98d8-ea69bfc5011f.png)

**Comment by mrnugget** [comment]
I'm wondering if that ☝️ has something to do with me and @eseliger debugging our Bitbucket Server instance, because I've also seen it locally.

**Comment by slimsag** [comment]
@sourcegraph/distribution will own fixing this by introducing CI infrastructure which ensures the underlying infrastructure is never to blame (but we will not fix the e2e tests themselves if they are real failures, or flakiness not caused by the underlying infrastructure).

Please continue to post any flaky e2e/regression test builds here (for other general flaky CI builds, please file separate issues)

**Comment by nicksnyder** [comment]
Another flake that appears to be infra: https://buildkite.com/sourcegraph/sourcegraph/builds/68627#b2022ea7-6603-4d6d-b246-cdd98a9a05e2

**Comment by pecigonzalo** [comment]
I believe we can close this issue as it has become stale given the work done in https://github.com/orgs/sourcegraph/projects/90 and https://github.com/orgs/sourcegraph/projects/72.
