### ISSUE TITLE
'Export Search Results' Fails for Long Queries on Windows

### ISSUE THREAD

**Issue by morgangauth** [sourcegraph/sourcegraph#57270]
- **Sourcegraph version:** 5.0.2
- **Platform information:** Windows

#### Steps to reproduce:

1. Search using a query >~230 characters long on a Windows Operating System
> Sample query: `context:global (repo:^github\.com/sourcegraph/sourcegraph$ OR repo:^github\.com/sourcegraph/sourcegraph-jetbrains$ OR repo:^github\.com/sourcegraph/prototools$ ) count:all (lang:Java OR lang:Python OR lang:C++ OR lang:JavaScript) select:file 
`
3. Go to Actions > Export Results

#### Expected behavior:
The search results will download with the query included in the file name.

#### Actual behavior:
In Windows OS: queries which cause the file name to exceed 255 characters will cause the download to fail.
In MacOS: OS automatically truncates the file name to be <255 characters and the file downloads as expected.
![image](https://github.com/sourcegraph/sourcegraph/assets/113058716/fc5c50c6-7191-491f-9a2c-6c549bd0e45f)

If you would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are no [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

/cc @sourcegraph/code-search

**Comment by morgangauth** [comment]
Occurring at https://github.com/sourcegraph/accounts/issues/7485

**Comment by camdencheek** [comment]
Oh, that's a fun one!

**Comment by camdencheek** [comment]
Confirmed fixed on the latest deployed sourcegraph.com 👍
