### ISSUE TITLE
JetBrains: Cody icon in toolbar looks weird when cody is selected

### ISSUE THREAD

**Issue by szymonprz** [sourcegraph/sourcegraph#57293]
selected Cody in toolbar looks kinda weird

![Image](https://github.com/sourcegraph/sourcegraph/assets/7345368/05f08e17-2397-4dc8-9b8b-a2407da5c3cd)

While other tool windows when selected look like this

![Image](https://github.com/sourcegraph/sourcegraph/assets/7345368/cd8a508b-d599-439d-ba21-c72fe62b8cb6)

**Comment by mkondratek** [comment]
Note: the issue happens in the new UI but it works fine in the old one
