### ISSUE TITLE
p4-fusion: build different binaries for each platform and install it (similar to what we do for universal-ctags)

### ISSUE THREAD

**Issue by burmudar** [sourcegraph/sourcegraph#57307]
The source team in an effort to increase their confidence in p4-fusion will start writing tests that use it. We can build p4-fusion using the nix work @Strum355 did.

Using a similar approach to what was done in `universal-ctags` we can also upload the p4-fusion binary and install/pull it via bazel and `sg setup`

/cc @sourcegraph/source

**Comment by Strum355** [comment]
Work is happening in the https://github.com/sourcegraph/p4-fusion/tree/nsc/nix-build branch, this is likely most convenient given we have a fork (unlike with ctags) and simplifies the GH Actions workflows instead of having the workflow located in https://github.com/sourcegraph/sourcegraph
