### ISSUE TITLE
Extend repo:has.topic() Support to GitLab

### ISSUE THREAD

**Issue by gabtorre** [sourcegraph/sourcegraph#57326]
#### Feature request description

Requested by: https://github.com/sourcegraph/accounts/issues/570

Extend the functionality of the repo:has.topic() filter to support GitLab repository topics.
https://docs.sourcegraph.com/code_search/reference/language#repo-has-topic

#### Is your feature request related to a problem? If so, please describe.

Being able to filter repositories based on topics is crucial for repository management and search workflows. 

#### Describe alternatives you've considered.

Using repo metadata. 

/cc @sourcegraph/search-product

**Comment by camdencheek** [comment]
Thanks for the feature request! I'm going to close it as a duplicate of #56279, which is tracked on our team's board already.
