### ISSUE TITLE
Should zoekt permit ctags binaries not named universal-ctags?

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#57336]
Running Sourcegraph locally with CTAGS_COMMAND set, I get the following error:

```
        OUT: 2023/10/04 11:25:52 indexGitRepo(/Users/erik/.sourcegraph/zoekt/index-1/.indexserver.tmp/github.com%2Fsourcegraph%2Fabout.git, delta=false): build.NewBuilder: ctags.NewParserMap: only supports universal-ctags, not /opt/homebrew/bin/ctags
```

I wonder: Should we be more lenient about the name of the binary? Or is this a security feature? 

/cc @sourcegraph/search-platform

**Comment by keegancsmith** [comment]
I think this is an artifact of when the code was written many years ago and what ubuntu called the ctags binary. Not a security problem, rather trying to prevent a footgun.
