### ISSUE TITLE
JetBrains: missing authentication token but logged in

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#57373]
I've hit on this issue twice, in IntelliJ CE and Goland where it looks like I'm logged in but nothing works (chat/autocomplete). When I open settings I see the root problem, the authentication token is missing

![Image](https://github.com/sourcegraph/sourcegraph/assets/1408093/eed54a60-72e2-48fd-9f81-436d2518d5ad)

We should treat this error as being logged out.
```[tasklist]
### Tasks
- [x] Report notification when the user is missing an access token
- [ ] Display error icon in the status bar whe the user is missing an access token
```

**Comment by mkondratek** [comment]
There is one more thing in this scope:
https://github.com/sourcegraph/jetbrains/issues/38
