### ISSUE TITLE
JetBrains: Random name of cody-agent executable vs firewall

### ISSUE THREAD

**Issue by JorisVanEijden** [sourcegraph/sourcegraph#57405]
## Installation information
 version 3.4.1

The cody-agent executable is recreated with a new random name at every start of the IDE.
This causes issues in creating firewall (or other security software) rules to allow it access to the network.

The executable is created with a new random name here:
https://github.com/sourcegraph/sourcegraph/blame/23290a03216643df74eab3ccedb29d9b6dd0da58/client/jetbrains/src/main/java/com/sourcegraph/cody/agent/CodyAgent.kt#L246

## Steps to reproduce
- configure windows firewall control to prompt for new executables wanting to access the internet
- Start IDE
- get prompt for network access for "Node.js JavaScript Runtime (cody-agent4206361224073132151.exe)"
- allow access
- Restart IDE
- get prompt for network access for "Node.js JavaScript Runtime (cody-agent11870444679388537647.exe)"
- allow access
- Restart IDE
- etc.

## Expected behavior
The cody-agent executable has a fixed name and location so it can be added to the firewall rules.

**Comment by taylorsperry** [comment]
Thanks for reporting this, @JorisVanEijden, and sorry it got buried! I'm closing since this logic has been updated, but please reopen if you're still having this issue.
