### ISSUE TITLE
Improve scip-locals correctness

### ISSUE THREAD

**Issue by SuperAuguste** [sourcegraph/sourcegraph#57419]
Locals in global scopes, identifiers completely unrelated to each other being mixed up - we can probably improve this.

See [this snapshot](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__can_do_go.snap) for example; it's not great :(

I'm not sure if this is actually a problem or not, but it might be worth it to look it.

**Comment by varungandhi-src** [comment]
Closing in favor of https://github.com/sourcegraph/sourcegraph/issues/57791

**Comment by varungandhi-src** [comment]
Sorry, this was a duplicate, so I need to pick the different closing option.
