### ISSUE TITLE
Does Perforce repo-centric syncing not work?

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#57476]
Scheduling a sync on the repo page resulted in no change. Syncing on the user page did. Or I am holding it wrong. Anyways, worth investigating.

/cc @sourcegraph/source

**Comment by pjlast** [comment]
FetchRepoPerms doesn't work with SubRepoPermissions

https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/authz/providers/perforce/perforce.go?L301-304
