### ISSUE TITLE
Allow external service edits is flaky in UI

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#57477]
When looking at the external service page with a mounted external_services JSON file, and allow UI edits set to true, the UI will briefly flash that you can edit but it will reset, but then update and show that it's set to false and no edits are possible. I believe this is an apollo cache issue. 

See video for details: 

https://github.com/sourcegraph/sourcegraph/assets/19534377/e7feeee9-812f-42a3-ad4e-2e1fd8aee9c1

maybe this: https://github.com/sourcegraph/sourcegraph/pull/56366/files#diff-a1881c6ca4481e3d7bc7e96bfc91e2bc53887a131971f16e676628e0f49e565bR23

/cc @sourcegraph/source

**Comment by pjlast** [comment]
Could not replicate this at all, so I'm going to close it unless someone can provide instructions on how to reliably replicate it
