### ISSUE TITLE
Bulk Update and Individual Management of Embeddings

### ISSUE THREAD

**Issue by gabtorre** [sourcegraph/sourcegraph#57499]
#### Feature request description

Requested by https://github.com/sourcegraph/accounts/issues/548

The current system doesn't allow for a bulk update or deletion of embeddings, which results in a significant overhead for users who are iterating configs over many repos.

Bulk Update Feature: A mechanism to forcibly update all embeddings collectively.

Individual Management: The capability to directly update or delete a specific embedding without influencing others.

Auto-indexing index management is attached as an example.

![Screenshot 2023-10-09 at 4 13 04 PM](https://github.com/sourcegraph/sourcegraph/assets/69164745/a61a0646-c613-4c75-9aa3-3af9bf3efc8b)

#### Describe alternatives you've considered.

Manual updates

**Comment by jtibshirani** [comment]
Closing this out as we're not investing in embeddings at the moment.
