### ISSUE TITLE
Prometheus Metrics for the Embeddings Service

### ISSUE THREAD

**Issue by gabtorre** [sourcegraph/sourcegraph#57498]
#### Feature request description

Requested by https://github.com/sourcegraph/accounts/issues/548

In large deployments, we've noticed that understanding the status of embedding jobs can be challenging. 
Having Prometheus metrics can give users a granular and overall view of the embeddings service.
Some useful metrics would be queue status, error rate, processing, etc. Attached are repo-updater and autoindexing metrics as an example.

![Screenshot 2023-10-09 at 2 59 17 PM](https://github.com/sourcegraph/sourcegraph/assets/69164745/c8d83259-dbbc-40e9-9182-34327740019d)
![Screenshot 2023-10-09 at 3 04 10 PM](https://github.com/sourcegraph/sourcegraph/assets/69164745/8c0870e5-1ad5-46e1-b0e2-7de7f994cf68)

#### Describe alternatives you've considered.

Monitoring in the UI.

**Comment by jtibshirani** [comment]
Closing this out as we're not investing in embeddings right now.
