### ISSUE TITLE
GitTreeEntry resolver consumes a lot of CPU and memory

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#57522]
See this graph from S2, but the same applies to dotcom as well. Seems to be quite a deep recursion and a ton of looping in there?

It seems like there are essentially zero tests for this, so maybe we should invest into that as well. 

![Image](https://github.com/sourcegraph/sourcegraph/assets/19534377/854b991e-fee9-4389-a435-75f806a7991e)

/cc @mrnugget

**Comment by mrnugget** [comment]
Do you have an example GraphQL query that produces this?
