### ISSUE TITLE
Disable code monitors on dotcom

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#57539]
@camdencheek proposed disabling code monitors on dotcom because:
- Monitors are a significant source of instability
- Monitors are a major source of resource usage on dotcom
- Monitors are easy to abuse
- Monitors are easy to abandon, forget about, and leave erroring forever
- Monitors are not a good fit for sourcegraph.com

There was general agreement from engineering. 

We are waiting on an email to be sent out announcing the change, then giving people a 2 week window to migrate their monitors before disabling code monitors.

**Comment by camdencheek** [comment]
Done by @eseliger last week

**Comment by eseliger** [comment]
The deprecation plan also mentioned hiding them completely on dotcom (and probably pruning the DB) which I didn't do yet - do we still plan to do that?

**Comment by camdencheek** [comment]
Oh shoot. I thought I had separate issues for those. I can't find them, so I'll re-open this one until that's finished.

**Comment by PatMyron** [comment]
> The deprecation plan also mentioned hiding them completely on dotcom (and probably pruning the DB) which I didn't do yet - do we still plan to do that?

Deleting hosted code monitors with less than a month notice and no way to bulk export seems very B2B SaaS platform unfriendly 

I totally understand prioritizing platform stability through many possible options:

- indefinitely pausing monitors
- limiting number of monitors per account
- ceasing creation of new monitors
- rate-limiting or resource-limiting monitors
- switching hosted monitors from free to paid functionality
- etc.

but hastily deleting them right around a holiday seems unnecessarily burdensome for customers with seemingly no platform stability benefit beyond simply keeping them disabled but viewable

---

(I've worked at places that would pay for hosted code monitoring. Pausing monitoring would leave open that possibility while deleting monitors would probably raise questions on if Sourcegraph is a reliable platform for businesses to build on)

**Comment by camdencheek** [comment]
Hi @PatMyron! Thanks for voicing your concerns. 

> a reliable platform for businesses to build on

To be clear, this change only applies to code monitors on the public sourcegraph.com instance. Code monitors are not being disabled on any instance that anyone is paying for, only on the freely-offered `sourcegraph.com/search`. Every user that will be affected by this was identified and notified via email a few weeks ago.

> no way to bulk export 

All code monitors data can be bulk exported via our GraphQL API. If you'd like help with that, I'd be happy to assist.
