### ISSUE TITLE
Ipython / Databricks notebook support

### ISSUE THREAD

**Issue by sslavian812** [sourcegraph/sourcegraph#576]
#### Question description

Do you have support of databricks and ipython notebooks?

#### Is your question related to a problem? If so, please describe or link to another issue.

I'd like to have a code search across all databricks notebooks in the company. 
Does you code intelligence server support multi-language files (scala, sql, bash, etc.)?
Do you have continuous line numbering across all cells?

I tried to index a scala notebook with some sql code in it, but all non-scala code looks like this:

```
// COMMAND ----------
// MAGIC %sql
// MAGIC describe formatted my_table
  
// COMMAND ----------
```

Is it possible for you language intelligence to treat a cell with `// MAGIC %sql` as sql code and not as a bunch of comments?

**Comment by sqs** [comment]
Currently we don't have any builtin support for multi-language files. However, you could build a [Sourcegraph extension](https://github.com/sourcegraph/sourcegraph-extension-api) that would add support for this.
