### ISSUE TITLE
VSCode Bug report: can not authenticate account

### ISSUE THREAD

**Issue by hi-rustin** [sourcegraph/sourcegraph#57607]
I tried it again and agian. It always failed and reported an error:
```console
Unable to verify your access token for sourcegraph.com. Please try again with a new access token or restart VS Code if the instance URL has been updated.
```

vscode:
```console
Version: 1.83.0
Commit: e7e037083ff4455cf320e344325dacb480062c3c
Date: 2023-10-03T16:13:10.518Z (1 wk ago)
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0
```
sourcegraph
```console
sourcegraph: v2.2.16
```

**Comment by hi-rustin** [comment]
I followed this docs to crate a token: https://docs.sourcegraph.com/cli/how-tos/creating_an_access_token

**Comment by yueyub** [comment]
same here

**Comment by hi-rustin** [comment]
Found a workaround here:
![9c1992da-d584-49c0-b2f3-c8c9349bab0c](https://github.com/sourcegraph/sourcegraph/assets/29879298/a72b3fa1-c0c0-442a-9db9-d325b8ed826e)


Put your token here.

**Comment by willjr** [comment]
> Found a workaround here: ![20240304-110813](https://private-user-images.githubusercontent.com/29879298/309616593-884bdd5a-621e-41a9-aae5-e13116342685.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MDA0ODcsIm5iZiI6MTcxMDkwMDE4NywicGF0aCI6Ii8yOTg3OTI5OC8zMDk2MTY1OTMtODg0YmRkNWEtNjIxZS00MWE5LWFhZTUtZTEzMTE2MzQyNjg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDAyMDMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwMTY4ZmNjZDMzM2YxMWZlNTk1Y2I1ODIwOTkwYjc0ZDY3MzFlNWNlNTY1ODMzNzRiN2ZiMTJiNjUyMjNiNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wPVjdFuin_siEU5mnH5oZPCkaJI5uWCu9uAumnnHaE4)
> 
> Put your token here.

This no longer seems to work for me — though I believe it did a few months ago.
