### ISSUE TITLE
sourcegraph.com shows license expiration in 8 days

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#5763]
![image](https://user-images.githubusercontent.com/1976/65836459-7f437a80-e323-11e9-9d71-186c94ff132d.png)

You can generate a longer-than-1-year license and then use it for Sourcegraph.com to avoid this being a problem each year. (I think we decided not to special-case Sourcegraph.com here, as in "don't enforce license checks for Sourcegraph.com", to avoid having too many special cases in the code that would prevent us from exercising the same code paths as customers.)

**Comment by unknwon** [comment]
(^ it expires right at my birthday... haha)

**Comment by unknwon** [comment]
New license key applied, another site admin please help verify I did the right thing.

**Comment by beyang** [comment]
Confirmed fixed.
