### ISSUE TITLE
introduce sourcegraph/p4-fusion fork (v1.13) into gitserver (?) under feature flag

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#57647]

**Comment by eseliger** [comment]
Note to self: Once we do this, we have to start setting the `"--noBaseCommit" "true"` parameters for p4-fusion calls as well.

**Comment by eseliger** [comment]
I just realized you wrote "under feature flag" here - is this something you think is necessary for the S2 rollout immediately?

We should be able to easily revert this before the next release in Feb and I expect us to not want to provide a fallback to 1.12 at that point, given it has a bunch of known issues generating support load. 

Just wondering if we need to spend a whole extra day working this out, keeping two binaries around, and so forth.
