### ISSUE TITLE
No hovers for Ruby tokens with "!"

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#5764]
Ruby symbols can contain "!" and "?", but I can't seem to get hovers on those tokens. For example, `validate_runtime!` at:

https://sourcegraph.com/github.com/bundler/bundler@2a4d88a7044528209321fd4441e995ec66f604b9/-/blob/lib/bundler/definition.rb#L469

The symbols that lack "!" work fine.

**Comment by chrismwendt** [comment]
Another use case for a custom `identCharPattern` per language. Linking https://github.com/sourcegraph/sourcegraph/issues/3614#issuecomment-486819941
