### ISSUE TITLE
scip-ctags: returns different kinds to universal-ctags

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#57659]
We just noticed a pretty major regression in ranking for go files in sourcegraph. This is likely more widespread. It is due to  scip-ctags returning different kinds, resulting in the zoekt ranking code incorrectly assigning weights to results.

Right now we will work around it, but ideally we get the same data. What we have noticed so far (only testing go). This is confusing because the univesal ctag kind names are bad:

- Kind is always "type". Can't tell between struct, interface and type alias.
- Functions are called "function" instead of "func".
- methodSpec is called method. methodSpec in universal-ctags is a method in an interface decleration.
- methods and functions in universal-ctags are both "func". scip-ctags it is "method" and "function".
- member is called variable. 
- var is called variable.
- const is called constant.

Given we are moving to scip-ctags it would be great if we had a well defined spec here. All the current use of kinds are done by running universal-ctags and seeing what it outputs. Additionally we should be using scip-ctags in the zoekt repo.

**Comment by keegancsmith** [comment]
The workaround just for go is at https://github.com/sourcegraph/zoekt/pull/655. Gonna target getting that in for the patch release.

cc @sourcegraph/search-platform

**Comment by jtibshirani** [comment]
Here's our plan to tackle this.

Improve 'kind' output for SCIP ctags:
- [ ] https://github.com/sourcegraph/sourcegraph/pull/57806
- [ ] https://github.com/sourcegraph/sourcegraph/pull/57879
- [ ] https://github.com/sourcegraph/sourcegraph/pull/57899
- [ ] Remaining languages: Scala, Kotlin

Make Zoekt robust to differences in 'kind' output from SCIP and universal-ctags:
- [ ] https://github.com/sourcegraph/zoekt/pull/674
- [ ] Use SCIP ctags binary in Zoekt tests

**Comment by jtibshirani** [comment]
Closing this out, as remaining work is tracked in follow-up issues:
* Remaining languages to fix: https://github.com/sourcegraph/sourcegraph/issues/58024
* https://github.com/sourcegraph/sourcegraph/issues/57666
