### ISSUE TITLE
Propose GraphQL API for 3.9 automation features

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#5766]
Make PR for changes to schema.graphql to support features outlined in #5678.

**Comment by tsenart** [comment]
@felixfbecker: We're starting to work on the backend for 3.9 a8n features and would like to know roughly when we can start a discussion on the API contract. Specifically:

- Burndown chart
- Event timeline
- Combined diff

**Comment by felixfbecker** [comment]
Discussed in person ✨

**Comment by tsenart** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.9 release is scheduled for tomorrow** at 10:00 CEST.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
