### ISSUE TITLE
Bug: User Permission Syncing Page Not Loading

### ISSUE THREAD

**Issue by alexAtSourcegraph** [sourcegraph/sourcegraph#57673]
- **Sourcegraph version:** 5.2.0
- **Platform information:** All Platforms (First discovered on managed instance)

#### Steps to reproduce:

1. Navigate to an individual user's permissions syncing page with the following URL (https://demo.sourcegraph.com/users/[username]/settings/permissions)
2. Observe idling page

#### Expected behavior:
The page displays the appropriate permissions syncing information.

#### Actual behavior:

The page idles and errors out, never loading the proper information.

<img width="1792" alt="Screen Shot 2023-10-17 at 10 20 33 AM" src="https://github.com/sourcegraph/sourcegraph/assets/86978415/50e027e9-022f-40fd-bd5e-7e607f83c8da">

The following graphql error is shown:

![image](https://github.com/sourcegraph/sourcegraph/assets/86978415/67c88594-bab4-4b3c-a17e-ea70edc83959)

/cc @mrnugget

**Comment by pjlast** [comment]
Should be closed by either https://github.com/sourcegraph/sourcegraph/pull/57375 or https://github.com/sourcegraph/sourcegraph/pull/57372
