### ISSUE TITLE
Search result page loses scroll position when user gets back to it from blob UI

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#57704]
It seems like a regression that we reset the scroll position every time when we navigate to the search result page. I suspect that some problems come from the fact that we use streaming API there. And we should preserve the cache and scroll state between result and blob UI pages.

https://github.com/sourcegraph/sourcegraph/assets/18492575/e2c453a7-bb58-4c1c-a42c-ef5333435016

**Comment by vovakulikov** [comment]
Interesting thing that this scroll preserve logic works in Chrome and Firefox, but doesn't work in Safari 15.5

**Comment by camdencheek** [comment]
Closing since I can no longer reproduce this in any browser, including safari

**Comment by vovakulikov** [comment]
I think this was a problem only in Safari 15.6. But I think we can close our eyes on this since this version is kind of outdated and even we don't have a good support browsers list  policy I think it's out of standard "support two last major versions"
