### ISSUE TITLE
Improve actions discoverability and UX on file page

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#57702]
Users do not search to search alone, they search to perform actions. Sourcegraph allows users to perform key actions on the file page, but the design of these moments has several usability problems that hinders their discovery and use. 

This change:
* Moves lessor used icons to a dropdown where expansion can occur 
* Labels the key actions at the top level

If this change is successful, it will promote additional use of these key functions and position Sourcegraph as a tool that helps users perform key actions in their workflow. 

### Before
![image](https://github.com/sourcegraph/sourcegraph/assets/539268/2d7e7957-96cb-4f64-b528-0f6675c0ebf3)

### After (Initial design)
![image](https://github.com/sourcegraph/sourcegraph/assets/539268/44b9189c-d42b-4c4d-8252-197857a59e9f)

## Design process

  - Estimate: Three days
  - Weighting factors:
    - LOW risk
    - HIGH clarity

  ### Discover
  - [ ] Existing customer feedback - Link
  - [x] Analytics - [Link](https://app.amplitude.com/analytics/sourcegraph/dashboard/tw6ulwty)

  ### Define
  - [x] GitHub issue

  ### Design
  - [x] High fidelity design using design system - [Figma](https://www.figma.com/file/skTkU7PPWCvH2SAlP9GYtC/Search-Suite-Q4-UX-work?type=design&node-id=215%3A4900&mode=design&t=bwZiFLJUEd0iHAHg-1)
  - [x] Prototype - [Figma](https://www.figma.com/proto/skTkU7PPWCvH2SAlP9GYtC/Search-Suite-Q4-UX-work?page-id=3%3A10575&type=design&node-id=215-7295&viewport=-4486%2C7068%2C1&t=pSd6V8nwY9QOHBDH-1&scaling=min-zoom&starting-point-node-id=215%3A7295&mode=design)
  - [x] Prod team and design team review

  ### Testing
  - [x] Hallway testing - [Link](https://sourcegraph.slack.com/archives/C05D629GWJK/p1698255200679059)
  - [ ] Usertesting.com task-based evaluation - Link

  ### Deliver
  - [x] Loom - [Link](https://www.loom.com/share/a1cf5b62f44b4c24945791aa2fc16da8)
  - [x] Figma Dev Link - [Link](https://www.figma.com/file/skTkU7PPWCvH2SAlP9GYtC/Search-Suite-Q4-UX-work?type=design&node-id=215-4900&mode=dev)
  - [ ] QA - Link

  ### Measure
  - [x] Metrics defined in the Figma file ([i](https://handbook.sourcegraph.com/departments/product-engineering/product/design/metrics/defining-metrics/)) - Link
  - [ ] Followup task will analyze metrics to ensure successful completion - Link

**Comment by taiyab** [comment]
I think we're ready to go on this @sourcegraph/code-search 

Please review the [prototype](https://www.figma.com/proto/skTkU7PPWCvH2SAlP9GYtC/Search-Suite-Q4-UX-work?page-id=3%3A10575&type=design&node-id=215-7295&viewport=550%2C3470%2C0.48&t=MVubXCTOg8B28ZO3-1&scaling=min-zoom&starting-point-node-id=215%3A7295&mode=design) and [designs](https://www.figma.com/file/skTkU7PPWCvH2SAlP9GYtC/Search-Suite-Q4-UX-work?type=design&node-id=3-10575&mode=design&t=y2Jf1OOvONfSbnXq-0).

If anything is unclear, let us know before you start implementation.

**Comment by taiyab** [comment]
@camdencheek This is ready to go. Let me know if you need a walkthrough.

**Comment by camdencheek** [comment]
@sourcegraph/code-search anyone want to volunteer for this one? Otherwise, I'll probably start work on this ~Wednesday.

**Comment by BolajiOlajide** [comment]
> @sourcegraph/code-search anyone want to volunteer for this one?

I can take it.
