### ISSUE TITLE
Add Autocomplete OpenAI support

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#57724]
Autocomplete support was added for Azure OpenAI but was not added for OpenAI

This issue is to bring the same Azure OpenAI logic overt to the OpenAI provider to add autocomplete support.

- [x] Allow autocomplete requests for OpenAI models in the backend.
- [x] Update the OpenAI provider prompt in VS Code to ensure it works well.
- [ ] ~~Optionally allow OpenAI autocomplete in Cody Gateway.~~

**Comment by cbart** [comment]
Done on BYOK, working on Gateway today. TODO @cbart follow up on M keys.

**Comment by chwarwick** [comment]
I'm going to close this and add a new backlog item to bring support to the gateway if needed.
