### ISSUE TITLE
Technical work plan for reliable vector worker / qdrant / scale testing

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#57726]
Please create a set of milestones for Q4 regarding reliable vector compute work and search. Let it end up in https://github.com/sourcegraph/sourcegraph/issues/56176 tasks.

In scope:

- Worker
- Scale testing
- Handling model updates (recomputing - @cbart can explain)
- Qdrant

Out of scope:

- Self-hosted vector compute model / deployment

**Comment by azayarni** [comment]
Feel free to let us know if you need any support. We are building a code search demo atm.
