### ISSUE TITLE
Blob view: extra column in gutter

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#57809]
The blob view has an extra empty column in the gutter, which IMO looks imbalanced when coupled with the expand/collapse functionality. 

<img width="628" alt="Screenshot 2023-10-23 at 11 04 47" src="https://github.com/sourcegraph/sourcegraph/assets/12631702/f835ca78-a4fc-40dc-a84b-f9dffcbdc111">

@camdencheek's recommendation is to decrease the padding so that the spacing on either side of the collapse icon is balanced. We may want a little bonus padding on the left so it's not quite so cluttered. See screenshot.

<img width="649" alt="Screenshot 2023-10-23 at 11 09 02" src="https://github.com/sourcegraph/sourcegraph/assets/12631702/76e01207-ce51-404c-8f5f-200974c4016f">

cc @taiyab for design thoughts

**Comment by jasonhawkharris** [comment]
@rrhyne @taiyab Thoughts on design here?
