### ISSUE TITLE
Loading repo list in code nav dropdown is slow on large instances

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#57821]
On a large instance (like sourcegraph.com), using the new repo dropdown in the blob view is painful because it takes a long time to load. It's likely we're trying to load all repos that match, which is way too many without any filter.

https://github.com/sourcegraph/sourcegraph/assets/12631702/5d3d105b-5647-4634-954d-e601700bc371

**Comment by jasonhawkharris** [comment]
This is the behavior of the repo link picker if user is not a site admin. @vovakulikov I am assuming this is intentional but I just want to be sure. 

![Screenshot 2023-10-31 at 8 48 43 AM](https://github.com/sourcegraph/sourcegraph/assets/62355966/48269fe0-4e24-4de9-b315-cfe1e264bc15)

**Comment by vovakulikov** [comment]
@camdencheek thanks for catching this, I'm curios is this something that we could cache? On the client I do fetch only first 15 entities max for this picker, ([here](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/repo/RepoLinkPicker.tsx?L43-62) is the query this picker uses) are you saying that we have that many rows in table that even simple query could lead to slow response? 

Oh @jasonhawkharris good call, this is a bug, I haven't checked the picker with non-admin user account (it looks like that external service info is user admin only gates @camdencheek do you know why does it under admin protection, seems like it should be public info)
