### ISSUE TITLE
Tree view: more useful recent activity

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#57827]
Our tree view has a "recent activity" column which shows an opaque red/green line that supposedly represents how much has changed in that entry recently. This is pretty useless in practice. 

<img width="800" alt="CleanShot 2023-10-23 at 13 39 34@2x" src="https://github.com/sourcegraph/sourcegraph/assets/12631702/8a89a191-daf4-4b7c-bfb1-6836b738740a">

Compare to the tree view of another well-known codehost, which shows the most recent commit message, how long ago it was edited, and a link to that change. This is significantly more useful when browsing code.

<img width="1024" alt="CleanShot 2023-10-23 at 13 37 52@2x" src="https://github.com/sourcegraph/sourcegraph/assets/12631702/516d1183-2eed-4d4e-a8b4-f34e42f5b52c">

________

### Preview

<img width="1119" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/5337876/3970556e-60c2-4dac-889e-c923d08e153b">

### Link

https://www.figma.com/file/pOuuecCujCnOfvaNEcws9z/Tree-View?type=design&node-id=69%3A1280&mode=design&t=gt9kf9NDtGUi5SWL-1

**Comment by taiyab** [comment]
@fkling Happy for you to do a first pass on this without design whilst I figure out what we can do on hovering the commit message.

**Comment by fkling** [comment]
After talking with @taiyab, my plan is to

- load commit information lazily (I think we do the same for the "activity" information).
- remove "Commits" panel to reduce the amount of seemingly duplicate information
- add the history action to tree pages, so that users can still access the full history if they need to. That's at least consistent with the file page.

**Comment by taiyab** [comment]
Here's a visual of the proposal:
<img width="1439" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/5337876/a1aa6376-8c4e-4178-8942-ee22546bcdf1">

Does the Commit panel actually buy us anything here? We should make sure whatever it's giving us at this point, we're able to bake into the file list is a useful way.

It's not an ideal solution, but I think it works alright in the interim, unless people really like the commit list for some reason?

cc @rrhyne

**Comment by camdencheek** [comment]
Removing the commit panel sounds good to me. Though, I agree with Felix that it would be nice to still be able to view history for a directory. A unified history panel across both the blob and tree views sounds excellent

**Comment by taiyab** [comment]
@fkling I've attached the designs above (https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/%E2%9C%B3%EF%B8%8F-Wildcard-Design-System?type=design&node-id=26240%3A6665&mode=design&t=oDljiz2Ggf7m6xbh-1).

Let me know if there are any questions.
