### ISSUE TITLE
Commit view: when lines wrap, they start on a second line

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#57834]
In the commit view, when a line wraps because it is too long, it starts on a second line, leaving an unnecessary empty line above it. 

https://github.com/sourcegraph/sourcegraph/assets/12631702/86d6f4e2-5d7d-480c-a8ef-17353b5fed48

**Comment by Galindo-J** [comment]
Here is an additional instance of this occurring: 

When the added elements in a yaml array have a value that is long enough to wrap in the UI, the Sourcegraph version of the diff starts the new line visually one space below the new line, and the indentation is thrown off to the left. In the screenshot, line 5 was modified to a longer value. The Sourcegraph diff result shows line 5 with `+` only, and starts the actual value below line 5 visually as well as making the indentation in the same scope as the name of the yaml array.

Sourcegraph View:
<img width="1724" alt="Screenshot 2023-11-06 at 4 21 12 PM" src="https://github.com/sourcegraph/sourcegraph/assets/54120980/1b641f89-b3e5-4230-92c4-434d285179e6">

Gitlab View:
![Screenshot 2023-11-03 at 6 25 31 PM](https://github.com/sourcegraph/sourcegraph/assets/54120980/3f452905-6281-43bf-bb87-fb87074b2242)
