### ISSUE TITLE
cody quality: create a proposal for how to automate / scale up test case generation

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#57844]
We will have a spectrum of lenient to strict evals for automated tests, starting from correct types to functional correctness and everything in between.

While we generate test cases in 2 weeks, we’ll think about how to automate them .. end of 2 weeks, share proposal on how we could scale this effort.

**Comment by cbart** [comment]
Olaf picked up a new promising direction there. Closing.
