### ISSUE TITLE
cody quality: user research for intents

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#57843]
Goal: understand the _intents_ behind people performing autocompletions with Cody via:

* @Rishabh User research (follow up with Megan on this, e.g. https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1697814412364089) 
* Scrape/search Twitter/Reddit for intent cases/examples based on how people talk about Cody and Copilot?
* @slimsag gather data from App feedback and customer #feedback

**Comment by cbart** [comment]
Done.
