### ISSUE TITLE
Tree-sitter-based syntax-highlighting support for Dart

### ISSUE THREAD

**Issue by matthewnitschke-wk** [sourcegraph/sourcegraph#57880]
#### Feature request description

Current dart syntax highlighting support for sourcegraph is limited to just a [`.sublime-syntax` file](https://github.com/sourcegraph/Packages/tree/st3/Dart). This lacks the contextual awareness that can be provided by a tree-sitter

Adding support for a tree-sitter for dart would pair well with the existing [scip-dart](https://github.com/Workiva/scip-dart) package, making a first class experience for dart developers within the sourcegraph platform. As one of those dart developers this is something I would love to see implemented

There exists a current tree-sitter-dart implementation that can be found [here](https://github.com/UserNobody14/tree-sitter-dart), It's licensed under MIT, and therefore should be fine to use within the sourcegraph codebase

#### Is your feature request related to a problem? If so, please describe.

Current syntax highlighting for dart leaves much to be desired. Implementing tree-sitter-dart would greatly improve browsing dart code within sourcegraph

![example of dart syntax highlighting](https://github.com/sourcegraph/sourcegraph/assets/39171685/a1891c83-1035-4778-be78-1cd562ef4a07)

#### Describe alternatives you've considered.

- a scip index file currently has support for a `SymbolInformation.Kind`: https://github.com/sourcegraph/scip/blob/main/scip.proto#L222. From what I understand, this field is currently utilized to style the code editor within sourcegraph.com, but it is not directly populated from user uploaded scip files (instead it comes from tree-sitter implementations). If this was updated to allow user-uploaded scip files to populate this Kind field, we could bypass the need to support both a tree-sitter-dart and a scip-indexer.

- I've also looked into just updating the `Dart.sublime-syntax` file within [packages](https://github.com/sourcegraph/Packages/tree/st3/Dart), google provides an official package for this, but it's specific to textmirror/vscode: https://github.com/dart-lang/dart-syntax-highlight/tree/master/grammars. I haven't yet looked whether the syntax highlighting results would be better with this grammar instead of the one provided by [dart-sublime-bundle](https://github.com/guillermooo/dart-sublime-bundle), but given the fact that this was last updated 8 years ago, I'd imagine it would be at least _some_ improvement. This would be a stepping stone solution as the contextual awareness that tree-sitter provides would be the preferred path

#### Additional context

- tree-sitter-dart currently uses an old version of tree-sitter ([`0.17`](https://github.com/UserNobody14/tree-sitter-dart/blob/master/Cargo.toml#L23)), in order to successfully implement this within sourcegraph, a fork+update would have to be implemented (similar to what has been done for [other](https://github.com/sourcegraph/tree-sitter-typescript) [languages](https://github.com/sourcegraph/tree-sitter-sql))

- tree-sitter-dart also has this strange setup with [duplicate git submodules](https://github.com/UserNobody14/tree-sitter-dart/blob/master/.gitmodules#L1) which fails when trying to depend on it from cargo. I've found that after removing the duplicate, you can successfully install the package within sourcegraph's tech stack

- I've already spiked the necessary work to implement this tree-sitter [here](https://github.com/matthewnitschke-wk/sourcegraph/tree/tree_sitter_for_dart), I'm coming up a bit short on how to generate the snapshot tests and actually test it though. Some assistance in this area would be greatly appreciated

**Comment by varungandhi-src** [comment]
Latest PR: https://github.com/sourcegraph/sourcegraph/pull/58480

**Comment by varungandhi-src** [comment]
Looks like this was accidentally re-opened; re-closing.
