### ISSUE TITLE
File tree: forever loading icon

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#57936]
[This directory](https://sourcegraph.com/github.com/backstage/backstage@HEAD/-/tree/contrib/chart) loads forever in the file tree. Not sure why yet. 

![Image](https://github.com/sourcegraph/sourcegraph/assets/12631702/c3627230-6230-402e-b24f-cf52f84a7b8d)

**Comment by camdencheek** [comment]
@eseliger I think this might actually have to do with the recent changes you made to this resolver. Would you mind taking a look? It seems to happen consistently when expanding any directory that contains only a single child.

**Comment by eseliger** [comment]
Duh, taking a look.

**Comment by camdencheek** [comment]
Looks like [this one](https://github.com/sourcegraph/sourcegraph/issues/57999) might also be related. If you don't have the time to look at it, @BolajiOlajide and I are planning to tackle these on Friday, so no worries
