### ISSUE TITLE
ranking: diversity boost code if no code at top

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#57975]
Another "diversity rule" that could be helpful: in the absence of file filters, at least one file in the top 3 should be a code file (not build, not docs).

_Originally posted by @jtibshirani in https://github.com/sourcegraph/zoekt/issues/665#issuecomment-1781921276_

**Comment by jtibshirani** [comment]
It could be good to "step back" and take a general look at how we mix results across languages and types (source, config, docs, etc.) For example, if scores were more comparable across types, maybe we wouldn't need special diversity rules?

**Comment by jtibshirani** [comment]
Closing in favor of https://github.com/sourcegraph/sourcegraph/issues/58057
