### ISSUE TITLE
Header bar: Code Search is not clickable without going through dropdown

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#57986]
![image](https://github.com/sourcegraph/sourcegraph/assets/12631702/8e2c87b9-0530-4a59-b2a7-adb32f57a821)

Original [Slack Thread](https://sourcegraph.slack.com/archives/C03CSAER9LK/p1698675472602199)

**Comment by taiyab** [comment]
I suspect that people are only clicking this dropdown when they are struggling to get back to home.

- Contexts doesn't belong under here, and it being here is an indication that the context menu that drops out on clicking `context:global` isn't known to everyone. **This is worth tackling urgently.**
- Code ownership and any extraneous features can go under a more link (attached).

I'm suggesting we remove the chevron + dropdown altogether:
<img width="1520" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/5337876/93d40d8d-2660-464c-8367-0024f52dd55d">

Any experimental stuff can also fall into that "More" link, such as these: 
<img width="269" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/5337876/8d9b6f18-8509-4d5b-a054-f4e948647cbe">

Again, not a perfect solution, but works in the interim.

cc @rrhyne
