### ISSUE TITLE
Chat on Bedrock never stops. Need to press stop generating.

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#58115]
Link: https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1699036222383849

**Comment by cbart** [comment]
@dhdiemer

**Comment by chwarwick** [comment]
Continued testing with 5.2.2 on the WebUI and have not been able to reproduce.

**Comment by chwarwick** [comment]
Unable to replicate and no new steps to reproduce.
