### ISSUE TITLE
Should be able to close blobview search

### ISSUE THREAD

**Issue by jasonhawkharris** [sourcegraph/sourcegraph#58208]
Currently, there is no way to close the blob view search. We need to add the ability to close it out. See video below:

https://www.loom.com/share/1b644ba6184843949c227af09206ce7b

Some ideas
- We use command F to open, maybe we also use command F to close?
- An X somewhere
- Both

Need design input on this.

**Comment by jasonhawkharris** [comment]
> We use command F to open, maybe we also use command F to close?

Some user feedback came in about this. I don't think command F to close is the best option. Most 'find' tools in browsers use command F to highlight the current text in the input field. Blobview search currently performs this way and we should retain that so that we don't mess with people's muscle memory. @taiyab

**Comment by camdencheek** [comment]
<kbd>Esc</kbd> works in my browser. Does that work for you?

**Comment by taiyab** [comment]
@jasonhawkharris We can add a close button, like this.
<img width="214" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/5337876/287cf2d3-4ed5-414f-bcb6-1bb7b41717e5">

You can find it here: https://www.figma.com/file/xZ7os2VODDE3rNe4uFRDFu/CodeMirror-UI-Imrovements?type=design&node-id=173%3A5731&mode=design&t=9mcl9wuZtUKA6sZq-1

Let's implement it with a hover state where the touch area is highlighted:
<img width="190" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/5337876/7bbfbade-53fe-4978-980c-bce3f648303d">

https://www.figma.com/file/xZ7os2VODDE3rNe4uFRDFu/CodeMirror-UI-Imrovements?type=design&node-id=414%3A4490&mode=design&t=9mcl9wuZtUKA6sZq-1

**Comment by taiyab** [comment]
@jasonhawkharris @camdencheek ++"Esc"++ also works for me too, and that's expected (for me, at least).
