### ISSUE TITLE
Cody is disable unless self hosted version  have a enterprise license ?

### ISSUE THREAD

**Issue by imotai** [sourcegraph/sourcegraph#58295]
- **Sourcegraph version:** 
- **Platform information:** 

#### Steps to reproduce:
I deploy the self-hosted  version without the license and use [ a third-party LLM provider](https://docs.sourcegraph.com/cody/overview/enable-cody-enterprise#using-a-third-party-llm-provider-directly)
but cody is always disabled

#### Expected behavior:
cody is enabled 
#### Actual behavior:
cody is disabled 
If you would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are no [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

**Comment by pxz2016** [comment]
@imotai 
Is there a conclusion?
是否有结论？

**Comment by csh0101** [comment]
@pxz2016  is there a conclusion?
