### ISSUE TITLE
Improve search results

### ISSUE THREAD

**Issue by taiyab** [sourcegraph/sourcegraph#58371]
The search results are key to finding and evaluating code discovered across all your (org's) repos. The better and more efficient this UX is, the more likely developers are to pick it up as part of their core workflow.

## Design process

  - Estimate: Two weeks to a month
  - Weighting factors:
    - HIGH risk
    - MEDIUM clarity

  ### Discover
  - [x] [PRD - WIP](https://docs.google.com/document/d/1OxbaoEsNwXJ6eiZmTUZ7CHEB3JY7FuQ5fZTHl8K9jfY/edit?usp=sharing)
  - [x] Existing customer feedback
    - [x] NPS scores (external users) - [Link](https://docs.google.com/spreadsheets/d/1--_g4Me24gWCwzxT5KQ70YXAxdRFiRQDfs0BMcBd8LM/edit?usp=sharing)
    - [x] Feedback submissions (internal users)

  ### Define
  - [x] PRD and/or RFC - [[Link](https://docs.google.com/document/d/1OxbaoEsNwXJ6eiZmTUZ7CHEB3JY7FuQ5fZTHl8K9jfY/edit?usp=sharing)]

  ### Design
  - [x] High fidelity design using design system - [Figma](https://www.figma.com/file/EPgl0qVbqGSumvf52brhda/branch/pAygQOR0whuEgLnuITwGrm/Improving-search-results?type=design&node-id=36%3A751&mode=design&t=AXLkP5hvYOYcZrJO-1)
  - [x] Prototype - [Link](https://www.figma.com/proto/EPgl0qVbqGSumvf52brhda/branch/pAygQOR0whuEgLnuITwGrm/Improving-search-results?page-id=1%3A52&type=design&node-id=36-751&viewport=-671%2C483%2C1&t=n5EisAyBrw9h0l1u-1&scaling=min-zoom&starting-point-node-id=36%3A751&mode=design)
  - [x] Designer review

  ### Testing
  - [x] Hallway testing - (Put it out on dotcom for general feedback)
  - [x] Usertesting.com task based evaluation - [Link](https://app.usertesting.com/workspaces/937482/study/4967480/sessions?shared_via=link&share_id=Sr97D3Myez)

  ### Deliver
  - [x] Announce in #progress
  - [x] Loom - [Link](https://sourcegraph.slack.com/archives/C05EA9KQUTA/p1701724770131329)
  - [x] Team review - Figma, 1-1s
  - [x] Design team review - [Link](https://www.figma.com/proto/EPgl0qVbqGSumvf52brhda/branch/pAygQOR0whuEgLnuITwGrm/Improving-search-results?page-id=1%3A52&type=design&node-id=36-751&viewport=-671%2C483%2C1&t=n5EisAyBrw9h0l1u-1&scaling=min-zoom&starting-point-node-id=36%3A751&mode=design)
  - [x] QA

  ### Measure
  - [ ] Metrics defined in the Figma file ([i](https://handbook.sourcegraph.com/departments/product-engineering/product/design/metrics/defining-metrics/)) - [Link](https://www.figma.com/file/EPgl0qVbqGSumvf52brhda/Code-Search?type=design&node-id=1540%3A20102&mode=design&t=JSGOywTI0Qz1HzR6-1)
  - [ ] Followup task will analyze metrics to ensure successful completion - Link
  - [x] Telemetry - [Link](https://github.com/sourcegraph/sourcegraph/pull/59985)

**Comment by taiyab** [comment]
@kelsey-brown I've tagged you in the [WIP doc here](https://docs.google.com/document/d/1OxbaoEsNwXJ6eiZmTUZ7CHEB3JY7FuQ5fZTHl8K9jfY/edit?usp=sharing).

Would love to get some early metrics in for this.

**Comment by camdencheek** [comment]
@taiyab can we close this one?
