### ISSUE TITLE
CLA bot broken

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#5839]
Our CLA bot is broken currently. See this thread for details: https://sourcegraph.slack.com/archives/C07KZF47K/p1570046864137300

It is broken because it cannot sync the issues:

```
2019/10/02 23:14:49 corpus.Sync: GET https://api.github.com/repos/sourcegraph/sourcegraph/issues/2921: 410 This issue was deleted []; sleeping 15s
```

This is due to golang.org/x/build/maintner not supporting closed GitHub issues. It is weird that GitHub decided to implement this as a 410 status instead of using a field similar to how they denote closed and other statuses, but nonetheless maintner cannot handle it and bails out.

We will need to fix that issue upstream here in the code: https://github.com/golang/build/blob/c41ee31c2ed1caabb143ad39d536b27087620bfc/maintner/github.go#L1841-L1861 and then rebuild and redeploy sgbot with the new version for it to start working again.

**Comment by nicksnyder** [comment]
CLA bot is indeed not asking for CLA signatures: https://github.com/sourcegraph/sourcegraph/pull/8055#issuecomment-578910214

This is a small issue that would be nice to get done next iteration.

**Comment by keegancsmith** [comment]
Upstream fix at https://go-review.googlesource.com/c/build/+/216438

Ran prod setup locally with fix applied and CLA bot processed deleted issues fine. I'm leaving it running locally to see if it ends up commenting. Just taking a while since it is syncing all comments/etc so takes a long time to run.

**Comment by keegancsmith** [comment]
I shipped a patched version of sgbot in https://github.com/sourcegraph/infrastructure/commit/f5e2d837d258247525c1d9737d70a5536799e609

Once the upstream fix is merged I'll switch us away from the patched version to the build version.
