### ISSUE TITLE
Autocomplete in Monaco broken on dotcom for code host connection config

### ISSUE THREAD

**Issue by pjlast** [sourcegraph/sourcegraph#58443]
Possibly same on site config and locally?

**Comment by pjlast** [comment]
![Image](https://github.com/sourcegraph/sourcegraph/assets/6427795/d7960742-5802-4f33-aa1c-16d8f4a7c169)

This seems to be the cause. This happens on Dotcom but not locally

**Comment by pjlast** [comment]
Seems relevant: https://github.com/microsoft/monaco-editor/issues/1384

**Comment by pjlast** [comment]
Something prevents the web workers from running on dotcom? https://github.com/microsoft/monaco-editor/issues/1995

**Comment by BolajiOlajide** [comment]
@pjlast Does this fix the auto complete bug for Site Config also?

https://github.com/sourcegraph/sourcegraph/issues/60694

**Comment by pjlast** [comment]
@BolajiOlajide no, I guess this should have been marked as "Closed" instead of "Completed". The issue is related to `esbuild` and was deemed to not be worth it since that process is temporary and in the process of being reworked as well.

**Comment by BolajiOlajide** [comment]
Thank you @pjlast
