### ISSUE TITLE
Investigate reported chat/command issues

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#58462]
Answers getting cutoff midway w/ chat
Halfway through chat, it forgets what you’re talking about

I'm running into an issue with Cody in VSCode. I am able to use Cody just fine up to a certain point, then when I give it a command or ask it a question in inline chat it spins and does nothing.  This usually happens after chatting with it for a bit or asking it document multiple functions.
Resolved https://github.com/sourcegraph/cody/pull/1831

**Comment by cbart** [comment]
@chwarwick I'll close this issue given https://github.com/sourcegraph/cody/pull/1831. Let me know if this needs reopening.

**Comment by chwarwick** [comment]
Haven't been able to recreate 

> Answers getting cutoff midway w/ chat

It's possible that https://github.com/sourcegraph/cody/pull/1831 or https://github.com/sourcegraph/cody/pull/1824 could resolve the issue.
