### ISSUE TITLE
Hide case/regex/structural search icons until search input is focused

### ISSUE THREAD

**Issue by taiyab** [sourcegraph/sourcegraph#58511]
I think these three icons (case sensitivity/regex/structural search) don't need to be there until the search input is focused.

<img width="135" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/5337876/5b851c2c-a320-4535-b298-3bb3f5b9d1b3">

If any one of them is active, we can keep the options always visible, that way you know if something has been activated always.

Anything I'm missing here? Any interaction/UX concern I'm not considering?

**Comment by camdencheek** [comment]
I'd propose closing this because the plans from @sourcegraph/search-platform include language changes that would let us get rid of these entirely

**Comment by camdencheek** [comment]
Tentatively closing as a "let's wait to see where the query language changes get us." Feel free to re-open in case you want to tackle this sooner
