### ISSUE TITLE
Copy/Paste of repo name results in additional content being copied

### ISSUE THREAD

**Issue by Galindo-J** [sourcegraph/sourcegraph#58517]
- **Sourcegraph version:** reproduced on  v5.2.2 & v5.1.0 (most likely exists on other versions as well)
- **Platform information:** 
Chrome Version 117.0.5938.149 (Official Build) (arm64) & 119.0.6045.106 (Official Build) (64-bit)
#### Steps to reproduce:

1. Open a repo at the root dir from a Sourcegraph instance in Chrome 
2. Double-click on the name of the repo
3. Copy & paste

https://github.com/sourcegraph/sourcegraph/assets/54120980/529bbb28-708f-47b3-8f6a-8d44a5a90ee4

#### Expected behavior:
Only the repo name is copied.

#### Actual behavior:
The entire header is copied including buttons.

I attempted to recreate this on Safari and on Firefox, and it didn't work. From my limited tests, it only seems to occur on Chrome. As the video shows above, it also only occurs when the name is double-clicked rather than highlighted.

If the program the content is being pasted into is using rich text, it seems to show the entire header in some manner, otherwise, only the header is displayed. 

If you would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are no [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

/cc @sourcegraph/search-product/search-platform

**Comment by keegancsmith** [comment]
This is likely a problem in the code running in the browser, so cc @sourcegraph/code-search

**Comment by peterguy** [comment]
I did a couple of tests also, and found that it only exhibits in Chrome, and only if the whole "line" is selected, up to the newline, which looks like an extra blank.
<img width="587" alt="image illustrating the extra space when selecting" src="https://github.com/sourcegraph/sourcegraph/assets/129280/bdc454ed-4ff7-4ab8-8b88-38fa876888ba">

**Comment by camdencheek** [comment]
Closing since this is no longer an issue in the svelte rewrite, and it's not high enough priority to tackle proactively before that is released
