### ISSUE TITLE
Names of test DBs clash in buildkite

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#5854]
Found a possible source of flaky Go tests on Buildkite. There is [some effort](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+%22DBNameSuffix%22) in the Go unit tests that interact with a database to shield them from interacting with other tests running concurrently. However, the resulting database names are deterministic and will not be safe to run in two different CI agents against the same db instance.

**Proposed solution**: append a uuid to each of these suffixes.

**Comment by keegancsmith** [comment]
I agree this is clunky, but we do that so we don't have to introduce a process which cleans up DBs. There might be a better solution based on introspecting the test binary package name. As it stands within a test for a go package there shouldn't be any conflicts since we have one postgres DB per buildkite-agent.

Do you have an example of this process being flakey?

**Comment by efritz** [comment]
> Do you have an example of this process being flakey?

Not specifically, but it looked like a _possible_ cause. There were some issues around creating a static second database (sourcegraph_lsif) that lead me to find this, but I haven't determined this to be a cause to an actual problem.

> There shouldn't be any conflicts since we have one postgres DB per buildkite-agent.

Does each agent run only one thing at once? Are any of the go tests parallel and assume they're the only ones running against a database?

**Comment by keegancsmith** [comment]
go tests don't run parallel across packages. An agent only does on job at a time. So yes on CI this shouldn't happen. cc @sourcegraph/core-services

**Comment by unknwon** [comment]
Are we discussing how to make no parallel tests for sure or ...?
If so, [How To _Avoid_ Parallel Execution of Tests in Go](https://medium.com/@xcoulon/how-to-avoid-parallel-execution-of-tests-in-golang-763d32d88eec) has a quick solution by using `go test -p 1 ./...`.

```
$ go help testflag
...
-parallel n
Allow parallel execution of test functions that call t.Parallel.
The value of this flag is the maximum number of tests to run
simultaneously; by default, it is set to the value of GOMAXPROCS.
Note that -parallel only applies within a single test binary.
The ‘go test’ command may run tests for different packages
in parallel as well, according to the setting of the -p flag
(see ‘go help build’).
...
```

**Comment by mrnugget** [comment]
Hard to tell without looking at a failing build, but what _could_ also lead to multiple tests using the same database is when this is **not** done:

> There is [some effort](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+%22DBNameSuffix%22) in the Go unit tests that interact with a database to shield them from interacting with other tests running concurrently.

Maybe there is a package that doesn't set this in its `init()` function?
