### ISSUE TITLE
Revise Cody permissions system to not be a ‘feature flag’ docs but rather site config or user management page

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#58623]
Today Cody's permissions controls are managed via a feature flag: https://docs.sourcegraph.com/cody/overview/enable-cody-enterprise#enable-cody-only-for-some-users

This should be a site config or user management page instead.

**Comment by chwarwick** [comment]
@slimsag  you should check out the [RBAC](https://docs.sourcegraph.com/dev/how-to/add_permissions#adding-permissions) option sounds like it would be a good fit and already has UI for it.
