### ISSUE TITLE
(stretch) Cody audit log

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#58633]
(stretch goal)

A cody audit log, allowing admins to view everything Cody is doing at their organization in detail. E.g. which repositories/filenames people are using Cody on, who is using it, etc. on their Sourcegraph instance.

Prior to work starting on this issue, we'll need to discuss/explore/spec-out a bit of the details between Product and Engineering to find the right balance of 'easy-to-implement' and 'useful-to-admins'.

**Comment by cbart** [comment]
I'll close this for now. We'll file separate issue once work on audit logging starts.
