### ISSUE TITLE
alias patterns in structural search producing inconsistent results

### ISSUE THREAD

**Issue by AJKemps** [sourcegraph/sourcegraph#58693]
**Sourcegraph version**: 5.2.2
**Reported by**: https://github.com/sourcegraph/accounts/issues/6938

**Steps to reproduce:**
I'm playing around structural search with Sourcegraph and the result is unexpected, I'm not sure if I wrote something wrong or it is an actual bug:
 
context:global repo:^mw/Bmain$ isa(...,:[~[ \t]+]class(...)) lang:MATLAB
matched 17 results
 
context:global repo:^mw/Bmain$ isa(...,:[ ]class(...)) lang:MATLAB
matched 0 result
 
According to their documentation, ":[~[ \t]+]" is an alias to ":[ ]" which is supposed to behave the same.
 
My ultimate goal is to find pattern and perform code transformation.

**Expected behavior:**
The second query returns the same number of results as the first query because the second query uses an alias of the syntax in the first query.

**Actual behavior:**
It seems sourcegraph doesn’t actually support :[ ] as an alias [when translating to a regex query](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@5c7b75569a5a871d5477f9aaa2a4c751b0086805/-/blob/internal/comby/translate.go?L173-176), so it’s being interpreted literally.

/cc @sourcegraph/search-platform

**Comment by jtibshirani** [comment]
Thanks for taking the time to report this. We aren't actively investing in structural search and are unlikely to tackle this, so I'll close it out.
