### ISSUE TITLE
VSCode Search extension not opening file when search result is clicked

### ISSUE THREAD

**Issue by AJKemps** [sourcegraph/sourcegraph#58721]
Sourcegraph version: 5.2.2
Reported by: https://github.com/sourcegraph/accounts/issues/6938

Steps to reproduce:

Search for a file in the VS Code Sourcegraph extension and attempt to open one of the files.

Here's a short clip showing the issue: https://hello.chorus.ai/listen?guid=d07b587d9519466fb136fde21ad885c7

Expected behavior:
The file should open quickly.

Actual behavior:
The file either doesn't open or takes more than 10 seconds to open.

**Comment by peterguy** [comment]
[Internal discussion](https://sourcegraph.slack.com/archives/C03EF1YSRKK/p1716497203720889?thread_ts=1716494134.805189&cid=C03EF1YSRKK)

**Comment by peterguy** [comment]
Recorded a new walkthrough showing this behavior and also showing that it does not exist in current `main`. Some update between when the extension was published and now has fixed this behavior.

https://github.com/sourcegraph/sourcegraph/assets/129280/c78adef4-cbfc-41d2-85b4-13c26531b4d9

**Comment by victoralvesp** [comment]
I'm seeing the same issue on version v2.2.18 on an Enterprise account
