### ISSUE TITLE
Test Sourcegraph with Atlassian Identity Manager

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#5873]
Test Sourcegraph with Atlassian Identity Manager SAML: https://www.atlassian.com/blog/announcements/introducing-identity-manager-atlassian-cloud.

[$CUSTOMER](https://app.hubspot.com/contacts/2762526/company/557475593) mentioned some difficulty in setting up Sourcegraph with Atlassian Identity Manager with SAML authentication. We should test this out and add to the SAML docs (and potentially improve docs around general SAML debugging, as well).

**Comment by tsenart** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.9 release is scheduled for tomorrow** at 10:00 CEST.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.10 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by dadlerj** [comment]
This can be closed for now — the customer is in a good place.
