### ISSUE TITLE
Let only Pro users use GPT-4

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#58753]
Change the logic to allow different models based on their Cody tier, and trigger a refresh on Tier upgrade.
It's probably just an `if` [here](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/dotcom/productsubscription/codygateway_dotcom_user.go?L332#tab=references).
Then reply [here](https://sourcegraph.slack.com/archives/C05SZB829D0/p1701187278753019)

**Comment by vdavid** [comment]
@chenkc805, two questions:
The current lists are these:
- chat: "anthropic/claude-v1", "anthropic/claude-2", "anthropic/claude-2.0", "anthropic/claude-2.1", "anthropic/claude-instant-v1", "anthropic/claude-instant-1"
- code: "anthropic/claude-instant-v1", "anthropic/claude-instant-1", "fireworks/accounts/fireworks/models/starcoder-7b-w8a16", "fireworks/accounts/sourcegraph/models/starcoder-7b", "fireworks/accounts/fireworks/models/starcoder-16b-w8a16", "fireworks/accounts/sourcegraph/models/starcoder-16b"

Questions:
1. Which one of these shall we allow for chat and for code completions for Free users?
2. What else do we want to allow for Pro users? I've heard GPT-4 I think. What's the name of that model to add in these list? My guess: "openai/gpt-4"? Shall I add it to both lists or for chat only?

**Comment by chenkc805** [comment]
This should be clarified here: https://sourcegraph.slack.com/archives/C05AGQYD528/p1701814858992039?thread_ts=1701813578.856019&cid=C05AGQYD528
