### ISSUE TITLE
Prototype search language simplifications

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#58799]
We discussed simplifying the query language at our offsite. This issue is to track the work in actually working out the details on that as well as a prototype so we can gain experience on the change.

/cc @sourcegraph/search-platform

**Comment by keegancsmith** [comment]
Notes from our meeting related to query language

If we could design the query language from scratch, what would it look like?

Repository filters:
* Exact match with glob patterns
   * Match sourcegraph repo: `sourcegraph/sourcegraph`
   * Match sourcegraph org: `sourcegraph/*`

File filters:
* Exact match with glob patterns
* Question: should `*` match across directories, or should we include `**`?
   * Extended glob with `**` might be a bit of a footgun … consider `*/vendor/*`
* Maybe fall back to regex for more complex use cases

Language filters
* Also support extension names, like `lang:md`

Query contents:
* Match literally
* Break on whitespace and AND tokens
* If you want to match exactly, wrap in quotes
* If you want to do regex, use `/…/`
* Quotes must be escaped – this may be annoying when copying and pasting in things like `throw new Exception("too many terms")`
* Keyword search: we actually make no guarantee about whether we use AND or OR, or stem …
   * If you explicitly use AND and OR, then we don’t stem
   * Question: What about single term queries? To avoid stemming these, do they need quotes?

**Comment by keegancsmith** [comment]
I've been thinking of this in how we can translate our new queries into our old queries. The main reason is that is the easiest way to prototype this... write some code which transforms the queries in the frontend then everything else doesn't need to know about this.

Exact match with glob patterns. Only support `*`, and it matches across path components. This allows us to translate to regex.

```
repo:sourcegraph
repo:^sourcegraph$

repo:github.com/*
repo:^github\.com/.*$

repo:*/sourcegraph
repo:^.*/sourcegraph$
```

File has some logic as repo. We need some extra handling for the transformation since we transparently add in the `/` to ensure we are matching on absolute paths.

TODO For more complicated use cases we need a way to fallback to regex. This is a bit confusing due to `/PATTERN/` being the usual way to indicate regex.

```
file:README.md
file:^/README\.md$

file:client/README.md
file:^/client/README\.md$

file:*/Dockerfile
file:^.*/Dockerfile$

file:*.go
file:^.*\.go$

file:src/*
file:^/src/.*$
```

Language filter only change is we can specify an extension and it changes to the most popular language for it. This is a minor QOL for things like writing `lang:md` instead of `lang:markdown`. May be less important now that we can just write `file:*.md`.

For contents we have treat everything like literals that are ANDed together.

```
foo
foo

foo bar
foo AND bar

"foo bar"
foo bar

/a beautiful regex/
/a beautiful regex/
```

**Comment by stefanhengl** [comment]
This look good to me.

A couple of thoughts

- Should we also prototype a new syntax for `rev:`?
- How do we handle `type:`? Support the old syntax vs. not supporting it?
- Do we want to support `content:` or does `""` take that role?

**Comment by jtibshirani** [comment]
I added a clarification to https://github.com/sourcegraph/sourcegraph/issues/58799#issuecomment-1843187335 that we will stick with precise semantics and not apply stemming. Your plan looks good to me, I just had a question about this:

> TODO For more complicated use cases we need a way to fallback to regex. 

Do we really need to support a way to fallback to regexp in file filters? What's an example of where this is important?

**Comment by keegancsmith** [comment]
> * Should we also prototype a new syntax for `rev:`?

Yes, sorry I missed this will add something.

> * How do we handle `type:`? Support the old syntax vs. not supporting it?

I would hope we could get rid of this. Personally if starting from scratch you would just write repo:pattern, symbol:pattern, diff:pattern, etc.

> * Do we want to support `content:` or does `""` take that role?

Yes. Right now I think we will default to both file: and content: on unadorned terms. So we need a way to just do content.

> > TODO For more complicated use cases we need a way to fallback to regex.
> 
> Do we really need to support a way to fallback to regexp in file filters? What's an example of where this is important?

I don't have a good example off hand, but I like the idea of having powerful syntax as a fallback. Can punt on this problem while experimenting with these ideas to see if good examples come up?
