### ISSUE TITLE
Set embeddings limit interval from 1 month to “forever” for Pro users

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#58836]
I'm actually not sure if it's 1 month or forever now, but we should check it and ensure it's forever

**Comment by vdavid** [comment]
This is not a launch blocker.

Next step: Work with @chenkc805 to figure out the exact requirements and timeline here.

**Comment by chenkc805** [comment]
Exact requirements for Dec GA:
- 1 month refresh for both Free and Pro tier
- Free tier gets 220 MB per month
- Pro tier gets 1.1 GB per month

Long term for a future delivery date:
- Free user gets 200 MB lifetime + an additional 20 MB per month 
- Pro user gets 1 GB lifetime + an additional 1 GB per month

CC: @rafax for viz

**Comment by chenkc805** [comment]
Closing this as "not doing" because embeddings is not a priority for us anymore. CC: @taylorsperry @
