### ISSUE TITLE
Automation prototype feedback

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#5885]
# Bugs

### some campaign types don't work yet

- `Existing pull requests and issues` -> impossible to define rules, I couldn't get it working.

### Can't add external thread by ID

I couldn't get http://50.112.230.151:7990/projects/TEST/repos/gpujs--gpu.js/pull-requests/1/overview added to my campaign at http://theoa.sgdev.org/users/admin/campaigns/RXhwQ2FtcGFpZ246Mg==/threads -- no combination of org/repo and issue ID worked.

### commenting broken

I left a comment in a campaign and got this:

![image](https://user-images.githubusercontent.com/3173176/66275597-02426480-e83f-11e9-8932-a7747819be3a.png)

After refreshing it shows up correctly.

### Timeline incorrect when commenting on repository changeset

I commented on the top-level campaign first, then on one of the repository changesets and the order it is presented on the campaign is wrong:

![image](https://user-images.githubusercontent.com/3173176/66275716-43874400-e840-11e9-876c-e4c00ce1ba27.png)

### Threads -> filter by label hover color wrong in light theme

![](http://g.recordit.co/anIdjLKCFL.gif)

### Threads top-level button broken

![image](https://user-images.githubusercontent.com/3173176/66275862-c0ff8400-e841-11e9-8a66-e117882bbe20.png)

# UX feedback

### empty "rules ran successfully" state is janky

I created a new draft "Existing pull requests and issues" campaign and the display for "rules ran successfully" looks janky:

![image](https://user-images.githubusercontent.com/3173176/66275888-1fc4fd80-e842-11e9-8674-8253bc980165.png)

### Add threads dropdown very confusing

As a user, I have no idea what I should type in for `Number` and whether or not these are PR IDs on my code host or something Sourcegraph specific?

![image](https://user-images.githubusercontent.com/3173176/66275739-834e2b80-e840-11e9-8fad-d7ca6c59cd7b.png)

### Changes -> Repo links are not helpful

Clicking any of the repo links here, I am just brought to the repo themselves but I'd rather be brought to the change in the repo somewhere:

![image](https://user-images.githubusercontent.com/3173176/66275807-2d2db800-e841-11e9-84b4-b1530d6768d7.png)

### Sidebar actions are weird

- Why would I hit refresh there instead of in my browser bar?
- `Delete` what exactly? The whole campaign?

![image](https://user-images.githubusercontent.com/3173176/66275841-7ed64280-e841-11e9-9db3-33b22aaf69dd.png)

### Navigation tree having user first is not useful

I do not ever envision myself wanting to go back to the user profile who created a campaign, even if it is owned by that user:

![image](https://user-images.githubusercontent.com/3173176/66275647-94e30380-e83f-11e9-8093-94e1f9c194bf.png)

In practice, I would always want to land back on the global view at e.g. http://theoa.sgdev.org/exp/campaigns -- I think discovering "user's campaigns" view would be better done through a separate link somewhere on the page `View all campaigns by $USER`.

# Questions

### campaign ownership

If I delete a user, what happens to their campaigns? I can imagine wanting to delete old users but not lose their campaigns, is this possible?

- It seems odd to me that campaigns are owned by a user

**Comment by mrnugget** [comment]
Closing this for now, since it's not applicable to the current version of campaigns.
