### ISSUE TITLE
Settings UI does not indicate invalid input

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#5887]
- **Sourcegraph version:** As of 2f49dbb15d5baf3a15c12765dab89330cf157a64

#### Steps to reproduce:

1. Go to user settings
2. Change the value of the config JSON to be invalid. E.g,. something like "{}}"
3. Hit "Save Changes"

#### Expected behavior:

An error appears informing the user that the format is invalid.

#### Actual behavior:

You see the "Saving..." loading indicator, which indefinitely hangs. The contents of the editor silently revert back to what was previously saved in the backend.

**Comment by beyang** [comment]
@sourcegraph/web can you triage?

**Comment by lguychard** [comment]
Seems like a quick and valuable fix, I'll try to fit this in 3.9.
