### ISSUE TITLE
Deleted repo hangs on "Cloning in progress"

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#5890]
The repo https://github.com/renovatebot/docker-yarn apparently used to exist  because it shows up in `repo:` search results:

![image](https://user-images.githubusercontent.com/1976/66297715-0b661c80-e8a5-11e9-95d2-d189213754d2.png)

But it is now deleted on GitHub: https://github.com/renovatebot/docker-yarn 404s.

When I visit https://sourcegraph.com/github.com/renovatebot/docker-yarn, I expect to see a 404, but instead I see:

![image](https://user-images.githubusercontent.com/1976/66297755-1f118300-e8a5-11e9-9c80-118354bf7262.png)

**Comment by slimsag** [comment]
this is probably the same issue as https://github.com/sourcegraph/security-issues/issues/15

**Comment by keegancsmith** [comment]
Funnily enough, this repo now exists? Yeah the issue @slimsag links looks like the same issue. We need to handle removing repos once they are gone for Sourcegraph.com.

**Comment by tsenart** [comment]
Duplicate of #7843.
