### ISSUE TITLE
`sg setup`: Root certificate not installed if Caddy admin server is not running

### ISSUE THREAD

**Issue by bevzzz** [sourcegraph/sourcegraph#58926]
I recently needed to setup my local dev environment and ran into this small issue with `sg setup`.  In case `"Caddy root certificate is trusted by system"` check is not successful, the automatic fix is to install a new root certificate by running run `caddy trust`.  From [`caddy trust`](https://caddyserver.com/docs/command-line#caddy-trust) docs:   
_This command will attempt to connect to Caddy's admin API to fetch the root certificate, using the GET /pki/ca/<id>/certificates endpoint._

Now, if the admin server is not running at that moment, the GET request will not succeed, and the certificate won't be installed correctly.

<details><summary>See GIF</summary>

Commit [`57166ea80caa7e2eb7d9c8134b35c47997a0835c`](https://github.com/bevzzz/sourcegraph/commit/57166ea80caa7e2eb7d9c8134b35c47997a0835c) (latest as of now)

![before](https://github.com/sourcegraph/sourcegraph/assets/53943884/a20c0af3-4ab3-4a95-a7f1-dee6d17bba17)

</details>

**Comment by jhchabran** [comment]
fixed by a third party contrib
