### ISSUE TITLE
Rely on default for GRAFANA_SERVER_URL in frontend deployment

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#5900]
For most services we rely on a default which is the service address. eg See the default for `ZOEKT_HOST`. This is nice since its less stuff the admin has to worry about / get merge conflicts over.

https://github.com/sourcegraph/deploy-sourcegraph/blob/5b59488bd2a7f22662a1c18ec2f260ccec7d67c0/base/frontend/sourcegraph-frontend.Deployment.yaml#L51-L52

WDYT?

cc @sourcegraph/distribution

**Comment by beyang** [comment]
SGTM. The default host should be a port that isn't expected to conflict with anything else (e.g., not 3000)

**Comment by slimsag** [comment]
Yep, we should be doing this I agree.

In deploy-sourcegraph-docker I should note we do not do this though since
we want the connections between services to be clear. I.e. these two repos
differ in that respect.

**Comment by uwedeportivo** [comment]
i'll send a PR tonight

**Comment by uwedeportivo** [comment]
@keegancsmith could you please describe how the ZOEKT_HOST example works ? i'm not clear on it and doing an rg search on all our repos didn't yield any illuminating values ( i redacted some private repo results)

```
➜  sourcegraph rg ZOEKT_HOST
deploy-sourcegraph-docker/deploy-frontend-internal.sh
28:    -e ZOEKT_HOST=zoekt-webserver:6070 \

deploy-sourcegraph-docker/deploy-frontend.sh
29:    -e ZOEKT_HOST=zoekt-webserver:6070 \

sourcegraph/CHANGELOG.md
442:- When using an external Zoekt instance (specified via the `ZOEKT_HOST` environment variable), sourcegraph/server no longer spins up a redundant internal Zoekt instance.

sourcegraph/dev/launch.sh
62:export ZOEKT_HOST=localhost:3070

sourcegraph/cmd/server/shared/zoekt.go
11:	if os.Getenv("ZOEKT_HOST") != "" {
16:	SetDefaultEnv("ZOEKT_HOST", defaultHost)

sourcegraph/cmd/frontend/internal/pkg/search/env.go
16:	zoektAddr   = env.Get("ZOEKT_HOST", "indexed-search:80", "host:port of the zoekt instance")
➜  sourcegraph 
```

is it just what we do here: sourcegraph/cmd/frontend/internal/pkg/search/env.go

the problem is that i use the GRAFANA_SERVER_URL value as a signal that grafana is not configured/running when the value is empty.

**Comment by keegancsmith** [comment]
Yes we don't rely on ZOEKT_HOST being unset to indicate no grafana. Instead we do expose a way to disable connecting to zoekt in the config.

In which context is grafana not configured/running? We could explicitly set the variable to empty? We may need to update some code to distinguish between unset and empty string.

**Comment by uwedeportivo** [comment]
i think in this case having the not-set value is preferable since the value is not the same across contexts and if we forget to set it in the contexts in which it's different we get a weird error instead of the nice page explaining that we need to set it.
