### ISSUE TITLE
Add New Search Result filter panel UI

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#59082]
Design issue https://github.com/sourcegraph/sourcegraph/issues/58371

In this issue we should add new search result panel plan (Figma [design](https://www.figma.com/file/EPgl0qVbqGSumvf52brhda/Improving-search-results?type=design&node-id=30-6646&mode=design&t=2D6heSXbRQhfXyYx-0))

Some notes from the latest meeting about this UI 

- The biggest change what we agreed on is we do not update the search query value as you select something in the filter panel
- Instead we will store selected filters values separately from the original query but still in the URL param
- So when you’re on the search results page and you select some filter the next flow happens
  - we will update filters value in the URL
  - search box query will not be updated
  - we will sum up (combine) the original query + filters value from the URL and re-run the search
  - so you will see new filtered search results and selected filters in the filters panel
- There is an idea that in the second iteration we still could render filters-like query value in the search box but just style them differently (the idea from 
- [@rob](https://sourcegraph.slack.com/team/U012SFU7BNJ)
 about having placeholder/chips in the search query UI)
- Filters are sharable, since they are part of URL you should be share URL with other users and they will see same set of filters
- In the first iteration we give up on multi-selection approach (when you select let’s say a repository from the filter picker since we immediately update (re-run the query) the search-results by filters you won’t be able to select second repository in the filters)
- There was an idea from 
[@Felix Kling](https://sourcegraph.slack.com/team/U0223UPMWLF)
 to run two search query to populate the filters panel separately form the search results to be able to pick multiple values but this will be our follow up after the first implementation
- We currently don’t think we need another RFC for it, I hope I will implement this in time and we would be able to ship this in the January release and after this based on user feedback we will write up RFC for the second iteration of filters (this is where the big changes will happen as I think)

**Comment by camdencheek** [comment]
Closing as done
