### ISSUE TITLE
Minimal reference panel

### ISSUE THREAD

**Issue by fkling** [sourcegraph/sourcegraph#59138]
Implement a simple version of the reference panel that shows a list of references, without a preview.
Selecting a reference should update the main view. Unlike the current version this should keep the reference panel open. It would also be great if using the back button would restore the content of the reference panel.

Suggestions from @varungandhi-src about how to get started:

> On fetching the relevant data, I'd use the same API that is currently being used here for precise code intel: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@9d821b78b68760e8f636f92cf8e5afd599c74ea5/-/blob/client/web/src/codeintel/ReferencesPanelQueries.ts?L46
>
> Potential simplification: use a high `firstReferences` value and don't add support for pagination for the first pass.
>
> For the fallback behavior to search-based code intel, it might somewhat simpler to reuse the existing code here. https://sourcegraph.com/github.com/sourcegraph/sourcegraph@9d821b78b68760e8f636f92cf8e5afd599c74ea5/-/blob/client/web/src/enterprise/codeintel/useSearchBasedCodeIntel.ts?L318 instead of talking to the API directly.
>
> For both of these, ideally we'd have an API where you pass in a SCIP symbol string instead of a position, but that's not implemented.

### Other issues to consider

- https://github.com/sourcegraph/sourcegraph/issues/40720
- https://github.com/sourcegraph/sourcegraph/issues/30973
- https://github.com/sourcegraph/sourcegraph/issues/30972

**Comment by fkling** [comment]
I started to work on this (branch `fkling/sk/reference-panel`) and it somewhat works. It's not satisfying to use though because of #59135. Even with this fixed though I don't know if we can make it work reliably with full page scrolling and a bottom panel. The core issue is that the bottom panel is "floating" above the scrollable area. In my testing it happened quite often that after clicking on a reference, the "target" lines have been positioned underneath the bottom panel and it looked the navigation didn't work.

I think before investing more time into this we need to make decisions about

- where to position the reference "panel" (i.e. will we continue to have a bottom panel)
- do we want to keep full page scrolling


FWIW, this is what the WIP version looks like:



![Image](https://github.com/sourcegraph/sourcegraph/assets/179026/7a838623-3621-4fff-9b6c-70ac85be2491)

**Comment by taiyab** [comment]
@fkling Apologies I haven't had a chance to get to this just yet.

Feel free to keep going with your version if you've got time. We can then pair on it a bit when I'm back from holidays.
