### ISSUE TITLE
`bazel query|test|build //...` should throw no errors (other than real build/test issues)

### ISSUE THREAD

**Issue by burmudar** [sourcegraph/sourcegraph#59155]
Right now, it does fail on some linux only things that we only build in CI or require some env vars.

**Comment by jhchabran** [comment]
First step is to map what's failing, creae tickets, then we dispatch them

**Comment by jhchabran** [comment]
An example of stuff that can happen when using the root glob: https://gist.github.com/slimsag/ced4720679e08882f117ae607e363902

**Comment by Strum355** [comment]
Here is a potential solution to the errors shown in the screenshot in the attached issue. Its not _as_ bulletproof yet as itd ideally be (see some further questioning on this front [here](https://sourcegraph.slack.com/archives/C05FDP58LRF/p1705583636603129?thread_ts=1705581394.840339&cid=C05FDP58LRF)) but we can iterate on that. Tests failing should give us indication of user error anyway :zany_face:  https://github.com/sourcegraph/sourcegraph/pull/59675

**Comment by jhchabran** [comment]
Python thing workaround: `--action_env="ASDF_DATA_DIR=/Users/tech/.asdf" --action_env="ASDF_PYTHON_VERSION=3.10.2"`

**Comment by jhchabran** [comment]
TODO ask Stephen about what's going on on his side, and have him run `sg doctor`
