### ISSUE TITLE
Search input is not focused on load

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#59174]
1. Go to https://sourcegraph.com/search

Expected: the search input is focused

Actual: it's not

It used to autofocus but is not anymore.

cc @sourcegraph/code-search 

---

https://twitter.com/janniksco/status/1737810910243078320

> any reason the search bar isn't auto-focused when opening [https://sourcegraph.com/search](https://t.co/pWXSn803UZ) ?

**Comment by peterguy** [comment]
[internal Slack convo](https://sourcegraph.slack.com/archives/C05MHAP318B/p1703178819303539) - summary is that the behavior change was intentional, but needs to be revisited.
