### ISSUE TITLE
LSIF: error cleaning worker queues

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#5917]
On 3bb9583ee0c5c43479dda2c46232d4208cda6ef8 (lsif-logging branch), I ran into this error:

```
18:24:06            lsif-server | ERROR scheduler error {
18:24:06            lsif-server |   service: 'lsif-server',
18:24:06            lsif-server |   error: 'force-cleaning worker REDACTED, but cannot find queues'
18:24:06            lsif-server | }
```

I don't see a stack trace, so I'm not sure where this is coming from.

**Comment by efritz** [comment]
It comes from https://github.com/sourcegraph/sourcegraph/blob/3bb9583ee0c5c43479dda2c46232d4208cda6ef8/lsif/src/server.ts#L192. It's an issue that occurs when a worker exits forcibly (via Ctrl+C or a signal).

It doesn't affect running, but it is an error according to node-resque.

**Comment by chrismwendt** [comment]
Got it, do you think any action could be taken here? If it doesn't affect running, would it make sense to suppress this log message?

**Comment by efritz** [comment]
Yeah I think suppressing this message would be an ok course of action. It's not really useful as-is.

**Comment by efritz** [comment]
Resolved by https://github.com/sourcegraph/sourcegraph/pull/5934.

**Comment by chrismwendt** [comment]
I saw this error again. This logic looks right to me, not sure what's wrong:

https://github.com/sourcegraph/sourcegraph/pull/5934/files#diff-4b1942f67e502286b26a153792ad2557R166

**Comment by efritz** [comment]
Did you see this in prod? If so, that container is old (I think).

**Comment by chrismwendt** [comment]
Nope, local dev on d0ec714afe94d38d8af15328eb69f2c3d312c323 `lsif-cache-ttl` branch
