### ISSUE TITLE
SAMS integration

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#59270]

**Comment by taras-yemets** [comment]
SAMS integration is developed ([code](https://github.com/sourcegraph/cody-analytics/blob/6242fd2f2e55a0c8d0d6dde41d26ec46ee88cd2e/internal/httpapi/handler.go#L21-L23)). It may need some additional configuration after the Cody Analytics service is deployed (https://github.com/sourcegraph/sourcegraph/issues/59276) but for now the main development work I consider to be done.
