### ISSUE TITLE
(TBD) Associate instance URLs with accounts

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#59274]
Currently instance URLs and accounts we use to log into cody analytics are manual. @taras-yemets mentioned we could put that metadata into SAMS, so that the setup is streamlined; However we need to be clear about understanding the goal here. Let's start with understanding how exactly will this streamline onboarding onto analytics.

**Comment by taras-yemets** [comment]
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/60918
