### ISSUE TITLE
Exception on GitHub search result pages: "Could not find commit link in snippet code view"

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#5932]
From Sentry: https://sentry.io/organizations/sourcegraph/issues/1264421932/events/9dc7a4ffcaa6425aa5f2806caa63306a/

Example page: https://github.com/75nineteen/order-simulator-woocommerce/search?q=WooCommerce+test&unscoped_q=WooCommerce+test

**Comment by vdavid** [comment]
The Sentry link doesn't work anymore.
We (@philipp-spiess and I) looked into Sentry and didn't find "Could not find commit link in snippet code view" in the past 14 days.
Also not seeing any error message in the console for the example page.
So closing this.
