### ISSUE TITLE
☂️  Search Jobs

### ISSUE THREAD

**Issue by stefanhengl** [sourcegraph/sourcegraph#59352]
P0: for 5.3 release
- [x] #59329  
- [x] Make search jobs available in UI by default

P1: future release
- [ ] support type:repo
- [ ] support type:diff, type:commit ([context](https://sourcegraph.slack.com/archives/C05KARB1F33/p1703094344907599))
- [ ] #59354

**Comment by jtibshirani** [comment]
5.3 release status: ✅ All set, not aware of any remaining work.
