### ISSUE TITLE
LSIF: stale data in caches

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#5936]
(This doesn't repro anymore because I restarted the lsif-server container)

- Visit https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/auth/gitlaboauth/login.go#L80:16
- Click on j2d to "NewClientProvider"
- Observe the error page (Git ls-tree pkg/extsvc/gitlab/client.go: file does not exist)

I suspect that internal caches were holding stale data and not getting invalidated upon upload.

**Comment by efritz** [comment]
We need a way to invalidate caches after a new database has been created. I'll draft an RFC for this and use this issue as a tracker.

**Comment by tsenart** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.9 release is scheduled for tomorrow** at 10:00 CEST.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by efritz** [comment]
Should be taken care of. See https://github.com/sourcegraph/sourcegraph/pull/5961#issuecomment-541923870 for context.
