### ISSUE TITLE
Filters: hover state on clickable filters

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#59443]
Currently, there is no reaction to hovering over filters. It seems strange since, when clicked, they turn into cards.

**Comment by camdencheek** [comment]
@taiyab I couldn't find any design for hover state in figma. But I could just be using it wrong. Is this something that's part of the designs? If not, was it intentional to not have any reaction to hovering over a filter?

**Comment by taiyab** [comment]
@camdencheek Can you screenshot what you're referring to specifically? Thanks.

**Comment by camdencheek** [comment]
When I hover over one of the filters, I expect the background color to change. Here's an example from github:


https://github.com/sourcegraph/sourcegraph/assets/12631702/d9f3f21e-a4f8-4975-9c04-4f0dd17f9e91

**Comment by taiyab** [comment]
![Recording 2024-01-09 at 18 34 38](https://github.com/sourcegraph/sourcegraph/assets/5337876/9a8ef0cd-cd0c-4900-adf3-88cd056b52aa)

You mean this? Yea, all the options have hover states. Pretty much everything has a hover state.

**Comment by camdencheek** [comment]
aha! I couldn't find the interactive mode of Figma. 

Looks like hovers states are missing from the dark mode in the current implementation. Looks like it works fine in light mode though.

**Comment by jasonhawkharris** [comment]
@camdencheek I can take this one.
