### ISSUE TITLE
Replace "Show all" with "Show more [X]" in the truncated filter list UI

### ISSUE THREAD

**Issue by jasonhawkharris** [sourcegraph/sourcegraph#59440]

**Comment by taiyab** [comment]
@jasonhawkharris Sorry, can we reopen this?

My bad. I didn't make it clear that the desired behaviour was already in place prior to this commit, in that clicking the more link would open up an additional 5 results, then switch to a show less link, to then hide the last 5 items in the list.

Are we OK as that being the behaviour? @camdencheek @BolajiOlajide @vovakulikov @jasonhawkharris?

Apologies!
