### ISSUE TITLE
Search Filters: Connect existing telemetry to the new filters UI and add new events

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#59450]
So the new filters UI doesn't have anything about telemetry at the moment, the only thing we track is query which doesn't change since filters doesn't affect it anymore. 

In this issue we should connect telemetry event that still make sense from old filter panel and add new events for new type of filters that we've added.

**Comment by taiyab** [comment]
I posted this too https://github.com/sourcegraph/sourcegraph/issues/59971 not sure how much of this covers that.
