### ISSUE TITLE
Design Search landing page

### ISSUE THREAD

**Issue by BolajiOlajide** [sourcegraph/sourcegraph#59472]

**Comment by taiyab** [comment]
[Initial drafts ](https://www.figma.com/file/QTaYwlaKM7c7Gh7oevPvoX/Cody-Licensing?type=design&node-id=83%3A52826&mode=design&t=RUNTXMio8nGgP6Ct-1)of this are done. Just awaiting commentary and approval.

**Comment by taiyab** [comment]
This is done (bar tweaking and implementation with Bolaji).

When you don't have Code Search: https://www.figma.com/file/QTaYwlaKM7c7Gh7oevPvoX/Cody-Licensing?type=design&node-id=432%3A81370&mode=design&t=oEyiL6acMwUcLd1N-1

When you have Code Search: https://www.figma.com/file/QTaYwlaKM7c7Gh7oevPvoX/Cody-Licensing?type=design&node-id=83%3A52789&mode=design&t=oEyiL6acMwUcLd1N-1
