### ISSUE TITLE
Search UX: "no results" page mentions structural search

### ISSUE THREAD

**Issue by jtibshirani** [sourcegraph/sourcegraph#59492]
For the upcoming 5.3 release, structural search will be disabled by default. However, the no results page still shows the structural search icon and mentioned "structural search". It'd be good to update this image and explanation.

Note: this is not a super high priority, just filing as a "nice to have".

/cc @sourcegraph/search-platform

**Comment by jtibshirani** [comment]
Here's what the "no results" page looks like. Structural search is mentioned at the bottom:

![Screenshot 2024-01-10 at 1 09 54 PM](https://github.com/sourcegraph/sourcegraph/assets/7461306/d9acb2a0-038b-4faf-8b44-1204bb9b1228)

**Comment by jtibshirani** [comment]
Here's what the "no results" page looks like. It mentions structural search at the bottom:

![Screenshot 2024-01-10 at 1 09 54 PM](https://github.com/sourcegraph/sourcegraph/assets/7461306/da9eafbb-278b-437e-8320-defae36c085d)

**Comment by stefanhengl** [comment]
The image has been removed.
