### ISSUE TITLE
Use higher-contrast text colors

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#595]
From Zeplin:

@sqs:
> The text here is all white, not the faded color we use as the default text color. I personally really like the increased contrast of this white. Do you intend to change all text color to this white? I can do that if so

@francisschmaltz:
> I really like using all white. I think there are implications to doing this, but from a accy and legibility standpoint im all for it.

**Comment by sqs** [comment]
Ping @francisschmaltz

**Comment by francisschmaltz** [comment]
Low Priority. Pushing back to 3.1
