### ISSUE TITLE
Go code intelligence error in sourcegraph/sourcegraph

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#5955]
Repro:
* Go to https://sourcegraph.com/github.com/sourcegraph/sourcegraph@ba77c414ce66b4d1149b9925a91218e6b05ad1e2/-/blob/internal/db/dbconn/dbconn.go#L218:40
* On line 218, click on `NewMigrationSourceLoader`
* You end up on a generated file, [bindata.go](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@ba77c414ce66b4d1149b9925a91218e6b05ad1e2/-/blob/migrations/bindata.go#L5549:6), instead of [the actual function definition](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@c1a6fddcd599346c7e038de906e96ecfdd42f888/-/blob/internal/db/dbutil/dbutil.go#L114:6)

**Comment by efritz** [comment]
It's outdated LSIF data. If you look at the hovers it's trying to move you to a gobindata Asset.

**Comment by chrismwendt** [comment]
Temporarily fixed by deleting all sourcegraph/sourcegraph LSIF dumps and restarting the lsif-server pod, but it's still possible for us to accidentally upload more LSIF data that gets stale. The real fix is to invalidate the caches https://github.com/sourcegraph/sourcegraph/issues/5936
