### ISSUE TITLE
On “Upgrade to Pro”, redirect from dotcom to SSC

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#59623]

**Comment by chrsmith** [comment]
What is the URL we are planning on redirecting users to? We may want to have two different URLs depending on the context? (Or just change the UI based on the user account.)

As a proposal, why don't we just redirect users to:
https://accounts.sourcegraph.com/cody/subscription

And then when that page loads, we:

- If the user doesn't have a Cody Pro subscription, show them the "signup flow".
- If the user has an active or canceled Cody Pro subscription, show the "subscription management" page.

**Comment by thenamankumar** [comment]
Makes perfect sense to me @chrsmith
