### ISSUE TITLE
Dotcom: Expose Subscription details through GraphQL

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#59620]
Expose these pieces of info:
- “Is user on Cody Pro”
- “is subscription active/past_due”
- “when will it cancel”.

Why?
- For clients and `/cody/manage` to consume.

How?
- Just proxy the requests to SSC. On the SSC side, we already have these exposed—see [this](https://github.com/sourcegraph/accounts.sourcegraph.com/pull/259/files#diff-b01dfe047d5c62ac4cb93d7420beefb09bc65dbbc7ad22ab6f3a4155c4e19938R15).

**Comment by chrsmith** [comment]
Adding a note with a few more requirements, @thenamankumar:

We need to do this in such a way that we don't require all dotcom / Cody Pro users be migrated or existing in the SSC/SAMS database. So the logic is slightly tricky.

If the user has signed up for the cody_pro trial, but dotcom doesn't have any SAMS info for the user, then we do _not_ need to fetch their subscription information from SSC. Instead, we just hard-code them being on a free trial that will end on 2/15. (And after 2/15, we say that their Cody Pro subscription has been canceled.)

For users that are on cody_pro AND have SAMS info, _then_ we should fetch their subscription information from SSC. This will also account for users that have entered their payment information on the SSC website prior to 2/15.

[This Slack Thread](https://sourcegraph.slack.com/archives/C05SZB829D0/p1705100026684459?thread_ts=1705085764.652129&cid=C05SZB829D0) captures the context here.
