### ISSUE TITLE
Gateway: Add SAMS/SSC Actor Source

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#59625]
Integrate SAMS access_token based rate limiting.
Preferred Option: gateway directly calls SSC to get the limits against the SAMS token.

- Remove SSC->dotcom integration to trigger rate limit refresh

**Comment by vdavid** [comment]
@thenamankumar, shall we mark this as post-Feb?

**Comment by thenamankumar** [comment]
There are continuous decision changes happening, so I don't know. https://sourcegraph.slack.com/archives/C05SZB829D0/p1705926652720929

**Comment by vdavid** [comment]
For the record, linking yesterday's [discussion](https://sourcegraph.slack.com/archives/C05SZB829D0/p1706621791588619) where we confirmed it is post-Feb.

**Comment by vdavid** [comment]
Let's also add a direct CG <-> SSC integration with a service-to-service call, and get rid of these retries: https://github.com/sourcegraph/accounts.sourcegraph.com/pull/583 and Cody Gateway's public API endpoint with the 10-second cooldown.

**Comment by chrsmith** [comment]
We will not be doing this any time soon. So let us close this ticket out, and when we do plan on adding a SAMS/SSC actor source to Cody Gateway we can create a new ticket then.

This topic comes up in [Design Doc:
Making Cody Gateway SAMS Aware](https://docs.google.com/document/d/1U1L1dG1guvxRH7ZhzWZsFwLJaTPk7mQlJxPi45ypf3o/edit#heading=h.lzbbie699j8o). But in short we cannot realistically update Cody Gateway to require a SAMS token for user-facing requests until we first update Cody clients to communicate with SAMS directly for log-in. (And that isn't something we have concrete plans to do this quarter.)

So the plan of record is to update Cody Gateway to utilize SAMS tokens for machine-to-machine communication. But keep using the `dotcomuser.Source` like we do today, for authenticating requests related to users using Cody.
