### ISSUE TITLE
Design Cody landing page

### ISSUE THREAD

**Issue by BolajiOlajide** [sourcegraph/sourcegraph#59627]

**Comment by taiyab** [comment]
[Initial drafts](https://www.figma.com/file/QTaYwlaKM7c7Gh7oevPvoX/Cody-Licensing?type=design&node-id=83%3A52797&mode=design&t=RUNTXMio8nGgP6Ct-1) of the design are done. Just awaiting commentary and approval.

**Comment by taiyab** [comment]
Bar a few tweaks and liasing with Bolaji on implementation, this is done.

When you don't have Cody for enterprise: https://www.figma.com/file/QTaYwlaKM7c7Gh7oevPvoX/Cody-Licensing?type=design&node-id=571%3A94663&mode=design&t=oEyiL6acMwUcLd1N-1

When you have Cody for enterprise: https://www.figma.com/file/QTaYwlaKM7c7Gh7oevPvoX/Cody-Licensing?type=design&node-id=83%3A52818&mode=design&t=oEyiL6acMwUcLd1N-1
