### ISSUE TITLE
Move to service-to-service authentication between SSC and dotcom

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#59621]
@unknwon created a pair of PRs to demo how machine-to-machine auth works against SAMS between dotcom and SSC using the standard OAuth2 protocol:
https://github.com/sourcegraph/sourcegraph/pull/59783
https://github.com/sourcegraph/accounts.sourcegraph.com/pull/347
This could be a good starting point for this.

**Comment by vdavid** [comment]
Currently blocked, see [this thread](https://sourcegraph.slack.com/archives/C05SZB829D0/p1705402188431279)

**Comment by chrsmith** [comment]
This is well under-way.

**Comment by chrsmith** [comment]
https://github.com/sourcegraph/sourcegraph/pull/59911 should be sufficient for us to close this ticket out. Although it only enables dotcom<->SAMS-prod. https://github.com/sourcegraph/sourcegraph/issues/59786 tracks making this configurable, so we can test subscription data coming from SAMS-dev as needed.

**Comment by chrsmith** [comment]
With https://github.com/sourcegraph/sourcegraph/pull/59911 merged, we can close this out. 🎉
