### ISSUE TITLE
Add Dotcom auto-redirect to SAMS (unless operator)

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#59634]
The logic should be: “IF Sourcegraph op is the only signin option besides SAMS THEN auto-redirect EXCEPT if the ?sourcegraph-operator flag is there in the URL”

See [this thread](https://sourcegraph.slack.com/archives/C05SZB829D0/p1705337441038019?thread_ts=1705335253.881089&cid=C05SZB829D0)

**Comment by unknwon** [comment]
We need to make sure this is dotcom-only code logic, otherwise on-prem users won't be able to sign out (because non-dotcom SG always redirects back to sign-in page after sign-out) cc @DaedalusG who worked that fix IIRC.
