### ISSUE TITLE
Bitbucket native integration doesn't work on Firefox

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#5969]
- **Sourcegraph version:** 3.8.2
- **Platform information:** Bitbucket Server, Firefox

A customer reported that the Bitbucket Server native integration wasn't working for them. When they checked the JavaScript console errors, they discovered why:

>re. the bitbucket issue. I looked at it a bit closer now and actually on firefox it doesn't work at all. I see this error in the dev console in firefox:
>
>ReferenceError: chrome is not defined integration.bundle.js:7324
>
>I just installed google chrome and there it works. So it's actually the compatibility with firefox thats not working. The experience of the extension in chrome seems more polished in general compared to what i get with the dedicated firefox browser extension.

Just curious, is this a bug, or expected?

**Comment by lguychard** [comment]
This is not expected.

**Comment by felixfbecker** [comment]
Verified this doesn't happen anymore on https://bitbucket.sgdev.org with k8s.sgdev.org
