### ISSUE TITLE
Blog template is broken on pages that scroll

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#597]
https://about.sourcegraph.com/blog/introducing-sourcegraph-server-2-4

![screenshot from 2018-10-30 00-35-43](https://user-images.githubusercontent.com/1976/47702937-be30f380-dbdb-11e8-956a-0d7401fb401d.png)

**Comment by francisschmaltz** [comment]
@sqs this is broken on all pages that are rendered from MD files. This is a major regression

**Comment by francisschmaltz** [comment]
The issue seems to be that this blog post https://about.sourcegraph.com/blog/introducing-sourcegraph-server-2-4 duplicates the footer so navigating to another page rendered from MD has the issue (the page never reloads).

**Comment by attfarhan** [comment]
Fixed. There was some custom HTML to accommodate an old gif that was causing this, so I removed the old gif + HTML.
