### ISSUE TITLE
Notice Banner Color Selection

### ISSUE THREAD

**Issue by Robertwadelinger** [sourcegraph/sourcegraph#59751]
#### Feature request description

The options for banners in global settings gives us 3 parameters to work with. It would be helpful if we could add a fourth to define the color of the banner, for instances where a given customer levees the requirement onto us.

Example:
`"notices": [   `<br>`
  {   `<br>`
    "message": "Your message here! [Include a link for more information](http://example.com).",   `<br>`
    "location": "top",   `<br>`
    "dismissible": true,   `<br>`
    "color": #FF0000   `<br>`
  }   `<br>`
]` 

(might also need a KV pair for banner text color)
 
#### Is your feature request related to a problem? If so, please describe.

May be an issue for some customers that have set standards on banner colors.

#### Describe alternatives you've considered.

Could change the CSS on each build, but that would not scale well.

#### Additional context

Code for Notice configuration is found here: doc/admin/config/settings.md

**Comment by aramaraju** [comment]
@cbart have we talked to Rik about this already to get this rolling?

**Comment by cbart** [comment]
@RXminuS can you prioritize this (even when it means we pause the diagnostics work for a little bit)?

**Comment by RXminuS** [comment]
Sorry wasn't aware this was something I had to look at. Will try and get my dev setup working and jump on it.

**Comment by RXminuS** [comment]
@aramaraju What's the actual use-case of these colors?

> May be an issue for some customers that have set standards on banner colors.

Wouldn't this more fall under theming then? So that they can say "alerts must be pink" etc? Because the more I'm looking at it the more I think we should just expose the notice variant so that you can specify if it's an error/info/warning rather than overriding specific style elements for this one element.

**Comment by RXminuS** [comment]
Yeah https://github.com/sourcegraph/sourcegraph/pull/61338 is the PR. Aravind suggested for search team and Meadah to add docs. I've added some basic docs myself but don't think they've had the time yet to look.

If you're happy with it I can quickly resolve the conflict and merge in. Then this should be resolved
