### ISSUE TITLE
Make sure dotcom and gateway don't log sensitive data from attribution calls

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#59776]
This work is to make sure that snippetAttribution invoked by gateway on dotcom does not log any sensitive information.

Gateway handler: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@dd34d1be076e69b3becf3cb7b6047aab668f4685/-/blob/cmd/cody-gateway/internal/httpapi/attribution/handler.go?L25

GraphQL resolver: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@dd34d1be076e69b3becf3cb7b6047aab668f4685/-/blob/cmd/frontend/internal/guardrails/resolvers/resolver.go?L17

- [x] Remove graphQL resolver logger in dotcom [link](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@5db45a0111b95f701f4702b93dc5c482aadd2085/-/blob/cmd/frontend/internal/guardrails/init.go?L37) #60464
- [x] Slow request logging in dotcom for attribution search
  - this is generally disabled on dotcom
- [ ] Audit log of graphQL [link](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/schema/site.schema.json?L1671%3A1-1675%3A15)

**Comment by andreeleuterio** [comment]
@cbart I'm following up on removing the logger from the search client altogether.

**Comment by cbart** [comment]
Audit log is not turned on for dotcom and [default setting is false.](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/schema/site.schema.json?L1677)

**Comment by cbart** [comment]
I'll file follow-up PRs to redact logging of this specific operation even when it's turned on.

**Comment by cbart** [comment]
https://github.com/sourcegraph/sourcegraph/issues/60555 filed.
