### ISSUE TITLE
docs: report minimum Postgres version supported (particularly for external dbs)

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#5978]
Reported by a customer: 
* https://app.hubspot.com/contacts/2762526/company/623971957

Our docs don't specify a minimum supported version of Postgres anywhere. I'm not sure if this is the right page for it to live in long-term, but https://docs.sourcegraph.com/admin/external_database should definitely have that info (or link to the product/dev docs page that does)!

See https://sourcegraph.slack.com/archives/CHPC7UX16/p1570832777037500 for discussion on the answer

**Comment by unknwon** [comment]
OK, I just found we do have version specified:

![image](https://user-images.githubusercontent.com/2946214/66690320-31dcdc80-ec44-11e9-90ab-a348a3ce5c2e.png)

![image](https://user-images.githubusercontent.com/2946214/66690326-3b664480-ec44-11e9-8d29-d885ed5e296c.png)

**Comment by keegancsmith** [comment]
@dadlerj given what @unknwon says above, is there any action we need to take?

**Comment by dadlerj** [comment]
Yeah Stephen also called that page out in the Slack discussion — that page is a bit weird, since it's focused on the 3.0 upgrade... Is that the right place for it? It's weird to me that it shows up there, on a page focused on a specific upgrade (sort of), rather than on a general external DB page. That said, I'm not totally sure what's ideal here, so I leave it up to the Core team as owners of these pages to just put it somewhere that would be clear to users.

**Comment by slimsag** [comment]
Sent PRs to fix this:

https://github.com/sourcegraph/deploy-sourcegraph/pull/438
https://github.com/sourcegraph/sourcegraph/pull/6418
