### ISSUE TITLE
Update dotcom to use SSC as the only source of truth for all subscription data.

### ISSUE THREAD

**Issue by thenamankumar** [sourcegraph/sourcegraph#59785]
This includes the following:

- Remove the `cody. consolidate` subscription details and use the SSC subscription directly.
- Removing "pending" status for user subscription.

**Comment by chrsmith** [comment]
Let's close this ticket out in favor of https://github.com/sourcegraph/accounts.sourcegraph.com/issues/642.

-Remove the cody. consolidate subscription details and use the SSC subscription directly.

This is part of the solution, yes. But I believe we also need to account for per-user rate limit overrides. Which is also part of the equation.

- Removing "pending" status for user subscription.

This has already been done as part of landing cleanups related to the aftermath of the Feb-launch.
