### ISSUE TITLE
Compact Search Results

### ISSUE THREAD

**Issue by AJKemps** [sourcegraph/sourcegraph#59817]
#### Feature request description

Requested by: https://github.com/sourcegraph/accounts/issues/6938

#### Is your feature request related to a problem? If so, please describe.

"We've heard from a few people that they've gone back to using our internal Code Search (CS) from Sourcegraph because they really like CS's compact display. Here's an example of the difference showing two screenshots taken at the same size."

![MicrosoftTeams-image (5)](https://github.com/sourcegraph/sourcegraph/assets/62579992/962eab7a-54bd-4ab2-9aa9-6e238b11d3d4)
![MicrosoftTeams-image (6)](https://github.com/sourcegraph/sourcegraph/assets/62579992/b1b3b68c-8eee-4a55-b8ee-d6d631940ff6)

#### Describe alternatives you've considered.

Some users are reverting back to their internal code search tool that the customer is looking to deprecate in favor of Sourcegraph because search results density is too low.

#### Additional context

It might be nice to toggle this on and off -- there are times, usually early in the search process, when a user wants to see as many results as possible and the preview is less important to them, but eventually once they've refined their query they'll want to toggle the preview back on

/cc @sourcegraph/search-product

**Comment by camdencheek** [comment]
We significantly improved the information density of results in https://github.com/sourcegraph/sourcegraph/pull/59834. I think that should address this request
