### ISSUE TITLE
Fix up the Cody Management page to work with all subscription statuses

### ISSUE THREAD

**Issue by thenamankumar** [sourcegraph/sourcegraph#59823]
- update Free Tier Until...
- update usage renews at...
- update copy for subscription management
- add a banner for pro opted pending subscription users, may be

**Comment by vdavid** [comment]
@thenamankumar, could you leave some notes on what these items are before you sail over to Noodle land?

**Comment by thenamankumar** [comment]
This was part of Feb Release work and is already resolved.
