### ISSUE TITLE
Search pagination API should be fully a Modern Relay pagination model

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#5983]
Modern Relay pagination similarly uses cursor-based pagination, but it is more standardized and has the nice property of being able to paginate backwards: https://facebook.github.io/relay/graphql/connections.htm#sec-Edges

In https://github.com/sourcegraph/sourcegraph/pull/4796 I independently implemented cursor-based pagination, not very aligned to Modern Relay, and Joe suggested I look into the above instead. Getting this to be Modern Relay-compliant (so to speak) is going to require a bit of work, we will need to:

1. Implement `hasPreviousPage` for [all existing `Connection` objects we have](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:schema.graphql+type+.*Connection) in our GraphQL API (see also: "Our GraphQL pagination types are a year out of date #5982").
2. Implement `hasPreviousPage` and backwards cursor pagination for paginated search -- should be easily done I think but will take a reasonable amount of time to do.
3. Redefine the search API (declare a new one?) to include a modern `SearchConnection` object instead of returning our existing `Search` type.

**Comment by felixfbecker** [comment]
Are we only _missing_ fields, or are we incompatible in a way that would need breaking changes?

**Comment by efritz** [comment]
Also note that while all page info objects may be able to tell you if they have a previous page, some connections may need to always return false first such a.m query due to the underlying data model (you can page forwards easily but is difficult to reverse).

**Comment by slimsag** [comment]
As noted in the description, point #3 would either be a breaking change or would require adding a new `search` resolver that returns a different type. Otherwise, as noted in the description, we are missing fields.

**Comment by slimsag** [comment]
(note this issue is backlogged, I view these as nice-to-haves)

**Comment by lguychard** [comment]
Pagination has been removed.
