### ISSUE TITLE
Remove SAMS origin control via feature flag for testing after release.

### ISSUE THREAD

**Issue by thenamankumar** [sourcegraph/sourcegraph#59839]
Undo the testing specific changes done as part of this [PR](https://github.com/sourcegraph/sourcegraph/pull/59838), once the prod testing is performed and SAMS & SSC are fully released.

**Comment by chrsmith** [comment]
The linked PR was never merged. And a quick GitHub code search didn't find any hits for the flag `use-sams-test-instance`. So I think this isn't required.
