### ISSUE TITLE
Link usage limit renews_at with TTL info from gateway

### ISSUE THREAD

**Issue by thenamankumar** [sourcegraph/sourcegraph#59855]
The usage renews at the timestamp is synthetically generated and does not reflect the actual source of truth which is cache TTL on cody gateway. 

Better time to make this improvement is once we add SSC as a separate actor source on dotcom.

**Comment by chrsmith** [comment]
@thenamankumar , how does this issue relate to this one: https://github.com/sourcegraph/sourcegraph/issues/59990

Is this a dupe of that? Or is it just a related-type of scenario where we need to integrate "subscription details" with Cody Gateway's internal TLLs and tracking data?

**Comment by thenamankumar** [comment]
Its a dupe. Closing this one in favour of #59990
