### ISSUE TITLE
Search results: do not fetch highlighted blob content for path results

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#59866]
Currently, when a path result (a file result with no matched ranges) scrolls into view, we fetch the full highlighted file content even though it's not used because passing an empty set of ranges to the highlight ranges API call returns the full content. We should check whether we actually have any ranges to highlight before fetching.

**Comment by camdencheek** [comment]
Closing since I can't repro this now and I think I may have just gotten confused.

**Comment by jasonhawkharris** [comment]
I am unable to reproduce this at the moment. The only time I see HighlightedFile requests are in the blob view.
