### ISSUE TITLE
Searcher: batch Zoekt list repo requests

### ISSUE THREAD

**Issue by jtibshirani** [sourcegraph/sourcegraph#59865]
When executing a search, searcher asks Zoekt whether it has the repo indexed, to determine if it should use Zoekt to execute the search. Looking at traces on dot com, it sends a separate request per repo to every Zoekt replica. It would be good to batch these together to reduce overhead when searching across many repos.

Note: this would require us to restructure things a bit, since we send one request to searcher per repo.

![Screenshot 2024-01-22 at 12 49 14 PM](https://github.com/sourcegraph/sourcegraph/assets/7461306/a01f7324-0fad-4349-9bcc-72bc980747ee)

/cc @sourcegraph/search-platform

**Comment by keegancsmith** [comment]
Looking at the timings, it is way to slow. We likely have some very low hanging fruit here for looking for a specific repo.

I'm not sure if I missed this when implementing hybrid search or it regressed, but I was expecting us to cache this data in memory. But either way, it feels like some targetted perf work here around batching at the frontend level so searcher can batch + faster List calls sounds good to me.

Side-note: It is also kinda weird this goes via ListAll? Something might not be adding up here. If we are indeed listing all, then this makes sense why it is slow. We shouldn't be ListAlling

> Note: this would require us to restructure things a bit, since we send one request to searcher per repo.

Agreed.

**Comment by jtibshirani** [comment]
@keegancsmith @stefanhengl should we close this out now that you've optimized `List` calls? Or is there work remaining we should do?

**Comment by keegancsmith** [comment]
We can close it out.
