### ISSUE TITLE
Search results: fix contrast in dark mode

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#59882]
Followup from https://github.com/sourcegraph/sourcegraph/pull/59834

In dark mode, the contrast of the border line against the header color doesn't isn't great, making it difficult to see the boundaries when we have header-only results (like repos or paths)

![Image](https://github.com/sourcegraph/sourcegraph/assets/12631702/518cfc29-d891-4795-a5ca-01b0006ae113)

**Comment by taiyab** [comment]
@camdencheek We can use `border-color-2` here.
