### ISSUE TITLE
[Visual Bug] Header background color for results headers

### ISSUE THREAD

**Issue by taiyab** [sourcegraph/sourcegraph#59903]
Visual bug with the implementation of: https://github.com/sourcegraph/sourcegraph/pull/59834

<img width="1509" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/5337876/4eb249ac-4a21-468b-abee-901833e97af1">

Background color of the results headers seems to be taking priority even with a focus overlay.

**Comment by fkling** [comment]
Probably a "conflict" with `position: sticky` and `z-index`. I ran into this a couple of times and have yet to find the proper solution to this (if it exists).

**Comment by camdencheek** [comment]
Note: I can only reproduce this with the "New Search Navigation UI" enabled, which I don't believe we're shipping in this release.
