### ISSUE TITLE
Search filters: no selected type by default

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#59922]
To get it out quickly, we implemented the filters panel so that `Code` is selected by default, and other types modify the query. I've found this to be very unintuitive when using it, especially since there is no way to actually only select code. 

Ideal behavior:
- No type is selected by default, but we do show counts for the result types that are returned
- The filters shown by default are just whatever is returned from the backend. We do not need to worry about type for these filters because the backend won't return filters that are irrelevant.
- Only a single type can be selected at a time
- Selecting a type does not modify the query, but adds `type:` to the set of filters like any other

**Comment by vovakulikov** [comment]
@camdencheek should we close this one since your PR about was merged last week?

**Comment by camdencheek** [comment]
Oh, yep. Thanks!

Closed by https://github.com/sourcegraph/sourcegraph/pull/60028
