### ISSUE TITLE
disk space getting full alerts on k8s and sourcegraph.com

### ISSUE THREAD

**Issue by uwedeportivo** [sourcegraph/sourcegraph#5994]
Alerts on the disk space getting full for relevant pods (indexed search for example)

**Comment by keegancsmith** [comment]
FYI we do have some alerts, see the daemonset `disk-exporter`. However, it has issues around detecting disks coming and going. Maybe there is something more "standard kubernetes" that we can use now? When disk-exporter was created nothing existed for this use case.

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.10 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
https://github.com/sourcegraph/deploy-sourcegraph/pull/443

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.11 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.12 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.13 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by slimsag** [comment]
Closing in favor of https://github.com/sourcegraph/sourcegraph/issues/9919 which is broader and better.
