### ISSUE TITLE
Request to log tier of the user for all Cody events in metadata

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/sourcegraph#59948]
### Description:

Purpose:
- We want to understand, when users use Cody, what tier they're on. 
- This help with understanding things like:
  - How different tiers of Cody users are using Cody
  - The % of the DAU that are Free vs Pro vs Enterprise
  - Problems that users are running into across diferent tiers. 

### Requirements:

For every event we log when the user is logged in, log metadata:
- tier: free|pro|enterprise

### Related Docs:

- [PRD: Your-Title]()

```[tasklist]
### Tasks
- [ ] https://github.com/sourcegraph/cody/issues/2466
- [ ] https://github.com/sourcegraph/cody/issues/2467
```

**Comment by beyang** [comment]
@kelsey-brown is this still a todo?

**Comment by kelsey-brown** [comment]
Yes it is. If we can't get this done in the near term, I can approximate this on my end with a few different data transformations, but logging it on the event directly would be a lot cleaner.

**Comment by taylorsperry** [comment]
> Kk sounds good, I'll create tickets for JetBrains and VS Code and link here when they're ready

@chenkc805 did you already create these tickets and they got lost in the shuffle?

**Comment by chenkc805** [comment]
@taylorsperry they're in the task list in the comment at the top of this issue

**Comment by kalanchan** [comment]
@chillatom needs follow up
