### ISSUE TITLE
Add "files" tab to search results

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#5996]
Requested by https://app.hubspot.com/contacts/2762526/company/947819054

Adding this just for tracking purposes

**Comment by attfarhan** [comment]
Just to make sure, would the file tab show only filename matches?

**Comment by dadlerj** [comment]
Yeah that was my idea. It's just odd to me that we have a tab for every single `type:` option except `type:path`: https://docs.sourcegraph.com/user/search/queries#filename-search

**Comment by attfarhan** [comment]
Yep agreed

**Comment by dadlerj** [comment]
is `type:path` actually broken? It doesn't seem to work for me: https://sourcegraph.com/search?q=repo:%5Egithub.com/sourcegraph/sourcegraph%24+type:path+auth&patternType=literal

**Comment by attfarhan** [comment]
Yes, on the zoekt code path. See the issue referenced right above your first comment.
