### ISSUE TITLE
Search pagination: Add support for non-file (text) result types

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#5997]
After https://github.com/sourcegraph/sourcegraph/pull/4796 is merged, the pagination API has a known limitation of only supporting non-file (text) result types. This limitation should be easy to lift, there is just one last decision to be made (how to guarantee ordering when indexed and unindexed results are intermingled) -- I have some ideas here just need to think about them a bit more.

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.10 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.11 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by lguychard** [comment]
Pagination has been removed.
