### ISSUE TITLE
Adding telemetry to new search results filters

### ISSUE THREAD

**Issue by taiyab** [sourcegraph/sourcegraph#59971]
We're looking to add telemetry to the new search filters UX for search results.

[Example search](https://sourcegraph.com/search?q=context%3Aglobal+foobar&patternType=standard&sm=1&filters=%5B%5B%22lang%22%2C%22Java%22%2C%22lang%3Ajava%22%5D%5D)

<img width="531" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/5337876/0db10b23-2e91-4cd6-9cdc-eb723d523923">

Specifically, for the LHS (left hand side) filter panel, we're interested in:
- % of all searches that use `count:all` (via panel vs. non-panel)
- % of searches that move from default to `count:all` (via panel vs. non-panel)
- Number of each individual filter applied (via panel vs. non-panel)
- Number of each individual filter applied, then moved those filters to the search query with [this button](https://github.com/sourcegraph/sourcegraph/pull/59764)
- % of "search success" with using the filter panel (compared to not)
- Number of filters applied per search (via panel vs. non-panel)

Overall, we'd love to see what filters per search come from the panel vs. not.

**Note: The `type` and `count` options when selected from the panel update the query bar instantly, the rest don't until I hit the "Move filters to the query" button.**

I'm not sure if we're already tracking this, it would also be great to get:
- % of search timeouts
- % of search timeouts by type

What else do you all want to add? @sourcegraph/code-search 

@kelsey-brown What are we missing here? What's unclear? Let us know if it's too much to get in at this point and we can strip stuff out.

**Comment by kelsey-brown** [comment]
Thanks for tagging me, this new UX looks really sharp. These all seem like very relevant [[metrics](http://metrics.to/)](http://metrics.To), though we may want to hone in on just a couple really high signal ones to keep focused on what is most important (but we should add the telemetry required to measure others as well). To me the most important question when evaluating a new UX like this is effectively - does this design make it easier for the user to get what they’re looking for, or not?

I think at a really high level to understand that we should measure: 

- Search success when using the filter panel (this is one you recommended) - are users who leverage the filter panel more successful?
- User behavior after using the filter panel - do users come back and use it again? Do they search more frequently/more regularly? Or some other variation of that high-level question

Those would be my recommendations for north star metrics, but like I said, everything you proposed would be relevant interesting as well. 

Have you all thought through how you’ll add this telemetry at all? (e.g will you log button clicks or just what metadata on the search event itself, if the latter what metadata you’ll include/how you'll format it, etc?)

**Comment by taiyab** [comment]
@kelsey-brown Thanks for the input Kelsey! Super valuable.

@vovakulikov @camdencheek Any ideas on how we can answer:

>User behavior after using the filter panel - do users come back and use it again? Do they search more frequently/more regularly? Or some other variation of that high-level question

More effectively?

**Comment by camdencheek** [comment]
The only way I know of that we handle this right now is using Amplitude's "session" feature, where we look for events in the same X-minute window.

**Comment by kelsey-brown** [comment]
Yes @taiyab @camdencheek we can do this analysis on our end in one of our BI tools (Amplitude/Looker) - as long as all the telemetry is in place to log user interactions with the filter panel. We don't need to calculate it in the product itself or anything like that.

**Comment by camdencheek** [comment]
I did a quick audit of the telemetry added by @vovakulikov, and I think we've got pretty solid coverage of the basics. Closing this as done since code freeze starts tomorrow and I don't expect we'll do anything more here before then.
