### ISSUE TITLE
Search pagination: potentially update and reason about bucket bounds / divisor

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#5998]
After https://github.com/sourcegraph/sourcegraph/pull/4796 is merged, the bucket divisor and bounds (min/max) are mostly arbitrarily chosen and should instead be based on measurements from benchmarking + measuring NITH query performance, etc. This could improve performance and reduce system load.

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.10 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.11 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by lguychard** [comment]
Pagination has been removed.
