### ISSUE TITLE
Search pagination: decide better behavior for cloning/missing/timedout/partial repos

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#6000]
After https://github.com/sourcegraph/sourcegraph/pull/4796 is merged, when the following condition is true:

```
len(batchCommon.cloning) > 0 || len(batchCommon.missing) > 0 || len(batchCommon.timedout) > 0 || len(batchCommon.partial) > 0
```

The result of the paginated request in this case is questionable for the user and we may want to consider returning an error or asking the user to retry the request later. This needs more thought.

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.10 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.11 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
