### ISSUE TITLE
Search pagination: preemptively fetch and cache results for users that are likely to come back soon

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#6001]
After https://github.com/sourcegraph/sourcegraph/pull/4796 is merged, we have the opportunity to preemptively fetch the next page of results for a user which would make using the paginated API substantially faster.

This can be done using the `UserID` field in the search cursor (see its documentation for some caveats / edge cases we must handle for e.g. security reasons)

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.10 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.11 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by lguychard** [comment]
Pagination has been removed.
