### ISSUE TITLE
Streamlined header unusable with new keyword treatment in search bar (visual bug)

### ISSUE THREAD

**Issue by taiyab** [sourcegraph/sourcegraph#60010]
I get locked out of interacting with anything when the new search navigation UI is activated.

I've explained how to reproduce it on the Loom.

Loom: https://www.loom.com/share/535b3bbb902f46eab1a51f295e83fa47?sid=448f45b6-e78d-445b-8b66-6bf572c9b77e

<img width="1504" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/5337876/4d189b66-37b5-43d3-9e73-ff850840adf9">

**Comment by vovakulikov** [comment]
This should be closed by https://github.com/sourcegraph/sourcegraph/pull/60019
