### ISSUE TITLE
Search pagination: approximateResultCount is certainly wrong

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#6002]
After https://github.com/sourcegraph/sourcegraph/pull/4796 is merged, `approximateResultCount` in paginated requests will only reflect the paginated request itself -- not taking into account prior repos in prior paginated requests with the cursor. Either the documentation needs to reflect this, or it needs to take into account prior requests. This probably doesn't make sense to handle until there is a UI in place to see if this field is required/useful in practice.

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.10 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.11 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by lguychard** [comment]
Pagination has been removed.
