### ISSUE TITLE
Gitlab: "unable to determine merge request ID"

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#6004]
From Sentry: https://sentry.io/organizations/sourcegraph/issues/801327036/?project=1334031&query=is%3Aunresolved+extension_version%3A19.10.9.1226+extension_version%3A19.10.9.1226&statsPeriod=14d

It seems like this is due to [expecting the URL to match `merge_requests/(.*)/diffs` in `getDiffPageInfo()`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@a9d2f8e784589992ba197f2a1443dfceae417e1f/-/blob/browser/src/libs/gitlab/scrape.ts#L104-106) even though `getPageInfo()` (called by `resolveView()`) matches [any page where the URL includes `${owner}/${projectName}/merge_requests`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@a9d2f8e784589992ba197f2a1443dfceae417e1f/-/blob/browser/src/libs/gitlab/scrape.ts#L49-50)

**Comment by vdavid** [comment]
(The code is now [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/client/browser/src/shared/code-hosts/gitlab/scrape.ts?L139:9))
The linked issue is not in Sentry anymore.
We checked Sentry and found no "Unable to determine merge request ID" errors from the last 14 days.
So I guess this is a non-issue now. Closing this.
