### ISSUE TITLE
Updated empty/no match state when filtering for repo/lang, etc. name

### ISSUE THREAD

**Issue by taiyab** [sourcegraph/sourcegraph#60058]
Proposing an updated empty/no match state for when you're filtering the name of a repo/lang/whatever has a text input filter.

**Current**
<img width="287" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/5337876/f1102628-fc24-4252-afcf-ba2549ff699c">

**Proposed**
<img width="323" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/5337876/91a1d2a1-9541-45fc-aa4a-d63e12de80a1">

The link focuses them to the search input bar.

https://www.figma.com/file/EPgl0qVbqGSumvf52brhda/Code-Search?type=design&node-id=60%3A6634&mode=design&t=jJmMuVMkTaj6CVpG-1

Thoughts?

**Comment by camdencheek** [comment]
A detail that snuck past me here: the list of repos in the filters panel is not an exhaustive enumeration of all the repos represented in the search results. It's only the 40 repos with the most matches. We can increase this number, but it will never be truly exhaustive. That kinda makes me feel like the search bar in that location is misleading

**Comment by taiyab** [comment]
@camdencheek Yea, you're right.

Any reason why we picked 40?

**Comment by camdencheek** [comment]
> Any reason why we picked 40?

Just the number we inherited from the old filters panel. We can make it somewhat arbitrarily high, but with the tradeoff that searching them might get slow.

**Comment by camdencheek** [comment]
I'll push up a quick fix to increase the number of repos we return to make this at least a little less problematic

**Comment by camdencheek** [comment]
@taiyab fixed [here](https://github.com/sourcegraph/sourcegraph/pull/60113)
