### ISSUE TITLE
some search suggestions no longer valid with literal search by default

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#6008]
1. Go to sourcegraph.com
2. Click the toggle so it is in literal mode.
3. Search for `error`, see this:

![image](https://user-images.githubusercontent.com/3173176/66786734-4fa18000-ee96-11e9-97c6-da64ba72fe0a.png)

4. Click the first suggestion. It brings you here: https://sourcegraph.com/search?q=%22error%22+repo:%5Egithub%5C.com/nf/goto%24&patternType=literal
5. Notice there are no results because it is in literal mode and the suggestion was for `"error"` not `error`

**Comment by slimsag** [comment]
Putting in 3.9 since I discovered this during testing. I don't know if it is a release blocker or not.

**Comment by tsenart** [comment]
I think we should uphold consistency of UX here and it seems like an easy enough fix so marking as release blocker. @attfarhan: Can you take a look at this please?
