### ISSUE TITLE
Gitlab: unable to determine revision or file path

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#6009]
From Sentry: https://sentry.io/organizations/sourcegraph/issues/791332306/?project=1334031&query=is%3Aunresolved+extension_version%3A19.10.9.1226+extension_version%3A19.10.9.1226&statsPeriod=14d

Seems to happen because `getPageInfo()` [defaults to `GitLabPageKind.File`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@a9d2f8e784589992ba197f2a1443dfceae417e1f/-/blob/browser/src/libs/gitlab/scrape.ts#L51-53) regardless of the URL, but `getFilePageInfo()` expects the URL to [match a specific pattern](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@a9d2f8e784589992ba197f2a1443dfceae417e1f/-/blob/browser/src/libs/gitlab/scrape.ts#L69).

**Comment by felixfbecker** [comment]
This was reported by Paul Slaughter from Gitlab when testing our native integration: https://gitlab.com/gitlab-org/gitlab/merge_requests/16556#note_233519994
I propose we prioritize fixing this

**Comment by lguychard** [comment]
Reproduced on all project pages, example: https://gitlab.com/gitlab-org/database-team/team-tasks
