### ISSUE TITLE
Panic during Cody remote context api

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#60090]
024-02-02 11:31:40,181 [   8529]   WARN - #c.s.c.a.CodyAgentClient - Cody by Sourcegraph: █ SimpleChatPanelProvider.getEnhancedContext: remote search error Error: panic occurred: panic: panic: runtime error: invalid memory address or nil pointer dereference
stacktrace:
goroutine 2647000 [running]:
runtime/debug.Stack()
	GOROOT/src/runtime/debug/stack.go:24 +0x5e
github.com/sourcegraph/conc/panics.NewRecovered(0x0?, {0x3efe8e0, 0x10574050})
	external/com_github_sourcegraph_conc/panics/panics.go:59 +0x7d
github.com/sourcegraph/conc/panics.(*Catcher).tryRecover(0xc001c25090)
	external/com_github_sourcegraph_conc/panics/panics.go:28 +0x65
panic({0x3efe8e0?, 0x10574050?})
	GOROOT/src/runtime/panic.go:914 +0x21f
github.com/sourcegraph/sourcegraph/internal/search/job/jobutil.(*alertJob).Run(0xc0058ffc68, {0xdceb7e8?, 0xc004eabce0?}, {{0xdd047d0, 0xc002e0d0c0}, {0xdd86620, 0xc0036b9f80}, {0xdcf0c20, 0xc0032b7bc0}, 0xc0032aeba0, ...}, ...)
	internal/search/job/jobutil/alert.go:41 +0x1ce
github.com/sourcegraph/sourcegraph/internal/search/job/jobutil.(*LogJob).Run(0xc0058ffc80, {0xdceb7e8?, 0xc004eab680?}, {{0xdd047d0, 0xc002e0d0c0}, {0xdd86620, 0xc0036b9f80}, {0xdcf0c20, 0xc0032b7bc0}, 0xc0032aeba0, ...}, ...)
	internal/search/job/jobutil/log_job.go:47 +0x179
github.com/sourcegraph/sourcegraph/internal/search/client.(*searchClient).Execute(0xc001088700, {0xdceb820?, 0xc0049b6aa0?}, {0xdca8880, 0xc004eab650}, 0xc002f6eea0)
	internal/search/client/client.go:174 +0x1f8
github.com/sourcegraph/sourcegraph/internal/codycontext.(*CodyContextClient).getKeywordContext.func1({0xdceb820?, 0xc0049b6a50?}, {0xc007e03020, 0x5a}, 0x5)
	internal/codycontext/context.go:325 +0x254
github.com/sourcegraph/sourcegraph/internal/codycontext.(*CodyContextClient).getKeywordContext.func3({0xdceb820?, 0xc0049b6a50?})
	internal/codycontext/context.go:344 +0x35
github.com/sourcegraph/sourcegraph/internal/codycontext.(*CodyContextClient).getKeywordContext.(*ResultContextPool[...]).Go.func5()
	external/com_github_sourcegraph_conc/pool/result_context_pool.go:24 +0x3a
github.com/sourcegraph/conc/pool.(*ContextPool).Go.func1()
	external/com_github_sourcegraph_conc/pool/context_pool.go:38 +0x72
github.com/sourcegraph/conc/pool.(*ContextPool).Go.(*ErrorPool).Go.func2()
	external/com_github_sourcegraph_conc/pool/error_pool.go:30 +0x22
github.com/sourcegraph/conc/pool.(*Pool).worker(0xc001c25080, 0xc00b228360?)
	external/com_github_sourcegraph_conc/pool/pool.go:156 +0x5a
github.com/sourcegraph/conc/pool.(*Pool).Go.func1()
	external/com_github_sourcegraph_conc/pool/pool.go:51 +0x1b
github.com/sourcegraph/conc/panics.(*Catcher).Try(0x446edc?, 0xc005d01f80?)
	external/com_github_sourcegraph_conc/panics/panics.go:23 +0x48
github.com/sourcegraph/conc.(*WaitGroup).Go.func1()
	external/com_github_sourcegraph_conc/waitgroup.go:32 +0x56
created by github.com/sourcegraph/conc.(*WaitGroup).Go in goroutine 2646998
	external/com_github_sourcegraph_conc/waitgroup.go:30 +0x73

**Comment by chwarwick** [comment]
Reported during internal testing against s2 
```
I cannot see and actual impact. It is not deterministic (I just opened a project and wrote a chat message - it appeared, no I cannot reproduce it).
```

**Comment by chwarwick** [comment]
@jtibshirani  If I'm reading this stack trace correctly it looks like the panic is from the search job.  Nothing stood out to me when I looked in there and doesn't look like there have been any recent changes.

**Comment by jtibshirani** [comment]
@chwarwick I think I have a fix for this! PR incoming.
