### ISSUE TITLE
C# code intelligence hover not functioning within Sourcegraph

### ISSUE THREAD

**Issue by GotenXiao** [sourcegraph/sourcegraph#601]
- **Sourcegraph version:** 2.12.3
- **Platform information:** Windows 7 (64bit), Firefox 63.0 (64bit), Docker 18.03.1-ce on-premises self-host as a member of a Rancher 1.6.18 cluster

Global settings:
```json
{
  "extensions": {
    "langserver/javascript": true,
    "langserver/cs": true,
    "langserver/css": true,
    "langserver/html": true,
    "langserver/dockerfile": true,
    "langserver/typescript": true
  }
}
```

`langservers` section from site configuration:
```json
[
  {
    "address": "tcp://typescript:2088",
    "language": "javascript"
  },
  {
    "address": "tcp://csharp:8080",
    "language": "cs"
  },
  {
    "address": "tcp://css:8080",
    "language": "css"
  },
  {
    "address": "tcp://docker:8080",
    "language": "dockerfile"
  },
  {
    "address": "tcp://html:8080",
    "language": "html"
  },
  {
    "address": "tcp://typescript:2088",
    "language": "typescript"
  }
]
```

Hostnames above are linked to the services within the Rancher stack for Sourcegraph.

#### Steps to reproduce:

1. Hover over a symbol within a C# code file

#### Expected behavior:
- Hover bubble displays code intelligence information

#### Actual behavior:
- Bubble disappears, the following error is logged into the user agent's debugging console:
```
An error occurred when sending LSP requests to the language server, disabling this instance of the language extension (reload the page to clear this state).  Error: Request textDocument/definition failed with message: Cannot read property 'replace' of null
```

JavaScript, CSS, Dockerfile, and HTML language servers and hover interfaces are working correctly.

I did notice while investigating this issue that the upstream **omnisharp-node-client** project has been idle for nearly a year now, aside from automated PRs that have gone unmerged for months (as mentioned in #5).

Also, I've installed the browser extension and configured it to point to the same Sourcegraph instance, and get different behaviour on the same file, for the same symbol; the bubble appears, but in an error state:
```
Error fetching hover from language server:
Invalid hover response: {"contents":"System.Data.DataRow"}
```

**Comment by sqs** [comment]
Thanks for filing. We are struggling to maintain the experimental C# support for the reasons you cite (the upstream library is unmaintained). I posted an update at https://github.com/sourcegraph/sourcegraph/issues/5#issuecomment-432994860 about our roadmap for making it better. We will revisit this in December 2018.
