### ISSUE TITLE
changesetCountsOverTime panics

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#6011]
Run this query on latest master: [GraphQL query](http://localhost:3080/api/console#%7B%22query%22%3A%22query%20CampaignByID(%24campaign%3A%20ID!)%20%7B%5Cn%20%20%20%20node(id%3A%20%24campaign)%20%7B%5Cn%20%20%20%20%20%20%20%20__typename%5Cn%20%20%20%20%20%20%20%20...%20on%20Campaign%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20...CampaignFields%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%7D%5Cn%5Cnfragment%20CampaignFields%20on%20Campaign%20%7B%5Cn%20%20%20%20id%5Cn%20%20%20%20namespace%20%7B%5Cn%20%20%20%20%20%20%20%20id%5Cn%20%20%20%20%20%20%20%20namespaceName%5Cn%20%20%20%20%7D%5Cn%20%20%20%20author%20%7B%5Cn%20%20%20%20%20%20%20%20username%5Cn%20%20%20%20%20%20%20%20avatarURL%5Cn%20%20%20%20%7D%5Cn%20%20%20%20name%5Cn%20%20%20%20description%5Cn%20%20%20%20createdAt%5Cn%20%20%20%20updatedAt%5Cn%20%20%20%20url%5Cn%20%20%20%20changesets%20%7B%5Cn%20%20%20%20%20%20%20%20nodes%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20id%5Cn%20%20%20%20%20%20%20%20%20%20%20%20title%5Cn%20%20%20%20%20%20%20%20%20%20%20%20body%5Cn%20%20%20%20%20%20%20%20%20%20%20%20state%5Cn%20%20%20%20%20%20%20%20%20%20%20%20reviewState%5Cn%20%20%20%20%20%20%20%20%20%20%20%20repository%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20name%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20url%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20externalURL%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20url%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20createdAt%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%20%20%23%20TODO%20move%20to%20separate%20query%20and%20configure%20from%2Fto%5Cn%20%20%20%20changesetCountsOverTime%20%7B%5Cn%20%20%20%20%20%20%20%20date%5Cn%20%20%20%20%20%20%20%20merged%5Cn%20%20%20%20%20%20%20%20closed%5Cn%20%20%20%20%20%20%20%20openApproved%5Cn%20%20%20%20%20%20%20%20openChangesRequested%5Cn%20%20%20%20%20%20%20%20openPending%5Cn%20%20%20%20%7D%5Cn%7D%5Cn%5Cn%20%20%20%20%20%20%20%20%22%2C%22operationName%22%3A%22CampaignByID%22%2C%22variables%22%3A%22%7B%5C%22campaign%5C%22%3A%20%5C%22Q2FtcGFpZ246MQ%3D%3D%5C%22%7D%22%7D)
Replace `campaignID` by an existing ID, or use my [DB dump](https://sourcegraph.slack.com/archives/GPF0CGQSK/p1571093169000100).

```graphql
query CampaignByID($campaign: ID!) {
    node(id: $campaign) {
        __typename
        ... on Campaign {
            ...CampaignFields
        }
    }
}

fragment CampaignFields on Campaign {
    id
    namespace {
        id
        namespaceName
    }
    author {
        username
        avatarURL
    }
    name
    description
    createdAt
    updatedAt
    url
    changesets {
        nodes {
            id
            title
            body
            state
            reviewState
            repository {
                name
                url
            }
            externalURL {
                url
            }
            createdAt
        }
    }
    # TODO move to separate query and configure from/to
    changesetCountsOverTime {
        date
        merged
        closed
        openApproved
        openChangesRequested
        openPending
    }
}
```

**Comment by mrnugget** [comment]
Replicating the relevant, non-sensitive parts of the DB dump (thanks for that! :clap:) here:

```sql
--
-- Data for Name: campaigns; Type: TABLE DATA; Schema: public; Owner: felix
--

COPY public.campaigns (id, name, description, author_id, namespace_user_id, namespace_org_id, created_at, updated_at, changeset_ids) FROM stdin;
2	bla	asdjasd	1	1	\N	2019-09-19 13:20:42.746394+02	2019-09-19 13:20:42.746394+02	{}
1	test camp	asdasd	1	1	\N	2019-09-12 22:18:10.495944+02	2019-10-08 18:39:48.591054+02	{}
5	asdsadasd	asdsad	1	1	\N	2019-10-09 19:20:33.16126+02	2019-10-09 19:20:33.16126+02	{}
7	asdasd	asdasdasdasdasd	1	1	\N	2019-10-09 19:21:54.099583+02	2019-10-09 19:21:57.988242+02	{}
\.


--
-- Data for Name: changeset_events; Type: TABLE DATA; Schema: public; Owner: felix
--

COPY public.changeset_events (id, changeset_id, kind, key, created_at, metadata, updated_at) FROM stdin;
\.


--
-- Data for Name: changesets; Type: TABLE DATA; Schema: public; Owner: felix
--

COPY public.changesets (id, campaign_ids, repo_id, created_at, updated_at, metadata, external_id, external_service_type) FROM stdin;
\.

```

In other words: 4 `campaigns`, no `changesets`, no `changeset_events`.
