### ISSUE TITLE
Port Jaeger from deploy-sourcegraph-docker -> sourcegraph/server deployments

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#6012]
Similar to https://github.com/sourcegraph/sourcegraph/issues/3410 -- but for single-container deployments, we would like to also have Jaeger.

Jaeger should ideally be on in all "major" / serious deployments, but it is much more resource intensive than e.g. Grafana and Prometheus. It may make sense for it to be optional and off in more trivial / demo deployments of `sourcegraph/server` where someone is just pulling the container down to try sourcegraph on a dev laptop. Maybe it could be turned on based on the # available CPUs or memory?

**Comment by beyang** [comment]
Replaced by https://github.com/sourcegraph/sourcegraph/issues/9300
