### ISSUE TITLE
literal search feedback: it is very hard to remove my double-quoting habbit

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#6016]
I have the literal search toggle enabled so my searches are literal, but it's very hard to remove my habit of double quoting things to get literal search. I am sure I will get used to it eventually, but I worry some other users will also feel this pain.

What would help me _a lot_ in this situation is if I get no results showing a suggestion that my search is interpreted literally and I might try changing the search toggle to regex: https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+%22docker+rm+-f%22&patternType=literal

**Comment by slimsag** [comment]
Putting in 3.9 since I discovered this during testing. I don't know if it is a release blocker or not.

**Comment by tsenart** [comment]
I don't consider this to be a release blocker given the pop up we show users about the new feature.
