### ISSUE TITLE
Update empty repository filter display

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#60172]
The empty repository filter is an improvement, but the copy could leave users feeling the repository was not found in the Sourcegraph instance. We need to make it much more clear that it was not found in the results only, and provide users a simple route to getting the repository they need:

## Before

![image](https://github.com/sourcegraph/sourcegraph/assets/539268/37f78389-8ad8-42b3-b3db-1da4e6d0aacb)

## Improved 

![image](https://github.com/sourcegraph/sourcegraph/assets/539268/971e66e2-c2af-41af-8a9a-2744fd35c9eb)

Figma: https://www.figma.com/file/EPgl0qVbqGSumvf52brhda/Code-Search?type=design&node-id=1493-16090&mode=design&t=kZi8GVeAPRfiyFv7-4

**Comment by taiyab** [comment]
Tweaked this a bit more (same Figma link): 

<img width="318" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/5337876/9404097a-bc7b-4872-959b-b730c4f9ef44">
