### ISSUE TITLE
Search filters: refine input empty state

### ISSUE THREAD

**Issue by taiyab** [sourcegraph/sourcegraph#60195]
cc @rrhyne 

Updates to https://github.com/sourcegraph/sourcegraph/pull/60179

<img width="338" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/5337876/4307ad51-b4e6-4820-9d4e-c2c1650ecebc">

https://www.figma.com/file/EPgl0qVbqGSumvf52brhda/Code-Search?type=design&node-id=1493%3A16077&mode=design&t=AuvsLW65e35cRgRT-1

It should:
- only give the filter recommendation for repository and author filters
- only give the filter recommendation when a count limit is hit

I also feel this confusion from users seeing the repo filter as a search is somewhat exacerbated by:
- currently not having the "filter by" title at the top (which is coming)
- having repository as the first filter option in the list

Fallback alternative for non-repo/author filters, or when the reqs. for recommendation aren't hit:
<img width="317" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/5337876/48f63859-bf7a-4636-bfa1-20afa68394f5">

@camdencheek Would be great if you could review this to see if it makes sense?

**Comment by camdencheek** [comment]
> only give the filter recommendation when a count limit is hit

This condition resolves all my concerns with the design. LGTM!

**Comment by taiyab** [comment]
Solved by https://github.com/sourcegraph/sourcegraph/pull/60239
