### ISSUE TITLE
gRPC Retry Test Plan

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#60191]
# QA Test Plan

## Summary

PRs that implement this feature:

- https://github.com/sourcegraph/sourcegraph/pull/59095
- https://github.com/sourcegraph/sourcegraph/pull/59140
- https://github.com/sourcegraph/sourcegraph/pull/59145
- https://github.com/sourcegraph/sourcegraph/pull/59146
- https://github.com/sourcegraph/sourcegraph/pull/59191
- https://github.com/sourcegraph/sourcegraph/pull/59107
- https://github.com/sourcegraph/sourcegraph/pull/59110
- https://github.com/sourcegraph/sourcegraph/pull/59111
- https://github.com/sourcegraph/sourcegraph/pull/59130
- https://github.com/sourcegraph/sourcegraph/pull/59133
- https://github.com/sourcegraph/sourcegraph/pull/59136
- https://github.com/sourcegraph/sourcegraph/pull/59218

PRs that implement the Prometheus dashboards:
- https://github.com/sourcegraph/sourcegraph/pull/59607
- https://github.com/sourcegraph/sourcegraph/pull/59680
- https://github.com/sourcegraph/sourcegraph/pull/59691

## Test Plan

This feature touches every aspect of gRPC and has undergone extensive unit testing, and has been running on sourcegraph.com with no issues for over a month now. 

This test plan will consist of: 

1) A basic local test for one method
2) Examining the Prometheus retry dashboards for every service to see if there are any oddities

### basic local test

I ran sourcegraph @ 5.3 with `sg start --except gitserver-0 && sg start monitoring` (notice that I have one of the gitserver instances disabled). 

I then ran the following diff search with tracing enabled: https://sourcegraph.test:3443/search?q=context:global+test+type:diff&patternType=keyword&sm=0&trace=1

```
context:global test type:diff
```

That produced the following trace:

![Screenshot 2024-02-05 at 16-29-57 Jaeger UI](https://github.com/sourcegraph/sourcegraph/assets/9022011/cc411128-c928-4aa9-a953-3dc3697fed49)

[example_trace.json](https://github.com/sourcegraph/sourcegraph/files/14173279/e6f2f6010cff142d87dc795044123f41.json)

The Grafana dashboard for gitserver also shows the expected spike in retry count:

<img width="1440" alt="Screenshot 2024-02-05 at 4 36 12 PM" src="https://github.com/sourcegraph/sourcegraph/assets/9022011/b934e36d-87b3-4c22-9f04-67c081beb4bc">

Running the same search without the disabled gitserver (`sg start && sg start monitoring`) shows the expected search results:

<img width="1505" alt="Screenshot 2024-02-05 at 4 42 14 PM" src="https://github.com/sourcegraph/sourcegraph/assets/9022011/b59673ce-32fe-4bce-a70a-9fcf092456c1">

The trace also shows that the request wasn't retried:

 ![Screenshot 2024-02-05 at 16-39-42 Jaeger UI](https://github.com/sourcegraph/sourcegraph/assets/9022011/a70cec61-4169-4550-9673-3ea909ba331a)

[good_trace.json](https://github.com/sourcegraph/sourcegraph/files/14173328/db241e3c8608ff3ed8fa7743710ed03d.json)

#### frontend

![screencapture-sourcegraph-debug-grafana-d-frontend-frontend-2024-02-05-16_51_49](https://github.com/sourcegraph/sourcegraph/assets/9022011/0fa0456d-5412-4d96-8ec5-ab1be98b367b)

We don't have an inordinate amount of retries.

The spike in retries corresponds to an `Unavailable` response from the server, so the feature seems to be working correctly:'

<img width="1499" alt="Screenshot 2024-02-05 at 9 38 42 PM" src="https://github.com/sourcegraph/sourcegraph/assets/9022011/c6a24bc2-8dc5-4567-8bc9-eee70630a52a">

#### gitserver 

https://sourcegraph.com/-/debug/grafana/d/gitserver/git-server?orgId=1&from=1706653431512&to=1707258231512&viewPanel=100802

![screencapture-sourcegraph-debug-grafana-d-gitserver-git-server-2024-02-05-16_53_06](https://github.com/sourcegraph/sourcegraph/assets/9022011/e0204306-ef05-457c-b220-f4f488ec4f5d)

The spikes here also correspond to rollouts, so the feature is working correctly.

#### searcher

![screencapture-sourcegraph-debug-grafana-d-searcher-searcher-2024-02-05-16_55_06](https://github.com/sourcegraph/sourcegraph/assets/9022011/6e4d16e0-8a4b-44f9-9197-5adb5ad6b5f3)

The spikes here also correspond to rollouts, so the feature is working correctly.

#### symbols 

![screencapture-sourcegraph-debug-grafana-d-symbols-symbols-2024-02-05-16_56_27](https://github.com/sourcegraph/sourcegraph/assets/9022011/f0c54aee-06fd-4555-8c56-1fb65f0034f4)

The spike here also corresponds to a rollouts, so the feature is working correctly.

#### repo-updater

![screencapture-sourcegraph-debug-grafana-d-repo-updater-repo-updater-2024-02-05-16_53_54](https://github.com/sourcegraph/sourcegraph/assets/9022011/1119317c-8cb7-463b-a226-bdc24ca424ff)

There have been no retries attempted in the past 7 days. 

## QA Checklist

1. **Have you made any infra related changes to environment variables, new services, or deployment methods that could affect customers?**
   - [ ] Yes - I've informed [#team-cloud](https://sourcegraph.slack.com/archives/C03LCPCT3SP) and [#team-delivery](https://sourcegraph.slack.com/archives/C02VDNKBWDU) of the changes.
   - [ ] Yes - Changelog or documentation has been updated, this includes changes to defaults and site config flags.
   - [x] No

    If your change is non-trivial, please review the [Cloud Launch](https://handbook.sourcegraph.com/departments/cloud/launch-process/#questionnaire) process. 

    If you've made changes to documentation, please link them in the comments below.  
    
    Comments:

2. **Which environments have the changes been tested on?**
   - [x] sourcegraph.com
  
3. **Experimental features have been marked and behind a feature flag?**
   - [x] N/A

    If no, please specify why: This feature isn't experimental. It has also been running for over a month on sourcegraph.com and S2.

4. **Has telemetry been added as part of the product requirements?**
   - [x] N/A

5. **Completed entry to release post.**
   - [x] N/A

6. **Is a feature flagged in a way when turns the feature off, it behaves as-if the feature does not exist?**
   - [x] Yes

Yes, you can set `SRC_GRPC_RETRY_MAX_ATTEMPTS=0` on every service: 
https://github.com/sourcegraph/sourcegraph/blob/afadc0ab3adabe5a1a734c3bd402e8764db89ad8/internal/grpc/defaults/retry.go#L19

7. **A [CHANGELOG entry](https://github.com/sourcegraph/sourcegraph/blob/main/CHANGELOG.md) has been added for the feature/change?**
   - [x] Yes: https://github.com/sourcegraph/sourcegraph/blob/8868eb5aa83f6f5e892bbe1d5f558959a4c60d64/CHANGELOG.md?plain=1#L91

8. **Please provide any additional testing you've done that has not been covered above:**

N/A

---- 

Tech Lead/DRI sign off: @kalanchan

**Comment by eseliger** [comment]
Great work, very clean journal!

**Comment by eseliger** [comment]
oops wrong button

**Comment by eseliger** [comment]
@kalanchan if this LGTM, can you please close the issue - thanks :)

**Comment by eseliger** [comment]
Release done, closing.
