### ISSUE TITLE
Search pagination: error when search contains no repositories

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#6020]
Example: https://k8s.sgdev.org/api/console#%7B%22query%22%3A%22query%20PaginatedSearch(%24query%3A%20String!%2C%20%24perPage%3A%20Int!%2C%20%24after%3A%20ID)%20%7B%5Cn%20%20search(query%3A%20%24query%2C%20first%3A%20%24perPage%2C%20after%3A%20%24after)%20%7B%5Cn%20%20%20%20results%20%7B%5Cn%20%20%20%20%20%20results%20%7B%5Cn%20%20%20%20%20%20%20%20...%20on%20FileMatch%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20repository%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20name%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20file%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20path%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20pageInfo%20%7B%5Cn%20%20%20%20%20%20%20%20endCursor%5Cn%20%20%20%20%20%20%20%20hasNextPage%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22variables%22%3A%22%7B%5Cn%20%20%5C%22query%5C%22%3A%20%5C%22repo%3A%5Egithub.com%2Fgorilla%20errorf%20type%3Afile%5C%22%2C%5Cn%20%20%5C%22perPage%5C%22%3A%205%2C%5Cn%20%20%5C%22after%5C%22%3A%20null%5Cn%7D%22%7D

**Comment by tsenart** [comment]
Moving to Backlog since it doesn't look like this got done in time for 3.9. Please update accordingly otherwise.

**Comment by slimsag** [comment]
This was a bug identified as part of 3.9 testing, I intend to land a fix for this in 3.9.
