### ISSUE TITLE
Search pagination: repeated results in some cases

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#6022]
With this query, the first queries last result is incorrectly also the 2nd queries first result, the same is true of the 2nd/3rd request:

1. tinyurl.com/yyn8cxyo
2. tinyurl.com/y4khxt3s
3. tinyurl.com/y264fbwv

**Comment by tsenart** [comment]
Moving to Backlog since it doesn't look like this got done in time for 3.9. Please update accordingly otherwise.

**Comment by slimsag** [comment]
This was a bug identified as part of 3.9 testing, I intend to land a fix for this in 3.9.

**Comment by tsenart** [comment]
Is this not release blocking because the whole feature is experimental?

**Comment by slimsag** [comment]
Correct, no issues about pagination are release-blocking as the whole feature is experimental.
