### ISSUE TITLE
gRPC - remove REST code fallback QA Test Plan

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#60236]
# QA Test Plan

## Summary

In https://github.com/sourcegraph/sourcegraph/pull/59093, we removed all of the REST code for all of our internal service communication. Much of this effort involved removing a lot of glue code, fixing our test suites to use gRPC (in the cases where they were hard-coded to use REST), and removing duplicative interfaces

## Test Plan

The GRPC code paths have been on by default since Sourcegraph 5.2. 

This change removed mostly dead code (REST code paths). As such, this change has already been implicitly tested on sourcegraph.com / customer instances for quite a long time. In addition, sourcegraph.com has been running the post https://github.com/sourcegraph/sourcegraph/pull/59093 version for well over a month now with no issues. 

As such, there is no need for a formal test plan - it's already clearly been working for a long time. 

## QA Checklist

1. **Have you made any infra related changes to environment variables, new services, or deployment methods that could affect customers?**
   - [x] Yes - I've informed [#team-cloud](https://sourcegraph.slack.com/archives/C03LCPCT3SP) and [#team-delivery](https://sourcegraph.slack.com/archives/C02VDNKBWDU) of the changes. 
      - See https://sourcegraph.slack.com/archives/C0EPTDE9L/p1706039695856019

2. **Which environments have the changes been tested on?**
   - [x] sourcegraph.com

3. **Experimental features have been marked and behind a feature flag?**
   - [x] No

    If no, please specify why: This changes promotes gRPC to the only method of communication, as opposed to 5.2 where it could be disabled.

4. **Has telemetry been added as part of the product requirements?**
   - [x] N/A

5. **Completed entry to release post.**
   - [x] N/A

6. **Is a feature flagged in a way when turns the feature off, it behaves as-if the feature does not exist?**
   - [x] No

    If no, please specify why: This changes promotes gRPC to the only method of communication, as opposed to 5.2 where it could be disabled.

7. **A [CHANGELOG entry](https://github.com/sourcegraph/sourcegraph/blob/main/CHANGELOG.md) has been added for the feature/change?**
   - [x] Yes: https://github.com/sourcegraph/sourcegraph/pull/60237

8. **Please provide any additional testing you've done that has not been covered above:**

N/A

---- 

Tech Lead/DRI sign off: @kalanchan

**Comment by eseliger** [comment]
LGTM.

**Comment by eseliger** [comment]
@kalanchan if this LGTM, can you please close the issue - thanks :)

**Comment by eseliger** [comment]
Release done, closing.
