### ISSUE TITLE
☂️ Search: solidify content-based language filtering

### ISSUE THREAD

**Issue by jtibshirani** [sourcegraph/sourcegraph#60341]
Currently, we translate `lang` filters to filters on file extensions. Because multiple languages may share the same extension, this can lead to errors. For example, `lang:matlab` also matches Objective C files, since they also end in `.m`.

We have a feature `search-content-based-lang-detection` that instead matches against the actual language of the file, as determined by go-enry. This issue tracks work to solidify the feature so we're comfortable recommending it to customers.

- [x] https://github.com/sourcegraph/sourcegraph/pull/60349
    - Simplify the Zoekt queries we create
    - Make sure exclude filters like `-lang` work correctly
    - Combine multiple filters through 'and' instead of 'or'
- [x] https://github.com/sourcegraph/zoekt/pull/740
- [x] https://github.com/sourcegraph/sourcegraph/pull/60496
- [x] https://github.com/sourcegraph/sourcegraph/pull/60625
- [x] https://github.com/sourcegraph/sourcegraph/pull/60626

/cc @sourcegraph/search-platform

**Comment by jtibshirani** [comment]
I'd appreciate your thoughts on the new behavior for `lang:cpp`.
* Before: we always include files ending in `.cpp`, `.hpp`, and `.h`. This includes C files that end in `.h`, which can be confusing (since you see both "C++" and "C" listed in the filters sidebar).
* Now we always return `.cpp` and `.hpp` because these are unambiguous. We also return `.h` files if they resemble C++, like import something from the standard library or use a namespace.

Downsides of new behavior:
* It's not super common, but you can have `.h` files in a C++ repo that just happen to resemble C. See [this example](https://sourcegraph.com/search?q=context%3Aglobal+repo%3A%5Egithub%5C.com%2Fgrf-labs%2Fgrf%24+file%3A%5C.h+lang%3Ac&patternType=keyword&sm=0&filters=%5B%5B%22lang%22%2C%22C%22%2C%22lang%3Ac%22%5D%5D&feat=search-content-based-lang-detection) from the open source repo `grf-labs/grf`.
* go-enry has some classification errors, where something is clearly C++ but it labels it as C (see [this example](https://sourcegraph.test:3443/github.com/grf-labs/grf@25f7756acaea2b926a6dd449060c2d3d53f71fae/-/blob/core/third_party/Eigen/src/plugins/MatrixCwiseUnaryOps.h) from same repo).

For me the trade-off is acceptable. It feels like a natural mental model for each file to have a single language. And C++ users can always put together a special context like `lang:C++ OR lang:C` to mirror the old behavior. If it's a big problem, we could also introduce custom overrides, like we do for syntax highlighting. (The linguist library allows custom attributes per repo through `.gitattributes`, but go-enry doesn't support anything like this yet.)

**Comment by varungandhi-src** [comment]
> It's not super common, but you can have .h files in a C++ repo that just happen to resemble C. See [this example](https://sourcegraph.com/search?q=context%3Aglobal+repo%3A%5Egithub%5C.com%2Fgrf-labs%2Fgrf%24+file%3A%5C.h+lang%3Ac&patternType=keyword&sm=0&filters=%5B%5B%22lang%22%2C%22C%22%2C%22lang%3Ac%22%5D%5D&feat=search-content-based-lang-detection) from the open source repo grf-labs/grf.

There were 14 files in the results that I'm seeing right now. I've annotated the files for which we could improve the results.

![](https://github.com/sourcegraph/sourcegraph/assets/93103176/0b8757dc-3f32-4e34-85c7-fa238c8e2d19)

> go-enry has some classification errors, where something is clearly C++ but it labels it as C (see [this example](https://sourcegraph.com/github.com/grf-labs/grf@3f3eb892844d335dc2faec062c7eb67195c104df/-/blob/core/third_party/Eigen/src/Core/util/Macros.h) from same repo).

Agreed, if go-enry checked for 'extern "C"` that would help fix the results for those files.

> For me the trade-off is acceptable

I agree, it's a big improvement compared to what we have, and we can iterate on further improvements down the line.

**Comment by jtibshirani** [comment]
We made a nice round of improvements and should feel comfortable recommending the feature to customers who have issues with our current lang filters. However, more work is required to really "complete" the feature and enable it by default. I filed https://github.com/sourcegraph/sourcegraph/issues/60676 to track that work.
