### ISSUE TITLE
Support for Azure DevOps repositories missing for "Exclude Repository" button

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#60346]
- **Sourcegraph version:** 5.2
- **Reported by:** https://github.com/sourcegraph/accounts/issues/4142

#### Steps to reproduce:

1. Connect to an Azure DevOps code host
2. Sync at least one repository
3. Go to the repository settings page for a repository from Azure DevOps
4. In the `Options` tab, click on `Exclude repository`

#### Expected behavior:

The repository is excluded

#### Actual behavior:

![image](https://github.com/sourcegraph/sourcegraph/assets/23640224/b4caa0fb-1d1d-4633-9d43-29ecd3731b95)

See https://sourcegraph.com/github.com/sourcegraph/sourcegraph@2a8670bc830640f15022d608a1e0cb08a0b7a791/-/blob/cmd/frontend/backend/external_services.go?L335:20-335:38 => https://sourcegraph.com/github.com/sourcegraph/sourcegraph@2a8670bc830640f15022d608a1e0cb08a0b7a791/-/blob/cmd/frontend/backend/external_services.go?L382:6-382:24 (missing azure devops)

If you would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are no [SLAs](https://sourcegraph.com/support/) on issues like there are for support requests).

**Comment by marcleblanc2** [comment]
Can reproduce from a repo's settings page 
https://marc-dev.sourcegraphcloud.com/dev.azure.com/marc-leblanc/tfvc-project-1/git-tfs/-/settings

Workaround is to configure the repo exclusion the hard way in the Code Host Config.

Seems like more code host types need to be added to the switch.
