### ISSUE TITLE
External service _.schema.json files failing with "...is outside repository" error

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#6034]
- **Sourcegraph version:** Sourcegraph.com

For some reason https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/doc/admin/external_service/bitbucket_cloud.schema.json works, while the rest don't:

- https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/doc/admin/external_service/bitbucket_server.schema.json
- https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/doc/admin/external_service/github.schema.json

etc...

**Comment by unknwon** [comment]
My guess: I think it is related to the way the symlink was made. I'll try if I can make a quick fix within 15 mins...

**Comment by unknwon** [comment]
I think it needs more time with debugging, the root issue I realize so far is at somewhere, we or our dependency resolved the symlink to its content, i.e. `doc/admin/external_service/github.schema.json` -> `../../../schema/github.schema.json`, which will not work for Git commands at the working tree root.

We should have composed a Git command like this (without resolving the symlink):

```
git ls-tree --long --full-name -z b19e0c65ec32d8f4a5a3649cd7623072bac63d18 -- doc/admin/external_service/github.schema.json
```

**Comment by dadlerj** [comment]
This isn't a high priority issue, by the way, just something that I ran into and wanted to file. Thanks for checking.
