### ISSUE TITLE
Bitbucket Cloud external service doesn't provide "exclude" config option

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#6035]
A user at https://app.hubspot.com/contacts/2762526/company/2478384295 just emailed and asked if we provided any way to exclude certain repos using a Bitbucket Cloud external service, like we do for [Bitbucket Server](https://docs.sourcegraph.com/admin/external_service/bitbucket_server#exclude), [GitHub](https://docs.sourcegraph.com/admin/external_service/github#exclude), etc... 

Looks like this never got added:
https://docs.sourcegraph.com/admin/external_service/bitbucket_cloud#admin-external-service-bitbucket-cloud-schema-json

**Comment by unknwon** [comment]
Good to know someone is using it 😄 And leak of some config options are being tracked in this issue: https://github.com/sourcegraph/sourcegraph/issues/5151

**Comment by dadlerj** [comment]
Feel free to close this one as a duplicate — but if so, please add a note to the tracking issue that it was requested by the user above.
