### ISSUE TITLE
Testing chat/commands/autocomplete against testing environment with selected client versions

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#60419]

**Comment by cbart** [comment]
@arafatkatze thanks for performing the tests!

https://sourcegraph.slack.com/archives/C05JDP433DL/p1707901170193009?thread_ts=1707771615.512579&cid=C05JDP433DL

Did you manage to exercise whole codebase context and did it work as expected? aka. the squirrel test?

See: https://github.com/sourcegraph/jetbrains/pull/541 for an example squirrel test.

**Comment by arafatkatze** [comment]
My version of squirrel test is this 

- _what is message provider class_


<img width="542" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/11155207/9cb4c7b2-a3d1-428d-b6d1-6350dbad2ca6">

And it did take the right files and find the right answers.

I also did a version of the squirrel test on their own public repos too(Basically a question about their own repo that refers to something specific in the repo) and the searched context files would give me that result.

**Comment by cbart** [comment]
Great!
