### ISSUE TITLE
Testing environment with Bedrock for evaluation

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#60418]
https://sourcegraph.slack.com/archives/C05JDP433DL/p1707516859083799?thread_ts=1707503490.330399&cid=C05JDP433DL

**Comment by loujar** [comment]
The reference sourcegraph instance is deployed and running, but still working out the bedrock VPN tunnel between AWS & GCP VPCs.

**Comment by cbart** [comment]
Thank you Louis! Once we're ready, please post a reference endpoint and let's make sure all teammates have accounts there:

@arafatkatze @taras-yemets @chwarwick @slimsag @cbart @aramaraju

**Comment by loujar** [comment]
The [reference environment](http://34.160.160.119/) is now configured to use AWS Bedrock as the completions provider via a VPN connection from the the GCP VPC hosting the Sourcegraph instance to an AWS VPC endpoint.
