### ISSUE TITLE
Selecting client versions for evaluation (VS Code / JetBrains)

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#60417]
Thread: https://sourcegraph.slack.com/archives/C01SD4A49E1/p1707503504977569

**Comment by taylorsperry** [comment]
Just to confirm my understanding, the question here is "Which version of the VSC and JetBrains clients can we recommend to customers starting Feb 14?" 

@kalanchan we will have final releases cut for launch, and I'm assuming those will be the versions we'll recommend, correct?

**Comment by aramaraju** [comment]
Adding @loujar here as well so we can replicate whatever version we land on :)

**Comment by cbart** [comment]
cc @arafatkatze:

- These will be the extension versions we're going to be testing against.

**Comment by cbart** [comment]
I'll resolve this as we have clarity https://sourcegraph.slack.com/archives/C05JDP433DL/p1707901170193009?thread_ts=1707771615.512579&cid=C05JDP433DL
