### ISSUE TITLE
Svelte prototype: add blame view

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#60425]
This should be relatively easy because most of the logic is in a CodeMirror extension which accepts a function to generate the UI.

**Comment by taiyab** [comment]
https://github.com/sourcegraph/sourcegraph/issues/61653

**Comment by camdencheek** [comment]
Leaving this open for two followups:
- [ ] Popover implementation (like in React app). Should probably consider if we want to implement it the same way.
- [ ] Playwright tests

**Comment by fkling** [comment]
> Popover implementation (like in React app). Should probably consider if we want to implement it the same way.

Personally I'm not a fan of the popover. It feels to heavy for something that should be small piece of information. I don't really know what added value it brings:

- If we want to make the full commit message visible we can add a `title` attribute or a simple popover.
- Reblaming at/before the commit can be done by adding button directly to the blame information.
