### ISSUE TITLE
5.3 Security approval

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#60449]
Security must close this issue before releases. It is the responsibility of the Security Engineer on rotation the week the release is cut. More steps will be added in the future.

- [ ] All feasible CVEs are closed.
- [ ] Any open CVEs are documented in the handbook.

Part of https://github.com/sourcegraph/sourcegraph/issues/60032

cc @sourcegraph/security

**Comment by keegancsmith** [comment]
I believe we are already in a good place there based on a scan done a few days ago and some pre-emptive work we did on removing CVEs from our go codebase.  I know there is a draft PR here for the docs page on accepted CVEs https://github.com/sourcegraph/handbook/pull/8579

**Comment by evict** [comment]
No issues found in our product. The most highest rates issues are in docker-in-docker, but they are not fixed upstream yet. Published justifications here: https://handbook.sourcegraph.com/departments/security/tooling/trivy/5-3-0/.
