### ISSUE TITLE
Provide a google doc describing for PANW team how to install the correct extension versions

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#60462]
Example: https://docs.google.com/document/d/1YD0MMUaxtnuKtLX1-wJylBKDlweHf7ST5ItpCE7yPac/edit#heading=h.xy4w62seq4am

**Comment by arafatkatze** [comment]
The document is [here](https://docs.google.com/document/d/1YD0MMUaxtnuKtLX1-wJylBKDlweHf7ST5ItpCE7yPac/edit#heading=h.xy4w62seq4am) it works fine and I tested it

<img width="483" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/11155207/1f0b777b-91dc-47e6-96ef-2b21f68af74c">
