### ISSUE TITLE
Browser extension: code intelligence on diffs does not work

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#605]
- **Sourcegraph version:** Browser ext 1.18.0
- **Platform information:**  macOS High Sierra, Chrome 70

#### Steps to reproduce:

1. Go to https://github.com/sourcegraph/sourcegraph/pull/586/files
2. Try to hover over anything. Notice no hovers work. 
3. Notice this error in the console:
![image](https://user-images.githubusercontent.com/16265452/47748347-cfafe500-dc47-11e8-9f3f-6bad04257088.png)

It appears there is an issue w this line now: 
https://sourcegraph.com/github.com/sourcegraph/browser-extensions/-/blob/src/libs/github/dom_functions.ts#L207:22 

#### Expected behavior:
Hovers work.

#### Actual behavior:
Hovers don't appear.

**Comment by attfarhan** [comment]
cc @chrismwendt (looks like the line above was written by you)

**Comment by chrismwendt** [comment]
I committed and @ijsnow authored it. I'm guessing the particular `td` element doesn't exist, so `querySelector` is returning `null`, but I'm not sure what could be causing that.

**Comment by ijsnow** [comment]
The DOM could have changed. I'm working on other high priority issues right now. This is probably a simple change. If I were to start debugging, I'd log the built selector and the parent we're looking for the link in then try to find something that looks like it.

**Comment by attfarhan** [comment]
This breaks diffs when there's a newly added file, since the blue border on the top is considered a row, but `line` will be null. https://github.com/sourcegraph/sourcegraph/pull/586/files#diff-f9e579844875cb46d3b49926faf8c740. PR open to fix: https://github.com/sourcegraph/sourcegraph/issues/605

**Comment by attfarhan** [comment]
@sqs yeah the feature flag is enabled when I run into this error, without it enabled it works

**Comment by ijsnow** [comment]
It's not directly an extensions bug though. It's a bug in GitHub's `getLineRanges` function for its `CodeHost` interface which is only required for extensions (because we have to send extensions the full file contents which we can only get from the DOM so we have to hackily scrape it :/ )
