### ISSUE TITLE
Regex toggle popup looks broken in dark theme

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#6051]
![image](https://user-images.githubusercontent.com/10532611/66878417-a1b5d480-ef6e-11e9-81c1-326747f30b73.png)

The old justification for these popups being light theme was that this was marketing/user research content (survey, browser extension ad) that is separate from the app, but imo this is tightly coupled to an in-app feature and as a user I would expect it to follow the theme.

**Comment by tsenart** [comment]
I don't consider this to be a release blocker so moving to Backlog.
