### ISSUE TITLE
Code intel popover automatically continues shrinking at small screen sizes

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/sourcegraph#60540]
Browser: Firefox 122.0

URL: https://sourcegraph.com/github.com/uber-go/cff@239d0216e326c2d061a71c62fbfe7b8bbd4771ef/-/blob/internal/package.go?L85:14&popover=pinned

![](https://github.com/sourcegraph/sourcegraph/assets/93103176/6a4142ff-7895-4367-9801-0b91f1ed486e)

**Comment by camdencheek** [comment]
@varungandhi-src I cannot reproduce this. Do you have any more detailed reproduction steps?

**Comment by varungandhi-src** [comment]
Unable to reproduce, closing.
