### ISSUE TITLE
[strat:P] Display new chat/commands metrics

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#60562]
PRD discussion: https://docs.google.com/document/d/1RO6BiFILyciMy8UtkznX6Z4ewqzJhwmhg7CEKI-YrSg/edit?disco=AAABEcMRSV4

Logging ticket: https://github.com/sourcegraph/jetbrains/issues/637

**Comment by cbart** [comment]
cc @aramaraju do we need to prioritize this?

**Comment by aramaraju** [comment]
Recommending a P1 here, as we can probably support this through raw data for PANW pilot

**Comment by arafatkatze** [comment]
Closed by https://github.com/sourcegraph/jetbrains/pull/814
