### ISSUE TITLE
Add .C and .H files to C++ file types

### ISSUE THREAD

**Issue by morgangauth** [sourcegraph/sourcegraph#60575]
#### Feature request description

Currently, `.c` and `.h` files are registered as C++ file types. In order for `.C` and `.H` files to be returned when filtering on `lang:C++` case sensitivity needs to be turned off, but C++ is a case-sensitive language so the rest of the search will contain false positives (e.g. enumField and EnumField are different) 

#### Is your feature request related to a problem? If so, please describe.

Some customers who use `.C` and `.H` files get false positives when searching with case-sensitivity disabled in order for those files to be included as C++ files. For example, `lang:C++ enumField` with case sensitivity turned **on**, will not include `.C` and `.H` files. When case sensitivity is turned **off**, then results for both `EnumField` and `enumField` will be returned, which includes false positives, as `EnumField` differs from `enumField`. 

#### Describe alternatives you've considered.

An alternative is to use regex search with `(file:.*\.C OR file:.*\.H)`, with case sensitivity enabled.

#### Additional context

go-enry file extensions listed here: https://github.com/go-enry/go-enry/blob/v2.8.4/data/extension.go

/cc @sourcegraph/search-platform

**Comment by morgangauth** [comment]
requested by https://github.com/sourcegraph/accounts/issues/7485

**Comment by varungandhi-src** [comment]
I think there might be a mistake here; `.C` is not a common file extension for C++, it is used for C. Are you 100% sure that it was requested for C++ and not C? Can you link to a Chorus call or similar where this was requested?

In the file that you linked: https://github.com/go-enry/go-enry/blob/v2.8.4/data/extension.go#L142

```
	".c":                   {"C"},
```

There is no C++ in that line.

**Comment by morgangauth** [comment]
@varungandhi-src good catch. The request specifically called out .C and .H for C++ but let me confirm that this is correct. Support request linked here: https://sourcegraph.zendesk.com/agent/tickets/16703

**Comment by jtibshirani** [comment]
@morgangauth we just merged a fix, so it will be available in the upcoming 5.3.4 monthly release.
