### ISSUE TITLE
Jetbrains: Cody Completions not formatted correctly

### ISSUE THREAD

**Issue by MehrJonas** [sourcegraph/sourcegraph#60590]
- **Sourcegraph version:** 5.3.27 (Jetbrains plugin)
- **Platform information:** Windows, IntelliJ 2023.2, IdeaVim plugin enabled

#### Steps to reproduce:

1. Enable Cody Completions
2. Write some code, cody suggests a multiline completion
3. Accept the suggestion

#### Expected behavior:

Inserted code is correctly formatted

#### Actual behavior:

The code is often incorrectly formatted, as in the following example (there is a linebreak missing):
```

public class Test {
    public static void main(String[] args) {            System.out.println("Hello World");
}
}
```

**Comment by taylorsperry** [comment]
Closed in favor of https://github.com/sourcegraph/jetbrains/issues/987
