### ISSUE TITLE
Serious problems with external service auth provider config are never shown

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#6061]
See this comment for full context: https://github.com/sourcegraph/sourcegraph/issues/6039#issuecomment-542705269

When you configure an external service, let's say Gitlab, with an invalid `authorization` config, like this:

```json
{
  "url": "https://gitlab.fooooobar.org",
  "token": "TOOOOOKEN",
  "projectQuery": [
    "?"
  ],
  "authorization": {
    "identityProvider": {
      "type": "external",
      "authProviderID": "testingtestinginvalid",
      "authProviderType": "openidconnect",
      "gitlabProvider": "saml"
    },
    "ttl": "3h"
  }
}
```

then this will validation and produce a `seriousProblem`: https://github.com/sourcegraph/sourcegraph/blob/b1f43ea108b0e93c9df3f75b7f756aaee95c53a1/enterprise/cmd/frontend/internal/authz/init.go#L43-L50

The problem is that these `seriousProblems` are never displayed or logged in the UI:

https://github.com/sourcegraph/sourcegraph/blob/b1f43ea108b0e93c9df3f75b7f756aaee95c53a1/enterprise/cmd/frontend/internal/authz/init.go#L35-L41

But they _do_ cause `allowAccessByDefault` to be set to `false`, which causes the `builtin` auth provider to not work anymore.

**Comment by slimsag** [comment]
This should be working. It is possible this is a regression in 3.9?

**Comment by mrnugget** [comment]
> This should be working. It is possible this is a regression in 3.9?

Looking at the code where the `seriousProblems`, _how_ should this be working? The `seriousProblems` are assigned to `_`:

https://github.com/sourcegraph/sourcegraph/blob/b1f43ea108b0e93c9df3f75b7f756aaee95c53a1/enterprise/cmd/frontend/main.go#L52-L53

When creating/updating an external service, the error _is_ displayed. Did you mean that? In our case, that didn't help with a fast diagnosis of the problem, because we had to update every external service to find which one has an invalid config.

---

I thought that this could maybe displayed as an error in the status indicator... 🤔

**Comment by slimsag** [comment]
well, here's the regression (apparently nick wrote it intentionally and I approved it. I don't know what I was thinking): https://github.com/sourcegraph/sourcegraph/pull/1416/files#r335820234

**Comment by slimsag** [comment]
(regression was last Dec. so not a release blocker)

**Comment by slimsag** [comment]
BTW this should be showing up as a site alert, on the top of the page similar to how when you start a fresh instance it warns you that `externalURL` is not set in the management console.

**Comment by slimsag** [comment]
If we have no way to validate _just_ the configuration (separate from the DB state of external services, which I assume was the problem and I guess why Nick removed it), then this is just another downside of having external services be separate from the rest of the config system and we'll need to build a separate validator that creates a site alert here independent from the existing config validation: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@c786d7943361a913ce28eec6cf8b47f0c20d58f3/-/blob/cmd/frontend/graphqlbackend/site_alerts.go#L87-95

**Comment by mrnugget** [comment]
> well, here's the regression (apparently nick wrote it intentionally and I approved it. I don't know what I was thinking): https://github.com/sourcegraph/sourcegraph/pull/1416/files#r335820234



> BTW this should be showing up as a site alert, on the top of the page similar to how when you start a fresh instance it warns you that `externalURL` is not set in the management console.

Am I understanding this correctly: the removed `ContributeValidator` was the thing that would display a site alert at the top of the page?

**Comment by slimsag** [comment]
Yes. `ContributeValidator` contributes a function which validates a critical+site config union. When it returns problems, they are [surfaced to site admins as alerts](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@c786d7943361a913ce28eec6cf8b47f0c20d58f3/-/blob/cmd/frontend/graphqlbackend/site_alerts.go#L87) and [printed to the logs on frontend startup](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@c786d79/-/blob/cmd/frontend/internal/cli/config.go#L27-40).

The alerts are displayed on all pages for admins and look like this for example:

![image](https://user-images.githubusercontent.com/3173176/66985187-183afb00-f071-11e9-834a-17a45e9a20ca.png)

**Comment by nicksnyder** [comment]
> If we have no way to validate just the configuration (separate from the DB state of external services, which I assume was the problem and I guess why Nick removed it)

IIRC we had to make a tough decision between "bad" and "broken" and we chose "bad". I am not sure we realized how "bad" it was and we didn't follow up. This was around the time I was trying to hand of my engineering responsibilities so I think this slipped through the cracks.

> this is just another downside of having external services be separate from the rest of the config system

For what it is worth, I regret our decision to separate these configs. I don't think it added clarity and it certainly made some things more complicated.

**Comment by keegancsmith** [comment]
@sourcegraph/core-services We don't have a clear owner for this issue. Can someone do it for 3.10? Or should we cut this for another release? Personally I won't have time this milestone.

**Comment by tsenart** [comment]
@unknwon: This seems aligned with the work you'll be doing in RFC 40 which specifies we should show site banner for invalid authorization configurations. Do you think this is something you should take on 3.10 as well?

**Comment by unknwon** [comment]
One problem is the code produces external service authz provider "problems" lives under `enterprise/` directory, but site alerts are produced in OSS directories. What we typically do is to import code from OSS directories in `enterprise/`, not the other way around.

Should I go ahead do whatever takes for now to fix the issue?

**Comment by tsenart** [comment]
> One problem is the code produces external service authz provider "problems" lives under enterprise/ directory, but site alerts are produced in OSS directories. What we typically do is to import code from OSS directories in enterprise/, not the other way around.

We typically use either dependency injection or the package level global mutation to alter behaviour. Look at the frontend enterprise main function for reference.

> Should I go ahead do whatever takes for now to fix the issue?

I don't think this is urgent, but it is important and I believe it's in scope with the rest of the work you're doing in 3.10. So I defer to you as to when exactly you think it's best to address this.

As always, I'm available to discuss problems / solutions / ideas.
