### ISSUE TITLE
2.13 test plan

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#607]
This issue tracks tasks associated with the [2.13 release](https://github.com/sourcegraph/sourcegraph/tree/2.13).

Relevant commits: https://github.com/sourcegraph/sourcegraph/compare/2.12...2.13

Test the release candidate with this command:
```
docker pull sourcegraph/server:2.13-insiders
docker run --publish 7080:7080 --rm --volume /tmp/sourcegraph/config:/etc/sourcegraph --volume /tmp/sourcegraph/data:/var/opt/sourcegraph --volume /var/run/docker.sock:/var/run/docker.sock sourcegraph/server:2.13-insiders
```

- [x] Test [GitHub Advanced Repository Selection](https://github.com/sourcegraph/sourcegraph/pull/482) @nicksnyder 
- [x] Test code intelligence works (Go, TypeScript) @nicksnyder 
- [x] Test [transformQuery](https://github.com/sourcegraph/sourcegraph/pull/499) @nicksnyder
- [x] Test indexed search @nicksnyder  (~~bug: https://github.com/sourcegraph/sourcegraph/issues/621~~)
- [x] Test upgrade from 2.12 @nicksnyder
- [x] Test [GitLab auth permissions](https://github.com/sourcegraph/sourcegraph/pull/557) @beyang 
- [x] Tag 2.13 release @nicksnyder

**Comment by attfarhan** [comment]
To test search using transformQuery:

1. Enable these extensions (these all register a queryTransformer):
- https://sourcegraph.com/extensions/farhan/go-imports-search
- https://sourcegraph.com/extensions/farhan/js-dependency-search
- https://sourcegraph.com/extensions/farhan/python-imports-search

1. Clone a python, JS, Go repository to your instance if you haven't already.

1. Conduct a search with `go.imports:$A_PACKAGE_NAME`, `js.depends:$A_DEP_NAME`, `py.imports:$A_MODULE_NAME`, and make sure that results that appear make sense. 

1. Conduct some searches without any of these operators and ensure search still works as normal.

**Comment by keegancsmith** [comment]
# indexed search enablement

A search query with `index:only` can be used to see if indexed search is working.

### Single Docker Image

- By default indexed search should be disabled.
- If you start the container with the environment `INDEXED_SEARCH=t` it should be enabled (backwards compatibility)
- In the config set `search.index.enabled: true`. Repositories should start indexing and `index:only` should start returning results.
- After confirming index search is working, set `search.index.enabled: false` and start seeing no results. (optional) After a few minutes confirm the search indexes are deleted and the zoekt-* processes have low resource usage.

### Cluster

- By default indexed search should be enabled.
- (optional) In the config set `search.index.enabled: false`. Search results should no longer be returned. This is a highly unlikely configuration.
