### ISSUE TITLE
Docs claim that management console can be accessed despite TLS error, but that is not true

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#6070]
A fresh Docker instance is telling me that I must go to the management console and set `externalURL`.

The docs say:

> You must click the Advanced option in your browser and continue anyway (Proceed to localhost (unsafe)).

https://docs.sourcegraph.com/@v3.9.0-rc.4/admin/management_console#what-is-the-password-to-my-management-console

That option does not exist (Chrome 77.0.3865.120) and it is therefor impossible to access the management console, unless I use Safari.

![image](https://user-images.githubusercontent.com/10532611/66963703-30872780-f029-11e9-9bc2-a484ecb6c161.png)

**Comment by unknwon** [comment]
What I did to get around with this: https://css-tricks.com/getting-around-revoked-certificate-osx/
