### ISSUE TITLE
Relicense `lib` under an OSI compatible license

### ISSUE THREAD

**Issue by kamikazechaser** [sourcegraph/sourcegraph#60716]
#### Feature request description

Some parts of sourcegraph have useful tiny utilities, e.g. the [`lib`](https://github.com/sourcegraph/sourcegraph/tree/main/lib) package, that would have almost no impact on business if the License was changed back to an OSI compatible one i.e. Apache 2.0.

#### Is your feature request related to a problem? If so, please describe.

Related to #53528

#### Describe alternatives you've considered.

Copying and modifying from https://github.com/sourcegraph/sourcegraph/commit/1cd36d2dbbd2a9ab638cc437d208d2717eaefb0b where Apache still applies.

#### Additional context

None

**Comment by sqs** [comment]
We have nothing in principle against this, but it is not a priority for us (extracting to a separate repo, relicensing, and maintaining for OSS).

**Comment by kamikazechaser** [comment]
You would just need to put a LICENSE file in the `lib` folder.

Quoting the relevant main LICENSE file:

> except for files in or under any directory that contains a
superseding license file.
