### ISSUE TITLE
VSCode Search plugin error when using 5.3.0 instance

### ISSUE THREAD

**Issue by enriquegh** [sourcegraph/sourcegraph#60710]
- **Sourcegraph version:**  5.3.0
- **Plugin version:** v2.2.16
- **Platform information:** 
macOS 14.1

#### Steps to reproduce:

1. Install latest version of VSCode Code Search plugin ([link](https://marketplace.visualstudio.com/items?itemName=sourcegraph.sourcegraph)) 
2. Open extension and click "Have an Account?"
3. Enter instance URL and access token
4. See error:
```
Unable to verify your access token for sourcegraph.com. Please try again with a new access token or restart VS Code if the instance URL has been updated.

```

#### Expected behavior:
Extension should authenticate and allow user to search

#### Actual behavior:
Error is thrown and cannot authenticate

#### Additional information:
Looking at the request sent to the instance it contains the following GraphQL query:

```
query CurrentAuthState {
  currentUser {
    __typename
    id
    databaseID
    username
    avatarURL
    email
    displayName
    siteAdmin
    url
    settingsURL
    organizations {
      nodes {
        id
        name
        displayName
        url
        settingsURL
      }
    }
    session {
      canSignOut
    }
    viewerCanAdminister
    tosAccepted
    searchable
    emails {
      email
      verified
    }
  }
}
```

which returns an empty string on 5.3.0 but not on previous versions. This is due to a change in 5.3.0 where we dropped `searchable` DB column ([link](https://github.com/sourcegraph/sourcegraph/pull/60429)).

#### Screenshots

<img width="1720" alt="Screenshot 2024-02-22 at 15 10 56" src="https://github.com/sourcegraph/sourcegraph/assets/6495540/ea3d4272-4a07-4edd-a83e-2892a3a6c367">

<img width="1496" alt="Screenshot 2024-02-22 at 15 14 55" src="https://github.com/sourcegraph/sourcegraph/assets/6495540/67a8acb0-3eec-49c3-bbe4-675bcb7c42e4">

If you would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are no [SLAs](https://sourcegraph.com/support/) on issues like there are for support requests).

**Comment by alexAtSourcegraph** [comment]
Happening to: 

[sourcegraph/accounts#8760](https://github.com/sourcegraph/accounts/issues/8760)

**Comment by camdencheek** [comment]
Workaround documented [here](https://www.loom.com/share/10a4a66a19b548c7b0866fe2cc358daa?sid=617c9b34-357f-470a-abdb-f560cc942404), but this is on our radar to fix

**Comment by loujar** [comment]
Also reported by https://github.com/sourcegraph/accounts/issues/8004
