### ISSUE TITLE
Telemetry: Track origin of signup

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#60741]
Copied from [slack conversation](https://sourcegraph.slack.com/archives/C05EMJM2SLR/p1708629693587119):

Hey Source folks - could I put in a telemetry request? I'm looking at the ExternalAuthSignupSucceeded event and I was wondering if we could tag it with metadata for whether the signup was:
Triggered from the web (aka user signs up first, and then installs)
Triggered from the IDE (aka user installs first, and then signs up through the IDE flow)
I believe we can since we have logic that re-routes users back to the IDE after the Hubspot work/personal form during the onboarding flow if they trigger signup from the IDE. Can I get your help adding logging for this?
Why:
In our effort to move retention, we're breaking down the funnel in each step: signup, install, first DAU action in the product, and then DAU actions in subsequent days.
What makes this difficult to currently measure, however, is that without that metadata, we can't tell whether or not a user started with signup before or after install. So our metrics are always kind of muddy
(ie we get twisted up with things like: "the dashboard shows signup --> install rate is 10%, but that's because a lot of the signup events shouldn't even be counted because they happened after install, so we don't really know what it is")

**Comment by eseliger** [comment]
cc @chenkc805

**Comment by dadlerj** [comment]
Just curious—do users go _direct_ from the editor to the /.auth URL and into the auth flow? Or do they land on a dotcom page and then see an option to sign in from GitHub/GitLab/etc.?

**Comment by eseliger** [comment]
Yes, directly to `/.auth` is my understanding, to trigger a flow where it's almost invisible that you connect to dotcom vs SAMS.

**Comment by chenkc805** [comment]
Hey @eseliger , bumping this, as this is pretty important for understanding how to improve retention. How can I help get this prioritized with the Source team? Context here: https://sourcegraph.slack.com/archives/C06K09TB8UR/p1711395129411779

**Comment by eseliger** [comment]
Checking

**Comment by chenkc805** [comment]
Thank you for re-opening this @eseliger . We've been intending to investigate this on the Cody Prime team but have 0 bandwidth to do so

**Comment by eseliger** [comment]
Pardon, this was some hiccup of Linear getting out of date and me touching the tickets so it triggered a reconciliation.

I will move this in linear to the cody prime team
