### ISSUE TITLE
Improve proposed queries for literal search 

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#6074]
We currently append `patternType:regexp` to all proposed queries which are displayed when a user runs into a "too many repos" or "no repos found" error. Ideally, we should be able to come up with equivalent suggestions when in literal search mode without appending patternType:regexp.

https://github.com/sourcegraph/sourcegraph/blob/84a4f70d658368ee3eb4b0f66b374a2324604eb6/cmd/frontend/graphqlbackend/search_alert.go#L39

**Comment by poojaj-tech** [comment]
cross-linking [#14668](https://github.com/sourcegraph/sourcegraph/issues/) as it's also about `patternType:regexp` and we should look at both issues together.

**Comment by camdencheek** [comment]
Closing as stale
