### ISSUE TITLE
Gitlab /projects usage improvements

### ISSUE THREAD

**Issue by enriquegh** [sourcegraph/sourcegraph#60742]
#### Question description

From an EM at Gitlab:

> I'm wondering if you could connect me with an engineer or EM who is familiar with requests to the GitLab GET /projects API endpoint made from the user agent Sourcegraph-Bot. I'm assuming these are calls from Sourcegraph to index a GitLab user's repos. We noticed a lot of the requests are quite slow and may be returning more data than needed, and I was hoping I could talk to someone at Sourcegraph about potentially making more efficient use of the endpoint.

#### Additional context

Internal Slack thread:
https://sourcegraph.slack.com/archives/C05EMJM2SLR/p1707513264604149?thread_ts=1707512398.176149&cid=C05EMJM2SLR

cc @ggilmore

**Comment by nnguyen-gl** [comment]
Hi Sourcegraph team! I'm the EM from GitLab who wrote into support. We noticed the `Sourcegaph-Bot` user agent is making a lot of calls to our `api/v4/projects` endpoint. It returns a large payload by default and can be quite slow for certain requests. Would it be possible to return a limited subset of fields using the `simple=true` param? Another open-source project using this endpoint was able to implement something similar - https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/pull/634/commits. For more details about this API endpoint, please see https://docs.gitlab.com/ee/api/projects.html#list-all-projects. Happy to answer any other questions you may have. Thanks!

**Comment by pjlast** [comment]
Hi @nnguyen-gl . Unfortunately the `simple=true` strips away a few things we require, namely:

`visibility`
`archived`
`forked_from_project`

We require `visibility` for access control, and `archived` and `forked_from_project` for search filtering, since users often don't want to search archived repos, and don't want forks as part of their results.

**Comment by pjlast** [comment]
@nnguyen-gl do you know what the earliest GitLab version is that supports `simple=true` ? Has this always been available?

**Comment by nnguyen-gl** [comment]
> @nnguyen-gl do you know what the earliest GitLab version is that supports `simple=true` ? Has this always been available?

@pjlast I don't know the exact version, but from looking through our past issues I see that it's been supported for at least the last 5 years. Does that help?

**Comment by pjlast** [comment]
@nnguyen-gl yep that's perfect, thanks!
