### ISSUE TITLE
Hidden 401 error in Bitbucket Server API request

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#6079]
- **Sourcegraph version:** k8s.sgdev.org
- **Platform information:** dogfood-full-k8s

When a user has no permission to access the Bitbucket Server (i.e. not able to login Bitbucket Server via web interface), update permission in background will always fail with the following error:

```
Bitbucket API HTTP error: code=401 url="https://bitbucket.sgdev.org/rest/api/1.0/repos?limit=1000&user_id=zoom" body=""
```

This error is only visible in the LightStep, for example: 

https://app.lightstep.com/sourcegraph-dev/trace?span_guid=1a957cf37fa2ede6&at_micros=1571291619575376#span-5e70d429c2cc6d5f

The UI only shows: `read:repos permissions for user=73 are stale and being updated`.

Look at the code, it does print the error, but I don't know where it goes for k8s.sgdev.org.

https://github.com/sourcegraph/sourcegraph/blob/c786d7943361a913ce28eec6cf8b47f0c20d58f3/enterprise/cmd/frontend/internal/authz/bitbucketserver/store.go#L157-L162

Nevertheless, this error should be displayed somewhere more visible.

Debugged together with @mrnugget.

---

I previously solved by adding the user to Global Permissions (`bitbucket.sgdev.org/admin/permissions`) -> User access with Bitbucket User box checked.

**Comment by keegancsmith** [comment]
Is this something we need to do in 3.11? I am guessing it may be related/solved by @kzh's work since he will be adding a custom endpoint. @kzh what do you think?

**Comment by unknwon** [comment]
It's not urgent, I think it's about how to display the error message in UI. i.e customers will always be able to find the error message in logs.

It's unrelated to @kzh's BbS plugin work IMO.

**Comment by tsenart** [comment]
@unknwon: Given BitbucketServer permissions syncing will move to repo-updater soon, can we close this?

**Comment by unknwon** [comment]
I think it's unrelated to how we sync, but since I now know [how to look for logs on GCP UI](https://about.sourcegraph.com/handbook/engineering/on_call#access-pod-logs-in-gcp-console), I think it can be closed 😄
