### ISSUE TITLE
Single ctags docker image

### ISSUE THREAD

**Issue by kzh** [sourcegraph/sourcegraph#6080]
At the moment, the docker images for zoekt index-server and the unindexed symbols service build and use their own ctags binary. This can cause version mismatches and lead to inconsistent user experience. There should be one docker images for ctags from which other docker images pull the ctags binary from.

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.10 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
