### ISSUE TITLE
Code nav popover does not trigger for identifiers in Jenkinsfile and .gradle files

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/sourcegraph#60818]
If I hover on varoius identifiers, such as `axes` in [this line](https://sourcegraph.com/github.com/jenkinsci/jenkins@50f675f6e7a255e743066311c3acb7b35e59d008/-/blob/Jenkinsfile?L15), there is no search-based code navigation being triggered.

It should be triggering a search with `lang:Groovy`.

Discovered while investigating https://github.com/sourcegraph/customer/issues/2858

Similar problem in `.gradle` files: [example](https://sourcegraph.com/github.com/spring-projects/spring-boot@40a702770716bfa378542b2354d60702a932481a/-/blob/buildSrc/build.gradle?L16:1-16:4) (which are also Groovy)

There is no such problem with files using the `.groovy` extension ([example](https://sourcegraph.com/github.com/spring-projects/spring-boot@40a702770716bfa378542b2354d60702a932481a/-/blob/spring-boot-project/spring-boot-tools/spring-boot-maven-plugin/src/main/groovy/generateGoalsDocumentation.groovy?L78:5-78:11#tab=references)).

**Comment by varungandhi-src** [comment]
So this is because we do not correctly mark identifiers in Groovy, and the reason for that is the underlying Sublime grammar doesn't mark identifiers properly.

Example test case: https://sourcegraph.com/github.com/sourcegraph/Packages@7481597c6971eec37f0df60a77b2b2a65099fb62/-/blob/Groovy/syntax_test_groovy.groovy?L51-54

Can we add a workaround in the client-side code to _not_ rely on the SCIP syntax kinds for Groovy? The other alternatives would be to [fix the highlighting itself](https://github.com/sourcegraph/sourcegraph/issues/60820):
1. Add support for highlighting Groovy properly using Tree-sitter (I found a couple of grammars on GitHub), but this would require several days worth of work. 
2. Add a patch to our fork of the Sublime Grammars (which already have a bunch of tech debt and we've essentially frozen development on them). This would really be an option of last resort.

I think adding the workaround would be faster, and perhaps the more sensible thing to do to save time, given that Groovy isn't a major language.

**Comment by hearit-danny** [comment]
In our on-prem instance of Sourcegraph, I have noticed this issue too. It seems to happen regardless if the file type is groovy or not, but whether it is scripted groovy (like in jenkinsfiles or gradle files) both can end in .groovy or not, and it has a difficult time finding all references and never definitions in our test examples.

If you think this is a different issue and would like me to post elsewhere or would like me to provide details and examples, please let me know.

**Comment by varungandhi-src** [comment]
@hearit-danny, this issue has the following scope based on the title:

>  Code nav popover does not trigger for identifiers in Jenkinsfile and .gradle files

Your issue sounds different:

> Both jenkinsfiles and gradle files can end in .groovy or not, and it has a difficult time finding all references and never definitions in our test examples

If the problem is _wrong_ code navigation, rather than the popover not showing up at all, then please file a separate issue through the official support channel and share details there. Your account's support engineer can file an issue privately so there shouldn't be a concern for leaking internal source code.
