### ISSUE TITLE
Keypad enter key doesn't work with command/ctrl + F in file view

### ISSUE THREAD

**Issue by hopkinscl** [sourcegraph/sourcegraph#60868]
* **Sourcegraph version:** 5.3.1
* **Platform information:** Chrome version 122.0.6261.94

#### Steps to reproduce:

1. Navigate to a file, e.g. [this one](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@e2be6a42a09e21541cc35dfc9d16b52cbfda5521/-/blob/cmd/frontend/graphqlbackend/settings_mutation.go)
2. Use command/ctrl + F to find a string in the file, e.g. `new` in the file linked above
3. Hit return/enter to tab between results

#### Actual behavior: Keypad enter button does not tab between results

**Comment by fkling** [comment]
This was fixed with [https://github.com/sourcegraph/sourcegraph/pull/62665](https://github.com/sourcegraph/sourcegraph/pull/62665)
