### ISSUE TITLE
rules_apko

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#60894]
Implementation: https://github.com/sourcegraph/sourcegraph/pull/60785

2024-03-06: @Strum355 blocked on Will returning, which won't be until the next week

**Comment by Strum355** [comment]
From Will:
> what’s holding me back from merging is the supporting components that will need updating:
> - local dev tooling for building images (+ using local package repos)
> - buildkite CI pipeline for branches
> - buildkite auto-update pipeline
> - docs
> one option would be to merge without the {cmd,docker-images}/*/BUILD.bazel  files so the supporting files are there but we don’t actually flip the switch to use them yet
> I’m on support rota this week, but can spend some time working on the above
