### ISSUE TITLE
Extending Bitbucket Server Plugin

### ISSUE THREAD

**Issue by kzh** [sourcegraph/sourcegraph#6091]
This issue is for tracking extending the capabilities of the bitbucket server plugin for automation and permissions. See [RFC 45: Extending Bitbucket Server Plugin](https://docs.google.com/document/d/1I3Aq1WSUh42BP8KvKr6AlmuCfo8tXYtJu40WzdNT6go/edit) for more details.

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.10 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.11 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by tsenart** [comment]
Done!
