### ISSUE TITLE
Error fetching github.com repositories

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#6095]
- **Sourcegraph version:** 3.8.2
- **Platform information:** docker

#### Steps to reproduce:

A user reported the following:

> I get this error when I added my token and hit the “Update external service” button.
>
>Warning
>
>External service updated, but we encountered a problem while validating the external service: Error getting GitHub repository: nameWithOwner=gcc-mirror/gcc: request to http://127.0.0.1:3180/repos/gcc-mirror/gcc returned status 500:

Their external service config:

```
{
    "url": "https://github.com",
    "token": “xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",

    "repositoryQuery": [
        "user:$USERNAME"
    ],
    "repos": [
        "gcc-mirror/gcc"
    ],
}
```

(Where $USERNAME is their username)

And logs showing:

```
23:12:48 github-proxy | t=2019-10-17T23:12:48+0000 lvl=warn msg="proxy error" err="Post https://api.github.com/graphql: x509: certificate signed by unknown authority"
23:12:48 repo-updater | t=2019-10-17T23:12:48+0000 lvl=warn msg="Failed to decode error response from github API" error="invalid character 'P' looking for beginning of value"
23:12:48 repo-updater | t=2019-10-17T23:12:48+0000 lvl=warn msg="github sync: fetching in batches failed. falling back to sequential fetch" error="request to http://127.0.0.1:3180/graphql returned status 500: "
23:12:49 github-proxy | t=2019-10-17T23:12:49+0000 lvl=warn msg="proxy error" err="Get https://api.github.com/repos/gcc-mirror/gcc: x509: certificate signed by unknown authority"
23:12:49 repo-updater | t=2019-10-17T23:12:49+0000 lvl=warn msg="Failed to decode error response from github API" error="invalid character 'G' looking for beginning of value"
23:12:49 github-proxy | t=2019-10-17T23:12:49+0000 lvl=warn msg="proxy error" err="Get https://api.github.com/search/repositories?page=1&per_page=100&q=user%3Ausername: x509: certificate signed by unknown authority"
23:12:49 repo-updater | t=2019-10-17T23:12:49+0000 lvl=warn msg="Failed to decode error response from github API" error="invalid character 'G' looking for beginning of value"
23:12:49 repo-updater | t=2019-10-17T23:12:49+0000 lvl=eror msg=Syncer error="syncer.sync.sourced: 2 errors occurred:\n\t* Error getting GitHub repository: nameWithOwner=gcc-mirror/gcc: request to http://127.0.0.1:3180/repos/gcc-mirror/gcc returned status 500: \n\t* failed to list GitHub repositories for search: page=1, searchString=\"user:username\": request to http://127.0.0.1:3180/search/repositories?page=1&per_page=100&q=user%3Ausername returned status 500: \n\n”
```
(where I’ve replaced the username with “username” throughout the logs).

Any ideas? L

**Comment by unknwon** [comment]
Looks like we don't have support for self-signed code hosts: https://github.com/sourcegraph/sourcegraph/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+certificate+signed+by+unknown+authority

**Comment by dadlerj** [comment]
Can you clarify? The user is using github.com.

**Comment by unknwon** [comment]
But yeah... the config says "https://github.com"... still digging.

**Comment by unknwon** [comment]
cc @sourcegraph/distribution

**Comment by dadlerj** [comment]
Not sure if it's relevant, but I actually wasn't able to repro the issue before I filed it. I ran the `docker run` command with 3.8.2 from docs.sourcegraph.com, set up a similar github.com external service, and added a token, and it worked just fine.

**Comment by unknwon** [comment]
Is it a fresh pull of sourcegraph/sourcegraph:3.8.2 or did they upgrade from the old version? (I'm not sure what's the difference here that could cause `ca-certificates` out-of-date, if that's the real root cause)

**Comment by dadlerj** [comment]
Could this be the same issue as https://github.com/sourcegraph/sourcegraph/issues/71?

**Comment by unknwon** [comment]
@dadlerj:
> Could this be the same issue as #71?

#71 is asking for support of self-signed certificated of on-prem code hosts (i.e. GitHub Enterprise in that case), which was I thought in the comment above: https://github.com/sourcegraph/sourcegraph/issues/6095#issuecomment-543408436, because the error message often occurs in self-signed scenario.

Then I realize the customer is trying to access the https://api.github.com, which is a public service. So the problem should be something else, possibly some server config outdated (since it is unlikely github.com got their certificates expired).

**Comment by keegancsmith** [comment]
Is it possible they have transparent proxying setup? ie can the user go into the container and try run 
```shell
apk --no-cache add curl
curl -v https://api.github.com
```

Either way the error we are reporting back is very poor. We should improve on that.

**Comment by keegancsmith** [comment]
@dadlerj I don't think this is a bug, I think this is more than likely an issue in the customers networking setup. Could you ask them?

**Comment by dadlerj** [comment]
Thanks @keegancsmith! I asked the user to cURL the github API from inside the container and this is what he got back. 

I then asked him to confirm he could access the GitHub from the host machine, and he had no problem. Makes me unsure as to whether it’s on his side.

>>>
see

/ # apk --no-cache add curl
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
(1/1) Installing curl (7.66.0-r0)
Executing busybox-1.29.3-r10.trigger
OK: 98 MiB in 65 packages
/ # curl -v https://api.github.com
* Trying 192.30.255.116:443...
* TCP_NODELAY set
* Connected to api.github.com (192.30.255.116) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
* CAfile: /etc/ssl/certs/ca-certificates.crt
CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: self signed certificate in certificate chain
* Closing connection 0
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**Comment by keegancsmith** [comment]
Yes this sounds like a problem with networking in the container. I am assuming the host machine has some sort of root CA certificate installed such that things seamlessly work within there networking setup. However, the docker container won't have that. The fact that curl fails confirms that. I am assuming they have issues in general with containers trying to contact the outside world?

It looks like they are using our single docker image, so it may suffice to just install this root certificate into the container. The person probably needs to reach out to someone inside of their company to find out more.

https://github.com/sourcegraph/sourcegraph/issues/71 would likely solve this issue for customers who have these requirements.

**Comment by keegancsmith** [comment]
@dadlerj is there anything else we can do here? Or should we close this out?

**Comment by dadlerj** [comment]
I'll reopen if I hear back from the user
