### ISSUE TITLE
Code nav hovers are not working

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#60985]
On Sourcegraph.com, code nav hovers are not working. They fail when I'm signed in and in incognito mode signed out. Here are 2 instances of the same issue:

## First instance

At https://sourcegraph.com/github.com/facebook/lexical@830b7e17f41557ea9220c5e6e81bf045cd4a3280/-/blob/packages/lexical-markdown/src/index.ts?L77:9-77:23, no hover appears when hovering anything (including `importMarkdown` and `createMarkdownImport`, even though Cmd+Click works to go to def). The JS error in the console is:

```
Uncaught Invariant Violation: Invariant Violation: 32 (see https://github.com/apollographql/invariant-packages)
    at new e (https://sourcegraph.com/.assets/chunks/chunk-chunk-LO5XSUI4.js:3:1573)
```

## Second instance

At https://sourcegraph.com/github.com/sourcegraph/sourcegraph@0243865d0009ebf9cd70b41dc7d4b6c74264f0a1/-/blob/internal/vcs/url.go?L37:6-37:14, same.

**Comment by fkling** [comment]
This was fixed on Friday but dotcom hasn't been deployed since then. https://github.com/sourcegraph/sourcegraph/pull/60967
