### ISSUE TITLE
Support Namespace Packages In Python Code Intelligence

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#61]
Our [python language server](https://github.com/sourcegraph/python-langserver/)'s data model doesn't support [namespace packages](https://wiki.gentoo.org/wiki/Project:Python/Namespace_packages) very well. 

Supporting this properly would require a rather large refactor of the existing logic.

**Comment by sqs** [comment]
The MS Python lang server (which is probably what we will switch to using) does not seem to support namespace packages either:

- https://github.com/Microsoft/python-language-server/issues/71
- https://github.com/Microsoft/vscode-python/issues/2527
