### ISSUE TITLE
Explore page should have analytics for Sourcegraph.com or not display the section

### ISSUE THREAD

**Issue by francisschmaltz** [sourcegraph/sourcegraph#610]
Sourcegraph.com

The explore page should not have a site analytics section if site analytics are disabled (sourcegraph.com mode).

![screen shot 2018-10-30 at 3 41 15 pm](https://user-images.githubusercontent.com/11583013/47755128-6ab1ba80-dc5a-11e8-9dfc-bb57c468e5f3.png)

**Comment by dadlerj** [comment]
This is a bit of a relic from when our calcs were more inefficient. That said, calculating some user stats are still a bit expensive, and more importantly, I believe some are still not admin-protected (for the benefit of users on self hosted instances).

**Comment by dadlerj** [comment]
And after refreshing, I now see this was already addressed
