### ISSUE TITLE
(P0) Fix the Cody Analytics for Telemetry v2

### ISSUE THREAD

**Issue by aramaraju** [sourcegraph/sourcegraph#61011]
We noticed that the Cody Looker dashboard for one of our Strat customers was not showing the right usage data, causing a whole bunch of confusion and underestimating the JBs usage. The cause was narrowed down to V1 telemetry being turned off for JBs, and only v2 telemetry was being sent

**Comment by taras-yemets** [comment]
The Data Analytics team is in the process of updating queries to use Telemetry V2. The Strat team update the Cody Analytics service once the query update is finalized. [Thread](https://sourcegraph.slack.com/archives/C05405NC49H/p1710250483229959?thread_ts=1710191693.951349&cid=C05405NC49H)
cc: @aramaraju, @cbart

**Comment by aramaraju** [comment]
Acknowledged! @kelsey-brown if you have a ticket for us to follow when the work is done for updating queries, can you attach it here?

**Comment by aramaraju** [comment]
@taras-yemets can you also chime in on the target finish here given the complexities raised by Kelsey?

**Comment by kelsey-brown** [comment]
> Acknowledged! @kelsey-brown if you have a ticket for us to follow when the work is done for updating queries, can you attach it here?

[Here's](https://github.com/sourcegraph/analytics/issues/1081#issue-2184056229) my tracking ticket

**Comment by taras-yemets** [comment]
The current plan is:
1. Rebuild the Cody customer usage dashboard with telemetry v2, as outlined in https://github.com/sourcegraph/analytics/issues/1081.
2. Integrate the new Looker dashboard queries into the Cody Analytics service, maintaining both telemetry v1 and v2 queries.
3. Determine the appropriate queries for each customer instance based on the migration list to telemetry v2, as discussed in the [Slack thread](https://sourcegraph.slack.com/archives/C06358CMSRM/p1710429924209559?thread_ts=1710312223.048759&cid=C06358CMSRM).

This approach ensures that Cody Analytics supports both telemetry versions simultaneously, with a consistent UI across dashboards. Once all customer migrations to telemetry v2 are complete, we will phase out v1 support and default to v2 queries.


cc: @aramaraju @cbart

**Comment by kelsey-brown** [comment]
@taras-yemets  you can find the new dashboard [here](https://sourcegraph.looker.com/dashboards/551?External+URL=https%3A%2F%2Fsourcegraph.sourcegraph.com&Timestamp+Date=30+day&Minutes+Saved+per+Completion=2&Minutes+Saved+per+Chat=5&Minutes+Saved+per+Command+=5). It’s missing two charts:

- Average number of days each user used cody
- Frequency of usage

Because those two run on a different table that hasn’t been set up yet. I'll have those live on the dashboard tomorrow, and everything else is good to go!

There is also one new chart (Cody users by IDE) - this was requested by a couple of sourcegraph teammates for internal use, but I leave it up to you if you want to include that chart in the cody analytics service.

**Comment by kelsey-brown** [comment]
@taras-yemets the outstanding two charts (Average number of days each user used cody, Frequency of usage) have been added! Let me know if you need anything else or have any questions

**Comment by taras-yemets** [comment]
Thank you, @kelsey-brown!

The v2 dashboard is missing two more charts for completions from v1 dashboard:
- Acceptance rate by language
- Average completion latency (ms).

Cody Analytics service also has a Weighted CAR chart. It mirrors [this look](https://sourcegraph.looker.com/looks/1779?toggle=dat,vis) relying on Telemetry v1 events.

Can you please add Telemetry v2 versions of these three charts, please?

**Comment by taras-yemets** [comment]
@kelsey-brown, I can't find the average latency chart on the Telemetry v2 dashboard. Can you share a link, please?

**Comment by kelsey-brown** [comment]
Here's a new weighted CAR chart: https://sourcegraph.looker.com/looks/1899

**Comment by taras-yemets** [comment]
Telemetry v2 support added: https://github.com/sourcegraph/cody-analytics/pull/43
We've got stuck with deployment ([thread](https://sourcegraph.slack.com/archives/C05GJPTSZCZ/p1711122159911169)). I expect it to be fixed by EOD March 25.
cc: @aramaraju, @cbart
