### ISSUE TITLE
Add support for auto version numbering to `sg release [...]` operations

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#61077]
`sg release create --version=auto` 

Context: see releaseregistry, the [API has exactly the right call for that](https://github.com/sourcegraph/releaseregistry?tab=readme-ov-file#post-releasesproductnextmajor_minor)

**Comment by Chickensoupwithrice** [comment]
Initial work at https://github.com/sourcegraph/sourcegraph/pull/62106

**Comment by Chickensoupwithrice** [comment]
Merged
