### ISSUE TITLE
Promote to public the April 6th release

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#61072]

**Comment by BolajiOlajide** [comment]
![celebrate](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZ281OGN5b2dlMHAyOGdjNmIyd2JvNDdlMnZiczhqd2VtbG02cDZrcCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/IwAZ6dvvvaTtdI8SD5/giphy.gif)
