### ISSUE TITLE
Plug the release registry in all release manifests

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#61078]

**Comment by BolajiOlajide** [comment]
This is dependent on https://github.com/sourcegraph/releaseregistry/issues/22. @Chickensoupwithrice is on it.

**Comment by Chickensoupwithrice** [comment]
deploy-sourcegraph-helm has a PR https://github.com/sourcegraph/deploy-sourcegraph-helm/pull/456/files#
deploy-sourcegraph and deploy-sourcegraph-k8s still need one.

**Comment by BolajiOlajide** [comment]
Gotcha.  Once merged, I intend to cut an internal release and test the COMMIT_SHA implementation before copy-pasting the implementation to the other deployment repos. @Chickensoupwithrice

**Comment by Chickensoupwithrice** [comment]
Created pending PRs: https://github.com/sourcegraph/deploy-sourcegraph-k8s/pull/130 https://github.com/sourcegraph/deploy-sourcegraph/pull/4323

**Comment by Chickensoupwithrice** [comment]
Completed! :)
