### ISSUE TITLE
Complete the release reference documentation and land it in its final home

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#61089]
Current draft (walkthrough only) https://docs.google.com/document/d/1f3leX01N3DUK9MVJbYzesxsCXq8K69T2OIL17Ks4Qk8/edit#heading=h.tafw3e4kh9n9

**Comment by Chickensoupwithrice** [comment]
Started working on a notion page https://www.notion.so/sourcegraph/How-to-Create-a-Sourcegraph-Release-43dc0d5b608b4dad82057553af46cee2?pvs=4

**Comment by Chickensoupwithrice** [comment]
Documentation looks good in [Notion](https://www.notion.so/sourcegraph/Release-Tooling-fa1052d9bf604f37a1c0f680b67424b5#7d0bcaa1700f484cb9cf07035a0e661e) now
