### ISSUE TITLE
Improve auth UX for native integrations

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#6108]
In native integrations, it is not obvious to users that they need to navigate to the Sourcegraph URL and sign in first (they might not even know about it).

In opposite to the browser extension, there was no explicit install by the user, and there is options menu to show the sign in status.

Things we can do to improve the experience here:
- Show some in-page UI that asks to sign in, directly linking to the sign in flow (preferrably SSO through the code host) on Sourcegraph, and closing the tab afterwards.
  - This UI can be in multiple places:
    - Where the command palette is, with a Sourcegraph logo
    - In the file toolbar, since that is where users use Sourcegraph the most (to get codeintel)
- Have some automatic way to sign in with OAuth, if SSO through code host is set up?

**Comment by lguychard** [comment]
@felixfbecker seems like this should be closed now?

**Comment by felixfbecker** [comment]
Yeah, apparently we had two issues for this. There is still more work to do though - the sign in button is currently not on Gitlab, and not on PR pages.
