### ISSUE TITLE
Document the process to publish an internal release to customes without making it fully public

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#61098]

**Comment by Chickensoupwithrice** [comment]
We had to do this recently with a customer, probably a good time to document this process. @jdpleiness @DaedalusG @BolajiOlajide @craigfurman 

I would take it up, but I wasn't here for the process yesterday.

**Comment by DaedalusG** [comment]
I can do this one yea

**Comment by DaedalusG** [comment]
https://www.notion.so/sourcegraph/Custom-Image-Releases-796a10738643474d907316bb785249a2
We can probably improve on this as we develop our policy and process here further but heres an example. At the moment to my knowledge not fully public is published but not publicized. i.e. registered publicly on docker hub, but not listed in our docs or release tags on Github.
