### ISSUE TITLE
Explore page cards should break to full width on medium-viewport

### ISSUE THREAD

**Issue by francisschmaltz** [sourcegraph/sourcegraph#611]
Explore page cards currently break on small-viewport but should break on the medium-viewport size.

This prevents cards from being too close and elongated. 

![screen shot 2018-10-30 at 3 46 30 pm](https://user-images.githubusercontent.com/11583013/47755304-004d4a00-dc5b-11e8-826f-03a7ac99b3c5.png)

**Comment by sqs** [comment]
Closing because it is the same underlying issue as #612
