### ISSUE TITLE
Update Release team handbook with Helm playbooks

### ISSUE THREAD

**Issue by jdpleiness** [sourcegraph/sourcegraph#61116]
We'd like to have some basic playbooks outlined that can help other teams troubleshoot issues with our deployments, such as Helm.

These should include basic general troubleshooting, how Helm fits in as a Sourcegraph Deployment, how to contribute to our Helm charts, setup a dev environment, or file an issue.

We can keep expanding on this as we come across more issues.

**Comment by Chickensoupwithrice** [comment]
created https://github.com/sourcegraph/handbook/pull/8843
mostly just adds what we removed back in, but it's slightly updated
