### ISSUE TITLE
Sourcegraph machine images use the new release process

### ISSUE THREAD

**Issue by jdpleiness** [sourcegraph/sourcegraph#61114]
"Appliance" images available in the marketplace

**Comment by Chickensoupwithrice** [comment]
This is now ready to be "confirmed". I should've had it set up for today, but I forgot to check. 

[https://github.com/sourcegraph/sourcegraph/actions/workflows/release-amis.yml](This action) needs to be updated such that it runs on [releases](https://github.com/sourcegraph/sourcegraph/actions?query=workflow%3A%22Build+AMIs%22)

**Comment by Chickensoupwithrice** [comment]
Gets resolved by https://github.com/sourcegraph/sourcegraph/pull/62312

However, thinking about it, the AMIs depend on deploy-sourcegraph-helm to be updated, not the monorepo. I believe there's an RFC that looks to merge these back into the monorepo, but until such a time it maybe makes sense to move that action to the helm repo?

**Comment by Chickensoupwithrice** [comment]
The action runs correctly when a release is published, but it leads to a whole bunch of nonsense on the [deploy repo](https://github.com/sourcegraph/deploy/pull/85)

**Comment by Chickensoupwithrice** [comment]
The buildkite pipeline successfully completes now. It's still a race to complete deploy-sourcegraph-helm's release before the action starts building the AMIs though.
