### ISSUE TITLE
Fix issue with jaeger image when promoting a release

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#61159]
See https://buildkite.com/sourcegraph/sourcegraph/builds/265249#018e3dab-0b5c-4bd3-a8ef-919e6f0f88cc/468-469 

It seems that either we don't use that image anymore, or it's somehow missing from the build pipeline. But we build there what we have on CI, so it's more likely there's some drift in the images list.

**Comment by jhchabran** [comment]
After digging a bit I've found https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/e3158c0c2717f6604fa01639927ecb4d3e32fc5d?visible=1 which is something you introduced @BolajiOlajide  

If I search for [`sourcegraph/jaeger-agent:`](https://sourcegraph.sourcegraph.com/search?q=context:global+repo:github.com/sourcegraph/.*+sourcegraph/jaeger-agent:&patternType=keyword&sm=0) I find stuff, but not with [`sourcegraph/jaeger:`](https://sourcegraph.sourcegraph.com/search?q=context:global+repo:github.com/sourcegraph/.*+sourcegraph/jaeger:&patternType=keyword&sm=0), so ... we don't need that image at all? 

Seeing it's such a recent change, do you recall exactly why you added it back?

**Comment by BolajiOlajide** [comment]
> After digging a bit I've found [sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/e3158c0c2717f6604fa01639927ecb4d3e32fc5d?visible=1](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/e3158c0c2717f6604fa01639927ecb4d3e32fc5d?visible=1) which is something you introduced @BolajiOlajide
> 
> If I search for [`sourcegraph/jaeger-agent:`](https://sourcegraph.sourcegraph.com/search?q=context:global+repo:github.com/sourcegraph/.*+sourcegraph/jaeger-agent:&patternType=keyword&sm=0) I find stuff, but not with [`sourcegraph/jaeger:`](https://sourcegraph.sourcegraph.com/search?q=context:global+repo:github.com/sourcegraph/.*+sourcegraph/jaeger:&patternType=keyword&sm=0), so ... we don't need that image at all?
> 
> Seeing it's such a recent change, do you recall exactly why you added it back?

I added the image because it can be found in the deployment repos and it hadn't been updated in a while via `sg ops update-images`

**Comment by jhchabran** [comment]
@BolajiOlajide actually, as I pointed out in my original comment, I can find the all-in-one, but not the just `jaeger` one. Am I missing something?

**Comment by jhchabran** [comment]
(we don't have a `jaeger` one on dockerhub either 
![image](https://github.com/sourcegraph/sourcegraph/assets/10151/442579a6-1532-4b87-ac4f-ebe766da27ad)
) 

I'm asking because I wonder if that's possible we abuse the images list for something else

**Comment by BolajiOlajide** [comment]
Okay. Seems like I've fixed my internet issues so responses should be better now.

I'm fairly certain I've seen the jaeger image on docker hub before, I'm happy to remove it since it doesn't exist again but this is weird to me.

**Comment by BolajiOlajide** [comment]
Hey @jhchabran 

Seems this was an oversight on my part. I've tagged you on a PR to correct this.
