### ISSUE TITLE
Explore page cards should break at md and not have left padding/margin on small/medium viewports

### ISSUE THREAD

**Issue by francisschmaltz** [sourcegraph/sourcegraph#612]
In the small (and medium https://github.com/sourcegraph/sourcegraph/issues/611 ) viewport, cards should not have left padding/margin to prevent cards from being shifted left and should have 100% width.

![screen shot 2018-10-30 at 3 48 54 pm](https://user-images.githubusercontent.com/11583013/47755403-4f937a80-dc5b-11e8-8793-614111fec9d9.png)

**Comment by sqs** [comment]
I’ll see what tweaks can be made. Unfortunately bootstrap card decks are not responsive yet. Maybe they are in the newer bootstrap version.

**Comment by sqs** [comment]
I made it use the Bootstrap grid instead of card-deck so it can be responsive. This approach means we lose equal-height across the cards, unfortunately.

![screenshot from 2018-10-31 01-13-37](https://user-images.githubusercontent.com/1976/47774409-349c2700-dcaa-11e8-908c-689d6d233bf9.png)

**Comment by francisschmaltz** [comment]
Seems like there should be a better solution to this problem. Both of these look rough
