### ISSUE TITLE
Prepare to remove "keyword search" toggle

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#61226]
Tasks

- [X] Honor default search pattern type ([https://github.com/sourcegraph/sourcegraph/pull/62066](https://github.com/sourcegraph/sourcegraph/pull/62066))
- [X] Leave patternType in query if not keyword or regex ([https://github.com/sourcegraph/sourcegraph/pull/63326](https://github.com/sourcegraph/sourcegraph/pull/63326))
- [X] Check our current event telemetry. (see comment below for analysis)
- [ ] Ensure that `search.defaultPatternType` can be set to fully disable keyword search ([https://github.com/sourcegraph/sourcegraph/pull/63410](https://github.com/sourcegraph/sourcegraph/pull/63410))

/cc @sourcegraph/search-platform

**Comment by stefanhengl** [comment]
Quick note so that we don't forget: Based on a recent feedback we received, we should make sure that `search.DefaultPatternType` can override keyword search. The way we implement it right now that's not the case.

**Comment by stefanhengl** [comment]
>  When you click the regex button (.*) we switch to patternType:regex.

This seems to work already. Are there some edge cases where we don't do this?

**Comment by keegancsmith** [comment]
> Quick note so that we don't forget: Based on a recent feedback we received, we should make sure that `search.DefaultPatternType` can override keyword search. The way we implement it right now that's not the case.

Added to task list

> > When you click the regex button (.*) we switch to patternType:regex.
> 
> This seems to work already. Are there some edge cases where we don't do this?

Right now in the UX it disables keyword search. I suppose this is more part of ensuring when we remove the toggle things still behave correctly.
