### ISSUE TITLE
Duplicate pre-resolved paths in TypeScript ref panel

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#61245]
At https://sourcegraph.com/github.com/sourcegraph/cody@032645f0e65c3d7958ff9d8fb0f8b78c56091062/-/blob/vscode/src/chat/chat-view/SimpleChatPanelProvider.ts?L622:19-622:34#tab=references I see the same file listed as a reference using multiple different paths by which it is reachable (with unresolved `../`s).

Note the multiple `SimpleChatPanelProvider.ts` entries:

<img width="1198" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/1976/fda9ffea-1d3b-4655-afcb-8e03ce595bfa">

(This appears to be a different issue than https://github.com/sourcegraph/sourcegraph/issues/36634.)

**Comment by kritzcreek** [comment]
I think this is recorded here https://github.com/sourcegraph/scip-typescript/issues/330

**Comment by sqs** [comment]
@kritzcreek Yes, that's the same. Feel free to close this as a dupe if you want.
