### ISSUE TITLE
Distribute code ownership spreadsheet to engineering & management

### ISSUE THREAD

**Issue by Strum355** [sourcegraph/sourcegraph#61243]
In order to assign ownership tags to >70% of test targets, we need to know _who_ owns what properly. Submit a spreadsheet to Erika (+ engineering teams) in order to get people to input ownership

**Comment by jhchabran** [comment]
@Strum355 would be nice to share then link to the spreadsheet here too :P

**Comment by Strum355** [comment]
https://docs.google.com/spreadsheets/d/1Vu-Nk0dSCDJb_1cffbd29sr3NQkhJAmVAU9x_M7TnTU/
