### ISSUE TITLE
Selecting autocompletions with arrow key severly broken

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#6126]
Pushing <kbd>↓</kbd> to select an autocompletion doesn't work.
Hitting enter instead sets a search query to `repo:^https:$` and the URL to https://sourcegraph.com/https://about.sourcegraph.com (which shows "repo not found")

![2019-10-21 13 44 08](https://user-images.githubusercontent.com/10532611/67241794-f80c9280-f408-11e9-979c-de2032bd1d0d.gif)

This is on sourcegraph.com, don't know if it reproduces in 3.9, but not unlikely.
It happens in both the global search bar and the directory page search bar.

**Comment by sqs** [comment]
@hadrian-git @attfarhan If this is in 3.9, we should get a 3.9.x patch release out ASAP with a fix.
