### ISSUE TITLE
search: implement more file: based suggestions

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#61283]
With the side-panel UX in 5.3.0 our suggested filters are much more prominent. Right now they feel very go centric. We should expand what we suggest. This issue tracks ideas and implementation of those.

- [X] more suggestions for `file:` which aren't go specific?
- [ ] suggestions for `file:` based on subdirs?

Part of #61225

/cc @sourcegraph/search-platform

**Comment by camdencheek** [comment]
Related: we should show user-specified snippets https://github.com/sourcegraph/sourcegraph/issues/61327
