### ISSUE TITLE
Update existing licenses/subscriptions to allow new Claude models

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#61291]
Run sql to add claude-3 models to all subscriptions.

Additionally cloud tooling automatically adds models when configured for use, but currently does not trigger a refresh of the limits.

**Comment by arafatkatze** [comment]
Solved in [this thread](https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1711632452407259)

<img width="674" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/11155207/22dc413c-f5c4-48e5-a3da-710bc46fc694">
