### ISSUE TITLE
Clicking on a filename on the negative side of a diff result takes you to the file on the positive side's commit

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#613]
- Visit https://sourcegraph.com/search?q=r%3Asourcegraph%24+typescript+type%3Adiff
- Click on the **filename** of a file that got deleted

![image](https://user-images.githubusercontent.com/1387653/47755391-46a2a900-dc5b-11e8-9d54-8a7b90ce4bed.png)

- Notice that the file does not exist at that revision

![image](https://user-images.githubusercontent.com/1387653/47755406-50c4a780-dc5b-11e8-9058-2d2dea7e101b.png)

If you click on a **result**, it works. The hash ends with `~` which is probably short for `~1` in git revision selection syntax, which selects the first parent commit where the file exists.

@vanesa Do you happen to know if each of the results should also have the tilde `~` in them?

**Comment by vanesa** [comment]
@chrismwendt You mean that each of the matching deleted files should have a tilde at the end of the hash? Yes that would work.

**Comment by chrismwendt** [comment]
Why was the tilde added in the first place? I've never seen that on any code hosts, and not all tools support that syntax. Are there any downsides to resolving it to a plain 40 character hash?

**Comment by sqs** [comment]
> Why was the tilde added in the first place?

It was easier to do that than to add in another call to ResolveRev.

> Are there any downsides to resolving it to a plain 40 character hash?

Nope, other than the extra code added. (Resolving it to the SHA seems like the right thing to do anyway.)

**Comment by nicksnyder** [comment]
cc @attfarhan for awareness since you are touching this code I think, but this is not a priority

**Comment by attfarhan** [comment]
Diff search results will just take you to the commit page once my changes are merged.
