### ISSUE TITLE
Markdown Rendering Issue with Blockquotes and Numbered Lists

### ISSUE THREAD

**Issue by gabtorre** [sourcegraph/sourcegraph#61313]
- **Sourcegraph version:** 5.3

When rendering Markdown, blockquotes inserted within numbered lists break the continuity of the list. Instead of continuing the sequence, the list restarts or breaks following a blockquote.

#### Steps to reproduce:

Create a Markdown document.
Insert a numbered list with at least two items.
Include a blockquote (using > syntax) after the first item and before the second.
Render the Markdown to observe the issue.

#### Expected behavior:

![Screenshot 2024-03-20 at 4 03 58 PM](https://github.com/sourcegraph/sourcegraph/assets/69164745/26833db5-6a7f-4cfd-9d9b-8b746f61e155)

#### Actual behavior:
![Screenshot 2024-03-20 at 4 04 23 PM](https://github.com/sourcegraph/sourcegraph/assets/69164745/b77e4d96-b0bc-4700-bff3-e0757eee58f0)

If you would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are no [SLAs](https://sourcegraph.com/support/) on issues like there are for support requests).

**Comment by raznar** [comment]
Affected by [customer 578](https://github.com/sourcegraph/accounts/issues/578)
