### ISSUE TITLE
Add admin warning message about retired anthropic model names

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/sourcegraph#61339]
The Anthropic messages API does not support model names like `claude-2` or `claude-instant-1` where only the major version is specified. 

Currently the backend [replaces](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@0ce98cd3861336716fa842f3f865099e712c312d/-/blob/internal/completions/client/anthropic/anthropic.go?L230:6&popover=pinned) these with specific versions.

Add an warning message based on the site config if any of the chat/fastChat/completions models are retired versions, to alert the admin that these values are no longer should be used and instead replaced with a specific model identifier.

**Comment by arafatkatze** [comment]
solved by #61379
