### ISSUE TITLE
Cody Web: bring back the old deleted codebase of `code-shared` and `cody-ui`

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#61368]
At the beginning cody web (and it still depends on it) on `cody-ui` and `cody-shared` packages, later these packages were moved to the cody repo. But cody has evolved since then and now it doesn't have dependencies on these packages. 

The only reason why Cody-web is still working is because these packages live only npm as published code, in this issue we should bring these packages back to the main repo that we can change logic there freely 

Also part of this we should write a small RFC as a conclusion for the further work on cody-web

**Comment by peterguy** [comment]
[Cody Web RFC](https://docs.google.com/document/d/1we2H0W7hszfnqY17N6l9biFZTGTa6dtSMvEpng0lHJA/edit#heading=h.trqab8y0kufp)
