### ISSUE TITLE
LSIF: retention policy

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#6148]
Currently, LSIF uploads will accumulate until lsif-server runs out of disk space.

A retention policy would prevent that from becoming a problem. Any other ideas?

Retention policy questions:

- What's the dimension? Time, number of uploads per repo, number of commits, total size, etc.
- How is this configured? Probably env var
- Do the in-memory caches need to get cleared?
- What kind of recommendations will we put in our docs?

**Comment by efritz** [comment]
[RFC 55](https://docs.google.com/document/d/1q7e0Rl9O9Weu33JDlcCz-3N1VGnnfI1zINppRNT60bQ).
