### ISSUE TITLE
dev: cmd/frontend/db/schema.md has a huge diff even though I didn't change anything about the schema

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#615]
#### Steps to reproduce:

1. Run `./dev/generate.sh` without changing anything about the database schema
2. See a huge diff in cmd/frontend/db/schema.md

See https://github.com/sourcegraph/sourcegraph/pull/603/files#diff-b6f9e2ecf0225776b1ba3bb45a3acd97 - there are no database changes in this PR, however cmd/frontend/db/schema.md has a huge diff

**Comment by slimsag** [comment]
@vanesa ran into the same problem earlier

**Comment by sqs** [comment]
You need to downgrade to postgresql 9’s psql. We should fix this for real but that is the workaround.
