### ISSUE TITLE
`lang:` filter support for Mojo language

### ISSUE THREAD

**Issue by carlca** [sourcegraph/sourcegraph#61500]
#### Feature request description

I would like to have the site search facility of Sourcegraph be extended so that `lang: Mojo` works.

#### Is your feature request related to a problem? If so, please describe.

It's difficult to narrow searches down by other means, especially since the term `mojo` crops up in other contexts, eg. Mojolicious. 

#### Additional context

`Github` themselves have, in the last few days, started to recognise `Mojo` as a distinct language, so there's no excuse now 😉

**Comment by varungandhi-src** [comment]
We rely on the go-enry library for language detection. Once that updates to Linguist 7.29.0 that contains the entry for Mojo https://github.com/go-enry/go-enry/pull/178, we can update the dependency.
