### ISSUE TITLE
Bitbucket Cloud repo syncing should allow hyphens in team names

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#6154]
- **Sourcegraph version:** 3.8.0
- **Platform information:** K8s

#### Steps to reproduce:

Reported by: 
* https://app.hubspot.com/contacts/2762526/company/557475593

Looks like we require alphanumeric team IDs in our Bitbucket Cloud/bitbucket.org external service config: https://docs.sourcegraph.com/admin/external_service/bitbucket_cloud#teams

Interestingly, the [Bitbucket docs](https://confluence.atlassian.com/bitbucket/create-and-administer-your-team-665225537.html) don't make this clear, but per our contact above, we should allow hyphens here as well.

**Comment by unknwon** [comment]
> Looks like we require alphanumeric team IDs in our Bitbucket Cloud/bitbucket.com external service config:

I think Bitbucket Server does not have the concept of "team", only Bitbucket Cloud (https://bitbucket.org) has.

But I will send a PR.

**Comment by unknwon** [comment]
PR #6181 is merged.

**Comment by keegancsmith** [comment]
@unknwon can we close this?
