### ISSUE TITLE
Refactor: Add storage for appliance state

### ISSUE THREAD

**Issue by jdpleiness** [sourcegraph/sourcegraph#61561]
As CRDs are no longer being used, a different method for storing the state of a sourcegraph deployment must be used. Options so far are configmap or possibly a PVC to serialize and store data in a similar way a CRD would.

**Comment by craigfurman** [comment]
@jdpleiness do we still need this issue? If we discover that we need any storage beyond putting annotations on the main ConfigMap, we can implement it then, right? If we do, using k8s resources (e.g. more configmaps, and/or Secrets), avoids bringing in more complex dependencies (persistent volumes to keep sqlite files on, or even possibly external DBs)
