### ISSUE TITLE
Svelte: Implement repo popover

### ISSUE THREAD

**Issue by taiyab** [sourcegraph/sourcegraph#61654]
This is what the repo popover looks like on the file page (when mousing over the repo name in the header).

<img width="593" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/5337876/b9049390-82c2-4bf6-8348-d2d76479b3a0">

There is also a version with a header too:
<img width="394" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/5337876/5c2eb1cc-35c0-4529-bbe5-d811a56c3227">

However, that's not used in this scenario (but will be in others).

Figma: https://www.figma.com/file/EPgl0qVbqGSumvf52brhda/Code-Search?type=design&node-id=2709%3A65462&mode=design&t=rs6WkWU36T6PfNDq-1

**Comment by taiyab** [comment]
@jasonhawkharris  I'm curious to understand why you think that.

For typical customers, they'll be seeing the icon/logo of whatever org owns the repos they're navigating in. It's only a duplicative Sourcegraph icon for us because we own the platform too :D and the example in the designs is `sourcegraph/sourcegraph`.

I think it's super useful to have it there, especially when navigating in unfamiliar places (dependencies/libraries, etc.)

The code host logo, you could still get on mouseover (which I have in one of the examples above, but should probably get into this version too).

**Comment by jasonhawkharris** [comment]
@taiyab Ah, I see. That explanation clears things up for me. I agree with your assessment. Thanks for explaining it!

I also have another question. Imagine a scenario where:

1. The user selects a search result, which leads them to the blob view for that result. At this point, I assume the "RepoMenu" (tentatively named) will appear in the navigation bar.
2. The user decides to switch to another repository and uses a keybind to do so.

In this scenario, my questions are:

1. What happens immediately after executing the command? 
2. Which page or view will we serve them when switching repos? Will it be the README for the repository, or something else?
3. How do they choose which repository to switch to?

All of these can wait until you get back, but I think we're a little underspecified in regards to the full functionality of this feature. For now, my plan is to focus on the MVP while you're gone, merge it, and address these questions in a subsequent PR.
