### ISSUE TITLE
Click the icon to find the page

### ISSUE THREAD

**Issue by 425183525** [sourcegraph/sourcegraph#6165]
Hello, I installed this plugin in the Google browser.Then click on the icon on GitHub to find the page.What is the reason?thank you
![image](https://user-images.githubusercontent.com/39403315/67399151-5b9be900-f5de-11e9-9142-ab1e97bfbb09.png)
![image](https://user-images.githubusercontent.com/39403315/67399170-635b8d80-f5de-11e9-81e6-0b729f10affd.png)

**Comment by dadlerj** [comment]
Hi @425183525, what repository was this? That link should take you the repository on Sourcegraph.
