### ISSUE TITLE
Svelte: Implement file header

### ISSUE THREAD

**Issue by taiyab** [sourcegraph/sourcegraph#61652]
The file header is now pretty stable in the designs.

<img width="1143" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/5337876/ffc932c3-8dd9-44aa-a2aa-66525c21c475">

The workflow actions toolbar adjusts according to available space or mode, it can also wrap. Cody Explain won't be available as an action item until later.

<img width="581" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/5337876/242fbad9-53df-4bff-a5f5-fba66dd1366b">

Figma:
- https://www.figma.com/file/EPgl0qVbqGSumvf52brhda/Code-Search?type=design&node-id=1947%3A37160&mode=design&t=rs6WkWU36T6PfNDq-1
- https://www.figma.com/file/EPgl0qVbqGSumvf52brhda/Code-Search?type=design&node-id=2591%3A75731&mode=design&t=rs6WkWU36T6PfNDq-1
- https://www.figma.com/file/EPgl0qVbqGSumvf52brhda/Code-Search?type=design&node-id=2730%3A226742&mode=design&t=rs6WkWU36T6PfNDq-1

**Comment by fkling** [comment]
For the initial version I suggest to

- [ ] Adjust styles (font, spacing, colors)
- [ ] Add open in codehost button (as an example for a permanent button)
- [ ] Add "overflow" menu

That leaves for the future:

- Repo name/icon in header. I think that's mostly needed when we have a second panel and might be more distinguishable when we have icons.
- Remaining file actions. We have separate issues for them.

Don't do for now:

- "Cody Explain" button. We don't have the cody sidebar in the prototype so clicking the button would have to redirect to the React app which is probably not a great experience. But we can always revisit this.
