### ISSUE TITLE
Re-enable e2e tests

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#6169]
Re-enable e2e tests in a way that doesn't block merges. One idea:
- Run them continuously, instead of on merge or branch push. Retry on failure to reduce the amount of flakiness.

**Comment by nicksnyder** [comment]
Can the first action to be to figure out why they are flaky in the first place? The ideal outcome is that we re-enable them on master and PRs for every commit and they are 100% reliable, right?

**Comment by unknwon** [comment]
I've spent some time on Buildkite's developer documentation and here is my plan to detect flaky tests and report automatically:
- [ ] Configure **Webhook Notification** for **sourcegraph** pipeline which sends events for `job.finished`.
- [ ] Set up a simple server that receives webhooks and discards any jobs that are not e2e (i.e. `:chromium:`)
- [ ] Report the job with `"state:": "failed"` to _somewhere_, and keep a record of it (e.g. build ID). At this point, the e2e test could have real failure.
- [ ] Report the job with `"state:": "succeed"` that has the same build ID but previously failed, this is most likely a flaky test.
 
This is of course a first baby step towards actually looking at those flaky tests and fix them.

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.10 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by unknwon** [comment]
Update: automated flaky reporting is now running, you can join #flaky-e2e-tests to see the reports (none yet). I'm going to start working on fixing them (gradually).

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.11 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by beyang** [comment]
Closing this, due to the fact that these are in a separate pipeline now.
