### ISSUE TITLE
Enterprise Context Improvements [Converted to "Enterprise Context Improvements" project]

### ISSUE THREAD

**Issue by mmanela** [sourcegraph/sourcegraph#61703]
This issue represents our initial round of improvements to remote keyword context, which is the main context source for Cody Enterprise. We'll also include local context (symf) and embeddings in our research.

Success criteria:

* Representative context quality evals (that everyone can run)
* Progress against those evals -- scores improve!
* Hardening: no obvious bugs or shortcomings

/cc @sourcegraph/search-platform

```[tasklist]
### Tasks
- [ ] https://github.com/sourcegraph/sourcegraph/issues/61571
- [ ] https://github.com/sourcegraph/sourcegraph/issues/62582
- [ ] https://github.com/sourcegraph/sourcegraph/issues/61745
- [ ] https://github.com/sourcegraph/sourcegraph/issues/61743
- [ ] https://github.com/sourcegraph/sourcegraph/issues/61744
```

**Comment by jtibshirani** [comment]
Converted to this linear project: https://linear.app/sourcegraph/project/enterprise-context-improvements-f921355713ce/overview
