### ISSUE TITLE
Ship non-bazel CI data to BigQuery

### ISSUE THREAD

**Issue by Strum355** [sourcegraph/sourcegraph#61716]
Once the async pipeline is being fired off, we can start to ship data to BigQuery. Loosely, theres two types of data we need to look at: Bazel data and everything else :^)

In the async pipeline, we set environment variables such as `DEVX_TRIGGERED_FROM_BUILD_ID` (example here: https://buildkite.com/sourcegraph/devx-build-metrics/builds/264#018ec294-353b-4b30-b314-656f0e0300d9). These values can be used with the buildkite graphql API in order to export information such as per-step timings, build/job start & end times, wall clock time, step status codes etc.

Where the code lives fort his is up to the implementer. We're split between the monorepo (build-tracker lives there) and devx-service (alfred lives there)

**Comment by jamesmcnamara** [comment]
Alright so yes I still have some questions:
1. What data do we want to ship to big query? Do we have an existing table / database of relevant info that we want to populate? If we don't already have a bigquery collection, what is the specific question we want to be able to  answer with the data collected in this ticket?
2. When do we want to collect this information? I remember you mentioning something about having buildkite kicking some external API when it's done, is that the plan? Or is it cron job sort of thing? Or do we start with just a CLI that takes a commit hash and reports stats about it?

**Comment by Strum355** [comment]
>     1. What data do we want to ship to big query? Do we have an existing table / database of relevant info that we want to populate? If we don't already have a bigquery collection, what is the specific question we want to be able to  answer with the data collected in this ticket?

Non-exhaustive list of data we want to collect include:
- build times + timestamps (wall clock + total compute time[1]), url/number, status code, etc
- job times + timestamps, including  (where a build is comprised of >=1 jobs)
- job status codes + retry counts
- commit details (author, branch, revhash etc)
- agent information per job (hostname, version, queue, etc)

No existing database of this I believe, this is all new :slightly_smiling_face: 

Questions we want to be able to ask include:
- How many times did e.g. Buildifier step need to be restarted (job reliability)
  - Build times + reliability trends
- Combined with (future) agent-level boot/shutdown info, can we explain infra cost (X step taking longer, stray VMs, suboptimal scaling)

>     2. When do we want to collect this information? I remember you mentioning something about having buildkite kicking some external API when it's done, is that the plan? Or is it cron job sort of thing? Or do we start with just a CLI that takes a commit hash and reports stats about it?

We fire off an async pipeline over at https://buildkite.com/sourcegraph/devx-build-metrics for every finished build. You can take a peek there to see what info is available to steps in the pipeline from existing
