### ISSUE TITLE
structural search on S2 doesn't honor lang filter

### ISSUE THREAD

**Issue by stefanhengl** [sourcegraph/sourcegraph#61714]
The following query returns results from various languages on S2

```
r:^github\.com/sourcegraph/sourcegraph$ lang:yaml if ... else ... patternType:structural
```

However, locally and on .com the language filter works

- S2: https://sourcegraph.sourcegraph.com/search?q=context:global+r:%5Egithub%5C.com/sourcegraph/sourcegraph%24+lang:yaml+if+...+else+...&patternType=structural&sm=0
- .com: https://sourcegraph.com/search?q=context:global+r:%5Egithub%5C.com/sourcegraph/sourcegraph%24+lang:yaml+if+...+else+...&patternType=structural&sm=0

/cc @sourcegraph/search-platform

**Comment by jtibshirani** [comment]
S2 has the `search-content-based-lang-detection` feature flag enabled, whereas it's not enabled on dot com and locally. So I likely broke this when working on https://github.com/sourcegraph/sourcegraph/issues/60341.
