### ISSUE TITLE
`sg setup` cannot clone `sourcegraph/dev-private` because it doesn't exist.

### ISSUE THREAD

**Issue by krishnakeshan** [sourcegraph/sourcegraph#61749]
* **Sourcegraph Version: N/A:**
* **OS: MacOS Ventura 13.6.1:**

Note: I'm not a Sourcegraph employee. So maybe `dev-private` (like the name suggests) is a private repo, please let me know if that's the case and how I can proceed 🙌

#### Steps to reproduce:

1. Follow instructions from [Quickstart Guide](https://sourcegraph.com/docs/dev/setup/quickstart)
2. Run `sg setup` inside `sourcegraph` local clone.

#### Expected behavior:

Clone the `dev-private` repository if needed. It looks like removing `dev-private` was discussed in [58883](https://github.com/sourcegraph/sourcegraph/issues/58883) and [29640](https://github.com/sourcegraph/sourcegraph/issues/29640) but the `sg` binary installed by running `curl --proto '=https' --tlsv1.2 -sSLf https://install.sg.dev | sh` still checks for it.

#### Actual behavior:

An `ERROR: Repository not found` gets returned and the `Clone repositories` check in `sg setup` fails. Blocker!

![Screenshot 2024-04-10 at 1 43 26 PM](https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/39100013-3511-472d-aec5-845d351a5f8a/6b77bd9d-94bb-4a61-b804-064c68a43de5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy8zOTEwMDAxMy0zNTExLTQ3MmQtYWVjNS04NDVkMzUxYTVmOGEvNmI3N2JkOWQtOTRiYi00YTYxLWI4MDQtMDY0YzY4YTQzZGU1IiwiaWF0IjoxNzEyODEwMDM1LCJleHAiOjMzMjgzMzcwMDM1fQ.UKyw71o6c-Qw8pmYWxj-EuFs58B7_NjdoN0_rGdZNvk "=1012x")

**Comment by krishnakeshan** [comment]
[58818](https://github.com/sourcegraph/sourcegraph/issues/58818) this is the same issue and as it mentions, `sg` is not maintained anymore for external contributors. I would like to make this specific fix in the `sg` tool to make it easier for external contributors to work on this project. Can I work on this?

**Comment by jhchabran** [comment]
@krishnakeshan Yes, `sourcegraph/dev-private` is a private repository containing a few pieces of data required to run the application locally. As the repo is public but not OSS anymore, it didn't make sense for us to keep maintaining that path, so we removed it.  

The quickstart guide you linked was out of date, as we forgot to remove that section when we dropped the original choice during `sg setup` that would allow you to skip that step. 

With all of that being said, you can still contribute if you desire so, you can see what steps are required in these three files (one being common to Ubuntu and Mac, the two others being specific to each platform). 

- Common to both platforms: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@af10bb83bf0df5a60ae1aa36e314b4b724e26aae/-/blob/dev/sg/dependencies/shared.go
- Mac specific: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@af10bb83bf0df5a60ae1aa36e314b4b724e26aae/-/blob/dev/sg/dependencies/mac.go
- Ubuntu specific: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@af10bb83bf0df5a60ae1aa36e314b4b724e26aae/-/blob/dev/sg/dependencies/ubuntu.go

While you might meet some issues with various `sg` commands without having `dev-private`, you'll most likely be able to run unit tests and build various components with Bazel. 

If you're looking to achieve something in particular, you can reach me on our Discord community server, @jdorfman and I may be able to help you 🙏 

PS: I'll close the issue, as this is very much a won't fix, but feel free to ping me again here if you prefer that to Discord.

**Comment by krishnakeshan** [comment]
@jhchabran got it. I was just looking to make contributions to the `sg` tool. I'll look into the files you mentioned and see what I can do. Thank you for your response!
