### ISSUE TITLE
Sveltekit: Graphql fragment naming convention

### ISSUE THREAD

**Issue by jasonhawkharris** [sourcegraph/sourcegraph#61792]
https://github.com/sourcegraph/sourcegraph/pull/61746#discussion_r1560656572

**Comment by camdencheek** [comment]
Proposal: use the form `<ComponentName><GraphQLObjectType>`. e.g., for the linked comment, we would use `RepoPopoverRepository`. That way, the generated type name for the fragment is a descriptive name that specifies "this is a subset of repository fields that are needed for the RepoPopover component"
