### ISSUE TITLE
Some about page footer links 404

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#619]
Note the new sourcegraph.com/start homepage links are fine, but since we use a different footer nav component there, the old links under "Features" are broken:

![image](https://user-images.githubusercontent.com/5589410/47804164-5f5d9e00-dcf1-11e8-8cb4-1a3e62545805.png)

**Comment by attfarhan** [comment]
Fixed with https://github.com/sourcegraph/about/commit/be01fdfd4e69f7caf2432202eb5c03eb1b48405d.

**Comment by attfarhan** [comment]
@Francis clicking those links from about.sourcegraph.com don't seem to open the modals as intended, though.

**Comment by francisschmaltz** [comment]
We should revert this change. It’ll be implimented soon

**Comment by attfarhan** [comment]
Revert which change?

**Comment by francisschmaltz** [comment]
@attfarhan we talked offline. I was confused. Thanks for correcting the issue!
