### ISSUE TITLE
Re-enable Firefox browser extension e2e tests in CI 

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#6191]
See https://github.com/sourcegraph/sourcegraph/pull/5928

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.10 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.11 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by lguychard** [comment]
@felixfbecker did this.
