### ISSUE TITLE
Support internal repos on GHE better without having to individually add orgs

### ISSUE THREAD

**Issue by pjlast** [sourcegraph/sourcegraph#61924]
There are 3 ways to add `internal` repos to an instance:

- Add the repo by name
- Use `"repositoryQuery": ["public"]`
- Use `"repositoryQuery": ["org:org-name is:internal"]`

However, on instances with many, fluctuating repos and fluctuating orgs, none of these are feasible.

`"public"` uses GitHub's public repos endpoint, which does not return `visibility` or `topics` as part of the JSON result, making it impossible to tell which repos are actually internal and yielding inconsistent search results for repos with topics.

And having to add a new repo or a new org to code host connections every time is extremely tedious.

What we should be able to do instead is add a new `"internal"` option to the `repositoryQuery` special cases that iterates over the users orgs, and lists all the repos for each org using `visibility=internal`

**Comment by eseliger** [comment]
https://github.com/sourcegraph/accounts/issues/569
