### ISSUE TITLE
Svelte: Improve repository revision picker UI

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#61922]
Original issue https://github.com/sourcegraph/sourcegraph/issues/61622

In the first implementation PR, we got the working first base version of picker https://github.com/sourcegraph/sourcegraph/pull/61817, but we left a few important things that we should have there such as

- keyboard navigation between tabs (see original designs)
- Revision item sub tooltip with revision description and history entry 
- Highlight matching parts in the suggestions

**Comment by taiyab** [comment]
We also might want to add this: https://sourcegraph.slack.com/archives/C03CSAER9LK/p1715076628502959?thread_ts=1715074711.049729&cid=C03CSAER9LK

We could do it all in the input and change the label to, e.g.: "Search by branch name or author", etc. etc.
