### ISSUE TITLE
Some forked repositories appear in searches when using the "fork:no" filter

### ISSUE THREAD

**Issue by wrporter** [sourcegraph/sourcegraph#6193]
- **Sourcegraph version:** 3.9.0
- **Platform information:** Docker 19.03.3

#### Steps to reproduce:

1. Setup GitLab repositories
2. Create forks
3. Search on Sourcegraph using the "fork:no" filter

#### Expected behavior:
All forks are filtered out.

#### Actual behavior:
Only some forks are filtered.

Attached is my Sourcegraph configuration.
[sourcegraph.txt](https://github.com/sourcegraph/sourcegraph/files/3768065/sourcegraph.txt)

**Comment by dadlerj** [comment]
Thanks @wrporter! Can you try running the exact same search with (1) `index:no` and (2)`index:only`, and see if you get the same results? That'll help us understand if this is an issue isolated to our indexed search or not.

**Comment by wrporter** [comment]
I attempted this again this morning and forks are properly filtered out. Not sure if they just were not indexed yet at the time of writing this issue. If I run into this again, I'll reopen the ticket with more details. Thank you!
