### ISSUE TITLE
Encoded links are not handled properly on the Sourcegraph Frontend

### ISSUE THREAD

**Issue by kalanchan** [sourcegraph/sourcegraph#61944]
- **Sourcegraph version:** latest
- **Platform information:** web browser

#### Steps to reproduce:

When using VS Code, encoded URLs that link back to context files found on Sourcegraph do not open properly in the Sourcegraph instance. Specifically, if an URL in VS Code contains encoded characters, the Sourcegraph UI fails to properly decode the URL when trying to display the linked file or subdirectory. This is preventing enterprise users from easily navigating to the context directly in Sourcegraph when clicking these links. I also filed a [bug in VS Code](https://github.com/sourcegraph/cody/issues/3766) to capture the issue, but I want to say it’s _probably_ not a client issue.

ex - https://sourcegraph.sourcegraph.com/github.com/sourcegraph/cody%40c69aaf7/-/blob/README.md doesn’t work
ex - https://sourcegraph.sourcegraph.com/github.com/sourcegraph/cody@c69aaf7/-/blob/README.md works

#### Expected behavior:
Encoded links to files or subdirectories should be handled properly on the Sourcegraph UI

#### Actual behavior:
Encoded links returns repo not found

If you would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are no [SLAs](https://sourcegraph.com/support/) on issues like there are for support requests).

**Comment by keegancsmith** [comment]
I think this is behaving as expected due to repo names with @ in them needing those to be encoded. See my comment here https://github.com/sourcegraph/cody/issues/3766#issuecomment-2063930635

Note: I didn't dig into the history to confirm my suspicion around @ in repo names.
