### ISSUE TITLE
GraphQL API calls return HTTP status code 200 on application errors

### ISSUE THREAD

**Issue by uwedeportivo** [sourcegraph/sourcegraph#6199]
This is a customer suggestion. When we have GraphQL application error payloads we should not return HTTP 200 but use appropriate HTTP error status codes.

Example from customer:

<redacted>

If we agree on this approach then two code changes are needed:

[relayHandler](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@master/-/blob/cmd/frontend/internal/httpapi/graphql.go#L12:14)

We use github.com/graph-gophers/graphql-go/relay. If the payload has application errors (for example from [SearchResolver](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@master/-/blob/cmd/frontend/graphqlbackend/search_results.go#L456:31) )we need to somehow change the relay handler to set http status code 500. It's a third-party lib but it's doable with some hacking.

We need to coordinate with the web team to show the same informative errors when presented with 500 http response as we do with 200 + errror payload. It needs to unwrap the payload and surface the application error.

**Comment by felixfbecker** [comment]
This is not conventional for GraphQL. In GraphQL, errors are _within_ the response and on a field-by-field basis, i.e. some fields may have errored while others succeeded. This makes sense if you consider that GraphQL allows you to fetch the data needed for the entire page in one request - you could not fail the entire request if one thing failed. So it wouldn't make sense to communicate a failure on the request depending on field failure. We only return status code errors in cases of request-level errors, like missing authentication.

Changing this would also break basically every API client interacting with the Sourcegraph API (including the CLI, web app, browser extension and native integrations).

**Comment by slimsag** [comment]
I agree with Felix. What should be done to address the customer issue, though, is improving our Prometheus metrics to give visibility into GraphQL field errors. We currently have a histogram for GraphQL field durations, we probably just need to add a secondary counter for # of errors.

https://sourcegraph.com/github.com/sourcegraph/sourcegraph@a091ba57f57f9341fca98492f056a18d7673fae1/-/blob/cmd/frontend/graphqlbackend/graphqlbackend.go#L22-28

**Comment by felixfbecker** [comment]
I am going to close this issue since there seems to be consensus that this is undesirable - please open a new issue for improving observability of errors :)
