### ISSUE TITLE
Case sensitive Regex return empty, incorrectly, IF using lang: operator

### ISSUE THREAD

**Issue by peter-kehl** [sourcegraph/sourcegraph#62127]
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:** current Firefox (124.0.2, Manjaro x64 Linux)

#### Steps to reproduce:
Run https://sourcegraph.com/search?q=context:global+type:file+lang:rust+/%28struct%7Cenum%7Ctrait%7Ctype%29+%2BC%5BA-Z%5D/&patternType=keyword&case=yes&sm=0 which is (supposed to be) **case-sensitive** for query
`context:global type:file lang:rust /(struct|enum|trait|type) +C[A-Z]/`
![image](https://github.com/sourcegraph/sourcegraph/assets/4270240/0fa91bce-22d7-41ca-8dd3-29e4007d3d81)

The same = empty result is returned if I don't use the sensitivity button, but if I type the above query and I append `case:yes` to the query - then Sourcegraph Search redirects to the same URL as above (and the case sensitivity toggle button becomes active/selected).

#### Expected behavior:

Expecting **Some** results.

The **same query**, but **case insensitive**, returns many results, and some of them DO MATCH as if the above regex was applied case-sensitive, too.
https://sourcegraph.com/search?q=context:global+type:file+lang:rust+/%28struct%7Cenum%7Ctrait%7Ctype%29+%2BC%5BA-Z%5D/&patternType=keyword&sm=0

For example, among the first few results is the following (the order of results varies a little from one search to another):
[rust/fate_utils/crates/ou/src/lib.rs](https://sourcegraph.com/github.com/FederatedAI/FATE@6731122324d94b366a99a81aa766cfc441f87899/-/blob/rust/fate_utils/crates/ou/src/lib.rs) ->  `pub struct CT(pub BInt)` in [rust/fate_utils/crates/ou/src/lib.rs](https://sourcegraph.com/github.com/FederatedAI/FATE@6731122324d94b366a99a81aa766cfc441f87899/-/blob/rust/fate_utils/crates/ou/src/lib.rs)
![image](https://github.com/sourcegraph/sourcegraph/assets/4270240/7f710c70-08bf-47a3-a019-7433295e1f0e)

Potentially partially related to #43491 - I can't fully confirm this, because there's no way to export from a query that gives an empty result. (I've tried to tweak & create a download URL - I've exported from a different query that does have some results, and I looked at the URL of the downloaded CSV file, but the URL contains a UUID-like identifier and has no resemblance to the non-export results page.)

UPDATE 1: More narrowed down below.

UPDATE 2: Ignore my previous update here - I was mistaken, this seems to show up only when running case sensitive.
~~Expanded: Initially I thought this (fewer results, or no results) applies only if we apply the regex case-sensitively. But, it happens **even without** enabling the case sensitivity ("Aa" button). See a newer comment.~~

/cc @sourcegraph/search-platform

**Comment by peter-kehl** [comment]
Is there a way to have a part of the query match file/source content, and another part of the (same) query match the file path? That could be a workaround.
But it doesn't seem possible: `context:global /struct CT/ (type:path /.*\.rs/)` and `context:global /struct CT/ (type:path .rs)` still return empty (at least so when case-sensitive is toggled on).

Some workaround:
`(type:file context:global /struct CT/) (type:path .rs)`
https://sourcegraph.com/search?q=%28type:file+context:global+/struct+CT/%29+%28type:path+.rs%29&patternType=keyword&case=yes&sm=0
does return results (with case-sensitive toggled on). But, it includes some `.cc`, `.cpp`, `.hpp`... files, too! Could you advise if such a query is well-formed (and hence, if it's supposed to return `.rs` files only)?

**Comment by jtibshirani** [comment]
Thank you @peter-kehl for the detailed bug report! We are aware of the regression and working on a fix now.
