### ISSUE TITLE
sg release create should fail if an internal release with the same version number exists 

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#62144]
Right now, you can run multiple times `sg release create --version vX.Y.Z`  which is convenient when iterating. But there's a risk of accidentally overwriting existing images with the same version number, which would be very dangerous, as it would completely break the semantics around internal/promoted. You could end up promoting an in internal release that isn't what you thought would be. 

And because we're only registering the release in the _finalization_  phase of the internal release creation, we would fail *after* having overwritten the containers. 

Ultimately, because we have the SHA of the previous internal release we could with some efforts get back on our feets, that's really not something we want to be forced to do. 

Ideas for how to approach this: 

A/ We say that a given Z number is a special one reserved for testing (like `X.Y.666`). 

- We check if the release exists before anything else, and fail unless it's the special number. 
- While this sounds fun (being an Iron Maiden fan, this always makes me sing "Number of the beast" in my head) not everyone might enjoy the cultural reference (`777` might be better though). 
- A special number is tribal knowledge, even if we say something about it when creating the release, it's hard to discover. 
- If more than one person try to use the _test number_ we'll end with multiple jobs pushing different images at the same time. Nice way to have fun on a friday evening, right? 

Mentioned it because it's fun, but I don't think we should do this. 

B/ We introduce a `--release-development` flag where we mark the release as "release-development" on the release registry, and allow for creating it repeatedly (basically overwriting the previous one). 

- We check if the release exists before anything else, and fail if it does unless it's been tagged as development. 
- We block promotion of released tagged as "release-development". 

The question remains on how to iterate on the promotion phase, I wonder if we should pass in the steps the info that it's a release-development one, and thus we could swap the artifacts destinations to a private destination on the fly. 

I'm scratching a bit my head on this one, as the steps might become really verbose if we do so. But still, B/ would be fine without this, as we already have to take manual steps to do so.

**Comment by BolajiOlajide** [comment]
> The question remains on how to iterate on the promotion phase, I wonder if we should pass in the steps the info that it's a release-development one, and thus we could swap the artifacts destinations to a private destination on the fly.

We can rely on the release registry to answer this question.
