### ISSUE TITLE
Docs: update docs for search max file size (search.largeFiles)

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#6216]
https://docs.sourcegraph.com/user/search#max-file-size is outdated. @attfarhan since you own search, can you update this?

FYI @ryan-blunden

**Comment by attfarhan** [comment]
@dadlerj I own the search frontend now, not backend anymore FYI. Core services owns search backend now. But I can open a PR to update this 👍

**Comment by dadlerj** [comment]
Got it. Heh, not super obvious how to assign these though... Would site config option documentation fall under frontend or backend? How about user/site settings options?

**Comment by dadlerj** [comment]
(and for this particular update, the docs are at https://docs.sourcegraph.com/admin/config/site_config#search-largeFiles)
