### ISSUE TITLE
Incorrect highlighting for 'authless' search

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#6218]
Off-by-one line highlighting when searching for 'authless': https://sourcegraph.com/search?q=authless&patternType=literal

**Comment by unknwon** [comment]
![Screen Shot 2019-10-25 at 4 39 04 PM](https://user-images.githubusercontent.com/2946214/67610189-f5ca7100-f745-11e9-863b-91e86d6a18b1.png)

Attach a screenshot just in case.

**Comment by lguychard** [comment]
This has been fixed.
