### ISSUE TITLE
`type:path` does not work on Zoekt code path 

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#6220]
`type:path` in search queries should only filename results, as per https://docs.sourcegraph.com/user/search/queries#filename-search. 

In the Zoekt code path, this does not work, see: https://sourcegraph.com/search?q=r:%5Egithub.com/sourcegraph/sourcegraph%24+type:path+test&patternType=literal. 

Expected results should look like this (same query with `index:no` appended): https://sourcegraph.com/search?q=r:%5Egithub.com/sourcegraph/sourcegraph%24+type:path+test+index:no&patternType=literal

I discovered this when trying to build https://github.com/sourcegraph/sourcegraph/issues/5996.

**Comment by attfarhan** [comment]
cc @kzh is this something you'd want to work on since it's Zoekt related? Otherwise I can set aside time to work on this soon.

**Comment by kzh** [comment]
I can take this on today.
