### ISSUE TITLE
LSIF: cache growth might cause OOM

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#6221]
From https://github.com/sourcegraph/sourcegraph/pull/6205#discussion_r339247849

I'm guessing that two caches of 1GB each would cause Node to run OOM before the caches evict entries. Needs investigation to:

- Determine whether or not OOM is possible at the current cache size
- Determine what the cache size ought to be (the tradeoff is that lsif-server will slightly more frequently reopen the DBs to fetch values)

**Comment by efritz** [comment]
Closing as we're porting the bundle manager to Go where we'll have an easier time managing the cache sizes.
