### ISSUE TITLE
Combined (implied AND) query including type:path matches other files/paths, too

### ISSUE THREAD

**Issue by peter-kehl** [sourcegraph/sourcegraph#62225]
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:** current Firefox

#### Steps to reproduce:
1. Advance apologies if the following query is not well formed - then please advise if queries with similar meaning are possible/planned.
2. https://sourcegraph.com/search?q=%28type:file+context:global+/%28struct%7Cenum%7Ctrait%7Ctype%29+%2BCa%5BA-Z%5D/%29+%28type:path+.rs%29&patternType=keyword&case=yes&sm=0 which is case sensitive for `(type:file context:global /(struct|enum|trait|type) +Ca[A-Z]/) (type:path .rs)`
3. Out of 30 results ("Preview") shown, 3 don't have any `.rs` or `rs` in their URL:
- https://sourcegraph.com/github.com/googleapis/google-cloud-go@31558c7df7f12424efddda43cdfaf463f99eae1c/-/blob/security/privateca/apiv1/privatecapb/resources.pb.go
- https://sourcegraph.com/github.com/GoogleCloudPlatform/k8s-config-connector@8078c5ce47599697f2f9d5d0854fbdb1d58f92b9/-/blob/mockgcp/generated/mockgcp/cloud/security/privateca/v1/resources.pb.go
- https://sourcegraph.com/github.com/NLnetLabs/krill@33e072ef44e60e1e9bdadc153ffc1f809d1f7912/-/blob/doc/development/04_es_krill.md
![image](https://github.com/sourcegraph/sourcegraph/assets/4270240/ea0735c6-fc27-4d7c-aa5b-17812b8ec312)

#### Expected behavior:
Only files with `.rs` in the path/URL.

#### Side note:
I do know of a workaround - but it's a workaround only for this particular use case, not a general workaround for this problem.
(The workaround for this instance is to search with `lang:rust`. Thank you for fixing #62127 with #62157 - I confirm that it works.)

**Comment by camdencheek** [comment]
Hey @peter-kehl! The query definitely looks a bit funky. Usually, putting `type:file` and `type:path` in the same query is not what you actually want. 

If you just want to search for `.rs` files that contain content matching the regex `/(struct|enum|trait|type) +Ca[A-Z]/`, I'd recommend a query like `type:file context:global file:\.rs$ /(struct|enum|trait|type) +Ca[A-Z]/`
