### ISSUE TITLE
Svelte: Create consistent, predictable, intuitive keyboard shortcuts

### ISSUE THREAD

**Issue by taiyab** [sourcegraph/sourcegraph#62273]
As we progress through our implementation of the [new file view designs](https://www.figma.com/file/EPgl0qVbqGSumvf52brhda/branch/bpPdFQrzcoQBxD8ujtdGbI/Code-Search?type=design&node-id=2675%3A96618&mode=design&t=C4E4Kpm4UJjgmsT8-1), we're starting to surface the keyboard shortcuts used to trigger various actions on the UI.

For example:
- `/` triggers global finder/search
- `⌥R` might trigger revision selector
- `⌥N` might trigger opening a new file pane

etc. etc.

We need to establish a set of shortcuts that make sense system-wide, and match up to other common shortcuts used in other systems and tools/IDEs.

We also need a way to universally show these keyboard shortcuts and hence a binding to show and hide that panel too (which preferably corresponds to the "prefix" we use, e.g. in the cases above, ⌥, so hitting ⌥ might bring up the keyboard shortcuts available to you in a menu).

The work here would be to:
- Gather all the places throughout the system that we'd want to enable a shortcut for
- Ensure a consistent pattern of shortcuts throughout
- Ensure no overlap in shortcuts used
- Ensure the shortcut mapping is intuitive
- Ensure the mapping works across all operating systems
- Create a better way for us to assign and manage these keyboard shortcuts, all in one place

Anything I've missed here? @camdencheek @vovakulikov @fkling

**Comment by bahrmichael** [comment]
The "RFC 945 Code Search Shortcuts" is ready for approvals after most of the discussion seems to be done.

I'm going to close this issue. Feel free to reopen if necessary.
