### ISSUE TITLE
Unable to copy generated code

### ISSUE THREAD

**Issue by hashborgir** [sourcegraph/sourcegraph#62391]
Hi. I am unable to copy generated code. 

VSCode - Latest version of VSCode and Cody extension
Pro account

You generated code.
You highlight certain parts of the code with mouse. 
Right click to get context menu.
Click copy.
Text is not copied to the clipboard.

You generate code.
You highlight certain parts of the code with mouse.
You hit CTRL + C.
Text is not copied to clipboard.

Please either fix this or issue a refund ASAP, because the Cody software is non-functional.

**Comment by varungandhi-src** [comment]
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/62361
