### ISSUE TITLE
Svelte: Truncate commit messages in history panel

### ISSUE THREAD

**Issue by taiyab** [sourcegraph/sourcegraph#62393]
Commit messages should probably get truncated in the history panel so they don't go over multiple lines.

![CleanShot 2024-05-02 at 17 39 14@2x](https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/870ed565-98aa-444b-804a-d9c9b696dda3/d3ad2cd2-bee6-48c9-a4a7-c15fc07441c8?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy84NzBlZDU2NS05OGFhLTQ0NGItODA0YS1kOWM5YjY5NmRkYTMvZDNhZDJjZDItYmVlNi00OGM5LWE0YTctYzE1ZmMwNzQ0MWM4IiwiaWF0IjoxNzE0NjkwOTU1LCJleHAiOjMzMjg1MjUwOTU1fQ.tvXmv6PkSp1nbkaHrti0MHm1RGTIZpd778FVQVFs9YA "=885x")

**Comment by vovakulikov** [comment]
@taiyab Should it always be one line, or should we truncate everything after the N line? 
I like what google code search has in their history panel, ability to expand the row where you can see the full commit message 

<img width="837" alt="Screenshot 2024-05-03 at 16 13 02" src="https://github.com/sourcegraph/sourcegraph/assets/18492575/9c36a019-6c52-4970-b57e-516262444724">

**Comment by taiyab** [comment]
@vovakulikov One line.

Feel free to add an expander like that.
