### ISSUE TITLE
Svelte: dotcom readiness

### ISSUE THREAD

**Issue by fkling** [sourcegraph/sourcegraph#62390]
This is an epic to collect tasks needed to be done to enable the Svelte app on dotcom. This list is not complete yet, a big part of working on this is completing the list.

**Comment by vovakulikov** [comment]
This is a kind of random thought. In our react codebase, we almost everywhere use the `isSourcegraphDotCom` flag. I understand that this is a very convenient way to distinguish between commercial and marketing instances. 

But I would like to challenge us to think not in terms of in-place flag checks but in terms of extension points of the app to make necessary differences in UI/logic/etc. Why? I actually don't have a clear list of arguments here but it feels like a coupled code-base problem when we have to make differences not in one but in many places at once for some specific instance (Implementation leak problem), consumers know too much about environment, leads to complexity of testing and reusing it later.

What do I propose instead? So ideally I would like to have one place (file/store/etc) where we will define feature set specific to the Sourcegraph dot com instance and include it by one check via `isSourcegraphDotCom`.

**Comment by fkling** [comment]
I agree, that would be ideal. My gut reaction is that this only works if all of the dotcom differences are data driven. E.g. I can totally see how this works for main navigation, but there might be other areas where it's not as obvious.
Of course we can always add more specific settings/props so that we do not couple it to `isSourcegraphDotCom` specifically. Maybe that's actually a good approach.
