### ISSUE TITLE
Search query builder automatically wraps "Exact string" with double quotes

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#6253]
On sourcegraph.com:

![Screen Shot 2019-10-29 at 10 59 38 AM](https://user-images.githubusercontent.com/2946214/67795261-39212a00-fa3b-11e9-9fef-5e092e092f88.png)

Redirects user to https://sourcegraph.com/search?q=%22open%28%22&patternType=literal.

![Screen Shot 2019-10-29 at 11 00 06 AM](https://user-images.githubusercontent.com/2946214/67795297-45a58280-fa3b-11e9-88e6-7a2b2d358f4f.png)

It is somewhat funny that before we have literal search as default, https://github.com/sourcegraph/sourcegraph/issues/2383 was reported no double quotes as a bug, now it's a bug on the other side 😂

**Comment by attfarhan** [comment]
Hah, good catch, thanks for filing.

@christinaforney this also raises the question, what do we want to do with the query builder once we're done with RFC10? Do we want to remove it completely, or should it remain on the homepage?
