### ISSUE TITLE
Code insights: Extend GraphQL schema to expose repositories that cause incomplete datapoints

### ISSUE THREAD

**Issue by bahrmichael** [sourcegraph/sourcegraph#62578]
https://github.com/sourcegraph/sourcegraph/issues/62295 surfaced problems with debugging timeout and generic problems that lead to incomplete data points. The documentation says that the user should reduce the scope of the query, but we see that customers prefer to run queries over all of their repositories. I'm not sure how we would bisect repositories to exclude the problematic ones.

Our GraphQL schema for `TimeoutDatapointAlert` and `GenericIncompleteDatapointAlert` contains the time and maybe a generic reason that something went wrong. 

We could help users that don't have access to logs by exposing the repository/repositories that caused problems.

Example:

```
type GenericIncompleteDatapointAlert implements IncompleteDatapointAlert {
    """
    The data point that is incomplete.
    """
    time: DateTime!

    """
    A message describing why the datapoint was marked incomplete.
    """
    reason: String!

    """
    The repositories that this data point is incomplete for.
    """
    repositories: [String!]!
}
```

As a next step we could surface this information in our UI, but including this info in our GraphQL should be a good start.

**Comment by camdencheek** [comment]
Seems useful! 

One question: can't we have multiple reasons? In particular, wouldn't there potentially be a different reason per incomplete repository?

**Comment by bahrmichael** [comment]
> wouldn't there potentially be a different reason per incomplete repository?

In theory yes. Currently we have only timeout and generic as reasons. From what I can see the code encourages adding new types when there are errors that we want to distinguish from each other.

https://github.com/sourcegraph/sourcegraph/blob/d7dc2b9d9a1e7c44c5de59617b0dae4c7d969cee/cmd/frontend/internal/insights/resolvers/insight_series_resolver.go#L554-L559

https://github.com/sourcegraph/sourcegraph/blob/d7dc2b9d9a1e7c44c5de59617b0dae4c7d969cee/internal/insights/store/store.go#L875-L879

I feel like changing the shape of the incomplete datapoints and its sub-fields can become a rabbit-hole and would avoid going this route unless necessary.

An alternative to satisfy the need to to isolate out repos could be an additional field next to the incomplete datapoints that just has a list of repos with problems.

```gql
"""
Status indicators for a specific series of insight data.
"""
type InsightSeriesStatus {

    ...

    """
    Data points that are flagged terminally incomplete for this series.
    """
    incompleteDatapoints: [IncompleteDatapointAlert!]!

    repositoriesWithProblems: [String!]!
}
```

Instead of a list of repo names, this could also be a more sophisticated list with error reasons and timestamps.
