### ISSUE TITLE
Publish latest intellij editor integration fixes

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#6258]

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.11 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by slimsag** [comment]
This was released Nov 5th.
