### ISSUE TITLE
How to retain a specific branch for repositories 

### ISSUE THREAD

**Issue by summer9989** [sourcegraph/sourcegraph#62599]
#### Question description

In the Sourcegraph , for all repositories connected to a code host, I only want to store and retain a specific branch (for example, master), in order to improve performance. How can I achieve this?

#### Additional context

**Comment by eseliger** [comment]
Hello! There are limited settings to achieve that today, Sourcegraph does not support shallow clones. There is some hidden setting in gitserver to specify the ref map, but that might affect features like batch changes.
For that you could use `SRC_GITSERVER_REFSPECS` as an env var on the gitserver statefulset and specify the mappings to pass to git. The default is 
```
			// Normal git refs
			"+refs/heads/*:refs/heads/*", "+refs/tags/*:refs/tags/*",
			// GitHub pull requests
			"+refs/pull/*:refs/pull/*",
			// GitLab merge requests
			"+refs/merge-requests/*:refs/merge-requests/*",
			// Bitbucket pull requests
			"+refs/pull-requests/*:refs/pull-requests/*",
			// Gerrit changesets
			"+refs/changes/*:refs/changes/*",
```

I'm curious what the performance issues are you are facing - could you share some details here?
