### ISSUE TITLE
Username normalization breaks repo permissions

### ISSUE THREAD

**Issue by gabtorre** [sourcegraph/sourcegraph#62676]
- **Sourcegraph version:** 5.3.12303 
- **Platform information:** 

We encountered an issue where usernames with suffixes are breaking permissions syncs with Bitbucket, as Bitbucket requires exact username matches. Sourcegraph normalizes usernames by adding a [suffix](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@058f831423994c6544605114505b1fd21d7796c3/-/blob/internal/auth/userpasswd/handlers.go?L553-555) if the username is in email format. This discrepancy affects setups where SCIM and SAML are involved and the username has to be set as an email.

#### Steps to reproduce:

1. Set up SCIM and SAML with Okta.
2. Create a user and sync permissions with Bitbucket.

#### Expected behavior:
Usernames should match exactly between Sourcegraph and Bitbucket without normalization issues.

#### Actual behavior:
Usernames in Sourcegraph get a suffix added during normalization, causing mismatches with Bitbucket usernames.

If you would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are no [SLAs](https://sourcegraph.com/support/) on issues like there are for support requests).

**Comment by noah-berman** [comment]
This is affecting Citadel after a recent upgrade (to 5.3.11625), as well
