### ISSUE TITLE
Svelte: preserve repo revision in search bar

### ISSUE THREAD

**Issue by peterguy** [sourcegraph/sourcegraph#62713]
In the Svelte web app prototype, the revision of the repository is not preserved in the search bar. See attached screen recording for details.

To replicate this behavior:

1. search for `repo:github.com/sourcegraph/sourcegraph rev:at.time(1 month ago)` as a convenient way to get right to a particular revision.
2. click on the link to the repo at the revision.
3. See that the revision is in the address bar.
4. Type slash (`/`) (or click on the search bar) and see that the revision is missing from the search bar.

https://github.com/sourcegraph/sourcegraph/assets/129280/9b492afe-54e4-42aa-8faf-8bc279fbf873

**Comment by taiyab** [comment]
@peterguy So we're only fixing this here and not in React? Meaning, until Svelte is shipped, no one gets a fix for this (if there is one)?

**Comment by fkling** [comment]
@taiyab The React app includes the revision: 
![2024-05-16_13-22](https://github.com/sourcegraph/sourcegraph/assets/179026/404af422-63e5-43ff-bdad-f08b2a43e79d)
