### ISSUE TITLE
Svelte: Import Lucide icons

### ISSUE THREAD

**Issue by taiyab** [sourcegraph/sourcegraph#62721]
We're going to replace all icons on the web app with Lucide ones: https://lucide.dev/icons/ -- feel free to pick appropriate icons from this set once implemented.

I think Vova is already working on removing the dependency on mdi.

**Comment by fkling** [comment]
We can either use their Svelte integration directly or use https://github.com/unplugin/unplugin-icons. The latter has the advantage that we could (apparently) use the same API for loading custom icons, should we need it.
