### ISSUE TITLE
It is not clear when a user needs to move from server -> docker-compose or cluster

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#6274]
I often get the question from customers as to whether they need to move to cluster or not (particularly due to https://github.com/sourcegraph/sourcegraph/issues/3538).

Typically my advice is “go for it, and if you see perf issues, let’s revisit”

It would be nice to have rough boundaries — e.g., 0–250 repos, use an AWS medium, 250-1K use an AWS large, 1K–2K use an AWS xlarge, >1.5–2k, consider switching to cluster. 

Or if that's hard, at least an explanation of why it's hard, and how they should figure it out. Nice to be able to share a docs page that shows we've thought about this stuff even if there's no universal answer!

@beyang note: See also https://github.com/sourcegraph/sourcegraph/issues/2019

**Comment by dadlerj** [comment]
A user at https://app.hubspot.com/contacts/2762526/company/974120254 ran into issues with this today while following instructions on our AWS deployment docsL https://docs.sourcegraph.com/admin/install/docker/aws

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.11 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.12 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.13 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by slimsag** [comment]
See also https://github.com/sourcegraph/sourcegraph/issues/11828

**Comment by pecigonzalo** [comment]
Isnt this sort of covered as well in https://docs.sourcegraph.com/admin/install? `Suggested for: Local testing`
