### ISSUE TITLE
Development documentation structure is messy

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#6289]
https://docs.sourcegraph.com/dev

It is currently very difficult to navigate our development docs:

- Truncated (too long) titles
  - Titles should be concise and fit into the sidebar, e.g. "Getting Started" instead of "Getting started with developing Sourcegraph". Context should be provided through nesting.
  - Lots of titles are prefixed with "Sourcegraph" which is redundant from the context of the docs
- Lots of top-level docs that are not truly top-level
  - e.g. MAJOR.MINOR.PATCH et al should be nested under "Releases"
  - "Developing xyz" should be grouped
- Lots of space taken up by old Retrospective notes
  - These are not canonical documentation (except the doc on how to run a retrospective), but a long log that doesn't belong here imo (especially not documents like "Milton's notes on xyz"). Our newer retrospectives are in GDoc, let's move the old ones there too.
- Dead links (_N# Sourcegraph Architecture diagram_, _Code Style Guide_)
- Confusing titles (e.g. "Print info from Gitolite" that is actually titled "Gitolite/Phabricator documentation")

![image](https://user-images.githubusercontent.com/10532611/67943885-58ef5400-fbdb-11e9-8735-3b73ecfb1e3a.png)

**Comment by nicksnyder** [comment]
Thanks for filing this, it does need attention. @lguychard do you want to take a pass at this when you are thinking about our eng onboarding process? If not, I can later.

I don’t think the individual retrospectives need to be in the sidebar.

**Comment by lguychard** [comment]
Yes, I will tackle this.

**Comment by dadlerj** [comment]
Not necessarily related to the work you're doing, but I have a branch where I'm creating a new /team section of the docs. This will be for our internal team processes, and a part of the /dev section would move there (i.e., everything having to do with how WE work internally, rather than how to contribute to our oss codebase).

See: https://sourcegraph.slack.com/archives/CCVUFTEFN/p1571856085059800

**Comment by ryan-blunden** [comment]
@lguychard Let's sync on some options for improving the nav as I've got a few ideas.

**Comment by christinaforney** [comment]
@felixfbecker - does https://github.com/sourcegraph/sourcegraph/pull/14509 help improve this for you? What other things could we do to make this better?

**Comment by felixfbecker** [comment]
Yeah, the sidebar is certainly clean now!

One thing I noticed - a lot of things in "Background information" are actually less knowledge documents and more contribution guides that may fit more under "How to" (although they are not really written in a how-to format). Meanwhile "How to" seems to be mostly Troubleshooting. Those titles maybe could be better (I don't have a concrete proposal rn).

**Comment by felixfbecker** [comment]
Will close this though as the original issue is definitely solved.
