### ISSUE TITLE
Layout bug in github notifications

### ISSUE THREAD

**Issue by Warchant** [sourcegraph/sourcegraph#629]
- **Sourcegraph version:** 2.12.3
- **Chrome extention version:** 1.19.0

#### Steps to reproduce:

1. Install chrome extention
2. Go to github notifications 
3. There should be some notifications (bug can be reproduced with 1-4, I tested with those)
4. Layout is buggy (I suspect that it is because of the button on the top left corner - file tree)

If I disable sourcegraph chrome extention, bug disappears (as expected).

#### Actual behavior:
![image](https://user-images.githubusercontent.com/1867551/47843472-61def700-ddc8-11e8-938c-1e3db2a6056a.png)

**Comment by keegancsmith** [comment]
Sorry about that! We will resolve this ASAP.

Reports on twitter of this happening to other users, and confirmed that it is Sourcegraph responsible. https://twitter.com/LiliCosic/status/1057948945266212864

**Comment by sqs** [comment]
Confirmed repro. Fixing now.

**Comment by sqs** [comment]
Fix is in CI now (https://github.com/sourcegraph/extensions-client-common/pull/67).

**Comment by sqs** [comment]
A fix is currently being published (to the Chrome Web Store) and should be available to Chrome users within the next hour. No action is necessary (assuming you have auto-update enabled in Chrome, as virtually everyone does). Sorry again for the issue!
