### ISSUE TITLE
Go to definition fails on TS function

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#62923]
This file (https://sourcegraph.com/github.com/sourcegraph/cody@89f8c73010ce21b3185c0816c1ed3ad671119697/-/blob/vscode/webviews/promptEditor/plugins/atMentions/atMentions.tsx) has a lot of other precise refs, but on the `scanForMentionTriggerInUserTextInput` symbol it fails:

1. It is not able to find any precise results for it. This `scanForMentionTriggerInUserTextInput` symbol should be precise because it's in the same repo and imported in a sane way.
2. It's not able to find any search-based results, even though this function is defined in a sane way elsewhere in the repo.

https://github.com/sourcegraph/sourcegraph/assets/1976/99c247ce-c6fd-4177-bc34-7fd0e1ccfe93

**Comment by varungandhi-src** [comment]
Assigning to myself to check if this is fixed with the fix for [GRAPH-632](https://linear.app/sourcegraph/issue/GRAPH-632/scip-upload-no-longer-work-for-long-paths)

**Comment by varungandhi-src** [comment]
Looks like navigation works properly locally now; the fix should make it's way to S2 etc. soon, so when a fresh upload is made, that should fix navigation.

<img src="https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/5156a533-e094-46da-abac-3988e047e968/247e1224-b1c8-4cd5-9532-836c3c27f98f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy81MTU2YTUzMy1lMDk0LTQ2ZGEtYWJhYy0zOTg4ZTA0N2U5NjgvMjQ3ZTEyMjQtYjFjOC00Y2Q1LTk1MzItODM2YzNjMjdmOThmIiwiaWF0IjoxNzE2OTkxOTMyLCJleHAiOjMzMjg3NTUxOTMyfQ.CQdiFzLXm9NvcdkFj0S9rECRUpvMBMZT-ldfyq1qRYU " alt="CleanShot 2024-05-29 at 22.10.07@2x.png" width="2854" height="1814" />
