### ISSUE TITLE
v5.4.3500 Security approval

### ISSUE THREAD

**Issue by DaedalusG** [sourcegraph/sourcegraph#62935]
https://buildkite.com/sourcegraph/sourcegraph/builds/275841 <- Buildkite build

Security must close this issue before releases. It is the responsibility of the Security Engineer on rotation the week the release is cut. More steps will be added in the future.

- [x] All feasible CVEs are closed.
- [x] Any open CVEs are documented in the handbook.

cc @sourcegraph/security

**Comment by andreeleuterio** [comment]
All set. I will check in with the team tomorrow for documenting this release but no new vulns were found.
