### ISSUE TITLE
Clicking command palette on /start scrolls to bottom of page

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#631]
On https://sourcegraph.com/start when you click the command palette, it scrolls to the bottom of the page and does not open the command palette.

![screenshot from 2018-11-01 09-35-46](https://user-images.githubusercontent.com/1976/47865476-8c758380-ddb9-11e8-9179-89a2624dfb42.png)

**Comment by nicksnyder** [comment]
Any update here?

**Comment by vanesa** [comment]
Yes: `display:block` is the root of all evil.
PR: https://github.com/sourcegraph/sourcegraph/pull/1767

**Comment by lguychard** [comment]
I think the [autofocus](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/shared/src/commandPalette/CommandList.tsx#L32:5) prop of `CommandList` may be the issue:

> this sometimes results in the page being scrolled to the bottom

**Comment by vanesa** [comment]
Thanks @lguychard! Just pushed a better solution #1767 using ref to apply the autofocus directly on the DOM element.

**Comment by francisschmaltz** [comment]
@vanesa @lguychard this is still occurring for me on sourcegraph.com. Is this resolved?

**Comment by ggilmore** [comment]
@francisschmaltz I just re-deployed sourcegraph.com. Could you try again?

**Comment by vanesa** [comment]
Yes, sorry @ggilmore and @francisschmaltz , waiting for review to merge.

**Comment by sqs** [comment]
Removing release-blocker because in reality we would be OK shipping the release without this fixed (because this only occurs on Sourcegraph.com not self-hosted instances, so users will get the fix when we redeploy, which we can do at any time).

**Comment by francisschmaltz** [comment]
@vanesa this is still an issue on Sourcegraph.com/ in safari and Firefox

**Comment by nicksnyder** [comment]
@vanesa did you deploy to production after this change?

**Comment by vanesa** [comment]
I didn't, but Geoffrey did. Will look into this.
