### ISSUE TITLE
Allow for team seat count decreases

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#63234]
In https://github.com/sourcegraph/self-serve-cody/issues/791, we only allow _increasing_ seat counts, but there is no way to decrease them.

We also don't have designs for this yet.

The back-end logic most likely fully exists (that is, `usePreviewUpdateCurrentSubscription` and `useUpdateCurrentSubscription` just do their job for negative changes), so it's probably only some front-end work missing.

**Comment by chenkc805** [comment]
@rob I think this one is in your space. This should just look like the checkout flow, and include this information:

1. Current number of seats paid for
2. Current accepted+pending invites
3. Selector that allows the user to choose what new seat plan they want (so if they are starting at 20 seats, they can change this dropdown to, say, 15 seats)
4. Show copy that they will not get a refund for any seats that they've already paid for this month. The new monthly payment will start in the next billing period
5. When the user confirms their plan if the selector in #3 is fewer than the users in bullet #2, then show an error:
   1. Error Copy: You cannot decrease your seats lower than the number of accepted and invited users in your plan. Please go to your plan <link to team management page> and remove users or rescind invites before downgrading your plan.

**Comment by rrhyne** [comment]
An experience built in that way would cause users to experience an error to learn how to reduce their seat count. I think we can improve upon that. <br><br>I think we should also consider the JTBD here. These two rely on removing a user already in the system:

* I need to remove a teammate from my plan as they no longer need the service
* I need to reduce billing for this service

<br>There is also this state/JTBD:

* I have extra seats I am not using and I want to reduce that number
  * Note that the only area where the invites are listed is in the invite form

Is there any reason the billing form needs to be involved? Why not revoke individual seats (the admin would surely need to select who, not just reduce a number), and then allow for a reduction in the number of remaining invites? We could make it simple for now and only allow them to remove all remaining invites.

**Comment by chenkc805** [comment]
I don't feel strongly about the billing form needing to be involved. That said, I think having this functionality on the billing form makes the change feel more "official" since it directly impacts how much users pay for their subscription. When users add seats to an existing Teams plan they also see the checkout page, so the downgrade seats flow would be consistent with that user experience.

Ultimately I defer to you on your call for how this should be designed. 

> *We could make it simple for now and only allow them to remove all remaining invites.* 

I think users would get confused why they couldn't decrease their seats more if we don't throw them an error, hence my idea for bullet (5a) above.

**Comment by rrhyne** [comment]
Here's a loom describing the proposal:<br><br>[https://www.loom.com/share/3f57ad98ac4f445386ac56846cd0c84d](https://www.loom.com/share/3f57ad98ac4f445386ac56846cd0c84d)

<br>and the link to the Figma section:<br>[https://www.figma.com/design/FMSdn1oKccJRHQPgf7053o/Cody-PLG-GA?node-id=5556-13856&t=KoC1fna6hYdzqbfU-4](https://www.figma.com/design/FMSdn1oKccJRHQPgf7053o/Cody-PLG-GA?node-id=5556-13856&t=KoC1fna6hYdzqbfU-4)

**Comment by chenkc805** [comment]
Great - let's move forward with the designs in @rrhyne 's Figma.
