### ISSUE TITLE
"Invite co-workers" button is missing

### ISSUE THREAD

**Issue by vdavid** [sourcegraph/sourcegraph#63245]
See bug report in the [figma](https://www.figma.com/design/FMSdn1oKccJRHQPgf7053o/Cody-PLG-GA?node-id=5393-24891&t=JNnWuJNvPLFnf7x1-0). Button is needed on the `/cody/manage` page.

**Comment by chenkc805** [comment]
@rob @taras.yemets @david.veszelovszki is this still a bug? I don't see the Figma link linking me to anything.
