### ISSUE TITLE
Negative lookahead unsupported

### ISSUE THREAD

**Issue by majapw** [sourcegraph/sourcegraph#636]
- **Sourcegraph version:** 2.12.2
#### Steps to reproduce:

1. Try to use negative lookahead, e.g. `foo(?!bar)` in the search bar

#### Expected behavior:
Search returns matches on `foo` but not `foobar`

#### Actual behavior:
I get an error saying `Type error at character 43: error parsing regexp: invalid or unsupported Perl syntax: '(?!'`

Is there any intention to support negative lookahead in the future? That would be super helpful! :)

**Comment by keegancsmith** [comment]
Unfortunately supporting negative lookahead requires using a regular expression engine with bad worst case performance in practice. So we would very unlikely support this syntax in the future. However, we will soon have a more powerful query syntax. You could write your query as `foo -foobar` to find all documents which contain foo but not foobar (unfortunately not exactly the same meaning, but may be good enough?)

**Comment by sqs** [comment]
Will reevaluate in January 2019 (or sooner if the need/priority arises), given that the soon-to-be-supported `-term` (term negation) will help here.

**Comment by majapw** [comment]
Thanks for responding! I appreciate the explanation.

**Comment by sqs** [comment]
Thanks! When you upgrade to 3.0-preview, let us know how well the term negation solves your needs. (Docs/announcement will be out next week for that.) We can reconsider priorities if it doesn’t help.

**Comment by slimsag** [comment]
@sqs @keegancsmith I assume the path forward being described above was us having support for full-blown nested search? (https://github.com/sourcegraph/sourcegraph/issues/1005)

A customer today also reiterated importance of having negation like this (and of course more generally, us having more powerful search would be good), so I am removing from backlog for us to reprioritize this work.

One option could be detecting negated queries and having them fall back to a different regex engine that does support negative lookahead, and warning the user those may be slower than regular queries? How complex is that relative to nested search, I wonder?

**Comment by sqs** [comment]
> @sqs @keegancsmith I assume the path forward being described above was us having support for full-blown nested search? (#1005)

Yes, that is correct. Sorry for the outdated info here. 

We will post an update soon the plan to provide this.

**Comment by poojaj-tech** [comment]
@rvantonder checking if this is good to close? Since the NOT operator supports this workflow, and I believe the next set of features / incremental improvements are planned for AND / OR operators.

**Comment by rvantonder** [comment]
Yes, I think we support something close enough now, like:

`foo not foobar`

`foo and not foobar`

(these are equivalent)

Before closing this issue, it would be great if we could document how we support something "like" negative lookahead. Not sure if our search syntax docs is the best place, this feels more like an example use (and it would be nice if it were discoverable if someone searched the docs for "negative lookahead"). Thoughts?

**Comment by poojaj-tech** [comment]
@rvantonder created an issue to document examples in #15365. (I added the 'docs' label to consider it for docs, but agree that docs aren't the best or only place for search example uses)
