### ISSUE TITLE
Public repo not showing up on sourcegraph search

### ISSUE THREAD

**Issue by sjain-stanford** [sourcegraph/sourcegraph#63745]
- **Sourcegraph version:**  Sourcegraph.com
- **Platform information:**  Chrome

I noticed that the public repo [github.com/cruise-automation/mlir-tcp](http://github.com/cruise-automation/mlir-tcp) doesn't show up on Sourcegraph anymore. It used to, but not as of a few days ago (maybe longer). Could you please help look into this?

#### Steps to reproduce:

1. Type this in the browser: https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/cruise-automation/mlir-tcp%24++&patternType=standard&sm=0&groupBy=repo

#### Actual behavior:

If you would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are no [SLAs](https://sourcegraph.com/support/) on issues like there are for support requests).

**Comment by jdorfman** [comment]
Hey @sjain-stanford I got you: https://sourcegraph.com/github.com/cruise-automation/mlir-tcp

BTW you totally qualify for https://sourcegraph.com/supporting-open-source =)

**Comment by sjain-stanford** [comment]
Thanks @jdorfman , appreciate restoring the repo on SourceGraph. I just applied for Cody Pro :D

**Comment by sjain-stanford** [comment]
Hi @jdorfman , do you know why I'm unable to search these repos on SourceGraph today?

https://github.com/llvm/llvm-project
https://github.com/llvm/torch-mlir

**Comment by jdorfman** [comment]
Hey @sjain-stanford 

We are currently resyncing and indexing repos from GitHub. This process will take some time. Please check out our [status page](https://sourcegraphstatus.com/incidents/3qnkdgrpr6cn) for updates.

We apologize for any inconvenience this has caused.

**Comment by sjain-stanford** [comment]
Ah thank you for the response. No worries!

**Comment by jdorfman** [comment]
For sure!
