### ISSUE TITLE
search pagination: timeouts produce panic

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#6383]
[this query](https://sourcegraph.com/api/console#%7B%22variables%22%3A%22%7B%5Cn%20%20%5C%22query%5C%22%3A%20%5C%22repo%3Akubernetes%2Fkubernetes%20type%3Afile%20.%5C%22%2C%5Cn%20%20%5C%22perPage%5C%22%3A%203%2C%5Cn%20%20%5C%22after%5C%22%3A%20null%5Cn%7D%22%7D) times out, but instead of the repository being reported as timedout it produces a panic unexpectedly.

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.10 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
