### ISSUE TITLE
search pagination: some single-repository result sets timeout

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#6384]
[this query](https://sourcegraph.com/api/console#%7B%22variables%22%3A%22%7B%5Cn%20%20%5C%22query%5C%22%3A%20%5C%22repo%3Akubernetes%2Fkubernetes%20type%3Afile%20.%5C%22%2C%5Cn%20%20%5C%22perPage%5C%22%3A%203%2C%5Cn%20%20%5C%22after%5C%22%3A%20null%5Cn%7D%22%7D) times out because the Kubernetes repository is too large to search. There must be a better way to handle this? options include:

1) Waiting a longer period of time (is a timeout without escape hatch what the user really wants in this case?)
2) Just making Zoekt faster in this case (probably not possible in this particular query that is haystack-full-of-needles, but would be possible in needle-in-the-haystack queries)

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.10 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
