### ISSUE TITLE
campaigns: Heuristic syncing of Changesets and ChangesetEvents

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#6388]
Currently, repo-updater syncs every single `Changeset` (regardless of state) and its full list of `ChangesetEvents` every time a sync runs. This behaviour limits our scalability to customers with large (and many) campaigns.

To solve this, we should introduce some **heuristics** based syncing logic for this data that takes into account the following (and potentially other) factors:

- Previous Changeset state (i.e. OPEN, CLOSED, etc): Do we need to sync closed changesets?
- `updated_at`: If something was updated recently, it should be synced last
- Last changeset event: Perhaps changesets with more activity are more likely to receive further activity soon after, so we should sync them first?
- Changesets can be unattached to Campaigns: we can stop updating/syncing them and then even delete them if they haven't been reattached after a while

These factors ought to be inputs to a **Scheduler** which is also able to **pace** updates over time according to some defined configuration, as well as report **its state**.

If you have other ideas, please add them here.

For prior art on a heurisitcs scheduler we already have for **git** updates:
- https://github.com/sourcegraph/sourcegraph/blob/master/cmd/repo-updater/repos/scheduler.go

**Comment by tsenart** [comment]
@mrnugget: We should triage this in the next @sourcegraph/core-services meeting.

**Comment by mrnugget** [comment]
Just discussed this with @ryanslade. Since this is a pretty open-ended ticket, we think a first clear goal would be to stop syncing _every_ changeset (requiring 2 requests for Bitbucket Server!) _every_ 2 minutes. We should feel comfortable telling customers to enable this on their own instances.

**Comment by tsenart** [comment]
cc @keegancsmith

**Comment by keegancsmith** [comment]
> cc @keegancsmith. Heuristic syncing of repos could be a thing too.

For repos the issue is detecting deletions. But that could happen at a much lower cadence / could be input from a `git fetch` failing in our update scheduler. We actually used to use a few of these sort of heuristics in our old repo "syncer". But yeah if we have some concrete ideas it should be possible thanks to `SyncSubset`.

**Comment by ryanslade** [comment]
One fairly simple change for GitHub would be to request the UpdatedAt field for all PR's in open campaigns and compare that with our UpdatedAt field. Surely that would trim down the number of changesets we need to sync significantly?

**Comment by tsenart** [comment]
> would be to request the UpdatedAt field for all PR's in open 

Wouldn't requesting this from the API for defeat the purpose of heuristic syncing? We're trying to avoid having to make these requests in the first place, or at least make them in a smart order.

**Comment by ryanslade** [comment]
Sure, but it's one request up front that would then reduce the number of syncs we need to make overall

**Comment by tsenart** [comment]
It's only one request if the code host API supports fetching this information in one request. This is not the case for Bitbucket Server, for instance.

**Comment by ryanslade** [comment]
Yep, I did mention this was only for GitHub :)

**Comment by keegancsmith** [comment]
Is there a "global" endpoint for events for each code host we support? Is there some sort of ordering guarantees on these events?

FYI in the past we relied on GitHub's UpdatedAt field, but it was unreliable. IE don't use timestamps in distributed systems if what you want is an serial counter :)

Given we want to do this for all codehosts, we likely will not have a full proof way to always do this quickly. Instead in our architecture we should design in "quick and mostly accurate", but fallback to "slow and accurate". The fallback happens periodically + there is a way for a user to trigger the slow sync.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.13 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by ryanslade** [comment]
A data point:

GitHub allows 5000 "points" per hour via the GraphQL API, our current pr query uses 28 points so that would limit us to only about 1 sync every 25 seconds.

Looking a bit more into this, most of that overhead seems to come from CheckSuites, if they are removed it goes down to 3 points.

**Comment by mrnugget** [comment]
This just occurred to me: when I thought of "heuristic syncing" I assumed that it also includes throttling when webhooks are activated. Now I read this issue again and realized that we didn't mention webhooks.

Do we want to tackle that separately? Do we need it? (I think we need it to roll it out for customers)

**Comment by tsenart** [comment]
@ryanslade and I talked about the necessity of incorporating rate limit state into the scheduling logic. I think this would be part of that.
