### ISSUE TITLE
5.5.1337 Security approval

### ISSUE THREAD

**Issue by craigfurman** [sourcegraph/sourcegraph#63908]
Security must close this issue before releases. It is the responsibility of the Security Engineer on rotation the week the release is cut. More steps will be added in the future.

- [ ] All feasible CVEs are closed.
- [ ] Any open CVEs are documented in the handbook.

cc @sourcegraph/security

**Comment by willdollman** [comment]
Approved! Couple of CVEs which shouldn't affect us and we'll fix in the next release - I'll document.
