### ISSUE TITLE
a8n: Implement `createCampaign` for Campaigns with a CampaignPlan

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#6403]
This is part of [RFC 42](https://docs.google.com/document/d/1j85PoL6NOzLX_PHFzBQogZcnttYK0BXj9XnrxF3DYmA/edit). Read [this section](https://docs.google.com/document/d/1j85PoL6NOzLX_PHFzBQogZcnttYK0BXj9XnrxF3DYmA/edit#bookmark=id.kthik89mqpoe) details.

When the `createCampaign` mutation is called with a `CampaignPlan` ID the following needs to happen:

- The `Diff`s of the `CampaignPlan`'s `CampaignJobs` are turned into commits in their respective repositories
- Commits are made by a Sourcegraph bot
- These newly created commits are pushed up to the codehost
- The newly created commits are turned into pull requests on the code hosts
- On the Sourcegraph side, these new pull requests are turned into `Changeset`s
- While this is happening asynchronously, the user can query `campaignResolver.ChangesetCreationStatus`

---

### Technical Notes

(These do not cover everything in this issue, but are more of a braindump to help with the implementation)

The starting point is the `CreateCampaign` resolver [here](https://github.com/sourcegraph/sourcegraph/blob/b2a844dc7762146c9cf0ccdac2172bbfdbbb9259/enterprise/pkg/a8n/resolvers/resolver.go#L160).

This ticket is about the case where a `CampaignPlanID` is given in the arguments. If none is given, the existing code is executed.

If a CampaignPlan is given, we need to:
- load the `CampaignPlan`
- check that it's finished executing its `CampaignJob`
- load all `CampaignJobs`
- create commits from `CampaignJobs`

#### Diff to commit

The `Diff`, `RepoID`, `Rev` fields on  `CampaignJob` should be enough create a commit by talking to `gitserver`. Maybe we can use [`CreateCommitFromPatch`](https://github.com/sourcegraph/sourcegraph/blob/8e8790d144733d2dc83ba8d758a2f997e63868fe/internal/gitserver/client.go#L800-L817) on the `gitserver.Client` for this. Maybe it needs to be extended.

Commits should probably all be created under `sourcegraph/*` branches or any other naming scheme that's explicit.

After the commit is created, we need functionality in `gitserver` to push the newly-created branch.

We also need to make sure that the newly-created branch/commit is not cleaned up by `gitserver'`s GC processes before we push it.

#### Creating Pull Requests

Once the commit/branch have been pushed, we need to use a `CreatePullRequest` method on the code host clients to create a pull request from branch/commit.

At the time of writing, these have not been implemented yet.

#### Pull requests to Changesets

Each created pull request needs to be turned into a `Changeset` and added to the `Campaign`.

#### Retrying

Keep in mind that `Creating Pull Requests` and `PUll requests to Changesets` might fail and that the whole process of `CampaignJobs -> Pull Requests & Changesets` need to be idempotently retryable. This issue here does _not_ cover the retry-functionality, but it is something to keep in mind.

#### Clean up?

After the `CampaignJobs` have been successfully turned into `Changesets`, we probably want to "freeze" (or even clean up?) the `CampaignJobs`.

**Comment by tsenart** [comment]
> check that it's finished executing its CampaignJobs

If this is not true at the time the client calls `createCampaign` with a `CampaignPlan` id, we can't proceed in creating branches in git-server and everything that follows, which makes me think this needs to be processed, again, as some sort of background job pulled from a durable queue.

I'm thinking that repo-updater can periodically load all pending campaign jobs that have an associated campaign (via a campaign plan) and process them then.

**Comment by tsenart** [comment]
Well, actually, the documentation in the schema says the mutation should error if the plan hasn't completed yet, so I guess that makes things simpler.

https://github.com/sourcegraph/sourcegraph/blob/master/cmd/frontend/graphqlbackend/schema.graphql#L436
