### ISSUE TITLE
Site init page shows in dark theme if OS dark theme is enabled

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#6420]
In macOS if you have the systemwide dark theme enabled, the site init page shows up in a dark theme because the default theme behavior is to match the system's behavior. This is a problem because the site init page is not designed to look good in the dark theme.

Fix: make the site init page look good with a dark theme

![image](https://user-images.githubusercontent.com/1976/68164231-32018c80-ff11-11e9-96fa-e1ae0262c6c9.png)

**Comment by dadlerj** [comment]
Saw this happen to https://app.hubspot.com/contacts/2762526/company/2974417760 during a setup call
