### ISSUE TITLE
v5.5.3956 Security approval

### ISSUE THREAD

**Issue by DaedalusG** [sourcegraph/sourcegraph#64231]
Security must close this issue before releases. It is the responsibility of the Security Engineer on rotation the week the release is cut. More steps will be added in the future.

- [ ] All feasible CVEs are closed.
- [ ] Any open CVEs are documented in the handbook.

cc @sourcegraph/security

**Comment by shivasurya** [comment]
Scanned manually no new CVEs reported. please consider this as approved
