### ISSUE TITLE
Missing prometheus metrics

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#6428]
This is a list of metrics that do not exist and would be helpful in debugging customer issues:

- [ ] # of repositories that are indexed, unindexed, indexing
- repo cloning
  - [x] # of repositories that are cloning -> `src_gitserver_clone_queue `
  - [x] # of repositories that have cloned since gitserver started -> `src_gitserver_clone_queue `
  - [ ] # of repositories that are not cloned on the instance overall
  - [ ] # of repositories that are cloned on the instance overall
- [ ] Total memory & CPU available to container/host-machine in sourcegraph/server deployments
- [ ] Network / disk IO in sourcegraph/server deployments
- [x] # of HTTP requests made to Sourcegraph by status code (`src_http_request_duration_seconds` is a histogram and has `src_http_request_duration_seconds_count`)
- [ ] # of GraphQL requests made by (type, field) -- current histogram doesn't cover this
- [ ] # of searches hitting zoekt vs. searcher
- [ ] # of symbol searches hitting zoekt vs. symbols
- [ ] # of diff/commit searches
- [ ] # of searches hitting indexed vs. unindexed branches

**Comment by uwedeportivo** [comment]
# of repositories that are cloned, not cloned, cloning:

src_gitserver_repo_cloned, src_gitserver_clone_queue

**Comment by slimsag** [comment]
`src_gitserver_repo_cloned` appears to be the number of repos that _have been cloned since gitserver started_, not the # that are cloned on the instance period

![image](https://user-images.githubusercontent.com/3173176/68349785-8d6f7e00-00bb-11ea-8ab1-44b58c06623e.png)

**Comment by slimsag** [comment]
I broke out that section into four bullets to indicate the two missing metrics

**Comment by uwedeportivo** [comment]
Cool, thanks

**Comment by uwedeportivo** [comment]
each histogram has a counter: src_http_request_duration_seconds_count should do it.

**Comment by slimsag** [comment]
Nice, we should perhaps declare rules to make that more obvious, so that `src_http_request_count` maps to that for each relevant histogram?

**Comment by slimsag** [comment]
Closing this issue.

> # of repositories that are indexed, unindexed, indexing

Superseded by:

- https://github.com/sourcegraph/sourcegraph/issues/9790
- https://github.com/sourcegraph/sourcegraph/issues/9789
- https://github.com/sourcegraph/sourcegraph/issues/9783
- https://github.com/sourcegraph/sourcegraph/issues/9782

> # of repositories that are not cloned on the instance overall

Superseded by https://github.com/sourcegraph/sourcegraph/issues/9837

> # of repositories that are cloned on the instance overall

Not useful / can't be alerted on.

> - Total memory & CPU available to container/host-machine in sourcegraph/server deployments
> - Network / disk IO in sourcegraph/server deployments

No longer a goal with Docker Compose deployments existing.

> # of GraphQL requests made by (type, field)

Superseded by https://github.com/sourcegraph/sourcegraph/issues/9797

> - # of searches hitting zoekt vs. searcher
> - # of symbol searches hitting zoekt vs. symbols

Superseded by https://github.com/sourcegraph/sourcegraph/issues/9838

> # of diff/commit searches

Superseded by https://github.com/sourcegraph/sourcegraph/issues/9744

> # of searches hitting indexed vs. unindexed branches

Superseded by https://github.com/sourcegraph/sourcegraph/issues/9838

> # that are cloned on the instance period

Already present in new monitoring via clone queue size (which effectively communicates the same thing).
