### ISSUE TITLE
Docs sidebar nav not updated?

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#6429]
After https://github.com/sourcegraph/sourcegraph/pull/6301 was merged, I expected the side nav bar to look like this (from local dev on latest master):

![image](https://user-images.githubusercontent.com/5589410/68178012-2331ce80-ff3f-11e9-85da-e5eeed45df3a.png)

But on docs.sourcegraph.com, it looks like this:

![image](https://user-images.githubusercontent.com/5589410/68178021-2fb62700-ff3f-11e9-802c-cc294402ec5c.png)

Is some sort of cache busting required here?

**Comment by rvantonder** [comment]
Also happened with #8853, #8958. Related to #8897.

**Comment by unknwon** [comment]
I guess this is the root cause: https://github.com/sourcegraph/sourcegraph/issues/7336

**Comment by rvantonder** [comment]
Deleting the pod is not a sustainable solution. Documenting that is just a bandaid. There's got to be a better way to solve it...

**Comment by rvantonder** [comment]
Maybe we can add something to dot-com deploy to do this automatically.

**Comment by unknwon** [comment]
Yeah, I think @ryan-blunden has plan to write a simple cron job to do that as a short-term fix.

**Comment by ryan-blunden** [comment]
Because docsite loads the templates and assets into a virtual file system, replacing the Pod via a metadata change in the deployment YAML is the only way I can't think of right now to achieve this.

> Maybe we can add something to dot-com deploy to do this automatically.

I think the solution is going to be along those lines.

**Comment by ryan-blunden** [comment]
@sqs Any ideas?

I was hoping to be able to run docsite in a Pod the same way we do locally where the path to the assets and templates is local file path. That way, the assets and templates could be in a shared volume that docsite reads from and a separate container in the Pod is responsible for automatically pulling in changes from master.

**Comment by sqs** [comment]
This requires a Go code change in docsite to make it reload the data. I just haven’t gotten around to it yet and nobody else has either.
