### ISSUE TITLE
On private instances, use sourcegraph.com for open source code intelligence and fallback search results

### ISSUE THREAD

**Issue by Warchant** [sourcegraph/sourcegraph#643]
#### Question description

I use sourcegraph chrome extention. In settings, I specify URL of my private hosted sourcegraph. 
Hosted sourcegraph has several private repos cloned, so I can easily use all available features, everything works as expected for those repos.
However, public repos are not cloned and code intelligence does not work for them.

And here is the question - how to enable code intelligence on hosted sourcegraph for both private and public repos without cloning all of used public repos?

##### Solution 1

Clone public repos on hosted sourcegraph. 

Downsides are:
- I can't use standard queries like `type:diff repo:@*refs/heads/ \/\/\s*(TODO|BUG|FIXME)` only for my private projects (result will contain all projects, including public)
- potentially me and my team can observe hundreds of public repos, I do not want to clone all of them just to enable sourcegraph. Also, not everyone in my team has access to do so (so for admin it is some extra work).

##### Solution 2

Depending on usage, change URL. For public repos I use `https://sourcegraph.com`, and for private repos I use my private URL.

Downsides are:
- UX is not good - some extra work to do
- there is no option to select pre-configured URL, just option to type it (extra work)

----

Or maybe there is a way to use multiple URLs at the same time? Or maybe I am missing something?

**Comment by ryan-blunden** [comment]
> I can't use standard queries like type:diff repo:@*refs/heads/ \/\/\s*(TODO|BUG|FIXME) only for my private projects (result will contain all projects, including public)

Searching a specific subset of repositories can be achieved by adding a repository group and a corresponding search scope in your Site admin > Global settings. Example below

```json
"search.repositoryGroups": {
    "k8s": [
      "github.com/kubernetes/kubernetes",
      "github.com/kubernetes/heapster",
      "github.com/kubernetes/contrib",
      "github.com/kubernetes/dashboard"
    ]
}
```

Add a search scope:

```json
"search.scopes": [
	{
	    "id": "k8s",
	    "name": "Kubernetes",
	    "value": "repogroup:k8s"
	}   "description": "Search Kubernertes core repositories"
]
```

Yes, this will mean you are cloning public repositories to your local instance. If this is not feasible, then Solution 2 will is the way to go.

**Comment by christinaforney** [comment]
We just got this request from a customer, and @mrnugget brought this up as a hackweek idea. The ability to have code intelligence (and to be able to fall back to searching open source code) from a private sourcegraph instance could be useful to many customers. I'll start asking around to get a sense of importance with more of our customers for prioritization.

**Comment by lguychard** [comment]
Retagged as feature request. For context on the reasons behind the removal of the original fallback logic, see https://github.com/sourcegraph/sourcegraph/issues/3233

**Comment by slimsag** [comment]
A prospective customer asked for this functionality just now: https://sourcegraph.slack.com/archives/CMT39K56Z/p1574297247213800

**Comment by christinaforney** [comment]
We just got another request for this feature. I'll be prioritizing this with the @sourcegraph/web team on Monday.

**Comment by ryan-blunden** [comment]
Another request from a potential customer who wants to search open source third party dependencies without individually listing the open source repositories on their private instance.

**Comment by sqs** [comment]
A user at https://app.hubspot.com/contacts/2762526/company/407948923 just requested this (by email to me).

**Comment by efritz** [comment]
An effort to solve this for code intel can be tracked in https://github.com/sourcegraph/sourcegraph/issues/13137.

**Comment by slimsag** [comment]
We are investigating implementing the code intelligence (but not search) angle of this in https://github.com/sourcegraph/sourcegraph/issues/13137

Also requested by https://app.hubspot.com/contacts/2762526/company/1712860829/ and https://app.hubspot.com/contacts/2762526/company/554275594/

**Comment by dadlerj** [comment]
Requested by https://app.hubspot.com/contacts/2762526/company/814799425 just now: https://sourcegraph.slack.com/archives/CKMSNT9C0/p1599167802010600

**Comment by nickatsegment** [comment]
I'm running v 20.7.31.225, which appears to be current. The behaviour I see when clicking a symbol in a repo that my private instance does not index (an OSS one) is that nothing pops up and there's an error in the console. This has the potential to confuse users significantly. Maybe in the meantime, we can surface that error and explain that it's currently not supported and link to this ticket or something?

Alternatively, maybe if the request fails we can fallback to the Github popover?

(I'm very much guessing at how much trouble these things would be to implement vs the eventual correct solution.)

**Comment by efritz** [comment]
> The behaviour I see when clicking a symbol in a repo that my private instance does not index (an OSS one) is that nothing pops up and there's an error in the console.

There shouldn't be an error in this case - may be an orthogonal issue. Could you share the error here?

**Comment by nickatsegment** [comment]
@efritz Browsing https://github.com/crewjam/saml/blob/master/samlsp/session.go, I see this:

![image](https://user-images.githubusercontent.com/40582825/92507836-74909700-f1bc-11ea-93a5-2ea7fe9ff931.png)

Everything works fine using the `sourcegraph.com` URL.

And I was wrong about something: I don't get that error on click, but rather on page load.

**Comment by efritz** [comment]
Ah I see. Your browser extension is pointing at your private instance?

**Comment by nickatsegment** [comment]
@efritz Correct. Updated.

**Comment by efritz** [comment]
Alright. I'm going to be jumping onto https://github.com/sourcegraph/sourcegraph/issues/13137 sometime this milestone to design a fallback solution for code intelligence. Once I draft a proposal I'll post it there if you'd like updates.

**Comment by sfllaw** [comment]
As a customer, we'd also like to see this implemented. We'd be able to get rid of a lot of junk imports in our private Sourcegraph instance.

**Comment by jjinnii** [comment]
@Warchant @sfllaw Thanks for your feedback! My name is Sara, and I'm a Product Designer here at Sourcegraph.

I'm working on some new designs to tackle this very issue, and I would appreciate the opportunity to run these designs by you in a 30-minute user testing session! You can learn more about how we conduct user testing sessions [here](https://about.sourcegraph.com/handbook/product/user_research/user_research_participant). 

If that sounds okay to you, please select a date and time that works best, using [this Calendly link](https://calendly.com/sara-lee-sg/30min?month=2021-09). And please let me know if none of these times work for you. 

Thanks again!

**Comment by erzhtor** [comment]
@jjinnii, @muratsu, do you think we can close this since we shipped the other alternative solution https://github.com/sourcegraph/sourcegraph/issues/29030?
