### ISSUE TITLE
Remove repo.indexed_revision and repo.freeze_indexed_revision columns

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#644]
In January 2019, we can remove these DB columns (which were made unnecessary by https://github.com/sourcegraph/sourcegraph/pull/584). We need to keep them until January 2019 for backcompat (so that the DB schema is backcompat between 3.0 and 3.1).

**Comment by nicksnyder** [comment]
Why can't we remove these before 3.0?

**Comment by sqs** [comment]
To support online migrations/upgrades (if we removed them, the old pods would have all their repo table queries fail).

If we don’t want to support online migrations, then we can remove them. That’d be fine, but let’s not make a habit of it (most releases should probably support online upgrades).

**Comment by nicksnyder** [comment]
I think we should defer this issue until _after_ we release a version of Sourcegraph that _all_ customers can upgrade to. Certain existing customers won't be able to upgrade until 3.2 at the earliest (pending scoping decisions), so the earliest we should remove this is 3.3.

**Comment by tsenart** [comment]
Makes sense @nicksnyder. Let's postpone.
