### ISSUE TITLE
Bug/confusion: Code Search result > source code lines  in the same file are out of order

### ISSUE THREAD

**Issue by peter-kehl** [sourcegraph/sourcegraph#64404]
- **Sourcegraph version:** current online https://sourcegraph.com/search

#### Steps to reproduce:

1. https://sourcegraph.com/search?q=%28always_abort%29+%28lang%3ARust%29&patternType=keyword&sm=0
2. that is the same as a (case insensitive) query: `(always_abort) (lang:Rust)`

#### Expected behavior:
In the list of lines from the same file have the sets of line sorted in ascending order. Or, if it's based on some other ordering criteria, make it known/obvious, and if possible, configurable.

#### Actual behavior:
Lines 408-412. and THEN lines 389+ from the same file:
![image](https://github.com/user-attachments/assets/adf59296-228e-44a1-9f5b-3b469c42af2c)

**Comment by peter-kehl** [comment]
Thank you, indeed, for SourceGraph. You rule!

**Comment by keegancsmith** [comment]
We use ranking and do not currently offer a way to turn it off. So the chunk shown first we regard as more important since it is a hit on the function definition, instead of just a mention in a comment.

**Comment by camdencheek** [comment]
We do actually support overriding the default intra-file ranking behavior. You can add this to your settings to override the ranking to always show chunks in line number order:

```
{
  "experimentalFeatures": {
    "clientSearchResultRanking": "by-line-number"
  }
}```
