### ISSUE TITLE
Explore alternatives to Reactstrap

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#6443]
We often get bugs from upgrading `reactstrap`. We should look into alternatives that might be more stable.

More info: https://sourcegraph.slack.com/archives/CMT39K56Z/p1572977510044700?thread_ts=1572977413.044200&cid=CMT39K56Z

/cc @taylorsperry @muratsu

**Comment by lguychard** [comment]
Reach UI might be an alternative.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by valerybugakov** [comment]
We replaced almost all `reactstrap` usages with Wildcard components. The remaining work will be done in https://github.com/sourcegraph/sourcegraph/issues/41630.
