### ISSUE TITLE
Go langserver+buildserver without lsp-proxy

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#647]
This issue tracks the progress of getting the Go langserver to work directly through a Sourcegraph extension, without lsp-proxy but still with a connection to gitserver.

- [x] Implement `-mode=websocket` in go-langserver
- [x] Copy buildserver code from sourcegraph/sourcegraph to go-langserver
- [ ] Cut `github.com/sourcegraph/sourcegraph` imports from buildserver code
- [ ] PR to go-langserver: TODO add link
- [ ] PR to remove buildserver code from sourcegraph/sourcegraph: TODO add link

Hovers/defs/refs/impls are working. I tested on gorilla/mux and kubernetes/kubernetes.

**Comment by sqs** [comment]
Closing in favor of #958 (which is being actively updated)
