### ISSUE TITLE
experimental repohascommitafter feature broken (invalid git syntax)

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#6475]
https://k8s.sgdev.org/search?q=errorf+repohascommitafter:%223+days+ago%22&patternType=literal shows:

![image](https://user-images.githubusercontent.com/3173176/68330462-8d0dbd80-0090-11ea-8d81-477d5c928a1c.png)

Reported by https://app.hubspot.com/contacts/2762526/company/407948923

**Comment by unknwon** [comment]
Seems an easy fix based on the error message, just need to find out which line of the code.

**Comment by kzh** [comment]
This might have been due to #5991 (also related: #5892). It seems that only instances with newly cloned repository will avoid running into this issue.

**Comment by slimsag** [comment]
This appears to happen anytime an _empty_ repository would be searched.

This is very easy to reproduce locally via `./enterprise/dev/start.sh` with the query http://localhost:3080/search?q=errorf+repohascommitafter:%227+days+ago%22&patternType=literal

In specific, it can be reproduced because we have these two empty test repositories in our dev environments:

- http://localhost:3080/git-codecommit.us-west-1.amazonaws.com/empty-repo
- http://localhost:3080/git-codecommit.us-west-1.amazonaws.com/__WARNING_DO_NOT_PUT_ANY_PRIVATE_CODE_IN_HERE

Probably this should be bubbled up by `git.HasCommitAfter` as a `gitserver.IsRevisionNotFound(err)` detectable error. What do you think @kzh ?

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.10 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by slimsag** [comment]
Fixed by https://github.com/sourcegraph/sourcegraph/pull/5864
