### ISSUE TITLE
Backend returns invalid filter chip with space "lang:ignore list"

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#6498]
![2019-11-07 22 58 57](https://user-images.githubusercontent.com/10532611/68431342-41533500-01b2-11ea-897a-95ee0ebb306b.gif)

Customers:
- https://app.hubspot.com/contacts/2762526/company/419771425

**Comment by unknwon** [comment]
Query to reproduce: https://sourcegraph.com/search?q=repo:github%5C.com/sourcegraph/sourcegraph-extension-samples+f:Dockerfile&patternType=literal

**Comment by ikonst** [comment]
The "lang:protocol buffer" filter button also results in a broken behavior.

**Comment by keegancsmith** [comment]
My fix in https://github.com/sourcegraph/sourcegraph/pull/7031 actually didn't work as we have realised in https://github.com/sourcegraph/sourcegraph/pull/7620

I think the escaping actually needs to happen in the frontend, or the schema needs to expose a field where the frontend doesn't create the search token.

**Comment by tsenart** [comment]
Estimate: 0.5 days

**Comment by tsenart** [comment]
Changed the estimate according to @rvantonder's input. He needs to load up context on frontend and is being conservative about it :)

**Comment by rvantonder** [comment]
Fixed in #8276
