### ISSUE TITLE
Support sending traces to Datadog

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#650]
Currently Sourcegraph supports sending traces and logging to [Sentry and LightStep](https://docs.sourcegraph.com/admin/monitoring_and_tracing#monitoring-and-tracing). We should also support Datadog.

Requested by:
- https://app.hubspot.com/contacts/2762526/company/561806411

**Comment by daxmc99** [comment]
We are removing Datadog tracing to focus on OpenTelemetry https://github.com/sourcegraph/sourcegraph/issues/27386
