### ISSUE TITLE
Redis AOF database corruption

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#651]
We received reports that the single-node Docker image's (version 2.12.3) Redis server sometimes needs manual recovery after a crash or power cycle. This problem manifests when Sourcegraph does not come back online after the crash. The admin SSH'd in and saw that the sourcegraph/server container's Redis server was reporting errors and required manual recovery steps. The manual recovery steps worked, but:

- Why were they necessary? Is it possible to run Redis with stricter journaling or fsyncing so that it can't get into this state?
- Is it possible to run the recovery steps automatically?

**Comment by tsenart** [comment]
Two ideas:

1. Remediate: Automatically run `redis-check-aof --fix appendonly.aof` on startup (if possible).
2. Fix: Investigate and tune our Redis setup to avoid this issue in the first place.

**Comment by keegancsmith** [comment]
> Remediate: Automatically run redis-check-aof --fix appendonly.aof on startup (if possible).

This sounds very simple, and from the description of `redis-check-aof` should be performant if there isn't much data in the oaf file (I expect the common case?). Lets do this!

> Fix: Investigate and tune our Redis setup to avoid this issue in the first place.

What do you think is wrong here? My intuitions tell me that this is the orchestrator coming in and killing it too quickly so there might not be much to do here.

**Comment by keegancsmith** [comment]
Couldn't help myself given the simple fix, see https://github.com/sourcegraph/sourcegraph/pull/6230

**Comment by tsenart** [comment]
> redis-check-aof should be performant if there isn't much data in the oaf file (I expect the common case?). Lets do this!

Unfortunately we know that some customers have a very large AOF file. This is something we wanted to fix by running [BGREWRITEAOF](https://redis.io/commands/bgrewriteaof) on server image startup. See this issue for more context: https://github.com/sourcegraph/sourcegraph/issues/3300

**Comment by tsenart** [comment]
> What do you think is wrong here? My intuitions tell me that this is the orchestrator coming in and killing it too quickly so there might not be much to do here.

- More graceful shutdown (?)
- More frequent fsyncs
