### ISSUE TITLE
Repo page polling doesn't unsubscribe correctly

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#6512]
- **Sourcegraph version:** latest master
- **Platform information:** macOS Catalina

#### Steps to reproduce:

1. Go to repository page of a repo that's still cloning
2. Navigate to another page
3. See polling requests still happening in chrome devtools (`ResolveRev` requests)

#### Expected behavior:

Unsubscribed correctly

#### Actual behavior:

Still polling

**Comment by felixfbecker** [comment]
Verified this no longer happens on https://sourcegraph.com/github.com/sourcegraphtest/AlwaysCloningTest

**Comment by eseliger** [comment]
ah sorry I meant to close this issue a while ago 🤦‍♂
