### ISSUE TITLE
TypeScript code intelligence misses references between web/ and shared/

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#6516]
Repro:
* Create a new instance of Sourcegraph, enable precise TypeScript code intelligence with the TS language server, add github.com/sourcegraph/sourcegraph to the instance.
* Go to https://sourcegraph.com/github.com/sourcegraph/sourcegraph@381d8101329a2b10188c4335b8fae728ac3c3e01/-/blob/shared/src/settings/edit.ts#L77:11&tab=references
* Note the two references found for `overwriteSettings`
* Go to `/github.com/sourcegraph/sourcegraph@381d8101329a2b10188c4335b8fae728ac3c3e01/-/blob/web/src/settings/SettingsPage.tsx#L54:23`. Note that this reference did not appear in the previous references list. Click go-to-definition on `overwriteSettings`.
* That should bring you to `/github.com/sourcegraph/sourcegraph@381d8101329a2b10188c4335b8fae728ac3c3e01/-/blob/shared/src/settings/edit.ts#L127:17`. Click "Find references"
* Observe that more references now show up. If you go back to `/github.com/sourcegraph/sourcegraph@381d8101329a2b10188c4335b8fae728ac3c3e01/-/blob/shared/src/settings/edit.ts#L77:11&tab=references` and refresh, you'll see more references pop up there, as well.

Could this be due to the fact that `shared/` and `web/` have separate `package.json`s?

**Comment by felixfbecker** [comment]
It is because they are separate projects (separate tsconfig.json). I think #6053 should fix this

**Comment by felixfbecker** [comment]
#6053 did in fact not fix this. This would be an upstream issue then that needs to be filed ("tsserver does not return cross-project references with composite projects")

**Comment by efritz** [comment]
Closing as this is is a language server-specific issue and we're dropping support (see [RFC 139](https://docs.google.com/document/d/1dl5u03dD63-RZB7S1p2IqFTiVcdx6On0aeIOXgsTehA)).
