### ISSUE TITLE
Add query builder

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#652]
Many other code search tools have multiple input fields to help users construct their query. Sourcegraph currently requires users to use the [search query syntax](https://docs.sourcegraph.com/user/search/queries#search-query-syntax) (such as `repo:foo`, `file:foo`).

We should add a (possibly optional) UI for this, to make it easier for users who are not familiar with the query syntax or who prefer an easier interface. (We actually used to have this.)

![screenshot from 2018-11-02 14-36-20](https://user-images.githubusercontent.com/1976/47941751-aba10d80-deac-11e8-852c-b4b3eecb0026.png)
![screenshot from 2018-11-02 14-36-43](https://user-images.githubusercontent.com/1976/47941771-b9569300-deac-11e8-8871-53d8ddae06e1.png)

**Comment by keegancsmith** [comment]
yup this should be a good way to teach people the syntax. :+1:

**Comment by sqs** [comment]
For simplicity, this query builder would NOT have 2-way binding with the query input field.

**Comment by attfarhan** [comment]
Merged https://github.com/sourcegraph/sourcegraph/commit/a8080d17a5019537b4e8b5b5522a3c11fd0e5f3c
