### ISSUE TITLE
GitLab: hover tooltip z-index issues

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#6520]
Reported on the GitLab MR: https://gitlab.com/gitlab-org/gitlab/merge_requests/16556#note_242204935

"It looks like the Sourcegraph popover floats above everything which is obvious when scrolling."

**Comment by felixfbecker** [comment]
This may also not be an issue with `z-index`, but with the `relativeElement` we give Gitlab (which would also be the reason why we have the `adjustPosition` kludge and #6495)

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.10 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.11 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by lguychard** [comment]
Closed in #7023
