### ISSUE TITLE
Browser extension not working when sourcegraphURL has a trailing slash

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#6521]
Works correctly when there is no trailing slash:
![image](https://user-images.githubusercontent.com/1741180/68527256-3d73ff80-02e5-11ea-8ea5-a61b7bf40a09.png)

Fails with unhelpful hints when there is a trailing slash:
![image](https://user-images.githubusercontent.com/1741180/68527260-46fd6780-02e5-11ea-96a1-be37759a4207.png)

We should gracefully handle the URL containing a trailing slash, or at the very least tell the user what the actual issue is.

**Comment by felixfbecker** [comment]
The options page should use `new URL()` to validate and canonicalize the URL

**Comment by lguychard** [comment]
This would also help not mishandling the URL: https://github.com/sourcegraph/sourcegraph/issues/3990

**Comment by dadlerj** [comment]
Reported by a user at https://app.hubspot.com/contacts/2762526/company/557476528 that ran into this today: https://sourcegraph.slack.com/archives/C0117QDJACU/p1586987397001600

**Comment by felixfbecker** [comment]
https://app.hubspot.com/contacts/2762526/company/974120254 ran into this as well,  https://sourcegraph.slack.com/archives/CMT39K56Z/p1587159903175600?thread_ts=1586798352.127800&cid=CMT39K56Z

**Comment by dadlerj** [comment]
Just hit by _another_ user at https://app.hubspot.com/contacts/2762526/company/557476528 a moment ago

**Comment by lguychard** [comment]
Fixed in browser extension v20.5.6.835. For native integrations, the fix will roll out in 3.16.
