### ISSUE TITLE
Support displaying arbitrary Markdown on the /search page

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#653]
The primary use case is for site admins to post useful messages/notifications/tips for users and possibly links to common repos and searches. This is like the motd setting but shown on the homepage instead of in the global nav alert banner.

One possible impl: Extensions can contribute Markdown to the panel and the explore area. They should also be able to contribute Markdown that is displayed on the homepage.

**Comment by KattMingMing** [comment]
We also have: https://github.com/sourcegraph/sourcegraph/issues/2442 and https://github.com/sourcegraph/sourcegraph/issues/2443 issues open – @sqs does your PR resolve either of these?

If not, should we prioritize?

**Comment by sqs** [comment]
@KattMingMing It pertially resolves #2443 (added comment there).  I have both of these issues listed in the updated roadmap at https://github.com/sourcegraph/sourcegraph/pull/2932 BTW, so they will be prioritized.
