### ISSUE TITLE
a8n: Don't create changeset when ID is invalid

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#6535]
#### Steps to reproduce:

1. Go to campaigns
2. Add a changeset manually, using a _not_ existing ID
3. See dev stack log output

#### Expected behavior:
The error is thrown and it's forgotten about.

#### Actual behavior:
The changeset still get's created and is getting synced over and over again, logging messages like the below: 

```
repo-updater | ERROR PreSync, error: error in GraphQL response: Could not resolve to a PullRequest with the number of 65526.
```

**Comment by mrnugget** [comment]
I cannot reproduce this:

<img width="1182" alt="Screen Shot 2019-11-14 at 10 46 52" src="https://user-images.githubusercontent.com/1185253/68845711-1eea7b80-06cc-11ea-81e9-f8589b04eae9.png">
<img width="1189" alt="Screen Shot 2019-11-14 at 10 46 36" src="https://user-images.githubusercontent.com/1185253/68845720-21e56c00-06cc-11ea-8ac0-b68db235a55e.png">

Can you maybe provide the exact repository and number that you used?

**Comment by mrnugget** [comment]
Nevermind, I see the error now:

```
10:48:26           repo-updater | ERROR ChangesetSyncer, error: Bitbucket API HTTP error: code=404 url="https://bitbucket.sgdev.org/rest/api/1.0/projects/SOUR/repos/automation-testing/pull-requests/999" body="{\"errors\":[{\"context\":null,\"message\":\"Pull request 999 does not exist in SOUR/automation-testing.\",\"exceptionName\":\"com.atlassian.bitbucket.pull.NoSuchPullRequestException\"}]}"
10:48:26           repo-updater | ERROR PreSync, error: Bitbucket API HTTP error: code=404 url="https://bitbucket.sgdev.org/rest/api/1.0/projects/SOUR/repos/automation-testing/pull-requests/999" body="{\"errors\":[{\"context\":null,\"message\":\"Pull request 999 does not exist in SOUR/automation-testing.\",\"exceptionName\":\"com.atlassian.bitbucket.pull.NoSuchPullRequestException\"}]}"
```
