### ISSUE TITLE
Rev not found error for commits that exist on code host

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#6539]
This is on https://sourcegraph.com/gitlab.com/felixfbecker/gitlab-ee@sourcegraph/-/commits :

![2019-11-11 18 43 05](https://user-images.githubusercontent.com/10532611/68608456-3ef32280-04b3-11ea-8f91-9b4362b9b914.gif)

It breaks the browser extension/native integration code intel on the MR, because it gets back a rev not found error from the backend:

![image](https://user-images.githubusercontent.com/10532611/68608505-62b66880-04b3-11ea-8115-b03bfcda450f.png)

I can even show files at that revision on Sourcegraph, but it does not show up in commit search and the extension gets a rev not found error.

**Comment by unknwon** [comment]
The quick answer is the `"query"` variable is used to search over _commit messages_ not _commit id_.

**Comment by felixfbecker** [comment]
I guess that was a red herring, then. This is the query failing from the browser extension:
```json
{
  "query": "\n                    query ResolveRev($repoName: String!, $rev: String!) {\n                        repository(name: $repoName) {\n                            mirrorInfo {\n                                cloned\n                            }\n                            commit(rev: $rev) {\n                                oid\n                            }\n                        }\n                    }\n                ",
  "variables": {
    "repoName": "gitlab.com/gitlab-org/gitlab",
    "rev": "ee421052dfd907c499172c213202c5d91fb6eb0a"
  }
}
```

https://sourcegraph.com/github.com/sourcegraph/sourcegraph@0e90e7f4ed2bcbb79e2f58a83250e0341da675cb/-/blob/browser/src/shared/repo/backend.tsx#L62:32

**Comment by felixfbecker** [comment]
Here's a direct repro in the API console: https://sourcegraph.com/api/console#%7B%22query%22%3A%22query%20ResolveRev(%24repoName%3A%20String!%2C%20%24rev%3A%20String!)%20%7B%5Cn%20%20%20%20repository(name%3A%20%24repoName)%20%7B%5Cn%20%20%20%20%20%20%20%20mirrorInfo%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20cloned%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20commit(rev%3A%20%24rev)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20oid%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%7D%22%2C%22variables%22%3A%22%7B%5Cn%20%20%20%20%5C%22repoName%5C%22%3A%20%5C%22gitlab.com%2Fgitlab-org%2Fgitlab%5C%22%2C%5Cn%20%20%20%20%5C%22rev%5C%22%3A%20%5C%2296462d8e77c8e896edefcdbd918f3aa3fbfcf43e%5C%22%5Cn%20%20%7D%22%7D

**Comment by unknwon** [comment]
This commit ID (I think) only exists in your fork of gitlab-ee@sourcegraph, so the `repoName` should be `gitlab.com/felixfbecker/gitlab-ee` not `gitlab.com/gitlab-org/gitlab`:  https://sourcegraph.com/api/console#%7B%22query%22%3A%22query%20ResolveRev(%24repoName%3A%20String!%2C%20%24rev%3A%20String!)%20%7B%5Cn%20%20%20%20repository(name%3A%20%24repoName)%20%7B%5Cn%20%20%20%20%20%20%20%20mirrorInfo%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20cloned%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20commit(rev%3A%20%24rev)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20oid%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%7D%22%2C%22variables%22%3A%22%7B%5Cn%20%20%5C%22repoName%5C%22%3A%20%5C%22gitlab.com%2Ffelixfbecker%2Fgitlab-ee%5C%22%2C%5Cn%20%20%5C%22rev%5C%22%3A%20%5C%2296462d8e77c8e896edefcdbd918f3aa3fbfcf43e%5C%22%5Cn%7D%22%7D

The commit does exist on https://gitlab.com/gitlab-org/gitlab/tree/96462d8e77c8e896edefcdbd918f3aa3fbfcf43e but it's possible hasn't been synced on sourcegraph.com yet.

I tried one they committed 4 years ago, and succeed: https://sourcegraph.com/api/console#%7B%22query%22%3A%22query%20ResolveRev(%24repoName%3A%20String!%2C%20%24rev%3A%20String!)%20%7B%5Cn%20%20%20%20repository(name%3A%20%24repoName)%20%7B%5Cn%20%20%20%20%20%20%20%20mirrorInfo%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20cloned%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20commit(rev%3A%20%24rev)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20oid%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%7D%22%2C%22variables%22%3A%22%7B%5Cn%20%20%5C%22repoName%5C%22%3A%20%5C%22gitlab.com%2Fgitlab-org%2Fgitlab%5C%22%2C%5Cn%20%20%5C%22rev%5C%22%3A%20%5C%22d3b62e683730df2d93a6c39f7c0da6bd24640ee3%5C%22%5Cn%7D%22%7D

**Comment by felixfbecker** [comment]
If a commit exists on the code host in the repo, it should be queryable from the Sourcegraph API. Any merge request rev is retrievable from `refs/merge-requests/$number` in the target repo (we can't use the base repo because we cannot assume that repo is on Sourcegraph). Furthermore, the browser extension code is built on the assumption that if a commit was not found, the backend will try to sync it first before giving up and returning the commit not found error. It's totally possible that a commit in an MR is not synced yet, since it is only in a hidden ref of the repo, and the `ResolveRef` call can happen before the commit is visited on Sourcegraph. That's why it's important that the backend always tries to fetch it first. It seems like the bug here is that the backend doesn't do that.

**Comment by unknwon** [comment]
> Furthermore, the browser extension code is built on the assumption that if a commit was not found, the backend will try to sync it first before giving up and returning the commit not found error.

Looking at the code path, I don't think it is happening. The API resolver only tries to what's already on the gitserver. But maybe I'm wrong, cc @nicksnyder @sourcegraph/core-services

**Comment by unknwon** [comment]
We have logic to trigger "auto sync" in the background for UI visits of a repository:

https://github.com/sourcegraph/sourcegraph/blob/cfd8220788c63f6815e484d6de34aae89c5b974f/cmd/frontend/internal/app/ui/handlers.go#L188-L191

To have the same trigger in the GraphQL APIs, we would potentially add it [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/repository.go#L121).

@nicksnyder: I would like to know was there any discussions around trigger background fetch with an API hit? i.e. did we have a reason to choose not to do or it's simply unhandled?

@felixfbecker: Even with this "auto sync" trigger, the first few API calls to get revisions will fail until the sync is completed in the background (similar behavior as when a user visits a repository on UI). Does this sound good to you?

**Comment by felixfbecker** [comment]
> Even with this "auto sync" trigger, the first few API calls to get revisions will fail until the sync is completed in the background (similar behavior as when a user visits a repository on UI). Does this sound good to you?

What do you mean with "fail"? It would be expected that it would return `cloneInProgress: true` (which is handled by the browser extension)

**Comment by unknwon** [comment]
@felixfbecker:
> It would be expected that it would return `cloneInProgress: true` (which is handled by the browser extension)

I agree, this [should be expected](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/repository_mirror.go#L93). I'll test afterwards to make sure.

**Comment by nicksnyder** [comment]
> @nicksnyder: I would like to know was there any discussions around trigger background fetch with an API hit? i.e. did we have a reason to choose not to do or it's simply unhandled?

AFAIK this has been the behavior for a long time and any discussion pre-dates my memory. If anyone has context, it is most likely to be @keegancsmith and/or @slimsag. 

My assumption is that the original motivation for this behavior is preventing a lot of load. We don't want to do a `git fetch` for every single graphql API call (e.g. our web app makes multiple per page). Our current solution/behavior might not be ideal and I remember complaints/confusion about it in the past. If we want to make changes here, I think this is RFC worthy.

> What do you mean with "fail"? It would be expected that it would return cloneInProgress: true (which is handled by the browser extension)

Note that the EnqueueRepoUpdate method in the code sample triggers an async update. There may be a race condition where `cloneInProgress: false` after `EnqueueRepoUpdate` but before the clone actually starts on gitserver. I don't know if we handle this so it is worth verifying.

**Comment by felixfbecker** [comment]
> We don't want to do a git fetch for every single graphql API call (e.g. our web app makes multiple per page).

The idea would be that it only does this call if the commit is not on Sourcegraph yet

**Comment by nicksnyder** [comment]
> The idea would be that it only does this call if the commit is not on Sourcegraph yet

Of course, but maybe we got a lot of invalid commits that were causing load? Maybe the load on gitserver itself was a problem? I don't know, this needs to be investigated.

> Furthermore, the browser extension code is built on the assumption that if a commit was not found, the backend will try to sync it first before giving up and returning the commit not found error. 

This is actually a pretty big assumption. Have you validated this assumption by looking at the code and/or speaking with the core services team?

Maybe @KattMingMing would remember :)

**Comment by unknwon** [comment]
OK, based on the information I gathered (code path, comments here and discussion with @tsenart), I think the following assumption is never the case:

>if a commit was not found, the backend will try to sync it first before giving up and returning the commit not found error.

I'll add this as a discussion item to our next core services team sync , and decide if we want to implement this.

**Comment by KattMingMing** [comment]
@nicksnyder I'm probably missing a lot of context here, but I'll do my best to help.

The original commit: 96462d8e77c8e896edefcdbd918f3aa3fbfcf43e doesn't exist anymore.

Is it possible someone force pushed over it or that the branch was deleted?

**Additional thoughts**
For example: Searching for @christinaforney commit on GitLab doesn't yield any results either. So to me that indicates the following:

1. GitHub and GitLab keep commits that were overwritten via force push and for deleted branches even though the cloned repository will not have this information. This is mentioned in their docs.
2. So from 1, I suspect something happened because there's a clear divergence in the SHA's for the same commits. I haven't had a chance to go all the up the tree to figure out where the commits / parent commits became problematic yet.

- Loic made the following commit:
    - [9d31459fb8129785d593d56e1ef9b2f572a37f08](https://gitlab.com/gitlab-org/gitlab/commit/9d31459fb8129785d593d56e1ef9b2f572a37f08)
        - Sourcegraph shows this commit as well.
    - Parrent: [980d08053218798ead37317ecf88182e90d019f7](https://gitlab.com/gitlab-org/gitlab/commit/980d08053218798ead37317ecf88182e90d019f7)
    - Also referenced in the merge request:

The following commit also exists:

- [https://gitlab.com/gitlab-org/gitlab/commit/408abfc428fe8ac40256eb92088bddae756490ec](https://gitlab.com/gitlab-org/gitlab/commit/408abfc428fe8ac40256eb92088bddae756490ec)
    - Sourcegraph does not have this commit.
    - Parent: [https://gitlab.com/gitlab-org/gitlab/commit/4d997f62dc04a2cbd02fb4bc011fdcef5a70bdcc](https://gitlab.com/gitlab-org/gitlab/commit/4d997f62dc04a2cbd02fb4bc011fdcef5a70bdcc)
    - Not mentioned in a merge request

I might be misunderstanding, but in these cases where the git rev isn't available due to these circumstances you could apply a local patch and use that. GitLab also gives you the patch (e.g [https://gitlab.com/gitlab-org/gitlab/commit/408abfc428fe8ac40256eb92088bddae756490ec.diff](https://gitlab.com/gitlab-org/gitlab/commit/408abfc428fe8ac40256eb92088bddae756490ec.diff))

I also could be completely wrong since I've only looked into this for a few minutes, but hopefully helpful.

**Comment by felixfbecker** [comment]
Thanks @KattMingMing. The merge request this happened on has been rebased since then so I wouldn't expect the commits to be available anymore. However, at the time I filed this issue I would have, and I would in general for the commits of a new merge request (newly pushed commits) when they are requested (without having to resort to applying a local patch, that shouldn't be needed).

**Comment by KattMingMing** [comment]
Wouldn't this only be an issue when you're looking at a specific commit? In the case of a branch the branch will have the commits and if you rebase the SHA will be different, but the branch is the same. For a merge request, again the rebased commits won't exist anymore and you'll use the updated SHA's.

In the case of a specific commit, that commit is gone which is why this is problematic and it's behavior built in to GitLab to allow users to see these commits. The only time you would apply a patch is when you are looking at a commit that exists on the code host and not in the git tree.

**Comment by felixfbecker** [comment]
I think you might be misunderstanding the issue. Assume the commit exists, in a merge request (not rebased etc). The browser extension requests the commit from Sourcegraph, _but Sourcegraph hasn't synced it yet_, and it returns an error. The proposal is to have Sourcegraph try to fetch it first (like it does when you navigate to the commit on Sourcegraph in the browser), because otherwise the browser extension has no way to provide codeintel for fresh merge requests.

**Comment by KattMingMing** [comment]
Understood and that makes sense. In any case, hopefully the info provided is useful. Thanks for clarifying the issue! 🍻

**Comment by keegancsmith** [comment]
FYI we do support blocking on fetch if we know a commit should exist. In most codepaths we avoid it, but at the GitServer client layer there is a field called `EnsureRevision` where if the commit doesn't exist, we run git fetch before running the git command. I don't know what needs to change to support your behaviour, it would actually require me to read the rest of this thread / more investigation. But we do support this and do this in some limited code paths. It should always be a behaviour we explicitly opt in to, and only do when we _know_ the commit should exist.

We will discuss this more at our core services sync today.

**Comment by unknwon** [comment]
Our action item is to have @keegancsmith review this thread more thoughtfully and recommend an approach / solution.

**Comment by keegancsmith** [comment]
Apologies, this slipped my radar last week. I will look into this tomorrow and ensure we are unblocked.

**Comment by keegancsmith** [comment]
We do fetch `merge-request` refs:

    gitserver-2:/data/repos/gitlab.com/gitlab-org/gitlab/.git# git config remote.origin.fetch
    +refs/*:refs/*
    gitserver-2:/data/repos/gitlab.com/gitlab-org/gitlab/.git# git show-ref | grep -o 'refs/[^/]*' | sort | uniq -c | sort -n
          1 refs/head
          2 refs/deployments
        128 refs/pipelines
       1714 refs/tags
       2838 refs/heads
      21697 refs/merge-requests
      38634 refs/environments

I then tested if we do the fetch behaviour we want. I tested this by using the api explorer + the command Felix used above with a non-existent commit. This took a while (good sign it is going out to the network), I then confirmed what we did in the logs (via honeycomb). We did the correct thing and did a fetch.

I think this may not be reproducable anymore, and it may have had to do with us not correctly supporting gitlab.com remote URLs on sourcegraph.com. As such I am going to assign this back to Felix to double check, then he can close this out. If you do run into this again, please can you capture a honeycomb trace or a lightstep trace of it failing. In the case of honeycomb, just capture all rev-parse commands against the commit https://ui.honeycomb.io/sourcegraph/datasets/gitserver-exec/result/iVSn4A2EJbp

Other things I noticed:
- We actually do the fetch twice for real non-existent commits
- Our GraphQL resolver does a full git log on the commit, even if we only want to know existence and not the author/etc.
- Lots of low hanging fruit w.r.t. performance when looking at traces for simple graphql queries :) cc @sourcegraph/core-services. eg rev-parse takes 1ms, but the full request takes 150ms.

**Comment by keegancsmith** [comment]
@felixfbecker ping

**Comment by felixfbecker** [comment]
I'll reopen if I see it again, thanks for investigating!
