### ISSUE TITLE
Stay on same PR logic is broken

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#6547]
`part` is never passed to `urlToFile`

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.11 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by felixfbecker** [comment]
@lguychard should we put this on 3.14? There is an open PR anyone could pick up: https://github.com/sourcegraph/sourcegraph/pull/6546
