### ISSUE TITLE
Add tests to ensure indexed search is working

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#6570]
This broke previously due to a misconfigured env var and we didn't notice, maybe regression tests @beyang added would've caught it? https://github.com/sourcegraph/sourcegraph/pull/6550

cc @rvantonder

**Comment by beyang** [comment]
Would this `index:only` search test have sufficed? https://sourcegraph.com/github.com/sourcegraph/sourcegraph@61bd03420e46686983432e60889663cffe4368af/-/blob/web/src/regression/search.test.ts#L257-260

**Comment by rvantonder** [comment]
Yes, pretty sure. Note that I ran into this early because I added a regression test for structural search, which wouldn't work otherwise: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@61bd03420e46686983432e60889663cffe4368af/-/blob/web/src/regression/search.test.ts#L381-388
