### ISSUE TITLE
docs: Document using an alternate clone URL for repos

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#658]
Some sites put an HTTPS or SSH proxy in front of their code host to reduce load. Some sites also use a service like AWS CodeCommit to do the same. In these cases, the repos still should be treated as being repos on the original code host, not the proxy site.

For example, I have a GitHub repo github.com/foo/bar. I want Sourcegraph to clone it using the URL https://cloneproxy.example.com/foo/bar.git. But I still want the "Go to GitHub repository" button, etc., to take me to https://github.com/foo/bar.

- Document workaround of using `ssh_config` or `gitconfig`'s `insteadOf`
- Support this as a first-class feature (not scheduled yet)

The actual code work is not prioritized, this is just a docs change.

**Comment by nicksnyder** [comment]
@tsenart Can you make this docs change sometime this week?

**Comment by tsenart** [comment]
Where in the docs should this work-around be included?

**Comment by tsenart** [comment]
I also need to understand exactly how these work-arounds work for this use case.

**Comment by sqs** [comment]
I don’t know from memory the ssh config directive, but to accomplish this using gitconfig insteadOf, see the git command here that contains insteadOf: https://wiki.codeaurora.org/xwiki/bin/Support/CodeAuroraMirrors

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.13 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
