### ISSUE TITLE
LSIF GraphQL API feedback

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#6584]
Here's my short review of the LSIF GraphQL API:

- `lsifJob`, `lsifDump`: These fields are not needed, clients should just use `Query.node()`.
- `lsifDumps`: This gets the LSIF dumps for a repository, so it should be a field of the `Repository` type. This makes the schema more flexible, as you can acquire a `Repository` resolver from another field (without needing to know the ID), then query its LSIF dumps, in one query.
  - Note: I am assuming here that uploading LSIF dumps for non-existent repos is not valid, which from my POV is what makes the most sense.

**Comment by efritz** [comment]
@slimsag Do you see an issue with marking the current implementation of the LSIF-related GraphQL endpoints as experimental? They'll be available in enterprise 3.10 but that would give us freedom for a version or so to muddle things around without worrying about backcompat.

**Comment by efritz** [comment]
> I am assuming here that uploading LSIF dumps for non-existent repos is not valid

In the long run, correct. In order to upload the repository and commit must exist. However, due to #6278 we can get into a state that breaks this assumption. In the long run this assumption will be exactly what we want.

**Comment by felixfbecker** [comment]
But with the current API, those dumps would still not be reachable, right? Because the current API uses IDs to refer to repos already, which I assume the GraphQL Go layer translates to a name for lsif-server. It could do the same if it was on the `Repository` type

**Comment by efritz** [comment]
See #6589 to address these issues.

**Comment by efritz** [comment]
Closed by #6589.
