### ISSUE TITLE
Layout issue in local_development.md

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#6597]
The numbered list for the macOS setup is rendered differently on the documentation site compared with github.

https://docs.sourcegraph.com/dev/local_development

Site:

<img width="969" alt="Screenshot 2019-11-14 at 15 50 18" src="https://user-images.githubusercontent.com/25610/68862798-c1b7ef80-06f6-11ea-8ebc-5de3e7b47119.png">

Github:

<img width="954" alt="Screenshot 2019-11-14 at 15 53 12" src="https://user-images.githubusercontent.com/25610/68862872-e7dd8f80-06f6-11ea-8312-53fea11cabe6.png">

**Comment by unknwon** [comment]
Thanks for filing this! I've noticed it for a while but too lazy to file it 😛

**Comment by ryanslade** [comment]
Looks like this has been fixed
