### ISSUE TITLE
Add category function for phabricator extsvc http requests metric

### ISSUE THREAD

**Issue by uwedeportivo** [sourcegraph/sourcegraph#6599]
Needed for metrics #4240 and relates to [TODO comment](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@abbace9/-/blob/internal/extsvc/phabricator/client.go#L38-39)

**Comment by uwedeportivo** [comment]
https://github.com/sourcegraph/sourcegraph/pull/6757

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.11 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.12 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.13 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by slimsag** [comment]
Looks like this was fixed, reopen if not.
