### ISSUE TITLE
Set application name in Postgres connection, so it is easier to debug

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#6607]
From a customer: 

Also would be also really cool to set application name in connection so that it would be easier to troubleshoot issues.

```
sg=# select application_name, count(*) from pg_stat_activity group by application_name;
 application_name | count
------------------+-------
 psql             |     1
 repo-updater     |     5
                  |    59
```

https://stackoverflow.com/questions/30322206/how-to-set-application-name-for-postgres-connections

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.11 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by dcrodman** [comment]
Hey @beyang, mind if I pick this up?

One question - I'm assuming this should this be configurable via env var with a default of `sourcegraph` or something?

**Comment by unknwon** [comment]
> Hey @beyang, mind if I pick this up?
> 
> One question - I'm assuming this should this be configurable via env var with a default of `sourcegraph` or something?

Thanks for asking! That sounds right to me :)

**Comment by dcrodman** [comment]
I have a PR ready, feedback is welcome! https://github.com/sourcegraph/sourcegraph/pull/9383
