### ISSUE TITLE
Document default value for `gitlab.authorization.matcher`

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#661]
- **Sourcegraph version:** Dev build

I tested the `matcher` property, and verified that it behaves as documented. 

However, without `matcher` set, the instance is able to correctly determine which repositories are attached to a GitLab instance. It would be good to document that there is a default or inferred value even when `matcher` is not set.

**Comment by beyang** [comment]
`matcher` seems superfluous, so I removed it.
