### ISSUE TITLE
Add external-link icons to actions in hover

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#6613]
When a hover action item is a link to an external URL (i.e. `url.origin !== window.location.origin`) then an external link icon should be displayed (e.g. something like an arrow pointing top-right with border)

https://gitlab.com/gitlab-org/gitlab/issues/36416

**Comment by lguychard** [comment]
Did you mean to close this @felixfbecker ?

**Comment by felixfbecker** [comment]
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/6563
