### ISSUE TITLE
a8n: For some repositories `gitserver` cannot apply the diff

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#6625]
(I haven't gotten the chance to dig into this really far, but I wanted to capture it in a ticket sooner rather than later)

For some repositories the conversion from `ChangesetJob` to `Changeset` fails because `gitserver` cannot apply the diff:

```
06:42:03           gitserver | 2019/11/15 06:42:03 4 github.com/sd9/vue-native-core command [git apply --cached] failed (35.710484ms): exit status 1
06:42:03           gitserver | OUT: error: patch failed: dist/vue.min.js:3
06:42:03           gitserver | error: dist/vue.min.js: patch does not apply
06:42:03           gitserver | error: patch failed: dist/vue.observer.min.js:3
06:42:03           gitserver | error: dist/vue.observer.min.js: patch does not apply
06:42:03           gitserver | error: patch failed: dist/vue.react.min.js:3
06:42:03           gitserver | error: dist/vue.react.min.js: patch does not apply
06:42:03           gitserver | error: patch failed: dist/vue.runtime.min.js:3
06:42:03           gitserver | error: dist/vue.runtime.min.js: patch does not apply
```

**Comment by mrnugget** [comment]
Here's another type of these errors:

```
07:25:11              gitserver | 2019/11/15 07:25:11 1 github.com/sd9/mpvue command [git apply --cached] failed (23.286865ms): exit status 1
07:25:11              gitserver | OUT: error: unit/features/component/component-slot.spec.js: does not exist in index
07:25:11              gitserver | ERROR Failed to apply patch., ref: sourcegraph/campaign-30, output: error: unit/features/component/component-slot.spec.js: does not exist in index
``

**Comment by tsenart** [comment]
Could it be that these repos have a different default branch than `master`?

**Comment by mrnugget** [comment]
> Could it be that these repos have a different default branch than `master`?

Good guess, but it looks like the one in the last error (`mpvue`) has `master` as its default branch.

The more I ran into these errors, the more I think that the one in the original ticket has something to do with minified JavaScript files and their really long lines and the second error, well, haven't figured it out yet :)

**Comment by mrnugget** [comment]
Another reproducible case.

Here's a diff we produced for https://github.com/appleboy/gorush (to be precise: our testing clone at github.com/sd9/gorush): https://gist.github.com/mrnugget/a2b651de247660a7c62fe3d6c74afaf0

This cannot be applied by `gitserver`:

```
2019/11/15 14:48:29 2 github.com/sd9/gorush ran successfully [git init] (15.404396ms)
OUT: Initialized empty Git repository in /Users/thorstenball/.sourcegraph/repos/.tmp/patch-repo-515379963/.git/
2019/11/15 14:48:29 2 github.com/sd9/gorush ran successfully [git reset -q a495d00eca99ee7dee4cadd1fdf6920b2fcd3ed8] (20.91211ms)
OUT:
2019/11/15 14:48:29 2 github.com/sd9/gorush command [git apply --cached] failed (22.260498ms): exit status 1
OUT: error: example/node/client.js: does not exist in index
error: example/node/gorush_grpc_pb.js: does not exist in index
ERROR Failed to apply patch., ref: sourcegraph/campaign-37, output: error: example/node/client.js: does not exist in index
error: example/node/gorush_grpc_pb.js: does not exist in index
```

And I can reproduce it locally, even in a non-bare-non-mirror clone of the repository:

```
$ git clone https://<secret-token-see-password-manager>@github.com/sd9/gorush
[..]
$ cd gorush
$ git reset a495d00eca99ee7dee4cadd1fdf6920b2fcd3ed8
$ git apply --cached ~/Downloads/gorush.patch
error: example/node/client.js: does not exist in index
error: example/node/gorush_grpc_pb.js: does not exist in index
```

Now, if I change these lines:

```
--- rpc/example/node/client.js
+++ rpc/example/node/client.js
```

into these:

```
--- a/rpc/example/node/client.js
+++ b/rpc/example/node/client.js
```

Then it works, at least in this full clone of the repository.

When I tried to replicate what `gitserver` does in its `handleCreateCommitFromPatch` handler (see [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@9381787ec70439fb1beb52e301cd39d7f43388a3/-/blob/cmd/gitserver/server/patch.go#L21)) I can't get it to work.

But for now it seems like we need to prefix the filenames with `a/` and `/b`?

That would mean we need to change how we concatenate the diffs [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@9381787/-/blob/enterprise/pkg/a8n/run/campaign_type.go#L135-148) and probably can't use `replacer`/`comby`'s "raw" diff for this (since we'd need to inject `a/` and `/b` into it)

**Comment by rvantonder** [comment]
Note that the `a/`, `b/` conventions disambiguate source and destinations and are [git-specific](https://git-scm.com/docs/git-diff), and unified diffs (without the prefixes) are not. The latter ensures we can always apply patches with the `patch` utility irrespective of versioning system without fixups. `patch` can apply git patches, but usually requires a fixup, like `patch -p1 < p.patch`, to get rid of the `a/` and `b/`.

That said, 

> But for now it seems like we need to prefix the filenames with a/ and /b?

Doing this sort of thing will bite us. In principle, we should never be manually changing diff contents. The working assumptions should be that diffs are atomically produced by some tool, and consumed by another. We can configure tools to work together for things like file paths (cf. above) but we should never be changing diff contents so that the tools (that implement the spec) work.

Consider:

```
mkdir tmp && cd tmp && git init . && echo 'foo' > foo && git add . && git commit -m "foo" && git rm foo && git restore --staged foo && git diff
```
Gives:

```patch
diff --git a/foo b/foo
deleted file mode 100644
index 257cc56..0000000
--- a/foo
+++ /dev/null
@@ -1 +0,0 @@
-foo
```

On deletion, there is no `b/` prefix for `/dev/null`. `/dev/null` is special: both `git apply` and `patch` know this, but if we go and change diffs and prefix filenames, we will break things. Unless we take into account the full spec of diffs in our code, we should not be changing contents of diffs. Even then, I would say we don't need to.

Now, to solve the actual issue for our case: The diff producer is `comby`, and that is unified diff format.  We can decide whether to add an option that produces the special 'git diff' format. Assuming we do not go that route, let's look at the consumer, which runs `git apply`. `git apply` expects the prefixes, and we see that it strips those prefixes using the `-p` option (the `-p` option is also available in `patch`, cf. above):

```
       -p<n>
           Remove <n> leading path components (separated by slashes) from traditional diff paths. E.g., with -p2, a
           patch against a/dir/file will be applied directly to file. The default is 1.
```

The default is 1 so that it strips the `a/`, `b/`, (this doesn't apply to special cases like `/dev/null`). So, to apply unified diffs, using `-p0` works:

```
git apply -p0 --cached p.patch
```

I suggest the above until we standardize on what we want diff formats we want to support in producers/consumers. Despite the ubiquity of `git`, I do think it's worthwhile avoiding version-control-specific formats in what we accept/consume (think `hg`, `perforce`, ...) if we can reasonably avoid it.

**Comment by tsenart** [comment]
Thanks for your very thorough response @rvantonder! Agree that with your rationale for not modifying diffs and not depending on git specific diffs. We didn't come across that option (i.e. `-p`)  when debugging this today, cheers!

**Comment by mrnugget** [comment]
#6660 fixes some (majority?) of the problems here, but there are still some left.

Here's another diff that fails to apply:

```diff
diff javascripts/highlight.customized/test/detect/openscad/default.txt javascripts/highlight.customized/test/detect/openscad/default.txt
--- javascripts/highlight.customized/test/detect/openscad/default.txt
+++ javascripts/highlight.customized/test/detect/openscad/default.txt
@@ -1,8 +1,8 @@
 use <write.scad>
 include <../common/base.scad>
 
-//draw a foobar
-module foobar(){
+//draw a barfoo
+module barfoo(){
     translate([0,-10,0])
     difference(){
         cube([5,10.04,15]);
@@ -10,6 +10,6 @@
     }
 }
 
-foobar();
+barfoo();
 #cube ([5,5,5]);
 echo("done");
diff javascripts/highlight.customized/test/markup/php/heredoc.expect.txt javascripts/highlight.customized/test/markup/php/heredoc.expect.txt
--- javascripts/highlight.customized/test/markup/php/heredoc.expect.txt
+++ javascripts/highlight.customized/test/markup/php/heredoc.expect.txt
@@ -9,6 +9,6 @@
 EOT;</span>
 
 <span class="hljs-keyword">array</span>(<span class="hljs-string">&lt;&lt;&lt;EOD
-foobar!
+barfoo!
 EOD</span>
 );
diff javascripts/highlight.customized/test/markup/php/heredoc.txt javascripts/highlight.customized/test/markup/php/heredoc.txt
--- javascripts/highlight.customized/test/markup/php/heredoc.txt
+++ javascripts/highlight.customized/test/markup/php/heredoc.txt
@@ -9,6 +9,6 @@
 EOT;
 
 array(<<<EOD
-foobar!
+barfoo!
 EOD
 );
```

It's for this repository at this commit: https://github.com/json-api/json-api/blob/3a08b94a940db690d9b886ca5b3bb42edaf3b0b6/javascripts/highlight.customized/test/detect/openscad/default.txt

`git apply --cached -p0` fails with this:

```
$ git apply --cached -p0 ~/work/json-api-foobar-barfoo-failed-diff.patch
error: patch failed: javascripts/highlight.customized/test/detect/openscad/default.txt:10
error: javascripts/highlight.customized/test/detect/openscad/default.txt: patch does not apply
```

`patch` outputs this and leaves a `default.txt.orig` backup file behind:

```
$ patch -p0 < ~/work/json-api-foobar-barfoo-failed-diff.patch
patching file javascripts/highlight.customized/test/detect/openscad/default.txt
Hunk #2 succeeded at 10 with fuzz 2.
patching file javascripts/highlight.customized/test/markup/php/heredoc.expect.txt
patching file javascripts/highlight.customized/test/markup/php/heredoc.txt
```

**Comment by mrnugget** [comment]
`git diff` simply prints the `\ No newline at end of file` when it can't find a `\n` in a given line that's to be printed. [See the code here](https://github.com/git/git/blob/d9f6f3b6195a0ca35642561e530798ad1469bd41/diff.c#L1749-L1771)

In the GNU diffutil's the `Changelog` [contains a pretty precise explanation of when this comment is to be printed](https://sourcegraph.com/github.com/Distrotech/diffutils@9e70e1ce7aaeff0f9c428d1abc9821589ea054f1/-/blob/ChangeLog#L1066):

```
diff: fix a regression when at least one input lacks a newline-at-EOF, 
and the final hunk plus context-length aligns exactly with the end 
of the newline-lacking file. Diff would fail to output the required 
"\ No newline at end of file" line, thus rendering the output invalid. 
```

Here is the [relevant part of the code](https://sourcegraph.com/github.com/Distrotech/diffutils@9e70e1c/-/blob/src/util.c#L662-664):

```c
  if ((!line_flag || line_flag[0]) && limit[-1] != '\n')
    fprintf (out, "\n\\ %s\n", _("No newline at end of file"));
```

**Comment by mrnugget** [comment]
It looks like the `patdiff` library that `comby` is using doesn't support printing the `\ No newline at end of file` file. It _does_ know about missing newlines though:

```ocaml
utop # Patdiff_lib.Compare_core.diff_files ~prev_file:"/Users/thorstenball/tmp/diffing_nneof/a" ~next_file:"/Users/thorstenball/tmp/diffing_nneof/b" (Configuration.Diff_configuration.plain ()) ;;
No newline at the end of /Users/thorstenball/tmp/diffing_nneof/a
No newline at the end of /Users/thorstenball/tmp/diffing_nneof/b
--- /Users/thorstenball/tmp/diffing_nneof/a
+++ /Users/thorstenball/tmp/diffing_nneof/b
@@ -1,2 +1,4 @@
+
+0

 1
```

**Comment by rvantonder** [comment]
> Yeah, diff and git diff output a `\ No newline at the end of file`.

Indeed, and `comby`/`patdiff` does not output this line, and it appears this output is necessary for both `patch` and `git apply`. Underneath the hood, my working assumption was that `git apply` calls out to `patch`, but there's some interesting deviation. More on that below. 

For our problem: `patdiff` does not support this output at this time (they could support it, and I will PR something and see), but for now I will add support to `comby`. The question I had was 'What do I need to add exactly, i.e., what is actually expected by `git apply` and/or `patch`?

Interesting discoveries:

- On the patching side (not the diff generations ide), the only documented behavior about `\ ...` I could find [was here](https://sourcegraph.com/github.com/mirror/patch/-/blob/ChangeLog-2011#L3091):

```
(another_hunk): The patch file may contain lines starting with '\',
```

[Implementation](https://sourcegraph.com/github.com/mirror/patch/-/blob/src/pch.c#L2060-2079)

Implication: `patch` only needs to a see a `\`, the ` No newline at end of file` is insignificant. I confirmed and tested that. Something like

```
--- a	2019-11-18 12:58:05.000000000 -0700
+++ b	2019-11-18 12:58:05.000000000 -0700
@@ -1,2 +1,4 @@
 
+0
+
 1
\
```

patches just fine 

Reproducible with
`printf '\n1'>a; printf '\n0\n\n1'>b`
`diff -u a b > p.patch`
`patch < p.patch`

- The above patch does _not_ work for `git apply` (‽). It reports the `error: <blah blah> patch does not apply`. So what does `git apply` expect? [It expects this](https://sourcegraph.com/github.com/git/git@d9f6f3b6195a0ca35642561e530798ad1469bd41/-/blob/apply.c#L1719-1731):

```
		/*
		 * We allow "\ No newline at end of file". Depending
		 * on locale settings when the patch was produced we
		 * don't know what this line looks like. The only
		 * thing we do know is that it begins with "\ ".
		 * Checking for 12 is just for sanity check -- any
		 * l10n of "\ No newline..." is at least that long.
		 */
		case '\\':
			if (len < 12 || memcmp(line, "\\ ", 2))
				return -1;
			break;
		}
```

- Implication: `\` followed by 'enough' characters will work. 

I confirmed and tested that. Something like:

```
diff --git a/javascripts/highlight.customized/test/detect/openscad/default.txt b/javascripts/highlight.customized/test/detect/openscad/default.txt
index 706ee13..ca942df 100755
--- a/javascripts/highlight.customized/test/detect/openscad/default.txt
+++ b/javascripts/highlight.customized/test/detect/openscad/default.txt
@@ -10,6 +10,6 @@ module foobar(){
     }
 }
 
-foobar();
+quxbar();
 #cube ([5,5,5]);
 echo("done");
\ DERP DERP THIS LINE IS GREATER THAN 12 CHARS
```

---

I will add `\ No newline at the end of file` since `git` needs at least this line length, though I am somewhat dissatisfied about the adoption of this (git-specific) sanity check is strictly stronger than what the `patch` utility needs. Out of our control though `¯\_(ツ)_/¯`

**Comment by mrnugget** [comment]
Code archeology high five ✋, @rvantonder! Thanks for further digging into this.

> I will add `\ No newline at the end of file` since `git` needs at least this line length,

If you want to give me some pointers as to how you would do it, I'd be happy to `opam switch` 😎

**Comment by mrnugget** [comment]
Just saw that you already landed this in `comby` (https://github.com/comby-tools/comby/commit/bd21fe22280e64bba548829169c2048b9a02195d) and updated `comby` here https://github.com/sourcegraph/sourcegraph/commit/bbd724791ed8e1ed88c8544cbb2b126dd496b6a6

 Thanks! I'll rebase my branches onto our `master` here and try to tackle the _other_ failing diffs :)

**Comment by mrnugget** [comment]
@rvantonder It looks like `patch` and `git apply` expects the `\ No newline at end of file` to come at least after the `-` part of the hunk.

In https://github.com/awslabs/serverless-application-model at e7c4117 `comby` produced the following diff:

```diff
diff tests/translator/input/error_application_properties.yaml tests/translator/input/error_application_properties.yaml
--- tests/translator/input/error_application_properties.yaml
+++ tests/translator/input/error_application_properties.yaml
@@ -40,6 +40,6 @@
     Properties:
       Location:
         ApplicationId:
-          Sub: foobar
+          Sub: barfoo
         SemanticVersion:
-          Fn::Sub: foobar
+          Fn::Sub: barfoo
\ No newline at end of file
```

Both `patch` and `git apply` cannot apply it:

```
$ patch -p0 --dry-run -u < ~/work/sourcegraph/failed.patch
patching file tests/translator/input/error_application_properties.yaml
Hunk #1 FAILED at 40.
1 out of 1 hunk FAILED -- saving rejects to file tests/translator/input/error_application_properties.yaml.rej

$ git apply --cached -p0 ~/work/sourcegraph/failed.patch                                                                -1-
error: patch failed: tests/translator/input/error_application_properties.yaml:40
error: tests/translator/input/error_application_properties.yaml: patch does not apply
```

But if I change the diff to this

```diff
diff tests/translator/input/error_application_properties.yaml tests/translator/input/error_application_properties.yaml
--- tests/translator/input/error_application_properties.yaml
+++ tests/translator/input/error_application_properties.yaml
@@ -40,6 +40,6 @@
     Properties:
       Location:
         ApplicationId:
-          Sub: foobar
+          Sub: barfoo
         SemanticVersion:
-          Fn::Sub: foobar
\ No newline at end of file
+          Fn::Sub: barfoo
```

or this

```diff
diff tests/translator/input/error_application_properties.yaml tests/translator/input/error_application_properties.yaml
--- tests/translator/input/error_application_properties.yaml
+++ tests/translator/input/error_application_properties.yaml
@@ -40,6 +40,6 @@
     Properties:
       Location:
         ApplicationId:
-          Sub: foobar
+          Sub: barfoo
         SemanticVersion:
-          Fn::Sub: foobar
\ No newline at end of file
+          Fn::Sub: barfoo
\ No newline at end of file
```

both can apply it.

**Comment by rvantonder** [comment]
Yeah--I expected this can still crop up (thanks for a concrete example, that way I can test against it).

**Comment by mrnugget** [comment]
Here is another failure. This repository https://github.com/cypress-io/cypress at da497e44d5bdc2f3dd7dbb5834bf0f9a5216aeaa with this diff: https://gist.github.com/mrnugget/41df2e9c5a32da19c30a8c5b9c84b98e

It fails with these messages:

```
$ patch -p0 --dry-run -u < ~/work/sourcegraph/failed.patch
patching file cli/types/index.d.ts
Hunk #1 FAILED at 2796.
Hunk #2 FAILED at 2804.
Hunk #3 FAILED at 2834.
Hunk #4 FAILED at 3296.
Hunk #5 FAILED at 3304.
Hunk #6 FAILED at 3334.
6 out of 6 hunks FAILED -- saving rejects to file cli/types/index.d.ts.rej
patching file cli/types/tests/chainer-examples.ts
patching file packages/driver/test/cypress/fixtures/dom.html
patching file packages/driver/test/cypress/integration/commands/actions/click_spec.js
patching file packages/driver/test/unit_old/cypress/server_spec.coffee
patching file packages/driver/test/cypress/integration/commands/actions/type_spec.js
patching file packages/driver/test/cypress/integration/commands/assertions_spec.coffee
patching file packages/server/lib/request.coffee
patching file packages/driver/test/cypress/integration/commands/querying_spec.coffee
patching file packages/server/__snapshots__/5_subdomain_spec.coffee.js
patching file packages/server/test/e2e/5_subdomain_spec.coffee
patching file packages/server/test/support/fixtures/projects/e2e/cypress/integration/subdomain_spec.coffee
patching file packages/server/test/integration/websockets_spec.coffee
patching file packages/server/test/support/fixtures/projects/todos/tests/_fixtures/message.txt
patching file packages/server/test/unit/config_spec.coffee
```
```
$ git apply --cached -p0 ~/work/sourcegraph/failed.patch
error: patch failed: cli/types/index.d.ts:2796
error: cli/types/index.d.ts: patch does not apply
```

**Comment by mrnugget** [comment]
I'm going to close this since all the errors mentioned in this ticket so far have been closed. At least as far as I can tell.

If other "cannot apply diff" errors pop up again, we should create separate tickets.
