### ISSUE TITLE
Autocomplete suggestions: comprehensive list of filters is never shown

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#6635]
- **Sourcegraph version:** `sourcegraph/server:3.10.0-rc.2`

This might actually be expected now (and if so, close this). @christinaforney can you chime in on what we want here? I remember raising it in code review and being told that this was actually desirable (and growing to like it during that round of testing), so I'm filing in case it was removed unintentionally. 

#### Steps to reproduce:

1. In the search query field, type in a valid filter with a value (for example `repo:^some/repo$`), then a space. 

#### Expected behavior:

All valid filters are suggested:

![image](https://user-images.githubusercontent.com/1741180/68942002-a8bb4700-07a7-11ea-87d8-737462f4d1ee.png)

#### Actual behavior:

Only "legacy" suggestions are shown:

![image](https://user-images.githubusercontent.com/1741180/68941869-46624680-07a7-11ea-90d5-c81da84d2f98.png)

**Comment by felixfbecker** [comment]
I would at least expect it to show suggestions after typing the beginning of an operator?

![image](https://user-images.githubusercontent.com/10532611/68942995-3ef06c80-07aa-11ea-8957-c4fdd55775a6.png)

i.e. the first suggestion here should be the `file` operator, then all the other suggestions

**Comment by lguychard** [comment]
@felixfbecker see https://github.com/sourcegraph/sourcegraph/issues/6632

**Comment by felixfbecker** [comment]
I think that issue is different. If you type in a repo filter, then you don't even get a suggestion anymore for typing just a single letter `f`.

**Comment by lguychard** [comment]
@felixfbecker that is not what I'm seeing:

![image](https://user-images.githubusercontent.com/1741180/68943450-81ff0f80-07ab-11ea-84bb-caf44ef61296.png)

**Comment by felixfbecker** [comment]
Ah, something interesting is happening here. The backend suggestions take a long time to load, and the client-side suggestions for operators are not shown until the backend suggestions arrived for some reason. If I wait a long time, I see `f` like you do.

**Comment by lguychard** [comment]
Yeah, I was going to say that what you're experiencing is probably linked to https://github.com/sourcegraph/sourcegraph/issues/6637
