### ISSUE TITLE
Autocomplete suggestions: do not wait for fechSuggestions() to emit before showing static suggestions

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#6637]
- **Sourcegraph version:** `sourcegraph/server:3.10.0-rc.2`

#### Steps to reproduce:

1. Type in "repo" in the search bar

#### Expected behavior:

Filter suggestions are immediately shown. Fuzzy suggestions are shown eventually, once they are fetched.

#### Actual behavior:

The suggestions dropdown is only shown when fuzzy suggestions have been fetched.

I think the suggestions dropdown would feel a lot more reactive if static suggestions were shown immediately (and then eventually merged with fuzzy suggestions).

This could be easily done with something like this:

```typescript
merge(
    of(staticSuggestions),
    fetchSuggestions().pipe(
        map(backendSuggestions => [...staticSuggestions, ...backendSuggestions])
    )
)
```

**Comment by lguychard** [comment]
This feels like a low-effort, high-value improvement.

**Comment by felixfbecker** [comment]
This can currently make the operator suggestions take so long to appear that I thought they were broken and weren't coming anymore (and we don't have a loading indicator anymore).

What needs to be avoided is an unstable UI, but as long as the client suggestions come first and the backend suggestions are appended, that constraint would be maintained.
