### ISSUE TITLE
Add DB table to distinguish between old and new instances

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#6643]
We want to be able to distinguish between old (previously upgraded) and brand new Sourcegraph instances.

From https://github.com/sourcegraph/sourcegraph/issues/6579#issue-522422670: 

> Engineering question, do we foresee wanting to make this distinction in the future? I think the answer is yes. It would be nice to have the capability to communicate in-product changes directly to the set of affected users (instead of all users). One potential solution for this would be to add a DB table that tracks the current version of Sourcegraph. Two columns: version_number and inserted_at

> Pseudocode that is executed on startup of a Sourcegraph instance
```
select version_number, inserted_at from versions order by inserted_at desc limit 1
if version_number == current_version_number_of_binary
    return // do nothing
else
    insert into versions (current_version_number, now())
```
> Any other code path can check if the instance is "new" with select count(*) from versions. If there is only one version, then the instance is "new".

**Comment by attfarhan** [comment]
@slimsag with [RFC 81](https://docs.google.com/document/d/1cDrQuLly_QZ_XoDDR41hgF3qCUGojvSXItI-knaBDY4/edit) being proposed, should we not plan on adding this versions table anymore?

**Comment by slimsag** [comment]
Yes, I think my proposal would be an alternative to this and would make
this issue obsolete.

**Comment by attfarhan** [comment]
Got it, will close for clarity then.
