### ISSUE TITLE
metric labels to distinguish traffic originating from gitlab.com integration

### ISSUE THREAD

**Issue by uwedeportivo** [sourcegraph/sourcegraph#6650]
This would enable Grafana dashboards showing load on the system from the integration

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.11 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.12 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
https://github.com/sourcegraph/sourcegraph/pull/7830

closing (if we need more we can re-open)
