### ISSUE TITLE
Clean up and fix Digital Ocean installation instructions

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#6652]
From a user reporting frustration with spinning Sourcegraph up on DO: https://twitter.com/morganestes/status/1195606693599760384

* Our docs (https://docs.sourcegraph.com/admin/install/docker/digitalocean) don't reference the DO 1-click app, which is different from the instructions on our docs page. Which is the "canonical" path?
* It was difficult to make Sourcegraph work with LetsEncrypt. Along the way, nginx was installed and took over port 80 on the host machine and this was not connected to the Sourcegraph instance running in Docker. User did manage to make Sourcegraph accessible with a mkcert certificate, but they would prefer to use LetsEncrypt.

Course of action:
- [x] Run through installation of Sourcegraph on DO.
- [x] Update the docs. If appropriate, link to DO 1-click app *or* instruct DO to take down that app in favor of instructions on our site.
- [ ] ~Reply to the reporting user on Twitter with links to new docs.~
- [ ] ~Add a test to the regression suite that tests installation on DO. (We should do this anyway for other cloud providers, and it makes sense to implement these all together.)~

**Comment by dadlerj** [comment]
Related: https://github.com/sourcegraph/sourcegraph/issues/6666

**Comment by morganestes** [comment]
I was able to follow the instructions on the Sourcegraph docs this morning and install and configure an instance on DO just using Docker on IPv4.

I used Certbot to install a certificate on my domain, and was able to connect my accounts and get everything working. 🙌 

When I went into the droplet and enabled IPv6 and set the `nginx.conf` file to listen on `[::]:7080` and `[::]:7443` and restarted Sourcegraph inside Docker, that's when it stopped working and went into a restart loop. Removing the IPv6 rules from the Nginx config and restarting didn't resolve the problem, so it seems that enabling IPv6 and trying to run Sourcegraph on it is the consistent thing among all the droplets I've run this on that have failed.

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.11 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by beyang** [comment]
Closing this as the docs have been updated and should be more accurate now. @morganestes please re-open if you are still running into issues!
