### ISSUE TITLE
Basic intellisense for objective-C

### ISSUE THREAD

**Issue by aisbaa** [sourcegraph/sourcegraph#6655]
#### Question description

Is objctive C supported by sourcegraph, it seems that j2d does not work in `.m` files.

#### Additional context

https://sourcegraph.com/github.com/changsanjiang/SJVideoPlayer@daef27455ee9ef71945bd323227beb51dc329086/-/blob/Example/1%20ObjC%20Example/SJVideoPlayerExample-ObjC/Pods/Masonry/Masonry/MASCompositeConstraint.m

**Comment by chrismwendt** [comment]
Objective-C is currently not supported https://sourcegraph.com/extensions?query=category%3A%22Programming+languages%22

**Comment by aisbaa** [comment]
Thank you for response. Is there a plan to add support for Objective-C? Header files seem to work:

https://sourcegraph.com/github.com/changsanjiang/SJVideoPlayer@daef27455ee9ef71945bd323227beb51dc329086/-/blob/Example/1%20ObjC%20Example/SJVideoPlayerExample-ObjC/Pods/Masonry/Masonry/MASConstraint.h#L25:24&tab=def

**Comment by chrismwendt** [comment]
Yes, it's on the roadmap https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.dimwsc9ccmwq
