### ISSUE TITLE
Add way to quickly/easily identify when LSIF is working in the browser

### ISSUE THREAD

**Issue by christinaforney** [sourcegraph/sourcegraph#6656]
Follow up from https://github.com/sourcegraph/sourcegraph/pull/6642#discussion_r347016777

From Felix:
> Maybe it would be easier if the LSIF handler in the extension logged a statement "Using LSIF code intelligence" on init

**Comment by efritz** [comment]
Merged into github.com/sourcegrpah/sourcegraph-go and github.com/sourcegrpah/sourcegraph-typescript.
