### ISSUE TITLE
Remove DigitalOcean 1-click app

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#6665]
We should take it down entirely ASAP given we're not investing in updating the docs — it still shows instructions for Sourcegraph 3.4! https://marketplace.digitalocean.com/apps/sourcegraph

**Comment by dadlerj** [comment]
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/6666

**Comment by unknwon** [comment]
I'm closing this one... it seems identical to #6666 and we already have discussions on that thread.

**Comment by dadlerj** [comment]
Oops, I thought by marking as a duplicate, this would get auto-closed... Thanks!
