### ISSUE TITLE
Remove DigitalOcean 1-click app

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#6666]
We should take it down entirely ASAP given we're not investing in updating the docs — it still shows instructions for Sourcegraph 3.4! https://marketplace.digitalocean.com/apps/sourcegraph

See https://github.com/sourcegraph/sourcegraph/issues/6652 for context.

**Comment by slimsag** [comment]
No objection to taking this down in the interim, but @dadlerj @ryan-blunden what is the reason this cannot be a part of our release process / automated? You and us at @sourcegraph/distribution should probably chat about this.

**Comment by ryan-blunden** [comment]
@slimsag Sounds good.

**Comment by dadlerj** [comment]
Thanks @ryan-blunden 

@slimsag , it required a lot of custom work each month since DO's marketplace was still in early stages (manually shipping them a custom image each month, having them package it, doing testing to ensure that everything was built/packaged correctly), and they couldn't (yet) provide metrics on usage, so we decided to scrap it until those issues were fixed.

**Comment by beyang** [comment]
@ryan-blunden has this been removed from DO's site yet? If not, do you know how I should go about removing it?

**Comment by ryan-blunden** [comment]
It has now been removed.
