### ISSUE TITLE
Missing monitoring for when gitserver fetches/execs/clones are slow

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#6675]
monitoring these two failure cases would be useful (I've seen them occur on customer deployments and indicate real problems): https://sourcegraph.com/github.com/sourcegraph/sourcegraph@45ee47a084694eecbd6b6a4c56e150645bc5a092/-/blob/cmd/gitserver/server/server.go#L596-601

**Comment by uwedeportivo** [comment]
cool, will do

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.12 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
