### ISSUE TITLE
Bottom Pane with "References and Definition" does not always update when clicking on Symbol in left nav bar

### ISSUE THREAD

**Issue by caseylmanus** [sourcegraph/sourcegraph#67]
- Issue type: bug
- Sourcegraph version: 2.7.5
- OS Version: Mac High Sierra (10.13.4)
- Docker version: 
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: true

Steps to reproduce:

1.  Open a Repository
2.  In left navbar  click on a function in Symbols list
3.  Expect that the "Reference or Definition" panel updates
4.  Actual:  The reference or definition panel updates only after navigating between them.  
![screen shot 2018-04-30 at 3 20 15 pm](https://user-images.githubusercontent.com/1685484/39448263-10f7d430-4c8a-11e8-867f-20c6ed2fa0b4.png)

**Comment by beyang** [comment]
@felixfbecker do you have any thoughts about this?
