### ISSUE TITLE
GitLab project permissions do not get updated as expected

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#671]
- **Sourcegraph version:** dev build

using gitlab2.sgdev.org

#### Steps to reproduce:

1. Create a private GitLab project on a GL instance.
2. Set up Sourcegraph to connect to the GL instance
3. Log in to sourcegraph with an account that does _not_ have access to the private repo.
4. See that the repo does not appear in the Sourcegraph site admin repos page .
5. Set `authorization.ttl` to `"10s"` in your config and apply the change
6. Change the permissions of the private repo to be public
7. Check your Sourcegraph site admin repos page, and see that it still does not appear.

I believe this is the associated log: 
```
17:42:33      repo-updater | ERROR Error listing GitLab projects, url: projects?membership=true&order_by=last_activity_at&per_page=100, error: unexpected response from GitLab API (http://gitlab.sgdev.org/api/v4/projects?membership=true&order_by=last_activity_at&per_page=100): HTTP error status 401
```
#### Expected behavior:

The repo would appear when changed to public. 

#### Actual behavior:

The repo does not appear despite being public.

**Comment by beyang** [comment]
Ah, the reason for this is that changing the TTL does not invalidate the existing cache entries (which still have the old TTL).

**Comment by beyang** [comment]
Fixed last iteration
