### ISSUE TITLE
Replacer service is never started by server in the docker image

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#6711]
`replacer` is missing in the server globals:

https://sourcegraph.com/github.com/sourcegraph/sourcegraph@master/-/blob/cmd/server/shared/globals.go#L12:5

**Comment by rvantonder** [comment]
Hm, not actually sure if it needs to be in that file, or [procfile](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@master/-/blob/cmd/server/shared/shared.go#L129)

**Comment by rvantonder** [comment]
Removing release blocker tag because this isn't a feature in the CHANGELOG that will breaks something. @sourcegraph/automation please take a look at #6712 for everything that we need to ship the automation stuff in the server image.

**Comment by slimsag** [comment]
> Hm, not actually sure if it needs to be in that file, or the procfile variable, or both.

Both.

The globals file is for the debug golang pprof port, the procfile is for launching the actual service.

**Comment by mrnugget** [comment]
This should be fixed by https://github.com/sourcegraph/sourcegraph/pull/6712 right, @rvantonder?

**Comment by rvantonder** [comment]
![](https://media2.giphy.com/media/x4c1BAQDx2ekL3LJMB/giphy.gif?cid=5a38a5a282f1b3173b85ba98a455d407c4d7486b267198e6&rid=giphy.gif)



I may test this manually later, if #6678 isn't done by the time I get to it. Thanks for commandeering that fix.

**Comment by mrnugget** [comment]
Can confirm that `replacer` is running inside a newly built image. But I just did a quick `ps aux | grep replacer` check.
