### ISSUE TITLE
a8n: Implement retryCampaign mutation

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#6718]
This is a follow-up to [RFC 42](https://docs.google.com/document/d/1j85PoL6NOzLX_PHFzBQogZcnttYK0BXj9XnrxF3DYmA/edit).

Right now, when the `createCampaign` mutation with a given `CampaignPlan` ID fails due to various reasons (GitHub not reachable, token invalid, gitserver down, ...) the conversion of `ChangesetJobs` into `Changesets` in the `(&a8n.Service).runChangesetJob` ends with the `ChangesetJobs` having its `Error` field populated. [See the code here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@034cee47c83a7734cf04a4b5720717665b5a69db/-/blob/enterprise/pkg/a8n/service.go#L114)

What we want is a `retryCampaign` mutation that
* takes in a `Campaign` ID
* loads all the failed `ChangesetJobs` (definition: `finished_at` is null, or `error` is non-blank, or `changeset_id` is null)
* uses `(&a8n.Service).runChangesetJob` to try again to create a commit from the given diff in the connected CampaignJob, push the commit, open a pull request on the codehost, save the pull request as an external service

**Important**: for that to work, the `runChangesetJob` method must be idempotent! That means: if it runs twice with the same `ChangesetJob` is **cannot create duplicate pull requests!**. That means it needs to check that new commits are not added to same branch, check for `ErrAlreadyExists` response from code hosts, early-exit if a `Changset` with the given `changeset_job_id` exists, etc.

**Comment by ryanslade** [comment]
> loads all the failed ChangesetJobs (definition: finished_at is null, or error is non-blank, or no Changeset with its changeset_job_id exists)

@mrnugget Maybe I'm missing something but I don't see any columns in `changesets` relating to changeset jobs

**Comment by mrnugget** [comment]
Sorry about that! It's the other way around: `changeset_jobs` has a `changeset_id`. So if that is set, we know that we created the `Changeset` on the code host, since that should happen in a transaction.

**Comment by ryanslade** [comment]
Thanks, I'll update the description
