### ISSUE TITLE
a8n: Implement cancelCampaignPlan GraphQL mutation

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#6719]
This is a follow-up to [RFC 42](https://docs.google.com/document/d/1j85PoL6NOzLX_PHFzBQogZcnttYK0BXj9XnrxF3DYmA/edit).

Currently the `previewCampaignPlan` mutation can run indefinitely (when `wait = false` in arguments, with `wait = true` the request timeout cancels the `context.Context`s).

We need a `cancelCampaignPlan` mutation that

* takes in a `CampaignPlan.ID`
* cancels the `CampaignPlan` so that no new `CampaignJobs` are executed

We probably want to extend the `BackgroundProcessState` with a `CANCELLED` state so that clients know when a CampaignPlan has finished execution or when it's been cancelled.

https://github.com/sourcegraph/sourcegraph/blob/034cee47c83a7734cf04a4b5720717665b5a69db/cmd/frontend/graphqlbackend/schema.graphql#L484-L492

---

### Thoughts on implementation

* Add a `CancelledAt` field to `CampaignPlan`, null by default
* In the `cancelCampaignPlan` mutation ([see the stub here](https://github.com/sourcegraph/sourcegraph/blob/034cee47c83a7734cf04a4b5720717665b5a69db/enterprise/pkg/a8n/resolvers/resolver.go#L456)) we populate the field in a transaction
* [At the beginning of `(&Runner).runJob`](https://github.com/sourcegraph/sourcegraph/blob/master/enterprise/pkg/a8n/run/runner.go#L173-L186) we query the database to check whether the `CampaignPlan` has been cancelled. If so, we do an early return.
* (Do we need to set an `Error` on the `CampaignJob` if the `CampaignPlan` has been cancelled? I don't think so)

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.11 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by mrnugget** [comment]
Fixed by #7036
