### ISSUE TITLE
a8n: Add tracing to `previewCampaignPlan` and `createCampaign` mutations

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#6721]
Right now we don't use any tracing and don't record any metrics in these two mutations.

[`CreateCampaign`](https://github.com/sourcegraph/sourcegraph/blob/d56ce18d1aa571fb5665931383c5fc9bc691223e/enterprise/pkg/a8n/resolvers/resolver.go#L161) calls `a8n.Service.CreateCampaign` and `a8n.Service.RunChangesetJobs`. It talks to the PostgreSQL database, `gitserver`, and external services. All of these interactions should be traced and recorded.

[`PreviewCampaignPlan`](https://github.com/sourcegraph/sourcegraph/blob/d56ce18d1aa571fb5665931383c5fc9bc691223e/enterprise/pkg/a8n/resolvers/resolver.go#L415) calls the `run.Runner.Run` method, which kicks off `CampaignJobs` which talk to the `replacer` service. These interactions should be traced and recorded.

Both kick off long running processes (`a8n.Service.CreateCampaign`

**Comment by ryanslade** [comment]
@mrnugget @tsenart 
Why does this line create a new context?
https://github.com/sourcegraph/sourcegraph/blob/2f9c1db79e3c1b33147c402edd2c701e62842c36/enterprise/internal/a8n/resolvers/resolver.go#L205

I think we'll need to reuse the current context if we want it traceable

**Comment by mrnugget** [comment]
Because otherwise the request returning earlier would cancel it, I assume.

Now looking at this, I realize that maybe it doesn't make sense to trace this background operation in this way.

**Comment by ryanslade** [comment]
Also, how do you feel about moving that goroutine in to the service. Spawning it from the resolver feels wrong, it should probably be spawned from within `svc.CreateCampaign`

**Comment by mrnugget** [comment]
When in doubt I usually pull the goroutines out of functions/methods so that every call by default is blocking and doesn't spawn asynchronous operations. The caller can then decide what to do. So, it doesn't feel wrong to me, but that's also a subjective thing. Not a really hard opinion here :)

As to spawning it inside `svc.CreateCampaign` and thus also moving the `CreateChangesetJobs` inside that: @tsenart split the method up into two as a preparation for "persistent queue" or the point in time where we'll have a separate process, not `frontend`, call `CreateChangesetJobs` and run the jobs. That's easy to do with the current split. If we merge the methods again, we'd probably have to split them up again at some point, because we do want `CreateCampaign` to be blocking and happen in the GraphQL request code path and `CreateChangesetJobs` happen in the background.

Same thing applies here, though: this is a rather subjective thing and includes "anticipation of what we'll do in the future", making it extra brittle 😄

**Comment by ryanslade** [comment]
I feel that each method in the resolver should only be concerned with unmarshaling and preparing arguments passed to the service. The "business logic" of what to do from that point should be done in the service layer.

I'm fine to leave it as is for now as we'll likely be doing a lot of refactoring once we're further along anyway but just wanted to voice my opinion :smile:

**Comment by mrnugget** [comment]
> I feel that each method in the resolver should only be concerned with unmarshaling and preparing arguments passed to the service. The "business logic" of what to do from that point should be done in the service layer.

That sounds like a good convention. From that point of view, I agree with moving the goroutine inside the method.
