### ISSUE TITLE
a8n: Execute ChangesetJobs in parallel

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#6722]
Right now we don't launch `ChangesetJobs` in parallel because we don't want to trigger GitHub's abuse detection and run into the rate limit when creating pull requests.

https://github.com/sourcegraph/sourcegraph/blob/034cee47c83a7734cf04a4b5720717665b5a69db/enterprise/pkg/a8n/service.go#L103-L109

But since we use `github-proxy`, which acts as a semaphore of size 1 for all requests to Github, we could probably parallelize these requests.

We shouldn't overload the code hosts, but it's likely safe to use 2-3 goroutines to speed up the creation of campaigns.

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.11 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
