### ISSUE TITLE
Only update a Changeset in the database if it changed

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#6725]
Currently we're always updating database rows when syncing `Changsets` and their `ChangesetEvents` from code hosts:

https://github.com/sourcegraph/sourcegraph/blob/d56ce18d1aa571fb5665931383c5fc9bc691223e/enterprise/pkg/a8n/syncer.go#L120-L141

The problem is that this produces unnecessary load on the database, since we write to the database even if the `LoadChangesets` didn't update the changeset because they didn't change on the code host.

The simplest solution would be to compare whether the `Metadata` on a `Changeset` has changed (which includes its `ChangesetEvents` in a de-normalized form) and not update the database entry if it didn't change.

**Comment by malomarrec** [comment]
This ticket has been inactive for a while, and after checking in internally it appears to be outdated. Closing.
If you come across this and think this ticket shouldn't have been close, please reopen and leave a comment so that we can reconsider it!
