### ISSUE TITLE
a8n: Upsert ChangesetEvents from Bitbucket Server webhooks

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#6726]
This the Automation/Sourcegraph side of [RFC 45 - Extend Bitbucket Server Plugin](https://docs.google.com/document/d/1I3Aq1WSUh42BP8KvKr6AlmuCfo8tXYtJu40WzdNT6go/edit).

With the webhooks added in https://github.com/sourcegraph/bitbucket-server-plugin/pull/10 and their documentation added in https://github.com/sourcegraph/bitbucket-server-plugin/pull/11 we can add support for Bitbucket Server webhooks to Automation.

What we need to do is the Bitbucket Server equivalent of the GitHub webhook implementation: https://github.com/sourcegraph/sourcegraph/pull/5913

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.11 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by tsenart** [comment]
@kzh: Tentatively added this to the 3.12 milestone and our tracking issue and assigned you. We'll confirm after our roadmap planning meeting today if this gets planned for 3.12 or not.

On implementation: The key difference between the equivalent GitHub implementation (in the issue description) and this one is that with Bitbucket Server, Sourcegraph should be automatically creating the webhooks via the API you created, and storing their configuration (i.e. secret, etc) in Postgres. This is in contrast with the admin creating the webhook via the GitHub UI and telling us about the secret via external service config (we don't have a UI to create those webhooks).

**Comment by tsenart** [comment]
@kzh: There are still things to be done here, right? Documentation and creating the webhooks in particular. Any other things?

**Comment by kzh** [comment]
Documentation and creating the webhooks (#7730) will close this out. There are other potential polish work (more general to the BBS SG plugin), but that is not required in 3.12.

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.12 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
