### ISSUE TITLE
Go to definition "stack"

### ISSUE THREAD

**Issue by veeral-patel** [sourcegraph/sourcegraph#6730]
Thank you for Sourcegraph - and especially for open sourcing it!

### Problem

Say I visit a method and find a method call in it I'd like to learn about. I click "go to definition" on this method call.

In the function I just opened, there's another method call I'd like to learn about. I click "go to definition" on this method call.

After doing this a couple times, I want to go back to the original function I was looking at. To do this I need to click "Back" repeatedly.

### Proposed solution

In the UI, show a list of functions where you've clicked "go to definition". A stack, really. Then, I should be able to click on any of those functions to open it.

**Comment by attfarhan** [comment]
Thanks for opening this! We have had similar requests, and another issue tracking this: https://github.com/sourcegraph/sourcegraph/issues/6730

I'm going to close this issue in favor of the older one, please subscribe to that issue for updates!

**Comment by veeral-patel** [comment]
@attfarhan Sure!
