### ISSUE TITLE
Edit code in Sourcegraph

### ISSUE THREAD

**Issue by veeral-patel** [sourcegraph/sourcegraph#6731]
### Problem

When I'm exploring a repository on my laptop, I like to add comments to the code describing my understanding of what's going on. I can't do this in Sourcegraph though.

### Proposed Solution

Provide an "edit mode" where I can comment on a repository. You can make me fork this repo first before allowing edit mode. Also, let me commit my changes whenever I want (if I want to save my comments) from the UI.

**Comment by unknwon** [comment]
Hi, thanks for the feedback!

> Provide an "edit mode" where I can comment on a repository. You can make me fork this repo first before allowing edit mode. Also, let me commit my changes whenever I want (if I want to save my comments) from the UI.

Despite the usefulness of this feature, I believe this is precisely the functionality that a code host (e.g. GitHub.com) should provide. Sourcegraph is not a code host platform, nor the source of truth for a repository (at least now and near future), I don't think this is something we would consider support. cc @christinaforney

**Comment by veeral-patel** [comment]
@unknwon Got it, and thank you for developing Sourcegraph -- and for open sourcing it especially! I've been browsing through the source code recently to try to learn more about structuring Go projects from your code, though I don't really get how your code is organized :(

Anyways, yes, that makes sense, and I can see how developing this feature would be really hard to do. Maybe it can be developed in a future tool :)
