### ISSUE TITLE
GitLab Sourcegraph.com production readiness

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#6738]
This issue is to track the work we will do in the 3.11 release milestone to ensure Sourcegraph.com is production ready for GitLab.com using Sourcegraph.com as an opt-in code intelligence provider. An RFC still needs to be fleshed out, but the high level themes will be operational:

- Load shedding / rate limiting - If something goes wrong, can we isolate the effects.
- Observability (likely in a good place after distribution's work on this)
  - Dashboards on general health.
  - Dashboards on code intelligence health.
- Pre-emptive load test

This is all work we have done before, so hopefully we will just be reviving it.

**Comment by keegancsmith** [comment]
As part of getting a handle on the state of Sourcegraph.com I took a look into our sentry reports. They are very much useless at the moment since we don't send the actual errors. So I got started on better error reporting here https://github.com/sourcegraph/sourcegraph/pull/7039

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.11 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by keegancsmith** [comment]
Will get to this, just had a few bugs come up this week which wanted to sort out before branch cut.

**Comment by tsenart** [comment]
@christinaforney: How much of a priority is this at this point from your perspective?

**Comment by christinaforney** [comment]
We've been handling upticks in usage from HN front page, etc, and until GitLab makes Sourcegraph on by default for everyone I don't think it's worth prioritizing.
