### ISSUE TITLE
Search autocomplete: lang selection persists even after specifying the language via keyboard

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#6748]
I expected that once I hit return in the search to specify the lang, that the language selection list would disappear.

![ScreenFlow](https://user-images.githubusercontent.com/133014/69374648-51abeb00-0c5b-11ea-9f2a-8b04ab0907e6.gif)

**Comment by beyang** [comment]
@sourcegraph/web can we bump the priority of this to 3.11? I find it quite disruptive to the user experience of search to have the autocomplete menu hanging there, obscuring search results.

**Comment by lguychard** [comment]
That sounds reasonable. cc @hadrian-git

**Comment by hadrian-git** [comment]
@beyang @lguychard #6774
