### ISSUE TITLE
a8n: Implement code intelligence for external changesets

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#6749]
**WebApp**
- create hoverifier and pass to all `FileDiffNode` instances in the `CampaignDetails` component

**Backend**
- ExternalChangeset needs to have `head` and `base` fields so we can pull the hover info correctly

**Comment by eseliger** [comment]
@mrnugget we were thinking something like proposed in #6750 would be helpful for us

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.11 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
