### ISSUE TITLE
GitLab native integration j2d hashtag does not highlight the line

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#6751]
### Steps to reproduce:

1. Go to https://gitlab.com/gitlab-org/gitlab/blob/master/app/assets/javascripts/issue.js#L71
2. Hover on `addDelimiter`
3. Click **Go to definition** on the popup panel
3. It redirects you to https://gitlab.com/gitlab-org/gitlab/blob/master/app/assets/javascripts/lib/utils/text_utility.js#L12:14

#### Expected behavior:

Highlight line 12

#### Actual behavior:

Line highlighting is not showing

---

GitLab.com seems not able to handle the extra `:14` part, if I open https://gitlab.com/gitlab-org/gitlab/blob/master/app/assets/javascripts/lib/utils/text_utility.js#L12 directly, the line highlighting works.

**Comment by felixfbecker** [comment]
Fixed
