### ISSUE TITLE
When search hits unindexed repositories, a poor timeout UX / error is returned

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#6754]
A user ran a search query that hit a few unindexed repositories and just got this error back:

```
1 error occurred: * text search failed: no results found before timeout in index search (try timeout:3s)
```

This is a poor UX and does not match other cases where we return timeouts and provide the user with a clear description of what happened and button/link to add `timeout:3s` to their query.

Reported by a user @ HS:407948923 (https://app.hubspot.com/contacts/2762526/company/407948923)

**Comment by slimsag** [comment]
Note: we do have a better UX for search timeouts, it just isn't being used here for some reason.

**Comment by slimsag** [comment]
Poor dev's workaround: configure a search scope in the global settings (NOT site settings):

```
"search.scopes": [
    {
      "name": "Increase timeout:3s",
      "value": "timeout:3s"
    }
]
```

A button will then appear a little bit above the error so you can just click `Increase timeout:3s`:

![image](https://user-images.githubusercontent.com/3173176/69380973-f2f16c00-0c70-11ea-8477-57e10ee44c88.png)

This of course is still not a good solution (you've already hit an error, gotten confused, and had a bad experience)

**Comment by dadlerj** [comment]
Reported by https://app.hubspot.com/contacts/2762526/company/623971957

**Comment by dadlerj** [comment]
@slimsag just to check, the repos here being "unindexed" (as you wrote above) was because they were being re-indexed when the search occurred? Or were they newly added? Or something else?

Curious if this might occur in the normal course of usage, or if this was some edge case.

**Comment by slimsag** [comment]
> was because they were being re-indexed when the search occurred? Or were they newly added? Or something else?

It could be any of these. It was occurring in the course of normal usage, though, yes. i.e. not in all searches, but in some.

**Comment by dadlerj** [comment]
Thanks 👍 any reason to believe that this is related to a recent change? Let me know if you have any specific suggestions for users — otherwise, sounds like the next step here is to just have better error logging?

**Comment by slimsag** [comment]
Clarification: I know the following for certain:

1. This happened on 3.9.4 but I have not observed it on prior versions. It *could* be a regression, but I have no reason to believe so.
2. When this happened, I noticed several repositories being reported as missing / timed out. When the issue stopped happening on the same search query, the repositories were no longer missing / timed out. It is possible this is not related to indexing.
3. I see that our default timeout is 1.5s here: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@d501db0620b5915b2e072c09f3b913cf5e1fa044/-/blob/cmd/frontend/graphqlbackend/zoekt.go#L51

It is possible that with more things going on in zoekt (symbol indexing, maybe peaks of user requests) we are just exceeding that 1.5s timeout.

**Comment by slimsag** [comment]
As for customers/users who run into this, I would suggest the following:

- What version of Sourcegraph they are on
- How many indexing repositories show up at https://sourcegraph.example.com/site-admin/repositories?filter=needs-index
- When this error appears, do any repositories appear as timed out or missing in the web UI? example:

![image](https://user-images.githubusercontent.com/3173176/69467677-4f728b00-0d46-11ea-877f-e0ea9572d319.png)

**Comment by slimsag** [comment]
Unfortunately, it appears my workaround mentioned above is incorrect. When this error appears, it prevents the display of search chips entirely so you just get this:

![image](https://user-images.githubusercontent.com/3173176/69998053-bc3e1000-1512-11ea-9855-7e5fcac86394.png)

**Comment by dadlerj** [comment]
From https://app.hubspot.com/contacts/2762526/company/623971957

* 3.9.1
* 
>Ah thanks - If I get the "no results found before timeout" error,  I don't see anything about timed out repos.
>But if I switch to the "Diffs" tab for results, I see this:
>("<REDACTED (nearly 100%)> repositories timed out")
>It seems to vary -- I reloaded a few times and saw "<REDACTED (also nearly 100%)>" or even higher.  And the "Commits" tab only says 5 timed out.

Looks like repos timing out wasn't the issue for this customer. The diff search issue is obviously separate, and related to https://github.com/sourcegraph/sourcegraph/issues/5519

**Comment by slimsag** [comment]
>  If I get the "no results found before timeout" error, I don't see anything about timed out repos.

This seems to indicate this user is hitting this issue AND #5519

**Comment by slimsag** [comment]
Even weirder, we have a third UX apparently for this:

![image](https://user-images.githubusercontent.com/3173176/69998520-bc8adb00-1513-11ea-9dd5-00a91539a196.png)

link: https://k8s.sgdev.org/search?q=ERRORF_EFG&patternType=literal

**Comment by slimsag** [comment]
Reproduction of original issue on k8s.sgdev.org:

![image](https://user-images.githubusercontent.com/3173176/69998630-f9ef6880-1513-11ea-9696-8e455f1c9cb1.png)

link: https://k8s.sgdev.org/search?q=LICENSE_KEY_MANAGEMENT&patternType=literal
