### ISSUE TITLE
It is difficult to know when basic code intel's global symbol search is off

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#6755]
Basic code intel can do cross-repository global symbol searches to find definitions. There is an option to turn this off in the global settings that was added in https://github.com/sourcegraph/sourcegraph-basic-code-intel/pull/123:

```
"codeIntel.globalSymbolSearch": false
```

This toggle was added to aid in debugging what was thought to be a perf issue related to this feature for a customer. This was back when symbol search was unindexed, so doing global symbol searches was quite an expensive / heavy operation. Now that we have indexed symbol search, it seems safe to remove this option. In lieu of that (if someone has a good reason to keep it), we need to make it much more clear when this option is off or not:

A user reported basic code intel hovers not working, and it took me/Chris 30 minutes to figure out that the problem was effectively just that this option had been disabled and not re-enabled by accident.

**Comment by chrismwendt** [comment]
Do we have any other customers who intentionally have disabled global symbol search? I don't know of any, but that would be a blocker.

We can easily bring the setting back (it's an extension-only change), so there's little cost to removing it.

**Comment by slimsag** [comment]
@chrismwendt I do not believe so, and if they do I would be willing to place a hefty bet that it is disabled by accident if so.
