### ISSUE TITLE
repohascommitafter autocomplete suggestions don't have quotes

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#6758]
- **Sourcegraph version:** Sourcegraph.com

#### Steps to reproduce:

1. Visit sourcegraph.com/search
2. Type `repohascommitafter:`
3. Click either of the suggestions (1 week ago, 1 month ago)
4. See that the results appear without quotes around them

![image](https://user-images.githubusercontent.com/5589410/69391431-a1a0a700-0c87-11ea-85bb-0d1ba80dd699.png)

**Comment by hadrian-git** [comment]
@attfarhan based on literal search, it's supposed to be without quotes, right?

**Comment by attfarhan** [comment]
If multiple words are the input, they must always be wrapped in quotes, in both modes. Otherwise they get treated as part of the match.
