### ISSUE TITLE
a8n: replacer service responds with 503 with cold cache

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#6766]
When previewing a campaign over a large number of repositories and the `replacer` cache in `/tmp/replacer-archives` is empty, `replacer` might respond with `503 Service Unavailable`.

Example: with a fresh Sourcegraph instance, locally, I ran the following CampaignPlan:

```
{
    "scopeQuery": "repo:github",
    "matchTemplate": "foobar",
    "rewriteTemplate": "barfoo"
}
```

That resulted in 173 campaign jobs.

Out of those, 17 resulted in the mentioned error:

```
# SELECT error FrOM campaign_jobs WHERE error != '';
                                    error
-----------------------------------------------------------------------------
 unexpected response status from replacer service: "503 Service Unavailable"
 unexpected response status from replacer service: "503 Service Unavailable"
 unexpected response status from replacer service: "503 Service Unavailable"
 unexpected response status from replacer service: "503 Service Unavailable"
 unexpected response status from replacer service: "503 Service Unavailable"
 unexpected response status from replacer service: "503 Service Unavailable"
 unexpected response status from replacer service: "503 Service Unavailable"
 unexpected response status from replacer service: "503 Service Unavailable"
 unexpected response status from replacer service: "503 Service Unavailable"
 unexpected response status from replacer service: "503 Service Unavailable"
 unexpected response status from replacer service: "503 Service Unavailable"
 unexpected response status from replacer service: "503 Service Unavailable"
 unexpected response status from replacer service: "503 Service Unavailable"
 unexpected response status from replacer service: "503 Service Unavailable"
 unexpected response status from replacer service: "503 Service Unavailable"
 unexpected response status from replacer service: "503 Service Unavailable"
 unexpected response status from replacer service: "503 Service Unavailable"
```

**Comment by ryanslade** [comment]
This is being caused by a short timeout when fetching zip files. Our default timeout is 500ms and we're not sending an override.

It's made worse by the fact that we only allow 10 concurrent zip fetches so with many repos some could time out simply waiting in the queue.

I think all we can really do is increase the timeout and maybe reduce the number of concurrent calls we make to replacer

**Comment by mrnugget** [comment]
> It's made worse by the fact that we only allow 10 concurrent zip fetches so with many repos some could time out simply waiting in the queue.
> 
> I think all we can really do is increase the timeout and maybe reduce the number of concurrent calls we make to replacer

Don't we restrict the number of calls by having a fixed set of workers in the `Runner`?

I think increasing the timeout to `1s` or `2s` is fine.

**Comment by ryanslade** [comment]
Yes, we currently restrict it to 8 workers per runner. We'll probably run into more issues when we have larger clients using this and more than one runner is running concurrently. At that point we'll  need to look into some more advanced work scheduling perhaps using persistent queues as you've mentioned before.
