### ISSUE TITLE
Add cache-busting context item

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#678]
We have multiple internal caches inside of Sourcegraph:
- [GitLab authz cache](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@999624ce8f1f523a682581f3fe8acb7ca484c6fa/-/blob/cmd/frontend/internal/authz/gitlab/gitlab.go#L38:2)
- [GitLab client cache](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@999624ce8f1f523a682581f3fe8acb7ca484c6fa/-/blob/pkg/extsvc/gitlab/client.go#L33:2)
- other caches

In the case of some caches, it would be desirable to invalidate/bypass/refresh the cache (or at
least a cache entry) if an end-user triggers a hard-refresh. For example, if a user adds a new
repository to a GitLab instance and then attempts to add that repository to Sourcegraph, they may
see a permissions error for as long as the GitLab authz cache TTL duration (default 3 hours).

Proposal: set a context item `UserHardRefresh` that gets set if an inbound HTTP request has header
"cache-control: no-cache". Individual caches can check for this item. The recommended behavior is
"invalidate and refresh the cache entries associated with the current request and the current user,
while leaving other cache entries intact". But it will be up to individual caches to deal with this
item accordingly. Not all caches have to use the item, just the ones that should be bypassed on an
end-user hard-refresh.

**Comment by beyang** [comment]
@nicksnyder @sqs @keegancsmith thoughts on the above? I'd like to implement this ASAP, as I think it would significantly improve the UX of repo permissions.

**Comment by keegancsmith** [comment]
- Is there a way to be less aggressive with our caching rather?
- Could we have a much less aggressive cache for missing entries?

By adding cache invalidation it makes things much trickier to understand. I would try avoid it TBH. If we find there is no alternative, then we need some good metrics/debuggability on it.

FYI Repo-updater has the knowledge of a new repo existing, maybe that is a use case for it understanding perms as well. OR maybe it can inform another system?

**Comment by nicksnyder** [comment]
> Could we have a much less aggressive cache for missing entries?

This feels simpler to me (i.e. if a user explicitly asks for a repo that we don't know permissions for, we implicitly treat that as a request to refresh permissions).

**Comment by beyang** [comment]
The issue is that permissions are stored per user, not per repository. This is dictated by the way permissions are fetched from the GitLab API, which is by the user ("get me all repositories the current user can access"), rather than by the repository ("get me all users who can access this repository").

It may be viable to fetch permissions by repository:
- GitLab "inherited members" API: https://docs.gitlab.com/ee/api/members.html#list-all-members-of-a-group-or-project-including-inherited-members
- GitHub "list collaborators" API: https://developer.github.com/v3/repos/collaborators/#list-collaborators

However, this still wouldn't eliminate the issue of "I gave this person access to this repository, but why don't they yet have access to Sourcegraph". The upper bound for code host permissions API QPS is `U*R / P*T`, where `U` is the number of active users, `R` is the number of repositories, `P` is the max `per_page` value, and `T` is the TTL in seconds. For `per_page=100`, 100 users, 1k repos, TTL=1h, QPS would be 0.28. For 1k users, 10k repos, TTL=1h, QPS is 28.

An hour is a long time to wait for that and it would be nice to punch a hole through the cache in that case. HTTP already offers a way to do that to the end-user, so why not propagate that through our system?

**Comment by keegancsmith** [comment]
> HTTP already offers a way to do that to the end-user, so why not propagate that through our system?

Indeed it does, I wonder how often it would trigger though (depending on browser / src cli / etc).

I think making this part of the context is the wrong thing to do. Rather, can we not explicitly do it like we do on Sourcegraph.com when a user visits a repo we don't know about. In that case we do an API request to see if the repo does indeed exist. Could we do the same as a user, then if the user can see it we bust the cache?

**Comment by keegancsmith** [comment]
I was thinking that if a user does not have access to a repo, but tries to directly access it, that triggers the refresh? We had the same model when we supported private repos on sourcegraph.com. From the codes perspective it was a 404 no matter if the repo existed or not, and we treated it the same w.r.t. looking upstream for it.

**Comment by keegancsmith** [comment]
Searches just use `db.Repos.List` which shouldn't trigger that. I am suggesting we use the same logic we use for repo discovery on Sourcegraph.com. When a user explicitly visits a repo URL that 404s for them, we check if the upstream repo is accessible for them.

**Comment by beyang** [comment]
Currently, authz providers are agnostic of whether a request is tied to a visit to a repo page vs. some other request. How does the repo discovery logic handle this? We cannot rely on repository existence here because (1) any repo passed to an authz provider will already exist and (2) we need to handle cases where the repo already existed and the permissions have changed to be more permissive.

Is the proposal here to add a method to the `authz.Provider` interface like `Refresh(user, []repo)`? Such a method, when invoked, should refresh the cache entry for the user, ensuring that the requested repos are up-to-date. It would then be up to the frontend handlers to recognize an end-user repo page 404 and invoke the method.

**Comment by beyang** [comment]
Another consideration is that we currently have multiple caches. For instance,
* The authz provider will cache info.
* It in turn uses an API client that also caches certain API responses.
* The API client, for all I know, might use a caching HTTP client.

Each of these caches exists because it can't rely on the caching in the layer below it to guarantee SLAs it has. For instance, the authz provider needs to check permissions on every request, but it doesn't want to issue a code host API request on every request, because it would hit the API limit and slow down the request. The API client caches [certain info](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@c77323e93591abd5b7586f1a2401730f3a430226/-/blob/pkg/extsvc/github/repos.go#L320:4) to avoid hitting the API rate limit. It can't rely on HTTP-level caching to achieve this constraint.

It seems like the question boils down to one of two high-level approaches:
1. Each caching layer has an explicit API for opting out of caching (e.g., `authz.Provider` could have a `InvalidateCache(user, repo)` method or each request could take a `noCache` argument as either a positional argument or options struct field).
2. Each caching layer buys into an implicit setting that suggests to it caching behavior. This setting would probably have to be passed around via context, since that's the only thing that spans up and down the different layers.

These seem to me to be the tradeoffs:
1. The explicit option makes it clear to the client what the cache invalidation behavior is, but it also requires designing and adding such an API to each layer.
2. The implicit option makes the cache invalidation behavior more, well, implicit. But it avoids the need to add explicitly defined cache invalidation endpoints at each layer.

The latter option seems easier in the short term. As author of an authz provider, I'd like to support the ability to bypass all caches when we need to (e.g., when a request uses permissions that probably have been recently updated). It's more work to add a cache invalidation API to the lower layers (option 1) to support what I need. If we use a context item (option 2), that eliminates the need to design cache invalidation APIs, but on the other hand, it masks the complexity of the cache invalidation logic. At least with option 1, whatever complexity is introduced into the cache invalidation logic will be reflected in complexity in the API. In the option 2 worst case, the cache invalidation logic becomes increasingly complex and none of that complexity is reflected in the interface, and what will happen is that client code will just over-eagerly set the no-cache context item defensively, which will eliminate the whole point of caching in the first place.

Upon this reflection, I think a better solution here is to support an explicit cache invalidation API similar to the proposal in the preceding comment:

> Is the proposal here to add a method to the `authz.Provider` interface like `Refresh(user, []repo)`? Such a method, when invoked, should refresh the cache entry for the user, ensuring that the requested repos are up-to-date. It would then be up to the frontend handlers to recognize an end-user repo page 404 and invoke the method.

This will require supporting cache invalidation in `authz.Provider` and the `Client` types in the `extsvc` packages.

**Comment by beyang** [comment]
Closing in favor of https://github.com/sourcegraph/sourcegraph/issues/937
