### ISSUE TITLE
GitLab integration: colons in anchors not supported in GitLab

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#6786]
Reported by a user.

1. Visit https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/current_settings.rb#L1:1 and note that the page doesn't scroll at all
2. Visit https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/current_settings.rb#L1 and note that you are correctly scrolled to the first line.

Apparently GitLab doesn't support anchors containing colons. All of our go to definition links in the GitLab integration append the symbol's location on the line to the anchor, so go to def scrolling is broken.

**Comment by unknwon** [comment]
Looks like the same issue here: https://github.com/sourcegraph/sourcegraph/issues/6751

**Comment by felixfbecker** [comment]
Closing as duplicate
