### ISSUE TITLE
Documentation for building OSS and enterprise images is missing

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#6790]
There is currently no documentation for building OSS and enterprise images outside of our CI pipeline. This is related to #6789 (which is about actually being able to do it, this issue is about the documentation for how to do it).

This is particularly bad in the OSS case since we do not currently publish OSS images on Docker Hub.

**Comment by jonathanmorley** [comment]
I have a couple of issues (#43300 and #43203) that i believe are related to web code not being correctly packaged into the frontend when building OSS. Documentation around building OSS sourcegraph correctly would be very helpful to help resolve these issues
