### ISSUE TITLE
Followups to finish migration of repo uri -> name

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#680]
We have deprecated calling the repository name (the value like `github.com/foo/bar`) the "URI" since April 2018. Now it is just called the repository "name".

There are more things we must do to complete the switch:

- January 2019: remove the GraphQL `RepoOrderBy.REPO_URI` value from our GraphQL API and [make src-cli use `REPOSITORY_NAME` not `REPO_URI`](https://sourcegraph.com/github.com/sourcegraph/src-cli@276dbd483b4a50d431fd6416ee1af3dbc52f3349/-/blob/cmd/src/repos_list.go#L99:20)

We can't do these until January 2019 per our deprecation policy.

**Comment by nicksnyder** [comment]
Can we do this for 3.0 or do we need to wait for 3.1?

**Comment by keegancsmith** [comment]
src-cli unfortunately is still not updated, so we can't remove this until it has had time to roll out. Sent https://github.com/sourcegraph/src-cli/pull/43
