### ISSUE TITLE
Code discussions notifs from dogfood not received

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#682]
I have not been receiving code discussions notifications recently from dogfood.

I see error logs:

```
t=2018-11-04T10:29:16+0000 lvl=eror msg="discussions: mailreply worker: error while working" error="NewMailReader: Login: Invalid credentials (Failure)"
```

**Comment by slimsag** [comment]
Pretty sure this was fixed. If not, it is a configuration issue anyway and we haven't found it important enough to fix. Closing.
