### ISSUE TITLE
Search suggestions: add common, static suggestions

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#6837]
#### Feature request description

In [RFC 14](https://github.com/sourcegraph/sourcegraph/pull/6836#pullrequestreview-322509521) and [RFC 15](https://github.com/sourcegraph/sourcegraph/pull/6836#pullrequestreview-322509521), it is shown that certain search filters would return commonly used suggestions. This is already done for the `lang:` filter. 

In particular, the `file:` filter is shown to suggest our default search filters such as "test files", "non-test files", "markdown files", etc.

cc @christinaforney

**Comment by unknwon** [comment]
Hmm, could you give more details about what's the actual feature request? i.e. what filters are wanting to have default suggestions?

PS: If these suggestions are static, it should be done all in web codebase as we did for RFC 14.

**Comment by attfarhan** [comment]
The request is to add these values as suggestions to the `file:` filter:
- Test files (`file:(test|spec`)
- Non-test files (`-file:(test|spec) `)
- Text files (`file:\.(txt|md)$ `)

These static values would be shown when the `file:` filter is detected, before any other character or value has been typed. These are useful filters for users to be aware of and easily use. 

@christinaforney, any other filters that should be added?

**Comment by unknwon** [comment]
> The request is to add these values as suggestions to the `file:` filter:
> 
> * Test files (`file:(test|spec`)
> * Non-test files (`-file:(test|spec) `)
> * Text files (`file:\.(txt|md)$ `)
> 
> These static values would be shown when the `file:` filter is detected, before any other character or value has been typed. These are useful filters for users to be aware of and easily use.

I thought this was part of RFC 14? Or it gets removed somehow?...

**Comment by attfarhan** [comment]
It is in RFC 14, but it doesn't appear that it was implemented

**Comment by unknwon** [comment]
I believe it was in @hadrian-git's original PR, then may get removed.

**Comment by hadrian-git** [comment]
PR sent :incoming_envelope: I removed it just because we started using the `SearchSuggestions` API (which was added on a later revision of the RFC) and thought it to no longer be necessary, but it's simple to add back so PR is there.

**Comment by unknwon** [comment]
![](https://media3.giphy.com/media/3o7TKRhoMxNj7LoBEI/giphy.gif?cid=5a38a5a20c40e280a0a363ef43899b6b44b927e8c3be1e50&rid=giphy.gif)
