### ISSUE TITLE
INDEXED_SEARCH_SERVERS + HOSTNAME is weird / kind of assumes Kubernetes

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#6846]
In our case of deploy-sourcegraph-docker, `zoekt-indexserver` and `zoekt-webserver` are deployed as two individual containers. By contrast, in Kubernetes, the are under one `indexed-search` pod.

In the docker case, if we configure things like you might expect at first glance:

```
# frontends
INDEXED_SEARCH_SERVERS='zoekt-webserver-0:6070

# zoekt-webserver containers
HOSTNAME=zoekt-webserver-0:6070

# zoekt-indexserver containers
HOSTNAME=zoekt-indexserver-0:6072
```

Then you will run into this error in the frontend logs:

```
t=2019-11-26T03:19:01+0000 lvl=eror msg="API HTTP handler error response" method=POST request_uri=/.internal/repos/index status_code=500 error="hostname \"zoekt-indexserver-0:6072\" not found in Endpoints{\"zoekt-webserver-0:6070\"}" trace=
```

To fix this, `zoekt-indexserver` must confusingly have its hostname configured to be the same hostname as `zoekt-webserver`. This kind of makes sense in Kubernetes where the hostname is just `indexed-search-0` for example -- but in other contexts it `HOSTNAME` starts to look very confusing:

- The hostname for zoekt-indexserver _appears_ to be wrong unless you know this fact.
- Why would the HOSTNAME include a port?

My suggestion to fix this would be to reword `HOSTNAME` to something else like `INDEXED_SEARCH_INSTANCE` -- WDYT? (we could keep backcompat for `HOSTNAME` in the interim obviously)

**Comment by keegancsmith** [comment]
Agreed, `HOSTNAME` is no good. What do you think of `NODE_NAME` instead of `INDEXED_SEARCH_INSTANCE`?

**Comment by slimsag** [comment]
Sounds perfect!

**Comment by keegancsmith** [comment]
`NODE_NAME` is now supported. Built and pushed new images:
- `sourcegraph/zoekt-indexserver:0.0.20191204145522-b470e5f`
- `sourcegraph/zoekt-webserver:0.0.20191204145231-b470e5f`
