### ISSUE TITLE
a8n: Campaign type to remove NPM credentials

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#6852]
This is the first campaign described in [RFC 73: Campaigns to find and remove credentials](https://docs.google.com/document/d/143FIe1Tak4_YPPuOuEzuobTQW09ZU85WfOCdZkNwIVQ/edit#heading=h.b5eblutsndzz)

The JSON arguments for this new campaign type would look like this:

```json
`{"matchers": [{"type": "npm"}], "scopeQuery": "repo:foo"}`
```

Default value:

```json
{"matchers": [{"type": "npm"}]}
```

A campaign of this type should then find tokens that match this regex:

https://sourcegraph.com/github.com/sourcegraph/sourcegraph@a8n/wip/-/blob/extensions/enterprise/sandbox/src/npmCredentials/scanner.ts#L8

It then creates a diff where the token is removed (e.g., `foo:_auth=mytoken` on a line becomes `foo:_auth=`).

---

Thoughts on implementation (copying my comments from the Google Doc here):

> We could "just" search for the regex, find the matching files and create the diffs in memory.

> Update on this: it's probably a tad harder than that, because our current architecture doesn't allow passing on line-specific search results. Instead, CampaignJobs run on repositories. So, in order to allow what I proposed above (search for regex, group results by repo, for each result in repo, construct diff in memory) we'd need to change the architecture.

> But what we could do, without changing architecture, is to just search twice: once to get a list of repos and then each job searches per repo again to get the specific location of the token.

Why doesn't "our current architecture [...] allow passing on line-specific search results"?

> Look at this snippet of code:

https://github.com/sourcegraph/sourcegraph/blob/ba0c7370e2b9ae050898374c8536601b9bbaaf22/enterprise/pkg/a8n/run/runner.go#L127-L142

> That is how we go from "scopeQuery + campaign-specific search query" to a list of repositories. For each repository, we create a campaign job, with repo_id, rev, base ref.

> Later, when the jobs run, there's currently no way to get back to the line-specific search results. Because here we convert search results into "repositories":

https://github.com/sourcegraph/sourcegraph/blob/ba0c7370e2b9ae050898374c8536601b9bbaaf22/cmd/frontend/graphqlbackend/search.go#L772-L794

> In order to pass specific results to campaign jobs, we need to persist those somewhere and I think that's non-trivial.

> Again, for now we could just search twice: search for a list of repositories once and then for each repository, each job searches again for the specific tokens (with the `repo:<name of repo>` filter in the query).

**Comment by tsenart** [comment]
> It then creates a diff where the token is removed (e.g., foo:_auth=mytoken on a line becomes foo:_auth=).

I haven't read the respective RFC in depth, so bear with me — is the plan to create a diff without calling an API to revoke the token or re-writing history? If so, the token will still be in git history and readily available to an attacker. What's the story here?

**Comment by mrnugget** [comment]
>  is the plan to create a diff without calling an API to revoke the token or re-writing history? If so, the token will still be in git history and readily available to an attacker. What's the story here?

The sentence you quoted is taken from the RFC. I think your questions here should be answered in the RFC, because they're not just an implementation detail.

**Comment by tsenart** [comment]
OK, let's discuss it there then! I'll post my question there in the relevant paragraph. cc @sqs

**Comment by mrnugget** [comment]
#6893 implements the first version of the workflow as described in [RFC 73](https://docs.google.com/document/d/143FIe1Tak4_YPPuOuEzuobTQW09ZU85WfOCdZkNwIVQ/edit#).

It has some performance shortcomings that are described in the PR description of #6893 itself.

My next steps on this will be to
1. investigate performance & stability improvements and possibly implement those
2. start implementing the "Enhanced workflow" as described in RFC 73, which includes making the replacement of the token with a dummy string optional and adding a campaign type specific addendum to the pull request body.

**Comment by mrnugget** [comment]
https://github.com/sourcegraph/sourcegraph/pull/6981 implements the 1/2 of the "Enhanced workflow" described in RFC 73.

The second part of the enhanced workflow includes adding campaign-type specific text to the end of the Changeset body we create on the code hosts. (I'm thinking that this won't be uncommon in the future.)

Here's what I had in mind to implement that:
1. Extend the `campaignType.generateDiff` method interface from
    ```go
    generateDiff(context.Context, api.RepoName, api.CommitID) (diff string, err error)
    ```
    to
    ```go
    generateDiff(context.Context, api.RepoName, api.CommitID) (diff string, body string, err error)
    ```
2. Persist the returned `body` next to the `diff` on `campaign_jobs`
3. When creating the changeset on the code host, we add `CampaignJob.Body` to its body.

The only thing that I'm not sure about yet is this part of RFC 73:

> In the changeset description, add a list (with `- [ ]` checkboxes for code hosts that support checklists in Markdown) of the removed secrets in the changeset. 

That means at some point we need to make the body of the `Changeset` dependent on which code host it's created on.

Question is: does the `CampaignType` already know about the code host? We could rather easily do that by changing the interface from

```go
generateDiff(ctx context.Context, repo api.RepoName, commit api.CommitID) (diff string, err error)
```

to this

```go
generateDiff(ctx context.Context, repo *repos.Repo, commit api.CommitID) (diff string, body string, err error)
```

Then each campaign type can check which external service the repo is from and create its `body` accordingly.

I thought that maybe that is mixing unrelated concerns (does a `CampaignType` have to know about a code host?) but then again, I bet future campaign types will have to know more about a repository.

Other options:
- **a)** CampaignType always adds a body (including `- []`) and when creating the changeset we decide to ignore the body or not. Con: we can't easily ignore certain parts of the body. But can we maybe sanitize it, and go from "Github flavored markdown" to "Markdown?"
- **b)** CampaignType doesn't return a string, but a slice of string. When creating the changeset we then add these to the changeset body depending on the codehost. Con: this seem really TODO-list specific.
- **c)** CampaignType returns a struct that implements a `CampaignTypeResult` interface which has methods `Diff` and `Body(codehostType string)`.

**Comment by tsenart** [comment]
> generateDiff(context.Context, api.RepoName, api.CommitID) (diff string, body string, err error)

What is a `body` in the context of `generateDiff`? I think we may be adding too many concerns to this interface. What would it look like to add a separate method to the `CampaignType` that returns a Changeset's metadata (i.e. body, title, etc)?

> I thought that maybe that is mixing unrelated concerns (does a CampaignType have to know about a code host?) but then again, I bet future campaign types will have to know more about a repository.

I think it's fine for us to just default to Markdown for now. Perhaps in the future we can automatically convert Markdown to whatever the code host supports in a higher layer. Then again, which code hosts we integrate with don't support Markdown?

**Comment by mrnugget** [comment]
> What would it look like to add a separate method to the `CampaignType` that returns a Changeset's metadata (i.e. body, title, etc)?

Thought about that, too. That would change the overall structure a bit, since right now we use a single instance of a `CampaignType` for generating multiple diffs. The `campaignType` is saved on the `Runner` and the `CampaignType` itself only has a single piece of state that's fine to transfer between repositories: the arguments.

In order to have multiple methods that return the data for a single repository, we need to introduce more state on the CampaignType (since the `Body` method would need access to the tokens found in the `generateDiff` method, etc.)

> I think it's fine for us to just default to Markdown for now. Perhaps in the future we can automatically convert Markdown to whatever the code host supports in a higher layer. Then again, which code hosts we integrate with don't support Markdown?

(Hmmm, I don't see how _that_ paragraph is relevant to the paragraph of mine that you quoted? What am I missing?)

I don't think it's about Markdown, but about supporting checkboxes in Markdown. Sorry, I could've made that more clear. As far as I know, GitHub supports these checkboxes, but they are part of Github Flavored Markdown and Bitbucket Server doesn't support them: [see here](https://bitbucket.sgdev.org/projects/SOUR/repos/automation-testing/pull-requests/19/overview)

**Comment by tsenart** [comment]
> Thought about that, too. That would change the overall structure a bit, 

Got it. The approach you proposed sounds good to me then.

>  Sorry, I could've made that more clear. As far as I know, GitHub supports these checkboxes, but they are part of Github Flavored Markdown and Bitbucket Server doesn't support them: 

Can we have each `Source` automatically convert Markdown to its flavour?

**Comment by mrnugget** [comment]
> Can we have each `Source` automatically convert Markdown to its flavour?

That's a good idea! For now, in order to avoid the deep pit of text sanitization or conversion, we can simply "downgrade" from GFM to Markdown in non-GitHub codehosts.
