### ISSUE TITLE
ci: use asdf to lock versions of frequently used build tools (go and node)

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#6862]
In [multi-stage Docker files](https://github.com/sourcegraph/sourcegraph/pull/5745), I attempted to make our builds completely hermetic by locking our build tools’ versions and generating all artifacts inside the docker build process. This turned out to be too slow to merge due to problems with our existing Docker infrastructure. 

In the meantime, we can achieve a weaker version of reproducibility by locking some of the build tools that we upgrade the most often: Go and Node. 

I propose that we use https://github.com/asdf-vm/asdf to manage the versions of these tools:

- It's a well-supported project
- It has a plugin system that supports multiple languages (Go, Node, etc.) as well as common tools (`hadolint`, `shellcheck`, etc.)
- It has a [configuration file](https://asdf-vm.com/#/core-configuration) that can be checked into the repository, and we can simply use `asdf install` to get the versions of that tool that are specified in the config file

**Comment by nicksnyder** [comment]
What is the effect of `asdf install`? Does it replace the version of `go` that is used on my command line globally or just whenever I am within the sourcegraph/sourcegraph directory?

**Comment by ggilmore** [comment]
I am pretty sure asdf has the same semantics as pyenv (e.g. it looks for an
environment variable, then in all the parent folders for the version
configuration file, and then it falls back to whatever’s in the rest of
your path (if present)

**Comment by ggilmore** [comment]
Oh sorry, I didn’t answer your exact question. I’m pretty sure that asdf
manages its own installation directory for all the different go and node
versions
