### ISSUE TITLE
Exclude directories from search results

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#6870]
Requested by https://app.hubspot.com/contacts/2762526/company/464956351

Customer scenario:

> Hi, this is not super urgent, but, is there a way to unlist a repository (or even better, a directory within a repository) from Sourcegraph?
> The repository REDACTED_REPO_NAME does ML on code and contains a dataset that duplicates large amounts of code from two large repos. This is causing problems with Sourcegraph surfacing the code there rather than in the original repos and confusing people searching for the original code.
> Ideally, we should be able to index the mobile/SmartLinter repo but not index the duplicated code under data/. Failing this, we would be fine with un-listing that repo from Sourcegraph altogether. Advice?

Possible solution: add a `.sourcegraph/config.json` or `.sourcegraphignore` file that allows a repository to configure Sourcegraph's behavior, including whether or not certain directories are excluded (by default) from search results.

**Comment by beyang** [comment]
Can @sourcegraph/core-services triage this?

**Comment by unknwon** [comment]
Added to core services team sync notes for triaging.

**Comment by keegancsmith** [comment]
Nice idea. Would require adding support into each of our search engines for performance reasons. But we can maybe do a two pronged approach:
- Filter when indexing a repo in zoekt and searcher
- Filter out results for search engines which don't support the setting.

**Comment by keegancsmith** [comment]
Apologies, have to deprioritize for 3.13, will revisit for planning in 3.14. The work on my plate for 3.13 has expanded and it looks unlikely I will finish this before then.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.13 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by keegancsmith** [comment]
I'm backlogging. I switched focussed on more pressing customer issues / the impromptu London Core Services meetup took up my time.

**Comment by keegancsmith** [comment]
@rvantonder this seems like a good "small->medium" sized task. What do you think about someone on the search team picking this up in 3.16 (or maybe 3.17). cc @asdine

**Comment by rvantonder** [comment]
Yeah seems reasonable to me!

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by tsenart** [comment]
@asdine: What's the status on this?

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by dadlerj** [comment]
Requested by https://app.hubspot.com/contacts/2762526/company/1799582875 (https://sourcegraph.slack.com/archives/C0169PH49L5/p1594927456005900)

**Comment by rvantonder** [comment]
Ack @dadlerj I'll push for doing this in 3.19.

**Comment by dadlerj** [comment]
Thanks! Just to add context, I definitely don't think this is urgent (for the company I linked above, at least). It may be a good fit for 3.19 for other reasons, but I can certainly name some other feature requests that are more common or higher priority (from the CE perspective) if that would be helpful.

**Comment by asdine** [comment]
Thanks @rvantonder ! I'm gonna unassign myself from this one and assign it you

**Comment by dadlerj** [comment]
@stefanhengl https://app.hubspot.com/contacts/2762526/company/464956351 just asked about this again, and I was pleasantly surprised to see that you had picked it up :). Just to check, do you expect that this will be solved by using the existing .sourcegraph/config.json file? 

(See https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/CHANGELOG.md#L1983:92 for context)

**Comment by stefanhengl** [comment]
I haven't really started yet, but I would have picked .sourcegraphignore because the filename immediately conveys the file's purpose. However, I do see the issue of creating another file (next to config.json) that configures Sourcegraph's behavior. @dadlerj Do you have a strong preference, maybe based on conversations with customers?

**Comment by dadlerj** [comment]
Not at all! Totally up to you. The customer I mentioned above had reached out and asked about whether our .sourcegraph/config.json supported it. I think those config files may only be in use by 1 or 2 customers though, so I wouldn't think there's much of a benefit to building on top of them. Perhaps all sourcegraph-related config files could live in a .sourcegraph dir at the top of each repo? I don't know, I leave it up to you.

**Comment by keegancsmith** [comment]
We have other reasons for sourcegraph specific configuration. So nice
not to pollute the top-level directory (just like your $HOME has been
slowly moving towards using $XDG_CONFIG to store configuration).

I've also noticed how GitHub and others have also been moving in this
direction. eg GitHub now uses `.github` for anything related to it.

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
