### ISSUE TITLE
Problems in setting up Sourcegraph Server

### ISSUE THREAD

**Issue by ruhullahshah** [sourcegraph/sourcegraph#69]
- Issue type: Question
- Sourcegraph version: sourcegraph/server:2.7.6
- OS Version: Ubuntu 16.04
- Docker version: 
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm
Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false

- Error message:
✱ Sourcegraph is ready at: http://127.0.0.1:7080
14:38:47       frontend | telemetry proxy: 2018/05/04 14:38:47 http: proxy error: context canceled
14:39:05   repo-updater | t=2018-05-04T14:39:05+0000 lvl=eror msg="Error listing GitLab projects" url="projects?membership=true&order_by=last_activity_at&per_page=100" error="Get https://someURL?membership=true&order_by=last_activity_at&per_page=100: proxyconnect tcp: dial tcp: i/o timeout"
14:40:05   repo-updater | t=2018-05-04T14:40:05+0000 lvl=eror msg="Error listing GitLab projects" url="projects?membership=true&order_by=last_activity_at&per_page=100" error="Get https://someURL/api/v4/projects?membership=true&order_by=last_activity_at&per_page=100: x509: certificate signed by unknown authority"

- With the given information, I have a couple of questions,
1) After supplying the proxy settings through `docker run -e HTTP_PROXY=.....`, I still see a proxy error.
2) How do I workaround the issue of Sourcegraph not recognizing my self-signed GitLab server certificate.

I am not able to setup any repository for code search as of now. Some advice would be highly appreciated.

Thanks

**Comment by nicksnyder** [comment]
We will think about what the best solution is for this. In the meantime, you can try the workaround mentioned in https://github.com/sourcegraph/issues/issues/71

**Comment by ruhullahshah** [comment]
Thanks for the advice. It looks promising

**Comment by sqs** [comment]
@ruhullahshah You can use the `certificate` property in the `gitlab` site config (see https://docs.sourcegraph.com/admin/site_config/all#certificate-string).

You will also need to configure the certificate to be used when git cloning (which is a separate task, unfortunately, but we plan to address that). For that, the workaround in https://github.com/sourcegraph/sourcegraph/issues/71 that @nicksnyder 	mentioned will solve it for now.

Do these solve your problem?

**Comment by Antoine98** [comment]
+1
I have the same problem.
When i tried to set certificate option in external service for gitlab :
`certificate": "-----BEGIN CERTIFICATE-----
MIIDJzCCAg+gAwIBAgIQFn ...

-----END CERTIFICATE-----",`

I have this error : 
![image](https://user-images.githubusercontent.com/47435532/54656233-f4cec280-4b18-11e9-9c2f-f62bb554040d.png)

**Comment by nicksnyder** [comment]
@Antoine98 Can you try escaping the newlines in your certificate?

For example:
```json
"certificate": "-----BEGIN CERTIFICATE-----\nMIIDJzCCAg+gAwIBAgIQFn\nfsdiwejfnikwe\n-----END CERTIFICATE-----"
```

**Comment by Antoine98** [comment]
@nicksnyder thank you, it's working now

**Comment by ovniomni** [comment]
Hello,

I know it's closed, but I need help in deploying the test Sourcegraph on my server. Whenever I run the command with the modified nginx.conf file https://docs.sourcegraph.com/admin/http_https_configuration 

I can't get it to start. it shows   x509: certificate signed by unknown authority

I do not understand the workaround involving the Dockerfile. Where can I find it? I am trying to pull from it. How can I change the Dockerfile if I am pulling from it.

3.31.0 is the version I am trying to get working.

I have my crt and key files in the ~/.sourcegraph/config/ dir
My CA file is also in /usr/local/share/ca-certificates.

Please help.

Thank you
