### ISSUE TITLE
Extreme logspam since switching to yarn workspaces

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#691]
Since switching to yarn workspaces there is an extreme amount of logspam from yarn that was not there before:

![image](https://user-images.githubusercontent.com/10532611/47996911-63772a80-e0fa-11e8-9daf-9ac7024755e8.png)

Some warnings also look legit, like the mismatching resolutions. Why are we using `resolutions` at all? I thought it was supposed to be removed

**Comment by chrismwendt** [comment]
You scared me a bit with the word "extreme" 😅 I thought that meant logs were constantly spewing at a high rate. I also thought that yarn workspaces were causing a problem in the app until I read the description.

Ah yes, I tested removing `resolutions` but forgot to commit it. Removed in https://github.com/sourcegraph/sourcegraph/commit/f3202423519ee86cb64575fca5cacaa5ee0e3027

I verified that the `api/console` page still works, so this probably didn't regress any functionality.

Is the solution to the "has unmet peer dependency" warning to add the dependency to package.json?
