### ISSUE TITLE
Searcher: cannot unmarshal number into Go value of type protocol.NotFoundPayload

### ISSUE THREAD

**Issue by aisbaa** [sourcegraph/sourcegraph#6911]
One of our clusters fails to with error for majority of search queries.:

<img width="1162" alt="Screenshot 2019-11-29 at 14 53 30" src="https://user-images.githubusercontent.com/82692/69870299-21e29000-12b8-11ea-9510-636f27ac17ce.png">

Not sure if this is related, but zoekt-indexserver contains a lot of ERR messages:
```
ERR: 2019/11/29 12:27:49 main.go:235: Get http://sourcegraph-frontend-internal/.internal/git/code.uber.internal/pro/tjpalanca/20161026-SENA-POOLDriverLifecycleAnalysis/tar/8a587e388e6bb23b9c38e174c87d62039590dfeb: 404 Not Found: 404 page not found

**Comment by dadlerj** [comment]
Thanks @aisbaa — just to check, is this occurring on all searches on this cluster, or just searches with `index:no`?

Which version of Sourcegraph is this cluster running?

And lastly, just to confirm, your other cluster is still running correctly, right?

**Comment by aisbaa** [comment]
Version we're on 3.8.1. This occurs on most searches (despite `index:no`). The other cluster is running correctly.

I'm available for debugging session for next 4 hours today, if needed.

**Comment by dadlerj** [comment]
Thanks. Did this issue just start happening? From looking at the trace you sent, this appears to coming from the symbols service (e.g., perhaps it's out of disk space?). Beyang will follow up from here.

**Comment by aisbaa** [comment]
DiskPresure is False on the node and there's still room on cache directory `17.6G  76% /mnt/cache`.  Though the cache is empty:

```
> kubectl exec -it searcher-xxxxxxxxx-yyyy -- find /mnt/cache
/mnt/cache
/mnt/cache/searcher-xxxxxxxxx-yyyy
/mnt/cache/searcher-xxxxxxxxx-yyyy/searcher-archives
```

**Comment by aisbaa** [comment]
I've noticed that after AWS VGW-DGW migration (network infra migration).

**Comment by uwedeportivo** [comment]
hm, the cache is empty which tells me that maybe symbols has trouble talking to gitserver. can you please take a look at the grafana dashboard "Cluster-Internal Network Activity, Client POV". don't remember if that's already available in 3.8.1 (come to think of it, probably not). 

alternatively can you please look at `src_gitserver_request_duration_seconds_count{code=~"5.."}` in prometheus.

**Comment by aisbaa** [comment]
There is some, but very little and it does not respond to querying:

<img width="1436" alt="Screenshot 2019-12-02 at 19 44 07" src="https://user-images.githubusercontent.com/82692/69982242-a3e2eb00-153c-11ea-826d-881a6e55e030.png">

**Comment by slimsag** [comment]
The error here:

> json: cannot unmarshal number into Go value of type protocol.NotFoundPayload

Appears to be a red herring / symptom of the underlying issue. The actual issue here is that `searcher` and other pods like `indexed-search` are for some reason unable to talk correctly with `sourcegraph-frontend-internal`. Unfortunately our tracing around this response is insufficient to debug this currently, so could you try the following?

1. Install Curl on a `searcher` pod: `kubectl exec -it $POD -- apk add --no-cache curl`
2. Download the response body and headers so we can inspect it from the pod's point of view:

```sh
kubectl exec -it $POD -- curl -i -L http://sourcegraph-frontend-internal/.internal/git/code.uber.internal/pro/tjpalanca/20161026-SENA-POOLDriverLifecycleAnalysis/tar/8a587e388e6bb23b9c38e174c87d62039590dfeb | less
```

If this shows a bunch of binary in your terminal, then the request succeeded and we'll have to try something else for debugging this. If it just shows text, then the request failed so copy the text here (with any secrets redacted).

**Comment by slimsag** [comment]
Can you also double-check that:

- Gitserver has disk space
- Gitserver logs don't show anything unordinary (i.e. it's not spamming errors)

**Comment by aisbaa** [comment]
> * Gitserver has disk space

22% used

> * Gitserver logs don't show anything unordinary (i.e. it's not spamming errors)

There are few errors stating that we hit gitolite limits (91 error logs over 24 hours), so this should not be an issue, since the subsequent request succeed.

curl returns 404 so network connectivity should not be an issue. Though this request does not seem to be logged on gitserver side.

```
# curl -i -L http://sourcegraph-frontend-internal/.internal/git/code.uber.internal/pro/tjpalanca/20161026-SENA-POOLDriverLifecycleAnalysis/tar/8a587e388e6bb23b9c38e174c87d62039590dfeb
HTTP/1.1 302 Found
Content-Type: application/json
Location: http://gitserver-0.gitserver:3178/archive?format=tar&repo=code.uber.internal%2Fpro%2Ftjpalanca%2F20161026-SENA-POOLDriverLifecycleAnalysis&treeish=8a587e388e6bb23b9c38e174c87d62039590dfeb
Vary: Accept-Encoding
Date: Tue, 03 Dec 2019 07:19:36 GMT
Content-Length: 0

HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Tue, 03 Dec 2019 07:19:36 GMT
Content-Length: 19

404 page not found
```

**Comment by aisbaa** [comment]
Repo and commit does exist on gitserver-0.

**Comment by beyang** [comment]
During a live debugging session, we determined the immediate issue was that the gitserver pods were running the gitserver container from 3.6 and the API changed from then to 3.8. This meant that requests from searcher and indexed-search to fetch git archives from gitserver failed. Updating the gitserver image to 3.8 resolved the issue.

It's unclear why gitserver pods were running 3.6, as the error first manifested when migrating an AWS networking configuration (which should not have touched the Sourcegraph k8s configuration).

**Comment by slimsag** [comment]
Good to know, this is one type of accidental misconfiguration I have been thinking we should surface. I'll file a tracking issue that includes this.

**Comment by aisbaa** [comment]
This is not the first time this happened to me 🤦‍♂. To surface such issue I did use this command:

```shell
> kubectl get pods -o 'jsonpath={range .items[*]}{range .spec.containers[*]}{.image}{"\n"}{end}{end}' | sort | uniq -c
```

Yet it is easy to miss a line with different version. Here's command to print only docker image versions:

```shell
> kubectl get pods -o 'jsonpath={range .items[*]}{range .spec.containers[*]}{.image}{"\n"}{end}{end}' | grep -Po '(?<=\:)(.*)(?=@sha256)' | sort | uniq -c
```

On mac os `ggrep` is require, because mac os grep does not support `-P` option.

Thank you again for help.
