### ISSUE TITLE
Private Repo not Showing for User Who's not Site Admin 

### ISSUE THREAD

**Issue by guanw** [sourcegraph/sourcegraph#6917]
#### Question description

It's possible people have asked this so sorry if it turned out to be. Trying to deploy sourcegraph on ec2 and found that regular users who use the builtin way to signup couldn't see private repos in our github org. e.g judepppp in below screenshot can only see public repo in typeahead results.
![image](https://user-images.githubusercontent.com/7311035/69881197-4465b080-129a-11ea-9592-ef7500e5f076.png)

for user judepppp the following shows: 
![image](https://user-images.githubusercontent.com/7311035/69881325-b0481900-129a-11ea-932f-96d98171c0d7.png)
Once I promote them to site admin all the private repos will show. I've tried:

1. changing bunch of params in the `external service` -> `setting` but no success so far.
2. updating the external resources token to include more permission and also no thing changes.

Curious if there's a easy way to grant access to private repos. Thanks for any help.

**Comment by unknwon** [comment]
Not sure if it's a product design or bug, assign to triage.

**Comment by dadlerj** [comment]
Hey @guanw thanks for the patience! Just to check, did you set up GitHub [repository permissions](https://docs.sourcegraph.com/admin/repo/permissions) (i.e., did you add the `authorization` field to the external service)? 

If not, can you share a redacted copy of your external service here so we can try to repro?

**Comment by guanw** [comment]
Hi @dadlerj I didn't set anything special in the external service config and I was using built-in auth to add team members.

The external service json file looks like this:
```
{
  "url": "https://github.com",
  "token": "xxxxxxxxxxxxxxxxxxxxx",
  
  "repositoryQuery": ["org:clicktherapeutics"],
  
  "authorization": {
  }
}
```
I just made sure the auth token has full control/access to the repo like the following on github token:
![image](https://user-images.githubusercontent.com/7311035/70381663-4bd12d80-191c-11ea-95ea-936d4b54399f.png) I didn't really `Create a GitHub OAuth application` as the [Prerequisite](https://docs.sourcegraph.com/admin/repo/permissions#github) mentioned. Could that be the reason why it's not working?

**Comment by dadlerj** [comment]
Hey @guanw — try deleting the lines that contain:

>  "authorization": {
>  }

from your configuration, and save it. 

Having that config option means that Sourcegraph will try to enforce GitHub's repository access authorization/permission. And since users are signing in via "builtin" auth, there's no way to link their user accounts to their GitHub accounts. As a result, they would only be able to see the public repos.

Let me know if that helps.

**Comment by guanw** [comment]
Ah. Gotcha. I just removed the authorization part and it seems working now. I think it would be helpful to mention this in your documentation.

BTW I don't think linking github accounts matters here since both admin and those users I added are members of same org so they should have the same access to both public and private repos.
