### ISSUE TITLE
Messy root dependencies

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#692]
There are a lot of dependencies in the root package.json:

```json
"@babel/plugin-syntax-dynamic-import": "^7.0.0",
    "@gql2ts/from-schema": "^1.10.1",
    "@gql2ts/language-typescript": "^1.9.0",
    "@sourcegraph/prettierrc": "^2.2.0",
    "@sourcegraph/stylelint-config": "^1.0.1",
    "@types/webpack": "4.4.17",
    "child_process": "^1.0.2",
    "fancy-log": "^1.3.2",
    "globby": "^8.0.1",
    "graphql": "^14.0.2",
    "graphql-schema-linter": "^0.1.6",
    "gulp": "^4.0.0",
    "json-schema-ref-parser": "^6.0.2",
    "json-schema-to-typescript": "^6.0.1",
    "koa-connect": "^2.0.1",
    "mkdirp-promise": "^5.0.1",
    "mz": "^2.7.0",
    "path": "^0.12.7",
    "plugin-error": "^1.0.1",
    "prettier": "1.13.7",
    "stylelint": "^9.7.1",
    "ts-unused-exports": "^2.0.11",
    "webpack": "^4.23.1",
    "webpack-dev-server": "^3.1.10"
```

A lot of these (if not all) seem to only be used for the webapp, so why are they not in `packages/webapp/package.json`?
Some I don't understand at all, like `child_process` and `path`, which are native Node modules.

**Comment by chrismwendt** [comment]
All but `@babel/plugin-syntax-dynamic-import` are used by `gulpfile.ts` or one of the scripts in the root package.json (prettier and stylelint).

`child_process` and `gulp` are imported by `gulpfile.ts` to build sourcegraph-extension-api and others.
