### ISSUE TITLE
Tooltip hovers over PR review box

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [sourcegraph/sourcegraph#694]
- **Sourcegraph version:** SourceGraph extension
- **Platform information:** https://github.com/palantir/tslint/pull/4249/files on Chrome on Windows 10

#### Steps to reproduce:

1. Go to the /files URL for a pull request
2. Hover over file content to get the SourceGraph extension tooltip
3. Quickly move your mouse to the PR review dropdown

#### Expected behavior:

Being able to see all of the text box & buttons for the PR review dropdown

#### Actual behavior:

If you're speedy enough & your internet is slow enough:

![image](https://user-images.githubusercontent.com/3335181/48020076-fd42d580-e102-11e8-90f1-a60a345113b0.png)

**Comment by sqs** [comment]
Have you/anyone seen this occur again? @ijsnow, has this been fixed?

Assigning to @ijsnow. (Sorry for missing this initially.)

**Comment by lguychard** [comment]
This still happens

![image](https://user-images.githubusercontent.com/1741180/54761183-e99b9580-4bf1-11e9-8dad-24d299c3e752.png)

@felixfbecker toying with z-index feels like the wrong fix here, but it looks like codeintellify only unpins on click events _in the code view_. Should we unpin the hover on click events _anywhere_, at least in the browser extension?

**Comment by felixfbecker** [comment]
It’s not intended for the hover to be unpinned when a UI element like a button is clicked outside the code view - z-index sounds like the right fix to me. Any reason you think it’s wrong?

**Comment by lguychard** [comment]
It would be the right fix if we controlled the entire UI - like on the webapp.

In the browser extension, relying on Z-index probably means this bug will re-surface in one way or another at some point.

**Comment by felixfbecker** [comment]
We could make it configurable

**Comment by felixfbecker** [comment]
This would be fixed by #8380
