### ISSUE TITLE
CODEOWNERS are wrong since monorepo switch over

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#695]
The file paths in `.github/CODEOWNERS` don't match anymore and I assume the CODEOWNERS files in the external repositories were not merged into it.

**Comment by chrismwendt** [comment]
Ah, I overlooked `.github/CODEOWNERS`. Fixed in https://github.com/sourcegraph/sourcegraph/commit/088db5d054b31d2b64de0f9c9ccae0a60ce38fa4
