### ISSUE TITLE
Cypress tests hang

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#697]
<img width="1039" alt="screen shot 2018-11-05 at 10 49 01 am" src="https://user-images.githubusercontent.com/754768/48023120-c1534480-e0f1-11e8-8fdc-f8fb69ac17cd.png">
<img width="1046" alt="screen shot 2018-11-05 at 10 48 55 am" src="https://user-images.githubusercontent.com/754768/48023125-c3b59e80-e0f1-11e8-80c8-7858bae51420.png">

https://buildkite.com/sourcegraph/sourcegraph/builds/22733#89b52b83-1834-4d35-8979-1d53f9f92c31

**Comment by chrismwendt** [comment]
I haven't found any useful info through Google about why this happens and how to prevent/recover from it, so I add a timeout and 1 retry for now: https://github.com/sourcegraph/sourcegraph/commit/0c70d954e5396899cb98aa9733e628c538858c08

**Comment by chrismwendt** [comment]
Hmm Cypress is not starting and `timeout` doesn't seem to actually kill Cypress after 3 minutes https://buildkite.com/sourcegraph/sourcegraph/builds/22748#695ac2e7-a130-480a-bb8c-be2bea91e2da I'll remove the line that runs e2e tests for now and investigate more later. It's currently blocking builds.

**Comment by chrismwendt** [comment]
This is puzzling. I even `kubectl exec`ed into the container and ran the e2e tests pass, and they passed. I was also able to kill them with a short `timeout`. Maybe the `for` syntax is not supported by buildkite?

**Comment by chrismwendt** [comment]
The test infra has changed a lot, reopen if this happens again.
