### ISSUE TITLE
./dev/ci/e2e.sh prints CI password into logs

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#6973]
As we file flaky CI builds, we often copy and paste CI logs into GitHub. It is very dangerous to have those logs print credentials like our DockerHub password, as it's easy to accidentally copy that into a GitHub issue comment.

https://github.com/sourcegraph/sourcegraph/blob/61f56996aee1c24c8a73f7dc153328074c2c2aad/dev/ci/e2e.sh#L30

The script is set to print all commands with variables evaluated, which prints the value of `DOCKER_PASSWORD`.

**Comment by chayim** [comment]
Resolving as stale. CI no longer behaves this way.
