### ISSUE TITLE
LSIF repo settings shows data, but files lack code intel

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#6977]
- I uploaded LSIF data for github.com/sqs/rego in https://github.com/sqs/rego/commit/e5f95739743cc596beb43efcae461bcf9c0425de/checks?check_suite_id=337129178 and confirmed it showed up at https://sourcegraph.com/github.com/sqs/rego/-/settings/code-intelligence?visible=1.
- I confirmed there is data in the upload:

```
Package: main
	File: /github/workspace/rego.go

1 package(s), 1 file(s), 83 def(s), 1539 element(s)
```

However, when I go to https://sourcegraph.com/github.com/sqs/rego/-/settings/code-intelligence?visible=1 and click the `/` link, then visit that commit's `rego.go` file, there is no code intelligence (no hovers). There are no errors printed in the console. I do have `codeIntel.lsif` set to true (in user settings, and of course it is true in Sourcegraph.com global settings).

**Comment by efritz** [comment]
I'm getting hovers from that file. Did you redo any of these steps?

**Comment by sqs** [comment]
I am still not. I will check my settings.

**Comment by chrismwendt** [comment]
I'm getting hovers, too. I'm viewing https://sourcegraph.com/github.com/sqs/rego@e5f95739743cc596beb43efcae461bcf9c0425de/-/blob/rego.go#L27:2

If you open the Network tab, do you see lsif requests?

![image](https://user-images.githubusercontent.com/1387653/69995496-63b84400-150d-11ea-978d-4277b9dafcc7.png)

**Comment by sqs** [comment]
My bad. I was using a temporary fork of the Go extension from a while back that I forgot to delete. After disabling that one and enabling the normal sourcegraph/go extension, it worked.
