### ISSUE TITLE
Added a repository from local clone, visiting 'tags' shows 'Strconv.ParseInt: parsing "": invalid syntax'

### ISSUE THREAD

**Issue by s1341** [sourcegraph/sourcegraph#6978]
- **Sourcegraph version:** 3.10.0

#### Steps to reproduce:

1. Add a locally cloned repository (for which the server is not accessible from the sourcegraph machine)
2. Try to view tags of the repo.

#### Expected behavior:
See the tags
#### Actual behavior:
Get an error:
Strconv.ParseInt: parsing "": invalid syntax

**Comment by unknwon** [comment]
Is this same as https://github.com/sourcegraph/sourcegraph/issues/5453? cc @christinaforney

**Comment by s1341** [comment]
Looks like the same issue. This is also a linux kernel repository...

**Comment by unknwon** [comment]
Thanks for confirming that! I'm closing this one in favor of #5453 unless there is something else different.
