### ISSUE TITLE
Search: "Searching literally" message when using patterntype:structural

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#6994]
- Visit https://sourcegraph.com/search?q=patterntype:structural+%22normalize%28:%5B1%5D%29%22&patternType=literal
- Notice:

![image](https://user-images.githubusercontent.com/1387653/69993319-ce1ab580-1508-11ea-8722-464a9e346408.png)

Should the URL param be `patternType=structural` instead so that https://github.com/sourcegraph/sourcegraph/pull/6090/files#diff-ce6a70b4e4b3bbf622ec3c8047e32c51R61 evaluates to false and doesn't show the warning?

**Comment by rvantonder** [comment]
Structural search is not a supported feature yet, and part of work in progress. Please post dogfood feedback and missed issues as a comment in the [issue tracker](https://github.com/sourcegraph/sourcegraph/issues/6679).
