### ISSUE TITLE
Should archives and forks be excluded by default?

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#7004]
A user suggested making archives and forks excluded from search results by default. I definitely agree with this, but I remember there was some conversation about a code host where this might be a bad idea. So my question is: Should archives and forks be excluded by default? why / why not?

cc product @christinaforney and @sourcegraph/core-services 

Code: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@9d2c526/-/blob/cmd/frontend/graphqlbackend/search.go#L353-356

**Comment by keegancsmith** [comment]
My suspicion is that for most orgs this is what you want. So I'm in favour of this if we come up with a clear UI which indicates this, and is easy to include all.

**Comment by unknwon** [comment]
I'm in favor of excluding forks and archives by default but nice to have a site config option to switch on/off.

**Comment by slimsag** [comment]
@christinaforney @keegancsmith Would there be any objections to the simple approach @unknwon mentioned above:

exclude archives/forks by default, site config option to change the default

(with no other UI actions/indicators for this.)

**Comment by christinaforney** [comment]
I've heard a lot of customers ask about this - but I'm pretty sure it's mostly in the "I want to exclude" context. I would be worried about adding this at such a top level config, since this is likely more of a user preference. Could we instead change the default of the filter to be archive:no and fork:no instead of the current both? This way users still have the option to include them, but by default the expected behavior makes more sense. This goes along nicely with the UI filters @attfarhan  is working on. 

I wish we could look at customer data on usage of these filters cc @sourcegraph/web on one case where [RFC 78](https://docs.google.com/document/d/1dvmLBis_uBzcnwNcfzDIwQ03JT6hViJwdg0DccQBa9E/edit) would help.

**Comment by slimsag** [comment]
I said site config above, but I actually meant global config. This would mean a site admin could configure it globally (e.g. if an organization does regularly want to search archived or forked repositories) and individual users could configure it in their user settings, since it would be a part of the regular global -> org -> user settings cascade

Thoughts on that @christinaforney ?

**Comment by unknwon** [comment]
To clarify, the "site config" I said just meant configurable 🤦‍♂

**Comment by christinaforney** [comment]
So what would the result be of your proposed change? Change the default behavior to exclude forks and archived (would this change the filter default?), users could change the default behavior in their own config. I'm not clear on how this impacts the archived and forks filters - how would those change in the usage?

**Comment by keegancsmith** [comment]
There is some good discussion going on in https://github.com/sourcegraph/sourcegraph/issues/7003 which would imply we change the default to exclude archive&forks and include some better designed syntax around including them. Personally my preference is to that solution than to introduce configuration.

Meta: We should try avoid adding specific config like this, and rather take a step back and see if there is a generic solution which is easier to understand and more flexible. For example in this case we could introduce config for a default search string prefix / sticky search string prefix?

**Comment by christinaforney** [comment]
+1 to @keegancsmith - I think a configuration change makes this much more complex than is desirable. I'm not sure what the implementation effort of this and #7003 are, but it seems that just the change in default behavior proposed here (without the config change) is a small undertaking, and the current proposed syntax change in #7003 is far more complex. I don't think we'll have an issue with customers wanting to revert back to this previous behavior as default. What this does impact is things like saved searches and bookmarks, though again my intuition is that users aren't wanting these results anyway and may not realize they are being included.

I think the desired outcome here would be to make the quick change here and schedule in the effort for changing the syntax as part of our roadmap.

**Comment by tsenart** [comment]
@sourcegraph/web, @lguychard: Is this something that you think we could do in 3.13 on the web team? Instead of what's being suggested in this thread, would it be possible for the web app to automatically include these filters in the query input by default? This would require no additional configuration, and users could still remove them. Filters have stickyness, right? So that's our configurability right there :)

**Comment by tsenart** [comment]
@lguychard: Ping. See above.

**Comment by lguychard** [comment]
> Instead of what's being suggested in this thread, would it be possible for the web app to automatically include these filters in the query input by default? This would require no additional configuration, and users could still remove them.

I'm not in favour of this -- split search modes and the new in-field toggles already added a lot around our search field, and we should be careful of making things even busier there. Filters only have "stickiness" (in the form of separate UI components) in interactive mode, and a pre-filled search input in plain text mode would be quite strange to me. I don't see this being the solution long-term, and I'd rather we don't build an intermediate fix here.

I'd also prefer a solution that changes the default to excluding archives and forks across all clients that make search requests (webapp, browser extension, API).

**Comment by tsenart** [comment]
@rvantonder and @christinaforney: Can you please sync and make a call here?

**Comment by rvantonder** [comment]
I'm going to put up a PR to exclude these and we can approve it if there's a consensus. At the very least, I personally agree that archived should be off by default. Forks, possibly.

**Comment by rvantonder** [comment]
Exclude archived: https://github.com/sourcegraph/sourcegraph/pull/8737
Exclude forked: https://github.com/sourcegraph/sourcegraph/pull/8739

**Comment by rvantonder** [comment]
Archives and forks are not excluded by default.

**Comment by lguychard** [comment]
> Archives and forks are not excluded by default.

Should this read "now"? 🙂

**Comment by rvantonder** [comment]
Oof, corrected. Thanks.
