### ISSUE TITLE
Hovering over package declaration in Go file breaks code intelligence

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#701]
- **Code host:** GitHub
- **Platform information:** macOS Majove, Chrome 69.0.3497.100
- Extension version: 1.18.0
- **Client settings:** empty

#### Steps to reproduce:

![sourcegraph](https://user-images.githubusercontent.com/133014/47651433-5da0a880-db40-11e8-91a7-c2318f4f5317.gif)

**Comment by chrismwendt** [comment]
Fixed in https://github.com/sourcegraph/sourcegraph-langserver-http/pull/9
