### ISSUE TITLE
Clicking "Show more" at end of a result set does not jump you back to the top of the page

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#7024]
A user at https://app.hubspot.com/contacts/2762526/company/407948923 reported this, and I agree the current behavior is surprising.

When you click "Show more" it doesn't jump you back to the top of the page, and instead lets you "continue" by leaving you at the bottom of the page.

Given that we do not have stable result ordering (outside of the experimental paginated search API), it is surprising that we do this because really we don't know which results the user has seen when the `count:` increases.

**Comment by tsenart** [comment]
@slimsag: Is there anything Core Services could do here or is this a purely a Web thing?

**Comment by Akarshit** [comment]
I tried to reproduce this one, but couldn't. [Here](https://sourcegraph.com/search?q=jacobian&patternType=literal) is the query I tried. Clicking on "Show More" does a "refresh" on the search results and takes me to the top.
Did I miss anything?

**Comment by slimsag** [comment]
@sourcegraph/web Is there an e2e test which guarantees this behavior? I am worried there may be a bug in some edge case here or that we may have regressed and then fixed this without knowing.

**Comment by felixfbecker** [comment]
I don't know, all e2e tests are in this file: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/web/src/e2e/e2e.test.ts

**Comment by slimsag** [comment]
See also https://github.com/sourcegraph/sourcegraph/issues/5120

Can someone on @sourcegraph/web own defining this behavior and adding an e2e test?

**Comment by lguychard** [comment]
> we do not have stable result ordering

Given this, the behaviour should be to scroll back to the top.

Looking at [relevant code](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@541ef3c940d1796c3faf56ed16e92013a3050651/-/blob/web/src/search/results/SearchResults.tsx#L314-327), I don't see anything that would leave you at the bottom of the page (eg. adding a hash fragment with the position, as mentioned in #5120).

I can own adding an e2e test for this.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.14 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by slimsag** [comment]
This has been fixed.
