### ISSUE TITLE
Extension request: "File issue assigned to code owners" button on directory page

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#705]
NOTE: The APIs required to build this do not yet exist.

#### Describe the feature request.

An extension for GitHub/Sourcegraph that adds a "File issue" button to directory pages, with a prepopulated set of assignees based on the recursive code owners for the directory.

#### Is your feature request related to a problem? Please describe.

> I wish GitHub’s CODEOWNER system could also work for issues somehow. I.e. make it possible to file issues on a subdirectory in a monorepo, and automatically assign all issues in a repo or folder to certain people

-- @felixfbecker 

#### Additional context

Seems like a good candidate for a CXP extension that jams a button into github dir pages with a prepopulated https://github.com/my/repo/issues/new?assignee=... link.

**Comment by keegancsmith** [comment]
If someone wants to work on this, I have some pre-existing work on CODEOWNERS so likely can advise on it.
