### ISSUE TITLE
File paths show up twice on diff search results on sourcegraph.com

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#7061]
- **Sourcegraph version:** Sourcegraph.com

#### Steps to reproduce:

1. Run any diff search on sourcegraph.com, such as https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24%4046575db+useEventObservable++type:diff&patternType=literal
2. See filenames show up twice at the top of every result:

![image](https://user-images.githubusercontent.com/5589410/70256473-65684e80-173d-11ea-9a89-f32f9574b9c4.png)

**Comment by camdencheek** [comment]
I don't believe this is a bug since this is just how git formats its diff output. The first file path is the name of the file before the commit, the second is the name of the file after the commit. In commits where there is a file rename, these two paths will be different

**Comment by lguychard** [comment]
@camdencheek is correct, this is by design.
