### ISSUE TITLE
a8n: credentials campaign fails on sd9

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#7064]
#### Steps to reproduce:

1. Create a new credentials campaign with
	```json
	{"matchers":[{"type": "npm"}], "scopeQuery": "repo:github.com/sd9"}
	```
2. Click "Create preview"

#### Expected behavior:
It's created successfully

#### Actual behavior:
Getting an error
> Mkdir /var/folders/kw/46c61lnd2jsd85rr9dm7lqb40000gn/T/tmpfriend-95404-085201419/diffing-multi/.npmrc453163637

Also, it is reported as completed, not errored
(errors.length > 0, status = ‘COMPLETED’)

**Comment by mrnugget** [comment]
> Also, it is reported as completed, not errored
> (errors.length > 0, status = ‘COMPLETED’)

`errors.length > 0` _is_ errored. 'COMPLETED' only means that it has completed execution. It doesn't say anything about the success status.

Or am I misunderstanding what you meant?

**Comment by mrnugget** [comment]
Note that the fix in https://github.com/sourcegraph/sourcegraph/pull/7259/files only fixes the underlying campaign. If the UI doesn't handle `errors.length > 0 && state == 'COMPLETED'` correctly, we should fix that separately.

**Comment by eseliger** [comment]
what does `state = 'ERRORED'` stand for then? 🤔 maybe I misunderstood the states 🤔

**Comment by mrnugget** [comment]
Ahh! You're right. My bad. Here is the code to "compute" the state:

https://github.com/sourcegraph/sourcegraph/blob/9725de6113d9be7a2276ae3f8d8cd4d87ded3138/enterprise/internal/a8n/store.go#L1434-L1445

**Comment by eseliger** [comment]
Hmm I can’t see how this produced COMPLETE with an error 🤔 (which happened in this issue) maybe no case matched and since the default is completed? 🤯

**Comment by mrnugget** [comment]
I think it has something to do with more jobs being launched than jobs finding a `.npmrc`. I'm digging into it and could reproduce it.

```sql
SELECT
  (SELECT canceled_at IS NOT NULL FROM campaign_plans WHERE id = 39) AS canceled,
  COUNT(*) AS total,
  COUNT(*) FILTER (WHERE finished_at IS NULL) AS pending,
  COUNT(*) FILTER (WHERE finished_at IS NOT NULL AND (diff != '' OR error != '')) AS completed,
  array_agg(error) FILTER (WHERE error != '') AS errors
FROM campaign_jobs
WHERE campaign_plan_id = 39
LIMIT 1;
```
```
-[ RECORD 1 ]--------------------------------------------------------------------------------------------------------------------------------------------
canceled  | f
total     | 174
pending   | 0
completed | 2
errors    | {"mkdir /var/folders/86/23tk7bxn04vgj7slgj_qdj6m0000gn/T/tmpfriend-64032-105461583/diffing-multi/.npmrc488259044: no such file or directory"}
```

**Comment by eseliger** [comment]
Maybe 
if processing: PROCESSING
If errors > 0: ERRORED
Else COMPLETED

Or sth works?

**Comment by mrnugget** [comment]
The problem is that we count jobs only as completed if they have either produced a diff or errored with this line:

```sql
  COUNT(*) FILTER (WHERE finished_at IS NOT NULL AND (diff != '' OR error != '')) AS completed,
```

I introduced that in https://github.com/sourcegraph/sourcegraph/commit/d270de30a173c47ecb3b9bcea3caa16ba3dfb8e1 and with the fix in that commit I made it work for cases where every repo yields a search result but not for the case here where we enqueue jobs for 180 repos and then only do actual work in 2 of them.

**Comment by mrnugget** [comment]
@eseliger I think it's a client question. Are you okay with (what I deemed a "bad thing" in d270de3) this being the case:

```
campaignPlan.changesets.totalCount != campaignPlan.status.completedCount
```

Note: it's "count of changesets" vs. "count of completed attempts to create changesets"

**Comment by eseliger** [comment]
Hmm we can justify that as being the amount of repos processed vs the amount of changesets to create and that seems alright to me 🤔 in the future, I see a more visualized UI for the status, especially if we run customer code which probably should have logs or sth attached. So I don’t see a problem separating those two now as we would at some point anyways (a guess)

**Comment by mrnugget** [comment]
> Hmm we can justify that as being the amount of repos processed vs the amount of changesets to create and that seems alright to me

I agree. And it would also fix the progress bar, because `status.completedCount` will grow from `0` to `status.totalCount`.

So you're fine with me reverting the change in d270de3?

**Comment by eseliger** [comment]
yes 👍

**Comment by mrnugget** [comment]
I also just realized that we don't expose the `status.totalCount` in the GraphQL API. Do you want me to @eseliger, would that help?

**Comment by eseliger** [comment]
the right hand side of the `12 / 170` was calculated by `{status.pendingCount + status.completedCount}`. We could switch to using `totalCount` there to prevent the current "counting down" behavior, but the status logic above would still be wrong, right?

**Comment by mrnugget** [comment]
Oh yeah, I just meant that _in addition_ to reverting d270de3 and fixing the `state`, I can also expose `Total` — while I have the files open, so to say ;)

**Comment by eseliger** [comment]
It's probably a bit more "fail safe" - why not(?) 
ping me if you don't like to change `web/src/enterprise/campaigns/detail/CampaignDetails.tsx:563` yourself 😬
