### ISSUE TITLE
New extension:  Linter support starting with ESLint (proposal)

### ISSUE THREAD

**Issue by jlangston** [sourcegraph/sourcegraph#708]
**sourcegraph-tslint:** 
A SourceGraph extension to show linter feedback in files (proposal). The goal of this extension would be to add further context while browsing or reviewing code both on supported code hosts or within Sourcegraph itself. Ideally, I see this providing the overall indicator with the number of warnings or errors in the file as well as per line indicators with either line highlighting or gutter icons. Tooltips could provide additional insight into a particular error or warning by showing the feedback for the given symbol or line. 

**Implementation:**
It would be hugely beneficial to look at this with the lens of how it might be possible to support multiple languages. For many languages and their different linter's, this would require running the analysis outside of the extension and reporting results back via a web service. One avenue I was interested in possibly pursuing with this was to approach it as being driven by diagnostics from the language server. As an initial intro into building Sourcegraph extensions and possibly being able to do all of the analysis within the web worker itself via something similar to how the [TSLint playground](https://palantir.github.io/tslint-playground/) is doing analysis in the browser, I thought TSLint would be a good place to start. 

This [Codecov extension ](https://github.com/sourcegraph/sourcegraph-graphql) is a good starting point for how some of the UX might work within this extension itself and reporting feedback to the user about the linter's results.

**Comment by jlangston** [comment]
Being able to add squiggles with the extension API would be great. I've got an initial take of a TSLint Sourcegraph extension that us using the line/range background color and tooltip decorations.  https://github.com/jlangston/sourcegraph-tslint-ext

**Comment by lguychard** [comment]
Prerequisite: https://github.com/sourcegraph/sourcegraph/issues/4102

**Comment by ryankscott** [comment]
Closing due to eventual [sunset](https://docs.sourcegraph.com/extensions/deprecation) of Sourcegraph extensions.
