### ISSUE TITLE
a8n: Allow closing and deleting of Campaigns

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#7082]
This is a follow-up to https://github.com/sourcegraph/sourcegraph/issues/6727 and the first PR that fixes it https://github.com/sourcegraph/sourcegraph/pull/7015.

[In this comment (and the following)](https://github.com/sourcegraph/sourcegraph/pull/7015#issuecomment-561829014) we noticed that in order to meet base level expectations of customers, we need to implement the proper closing and deleting of Campaigns.

@christinaforney proposed the following:

-  Add the ability to comment on a changeset in a code host
-  When closing a campaign, comment on the changeset to indicate that the campaign that created it has been closed.
-  Close the changeset on the code host when a campaign is deleted.

But the ["Campaigns can be closed" section in RFC 36](https://docs.google.com/document/d/1DKWy2zC6_rDZzoPS7ASUpvnVDK3Zj6cf_I9Riq9KNu0/edit#bookmark=id.uw8h18u0qxcu) describes the behavior as follows:

> Campaigns can be closed. After a campaign is closed, any user visiting the campaign will be prompted to close all changesets in the campaign if any are open. Upon clicking this button, all of those changesets will be closed on the code host.
> * A closed campaign has the same UI styling as a closed PR on GitHub (e.g., red).
> * Site admins can delete a campaign, which completely removes it (but does not affect the underlying changesets or branches on the code host).

What @christinaforney and I agreed on in a meeting yesterday was that the minimal thing we need to implement:

- [ ] When a `Campaign` is *closed* its `Changesets` will be closed on the codehost

That we're sure of. What we still need to answer:

- [ ] What happens to Changesets on the codehost when a campaign is *deleted*?
- [ ] Should we comment on Changesets when closing a Campaign?
- [ ] Should we comment on Changesets when deleting a Campaign?
- [ ] Is there a difference in behavior when closing/deleting a campaign if the Campaign is a "manual" campaign and the changesets have not been created by Sourcegraph?

(I personally think we should go with the proposal from RFC 36 since that is the least invasive and from a users perspective the most expected behavior. I don't think we need to post comments, since the timeline on the codehost will show "$user-associated-with-token closed PR" anyway.)

**Comment by christinaforney** [comment]
If we think about the user flow I think it answers the above questions. The user should be given the option to choose what happens to the changesets on the code host in each case. For both deletions and closing the options include:
1. Close changesets
1. Do not close changesets
Ability to add an optional custom comment to all changesets. (We can add the commenting piece later at a later date.)

**Comment by mrnugget** [comment]
Sounds good to me.

Regarding implementing the deletion: I think what we need to do is
1. Load Campaign and its Changesets
2. Detach the Changesets from the Campaign (i.e. remove its ID from `changesets.campaign_ids`)
3. Delete the Campaign
4. Enqueue a goroutine that closes the changesets.

That is straightforward but there is something to think about here: changesets can exist without being attached to a campaign. And they can also be attached to multiple campaigns. That means if a changeset is attached to 5 campaigns and one is closed and the user chooses "close changesets" then that changeset will be closed but still be in these campaigns.

I personally think that's totally fine, since it's an explicit user action and actually what I would expect. But I wanted to raise the issue.

**Comment by christinaforney** [comment]
>That is straightforward but there is something to think about here: changesets can exist without being attached to a campaign. And they can also be attached to multiple campaigns. That means if a changeset is attached to 5 campaigns and one is closed and the user chooses "close changesets" then that changeset will be closed but still be in these campaigns.
> 
> I personally think that's totally fine, since it's an explicit user action and actually what I would expect. But I wanted to raise the issue.

Agreed this would be expected and is a fine user flow.

**Comment by mrnugget** [comment]
Closing this after merging #7127 and #7163. The UI work has been added to the tracking issue https://github.com/sourcegraph/sourcegraph/issues/6663 And, as suggested, we can address commenting later.
