### ISSUE TITLE
a8n: External branch names should be more unique

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#7088]
Remote branch names are currently named `campaign-id` where id is and integer. There is a high chance of a conflict whenever we have a fresh db.

I propose we generate a unique id with each campaign that we'll use as part of external branch names. 

A random sequence of 3 hex digits should be enough and won't make the branch name too noisy. We should also include a link in the PR back to the campaign in the sourcegraph instance that created it.

**Comment by tsenart** [comment]
Trying to get this done in 1h @mrnugget
