### ISSUE TITLE
Ability to determine if running on a private instance

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#709]
Reported in: https://github.com/sourcegraph/sourcegraph-extension-api/issues/85#issuecomment-432838915

It would be nice for extensions to know if running on a private instance or on an instance like e.g. sourcegraph.com where global search is not possible.

For now, it is possible to derive this information using a hacky GraphQL query:

https://sourcegraph.com/api/console#%7B%22query%22%3A%22%7B%5Cn%20%20extensionRegistry%20%7B%5Cn%20%20%20%20localExtensionIDPrefix%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22variables%22%3A%22%22%7D

On sourcegraph.com this will return:

```json
{
  "data": {
    "extensionRegistry": {
      "localExtensionIDPrefix": null
    }
  }
}
```

On a private instance this will return e.g.:

```json
{
  "data": {
    "extensionRegistry": {
      "localExtensionIDPrefix": "sourcegraph.sgdev.org"
    }
  }
}
```

**Comment by sqs** [comment]
You can use `sourcegraph.internal.sourcegraphURL === 'https://sourcegraph.com'`
