### ISSUE TITLE
Diff and commit search completely broken in 3.10.2, 3.10.3

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#7090]
- **Sourcegraph version:**  "Sourcegraph.com" and sgdev

#### Steps to reproduce:

1. Run any diff or commit search on any repo on sourcegraph.com or sourcegraph.sgdev.org, e.g. https://sourcegraph.sgdev.org/search?q=test+repo:%5Esourcegraph/test%24++type:diff&patternType=literal or https://sourcegraph.sgdev.org/search?q=type:diff+repo:%5Esourcegraph/sourcegraph%24++test&patternType=literal
(with any timeout... It doesn't get fixed if you go higher)

2. See the new timeout warning
![image](https://user-images.githubusercontent.com/5589410/70343083-3c15f400-180b-11ea-87cc-92f9286dd83c.png)

Assigned to @sourcegraph/core-services (and @slimsag as I assume this is related to https://github.com/sourcegraph/sourcegraph/pull/7020)

**Comment by slimsag** [comment]
Fixed by #7103 and will go out in a 3.10.3 patch release soon (only 3.10.2 is affected).

**Comment by slimsag** [comment]
I don't know why, but my patch fixed the issue for Sourcegraph.com and small instances but not k8s.sgdev.org and a customer replica instance. Example: https://k8s.sgdev.org/search?q=timeout:2s+type:diff+%22err%22+&patternType=regexp

I am investigating.
