### ISSUE TITLE
LSIF plaintext hover support

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#7099]
We currently assume everything is formatted as markdown. See https://github.com/sourcegraph/sourcegraph/blob/5e425cfec07790e8f4836738629c5ec2b0dd2e6a/lsif/src/worker/importer/correlator.ts#L452

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by efritz** [comment]
Closing due to low priority. This requires larger changes to the GraphQL API and the code intel extensions which doesn't seem worth it unless there is a legitimate issue treating text as markdown (which I've never heard).
