### ISSUE TITLE
Support internal CA or self-signed TLS certificates for all external communication

### ISSUE THREAD

**Issue by sfllaw** [sourcegraph/sourcegraph#71]
- Issue type: Feature Request
- Sourcegraph version: 2.7.6
- OS Version: N/A
- Docker version: N/A

We have a private GitHub Enterprise instance running under a self-signed private Certificate Authority. Because of this, we need to tell the Sourcegraph image about this CA, or Git will complain:

```
fatal: unable to access 'https://github.example.com/user/repo.git': server certificate verification failed. 
```

The configuration option in [`github.certificate`](https://about.sourcegraph.com/docs/config/settings/#certificate-string) is available, but it only applies to Sourcegraph, not to processes that `gitserver` controls. As well, since it only seems to handle server certificates and not CAs, it will have to be updated every time the GitHub Enterprise server rotates its certs.

Our workaround, which you are welcome to document, is to install the certificate in the Docker image, so the OS handles it. In a `Dockerfile`:

```Dockerfile
FROM sourcegraph/server:2.7.6
COPY ssl/certificate-authority.crt /usr/local/share/ca-certificates
RUN /usr/sbin/update-ca-certificates
```

Running this derived image makes everything work magically, because Sourcegraph also trusts the CAs provided by the OS.

**Comment by sqs** [comment]
Tentatively scheduling for November 2018 as part of the [More robust code host repository syncing](https://docs.sourcegraph.com/dev/roadmap#november-2018) feature on the roadmap.

**Comment by sqs** [comment]
The "More robust code host repository syncing" project was narrowed to be [Handling renames and deletions of mirrored repositories](Handle renames and deletions of mirrored repositories). I am pushing back this issue as a result.

**Comment by sqs** [comment]
This issue is not yet prioritized, and it will take a lot more research/planning (which is not necessary right now). However, I updated the title in the meantime to reflect that the fix should be holistic (you should be able to specify a cert for Sourcegraph to trust in all of its HTTP calls, or at least that process should be documented), not just for GitHub or for one additional place where we make external HTTP calls.

**Comment by keegancsmith** [comment]
The solution for this would likely also be a solution for specifying an HTTP_PROXY https://github.com/sourcegraph/sourcegraph/issues/250

**Comment by MMulero** [comment]
> * Issue type: Feature Request
> * Sourcegraph version: 2.7.6
> * OS Version: N/A
> * Docker version: N/A
> 
> We have a private GitHub Enterprise instance running under a self-signed private Certificate Authority. Because of this, we need to tell the Sourcegraph image about this CA, or Git will complain:
> 
> ```
> fatal: unable to access 'https://github.example.com/user/repo.git': server certificate verification failed. 
> ```
> The configuration option in [`github.certificate`](https://about.sourcegraph.com/docs/config/settings/#certificate-string) is available, but it only applies to Sourcegraph, not to processes that `gitserver` controls. As well, since it only seems to handle server certificates and not CAs, it will have to be updated every time the GitHub Enterprise server rotates its certs.
> 
> Our workaround, which you are welcome to document, is to install the certificate in the Docker image, so the OS handles it. In a `Dockerfile`:
> 
> ```dockerfile
> FROM sourcegraph/server:2.7.6
> COPY ssl/certificate-authority.crt /usr/local/share/ca-certificates
> RUN /usr/sbin/update-ca-certificates
> ```
> 
> Running this derived image makes everything work magically, because Sourcegraph also trusts the CAs provided by the OS.

I tried this solution but still I have the same issue:
sourcegraph    | 12:46:24       repo-updater | t=2019-04-12T12:46:24+0000 lvl=eror msg="Error listing GitLab projects" url="projects?groups%2Fidedio%2Fprojects=&order_by=last_activity_at&per_page=100" error="Get https://git.svb.lacaixa.es/api/v4/projects?groups%2Fidedio%2Fprojects=&order_by=last_activity_at&per_page=100: dial tcp 10.144.11.112:443: connect: connection timed out"

using Curl or git from docker I am able to connect to the server. Could you provide more information about how do you configure it in sourcegraph?

**Comment by tsenart** [comment]
@MMulero: If you try to reach that endpoint from within the sourcegraph container, does it work?

You can exec into the container to try this out.

```
docker exec -it $SOURCEGRAPH_CONTAINER_NAME /bin/bash
```

**Comment by MMulero** [comment]
Yes, from docker using curl I reach the endpoint. And also I am able to download repos with git.

**Comment by tsenart** [comment]
> Yes, from docker using curl I reach the endpoint.

But is it from within the Sourcegraph container?

**Comment by MMulero** [comment]
Yes, I've installed Curl using a Dockerfile and I've checked that I've connectivity to the gitlab repository.
Additionally, I've checked the connectivity dowloading repos using git inside sourcegraph docker.

**Comment by MMulero** [comment]
Yes, I've installed Curl using a Dockerfile and I've checked that I've connectivity to the gitlab repository.
Additionally, I've checked the connectivity dowloading repos using git inside sourcegraph docker.

**Comment by slimsag** [comment]
This appears to be heavily related to (but not exactly 100% the same as) https://github.com/sourcegraph/sourcegraph/issues/2990

**Comment by slimsag** [comment]
See also some workarounds I posted in that thread: https://github.com/sourcegraph/sourcegraph/issues/2990#issuecomment-557704995

**Comment by keegancsmith** [comment]
3.12 will contain an experimental setting `experimentalFeatures/tls.external` which will allow turning off SSL/TLS verification. We will continue to work on this in 3.13 and plan to ship a non-experimental setting which allows setting an internal CA that git will respect.

**Comment by keegancsmith** [comment]
https://github.com/sourcegraph/sourcegraph/pull/8092 contains a new field under the experimental setting "tls.external" for "certificates". This will allow you to add self-signed certificates / any certificate to the CA chain used by Sourcegraph to communicate with code host APIs / git.

This will go out in our next release 3.13. It may be promoted to not being an experimental feature by then. Either way read the changelog for our next release to find out more :)

**Comment by sfllaw** [comment]
@keegancsmith It looks like `tls.external.certificates` clobbers system certificates if you define it. That means that we cannot use _both_ GitHub.com and our own GitHub Enterprise code hosts simultaneously.

**Comment by tsenart** [comment]
@ryphil: Seems like a bug for @sourcegraph/core-application

**Comment by keegancsmith** [comment]
@sfllaw thanks for the report. This is a bit surprising since we explicitly handle loading in root certificates and I (somewhat) remember testing it :) https://github.com/sourcegraph/sourcegraph/blob/4b71a44790e1a82cc570b64084a63b4e67b0cdac/internal/httpcli/external.go#L54-L60

You don't set any variables like `SSL_CERT_FILE` or `SSL_CERT_DIR`? I see that might clobber loading the root certs based on the doc string for `SystemCertPool`:

> // On Unix systems other than macOS the environment variables SSL_CERT_FILE and
// SSL_CERT_DIR can be used to override the system default locations for the SSL
// certificate file and SSL certificate files directory, respectively. The
// latter can be a colon-separated list.


I am guessing there is a regression here somehow. I'll leave it to core-app to triage fix, should hopefully be easy to reproduce.

**Comment by sfllaw** [comment]
I haven't set any environment variables at all.

**Comment by sfllaw** [comment]
I wonder if getting the system very pool is failing for some crazy reason?

**Comment by keegancsmith** [comment]
@sfllaw I've added some extra logging to help here https://github.com/sourcegraph/sourcegraph/pull/22285. In the meantime, how feasible is it for you to install the certificates you want to trust into the sourcegraph container(s) as a workaround?

**Comment by sfllaw** [comment]
I worked around it, as I mentioned above, by manually enumerating GitHub.com's certificate authority.

The reason I followed up was to help someone who was trying to get this experimental feature working.

Let me know if how I can dump the debugging info.
