### ISSUE TITLE
Add campaign form UI instead of Monaco editor

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#7112]
Having to double-escape regexps in the JSON is a big UX problem.
In addition, providing real inputs opens the door for reusing our search autocompletion.

Investigate generating the form from JSON schema.

- [ ] Update docs (https://docs.sourcegraph.com/user/automation) to mention the new UI instead of the JSON schema for campaign types

**Comment by sqs** [comment]
For the simple campaign types we are implementing now, I think it would be easier to just have hardcoded forms that map to JSON instead of a generalized generate-form-from-JSON-Schema approach. cc @christinaforney

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.11 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by sqs** [comment]
Added to 3.13 milestone because this is mentioned in the 3.13 tracking issue. If I misunderstood, let me know.

**Comment by sqs** [comment]
Added a checklist to the issue description about updating docs to use the new campaign form UI as the primary thing users will use. To avoid confusion, I think the docs should only mention the JSON Schema in a separate section for people who are using the `src` CLI or our API to create campaigns (and not mention the equivalent JSON Schema for each campaign type in the campaign type's section).

**Comment by sqs** [comment]
See proposal to deprioritize this work at https://sourcegraph.slack.com/archives/CMMTWQQ49/p1579746146079200.

**Comment by sqs** [comment]
Based on the outcome of https://sourcegraph.slack.com/archives/CMMTWQQ49/p1579746146079200, we are deprioritizing this in favor of specifying campaign plans via the CLI (#7850 and related work).
