### ISSUE TITLE
After Campaign creation list of changesets is empty

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#7126]
When creating a new campaign with the "Changesets" tabs selected the list of changesets will stay empty, even after creation. You have to select "diff" and then "changesets" again for the changesets to actually show up.

See this GIF:

![changesets_not_shown](https://user-images.githubusercontent.com/1185253/70440347-4695ef00-1a92-11ea-8c67-ba5c5056bed0.gif)

Note that the count of changesets is correct right after creation, but the list is empty.

**Comment by eseliger** [comment]
This has been fixed as a side-effect of #7105
