### ISSUE TITLE
release process requires high context switching

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#7148]
Today, the patch release process is as follows:

1. **WAIT 20-24 minutes for CI** after `cd dev/release && yarn run release patch:issue 3.10.4` -> cherry pick commits onto `3.10` branch -> push `3.10` branch and `v3.10.4-rc.1` release candidate.
2. **WAIT 20-24 minutes for CI** after pushing `v3.10.4` tag
3. **WAIT ~20 minutes for Renovate to open PRs in deploy-sourcegraph**
4. **WAIT 13 minutes for CI** after merging and cherry picking -> push tags
4. **WAIT 20-24 minutes for CI** after `yarn run release release:publish 3.10.4`

All in all, the most painful part of this process is not that it is time consuming but that it requires constant interrupts and context switching. I cannot do anything meaningful in 20 minutes so I effectively must sit on my hands during this time.

My goal in opening this issue is to communicate that I think this is the most pressing issue with the release process today -- not the time it takes.

Fixing this will depend on https://github.com/sourcegraph/sourcegraph/issues/9252

**Comment by slimsag** [comment]
In 3.16 I will do https://github.com/sourcegraph/sourcegraph/issues/9252 which will lay the groundwork for fixing this issue, but will likely not fix it entirely. Given that, I am removing this from the milestone.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
