### ISSUE TITLE
Search syntax with AND and OR

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#7154]
A [customer](https://app.hubspot.com/contacts/2762526/company/464956351) requested the ability to use AND and OR in search queries to combine search criteria. I will ask them to comment on this issue with specific queries they'd like to be supported.

This is in a similar vein to the structured search feature we've explored in the past. (cc @keegancsmith)

**Comment by rvantonder** [comment]
> specific queries they'd like to be supported.

This would be useful, because `AND`/`OR` expressions don't necessarily apply to all of our keywords, and will give us an indication of what to prioritize.

**Comment by dadlerj** [comment]
Also requested by https://app.hubspot.com/contacts/2762526/company/419004361

I think this was filed at one point in the past, but not sure how to search for "AND" or "OR" in GitHub haha

**Comment by rvantonder** [comment]
With https://github.com/sourcegraph/sourcegraph/pull/16866 we'll be supporting and/or/not in a general way. From this point on we should create specific issues for queries/search behavior that users request that we discover are not supported by some combination of our current language features.
