### ISSUE TITLE
Extension request: Jump to definition and find references for HTTP routes

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#716]
Consider [this code](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/gitserver/server/server.go#L234:18):
```go
mux.HandleFunc("/create-commit-from-patch", s.handleCreateCommitFromPatch)
```

Find references when hovering over "/create-commit-from-patch" could return the locations from this search:
- https://sourcegraph.com/search?q=%5C%22%5C/%3Fcreate-commit-from-patch+r:sourcegraph/sourcegraph (Open source requires a repo filter)
- https://sourcegraph.example.com/search?q=%5C%22%5C/%3Fcreate-commit-from-patch (private Sourcegraph instance would not require a repo filter)

**Comment by lguychard** [comment]
Handled by https://github.com/lguychard/sourcegraph-configurable-references
