### ISSUE TITLE
Errors thrown in references can block other extension's references from showing

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#719]
Accidentally misbehaving extensions should not be able to ruin the UX of other extensions so easily.

I'm guessing the errors just need to be handled a bit more gracefully.

**Comment by lguychard** [comment]
This doesn't seem to happen anymore. Eg., running the following extension along with lang-typescript:

```

export function activate(ctx: sourcegraph.ExtensionContext): void {
   ctx.subscriptions.add(
    sourcegraph.languages.registerReferenceProvider(['*'], {
        provideReferences: () => {
            throw new Error('Error providing references')
        }
    })
   )
}
```

I can still see references from other extensions:

![image](https://user-images.githubusercontent.com/1741180/51199710-c99cdc80-18f7-11e9-8b31-28f2ff89c47e.png)
