### ISSUE TITLE
Saved searches should not be subject to 50 repositories limit

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#7215]
Today, saved searches are subject to a 50 repository limit in the same way that users are: https://github.com/sourcegraph/sourcegraph/issues/6826

Because saved searches aggressively scope queries to a smaller subset using `before:` and `after:` time scoping filters, they should not be subject to this limit as they were before.

Proposed (somewhat non-ideal) implementation: If `before:` or `after:` are in use, do not show the alert. When the alert is shown, advise scoping to fewer repositories OR using `before:` / `after:` (users must do this to create the saved search).

**Comment by keegancsmith** [comment]
Dear future traveller who clicked on the link in the changelog, see this PR which decided to add a 10k limit https://github.com/sourcegraph/sourcegraph/pull/13386
