### ISSUE TITLE
Authenticate via LDAP

### ISSUE THREAD

**Issue by Cyndi-1** [sourcegraph/sourcegraph#7218]
#### Question description

Can we login to sourcegraph via LDAP?

#### Is your question related to a problem? If so, please describe or link to another issue.

Login to Sourcegraph by authenticate to Active Directory server. 

#### Additional context

Reading about authentication method of Sourcegraph, its allow different method.  
Would like to know if Sourcegraph provide feature of authenticate and login with LDAP with not using GitHub or GitLab

**Comment by sqs** [comment]
Thank you for filing this. We are tracking this at #618. Could you please answer the questions at https://github.com/sourcegraph/sourcegraph/issues/618#issuecomment-438778854 and reply to that issue to help us understand your needs?
