### ISSUE TITLE
LanguageStatistics.totalBytes field is incorrect in SearchResultsStats

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#7220]
https://github.com/sourcegraph/sourcegraph/pull/5287 (https://github.com/sourcegraph/sourcegraph/pull/5287#discussion_r358157979) added search results stats about the languages in use. The `totalLines` fields are correct, but the `totalBytes` fields are incorrect. It needs to sum up *all* bytes in files that are matched entirely (ie by repo or filename matching) and only *matching* bytes in files with term matches (see https://docs.sourcegraph.com/user/search#statistics for how this works for line counting). I did not implement this in the original PR because totalBytes was a lot less useful in this case.

**Comment by stefanhengl** [comment]
@coury-clark I think you touched this code recently. Do you know if this is still relevant? Please close if not.
