### ISSUE TITLE
LSIF server does not run correctly in non-root mode

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#7231]
Reported by https://app.hubspot.com/contacts/2762526/company/578600789

Running on k8s, not sure about version

See discussion at https://sourcegraph.slack.com/archives/CHXHX7XAS/p1575304705085700 for more context (@efritz be warned the Slack thread will be deleted after 90 days, ~end of February)

**Comment by efritz** [comment]
Removed supervisor in https://github.com/sourcegraph/sourcegraph/pull/7233.

**Comment by efritz** [comment]
PR merged, this should work for this deployment context now.
