### ISSUE TITLE
line decoration text / links conflict with inline blame

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#727]
When a line decoration is provided by an extension, and the line itself is highlighted / selected on Sourcegraph, there is a conflict as both of them render, making them both illegible:

![image](https://user-images.githubusercontent.com/3173176/45585752-888bb180-b89e-11e8-928f-0bd63f8aa1aa.png)

**Comment by sqs** [comment]
This bug was caused by inline blame and extension decorations being added independently, without knowledge of each other. We made blame work via an extension (git-extras) so this specific thing is no longer an issue.
