### ISSUE TITLE
a8n: Backend stuck on npm campaign creation

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#7279]
- **Sourcegraph version:** 3.11, master
- **Platform information:** Local Enterprise Dev, macOS Catalina

#### Steps to reproduce:

1. Create a new campaign, input
	```json
	{
	    "scopeQuery": "repo:github.com/sourcegraph/automation-testing",
	    "matchers": [{ "type": "npm" }]
	}
	```
2. Create preview
3. Hit "Create"
4. Wait forever

#### Expected behavior:
It finishes at some point creating the PR on GH.com

#### Actual behavior:
It never finishes, and the backend seems to be busy, not creating any other previews and so forth either, this could only be solved by restarting the server

**Comment by mrnugget** [comment]
I cannot reproduce this with my tokens:

<img width="1211" alt="Screen Shot 2019-12-18 at 13 51 24" src="https://user-images.githubusercontent.com/1185253/71087889-826d3a80-219d-11ea-84da-09910e6fd0aa.png">

I'll try your tokens now.

**Comment by mrnugget** [comment]
With this setup in my `external-services-config.json`:

```json

  "GITHUB": [
    {
      "authorization": {},
      "url": "https://github.com",
      "token": "TOOOKEN", // sd9
      "repositoryQuery": ["affiliated"]
    },
    {
      "authorization": {},
      "url": "https://github.com",
      "token": "TOOOKEN", // my token
      "repositoryQuery": ["none"],
      "repos": ["sourcegraph/automation-testing"]
    },
    {
      "authorization": {},
      "url": "https://github.com",
      "token": "TOOOKEN", // unprivileged sqs-test user
      "repositoryQuery": ["affiliated"],
      "repos": ["sourcegraph/sourcegraph"]
    },
    {
      "url": "https://ghe.sgdev.org",
      "token": "TOOOKEN", // token from dev private
      "repositoryQuery": ["org:sourcegraph gorilla"]
    }
  ],
```

I still cannot reproduce it.
