### ISSUE TITLE
NPM campaign removes valid use-case

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#7280]
- **Sourcegraph version:** 3.11, master

#### Steps to reproduce:

1. Create a credentials campaign
2. Look at the result (sourcegraph/automation-testing has such a case for example)

#### Expected behavior:
The line with `${NPM_TOKEN}` is **not replaced**
As this is legitimate usage of the `.npmrc` file as per the [docs](https://docs.npmjs.com/files/npmrc#files)
> All npm config files are an ini-formatted list of key = value parameters. Environment variables can be replaced using ${VARIABLE_NAME}.

#### Actual behavior:
The line with `${NPM_TOKEN}` is **replaced**

A cherry-pick into 3.11 might be useful to make this campaign usable

**Comment by mrnugget** [comment]
Reopening because I couldn't see why it was closed. If you did have a fix, @ryanslade, feel free to close again and mention the issue/PR that fixes it.

**Comment by mrnugget** [comment]
Ah, I see. This was closed by https://github.com/sourcegraph/sourcegraph/issues/7280
