### ISSUE TITLE
Integrate Bitbucket Server Plugin's permissions endpoints

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#7282]
As part of RFC 45, our Bitbucket Server Plugin [was extended](https://github.com/sourcegraph/sourcegraph/issues/6091) to have API endpoints that serve permissions in an efficient way compatible with our Bitbucket Server authz provider.

This issue tracks the integration of those endpoints with the Bitbucket Server authz provider in Sourcegraph.

**Comment by tsenart** [comment]
@kzh: What are the next steps here?

**Comment by kzh** [comment]
It's complete. All that is left is validating on k8s.sgdev.org.

**Comment by tsenart** [comment]
@dadlerj, @slimsag: This means we'd be ready to ask a customer to try this out. @kzh: Do we have appropriate user documentation for rolling this out (i.e. caveats and all)?

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.12 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
