### ISSUE TITLE
Merge k8s docs into main docs site

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#7285]
Kubernetes Sourcegraph site admins have been confused when they go to look up how to do something (e.g., configuring external Redis and Postgres) and find the [main docs site page](https://docs.sourcegraph.com/admin/external_database#using-your-own-redis-server) rather than the [deploy-sourcegraph one](https://github.com/sourcegraph/deploy-sourcegraph/blob/master/docs/configure.md#configure-custom-redis).

A Google search for "sourcegraph external redis" yields the first page at the top and the second one 4th from the top.

We should have a single place for all core documentation.

**Comment by beyang** [comment]
Additional thing to be careful about: redirects from old docs.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
https://docs.sourcegraph.com/admin/install/kubernetes

https://docs.sourcegraph.com/admin/updates/kubernetes

**Comment by uwedeportivo** [comment]
https://github.com/sourcegraph/deploy-sourcegraph/pull/684
