### ISSUE TITLE
Enforce warnings for unsupported parameters and filters in structural search

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#7293]
The documentation covers that some of the [search parameters](https://docs.sourcegraph.com/user/search/queries) are unsupported. Specifically, things like `case` (structural search is always case sensitive) and `-lang` and multiple `lang` options just don't make sense contextually. 

The code currently just ignores these options, and as a quality measure I want to enforce and warn/alert on any such usages. Note that this is aligned with the higher level goals outlined in RFC 75, where we separate and explicitly define and enforce how Sourcegraph's parameters interact with various kinds of search.

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.12 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.13 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by rvantonder** [comment]
Closed by #8488
