### ISSUE TITLE
Promote comby warnings and suggestions to alerts

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#7294]
Running `comby` on the command line will surface alerts for certain weird patterns (like when your pattern starts with `:[x]`, which matches across newlines and thus matches a lot more things than intended. These warnings are currently suppressed.

I want to pass these warnings through to the web frontend, and some work is needed to filter certain warnings and nicely reformat others to be contextually useful.

Related: #9079 we should warn if a query is unbalanced.

**Comment by keegancsmith** [comment]
@rvantonder which milestone do you think this is? I am gonna assume backlog, but if you wanna tackle sooner please update :)

**Comment by tsenart** [comment]
@rvantonder: Recent PRs suggest that you're working on this area of the codebase. Wanna pull this in for 3.14?

**Comment by tsenart** [comment]
@rvantonder: Please triage.

**Comment by rvantonder** [comment]
This is done for the most part. Any remaining warnings/suggestions should go in the webapp parser.
