### ISSUE TITLE
RFC 40: GraphQL APIs

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#7298]
This issue tracks implementation of GraphQL APIs for [RFC 40: Explicit Repository Permissions Model](https://docs.google.com/document/d/167WV_rhBg3oj0yw9fHwUMlB-8BR3ktk2FSsKiUQo55Y/edit).

- [x] Update `schema.graphql`
- [x] `setRepositoryPermissionsForUsers` #7547
- [x] `authorizedUserRepositories` #7610
- [x] `usersWithPendingPermissions` #7678
- [x] `Repository.authorizedUsers`
- [ ] Tests https://github.com/sourcegraph/sourcegraph/pull/6427#issuecomment-557392099

**Comment by tsenart** [comment]
@unknwon: Please triage. What's going to make it in 3.12 and what is going to be left to 3.13?

**Comment by unknwon** [comment]
The unit and regression test will be tracked independently in #7747 and #7748, and closing this one. Doing this way because they're eating more time and I want to prioritize other items and come back to them later.
