### ISSUE TITLE
Very hard to find console.log lines in e.g. Chrome dev tools

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#730]
When developing the first thing I tried to do was get some `console.log` output, but with all the other extensions going on it is very hard to find:

![image](https://user-images.githubusercontent.com/3173176/45584065-1ad18c80-b882-11e8-912a-4963082224f4.png)

I tried filtering by just my extension name:

![image](https://user-images.githubusercontent.com/3173176/45584070-2ae96c00-b882-11e8-9210-39a582ab42d4.png)

But ironically that filters out my debug log line!!

If you could make `console.log` lines have a consistent prefix, e.g. `slimsag/code-discussions console.log` that would be perfect

**Comment by felixfbecker** [comment]
Are you aware you can disable the communication logs (they are going away with comlink anyway)?

> Additionally, it seems that `console.log` and `console.debug` lines do not show up in the chrome console output on GitHub.com **ever**, which makes extensions impossible to debug there.

They do, but in the background page, not in the content page.

**Comment by felixfbecker** [comment]
I'm closing this because those logs have gone away with comlink a long time ago. I openend #9694 for the other issue you mentioned.
