### ISSUE TITLE
RFC 40: Integrate explicit permissions model into authz workflow

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#7300]
This issue tracks integration of explicit permissions model into existing authorization workflow for [RFC 40: Explicit Repository Permissions Model](https://docs.google.com/document/d/167WV_rhBg3oj0yw9fHwUMlB-8BR3ktk2FSsKiUQo55Y/edit).

- [x] Inject into [`authzFilter`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@88392bca41bedd7eb90f3a714b2ea020f6a492fd/-/blob/cmd/frontend/db/repos_perm.go#L42:6) https://github.com/sourcegraph/sourcegraph/pull/6427#discussion_r349900524
- [x] Block all access when both permission models are configured

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.12 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
