### ISSUE TITLE
RFC 40: Handle change of `bind_id` in site config

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#7301]
This issue tracks implementation of `bind_id` change event handle logic for [RFC 40: Explicit Repository Permissions Model](https://docs.google.com/document/d/167WV_rhBg3oj0yw9fHwUMlB-8BR3ktk2FSsKiUQo55Y/edit).

Wipe out everything in `user_pending_permissions` and `repo_pending_permissions` tables.

**Comment by unknwon** [comment]
In a second thought, I think it might not worth doing it automatically, it might just be much easier and intuitive to admins if there is a button says "clear all pending permissions". Besides, username and email aren't interchangeable in the way that email always contains `@` symbol and username doesn't.

**Comment by tsenart** [comment]
So, can this be closed if you think it's not worth doing? @unknwon
