### ISSUE TITLE
RFC 40: Handle user deletion

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#7302]
This issue tracks implementation of user deletion event handle logic for [RFC 40: Explicit Repository Permissions Model](https://docs.google.com/document/d/167WV_rhBg3oj0yw9fHwUMlB-8BR3ktk2FSsKiUQo55Y/edit).

- [x] Remove all user permissions
- [x] Also clean up pending permission for the user (by username and email address(es)) just in case

**Comment by tsenart** [comment]
@unknwon: Is this going to be complete in time for the 3.12 release? If not, please change the milestone accordingly.

**Comment by unknwon** [comment]
Changing this to 3.13 so I could focus more on prioritized items.
