### ISSUE TITLE
a8n: Running ChangesetJobs is not serializable

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#7309]
Right now it's possible to call the `RetryCampaign` mutation from two requests and the code would run the same `ChangesetJobs` at the same time:

https://github.com/sourcegraph/sourcegraph/blob/c43e9cc674c361aeda9f51b53ed99efe80290fc8/enterprise/internal/a8n/resolvers/resolver.go#L310-L322

That can possibly lead to multiple git pushes to the same branch at the same time.

The same holds true for `PublishChangesetPlan` which would create only a single `ChangesetJob` but run it multiple times:

https://github.com/sourcegraph/sourcegraph/blob/b8545df26897db870b9e87c95479bac3ed3d0464/enterprise/internal/a8n/resolvers/resolver.go#L693-L709

**Comment by tsenart** [comment]
Notable mention of some Postgres features to look into that could be part of a solution: Row level locking (i.e. `SELECT FOR UPDATE`), serializable level transactions, advisory locks.

**Comment by ryanslade** [comment]
My initial thoughts on this are that what we want is distributed locking as we want to avoid concurrent calls both on the same frontend and potentially across multiple frontend instances.

The locks need to be held across more than just SQL transactions as we also need to avoid concurrent calls to github for example.

Something like this could be useful:
https://github.com/cirello-io/pglock

But, I'll have a think about whether there is a simpler approach where we don't need to pull in another external library.

**Comment by ryanslade** [comment]
After a little more reading I'm going to go ahead and try using advisory locks at the transaction level.

The plan is to grab a transaction at the start of `RunChangesetJob` and attempt to grab a lock tied to that transaction. For now we can return an error if we're unable to acquire the lock. The lock will be released when the transaction ends.

By doing it this way we're essentially putting a distributed mutex around `RunChangesetJob` which ensures that only one call is ever made concurrently.

**Comment by tsenart** [comment]
@ryanslade: We have used advisory locks before in other areas of the codebase which may save you some time:

https://github.com/sourcegraph/sourcegraph/blob/4fd7418ff25116246c0afa06f2298b048b7286f2/enterprise/cmd/frontend/internal/authz/bitbucketserver/store.go#L160
