### ISSUE TITLE
Structural search needs code monitoring support

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#7316]
![Screen Shot 2019-12-19 at 1 08 26 PM](https://user-images.githubusercontent.com/888624/71205956-bb221800-2260-11ea-9bd1-4e80c92d50a9.png)

**Comment by camdencheek** [comment]
Code monitoring only supports `type:commit` or `type:diff`, which do not support structural search. We have no plans to expand structural search support to diffs, so this is unlikely to ever be implemented. Closing as "won't do"
