### ISSUE TITLE
Support GitLab projects with multiple nested subgroups

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#7321]
In the GitLab external service, we allow listing projects by ID or name. The name option restricts names to have only 2 components `<group>/<name>`, but GitLab can have nested subgroups. We should support listing these by name, as well.

**Comment by keegancsmith** [comment]
@beyang FYI there is a version of #7375 that is on the 3.11 branch. However, it looks like you directly committed that before creating the PR. It is failing the unit tests. I just re-cherry-picked #7375 and now the tests pass.

- old commit on 3.11 is 36758031615eeccc183366c88d3f46464b89ee20 which additionally has the tag 3.11.1 (I am guessing it didn't build?)
- New commit on 3.11 is 97214a9e74091f01368c469e44eb123393712989
