### ISSUE TITLE
Org reports out-of-disk space when cloning repositories with Git LFS

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#7322]
From the admin:

> We noticed some issue related to cloning repositories and I suspect it might be related to LFS support. After we configured our BitBucket server in external service, Sourcegraph started to clone all the repositories we specified using repository query. The problem is that those repositories are much bigger in size that the same repos stored in bitbucket (5gb on sourcegraph git-server comparing to 10mb on bitbucket server).

@sourcegraph/core-services I think we may need to configure gitserver to ignore LFS contents (https://stackoverflow.com/questions/42019529/how-to-clone-pull-a-git-repository-ignoring-lfs). Can one of you own this?

**Comment by dadlerj** [comment]
Reported by https://app.hubspot.com/contacts/2762526/company/1767812339
