### ISSUE TITLE
Unexpected no results in comby search

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#7330]
https://sourcegraph.com/search?q=repo:sourcegraph/go-diff+%22bytes.Split%28:%5Bargs%5D%29%22&patternType=structural has no results, despite https://sourcegraph.com/search?q=repo:sourcegraph/go-diff+bytes.Split&patternType=literal (literal) having results.

**Comment by rvantonder** [comment]
It looks like we do not index `sourcegraph/go-diff` on sourcegraph.com. Unindexed repos are not supported. I tried to make this visible ([first bullet here](https://docs.sourcegraph.com/user/search/structural#current-functionality-and-restrictions)). You query works fine on k8s https://k8s.sgdev.org/search?q=repo:%5Egithub%5C.com/sourcegraph/go-diff%24++bytes.Split&patternType=structural

Raising an alert in the search results area would be informative.

**Comment by rvantonder** [comment]
PR up at #7337 as a proposal to help clear this up. @sqs could you look at the phrasing there for casual users of sourcegraph.com? The feature and alert might be a nice prompt for users to try a self install.

**Comment by rvantonder** [comment]
Addressed in #7337. I hope to lift this soon and enable unindexed structural search.
