### ISSUE TITLE
Sourcegraph docs requires deletion of Pod to reflect resource/asset changes

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#7336]
It appears that the docsite will pull in content (markdown) changes dynamically (~ every 5 mins) but resource changes such as updating the template require the Pod to be killed.

![docsite](https://user-images.githubusercontent.com/133014/71296341-f2acd380-23ca-11ea-8ee8-9d1ab8b75eab.gif)

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.12 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by nicksnyder** [comment]
3.12 is done so I am moving this to the backlog.

**Comment by unknwon** [comment]
For the record, there is the command for cheatsheet: `kubectl delete pod docs-sourcegraph.com-$PODID`

**Comment by ryan-blunden** [comment]
#9427 has been created to address this and aims to be shipped in time for the 3.15 release.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
