### ISSUE TITLE
Flaky search stats page test

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#7355]
`Search statistics` `page` test was consistently flaky and disabled in https://github.com/sourcegraph/sourcegraph/pull/7353.

**Comment by sqs** [comment]
looking into this now

**Comment by sqs** [comment]
Representative failures:

- https://buildkite.com/sourcegraph/sourcegraph-e2e/builds/1676#ff022cfa-a0cc-4aac-846c-a1d6e15743ff/160-755
- https://buildkite.com/sourcegraph/sourcegraph-e2e/builds/1671#32dc2666-4747-4de3-9b62-178b9207742e/143-773
