### ISSUE TITLE
Search suggestions dropdown does not dismiss when clicking out of it

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#7358]
Repro:

1. Go to https://sourcegraph.com/github.com/sourcegraph/sourcegraph@39f93e5/-/blob/enterprise/cmd/frontend/auth/saml/middleware.go#L122
1. In the search query input, type any letter (such as <kbd>a</kbd>)
1. Wait for the search suggestions dropdown to show up (as expected)
1. Click in the blob view

Expected: clicking in the blob view should dismiss the search suggestions dropdown.

Actual: sometimes it dismisses it but then it comes back again in 1-3s. Sometimes it doesn't dismiss it at all.

**Comment by attfarhan** [comment]
This looks like it is caused by `repeat()`, which re-emits previous values, and us setting `showSuggestions: true` on each completion of `componentUpdates`. https://sourcegraph.com/github.com/sourcegraph/sourcegraph@20ef5f3b45d54cda0a75dd85ac17b65c1806fe04/-/blob/web/src/search/input/QueryInput.tsx
