### ISSUE TITLE
No nav links on Sourcegraph.com for unauthed users

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#7359]
I know we've been fixing issues in this code recently. I found another regression. As an unauthed user, there are no about/sign-in links. There should be on Sourcegraph.com. I think this is a simple bug where the NavLinks component is not being shown (and when it's shown, it will show the correct set of links).

![image](https://user-images.githubusercontent.com/1976/71339019-ee85d080-2506-11ea-9d66-b2f269e28ca7.png)

**Comment by attfarhan** [comment]
Fixed this by adding `auth.public: true` to sourcegraph.com
