### ISSUE TITLE
Firefox: Forbidden - CSRF token invalid

### ISSUE THREAD

**Issue by philjones** [sourcegraph/sourcegraph#7368]
I've been following the quick-start + GitLab instructions for getting the new integration working within GitLab.

I got a must be logged into sourcegraph error in GitLab and even though I was logged in, I thought perhaps it needs the OAuth authentication setup - so I followed the instructions for configuring that and logged in.

The GitLab sign-in doesn't work - "The redirect URI included is not valid." though I'm pretty sure I followed the instructions - not sure if it's not happy about the port or the http sourcegraph (it's https).

Now every request to login (with the regular account I was previously using) is failing with "Forbidden - CSRF token invalid".

I've cleared cookies, session, tried new browsers, etc. - same issue.

I see a graphQL log 
![image](https://user-images.githubusercontent.com/692676/71368847-09902900-2577-11ea-9fc3-85a406a6707d.png)

ahead of each of the login attempt - not sure if that's "using up" the CSRF token.

I can't access the site configuration because I can't login so I can't undo the GitLab OAuth setup either.

**Comment by slimsag** [comment]
Hi there, apologies for the long delay (many of us were out for holiday break).

I'm not 100% positive how you would've ended up in this state, and I can confirm the graphQL log is not "using up" CSRF tokens. My guess is that some combination of changing HTTP <-> HTTPS and the auth method configuration in Sourcegraph has left the sessions in the Redis DB in an invalid state (but still associated with the users).

Could you try the following and let me know if it helps? Grab a redis-CLI prompt:

```sh
docker ps # look for the sourcegraph container name
docker exec -it $SOURCEGRAPH_CONTAINER redis-cli 
```

Then at the prompt, enter:

```
127.0.0.1:6379> FLUSHDB
OK
127.0.0.1:6379> exit
```

This will sign out all users and clear the session data on the Sourcegraph side, after which you should no longer have any issues signing in.

**Comment by philjones** [comment]
Thanks for the instructions - I managed to get into the redis prompt and the FLUSHDB command returned "OK". 

Login / Reset password / etc. still all receive the "Forbidden - CSRF token invalid".

I tried stopping and restarting docker which didn't change anything.

The username of the gitlab user I was trying to log in as and the one that I had originally setup on the sourcegraph instance do overlap if that will cause issues.

Any other ideas?

**Comment by slimsag** [comment]
Hi @philjones so sorry for the delays here. Can you do the following for me:

1. If you are running a Sourcegraph version older than v3.11.0, upgrade (simply stop the old Docker container and start the new one using the run command on https://docs.sourcegraph.com )
2. Use the `docker exec` command provided here to edit your site configuration: https://docs.sourcegraph.com/admin/config/site_config#editing-your-site-configuration-if-you-cannot-access-the-web-ui

Once you have the editor open, copy the site configuration and post it here with any secrets redacted. I suspect that one of the following is misconfigured:

- `externalURL` (the URL you access Sourcegraph at)
- Your GitLab `"auth.providers"`

Please also let me know: Are both GitLab and Sourcegraph running under HTTP or HTTPS, or is one different from the other?

Appreciate your time, sorry this is so tedious to resolve!

**Comment by tsenart** [comment]
@slimsag: We're doing 3.13 triage for Core Services. I see you added this to the 3.12 milestone. Do you plan on working on this? If so, we'll take out the `team/core-services` label. Let us know.

**Comment by tsenart** [comment]
Ping @slimsag

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.12 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by tsenart** [comment]
@slimsag: Taking this on our 3.13 plan. @kzh assigned to you.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.13 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by felixfbecker** [comment]
This issue is reproducible with the new version of Puppeteer: https://github.com/sourcegraph/sourcegraph/pull/6966

**Comment by unknwon** [comment]
Taking out of 3.14 to have more focus on shipping RFC 113.

**Comment by dcrodman** [comment]
Hey @philjones, are you by any chance using Firefox? I ran into the same thing and found that I wasn't able to reproduce the issue in Chrome. After some digging it looks like Firefox isn't sending the `sg_csrf_token` cookie when making the POST request to create an account and this causes the CSRF validation (in gorilla/csrf) to fail.

 I was able to bypass it on Firefox by setting`SameSite=Lax` on the cookie with a debugger, I think it just doesn't like `SameSite=None`/unrestricted mode. Happy to submit a PR to change this (since it looks like a default) but I'm hesitant to do so without knowing whether or not this is intentional or what it might affect.

**Comment by unknwon** [comment]
> I was able to bypass it on Firefox by setting`SameSite=Lax` on the cookie with a debugger, I think it just doesn't like `SameSite=None`/unrestricted mode. Happy to submit a PR to change this (since it looks like a default) but I'm hesitant to do so without knowing whether or not this is intentional or what it might affect.

I think we recently changed this to `None` because of Chrome 80 cc @uwedeportivo

**Comment by felixfbecker** [comment]
I think this happens only when using HTTP and latest browser versions - more context in this thread: https://github.com/sourcegraph/sourcegraph/issues/6167

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by unknwon** [comment]
While following along all discussions around cookies, I think this is a combined problem of browser and the Sourcegraph instance setup. With our effort in https://github.com/sourcegraph/sourcegraph/issues/6167, this should be closed until it resurfaces (with probably different cause and needs a new ticket anyway).

**Comment by mrnugget** [comment]
Fresh instance, `sourcegraph/server:insiders`, on an Ubuntu machine. Connected via SSH and forwarding port 7080 to localhost with

```
gcloud beta compute --project "sourcegraph-dev" ssh --zone "europe-west3-c" "thorstens-big-test-instance-2" -- -L 7080:localhost:7080
```

I run into `CSRF token invalid` when trying to create the initial site admin account.

But only when using Firefox 75, with Chrome  81.0.4044.129 it seems to work.

![csrf_protection](https://user-images.githubusercontent.com/1185253/81179477-ff148000-8fa9-11ea-9fca-518eadceaed9.gif)

**Comment by mrnugget** [comment]
@unknwon and I just tried to reproduce this on a call and couldn't. After I could reproduce it 4-5 times alone!

We believe it has something to do with me having used `localhost:3080` for my local dev instance yesterday and that leaving a cookie for the `localhost` domain in my browser. When I then tried to create a new account on `localhost:7080` (which is forwarding to the new instance) it used the cookie and complained about CSRF.

I then access the fresh instance through `http://127.0.0.1:7080` and that worked and after that we couldn't reproduce it.

**Comment by unknwon** [comment]
After few other occurrences I witnessed, I think the problem here is that having site config `externalURL` having `https://` prefix and accessing the instance via `http://`. In this scenario, the browser won't persist cookie because the server will set `Secure` flag for all cookies. Thus, closing it for now.
