### ISSUE TITLE
Commit message search results lack H-padding

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#7379]
At https://sourcegraph.com/search?q=type:commit+test+repo:sourcegraph/sourcegraph%24&patternType=regexp, for example, there is no horizontal padding (eg to the left of the yellow "Skip flaky symbols" monospace text).

![image](https://user-images.githubusercontent.com/1976/71432150-3da93e00-268c-11ea-8346-87f2a0cd65b6.png)

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.12 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
