### ISSUE TITLE
Add search results provider (extensibility point)

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#738]
Extensions should be able to contribute search results to a search. For example, if I type a query `foo` into Sourcegraph or GitHub search, it should be possible for extensions to provide additional results that are displayed on the search results page.

Use cases: extensions that provide search results from:

- Google Docs
- Formatted documentation (e.g., from Sphinx, JSDoc, etc.)
- JIRA tickets' full text and metadata (related: https://github.com/sourcegraph/issues/issues/141)
- Logs (e.g., by hitting the search API of your logging system)

This makes it possible for developers to have a single search box that searches everything they care about (all of their tools/systems).

Customers:

- https://app.hubspot.com/contacts/2762526/company/561806411 for config data
- https://app.hubspot.com/contacts/2762526/company/407948923 for docs

**Comment by camdencheek** [comment]
Closing since we have removed extensions from the product and have no plans to allow contribution of custom search results.
