### ISSUE TITLE
API reference documentation

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#739]
We need good, extensive API documentation, like https://code.visualstudio.com/docs/extensionAPI/vscode-api.

## Proposal:

Use [typedoc](https://github.com/TypeStrong/typedoc) to generate API documentation, and either include it in the npm package or publish a second `sourcegraph-docs` package. Then link to it on https://upkg.com.

Here's an example of how this can look like:

https://github.com/felixfbecker/abortable-rx
https://unpkg.com/abortable-rx/docs/

The advantage is that the API docs can be viewed for any exact version, forever.

**Comment by ryan-blunden** [comment]
Extension API documentation is now available at https://unpkg.com/sourcegraph/dist/docs/index.html
