### ISSUE TITLE
Line BG colors from multiple extensions can clobber each other

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#740]
If two extensions publish decorations for the same line, the precedence and merging behavior is undefined. (E.g., extension A says line 15 should have a blue background color, and extension B says line 15 should have a red background color.)

VS Code solves this by recommending setting the alpha channel to less than 100% (so that the decorations are somewhat transparent). We also need to add support for this in each client (browser extensions, Sourcegraph.com web app, etc.).

**Comment by fkling** [comment]
This is not a problem anymore because we don't have inline extensions anymore.
