### ISSUE TITLE
Hovering a definition and then clicking "find implementations" breaks further hover of definitions

### ISSUE THREAD

**Issue by brianfeister** [sourcegraph/sourcegraph#742]
Steps to reproduce:

1. Visit [https://sourcegraph.com/github.com/sourcegraph/browser-extensions/-/blob/src/browser/permissions.ts#L27:17](https://sourcegraph.com/github.com/sourcegraph/browser-extensions/-/blob/src/browser/permissions.ts#L27:17)
1. Hover the function `remove`
1. Click `Find Implementations` in the hover / popup UI
1. `No Implementations Found` is shown in footer UI
1. Hovering definitions of any function in the file is broken and no longer show hover / popup UI
1. Note that the following error happens in the Chrome dev tools console, though I'm not familiar enough with it to say if it's related or not 
`blob:https://sourcegraph.com/15c0e75c-1f32-43c4-af6e-1ca1eab78172:303 An error occurred when sending LSP requests to the language server, disabling this instance of the language extension (reload the page to clear this state).  Error: Method textDocumentImplementation not implemented
    at sourcegraph.commands.executeCommand.then.responses (blob:https://sourcegraph.com/15c0e75c-1f32-43c4-af6e-1ca1eab78172:240)`

**Comment by chrismwendt** [comment]
Fixed in https://github.com/sourcegraph/sourcegraph-langserver-http/pull/9
