### ISSUE TITLE
Version number is wrong for 3.11.0, causing update checker to not work

### ISSUE THREAD

**Issue by morganestes** [sourcegraph/sourcegraph#7442]
- **Sourcegraph version:** 3.11.0
- **Platform information:** Docker on Digital Ocean droplet

#### Steps to reproduce:

1. Run `docker run --publish 7080:7080 --publish 127.0.0.1:3370:3370 --rm --volume ~/.sourcegraph/config:/etc/sourcegraph --volume ~/.sourcegraph/data:/var/opt/sourcegraph sourcegraph/server:3.11.0` (per docs) to create a local instance of Sourcegraph with Docker.
2. Go to http://127.0.0.1:7080/site-admin/updates and get an error notice `Error checking for updates: Update endpoint returned HTTP error 400: "1548 is a bad version string:"`

![Screenshot_2020-01-02 Updates - Admin - Sourcegraph](https://user-images.githubusercontent.com/110755/71681066-bd549e00-2d59-11ea-98c9-f3056c256dcc.png)

#### Expected behavior:
Version should be set to 3.11.0 in Docker Hub.

#### Actual behavior:
Version is set to 1548 in [the Docker image](https://hub.docker.com/layers/sourcegraph/server/3.11.0/images/sha256-fd0048cc6d3ec4f0218e03680a26fada56c05ad756d05f5cd68a3bbad89ce2d6), causing errors in update checker.

**Comment by slimsag** [comment]
@beyang Do you know why this would've happened in our new release scripts, and can we ship a patch to fix this ASAP?

**Comment by slimsag** [comment]
@ggilmore was this fixed in the latest patch releases?

**Comment by beyang** [comment]
Fixed in 3.11.4
