### ISSUE TITLE
The Files list toggle icon overlaps with the github homepage icon

### ISSUE THREAD

**Issue by thanos-irodotou** [sourcegraph/sourcegraph#745]
When `GitHub file tree navigation.` is checked in the extension's settings the icon that toggles the file tree list is placed on the top left of the webpage view, in github that's the default place for the homepage icon which is quite handy to click on at times, hence the placement of the File tree icon is hindering that functionality. 

Maybe a better placement would either be the bottom left/right of the page as github seems to be more clattered in the center leaving those areas usually empty.

What it looks like:
![screen shot 2018-10-26 at 10 49 10](https://user-images.githubusercontent.com/6057330/47559241-e59e6c80-d90c-11e8-8a8f-91c24891c9c7.png)

_sorry if this has already been raised or fixed_
Cheers.

**Comment by sqs** [comment]
This icon and the file tree feature was removed from the browser extension
