### ISSUE TITLE
Code host fingerprinter

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#7464]
An experiment to drastically simplify our onboarding process for most first time admins. A user gives us an URL from the code host and we discover what kind of code host it is and a reasonable config for it. We should be able to discover what kind of code host most are via normalizing URLs and trying well-known and unique queries.

The deliverable for this experiment is a simple binary which takes the URL and spits out our guess. If it seems to work reasonably well, we can look into integrating it into an onboarding flow.

**Comment by nicksnyder** [comment]
I think this is good to experiment with. @beyang mentioned a concern though in the distribution team meeting yesterday: this might speed up onboarding, but it could come at a cost of not training the user how to do more advanced configuration; it would be nice if onboarding were not a special case. More generally, @beyang and @slimsag found a lot of value in sitting in on customer calls to observe where they got tripped up, so to the extent that you are interested in this problem I think it would be valuable for you to do this too (if you haven't already recently).

**Comment by keegancsmith** [comment]
> I think this is good to experiment with. @beyang mentioned a concern though in the distribution team meeting yesterday: this might speed up onboarding, but it could come at a cost of not training the user how to do more advanced configuration; it would be nice if onboarding were not a special case.

This ticket is more to experiment/validate the idea of how little we can do to add a code host. I think whatever we do here can address those concerns when properly integrated into our product. For example for v0 of this I was thinking it would just generate the config for the user. But then still dump the user into the settings editor for them to hit save. From that point we can iterate on the process.

> More generally, @beyang and @slimsag found a lot of value in sitting in on customer calls to observe where they got tripped up, so to the extent that you are interested in this problem I think it would be valuable for you to do this too (if you haven't already recently).

I have not been doing this at all. I'll reach out to the team to see what calls I can sit on in.

**Comment by keegancsmith** [comment]
I ended up spending most of this week on issues in our core services tracking issue. I'll likely only start tackling this on Monday.

**Comment by keegancsmith** [comment]
Deprioritizing for 3.13, will revisit for planning in 3.14. The work on my plate for 3.13 has expanded and it looks unlikely I will finish this before then.
