### ISSUE TITLE
Build up testing infrastructure

### ISSUE THREAD

**Issue by ijsnow** [sourcegraph/sourcegraph#747]
- [x] Add unit testing infra
- [ ] Run e2e tests on all code hosts and with extensions
- [ ] Make `cypress-browser-extension-plugin` work with us better so that we can test more than just content scripts
- [ ] Unit test `libs/code_intelligence`
...

**Comment by lguychard** [comment]
Some of this is now irrelevant, and 'Run e2e tests on all code hosts' is tracked in #5294, closing.
