### ISSUE TITLE
Send email notifications when important user account information is changed

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#7517]
When important user data is changed, we should send an email notification to tell the user what changed. This will alert the user in the event that their account has been taken over by someone else (to be clear, this has not ever happened).

For example:
- Adding email address
- Removing email address
- Changing password
- Adding an access token

Since auth is owned by @sourcegraph/core-services I am assigning @tsenart. This is not a high priority since there is no private code on sourcegraph.com and on-premise instances generally use some sort of SSO.

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
