### ISSUE TITLE
Buttons on GitLab bunch up and are incorrect

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#752]
On https://gitlab.com/gitlab-org/gitlab-runner/merge_requests/1058/diffs:

- There are 2 plug icons
- **View File** should be sentence case (lowercase "F")
- The plug and "Inline discussions" icons should be laid out horizontally, not one on top of each other
- The alignment of the leftmost plug icon is wrong (it should be in the middle of its button; instead it is most toward the bottom of the button)
- Inline discussions shouldn't show up on the PR because they don't actually work here (this is a deeper extension API feature request, most likely)

This issue contains multiple problems, so please create separate issues from these as needed.

![screenshot from 2018-10-17 09-48-21](https://user-images.githubusercontent.com/1976/47102513-d1ae8880-d1f1-11e8-86a8-745f4fad6adb.png)

**Comment by ryan-blunden** [comment]
![screen shot 2018-12-18 at 4 44 03 pm](https://user-images.githubusercontent.com/133014/50191802-45e5d500-02e4-11e9-9714-ec71943ba88e.png)

The View file button is misaligned too.

**Comment by christinaforney** [comment]
This appears to be fixed so am going to leave it closed, although we should look at why the sentry button is spaced differently (@vanesa):

![image](https://user-images.githubusercontent.com/1559622/59739281-196e2f80-9219-11e9-89e3-15fcd7d23740.png)
