### ISSUE TITLE
Enforce minimum password requirements

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#7521]
Right now our built-in auth provider allows passwords as short as 1 character. I think we should enforce some minimum password length by default (e.g. 12 characters for sourcegraph.com) which is configurable per instance.

This is not urgent because there is no private code on sourcegraph.com and most customers use some form of SSO.

Assigning to @tsenart to triage.

**Comment by tsenart** [comment]
@nicksnyder: Is this fixed by #7514?

**Comment by tsenart** [comment]
Oops, I see it doesn't.

**Comment by unknwon** [comment]
qq: It seems to me the core part is changing `checkPasswordLength` to the following:

```go
func checkPasswordLength(pw string) error {
	if utf8.RuneCountInString(pw) < minPasswordRunes || 
		utf8.RuneCountInString(pw) > maxPasswordRunes {
		return errcode.NewPresentationError(fmt.Sprintf("Passwords may not be less than %d or be more than %d characters.", minPasswordRunes, maxPasswordRunes))
	}
	return nil
}
```

Am I missing anything? (I changed to `estimate/0.5d`)

**Comment by nicksnyder** [comment]
That is all you need to change (aside from adding a config option).
