### ISSUE TITLE
Add documentation for setting up Grafana alerting

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#7523]

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.12 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by slimsag** [comment]
Fixed in 3.13 via https://github.com/sourcegraph/sourcegraph/pull/7786
