### ISSUE TITLE
Identify further service-specific metrics missing from new Grafana dashboards + alerts

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#7524]
Look at the list of metrics exported by each service today, confirm they are covered appropriately in the Grafana dashboards and alerts.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by slimsag** [comment]
For the most part this is complete or covered by existing issues.
