### ISSUE TITLE
Identify further inter-service communication metrics missing from new Grafana dashboards + alerts

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#7525]
In 3.11 we added a number of new dashboards and alert definitions, but we can probably still improve with monitoring inter-service communication a bit. This issue is to track that I need to investigate which ones are missing, and file issues for (or just add) them.

To close this issue, I should feel confident we're covering 100% of inter-service communication failure points which have been a pain for customers in the past. This includes:

- Success/failure error rates
- DNS failures
- Outright network failures
- Unable to connect to services (without users sending requests, e.g. if an admin sets an env var incorrectly).

**Comment by slimsag** [comment]
See also #6593 and #6599 which help this issue.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by davejrt** [comment]
This seems out of date, and ambiguous. Closing in favor of raising issues for each metric and assigning to the appropriate team.
