### ISSUE TITLE
Not dogfooding the monitoring we ship to customers

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#7527]
Dogfood our own new alerting by configuring k8s.sgdev.org and sourcegraph.com to alert to our Slack channels.

In the future, this would supersede alertmanager. See also https://github.com/sourcegraph/sourcegraph/issues/7528

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by bobheadxi** [comment]
Related: https://github.com/sourcegraph/sourcegraph/issues/5370

**Comment by slimsag** [comment]
Closing in favor of https://github.com/sourcegraph/sourcegraph/issues/5370 which has more concrete details and steps.
