### ISSUE TITLE
observability: Add monitoring to signal whether instance is underprovisioned or not

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#7529]
A site admin should be able to visit Grafana and easily identify if their instance may be under-provisioned or over-provisioned, having relatively-clear actions to take.

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.12 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by bobheadxi** [comment]
@slimsag I'd be interested in tackling this after my current issues are wrapped up!

**Comment by slimsag** [comment]
Great! One pre-requisite to this is going to be fixing this: https://github.com/sourcegraph/sourcegraph/issues/9791

**Comment by bobheadxi** [comment]
Alerts for:

* warning CPU too high (> 95%)
* warning CPU too low (< 5%)
* warning restart count high (>0)
* base memory thresholds on what we see in live, make a guess for now

**Comment by bobheadxi** [comment]
@slimsag looks like there are already alerts in place: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@583d470abf479098ba8afc394b11b4d90a1431dc/-/blob/monitoring/shared.go#L52

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
