### ISSUE TITLE
Searcher dashboard incorrectly reports on query-runner

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#7531]
https://k8s.sgdev.org/-/debug/grafana/d/searcher/searcher?orgId=1 shows some stuff about query-runner:

![image](https://user-images.githubusercontent.com/3173176/71932074-689b9380-315c-11ea-919e-f03cb3c72b5c.png)

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.12 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
