### ISSUE TITLE
Detect when browser extension is not configured for private sourcegraph instance

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#754]
If I have the Sourcegraph browser extension installed and visit a private Sourcegraph instance (e.g. sourcegraph.example.com) then I would expect the browser extension to prompt me to configure it with the url of the private Sourcegraph instance I am visiting.

**Comment by felixfbecker** [comment]
This is implemented as of our last iteration as part of RFC 221 🚀 

![image](https://user-images.githubusercontent.com/10532611/96148300-6dba1a00-0f08-11eb-9b2b-bc1e5a79c64b.png)

![image](https://user-images.githubusercontent.com/10532611/96148231-5b3fe080-0f08-11eb-82e9-fd5d2b6d1ab4.png)
