### ISSUE TITLE
a8n: Use the same git committer and author

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#7546]
Right now we use different values for the `GIT_COMMITTER_{NAME,EMAIL}` and `GIT_AUTHOR_{NAME,EMAIL}` values.

That's not only ugly but also not even helpful (it might be if the `AUTHOR` were the user that created the campaign.

I propose that we change this code to allow specifying the `GIT_COMMITTER_{NAME,EMAIL}` and then pass in the same information as we do for the author:

https://github.com/sourcegraph/sourcegraph/blob/454ce5a044cd8e9294125115b23d3ddde5a4012f/cmd/gitserver/server/patch.go#L126-L146

Or we change the code so that only `GIT_COMMITTER` is set, but to the values that we pass in.

**Comment by ryanslade** [comment]
I'm taking a quick look at this
