### ISSUE TITLE
a8n/core: Expose comments of all changesets in campaign in GraphQL API

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#7548]
From [RFC 20](https://docs.google.com/document/d/1UY9B_kLlwRtYj-fuv7XZS1-Mu99Czx9Ojm7sgEmoQIA/edit)

We want to sync comments on changesets in one direction so that they appear on the campaign page.

**Comment by eseliger** [comment]
do we expect this to be more like a timeline, like github has it, or more as an extension to the rows in the changesets tab, having some toggle between "Discussion" and "Diff" or something?

**Comment by sqs** [comment]
Deprioritized (moving from 3.13 to backlog) because none of the private beta customers have told us this is necessary to start using campaigns.

**Comment by tsenart** [comment]
@christinaforney: Have priorities changed here or is this still not important?

**Comment by christinaforney** [comment]
Still not important yet.

**Comment by malomarrec** [comment]
Related #20738

**Comment by malomarrec** [comment]
Closing this, and keeping the parent ticket #7688 open for tracking.
