### ISSUE TITLE
Show combined event timeline from all threads, with PR/issue comments

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#7551]
From [RFC 20](https://docs.google.com/document/d/1UY9B_kLlwRtYj-fuv7XZS1-Mu99Czx9Ojm7sgEmoQIA/edit)

This should appear on the campaign detail page

**Comment by mrnugget** [comment]
Closing this, because we haven't gotten any requests for this ever since opening the ticket and we need to re-think our roadmap/goals anyway. If we decide we want to do this, we can reopen this ticket.
