### ISSUE TITLE
a8n/core: Extend GraphQL API to include participant users involved in the campaign

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#7552]
From [RFC 20](https://docs.google.com/document/d/1UY9B_kLlwRtYj-fuv7XZS1-Mu99Czx9Ojm7sgEmoQIA/edit)

This should appear on the campaign detail page

**Comment by eseliger** [comment]
do we expect this to be more like a timeline, like github has it, or more as an extension to the rows in the changesets tab, having some toggle between "Discussion" and "Diff" or something?

**Comment by eseliger** [comment]
I think first thing to do here is define who is "involved" in a campaign, the RFC doesn't specify that.

Are participants:
- All that edited/created the campaign itself?
- All that triggered any gql mutation on the campaign? (so 1. + things like publishing a single changeset)
- All people that interacted with the externalchangesets on the code hosts? 

I think, considering campaigns can grow _very_ large, the last point is not very helpful(?). In a company with a lot repositories, chances are high that almost every employee is in the list of participants when it was fully merged (assuming everyone owns at least something)

**Comment by sqs** [comment]
Deprioritized (moving from 3.13 to backlog) because none of the private beta customers have told us this is necessary to start using campaigns.

**Comment by tsenart** [comment]
@sqs: The `planned/$MILESTONE` label should not be removed when something is deprioritised as it is meant for us to visualise that in the tracking issue. Documentation: https://about.sourcegraph.com/handbook/engineering/core-services#monthly-planning

**Comment by tsenart** [comment]
In other words, it means it was planned at one point in time, not that it is still in scope.

**Comment by tsenart** [comment]
@ryanslade: Please keep your assignment until the end of the iteration so we can review which work got deprioritised per person.

**Comment by tsenart** [comment]
@christinaforney: Do we have customers that require or want this (asking for @mrnugget as part of triaging).

**Comment by christinaforney** [comment]
Not a priority until we can get more feedback on campaigns in use.

**Comment by chrispine** [comment]
Now we show who created/edited/updated a campaign, so I'm closing this one.
