### ISSUE TITLE
a8n/core: GraphQL API for an extended campaign list view

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#7553]
From [RFC 20](https://docs.google.com/document/d/1UY9B_kLlwRtYj-fuv7XZS1-Mu99Czx9Ojm7sgEmoQIA/edit)

An overall campaign list shows all active campaigns (globally, and for a specific namespace) and some indication of their progress

**Comment by mrnugget** [comment]
This is still pretty undefined. I just synced with @ryanslade on this. This ticket includes talking to @christinaforney and @sqs about the ideas behind this ticket and talking to @felixfbecker and @eseliger about the API and frontend implementation.

**Comment by sqs** [comment]
- In GraphQL API, add `Query.campaigns` parameters for showing only open campaigns, only closed campaigns, and all campaigns (default, and also the current behavior).
- In UI, in the campaigns list, show open campaigns by default, but allow the user to toggle to see closed campaigns.

The other parts (such as showing campaigns per-namespace, like as an other tab on your user/org pages; and showing more campaign summary info such as number of open/closed changesets in the list items) are not necessary. More campaign summary info is nice, and feel free to show it if it's easy, but it's not needed.
