### ISSUE TITLE
a8n: Campaign type to update Ruby gem dependencies

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#7557]
From [RFC 36](https://docs.google.com/document/d/1DKWy2zC6_rDZzoPS7ASUpvnVDK3Zj6cf_I9Riq9KNu0/edit)

Find usages of a specific Ruby gem dependency and proposing upgrade PRs to Gemfile/Gemfile.lock

**Comment by mrnugget** [comment]
Closed by #8008 for now.
