### ISSUE TITLE
No codeintel, Uncaught Error: File actions not found. Make sure you aren't trying to create a toolbar mount for a code snippet that shouldn't have one

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#756]
When I reviewed this PR, I did not get code intel: https://github.com/sourcegraph/browser-extensions/pull/245/files

This error was in the console:

![image](https://user-images.githubusercontent.com/10532611/46939732-6173fb80-d067-11e8-9a8a-ec73085765d3.png)

Besides the error being a bug, there seems to be poor error handling if this bubbles up as an uncaught exception that breaks all other functionality.

**Comment by ijsnow** [comment]
Can't repro
