### ISSUE TITLE
a8n: Automatically run credential / token searches in the background

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#7565]
From [RFC 73](https://docs.google.com/document/d/143FIe1Tak4_YPPuOuEzuobTQW09ZU85WfOCdZkNwIVQ/edit#heading=h.b5eblutsndzz)

A way to periodically (in the background) run this, so that it doesn't only re-scan all repositories when a user interactively visits and updates the campaign in their web browser.

**Comment by mrnugget** [comment]
Closed by #8008 for now.
