### ISSUE TITLE
Using the mouse in interactive search popups doesn't work

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#7568]
Using the mouse with the interactive search doesn't work. When you click on the checkmark, the filter is not added. You have to hit return on the keyboard.

![interactive_search](https://user-images.githubusercontent.com/1185253/71998135-6100eb00-323f-11ea-905a-a625230100ad.gif)

**Comment by attfarhan** [comment]
@mrnugget I can't actually repro this on sourcegraph.com. It seems like you were doing this on local dev? Are you able to repro still?

**Comment by mrnugget** [comment]
I'm on `master`, running enterprise. I can still reproduce it. Do you need more information?

**Comment by mrnugget** [comment]
![interactive_mode](https://user-images.githubusercontent.com/1185253/72618252-ff293b00-393a-11ea-896a-5e1b4c045f98.gif)

Still persists on latest master. I think this is a release blocker, to be honest.

**Comment by attfarhan** [comment]
Ah, it's on Firefox. Works fine in Chrome, which is why I couldn't repro. Will fix.
