### ISSUE TITLE
Firefox extension stopped working entirely, cannot get it to work again at all

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#7579]
I observed a user:

1. Install the Firefox extension, and get it working OK with public code through Sourcegraph.com.
2. Configure the extension to use their own Sourcegraph instance URL.
3. Configure the extension to use `https://sourcegraph.com` again.

At this point:

- The extension stopped working entirely on all public Go files (no hovers, jump to definitions, etc).
- It was clearly loaded fine, e.g. the "jump to repo on Sourcegraph" button at top of GitHub page worked.
- There were no console errors, even with "Allow error reporting" turned on.
- The extension clearly showed `Connected` to `https://sourcegraph.com`
- Restarting Firefox did not resolve the issue.
- The extension did not make ANY network requests to Sourcegraph.com

Video demonstrating the issue: https://drive.google.com/file/d/1sC_tWzzP8xuepxVH2zcK4TYgo2Iz6j4T/view?usp=sharing

The file the user was trying: https://github.com/Andoryuuta/Erupe/blob/master/channelserver/session.go

**Comment by slimsag** [comment]
After restarting firefox, uninstalling the extension, and installing it again it is still broken:

![image](https://user-images.githubusercontent.com/3173176/72030196-898be380-3245-11ea-91d3-da4413e8f417.png)

**Comment by lguychard** [comment]
I cannot reproduce this using the provided scenario. That being said, I'd really like to understand what is going on here.

> The extension did not make ANY network requests to Sourcegraph.com

@slimsag all browser extension network requests are made from the background page, so you wouldn't see any in the devtools for the `github.com/..../session.go` tabs.

To inspect browser extension network requests, on Firefox:
1. Navigate to `about:addons`
1. Click the cog in the right-hand corner and select **Debug add-ons**
1. Click the **Inspect** button for the Sourcegraph add-on.
1. A new tab opens with a devtools instance inspecting the add-on's background page.
1. Reload your GitHub tab, and inspect network requests in the background page's devtools.

Do you think Andrew would be willing to help us with this?

**Comment by Andoryuuta** [comment]
Sure. I've attached the HAR file from a fresh reload of the tab in a private window. No other requests got sent when trying to hover over or click symbols.

[120803a8-4da2-49e1-ad17-05c793764ea1_Archive [20-01-13 18-00-49].har.txt](https://github.com/sourcegraph/sourcegraph/files/4056399/120803a8-4da2-49e1-ad17-05c793764ea1_Archive.20-01-13.18-00-49.har.txt)

Console:
![console](https://user-images.githubusercontent.com/8594162/72299551-2f1cc980-362f-11ea-9146-2d22dcc683bb.png)

**Comment by marbar3778** [comment]
I'm not sure if my issue has overlap here. I am unable to get sourcegraph installed. 
![Screen Shot 2020-06-18 at 10 19 09 AM](https://user-images.githubusercontent.com/24299864/84996201-3d769080-b14d-11ea-8e92-1a04b137c688.png)
![Screen Shot 2020-06-18 at 10 19 18 AM](https://user-images.githubusercontent.com/24299864/84996209-3f405400-b14d-11ea-8fe5-9ecfbc4c605a.png)

I am always getting a connection issue, yet when I try to install a different extension it works fine. Im not sure If I'm doing something wrong?

**Comment by Joelkw** [comment]
Firefox should be long fixed – grab the [latest here](https://docs.sourcegraph.com/integration/browser_extension)
