### ISSUE TITLE
Error parsing regexp: space characters

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#7601]
- **Sourcegraph version:** Current

Reported by https://app.hubspot.com/contacts/2762526/company/557475882

Regexps with space characters fail on Sourcegraph — e.g.:

* Escaped spaces (`\ `): https://sourcegraph.com/search?q=repo:%5Egithub.com/sourcegraph/sourcegraph%24+%28%5C+.%29&patternType=regexp
* Spaces in square brackets (`[ ]`): https://sourcegraph.com/search?q=repo:%5Egithub.com/sourcegraph/sourcegraph%24+%5Ba-z+%5D%2B&patternType=regexp

Both of these patterns work on various RE2 testers, e.g.https://regex-golang.appspot.com/assets/html/index.html

A workaround is to use `\040` in place of spaces (or `\s` of course, though it includes tabs/newlines/etc.)

**Comment by slimsag** [comment]
> `\040`

Ah good find, I only thought of `\s`

Merging this issue with #7604 which I filed before seeing this
