### ISSUE TITLE
LSIF OpenAPI swagger document parser error caused by duplicated paths

### ISSUE THREAD

**Issue by alex-yh99** [sourcegraph/sourcegraph#7603]
- **Sourcegraph version:** 
- **Platform information:** 

#### Steps to reproduce:

Run swagger server locally via docker as instructed by [LSIF api.md](https://github.com/sourcegraph/sourcegraph/blob/master/lsif/docs/api.md) 

#### Expected behavior:

Swagger API document can be viewed

#### Actual behavior:

Unable to render [api.yaml](https://github.com/sourcegraph/sourcegraph/blame/master/lsif/docs/api.yaml) document due to duplicated key  @efritz

**Comment by efritz** [comment]
Should be fixed in https://github.com/sourcegraph/sourcegraph/pull/7526.
