### ISSUE TITLE
Errors about unlinked accounts are not helpful 

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#7606]
A customer [reported]() an error when searching from what I believe to be caused due to unlinked builtin-auth and github-auth accounts:

> Error in GraphQL response: Resource protected by organization SAML enforcement. You must grant your personal token access to this organization.

This is not a helpful error message, we should link to documentation here and explain potential causes.

**Comment by slimsag** [comment]
It seems I was likely wrong about the source of this issue and the fix may be different, making this issue moot. https://sourcegraph.atlassian.net/jira/servicedesk/projects/SG/queues/custom/2/SG-6

**Comment by tsenart** [comment]
If this issue is moot, can we close it? :dagger:

**Comment by slimsag** [comment]
The source of the issue was indeed different (see the JIRA ticket) quoting the relevant part of the response from Beyang:

> hypothesis is that the personal access token Sourcegraph uses to clone repositories (set in the GitHub external service configuration, token field) is not SAML-authorized [...for your GitHub Enterprise Cloud organization which has SAML SSO enforcement turned on]. GitHub provides documentation for authorizing the token here: https://help.github.com/en/github/authenticating-to-github/authorizing-a-personal-access-token-for-use-with-saml-single-sign-on.

This error and what to do needs to be added to our documentation. I will own.
