### ISSUE TITLE
Make it more obvious that admins have to set the corsOrigin

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#761]
This would have prevented https://github.com/sourcegraph/browser-extensions/issues/237 and similar issues.

**Comment by lguychard** [comment]
#1954 allows to successfully bypass `corsOrigin` restrictions on Chrome and FF.

**Comment by sqs** [comment]
@lguychard Can we completely remove corsOrigin now or is it still needed?

**Comment by lguychard** [comment]
I think it may still be needed if the code host is Phabricator (since in that case, all requests will be made from the in-page script, and not the browser extension). @ijsnow can you confirm?
