### ISSUE TITLE
Phabricator integration not working

### ISSUE THREAD

**Issue by henryaj** [sourcegraph/sourcegraph#7617]
- **Sourcegraph version:** 3.11
- **Platform information:** deployed on k8s per https://github.com/sourcegraph/deploy-sourcegraph/

#### Steps to reproduce:

1. connect Phabricator as an external service 

#### Expected behavior:

Phabricator repos appear in Site admin > Repositories

#### Actual behavior:

no repositories appear

This integration used to work for us; I suspect a change to the Phab API has broken it. The sourcegraph logs look healthy and I can see it connecting in the Conduit logs, but no repos ever appear.

I've tried configuring the connection both as `{"url": "...", "token": "..."}` and `{"url": "...", "token": "...", "repos": [...]}`.

**Comment by slimsag** [comment]
Hi @henryaj -- just want to confirm you and Mike did get my response about this in the support email thread ("[Support] Re: Fwd: Phabricator integration not working")?

We'll correct our documentation here soon (#7704) to make this much more clear, but it looks like you just need to set up the additional external service to mirror the repos onto Sourcegraph as I mentioned in the email. Please let me know if this didn't help.

**Comment by henryaj** [comment]
Thanks, all received

**Comment by henryaj** [comment]
(Mike wasn't cc'ed so didn't receive it; have forwarded it to him now)
