### ISSUE TITLE
Ensure defined Grafana alerts do not disappear without data

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#7623]
The "Total defined alerts" are sometimes not showing up when there is no data, need to add empty vectors so these are always present.

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.12 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by slimsag** [comment]
I think this may be fixed, just need to confirm.

**Comment by slimsag** [comment]
Closing in favor of https://github.com/sourcegraph/sourcegraph/issues/11571 which I suspect is the same issue and has more reproducible details.
