### ISSUE TITLE
Grafana: Frontend dashboard: "Search responses by status" query is not aggregated

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#7627]
Shows multiple/duplicate success, alert, etc. categories

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.12 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
