### ISSUE TITLE
Grafana: gitserver dashboard: echo duration panel needs time unit

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#7628]
![image](https://user-images.githubusercontent.com/3173176/72105644-31a7b800-32eb-11ea-8a0e-05b57b4d24c6.png)

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.12 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
