### ISSUE TITLE
Ref glob search perf followups

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#7642]
https://github.com/sourcegraph/sourcegraph/pull/7641#pullrequestreview-340956998

**Comment by tsenart** [comment]
@sqs: We're doing 3.13 triage for Core Services. Do you think you'd have time to pick this up soon or should we take into account ourselves? Thanks.

**Comment by sqs** [comment]
It would be great if you guys could pick this up. I’ll try to get to it sooner myself, but I can’t promise anything.

**Comment by keegancsmith** [comment]
Deprioritizing for 3.13, will revisit for planning in 3.14. The work on my plate for 3.13 has expanded and it looks unlikely I will finish this before then.

**Comment by tsenart** [comment]
@keegancsmith: Do you mind keeping your assignment until the next planning cycle so we can visualise the changes that occurred during the iteration?

**Comment by unknwon** [comment]
Removing "team/cloud" since this can be solely accomplished by the search team.

**Comment by stefanhengl** [comment]
Triaging. Closing this after verifying that search limits concurrency.
