### ISSUE TITLE
 Freeze blowser tab When I change branch

### ISSUE THREAD

**Issue by mntky** [sourcegraph/sourcegraph#7645]
**Platform information**
Sourcegraph version: 3.8.0
OS: Debian9
web browser: firefox,chrome
Docker version: 19.03.2

#### Steps to reproduce:

1. Open code page.
2. Click function and click [Find references].
3. Change branch.

#### Expected behavior:
The branch switches and the reference is displayed.

#### Actual behavior:
Browser tab freezes

**Comment by slimsag** [comment]
Hello, could you let us know which repository this is happening on or how many branches this repository has? This could help us in debugging why this is happening.

Thanks!

**Comment by mntky** [comment]
This is happening in kubernetes repository.
There are about 40 branches.
