### ISSUE TITLE
a8n/web: Allow users to specify branch name before Campaign creation and provide great default value

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#7646]
In order to make "updating Campaigns" work I had to change our current code that turns the Campaign's current title into a human-readable branch name. Otherwise, a title update would produce a new branch name.

The obvious solution to this is that we persist the branch name on Campaign creation and don't change it when we update a campaign.

But since @sqs mentioned in his [a8n experience notes](https://docs.google.com/document/u/1/d/11uudJpg1qGdXwLOS-HATs3J8z3qph9NUKwry-zFzeB8/edit?folder=0AHlEU2lM-l9gUk9PVA) that, as a user, he'd like to specify a custom branch (or at least see what the branch name will be), we came up with with [a solution for both problems in Slack]:

* When creating a campaign users can specify the branch name
* We provide a suggested default value that's derived from currently typed in Campaign's title
* We add a label to let the user know that this cannot be changed after creating the campaign
* In draft mode, the user can still change the branch name as long as not a single changeset has been published. If only a single changeset has been published, it's not editable anymore.

From a technical perspective that means

* We extend `CreateCampaignInput` with `branchName: String!`
* We persist the branch name on the Campaign and use it when creating changesets
* We keep the branch name stable across Campaign updates
* When updating a campaign, we validate that updating the branch name is only allowed when the Campaign itself is in draft mode and not a single Changeset has been published yet
* We have an input field in the frontend to specify the branch name
* The input field is prepopulated with a branch name that's derived from the campaign title, using a slugify/sanitization technique similar to [the one we used in the backend](https://github.com/sourcegraph/sourcegraph/blob/1120af90b576be6f983e4c3bab3b908943472f01/internal/vcs/git/refs.go#L22-L44)
* Since a Campaign needs a title, we only need to prepopulate the field when a title has been typed in, otherwise the form would be invalid anyway

**Comment by eseliger** [comment]
Did you think about how to handle the edge-case of a branch name being already in use yet? 🤔
Ie. I enter branchName: 'a8n/update-deps'
But there is a repository that has such a branch already.

Options off my head:
- Fail for that single repo (not very desirable, as the job can not be fixed with a retry and after any other is published, the branch name is fixed)
- Have some mechanism to check if the branch name is available across all matching repositories (also somewhat hard, especially when it comes to updating campaigns which extend the scope)
- Fallback to `${name}-${retryNo}`

**Comment by mrnugget** [comment]
Good point! I think your option 3 is the best one and what I would expect as a user.

But it also changes the original scope of this ticket, at least on backend side, in that we now also need to 
1. check whether branch already exists
2. make sure to fall back
3. persist fallback branch name per ChangesetJob, so that on retry/update we use the same fallback name again

**Comment by sqs** [comment]
Added one more requirement to the issue (to add a new `src campaigns create -branch` flag to the CLI)

**Comment by mrnugget** [comment]
Now we do have a `src campaigns create` command and @kzh already started working on adding `-branch` to it: https://github.com/sourcegraph/src-cli/pull/96

**Comment by mrnugget** [comment]
Just for the record because @kzh and I ran into this: the branch name is only required for non-manual campaigns (those that have a campaign plan).

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.13 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by mrnugget** [comment]
The frontend portion of this has also been implemented by @eseliger
