### ISSUE TITLE
Move background workers out of frontend

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#7647]
Background worker for ChangesetJobs are launched in the frontend.

They should instead be launched in another process, maybe `repo_updater`

Moving them to `repo_updater` currently leads to a panic in our SQL layer so needs further investigation.

**Comment by ryanslade** [comment]
Why did you close this?

**Comment by mrnugget** [comment]
Reopened it because I misread this. I thought it was about launching Go routines in the resolver vs. somewhere else.

**Comment by ryanslade** [comment]
Note, this is required so that all code host requests are made from repo-updater which allows us to perform all our rate limiting there.
