### ISSUE TITLE
Safari extension

### ISSUE THREAD

**Issue by caarlos0** [sourcegraph/sourcegraph#766]
Hi everyone! 

Thanks for sourcegraph, it is **awesome**!

Any plans to support Safari? It would be even more awesome 🚀 

Cheers!

**Comment by aofei** [comment]
Update: https://developer.apple.com/news/?id=kuswih5l

**Comment by felixfbecker** [comment]
@marekweb @Joelkw since we have the Safari extension released now, it sounds like we can close this. @marekweb could you make sure to file any follow-up issues for remaining work (e.g. automatic release in CI, description updates, ...?)
