### ISSUE TITLE
Enable HTTP Strict Transport Security (HSTS) on sourcegraph.com (and all subdomains)

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#7660]
https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security

Currently we redirect from http to https but we don't set the Strict-Transport-Security header.

**Comment by nicksnyder** [comment]
I was poking around in Cloudflare and it seems like this is as easy as clicking a button. This is a one-way door, so I wanted to get confirmation from a few people that this is the right thing to do.

<img width="1049" alt="Screen Shot 2020-01-13 at 3 33 07 PM" src="https://user-images.githubusercontent.com/754768/72300914-02aa8280-361a-11ea-9bb1-93163d72ad1d.png">


cc @keegancsmith @slimsag @beyang

**Comment by nicksnyder** [comment]
Also, I suppose that clicking the button in the UI is the wrong thing to do and we should make the change via terraform: https://github.com/sourcegraph/infrastructure/tree/master/dns

**Comment by unknwon** [comment]
Despite PR is not yet merged, but changes have been approved and made to the Cloudflare (also eye checked).

**Comment by tsenart** [comment]
@unknwon: Since you already touched our Terraform manifests related to these configurations, could you pick this other one up too? https://github.com/sourcegraph/security-issues/issues/54

Should be a tiny change now.

**Comment by unknwon** [comment]
SGTM.
