### ISSUE TITLE
Weird highlighting on multiple go to definition results with basic code intel

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#7668]
https://sourcegraph.com/github.com/libgit2/libgit2sharp@7cdddd267ca4f2a555acf6cfb98b588a72f33d67/-/blob/LibGit2Sharp/Diff.cs#L202:140&tab=def

![image](https://user-images.githubusercontent.com/10532611/72221708-5efb9c80-355d-11ea-92f6-e7dd387b7459.png)

**Comment by efritz** [comment]
<img width="793" alt="Screen Shot 2020-01-13 at 9 10 28 AM" src="https://user-images.githubusercontent.com/103087/72266728-91041180-35e4-11ea-8f42-3cf8b384569a.png">

The first weird-looking highlighted line happens to be highlighting exactly what is coming back from the search endpoint:

```json
{
  "name": "IDiffResult",
  "containerName": "LibGit2Sharp.Diff",
  "url": "/github.com/libgit2/libgit2sharp@7cdddd267ca4f2a555acf6cfb98b588a72f33d67/-/blob/LibGit2Sharp/Diff.cs#L172:1-172:12",
  "kind": "CLASS",
  "location": {
    "resource": {
      "path": "LibGit2Sharp/Diff.cs"
    },
    "range": {
      "start": {
        "line": 171,
        "character": 0
      },
      "end": {
        "line": 171,
        "character": 11
      }
    }
  }
}
```

**Comment by efritz** [comment]
Should be fixed by https://github.com/sourcegraph/sourcegraph/pull/10231.
