### ISSUE TITLE
case: filter breaks searches with repo: filter if no other term is provided

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#7671]
- **Sourcegraph version:** Sourcegraph.com"

#### Steps to reproduce:

1. search for `repo:sourcegraph case:no` or any query with a `repo:` filter and `case:` filter and nothing else. notice that no results appear

#### Expected behavior:

I would expect the search to display the repository results. `case:no` is the default behavior, so it should show repos as if no `case:` was provided, and `case:yes` should show only repos that match the case provided to the filter.

#### Actual behavior:

No results

**Comment by attfarhan** [comment]
Ran into this while adding the case sensitivity toggle.

**Comment by rvantonder** [comment]
This seems like something that should be fixed ASAP. Don't know if it can go into 3.12. I can investigate ~tomorrow.

**Comment by tsenart** [comment]
@keegancsmith volunteered to fix this in time for the 3.12 release.
