### ISSUE TITLE
RFC 40: Grant permissions on user creation and email verification

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#7679]
This issue tracks implementation of granting pending permissions for [RFC 40: Explicit Repository Permissions Model](https://docs.google.com/document/d/167WV_rhBg3oj0yw9fHwUMlB-8BR3ktk2FSsKiUQo55Y/edit).

- [x] Grant on user creation when `bindID` is `username` in site config
- [x] Grant on email verification when `bindID` is `email` in site config

**Comment by beyang** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.12 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
