### ISSUE TITLE
a8n/web: Display commit CI status

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#7680]
This depends on https://github.com/sourcegraph/sourcegraph/issues/7093 and is the frontend portion of the work.

**Comment by christinaforney** [comment]
Feedback/suggestion from a customer (https://app.hubspot.com/contacts/2762526/contact/17877751): 
>  a suggestion I have would be to have a similar indication above the list of changesets that indicates the overall status (i.e. if any changeset has a failing CI status, show the failure indicator). This would allow us to quickly see whether any action is required on our part

**Comment by mrnugget** [comment]
@eseliger Assigning this to you, because you've been working on this. If this ticket is a duplicate/outdated: feel free to close.

**Comment by eseliger** [comment]
was done before
