### ISSUE TITLE
a8n/web: Implement UI to allow stacking of diffs

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#7682]
This ticket represents the frontend work of [RFC 92 WIP: Add ability to stack diffs to Automation](https://docs.google.com/document/d/1m6WH47vl-DFynfEdjpGez2pj7bTO3MRFAPpDgEDlvFI/edit#heading=h.kfdzelmr4v06)

**Comment by sqs** [comment]
Deprioritizing because `src` CLI work (in https://github.com/sourcegraph/sourcegraph/issues/7850) makes it possible for customers to solve the biggest problem (make a change and then reformat code) without the complexity of full stacked diffs.

**Comment by mrnugget** [comment]
Closing this because it's outdated and not applicable to the current architecture of Campaigns anymore.
