### ISSUE TITLE
a8n/web: Allow updating the CampaignPlan and other fields of a Campaign

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#7683]
After https://github.com/sourcegraph/sourcegraph/pull/7328 we need to implement the UI that allows a user to update a Campaign with a new CampaignPlan. See the discussion in #7328 for more details.

- [ ] Add a section to the docs at https://docs.sourcegraph.com/user/automation about updating a campaign. Mention all of the kinds of operations that can occur due to an update (start from the bullet list under Proposal in [RFC 95](https://docs.google.com/document/d/1_0fOwbmIov3utmpFa2cs_3qSM3HGO3mNLTUVB8sZxIg/edit#heading=h.umigb8il1vw3) and ask @mrnugget to make sure any other edge cases he considered are mentioned if users would care).

**Comment by sqs** [comment]
This UI is going to be quite nuanced/tricky. Keep in mind it needs to support updating the campaign plan as well as title and description (but not branch name, we will not support changing that after creation, and that is OK). @eseliger @felixfbecker would you like help from me and @christinaforney on proposing the design/UX, or do you want to do so yourselves?

**Comment by eseliger** [comment]
If you got good ideas, always super welcome! Off the top of my head I would think of some UI like 
```
N Added changesets
<List of changesets and it's diff>
---
M Updated changesets
<List of changesets and it's diff>
---
P Deleted changesets
<List of changesets and it's diff>
```
Which is somewhat rudimentary but I feel like could be rather efficient to skim through. Any improvements super welcome though!

**Comment by felixfbecker** [comment]
I would make everything editable with the same edit button, but only update the things that actually changed.
For changesets and the diff, I'd avoid the UI complexity of "diffing the diff". I'd show the new state, but we can flag newly added changesets with a different color or badge, and cross/fade out deleted ones.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.13 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
