### ISSUE TITLE
a8n/web: Extended campaign list view

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#7684]
This depends, in parts, on https://github.com/sourcegraph/sourcegraph/issues/7553 and represents the UI portion of extending the campaign list view. See https://github.com/sourcegraph/sourcegraph/issues/7553#issuecomment-577005761 for what needs to be implemented in the UI.

Note that [RFC 20](https://docs.google.com/document/d/1UY9B_kLlwRtYj-fuv7XZS1-Mu99Czx9Ojm7sgEmoQIA/edit) originally specified more work ("An overall campaign list shows all active campaigns (globally, and for a specific namespace) and some indication of their progress"), but that is not necessary yet. Follow the comment linked above.

**Comment by ryanslade** [comment]
#7553 is done so I think we're unblocked to do the frontend work

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.13 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by mrnugget** [comment]
@eseliger If I understood the tracking issue (https://github.com/sourcegraph/sourcegraph/issues/7726) correctly, this ticket was not planned for web in 3.13, right? Can we remove the milestone?

**Comment by eseliger** [comment]
Hmm let's revisit today evening, I'm trying to look into it later
