### ISSUE TITLE
a8n/web: Show set of participant users involved in the campaign in campaign detail view

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#7685]
This depends on https://github.com/sourcegraph/sourcegraph/issues/7552

From [RFC 20](https://docs.google.com/document/d/1UY9B_kLlwRtYj-fuv7XZS1-Mu99Czx9Ojm7sgEmoQIA/edit)

> This should appear on the campaign detail page

**Comment by sqs** [comment]
Deprioritized (moving from 3.13 to backlog) because none of the private beta customers have told us this is necessary to start using campaigns.

**Comment by chrispine** [comment]
Closing because I closed the back-end issue
