### ISSUE TITLE
a8n/web: Show labels of all changesets in campaign

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#7686]
This is from [RFC 20](https://docs.google.com/document/d/1UY9B_kLlwRtYj-fuv7XZS1-Mu99Czx9Ojm7sgEmoQIA/edit)

After we've implemented https://github.com/sourcegraph/sourcegraph/issues/7549 we need to display the labels in the frontend.

**Comment by eseliger** [comment]
Closed in #8115
