### ISSUE TITLE
Improve completion items icons for MonacoQueryInput

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#7694]
We currently have the stock Monaco icons:

![image](https://user-images.githubusercontent.com/1741180/72289559-5f596d80-3619-11ea-8c93-8ec4658df7e7.png)
![image](https://user-images.githubusercontent.com/1741180/72289549-5a94b980-3619-11ea-8090-68179ad58340.png)

We should try to have custom icons like in the existing query input:

![image](https://user-images.githubusercontent.com/1741180/72289623-82841d00-3619-11ea-8afc-cd4eba478c49.png)
![image](https://user-images.githubusercontent.com/1741180/72289625-844de080-3619-11ea-9831-087b1542336e.png)

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.13 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
