### ISSUE TITLE
Some dynamic suggestion types are missing from MonacoQueryInput

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#7695]
Currently, only file and repository dynamic suggestions are shown. All suggestion types should be shown.

![image](https://user-images.githubusercontent.com/1741180/72289800-dbec4c00-3619-11ea-915f-ba9884d23942.png)
![image](https://user-images.githubusercontent.com/1741180/72289805-ddb60f80-3619-11ea-8734-4c8849931e8c.png)

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.13 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
