### ISSUE TITLE
MonacoQueryInput: improper warnings for lang: filter

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#7696]
`lang:ts` should not trigger a warning, but it does:

![image](https://user-images.githubusercontent.com/1741180/72289883-0b02bd80-361a-11ea-9cb8-c4a7da7e54bc.png)

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.13 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
