### ISSUE TITLE
MonacoQueryInput theme is broken on pages that have another Monaco editor

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#7697]
![image](https://user-images.githubusercontent.com/1741180/72289936-2b327c80-361a-11ea-8632-7c3c018ace94.png)

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.13 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.14 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
