### ISSUE TITLE
Ideas for simplifying the interface with extensions-client-common/sourcegraph-extension-api

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#770]
These are rough notes.

Maybe we can:

- Unify the two `Controller`s (one from e-c-c, one from s-e-a) into one `Controller`
- Have e-c-c pipe the `context`, `configurationCascade`, and `viewerConfiguredExtensions` from one controller to the other
- Require that an `Observable<TextDocumentItem[]>` be passed in when creating the `Controller`
- Drop the concept of multiple levels of settings from `Controller`
- Drop the type parameters `ConfigurationSubject` and `Settings` from the `Controller`
- `Settings` will be hard-coded into the `Controller`

**Comment by felixfbecker** [comment]
Is this still relevant?

**Comment by chrismwendt** [comment]
The internals have changed so much that most of these points do not apply anymore. Closing since we're not actively working on this.
