### ISSUE TITLE
Prevent upgrading more than one minor version at a time

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#7702]
I have seen two customers in the past day incorrectly upgrade more than two minor versions at one time, leading to migration failures taking down their instance.

This is a failure on our part, because nobody should have to be realizing this on their own (or through our (missing!) documentation #7699 ): If you upgrade Sourcegraph more than two minor versions at once and we require you don't, you should be getting an obvious error explaining you need to do it in increments.

**Comment by keegancsmith** [comment]
This sounds like an easy thing to fix with a high impact. cc @sourcegraph/core-services

**Comment by mrnugget** [comment]
> This sounds like an easy thing to fix with a high impact.

How do you imagine we can check this? Do we already record the current version somewhere and could abort on boot of the diff is too big?

If we don't have the current version somewhere, I'm wondering where should we record it. We could use a file in `~/.sourcegraph` or even the database, but I think the latter might be available too late, since we probably want the check to happen ASAP when the instance boots up. The other question is: when do we record the _current_ version? Or, when are we confident that we have fully and successfully booted up and updated?

**Comment by slimsag** [comment]
> If we don't have the current version somewhere, I'm wondering where should we record it. We could use a file in ~/.sourcegraph or even the database, but I think the latter might be available too late, since we probably want the check to happen ASAP when the instance boots up.

We don't currently have the version anywhere. I imagine there are likely other cases where we would want to know:

- the current version of sourcegraph (and date that version was released on)
- version of sourcegraph the instance was originally created with (and date that version was released on)
- date the instance was created at

A file might be tricky because there are e.g. multiple frontend instances in cluster deployments. The DB would work fine, but we'd have to access this information before the migrations tried to run.

**Comment by slimsag** [comment]
Hit the wrong button before I finished typing my comment :)

> when are we confident that we have fully and successfully booted up and updated?

After the DB migrations have completed successfully, it seems reasonable to consider that point successfully booted up and updated OK.

**Comment by mrnugget** [comment]
Thanks for the answers, @slimsag!

> After the DB migrations have completed successfully, it seems reasonable to consider that point successfully booted up and updated OK.

Then we need to coordinate between `frontend` and `repo-updater`, since they can both potentially run migrations.

In other words, I think we need a way for our services to report "Fully booted up and healthy" to the frontend, which then writes the current version.

**Comment by nicksnyder** [comment]
Would moving the responsibility of running migrations out of the frontend and into a singleton service (like repo updater) help?

**Comment by keegancsmith** [comment]
> Then we need to coordinate between frontend and repo-updater, since they can both potentially run migrations.

can we avoid that in repo-updater? What is an example migration that isn't idempotent? Making migrations have more moving parts introduce more risk, I'd prefer to not do that if we can.

> Would moving the responsibility of running migrations out of the frontend and into a singleton service (like repo updater) help?

frontend is currently the only service with postgres auth details configured in our cluster setups. Additionally every other service waits for frontend for configuration needs (configuration includes how those services then connect to postgres). Given that every other service waits for frontend to start (for config), its quite nice that it is responsible for DB migrations.

**Comment by tsenart** [comment]
> can we avoid that in repo-updater? What is an example migration that isn't idempotent? Making migrations have more moving parts introduce more risk, I'd prefer to not do that if we can.

We don't actually run migrations from repo-updater. Only the frontend runs db migrations.

**Comment by mrnugget** [comment]
> We don't actually run migrations from repo-updater. Only the frontend runs db migrations.

Ah, not anymore, right? We did run migrations written in Go at some point. But I now see how that was/is slightly different in regards to the question of "did the system fully boot up?"

**Comment by tsenart** [comment]
> Ah, not anymore, right? We did run migrations written in Go at some point.

Yes, but application level migrations, never database schema migrations. We do neither of those at this point.

**Comment by nicksnyder** [comment]
Update: we only want to support consecutive versions: https://github.com/sourcegraph/sourcegraph/pull/7886

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.13 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
