### ISSUE TITLE
Faulty snippet detection on GitHub issues

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#771]
- Visit https://github.com/gorilla/mux/issues/381
- Notice hovers don't work on the first snippet

It looks like [this code](https://sourcegraph.sgdev.org/github.com/sourcegraph/browser-extensions@71791ff24f6f87ff86b85008ea3405c0e49843ca/-/blob/src/libs/github/file_info.ts#L92) assumes that the first `<a>` tag within a comment that links to a URL that can be parsed by `getGitHubState(anchor.href)` is a snippet, but in that issue it's actually a link to a commit.

![image](https://user-images.githubusercontent.com/1387653/46129307-19418600-c1eb-11e8-9258-9b164faf05d7.png)

![image](https://user-images.githubusercontent.com/1387653/46129438-8ce39300-c1eb-11e8-968b-ccd1d02af9be.png)

One solution is to not stop after the first is found, and to tighten the URL regex.

**Comment by felixfbecker** [comment]
Needs to be reinvestigated after fixing #3105
