### ISSUE TITLE
Send pings about Automation usage to Sourcegraph

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#7711]
As discussed in yesterday's @sourcegraph/core-services sync.

In order to measure our progress towards our OKRs this quarter we need to take measurements. Since one key results is about how many customers use Automation and how many Campaigns they've run, what we need to measure is exactly that.

For that we can use pings and report back number of campaigns run by customer.

**Comment by tsenart** [comment]
This is where you need to add this information: https://github.com/sourcegraph/sourcegraph/blob/f348ef5c7ea63f5f189d2369f813861de5243aef/cmd/frontend/internal/app/pkg/updatecheck/client.go#L82

**Comment by dadlerj** [comment]
Happy to consult (and review) any code that affects pings. Ping results are stored in BigQuery, and @ebrodymoore and I can help with that portion.

**Comment by dadlerj** [comment]
@kzh please let me know before you start working on this so we can discuss how this will be implemented.

**Comment by efritz** [comment]
I'm also working on a similar effort for codeintel, so please sync with me before hand as well (I may have already done some of the work you'll need).
