### ISSUE TITLE
a8n/web: Campaign detail view scrolls to top when diff/changesets tab is changed

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#7714]
On the Campaign detail view, when selecting either "DIFF" or "CHANGESETS" the whole view scrolls to the top, which is really frustrating:

![jump_to_top](https://user-images.githubusercontent.com/1185253/72329897-de03e880-36b5-11ea-8a37-b5806de6ee2c.gif)

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.14 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
