### ISSUE TITLE
"Grant" sometimes requests an empty set of permissions

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#772]
![image](https://user-images.githubusercontent.com/1387653/46048934-b4016e00-c0e0-11e8-8227-19b738c08791.png)

The browser extension might be able to check if it already has the permissions, and decide not to show the button at all in that case.

**Comment by christinaforney** [comment]
@chrismwendt - we made some updates to how permissions are granted (I think). Can you confirm if this is still relevant or not?

**Comment by chrismwendt** [comment]
I haven't seen this behavior in a long time, but I'll reopen and add more context if I do.
