### ISSUE TITLE
a8n Spike: Add ability to "stack diffs" (RFC 92)

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#7721]
This is a spike for the technical implementation of [RFC 92](https://docs.google.com/document/d/1m6WH47vl-DFynfEdjpGez2pj7bTO3MRFAPpDgEDlvFI/edit#heading=h.kfdzelmr4v06).

The expected result is that we know

1.) what the technical implementation would look like in detail
2.) how long it would roughly take to implement
3.) possible tradeoffs

and can add that information to the RFC.

**Comment by sqs** [comment]
Deprioritizing because `src` CLI work (in https://github.com/sourcegraph/sourcegraph/issues/7850) makes it possible for customers to solve the biggest problem (make a change and then reformat code) without the complexity of full stacked diffs.

**Comment by mrnugget** [comment]
Closing this for now, since it's only a "placeholder" for a spike and doesn't contain actionable instructions.
