### ISSUE TITLE
Which feature flag to turn on sourcegraph for self hosted GitLab?

### ISSUE THREAD

**Issue by songz** [sourcegraph/sourcegraph#7740]
#### Question description

Really excited about this blog post:
https://about.sourcegraph.com/blog/gitlab-integrates-sourcegraph-code-navigation-and-code-intelligence

However, I don't see a way to enable sourcegraph on my gitLab installation (v12.6). I'm guessing it has to do with the feature flag mentioned in this sentence:

> Once internal testing is complete, the feature flag will be lifted and all users can choose to opt-in to this feature on GitLab.com.

Could I get some guidance on how to turn on this feature flag so I can use some of sourcegraph's features? I have my own sourcegraph installation working and the UI is hosted here:

https://sourcegraph.c0d3.com

**Comment by songz** [comment]
Blog post that details the setup is here: https://docs.gitlab.com/ee/integration/sourcegraph.html

Start gitlab console, then enable flag (For my self hosted server I had to execute these as root)
```
gitlab-rails console
Feature.enable(:sourcegraph)
```

**Comment by christinaforney** [comment]
Glad you were able to get it running! We're hoping to work with GitLab to remove that feature flag soon :)
