### ISSUE TITLE
Add regression tests for permissions APIs

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#7747]
This issue tracks the progress of regression tests for [RFC 40: Explicit Repository Permissions Model](https://docs.google.com/document/d/167WV_rhBg3oj0yw9fHwUMlB-8BR3ktk2FSsKiUQo55Y/edit).

I created this issue because I found it hard to add scenarios in our regressions test suite without implementing all necessary pieces in RFC 40.

From https://github.com/sourcegraph/sourcegraph/pull/6427#issuecomment-557392099:
* [ ] Add a regression test for this case, please: [#6427 (comment)](https://github.com/sourcegraph/sourcegraph/pull/6427#discussion_r350446261)
* [ ] GraphQL API `setUserEmailVerified` (true, false)
* [ ] GraphQL API `createUser`
* [ ] Set permissions for existing user, grant by username (sign up), grant by verified email (verify email link)
* [ ] Should hit the API [like the existing authz integration test](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@61bd03420e46686983432e60889663cffe4368af/-/blob/web/src/regression/external-services.test.ts#L277-350) and do some sanity checks that permissions are enforced end-to-end.
* [ ] When `permissions.userMapping` is enabled while another authz provider (e.g., GitHub authz) is enabled, repository access attempts return a status code 500 *if* the repository exists, but a 404 if the repository doesn't exist. In both cases, the status code should be consistent. Otherwise, this reveals the existence of a repository to an unauthorized user. (https://sourcegraph.slack.com/archives/CHPC7UX16/p1579414175006000)

**Comment by unknwon** [comment]
I put this issue on hold because of big migration in #7872, will work on #7748 first instead.

**Comment by tsenart** [comment]
Is this still relevant @unknwon?

**Comment by unknwon** [comment]
It is no longer important given no known prospect customer is going to use the feature in foreseeable future. Besides, we have unit tests for all of the bullet points.

Closing it for now.
