### ISSUE TITLE
What does "Limited Functionality" mean when connecting the browser extension to Sourcegraph.com?

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#775]
What functionality does this limit?

I'd like to propose adding a help icon and text here to explain.

https://github.com/sourcegraph/browser-extensions/blob/becfba3ad64adbac71402de6fc10774887c11002/src/shared/components/options/ConnectionCard.tsx#L153

**Comment by ijsnow** [comment]
No longer an issue with new options menu.
