### ISSUE TITLE
a8n: Empty campaign title caused infinite loop of job being processed

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#7759]
- **Sourcegraph version:** master

#### Steps to reproduce:

1. Create a campaign that has an empty title (not possible anymore after #7757, need to remove the db constraint to reproduce, it's still an error swallowed somewhere, so still worth fixing it)
2. See console logs, find gitserver repeatedly creating the commits for the changeset, then frontend logs `frontend | ERROR Running campaign job, err: creating changeset: error in GraphQL response: Title can't be blank`

#### Expected behavior:
It's created or the creation fails, and the error is logged in the changeset_jobs table

#### Actual behavior:
It's not failing, not setting `started_at`, nor `error`, causing infinite retries of this job

**Comment by mrnugget** [comment]
Ran into this myself just now. The error message is misleading, it should be `"Running changeset job"`, but I do think that the bug is not exclusive to changeset jobs.
