### ISSUE TITLE
Remove published_at fields from Campaign and ChangesetJob

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#7782]
published_at is used to indicate that the campaign is no longer in draft mode but the only effect it has is to enable changeset jobs to begin being processed.

We've since added individual published_at columns to each changeset job so that they can be published individually. This make published_at on the campaign redundant.

**Comment by mrnugget** [comment]
Just synced with @ryanslade on this. We realized that we don't need _any_ `published_at` field on _any_ table if we hold the invariant that **every created `changeset_job` will be run**. To keep the GraphQL API stable (`campaign.publishedAt()`), we simply use the `max(created_at)` for changeset jobs (watch out: we can only return a value of `len(changeset_jobs) == len(campaign_jobs)`)
