### ISSUE TITLE
"permissions are stale and being updated" error doesn't tell users to refresh

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#7787]
This is a suggestion from https://sourcegraph.atlassian.net/jira/servicedesk/projects/SG/queues/custom/1/SG-18 but I will consider it a UX bug.

When a new users signs up, they can receive this warning, and a customer reported that most of the time refreshing the page "fixes the issue" (it is temporary) but our error message doesn't inform you to refresh the page.

**Comment by tsenart** [comment]
@slimsag: Going forward, please always assign `team/core-services` issues to me for triaging.

**Comment by tsenart** [comment]
@unknwon: I believe you fixed this in #8356. Close this issue if so.
