### ISSUE TITLE
Visually distinguish archived repos in search results

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#7788]
From a customer: https://app.hubspot.com/contacts/2762526/company/430823645

>I've been doing some changes and used SG to look for where to do them. However, I got lead down a rabbithole a little because some of the results I visited were inside archived repositories.
>
>Would it be possible to differentiate how those hits get shown up, visually, please?
>
>For example, placing them later in the search results, maybe hidden unless shown (or a config to show-always), an icon...?
>
>Best regards

I think a different icon would be great here (similar to a fork icon)

**Comment by lguychard** [comment]
Related: #7004

**Comment by camdencheek** [comment]
Closing as done since we now show an "Archived" badge on repo search results

![Image](https://github.com/sourcegraph/sourcegraph/assets/12631702/71de16d8-8b5e-466e-afa1-dd3603fbff48)
