### ISSUE TITLE
gitserver: implement back-off on reclone operation

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#7804]
Our reclone operation can fail. In particular we have seen instances of large monorepos fail. Constantly recloning leads to load on the codehost and Sourcegraph => impacts users.

https://app.hubspot.com/contacts/2762526/company/555146901/

**Comment by tsenart** [comment]
Re-assigning to you for now, but you're already overloaded for 3.13. We need to adjust accordingly.
