### ISSUE TITLE
RFC 40: Add Prometheus metrics

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#7827]
This issue tracks the implementation of adding Prometheus metrics for [RFC 40: Explicit Repository Permissions Model](https://docs.google.com/document/d/167WV_rhBg3oj0yw9fHwUMlB-8BR3ktk2FSsKiUQo55Y/edit).

**Comment by tsenart** [comment]
Closing this since we already have Prometheus metrics for all GraphQL queries and mutations.
