### ISSUE TITLE
docker-compose: file permission issues with grafana, gitserver, prometheus, redis-store

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#7829]
- **Sourcegraph version:** 
- **Platform information:** 

#### Steps to reproduce:

1. Install docker and docker-compose on a linux host (Ubuntu 18.04 for my purposes)
1. Clone https://github.com/sourcegraph/deploy-sourcegraph-docker on to the host
1. `cd docker-compose && docker-compose up -d`
1. See that grafana, gitserver, prometheus, and redis-store all etc. are restarting with file permission issues 

Logs:

**grafana:**

```
mkdir: can't create directory '/var/lib/grafana/plugins': Permission denied
GF_PATHS_DATA='/var/lib/grafana' is not writable.
```

**gitserver**: 

```
2020/01/16 20:22:46 failed to setup temporary directory: mkdir /data/repos/.tmp: permission denied
```

**redis-store**

```
6:M 16 Jan 20:21:07.282 # Can't open the append-only file: Permission denied
```

**prometheus**

```
goroutine 1 [running]:
github.com/prometheus/prometheus/promql.NewActiveQueryTracker(0x7ffc3e779ede, 0xb, 0x14, 0x2b4f400, 0xc0006fb290, 0x2b4f400)
	/app/promql/query_logger.go:115 +0x48c
main.main()
	/app/cmd/prometheus/main.go:364 +0x5229
level=info ts=2020-01-16T20:38:30.233Z caller=main.go:296 msg="no time or size retention was set so using the default time retention" duration=15d
level=info ts=2020-01-16T20:38:30.233Z caller=main.go:332 msg="Starting Prometheus" version="(version=2.14.0, branch=HEAD, revision=edeb7a44cbf745f1d8be4ea6f215e79e651bfe19)"
level=info ts=2020-01-16T20:38:30.233Z caller=main.go:333 build_context="(go=go1.13.4, user=root@df2327081015, date=20191111-14:27:12)"
level=info ts=2020-01-16T20:38:30.233Z caller=main.go:334 host_details="(Linux 5.0.0-1028-gcp #29~18.04.1-Ubuntu SMP Thu Dec 19 19:04:05 UTC 2019 x86_64 cff8783f9cc6 (none))"
level=info ts=2020-01-16T20:38:30.233Z caller=main.go:335 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2020-01-16T20:38:30.233Z caller=main.go:336 vm_limits="(soft=unlimited, hard=unlimited)"
level=error ts=2020-01-16T20:38:30.233Z caller=query_logger.go:85 component=activeQueryTracker msg="Error opening query log file" file=/prometheus/queries.active err="open /prometheus/queries.active: permission denied"
panic: Unable to create mmap-ed active query log

goroutine 1 [running]:
github.com/prometheus/prometheus/promql.NewActiveQueryTracker(0x7ffe6a746ede, 0xb, 0x14, 0x2b4f400, 0xc00056e570, 0x2b4f400)
	/app/promql/query_logger.go:115 +0x48c
main.main()
	/app/cmd/prometheus/main.go:364 +0x5229
```

**Comment by ggilmore** [comment]
Update:

There are two approaches that I can think of solve this problem.

1. Write a bash script that runs `chown` on all the data directories that will be [bind mounted](https://docs.docker.com/storage/bind-mounts/) into each container, and tell users that they need to run this after the containers are started for the first time.

   - This is simple, but seems very dirty and brittle.   Also, only Linux users will need to run this script (docker for mac automagically handles the file permission translation - I am not even sure if this strategy would work for windows).

1. Switch to using [named volumes](https://docs.docker.com/storage/volumes/) in the Docker container.

   - In addition to the [benefits listed on the docs page](https://docs.docker.com/storage/volumes/) (handled through docker api, can use remote storage, etc.), named containers [**inherit the permissions of the container’s filesystem** if the folder already exists in the container](https://serverfault.com/a/984599).

---
For these reasons, I continued down the named-volume path.

I created the following branches:

- https://github.com/sourcegraph/deploy-sourcegraph-docker/tree/permission: This replaces all the bind-mounted volumes in docker-compose.yaml with named volumes.

- https://github.com/sourcegraph/sourcegraph/compare/volumes: This modifies all all of our docker images in sourcegraph/sourcegraph to pre-create all the volume directories so that the named docker volumes can be attached with the correct permissions.

- https://github.com/sourcegraph/infrastructure/tree/zoekt-permissions: Does the same thing as above., but for `zoekt`.


---

This strategy works for all the docker images beside `prometheus`.  `prometheus` wants to write all of its data to `/prometheus` . However, `/prometheus` can be only written to by the `nobody` user and their use of the `VOLUME` directive in the Prometheus `Dockerfile` makes it impossible to `chown` `/prometheus` from a downstream Dockefile (like `sourcegraph/prometheus` ) : https://github.com/prometheus/prometheus/blob/7d159b2f0166084eeeb9f10bc47642386ce59486/Dockerfile#L22 (see https://devops.stackexchange.com/a/4542).

Three paths forward:

1. Give up on named volumes and use the bash script mentioned above
1. Change `prometheus`’ data folder to anything other than `/prometheus` . Note that doing this across the board will require migrations for our existing k8s users, but it’s possible to isolate it to just deploy-sourcegraph-docker through environment variables cc @uwedeportivo. 
1. Change the default user in `sourcegraph/prometheus` back to `nobody`. We are already running as root in `k8s`,: https://github.com/sourcegraph/deploy-sourcegraph/blob/e3beefb4a161dc6f9c84f3953c337e5b4a4f737c/base/prometheus/prometheus.Deployment.yaml#L58-L59, so we weren’t using the [sourcegraph user](https://github.com/sourcegraph/sourcegraph/blob/9b5e6102d93c43c1c228b03aabe2094f13ff72cf/docker-images/prometheus/Dockerfile#L13-L19) to anyway. Doing this will require the existing `deploy-sourcegraph-docker` that use deploy-sourcegraph-docker to run chown make sure that their existing data directory is writeable by `nobody` again - but this seems reasonable since I can only think of one major customer that's using `deploy-sourcegraph-docker` anyway.

**Comment by slimsag** [comment]
> Change prometheus’ data folder to anything other than /prometheus . Note that doing this across the board will require migrations for our existing k8s users, but it’s possible to isolate it to just deploy-sourcegraph-docker through environment variables

We shouldn't isolate things like this just to deploy-sourcegraph-docker. It adds more cases where we are prone to breakage in the future. If we do go down this route, we need to do it across the board for both k8s and deploy-sourcegraph-docker.

**Comment by slimsag** [comment]
> Change the default user in sourcegraph/prometheus back to nobody. We are already running as root in k8s,: https://github.com/sourcegraph/deploy-sourcegraph/blob/e3beefb4a161dc6f9c84f3953c337e5b4a4f737c/base/prometheus/prometheus.Deployment.yaml#L58-L59, so we weren’t using the sourcegraph user anyway. Doing this will require the existing deploy-sourcegraph-docker users to run chown to make their existing data directory writeable by nobody again - but this seems reasonable since I can only think of one major customer that's using deploy-sourcegraph-docker anyway.

I believe doing this would be a mistake for a few reasons:

1. There is a lot of existing art here about why running as `nobody` and `root` are both bad ideas:

- https://github.com/prometheus/prometheus/issues/3441
- https://github.com/prometheus/prometheus/issues/3485

2. I am certain there are three customers running deploy-sourcegraph-docker currently, we would need to inform each. There also may be more we're not aware of, so more importantly: because we don't have a good way to communicate these changes yet you would need to ensure we have a prominent marker in our blog post and changelog linking to a docpage for something along the lines of "IMPORTANT: Use deploy-sourcegraph-docker? A manual migration is required, please see [the migration notes]()"

3. There are some customers who _cannot_ run containers as root in k8s, and I suspect `nobody` will also give them problems (ping me on Slack and I can name them if you want more specifics).

**Comment by slimsag** [comment]
> However, /prometheus can be only written to by the nobody user and prometheus/prometheus 's use of the VOLUME directive in the upstream Dockerfile makes it impossible to chown /prometheus from a downstream Dockefile (like sourcegraph/prometheus ).

Option 4: We're already publishing our own Prometheus image, and it looks like many users do not want Prometheus running as `nobody` (https://github.com/prometheus/prometheus/issues/3441) -- why don't we just fork that repository, send a PR, and use our own "upstream" image temporarily? This seems to me it would be a very straightforward way of solving the problem and wouldn't require writing or communicating complex migrations for users

**Comment by ggilmore** [comment]
> > However, /prometheus can be only written to by the nobody user and prometheus/prometheus 's use of the VOLUME directive in the upstream Dockerfile makes it impossible to chown /prometheus from a downstream Dockefile (like sourcegraph/prometheus ).
> 
> Option 4: We're already publishing our own Prometheus image, and it looks like many users do not want Prometheus running as `nobody` ([prometheus/prometheus#3441](https://github.com/prometheus/prometheus/issues/3441)) -- why don't we just fork that repository, send a PR, and use our own "upstream" image temporarily? This seems to me it would be a very straightforward way of solving the problem and wouldn't require writing or communicating complex migrations for users

Forking is an interesting option. However, the fundamental issue with their dockerfile is the use of the [`VOLUME` directive](https://github.com/prometheus/prometheus/blob/7d159b2f0166084eeeb9f10bc47642386ce59486/Dockerfile#L22). This [makes it impossible](https://devops.stackexchange.com/a/4542) for us to chown `/prometheus` to be owned by any other user besides the one declared in the upstream dockerfile. 

Getting rid of this volume directive probably isn't a PR they'd accept. We could fork prometheus and simply change [`USER nobody`](https://github.com/prometheus/prometheus/blob/7d159b2f0166084eeeb9f10bc47642386ce59486/Dockerfile#L21) to our "sourcegraph" user. This is also something that can't be upstreamed, but the diff would be tiny so it'd be easy for us to maintain.

**Comment by ggilmore** [comment]
> > Change prometheus’ data folder to anything other than /prometheus . Note that doing this across the board will require migrations for our existing k8s users, but it’s possible to isolate it to just deploy-sourcegraph-docker through environment variables
> 
> We shouldn't isolate things like this just to deploy-sourcegraph-docker. It adds more cases where we are prone to breakage in the future. If we do go down this route, we need to do it across the board for both k8s and deploy-sourcegraph-docker.
> 
> Also, I am pretty sure we could do this migration using an init container to make it seamless for users upgrading on k8s.

Thinking about this a bit more, I think the only thing that we'll need to change specifically for k8s is just the path of the volume mount: https://github.com/sourcegraph/deploy-sourcegraph/blob/e3beefb4a161dc6f9c84f3953c337e5b4a4f737c/base/prometheus/prometheus.Deployment.yaml#L46

We tell our users to fork and merge upstream when upgrading. As long as they accept the diff, the existing PVC should be able to mount at the new, writeable location.

**Comment by slimsag** [comment]
> Getting rid of this volume directive probably isn't a PR they'd accept. We could fork prometheus and simply change USER nobody to our "sourcegraph" user. This is also something that can't be upstreamed, but the diff would be tiny so it'd be easy for us to maintain.

I think we can do it by passing an ARG to their Dockerfile (i.e. allowing downstream `FROM prometheus` users to specify the user): https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact

**Comment by slimsag** [comment]
Let me know which option you decide on and I can give more feedback on that particular one if helpful

**Comment by ggilmore** [comment]
> > Getting rid of this volume directive probably isn't a PR they'd accept. We could fork prometheus and simply change USER nobody to our "sourcegraph" user. This is also something that can't be upstreamed, but the diff would be tiny so it'd be easy for us to maintain.
> 
> I think we can do it by passing an ARG to their Dockerfile (i.e. allowing downstream `FROM prometheus` users to specify the user): https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact

afiak this won't work. Docker doesn't replay all of the instructions from each image that you inherit from - it just downloads the layers that the image refers to. `ARG` won't have any effect here. So, any downstream users would still see `/prometheus` as owned by whatever user was specified in the upstream Dockefile because of the volume directive

**Comment by slimsag** [comment]
https://github.com/slimsag/example-for-geoffrey
