### ISSUE TITLE
Track usage of search modes in pings

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#7831]
https://sourcegraph.slack.com/archives/CMT39K56Z/p1579200732080100

**Comment by dadlerj** [comment]
What decisions will we make, or what will we do differently with this information? Please be specific.

**Comment by dadlerj** [comment]
@attfarhan #8317 doesn't actually close this! This just adds the data to the event log stream (which is stored in BigQuery for Sourcegraph.com, and in the internal Postgres db on self-hosted instances). If you want to capture this in pings, there are additional steps involved: 

https://about.sourcegraph.com/handbook/engineering/adding_ping_data

https://docs.sourcegraph.com/dev/architecture/life-of-a-ping

CC @ebrodymoore can help with questions here!

**Comment by attfarhan** [comment]
Got it, thanks

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.14 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
