### ISSUE TITLE
Track usage of search filters in pings

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#7832]
We need to measure usage of search filters in pings, so that we can track our user's adoption of advanced search features.

**Comment by dadlerj** [comment]
What decisions will we make, or what will we do differently with this information? Please be specific.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.14 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by lguychard** [comment]
This was done in 3.14
