### ISSUE TITLE
Track daily, weekly, monthly active users of search in pings

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#7833]
We'd like to have a better view of our user's engagement with the search feature on customer instances.   In order to do this, we'd like to track aggregate daily, weekly and monthly users of the search features in pings.

**Comment by dadlerj** [comment]
What decisions will we make, or what will we do differently with this information? Please be specific.

Are you aware that we do capture whether an instance has ever run a search or not (see https://docs.sourcegraph.com/admin/pings for the current list) — it should be possible to calculate this duration (roughly) based on the first time we see this boolean set to true.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.14 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
