### ISSUE TITLE
Monitoring doesn't work on Amazon EKS out of the box

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#7835]
A customer running our vanilla YAML files on Amazon EKS (with no special configuration) is unable to use our monitoring because of some errors in Prometheus like:

> [...] Failed to list *v1.Node: nodes is forbidden: User \"[]...]\" cannot list resource \"nodes\" in API group [...] at the cluster scope

This indicates our YAML are somehow incompatible with EKS out of the box. We should fix that, or provide steps to correct this when deploying on EKS.

@ggilmore suggested that he found https://github.com/awsdocs/amazon-eks-user-guide/blob/master/doc_source/dashboard-tutorial.md#step-3-create-an-eks-admin-service-account-and-cluster-role-binding which indicates the existence of a cluster-admin role and imagines this to be due to some weird IAM behavior with k8s.

**Comment by slimsag** [comment]
The customer ended up finding out the problem: the 'default' namespace [here](https://github.com/sourcegraph/deploy-sourcegraph/blob/master/base/prometheus/prometheus.ClusterRoleBinding.yaml#L16) needed to be set to 'ourcompanyname' for our k8s cluster.

Proposal: Let's just document that if you see this error in Prometheus container logs, you may need to do this or reach out to us for help debugging.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.13 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
woops, we dropped the ball on this, assigning to me and changing milestone

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.14 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
fixed with restrictive permission variant of our YAMLs (changed role and configmap)
