### ISSUE TITLE
Add steps to acquire a full metrics dump for last 7 days from Kubernetes and load it into dev instance

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#7836]
I previously documented a way for sourcegraph/server customers we can gather a dump of all Proemtheus metrics for us to support and this has been really valuable: https://docs.sourcegraph.com/admin/troubleshooting#submitting-a-metrics-dump
 
But there are some problems:

1. This archives the entire Prometheus dataset, which in Kubernetes deployments can be *really* large. We often only care about the past 7 days.
2. These steps do not work with Kubernetes deployments, because it is not possible to `apk add --no-cache curl` inside the Prometheus container (it uses a Busybox base image with no package manager, so we must install `curl` in our prometheus image ahead of time).

The ask here is simple:

- [x] Update our Prometheus docker image to have curl installed by default (you will need to find a static binary from curl's website I imagine).
- [x] Update our Prometheus configurations so that the admin API is enabled: https://prometheus.io/docs/prometheus/latest/querying/api/#tsdb-admin-apis
- [x] Document the commands for server, k8s, and docker-compose for how an admin can submit to us a full metrics dump for the last 7d using the TSDB snapshot API https://prometheus.io/docs/prometheus/latest/querying/api/#tsdb-admin-apis
- [x] Document how I can load this snapshot into a Prometheus instance of a `sourcegraph/server` with the same Sourcegraph version on my dev machine for investigating / poking around.

**Comment by uwedeportivo** [comment]
- https://github.com/sourcegraph/sourcegraph/pull/8038
- https://github.com/sourcegraph/about/pull/526

**Comment by slimsag** [comment]
Fixed already by Uwe in the PRs linked above.
