### ISSUE TITLE
Add metrics and alerting for latency induced from permissions rate limiting

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#7837]
If an instance is experiencing latency induced from repository permissions enforcement hitting rate limiting, they must currently discover it through user reports. We should:

1. Track and inform site admins how much latency is being added from this on a dashboard.
2. Alert if latency is being added due to it (outside the case of a brand new user whose permissions are being sync'd)

**Comment by beyang** [comment]
I think this is mostly obviated by the new permissions API. Re-open if this is still necessary.
