### ISSUE TITLE
Sourcegraph search removes `[A` from search

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#784]
Try searching `r:golang/go$ type [A-Z] [A-Z] [A-Z]`, and the query is transformed into `r:golang/go$ type -Z] -Z] -Z]`

![search-bar-bug](https://user-images.githubusercontent.com/187831/45047038-c716a600-b02c-11e8-9630-f2744574a668.gif)

**Comment by ijt** [comment]
This seems to be working just fine. Closing it.

![Screen Shot 2019-05-08 at 4 07 56 PM](https://user-images.githubusercontent.com/15530/57414061-82d73900-71ab-11e9-9be2-d92bf0cb2933.png)
