### ISSUE TITLE
There are a lot of problems in the upgrade of sourcegraph from 3.8.0 to 3.11.4. The official solutions are also puzzling. To be honest, the user experience is not very good

### ISSUE THREAD

**Issue by Janche** [sourcegraph/sourcegraph#7848]
There are a lot of problems in the upgrade of sourcegraph from 3.8.0 to 3.11.4. The official solutions are also puzzling. To be honest, the user experience is not very good

**Comment by christinaforney** [comment]
Hi @Janche - thank you for that feedback! We're working hard to make this better, and understand this can be confusing. Just to confirm, you are only upgrading two minor versions at a time? Are you running a single docker node instance or a kubernetes cluster?

**Comment by Janche** [comment]
> Hi @Janche - thank you for that feedback! We're working hard to make this better, and understand this can be confusing. Just to confirm, you are only [upgrading two minor versions](https://docs.sourcegraph.com/#upgrading-sourcegraph) at a time? Are you running a single docker node instance or a kubernetes cluster?

Now，I solved this problem by deleting the user profile of the sourcegraph，And I used single docker.
