### ISSUE TITLE
Automation should never miss search results

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#7861]
In its current state Automation campaigns might miss search results because of the way it interacts with our search infrastructure. See [this comment chain](https://github.com/sourcegraph/sourcegraph/pull/7790#discussion_r367736633) for the full context. Below are a few excerpts

---

@rvantonder in https://github.com/sourcegraph/sourcegraph/pull/7790#discussion_r367736633:

> Here's a breakdown of things:
> 
> - for the repo question: this  (to me) is a problem where we don't have the possibility of two things at the same time: (1) a clean way to operate on a repo given we know what the repo is already and (2) a filtering mechanism to only run on certain files, or with certain constraints. The nice thing about replacer is that it actually solves (1) as far as the API is concerned: just give it the repo, it'll do the fetching, and it'll run comby on all the files (there is a way to filter files, but it is not _exactly_ the same as what we support in the query). But the point is there's no danger of fiddling with queries/escaping. The problem: the replacer interface is too rudimentary to understand/implement the full spectrum of our search query. The frontend/search interface (2) _does_ understand the full query and can perform the filtering mechanism (useful!) but the problem is that we need to mess around with the query to do that properly. I agree this is the best possible option right now, but there is another danger hidden in (2). Next point.
> 
> - Any time we ever call `newSearch`, we are never guaranteed to find all matches. For search/replace, it is imperative that we (a) always try our hardest to replace every instance (i.e., we will wait!) or (b) if we don't get everything, we need to know about what was missed. It would be great if there was a knob to say 'search and replace this, just guarantee me that you found every single instance', but there is a ton of search functionality across concerns (index/searcher/...) that make adding such a knob very very hard IMO, and it would be easier to build such a "guaranteed searcher" 'from scratch in replacer than try layer it onto search. The alternative is that we are cognizant of the limitations of search and monitor it when it tells us 'there were more results, but I didn't return them'. If we go this route, we will need to add a lot of (TBH probably annoying) logic that checks the state of returned results, refetches, and all that. I'm not even sure how we can guarantee that pans out, since search can skip repos _or_ files. It is brittle for this purpose brittle. Pagination gives me some hope that we can do finer accounting and do 'retry' operations in a much easier way (right now we'd have to do the accounting ourselves, somehow).
> 
> So we have bigger problems than that repo issue. Just for this regex campaign mode, I realized that since this is using searcher, partial results will return quickly, and so I basically will add `count:10000` with no real guarantee that all of the matches are covered. 
> 
> For example, when I create these campaigns locally:
> 
> ```
> {
>     "scopeQuery": "repo:github.com/sourcegraph/sourcegraph file:.*",
>     "regexMatch": "func",
>     "textReplace": "foo"
> }
> ```
> 
> will have 1048 matches (and returns quickly) while
> 
> ```
> {
>     "scopeQuery": "repo:github.com/sourcegraph/sourcegraph file:.* count:10000",
>     "regexMatch": "func",
>     "textReplace": "foo"
> }
> ```
> 
> will have 10647.
> 
> But there's an even bigger problem than the number of matches getting cut off by `count` or `timer`: it is that when we filter using, e.g., `file`, the list of files can _also_ be cut off. So for example, the query
> 
> ```
> {
>     "scopeQuery": "repo:github.com/torvalds/linux index:no file:.* count:10000",
>     "regexMatch": "TODO",
>     "textReplace": "DONE"
> }
> ```
> 
> on my machine will return only 15 matches. That's because we return some number of files (I think 1000 and `count` doesn't appear to do anything) and there are only 15 matches in those files. If I want to force search to try harder, I actually have to use the `regexMatch` value in the `scopeQuery`:
> 
> ```
> {
>     "scopeQuery": "repo:github.com/torvalds/linux TODO index:no file:.* count:10000",
>     "regexMatch": "TODO",
>     "textReplace": "yo"
> }
> ```
> 
> This finds 1776 matches. Does this find all the matches? _I still don't know_ and that's the problem. Long term we'll have to think about how to either rearchitect search code or queries to handle this issue, or build up a dedicated replacer service. There's contention in designing for 'time-to-first-result' and 'match-and-replace-all-instances-at-almost-any-cost'.

---

@rvantonder in https://github.com/sourcegraph/sourcegraph/pull/7790#discussion_r367868835:

> To be clear, what I mean is that we need to do (possibly significant) extra work compared to what the current search code is geared towards, not that it's at odds.
> 
> @keegancsmith probably has better insight, but my gut reaction is that using indexed search results/Zoekt is a no go. It is a black box and takes lots of shortcuts in ways that's hard to guarantee that it returns all matches, whether content or files (issue in #7709 may be indicative). Which implies using searcher logic. But searcher doesn't do repo filtering, that happens in the frontend. So there is an interface to cut out here.

---

@mrnugget in https://github.com/sourcegraph/sourcegraph/pull/7790#discussion_r367877914:

> There's two problems we have to address:
> 
>   1. We need to reliably come up with a list of repositories over which to run Automation campaigns.
>   2. We need to find every search result in each one of these repositories.
> 
> With our current state of campaign types and our roadmpa, I think (1) is already (or can be made) reliable by restricting scopeQuery to only accept repo:. That should always give us the full list of repositories that match the scopeQuery.
> 
> The problem is that once you do that, you start to come up with a lot of false positives. Example: you run a NPM credentials campaign with "scopeQuery": "repo:github". That returns 200 repos, but only 3 of those have an .npmrc file. So I decided to add file:.npmrc to the scopeQuery. Problem is that, apparently, we're now not reliable anymore without adding count:99999 to it. For regex-search-replace the problem is even bigger, because it can yield more hits.
> 
> Problem (2) is what we're discussing this in this comment chain and now becomes more important with regex-search-and-replace and future campaigns that will run in the background and proactively scan/search repositories.
> 
> I hope that we, builders of code search, can up with a way that allows us to make use of the search infrastructure we already have in a reliable way 😄
> 
>  [... comment by @rvantonder ...]
> 
> This comment combined with your earlier comment makes me think again of the idea of combining searcher/replacer into a single service with added "run code over git repo" functionality.

**Comment by rvantonder** [comment]
We need to discuss work items and timeline around this. There are [major items in Q1 OKRS](https://github.com/sourcegraph/about/pull/422/files#diff-a405389b63ebba44625dde67605b8ea5R92-R96) related to mostly orthogonal search issues. A lot of those issues and the underlying complexity rely heavily on my making progress toward them.

High level I agree with the idea of

> combining searcher/replacer into a single service with added "run code over git repo" functionality.

Addressing the 'automation should return all results' and implementing this is a different beast and my outlook is that taking this on will sap my ability to hit KRs. It's a lot of stuff.

**Comment by rvantonder** [comment]
@slimsag basing this question off of [comment](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@837b3b25d94e180864c7d1b7276a235a1ed9933a/-/blob/cmd/frontend/graphqlbackend/search_pagination.go#L224-2258): is the idea that search pagination would eventually provide a guarantee on:

- finding all repos for a query?
- finding all results of matching file content (results) across a subset of repos or single repo?

**Comment by rvantonder** [comment]
One attack plan, to support this in a native service:

- Use "replacer" service to generate diffs per repo (rename this service as needed). We send the service only a repo name and it uses the cache fetched from gitserver or whatever source (e.g., existing replacer service already does this).
- Replacer runs over all files, guaranteeing everything is processed and returns the diffs.
  - It will need to expand to allow filtering by file name. We should support only a limited scope query that allows specifying `file:` and the search pattern. We should avoid using existing searcher code and not support the entire set of search keywords
- We need to guarantee that we filter all matching repos (existing search code _may_ be good enough for this) to send to replacer.

Other attack plan: do this as an 'action' if we support arbitrary commands: https://github.com/sourcegraph/sourcegraph/issues/7723. If we run actions per-repo, it would take as input a file filter and search-replace patterns.

**Comment by mrnugget** [comment]
> and my outlook is that taking this on will sap my ability to hit KRs. It's a lot of stuff.

I got you. I assigned this to me and will own this. Making systems run better is what I _enjoy_ so I'm happy to take this on — I need your help though 🙂

> Addressing the 'automation should return all results' and implementing this is a different beast

I'm not sure how to read that sentence 😄 Are you saying that addressing this problem here is different than implenting the code-over-git-repo-service? Or are you saying problem-here vs. search-goals in Q1 are different?

> One attack plan, to support this in a native service:

Agree in general with this plan. I think though we should concentrate on this _as the first measure_:

>     * We need to guarantee that we filter all matching repos (existing search code _may_ be good enough for this) to send to replacer.

If we have the correct list of repos (right now: max of 200) I feel more confident searching for specific results in each repo (since the result set per search will be smaller).

For that I agree with

> We should support only a limited scope query 

I would go one step further and say that `scopeQuery` should be changed to only allow the value that's passed to `repo:`. No `file:`, no keyword etc.

**Comment by rvantonder** [comment]
> I need your help though

Of course! I was not necessarily originally opposed to taking this on, just that we need to discuss (next sync or whenever) what it all entails, and that I would probably have to drop other things if I owned this.

> that sentence

Dangling antecedent :(. 'this' refers to 'automation should return all results'. Implementing a solution for the automation problem is a distinctly different problem to fixing/extending search wrt Q1 goals in my mind. There's some overlap under the umbrella of 'search', but the issue is different enough that it needs special attention.

--- 

Agree with the rest. No `file:` to start is fine by me.

**Comment by keegancsmith** [comment]
Chiming in with a random infra thought to try make us more nimble. Searcher service becomes a “run code on commit” service. It’s already scaled out for having good IO and CPU. This idea is inspired by Joyent’s Manta project.

**Comment by mrnugget** [comment]
> Chiming in with a random infra thought to try make us more nimble. Searcher service becomes a “run code on commit” service. It’s already scaled out for having good IO and CPU. This idea is inspired by Joyent’s Manta project.

That's _exactly_ what I had in mind 😎 I think `searcher`/`replacer`/`<new automation thing>` are all "run X over repository". There's a slight difference in that `searcher`/`replacer` use the ZIP in memory and a new thing might need to extract it, but those could be endpoint-internal.

We'd get rid of 1 service (reduce our memory footprint _and_ disk usage due to shared cache), gain new functionality.

**Comment by mrnugget** [comment]
@tsenart I'm putting a 3d estimate on this, but understand that this is more of a placeholder to signify that I'll be spending _at least_ that amount of time on it.
