### ISSUE TITLE
Use simplified header on Campaign pages

### ISSUE THREAD

**Issue by christinaforney** [sourcegraph/sourcegraph#7868]
Currently you can see the search bar when on Campaign pages. If there is a search in scope, that will be shown. This feels out of context for the Campaign state, since the search bar does not influence what happens on these pages.

![image](https://user-images.githubusercontent.com/1559622/72636611-4223e800-3914-11ea-9638-a078eed0ee56.png)

Instead, we should use the simplified header used on the search query builder to avoid confusion.

![image](https://user-images.githubusercontent.com/1559622/72636642-510a9a80-3914-11ea-9a01-9a6993279ce9.png)

**Comment by eseliger** [comment]
@christinaforney campaign details view only (as shown above in screenshot) or also on the campaigns list view?

**Comment by christinaforney** [comment]
> @christinaforney campaign details view only (as shown above in screenshot) or also on the campaigns list view?

On the campaigns list view as well. I think the small conceptual separation of search vs. campaigns can help to focus the user on that part of the functionality.

**Comment by eseliger** [comment]
@christinaforney this was discussed on todays sync and we came to the conclusion that it's a more global problem and @attfarhan is going to take this on. Shall we close this automation specific issue then?

**Comment by christinaforney** [comment]
Yep, that makes sense. Thanks @eseliger !
