### ISSUE TITLE
Use serializable transactions for updating permissions

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#7877]
Our current code that interacts with DB for permissions ([`enterprise/cmd/frontend/internal/authz/store.go`](https://github.com/sourcegraph/sourcegraph/blob/master/enterprise/cmd/frontend/internal/authz/store.go)) uses Postgres's row-level locking (mostly `FOR UPDATE`) to ensure data consistency, but as @beyang noted, we might encounter lock-contention performance issues at scale because `FOR UPDATE` prevents regular reads (i.e. `FOR NO KEY UPDATE` locks while checking permissions in `authzFilter`) according to the documentation: https://www.postgresql.org/docs/9.6/explicit-locking.html#LOCKING-ROWS.

@beyang suggested we should revisit this issue (ideally) and be lockless in 3.13.

**Comment by tsenart** [comment]
> @beyang suggested we should revisit this issue (ideally) and be lockless in 3.13.

We could serializable transactions for such.

**Comment by unknwon** [comment]
I think we (i.e. me) should try serializable transactions as a spike in the end of this iteration if possible.

**Comment by unknwon** [comment]
Taking out of 3.14 to have more focus on shipping RFC 113.

**Comment by unknwon** [comment]
Example found in our codebase: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/repo-updater/shared/main.god#L91:20

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by unknwon** [comment]
Putting into 3.16 for now, this is more doable than ever since the development of background permission syncing (write path is mostly single threaded, except for granting permission upon user sign up).

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by unknwon** [comment]
Close until further input.
