### ISSUE TITLE
Reject invalid externalURL with non-/ path

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#7884]
We don't support non-root externalURLs #103 (eg `https://example.com/sourcegraph`) yet, but people sometimes miss this (eg #7876). It should reject or warn (just in the JSON Schema is fine) if there is a non-root-path external URL.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.13 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.14 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by keegancsmith** [comment]
@asdine another small task to help familiarize yourself with the codebase.
