### ISSUE TITLE
Extract and dump type information for Dart LSIF 

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#7908]
I'm supporting the Dart LSIF effort in '20% time'. I'm working with @chrismwendt on using crossdart for dumping LSIF data. I'm working closely with extracting static types and adding type hovers to the dump format.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.13 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by tsenart** [comment]
@rvantonder: Can you adjust the milestone accordingly?

**Comment by uwedeportivo** [comment]
please adjust milestone, spasiba

**Comment by rvantonder** [comment]
Backlogging this. Background:

- I don't think I'll have time to make progress on this in 3.14, but can shift things around if this becomes a strong request.
- We provide documentation hovers in the Dart LSIF indexer. Type hovers/annotations is a bonus, and my impression is this is not immediately pressing.

**Comment by rvantonder** [comment]
This issue is stale, closing. Please open a new issue if we want to support better Dart LSIF dumps with an owner.
