### ISSUE TITLE
a8n/auth: Regex search/replace doesn't work in private repos

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#7914]
In order to reproduce, make sure that you have two external services:

1. GitHub external service with your token that clones `github.com/sourcegraph/automation-testing`, a public repo
2. GitHub external service with `sd9` token (see 1Password) that clones `github.com/sd9/ava`

Preview a CampaignPlan for `automation-testing` repo with these
parameters:

```json
{"scopeQuery": "repo:github.com/sourcegraph/automation-testing","regexpMatch": "This", "textReplace": "That"}
```

([Click here to run this in local API console](http://localhost:3080/api/console#%7B%22variables%22%3A%22%7B%5Cn%20%20%5C%22spec%5C%22%3A%20%7B%5Cn%20%20%20%20%5C%22type%5C%22%3A%20%5C%22regexSearchReplace%5C%22%2C%5Cn%20%20%20%20%5C%22arguments%5C%22%3A%20%5C%22%7B%5C%5C%5C%22scopeQuery%5C%5C%5C%22%3A%20%5C%5C%5C%22repo%3Agithub.com%2Fsourcegraph%2Fautomation-testing%5C%5C%5C%22%2C%5C%5C%5C%22regexpMatch%5C%5C%5C%22%3A%20%5C%5C%5C%22This%5C%5C%5C%22%2C%20%5C%5C%5C%22textReplace%5C%5C%5C%22%3A%20%5C%5C%5C%22That%5C%5C%5C%22%7D%5C%22%5Cn%20%20%7D%2C%5Cn%20%20%5C%22wait%5C%22%3A%20true%5Cn%7D%22%2C%22query%22%3A%22mutation%20PreviewCombyCampaign(%24spec%3A%20CampaignPlanSpecification!%2C%20%24wait%3A%20Boolean!)%20%7B%5Cn%20%20previewCampaignPlan(specification%3A%20%24spec%2C%20wait%3A%20%24wait)%20%7B%5Cn%20%20%20%20__typename%5Cn%20%20%20%20...%20on%20CampaignPlan%20%7B%5Cn%20%20%20%20%20%20...CampaignPlanFields%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%5Cn%5Cnfragment%20CampaignPlanFields%20on%20CampaignPlan%20%7B%5Cn%20%20id%5Cn%20%20type%5Cn%20%20arguments%5Cn%20%20status%20%7B%5Cn%20%20%20%20completedCount%5Cn%20%20%20%20pendingCount%5Cn%20%20%20%20state%5Cn%20%20%20%20errors%5Cn%20%20%7D%5Cn%20%20changesets%20%7B%5Cn%20%20%20%20totalCount%5Cn%20%20%20%20nodes%20%7B%5Cn%20%20%20%20%20%20diff%20%7B%5Cn%20%20%20%20%20%20%20%20baseRepository%20%7B%20name%20%7D%5Cn%20%20%20%20%20%20%20%20fileDiffs%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20rawDiff%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%7D))

That returns a few results.

Now, if I change the `scopeQuery` to search `github.com/sd9/ava` it doesn't return anything:

```json
{"scopeQuery": "repo:github.com/sd9/ava","regexpMatch": "This", "textReplace": "That"}
```

([Click here to run this in local API console](http://localhost:3080/api/console#%7B%22variables%22%3A%22%7B%5Cn%20%20%5C%22spec%5C%22%3A%20%7B%5Cn%20%20%20%20%5C%22type%5C%22%3A%20%5C%22regexSearchReplace%5C%22%2C%5Cn%20%20%20%20%5C%22arguments%5C%22%3A%20%5C%22%7B%5C%5C%5C%22scopeQuery%5C%5C%5C%22%3A%20%5C%5C%5C%22repo%3Agithub.com%2Fsourcegraph%2Fautomation-testing%5C%5C%5C%22%2C%5C%5C%5C%22regexpMatch%5C%5C%5C%22%3A%20%5C%5C%5C%22This%5C%5C%5C%22%2C%20%5C%5C%5C%22textReplace%5C%5C%5C%22%3A%20%5C%5C%5C%22That%5C%5C%5C%22%7D%5C%22%5Cn%20%20%7D%2C%5Cn%20%20%5C%22wait%5C%22%3A%20true%5Cn%7D%22%2C%22query%22%3A%22mutation%20PreviewCombyCampaign(%24spec%3A%20CampaignPlanSpecification!%2C%20%24wait%3A%20Boolean!)%20%7B%5Cn%20%20previewCampaignPlan(specification%3A%20%24spec%2C%20wait%3A%20%24wait)%20%7B%5Cn%20%20%20%20__typename%5Cn%20%20%20%20...%20on%20CampaignPlan%20%7B%5Cn%20%20%20%20%20%20...CampaignPlanFields%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%5Cn%5Cnfragment%20CampaignPlanFields%20on%20CampaignPlan%20%7B%5Cn%20%20id%5Cn%20%20type%5Cn%20%20arguments%5Cn%20%20status%20%7B%5Cn%20%20%20%20completedCount%5Cn%20%20%20%20pendingCount%5Cn%20%20%20%20state%5Cn%20%20%20%20errors%5Cn%20%20%7D%5Cn%20%20changesets%20%7B%5Cn%20%20%20%20totalCount%5Cn%20%20%20%20nodes%20%7B%5Cn%20%20%20%20%20%20diff%20%7B%5Cn%20%20%20%20%20%20%20%20baseRepository%20%7B%20name%20%7D%5Cn%20%20%20%20%20%20%20%20fileDiffs%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20rawDiff%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%7D))

But if I run the search manually, by [searching for `repo:github.com/sd9/ava This` in regexp-mode](http://localhost:3080/search?q=repo:github.com/sd9/ava+This&patternType=regexp)), I get results.

Just not in Automation, which in combination with https://github.com/sourcegraph/sourcegraph/issues/7912 makes me think that this has something to do with auth

**Comment by unknwon** [comment]
qq: Have campaigns for private repositories ever worked? Or is this a new attempt and new discover?

**Comment by mrnugget** [comment]
I only discovered this now with the new search/replace campaign type, but now that you mentioned it, I think that this also affects the NPM credentials campaign type, which also uses search to find matches. But I'm not sure. 

We previously also ran into auth issues with search, where we forgot to set the actor. See this comment:

https://github.com/sourcegraph/sourcegraph/issues/6620#issuecomment-554252346

I'm wondering whether we introduced a regression with the move to background workers (cc @ryanslade) since we now don't have the actor at hand anymore.

To fix this, we could produce an actor in the background. But for that, we'd need to persist an `author_id` on the `CampaignPlan`.

**Comment by mrnugget** [comment]
Correction: I don't think it's the move to background workers, because in the example queries I linked to above we use `wait: true`, which runs the CampaignPlan in `frontend`, using the actor of the request:

https://github.com/sourcegraph/sourcegraph/blob/97af9d04a8ce24d88dde2e79cb02261622da058f/enterprise/internal/a8n/resolvers/resolver.go#L509-L515

And even that doesn't return any results.

So, what are we missing from our usage of search in Automation that stops us from accessing the repo contents? If I search the repositories, I can access them. But if we search inside Automation, we don't get any results.

**Comment by mrnugget** [comment]
Scratch my correction: even if we do use `Wait` we run the jobs in the background, except that we poll for their completion.

**Comment by mrnugget** [comment]
Confirmed: it's because we don't use an actor in the background process. If I apply the following diff it works.

```diff
diff --git a/enterprise/internal/a8n/runner.go b/enterprise/internal/a8n/runner.go
index 9c922f5d32..e241e1454e 100644
--- a/enterprise/internal/a8n/runner.go
+++ b/enterprise/internal/a8n/runner.go
@@ -13,6 +13,7 @@ import (
 	"github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend"
 	"github.com/sourcegraph/sourcegraph/cmd/repo-updater/repos"
 	"github.com/sourcegraph/sourcegraph/internal/a8n"
+	"github.com/sourcegraph/sourcegraph/internal/actor"
 	"github.com/sourcegraph/sourcegraph/internal/api"
 	"github.com/sourcegraph/sourcegraph/internal/env"
 	"github.com/sourcegraph/sourcegraph/internal/trace"
@@ -377,6 +378,8 @@ func runCampaignJob(ctx context.Context, clock func() time.Time, store *Store, c
 		}
 	}
 
+	act := actor.FromUser(1)
+	ctx = actor.WithActor(ctx, act)
 	diff, desc, err := ct.generateDiff(ctx, api.RepoName(rs[0].Name), job.Rev)
 	if err != nil {
 		job.Error = err.Error()
```

**Comment by mrnugget** [comment]
We need to fix this because it broke NPM credentials campaigns in 3.12.

Possible solution: persist the `user_id` of the current user on a `CampaignPlan` (I think it can be nullable, to make testing easier everywhere). Then, when running the `CampaignJobs`, fetch the user ID by fetching the `CampaignPlan` of the `CampaignJob`, create an `actor.FromUser` and use that in the `ctx` (see diff in previous comment).

That requires an additional query. Instead we could also denormalize the data and save the user_id on every CampaignJob. Since the data is immutable, that doesn't seem like a big problem.

**Comment by ryanslade** [comment]
I'm going to go with the first option and put it on the CampaignPlan. I don't feel we need to denormalise for performance at this point as the query will only be run when a job is taken from the queue which probably won't be frequent enough to cause problems.
