### ISSUE TITLE
Add "edit saved searches" to email notifications

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#7928]
The emails lack a link to edit the saved search — they only have "view results" and "unsubscribe"

![image](https://user-images.githubusercontent.com/5589410/72825378-c4b9e980-3c2b-11ea-81b4-daec6198872a.png)

Honestly not sure who to tag on this, so it's yours to distribute to the right person, @christinaforney :)

**Comment by christinaforney** [comment]
I have so many ideas about improving these emails! Is this a specific feature request from a customer, or a pain point that you noticed?

**Comment by dadlerj** [comment]
Same haha. This was a personal annoyance. I had created one for a customer demo. When I got a notification, I wanted to turn it off, but had no way to do so.

**Comment by christinaforney** [comment]
Gotcha. Yep, have had the same issue too.

**Comment by lguychard** [comment]
We no longer have saved searches, but code monitoring emails link to the code monitor definition.
