### ISSUE TITLE
zoekt: support indexing multiple branches in zoekt-archive-index

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#7930]
Parent issue: https://github.com/sourcegraph/sourcegraph/issues/6728

The first step in supporting indexing multiple branches is for our indexing method to handle multiple branches. Right now we index tarballs via `zoekt-archive-index`. This issue is about supporting passing multiple tarballs (or zips) into zoekt-archive-index such that each tarball represents a branch. See the parent issue for much more context/discussion on this topic.

Requested by https://app.hubspot.com/contacts/2762526/company/554338610

**Comment by tsenart** [comment]
A potential idea for consideration is to have git-server merge these archives itself and serve that result for download. Not sure if worth it from a performance / implementation time perspective, just wanted to leave this here :-)

http://tldp.org/HOWTO/SquashFS-HOWTO/whatis.html

**Comment by keegancsmith** [comment]
I do like that idea a lot, and was in fact something I mentioned in my original proposal. I didn’t move forward with the idea due to it being more effort. But I am quite enamoured with the idea of having more control of this bit of data we generate and use everywhere.

**Comment by keegancsmith** [comment]
@tsenart filed this issue to explore your idea. Something to consider for next milestone https://github.com/sourcegraph/sourcegraph/issues/7937

**Comment by keegancsmith** [comment]
Most of my work I have been doing by submitting patches upstream. However, I have now created a draft PR with active work. I have spent the better part of two days hacking on this, which is more time than we allocated for this spike. We have something working, but very hacky. I would regard this spike as complete, but would like to clean up the code a bit since it is extremely hacky at the moment. So will leave this issue open and address this later in the cycle.

https://github.com/sourcegraph/zoekt/pull/36

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.13 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by tsenart** [comment]
@slimsag: I believe this was closed by mistake?

**Comment by slimsag** [comment]
Yes, mistake, thanks! I corrected the typo in my PR description but not in the commit and didn't realize it.

**Comment by keegancsmith** [comment]
Using shallow git clones instead. See https://github.com/sourcegraph/sourcegraph/issues/9888 and #6728
