### ISSUE TITLE
Placeholder: Continuous release process

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#7950]
This is a placeholder issue for implementing a continuous release process and adding more release automation.

## Notes
- Merge on test pass                                                                                                                                           
- Changelog entries from commit message                                                                                                                        
- Cut releases (if commit message includes special tag ("release: v3.11.4"))                                                                                   
- Try GitHub actions to implement the above
- PR template

## Prior work
* https://github.com/sourcegraph/sourcegraph/issues/2311
* https://github.com/sourcegraph/sourcegraph/issues/2392
* https://github.com/sourcegraph/sourcegraph/issues/7148

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.13 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
i'm taking the liberty to move to 3.14, @beyang adjust if i'm wrong

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.14 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by slimsag** [comment]
Closing in favor of https://github.com/sourcegraph/sourcegraph/issues/9252
