### ISSUE TITLE
codecov: dashboard redirect includes "undefined" in URL

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#7954]
This repository has codecov data:

https://sourcegraph.sgdev.org/sourcegraph/enterprise@093a16521df58e6c49cf70e6a4832137e740265a/-/blob/cmd/frontend/backend/dependencies.go

Configure a codecov access token, then select:

![image](https://user-images.githubusercontent.com/3173176/72947289-c7f1ca00-3d3e-11ea-8501-db505068f480.png)

You will be redirected to https://codecov.io/gh/enterprise/undefined which is obviously wrong (it should be https://codecov.io/gh/sourcegraph/enterprise )

**Comment by slimsag** [comment]
Also happens using the browser extension on same page on GitHub, when extension is configured to sourcegraph.sgdev.org

**Comment by lguychard** [comment]
The root cause of this issue is the same as https://github.com/sourcegraph/sourcegraph/issues/7956#issuecomment-577577973
