### ISSUE TITLE
codecov: does not work on private repositories without private Sourcegraph instance

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#7955]
According to our docs, the codecov extension should work on a private GitHub repository when the browser extension is configured to `https://sourcegraph.com`.

Yet, when you select the "set API token" action in the command pallet nothing happens (the menu just disappears):

![image](https://user-images.githubusercontent.com/3173176/72947529-7c8beb80-3d3f-11ea-9676-095c04ac4c3b.png)

Additionally, it doesn't seem to be possible to get codecov to appear on such repositories unless a private Sourcegraph instance with that repo is configured in the browser extension. The button does not appear (even in a repo/file with code coverage, like https://codecov.io/gh/sourcegraph/enterprise/src/master/cmd/frontend/backend/dependencies.go ), certain actions do not appear in the command palette such as `View repository coverage dashboard`, etc.

**Comment by lguychard** [comment]
Fixed in browser extension version 20.1.23.1131.
