### ISSUE TITLE
Scala LSIF indexer

### ISSUE THREAD

**Issue by christinaforney** [sourcegraph/sourcegraph#7957]
Requested by a user via twitter: https://twitter.com/jvican/status/1219797315617095680 

Two interested customers:
- https://app.hubspot.com/contacts/2762526/company/407948923
- https://app.hubspot.com/contacts/2762526/company/554275594

**Comment by macraig** [comment]
@scalabilitysolved keeping separate as Scala support is out of scope for now.

**Comment by macraig** [comment]
Shipped in [scip-java](https://sourcegraph.github.io/scip-java/)
