### ISSUE TITLE
server_proxy_test.go: TestCache flakey

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#797]
```
FAIL: TestCache (0.07s) | 0s
  server_proxy_test.go:94: expected get(x) = hello, got cache miss
```

Failed first time:
https://buildkite.com/sourcegraph/sourcegraph/builds/22766#507d4137-98b2-4ba0-9930-d5d24a829a5a

Passed on retry:
https://buildkite.com/sourcegraph/sourcegraph/builds/22766#f4ba9fab-acce-4c88-9a78-214d221549f0

**Comment by keegancsmith** [comment]
woah, that is rather surprising. Either the 50ms sleep is not enough time (surprising), or redis cache is aggressively evicting items. Either way we will be deleting lsp-proxy, so unless this has been flakey more than once I'm not sure it is worth fixing / rather just delete the test.

**Comment by sqs** [comment]
Will be fixed with the removal of lsp-proxy (or will delete it sooner)

**Comment by keegancsmith** [comment]
I forgot this issue existed and I just had a build fail due to this test and took another look at it. Assuming redis is behaving, it is quite easy to fix so I did that. If this fails again then we can make the test DIAF
