### ISSUE TITLE
Add nightly browser extension test runs

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#7980]
We should improve our browser extension tests so that we can:
- [x] Catch regressions caused by GitHub DOM changes (this may be as simple as running our regular browser extension tests more often than just on bext release)
- [ ] Catch visual regressions such as https://sourcegraph.slack.com/archives/CHXHX7XAS/p1579741455063500

This should take the form of:
- [x] Nightly browser extension tests against github.com
- [x] Nightly browser extension tests against gitlab.com
- [ ] Nightly native integration tests agains gitlab.com
- [ ] Upload coverage under an extra flag

Tests should cover:
- [ ] Code intelligence on all supported code views (file, commit, pull request in unified/split view...)

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by eseliger** [comment]
Extracting remaining work items into separete issues, as they are no immediate requirement and out of scope for the issue title.
