### ISSUE TITLE
Semantic commit linting somehow getting turned on in latest master

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#799]
Running the latest master it seems that one of the browser-extensions, e-c-c, or sourcegraph-extensions-api subdirs is now adding a semantic commit linting pre-commit hook to my `.git/hooks`. This seems like it may be occurring unintentionally?

https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+commitlint

**Comment by chrismwendt** [comment]
This was unintentional, I'll remove husky
