### ISSUE TITLE
Bitbucket Cloud external service doesn't respect custom URLs

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#7990]
Reported by https://app.hubspot.com/contacts/2762526/company/557475593

>there’s already a field for ‘url’ [for the Bitbucket Cloud external service] but entering a value there doesn’t seem to change the URL of the API calls from Sourcegraph to Bitbucket.

**Comment by unknwon** [comment]
The action item here is to add an optional `apiURL` field, and document it clear that regular users shouldn't use it.

**Comment by unknwon** [comment]
What's the priority of this issue, should it be squeezed in 3.13?

**Comment by unknwon** [comment]
PR sent: https://github.com/sourcegraph/sourcegraph/pull/8082, PTAL!
