### ISSUE TITLE
LSIF: cannot upload LSIF for private repository

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#7996]
@efritz reported that when running a local dev instance with a private repository added, uploading LSIF data for it fails at "NO":

```go
	repo, err := backend.Repos.GetByName(ctx, api.RepoName(repoName))
	if err != nil {
		if errcode.IsNotFound(err) {
			fmt.Printf("NO: %#v\n", err)
			http.Error(w, fmt.Sprintf("unknown repository %q", repoName), http.StatusNotFound)
			return nil, false
		}
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return nil, false
	}
```

https://sourcegraph.com/github.com/sourcegraph/sourcegraph@727dcb2f6ad74f67294c4c07930e172eb2493c02/-/blob/enterprise/internal/codeintel/lsifserver/proxy/proxy.go#L96:16

I believe `backend.Repos.GetByName` fails for private repos because the auth data carried in `ctx` and this is an unauthenticated endpoint.

Ideas:

- Additionally accept a Sourcegraph access token
- Bypass auth for that particular repository check (`lsif.enforceAuth` will still have an effect later)
- Skip that particular repository check entirely (could have unintended consequences, such as allowing uploads for nonexistent repositories)

cc @sourcegraph/code-intel

**Comment by efritz** [comment]
LOL thanks for keeping my debug statements in there.

**Comment by efritz** [comment]
Option 3 is a non-starter. Option 1 basically makes it an authed request. What is the damage Option 2 can do in private instances w.r.t. leaking data?

We return a 404 on unknown repo and commit and a 401 on a codehost auth check (when enabled).

**Comment by chrismwendt** [comment]
> What is the damage Option 2 can do in private instances w.r.t. leaking data?

The Sourcegraph instance could act as an oracle that tells you whether or not a private repository exists. I don't know if that's acceptable. cc @sourcegraph/core-services to weigh in.

**Comment by keegancsmith** [comment]
> The Sourcegraph instance could act as an oracle that tells you whether or not a private repository exists. I don't know if that's acceptable

That isn't acceptable. If an actor doesn't have access to a repo, then Sourcegraph should behave like it doesn't exist.

**Comment by scalabilitysolved** [comment]
Is this still a valid issue @efritz ?

**Comment by efritz** [comment]
No this is outdated.
