### ISSUE TITLE
Error creating campaign

### ISSUE THREAD

**Issue by christinaforney** [sourcegraph/sourcegraph#7999]
From https://app.hubspot.com/contacts/2762526/contact/17877751

> At one point I hit this error trying to create the campaign:
Pq: insert or update on table "campaigns" violates foreign key constraint "campaigns_campaign_plan_id_fkey"
Not sure what produced this error. Ended up starting over, created a new campaign and changed the title and it worked.
Might have been [ ] characters in the title?

**Comment by mrnugget** [comment]
This sounds like a Campaign with the same CampaignPlan already exists. Can you confirm that this was not the case?

**Comment by mrnugget** [comment]
I'm closing this, because I'm reasonably sure that it was a double-submission and the CampaignPlan was already attached to a Campaign. If we run into this again, let's reopen.
