### ISSUE TITLE
Scala code intelligence

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#8]
Support Scala on Sourcegraph

**Comment by sqs** [comment]
Update: https://twitter.com/avibryant/status/1047181708687265792

I will be talking with Olafur and Eugene in the next week or so about integrating the existing Scala lang server into Sourcegraph.

**Comment by mwz** [comment]
Goto definition feature was recently implemented in metals, perhaps it should now be possible to make a start on this?

**Comment by chrismwendt** [comment]
Sweet, would you (or someone you know) be interested in making it happen? [Sourcegraph extensions](https://docs.sourcegraph.com/extensions) make it easy to add language support to Sourcegraph (e.g. [Go](https://sourcegraph.com/extensions/sourcegraph/lang-go)). We're happy to help out with support and funding!

**Comment by chrismwendt** [comment]
Scala code intelligence has been added in Sourcegraph 3.0 :tada:

https://about.sourcegraph.com/blog/sourcegraph-3.0#code-intelligence-for-all-languages

[Try it out](https://sourcegraph.com/github.com/flix/flix@f6ac989206d195225e90ea2b65f0d6b5b517e6a1/-/blob/main/src/ca/uwaterloo/flix/language/phase/Resolver.scala#L210:24) on Sourcegraph.com:

![image](https://user-images.githubusercontent.com/1387653/52602419-73985780-2e17-11e9-9bc9-002d349fa089.png)

**Comment by sslavian812** [comment]
Is this Scala-langserver open-sourced already?

**Comment by sqs** [comment]
Yes, the language server discussed above is https://github.com/scalameta/metals.

**Comment by ittaiz** [comment]
Just to make sure I understand- the scala support is text based and without a language server protocol, right? Just couldn’t be sure from the docs

**Comment by chrismwendt** [comment]
@ittaiz Correct, Scala support is based on ctags + text search (as is all out-of-the-box code intelligence for Sourcegraph).

Which docs page did you look at? I'd like to improve these.

**Comment by ittaiz** [comment]
I was [here](https://sourcegraph.com/extensions/sourcegraph/scala) which does say it's text based but doesn't explicitly says it's not LSP based. I wasn't sure if the omission indeed means it's not supported because this issue made me think it might have been implemented with it due to above comments.
