### ISSUE TITLE
e2e: log all e2e failures into central location for triage

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#8026]
Either googledocs or airtable. Will allow us to track all failed builds, and then triage them to understand why they failed.

Currently we rely on devs self reporting in a central tracking issue. Rather we can pro-actively investigate all failures.

I (@keegancsmith) will timebox 30min a day to triaging failures. This will help me get intimate with our e2e stack so I can improve stuff.

**Comment by nicksnyder** [comment]
I think this is a good next step. I have a weak preference for google sheet, but whatever is easier to automate really.

I am surprised that we can't get this information out of buildkite and will send an email to ask for this.

**Comment by nicksnyder** [comment]
Is this a list of all red builds, or only builds that we automatically detect as flaky?

**Comment by keegancsmith** [comment]
I'm not interested in red builds, we can get that from buildkite. I'm interested in the individual tests that failed. So at a granularity buildkite doesn't support.

**Comment by nicksnyder** [comment]
Buildkite support let me know that URL hacking can give us what we want:

https://buildkite.com/organizations/sourcegraph/builds?state=failed&branch=master
https://buildkite.com/organizations/sourcegraph/builds?state=failed

There is also a REST api that might be helpful:
https://buildkite.com/docs/apis/rest-api/jobs

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.13 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by tsenart** [comment]
Nothing to do here given https://github.com/sourcegraph/sourcegraph/issues/8026#issuecomment-578350348
