### ISSUE TITLE
Sprinkle CLI instructions into the campaigns UI

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#8070]
With the campaign plans being created by the CLI, we should guide the users there.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.13 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
@eseliger could you please move to appropriate milestone or close if it's done, danke schoen :-)

**Comment by eseliger** [comment]
sorry, done!

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
