### ISSUE TITLE
CLA bot should not message PRs authored by member's of the Sourcegraph org on github

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#8097]
Members of https://github.com/sourcegraph should not need to fill out the CLA.

The new check should probably be added here: https://sourcegraph.sgdev.org/sourcegraph/infrastructure@01eb0fd02520e26162a26a04c7feac8003120f20/-/blob/docker-images/sgbot/main.go#L104-119

Example PR where CLA bot was failing because @efritz had not signed CLA: https://github.com/sourcegraph/sourcegraph/pull/8029

The workaround is for Sourcegraph employees to just fill out the CLA.

**Comment by unknwon** [comment]
I've signed CLA and received confirmation email for my work email "joe@sourcegraph.com" but the cla-bot is still failing on https://github.com/sourcegraph/sourcegraph/pull/8067. 🤔

**Comment by eseliger** [comment]
@unknwon I retriggered CI on #8067 and it seems to work after my patch here https://github.com/sourcegraph/infrastructure/pull/1809

Closing this for now, but if anyone on the Sourcegraph org still has trouble with the CLA bot, please feel free to reopen.

**Comment by unknwon** [comment]
Thank you! @eseliger
