### ISSUE TITLE
a8n: exposed token in the error message if create campaign failed

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#8105]
Trying to create a campaign but my token in the GitHub code host config does not have access to certain repository. Then it shows me the error message with the token.

![image](https://user-images.githubusercontent.com/2946214/73351296-a4dc9280-42c9-11ea-81c9-394b61eaff8f.png)

**Comment by ryanslade** [comment]
I can easily make the change for that particular case, but I think maybe we should add something at the resolver layer so that we redact any "token@github.com" strings and perhaps others in future. Currently looking for a way to do this.

**Comment by nicksnyder** [comment]
See also https://github.com/sourcegraph/sourcegraph/issues/8078 and in particular this comment

https://github.com/sourcegraph/security-issues/issues/60#issuecomment-579295610

**Comment by keegancsmith** [comment]
the issue seems to be that the patch code actually constructs a command containing the remote URL. It shouldn't need to "know" the remote URL, it should just tell gitserver to push. This should work since it is literally just asking gitserver for the remote URL that it would use if you just tell it to push :slightly_smiling_face: Additionally I think us directly specifying a "git push" command also bypasses some injection we do for remote commands, so likely breaks in some customer environments (grep our code for runWithRemoteOpts to see why).

**Comment by ryanslade** [comment]
I updated the code to simply push to `origin` instead of fetching the URL as `remoteURL` is simply obtained by requesting the remote url for the `origin` remote.

However, I now get this error:

```text
 CreateCommitFromPatch http://127.0.0.1:3178/create-commit-from-patch: CreateCommitFromPatch: http status 500 {"Rev":"","Error":{"RepositoryName":"bitbucket.sgdev.org/K8S/zoekt","Err":{},"Command":"git push --force origin dab52aec9e62c93727235045e8657b386ec0ac23:refs/heads/sourcegraph/campaign-1581089799","CombinedOutput":"remote: error: By default, deleting the current branch is denied, because the next \nremote: 'git clone' won't result in any file checked out, causing confusion. \nremote: \nremote: You can set 'receive.denyDeleteCurrent' configuration variable to \nremote: 'warn' or 'ignore' in the remote repository to allow deleting the \nremote: current branch, with or without a warning message. \nremote: \nremote: To squelch this message, you can set it to 'refuse'. \nremote: error: refusing to delete the current branch: refs/heads/master \nTo https://bitbucket.sgdev.org/scm/k8s/zoekt.git\n - [deleted] sourcegraph/campaign-1581088866\n * [new branch] dab52aec9e62c93727235045e8657b386ec0ac23 -\u003e sourcegraph/campaign-1581089799\n ! [remote rejected] master (deletion of the current branch prohibited)\nerror: failed to push some refs to 'https://milton:redacted@bitbucket.sgdev.org/scm/k8s/zoekt.git'\n"}}
```

**Comment by keegancsmith** [comment]
To unpack the error a bit :)

```json
{
  "Rev": "",
  "Error": {
    "RepositoryName": "bitbucket.sgdev.org/K8S/zoekt",
    "Err": {},
    "Command": "git push --force origin dab52aec9e62c93727235045e8657b386ec0ac23:refs/heads/sourcegraph/campaign-1581089799",
    "CombinedOutput": "remote: error: By default, deleting the current branch is denied, because the next \nremote: 'git clone' won't result in any file checked out, causing confusion. \nremote: \nremote: You can set 'receive.denyDeleteCurrent' configuration variable to \nremote: 'warn' or 'ignore' in the remote repository to allow deleting the \nremote: current branch, with or without a warning message. \nremote: \nremote: To squelch this message, you can set it to 'refuse'. \nremote: error: refusing to delete the current branch: refs/heads/master \nTo https://bitbucket.sgdev.org/scm/k8s/zoekt.git\n - [deleted] sourcegraph/campaign-1581088866\n * [new branch] dab52aec9e62c93727235045e8657b386ec0ac23 -> sourcegraph/campaign-1581089799\n ! [remote rejected] master (deletion of the current branch prohibited)\nerror: failed to push some refs to 'https://milton:redacted@bitbucket.sgdev.org/scm/k8s/zoekt.git'\n"
  }
}
```

```
remote: error: By default, deleting the current branch is denied, because the next 
remote: 'git clone' won't result in any file checked out, causing confusion. 
remote: 
remote: You can set 'receive.denyDeleteCurrent' configuration variable to 
remote: 'warn' or 'ignore' in the remote repository to allow deleting the 
remote: current branch, with or without a warning message. 
remote: 
remote: To squelch this message, you can set it to 'refuse'. 
remote: error: refusing to delete the current branch: refs/heads/master 
To https://bitbucket.sgdev.org/scm/k8s/zoekt.git
 - [deleted] sourcegraph/campaign-1581088866
 * [new branch] dab52aec9e62c93727235045e8657b386ec0ac23 -> sourcegraph/campaign-1581089799
 ! [remote rejected] master (deletion of the current branch prohibited)
error: failed to push some refs to 'https://milton:redacted@bitbucket.sgdev.org/scm/k8s/zoekt.git'
```

I have no idea why this is happening. Maybe some config is kicking in when you specify origin? IE we have mirror=true normally and a refspec on a remote specified. And if you specify the remote URL instead of origin it works? 

Can you try the command locally with some git tracing turned on? `GIT_TRACE=1 GIT_TRACE_PACKET=1 GIT_CURL_VERBOSE=1`

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.13 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
