### ISSUE TITLE
Treat .build_defs and BUILD as Bazel/Starlark files.

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#8123]
A customer https://app.hubspot.com/contacts/2762526/company/2174376075/ uses [please build](https://please.build/) which defines `BUILD` files and `.build_defs` files in Starlark (Bazel's language). Bazel [also uses `BUILD` files](https://docs.bazel.build/versions/master/build-ref.html#BUILD_files).

Today, we only treat `.bzl` as Bazel/Starlark files (both in our syntax highlighter and e.g. when using `lang:bazel` I believe), the ask here is to also treat `BUILD` and `.build_defs` files as Bazel/Starlark by default / out of the box.

Ref. https://sourcegraph.atlassian.net/jira/servicedesk/projects/SG/queues/custom/1/SG-25

**Comment by aisbaa** [comment]
+1 I also would like to see this implemented.

**Comment by slimsag** [comment]
Note: also consider .star files https://sourcegraph.slack.com/archives/CTGBWCKM0/p1587456392048500

**Comment by slimsag** [comment]
Re-prioritized to fix in 3.16 most likely.

**Comment by slimsag** [comment]
This should be fixed by https://github.com/sourcegraph/sourcegraph/pull/10374 and will be in Sourcegraph 3.16.
