### ISSUE TITLE
Code views are not detected on merge requests on gitlab.com

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#8134]
No code intelligence on code views, eg. https://gitlab.com/gitlab-org/gitlab/-/merge_requests/22932/diffs?view=inline

This is because we detect a `GitLabPageKind.Other`:

![image](https://user-images.githubusercontent.com/1741180/73448583-7d390900-4361-11ea-8589-ddc8eec7fa0e.png)

We [expect](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@b12f5679e669363e27c74f5dcb8b818478a412a0/-/blob/browser/src/libs/gitlab/scrape.ts#L46-55) the pathname to match `${owner}/${projectName}/merge_requests`, but it's `${owner}/${projectName}/-/merge_requests`. This appears to be a recent change.

**Comment by lguychard** [comment]
Commits and blobs still work.

**Comment by ryan-blunden** [comment]
I just tested https://gitlab.com/gitlab-org/gitlab/-/merge_requests/22932/diffs?view=inline and I'm not seeing code intelligence work.

The `code view added` message does not appear in the console and an error `Uncaught Error: Could not find merge request source repo link` is output.

**Comment by ryan-blunden** [comment]
Can error handling and console.error output be utilized when code views are not detected in MRs/PRs?

**Comment by lguychard** [comment]
> Can error handling and console.error output be utilized when code views are not detected in MRs/PRs?

@ryan-blunden can you clarify, I'm not sure I understand the question?
