### ISSUE TITLE
Dates in schema should use a specified format

### ISSUE THREAD

**Issue by creachadair** [sourcegraph/sourcegraph#8142]
There are a couple of places where [schema.graphql](https://github.com/sourcegraph/sourcegraph/blob/master/cmd/frontend/graphqlbackend/schema.graphql) specifies date values as type `String`. Ideally these should use a more specific type label with a format definition. The `DateTime` scalar type is defined to use RFC3339, and we could re-use that; or we could define a separate `Date` type (e.g., to be an RFC3339 `full-date`).

**Comment by felixfbecker** [comment]
I looked and the only instance I could find is `Signature.date`, which is already RFC3339 compliant, so should be possible to change without any breakage:

![image](https://user-images.githubusercontent.com/10532611/73487698-ce6beb80-43a7-11ea-8fa5-42e91451d985.png)

Did you see any other cases?

**Comment by creachadair** [comment]
There's also a [date parameter](https://github.com/sourcegraph/sourcegraph/blob/master/cmd/frontend/graphqlbackend/schema.graphql#L301) to the `resolvePhabricatorDiff` member of the `Mutation` type. Those are the only two I see with an obvious name signal for time.

**Comment by efritz** [comment]
https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:%5Ecmd/frontend/graphqlbackend/schema%5C.graphql%24+%22date:+String%22&patternType=regexp

**Comment by efritz** [comment]
Also, https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:%5Ecmd/frontend/graphqlbackend/schema%5C.graphql%24+%22time:+String%22&patternType=regexp
