### ISSUE TITLE
Unify definition of filters/suggestions in webapp

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#8151]
Currently, we define the list of valid filters in three different places: [SuggestionTypes enum](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/shared/src/search/suggestions/util.ts#L1:13), [FilterTypes enum](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/shared/src/search/interactive/util.ts#L21:13), [FILTERS list](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/shared/src/search/parser/filters.ts#L36:23) in the frontend query parser.

We should have a canonical list of filters, which makes any functionality using filters actually testable.

**Comment by lguychard** [comment]
@attfarhan is there anything left to do here besides #8577?

**Comment by attfarhan** [comment]
I think #8577 is sufficient for now, so will close this.
