### ISSUE TITLE
Warn site admins if they are not accessing Sourcegraph over HTTPS

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#8160]
Customer should configure their Sourcegraph instance to be accessible over HTTPS by following these instructions: https://docs.sourcegraph.com/admin/nginx

If we detect that a site admin is accessing Sourcegraph over HTTP (this should be easy to detect in JavaScript, right?), we should show the site admin a warning (I don't have a proposed UI/UX) and point them to the above documentation.

**Comment by unknwon** [comment]
> If we detect that a site admin is accessing Sourcegraph over HTTP (this should be easy to detect in JavaScript, right?)

I think by just checking the `externalURl` in the site config is sufficient? i.e. having prefix `http://`.

**Comment by nicksnyder** [comment]
That might be sufficient. What do you think @slimsag ?

Could be easy to add code right here:
https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/site_alerts.go#L65-67
