### ISSUE TITLE
Make read:org permissions optional / dependent upon whether `allowOrgs` is specified

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#8163]
A customer https://app.hubspot.com/contacts/2762526/company/768958849/ was surprised when they upgraded to 3.12 and it required new undocumented `read:org` permissions, which I corrected in https://github.com/sourcegraph/sourcegraph/pull/8101

They use GHE, though, and not GitHub.com where the `allowOrgs` setting would be useful -- and are hesitant to upgrade because of these new permission requirements. Questions:

Questions for @sourcegraph/core-services :

1. How hard would it be for us to make `read:org` permissions dependent upon whether the `allowOrgs` property is set, or whether or not GHE is in use, or something like that? (i.e. opt-in)
2. Assuming it is possible and there aren't implications I am not thinking of, can we commit to doing this in a specific release (so I can let them know)?

Note: I think this type of permission opt-in would generally be beneficial as we require new code host permissions in the future, as we have seen this be a mild hurdle within some organizations where changes in permissions like this require sign off from different teams, etc. I am proposing this not for a specific customer but rather because it would be beneficial for most, I believe.

**Comment by unknwon** [comment]
Technically we could and shouldn't be hard by reading configs in this `requestedScopes` function: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@master/-/blob/enterprise/cmd/frontend/auth/githuboauth/provider.go?utm_product_name=GoLand&utm_product_version=GoLand#L59:20

Not sure about side effects though. And if admin turns back on and off multiple times, that won't change what users already granted to us.

**Comment by slimsag** [comment]
Can we ask users to sign-in again after permissions changes or something? I am thinking this will particularly become a bigger problem with automation when we start asking for permissions to create PRs as well (in which case I can imagine many orgs that might not be interested in automation not wanting to grant that permission, then later maybe deciding they do want to turn it on)

**Comment by unknwon** [comment]
> Can we ask users to sign-in again after permissions changes or something?

If a user signs out and sign-in again, if desired permissions changed, I think GitHub will prompt the "grant permissions page", otherwise it redirects right back to Sourcegraph instance.

Related: https://github.com/sourcegraph/sourcegraph/issues/1126

**Comment by tsenart** [comment]
@unknwon: Could we pick this up this iteration, given we dropped some other things, would be timely for our customer.

**Comment by unknwon** [comment]
@tsenart Yep, adding to my plate.

**Comment by unknwon** [comment]
PR sent: https://github.com/sourcegraph/sourcegraph/pull/8296
