### ISSUE TITLE
Enable structural search on all sourcegraph.com repositories

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#8164]
This is the tracking issue for enabling structural search on all (i.e., uindexed) repositories.

Hit the :+1: if you're interested in this feature.

**Comment by unknwon** [comment]
I remember there was an issue (or a doc?) lists pros and cons of enabling structural search for all repos but couldn't find it anymore. Would you mind post them in this issue?

**Comment by rvantonder** [comment]
I don't think there's a good existing reference. The two main things are:

- Add support for relevant filters to unindexed structural search (we currently use the indexed search logic to take care of this, and some would be unsupported in unindexed search without some work)
- Benchmark and evaluate tradeoffs of running raw structural search versus optimizing file filtering with regex
