### ISSUE TITLE
Definition of scalar type not found in GraphQL schema

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#8183]
![image](https://user-images.githubusercontent.com/10532611/73589169-015ece00-44d3-11ea-83b1-bb7211294e08.png)

https://sourcegraph.com/github.com/sourcegraph/sourcegraph@947c0eb944c4a99dabfa7a1f2a5c3e4c9fdf673d/-/blob/cmd/frontend/graphqlbackend/schema.graphql#L701:16

Maybe it's missing the keyword `scalar` from the regex?

**Comment by creachadair** [comment]
> Maybe it's missing the keyword `scalar` from the regex?

Yes, it is, good catch. The fix is in #8315.
