### ISSUE TITLE
Search header improvements

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#8253]
On non-search-related pages:
- Discard the query in the navbar
- Hide interactive mode UI elements

This is ensure users don't think that queries are still relevant on certain pages (such as campaigns pages, which have some relationship with search), and to reduce vertical clutter.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.13 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by attfarhan** [comment]
Fixed by https://github.com/sourcegraph/sourcegraph/commit/0f9f8d2a3b48688fc6b13a92bf38619d32f78908
