### ISSUE TITLE
Browser extension doesn't work in Phabricator

### ISSUE THREAD

**Issue by lawrence-tan** [sourcegraph/sourcegraph#8275]
- **Sourcegraph version:** 3.12.5
- **Platform information:** Docker version

#### Steps to reproduce:

1. install and launch Docker version of Sourcegraph
2. add Phabricator-hosted git repository via the "Generic Git host" option
3. add Phabricator connection
4. install Chrome browser extension
5. browse to a Differential revision in Phabricator

#### Expected behavior:
Code intel to show up.

#### Actual behavior:
Nothing happens. An error is logged in the Chrome console "Uncaught Error: could not parse repo details"

This appears to be happening because of the check [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@7ac3ada581c2704aa3f6a06d6bbae48156a0b4db/-/blob/browser/src/libs/phabricator/backend.tsx#L365). The repository I'm trying to use is hosted on Phabricator, so the uri for the repository has the same host as the Phabricator webpage, and convertToDetails is never able to find a valid uri for this repository.

I was able to fix this locally by editing the javascript for the Chrome extension and removing the check against window.location.host.

Separately, it appears the logic in convertToDetails iterates through all returned uris, and uses the first one that doesn't match window.location.host. My set up had 2 disabled uris that had an older, deprecated location which appear first in the list or returned uris. I had to edit those to be the same as the current uri because Sourcegraph doesn't check the disabled field on the uri. Perhaps convertToDetails should check and skip disabled uris?

**Comment by unknwon** [comment]
cc @sourcegraph/web to triage.

**Comment by lguychard** [comment]
Thanks for the detailed report, @lawrence-tan, and sorry for the inconvenience!

I've opened a PR to fix this: https://github.com/sourcegraph/sourcegraph/pull/8286

**Comment by lawrence-tan** [comment]
Thanks for the quick turnaround!
