### ISSUE TITLE
Confused as to why supported code intel languages aren't reflected in lang search filter

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#8282]
I was confused to see that we have support for Pascal code intelligence, but there is no support for `lang:pascal` when searching, which is what I expected.

**Comment by creachadair** [comment]
It is possible I missed something when I set up the basic code intel support for Pascal. I only touched ctags and the basic intel extension—is there some other component I should have updated?

**Comment by ryan-blunden** [comment]
So I may have misspoke here. It seems Pascal has quite a few file extensions that it seems we do handle.

**Comment by ryan-blunden** [comment]
What I should have made clear in my initial description, is that not all languages that we support show up in the search autocomplete for `lang:`.  The problem is that not all languages that we support [have material icons](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@e6183fd1ab543f6ed72f2e6e1666c168e0034999/-/blob/shared/src/components/languageIcons.tsx#L26), but we could get around that by choosing a generic icon. 

The main thing is that if someone types `lang` while searching, that the list of languages shown is complete.

**Comment by lguychard** [comment]
`lang:` suggestions now show all languages.
