### ISSUE TITLE
user preferences documentation is missing

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#8291]
Where is the documentation for user preferences / settings such as `search.contextLines`? What other settings are in the user schema JSON that are not documented?

**Comment by dadlerj** [comment]
This is unfortunately a known issue, and a duplicate of https://github.com/sourcegraph/sourcegraph/issues/7707 and https://github.com/sourcegraph/sourcegraph/issues/5328

CC @ryan-blunden

**Comment by aileenrose** [comment]
no longer an issue
