### ISSUE TITLE
Perl code intelligence not working

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#8303]
Reported by https://app.hubspot.com/contacts/2762526/company/864034457

This company has a monorepo with mostly Perl. They are unable to get code intelligence on Perl files. Search is verified working and they have the Perl extension enabled.

When hovering over a token in a Perl file, they see this in the browser console:
```
hover.ts:49 TypeError: Cannot read property 'results' of null
    at r.search (3420-sourcegraph-perl.js?c09ft7py723c--sourcegraph-perl:210)
    at async R.definition (3420-sourcegraph-perl.js?c09ft7py723c--sourcegraph-perl:227)
    at async R.hover (3420-sourcegraph-perl.js?c09ft7py723c--sourcegraph-perl:227)
    at async Object.provideHover (3420-sourcegraph-perl.js?c09ft7py723c--sourcegraph-perl:253)
```

This is high priority, and it would be great to get this resolved sometime this iteration.

**Comment by dadlerj** [comment]
FYI @beyang not a big deal, but I updated this issue to remove your inline link. It's impossible to search for link hrefs when searching GitHub issues, so having the full text associated with the HubSpot URL is critical (so we can search for a company's unique ID to find all issues associated with them). 

If you ever see this in other issues, please edit them!

I'll update my PR about filing issues for companies at https://github.com/sourcegraph/about/pull/528/files to add this note.

**Comment by davejrt** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by macraig** [comment]
@beyang is this issue still relevant with the newer version of the extension?

**Comment by scalabilitysolved** [comment]
@macraig are you able to see the customer in question and whether it was resolved?

**Comment by macraig** [comment]
@scalabilitysolved customer in question seems to be inactive at the moment (I suspect their trial ended and didn't move forward). I did try to navigate perl files and didn't get any hovers so this seems to be ongoing. Example: https://sourcegraph.com/github.com/SpiderLabs/owasp-modsecurity-crs@56ff01a8408bd387fe14f7856391c48e245b7937/-/blob/util/regexp-assemble/regexp-assemble-v2.pl?utm_source=chrome-extension#L15

**Comment by scalabilitysolved** [comment]
Perl currently is <0.13% of total hovers.  I think we should close this and tackle if it comes up again @macraig .

**Comment by macraig** [comment]
Closing, will reopen if we decide to pursue Perl support.
