### ISSUE TITLE
Add search metrics for time-to-first-result

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#8306]
We want to track how long any given search takes and bring the latency under 3s for returning the first search result. This issue tracks progress for adding metrics.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.13 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by tsenart** [comment]
@rvantonder: Is this moving over to 3.14? If so, please change the milestone.

**Comment by uwedeportivo** [comment]
yes, please, i'm about to release and need to check that checkbox :-)

**Comment by rvantonder** [comment]
We are now logging latency for backend searches.
