### ISSUE TITLE
Hover tooltip syntax highlighting: need to support Perl

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#8307]
https://sourcegraph.com/github.com/ceph/ceph@d64aa0a4213a7138ddb4ca3922dc8270221defc0/-/blob/qa/workunits/rgw/s3_bucket_quota.pl#L62:5

Hover tooltips on Perl files throw this error:

![image](https://user-images.githubusercontent.com/1387653/73982179-fa7bf500-48f0-11ea-99ea-003f41e6c18c.png)

cc @sourcegraph/web

**Comment by felixfbecker** [comment]
Would you mind posting a repro link and/or the stack trace? I can't repro on https://sourcegraph.com/github.com/kazeburo/GrowthForecast/-/blob/eg/alter_for_primary.pl#L9:5

**Comment by chrismwendt** [comment]
Link to repro: https://sourcegraph.com/github.com/ceph/ceph@d64aa0a4213a7138ddb4ca3922dc8270221defc0/-/blob/qa/workunits/rgw/s3_bucket_quota.pl#L62:5

**Comment by felixfbecker** [comment]
Looks like the perl support for highlight.js is not imported (this needs to be done whenever codeintel support for a new language is added, because we cherry-pick the languages for bundle size optimization)

**Comment by felixfbecker** [comment]
Clarified title that it only affects hovers (not file contents)
