### ISSUE TITLE
observability: Add monitoring for when zoekt indexing fails on repos

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#8309]
Such as in cases like https://sourcegraph.atlassian.net/browse/SG-48

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by pecigonzalo** [comment]
@slimsag I believe this should be assigned to the Search team.
