### ISSUE TITLE
Improve Sourcegraph quickstart guide

### ISSUE THREAD

**Issue by mmeeshari** [sourcegraph/sourcegraph#8316]
> ``docker run --publish 7080:7080 --publish 127.0.0.1:3370:3370 --rm --volume ~/.sourcegraph/config:/etc/sourcegraph --volume ~/.sourcegraph/data:/var/opt/sourcegraph sourcegraph/server:3.12.5

**Comment by mmeeshari** [comment]
> ``docker run --publish 7080:7080 --publish 127.0.0.1:3370:3370 --rm --volume ~/.sourcegraph/config:/etc/sourcegraph --volume ~/.sourcegraph/data:/var/opt/sourcegraph sourcegraph/server:3.12.5

**Comment by christinaforney** [comment]
Hi @mmeeshari - we'd love your feedback on what we could do to improve the quickstart guide. Unfortunately, the above command does not clarify what we could do to improve. I'm going to close out this issue, but if you do have some actionable feedback for us, please update the description and let me know!
