### ISSUE TITLE
search: design proposals for AND / OR / NOT expressions

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#8346]
A subtask of #7823 is to define the constraints and behaviors for implementing AND / OR / NOT expressions. The progress on this task so far is:

- A design proposal for the Query Predicate Language, [RFC 94](https://docs.google.com/document/d/1nYv_p1138eHsN7WOw0s3x69Y0HK2L8x7VP-nFKQGal8/edit?ts=5e2845ae#heading=h.trqab8y0kufp)
- A proposal to change literal search so that we can support the query predicate language universally, [RFC 108](https://docs.google.com/document/d/1k19NAYyhGWt7X0Ktnqt0WbNzx61htNrhvoEquyRDZVQ/edit#). This RFC is abandoned and we will not implement AND / OR expressions for literal search initially due to conflicting design decisions in the input representation.

**Comment by tsenart** [comment]
@rvantonder: Was this done in 3.13? If so, can you add the milestone and close it?
