### ISSUE TITLE
AWS CodeCommit error MaximumRepositoryNamesExceededException

### ISSUE THREAD

**Issue by lalau** [sourcegraph/sourcegraph#835]
- **Sourcegraph version:** 2.13.0
- **Platform information:** localhost Mac OSX 10.12.6, Docker version 18.09.0-ce-beta1, build 78a6bdb, Google Chrome 70

#### Steps to reproduce:

1. Enter AWS CodeCommit config

#### Expected behavior:

Load AWS CodeCommit repos

#### Actual behavior:

Following error is logged in docker:
```
19:33:57   repo-updater | t=2018-11-06T19:33:57+0000 lvl=eror msg="Error listing AWS CodeCommit repositories" error="MaximumRepositoryNamesExceededException: repositoryNames has too many repository names.  Maximum allowed is 25\n\tstatus code: 400, request id: e7877e0a-e1fa-11e8-a717-a31dc9b4bb1a"
```

According to [aws doc](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/codecommit/model/MaximumRepositoryNamesExceededException.html), the limit is 25 currently.

I suspect the following code is causing the error, which is trying to list 50 repos at a time:
https://github.com/sourcegraph/sourcegraph/blob/2d0f5738113ae3ae926d0ae530dd47daf400a21f/cmd/repo-updater/repos/awscodecommit.go#L311

**Comment by nicksnyder** [comment]
This fix was just released as 2.13.2
