### ISSUE TITLE
Improve discoverability of LSIF indexer installation instructions

### ISSUE THREAD

**Issue by creachadair** [sourcegraph/sourcegraph#8351]
Improvements for https://docs.sourcegraph.com/user/code_intelligence/lsif_quickstart suggested by @beyang (with minor redactions for clarity).

- Add the links to individual language indexer installation instructions in that page itself, instead of linking to lsif.dev, which has inconsistent styling and doesn't communicate clearly what the next steps should be. Also, people are going to ctrl-F and search for their specific language, and if that language name doesn't appear anywhere, they may assume it's unsupported.
- Ideally [the quickstart guide] should be shorter, more specific, and less daunting. Consider writing up separate docs for each language, and adding troubleshooting tips specific to each language. 

We did this for configuring authN providers (https://docs.sourcegraph.com/admin/auth/saml). It increased the volume of docs, but it made each individual doc page shorter and easier to understand (and a customer is going to configure these 1 at a time anyway, so they got much shorter from the customer's POV)

[Original Slack thread](https://sourcegraph.slack.com/archives/CHXHX7XAS/p1581382370209100?thread_ts=1581378102.203200&cid=CHXHX7XAS)

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by aidaeology** [comment]
Superseded by: https://github.com/sourcegraph/sourcegraph/pull/13041
