### ISSUE TITLE
Phabricator integration raises exception: ERR-INVALID-AUTH

### ISSUE THREAD

**Issue by aisbaa** [sourcegraph/sourcegraph#8357]
- **Sourcegraph version:** 3.9.4-1
- **Platform information:** Chrome 80.0.3987.87

I get exception in browser console: 

```
Uncaught AggregateError: ERR-INVALID-AUTH: API token "api-xxxxxxxxxxxxxxxxxxxx" is not valid.
 ```

This seems to be outdated phabricator token. Is there a way to refresh it? Also I would be curious to know why it token is used at all, isn't auth cookie enough?

**Comment by unknwon** [comment]
Assigning @lguychard for triaging :)

**Comment by lguychard** [comment]
Hey @aisbaa,

> I would be curious to know why it token is used at all, isn't auth cookie enough

You're correct - the Sourcegraph frontend only uses auth cookie to make requests to the Phabricator Conduit API.

What's being surfaced here is a backend error: some graphQL requests to the Sourcegraph API will trigger Conduit requests in the Go backend, which does needs a token. That token is set in the Phabricator [code host connection](https://docs.sourcegraph.com/admin/external_service/phabricator).

**Comment by aisbaa** [comment]
Thank you, token expired.
