### ISSUE TITLE
Error in references breaks subsequent hovers

### ISSUE THREAD

**Issue by Desentso** [sourcegraph/sourcegraph#838]
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:** Windows 10, Chrome 70.0.3538.77

#### Steps to reproduce:

1. Open any C file on sourcegraph.com (I could only reproduce with C) 
2. Hover over any function
3. Click "Find references"

#### Expected behavior:
It should show the correct references. 
After that the hover features should work normally.

#### Actual behavior:
References tab says "No local references found", even though there is local references on the same file
Console throws error: 
```
An error occurred when sending LSP requests to the language server, disabling this instance of the language extension (reload the page to clear this state).  
Error: method not found at sourcegraph.commands.executeCommand.then.responses
```
After this all hovering features stop working.

**Comment by sqs** [comment]
We will be temporarily removing C support as it does not work well enough. Sorry you encountered these problems.

There is a separate issue you raised, too: a hover error causes subsequent hovers to not work. Assigned to @chrismwendt 	and retitled issue.

**Comment by chrismwendt** [comment]
The separate issue about errors preventing subsequent hovers from working was fixed in https://github.com/sourcegraph/sourcegraph-langserver-http/pull/9
