### ISSUE TITLE
Improve LSIF root boundaries

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#8383]
Specifically for detection of overlapping dumps, we may treat the following as conflicting:

- `alpha/bravo/charlie`
- `alpha/bravo/charliefoxtrot`

Because one is a prefix of the other, even though one path does not subsume the other. This may also be an issue in finding roots for closest dumps.

We could simply require that all roots end with a normalized separator to fix this issue.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by efritz** [comment]
Roots are already normalized. Closing as there's nothing to fix.
