### ISSUE TITLE
a8n: Changeset status changes from "Publishing" back to "Draft" while it's being published

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#8402]
I've created a campaign with 5 changesets and while they're all publishing, the status of two changesets changed back from "publishing" to "draft":

![branch-name-specified](https://user-images.githubusercontent.com/1185253/74438574-c8c3da80-4e6a-11ea-8d6f-61d2f190c4e5.gif)

I'm not sure yet whether that's an API or a web issue, that's why I'm assigning three of you.

**Comment by eseliger** [comment]
Hm, on first sight it looks like the bug is in the logic that determines `publicationEnqueued`

**Comment by mrnugget** [comment]
For the record, `Campaigns.ChangesetPlans` contains ONLY the `campaign_jobs` that do not have a **successfully completed** `changeset_job` yet:

https://github.com/sourcegraph/sourcegraph/blob/83a13781c31935af0a11fcc04aa035ec5cea4424/enterprise/internal/a8n/resolvers/campaigns.go#L169-L187

See the last line and the definition of `OnlyUnpublishedInCampaign` here:

https://github.com/sourcegraph/sourcegraph/blob/83a13781c31935af0a11fcc04aa035ec5cea4424/enterprise/internal/a8n/store.go#L2009-L2012
