### ISSUE TITLE
Docs page for "using Sourcegraph with a monorepo"

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#8411]
See: https://sourcegraph.slack.com/archives/C0B2RU51Q/p1581615419427200

We have had a number of calls with prospects and customers recently in which they expressed uncertainty as to whether Sourcegraph would solve their needs, given they operate out of "huge" monorepos (though the size and complexity varies widely). This list includes:

* https://app.hubspot.com/contacts/2762526/company/554275594
* https://app.hubspot.com/contacts/2762526/company/768958891
* https://app.hubspot.com/contacts/2762526/company/1749284051
* https://app.hubspot.com/contacts/2762526/company/815026279
* https://app.hubspot.com/contacts/2762526/company/416674538
* https://app.hubspot.com/contacts/2762526/company/557691596

As well as some existing customers who have to deal with this:

* https://app.hubspot.com/contacts/2762526/company/947819054
* https://app.hubspot.com/contacts/2762526/company/578600789
* https://app.hubspot.com/contacts/2762526/company/555146901
* etc...

Examples of questions we get include:
* High-level use cases for Sourcegraph when using a monorepo
* General scale/performance concerns (for search and code intelligence)
* Usage of Sourcegraph with git submodules or sub-trees (how do these appear in the UI/in searches?)
* Custom git binaries, or usage of Sourcegraph with tools like git-meta
* Massive numbers of branches
* UI tweaks (e.g., "can we customize the search scopes to show submodules or branches instead of repos?")
* Etc.

Searching our docs for "[monorepo](https://docs.sourcegraph.com/search?q=monorepo&v=)" or "[monolith](https://docs.sourcegraph.com/search?q=monolith)" or "[submodule](https://docs.sourcegraph.com/search?q=submodule&v=)" doesn't return anything useful on this topic.

Happy to answer any questions about this ask!

**Comment by tsenart** [comment]
@keegancsmith: Assigned this to you since it has a lot of overlap with the work you're doing for https://app.hubspot.com/contacts/2762526/company/554275594

**Comment by tsenart** [comment]
We can estimate it tomorrow in our triaging session.

**Comment by beyang** [comment]
Re: submodules, submodules appear in the file navigation sidebar. When the user clicks on them, it takes them to the submodule repository. Here is a 
 test repository with many submodules to give you an idea of how it looks: https://sourcegraph.com/github.com/sgtest/many-submodules.

I don't believe we have any special facilities for submodules when it comes to search (e.g., no search scopes that let you scope a search to submodules of particular repository).
