### ISSUE TITLE
Update docs for "Adding repositories already cloned to disk"

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#8412]
Needed for:
* https://app.hubspot.com/contacts/2762526/company/554275594

A prospect was confused by our docs at https://docs.sourcegraph.com/admin/repo/add_from_local_disk — seems like they haven't been updated in a _long_ time (they refer to "enabling" a repo). 

@uwedeportivo was also confused and unable to get it working.

This page probably just needs a quick refresh.

**Comment by tsenart** [comment]
Pro-tip: Batch docs work to get into the flow :)
