### ISSUE TITLE
Interactive mode filters have trouble with double quotes

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#8418]
So, there's some trouble with the below behaviors. I expect that instead of the below, either of the following happens:

- My input gets quoted automatically (so `file:"` turns into`file:"\""`)
OR
- My input is invalid (if I put a `"` I get an error)

I would prefer the former, but either way what ends up happening with these inputs currently is weird and unexpected. Don't get me wrong, I like interactive search (especially if we do the quoting automatically in the raw input), just think we should be careful about validating the inputs. The following may seem contrived, but if we provide `content:` it is reasonable that a user might want to search for `"`, in which case we must ensure that quote the pattern for the user, or error on `"` entry and warn them that they need to quote the pattern themselves. 

![quotes-1](https://user-images.githubusercontent.com/888624/74509627-3bf73c00-4ebf-11ea-98c7-2f282e69707f.gif)

In the above case, putting a single double quote for `repo`, and then a single double quote for `file` merges the pill and assigns the value `" file:"` to the repo filter.

![quotes-2](https://user-images.githubusercontent.com/888624/74509631-3f8ac300-4ebf-11ea-866d-ef28acd32427.gif)

In the above case, `">""` doesn't create a UI filter image at all, and ends up searching for `"`.  What happens is that this turns into the query `file:">" "`

**Comment by lguychard** [comment]
@attfarhan tentatively adding this to 3.14, as it seems valuable.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.14 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by attfarhan** [comment]
@rvantonder it seems like the content field has trouble with quotes more generally. For example, if I type in a [query `content:"`](https://sourcegraph.com/search?q=content:%22&patternType=literal) or [query `content:"""`](https://sourcegraph.com/search?q=content:%22%22%22&patternType=literal) in non-interactive mode, it fails to search. If I escape that quote, the query works as expected. But I'd expect that I should be able to search for `\"` exactly using `content`.

I opened https://github.com/sourcegraph/sourcegraph/pull/9301 to fix the single quote case, but not sure if this solution needs to be generalized further.

**Comment by rvantonder** [comment]
> query content:" or query content:""" in non-interactive mode, it fails to search

This is expected, since any time a `filter:` is used, and starts with a quote, then it must be a well-formed _quoted_ string. Literal search doesn't require quoting. Using `content` _must_ have a well-formed quoted string (i.e., escaped) _if_ it starts with a `"`. This is why escaping the inner quote works.

> But I'd expect that I should be able to search for `\"` exactly using content

You can search for `\"` exactly by making sure it is a well-formed quoted string. To wit:

[`content:"\\\""`](https://sourcegraph.com/search?q=content:%22%5C%5C%5C%22%22&patternType=literal)

And, you can even search for `\"` without quotes, so long as you escape it:

[`content:\"`](https://sourcegraph.com/search?q=content:%5C%22&patternType=literal)

Why does it need to be escaped? Precisely because the grammar allows filters to accept quoted values like `file:"foo"`. For literal search patterns without filters, this is not required or handled in the grammar.

I haven't had a look at the implementation handling yet (will tomorrow), but it should possible to express and handle all well-formed inputs with the correct amount of quoting/unquoting.

**Comment by rvantonder** [comment]
The gist is: if a user enters `\"` in the interactive UI box, it should be escaped for them (the escaped string will become `\\\"`). Then quoting that value, you wind up with `"\\\""`, and can express `content:"\\\""` as above. It's a mechanical transformation that will work for any input.

**Comment by attfarhan** [comment]
Got it, I understand the ONE double quote case.

What would you expect to happen if you entered `"""` into the content filter input? Do you expect it to be interpreted as `"\""` or `"\"\"\""`? Right now, when we see quotes at the beginning and end of a string, we interpret it as "The user knows what they're doing, and these quotes represent delimiters". So to be consistent with current behavior, we would interpret it as `"\""`. 

Alternatively, we could make the assumption that the user _never_ intends to add quotes around their query, and always interpret any quotes passed into the input as a character to be matched. This actually seems more in line with the behavior the content filter input should have.

**Comment by lguychard** [comment]
> Alternatively, we could make the assumption that the user never intends to add quotes around their query, and always interpret any quotes passed into the input as a character to be matched. This actually seems more in line with the behavior the content filter input should have.

I would personally find this better:
- It makes the behaviour of filter inputs consistent. Having one "magical" case where we don't escape and you would have to escape yourself if you meant to match the quotes, which is potentially confusing.
- It ensures that the filter values are always valid: currently [`isQuoted()`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@04eafa7b97355240c0a1f6207526187d9b1df3a6/-/blob/shared/src/util/strings.ts#L43-50) fails to realize that `"foo":  "bar"` is not a valid quoted filter value, and the resulting search behaviour (only searching for `foo`) is confusing. Always escaping removes this problem.
- The escaping is reflected in the UI, so this behaviour is discoverable for the user:

![image](https://user-images.githubusercontent.com/1741180/77524594-e5026080-6e87-11ea-8636-80914b7eacfa.png)

**Comment by rvantonder** [comment]
I agree with @lguychard. I mentioned this in the beginning of the PR:

> I would prefer the former, but either way what ends up happening with these inputs currently is weird and unexpected.

The former being the `Alternatively,' approach @attfarhan describes here, corresponding to `"\"\"\""`. Part of this is motivated in #9016.

Like, `content` _exists_ as an escape hatch so that it's possible to unambiguously specify the search pattern. This is _not_ true for literal search patterns without `content`. There are things that are inexpressible in literal search patterns, and will never be expressible due to our simplifying assumptions (leading whitespace, I can give you a list). With `content:`, every single input is expressible, including things like leading whitespace. All the UI needs to do is make sure it escapes special characters in user input that goes in the box (`"` and `\`). Then our job is to put that escaped value in quotes, and use `content:`.

It is a _huge_ benefit that users do not need to escape or quote search patterns when using these filters in interactive mode (it's especially useful for `content`, due to the nature of search patterns, but this benefit holds for all of our filters).  It is also the only reason I personally think Interactive mode adds value. If interactive mode is just a cosmetic thing with convenient buttons, I personally wouldn't use it. If the input buttons/fields takes care of quoting and escaping for me, it's a winner.

There is a one-to-one, mechanical mapping from unquoted strings to quoted ones and vice versa for search patterns _as long as_ `content`: _is used_, like in @lguychard's example. We can _always_ display the original value back to the user when they edit it. All we do is unquote/unescape. This mapping does not exist if we don't wrap the string with `content`, because of the assumptions on search pattern/grammar in literal mode, etc. otherwise.

**Comment by attfarhan** [comment]
Thanks for the feedback, helps a lot!

**Comment by rvantonder** [comment]
Yay, it works! See, so now I don't have to quote my structural queries any more because I can use the content filter: https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+content:%22func+%28:%5B1%5D%29+Insert%22&patternType=structural

Just an addendum: I now feel conflicted because I don't really want use the search bar any more, because there, in interactive mode, we don't automatically quote the input. I don't know what the plan is for this (likely we should be thinking of doing the same to input in the search query bar), but we haven't made a commitment to what the search bar should be doing. Boils down to the same discussion in #9016, but with this change, the `content` filter becomes strictly more convenient than the search bar :)
