### ISSUE TITLE
Docs: SSL setup for Docker Compose

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#8429]
Requested by https://app.hubspot.com/contacts/2762526/company/947819054

We received the message below — looks like our docs just need to be updated in a few places for the new deployment option:

> He,
>  
> I had a quick question about getting SSL setup on the docker-compose instance.
>  
> Based on https://docs.sourcegraph.com/admin/ssl_https_self_signed_cert_nginx
>  
> 1. get crt and key file, We have an internal method of getting ssl certs, so I’ll use that rather than mkcert
> 2. Update`~/.sourcegraph/config/nginx.conf` per the instructions
> 3. Update the docker-compose? The instruction on the site seem geared to a single docker instance, so are there different instructions for docker compose?

**Comment by beyang** [comment]
@ggilmore please re-open if this is still an issue.
