### ISSUE TITLE
Selective custom repository fetching

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#8434]
This is deal-blocking for https://app.hubspot.com/contacts/2762526/company/554275594

## Background

A recent change 8cd1419f4d5c1e0527f2893c9422f1a2a435116d added the ability to override the repository contents update command (`git fetch`) with a custom one.

The customer would like the ability to configure this override on a per-repo basis. They have one special repository for which they would like to use the custom fetch command, but the others are vanilla Git repositories and the special fetch command does not work for them.

## Proposal

Enable selective customization of the git fetch command. I think the easiest way to accomplish this would be to add a field to experimentalFeatures that describes a map from repo name to custom fetch command. E.g.,

```
"git.customFetch": {
  "git.company.com/foo/bar": "git custom fetch"
}
```

This site config field could be read in gitserver, instead of the environment variable `SRC_GITSERVER_CUSTOM_FETCH`.

**Comment by dadlerj** [comment]
Should this be closed @uwedeportivo ?

**Comment by beyang** [comment]
@uwedeportivo please re-open if still an issue
