### ISSUE TITLE
Campaign progress is "Creating changes" even when updating a Campaign

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#8438]
See screenshot:

<img width="623" alt="Screen Shot 2020-02-17 at 11 06 28" src="https://user-images.githubusercontent.com/1185253/74643861-b355f580-5175-11ea-9c56-6c278b49a64a.png">

It would be great if the text could be "Creating changesets on code hosts" when creating a Campaign and "Updating changesets on code hosts".

If it's not possible to determine between the two states (whether changesets are being updated or created for the first time), let me know.

**Comment by eseliger** [comment]
Hmm what would you say would be the wording for the following cases:

```
Existing campaign: 
3 published, 3 unpublished changesets
New campaign plan diff:
1 published closed, 1 published updated
```
the above case might be covered off by updating since a "close" can be interpreted as an update(?) 

```
Existing campaign: 
3 published, 0 unpublished changesets (fully published, => no draft)
New campaign plan diff:
1 published closed, 1 published updated, 2 new published
```

This case would be more of `Updating 0/2, Creating 1/2`, though this would get rather complex with the progressbar 🤔

**Comment by mrnugget** [comment]
> the above case might be covered off by updating since a "close" can be interpreted as an update(?)

Agree. I would say say "Updating" is fine for all operations that result from a campaign update.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by mrnugget** [comment]
Invalid with the new workflow.
