### ISSUE TITLE
CI steps fail when installing cypress even though they don't need cypress

### ISSUE THREAD

**Issue by ijsnow** [sourcegraph/sourcegraph#844]
Multiple steps are failing due to errors thrown when trying to download cypress. See this build https://buildkite.com/sourcegraph/sourcegraph/builds/22852#f174776e-684f-4980-b1fc-556ff588f917.

Cypress shouldn't be installed on each step. [See how it was done before with Travis CI.](https://github.com/sourcegraph/browser-extensions/blob/master/.travis.yml)

**Comment by chrismwendt** [comment]
Fixed in https://github.com/sourcegraph/sourcegraph/pull/850
