### ISSUE TITLE
Add query filter FieldTypes map to frontend parser

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#8440]
In the backend query parser, we have [a map that specifies the `FieldType` of each query filter](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@88aa4903f0bdd186ead419e48a473cfcbe9dfc4a/-/blob/internal/search/query/searchquery.go#L49-90). 

This would be very useful in the frontend parser, and so we should add it. It'll also help us ensure consistency between the frontend and backend behaviors.

**Comment by rvantonder** [comment]
FYI that validation/typing is/will be subsumed by the new and/or [validation routine](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@5683769a4fbf20624372c1c13947cad1b863ef95/-/blob/internal/search/query/validate.go#L184-312), which is not as duplicative and also self-contained (not just definitions, but also the checks associated with the properties).

**Comment by lguychard** [comment]
Frontend validation of search queries has evolved a lot since this issue was opened.
