### ISSUE TITLE
Expose GitHub type in ExternalServices API

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#8444]
A temporary fix for the GitHub type detection was merged in https://github.com/sourcegraph/sourcegraph/pull/8426 in the long run it would be beneficial though if the distinction between those two services would have happened on the data layer already

**Comment by tsenart** [comment]
We do exactly the same thing in the backend as what was done in #8426. We don't distinguish between Github Enterprise and Github.com, so that fix is fine I believe.
