### ISSUE TITLE
New repositories are not cloned when `disableAutoGitUpdates` is true

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#8458]
Reported by https://app.hubspot.com/contacts/2762526/company/464956351.

After upgrading from 3.8 to 3.9, the customer noticed that newly added repositories were not being cloned by repo-updater. The custer had `disableAutoGitUpdates` to true. The repo-updater queue was null when we examined the repo-updater debug server (`http://localhost:6060/repo-updater-state`).

In the 3.8, the customer believes new repositories were getting cloned. The evidence for this is that the customer had 2 servers. One was upgraded earlier and had a larger queue size (~20k) than the one that was upgraded later (7k). The new repositories were added when both servers were still on 3.8.

**Comment by keegancsmith** [comment]
Will take a look at this tomorrow. Good find.

**Comment by keegancsmith** [comment]
I investigated this, and at least from what I can tell we wouldn't enqueue clones from 3.8 either. We would enqueue a clone if the repo was visited / webhook though. Is it possible something changed with the webhooks?

Either way this is a mini feature request to support this behaviour. I estimate half a days work. Asking the customer for an understanding of prioritisation.

**Comment by aisbaa** [comment]
Interesting, in that case I do not know how part of the repos did get cloned. Maybe one of bots using sourcegraph tried to access these repos.

**Comment by keegancsmith** [comment]
Part of me thinks that if `disableAutoGitUpdates` is true, we shouldn't automatically clone. I also believe that once we fix #8501 (should be soon) you will be able to run our update scheduler again. Given that I am going to close this out and can re-open if we need to revisit adding this feature.

FYI I did some spelunking on the code and we may have supported what you are saying in 3.0.1 (and later). When I did my testing I was testing against GitHub as the code host, but we had some special casing for the "other" git code host (ie gitolite). I haven't confirmed that, but you may indeed be correct (or you had some bots :) )

Please feel free to re-open.
