### ISSUE TITLE
Code intelligence tracking issue 3.14

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#8476]
**Nick**
- [ ] Finalize this tracking issue

**Eric**
- [ ] TODO

**Michael**
- [ ] TODO

**Comment by creachadair** [comment]
Should this supersede https://github.com/sourcegraph/sourcegraph/issues/8457 then?

**Comment by efritz** [comment]
I'm going to close this one in favor of #8457.
