### ISSUE TITLE
LSIF client/server: Name parameter struct types in exported Go APIs.

### ISSUE THREAD

**Issue by creachadair** [sourcegraph/sourcegraph#8500]
Context: https://github.com/sourcegraph/sourcegraph/pull/8496#discussion_r381403424

There are several places in the LSIF Go code where we have exported methods of a type that take an anonymous struct pointer as argument. Those cases should either be unpacked explicitly or given names. As written now, every call site has to be updated when any change is made to the parameter of any of these methods. This style is not just unidiomatic for Go, but an actively hostile API surface. 

Give these names and fix up the existing uses.

**Comment by efritz** [comment]
I think the point was (at the time I was told to use this idiom) that adding additional parameters to a function will break all callers as they are passing the wrong struct shape instead of simply passing a zero value for the new field.

I think that side-effect is valuable.

**Comment by creachadair** [comment]
I understand that concern, but I think it is misplaced, and in any case is _not_ common practice in Go code. There are two separate issues folded together in using this approach: One of API design, and one of maintenance.

Anytime we make a breaking API change, e.g., such as adding a new required parameter, we are going to have to update caller sites regardless. That's true whether we are using struct types or positional parameters, regardless whether the struct is named.

However, when we are _not_ making a breaking API change, which should be the norm, the API should not require the caller to type the entire type signature of the structure at every call site. 

As a rule, we shouldn't use the language in an unnatural way simply to work around limitations of the static type system. The type system is not intended to express "required-ness" in field values, and so we shouldn't be trying to hack it.  In cases where we can't (for whatever reason) update all the callers the right solution is to make the method report an error for (semantically) invalid field values.

**Comment by unknwon** [comment]
FYI I think this pattern exists not just for code-intel code, basically many places in the "graphqlbackend". The issue title could be more general if we want to tackle all at once. I do not think by giving these anonymous structs a name will break any consumer (may have some edge cases). 

I was surprised when I first touched the package TBH.

**Comment by keegancsmith** [comment]
This pattern exists in our codebase due to the graphql package we use. It uses introspection to match up methods with a graphql schema (so much be exported). I would be happy to explore a different graphql package. I agree that unless this is for graphql this is not a great pattern to use.

**Comment by creachadair** [comment]
> This pattern exists in our codebase due to the graphql package we use. It uses reflection to match up methods with a graphql schema (so [must] be exported).

That makes sense, and thank you for the context. In that case I may start with a simpler mitigation, and add some documentation to that effect in the files where this is relevant. That's quick and easy and will help new folks coming to the codebase avoid heart attack. 😁 I still think it'd be worth naming those argument types, but it does make sense that the stubs are, in effect, generated code.
