### ISSUE TITLE
repo-updater: Updates every repository on every syncer sync

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#8501]
A customer complained that every repository was being "git fetched" even though the UpdateSchedule had a much later interval. I believe the problem is that we enqueue the repository onto the update queue every time we run the repo metadata  syncer!

The fix may be as simple as removing this line https://github.com/sourcegraph/sourcegraph/blob/b02024dc415af27008d42a9811fe119574cce2a9/cmd/repo-updater/repos/scheduler.go#L262-L263

A new repository should be enqueued by the scheduler, so we should still clone new repositories. (This will need to be tested). The only other thing upsert needs to do is update the remote URL on the update queue if it has changed.

Context: Our git scheduler has two parts. The `schedule` and the `updateQueue`. The `updateQueue` is consumed and issues `git fetch`/`git clone` against gitserver. `schedule` stores all repositories and periodically puts items into the `updateQueue` to actually be updated. The upsert function linked to above is how the scheduler/updatequeue is informed of the list of repositories.

See https://github.com/sourcegraph/customer/issues/31
This may also explain the issues seen with enabling `autoGitUpdates` at https://github.com/sourcegraph/sourcegraph/issues/8458. So is likely closely related to the graphs seen in https://github.com/sourcegraph/sourcegraph/issues/8400#issuecomment-587813653

**Comment by slimsag** [comment]
Can someone with context comment when this regression occurred? If it is a recent regression then we can consider notifying customers not to upgrade until we release a patch, if it's been ongoing for several versions then likely it is not a problem

**Comment by keegancsmith** [comment]
I just checked out 3.10 and the same problem exists from reading the code. I then checked out 3.8 and it has the same issue. I would almost expect this problem has existed for a _very_ long time, it's just large scale customers worked around it by adjusting the concurrent git clones / disabled auto git update or had a code host who could handle the git traffic.

**Comment by tsenart** [comment]
This is the commit that introduced the regression: https://github.com/sourcegraph/sourcegraph/commit/29f961a5fcaf943a18de2853baf776a2fa150613?w=1

I squashed the update and add logic into upsert, and that was wrong for repos that were only modified.

**Comment by unknwon** [comment]
@keegancsmith:
> The only other thing upsert needs to do is update the remote URL on the update queue if it has changed.

After working on the issue, I think this is not a problem? We update whatever in the queue with a new `configuredRepo2`, and it contains a URL field which I suppose it is the remote URL?
