### ISSUE TITLE
Cannot enable Codecov extension on private repository

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#852]
Source: https://twitter.com/munchybunch/status/1059907028951359493

> We followed the instructions (including API token for private repo) but just see "Configure Sourcegraph" on our private PRs, any way to troubleshoot that? Confirmed working on public repos.

@joshma can you verify you have the following:
* A private Sourcegraph instance running (https://docs.sourcegraph.com/)
* The URL of the personal instance is configured in your Chrome extension (click the Sourcegraph Chrome extension icon to go to the settings page).
* Codecov works on https://github.com/theupdateframework/notary/blob/fb795b0bc868746ed2efa2cd7109346bc7ddf0a4/server/storage/tuf_store.go

**Comment by joshma** [comment]
@chrismwendt You're right, we don't have a private sourcegraph instance - we actually aren't sourcegraph users right now :x - and are hoping to get codecov highlighting on PRs.

What form of background colors are you referring to? I see green highlighting at https://github.com/theupdateframework/notary/blob/fb795b0bc868746ed2efa2cd7109346bc7ddf0a4/server/storage/tuf_store.go

![image](https://user-images.githubusercontent.com/64739/48099937-28e2c000-e1d6-11e8-917b-f204b4101a5d.png)

I'm hoping to see that for our own repos - we don't see a `Coverage: XX%` button at all.

**Comment by joshma** [comment]
Hm so I:
- Inspected background page, cleared console
- Refreshed a github PR

Got the following (doesn't seem to have any errors):
![image](https://user-images.githubusercontent.com/64739/48101185-0901cb00-e1db-11e8-842e-0ca25da1a257.png)

Is there a way to see if it's even attempting to pull data from codecov? (I suspect codecov but have been having a hard time getting in touch with their support.) The PR has since been closed and its page on codecov.io isn't loading. (But I did expect to see an error or a "no coverage" note of some kind.)

**Comment by joshma** [comment]
For what it's worth, I get this on the console of the PR itself (not the background page):
![image](https://user-images.githubusercontent.com/64739/48101356-79a8e780-e1db-11e8-9541-3ba8787934f3.png)

**Comment by chrismwendt** [comment]
You can check the Network tab to see if any requests are going to codecov.io

You could try disabling every other extension and see if it works.

**Comment by joshma** [comment]
Confirming that I see requests going to codecov.io when I'm on a public repo but not on the private repo.

I do think the `Uncaught h: no sourcegraph urls are configured` error is related actually - is it crashing the call so that it gives up after that?

(I'm on Version 2.0.0 of the sourcegraph extension - looks like the latest in the marketplace.)

**Comment by beyang** [comment]
@chrismwendt I can repro on my own private repo. Want to debug together sometime this afternoon?

**Comment by chrismwendt** [comment]
@beyang Great, yeah feel free to ping me when you're available.

**Comment by ijsnow** [comment]
Hmmm, definitely thought that was flipped to the default a long time ago. It should be removed . I can deploy that today. 

Currently, the only way to toggle that would be to:

1. Go to chrome://extensions
2. Enable developer mode in the top right
3. Click background page for the Sourcegraph extension
4. Run the following in the console

```
chrome.storage.sync.get('featureFlags', ({featureFlags}) => chrome.storage.sync.set({featureFlags: {...featureFlags, newInject: true}}))
```

**Comment by beyang** [comment]
^ @joshma do Isaac's instructions for enabling the extension by toggling the feature flag work for you?

**Comment by ijsnow** [comment]
I'll merge the fix and release it soon https://github.com/sourcegraph/sourcegraph/pull/891.

**Comment by ijsnow** [comment]
Deploying right now. Reopened so that we can confirm this isn't an issue anymore.

**Comment by ijsnow** [comment]
Version 2.0.4 should be on the Chrome store within an hour! You won't have to do the steps above to see if this is fixed.

**Comment by joshma** [comment]
Thanks for the continued help folks. Here's what I see now:
1. "Use sourcegraph extensions" was disabled after the update, so I re-enabled it
2. When I load a private PR, I don't see coverage still, but I do see new errors!

From the page's console:
```
inject.bundle.js:1 Uncaught g: A ResolveRev GraphQL request to the public Sourcegraph.com was blocked because the current repository is private.
    at p (chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/js/inject.bundle.js:1:150317)
    at f (chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/js/inject.bundle.js:1:151335)
    at e (chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/js/inject.bundle.js:1:155543)
    at chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/js/inject.bundle.js:1:166290
    at t.Object.pipe.e [as project] (chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/js/inject.bundle.js:65:788530)
    at t._next (chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/js/inject.bundle.js:1:12596)
    at t.next (chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/js/inject.bundle.js:1:71843)
    at t._next (chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/js/inject.bundle.js:1:1297)
    at t.next (chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/js/inject.bundle.js:1:71843)
    at t._next (chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/js/inject.bundle.js:1:1297)
```

From the background page console, I don't see a codecov.io request.

**Comment by joshma** [comment]
Also, when I try to set my codecov API token, the GH command palette only shows 1 item:
![image](https://user-images.githubusercontent.com/64739/48234558-e9031080-e36e-11e8-99d1-818f2a1c7488.png)

**Comment by chrismwendt** [comment]
Great, I filed a feature request for line decorations on PR/diff pages https://github.com/sourcegraph/sourcegraph/issues/911

**Comment by beyang** [comment]
Closing in favor of https://github.com/sourcegraph/sourcegraph/issues/911
