### ISSUE TITLE
onboarding confetti hidden by other layers in web UI

### ISSUE THREAD

**Issue by uwedeportivo** [sourcegraph/sourcegraph#8527]
- 3.13 
- observed on single docker, k8s and dev/start.sh

#### Steps to reproduce:

1. start instance, as admin allow signups
1. add some repos to have something to search
1. signup as new user
1. do search
1. do 'find references' in some source code 

#### Expected behavior:

first search and first 'find references' should trigger confetti

#### Actual behavior:

confetti is not visible

![confetti-appears-after-find-refs](https://user-images.githubusercontent.com/534011/74966241-90248380-53cb-11ea-8b0b-1cd3c5ba30bc.png)

![confetti-appears-after-first-search](https://user-images.githubusercontent.com/534011/74966252-974b9180-53cb-11ea-99bf-82b3163cc2c1.png)

**Comment by lguychard** [comment]
This is a small tweak that would be nice to fix, let's get it done in 3.14

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.14 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
sorry i'm opening it again :-). could you please double-check:
i ran it with web/src/regression/onboarding.test.ts and the first find reference did show confetti, the first search did not. 
![confetti-appears-after-find-refs](https://user-images.githubusercontent.com/534011/77005625-58532200-691e-11ea-9ec7-01b9e32a3047.png)
![confetti-appears-after-first-search](https://user-images.githubusercontent.com/534011/77005642-5e490300-691e-11ea-96f8-b6ac426e95b2.png)

close it if it's not legit, thanks

**Comment by lguychard** [comment]
@uwedeportivo I tried to reproduce on my end and saw confetti in both cases...

**Comment by uwedeportivo** [comment]
perfect
