### ISSUE TITLE
e2e test runner doesn't respect -t anymore

### ISSUE THREAD

**Issue by uwedeportivo** [sourcegraph/sourcegraph#8538]
- 3.13
- dev/start.sh

#### Steps to reproduce:

1. start an instance
1. follow web/src/regression/README.md to set up your e2e env
1. run a target with -t argument (like test:regression:search -t 'Global text search, fork:no, 0 results')

#### Expected behavior:

it should only run that one test

#### Actual behavior:

it runs all of them

**Comment by lguychard** [comment]
We moved from Jest to [Mocha](https://mochajs.org/) for e2e and regression tests: https://github.com/sourcegraph/sourcegraph/pull/7872

Mocha supports the `--grep` flag to filter tests by name, similar to Jest's `-t`.

**Comment by uwedeportivo** [comment]
got it, thanks. i figured that must be the reason. i'll update the docs, issue templates and then close this.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.14 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
i updated the docs
