### ISSUE TITLE
RFC 132: Expose configurable rate limiter for external services

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#8546]
See RFC 132 for details

We'll need to expose rate limiters for each of Github, GitLab and BitbucketServer via a new interface on Source.

**Comment by ryanslade** [comment]
After chatting with @tsenart we also decided that whatever rate limit we use should be fed back into the changeset syncer so that we can  better estimate when to run the next job.

**Comment by tsenart** [comment]
Same would go for the perms syncer @unknwon and @keegancsmith.

**Comment by ryanslade** [comment]
@tsenart I'm going to create an RFC around the idea of a global shared rate limiter and having rate limits set per external service in config.

**Comment by tsenart** [comment]
@ryanslade: Sounds good!

**Comment by tsenart** [comment]
Same here. Please change milestone accordingly if necessary.
