### ISSUE TITLE
Add a resource estimator

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#8579]
When users come to us initially, they often ask exactly what hardware and replica counts, deployment types, etc. they will need for their $X users, $Y repositories, and $Z large monorepos. In the past we have always responded to these by either overestimating and telling the customer we were doing so with the intent of reducing resources later, or by making educated estimates based on other well-behaving deployments (e.g. this was the case in https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/74 ) -- but this takes a lot of work and effort to calculate.

There should be a way for customers and us to easily estimate the resources required, and what deploy type we would suggest, based on their users/repos/monorepos/etc.

This would supersede https://github.com/sourcegraph/sourcegraph/issues/6274 and have some overlap with existing scaling documentation which would be reduced in favor of this approach.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.14 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by slimsag** [comment]
This was added: https://docs.sourcegraph.com/admin/install/resource_estimator

The code lives here: https://github.com/sourcegraph/resource-estimator
