### ISSUE TITLE
Improved search monitoring and alerting

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#8580]
There are a number of improvements we could make to the built-in monitoring around search performance.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.14 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by slimsag** [comment]
Fixed already via "Search at a glance" on the Frontend dashboard:

![image](https://user-images.githubusercontent.com/3173176/79180947-1bb10400-7dc0-11ea-9aca-cc41bc122e5a.png)
