### ISSUE TITLE
Improve onboarding experience

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#8584]
Stub issue for improving the site admin and user onboarding experience in 3.14.

- [ ] Create RFC to:
  - [ ] provide background on problems with the current onboarding experience
  - [ ] list and link current open issues related to onboarding 
  - [ ] propose potential solutions to problems 
- [ ] [Immediate improvements to the onboarding checklist](https://www.figma.com/file/x3d9uhuknTyhKASbqwxMVg/Onboarding-(RFC-121-%2B-125)?node-id=38%3A0)

Issues:
- https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aopen+is%3Aissue+label%3Aonboarding
- https://github.com/sourcegraph/sourcegraph/issues?q=is%3Aopen+is%3Aissue+label%3Aonboarding-test-1

**Comment by attfarhan** [comment]
First draft of RFC: https://docs.google.com/document/d/1BlJcrn_nCnzSw7_2M2QG9hLABTvqLPvmhz4XCQkglhw/edit

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.14 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by attfarhan** [comment]
This wasn't that useful to keep track of onboarding updates. We should just keep planning/checklists in RFCs and make issues as we identify work to be done.
