### ISSUE TITLE
Redactor can be too aggressive

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#8586]
We've seen this in the logs:

```
00:01:55           gitserver | fatal: repository 'https://<redacted>lab.sgdev.org/sourcegraph/src-cli.<redacted>/' not found

```

**Comment by unknwon** [comment]
My 2 cents: I don't think in practice expose the system user is a problem, as it is visible as encoded in the clone URL anyway. We just need to redact the password part in the URL: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@682af2c61cbf59163a2768d880ecf1fda0ed48fc/-/blob/cmd/gitserver/server/server.go#L925

Unless... there is a use case I'm not aware of that some code hosts we support use username as the password.

**Comment by ryanslade** [comment]
With github we use `token@github.com` as the URL

So when there is no colon, we do need to redact the username
