### ISSUE TITLE
Instrument changeset syncing

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#8588]
We need observability over the changeset syncer.

I propose at least the following metrics:
* Sync rate
* Sync timings
* Sync error rate
* Queue depth, ie, how many changesets are  scheduled to be synced but haven't been
* Rate and timings for code host api requests

**Comment by ryanslade** [comment]
Part of https://github.com/sourcegraph/sourcegraph/issues/6388

**Comment by tsenart** [comment]
@ryanslade: Doing triage for 3.15. Is this (or part of this) done in 3.14? If not, please change the milestone accordingly.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
