### ISSUE TITLE
Search became slower

### ISSUE THREAD

**Issue by aisbaa** [sourcegraph/sourcegraph#8589]
#### Question description

We recently added a 25k repos (42k in total) and it seems that this has slowed down sourcegraph. Developers are complaining that search times out and/or no results are found.

- Would it help if we would scale indexed-search statefulset? Currently we are running with 1 replica.
- Is it possible to limit scope of search? I would love to sourcegraph not to search repos from few gitolite namespaces. Which I can do manually by passing `-repo:namespace-1` to query.

**Comment by dadlerj** [comment]
Hi @aisbaa, we added the ability to horizontally scale indexed search in 3.10: https://about.sourcegraph.com/blog/sourcegraph-3.10#scaling-search-for-our-largest-customers (note this requires a quick migration).

The instructions for scaling after the upgrade is complete can be found at https://github.com/sourcegraph/deploy-sourcegraph/blob/master/docs/configure.md#configure-indexed-search-replica-count. @keegancsmith is the right point of contact if you have questions about this process.

Given your instance is still on 3.9.x (correct?), this could be a big benefit of upgrading! (I may be missing context if you've already been discussing with @beyang)

As for limiting the scope of search, would you want to prevent those namespaces from being available on Sourcegraph at all? If so, the `blacklist` or `exclude` configuration options for the Gitolite external service may help here (which I believe you may already be using?): https://docs.sourcegraph.com/admin/external_service/gitolite#configuration.

**Comment by keegancsmith** [comment]
> Would it help if we would scale indexed-search statefulset? Currently we are running with 1 replica.

Yes, please adjust to two replicas (or more). indexed-search is likely currently IO or CPU bound, so adjusting the replica count should solve the issue. When adjusting it will take some time for the new replica to index all the new repos. However, it shouldn't take down indexed search while indexes move over. You can expedite the process by using a disk snapshot of indexed-search-0 on indexed-search-1.

> Is it possible to limit scope of search? I would love to sourcegraph not to search repos from few gitolite namespaces. Which I can do manually by passing -repo:namespace-1 to query.

You can look into our [Search Scopes](https://docs.sourcegraph.com/user/search/scopes) feature if you wish to still include these repositories. If they are never useful to search there is blacklist and exclude. If that doesn't fit your needs, it would be great to understand more so we can improve your search experience.

**Comment by keegancsmith** [comment]
Oh as @dadlerj noted, you need to be on 3.10 or greater for horizontal sharding of indexed search.

**Comment by keegancsmith** [comment]
@aisbaa any luck with scaling indexed search?

**Comment by aisbaa** [comment]
I'm increasing number of indexed-search replicas right now. I think I can close this issue. Thank you for your guidance.
