### ISSUE TITLE
User can't add repositories through GraphQL API

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#859]
- **Sourcegraph version:** 
- **Platform information:** 

#### Steps to reproduce:

A user reported that using our API to add repositories wasn't working for them. They tried the following mutation:

```
mutation{
configurationMutation(input: {subject: "VXNlcjox", lastID: 1}) {
overwriteConfiguration(contents: "repos.list:[{url:file:///var/opt/sourcegraph/repos/gerrit/proctool/jenkins-jobs, path:jenkins-jobs}]") {
empty {
alwaysNil
}
}
}
}
```

They indicated that they got this by copying the mutation done in `graphqlbackend/configuration_test.go`

The documentation indicated to them, regarding the AddRepository migration: 

> "To add arbitrary repositories (that don't need to reside on an already configured code host), use the site configuration "repos.list" property."

They also tried this query, but got no response:

```
mutation{
configurationMutation(input: {subject: "VXNlcjox", lastID: 6}) {
editConfiguration(edit : {keyPath: [{property: "repos.list"}], 
value: "bla"}) {
empty {
alwaysNil
} 
}
}
}
```

**Comment by IizunaK** [comment]
Hi, I am the user in question.

My goal is to automatize the installation of sourcegraph and its continuous setup, and I would like to go through the API (not the UI).
So basically =
- Adding new repositories as soon as they are added to our subproject in Github Enterprise (not even easy to do in the UI as you have to manually click to enable the repos as the search regex is not taken into account)
- Adding new repositories as soon as they are added to our local Gerrit instance.

I was not able to forge the proper curls for that and I would like your help please :bowing_man:

**Comment by sqs** [comment]
Sorry you ran into these issues. For updating **site configuration**, you need to use the [`updateSiteConfiguration`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@b7ece43c5e3ef4a80f5661588f49ac6a879cb956/-/blob/cmd/frontend/graphqlbackend/schema.graphql#L276) mutation, not `configurationMutation`. I will clarify the docs here (I can see how it is confusing). The `input` arg needs to be a valid JSON document with the full site configuration (not just a patch).

As an aside, for syncing repositories with GitHub Enterprise, you should use the [GitHub integration](https://docs.sourcegraph.com/integration/github#syncing-github-repositories) and add a `github` entry in site config. Did that not work for you? The [`repositoryQuery`](https://docs.sourcegraph.com/admin/site_config/all#repositoryquery-array) option lets you specify to sync all repositories that match a particular query. That was added in [2.13](https://about.sourcegraph.com/blog/announcing-sourcegraph-2.13) and might help.

For Gerrit, I added https://github.com/sourcegraph/sourcegraph/issues/871 to track that feature. Please +1 it if you would like that feature.

**Comment by IizunaK** [comment]
Hi, thank you for the quick answer :+1: !

So I tried the following configuration with Sourcegraph 2.13.2

```
{
  "auth.public": true,
  "auth.providers": [
    {
      "type": "builtin"
    }
  ],
  "disablePublicRepoRedirects": true,
  "maxReposToSearch": 50,
  "github": [
    {
      "token": "{TOKEN}",
      "url": "https://github.schibsted.io",
      "repositoryQuery": [
        "org:leboncoin"
      ]
    }
  ],
  "repos.list": [
    {
      "url": "file:///var/opt/sourcegraph/repos/gerrit/proctool/jenkins-jobs",
      "path": "jenkins-jobs"
    }
  ],
}```

But the forged url seems to be not functional, even on github.com :
- https://github.com/api/search/repositories?page=1&q=org%3Aleboncoin leads to a 404
- https://github.com/search?utf8=%E2%9C%93&q=org%3Aleboncoin&type=Repositories&ref=advsearch&l=&l= leads to the wanted result

Could you look at it ? Did I do something wrong ?

**Comment by IizunaK** [comment]
Maybe the right url would be something like https://api.github.com/search/repositories?page=1&q=org%3Aleboncoin instead ?

**Comment by sqs** [comment]
@nicksnyder Assigning to you because this seems repo-updated-related. Is the code or docs wrong for the github url site config property?

**Comment by nicksnyder** [comment]
I think this is a bug in https://github.com/sourcegraph/sourcegraph/pull/482/files#diff-004e70637a984c7b22dfa7c3331d25f5R335

We need a fix similar to https://github.com/sourcegraph/sourcegraph/pull/496/files

(GitHub enterprise API paths are annoyingly different than github.com)

**Comment by nicksnyder** [comment]
Just released 2.13.3 with a fix; @lixunaK can you confirm that it works for you?

**Comment by IizunaK** [comment]
Yes I confirm it works with the above configuration :)
Thank you very much !

As for the updateConfiguration, I have a hard time making it work
```
json='{  "auth.public": true,  "auth.providers": [    {      "type": "builtin"    }  ],  "disablePublicRepoRedirects": true,  "maxReposToSearch": 50,  "github": [    {      "token": "{TOKEN}",      "url": "{URL}",      "repositoryQuery": [        "{QUERY}"      ]    }  ],  "repos.list": [    {      "url": "file:///var/opt/sourcegraph/repos/gerrit/proctool/jenkins-jobs",      "path": "jenkins-jobs"    }  ]}'

inner_body="mutation{updateSiteConfiguration(input: $json) }"

body="{\"mutation\": \"$inner_body\"}"

curl \
  -H 'Authorization: token-sudo user="{user}",token="{token}"' \
  -d $body \
  http://127.0.0.1:7080/.api/graphql
```
leads to "invalid character 'a' after object key:value pair"

And I wonder at which point my procedure is wrong.
Maybe we can discuss it in another issue though ?

**Comment by sqs** [comment]
@IizunaK If I run the following, I see that the JSON is not properly escaped:

```
json='{  "auth.public": true,  "auth.providers": [    {      "type": "builtin"    }  ],  "disablePublicRepoRedirects": true,  "maxReposToSearch": 50,  "github": [    {      "token": "{TOKEN}",      "url": "{URL}",      "repositoryQuery": [        "{QUERY}"      ]    }  ],  "repos.list": [    {      "url": "file:///var/opt/sourcegraph/repos/gerrit/proctool/jenkins-jobs",      "path": "jenkins-jobs"    }  ]}'

inner_body="mutation{updateSiteConfiguration(input: $json) }"

body="{\"mutation\": \"$inner_body\"}"

echo $body
```

I would recommend:

1. Compose the JSON body in a file `postbody.json`, so you don't need to worry about escaping in Bash
2. Use GraphQL variables, so the body would be `{"mutation": "mutation Update($input: String!) {updateSiteConfiguration(input: $input)}", "variables": {"input": "{\"auth.public\": REST OF CONFIG HERE}"}}`
3. Use `curl -H '...' -d @postbody.json http://127.0.0.1:7080/.api/graphql` (the `-d @postbody.json` tells curl to read in that file)

Feel free to open another issue if you can't get this to work.

**Comment by IizunaK** [comment]
Ok thank you I will try that :)

As for the original githubsearch issue, maybe I was happy too soon. I have lots of logs and even if I enable the repos, they don't seem to clone.

```
11:09:30      repo-updater | t=2018-11-16T11:09:30+0000 lvl=eror msg="repoLookup failed" args="RepoLookupArgs{ExternalRepoSpec{https://github.schibsted.io/ github MDEwOlJlcG9zaXRvcnkxMzY1OQ==}}" error="Post https://github.schibsted.io/api/graphql: dial tcp: lookup github.schibsted.io on 127.0.0.11:53: read udp 127.0.0.1:60170->127.0.0.11:53: i/o timeout"

11:09:36           indexer | t=2018-11-16T11:09:36+0000 lvl=eror msg="Index failed" repo=github.schibsted.io/blabla rev= isPrimary=false error="repository does not exist: github.schibsted.io/blabla"
```

**Comment by IizunaK** [comment]
Sorry you are right, bad dns configuration...

As for the query I managed to make it work with the body beginning by : 
`{"query": "mutation Update($input: String!)}` instead of
`{"mutation": "mutation Update($input: String!)`

But apart for that thank you so much for helping me on that !
And for your reacitvity !

**Comment by sqs** [comment]
Great! :+1: (I edited my post above to fix the mistake, `"query"` vs. `"mutation"`, so nobody else gets confused.)
