### ISSUE TITLE
Ambiguous association between permissions and authz provider

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#8597]
In the current design of permissions tables (i.e. `user_permissions`, `repo_permissions`), it has the assumption that only one authz provider per code host is configured for mirroring permissions. This assumption IMO is inherited from the assumption of a customer would only want to configure at most one code host connection per type, i.e. only one GitLab code host connection, and maybe another GitHub code host connection.

Some evidences are in cache implementation, we only store the project/repo ID but not the actual service ID (e.g. https://github.com, https://gitlab.mycorp.com) these project/repo IDs belong to, which could potentially have collisions when there are multiple authz providers configured for the same type of code host, e.g. two GitLab authz providers.
- https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/internal/authz/github/cache.go
- https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/internal/authz/gitlab/cache.go

It is generally unlikely thus not a problem so far, but could cause ambiguity with the transition of moving permissions syncing to the background (RFC 113) which unifies the store layer to Postgres.

There are two ways we could think about this problem:
a. We make it clear in [our docs: **Repository permissions**](https://docs.sourcegraph.com/admin/repo/permissions) that we currently only support one code host authz provider per type until a large customer wants such support.
b. We fix it now.

I personally prefer **option a** because:
1. We could do the migration in the future (find the code host config has the authz provider and update the column in perms table with the URL of that code host).
2. It is still possible to configure multiple code host connections of same type, but only have single authz provider.
3. Tackle **option b** requires non-trivial work with not so much in return (for the foreseeable future) given the assumption of only having one authz provider configured has lasted in fairly long time.

cc @beyang in case I missed some parts from the whole picture.

**Comment by beyang** [comment]
Good catch, let's go with option a.

**Comment by unknwon** [comment]
The action item here is to update the docs.

**Comment by tsenart** [comment]
If the fix is documentation AND enforcement, I’m fine with option a :-)

**Comment by keegancsmith** [comment]
FYI there are customers doing this. For example see the configuration linked in this support request from a customer: https://sourcegraph.atlassian.net/browse/SG-64

**Comment by unknwon** [comment]
@keegancsmith 
> FYI there are customers doing this. For example see the configuration linked in this support request from a customer: [sourcegraph.atlassian.net/browse/SG-64](https://sourcegraph.atlassian.net/browse/SG-64)

Thanks for the link! I downloaded the config dump and I think they only have configured two **authentication** providers and in fact no **authorization** providers. This issue describes the problem of configuring multiple **authorization** providers. Does this make sense to you?

**Comment by keegancsmith** [comment]
aah thanks I see. I always get those mixed up.

**Comment by unknwon** [comment]
Will be solved by finishing RFC 113, no need to keep this open anymore.
