### ISSUE TITLE
"Example queries" link from iGraphQL console doesn't work

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#860]
Visit https://sourcegraph.com/api/console

Try the "Example queries" link at the bottom (https://about.sourcegraph.com/docs/features/api/examples)

It appears as though this link got broken in the docs changeover.

**Comment by sqs** [comment]
Will update all of https://sourcegraph.com/search?q=repo:sourcegraph/sourcegraph%24+%22https://about.sourcegraph.com/docs%22
