### ISSUE TITLE
Duplicate type signatures/docs in hover tooltips

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#8602]
Sourcegraph.com/GitHub (Chrome extension)

I've seen this multiple times today, always on GitHub. No idea how to repro, and after refreshing it disappears. The first time I saw them, there were 3x, not just 2x (as you see here).

![image](https://user-images.githubusercontent.com/5589410/75327350-1a883f80-5831-11ea-9ce7-631988809fe1.png)

![image](https://user-images.githubusercontent.com/5589410/75327450-43a8d000-5831-11ea-8815-43316b96fbfc.png)

**Comment by lguychard** [comment]
@efritz nothing changed on the web side that would cause this AFAICT. Could some recent changes in code intel extensions have caused duplicate hover provider registration?

**Comment by lguychard** [comment]
![image](https://user-images.githubusercontent.com/1741180/75438925-24a55d80-5959-11ea-81e6-fc3b54436d85.png)

Seems like two hover providers are registered; They both emit the same hover content.

**Comment by lguychard** [comment]
Only seeing this on GitHub pull requests because it appears to be caused by two language server connections being opened for the base+head workspace roots:

![image](https://user-images.githubusercontent.com/1741180/75440466-1c9aed00-595c-11ea-819b-87cd13a2fabe.png)

**Comment by lguychard** [comment]
Oh, I think this is an issue with how scoped document selectors are built. All providers are registered with the document selector `{language: "go", pattern: "git://github.com/sourcegraph/**"}`

**Comment by lguychard** [comment]
I _think_ the culprit here is https://github.com/sourcegraph/code-intel-extensions/commit/24e4d1333f6ae86fec80cd78c3a804847bdb58ec
