### ISSUE TITLE
Chrome extension flaky; no tooltips in Bitbucket server

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#8604]
- **Sourcegraph version:** 3.12.7 + Sourcegraph Chrome extension
- **Platform information:** Bitbucket Server 6.7.1

Reported by https://app.hubspot.com/contacts/2762526/company/1767812339

A user reported that the chrome extension is not adding any hover tooltips to files in Bitbucket Server. However, the Sourcegraph icon does appear (sometimes).

>I am trying to use the SourceGraph browser extension together with our BitBucket server instance. The browser extension does not seem to do anything, I do not see any extra buttons or get any stuff like blame highlighting when browsing code or PRs. Any ideas what I am missing? I did follow the instructions from https://docs.sourcegraph.com/integration/browser_extension
>
>Sometimes I see the source graph icon in the repository, but frequently it disappears again, refreshing sometimes shows it again. That is about all I can get to work.
>
>If this button appears, and I click it, it does bring me to our SG instance. Also searching by typing src<space> in the URL box works.

When I asked if code intelligence was working on Sourcegraph for a file that wasn't working on Bitbucket Server, they indicated yes:

>Hovering on items in the file on SourceGraph does work. I get the buttons to look for references and such.

**Comment by lguychard** [comment]
Things seem to be working OK on our Bitbucket Server instance: 

![image](https://user-images.githubusercontent.com/1741180/75339369-ac736500-5890-11ea-907f-aa7f618b3c86.png)

That instance is running v5.16.6. I'll test with v6.7.1 to see if that could be the issue.

Note that there is one major known limitation with Bitbucket Server: we do not provide code intelligence on unified diff views (https://github.com/sourcegraph/sourcegraph/issues/4808).

**Comment by lguychard** [comment]
I've done some more testing on v6.7.1, and AFAICT all looks good there on blob, PR, commit views (with the exception of the known limitation linked above). I can reliably get code intelligence hovers.

@dadlerj is the customer seeing any errors in the browser console?

**Comment by dadlerj** [comment]
Looks like a CORS error. Do users need to set the `corsOrigin` property for browser extension usage as well, or only native integrations?

**Comment by lguychard** [comment]
The site admin should not need to set `corsOrigin` when using the browser extension.

**Comment by lguychard** [comment]
Closing - this was an issue on the user's side: the native integration was activated but badly configured, and since it takes precedence over the browser extension, neither worked. We worked with the user to fix their configuration, and code intel is now working on their Bitbucket Server instance, provided by the native integration.
