### ISSUE TITLE
RFC 113: Schedule permissions syncing upon user log in

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#8610]
This issue tracks the progress of scheduling a new permissions syncing request upon user log in, in specific, when user logs in after being inactive for 7 days.

Should be implemented after https://github.com/sourcegraph/sourcegraph/issues/8609.

**Comment by unknwon** [comment]
The tech problem encountered is that `PermsSyncer` is only initialized in `repo-updater`, the frontend would have to call an API on repo-updater in order to schedule the sync request.

Putting to backlog as this is an optimization.

**Comment by keegancsmith** [comment]
@unknwon Should this be in 3.16 or closed?

**Comment by unknwon** [comment]
@keegancsmith This is not implemented, but I think we can close it until there is a real need from the customer.
