### ISSUE TITLE
RFC 113: Instrumenting `PermsSyncer`

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#8612]
See examples in these two files:

- https://github.com/sourcegraph/sourcegraph/blob/master/cmd/repo-updater/repos/observability.go
- https://github.com/sourcegraph/sourcegraph/blob/master/cmd/repo-updater/repos/metrics.go

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.14 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
