### ISSUE TITLE
Bad hovers in Go basic code intel

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#8617]
Repro:

1. Ensure codeIntel.lsif is false and go.serverUrl is null in your settings (i.e., to ensure the results are coming from basic code intel and not a lang server or LSIF)
1. Go to https://sourcegraph.com/github.com/sourcegraph/sourcegraph@5d586e607061d26292d8c460693b833edf39b74f/-/blob/cmd/frontend/graphqlbackend/repository.go#L410:19&tab=def
1. Hover over `CommitID`

Expected: see a hover for CommitID
Actual: see a hover for some RedirectURL method

This is also occurring on a self-hosted instance of mine (at `master`).

![image](https://user-images.githubusercontent.com/1976/75358042-1f67e600-5867-11ea-8337-8e81b10f9bbc.png)

**Comment by efritz** [comment]
Will take a look today.
