### ISSUE TITLE
"head>" string shows up in long-line search results

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#8619]
When you search over a file with a very long line, the snippet is not highlighted (this is fine). But there is a weird string `head>` shown in the snippet that appears to be a bug.

![image](https://user-images.githubusercontent.com/1976/75360491-bbdfb780-586a-11ea-9ace-70082f2166fe.png)

**Comment by lguychard** [comment]
This was likely caused by https://github.com/sourcegraph/sourcegraph/pull/8349 cc @unknwon

**Comment by unknwon** [comment]
I'm looking into it now.

**Comment by unknwon** [comment]
I can reproduce with the following query as well:

https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+%22deprecated:%22+&patternType=regexp

But the confusing is if I click on the result that has weird `head>` thing, it doesn't show up in the single file view (which also I believe also went through the highlight function).

(Long lines killed my Chrome again 😞 Restarting my Chrome)

**Comment by unknwon** [comment]
I noticed it only occurs when a first line (line number 1) shows up in the result. PR sent: https://github.com/sourcegraph/sourcegraph/pull/8623
