### ISSUE TITLE
Add docs for connecting to Azure DevOps as a code host

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#8647]
From a user

>I'm trying to configure repos from Azure DevOps using SSH authentication.
>
>I tried following these instructions: https://docs.sourcegraph.com/admin/external_service/other
>
>I'm a little foggy though. For starters, I don't know the SSH port number that Azure DevOps uses.
>
>Do you have any more specific instructions specially for Azure DevOps?

Based on searching online, it looks like Azure DevOps only supports port 22 for SSH access, so no port number is required. References:
* https://developercommunity.visualstudio.com/idea/668359/ssh-server-for-git-on-port-443.html
* https://docs.microsoft.com/en-us/azure/devops/repos/git/use-ssh-keys-to-authenticate?view=azure-devops&tabs=current-page

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by keegancsmith** [comment]
@dadlerj, @tsenart I don't have any bandwidth for this, and have consistently dropped the ball on doing it. Is there someone more appropriate for this task?

**Comment by unknwon** [comment]
Note: we now have working example on https://k8s.sgdev.org/site-admin/external-services/RXh0ZXJuYWxTZXJ2aWNlOjE0, should be helpful for whoever takes this.

**Comment by apjanke** [comment]
Hi @unknwon and all! Can someone share how you got this working? I'm a new user and I've been trying to set up a local Sourcegraph 3.25.2 instance on Ubuntu 18.04 connected to our Azure DevOps repos, and having no luck.

I tried adding them as a generic Git host, like this:

```
{
  "url": "ssh://git@ssh.dev.azure.com:22/",
  "repos": [
    "v3/MYORG/Project1/Project1",
    "v3/MYORG/Project2/Project2",
    "v3/MYORG/Project3/Project3"
     ]
}
```

("MYORG", "Project1", "Project2", and "Project3" are bogus names, of course, for privacy)

and the repos show up in the list of our repos, but when I try to clone any of them, I just get this error:

```
Repository does not exist: ssh.dev.azure.com-22/v3/MYORG/Project1/Project1
```

I'm running Sourcegraph as a user which has an SSH key attached to a DevOps account that has access to these repos.

**Comment by unknwon** [comment]
@apjanke We used HTTPS, I'm pretty sure SSH won't work because there is no way to specify which SSH key to use for Azure code host connections.

```json
{
  "url": "https://{REDACTED}@sourcegraph.visualstudio.com/sourcegraph/_git/",
  "repositoryPathPattern": "sourcegraph.visualstudio.com/{repo}",
  "repos": [
    "Test%20Repo"
  ]
}
```

**Comment by apjanke** [comment]
@unknwon Darn. Were you using 2FA with your DevOps accounts? We have 2FA enabled for our Microsoft/Azure AD accounts, and I haven't been able to get HTTPS-based cloning working on Linux with that setup.

**Comment by unknwon** [comment]
@apjanke Not sure about Azure DevOps, but GitHub allows using PAT as password when 2FA enabled, maybe that's also the case?

**Comment by apjanke** [comment]
@unknwon Aha, yes it does: https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=preview-page

I will give that a try.

**Comment by alexfogg** [comment]
Chiming in here that I think this would be a welcome addition - I've noticed a few questions coming in from prospects lately to our team and to the SDRs around setting up ADO.

**Comment by unknwon** [comment]
cc @ryphil for triage, also cc @flying-robot this was an onboarding task for Indra but we didn't get it prioritized, maybe give another try for the coming new hire?
