### ISSUE TITLE
kubernetes: admin service debug page discovers endpoints

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#8654]
Service debug is a page which links to the debug pages for each service (ie the stuff that normally runs on port 6060). We haven't implemented service discovery for kubernetes so the page is empty (unlike for single docker image).

For example see https://sourcegraph.com/-/debug/ vs https://sourcegraph.sgdev.org/-/debug/

This issue is about implementing the required service discovery. This page is very useful when debugging issues, because it gives easy access to our `net/trace` interface.

The service discovery will likely work the same way prometheus discovers metrics. There is an in-progress branch by keegan from a few months ago, so just reach out to him before starting on this.

**Comment by uwedeportivo** [comment]
nuggets from @keegancsmith:

- wonder how far you can get by copy pasting code from internal/endpoint
- messing with k8s can be annoying. Previously what I have done is create a minimal program which just outputs to stdout what I want. You can see hints of that at the bottom of ./internal/endpoint/endpoint.go if you look at the loadClient function
- doing kubectl --v=6 (or higher) will include the REST calls it does. The REST calls will map directly into the k8s api calls you need to do
- revive minikube
- kubectl --v=6 get endpoints --watch is enlightening
- note we don't use the official k8s client. It's super heavy weight, used to give dependency issues and is unneccessary. The client we use is quite nice and is essentially a light wrapper around the rest api

**Comment by uwedeportivo** [comment]
done
