### ISSUE TITLE
Document licenses for third party open source projects that we depend on

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#8659]
We need something like this: https://neo4j.com/terms/thirdpartylicenses/

The page should be generated automatically. Tagging both @lguychard and @tsenart because the implementation is probably different for TypeScript and Go dependencies.

I would like to prioritize this for 3.15 release on April 20 but if you want to do it earlier, I wouldn't complain :)

slack thread: https://sourcegraph.slack.com/archives/C0B2RU51Q/p1582918787128100

**Comment by eseliger** [comment]
For the web at least there are some good and easy to use plugins:

- https://github.com/codepunkt/webpack-license-plugin which generates a list of licenses and does checks that certain licenses that won’t fit our business model are throwing a build error
- https://www.npmjs.com/package/license-webpack-plugin this is what google uses in @angular/cli

**Comment by drazisil** [comment]
`npx license-checker --json > ./licenses.json` is good for the TS/JS part :)

**Comment by tsenart** [comment]
https://github.com/src-d/go-license-detector

**Comment by tsenart** [comment]
@lguychard: How should approach this? I guess a generated file with all aggregated licences in this repo would suffice (i.e. no need for a web page). With that said, then, we'd need to find a way to merge and normalize the outputs of these different tools (including https://crates.io/crates/cargo-license, for our Rust service) into a single deterministic output format.

I see that you have this on your plate for the web team in this iteration, but if there's not web page needed, I could take this on for all the different languages we have. What do you think?

**Comment by lguychard** [comment]
I agree that a generated file would be sufficient. If you wish to take this on, go for it 🙂

**Comment by tsenart** [comment]
Sounds good, I will.

**Comment by tsenart** [comment]
@nicksnyder, @dadlerj: I'd like your input here on the requirements.

1. Do we need a web page or is a generated text file in our git repo (linkable on Github.com) enough?
2. What level of detail do we need in this file / page? If it is a file, can it be structured JSON or is it meant to be consumed by humans strictly?
3. Is there any sort of legal compliance that this artefact need to abide by?

Example of what a JSON file with all our automatically detected third party dependency libraries would look like:

```json
{
  "@babel/code-frame@7.0.0": {
    "licenses": "MIT",
    "repository": "https://github.com/babel/babel/tree/master/packages/babel-code-frame",
  },
  ...
}
```

**Comment by nicksnyder** [comment]
Dan said this in the linked Slack thread:

> I think even an 80/20 approach here would be better than nothing, e.g. just manually scanning package.json and go.mod files to start and throwing it in a markdown file in the repo

I do think it should be human readable.

**Comment by dadlerj** [comment]
Agreed with Nick's comment above. A text file in our repo is perfectly fine.

CSV or just a space/tab-formatted file would be ideal. If JSON is much easier, we can use that also.

>Is there any sort of legal compliance that this artefact need to abide by?

We need this for our own peach of mind, but also typically customers and investors (and basically anyone doing business with us) asks us to provide this and promise that we aren't and won't be using copyleft. So yeah there is a legal need for this to be correct and updated, but like most things legal, the _practical_ reality is that it's unlikely to be a problem if we build it in good faith and try to keep it updated. That said, if we discover any copyleft licenses, then things get much more complicated :).

**Comment by tsenart** [comment]
I've [extended license_scout](https://github.com/sourcegraph/license_scout/commit/94866c6df9e6892fe2fe67704f9575800c3765a7) to support go mod dependencies which it was missing. I plan to contribute that change upstream. It can export a manifest in both JSON and CSV. How does this CSV look like to you @dadlerj?

If it looks good, I can setup a periodic GitHub action that runs this and creates a PR with the changes (if any).


[sourcegraph-dependency-licenses.csv.txt](https://github.com/sourcegraph/sourcegraph/files/4422148/sourcegraph-dependency-licenses.csv.txt)
[sourcegraph-dependency-licenses.json.txt](https://github.com/sourcegraph/sourcegraph/files/4422149/sourcegraph-dependency-licenses.json.txt)

**Comment by dadlerj** [comment]
Thanks! 🎉 can we remove the "License content" column? It adds every license directly into each row in the CSV

**Comment by tsenart** [comment]
> can we remove the "License content" column? It adds every license directly into each row in the CSV

Sure, if that's OK, I'll do that.

**Comment by tsenart** [comment]
@felixfbecker: I'm taking care of this, so you can take it out of your plate.

**Comment by felixfbecker** [comment]
Thank you @tsenart!

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by keegancsmith** [comment]
Done. See #9823
