### ISSUE TITLE
Cursor is put at the beginning of search field after submitting (instead of staying at end)

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#8731]
After sending a search, I often append to it. This is harder when the cursor jumps to the beginning.

**Comment by lguychard** [comment]
Happens when the search is submitted from the homepage, but not from the global navbar.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.14 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
