### ISSUE TITLE
search bar: Ctrl-f on website cut off

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#8736]
![uhhhh-ctrl-f](https://user-images.githubusercontent.com/888624/75719543-27be8780-5c92-11ea-9674-3d94583b33a5.gif)

Suddenly Hit ctrl-f on a sourcegraph.com search page and I see the above. Can't search in the web page. Don't know if I need to do anything extra to reproduce.

Update: this is if the cursor _focus_ is in the search bar!

**Comment by eseliger** [comment]
Oh, that's a monaco UI. Probably can fix this by removing that keybinding in a monaco config? 🤔

**Comment by lguychard** [comment]
Yup 😆
