### ISSUE TITLE
Missing space when inserting new filter

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#8740]
- **Sourcegraph version:** master
- **Platform information:** sourcegraph.com

#### Steps to reproduce:
1. Enter some repo filter
2. Press space
3. Type 'l'
4. Choose `lang` filter from suggestions
5. See it works correctly
6. Remove lang filter again
7. Add space after repo filter
8. Use ctrl + space to get suggestions (I think there is some unnecessary delay here also, but just very minor)
9. Choose `lang` again

#### Expected behavior:
The filter is added and works

#### Actual behavior:
It is added by removing the space, hence it's invalid

![2020-03-02 22 39 12 2](https://user-images.githubusercontent.com/19534377/75720421-c076f680-5cd6-11ea-9d9c-7ea0e3d5749e.gif)

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.14 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by fkling** [comment]
We've since switched to CodeMirror for the search input and we haven't seen this issue with it.
