### ISSUE TITLE
New search autocomplete yields no results in this particular case

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#8749]
Repro:
* On a Sourcegraph instance, add the github.com/sourcegraph/sourcegraph main repo
* After it's added, search for something like `router.go`
* Observe the autocomplete dropdown shows you a menu of options, including file matches:
![image](https://user-images.githubusercontent.com/1646931/75732393-36fc0000-5ca7-11ea-8d37-021379eca790.png)
* On selection, it expands this to the full file path:
![image](https://user-images.githubusercontent.com/1646931/75732415-48dda300-5ca7-11ea-99f4-6925965d43d0.png)
* When I hit enter, it searches for that query, yielding "No results": 
![image](https://user-images.githubusercontent.com/1646931/75732451-5bf07300-5ca7-11ea-9d72-6eed38d5fdfc.png)

I like the new search bar as a whole, but this experience seems broken. If what I want to do is jump to a file, my natural inclination is to type the name of that file. The old quicksearch would take me directly to the file. The new one just populates the search bar (which is already less good than the old experience, because there's an extra step) and then when I hit enter, it shows me no results.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.14 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
