### ISSUE TITLE
Search bar and directory page have different search bars

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#8752]
The directory page does not use the Monaco editor

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.14 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by lguychard** [comment]
Fixed by https://github.com/sourcegraph/sourcegraph/pull/9225 (the tree search bar no longer exists)
