### ISSUE TITLE
Suggestion icons hard to see in light theme

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#8764]
![image](https://user-images.githubusercontent.com/10532611/75778046-610cfb00-5d57-11ea-998b-2dd01456e3f9.png)

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.14 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
