### ISSUE TITLE
Provide an easier way to add changesets to manual campaigns

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#8766]
A new customer wanted to try out Campaigns and immediately ran into an issue because she shouldn't figure out how to add a changeset to a manual campaign.

The problem was the she couldn't figure out the correct "Repository name" required by this form:

<img width="1043" alt="Screen Shot 2020-03-03 at 14 20 34" src="https://user-images.githubusercontent.com/1185253/75779607-3a9c8f00-5d5a-11ea-8d9a-5061dd1d0980.png">

She tried every combination of `<owner>` and `<project>`, but none worked. The explanation text didn't help.

And if we look at a repository page it's easy to see why she got confused when asked to input a "Repository name" and a text referring to a name:

<img width="991" alt="Screen Shot 2020-03-03 at 14 18 58" src="https://user-images.githubusercontent.com/1185253/75779719-691a6a00-5d5a-11ea-9a78-e489514004b4.png">

The URL in green contains the correct "name", but every other mention of the repository name is either kinda wrong (the escaped full name in the search bar) or doesn't work (the two repository names).

Since manual campaigns and adding a changeset to them is one of the first things customers do when trying out Campaigns we should make that a great experience.

I think there's several possible solutions here, differing in effort required:

1. Make the explanation text better so there's no confusion between URL, full name and name.
2. Provide a search for repositories (like on the repositories page for site-admins)
3. Provide auto-complete for repository names.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by eseliger** [comment]
Removed from 3.17 milestone because https://github.com/sourcegraph/sourcegraph/issues/10986 will likely result in multiple changes to the form, that could invalidate the issue.

**Comment by eseliger** [comment]
I think this is not relevant anymore, with the recent changes to the campaigns schema. If people are confused on how to add them to the yaml, we should file a separate ticket then.
