### ISSUE TITLE
Ability to text-search across all branches (but not necessarily in the same file in another branch)

### ISSUE THREAD

**Issue by AndrewRussellHayes** [sourcegraph/sourcegraph#878]
#### Feature request description

I want the ability to come across code in my codebase that looks out of place and search for that text across all branches of my repository. Further, let us say that the code in question was the first line in a file and said: "hello world". I would like the search to also return hello world's found in all branches and in other files in those branches. (i assume it's implied that I'd want things it was a substring of too... so "hello worldly people" would be a positive return.

#### Is your feature request related to a problem? If so, please describe.

yeah! I'm going through some code and see something that I don't expect to be there and think.. I better find if this developer did this silly thing anywhere else. So to accomplish that I essentially need a full-text search of ALLLL of the current repo's branches and history. (but if searching through history is a huge lift, searching through the head of all branches would be fully acceptable for the current problem.. history is just a nice-to-have).

BTW this will totally make us jump into paid customer territory! I hope you guys find time to add it to your roadmap!

ALSO GitHub does NOT have this feature so this would just be more icing on the sourcegraph cake!

#### Describe alternatives you've considered.

I'm open-minded to any solution that allows me to find all occurrences of a string within all branches of my repository!

#### Additional context

attaching a clip showing how bad github is at this!
![githubsearchsucks](https://user-images.githubusercontent.com/1654144/48169939-640eed00-e2c3-11e8-818a-b66be333eb44.gif)

(by the way, really great looking product! almost never do I get setup instructions for a Docker-based installation that work perfectly the first time! props to your team!)

**Comment by sqs** [comment]
@AndrewRussellHayes and I talked on Twitter. Summary below.

You *can* search all/multiple branches for matching diffs and commit messages (see `repo:regexp-pattern@refs` in the [query syntax docs](https://docs.sourcegraph.com/user/search/queries#keywords-diff-and-commit-searches-only)).

For example:

- [unmerged commits with `task` in their diff](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/Microsoft/vscode%24%40*refs/heads/:%5Erefs/heads/master+type:diff+after:%221+month+ago%22+task#1)
- ["Who's been adding init functions?"](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24%40*refs/heads/+type:diff+after:%222+weeks+ago%22+lang:go+%22func+init%28%29%22) (Go static init functions, which can sometimes be undesirable)
- [Who's using old-style JS require (not import)?](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24%40*refs/heads/+type:diff+after:%222+weeks+ago%22+file:%5C.%28js%7Cts%29x%3F%24+%22require%28%22)

(Note: These queries have a time range on them, so they may go stale if you're reading this far in the future. Try removing the `after:` if so.)

You can't do a normal text search on multiple branches at once, though, but it sounds like diff searching (above) is what @AndrewRussellHayes wants.

**Comment by GaetanoPiazzolla** [comment]
I'm developing a tool to search in a text in all local and remote repos : https://github.com/GaetanoPiazzolla/git-search

**Comment by miso-belica** [comment]
I am using one BAT file as a quick and dirty tool on Windows. Not ideal but helps sometimes.

```bat
@echo off
rem https://stackoverflow.com/questions/7151311/using-git-how-could-i-search-for-a-string-across-all-branches
git fetch origin
git remote prune origin
git branch --remote | grep -v " -> " | xargs git grep %*
```
