### ISSUE TITLE
Update logic for ChangesetEvents does not contain all GitHub event types

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#8796]
This comment https://github.com/sourcegraph/customer/issues/13#issuecomment-594482215 caused me to look into our `(&ChangesetEvent).Update` method, which contains a `panic` at its end:

https://github.com/sourcegraph/sourcegraph/blob/57abf4cb3ba3002e8b8f9c909c0aa704fc47a18a/internal/campaigns/types.go#L1245-L1246

Besides the `*bitbucketserver.Activity` there are also three other GitHub event types missing from the `switch` statement:

```
case *github.CheckRun:
case *github.CheckSuite:
```

If we receive a double delivery of a webhook this code is called and we need to make sure that it doesn't crash:

https://github.com/sourcegraph/sourcegraph/blob/57abf4cb3ba3002e8b8f9c909c0aa704fc47a18a/enterprise/internal/campaigns/webhooks.go#L63-L81

**Comment by eseliger** [comment]
Is this fixed/can it be fixed for 3.14?

**Comment by ryanslade** [comment]
AFAIK this is done

**Comment by mrnugget** [comment]
Yes, fixed by #8799 and #8848
