### ISSUE TITLE
Use tooling to ensure exhaustiveness of ChangesetEvent type checks

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#8798]
Our code for `campaigns.ChangesetEvent`s has multiple switch statements on the `metdata` field of the events:

https://github.com/sourcegraph/sourcegraph/blob/6b7e72a311ccd574496b0278f980879a64a48c57/internal/campaigns/types.go#L984-L989

https://github.com/sourcegraph/sourcegraph/blob/6b7e72a311ccd574496b0278f980879a64a48c57/internal/campaigns/types.go#L834-L837

https://github.com/sourcegraph/sourcegraph/blob/6b7e72a311ccd574496b0278f980879a64a48c57/internal/campaigns/types.go#L940-L943

https://github.com/sourcegraph/sourcegraph/blob/6b7e72a311ccd574496b0278f980879a64a48c57/internal/campaigns/types.go#L1322-L1326

The problem is that not all of them are exhaustive and that `(&ChangesetEvent).Update` creates a `panic` if it comes across an unknown type. See https://github.com/sourcegraph/customer/issues/13#issuecomment-594482215.

https://github.com/sourcegraph/sourcegraph/issues/8796 is about adding missing event types, but we should probably ensure in our tooling that our switch statements are exhaustive _or_ make sure our code doesn't crash.

At the very least we should probably switch on `ChangesetEvent.Kind` instead of the `Metadata.(type)`. And if we do a check on the `ChangesetEventKind` (an "enum"), we can probably add some tooling to ensure that our switch statements are exhaustive, or at the very least a test.

**Comment by keegancsmith** [comment]
I got started implementing a way to do exhaustiveness checks in go using the new `analysis` pkg in `go vet`. I can look into finishing that as part of my day job instead of my occasional hacking :)

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
