### ISSUE TITLE
Two features needs to be added

### ISSUE THREAD

**Issue by truelv** [sourcegraph/sourcegraph#88]
- **Issue type:** 
- **Sourcegraph version:** 
- **Platform:** 

#### Steps to reproduce:

1. can't find function list in a file (terrible bad).
2. can't go to defination or reference on firefox56.02

**Comment by beyang** [comment]
1. Have you tried the "Symbols" option in the sidebar? It shows a list of all symbols in the file (though it doesn't specifically support filtering for function symbols):

![image](https://user-images.githubusercontent.com/1646931/40797592-8ccd8c44-64bd-11e8-901f-4d049a08c431.png)

2. I was able to go to definition and find references in Firefox 60. Firefox 56 is a pre-Quantum release of Firefox and will probably be phased out over time. Is upgrading Firefox an option for you?
