### ISSUE TITLE
Triple quotes cause a query to become invisible

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#8801]
![triple-quotes](https://user-images.githubusercontent.com/888624/75901456-c3b7d280-5dfb-11ea-80d9-004d4c3f361e.gif)

[example](https://sourcegraph.com/search?q=%22%22%22&patternType=literal)

**Comment by lguychard** [comment]
~~Congratulations! You've discovered "search ninja mode"~~

Thanks for fin(d|l)ing!
