### ISSUE TITLE
Case sensitivity icon state wrong when structural search is enabled

### ISSUE THREAD

**Issue by imtommyroberts** [sourcegraph/sourcegraph#8817]
Small issue I found. When enabling structural search, case sensitivity is enabled, my intuition tells me this state is unclear and could cause unnecessary confusion/increase of cognitive load. 

1. The state when nothing is selected: 

![image](https://user-images.githubusercontent.com/40544396/75978222-f46c3a80-5ed5-11ea-96ad-2c4992712a9b.png)

2. The state when structural search has been enabled (automatically enabling case sensitivity)

![image](https://user-images.githubusercontent.com/40544396/75978311-22517f00-5ed6-11ea-9aab-68dd5b698b38.png)

3. The state when structural search has been enabled after the user independently enables case sensitivity

![image](https://user-images.githubusercontent.com/40544396/75978355-3ac19980-5ed6-11ea-8242-d50e6ed1b0d7.png)

State 2 should not exist, instead state 3 should fill the role of option 2.

**Comment by christinaforney** [comment]
What should happen in the de-selection of the structural search toggle? Should case sensitivity stay enabled or get de-selected? 

This could be confusing if I enter the state:
- with case sensitivity enabled, structural search disabled
- structural search enabled
- structural search disabled -> what happens to the case sensitivity toggle? Does it stay enabled or get disabled when I leave the structural search mode?

**Comment by imtommyroberts** [comment]
Good point.

Ideally, if you had enabled case sensitivity beforehand, it would stay enabled after deselecting structural search. If case sensitivity was enabled by structural search, it would be disabled. How feasible would this be? 

If it's not feasible, I would lean towards case sensitivity being disabled in conjunction with structural search being disabled. My intuition is that the appearance of the selected state, in conjunction with the logic that case sensitivity is automatically enabled by structural search, would give users adequate information. 

If anyone is aware of a conventional pattern that suggests this should or should not be the case I would be very interested in seeing that. Also, if there's any use case that I'm missing due to lack of context, please let me know.

**Comment by fkling** [comment]
I don't think I've seen issues with this combination but regardless, we've removed the structure search button.
