### ISSUE TITLE
Browser extension: simpler options menu editor has weird behavior

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#882]
- **Sourcegraph version:** Browser ext 2.02
- **Platform information:** Chrome 70

There is a bunch of odd behavior in the feature flag editor.
- The cursor does not update when pressing the left or right arrow keys
- Lines sometimes disappear (see gif below). I don't know what I pressed to make this happen but I was just moving around the editor to show the lack of cursor movement, and inserting characters periodically.

![2018-11-08 10 09 09](https://user-images.githubusercontent.com/16265452/48218329-7c701d80-e33e-11e8-9206-f588be715910.gif)

#### Steps to reproduce:

1. Use simple options menu and try editing the feature flags

#### Expected behavior:

Cursor moves as you'd expect, lines don't get deleted.

#### Actual behavior:

Cursor does not move, sometimes lines get deleted.

**Comment by ijsnow** [comment]
This is because I'm using a jsonc parser. I'd rather just use check boxes than using a settings editor. The only configurable settings will be boolean feature flags other than the URL
