### ISSUE TITLE
Search bar no longer updating to show current repo with smartSearchField turned on

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#8839]
- **Sourcegraph version:** 3.13.1

With the new `smartSearchField` experimental feature turned on, the search bar behaves differently when you visit a repo.

#### Steps to reproduce:

1. Visit Sourcegraph.com
2. With `smartSearchField` set to true:
    1.  Search for "test"
    2. Click on any result
    3. Note that the search bar still just says "test"
3. With `smartSearchField` set to false:
    1. Search for "test"
    2. Click on any result
    3. Note that the search bar now shows the current `repo:<REPO>` filter applied

With `smartSearchField`:
![image](https://user-images.githubusercontent.com/5589410/76043582-d7069300-5f0c-11ea-91f3-f322e024b41f.png)

Without `smartSearchField`:
![image](https://user-images.githubusercontent.com/5589410/76043614-f3a2cb00-5f0c-11ea-96b0-9ee543947e6e.png)

**Comment by felixfbecker** [comment]
Noticed this too

**Comment by lguychard** [comment]
I just understood where the code that triggered this scoping behaviour was, it wasn't immediately obvious to me: a [global `queryUpdates` Subject](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@4635b6bb97cd9fa88b5e738ee4d9849a1a7a8efc/-/blob/web/src/search/input/QueryInput.tsx#L45:14) that allows components [anywhere in the app](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@4635b6b/-/blob/web/src/repo/RepoContainer.tsx#L169:17) to change the local state of the QueryInput.

**Comment by rvantonder** [comment]
This may or may not be related (please say if it's a different issue and I'll file): The search query gets inconsistently populated on refresh. Sometimes it contains `repo:...` and sometimes it's just blank. I reproduced this by refreshing about 5 to 10 times and one of them is bound to show an empty query on load. In this clip, I am only refreshing the page, and one of the page loads the query is empty, and then returns on another refresh:

![query-bar-gets-cleared](https://user-images.githubusercontent.com/888624/76344868-83ef6000-62bf-11ea-929a-dd8ac510ba0e.gif)

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.14 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by lguychard** [comment]
Fixed in https://github.com/sourcegraph/sourcegraph/pull/9225
