### ISSUE TITLE
No "Find references" on dotcom in LSIF-enabled repo

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#8841]
Repro: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@7f0c0e73dcb5c2cb7fb7d194d9d506b0f5b10007/-/blob/enterprise/internal/campaigns/service.go#L333

![image](https://user-images.githubusercontent.com/5589410/76053055-cc55f900-5f20-11ea-85d4-ba5badf32296.png)

Sorry for another one today guys!

**Comment by dadlerj** [comment]
Never mind! This seems to have just gone away 🤷‍♀ . Previously, I had refreshed and it had remained... 

Closing unless I can repro.

**Comment by dadlerj** [comment]
Reported by @felixfbecker at https://sourcegraph.slack.com/archives/CHXHX7XAS/p1583512113220400

**Comment by efritz** [comment]
I believe this is now being tracked in https://github.com/sourcegraph/sourcegraph/issues/9346.
