### ISSUE TITLE
Search suggestions should only fire after user finished typing

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#8843]
I noticed yesterday that the new search bar was getting really slow when I was editing my query and I realized that it sends an autocomplete-request on every keypress.

If I just hold a button, every character triggers a new request.

Ideally the suggestions only fire when the user stopped typing for ... 50ms? 100ms?

![suggestions](https://user-images.githubusercontent.com/1185253/76066561-25a84180-5f8e-11ea-806c-b5d1fd631854.gif)

**Comment by lguychard** [comment]
Fixed by https://github.com/sourcegraph/sourcegraph/pull/9197
