### ISSUE TITLE
Duplicate requests to phabricator API from sourcegraph extensions

### ISSUE THREAD

**Issue by aisbaa** [sourcegraph/sourcegraph#8849]
- **Sourcegraph version:** 3.12
- **Platform information:** phabricator custom integration and chrome extension v20.2.5.1810

#### Steps to reproduce:

Looks like it for every file changed in diff - javascsript part of sourcegraph in phabricator does:

1. Open diff in phabricator with one file changed.
2. Inspect requests made to phabricator API.
2. Open diff with more than one files changed.
2. Inspect requests made to phabricator API.

For the following cases I've used only sourcegraph extension integrated into phabricator. Browser extension was turned off.

**Diff with 1 file changed:**

<img width="1152" alt="Screenshot 2020-03-06 at 13 22 50" src="https://user-images.githubusercontent.com/82692/76080477-a3307980-5faf-11ea-9917-be694289d6c6.png">

- 1 or more diffusion.repository.search
- 1 or more differential.getrawdiff 
- 2 differential.querydiffs

This one seems fine only one duplicate request.

Differential.querydiffs calls have the same arguments passed and the same response.

**Diff with 10 files changed:**

<img width="1108" alt="Screenshot 2020-03-06 at 13 16 02" src="https://user-images.githubusercontent.com/82692/76079323-18e71600-5fad-11ea-96b4-8ed04df6ca15.png">

- 10 times diffusion.repository.search
- 10 times differential.getrawdiff 
- 20 times differential.querydiffs
- 10 times differential.query

For all requests above 9 were duplicates with exception to differential.querydiffs, where 19 requests were duplicates.

#### Expected behavior:

Expect not to see duplicate API requests

#### Actual behavior:

See duplicate API requests

**Comment by artms** [comment]
It especially taxing browser when you open large change with lots of files changed - then for each changed file you download full raw diff of whole change, sometime is can be tens of megabytes, not only it takes time to download but browser is working hard, UI becomes very sluggish...

**Comment by aisbaa** [comment]
I think @artms is referring `differential.getrawdiff` API call. It would be cool if sourcegraph extension would have some sort of caching for this part. It could be short lived in memory cache. No need to preserve response between page reloads.

**Comment by dadlerj** [comment]
Sorry about that @aisbaa, we'll take a look!
