### ISSUE TITLE
Remove "critical config" from docs

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#8855]
After the management console was removed, we should remove/merge the critical config docs with the site config.

In particular, see the "note" below this link: https://docs.sourcegraph.com/admin/config/site_config#reference

And the page it links to: https://docs.sourcegraph.com/admin/config/critical_config

**Comment by slimsag** [comment]
Will remove soon (likely next release), this was left intentionally in because of all the large numbers of deployments with management console still in them so I made sure the docs would work for both old and new deployments alike.

**Comment by dadlerj** [comment]
Got it, thanks 👍 

I was mostly just worried that the site_config page wasn't complete because some of it was still in the critical_config section, but if that's not the case then not an urgent priority

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by slimsag** [comment]
Quinn did this.
