### ISSUE TITLE
How to add additional capacity for language servers

### ISSUE THREAD

**Issue by KattMingMing** [sourcegraph/sourcegraph#886]
#### Question description

User feeedback:
>Is it possible to add additional capacity for language servers? For example, lots of users have a ton of Go and the go language server for Sourcegraph chokes some of the time on it (doing code intel on it can be super slow.. or completely fail)

#### Additional context

Running v2.12.3 k8s deployment.

**Comment by keegancsmith** [comment]
They can increase the number of replicas for go-langserver. Additionally they may find it useful to give the deployment more CPU/memory resources.

**Comment by sqs** [comment]
@chrismwendt 	Please close this issue when you have added docs to the *new* Go extension's README to cover this (basically what Keegan said).

**Comment by chrismwendt** [comment]
I added a small section to the new Go extension's README about replica count https://github.com/sourcegraph/lang-go#scaling-out-by-increasing-the-replica-count
