### ISSUE TITLE
allow cloning a specific branch only

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#8875]
Some customers have a large number of unrelated branches that they do not wish to clone. Additionally there are cases where a single repo keeps different projects on different branches. In both these cases restricting cloning to a specific branch would be useful.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.14 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by keegancsmith** [comment]
Instead of solving this in our codebase, we have decided to unblock a customer with `src-expose serve` which will serve up any set of directories containing git repos. The admin will then create the desired directory structure with a bunch of single branch repos cloned like `git clone https://github.com/dadlerj-test/mux --single-branch --branch matcher-refactor`. Something just needs to periodically fetch then.
