### ISSUE TITLE
Cleanup error 

### ISSUE THREAD

**Issue by Philipp0205** [sourcegraph/sourcegraph#8876]
I get the following error: 

> gitserver | t=2020-03-07T06:53:31+0000 lvl=eror msg="cleanup: error freeing up space" error="only freed 0 bytes, wanted to free 6953492070"

![image](https://user-images.githubusercontent.com/36603238/76138484-d96e0780-6048-11ea-9a9e-1fc9389e406e.png)

How can I fix this? 

Thanks!

**Comment by unknwon** [comment]
Hi, please use this template to fill in details (https://github.com/sourcegraph/sourcegraph/issues/new/choose):

![image](https://user-images.githubusercontent.com/2946214/76142951-795d7c80-60ad-11ea-994f-b3e882a4be94.png)
