### ISSUE TITLE
Cleanup: error freeing up space

### ISSUE THREAD

**Issue by Philipp0205** [sourcegraph/sourcegraph#8878]
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:**  Ubuntu 19.10, docker version 18.09.9, build 1752eb3

#### Steps to reproduce:

1. Run: 
"sudo docker run --publish 7080:7080 --ulimit nofile=10000:10000 --publish 127.0.0.1:3370:3370 --rm --volume ~/.sourcegraph/config:/etc/sourcegraph --volume ~/.sourcegraph/data:/var/opt/sourcegraph sourcegraph/server:3.13.1" 

#### Expected behavior:
The server starts and I can access the application on localhost:7080.

#### Actual behavior:
Application does not start and error occurs: 

"06:53:31         gitserver | t=2020-03-07T06:53:31+0000 lvl=eror msg="cleanup: error freeing up space" error="only freed 0 bytes, wanted to free 6953492070"

![image](https://user-images.githubusercontent.com/36603238/76144026-89109d00-607c-11ea-9d84-7ca804642a39.png)

**Comment by unknwon** [comment]
Would you be able to try setting this environment variable `SRC_REPOS_DESIRED_PERCENT_FREE=0` then restart the container?

cc @keegancsmith in case you have a gut feeling.

**Comment by Philipp0205** [comment]
I think your gut feeling was quite good.
I ran this command by just passing the variable with -e: 

`sudo docker run -e SRC_REPOS_DESIRED_PERCENT_FREE=0 --publish 7080:7080 --ulimit nofile=10000:10000 --publish 127.0.0.1:3370:3370 --rm --volume ~/.sourcegraph/config:/etc/sourcegraph --volume ~/.sourcegraph/data:/var/opt/sourcegraph sourcegraph/server:3.13.1`

The error is gone but the tabs application on localhost is just loading forever and nothing happens.

**Comment by unknwon** [comment]
I feel like the container sees it has no space.

**Comment by Philipp0205** [comment]
This did the trick, I completely reinstalled docker on my system. Now everything works as expected. I did not know that it was something with my docker installation, normally it works fine. Ty!

**Comment by unknwon** [comment]
Haha, good to know.

**Comment by wpcarro** [comment]
I'm seeing this error message too. Setting `SRC_REPOS_DESIRED_PERCENT_FREE` made the error message go away. Is this desirable configuration to maintain? Or is this just a recommended debugging step? I'm not sure *why* we were getting that error message. Any ideas?

**Comment by keegancsmith** [comment]
@wpcarro that message is from something which tries to ensure gitserver has x% disk space free. How much space is available in your case? The better solution is likely to increase your disk space for gitserver.
