### ISSUE TITLE
Allow default branch configuration per-repo (separate from git symbolic-ref HEAD)

### ISSUE THREAD

**Issue by phrohdoh** [sourcegraph/sourcegraph#89]
Allowing admins to configure the default branch to search means I don't have to change from `master` every time (or whatever the default of the code host we cloned from is).

/cc @sourcegraph/search-platform

**Comment by nicksnyder** [comment]
Thanks for the feedback!

Ideally we should be able to detect this automatically without any configuration necessary (either by calling a code host API or by fetching the remote HEAD reference). What code host do you use?

If you run `git remote show origin` in the repository, does it show output that contains a line like `HEAD branch: mydefaultbranch`?

**Comment by Phrohdoh** [comment]
Currently I am evaluating sourcegraph with bitbucket but the point of this request is to allow default branch config separate from host config.

For example `master` may be the default on the code host but I want sourcegraph to default to `stable` or similar.

**Comment by sqs** [comment]
@Phrohdoh Did my workaround work?

There are a few ways we could solve this, but you're the only one who has requested this feature. Let us know if you're still using Sourcegraph so we can prioritize it if so.

**Comment by Phrohdoh** [comment]
We are not using Sourcegraph after my initial prodding.
I believe this would be a good feature to have but probably doesn't warrant a high priority.

**Comment by nicksnyder** [comment]
We haven't heard any more requests for this so I am going to close it as low priority.  This can be reopened in the future if customers start asking for this and it becomes a priority.

**Comment by luisxiaomai** [comment]
@nicksnyder appreciate that the branch can be configurable, please consider this feature.

**Comment by sqs** [comment]
@luisxiaomai You can configure the default branch used on Sourcegraph by setting the default branch on your code host. Is that what you need, or do you truly need a way to specify the default branch on Sourcegraph *differently* from the code host's default branch?

To search any other branch, just use `@mybranch` after the `repo:` filter, such as https://sourcegraph.com/search?q=repo:sourcegraph/sourcegraph%24%40roadmap+infrastructure+f:roadmap+file:%5C.md%24. See the `@rev` bit at https://docs.sourcegraph.com/user/search/queries for full docs.

**Comment by luisxiaomai** [comment]
@sqs  thanks for your reply. We really need a way to specify the default branch on Sourcegraph like in repository setting level.

**Comment by sqs** [comment]
@luisxiaomai Got it. Can you help us understand the use case? I.e., why is it important that your code host has default branch `master` (for example) and Sourcegraph's default branch is `develop`?

**Comment by AHassanSOS** [comment]
@sqs I'm trying to do the same thing. We have a default branch and release branch. I'm trying to set the default branch in sourcegraph to the release one. So engineer can search the latest code without the need to change the branch.

**Comment by AHassanSOS** [comment]
@sqs At Google, everything goes to a single branch, which makes the searching very easy and consistence. 

On Github, if someone push to a separate branch other than default, I won't be able to search for the new changes unless I explicitly go to explore, select the repo, change the branch, then I will have the ability to search. That requires a bit of **effort** in order to search anything other than the default branch.

**Comment by sqs** [comment]
Thank you all for providing the additional context. 
I've reopened this. It is low priority right now, but that will change if/when we hear about it from more customers or prospective customers.

We would probably try to add this feature by making it easy in general to create Git hooks for all Git repositories mirrored by Sourcegraph (in which you could put a script that runs `git symbolic-ref HEAD refs/heads/develop`) to handle this. This lets us keep complexity out of the application code. If this solution does or doesn't work for you, let us know.

In the meantime, you can run a command like this (I realize this is a hacky workaround, but it may suffice for now):

```
while true; do
  for gitdir in $(find ~/.sourcegraph/repos/ -name .git -type d); do
    (cd $gitdir/.. && git symbolic-ref HEAD refs/heads/master)
  done
  sleep 30
done
```

---

@AHassanSOS: You can also search a different branch by using `repo:myreponame@mybranch` in your search query, although I understand that takes extra effort and is not obvious. (Documented at https://docs.sourcegraph.com/user/search/queries.)

**Comment by dadlerj** [comment]
Also requested by https://app.hubspot.com/contacts/2762526/company/2311695453

**Comment by SugoiDev** [comment]
This could be interesting for [Plastic SCM](https://www.plasticscm.com/) users.

Plastic has a GitServer feature, where it can serve git repositories (that can be consumed by SourceGraph).
A very common workflow in plastic is "one branch per task", so Plastic users usually have many branches.
Since Plastic is often used in a centralized manner, the usual pattern is that each user will have their own "main" branch, with many sub-branches. When translated to git, this will be a flat structure with many branches. You're usually only interested in your branches, and, usually, a specific one.

**Comment by nwiebe** [comment]
I'd also find the feature useful.  Our default branch on GitLab is set to a development branch we merge to most often, so it's the default for MRs.  When it comes to searching our code, we'd like to search the code that's currently in prod by default.

**Comment by githubzaibao** [comment]
> @phrohdoh Did my workaround work?
> 
> There are a few ways we could solve this, but you're the only one who has requested this feature. Let us know if you're still using Sourcegraph so we can prioritize it if so.

yes, I need too!

**Comment by 0Oo-oO0** [comment]
I need it too. Cause some reason, our default branch is not master but faster, so we can't search our newest code in Sourcegraph, this feature will be useful.
