### ISSUE TITLE
new search autocompletion gets in my way

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#8904]
1. Visit https://sourcegraph.com/github.com/sourcegraph/sourcegraph
2. Check the case sensitive toggle
3. Type `repositoriesCount` into the search bar.
4. This appears:

![image](https://user-images.githubusercontent.com/3173176/76267400-d41ae380-6227-11ea-8789-1bf313066096.png)

5. Press enter -- your search does not get ran. Very annoying!
6. Press enter again, finally your search gets ran but the autocompletion incorrectly changed my query to `RepositoriesCount` (capital `R`) even though I wasn't trying to use its suggestion. Very annoying!

**Comment by rvantonder** [comment]
👍 but basically for any autofill suggestion (like, if I type `a` to test something, it'll immediately suggest `after:` and when I hit enter it autofills). The only way around this is to press space, but I don't want to have to remember to press space after every query. How about `<tab`> for activating autofill?

**Comment by unknwon** [comment]
I use <kbd>ecs</kbd> to cancel auto-suggestion, one more key stroke but pretty nature 🤔

**Comment by felixfbecker** [comment]
I've met this too, it's especially frustrating if the suggestion appears last-millisecond. I also think only using <kbd>tab</kbd> for accepting suggestions is the best solution.

**Comment by lguychard** [comment]
> I use esc to cancel auto-suggestion, one more key stroke but pretty nature 🤔

I've been doing this as well and hadn't felt this pain point too much. It's easy enough a change though: https://github.com/sourcegraph/sourcegraph/pull/8907
