### ISSUE TITLE
docs.sourcegraph.com search broken

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#8905]
Repro:
* Go to https://docs.sourcegraph.com/
* Search for something in the "Search docs" bar in the upper right corner
* Arrive at this URL (https://docs.sourcegraph.com/search?q=asdf&v=) with the following error:

![image](https://user-images.githubusercontent.com/1646931/76278524-05f07200-6249-11ea-94e8-d67cdd6193e3.png)

Possibly related to https://github.com/sourcegraph/sourcegraph/pull/8892?

**Comment by unknwon** [comment]
Here it is: https://github.com/sourcegraph/sourcegraph/commit/4a7dad5bf11a8ba4c8bf98d9c9cf7fd2b5df43d5#diff-81d37edaea9ebd4968955592bcdf6961L38

But not sure why it breaks yet.

**Comment by unknwon** [comment]
PR sent: https://github.com/sourcegraph/sourcegraph/pull/8906

**Comment by mrnugget** [comment]
Sorry about this, I totally forgot about the search functionality. Thanks @unknwon for fixing it.
