### ISSUE TITLE
Automatically remove Bitbucket Server webhooks if the `plugin.webhook` property has been removed

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#8914]
As suggested by @eseliger we could automatically remove the webhook we automatically create on Bitbucket Server once the config is removed: https://github.com/sourcegraph/sourcegraph/pull/8908#discussion_r390334511

**Comment by tsenart** [comment]
In the meantime, we can document that admins can manually remove the webhooks if they want.
