### ISSUE TITLE
Not signed in users only get basic code intel

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#8915]
This affects all users of sourcegraph.com, native integration on gitlab.com, and any user of the browser extension on any code host. Those users get inferior codeintel results in their very first experience with the product, which is not ideal. Basic code intel also often returns multiple results, which means go-to-definition doesn't stay on the code host, but links to sourcegraph.com. Users may assume that is always the case, and it's unfortunate because we **have** stay-on-code-host implemented as a feature.

The code intel extensions currently bail out on precise codeintel if no access token is in the settings (it is dynamically created, which can only be done if the user is signed in). But for public instances like sourcegraph.com, there is no technical reason for this, and the language server should work fine without an access token.

Context: https://sourcegraph.slack.com/archives/CHXHX7XAS/p1583836104283400

**Comment by efritz** [comment]
Fixed by https://github.com/sourcegraph/code-intel-extensions/pull/320.
