### ISSUE TITLE
Dark theme makes my query unreadable after pressing enter

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#8922]
**Sourcegraph version:** Sourcegraph.com
- **Platform information:** Mac 10.15, Chrome Version 80.0.3987.106 

On enter, the text here turns dark/black:

![font-color-change](https://user-images.githubusercontent.com/888624/76344455-dda35a80-62be-11ea-92d6-d8f796cba29d.gif)

Possibly related to #8801, at least in the sense that it makes the query color black.

**Comment by lguychard** [comment]
@rvantonder I'm having trouble reproducing this one. Anything in the browser console?

**Comment by rvantonder** [comment]
So after opening console, I reproduced it once, and now it's gone! (stale cache thing?). I saw an error but I didn't screen cap it, because I thought it would come up again when I was making a clip. The error was something to do with `helpers.ts` and contained the words `token` and `column`. Feel free to close, since I can't reproduce any more.

**Comment by lguychard** [comment]
Possible candidate: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@7d02656e593a456118593d28739f40888e9083fa/-/blob/shared/src/search/parser/completion.ts#L174:46

I'm not sure how that could happen with that query / cursor position though... If we have no stable repro I'll close for now.

**Comment by rvantonder** [comment]
OK it came back and then disappeared when I opened console, but not before I could capture the screenie >:-)

![Screen Shot 2020-03-10 at 2 58 58 PM](https://user-images.githubusercontent.com/888624/76363463-51099400-62e0-11ea-9194-1fd89b291718.png)

Looks like you were right @lguychard, `completion.ts` @ line 174

**Comment by sqs** [comment]
Just experienced this myself too

Repro:

1. Go to https://sourcegraph.com/github.com/freebsd/freebsd
2. Append ` foo` in the search box at the top and hit enter

**Comment by slimsag** [comment]
Marking as release blocker unless someone can verify this only occurs when something like a feature flag is on.

**Comment by unknwon** [comment]
@slimsag it is behind a feature flag in global/user settings:

```json
  "experimentalFeatures": {
    "smartSearchField": true
  }
```

Default is `false`, we just enabled for everyone on the sourcegraph.com.

I've tested the I don't have this problem on sourcegraph.com anymore when turn "smartSearchField" off in my user settings.
