### ISSUE TITLE
smartSearch racy cursor focus

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#8923]
I'm not sure how to reproduce this, but on one of my page loads the cursor blinked in both queries, and I couldn't type anything until I clicked one that seemed to focus the cursor. Some kind of racy behavior.

![racy-cursor-focus-on-page-load](https://user-images.githubusercontent.com/888624/76345031-dcbef880-62bf-11ea-8536-2d76404497ea.gif)

**Comment by lguychard** [comment]
This will be fixed by https://github.com/sourcegraph/sourcegraph/pull/9225

**Comment by lguychard** [comment]
Fixed by https://github.com/sourcegraph/sourcegraph/pull/9225 - the second search bar is now removed.
