### ISSUE TITLE
Structural search conditions?

### ISSUE THREAD

**Issue by jtmarmon** [sourcegraph/sourcegraph#8924]
#### Question description

Howdy,
I'd like to run the following structural search: `'MyClass implements Foo<[:interface]>' where interface != "IrrelevantInterface"`

It seems like the comby syntax supports this but as far as I can tell, the above isn't supported in sourcegraph. 

Is this supported? It seems to me having some kind of conditional logic on the matches must be possible or planned (otherwise why even give the matches names? you might as well do `Foo<[:?]>` since you can't refer to it in any way)

In either case (supported or not) it would be great to have this outlined in the docs

**Comment by rvantonder** [comment]
Hey @jtmarmon, I think we covered this "offline" :-) Thanks for the note, I'll document the current state of (un)supported functionality on the search page.

**Comment by jtmarmon** [comment]
Thanks @rvantonder!
