### ISSUE TITLE
Firefox security errors when using comlink transfer handlers for URLs

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#8928]
Placeholder to be filled out, context for now: https://sourcegraph.slack.com/archives/CMT39K56Z/p1583872625089900

**Comment by lguychard** [comment]
Hard to fix properly.

**Comment by vdavid** [comment]
That Slack convo is already archived, so in the lack of context, I'm closing this.
(If this was a problem in the past 3 years, we probably have another issue about it.)
