### ISSUE TITLE
Organization profile should not have sidebar

### ISSUE THREAD

**Issue by francisschmaltz** [sourcegraph/sourcegraph#893]
![screen shot 2018-11-08 at 5 49 35 pm](https://user-images.githubusercontent.com/11583013/48238132-b103c980-e37e-11e8-90d6-54e68f14890e.png)

There should never be a sidebar with a single item. There should not be a sidebar here.

**Comment by francisschmaltz** [comment]
@nicksnyder can you assign someone to fix this.

**Comment by nicksnyder** [comment]
Since this is purely cosmetic, it isn't high priority.
