### ISSUE TITLE
"Search in this repository" behaves unexpectedly for forked and archived repos

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#8953]
[This search query](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/zoekt%24+error&patternType=literal) shows:

![image](https://user-images.githubusercontent.com/3173176/76469376-67c8ed00-63ab-11ea-91d0-f474c0db59fc.png)

But the repository is cloned: https://sourcegraph.com/github.com/sourcegraph/zoekt

Why can't I search in this repository?

UPDATE: important part here: I got here from the "Search in this repository" search box on the repository page.

**Comment by rvantonder** [comment]
Working as intended. sourcegraph/zoekt is a forked repo, and excluded from search by default.

**Comment by slimsag** [comment]
![image](https://user-images.githubusercontent.com/3173176/76470384-394c1180-63ad-11ea-891b-2dc886016e10.png)

**Comment by slimsag** [comment]
Question is: should 3.14 be released with or without fixing this? Seems like a web/JS change will be needed, easy fix would be to revert the fork-off-by-default change but I'm not sure that is actually better

**Comment by rvantonder** [comment]
> Question is: should 3.14 be released with or without fixing this?

We should address it.

Thought: the `fork:yes` magically appearing in the top query would feel like a surprising addition to some maybe. But I don't think we have a nice mechanism to silently do that.

**Comment by slimsag** [comment]
> Thought: the fork:yes magically appearing in the top query would feel like a surprising addition to some maybe. But I don't think we have a nice mechanism to silently do that.

I'm not sure why this would be surprising? We are adding `repo:...` for the user already so if `fork:true` or `archived:true` would also be needed that seems reasonable and expected?

**Comment by rvantonder** [comment]
Yeah it seems reasonable and expected the way "Search this repo" functionality currently works. I prefer addressing this in the webapp compared to reverting and can own that. This is an important $customer-related change.

**Comment by slimsag** [comment]
Update: We also add `file:` for when you start searching from within a file tree

Here is the place at which we submit this search for both cases:

https://sourcegraph.com/github.com/sourcegraph/sourcegraph@f3e5cccad5dd68cd8360bbe571a193601dce833e/-/blob/web/src/repo/TreePage.tsx#L431-438

**Comment by slimsag** [comment]
Thanks for taking this on @rvantonder !

**Comment by keegancsmith** [comment]
- What happens if you search using the editor integration?
- Should we consider including forks when your repo regex is exact (ie is a literal string anchored with ^$)
- Archive?
- I suggest we include the alert suggestion of adding fork in the filters bar below the search bar.

**Comment by rvantonder** [comment]
> Should we consider including forks when your repo regex is exact (ie is a literal string anchored with ^$)

This feels like a much better workaround compared to the current approach that requires changing queries in the webapp. For 'exact repo' searches through the "Search in this repository", the repo: would already be in that form. This way we could handle that decision on the backend. It feels fairly safe to assume that we can rely on exact-match to return results or not. I'm in favor. Input @christinaforney?

> Archive?

Whatever we do for fork should happen for archive too?

> What happens if you search using the editor integration?

I'm not familiar with editor integrations and the problems this might surface.

> I suggest we include the alert suggestion of adding fork in the filters bar below the search bar.

Sure, in addition to the suggestions yes? Feels like this addition shouldn't be release blocking though?

**Comment by rvantonder** [comment]
I'm going to go ahead with the "include search results for exact `repo:` matches" and will put up a PR and take things from from there. I think it'll solve this in a better and faster way.

**Comment by keegancsmith** [comment]
> > Should we consider including forks when your repo regex is exact (ie is a literal string anchored with ^$)
> 
> This feels like a much better workaround compared to the current approach that requires changing queries in the webapp. For 'exact repo' searches through the "Search in this repository", the `repo:...` would already be in that form. This way we could handle that decision on the backend. It feels fairly safe to assume that we can rely on exact-match to return results or not. I'm in favor. Input @christinaforney?

Great, I think this makes sense. I think our defaults can be "magic" to guess what the user wants. If they opt in to explicit inclusion/exclusion it turns off the magic.

> > Archive?
> 
> Whatever we do for fork should happen for archive too?

Agreed.

> > What happens if you search using the editor integration?
> 
> I'm not familiar with editor integrations and the problems this might surface.

I'm also not that familiar with it, but I believe the proposed fix should resolve that as well.

> > I suggest we include the alert suggestion of adding fork in the filters bar below the search bar.
> 
> Sure, in addition to the suggestions yes? Feels like this addition shouldn't be release blocking though?

Yes not release blocking, just an idea I had (feel free to ignore).

**Comment by dadlerj** [comment]
>This is an important $customer-related change.

If a quick fix would come at the cost of proper testing, this is not an urgent issue that has to be included in 3.14. Happy to notify the user, just let me know!

https://github.com/sourcegraph/sourcegraph/pull/8974 is an alternative approach/solution for this user anyway.

>Should we consider including forks when your repo regex is exact (ie is a literal string anchored with ^$)

👍

**Comment by christinaforney** [comment]
Sorry for the slow reply, definitely agree with this improvement!
