### ISSUE TITLE
Sourcegraph.com search returned no results

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#8960]
In https://twitter.com/FreeBSDHelp/status/1237942414578454528 a user reported that https://sourcegraph.com/search?q=freebsd&patternType=regexp showed no results, but then later it showed results. Feel free to follow up with that user (on Twitter) to gather more info if we can't find anything in our logs.

**Comment by rvantonder** [comment]
Can't reproduce and this issue has gone stale, so there's likely no action we can take here. Might have been related to https://github.com/sourcegraph/sourcegraph/issues/9001.
