### ISSUE TITLE
"On this page" docs expansion overflows and not scrollable

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#8961]
The right side "On this page" in the docs can overflow and is not scrollable, so it's not possible to see all the links or navigate them. Noticed this when looking at the campaigns docs and wanted to click 'edit this page' but couldn't reach the button.

I think you have some context, but feel free to reassign @mrnugget

![cant-scroll-on-this-page](https://user-images.githubusercontent.com/888624/76485182-04ee4a80-63d9-11ea-9465-d492eb08f89f.gif)

**Comment by mrnugget** [comment]
Nice catch! I'll try to fix it.

If someone from @sourcegraph/web knows what's wrong here, though, that would save me a lot of debugging and reading 😄

**Comment by eseliger** [comment]
I guess it's just missing an `overflow-x: auto`? 🤔

**Comment by mrnugget** [comment]
Fixed by now!
