### ISSUE TITLE
Code intel stops working after a couple of minutes on idle page

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#8963]
- **Sourcegraph version:** Master
- **Platform information:** Chrome, Mac OS X

This may be LSIF-specific, I'm not sure.

#### Steps to reproduce:

1. Visit [a Go file in our repo](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/search.go#L123:9)
2. Hover on `NewSearchImplementer` and see results (the specifics doesn't really matter, choose anything to hover on).
3. Go do something else for 5 minutes
4. No pop up hovers for `NewSearchImplementer` or anything else. Basically, no code intel.

I didn't see anything come up in the console. It works again after a page refresh.

**Comment by felixfbecker** [comment]
One thing that may help prevent this is periodic ping-pong messages, which are implemented in the TS langserver. I'm not sure if they are in the Go langserver too. https://github.com/sourcegraph/code-intel-extensions/pull/328 of course is great to have in any case, but reconnecting still comes with an overhead (langserver needs to reinitialize again) so avoiding the disconnect in the first place in addition would be ideal

**Comment by efritz** [comment]
Code intel does not have any bandwidth for LSP server features.
