### ISSUE TITLE
Existing merged changesets are “closed” and hence removed from the tracking campaign

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#8981]
- **Sourcegraph version:** master
- **Platform information:** Dogfood

#### Steps to reproduce:

1. Have a campaign with some changesets already merged
2. Run src-cli again to create the newest patches (I wanted to expand the scope)
3. See them marked as "to be closed" (pr for a "unchanged" tab is up)
4. Click update, see them disappear

#### Expected behavior:

The 4 merged changesets would have been skipped, retaining them in the campaign.

#### Actual behavior:

The 4 merged changesets were interpreted as "to be closed" and are removed from the campaign. Lost tracking progress of them.

**Comment by mrnugget** [comment]
Note on step 2: it _didn't_ include the merged changeset's repos.
