### ISSUE TITLE
Progress status indicator for repo / user permissions syncing

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#8988]
- Initial syncing of permissions
- Refresh since last time it was refreshed

NOTE: Take a look at showing repo cloning progress

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by unknwon** [comment]
Putting into backlog for now because I want to fist get done with the permissions UI in user/repo settings page. After that, could invest more thinking into this.

**Comment by uwedeportivo** [comment]
can we please look into moving it into a release if possible. i can help with the impl.
we are replicating a customer setup with lots of repos and having more progress indicators would really help there.

**Comment by unknwon** [comment]
@uwedeportivo 3.17 or 3.18? And do prospects plan to enable repository permissions? If not, wouldn’t benefit from this progress indicator I think 🤔
