### ISSUE TITLE
Display last updated time of permissions in repo and user settings page

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#8989]

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by unknwon** [comment]
Close this one in favor of https://github.com/sourcegraph/sourcegraph/issues/4672 since there has more information.

**Comment by unknwon** [comment]
Nope, that one requires something different... hmm.
