### ISSUE TITLE
Admin button for refreshing permissions for a user / repo

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#8990]
https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/web/src/repo/settings/RepoSettingsMirrorPage.tsx#L303:40

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
