### ISSUE TITLE
Clearly segment telemetry into "critical" and "non-critical", and update docs for disabling non-critical

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#8995]
Context: https://sourcegraph.slack.com/archives/CN4FC7XT4/p1584044524066100

Notes on ideal future state:

* It will impossible to disable telemetry _entirely_, however, more pieces of telemetry will be disable-able by using the `disableNonCriticalTelemetry` config option.
* Five key fields will be considered "critical", based on the reason in parentheses:
  * Email address of installer (for contact for security notices, product releases, etc.).
  * Unique site ID (random string ID of an instance)
  * Sourcegraph version (for security notices)
  * Total user accounts (for billing)
  * Monthly active users (for billing)
* Everything else will be disable-able using `disableNonCriticalTelemetry`, which will be clearly documented. Disabling telemetry will initially be an opt-in option (i.e., anonymous telemetry will be sent by default).

**Comment by slimsag** [comment]
Great! Thank you for filing this! Some clarifications on wordings here:

> Email address of installer (for contact for security notices, product releases, etc.).

We should clarify product releases here is something you can opt-out of (not a spam list), and enumerate exactly what `etc.` means.

**Comment by ebrodymoore** [comment]
Just to clarify, the current state of this is that it's a Y/N on whether pings get sent from an instance. If it's a yes, everything gets sent. If it's a no, nothing gets sent. 

If so, what does `disableNonCriticalTelemetry` currently do? I'm interpreting all this as we'd like to eventually have those five fields as critical, but there's nothing in production like this today.

**Comment by dadlerj** [comment]
It's not quite that simple — `disableNonCriticalTelemetry` was actually added by Eric when he added the code intel latency data to allow opting out of aggregated event counts (vs. aggregated unique user counts). So currently, it only affects 1 (now 2, with Rijnard's PR) of the items in the pings. Eventually it should affect many more (i.e., almost all).
