### ISSUE TITLE
C code intelligence

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#9]
Support C on Sourcegraph.

**Comment by tbodt** [comment]
How is this going?

**Comment by sqs** [comment]
@tbodt We are working on a solution for many more languages. What are the main open-source C repositories (if any) you’d like to use on Sourcegraph?

**Comment by tbodt** [comment]
@sqs Linux, mainly

**Comment by zhaojh329** [comment]
How is this going?

**Comment by ggilmore** [comment]
Hello @zhaojh329, we (and me personally) are actively working on solutions that will make it easier to add support for many new languages on Sourcegraph. C is on our shortlist of languages to get up and running 👍 

[We also recently released symbol search](https://about.sourcegraph.com/blog/introducing-sourcegraph-server-2-6/#symbol-search-for-75-languages). C is one of the 75+ languages that support this feature. You might find this useful until we add support for full C code intelligence.

**Comment by chrismwendt** [comment]
Experimental C support has been shipped in Sourcegraph 2.8! Check out the blog post https://about.sourcegraph.com/blog/code-intelligence-for-more-languages-and-lsp-language-server-protocol-support

![image](https://user-images.githubusercontent.com/1387653/40390495-4a06a624-5dca-11e8-886b-bc0e1524f97c.png)

Thanks go to [LLVM](https://clang.llvm.org/extra/clangd.html) (and [Chilledheart/vim-clangd](https://github.com/Chilledheart/vim-clangd) for providing prebuilt binaries) for providing the language server.

**Comment by chrismwendt** [comment]
C/C++ code intelligence has been added in Sourcegraph 3.0 :tada:

https://about.sourcegraph.com/blog/sourcegraph-3.0#code-intelligence-for-all-languages

[Try it out](https://sourcegraph.com/github.com/torvalds/linux@aa0c38cf39de73bf7360a3da8f1707601261e518/-/blob/arch/arm/mach-footbridge/dc21285.c#L263:34) on Sourcegraph.com:

![image](https://user-images.githubusercontent.com/1387653/54005876-fb6c3b80-410f-11e9-8d93-2a8d73b7a175.png)

**Comment by s1341** [comment]
Hi,
When I do 'find references' on a function in the linux kernel (C language mostly), I get matches in strings and comments. I'd expect to get only actual calls. Is this configurable somewhere?

**Comment by chrismwendt** [comment]
> I get matches in strings and comments... Is this configurable somewhere?

The results are fuzzy because internally it uses ctags and text search to find definitions and references.

To get precise code intelligence, you can upload LSIF data for the repository on Sourcegraph.com or your own Sourcegraph instance https://docs.sourcegraph.com/user/code_intelligence/lsif

Luckily there is a C++ LSIF indexer available already! https://github.com/sourcegraph/lsif-cpp Please send us feedback 🙇 We are actively recommending LSIF as the primary way to get precise code intelligence now.

**Comment by s1341** [comment]
@chrismwendt Hi.

I spent three days getting the android kernel to compile with your clang plugin. I finally managed, but it doesn't appear to generate data for everything. For example, the string "read" doesn't appear in the dump.lsif generated by lsif-cpp.

Is lsif-cpp useful for C code as well as CPP? What am I doing wrong?

**Comment by chrismwendt** [comment]
Where did you spend the most time? Is there anything about lsif-cpp that made this difficult? I'd be happy to make improvements if you have any suggestions 😃 

> the string "read" doesn't appear in the dump.lsif generated by lsif-cpp.

Are you referring to the system call "read", or some random string with the text "read"? Library functions such as `printf` should show up in the output.

> Is lsif-cpp useful for C code as well as CPP?

Yes.

> What am I doing wrong?

Can you show what commands you ran? Ideally we could narrow this down to a minimal repro.

**Comment by s1341** [comment]
> Where did you spend the most time? Is there anything about lsif-cpp that made this difficult? I'd be happy to make improvements if you have any suggestions 
Most of my time was getting the kernel to compile correctly with an 'outside' clang. This was necessary as the prebuilt clangs shipped with the android kernel are too old for your plugin. It might be worth mentioning in the lsif-cpp documentation/README which versions of clang are needed/supported.
> 
> > the string "read" doesn't appear in the dump.lsif generated by lsif-cpp.
> 
> Are you referring to the system call "read", or some random string with the text "read"? Library functions such as `printf` should show up in the output.
There are many functions in the kernel which contain the word 'read'. They should be part of the symbol data, no? Also, 'printf' does not appear in the dump.lsif either :P.

> Can you show what commands you ran? Ideally we could narrow this down to a minimal repro. Please file an issue at https://github.com/sourcegraph/lsif-cpp
I've filed a (very) detailed issue at https://github.com/sourcegraph/lsif-cpp/issues/7. Let's continue the discussion there.
