### ISSUE TITLE
Indexed Search timing out with cold cache

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#9001]
Recently several customer ran into indexed search queries timing out, but after refreshing the query does not timeout / increasingly finds more results.

### Mitigation

We have successfully mitigated this by horizontally scaling `indexed-search`. Instead of one vertically scaled pod with lots of memory, use 4 pods with a quarter of the memory. The helps to increase effective IO in the cold cache case. This may also help prevent all of the cache being dropped at once since it is 4 independent kernels deciding when to page out.

### Open questions

-   This seems to have recently started happening at several customers. Is there something we have changed?
-   What exactly is being slow in zoekt (paging in index vs paging in content)
-   What other mitigations can we implement?

### Context

We have ruled out other parts of our system and have narrowed down this behaviour to zoekt. Zoekt mostly relies on MMAP data when performing a search. This means data can be dropped from the cache depending on the whims of the operating system and/or noisy neighbours.

Zoekt stores some data explicitly in memory. In practice there are 3 main parts to resolving a search query:

1.  trigram index
2.  trigram posting lists
3.  file contents

The trigram index is stored in memory as a `map[uint64]uint64`. Each key is a trigram (you can bitpack 3 runes into 64bits) and each value is a offset of where the posting list is stored. Posting lists are backed by MMAP, so can be cached in and out. The posting list is used to decide which files could contain a match for the regex. We then run the regex on file contents, which are also backed by MMAP.

### Needle in Haystack

Queries that are most likely to exhibit the timeout behaviour are unique terms in your repos. This is because they do not trigger file match limits, so we end up searching every repo (every shard). But these queries should perform well since for most shards we hopefully can exclude them at the trigram index stage since there is a missing trigram. But if all trigrams exist, we then decode the two smallest posting sets. If it is indeed a rare term these should be small and mostly result in us looking in no files.

What is confusing is that posting lists are small so paging in from disk should be relatively fast. So you would think the slowness is paging in file contents. But for needle in haystack queries we should mostly be looking at posting lists. This could indeed just be seek latency of loading in lots of posting lists.

### What has changed recently

A useful bit of data is upgrade timelines for affected customers. This should help us narrow down which potential change could have caused this. Ideas:

-   Indexed symbols (somewhat old) uses up cache, so could kick out the more important text search cached data.
-   Using indexed symbols more in our product.
-   Suggestions code being more aggressive.
-   UI changes leading to more searches.

### Customer issues

- https://github.com/sourcegraph/customer/issues/37
- https://github.com/sourcegraph/customer/issues/34
- https://github.com/sourcegraph/customer/issues/33

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.14 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by keegancsmith** [comment]
@slimsag 3.14 will include some extra debug goodness for zoekt:

- debug logs for each search request (this should help a lot)
- prometheus metrics on search https://github.com/sourcegraph/sourcegraph/issues/9111
- `IN_MEMORY_CONTENT=filecontents` to keep file contents in memory. You can load any section into memory now, for us to experiment. Posting lists is the other important data structure but is much bigger than contents normally. You can load both with `IN_MEMORY_CONTENT=filecontents,postings`.

**Comment by keegancsmith** [comment]
I'm moving this to 3.15 since we haven't resolved the issue for all customers yet and we still have unanswered questions around why this happened in the first place.

**Comment by keegancsmith** [comment]
Found a potential cause for why things are getting paged out: suggestion code running too often. https://github.com/sourcegraph/sourcegraph/issues/9133

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by slimsag** [comment]
I am backlogging as the workaround we merged has been sufficient.

**Comment by lguychard** [comment]
Closing: this has been inactive for a long time, streaming search + scaling work should have vastly improved the situation here.
