### ISSUE TITLE
Terms within large file are not appearing in search

### ISSUE THREAD

**Issue by SKHecht** [sourcegraph/sourcegraph#9011]
I'm working with a private instance of sourcegraph and I tried doing a straightforward literal search (no operators/filters or anything) for a term across the entire codebase, trying to find its definition. Only a couple usages came up and none of them were the definition.

I investigated further and found that the variable (the term I was searching for) was defined in a file that is nearly 15K lines long. I'm assuming that's why the file didn't come up in search but it's hard to say. I realize this bug report isn't a lot to go off of, but there isn't so much else to describe without literally just sharing the entire codebase (obviously not an option) and the term I was searching for. Happy to give more info where I can.

**Comment by dadlerj** [comment]
Hey @SKHecht, yeah, you probably hit our default file size limit of 1MB. You can read more about this (and find how to update a configuration option to include them) in our docs at https://docs.sourcegraph.com/user/search#max-file-size

**Comment by lguychard** [comment]
This would be fixed with `largeFiles` as suggested.
