### ISSUE TITLE
Discussions for disabled repo should not appear on main discussions page

### ISSUE THREAD

**Issue by francisschmaltz** [sourcegraph/sourcegraph#902]
![disq-dis](https://user-images.githubusercontent.com/11583013/48281149-95460500-e40a-11e8-8ceb-17d7bc1a5958.gif)

Discussions for repositories that are disabled should either be visible in a historical view, or hidden from the main discussions page.

@slimsag I'm open to talking about UI considerations for this

**Comment by sqs** [comment]
This may still be a (low-prio) issue on the explore page

**Comment by sqs** [comment]
Code discussions are not shown here anymore
