### ISSUE TITLE
Basic code intel info button is wrong size and color

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#9065]
![2020-03-17 14 46 42](https://user-images.githubusercontent.com/10532611/76862310-34300c00-685e-11ea-8999-04b06eaa8286.gif)

cc @efritz

**Comment by efritz** [comment]
Could @sourcegraph/web own this? It looks like it's solely a styling issue.

**Comment by felixfbecker** [comment]
It's a bit more complicated unfortunately. It's not possible to style an SVG that is embedded with `<img>` with CSS, so the SVG is always in the colors that are encoded in the SVG. This makes it impossible to have the style match the code host. The close button is embedded SVG, so it can use the CSS font color. But since the code intel extensions contribute this SVG through a `data:` URI that then is embedded with `<img>`, it's not stylable.

I don't know an easy solution to this unfortunately.

Do the extensions need full flexibility over the icon? Could it be enough to let them pick between a few "categories" (info, warning, ...) and the webapp provides the icon?

**Comment by efritz** [comment]
@felixfbecker I'd be fine with updating the extension API so have a class of icons instead of a single image. Alternatively we can send the full svg text instead of a base64 encoded one so that it can be styled appropriately.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by twop** [comment]
should be fixed with #10521 
Note: codeintel extension needs to opt in to the new API

**Comment by felixfbecker** [comment]
@twop do you plan to open a PR at https://github.com/sourcegraph/code-intel-extensions or do you expect @sourcegraph/code-intel to do that?

**Comment by twop** [comment]
I have changes ready, I will open a PR, tnx for reminder!

**Comment by felixfbecker** [comment]
Awesome! For future changes to the API, it may also be good to open that PR at the same time as the PR here, as an "example usage" of the new API :)
