### ISSUE TITLE
Can't switch away from structural search when enabled

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#9078]
Visit sourcegraph.com

Type anything

Toggle the structural search button `[]`

Try to toggle any other search button (e.g. the regex or case ones, `.*` or `aA`)

You can only switch off of it by first un-toggling it

**Comment by attfarhan** [comment]
This is by design. Structural search is always case sensitive and uses Comby syntax. If you hover over the regex and case toggles you’ll see tooltips explaining this.

**Comment by dadlerj** [comment]
Ahhh thanks. Makes sense for case. But in my mind, structural and regex are mutually exclusive, so toggling regex would be a way to switch off structural, and to switch to regex. 

Note that if I'm on regex, and I hit the structural button, it works as expected — it untoggles regex, and toggles structural. I would've expected the same here.

**Comment by rvantonder** [comment]
Yeah, I've actually also thought about this @attfarhan. It's fine if you can't toggle the caps, but it would make sense to be able to toggle regexp directly from structural search being active (and then disable structural search). I've run into this and think @dadlerj expectation is reasonable. Can we do that?

**Comment by attfarhan** [comment]
Yeah sure, that's reasonable

**Comment by rvantonder** [comment]
Super!! thanks @attfarhan
