### ISSUE TITLE
Canceling new access token creation throws 404

### ISSUE THREAD

**Issue by AnandChowdhary** [sourcegraph/sourcegraph#9083]
- **Sourcegraph version:** 58360_2020-03-17_da29d70
- **Platform information:** Chrome 80.0.3987.132  on macOS 10.15.1

#### Steps to reproduce:

1. Go to User account settings –> Access tokens
2. Click on "Generate new token"
3. Click on "Cancel"

#### Expected behavior:

The link goes to `.../settings/tokens`

#### Actual behavior:

The link goes to `.../settings/tokens%7D` and shows a 404 Error

**Comment by unknwon** [comment]
cc @sourcegraph/web

**Comment by AnandChowdhary** [comment]
Line to fix: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@6721280eca6ac39aebfa8febc17461a7d57146ee/-/blob/web/src/user/settings/accessTokens/UserSettingsCreateAccessTokenPage.tsx#L196

There is an additional, unnecessary closing brace `}` which needs to be removed.
