### ISSUE TITLE
authz: better heuristic of `NextSyncAt` by `PermsSyncer`

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#9098]
We currently reuse the value of `UpdatedAt` column which sync permissions as fast as we can, it is generally not a problem as long as rate limiter allows.

There is a side effect in current implementation that we have `BIGINTSERIAL` for `user_pending_permissions` table's surrogate key and every `ON CONFLICT` increases its value by 1 silently, but not an immediate concern.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by unknwon** [comment]
Moving to 3.16, with the new code host rate limiter, the heuristic could be done better.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
