### ISSUE TITLE
Use the same code for burndown chart and derived Changeset State

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#9101]
Right now `CalcCounts` and, for example, `ChangsetEvents.ReviewState` use different code, which lead to a lot of bugs sneaking in in the past.

We need to find a solution to merge both pieces of critical business logic.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
