### ISSUE TITLE
Add tests for the webhook handler that persists data

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#9104]
We currently don't have any tests that make sure that receiving a webhook event leads to the correct events in the database. Since we have a ton of logic in there by now, we should add some tests. We don't have to test _every_ event, but we should at least test some.

- [x] Test for Bitbucket Server review events
- [x] Test for GitHub review events

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
