### ISSUE TITLE
RFC 132: Use rate limit data when scheduling changeset syncs

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#9105]
We should include rate limit data when computing the schedule for changeset syncing. 

See details in [RFC 132](https://docs.google.com/document/d/1iS5cr_vI1wEKbQHLLjLyXLaGdci1bt0VAY2_QzbXj5I/edit#)

At a high level we want to avoid scheduling syncs that we know up front are likely to be rate limited.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by ryanslade** [comment]
This is low priority as can be seen by the fact that it's been missed for a few iterations. It'll only become an issue when we have customers using campaigns at a level where syncing them causes us to consistently hit our internal rate limit.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by ryanslade** [comment]
I've increased the estimate for this issue since we first need to change our code to have one changeset syncer per code host, not per external service. The reason for this is that rate limiting is done per code host so each syncer needs to own the schedule related to each rate limiter.

**Comment by ryanslade** [comment]
The more I think about this issue the more I think it's just adding complexity without much benefit.

The idea is that we can use feedback from the rate limiter to more intelligently schedule future work. The issue is that the rate limit at any point in time is not predictable. We can predict the limit for the changeset syncer in isolation, but it's not the only user of the limiter. Permission syncing currently also uses it and in future it is likely that we have global rate limiters in place used for all outbound requests to code hosts.

Also, changeset syncing is a background process. If we attempt to run a sync and we would exceed our rate limit, we simply wait. The items are still in priority order so we'll get to them as quickly as the limiter allows.

I think trying to make it too intelligent at this point isn't worth it, especially as we are probably going to have to change the way it works when we scale our repo updater and make the limiters global.

@tsenart What do you think, given that you were keen on this feature originally?

**Comment by tsenart** [comment]
> @tsenart What do you think, given that you were keen on this feature originally?

Your rationale makes sense, I think it's the right call to punt on this work now.

**Comment by ryanslade** [comment]
Ok, closing this issue.
