### ISSUE TITLE
Make campaigns accessible to non-site-admins

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#9107]
In order to get rid of the feature-flag and rollout Campaigns to all Sourcegraph customers we need better permission handling in place.

Status quo:
- Only site-admins have read+write access to campaigns
- By setting `campaigns.readAccess.enabled` site-admins can give read-only access to non-site-admins
- Campaigns have a namespace (see [code here](https://github.com/sourcegraph/sourcegraph/blob/24292af6e68bbe87578435be029c2f81d342c897/cmd/frontend/graphqlbackend/schema.graphql#L564-L565) but we currently don't present that to the user yet and simply use the current user as the namespace ([see code here](https://github.com/sourcegraph/sourcegraph/blob/24292af6e68bbe87578435be029c2f81d342c897/web/src/enterprise/campaigns/detail/CampaignDetails.tsx#L252))

When talking about permissions @christinaforney suggested in Slack that we can maybe defer on the full solution:

> Permissions: I think the short version of this is:
> * Enable as read only for all users
> * Create a user group that individuals can be added to to grant campaign edit access (in addition to admins having this by default)
> * One thing that this doesn't take into consideration is repository permissions - we got around the read only scenario because a customer doesn't have any repo auth restrictions (everyone can see everything).

It turns out that [RFC 36 already contains a section about permissions](https://docs.google.com/document/d/1DKWy2zC6_rDZzoPS7ASUpvnVDK3Zj6cf_I9Riq9KNu0/edit#heading=h.vikdh9q69nm8) that is not _that_ much more complicated and makes use of the namespace:

> - A campaign is owned by a "namespace", which currently means either a user or organization.
>   - For a user-owned campaign, the owner and all site admins may view and modify it.
>   - For a organization-owned campaign, all organization members and all site admins may view and modify it.
> - Out of scope for this RFC:: Allowing campaigns to be read (but not modified) by certain users or unauthenticated users.
> - Repository permissions must be respected.
>   - All of a user's read and write operations on a campaign must not elevate the user's privileges. For example:
>   - A user who isn't authorized to view repository X must not be able to see a campaign's diffs or changesets in repository X.
>   - A user who isn't authorized to push to repository X must not be able to cause Sourcegraph to push to repository X by creating/updating a campaign.

But it also mentions this:

> DISCUSS: How best to achieve this? A simple temporary solution (that respects permissions 100% but isn't as flexible/powerful) is OK.
> - Consider this case: Suppose 3 repositories (X, Y, and Z) all contain "foo", and we want to replace "foo" with "bar". Suppose Alice is authorized to view repositories X and Y. Suppose Bob is authorized to view repositories Y and Z. Alice creates the campaign, which opens changesets on repositories X and Y.
>   - If Bob views the campaign, what does he see? He must not be able to see the changeset on repository X.
>   - If Bob updates the campaign (e.g., to replace "foo" with "qux"), what happens to the changeset on repository X? Is a new changeset opened on repository Z?
>   - Suppose Carol isn't authorized to see any of those repositories, but she can view the campaign. What does she see? It seems bad if she sees "0 changesets open" and closes the campaign because she (erroneously) thinks it's complete.
> - Customer/product input: Generally customers like the idea of people who can't read/write to a repository being able to propose sufficiently general refactors to it. One extreme but common case of this is an open-source author releasing a new library version and "proposing" an upgrade and call-site rewrites to all dependents, including in all private repositories that the author can't view. The sensible way to handle these "one-way changes" is probably to make them opt-in by the authors of the more-restrictive target repository. You could see a list of proposed changes to your private repository from all active campaigns, and if you accepted one, you could also opt-into accepting all future changes from that campaign. Arbitrary code execution may be required to even determine if a campaign would have a proposed change to a repository, so we would need heuristics or ranking mechanisms to determine whether to prompt the private repository author to run a given campaign's code to compute a possible change.

(cc @sqs since you wrote this part of the RFC)

---

I think the ideas presented in RFC 36 are doable, especially after the move to src CLI, which uses our GraphQL API to search for repositories, which means users only have access to repositories they have permissions for.

In order to rollout Campaigns we need to:

1. Implement the permission model mentioned in RFC 36, which requires  **writing a technical RFC** that takes namespaces/repository-permissions into account for read/write access to campaigns/changesets when reading/creating/updating/deleting/closing and **implementing it**
2. Come up with a simpler solution

**Comment by unknwon** [comment]
My rough thoughts on:
>Consider this case: Suppose 3 repositories (X, Y, and Z) all contain "foo", and we want to replace "foo" with "bar". Suppose Alice is authorized to view repositories X and Y. Suppose Bob is authorized to view repositories Y and Z. Alice creates the campaign, which opens changesets on repositories X and Y.
>- If Bob views the campaign, what does he see? He must not be able to see the changeset on repository X.
>- If Bob updates the campaign (e.g., to replace "foo" with "qux"), what happens to the changeset on repository X? Is a new changeset opened on repository Z?
>- Suppose Carol isn't authorized to see any of those repositories, but she can view the campaign. What does she see? It seems bad if she sees "0 changesets open" and closes the campaign because she (erroneously) thinks it's complete.

- Alice sees X, Y
- Bob sees Y and "1 changeset that are not authorized to see"
- Carol sees "2 changesets that are not authorized to see"

When Bob adds changeset for Z:
- Alice sees X, Y, and "1 changeset that are not authorized to see"
- Bob sees Y, Z, and "1 changeset that are not authorized to see"
- Carol sees "3 changesets that are not authorized to see"

**Comment by keegancsmith** [comment]
I think saying the number of changesets you can't see might be regarded as leaking information. However, I think making it clear there are other non-visible changesets makes sense to me. Also if someone can't see all the changesets, should they be allowed to close the campaign? I would think no. So think of the changeset list the same as the list of repos in an org. I think that should be an alright model to copy?

A simple idea for v1. When creating a campaign a user can specify if everyone can read it or just themselves + admins. Additionally they can toggle that. IE private vs public campaigns.

**Comment by mrnugget** [comment]
Regarding the "masking" of information like

>     * "2 changesets that are not authorized to see"

and

> making it clear there are other non-visible changesets makes sense to me. 

I wonder: how will we represent that in the API? Right now you can query a changeset `node(id: "foobar"): ExternalChangeset` — how do we represent "masked" information? Do we need to add another field to all of our queries, e.g. "securityNotices", that contains things like "Some of the changesets in this campaign are not visible to you"?

>  So think of the changeset list the same as the list of repos in an org. I think that should be an alright model to copy?

That's what I was thinking of. Except, of hourse, here it's a bit more complicated because we'd need to join everything against repositories/permissions.

**Comment by unknwon** [comment]
🤔 I think the first question we need to answer is, should a user ever allow to know there are changesets she/he couldn't see? From repo perms model, the user should never know.

Thus only users who have full access to all changesets are able to close the campaign and others may be able to update the changesets based on repos they can see.

**Comment by mrnugget** [comment]
Closing this in favor of the proposal in [RFC 157](https://docs.google.com/document/d/1-Ed6s3yiB-pmL7Up8H6nMlUhgmLn5BVu34Zpvf-_YNo/edit)
