### ISSUE TITLE
Report scheduled time of next changeset sync

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#9108]
We should allow clients to find out when the next scheduled sync is for a specific changeset.

We can expose it in the GraphQL API as follows:

```graphql
type ChangesetSyncSchedule {
    # Time of next scheduled sync
    scheduled: DateTime
    # Position in queue, 0 indexed
    position: Int
}

type Query {
    # Changeset Sync Schedule data
    changesetSyncSchedule(changesetID: ID!): ChangesetSyncSchedule
}
```

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
