### ISSUE TITLE
No hover tooltips on diff pages in webapp

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#9114]
- **Sourcegraph version:** master @ sourcegraph.com
- **Platform information:** macOS 10.15.3 Chrome 80

#### Steps to reproduce:

1. Go to any diff page, like a repo commit page (https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/cfe045539c084bfb15e6d5e7b091b189bcb1c9bd)
2. Hover over tokens to get hover information

#### Expected behavior:

A hover tooltip appears

#### Actual behavior:

Nothing happens

Also, it seems like the three listeners here are unused: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@e65b9d368371e9682d52a7e1f5f5215ab6d5bed4/-/blob/web/src/components/diff/FileDiffHunks.tsx#L191

**Comment by felixfbecker** [comment]
Cannot repro anymore
![image](https://user-images.githubusercontent.com/10532611/82895409-7b203900-9f54-11ea-80c9-87e7c2de093c.png)
