### ISSUE TITLE
New campaign form shouldn't show filtering for changesets

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#9122]
When I create a new Campaign from a plan, I see this:

<img width="1258" alt="Screen Shot 2020-03-18 at 15 30 35" src="https://user-images.githubusercontent.com/1185253/76971461-82f8a700-692d-11ea-82c6-594ad5d28827.png">

The filtering doesn't have an effect, I assume, since none of the changesets has been created yet and doesn't have a state/review state etc.

**Comment by eseliger** [comment]
Closed by #9055
