### ISSUE TITLE
Search bar looses focus after whole page is loaded

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#9124]
1. I go to https://k8s.sgdev.org/github.com/sourcegraph/sourcegraph
2. I see the search bar and my cursor in it
3. I start typing
4. Rest of the page loads
5. Another search bar steals focus and the rest of my query ends up in wrong search bar

Recording of the incident:

![search_bar_looses_focus](https://user-images.githubusercontent.com/1185253/76973307-0ddaa100-6930-11ea-8cfc-b42f5dec6eb4.gif)

**Comment by felixfbecker** [comment]
https://github.com/sourcegraph/sourcegraph/pull/4817#issuecomment-508915775

@christinaforney wdyt about reopening that PR?

**Comment by mrnugget** [comment]
+100 on removing the second search bar.

**Comment by attfarhan** [comment]
Also think that PR is a good idea

**Comment by christinaforney** [comment]
Yeah, we should definitely revive it! There were a few pieces of functionality remaining that I didn't know how to handle, but it was a chunk of the way there. Feel free to take over my old PR!

**Comment by lguychard** [comment]
Fixed by https://github.com/sourcegraph/sourcegraph/pull/9225 - this second search bar is now removed.
