### ISSUE TITLE
Search bar steals "Cmd+L" keybinding

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#9125]
1. Go to https://k8s.sgdev.org/github.com/sourcegraph/sourcegraph
2. Click in the new search bar at the top
3. Hit Cmd+L which I use in Firefox to select the browser's location
4. Text in the search bar is selected

What I expected:

4. Location in browser's location bar is selected

**Comment by attfarhan** [comment]
@mrnugget I can't repro this, what version of Firefox?

Maybe also check if this persists if you turn off the `smartSearchField`? We definitely did not add cmd+L as a custom keybinding for focusing the search bar, but I imagine Monaco has a lot of keybindings

**Comment by mrnugget** [comment]
I'm on Firefox `74.0 (64-bit)`.

If I turn off `smartSearchField` Cmd+L works again.

I also noticed that the settings-Monaco-editor also steals Cmd+L.

**Comment by attfarhan** [comment]
I missed step 2 and I can repro. Opened https://github.com/sourcegraph/sourcegraph/pull/9150 to fix.

**Comment by attfarhan** [comment]
@lguychard I tried fixing this but didn't find an "easy" solution. I also noticed Cmd+F and any other default browser keybindings won't work, despite disabling the Monaco keybindings. Any ideas on how we work towards allowing browser shortcuts to still work when the monaco input is focused?

**Comment by lguychard** [comment]
The only way to unbind default Monaco keybindings is currently quite hacky, so hadn't resorted to it yet - see https://github.com/microsoft/monaco-editor/issues/287

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by sqs** [comment]
It also steals the Ctrl+T/Cmd+T keybinding (for "new tab"). I notice this quite often now and it is inconvenient.

**Comment by mrnugget** [comment]
That was what made me disable `smartSearchField` locally. I'd consider this a blocker for further rollout.
