### ISSUE TITLE
one saved search runs _very_ often against indexed search on sourcegraph.com

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#9132]
This is likely a bug in saved searches. I was watching the indexed search logs and noticed this query kept coming up:

```
2020/03/18 19:29:38 DBUG: search q=(and (reposet github.com/sourcegraph/sourcegraph) file_regex:"(?-s:.)*mp4") Options{EstimateDocCount=false Whole=false ShardMaxMatchCount=10000 TotalMaxMatchCount=10000 ShardMaxImportantMatch=1500 TotalMaxImportantMatch=2500 MaxWallTime=20s MaxDocDisplayCount=2000} Stats{ContentBytesLoaded=0 IndexBytesLoaded=0 Crashes=0 Duration=832.204µs FileCount=0 ShardFilesConsidered=0 FilesConsidered=0 FilesLoaded=0 FilesSkipped=0 ShardsSkipped=0 MatchCount=0 NgramMatches=0 Wait=1.838µs}
```

It runs in bursts, then goes quite for a while. I assumed it must be a saved search, and indeed it is:

```
# select * from saved_searches where query like '%mp4%';
-[ RECORD 1 ]-----+---------------------------------------------------------------------------------
id                | 362
description       | Alert me when a new file is added that is a video
query             | repo:sourcegraph/sourcegraph$ file:.*mp4 type:path patternType:literal type:diff
created_at        | 2020-01-15 00:14:17.491181+00
updated_at        | 2020-01-15 00:14:17.491181+00
notify_owner      | t
notify_slack      | f
user_id           | 7432
org_id            |
slack_webhook_url |
```

Notice that the saved search query is for `type:diff`. I don't know how to debug further, since I am unfamiliar with the code. @slimsag maybe you can point someone in the right direction? Hopefuly benign issue, but may indicate a bigger bug in saved searches.

**Comment by slimsag** [comment]
What is the reason `type:diff` searches would go to indexed search at all? Is that intended? Note that saved searches literally just issues searches via the GQL API: https://github.com/sourcegraph/sourcegraph/blob/master/cmd/query-runner/graphql.go#L125

**Comment by slimsag** [comment]
> It runs in bursts, then goes quite for a while.

The saved searches logic is actually really dumb, and that is likely the cause. It runs all of a user's saved searches at once every 5s:

https://github.com/sourcegraph/sourcegraph/blob/master/cmd/query-runner/main.go#L108-L134

The good news is it always specifies `before:` and `after:` to only capture the new results (saved searches do not allow queries that are not `type:diff` or `type:commit`), which is what makes it not kill all of Sourcegraph with queries. But yeah -- still a lot, and we could probably be smarter about how things happen here.

Probably the starting point here would be to check how many instances of this query are in the DB, and then check

**Comment by keegancsmith** [comment]
no idea why it does an indexed search, would have to investigate.

ok every 5s explains it. Thats alright for now. I'm gonna close this out, but will follow-up on why indexed search is getting called.
