### ISSUE TITLE
search input: no debouncing done on suggestions

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#9133]
I was monitoring indexed-search logs and noticed as I typed a query we would send every substring as a search query. I would of expected some debouncing here. See the recording of logs and search at the same time in production.

![Kapture 2020-03-18 at 22 05 48](https://user-images.githubusercontent.com/187831/77002733-a9860480-6964-11ea-8857-cd4ed8c6e9b9.gif)

Note: we have 3 replicas, so each query will be logged 3 times.

Not only do we do a query for every prefix of the "hello world" I typed above quickly, but for each prefix we do two separate queries:
- check for content or path matches
- check for symbol matches

When there is 1 token, we additionally check for path matches (which we already do above). So our suggestions code is heavily overloading our zoekt instances:

Proposal:
- Only do suggestions once our token length is 3 or more.
- debounce, ie only query for suggestions after 300ms of the user not typing.
- audit the suggestion code so it doesn't do unneccessary/broken work.

This might be a contributing factor to https://github.com/sourcegraph/sourcegraph/issues/9001

Feel free to break this out into smaller issues.

Here is the full list of zoekt queries sent for me typing "hello world" without hitting enter (ie only suggestions)

<details>

```
grep -o 'q=.*Options' kubernetes.txt | sort | uniq   
q=(and (reposet github.com/kubernetes/kubernetes) (and regex:"(?-s:.)" file_substr:"h")) Options
q=(and (reposet github.com/kubernetes/kubernetes) (and regex:"(?-s:.)" file_substr:"he")) Options
q=(and (reposet github.com/kubernetes/kubernetes) (and regex:"(?-s:.)" file_substr:"hel")) Options
q=(and (reposet github.com/kubernetes/kubernetes) (and regex:"(?-s:.)" file_substr:"hell")) Options
q=(and (reposet github.com/kubernetes/kubernetes) (and regex:"(?-s:.)" file_substr:"hello")) Options
q=(and (reposet github.com/kubernetes/kubernetes) regex:"(hello)(?-s:.)*?(w)") Options
q=(and (reposet github.com/kubernetes/kubernetes) regex:"(hello)(?-s:.)*?(wo)") Options
q=(and (reposet github.com/kubernetes/kubernetes) regex:"(hello)(?-s:.)*?(wor)") Options
q=(and (reposet github.com/kubernetes/kubernetes) regex:"(hello)(?-s:.)*?(worl)") Options
q=(and (reposet github.com/kubernetes/kubernetes) regex:"(hello)(?-s:.)*?(world)") Options
q=(and (reposet github.com/kubernetes/kubernetes) substr:"h") Options
q=(and (reposet github.com/kubernetes/kubernetes) substr:"he") Options
q=(and (reposet github.com/kubernetes/kubernetes) substr:"hel") Options
q=(and (reposet github.com/kubernetes/kubernetes) substr:"hell") Options
q=(and (reposet github.com/kubernetes/kubernetes) substr:"hello") Options
q=(and (reposet github.com/kubernetes/kubernetes) sym:regex:"(hello)(?-s:.)*?(w)") Options
q=(and (reposet github.com/kubernetes/kubernetes) sym:regex:"(hello)(?-s:.)*?(wo)") Options
q=(and (reposet github.com/kubernetes/kubernetes) sym:regex:"(hello)(?-s:.)*?(wor)") Options
q=(and (reposet github.com/kubernetes/kubernetes) sym:regex:"(hello)(?-s:.)*?(worl)") Options
q=(and (reposet github.com/kubernetes/kubernetes) sym:regex:"(hello)(?-s:.)*?(world)") Options
q=(and (reposet github.com/kubernetes/kubernetes) sym:substr:"h") Options
q=(and (reposet github.com/kubernetes/kubernetes) sym:substr:"he") Options
q=(and (reposet github.com/kubernetes/kubernetes) sym:substr:"hel") Options
q=(and (reposet github.com/kubernetes/kubernetes) sym:substr:"hell") Options
q=(and (reposet github.com/kubernetes/kubernetes) sym:substr:"hello") Options
```

</details>

**Comment by rvantonder** [comment]
@keegancsmith, @attfarhan what is the historic context of search suggestions, as in:
- when was it added?
- what is the scope of search suggestions? It looks like it might only be files: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@85b937558b2bcab950e8c69b0cbba61d9bafe509/-/blob/cmd/frontend/graphqlbackend/search_suggestions.go#L265
- is anyone currently employed at Sourcegraph familiar with this code path?

I ask because nothing around suggestions have changed that I'm aware of on backend, and I'm not familiar with it, and can't propose a solution to this without the proper context. Maybe there have been changes on frontend that factor into this, and solvable from the webapp side as a quickfix.

**Comment by rvantonder** [comment]
The proposals above sound reasonable, but it'd be valuable to know the context on how this feature was introduced.

**Comment by keegancsmith** [comment]
most important are the frontend changes. The backend changes required are more just peculiarities of suggestion doing more work than needed. I think no one really understands all of suggestions code (except maybe @sqs), so that context will have to be gleaned through the code.

**Comment by slimsag** [comment]
> when was it added?

Several years ago.

> what is the scope of search suggestions?

- Files containing text matching your query: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@85b937558b2bcab950e8c69b0cbba61d9bafe509/-/blob/cmd/frontend/graphqlbackend/search_suggestions.go#L259-286
- Symbols matching your query: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@85b937558b2bcab950e8c69b0cbba61d9bafe509/-/blob/cmd/frontend/graphqlbackend/search_suggestions.go#L191-257
- If the query has `repo:` field, suggestions for which `lang:` filters you might specify based on the languages in that repository: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@85b937558b2bcab950e8c69b0cbba61d9bafe509/-/blob/cmd/frontend/graphqlbackend/search_suggestions.go#L124-189
- Files whose names match your query: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@85b937558b2bcab950e8c69b0cbba61d9bafe509/-/blob/cmd/frontend/graphqlbackend/search_suggestions.go#L105-122
- Repositories whose name matches your query: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@85b937558b2bcab950e8c69b0cbba61d9bafe509/-/blob/cmd/frontend/graphqlbackend/search_suggestions.go#L63-103

It was added out of need and very hacked together, and not out of any proper design. It effectively fires off several searches for every query you type, so it does not surprise me that it is a problem for us. Additionally, the suggestions you do get are quite poor in practice for several reasons.

In the past, it has been a MAJOR source of performance regressions for us, e.g. see https://github.com/sourcegraph/sourcegraph/pull/3685

> is anyone currently employed at Sourcegraph familiar with this code path?

Quinn wrote it technically, it has been hodge podged together by multiple people over the years and as you might guess at this point the answer is "yes, me :("

**Comment by slimsag** [comment]
(And yes, Keegan is correct here that the web/frontend side issuing these requests is the most significant issue here)

**Comment by keegancsmith** [comment]
@sourcegraph/web it would be great to get debouncing triaged and fixed for 3.15 / patch release soon. Likely a source of bad perf, and contributing to quite a few of the perf issues @slimsag and I have been investigating at customers over the last few weeks.

**Comment by eseliger** [comment]
I think this is only happening with the smart search field as the fetch is promisified and not cancellable (nor throttled) cc @lguychard

**Comment by keegancsmith** [comment]
I just checked sourcegraph.com in incognito mode, and looking at the network panel we are very very chatting as well w.r.t. suggestions. This might explain why sourcegraph.com has been so slow over the last few days/week (cc @beyang)

**Comment by slimsag** [comment]
This is indeed NOT an issue if you have the following in your configuration:

```
  "experimentalFeatures": {
    "smartSearchField": false
  },
```

However, this is indeed a severe issue on Sourcegraph.com for all users (it is on for all users there). Every key stroke issues a new request.

**Comment by lguychard** [comment]
Will fix frontend today.
