### ISSUE TITLE
More thorough E2E tests for campaigns

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#9138]
Handle visual regressions and test actual workflows.
Possibly some of the tests would need to go into a regression test suite, since they are quite dependent on external services

**Comment by mrnugget** [comment]
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/9102? Am I correct in assuming that you want to do this? If so, I'll close my ticket.

**Comment by eseliger** [comment]
I wanted to track it separetely, as on the one hand there needs to be the actual tests written by the web team probably, and on the other hand I assumed that we need some work from core services also, to enable making it all testable properly. I might be wrong though, and if you want to tackle the e2e tests, please do so, I just wanted to keep track of that someone should do that this iteration.

**Comment by eseliger** [comment]
We don't do those anymore, should investigate integration tests in the future
