### ISSUE TITLE
Bitbucket Server webhooks miss needs work => unapproved

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#9139]
Currently, the webhooks by Bitbucket Server don't trigger when the review status is changed from "needs work" to "unapproved". The reason for that is, that we listen for `PullRequestActivityEvent`s, not `PullRequestEvent`s. That's what is reflected in the activity log, but for some reason BBS doesn't log unapproved after approved.

![image](https://user-images.githubusercontent.com/19534377/77028435-0b606180-6999-11ea-9ec7-8643fda57371.png)

I think the completely correct behavior would be to not listen for the activity events but PR events in general and do proper filtering. This would require some adjustment to the code parsing the webhook payload also.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by ryanslade** [comment]
I'm digging into this now, leaving comments here to document the events that are fired:

No review -> Needs work:
* PullRequestActivityEvent, Action -> `REVIEWED`
* PullRequestParticipantReviewedEvent, Action -> `REVIEWED`

Needs work -> No review
* PullRequestParticipantUnapprovedEvent, Action `UNAPPROVED`

No review -> Approve
* PullRequestActivityEvent, Action -> `APPROVED`
* PullRequestParticipantApprovedEvent. Action -> `APPROVED`

Approved -> No review
* PullRequestActivityEvent, Action -> `UNAPPROVED`
* PullRequestParticipantUnapprovedEvent, Action `UNAPPROVED`

Needs work -> Approved
* PullRequestActivityEvent, Action -> `APPROVED`
* PullRequestParticipantApprovedEvent. Action -> `APPROVED`

Approved -> Needs work
* PullRequestActivityEvent, Action -> `REVIEWED`
* PullRequestParticipantReviewedEvent, Action -> `REVIEWED`

All changes fire two events, except Needs work -> No review (as @eseliger) mentioned.

**Comment by eseliger** [comment]
Yes that is because we are listening for `ActivityEvents`, but that doesn't put an activity in the timeline 👀 There was some other event though that was triggered 🤔

**Comment by ryanslade** [comment]
Yep, that's what I've started doing but I didn't realise it was sending duplicated events so I'll do some deduping too. I'm also going to include the "Action" field in the event as we aren't currently.
