### ISSUE TITLE
Handle renames and deletions of mirrored repositories

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#914]
This is an umbrella issue that covers generally cleaning up the problem where code host entries in site config (and `repos.list`) merely create repositories, they do not "manage" the active set of repositories. This causes the following (specific) problems:

- If a GitHub token is used and grants access to repos `a` and `b`, then the token's owner no longer has access to `b`, the `b` repo remains on the Sourcegraph instance (but is not git-updated)
- If a repository is renamed on the code host, both the old and new repos will be added on Sourcegraph
- If a repository is deleted on the code host, it remains on Sourcegraph (from the backend POV, this is equivalent to the token-no-longer-can-access case above)
- If a repository's metadata is changed such that it is no longer in the set of repositories-to-sync (e.g., a GitHub [`repositoryQuery`](https://docs.sourcegraph.com/admin/site_config/all#repositoryquery-array) excluding archived repos and a someone archives a repo on GitHub), it remains on Sourcegraph

Fixing this issue also addresses the following problems:

- https://github.com/sourcegraph/sourcegraph/issues/383
- https://github.com/sourcegraph/sourcegraph/issues/368
- https://github.com/sourcegraph/sourcegraph/issues/108

In general, the principle we want is: "You tell Sourcegraph which repositories you want on Sourcegraph. Sourcegraph upholds that contract continuously." So if you want archived repositories to not exist on Sourcegraph, then you need to specify a [`repositoryQuery`](https://docs.sourcegraph.com/admin/site_config/all#repositoryquery-array) that omits archived repositories. If a GitHub repository is archived, then Sourcegraph will automatically remove it. Another way to say this is that the site config is essentially a constraint you specify that Sourcegraph always seeks to satisfy in the current instant.

### Robustness

However, we don't want this to result in data loss. It needs to be robust to (1) unexpected errors from the code host API and (2) typos in site config. If one of those things happens and suddenly a previously included repository is no longer included, we do not want to permanently delete all data associated with the repository. (Today this really just includes code discussions but will likely include other info in the future.) So if Sourcegraph detects that a repository is no longer included, it should *disable* it on Sourcegraph.

This entails another addition, I think: there should be a "disable reason" to explain to site admins why a repo was disabled (e.g., "repository deleted on GitHub.com" or "repository not included by repositoryQuery")

Of course, this should be smart in the case of renames; if there is a rename, it should just rename the repo on Sourcegraph, too, not disable the old name and create a new repo with the new name.

**Comment by keegancsmith** [comment]
We should make the repos table the source of truth for everything that reads repo information, but repo-updater responsible for maintaining the repos table (via config + syncing from codehost). We are actually quite close to this, we just don't have repo-updater reading the full repos table and making decisions about disabling/updating/etc. Currently it only reads from code hosts.

**Comment by nicksnyder** [comment]
To solve all of the above problems well, we need to have a first class model for "Code host connections" and each row in the repo table will be owned by a single code host connection.

A code host connection should have a stable ID that is independent from information that might need to change about that code host connection (e.g. access token). Requiring a user to manage connection ids in a config file is error prone and hard to document, so the proposal is to create a new database table (with an auto increment id). Users can then update an expired/revoked access token without causing a lot of churn in the db.

We don't have a lot of time between now and when we want to ship 3.0-preview and it is important to get the breaking changes in now.

Plan for 3.0-preview
- [ ] Remove all UI paths to manually add repos
    - Preserve behavior that user visiting repo for first time will have it transparently added on sourcegraph.com
    - Deploy to sourcegraph.com and dogfood
- [ ] Remove repo code host configuration from site config and move it into a new database table
    - Each row is a codehost connection with a stable (auto incremented) id.
    - Manual config/db migration for sourcegraph.com and dogfood (deploy to sourcegraph.com and dogfood)
- [ ] Bare bones UI for editing code host connections.
    - List of connections
    - Editing a connect is just a raw text box that contains the json that was previously in the config
- [ ] Remove repos.list and github.list

**Comment by sqs** [comment]
Added needs-design label for "Create UI to create/edit codehosts" @francisschmaltz

**Comment by nicksnyder** [comment]
@francisschmaltz I updated the PR description with an animated gif of the current state

**Comment by sqs** [comment]
I moved this to milestone **3.0** on the roadmap and added the [External services UI #1103](https://github.com/sourcegraph/sourcegraph/pull/1103) subset to **3.0-preview**.

**Comment by sqs** [comment]
Some subset of this and other repository-related work will be planned for 3.1 and described at #2025; see #2025 for more info.

**Comment by sqs** [comment]
@sourcegraph/core-services Can you close this issue since #2025 is more up to date and covers the same stuff?
