### ISSUE TITLE
Campaigns splash screen

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#9140]
For first time campaigns users and customers that don't have a tier with access to campaigns yet, show an informative splash screen that describes the campaigns feature.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
