### ISSUE TITLE
k8s: upgrade deprecated apis

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#9148]
We have lots of uses of deprecated APIs. See https://sourcegraph.sgdev.org/search?q=f:%28DaemonSet%7CDeployment%7CReplicaSet%7CStatefulSet%7CNetworkPolicy%29+count:1000+apiVersion+/v1beta&patternType=regexp#50

The notice about this is at https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/ (which GKE is upgrading to very soon).

Notice that most of our hits are on our kube-backup repo. This reflects what we actually run in production. It seems a lot of our resources are old.

**Comment by ggilmore** [comment]
@keegancsmith I think there is some wierdness happyening with kube backup. It's still reporting that dogfood's sourcegraph-frontend is running an older api version when it clearly has been updated:

- https://github.com/sourcegraph/kube-backup/blob/e30436dc0342420e9fe0f49c3bc7df7cb08c595d/dogfood/default/sourcegraph-server.deployment.yaml#L1

- https://github.com/sourcegraph/infrastructure/blob/fb638236b79550e9ea04535be0b636cc8f8ee48f/kubernetes/dogfood/server/sourcegraph.Deployment.yaml#L1

Then again, I noticed that the api version of some resources doesn't seem to change when I apply them. Example, I updated  the api version of dot-com's ingress definition: https://github.com/sourcegraph/deploy-sourcegraph-dot-com/commit/ef5b98dc49073c09a3d6707bfa7ce4d89ecb47e9 . `kubectl` doesn't complain when I apply it. However, the kubernetes api server is still reporting the outdated version:

```
kubectl --namespace=prod get ingress sourcegraph-frontend -o=json | jq '.apiVersion'
"extensions/v1beta1"
```

**Comment by keegancsmith** [comment]
> Then again, I noticed that the api version of some resources doesn't
> seem to change when I apply them.

I did some research and there seems to be some magic here. Quoting on
https://github.com/kubernetes/kubernetes/issues/62283#issuecomment-380968868

> kubectl get uses server-preferred order, which will prefer the
> extensions API group for backward compatibility, until extensions is
> removed. That is to say, kubectl get deployment uses extenions/v1beta1
> endpoint by default.
>
> To get deployments under apps API group, you can use kubectl get
> deployment.apps, which returns you apps/v1 deployments.

This is a bit confusing, but if you explicitly request `deployment.apps`
we get back all our deployments. I think we can assume we are on the
correct version and can close this issue.

Validated by getting no output with this command:

```shell
diff \
  <(kubectl --all-namespaces=true get deploy) \
  <(kubectl --all-namespaces=true get deployment.apps)
```

**Comment by ggilmore** [comment]
Closing - I believe that we addressed this with recent updates

**Comment by mailjunze** [comment]
https://github.com/terraform-providers/terraform-provider-kubernetes/issues/573#issuecomment-640122067
