### ISSUE TITLE
Panel title from hover is too large

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#915]
The panel title is supposed to just be the type signature. But it is showing the full docstring there now for some reason. That means can't see very many references without scrolling, which is annoying. (Probably because we now jam them together in the hover response?)

![image](https://user-images.githubusercontent.com/1976/48294006-9f7df880-e436-11e8-99c7-05e0925a6f9c.png)

@felixfbecker you might have an idea of how best to fix this; if so, go for it

**Comment by felixfbecker** [comment]
I don't know how the panel is implemented, where does it get its content from? The new server uses the non-deprecated `MarkdownContent` only, and seperates sections with horizontal rules (`---`/`<hr>`). The UI should really never make assumptions about the structure of hover contents.
