### ISSUE TITLE
repo-updater: remove the use of `dbconn.Global` for getting external services

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#9156]
https://github.com/sourcegraph/sourcegraph/blob/8ac72992739396ff92403bea2458d2c84a468ce3/enterprise/cmd/repo-updater/main.go#L69-L70

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by unknwon** [comment]
Moving to backlog for now because reimplement the same method isn't ideal, researching a better approach.

**Comment by unknwon** [comment]
This will be fixed by https://github.com/sourcegraph/sourcegraph/pull/15530 so closing it.
