### ISSUE TITLE
Syntax highlighting for diff hunks

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#9166]
Implement syntax highlighting for diff hunks. As we use diff views more and more with campaigns really coming together, I'm feeling that proper syntax highlighting here would add a ton of value. 

While hacking something together using highlightjs in the `DiffHunk` component, it became clear that this adds a high value in legibility.

Before:
![image](https://user-images.githubusercontent.com/19534377/77093340-2075d880-6a0b-11ea-98e2-c52caaf74e6b.png)

After:
![image](https://user-images.githubusercontent.com/19534377/77093097-cd9c2100-6a0a-11ea-8661-61b09b641c23.png)

**Comment by slimsag** [comment]
This should really be done with our backend syntax highlighter and not highlightjs

**Comment by eseliger** [comment]
That’s the plan the screenshot was just to verify how much value it adds

**Comment by mrnugget** [comment]
I'll take this on in 3.16, timeboxed, because I'm not sure yet what's involved.
