### ISSUE TITLE
Implement concat search pattern semantics for literal, regexp, structural search

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#9171]
This issue tracks implementing the branching the logic for concat on search patterns. For example, literal search concatenates whitespace, regexp search concatenates `(.*)?`, etc., and requires testing. Each respective search pattern type (literal, regexp, structural) can be chunked up into 0.5 or 1d tasks.

An example of why this issue is distinctly tracked: consider the literal pattern `foo bar baz`. It implies `foo<single space>bar<single space>baz`. Our current implementation treats whitespace sensitively. 

In time we may not necessarily want to _exactly_ match whitespace (e.g., to the exact number of spaces), but rather just match the presence of whitespace. There is some existing feedback/request that we be more flexible with handling whitespace in search patterns, and the concat semantics is the place to introduce such a change.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by rvantonder** [comment]
Superseded by #9846 and #9249. Can still be improved by removing the references in our codebase to `getPatternInfo` entirely.
