### ISSUE TITLE
ci: re-enable go linting

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#9193]
go linting is using too many resources and is being killed by the OS and blocking CI. So it has been disabled. We need to re-enable it otherwise our codebase will slowly descend into chaos :)

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by keegancsmith** [comment]
@ggilmore did you intend on tackling this in 3.16? Either way not tied to release and maybe something to do soon.

**Comment by tsenart** [comment]
I'd like to bump this up in priority. What is the issue here? Can't we just give more memory to CI nodes?

**Comment by tsenart** [comment]
@ggilmore: Please advise.

**Comment by tsenart** [comment]
FYI, I'm playing with running golang-ci as a GitHub action.

**Comment by keegancsmith** [comment]
I suggest we get rid of golang-ci and rather just run staticcheck. Most of the valuable checks are done by staticcheck, and the developer for that cares a lot more about memory use/etc. We can then additionally also run some other linters like errcheck (if we are clean for that again).

**Comment by unknwon** [comment]
> FYI, I'm playing with running golang-ci as a GitHub action.

An example in case useful: https://github.com/gogs/gogs/blob/280b06485f3f1719f5d8d3766ca6c2e1d34b6295/.github/workflows/go.yml#L10-L18
