### ISSUE TITLE
bitbucketServer option to ignore user repositories

### ISSUE THREAD

**Issue by terinjokes** [sourcegraph/sourcegraph#92]
The `bitbucketServer` configuration provides no mechanism to exclude user repositories/forks, so they will be cloned alongside the main repositories.

It would be great if a configuration option was added to ignore them, so I don't have to occasionally find them all to disable.

**Comment by sqs** [comment]
Thanks! We do this for GitHub and should add support for this for all code hosts.

**Comment by sqs** [comment]
This was added a while ago. See https://docs.sourcegraph.com/integration/bitbucket_server#excluding-personal-repositories.
