### ISSUE TITLE
Creating larger campaigns using src-cli fails with 413

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#9202]
Creating a campaign that generates a quite significant amount of patches currently fails with

```
error: 413 Request Entity Too Large
<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

One solution I would see is separately pushing the patches and then combining them to one campaign plan.. For src-runner and remote execution, that's what currently happens and the behavior was not reproducible in that branch using the runners, not src-cli.

**Comment by mrnugget** [comment]
We're going to fix this with https://github.com/sourcegraph/sourcegraph/issues/10985 so I'm assigning it to myself.

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by mrnugget** [comment]
I'm closing this, since everything that prevents this is already on `master`.
