### ISSUE TITLE
Failing dev/start leaves behind tsc background process

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#9228]
![image](https://user-images.githubusercontent.com/10532611/77306713-5a3f2b80-6cf8-11ea-9f20-6c21f30849ff.png)

https://github.com/sourcegraph/sourcegraph/pull/8840 changed `tsc` to run in the background on dev/start.sh. Unfortunately this means that when dev/start fails, `tsc` is still running in the background printing to the console.

**Comment by felixfbecker** [comment]
@eseliger  This still seems to happen

![image](https://user-images.githubusercontent.com/10532611/77658751-6f75bd80-6f77-11ea-88e7-0758a86f9331.png)

**Comment by eseliger** [comment]
Hmm twice? 🤔 can you give me a way to reproduce by any chance?

**Comment by felixfbecker** [comment]
Try launching dev/start without having Docker running, that will cause it to terminate before `tsc` finishes

**Comment by felixfbecker** [comment]
Or maybe it's one of the LSIF processes? cc @sourcegraph/code-intel

**Comment by felixfbecker** [comment]
I don't think it can be those though because the logs are not prefixed like this:

![image](https://user-images.githubusercontent.com/10532611/77660180-481ff000-6f79-11ea-9a5d-cb3ece2c0511.png)

**Comment by efritz** [comment]
@felix Is there action on our part here?

**Comment by eseliger** [comment]
@efritz no this is not codeintel related

**Comment by eseliger** [comment]
Ah, exec makes it so that goreman is not a child process and hence trap doesn't get triggered. I don't know the implications of making it a subprocess though

**Comment by pdubroy** [comment]
Is this issue still valid?

**Comment by eseliger** [comment]
I don't think we do this anymore, so I think no!
