### ISSUE TITLE
src-expose: fold into src cli tool

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#9243]
src-expose has a few users now. Some are wanting to follow along so they know when there is a new version/etc. We could create its own repo and do releases. However, its likely better if the tool lives in the src cli.

WDYT @dadlerj @slimsag @mrnugget?

**Comment by mrnugget** [comment]
I like the idea! `src expose` would fit in nicely, since we now also have other commands that don't directly match an API query/mutation (such as `src action exec`).

**Comment by dadlerj** [comment]
Absolutely — love this idea 👍 . Would make it feel like much more of an official feature, and head off questions like we received from https://app.hubspot.com/contacts/2762526/company/947819054 about how to keep it updated.

**Comment by keegancsmith** [comment]
Breaking change to put into the migration: serving PWD by default https://github.com/sourcegraph/sourcegraph/issues/9292

**Comment by slimsag** [comment]
Strongly in favor; I said originally it should've been a part of the `src` CLI and not a separate binary 😛

**Comment by keegancsmith** [comment]
I've put this in the backlog since I'll likely have more pressing work to do for search. I may look into this, especially if someone believes it is more pressing to do soon.

**Comment by mrnugget** [comment]
> Any conventions I am messing up in src-cli @mrnugget @slimsag?

None that I'm aware of 👍 

Minor: I think `src serve-git` might be better since `git-serve` looks like it can be a wrapper around `git serve` (if that would exist).

**Comment by keegancsmith** [comment]
> Minor: I think src serve-git might be better since git-serve looks like it can be a wrapper around git serve (if that would exist).

Sounds good to me, will update in my PR.

**Comment by keegancsmith** [comment]
src-cli master now has this, but not advertised. I'm going to close this issue out, you can follow along in https://github.com/sourcegraph/sourcegraph/issues/12363 for when it will be published.
