### ISSUE TITLE
RFC 128: Implement consistent Docker image versioning

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#9251]
Per RFC 128 ([tracking issue](https://github.com/sourcegraph/sourcegraph/issues/9250)) we should implement consistent versioning of our Docker images so that it is easy for admins to upgrade Sourcegraph and use a version of Sourcegraph released from `master` (`insiders` does not currently solve this, see the RFC for details about why.)

1. [ ] Push Sourcegraph-versioned images of images that are built in this repository (Grafana and Prometheus).
1. [ ] Push Sourcegraph-versioned images of images that are built outside this repository (zoekt-webserver, zoekt-indexserver, syntect_server, redis-store, redis-cache, pgsql, etc.)

**Comment by slimsag** [comment]
> > @keegancsmith I intend to version zoekt-* alongside Sourcegraph ASAP before the 3.15 release.
>
> What is your plan for this?

@keegancsmith the idea here is to immediately have the following images match our Sourcegraph versioning scheme:

- zoekt-webserver
- zoekt-indexserver
- redis-store
- redis-cache
- postgres-11.4
- syntect_server
- grafana
- prometheus

For 3.15 (branch cut tomorrow), this will simply be a step in our CI that takes a pinned pre-published version of these images and publishes them using the same Sourcegraph image tags so that:

- `sourcegraph/grafana:3.15.0`
- `sourcegraph/grafana:insiders`
- `sourcegraph/grafana:60878_2020-04-13_e3b1adb`

all point to a pinned `sourcegraph/grafana:10.0.14@sha256:...` image for example.

Publishing these images will still be done out-of-band for now. In the future, I envision all of these images living and being built in https://github.com/sourcegraph/sourcegraph/tree/master/docker-images with the exception of zoekt images if we want those built elsewhere.

Now, version conflicts here are non-trivial. Some of these images have version tags that conflict with Sourcegraph's version tags if we do this. Luckily:

- redis-store, redis-cache, and postgres-11.4 use `20-01-30_c903717e` format, and have never had another format published -- so no conflict here.
- syntect_server has always used `c903717e` format, so no conflict here.
- grafana and prometheus DO have conflicts, but their version numbers started at 10.x.x so luckily we won't have any conflicts until years from now (at which point it seems fine to delete said images).
- zoekt images are the only ones that are problematic, and it's because they have many different formats used in the past including `0.0.20200401202737-ef3ec23` (easy to workaround) and `2019.08.21-4e4eef5` (breaks basically all semver tooling, because `2019.08.21` is way greater in semver than `3.15.0`.

So, the only issue is zoekt, which is why I will be renaming those images following the proposal in https://github.com/sourcegraph/sourcegraph/issues/9785 that way we start with a clean slate

**Comment by keegancsmith** [comment]
> For 3.15 (branch cut tomorrow), this will simply be a step in our CI
> that takes a pinned pre-published version of these images and
> publishes them using the same Sourcegraph image tags so that:

Great, that sounds like a good plan.

> - zoekt images are the only ones that are problematic, and it's
> because they have many different formats used in the past including
> `0.0.20200401202737-ef3ec23` (easy to workaround) and
> `2019.08.21-4e4eef5` (breaks basically all semver tooling, because
> `2019.08.21` is way greater in semver than `3.15.0`.

Happy to version them in anyway. I'd propose if you are going to
republish them then maybe the zoekt repo just pushes the "go.mod"
version as the tag. Then you can pull the same version that we have in
our go.mod and we get gaurenteed consistency between our server image
and others.
