### ISSUE TITLE
RFC 128: Investigate and propose a solution for how the Slack /release command could be implemented behind the scenes

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#9252]
This issue tracks the work in RFC 128 of figuring out how the Slack `/release` command would work behind the scenes. The goal of this issue is not to actually implement the command, but to figure out the underlying data store the command would interact with which includes considerations for:

- What happens when the release process does fail (how is it resumed)?
- What happens when we must introduce a human in the loop for some reason (e.g. to approve some PR that cannot be automatically reviewed)?
- How do we provide visibility into the ongoing release process?

Prior work around automating our release process:

- #2311
- #2392
- #7148

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by bobheadxi** [comment]
Assigning to self since this is part of one of the Distribution goals [Any engineer at Sourcegraph can create a release for all of our supported deployment types by running a single action](https://about.sourcegraph.com/handbook/engineering/distribution/goals#any-engineer-at-sourcegraph-can-create-a-release-for-all-of-our-supported-deployment-types-by-running-a-single-action)

This is the first I've heard of an RFC for this (not mentioned in the goals page), I'll see if I can find it and figure out what work/exploration has already been done here.

cc @pecigonzalo

**Comment by bobheadxi** [comment]
The RFC is described here: [RFC 128 APPROVED: Frictionless release & upgrade process](https://docs.google.com/document/d/1YHYxx63jxEyLb3Hs7VnzZcASQXn3dWb6IUyQXvP2i30/edit)

I think we're pretty close:

* significant automation progress and streamlining of steps in the process
* e2e/qa tests running on all `main` commits

That said, I still see a few blockers here:

* almost all changes (including changelog) still requires a PR
  * there is some automerging tooling we can leverage to land things ASAP
* some release PRs require manual steps:
  * https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+f:dev/release+prBodyAndDraftState%5C%28+&patternType=regexp
  * a big one is probably pure-docker release

That said, I think we can get pretty close to the RFC with the adjustment:

* remove all tracking issues
* a bot identity attached to all PR automation
* everything up to and including the release PRs: `/release stage [REF]`, e.g. `/release stage main`
  * versions derived from release config on target branch, so works for patches too (`/release stage 3.23` cuts the patch from the `3.23` branch)
    * We currently never seem to cut patches for old releases, but we might need to do some validation to ensure generated docs of patches for old releases do not overwrite newer releases (e.g. "upgrading" from `3.24.0` to `3.23.1`), or rethink how we do these docs
  * Does CHANGELOG, branch cut, PR status checks, first candidate cut. If the candidate fails, it opens a `release-blocking` issue and reports to Slack. If candidate passes, it gives an okay in Slack
  * We need to ensure all release repos (e.g. `deploy-sourcegraph`) uses the same branch naming scheme (`main` for default, `3.X` for releases, etc)
* PRs reviewed and merged manually as they are now via the campaign
* everything after release PRs merge: `/release finalize [REF]`, e.g. `/release finalize 3.24`
  * versions derived from release config on target branch
  * does final tags, announcements, etc.

That said, I'm mildly confused about how this relates to the [conservative patch release philosophy](https://about.sourcegraph.com/handbook/engineering/releases#when-are-patch-releases-performed), but it might just be that with this change it will become outdated?

**Comment by pecigonzalo** [comment]
@bobheadxi sounds good, I think we should lay this out in a new project, and draft the tasks/effort. If there is some step that we cant automate, may be an interim step is to, use https://buildkite.com/docs/pipelines/block-step or github-actions equivalent, and let the user go do X, then come and unblock. We can replace the block step or remove it once that is automated as well.

Regarding the conservative patch release philosophy, I think we can revisit that in the future as there might be other considerations there.
