### ISSUE TITLE
Stabilize GraphQL API in regards to code actions

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#9260]
To stabilize the API, the GraphQL schema work should be pulled out of #8574 and completed in this iteration already.

**Comment by mrnugget** [comment]
We should do this as part of writing up an RFC. We already have a lot of the things we need to put in an RFC at hand, the only thing missing would be the implementation section.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by eseliger** [comment]
I don't think this is necessary anymore, as it turned out to be an additive system.
