### ISSUE TITLE
List styling is not consistent across features

### ISSUE THREAD

**Issue by imtommyroberts** [sourcegraph/sourcegraph#9268]
I've noticed some inconsistency in the way borders are styled in lists. I'm drawing attention to it, as I think it would be an easy fix that would increase a sense of cohesion. 

I think all lists should follow the border styling we see in lists in 'Repositories', 'Users & auth' etc (Site admin)

Examples (inside red outlines):

Manage repositores:

![image](https://user-images.githubusercontent.com/40544396/77418829-604c0f80-6dbf-11ea-9e3b-5fd5c317de01.png)

Campaigns (these two are also different to each other):

1. 
![image](https://user-images.githubusercontent.com/40544396/77418880-7063ef00-6dbf-11ea-9792-b5802d0cf216.png)

2.
![image](https://user-images.githubusercontent.com/40544396/77418921-7c4fb100-6dbf-11ea-9ec9-2e90a250aab0.png)

My proposal is that 1 and 2 (and elsewhere in campaigns and sourcegraph as a whole) should follow the list border styling in 'Manage repositories'.

Interested in hearing cases for other border styles, or reasons why it might actually be better to have separate styling in certain features.

**Comment by felixfbecker** [comment]
A difference I see between "manage repos" and number (2) is that (2) is an accordion-style list where each item is expandable. I think the "simple" repository-style border would not do well with accordion-style lists, but I might be wrong.

I agree though that (1) should probably have a consistent style with (2) - rn it's designed as individual "cards" instead of a list, which seems to just add visual noise (more lines) without adding much value.

**Comment by imtommyroberts** [comment]
Agree with @felixfbecker here. On review, I think (1) and (2) should have a consistent style (and follow  design of (2)).

I hesitated to respond sooner, because I'm not sure how we should differentiate between these two styles consistently. I think this will be something we can review over time when we look at these things in more depth.

**Comment by eseliger** [comment]
The (1) and (2) are aligned now since the recent refactors. Given your conversation, I think we can close this issue, as we won't align repos and changesets list-styles. Please reopen if you object.
