### ISSUE TITLE
https://sourcegraph.com/github.com throws a 500

### ISSUE THREAD

**Issue by sixhobbits** [sourcegraph/sourcegraph#9274]
- Sourcegraph.com

#### Steps to reproduce:

1. visit https://sourcegraph.com/github.com

#### Expected behavior:
2. A 404? 

#### Actual behavior:
3. 500 server error

**Comment by unknwon** [comment]
This only happens when `"disablePublicRepoRedirects": false`.

**Comment by keegancsmith** [comment]
@asdine This is a good first issue for you to get some familiarity with the Sourcegraph codebase and investigating Sourcegraph.com issues.

**Comment by unknwon** [comment]
@asdine FYI, #10112 fixes this specific kind of problem (i.e. only has hostname), but doesn't propose a systematic way to help us response 404 vs 500.
