### ISSUE TITLE
RFC 122: Automate indexing for public Go and TypeScript repositories

### ISSUE THREAD

**Issue by creachadair** [sourcegraph/sourcegraph#9286]
Generate LSIF indexes for the same repositories indexed in #9285, using the same CI that the original project uses (given that it’s sufficiently replicable). This may require temporarily forking repositories to update a build environment to add an indexing step.

See [Milestone 2 of RFC 122](https://docs.google.com/document/d/1W8uR0vQBYtdkNynMxEq24CFdzPTWkGijCURsosdvzAM/edit#heading=h.7xcc2xuzdrxg)

**Comment by efritz** [comment]
Now tracked in https://github.com/sourcegraph/sourcegraph/issues/9738.
