### ISSUE TITLE
RFC 122: Write detailed LSIF integration instructions for Go and TypeScript

### ISSUE THREAD

**Issue by creachadair** [sourcegraph/sourcegraph#9289]
See [Milestone 3 of RFC 122](https://docs.google.com/document/d/1W8uR0vQBYtdkNynMxEq24CFdzPTWkGijCURsosdvzAM/edit#heading=h.ylem6ffdsey1).

**Comment by gbrik** [comment]
- [ ] cleanup/collapse indexer repos
- [ ] write ci instrucitons in readmes fro those repos
- [ ] clean up orbs & actions

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
