### ISSUE TITLE
RFC 127: Implement a sharded database storage service

### ISSUE THREAD

**Issue by creachadair** [sourcegraph/sourcegraph#9290]
Introduce a new service that turns [the LSIF server's `Database` class](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@master/-/blob/lsif/src/server/backend/database.ts#L11:14&tab=references) into a network-accessible internal API. 

This will encapsulate all SQLite-query logic and expose the class’s current public methods as the methods of an HTTP API or RPC API.

See [RFC 127 Proposal C](https://docs.google.com/document/d/1lno7N_gDg2RmvI4cLZ7l_TdnxP1e-P1Ri7Iwr2RCjKQ/edit#heading=h.my06tuddqo90).

**Comment by efritz** [comment]
Implemented in https://github.com/sourcegraph/sourcegraph/pull/9179.
