### ISSUE TITLE
Add ability to remove changeset from a manual campaign

### ISSUE THREAD

**Issue by christinaforney** [sourcegraph/sourcegraph#9317]
Manual campaigns allow users to add existing changesets to a campaign. For cleanup and typos on changeset numbers, it would be nice to remove a changeset from the campaign.

@imtommyroberts - this could be a quick design for you to work on. Let me know if you have any questions. I think the important thing to note is that removal is not a primary action, so we should make sure it's in an appropriate place that it's discoverable, but not too high on the visual hierarchy (i.e. don't put a trashcan button on each changeset).

**Comment by chrispine** [comment]
This is implemented
