### ISSUE TITLE
update deploy-sourcegraph for appURL -> externalURL change

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#933]
8e9ddedab00c969ab091c0dfe35d5f7d5f490526 (#924) renamed appURL to externalURL. This change needs to also be made in deploy-sourcegraph and deploy-sourcegraph-docker.

**Comment by nicksnyder** [comment]
cc @ggilmore @slimsag

**Comment by slimsag** [comment]
ack

**Comment by ggilmore** [comment]
I opened https://github.com/sourcegraph/deploy-sourcegraph/pull/146, but it shouldn't be merged until `3.0-preview` has actually been tagged.
