### ISSUE TITLE
Documentation: sourcegraph/doc/admin/install/docker/index.md

### ISSUE THREAD

**Issue by nathanverrilli** [sourcegraph/sourcegraph#9344]
Current Master 
Windows 10, Docker For Windows 

#### Steps to reproduce:
1. This is a configuration issue. 
2. Installing Docker for Windows on Windows 10 turns on low-level Windows configuration HyperV features, which in turn conflict with VMWare.
2a. I did this to myself previously -- enabling HyperV to see if I could move from VMWare to HyperV (quick answer: NO). It took me a day of research to figure out how to undo it.
3.  Simply uninstalling Docker for Windows does not undo this. Backing this configuration out requires a significant understanding of what and how the low-level settings for virtualization work (see 2a. above).
4. The Docker Run command fails.
4a. I don't know why. Once I realized I'd clobbered my VMWare setup, my first priority was getting VMWare back up and running correctly. Why Docker wasn't running in a configuration I didn't want on my computer in any situation was a lower priority.

5. AFTER FIXING VMARE. Attempted to run Docker container in (a virtual) Ubuntu Desktop 19.10 (Eoan Ermine). Fails instantly with a message about insufficient MLOCK capabilities and a recommendation for a higher version of the Linux kernel.
5A. Although the message is useful, it is obscured by the output of 50+ go routines, and remarkably easy to miss (yes, I missed it. Several times).
5B. Upgrading the Linux kernel in-place on Ubuntu sounded like it risked my Ubuntu configuration. Thanks but no thanks.
6.  New installation of Fedora 31 works (but see 6a)
6a. Fedora 31 requires migrating the CGROUPS hierarchy back to V1 -- Docker is incompatible with V2.
7. After downgrading cgroups and installing Docker , all works.
#### Expected behavior:
4. Docker container starts, Sourcegraph is running.

#### Actual behavior:
5. It doesn't work (the Docker container doesn't start).

#### Recommendations:
I. Tell persons running Windows and VMWare to run Sourcegraph in a VM (turn on virtualization options) running some Linux version known to work with docker (probably not Fedora 31).

**Comment by beyang** [comment]
If I'm reading the issue correctly, it seems like the source of difficulties was getting a working Docker installation on Windows 10 and then Fedora Linux. If that is the case, that's outside the scope of what our docs cover (we assume a working Docker installation as a prerequisite).
