### ISSUE TITLE
Integrate with GitHub search box

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#935]
It would be nice if there was a way to perform a Sourcegraph search from the GitHub search box, like another row `On Sourcegraph` in the dropdown:

![image](https://user-images.githubusercontent.com/1976/48306951-9bfe7600-e4f7-11e8-865a-62215d3f874b.png)

cc @felixfbecker @dadlerj

**Comment by erzhtor** [comment]
I believe this was addressed in https://github.com/sourcegraph/sourcegraph/pull/24645

![image](https://user-images.githubusercontent.com/6717049/144613382-e2c013eb-15a9-4cd7-95d1-03625776b02a.png)
