### ISSUE TITLE
Find references button doesn't show if token is hovered before provider is registered

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#9350]
Similar to https://github.com/sourcegraph/sourcegraph/issues/9349.

A "find references" button is not shown if there is a `null` definition emitted before the loader delay. If no providers are registered yet, `null` is emitted immediately, meaning the "find references" button will never show up, even after the providers were registered and emitted non-null.

https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/shared/src/hover/actions.ts#L124-134

Reported in https://github.com/sourcegraph/sourcegraph/issues/9346

**Comment by efritz** [comment]
Is the title correct?

What was the case for this condition in the first place? Assuming that the inline comments were correct at some point, what changed to make find references appropriate to show now?

**Comment by felixfbecker** [comment]
Yes, the title is correct, and I think the code comments are correct too. I'm not sure I understand your question, specifically the "what changed to make to make find references appropriate to show now" part, but I'll try my best to explain. The button is shown after a delay or after we got a non-empty definition result, whichever comes first. It is not shown when there is an empty definition result, this is so we don't show the button literally everywhere you hover (even comments). But in case the definition result takes a while to return, we show it after a delay.

**Comment by efritz** [comment]
Could we instead of on null definition we have on null definition AND null hover?

**Comment by felixfbecker** [comment]
Yes, I suppose we could do that. But in general, if a hover is there, shouldn't there be a definition too? How would it get the hover if it doesn't have the definition? I suppose that's why it was implemented this way (because of this assumption, and because this part of the code is independent of hover data/doesn't have easy access).

Note that the real problem here is that this condition is not reevaluated after providers were registered. Changing it to consider hovers wouldn't solve this problem. (Not saying considering hovers wouldn't be better, just saying this is the more severe issue)

**Comment by efritz** [comment]
Oh I see now. Then the title _does_make sense.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
