### ISSUE TITLE
saved searches should be excluded from search panels/alerts where possible

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#9358]
A saved search encountering an error can inflate the search dashboards/alerts substantially, and is far less significant than a user encountering a search error. They should be excluded from the search panels where possible (e.g. for user alerts, successful/failed search counts, etc. but not for performance since that would not be possible) and separately monitored for failures in the query-runner service.

e.g. this is likely inflating this frontend dashboard panel on sourcegraph.com:

![image](https://user-images.githubusercontent.com/3173176/77700730-0770a880-6f72-11ea-903c-5456d338a8cf.png)

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
