### ISSUE TITLE
sourcegraph.com search performance regularly poor

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#9359]
99th percentile search performance (end-to-end, from graphql request to response) is regularly exceeding 25s on sourcegraph.com over the last 14d:

![image](https://user-images.githubusercontent.com/3173176/77701004-9251a300-6f72-11ea-83c5-af4c8ef319f1.png)

90th percentile is more reasonable, of course, but still seems a bit all over the place:

![image](https://user-images.githubusercontent.com/3173176/77701143-d3e24e00-6f72-11ea-84a8-e26a3f98ea6d.png)

Both of these panels can be viewed [in the Frontend dashboard](https://sourcegraph.com/-/debug/grafana/d/frontend/frontend?orgId=1&from=now-14d&to=now).

I suspect that grabbing samples of the worst and medium offenders here could give us some good insights to improve search perf. This could be done through Jaeger.

cc @sourcegraph/core-services @sourcegraph/distribution in case anyone is interested in taking a peek

**Comment by slimsag** [comment]
Important note: these charts show the performance of successful queries only. i.e. `src_graphql_field_seconds_bucket{type="Search",field="results",error="false"}`

**Comment by slimsag** [comment]
Update: As of the last 7d the following is true:

5m P99 search latency still shows regular spikes up to 30s:

![image](https://user-images.githubusercontent.com/3173176/86871053-5f00d300-c08e-11ea-8663-21c58ecb78c4.png)

5m P90 is quite a bit more bad:

![image](https://user-images.githubusercontent.com/3173176/86871120-83f54600-c08e-11ea-9dfa-83214656e1c8.png)

You can view all of this here: https://sourcegraph.com/-/debug/grafana/d/frontend/frontend?orgId=1&from=now-7d&to=now

**Comment by tsenart** [comment]
@keegancsmith: Troubleshooting this with Honeycomb would be a breeze. Do you think it's too hard to instrument the whole search path with it?

**Comment by keegancsmith** [comment]
In the early days we had it on honeycomb and it was indeed very very useful. However, in this case it is pretty clear that the model we use just hasn't scaled and has been left alone for too long. The work I am doing on streaming will likely help these alerts a lot. I assume streaming for just in time search (The cause of this) is what is most useful from a product perspective, so will target that before I target zoekt. So watch this space :)

**Comment by bobheadxi** [comment]
Some notes from today, noticed today in a lot of types of queries, there's some low-hanging-fruit-slowness:

* a lot of git commands
* a lot of sql queries

Seems very case-by-case though

**Comment by slimsag** [comment]
I have silenced the following alerts in response to this:

"warning_frontend_99th_percentile_search_request_duration"
"warning_frontend_hard_error_search_responses"
"warning_frontend_internal_indexed_search_error_responses"
"warning_frontend_internal_unindexed_search_error_responses"
"warning_frontend_search_api_alert_user_suggestions"

Please fix, confirm the alert is not firing anymore, and then unsilence it in: https://github.com/sourcegraph/deploy-sourcegraph-dot-com/blob/e33d7cd48e9407aac88124eec89644dd4d51699c/base/frontend/sourcegraph-frontend.ConfigMap.yaml#L5271-L5275
