### ISSUE TITLE
Interactive search doesn't play well with suggestions

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#9378]
If I click a suggestion, the previous query values are preserved, not replaced:

![suggestions](https://user-images.githubusercontent.com/888624/77792971-88897780-7026-11ea-8060-43730dabdf87.gif)

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
