### ISSUE TITLE
dev/update-phabricator-extension.sh was broken during repo migration

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#938]
This file was not migrated after the move from the separate browser-extensions repo to the single repo.

I am going to delete it to avoid confusing anyone. You can revive it from git history. (I do not need it and am not blocked on it. Just filing this for you.)

**Comment by chrismwendt** [comment]
The Phabricator files are copied from `packages/browser-extensions` in [`gulpfile.ts`](https://sourcegraph.sgdev.org/github.com/sourcegraph/sourcegraph@master/-/blob/gulpfile.ts?diff=9cd5e49cc4fe3a6efa3a8058475e86763f710b86#L230). `dev/update-phabricator-extension.sh` might be superfluous now.

**Comment by ijsnow** [comment]
This is a gulp task now.
