### ISSUE TITLE
"Close" and "Delete" popups show "open changesets" even though they are merged

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#9393]
Extracted from https://gist.github.com/unknwon/b7c80d23e6b2a624e50e4073454959e0

> While running another campaign, I notice the "close" panel doesn't get updated without a page refresh:

![](https://user-images.githubusercontent.com/2946214/77843845-916b7c00-71d3-11ea-80a1-cb09a012c841.png)

All PRs are merged but it says "open"

**Comment by eseliger** [comment]
I cannot reproduce this issue anymore, we are using the `openChangesets.totalCount` field here. It was introduced after that was initally reported, on Apr 30 here c910cff0e49964fc8042080194fe51b7d9366706.
