### ISSUE TITLE
Diffs for files without newline at EOF are missing the last line

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#9397]
Extracted from https://gist.github.com/unknwon/b7c80d23e6b2a624e50e4073454959e0

> Diff with no EOF missing the last line
> Notice on the right, +2, it's most likely a bug in parsing diff (I've encounted it once in one of my projects). The diff will have a \ No newline at end of file if the file does not end with a new line.

![](https://user-images.githubusercontent.com/2946214/77819157-9a951400-7113-11ea-8c43-8523913b5377.png)

This seems to happen for non-Campaigns diff too. When the diff has no newline at EOF we don't display the last line:

https://k8s.sgdev.org/github.com/sourcegraph/automation-testing/-/commit/3a0d12026c1349c4aefb712145433cc26c330a06

**Comment by eseliger** [comment]
@mrnugget I think I fixed it in the syntax highlighting PR, can you reconfirm?

**Comment by mrnugget** [comment]
Confirmed that it's working now. [Example commit](https://k8s.sgdev.org/github.com/sourcegraph/automation-testing/-/commit/3a0d12026c1349c4aefb712145433cc26c330a06) with an addition to a file without a new line now looks like this:

<img width="521" alt="image" src="https://user-images.githubusercontent.com/1185253/83117485-69ae6c80-a0cd-11ea-8318-917bc4216d85.png">
