### ISSUE TITLE
Open changesets of a closed campaign are still being synced

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#9402]
It seems to me that we are still pulling events for open PR/changesets that belong to a closed campaign:
![image](https://user-images.githubusercontent.com/2946214/77944452-97f01580-72f1-11ea-901f-f97b8f69ba16.png)

I'm confident that I didn't do anything on UI for the last 3 hours.

Context: These changesets were created by changing the description of a closed campaign which reported in #9395.

**Comment by mrnugget** [comment]
cc @ryanslade This could be a low-hanging fruit to save requests to code hosts.
