### ISSUE TITLE
sourcegraph-frontend disk cache at 160GB

### ISSUE THREAD

**Issue by uwedeportivo** [sourcegraph/sourcegraph#9403]
on dot-com we ended up with two frontend pods on the same node and both had /mtn/cache sizes of 160GB which consumed all the available disk space.

i see in code that we have cache size limits for searcher, replacer and symbols but i couldn't find for frontend. do we limit cache size in the frontend ?

feel free to close if this is expected behavior. we should check if we should increase disk sizes then though.

**Comment by uwedeportivo** [comment]
related to this incident: https://github.com/sourcegraph/about/pull/716

**Comment by keegancsmith** [comment]
Not limiting in frontend may be an oversight. I will investigate. Note: I hope to remove most of our use of the cache in https://github.com/sourcegraph/sourcegraph/issues/9372

**Comment by keegancsmith** [comment]
Yeah we don't limit. Will track in an older issue.

Duplicate of https://github.com/sourcegraph/sourcegraph/issues/8308
