### ISSUE TITLE
"Clone in progress" errors are not properly handled

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#9411]
The function `retryWhenCloneInProgressError()`, for example used by the "open on Sourcegraph" button, does not properly detect the error if it comes from the background page (which is always the case in the browser extension).

This surfaced because I recently changed the button to show errors instead of swallowing them:

<img width="505" alt="Screen Shot 2020-03-28 at 17 37 00" src="https://user-images.githubusercontent.com/10532611/78028814-e50ad080-735f-11ea-853a-31ba2be2c6ed.png">

It happens because it checks for the error's `code`, but that is not cloned through the page boundary, see https://github.com/mozilla/webextension-polyfill/issues/210.
For a workaround, we can check the error message like we do for `HTTPStatusError`. This bug applies to _all_ errors.

**Comment by felixfbecker** [comment]
@lguychard this has caused bugs enough that I think it is warranted to prioritize a PR to `webextension-polyfill`. Do you still have this on your list? https://github.com/mozilla/webextension-polyfill/issues/210#issuecomment-551190245

**Comment by lguychard** [comment]
@felixfbecker yeah, I have a local branch but haven't had time to wrap it up. Will do this week.

**Comment by felixfbecker** [comment]
Awesome!

**Comment by felixfbecker** [comment]
@lguychard I split this off into a separate issue: #9693
