### ISSUE TITLE
docs: Automatically and periodically sync changes to docs resources (templates, CSS, JS) from master

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#9427]
To fix https://github.com/sourcegraph/sourcegraph/issues/7336, the latest versions of docs resources such as templates, CSS, and, JS should be reflected in docs.sourcegraph.com no longer less than 5 minutes from the time changes are merged into master.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
