### ISSUE TITLE
Can't get Go code intelligence working.

### ISSUE THREAD

**Issue by vincentwoo** [sourcegraph/sourcegraph#945]
- **Sourcegraph version:** 2.13.2
- **Platform information:** Google container optimized OS 70 (Docker 18.06)

Hi all,

Vincent from CoderPad here, after following @sqs and co for some time, I decided to give sourcegraph a whirl on our Go repo. I provisioned a google container optimized instance and managed to get it working up to the point where I'm in the site admin. I'm using the latest published docker image of sourcegraph. I've turned on Go code intelligence and see the container running. I've also installed and connected my Chrome extension. However, when I hover over symbols in the sourcegraph repo view, I don't see anything. Looking at the network tab shows:

> blob:https://sourcegraph.coderpad.io/8258aafa-e640-49a9-9a51-8a9b8b220894:303 An error occurred when sending LSP requests to the language server, disabling this instance of the language extension (reload the page to clear this state).  Error: other goroutine failed to connect and initialize LSP server: dial tcp: lookup go on 169.254.169.254:53: no such host
    at sourcegraph.commands.executeCommand.then.responses (blob:https://sourcegraph.coderpad.io/8258aafa-e640-49a9-9a51-8a9b8b220894:240)

The config added by default when enabling intelligence shows:

```
  "langservers": [
    {
      "address": "tcp://go:4389",
      "language": "go"
    }
  ]
```

`docker logs` on the `sourcegraph/codeintel-go` shows:

```
$ docker logs 225b56ac29e1        
xlang-go: listening on :4389
```

I'm not sure what to do next, any help?

**Comment by vincentwoo** [comment]
I believe this may be related to Google's policy of running containers with `--net host` by default, btw.

**Comment by sqs** [comment]
Sorry it didn't work for you! Our [Google Cloud install instructions](https://docs.sourcegraph.com/admin/install/docker/google_cloud#deploy-to-google-cloud-vm) do not specify a `--network`, which means that `--network bridge` will be used by default (per https://docs.docker.com/engine/reference/run/#network-settings). Can you try using that instead? Or using Ubuntu as described in the instructions.

**Comment by vincentwoo** [comment]
I can take another crack at running it with the normal Ubuntu setup, but I think it would be really cool if sourcegraph was one-click deployable on COS. It seems *almost* doable - I think the networking thing is the last bit.

**Comment by sqs** [comment]
Assigning to @chrismwendt to follow up as part of Sourcegraph 3.0 testing to ensure that the Go extension works for @vincentwoo.

**Comment by vincentwoo** [comment]
Ah, is the preview out? Is it a tag on dockerhub?

**Comment by sqs** [comment]
The release candidate is not out yet. It will use the new Go extension at https://github.com/sourcegraph/lang-go/blob/master/README.md, which you could try with your current version. The installation is more manual for now (not automatic as in 2.x), but this makes it less magic.

I recommend you wait for us to get the 3.0 release candidate out before trying the new Go extension, but if you want to try it sooner, go ahead. :)

**Comment by vincentwoo** [comment]
I'll wait a bit, thanks for the info.

**Comment by chrismwendt** [comment]
[3.0-beta](https://about.sourcegraph.com/blog/sourcegraph-3.0-beta-is-now-available) is now available! Let us know if you run into any problems. We're keen on improving any rough spots in the UX for first-time users.
