### ISSUE TITLE
"View on Sourcegraph" opens options page

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#946]
Wth?

![2018-11-12 14 08 54](https://user-images.githubusercontent.com/10532611/48349431-92564900-e684-11e8-912d-3f0829431685.gif)

https://github.com/Xanewok/rls

**Comment by ijsnow** [comment]
Can't repro with the provided link, but have seen this before. It has to do with a repo not being on the instance that the browser extension is pointing at.

**Comment by felixfbecker** [comment]
It just happened to me again with https://github.com/Microsoft/lsif-typescript

**Comment by felixfbecker** [comment]
I'm closing this, we can reopen if we see it again. I recently edited the component and don't know how this would happen.
