### ISSUE TITLE
Improving extensions toolbar on code hosts and Sourcegraph

### ISSUE THREAD

**Issue by imtommyroberts** [sourcegraph/sourcegraph#9462]
The extensions toolbar feels overcrowded on Sourcegraph, and too many extensions are breaking the toolbar in GitHub. #4480 

Myself and Felix had a call to discuss some of these issues, and figure out small improvements we can make in 3.15. [Corresponding document](https://docs.google.com/document/d/1X3RLBeRhz-HccKLI7D9nVHRN4bzNAzEqfGPKYfHnEXY/edit)

Improvements to Sourcegraph extension toolbar: 

- Extension buttons are overcrowded and it's not immediately clear what is a button and what isn't, to fix this we decided it would be best to slightly increase the padding (myself and Felix will decide on a `rem` amount and share here, this goes for other situation where we will be changing padding too)
- To further increase clarity, I would like to add icons to extensions we have control over (Discussions)
- Fix inconsistent 'colours' (make all buttons (icons + text) white, and blue on hover)
- Potentially: Add a background on hover
- Change cursor pointer to be consistent

Improvements to code hosts extensions toolbar:

- Native button groups (Raw/Blame/History + icons on the right side, but not the text on the left side) should never wrap/break 
- As a result of the previous change, we can decrease padding on either side of extensions to allow for more extensions to be visible before a second line is needed
- Increase vertical padding between buttons when they stack
- Keep vertical stack effect when 'too many' extensions are added, with these changes it shouldn't 'break' the current extensions toolbar

cc: @lguychard @christinaforney

**Comment by felixfbecker** [comment]
Icon additions:
- https://github.com/codecov/sourcegraph-codecov/pull/48
- https://github.com/sourcegraph/sourcegraph-git-extras/pull/109

**Comment by felixfbecker** [comment]
All improvements discussed in this issue are merged ✨
