### ISSUE TITLE
Intermediate plain text search bar should use same font as Monaco editor

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#9499]
We use progressive enhancement for the search bar. Currently the intermediate search bar uses a non-monospace font, which causes an unstable UI because text moves around as soon as the editor is loaded. If we apply the same font, we can make it so only the syntax highlighting visually changes.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
