### ISSUE TITLE
authentication failure text gives no next steps

### ISSUE THREAD

**Issue by terinjokes** [sourcegraph/sourcegraph#95]
- **Sourcegraph version:** 2.8.9 (server)
- **Platform:** n/a

#### Steps to reproduce:

1. Connect to the authentication callback with an unexpected value

#### Expected: 

Error message would explain the failure (invalid state), attempt to fix the situation (unset cookies), and give next steps ("try logging in again" or "delete your cookies for $APP_HOST")

#### Actual:

```
Authentication failed. OpenID Connect state paramater did not match the expected value (possible request forgery).
```

**Comment by sqs** [comment]
Fix in review
