### ISSUE TITLE
Campaign screenshot tests flaky since burndown default change because they now depend on current date

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#9506]
Changing the default for the burndown chart to be shown has an unwanted consequence: the burndown chart is dependent on the current date, which comes from the backend. This means our e2e screenshot tests will now fail every 24h...
I think the solution would be to pass the start/end date explicitely from the webapp through GraphQL, where we can mock the date in tests

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by mrnugget** [comment]
Closing this because I'm 99% sure that the test setup has changed and this is invalid. Feel free to reopen if I was wrong here.
