### ISSUE TITLE
Clicking on some search results takes users to Sourcegraph homepage

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#9511]
Reported by https://app.hubspot.com/contacts/2762526/company/1686989427

- **Sourcegraph version:** 3.13.2

#### Steps to reproduce:

I cannot reproduce this on dotcom or k8s.sgdev, so I'm requesting more information. That said, @christinaforney and I watched this happen live, so I can confirm that the issue is happening as described.

1. Run a search (this occurs on both the text and repo tabs, not sure about others)
2. Click on a result
3. Instantly land at the root URL on the Sourcegraph instance (e.g., on dotcom, at https://sourcegraph.com)

Note that MOST search results work, this only occurs with some.

When the user hovered over the repo link, I could confirm that Chrome was showing the correct URL in the status bar at the bottom. However, when they actually clicked, they landed at the Sourcegraph URL, but without the <host>/<org>/<repo> on it.

I have asked the contact to try URL-hacking to arrive at the repo directly, to see if the error is coming from the search results page or the repo page.

**Comment by dadlerj** [comment]
Confirmed that URL-hacking to arrive at the repo also redirects to root.

**Comment by keegancsmith** [comment]
Some discussion from slack:

> stephen 16 hours ago
> The most likely causes of this would be:
> 
> 1. They are running something in front of Sourcegraph which is custom (Apache or nginx, some auth proxy, etc) which is having this behavior.
> 1. They are using one of our SSO providers and it is misconfigured in some way that causes this.
> 
> Can you ask or details on what they have setup or 1 & 2 above? Also it would be good to know if this only happens on repository pages or if other pages are accessible fine? e.g. can the homepage be accessed fine, what about the site admin page or user pages?
> 
> dan  16 hours ago
> Yeah, to be clear, most pages work fine, and most search results work fine as well. Only some repo/file pages cause this.
> 
> dan  16 hours ago
> And they’ve added all their repos and configured it, so site-admin definitely works
> 
> stephen  16 hours ago
> Have they ever been able to access repo pages before?
> 
> dan  16 hours ago
> Yeah, for most repos and files they’re able to view them just fine. But this occurs on some repos/files.
> 
> dan  16 hours ago
> So I assumed it could be due to some weird state that some repos get in? Or perhaps they enabled permissions and that’s causing issues?
> 
> stephen  16 hours ago
> Ahhh, ok, then in that case I take back everything I said above and would suspect that maybe this is a bug in some extension that they have enabled.
> 
> stephen  16 hours ago
> If this was with something in front o Sourcegraph, or permissions/SSO, I would expect it to affect all repositories equally.

**Comment by keegancsmith** [comment]
@tsenart @unknwon given this only happens for some repositories it points at this maybe being permissions related. Do you have any ideas about if this sort of behaviour is possible?

@dadlerj Does this also happen to site admins? Site admins generally skip permissions code so that would help rule that out. Another possibility is redirects failing.

To help debug this can I request a bit more information:
- The hacked URL for a repo.
- A screenshot of the "settings" page for it.
- A capture of the network request and response when visiting the repo. IE open chrome explorer, network tab, enable "preserve log", visit direct repo URL.
- Bonus: any frontend logs around the time of the request.

**Comment by unknwon** [comment]
> @tsenart @unknwon given this only happens for some repositories it points at this maybe being permissions related. Do you have any ideas about if this sort of behaviour is possible?

I think it's not possible to make this happen with repo permissions alone, i.e. the user won't even see the search results if no permissions.

---

@dadlerj When you say "some repo/files", are they in fact just "some repos"? We have a thing call `repostiroyRedirect` which redirects the user to a guessed URL (`https://sourcegraph.com/{URI}`) when for any reason not found in the DB. (enabled via site config `disablePublicRepoRedirects: false`). It's unlikely but worth double checking and rule it out.

**Comment by dadlerj** [comment]
Great, thank you all for guidance!

**Comment by keegancsmith** [comment]
@dadlerj any updates here?

**Comment by dadlerj** [comment]
Actually, yes, I just got some information back this morning... I had sent over a series of questions based on the discussion above, and the response was:

>The third point is interesting because raises the idea to check if additional paths need to be whitelisted (either ending with / - as you suggested, or in another way)
> ... And $person found indeed that paths like "/<source_tree_site>" were not whitelisted.
> Apparently, the whitelisting solves the issue.
> However, remains the question why when those paths were not whitelisted, some of those links were still workable.

When I asked for clarification ("Was some sort of network access restriction on your side causing the problem?"), he answered:

>Confirmed. SourceGraph's paths are controlled via nginx and oauth proxy. The paths corresponding in SourceGraph to $codehosts were not whitelisted in oauth proxy.

When I asked _why_ they would require such whitelists instead of just whitelisting everything under the Sourcegraph path, he replied:

>Re - reasons that to not whitelist all Sourcegraph sub-paths... The / need to be under control of oauth proxy. Since SourceGraph cannot be installed under a sub-path (like /sourcegraph for instance), we need to use the available regexp-s and explicit paths for whitelisting. Of course, we’ll review the solution, but that’s current status

Sounds like they have multiple apps running on the same domain with different access requirements, I suppose? So ultimately, the underlying root cause of the setup they used ended up being https://github.com/sourcegraph/sourcegraph/issues/103 (that's an old issue number!). 

Thank you @keegancsmith @unknwon and @slimsag for the help resolving this!
