### ISSUE TITLE
`src-expose dir` (where dir is a git repo) serves a repo named "."

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#9530]
Reported by https://app.hubspot.com/contacts/2762526/company/693777200, confirmed by me.

Repro:

* install `src-expose`
* `git clone https://github.com/<org>/<any git repo>`
* `src-expose serve /path/to/<any git repo>/`
* visit http://[::]:3434, click on `list-repos`, and note that the repo is being served as "."

![image](https://user-images.githubusercontent.com/5589410/78307838-b9bce880-74fb-11ea-9147-15c20c124afc.png)

(Note that the same behavior is exhibited when using `src-expose` without the `serve` arg)

The only way to make this work as expected is to instead run `src-expose /path/to/`, and then the git repos that are children of that path are all served up with the correct names. This is, however, less ideal as you can't explicitly enumerate which repos you want to include — you always have to create a parent dir that only contains the ones you want.

**Comment by keegancsmith** [comment]
ok so the solution I'll use here is if the `/path/to` is a git repo we root all repo names at the basename of the path. That should give the behaviour we want without making things more complicated.

**Comment by dadlerj** [comment]
SGTM. Also, if I'm mistaking how this is supposed to work, please just let me know! I don't mean to add extra confusion to the CLI, this just threw me off during testing.

**Comment by keegancsmith** [comment]
@dadlerj latest version of src-expose will have better behaviour for this case. You can fetch the latest linux binary from
https://storage.googleapis.com/sourcegraph-artifacts/src-expose/latest/linux-amd64/src-expose
or use the specific version we just pushed at
https://storage.googleapis.com/sourcegraph-artifacts/src-expose/bbe8f46ca2f1749880cf71afbc29842906585ede/linux-amd64/src-expose
