### ISSUE TITLE
Repositories are always recloned on every page visit

### ISSUE THREAD

**Issue by yunchih** [sourcegraph/sourcegraph#9546]
- **Sourcegraph version:** 3.14.1
- **Platform information:** Docker sourcegraph/server:3.14.1

Repositories are always recloned on every page visit.
`docker logs` output: http://ix.io/2gsK
It seems that sourcegraph tries to reclaim space, but the `/var` file-system configured for Docker still has ample space.

#### Steps to reproduce:

1. Run with Docker:
```
docker run -d --tmpfs /tmp:rw,nodev,noexec,nosuid,size=65536k --publish 7080:7080 --publish 127.0.0.1:3370:3370 --volume ~/.sourcegraph/config:/etc/so
urcegraph --name sourcegraph-3.14 --volume ~/.sourcegraph/data:/var/opt/sourcegraph sourcegraph/server:3.14.1
```
2. Add some single Github repos:

```
{
  "url": "https://github.com",
  "token": "<token>",
  "orgs": [],
  "repos": [
    "facebook/rocksdb", "google/leveldb", "torvalds/linux"
  ]
}
```
3. Go to the "facebook/rocksdb" sourcegraph page, it is recloned every time the page is accessed.
4. When opening some files, error messages are shown:  "Repository does not exist (clone in progress): github.com/facebook/rocksdb"

#### Expected behavior:
Once it is cloned the first time, it never has to be cloned again.

#### Actual behavior:
Repositories are always recloned on every page visit.

**Comment by unknwon** [comment]
This issue sounds similar to https://github.com/sourcegraph/sourcegraph/issues/8878#issuecomment-596105611, which happens to be a Docker installation problem.

**Comment by yunchih** [comment]
The environment variable  `SRC_REPOS_DESIRED_PERCENT_FREE=0` seems to fix it.  Thanks @unknwon
