### ISSUE TITLE
No codeintel in browser extension, Uncaught Error: File actions not found. Make sure you aren't trying to create a toolbar mount for a code snippet that shouldn't have one

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#955]
I don't get any codeintel when reviewing https://github.com/sourcegraph/sourcegraph/pull/919/files

Version 2.0.6, Chrome, "use extensions" OFF

Error in console:
```
Uncaught Error: File actions not found. Make sure you aren't trying to create a toolbar mount for a code snippet that shouldn't have one
```

**Comment by ijsnow** [comment]
I can't reproduce this. Is refined github or another extension you are using changing class names?

**Comment by ijsnow** [comment]
Curious because you're the only one reporting this and I still can't repro (literally just closed the same issue https://github.com/sourcegraph/sourcegraph/issues/756).

**Comment by felixfbecker** [comment]
I get code intelligence now, no matter if Refined GitHub is on or off. But this bug definitely exists because it keeps happening to me since the original issue I filed. Could this be a race condition? Is the element it is looking for not rendered yet?

**Comment by nicksnyder** [comment]
This just happened to me and has happened to me multiple times in the past week. Hard refreshing the page always fixes it. I have yet to deduce what series of actions causes this to happen.

I don't have refined GitHub installed.

```
Uncaught Error: File actions not found. Make sure you aren't trying to create a toolbar mount for a code snippet that shouldn't have one
    at o (inject.bundle.js:1)
    at t.Ao.o.add.Object.pipe.subscribe [as _next] (inject.bundle.js:63)
    at t.__tryOrUnsub (inject.bundle.js:1)
    at t.next (inject.bundle.js:1)
    at t._next (inject.bundle.js:1)
    at t.next (inject.bundle.js:1)
    at e.observe (inject.bundle.js:1)
    at t.dispatch (inject.bundle.js:1)
    at t._execute (inject.bundle.js:1)
    at t.execute (inject.bundle.js:1)
```

**Comment by ijsnow** [comment]
This will be addressed by changing the internal architecture of the `code_intelligence` directory and how we handle interactions with the DOM.

**Comment by felixfbecker** [comment]
Cannot repro anymore with #2909
