### ISSUE TITLE
Remove feature flag for campaigns in navbar

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#9555]
Only show the splash page, campaigns is still going to be _Beta_. On dotcom, we are showing different content, but also _some_ content.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
