### ISSUE TITLE
verify "syntax highlighting sometimes doesn't work" is fixed on customer instance

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#9557]
A customer at https://app.hubspot.com/contacts/2762526/company/407948923 reports that syntax highlighting on some e.g. Python files is not working. When the page is refreshed, it does sometimes work.

This is due to HSS worker restarts due to another type of file taking down the underlying worker process, causing highlighting to fallback to plaintext rendering. I will investigate and fix this soon.

**Comment by slimsag** [comment]
Deferring this to 3.16, apologies.

**Comment by slimsag** [comment]
This should be fixed in Sourcegraph 3.16 (slated for release May 20th, 2020). I will leave this issue open to get confirmation on a customer instance that this is indeed fixed.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by pecigonzalo** [comment]
@slimsag Did we hear back from the customer? If there are no updates, I would close this for now and re-open if reported again.
