### ISSUE TITLE
Expose logical content match counts in GQL API

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#9564]
Match counts can differ from line count matches, if a logical match corresponds to multiple lines. This comes up for structural search and regexp multiline searches. We don't currently expose the accurate match count number, which means the webapp doesn't always display the logical number of matches on the right hand side of result expansion windows ("Show XX more results").

This issue tracks exposing match count in the API, and updating the webapp accordingly.

See https://github.com/sourcegraph/sourcegraph/pull/9541 for context.

**Comment by rvantonder** [comment]
Related to getting counts for submatches by https://app.hubspot.com/contacts/2762526/company/557693052

**Comment by camdencheek** [comment]
Closing as done since we now use chunk matches, which may contain multiline ranges
