### ISSUE TITLE
Add Percy tests from storybooks

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#9565]
Percy supports screenshotting storybooks.
- This way we can expand our stoybook library and get free unit tests for free
- It adds a layer of testing we are severely undertesting, which is styling
- It makes it easier for the design team to review changes, as they can review screenshots in Percy
- One screenshot can replace dozens of assertions, and is way easier to evolve

First came up in https://sourcegraph.slack.com/archives/CMT39K56Z/p1579792526049200

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
