### ISSUE TITLE
docs: Sourcegraph with external RDS/Postgres may be broken

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#9566]
Reported by https://app.hubspot.com/contacts/2762526/company/557476528

Assigning to @slimsag for triage/assignment

The user reported seeing the following:

> FATAL: Failed to migrate the DB. Please contact support@sourcegraph.com for further assistance: Dirty database version 1528395617. Fix and force version. 

After connecting their Sourcegraph instance (on K8s) to an external RDS instance following the docs at https://docs.sourcegraph.com/admin/external_database.

He used PG v11.4, but had trouble with Postgres extension installation.

From @slimsag 
>We rely on the citext, hstore, and pg_trgm extensions. I suspect right now it's stuck on hstore -- can you add all three of those and give it another go?

And after the fact, from @slimsag 
>it is strange he had to do something special to get those installed. https://app.hubspot.com/contacts/2762526/company/407948923 did not have to (but they did initially setup their DB a while ago). This could be a regression in our "external Postgres DB (on RDS)" documentation, or this could be something specific to their usage of RDS through Terraform. I am not sure, we'll need to test it by simply setting up Sourcegraph with an RDS instance connected and updating the documentation appropriately

**Comment by daxmc99** [comment]
We currently use Cloud SQL in some deployments. External Postgres should work. We may need more docs in this area but this is not currently broken
