### ISSUE TITLE
GraphQL API Search result line numbers

### ISSUE THREAD

**Issue by aisbaa** [sourcegraph/sourcegraph#9587]
- **Sourcegraph version:** 3.12.7

#### Steps to reproduce:

1. Run this [search graphql query](https://sourcegraph.com/api/console#%7B%22query%22%3A%22%7B%5Cn%20%20currentUser%20%7B%5Cn%20%20%20%20username%5Cn%20%20%7D%5Cn%20%20search(query%3A%20%5C%22repo%3A%5Egithub.com%2Fsourcegraph%2Fsourcegraph%24%20file%3A%5EREADME.md%20LICENSE%5C%22)%20%7B%5Cn%20%20%20%20results%20%7B%5Cn%20%20%20%20%20%20results%20%7B%5Cn%20%20%20%20%20%20%20%20...%20on%20FileMatch%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20lineMatches%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%5Cn%5Ct%5Ct%5Ct%5Ct%5Ct%5Ct%5Ctpreview%5Cn%5Ct%5Ct%5Ct%5Ct%5Ct%5Ct%5CtlineNumber%5Cn%5Ct%5Ct%5Ct%5Ct%5Ct%5Ct%5CtoffsetAndLengths%5Cn%5Ct%5Ct%5Ct%5Ct%5Ct%5Ct%7D%5Cn%20%20%20%20%20%20%20%20%20%20file%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20url%5Cn%20%20%20%20%20%20%20%20%20%20%20%20externalURLs%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20url%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20repository%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20name%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20resultCount%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22variables%22%3A%22%22%7D)

#### Expected behavior:

Matched result lines are off by 1, seems like API file starts from line 0.

#### Actual behavior:

Expect file to start from line 1 or mention that it starts from 0 in the docs.

https://github.com/sourcegraph/sourcegraph/blob/94e5aa4c6dc58fe46c8febc00a081b26cf65a7c1/cmd/frontend/graphqlbackend/schema.graphql#L2906

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
