### ISSUE TITLE
[Docker, self-hosted Gitlab] Private mode requires authentication

### ISSUE THREAD

**Issue by francisjeanneau** [sourcegraph/sourcegraph#9590]
- **Sourcegraph version:** sourcegraph/server:3.14.1
- **Platform information:** Docker version 19.03.6, build 369ce74a3c, Ubuntu 18.04.4 LTS

I've had a discussion with Nick Thomas from Gitlab, here is the link: https://gitlab.com/gitlab-org/gitlab/-/issues/205153#note_318341512

Summary:
> There seems to be an issue with authentication. It may be my setup, I go through a VPN. Cookies seems to be sent (see screenshot), but Sourcegraph denies the requests nonetheless. At first I thought Gitlab was the issue, but Nick made me realize that the auth works with cookies. After trying the Sourcegraph URL directly in my browser, I concluded that this is not a Gitlab issue. 

**Note**: I have third-party cookies enabled in Firefox 74.0 (64-bit) for Linux Mint
**Note2**: I have tested with a local docker container (instead of on the same server as Gitlab) but I get the same results: authentication fails.

![image](https://user-images.githubusercontent.com/14813038/78564570-a0ad8380-77ea-11ea-93cc-ff7903ee8958.png)

#### Steps to reproduce:

1. Setup a Docker Sourcegraph instance
2. Configure with a self-hosted Gitlab instance
3. Test native integration.

#### Expected behavior:
This should return whatever is needed for the Gitlab native integration to work.

#### Actual behavior:
Tells me I am not authenticated

**Comment by unknwon** [comment]
As a quick dig, I think the problem is that Sourcegraph thinks the request is not authenticated (you're not logged in): https://sourcegraph.com/github.com/sourcegraph/sourcegraph@206177ad9c4aa5bd266e73d554c82628a95eeb8a/-/blob/cmd/frontend/auth/non_public.go#L27

**Comment by unknwon** [comment]
cc @sourcegraph/web since it is from native integration.

**Comment by felixfbecker** [comment]
@francisjeanneau I see in your screenshot that there is the 🚫🔒 icon, which I think indicates the site is not using HTTPS. Browsers have recently started to block cross-origin cookies on non-HTTPS sites, so that would explain why the native integration is being rejected. Is this the case?

**Comment by francisjeanneau** [comment]
@felixfbecker Oh god, I thought about that and did not bother to setup an SSL cert. I should have tried before bothering you guys :man_facepalming: 

I find it weird that this feature relies on browser behaviour though, I thought intuitively that the communication from Sourcegraph was proxied through Gitlab. Good job nonetheless! I'll report here with the results using HTTPS. If this works, should there be a notice somewhere in the docs? Or on Gitlab side of things?

Thanks a lot for the quick reply!

**Comment by francisjeanneau** [comment]
Hello again, I finally found some time to try it again without luck. I used a self signed certificate but see the same behaviour: Private mode requires authentication.

Do you think a self signed certificate is not enough? I even added it in my local machine's trusted CA list.

**Comment by felixfbecker** [comment]
Does it show a green lock icon now in front of the URL?

**Comment by francisjeanneau** [comment]
Yes it is. 

Though it seems I found the issue: uBlock Origin was running for my Sourcegraph instance URL! It's as if having this running was preventing my Sourcegraph instance from storing a authentication cookie? So this could potentially happen with any ad blocking software.

I still have some issues: the popup sometimes stops to appear when hovering. This seems to be happening in large files:
![image](https://user-images.githubusercontent.com/14813038/96183475-ec14bd00-0f04-11eb-989f-163882c35ecb.png)
I see the requests in the Network tab, and they are successful.

Thanks a lot for the help, initial issue is solved, so feel free to close this :)

**Comment by felixfbecker** [comment]
Awesome!

Weird that uBlock Origin is causing issues for you, I have it running in Chrome on macOS and no issues. However, I know that in uBlock Origin you can subscribe to different lists and features with varying strictness, so maybe you have a stricter configuration.

> I still have some issues: the popup sometimes stops to appear when hovering. This seems to be happening in large files:

Is that screenshot not working as expected?

Anything in the console?

**Comment by francisjeanneau** [comment]
Yes the screenshot is working properly, it was simply to illustrate what "does not appear" with certain files. 

Console's last message is this:
![image](https://user-images.githubusercontent.com/14813038/96184153-0d29dd80-0f06-11eb-979e-f8f6938a82fa.png)

I think I found the issue there... Looks like Sourcegraph is not resolving submodules. JSON comes out empty in the request's response:
![image](https://user-images.githubusercontent.com/14813038/96184293-46fae400-0f06-11eb-8875-2afe270c1f11.png)

Are submodules supported at all? Should I also index them separately in Sourcegraph?

**Comment by felixfbecker** [comment]
Our code intelligence on Ruby is powered by [Basic code intelligence](https://docs.sourcegraph.com/user/code_intelligence/explanations/basic_code_intelligence), which uses code search under the hood. Functionality for cross-repository code intelligence is limited in this mode, at least when the target repositories are not on the Sourcegraph instance.
For languages that have LSIF indexers we can offer full precise code intelligence.
@sourcegraph/code-intel can answer more questions on this :)

**Comment by felixfbecker** [comment]
> Weird thing is that some symbols are resolved within Gitlab, whereas some other are redirecting right into Sourcegraph's code view. I'd really prefer staying inside Gitlab.

We generally try to stay within the code host for go to definition, if that's not working I'd appreciate if you filed an issue for that! Find references always goes to Sourcegraph since it needs the panel UI in our webapp.

**Comment by francisjeanneau** [comment]
> Our code intelligence on Ruby is powered by [Basic code intelligence](https://docs.sourcegraph.com/user/code_intelligence/explanations/basic_code_intelligence), which uses code search under the hood. Functionality for cross-repository code intelligence is limited in this mode, at least when the target repositories are not on the Sourcegraph instance.
> For languages that have LSIF indexers we can offer full precise code intelligence.
> @sourcegraph/code-intel can answer more questions on this :)

This is for C, I'll dig in the docs to find if it is supported. 

> We generally try to stay within the code host for go to definition, if that's not working I'd appreciate if you filed an issue for that! Find references always goes to Sourcegraph since it needs the panel UI in our webapp.

Excellent, will do.

Thanks again!

**Comment by mrvaghani** [comment]
Has there been any updates regarding this issue? I have SSL setup but I am still seeing the same error as OP.

**Comment by francisjeanneau** [comment]
> Has there been any updates regarding this issue? I have SSL setup but I am still seeing the same error as OP.

@mrvaghani, we went into heavy infrastructure refactor and sadly dropped Sourcegraph integration for our self-hosted Gitlab instance on the way. I don't have any news regarding this and probably won't have any in the near future. Sorry about that 😢

**Comment by souldzin** [comment]
Over at GitLab, we ran into this issue when testing out the Sourcegraph/GitLab integration with a local Sourcegraph instance.

https://gitlab.com/gitlab-org/gitlab/-/issues/361820

It looks like a main contributor to this is that the Sourcegraph in "private mode" **does not** set `SameSite: None` for it's main cookie. It looks like browsers have [somewhat recently started defaulting to `Lax`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite#browser_compatibility) which means that the cookie will not be shared across site.

You can temporarily work around this by manually setting the cookie to `SameSite: None` ([see relevant video](https://www.youtube.com/watch?v=5KSfcP7kL74)), but this workaround doesn't last long.

**Comment by cambierr** [comment]
So ... no way to get this working at the time without messing with the browser developer tools ?

**Comment by lrhacker** [comment]
After some internal discussion, it sounds like this issue was addressed recently in [another thread on GitLab](https://gitlab.com/gitlab-org/gitlab/-/issues/361820#note_946525406) by @abeatrix.

For simplicity, here's the same information to track in this thread:

> I believe this is expected when running the open source version of Sourcegraph because extensions only work with the Enterprise version supposedly.
>
> If you want to test the GitLab integration locally, you can start a free Sourcegraph Enterprise instance locally following [this guide](https://docs.sourcegraph.com/#try-sourcegraph-locally), make sure that it is running behind HTTPS (All Cookies are set as “Lax” when running behind HTTP, [link to docs](https://github.com/sourcegraph/sourcegraph/blob/33eaf86a334ded4eeef6289304f90f3276aa6748/CHANGELOG.md#changed-32)), and the Cookies will be set up correctly.
>
> You will also need to add your private Gitlab instance using the [corsOrigin setting](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/schema/site.schema.json?L583-589) to your site configuration to avoid cors issueI believe this is expected when running the open source version of Sourcegraph because extensions only work with the Enterprise version supposedly.
>
> If you want to test the GitLab integration locally, you can start a free Sourcegraph Enterprise instance locally following [this guide](https://docs.sourcegraph.com/#try-sourcegraph-locally), make sure that it is running behind HTTPS (All Cookies are set as “Lax” when running behind HTTP, [link to docs](https://github.com/sourcegraph/sourcegraph/blob/33eaf86a334ded4eeef6289304f90f3276aa6748/CHANGELOG.md#changed-32)), and the Cookies will be set up correctly.
>
> You will also need to add your private Gitlab instance using the [corsOrigin setting](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/schema/site.schema.json?L583-589) to your site configuration to avoid cors issue

Also, here's a relevant update from our [changelog](https://github.com/sourcegraph/sourcegraph/blob/33eaf86a334ded4eeef6289304f90f3276aa6748/CHANGELOG.md#changed-32):

> CSRF and session cookies now set SameSite=None when Sourcegraph is running behind HTTPS and SameSite=Lax when Sourcegraph is running behind HTTP in order to comply with a [recent IETF proposal](https://web.dev/samesite-cookies-explained/#samesitenone-must-be-secure). As a side effect, the Sourcegraph browser extension and GitLab/Bitbucket native integrations can only connect to private instances that have HTTPS configured. If your private instance is only running behind HTTP, please configure your instance to use HTTPS in order to continue using these.

If there are more questions or concerns, please feel free to comment again in this issue or reach out on our [Developer experience discussion board](https://github.com/sourcegraph/sourcegraph/discussions/categories/developer-experience)in our [Developer experience discussion board](https://github.com/sourcegraph/sourcegraph/discussions/categories/developer-experience)!
