### ISSUE TITLE
Improve performance of LSIF upload processing

### ISSUE THREAD

**Issue by creachadair** [sourcegraph/sourcegraph#9593]
Converting LSIF uploads into SQLite databases can be a bottleneck for indexing large repositories. Processing a large upload can cause worker processes to exceed their RAM budget and terminate, and throttle or starve the processing queue.  

Upload conversion currently runs on Node, mainly for historical reasons. As a step toward understanding and improving the performance of the conversion, we are going to start by re-implementing the [`convertLsif` function](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@206177ad9c4aa5bd266e73d554c82628a95eeb8a/-/blob/cmd/precise-code-intel/src/worker/conversion/importer.ts#L40:23) that handles the core conversion logic in Go. This will make it easier for us to hook up CPU and memory profiling, without disrupting the existing worker logic too much.

As a temporary step, the worker will communicate with the converter via a pipe. Later, if this is fruitful, we'll investigate replacing more of the worker and remove that dependency.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by efritz** [comment]
Technically complete after rewrite. Will address performance issues in smaller tickets as they arise.
