### ISSUE TITLE
Finished processing timestamp on LSIF upload details page is wrong

### ISSUE THREAD

**Issue by benhansenslc** [sourcegraph/sourcegraph#9596]
- **Sourcegraph version:** 3.14.1
- **Platform information:** Docker

#### Steps to reproduce:

1.  Visit the LSIF Upload details page for a particular upload.
2. Hover over the "Began processing" timestamp and the "Finished processing" timestamp and notice they are the same. I wish it was that fast but it wasn't :)

#### Expected behavior:

The Finished processing timestamp reports the actual time it finished processing.

#### Actual behavior:

It reports the same timestamp as the "Began processing"

**Comment by unknwon** [comment]
cc @sourcegraph/code-intel

**Comment by efritz** [comment]
Thanks! I actually noticed this Friday. I'll look to see how far into the stack it goes. At a glance the frontend looks fine.

It may be an error with postgres' `now()` function inside of the processing transaction.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
