### ISSUE TITLE
Update docs for how to upgrade sourcegraph.com

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#9607]
Changes merged to master in deploy-sourcegraph should land in deploy-sourcegraph-dot-com very quickly. This is in response to the alerts caused by Uwe’s change not getting deployed to sourcegraph.com for 1 month (and then we discovered issues).

Additional feedback from Thorsten, Eric, Stephen: https://sourcegraph.slack.com/archives/CMBA8F926/p1585908278034100

**Comment by uwedeportivo** [comment]
i'll also update a doc about capturing common diffs into kustomization.yaml

**Comment by uwedeportivo** [comment]
https://sourcegraph.slack.com/archives/CJX299FGE/p1586304249244400

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
also updates to k8s dogfood

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
https://github.com/sourcegraph/about/pull/934

https://about.sourcegraph.com/handbook/engineering/deployments#merging-changes-from-deploy-sourcegraph
