### ISSUE TITLE
Create docs page for codeintel showcase repos

### ISSUE THREAD

**Issue by efritz** [sourcegraph/sourcegraph#9609]
Update LSIF docs with links to codeintel showcase repos.

**Comment by efritz** [comment]
- [ ] prometheus
- [ ] TypeScript
- [ ] aws-sdk-go
- [ ] hugo
- [ ] express
- [ ] react
- [ ] grafana
- [ ] helm
- [ ] jest
- [ ] moby
- [ ] kibana
- [ ] IxJS
- [ ] kubernetes
- [ ] etcd
- [ ] go
- [ ] lodash
- [ ] moment
- [ ] got
- [ ] angular
- [ ] rxjs

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
