### ISSUE TITLE
Use query parser to get search filter counts in queryTelemetry

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#9623]
See https://github.com/sourcegraph/sourcegraph/pull/9622#discussion_r404575905 for context.

We should use the query parser rather than regexes.

**Comment by benvenker** [comment]
@lguychard or @limitedmage is this something we want to keep? Looks like it was opened in April 2020...

**Comment by lguychard** [comment]
Let's close -- search query metrics have changed quite a bit since then.
