### ISSUE TITLE
Search in same repo fork in basic code intel

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#9634]
If you are viewing a file in a forked repo (and using basic code intel), you should be able to see hovers/definitions/references in that repo. The current intended behavior is for this to not work; see https://github.com/sourcegraph/sourcegraph/issues/9583#issuecomment-609551599:

> Search has disabled forked repo results by default.

The current behavior makes sense when you're viewing a file in a non-fork repo, because you don't want the results to be littered with duplicate results from forks.

However, when you're viewing a file **in a forked repo**, the behavior doesn't make sense. When the current repo is a fork, it would be better for basic code intel to search only in the current repo. This would allow same-repo code navigation to work, and it would not introduce the problem of showing duplicate results from other forks. As a user I would not expect to see cross-repo references in this case (because I'm viewing a fork, which is likely not the actual repo that the other things are referencing).

**Comment by efritz** [comment]
This is sensible behavior. I'll try to prioritize this improvement for this week - it shouldn't be too difficult.

**Comment by efritz** [comment]
Fixed.
