### ISSUE TITLE
Complete search alert improvements and refactoring

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#9640]
#8874 refactored most of the search alert functions in `search_alert.go`, but there's still [the `alertForOverRepoLimit` left to refactor](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@master/-/blob/cmd/frontend/graphqlbackend/search_alert.go#L344-451). 

See #8874 and individual commits for guidance. The general idea is that all search alert functions should:

- return only an `*searchAlert`, not an error as well. It should not be possible for a search alert function to fail with any `err`. If an alert depends on a process that can fail with an `err` (like resolving repos), it should be suppressed and the alert message should reflect an appropriate message, or omit the extra repo information.
- Alert construction should be concentrated, and created closer to where the alert is returned. What that means is that instead of doing `alert.<field> = value` in various control flow/if conditions, we should build up the intermediate values and then only create an alert constructor close to the return location. See, for example, https://github.com/sourcegraph/sourcegraph/pull/8874/commits/dfedce367b5956a52d91e47a949fa4238a8ced97 and https://github.com/sourcegraph/sourcegraph/pull/8874/commits/be1cea7b6be3701c98533dc185ba74fc3da78e58, and other commits in #8874. 
- Various restructuring to reduce the number of if-conditionals/control flow complexity (which is what the above two things help achieve). 

The above should be mostly semantics-preserving changes, except where we might want to tweak the alert message or behavior. We ought to have tests that covers the refactor, but I don't think we cover this function, so this is a good time to add tests for it.

**Comment by rvantonder** [comment]
CC @fedealconada: this is a good task to familiarize with some of the search alert code, improve the Go code, and write some tests :-) I've put in a lengthier issue description so that it should be easy to get started. You'll want to set up [local dev](https://docs.sourcegraph.com/dev/local_development). Please assign this to yourself if it looks good to you.

**Comment by fedealconada** [comment]
Great! Thanks a ton @rvantonder! I'll be working on it. I can't assign it to myself (I guess I don't have permissions to do that) so you should do that for me :)

**Comment by rvantonder** [comment]
Also, feel free to put up a draft PR with comments if you have questions.
