### ISSUE TITLE
Add ability for src-expose to periodically run a command (without then running git commit)

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#9643]
Requested by https://app.hubspot.com/contacts/2762526/company/768958891

Context: https://github.com/sourcegraph/sourcegraph/pull/9246#issuecomment-603288802

More context from a discussion when a user learned about src-expose for the first time:

Me:

>Your understanding of what has to happen (pull down a tree, run git pull periodically) is mostly correct, but the final step is to serve the directories up over HTTP so that Sourcegraph can access them. This is the part that src-expose takes care of for you. 

Them:

>Sure. I understand that, I guess what I was really asking is "does your container take care of periodically running git update on a git directory I give it? or does it just do the last step"

>I mean ideally I would hope for `docker run -v /repo:/path/to/repo/on/host -e INTERVAL:300 src-expose` or something similar

>Atleast thats what I am planning on creating

This feels like the most useful way to use src-expose today (based on feedback from a handful of companies). They want to use some periodic syncing command that syncs changes as git commits in the repo, and then simply serves it. 

The extra step in our current default `src-expose dir` behavior of squashing all changes and committing them (and causing the Git history to be lost) is only useful in specific circumstances, and likely wouldn't be a common use case for our customers today.

**Comment by keegancsmith** [comment]
Just to make it clearer in my head. We expect most users of `src-expose` to not actually have git repos on a code host. Rather they have it stored some other way, but they have a tool to create local git repos (eg `git p4`). And they would like to get that into Sourcegraph.

For the same reason we have the periodic snapshotting built in, we would like periodic running of a command. This is a convenience over the user needing to muck about with cron / cron in docker?

If so that all sounds good, just want to get the motivation in my head clear.

**Comment by dadlerj** [comment]
Yep, that sounds like a good way to describe it!

So far, a majority of the customers and prospects I’ve worked with have
ended up in this state — where, ignoring how their external code is stored,
they end up running _some_ command periodically that results in a local git
repo that doesn’t require any additional “work” (such as running `git
commit`) before it’s ready to be served.

Those commands have included git-p4, git-tfs, and just a plain git pull (in
a situation where some special local setup was required).
-- 
Dan Adler
Sourcegraph <https://sourcegraph.com/> | @srcgraph
<https://twitter.com/srcgraph>

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by keegancsmith** [comment]
Sorry didn't have time to work on this. Maybe something useful for @unknwon to look into when he looks into src-expose? Feel free to unassign if not @unknwon.
