### ISSUE TITLE
OpenDiffOnSourcegraph: error when a staging repository is synced to the Sourcegraph instance

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#9652]
When visiting diffs for a repository whose staging repository is synced to the Sourcegraph instance, the following error can be seen in the console:

![image](https://user-images.githubusercontent.com/1741180/78790383-b8ce0000-79ae-11ea-8720-76976fbe64fa.png)

This is because `queryRepositoryComparisonFileDiffs()` is called with the base repo name & base commit ID, but with a head commit ID that exists on the staging repo, _not_ on the base repository.

Additionally, `<OpenDiffOnSourcegraph/>` is still rendered, and links to a diff that will produce an error on the Sourcegraph instance: 

![image](https://user-images.githubusercontent.com/1741180/78790567-02b6e600-79af-11ea-93da-70b28b985f33.png)

**Comment by pdubroy** [comment]
Is this still an issue?

**Comment by pdubroy** [comment]
I'm going to close this since it's over a year old, and I don't think there's enough information here for us to verify whether the issue still exists or not. Please feel free to re-open if necessary.
