### ISSUE TITLE
Hover states are inconsistent

### ISSUE THREAD

**Issue by imtommyroberts** [sourcegraph/sourcegraph#9659]
This is a design debt I would like to tackle in Q2.

Our hover states are all over the place, it would be nice to make these consistent. I'm going to share some examples below, and add to this issue as I come across more, please feel free to do the same. 

1. 

Here we're taken to another page, but we need to hover over this or another piece of text specifically to be taken to that page, but the whole background is highlighted.

![image](https://user-images.githubusercontent.com/40544396/78802495-cd61c680-79b5-11ea-9a3b-211fbb76108d.png)

2.

This is in the burger menu dropdown on .com, to left of the user icon dropdown. The pre and post hover state is different to that of the user icon dropdowns hover state.

![image](https://user-images.githubusercontent.com/40544396/78802523-d6eb2e80-79b5-11ea-8d21-86ceab3070f2.png)

3.

Here we have an additional underline, perhaps to indicate this will take you to another page and not create a dropdown from the carat?

![image](https://user-images.githubusercontent.com/40544396/78804106-a99f8000-79b7-11ea-8a94-0da245d85417.png)

General solution:

Right now, I feel like most of our hover state styling can follow this pattern. Items (text, icons) are a shade of blue, and white on hover, and a shade of blue appears as a backdrop. When there is a pre-defined border this backdrop fills to those edges, when there is no border (think extensions bar on .com) it fills to a universal amount of padding.

![image](https://user-images.githubusercontent.com/40544396/78804067-a1474500-79b7-11ea-9473-ac499ffeecb6.png)

Once we've agreed this is a problem and decided on a release window, I will produce designs with guidelines to follow in Figma.

This feels relevant: #9002

**Comment by pdubroy** [comment]
Closing this — last update was over a year ago, so I'm assuming it's obsolete. Please feel free to re-open if I'm wrong.
