### ISSUE TITLE
src-expose: periodically check if new repos or directories are added

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#9677]
Once `src-expose serve` is running, it does not seem to check if new git repos are added to the parent folder.

Adding this feature would prevent admins from having to manually restart `src-expose` if new repositories are added.

cc @dadlerj

**Comment by keegancsmith** [comment]
@ryan-blunden It doesn't store any state, it scans the filesystem on every request. If you have this connected to Sourcegraph, you may just be waiting for Sourcegraph to poll `src-expose serve` again. You can manually trigger a refresh by making a noop edit to the code host configuration.

**Comment by ryan-blunden** [comment]
Ok, that did it. Thanks!
