### ISSUE TITLE
Move src-expose from dev to cmd

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#9683]
The `src-expose` CLI tool is now being used by several customers so it's time to move it out of dev and under cmd.

**Comment by keegancsmith** [comment]
Everything under cmd is a service for us, not a cli. Additionally I plan on moving src-expose into src-cli. I think work like this is likely less important than promoting this in our official cli tool. #9243

**Comment by ryan-blunden** [comment]
Sounds good.
