### ISSUE TITLE
Add Azure install docs for Sourcegraph Server

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#97]
@ctolkien requested Azure install docs for Sourcegraph Serve at https://twitter.com/c_tolkien/status/1009689484361809921. We currently only have AWS, GCP, and DigitalOcean docs for Sourcegraph Server, although we do have Azure docs for Sourcegraph Data Center (https://github.com/sourcegraph/deploy-sourcegraph/blob/master/docs/k8s.azure.md).

We should add Azure install docs for Sourcegraph Server.

- [ ] Add step-by-step docs
- [ ] Add Terraform plan

**Comment by ctolkien** [comment]
Thanks 💃

**Comment by sqs** [comment]
SpaceHexagon also requested Azure install docs at https://twitter.com/SpaceHexagon/status/1103807673026445317

**Comment by dadlerj** [comment]
Ping @ggilmore and @ryan-blunden — we just had a request for this from https://app.hubspot.com/contacts/2762526/company/1832823611

**Comment by ryan-blunden** [comment]
Hey @ctolkien, I'm going to start working on this next week and will keep you posted. Would you be down for kicking the tires once I've got an initial version working?

**Comment by ctolkien** [comment]
@ryan-blunden  - yep, happy to help.

**Comment by dadlerj** [comment]
Also requested by a user at https://app.hubspot.com/contacts/2762526/company/557475593
