### ISSUE TITLE
Warn users when Sourcegraph is out of date

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#9708]
Sourcegraph instances that are offline (firewalled-off, configured not to, etc.) do not get update notifications because they cannot reach Sourcegraph.com to check for updates.

From paying customers, we see around 25%+ are running a version of Sourcegraph older than 4 months. [data](https://sourcegraph.slack.com/archives/CJX299FGE/p1585339813068500)

This is bad for a few reasons:

1. Users on these instances (even if the instance was able to contact Sourcegraph.com) do not know the instance is out of date, since we only display update-available notifications to site admins. This means that large numbers of our users may not know that Sourcegraph has improved and they are just using a really old version.
2. Because users aren't aware Sourcegraph is severely outdated, site admins managing these instances are not encouraged by their users to update it ([example](https://sourcegraph.slack.com/archives/C0B2RU51Q/p1586453412299900)).

We should progressively warn site admins and users when Sourcegraph is out of date, even if the instance cannot reach Sourcegraph.com. It should be possible and easy to derive this information from the version strings that are baked into Sourcegraph's `frontend` Go binaries at build time and display this information via global site-wide alerts.

https://sourcegraph.com/github.com/sourcegraph/sourcegraph@922ce20fcd3ce2534fd20d6b9805d350e611c45d/-/blob/internal/version/version.go

How it would work:

- We know Sourcegraph releases a new version on the 20th of each month, per our documented [release policy](https://about.sourcegraph.com/handbook/engineering/releases).
- If we release, say, Sourcegraph 3.16 and include "date of release" metadata in it then we can easily say the following:

| Time since date of release | Instance is offline? | shown to | dismissable? | alert message |
|---------------------------|--------------------|----------|--------------|----------------|
| 1 month | yes | admins only | yes | "Sourcegraph is 1 month out of date" |
| 2 months | yes | admins only | yes | "Sourcegraph is 2 months out of date" |
| 3 months | yes | admins only | no | "Sourcegraph is 3 months out of date, at 4 months users will be warned Sourcegraph is out of date" |
| 4 months | yes or no | all users | by non-admins only | "Sourcegraph is 4+ months out of date, for the latest features and bug fixes ask your site administrator to upgrade." |
| 5 months | yes or no | all users | by non-admins only | "Sourcegraph is 5+ months out of date, for the latest features and bug fixes ask your site administrator to upgrade." |
| 6+ months | yes or no | all users | no | "Sourcegraph is 6+ months out of date, for the latest features and bug fixes ask your site administrator to upgrade." |

cc @dadlerj does the above behavior look good to you?

**Comment by dadlerj** [comment]
Looks great to me!

**Comment by dadlerj** [comment]
CC @christinaforney for review, didn't mean to assign

**Comment by christinaforney** [comment]
Looks good to me too! Are you planning to use the existing banner styles for site notices? Were you planning to use info, warning, or alert styles? (Perhaps this changes depending on the length of time).

**Comment by slimsag** [comment]
> Are you planning to use the existing banner styles for site notices?

Yes, since this should just be a backend change.

> Were you planning to use info, warning, or alert styles? (Perhaps this changes depending on the length of time).

It should change based on severity, yeah.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by slimsag** [comment]
Note: I tagged this as 3.16 optimistically, but most likely it'll land after branch cut so no rush.

**Comment by daxmc99** [comment]
After discussing with @slimsag 

1. Refactor this code such that plain users ALSO get update notifications. 

2. Update alerts continue to increase in severity 

Minor modification: This should occur inside of the `site_update_check.go` file via the `UpdateCheck` GraphQL site resolver _instead_ _of_ inside of site_alerts. We should maintain the animations of the current update check notifications. 


Steps to be taken: 
1. Allow [this query](https://github.com/sourcegraph/sourcegraph/blob/5e425cfec07790e8f4836738629c5ec2b0dd2e6a/web/src/site/backend.tsx#L25-L58) to return without err to normal users. Ensure no secure info is leaked

2. Refactor `update_check` so that it returns checks for nomal users.

3. Modify `update_check` so that it can support checking the version offline and can indicate the instance is offline (not able to reach "https://sourcegraph.com/.api/updates") 

4. Modify `UpdateAvailableAlert.tsx` to support **non**-dismissble alerts, also modify graphQL schema.

**Comment by slimsag** [comment]
Updated estimate for "anticipated time in 3.17" -- feel free to alter if what I put looks wrong
