### ISSUE TITLE
View history view broken on sourcegraph.com

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#9713]
Repro: Go to https://sourcegraph.com/github.com/sourcegraph/sourcegraph@34ab38ed015ce2aa30d058c1d6679c1569fb28b8/-/blob/cmd/frontend/internal/httpapi/router/router.go#L50&tab=history. Got:

![image](https://user-images.githubusercontent.com/1646931/78935882-7108b080-7a62-11ea-8093-c163b20839c0.png)

![image](https://user-images.githubusercontent.com/1646931/78935930-7ebe3600-7a62-11ea-8452-7ee5c51394a7.png)

**Comment by pdubroy** [comment]
Closing since this seems to be fixed.
