### ISSUE TITLE
Surface alert if type: other than file is used with stable:

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#9715]
> Will the user appropriately get an error if they try to run a different type of search like type:file type:symbol? Or will they not get symbol results and end up surprised?

> I can handle this better by throwing an alert if type is explicitly specified for anything other than file.

From https://github.com/sourcegraph/sourcegraph/pull/9681#discussion_r405941029

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by rvantonder** [comment]
This is enforced by the new parser (`"migrateParser" : true`). Will close when migration is complete.

**Comment by marekweb** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by rvantonder** [comment]
Stable is removed.
