### ISSUE TITLE
Document LSIF data expectations

### ISSUE THREAD

**Issue by christinaforney** [sourcegraph/sourcegraph#9719]
From [slack thread](https://sourcegraph.slack.com/archives/CHXHX7XAS/p1586462406237200).

Is there documentation somewhere explaining which LSIF data tuples we accept and which we ignore?

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by efritz** [comment]
Also requested in https://github.com/sourcegraph/sourcegraph/issues/10385.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
