### ISSUE TITLE
Grafana sqlite DB can get stuck in a locked state; prevents Grafana from working entirely

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#9720]
At a customer deployment (https://app.hubspot.com/contacts/2762526/company/407948923) we observed Grafana get stuck with all dashboards failing to load any metrics from the Prometheus data source. Upon closer inspection, Grafana's internal data proxy was failing as indicated by its logs:

```
t=<redacted> lvl=eror msg="failed to run garbage collect" logger=remotecache.database error="database is locked"
t=<redacted> lvl=eror msg="failed to run garbage collect" logger=remotecache.database error="database is locked"
t=<redacted> lvl=eror msg="Data proxy error" logger=data-proxy-log userId=0 orgId=1 uname= path=/api/datasources/proxy/1/api/v1/query remote_addr="<redacted>" referer="https://<redacted>/-/debug/grafana/?orgId=1" error="http: proxy error: dial tcp <redacted>:9090: i/o timeout"
t=<redacted> lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/api/datasources/proxy/1/api/v1/query status=502 remote_addr="<redacted>" time_ms=<redacted> size=0 referer="<redacted>"
```

This appears to be an issue others have faced with Grafana where its sqlite DB gets stuck in a locked state, and is reportedly fixed in v6.7.1 (which we are running). This can be worked around via these instructions to recover the sqlite DB: https://github.com/grafana/grafana/issues/16638#issuecomment-494427913

In specific, for a pure-docker or Docker Compose Sourcegraph deployment, the command is:

```
docker exec -it -u 0 grafana sh -c 'apk add --no-cache sqlite && cd /var/lib/grafana && sqlite3 grafana.db ".clone grafana-new.db" && mv grafana.db grafana-old.db && mv grafana-new.db grafana.db'
```

I suspect this happens when the container is terminated non-gracefully (such as shutting down the host running the containers without shutting down the containers themselves first).

### Potential solutions

1. The main reason I see for having a persistent Grafana volume is for when users configure alerting (otherwise they'd lose that across restarts), so removing that and starting fresh on each boot seems like a no-go option (even though we provision everything else from pre-baked files on disk).

2. https://github.com/grafana/grafana/pull/17274 seems to indicate this might not be an issue when Grafana's auth proxy is in use. This is something I've been meaning for us to upgrade to for a while since they fixed the CSRF vulnerability I reported to them. So this issue may implicitly be fixed by resolving https://github.com/sourcegraph/sourcegraph/issues/6075

3. We could run the sqlite commands above as the entrypoint in our Docker image, so that the DB is never stuck in a locked state?

**Comment by slimsag** [comment]
This happened again, but the resolution wasn't so easy. I think even with the command above `sqlite3 grafana.db ".clone grafana-new.db"` can fail due to timeout if Grafana is holding (some other?) lock to the DB.

Probably easily solved by just copying the file first before invoking the `sqlite3` command, more resilient workaround:

```
docker exec -it -u 0 grafana sh -c 'cd /var/lib/grafana && rm grafana.db && apk add -v --no-cache sqlite && du -sh ./* && cp grafana.db grafana-tmp.db && echo "cloning grafana-tmp.db" && rm -f grafana-new.db && sqlite3 grafana-tmp.db ".clone grafana-new.db" && mv grafana.db grafana-$(date +%s).db && mv grafana-new.db grafana.db && echo "Success!"'
```

Ultimately it was easier to wipe the entire Grafana disk (we didn't have any custom alerts/dashboards configured):

```
docker stop grafana
mv $VOLUMES/grafana-disk $VOLUMES/grafana-disk-bak
mkdir -p $VOLUMES/grafana-disk
chown -R 472:472 $VOLUMES/grafana-disk
docker start grafana
```

(then navigating back to Grafana via Sourcegraph web UI for the user creation)

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by pecigonzalo** [comment]
Closing as e has not seen reports of this in a while. Given that Grafana can likely be destroyed and re-created, ill close this for the time being.

Feel free to re-open if we heard back from this issue.
