### ISSUE TITLE
kubernetes: prevent regressions of SSH gitserver secrets not being respected

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#9722]
Primary goal: avoid site admin pain such as https://github.com/sourcegraph/deploy-sourcegraph/pull/583#issuecomment-611603625 in the future.

Certain customers configure SSH git authentication, following [our instructions](https://github.com/sourcegraph/deploy-sourcegraph/blob/master/docs/configure.md#configure-repository-cloning-via-ssh). Possibly because the secret is created by `kubectl` and not represented in any of the files in deploy-sourcegraph, we failed to test for this scenario when implementing the k8s permission updates. If that is the case, a potential solution is the create a placeholder `git.Secret.yaml` file that is mounted into the gitserver FS and update our docs appropriately.

Update: If we implement the above suggestion, we should include a ConfigMap(s) for everything that might be mounted into the .git or .ssh directories. There are other git customizations we need to support ([example](https://github.com/sourcegraph/sourcegraph/pull/9688/files#diff-f874bd526c28a1954651c1979d797763)).

Another thought: perhaps we should be testing more of these configurations out in our CI, and also testing upgrades from the previous minor version of deploy-sourcegraph to `master`.

**Comment by slimsag** [comment]
https://github.com/sourcegraph-testing

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by slimsag** [comment]
https://github.com/sourcegraph/deploy-sourcegraph/pull/687

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
https://github.com/sourcegraph/deploy-sourcegraph/pull/687
