### ISSUE TITLE
deploy-sourcegraph: Separate manifests for non-admin users

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#9723]
Copied from https://github.com/sourcegraph/deploy-sourcegraph/issues/596. From @dadux:

We run large multi-tenanted Kubernetes clusters, with a dedicated team looking after the cluster (admin, monitoring, etc...)
All the clusters are self-service as much as possible.

One of our a team have successfully deployed sourcegraph in their own namespace, but in order to do so they had to manually apply only a subset of the manifests. 
Some objects (ClusterRoleBindings for example) require cluster-admin privileges. 

Would it be possible to split the config for non-admin users when doing the `kubectl-apply-all.sh` ? I believe only the prometheus config requires cluster wide privileges, and we already manage that in a separate instance.

This would greatly make upgrades easier for them if they can use the upstream tool.

**Comment by beyang** [comment]
@dadux yes, this should be possible. We'll discuss this for the next iteration.

**Comment by uwedeportivo** [comment]
https://github.com/sourcegraph/deploy-sourcegraph/pull/685
