### ISSUE TITLE
deploy-sourcegraph: AWS EKS questions/notes

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#9724]
From @sqs (migrated issue from https://github.com/sourcegraph/deploy-sourcegraph/issues/519):

I followed https://github.com/sourcegraph/deploy-sourcegraph/blob/master/docs/k8s.eks.md. Keeping a list of questions/notes:

- `(others do not support EKS yet as of September 12, 2018)` docs should be updated, more regions now support EKS
- `Under Security groups, select the one prefixed eks-vpc-sourcegraph-ControlPlaneSecurityGroup-` I don't recall seeing this one and didn't select it (will see if it causes problems later)
- `Select the very last Specify an Amazon S3 template URL option and enter https://amazon-eks.s3-us-west-2.amazonaws.com/cloudformation/2018-08-30/amazon-eks-nodegroup.yaml` This is different from what the guide at https://docs.aws.amazon.com/eks/latest/userguide/worker_node_IAM_role.html recommends. The guide does not recommend using a CloudFormation stack to create the nodegroup. Perhaps this is because the EKS console now has a UI for nodegroup creation, and you only need to create the IAM role via CloudFormation now. So this whole doc section might need updating.
- `Under NodeImageId, choose based on your region:` now that more regions support EKS, and now that the EKS console has a node group creation UI, we don't need to specify these AMIs. They are also incomplete (more regions support EKS than are listed in our docs).
- The EKS docs were hard to find in this repo. I did not realize that `Amazon EKS` at https://github.com/sourcegraph/deploy-sourcegraph/blob/master/docs/k8s.md linked to a much more helpful (although outdated) doc page for EKS. I originally assumed the EKS link just went to AWS's EKS site.

**Comment by bobheadxi** [comment]
> This is different from what the guide at https://docs.aws.amazon.com/eks/latest/userguide/worker_node_IAM_role.html recommends.

It looks like the documentation in `deploy-sourcegraph` is based on  https://docs.aws.amazon.com/eks/latest/userguide/getting-started-console.html , which contains pretty much the exact same guidance still
