### ISSUE TITLE
ActionItems in references panel don't look good

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#9740]
The change to truncate ActionItems over a certain width affects the action items in the references panel, which are currently just text. @imtommyroberts  I think we should rethink these

![image](https://user-images.githubusercontent.com/10532611/79002294-747a6580-7b50-11ea-9e36-7623e3a17d05.png)

**Comment by AlicjaSuska** [comment]
Thank you for bringing this up @felixfbecker Here is my proposition of fix:

**Changes (big screens):**
- move action items to the same row as tabs
- change tabs margin to 8px (was 4px)
- remove 'max-width' from action items to avoid overflowing (always one line)
- add divider below the tabs/action items bar

<img width="1536" alt="References-fix" src="https://user-images.githubusercontent.com/20326070/97843353-72911300-1ce9-11eb-92f5-b9860bce5c44.png">

**In addition on the small screens:**
- drop action items below the tabs bar when they cannot fit in one row any more
- add a divider between tabs and action items rows

![References-small-fix](https://user-images.githubusercontent.com/20326070/97843271-4bd2dc80-1ce9-11eb-8082-0efb53cbdf57.png)

**Connected fix: underline missing from the tabs bar #14251**

**Comment by felixfbecker** [comment]
Okay, so to summarize the changes:
- Move the action items to the level of the tabs themselves
  - Note these are only for the references tab. Does that mean they should disappear when switching tabs?
  - I don't know how easy this will be to do, because it will require commmunication across component boundaries (since the buttons now reside outside the tab content area, but only appear when a certain tab is active)
- **Remove** the thick underline completely from the tabs themselves (seen in screenshot in the issue above), instead of restoring it when fixing https://github.com/sourcegraph/sourcegraph/issues/14251, and remove the blue active underline in favor of a thin text-color underline.
  - The tabs are a shared component used in multiple places of the app (e.g. the sidebar too), so this would change the look of the tabs everywhere. Can you confirm you want these changes to be made to the sidebar too?

**Comment by Joelkw** [comment]
Copying a relevant comment from #15951 – I feel like keeping these action items on the far right is still a bit odd, given all the other menu interactions/non-code display is on the left. @AlicjaSuska this isn't high priority but while this is "in progress" I'd be curious to see what a version with these text actions on the left could look like.

**Comment by AlicjaSuska** [comment]
@Joelkw I think we can left-align on the smaller screens - it looks good:
![Left-align-small](https://user-images.githubusercontent.com/20326070/100214802-96263280-2f10-11eb-814d-7988f287e0ff.png)

On bigger screens, I would leave the action items on the right. When they are close to tabs with a lof of white space on the right, they look a little confusing:

<img width="1536" alt="left-align-big" src="https://user-images.githubusercontent.com/20326070/100214882-ab02c600-2f10-11eb-8ca1-2b660ec31c4c.png">

What do you think about it?

**Comment by Joelkw** [comment]
I agree with all of that. I think it helps even just moving them onto the same line; right now they're on the right but on their own line – if they're on the same line as the 'x' I think it establishes more of a "group" UI spot than an orphaned set of buttons.

**Comment by AlicjaSuska** [comment]
@Joelkw can we fix it any time soon?

**Comment by Joelkw** [comment]
@AlicjaSuska now that we have a frontend platform group, yes! I expect this could be done as soon as the next iteration; moved it around some other larger issues since it could be good for an onboarding-esque task.

**Comment by AlicjaSuska** [comment]
That's great news @Joelkw . I moved designs to a [separate file](https://www.figma.com/file/yPrTtrvmkUtizDuzWiqzrZ/9740-ActionItems-in-references-panel-don-t-look-good?node-id=246%3A11), they are ready for the final review. @felixfbecker I've addressed your concerns from the comment (restored the current visual for tabs and added the case for other tabs with no action items).

Please, add your reviews (in [Figma](https://www.figma.com/file/yPrTtrvmkUtizDuzWiqzrZ/9740-ActionItems-in-references-panel-don-t-look-good?node-id=246%3A11)) by the end of this week @Joelkw @felixfbecker @quinnkeast

**Comment by felixfbecker** [comment]
(Alternatively this could also be argued to be an Extensibility task as it's in the reference panel)

**Comment by AlicjaSuska** [comment]
[Design](https://www.figma.com/file/yPrTtrvmkUtizDuzWiqzrZ/9740-ActionItems-in-references-panel-don-t-look-good-Approved?node-id=246%3A11) is ready and approved
