### ISSUE TITLE
RFC 139: Remove language servers

### ISSUE THREAD

**Issue by creachadair** [sourcegraph/sourcegraph#9742]
This issue tracks the work to remove language servers as documented in [RFC 139][1].

- [x] Disable language servers in the global settings on sourcegraph.com.
- [ ] Down the language server pods and recover their resources in k8s.
- [ ] Update deploy-sourcegraph/configure to remove language server deplyments.
- [ ] Remove language server support from the Go and TypeScript extensions.
- [ ] (cleanup) Consolidate the Go and TypeScript extensions to remove unnecessary duplication.

[1]: https://docs.google.com/document/d/1dl5u03dD63-RZB7S1p2IqFTiVcdx6On0aeIOXgsTehA/edit

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by efritz** [comment]
Before moving on with this work, we need to ensure that customers that still rely on language servers for their private instance have a suitable replacement.

One such path forward is via the effort in [RFC 153: Automatic LSIF indexing](https://docs.google.com/document/d/1LFwtfIqTgxzyNQDRvKsWbY9pZKiXVhwPyrNB04gnpDQ). Another such path is effort we are putting into manual LSIF adoption.

**Comment by macraig** [comment]
@ebrodymoore do we have any data on which customers that still rely on language servers?
