### ISSUE TITLE
gitserver low_disk_space alerts and other alerts may fire right when containers come online due to overprojection

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#9743]
Gitserver low disk space alerts may fire right when containers come online because the metrics are present but not yet populated with information. Need to find a way to relax this so this doesn't happen.

Fires both critical and warning alerts.

Only happens directly when containers start, not when they are otherwise down.

**Comment by slimsag** [comment]
Same thing happening with:

- `critical: echo_duration_slow`
- `critical: high_concurrent_execs`
- `warning: large_clone_queue`
- `warning: large_ls_remote_queue`

All of these are due to the overprojection of prometheus metrics I think.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
