### ISSUE TITLE
Frontend dashboard: "non-200 indexed search responses every 5m" should be by (category,code)

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#9744]
We record both a `category` (e.g. `List`, `Search`) and `code` (`error`) so we should display both.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by bobheadxi** [comment]
Does this refer to https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/monitoring/frontend.go#L371:1-383:9 ?

**Comment by bobheadxi** [comment]
This dashboard is not owned by distribution

**Comment by stefanhengl** [comment]
Triaging. Closing this because the panel doesn't exist anymore.
