### ISSUE TITLE
Site admin checklist for activation flow

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#975]
Site admin checklist UI: https://zpl.io/aXkpgop

**Comment by francisschmaltz** [comment]
I'll work on mockups for the new additions to the UI. @KattMingMing can you list a few message/stat ideas we could create for admins to send

**Comment by francisschmaltz** [comment]
Site admin checklist UI: https://zpl.io/aXkpgop

**Comment by beyang** [comment]
Can one of you add me to the Zeplin? 
![image](https://user-images.githubusercontent.com/1646931/52218427-87c9db00-2892-11e9-91b2-c9282e875f14.png)

**Comment by francisschmaltz** [comment]
@beyang CC: @ all sourcegraph I've added everyone.
