### ISSUE TITLE
Add protocol buffers to our `lang:` search filter

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#9750]
Requested by https://app.hubspot.com/contacts/2762526/company/768958891

We were screensharing, and the user seemed concerned that Sourcegraph didn't support searching for proto files... I wonder if there's a downside of having the lang filter, in that not having everything listed there erodes confidence? This is almost certainly overthinking it, but wanted to share (CC @christinaforney)

.proto and .pb seem to be the relevant extensions here...

**Comment by attfarhan** [comment]
I think your concern about users thinking some languages aren't supported is valid. I'll file another issue.
