### ISSUE TITLE
Merge deploy-sourcegraph latest into k8s.sgdev.org

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#9759]
I need to merge the latest updates to deploy-sourcegraph into k8s.sgdev.org in order to test out the updates to Jaeger I want to ship this milestone. However, I'm unfamiliar with Pulumi and also the latest build changes to deploy-sourcegraph, so can't effectively resolve the merge conflicts that arise when trying to pull the latest changes.

There appears to be another issue where k8s.sgdev.org is not auto-updating at the moment (potentially because the sha256 tags are missing so Renovate is failing).

@ggilmore could you do this by EOD Monday?
- [ ] @ggilmore after this is merged, can you post something in #dev-ops stating that k8s.sgdev.org is auto-deployed again?

**Comment by slimsag** [comment]
Note: Renovate cannot update the image tags in deploy-sourcegraph-dogfood-k8s currently due to them being `59913_2020-04-02_5ae630c`

**Comment by slimsag** [comment]
https://github.com/sourcegraph/deploy-sourcegraph-dogfood-k8s/blob/release/base/frontend/sourcegraph-frontend.Deployment.yaml#L68

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by ggilmore** [comment]
This gas been resolved. k8s.sgdev.org is up to date with https://github.com/sourcegraph/deploy-sourcegraph/commit/2a86be5bbbbfdb95827ad551c2ca5895efe744ae

The only pulumi issue was that it doesn't handle kustomize files (not a recognized k8s api type). This was solved using the same technique that's in our integration tests. The other time syncs were nagivating all the permissions changes (non-root users) that were introduced by the merge. 

Everything is up to date now, and all the services are using `insiders` tags.

**Comment by uwedeportivo** [comment]
👍
