### ISSUE TITLE
tracking-issue-syncer: missing some of my PRs

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#9774]
I'm not sure why but the tracking issue syncer is missing some of my PRs. It seems to be only ones that are not linked to issues? These without linked issues did not get put in our tracking issue:

- https://github.com/sourcegraph/sourcegraph/pull/9765
- https://github.com/sourcegraph/sourcegraph/pull/9767
- https://github.com/sourcegraph/sourcegraph/pull/9769
- https://github.com/sourcegraph/sourcegraph/pull/9770

I tried debugging briefly by searching in https://github.com/sourcegraph/sourcegraph/actions?query=workflow%3A%22Tracking+Issue+Syncer -- but I wasn't able to figure out the search syntax there enough to figure out definitively if the event fired or not, so I am not sure

**Comment by slimsag** [comment]
It seems to have happened around when https://github.com/sourcegraph/sourcegraph/pull/9734 was merged, so maybe the `latest` image is just not up to date?

**Comment by tsenart** [comment]
Was a bug, fixed!
