### ISSUE TITLE
verbose Jaeger logs should be redirected to file

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#9778]
Grafana and Prometheus both have their verbose logs redirected to a file (in both dev and `sourcegraph/server` deployments), so as to not pollute our application logs. Jaeger should follow the same pattern.

- Prometheus: https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+prometheus.log&patternType=literal
- Grafana: https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+grafana.log&patternType=literal

This should be fixed before we cut the release.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by slimsag** [comment]
Dev portion fixed by https://github.com/sourcegraph/sourcegraph/pull/9896

Leaving this issue open for @beyang to reference when adding Jaeger to single-container instances
