### ISSUE TITLE
Major regression in code host syncing / EXTSVC_CONFIG_FILE support?

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#9779]
@sourcegraph/core-services Running `./enterprise/dev/start.sh` on the latest `master` shows:

```
repo-updater | WARN Updating rate limiter, kind: AWSCODECOMMIT, err: internal rate limiting not support for AWSCODECOMMIT
repo-updater | WARN Syncer not started for unsupported code host, kind: GITLAB
repo-updater | WARN Syncer not started for unsupported code host, kind: AWSCODECOMMIT
repo-updater | WARN Syncer not started for unsupported code host, kind: GITLAB
repo-updater | INFO server listening, addr: 127.0.0.1:3182
```

This looks like a major regression in code host syncing support, since most customers use the `EXTSVC_CONFIG_FILE` to load configuration. What change introduced this?

**Comment by mrnugget** [comment]
cc @ryanslade

**Comment by tsenart** [comment]
@mrnugget: Can you take a look at this? @ryanslade is off today, and this is release blocking, so I think it'd be better for us to address it sooner.

**Comment by mrnugget** [comment]
I'm pretty sure this is harmless, but not 100%:

https://github.com/sourcegraph/sourcegraph/blob/6fdd0e3ef693597ca167140cf5d20b1e223793f7/enterprise/internal/campaigns/syncer.go#L81-L86

 See my comment here: https://github.com/sourcegraph/sourcegraph/pull/9544/files#r402890686 @ryanslade Would be great if you could reply to that.

In the meantime, I'll change that to a `log15.Debug`
