### ISSUE TITLE
Alert when search indexing is failing

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#9783]
When we're trying to index repositories (in zoekt) and it is failing, an alert should fire.

c.f. https://github.com/sourcegraph/deploy-sourcegraph-docker/issues/55

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by poojaj-tech** [comment]
@slimsag does this include improving the UI experience for users who experience lagging or unavailable indexing - issue created here #12029. Let me know if this issue belongs in code intel instead.
