### ISSUE TITLE
Improve search scanner parameterization

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#9784]
The scanner introduced in #9777 makes some opinionated decisions about corner cases that could be better abstract for each kind of search. For example, it decides to always treat a `\n` encountered outside of quotes as a newline rather than literal slash-followed-by-the-letter-n. The latter is preferred for literal search.

It also interprets escape sequences for metasyntax in our language, like `\:`, and in some scenarios we might want to disable that. 

It also makes the decision to not try and parse quoted values in the heuristic search pattern scanner, meaning, it interprets `"foo"` without unquoting before the grammar spec can unquote it. This is desirable for now, but in future we want the heuristic scanner to be parameterized in a way that decides whether to unquote or not.

Last, we pass in heuristic options to the `ScanValue` function, but this parameterization could be better accomplished with higher order functions.

**Comment by camdencheek** [comment]
cc @sourcegraph/search-platform, I'm closing this since the parser has changed pretty dramatically since it was opened, but it might still be some useful historical context
