### ISSUE TITLE
Alert on gitserver "Deadline Exceeded" rate?

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#9786]
Unclear how useful this actually is currently. See linked PR.

https://sourcegraph.com/github.com/sourcegraph/sourcegraph@fc0dfa5e9bc6dc83bab8e012f492804c87721202/-/blob/internal/gitserver/client.go#L276-281

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by pecigonzalo** [comment]
@tsenart I believe this is for Core/Backend to decide.
