### ISSUE TITLE
monitoring: show disk space in GB not just percentage

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#9787]
Currently, the Git Server dashboard shows disk space in percentages. GB will likely be useful in some cases, so I should figure out how such a thing would fit into the generator.

Most likely, we do not want this to violate the existing rule of "everything worth monitoring is also worth alerting", so perhaps a way to express the ratio as two separate panels.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
