### ISSUE TITLE
Swift language support

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#979]
We will be adding Swift language support to Sourcegraph to provide hovers, go-to-definition, find-references, and possibly other features for Swift code. Details TBD. This is expected to ship in Sourcegraph 3.0 (2nd week of Jan 2019).

### Links

- Likely the best lang server to use: https://forums.swift.org/t/introducing-sourcekit-lsp/17964
- Blog post about it: https://nshipster.com/language-server-protocol/
- Older discussion about it: https://forums.swift.org/t/new-lsp-language-service-supporting-swift-and-c-family-languages-for-any-editor-and-platform/17024
- Old lang server: https://github.com/RLovelett/langserver-swift

**Comment by chrismwendt** [comment]
Swift code intelligence has been added in Sourcegraph 3.0 :tada:

https://about.sourcegraph.com/blog/sourcegraph-3.0#code-intelligence-for-all-languages

[Try it out](https://sourcegraph.com/github.com/iina/iina@99b2f539054d88f82f7486daa2f67d5ddac9c8cc/-/blob/iina/InitialWindowController.swift#L226:19) on Sourcegraph.com:

![image](https://user-images.githubusercontent.com/1387653/52603160-84969800-2e1a-11e9-8c58-dcd32778a22b.png)
