### ISSUE TITLE
monitoring for CPU and memory usage in Kubernetes

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#9791]
Today, we have container CPU and memory monitoring on each service dashboard e.g. at the bottom of https://k8s.sgdev.org/-/debug/grafana/d/frontend/frontend?orgId=1

![image](https://user-images.githubusercontent.com/3173176/82520383-de374900-9ad8-11ea-954e-73c431258c94.png)

As it says, however, this is not available in Kubernetes deployments yet. In docker-compose deployments we use cadvisor to export these metrics for Prometheus to scrape:

https://github.com/sourcegraph/deploy-sourcegraph-docker/blob/master/docker-compose/docker-compose.yaml#L485-L504

Historically, I believe we had [node_exporter](https://github.com/prometheus/node_exporter) which exposed _some_ CPU and memory container metrics but not as much as cadvisor did itself (internally, I understand Kubernetes runs cadvisor but I think perhaps it can be an outdated version or something?)

From an initial glance, I think we should add cadvisor to https://github.com/sourcegraph/deploy-sourcegraph by doing something like what is done in the official cadvisor kubernetes deployment here: https://github.com/google/cadvisor/tree/master/deploy/kubernetes
 
This will ensure we have the closest / most similar Prometheus metrics as in our docker-compose deployments, so the existing queries on the Grafana dashboards should likely just work (or, if not, it should be easy to tweak them in a way that works in both environments).

One challenge, however, is that we want to make sure:

1. It is in the base deployment, for all stock / out-of-the-box Kubernetes deployments: https://github.com/sourcegraph/deploy-sourcegraph/tree/master/base
2. We edit the non-privileged overlay [here](https://github.com/sourcegraph/deploy-sourcegraph/tree/master/overlays/non-privileged) so that it disables / removes the cadvisor deployment we add in `base/`, since it will require privileged access to the Kubernetes cluster.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by slimsag** [comment]
Updated the issue description with a lot more information about what this entails, feel free to ping me or @uwedeportivo if you start working on this and have any questions

**Comment by daxmc99** [comment]
Do we also want to add this as a Grafana dashboard? Linkerd does this 
https://sourcegraph.com/github.com/linkerd/linkerd2@2b8df8076d750062c6ab478fe0c8f16797ee090e/-/blob/grafana/dashboards/kubernetes.json#L15:4

**Comment by slimsag** [comment]
All existing service-level dashboards (which encapsulate multiple pod replicas and containers) should include CPU/memory/disk metrics at the bottom of them. This way one can see if a specific service's issues are possibly due to resource limits instead of needing to go to another dashboard for that info

Monitoring the host k8s nodes itself (and in the case of Docker Compose, the host machine) would be an additional good thing to have and would warrant introducing a new dashboard - but probably outside the scope of this issue itself

**Comment by slimsag** [comment]
If someone wants to file an issue for the latter, that'd be great! I think we'd need `node_exporter` probably in both k8s/docker-compose deployments, and a "Kubernetes" (k8s deployments) + "System" (docker-compose deployments) dashboards, respectively.

**Comment by slimsag** [comment]
There may be some heavy overlap with https://github.com/sourcegraph/sourcegraph/issues/7529 here.

**Comment by bobheadxi** [comment]
> Monitoring the host k8s nodes itself (and in the case of Docker Compose, the host machine) would be an additional good thing to have and would warrant introducing a new dashboard

Curious about this - how do orgs that have these deployments typically monitor their clusters? Won't implementing node-level monitoring likely overlap with monitoring that other orgs already have in place (as opposed to per-service monitoring, which is a bit more specific to sourcegraph)

**Comment by slimsag** [comment]
It's a bit of a mixed bag:

_Some_ organizations are in the "oh yeah, we use k8s everywhere and have our own monitoring stack for everything. In fact, we're not really sure we want to use yours at all...?"

Other organizations are in the "we've never used k8s in our lives, we heard we can provision a cluster on GCP or EKS and then deploy Sourcegraph? How do we monitor it, though?"

You're totally right it does get more into the "we own the cluster" space, but I think that's _probably_ okay. I consider this low-priority. The more important priority here is knowing "does sourcegraph have too many (or too little) resources" which can be entirely done with container-level cadvisor monitoring and without introducing a new dashboard (can be done as additional panels on the existing dashboards).
