### ISSUE TITLE
Alert if containers are entirely down/missing

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#9792]
alerts should fire when services are down, regardless of what other alerts are defined.

Note: alertmanager on Sourcegraph.com (the old monitoring system) has pod downtime metrics, but they sometimes are flaky as they fire when deployments happen (too aggressive) https://sourcegraph.slack.com/archives/CMBA8F926/p1593629287002800 (also we want this to work for all deployment types, not just kubernetes).

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by keegancsmith** [comment]
> alertmanager on Sourcegraph.com (the old monitoring system)

What is the new one? :) Additionally alertmanager doesn't do alerting, it just notifies other systems. Alerting rules are defined in prometheus which I assume we are still using. I guess we now define rules in some other system which just consumes prometheus?

FYI this should be quite easy to tweak. We already have both alerts (totally down vs partially down). We should special case the alert for services that are currently not coming up quickly. For the partial down that alert needs to be changed. It was originally written when we had small deployments. Now we have massive stateful sets which take much longer to roll out, so you will have 1 pod down (but constantly changing) for much longer. The alert only checks the percentage of down pods, not if specific pods are down.

**Comment by slimsag** [comment]
> Edit: I see we are now using grafana alerting. Cool, will check it out.

We are not, we started going down that rabbit hole and then switched due to some major limitations it had that we ran into (no templating, etc.) We are currently in the process of switching back to alertmanager but making it super friednly for site admins to set up alerting. https://github.com/sourcegraph/sourcegraph/pull/11832 - lengthy conversations about this [here](https://github.com/sourcegraph/sourcegraph/issues/11452#issuecomment-648567565)

I will document the architecture more clearly somewhere, but the quick response is:

- We ship Grafana with baked in dashboards
- We ship Prometheus with baked in alerting rules
- We ship alertmanager which can be configured through the Sourcegraph site config (as part of admin/product onboarding)
- There is a Go generator which produces all of the above at a per-service level (the dashboards, alerting rules, etc.) and keeps them consistent. It is defined here https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/tree/monitoring

The monitoring generator, motivations here, and dev experience are all documented in more detail here: https://about.sourcegraph.com/handbook/engineering/distribution/observability/monitoring

**Comment by bobheadxi** [comment]
> I will document the architecture more clearly somewhere

For vis: https://github.com/sourcegraph/about/pull/1221

Re: the alerts - why is this not covered by our container restart rules/dashboards? If those don't measure this, what are those metrics? 🤔
