### ISSUE TITLE
[deploy-sourcegraph-docker] health checks should be defined in images

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#9794]
Docker Compose currently hacks the health checks via the compose file. These should be baked into our Docker images directly.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by davejrt** [comment]
closing in favor of https://github.com/sourcegraph/sourcegraph/issues/7746
