### ISSUE TITLE
Unindexed search archive cache is not monitored

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#9796]
Something like what was in the old searcher dashboard, but with alerts:

![image](https://user-images.githubusercontent.com/3173176/79108695-bb708280-7d2b-11ea-91c2-9b07dce8b045.png)

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket,  please attach a reliable way to reproduce the issue.
