### ISSUE TITLE
Missing monitoring for GraphQL requests in general

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#9797]
Defined performance warnings by common routes

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by bobheadxi** [comment]
@slimsag I'd like to take a stab at this - it seems like I can pull up request durations for all graphql routes with the following query:

```
route:src_http_request_duration_seconds_bucket:rate5m{route=~"graphql:.*"}
```

Presumably I'd set a alert on when this value is too high?

**Comment by slimsag** [comment]
There is some additional information in `src_graphql_field_seconds` but it's unfortunately our highest cardinality metric, and I think we should remove it fully. But before we can do that, we'll need to sort out this issue.

I think your query may be a good starting point, the problem is what we _really_ want to be doing is defining an alert per request because each of those `graphql:` request route types will have a different underlying GraphQL query with different complexity. We could try to break it up into individual alerts / panels, but that's frankly a lot of tedious work.

It may be best to wait on this one until we have (1) reporting from customer instances about which alerts are firing so we could find some average value of these requests across most instances or (2) put in place stricter cost-accounting of GraphQL requests
