### ISSUE TITLE
Extension registry discovery and statistics

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#980]
Milestones:
- [ ] User count 3.0
- [ ] Favorite/Star/Like for users to chose favorites 3.1
- [ ] Interaction stats 3.2
- [ ] Usage from other instances (opt-in) 3.2

**Comment by lguychard** [comment]
@sqs should this still be in 3.2?

**Comment by nicksnyder** [comment]
Closing because this is not in our near term roadmap.
