### ISSUE TITLE
Sign out page only has dark theme

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#9810]
#### Steps to reproduce:

1. Sign out of your account in your browser
2. See the sign-out page

#### Expected behavior:
It matches the theme (light) I had used before

#### Actual behavior:
![image](https://user-images.githubusercontent.com/19534377/79132719-1c8b6b00-7dab-11ea-889c-63e023cf471c.png)

It is themed dark

**Comment by rrhyne** [comment]
@quinnkeast here is another that should probably should be closed by: https://github.com/sourcegraph/sourcegraph/issues/12695

**Comment by quinnkeast** [comment]
Addressed in #12695.
