### ISSUE TITLE
search: Improve keyword scanning

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#9812]
In #9811 I introduced a helper function `matchKeyword` to identify keywords that must have spaces before and after. The function is not ideal because the lookbehind is avoidable, by making slightly more involved changes to `parseParameterList`. The lookahead/lookbehind is also imperfect because it looks at the byte, not rune.

Also, `type keyword` has become a misnomer: this should be renamed to `type syntax` or similar, and `type keyword` should refer to syntax that are actual keywords, i.e., separated by whitespace.

**Comment by camdencheek** [comment]
cc @sourcegraph/search-platform, also closing this one as stale, but you may again be interested

**Comment by keegancsmith** [comment]
cc @stefanhengl who worked on related areas recently.
