### ISSUE TITLE
Move e2e tests into regression test suite

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#9814]
Given we no longer run the e2e tests in CI as of https://github.com/sourcegraph/sourcegraph/pull/9615, we need to run them as part of the regression suite. This should be done starting with the current iteration's testing cycle.

There might be some duplication between the e2e tests and regression suite. Redundant tests should be eliminated.

**Comment by beyang** [comment]
@uwedeportivo can you handle this as part of the release testing process for this iteration?

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
also make at least a good portion of it runnable in CI and runnable for outside admin customers as part of their health check after an upgrade

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by pecigonzalo** [comment]
Closing this as I believe this should be tackled by each team as required.
