### ISSUE TITLE
search: unquote field values for validation

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#9818]
Things like `count:"3"` should validate when enclosed by quotes for and/or queries. Right now we do not, because the choice is currently to preserve quotes for other purposes (like search pattern values), and this needs to be separated.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
