### ISSUE TITLE
observability: frontend dashboard: P90/P99 search latency should clarify it covers successful searches only

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#9819]
Covering successful searches only makes sense, but should state this in the panel title / alert to avoid having anyone surprised or think we did this to be sneaky or anything.

![image](https://user-images.githubusercontent.com/3173176/79154683-d3c0bb80-7d84-11ea-9a63-5e45804bf6dc.png)

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
