### ISSUE TITLE
Flow (JavaScript) language support

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#982]
You will be able to see hovers, go to definition, and find references in JavaScript code with [Flow types](https://flow.org/). Sourcegraph already supports JavaScript (and TypeScript) using TypeScript's code analyzer and type inferencer (#960), but this does not yet support Flow. Details TBD.

**Comment by vicapow** [comment]
Any update on this one? With some guidance, I may be able to jump in.

**Comment by chrismwendt** [comment]
Sweet, code intelligence on Sourcegraph is now provided through [Sourcegraph extensions](https://docs.sourcegraph.com/extensions). We've built extensions for [Go](https://sourcegraph.com/extensions/sourcegraph/lang-go), [TypeScript](https://sourcegraph.com/extensions/sourcegraph/lang-typescript), and [Python](https://sourcegraph.com/extensions/sourcegraph/lang-python).

Anyone can create a new Sourcegraph extension for Flow support, and Sourcegraph is happy to help out with funding and technical guidance! @vicapow let me know if you'd like to get started 😃

**Comment by vicapow** [comment]
Still hoping we can add support for this.

**Comment by christinaforney** [comment]
@vicapow - are you still wanting to help out with this?

**Comment by vicapow** [comment]
We are but have not yet been able to prioritize it.

**Comment by christinaforney** [comment]
Ok cool! Let us know when you're ready and we can support.

**Comment by scalabilitysolved** [comment]
@macraig would this still fall within scope of lsif-node or something we'll close and track in productboard?

**Comment by macraig** [comment]
Tracking in productboard
