### ISSUE TITLE
search: Implement NEAR/proximity search variant

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#9822]
With and/or queries, `and` finds documents containing the same terms. It'd be useful to also do this on a line-bases or, within a certain distance AKA [proximity search](https://en.wikipedia.org/wiki/Proximity_search_(text)). There's a naive (i.e., expensive) way to get `near` pretty easily with our current search additions for matches on the same line. For proximity across multiple lines, it's more complex.

**Comment by dadlerj** [comment]
Requested by https://app.hubspot.com/contacts/2762526/company/557693052

**Comment by keegancsmith** [comment]
I believe this is something that OpenGrok likely supports? Something classic search engines usually do. I've never really seen this used in a dev search use case. I'd be interested in having some concrete examples of this being used.

**Comment by rvantonder** [comment]
> Use cases were, e.g., finding commands or function calls broken up into multiple lines, or finding a function usage preceded with a certain comment, etc.

https://sourcegraph.slack.com/archives/C0B2RU51Q/p1587057456371800

**Comment by rvantonder** [comment]
stale, closing
