### ISSUE TITLE
Increase maximum limit when evaluating and-expressions

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#9824]
Searching with and-expressions is currently designed and implemented to restrict doing too much work and avoid long run times that harm user experience. 

<img width="1069" alt="Screen Shot 2020-04-13 at 3 07 47 PM" src="https://user-images.githubusercontent.com/888624/79165749-9d8d3700-7d98-11ea-9a8d-a3989d9c395d.png">

If you ran into this issue, feel free to comment and share your thoughts or otherwise **+1 on this issue** if you would like us to prioritize addressing this restriction.

**Comment by jjwon0** [comment]
I also get this same error message when a more complicated query like this returns no results, which is really misleading.

**Comment by emclain** [comment]
It looks like  #11281 is closed.  Does that mean this cap can be lifted?

**Comment by rvantonder** [comment]
Hey @emclain. #11281 improved this, but it can still crop up. We have more improvements planned--if you're still seeing this message it means things are not as performant as we'd like it to be. I'll keep this issue open until we've added those improvements. Related to https://github.com/sourcegraph/sourcegraph/issues/15145.

**Comment by NightMachinary** [comment]
I get this error on a rather simple `not` [search](https://sourcegraph.com/search?q=context:global+file:%5Eposts/.*.org+repo:%5Egithub%5C.com/NightMachinary/r_HPfanfiction%24+timeloop+not+timeloopedpowergamer+count:100&patternType=regexp).

**Comment by craigkovatch** [comment]
I'm getting this with a simple search on `SingleSelectDropdown AND valid count:100`

**Comment by rvantonder** [comment]
Thanks for the input @craigkovatch, should have this nipped in the bud in our next release (2 weeks from now) or worst case, the one thereafter. As an interim workaround, since this that query only has two terms, you could try this regular expression instead:

```
(SingleSelectDropdown(.|\n)*valid)|(valid(.|\n)*SingleSelectDropdown)
```

**Comment by Smittyvb** [comment]
I get this with the seemingly simple query [`has not yet been implemented as HTMLFormControlElement in WKC layer`](https://sourcegraph.com/search?q=context:global+has+not+yet+been+implemented+as+HTMLFormControlElement+in+WKC+layer&patternType=literal). I was able to workaround that by just lopping off half the query, since it turns out just searching the last half was all I needed.

**Comment by Joelkw** [comment]
+1'ing this issue, just hit it trying to help out an interesting feedback/lead request – [see this for more details](https://github.com/sourcegraph/customer/issues/508) (details are private).

**Comment by rvantonder** [comment]
Thanks everyone for your patience, this issue should now be resolved and will be available in the next release: 3.39 and onwards. (We just kinda had to rewrite the entire search frontend over the course of many months to make this possible). Here's the corresponding CHANGELOG entry:

> Search patterns containing and and not expressions are now optimized to evaluate natively on the Zoekt backend for indexed code content and symbol search wherever possible. These kinds of queries are now typically an order of magnitude faster. Previous cases where no results were returned for expensive search expressions should now work and return results quickly. https://github.com/sourcegraph/sourcegraph/pull/33308

If you experience issues after the 3.39 release, please comment/reopen here.

**Comment by DaedalusG** [comment]
@rvantonder since this issue is closed should we remove the link in Sourcegraph.com?
![Screen Shot 2022-09-06 at 2 48 00 PM](https://user-images.githubusercontent.com/13024338/188746983-85a93194-c3f7-439c-9f37-188668243aac.png)
received for a `-content:` search

**Comment by rvantonder** [comment]
@DaedalusG updated in https://github.com/sourcegraph/sourcegraph/pull/41552 that provides a link to create a new issue. Please forward any questions or issues in slack, or create a new issue. Thanks!
