### ISSUE TITLE
Issues with Docker Compose on AWS installation docs

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#9829]
On a call with @beyang,  a user at https://app.hubspot.com/contacts/2762526/company/693777200 was attempting to follow our installation instructions at https://docs.sourcegraph.com/admin/install/docker-compose/aws and had trouble.

The instance never came online. When we walked through each section of the startup bash script and watched him execute them live, he ran into a few issues:

1. He was attempting to run them as a non-root user. Do we assume that this will be run as root?
2. He used the AWS default name for his EBS volume, /dev/xvdb, rather than our /dev/sdb (which is specified lower in the docs). The install script failed as a result. Can we auto-detect this instead of requiring them to name it a certain way?

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by slimsag** [comment]
> The instance never came online.

It is possible he didn't wait long enough, or that the drive was mounted incorrectly. It would've been nice to check the log output in this case, as is mentioned in the docs:

> * [...] You may have to wait a minute or two for the instance to finish initializing before Sourcegraph becomes accessible. You can monitor the status by SSHing into the instance and using the following diagnostic commands:
>
> ```bash
> # Follow the status of the user data script you provided earlier
> tail -f /var/log/cloud-init-output.log
>
> [...]
> ```

> When we walked through each section of the startup bash script and watched him execute them live, he ran into a few issues:

It's really not intended to be run live / directly, I would encourage restarting if you get to that point.

> He was attempting to run them as a non-root user. Do we assume that this will be run as root?

It does expect to be ran as root.

> He used the AWS default name for his EBS volume, /dev/xvdb, rather than our /dev/sdb (which is specified lower in the docs). The install script failed as a result. Can we auto-detect this instead of requiring them to name it a certain way?

This is definitely why the script failed, I have made this more explicit in the docs https://github.com/sourcegraph/sourcegraph/pull/12282

We can't easily auto-detect this AFAIK, going to see if the docs change helps and if this comes up again will see about different solutions.
