### ISSUE TITLE
Missing monitoring to signal if requests are not hitting search index

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#9838]
e.g. if most requests are hitting unindexed search, that is unexpected.

Should take into account symbol searches

**Comment by pecigonzalo** [comment]
@lguychard Re-assigning this, I believe this is something to be evaluated by the Search team.

**Comment by stefanhengl** [comment]
This issue has been inactive for a long time. To reopen the ticket,  please attach a reliable way to reproduce the issue.
