### ISSUE TITLE
(release docker compose 3.15) merge and test deploy-sourcegraph-docker#93

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#9839]
Tracking issue for me to merge and test https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/93

**Comment by slimsag** [comment]
https://github.com/sourcegraph/sourcegraph/pull/9552

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by slimsag** [comment]
I will do this after the 3.15 branch is cut.
