### ISSUE TITLE
multiple gitserver alerts need DataMayNotExist=true

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#9856]
Upon starting a docker-compose deployment:

![image](https://user-images.githubusercontent.com/3173176/79228520-6a898880-7e16-11ea-80b9-5bb17b472461.png)

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
