### ISSUE TITLE
observability: Improve ping logging

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#9866]
https://sourcegraph.com/github.com/sourcegraph/sourcegraph@855765631d4c8236ed6f5efcc7a356ffca9a84fa/-/blob/cmd/frontend/internal/app/pkg/updatecheck/client.go#L139-220

All of the logs in this function should have a proper prefix. Right now you must manually search frontend logs for each one, which is a huge pain and made debugging https://sourcegraph.slack.com/archives/CMB6K7SMN/p1586814349064400 really hard.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
