### ISSUE TITLE
observability: Add ping performance stats to frontend dashboard

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#9867]
These checks have gotten more expensive and now take more than 15s to complete on large customer instances. We should add Prometheus metrics to monitor each of them on k8s.sgdev.org so we can identify ones that may be unexpectedly slow.

https://sourcegraph.com/github.com/sourcegraph/sourcegraph@855765631d4c8236ed6f5efcc7a356ffca9a84fa/-/blob/cmd/frontend/internal/app/pkg/updatecheck/client.go#L139-220

Once implemented, measure and start a discussion about whether or not the current speeds are expected or not.

**Comment by dadlerj** [comment]
This can be reproduced on Sourcegraph.com : https://sourcegraph.com/site-admin/updates

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by slimsag** [comment]
Next steps:

- [ ] Display this information in a dashboard via [the monitoring generator](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/tree/monitoring)
- [ ] Add logging to the same points monitoring points as in https://github.com/sourcegraph/sourcegraph/pull/10464

**Comment by daxmc99** [comment]
I'm still planning to add metrics to this area but we may no longer need to collect metrics here per @dadlerj 's comment 
https://github.com/sourcegraph/sourcegraph/blob/9d56df7477c0d84040f25a0b19d737617dc033e5/cmd/frontend/internal/app/pkg/updatecheck/client.go#L186-L190

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by daxmc99** [comment]
While #11594 adds monitoring for this, this issue is not fixed until we determine what functions need additional refactoring to reduce the overall time to send data for an `updatecheck`.  Furthermore, `src_updatecheck_*` continues to be some of our highest cardinality metrics (over 100) so we should consider removing or scaling back monitoring in this area in the future.
