### ISSUE TITLE
src-expose: document usage with docker compose and kubernetes

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#9884]
Write two short sections at the end of the https://docs.sourcegraph.com/admin/external_service/non-git docs titled Using src-expose with a Docker Composes deployment and Using src-expose with a Kubernetes cluster deployment.

Those sections could be short, or link to Ryan’s repo, but should cover the tradeoffs of different ways of doing it (e.g. if they just SSH in and run it alongside Sourcegraph, what happens if the system restarts? Etc.)

Docker and Kubernetes examples for using src-expose at https://github.com/sourcegraph/src-expose-demo/

Note: avoiding modifying docker compose file is preferred. 

Context: https://sourcegraph.slack.com/archives/CJX299FGE/p1586472552293000

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by keegancsmith** [comment]
This is another task I haven't got bandwidth for. Not sure who is more appropriate to tackle it though.

**Comment by abitrolly** [comment]
I tried with `podman` but couldn't get the containers to communicate - https://gist.github.com/abitrolly/247568f07790f69abb2300e1fdab82cb
