### ISSUE TITLE
proposal: indexed search uses shallow git clones

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#9888]
Parent issue: https://github.com/sourcegraph/sourcegraph/issues/6728

Zoekt currently relies on archives of git repositories to do its indexing. Instead of relying on archives, we can use shallow clones. This is motivated as a way to avoid complications around git archives and multiple branches I encountered while doing https://github.com/sourcegraph/sourcegraph/issues/7930

Two approaches:

-   Clone just for indexing. Can increase complexity by adding in some caching to avoid needing to refetch objects. This has some nice properties for fast moving repositories at the cost of simplicity.
-   Maintain a global set of clones. Can then just use the standard zoekt repository indexing tooling which is quite nice. Cost is disk space, benefit is simplified code / decoupling.

I'm looking for some input around the viability of this approach, especially the cost of requiring larger disks in the second approach.

We will also need to add endpoints to allow us to clone. We used to have these and it isn't too much work to add back.

Notes on how I tested this approach:

```shell
export REMOTE=file:///Users/keegan/go/src/github.com/sourcegraph/sourcegraph
mkdir target.git
# just clones HEAD
git clone --bare --depth 1 "$REMOTE" target.git
cd target.git
# for each branch we want we add it to the fetch specs
for branch in develop test; do
  git config --add remote.origin.fetch "+refs/heads/$branch:refs/heads/$branch"
done
# This will now fetch each of the above branches only
git fetch --depth 1
# you can just use the upstream zoekt-git-index tool
zoekt-git-index -submodules=false -incremental -branches HEAD,develop,test .
```

The main divergence in the index produced is we no longer refer to the branch as HEAD, instead zoekt-git-index will resolve it to the actual branch name. This will break assumptions made in our frontend. Probably easier to patch zoekt-git-index to keep the HEAD name.

cc @sourcegraph/core-services

**Comment by keegancsmith** [comment]
> I'm looking for some input around the viability of this approach, especially the cost of requiring larger disks in the second approach.

@slimsag @beyang are there any customers where indexed-search using more disk space is a concern? I would safely say double disk usage (in practice likely a third more disk space required).

**Comment by unknwon** [comment]
> The main divergence in the index produced is we no longer refer to the branch as HEAD, instead zoekt-git-index will resolve it to the actual branch name. This will break assumptions made in our frontend. Probably easier to patch zoekt-git-index to keep the HEAD name.

Just to clarify, by "HEAD", you mean the default branch (often "master")? 

If so, when we use the "shallow clone" approach, what happens when the HEAD changes? I guess this is not a problem right now because we only have "HEAD" and give zoket an archive which has no sense of "branch". While zoket refers to actual branch names, we probably should substitute "HEAD" to the actual default branch then pass it to zoket.

**Comment by keegancsmith** [comment]
>> The main divergence in the index produced is we no longer refer to
>> the branch as HEAD, instead zoekt-git-index will resolve it to the
>> actual branch name. This will break assumptions made in our
>> frontend. Probably easier to patch zoekt-git-index to keep the HEAD
>> name.
>
> Just to clarify, by "HEAD", you mean the default branch (often
> "master")?

Yes. FYI "HEAD" is your "default branch" in
git. https://git-scm.com/docs/gitglossary#def_HEAD and
https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefsymrefasymref

> If so, when we use the "shallow clone" approach, what happens when the
> HEAD changes? I guess this is not a problem right now because we only
> have "HEAD" and give zoket an archive which has no sense of
> "branch". While zoket refers to actual branch names, we probably
> should substitute "HEAD" to the actual default branch then pass it to
> zoket.

When you say "HEAD" changes, do you mean there is a new commit or that
the symbolic ref "HEAD" changes to point to a different branch? In
either case if we continue to refer to it as "HEAD" it will do the right
thing when indexing. The issue comes in that when doing a search request
we don't know what the symref resolves to. Right now Zoekt will say it
indexed HEAD, so we don't need to know that. Naively switching to
zoekt-git-index will mean it will say "master" (or whatever HEAD
is). When we have multiple branches we won't know which one is HEAD.

So the simple change is to make "zoekt-git-index" not resolve the
reference. The likely better change is updating the Zoekt API to
indicate if a branch is the HEAD branch.

**Comment by unknwon** [comment]
> When you say "HEAD" changes, do you mean there is a new commit or that the symbolic ref "HEAD" changes to point to a different branch?

Yeah I mean "the symbolic ref "HEAD" changes to point to a different branch".

>  In either case if we continue to refer to it as "HEAD" it will do the right thing when indexing.

That's good to know :+1:

>Naively switching to
zoekt-git-index will mean it will say "master" (or whatever HEAD
is). When we have multiple branches we won't know which one is HEAD.
>....
>The likely better change is updating the Zoekt API to
indicate if a branch is the HEAD branch.

Don't we know HEAD on gitserver side? (but requiring an RPC to gitserver on every search is not ideal, or update the HEAD/default_branch on repo table after every pull on the gitserver).

With that said, making Zoekt API indicate "if a branch is the HEAD branch" feel pretty nice and performant.

**Comment by keegancsmith** [comment]
> Don't we know HEAD on gitserver side? (but requiring an RPC to
> gitserver on every search is not ideal

Yup that is exactly the problem, we would need to RPC for every git
repo.

> or update the HEAD/default_branch on repo table after every pull on the gitserver).

We don't have any infrastructure in place for doing that / keeping it up
to date. (yet) Additionally if we did do this there will be times when
zoekt thinks HEAD is something else until it reindexes. So easier to
rely on zoekt for now.

**Comment by slimsag** [comment]
Thoughts:

1) Do shallow clones introduce any bookkeeping we might be forgetting about? e.g. do we shallow clean fresh each time, or do we keep them around and need to `git gc` etc.?
2) What is the reason that shallow clones would take 1/3-2x more disk space than archives? I'm not sure I follow the reasoning for this. Is it because archives are compressed, or something else?

> @slimsag @beyang are there any customers where indexed-search using more disk space is a concern? I would safely say double disk usage (in practice likely a third more disk space required).

This is an interesting question and the simple answer is: I don't know, nobody knows. The questions this raises are:

1) What happens when zoekt runs out of disk space? How do we handle that today? Scenarios:
  - Someone blindly upgraded and didn't know it required more disk space, now XYZ bad things are happening and they immediately need to recover. What do they do? (they probably can't downgrade due to DB migrations, right?)
  - Someone reports XYZ bad things are happening (searches are slow, searches are missing results, something else that might be caused by this), how easy is that to attribute back to them not having enough disk space?
2) Do we have sufficient instructions for how someone would expand their zoekt k8s volumes in production with minimal downtime easily?
3) What happens in sourcegraph/server and Docker Compose instances when it runs out of disk space (much worse I imagine? Given "every service" is now out of disk space)
4) How do we / can we prevent admins from upgrading without knowing the risks here
5) Is all of the above worth the value we get out of this change (I honestly am not sure I understand the value tradeoff here, so this is a real question not a loaded question where I am saying I think it isn't)

If you can answer the above that would be helpful and I could give more educated advice here

**Comment by keegancsmith** [comment]
> 1) Do shallow clones introduce any bookkeeping we might be forgetting
> about? e.g. do we shallow clean fresh each time, or do we keep them
> around and need to `git gc` etc.?
> 2) What is the reason that shallow clones would take 1/3-2x more disk
> space than archives? I'm not sure I follow the reasoning for this. Is
> it because archives are compressed, or something else?

In the proposal above I gave two options of how we do this. In one case
we keep the shallow clones in-between indexes. This would imply much
more disk space use + some potential extra bookkeeping. But this would
have some other benefits as mentioned above.

The alternative is to treat it like we did archives, and clone when
indexing. This is also good, and likely how I would first implement
it. This wouldn't have extra space requirements (on top of needing to
clone vs archives which is done purely via streaming).

> This is an interesting question and the simple answer is: I don't
> know, nobody knows. The questions this raises are:

Ok, then I will be conservative and not keep shallow clones around.

> 1) What happens when zoekt runs out of disk space? How do we handle
> that today?

We recently added a prometheus metric for that. But yes this has
happened in the past and we just stop indexing. The read path isn't
affected though. I don't think it has happened since we made it have
much smarter garbage collection. We now claim "trash" shards if we are
running low on space I believe. But we need to do better here.

> 2) Do we have sufficient instructions for how someone would expand
> their zoekt k8s volumes in production with minimal downtime easily?

This is deployment dependent. But generally growing a disk is easy :)
Alternatively you can also increase the number of replicas to decrease
disk space.

> 3) What happens in sourcegraph/server and Docker Compose instances
> when it runs out of disk space (much worse I imagine? Given "every
> service" is now out of disk space)
> 4) How do we / can we prevent admins from upgrading without knowing
> the risks here

We need to do better here. One of the original use cases of the admin
notification area in the top was for disk space. We still need to
actually implement that :)

> 5) Is all of the above worth the value we get out of this change (I
> honestly am not sure I understand the value tradeoff here, so this is
> a real question not a loaded question where I am saying I think it
> isn't)

Yeah this is why I wanted input. There are two options, the one option
doesn't have the concern around disk space. This is all around enabling
us indexing more than just the HEAD branch, which is important.

**Comment by beyang** [comment]
> @slimsag @beyang are there any customers where indexed-search using more disk space is a concern? I would safely say double disk usage (in practice likely a third more disk space required)

I would say the answer is, in general, no. Disk is relatively cheap and as you stated earlier, we can increase the shard count if necessary. We just need to state clearly the risks in the CHANGELOG notes along with a link to docs describing what to look out for and do if the disk size must be increased.

**Comment by keegancsmith** [comment]
I added a way to do internal git clones which support shallow clone in #10278.

I've just tested this in production and it validates we should go forward with this. So I am closing this out and you can follow along in #6728. See below for notes on my investigation:

Shallow git clone is much slower, but still fast. I tested in production with the sourcegraph/sourcegraph repo. Fetching the archive takes about 0.75s, while a shallow clone takes 2.3s. This is insignificant compared to the time it will take to index, so I believe this change makes sense going forward.

First surprise, now that our containers aren't root you can't install additionally tools easily. kubectl exec doesn't support passing in a user flag, so have to ssh into the node and docker exec into the container&#x2026;

```shell
gcloud compute ssh gke-dot-com-dot-com-93160456-5dwm
sudo -i
docker ps | grep zoekt-index
docker exec -it -u root 7820f7d53b36 /bin/sh -il
apk add --no-cache git
```

Had to force deploy-sourcegraph to deploy frontend changes. Then realised gitserver is only deployed once a week, so needed to force an update and deploy of that.

Now I can actually try cloning out

```shell
kubectl exec -it indexed-search-1 -c zoekt-indexserver -- /bin/sh -il
cd /data
mkdir tmp
cd tmp
git -c protocol.version=2 clone --depth=1 --bare "$SRC_FRONTEND_INTERNAL/.internal/git/github.com/sourcegraph/sourcegraph"
curl "$SRC_FRONTEND_INTERNAL/.internal/git/github.com/sourcegraph/sourcegraph/resolve-revision/HEAD"; echo
curl -L "$SRC_FRONTEND_INTERNAL/.internal/git/github.com/sourcegraph/sourcegraph/tar/33880a51d811bb9c68b065997a9e1db6defb18cf" > HEAD.tar

du -hs HEAD.tar sourcegraph.git
# 61.4M   HEAD.tar
# 18.6M   sourcegraph.git

# Test fetching more branches
cd sourcegraph.git
git -c protocol.version=2 fetch --no-tags --depth=1 origin 3.15 v3.14.1
du -hs .
# 22.4M   .

# Instead of refs, probably better to specify commits. That works!
git -c protocol.version=2 fetch --no-tags --depth=1 origin 8038171c0a43f10c90be7d98eb8ce1754a41cf2d 9f1796c4b6b0301f775aa7e30a9f0c4354baf842

# Get some samples of timing
for i in `seq 1 10`; do rm -rf sourcegraph.git; time -f %e git -c protocol.version=2 clone --quiet --depth=1 --bare "$SRC_FRONTEND_INTERNAL/.internal/git/github.com/sourcegraph/sourcegraph" > /dev/null; done
# 2.45
# 2.38
# 2.46
# 2.26
# 2.30
# 2.25
# 2.31
# 2.38
# 2.41
# 2.36

for i in `seq 1 10`; do time -f %e curl -Ls "$SRC_FRONTEND_INTERNAL/.internal/git/github.com/sourcegraph/sourcegraph/tar/33880a51d811bb9c68b065997a9e1db6defb18cf" >
 HEAD.tar; done
# 0.86
# 0.70
# 0.70
# 0.70
# 0.77
# 0.73
# 0.72
# 0.76
# 0.76
# 0.73
```

First interesting insight is we have to use protocol version 2 for our shallow clones. Will probably want to debug that just incase we regress on that. The version of git on zoekt containers has yet to default to v2.
