### ISSUE TITLE
Hot reloading fails due to Reach Portal in MenuButton

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#9889]
Repro: 
1. Edit a component, save.
2. Wait for browser to refresh.
3. See error `Cannot read property 'ownerDocument' of null`

It comes from Reach Portal, which is used in the MenuButton component in the ActivationDropdown. 

I think it's coming from this effect hook in the reach menu button: 
https://sourcegraph.com/github.com/reach/reach-ui@master/-/blob/packages/menu-button/src/index.tsx#L453-458

When hot reloading occurs, some DOM nodes get unmounted, including the ownerDocument of the Portal component. So when hot reload happens, and it tries to remove (or add) the eventListener, it fails.

**Comment by felixfbecker** [comment]
I'd file this on Reach UI if there is no issue yet (and maybe do a PR to fix it if it's clear)

**Comment by felixfbecker** [comment]
@attfarhan is this fixed?
