### ISSUE TITLE
jaeger images must be versioned alongside sourcegraph

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#9893]
These were added last-minute and must be versioned alongside Sourcegraph.

https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/94

https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/deploy-sourcegraph%24+sourcegraph/jaeger&patternType=literal#4

**Comment by uwedeportivo** [comment]
fixed using same re-tagging as redis and others
