### ISSUE TITLE
[ci] our database backcompat tests have been broken for a while 

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#9921]
https://github.com/sourcegraph/sourcegraph/blob/ded9b7c556251e3e85175d56851739bacc62e255/dev/ci/db-backcompat.sh#L67

Our database back compat script looks for all packages that import `cmd/frontend/db/dbtesting`, but the `cmd/frontend/db/dbtesting` package hasn't exist for a while. It was extracted out and renamed to https://github.com/sourcegraph/sourcegraph/tree/master/internal/db/dbtesting as part of the management console work. 

This implies that this test has been **broken for over a year**. Going forward, we should add check to this script to make sure that at least one package is returned from that query.

**Comment by slimsag** [comment]
Thanks for finding this!

**Comment by unknwon** [comment]
Wow.... nice find!
