### ISSUE TITLE
Update and expand the code intelligence team roadmap

### ISSUE THREAD

**Issue by creachadair** [sourcegraph/sourcegraph#9922]
Our current [team roadmap](https://docs.google.com/document/d/1cBsE9801DcBF9chZyMnxRdolqM_1c2pPyGQz15QAvYI/edit#heading=h.dimwsc9ccmwq) is out-of-date. 

In addition, during our recent [discussion on planning & organization](https://docs.google.com/document/d/16IyVmOgYGJ06xfZFgt3zEXVdak6h6UaDOIZ5lcBBdEQ/edit) we identified a need to document a higher level view of our plans. What we call a "Roadmap" today is a list of work items, some of which are concretely tied to product deliverables and some of which are more aspirational. 

I wrote https://github.com/sourcegraph/about/pull/784 as a first attempt at documenting some of our higher-level aspirations, but I think we should probably expand on this also.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by efritz** [comment]
Closing. Will re-discuss in this week's code intel sync.
