### ISSUE TITLE
jetbrains editor configuration

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#9925]
reminder for me to resolve this PR and not let it go stale: https://github.com/sourcegraph/sourcegraph-jetbrains/pull/13

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by slimsag** [comment]
Added the relevant sourcegraph-side changes in:

- https://github.com/sourcegraph/sourcegraph/pull/10586
- https://github.com/sourcegraph/sourcegraph/pull/10654

Still some work to do on the plugin side, but closing this for now.
