### ISSUE TITLE
Sourcegraph.com gitserver echo test duration regularly exceeds several seconds

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#9926]
On Sourcegraph.com the gitserver `echo` command duration is regularly very abnormally high.

This may be related to https://github.com/sourcegraph/sourcegraph/issues/9355 and may be a partial cause in search performance on Sourcegraph.com being regularly poor https://github.com/sourcegraph/sourcegraph/issues/9359

Over [the last 15 days](https://sourcegraph.com/-/debug/grafana/explore?orgId=1&left=%5B%22now-15d%22,%22now%22,%22Prometheus%22,%7B%22expr%22:%22max(src_gitserver_echo_duration_seconds)%22%7D,%7B%22mode%22:%22Metrics%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D) it has peaked over 1s regularly:

![image](https://user-images.githubusercontent.com/3173176/79515860-97988f80-7ffe-11ea-8962-1447a95efd86.png)

In stark contrast, [on k8s.sgdev.org over the last 15 days](https://k8s.sgdev.org/-/debug/grafana/explore?orgId=1&left=%5B%22now-15d%22,%22now%22,%22Prometheus%22,%7B%22expr%22:%22max(src_gitserver_echo_duration_seconds)%22%7D,%7B%22mode%22:%22Metrics%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D) this has not once exceeded 125ms:

![image](https://user-images.githubusercontent.com/3173176/79515936-c6af0100-7ffe-11ea-93e3-cdfba1709761.png)
 
I also checked a customer instance, and similarly there not once above 125ms in the last 15d.

cc @sourcegraph/core-services

**Comment by keegancsmith** [comment]
Likely a sign that we need to give more CPU to gitserver. This has happened at customers before and the addition of more CPU usually resolves it.

**Comment by slimsag** [comment]
Indeed, scaling gitserver with 2x as many replicas appears to have solved this:

![image](https://user-images.githubusercontent.com/3173176/86196579-5fd2bb80-bb08-11ea-8970-ecd8a24edc89.png)
