### ISSUE TITLE
search UI should be clear when forks or archived repositories were excluded

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#9928]
A user at https://app.hubspot.com/contacts/2762526/company/407948923 complained that they were not seeing expected results. This was due to the fact that forks are no longer included by default as of 3.14.

I think it is reasonable that this might surprise some users and lead to a negative impression ("sometimes it doesn't show results that bitbucket's search does") so we should be clear about e.g. how many forks were excluded and the fact that you can add `fork:yes` to include them. The same should go for archived repositories.

cc @christinaforney for prioritization

**Comment by rvantonder** [comment]
This wasn't entirely overlooked--An alert was added to pick up on this in some instances https://github.com/sourcegraph/sourcegraph/pull/8739#issuecomment-596789339. But this only happens when No repos are resolved. Because, if some repos were resolved, we'd have no way to tell whether that's what the user intended, or not.

Would you say this is in good support of alerts and results? :-) #9745

**Comment by slimsag** [comment]
We indicate three items in this same category today in the UI already:

https://sourcegraph.com/github.com/sourcegraph/sourcegraph@610d1eac7a81a68f595f5d1fe2a86f469f26965f/-/blob/cmd/frontend/graphqlbackend/schema.graphql#L1340-1359

How the UI communicates them today:

https://sourcegraph.com/search?q=repo:sourcegraph+errorf+timeout:100ms&patternType=literal

![image](https://user-images.githubusercontent.com/3173176/81248627-a22cc000-8fd1-11ea-8794-62b81daa08ba.png)

I am all in favor of making this more consistent, uniform in the GraphQL API itself, etc. But I think it would also be enough to perhaps do one of the following:

- Add an "excluded" list of repositories similar to `missing`, `cloning`, `timedout` today
- Include only archived / forks in that `excluded` list, and document that.
- Have the UI render "N repositories excluded (forks/archives)"

**Comment by slimsag** [comment]
I imagine the above would be pretty easy to do by copying existing code for `missing` repos, for example

**Comment by slimsag** [comment]
Given https://github.com/sourcegraph/sourcegraph/issues/10313#issuecomment-624994250 I would like to see this issue prioritized (just any basic indicator to prevent the issues noted in that thread)

**Comment by rvantonder** [comment]
> Would you say this is in good support of alerts and results? :-) #9745

**Comment by rvantonder** [comment]
My proposal at this point is, in turn, to request we bump priority on #9745 to surface results and alerts. Should be a straightforward web change.

**Comment by rvantonder** [comment]
Missed the comment about GQL. I'm more in favor of the above than making changes to the existing GQL entries, because then we can just rely on the UI always surfacing it and we wouldn't have to have an extra step like

> Have the UI render "N repositories excluded (forks/archives)"

But, I suppose that would also work.

**Comment by keegancsmith** [comment]
Alternatively we could revisit this decision, and rather than excluding we use some naive ranking which puts normal repos > forks > archived.

**Comment by slimsag** [comment]
Bumping priority on https://github.com/sourcegraph/sourcegraph/issues/9745 makes sense to me 👍

> Have the UI render "N repositories excluded (forks/archives)"

My suggestion for this is just because it is likely quicker than #9745 to implement, since it would be mostly copying existing code. Granted, I am in full agreement that is not the best long-term solution.

> Alternatively we could revisit this decision, and rather than excluding we use some naive ranking which puts normal repos > forks > archived.

Ranking would work, but I suspect may be hard to implement. See also my comment here about revisiting the decision more broadly: https://github.com/sourcegraph/sourcegraph/issues/10313#issuecomment-625451535

**Comment by rvantonder** [comment]
I'll own this and prioritizing now. Either via GQL changes as excluded list or alerts with results, depending on complexity. I'm going to shoot for doing #9745 first. 

As for ranking, I think it's a nice-to-have but possibly more complex, but more significantly, it also would only apply in a setting where forks are included, and Stephen and I are agreed after some discussion that there are major challenges for revisiting the decision to the extent of reintroducing fork inclusion by default, as per https://github.com/sourcegraph/sourcegraph/issues/10313#issuecomment-625451535 and #10482

**Comment by rvantonder** [comment]
@slimsag this is what it'd look like so far, which I think is what you proposed above:

![Screen Shot 2020-05-12 at 4 35 18 PM](https://user-images.githubusercontent.com/888624/81755855-ccb5c780-946e-11ea-9f78-0bf812a87e66.png)

Question: is this, in your opinion, overt enough? I can do the bigger Info search alert too, but I feel like that version of it is tooo big. I feel like the current one is just a tad subtle (would be nice to make it a brighter color maybe?), and the alternative big search alert is overkill (and likely to crop up often, so it adds clutter).

**Comment by rvantonder** [comment]
Or some less subtle but not crazy icon color? Just pitching an idea, I realize this needs to take into account our themes and things.

![Screen Shot 2020-05-12 at 4 43 52 PM](https://user-images.githubusercontent.com/888624/81756151-cbd16580-946f-11ea-9bfe-ddc7806b6626.png)

**Comment by slimsag** [comment]
This looks perfect! Two things:

1. Remove `(add fork:yes to include forks)` and instead just have this information be present upon hovering over it.
2. Make sure there is a similar one for `1 archived repository excluded` OR make it `N repositories excluded` and then explain # of archives/forks in hover tooltip.

I do NOT think you need to make this more visible than in your first screenshot, since the most common / worrying case here is "I know the result exists but it is literally not on this page" at which point users will look around for an explanation out of habit (or we can redirect them to it in support).

Anything more red/alert/dangery looking appears like this is not normal, which is not what we want to communicate here.

**Comment by rvantonder** [comment]
>  instead just have this information be present upon hovering over it.

The current on-hover will list the excluded repos. That will deviate from the current `missing` and `cloning` repos behavior, which just list the repos, and I'm just using that. I'm not sure how many changes I need to make to allow a suggestion, or if deviating is what we want (I'm personally indifferent, since I wouldn't have the inclination to hover on these).

> archived

Yes the plan is to have it separately mention 'archives excluded'. 

> ... Anything more red/alert/dangery looking appears like this is not normal, which is not what we want to communicate here. 

Kay

**Comment by slimsag** [comment]
My only worry is it being a little verbose when both are present which will happen in 90% of searches I imagine:

```
1 forked repository excluded (add fork:yes to include forks)   1 archived repository excluded (add archived:yes to include archives)
```

But that is nothing in the grander scheme of this immediate issue, so if ignoring that for now and dealing with it later helps you land this sooner that's A-ok by me!

**Comment by slimsag** [comment]
I would imagine not too hard to add an option to include a prefix string though, so it can be something like this on hover:

> add fork:yes to include forks
>
> Excluded:
> repo1 repo2 repo3 repo4 ...

**Comment by rvantonder** [comment]
Yeah it's not actually a problem to add it in hover and format things. We can wrap up this discussion when I put up the PR.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
