### ISSUE TITLE
Add integration tests for and/or queries

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#9937]
I've been manually testing inputs that should go in integration tests. We are transitioning away from e2e web tests, so I can't put these tests there. We need some testing infrastructure for this [RFC 142](https://docs.google.com/document/d/1LfCDPZZAkP4gFB0no-0Hb90EqMItnzv3YEb07B7WtrM/edit) but I'd like to happen in some way or form possibly sooner than that. It may come down to a simple Go binary that runs the queries against a sourcegraph URL until the more mature testing infra exists.

**Comment by rvantonder** [comment]
Part of #10712

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by rvantonder** [comment]
GH's linked pull request thing is so so borked. 

#10712
#10946
#11104
#11127
