### ISSUE TITLE
proposal: make prometheus metrics greppable

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#9941]
Right now most prometheus metrics are declared like this:

```go
var requestDuration = prometheus.NewHistogramVec(prometheus.HistogramOpts{
	Namespace: "src",
	Subsystem: "zoekt",
	Name:      "request_duration_seconds",
	Help:      "Time (in seconds) spent on request.",
	Buckets:   prometheus.DefBuckets,
}, []string{"category", "code"})
```

However, this makes it very hard to find the metric unless you know where it is declared. Even with our smarter search syntax coming, this is still difficult to search for (cc @rvantonder for advise on how to use structural search?)

I propose we instead stop using the `Namespace` and `Subsystem` fields, and just use the `Name` field. I have seen other projects do this, and it makes it very easy to grep. So the above would become.

```go
var requestDuration = prometheus.NewHistogramVec(prometheus.HistogramOpts{
	Name:      "src_zoekt_request_duration_seconds",
	Help:      "Time (in seconds) spent on request.",
	Buckets:   prometheus.DefBuckets,
}, []string{"category", "code"})
```

Assigning @uwedeportivo and @slimsag just so I can hear their thoughts on this. They don't need to do the transformation.

@mrnugget this looks like a fun campaign if we do decide to do this. How would I do this?

**Comment by mrnugget** [comment]
1. Go to `$SOURCEGRAPH_URL/campaigns/create`
2. Click `Create and track changesets`
3. Follow instructions to setup `src` CLI
4. Create an action definition that will search for `lang:go Opts{\s*Namespace: patterntype:regexp` and run Comby + `gofmt` over it:

```json
{
  "scopeQuery": "lang:go Opts{\\s*Namespace: patterntype:regexp",
  "steps": [
    {
      "type": "docker",
      "image": "comby/comby",
      "args": [
        "-in-place",
        "Namespace: \":[namespace]\", Subsystem: \":[subsystem]\", Name: \":[name]\"",
        "Name: \":[namespace]_:[subsystem]_:[name]\"",
        ".go",
        "-matcher", ".go",
        "-d", "/work",
        "-exclude-dir", ".,vendor"
      ]
    },
    {
      "type": "docker",
      "image": "golang:1.14-alpine",
      "args": ["sh", "-c", "cd /work && gofmt -w ./"]
    }
  ]
}
```
5. Check that results are returned by the `scopeQuery`: `src -v action scope-query -f  action.json`
6. If happy with the returned repositories: push. the. button!
```
src -v action exec -f action.json -create-patchset
```
7. Follow instructions to create a campaign.

If you did everything right, you should see something like this:


<img width="1537" alt="Screen Shot 2020-04-17 at 11 17 43" src="https://user-images.githubusercontent.com/1185253/79553645-12b08300-809d-11ea-96c6-22ecb1e5344b.png">

**Comment by keegancsmith** [comment]
> `"Namespace: \":[namespace]\", Subsystem: \":[subsystem]\", Name: \":[name]\"",`
>  `"Name: \":[namespace]_:[subsystem]_:[name]\"",`

Woah comby is cool! Out of interest do we require the fields to be specified in that order? Will try out campaigns for this :)

**Comment by mrnugget** [comment]
> Out of interest do we require the fields to be specified in that order?

Do you mean whether we require that in our Go code or whether we require that with Comby? If it's the second: I'm not 100% sure, but I don't think Comby supports "position-independent matching of terms" or something like that :)

If it's the first: you could simply run Comby multiple times in the same repository, with different order of the match params.

**Comment by keegancsmith** [comment]
Thorsten Ball <notifications@github.com> writes:

>> Out of interest do we require the fields to be specified in that order?
>
> Do you mean whether we require that in our Go code or whether we require that with Comby? If it's the second: I'm not 100% sure, but I don't think Comby supports "position-independent matching of terms" or something like that :)
>
> If it's the first: you could simply run Comby multiple times in the same repository, with different order of the match params.

This is comby specific and I don't want to detract too much from the
discussion around this proposal (my bad for asking above). I was
wondering if comby did the matching independent of order (since go
fields can be in any order). If it doesn't, I agree I would just run the
query for all permutations of the order (which isn't a big deal).

**Comment by unknwon** [comment]
@mrnugget that was quick and cool! (Comby hacker)

I like this proposal 👍

**Comment by uwedeportivo** [comment]
we also have https://github.com/sourcegraph/promgrep :-). not saying it's perfect but i use it (especially in the Goland terminal where the results are clickable)

**Comment by slimsag** [comment]
Yes, I am very much in favor of this proposal. I think that `Namespace` and `Subsystem` are only particularly useful when you aren't operating in a monorepo and thus there is larger chance for accidental overlap of metrics.

One challenge, though, is that we're recently introducing many dynamically-generated Prometheus metric names. Maybe we should avoid that?

- https://sourcegraph.com/github.com/sourcegraph/sourcegraph@046b2c861c3846c136abef34df058d7e33c4145b/-/blob/internal/db/dbconn/dbconn.go#L197-211
- https://github.com/sourcegraph/sourcegraph/pull/9920/files
- I recall there being a really large number somewhere in code host rate limiting? I couldn't find them though

**Comment by keegancsmith** [comment]
> One challenge, though, is that we're recently introducing many
> dynamically-generated Prometheus metric names. Maybe we should avoid
> that?

I don't think we necessarily need to prevent it, but I can't think of
many cases where we would prefer generating the metric name vs setting
of a label.

> https://sourcegraph.com/github.com/sourcegraph/sourcegraph@046b2c861c3846c136abef34df058d7e33c4145b/-/blob/internal/db/dbconn/dbconn.go#L197-211

That looks like it just registers one metric, so we should probably just
directly declare that? Additionally we probably want the db name as a
label rather than a metric name.

> - https://github.com/sourcegraph/sourcegraph/pull/9920/files

This too should just set a label which is service.


> - I recall there being a really large number somewhere in code host
> rate limiting? I couldn't find them though

Some quick searching I didn't come across this. But these sound like
things that could also be differentiated by labels.

Thanks for linking to those!

**Comment by unknwon** [comment]
From my observation this is already achieved? Please re-open if anyone thinks there is remaining work to be done.
