### ISSUE TITLE
TypeScript cross-repository go to definition broken with LSIF

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#9952]
### Actual

- Go to https://sourcegraph.com/github.com/sourcegraph/about/-/blob/website/src/components/Header.tsx
- Hover over `Link` in the first line
- Get no hover or go to definition

### Expected

As an example of what would be expected, this is how the language server behaves:
- Add to your user settings:
  ```json
  "codeIntel.lsif": false,
  "typescript.serverUrl": "wss://typescript.sourcegraph.com"
  ```
- Navigate to https://sourcegraph.com/github.com/sourcegraph/sourcegraph-typescript/-/blob/src/tracing.ts
- Hover over `Span` in the first line
- Wait for dependency installation to finish (this would not be expected for LSIF of course 🙂 )
![image](https://user-images.githubusercontent.com/10532611/79569825-a9d70400-80b8-11ea-89ac-5c6734c80ced.png)
- Hover again, click go to definition
- Get taken to https://sourcegraph.com/github.com/opentracing/opentracing-javascript@cb74683fefe5bd4d711eaa0c273f3fc17a6c3781/-/blob/src/span.ts#L11:1 
![image](https://user-images.githubusercontent.com/10532611/79570049-09cdaa80-80b9-11ea-8e1d-92ae29e0473c.png)

There are some special cases here that are considered too, like JS-only libraries that jump to the definition of the typings in https://github.com/DefinitelyTyped/DefinitelyTyped, or references to the standard library, that jump to the lib.d.ts in https://github.com/Microsoft/TypeScript (at the right TypeScript version)

**Comment by efritz** [comment]
LSIF can currently only jump to locations that are indexed, so if opentracing had an LSIF index cross-references should work.

This isn't unexpected behavior for the state we're at, but if you have behavioral or technical suggestions to bridge the gap in the meantime we'd be happy to hear it.

**Comment by felixfbecker** [comment]
Could the LSIF indexer use the information from node_modules to determine the target repo, commit, file and position like the language server does it? I wrote an overview of the algorithm back then here: https://github.com/sourcegraph/sourcegraph-typescript/issues/8#issue-379063436

The "resolve clone URL to repo URL using raw API" step would probably not be done by the indexer, but by the LSIF server or JIT by the code intel extension (not sure how it currently works for LSIF-to-LSIF xrepo j2d). The indexer would just do the steps of the algorithm necessary to produce the information necessary for LSIF's xrepo information encoding mechanism (package monikers etc).

**Comment by efritz** [comment]
I'm going to bring this up in team discussions and see what the effort/benefit ratio is. Currently I'd say the solution is to index more things! Pop a list of repos into the code-intel channel and we can add it to our auto-indexing effort. I think this is a particularly bad case on dot-com as it _can_ clone these dependencies, where most private instances won't have anything to jump to regardless.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by efritz** [comment]
Moving discussion of this request over to https://github.com/sourcegraph/sourcegraph/issues/9952.

**Comment by felixfbecker** [comment]
Is that really the root cause though? The repos I'd expect to jump to in the examples in the issue are all cloned on sourcegraph.com, it just seems the definition is not being mapped to those repos (see above for a proposal how that could work). Just showing the file content of a "virtual" file in node_modules, as opposed to jumping to the source repo, is probably not what the user wants, no?

**Comment by efritz** [comment]
Yes, the new issue covers _any_ case where RepoA depends on RepoB and RepoB doesn't have full information (either because of a missing index or because it's not cloned).

Correct, I'm trying to look for solutions that don't have virtual files where it's not completely necessary.
