### ISSUE TITLE
Alert if gitserver is failing to clone

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#9966]
From [customer](https://sourcegraph.slack.com/archives/CTGBWCKM0/p1587116264035000?thread_ts=1587056982.018800&cid=CTGBWCKM0): 

>  would it be possible to add alert for case when gitserver consistently fails to clone?

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
