### ISSUE TITLE
Propose and implement and/or queries in literal search

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#9968]
Given my context/development on and/or queries, I think there's a solid case for allowing a reduced form of and/or queries in literal search mode. 

- [x] Proposal: 0.5 days - [RFC 176](https://docs.google.com/document/d/11hJ12V996Edyo9mguWcVp_5qT5vpbq3hEdcOBhpLS58/edit#)
- [x] Implementation/testing if approved (+1.5 days)

**Comment by rvantonder** [comment]
At least these people experienced and/or queries not working in literal search and thought it was a bug/issue:
- Me
- Dan
- Ryan
- Joe

**Comment by rvantonder** [comment]
Self note: while working on this, realized potential downside that without parens, the precedence can't be overridden so if our default behavior is `repo:foo repo:bar foobar` => `repo:foo and repo:bar foobar` there is no way to change this. So we'll need to alert or suggest alternatives as needed.

**Comment by slimsag** [comment]
You can add me to that list.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
