### ISSUE TITLE
Improve documentation for and/or queries

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#9969]
I want us to have good documentation for and/or queries, including a railroad diagram of the grammar and examples.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
