### ISSUE TITLE
Promote visibility of structural search at customers

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#9970]
This is something I've been putting off for a long time and it really deserves attention. There are a bunch of customers that could benefit from this feature already, but it needs some initial momentum. This mostly involves coming up with example searches for conventions or buggy patterns.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by rvantonder** [comment]
Closing in favor of #12767
