### ISSUE TITLE
Refine and/or query validation for different searches

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#9971]
One piece of validation that is preserved in and/or queries is detecting whether a field exists. For example, `blahblah:value` will raise an alert that `blahblah` does not exist. This is fine for regex search mode, but in structural search, the pattern `blahblah:[hole]` is quite common, and here we'll raise an alert. This effectively means that all structural search queries need to be quoted, which is annoying. I want to remove this validation for structural search, but not regex mode (unless there are good reasons to do so for regex too). It'll make it a lot more usable.

Currently, the search-specific validation (e.g., ensure that `case` cannot be set with structural search) has not been migrated yet.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by rvantonder** [comment]
Note to self: @ggilmore ran into this usability issue.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
