### ISSUE TITLE
Use comma delimiters in ThirdPartyLicensesGo.csv

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#9972]
Not urgent, but is a nice usability improvement:

ThirdPartyLicensesNpm.csv looks nicer due to GitHub formatting: https://github.com/sourcegraph/sourcegraph/blob/master/ThirdPartyLicensesNpm.csv

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
