### ISSUE TITLE
Automate creation of the Go third-party licenses CSV

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#9973]
### Background

Some customers need a list of the licenses of our dependencies for compliance and risk analysis reasons. There is currently no standard approach to automatically generate this list from a `go.sum`. 

The `ThirdPartyLicensesGo.csv` file we already have has been generated with https://github.com/mitchellh/golicense which produces an XLS file, then converted to CSV, then manually edited those entries for which it couldn't detect the license properly. This process doesn't scale.

While the generation of `ThirdPartyLicensesNpm.csv` is already automated because it is natively supported, it would perhaps be better to unify the production of these two lists with a more general tool like https://github.com/pivotal/LicenseFinder (which is used by [GitLab](https://docs.gitlab.com/ee/user/compliance/license_compliance/) for instance). This is however just a suggestion, not a strict requirement.

### Definition of success

The list of dependency licenses is generated automatically periodically. A pull request is opened by a script (GitHub Action?) with the diff, which should be reviewed carefully for non compliant licenses (perhaps we can define these programatically too).

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by tsenart** [comment]
I updated the description with sufficient context for @bobheadxi to pick this up.

**Comment by tsenart** [comment]
If you need further input, don't hesitate to ask though!

**Comment by slimsag** [comment]
Thanks @tsenart !

**Comment by bobheadxi** [comment]
> While the generation of ThirdPartyLicensesNpm.csv is already automated because it is natively supported

@tsenart do you mind clarifying this? does this refer to periodic updating of npm licenses, or specifically programmatic generation? if the latter, does this issue refer to automating the creation of both the Go and npm licenses, or just the Go ones?

If the npm licenses aren't currently automated to periodically update, I would expand the scope of this issue to cover both

**Comment by bobheadxi** [comment]
I tried https://github.com/pivotal/LicenseFinder and it seems to work very well and seems better supported than any of the Go-specific tooling I could fine - I would advocate for its adoption. By default it outputs all licenses in a single csv, would that work @dadlerj ? Might affect #11116

**Comment by dadlerj** [comment]
>@tsenart do you mind clarifying this? does this refer to periodic updating of npm licenses, or specifically programmatic generation? if the latter, does this issue refer to automating the creation of both the Go and npm licenses, or just the Go ones?

@felixfbecker added this. You can find it in the script I edited in #11116 !

Regarding which tool to use, I defer to @tsenart . I think the current one already outputs to a single Go dependencies file, doesn't it? I think that's ideal.

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
