### ISSUE TITLE
Implement and/or-expressions for file and repo search (AKA hierarchical search)

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#9974]
This task tracks initial exploration for expanding and/or queries to fully nested search. Wanted to start with this in 3.16, but don't think I'll have time.

Relates to #9712 and issues in #7823

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by rvantonder** [comment]
Subsumed by #11009.
