### ISSUE TITLE
Add ThirdPartyLicensesDistributedTools.csv

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#9975]
Add a file that lists the separate third-party tools that are distributed alongside Sourcegraph. This doc was previously named "ThirdPartyLicensesInfrastructure" if I recall correctly...

We should preface this doc with the following message:

>The following list contains open source software that is not compiled with Sourcegraph but is distributed to users as a separate program for use with Sourcegraph's official builds:

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you
