### ISSUE TITLE
Expose and/or query parsing result through GQL API

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#9979]
We should provide a way for clients to understand how a query was parsed/interpreted, given the relatively complex set of heuristics and fallbacks we apply. This will aid debugging and feature development of a web-side parser. The value should be returned in JSON format. Additionally, the same endpoint might return additional suggestions for potentially ambiguous queries. 

Clients, like the webapp, can in due time support a client-side parser, but given the current complexity of parsing and heuristics we do in the backend, this enpdpoint will fill a gap in the interim.

**Comment by rvantonder** [comment]
https://github.com/sourcegraph/sourcegraph/tree/rvt/expose-and-or-query-gql

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by rvantonder** [comment]
#11776
