### ISSUE TITLE
Prevent releasing server without latest grafana/prometheus changes

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#9983]
i.e. this PR should never have to be made: https://github.com/sourcegraph/sourcegraph/pull/9982

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.16 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by daxmc99** [comment]
I'm curious if renovate should be used here to automate this. 

I'm not familiar with renovate but I think it should be able to do this. 

https://github.com/sourcegraph/deploy-sourcegraph/pull/712

**Comment by daxmc99** [comment]
Plan to use https://github.com/slimsag/update-docker-tags/issues/1 in a Github Action instead of Renovate.

**Comment by felixfbecker** [comment]
Is there a reason we want to introduce a new tool for this instead of using Renovate? It seems like we'd then have two tools in our toolchain doing the same thing but through different configuration etc, but I'm probably missing some requirement here

**Comment by daxmc99** [comment]
I think there is some value to be gained from using something that has higher observability 
https://github.com/sourcegraph/sourcegraph/issues/10011

**Comment by slimsag** [comment]
I just wrote a full explanation of why we are moving away from Renovate for specifically our release process (and general Docker image tag updates) here: https://github.com/sourcegraph/sourcegraph/issues/10011#issuecomment-639953001

**Comment by bobheadxi** [comment]
@daxmc99 also I'll be putting up a PR for https://github.com/sourcegraph/sourcegraph/issues/10641 soon, which will depend on Grafana's alert provisioning format (https://grafana.com/docs/grafana/latest/administration/provisioning/#alert-notification-channels). Unless we introduce an abstraction on top of the notification configuration, it might be better to keep the Grafana version pinned as we do now

**Comment by slimsag** [comment]
Yes, agreed, anytime we upgrade Grafana we'll need to carefully consider if it breaks the alerting config or generated dashboard format. We'll need to put in place some tests (maybe just manual documented steps, including testing on k8s.sgdev.org and sourcegraph.com or something) for this.

**Comment by slimsag** [comment]
Filed https://github.com/sourcegraph/sourcegraph/issues/11358 for that.

**Comment by slimsag** [comment]
Thinking about this issue some more (this doesn't change anything anyone here is working on, all ongoing work here is still valuable in any case), I am wondering how hard it would be to:

1. In dev, don't rely on a baked image at all? e.g. maybe start with the baked image, but sideload all changes via a Docker volume mount OR `docker copy` them in as things change.
2. In server, build the image we include as part of `cmd/server/build.sh` - I think this will be needed anyway to ensure we ultimately have reliable builds that don't rely on an external process

**Comment by daxmc99** [comment]
👍 To allowing local builds to be a simpler process. I'm not entirely sure why we need to push to buildkite to make some images

**Comment by bobheadxi** [comment]
@daxmc99 heads up that #11427 will remove the baking in of the grafana image: https://github.com/sourcegraph/sourcegraph/pull/11427#discussion_r438993065

**Comment by daxmc99** [comment]
Looks good, I will take a look to see if I need to make any further changes

**Comment by uwedeportivo** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by daxmc99** [comment]
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by pecigonzalo** [comment]
@bobheadxi @daxmc99 do you think this can be closed?

**Comment by slimsag** [comment]
I believe this has been fixed, closing. Reopen if not.
