### ISSUE TITLE
Fix docs for LSIF option DBS_DIR_MAXIMUM_SIZE_BYTES

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#9987]
Reported by https://app.hubspot.com/contacts/2762526/company/2931649618

Our docs (https://docs.sourcegraph.com/user/code_intelligence/lsif#data-retention-policy) say:

>The bulk of LSIF data is stored on-disk, and as code intelligence data for a commit ages it becomes less useful. Sourcegraph will automatically remove the least recently uploaded data **if the amount of disk space falls below a configurable threshold**. This value defaults to 10 GiB (10⨉2^30 = 10737418240 bytes), and can be changed via the DBS_DIR_MAXIMUM_SIZE_BYTES environment variable.

But this is incorrect. The `DBS_DIR_MAXIMUM_SIZE_BYTES` reflects the maximum size of uploads on disk, not a minimum amount of extra  space required (as the bolded words above indicate).

**Comment by gbrik** [comment]
The hubspot link just goes to the company home page for me, is there a way to link directly to the communication about this issue?

**Comment by gbrik** [comment]
@efritz could you update the docs really quick? I'm not entirely clear on how this works myself.

**Comment by dadlerj** [comment]
>The hubspot link just goes to the company home page for me, is there a way to link directly to the communication about this issue?

Unfortunately this conversation happened in Slack. I can ask to have you join the channel if helpful?

Alternatively, if there's anything missing from the description/quote, just let me know and I can clarify.

**Comment by gbrik** [comment]
No need for this issue. Was half a general question as I click on a lot of hubspot links that don't directly go to the context, now I know it's because it lives in slack!

**Comment by slimsag** [comment]
Context: We put the hubspot links in issues so folks can see which customer reported the issue without disclosing their name (since this tracker is public)

**Comment by dadlerj** [comment]
See https://about.sourcegraph.com/handbook/support/filing_customer_issues for how to do this

**Comment by gbrik** [comment]
Makes sense, thanks!
