### ISSUE TITLE
Alert admins if LSIF uploads are too large for DBS_DIR_MAXIMUM_SIZE_BYTES

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#9989]
Reported by https://app.hubspot.com/contacts/2762526/company/2931649618

A user reported that their LSIF uploads page seemed to be oddly empty — a bunch of uploads processing, but zero "current" uploads appearing.

After reading our docs (and first being confused by https://github.com/sourcegraph/sourcegraph/issues/9987) he realized that disk space could be the problem:

>ok i'd guess we have to up ours, because we've enabled lsif on a separate repository, and uncompressed, our lsif is 7.2G

>so i'm guessing the decompression of a new lsif kicks the recently processed lsif out

So basically every successful upload would cause the previous one to be evicted. 

I know we don't have (as far as I know) any way to expose asynchronous errors to site admins, but this seems like a good use case for it. Perhaps in the meantime simply returning an error or warning from the LSIF upload endpoint if the compressed upload exceeds some percentage (e.g. 10%?) of the current `DBS_DIR_MAXIMUM_SIZE_BYTES`?

**Comment by gbrik** [comment]
How urgent do you think this is? I think the underlying issue is going to resolve itself because of other current efforts, but we could potentially add a stop-gap like that. We'll revisit towards the end of the milestone. 

Could you refile anything else in this issue you'd like to discuss further? I think for this particular use case the need for exposing async errors can be covered by #10083

**Comment by dadlerj** [comment]
>How urgent do you think this is? I think the underlying issue is going to resolve itself because of other current efforts, but we could potentially add a stop-gap like that. We'll revisit towards the end of the milestone.

Not super urgent. My concern is that while this env var is documented, but not called out as a key thing, and if it's not set appropriately, then things will just silently fail/be problematic. If you have another path to solving the underlying issue, though, then no rush.

**Comment by slimsag** [comment]
I'm not intimately familiar with the problem here, but if you can add a Prometheus metric for "failed uploads" or "uploads exceeding size of DBS_DIR_MAXIMUM_SIZE_BYTES" then it's trivial to add an alert to our monitoring that site admins would see in Grafana.

**Comment by slimsag** [comment]
Likely @efritz is already thinking of stuff along these lines, I presume

**Comment by gbrik** [comment]
Not sure about this whether we wanted to monitor this particular metric, but yeah we have a whole bunch of metrics + benchmarking + documentation in the pipeline that will avoid this kind of confusion. Going to close.
