### ISSUE TITLE
Make it easier for non-admins to find and get to commits with LSIF data

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#9990]
Requested by https://app.hubspot.com/contacts/2762526/company/2931649618

>oh sorry - one last thing. i was explaining how lsif only applies to 100 commits to a colleague, and he opinined it might be useful to have an indication of (1) whether a commit has lsif, and (2) if there's an easy way to jump to the newest commit with lsif available - for a non-administrator, the 2nd is surprisingly difficult

This issue is for both of the bullets above, as they sort of overlap... When I asked for the use case to know which UI this would be helpful in:

>so his use case was refactoring hairy interfaces without recompiling waiting to see what would fail
>
>so at a high level, he'd like to use 'show references' and see all of them at one go
>
>but he can't do that until he find a revision with LSIF

This is tough for this user for two reasons:
1. They are using C++, which has an issue where all hovers show the "basic code intel" indicator.
2. There is no way for a non-admin to see the list of the most recent commits that have LSIF data. 

There are multiple approaches to improve this experience. 

**One is simply making the repo's LSIF upload view visible to non-admins** (e.g. adding a new button like these that lists the LSIF uploads available:
![image](https://user-images.githubusercontent.com/5589410/79624758-c6833400-80d8-11ea-84a4-5365a1de996b.png)

**Another would be to add indicators to the existing "file history" or "commit list" UIs that show whether LSIF exists, e.g. at:**

![image](https://user-images.githubusercontent.com/5589410/79624774-da2e9a80-80d8-11ea-9cdc-b2ef7c7b9b72.png)

Or:

![image](https://user-images.githubusercontent.com/5589410/79624779-e1ee3f00-80d8-11ea-9191-0a1248341d8d.png)

Or:

![image](https://user-images.githubusercontent.com/5589410/79624785-ed416a80-80d8-11ea-8516-34d8a98bad43.png)

**And finally, another option would be to add a button like "jump to latest commit with LSIF"** — but this is a bit of a special case...

The last option here would be possible as an extension, by the way!

**Comment by gbrik** [comment]
I just saw this! It seems there's no way to get notifications for GitHub labels :( Maybe you could mention @sourcegraph/code-intel on issues that need our attention?

I've since filed #10083 and I think these proposals fall under that topic, let me know if you agree and I'll link it there and close this issue.

**Comment by dadlerj** [comment]
>I just saw this! It seems there's no way to get notifications for GitHub labels :( Maybe you could mention @sourcegraph/code-intel on issues that need our attention?

Thanks! I assumed that when I added the label, you were notified. 

>I've since filed #10083 and I think these proposals fall under that topic, let me know if you agree and I'll link it there and close this issue.

Agreed — that's issue's focus on end-users, rather than admins, is the key thing here. I'll close this as a duplicate.
